### ISSUE TITLE
Clarify pull request stance in Readme

### ISSUE THREAD

**Issue by af** [tmux/tmux#10]
Hi,

Now that Github is the primary repo for tmux, my initial assumption was that pull requests would be the preferred way to submit patches. Since [it is not](https://groups.google.com/forum/#!topic/tmux-users/rySuwnHcJJo), it would be nice to mention this in the readme. 

Even though the Readme does explicitly say "Patches should be sent by email to
the mailing list at tmux-users@googlegroups.com.", I can't be the only person that would assume PRs would also be welcome. If you don't want to receive them, a mention of this in the Readme would probably save you some time.

**Comment by bruno-** [comment]
Also an idea: github has a nice feature where "guidelines for contributing" will be visibly prompted to a user before he/she opens a new issue or pull request as described in [this blog post](https://github.com/blog/1184-contributing-guidelines).

All that's needed it to create a `CONTRIBUTING` file in the project root. This could probably filter out some percentage of impulsive issue or PR openings and reduce the maintenance burden on the maintainers.

**Comment by nicm** [comment]
Let's see what happens before jumping to add to the documentation.

And no more documentation files, we have too many already. README or not at all.

-------- Original message --------

**Comment by fatih** [comment]
Checkout https://github.com/golang/go which doesn't not accept Pull Requests. They have a `CONTRIBUTING.md` and don't use Pull Requests at all.

**Comment by aleksandrs-ledovskis** [comment]
Another option - just edit project description. Check [git/git](https://github.com/git/git) for example
