### ISSUE TITLE
Sync tmux panes only on Certain commands Executed

### ISSUE THREAD

**Issue by sivaswami** [tmux/tmux#1000]
Hi,

This is more of a question.

How can I synchronize 2 panes automatically of tmux only for Certain commands  like 'cd, ssh, etc'
any suggestions ? once those commands executed it should un-sync the panes automatically.

More like a pseudo-sync mode. #

**Comment by nicm** [comment]
You could write a shell script and alias all the command you want to fiddle with to it.
