### ISSUE TITLE
tmux 2.5 exits automatically on ssh logout (2.4 regression)

### ISSUE THREAD

**Issue by AaronVanGeffen** [tmux/tmux#1001]
Since I've upgraded tmux to 2.5, I've been having problems keeping a session open after I log out from my ssh session.

In an attempt to narrow it down, I tested this on a manually compiled version of the 2.4 tag (f21cb71fbe79c8949edc3c1d300aa783382a0d77). I've not been able to reproduce the problem on this version. However, I am able to reproduce it on HEAD at the time of writing, 05062e7d2d59a4e88c25d1d1a0b71ca97d74f8a3.

Initially, I thought this might be a systemd-related problem, as it would always happen as I logged out of my last pts. However, systemd was compiled with the infamous `KillUserProcesses` setting set to `no`, and both tmux-2.4 and screen-4.06 are unaffected.

**Steps to reproduce**

I can reproduce this using the following steps:

1. ssh to server
2. `$ tmux`
3. detach newly-created session (one window, just `bash`)
4. log out of server
5. ssh back into server
6. `$ tmux attach`
7. detach session again
8. log out of server
9. ssh back into server
10. `$ tmux attach` yields `no sessions`

The number of times I am able to attach and detach without issue seems to vary, but ultimately I get the `no sessions` message between three to five times.

**Log files**

I've reproduced the problem twice with tmux running in verbose mode. Hopefully, these logs provide you with some means to track down what's going wrong.

[Logs for tmux on first reproduction](https://github.com/tmux/tmux/files/1132987/attempt1.tar.gz)
[Logs for tmux on second reproduction](https://github.com/tmux/tmux/files/1132988/attempt2.tar.gz)

[My tmux configuration file](https://github.com/tmux/tmux/files/1132986/tmux.conf.txt)

**System details**

This happens for me on Arch Linux using either the linux-lts 4.9.36 or linux 4.11.9 kernels provided. systemd 233.75 is also installed.

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by nicm** [comment]
tmux is exiting normally so either it is being killed or there is a reference counting error.

**Comment by AaronVanGeffen** [comment]
Yes, it is still happening in 05062e7d2d59a4e88c25d1d1a0b71ca97d74f8a3.

Please let me know if there is more information I can provide you with.

**Comment by nicm** [comment]
Apply this to master then reproduce and show me the log please: [x.diff.txt](https://github.com/tmux/tmux/files/1134039/x.diff.txt)

**Comment by AaronVanGeffen** [comment]
Thank you. As for the logs: [attempt3.tar.gz](https://github.com/tmux/tmux/files/1134082/attempt3.tar.gz)

**Comment by nicm** [comment]
Why are you are including two server log files each time?

In any case,  attempt3/tmux-server-23962.log shows:

~~~~
1499634823.216801 server_signal: Terminated
1499634823.216805 session 0 destroyed (server_send_exit)
~~~~

So your tmux server is being sent SIGTERM.

**Comment by AaronVanGeffen** [comment]
Thank you for inspecting the logs. I do apologise for the inclusion of an unrelated server log — I'm not sure how that happened, but it's probably an error on my part.

With the help of a friend, I set up a basebones VPS to test with. I've bisected the issue to merge commit e354b0e40fe1be1e1f8977d424e02e6487039a56; I am unable to reproduce the issue on the preceding merge commit, 0adb60b3a6309f27947b1b2e70d63e8b61c57e1b.

Moreover, we were able to reproduce the issue without actually logging out of the SSH session. We discovered this by running `strace` on the tmux server process as the root user — tmux would output a successful detach message, while in reality the process quit altogether shortly after the output. We did not observe any SIGTERMs in the straces.

One more observation: running strace with either the `-f` or `-ff` flags set, monitoring child processes, lead to us not being able to reproduce the bug.

This is just speculation, but could it be that the issue arises due to a race condition?

**Comment by nicm** [comment]
Where are the strace logs...?

What makes you think it would be a race condition?

**Comment by nicm** [comment]
Make sure you are strace'ing a server started with -vvv so you have corresponding tmux and strace logs, so do something like:

$ tmux -vvvvLtest new -d
$ tmux -Ltest display -p '#{pid}'
4415
$ strace  -tttostrace.out -p4415

Then reproduce the problem. When tmux and strace exit, send me the tmux-server-$PID.log file and the strace.out file.

**Comment by AaronVanGeffen** [comment]
> Where are the strace logs...?

Here are yesterday's logs:
[strace_attempt1.txt](https://github.com/tmux/tmux/files/1141107/strace_attempt1.txt)
[strace_attempt2.txt](https://github.com/tmux/tmux/files/1141108/strace_attempt2.txt)

Just saw your other message, I'll do another run with increased verbosity.

> What makes you think it would be a race condition?

Our hypothesis was that, because strace effectively slows down the syscalls slightly, it introduces enough delay when tmux is sent SIGCHLDs.

**Comment by nicm** [comment]
~~~~
read(3, "\21\17", 1024)                 = 2
~~~~
I think this is the libevent signal pipe. 021 is 17 which is SIGCHLD. 017 is 15 which is SIGTERM.

What libevent version are you using?

**Comment by nicm** [comment]
Are you using a libevent 2.1 from before https://github.com/libevent/libevent/commit/ad0c237bc0b2edd4f1dc0e82c6cffbde71bad78b?

**Comment by AaronVanGeffen** [comment]
> What libevent version are you using?

I'm using libevent 2.1.8 as [packaged](https://www.archlinux.org/packages/core/x86_64/libevent/) by Arch Linux. Looks like that's the exact version you pointed to.

Perhaps unrelated, but I was using the same version of libevent when I compiled 2.4 manually, and when I bisected yesterday.

(I'll get to the extended strace later; it's early morning over here, so things are a bit busy.)

**Comment by nicm** [comment]
See if you can reproduce after doing this before starting tmux for the
first time:

export EVENT_NOPOLL=1

**Comment by nicm** [comment]
I know what this probably is, will send you something to test shortly.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1141379/x.diff.txt)

If the libevent signal handler gets called in the child process before we call event_reinit or clear_signals it could still write to the parent's signal pipe, so we need to block all signals to stop it.

**Comment by nicm** [comment]
I've made some other changes to how tmux manages the processes, if they have made it to GitHub by the time you test then you may need this diff instead: [y.diff.txt](https://github.com/tmux/tmux/files/1141498/y.diff.txt)

**Comment by AaronVanGeffen** [comment]
I just applied your x.diff.txt patch to fbbf5a108b01c742ca11e779845a4d19a1c5edd1, and am happy to say I cannot reproduce the problem. I tested it again without the patch, too, and could reproduce it again. So, it looks like you were successful. Thank you.

Could you speculate as to why e354b0e40fe1be1e1f8977d424e02e6487039a56 appears to introduce the problem, though?

On a minor sidenote: I had to manually add the `#include <signal.h>` line, though, as that part of the patch was rejected in cmd-pipe-pane.c, proc.c, and window.c. I assume that to be because the OpenBSD repository and the one on GitHub are slightly out of sync?

**Comment by nicm** [comment]
OK I have applied the second diff now, if you could test again in a day or so when GitHub is all synced up it would be great.

I suspect it is because until that change jobs were not killed when the client detached, they were left to die naturally, so it was much less likely you would get a process started and then killed very quickly.

**Comment by AaronVanGeffen** [comment]
Alright, I'll check back tomorrow, then. Thanks again.

**Comment by nicm** [comment]
This is all there now.

**Comment by LDVSOFT** [comment]
Hello! Is this the issue that causes tmux to kill server when detaching via `prefix-d`, and not to kill when done via `tmux detach`? I am having this issue right now and cannot figure out, is this issue relevant.

**Comment by Nexolight** [comment]
Just recently I also experience exactly this problem. I'm using v2.6

**Comment by FelipeMarcelino** [comment]
Same here @Nexolight
