### ISSUE TITLE
[2.5] Attached clients with differing dimensions do not draw complete buffer

### ISSUE THREAD

**Issue by MacGyverNL** [tmux/tmux#1003]
Also confirmed on my current master, fbbf5a108b01c742ca11e779845a4d19a1c5edd1

Platform is Arch Linux with kernel 4.11.9, no tmux config needed to reproduce.
Terminal in use is rxvt-unicode, version 9.22
```$TERM``` inside tmux is ```screen```, ```$COLORTERM``` is ```rxvt```. Behaviour also seen with ```$TERM``` set to ```screen-256color```.
```$TERM``` outside tmux is ```rxvt-unicode-256color```, ```$COLORTERM``` is ```rxvt```

When attaching multiple clients to a session, several clients seem to have issues with redrawing a multiline prompt. In this specific case, my multiline prompt is only drawn if I switch away and back to the pane. This behaviour shown in https://ptpb.pw/AgLB (before switching away and back to pane 0) and https://ptpb.pw/cJRv (after). Note how the right client is only missing the bottom prompt, whereas the bottom left client is missing all prompts since the last forced redraw. On master, I'm unable to reproduce the latter, so there it only looks like https://ptpb.pw/qIrh

There also seem to be issues with searching through man pages, https://ptpb.pw/QWx5 is a screenshot of reverse searching the manpage of hexdump for the term width. Clearly not the same output on all three clients.

Logs for the server, out, and three clients for the reproduction of the prompt issue in master at https://ptpb.pw/85dd.tar.gz

I've bisected this to commit a71c262d5f1ff2125797569d474ff21efb7ddc91, so probably introduced by 8c8ce08d7927e6a83f0cb09388b2d1068fded529, or less likely by f731ae4a2dc6aca565b20dffd6ddf661e585cbb5

**Comment by giann** [comment]
I have the same issue: whole chunks of text are not drawn.

**Comment by nicm** [comment]
There are a lot of prompts in this log so I can't really work out anything useful.

Can you please try and reproduce again but mark just before or after you do so with some unique text?

For example, reproduce the problem then immediately type "abcdef" at the next prompt (without redrawing) so I can see which one is being displayed incorrectly.

**Comment by nicm** [comment]
Also you have 3 clients in this screenshot? Please make some logs with 2 instead if possible. The less you do while logging the easier it is to see.

**Comment by MacGyverNL** [comment]
Done, by typing abcdef at the prompt _after_ reproduction. New logs at https://ptpb.pw/V-aD.tar.gz

I've reproduced with a minimalistic multiline prompt, as can be seen at https://ptpb.pw/Gh9U.png
It's not as reliably reproducible as with my normal multiline prompt, though, since https://ptpb.pw/a19r.png immediately after looks fine.

**Comment by nicm** [comment]
OK thanks so you are pressing enter at one prompt, then it draws the next prompt incorrectly, then you typed "abcdef"?

**Comment by nicm** [comment]
It was the one you attached second draws incorrectly? Or the one you attached first?

**Comment by MacGyverNL** [comment]
> OK thanks so you are pressing enter at one prompt, then it draws the next prompt incorrectly, then you typed "abcdef"?

Yes, exactly; then I press enter again and we get the (expected) ```command not found``` output, and the prompt that's then at the bottom is drawn normally.

> It was the one you attached second draws incorrectly? Or the one you attached first?

The one I attached second; in the screenshots the right one. I haven't been able to reproduce this in the one attached first, only subsequently attached ones.

If I detach the first one, then attach a new client, it seems only reproducible in the one attached last, not the one that initially showed the bad behaviour.

If I detach all, then attach one new client, no issue; if I attach another one, only reproducible in the one attached last.

**Comment by nicm** [comment]
Does this fix it?
~~~~~
Index: server-client.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/server-client.c,v
retrieving revision 1.240
diff -u -p -r1.240 server-client.c
--- server-client.c	12 Jul 2017 09:07:52 -0000	1.240
+++ server-client.c	13 Jul 2017 16:34:59 -0000
@@ -1339,8 +1341,6 @@ server_client_check_redraw(struct client
 			c->flags |= CLIENT_REDRAW;
 			return;
 		}
-		if (evtimer_initialized(&ev))
-			evtimer_del(&ev);
 		log_debug("%s: redraw needed", c->name);
 	}

**Comment by nicm** [comment]
Wait need more than that.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1145926/x.diff.txt)

**Comment by MacGyverNL** [comment]
In addition to the patch in server-client.c?

**Comment by nicm** [comment]
No just the second one.

**Comment by MacGyverNL** [comment]
Unfortunately, no change.

(Btw, I'm reproducing on master, had to apply your patch reversed otherwise it wouldn't apply; but I assume that's what you wanted to happen)

**Comment by nicm** [comment]
No, the patch should apply as it is without changes.

**Comment by MacGyverNL** [comment]
On master, the changes in that patch already exist, since 1029f2b27753355d5ae48eaac91f9569a10b8785 which is the merge of 1f7ca973c5ddae22db18b1d3dbb9e5c7cb0f3a6a. I can reproduce the issue on master, and with that reverted, so either way this doesn't seem to influence the behaviour.

**Comment by nicm** [comment]
Ugh sorry this is the wrong file, try this instead 
[x.diff.txt](https://github.com/tmux/tmux/files/1146329/x.diff.txt)

**Comment by nicm** [comment]
That is wrong too, got the right directory this time i think
[x.diff.txt](https://github.com/tmux/tmux/files/1146338/x.diff.txt)

**Comment by MacGyverNL** [comment]
That one applied to master (e3698e6e1f3d7bfbe50ad74d816751ab465627ce) does seem to resolve the issue.

**Comment by nicm** [comment]
Appled to OpenBSD now, thanks. Will be in GitHub later.
