### ISSUE TITLE
Add ability switch to panes (like in display-panes) on pressing prefix

### ISSUE THREAD

**Issue by purpleP** [tmux/tmux#1004]
The motivation is to make possible to jump to any pane in two keypresses.
I really like `display-panes` command, but by default it's bound to `prefix q`. So three keypresses required to switch into arbitrary pane.

I've bounded `C-b` into `display-panes` (my prefix is `C-Space`) command (seems like it's the only control-something combination that isn't used in vim), but this also unsatisfactory, because maybe I would use some app that use C-b (like running screen inside of tmux session via ssh or something). And it seems to me that it would be really nice if pressing prefix would show pane numbers and I could press
`prefix 0` to switch to 0 pane (you can of course do that now, but you can't see pane number). Wouldn't hurt anyone by displaying the numbers until next key is pressed or timeout is gone.

the config could look like this
```
set -g show-pane-numbers-on-prefix

bind 0 switch-pane -t.0
bind 1 switch-pane -t.1
```

**Comment by nicm** [comment]
set -g prefix none
bind -n C-b display-panes\; switchc -Tprefix
unbind 0
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9

**Comment by purpleP** [comment]
Wow, thanks a lot!

**Comment by purpleP** [comment]
@nicm Is there a way to also make tmux stop waiting for command keys if I pressed a digit?
Right now after I've switched window by pressing digit if I would press keys like `o` or `:` tmux would do the thing that is bounded to them like entering tmux command line.

**Comment by nicm** [comment]
Try making the change below, then you can do:

set-hook -g pane-chosen 'switchc -Troot'

~~~~
Index: server-client.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/server-client.c,v
retrieving revision 1.241
diff -u -p -r1.241 server-client.c
--- server-client.c     14 Jul 2017 08:04:23 -0000      1.241
+++ server-client.c     21 Jul 2017 07:31:18 -0000
@@ -839,6 +839,8 @@ server_client_handle_key(struct client *
                if (wp != NULL && !window_pane_visible(wp))
                        wp = NULL;
                server_client_clear_identify(c, wp);
+               if (wp != NULL)
+                       notify_pane("pane-chosen", wp);
                return;
        }

**Comment by nicm** [comment]
Or wait, just use the argument to display-panes instead - you don't need any code changes:
~~~~
set -g prefix none
bind -n C-b display-panes "select-pane -t '%%'; switchc -Troot"\; switchc -Tprefix
unbind 0
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9

**Comment by purpleP** [comment]
@nicm Thanks a lot. Can you you explain how it works? I don't understand why I can use ` "select-pane -t '%%'; switchc -Troot"\;` If this is the way to define a command that takes argument, than I don't understand why I can still press `prefix c` and new window is created? Why tmux doesn't wait for me to press digit (which is exactly what I want, but I don't understand why is this working).

**Comment by nicm** [comment]
When you first press C-b, the command display-panes shows the numbers and switchc changes into the prefix key table.

When you press next key, if it is a digit then tmux handles it specially and runs the command you gave to display-panes - which selects a pane with select-pane and changes back into root key table. Without the switchc -Troot, the next key would be looked up in the prefix key table instead of sent to the pane.

If you press a key that isn't a digit, it will be looked up in prefix key table and command run, which automatically switches back to the root key table afterwards.

**Comment by purpleP** [comment]
@nicm thanks for explaining.
