### ISSUE TITLE
`bind -n C-h <some_action>` will trigger some_action if you hit ctrl-backspace or shift-backspace

### ISSUE THREAD

**Issue by dansteen** [tmux/tmux#1005]
Hi!  Thanks so much for your work on tmux.   It really changes all of our workflows for the better.  

I did run into one issue.   When I have a tmux.conf as follows:

```
bind-key -n C-h previous-window
```

If I then hit ctrl-h it switches to the previous window.  That's as it should be, however, it also switches to the previous window if I hit ctrl-backspace or shift-backspace (but not if I just hit backspace).   I would understand if it triggered on backspace since C-h is the ctrl key for backspace, however, it seems strange that it would trigger on ctrl-backspace and shift-backspace but not just plain backspace.   (and I'd really prefer it didn't trigger on any of these :-) )

Thanks so much!

Versions: 
linux: ArchLinux (fully updated)
version: tmux 2.5
TERM inside tmux: screen-256color
TERM outside tmux: st-256color

[tmux-client-117603.log.zip](https://github.com/tmux/tmux/files/1139477/tmux-client-117603.log.zip)

**Comment by nicm** [comment]
There is no difference between BSpace and C-BSpace and S-BSpace.

On most platforms and terminals BSpace is \177 not C-h for exactly this reason.

**Comment by dansteen** [comment]
right, but I *am* seeing a behavior difference.  It took me a while to pin down because I wasn't expecting it to be any different either.   Doing a bit more poking,  it looks like there is a difference between how `st`, `xterm`, and `rxvt` handle this.   In `st` ctrl-backspace and shift-backspace 
 but not plain backspace will trigger the `C-h` action.  In `urxvt` ctrl-backspace will trigger the `C-h` action, but not shift-backspace nor just plain backspace.   In `xterm` nothing will trigger the `C-h` action (even actually hitting ctrl-h).

All very strange...

**Comment by nicm** [comment]
Perhaps these terminals send different escape sequences for BSpace, S-BSpace and C-BSpace. You can see what each is sending by running this outside tmux
~~~~
stty erase ''; cat
~~~~
Then pressing the keys. Or by looking at tmux logs.

**Comment by dansteen** [comment]
Ok, so I made a few handy charts to help figure this out:

# Tmux Behavior
|       | backspace | ctrl-backspace | shift-backspace |
|-------|-----------|----------------|-----------------|
| st    | backspace | action         | action          |
| xterm | action    | backspace      | action          |
| urxvt | backspace | action         | backspace       |

# stty erase ''; cat output
|       | backspace | ctrl-backspace | shift-backspace |
|-------|-----------|----------------|-----------------|
| st    | ^?        | ^H             | ^H              |
| xterm | ^H        | ^?             | ^H              |
| urxvt | ^?        | ^H             | ^?              |

So the two charts definitely seem to line up as far as behavior goes (note that originally when I tested xterm nothing triggered the action, however, in all my subsequent tests the chart above is the result for xterm - so I'm going to assume I made some mistake or other in the original xterm test).

This is all very interesting, and definitely explains the behavior I was seeing.  Thanks so much for your help!
