### ISSUE TITLE
tmux 2.4+ no longer detects utempter by default.

### ISSUE THREAD

**Issue by DarkHelmet433** [tmux/tmux#1006]
The commit  733185d on Oct 17th 2016
"Can use enable_* rather than adding our own found_* variables, from Dilyan Palauzov"
also inverted the default handling of utempter support.  In tmux 2.3 and earlier, it used to probe by default.  

The previous tmux 1.9 - 2.3 default of "found_utempter=yes" was removed in the commit.

If disabling the detection of utempter support was intended, it was not mentioned in the CHANGES file.

I was trying to figure out why utmp support wasn't working on the freebsd project dev cluster and couldn't find any mention of a change that might cause it.  If it is intended, a note to that effect would have helped.

Adding --enable-utempter restores the old behavior of probing for the library and functions.

**Comment by nicm** [comment]
This is intentional, utempter is not used by default.

**Comment by DarkHelmet433** [comment]
Fair enough,  still, it would have been nice to have had a mention in the changes file so I didn't have to figure out what happened.  Thanks anyway though.

**Comment by nicm** [comment]
Right, but it was missed. And it mentioned in the README - and that change is the third thing you see if you search for utempter in git log, so it is hardly a big problem.
