### ISSUE TITLE
waitpid for xyz failed: No child processes

### ISSUE THREAD

**Issue by trassl** [tmux/tmux#1007]
Since fbbf5a108b01c742ca11e779845a4d19a1c5edd1 some processes fail with `waitpid for xyz failed: No child processes` errors. Affected processes use clone syscalls.

How to test (inside a git repository, inside tmux):
```
$ # works
$ git status
...

$ # error, aliased git commands use clone/wait4 syscalls
$ git config alias.st status
$ git st
error: waitpid for git-st failed: No child processes
...
error: waitpid for git-status failed: No child processes
```
* platform linux
* libevent 2.1.8
* tmux master 1265e212e47ca6cfc05ffbccc1edc079f97de461

**Comment by nicm** [comment]
Does this fix it: 
[x.diff.txt](https://github.com/tmux/tmux/files/1148393/x.diff.txt)

**Comment by trassl** [comment]
Yes, tmux master 1265e212e47ca6cfc05ffbccc1edc079f97de461 + your patch fixes the problem. Thank you.

**Comment by speters** [comment]
I've run into the same problem. The patch by nicm seems to fix it. Thx, nicm!

**Comment by nicm** [comment]
I've applied a similar change, thanks. Should be in GitHub in a while.
