### ISSUE TITLE
expanding command completion after ":"

### ISSUE THREAD

**Issue by sdwarwick** [tmux/tmux#1009]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

HI - has there been any thought to expanding the command completion function to provide more extensive command suggestions ( perhaps as an overlay window) ?  we see this capability in bash, and in many other IDEs where you can type some characters and see all commands that include these as a  substring, or even all commands where the description includes the substring.

**Comment by ThomasAdam** [comment]
There has; we could use libedit for this.  It's in the TODO file.

**Comment by sdwarwick** [comment]
I'm sorry,  I just went through the TODO file.  For some reason, I'm not seeing it called out.

**Comment by nicm** [comment]
If you are interested in doing this I'd definitely look at a diff, I'm more
interested in showing potential completions than adding new ones though.
But the current completion works for me at the moment so it's not likely to
be something I will do soon.

**Comment by thejmazz** [comment]
FWIW I came to my own solution of “I want generic completions in tmux statusline”:

The vanilla way with no autocompletion would be:

```
split-window kubectl exec -it ugh-what-is-the-pod-name
```

I have a specific zsh plugin:

```zsh
autoload -Uz add-zsh-hook
	
function swappane () {
    tmux if-shell "exit 0" "kill-pane; split-window -$DIR $1"
}
	
add-zsh-hook preexec swappane

# inform user this is not a regular shell	
PROMPT="TMUX: "
```

Which is only sourced within `~/.zshrc` if `TMUX_PROMPT` is set:

```zsh
[[ "$TMUX_PROMPT" == "1" ]] && source ~/.zsh/tmux-prompt.zsh
```

And some bindings:

```tmux
bind-key R switch-client -T RUNPANE
bind-key -T RUNPANE h split-window -bh 'TMUX_PROMPT=1 DIR=bh zsh'
bind-key -T RUNPANE j split-window -v 'TMUX_PROMPT=1 DIR=v zsh'
bind-key -T RUNPANE k split-window -bv 'TMUX_PROMPT=1 DIR=bv zsh'
bind-key -T RUNPANE l split-window -h 'TMUX_PROMPT=1 DIR=h zsh'
```

Now I can do something like `kubectl exec -it some-super-long-podname-that-was-autocompleted` into a new pane on left/bottom/top/right, which will remove the pane when quit (the magic with the quick kill-pane and split-window). :)

Any other way than the `if-shell` hack to run `kill-pane; split-window` in succession? I tried `bash -c “tmux kill-pane && tmux split-window mycmd”.
