### ISSUE TITLE
Remove Spaces from Status Bar

### ISSUE THREAD

**Issue by 73** [tmux/tmux#101]
Hi Girls and Guys,
is it possible to remove the spaces from the status bar by config? 
```
[0] [1:zsh] [2:zsh]
```
I would like it more condensed.
Thanks for tmux!
--73

**Comment by ntnn** [comment]
`man tmux | less +/set-titles-string`

**Comment by 73** [comment]
Well, I meant the status bar not the title... 
I tried:
´´´
set -g window-status-separator '' #remove space between window titles 
´´´
That works, but I do not find a setting to remove the spacing between  `status-left` and `window-status`.

If there is no way, this issue might be closed.

**Comment by nicm** [comment]
Use a newer tmux and the space is part of status-left.
