### ISSUE TITLE
pipe to macOS's pbcopy is not working

### ISSUE THREAD

**Issue by learning** [tmux/tmux#1010]
pipe to pbcopy is not working

```shell
cat ~/.ssh/id_rsa.pub | pbcopy
```

- tmux 2.5
- macOS 12.12.5

**Comment by learning** [comment]
Sorry for duplication, I found the answers:
#543 
https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/53

```
brew install reattach-to-user-namespace
```

And add this to `~/.tmux.conf`

```
set -g default-shell $SHELL
set -g default-command "reattach-to-user-namespace -l ${SHELL}"
```

**Comment by kylewayman** [comment]
Just a quick note, because it took me quite a while to realize this, if you have tmux currently running, you also need to kill the tmux server before it will take the new configuration.
```
tmux kill-server
```
