### ISSUE TITLE
Please help. I'm having a nervous breakdown with this

### ISSUE THREAD

**Issue by snapchatdotcom** [tmux/tmux#1011]
So i followed this tutorial where I could have made an inactive pane darker and now when I type text in iterm with tmux, nothing shows. As if the color was clear or something. How can i revert to the defaults of tmux? Default colors, settings, bindings, etc?

**Comment by krader1961** [comment]
What tutorial? The link you presumably intended to include is not present.

As for fixing your problem just revert the changes you made to your *~/.tmux.conf* or remove that file then `tmux kill-server`. When you start new tmux sessions you will have the default (or at least your pre-problem) settings.

**Comment by snapchatdotcom** [comment]
What in tarnation! Thank you for such a simple solution. 

Sorry, I had the link in clipboard but was very distressed from my noobish mistake that I forgot: 

http://www.deanbodenham.com/learn/tmux-pane-colours.html
Do not recommend.
