### ISSUE TITLE
Multiple panes and flickering

### ISSUE THREAD

**Issue by hholst80** [tmux/tmux#1012]
```
Linux x86_64
tmux 2.1
screen-256color
```

When I have programs emitting a lot of data in my panes I get a lot of cursor flickering. Is there some way to get rid of that?

**Comment by nicm** [comment]
No tmux has to move the cursor in order to draw output.

**Comment by hholst80** [comment]
I cannot see any flickering if I pull up a lot of curses based programs in high refresh (like `top` with 0.02 delay). Is it not possible to render the non-active windows in the same way?

**Comment by nicm** [comment]
top at 0.02 delay is not high refresh, maybe at 0.

**Comment by hholst80** [comment]
compare `top -d 0.01` in 3 panes with
```
while :
do
    echo aksjdfkl asdklfjakl sdfklaj sdklfjklas dfklajskl dfklasj dfaskl
    sleep 0.01
done
```

it is enough on my system to run a single one of those bash loops to induce a cursor flickering behavior. 3 top is ok though.

**Comment by nicm** [comment]
top flickers for me and your loop does not, this is heavily dependent on the speed of your computer and terminal.

**Comment by nicm** [comment]
Anyway, 2.1 is way too old. Try with 2.5 or master.

**Comment by hholst80** [comment]
Thanks for looking into it. It is not a big thing just, slightly annoying. ;-) I'll try with the latest stable and see if it is less noticeable.
