### ISSUE TITLE
User need to be told to install automake and autoconf

### ISSUE THREAD

**Issue by FreeBlues** [tmux/tmux#1015]
In Readme, the step of build tmux, when you run `sh autogen.sh`, you need the autoconf installed otherwise it will return error and said that aclocal can not found. Please add it

>$ git clone https://github.com/tmux/tmux.git
>$ cd tmux
>$ sh autogen.sh
>$ ./configure && make

**Comment by nicm** [comment]
It is safe to assume that if someone is building from Git they know what
autotools is.

**Comment by nicm** [comment]
I have mentioned these in the README.
