### ISSUE TITLE
[Feature request] Give default-command a window scope

### ISSUE THREAD

**Issue by LoveIsGrief** [tmux/tmux#1018]
Hello,

First of all, thanks for the great tool! It's a daily companion.

For my example below, it would be great to be able to do `set-option -w -t 0 default-command "ssh master.server.me"`.

Or at least raise an error when `-w` is passed to an option that isn't in the window scope.

# My example

## Setup
 - 1 window with a connection to master server running tmux on the master server
 - multiple other windows of server groups (redis, db, processing, load balancers, etc.)

## Problem

Doing any command on the master server, needs me hitting `Ctrl+b` twice e.g `Ctrl+b` + `Ctrl+b` + `v` -> create new pane on master. It's tedious.  
Of course when I run an important command on the server, it's nice to know that cutting the SSH connection won't interrupt the command due to the tmux session, but that doesn't happen often.

**Comment by LoveIsGrief** [comment]
rofl, holy shit, never mind.

`set-option -w -t 0 default-command "ssh master.server.me"`

It was there all along. Move along folks.

`tmux` is awesome.

**Comment by LoveIsGrief** [comment]
From what I see it would change this single [line](https://github.com/tmux/tmux/blob/6995497e5b66e090f25e85fbb207f033f7790199/options-table.c#L176)

**Comment by nicm** [comment]
I don't think we should change this because there is a strong chance there are people doing the same as you but with different sessions for each server rather than different windows.

**Comment by LoveIsGrief** [comment]
Would it be possible to honor the `-w` option even for commands with a `OPTIONS_TABLE_SESSION` scope? It is kind of confusing to have `-w` ignored without an error on that scope.

**Comment by nicm** [comment]
No. And -w is for set-option is only for user options and backwards compat.

**Comment by nicm** [comment]
You could set default-command to a small script that does what you want based on a user option or the name of the window or something else.

**Comment by LoveIsGrief** [comment]
Would you have an example of passing user-options to default command?

I tried

```
set-option -w @foo what
set-option default-command "echo @foo && sleep 10"
```

And just see "@foo" in the new pane.

**Comment by nicm** [comment]
You need to do something like:

x=$(tmux display -pF '#{@foo}')

Of course you will need to make sure you set the user option after you create the window.

**Comment by LoveIsGrief** [comment]
In the end I wrote 

```bash
#!/usr/bin/env bash
# Used with tmux in order to have default commands per window

if [[ -n "$@" ]] ; then
    # echo "$#" "$@"
    bash -c "$@"
else
    bash
fi

# vi:syntax=sh
```

and my default comannd now looks like

    set-option -g default-command "command_or_bash \"`tmux display -pF \'#{@default-command}'`\""

It's very hacky, but it works, even with multiple sessions (which is honestly surprising, imo). 

Anyway, I'd still support a cleaner implementation in tmux e.g letting "default-command" be overriden by an option of the same name / new name ("override-command") in a window. I'd be ready to do it too, if that'd be consider for merging.

**Comment by nicm** [comment]
I don't think we need another way to do this unless you can think of a way that will be generally useful.

Ideally I'd like it if the separate global window and session option trees were collapsed together so that all options were searched window->session->server. But the issue is there are a number of contexts where the window is known but not the session, or where there are multiple equally good choices of session, and I don't think there is any way to resolve that.
