### ISSUE TITLE
[question/request] copy-mode without automatically selecting a pane?

### ISSUE THREAD

**Issue by avih** [tmux/tmux#1021]
I'm trying to enable mouse wheel in tmux panes similar to how terminator or other multiple-panes apps work: wheel over the pane scroll the app if in alt-mode, else scroll the backbuffer (the latter being copy-mode in tmux), and left-click selects the pane.

Sending mouse or kb events to an inactive pane works without making it the active pane, however, whenever I enter copy mode or send a wheel scroll event to an inactive pane in copy-mode, it becomes automatically the active pane. Is there some way to enter-copy-mode/scroll-in-copy-mode for an inactive pane while keeping it inactive?

Here's the wheel config in my `tmux.conf`:
```sh
# Mouse wheel scroll:
# if in non-alt-screen -> always enter/use copy mode. In alt screen, if the app
# registers "complex" mouse events (e.g. vim with set ttymouse=xterm2) - then
# passthrough the event, otherwise send up/down arrows. gnome-terminal sends
# up/down only if the app doesn't register any mouse events. To get that
# behavior, replace _button_ with _any_ at the mouse flags below.

bind-key -n WheelUpPane \
    if-shell -Ft= "#{?pane_in_mode,1,#{mouse_button_flag}}" \
        "send-keys -N3 -Mt=" \
        "if-shell -Ft= '#{alternate_on}' \
            'send-keys -N3 -t= Up' \
            'copy-mode -et=; send-keys -N3 -Mt='"

bind-key -n WheelDownPane \
    if-shell -Ft= "#{?pane_in_mode,1,#{?mouse_button_flag,1,#{?alternate_on,0,1}}}" \
        "send-keys -N3 -Mt=" \
        "send-keys -N3 -t= Down"
```

[edit] testing using current tmux git master ( 06a2644a ).

**Comment by nicm** [comment]
You probably want to remove the select-pane command from the WheelUp and WheelDown bindings in the copy-mode table.

**Comment by avih** [comment]
> You probably want to remove the select-pane command from the WheelUp and WheelDown bindings in the copy-mode table.

You mean the `-t=` of `copy-mode -et=` ? if yes, i tried without it as well before, but it correctly sends the event to the currently active pane - which isn't what i want. I want to scroll in copy mode or enter into copy mode the pane under the mouse pointer - but without making it active.

**Comment by nicm** [comment]
No...
~~~~
$ tmux lsk|grep WheelUpPane
bind-key    -T copy-mode    WheelUpPane       select-pane ; send-keys -X -N 5 scroll-up
bind-key    -T copy-mode-vi WheelUpPane       select-pane ; send-keys -X -N 5 scroll-up
bind-key    -T root         WheelUpPane       if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= \"#{pane_in_mode}\" \"send-keys -M\" \"copy-mode -et=\""

**Comment by avih** [comment]
Appreciate the help and I confirm it works as I wanted. For reference if others are interested, that's how the wheel part of my `tmux.conf` looks now (I use vi copy mode):

```sh
# Mouse wheel scroll: scroll pane under the cursor without explicitly activating it.
# if in non-alt-screen -> always enter/use copy mode. In alt screen, if the app
# registers "complex" mouse events (e.g. vim with set ttymouse=xterm2) - then
# passthrough the event, otherwise send up/down arrows. gnome-terminal sends
# up/down only if the app doesn't register any mouse events. To get that
# behavior, replace _button_ with _any_ at the mouse flags below.

# the original wheel up/down in copy mode select the pane. redefine without select
bind-key -T copy-mode-vi WheelUpPane   send-keys -X -N3 scroll-up
bind-key -T copy-mode-vi WheelDownPane send-keys -X -N3 scroll-down

bind-key -n WheelUpPane \
    if-shell -Ft= "#{?pane_in_mode,1,#{mouse_button_flag}}" \
        "send-keys -N3 -Mt=" \
        "if-shell -Ft= '#{alternate_on}' \
            'send-keys -N3 -t= Up' \
            'copy-mode -et=; send-keys -N3 -Mt='"

bind-key -n WheelDownPane \
    if-shell -Ft= "#{?pane_in_mode,1,#{?mouse_button_flag,1,#{?alternate_on,0,1}}}" \
        "send-keys -N3 -Mt=" \
        "send-keys -N3 -t= Down"
```

Thanks again.
