### ISSUE TITLE
How can I distinguish mutliple panes when I ssh into multiple remote machine?

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#1022]
tmux version: compiled and installed from git commit a612007, Jun 16 18:01:13 2017

When I ssh into several remote machines in the same tmux session, and if I want to switch among those panes, I cannot distinguish the panes according to their IP address. I have to `ifconfig` in the pane to check if it is the right machine.

I can `rename-window` if only one pane is in that window, but there is no `rename-pane` function, and I usually arrange multiple remote panes in one same window.

Is is able to show their IP address in status line when I focus on a pane or (better to ) provide all IP addresses info in `tmux choose-tree` ?

**Comment by nicm** [comment]
You could set the pane title from inside the pane and then use
#{pane_title}, or use a script that uses #{pane_pid} to work out something.
Either for status line or pane-status.

**Comment by c02y** [comment]
I wrote something that could show IP address of the current pane in the status line, now I want to put the those IP addresses in the list of `tmux choose-tree`, so I can directly choose the remote machine from the list.

Long time ago, I used customized `choose-tree` to show the info I needed in the list:

    bind w choose-tree -u -W '#{window_index}(#{window_panes}): #{window_name} #{session_attached,yes,} #{pane_current_path} #F'

but the function is updated in commit aad4e4d, so this config does not work any more, I just want to add something in the end of each line of the list in `tmux choose-tree` based on the default info.

This is the current info `tmux choose-tree` for panes:

![snapshot1](https://user-images.githubusercontent.com/2135996/28698808-5f08bf36-7378-11e7-9ff5-9da7778de387.png)

I want it to be like this:

    (2)    |    |--> 1: sudo "root@localhost:!" <192.168.50.49>

How can I do that?

**Comment by nicm** [comment]
If you put it in the pane title it will show it (we should change so the title is shown for windows with 1 pane too).

**Comment by c02y** [comment]
There is builtin variable called `pane_title`, you mean to redefine `pane_title`, but how can I make it work in `choose-tree`?

**Comment by nicm** [comment]
You can set pane_title with the escape sequences and it will be shown in the choose-tree list.

**Comment by c02y** [comment]
I'm sorry, I googled and searched in this tmux github project, but I'm still not familiar with the `set pane_title with the escape sequences` here. Ho to do that?

**Comment by nicm** [comment]
if you do somethign like this inside the pane:
~~~~
printf "\033]2;mytitle\007"
~~~~
It will set the pane title. Then that should be displayed in "" in the choose-tree list.

**Comment by c02y** [comment]
I failed to find a way to redefine tmux builtin variable like `pane_title`.

Are we going to the right direction? No need to modify `pane_title` itself, besides modifying `pane_title` will change `change pane-border-format`, that is unnecessary, I just want to **add another info** at the end of each pane in `choose-tree` list.

I guess there is no way to customize the info shown in `choose-tree` like the old way:

    bind w choose-tree -u -W '#{window_index}(#{window_panes}): #{window_name} #{session_attached,yes,} #{pane_current_path} #F'

If so, I think I should give up.

**Comment by nicm** [comment]
~~~~
$ tmux new
$ tmux lsp -F '#{pane_title}'
myhost
$ printf '\033]2;foobar\007'
$ tmux lsp -F '#{pane_title}'
foobar
$ tmux choose-tree
~~~~
![x](https://user-images.githubusercontent.com/304243/28867256-4d668058-776d-11e7-8bc4-5471644aa009.png)

**Comment by nicm** [comment]
You could also use this [x.diff.txt](https://github.com/tmux/tmux/files/1193346/x.diff.txt) which adds selectp -T to set the title.

**Comment by c02y** [comment]
This is my result of your instructions with loading my .tmux.conf: 

    $ tmux new
    $ tmux lsp -F '#{pane_title}'
    tmux  /home/chz
    $ printf '\033]2;foobar\007'
    $ tmux lsp -F '#{pane_title}'
    tmux  /home/chz
    $ tmux choose-tree

![snapshot1](https://user-images.githubusercontent.com/2135996/28870409-be6228da-77b2-11e7-8a9a-5f177c000c26.png)

This is my result if your instructions without loading my .tmux.conf:

    $ tmux new
    $ tmux lsp -F '#{pane_title}'
    root@chz:~ 
    $ printf '\033]2;foobar\007'
    $ tmux lsp -F '#{pane_title}'
    root@chz:~ 
    $ tmux choose-tree

![snapshot1](https://user-images.githubusercontent.com/2135996/28870524-28fcaeb8-77b3-11e7-82ae-ca74ded9a760.png)

**Comment by nicm** [comment]
Your shell is changing the pane title itself and writing over the one you set, you will need to stop it doing that.

**Comment by c02y** [comment]
I tested it in bash-shell for root user, fish-shell for regular user.

The .bashrc file in /root/ contains lines:

    # Source global definitions
    if [ -f /etc/bashrc ]; then
            . /etc/bashrc
    fi

which will change pane title. **The pane title will not be changed by bash-shell (just like your result) if I remove .bashrc file**.

I tested it again in fish-shell without any of my own configuration (just using default configuration loaded by fishshell), the pane title will still be changed by fish-shell.

So I believe that it is not a good idea to modify pane title directly. 

Again:

> Are we going the wrong way? No need to modify `pane_title` itself, besides modifying `pane_title` will change `change pane-border-format`, that is unnecessary, I just want to add another info at the end of each pane in `choose-tree` list.

> If it's impossible to customize the info shown in `choose-tree` like the old way:

>     bind w choose-tree -u -W '#{window_index}(#{window_panes}): #{window_name} #{session_attached,yes,} #{pane_current_path} #F'
>
> maybe I should give up.

If it is really impossible to customize 'choose-tree` directly, I could just give it up.

**Comment by nicm** [comment]
You can't change the format of choose-tree anymore, that's why I am suggesting using pane_title.

**Comment by c02y** [comment]
OK, Thank you anyway, your effort and patience is appreciated.

**Comment by nicm** [comment]
I would be open to a diff that allowed you to append to the line in the various choose-* modes (maybe adding your part in []s or something).

**Comment by c02y** [comment]
OK, I'll try any solution.

**Comment by nicm** [comment]
Here is a change which adds choose-tree -F to let you set the format: [y.diff.txt](https://github.com/tmux/tmux/files/1207724/y.diff.txt)

The disadvantage is that the format is pretty complicated, because it needs to work for panes windows and sessions. This is the default one:
~~~~
#define WINDOW_TREE_DEFAULT_FORMAT \
        "#{?pane_format," \
                "#{pane_current_command} \"#{pane_title}\"" \
        "," \
                "#{?window_format," \
                        "#{window_name}#{window_flags} " \
                        "(#{window_panes} panes)" \
                        "#{?#{==:#{window_panes},1}, \"#{pane_title}\",}" \
                "," \
                        "#{session_windows} windows" \
                        "#{?session_grouped, (group ,}" \
                        "#{session_group}#{?session_grouped,),}" \
                        "#{?session_attached, (attached),}" \
                "}" \
        "}"
~~~~
I tried adding an "additional" format that you could tag onto the end, but I think it is not so useful.

**Comment by nicm** [comment]
This is the default format without the cpp bits:
~~~~
#{?pane_format,#{pane_current_command} "#{pane_title}",#{?window_format,#{window_name}#{window_flags} (#{window_panes} panes)#{?#{==:#{window_panes},1}, "#{pane_title}",},#{session_windows} windows#{?session_grouped, (group ,}#{session_group}#{?session_grouped,),}#{?session_attached, (attached),}}}
~~~~

**Comment by nicm** [comment]
Here is expanded diff which adds the same for choose-buffer and choose-client and also updates tmux.1:
 [x2.diff.txt](https://github.com/tmux/tmux/files/1207849/x2.diff.txt)

**Comment by nicm** [comment]
I have applied this to OpenBSD now, it should be in GitHub soon. You can use choose-tree -F to specify your own format for the lines.

**Comment by c02y** [comment]
I tried to compile and install the latest tmux from git, unfortunately, the ssh IP that can be displayed in mode line cannot be displayed in the choose-tree list **correctly**. Actually all the panes in the list will contain the same IP address which is the IP address of the current pane which the command `tmux choose-tree` is executed, since I get the IP address  according to `${pane_tty}` variable in a bash script.

This is my ssh_ip bash script if it helps:

    #!/bin/bash
    # this file is for tmux config to show pane_tty<-->IP address
    
    # tmux: pane_tty: pts/5
    pane_tty=$(tmux display-message -p '#{pane_tty}' | cut -c 6-)
    
    # get IP address according to pane_tty
    ip_addr=$(pgrep -t $pane_tty -l -f "sudo ssh " | awk 'NF>1{print $NF}')
    
    if [[ "$ip_addr" != "" ]]; then
        echo "<$ip_addr> "
    else
        echo "<localhost> " # or empty
    fi

But I put a tmux variable like `#{pane_tty}` in `choose-tree -F`, it will be displayed in `tmux choose-tree` correctly. This is my `choose-tree` configutation:

    bind w choose-tree -F '#{?pane_format,#{pane_current_command} "#{pane_title}" #{pane_tty} #(ssh_ip),#{?window_format,#{window_name}#{window_flags} (#{window_panes} panes)#{?#{==:#{window_panes},1}, "#{pane_title}",},#{session_windows} windows#{?session_grouped, (group ,}#{session_group}#{?session_grouped,),}#{?session_attached, (attached),}}}'

Any suggestion?

**Comment by nicm** [comment]
Did that ever work?

**Comment by c02y** [comment]
> I tried to compile and install the latest tmux from git, unfortunately, the ssh IP that can be displayed in status line cannot be displayed in the choose-tree list correctly. Actually all the panes in the list will contain the same IP address which is the IP address of the current pane which the command tmux choose-tree is executed, since I get the IP address according to ${pane_tty} variable in a bash script.

Not working correctly. Check the whole context.

**Comment by nicm** [comment]
...did it ever work?

**Comment by nicm** [comment]
That is, did it work in older tmux versions?

I'm not sure if we can make #() work in choose-tree, I'll need to look when
I get home next week. Or there may be an alternative.

**Comment by c02y** [comment]
This issue is not fixed yet, is it in the plan?

**Comment by nicm** [comment]
Oh I forgot, sorry, I'll try and take a look this week.

**Comment by nicm** [comment]
It is not easy to support #() in choose tree and I don't have time to do it right now. If you try this it may work if you are setting up the #() from elsewhere (status line for windows, or pane-border-status for panes): [x.diff.txt](https://github.com/tmux/tmux/files/1274271/x.diff.txt)
