### ISSUE TITLE
freebsd build fail

### ISSUE THREAD

**Issue by jungle-boogie** [tmux/tmux#1024]
Hi All,

I just upgraded to freebsd 11.1-release and tmux is failing to build:

```
erts.o -MD -MP -MF $depbase.Tpo -c -o alerts.o alerts.c && mv -f $depbase.Tpo $depbase.Po
In file included from alerts.c:19:0:
/usr/local/lib/gcc49/gcc/i386-portbld-freebsd11.0/4.9.4/include-fixed/sys/types.h:266:9: error: unknown type name '__vm_ooffset_t'
 typedef __vm_ooffset_t vm_ooffset_t;
         ^
/usr/local/lib/gcc49/gcc/i386-portbld-freebsd11.0/4.9.4/include-fixed/sys/types.h:268:9: error: unknown type name '__vm_pindex_t'
 typedef __vm_pindex_t vm_pindex_t;
         ^
*** Error code 1

Stop.
make: stopped in /usr/home/sean/bin/tmux
```

config.txt attached

Is this likely a freebsd issue?
[config.txt](https://github.com/tmux/tmux/files/1180997/config.txt)

**Comment by nicm** [comment]
I would say this is a FreeBSD issue

**Comment by nicm** [comment]
Isn't this exactly the same as #809 which you also opened...

**Comment by jungle-boogie** [comment]
Hi @nicm,

I thought it looked familiar. At that time I was using 12-current and now I'm not 11.1. So still a wait and see with freebsd, I suppose.
