### ISSUE TITLE
Vim copy to clipboard not working

### ISSUE THREAD

**Issue by ovu** [tmux/tmux#1025]
I am using Mac OS Sierra and tmux 2.5 with vim 8.0.648.

When I use the vim functionality to copy to clipboard (Register "+) with tmux, it does not work.
When I start vim without tmux in the terminal then it works. Is it a known issue with tmux?

**Comment by nicm** [comment]
This sounds like a vim problem not a tmux problem.

**Comment by ovu** [comment]
As I mentioned, vim works when it runs without tmux. With tmux there is the issue. I tried removing my .tmux.conf file and I still have the same problem.

**Comment by nicm** [comment]
All the same.

**Comment by nicm** [comment]
How is vim setting the clipboard?

**Comment by nicm** [comment]
Show tmux logs please.

**Comment by ovu** [comment]
Normally in vim in order to copy to system clipboard it is used the commands "+y  It should set the register + with what was selected. However the register is empty. Nothing gets copied to the system clipboard. Without tmux vim works as it should be. That is why I think it is something related to tmux.

**Comment by ovu** [comment]
How do I get the tmux logs?

**Comment by nicm** [comment]
Look at the CONTRIBUTING file it has instructions

**Comment by ovu** [comment]
Attached is the log file. I hope it can help.

[tmux-server-50172.log.zip](https://github.com/tmux/tmux/files/1184124/tmux-server-50172.log.zip)

**Comment by nicm** [comment]
vim is not using OSC 52 so it may be using X. Are you sure you have set
DISPLAY?

**Comment by ovu** [comment]
I installed macvim using brew and I did not set any DISPLAY. Where should it be configured?

**Comment by ovu** [comment]
I think I figured it out how to fix the issue. Using the command mvim instead of vim fixed the issue. Now the clipboard is working as it should be. Thanks for your help.

**Comment by ovu** [comment]
Sorry, I ran mvim without tmux. That is why it worked. Copying to system clipboard is still not working :(

**Comment by krader1961** [comment]
As always the first response to any question involving problems with tmux on macOS should be to ask if the user has the following in their *~/.tmux.conf*

```
# The reattach-to-user-namespace is necessary to be able to contact ssh-agent
# via the SSH_AUTH_SOCK env var. This is also necessary to make pasteboard
# (clipboard) interaction work for programs run within the tmux server.
set-option -g default-command "exec reattach-to-user-namespace -l fish"
```

Obviously substitute your shell where I have `fish`. Note that `reattach-to-user-namespace` is not part of macOS. You can install it with Homebrew.

**Comment by ovu** [comment]
Thanks for your help. That was the trick. Now it is working as it should be. I think it should be included in the tmux documentation. I can imagine tmux users having the same issue with MacOS.
