### ISSUE TITLE
Hot key for both begin-selection and copy-selection-and-cancel feature request.

### ISSUE THREAD

**Issue by ondrejj** [tmux/tmux#1028]
With all tmux releases (currently at master) begin-selection and copy-selection-and-cancel are different keys. As an user of "screen" program, I can't settle in to use space::enter to copy from tmux history.
Is it possible to add a new feature to set space to begin-selection if it was not started and copy and cancel selection if there was already started? Using tmux more years, but always fail if I select first time.
Thank you.

**Comment by nicm** [comment]
You could add a format to tell you if there is a selection and then use that to decide which command to use.

**Comment by ondrejj** [comment]
Can you give me an example, how to do this?

**Comment by nicm** [comment]
Try apply this [x.diff.txt](https://github.com/tmux/tmux/files/1193361/x.diff.txt), rebuild and restart tmux and then:
~~~~
bind -Tcopy-mode Space if -F '#{selection_present}' 'send -X copy-selection-and-cancel' 'send -X begin-selection'

**Comment by ondrejj** [comment]
Unable to download your diff. Any chance to get into a tmux git branch?

**Comment by nicm** [comment]
I can download it OK.

**Comment by nicm** [comment]
Try this https://pastebin.ca/raw/3849916

**Comment by ondrejj** [comment]
Thanks, I allowed insecure downloads and downloaded it.
Applied to git master, existed current tmux, started new one, added your binding, but no luck with selection in new mode. Space still starts selection. Here is list from my bindings:

[ondrejj@work ~]$ tmux list-keys -T copy-mode | grep Space
bind-key -T copy-mode C-Space           if-shell -F "#{selection_present}" "send -X copy-selection-and-cancel" "send -X begin-selection"
bind-key -T copy-mode Space             if-shell -F "#{selection_present}" "send -X copy-selection-and-cancel" "send -X begin-selection"

**Comment by nicm** [comment]
Works for me, are you sure you restarted tmux entirely?

**Comment by ondrejj** [comment]
Works now, but I have to use -T copy-mode-vi (may be because I use vi mode).
Can you apply this to git?

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later, thanks.
