### ISSUE TITLE
tmux vim ctrlp colorscheme

### ISSUE THREAD

**Issue by jrock2004** [tmux/tmux#103]
When using tmux and I open vim. I open ctrlp, which opens, but I am not able to use the arrow keys to select any of the items. I am using a vim colorscheme that is not packaged with vim. If I change my colorscheme to a default one it works fine. Any ideas?

**Comment by riesebie** [comment]
* John Costanzo <notifications@github.com> [2015-09-03 10:30 -0700]:

> When using tmux and I open vim. I open ctrlp, which opens, but I
> am not able to use the arrow keys to select any of the items. I am
> using a vim colorscheme that is not packaged with vim. If I change
> my colorscheme to a default one it works fine. Any ideas?

Your customized vim colorscheme maybe needs a 256color capable
terminal? If your term supports 256 colors set TERM=screen-256color
and try again.

Elimar
-- 
 Never make anything simple and efficient when a way
  can be found to make it complex and wonderful ;-)

**Comment by jrock2004** [comment]
I figured the problem. I had to force tmux to start with 256 color by doing the following command:

```
tmux -2
```
