### ISSUE TITLE
bind-key -r <Arrow> not repeating

### ISSUE THREAD

**Issue by ahmedelgabri** [tmux/tmux#1032]
I'm using the `master` version & I have these key bindings in my config but they don't repeat. I have to do `<prefix> <arrow>` everytime.

```tmux
# Resizing
unbind-key Left
unbind-key Right
unbind-key Down
unbind-key Up
bind-key -r Left resize-pane -L 10
bind-key -r Right resize-pane -R 10
bind-key -r Down resize-pane -D 10
bind-key -r Up resize-pane -U 10
```

**Comment by nicm** [comment]
Works for me.

**Comment by ahmedelgabri** [comment]
Ok, so how can I debug this? this is my [`.tmux.conf`](https://github.com/ahmedelgabri/dotfiles/blob/42c4f10f783a4e92a8b98d3c10ca6efa7f93752e/tmux/.tmux.conf)

**Comment by ahmedelgabri** [comment]
I didn't think about that, yes it does. Will go through the config to find the issue. Thanks.
