### ISSUE TITLE
error connecting to /tmp/tmux-4399/default (No such file or directory)

### ISSUE THREAD

**Issue by attitudechunfeng** [tmux/tmux#1036]
I have installed tmux-2.5 on a CentOS server. However, once i detached from a session, i will come across the error like "error connecting to /tmp/tmux-4399/default (No such file or directory)" if i tried to attach the session again.
Can anybody give me some advices?

many thanks.

**Comment by nicm** [comment]
If the tmux server is still running, you can send SIGUSR1 to it to get it to recreate its socket.

**Comment by kshenoy** [comment]
@nicm Can you please expand on how to do that?

**Comment by nicm** [comment]
pkill -USR1 tmux

**Comment by kshenoy** [comment]
@nicm Thanks a lot! That gets rid of a common annoyance 👍
