### ISSUE TITLE
tmux+nvim/vim render blinking

### ISSUE THREAD

**Issue by vaxXxa** [tmux/tmux#104]
iTerm Build 2.9.20150830
tmux: stable 2.0
nvim

iterm + nvim: **ok**
https://dl.dropboxusercontent.com/u/33889723/iterm%2Bnvim.mov

iterm+tmux+nvim: **problem**
https://dl.dropboxusercontent.com/u/33889723/iterm%2Btmux%2Bnvim.mov

iterm+tmux+nvim+layouts: **problem** on different layouts
https://dl.dropboxusercontent.com/u/33889723/iterm%2Btmux%2Bnvim%2Blayouts.mov

**Comment by nicm** [comment]
Seems like an iterm problem to me.

**Comment by vaxXxa** [comment]
Yeah, I posted this bug 6 month ago to iterm helpdesk. But just for sure, I've posted also here, cause term + nvim works fine, iterm+tmux+nvim rises blinking error.

Interesting fact with different layouts.. I guess, that I have problem depends on width of viewport (width = 80 characters, or 300 – maybe this causes the render problem)

**Comment by nicm** [comment]
The scroll region only works over the full terminal width so when panes do not cover the full width we cannot use a scroll region and instead redraw the pane differently.

**Comment by vaxXxa** [comment]
So, maybe that's a problem? Half-width pane works better then full-width.

**Comment by nicm** [comment]
Yes probably there is a bug in the way they are doing the scroll region.

**Comment by vaxXxa** [comment]
So, it's definitely the iterm bug and I must write an issue to iterm, right?

**Comment by nicm** [comment]
Pretty sure. Can you reproduce in xterm?
