### ISSUE TITLE
some kind of screen corruption

### ISSUE THREAD

**Issue by hiciu** [tmux/tmux#1040]
tmux version: 2.4, 2.5 and current git master
platform: linux
possible to reproduce without config: yes
terminal: alacritty
TERM outside: screen-256color
TERM inside: screen (when tested without config, `tmux -f /dev/null ...`) or screen-256color (when tested with config)

output of `uname -sp && tmux -V && echo $TERM`:
```
[hiciu@unknown tmux]$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.5
screen-256color
```

reproducible on current git master: yes
logs from `tmux -vv -Ltest -f/dev/null new`: [client](http://hiciu.org/2017-08-17-tmux/tmux-client-667252.log), [server](http://hiciu.org/2017-08-17-tmux/tmux-server-667254.log)

---

Hello,

I'm very sorry about vague bug report, hopefully you can help me with futher debugging / information gathering.

Somewhere between versions 2.3 and 2.4 something changed with regards to right margin handling. It's really hard to explain as I don't really understand what is going on; please see this video:

http://hiciu.org/2017-08-17-tmux/output-2017-08-17_14_04_20-tmux-current-head.mkv

I'm executing `/)`, then repeating that search few times with `n` and after that I'm using move commands. You can notice some kind of corruption on screen - it looks like some of the lines are duplicated until vim repaints them. For completness, here I'm trying to reproduce this with 2.3, where everything works correctly:

http://hiciu.org/2017-08-17-tmux/output-2017-08-17_14_37_38-tmux-2.3.mkv

And here is 2.4:

http://hiciu.org/2017-08-17-tmux/output-2017-08-17_14_36_59-tmux-2.4.mkv

I can reliably reproduce this issue with vim running under tmux, but only when I'm using specific terminal emulator. It also happens with other applications under tmux, not only vim (but I don't have any examples right now). I cannot reproduce this with empty vim configuration. I cannot reproduce this when running vim directly on the terminal emulator. Corruption is visible under these terminal emulators:

- alacritty (with TERM=screen-256color and TERM=xterm-256color)
- kitty
- terminology (with TERM=screen-256color and TERM=xterm-256color)

And I cannot reproduce this behavior under these:

- sakura (with TERM=screen-256color and TERM=xterm-256color)
- xterm (tested only with TERM=xterm)
- urxvt (tested with TERM=rxvt-unicode-256color, TERM=xterm-256color and with TERM=screen-256color)
- st
- lxterminal

For the record I'm setting TERM variable before running tmux. At this point I don't believe TERM variable has anything to do with it.

The issue does not occur if I have some other client attached to the same window. That means: if I attach to already-corrupted window the corruption persist on the old window, but new window seems fine. Please see the attached video of alacritty with urxvt in the background:

http://hiciu.org/2017-08-17-tmux/output-2017-08-17_14_52_41-tmux-with-second-client.mkv

Everything was fine as long as tmux client running on urxvt was attached. I have the same results if there is some other terminal emulator instead of urxvt (for example, 2x alacritty).

I've tried to bisect this with `git bisect`, here are the results:

	There are only 'skip'ped commits left to test.
	The first bad commit could be any of:
	3bb14001b9a9a5665c7dcac542dc49841e1b3c58
	74c40d04eadc40c034634d70925355a0751c1433
	33ebb9ec39e175197b9a7ba7071aeea472f76e8b
	We cannot bisect more!

And `git bisect log`:

	$ git bisect log
	git bisect start
	# good: [52869ed182482c26163799a7215139f4d81b6fca] Release tmux 2.3
	git bisect good 52869ed182482c26163799a7215139f4d81b6fca
	# bad: [f21cb71fbe79c8949edc3c1d300aa783382a0d77] Enter date of release.
	git bisect bad f21cb71fbe79c8949edc3c1d300aa783382a0d77
	# bad: [f20e3ee62c310da3eb091a2773e21442412db4ed] We need VIS_DQ in vis.h as well.
	git bisect bad f20e3ee62c310da3eb091a2773e21442412db4ed
	# good: [a44024a795164d627833450133c6275dfcdba0b3] Note about TERM.
	git bisect good a44024a795164d627833450133c6275dfcdba0b3
	# good: [45dbbb78b0f8865475ef262d45465f3faafd3500] Merge branch 'obsd-master'
	git bisect good 45dbbb78b0f8865475ef262d45465f3faafd3500
	# good: [8f79b079cd5be1e63fb4e05c389c4334c5e7882a] Merge branch 'obsd-master'
	git bisect good 8f79b079cd5be1e63fb4e05c389c4334c5e7882a
	# bad: [d4cb178249c6c73c6197e34e871c2b8e803de175] Merge branch 'obsd-master'
	git bisect bad d4cb178249c6c73c6197e34e871c2b8e803de175
	# bad: [33ebb9ec39e175197b9a7ba7071aeea472f76e8b] Merge branch 'obsd-master'
	git bisect bad 33ebb9ec39e175197b9a7ba7071aeea472f76e8b
	# skip: [3bb14001b9a9a5665c7dcac542dc49841e1b3c58] Add some missing special keys to key_string_lookup_key, fix a mouse check in server_client_handle_key, and tweak a comment.
	git bisect skip 3bb14001b9a9a5665c7dcac542dc49841e1b3c58
	# good: [0d19d78fff40fbf57c557698f29049dcd1b1ca7b] Merge branch 'obsd-master'
	git bisect good 0d19d78fff40fbf57c557698f29049dcd1b1ca7b
	# skip: [74c40d04eadc40c034634d70925355a0751c1433] Be less aggressive about turning margins off.
	git bisect skip 74c40d04eadc40c034634d70925355a0751c1433
	# good: [d87ab0cadf6ee30f253a815ebc80c14d2818391d] Merge branch 'obsd-master'
	git bisect good d87ab0cadf6ee30f253a815ebc80c14d2818391d
	# only skipped commits left to test
	# possible first bad commit: [33ebb9ec39e175197b9a7ba7071aeea472f76e8b] Merge branch 'obsd-master'
	# possible first bad commit: [74c40d04eadc40c034634d70925355a0751c1433] Be less aggressive about turning margins off.
	# possible first bad commit: [3bb14001b9a9a5665c7dcac542dc49841e1b3c58] Add some missing special keys to key_string_lookup_key, fix a mouse check in server_client_handle_key, and tweak a comment.

Based on this I would say commit 74c40d04eadc40c034634d70925355a0751c1433 introduced problem. If do `git checkout f20e3ee62c310da3eb091a2773e21442412db4ed` followed by `git revert 74c40d04eadc40c034634d70925355a0751c1433` then the issue is fixed, but I cannot do the same on 2.4 tag (on 2.4 after reverting 74c40d04eadc40c034634d70925355a0751c1433 corruption seems to be even worse).

**Comment by nicm** [comment]
These logs are not from master, please show me logs from master.

Do not use TERM screen-256color outside tmux unless you are running tmux inside screen or tmux.

**Comment by hiciu** [comment]
Logs from the master: [tmux-server](http://hiciu.org/2017-08-17-tmux/tmux-server-690726.log), [tmux-out](http://hiciu.org/2017-08-17-tmux/tmux-out-690726.log), [tmux-client](http://hiciu.org/2017-08-17-tmux/tmux-client-690724.log).

Current settings: TERM=xterm-256color outside (default for alacritty), TERM=screen inside (this is without config, with `-f/dev/null`).

**Comment by townba** [comment]
I suspect that the three emulators that show the problem don't implement everything correctly.

Can you try adding the line `set -ags terminal-overrides ",xterm-*:csr@"` to your `.tmux.conf` and see if that helps?

**Comment by hiciu** [comment]
> Can you try adding the line set -ags terminal-overrides ",xterm-*:csr@" to your .tmux.conf and see if that helps?

Thank you very much! That command has fixed the issue, now everything looks fine.

I guess this is only temporary workaround and I should open a bug report with alacritty project (and perhaps other terminals I've tested)?

**Comment by nicm** [comment]
I can't see any problems with tmux master and a terminology built from their Git repository. Can you please try these versions and see if you can reproduce?

**Comment by nicm** [comment]
Terminology appears to have some odd behaviour with scroll regions and margins.

Firstly, ED2 seems to reset the bottom of the scroll region. For example compare this in xterm and terminology:
~~~~
printf '\033[10;20r\033[H\033[2J'; seq 100
~~~~
ED0 and ED1 seem to be OK. 

Secondly, a newline at the right hand of the margin does not correctly keep the cursor within the margins. Compare this in xterm and terminology:
~~~~
printf '\033[?69h\033[20;30s\033[1;20H\033[2J'
x="01234567890"; printf "$x\n$x"
sleep 1000
~~~~

The first is probably not an issue for tmux; I suspect the second is. tmux started using margins between 2.3 and 2.4 so that would fit in with what you are seeing.

Perhaps @billiob can advise here?

**Comment by billiob** [comment]
Thanks for the heads-up. I'll have a look.

**Comment by hiciu** [comment]
I can reproduce this issue with terminology (version 50c14419e0002a29a3a36aaab6cd6e06c27fc056) and tmux (07a13697e10af0a4eee1c158cef679be177fb6e7) without `csr@` option in `tmux.conf`. With `csr@` it works correctly.

I can also confirm that terminology and alacritty are behaving differently from xterm with second test:
alacritty:
![alacritty](https://user-images.githubusercontent.com/1618371/29499217-b599f058-860c-11e7-8226-f493308365a6.png)
terminology (both current master and 1.0.0 are looking the same):
![terminology](https://user-images.githubusercontent.com/1618371/29499218-b59c41a0-860c-11e7-814e-1ac91647c662.png)
xterm:
![xterm](https://user-images.githubusercontent.com/1618371/29499216-b596dbac-860c-11e7-88ff-21d0e017350c.png)

**Comment by nicm** [comment]
As far as I can tell these three terminals (terminology, alacritty, kitty) are unrelated (they seem to be written in three different languages anyway), so probably this is just a case where this (\n at right edge of margin) is something easy to miss. Of course, unless someone has an actual VT420 lying around to check, we are probably left assuming xterm is correct (and there is at least one bug in xterm's margin support too...).

**Comment by nicm** [comment]
Note it is actually \r that is incorrect not \n (the tty will emit \r\n for \n in my example).

I am not entirely certain this is causing the actual issue you are seeing though, I don't see that tmux assumes what \r will do with the cursor in the margins. In fact it would seem to assume it goes to 0 as well.

Can you see if this makes any difference? [x.diff.txt](https://github.com/tmux/tmux/files/1240138/x.diff.txt)

**Comment by nicm** [comment]
I can't see anything else obviously wrong with margins or scroll regions in terminology and it all seems fine with tmux for me in any case.

**Comment by hiciu** [comment]
Unfortunately the attached patch doesn't help with that issue (screen is garbled with both alacritty and terminology).

![2017-08-21-230625_774x445_scrot](https://user-images.githubusercontent.com/1618371/29538307-7dc7fce2-86c5-11e7-8eec-abbffcf29436.png)

**Comment by nicm** [comment]
OK I think these problems with margins are a red herring; it is something to do with the scroll region rather than margins (disabling CSR turns them both off).

**Comment by nicm** [comment]
@hiciu can you please show me a screenshot like the one above and also the corresponding tmux logs from generating that screenshot? That is, run tmux -f/dev/null -Ltest -vv new then reproduce to that state, then take a screenshot, exit tmux and show me both screenshot and the server log. Use tmux master please.

**Comment by hiciu** [comment]
Sure. That should be tmux master with the patch or without the patch?

**Comment by nicm** [comment]
Without the patch.

**Comment by billiob** [comment]
In case it can help, I've pushed a fix for the bottom margin issue: https://github.com/billiob/terminology/commit/2343efd6a13606ad05a61f30adcbb284b3c464f5
I'm still investigating the other issue.

**Comment by hiciu** [comment]
screenshot: ![2017-08-21-233530_802x458_scrot](https://user-images.githubusercontent.com/1618371/29539271-76374b00-86c9-11e7-96cb-e70fd26112ea.png)
logs:
http://hiciu.org/2017-08-17-tmux/tmux-server-398502.log 
http://hiciu.org/2017-08-17-tmux/tmux-out-398502.log
http://hiciu.org/2017-08-17-tmux/tmux-client-398500.log

**Comment by nicm** [comment]
@hiciu @billiob  I have found the problem. Terminology is scrolling the scroll region when it sees a linefeed, even if the cursor is actually below the scroll region. Compare this with xterm:
~~~~
printf '\033[H\033[2J\033[10;20r'
seq 1000
printf '\033[21;1H\n'
sleep 3
~~~~
So with a scroll region of lines 10-20, it is behaving for a linefeed on line 21 as if it the cursor was on line 20.

It appears that it (correctly) doesn't scroll if the cursor is above the last line of the scroll region, it's only if it is below the last line.

You can also see the difference if you cat this file which is based on what tmux is sending: [xtest.txt](https://github.com/tmux/tmux/files/1240308/xtest.txt)

**Comment by nicm** [comment]
Best to "clear;cat xtest.txt;sleep 100" for the test file.

**Comment by nicm** [comment]
It is easier to see with more \n:
~~~~
printf '\033[H\033[2J\033[10;20r'
seq 1000
printf '\033[21;1H\n\n\n\n\n'
sleep 10
~~~~

**Comment by hiciu** [comment]
xtest.txt test results for xterm, terminology and alacritty:
![2017-08-22-011106_484x316_scrot](https://user-images.githubusercontent.com/1618371/29541810-d621d03c-86d6-11e7-85d7-f92671dc6a63.png)
![2017-08-22-011110_802x458_scrot](https://user-images.githubusercontent.com/1618371/29541809-d6207494-86d6-11e7-9f1d-ee748f19b8dc.png)
![2017-08-22-011114_800x453_scrot](https://user-images.githubusercontent.com/1618371/29541808-d6201328-86d6-11e7-9f5f-d7aad66fd916.png)

**Comment by nicm** [comment]
@hiciu it would be best if you reported this to alacritty.

**Comment by hiciu** [comment]
Alacritty has just been fixed (https://github.com/jwilm/alacritty/commit/866668711c8feb6904b7f47a3f5e8458cdbf8500). 

Thank you very much for the help and such awesome software @nicm.

**Comment by billiob** [comment]
I should have those issues in Terminology.
@hiciu could you please try again?

**Comment by hiciu** [comment]
@billiob I have tested https://github.com/billiob/terminology/commit/9abf6520035be7720b42e72b8bdf74739a125957 and the issue with tmux + vim is gone. Thank you very much!

**Comment by billiob** [comment]
@hiciu Thank you for testing it. I'll make a bugfix release soon.
@nicm Thanks for the great bug report
