### ISSUE TITLE
Feature Request: History Divider / Bookmark

### ISSUE THREAD

**Issue by acook** [tmux/tmux#1042]
# The Feature

A visual divider which allows users to jump back into the history/scrollback to the given divider.

# Purpose

Recent activity dividers, generic history bookmarks.

# Mockup

<img width="664" alt="screen shot 2017-08-18 at 12 00 42 pm" src="https://user-images.githubusercontent.com/71984/29469223-f2581da0-840c-11e7-8c8e-4336834c67fc.png">

# Work-around

As in the above mockup, it's using command which prints a terminal-width divider, it can also be modified to increment or produce UUIDs for markers (in the above script it's static for demonstration purposes) and then the marker text can be searched in tmux's scrollback. 

# References

- #758 - A closed issue which mentions similar functionality
- This below Colloquy screenshot shows a plain activity marker in the chat (visible as just a simple line across the chat history)
<img width="664" alt="Colloquy" src="https://dev.adiirc.com/attachments/download/263/Colloquy_theme.png">

**Comment by nicm** [comment]
Added this to TODO file.

**Comment by ThomasAdam** [comment]
Although still a WIP, those of you wishing for this feature can have a look here:

https://github.com/ThomasAdam/tmux/tree/ta/marker

To use this:

```
set -g monitor-activity
set -g monitor-activity-marker
```

That is to say, the activity-marker only works if `monitor-activity` is set.

Should you wish to change the style of the activity-marker you can do so with:

```
set window-activity-marker-style 'fg=white'
```

Currently in both `copy-mode` and `copy-mode-vi` the key `a` is bound to the command `activity-marker` to jump to the last marker.  This is of course configurable.

Feedback welcome from a usability point of view, as I'm still not convinced this is at all useful.
