### ISSUE TITLE
'set user-keys[0] ...' requires literal ESC char at the string

### ISSUE THREAD

**Issue by avih** [tmux/tmux#1043]
Using current latest git master 07a13697 (2017-08-17)

I'm trying to bind C-Tab and C-S-Tab and it doesn't work as-is in mintty (msys2/cygwin - after disabling ctrl-[shift]-tab from cycling mintty windows) - it just bells.

When using ctrl+v inside or outside of tmux it prints `^[[1;5I` and `^[[1;6I` (capital i) respectively, and I'm trying to bind those using the new `user-keys` command, and my issue is how to convey the ESC char at the beginning of the string.

The manual gives the example of `set -s user-keys[0] '\[5;30012~'`, however, this appears to be an incorrectly formatted escaping in `tmux.1` - which contains the following line: `set -s user-keys[0] '\e[5;30012~'`, so the `e` got escaped out when reading the manual via `man`.

So, I tried `'\e[1;5I'` and `'\[1;5I'` and `'\\e[1;5I'` and `'^[[1;5I'` and `'\033[1;5I'` and even `'[1;5I'` and none of those bound ctrl+tab. The only way I succeeded in binding it was inserting the actual ESC char (ascii 27) into the string at tmux.conf: `set -s user-keys[0] '<actual char 27>[1;5I'` .

Assuming it's not just a glitch on my system, I think there are two issues:
1. The manual seem to accidentally omit the `e` in `'\e[5 ...'` .
2. Tmux doesn't seem to be able to interpret `'\e...'` correctly.
3. If the original intent was that the user inserts unprintable characters (ESC) into `tmux.conf`, then I think it's quite unfriendly, and possibly unexpected.

Regardless of fixing the interpretation of `\e`, maybe tmux should just assume it starts with an escape char such that the user only has to do `set -s user-keys[0] '[1;5I'` where the leading ESC is implicit? Are there escape sequences which don't start with the escape char? (as silly as it sounds...)

**Comment by nicm** [comment]
Yes it should be:
~~~~
diff -u -p -r1.574 tmux.1
--- tmux.1      17 Aug 2017 08:37:38 -0000      1.574
+++ tmux.1      19 Aug 2017 20:39:54 -0000
@@ -2912,7 +2912,7 @@ and so on.
 .Pp
 For example:
 .Bd -literal -offset indent
-set -s user-keys[0] '\e[5;30012~'
+set -s user-keys[0] "\ee[5;30012~"
 bind User0 resize-pane -L 3
 .Ed
 .It Xo Ic visual-activity

**Comment by avih** [comment]
Right, it also needs double quote rather than single quote. So these indeed work as expected:
```
set -gw user-keys[0] "\e[1;5I"
set -gw user-keys[1] "\e[1;6I"
bind-key -n User0 select-pane -t+
bind-key -n User1 select-pane -t-
```

Also, you noted here https://github.com/tmux/tmux/issues/786#issuecomment-280922363 that:
> Or use \E instead of \e, I think that will work.

However, `\E` didn't work for me neither with single nor with double quotes.

As for this issue, I'm leaving it open as a reminder since the fix to `tmux.1` wasn't pushed yet. But indeed it's only an issue with the manual.

Thanks.

**Comment by nicm** [comment]
\E only works in terminal-overrides

**Comment by nicm** [comment]
Fixed thanks.
