### ISSUE TITLE
No syntax highlighting in neovim

### ISSUE THREAD

**Issue by chrisbra** [tmux/tmux#1046]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING
(will attach all information I have).

When running neovim inside tmux in a putty terminal, I do not see any colors. Usually, I would just stick into my `.vimrc` a `:set t_Co=256` to force Vim to assume a 256color capable terminal, however the neovim folks removed that feature <sigh>.

Can be reproduced with `tmux -vv -Ltest -f/dev/null new`.  please advise how to fix this issue.

tmux-version: 2.3
$TERM: putty-256color
$TERM inside tmux: screen or tmux (does not matter)
[tmux-server.log](https://www.256bit.org/~chrisbra/zeugs/tmux-server.log)

**Comment by nicm** [comment]
Use TERM=tmux-256color inside tmux

**Comment by chrisbra** [comment]
thanks. That works. Is there a reason, why tmux does not automatically export this for color terminals? It doesn't even do it, if I explicitly call it with `-2`

**Comment by nicm** [comment]
Many platforms do not have a new enough terminfo

**Comment by chrisbra** [comment]
I see. Thanks.
