### ISSUE TITLE
Feature Request: toggle between two panes like screen "Ctrl-a a"

### ISSUE THREAD

**Issue by HariSekhon** [tmux/tmux#1047]
Feature Request for a command to toggle back and forth between two panes without having to know the number or next/previous.

This is useful when editing something in one pane, and running a test command in the other and is something I use frequently in screen.

**Comment by AaronVanGeffen** [comment]
You can already do this by binding a key to `last-window` in your tmux config. For example:
```
bind-key ^A last-window
```

**Comment by HariSekhon** [comment]
Thanks I'll try that
