### ISSUE TITLE
select-pane binding works for horizontal split but not vertical

### ISSUE THREAD

**Issue by kevinclevenger** [tmux/tmux#1048]
With the binding below I can change panes in a horizontal split, but with a vertical split M-S-Left/M-S-Right execute previous-window/next-window

config
Linux 
tmux 2.5-3
tmux TERM & shell TERM: screen-256color

.tmux.conf
bind-key -n M-Left     previous-window
bind-key -n M-Right    next-window
bind-key -n M-S-Down   select-pane -D
bind-key -n M-S-Left   select-pane -L
bind-key -n M-S-Right  select-pane -R
bind-key -n M-S-Up     select-pane -U  

Prefix-?
bind-key    -T root         M-Left            previous-window                                         
bind-key    -T root         M-Right           next-window                                             
bind-key    -T root         M-S-Up            select-pane -U                                          
bind-key    -T root         M-S-Down          select-pane -D                                          
bind-key    -T root         M-S-Left          select-pane -L                                          
bind-key    -T root         M-S-Right         select-pane -R

**Comment by nicm** [comment]
What TERM outside tmux? What terminal?

**Comment by kevinclevenger** [comment]
What TERM outside tmux? 
tmux TERM: screen-256color
outside TERM: tried both screen-256color and rxvt-256color with same result

What terminal?
rxvt-unicode 9.22-3

**Comment by nicm** [comment]
If you run cat outside tmux, then press M-Left and M-S-Left, what do you see for each?

**Comment by kevinclevenger** [comment]
"If you run cat outside tmux ..."

Did you really mean "cat" there? If you did can you please be more specific about what's needed and wanted and the sequence required.

**Comment by nicm** [comment]
Run cat then press the keys and tell me what it shows.

**Comment by nicm** [comment]
Or show logs from tmux of you pressing the keys, that would be fine too.

**Comment by kevinclevenger** [comment]
Outside Tmux
M-Left : ^[^[[D
M-Right : ^[^[[C
M-S-Left : ^[^[[d
M-S-Right : ^[^[[c

In Tmux (unbound all the R/L/U/D keys, xterm-keys on)
M-Left : ^[^[[D
M-Right : ^[^[[C
M-S-Left : ^[^[[1;2D
M-S-Right : ^[^[[1;2C
TERM rxvt-unicode-256color or screen-256color, same result

**Comment by nicm** [comment]
Hmm. M-S-Left should be \033[1;4D not \033\033[1;2D, so it looks like tmux is seeing it as Escape+S-Left.

Show me logs please from starting tmux, pressing the keys and then exiting tmux, and also your .tmux.conf.

**Comment by nicm** [comment]
Oh this may be because rxvt-unicode-256color lists kLFT (S-Left) but not kLFT4 (M-S-Left). If tmux sees a modified function key it assumes it is complete (that is, that Escape+S-Left is an actual Escape+S-Left, not M-S-Left - if M-S-Left exists it will also be given in kLFT4). We need to do this to avoid problems with vi.

Try adding kLFT4 as well and see if it works then:

set -as terminal-overrides ',rxvt-unicode*:kLFT4=\E\E[d:kRIT4=\E\E[c:kUP4=\E\E[a:kDN4=\E\E[b'

Make sure TERM outside tmux is rxvt-unicode or rxvt-unicode-256color.

**Comment by kevinclevenger** [comment]
No joy with the terminal overrides

[tmux_debug_20170828-2.zip](https://github.com/tmux/tmux/files/1257716/tmux_debug_20170828-2.zip)

Config:
set-window-option -g xterm-keys on
set -g prefix C-f
bind C-f send-prefix
bind-key -n M-S-Down   select-pane -D
bind-key -n M-S-Left   select-pane -L
bind-key -n M-S-Right  select-pane -R
bind-key -n M-S-Up     select-pane -U
bind-key -n M-Left     previous-window
bind-key -n M-Right    next-window
bind | split-window -h
bind - split-window -v
set-option -g status on
set -g status-interval 5
set -as terminal-overrides ',rxvt-unicode*:kLFT4=\E\E[d:kRIT4=\E\E[c:kUP4=\E\E[a:kDN4=\E\E[b'
run-shell ~/src/tmux-logging/logging.tmux

**Comment by nicm** [comment]
OK this code doesn't work the way I intended, please try this diff: [x.diff.txt](https://github.com/tmux/tmux/files/1257902/x.diff.txt) (you will need to keep the terminal-overrides).

**Comment by kevinclevenger** [comment]
Yes, that patch fixes the problem when using terminal-overrides

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks

**Comment by kevinclevenger** [comment]
Thank you so much for your efforts!
