### ISSUE TITLE
tmux server sometimes crashes when 1x1 clients attach

### ISSUE THREAD

**Issue by chrysn** [tmux/tmux#1049]
When clients with ridiculously small window sizes attach to a running tmux server, this can make the server crash. The following steps-to-reproduces are obviously not realistic examples, but are a reproducible way of making a things crash that previously only happened under race conditions between terminal emulators starting up and the window manager resizing them. (Especially, I don't know which component in the window-manager/terminal-emulator/pty chain is responsible for creating 1x1 windows, but IMO no matter which bug a component there has, it shouldn't crash tmux).

Steps to reproduce (with an empty config):
* Have a terminal that you can resize down to 2 column and 1 row. I'm using xfce4-termnal with a large font size, and the i3 window manager with floating windows (Win-Shift-Space to make floating, Win-rightclick to resize in default configuration).
* Prepare three terminal windows: Number 1 regular-sized, number 2 2x1, and number 3 2x1.
* In window 1, start tmux, detach, start tmux again, detach, and start tmux a third time.
* In window 2, run `tmux attach -t0`
* In window 3, run `tmux attach -t1`
* All tmux clients quit, and window 1 shows "[lost server]".

This was tested on Debian GNU/Linux with the following versions:

guest@hephaistos:~$ uname -sp && tmux -V && echo "$TERM"
Linux unknown
tmux 2.5
xterm-256color

This was all tested with the current master branch 1492c9d7, built using the building infrastructure of the Debian package version 2.5-3; I added a few debug statements to pin down failure path, so some lines in the logs might be my doing. The issue was also observed with 2.5 as packaged in Debian as 2.5-3.

Log file: [tmux-server-16380.log.txt](https://github.com/tmux/tmux/files/1251890/tmux-server-16380.log.txt)

**Comment by nicm** [comment]
tmux -Ltest kill-server
tmux -Ltest new -d\; new -d\; new -d

stty rows 1 cols 2
tmux -Ltest a -t0

stty rows 1 cols 2
tmux -Ltest a -t1

**Comment by nicm** [comment]
The problem is that we want to establish a valid (session, window, pane) but a 1x1 session does not have any valid panes.

I don't see why cmd_find_* needs to worry if the pane is visible - why shouldn't you be able to target a pane that is invisible? Anywhere that cares should check that itself, and I think most do.

Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1252069/x.diff.txt)

**Comment by chrysn** [comment]
the patch applies only with offsets/fuzz to the master version i tested with, but it compiles and the crashes did not show up any more with it applied.

thanks for the quick fix!

**Comment by nicm** [comment]
Applied now, thanks.
