### ISSUE TITLE
About tmux's use of /usr/bin/script

### ISSUE THREAD

**Issue by tiferrei** [tmux/tmux#1052]
Hello there,
I am currently working with Apple to debug a bug where `/usr/bin/script` seems to be evoking `/bin/date` and setting incorrect system dates. I would like to know if you could enlighten me by describing `tmux`'s usage of `script`. If it is used for example to log sessions or the output. Any help right now would be greatly appreciated. I personally do not use `script` but `tmux` might internally. My other option is iTerm, as it also logs command output, I have already contacted the code maintainer and they are looking into it.

Thank you for your time,
Tiago Ferreira

**Comment by nicm** [comment]
tmux does not use script

**Comment by tiferrei** [comment]
Thank you very much for the quick reply, one less thing to debug then. :)
Have a good day.
