### ISSUE TITLE
Unable to install from source.

### ISSUE THREAD

**Issue by agirorn** [tmux/tmux#1054]
The install instructions say run `./configure` this file does not exist on a fresh clone of the project. Assume you have to run `autoconf` first.

When I run `autoconf` it generates the `configure` script but it also outputs these errors

```shell
configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:26: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:43: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:90: error: possibly undefined macro: AC_SEARCH_LIBS
```

When I then run ./configure it fails.

```shell
./configure 
configure: error: cannot find install-sh, install.sh, or shtool in etc "."/etc
```

Version: This is on current master: e941e532fac25237a7902ebda7e36a5c86c4e638
platform: "Ubuntu 16.04.3 LTS"

**Comment by agirorn** [comment]
I got the install working by run `autoreconf --install`, maybe that should be added to the README file.

**Comment by nicm** [comment]
You need automake and to run autogen.sh like it says in README.
