### ISSUE TITLE
[Question] Making MouseDown1Pane clear selection and put cursor where I clicked

### ISSUE THREAD

**Issue by maximbaz** [tmux/tmux#1055]
* Arch Linux
* tmux 2.5
* tmux-256color
* alacritty terminal

Hello,

I'm trying to achieve the following: when I am in the copy mode, I want mouse click to cancel the current selection and place cursor to the place where I clicked. The minimal `.tmux.conf` that _almost_ achieves it is the following:

```
set -g default-terminal tmux-256color
set -g mouse on
set -g mode-keys vi
bind -T copy-mode-vi MouseDown1Pane select-pane \; send -X clear-selection
```

It just has one problem - the cursor is lagging behind on one step every time. I'll try to explain below.

Suppose I start a new tmux session and this is the entire output in my terminal:

```
> /home
```

I enter `copy-mode`, then click with a mouse slowly three times, (1) `m`, (2) `o`, (3) `e`. When I do that, after every step the cursor position jumps at (1) `>`, (2) `m`, (3) `o`. In other words, after the first click the cursor jumped to the (0,0) coordinate, after the second click it jumped to where I clicked for the first time, and on the third click it jumped to where I clicked for the second time. It always lags behind one step.

Is it just a matter of refreshing cursor position, maybe some kind of a command that I can add to my binding? I tried extending it as `bind -T copy-mode-vi MouseDown1Pane select-pane \; send -X clear-selection \; send -M`, but that has no effect.

**Comment by nicm** [comment]
Try this please:
~~~~
Index: window-copy.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/window-copy.c,v
retrieving revision 1.182
diff -u -p -r1.182 window-copy.c
--- window-copy.c	29 Aug 2017 20:26:25 -0000	1.182
+++ window-copy.c	3 Sep 2017 10:48:41 -0000
@@ -2454,7 +2454,7 @@ window_copy_move_mouse(struct mouse_even
 	if (wp == NULL || wp->mode != &window_copy_mode)
 		return;
 
-	if (cmd_mouse_at(wp, m, &x, &y, 1) != 0)
+	if (cmd_mouse_at(wp, m, &x, &y, 0) != 0)
 		return;
 
 	window_copy_update_cursor(wp, x, y);
~~~~

**Comment by maximbaz** [comment]
That helps! @nicm

**Comment by nicm** [comment]
Applied to OpenBSD now, should be in GitHub later. Thanks!
