### ISSUE TITLE
tmux a \; split-window -v \; detach-client closes tmux

### ISSUE THREAD

**Issue by Gregregorovich** [tmux/tmux#1056]
tmux version 2.5-1.2
OS: OpenSUSE Tumbleweed x86_64
terminal: xterm-256-color

I'm attempting to run an automated script that attaches to a tmux session, runs a command, and then detaches from the session. Am I doing something wrong here? I haven't built from source, but I suspect there's a better way to do what I'm accomplishing. This was really easy to do in screen :b - though I much prefer the interface of tmux...

    $ tmux new-session -t tmux -d
    $ tmux attach -t tmux \; split-window -v \; detach-client
    [detached (from session tmux-0)]
    $ tmux a
    no sessions

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by Gregregorovich** [comment]
With master, this does not happen.
Sorry, was having real trouble getting the right version of ncurses installed so I could build it. I see tmux 2.6 has been released - I'll see if installing that fixes it.

**Comment by Gregregorovich** [comment]
I was hoping for the OpenSUSE Build Service to have someone package 2.6, but noone has yet.
I can confirm 2.6-rc, released 11 days ago does work, the same as my previous comment, the same as master.
I can also confirm that 2.5, released on 9 May, downloaded from https://github.com/tmux/tmux/releases , does not work; ie performs as in my original post; ie is broken somewhere.
The fact that this has been fixed in 2.6 is good, so looks like I'll have to alias tmux to $(path-to-)/tmux until such a time as Tumbleweed updates to 2.6 : )

**Comment by nicm** [comment]
Great thanks.
