### ISSUE TITLE
new choose-tree doesn't always show selection line

### ISSUE THREAD

**Issue by frosencrantz** [tmux/tmux#1059]
The new choose-tree mode doesn't always show the selection line.  When first entering choose-tree mode with more than a screen worth of windows, the selection line is below the visible part of the list when there are previews.

Building from current github head.

Sometimes is appears hidden just below the line that shows the sort order.  I can do this by hitting the End key, to get the selection line to end of the list of items.

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/1287133/x.diff.txt)

**Comment by frosencrantz** [comment]
The issue happens when:
1) There so many panes/windows, the tree doesn't fit on the pane..
2) I hit C_END
3) The cursor line is one line off the visible screen (seems like an off by one error)

The patch/code seems to make this worst when I toggle previews('v'), in that if I hit C_END, and then 'v' it moves the cursor up a line every time I hit 'v'.  That seems broken.  I moved the cursor to the last line of the tree, it should stay there.  The view port should change to make that last line visible.

**Comment by nicm** [comment]
Please try this instead: 
[y.diff.txt](https://github.com/tmux/tmux/files/1287797/y.diff.txt)

**Comment by frosencrantz** [comment]
That appears to work better, especially now when I enter choose-tree mode, it shows the cursor on the current pane, and it is visible.

But if I hit C_HOME, and then C_END, there still appears to be the off by one error, the cursor is on the last line, but the cursor is just off the visible screen by one line.

**Comment by nicm** [comment]
Try this please: [z.diff.txt](https://github.com/tmux/tmux/files/1287908/z.diff.txt)

**Comment by frosencrantz** [comment]
Yes, that appears to work.  Thank you.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
