### ISSUE TITLE
Leaving the copy mode with copy-pipe

### ISSUE THREAD

**Issue by samuelsimoes** [tmux/tmux#106]
Today we can use the `-x` flag on the `copy-selection` to not leave the copy mode when make the copy (example: `bind-key -t vi-copy y copy-selection -x`), but there's some way to use this with `copy-pipe`, which continues leaving after copy?

**Comment by nicm** [comment]
No it doesn't work with copy-pipe at the moment.

-------- Original message --------

**Comment by nicm** [comment]
Added to the TODO file.

**Comment by michalre** [comment]
Any hint when this can be available? It slows me down a lot when I need to scroll back to the same place in a long program output every time I copy something to clipboard.

Btw. Thanks for the tmux, it is very usable and well designed, I use it all the time.

**Comment by samuelsimoes** [comment]
@michalre I made a fork with this adjustment. I didn't make de pull request because I don't know if this change makes sense or if it could break something.

https://github.com/samuelsimoes/tmux/commit/b2f82936e930a077517c03ed41fc92cfdf19b568

@nicm ☝️ this make sense?

**Comment by nicm** [comment]
No... this will never exit copy mode, it needs to do it when arg == NULL the same COPYSELECTION.

**Comment by nicm** [comment]
Except it can't, because the arg is used for -e.

**Comment by iamFIREcracker** [comment]
Hello everyone,

Could you please confirm this has been fixed inside 391f5fd?  I quickly skimmed through the PR but I couldn't find anything related -- except the issue number in the description.

Like @samuelsimoes I am looking for a way to execute 'copy selection and exit copy-mode' with a single keystroke, but as of today (I am using 2.4) I am forced to copy first, and then manually exit copy-mode.

**Comment by iamFIREcracker** [comment]
> Like @samuelsimoes I am looking for a way to execute 'copy selection and exit copy-mode' with a single keystroke, but as of today (I am using 2.4) I am forced to copy first, and then manually exit copy-mode.

Nevermind, I did not know the existence of `copy-pipe-and-cancel`!
