### ISSUE TITLE
Tmux stuck when "echo" a special string

### ISSUE THREAD

**Issue by shiloong** [tmux/tmux#1060]
VERSION:
Tmux 2.3 and GIT master
PLATFORM:
Linux xxx 3.17.8-13.NSN.el6.x86_64 #1 SMP Tue Mar 28 20:56:38 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

ISSUE:
When running commandline:
echo -e "\EXblah"
Tmux will be stuck, actually, it's the terminal/shell is stuck, cannot response for any keyin, looks like:
---
$ echo -e "\EXblahblah"
(cursor is stuck for ever...)
---

OUTSIDE TMUX:
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux master
xterm

INSIDE TMUX:
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux master
screen

Thanks!

**Comment by nicm** [comment]
Yes you have to terminate \033X or \033^ by ST (\033\\), tmux will wait until it sees that.

**Comment by nicm** [comment]
Note that all other terminals will behave the same - this is not a bug. In master we have a timeout for some of this kind of stuff but I am not sure we should do it for these because TBH I don't know what they are used for.

**Comment by shiloong** [comment]
Hi,
Thanks for your reply!
But it seems the older version 2.1 have no this issue, why?
