### ISSUE TITLE
tmux garbage character when execute tail -f command

### ISSUE THREAD

**Issue by dslztx** [tmux/tmux#1061]
I use tmux as a beginner.

I use gnome terminal in Ubunutu 16.04.I split the window into 4 panes.When I execute tail -f FILE command in the top-right pane,so much content is emerging.At the same time,I find that some garbage characters come out in the left margin on the top-left pane?

How could I do to solve the problem?

thanks very much.

I use tmux 2.1.My tmux conf content is as follows:
```
# change prefix-key
unbind C-b
set -g prefix C-f

# solve gibberish problem in copy-paste mode
set -g set-clipboard off

# up
bind-key k select-pane -U
# down
bind-key j select-pane -D
# left
bind-key h select-pane -L
# right
bind-key l select-pane -R
```

**Comment by nicm** [comment]
Does this still happen with tmux 2.5 or master?

**Comment by dslztx** [comment]
Yes.I just test it in tmux 2.5,the same problem exists.

**Comment by nicm** [comment]
Show me some logs please, preferably from master.

**Comment by dslztx** [comment]
I can not reproduce any more.But I guess it is about ssh , locale , unidentifiable char.
Just forget it.
Sorry for wasting your time.
