### ISSUE TITLE
equivalent on OSX of MouseDragEnd1Pane send-keys -X copy-selection ?

### ISSUE THREAD

**Issue by timotheecour** [tmux/tmux#1063]
```
Darwin i386
tmux 2.5
screen
```

on linux this works:
`bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection`
(selects text that can be copied, without requiring `q`, and without loosing scrolling position in copy mode)

what's the equivalent on OSX?
this is my best currently:
`bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "reattach-to-user-namespace pbcopy"`
but it requires pressing `q` after entering text

**Comment by nicm** [comment]
Are you sure you are using the same tmux versions on both platforms?
