### ISSUE TITLE
message-command-style vs message-style

### ISSUE THREAD

**Issue by AquaL1te** [tmux/tmux#1065]
It seems like that message-style is leading in contrast to message-command-style. At least as far as I understand the message-command-style is for the bar below to insert tmux commands and the message-style is for status updates? It's not entirely clear from the man page. If this is the case, then when I set the message-style, it sets both the command and status bar. I want to have the status bar be in bold and the command bar not. I'm probably doing something wrong...

```
set-option -g message-command-style fg=white,bg=colour31            
set-option -g message-style fg=white,bright,bg=colour31 
```

**Comment by nicm** [comment]
command style is when you are in command mode with vi keys

**Comment by AquaL1te** [comment]
Can you please help me understand which one I should use for the 'notification-style'? Because I don't find the man page very descriptive. Below are the descriptions from the man page, I understand them as being for indeed the vi command line and the other one for the notification messages from other windows (which is not what it does).

_message-command-style: Set status line message command style, where style is a comma-separated list of characteristics to be specified.

message-style: Set status line message style._

status-style, mode-style and window-style are also not what I'm looking for.

**Comment by nicm** [comment]
Message-style is the style for the command prompt and the status line
messages

**Comment by AquaL1te** [comment]
Is there any way to make a distinction in style between the command-style and message-style? :) If not then thanks for the information, the ticket can then be closed.

**Comment by nicm** [comment]
No it is one option for both.
