### ISSUE TITLE
Which version of libevent to use

### ISSUE THREAD

**Issue by blub4747** [tmux/tmux#1067]
Hi guys,

I am trying to build tmux on my armboards under armbian eg the  ubuntu flavours os armbian.
from the gz archive 
However when I first tried to compile tmux the process failed since libevent was missing.
I therefore did run a apt search for libevent which gave me a very long list of results.
On the other hand when I simply tried to install libevent with apt-get install libevent.
 I did get a reply that no package was avaliable.
> Unable to locate package libevent

I there compiled libevent myself using 
the latest version from the libevent website
> libevent-2.1.8-stable.tar.gz
However when I now try to compile tmux I still get a error
msg as shoen below.

>  tmux -v
tmux: error while loading shared libraries: libevent-2.1.so.6: cannot open shared object file: No such file or directory

Can you please tell what I should do to resolve this problem?
 Thx, blub4747

Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

**Comment by nicm** [comment]
Easiest would be to build a static tmux by running configure --enable-static (make clean first).

Or you will need to install libevent in one of the ld.so search paths, or add wherever you installed it to the search paths, or set LD_LIBRARY_PATH.
