### ISSUE TITLE
crash on macOS in libevent on start

### ISSUE THREAD

**Issue by Darkshadow2** [tmux/tmux#1068]
macOS 10.12.6 (and 10.11.6)
tmux from git master

tmux crashes on launch with libevent-2.1.8 in `event_del`
Interestingly, a much older libevent (2.0.22) worked fine - possibly a bug fixed in libevent since is triggering this.

I managed to fix it by editing `alerts.c` in function `alerts_queue` and moving `alerts_reset(w);` to below the check if events are initialized.  Like so:

```
void
alerts_queue(struct window *w, int flags)
{
    if (!event_initialized(&w->alerts_timer))
        evtimer_set(&w->alerts_timer, alerts_timer, w);

    alerts_reset(w);
```

Crash log:
[tmux.txt](https://github.com/tmux/tmux/files/1293367/tmux.txt)

**Comment by nicm** [comment]
Try this instead please:
~~~~
Index: alerts.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/alerts.c,v
retrieving revision 1.26
diff -u -p -r1.26 alerts.c
--- alerts.c    23 Aug 2017 09:16:39 -0000      1.26
+++ alerts.c    11 Sep 2017 17:59:41 -0000
@@ -142,7 +142,8 @@ alerts_reset(struct window *w)
        struct timeval  tv;

        w->flags &= ~WINDOW_SILENCE;
-       event_del(&w->alerts_timer);
+       if (event_initialized(&w->alerts_timer))
+               event_del(&w->alerts_timer);

        timerclear(&tv);
        tv.tv_sec = options_get_number(w->options, "monitor-silence");

**Comment by Darkshadow2** [comment]
Yep, that works just as well

**Comment by nicm** [comment]
Applied to OpenBSD now; will be in GitHub later. Thanks!
