### ISSUE TITLE
mouse click can not select correct panel in dual screen setup

### ISSUE THREAD

**Issue by dlintw** [tmux/tmux#1069]
- tmux version:master, tmux-git-2.5.r308.g9a1b9f15-1
- Manjaro Linux 64 (tmux installed here)
- client (windows 7 64 bit) run [pietty](https://sites.google.com/view/pietty-project/download)(putty) to connect to server
- your terminal(pietty - a putty variance), and $TERM inside(screen-256color) and outside of tmux(xterm-256color)
- reproduce steps

1. runing pietty(putty) dual screen on Windows 7, 
2. Use tmux to split six panel like
   123
   456
3. drag pietty's corner to cross two screen, so the panel 1,4 are put on left screen, the other panels 2,5,3,6 are put on right screen
4. ctrl-b + M to enable mouse.
5. When I try to click the panel 3, it switch to panel 1, click the panel 6, it switch to panel 4.

- logs from tmux 

$ uname -sp # Linux unknown

To run tmux without a config and get logs, run:

    tmux -Ltest kill-server
    tmux -vv -Ltest -f/dev/null new

Then reproduce the problem, exit tmux, and attach the tmux-server-*.log file
from the current directory to the issue.
![tmux](https://user-images.githubusercontent.com/326179/30316628-71e6520e-97da-11e7-9b34-42461180fc1d.png)
[tmux.log.zip](https://github.com/tmux/tmux/files/1295308/tmux.log.zip)

**Comment by nicm** [comment]
Your terminal is 317 columns wide but standard mouse mode only supports up to 223 columns (or sometimes 256). You need to use a terminal which supports SGR mouse mode to use the mouse beyond column 223.

**Comment by dlintw** [comment]
@nicm, you are right, so, this is not tmux's bug, this is terminal's bug.  I use the mintty in msys2 to replace putty/pietty, it works.
