### ISSUE TITLE
Can i have one key to copy selection to both tmux and system clipboard?

### ISSUE THREAD

**Issue by tkossak** [tmux/tmux#1079]
Is there a way to make one key copy selected text (in vi mode) to both system clipboard and tmux clipboard?
I have in my tmux.conf:

```
set-option -s set-clipboard off
bind -n M-c copy-mode
bind -n M-v paste-buffer

bind-key -T copy-mode-vi 'v' send -X begin-selection
# bind-key -T copy-mode-vi y send -X copy-selection
bind-key -T copy-mode-vi y send -X copy-pipe 'xclip -sel clip'
```
And when i press `y` the text is copied to system clipboard, but the selection stays on, and i have to press enter to copy it to tmux clipboard. I'd like the selection to disappear when I press `y` and be available in both clipboards (system and tmux).

Thank you.

I use
Linux Manjaro
xfce4-terminal
tmux 2.5
$TERM inside tmux = screen-256color
$TERM outside of tmux = xterm-256color

**Comment by nicm** [comment]
Try something like:

send -X copy-selection; run "tmux save -|xclip ..."

**Comment by nicm** [comment]
saveb not save.

**Comment by tkossak** [comment]
The binding `bind-key -T copy-mode-vi y send -X copy-selection; run "tmux save -|xclip -sel clip"` actually makes tmux not start at all (it freezes until i press CTRL+\ and then it dumps core).

**Comment by nicm** [comment]
You are missing a \ before ;

**Comment by nicm** [comment]
You will probably also need >/dev/null 2>&1 because of xclip bug

**Comment by tkossak** [comment]
I changed it to:
`bind-key -T copy-mode-vi y send -X copy-selection\; run "tmux save -|xclip -sel clip >/dev/null 2>&1"`

But it doesn't exit vi selection mode (the selection disappears, but i still have to press enter to be able to write commands in terminal). Can I do all of it (copy selection to both clipboards + exit vi selection mode) in one go?

**Comment by nicm** [comment]
Use copy-selection-and-cancel...

**Comment by tkossak** [comment]
This works! Thank you very much for your time.

If anyone wants the same behaviour the proper mapping is:
`bind-key -T copy-mode-vi y send -X copy-selection-and-cancel\; run "tmux save -|xclip -sel clip >/dev/null 2>&1"`

**Comment by noraj1337** [comment]
For `xsel` instead of `xclip`:

```
 bind-key -T copy-mode-vi y send -X copy-selection-and-cancel\; run "tmux save -|xsel -b >/dev/null 2>&1"
```
