### ISSUE TITLE
improve choose-tree navigation

### ISSUE THREAD

**Issue by non** [tmux/tmux#1080]
In tmux 2.6-rc3, `choose-window` is now implemented via `choose-tree`.

Previously, I was able to navigate the `choose-window` list using C-p and C-n (Emacs' up and down bindings). I noticed that after an upgrade to 2.6-rc3 this no longer works. It seems like the `choose-tree` bindings are different than those from `choose-window`. I confirmed in Vanilla tmux 2.5 that this works as I had expected.

I can imagine several possible fixes:

 1. Add these bindings to `choose-tree`.
 2. Add an option to add these bindings to `choose-tree`.
 3. Make one of the existing editor options (e.g. `mode-keys`) also add these bindings to choose tree when in Emacs mode.

(Not sure you'll need this info but: I'm running Linux, TERM is screen-256color (within tmux) and xterm-256color (outside of tmux).)

**Comment by nicm** [comment]
I would be OK with having these as builtin keys.

**Comment by ght** [comment]
Maybe use the same bindings in choose-tree as in copy-mode (`cursor-up`, `cursor-down`, `history-top`, `history-bottom`, vi type repeat prefixes, etc.) to keep them consistent and configurable (emacs/vi).

I just noticed that while `j`/`k` work, `g`/`G` do not, instead `C-b`/`C-f` go to the first/last line, despite usually being bound to `cursor-left`/`cursor-right`.

Also collapsing/expanding the pane list of sessions with `space` does not seem to work any more either.

The new preview feature is really nice, keep up the great work.

**Comment by nicm** [comment]
Added C-p and C-n now, thanks.

**Comment by tbrand** [comment]
I would like to see full .tmux.conf about the option since I'm new-comer for tmux.
Could you show me how to add emacs like key binds in choose-tree mode?

Thanks!

**Comment by xuxiangyang** [comment]
Hi，I saw this feature was add in this https://github.com/tmux/tmux/commit/99351c9cae3c01c68c57aebf127551ec6afe7db2 commit, but this commit is done after 2.6. When the 2.7 will be released? Need this feature so much. thx
