### ISSUE TITLE
bell-action any with monitor-bell on does not highlight current window

### ISSUE THREAD

**Issue by oblitum** [tmux/tmux#1081]
The [new monitor-bell option](https://github.com/tmux/tmux/pull/1037) is being [quite useful for me
](http://nosubstance.me/post/mutt-secret-sauce/#tmux-tips) but I've noticed that with

```
set -g monitor-bell on
set -g bell-action any
```

I'm not getting window highlighting for the current window, just for non focused, like if I was using `set -g bell-action other`.

Besides this minor inconsistency, monitor-bell isn't listed in the CHANGES file as a new feature.

**Comment by nicm** [comment]
Status line flags are never displayed for the current window and I am pretty sure they never were...

**Comment by oblitum** [comment]
OK, I supposed there was an inconsistency just because of how I've interpreted man pages:

```
monitor-bell [on | off]
        Monitor for a bell in the window.  Windows with a bell are highlighted
        in the status line.

bell-action [any | none | current | other]
        Set action on a bell in a window when monitor-bell is on.  The values
        are the same as those for activity-action.

activity-action [any | none | current | other]
        Set action on window activity when monitor-activity is on.  any means
        activity in any window linked to a session causes a bell or message
        (depending on visual-activity) in the current window of that session,
        none means all activity is ignored (equivalent to monitor-activity
        being off), current means only activity in windows other than the
        current window are ignored and other means activity in the current
        window is ignored but not those in other windows.
```

So, the current window is not supposed to highlight with **any**... 😢
