### ISSUE TITLE
Feature-Request: display to all clients

### ISSUE THREAD

**Issue by lnxbil** [tmux/tmux#1082]
Hi,

as stated in the title, this is not a bug or an issue but a feature request for something that I think could be useful to others. I checked and it is not present in current master.

Currently, We broadcast via 

```
for i in $( tmux list-clients | cut -d: -f1 ); do tmux display-message -c $i "my message"; done
```

to all attached clients, e.g. that a new client as attached to the session. It would be great to have a `display-message-all` command or use something like `display-message -c all` to do the same.

**Comment by nicm** [comment]
What is the advantage to having this built in to tmux instead of a one line shell script?

**Comment by lnxbil** [comment]
Fair enough, the `display-message -c all` or even `display-message -a` would be a very-nice-to-have feature with a clean interface - and it needs less code. Quoting would also be easier, the oneliner will become more complex or very long :-D

Personally, I think that embedding shell code inside tmux can get very ugly with more complex quoting, so I often extract it, yet have to handle more files in a distributed environment.

**Comment by nicm** [comment]
I would like to have -c * but I don't want to special case it for this, it has been on the TODO list for ages anyway.

**Comment by lnxbil** [comment]
Oh nice, then it's fine to close the issue. I looked at the code and I also do not thing there is an easy way to fix it, yet keep up the good work. I really felt in love with `tmux`.
