### ISSUE TITLE
Complete list of hooks

### ISSUE THREAD

**Issue by 0phoff** [tmux/tmux#1083]
## Details
Manjaro Linux - Budgie
tmux version 2.5

## Question
I wanted to know if there is a complete list of all the hooks that are available in tmux. The manpages show a few and then talk about after-* and before-* hooks. I wondered if there is a list for those!

More specifically, I am looking for an after-pane-switched hook of some kind.  
I want to execute a command each time the user changes to another pane somehow (eg. switching session, window, pane, destroying pane, etc.)

I can almost achieve what I want by adding the script to the PROMPT_COMMAND env, but the hook is really what I'm after :innocent:

Any help is appreciated!

**Comment by nicm** [comment]
Try window-pane-changed hook?

**Comment by 0phoff** [comment]
Thanks for your help!

For other people wanting to run a command whenever the user changes a pane somehow, these 3 hooks did it for me:
  > tmux set-hook window-pane-changed ...
  > tmux set-hook session-windows-changed ...
  > tmux set-hook client-session-changed ...

The only hook I am looking for now, is a hook that runs every time a new command is run from the current terminal. I am using PROMPT_COMMAND for that now, but it causes the a slight delay after every command and I find that disturbing... I am guessing there must be a hook of that kind, since your automatic-rename must work like that?

If you could point me to where in the code I should search to find all the different hooks, I would be willing to create a list of some sorts!

**Comment by nicm** [comment]
tmux doesn't know when a command is run from the shell but you could
theoretically add one for when it does the automatic rename. You can see
hooks by looking for calls to notify_add in the code.

**Comment by 0phoff** [comment]
Ok, thanks for your help!
I'll try to look into it whenever I have some spare time.

I think a list could help other people to be able to use this awesome feature of tmux more, but I see it might be a lot of work to create a complete list.. :sweat_smile:
Unless you also feel we need such a list, you can close this issue.

**Comment by nicm** [comment]
Making the existing list in the man page complete would be nice but I don't
have time to do it now.

**Comment by nicm** [comment]
Changed like so:
~~~~
Index: tmux.1
===================================================================
RCS file: /cvs/src/usr.bin/tmux/tmux.1,v
retrieving revision 1.583
diff -u -p -r1.583 tmux.1
--- tmux.1      25 Oct 2017 14:14:52 -0000      1.583
+++ tmux.1      25 Oct 2017 15:19:55 -0000
@@ -3347,7 +3347,12 @@ layout after every
 set-hook after-split-window "selectl even-vertical"
 .Ed
 .Pp
-In addition, the following hooks are available:
+All the notifications listed in the
+.Sx CONTROL MODE
+section are hooks (without any arguments), except
+.Ic %exit .
+The following additional hooks are available:
+.Pp
 .Bl -tag -width "XXXXXXXXXXXXXXXXXXXXXX"
 .It alert-activity
 Run when a window has activity.
