### ISSUE TITLE
./configure: libevent not found

### ISSUE THREAD

**Issue by dajuno** [tmux/tmux#1084]
I am trying to compile tmux 2.5 on OpenSUSE 3.16.53, via this [bash script](https://gist.github.com/ryin/3106801#gistcomment-2191503), with libevent 2.1.8 and ncurses 5.9.

libevent is configured with:

    ./configure --prefix=$HOME/local --disable-shared

ncurses ./configure:

    ./configure --prefix=$HOME/local

tmux ./configure:

    ./configure CFLAGS="-I$HOME/local/include -I$HOME/local/include/ncurses" \
    LDFLAGS="-L$HOME/local/lib -L$HOME/local/include/ncurses -L$HOME/local/include" \
    CPPFLAGS="-I$HOME/local/include -I$HOME/local/include/ncurses" \
    LDFLAGS="-static -L$HOME/local/include -L$HOME/local/include/ncurses -L$HOME/local/lib" make

The tmux configuration fails due to libevent issues:

> checking for LIBEVENT... no
> checking for library containing event_init... no
> checking event.h usability... yes
> checking event.h presence... no
> configure: WARNING: event.h: accepted by the compiler, rejected by the preprocessor!
> configure: WARNING: event.h: proceeding with the compiler's result
> checking for event.h... yes
> configure: error: "libevent not found"

Thanks in advance!

**Comment by nicm** [comment]
config.log?

**Comment by dajuno** [comment]
https://gist.github.com/dajuno/cf3a41909fb7e6846a7ebda29c4e2798#file-config-log

thanks

**Comment by dajuno** [comment]
Sorry, my bad. There was -L$HOME/local/lib64 missing in LDFLAGS for libevent.

**Comment by the7threvival** [comment]
For anyone who came here like me and still didn't understand:

https://stackoverflow.com/questions/21926202/libevent-not-found-error-in-tmux

**Comment by lawrence321** [comment]
same problem as of 01/14/2020.


tmux-3.0a$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for bison... bison -y
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking bitstring.h usability... no
checking bitstring.h presence... no
checking for bitstring.h... no
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking ndir.h usability... no
checking ndir.h presence... no
checking for ndir.h... no
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking pty.h usability... yes
checking pty.h presence... yes
checking for pty.h... yes
checking for stdint.h... (cached) yes
checking sys/dir.h usability... yes
checking sys/dir.h presence... yes
checking for sys/dir.h... yes
checking sys/ndir.h usability... no
checking sys/ndir.h presence... no
checking for sys/ndir.h... no
checking sys/tree.h usability... no
checking sys/tree.h presence... no
checking for sys/tree.h... no
checking util.h usability... no
checking util.h presence... no
checking for util.h... no
checking for library containing flock... none required
checking for dirfd... yes
checking for flock... yes
checking for prctl... yes
checking for sysconf... yes
checking for asprintf... yes
checking for cfmakeraw... yes
checking for closefrom... no
checking for explicit_bzero... no
checking for fgetln... no
checking for freezero... no
checking for getdtablecount... no
checking for getprogname... no
checking for memmem... yes
checking for recallocarray... no
checking for reallocarray... no
checking for setenv... yes
checking for setproctitle... no
checking for strcasestr... yes
checking for strlcat... no
checking for strlcpy... no
checking for strndup... yes
checking for strsep... yes
checking for strtonum... no
checking for working strnlen... yes
checking for library containing clock_gettime... -lrt
checking for LIBEVENT... no
checking for library containing event_init... no
checking event.h usability... no
checking event.h presence... no
checking for event.h... no
configure: error: "libevent not found"
