### ISSUE TITLE
Clearing full lines by scrolling them away broken

### ISSUE THREAD

**Issue by 22dh22** [tmux/tmux#1085]
## problem / steps
Opening a large file in vim-nox and jumping to bottom (`G`), then top (`gg`), then bottom (`G`), then top (`gg`) causes corrupted output (old and new line content mixed).
This problem does not occur outside of tmux.

## environment
- current tmux master https://github.com/tmux/tmux/commit/ff526e43de84cff3770d32c0b6ea215a7359f521
- up to date Debian stable and sid
- no config
- Konsole, and directly on the virtual console outside X, currently not reproducible on xterm, but I think I saw some corruption there as well some days ago
- `TERM`
  - outside tmux `TERM=xterm` is broken while `TERM=linux` works, probably because of missing features required for the clearing trick
  - inside always `TERM=screen`
  - using `TERM=konsole` or `TERM=konsole-256color` does not fix this

```
$ uname -sp && ./tmux -V && echo $TERM
Linux unknown
tmux master
screen
```

## example
[log and example file](https://github.com/tmux/tmux/files/1325579/log.zip)
I open `/tmp/longfile`, jump `down`+`up`+`down`+`up`, then lines show `ab`.

## links
found Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876362

## bisect results
new way to clear added with first chunk of https://github.com/tmux/tmux/commit/0264ef094a79c828e72e03052b9969cd80b28d16
=> introduced into [Debian git](https://anonscm.debian.org/git/collab-maint/tmux.git) with [`749aa5`](https://anonscm.debian.org/git/collab-maint/tmux.git/commit/?id=749aa52e923657cfd09b395eaf3d48f79de521e0)

**Comment by nicm** [comment]
Probably the same as https://github.com/tmux/tmux/issues/933 and https://github.com/tmux/tmux/issues/931.

**Comment by nicm** [comment]
This is a bug in Konsole. May also be a bug in Linux console but since you are not meant to use TERM=xterm but rather TERM=linux it is up to you if you want to see if they will fix it.

**Comment by 22dh22** [comment]
The `set -as terminal-overrides ',*:indn@'` did not work but I can confirm that this is fixed with the Konsole version in Debian experimental which is newer than the version of https://bugs.kde.org/show_bug.cgi?id=379318

So not a tmux bug, closing.
Thanks for the quick response!

**Comment by hefee** [comment]
@22dh22 but you mention that it is also broken "directly on the virtual console outside X", is this solved too? Or are you mean, that if you open the broken session in a  "virtual console outside X", than you see the same behavior?

I can reproduce the issue with konsole/sid and been fixed with konsole/experimental. For me outside tmux started in konsole i couldn't see the issue... But you issue here reads like you see the issue on more places...

**Comment by 22dh22** [comment]
@hefee as mentioned I could only reproduce it directly on the virtual console with `TERM=xterm` which you are not supposed to do. I am not sure if that is a bug or to be expected since tmux might assume more features than are present. To reproduce use `TERM=xterm tmux`.
As for reproducing it in xterm, I guess I was mistaken. As stated I could not reproduce it there when I tried.
