### ISSUE TITLE
tmux client suddenly stops recognizing prefix key.

### ISSUE THREAD

**Issue by dpc** [tmux/tmux#1086]
Hi,

I'm a long-term `tmux` user, and my config works fine most of the time, but sometimes, in the middle of a heated hacking and keystrokes flying around, `tmux` stops recognizing `C-Space` shortcut (my prefix).

I have no idea why. I know it's not misconfigured, because it works for hours, until it suddenly stops. Usually, I just quit whatever I'm doing, reach shell and do `tmux detach`, then I attach again, and everything is working again. So it is client side thing, it seems.... And it happens on all: Ubuntu 14.04, Archlinux (up-to-date), Fedora 26 . So it's a variety of versions behaving the same way.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by dpc** [comment]
Ubuntu 14.04 box:

```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 1.8
xterm-256color
```

Fedora 26 box:

```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.5
xterm-256color
```

I'll post more information if I manage to get it.

**Comment by nicm** [comment]
Config? Logs?

**Comment by dpc** [comment]
My `tmux.conf`:

```
run-shell "tmux setenv -g TMUX_VERSION $(tmux -V | cut -c 6-)"

unbind C-b
set-option -g prefix "C- "
bind-key "C- " send-prefix
set-option -g default-terminal screen-256color
set-option -g base-index 1
set-option -s escape-time 0
set-option -g aggressive-resize on
set-option -g monitor-activity on
set-option -g visual-activity off
set-option -sg escape-time 10

# Don't start login shell each time
set-option -g default-command "${SHELL}"

set-option -g mode-keys vi
set-option -g history-limit 100000

set-option -g mode-keys vi
set-option -g history-limit 10000

set-option -gq utf8 on

# y and p as in vim
bind Escape copy-mode
unbind p
bind p paste-buffer
if-shell -b '[ "$(echo "$TMUX_VERSION >= 2.4" | bc)" = 1 ]' \
' \
bind-key -T copy-mode-vi v send-keys -X begin-selection ; \
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "xclip -in -selection clipboard" ; \
bind-key -T copy-mode-vi Space send-keys -X halfpage-down ; \
bind-key -T copy-mode-vi Bspace send-keys -X halfpage-up ; \
' \
' \
bind -t vi-copy 'v' begin-selection ; \
bind -t vi-copy 'y' copy-selection ; \
bind -t vi-copy 'Space' halfpage-down ; \
bind -t vi-copy 'Bspace' halfpage-up ; \
'

# extra commands for interacting with the ICCCM clipboard
bind C-c run "tmux save-buffer - | xclip -i -sel clipboard"
bind C-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"

set-option -g automatic-rename on
set-option -g set-titles on
set-option -g set-titles-string '#(hostname -s):#I.#P #W #S' # window number,program name,active (or not)

set-option -g status-left-length 20
set-option -g status-left '#[fg=black][ #[fg=colour1]#(hostname -s) #[fg=black]] [#[default]'
set-option -g status-right '#[fg=black]][ #[fg=white]%m/%d %H:%M #[fg=black]]#[default]'

#set-option -g lock-after-time 900
#set-option -g lock-server on
set-option -g lock-command vlock

# prefix r reloads the configuration, handy
bind r source-file ~/.tmux.conf

bind s split-window -v
bind v split-window -h

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key C run-shell "tmux show-buffer | xsel -i -b"

#### COLOR

# default statusbar colors
# colour235 - base02
# colour240 - base01
set-option -g status-bg colour8 #base02
set-option -g status-fg white
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg white
set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg white
set-window-option -g window-status-current-bg default
set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg white
set-option -g pane-active-border-fg black

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
set-window-option -g clock-mode-colour white
```

I'll see about running git version, and capturing the logs, but as I said, it happens maybe once a day, and only if I do a lot of typing.

**Comment by dpc** [comment]
It might be just a PIBKAC: I might be just triggering some weird state by accident with xclip or something, by typing fast etc. However, I am just unable to to get prefix (Ctrl+ Space) to work again, while typing normally fast.

It's a week datapoint, but I belive the problem is happening only when I'm working inside Neovim. But like 90% of what I'm doing in tmux is having Neovim open, so there's that.

Another thing to mention is that it wasn't happening before (like a half a year ago). It was introduced couple of months ago, but I'm unable to tell if it was something that I've changed locally. Maybe Neovim is doing something different. Eg. it introduced that lovely "insert mode cursor".

I'm mostly hopping that someone experiencing similiar issue can find this one.

**Comment by nicm** [comment]
Oh yeah, you are probably hitting the xclip bug with your C-c binding,
you need to redirect xclip stdout and stderr to /dev/null because
otherwise tmux can never tell when it has finished. Or alternatively
use run-shell -b.

**Comment by nicm** [comment]
Or just change to xsel throughout rather than using xclip at all.

**Comment by dpc** [comment]
@nicm That would explain it. Thank you so much!
