### ISSUE TITLE
New pane creation is slow

### ISSUE THREAD

**Issue by psp26** [tmux/tmux#1087]
tmux version: 2.5
platform: Linux (Debian 4.9.30-2+deb9u3)
term: xterm-256color

Creating a new tmux pane seems to have gotten noticeably slower after upgrading to v2.5 (I forget my previous version, 1.8 maybe?).

I know my shell (zsh) isn't slow. Creating a new terminal with the same shell without tmux is fast. "exec zsh" is also fast. I completely cleared out my .zshrc for good measure and the problem remains.

It's only when I create a new tmux window or split an existing window that it feels like it takes about 500ms for the new pane to start the shell.

This is with an empty .tmux.conf, fresh install (OS installed today), no plugins.

Is there an easy way to profile pane creation time to see why it's slow? Any other debugging tips? Much appreciated, Thanks!

**Comment by nicm** [comment]
tmux creates login shells, so comparing it with exec zsh is not the same.

**Comment by psp26** [comment]
Thanks nicm! I didn't know about this difference. Switching tmux to start non-login shells with

set -g default-command "${SHELL}"

has solved the issue for me. "exec zsh -l" is much slower than "exec zsh".

Looks like my terminal (alacritty) doesn't start login shells by default which is why it too is fast.

Now to investigate why starting login shells is slow...

**Comment by uri** [comment]
This might be a bad idea but would it be possible to "warm up" a shell? So that next time a new pane or window is created it would just display that shell and then begin to "warm up" another shell in the background?

**Comment by ThomasAdam** [comment]
It's definitely a silly idea.

**Comment by micimize** [comment]
@ThomasAdam why is that silly? Do you just mean it's not something tmux should do? Having a small pool of already-initialized shell processes ready to go is seems like a fine idea.

**Comment by krader1961** [comment]
@micimize It would cause more problems than it solves. For example, if I start tmux, then modify my *~/.profile*, then create a new pane I expect it to run the modified profile. I do not expect to get a shell using the prior profile because tmux cached a shell session just in case I create a new pane.

**Comment by micimize** [comment]
@krader1961 right, but if it was a separate tool that wrapped your shell, and not a part of `tmux`, then it wouldn't necessarily be silly right? You could imagine a standalone utility with an api like
```
shell-pool --queue 3 "exec zsh"
shell-pool cache clear
```
and then `tmux set -g default-command "shell-pool ..."`
