### ISSUE TITLE
Mapping mintty escape sequences in tmux

### ISSUE THREAD

**Issue by costincaraivan** [tmux/tmux#1088]
Hello - this is not so much a code issue but more of a support/documentation issue.

Details:
CYGWIN_NT-10.0 unknown
tmux 2.6-rc3
screen (mintty)

I'm trying to map Ctrl-Shift-<...> keys to tmux commands using mintty proprietary escape sequences. I think (hope?) that this is possible using user-keys. However I don't know how to map their [escape sequences](https://github.com/mintty/mintty/wiki/Keycodes#ctrl) to things tmux understands.

I'd want to use: Ctrl-Shift-t for opening a new window, Ctrl-Shift-x for closing a pane, Ctrl-Shift-w for closing a window, Ctrl-Shift-- for a horizontal split, Ctrl-Shift-\ for a vertical split.

The code mintty emits show up in tmux as:

Ctrl-Shift-t: ^Ô
Ctrl-Shift-x:  ^Ø
Ctrl-Shift-w: ^×
Ctrl-Shift--: ^Ü
Ctrl-Shift-\: ^Ü (this is a bit weird, it seems to be the same sequence as the one above...)

How can I map these? Is it even possible?

**Comment by nicm** [comment]
What do they show outside tmux? Run cat and then press the keys.

**Comment by nicm** [comment]
These are Unicode so you should be able to bind them directly but you will need to put them as raw characters in the config file, for example do something like:
~~~~
printf "bind \xc2\x80 lsk" >>.tmux.conf

**Comment by costincaraivan** [comment]
I launched an empty mintty, ran cat and then input several combinations but saw nothing. However, sort of by accident I also input one combo directly at the prompt and got this:
Ctrl-Shift-x ->
    $  # The console actually didn't print a visible character, unlike in Github, I saw nothing in the console.
    bash: $'\230': command not found

**Comment by krader1961** [comment]
If you install fish you can use its `fish_key_reader` command which makes it easy to see what a given combination of keys transmits. The alternative is to run a command like `xxd` or `od -tx1z` then press the keys of interest, [enter], then [ctrl-D] to exit the program. For example, this is what I see when I press [shift]+[right-arrow]:

```
$ od -tx1z                                                                      0 ms
^[[1;2C
0000000 1b 5b 31 3b 32 43 0a                             >.[1;2C.<
0000007
```

The final 0x0a is from pressing [enter] so that [ctrl-D] will exit `od` and isn't part of the sequence sent by the key(s).
