### ISSUE TITLE
ASCII disappeared after move window

### ISSUE THREAD

**Issue by norio13** [tmux/tmux#1090]
## Probrem

Hello,

Insert ASCII before multibyte character.
Move window.
ASCII disappears from the screen.

## Reproduction procedure

Run tmux on xfce4-terminal.
```
tmux -Ltest kill-server
tmux -vv -Ltest -f/dev/null new
```

(1) Input ```あ(U+3042)```.
![1](https://user-images.githubusercontent.com/18260849/30852037-6e96a19c-a2e5-11e7-812b-87a5b99849c9.png)

(2) Input ```aaaaa``` before ```あ```.
![2](https://user-images.githubusercontent.com/18260849/30852027-67061016-a2e5-11e7-9d67-bae717d2c9ca.png)

(3) Press ```CTRL-b c``` ```CTRL-b p```.
(4) ```aaaaa``` disappeared.(however, press CTRL-L to draw.)
![3](https://user-images.githubusercontent.com/18260849/30852047-76612370-a2e5-11e7-9b24-65edc3d42fbd.png)

## Environment

- OS: Linux Debian stretch 9.1 64bit
- tmux version: 2.5-2~bpo9+1, master(ff526e4)
- terminal: xfce4-terminal 0.8.3-1, gnome-terminal 3.22.2-1
- TERM(inside and outside): screen-256color

[tmux-server-23011.log](https://github.com/tmux/tmux/files/1332651/tmux-server-23011.log)

best regards,

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by nicm** [comment]
Oh sorry yeah you said. Does it happen with xterm?

**Comment by norio13** [comment]
Yes, it also happens in xterm.
xterm 327-2, tmux (master)

I'm sorry. I have submitted the tmux 2.5 log.
update log: [tmux-server-25541.log](https://github.com/tmux/tmux/files/1332987/tmux-server-25541.log)

**Comment by nicm** [comment]
Weird... I can reproduce, looking into it.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1336835/x.diff.txt)

We weren't overwriting padding when writing collected sequences of characters, this changes to do so.

There are probably other issues with padding in there (for example with insert character), so perhaps we don't do this in the best way. But it works OK for now I guess.

**Comment by norio13** [comment]
It works.
Thank you so much!

**Comment by nicm** [comment]
Great. This is clearly a bug, but it doesn't seem particularly critical and I'm not sure I want to put it in without time for good testing; so I think it will be better to wait until after 2.6.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by norio13** [comment]
Thank you very much!
