### ISSUE TITLE
Can't rename window to name beginning with - and followed by any other char

### ISSUE THREAD

**Issue by RatanRSur** [tmux/tmux#1091]
```
uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.5
tmux-256color
```
renaming to `-` works but not, for example, `-a`, `-ab`, `-5`.

**Comment by nicm** [comment]
Works for me.

**Comment by RatanRSur** [comment]
Does it make a difference if you do it with prefix + , as opposed to typing the command out?

**Comment by nicm** [comment]
Oh yeah, you need to change the binding to do rename-window -- '%%'.

**Comment by RatanRSur** [comment]
Would changing to this mapping render any other strings currently accepted as names unacceptable? If not, couldn't this be the new default mapping?

**Comment by nicm** [comment]
Yeah I will change it after next release.

**Comment by RatanRSur** [comment]
This seems like it would be an easy fix, would you mind if I try putting the pull request together for fun? :)

**Comment by nicm** [comment]
It's just a two line change so it probably isn't worth it, I'll do it after release.

**Comment by nicm** [comment]
Changed in OpenBSD now, will be in GitHub later. Thanks!
