### ISSUE TITLE
tmux fails on openSUSE when tempfs folder doesn't exist

### ISSUE THREAD

**Issue by bitcrazed** [tmux/tmux#1092]
Running tmux 2.5 on a freshly opened openSUSE 42.3 instance (installed via zypper, default config) on Windows 10 [WSL](https://aka.ms/learnwsl).

```
> uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.5
xterm-256color
```

tmux crashes when run from a freshly opened openSUSE instance:

```bash
> tmux
can't create socket: No such file or directory
```

Took a look at the strace and noticed that tmux is trying to open a file in /run/tmux, but failing.

Immediately after installing tmux:
```bash
> ls /run
lock  shm  tmux  user  zypp.pid
```
After closing openSUSE session and re-opening:
```bash
> ls /run
lock  shm  user
```

If we manually create ```/run/tmux``` tmux opens fine.

Since we clear tempfs when we shutdown an instance, this affects all our users running openSUSE.

> Note: Tried to capture a log as per CONTRIBUTING instructions, but cannot:

```bash
> tmux -Ltest kill-server
can't create socket: No such file or directory
> tmux -vv -Ltest -f/dev/null new
can't create socket: No such file or directory
```

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by bitcrazed** [comment]
Hey @nicm - updated description above with a little info.

**Comment by nicm** [comment]
It sounds like you have modified tmux so that it puts sockets in /run/tmux instead of _PATH_TMP (usually /tmp). If you do this, you need to make sure the directory exists. tmux will not (and should not) attempt to create it.

**Comment by nicm** [comment]
For the period where Debian tried to move tmux sockets to /var/run/tmux, they had a boot script to create the directory with the right permissions, doesn't SuSE have similar?

**Comment by bitcrazed** [comment]
Hey @nicm: Sorry - was swamped at SUSECON the last few days.

So, we dug into this and it turns out that it's likely our fault (I work on the WSL team at Microsoft):

Many [systemd distros are adopting the new /run folder ](http://www.h-online.com/open/news/item/Linux-distributions-to-include-run-directory-1219006.html) replacing `/var/run` as a place to store transient info at startup, because `/var/run` is mounted later in the startup process. 

SUSE also has a policy that sockets etc. get created under /run, which is on tmpfs, which WSL:
a) Nukes when we shut-down a distro instance
b) Does not initialize when the distro starts-up

This combination of factors means that:
1. Tools & apps like tmux have no socket at startup
1. We need to figure out a way to allow distro owners to execute some init steps (e.g. call system-tmpfiles) when a distro instance is started:
![image](https://user-images.githubusercontent.com/961950/31001436-f0f6b136-a4e3-11e7-8ff1-a007aa4d277e.png)

Closing this issue - we'll go figure out a fix at our end! :)

**Comment by nicm** [comment]
tmux doesn't need a socket at startup, it will create one (and the user
parent directory). But it does need the top level directory (usually /tmp,
in your case /run/tmux) to exist. Don't forget it will also need the right
permissions (777 + sticky bit).

**Comment by bitcrazed** [comment]
Yep - sorry - should have been clearer.

If we run `system-tmpfiles --create`, the tmux folder will be created correctly.

Have just filed an issue for us to track the fix for this: Microsoft/bashonwindows#2530

**Comment by ichimei0125** [comment]
It is a problem of permission

you should check the system-tmpfiles by use `man tmpfiles.d` 

Here is a Solution

There is a file, /usr/lib/tmpfiles.d/tmux.conf
which content is `d /run/tmux 1777 root root -`

edit the file, use like `sudo vim`
to `d /run/tmux 1755 [your name] [your group] -`

Ta-da! And you can use `tmux` without `system-tmpfiles --create`

**Comment by ray13eezy** [comment]
Just wanted to provide one additional tidbit of info for anybody else who comes across this thread - in the comment above from the WSL team, the command you need to run is `systemd-tmpfiles --create` (note that it is systemd and not system).

Hope this helps.
