### ISSUE TITLE
tmux+fish works not well 

### ISSUE THREAD

**Issue by 3xp10it** [tmux/tmux#1093]
I am using tmux and fish and iterm2 in macOS,my .tumx file is <a href="https://github.com/3xp10it/.tmux/blob/master/macosTmux/.tmux.conf">here</a>,and my fish shell config file config.fish is <a href="https://github.com/3xp10it/config.fish/blob/master/config.fish">here</a>,it come out below error info:
```
fish: Unknown command 'initializing...'
fish:
exec initializing... 2> /dev/null & reattach-to-user-namespace /usr/local/bin/fish -l
     ^
sessions should be nested with care, unset $TMUX to force
```

env:
tmux
iterm2
fish2.6.0
macOS sierra

**Comment by nicm** [comment]
Seems like this is a problem in your shell profile files.

**Comment by 3xp10it** [comment]
I have find the answer.
