### ISSUE TITLE
configure.ac check for b64_ntop unconditionally includes libresolv

### ISSUE THREAD

**Issue by Ralf-Friedl** [tmux/tmux#1095]
tmux version is 2.5.
I am cross-compiling, host is Linux x64, target is an embedded system with Linux on MIPS CPU, without external libresolv library, and without b64_ntop function.

configure.ac line 271 starts the check for b64_ntop. If it is found without extra libraries, is is node. This is not the case for this target, the link fails.
As the link failed, configure.ac the proceeds the same check with -lresolv appended to LIBS. This link also fails, because libresolv doesn't exist on the target.
So found_b64_ntop is set to no, which is correct. But -lresolv is still included in LIBS, and therefor the final link of the tmux program searches for libresolv, which doesn't exist, and therefor fails.

This can be fixed with the following patch, which saves LIBS and restores it if b64_ntop was not found in libresolv.

```diff
--- configure.ac
+++ configure.ac
@@ -284,6 +284,7 @@
        AC_MSG_RESULT(no)
 
        AC_MSG_CHECKING(for b64_ntop with -lresolv)
+       save_LIBS=$LIBS
        LIBS="$LIBS -lresolv"
        AC_TRY_LINK(
                [
@@ -296,6 +297,7 @@
                found_b64_ntop=no
        )
        if test "x$found_b64_ntop" = xno; then
+               LIBS=$save_LIBS
                AC_MSG_RESULT(no)
        fi
 fi
```

**Comment by nicm** [comment]
Fixed, thanks!
