### ISSUE TITLE
How do disable history suggestions when performing a simple text search

### ISSUE THREAD

**Issue by accesio** [tmux/tmux#1098]
Hi,

Using tmux 2.1 I could enter copy-mode and type control-R to search for a string. Now everytime i start trying to do a search Tmux has already suggested a previous search to me and I find that this gets in the way.

How can you disable this feature ?

**Comment by nicm** [comment]
Change the key binding to leave out -I.

**Comment by accesio** [comment]
wow, super fast response and it works !
