### ISSUE TITLE
Allow interpolating format variables before shell invocation

### ISSUE THREAD

**Issue by ezyang** [tmux/tmux#11]
http://unix.stackexchange.com/questions/193943/passing-tmux-variable-into-shell-command-in-tmux-conf has a pretty decent discussion of the request. Allowing this would mean you could completely reimplement any format string via shell and would offer a lot more flexibility. Additionally, the behavior of shell commands format strings would be more like if-shell, which does interpolate format commands before running the shell.

**Comment by nicm** [comment]
Try git please.

**Comment by ezyang** [comment]
Yup, it's fixed. Looks like this commit:

{{{
commit 66edb3392b234ccd9a940039936edb34258c2102
Author: Nicholas Marriott <nicm@openbsd.org>
Date:   Sun Mar 24 09:33:35 2013 +0000

    Expand format variables in the run-shell and if-shell shell commands,
    from Thiago Padilha.
}}}
