### ISSUE TITLE
Shell output history lost for inactive window

### ISSUE THREAD

**Issue by SnowDiamond** [tmux/tmux#1101]
Problem: I can't see shell output history that was logged into inactive window, it seems like history isn't save. But if window active I see all history and can scroll up to view it from the beginning. 

Steps to reproduce:
1. Open new tmux session
2. Create additional window
3. Run any script that will display execution log in terminal. In my case, I run HTTP server
4. Switch to additional window and wait some time, so first window will be filled with some log text
5. Return back to first window
6. As a result, I see history that fit current terminal height, and I can't scroll up. 

If window is active during server logging, then scroll up works as expected, and I see previous output history.

I use OSX, and output for `uname -sp && tmux -V && echo $TERM` following:
```
Darwin i386
tmux 2.6
xterm-256color
```

**Comment by nicm** [comment]
Scroll up in tmux copy mode, right?

**Comment by SnowDiamond** [comment]
@nicm I'm sorry, but don't know anything about tmux copy mode. How it looks like?

**Comment by SnowDiamond** [comment]
with "scroll up" I mean Page Up/Down (or mouse scroll up/down) in terminal to see previous scrollback history

**Comment by nicm** [comment]
tmux has no control over terminal scrollback, you need to use copy mode in tmux to view history of each pane.

**Comment by SnowDiamond** [comment]
In attached image you can see that I'm in tmux copy mode, which indicates 0/146. So terminal output contain 146 lines above, but I can scroll up to see these lines, if window was inactive during output proccess. If window was active, than I can see all output from begining.

<img width="1280" alt="2017-10-08 00 23 51" src="https://user-images.githubusercontent.com/9202886/31311921-72a07302-abbf-11e7-85e2-55be52ed20b7.png">

**Comment by nicm** [comment]
Works OK for me.

**Comment by nicm** [comment]
When you say you can't scroll up to see the lines, do you mean you press the Up key and nothing happens?

What is in .tmux.conf?

**Comment by SnowDiamond** [comment]
By saying can't scroll up I mean - there are no any lines above in shell output.

For example,
1. I create 2 tmux windows - A and B.
2. In window 'A' I run some process that writes new output lines in shell (server log for example).
3. Switch to window 'B', so window 'A' becomes inactive.
4. Let's say, during window 'A' was inactive shell output wrote 1000 new lines of log information.
5. Switch back to window 'A'.
6. Result: I can't access (or view, or scroll up to see) any lines of log information that aren't fit terminal height.

My tmux.conf file:

```
###########################
#  Configuration
###########################

# use 256 term for pretty colors
set -g default-terminal "xterm-256color"
# set-window-option -g xterm-keys on

set-option -g default-command "reattach-to-user-namespace -l zsh"

# increase scroll-back history
set -g history-limit 10000

# Enable mouse control (clickable windows, panes, resizable panes)
set-option -g mouse off
# setw -g mode-mouse on
# set -g mouse-select-window on
# set -g mouse-select-pane on
# set -g mouse-resize-pane on

# decrease command delay (increases vim responsiveness)
set -sg escape-time 1

# increase repeat time for repeatable commands
set -g repeat-time 1000

# start window index at 1
set -g base-index 1

# start pane index at 1
setw -g pane-base-index 1

# highlight window when it has new activity
setw -g monitor-activity on
set -g visual-activity off # Message on activity

# re-number windows when one is closed
set -g renumber-windows on

# Reload tmux config
bind

# use of ` instead of Ctrl+b
set-option -g prefix `
bind-key ` send-prefix
unbind-key C-b

bind-key v split-window -h
bind-key s split-window -v

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Standard pane selection
bind Left select-pane -L
bind Down select-pane -D
bind Up select-pane -U
bind Right select-pane -R

# Shift arrow to switch windows
bind -n C-h  previous-window
bind -n C-l next-window
bind -n C-Left  previous-window
bind -n C-Right next-window

unbind -n M-h
unbind -n M-l
unbind -n M-Left
unbind -n M-Right

# PGup PGdn to switch windows
bind -n PPage previous-window
bind -n NPage next-window

# No delay for escape key press
set -sg escape-time 0

# Resize panes
bind -r S-Up resize-pane -U 5
bind -r S-Down resize-pane -D 5
bind -r S-Left resize-pane -L 5
bind -r S-Right resize-pane -R 5


###########################
# Status Bar
###########################

set-option -g status on
set-option -g status-interval 2
# set-option -g status-utf8 on

# set refresh interval for status bar
set -g status-interval 30

# center the status bar
set -g status-justify left

# show session, window, pane in left status bar
set -g status-left-length 40
set -g status-right-length 150
set -g status-left '#[fg=green]#S#[fg=blue]  #P pane(s) #[default] '

# show hostname, date, time, and battery in right status bar
set-option -g status-right '#[fg=green]#H#[default] %d %b %H:%M'

# window-title format (#I #F)
set-option -gw window-status-format " #I.#W "
set-option -gw window-status-current-format " #I.#W "
set-option -g allow-rename off


###########################
# Colors
###########################

# color status bar
set -g status-bg black
set -g status-fg white

# active window title colors (default: white, default, bright (= bold))
set-window-option -g window-status-current-fg white
set-window-option -g window-status-current-bg red
set-window-option -g window-status-current-attr dim

# window title colors (default: white, default, dim (= non-bold))
#set-window-option -g window-status-fg white
#set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim

# activity window
setw -g window-status-activity-bg red
setw -g window-status-activity-fg black

# Clipboard support for Mac
set -g default-shell $SHELL
set -g default-command "reattach-to-user-namespace -l ${SHELL}"
```

**Comment by nicm** [comment]
But there are lines, because it said 0/146?

**Comment by nicm** [comment]
You are not being clear. Are you saying that when you enter copy mode in an "inactive" window it says 0/0, so there is no history? Or that when you enter copy mode in an inactive window it says, eg 0/999, but that pressing Up or Page Up to see that history doesn't work?

**Comment by SnowDiamond** [comment]
1000 lines just for example, it's doesn't matter how many lines. 146 as in first example works in same way

**Comment by nicm** [comment]
I can't help you with this since you will not explain what you are doing.

**Comment by nicm** [comment]
I think you are trying to use the terminal scrollback to view history even of inactive panes. You can't do this, you need to use copy mode. But that's just a guess.

**Comment by tx1985** [comment]
I have the same problem as @SnowDiamond  : 

Let's say I open one new tmux session, and have a script running there, which outputs 1 new line per second. 

If I detach and then, after 5 minutes, enter again the tmux session, I will only see the output history which fits in my window screen. If I scroll up, I will NOT see more of the history, but either only black blank space or the history of my main terminal session.

The problem seems to be the same like described in https://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows/1292#1292 for multiple terminal windows, BUT the described solution there does not work here.
