### ISSUE TITLE
Wildcard/ignore for escaping from a custom key-table?

### ISSUE THREAD

**Issue by treyharris** [tmux/tmux#1104]
The manual gives an example for how to use custom key-tables to make the sequence `abc` run `list-keys`:

```
bind-key -Ttable2 c list-keys
bind-key -Ttable1 b switch-client -Ttable2
bind-key -Troot   a switch-client -Ttable1
```

Unfortunately, this makes the `a` key otherwise unusable. You could do this:

```
bind-key -Ttable2 a send-keys aba
bind-key -Ttable2 b send-keys abb
bind-key -Ttable2 c list-keys
[...]
bind-key -Ttable1 a send-keys aa
bind-key -Ttable1 b switch-client -Ttable2
bind-key -Ttable1 b send-keys ab
bind-key -Ttable1 c send-keys ac
bind-key -Ttable1 d send-keys ad
[..]
bind-key -Troot   a switch-client -Ttable1
```

and so on for every single possible key except for the ones you want to run `switch-client` or the eventual command(s).

But one could also imagine an `ANY` key that could be used like:

```
bind-key -Ttable2 c list-keys
bind-key -Ttable2 ANY send-key ab
bind-key -Ttable1 b switch-client -Ttable2
bind-key -Ttable1 ANY send-key a
bind-key -Troot   a switch-client -Ttable1
```

That way, typing `a` followed by anything but `b` would "escape", giving you just an `a`; typing `ab` followed by anything but `c` would give you just `ab`.

Finally (best, but perhaps hardest to implement) would be something like:

```
bind-key -Ttable2 c list-keys
bind-key -Ttable2 ANY switch-back
bind-key -Ttable1 b switch-client -Ttable2
bind-key -Ttable1 ANY switch-back
bind-key -Troot   a switch-client -Ttable1
```

This would give you the equivalent of the earlier example with each key listed explicitly; `abq` would give `abq`, `ag` would give `ag`, and so on, by returning back to the prior key-table with the key still in the input buffer.

My use case is that I would like to implement RFC 1345 Unicode input, allowing typing of thousands of characters using ASCII multigraphs. Since it uses variable-width mnemonics, I'd need tens of thousands of lines of configuration code to do it with the current key-table method, 98% or so of which would be to reject incorrect sequences.

**Comment by nicm** [comment]
You can try this [x.diff.txt](https://github.com/tmux/tmux/files/1414354/x.diff.txt) but I'm not entirely sure it is a good idea.
