### ISSUE TITLE
Shift-Down is registering as Shift-Up in 2.6

### ISSUE THREAD

**Issue by txgruppi** [tmux/tmux#1108]
- tmux version 2.6
- Mac OSX 10.12.6 (Sierra)
- iTerm2 3.1.3 (also tested on Terminal 2.7.3)
- zsh 5.2
- $TERM=screen-256color (also tested with $TERM=xterm-256color)

Minimal config:

```
bind-key -n S-Down new-window -c '#{pane_current_path}'
```

Description:

Try to use Shift + Down to create a new window.

On my machine it displays the letter "A" which I believe comes from the escape sequence `[1;2A` but as far as I know this sequence is for Shift + Up. The sequence for Shift + Down should be `[1;2B`.

If I try these keys outside of tmux it displays "A" and "B" correctly.

With version 2.5 it works.

**Comment by nicm** [comment]
This is the same as https://github.com/tmux/tmux/issues/1105.
