### ISSUE TITLE
pane_title won't display title if it contains Chinese characters.

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#1109]
- CentOS 6.5 32-bit
- tmux version master, compiled and installed from git commit 044019d9
- $TERM: xterm-256color

a minimal tmux config:

    set -g default-terminal "xterm-256color"
    
    set -g pane-border-status top
    set -g pane-border-format "#{?pane_active,#[reverse],}#{pane_index}#[default] ""\"#(echo #{pane_title} | sed \"s#$HOME#~#g\")\""

`pane_title` variable won't display title if it contains Chinese characters, if it contains no Chinese characters, it works fine.

Notice the statue line of the top/bottom and the info in `choose-tree`.

![snapshot1](https://user-images.githubusercontent.com/2135996/31378830-1c28a900-addf-11e7-982f-54317088d073.png)
![snapshot2](https://user-images.githubusercontent.com/2135996/31378845-22cca20c-addf-11e7-8aeb-34212a5d4526.png)
![snapshot3](https://user-images.githubusercontent.com/2135996/31378856-25409412-addf-11e7-8bd9-b367cd430c08.png)
![snapshot4](https://user-images.githubusercontent.com/2135996/31378865-27d19ca8-addf-11e7-9786-ea1a87cae7bc.png)

**Comment by nicm** [comment]
If you just do:
~~~~
set -g pane-border-format '#{pane_title}'
~~~~
instead of using #(), is it any different?

**Comment by c02y** [comment]
No, the same result.

**Comment by nicm** [comment]
It works OK for me, show me logs please.

**Comment by c02y** [comment]
To run tmux without a config and get logs,

    tmux -Ltest kill-server
    tmux -vv -Ltest -f/dev/null new

and then

    tmux choose-tree



[tmux-server-5703.log](https://github.com/tmux/tmux/files/1374684/tmux-server-5703.log)

**Comment by nicm** [comment]
This appears to be a problem with your shell or the scripts that are setting the title. You can see the OSC commands tmux is receiving:
~~~~
1507708361.244407 input_exit_osc: "0;fish  /home/chz"
1507708361.271337 input_exit_osc: "0;fish  /home/chz"
1507708361.276363 input_exit_osc: "0;fish  /home/chz"
1507708364.996694 input_exit_osc: "0;cd  /home/chz"
1507708365.004379 input_exit_osc: "0;fish  /tmp/"
1507708369.519992 input_exit_osc: "0;tmux  /tmp/"
1507708369.531724 input_exit_osc: "0;fish  /tmp/"
1507708372.088580 input_exit_osc: "0;x  /tmp/"
~~~~
There is no UTF-8 data in any of these. If I do it manually in tmux:
~~~~
printf '\033]0;tmp/\351\233\206\344\270\255\345\255\230\345\202\250\346\223\215\344\275\234\347\263\273\347\273\237\346\227\245\345\277\227\345\217\212iscsi\351\205\215\347\275\256\344\277\241\346\201\257/\a'
~~~~
It works fine:
![x](https://user-images.githubusercontent.com/304243/31429270-7efeaa8a-ae65-11e7-8abd-633e520ff56b.png)

**Comment by c02y** [comment]
> This appears to be a problem with your shell or the scripts that are setting the title. 

`tmux -vv -Ltest -f/dev/null new` works without loading .tmux.conf, right? Even if I use my simple .tmux.conf, (only three lines of configuration in the first post), it is the same result. 

So

    the scripts that are setting the titl

is not existed.

After I execute tmux in bash instead fishshell, yes, it is the problem of my shell (fish shell).

But how can I solve this problem?

**Comment by nicm** [comment]
I don't know, I think you will need to ask the fish developers.

**Comment by c02y** [comment]
Sure, I already posted an issue in fishshell repo issue page.

Thanks.

**Comment by nicm** [comment]
OK cool.

**Comment by c02y** [comment]
I can get around this issue by modifying the .tmux.conf  file:
from 

    set -g pane-border-format "#{?pane_active,#[reverse],}#{pane_index}#[default] ""\"#(echo #{pane_title} | sed \"s#$HOME#~#g\")\""

to 

     set -g pane-border-format "#{?pane_active,#[reverse],}#{pane_index}#[default] ""\"#(echo #{pane_current_path} | sed \"s#$HOME#~#g\")\""

i.e., change `pane_title` to `pane_current_path`.
