### ISSUE TITLE
Need more info about version of tmux if compiled and installed from git source code.

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#1110]
When I compiled and installed tmux from git source code, and want to post an issue in here. You need the version of the tmux. But it always shows `tmux master` no matter when I compiled and installed from git source code.

The best strategy is, when I compiled and installed tmux from git source code, put the latest commit into the version info of tmux so I can know exactly the version of tmux, and it is easier to track down the problem from the right source code.

**Comment by nicm** [comment]
No this is not going to happen, I am not making git a dependency. You can
check where your repository is with git status or git log, or just make
sure you are up to date before you reproduce.
