### ISSUE TITLE
Can I make Tmux stay in 'prefix mode' until I press escape?

### ISSUE THREAD

**Issue by Krakob** [tmux/tmux#1111]
Hello! I asked [this question on Super User](https://superuser.com/questions/1257491/can-i-make-tmux-stay-in-prefix-mode-until-i-press-escape) without any luck, so I figured I'd post it here:

> Similarly to Vim's modes, I'd like Tmux to stay in 'prefix mode' (what do you actually call it?) until I hit Escape, so that I'd be able to do something like
> 
> `Prefix h j + +`
> 
> instead of
> 
> `Prefix h Prefix j Prefix + Prefix +`
> 
> and not have to worry about timers or excessive chording.

I'm personally running Tmux 2.1 on Xubuntu 16.04, but that's not all too relevant I'd wager.

**Comment by nicm** [comment]
You could rebind all your keys to add switch-client -Tprefix to the end of each command sequence, but there is no automated way to do this.

**Comment by Krakob** [comment]
That sounds like a workable solution! I prefer having explicit keybinds anyhow. As I understand it, what this command does is to try to switch client, but we don't give it anything so it just "switches" to where it already is, and then sends prefix. Is that right?

I'll try to implement it tomorrow. Going to send a mail to the mailing list about a proper feature, also.

Thank you for your help!

**Comment by Krakob** [comment]
I've now got it working, thanks! One issue though, it will exit prefix mode if an action fails, for example `bind j switch-client -p \; switch-client -T prefix` works as expected when there are several sessions but when there isn't, I'm not in prefix mode.

**Comment by nicm** [comment]
switch-client -T just changed the current key table for a client. I am not sure we need an automated way to do this unless it can be done very simply.

**Comment by nicm** [comment]
Yes error will cancel the command sequence you could get around this by using run-shell eg

run "tmux mycmd; tmux switch-client -Tprefix"

But that might hide the error from being displayed.

**Comment by Krakob** [comment]
Good to know, thanks a bunch! :)
