### ISSUE TITLE
Mouse select copy not getting into paste bin

### ISSUE THREAD

**Issue by fewstera** [tmux/tmux#1113]
Hey,

I recently upgrade to Mac Sierra (clean install) and installed tmux 2.6.

I've installed and configured reattach-to-user-namespace and it seems to be working well in tmux. For example `echo 'hi' | pbcopy` does end up changing the pastebin to hi.

I'm having an issue where after enabling mouse support, when I drag and select text, the text gets highlighted then when I let go the highlighting removes, if I then try to paste, my paste bin hasn't been updated with the selected text.

```
~ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.6
xterm-256color
```
```
~ cat ~/.tmux.conf
set-option -g default-command "reattach-to-user-namespace -l zsh"
set -g mouse on
```

**Comment by nicm** [comment]
When you paste with C-b ] right?

**Comment by fewstera** [comment]
No, I'm trying to paste using the system pastebin, so 'Cmd + V.'

Thanks

**Comment by nicm** [comment]
tmux has no control over your system clipboard.

**Comment by nicm** [comment]
You can make it use it either with copy-pipe, or if your terminal supports
it, set-clipboard.

**Comment by fewstera** [comment]
i'm using iterm so I believe I can uset set-clipboard.

I could've sworn that this happend on my previous setup (Yosemite - tmux 2.1).

How would I make tmux use either copy-pipe or set-clipboard?

Thanks for your fast responses.

**Comment by fewstera** [comment]
I managed to fix this with the following config:
```
# Fix copying behaviour
set-option -g default-command "reattach-to-user-namespace -l zsh"
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
```

My full tmux.conf incase it helps anyone else:
```
set-option -g default-shell /bin/zsh
set -g default-terminal "screen-256color"
set -g mouse on

# Move around like vim!
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

# When opening new pane, open at current path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Fix ESC in vim
set -s escape-time 0

# Make it like vi
set-window-option -g mode-keys vi

# Setup 'v' to begin selection as in Vim, 'y' or 'Enter' yanks
bind-key    -T copy-mode-vi    v send-keys -X begin-selection
bind-key    -T copy-mode-vi    y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key    -T copy-mode-vi    Enter send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Fix copying behaviour
set-option -g default-command "reattach-to-user-namespace -l zsh"
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

## Bind ']' to use pbpaste
bind ] run "reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"
```

Thank you for building tmux and your help in this ticket.

Aidan

**Comment by alexfornuto** [comment]
@fewstera thanks for posting the solution that worked for you! I'm hoping some courageous soul could demonstrate the same type of solution for Linux. In other words, I would also like to a) have mouse support enabled in tmux, and b) have selected text go to my system clipboard, so I can paste into other applications. 

I'm running gnome, which I assume affects the clipboard available. TIA!

**Comment by fewstera** [comment]
@alexfornuto I guess if you install xclip then you can use the following to enable click and drag copying:

```
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip"
```

**Comment by alexfornuto** [comment]
@fewstera I installed xclip and tried that line, to no avail unfortunately.

**Comment by rofrol** [comment]
@alexfornuto

I have this in `/.tmux.conf`:

```
'tpope/vim-commentary'
```
After running `tmux source-file .tmux.con`, I can select text with mouse and it gets copied to clipboard.

Ubuntu 18.10.
