### ISSUE TITLE
Search feature inside `choose-tree` view.

### ISSUE THREAD

**Issue by bitifet** [tmux/tmux#1114]
Hello!

I would propose a feature idea I think it could be interesting to many people.

I intensively use tmux and always have many sessions with their own windows each and I really appreciate `choose-tree` (prefix + 's') to navigate over all sessions and windows.

But I sometimes forgive where I put something in what I worked before but I must left to attend other tasks.

So I think it will be wonderful if we simply could type "/" + some text to search text patterns inside session and window names.

For windows, their session should be unfolded too to make them visible when matched.

It not need to be interactive (search while typing): Of course, interactive would be great. But simply being able to search for a word, phrase or regex would be much enought.

It's just an idea.

Anyway, thanks for this wonderful tool ;-)

**Comment by nicm** [comment]
Like C-s?...

**Comment by bitifet** [comment]
Sorry!

A searched about it previously (Man, Google, Stackoverflow...).

...and even I searched in this project changelog but I searched by **"choose-tree"** (the name of the man section I fully read searching for this feature) because I knew man page I read is of my current tmux version (2.1).

Now I see this paragraph in CHANGELOG I missed before:

* Major rewrite of **choose mode**. Now includes preview, sorting, searching and
  tagging; commands that can be executed directly from the mode (for example,
to delete one or more buffers); and filtering in tree mode.

I apologize for that. Sorry.

**Comment by nicm** [comment]
Key bindings are in the manual:
~~~~
     choose-tree [-Nsw] [-F format] [-f filter] [-O sort-order] [-t
             target-pane] [template]
             Put a pane into tree mode, where a session, window or pane may be
             chosen interactively from a list.  -s starts with sessions
             collapsed and -w with windows collapsed.  The following keys may
             be used in tree mode:

                   Key    Function
                   Enter  Choose selected item
                   Up     Select previous item
                   Down   Select next item
                   <      Scroll list of previews left
                   >      Scroll list of previews right
                   C-s    Search by name
                   n      Repeat last search
                   t      Toggle if item is tagged
                   T      Tag no items
                   C-t    Tag all items
                   :      Run a command for each tagged item
                   f      Enter a format to filter items
                   O      Change sort order
                   v      Toggle preview
                   q      Exit mode

**Comment by enanajmain** [comment]
How can I format the items in the pane of choose-tree?
