### ISSUE TITLE
S-Down broken

### ISSUE THREAD

**Issue by rathsky** [tmux/tmux#1117]
Commit 25cf126d (Use kind and kri for S-Up/Down as well as kUP and kDN.) breaks S-Down for me, leading it to be reported a S-Up.

Culprit seems to be the added "TTYC_KRI, KEYC_UP" part in tty-keys.c, changing it to KEYC_DOWN (like commit db44151a did for TTYC_KIND) fixes it for me.

**Comment by nicm** [comment]
kri is S-Up and kind is S-Down so it now correct.
