### ISSUE TITLE
Pane size not updating while executing script.

### ISSUE THREAD

**Issue by MasterTextman** [tmux/tmux#1118]
Linux x86_64
tmux master
rxvt-unicode

I wrote a script that launched ncmpcpp in 3 different panes that were equal in horizontal size, and it glitched out. So, to try and figure out the problem, I wrote a different script:

```
#!/bin/sh

printf '\033[8;29;252t'

tmux new-session -d 

tmux select-layout even-horizontal
tmux send-keys -t 0 'tput cols' Enter
tmux split-window -h 

tmux select-layout even-horizontal
tmux send-keys -t 1 'tput cols' Enter
tmux split-window -h 

tmux select-layout even-horizontal
tmux send-keys -t 2 'tput cols' Enter

tmux send-keys -t 2 'tput cols' Enter
tmux send-keys -t 1 'tput cols' Enter
tmux send-keys -t 0 'tput cols' Enter

tmux a #
```

What this script does, is ensure that the size at the start at the script is at a fixed size, 252x29, and then it starts a new session, in which 3 panes are opened and evened out.
`tput cols` should show the amount of columns in each pane.
I did them twice for each pane, one before I split the others, and one after. But in some weird fashion, they all came out the same.

Pane 1 said it had 40 columns, Pane 2 said it had 39, and Pane 3 said it had 19.
After the script ran, I typed `tput cols` manually in each pane.
Pane 1 said it had 84 columns, Pane 2 said it had 83, and Pane 3 said it had 83.

There is a major difference between the script result and the manual result. Is there a way the size of each pane could be updated while the script is running?

**Comment by nicm** [comment]
You need to use -x and -y with new-session.

**Comment by MasterTextman** [comment]
It worked, I think. Using tput cols, the first two are now 126 and 125, while the third one is 62.
I used `tmux new-session -d -x 252 -y 29`.
