### ISSUE TITLE
Copy does not copy all of the selcted text.

### ISSUE THREAD

**Issue by sittim** [tmux/tmux#1119]
## Issue

Only a portion of data is copied, here is the image of data:

![selection_210](https://user-images.githubusercontent.com/8825037/31667404-5cb0b146-b31d-11e7-818d-5b938f9098c1.png)

When I copy starting on line `>{uC:8388}`, and paste anywhere, (I tried Atom, Sublime ...)  This is all I get, it is only a portion of the initial selection.

![selection_211](https://user-images.githubusercontent.com/8825037/31667621-f54c7e6c-b31d-11e7-825c-49a179cfafa6.png)

## Info
- tmux version - 2.6
- OS - Ubuntu 16.04
- terminal - ST v 0.7
echo $TERM - st-256color
uname -sp && tmux -V && echo $TERM
```
Linux x86_64
tmux 2.6
st-256color
```

**Comment by nicm** [comment]
Does this still happen in xterm?

**Comment by sittim** [comment]
One other note, it is not consistent, it does not happen for a while, than all of a sudden it begins to happen.  Also there are no issues with small text snippets.  I tried it in `xterm` few times, it did not seem to happen yet.  It usually takes a while for it to begin to happen.

**Comment by nicm** [comment]
It is more likely that st has a length limit and you are only occasionally copying enough to hit it. Make sure you are copying the same amount of text in xterm and in st.

**Comment by nicm** [comment]
st length limit for escape sequences appears to be 1024 bytes which means you will not be able to copy any more than around 764 bytes. Well, you can copy them and they will be stored in a tmux buffer, but they will not be copied to the X clipboard.

**Comment by sittim** [comment]
I use the following command, does it not bypass st?

```
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel\; run "tmux save -|xclip -sel clip >/dev/null 2>&1"
```

**Comment by sittim** [comment]
Oh, did not know about that, I will have to look into it, here my .tmux.conf

```
# set-option -ga terminal-overrides ",xterm-256color:Tc"
# set -g default-terminal "xterm-256color"

set-option -ga terminal-overrides ",st-256color:Tc"
set -g default-terminal "st-256color"

# set-option -ga terminal-overrides ",screen-256color:Tc"
# set -g default-terminal "screen-256color"

set-option -g history-limit 100000 
set-option -g default-shell /usr/bin/fish
set-window-option -g mode-keys vi
setw -g mode-keys vi

set-window-option -g status-left " #S "
set-window-option -g status-right " %H:%M %d-%b-%y "
set-window-option -g window-status-format " #I: #W "

set-window-option -g window-status-current-format " #I: #W "

bind-key -n C-S-Up resize-pane -U 10
bind-key -n C-S-Down resize-pane -D 10
bind-key -n C-S-Left resize-pane -L 10
bind-key -n C-S-Right resize-pane -R 10

# Smart pane switching with awareness of vim splits
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel\; run "tmux save -|xclip -sel clip >/dev/null 2>&1"
# bind-key -T copy-mode-vi y send-keys -X copy-selection
# bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe "xclip -in -selection clipboard"
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# mouse support
setw -g mouse on

bind-key b send-keys -R \; clear-history

# force a reload of the config file
unbind r
bind r source-file ~/.tmux.conf

unbind e
bind e split-window -h -l 80

# quick pane cycling
unbind ^A
bind ^A select-pane -t :.+

set -g @shell_mode 'vi'

```

**Comment by nicm** [comment]
Try
~~~~
set -g set-clipboard off

**Comment by codebam** [comment]
I still have this issue with `set -g clipboard off`

**Comment by enanajmain** [comment]
@nicm, could you explain briefly why I need to use `set-clipboard off`? I mean, I get that there will be undefined behaviour as to who gets to set clipboard, st or xclip. But why is that? And why would one be different that the other?
