### ISSUE TITLE
Terminal not available in .tmux.conf

### ISSUE THREAD

**Issue by mathstuf** [tmux/tmux#1120]
In my `.tmux.conf` file, I check to see if the terminal is 256-color enabled or not and if so, source my 256-color configuration file using `tput`. This has started failing because it errors out with `tput: terminal attributes: No such device or address`. It isn't `tmux` (1.8 shows the same problem), but something in the stack has shifted and I'm not familiar enough to know what it could be.

For baseline, this worked on Fedora 25 installs, but now that I've upgraded to Fedora 26, things have changed and I've been unable to figure out what the root cause is. libevent is unchanged between the two and it happens with multiple terminals (rxvt-unicode and alacritty). What else should I be looking at?

**Comment by nicm** [comment]
Is this https://marc.info/?l=ncurses-bug&m=150715574431080&w=2?

**Comment by mathstuf** [comment]
That would indeed seem to be the problem, thanks. It looks like it was fixed in mirror/ncurses@cd142df6d9934f1bda19f5b968cc666291be5072.
