### ISSUE TITLE
Start up very slow on msys2.

### ISSUE THREAD

**Issue by eromoe** [tmux/tmux#1121]
I don't know it is by tmux or msys2, so I post both.

```
$ pacman -Ss tmux
msys/tmux-git 2.5.94.g73b9328c-1 [installed]
    A terminal multiplexer
```

It take at least 10 second to start up:
![tmux](https://user-images.githubusercontent.com/3938751/31697487-7ace5d4a-b3ea-11e7-822f-c026b8f51b8f.gif)

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by eromoe** [comment]
Have updated, and my conf is  https://github.com/gpakosz/.tmux/. 

And I found that, after set `TERM=xterm-256color`, it became much more faster. I don't know why.

**Comment by nicm** [comment]
Of the slow startup, that is.

**Comment by eromoe** [comment]
[tmux-server-13816.log](https://github.com/tmux/tmux/files/1394121/tmux-server-13816.log)
Is this OK?

**Comment by nicm** [comment]
So it is slow with TERM=xterm and fast with TERM=xterm-256color?

Can you show me log from xterm-256color as well?

If it is fast once tmux is already running (ie you are attaching to an existing server), then probably it is something to do with the first time we read the TERM data.

**Comment by eromoe** [comment]
No,  `TERM=xterm` and `TERM=xterm-256color` both slow  after kill all task and restart (I all test with config. )
Without config file,  `tmux -vv -Ltest -f/dev/null new`  takes 2~3 second to start up.

And I found that, if one console already enter tmux(took  10s ), then I started another one and enter tmux would be very fast. So my previous  conclusion is wrong.

PS： I am home now, PC is different, I would test on my work PC tomorrow.

**Comment by eromoe** [comment]
I move ssh-agent problem to another issue https://github.com/tmux/tmux/issues/1122

**Comment by nicm** [comment]
Can you run tmux with strace, like this:
~~~~
pkill tmux
strace -ttt -f -ostrace.out tmux new
~~~~
Wait until tmux starts, then exit tmux then show me the strace.out file.

**Comment by eromoe** [comment]
[strace.log](https://github.com/tmux/tmux/files/1394510/strace.log)

**Comment by nicm** [comment]
This is next to useless because it does not distinguish between different processes, but there is a 5 second delay here:
~~~~
00:00:03 [main] tmux 16096 select_stuff::wait: m 4, us 18446744073709551615, wmfo_timeout -1
00:00:08 [socksel] tmux 16096 peek_socket: read_ready: 1, write_ready: 0, except_ready: 0
~~~~
And I do not see a similar delay in the tmux logs (there is no delay until tmux has clearly started and is waiting for a key press).

I think you will need to ask the msys2 developers what is going on.

**Comment by nicm** [comment]
Closing but please comment again and let me know if you get any further.
