### ISSUE TITLE
tmux would stuck ssh-agent (auto-login)

### ISSUE THREAD

**Issue by eromoe** [tmux/tmux#1122]
```
$ uname -sp && tmux -V && echo $TERM
MINGW64_NT-6.1 unknown
tmux master
xterm
$ pacman -Ss tmux
msys/tmux-git 2.5.94.g73b9328c-1 [installed]
    A terminal multiplexer
```

Several times enter & quit tmux may cause this problem. tmux would make ssh-agent freezed(stuck or broken) . I have to kill all ssh-agent and restart tmux. Then works some time, error again.

You can see this,  
![tmux](https://user-images.githubusercontent.com/3938751/31716900-67007058-b43c-11e7-9258-0b262d40270a.gif)

gif shows:
1. enter tmux, stuck
2. quit, enter again, still stuck
3. kill ssh-add not work, so kill ssh-agent

After ssh-agent killed, tmux could work with ssh-agent again, would not stuck. But severals quit & enter would happen again.

logs:
[tmux-server-13592.log](https://github.com/tmux/tmux/files/1394435/tmux-server-13592.log)
[tmux-client-17148.log](https://github.com/tmux/tmux/files/1394436/tmux-client-17148.log)

ssh-agent is auto-start, script by https://help.github.com/articles/working-with-ssh-key-passphrases/#auto-launching-ssh-agent-on-git-for-windows .

Doesn't see this problem when only using git-bash, msys2(not enter tmux).  

In addition, ssh-agent seems would expire the passphrases after a long time, then when I start a new console(git-bash/msys2), would prompt to ask me enter passphrases. Maybe that is not by expire mechanism, because  github's auto-start script not show code about this.  I don't know if it is relative,  just let you know.

**Comment by nicm** [comment]
I do not think this is anything to do with tmux.

**Comment by eromoe** [comment]
Hmm... it is strange.  Only severals quit & enter `tmux` would happen , so you mean it is by ssh-agent?

**Comment by nicm** [comment]
Are you sure you are not ending up with 2 ssh-agent or something?

**Comment by eromoe** [comment]
What do you mean `ending up with 2 ssh-agent` ? 
I come up one thing,  msys has its ssh-agent, which is different from git-bash . And the version is different too. It doesn't happen on my work PC today,  may due to I update all pakcages today . My home PC is using old ssh package. I would tried that.

**Comment by nicm** [comment]
OK let me know if that fixes it.

**Comment by eromoe** [comment]
Never happen again until now, after update ssh and .tmux.conf

PS: I also found there were some sh.exe(6 ~11) runing on background after enter tmux  yesterday later . Also may by the .tmux.conf I used.  What ever, it is solved now.
