### ISSUE TITLE
Choose-tree ignores pane-base-index in preview

### ISSUE THREAD

**Issue by Crote** [tmux/tmux#1125]
Platform: Fedora 26
Version: 2.6
Config: set `pane-base-index` to anything but `0`

As far as I can tell, this bug is purely visual and doesn't have any real input, but it's just annoying enough.

---
In my tmux.conf, i have set `pane-base-index` to `1`, as I don't like them starting at `0`.

The new `choose-tree` command has a very interesting bug. When a window has been selected in the list, the preview will show the panes with their index numbers. In the screenshot below, the left pane is pane `1` due to my `base-pane-index`, but a `0` is shown, which is wrong. The index is however correct in the selection list above.
![screenshot from 2017-10-20 01-58-39](https://user-images.githubusercontent.com/931757/31799592-43330816-b53b-11e7-813c-358b63f926ad.png)

Just for the record, `display-panes` is doing it correct, and I would expect the numbers in `choose-tree` to look identical.
![screenshot from 2017-10-20 01-58-14](https://user-images.githubusercontent.com/931757/31799643-9bad29c2-b53b-11e7-82f3-b169065a68ed.png)

**Comment by ThomasAdam** [comment]
Untested, but try the attached patch.
[x.diff.txt](https://github.com/tmux/tmux/files/1400813/x.diff.txt)

**Comment by Crote** [comment]
I tested it locally and it seems to fix it without any issues! :+1:

**Comment by nicm** [comment]
Applied, thanks.
