### ISSUE TITLE
Add a `zoom` flag to choose-tree

### ISSUE THREAD

**Issue by Crote** [tmux/tmux#1126]
Tmux 2.6 introduces a very nice preview  to `choose-tree`.

However, when a lot of panes are being used, the preview displayed in a small pane is often too small to be really useful. It would be nice if `choose-tree` were to have a `-Z` flag which would zoom the pane in which `choose-tree` is being run for the duration of the command. This way the previews would be as large as possible, which would make them even more useful.

If there is another way to do this I'd be happy to use that as well, but I have yet been unable to find one.

**Comment by ThomasAdam** [comment]
Adding a -Z flag here is not the right approach.

`resizep -Z` already exists for this reason, and can still work for you, however, the `choose-tree` command will need changing to support the use of `resizep -Z` afterwards, as in:

`resizep -Z ; choose-tree ; resizep -Z`

Currently won't work in the way it should.

**Comment by nicm** [comment]
Yes it doesn't work because choose-tree does not block the command queue until the mode is exited - if it did then you would need to finish with choose-tree before you could do anything else in that client. You could do it with a script that loops until the mode is exited though.

I toyed with the idea of making modes always zoom, like this: [z.diff.txt](https://github.com/tmux/tmux/files/1404920/z.diff.txt)

I quite like this but I'm not sure it is a good idea.

A -Z flag might be OK instead.

**Comment by ThomasAdam** [comment]
@nicm -- I think your z.diff patch makes a lot of sense -- typically speaking, if someone has entered a choose-* mode, then it's unlikely they're going to want to do anything else with the client anyway.  I can't say I've ever been in a situation where I've run `choose-tree` in a pane, and carried on in an editor.

Zooming by default makes sense to me

**Comment by nicm** [comment]
This works too:
~~~~
set-hook -g pane-mode-changed 'resizep -Z'

**Comment by nicm** [comment]
This works better:
~~~~
set-hook -g pane-mode-changed 'if -F "#{||:#{&&:#{pane_in_mode},#{&&:#{pane_in_mode},#{!=:#{pane_mode},copy-mode}}},#{&&:#{?pane_in_mode,0,1},#{window_zoomed_flag}}}" "resizep -Z"'

**Comment by nicm** [comment]
Well, it doesn't work if you are zooming panes yourself, since it will unzoom unexpectedly. Anyway we could probably tweak it so this could be done with hooks.

**Comment by nicm** [comment]
I tried adding a -Z flag and I quite like it too [tmux-mode-zoom.diff.txt](https://github.com/tmux/tmux/files/1673656/tmux-mode-zoom.diff.txt)

**Comment by DmitryBochkarev** [comment]
Will this patch be included in tmux?

**Comment by nicm** [comment]
Maybe. Did you test it?

**Comment by Crote** [comment]
For those interested, https://gist.github.com/Crote/48361cf486c39da0d11f7d7ab6f9c5c2/45fcb5202dfbe445ba01b30a762b74e9d508e5df is a patch which applies to master, https://gist.github.com/Crote/48361cf486c39da0d11f7d7ab6f9c5c2/f7026de95a4d7b8bda1e48c2548a9a9c2a988bb8 applies to 2.6. A Fedora 26 build of 2.6 with this patch is available in [this](https://copr.fedorainfracloud.org/coprs/crote/tmux-latest/) copr.

This seems to be working exactly as I intended! The zoom works properly, even when choose-tree is cancelled. I'll try it out for a while and report back when I find a bug.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. I also added -Z to the default key bindings.
