### ISSUE TITLE
Add mouse support for the choose-tree preview

### ISSUE THREAD

**Issue by Crote** [tmux/tmux#1127]
I recently updated to 2.6 and the `choose-tree` preview looks quite nice. However, I tried clicking on the content of the preview to select that item and it didn't work. Clicking in the actual tree works fine, so my mouse support is fine.

This feature would just be nice to have, but it would make sense if I could select items by clicking in the preview, and if the side scroll arrows in the preview were to be clickable as well.

**Comment by nicm** [comment]
This is now done in OpenBSD, will be in GitHub later.
