### ISSUE TITLE
configure: check for proper libevent version

### ISSUE THREAD

**Issue by barsnick** [tmux/tmux#1130]
configure.ac could, or rather should, contain a proper check for the required libevent version:

```
--- tmux-2.6/configure.ac       2017-10-05 15:30:34.000000000 +0200
+++ tmux-2.6-libevent_version_b/configure.ac    2017-10-23 16:31:22.000000000 +0200
@@ -127,7 +127,7 @@
 # Look for libevent.
 PKG_CHECK_MODULES(
        LIBEVENT,
-       libevent,
+       libevent >= 2.0,
        [
                AM_CFLAGS="$LIBEVENT_CFLAGS $AM_CFLAGS"
                CFLAGS="$AM_CFLAGS $SAVED_CFLAGS"
```

This avoids issues like #856, which lead to user irritation and googling. ;-)

Actually, I believe the preferred "proper" syntax is
```
PKG_CHECK_MODULES(
        [LIBEVENT],
        [libevent >= 2.0],
...
```
but I don't know which autoconf version allows this, or which autoconf version enforces this, and it works fine without, so probably no need to bother for the time being.

**Comment by nicm** [comment]
Yes, it is probably going to be more trouble than it is worth.
