### ISSUE TITLE
Auto balance panes in vertical or horizontal orientation

### ISSUE THREAD

**Issue by mattkrass** [tmux/tmux#1131]
It would be nice if there was a hotkey or command to auto balance selected panes in height or width instead of needing to manually size them. I had to write a shell script of tmux commands to reliably construct a three tier vertical split to the right of a horizontal split and it only works if my window and font sizes are preset to known values. Something like select-layout even-vertical, but only for a given horizontal pane, and even-horizontal for a given vertical pane would be very effective.

**Comment by nicm** [comment]
Try this please (then C-b E): [x.diff.txt](https://github.com/tmux/tmux/files/1414372/x.diff.txt)

I wrote this ages ago and didn't use it, but I don't remember if there was a problem with it or it wasn't something I needed.

**Comment by mattkrass** [comment]
Tried it tonight, works great in both directions, any chance of this becoming a permanent feature?

**Comment by mattkrass** [comment]
Any thoughts?

**Comment by nicm** [comment]
Will look at it again at some point.

**Comment by nicm** [comment]
I have applied this to OpenBSD now, will be in GitHub later. Thanks!
