### ISSUE TITLE
Window flags used to be at least single space

### ISSUE THREAD

**Issue by jeenuv** [tmux/tmux#1135]
I've recently moved to v2.6 (built from source) from v1.8 (blame the package manager). My status line had window flags, and now having moved tmux versions, I noticed that the flags expand to nothing most of the time. I.e., with the `window-status-format` set as `[#I#F#W]`, I use to have `[0 bash]`, but I now have `[0bash]`. I think the former is neater. With the new behaviour, a single window's status expand and contract depending on whether it's the current window or not.

Having had a browse, I figured that if there were no flags, v1.8 [left the flag field as single space](https://github.com/tmux/tmux/blob/1b083aa0fd2d8ac000504488135bf58e35c3361e/window.c#L647), where as v2.6 [leaves it as empty](https://github.com/tmux/tmux/blob/bd71cbbe276432ce8869baa0f2d55433e1ab820c/window.c#L766). 

Was there any rationale behind this? From what I could learn, flags don't stay single-character-wide, but it'd be the cast most of the time.

Also, I can't spot the flags documented in the manual, and it'd be good not to browse code to figure out what flags there are, and what they mean.

**Comment by nicm** [comment]
It is several years too late to complain about this but you can do
something like

#{?window_flags,#{window_flags}, }

to use a space when they are empty.

**Comment by jeenuv** [comment]
Thanks, that works. 

PS: I wasn't complaining. I didn't even realise that 1.8 that was old!

**Comment by nicm** [comment]
Great. The flags are in the status line part of the manual (search for
"STATUS LINE" heading).
