### ISSUE TITLE
Why do I reattach to an unexpected session?

### ISSUE THREAD

**Issue by Takeoffyoung** [tmux/tmux#1136]
For convenience, I alias tt = "tmux a -t $name || tmux new -s $name".
So when I want to attach to a session, if is does not exist, one will be created.

But, in the latest version (commit-id: e85213a94499a1b222c94ba3f0ec9af11c8f9024).

Once I detached from a session named "recommemd_loader", and then I want to make a new session named "recommend".

When "tmux a -t recommend" been executed, it success???

Actually, it should fail?

I don't know it's a bug or feature? If it's a feature,  how to turn it off?

**Comment by nicm** [comment]
Manual:
~~~~
     target-session is tried as, in order:

           1.   A session ID prefixed with a $.

           2.   An exact name of a session (as listed by the list-sessions
                command).

           3.   The start of a session name, for example `mysess' would match
                a session named `mysession'.

           4.   An fnmatch(3) pattern which is matched against the session
                name.

     If the session name is prefixed with an `=', only an exact match is
     accepted (so `=mysess' will only match exactly `mysess', not
     `mysession').

**Comment by nicm** [comment]
Note you can also use new-session -A for this purpose.

**Comment by Takeoffyoung** [comment]
Any choice to turn it off?

There's no configuration option for this.

Otherwise, I'd like to use elder version.

**Comment by Takeoffyoung** [comment]
I find another way to solve

Change the command order,  from `tmux a -t $name || tmux new -s $name`  to `tmux new -s $name || tmux a -t $name`

**Comment by nicm** [comment]
... why don't you read what I showed you?

**Comment by Takeoffyoung** [comment]
I've read and tried.

![image](https://user-images.githubusercontent.com/8630885/31997638-59081c74-b952-11e7-968b-0dd3b644d920.png)

I was trapped in this problem long time ago, I use iTerm2 and tmux with xtem-256color, once I could not figure it out, and thought it as a bug. 

That's why I don't use `new-sesson -A`

**Comment by nicm** [comment]
But that's not how new-session works, or attach-session. You don't give the session name as the argument, you use -s or -t:
~~~~
tmux new -A -s haha
~~~~
And you can bypass the "match the start of session name bit", by using =, so you need to change your alias to:
~~~~
tmux attach -t=$name || tmux new -s$name
~~~~

**Comment by Takeoffyoung** [comment]
Get it.

Thank you very much.
