### ISSUE TITLE
Italic and strike-through

### ISSUE THREAD

**Issue by Atcold** [tmux/tmux#1137]
I'm trying to understand how to get italic and strike-through working in Tmux. Maybe I'm doing something wrong.

```bash
echo -e "\e[1mbold\e[0m"
echo -e "\e[3mitalic\e[0m"
echo -e "\e[4munderline\e[0m"
echo -e "\e[9mstrikethrough\e[0m"
```

In Mate Terminal I get the following

![image](https://user-images.githubusercontent.com/2119355/32014917-7d267098-b98d-11e7-9269-238f54ae88d7.png)

In Tmux I get the following

![image](https://user-images.githubusercontent.com/2119355/32014986-b7738fb0-b98d-11e7-9fd7-85b1e8aea6f0.png)

How can I debug this?

---

System info: Linux x86_64, tmux 1.8, xterm (in the Terminal), screen-256color (in Tmux).
Distribution: CentOS Linux 7 (Core).

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by Atcold** [comment]
Sorry, my bad. Added some info. Are log files necessary as well?

**Comment by nicm** [comment]
tmux 1.8 is far too old for strikethrough and it will be annoying to get italics working. You need to upgrade and then set default-terminal to tmux or tmux-256color for italics. For strikethrough you will probably need to add the two strikethrough escape sequences with terminal-overrides, I forget what they are will check later.

**Comment by Atcold** [comment]
So, you suggest to build from source, right? I've moved to NYU, and here I'm no longer the system admin of my servers...

**Comment by nicm** [comment]
You will need to either build from source or see if the admin will upgrade or live with 1.8, but you will not be able to use strikethrough and I don't remember how to configure italics. 1.8 was released 5 years ago.

**Comment by Atcold** [comment]
Haha, yeah, you have a point. Let's see if I'm capable of build it in my home. :grimacing:

**Comment by Atcold** [comment]
Hmm, I've just installed from source the `v2.6`.
Setting `set -g default-terminal "tmux-256color"` gets Tmux to say `'tmux-256color': unknown terminal type.`.

**Comment by nicm** [comment]
On 25 Oct 2017 11:16 pm, "Alfredo Canziani" <notifications@github.com>
wrote:

Hmm, I've just installed from source the v2.6.
Setting set -g default-terminal "tmux-256color" gets Tmux to say
'tmux-256color':
unknown terminal type..

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1137#issuecomment-339489774>, or mute
the thread

**Comment by nicm** [comment]
Use this file  
[x.txt](https://github.com/tmux/tmux/files/1416396/x.txt)
and install it with "tic -x x.txt"

**Comment by nicm** [comment]
You will also need to do this in .tmux.conf for strikethrough to work:
~~~~
set -as terminal-overrides ',*:smxx=\E[9m'

**Comment by Atcold** [comment]
I did run `tic -x x.txt`, but Tmux kees saying `'tmux-256color': unknown terminal type.`.

**Comment by Atcold** [comment]
Oh, strike-through works with `screen-256color`. Italic does not.

**Comment by nicm** [comment]
No you need to figure out how to install the tmux terminfo entries (or copy the screen ones to tmux) or you will not be able to use italics. Are you sure you restarted tmux entirely after running tic? Does tmux instead of tmux-256color work?

**Comment by Atcold** [comment]
`'tmux': unknown terminal type.`

**Comment by nicm** [comment]
Well doesn't matter so long as programs inside don't need to use TERM to
decide if they can use italics but if you are sending the escape sequences
yourself it'll be fine.

**Comment by Atcold** [comment]
Oh... So, setting the `default-terminal` to `tmux-256color` will produce italic output with 
```
echo `tput sitm`italics`tput ritm`
```
But Tmux will start by saying `'tmux-256color': unknown terminal type.`.

**Comment by Atcold** [comment]
`set -as terminal-overrides ',*:sitm=\E[3m'` is also required.

**Comment by Atcold** [comment]
So, in summary
 - italic and strike through work as expected;
 - I don't know how you generated the `x.txt` file;
 - when Tmux is launched, I get a `unknown terminal type` error.
Can you address the latter two points, please?

**Comment by Atcold** [comment]
> That isn't coming from tmux though, it is coming from something inside
> tmux. It actually doesn't matter if TERM inside tmux is tmux, so long as
> default-terminal is. So you could change it in .profile with eg
> 
> ```bash
> [ -n "$TMUX" ] && export TERM=screen-256color
> ```

Got it. It worked.

**Comment by Atcold** [comment]
Just before closing this issue, where would someone get your `x.txt` file?

**Comment by nicm** [comment]
tmux won't use sitm unless default-terminal is tmux*. You can get the tmux* terminfo entries from another box that has them already with infocmp -x tmux, but since you didn't manage to install them you can do without them.

**Comment by Atcold** [comment]
So `tmux*` as `default-terminal` is a requirement for anything to work correctly.
Then, having the actual `tmux*` terminfo installed is optional (given the overrides).
Finally, how was the *original* `tmux*` terminfo created?

**Comment by nicm** [comment]
It has nothing to do with terminal-overrides, they (with TERM outside tmux) only tell tmux itself how to behave. You only need to add sitm there if your terminfo entry outside tmux doesn't have it.

TERM inside tmux (which is set by default-terminal), tells applications inside tmux how to behave. You don't need to worry about TERM inside tmux if you are using the escape sequences directly, only if you want applications inside tmux to use italics as well.

Having default-terminal of screen also tells tmux to emulate screen (which does not support italics); the only valid thing to set it to other than screen is tmux (or some variant). But you don't need to actually have the terminfo entry installed if you don't care whether applications use it, you can just replace it later in your shell profiles.

**Comment by jsatk** [comment]
I just came in here to say that @nicm completely solved my issue. Thanks.
