### ISSUE TITLE
Unable to use basic tmux commands in Mac OSX Sierra

### ISSUE THREAD

**Issue by JohnMerlino2** [tmux/tmux#1138]
I run tmux in terminal. I try to list general commands. I follow this guide:

https://gist.github.com/michaellihs/b6d46fa460fa5e429ea7ee5ff8794b96

I press CTRL+b and ? to show a list of all commands. The computer just makes a noise and nothing happens. tmux does not work on osx?

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by krader1961** [comment]
Tmux works just fine on macOS (aka OS X). I'm using it as I type this. Do you have a *~/.tmux.conf* file? Perhaps you've changed the prefix to something else. For example, I use [ctrl-space] by having this in my config: `set-option -g prefix C-Space`. What does `tmux show-options -g | grep prefix` show?

**Comment by JohnMerlino2** [comment]
For me it outputs this:

prefix C-b
prefix2 <NONE>
