### ISSUE TITLE
Tmux cancels vim's <C-*> <S-*> mapping

### ISSUE THREAD

**Issue by gamardzoba** [tmux/tmux#114]
**Steps to reproduce**
* Add to your ~/.vimrc:
```
nmap <C-F11> <Esc>:echo 'C-F11 pressed'<CR>
nmap <S-F11> <Esc>:echo 'S-F11 pressed'<CR>
```
* Open vim in you terminal (not via tmux) and try to press either **C-F11** or **S-F11**. There should be confirmation in vim status line;
* Open vim within tmux terminal and repeat step 2. No result in vim-status line.

**Comment by nicm** [comment]
TERM is probably wrong or you need xterm-keys on.
