### ISSUE TITLE
tmux -V not available on OpenBSD

### ISSUE THREAD

**Issue by javier-lopez** [tmux/tmux#1141]
Hello,

I'm running OpenBSD current 6.2 and tmux doesn't have the -V option to output the tmux version, is there any other way to get the tmux version in such platform?, I'm developing a [plugin manager](https://github.com/javier-lopez/tundle) and knowing the tmux version is useful to know what features are available.

```
$ tmux -V
tmux: unknown option -- V
usage: tmux [-2Cluv] [-c shell-command] [-f file] [-L socket-name]
            [-S socket-path] [command [flags]]
```

```
uname -a
OpenBSD openbsd-6.2.example.com 6.2 GENERIC#132 amd64
```

**Comment by nicm** [comment]
tmux is built in to OpenBSD so there is no separate version number.

**Comment by theScrabi** [comment]
The issue here is that tmux scripts from other operating systems are not compatible with openbsd tmux due to this reason. I know it does make sense to not add the `-V` flag for the core utils of openBSD, but in this case it's actually counter-productive.
