### ISSUE TITLE
choose-tree preview creates significant delay

### ISSUE THREAD

**Issue by buckhx** [tmux/tmux#1145]
When choosing sessions in the new preview mode of choose-tree there is a significant delay after a key is pressed. The following screen grabs demonstrate toggling between two sessions in the session chooser with and without the new preview mode of choose-tree. The config is empty when enabled, and "bind-key s choose-tree -N -w" is added to disable the preview.

Preview Enabled: https://asciinema.org/a/cyBPhJbgOhmzDy7NL94QVTVNY
Preview Disabled: https://asciinema.org/a/m1wFUlWPACUfw6O6qSkkiZaLA

```
$ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.6
xterm-256color
```

**Comment by ThomasAdam** [comment]
Which terminal are you using?  Doesn't happen in xterm for me, for instance.

**Comment by buckhx** [comment]
@ThomasAdam plain OSX Terminal. I'll try some different ones and see if there are differences.

**Comment by nicm** [comment]
Please try master now, I have made some changes which may make it faster.
