### ISSUE TITLE
new-window no longer working

### ISSUE THREAD

**Issue by rightaway** [tmux/tmux#1146]
In my tmux config file I have `bind -n S-down new-window -c '#{pane_current_path}'` so that Shift+down would create a new window. However this no longer works although I'm not sure what changed. I'm using version 2.6.

**Comment by ThomasAdam** [comment]
Try tmux master from git.

**Comment by rightaway** [comment]
It fixes the problem but creates another bug, this time in tmuxinator (latest version 0.9.0) https://github.com/tmuxinator/tmuxinator/issues/570, just thought I'd let you know in case the bug is on the tmux side.
