### ISSUE TITLE
Window split markers in wrong place with powerlevel9k prompt

### ISSUE THREAD

**Issue by cccCody** [tmux/tmux#1149]
I'm using mosh windows native client to connect to an amazon linux 2012 box
That machine has tmux 2.1, zsh 5.07 w/ prezto installed and using the powerlevel9k theme
Linux x86_64
tmux-2.1 2.1
xterm-256color
 
![tmux](https://user-images.githubusercontent.com/753031/32387115-aae1760a-c080-11e7-9035-a331ab91db0d.png)

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by cccCody** [comment]
logs:
[tmux-client-1883.log](https://github.com/tmux/tmux/files/1441910/tmux-client-1883.log)
[tmux-server-1892.log](https://github.com/tmux/tmux/files/1441911/tmux-server-1892.log)

**Comment by cccCody** [comment]
I'm not able to build it myself. I'm getting this when I run ./configure:
```
checking for event.h... no
configure: error: "libevent not found"
```
yum says I have libevent2 installed:
`Package libevent2-2.0.21-4.15.al12.x86_64 already installed and latest version`

**Comment by cccCody** [comment]
Yeah, still happens with master
[tmux-server-28061.log](https://github.com/tmux/tmux/files/1441964/tmux-server-28061.log)

![tmux](https://user-images.githubusercontent.com/753031/32388171-1336d3be-c084-11e7-97f5-dca817c42848.png)
[tmux-client-28059.log](https://github.com/tmux/tmux/files/1441962/tmux-client-28059.log)
[tmux-out-28061.log](https://github.com/tmux/tmux/files/1441963/tmux-out-28061.log)

**Comment by nicm** [comment]
I thought this might be a Unicode width issue, but the widths that tmux is reporting look consistent.

Looking more closely at the screenshot, it appears that sometimes the line is off by less than a completely cell (for example, the fourth line down). It is impossible for tmux to do this, so I this is probably a bug in your terminal (or perhaps your font), presumably it is miscalculating the width of some of these characters. You should report this to the terminal developers.

**Comment by cccCody** [comment]
Crap, I think you're right. I got a remote gnome session up on the machine and it looked fine on the built-in terminal
