### ISSUE TITLE
search-backward: avoid extraneous scrolling

### ISSUE THREAD

**Issue by ivanbrennan** [tmux/tmux#1150]
When executing a `search-backwards` search in copy-mode, the text is scrolled even if jumping to a position that was already visible. This is disorienting, as you lose your frame of reference unexpectedly.

An example scenario: I just ran `docker ps` in order to get the id of a container I want to operate on. I see the id I want, let's say it's "12345678", so I enter copy-mode `search-backward` for "123". When I hit Enter , the cursor jumps to the intended text, but the screen also scrolls, and I lose my frame of reference. I have to visually scan the screen to find the cursor and make sure I ended up where I wanted to.

Of course, it makes sense to scroll in cases where the found text would not otherwise be visible, but if it's already shown in the pane, it's unexpected and disorienting. I've noticed it only occurs if the found text is more than 5 lines from the bottom of the pane, and when it happens, it scrolls enough to ensure a 5 line offset from the bottom.

Tmux version: 2.6
Platforms tested: Ubuntu (Linux x86_64), macOs (Darwin i386)
TERM outside tmux: xterm-256color
TERM inside tmux: tmux-256color

**Comment by thornycrackers** [comment]
+1 Came to request the same, it's very jarring.

**Comment by nicm** [comment]
I quite like it but I don't really care if it changes, maybe this: [x.diff.txt](https://github.com/tmux/tmux/files/1459546/x.diff.txt)

**Comment by thornycrackers** [comment]
@nicm That works awesome thanks so much for your work!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
