### ISSUE TITLE
Set shell PWD

### ISSUE THREAD

**Issue by llchan** [tmux/tmux#1151]
I work in an environment where my home directory is mapped to a gnarly long mounted filesystem path. I prefer to  have my pwd be `/home/$USER` rather than `/some/super/long/realpath`. ~Can we make the realpath optional?~ Can we set `$PWD` for the new shell?

tmux-2.6

EDIT: updating title/message in case anyone else runs into the same issue.

**Comment by nicm** [comment]
What are you talking about?

On 8 Nov 2017 4:54 am, "Lawrence Chan" <notifications@github.com> wrote:

I work in an environment where my home directory is mapped to a gnarly long
mounted filesystem path. I prefer to have my pwd be /home/$USER rather than
/some/super/long/path. Can we make the realpath optional?

tmux-2.6

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1151>, or mute the thread

**Comment by llchan** [comment]
I suppose it's not homedir specific. I'm just requesting for a way to disable the realpath/readlink/whatever on new window/pane cwds.

```bash
$ mkdir /tmp/real
$ ln -s /tmp/real /tmp/link

:new-window -c /tmp/link

$ pwd
/tmp/real
```
I'd like for that last shell to report back `/tmp/link`. This example looks silly, but when the real path is dramatically longer than the link path it becomes important.

**Comment by nicm** [comment]
tmux does not make any change to the path you pass to -c, it is passed
directly to chdir:

$ ln -s /tmp mylink
$ ktrace -i tmux -Ltest new -dc$PWD/mylink
$ tmux -Ltest kill-server
$ kdump
...
 77797 tmux     NAMI  "/home/nicholas/tmux/mylink"
 77797 tmux     RET   chdir 0
...

You could try setting PWD as well, some shells will pick that up:

$ tmux -Ltest new -dc$PWD/mylink "PWD=$PWD/mylink $SHELL"

**Comment by llchan** [comment]
Ahhh, I see. Silly me. This makes more sense now, was confused before because I didn't see much mention of realpath/readlink in the source.

Could we do something like `environ_set(env, "PWD", "%s", wp->cwd)` so that the shell has a better chance of knowing the unresolved path that was requested?

**Comment by nicm** [comment]
Yes, could probably do that, I don't think it will do any harm.

**Comment by nicm** [comment]
You will need to only do it if chdir works though, maybe something like this: [x.diff.txt](https://github.com/tmux/tmux/files/1458974/x.diff.txt)

**Comment by nicm** [comment]
Actually that is wrong, this is better: [y.diff.txt](https://github.com/tmux/tmux/files/1458977/y.diff.txt)

**Comment by llchan** [comment]
That looks good to me. Appreciate the quick response!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
