### ISSUE TITLE
Last 2 lines of output not shown when output hits bottom of the terminal (tmux status bar)

### ISSUE THREAD

**Issue by unmanifest** [tmux/tmux#1152]
Hi - I see a problem apparently introduced in commit 130b77edc (per git bisect). I started with 2.3 as good (which is what I have been using for a long time) and 2.6 as bad. Will try to describe it but it is a lot easier with the 3 pics attached.

With the bad version of tmux (run w/o *any* tmux.conf file) and with just one full-width pane, whenever I run a command whose output hits the tmux status bar (bottom of the pane), I "lose" ~2 lines and end up with my cursor (for the new prompt) hanging. For example I ran 'ls -1' and the output looks like Image 1 below. Notice how 'xterm-keys.o' and the newline below it is is not shown properly. I'd expect it to look like Image 2. Which BTW is what I see the moment I hit "C-b [" (default bindings) right after I get the "bad output".  Notice that the cursor position in Image 1 is actually correct. It's just that I don't see my prompt strings. 

FWIW, I have a multi line prompt which begins with a blank line and in general it should look like Image 3 (when a command returns). I'm including my system details below.

Tmux running on CentOS6, ZSH;
Connected to CentOS host via mosh from a Mac via iTerm.
And BTW - this problem does not occur when I go back to tmux 2.3 - all else being exactly the same.

Image 1:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/4008865/32592366-3bae562a-c4d8-11e7-8fc0-9f4589dcac7b.png">

Image 2:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/4008865/32592378-4937c164-c4d8-11e7-836f-af1d6ea30194.png">

Image 3:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/4008865/32592402-5a86b0e2-c4d8-11e7-8001-b032c9170632.png">

**Comment by nicm** [comment]
Does it happen with ssh instead of mosh?

**Comment by unmanifest** [comment]
Just checked - you are right. It does not happen with ssh but does happen with mosh (1.3.0). And I verified both with a tmux-2.3 build and the 'bad' build.  Works fine via ssh both cases. Via mosh only tmux-2.3 works okay.

**Comment by nicm** [comment]
Seems like a mosh problem then.

**Comment by unmanifest** [comment]
I just checked the latest [mosh release notes] (https://mailman.mit.edu/pipermail/mosh-users/2017-July/000357.html) and see a bug fix regarding what appears to be the same issue w/ tmux 2.4.

Updating to mosh 1.3.2 resolves the issue. Thanks for your time.
