### ISSUE TITLE
Some commands not working

### ISSUE THREAD

**Issue by rightaway** [tmux/tmux#1156]
I'm using `master` as suggested in https://github.com/tmux/tmux/issues/1146 but now several commands like `gg` to go to the top of the screen, and `?` to start searching aren't working. It was working fine in the last release 2.6.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.
