### ISSUE TITLE
0 exit status even if not successful

### ISSUE THREAD

**Issue by vede1** [tmux/tmux#116]
This excerpt show proper behavior: 
```
$ tmux ls
failed to connect to server: Connection refused
$ tmux new-session -s s1 -d
$ echo $?
0
$ tmux ls
s1: 1 windows (created Sat Sep 19 13:07:52 2015) [95x19]
```

This excerpt shows potentially erroneous status code:
```
$ tmux ls
failed to connect to server: Connection refused
$ tmux new-session -s s1 -d /usr/bin/nocommand
$ echo $?
0
$ tmux ls
failed to connect to server: Connection refused
```
Now programs that rely on tmux's exit status cannot proceed accordingly due to not knowing that nocommand has failed.

**Comment by nicm** [comment]
It it is impractical for tmux to wait until processes it starts to exit successfully before it continues. What if you did "sleep 1000; exit 1"? Should it wait for 1000 seconds? No.
