### ISSUE TITLE
Can we change how tmux displays the window list?

### ISSUE THREAD

**Issue by varmanishant** [tmux/tmux#1160]
In the latest tmux, the windows listing bound to <kbd>C-a w</kbd> has arrows ─> indicating which session it belongs to.

Would it be possible to make it look like before without the ─>? I prefer minimal effects because it gets pretty difficult when there are lots of windows.

```
(0)  - 0: 2 windows (attached)
(1)  ├─> 1: fish- (1 panes) "fish  /home/nishant"
(2)  └─> 2: fish* (1 panes) "fish  /home/nishant"  

```

**Comment by nicm** [comment]
No this is how it is now.

**Comment by varmanishant** [comment]
Thank You.

**Comment by brainkim** [comment]
I LIKED THE OLD WAY BETTER 😠😠😠😠😠😠😠😠😠

Lock this thread fam.

**Comment by varmanishant** [comment]
So true!
