### ISSUE TITLE
Tmux panes are not displaying PS1, and long commands properly, cursor goes to the begining of the line

### ISSUE THREAD

**Issue by Wheele9** [tmux/tmux#1162]
I recorded my terminal session here  ([Ascinema](https://asciinema.org/a/j862faWqzUewDfWa6iGKUInx1)). As I typed normal letters, cursor goes back to the beginning randomly.  Issue is more severe, when pane is narrow.

I have tmux 2.6, built from source on ubuntu 16.04, I had tmux 2.1 in my other machine with ubuntu as well, it did not have this issue.

My tmux config:
https://github.com/Wheele9/vim-and-git-config-files/blob/master/.tmux.conf

Can someone help me with that? :)

**Comment by nicm** [comment]
Show tmux logs from reproducing please.

**Comment by Wheele9** [comment]
[tmux-server-6728.log](https://github.com/tmux/tmux/files/1565544/tmux-server-6728.log)
[tmux-out-6728.log](https://github.com/tmux/tmux/files/1565545/tmux-out-6728.log)

Okay I uploaded the logs

**Comment by nicm** [comment]
Hmm. If you do 
~~~~
eval `resize`
~~~~
in the pane after resizing it, does it fix it?

**Comment by nicm** [comment]
Also what do you have in PS1? Are you sure you remembered to wrap escape sequences in \[ \]?

**Comment by Wheele9** [comment]
Running resize command, did not help. My PS1:
\e[0;31m\u\e[0;36m@\e[0;35m\H\e[0;36m@\e[0;33m\w\e[0;34m\n$\e[m

(I changed to fish shell, because of the issue, it did not occur there)

**Comment by nicm** [comment]
You are not using \[ \] around escape sequences in your PS1 so your shell
is probably not calculating its width correctly.

**Comment by Wheele9** [comment]
Yes, correcting my prompt in bash solved the problem, thanks
