### ISSUE TITLE
Moving cursor between words with Ctrl+← / Ctrl+→ keys doens't work

### ISSUE THREAD

**Issue by unfa** [tmux/tmux#1163]
Tmux version: 2.6
Platform: Linux Mint 18.2 with KDE5

The problem:

I learned to use Ctrl with arrow keys to quickly navigate my commandline - skipping one word at a time, not one character at a time. It greatly speeds up my work in the terminal.

I've noticed that this doesn't work when I use tmux. It works in my raw terminal sessions, but when I use tmux, I can no longer skip one word at a time.

Does that require some configuration or is it not supported?
Am I missing something?

My $TERM is "xterm" outside of tmux, and "screen" inside tmux.

**Comment by keks24** [comment]
Hi @unfa 

You can try this in your `tmux.conf`:
```bash
set-window-option -g xterm-keys "on"
```

**Comment by ght** [comment]
Just tried it ond it works for me out of the box on Arch Linux with st 0.7.

There is [a setting in inputrc](https://wiki.archlinux.org/index.php/readline#Fast_word_movement) for that, maybe you need to set that yourself on Mint.

I usually use the [readline standard keys](https://www.gnu.org/software/bash/manual/html_node/Bindable-Readline-Commands.html) <kbd>Alt</kbd>+<kbd>B</kbd> / <kbd>Alt</kbd>+<kbd>F</kbd>, they work in a lot of cli programs and don't require moving one hand to the cursor keys. ([Cheatsheet](http://readline.kablamo.org/emacs.html), or see `man readline` and search for "default key bindings")
