### ISSUE TITLE
Tmux variables does not interpolates in rename-window function

### ISSUE THREAD

**Issue by sandric** [tmux/tmux#1164]
I want to change window name after I change pane and I have that in my tmux.conf:
```
bind -n M-Y rename-window "#{pane_current_path}"
```
But that changes window name to exacly "#{pane_current_path}", if instead I displayed message:
```
bind -n M-Y display-message "#{pane_current_path}"
```
I get current path displayed as expected.

I also tried to use hooks:
```
set-hook -g 'after-select-pane' 'rename-window "#{pane_current_path}"'
```
The same here, if I change to display:

set-hook -g 'after-select-pane' 'display-message "#{pane_current_path}"'
Again, interpolation works. Also, if I try to run
```
tmux rename-window "#{pane_current_path}"
```
in active pane as command in shell, everything works.

I'm new to tmux source code, quickly searching on issues I found out some similar questions like #711  and the solution there was to modify source code for tmux to understand variables interpolation in specific functions, mb @nicm can suggest smth?

**Comment by nicm** [comment]
Yes formats are not replaced in all places, you will need to add it to rename-window (and I would suggest rename-session as well).

**Comment by nicm** [comment]
I forgot I did this already but the person who asked about it disappeared. Please try this: 
[tmux-name-format.diff.txt](https://github.com/tmux/tmux/files/1747635/tmux-name-format.diff.txt)
