### ISSUE TITLE
tmux takes too much memory after a perid of time

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#1167]
- tmux master from github
- CentOS 64. 32-bit

unable or difficult to provide other info since this problem only occurs to me after a period of time such as days.

This happens many times, it will take too much memory comparing to my total physical memory. Check the screenshots, there are no heavy activities running in tmux. But lt lags when I type or change windows in the terminal, once I kill the tmux server and restart it, all the memory and lag problem will be gone.

And when I close all the windows and leave only one, the memory does not decrease, and it still lags when I type in the terminal.

![snapshot9](https://user-images.githubusercontent.com/2135996/33106538-7c0755ec-cf6d-11e7-8f55-0c3b67623c8b.png)
![snapshot10](https://user-images.githubusercontent.com/2135996/33106539-7c5a9bb2-cf6d-11e7-9a3a-3505bdf5cb7f.png)

**Comment by Ghosthree3** [comment]
I've been experiencing this problem for several months now using tmux to keep weechat open. Every few days or week I need to kill and restart it because it starts using way too much memory and glitching out (eg. trying to open a new window gives "Create window failed: : Cannot allocate memory"). I thought it might be scrollback history slowly growing to extreme sizes, but I don't actually have any ([0/0]).

tmux version 2.6
Kernel 4.13.11
Been happening way further back than these versions though.

**Comment by altblue** [comment]
`pane-border-status` is a very nice feature, but pitifully that is a major source of memory leaks.

Notice the `RSZ` growth slowdown after disabling `pane-border-status` in this real memory usage example:
```
→ started `tmux` with `pane-border-status` enabled
    ELAPSED      RSZ      VSZ       SZ      DRS      TRS       SZ
      00:02     1872   116788    29197   116298      489      588
   01:00:02    14432   129264    32316   128774      489    13064
   02:00:02    16180   131052    32763   130562      489    14852
   03:00:02    74032   188792    47198   188302      489    72592
   04:00:02   126644   241412    60353   240922      489   125212
   05:00:02   174780   289576    72394   289086      489   173376
   06:00:02   230728   345468    86367   344978      489   229268
   07:00:02   285308   400112   100028   399622      489   283912
→ disabled `pane-border-status`
   08:00:03   312180   426976   106744   426486      489   310776
   09:00:03   316172   431016   107754   430526      489   314816
   10:00:03   316352   431196   107799   430706      489   314996
   11:00:03   316360   431188   107797   430698      489   314988
   12:00:03   316356   431184   107796   430694      489   314984
 1-00:00:04   319860   434832   108708   434342      489   318632
 2-00:00:06   321208   436144   109036   435654      489   319944
 3-00:00:08   321036   435976   108994   435486      489   319776
 4-00:00:10   321056   435980   108995   435490      489   319780
 5-00:00:11   320972   436000   109000   435510      489   319800
 6-00:00:13   322084   437236   109309   436746      489   321036
 7-00:00:14   333580   448452   112113   447962      489   332252
```

Run a simple/crude test in order to verify this finding:
```
$ tmux -L none -f /dev/null new-session -s leaky-tmux-test 'tmux set-option -w -g pane-border-status top; tmux pipe-pane "cat>/tmp/leaky-tmux-test.log"; p=${TMUX#*,}; p=${p%,*}; s=0; j=0; echo "ITER: RSZ"; while [ $j -lt 6000 ] ; do j=$((j+1)); n=$(ps hwo rsz $p); printf "\e]2;%d: %d\e\\\\\r%4d: %d" $j $n $j $n; [ $s -ne $n ] && { echo; s=$n; }; done'
[exited]
$ cat /tmp/leaky-tmux-test.log ; echo
ITER: RSZ
   1: 3512
1993: 3568
3650: 3696
5279: 3824
6000: 3824
```

To compare, run it *without* `tmux set-option -w -g pane-border-status top`:
```
$ tmux -L none -f /dev/null new-session -s leaky-tmux-test 'tmux pipe-pane "cat>/tmp/leaky-tmux-test.log"; p=${TMUX#*,}; p=${p%,*}; s=0; j=0; echo "ITER: RSZ"; while [ $j -lt 6000 ] ; do j=$((j+1)); n=$(ps hwo rsz $p); printf "\e]2;%d: %d\e\\\\\r%4d: %d" $j $n $j $n; [ $s -ne $n ] && { echo; s=$n; }; done'
[exited]
$ cat /tmp/leaky-tmux-test.log ; echo
ITER: RSZ
   1: 3492
6000: 3492
```

**Comment by ThomasAdam** [comment]
Can you do likewise with logging enabled on the server tmux process (`-v`)
and attach the logs?

**Comment by altblue** [comment]
total 2.4M
2.3M [tmux-server-26634.log.xz](http://tmp.n0i.net/tmux-pane-border-status-leak-test/tmux-server-26634.log.xz)
4.0K [tmux-client-26632.log.xz](http://tmp.n0i.net/tmux-pane-border-status-leak-test/tmux-client-26632.log.xz)
8.0K [leaky-tmux-test.log.xz](http://tmp.n0i.net/tmux-pane-border-status-leak-test/leaky-tmux-test.log.xz)
4.0K [test.log](http://tmp.n0i.net/tmux-pane-border-status-leak-test/test.log)

**Comment by Ghosthree3** [comment]
Nice find, but I do not believe it is the cause of my issue personally, it's disabled by default right?

I originally thought that option was related to the bottom bar that contains the open windows etc. Which made me think, I use powerline, it could actually be this that's causing the leak? I will test with it disabled soon.

**Comment by altblue** [comment]
@Ghosthree3, I'm not sure why you believe I replied to your comment: `pane-border-status` is affecting issue reporter, check [his screenshot](#issue-275922571).

**Comment by Ghosthree3** [comment]
@altblue Oh my apologies, I didn't see the relevance to the snapshots in the OP (probably as I was unaware of what pane-border-status was). I thought you'd just found a leak that was potentially the problem and was merely replying to say it's not for me.

I'll stop hijacking this issue now since my problem is clearly unrelated (and probably caused by powerline as I mentioned it might be earlier).

**Comment by c02y** [comment]
I've been using tmux with all my old configurations except the `pane-border-status` for over 9 days, I believe @alblue is right.

Screenshot without `pane-border-status`: 
![asr4](https://user-images.githubusercontent.com/2135996/34034723-9803395a-e1ba-11e7-8d9f-3485ce8145a2.png)

**Comment by nicm** [comment]
Try this please:
~~~~
diff --git a/screen-redraw.c b/screen-redraw.c
index 7a31182a..1083642d 100644
--- a/screen-redraw.c
+++ b/screen-redraw.c
@@ -18,6 +18,7 @@
 
 #include <sys/types.h>
 
+#include <stdlib.h>
 #include <string.h>
 
 #include "tmux.h"
@@ -299,6 +300,7 @@ screen_redraw_make_pane_status(struct client *c, struct window *w,
 	screen_write_cnputs(&ctx, outlen, &gc, "%s", out);
 	screen_write_stop(&ctx);
 
+	free(out);
 	format_free(ft);
 
 	wp->status_size = outlen;

**Comment by c02y** [comment]
Sorry, I was testing the effect of this snippet, but recently my company forces us to power off our computers when we come off duty every day, and they will check that. So I'm not able to run the tmux for multiple days as I wanted. Maybe others people can test that.

**Comment by altblue** [comment]
@nicm's patch works for me: running previous test on a build patching current HEAD (e19df0e8) does _not_ exhibit previously observed behavior.

Tested on CentOS7, using [tmux-2.7-0.n0i.12.e19df0e8.20171225.git.el7.centos.x86_64.rpm](http://linux.reb00t.com/centos/7/extras/tmux-2.7-0.n0i.12.e19df0e8.20171225.git.el7.centos.x86_64.rpm) ([SRPM](http://linux.reb00t.com/SRPMS/extras/tmux-2.7-0.n0i.12.e19df0e8.20171225.git.el7.centos.src.rpm)):
```
$ tmux -v -L none -f /dev/null new-session -s leaky-tmux-test 'tmux set-option -w -g pane-border-status top; tmux pipe-pane "cat>leaky-tmux-test.log"; p=${TMUX#*,}; p=${p%,*}; s=0; j=0; echo "ITER: RSZ"; while [ $j -lt 6000 ] ; do j=$((j+1)); n=$(ps hwo rsz $p); printf "\e]2;%d: %d\e\\\\\r%4d: %d" $j $n $j $n; [ $s -ne $n ] && { echo; s=$n; }; done'; cat leaky-tmux-test.log
[exited]
ITER: RSZ
   1: 2068
  35: 2072
6000: 2072
```
Thanks Nicholas, merry Christmas! :santa:
