### ISSUE TITLE
Session list select issue

### ISSUE THREAD

**Issue by rikkipitt** [tmux/tmux#1168]
Hi folks,

When I choose a session from a list (prefix s), I can quickly select a numerical session by typing the digit 0 - 9 of the required session.

Once above 10 available sessions, to select the 11th+ session it says to use <M-a>, <M-b> etc... however, using `alt+a` on my setup doesn't work, it just sits there. Any ideas on why this might be?

Thanks!

Setup:

MacOS Sierra (10.12.6)
iTerm2 (Build 3.1.5.beta.2)

Darwin i386
tmux 2.6
xterm-256color

**Comment by nicm** [comment]
Did you reduce escape-time?

**Comment by rikkipitt** [comment]
Hi @nicm - quick reply, thanks!

Mine was set to `set-option -gs escape-time 2`

I've tried 0 and 10 to no avail...

**Comment by nicm** [comment]
What do you see if you run  cat then press M-a inside and outside tmux?

**Comment by rikkipitt** [comment]
In both instances, I see the `å` character.

**Comment by nicm** [comment]
Your terminal is configured to send Unicode characters for meta keys rather
than escape sequences, you will need to change it, or you can use eg Escape
then a instead of M-a.

**Comment by rikkipitt** [comment]
Thanks @nicm.

iTerm2 has an option to change the alt key mode. By default it's set to "Normal" but can be "Meta" or "Esc +". Setting to "Esc +" fixes this in my case. Cheers for the advice.

For future Googlers: iTerm2 > Preferences > Profiles > Keys:

<img width="303" alt="screen shot 2017-11-24 at 21 24 43" src="https://user-images.githubusercontent.com/1147871/33224140-382b6582-d15e-11e7-9142-bcfc5f701b04.png">
