### ISSUE TITLE
confusing 'split-window' parameters

### ISSUE THREAD

**Issue by keks24** [tmux/tmux#1170]
**Tmux version**
```bash
ramon@lenovo ~ % tmux -V
tmux 2.6
```

**Operating system**
```bash
ramon@lenovo /tmp % uname -mor
4.12.12-gentoo x86_64 GNU/Linux
```

**Description**
When using parameters to split windows, you use `-v` to split horizontally and `-h` to split vertically. They are interchanged.

**Steps to reproduce**
Use the following bash scripts to reproduce:
_split_horizontally.sh_
```bash
#!/bin/bash
tmux new-session -n "$(id -un)@$(hostname)" -d
tmux split-window -d -t 1 -v
tmux send-keys -t 0 "this is 'split_horizontally.sh' with 'split-window -v'"
tmux attach
```

_split_vertically.sh_
```bash
#!/bin/bash
tmux new-session -n "$(id -un)@$(hostname)" -d
tmux split-window -d -t 1 -h
tmux send-keys -t 0 "this is 'split_vertically.sh' with 'split-window -h'"
tmux attach
```

**Terminal**
Shell:
```bash
ramon@lenovo ~ % echo $SHELL
/bin/zsh
```

$TERM outside of tmux:
```bash
ramon@lenovo ~ % echo $TERM
xterm-256color
```
$TERM inside of tmux:
```bash
ramon@lenovo ~ % echo $TERM
screen-256color
```
**Logs**
No logs needed. :)

**Screenshots**
_split_horizontally.sh_
![split_horizontally sh](https://user-images.githubusercontent.com/13721064/33215500-5774448c-d130-11e7-953c-9348fa87f47d.png)

_split_vertically.sh_
![split_vertically sh](https://user-images.githubusercontent.com/13721064/33215501-578eec42-d130-11e7-89d9-8d9ed46f57b5.png)

**Comment by nicm** [comment]
They are fine thanks.
