### ISSUE TITLE
Future request: Two bars in Tmux

### ISSUE THREAD

**Issue by id777** [tmux/tmux#1171]
Hello! I have a lot of stuff in my tmux bar - windows, system info, time, user and host name, and so on. There is no enough space for everything.

So it would be super nice to have two bars as an option: one on bottom and second on top. Just like in MATE Desktop Environment for example.

**Comment by c02y** [comment]
There are two bars supported

top bar:
    
    set -g pane-border-status top

then

    set -g pane-border-format "..."

to set the info shown in top bar

the bottom bar consists of two parts, `status-left` and `status-right`

     set -g status-left "..."
     set -g status-right "..."

**Comment by id777** [comment]
@c02y 
Looks like you dont get what I'm talking about.

set -g pane-border-status top - this is pane border. This is NOT a bar. Each pane has border. But for now in window there is only one bar. At the very bottom. 
I want two bars. One at the bottom, and one at the top.

**Comment by c02y** [comment]
I know that the "set -g pane-border-status top" is not a bar like the bar at the bottom, I posted a similar issue #544 (not exact two bars but very similar) last year, the author said that it was impossible back then, after several months, I found that the "pane-border-status" was added into tmux, and I can just use it as the top bar, and you can configure "pane-border-format" variable and put some info in it, it is like bottom bar, except it contains one specific top bar for each pane.

**Comment by id777** [comment]
Thanks, I know, but it's not what I need.

**Comment by c02y** [comment]
https://github.com/tmux/tmux/issues/308

https://github.com/tmux/tmux/pull/303

**Comment by nicm** [comment]
It is unlikely we will have top and bottom status lines at the same time, might make it >1 in height at some point, it has been in TODO file for a while IIRC.
