### ISSUE TITLE
[Feature request] Please provide a pre-built AppImage package for download

### ISSUE THREAD

**Issue by KurtPfeifle** [tmux/tmux#1172]
> **User story:** As a `screen` user, I would like to have a quick+smooth access to the latest `tmux` release as a working binary that runs on my distros of choice, without a need to compile it myself from sources first (and doing this on every single distro again) so that I can thoroughly test it and do so very easily before I make the permanent switch to `tmux`.

On the latest Debian Stretch the official version of *`tmux`* available in the repos is v2.3-4. This is one year old. Hence, I cannot easily get access to your latest achievements.

I would love to see an *AppImage package* released by you guys, the tmux developers themselves.

AppImage packages are pre-compiled software binaries embedded into a single compressed file, and they are super-easy to handle, especially for testing purposes:

+ Implements the *"1 application == 1 file"* philosophy.
+ Can run directly (after making executable) after download.
+ Does not need an "installation" step.
+ Does not need root privileges.
+ Does not interfere with system package management tools, leaves system libraries un-touched.
+ Works on (almost) every single Linuxdistro in use, old and new.
+ Can be regarded as *PortableApp*-like package for Linux.
+ Works when started from USB flash storage, thumb drivers, shared network folders or even remotely mounted file systems like *`sshfs`*.
+ Is super-easy for users to remove again if this is wanted: just delete 1 file.
+ I could run it side-by side with my system-supplied tmux v2.3-4 without interference.
+ Can update to new releases via differential binary downloads (using "zsync2") which makes for faster and leaner downloads.

So for me as a user, I'd get the best of what I could imagine.

For you as developers you'd also win:

+ Faster feedback from users running the code.
+ Gain a certain independence from distro gatekeepers which are sometimes slower than you may wish for with integrating newer releases into their repos.
+ Have a release channel for binaries which is under YOUR control.
+ Make your support efforts more easy by being able to point users with problems to the AppImage version they should test.
+ Building of AppImage packages could be automatically achieved by integrating it into your Travis CI builds.
+ You could even go one step further and build a "continuous" AppImage for each Git commit that does not break the build.
+ "Build once -- run everywhere".

More infos about the AppImage project are to be found in their Wiki and in their GitHub repo:

* [How to create AppImages](https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages)
* [AppImage Eco System](https://github.com/AppImage/AppImageKit/wiki/Ecosystem)
* [AppImage Source Code](https://github.com/AppImage/AppImageKit)
* [AppImage Examples]()
* [AppImage comparison to Snap and FlatPak](https://github.com/AppImage/AppImageKit/wiki/Similar-projects)

NeoVim offers AppImage builds under their own control [from their GitHub release page](https://github.com/neovim/neovim/releases).
Direct link to download [*"nighly"* neovim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage).

**Would you be interested in this? Would you accept a pull request?**

I'm sure, the AppImage developers would lend a hand in putting the required additional steps into your `.travis.yml` file, or maybe even stitch together a fully working PR for you.

**Comment by ThomasAdam** [comment]
God no.

Compile tmux statically if you need to.

**Comment by id777** [comment]
AppImage sounds intresting. But even if no, do you know about checkinstall? It's much more better then make install.
Info: https://www.linux.com/learn/easy-package-creation-checkinstall

Here how you can install tmux from master using checkinstall:
```
sudo apt remove -q -y tmux
sudo apt install -q -y wget tar git libevent-dev libncurses-dev checkinstall

cd /tmp && git clone https://github.com/tmux/tmux.git
cd tmux/ && sudo sh autogen.sh
./configure && sudo make

#here in pkgversion you can point the current date for example and latest release version.
#Flag --install will auto install package to system.
sudo checkinstall --pkgname tmux --pkgversion latest-master --nodoc --install

tmux -V
```
Done. Wand to delete package? Easy, `sudo apt remove -q -y tmux`

**Comment by nicm** [comment]
Why don't you guys host these packages? Create a GitHub repo for them or
there is tons of other free hosting. If you do let me know and we can link
to them from the README.

**Comment by KurtPfeifle** [comment]
Just so you know:

* The idea of the AppImage guys is NOT to create and host AppImages *èn masse* all by themselves.
* They want to develop the tools which make the AppImages. 
* AppImages are meant to be a means for *upstream* developers to be in the driver seat themselves when it comes to distribute "original" binaries (and so they can get back some control over distribution channels, and free them from distro gatekeepers).

Users will likely quite "naturally" trust the creators of the source code themselves when it comes to running *binaries* -- after all, they have implicitely already decided to trust the source.

(If AppImage developers generate AppImages themselves, it is as a showcase only. They are not in the business of becoming distributors themselves.)

So, you don't want it. For whatever reason. That's fine. Maybe one day you'll change your mind...

**Comment by c02y** [comment]
pre-built AppImage is a good idea, since on some old servers, because of the dependencies I cannot compile or install the latest tmux easily, and my ~/.tmux.conf is for the latest version of tmux and somes lines are not working for old version of tmux.

If I can just use the latest version of tmux built as AppImage which contains all the dependencies, so I can just use that binary+~/.tmux.conf everywhere.

**Comment by KurtPfeifle** [comment]
@c02y: The issue is closed. The tmux maintainer even invoked a religious formula when closing it, so please give up all hope.

**Comment by c02y** [comment]
@KurtPfeifle It's been almost two years. Like you said "Maybe one day you'll change your mind."

**Comment by nicm** [comment]
Instead of making a script why not make and distribute the binary packages you want?

**Comment by nelsonenzo** [comment]
@c02y  @KurtPfeifle I created a Docker build of tmux AppImage, for Debian at least.  I put an AppImage in the release section for easy access, but if you don't trust my build you can pump one out for yourself by running the docker container.  
 https://github.com/nelsonenzo/tmux-appimage

@nicm would you still be willing to link my github in the readme?  It will probably be my dev highlight for all of 2020.  i :heart: tmux.

**Comment by nicm** [comment]
Why not do a build from the 3.0a tarball instead of a random checkout?

**Comment by nelsonenzo** [comment]
prefer to call it "edge" over "random" :smile: but you are right, that makes more sense.  I updated the code to checkout the release tag and build from there as well as updated the released AppImage.  Thank you.

**Comment by nicm** [comment]
Hi

Thanks for doing this.

I don't really want to link to build or install instructions for various
package systems in the README, there are too many. It is a nice idea for
new wiki page though - install/build instructions or links to instructions
for various platforms or package systems, then we could just link to that.

I'd like to link to your binary packages , but are you planning to support
them? There is already one person saying they don't work? Will you do one
for 3.1 when it is released?

**Comment by nicm** [comment]
> It is a nice idea for new wiki page though

Although saying that, is there any point in a page that says "on Debian, do apt-get install tmux; on CentOS, use yum install tmux" - surely for any Debian or CentOS user this is just stating the obvious. I can't think of any supported platform where this would really be necessary.

**Comment by nelsonenzo** [comment]
Hello @nicm .  Yes, I do plan to support the AppImage!  I fixed the reported issue and did more verification that AppImage works on a wider range of Linux distros (so far, at least Centos6.9, 7.7, Fedora 31, Ubuntu 18, and Debian 7 have been tested, I plan to do more).  I'll gladly create new releases for minor versions and I'll look into automation solutions as well (so your not reliant on me for updated AppImages in the future).

So far I have found 2 use cases for AppImages in the wild, even when packages are widely available on the normal distribution channels.
1) some admins are building "tool chests" that they clone from some cloud bucket or similar source in order to get their entire set of tools at once, thus avoiding having to install individual packages. 
2) Avoid cluttering production machines / vm builds with tools that may only be temporarily used or used by limited set of users.

I definitely concur with keeping readme's as simple as possible and the wiki is a better place, if at all.  No biggie if you don't feel it's a fit, you already do enough in maintaining tmux!

**Comment by nicm** [comment]
Well, why don't I attach the 3.0a AppImage file to the release, are you OK for me to do that? I take it is isn't likely to change often? You can email me or open an issue when there is a new build, or I can open an issue on your project.

tmux doesn't have many releases, it has a release every six months and occasionally a patch release on top of that. Only the most recent release is supported.

If you want to do automated builds or builds from master then go for it but I don't do anything like that at the moment.

I'm going to write a build instructions wiki page and I will link your repo from it in any case.

**Comment by nicm** [comment]
I have added an installing page here https://github.com/tmux/tmux/wiki/Installing.

**Comment by nelsonenzo** [comment]
Sweet!  Awesome.  I have no problem with attaching the AppImage file to your release. Happy to be a contributor to Tmux, one of my long time favourite utilities :)

**Comment by nicm** [comment]
I have added this to the 3.0a release now https://github.com/tmux/tmux/releases/tag/3.0a.
