### ISSUE TITLE
Error with send-keys: "usage: send-keys [-lRM] [-t target-pane] key ..."

### ISSUE THREAD

**Issue by tiagopog** [tmux/tmux#1173]
### Platform

macOS High Sierra 10.13.1

### Brief description of the problem

After updating my OS to High Sierra and tmux to 2.6 all vim key bindings stop working inside tmux sessions. When I try to source the config file I got a couple of errors referring to the syntax of `send-keys`.

So it seems like `send-keys` is no longer accepting the `-X` flat and it's unclear how one should proceed to migrate from the old syntax to the new one, if that's the case.

### Steps to reproduce

```
$ tmux source-file ~/.tmux.conf
usage: send-keys [-lRM] [-t target-pane] key ...
usage: send-keys [-lRM] [-t target-pane] key ...
usage: send-keys [-lRM] [-t target-pane] key ...
usage: send-keys [-lRM] [-t target-pane] key ...
usage: send-keys [-lRM] [-t target-pane] key ...
usage: send-keys [-lRM] [-t target-pane] key ...
usage: send-keys [-lRM] [-t target-pane] key ...
usage: send-keys [-lRM] [-t target-pane] key ...
```

### Minimal tmux config

Errors are related to the following lines of the config file – only the ones containing the `-X` flag. If lines are commented or `-X` is replaced by anyone of those other flags shown above then it seems to source the file properly but the vim key bindings still don't work.

```
# Deal with history in the edit mode
bind-key -T edit-mode-vi Up send-keys -X history-up

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe "reattach-to-user-namespace pbcopy"

# Setup 'v' to begin selection and y to yank it as in Vim
unbind-key -T copy-mode-vi Space     ;   bind-key -T copy-mode-vi v send-keys -X begin-selection
unbind-key -T copy-mode-vi Enter     ;   bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Copy and paste within tmux using vi-style bind-keyings
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
```

### Terminal, and $TERM inside and outside of tmux;

Outside:

```
$ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.6
xterm-256color
```
Inside:

```
$ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.6
screen-256color
```

### Tmux version

```
$ brew info tmux
tmux: stable 2.6 (bottled), HEAD
Terminal multiplexer
https://tmux.github.io/
/usr/local/Cellar/tmux/2.6 (10 files, 688.6KB) *
  Poured from bottle on 2017-11-27 at 19:25:17
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tmux.rb
==> Dependencies
Build: pkg-config ✔
Required: libevent ✔
Optional: utf8proc ✘
==> Options
--with-utf8proc
        Build with utf8proc support
--HEAD
        Install HEAD version
==> Caveats
Example configuration has been installed to:
  /usr/local/opt/tmux/share/tmux

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
```

**Comment by tiagopog** [comment]
FYK I've downgraded to 2.4 and it's got fixed. I'm still not sure about what happened with the 2.6 one but I will stick with this older version for now.

**Comment by nicm** [comment]
You are doing something weird because 2.4 does not support -X and 2.6 does.

**Comment by tiagopog** [comment]
As far as I know the [2.4 do accept](https://shapeshed.com/custom-vim-bindings-in-tmux-2-4/) the `-X` flag. Actually, It's been a while since I've change that old syntax (eg. `bind-key -t vi-copy v begin-selection;`) to the new one (eg. `bind-key -T copy-mode-vi v send-keys -X begin-selection`) and it was working just fine in the 2.4 version. It has only started to get issues after updating the macOS to High Sierra + the bump up of tmux's version to 2.6.

**Comment by nicm** [comment]
Well in any case this has not changed in 2.6. Please show logs from running
tmux with your config file where it fails.

**Comment by tiagopog** [comment]
https://gist.github.com/tiagopog/062e8a3e86641363d515b1471bd8f524

**Comment by nicm** [comment]
This log is incomplete.

**Comment by nicm** [comment]
Also, it is no use loading /dev/null when the problem is with the commands
in your config file...

On 28 November 2017 at 19:13, Nicholas Marriott <nicholas.marriott@gmail.com

**Comment by tiagopog** [comment]
Well, I just followed the steps from the [contributing guideline](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING).

Any suggestions on how to proceed and log exactly what you need?

**Comment by nicm** [comment]
Just point -f to your config file not /dev/null
