### ISSUE TITLE
unsuccessful compiling with gcc 

### ISSUE THREAD

**Issue by bjoernbroetz** [tmux/tmux#1176]
Using the master at 2c6af068 (most recent when I cloned it) I encountered a failing make. My gcc complained about an: 
`cc1: error: unrecognized command line option "-Wno-unused-result"` 
Manually changing this to `-Wno-unused-value` led to a successful build.

My machine is running a SUSE Linux x86_64.
gcc --version 
gcc (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]

**Comment by nicm** [comment]
Make output and config.log please.

**Comment by bjoernbroetz** [comment]
Here are the log files:
[config.log](https://github.com/tmux/tmux/files/1567154/config.log.txt)
[make.log](https://github.com/tmux/tmux/files/1567155/make.log.txt)

**Comment by nicm** [comment]
If you configure tmux with --disable-debug it will not include the -W flags.

I don't think it is worth playing games to try and support gcc where unknown -W are an error.
