### ISSUE TITLE
Feature request: ls formatting by default

### ISSUE THREAD

**Issue by sinnlosername** [tmux/tmux#1177]
Hei!

Currently the `tmux ls` commands looks like:

```
asession: 1 windows (created Wed Nov 29 23:19:28 2017) [138x52]
another: 1 windows (created Wed Nov 29 23:13:08 2017) [138x52]
1more: 1 windows (created Wed Nov 29 23:50:39 2017) [138x52]
```

This is very difficult to read if you got many different sessions. Also "1 windows" doesn't sound correct. Could you add some tabs like:

```
asession:  1 window(s)  (created Wed Nov 29 23:19:28 2017)  [138x52]
another:   1 window(s)  (created Wed Nov 29 23:13:08 2017)  [138x52]
1more:     1 window(s)  (created Wed Nov 29 23:50:39 2017)  [138x52]
```

**Comment by nicm** [comment]
You can make it show whatever you like with -F.

**Comment by sinnlosername** [comment]
@nicm I know, but I don't want to but it's annoying to put a -F there all the time. :/

**Comment by ThomasAdam** [comment]
There's a TODO item to make formats have things like quoting, etc.  The idea of `%.s` type formatting would naturally fall into this.
