### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by Ovid** [tmux/tmux#1179]
I'm using tmux 2.5.

Open source authors often don't get enough thanks, so I just want to say "thank you" to everyone who has contributed to tmux. You've made my life much easier.

(Yeah, I know this isn't what tickets are generally for, so I hope you don't mind)

**Comment by mischapeters** [comment]
I have the same issue.

**Comment by nicm** [comment]
Thanks

**Comment by jungle-boogie** [comment]
This should be re-opened so we're reminded of how great tmux is. 

Thanks for ten great years of tmux!
