### ISSUE TITLE
if-shell have different behavior between Mac and Ubuntu

### ISSUE THREAD

**Issue by cmaohuang** [tmux/tmux#118]
I use brew to install tmux 2 on my Mac, and use ppa:pi-rho/dev to install tmux 2 on my Ubuntu. (I have build source on Ubuntu, but the same behavior)

In my ~/.tmux.conf, I would like to git clone [tpm](https://github.com/tmux-plugins/tpm) at the first time if the tpm folder doesn't exist, but it always failed on my Ubuntu machine but work on my Mac.

I wrote the same config on Mac and Ubuntu as below:

```
if-shell "[[ ! -d ~/.tmux/plugins/tpm ]]" 'run-shell "echo True:$? > result"' 'run-shell "echo False:$? > result"'
```

On my Mac, the result file contain
```
True:0
```

But on my Ubuntu, the result file contain
```
False:0
```

Could anyone give me some advice, do I misconfigure anything?

**Comment by nicm** [comment]
If you run:
    sh -c '[[ ! -d ~/.tmux/plugins/tpm ]]; echo $?'

In your shell is it the same on both platforms

**Comment by cmaohuang** [comment]
Thank you @nicm . Now I know where is the problem.

On Ubuntu
```sh
james@ubuntu:~$ sh -c '[[ ! -d ~/.tmux/plugins/tpm ]]; echo $?'
sh: 1: [[: not found
127
james@ubuntu:~$ bash -c '[[ ! -d ~/.tmux/plugins/tpm ]]; echo $?'
0
```
On Mac
```
james@mac:~$ sh -c '[[ ! -d ~/.tmux/plugins/tpm ]]; echo $?'
0
```
So I change it to this and have the same behavior.
```
if-shell "[ ! -d ~/.tmux/plugins/tpm ]" 'run-shell "echo True:$? > result"' 'run-shell "echo False:$? > result"'
```
