### ISSUE TITLE
fature require:I want display a file which contained Escape Sequences for the occasion

### ISSUE THREAD

**Issue by qdzhaov** [tmux/tmux#1180]
I tried:
 `run "cat file"'        ,display in copymode,but not surport Escape Sequences.
 neww less file       ,display  in new window for the occasion,but not surport Escape Sequences.
 neww more file       ,display  in new window ,I can't saw it;
neww 'more file;read'    ,display  in new window ,nearly sucessed,but it returned only by \<CR\>

**Comment by qdzhaov** [comment]
I change file screen-write.c,line 272:
                        else if (*ptr > 0x1f && *ptr < 0x7f) {
==>
                        else if (*ptr >= 0x1b && *ptr < 0x7f) {
make copy mode suport  Escape Sequences,but I donot know it have other side-effects.
so I can use `run "cat file"' ,display colored text file in copymode.

**Comment by nicm** [comment]
Copy mode should use the colours NS attributes currently in the pane, except for the selection.

**Comment by nicm** [comment]
Colours and attributes that is.

**Comment by qdzhaov** [comment]
where can found the discribe of NS attributes

**Comment by qdzhaov** [comment]
do you mean like this:
#[fg=blue] s #[default]session list
but it not work
I tested:
: run 'echo "#[fg=blue] s #[default]session list"'

**Comment by nicm** [comment]
I don't understand what you are trying to do.

If you have a file like:

\033[33;1mfoo\033[0m\n

Then you cat it at the shell prompt, you should see foo in yellow and bold.

Then if you enter copy mode with C-b [ you will still see the same colour and attributes.

You need to describe what you are trying to do better.

**Comment by qdzhaov** [comment]
The inline help with C-b ? ,is too complexity ,I want a Help message like gnu screen with C-a ?,

**Comment by nicm** [comment]
You want to show colours in the output from run-shell or similar.

You can't do this, you should just use new-window or split-window and show it in a new window or pane.
