### ISSUE TITLE
can it surport GBK/CP936 mode

### ISSUE THREAD

**Issue by qdzhaov** [tmux/tmux#1181]
I most file in GBK mode,so int utf-8 mode ,I cannot display it use cat,more less etc.
Can it surport GBK mode.

**Comment by c02y** [comment]
This is not the problem of `tmux`, or the problem of your terminal, but the problem of your files which may be edited in Windows. (Just try to view the file using `cat`, `more` or `less` without tmux, you 'll see the same result.) 

So, blame MS please.

If you want to edit or view such files, using vim with a little configuration:

put the following lines into your .vimrc

      set encoding=utf8
      set fileencodings=utf8,gb2312,gb18030,ucs-bom,latin1

I've been using these lines for years, nothing goes wrong. There exists other ways, but for me, this is the simplest one to edit or view those files.

BTW: 
I know your monther language is not Engligh, please at least learn some basic grammer.

**Comment by nicm** [comment]
tmux only supports UTF-8, sorry.

**Comment by ThomasDickey** [comment]
Supposedly [luit](https://invisible-island.net/luit/) supports GBK, but that in turn depends upon having the command-line utilities work in that locale (I've not seen that).
