### ISSUE TITLE
Detached sessions clear window_bell_flag in 'active' window

### ISSUE THREAD

**Issue by natebosch** [tmux/tmux#1182]
In old versions of tmux (at least `2.0`) if there was a bell in a detached session the `window_bell_flag` would still be set and could be seen with the `!` in `tmux list-windows`. In later versions (I tried `2.2`, `2.6`, and `master`) the `window_bell_flag` is kept for inactive windows, but lost for the active window.

Repro steps:
- `tmux new`
- Run `sleep 1s; print -n '\a'` to get a bell
- `<c-b>d` to detach before the second is up.
- `tmux list-windows`

Expected (behavior in `2.0`): 
`0: zsh!* (1 panes) [135x61] [layout b5bd,135x61,0,0,0] @0 (active)`

Actual (behavior at `master`):
`0: zsh* (1 panes) [135x61] [layout b5bd,135x61,0,0,0] @0 (active)`

The flag for inactive windows isn't cleared. I can still get:
```
0: zsh* (1 panes) [135x61] [layout b5bd,135x61,0,0,0] @0 (active)
1: zsh!- (1 panes) [135x61] [layout b5be,135x61,0,0,1] @1
```

System details:
Reproduced with no `.tmux.conf`
```
$ uname -sp
Linux x86_64
$ echo $TERM
xterm-256color
$ echo $TERM # while in tmux
screen
```

**Comment by ThomasAdam** [comment]
Try the following diff.  We've been round this loop before in terms of bell behaviour and current window, etc.  Does this patch do what you want?

[x.diff.txt](https://github.com/tmux/tmux/files/1538998/x.diff.txt)

**Comment by natebosch** [comment]
This patch does have correct behavior when the session is detached, but changes behavior when the session is attached.

In `2.0` the flag would not be present if the session was attached and the window was active. With this patch I need to manually clear it by switching windows and back, or with `kill-session -C` in order to change the styling back to default.

**Comment by ThomasAdam** [comment]
Hi,

Yes, I am aware of the difference and hence think this is perhaps better
behaviour. There's any number of ways to still clear the flag, including
hooks.

**Comment by natebosch** [comment]
Sounds good. I'd be fine with finding another way to clear the flag myself.

**Comment by nicm** [comment]
I don't think bells should highlight the current window in the status line if I am actually looking at it and I think we should be prepared to sacrifice having the flag set correctly for formats so that it doesn't.

The best we could do is set the flag for the current window if the session is unattached.

**Comment by nicm** [comment]
Or add an additional state to bell-action and friends.

**Comment by natebosch** [comment]
> The best we could do is set the flag for the current window if the session is unattached.

That would be fine with me as well.

**Comment by nicm** [comment]
I think this will do it [a.diff.txt](https://github.com/tmux/tmux/files/1824657/a.diff.txt)
