### ISSUE TITLE
bug&fix:In Cygwin:work directory is no effect.

### ISSUE THREAD

**Issue by qdzhaov** [tmux/tmux#1183]
CYGWIN_NT-6.1 unknown
tmux 2.6
xterm-256color
      -------------------------
work directory is no effect,
all new window&new pane start at home Directory.
      -------------------------
I fixed it,it will work OK,but I don't know if I have any side effects .
fixit : window.c 996,998
=======begin
           xasprintf(&argv0, "-%s", ptr + 1);
    else
           xasprintf(&argv0, "-%s", wp->shell);
==>change to
           xasprintf(&argv0, "%s", ptr + 1);
    else
           xasprintf(&argv0, "%s", wp->shell);
=========End

**Comment by qdzhaov** [comment]
And  for fiendly linked dir,
fixed it:
diff tmux.c ../tmux-master_b/tmux.c
196c196
<     const char *cwd;
---
>
297,303c297,298
<     if((cwd=getenv("PWD"))==NULL){
<               if((cwd=getcwd(tmp,sizeof tmp))==NULL){
<                       cwd=".";
<               }
<       }
<       environ_set(global_environ, "PWD", "%s", cwd);
<
---
>       if (getcwd(tmp, sizeof tmp) != NULL)
>               environ_set(global_environ, "PWD", "%s", tmp);
=================
diff client.c ../tmux-master_b/client.c
281,285c281,284
<     if ((cwd=getenv("PWD"))==NULL){
<         if ((cwd = getcwd(path, sizeof path)) == NULL) {
<                   if ((cwd = find_home()) == NULL)cwd = "/";
<         }
<     }
---
>       if ((cwd = getcwd(path, sizeof path)) == NULL) {
>               if ((cwd = find_home()) == NULL)
>                       cwd = "/";
>       }

**Comment by nicm** [comment]
The leading - is required for login shells. But I don't understand the issue, can you explain what is happening again?

**Comment by qdzhaov** [comment]
in CYGWIN,
start tmux at any directory,the work directory be $HOME,
other system is OK.
~/work $ tmux 
in new window
I expect : ~/work $
but it is : ~ $
------------------------------------------------------
second error is  in any system:
~ $ ln -s  /WORK/zhw work
~ $ cd work
~/work $ pwd 
/home/zhw/work
~/work $ tmux
I expect: 
~/work $ pwd
/home/zhw/work
bu it is: 
/WORK/zhw $ pwd
/WORK/zhw

**Comment by nicm** [comment]
Oh so you are saying we should check PWD in tmux.c as well as in window.c? Can you send your change again as a unified diff (diff -u)?

**Comment by qdzhaov** [comment]
window.c for cygwin only
tmux.c client.c for work in symbol linked directory 
[pat.txt](https://github.com/tmux/tmux/files/1581081/pat.txt)

**Comment by nicm** [comment]
OK sorry for the delay.

In tmux.c and client.c, you want to prefer PWD over getcwd(). That's fine, I will change that.

In window.c: when we create a login shell we want a leading -, but when we run /bin/sh -c we do not (it is not a login shell). So I won't change this.

**Comment by qdzhaov** [comment]
OK,thanks
