### ISSUE TITLE
send-keys commands are sporadically dropped

### ISSUE THREAD

**Issue by yaroslavvb** [tmux/tmux#1185]
When large volume of stuff is being printed into tmux window, `tmux send-keys` commands to that window get sporadically ignored.

IE, my script rapidly executes a series of 20-30 commands like
`tmux send-keys 'sudo apt-get install emacs24'`
`tmux send-keys 'sudo apt-get install tensorflow'`
etc.

Sometimes these `sudo apt-get` just don't appear in the tmux window. Rerunning the script gets a little bit further, so I suspect messages are being dropped because the `apt-get install xyz` command generates large volume of output the first time it's run

You can theoretically reproduce it by following instructions in https://github.com/yaroslavvb/tf_build
Sorry for not following guidelines in [contrib](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING), as a small example would take some effort given nature of bug. Before spending this effort I wanted to know if it's something that may be feasible to fix (ie, perhaps tmux architecture makes this kind of use case hard to support)

**Comment by kkovacs** [comment]
Hi Yaroslav, actually, IMHO your problem would *also* be best solved by the same feature I'm hoping for :) The two-way process communication, and `expect`-like scipts, so you can wait for the output of one command before the next one is being sent. Nice job on tf_build, by the way!

**Comment by yaroslavvb** [comment]
Ah, that's true. Right now my work-around is to insert "time.sleep(5)" after each command and hope it finishes in 5 seconds, I think ability to block until command finishes would be a better work-around

**Comment by nicm** [comment]
Are you sure the application inside the pane is not throwing away the input?

**Comment by yaroslavvb** [comment]
Oh.....good observation. Now to think of it, the following two blocks are not identical because tmux will send the second set of keys to `apt-get` process rather than `bash` process.  Now I wonder if there's a way to make this work in tmux

```
sudo apt-get install emacs24
sudo apt-get install tensorflow

tmux send-keys mine:0 'sudo apt-get install emacs24'
tmux send-keys mine:0 'sudo apt-get install tensorflow'
```

**Comment by nicm** [comment]
Well it depends if apt-get is actually eating the input or not. If it isn't, it could be a tmux bug.

If it is, you may need to be more sophisticated and make the outer script wait for the apt-get to finish (either with ps/pgrep or eg tmux wait-for).

**Comment by nicm** [comment]
For this case why can't you just install everything with one apt-get command?

**Comment by yaroslavvb** [comment]
because after `apt-get`, I'm doing `pip install ...`, scp'ing some files from local machine to the machine where tmux is running, and then running `python run_my_script.py` in the same tmux window. If there's no way to do 'expect-like' workflow through tmux I would need to refactor my setup pipeline

**Comment by yaroslavvb** [comment]
ok, wait-for may be what I need, thanks for the tip

**Comment by nicm** [comment]
You will need to loop around capture-pane, or use some form of synchronization (ps/pgrep, wait-for, lock files).

**Comment by yaroslavvb** [comment]
ok, I'll close this bug now and will reopen if I can definitely confirm that apt-get is not discarding the output
