### ISSUE TITLE
Problem in copy-mode when using ssh remote login

### ISSUE THREAD

**Issue by sixshotx** [tmux/tmux#1188]
I am currently using tmux-2.6 on a remote server and ssh to it from my local machine. I have set up a copy-mode shortcut in the vi mode, which intends to copy my selection and put it to the X11 clipboard using xsel.
`bind-key -Tcopy-mode-vi y send -X copy-pipe-and-cancel "xsel -ib"`

However, this does not work inside tmux from my end, although copying through _shift+mouse click_  is fine with the system clipboard in remote tmux sessions. I have tried to use `echo "hello" |  xsel -ib` with no problem so X11 forwarding is OK.  I also confirm the keybinding works in my local tmux session. 

Any hints? Thanks in advance.

**Comment by nicm** [comment]
Are you sure DISPLAY is correct in the session options? Check "tmux showenv DISPLAY" in the session you are copying from.

**Comment by sixshotx** [comment]
Yes. I created a completely new session with the same DISPLAY environment variable and copy-paste works fine there. However, when I switched back to the existing session, copy-paste is not working. Weird from my end.

**Comment by nicm** [comment]
So you can't reproduce if you restart tmux?
