### ISSUE TITLE
tmux cannot select text using mouse when ssh

### ISSUE THREAD

**Issue by bzvew** [tmux/tmux#1189]
I use osx 10.12.6. When I ssh to a linux server, and run tmux on that server, my mouse cannot select text. That server uses tmux 1.6

On my mac, I use tmux 2.6, the mouse select is perfect.

**Comment by nicm** [comment]
1.6 is too old, you need to upgrade.

**Comment by bzvew** [comment]
I update the tmux on centos to 2.6, and I use ssh to connect to centos from osx 10.12. When I set set -g mouse on, I can mouse scroll for content(not for shell history), but I cannot select text, because when I release mouse, the selected text automatically get unselected. If I do not use set -g mouse on, I can select text, but I can only mouse scroll for shell history(not for content). How to enable mouse select and I can also scroll for content?
