### ISSUE TITLE
Bindings with -n Alt (bind -n M-) sometimes didn't work

### ISSUE THREAD

**Issue by id777** [tmux/tmux#1190]
I have keybindings with Alt key using -n mode. For example:
```
bind -n M-, previous-window
bind -n M-. next-window
bind -n M-z resize-pane -Z
```
And it seems like sometimes these keybindings didn't work, like Alt key not pressed, for example here:
`bind -n M-, previous-window` sometimes just typing `,` instead of action previous-window.
It has random format, for example 5 times all is ok, but on 6-7 times it happens, then again everything is ok.

I don't know what the problem, all others keysbindings works well, this problem happens only with Alt in -n mode.

---
Linux x86_64
tmux 2.6
screen-256color

**Comment by nicm** [comment]
Please show logs of reproducing this and also describe what you did so I can find it in the logs.

**Comment by id777** [comment]
I found what it's not a Tmux problem. Same thing (Alt+key) happend outside of tmux as well.

**Comment by doubleloop** [comment]
@id777 did you found the root cause of the issue? I have the same problem and it is very annoying when this happens (I use alt+hjkl for pane navigation). Did not observe it outside tmux but I do not use alt outside tmux.
