### ISSUE TITLE
Tmux title not updated on first event, only on second

### ISSUE THREAD

**Issue by ondrejj** [tmux/tmux#1191]
When an bell is triggered in a tmux window, tmux should mark it in title. This works for 2nd event, but not for first, or works for first too, but I have to press many keys or switch to another tmux window.
I think this worked well with tmux stable, but tmux-git is much better.

You can try to open new window and run this command:
  sleep 3s; ping -c 1 -a localhost
  -a is audible ping, -c 1 is for only one ping. If you change it to -c 2, then it works, but only on 2nd bell.

After running this command, switch to another window in 3 seconds (or change sleep value).

Here is my minimal configuration:
set -g status off
set -g set-titles on
set -g set-titles-string "#I:#W - #T #{session_alerts}"
set -g bell-action other
set -g status-interval 1
set -g monitor-bell on

It's better, if I set alert-bell to display-message, but I don't need this message, only information in window title.

Using tmux latest git on Fedora Linux.

**Comment by nicm** [comment]
Yes, I see. Title is set when status or window is redrawn, but without a status line there is nothing to make this happen. Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1589141/x.diff.txt)

**Comment by nicm** [comment]
That has some unrelated bits in it, this one is just the change: [y.diff.txt](https://github.com/tmux/tmux/files/1589143/y.diff.txt)

**Comment by ondrejj** [comment]
This latest patch (y) works well. Thank you.
Can you please apply to master branch?

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
