### ISSUE TITLE
kill-pane by title is not working

### ISSUE THREAD

**Issue by gerardbm** [tmux/tmux#1192]
The command `kill-pane -t <name>` is not working.

Steps to reproduce:
1. Split the window: 
`split-window -h`
2. Rename it using the new `-T` flag (C-b :)
`select-pane -T helloworld`
3. Try to kill it: 
`kill-pane -t helloworld`

It returns: `Can't find pane helloworld`.

Using tmux -V 2.6-1 on Debian 9 stable, i3wm and the terminal URxvt (tmux installed from sid via apt-pinning). My $TERM variable is `screen-256color` inside and outside of tmux, however steps are reproduced as well using `tmux -vv -Ltest -f/dev/null new` (so without config, where $TERM is `screen`).

**Comment by nicm** [comment]
-t is not title.

**Comment by gerardbm** [comment]
Is not `-t` used to target? (In this case: `target-pane`).

About tmux windows we can do: `rename-window hello` and `kill-window -t hello`; then it would be coherent to do the same with tmux panes.

PS: I know the difference between `-t` and `-T`, thanks.

**Comment by nicm** [comment]
No pane titles are not used for target.
