### ISSUE TITLE
Feature request: selection_active_flag

### ISSUE THREAD

**Issue by ivanbrennan** [tmux/tmux#1193]
Similar to variables like `window_zoomed_flag`, it would be useful if Tmux exposed a flag indicating whether any text is currently selected in copy-mode. I guess it would be per pane, so maybe `pane_selection_active_flag` is a better name.

I'd find this very useful because I use vi keybindings in copy-mode and would like to make <kbd>Esc</kbd> clear the current selection if there is one, or exit copy-mode if nothing was selected.

```
bind -T copy-mode-vi Escape if-shell -F '#{pane_selection_active_flag}' \
                                        'send-keys -X clear-selection' \
                                        'send-keys -X cancel'
```

**Comment by nicm** [comment]
Like selection_present?

**Comment by ivanbrennan** [comment]
@nicm Yes, exactly that! Sorry, I seem to have an outdated man page, as my tmux supports `selection_present` (and it does exactly what I wanted) but the man page doesn't mention it. Sorry, I'll close this issue.
