### ISSUE TITLE
Patch to preserve highlighting when scrolling in vi-copy-mode

### ISSUE THREAD

**Issue by ericpruitt** [tmux/tmux#1194]
I'm providing a patch* that implements the change requested in [issue #950](https://github.com/tmux/tmux/issues/950#issuecomment-346182185) to keep highlighted text when scrolling when using Vi bindings for copy mode: [tmux-src-bd71cbb-preserve-search-with-vi-mode-motions.txt](https://github.com/tmux/tmux/files/1565355/tmux-src-bd71cbb-preserve-search-with-vi-mode-motions.txt).

\* In my comment on the original issue, I wrote that I would open a pull request, but I meant to write that I would open a new issue. The patch doesn't update the man page since I wrote the patch for myself without assuming it'd be accepted upstream.

**Comment by ericpruitt** [comment]
@nicm, thoughts?

**Comment by id777** [comment]
Thanks! Pretty awesome, I found default behavior when selected results gone if I scroll or move cursor not useful. With this patch it will be much more better.

Selection with results still will be dissapear when pressing ESC?

**Comment by ericpruitt** [comment]
> Selection with results still will be dissapear when pressing ESC?

Yes.

**Comment by ericpruitt** [comment]
> > Selection with results still will be dissapear when pressing ESC?
>
> Yes.

More specifically, the selection will disappear **if** you have it mapped to "clear-selection" -- the default binding.

**Comment by nicm** [comment]
Hmm. I don't like having a big list of motion commands in window_copy_command. Not sure what to do instead.

Also I think it is better to check for vi by checking mode-keys, not checking the key table name.

**Comment by nicm** [comment]
Yes I think that would be better.

**Comment by ericpruitt** [comment]
If I update the patch accordingly, are you going to accept it? My original version of the patch has the benefit of being less likely to cause merge conflicts, and I'm not interested in updating the patch just to have it ignored.

**Comment by balta2ar** [comment]
It's inconvenient that highlighting disappears when scrolling so I really hoped this patch would get merged.

**Comment by nicm** [comment]
I have not had time to look at this again yet.



On 28 Jan 2018 8:59 am, "Yuri Bochkarev" <notifications@github.com> wrote:

It's inconvenient that highlighting disappears when scrolling so I really
hoped this patch would get merged.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1194#issuecomment-361047936>, or mute
the thread

**Comment by calincru** [comment]
@ericpruitt any updates on this? It would be really useful.

**Comment by ericpruitt** [comment]
@calincru I don't understand why you're asking me for updates. I closed this issue because it due to the lack of responsiveness nicm. You're free to open an issue yourself and update the patch to suit nicm's preferences, but I have no intention of doing that.

**Comment by cangermueller** [comment]
The problem still exists and it would be great if the dispute got resolved. @nicm, can you merge the pull request?

**Comment by nicm** [comment]
I will look at this again when there is something new to look at.

**Comment by ericpruitt** [comment]
> @ericpruitt @nicm would it be helpful if a PR was made (instead of a text patch)? I desire this functionality as well.

Please read these messages and don't drag me into this discussion again:
- https://github.com/tmux/tmux/issues/1194#issuecomment-357311893
- https://github.com/tmux/tmux/issues/1194#issuecomment-357453355
- https://github.com/tmux/tmux/issues/1194#issuecomment-357460535
- https://github.com/tmux/tmux/issues/1194#issuecomment-372048833

My proposed alternative implementation is outlined well enough for someone else to do it if the maintainer if actually willing to accept the change. In the meantime, I'm personally content maintaining my original version of the patch.

**Comment by unphased** [comment]
I hear ya. I was mainly asking if I have your permission to take the changes that you authored and outlined, and creating a pull request for it, in hopes that it may then be accepted. Thanks.

**Comment by ericpruitt** [comment]
> I hear ya. I was mainly asking if I have your permission to take the changes that you authored and outlined, and creating a pull request for it, in hopes that it may then be accepted.

Yes, that's fine by me. My most recent version of the patch can be found at <https://github.com/ericpruitt/emus/blob/master/core/patches/tmux-src-preserve-search-with-vi-mode-motions.patch>. It may be missing some keywords. The repository that the file originally came from had a note stating that all patches for the various programs are licensed under the licensed used by the original application, but I just noticed I didn't include that message in the current README.md. I'll fix that, but in the mean time, consider the patch the in the public domain or BSD licensed; whichever works for you.

**Comment by ericpruitt** [comment]
Due to changes in tmux since I originally wrote this patch, I wound having to rewrite my patch in a manner similar to what I proposed in https://github.com/tmux/tmux/issues/1194#issuecomment-357311893. I have opened https://github.com/tmux/tmux/pull/1985.

**Comment by unphased** [comment]
#1985 is in! :tada:

**Comment by unphased** [comment]
Confirmed this feature is working whether i use vi-mode motions or mouse wheel.
