### ISSUE TITLE
bind-key: support for multiple tables

### ISSUE THREAD

**Issue by blueyed** [tmux/tmux#1195]
It would be nice if the bind-key command would support setting the binding on multiple tables at once.

I've tried `-T root,copy-mode`, but that appears to use the "root,copy-mode" literally for the table name.
With `-T root -T copy-mode` only the last entry (`copy-mode`) is used.

This is useful in case you want to use the same binding in multiple/all modes.

**Comment by ThomasAdam** [comment]
We don't support this anywhere else, and there's any number of arguments to be made where we could (for instance:  `tmux neww -tsession1,session2`).  I fail to see why the mode tables are special in this regard, and I very much doubt you're going to be switching between two tables that frequently, such that the additional line(s) in your configuration are a problem.

**Comment by blueyed** [comment]
Fair enough, closing.
