### ISSUE TITLE
Can't upgrade tmux

### ISSUE THREAD

**Issue by RomaniukAS** [tmux/tmux#1196]
Hi,
when I try upgrade tmux, I got this:

mv -f $depbase.Tpo $depbase.Po
depbase=`echo tty-term.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"master\" -DPACKAGE_STRING=\"tmux\ master\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"master\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_PRCTL=1 -DHAVE_SYSCONF=1 -DHAVE_ASPRINTF=1 -DHAVE_CFMAKERAW=1 -DHAVE_MEMMEM=1 -DHAVE_SETENV=1 -DHAVE_STRCASESTR=1 -DHAVE_STRNDUP=1 -DHAVE_STRSEP=1 -DHAVE_NCURSES_H=1 -DHAVE_B64_NTOP=1 -DHAVE_DAEMON=1 -DHAVE_FORKPTY=1 -DHAVE___PROGNAME=1 -DHAVE_PROGRAM_INVOCATION_SHORT_NAME=1 -DHAVE_PR_SET_NAME=1 -DHAVE_PROC_PID=1 -I.  -DTMUX_CONF="\"/etc/tmux.conf\"" -DDEBUG -iquote.      -D_GNU_SOURCE   -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes -Wno-unused-result   -MT tty-term.o -MD -MP -MF $depbase.Tpo -c -o tty-term.o tty-term.c &&\
mv -f $depbase.Tpo $depbase.Po
tty-term.c:24:21: fatal error: ncurses.h: No such file or directory
compilation terminated.
Makefile:811: recipe for target 'tty-term.o' failed
make: *** [tty-term.o] Error 1

can you help me to solve it?

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by RomaniukAS** [comment]
1. Platform Ubuntu 16.04
2. 2.1 When I start update tmux with this commands (
	**$ git clone https://github.com/tmux/tmux.git
	$ cd tmux
	$ sh autogen.sh
	$ ./configure && make
[tmux-server-8977.log](https://github.com/tmux/tmux/files/1569684/tmux-server-8977.log)
**
), I got an error. 
  2.2 Then I run command - **sudo apt install libevent-dev**
and  repeat stet 2. After that got the errors described above.

3. My **tmux.conf** (
set-option -g default-command bash

#source config file 
bind R source-file ~/.tmux.conf
bind S source-file ~/.tmux

#switch panels
bind k selectp -U # switch to panel Up
bind j selectp -D # switch to panel Down 
bind h selectp -L # switch to panel Left
bind l selectp -R # switch to panel Right

# Set prefix to space.
unbind C-b
set -g prefix C-Space


# Open new/split panes with the path of the current pane.
unbind c
bind c new-window -c '#{pane_current_path}'
unbind %
bind % split-window -h -c '#{pane_current_path}'
unbind '"'
bind '"' split-window -v -c '#{pane_current_path}'


# Resizing (mouse also works).
# unbind Left
# bind -r Left resize-pane -L 5
# unbind Right
# bind -r Right resize-pane -R 5
# unbind Down
# bind -r Down resize-pane -D 5
# unbind Up
# bind -r Up resize-pane -U 5

# Stay in copy mode on drag end, but otherwise exit for mouse up.
# Requires patch from https://github.com/tmux/tmux/issues/326
# unbind-key -t vi-copy MouseDragEnd1Pane
# bind-key -t vi-copy MouseUp1Pane cancel

# For those times when C-c and q are not enough.
# bind-key -t vi-copy Escape cancel


# Status bar.
set -g status-bg '#343d46'
set -g status-fg white
set -g status-left-length 40
set -g status-left '#[fg=yellow]#S ⧉ '
set -g status-right "#[fg=yellow]$USER@#h #[fg=magenta]%l:%M %p"
set -g status-interval 60 # Default is 15.

# Clipper.
bind-key y run-shell "tmux save-buffer - | nc -U ~/.clipper.sock"

# "copy-pipe" requires tmux >= 1.8
# bind-key -t vi-copy Enter copy-pipe "nc -U ~/.clipper.sock"

# Scroll
set-option -g mouse on

# Restore pre-2.1 behavior of scrolling with the scrollwheel in Vim, less, copy
# mode etc, otherwise entering copy mode if not already in it.
#
#   if in copy mode (pane_in_mode) || using the mouse already (mouse_any_flag)
#     pass through mouse events to current pane (send -Mt=)
#   elsif in alternate screen mode
#     send `Up` key
#   else
#     enter copy mode (-e exits if we scroll to the bottom)
#   end
#
bind-key -T root WheelUpPane \
[tmux-server-8977.log](https://github.com/tmux/tmux/files/1569687/tmux-server-8977.log)

    if-shell -Ft= '#{?pane_in_mode,1,#{mouse_any_flag}}' \
        'send -Mt=' \
        'if-shell -Ft= "#{alternate_on}" "send -t= Up" "copy-mode -et="'
bind-key -T root WheelDownPane \
    if-shell -Ft = '#{?pane_in_mode,1,#{mouse_any_flag}}' \
        'send -Mt=' \
        'if-shell -Ft= "#{alternate_on}"  "send -t= Down" "send -Mt="'

# Copy via mouse
set mouse-select-pane
set mouse-select-window

# Stay in copy mode on drag end, but otherwise exit for mouse up.
# Requires patch from https://github.com/tmux/tmux/issues/326
# unbind-key -t vi-copy MouseDragEnd1Pane
# bind-key -t vi-copy MouseUp1Pane cancel

# For those times when C-c and q are not enough.
# bind-key -t vi-copy Escape cancel

# Slightly more useful width in "main-vertical" layout; enough room for 3-digit
# line number gutter in Vim + 80 columns of text + 1 column breathing room
# (default looks to be about 79).
set -w -g main-pane-width 85

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',xterm-256color:Tc'

set -g history-limit 262144 





######################
### DESIGN CHANGES ###
######################

# panes
set -g pane-border-fg black
set -g pane-active-border-fg brightred

## Status bar design
# status line
set -g status-justify left
set -g status-bg default
set -g status-fg colour12
set -g status-interval 2

# messaging
set -g message-fg black
set -g message-bg yellow
set -g message-command-fg blue
set -g message-command-bg black

#window mode
setw -g mode-bg colour6
setw -g mode-fg colour0

# window status
#setw -g window-status-format " #F#I:#W#F "
#setw -g window-status-current-format " #F#I:#W#F "
#setw -g window-status-format "#[fg=magenta]#[bg=black] #I #[bg=cyan]#[fg=colour8] #W "
#setw -g window-status-current-format "#[bg=brightmagenta]#[fg=colour8] #I #[fg=colour8]#[bg=colour14] #W "
#setw -g window-status-current-bg colour0
#setw -g window-status-current-fg colour11
#setw -g window-status-current-attr dim
#setw -g window-status-bg green
#setw -g window-status-fg black
#setw -g window-status-attr reverse

# Info on left (I don't have a session display for now)
set -g status-left ''

# loud or quiet?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

set -g default-terminal "screen-256color"

# The modes {
setw -g clock-mode-colour colour135
#setw -g mode-attr bold
setw -g mode-fg colour196
setw -g mode-bg colour238

# }
# The panes {

set -g pane-border-bg colour235
set -g pane-border-fg colour238
set -g pane-active-border-bg colour236
set -g pane-active-border-fg colour51

# }
# The statusbar {

set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour137
set -g status-attr dim
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-fg colour81
setw -g window-status-current-bg colour238
setw -g window-status-current-attr bold
setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '

setw -g window-status-fg colour138
setw -g window-status-bg colour235
setw -g window-status-attr none
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

setw -g window-status-bell-attr bold
setw -g window-status-bell-fg colour255
setw -g window-status-bell-bg colour1

# }
# The messages {

set -g message-attr bold
set -g message-fg colour232
set -g message-bg colour166

# }
)

**uname -sp && tmux -V && echo $TERM**
Linux x86_64
tmux master
xterm-256color

**Comment by nicm** [comment]
Try to install libncurses-dev as well?

**Comment by RomaniukAS** [comment]
It didn't help.
tmux -V show **master**
[tmux-client-19195.log](https://github.com/tmux/tmux/files/1573128/tmux-client-19195.log)
[tmux-out-19198.log](https://github.com/tmux/tmux/files/1573129/tmux-out-19198.log)
[tmux-server-19198.log](https://github.com/tmux/tmux/files/1573130/tmux-server-19198.log)

and lines in my .tmux.conf:
 **unbind-key -t vi-copy MouseDragEnd1Pane
 bind-key -t vi-copy MouseUp1Pane cancel**
throw errors:
**/.tmux.conf:39: usage: unbind-key [-an] [-T key-table] key                                                                                                                       
/.tmux.conf:40: usage: bind-key [-cnr] [-T key-table] key command [arguments]**

**Comment by jungle-boogie** [comment]
If you think the `.tmux.conf` is an issue, move it to `tmux.conf` and then attempt to compile.

`ncurses.h: No such file or directory` You might want to do a find for that file to see if it exists.

**Comment by RomaniukAS** [comment]
I do not think that the .tmux.conf is an issue, just say, that install libncurses-dev didn't solve the problem.
And I can't understand why command tmux -V show **master** instead version value.

**Comment by jungle-boogie** [comment]
> And I can't understand why command tmux -V show master instead version value.

Is it possible tmux is being installed in the directory where you're attempting to compile it?

try the usual `make clean` and `make distclean`

**Comment by RomaniukAS** [comment]
It didn't help.
Than I remove `tmux` and then reinstall it. After that, I tried to upgrade it again, but `tmux -V` shows **tmux 2.1**

**Comment by nicm** [comment]
Show config.log and full configure+make output please.

**Comment by RomaniukAS** [comment]
Sorry for my late answer.
[config.log](https://github.com/tmux/tmux/files/1586159/config.log)

`./configure && make`
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking bitstring.h usability... no
checking bitstring.h presence... no
checking for bitstring.h... no
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking ndir.h usability... no
checking ndir.h presence... no
checking for ndir.h... no
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking pty.h usability... yes
checking pty.h presence... yes
checking for pty.h... yes
checking for stdint.h... (cached) yes
checking sys/dir.h usability... yes
checking sys/dir.h presence... yes
checking for sys/dir.h... yes
checking sys/ndir.h usability... no
checking sys/ndir.h presence... no
checking for sys/ndir.h... no
checking sys/tree.h usability... no
checking sys/tree.h presence... no
checking for sys/tree.h... no
checking util.h usability... no
checking util.h presence... no
checking for util.h... no
checking for library containing flock... none required
checking for dirfd... yes
checking for flock... yes
checking for prctl... yes
checking for sysconf... yes
checking for asprintf... yes
checking for cfmakeraw... yes
checking for closefrom... no
checking for explicit_bzero... no
checking for fgetln... no
checking for freezero... no
checking for getdtablecount... no
checking for getprogname... no
checking for memmem... yes
checking for recallocarray... no
checking for reallocarray... no
checking for setenv... yes
checking for setproctitle... no
checking for strcasestr... yes
checking for strlcat... no
checking for strlcpy... no
checking for strndup... yes
checking for strsep... yes
checking for strtonum... no
checking for working strnlen... yes
checking for library containing clock_gettime... none required
checking for LIBEVENT... yes
checking event.h usability... yes
checking event.h presence... yes
checking for event.h... yes
checking for LIBTINFO... yes
checking for b64_ntop... no
checking for b64_ntop with -lresolv... yes
checking for library containing inet_ntoa... none required
checking for library containing socket... none required
checking for socket in -lxnet... no
checking for CMSG_DATA... yes
checking for err... yes
checking for errx... yes
checking for warn... yes
checking for warnx... yes
checking err.h usability... yes
checking err.h presence... yes
checking for err.h... yes
checking for library containing imsg_init... no
checking for daemon... yes
checking whether daemon is declared... yes
checking for stravis... no
checking for getopt... yes
checking if getopt is suitable... no
checking for library containing fparseln... no
checking for library containing fdforkpty... no
checking for library containing forkpty... -lutil
checking whether TAILQ_CONCAT is declared... yes
checking whether TAILQ_PREV is declared... yes
checking whether TAILQ_REPLACE is declared... no
checking for __progname... yes
checking for program_invocation_short_name... yes
checking whether PR_SET_NAME is declared... yes
checking whether F_CLOSEM is declared... no
checking for /proc/$$... yes
checking platform... linux
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
make: Nothing to be done for 'all'.

**Comment by nicm** [comment]
This all looks fine to me, what is output when you run make?

**Comment by nicm** [comment]
Oh, you already built, so what's the problem?

**Comment by RomaniukAS** [comment]
`tmux -V` shows **2.1** instead number of latest version.

**Comment by nicm** [comment]
You are running the wrong tmux binary or you installed it in the wrong
place.

**Comment by RomaniukAS** [comment]
Below the command list that I was run:
1. `sudo apt-get install tmux`
2. install depended packages
3. `git clone https://github.com/tmux/tmux.git`
4. `cd tmux`
5. `sh autogen.sh`
6. `./configure && make`

If I was made something wrong, please, tell me what exactly. I will be very grateful.
If all ok, sorry and thank you for the time you spent.

**Comment by nicm** [comment]
What does "which tmux" show?

**Comment by RomaniukAS** [comment]
/usr/bin/tmux

**Comment by nicm** [comment]
So put the one you just built in there to replace the old one

**Comment by RomaniukAS** [comment]
Yes it helped. Thank you very much for your help.
