### ISSUE TITLE
window-status-activity-{bg,fg} are reverse to other colour settings

### ISSUE THREAD

**Issue by SpikePy** [tmux/tmux#1197]
As you can see in the screenshot setting the colours for window-status-activity-bg and window-status-activity-fg seems to work reverse to the other colours. 
fg is setting the basic colour and bg sets the font colour.

![image](https://user-images.githubusercontent.com/16565183/34085421-f6e5783e-e390-11e7-83ff-023082e808e4.png)

Using tmux 2.6 on arch

**Comment by nicm** [comment]
What is window-status-activity-style set to?

**Comment by SpikePy** [comment]
havent set anythingI haven't set it.
If I run `:set-option -gw  window-status-activity-attr` it says `empty value`

**Comment by nicm** [comment]
Right but what if you do show-option -gw window-status-activity-style...

**Comment by SpikePy** [comment]
That returns `window-status-activity-style fg=colour4,bg=colour2`

**Comment by nicm** [comment]
What about status-style?

**Comment by SpikePy** [comment]
window-status-style fg=colour0,bg=colour4

**Comment by nicm** [comment]
status-style...

**Comment by SpikePy** [comment]
If I set colors with `:set-option -gw  window-status-activity-style fg=colour2,bg=colour4` it seems to work as expected.

But setting 
`set -g window-status-activity-bg      colour2
set -g window-status-activity-fg       colour4`

inverts the colors

**Comment by nicm** [comment]
But they are not equivalent?

**Comment by nicm** [comment]
set-option -gw window-status-activity-style fg=colour2,bg=colour4

is the same as

set -g window-status-activity-fg colour2

set -g window-status-activity-bg colour4


not


set -g window-status-activity-bg colour2

set -g window-status-activity-fg colour4



On 18 December 2017 at 12:44, Nicholas Marriott <nicholas.marriott@gmail.com
> wrote:

> But they are not equivalent?
>

**Comment by SpikePy** [comment]
The initial problem was that the default config has `window-status-activity-attr reverse` and it looks like I'm not the only one who stumbled across this problem: https://unix.stackexchange.com/questions/120857/tmux-monitor-activity-change-highlight-color

**Comment by nicm** [comment]
OK.
