### ISSUE TITLE
Show jobs inside the status bar

### ISSUE THREAD

**Issue by edi9999** [tmux/tmux#12]
I would like to be able to see the jobs that I have running in the background in the status bar.

Here is what I tried : 

    set -g status-right '#[fg=black,bright]#(jobs | wc -l)'

However, this will not show anything because I guess the jobs command is not called from the context of the current pane but rather an other unacessible tty.

Is they a way to run the `jobs` command from inside the tty of the current pane ?

**Comment by nicm** [comment]
Put something like \[$(jobs >~/.jobs)\] in your PS1 then do #(wc -l ~/.jobs) in status-right. It'll only be updated after you enter a command in the pane, but that's the best you're going to get.
