### ISSUE TITLE
Using terminal overrides to force 256 colors on xterm stopped working around tmux 1.8

### ISSUE THREAD

**Issue by filbranden** [tmux/tmux#120]
In order to reproduce it:

- Add this line to your `.tmux.conf`:
```
set -g terminal-overrides "xterm*:colors=256"
```
- Set `TERM=xterm` outside of tmux.
- Start tmux.
- Set `TERM=screen-256color` or something that supports 256 colors inside tmux.
- Run a 256color application, such as vim, and check for correct colors (e.g. `:set t_Co?` inside vim).

I traced this to commit f2e54e1e2ff5a1902cdab4db50a503541186638e, reverting this commit on top of HEAD seems to fix this issue, then the terminal overrides seem to work correctly as expected.

I imagine that the problem is because the terminal-overrides indicate that 256 colors are available, but when searching the terminfo for `setaf` and `setab` they are not present...

Not really sure what is the best fix for this issue. Is it possible to detect whether `setaf` and/or `setab` are present and functional? Or maybe fallback to the old command if the `colors=256` is coming from a `terminal-overrides` setting?

Or maybe that setting now needs to be updated to include a sample value of `setaf` and `setab` other than setting `colors`? Though that seems to be a fairly common recipe, being even (somewhat) included in the tmux manpage itself...
https://github.com/tmux/tmux/blob/master/tmux.1#L2477

For now, I'm running with that commit reverted... Let me know if you can think of a cleaner solution for this problem. I'd be happy to test and contribute a patch if you can guide me through how you think it should work.

Cheers!
Filipe

@nicm @ThomasAdam

**Comment by filbranden** [comment]
This seems to work as a workaround:

```
set -g terminal-overrides "xterm:colors=256:\
setaf=\e[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m:\
setab=\e[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m"
```

I got the entries from `tput -T xterm-256color setaf` and `setab`.

But it's ugly... Suggestions?

**Comment by nicm** [comment]
Try this please:

```
diff --git a/tty.c b/tty.c
index c4dfde1..7be952c 100644
--- a/tty.c
+++ b/tty.c
@@ -1648,14 +1648,19 @@ tty_try_256(struct tty *tty, u_char colour, const char *type)
 	char	s[32];
 
 	/*
-	 * If the terminfo entry has 256 colours, assume that setaf and setab
-	 * work correctly.
+	 * If the terminfo entry has 256 colours and setaf and setab exist,
+	 * assume that they work correctly.
 	 */
 	if (tty->term->flags & TERM_256COLOURS) {
-		if (*type == '3')
+		if (*type == '3') {
+			if (!tty_term_has(tty->term, TTYC_SETAF))
+				goto fallback;
 			tty_putcode1(tty, TTYC_SETAF, colour);
-		else
+		} else {
+			if (!tty_term_has(tty->term, TTYC_SETAB))
+				goto fallback;
 			tty_putcode1(tty, TTYC_SETAB, colour);
+		}
 		return (0);
 	}
 
@@ -1663,13 +1668,15 @@ tty_try_256(struct tty *tty, u_char colour, const char *type)
 	 * If the user has specified -2 to the client, setaf and setab may not
 	 * work, so send the usual sequence.
 	 */
-	if (tty->term_flags & TERM_256COLOURS) {
-		xsnprintf(s, sizeof s, "\033[%s;5;%hhum", type, colour);
-		tty_puts(tty, s);
-		return (0);
-	}
+	if (tty->term_flags & TERM_256COLOURS)
+		goto fallback;
 
 	return (-1);
+
+fallback:
+	xsnprintf(s, sizeof s, "\033[%s;5;%hhum", type, colour);
+	tty_puts(tty, s);
+	return (0);
 }
 
 void


On Tue, Sep 22, 2015 at 01:53:11PM -0700, Filipe Brandenburger wrote:
>    In order to reproduce it:
> 
>      * Add this line to your .tmux.conf:
> 
>  set -g terminal-overrides "xterm*:colors=256"
> 
>      * Set TERM=xterm outside of tmux.
>      * Start tmux.
>      * Set TERM=screen-256color or something that supports 256 colors inside
>        tmux.
>      * Run a 256color application, such as vim, and check for correct colors
>        (e.g. :set t_Co? inside vim).
> 
>    I traced this to commit [1]f2e54e1, reverting this commit on top of HEAD
>    seems to fix this issue, then the terminal overrides seem to work
>    correctly as expected.
> 
>    I imagine that the problem is because the terminal-overrides indicate that
>    256 colors are available, but when searching the terminfo for setaf and
>    setab they are not present...
> 
>    Not really sure what is the best fix for this issue. Is it possible to
>    detect whether setaf and/or setab are present and functional? Or maybe
>    fallback to the old command if the colors=256 is coming from a
>    terminal-overrides setting?
> 
>    Or maybe that setting now needs to be updated to include a sample value of
>    setaf and setab other than setting colors? Though that seems to be a
>    fairly common recipe, being even (somewhat) included in the tmux manpage
>    itself...
>    [2]https://github.com/tmux/tmux/blob/master/tmux.1#L2477
> 
>    For now, I'm running with that commit reverted... Let me know if you can
>    think of a cleaner solution for this problem. I'd be happy to test and
>    contribute a patch if you can guide me through how you think it should
>    work.
> 
>    Cheers!
>    Filipe
> 
>    [3]@nicm [4]@ThomasAdam
> 
>    --
>    Reply to this email directly or [5]view it on GitHub.
> 
>    Reverse link: [6]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/tmux/tmux/commit/f2e54e1e2ff5a1902cdab4db50a503541186638e
>    2. https://github.com/tmux/tmux/blob/master/tmux.1#L2477
>    3. https://github.com/nicm
>    4. https://github.com/ThomasAdam
>    5. https://github.com/tmux/tmux/issues/120
>    6. https://github.com/tmux/tmux/issues/120

**Comment by filbranden** [comment]
Hi @nicm,

Unfortunately, that didn't work, because it turns out that the `xterm` entry *does* have `setaf` and `setab`, it's just that those definitions are too simple to support 256 colors...

```
$ infocmp xterm | grep -w -e xterm -e setaf -e setab
#       Reconstructed via infocmp from file: /lib/terminfo/x/xterm
xterm|xterm-debian|X11 terminal emulator,
        setab=\E[4%p1%dm, setaf=\E[3%p1%dm,
```

I was thinking of maybe creating a new `terminal-aliases` server option that would allow aliasing `xterm` to `xterm-256color`, not requiring to override individual commands one by one...

```
set -g terminal-overrides "xterm*:xterm-256color,whatever:linux"
```

That way `TERM=xterm` would be interpreted as `TERM=xterm-256color` (and `TERM=whatever` the same as `TERM=linux`), what do you think of that idea?

Cheers,
Filipe

**Comment by nicm** [comment]
Well, if the xterm entry has setaf/setab then tmux is right to use
them. If your platform has xterm-256color you should be using it
instead.

**Comment by filbranden** [comment]
Unfortunately, my terminal (xfce4-terminal) uses termcap (ugh!) which these days only contains the really basic entries... http://docs.xfce.org/apps/terminal/preferences#compatibility

I also have to deal with a fair share of systems hardcoding TERM=xterm or similar in /etc/profile or some other global scripts as they assume (not that incorrectly) that most people don't understand terminals and don't really know how to set theirs properly... making life harder for those of us who do know it.

I just sent you PR #121 introducing a new option to do a full translation of terminal name, so that whenever tmux sees TERM=xterm it can simply use xterm-256color instead. I think that's in many ways more elegant than terminal-overrides, particularly for something like forcing 256 colour support... Let me know if you like the patch or if you'd like me to do some changes to it.

If you prefer to accept patches some other way (e.g. `git format-patch` or some other VCS) just let me know and I'll be happy to oblige.

Cheers!
Filipe

**Comment by nicm** [comment]
Terminals do not use termcap or terminfo, aside from a few special cases like tmux, applications do. IIRC xfce4-terminal is VTE and it has full terminfo entries. And besides you are using the xterm terminfo anyway...

If you really insist on using xterm there are already mechanisms to fix it up, you can either build your own terminfo entry or use terminal-overrides in tmux, we don't need any more.

-------- Original message --------

**Comment by filbranden** [comment]
Hi @nicm please take a look at #122 then to see what you think...

There's some precedent for a use=... tag in a terminfo source description, so I thought using it here would be somewhat appropriate...

I do see your point about fixing this elsewhere (e.g. actually setting $TERM to point to xterm-256color or compiling my own replacement entry for xterm in my $HOME/.terminfo) but I think the fact that terminal-overrides exists (and many recipes for using it to enable 256 colours) means that's where some people want to support that and, well, that includes me... So I think this is a fairly natural extension to the currently existing terminal-overrides. Let me know what you think!

Cheers,
Filipe

**Comment by nicm** [comment]
But this does not work the same as use= which is a merge, whereas this is a replacement. I don't see any need for additional code in tmux to do this, it is a niche requirement and there are lots of alternatives. This is no easier than "[ x$TERM = xxterm ] && export TERM=xterm-256color" at the end of your shell profile. Or xterm*:colors=256:setaf@:setab@ in terminal-overrides if your only problem is 256 colours.

**Comment by filbranden** [comment]
So I tried with the "merge" behavior but there are a few problems, one of them is boolean flags so for instance if I want to `use=xterm+256color` it thinks flags such as `xenl` are off. So, to do the merge, I'd have to do a `|=` on the boolean flag.

The other problem is that I need to `setupterm()` multiple times to be able to get the information from the other terminal entry.

Something like:

```
if (setupterm(merge_term, fd, NULL) == OK) {
    /* Merge in codes for terminal */
    ...
    if (setupterm(term->name, fd, NULL) != OK) {
        /* Something really bad happened, do something about it... */
    }
}
```

Not sure if that's good enough...

Btw, your suggestion about `xterm*:colors=256:setaf@:setab@` doesn't work, unless you push your patch with `if (!tty_term_has(tty->term, TTYC_SETAF)) goto fallback;`.

I'm really in love with the idea to use `terminal-overrides` to turn my `xterm` into an `xterm-256color`, I was already doing so (poorly) with `xterm*:colors=256` before, so why not just do it "right" and switching it completely? What would it take for me to convince you that this is an useful (and somewhat natural) extension of what `terminal-overrides` already does?

Cheers!
Filipe

**Comment by nicm** [comment]
I don't think this is a good idea.

**Comment by filbranden** [comment]
Hi @nicm,

Sorry to be pushy... But I really care about this, I think it is useful.

My main concern is that googling for something like [256 colors in tmux](https://www.google.com/search?q=256+colors+in+tmux) you get to results such as [this page](http://bentomas.com/2012-03-28/256-colors-in-tmux.html) which recommends using terminal-overrides to enable 256 colours, with:

```
set -g terminal-overrides 'xterm:colors=256'
```

But, as mentioned before, this setup is broken since f2e54e1e2ff5a1902cdab4db50a503541186638e and there are really no _great_ ways around it still in `.tmux.conf`.

For instance, you suggested:

```
set -g terminal-overrides 'xterm:colors=256:setaf@:setab@'
```

But that will only work with your previous patch of `goto fallback` (and will use a hardcoded fallback instead of the actual string of the terminal).

What I have been using works, but it's *ugly*...

```
set -g terminal-overrides "xterm:colors=256:\
setaf=\e[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m:\
setab=\e[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m"
```

Not to mention that this will possibly get out of sync with its origin, which turns out to be... well, xterm-256color!

Because it turns out that the *intent* of that configuration is really to map the terminal entry, so that even though I'm saying `TERM=xterm`, I'm telling tmux that I know I have 256 colour support, so please go ahead and enable it, act as if `xterm-256color` was used instead.

The fact that many web search results (such as that aforementioned web page) suggest solutions in `.tmux.conf` indicates that fixing TERM settings is not really practical everywhere... So much so that tmux already supports `terminal-overrides`!

What is it about that feature that you dislike so much? Is it the name? We could use something other than `use=...` if you prefer (like `replace=...`?), or even a separate configuration variable (as I suggested `terminal-aliases` before, but we could use another name.) Do you have a different suggestion on how to fully map terminal entries from .tmux.conf that you'd be happy with?

Do you worry that this might cause confusion to users? I'd say unlikely, since it requires them to configure it explicitly...

Do you think this might become a maintenance burden? I think it's fairly straightforward, but we could try to make it more so to make it less of a burden...

Please let me know what would it take for you to consider adding a way to do full terminal name mapping!

Thanks,
Filipe

**Comment by nicm** [comment]
I am not adding code to do this when there are several perfectly adequate existing solutions, this does not add anything that you cannot already do easily. This is not something where the current solutions are huge and complicated. You can do any of these:

- Use the right TERM in the first place.
- Change TERM in your shell profile.
- With the diff above (which I will apply), put xterm*:colors=256:setaf@:setab@ in terminal-overrides.
- Create an alternative xterm which is basically just use=xterm-256color and install it with tic.
- Use tmux -2 which will get tmux to use SGR directly instead of setaf/setab.

I am not responsible for information given by other people that you can find with Google and I am not going to change tmux to fit in with it. Now that terminfo has the correct setaf and setab we are doing the right thing by using them. For anyone left using a system without xterm-256color or using a terminal whose terminfo entry does not have a 256 colour variant, there is tmux -2.
