### ISSUE TITLE
Tmux set-buffer makes tmux server crash completely

### ISSUE THREAD

**Issue by edi9999** [tmux/tmux#1200]
# Environment 

Linux x86_64
tmux master (commit https://github.com/tmux/tmux/commit/43a1294ed99c301bcbea808384535a37d8fd0066)
screen-256color

Bug can be reproduced with no config, on 2.6 and on master

To reproduce, run following code : 

```
yes 1 | head -n 76455 | tr -d '\n' > /tmp/text   
tmux set-buffer -- "$(cat /tmp/text)" 
```

You will loose the server 

The message in the logs is : 

```
1513614185.090898 peer 0x821090 message 200
1513614185.090902 fatal: bad MSG_COMMAND string
```

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1568984/x.diff.txt)

**Comment by nicm** [comment]
Wait, that is wrong define.

**Comment by nicm** [comment]
Try this please: [y.diff.txt](https://github.com/tmux/tmux/files/1569001/y.diff.txt)

**Comment by edi9999** [comment]
Yes, it is working !

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by edi9999** [comment]
Thanks a lot too !
