### ISSUE TITLE
Increase gap between lines?

### ISSUE THREAD

**Issue by elvisoliveira** [tmux/tmux#1203]
Is there an way to increase the gap between the devision lines? If no, it would be nice to have the possibility to set a padding in order to organize better the info on the multi panes.

**Comment by nicm** [comment]
What gap?

**Comment by elvisoliveira** [comment]
The gap between the green pane border and it's contents.

![tmux](https://i.imgur.com/PEAPUNH.png)

**Comment by nicm** [comment]
I don't think we want to add a gap there.

**Comment by elvisoliveira** [comment]
Sometimes when i'm compiling different codes, i use multi panes in order to see how things are going with all compilations simultaneously, but as the gap between panes are small and not configurable it's harder for me.
I totally understand when you say you don't want a gap there, but it would not be good to add this as an additional option for the ones who want to increase the space between the panes?

**Comment by nicm** [comment]
If you want the border to be more obvious, try giving it a background colour:
~~~~
set -wg pane-border-style bg=green
set -wg pane-active-border-style bg=green

**Comment by elvisoliveira** [comment]
That's for sure solves the problem, thanks for addressing my issue. But what i'm suggesting could be an alternative solution, something like what i3wm gaps does.
Since as you said there is no plans for a gap feature, and i totally understand your position, something that could also solve the issue would be allowing custom lines ASCII chars, so i could replace them by high density dotted blocks (Eg.: ▓) or doubled lines (Eg.:║╣╗╝).
But this is just a suggestion, i'll keep using tmux anyway because it's an awesome project. Thanks.

**Comment by nicm** [comment]
The gap could only be one or two full lines in height which would be very big and I think hardly anyone would use it, it is not worth it.

**Comment by elvisoliveira** [comment]
Well.. I would use it :)
Anyways, thanks for the replies.

**Comment by jemueller** [comment]
I would like to see this as an option

**Comment by jocap** [comment]
>The gap could only be one or two full lines in height which would be very big and I think hardly anyone would use it, it is not worth it.

You'd be surprised. People like big gaps, especially those who "rice" their system to make it look cool. That's why forks like i3-gaps exist.

How difficult would it be to add an option for this? How "hard-coded" is the pane divisor's width?

Best regards,
John

**Comment by jemueller** [comment]
I would use it
