### ISSUE TITLE
Shift+Down interpreted as Shift+Up

### ISSUE THREAD

**Issue by seamus-45** [tmux/tmux#1204]
name | version
-------|------
tmux | 2.6
termite | 13
vte | 0.48.3

on Gentoo Linux

Not sure it is the right place for my bug report, maybe the problem is terminfo or terminal emulator, but anything's possible..
In clean terminal session mentioned keys works as intended, but in tmux S-Down acts like S-Up.
Please look at the [video](http://telegra.ph/file/d3026b8c0b6638db89887.mp4) that describing my problem.

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by seamus-45** [comment]
Thanks, anyway! :+1:

**Comment by RobbieClarken** [comment]
I encountered this bug with the default version of tmux in homebrew. Fixed with:

```
brew install tmux --HEAD
```
