### ISSUE TITLE
set -g default-terminal didn't work

### ISSUE THREAD

**Issue by id777** [tmux/tmux#1205]
How should work `set -g default-terminal` option? Do I understand correctly, what if there is this option in config, then inside tmux `$TERM` will be as value of this option?

In .tmux.conf I have `set -g default-terminal "tmux-256color"`. Term outside tmux - xterm-256color.
When I run tmux, value of `echo $TERM` is `xterm-256color`. Not `tmux-256color`. 

Is this a correct behavior?

---
Tmux without any plugins. 
`$ uname -sp && tmux -V && echo $TERM`:
Linux x86_64
tmux 2.6
xterm-256color

**Comment by nicm** [comment]
Are you changing it in some shell profile?

**Comment by id777** [comment]
Changind what? 

I have `set -g default-terminal "tmux-256color"` in ~/.tmux.conf
and 
```
if [ -n "$DISPLAY" ]; then
  export TERM=xterm-256color
else
  export TERM=screen-256color
fi
```
in ~/.bashrc.

**Comment by krader1961** [comment]
You should not set `TERM` in your *~/.bashrc* unless it is not already set. If `$DISPLAY` is set when you start a tmux session you end up replacing the TMUX value for `$TERM`. Even outside of tmux it doesn't make sense to predicate `$TERM` on whether or not `$DISPLAY` is set.

**Comment by nicm** [comment]
Seems like DISPLAY is most likely set and this is overwriting the TERM tmux sets.

**Comment by brlafreniere** [comment]
having the same issue, DISPLAY is indeed not set.

**Comment by Peppershaker** [comment]
exact same issue here
