### ISSUE TITLE
Geeting "tmux: fork: Resource temporarily unavailable" in MacOS 10.13.2

### ISSUE THREAD

**Issue by yaroslavvb** [tmux/tmux#1207]
Something happened after upgrading to 10.13.2 MacOS from 10.13.1 so that I can no longer use tmux. TMUX seems to be the only program that is affected.

Running under dtrace I see that tmux rapidly forks 10 times within microseconds before getting this error. Any idea why it needs to fork so many times?

```sudo drtuss -a tmux
...
10721/0xd199:      3633       1      0 sigprocmask(0x1, 0x7FFEE9B0E3EC, 0x7FFEE9B0E3FC)		 = 0x0 0
10721/0xd199:      4196     558    549 fork()		 = 10722 0
```

MacOS: 10.13.2
tmux: 2.6 from homebrew

Also tried with tmux: 2.3_2

**Comment by nicm** [comment]
It would be more helpful to show the whole trace. Also tmux logs.

**Comment by yaroslavvb** [comment]
There's no trace, I just see this:
÷17-12-22 13:00:35|ttys004|mac|~/Google Drive/src\÷ tmux
/Users/yaroslav/d/bin/tmux: fork: Resource temporarily unavailable

whole dtruss logs attached
[tmux.txt](https://github.com/tmux/tmux/files/1583467/tmux.txt)

**Comment by nicm** [comment]
That's what I meant also please show logs from tmux -vvvv

**Comment by yaroslavvb** [comment]
÷17-12-22 13:05:13|ttys004|mac|~/Google Drive/src\÷ tmux -vvvv
/Users/yaroslav/d/bin/tmux: fork: Resource temporarily unavailable

**Comment by yaroslavvb** [comment]
Sorry, for noise, looks like I was accidentally using wrong version of tmux, homebrew actually works
