### ISSUE TITLE
Ctrl-Home and Ctrl-End keys not passed through

### ISSUE THREAD

**Issue by myly10** [tmux/tmux#1209]
### your platform (Linux, OS X, or whatever);
Linux 4.10.0-42-generic, but actually reproducible everywhere

### a brief description of the problem with steps to reproduce;
- Run `sudo showkey`
- Observe different output
- Run tmux with `-vvvvv` and press `C-End`, there will be:
```
event dispatch enter
keys are 6 (\033[1;5F)
complete key \033[1;5F 0x5034
session 0 not pasting
writing key 0x5034 (C-End)
key 0x5034 missing
event dispatch exit
```

I checked tmux code and found related line: [here](https://github.com/tmux/tmux/blob/336beeb09afcc8f381062da49a4c23c6d16a9833/input-keys.c#L226), which seems its caused by a hard-coded array not containing C-End and C-Home escape sequence.

### a minimal tmux config, if you can't reproduce without a config;
Just default config

### your terminal, and $TERM inside and outside of tmux;
SSH. Inside: `screen` Outside: `xterm`

**Comment by nicm** [comment]
Do you have xterm-keys turned on?

**Comment by myly10** [comment]
Thanks a lot for this. Turning on `xterm-keys` will pass C-End and C-Home to panes inside, but vim doesn't recognize them this time. I need to use Vundle plugin `Plugin 'nacitar/terminalkeys.vim'` to make it work. Though this part is not related to tmux, maybe this can help others.
