### ISSUE TITLE
tmux always sets the iutf8 flag, even for non-Unicode locales

### ISSUE THREAD

**Issue by unix-junkie** [tmux/tmux#1211]
I'm running tmux 2.3, Debian Linux 9 (amd64).

tmux always sets the `iutf8` flag, rendering it unusable in non-ASCII (i. e. 8 bit) non-Unicode locales
like `ru_RU.KOI8-R`.

The problem is easy to reproduce using a `ru_RU.KOI8-R` environment or, alternatively, by running `koi8rxterm` which already has all the necessary environment set.

Before running tmux:

    $ locale charmap
    KOI8-R
    $ stty
    speed 38400 baud; line = 0;
    -brkint -imaxbel

![before](https://user-images.githubusercontent.com/3080024/34339429-690b4eaa-e98d-11e7-8628-3950d0b8537f.png)

After running tmux, from a subshell of the parent process:

    $ locale charmap
    KOI8-R
    $ stty
    speed 38400 baud; line = 0;
    -brkint -imaxbel iutf8

So the terminal settings are changed while the locale settings are not, and obviously `KOI8-R` and `iutf8` don't play well together (all 8-bit output from child precesses is stripped, being never echoed).

![after](https://user-images.githubusercontent.com/3080024/34339433-738d74fc-e98d-11e7-98ed-e3e3c1600693.png)

tmux 1.9 (e. g.: in Debian 8), as well as previous versions, was never affected.
Neither is GNU `screen` (have to switch back to `screen` until this issue is fixed).

tmux from git master is equally affected. It looks like the issue was introduced with commit b7397bf, when the utf8 option was dropped.

The corresponding issue in _Debian Linux_ is [bug #885164](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885164).

**Comment by nicm** [comment]
tmux does not support any locale except UTF-8. All programs running inside tmux must output UTF-8 or they will not work correctly.

**Comment by unix-junkie** [comment]
Thanks.
That's a shame, though.
Does the same apply to tmux 2.1 (before `mouse-utf8` and `utf8` options were dropped)?

**Comment by nicm** [comment]
I don't remember when tmux changed but possibly it was 2.1. If you want to use non-UTF-8 locales with a later version you will need to use something like luit.
