### ISSUE TITLE
cannot select text when using osx 10.12 ssh to a centos with tmux 2.6

### ISSUE THREAD

**Issue by bzvew** [tmux/tmux#1212]
I update the tmux on centos 7 to 2.6, and I use ssh to connect to centos from osx 10.12. When I set set -g mouse on, I can mouse scroll for content(not for shell history), but I cannot select text, because when I release mouse, the selected text automatically get unselected. If I do not use set -g mouse on, I can select text, but I can only mouse scroll for shell history(not for content). How to enable mouse select and I can also scroll for content?

**Comment by nicm** [comment]
I don't really understand this issue. It sounds like you are mixing up tmux selection with copy mode and terminal selection to the X clipboard?

**Comment by bzvew** [comment]
The mouse cannot select text in tmux window when using ssh when set -g mouse on. If not set -g mouse on, I can select text, but I want to use set -g mouse on for other features.

**Comment by nicm** [comment]
In most terminals you can make the terminal use the mouse by holding Shift.
