### ISSUE TITLE
Bind key to cancel from command prompt

### ISSUE THREAD

**Issue by zhammer** [tmux/tmux#1213]
Is it possible to bind a custom key to cancel from command-prompt? Right now only ```C-c``` works, though it seems to not be associated to any key binding in ```list-keys```. I'd like to add ```C-g``` to cancel from command prompt for emacs-like behavior.

**Comment by nicm** [comment]
You can't bind it but it might be a good idea to add it, try this change:
~~~~
Index: status.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/status.c,v
retrieving revision 1.172
diff -u -p -r1.172 status.c
--- status.c	18 Dec 2017 12:39:34 -0000	1.172
+++ status.c	27 Dec 2017 13:38:07 -0000
@@ -1337,6 +1337,7 @@ process_key:
 		break;
 	case '\033': /* Escape */
 	case '\003': /* C-c */
+	case '\007': /* C-g */
 		if (c->prompt_inputcb(c, c->prompt_data, NULL, 1) == 0)
 			status_prompt_clear(c);
 		break;

**Comment by zhammer** [comment]
will do. i'll try out this patch after work

**Comment by zhammer** [comment]
@nicm added the patch and everything's working as expected. can i submit as a PR?

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by zhammer** [comment]
@nicm awesome. is there a doc somewhere that explains the openbsd -> github -> deployment pipleline?
