### ISSUE TITLE
no current target error on startup

### ISSUE THREAD

**Issue by happyyi008** [tmux/tmux#1214]
Linux x86_64
tmux 2.6
screen-256color

$ echo $TERM
xterm

I have `bind r source-file -q ~/.tmux.conf; display "Reloaded!"` in my tmux.conf and when I start tmux I get this error:

`/home/yi/.tmux.conf:54: no current target `

**Comment by nicm** [comment]
The ; should be \; or it will run the display command immediately while
loading config.

**Comment by happyyi008** [comment]
That fixed it! Thanks
