### ISSUE TITLE
can't create socket: Permission denied

### ISSUE THREAD

**Issue by eromoe** [tmux/tmux#1215]
centos 7

I uninstall tmux 1.8 in this machine and tried to install latest by 
this script:
https://gist.github.com/djnugent/33a263f8d4139a14bad83105ea9f75b4

I use root install tmux 2.6 in `/usr/local/bin/`  .

```
[root@repo env (master ✗)]$ tmux
can't create socket: Permission denied

[root@repo env (master ✗)]$ ll `which tmux`
-rwxrwxrwx 1 root basin 1.3M Dec 28 15:33 /usr/local/bin/tmux

[root@repo env (master ✗)]$ tmux -S /tmp/tmux-12162/default
lost server

```

**Comment by eromoe** [comment]
Solve by
```
rm -r /tmp/tmux-*
```

Why this would happen?  Tmux tried to find previous session ?

**Comment by nicm** [comment]
You must have had some preexisting directories with the wrong permissions,
perhaps you are the second user to use this UID?

**Comment by eromoe** [comment]
I think it would be better to provide a more detaily error msg

**Comment by nicm** [comment]
I think it might be better too.

**Comment by ThomasAdam** [comment]
It should be trivial to change `tmux.c:make_label()` to indicate this, if someone fancies giving it a go?   @eromoe - how about you?

```
static char             *make_label(const char *, char **);

static char *
make_label(const char *label, char **cause)
{
    ....
    *cause = NULL;
    if (something_blew_up)
        xasprintf(cause, "Oops: %s", reason);
    }
}
```

**Comment by eromoe** [comment]
@ThomasAdam 
Sorry, I am not familiar with C,  mainly coding python. 
I tried to read the code, do you mean add another parameter `char **cause` to `make_label` function? But how to generate `cause` ,  I think need use C code to detect file permission ( recursively? ) is something difficult for me.

**Comment by zeroc0d3** [comment]
This steps work for me:
* Add this line on your `~/.bashrc` or `~/.zshrc`
```
export TMUX_TMPDIR=~/.tmux/tmp
```
* Create folder & change to write mode:
```
mkdir -p ~/.tmux/tmp
chmod 777 -R ~/.tmux/tmp
```
* Reload `~/.bashrc` or `~/.zshrc`
```
$SHELL
```
* Re-run the tmux
```
tmux
```

**Comment by ThomasAdam** [comment]
Try this.  No need to restart tmux.

[x.diff.txt](https://github.com/tmux/tmux/files/1609791/x.diff.txt)

**Comment by nicm** [comment]
Applied with some minor tweaks, thanks!

**Comment by BlockChainCaffe** [comment]
Soved with 
`rm -Rf /tmp/tmux-<userid>`

**Comment by emergencyd** [comment]
I also encountered this problem. But I find that I can use sudo to operate the tmux. So I guess it's the problem of authority.
 
Then, "chmod 777 -R /tmp" should definitely work

**Comment by biocyberman** [comment]
> I also encountered this problem. But I found that I can use "sudo" to operate the tmux. So I guess it's the problem of authority.
> 
> Then, "chmod 777 -R /tmp" should definitely work

You should run `chmod 1777 /tmp` instead. That's the correct permission for `/tmp`.
