### ISSUE TITLE
Tmux status line is not displaying exactly the way output of my python script should be

### ISSUE THREAD

**Issue by phenomenal-ab** [tmux/tmux#1216]
I wrote a python script for displaying a battery bar with unicode characters, charging status and percentage.
My script successfully executes in the bash terminal and produces desired output , but as i try to use that output in the tmux statusline , it doesn't provide the effect.

I am attaching the scrrenshots to give you a clear look about what i am getting 
![tmux_bug](https://user-images.githubusercontent.com/22402557/34441881-8f871cda-ece4-11e7-8878-fb014aa65502.png)

You can see in the bottom , tmux left status line portion shows fragmented output [ not exactly the ouput ]
while in bottom-right pane , you can see the script does show, the battery bar in colors , with percentage i.e. the desired output.

**Comment by Darkshadow2** [comment]
tmux doesn't do ANSI escape sequences. You'll have to write a new script to output the tmux color sequences (like what you have in the status-right option in the screen shot).

**Comment by phenomenal-ab** [comment]
Thanks @Darkshadow2 . And Hell, I did a lot to create a bar like that when the terminal suppors it , it should have supported the exact same way . Anyway , this is how it works . 
And very thanks for an early reply .
