### ISSUE TITLE
Tmux crashed

### ISSUE THREAD

**Issue by liucsthu** [tmux/tmux#1217]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING
I created session running user programs, but in the next day the session does not exist. So is there a method to find why the session failed?

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.
