### ISSUE TITLE
Tmux stopped showing some colors

### ISSUE THREAD

**Issue by danielramospy** [tmux/tmux#1218]
When restarting my computer tmux stopped showing some colors.

Before
![screenshot](https://user-images.githubusercontent.com/25720107/34460653-8934ec1c-edf3-11e7-8793-1f82c38dbcf6.png)
![screenshot2](https://user-images.githubusercontent.com/25720107/34460654-895df58a-edf3-11e7-85df-29acf8965818.png)

After
![screenshot3](https://user-images.githubusercontent.com/25720107/34460655-897f01da-edf3-11e7-830e-fc66422a6330.png)
![screenshot4](https://user-images.githubusercontent.com/25720107/34460656-899ee856-edf3-11e7-942d-aec7ef906b9a.png)

However TC is working:

![screenshot5](https://user-images.githubusercontent.com/25720107/34460657-89bf6004-edf3-11e7-99ec-99fd40f8886e.png)

Colors work fine outside tmux. Tmux was working fine for more than 1 week, this problem appeared just today. Reinstalling tmux from master does not fix.

### Environment

**Tmux version**: 2.6
**OS**: Ubuntu 16.04
**Terminal**: GNOME Terminal 3.18.3

#### Inside tmux

```bash
$ echo $TERM
screen
```

#### Outside tmux

```bash
$ echo $TERM
xterm-256color
```

### Tmux.conf

```
set-option -sa terminal-overrides ",xterm*:Tc"
```

### Also tried

.bashrc
```BASH
export TERM=screen-256color
```

.tmux.conf
```
set-option -sa terminal-overrides ",screen*:Tc"
```

### tmux info
[tmux info](https://gist.github.com/danielramospy/e0f34ddc4d2c9da948dcd39b44128913)

**Comment by nicm** [comment]
TERM inside tmux needs to be screen-256color and outside xterm-256color, try setting default-terminal to screen-256color and not changing TERM in .bashrc.

**Comment by danielramospy** [comment]
Now:

### Inside tmux
```
$ echo $TERM
screen-256color
```

### Outside tmux
```
$ echo $TERM
xterm-256color
```

and still not working.

**Comment by nicm** [comment]
If you get this script http://scie.nti.st/dist/256colors2.pl and run it
with perl inside tmux, what do you see?

**Comment by danielramospy** [comment]
![screenshot](https://user-images.githubusercontent.com/25720107/34461618-64eef6b2-ee0d-11e7-84bd-d52240d0b572.png)

TC seems to work fine, but theme colors are not displayed, only in the bottom bar.

**Comment by danielramospy** [comment]
I have updated to gnome-terminal 3.20.2 and it does not fix the problem.

**Comment by nicm** [comment]
Seems like tmux is showing the colours fine, what applications are you
having trouble with?

**Comment by danielramospy** [comment]
I'm just using the terminal and vim. The terminal and vim schemes do not work inside tmux. They were working inside and outside tmux, as in the first screenshots.

**Comment by danielramospy** [comment]
I suspect it is a problem related to gnome-terminal.

**Comment by danielramospy** [comment]
With TERM=screen-256color and

```
set -g default-terminal "xterm"
set-option -sa terminal-overrides ",screen*:Tc"
```

vim takes the correct colors.

Also with TERM=xterm-256color and

```
set -g default-terminal "xterm"
set-option -sa terminal-overrides ",xterm*:Tc"
```

The terminal scheme however does not work.

**Comment by nicm** [comment]
Seems like vim is deciding to use colours if TERM is xterm but not screen,
maybe you need to configure it.

**Comment by danielramospy** [comment]
You are right. Now I use screen-256-color on tmux and put this in .vimrc:

```
set termguicolors
set term=xterm-256color
```

The problem of the terminal scheme I could not solve. But I guess it's a gnome-terminal scheme thing.

**Comment by danielramospy** [comment]
It's strange but with --color=auto the colors work:
![screenshot](https://user-images.githubusercontent.com/25720107/34462679-f89c22bc-ee27-11e7-8ffd-3d325d9a13f8.jpg)

**Comment by danielramospy** [comment]
Reloading .bashrc the colors also come back
![screenshot](https://user-images.githubusercontent.com/25720107/34462779-e1fc79ce-ee29-11e7-80ad-cba194b9c059.jpg)

**Comment by danielramospy** [comment]
Outside tmux

```bash
$ echo $PS1
${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$
```

Inside tmux

```bash
$ echo $PS1
${debian_chroot:+($debian_chroot)}\u@\h:\w\$
```

**Comment by danielramospy** [comment]
Solved with

```bash
$ tmux new bash
```

or 

.bashrc
```
alias tmux='tmux new bash'
```

https://stackoverflow.com/a/28003594
