### ISSUE TITLE
function free should be replaced with xfree

### ISSUE THREAD

**Issue by qdzhaov** [tmux/tmux#1220]
The functions malloc,calloc,.. replaced with xmalloc,xcalloc;
Should the function free  be replaced with xfree.
patch file:
[0xfree_pat.txt](https://github.com/tmux/tmux/files/1598025/0xfree_pat.txt)

**Comment by ThomasAdam** [comment]
No.  I actually helped remove it.  See:  a432fcd30617610b46d65f49b7513bf5da5694de

**Comment by qdzhaov** [comment]
free to pair with xmalloc , it doesn ' t look comfortable,

**Comment by ThomasAdam** [comment]
I'm afraid I'm having trouble understanding you.  But for the avoidance of doubt, thank you for the patch, but it won't be applied.
