### ISSUE TITLE
log_debug(...) should replaced LOG_DEBUG((...))

### ISSUE THREAD

**Issue by qdzhaov** [tmux/tmux#1221]
function call log_debug(...) is not well,
should use  LOG_DEBUG((...))
#ifdef DEBUG
#define LOG_DEBUG(a) log_debug a
#else
#define LOG_DEBUG(a)
#endif
patchfile:
[1LD_pat.txt](https://github.com/tmux/tmux/files/1598049/1LD_pat.txt)

**Comment by ThomasAdam** [comment]
Err, no.  Why do you think this?

**Comment by qdzhaov** [comment]
In Release Build,call speed up,and many code use this method.
Sorry, My English is very bad

**Comment by ThomasAdam** [comment]
I'm not convinced it's slow at all.  You wouldn't macro this out like this anyway -- and if it were critical, you're better off trying to inline the function.

Neither of these are warranted in this case.

**Comment by nicm** [comment]
Which code path does logging make slower and by how much?

Needing to recompile for logging makes it hard to debug issues.
