### ISSUE TITLE
TrueColor by default

### ISSUE THREAD

**Issue by fbruetting** [tmux/tmux#1222]
- v2.6 @ FreeBSD 11.1 and Fedora 27

Could you please set-up TrueColor support by default?

**Comment by nicm** [comment]
I have no idea what you mean by this.

**Comment by fbruetting** [comment]
For being able to show TrueColor, I need to specify this manually, and I’d like to ask if this could be made default:
```
(set        -g  default-terminal    "xterm-256color")
set-option  -ga terminal-overrides  ",xterm-256color:Tc"
```

**Comment by nicm** [comment]
No it can't be the default, not least because xterm doesn't really support
it.

**Comment by fbruetting** [comment]
Well, with this configuration, it does…?

**Comment by nicm** [comment]
xterm only emulates it by using the 256 colour palette, it doesn't support it.

**Comment by fbruetting** [comment]
Ok, I have no idea of such internals – but at least I can say that I’m able to see more colors with that setting, which is nice. ;P

**Comment by nicm** [comment]
I don't think we want to make it the default or can make it any easier than it already is.
