### ISSUE TITLE
Pos1 & End don’t work inside nvim inside tmux

### ISSUE THREAD

**Issue by fbruetting** [tmux/tmux#1223]
- v2.6 @ FreeBSD 11.1

Both keys work nice in zsh/nvim without using tmux – but as soon as I am inside tmux, these just work in zsh, but not in nvim anymore. This happens both without having anything defined in .tmux.conf, and with having xterm-256color and the appropriate TrueColor setting defined.

For these keys getting to work in the first place, I hat to put this in my .zshrc:
```
bindkey "^[[1~" beginning-of-line
bindkey "^[[4~" end-of-line
```
I also tried "^[[{7,8,H,F}".

**Comment by nicm** [comment]
You will need to configure vim to recognize the tmux home and end sequences, not just zsh.

**Comment by nicm** [comment]
Did you try using TERM=tmux inside tmux instead of TERM=screen?

**Comment by fbruetting** [comment]
I use TERM=xterm-256color because of TrueColor, and I got strange behaviour with using TERM=tmux (I for example couldn’t use backspace/delete).

**Comment by nicm** [comment]
If you want to use TERM=xterm* inside tmux you are on your own, only TERM=screen* or TERM=tmux* is supported.
