### ISSUE TITLE
Lag introduced in nvim

### ISSUE THREAD

**Issue by fbruetting** [tmux/tmux#1224]
- v2.6 @ FreeBSD 11.1

As soon as I use nvim in tmux, I recognize a certain lag. Often times when I hit `Esc`, this won’t get recognized if I press another key (mostly `:`) quickly afterwards. What happens, is that I write `:wq` or things like that into my file instead of getting back to the command mode and having that command executed. So after hatting `Esc`, I always have to wait for about one second for getting this forwarded to nvim. As soon as I use nvim without tmux, everything runs perfectly fine.

**Comment by chrisbra** [comment]
that is a neovim [FAQ](https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed)
