### ISSUE TITLE
Can capture-pane always capture current view of pane, even it's have copy mode enabled?

### ISSUE THREAD

**Issue by id777** [tmux/tmux#1226]
Hi! I found what capture-pane only pipes current content in normal mode.
When tmux in copy mode, capture-pane still capture content at the bottom of history, not in current position of copy mode.

I also know what capture-pane can accept argument's as an exact range of lines from history what I want to copy. 

But can capture-pane automatically copy all currently visible content of pane when tmux in copy mode?

**Comment by nicm** [comment]
I think you can use scroll_position format (get value with display -p) then pass to capture-pane -S/-E.

**Comment by id777** [comment]
Thanks for answer!

I found plugin which doing exactly what I want (can pipe the current view of pane even if in copy mode) https://github.com/Morantron/tmux-fingers. In the source of this plugin everyone can see how to do it.
