### ISSUE TITLE
redraw fails with vim

### ISSUE THREAD

**Issue by jruffet** [tmux/tmux#1228]
I'm having an issue with tmux 2.6 from stretch-backports (2.6-3~bpo9+1)
Spawning a new tmux with `tmux -f/dev/null -Ltest new` (to be sure, but the issue arises with my conf), vim with stock configuration, when I scroll in vim (pgup/pgdwn) parts of what was displayed and should be redrawn is not.
If I force a tmux redraw (C-b r), it is displayed correctly.
Forcing a vim redraw (C-l) has no effect.
Note that if I split the window in 2 panes, then there is no issue.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by jruffet** [comment]
Issue still present in master. All the following info are based on tmux/master.
Within tmux spawned with `tmux -f/dev/null -Ltest new`
```
$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.6
screen
```
Terminal : konsole
TERM outside tmux : xterm-256color (same term within, if I use my tmux conf)
Log with `tmux -vv -Ltest -f/dev/null new` : [tmux-server-13389.log](https://github.com/tmux/tmux/files/1618514/tmux-server-13389.log)

I hope you have all the info that you need.

**Comment by nicm** [comment]
This is probably https://bugs.kde.org/show_bug.cgi?id=379318, try upgrade Konsole or:
~~~~
set -as terminal-overrides ',*:indn@'
~~~~
Do not use TERM=xterm* inside tmux.

**Comment by jruffet** [comment]
Your workaround works like a charm.
Indeed, konsole shipped with the latest ubuntu is pre-patch.

Sorry about the xterm-256color, that was a mixup. That is actually screen-256color in a tmux session with my .tmux.conf.

Thank you for the very fast and accurate replies.
