### ISSUE TITLE
Feature request: Restore old choose-buffer inline preview UI treatment

### ISSUE THREAD

**Issue by hmak3d** [tmux/tmux#1229]
## Issue

Hi, tmux v2.6 seemed to have changed the UI treatment for `choose-buffer` command.  Instead of showing the buffer contents inline for _all_ buffers like in v2.5

![image](https://user-images.githubusercontent.com/12662132/34796248-e693bc8a-f622-11e7-9808-95972a3798d8.png)

the content in v2.6 are now shown in the preview pane only for a _single_ buffer

![image](https://user-images.githubusercontent.com/12662132/34796281-044781f8-f623-11e7-8906-902aaf67249e.png)

This means I need to select every single buffer to find the correct buffer.

## Feature request

Could we have a way to restore the old UI treatment ... or come up with a solution that lets me quickly scan the contents of _all_ buffer at once?  Thanks.

## My setup:

```
$ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.6
screen
```

**Comment by nicm** [comment]
You can use -F and buffer_sample.

**Comment by hmak3d** [comment]
Thanks!  The [formats](https://leanpub.com/the-tao-of-tmux/read#formats) feature was exactly what I was looking for.  `choose-buffer -F "#{buffer_size} bytes: #{=60:buffer_sample}"` brings back the old look for me.

BTW, is there any way to format `buffer_created` as date string [like `choose-buffer` default output] instead of as number of seconds?

**Comment by nicm** [comment]
Use #{t:buffer_created} for a string.
