### ISSUE TITLE
feature request: rename socket

### ISSUE THREAD

**Issue by regisz** [tmux/tmux#1230]
Hi,

I tried to rename my tmux socket (`mv /tmp/tmux-my-user-id/my-tmux-socket_old /tmp/tmux-my-used-id/my-tmux-socket_new`), but after it the socket became broken. I could not attach to it.

It would be great, if an official command could be do this.

**Comment by nicm** [comment]
Why do you need to do this?

**Comment by regisz** [comment]
I use more sockets, because I have 2 bigger projects, and I would like to separate them (I use more sessions and windows, of course, in these sockets).
The name of one of my sockets was default (it is the name of the default socket), and I would have liked to rename it.

**Comment by nicm** [comment]
But you need to do this once right? Next time you will use the socket you
want from the start? I don't think we need to support this, it is needed
rarely.

**Comment by regisz** [comment]
Yes, you are right, it is a very rarely action, I think. But, I do not understand, why the socket became broken. Should I know any extra information for this operation?

**Comment by nicm** [comment]
Did you move it to a different partition?

**Comment by regisz** [comment]
no

**Comment by nicm** [comment]
Dunno then. If it ends up copy+unlink it won't work but I would have
thought a rename would.

**Comment by regisz** [comment]
I see, thx!
