### ISSUE TITLE
Searching word in copy-mode is too slow

### ISSUE THREAD

**Issue by Xeite** [tmux/tmux#1232]
Hello. When I entered in copy-mode and was trying to find any word, the word appeared too slowly.

I attached my tty screen [here](https://asciinema.org/a/6nNJqq6O0ZoUnGrBaZmJNQPvz)

as you see in here, I typed the word "Error", but it does not shown until 2~3 sec later. I understand there were many scroll lines and matching word for entire scroll buffer is very time consuming though, hope any workaround or advices.

My environment

Darwin i386
tmux 2.6
tmux-256color

set -g history-limit 1048576

Thanks!

**Comment by nicm** [comment]
Your history-limit is very big, try making it smaller.
