### ISSUE TITLE
tmux autostart bug

### ISSUE THREAD

**Issue by namkhaib** [tmux/tmux#1233]
I have a problem with autostarting tmux in fish shell. It's hard to explain, I attach a screenshot

![tmux](https://user-images.githubusercontent.com/33267474/34885897-5d8506ec-f78f-11e7-95fd-a8cc147964d3.png)

My command to start tmux in ~/.config/fish/config.fish

`test $TERM != "screen"; and exec tmux new-session -A -s $USER`

I think it's tmux, that don't read the actual size of the terminal on autostarting, because if I comment out this line in config.fish, and I run `tmux new-session -A -s $USER` _after_ logging to Konsole, this don't happen... I don't know how to solve it, I have already googled lots of time, and I found nothing.

Tmux version: 2.6.r98.g06684c93-1
Terminal: Konsole
OS: Manjaro up to date as 12/01/2018
$TERM inside tmux: screen
$TERM outside tmux: xterm-256color

To get the logs as in

>To run tmux without a config and get logs, run:
>
>    tmux -Ltest kill-server
>    tmux -vv -Ltest -f/dev/null new
>
>Then reproduce the problem, exit tmux, and attach the tmux-server-*.log file
>from the current directory to the issue.

I have runned `tmux -vv -Ltest -f/dev/null new` in config.fish, and it don't happens. I attach the logs and ~/.tmux.conf

[tmux-client-25713.log](https://github.com/tmux/tmux/files/1626829/tmux-client-25713.log)
[tmux-client-25909.log](https://github.com/tmux/tmux/files/1626830/tmux-client-25909.log)
[tmux-client-25949.log](https://github.com/tmux/tmux/files/1626831/tmux-client-25949.log)
[tmux-client-26012.log](https://github.com/tmux/tmux/files/1626832/tmux-client-26012.log)
[tmux-client-26041.log](https://github.com/tmux/tmux/files/1626833/tmux-client-26041.log)
[tmux.conf](https://github.com/tmux/tmux/files/1626838/tmux.txt)

**Comment by nicm** [comment]
Looks like these are only client logs you need to kill tmux to get the
server log.

**Comment by namkhaib** [comment]
@krader1961, fish version version 2.7.0

**Comment by namkhaib** [comment]
@nicm, if I put 

>tmux -Ltest kill-server
tmux -vv -Ltest -f/dev/null new

I get 
>error connecting to /tmp/tmux-1000/test (No such file or directory)
[server exited]

and tmux does not starts. And if I run tmux manually, the issue don't happens

**Comment by namkhaib** [comment]
@krader1961, I tested autostarting tmux in bash and changing shell to bash, and this don't happens. You're right, it's fish that does not read the terminal size correctly...
