### ISSUE TITLE
`clear`/`ctrl-l` don't work

### ISSUE THREAD

**Issue by dbarella** [tmux/tmux#1235]
Howdy y'all,

I'm having a heck of a time with this issue -- I've been on a documentation bender for the past hour at least, and at this point I think I have to give up and report a bug (or be proven silly, either way works).

## The Issue

![failed-clear](https://user-images.githubusercontent.com/1514497/34932720-0f84ed44-f9a2-11e7-9993-9c3665845420.png)

Pretty plain and simple, I can't get `clear`/`ctrl-l` to actually clear the screen -- the cursor will reset back to the top of the screen, but it seems that no redraw happens. I can trigger a redraw (completing the actual clear) by doing something like opening a split -- but on its own, nada.

I've attempted `tput reset; clear; commandline -f repaint` to no avail -- text remains on the screen.

## Repro

```
$ tmux -Ltest kill-server
no server running on /tmp/tmux-1000/test
$ tmux -vv -Ltest -f/dev/null new

# Now in tmux
$ echo $TERM
screen
$ clear

# Cursor resets to top of screen, but only clears the first line -- everything else persists.
<Ctrl-D>
[exited]
```

## Hypotheses
I believe that this is some arcane issue, possibly having to do with an interaction between `tmux` and `ncurses`. My reasoning:
 
- `clear`/`ctrl-l` both work fine outside of tmux
- The problem persists across several shells within tmux -- most notably `bash`, as well as `fish`

To this end, I tried to figure out if any `ncurses5` shared objects were being invoked where `ncurses6` ones should have been, but unfortunately I'm just a lowly backend systems programmer, so I wasn't really sure how to figure that out...

## System Info

- I'm running a Kubuntu (16.04.3 LTS) on a Lenovo Thinkpad X1 Carbon (5th Gen).
- I'm running `bash` and `fish-shell`. This problem occurs across both!
- All packages are up-to-date by apt -- I ran `sudo apt update && sudo apt upgrade` about an hour ago and still repro'd

Here's some data:
```
# Note: I'm using fish-shell to get this info

$ uname -sp; tmux -V; echo $TERM
Linux x86_64
tmux 2.6
xterm

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)                                                              
Copyright (C) 2013 Free Software Foundation, Inc.                                                                      
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>                                          
                                                                                                                       
This is free software; you are free to change and redistribute it.                                                     
There is NO WARRANTY, to the extent permitted by law.      
                                                            
$ fish --version
fish, version 2.7.1 

$ tmux
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
$ echo $TERM
screen
```

## Data

[tmux-server-3168.log](https://github.com/tmux/tmux/files/1630800/tmux-server-3168.log)

## Other Useful Reading

I found [this issue](https://github.com/fish-shell/fish-shell/issues/2855) enlightening, but couldn't find any pieces that I could easily apply to this problem.

**Comment by nicm** [comment]
Are you using Konsole?

**Comment by dbarella** [comment]
Yep! Is this some escape sequence trickery?

**Comment by nicm** [comment]
This is a bug in Konsole, https://bugs.kde.org/show_bug.cgi?id=379318, try upgrading Konsole or:

set -as terminal-overrides ',*:indn@'

**Comment by dbarella** [comment]
The terminal override works; I'm going to use that until a Konsole upgrade comes through the stable pipeline. Thanks for the tip!
