### ISSUE TITLE
{host} variable modified by a tpm plugin not showing in window-status-(current-)format

### ISSUE THREAD

**Issue by lcorsini** [tmux/tmux#1237]
Hello,
recently I've installed this TPM plugin:
https://github.com/soyuka/tmux-current-pane-hostname
which basically replaces the #H format variable with ssh hostname.
I've placed this variable inside window-status-format, and on my mac it works, but when using the same configuration on ubuntu 17.10 with tmux 2.6 that replacement get's ignored (leaving the local machine hostname)
If I move the #H in status-left or status-right it works fine.

The code of the plugin shows that it get's applied only on status-left or status-right, so it should be the correct behaviour (but on mac works fine, maybe because it's an older tmux or because of iterm?) 

I tried modify the code of the plugin (see snippet here)

```
update_tmux_option() {   
local option=$1
    local option_value=$(get_tmux_option "$option") 
    local new_option_value=$(do_interpolation "$option_value")   
main() { 
    update_tmux_option "status-right"   
    update_tmux_option "status-left"       
}  

```
adding something like:
`update_tmux_option "window-status-format"`
but tmux seems not liking that.
How can I get the plugin work as intended?
Do I need to run the script to change window title instead? 
what I want to achieve is to show on the statusbar the machine where I'm connected to

**Comment by nicm** [comment]
This is only the place for tmux issues, you will need to ask the plugin authors.

**Comment by lcorsini** [comment]
I know, but this seems a tmux issue to me (also have already asked plugin author)
why I can replace the #H format variable for status-left or status-right but not for window-status-current-format or window-status-format? is there some limitation? why on osx this seems to work but not on other platforms?

**Comment by nicm** [comment]
#H works fine for me in window-status-format and window-status-current-format for me, if you can reproduce without the plugin then provide logs etc as in the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.
