### ISSUE TITLE
Tmux displays some symbols after send -X copy-selection command

### ISSUE THREAD

**Issue by vfreefly** [tmux/tmux#1238]
![](https://hsto.org/webt/h5/if/kz/h5ifkz2__psipk6mebdwiq664ye.gif)

It looks like screen doesn't updates properly after copy command.
Because if I add `\; refresh` (`bind -T copy-mode-vi y send -X copy-selection \; refresh`), everything is ok.

Tmux config:
```
set -g mode-keys vi
bind -T copy-mode-vi y send -X copy-selection
```

Issue appears in Gnome terminal, Terminator, XFCE terminal (Ubuntu 16.04, 17.10).

---
Linux x86_64
tmux 2.6
screen-256color

**Comment by nicm** [comment]
You have TERM=xterm and set-clipboard on with a terminal that is not xterm.

**Comment by vfreefly** [comment]
I have TERM=screen-256color as you can see in issue desc above. 
Or do you mean what this is not a tmux problem?

**Comment by nicm** [comment]
That is inside tmux not outside.

Either use the right TERM outside tmux for your terminal, or turn off set-clipboard, or both.

**Comment by vfreefly** [comment]
Get it, thanks!
