### ISSUE TITLE
repeat-time usage

### ISSUE THREAD

**Issue by nickelchen** [tmux/tmux#1239]
hi, when I use tmux, I always want to increase repleat-time to elimate key-strokes for next few commands.
```
set -sg repeat-time 2000
```
and I use `H` `L` to select prev & next window, so hit `CTRL+b` `H` `H` `H` `H` within 2 seconds I can walk quickly to window I want.

problem is: within that 2 seconds, if I hit `CTRL+b` `H` again, the command did not respond, seems it's expecting `H` while not `CTRL+b` `H`

did I miss any settings ?  

Thank you!

**Comment by nickelchen** [comment]
@nicm  Thank you for your quick repsonse.

I tried and rebuilt it. without any luck, didn't work as I want.

**Comment by nickelchen** [comment]
Curiously I tested tmux tag 2.3, it has exactly the right behavior.

**Comment by nicm** [comment]
I don't understand what behaviour you expect, what exactly are you pressing?

**Comment by nickelchen** [comment]
Sorry for not describe clearly.

I press `CTRL+b`(holding them, actually holding CTRL is enough) `h` `h` `h` to cycle through windows. After I get my desired window, I release all the keys. In a **short time** , I regret and want to cycle windows again,  I press `CTRL+b` `h`, tmux 2.6 did not respond. while tmux 2.3 did respond.

It's indeed a strange workflow for what I did,  I hope I make it clear this time :) 

that **short time** as I tested, is likely the same as the `repeat-time` setting.

**Comment by nicm** [comment]
OK I see what you mean, if you press C-b during repeat time period it is
being treated as C-b and not as the prefix.

**Comment by nickelchen** [comment]
Thank you for pointing out the root cause of my problem. 

if I set `repeat-time` to `1ms`, I can cycle through windows again after releasing those keys. but it introduce another problem, that I cannot use `CTRL+b``h``h``h` to quickly switching windows.

**Comment by nicm** [comment]
You can try this, but I think it was changed for a reason, so I'll need
to figure out why that was:

Index: server-client.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/server-client.c,v
retrieving revision 1.246
diff -u -p -r1.246 server-client.c
--- server-client.c	19 Dec 2017 15:00:39 -0000	1.246
+++ server-client.c	25 Jan 2018 08:50:55 -0000
@@ -907,6 +907,7 @@ server_client_handle_key(struct client *
 	 * The prefix always takes precedence and forces a switch to the prefix
 	 * table, unless we are already there.
 	 */
+retry:
 	key0 = (key & ~KEYC_XTERM);
 	if ((key0 == (key_code)options_get_number(s->options, "prefix") ||
 	    key0 == (key_code)options_get_number(s->options, "prefix2")) &&
@@ -917,7 +918,6 @@ server_client_handle_key(struct client *
 	}
 	flags = c->flags;
 
-retry:
 	/* Log key table. */
 	if (wp == NULL)
 		log_debug("key table %s (no pane)", table->name);

**Comment by nickelchen** [comment]
Thank you!!  that patch works!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
