### ISSUE TITLE
Feature Request: Search word under cursor by pressing "*" in "vi" search mode

### ISSUE THREAD

**Issue by artem-nefedov** [tmux/tmux#1240]
In vi/vim. one of the commonly used search methods is pressing `*` to search next occurrence of the word under cursor. Consider making it default behavior in tmux if `mode-keys` is set to `vi`.

**Comment by nicm** [comment]
Added to TODO file.

**Comment by nicm** [comment]
This was added by https://github.com/tmux/tmux/pull/1945 and https://github.com/tmux/tmux/pull/1964.
