### ISSUE TITLE
usage: bind-key [-cnr] [-T key-table] key command [arguments]

### ISSUE THREAD

**Issue by pengyu** [tmux/tmux#1242]
I got the following message. Does anybody know what is wrong? Thanks.

```
/home/py/.tmux.conf:33: usage: bind-key [-cnr] [-T key-table] key command [arguments]                                                                                                                                                             [0/0]
```

And line 33 of `~/.tmux.conf` is

```
bind-key -t vi-copy 'v' begin-selection
```

My tmux version is

```
$ tmux -V
tmux 2.6
```

**Comment by nicm** [comment]
The syntax to bind-key has changed, see https://github.com/tmux/tmux/blob/master/CHANGES#L235

**Comment by pengyu** [comment]
@nicm I'm not sure how to make the change. Could you please let me know the command for the new version of tmux equivalent to `bind-key -t vi-copy 'v' begin-selection`? Thanks.

**Comment by nicm** [comment]
bind -Tcopy-mode-vi v send -X begin-selection

**Comment by ethagnawl** [comment]
> The syntax to bind-key has changed, see https://github.com/tmux/tmux/blob/master/CHANGES#L235

This URL no longer points to the relevant portion of CHANGES. I believe [this](https://github.com/tmux/tmux/blob/7a1abd66e7f38412f4bdc944d969e88d6b268a13/CHANGES#L571-L596) is the entry which was originally referenced.
