### ISSUE TITLE
Dynamically linking to util

### ISSUE THREAD

**Issue by NickeZ** [tmux/tmux#1244]
I'm trying to build tmux on a machine I don't control. I think my problem is that `util` is only available as a dynamic library and gcc is called with `-static` when it checks if it can find `forkpty`. If this is the problem, could it be possible to change `configure.ac` so that one can statically link **only** the non-system libraries? 

Using latest master of tmux and latest stable versions of ncurses and libevent.

```
#libevent
./configure --prefix=$HOME/.local

# ncurses
./configure --enable-pc-files --enable-symlinks --with-termlib --prefix=$HOME/.local --with-pkg-config=$HOME/.local/lib/pkgconfig

# tmux
./configure PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig --enable-static --prefix=$HOME/.local
```

```
configure:9447: checking for library containing forkpty
configure:9488: gcc -std=gnu99 -o conftest  -D_GNU_SOURCE   -I/<>/user/c/claesson_n/.local/include      -static   conftest.c  -L/<>/user/c/claesson_n/.local/lib -ltinfo   -L/<>/user/c/claesson_n/.local/lib -levent -lcrypto -lrt    >&5
/usr/bin/ld: cannot find -lcrypto
collect2: ld returned 1 exit status
configure:9495: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "tmux"
| #define PACKAGE_TARNAME "tmux"
| #define PACKAGE_VERSION "master"
| #define PACKAGE_STRING "tmux master"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE "tmux"
| #define VERSION "master"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define __EXTENSIONS__ 1
| #define _ALL_SOURCE 1
| #define _GNU_SOURCE 1
| #define _POSIX_PTHREAD_SEMANTICS 1
| #define _TANDEM_SOURCE 1
| #define HAVE_DIRENT_H 1
| #define HAVE_FCNTL_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_PATHS_H 1
| #define HAVE_PTY_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_SYS_DIR_H 1
| #define HAVE_NCURSES_H 1
| /* end confdefs.h.  */
|·
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char forkpty ();
| int
| main ()
| {
| return forkpty ();
|   ;
|   return 0;
| }
configure:9488: gcc -std=gnu99 -o conftest  -D_GNU_SOURCE   -I/<>/user/c/claesson_n/.local/include      -static   conftest.c -lutil   -L/<>/user/c/claesson_n/.local/lib -ltinfo   -L/<>/user/c/claesson_n/.local/lib -levent -lcrypto -lrt    >&5
/usr/bin/ld: cannot find -lutil
collect2: ld returned 1 exit status
configure:9495: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "tmux"
| #define PACKAGE_TARNAME "tmux"
| #define PACKAGE_VERSION "master"
| #define PACKAGE_STRING "tmux master"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE "tmux"
| #define VERSION "master"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define __EXTENSIONS__ 1
| #define _ALL_SOURCE 1
| #define _GNU_SOURCE 1
| #define _POSIX_PTHREAD_SEMANTICS 1
| #define _TANDEM_SOURCE 1
| #define HAVE_DIRENT_H 1
| #define HAVE_FCNTL_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_PATHS_H 1
| #define HAVE_PTY_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_SYS_DIR_H 1
| #define HAVE_NCURSES_H 1
| /* end confdefs.h.  */
|·
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char forkpty ();
| int
| main ()
| {
| return forkpty ();
|   ;
|   return 0;
| }
configure:9526: result: no
```

I also had to create this file to detect libtinfo (ncurses didn't create it by itself).
```
$ cat ../../.local/lib/pkgconfig/tinfo.pc
# pkg-config file generated by gen-pkgconfig
# vile:makemode
prefix=/afs/psi.ch/user/c/claesson_n/.local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
abi_version=6
major_version=6
version=6.0.20180121
Name: tinfo
Description: ncurses 6.0 library
Version: ${version}
URL: https://invisible-island.net/ncurses
Requires.private:
Libs:  -L${libdir} -ltinfo
Libs.private:
Cflags:  -D_GNU_SOURCE
```

**Comment by nicm** [comment]
Why don't you just modify configure or configure.ac yourself?

**Comment by NickeZ** [comment]
I found this comment but I didn't understand how to implement it. I have never written any autotools files before so it would take me weeks to implement it.

> However, for something fancy, you could pull the flags into your configure.ac. Once there, you could add DYNLIBS="-Wl,-Bdynamic,-L/path/to,-lshared,-Bstatic" with a call to AC_SUBST([DYNLIBS]). Then all you'd need to do is call $(DYNLIBS) in your Makefile.am. This would give you a more control, but remember that AC_CHECK_LIBS doesn't check for static vs. dynamic libs. Is that what you want or is there something else that would make it more flexible?

https://stackoverflow.com/questions/13997415/how-can-an-autotools-user-specify-a-combination-of-static-dynamic-linking#14027512

I have tmux running with `LD_LIBRARY_PATH=$HOME/.local/lib` for now. If you don't have the time to implement this feature you can close the issue.

**Comment by nicm** [comment]
You want configure to use static libraries except for libutil so you are going to need to go into configure and eg change the libutil test so it always passes.

We aren't going to change this for everyone because normally you want a static libutil.

**Comment by NickeZ** [comment]
I thought statically linking to libc wasn't recommended.

**Comment by nicm** [comment]
libutil is not libc.

**Comment by nicm** [comment]
Right but libc is a special case not libutil. We want to link against libutil statically. Why don't you just edit configure?

**Comment by NickeZ** [comment]
> Why don't you just edit configure?

Because I don't know what changes to make and I haven't been able to figure it out.

**Comment by nicm** [comment]
Find the bit that says something like "checking for library containing forkpty" then remove the check up until the "if test "x$found_forkpty" = xyes" bit and just force found_forkpty=yes.

I think you are going to have problems with libcrypto as well judging by your output. You can probably build libevent without ssl support to avoid that though.

I expect you will also need to fiddle with the generated Makefile but I don't know what you will need to change there.

Can't you build a static build on a system where you do have root and then copy it over?

**Comment by NickeZ** [comment]
I guess I need the exact same environment as the target system (linux kernel and libc) so this doesn't really scale for me. My plan is to have a script I can run on systems which I don't own. This use case is nothing you want to support and I respect that.

I can use my LD_LIBRARY_PATH hack, thanks for trying to help me!

**Comment by nicm** [comment]
You shouldn't need the exact same environment for a static build, just a libc that is the same or newer.

**Comment by chros73** [comment]
@devs: I "finished" my small but powerful [build script](https://github.com/chros73/build-tmux) (along with `tig` and `mc` build script), take a look, maybe you also like it. It can be used for development as well, just drop in patches and modify the version number.
Maybe I'll update the readme later with more info.

Thank You, guys, for this amazing project!

@NickeZ: unfortunately there's no support static linking in it. If you like it, you can modify it to include those (we can move the conversation over there).
