### ISSUE TITLE
[memory]show mem used info of each window

### ISSUE THREAD

**Issue by jinleileiking** [tmux/tmux#1248]
After 1 month runing tmux. 

My rss is: 91g. And I have 30 seesions.

I cannot locate new tmux window.

I do not know which session(window) should I close.

I need a way to find out which mem-killer should I close.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by jinleileiking** [comment]
I update tmux. When I got this problem. I will reopen
