### ISSUE TITLE
Very slow reflow with large histories

### ISSUE THREAD

**Issue by da-x** [tmux/tmux#1249]
I experience very slow reflows with branch `master`, in standard compilation.

The logs show this with '-v':

```
1517228652.728874 grid_reflow: 198487 lines, new width 84
1517228685.060572 grid_reflow: now 327153 lines (in 32.331704 seconds)
1517228685.060605 grid_reflow: 53 lines, new width 83
1517228685.060613 grid_reflow: now 53 lines (in 0.000009 seconds)
1517228696.923647 grid_reflow: 327153 lines, new width 168
1517228764.131449 grid_reflow: now 198487 lines (in 67.207795 seconds)
1517228781.930553 grid_reflow: 198487 lines, new width 84
1517228813.779507 grid_reflow: now 327153 lines (in 31.848961 seconds)
1517228813.779534 grid_reflow: 53 lines, new width 83
1517228813.779541 grid_reflow: now 53 lines (in 0.000006 seconds)
1517228826.859557 grid_reflow: 327153 lines, new width 168
1517228891.105501 grid_reflow: now 198487 lines (in 64.245937 seconds)
```

History is the truncated output of `find /` on my PC.

A whole minute or half a minute where tmux is completely frozen is way too long to reflow 200,000 ASCII lines, IMHO.

Perf callgraph output:

```
    99.91%     0.08%  tmux: server  tmux                   [.] grid_reflow_join
            |          
             --99.83%--grid_reflow_join
                       |          
                        --99.62%--__memmove_avx_unaligned_erms
```

And:

```
     0.15%     0.04%  tmux: server  tmux                   [.] grid_set_cell
     0.11%     0.03%  tmux: server  tmux                   [.] grid_expand_line
     0.06%     0.00%  tmux: server  tmux                   [.] xreallocarray
     0.05%     0.04%  tmux: server  libc-2.26.so           [.] realloc
     0.04%     0.04%  tmux: server  tmux                   [.] grid_get_cell1
     0.03%     0.03%  tmux: server  [kernel.kallsyms]      [.] native_irq_return_iret
     0.02%     0.02%  tmux: server  tmux                   [.] grid_clear_cell.isra.3
     0.01%     0.01%  tmux: server  tmux                   [.] memmove@plt
     0.01%     0.01%  tmux: server  tmux                   [.] utf8_set
     0.01%     0.01%  tmux: server  tmux                   [.] grid_need_extended_cell.isra.0
     0.01%     0.01%  tmux: server  libc-2.26.so           [.] _dl_find_dso_for_object@plt
     0.01%     0.01%  tmux: server  libc-2.26.so           [.] _int_realloc
```

So almost the entire time is spent in `memmove`.

**Comment by nicm** [comment]
What if you build with --disable-debug?

**Comment by da-x** [comment]
I see no difference with or without `--disable-debug`.

Git bisect suggest either 533a5719c5edf53f0d7021d4340af230cc43ac8a, aeda2e5808af7c4b629dce23d2b4331a77ecde83 or e755ca37b339ac2960f753eff4470c3b68f4b223 as the culprits.

On 2357bfb2545509f0b449ddf0519b6a638bfcf351, the reflow in the same scenario was almost immediate.

**Comment by nicm** [comment]
Right but the old code didn't handle UTF-8 characters at all really, so we aren't going back to it.

**Comment by nicm** [comment]
This came up before and I had some ideas, let me see if I can find the issue.

**Comment by nicm** [comment]
Oh yeah, it was you in https://github.com/tmux/tmux/pull/1147 and we turned off reflow when the horizontal size did not change.

1m30s sounds excessive, although it does have to do quite a lot of work. It is such a pain in the arse to get reflow right that there probably is scope to make it faster.

When we did not handle UTF-8 we could copy multiple cells at once, but now we need to know the width which means every cells has to be at least inspected. We both inspect and copy though, so it would probably be faster to copy in bulk instead of one by one, by calculating the number of characters that can fit in the width first and then copying. So the loop in grid_reflow_join ("Join as much more as possible onto the current line") would just count and then do single realloc+memcpy.

It might also be possible to collect together cells which have the same attributes (perhaps remember a whole line using a line flag), and copy the whole line or at least sets of cells.

**Comment by nicm** [comment]
Of course that will only speed up one pane, so if you have multiple panes with 200k+ history you will need some of the ideas I mentioned before.

**Comment by da-x** [comment]
Yes, I seem to have accumulated a history with tmux (pun intended :)

Thanks for the pointers. I think perhaps even one pane would be good enough for now.

Also, maybe there can be a compile-time or run-time option to turn off UTF-8 support for reflow so that the faster algorithm can be easily implemented in that case? I rarely use UTF-8 chars in the terminal on the day-to-day.

**Comment by nicm** [comment]
It does seem to scale quite badly for both split and join. 50000 lines is about 9 (split) and 5 (join) seconds but 100000 is 41 (split) and 86 (join) seconds:
~~~~
N=100000
tmux set -g history-limit $N
W=$(tmux neww -P)
tmux send -t$W "find /|head -$N" Enter
tmux send -t$W "# SPLIT" Enter
tmux send -t$W "time tmux set -g force-width 25" Enter
tmux send -t$W "# JOIN" Enter
tmux send -t$W "time tmux set -g force-width 0" Enter

**Comment by nicm** [comment]
I tried collecting the cells together and using grid_set_cells and it didn't really help. I think it would need to do an actual batch memcpy but it can't memcpy anything that might be an extended cell because the extended cell offset would be different.

**Comment by nicm** [comment]
I thought this would help but it only takes off a few seconds, I think need to do more profiling: 
[tmux-reflow1.diff.txt](https://github.com/tmux/tmux/files/1673798/tmux-reflow1.diff.txt)

**Comment by nicm** [comment]
OK so it looks like the time is not spent where I thought but in fact in removing lines that are no longer present. That is if we have lines A,B,C,D,E we join to give ABC,B,C,D,E then move D,E up to get ABC,D,E.

**Comment by nicm** [comment]
I think we need to go back to doing this by copying to a new grid (well, to a new linedata would be better). Doing it in place requires too much shifting of existing lines. But we need to handle wide characters.

**Comment by nicm** [comment]
Try this please: [tmux-reflow-moar-faster.diff.txt](https://github.com/tmux/tmux/files/1688743/tmux-reflow-moar-faster.diff.txt)

**Comment by da-x** [comment]
Tested it and it looks good, thanks

**Comment by nicm** [comment]
Applied now, thanks.
