### ISSUE TITLE
AC_INIT(tmux, master)?

### ISSUE THREAD

**Issue by sebastianganson** [tmux/tmux#1250]
Hi, I noticed when I compiled and ran tmux -V that it gave 'master' as the version.  Should the line in configure.ac be AC_INIT(tmux, 2.6)?

Thanks

**Comment by nicm** [comment]
Apparently you did not build 2.6, you built master.

**Comment by sebastianganson** [comment]
That would explain it (facepalm).  Thanks

**Comment by chros73** [comment]
You can try [this](https://github.com/chros73/build-tmux) out if you want to use master (or any commit):
- it will modify the version number, hence you won't get a debug build

**Comment by sebastianganson** [comment]
Thanks, @chros73 - I'll take a look.
