### ISSUE TITLE
Makes life too easy

### ISSUE THREAD

**Issue by Ganneff** [tmux/tmux#1251]
YOU MUST INCLUDE THE TMUX VERSION

2.6

DO NOT OPEN AN ISSUE THAT DOES NOT MENTION THE TMUX VERSION

Previously 2.3 and way off started with 1.something. All versions affected!

Please also include:

- your platform (Linux, OS X, or whatever);

Linux, not hurting myself with others.

- a brief description of the problem with steps to reproduce;

It works too good. Reproducable by just using it.

- a minimal tmux config, if you can't reproduce without a config;

Only the following, without it it just hurts. C-b, seriously?

unbind C-b
set -g prefix ^A
bind a send-prefix

- your terminal, and $TERM inside and outside of tmux;

rxvt-unicode

- logs from tmux (see below);

Nono.

- at most one or two screenshots, if helpful.

Nono.

Please do not report bugs (crashes, incorrect behaviour) without reproducing on
a tmux built from Git master.

I'm sure it will have the same _problem_, no need.

Boilerplate done, now the real content:

Thanks for tmux, it's a **GREAT** tool and a **LOAD** of help in daily
administrative work over all our (tons of) machines.

With my https://github.com/Ganneff/tm i usually have something between
70 and 90 tmux sessions in LOADS of different window/pane configs open
(sometimes up to 200 panes in one window, with synchronized input to
all).

The scriptability, the ease of multiple sessions, moving/reattaching
panes and windows, break em up, join again, lalala, loads of paste
buffers, etc, it makes life so much easier.

And the new choose-tree with searching in the mass of sessions even
makes the load I have in tmux bearable.

And it really helps to say "Just type tm $foo.cfg and tm and tmux give
you the right view" to colleagues.

So, instead of a bug, this is a **THANKS FOR TMUX** issue. I know that
(especially) open source projects usually just get yelled at when they
don't work, and seldom get to hear a thanks, and as I just had someone
sit beside me again being impressed in how it all works, I thought of
passing that on. Wouldn't have had that without your work.

Keep it up, we really like it!

**Comment by nicm** [comment]
OK thanks.
