### ISSUE TITLE
Feature request: golden ratio toggle

### ISSUE THREAD

**Issue by vbauerster** [tmux/tmux#1255]
I'd like to propose to have a `golden-ratio` toggle option in tmux. By `golden-ratio` I mean active (just focused) pane should resize itself automatically, in order to be the largest pane in size among others. Following screenshots illustrate `golden-ratio` behaviour in `spacemacs` editor. I often find myself manually resizing panes to `golden-ratio` pattern, which takes some not necessarily long time for a single pane context switch, but when pane context switch happens often (and it happens often during a session), it becomes very tedious to resize panes in manual mode.
[![pane1.png](https://s25.postimg.org/gfx2pdxan/pane1.png)](https://postimg.org/image/gsogvkfkb/)
[![pane2.png](https://s25.postimg.org/x3okrvzrz/pane2.png)](https://postimg.org/image/6im1wbxej/)
[![pane3.png](https://s25.postimg.org/mtm5snhm7/pane3.png)](https://postimg.org/image/rfia10357/)
Sorry in advance, if it's not right place to make feature request.

**Comment by nicm** [comment]
If you write code for a new builtin layout I'll look at it, but this should be easy to script so it would be better to do that instead.

**Comment by chros73** [comment]
> this should be easy to script 

Really? :) I'm also curios about the scripting part, but I'm not good at it. :(

**Comment by nicm** [comment]
I would start from select-layout main-vertical then use resize-pane to adjust the sizes how you want, you can get a list of panes with something like tmux lsp -F '#{pane_index} #{pane_id}' (after selectl main-vertical, the left pane should always be 0) and the full width and height with for example display -p '#{session_width}'.

Or see if there is an existing script like https://sunaku.github.io/tmux-layout-dwindle.html.

**Comment by chros73** [comment]
Thanks @nicm for the idea and the link! I'll try it out today, it's just insane! :)

**Comment by mattkatz** [comment]
@chros73 sorry to comment on an old issue but I had the same idea and the same thought and found this thread. Did you ever get a goldenratio layout script working?

**Comment by sunaku** [comment]
For starters, try changing [this line](https://github.com/sunaku/home/blob/master/bin/tmux-layout-dwindle#L276) to divide by the golden ratio (instead of 2):
```sh
branch_height=$(echo "( $branch_height / 1.618 ) / 1" | bc)
```
This doesn't make widths golden though :stuck_out_tongue_winking_eye:, that's left as an exercise for you.
