### ISSUE TITLE
join-pane doesn't work when joining to first window

### ISSUE THREAD

**Issue by nabn** [tmux/tmux#1256]
version: 2.5
platform: Darwin i386

Desc: When attempting to `join-pane` any other pane to first window, such as `join-pane -s 1 -t 0` tmux fails with message "can't join a pane to its own window". This works fine for any other window(3 to 2, 2 to 3, etc) but not for 1 to 0 or 2 to 0.

terminal: iTerm(beta)
$TERM: screen-256color

**Comment by nabn** [comment]
(P.S. I tried to take a crack at it, but my experience working with C is pretty much non-existent.)

**Comment by nicm** [comment]
A plain 0 for target-pane will look for pane 0 not window 0, use :0 if you want window 0.
