### ISSUE TITLE
pane_current_path missing in openbsd tree?

### ISSUE THREAD

**Issue by nanaya** [tmux/tmux#126]
Not sure if this is the appropriate place but [this commit](https://marc.info/?l=openbsd-cvs&m=138140881419937&w=2) removed `pane_current_path` formatting variable and stayed that way and thus the variable is missing in openbsd.

I tried compiling the github one (in openbsd 5.7) and the functionality seems to be working fine.

What's the reason it's removed in openbsd tree version?

**Comment by nanaya** [comment]
From searching the list it seems to be ["unpredictable behavior"](`https://marc.info/?l=openbsd-cvs&m=138098142428789&w=2). Is it still the case? The removal is since two years ago but the sysctl is still there

**Comment by nicm** [comment]
It was removed from OpenBSD because of concerns about its
unpredictability, it won't be returning.
