### ISSUE TITLE
utmp records are potentially dangerous

### ISSUE THREAD

**Issue by elenril** [tmux/tmux#1260]
I reported this in Debian some time ago as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879515 but it's been ignored there, so I thought I'd raise it here as well.

In short, I think the utmp records created by tmux are potentially dangerous, since it uses the "hostname" field for something that
- is not a hostname
- contains information about the system - the PID and window ID
Some system tools can then try to resolve this "hostname", spamming the DNS with bogus requests and leaking system information. What makes this more aggravating is that this behaviour is decided at compile time and cannot be disabled at run time.

Do you consider this a valid bug? If so, any thoughts on the best way of resolving it? What comes to mind is at least making this runtime-configurable and/or changing the record format.

**Comment by nicm** [comment]
PIDs are not secret and nor are tmux window IDs, any more than the tty is secret.

There is no guarantee that the utmp hostname field will be a valid, resolvable hostname and any tool that depends on this is making a mistake.

**Comment by elenril** [comment]
PIDs are not secret provided you have access to the system. I would argue that broadcasting them to the whole world (plus the fact that someone is running tmux on the system) is, while not a giant horrible leak, at least undesirable.

As for your second comment - I certainly agree that those tools should be more careful. But the sad fact of life is that they are not - from what I can see (http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/who.c#n374) GNU coreutils *who* and *pinky* have had code for resolving the hostname field for something like 20 years now.

**Comment by nicm** [comment]
I don't really see what you are worried about here.

tmux doesn't do this by default, you have to build with --enable-utempter.

PIDs are not secret. utmp is not broadcast anywhere by default and if you are showing it to users who can't see it themselves, then the tmux server PIDs are not the most useful thing you are revealing.

Users who can normally see utmp can - without measures to stop them - probably figure out if tmux is running in several other ways if they feel like it.

There are several ways that non-hostname data can appear in hostname (not least, from X). I don't think programs should assume the hostname must be resolvable. Yes, GNU who has code to resolve it, but it doesn't do it by default.

**Comment by elenril** [comment]
This is not a purely theoretical problem, I actually got complaints from my local netadmin about my machine spamming bogus DNS requests. The details are that some scripts in debian acpi-support invoke pinky, pinky reads utmp and tries to "resolve" the hostname from there. Hilarity ensues.

> tmux doesn't do this by default, you have to build with --enable-utempter.

Which at least Debian does. Compiling a local tmux build (with all the associated maintenance fun) is not exactly nice.

> There are several ways that non-hostname data can appear in hostname (not least, from X). I don't think programs should assume the hostname must be resolvable. Yes, GNU who has code to resolve it, but it doesn't do it by default.

The GNU tools have special detection for X data - which is an ugly hack as far as I'm concerned, but that's the way it is.

**Comment by nicm** [comment]
It would have been simpler to explain this at the start.

Anyway, there doesn't seem to be anything practical we can do here, because I don't see a way to stop the GNU tools trying to resolve. Even if it contains a colon, they will still try to resolve part of the string. I don't think we should make tmux put a colon at the start. And making the hostname field blank makes the utmp entries pretty useless.

I think you will need to talk to the Debian maintainer about building without utempter, or to the script authors about using pinky -i, or to GNU about adding some better validation.

Personally I would ask about the scripts first because there is surely no need for them to be doing DNS lookups all the time, valid or not.

**Comment by elenril** [comment]
The things that can be done about this in tmux are IMO:
- make utmp entries runtime-configurable. Or is there some reason that is undesirable/hard to do?
- as you mention, prepend a colon to the string. Ugly but workable.

**Comment by nicm** [comment]
Whether or not to write into utmp is a decision for the sysadmin not for users, it can't be runtime configurable.

We're not going to prepend a colon.

**Comment by nicm** [comment]
Actually I just remembered someone asked how to disable utempter without recompile before, and I am pretty sure you can do it by making the utempter binary non-executable. /usr/lib/x86_64-linux-gnu/utempter/utempter I think on 64-bit Debian.

**Comment by elenril** [comment]
> Whether or not to write into utmp is a decision for the sysadmin not for users, it can't be runtime configurable.

I think the root can't force the users to get utmp entries in this way, since the user can always run tmux with their custom libutempter LD_PRELOADed. So runtime configuration doesn't allow anything not possible through other means, it just makes it more user-friendly.

>  you can do it by making the utempter binary non-executable.

I suppose that also works, though again one has to remember to do this every single time libutempter is updated.

**Comment by nicm** [comment]
I think the existing possibilities are enough for this.

**Comment by signe** [comment]
> Whether or not to write into utmp is a decision for the sysadmin not for users, it can't be runtime configurable.

Then how does screen do it?  The decision for whether to include each screen in utmp can be toggled not only by base configuration, but also at whim, by using the 'deflogin' (in .screenrc, setting the default for all new windows) and 'login' (as a : command for an individual window).

I personally turn them off because having 25+ utmp entries listing each and every window and their currently running commands is obnoxious when I look to see who's logged into the system.
