### ISSUE TITLE
tmux leaks memory after running for a few weeks

### ISSUE THREAD

**Issue by TomasTomecek** [tmux/tmux#1261]
Hi, this is a tough one. I use recent version of tmux on my machines and after running for a couple of weeks, it starts to leak memory and use CPU substantially. After reading the contrib guidelines, I compiled git master (88711e8) and ran it for a ~week (showing also systemd just for comparison):

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND                                                                                                    
root         1  0.0  0.8  33808  8652 ?        Ss   Jan29   0:44 /usr/lib/systemd/systemd --switched-root --system --deserialize 24 
tt       21943  2.6  8.4  90992 83764 ?        Rs   Feb12 248:51 tmux -2
```

This tmux session holds just an IRC client (weechat) and that's it. Here is my [.tmux.conf](https://github.com/TomasTomecek/dotfiles/blob/master/tmux/.tmux.conf)

This is my raspberry pi (Fedora 27) but the same thing is happening on x86_64, Fedora 27 (tmux 2.5), running only htop. After running tmux for a month, I need to restart it because the performance impact is so heavy.

Now that I am thinking about it. Since I set pretty big history-limit: could it be a problem that if the interactive terminal app is running for quite some time, it eats a lot of memory due to the big limit?
```
set -g history-limit 200000
```

**Comment by nicm** [comment]
Full-screen interactive programs should usually not have a history at all - history is disabled in cursor positioning mode. What does this show?
~~~~
tmux lsp -aF '#{history_bytes}'
~~~~

**Comment by TomasTomecek** [comment]
```
$ tmux lsp -aF '#{history_bytes}'
2230
0
```

**Comment by nicm** [comment]
Can you reproduce without a config?

**Comment by TomasTomecek** [comment]
I can definitely try, but it will take me a ~week to get back.

**Comment by nicm** [comment]
This is a very big config for someone just running weechat?

I would try just commenting out status-left/status-right and anything else using #() and see if the problem goes away.

**Comment by TomasTomecek** [comment]
It's my default config I use everywhere. Didn't think all these options would actually waste resources so much -- can definitely create something smaller for weechat/htop.

After few hours, I am getting loadavg 0.00 for all 3 segments -- looks way better.

**Comment by nicm** [comment]
No the options shouldn't make any difference to memory use really but it is hard to track down what the problem is when you have so many.

Does it happen if you just comment out the status-left/status-right bits?

**Comment by TomasTomecek** [comment]
trying right now, will report tomorrow; thanks a lot for help

**Comment by TomasTomecek** [comment]
@nicm I think you hit the nail on the head. It's running for a ~day now and there is no performance regression:
```
$ cat /proc/loadavg
0.00 0.00 0.00 1/108 3736

$ ps aux | grep tmux
tt        3101  0.0  0.2   3812  2444 pts/1    S+   Feb19   0:00 tmux -2
```

Does it mean that status-{left,right} leak memory?

**Comment by nicm** [comment]
What is in your tmux-top script?

**Comment by TomasTomecek** [comment]
@nicm it's a golang binary: https://github.com/TomasTomecek/tmux-top

**Comment by TomasTomecek** [comment]
Exactly. But the line is not terminated with a newline (as I can see now):

```
$ tmux-top n
#[bg=default,fg=white]E#[bg=default,fg=default] #[bg=default,fg=colour4]10.43.12.139/24#[bg=default,fg=default] #[bg=default,fg=white]W#[bg=default,fg=default] #[bg=default,fg=green]10.200.153.114/21#[bg=default,fg=default]

$ tmux-top io  # there was no I/O

$ tmux-top l
#[bg=default,fg=green]0.41#[bg=default,fg=default] #[bg=default,fg=green]0.64#[bg=default,fg=default] #[bg=default,fg=green]0.69#[bg=default,fg=default]%

$ tmux-top m
#[bg=default,fg=green]8.17GB#[bg=default,fg=default]#[bg=default,fg=white]/#[bg=default,fg=default]#[bg=default,fg=colour14]11.43GB#[bg=default,fg=default]%
```

**Comment by nicm** [comment]
If you put the status-left and status-right back and run it for a bit, then look at output of "tmux showmsgs -J", what does it say?

**Comment by nicm** [comment]
Does this fix it? [tmux-leak.diff.txt](https://github.com/tmux/tmux/files/1739745/tmux-leak.diff.txt)

**Comment by TomasTomecek** [comment]
```
$ ~ tmux showmsgs -J
Job 0: tmux-top n [fd=16, pid=21366, status=0]
Job 1: tmux-top n [fd=9, pid=21357, status=0]
Job 2: tmux-top i [fd=14, pid=21356, status=0]
Job 3: tmux-top i [fd=10, pid=21337, status=0]
$ tmux showmsgs -J
Job 0: tmux-top n [fd=16, pid=21795, status=0]
Job 1: tmux-top n [fd=9, pid=21786, status=0]
Job 2: tmux-top i [fd=14, pid=21766, status=0]
Job 3: tmux-top i [fd=10, pid=21751, status=0]
$ tmux showmsgs -J
Job 0: tmux-top n [fd=9, pid=22046, status=0]
Job 1: tmux-top i [fd=14, pid=22030, status=0]
Job 2: tmux-top i [fd=10, pid=22011, status=0]
Job 3: tmux-top n [fd=16, pid=22006, status=0]
$ tmux showmsgs -J
Job 0: tmux-top n [fd=16, pid=22209, status=0]
Job 1: tmux-top n [fd=9, pid=22196, status=0]
Job 2: tmux-top i [fd=14, pid=22177, status=0]
Job 3: tmux-top i [fd=10, pid=22165, status=0]
```

trying the patch, will report in a few hours

**Comment by nicm** [comment]
I have applied the patch because it is definitely needed; I don't see any other significant leaks though. Let me know if you still see the problem.

**Comment by TomasTomecek** [comment]
After a few hours, the memory usage is low. I would say it's fixed and we can close.

(the cpu usage is still higher than it should be: after a bit of searching I think it's because of https://github.com/tmux/tmux/issues/797#issuecomment-283269499; I'm going to fix it in tmux-top)

@nicm Thank you very much! You are an exemplar open source maintainer!

**Comment by TomasTomecek** [comment]
(just a small update: running for a week now, no memory is leaking; good job and thank you!)
