### ISSUE TITLE
tmux server crashes under st+nvim

### ISSUE THREAD

**Issue by 5paceToast** [tmux/tmux#1265]
- `tmux -V` : `tmux 2.6`, `tmux master`
- platform: Arch Linux (latest, Feb 26 2018), 4.15.3-2-ARCH
- reproducible without config?
- TERM outside tmux: `st-256color`
- TERM inside tmux: `tmux-256color`

### Steps to reproduce
```sh
st
# within st
tmux -f/dev/null # can be modified arbitrarily
# within tmux
nvim -u NORC # -u NORC disables configuration in neovim
```

### Expected behavior
Neovim opens in tmux, running over st.

### Actual behavior
- The entire tmux server crashes.
- St is now messed up (e.g `\n` doesn't function as expected).

### Logs
[tmux-client-15062.log](https://github.com/tmux/tmux/files/1745582/tmux-client-15062.log)
[tmux-out-15064.log](https://github.com/tmux/tmux/files/1745585/tmux-out-15064.log)
[tmux-server-15064.log](https://github.com/tmux/tmux/files/1745586/tmux-server-15064.log)

### Why here?
This could be a variety of things, but I'm reporting the bug here first, for the following reasons:
1. This *only* happens with st+tmux. Switching the terminal makes the issue disappear.
  This doesn't happen with classic vim, potentially because it uses a different mechanism for terminal capability probing.
2. st+tmux as a combination is already known to have occasional issues (e.g see https://github.com/zyedidia/micro/issues/1047 ).
3. This wasn't the case previously.
4. tmux (ideally) shouldn't care what terminal is behind it (see following section).

Unfortunately re: 3 I'm not sure which got updated or changed, but I haven't had this happen previously. I was initially going to report this to neovim (and I still might), but since switching out the backing terminal doesn't reproduce the problem, and neovim has no way of knowing what's behind tmux (as far as I'm aware) starting here seemed more appropriate.

**Comment by nicm** [comment]
See https://github.com/tmux/tmux/issues/1264
