### ISSUE TITLE
`can_change_color()` returns false

### ISSUE THREAD

**Issue by lenormf** [tmux/tmux#1266]
Hi,

After investigating [an issue on the Kakoune editor](https://github.com/mawww/kakoune/issues/762#issuecomment-367574921) related to colors, it turned out that the `can_change_color()` function returned false when the terminfo profile was that of `tmux-256color`. This prevents tools that plan on using OSC4 sequences to change the palette from doing just that.

Thanks.

**Comment by nicm** [comment]
If you want applications inside tmux to be able to modify the palette you need to make sure your tmux is new enough, run tmux with RGB colour configured and create a modified terminfo(5) entry for inside tmux with the palette setting capabilites (ccc and initc).

**Comment by lenormf** [comment]
As said in the thread I linked in my message above, I've tried creating a custom terminfo file with an `initc` field in it - though without any `ccc`. What should the file look like?

Also I was under the impression that it was possible to get this to work simply by fixing the terminfo file provided by `tmux`, isn't that the case? I'd rather not have to create a user-local terminfo file.

**Comment by nicm** [comment]
tmux doesn't provide a terminfo entry, it is provided by ncurses. You will need to create a custom one locally based on the tmux or tmux-256color entry, you can use infocmp and tic to do this. ccc is a flag, you can look at something like xterm-256color to see what initc and ccc should look like.

You need to configure tmux for RGB colour by providing the Tc flag or it will not be able to correctly display any palette changes that don't match an entry in the default 256 colour palette.

**Comment by lenormf** [comment]
I will look into it, thanks for all the info!

**Comment by kaspergrubbe** [comment]
If anyone else are wondering how this is done, this is how:

# Write terminfo to file

(I do not have a `tmux-256color` definition in my terminfo, so I use `screen-256color`)

```bash
$ infocmp screen-256color > screen-256color.ti
```

# Modify terminfo file

The `can change colors` definition is the `ccc` flag. So I opened up `screen-256color.ti` in my editior, and did the following change:

```diff
screen-256color|GNU Screen with 256 colors,
-  am, km, mir, msgr, xenl,
+ am, km, ccc, mir, msgr, xenl,
  colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
```

# Install your new definition

```bash
$ tic screen-256color.ti
```

You are now done.
