### ISSUE TITLE
Resize font in specific pane in tmux

### ISSUE THREAD

**Issue by cdrrazan** [tmux/tmux#1267]
I would like to open multiple panes in the tmux session and some of the panes contain  app server for eg. rails server. I would like to resize the panes in required panes only as i can see what's happening there. I know i can maximize the pane in quick flash but would love that feature of resizing font to specific pane as per need. Is there any way to do this?

Here's my tmux and OS details

tmux version: 2.27
OS: linux(Ubuntu)

**Comment by nicm** [comment]
It is not possible for tmux to use more than one font size.

**Comment by unphased** [comment]
This is a limitation of terminal UI. 

Check out the https://github.com/yaronn/blessed-contrib project.

**Comment by da-x** [comment]
This indeed something that would require a lot more than a change in tmux. I've made a little experiment around this, article [here](https://medium.com/@danaloni/alacritmux-tmux-pane-font-resize-3bd07e186c).
