### ISSUE TITLE
Status sometimes clips off right side

### ISSUE THREAD

**Issue by ma9e** [tmux/tmux#1268]
I have three widgets in my status, one of which frequently changes between something like "Available now" and "1 hours, 28 minutes" (it's for my spaced repetition software). It looks like the allocated length for the status isn't updating when this widget changes, which causes another widget to start clipping off the right side.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by ma9e** [comment]
I see that my issue is with status-right-length defaulting to 40 characters. Would you consider a pull request that interprets a value of -1 to mean unlimited length?

**Comment by nicm** [comment]
The maximum is 32767, nobody has a terminal which is that wide.
