### ISSUE TITLE
Allow mouse capture for scrolling while keeping default mouse selection

### ISSUE THREAD

**Issue by fserb** [tmux/tmux#1270]
I'm running tmux 2.6 on iTerm2/OSX.

It's a deal breaker that the only way to get proper selection behaviour on tmux when "set mouse on" is to press Option (to fallback to iTerm selection). But if I leave "set mouse off", then I can't get mouse scrolling to work properly.

I don't need inside pane selection (I use only one pane anyway). 
The current settings don't support this use case at all. All old ways (that existed before "set mouse") to support scrolling are broken and the new way is a "all or none" kind of deal.

Is there a solution to this problem? Could there be a "do not capture" setting for some events that keep the default behavior? Or something that allows specifically to only enable mouse-scrolling?

**Comment by nicm** [comment]
Either tmux gets the mouse or your terminal does, there is no other way to do it.

**Comment by fserb** [comment]
You sure knows way more about this stuff than I will ever do. 

But vim on my iterm2 does it correctly (I just tested again to double check, and I'm able to scroll the cursor inside vim, while still selecting with iterm2), so I'm guessing there's a TTY console code that sends scroll events (that could be mapped to WheelUp/WheelDown) without doing the full capture thing, no?

**Comment by nicm** [comment]
No, either tmux gets all mouse events or the terminal does.

Some terminals send Up and Down keys (that is, as if you had pressed Up or Down) for the mouse wheel when the application has /not/ taken over the mouse and is in cursor position mode. But if iterm2 is doing that you should get them in tmux too with mouse off.

**Comment by fserb** [comment]
Ahn. That would make sense. On tmux, when I scroll (with mouse off) I get the bash history to go up/down (as if I had pressed up/down). :/

I'll try to see if iTerm2 would be willing to add a setting to only send scrolling events when mouse on. Or to configure what to send when scrolling when mouse off. Thanks for replying. :)
