### ISSUE TITLE
Breaks GPG Keychain signing in Tmux

### ISSUE THREAD

**Issue by holms** [tmux/tmux#1271]
There's a problem using gpg in Tmux. It tries to call window for entering password and fails.
It works outside of tmux, so it's definitely a tmux problem.

```
roman@debian:~/Dev/OFS/ofs/source/childminder$ git commit
error: gpg failed to sign the data
fatal: failed to write commit object
```

My env:

```
roman@debian:~/Dev/OFS/ofs/source/childminder$ uname -a
Linux debian 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
```

**Comment by nicm** [comment]
Sounds more like an environment variable problem than a tmux problem to me.

**Comment by nicm** [comment]
Are you sure you have DISPLAY set properly inside tmux? And whatever else gpg needs?

**Comment by holms** [comment]
Sorry I don't what is a proper display, using DWM in here :)
```
roman@debian:~/Dev/OFS/ofs/source/childminder$ printenv | grep DISPLAY
DISPLAY=:0
```

It is set. Here's trace from git:

```
roman@debian:~/Dev/OFS/ofs/source/childminder$ GIT_TRACE=1 git commit -m "test"                                                                
12:52:29.491220 git.c:371               trace: built-in: git 'commit' '-m' 'test'
12:52:29.497817 run-command.c:350       trace: run_command: '/usr/bin/gpg2' '--status-fd=2' '-bsau' 'E2AB66331DA5CA780B7B1FA5D4BF11DA1E39EDFF'
error: gpg failed to sign the data
fatal: failed to write commit object
```

And if done outside of tmux then everything works.

![gpg](https://user-images.githubusercontent.com/280958/36595055-aa0247ee-1898-11e8-8cb7-66b9a977b6ea.png)

**Comment by holms** [comment]
This happened to me once when I've set wrong tty in gpg-agent. So it's something about tty settings for sure

**Comment by nicm** [comment]
DISPLAY is for X so it is not that then. I think you will need to ask the GPG developers.

**Comment by holms** [comment]
What's the default TTY outside of tmux and inside tmux? 

Here's settings what's GPG is using

```
roman@debian:~/Dev/OFS/ofs/source/arc_service$ printenv | grep TTY
GPG_TTY=/dev/pts/0
```

**Comment by nicm** [comment]
try setting it to output of `tty` inside tmux

**Comment by holms** [comment]
Cool it works! Maybe you could point me how can I set env var in config? Somehow my google skills today aren't good.
