### ISSUE TITLE
history management discussion

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#1273]
I played around with history more and the way the number of lines gets calculated and the way the `history-limit` works is pretty sensible to me so far. The (maximum) amount of memory used for history will scale with the amount of terminal-widths. E.g. a horizontally split set of panes could hold 3x as much history as a vertically split set of panes, if in the same containing terminal size. Now, I was thinking that maybe history-limit instead of lines could be safer as a limit in bytes, but, because of wrapping, it is not possible to have an unreasonably long *actual* terminal line count as one tmux history line, so no real issue there, and lines is often easier to reason about anyway.

Seems to me that there is a good opportunity (esp considering the nature of most terminal output content) here to allow history content (or some older fraction of it) to become *compressed*, this would allow for a lot more history to be kept, memory consumption being equal. Once we get into higher values for history limit, there should probably also be a byte counting based limit. and working within that limit, compression can be used to maximize the efficiency. Users may want to decide what type of compression though, as that will affect speed/energy and ratio.

So, then, to me, the optimal way this would work might be to configure a per-session (or per tmux server, even) history size budget. Then, until this limit is hit, panes do not have to have any limit on their history size. 

Once the limit is hit, we start truncating the longest of them (per history-limit settings)

Another benefit of this is that if so many panes exist that they stay within their own history-limit but overflow the global budget they can also get limited further to enforce the budget.

**Comment by nicm** [comment]
History is better measured in lines than bytes.

I don't think compression or writing history to disk is worth the
complexity for modern machines and I don't particularly want to link
tmux against libz. So long as there is some way for people to put a
rough bound on the total memory that is enough.

Per-session history limit would be nice but it is a) not as obvious as
per-pane b) going to be trouble with panes that exist in multiple
sessions.

Ideally history would be deleted by age.

There are too many options already, it preferably needs to just do the
right thing without adding more. Definitely no unnecessary tuneables,
nobody needs to set both lines and bytes.

**Comment by unphased** [comment]
I was actually more thinking about something like LZ4 or LZO, something less taxing and much faster than gzip. I hear you on not wanting more dependencies, though...
