### ISSUE TITLE
tmux picks `/bin/bash` instead of the bash set in `chsh` command

### ISSUE THREAD

**Issue by fishy** [tmux/tmux#1278]
```
$ tmux -V
tmux 2.6
```

I recently noticed some bash-completion issue on macOS with homebrew, and tracked it down to that it's because of tmux picked `/bin/bash` instead of the bash I set with `chsh` command.

I fixed it by adding the following line to my `~/.tmux.conf`:

```
set-option -g default-shell "$HOME/work/homebrew/bin/bash"
```

The question is, why do I even need to do that manually? Why doesn't tmux just pick up the default version of bash I set via `chsh`, or just inherit `$SHELL`?

**Comment by nicm** [comment]
How tmux sets the initial value for default-shell is explained in the man
page.

**Comment by fishy** [comment]
Thanks for the reply, but I'm still not sure what's going wrong.

The man page says:

```
When started tmux tries to set a default value from the first suitable of the SHELL environment variable, ...
```

My $SHELL outside of tmux is the bash from homebrew:

```
$ echo $SHELL
/Users/fishy/work/homebrew/bin/bash
```

But tmux doesn't pick that up by default.

**Comment by nicm** [comment]
Are you sure you didn't start tmux from somewhere with a different SHELL?

**Comment by krader1961** [comment]
Works for me on macOS (although I'm using tmux built from git master). If I export SHELL=/usr/local/bin/bash and start tmux it honors that value. Note that you may need to `tmux kill-server` if you started tmux before you changed your shell.

**Comment by fishy** [comment]
Ah that's a good point. My tmux was started by ssh:

```
ssh $SSHHOST -t -- tmux new -A -s my-session
```

I guess at that point $SHELL was not set properly yet.

Adding `-c "$HOME/work/homebrew/bin/bash"` to the end of that ssh command line fixed it.
