### ISSUE TITLE
ls colors stripped in tmux

### ISSUE THREAD

**Issue by gregflynn** [tmux/tmux#1279]
When running `ls -l --color` in tmux I don't get colors

**Platform:** Arch Linux
**Terminal:** `xfce4-terminal`
**TERM:** `xterm-256color`
**tmux TERM:** `xterm-256color` / `screen-256color` (see below)
**tmux version:** `tmux 2.6-2` installed from official repo

![image](https://user-images.githubusercontent.com/295898/36953014-db221cde-1fe4-11e8-9814-aaabe1079937.png)

But when I'm outside tmux
![image](https://user-images.githubusercontent.com/295898/36953029-06639314-1fe5-11e8-9118-0a47849d4a48.png)

This is with or without a `~/.tmux.conf`, I tried
```
set -ga terminal-overrides ",screen-256color:Tc"
set -g default-terminal "screen-256color"
```
with no luck.

I have other commands coloring output fine, and Vim in `termcolors` mode through tmux with the following options:
```
set -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "xterm-256color"
```

Thanks for any help in advance

**Comment by nicm** [comment]
It is much more likely that ls is not sending the colours at all than that tmux is removing them.

**Comment by nicm** [comment]
You need to set TERM=screen-256color or TERM=tmux-256color inside tmux, xterm-256color is not supported.

**Comment by gregflynn** [comment]
@nicm Thanks for your reply, I was hoping it was as simple (or stupid on my part) as you suggest, but with the following in my `~/.tmux.conf`:
```
set -ga terminal-overrides ",screen-256color:Tc"
set -g default-terminal "screen-256color"
```

and then launch tmux with `TERM=screen-256color tmux` and I still don't get ls colors. I tired the same with `tmux-256color`

**Comment by nicm** [comment]
No, you need TERM=tmux-256color inside tmux and xterm-256color outside.

Do this please:
~~~~
tmux -vvLtest new
TERM=screen-256color \ls -l --color=always
exit
~~~~
Then show me the tmux-server*.log file.

**Comment by gregflynn** [comment]
Here's the log, looks like ls is sending the escape codes

[tmux-server-10004.log](https://github.com/tmux/tmux/files/1780765/tmux-server-10004.log)

Sorry for the confusion and thanks for the help, I've been on screen for a decade :smile:

**Comment by nicm** [comment]
Yes, you are right, ls is sending it, but it is sending \033[32;10m.

In tmux, the 10 is equivalent to SGR 0 and resets the colours and attributes.

It doesn't appear to do this in xterm, but I'm not sure where it came from - it was present in tmux 0.1

I'm not sure what ls wants it to do either.

**Comment by nicm** [comment]
Looks like it is for font control on some terminals, although I can't find any that support it.

You can do this:
~~~~
--- input.c     19 Feb 2018 21:20:10 -0000      1.131
+++ input.c     5 Mar 2018 12:30:29 -0000
@@ -1907,7 +1907,6 @@ input_csi_dispatch_sgr(struct input_ctx

                switch (n) {
                case 0:
-               case 10:
                        memcpy(gc, &grid_default_cell, sizeof *gc);
                        break;
                case 1:

**Comment by gregflynn** [comment]
@nicm Just recompiled tmux without that `case 10` statement and now ls outputs color, though I'm surprised this isn't more widespread (I don't think much of my config is wildly unique)

So do you want a PR with that case statement removed?
- this seems like a workaround? but you're the expert here

or any suggested next steps for figuring out why my `ls` binary is emitting that `10`?

**Comment by nicm** [comment]
I have removed the case statement now, thanks.
