### ISSUE TITLE
long text (>1023 bytes) in status-(left|right) may be invisible on OS X

### ISSUE THREAD

**Issue by delphinus35** [tmux/tmux#128]
In OS X 10.10.5 and tmux 2.0, a long text (>1023 bytes) in `status-left`, `status-right` option may not work. For instance,

* execute tmux with no conf.

* set `status-left` to 1023 bytes text => show properly  

```sh
tmux set -g status-left '#[__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________]0123456789'
# 1023 bytes
```

* set `status-left` to **1024** bytes text => **invisible**  

```sh
tmux set -g status-left '#[___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________]0123456789'
# 1024 bytes
```

I tried this in CentOS6 & tmux 2.0, but this did not occur. Is this the limitation in OS X only?

I think #46 occurs for the same reason. The text made by powerline for `status-right` may include plenty of style text such as `#[fg=colour8,bg=default,nobold,noitalics,nounderscore]some more texts....`. So `status-right` may exceed the threshold easily.

**Comment by nicm** [comment]
Can't reproduce here on Linux or OpenBSD, probably some limit on OS X is
1024 bytes (BUFSIZ or similar). Can't see anything obvious in the code
path for status-left but there must be something.

**Comment by edouard-lopez** [comment]
There is definitily some limitations on the width, and it happens on Linux too.

### Env
 
```
$ lsb_release -a
Distributor ID: LinuxMint
Description:    Linux Mint 18 Sarah
Release:        18
Codename:       sarah
```

    $ tmux -V
    tmux 2.1

### Configuration

    set -g status-right '#[fg=blue]%a %d %b#[fg=white] | #[fg=yellow]%H#[fg=white]:#[fg=yellow]%M #[fg=white] | #[fg=blue]⇣#{download_speed} #[fg=green]⇡#{upload_speed}#[fg=white] | bat.  #{battery_icon}#{battery_percentage} (#{battery_remain})'

### Result

Battery info aren't visible:
![tmux](https://cloud.githubusercontent.com/assets/1212392/18275605/098ce8b4-7448-11e6-8952-92a7e3f41801.png)

**Comment by edouard-lopez** [comment]
The [`tmux` documentation](http://man.cx/tmux) has a `status-right-length` settings you can play with:

> status-right-length length
> 
>     Set the maximum length of the right component of the status bar. The default is 40.
