### ISSUE TITLE
#{pane_current_path} does not retain symlinked path

### ISSUE THREAD

**Issue by sorsasampo** [tmux/tmux#1282]
In shell:

```
$ mkdir real
$ ln -s real symlink
$ cd symlink
$ echo $PWD
/home/user/symlink
```

In tmux `:display "#{pane_current_path}"`, result is: `/home/user/real`.

I would expect #{pane_current_path} to return the same as $PWD in the shell.

Debian Stretch/9.4, `tmux -V` 2.3, package 2.3-4.

**Comment by sorsasampo** [comment]
Same result with `tmux -V` 2.6, package 2.6-3~bpo9+1.

**Comment by nicm** [comment]
It is whatever the kernel tells it, which is the physical path. Nothing to
do with the shell.

**Comment by sorsasampo** [comment]
I guess the relevant code is here:

https://github.com/tmux/tmux/blob/9fd995275201893a604d15bb426e0f5a7f7971e6/format.c#L534-L547
https://github.com/tmux/tmux/blob/895f1d93d51f54b3f76e6406d51f4fc491399ce2/osdep-linux.c#L64-L90

So, basically the same as `/proc/$$/cwd`.

Any ideas how to access the `$PWD` of the running process from the tmux command line?

**Comment by nicm** [comment]
You will need to make the shell tell tmux by setting something in the tmux environment or a user option.

**Comment by sorsasampo** [comment]
And how would I do that exactly?

**Comment by nicm** [comment]
User option would probably be best, tmux set-option. You can use TMUX_PANE inside the pane to generate a unique name when you store the PWD, then use display -F #{pane_id} to get the current pane ID in a script, look up the option and pass it to neww -c.

**Comment by hanxi** [comment]
I use this `:display "#(pwd)"`

```
bind '"' splitw -v -c "#(pwd)"
bind '%' splitw -h -c "#(pwd)"
bind c neww -c "#(pwd)"
```

**Comment by typelogic** [comment]
Is there a fix to this? For `bind-key c new-window -c "#{pane_current_path}"` to work?

**Comment by hanxi** [comment]
@typelogic I use symlinked like this:

```
# .bashrc
# set pwd for tmux
function set_tmux_pwd() {
    [ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD"
    return 0
}
function my_cd() {
    \cd $1
    set_tmux_pwd
}
set_tmux_pwd
alias cd=my_cd
```

```
# .tmux.conf
# this support symbolic link
bind c run-shell 'tmux new-window "cd \"$(tmux show-environment $(echo "TMUXPWD_#D" | tr -d %) | sed -e "s/^.*=//")\"; exec $SHELL"'
bind '"' run-shell 'tmux split-window -v "cd \"$(tmux show-environment $(echo "TMUXPWD_#D" | tr -d %) | sed -e "s/^.*=//")\"; exec $SHELL"'
bind '%' run-shell 'tmux split-window -h "cd \"$(tmux show-environment $(echo "TMUXPWD_#D" | tr -d %) | sed -e "s/^.*=//")\"; exec $SHELL"'
```
