### ISSUE TITLE
Wrong colors in tmux in console but ok in wsltty

### ISSUE THREAD

**Issue by persep** [tmux/tmux#1285]
Can you check if this issue is related to the console of ubuntu on windows or to tmux. I've already ruled out the vim colorscheme and the airline plugin.
https://github.com/Microsoft/console/issues/136

The tmux -info output [here](https://gist.github.com/persep/85f2b3c952dd1777f8c2e225ab84c806)

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by persep** [comment]
- Ubuntu on Windows Windows [Version 10.0.16299.309]. Ubuntu 16.04.3 LTS
- .tmux.config contains: 

    set -g default-terminal "tmux-256color"
    set -g terminal-overrides ',xterm-256color:Tc'

- The terminal is bash of Ubuntu on windows, and $TERM inside tmux is xterm-256color and outside of tmux is tmux-256color
- logs from tmux (see below); I get:

    $ tmux -Ltest kill-server
    error connecting to /tmp/tmux-1000/test (No such file or directory)

 I've attached the logs from tmux -vv -Ltest -f/dev/null new

[tmux-client-46.log](https://github.com/tmux/tmux/files/1816930/tmux-client-46.log)
[tmux-out-48.log](https://github.com/tmux/tmux/files/1816931/tmux-out-48.log)
[tmux-server-48.log](https://github.com/tmux/tmux/files/1816936/tmux-server-48.log)

- description of the problem with steps to reproduce;
when in terminal (ubuntu on windows) and in wsltty (mintty 2.8.4 wsltty 1.8.4)  I have vim with gruvbox and the gruvbox airline all working ok:
![Imgur](https://i.imgur.com/7I8xNWy.jpg)

If I change to the wombat airline theme, for testing purposes, it also works ok:
![Imgur](https://i.imgur.com/9DD2mZs.jpg)

So the airline themes work fine in the terminal but if I open vim inside tmux on ubuntu for windows I get a different color in the text from the vim status line but it's the correct colors in tmux on wsltty. Look at the different color in the "NORMAL" text
![Imgur](https://imgur.com/AjInN9G.jpg)

And if a change to the wombat airline you can see the "NORMAL" text color is also lighter:
![Imgur](https://imgur.com/M4J8FKJ.jpg)

It happens to all the other airline themes like solarized for example.
I've tried this in vim 8-1605 and tmux 2.1 and 2.6. I've also tried with tmux in 256 and 24 bit colors and it doesn't make a difference. Vim colors schemes are ok in tmux but not the text color from the airline themes. They render with wrong colors inside tmux on the ubuntu on windows terminal but correctly in tmux on wsltty.

My `.tmux.conf` file is:

    set -g default-terminal "tmux-256color"                                              
    # enable 24 bit support                                                              
    set -g terminal-overrides ',xterm-256color:Tc'  

And my vimrc is [here](https://gist.github.com/persep/e66f00f84f619b8086ec60e4e878ef5a)

**Comment by nicm** [comment]
Are you sure these logs show the problem? There are no colours in the logs. It is no use running tmux with -f/dev/null to if you can't then reproduce the problem without your .tmux.conf.

Please run "tmux -vv new" so it does use your config file and show me the logs from that.

**Comment by persep** [comment]
These are the logs after running vim inside tmux and showing in the wrong colors
[tmux-client-19.log](https://github.com/tmux/tmux/files/1818456/tmux-client-19.log)
[tmux-out-21.log](https://github.com/tmux/tmux/files/1818458/tmux-out-21.log)
[tmux-server-21.log](https://github.com/tmux/tmux/files/1818459/tmux-server-21.log)

**Comment by nicm** [comment]
Does this
~~~~
printf '\033[38;2;40;40;40m\033[48;2;168;153;132m\033[1m NORMAL \033[m'
~~~~
show different colours in the two terminals outside tmux?

**Comment by nicm** [comment]
The escape sequences that tmux is using in these logs match your correct screenshots when I try them in gnome-terminal, so I suspect you are hitting a bug in your terminal, perhaps it does not correctly handle mixing bold text with RGB colours.

**Comment by nicm** [comment]
Can you run vim in script, outside tmux like this:

~~~~
$ script
Script started, file is typescript
$ vim
<reproduce the problem>
:q
$ exit
Script done, file is typescript
~~~~
Then send me the typescript file.

**Comment by persep** [comment]
The escape sequence you gave me prints the same outside and inside tmux:
![Imgur](https://i.imgur.com/1yGFfIl.jpg)

I can't run script because its missing a system call in WSL. Anyway the bug does look like a problem with bold characters inside tmux as its being discussed in the console bug I opened.

If you agree you can close it here

**Comment by nicm** [comment]
Right, but I didn't ask if it printed the same inside and outside tmux, I asked if it printed the same in the working and nonworking terminals.

**Comment by nicm** [comment]
Anyway, it is almost certainly a terminal issue, so best to report it to them.

**Comment by persep** [comment]
Just for closure.
In wsltty outside tmux:
![img]https://i.imgur.com/wPg6wMn.jpg[/img]

In bash ubuntu on windows outside:
![img]https://i.imgur.com/1yGFfIl.jpg[/img]

**Comment by nicm** [comment]
OK it definitely seems that the terminal is doing something wrong. This is how it looks in gnome-terminal (not that it is always correct, but I think it is in this case):
![screenshot from 2018-03-16 10-15-22](https://user-images.githubusercontent.com/304243/37515553-0dfb4262-2903-11e8-8a57-4cbb5e0af9d3.png)
