### ISSUE TITLE
Feature request: Forcibly size the current screen to the current terminal

### ISSUE THREAD

**Issue by Rhialto** [tmux/tmux#1287]
If I attach to the same window from two terminals (be it using the same session, or with a cloned session (`tmux new-session -t "$session"`)) then the effective window size is the smaller of the widths and the smaller of the heights of both terminals.

I would like the feature that screen has in tmux too: by default it is mapped to ^A F ("fit"):

```
       C-a F      (fit)       Resize the window to the current region size.
```
The smaller terminal will then show a subset of the window, scrolling around as necessary to keep the cursor visible.
(A method to set any size would be even better of course)

This feature is as far as I know still missing as of tmux-2.6. Since it was originally added to screen at my suggestion, I use it a lot and it keeps me from switching to tmux.

Example: two differently sized terminals showing the same window, which has the size of the taller one here.
![example1](https://user-images.githubusercontent.com/6436498/37557529-2f71a04a-2a06-11e8-97c6-afd623842113.jpg)

**Comment by nicm** [comment]
This has been on the todo list for years. It is not easy to implement.

**Comment by nicm** [comment]
It would be great if you want to implement this ;-)...

**Comment by Rhialto** [comment]
Oh I just remembered the *other* thing that is a showstopper for me: that tmux insists on changing my backspace characters (VERASE) to DEL. That is absolutely unacceptable.

**Comment by Rhialto** [comment]
For the record: I tried to program this myself back then (with two different approaches even), but indeed the situation is complicated and I didn't get anything working enough to think I was on the right path.
