### ISSUE TITLE
[Enhancement] Hold position in scrollback

### ISSUE THREAD

**Issue by atweiden** [tmux/tmux#129]
It's common to scroll up in tmux to copy text. It would be a major benefit not to lose your position in the scrollback when copying text or visually selecting text with the mouse.

CC @bruno- https://github.com/tmux-plugins/tmux-yank/issues/40

**Comment by ntnn** [comment]
It's already there.
`man tmux | less +/ copy-selection`

**Comment by bruno-** [comment]
Thanks for the quick reply @ntnn.

Do you know if `tmux` gained the ability to somehow invoke `copy-pipe` and stay in copy mode?

**Comment by ThomasAdam** [comment]
Nope:

```
	case MODEKEYCOPY_COPYPIPE:
		if (sess != NULL) {
			window_copy_copy_pipe(wp, sess, NULL, arg);
			window_pane_reset_mode(wp);
			return;
		}
```
