### ISSUE TITLE
accidentally suspended client... how do revive it

### ISSUE THREAD

**Issue by nnako** [tmux/tmux#1292]
I have a tmux environment with four windows. Each window accessible by pressing ```<CTRL> + <B>``` and then  ``` <0>``` to ```<3>```. In each window, I use two panes, one on the left and one on the right within the respective window. In window "2" I run ```vim``` on the left and an ordinary ```bash``` console on the right. In the status line (footer) of the session I saw this picture:

```[gateway] 0:BASH 1:FILE 2:VIM* 3:MGT```  (here the vim pane was in focus)

The asterisk ```*``` showing the active window as being ```2:VIM```. Everything fine.

Now, I accidentally suspended the "client" by using the hotkeys ```<CTRL> + <B>``` / ```<CTRL> + <Z>```, originally intending to suspend the "session" (and not the "client"). So, the ```vim``` pane closed in the window ```2:VIM```. Leaving the status row (footer) like this:

```[gateway] 0:BASH 1:FILE 2:VIM*Z 3:MGT```  (please note the new "Z" at window "2")

As I have some open (un-saved) documents within that suspended "client" ```vim```, I need to revive the "client" somehow, but can not find any option to do this within tmux. As the ```vim``` client does not seem to have a parent bash console accessible, I don't see it anymore and so can not send an appropriate signal to wake it up.

**What activities are possible to revive my "client"?**

**Comment by leorosa** [comment]
Try the following:
`tmux list-sessions` to the existing sessions. You "revive" one by its number, using
`tmux attach-session -t N`, where `N` will be `0`, in the case of only one session as you described.

**Comment by nicm** [comment]
I think you pressed C-b Z not C-b C-z. Just press C-b Z again to unzoom the pane.

**Comment by nnako** [comment]
@nicm great. Thank you. You saved my work.
