### ISSUE TITLE
tmux is not exact matching session-names

### ISSUE THREAD

**Issue by useltmann** [tmux/tmux#1295]
As long as an existing session name starts with the session name to test tmux says the session exists.

# Version Information:
```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.5
xterm-256color
```
# Steps to reproduce:

* make sure there is no existing tmux-session
```
tmux list-sessions
error connecting to /tmp/tmux-0/default (No such file or directory)
```
* create a new session
```
$ tmux new-session -d -s testsession
```
* list existing sessions
```
$ tmux list-sessions
testsession: 1 windows (created Mon Mar 26 17:38:49 2018) [130x36]
```
* test for existing session *test*:
```
$ if tmux has-session -t test; then echo "session exists";fi
session exists
```
Tmux says the session *test* exists, but this is wrong. there is only a session *testsession*. It seems that tmux is not exact-matching the session-names.

**Comment by ThomasAdam** [comment]
Hi,

Use:  has -t=foo

Thomas

**Comment by useltmann** [comment]
thanks. that works
