### ISSUE TITLE
tmux crash on :join-pane when in window selection mode with marked pane

### ISSUE THREAD

**Issue by jameh** [tmux/tmux#1299]
I'm admittedly just learning how join-pane works, but something I tried that I think is supposed to work ended up crashing the tmux server:

```
touch empty.conf
tmux -f empty.conf
```

then, `<prefix>` `c` to create a new window, then `<prefix>` `m` to mark the window

then, `<prefix>` `w` to enter the interactive window selector

then highlighting the unmarked window, and typing `:join-pane` then `enter`

This crashes the server with the most recent `master` commit on MacOS 10.11.6 in iTerm2 (or Terminal)

Also, I'm running tmux within zsh

**Comment by jameh** [comment]
trying to bisect now, so far 2.7 and 2.6 both crash as well

**Comment by jameh** [comment]
2.5 and a couple earlier also crash. I think this is must not be how join-pane is normally used - what does work is after highlighting the unmarked window, `enter` to open it, then `<prefix>` `:join-pane` `enter`.

What is weird though is when in window-selection mode, if the highlighted pane is the marked (and current) pane, `join-line` returns error "pane cannot be joined to it's own window" and *doesn't* crash - some error message at least would be helpful for the crash I stumbled into.

**Comment by jameh** [comment]
So after more experimentation, I understand a bit better now that my initial instinct of wanting to join the marked window to the currently highlighted window isn't the way `join-pane` works - and essentially what I was trying to do was join the marked window to the current window (which is also the marked window) I think then the correct thing for tmux to do is print "can't join a pane to its own window" instead of crashing

**Comment by jameh** [comment]
oh shoot, I just read CONTRIBUTING closer and here is the requested system info

```
uname -sp && tmux -V && echo $TERM
Darwin i386
tmux master
xterm-256color
```

I just realized that my `$TERM` is neither `screen-256color` nor `tmux-256color` is this relevant?

**Comment by jameh** [comment]
and here is a log file of the first crash case I describe in post 1
[tmux-client-70728.log](https://github.com/tmux/tmux/files/1858430/tmux-client-70728.log)
[tmux-out-70730.log](https://github.com/tmux/tmux/files/1858431/tmux-out-70730.log)
[tmux-server-70730.log](https://github.com/tmux/tmux/files/1858432/tmux-server-70730.log)

**Comment by ThomasAdam** [comment]
Does the attached patch fix this?
[x.diff.txt](https://github.com/tmux/tmux/files/1858677/x.diff.txt)

**Comment by jameh** [comment]
that patch on `master` does not fix the issue

**Comment by jameh** [comment]
is the test case not reproducible for you?

**Comment by ThomasAdam** [comment]
Yep -- the test-case shows the problem.

Make sure you kill tmux entirely, or run:

```
./tmux -f /dev/null -Ltestcase
```

**Comment by jameh** [comment]
sorry, I must have not fully restarted the server! That patch fixed the crashes for me!

Just wondering what you think of what I pointed out about how case (6) should successfully join also? Am I misunderstanding something about that case?

**Comment by nicm** [comment]
I have applied this fix now.

Running a command from tree mode uses EITHER the selected pane or the tagged pane, not both. They will both be passed as -t to join-pane; if you want to specify -s you need to mark the pane (-s will use the marked pane by default).

**Comment by jameh** [comment]
sweet, thanks bud!
