### ISSUE TITLE
Processes get defunct on Cygwin

### ISSUE THREAD

**Issue by ismail** [tmux/tmux#13]
This is originally reported at https://cygwin.com/ml/cygwin/2015-05/msg00314.html , how to reproduce. Build and compile the following Go program

package main

import (
    "fmt"
    "time"
)

func main() {
    for i := 0; ; i++ {
        fmt.Println(i)
        time.Sleep(500*time.Millisecond)
    }
}

Run it in one window and try to switch, it will eventually switch but will take a lot of time. And if you wait long enough it'll put \<defunct> title on the window. I have this semi-regularly happening with ssh running under a tmux window.

**Comment by nicm** [comment]
Can you reproduce it with Bash instead of Go and give me the script please?

**Comment by nicm** [comment]
Also please tell me the libevent versions you are using with tmux 1.9 and 2.0? Are they the same?

**Comment by ismail** [comment]
1. Can't seem to reproduce with Bash, I suspect this has something to do with native (non-cygwin) Windows programs.

2. libevent version is 2.0.21, but I tested with 2.0.22 with no success.

3. I didn't try myself to be sure but the initial report says tmux 1.9a works fine and this is a 2.0 regression.

**Comment by ismail** [comment]
A very easy reproducer, run cmd.exe in one window, and tmux goes to defunct state soon and gets really really slow.

**Comment by fosterfreedom2015** [comment]
Lol... jt all works fine now go he ass tosleep

**Comment by nicm** [comment]
Can you try this please and see if the problem goes away?

```
diff --git a/osdep-cygwin.c b/osdep-cygwin.c
index 91bc5fc..061be7a 100644
--- a/osdep-cygwin.c
+++ b/osdep-cygwin.c
@@ -35,6 +35,8 @@ osdep_get_name(int fd, unused char *tty)
 	int	 ch;
 	pid_t	 pgrp;
 
+	return;
+
 	if ((pgrp = tcgetpgrp(fd)) == -1)
 		return (NULL);
 
@@ -68,6 +70,8 @@ osdep_get_cwd(int fd)
 	pid_t		 pgrp;
 	ssize_t		 n;
 
+	return;
+
 	if ((pgrp = tcgetpgrp(fd)) == -1)
 		return (NULL);

**Comment by nicm** [comment]
If it does, please try moving the returns you added down below the tcgetpgrp lines like this:

```
    if ((pgrp = tcgetpgrp(fd)) == -1)
        return (NULL);
    return NULL;
```

And see if the problem comes back.

**Comment by ismail** [comment]
In both cases bug is gone and tmux is really responsive as expected.

**Comment by nicm** [comment]
If you remove the return from osdep_get_cwd but not osdep_get_name, does the problem come back?

**Comment by ismail** [comment]
Yes the problem comes back.

**Comment by nicm** [comment]
Ok, it sounds like there is a problem with /proc/*/cmdline with native processes, I suspect either Cygwin has a bug which is making tmux have to read a lot of data from the cmdline file, or Cygwin is having to go off and do a lot of slow, extra work that it doesn't have to do for Cygwin processes. I expect you would have mentioned if tmux did not actually rename the window to cmd.exe so I suspect the second idea is true.

I suggest you report this to Cygwin. If they can't or won't fix it, I would be fine with making tmux disable automatic-rename for native processes, but I need to know if there is a way to detect them (is there something in /proc to look at?).

As a workaround, you can just turn off automatic-rename either globally with -g or just for the window where you are running the native process.

**Comment by ismail** [comment]
Thanks but I can't reproduce it with usual tools, I run cmd.exe under bash and

> cat /proc/6784/cmdline
<defunct>

So thats where the defunct title is coming. It takes 1s to get that output (quite slow compared to the native cygwin procs.) I'll try to find out if there is a way to find if a program is native-cygwin or not.

**Comment by ismail** [comment]
Btw with "set -g automatic-rename off" there is a noticable slowdown.

**Comment by nicm** [comment]
A second is too long, tmux does this for every window twice a second.

-------- Original message --------

**Comment by ismail** [comment]
Well, if it reads <defunct> on Cygwin then it can decide its non-cygwin program and stop.

**Comment by ismail** [comment]
Is there a way to also stop cwd reading for current process? Thats also very slow for non-Cygwin apps.

**Comment by nicm** [comment]
No because then when you stop the program it wouldn't know to start again. It needs something fast it can check to tell it not to open cmdline at all. Or better it needs it not to be so ridiculously slow, ask the Cgywin ML.

**Comment by nicm** [comment]
Any way to detect native processes can be used for both cmd and cwd. But there is no point in adding workarounds if they could fix it in Cgywin :-).

**Comment by ismail** [comment]
I am writing to cygwin list, hopefully this can be fixed. Thanks a lot for insight!

**Comment by ismail** [comment]
Fixed in Cygwin: https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=commitdiff;h=95868172f39e972dbcfad3e69fee7854eafe20dd

**Comment by nicm** [comment]
Ok what does automatic-rename rename the windows with native processes in to now?

**Comment by ismail** [comment]
For native Windows processes it shows "<defunct>" now.

**Comment by nicm** [comment]
Alright well I guess that will do. Thanks for getting this fixed.

**Comment by ismail** [comment]
Thanks for the clues :)

**Comment by ismail** [comment]
Just an update, with https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=commitdiff;h=575ec00a43ae3bbc84d5dab1233c3f95fdad18d0 Cygwin now shows real cmdline and cwd for non-native cygwin processes.
