### ISSUE TITLE
Unable to set global hooks

### ISSUE THREAD

**Issue by XanderXAJ** [tmux/tmux#1301]
I'm unable to set global hooks (e.g. `set-hook -g`).  Session hooks work fine.  This feels like it should be an environmental issue, but telling tmux to ignore my environment doesn't seem to help.  Likewise, I haven't been able to work out what I'm doing wrong.

Reproduced on tmux 2.5 (installed via Fedora), 2.6 (installed via Linux Brew) and master (SHA b5c0b2cae2d9b794a3de24afd50d5941eed3fda8).

The initial idea was to try and see if tmux would re-attach to a different session if one closed:

```
set-hook -g session-closed attach-session
```

But, upon further testing, I noticed I didn't seem to be able to make any global hooks.  This is what I ran in the attached server log (generated as per the contributing guidelines):

```
./tmux -f/dev/null set-hook -g session-closed attach-session
./tmux -f/dev/null set-hook -g alert-bell 'run something'
./tmux -f/dev/null set-hook -g alert-activity 'run something'
./tmux -f/dev/null set-hook -g session-created 'run something'
./tmux -f/dev/null show-hooks
```

The final `show-hooks` output is blank.

Removing the `-g` works, but I was hoping to have this set up for every session automatically from my `.tmux.conf`.

Outside tmux:
```
$ echo $TERM
xterm-256color
```

Inside tmux (master version):
```
$ uname -sp && ./tmux -V && echo $TERM
Linux x86_64
tmux master
screen
```

Logs:
[tmux-server-23952.log](https://github.com/tmux/tmux/files/1866751/tmux-server-23952.log)

**Comment by nicm** [comment]
show-hooks -g

But you could probably turn detach-on-destroy off instead.

**Comment by XanderXAJ** [comment]
Well, this isn't exactly my best moment.

Both `show-hooks -g` and `detach-on-destroy off` work exactly as you suggest.  Awesome.

Sorry to bother you!
