### ISSUE TITLE
scrolling in tmux in xterm with alternateScroll on

### ISSUE THREAD

**Issue by agguser** [tmux/tmux#1302]
ArchLinux; tmux 2.6

With `xterm -xrm '*alternateScroll: true'` (the scroll-back and scroll-forw actions send cursor-up and -down keys when xterm is displaying the alternate screen), `less` (a pager) outside `tmux` can be scrolled with mouse wheel, but not if inside `tmux`. How to make it work?

**Comment by nicm** [comment]
Are you sure you are actually using xterm? I don't think xterm will send cursor keys for the mouse wheel.

**Comment by agguser** [comment]
I'm sorry, It is `alternateScroll`, not `alternateScreen`. see `man xterm`

**Comment by nicm** [comment]
You will need to either turn off mouse in tmux so that xterm sends the keys
even when tmux is running, or to configure tmux to do it as well (bind -n
WheelUpPane send Up).

**Comment by agguser** [comment]
It works! Thanks a lot.
