### ISSUE TITLE
Add "--version" to display tmux version

### ISSUE THREAD

**Issue by kenden** [tmux/tmux#1304]
To find the version of programs, `--version` works with many programs. 
Could we add it to tmux to save a few key presses for users?

(Long arguments are more obvious too. With autocompletion, having short options doesn't matter as much as making them easy to remember).

Versions:
```
$ tmux -V  # <--- `tmux --version`, better
tmux 2.6

$ uname -a
Darwin maclocal 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

$ echo $TERM
xterm-256color
```

**Comment by nicm** [comment]
No we are not going to add any long options.

**Comment by nicm** [comment]
tmux is not a GNU program and we do not follow their conventions. -V matches other OpenBSD programs like OpenSSH.
