### ISSUE TITLE
Storing the PID of tmux server somewhere

### ISSUE THREAD

**Issue by hewenyang** [tmux/tmux#1305]
I have not been able to find a command that spawns server in the current process. All servers are created from server_start(), which in turn is called only when an attempt to connect to a server failed. A socket pair is created, but the pid is forgotten.
The pid of the tmux server can be useful in many circumstances. The tmux server is the root of all processes running in it. For example, with the pid we can kill the whole process tree so all processes in the tmux server stop. We can also dump the whole tmux hierachy using criu dump --tree.
Currently I can only find out the pid by running "pidof tmux". However this seems more like a hack because there may be another process named 'tmux' or other instances of tmux, such as 'tmux attach'.
Thus I'd like to either have tmux server's pid stored somewhere, for example when the socket is '/tmp/tmux-1000/default' then create a pid file at '/tmp/tmux-1000/default.pid'. A way to fork a server directly would also be appreciated.

**Comment by nicm** [comment]
There is a format called "pid". Or you could just use pgrep or ps like
every other process.
