### ISSUE TITLE
tmux dies when restarting my X greeter (lightdm), NOT SYSTEMD.

### ISSUE THREAD

**Issue by PegasusEpsilon** [tmux/tmux#1307]
At first, I thought this was the advertised systemd bug, where you log out of a controlling terminal, and all your processes in that terminal get slaughtered, because systemd can't be bothered to work within standards.

So I switched from Manjaro to Artix, because I didn't want systemd anyway, so solve two problems at once, right? Well...It still happens in Artix.

I guess I'll see if screen fares any better.

---

Steps to reproduce:
1) open any xterm you like
2) start tmux
2b) optional: detatch from session
2c) optional: switch to console
2d) optional: attach to tmux session
3) sudo rc-service xdm restart (or whatever your init system uses)
4) notice tmux has now died, taking everything you were working on with it
5) rage

---

System info:
PRETTY_NAME="Artix Linux"
openrc 0.35.5-4
X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.77-1-lts x86_64 
Current Operating System: Linux lithium 4.15.15-1-ck #1 SMP PREEMPT Tue Apr 3 03:08:29 CDT 2018 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-linux-ck root=UUID=76cb71e5-a1fd-4205-b420-167fd10ffbe0 rw rootflags=subvol=artix resume=UUID=386d1ff1-cf02-44d1-9b8f-1038fe301082 pcie_aspm=force panic=10
Build Date: 26 January 2018  09:51:19PM
Current version of pixman: 0.34.0
lightdm 1.26.0
tmux 2.6
TERM=xterm-256color

---

Logs:
[tmux-client-12067.log](https://github.com/tmux/tmux/files/1873658/tmux-client-12067.log)
[tmux-server-12069.log](https://github.com/tmux/tmux/files/1873659/tmux-server-12069.log)

**Comment by nicm** [comment]
tmux is being sent SIGTERM so it exists. You will need to figure out what
is sending this to tmux and configure it not to. Does tmux exit if you just
kill the xterm it was started from? If you start the tmux server from the
console, is it still terminated when you kill xdm?

**Comment by PegasusEpsilon** [comment]
Update:

pegasus@Li⁺:~$ screen -li
No Sockets found in /run/screens/S-pegasus.

Well, I have no idea what to do now. I just don't get to have persistent processes anymore I guess.

**Comment by PegasusEpsilon** [comment]
@nicm It survives restarting the xterm just fine. Nothing goes sideways when started from the console.

**Comment by nicm** [comment]
So it looks like something in the X food chain is killing it. You will need
to find out what that is, I have no idea what any of this stuff you are
using is so I can't really help you, but you could perhaps start by asking
the developers of the desktop environment or of the Linux distribution
you're using. Or whoever maintains their tmux package if you are using
their package.

Or you could just always start tmux from the console.

If you don't think anything is sending SIGTERM you could verify by
attaching strace to the tmux server process (run strace from the console
though).

**Comment by nicm** [comment]
If you run something like:

nohup sleep 1000 &

In xterm, is it also killed when you restart xdm? (Check with pgrep sleep
afterwards)

**Comment by PegasusEpsilon** [comment]
The nohupped sleep is also killed. Here's some strace, though.

[tmux-10995.strace.log](https://github.com/tmux/tmux/files/1873799/tmux-10995.strace.log)
[tmux-10997.strace.log](https://github.com/tmux/tmux/files/1873800/tmux-10997.strace.log)

**Comment by PegasusEpsilon** [comment]
Found elogind config, it also has the KillUserProcesses flag. It was commented it out, I uncommented it, set it to "no", rebooted aaaaand.... Still broken. Goddamnit.

**Comment by PegasusEpsilon** [comment]
@nicm Yes, I noted that. I believe the sending process was PID 2419, elogind. I've double checked the KillUserProcesses flag (which it apparently inherited from systemd) and it seems to be ignoring it. So I've passed the bug on to them. Feel free to close this.
