### ISSUE TITLE
git diff include chinese in tmux display confuse 

### ISSUE THREAD

**Issue by tankywoo** [tmux/tmux#1310]
### Env

- OS: Gentoo
- Tmux: 2.6
- $TERM: outside tmux is xterm-256color, inside tmux is screen-256color

### Describe

With tmux 2.6, inside tmux, git diff include chinese (maybe any non-ascii ?), will display confuse, lines mixed or missed; outside tmux, it display well.

Run tmux without config file, it's still the same situation.

But when I downgrade to tmux-2.3, the display confusion fixed.

**Comment by nicm** [comment]
Please try tmux built from master and if the problem still exists please
show screenshots and logs.

**Comment by tankywoo** [comment]
Hi, I have tried to build tmux from master, and the problem still exists. And it will also display with `cat`.

Build from source master and run command to start server:

```
$ ~/lab/testtmux/tmux/tmux -V
tmux master
$ ~/lab/testtmux/tmux/tmux  -Ltest kill-server
no server running on /tmp/tmux-1000/test
$ ~/lab/testtmux/tmux/tmux -vv -Ltest -f/dev/null new
```

Commonly, if the cursor is in the top of screen ,it display ok, but if it already has text on screen, such as cursor in the middle of screen, the command output will confuse.

This screenshot is `git --no-pager diff` with confuse output, the first time it display ok(clean screen, cursor on top), and the second time it display confused:

![git-diff-err](https://user-images.githubusercontent.com/1169499/38549432-933e1048-3ce6-11e8-9127-3acfe2a9bffb.jpg)

This screenshot is show diff by `tig`, and it works fine:

![git-diff-ok](https://user-images.githubusercontent.com/1169499/38549550-dc92dbb6-3ce6-11e8-93a7-1fc8e870ab4a.jpg)

This screenshot is `cat` file and also display confused:

![cat-err](https://user-images.githubusercontent.com/1169499/38549582-f2a376fe-3ce6-11e8-8741-3c7ec4427842.jpg)

This is the tmux-server.log include `git diff` action with confused text (already change/hidden username, PATH):

[tmux-server-21017.log](https://github.com/tmux/tmux/files/1894076/tmux-server-21017.log)

**Comment by nicm** [comment]
Can you give me the index.html file you are testing with and a screenshot
of what it looks like when it is correct outside tmux?

**Comment by nicm** [comment]
Hmm the text from the log file looks OK to me.

Here is the file I am using [aaa.txt](https://github.com/tmux/tmux/files/1894110/aaa.txt). Can you see if the same (printf "`cat aaa.txt`") is still wrong for you?

![aaa](https://user-images.githubusercontent.com/304243/38550605-dfa7d2e4-3cae-11e8-94d2-382d7a212704.png)

**Comment by tankywoo** [comment]
@nicm 

unchanged index.html file:

```html
{% extends "main/base.html" %}

{% block main_content %}

<div class="col-sm-12">

  <table class="table">
    <thead>
      <tr>
        <th>时间</th>
        <th>IP 地址</th>
        <th class="col-md-4">URL 链接</th>
        <th>显示类型</th>
      </tr>
    </thead>
    <tbody>
      {% for msg in msgs %}
      <tr class="">
        <td>{{ msg['time'] }}</td>
        <td>{{ ip }}</td>
        <td><a href="{{ url }}" target="_blank">{{ url }}</a></td>
        <td>
          <span data-toggle="tooltip" data-placement="top" title="{{ msg['desc'] }}"  >
            {{ cls_map[msg['cls']] }}&nbsp;
            {% if msg['desc'] %}<i class="fa fa-info-circle" aria-hidden="true"></i>{% endif %}
          </span>
          <a href='{{ "%s%s"|format(config['UPLOAD_URL'], msg['upload']) }}' title="点击打开附件"><i class="fa fa-file" aria-hidden="true"></i></a>
        </td>
        <td>测试一下</td>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}
```

after changed:

```html
{% extends "main/base.html" %}

{% block main_content %}

<div class="col-sm-12">

  <table class="table">
    <thead>
      <tr>
        <th>时间</th>
        <th>IP 地址</th>
        <th class="col-md-4">URL 链接</th>
        <th>显示类型 type</th>
      </tr>
    </thead>
    <tbody>
      {% for msg in msgs %}
      <tr class="">
        <td>{{ msg['time'] }} 测试</td>
        <td>{{ ip }}</td>
        <td><a href="{{ url }}" target="_blank">{{ url }}</a></td>
        <td>
          <span data-toggle="" data-placement="top" title="{{ msg['desc'] }}"  >
            {{ cls_map[msg['cls']] }}&nbsp;
            {% if msg['desc'] %}<i class="fa fa-info-circle" aria-hidden="true"></i>{% endif %}
          </span>
          <a href='{{ "%s%s"|format(config['URL'], msg['upload']) }}' title="点击打开附件"><i class="fa fa-file" aria-hidden="true"></i></a>
        </td>
        <td>测试一下</td>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}
```

the simple trigger way: in tmux, `cat` the **changed** index.html first, it's ok, and `cat` it second time (do not flush screen), it will output confused

**Comment by nicm** [comment]
Please attach files as files rather than copy and paste them into the issue.

**Comment by nicm** [comment]
What terminal are you using?

**Comment by tankywoo** [comment]
@nicm 

> Here is the file I am using aaa.txt. Can you see if the same (printf "cat aaa.txt") is still wrong for you?

Yes, the same problem, make sure your first output's parts is scroll to hidden.(**or you can `cat` more than two times**)

> Please attach files as files rather than copy and paste them into the issue.

Got it next time. 😄 

> What terminal are you using?

iTerm2, Build 3.1.5

**Comment by nicm** [comment]
I can't reproduce this at all with either gnome-terminal or rxvt-unicode or uxterm. Can you try a different terminal and see if you can still reproduce?

**Comment by tankywoo** [comment]
@nicm Another discovery..., the machine I used is connected by [`mosh`](https://mosh.org/), for auto connection, and I found if I directly used `ssh`, it works fine.

So, now the problem environment is: mosh + pdsh 😢 

And I will check if mosh has some configuration to handle this.

**Comment by nicm** [comment]
This sounds like a bug in mosh.

**Comment by tankywoo** [comment]
@nicm 

Great, it works! 

Can you please explain the meaning of this setting?

**Comment by nicm** [comment]
This tells tmux not to use the CSI S escape sequence (indn in terminfo) to scroll multiple lines. Clearly this sequence is buggy in mosh, you should report it to them.

**Comment by tankywoo** [comment]
@nicm Got it, thanks for your help. 👍
