### ISSUE TITLE
Let multiple users work in multiple panes in one window simultaneously

### ISSUE THREAD

**Issue by hewenyang** [tmux/tmux#1311]
Is it possible in tmux?
I'd like to create a window which is split into many panes, and let multiple users connect to the same window and work in different panes so they can see each others' progress. It would be very cool if implemented in tmux.

**Comment by edi9999** [comment]
I also like this idea, but I'm totally unaware if it is already possible with the current tmux.

**Comment by nicm** [comment]
This is not possible at the moment.
