### ISSUE TITLE
Show pane names

### ISSUE THREAD

**Issue by pixelcrafter001** [tmux/tmux#1312]
Hey, 
First I'm from Germany my english not the best but i hope you are understand what i mean

I'm use tmux on a V-Server Ubuntu 16.04.4 tmux has the Version 2.6

I have tested some things first 

> tmux set -g pane-border-format "#{pane_index} #T"

> printf '\033]2;My Pane Title\033\\'

> select-pane -T "my title"

this they the command unknown option or will not function

I will show me the names for game server where a pane a server but all show same and i will not stop the server to see what for server is it...
my config is alone mouse aktivate and another layout for the footbar

**Comment by nicm** [comment]
Did you do "set -g pane-border-status top" as well?

**Comment by pixelcrafter001** [comment]
this Option was it thanks for your Help 👍
