### ISSUE TITLE
Remapping vi movement keys

### ISSUE THREAD

**Issue by nathanshelly** [tmux/tmux#1315]
On tmux master, macOS

Just want to clarify given [this changelog](https://github.com/tmux/tmux/blob/master/CHANGES#L235), is it no longer possible to remap for example hjkl movement keys in choose windows?

**Comment by nicm** [comment]
You can do something like this but YMMV:

    bind -n h if -F '#{==:#{pane_mode},copy-mode}' 'send Up' 'send h'

**Comment by nathanshelly** [comment]
Works perfectly, thank you so much!

**Comment by nathanshelly** [comment]
Apologies for reopening this I just realized that sending semicolon doesn't work and can't figure out what sequence of characters will. I tried escaping with a backslash but that didn't seem to change anything (sorry if this is in the man page somewhere and I just didn't find it).

```
bind -n \; if -F '#{==:#{pane_mode},tree-mode}' 'send Right' 'send ;'
```

And here's what I see in the keys table:

<img width="882" alt="key" src="https://user-images.githubusercontent.com/9750687/38783449-c3c50a7a-40c7-11e8-8dee-e8e4a981dd9f.png">

**Comment by nicm** [comment]
You need to escape ; for the config file and for the command parser because if-shell will also parse it when it is executed, so do \\\\\\;

**Comment by nathanshelly** [comment]
Perfect, thanks again!
