### ISSUE TITLE
Please allow create session wihtout windows

### ISSUE THREAD

**Issue by przepompownia** [tmux/tmux#1316]
I would like to create standalone "services" such that each of them:
- assumes that session `x` exists and cannot create new session,
- does not depend of another "service", depends of session `x` only,
- can be enabled separately in any order.

It seems that first I need to create an empty session that can survive without any window. 

I found no mention about such feature (only the server can similar `exit-empty` option). What do you think about add it to sessions?

Currently I have no better idea than create a session with unneeded window that keeps it alive.

**Comment by nicm** [comment]
Why do you need the session to exist? Why not create it when you need it?

**Comment by przepompownia** [comment]
It then have to be created in the exactly one of such "services" (imagine them as systemd user services). Which service has to create session assuming that on some environment I would not like activate this special one and I do not care about the order of running it. Similarly, why some service has to have responsibility of closing session or keeping it alive?

**Comment by nicm** [comment]
This doesn't make any sense to me, I don't know anything about systemd.

I don't think we want sessions without windows.

You can create empty named session groups if that is enough, otherwise I suggest you just manage sessions on demand.
