### ISSUE TITLE
documentation: man page section "new-window"

### ISSUE THREAD

**Issue by UweSauter** [tmux/tmux#1317]
Man page section for `new-window` states option `-t target-window`. I think it should read `-t target-session` as a session where the new window is created is needed, not a target window. A target window makes sense for `split-window` but not for `new-window`

**Comment by ThomasAdam** [comment]
Nope, consider:

```
tmux neww -tsession:index_numer
```

as in:

```
tmux neww -t:5
```

That would create a new window with an index of `5`.  That's a window target, the session is incidental.

**Comment by nicm** [comment]
No, it is a window target, try it...

**Comment by UweSauter** [comment]
Oh. Didn't know I could create windows with arbitray index… well, then it makes sense.
But pane numbering is always sequential?
