### ISSUE TITLE
Format logical AND/OR example incorrect

### ISSUE THREAD

**Issue by neersighted** [tmux/tmux#1319]
```
Linux x86_64 / tmux 2.6
```
The given example for the logical AND/OR directives in the manpage appear to be incorrect:

> ‘||’ and ‘&&’ evaluate to true if either or both of two comma-separated alternatives are true, for example ‘#{||,#{pane_in_mode},#{alternate_on}}’.

The correct syntax appears to be `#{||:#{pane_in_mode},#{alternate_on}}`. The example as given will always evaluate as blank.

Also, on a related note, I'd like to suggest `if -Ft= '#{||:#{mouse_any_flag},#{pane_in_mode}}' 'send -M' 'copy-mode -et='` as the default binding for `WheelUpPane`, as it is much more readable than nested `if-shell`.

**Comment by nicm** [comment]
Yes you are right  will fix the #{|| as soon as I am able to.

Please make a PR or send a diff with your suggested key binding changes.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
