### ISSUE TITLE
set -g mouse breaks scrolling in less

### ISSUE THREAD

**Issue by neersighted** [tmux/tmux#1320]
```
Linux x86_64 / tmux 2.6 / tmux-256color
```

`set -g mouse on` appears to break all scrolling in less for me. This is reproducible with `tmux -f /dev/null`; and then a `tmux set -g mouse on` from inside the session.

Setting mouse to off again appears to fix it. So far I have tested in termite (vte-based) and mintty, both with the same result. tmux's own mouse support works correctly in both these terminals, and other applications (such as a nested tmux or vim/neovim) respond to the mouse correctly.

This can also be reproduced even after resetting all binds (`unbind -a`) and ensuring there are no bindings to `WheelUpPane`/`WheelDownPane`.

**Comment by nicm** [comment]
Less does not support the mouse. Some terminals will send key presses for
the mouse wheel for applications that don't enable the mouse but tmux does
not do this. You can configure it to do so by rebinding the mouse wheel
keys to send Up or Down if mouse_any_flag is not set and send -M otherwise.

**Comment by T1T4N** [comment]
Hello,
I'm pretty new here, but I've been using tmux for quite some time and I can only say good things about it. There is no other tool that has boosted my productivity as much as tmux.
I wanted to share my implementation for what @nicm explained above, in case someone needs it as well.
```
# Emulate scrolling by sending up and down keys if these commands are running in the pane
tmux_commands_with_legacy_scroll="nano less more man git"

bind-key -T root WheelUpPane \
	if-shell -Ft= '#{?mouse_any_flag,1,#{pane_in_mode}}' \
		'send -Mt=' \
		'if-shell -t= "#{?alternate_on,true,false} || echo \"#{tmux_commands_with_legacy_scroll}\" | grep -q \"#{pane_current_command}\"" \
			"send -t= Up" "copy-mode -et="'

bind-key -T root WheelDownPane \
	if-shell -Ft = '#{?pane_in_mode,1,#{mouse_any_flag}}' \
		'send -Mt=' \
		'if-shell -t= "#{?alternate_on,true,false} || echo \"#{tmux_commands_with_legacy_scroll}\" | grep -q \"#{pane_current_command}\"" \
			"send -t= Down" "send -Mt="'
```
Any suggestions and improvements are highly appreciated.
Thanks to everyone associated with the development of this wonderful tool.

**Comment by neersighted** [comment]
Ah, interesting, I had not realized that VTE (and apparently mintty) had added this functionality. I'd suggest you close this then, if you consider it sufficiently resolved. Also, thank you for the example config, @T1T4N. I'll probably make use of it myself if I decide I want to emulate this terminal behavior.

**Comment by dylan-chong** [comment]
@T1T4N Is there a way to make script press the arrow keys three times per scroll event? The scroll speed is a little slow

**Comment by T1T4N** [comment]
@dylan-chong Just copying the ```send -t= Up``` and delimiting with a ```;``` should be enough I think

**Comment by dylan-chong** [comment]
The above solution is quite laggy for me. I found a better solution by using the plugin https://github.com/NHDaly/tmux-better-mouse-mode with `set -g @emulate-scroll-for-no-mouse-alternate-buffer 'on'`

**Comment by pandasauce** [comment]
Simple solution for mintty that does not require changes to tmux configuration: hold down shift key before scrolling the wheel. I believe this is configurable under its Options -> Window -> Modifier for scrolling

**Comment by mckellyln** [comment]
I found also to not use the -X option to less, so that it uses the alternate screen and then can work with tmux mouse sending Down etc.

**Comment by mmonaco** [comment]
Note: Newer versions of `less` have a `--mouse` and `--wheel=lines=#` options. So, for example:

`export LESS='--mouse --wheel-lines'`

**Comment by noscript** [comment]
For those who's stuck with older less https://github.com/noscript/tmux-mighty-scroll
