### ISSUE TITLE
Feature Request: Different Status lines for clients connected to the same session

### ISSUE THREAD

**Issue by StopMotionCuber** [tmux/tmux#1321]
Hey all,
I wanted to request a feature to be able to have different status lines on a client basis.
The purpose of this is that I'm trying to implement functionality for the status line to detect whether that client is connected via ssh. I'm doing this by traversing the parent pid's from `tmux display -p '#{client_pid}'`.
Another use case for this would be status lines with a different width depending on the clients width.
Right now this is working for the current active client, but the other clients will obtain the same status bar.

**Comment by StopMotionCuber** [comment]
OK, is there a way to also configure them on a per-client basis? I'm thinking of a different `tmux set status-left` on the same session for different clients

**Comment by nicm** [comment]
You can use client formats such as client_pid and they will evaluate differently for each client but there are no client options and we are very unlikely to add them.

**Comment by nicm** [comment]
You can do #(myscript #{client_pid}) and it would invoke your script separately for each client.

**Comment by StopMotionCuber** [comment]
Thanks, this is exactly what I was looking for.
