### ISSUE TITLE
window-active-style default color

### ISSUE THREAD

**Issue by dylnmc** [tmux/tmux#1325]
v2.7 in urxvt (linux)

---

When I have this set in tmux conf:

```
set -g window-style 'fg=colour252,bg=colour0'
set -g window-active-style 'fg=white,bg=default'
```

I get this result:

![screenshot from 2018-04-22 01 18 38](https://user-images.githubusercontent.com/7635158/39091787-2ac69290-45cb-11e8-8c0d-b051a1b62511.png)

You can see that the "active" pane does not use the "default" color, as I told it to.

---

edit: same issue with the settings for `status-left` and `status-right` etc.

**Comment by nicm** [comment]
Show logs please.

**Comment by dylnmc** [comment]
what logs?

to recreate all you have to do is remove your tmux conf and put this in ~/.tmux.conf:

```
set -g window-style 'bg=red'
set -g window-active-style 'bg=default'
```

**Comment by nicm** [comment]
No, that isn't how it works. window-style sets the default, window-active-style is applied on top.

**Comment by dylnmc** [comment]
oh. Ok, then is there a `window-inactive-style`? Or is there a way to achieve this (`default` for active window and `black` for inactive window)?

Thanks for clearing up the issue and helping me understand how it works internally.

**Comment by nicm** [comment]
There isn't, someone did talk about adding a colour meaning "actual default" before but didn't implement it.

**Comment by dylnmc** [comment]
so, WONTFIX? .....

**Comment by jtmkrueger** [comment]
I just ran into this as well. I can set the 2 colors specifically, but it seem that once you set the `window-style` it is then considered default with relation to `window-active-style`. @nicm is this closed because we should take this as expected behavior (_"It's a feature, not a bug"_)?

**Comment by guiambros** [comment]
Likewise; I ran into this a while ago. There's no such thing as a '_default_' color, but using specific colors works well. My solution was to use specific colors for active/inactive panes.

> set -g window-style 'fg=colour247,bg=colour236'
set -g window-active-style 'fg=colour255,bg=black'

_(Unrelated, but as an added bonus, I'm also using `tmux select-pane -P bg#xxxxxx.` to change the pane color in response to specific events, like when I `sudo su root`)_

**Comment by bfrg** [comment]
I ran into this as well a few months ago. 
In `tmux` 2.9 we can now specify a `terminal` color.
Example:
```
set-window-option -g window-active-style bg=terminal
set-window-option -g window-style        bg=black
```

**Comment by jtmkrueger** [comment]
That's really nice @bfrg thanks for adding that here!
