### ISSUE TITLE
Searching(Ctrl-s) in choose-tree will not search in pane_title

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#1326]
Linux x86_64
tmux master
xterm-256color

I changed the default `choose-tree` command to show more info.

    bind w choose-tree -F '#{?pane_format, <#{pane_tty}> #{pane_current_command} "#{pane_title}",#{?window_format,#{window_name}#{window_flags} (#{window_panes} panes)#{?#{==:#{window_panes},1}, "<#{pane_tty}> #{pane_title}",},#{session_windows} windows#{?session_grouped, (group ,}#{session_group}#{?session_grouped,),}#{?session_attached, (attached),}}}'

So the list will be something like the following screenshot:

![screenshot_2018-04-24_17-38-25](https://user-images.githubusercontent.com/2135996/39179257-6f1b73ee-47e6-11e8-9fca-c2212a23d4c7.png)

But when the list is long and the info in the list is complicated, `Ctrl-s` will not get what I want quickly, and it seems `Ctrl-s` only searches certain elements, not from all the info in the list, such as tty or path in the list.

So is is able to search (Ctrl-s) string in the whole list, just like grep a file?

**Comment by nicm** [comment]
It searches session or window names or the pane current command,

**Comment by c02y** [comment]
Yes.

But when the list is long and the info in the list is complicated, `Ctrl-s` will not get what I want quickly.

So is is able to search (Ctrl-s) string in the whole list, just like grep a file?
