### ISSUE TITLE
tmux commands from a shell will sometimes choose the wrong session

### ISSUE THREAD

**Issue by TauPan** [tmux/tmux#1328]
I'm running tmux 2.7 (from openSUSE utilities repository).
```shell
> uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.7
screen-256color
```

Sometimes if I run a tmux command in a shell inside, e.g. `tmux neww` or `tmux copy-mode -u` (I've bound that to a key inside zsh.), the command will be executed in a different session, in a terminal window next to the current one. The session inside that window does not even contain the current shell.

(We've talked about this on irc, today it finally spontaneously occured again.)

**Comment by nicm** [comment]
Please apply this to add some more logging then rebuild tmux, restart tmux entirely then similarly reproduce and show me the new logs: [abc.diff.txt](https://github.com/tmux/tmux/files/1947133/abc.diff.txt)

**Comment by nicm** [comment]
No?

**Comment by TauPan** [comment]
I had to wait a week before the bug occured with unpatched tmux and I've been running the patched master version for a couple of days now (and there were a couple of days of holiday... this only occurs on my multi-monitor setup at work for me). We have to be a little more patient, I'm afraid.

**Comment by TauPan** [comment]
(2.7-32-gd24bd739 right now... there's also a chance that this might "inadvertently" have been fixed  since 2.7)

**Comment by TauPan** [comment]
Ok, finally caught the bug again. Here's a log (This time I redacted it with search + replace, so there should be no need to delete it).
[tmux-server-5677-redacted.log](https://github.com/tmux/tmux/files/2004887/tmux-server-5677-redacted.log)

Bug was hit with 2.7-32-gd24bd739 + your patch.

**Comment by nicm** [comment]
Try this please: 
[x.diff.txt](https://github.com/tmux/tmux/files/2005369/x.diff.txt)

**Comment by TauPan** [comment]
Happened again today.
[tmux-server-11811-redacted.log](https://github.com/tmux/tmux/files/2047726/tmux-server-11811-redacted.log)

**Comment by TauPan** [comment]
Trying again with master because of #1354

**Comment by nicm** [comment]
Does this still happen?

**Comment by TauPan** [comment]
Nope, not in the 7.5 workdays since I switched to 2.7-61-g54cd292f.

**Comment by nicm** [comment]
I assume this is no longer happening.

**Comment by nicm** [comment]
Let me know if it is of course :-).
