### ISSUE TITLE
choose-tree format strings

### ISSUE THREAD

**Issue by enanajmain** [tmux/tmux#1330]
I have been trying to use the choose-tree command with format option `-F`. But I can't find out how to do it. What is the default format for this command? When I give a format string, it gets collected for all items. But I want different formats for different items, e.g. sessions, windows, panes. For sessions, I want

    #{session_name}:(number of windows) (attached or not)

For windows, I want

    #{index}: #{window_name}

How can I achieve that?

The tmux manpage has info about the format variables, but no way to use them in choose-tree/choose-buffers etc.

**Comment by nicm** [comment]
The default is:

#{?pane_format,#{pane_current_command} "#{pane_title}",#{?window_format,#{window_name}#{window_flags} (#{window_panes} panes)#{?#{==:#{window_panes},1}, "#{pane_title}",},#{session_windows} windows#{?session_grouped, (group #{session_group}: #{session_group_list}),}#{?session_attached, (attached),}}}

**Comment by nicm** [comment]
You need to do something like:

set -g prefix None
bind -n C-b switchc -Tprefix\; set display-time 0\; display-message "Prefix pressed"\; set -u display-time

**Comment by enanajmain** [comment]
Superb!
