### ISSUE TITLE
new-session sets the working directory to literal "."

### ISSUE THREAD

**Issue by lochlainn** [tmux/tmux#1331]
Platform: Ubuntu 16.04, Mac OS X Sierra
Problem: When creating a new tmux session with `new-session`, without specifying a specific directory, the new session starts with the current directory set to a period.  This only happens when calling new-session from inside an existing session.

No config needed to reproduce this.  Here's an example of what I mean:
```
$ tmux new-session -s test1
[in test1]
$ echo $PWD
/home/lochlainn/src/tmux
[<prefix> :new-session -s test2]
$ echo $PWD
.
```
I was able to fix it on master with [the attached diff](https://github.com/tmux/tmux/files/1962101/0001-fix-incorrect-directory-in-new-session.patch.txt), but I'm not sure if this is how you'd want to do it.

**Comment by nicm** [comment]
It should try the session as well if one is present, and there is already a function to do this we can use. Try this instead please: [x.diff.txt](https://github.com/tmux/tmux/files/1962202/x.diff.txt)

**Comment by nicm** [comment]
Actually, this is not right.

**Comment by nicm** [comment]
We need to check the client, then the target session (if any), then the client session. If all those fail, I don't think it is terribly useful to use the server working directory, so let's use the user's home instead. Please try this: [y.diff.txt](https://github.com/tmux/tmux/files/1962261/y.diff.txt)

**Comment by dlipovetsky** [comment]
@nicm I'm affected by this issue. It's reproducible in master. Did you close this by mistake?

**Comment by nicm** [comment]
Does the diff above fix it for you?

**Comment by dlipovetsky** [comment]
@nicm Did you close this issue by mistake? I can reproduce this issue on master, and it affects my workflow.

**Comment by lochlainn** [comment]
Sorry, I was AFK for the past few weeks.  y.diff fixes the issue for me as well.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by dlipovetsky** [comment]
Thank you for fixing this @nicm!
