### ISSUE TITLE
Add support for scroll wheel while viewing man pages

### ISSUE THREAD

**Issue by jtpereyda** [tmux/tmux#1333]
Currently, with mouse mode enabled, viewing a man page in tmux and using the scroll wheel, tmux tries to go backward in the buffer rather than passing the scroll info to the command. It would be nice if tmux could somehow pass mouse keys instead of trying to scroll an empty buffer.

It is already possible to do this with vim by enabling mouse mode in both vim and tmux. Not sure what it would take to achieve this with man.

This answer explains the situation and what tmux might be able to do: https://superuser.com/a/990887/72210

![image](https://user-images.githubusercontent.com/244969/39541816-b2fec122-4dfb-11e8-9d36-b76e1ca3c5e4.png)

### Version info
```
> uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.1
screen-256color
```

**Comment by nicm** [comment]
You can do this by binding the wheel to send Up and Down when man is running. Or you could go ask the man developers to support the mouse same as vim does.

**Comment by nicm** [comment]
https://github.com/tmux/tmux/issues/1320 has an example of the former.

**Comment by jtpereyda** [comment]
@nicm thank you for the reference; I adapted the workaround but switched to three keys per mouse wheel scroll:
```
# Emulate scrolling by sending up and down keys if these commands are running in the pane                                                                                                                   
tmux_commands_with_legacy_scroll="nano less more man git"                                                                                                                                                   
                                                                                                                                                                                                            
bind-key -T root WheelUpPane \                                                                                                                                                                              
    if-shell -Ft= '#{?mouse_any_flag,1,#{pane_in_mode}}' \                                                                                                                                                  
        'send -Mt=' \                                                                                                                                                                                       
        'if-shell -t= "#{?alternate_on,true,false} || echo \"#{tmux_commands_with_legacy_scroll}\" | grep -q \"#{pane_current_command}\"" \                                                                 
            "send -t= Up Up Up" "copy-mode -et="'                                                                                                                                                           
                                                                                                                                                                                                            
bind-key -T root WheelDownPane \                                                                                                                                                                            
    if-shell -Ft = '#{?pane_in_mode,1,#{mouse_any_flag}}' \                                                                                                                                                 
        'send -Mt=' \                                                                                                                                                                                       
        'if-shell -t= "#{?alternate_on,true,false} || echo \"#{tmux_commands_with_legacy_scroll}\" | grep -q \"#{pane_current_command}\"" \                                                                 
            "send -t= Down Down Down" "send -Mt="'
```

**Comment by jtpereyda** [comment]
I wonder if it would be appropriate for tmux to implement a more generic workaround, similar to other terminal emulators (quoting from the [SuperUser Answer](https://superuser.com/a/990887/72210)):

> When terminology (in fact most of the terminal emulators) realizes that these two conditions are met (i.e. alternate screen, no interest in mouse), it converts scroll events into up and down keystrokes. So less doesn't see any mouse event, it only sees keypresses.

It sounds like this is a common feature for terminal emulators and may therefore be appropriate functionality for tmux; it would be more generic than hardcoding command names.

**Comment by nicm** [comment]
You don't have to hardcode command names, you can just check the formats you want (alternate_on, mouse_any_flag, pane_in_mode).

**Comment by jtpereyda** [comment]
@nicm Just curious, what don't you like about this feature being on by default? Given that one condition would be an alternate screen, I would expect that typically mouse scrolling won't do anything useful anyway.

**Comment by jtpereyda** [comment]
@nicm what are some applications that would meet those conditions but for which arrow keys for scrolling would not be appropriate?

**Comment by nicm** [comment]
Why don't you configure it for the applications you want?

**Comment by jtpereyda** [comment]
I do have it configured, but I'm just trying to determine if this might be a helpful feature for tmux in the future. Given that it's a common terminal emulator feature, I figure maybe it makes sense for tmux too. It seems like a lot of users would benefit without even noticing.

I'm not trying to ask you to do this right now, but if we can determine that it would be helpful maybe I or someone else could impelement it sometime.
