### ISSUE TITLE
[Mac 10.13.4] [tmux 2.6] Error: mouse wheel scrolling receiving "Repeat count invalid" error message

### ISSUE THREAD

**Issue by arooni** [tmux/tmux#1334]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

Behavior:
1) open iterm (latest) and use the wheel mouse wheel to scroll up
2) see error message "Repeat count invalid" on the bottom status line.  iterm doesnt scroll
3) sigh
4) write this issue on github

as an aside, I have the same tmux config running on ubuntu 16.04 and it scrolls just great.  Using tmux version 2.2 there.   just for fun i updated my tmux version on mac from 2.6 to 2.7 and got the same beahvior.

Let me know if more info is needed such as my tmux config file.

**Comment by arooni** [comment]
I thought I was being poetic & entertaining back to the drawing board... lol.  

my tmux config file: https://gist.github.com/a0129d4c98134a65ce24183e0c1df03b
my mac-osx specific config referenced: https://gist.github.com/d350be88553b3fc00c76bce94dfc6297

I did verify:
1) disabling the tmux better mouse plugin and reloading tmux didn't seem to have an effect.

any other suggestions?  would love to get it scrolling.  thanks!

**Comment by nicm** [comment]
This seems likely to be a problem with one of the plugins, try taking them
out.

**Comment by arooni** [comment]
For whatever reason it's working great now... not sure why it started cooperating but I'm not complaining.

**Comment by nicm** [comment]
OK good stuff.
