### ISSUE TITLE
incorrect pane arrangement in newer tmux versions

### ISSUE THREAD

**Issue by sassmann** [tmux/tmux#1335]
Running the following script gives an incorrect layout.
#/bin/sh
tmux -f/dev/null  new-session -d -s test
tmux split-window -v -p 55 -t 0
tmux split-window -h -p 67 -t 0
tmux split-window -h -p 50 -t 1
tmux split-window -h -p 67 -t 3
tmux split-window -v -p 25 -t 3
tmux split-window -h -p 33 -t 5
tmux split-window -v -p 33 -t 6
tmux split-window -v -p 50 -t 7
tmux attach-session -t test

Using tmux 2.5 the layout is still as expected. However with tmux 2.6 and 2.7 the layout looks incorrect. Pane sizes are different from what you would get from running the splits from inside the session.
Tested this with xterm and gnome-terminal (terminal size of approx. 390x110).

uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.7
xterm-256color

**Comment by nicm** [comment]
You now need to specify the starting size for detached sessions to new-session or you will get 80x24.

**Comment by sassmann** [comment]
Thanks! Specifying -x and -y and the layout looks right again. May I ask why this is necessary now? Version 2.5 has been able to figure out those values by itself.

**Comment by nicm** [comment]
It is not always possible to know what the size is so we use 80x24.

**Comment by sassmann** [comment]
Without having looked closely yet, would you accept a patch using $LINES and $COLUMNS from the environment (if available) instead of the 80x24?

**Comment by nicm** [comment]
No, it has the actual size from the client but we do not use it because we can't do so consistently. You could make it so that if you do -x- -y- it uses them if possible.

**Comment by sassmann** [comment]
Roger, I'll take a look.
