### ISSUE TITLE
tmux downgrades 256-colour palette to 16-colour palette in a 24-bit-colour-capable terminal

### ISSUE THREAD

**Issue by marienz** [tmux/tmux#1337]
tmux 2.7 or tmux master (built from 91b220525b0406763dafb6698d2741bec580bc10).
uname -sp: Linux Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
tmux is running inside st-0.8.1, using the terminfo database from ncurses-6.1.
TERM=st-direct outside of tmux, tmux-256color or screen-256color inside tmux.

(TERM=st-direct has the "RGB" flag set, "colors" set to 16777216, and setaf/setab strings that use `\e[38;2;R;G;Bm` / `\e[48;2;R;G;Bm` for inputs > 8.)

With tmux running inside a 24-bit color terminal ("RGB" terminfo flag set and "colors" terminfo number > 256), an application inside tmux that uses the 256-colour palette (`\e[48;5;Nm`) gets its colours approximated using the 16-colour palette. If the application uses 24-bit colour (I tested using `\e[48;2;R,G,Bm`), that displays correctly.

The problem can be worked around by running tmux with `-2`, or by using `set -g terminal-overrides "st-direct:colors=256"` (note: not suggesting that terminal override is reasonable, only that the value of "colors" matters). With either of those, 256-colour and 24-bit colour inside tmux both display correctly.

If I read the code right, the conversion to 16-colour happens in tty_check_fg / tty_check_bg, where we hit the "256-colour colour, but not a 256 colour mode" code. With `-2` or the terminal override, we skip that conversion and hit fallback_256 in tty_try_colour.

Would it make sense for tmux to handle this case by converting 256-colour to 24-bit colour in tty_check_fg / tty_check_bg when the terminal has colours != 256 and supports 24-bit colour (has TTYC_SETRGBF / TTYC_SETRGBB)? That seems a bit more future-proof than relying on the terminal supporting the hardcoded sequence from fallback_256, and it's similar to the conversions tmux already performs.

(Note using the terminal's setaf/setab with 256 colours would not work with this terminfo entry: I didn't change the code to confirm it, but I'd expect all colors to show as shades of blue if tmux trusted setaf/setab instead of the hardcoded "usual sequence").

**Comment by nicm** [comment]
Does this fix it?
~~~~
--- tty-term.c  4 Feb 2018 10:10:39 -0000       1.58
+++ tty-term.c  7 May 2018 13:26:03 -0000
@@ -489,7 +489,7 @@ tty_term_find(char *name, int fd, char *
        }

        /* Figure out if we have 256. */
-       if (tty_term_number(term, TTYC_COLORS) == 256)
+       if (tty_term_number(term, TTYC_COLORS) >= 256)
                term->flags |= TERM_256COLOURS;

        /*

**Comment by marienz** [comment]
Yup, that fixes it for me.

**Comment by nicm** [comment]
Applied a slightly different change to OpenBSD now, will be in GitHub later. Thanks!
