### ISSUE TITLE
%if conditional in config file with shell command's output

### ISSUE THREAD

**Issue by tardypad** [tmux/tmux#1340]
tmux 2.7 on Arch Linux

I've been trying to make use of the `%if %else`conditionals in my config file to make my configuration dependant on some host characteristics such as `is xdg-open present?`, `is there a DISPLAY?`,...
Such characteristics are not present in the FORMATS as predefined variables so I tried to use the expansion of a shell command's output.

For example
```
%if #{!=:#(ls /usr/bin/xdg-open 2> /dev/null),}
```
```
%if #{!=:#(echo $DISPLAY),}
```

However it seems such command's output are not properly expanded inside those conditionals.
I've tried for example a "simple" `%if #{==:#(echo yo),yo}` which is not working correctly either.
Now I know that such expansions are a bit special, that tmux doesn't wait for the command to finish and cache the result and so on.
I don't think it was designed to be used within such conditionals but since the doc said that the argument was "expanded as a format", I gave it a try :)

If such expansion is indeed not supposed and planned to work there:
- Is there another way (which I missed) to achieve what I'm trying here?
- If not, would it possible at least to add the possibility to do a conditional based on an environment variable or such?

Right now my workaround is to use multiple conditionals checking hardcoded hostnames using the `host_short` FORMATS predefined variable. But it is not really ideal.

Thanks

**Comment by nicm** [comment]
DISPLAY may work, you can just do #{DISPLAY}.

#() are not expanded for %if so your best bet for commands is to write a
shell script that does something like:

if mycondition; then
    tmux whatever
    tmux whatever-else
fi

And run it via run-shell from .tmux.conf.

**Comment by tardypad** [comment]
I've been testing a bit and indeed I can use any **exported** variable in such a way!
`%if #{DISPLAY}`
`%if #{HAS_XDG_OPEN}`
which will evaluate to `"true"` if the variable is defined and not 0 (maybe some other edge cases too)

Maybe it'd be worth adding it the man pages?

In any case, that's good enough for my use case so I'm gonna close this

Thanks for the tip and quick response again
