### ISSUE TITLE
\033ktitle\033\\ and #W vs #T (behavior contradicts docs I think)

### ISSUE THREAD

**Issue by jettero** [tmux/tmux#1342]
> tmux distinguishes between names and titles.  Windows and sessions have names, which may be used to specify them in targets and are displayed in the status line and various lists: the name is the tmux identifier for a window or session.  Only panes have titles.  A pane's title is typically set by the program running inside the pane using an escape sequence (like it would set the xterm(1) window title in X(7)).  Windows themselves do not have titles - a window's title is the title of its active pane.

It doesn't seem to me the `\033kTITLE HERE\033\\` strings update the #T like the docs seem to say they should... it updates #W and #T remains the hostname no matter what.

So should xterm titles update #W or #T? Should #T remain always the same, in which case the docs seem to be wrong, or should #W just follow the currently selected #T and #T should update like the docs say?

One or the other seems to be wrong for me. It's possible I changed some setting or another that's messing up the behavior.

**Comment by nicm** [comment]
\033k renames the window, you want OSC 2 (\033]2;) to change the pane title.

**Comment by jody-frankowski** [comment]
I also had a hard time understanding this part of the documentation:
`Windows themselves do not have titles - a window's title is the title of its active pane.`

I think it can be resumed by:
* `\033k` changes `#W` if `allow-rename` is `on`
* `\033]2;` or `\033]0;` change `#T`

`#W` is unique per window and is used in `window-status-format` which equals to `#I:#W#F` and is what users usually see automatically changing.

So overall I don't see how this sentence can be true.

**Comment by nicm** [comment]
I don't understand what you are asking.

**Comment by jody-frankowski** [comment]
Basically I'm saying that with my understanding of the default workings of tmux, the phrase ` Windows themselves do not have titles - a window's title is the title of its active pane.` is wrong.

**Comment by jody-frankowski** [comment]
So I guess you are neither referring to `#W` nor `window-status-format`. If that is so, I guess I don't understand what a window title is.

**Comment by nicm** [comment]
#W is window name...

**Comment by nicm** [comment]
I don't know how I can explain it any better than the manual. These are all literal quotes:

* tmux distinguishes between names and titles
* Windows and sessions have names
* Only panes have titles
* A session's name is set with the new-session and rename-session commands.
* A window's name is set with one of: ...  2. An escape sequence: $ printf '\033kWINDOW_NAME\033\\'
* A pane's title can be set via the OSC title setting sequence, for example: $ printf '\033]2;My Title\033\\'

And in the list of formats, not more than 100 lines above the section about names and titles:

* pane_title             #T       Title of pane
* window_name            #W       Name of window

**Comment by nicm** [comment]
The bit you seem to have trouble with:

    Windows themselves do not have titles - a window's title is the title of its active pane.

Just means that a window does not itself have a title - clearly, because "only panes have titles" - but if you ask for the title for a window, you will get the title of its active pane.

So if you put #T or #{pane_title} in window-status-format (which is a window option which describes a window, not a pane), you will not get the window title (it doesn't have one, only panes have titles), but the title of the window's active pane.
