### ISSUE TITLE
Nothing compiles under tmux

### ISSUE THREAD

**Issue by shoober420** [tmux/tmux#1344]
I'm using git master builds of tmux, and the alacritty terminal emulator. No matter what package I try to compile while under tmux, it freezes during a package compilation. I tried tmux with the "st" terminal emulator as well, and same results. Any package I try to compile, will freeze and I have to kill the pane.

**Comment by shoober420** [comment]
I'll post some build logs when I get home.

**Comment by nicm** [comment]
No, tmux logs please.

**Comment by shoober420** [comment]
What do you mean by tmux logs?

**Comment by shoober420** [comment]
Ok, I ran tmux with "tmux -vvvv" and got these logs. I've been trying to compile this package and many others and they all freeze at the same places everytime.

[tmux-client-3240.log](https://github.com/tmux/tmux/files/2003244/tmux-client-3240.log)
[tmux-out-3242.log](https://github.com/tmux/tmux/files/2003245/tmux-out-3242.log)
[tmux-server-3242.log](https://github.com/tmux/tmux/files/2003246/tmux-server-3242.log)

**Comment by nicm** [comment]
There is nothing being sent here that will cause tmux to make a pane hang, it seems most likely this is a problem with the last command that is run ("./configure  '--prefix=/usr' '--disable-static'"?). Are you sure your configure script is not playing silly games with /dev/tty or something like that?

**Comment by nicm** [comment]
What do you see if you run configure yourself with "sh -x ./configure ..."?

**Comment by shoober420** [comment]
When I run that command, it still stops compiling at the same spot "checking build system type..."

**Comment by shoober420** [comment]
[tmuxthing.txt](https://github.com/tmux/tmux/files/2005170/tmuxthing.txt)

**Comment by nicm** [comment]
This doesn't show anything really. What is in your configure script? Is this a standard autoconf script?

**Comment by shoober420** [comment]
Nothing is a stretch, some things do compile. Like alacritty compiles, it uses some weird compilation software. Anything that involves GCC doesn't compile.

**Comment by nicm** [comment]
This sounds like a problem with autoconf or your environment not with tmux.

**Comment by chros73** [comment]
I also doubt it's a tmux issue but a system/user error instead. I compile regularly under different tmux versions without having any issues, and since you're the first user to report such things out of 10 thousands ... :)

**Comment by shoober420** [comment]
Everything compiles fine under any terminal I use. It's only under tmux do I have issues compiling things, which leaves me puzzled. I don't know where to begin to diagnose the issue.

**Comment by nicm** [comment]
My bet is something in the environment is messing with detecting the OS type. Configure scripts are just shell scripts so you should be able to look at them and add debugging or comment bits out to find it.

**Comment by shoober420** [comment]
My bad homie, I decided to go with kitty
