### ISSUE TITLE
Question: about pane_current_command

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#1345]
Hi,

Is this possible at all I am trying to customise ```window-status-current-format``` like this
```set -g window-status-current-format "#{?window_name,#{window_name},#{?pane_current_command,#{pane_current_command}} #{window_index}}"```  I have tried it  but results are not what i want.

basically what I want is this.

showing only ```1``` when there is no command running,  if I run ```vim``` to replace ```1``` with ```vim```, once I exit the ```vim``` to go back to ```1```

no matter what I do it always ends up showing zsh or blank.

Thanks

**Comment by nicm** [comment]
pane_current_command will only be unset if it actually fails which will be unlikely, you will need to test for it explicitly containing zsh.

But you would probably be better changing automatic-rename-format, something like:

set -wg automatic-rename-format "#{s/zsh//:pane_current_command}"
set -wg window-status-current-format '#{?window_name,#{window_name},#{window_index}}'

**Comment by lanox** [comment]
Thanks @nicm. Will give it a try and report back.

**Comment by lanox** [comment]
@nicm it works like a charm thanks so much, only one thing I realise was, when exiting automatic rename doesn't happen till i don't press any key then it changes to 1.

**Comment by lanox** [comment]
@nicm it seem to work fine however sometime status bar will not change till I don't press a key in terminal then it changes.

e.g:  running vim , pane changes, I exit vim pane will still say vim, as soon as I start typing it will change back to 1.

**Comment by nicm** [comment]
Yes that is expected, checking pane_current_command is expensive so we do
not do it unless something changes.

**Comment by lanox** [comment]
thanks @ncim, much appreciated.

**Comment by lanox** [comment]
@nicm last question, I have tried playing with the spaces and adding few things but could not get it to display how I want it. I am assuming that is because of process ? and the way its captured.
while the status bar is active look exactly how i want it.
![screen shot 2018-05-24 at 5 20 55 pm](https://user-images.githubusercontent.com/7599183/40470436-d6730b68-5f76-11e8-9d74-566f7d6c7ff2.png)
however as soon as I change to another pane the spacing between current process and index id is not equal. ( as you can see next to number 1 and at the end of vim spacing is different.)
![screen shot 2018-05-24 at 5 23 06 pm](https://user-images.githubusercontent.com/7599183/40470558-297abf72-5f77-11e8-9acd-3670ebf3ece4.png)

I was wondering is there a way to make the spaces before 1 and after vim be the same ? 

here is my section from tmux.conf
```
set-window-option -g automatic-rename on
set -wg automatic-rename-format "#{s/zsh//:pane_current_command}"
set -g window-status-current-format "#{?window_name,#{window_name},#{window_index}}#{?window_zoomed_flag, ZOOMED,}"
```


Thanks so much and sorry I am just been pedantic.

**Comment by nicm** [comment]
You mean the way there is an extra space, so "vimAAA2" and "vimAA2" (where A=space)?

There shouldn't be extra spaces in pane_current_command, do you see them when you do eg tmux display -p '#{pane_current_command}' in the shell?

What do you have in window-status-format as well?

**Comment by lanox** [comment]
@nicm what I would like to have is following scenario
If active pane with current command 
"AvimA" 
non active pane
"A1AvimA"
if no current command running 
"A1A"

At the moment I am having this scenario:

if active pane with current command 
"AvimA" <-- This is good ( nothing to fix)
non active pane
"A1Avim"<--- Not good, I would like to have A(extra space after vim)
if no current command running 
"A1A" <-- This is good (nothing to fix)

this is  what I have in windows-status-format.
```
setw -g window-status-format "#[fg=colour245,bg=colour236] #I #[fg=colour245,bg=colour236]#W"
```

**Comment by nicm** [comment]
You have an extra space at the start of window-status-format?

**Comment by lanox** [comment]
sorry I am not sure what you mean.

**Comment by nicm** [comment]
~~~~
setw -g window-status-format "#[fg=colour245,bg=colour236] #I #[fg=colour245,bg=colour236]#W"
                                                          ^ -- there is a space here
~~~~

**Comment by nicm** [comment]
tmux will always add a space after each window so you will need to bear that in mind.

**Comment by lanox** [comment]
I have tried that as well however this is how it looks
<img width="143" alt="screen shot 2018-05-24 at 7 19 56 pm" src="https://user-images.githubusercontent.com/7599183/40476511-8f9fe7b8-5f87-11e8-9883-08b2dfc7f230.png">

as you can see it looks like "1 vim" I would like to add a space at the front of 1 and at the end of vim, "A1AvimA" 

however when pane with no running command is not active it ends up looking like this 
<img width="145" alt="screen shot 2018-05-24 at 7 24 24 pm" src="https://user-images.githubusercontent.com/7599183/40476897-85787d8a-5f88-11e8-9f43-86a4729d97bb.png">
that is why I have a space before #I and after.
Yes, i could remove both spaces before #I and after but it looks like this 
<img width="113" alt="screen shot 2018-05-24 at 7 29 52 pm" src="https://user-images.githubusercontent.com/7599183/40477077-e87cf8fc-5f88-11e8-9a61-aaca125946ef.png">


sorry I dunno how to explain it any better

**Comment by nicm** [comment]
You can't add a space at the front without having two spaces in between, because tmux will add one itself.

**Comment by nicm** [comment]
tmux will always display windows as "AxBxCxDxE" where x = space.

So if you have extra spaces at start or end you will end up with "yAxyBxyCxyD" or "AyxByxCyxDy"  respectively where x = tmux's space and y = your space.

**Comment by lanox** [comment]
Okay, so to wrap this up as I am sorry to bother you with this.
my current settings with out any spaces added by me
```
set-window-option -g automatic-rename on
set -wg automatic-rename-format "#{s/zsh//:pane_current_command}"

# active window title colors
set -g window-status-current-format "#[fg=colour241,bg=colour252,bold]#{?window_name,#{window_name},#{window_index}}#[fg=colour135]#[fg=colour1,bold]#{?window_zoomed_flag, ZOOMED,}#[fg=colour148,bg=colour236,nobold,nounderscore,noitalics]"
set -g window-status-format "#[fg=colour245,bg=colour239]#I#[fg=colour245,bg=colour239]#W"
```
when second pane is active looks like this
<img width="103" alt="screen shot 2018-05-24 at 7 43 23 pm" src="https://user-images.githubusercontent.com/7599183/40477829-c8dd727c-5f8a-11e8-92b3-29c2405148d3.png">

when vim pane is active
<img width="85" alt="screen shot 2018-05-24 at 7 43 29 pm" src="https://user-images.githubusercontent.com/7599183/40477843-d32f1302-5f8a-11e8-85ba-e1668f822185.png">

You are saying that I can't add space in front and at the back ? so that both scenarios are covered

**Comment by nicm** [comment]
Oh I see what you are asking now.

If you want a space that only appears when there is a command you will need to put it inside the #{?}. What about this:
~~~~
set -wg automatic-rename-format "#{s/ksh//:pane_current_command}"
set -g window-status-current-format "#[fg=colour241,bg=colour252,bold] #{?window_name,#{window_name},#{window_index}}#[fg=colour135]#[fg=colour1,bold]#{?window_zoomed_flag, ZOOMED,}#[fg=colour148,bg=colour236,nobold,nounderscore,noitalics]#[bg=colour252] "
set -g window-status-format "#[fg=colour245,bg=colour239] #I #[fg=colour245]#{?window_name, #{window_name},}"

**Comment by nicm** [comment]
If you want " #I " sometimes and " #I #W " other times you will need to make the second space in the latter only appear when #W is non-empty, or you will have two spaces. Or like your original example, no space.

So do #{?window_name,#{window_name} ,} instead of #W so you get a trailing space only when it is present.

**Comment by lanox** [comment]
@nicm  you are a legend. PERFECT as alway, if I could i would buy you a beer.

**Comment by nicm** [comment]
No problem.

**Comment by lanox** [comment]
HI @nicm 

Sorry to ask the question in here but since it's kind of in the same topic to what I was asking here before, and to be honest didn't want to open another issue as this is silly, but for some reason, I can't seem to wrap my head around it.

I have ```#{b:pane_current_path}:#{s/zsh//:pane_current_command}``` 

which displays `CWD:current_command` if there is no current commend it shows `CWD:` how can I move `:` to be part of  `#{s/zsh//:pane_current_command}`.

Ideally what I am trying to achieve is`CWD:current_commend` and `CWD` if there is no current_command

**Comment by nicm** [comment]
#{?#{s/zsh//:pane_current_command},:,}

**Comment by lanox** [comment]
Okay I am kind of glad, that this is not working as it makes me look less stupider, that is what I had as well and it did not work.

below is my complete status config
```
set -g automatic-rename-format "#{}"
H="/Users/xxx" 
set-option -g status-justify left
set-window-option -g window-status-format "#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H},●, #{b:pane_current_path}}} "

set-window-option -g window-status-current-format "#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H},●,#{?#{m:$H/*,#{pane_current_path}},,} #{b:pane_current_path}#{?#{s/zsh//:pane_current_command},:,}}}"
```

result was CWD:<did not display pane_ current_command]>

**Comment by nicm** [comment]
The bit I gave works for me. Try it with display -p and display -pv to debug it.

**Comment by lanox** [comment]
sorry @ncim I am not really sure what do to with display -p, but will do some googleing.

**Comment by lanox** [comment]
more output from display -pv 
```
(tic-tac-toe) tic-tac-toe λ tmux display -pv '#{?#{s/zsh//:pane_current_command},:,}'
# expanding format: #{?#{s/zsh//:pane_current_command},:,}
# found #{}: ?#{s/zsh//:pane_current_command},:,
# condition is: #{s/zsh//:pane_current_command}
#  expanding format: #{s/zsh//:pane_current_command}
#  found #{}: s/zsh//:pane_current_command
#   expanding format: zsh
#   result is: zsh
#  modifier 0 is s
#  modifier 0 argument 0: zsh
#  modifier 0 argument 1:
#  format 'pane_current_command' found: python3.7
#   expanding format: zsh
#   result is: zsh
#  substitute 'zsh' to '': python3.7
#  replaced 's/zsh//:pane_current_command' with 'python3.7'
#  result is: python3.7
# condition '#{s/zsh//:pane_current_command}' not found; assuming false
# condition '#{s/zsh//:pane_current_command}' is true
#  expanding format: :
#  result is: :
# replaced '?#{s/zsh//:pane_current_command},:,' with ':'
# result is: :
:
```

**Comment by nicm** [comment]
So what is the problem, this is replacing it with : when it is not empty, isn't that what you want?

**Comment by lanox** [comment]
Sorry @ncim if I am not explaining it properly, I do not want to replace pane_current_command with : what I want is to append : to pane_current_command. so it shows like this

 :python <- when there is commend
CWD <- if there is no current_commend

**Comment by nicm** [comment]
Right so do CWD#{?pane_current_command,:,}#{pane_current_command}

**Comment by lanox** [comment]
Yep that is fine but I am struggling to incorporate s/zsh//: as I do no want to show zsh if there is no other commends running,

**Comment by nicm** [comment]
CWD#{?#{s/zsh//:pane_current_command},:,}#{s/zsh//:pane_current_command}

**Comment by lanox** [comment]
You are a machine, how do you know all this.... where do I start, believe it or not I have been reading man page for tmux and documentation for last 4 hours and couldn't work it out.
