### ISSUE TITLE
window-status-current-style don't respect no[attr] when window-style-style [attr] is set

### ISSUE THREAD

**Issue by MindTooth** [tmux/tmux#1346]
Hi,

Been trying to create a color scheme, but I've come across an issue I'm not quite sure to make of.

## Issue
```tmux
set -g window-status-current-format " #I: #W (#F) "
set -g window-status-current-style fg=brightwhite,bg=colour237,bold,noitalics
set -g window-status-format " #I: #W (#F) "
set -g window-status-style fg=white,bg=default,italics
set -g window-status-separator ""
```
I expected that the `italics` attribute would be removed when I put `noitalics`.  But as you can see on the image, the text is still italic for the `window-current-state`.  With my config, I only want inactive windows to be italic.   Tried with both 2.7 & master.

So my question is; is this by design, is it a bug, or a natural consequence and I expect to much? 

_Not sure how I can disable config and create a log, when the issue is with the config._

## Screenshot
<img width="1483" alt="screen shot 2018-05-16 at 18 27 55" src="https://user-images.githubusercontent.com/33870508/40130530-99abc4c6-5937-11e8-8266-fa35d272f9a5.png">
<img width="1483" alt="screen shot 2018-05-16 at 18 30 05" src="https://user-images.githubusercontent.com/33870508/40130531-99d62bb2-5937-11e8-919d-7f905109d2f3.png">
_(neofetch behave strange under tmux, launchd is not my terminal.)_
### screen-256color
<img width="1483" alt="screen shot 2018-05-16 at 18 41 49" src="https://user-images.githubusercontent.com/33870508/40130967-d37a14c2-5938-11e8-9ed4-18ac0e16c71d.png">

## tmux master
<img width="1483" alt="screen shot 2018-05-16 at 18 45 32" src="https://user-images.githubusercontent.com/33870508/40131124-59cd909e-5939-11e8-8238-a13a0ee11f48.png">

## System
```sh
$ uname -sp; and tmux -V; and echo $TERM
Darwin i386
tmux 2.7
xterm-kitty
```

**Comment by nicm** [comment]
This is how it works, and it is sort of intended.

Styles are not parsed when they are used but when the option is set and as
you might imagine, there is no such attribute as "noitalics" - it just
means the italics bit is not set when the option is parsed. So when
window-status-current-style is combined with window-status-style it will
still get the italics bit just as if you hadn't specified noitalics.

It would be better if it worked how you want but then each bit would need
to have three states: set, inherit, and not set.

**Comment by MindTooth** [comment]
OK.  Then I guess I'm a bit off by the multiple ways of setting styles.  With the various ways of `-style` prefix, or `-fg/-bg`.

To conclude, which do you recommend?  I had hoped that I could use the `-style` variant, but I'm a sucker for constancy — though I failed that regarding the `-status-left/-status-right` option.

**Comment by nicm** [comment]
Style and fg/by/attr are the same.

**Comment by MindTooth** [comment]
Well, I kinda knew that.  I asked you :/  But, oh well, guess I'm going down the explicit way.

Thanks anyhow 👍

**Comment by nicm** [comment]
It doesn't matter which you use, although the style options are more future
proof probably.

**Comment by MindTooth** [comment]
Good to hear.  A combination for now will do the job nicely.  I'll be sure to follow the changes of future releases.

Thank for you the replies, much appreciated :)
