### ISSUE TITLE
tmux nested

### ISSUE THREAD

**Issue by wangw11** [tmux/tmux#1347]
hi:
     I am trying to use tmux nested. I use tmux background to open a docker, then in this docker, I use tmux again, the following is my problems:
If I use docker run -it *, tmux can work well. But when I use docker exec -it *, tmux is no respoding:
<img width="352" alt="2018-05-18 15 40 04" src="https://user-images.githubusercontent.com/35212977/40222347-c382d00c-5ab1-11e8-80ee-e0a55b245b54.png">

Is there any idea?
Thanks a lot!

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by wangw11** [comment]
hi:
    I use tmux 1.8 in ubuntu14.04 as the server, which run many dockers on it. The following is the info of server:
<img width="121" alt="2018-05-18 16 16 30" src="https://user-images.githubusercontent.com/35212977/40223816-de1f7c4e-5ab6-11e8-80d0-939debf81307.png">
and I start a docker with ubuntu16.04, tmux 2.1, the following is the info:
<img width="471" alt="2018-05-18 16 17 16" src="https://user-images.githubusercontent.com/35212977/40223854-f63385be-5ab6-11e8-8395-9cdd8b2d8583.png">
The problom is when I use docker exec -it * /bin/bash, in the terminal, the command tmux has no response:
<img width="558" alt="2018-05-18 16 18 47" src="https://user-images.githubusercontent.com/35212977/40223923-3085d69a-5ab7-11e8-9f61-4f0d0126ad51.png">
Is there any idea?
Thanks~

**Comment by wangw11** [comment]
Thanks for your reply.
Yes, the tmux in docker dose not work.
BTY, the following shows the tmux-server-128.log after run  $tmux -vv -Ltest -f/dev/null new
<img width="822" alt="2018-05-18 16 26 23" src="https://user-images.githubusercontent.com/35212977/40224302-53f1a194-5ab8-11e8-9304-b5e67648c108.png">
and the tmux-clinet-126.log is empty.

**Comment by nicm** [comment]
Does this still happen with tmux 2.7?

**Comment by wangw11** [comment]
Thanks a lot. It works well when I change tmux in server from v1.8 to v2.1.
BYW, I wonder is there any idea to get an new panel in docker.
Currently, when I use control-b + c with tmux in docker:
 
<img width="283" alt="2018-05-18 16 44 21" src="https://user-images.githubusercontent.com/35212977/40225109-bfbc514c-5aba-11e8-9033-7408a49d4c35.png">

It will create a new session parallel with the docker session:
 
<img width="316" alt="2018-05-18 16 45 46" src="https://user-images.githubusercontent.com/35212977/40225182-f0609fce-5aba-11e8-811a-c73d06cd114a.png">
