### ISSUE TITLE
Emoji (UTF-8) full support

### ISSUE THREAD

**Issue by robmuh** [tmux/tmux#1350]
I have noticed that when composing HTML from vim on a mac terminal the inserting emojis directly works. However, when using tmux it appears to not account for the correct size (probably using simple chars instead of unicode points (runes)). I've gone back to using HTML entities with the UNICODE number instead, but would be nice to eventually fix this.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by robmuh** [comment]
It has plenty of information to recreate the issue, for those who care. tmux breaks emojis, boom. That is all. Anyone can try again using exactly what I described. (Sorry but already wasted enough of my time reporting this and responding to this comment.)

**Comment by krader1961** [comment]
@robmuh You need to take a deep breath and calm down. I appreciate how frustrating an issue like this can be. But your problem report does not contain enough information. At a minimum you need to tell us which unicode code point(s) you're having problems with. You also need to tell us the OS and terminal you are using. The version of Vim might also be relevant. A screenshot or ascinema recording would also be helpful. Not only did you not provide enough information you provided essentially no information.

P.S., I do almost everything within tmux sessions and have no difficulty using  most non-ASCII code points. As do most people. So your blanket assertion that this is broken is self-evidently not true.

**Comment by robmuh** [comment]
And you need to freaking read the post including the part that says "mac terminal" and any emoji has the problem. I provided all the information for any sincerely interested in looking into the problem. Which you clearly are not. You simply need to attempt with the information I gave, and you didn't. End of thread. You can continue to live in your denial. You can't even make an assertion about "everyone" because you didn't even read my freaking issue. Bubye.

**Comment by sansna** [comment]
@krader1961 @nicm 
https://emojipedia.org/keycap-digit-one/
This emoji breaks.
MacOS Mojave, iterm2 version 3.2.0, bash version 5.0.7(1)-release, tmux version 2.8.
vim: macvim/8.1-151
The image you requested:
![image](https://user-images.githubusercontent.com/17974680/61724382-70c76880-ada0-11e9-941e-227ab3ef8386.png)
