### ISSUE TITLE
[2.7] [ubuntu 16.04] pressing the 'n' key results in golbdygook like ' n20j20k141l'; have to kill tmux-server to get it to stop

### ISSUE THREAD

**Issue by arooni** [tmux/tmux#1351]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

LilArooni ~: uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.7-rc
screen-256color

will work fine for awhile after killing the server and then start right back up again.

**Comment by ThomasAdam** [comment]
Turn off set-clipboard

**Comment by nicm** [comment]
Your terminal probably just doesn't support set-clipboard.

**Comment by arooni** [comment]
Apparently you're right; I set set-clipboard to off and I don't see this
happening anymore so you can close it out.  Not sure how the average user
(like me) would figure out that this error would be from that but hopefully
they'll find this bug mentioned in a google search result and it'll help em
out


may today be the best day of your life,
-------
david parkinson
founder - aroonilabs.com
blog - brofist.com
twitter - @brofist <https://twitter.com/brofist>

**Comment by nicm** [comment]
If you are using the correct TERM outside tmux you should not have this problem.
