### ISSUE TITLE
error in FAQ

### ISSUE THREAD

**Issue by simsong** [tmux/tmux#1353]
In this paragraph:

> tmux and GNU screen have many similarities and similar goals but now many differences. Most things that can be achieved in one can be achieved in the other, however.

Change "now many differences" to "not many differences" or "many differences," depending on what you intend.

**Comment by nicm** [comment]
Why?

**Comment by simsong** [comment]
Because it the usage is confusing. I don't understand what "now many differences" means.  Do you mean to say:

> tmux started out  as a re-implementation of GNU screen. It started with a similar set of design goals but has evolved into a different program.

Or do you mean to say:

> tmux and GNU screen started out at the same time, with different teams who didn't know what the other was doing. The two programs have converged on their feature set as the teams have shared ideas.

Or do you mean:

> tmux and GNU screen basically accomplish the same things, but have different ways of doing the same thing.

**Comment by nicm** [comment]
tmux and GNU screen have many similarities and similar goals but [there
are] now many differences.

**Comment by simsong** [comment]
Sounds great. Can you update the FAQ?

**Comment by nicm** [comment]
I was just showing you what the sentence means, but I suppose it would do
no harm to change it.

**Comment by nicm** [comment]
On second thoughts I just removed that question altogether since it is not particularly helpful. Thanks

**Comment by simsong** [comment]
Thanks to you!
