### ISSUE TITLE
tmux new-session -P -d 'tmux setw remain-on-exit on' only works once

### ISSUE THREAD

**Issue by leezu** [tmux/tmux#1354]
With both tmux 2.1 on Ubuntu and tmux 2.7 on OS X, running `tmux new-session -P -d 'tmux setw remain-on-exit on; echo hello'` multiple times (possibly with attaching to the session in the meantime) will loose all sessions but the first one.
Only once the first session is killed (`kill-session`) will `tmux new-session -P -d 'tmux setw remain-on-exit on; echo hello'` again create a new session (and will loose all sessions but the first one).

**Comment by leezu** [comment]
Thanks @nicm . Indeed this still happens with master and the `x.diff.txt`path from #1328

**Comment by nicm** [comment]
Found the problem. The dead pane's pty has been closed, so the kernel is reusing it for the next new pane. But when tmux looks for it it finds the original pane.

We should skip dead panes when we are searching, please try this change:

~~~~
--- cmd-find.c  9 May 2018 07:50:03 -0000       1.64
+++ cmd-find.c  24 May 2018 09:34:10 -0000
@@ -112,7 +112,7 @@ cmd_find_inside_pane(struct client *c)
                return (NULL);

        RB_FOREACH(wp, window_pane_tree, &all_window_panes) {
-               if (strcmp(wp->tty, c->ttyname) == 0)
+               if (wp->fd != -1 && strcmp(wp->tty, c->ttyname) == 0)
                        break;
        }
        if (wp != NULL)

**Comment by leezu** [comment]
Works fine, thanks!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
