### ISSUE TITLE
tmux new pane is empty

### ISSUE THREAD

**Issue by hiraksarkar** [tmux/tmux#1355]
While spawning a new pane `Ctrl+b c` the new pane is empty. Absolutely empty, no shell prompt, nothing. I tried `respawn-pane -k`, did not work. 
Note: I am using `oh-my-zsh` shell. 

The specifics of the problem are exactly same as one posed here
[https://github.com/tmux/tmux/issues/298](https://github.com/tmux/tmux/issues/298)

My problem is not due to aliases though. Running `tmux` by usual `tmux` command, the zombie state happens randomly while starting new pane by split or by creating new tab. 

My configuration
1. `Ubuntu 16.10 (GNU/Linux 4.8.0-59-generic x86_64)`
2. `tmux 2.7`
3. Custom `.tmux.conf`

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by hiraksarkar** [comment]
@nicm apologies for the short post, I just added some details related to configuration. I have no idea how to reproduce the problem though.

**Comment by hiraksarkar** [comment]
@nicm  I indeed tried `respawn-pane -k` but without those options. It did not work, trying with the options now.

**Comment by nicm** [comment]
Well, I didn't ask if they fixed it, I asked if you see anything when you do it.

Can you show me tmux logs from reproducing please?
