### ISSUE TITLE
File limit bug

### ISSUE THREAD

**Issue by George3d6** [tmux/tmux#1356]
On my user the following commands yield these results:

```
ulimit -Sn 
65535
ulimit -Hn
 65535
```

However, upon attaching to a tmux sessions created by the same user that ran those command before, I get:

```
ulimit -Hn
1024
ulimit -Sn
1024
```

Screen seems to be able to source those limits properly, and, just to make sure, I restarted the machine before setting those limits.

Why is the tmux not sourcing those limits ? It seems a very unintuitive and potentially dangerous behavior ? I was lucky to spot this during load testing, but I feel like this could cause a lot of harm to any serious server running in a tmux sessions.

**Comment by nicm** [comment]
Where did you set the limits?

**Comment by George3d6** [comment]
The limits were set via: /etc/security/limits.conf

I had both screen and tmux sessions running beforehand, so It's not like the screen server was restarted after the limits were.

The sessions were created after the limits were set, but the original tmux/screen processes were started with the wrong limits.

**Comment by krader1961** [comment]
Note there is nothing magical about */etc/security/limits.conf* and `screen` doesn't read its contents. That file is read by by the PAM subsystem to initialize the environment that login shells inherit. Changing that file will not affect any existing processes; including any running tmux or screen server and the terminal sessions they manage.

You say "the original tmux/screen processes were started with the wrong limits." If the tmux server was still running after you edited that file then the new settings will have no effect on the sessions, existing or new, managed by that tmux server. Same for the screen server. What you've said so far strongly suggests a new screen server was started after you edited that file while the tmux server that was running before the edit was still running after the edit.
