### ISSUE TITLE
Using #{session_group} in commands

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#1357]
I've started using the session-group feature, ensuring that each new session is started with

```new-session -t default```

I also have a key binding for 'new-session' which I updated to
```bind-key -T prefix C  if-shell -F "#{session_grouped}" "new-session -c #{pane_current_path} -t #{session_group}" "new-session -c #{pane_current_path}"```

Without session groups, this works fine, but with session group, I get a new session called `#{session_group}` with an initial window `#{session_group}-0`

Simply typing `tmux display-message #{session_group}` displays the word 'default' in the status bar, so I know the format works, but it appears session group formats are skipped when expanding formats in commands.

Can session group variables be added to the list that are expanded in bindings?

Thanks

**Comment by nicm** [comment]
session_group is expanded exactly the same as all over formats. You need to
be more specific about where it is not working.

**Comment by systemmonkey42** [comment]
I think the problem isn't with `#{session_group}` but with the `-t` option to new session.

Anything I pass to `new-session -t ` is used as the session group name.  Format specifications are not expanded.

Try for yourself - 
``` <prefix>: new-session -t #{session_group}```

creates a session called '#{session_group}'

Or am I doing it wrong?

BTW, version is 2.5.

Checking the source shows that args 'c' 's' 'F' et al, explicitly call 'format_single' while the '-t' arg does not.   As a side effect of checking the source, I find specifying `-t ""` uses the group name of the current window, which works just as well as what I was trying to achieve.

**Comment by nicm** [comment]
Formats are not expanded in -t.

**Comment by systemmonkey42** [comment]
Is this a problem? I certainly noticed it when I want to create a new session using the session group of the current window/session.
