### ISSUE TITLE
Should be able to add a new window at 0

### ISSUE THREAD

**Issue by wwalker** [tmux/tmux#136]
"With -a, the new window is inserted at the next index up from the specified target-window, moving windows up if necessary, otherwise target-window is the new window location."

This means that one cannot insert a new window at 0?  I tried -1 and it was treated as if I had done 0.

new-window -t 0
swap-window -s 0 -t 1

Seems to do it, and fairly reasonably.  If there is no simpler way to do it, then a note in the man page would save quite a few of us a long goose chase.

**Comment by nicm** [comment]
Melodrama aside, no, you can't insert at 0 with one command. You could do something like:

tmux set base-index 1\; movew -r\; set -u base-index\; neww

But it would of course renumber all your windows...

**Comment by nicm** [comment]
Or, much better perhaps:

tmux selectw -t:0\; neww -a\; swapw -s:1 -t:0

**Comment by nicm** [comment]
Er doh you said that already :-).
