### ISSUE TITLE
tmux alignment in iTerm2

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#1361]
Hi, 

I am not sure if this is issue with iTerm2 or tmux, I have created issue with iTerm2 but I might as well ask if this could be a tmux issue.

If i am in full screen as in the image below 
![screen shot 2018-05-29 at 1 09 37 pm](https://user-images.githubusercontent.com/7599183/40637771-81873d90-634a-11e8-85da-033cedd655a6.png)

you can see that tmux is not been centered properly, to reproduce this, all you need to do is set the active pane background and set the background of iTerm2 to white.

however if I am not in the full screen it sort of looks centered.

![screen shot 2018-05-29 at 1 11 39 pm](https://user-images.githubusercontent.com/7599183/40637806-b85a9c7c-634a-11e8-98be-38896962e658.png)

**Comment by nicm** [comment]
This is not something tmux has any control over.
