### ISSUE TITLE
Question: Tmux RPC api

### ISSUE THREAD

**Issue by imomaliev** [tmux/tmux#1362]
Is there RPC api for tmux like in neovim https://neovim.io/doc/user/msgpack_rpc.html or are there any plans on implementing something like this?

**Comment by nicm** [comment]
No and no plans.

**Comment by imomaliev** [comment]
@nicm Oh, ok. I wanted to know if there are any custom UIs for tmux and/or some sort of remote connection solutions, when you could use your local config's for remote tmux server, without explicitly uploading them.

**Comment by nicm** [comment]
You can use control mode to connect remotely but AFAIK nobody has written a UI using it apart from iTerm2.
