### ISSUE TITLE
tmux prompts for password when logging in?

### ISSUE THREAD

**Issue by tellmejeff** [tmux/tmux#1364]
When I use tmux, it always prompts me for a password when I first log in:

```
sudo] password for linuxuser: 
reboot to start in GNOME Desktop

linuxuser@ld7-nbkdcwl-ws  ~
$ 
```

I've tried rebooting but it still does it. I couldn't find what the message about GNOME Desktop was about. I'm sure I'm missing something pretty simple, but I'd love to know what. Granted, I just built it from the source (2.7), so I could probably figure it out if I had time.

Any ideas?

**Comment by krader1961** [comment]
Tmux is not prompting you for your password. You probably have a `sudo` command or something similar in one of your shell config files (e.g., *~/.profile* or *~/.bashrc*). And, it may not be obvious because the `sudo` may be embedded in a script/command you're running from your shell config.

**Comment by tellmejeff** [comment]
Thanks. I found it. I should have thought of that!
