### ISSUE TITLE
Redrawing issue with choose-tree's zoom flag

### ISSUE THREAD

**Issue by alesandar** [tmux/tmux#1365]
`choose-tree -Z`, introduced in version 2.7, does not always redraw curses applications upon its initial spawn. Switching back and forth in the client list sometimes redraws the zoomed pane. Example applications: `nvim`, `htop` and `ranger`.

Steps to reproduce (better execute them one by one, not as a one-liner):
- `tmux new`
- `tmux split -h` (next commands must be executed within the newly created split here)
- `tmux send-keys -t -1 'htop' Enter`
- `tmux choose-tree -t -1 -Z` || `tmux choose-tree -Z`

Depending on which pane has been used for the `choose-tree` command, the redrawing signal may have been invoked or not.

Case 1:
If you've used the first command - `choose-tree -t 1 -Z` - you've probably started the tree mode inside the `htop` pane. By now `htop` must be in half width, inside a full width preview window. Switch back and forth using `Up`/`Down` or `k`/`j`. By focusing back to the `htop` pane, the application must have been redrawn.

Case 2:
If you've used the second command - `choose-tree -Z` (without targeting a specific pane) - you've probably started the tree mode inside the empty pane, placed on the right of the `htop` pane. `htop` must be in half width again, as it has been described in the first case. Switch back and forth using `Up`/`Down` or `k`/`j`. **This time `htop` is not being redrawn at all.**

I used to believe that it's a problem related to the curses libraries that has been used by this applications, but because of the variety of the aforestated cases, now I think that it's not related to them.

**Comment by nicm** [comment]
Show some logs please.

**Comment by nicm** [comment]
Are you talking about the preview pane?

**Comment by nicm** [comment]
When you enter choose mode, the application in the pane may not have been resized yet, so the preview may show it as before or after resize. This is expected and is not a problem.

When you force it to refresh the preview to the current state by pressing Up and Down, it will probably have had time to redraw. It works OK for me with all the applications I have available here.

**Comment by alesandar** [comment]
That's right, I am talking about the preview pane. My first case explains exactly what you said, but the other one shows that the application inside the preview pane is not being forced to refresh. I'll provide logs (and possibly screenshots) a little bit later, if it's still necessary.

Simple steps to reproduce the second case:
- create new session or a window inside an existing one
- create a new horizontal split (split-window -h)
- start htop or any other curses interface inside one of the splits
- focus the other (empty) one
- call `choose-tree -Z`
- try to refresh the the preview pane of the application split by moving Up and Down

**Comment by nicm** [comment]
This works fine for me.

**Comment by nicm** [comment]
If you are zooming the other pane (that is, that doesn't contain the ncurses program), it will not be resized or redrawn because its size hasn't changed. Only the zoomed pane has changed size.
