### ISSUE TITLE
Headlessly resizing tmux window/session

### ISSUE THREAD

**Issue by i336** [tmux/tmux#1367]
[Edit: Forgot (!): tmux master (7de25d8), Arch Linux]

Hi.

I'd like to run a program headlessly within tmux, and periodically capture output for display in a webpage via `capture-pane` and `save-buffer -`.

While I don't need full interactivity (indeed, I only want read-only access, so a full JS-side VT102 is absolute overkill), I *do* want it to be possible to resize the terminal view on occasion.

I don't seem to be able to resize programmatically, in a way that suggests there's a bit of a bug floating around somewhere.

Specifically, if I go ahead and create a new session, detach from it, try and resize it, then dump the buffer, the session will still have the size of the terminal that created it.

In mostly copy-paste-able form, for an example of 80x50:

```
tmux -S tmux-socket

# (Manually detach)

tmux -S tmux-socket resize-pane -t 0 -Z -x 80 -y 50

tmux -S tmux-socket set -t 0 -g aggressive-resize on

tmux -S tmux-socket set -t 0 force-height 50
tmux -S tmux-socket set -t 0 force-width 80

tmux -S tmux-socket set -t 0 main-pane-height 50
tmux -S tmux-socket set -t 0 main-pane-width 80

tmux -S tmux-socket capture-pane -b X -t 0

tmux -S tmux-socket save-buffer -b X -

```

*However*, the moment I `tmux -S tmux-socket a` to reattach to the fully-detached session, it will immediately resize!

I don't mind what the solution looks like, as long as I can resize the entire window/session (not pane) programmatically.

(On that note, the reason I didn't headlessly create the session in the demo example is to illustrate/point out that I *don't* want to create the session with the restriction of never ever being able to attach to it.)

I don't _really_ want to have to, eg, use `socat` to create a fake PTY <sup>\**shudder*\*</sup> with the height/width I want <sup>\**cough*\*</sup>, then run and kill `tmux` after half a second or so <sup>\**twitch*\*</sup>...

**Comment by i336** [comment]
Considering the twitch-inspiring hacky workarounds, how about: setting force-resize from the commandline quietly sends an attach immediately followed by a detach, with any received TTY data being silently discarded.

Yep; I'll be the first to say it's *very* hacky, but I don't see it stomping on any security sensibilities. Something to loudly document internally, maybe, and maybe shove an obscure "if you set this parameter from the commandline it gets specially handled" in the manual just in case.

**Comment by nicm** [comment]
You could just make force-width/force-height set the size of any unattached sessions immediately you don't need to pretend to attach.
