### ISSUE TITLE
redraw issues in split-window -h

### ISSUE THREAD

**Issue by sassmann** [tmux/tmux#1368]
When doing a simple split-window -h I see flickering on the currently unused pane when the screen gets redrawn. Easiest way to reproduce this:
- do a split-window -h
- fill both panes with text
- cat a large file on the left pane
- observe occasional brief text flickering on right pane (might have to re-run a few times)

It's a really short flickering, but after you become aware of it it's annoying.
Doing a similar setup in screen doesn't show any flickering. Using xterm in both cases.
If you want any kind of debug output let me know. Also tested this with an empty .tmux.conf.

uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.7
screen

**Comment by sassmann** [comment]
You're right, rxvt-unicode doesn't show this behaviour. Still I'm wondering why this doesn't happen with screen in xterm. I'd rather stay with xterm. Any suggestions or is this something you think I'll have to cope with.

**Comment by nicm** [comment]
You are probably generating enough output on a slow enough terminal that
tmux is switching to redrawing the whole terminal to stop the terminal
being overwhelmed and to stay responsive, although I guess you are just on
the border. Or it is a side effect of using margins which only xterm
supports (but few programs other than tmux use them).

Try printing the client_discarded format with display -p. If it is not
zero, you could try fiddling with the TTY_BLOCK_* defines in tty.c but we
are unlikely to make any permanent changes to them.

**Comment by sassmann** [comment]
Thing is, I'm also occasionally seeing this when only a single line changes, i.e. just hitting enter in bash.
I've tried several combinations of xterm and tmux versions now, didn't make a difference.
gnome-terminal also showed the issue although a lot less often.

Not sure what you meant by "printing the client_discarded format".
I've tried "tmux display -p client_discarded" but that's probably not what you meant, right?

**Comment by sassmann** [comment]
tmux display -p '#{client_discarded}'
0

**Comment by nicm** [comment]
What exactly is flickering? All the text in the pane?

**Comment by sassmann** [comment]
It's single lines that seem to disappear (once) for about 200ms before reappearing. Line is completely blank during that period. Not sure how to describe this any better.

**Comment by nicm** [comment]
200 ms is a lot, can you show me some logs please of this happening

**Comment by sassmann** [comment]
I made a video of the problem and took 2 screenshots.
https://imgur.com/a/4SeFQJb
https://imgur.com/a/bKySz9s
In the first URL everything is still fine, the second URL shows a disappearing line in the bottom right.

**Comment by sassmann** [comment]
The 8th line from the bottom on right pane is gone. It should say "Yoyodine, Inc. ...."
I'll reproduce and provide logs, is tmux -v sufficient?

**Comment by nicm** [comment]
need vv

**Comment by sassmann** [comment]
Logs
https://paste.fedoraproject.org/paste/54nSt8doyTM~hSMcCLzokg/raw client
https://paste.fedoraproject.org/paste/uJLur~wLNz9~bTSqwkdQrQ/raw out
https://paste.fedoraproject.org/paste/LHBRlnUcbLfRwn-zoypWTw/raw server

**Comment by nicm** [comment]
Does it make any difference if you rebuild tmux with this change? If not please show me logs from that (with this change) instead.

~~~~
diff -u -p -r1.302 tty.c
--- tty.c       7 May 2018 13:39:09 -0000       1.302
+++ tty.c       5 Jun 2018 15:01:16 -0000
@@ -72,7 +72,7 @@ static void   tty_default_attributes(struc
                    u_int);

 #define tty_use_margin(tty) \
-       ((tty)->term_type == TTY_VT420)
+       (0)

 #define tty_pane_full_width(tty, ctx) \
        ((ctx)->xoff == 0 && screen_size_x((ctx)->wp->screen) >= (tty)->sx)

**Comment by sassmann** [comment]
Sorry for the confusing logs.
Here's a new set, still without the patch. I'll try that next.
https://paste.fedoraproject.org/paste/BIs75KdQ9QCnps~kJKpyIQ/raw
https://paste.fedoraproject.org/paste/mVc6h46NzGzS8z9jodZyDw/raw
https://paste.fedoraproject.org/paste/8W00mE5yiNPWSX4hm-ingg/raw

**Comment by sassmann** [comment]
Still reproducible with patch applied. Logs:
https://paste.fedoraproject.org/paste/k9b0o8c-OZvvd560rr67zw/raw
https://paste.fedoraproject.org/paste/VVNXHq-AgFQEQiNr1Y25og/raw
https://paste.fedoraproject.org/paste/KpjpABiVwVxL0vCoXe-NpA/raw

**Comment by nicm** [comment]
OK, when you have the problem on screen, instead of killing both shells which causes tmux to redraw the other pane and leaves a lot of noise in the logs, can you please just do "tmux kill-server" from an entirely different terminal window, so tmux does not redraw anything and just exits?

**Comment by nicm** [comment]
Also please reproduce on a smaller terminal, say 100x60 at most.

**Comment by nicm** [comment]
Actually 200x60 would be OK.

**Comment by sassmann** [comment]
Changed window to 200x60 and killed tmux server at the end. I had to increase the amount of text scrolling down to trigger the effect, probably due to smaller window size.
https://paste.fedoraproject.org/paste/DiyK6~HBA~3Od~vNdRBalg/raw
https://paste.fedoraproject.org/paste/EQaLIgDx7cUEO~voGlJZRw/raw
https://paste.fedoraproject.org/paste/HHeRQWyx6o~3uYvFmX8BFg/raw

**Comment by nicm** [comment]
What text did the line that went missing have on it in this time?

**Comment by sassmann** [comment]
Sorry, I don't remember. It's only a fraction of a second. I'd have to make a recording of the whole thing again to know.

**Comment by sassmann** [comment]
OK here we go.
https://paste.fedoraproject.org/paste/3rigBNlzrfz7uGhgWcAhaw/raw
https://paste.fedoraproject.org/paste/lOMOvRRJmYzFqW3gzTuCqA/raw
https://paste.fedoraproject.org/paste/cfx7NcbkH6hvwHkqbjtpzQ
Missing line:
related entities. Because LDAP is often not tightly integrated with

**Comment by nicm** [comment]
Hmm. That line is definitely being printed. Do you see it if you do this in a terminal of the same size:

clear;stty -onlcr;cat tmux.out;read

The left pane will be messed up but don't worry about that, do you see the text in the right pane?

(You'll need to run reset to get the terminal back to normal afterwards.)

**Comment by nicm** [comment]
There is hardly any output after that line that could be clearing it. I don't have time to look at it more closely until later though.

**Comment by sassmann** [comment]
OK, thanks Nicholas. I appreciate the time you spent on this.

**Comment by nicm** [comment]
OK well, I know what is happening anyway, I should have thought it through a bit more earlier. In a terminal without margins (or when you turned margins off using the diff I gave earlier), tmux has to redraw the entire window when one pane scrolls, because there is no other way to do it - it can only scroll full lines, so if the left pane scrolls the right pane would have to scroll too.

Obviously this is slower than being able to scroll normally, and it shows in the logs that your terminal is not able to redraw as fast as tmux actually wants to (because tmux notices this and redraws less often).

Also you have a very large terminal so this will make it slower again.

xterm does support margins so if you revert the diff I gave you earlier tmux should use them, which lets it scroll only part of the line. I'm surprised you still see the problem with margins in use. But margins in xterm are still slow, and not many applications use them so I wouldn't be surprised if they were a bit funny. If you give me similar logs without the diff I gave you I can take a look but I suspect they are just still slow.

If you want to get rid of this, I can only really suggest you use a faster terminal, or split fast-scrolling pane across top-bottom (which can use normal scroll regions) rather than left-right.

**Comment by sassmann** [comment]
Just to confirm, here's a short screencast so you can actually see what I'm describing.
https://www.dropbox.com/s/c0hed3rnvtckozk/Screencast%20from%2006-06-2018%2008%3A22%3A40%20PM.webm?dl=0
Just watch the right pane, in the lower part. A whole line is disappearing.
Doesn't take long to show up.

If that's what you're suspecting let's just close the issue.

**Comment by nicm** [comment]
Does it make any difference if you do this:

    tmux set -as terminal-overrides ',*:ech@'

**Comment by nicm** [comment]
Well, I think it is just an artefact of tmux having to redraw so much, I wondered if it was specifically with ech but I guess not. I don't see anything in the output that would cause this particularly.

**Comment by sassmann** [comment]
yeah, feel free to close this. It was worth a try! Thanks.

**Comment by nicm** [comment]
Unfortunately there isn't really an ideal way to deal with fast scrolling particularly in left-right split panes because it can generate such a huge volume of data. If tmux didn't try to avoid sending so much by redrawing instead, you would find that you would not be able to use tmux for long periods while the terminal finished processing all the output.
