### ISSUE TITLE
Support indicating tmux extra space with color instead of dots

### ISSUE THREAD

**Issue by tyll** [tmux/tmux#1369]
I am using tmux 2.7 and when I attach to a smaller screen, tmux indicates the unused space with dots. Therefore when trying to copy mulitple lines from this screen, I get a lot of dots in the copy buffer. It would be great if tmux could indicate the unused space with spaces in a different background color. Then it would still be visible but it would not disturb copying contents.

**Comment by nicm** [comment]
I don't think this would help you because there would still be the pane border and we aren't going to get rid of that.

**Comment by tyll** [comment]
Would it be possible to allow the same for the pane border, i.e. use colored space characters?

**Comment by nicm** [comment]
It would be possible to do it but I don't think we want to.

**Comment by tyll** [comment]
Please help me understand why you do not want to.

**Comment by nicm** [comment]
I like the way it looks now, it has been that way for years and years, the recommended way to copy from tmux is with copy mode which is aware of panes, I don't want to add any more options that hardly anyone will ever use.

**Comment by nicm** [comment]
You can change the characters by modifying CELL_BORDERS in screen-redraw.c, the defines just above list which characters are used for which part.

**Comment by nicm** [comment]
They are ACS characters so you need to do this to see which one corresponds to each symbol:
~~~~
tput enacs;tput acsc; echo; tput smacs; tput acsc; tput rmacs; echo

**Comment by nicm** [comment]
The real solution of course is to support panning and then the window would never need to be smaller than the terminal... but that is not easy to do.

**Comment by tyll** [comment]
Thank you for the explanation. The problem with the copy mode is that it does not work in SSH sessions, i.e. if I copy something this way in tmux it does not get to the clipboard on my machine. Also using the mouse is faster.

**Comment by nicm** [comment]
tmux supports the mouse. If you use a terminal that supports set-clipboard then it will work over ssh also.

**Comment by tyll** [comment]
did not know that. Can you recommend a terminal? I checked with gnome-terminal and urxvt and I do not see the text that I copied in copy mode in my clipboard.

**Comment by tyll** [comment]
`set mouse on`  is awesome :+1:

**Comment by nicm** [comment]
Yes it appears gnome-terminal does not support it. I think there is a script for rxvt-unicode to do it somewhere.

xterm supports it, and I think st does too (with a length limit though). I'm not sure of others.

**Comment by tyll** [comment]
Hm, it seems to work locally with st but not when tmux is running on the SSH server

**Comment by nicm** [comment]
What is TERM set to after you ssh?

**Comment by tyll** [comment]
st-256color when I use st

**Comment by nicm** [comment]
Run these inside tmux where it is not working:
~~~~
tmux info|grep Ms
tmux show -s set-clipboard
~~~
What do they both say?

**Comment by tyll** [comment]
```
$ tmux info|grep Ms
 180: Ms: [missing]
$ tmux show -s set-clipboard
set-clipboard on
```
When I start tmux on the SSH server locally, it is:

```
 180: Ms: (string) \033]52;%p1%s;%p2%s\007
```

**Comment by tyll** [comment]
I noticed that inside tmux TERM is set to screen (when started from an SSH session) or screen-256color (when started in X11)

**Comment by nicm** [comment]
Right so your remote host at entry in terminfo is probably too old.

You can do this in . tmux.conf:

set -as terminal-overrides ',st*:\033]52;%p1%s;%p2%s\007'

Then restart tmux entirely

**Comment by tyll** [comment]
Thank you so much, that did the trick! Just wondering, is there a way to do vertical copy in mouse mode?

**Comment by tyll** [comment]
Do you maybe have a pointer to a doc explaining what needs to be done in gnome-terminal to support setting the clipboard? Maybe I can open a feature request there

**Comment by tyll** [comment]
Never mind about gnome-terminal, it seems to be working there as well. I guess it was a missing set-clipboard when I tried there before.

**Comment by nicm** [comment]
OK great.
