### ISSUE TITLE
smooth scrolling when using PageUp/PageDown

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#137]
Currently, PageUp/PageDown will just change screen, but the better one is you can see the movement of the lines of the screen. 

Is there any configuration that I can use for smooth scrolling using PageUp/PageDown when 'm viewing a file in vim, less comand or the command history of the current terminal?

**Comment by ntnn** [comment]
The scrolling would be determined by the underlying program you use, not tmux. So you'd need to change less/vim/etc for that. The only time where tmux actually can control the 'type' of scrolling is when you are scrolling through its own history.

**Comment by c02y** [comment]
OK, thanks.
