### ISSUE TITLE
tmux doesn't always answer to C-b n or C-b p

### ISSUE THREAD

**Issue by vb0** [tmux/tmux#1370]
Sometimes when doing "next" or "previous" window the combination is ignored. Sometimes twice in a row. It works eventually if repeated. It is not something that takes time to develop after long uptime it can happen with fresh tmux from machine started earlier today.

Version: 2.1 (quite old from ubuntu), also tried master built from git today. The problem is still present

Environment: tested on multiple machines, ubuntu x64 LTS (now 16.04.04). Headless, coming from ssh. I don't have any nested (or even running) multiple/combination tmux/screen - just one.

It does it (also) over local network and the input (C-b n) isn't buffered and eventually all commands executed instead the commands are just ignored as they never happened. I do not have any tmux user configuration. I tried to change to C-a instead of C-b (screen works without this issue) and tmux still has the same problem. I have very good "muscle memory" and I type on terminals for too long to remember, even if a command isn't finished and I start typing or if there's some network latency and I keep writing the state of the terminal eventually sync perfectly with my brain - except for this tmux glitch. It is not the case that I don't release C-b before typing n or something similar.

$TERM=screen if it matters.

This is minor and most likely an issue on my side (or at least can be fixed by changing some configuration on my terminal/setup). I've been having this for years, each time I decide to try (and give up) tmux.

**Comment by nicm** [comment]
Are you sure you are pressing C-b n and not C-b C-n?

**Comment by vb0** [comment]
Positive. I've been doing this for more than 20 years (obviously not with tmux specifically). Screen never fails and I'm using it a lot. If need be I can probably get a terminal that logs everything but I'm sure this is not the issue.

**Comment by nicm** [comment]
screen binds C-n by default, so if you are pressing C-b C-n then screen will work and tmux won't.

Please show me tmux server log of you reproducing the problem, preferably with master rather than 2.1.

**Comment by vb0** [comment]
That is really brilliant, I guess I was doing C-b C-n sometimes and didn't know it!
bind C-n next-window
bind C-p previous-window
fixes it; well it was never broken - it allows for my mistakes!

Thank you so much.
