### ISSUE TITLE
fd leak

### ISSUE THREAD

**Issue by codingDuan** [tmux/tmux#1373]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING
I am using tmux 1.8，I found tmux1.8 a fd leak bug (reached 1024, i don't know whether It's related to my network environment) here is my strace log and lsof result

![wx20180608-120733](https://user-images.githubusercontent.com/4122782/41138544-97360bb8-6b14-11e8-85fc-e50d3f3b8e4b.png)

[tmuxStrace.log](https://github.com/tmux/tmux/files/2082897/tmuxStrace.log)

[lsof.log](https://github.com/tmux/tmux/files/2082896/lsof.log)

PS: /prox/pid/fd/inode  **socket missing**

**Comment by nicm** [comment]
Does this still happen with tmux 2.7?
