### ISSUE TITLE
Cannot get window title changes working

### ISSUE THREAD

**Issue by Ketrel** [tmux/tmux#1375]
Connection Method: SSH via Putty
Ubuntu 16.04.4 LTS
Linux x86_64
tmux 2.7
screen-256color

2.7 was a fresh compile as of today.

What I've tried
`set -g set-titles on`  
`set -g automatic-rename off`

Followed by
`printf '\033kTESTING\033\\'`  
`printf '\033]2;TESTING\007'`

Expected:  
  Putty window title would change to: "TESTING"  

Actual:  
  Putty window title stayed at the default format set in config: '#W  (#h)' 

Additional Info:    
  Running those same two printf commands OUTSIDE of tmux changes the putty window title as expected.

**Comment by Ketrel** [comment]
Also, here's my .tmux.conf file for reference

    # Setup Window Titles
    set -g set-titles on
    set -g set-titles-string '#W (#h)'

    # Setup Status
    set -g status-bg colour31
    set -g status-fg colour16
    set -g status-left-length 16

    # Change Window Split Keys
    bind-key | split-window -h
    bind-key - split-window -v
    unbind-key '"'
    unbind-key '%'

    # Other Bind Changes
    bind-key C-r source ~/.tmux.conf
    bind-key C-s choose-tree -swGN

    # Other settings
    set -g default-terminal screen-256color

**Comment by nicm** [comment]
You don't have #{pane_title} or #T in set-titles-string so the OSC 2 sequence won't do anything to the title. For the \\ek sequence you need allow-rename turned on.

**Comment by nicm** [comment]
Yes the default changed, it's in the changelog.
