### ISSUE TITLE
Focus hooks

### ISSUE THREAD

**Issue by nuao** [tmux/tmux#1378]
Hello
Is there a way to set a hook for the focus sequences affecting the client terminal? That is, these defined here:

https://github.com/tmux/tmux/blob/9da78d72de478c1ea2e8d0fc3a8efa06cfaaeaf7/tty-keys.c#L165-L167

I don't notice focus events in the hook documentation, but, essentially, I'd like to do something like this:

    tmux set-hook FocusIn 'run hello_world'
    tmux set-hook FocusOut 'run bye_world'

Or perhaps you could suggest another solution to run `hello_world` on FocusIn if the hook is not currently possible.

tmux 2.7, Linux, tmux-256color (with `set -g focus-events on`)

**Comment by nicm** [comment]
No there are no hooks for these at the moment but I think they would be relatively easy to add (put some notify_pane calls in the right place).

**Comment by nicm** [comment]
Please try this: [focus.diff.txt](https://github.com/tmux/tmux/files/2142335/focus.diff.txt)

**Comment by nicm** [comment]
With the diff, for example:
~~~~
set -g focus-events on
set-hook -g pane-focus-in "run 'echo I #{pane_id} $(date) >>/tmp/focus'"
set-hook -g pane-focus-out "run 'echo O #{pane_id} $(date) >>/tmp/focus'"

**Comment by nuao** [comment]
I appreciate your taking a look at this. Thank you.

Works well, though I've noticed there's one scenario where there can be a delay of several seconds before the `pane-focus-out` event is fired. This is when the focus is lost because the terminal itself is no longer in focus, and so all panes are therefore also not focused.

My guess is that in the case the focus out event is eventually fired because tmux is running some background check for focus every N seconds.

Would tmux also be able to monitor any focus out notifications from the terminal and thereby have `pane-focus-out` work immediately in all cases, not just switching panes?

**Comment by nicm** [comment]
\033[O is the usually start of several possible keys so tmux has to wait until escape-time expires before it processes it, you will need to reduce escape-time if you want it to fire it immediately.

**Comment by nuao** [comment]
I actually have already `set -sg escape-time 50`. Also, the delay is often up to ten seconds or so, much above the default 500ms escape time.

I tried a few terminals to see what happens when the terminal window loses focus. Alacritty and termite both have the same behaviour where the focus out event eventually fires after a random few seconds. I don't use urxvt, but in urxvt's case the focus out event does not appear to fire at all when uxrvt loses focus. In all cases, the hooks fire immediately when switching panes inside tmux and the terminal itself still retains focus.

**Comment by nicm** [comment]
Show logs please.

**Comment by nuao** [comment]
I won't waste your time with going through logs. I'll take your request as indicating suprise that I should experience that delay, so I'll assume it's something to do with my own setup. I'll look further into the matter myself when I have the time, and in the meantime close the issue here.
