### ISSUE TITLE
tmux override terminal profile

### ISSUE THREAD

**Issue by lazybensch** [tmux/tmux#1379]
Hi. Is it possible, with `terminal-override` or another feature to override the terminal profile colors used? so when displaying content in a tmux window to use a custom color for green, red, foreground, etc. (basically bypassing my iTerm2 (or any other terminal app) profile?

I have configured my tmux with true color support and would like to create a color scheme that is consistent no matter what terminal app i use. Couldn't find anything in the man pages though.

If anyone can point me into the right direction would be great. Thanks.

**Comment by nicm** [comment]
No but some terminals (IIRC gnome-terminal) do allow you to change the colours used for the ANSI colours.
