### ISSUE TITLE
scroll the other pane from the current pane

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#138]
When I open two panes side by side, I want to scroll the content of the other pane such as when viewing a file using vim or less or just the history of the command history of the terminal from the current pane using `PREFIX + Alt-PageUp/PageDown` specifically. I want this because I can make this happen in Emacs and I love it.

Is there configuration that I can do that?

**Comment by nicm** [comment]
You can probably write a script to do it using send-keys with a target.

**Comment by c02y** [comment]
Solution:

    bind -r M-PageDown last-pane \; send-keys "PageDown" \; last-pane
    bind -r M-PageUp last-pane \; send-keys "PageUp" \; last-pane
