### ISSUE TITLE
window active syle and non active

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#1383]
Hi, 

I am not sure if this is a issue or I am doing something wrong, I have attached the image showing non active border not covering entire area see the number 1 red arrows, is this how it's suppose to be ?.
<img width="1792" alt="screen shot 2018-06-25 at 8 27 45 pm" src="https://user-images.githubusercontent.com/7599183/41845758-eaf13402-78b7-11e8-87a6-ce07409e82d1.png">

Also the active panel is it normal that non active color is overlapping the lines of active pane see number 2 and 3.

here is my config.
```
set-option -g status-bg black
set -g window-style 'bg=colour236'
set -g window-active-style 'bg=black'
set -g pane-border-fg colour238 #non active line color
set -g pane-border-bg colour236 # non active border 
set -g pane-active-border-fg colour238 # active line color
set -g pane-active-border-bg colour236 # active border
```

**Comment by nicm** [comment]
The lines take up a whole character cell, you can only have one background colour for each cell.

**Comment by lanox** [comment]
Righ, but how come number 1 is not covering all the way to the end ?

**Comment by nicm** [comment]
Your font probably doesn't fit evenly into the size of the window so the terminal just draws the background colour.

**Comment by lanox** [comment]
Ugh, thanks everything takes in play, you are right by increasing the font size it adjusted that gap.

Number 2 seems like the gap is lot bigger almost as the character cell is doubled is that the case ?

Thanks for the amazing support and answering all the questions

**Comment by nicm** [comment]
Cells are normally about twice as tall as they are wide.
