### ISSUE TITLE
Activity/Bell/Silence action across sessions

### ISSUE THREAD

**Issue by tardypad** [tmux/tmux#1384]
Using tmux 2.7

I noticed that alert actions are not triggered across sessions
So for example, if I'm on session 1 and enable monitoring of activity, no message will be displayed if activity happens while I'm on session 2  I switched to afterwards.

I managed to simulate this with my config using the alert-* hooks
https://github.com/tardypad/dotfiles/commit/fe73810922f8f27fd4f70e0bb969e3a5cc83fe7b

I was wondering if such a behavior would be worth being implemented directly inside tmux itself

Another side issue with this:
it seems that when activity is triggered in another session than current one, the alert-activity hook gets triggered multiple times (usually between 3 and 5 times)

**Comment by nicm** [comment]
Yes... it doesn't work across sessions, but hardly anything does.

If you can do it with hooks I would leave it at that rather than trying to do it in code.

**Comment by tardypad** [comment]
Ok fair enough
For now, it seems to work good enough for me

Just for the record, what other stuff you have in mind that don't work across sessions?

**Comment by nicm** [comment]
Almost everything is per session or confined to a session. Options? select-window etc?
