### ISSUE TITLE
tmux not working when there is no ipv4

### ISSUE THREAD

**Issue by mat813** [tmux/tmux#139]
Some FreeBSD user was trying to run tmux in an ipv6 only jail:
http://docs.freebsd.org/cgi/getmsg.cgi?fetch=203867+0+archive/2015/freebsd-questions/20151011.freebsd-questions

and it fails because at one point, it's trying to do something with PF_INET:

```
poll({4/POLLIN 6/POLLIN},2,-1)			 = 1 (0x1)
socket(PF_INET,SOCK_DGRAM,0)			 ERR#43 'Protocol not supported'
poll({4/POLLIN},1,0)				 = 0 (0x0)
fcntl(0,F_GETFL,)				 = 6 (0x6)
fcntl(0,F_SETFL,0x2)				 = 0 (0x0)
process exit, rval = 1
```

**Comment by niklaas** [comment]
In case you need further information please let me know. I just subscribed to this issue.

**Comment by mat813** [comment]
I should point out that v6 being here or not doesn't really matter, what matters is that v4 is here or not, if it's not, tmux fails to start.

**Comment by nicm** [comment]
Try this please:
```
diff --git a/compat/imsg.c b/compat/imsg.c
index 982ee06..f4026b5 100644
--- a/compat/imsg.c
+++ b/compat/imsg.c
@@ -51,8 +51,12 @@ available_fds(unsigned int n)
 	for (i = 0; i < n; i++) {
 		fds[i] = -1;
 		if ((fds[i] = socket(AF_INET, SOCK_DGRAM, 0)) < 0) {
-			ret = 1;
-			break;
+			if ((errno == EAFNOSUPPORT ||
+			    errno == EPROTONOSUPPORT) &&
+			    (fds[i] = socket(AF_INET6, SOCK_DGRAM, 0)) < 0) {
+				ret = 1;
+				break;
+			}
 		}
 	}

**Comment by nicm** [comment]
Er wait that is wrong.

**Comment by nicm** [comment]
Try this one:
```
diff --git a/compat/imsg.c b/compat/imsg.c
index 982ee06..6c9bee6 100644
--- a/compat/imsg.c
+++ b/compat/imsg.c
@@ -51,8 +51,12 @@ available_fds(unsigned int n)
 	for (i = 0; i < n; i++) {
 		fds[i] = -1;
 		if ((fds[i] = socket(AF_INET, SOCK_DGRAM, 0)) < 0) {
-			ret = 1;
-			break;
+			if (errno == EAFNOSUPPORT || errno == EPROTONOSUPPORT)
+				fds[i] = socket(AF_INET6, SOCK_DGRAM, 0);
+			if (fds[i] < 0) {
+				ret = 1;
+				break;
+			}
 		}
 	}

**Comment by mat813** [comment]
I'll try that. What happens if there is no ip at all, shouldn't tmux work anyway ?

**Comment by nicm** [comment]
Maybe it should but unless you come up with a better way to get around the lack of getdtablecount() it won't.

**Comment by mat813** [comment]
This solves the "no v4 but v6" problem. :+1:
I'll let you decide wether you want to keep the issue open for the "no v4 nor v6" case 😄

**Comment by niklaas** [comment]
Thanks to both of you for providing such a quick fix.

**Comment by nicm** [comment]
Thanks
