### ISSUE TITLE
set-buffer in display-panes template not avaliable immediately

### ISSUE THREAD

**Issue by bootleq** [tmux/tmux#1390]
Linux x86_64
tmux master
xterm-256color

Hi, I expect the callback of `display-panes` take effect immediately after select target.
While below command:

```sh
tmux display-panes -d 0 "set-buffer -b foo %%" && tmux show-buffer -b foo
```

outputs `no buffer foo`, but if we issue next command `tmux list-buffers` the buffer is avaliable.
Is this expected behavior? Thanks.

**Comment by nicm** [comment]
This is expected, display-panes does not wait, so your command is a race.
