### ISSUE TITLE
Add a foreground option to `start-server`

### ISSUE THREAD

**Issue by ismell** [tmux/tmux#1392]
With the inclusion of #1262, it would be nice to add a `--foreground` option to start-server that would prevent the server from daemonizing. This would allow `tmux start-server -f` to be the root process of a chroot or docker container. The socket can be shared via a bind mount to the host.

**Comment by nicm** [comment]
I don't really see a compelling use for this and I don't want to support a
different mode of operation.

**Comment by untoreh** [comment]
I also would have liked to use tmux as init :(

**Comment by RuRo** [comment]
It's really annoying, that you are forced to keep a dummy session open, if you want to run tmux in docker as a service.

Although I don't know the particulars of how tmux is implemented, this feature should be as simple to implement, as not `fork`ing before starting the tmux server if the `-f` option is present.

The current setup forces the following ugly script:
``` sh
#!/bin/sh
tmux start-server\; set-option exit-empty off && tail --pid=$(pgrep tmux) -f /dev/null
```

**Comment by jorsn** [comment]
What about
```bash
#!/bin/sh
tmux start-server\; set-option exit-empty off\; wait-for kill-server\; kill-server
```
? The `kill-server` in the end is to ensure that the client does not exit as long as the server is running.

You then have two equivalent methods of killing the server:

* `tmux kill-server`
* `tmux wait-for -S kill-server`
