### ISSUE TITLE
Problem with my bind command disabling Tmux global key binding after choose-buffer is run

### ISSUE THREAD

**Issue by purplefishies** [tmux/tmux#1396]
Hi,

I have the following bind key for choose-buffer in my .tmux.conf

bind C-c choose-buffer "run \"tmux save-buffer -b %% - | xclip -i -sel clipboard\" "

The problem I have is that after I run the choose buffer, my tmux Prefix binding has been disabled (Control-B plus any key does nothing )  so that I can't work with tmux from my terminal. I have to typically close the terminal and reattach to tmux, even though Tmux is still active in original terminal window where I've selected to choose-buffer.  The choose-buffer part is working in that I can perform a Control-V to paste the selected buffer.

I've had this problem since tmux 2.4 and it still existed with tmux 2.7 so I assume that it was a problem with my .tmux.conf.  I'm using this in gnome-terminal .

Not sure how to reestablish C-b as the binding if it is removed.

Thanks for any suggestions.

**Comment by nicm** [comment]
xclip has a bug and does not close stdout when it has finished, so you
either need to use run -b so tmux doesn't wait for it to finish, or
use xsel instead, or redirect xclip's stdout to /dev/null yourself.

**Comment by purplefishies** [comment]
Thanks ! that was a perfect solution.
