### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by huyvohcmc** [tmux/tmux#1397]
How can I format the date in the status line to something like ` July 7 2018` instead of `2018-07-07`?

**Comment by krader1961** [comment]
What date are you referring to? Are you referring to the `status-right` default value? If so you can specify another value which is passed to the `strftime()` function (see `man strftime`). That allows you to specify the date/time in whatever format you want. So to get the date formatted the way you want you would do `set-option -g status-right "\"#W\" %B %e %Y"`.
