### ISSUE TITLE
$PWD becomes "." with "new-session" config on Mac

### ISSUE THREAD

**Issue by fishy** [tmux/tmux#1399]
```
$ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.7
screen-256color
```

I noticed this issue on Mac only (I have tmux 2.7 on 2 Mac machines that both have this issue and I also have tmux 2.7 on several Linux machines that don't have this issue)

I have `new-session` in my `~/.tmux.conf` so that when I do `tmux a` it will create a new session if none exists. I noticed that when I do `tmux a` to create a new session, `$PWD` will be `.`, and that will cause some weird issues. If I use `tmux new` to create a new session `$PWD` will be `/Users/fishy` which is expected and everything is fine. (On Linux both new sessions will have `$PWD` being `/home/fishy` and that's fine)

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by fishy** [comment]
Haven't tried with master yet. I could try it later.

**Comment by fishy** [comment]
I _think_ it might have the same issue the first time I do `tmux a` from the master version, but I can't reproduce it any more so it might be that I misread it and it's actually fixed in master.

**Comment by nicm** [comment]
Show logs from reproducing with master please.

**Comment by fishy** [comment]
I cannot reproduce it on master any more, feel free to close it :)

**Comment by nicm** [comment]
Good stuff.
