### ISSUE TITLE
Option to disable "release mouse click to copy selection & exit copy-mode" behavior.

### ISSUE THREAD

**Issue by NHDaly** [tmux/tmux#140]
I don't find this behavior desirable. Often, i am simply scrolling with my mouse and highlight something out of habit just to show someone, and I exit copy-mode. Also, I would like to use plugins like [tmux-yank](github.com/tmux-plugins/tmux-yank) to copy the highlighted text to my OS instead of just tmux's paste buffer. This is difficult with the current behavior:

https://github.com/tmux-plugins/tmux-yank/issues/24
https://github.com/tmux-plugins/tmux-yank/issues/28

It would be nice to have an option to disable this behavior. Ideally something like `set-option -g mouse-release-copies-selection off`, which could be set to `on` by default.

I'm not sure, but I *think* such an option would go here in the code?:
https://github.com/tmux/tmux/blob/4afe26fa82fd2701cbf686799668d685645b220e/window-copy.c#L2287

Thanks!

**Comment by NHDaly** [comment]
Oh, I see that after commit bf635e7 the mouse-support options have changed. Is this already addressed by those changes? Thanks.

**Comment by nicm** [comment]
No I like this behaviour.

**Comment by NHDaly** [comment]
I'm sorry, no, I wasn't asking the default to change, just that there be *an option to change the behavior*. We don't *all* like that behavior.

**Comment by NHDaly** [comment]
Will I be able to disable it by setting something like `bind -n   MouseUp1Pane copy-mode <space>` or something like that?

**Comment by freitass** [comment]
I would use that option myself! Often times I end up in the following scenario:

1. Scroll up to analyse a huge log
2. Switch to another window (i.e. the browser)
3. (Accidentally) click on the terminal window to set it focused, leaving copy-mode and losing the point of the log where I was

**Comment by twof** [comment]
+1 for this option.

**Comment by spazm** [comment]
+1 for an alternate behavior/option.

  I use mouse select for highlighting as well as copying.   As a workaround I'll be disabling mouse mode.

**Comment by sblask** [comment]
I have mouse mode disabled because of this behaviour and it would be great to have an option to disable it. I can see how it is useful if you want to copy something from the current screen, but if you have a huge log, try to find something and suddenly you click and lose the position, it's more of an annoyance. Also, not sure what I did, but for me dragging does not even copy, I just lose the position which totally looks like a bug...

**Comment by ramn** [comment]
+1

**Comment by maikelmeyers** [comment]
I also think it is inconsistent that it is not possible to override the default behavior using `bind -t vi-copy MouseUp1Pane "something else then copy-selection and leave copy-mode"`
You can do nearly anything in Tmux, but you can not disable or workaround the most annoying behavior. It's a pity.

**Comment by maikelmeyers** [comment]
+1

**Comment by coderstephen** [comment]
Hey everyone! I'm working to see if I can implement this feature, via #273. Please check out the latest commits in https://github.com/coderstephen/tmux and let me know what you think. Does it work as expected? Are there any side effects or other weird behavior?

**Comment by Koshmaar** [comment]
I'm also observing this behaviour and find it very irritating: when scrolling tmux buffer (using mouse wheel through tmux-scroll-copy-mode plugin), as soon as I select any piece of text, bam, the scrolling is reset, and view goes all the way down. This doesn't make sense :) So has anyone tried Coderstephen recent changes?

**Comment by phphong** [comment]
+1. I myself find this 'feature' very annoying.

**Comment by mtdeguzis** [comment]
I also consider disabling mode all the time because of this behaviour and it would be great to have an option to disable it.

**Comment by sagebind** [comment]
@mtdeguzis This went in to version 2.2 I believe. Current version is 2.4. To disable this behavior, just unbind the default behavior of `MouseDragEnd1Pane` in copy mode:

```
# 2.4+
unbind -T copy-mode MouseDragEnd1Pane
# 2.2 - 2.3
unbind -t vi-copy MouseDragEnd1Pane
```

**Comment by mtdeguzis** [comment]
@sagebind grrrr, I am stuck on 1.8 for RHEL 7.3 :(

**Comment by spazm** [comment]
[tmux-server-21885.log.txt](https://github.com/tmux/tmux/files/1201879/tmux-server-21885.log.txt)
@sagebind:  I just upgraded to 2.5 and am running with MouseDragEnd1Pane unbound, but copy mode is still exited when I mouse up.    Any suggestions?

tmux-copy-only.conf:
```
set-option -g mouse on
unbind -T copy-mode MouseDragEnd1Pane
```

```
% uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.5
screen
```

**Comment by sagebind** [comment]
@spazm If you have vi-mode enabled, you need to do this:

```
unbind -T copy-mode-vi MouseDragEnd1Pane
```

**Comment by mckellyln** [comment]
I am still on v2.1 so I cannot do this unbind.  I will try it when I upgrade soon.
For now I toggle mouse mode with a 'm' and if you hit <Tab> while highlighting it will 'keep' the highlighted section and then you can release the mouse left button and scroll etc. then copy etc.
I only wish I could automatically set the mouse off when leaving copy-mode.
Anyone know of an easy way to do that ?

**Comment by mckellyln** [comment]
I have upgrded to tmux master branch and the unbind MouseDragEnd1Pane works awesome, thx.

**Comment by Droj** [comment]
I'm using tmux v2.3 and needed to use a slightly different syntax:

    unbind-key -t vi-copy MouseDragEnd1Pane

**Comment by Immexxx** [comment]
@tbarbette tmux might still have some sessions running (this might be useful: https://stackoverflow.com/questions/38295615/complete-tmux-reset)

**Comment by mhourahine** [comment]
@tbarbette FYI - This worked for me:

```unbind-key -T copy-mode-vi MouseDragEnd1Pane```

**Comment by tbarbette** [comment]
> @tbarbette FYI - This worked for me on v2.8:
> 
> `unbind-key -T copy-mode-vi MouseDragEnd1Pane`

Thanks ! Some people do not like backward compatibility around here.

**Comment by phcerdan** [comment]
For users of the [tmux-yank](https://github.com/tmux-plugins/tmux-yank#controlling-yank-behavior) plugin:

```
set -g @yank_action 'copy-pipe' # or 'copy-pipe-and-cancel' for the default
```

**Comment by reorx** [comment]
Here's my solution for better experience in drag selection:

```
set -g mouse on

# disable "release mouse drag to copy and exit copy-mode", ref: https://github.com/tmux/tmux/issues/140
unbind-key -T copy-mode-vi MouseDragEnd1Pane

# since MouseDragEnd1Pane neither exit copy-mode nor clear selection,
# let single click do selection clearing for us.
bind-key -T copy-mode-vi MouseDown1Pane select-pane\; send-keys -X clear-selection

# this line changes the default binding of MouseDrag1Pane, the only difference
# is that we use `copy-mode -eM` instead of `copy-mode -M`, so that WheelDownPane
# can trigger copy-mode to exit when copy-mode is entered by MouseDrag1Pane
bind -n MouseDrag1Pane if -Ft= '#{mouse_any_flag}' 'if -Ft= \"#{pane_in_mode}\" \"copy-mode -eM\" \"send-keys -M\"' 'copy-mode -eM'
```

**Comment by subtleseeker** [comment]
> Here's my solution for better experience in drag selection (tmux 2.8):
> 
> ```
> set -g mouse on
> 
> # disable "release mouse drag to copy and exit copy-mode", ref: https://github.com/tmux/tmux/issues/140
> unbind-key -T copy-mode-vi MouseDragEnd1Pane
> 
> # since MouseDragEnd1Pane neither exit copy-mode nor clear selection now,
> # let single click do selection clearing for us.
> bind-key -T copy-mode-vi MouseDown1Pane select-pane\; send-keys -X clear-selection
> 
> # this line changes the default binding of MouseDrag1Pane, the only difference
> # is that we use `copy-mode -eM` instead of `copy-mode -M`, so that WheelDownPane
> # can trigger copy-mode to exit when copy-mode is entered by MouseDrag1Pane
> bind -n MouseDrag1Pane if -Ft= '#{mouse_any_flag}' 'if -Ft= \"#{pane_in_mode}\" \"copy-mode -eM\" \"send-keys -M\"' 'copy-mode -eM'
> ```
> 
> Note the above config can be used with both `nhdaly/tmux-better-mouse-mode` and `tmux-plugins/tmux-yank`.

@reorx It seems to be really good solution but its not working for me. 
This is my configuration:
CentOS 7
tmux-next 3.1
These are the plugins I use:
```
 # List of plugins
 set -g @plugin 'tmux-plugins/tpm'
 set -g @plugin 'tmux-plugins/tmux-sensible'
 set -g @plugin 'nhdaly/tmux-better-mouse-mode'
 set -g @plugin 'tmux-plugins/tmux-yank'
```
Any idea, where can I start to debug?

**Comment by vhristev** [comment]
I'm still searching how to make the mouse behave like regular terminal. Just select and when you want to copy it Command+C  ( or CTRL + C ). Sometimes I need to copy different things a couple of lines above or below and this exit from copy-mode is driving me crazy.
