### ISSUE TITLE
request: option to parse "#{pane_current_path}" in save-buffer

### ISSUE THREAD

**Issue by biocyberman** [tmux/tmux#1400]
I am using byobu+tmux and the possiblity to do `save-buffer "#{pane_current_path}/myfilename"` will make it possible to save buffer to the current working directory.  And saving to to cwd is more preferable than saving to `/tmp`

**Comment by nicm** [comment]
Try this please [x.diff.txt](https://github.com/tmux/tmux/files/2180618/x.diff.txt)

**Comment by biocyberman** [comment]
@nicm 

It worked perfectly for what I was looking for. Thank youu :) 
Just curious, I still haven't understood why cmd-load-buffer.c has to be modified also. 

For future viewers, this is what I did:

```
sudo mv /usr/bin/tmux /usr/bin/tmux.bak #backup stock tmux.
tmux kill-server #shutdown tmux
cd <tmux git repo>
patch -i x.diff.txt
sh autogen.sh
configure --prefix=/usr/local && make
sudo make install

#Modify /usr/share/byobu/keybindings/f-keys.tmux 
#bind-key -n S-F7 capture-pane -S -32768 \; save-buffer "$BYOBU_RUN_DIR/printscreen" \; delete-buffer \; new-window -n "PRINTSCREEN" "$BYOBU_EDITOR $BYOBU_RUN_DIR/printscreen"
bind-key -n S-F7 capture-pane -S -32768 \; save-buffer "#{pane_current_path}/printscreen" \; delete-buffer \; new-window -c "#{pane_current_path}" -n "PRINTSCREEN" "$BYOBU_EDITOR printscreen"
```

**Comment by nicm** [comment]
Applied now, will be in GitHub later. It would be strange to expand formats in save-buffer and not load-buffer as well. Thanks.

**Comment by biocyberman** [comment]
Follow up: To avoid overwriting, I am thinking it is useful to have timestamp in the output filename. For example: `save-buffer "#{pane_current_path}/printscreen#{date_hour_minute}"`.  Time stamp is similar to the output of `date +date +%Y%m%d%H%M)`
