### ISSUE TITLE
format tags in command string?

### ISSUE THREAD

**Issue by biocyberman** [tmux/tmux#1402]
With the improvement from #1400 , I now can do this:

`bind-key -n S-F7 capture-pane -S -32768 \; save-buffer "#{pane_current_path}/#{printscreen" \; delete-buffer \; new-window -c "#{pane_current_path}" -n "PRINTSCREEN" "vim printscreen"
`
However, this does not work:

`bind-key -n S-F7 capture-pane -S -32768 \; save-buffer "#{pane_current_path}/printscreen#{window_activity}" \; delete-buffer \; new-window -c "#{pane_current_path}" -n "PRINTSCREEN" "vim printscreen#{window_activity}"`

This is because new-window does not parse format tags in the command `vim printscreen#{window_activity}`. 

Other info:

My intention is to make a unique filename from timestamp to avoid overwriting. And I would pass it around for a short while. So, 
 `save-buffer "#{pane_current_path}/printscreen#{window_activity}` and ` new-window -c "#{pane_current_path}" -n "PRINTSCREEN" "vim printscreen#{window_activity}"` must refer to the same file.

**Comment by ThomasAdam** [comment]
Hmm.  I wonder whether we should change the mechanics in `cmd_copy_argv` to just expand formats, rather than keep doing this in all commands when some use case arises?  It might have to be further into the `cmd_find` logic though, as doing it in `cmd_copy_argv` is going to be too early before clients/sessions are established.

**Comment by ThomasAdam** [comment]
Hmm, but wouldn't this escaping need to happen everywhere else where we currently interpolate formats?

**Comment by nicm** [comment]
Well, it is more than commands are very likely to use # whereas normal arguments and filenames are not so much.

**Comment by nicm** [comment]
I think at this point using a script is appropriate so I'm going to leave this as it is for now. If we added this I think it would need a -F flag.
