### ISSUE TITLE
a lot of commands like ll doesnt work

### ISSUE THREAD

**Issue by f4h4m** [tmux/tmux#1405]
![screenshot from 2018-07-15 03-39-57](https://user-images.githubusercontent.com/20015479/42729059-2f5b1080-87e1-11e8-8c97-ffc6100286a8.png)

**Comment by ThomasAdam** [comment]
I suspect you're not launching a login shell (since `ll` isn't a command it's likely an alias you have).

Either way, nothing to do with tmux.

**Comment by f4h4m** [comment]
ll command working in ubuntu terminal

**Comment by f4h4m** [comment]
@ThomasAdam 
![Screenshot from 2019-05-12 00-46-09](https://user-images.githubusercontent.com/20015479/57574524-c94cc200-744f-11e9-80ac-c5afd2acf4ee.png)

set-option -g default-terminal "screen-256color"

# Mouse
# —---

set -g mouse on

# Windows
# —---—

# Split window horizontaly (legacy & 1.9+)
bind-key '|' split-window -h

# Split window verticaly (legacy & 1.9+)
bind-key '-' split-window -v
bind-key '_' split-window -v

# Status bar
# —------—
set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour137
set -g status-attr dim
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-fg colour81
setw -g window-status-current-bg colour238
setw -g window-status-current-attr bold
setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '

setw -g window-status-fg colour138
setw -g window-status-bg colour235
setw -g window-status-attr none
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

setw -g window-status-bell-attr bold
setw -g window-status-bell-fg colour255
setw -g window-status-bell-bg colour1

**Comment by f4h4m** [comment]
Just you need add source ~/.bashrc into ~/.bash_profile
