### ISSUE TITLE
"send -X copy-pipe" truncates large selections

### ISSUE THREAD

**Issue by andrey-utkin** [tmux/tmux#1407]
Steps to reproduce:
* add such a binding:
```
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe "xclip -sel clip -i -d :0"
```
* go to vi copy mode and select a couple of screens worth of text
* press 'y'
* paste from the clipboard to somewhere
* examine the pasted contents - it'll be incomplete

Alternative way not requiring any config:

* go to vi copy mode and select a couple of screens worth of text
* press 'y'
* switch to a different terminal with TMUX variable exoported, set manually to the same as in your tmux session
* execute `tmux send -X copy-pipe "cat > tmp"; sleep 1; cat tmp`

Versions: 2.7, also latest git master 4f04b2094ca0011277d23369cf03870227c6afc1 .
```
 $ uname -sp && tmux -V && echo $TERM
Linux Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
tmux master
st-256color
```

Gentoo Linux.

**Comment by andrey-utkin** [comment]
When I am reproducing the issue (with my config and busy session), the log is appended with just this:
```
1531832550.555342 %0 in mode: last=1531832132
1531832550.555409 cmdq_next <global>: empty
1531832550.555426 @0 active pane not changed
1531832551.263157 cmdq_next <global>: empty
1531832551.263227 @0 active pane not changed
1531832560.564651 %0 in mode: last=1531832132
1531832560.564736 cmdq_next <global>: empty
1531832560.564768 @0 active pane not changed
1531832570.574898 %0 in mode: last=1531832132
1531832570.575006 cmdq_next <global>: empty
1531832570.575390 @0 active pane not changed
```
Am happy to share full log - it's 14 MB.

**Comment by andrey-utkin** [comment]
Workaround: put the selection to tmux buffer (e.g. press Enter), then use such binding:
```
bind-key y run-shell "tmux save-buffer - | xclip -sel clip -i -d :0"
```
This works flawlessly.

**Comment by nicm** [comment]
You probably have set-clipboard on and so tmux is setting the clipboard with the escape sequence and overwriting what xclip has set. st has a limit on the size you can set using the clipboard escape sequence.

**Comment by andrey-utkin** [comment]
Thanks, looks you are right, `set-option -g set-clipboard off` fixes it.

**Comment by andrey-utkin** [comment]
I wonder, though, what exactly triggers "tmux (is) setting the clipboard with the escape sequence"?
Just for record, previously I had no explicit `set-clipboard` setting, and the implicit value is not exactly `on`, but `external`:
```
 $ tmux show-option -g -s set-clipboard
set-clipboard external
```
