### ISSUE TITLE
Certain characters overflow across panes with `cat filename` and running `tmux` over ssh

### ISSUE THREAD

**Issue by alphaCTzo7G** [tmux/tmux#1409]
Tmux works great most of the time.. and I know a lot of people run `vim` in `tmux` as their development environment. I ran into a weird problem, where if I do a `cat _identifier.py` where `_identifier.py` is the file from here: https://github.com/pallets/jinja/blob/master/jinja2/_identifier.py

the characters in `_idenfitifer.py` oveflow acrsoss the boundaries of the `tmux` pane as shown here: 

![2018-07-21_09-03-31](https://user-images.githubusercontent.com/29691914/43037699-30a2ac94-8cc5-11e8-9f15-f8d6bd4f7d40.gif)

Can this be corrected? I am using `screen-256color` as shown below.. 

The following command:
`uname -sp && tmux -V && echo $TERM`

gives the following output:
```
Linux x86_64
tmux master
screen-256color
```

I am running `tmux-master` version 2.7, compiled a few weeks back.
`dpkg --status tmux` returns

```
➜  ~ dpkg --status tmux
Package: tmux
Status: install ok installed
Priority: extra
Section: checkinstall
Installed-Size: 720
Maintainer: root@username-VirtualBox
Architecture: amd64
Version: 2.7-1
Provides: tmux
Description: tmux
```

**Comment by alphaCTzo7G** [comment]
@k-takata (https://github.com/vim/vim/issues/3237#issuecomment-406755205) mentioned that this could be pa problem with `tmux`..

**Comment by nicm** [comment]
Probably an issue with your Unicode widths, are you sure that your libc and font and terminal all agree on the Unicode version?

Does it work if you build tmux with utf8proc?

**Comment by alphaCTzo7G** [comment]
my libc version using `ldd --version`  gives 'GLIBC 2.23' which seems to support Unicodev8.0

I am using Putty to connect to my `tmux` server.. and using Consola font..I tried a couple of other fonts as well to see if it would rectify the issue `Anonymous Pro`, `Source Code Pro`, `Lucida Console` etc.. but none of them solved the problem although they are supposed to be quite recent and probably support unicodev10.

How do I determine the version that my `terminal`/`font` supports?

I see there is a easy way to enable `utf8proc` on macs[1].. but I am on Ubuntu. 

Are these the steps to install `tmux` with `utf8` support: https://github.com/tmux/tmux/issues/1057#issuecomment-328025206

[1]: https://github.com/tmux/tmux/issues/1057#issuecomment-328025206

**Comment by nicm** [comment]
2.1 used its own Unicode tables rather than libc so apparently they were
correct for your terminal.

Does putty have a setting about ambiguous width characters? You could try
changing that.

**Comment by alphaCTzo7G** [comment]
@nicm, yes.. it does..

![putty_2018-07-22_07-43-39](https://user-images.githubusercontent.com/29691914/43046787-1d4e83ac-8d83-11e8-8795-c404b7ad701b.png)
![putty_2018-07-22_07-40-50](https://user-images.githubusercontent.com/29691914/43046789-204a7ebc-8d83-11e8-997c-ee2597c03791.png)

Unfortunately, it didn't solve the problem.

**Comment by alphaCTzo7G** [comment]
I tried out `putty v 6.9`, mobaxterm, and bitvise ssh server. None of them helped..

Previously, atleast on Gnome terminal, this issue didn't happen.

After upgrading libevent, ncurses, and system libraries to the latest version, even Gnome terminal has started showing the same problem.

![totermw_2018-07-22_08-30-40](https://user-images.githubusercontent.com/29691914/43047288-e99d3862-8d89-11e8-8267-199f68326f48.png)

**Comment by nicm** [comment]
Show tmux logs from starting, cat the file then exit please.

**Comment by alphaCTzo7G** [comment]
@nicm Sent you are the logs by email.. I had to revert back to a backup of my VM, because along with the new updates and the new method of compilation.. tmux became very unstable. The log is from the backup of the VM. So the problem persists on Putty.. but doesn't exist on Gnome-terminal..

Let me know if I can provide any additional information..

**Comment by nicm** [comment]
If gnome-terminal works but not putty maybe you should talk to the putty
developers.

**Comment by alphaCTzo7G** [comment]
Actually.. its not just putty.. I have tried mobaxterm, bitvise ssh etc.. It happens on all of them.

**Comment by nicm** [comment]
Right, but it works in gnome-terminal... so it has Unicode character widths that agree with tmux.

There are a number of characters in your logs that do not agree with the width from my libc, so clearly they have changed.

tmux uses libc to establish Unicode character widths, so you need to make sure that your libc and terminal agree on the widths. If they don't, you will have display problems like this.

There is nothing tmux can do here, it is told the widths by libc.

**Comment by alphaCTzo7G** [comment]
ok.. no problem.. Thanks for your help.

Sorry.. if it seemed I was complaining.. I love tmux.. and I saw this edge case. So I thought I could help solve it for myself and for others. 

I don't know a lot about the internals of tmux.. and about Unicode character widths.. but I will figure that out and post here..
