### ISSUE TITLE
In tmux 2.0 the legacy `status-left-bg` always sets a value globally and not on the session

### ISSUE THREAD

**Issue by dgmstuart** [tmux/tmux#141]
Tmux 2.0 
OSX 10.10.5

``` tmux
➜  ~  tmux show -g status-left-bg
status-left-style default
➜  ~  tmux show status-left-bg # returns nothing, as expected
➜  ~  tmux set status-left-bg red
➜  ~  tmux show status-left-bg # still returns nothing - should show that the status-left-bg is red
➜  ~  tmux show -g status-left-bg # shouldn't be set
status-left-style bg=red
```
The impact is that calling `tmux set -u status-left-bg` doesn't re-set this option as expected, since it has been set globally.

https://github.com/tmux/tmux/commit/945339b443affdaaca260605e15b5a3b9a3c6e16 suggests that `status-left-bg` should be fully backwards-compatible, but it looks like that might not be the case for this scenario.

Setting the background colour with `-style` works as expected:
``` tmux
➜  ~  tmux show -g status-left-bg
status-left-style default
➜  ~  tmux show status-left-bg # returns nothing
➜  ~  tmux set status-left-style "bg=red"
➜  ~  tmux show status-left-style # still returns nothing
status-left-style bg=red
➜  ~  tmux show -g status-left-bg # shouldn't be set
status-left-style default
➜  ~  tmux set -u status-left-style
➜  ~  tmux show status-left-bg # returns nothing
```

Context: highlighting the status bar by way of surfacing a notification from Guard.
Original issue report: https://github.com/guard/guard/issues/795

**Comment by nicm** [comment]
Works fine for me, maybe this is already fixed.

$ tmux show -g status-left-bg
status-left-style default
$ tmux show status-left-bg
$ tmux set status-left-bg red
$ tmux show status-left-bg
status-left-style bg=red
$ tmux show -g status-left-bg
status-left-style default

**Comment by dgmstuart** [comment]
Cool - yes, I've built the development version from source and the issue seems to have been fixed at some point. 

Any idea when we can expect a new stable release?
