### ISSUE TITLE
tmux changes locale settings

### ISSUE THREAD

**Issue by derek-kim** [tmux/tmux#1410]
[environment]
Linux x86_64
tmux 2.6
screen  (within a tmux session) /  xterm-256color  (outside of tmux session)

I have observed a unexpected phenomenon when using tmux. When the terminal is outside of tmux session LC_ALL and LC_CTYPE are both set to "en_US.UTF-8". But when it's inside of a tmux session, LC_ALL is set to "" and LC_CTYPE is set to "UTF-8". I'm not exactly sure if it's a feature or a bug, but I cannot understand why this happens anyway and couldn't find any explanation related to this issue. This locale issue causes problems when I use scp command.

**Comment by nicm** [comment]
tmux does not change these environment variables, either you started tmux initially with them set differently so they are in the global environment, or your shell profiles are setting them differently inside tmux.

**Comment by derek-kim** [comment]
Okay. That being said, it's seems unrelated to tmux. Thank you so much.
