### ISSUE TITLE
Sequencing problem between display-pane+capture-pane and show-buffer

### ISSUE THREAD

**Issue by chreekat** [tmux/tmux#1412]
## Steps to reproduce (running with `-f/dev/null`)

```
$ tmux display-panes -d 0 'capture-pane -t %%'; tmux show-buffer | head
                      «press 0 to select the pane»
no buffers
```

## Expected behavior
I expect the buffer to be filled before show-buffer is run.

If display-panes' command is asynchronous, perhaps there could be a way to block on it?

Note that `tmux capture-pane -t 0; tmux show-buffer` works fine.

## Workaround

Just sleep for a second between the capture and the show. :frowning_face: 

## Versions

```
$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.7-rc
screen
```
I'm using tmux from NixOS, and see the same behavior on tmux 2.6 (from [nixpkgs@9e1d8b747060](https://github.com/NixOS/nixpkgs/tree/9e1d8b7470606387555c6b7e4dc62763f0594757)) and tmux 2.7-rc (from [nixpkgs@dae9cf6106da](https://github.com/NixOS/nixpkgs/tree/dae9cf6106da19f79a39714f183ed253c62b32c5)).

## Screenshot
![image](https://user-images.githubusercontent.com/538538/43095348-88090fb8-8e83-11e8-9724-4b99e8a54031.png)

## Logs
Can be provided if needed.

**Comment by ThomasAdam** [comment]
Yes, this is expected.

**Comment by chreekat** [comment]
I'd be interested in poking at such a feature, but it would take me a minute to get familiar with the codebase. Is there a similar example I could look at?

**Comment by nicm** [comment]
I think this is enough [x.diff.txt](https://github.com/tmux/tmux/files/2250692/x.diff.txt). I wonder if we need a -b flag like run-shell, although I can't see any reason why.

**Comment by chreekat** [comment]
Makes sense - presumably one can delegate the blocking-ness to the command being templated (e.g. `tmux display-pane 'run-shell -b "..."'`

**Comment by nicm** [comment]
No, display-panes will always block, whether or not it then runs run-shell -b won't make any difference.

What I meant is I can't see any reason you wouldn't want display-panes to block. If you press any key it cancels it (even the prefix), so I don't see when not being able to run any other commands while it is open will make any difference.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by chreekat** [comment]
Thanks for working on this. I just confirmed it solved my original use case!
