### ISSUE TITLE
how to change the prefix

### ISSUE THREAD

**Issue by shangadi** [tmux/tmux#1415]
Is there any possible way to change prefix to jh like we do in vim remapping Esc to jk (mac with touch bar). without using any keys like ctrl, alt or is it too much..

**Comment by nicm** [comment]
I don't understand the question.

**Comment by jungle-boogie** [comment]
@shangadi, you mean this?
https://github.com/tmux/tmux/wiki/FAQ#why-is-c-b-the-prefix-key-how-do-i-change-it
