### ISSUE TITLE
NULL dereference - tmux 2.7 

### ISSUE THREAD

**Issue by PatriciaSVMonteiro** [tmux/tmux#1417]
I've been testing the latest version of Tmux (v2.7) with 3 static analysis tools (Clang Static Analyzer, Infer and Cppcheck), two of which have identified a null dereference error every time you call the RB_GENERATE_STATIC or RB_GENERATE_STATIC macros. This error occurs because a possible null dereference occurs within the macro.

This is one of the reports returned by Clang Static Analyzer:
[csa_argument40_tmux2.7.pdf](https://github.com/tmux/tmux/files/2238620/csa_argument40_tmux2.7.pdf)

And this is Infer's report:
arguments.c:40: error: NULL_DEREFERENCE
  pointer `tmp` last assigned on line 40 could be null and is dereferenced at line 40, column 1.
  38.   
  39.   static int	args_cmp(struct args_entry *, struct args_entry *);
  40. > RB_GENERATE_STATIC(args_tree, args_entry, entry, args_cmp);
  41.   
  42.   /* Arguments tree comparison function. */

**Comment by nicm** [comment]
You will need to look at the definition of RB_GENERATE_STATIC and work out which statement is the problem in order to verify if this is a false positive (I suspect it is). Try expanding the macro yourself into a .c file.
