### ISSUE TITLE
Path of logging files

### ISSUE THREAD

**Issue by karakays** [tmux/tmux#1418]
Is there a way to specify the location where logging files are kept? As per man pages, log files are written into the current directory (where tmux started), is there a way to override that?

**Comment by nicm** [comment]
No, what for?

**Comment by karakays** [comment]
To keep them well organized in a separate directory. I don't want my home directory to get messy with lots of config files, log files, etc.

**Comment by nicm** [comment]
tmux log files are for debugging tmux, if you are doing that and you want the log files to go elsewhere then start tmux from that directory.
