### ISSUE TITLE
copy-mode -e but don't exit if selecting

### ISSUE THREAD

**Issue by mckellyln** [tmux/tmux#1420]
Hi,
Thx for amazing tmux.
I love copy-mode -e, but for one minor request - I don't want to exit copy-mode when scrolling to the bottom if a selection is in process.  Anyone know of a way to exit copy-mode when at the bottom except for when a selection is happening ?

I'm using tmux master, commit aa32457772f175cd7b09b8a70caa002b44c0152b
built on Ubuntu 16.04 with 4.15 kernel on x86_64

**Comment by mckellyln** [comment]
I think like this, in window_copy_pagedown():
```
#if 0
	if (scroll_exit && data->oy == 0)
		return (1);
#else // stay in copy-mode if selecting ...
	if (scroll_exit && data->oy == 0)
    {
	    if (data->screen.sel.flag)
        {
		    if(data->endsely == data->sely)
		        return (1);
        }
        else
		    return (1);
    }
#endif
	window_copy_update_selection(wp, 1);
	window_copy_redraw_screen(wp);
```

**Comment by nicm** [comment]
You can not use copy-mode -e and instead bind the scroll down keys to cancel unless selection_present is set. Something like (not tested):
~~~~
bind -Tcopy-mode WheelDownPane select-pane\; if -F '#{selection_present}' 'send -XN5 scroll-down' 'send -XN5 scroll-down-and-cancel'

**Comment by mckellyln** [comment]
Yes, thx, doing this everywhere I was doing scroll/half/page-down works well.
