### ISSUE TITLE
Copy does not copy all of the selcted text

### ISSUE THREAD

**Issue by codebam** [tmux/tmux#1421]
When copying text using the mouse in tmux, tmux doesn't copy all of the selected text to the clipboard.

Here it was concluded that by setting `set -g set-clipboard off` solves this issue, but in my experience it does not. https://github.com/tmux/tmux/issues/1119

Tmux version: 2.7
Platform: Void Linux (glibc)
Problem: Same as issue linked above, to reproduce copy more than 20 or 30 lines and only 5 or 6 will be copied to the clipboard.

```
Linux unknown
tmux 2.7
tmux-256color-italic
```

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by codebam** [comment]
Yeah, my bad. I pressed shift-enter by accident

**Comment by codebam** [comment]
Here's my tmux.conf

```
set -g default-terminal "tmux-256color-italic"
# set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256*:Tc"
set -ga terminal-overrides ',xterm*:smcup@:rmcup@'
set -wg xterm-keys on
setw -g mouse on
set -g set-clipboard off

# use ctrl-a instead of ctrl-b
# unbind C-b
# set -g prefix C-a
# bind C-a send-prefix

# toggle the status line with: prefix, b
bind-key b set-option status

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# change bar color
set -g status-bg default
set -g status-fg white

# fix input lag on esc
set -sg escape-time 0

# select panes with vim keybindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

setw -g aggressive-resize on
# resize the pane the same way screen does
```

**Comment by codebam** [comment]
My custom TERM was generated with this (it's just screen with italics)

```
tmux-256color-italic|tmux with 256 colors and italic,
  sitm=\E[3m, ritm=\E[23m,
  use=screen-256color,
```

**Comment by codebam** [comment]
Here's a tmux server log https://transfer.sh/5qdjf/tmux-server-4459.log

**Comment by nicm** [comment]
What clipboard? Do you mean a paste buffer in tmux? If you do "tmux saveb /tmp/foo" is all the text there?

**Comment by codebam** [comment]
I mean the system clipboard (xsel -b), and yes it is all there when I run that

**Comment by nicm** [comment]
As you have set-clipboard off and no key bindings that call xsel or xclip, tmux doesn't have anything to do with the system clipboard and won't try to set it. If you are still seeing text copied in copy mode with the mouse appear in the clipboard and also in a buffer, then you probably didn't turn set-clipboard off properly. Are you sure you restarted tmux entirely?

**Comment by codebam** [comment]
Yes I made sure to close all my tmux sessions and then did `tmux a` to make sure none were still running. How would I tell tmux to use `xsel` or `xclip` to copy to my clipboard when using the mouse?

**Comment by codebam** [comment]
Solved, used these options in my tmux.conf

```
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
```
