### ISSUE TITLE
send-keys is stripping spaces in strings that should be interpreted as series of characters

### ISSUE THREAD

**Issue by daveyarwood** [tmux/tmux#1425]
# Background

Per the man-page (emphasis mine):

> send-keys [-lMRX] [-N repeat-count] [-t target-pane] key ...
>     (alias: send)
>     Send a key or keys to a window.  Each argument key is the name of the key (such as ‘C-a’ or ‘NPage’) to send; **if the string is not recognised as a key, it is sent as a series of characters.**  The -l flag disables key name lookup and sends the keys literally.  All arguments are sent sequentially from first to last.  The -R flag causes the terminal state to be reset.

I observed that this behavior was working as described back when I was using the older version of tmux that comes in the official Ubuntu 16.04 repos (tmux 2.1, IIRC). You can also see how it should work [in this blog post](https://blog.damonkelley.me/2016/09/07/tmux-send-keys/).

```
$ tmux send-keys -t 1 "ls -1" Enter
# $ ls -1<Enter>
```

# Issue

I am now running a newer version of tmux (2.7~20180802), and it appears that this behavior has broken. If I create a split so that I have two panes, 1 and 2, and in pane 1, I type:

```
$ tmux send-keys -t 2 "ls -l" Enter
```

In pane 2, I see:

```
$ ls-l
ls-l: command not found
```

Notably, if I include the Space character explicitly, the `ls -l` command does work:

```
$ tmux send-keys -t 2 "ls" Space "-l" Enter
```

However, this is cumbersome for my script, which involves scripting running a bunch of commands, i.e. `do this && do that && do this-other-thing`. The spaces are all being stripped out, i.e. `dothis&&dothat&&dothis-other-thing`. The workaround is something like:

```
$ tmux send-keys -t 2 "do" Space "this" Space "&&" Space # etc.
```

which is clearly not great!

# System info

```
$ uname -sp; tmux -V; echo $TERM
Linux x86_64
tmux-next master
tmux-256color
```

I'm running Ubuntu 16.04, and I have the tmux-next package installed from the pi-rho/dev ppa:

```
$ apt show tmux-next
Package: tmux-next
Version: 2.7~20180802~bzr4105+21-1ubuntu1~ppa0~ubuntu16.04.1
...
Maintainer: pi-rho <ubuntu@tyr.cx>
...
APT-Sources: http://ppa.launchpad.net/pi-rho/dev/ubuntu xenial/main amd64 Packages
```

**Comment by nicm** [comment]
Works for me, show logs please.

**Comment by daveyarwood** [comment]
Logs attached. I followed the process outlined [here](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) and repro'd the issue.

[tmux-client-22999.log](https://github.com/tmux/tmux/files/2254577/tmux-client-22999.log)
[tmux-out-23001.log](https://github.com/tmux/tmux/files/2254578/tmux-out-23001.log)
[tmux-server-23001.log](https://github.com/tmux/tmux/files/2254579/tmux-server-23001.log)

I will go ahead and mention, in case it's relevant, that I use fish shell. However, I also experience the same behavior when I go into a bash subshell, so AFAICT it's not fish-related.

**Comment by nicm** [comment]
Hmm this doesn't log what I hoped it did, can you apply this please then rebuild tmux and show me similar logs: [x.diff.txt](https://github.com/tmux/tmux/files/2254723/x.diff.txt)

**Comment by krader1961** [comment]
Works for me. I too use fish as my primary shell. I built and installed tmux from Git head (commit eceaa9a49). I started a new tmux session. In a different window I did `tmux send-keys -t 0 '  ls   -l   '`. All the spaces were retained in the target session.

@daveyarwood You haven't done something weird like create a fish function or script named `tmux`? What does `type tmux` report?

**Comment by daveyarwood** [comment]
I have done something slightly weird, as a consequence of using the tmux-next page which installs an executable called `tmux-next` instead of `tmux`:

```
$ type tmux
tmux is /home/dave/.bin/tmux

$ cat ~/.bin/tmux
#!/bin/sh

# I use the tmux-next package in the ppa:pi-rho/dev repo, which is a lot more
# up to date than the version in the official Ubuntu ppa. Some tools I use rely
# on tmux being on the PATH, so that's what this script is for.

tmux-next $@
```

...oh, maybe the issue is that `$@` is exploding the arguments!

**Comment by krader1961** [comment]
> maybe the issue is that $@ is exploding the arguments!

Bingo! POSIX shells are dangerous due to how var expansion and word splitting interact. You want `tmux-next "$@"` in this case.

**Comment by daveyarwood** [comment]
That totally works. Thanks for walking through this with me, @nicm and @krader1961 ! :tada:
