### ISSUE TITLE
ascii escape sequences not work as expected

### ISSUE THREAD

**Issue by doraeric** [tmux/tmux#1426]
[tmux log](https://github.com/tmux/tmux/files/2256380/tmux-issue.zip)
my platform: Ubuntu 16.04
outside tmux
```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.7
xterm
```
inside tmux
```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.7
screen
```

## Reproduce
use default config
```
$ printf '\033[H\033[2J'
```
Result: Tmux move the the cursor to top. If I scroll up, I can see the next command is right below the previous one, but I expect there would be blank between these two commands.

`ESC` `[` `H` is move cursor to top left corner according to wiki, and
`ESC` `[` `2` `J` is clear entire screen, and many terminals are just moving the content up

So all the content including the blank below the cursor should be in the buffer, and pressing `Pg Up` would show the previous status.

## Illustrate
```
┌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│$ echo hi                │
│hi                       │
│$ printf '\033[H\033[2J' │
│                         │
│                         │
│                         │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
```
after `Enter`
expect (also real status without tmux in gnome terminal):
```
│$ echo hi                │
│hi                       │
│$ printf '\033[H\033[2J' │
│                         │
│                         │
│                         │ <= buffer
┌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│$                        │ <= window
│                         │
│                         │
│                         │
│                         │
│                         │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
```
actually:

```
│$ echo hi                │
│hi                       │
│$ printf '\033[H\033[2J' │ <= buffer
┌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│$                        │ <= window
│                         │
│                         │
│                         │
│                         │
│                         │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
```

## C-l behaviour
There is another problem, but more relative to bash or zsh.
When there's `xterm` in `$TERM`, pressing `Control` + `L` will make bash print
`ESC` `[` `H` `ESC` `[` `2` `J`
If no, bash will print
`ESC` `[` `H` `ESC` `[` `J`

In gnome terminal without tmux:
```
│$ echo hi                │
│hi                       │ <= buffer
┌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│$ cat xxx                │ <= window
│1                        │
│1                        │
│2                        │
│2                        │
│$ printf '\033[H\033[J'  │( same as clear command)
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
```
after enter

```
│$ echo hi                │
│hi                       │ <= buffer
┌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┐
│$                        │ <= window
│                         │
│                         │
│                         │
│                         │
│                         │
└╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┘
```
tmux set `$TERM` to `screen(-256color)`, how do I make bash behave like there's `xterm` in `$TERM`?

**Comment by nicm** [comment]
tmux does not scroll lines which have never been used into the history on clear - they are empty, so what use are they? This entire behaviour (scrolling visible content rather than clearing it) is an extension, so there is no fixed rule on how it should behave. As it happens, gnome-terminal behaves the same for me, perhaps your VTE is too old, or too new.

I don't know what you are talking about with C-l, it behaves exactly the same as clear for me. Are you checking the history with copy mode?

**Comment by doraeric** [comment]
Hi, I have uploaded video for showing the difference.
[gnome](https://vimeo.com/282989429)
[tmux](https://vimeo.com/282989653)
with and without tmux, `ESC` `[` `H` `ESC` `[` `2` `J` behaves differently

Yes, there's no fixed rule on the behaviour, It's just a small wish I hope tmux can support.
Here's the package I found on my system.
- libvte-2.91-0
- libvted-3-0

**Comment by nicm** [comment]
We are not going to scroll a bunch of blank lines into the history on clear for no reason.

**Comment by doraeric** [comment]
Some cli tools use the control sequence to format their output, and users can switch between different states by page up/down quickly. Maybe adding an option to let users configure the behaviour will be wonderful?

It's okay to close the issue if tmux is not going to support this.

**Comment by nicm** [comment]
No we do not need an option for this. The important content is always in the history, I don't think blank lines are useful.
