### ISSUE TITLE
user-keys[] mapped sequences won't bind when read from a config file

### ISSUE THREAD

**Issue by izemmouri** [tmux/tmux#1428]
Hi,

I have my terminal set up to send "\e[[CSa" for CTRL+SHIFT+a.
Choose a key sequence then please try the following from an interactive tmux command line prompt:
set -s user-keys[0] "\e[[CSa"
bind -n User0 split-window

This works perfectly when done directly from the tmux command prompt, but if you put the same 2 lines in /etc/tmux.conf, suddenly the key sequence doesn't can bound at all.

What is happening? Is this a bug?

**Comment by nicm** [comment]
Try \033 not \e?

**Comment by izemmouri** [comment]
I did. No change. I take this opportunity to emphasize the fact that doing this mapping from the tmux command prompt (Prefix ':') works perfectly. It is when reading the same 2 binding commands from a config file, /etc/tmux.conf or .tmux.conf that the binding doesn't happen.

**Comment by nicm** [comment]
Show logs please.

**Comment by izemmouri** [comment]
The tmux-server logs seem to be extremely verbose. Do you really want all of it?

**Comment by nicm** [comment]
yes

**Comment by izemmouri** [comment]
Very sorry. My tmux.conf just unbinded every key in the root table a few lines after... Sorry.

**Comment by nicm** [comment]
So you have found the problem, yes?

**Comment by izemmouri** [comment]
Oh yes, yes. As i said, there was an unbind-key -a just a few lines after the bind -n User0 "\e[[CSa".
