### ISSUE TITLE
`tmux kill-server` fails if server started via my script to start or reattach to existing sessions

### ISSUE THREAD

**Issue by krader1961** [tmux/tmux#1429]
I have a script to reconnect to, or start, a given set of tmux sessions in new terminal windows. The end result is running `tmux new-session -s "$session_name"` commands as the first thing done in each terminal window. When I launch the tmux server via this script doing `tmux kill-server` is a no-op. But if I start a new tmux server via a single instance of the same tmux command or just `tmux` then `tmux kill-server` works.

Attached is a server log showing a `kill-server` that does not kill the tmux server. I've also attached the five tmux client scripts that resulted from the `tmux new-session` run in each of the five terminal windows.

[tmux-client-29628.log](https://github.com/tmux/tmux/files/2272738/tmux-client-29628.log)
[tmux-client-29686.log](https://github.com/tmux/tmux/files/2272739/tmux-client-29686.log)
[tmux-client-29756.log](https://github.com/tmux/tmux/files/2272740/tmux-client-29756.log)
[tmux-client-29824.log](https://github.com/tmux/tmux/files/2272741/tmux-client-29824.log)
[tmux-client-29892.log](https://github.com/tmux/tmux/files/2272742/tmux-client-29892.log)
[tmux-server-29694.log](https://github.com/tmux/tmux/files/2272743/tmux-server-29694.log)

**Comment by krader1961** [comment]
And here are the logs on the same system when I first do `tmux` in an existing terminal window with no tmux server currently running. Followed by `tmux kill-server` in a different window. I didn't see any obviously significant differences between the two server logs.

[tmux-client-30084.log](https://github.com/tmux/tmux/files/2272751/tmux-client-30084.log)
[tmux-server-30086.log](https://github.com/tmux/tmux/files/2272752/tmux-server-30086.log)

**Comment by nicm** [comment]
~~~~
$ grep 'server_signal' tmux-server-*.log
tmux-server-30086.log:1533786769.887828 server_signal: Terminated: 15
$
~~~~

In the second log, tmux is getting the SIGTERM. In the first, it isn't.

Something else is eating it. Do you have a "trap" in your shell script?

**Comment by krader1961** [comment]
Sorry for the noise. MacOS doesn't make it easy to inspect the signal disposition for an already running process. So I wrote a small program to display which signals are blocked or ignored and installed it as `tmux`. Lo and behold. My shell is running tmux with all signals in the blocked state when started via `exec tmux`. When run without the `exec` no signals are blocked. Definitely a WTF situation. I'll take it up with the shell maintainers.
