### ISSUE TITLE
Shorcuts not working

### ISSUE THREAD

**Issue by Xosmond** [tmux/tmux#143]
I have a problem, i have installed tmux on OS X El capitan thought brew "brew install tmux" but when i type "tmux" and after that press "ctrl+b c" to open a new panel nothing happen, no shortcut works. Also i notice that i don't have a ~/.tmux.conf. So i created one to change to ctrl+a but nothing works. Somebody know what could i do?

**Comment by nicm** [comment]
What if you do:

tmux neww

Inside tmux, does it open window?

**Comment by Xosmond** [comment]
The current windows still there but It looks like it there another but i don't know how access it . 
![captura de pantalla 2015-10-15 a las 4 33 38 p m](https://cloud.githubusercontent.com/assets/11930063/10528346/4c48b42e-735b-11e5-8347-ead83e1cdbc6.png)

**Comment by nicm** [comment]
Are you sure you are pressing C-b then c, not C-b C-c?
