### ISSUE TITLE
Not all combining characters are displayed inside tmux.

### ISSUE THREAD

**Issue by agguser** [tmux/tmux#1430]
tmux 2.7, Arch Linux
```
% urxvt -fn -misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1   # or xterm with '*combiningChars: 5'
% echo "กุิ้"
% tmux
% <Up><Up>   # 'echo "กุิ"' is shown (note that  ้ is not shown!)
```
Does `tmux` limit number of combining characters to 2? How to fix this?

**Comment by nicm** [comment]
Logs?

**Comment by agguser** [comment]
Here is the logs (with personal environment variables filtered out):

[tmux-client-4072.log](https://github.com/tmux/tmux/files/2273437/tmux-client-4072.log)
[tmux-out-4074.log](https://github.com/tmux/tmux/files/2273438/tmux-out-4074.log)
[tmux-server-4074.log](https://github.com/tmux/tmux/files/2273439/tmux-server-4074.log)

You may reproduce the problem with
```
% echo "กุิ้" > /tmp/t.txt
% cat /tmp/t.txt
กุิ้
% tmux
% cat /tmp/t.txt
กุิ
```

**Comment by nicm** [comment]
Does this fix it?
~~~~
--- a/tmux.h
+++ b/tmux.h
@@ -517,7 +517,7 @@ struct msg_stderr_data {
  * A single UTF-8 character. UTF8_SIZE must be big enough to hold at least one
  * combining character as well.
 */
-#define UTF8_SIZE 9
+#define UTF8_SIZE 12
 struct utf8_data {
        u_char  data[UTF8_SIZE];

**Comment by agguser** [comment]
Yes, it works. Thank you!

So to support maximum of 5 combining characters (3-byte per character), I have to set UTF8_SIZE to 18. Will this change be included in the repository? (So it will be supported in all platforms, e.g. Termux in Android)

**Comment by nicm** [comment]
Yes I will change it to 18.

**Comment by nicm** [comment]
I have changed it to 18 in OpenBSD now, it will be GitHub later and then in tmux 2.8. Thanks!
