### ISSUE TITLE
new pane has modified PATH-variable (anaconda3)

### ISSUE THREAD

**Issue by PaPeK** [tmux/tmux#1431]
Hi there,

I installed recently anaconda3 in tmux(apparently not recommended... didnt know). I wanted to switch back to my python-packages from before and removed all PATH modifications of anaconda in ~/.zshrc, ~/.bashrc. 
When I now open tmux the first pane outputs correctly: 
```
which python
/usr/bin/python
```

However aver new pane gives me:
```
which python
/home/.../anaconda3/bin/...
```

I also checked the path variables. The first pane says:
```
echo $PATH
/home/dudu/Wolfram/Mathematica/7.0/Executables:/home/dudu/bin:/home/dudu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

while every other new pane says:
```
echo $PATH
/home/dudu/Wolfram/Mathematica/7.0/Executables:/home/dudu/anaconda3/bin:/home/dudu/bin:/home/dudu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

note that anaconda3/bin is not added at the start..... I dont get it.
Can anyone help?

**Comment by nicm** [comment]
It's probably still in the global or session environment.

**Comment by PaPeK** [comment]
Ok I tried logging out and in again. How do I get rid of it. Where is the session environment saved?

**Comment by nicm** [comment]
Either restart tmux entirely (tmux kill-server) or fiddle with tmux setenv.

**Comment by PaPeK** [comment]
Cool! I thought exiting tmux would be equivalent with tmux kill-server. Obviously not. That solved it. THANKS!
