### ISSUE TITLE
Changing Alt+function keys to use xterm-style modifier codes instead of leading ESC

### ISSUE THREAD

**Issue by craigbarnes** [tmux/tmux#1437]
I just noticed that tmux sends `ESC ESC [ 2 0 ~` for <kbd>Alt</kbd>+<kbd>F9</kbd>, whereas the the current xterm release seems to send `ESC [ 2 0 ; 3 ~`. Would there be any objection to adding an option (or "DEC Private Mode") to tmux to use the other scheme?

I realize it may seem like a frivolous change, but the advantage of not using double-escape is that there's no ambiguity and therefore no need to use timing to disambiguate. The double-escape sequence could either be <kbd>Esc</kbd> followed by <kbd>F9</kbd> or <kbd>Alt</kbd>+<kbd>F9</kbd>.

```
$ uname -s && tmux -V && echo $TERM
Linux
tmux 2.7
screen-256color
```

**Comment by craigbarnes** [comment]
On seconds thoughts, I guess doing this isn't really worth complicating the code.

**Comment by nicm** [comment]
I think all the function keys where the modifiers are builtin need to be marked as well so they get translated to xterm keys, please try this: [x.diff.txt](https://github.com/tmux/tmux/files/2293824/x.diff.txt)

**Comment by craigbarnes** [comment]
That patch seems to work nicely. Are there any backwards compat concerns with enabling it by default?

**Comment by nicm** [comment]
No I don't think so. If kf49 implies Meta (that is, the key that kf49 specifies is M-F1) then M-kf49 is nonsense, it must be interpreted as Escape then kf49.

If the terminal doesn't specify kf49 and doesn't send xterm-style keys it is a bit harder, if the terminal sends Escape+kf1 are we supposed to send Escape+F1 or M-F1? But nobody has complained so far so I think we can leave the unmodified function keys alone for now.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by craigbarnes** [comment]
Awesome, thanks! That was a lot easier than I expected.
