### ISSUE TITLE
Supporting unicode escape sequences in config string literals

### ISSUE THREAD

**Issue by chrahunt** [tmux/tmux#1441]
It would be  helpful if unicode code point escape sequences could be embedded in tmux configuration string literals. Assuming we use something like the C syntax for universal character names, the following would be considered equivalent:

```
set -g status-right '⌚ %H:%M:%S '
```

```
set -g status-right "\u23F1 %H:%M:%S "
```

or

```
set -g status-right '🕐 %H:%M:%S '
```

```
set -g status-right "\U0001F550 %H:%M:%S "
```

Currently (on master) it appears that the string processing in the config file does not permit any escape sequences other than `\e`, `\t`, `\n`, and `\r` per [here](https://github.com/tmux/tmux/blob/91dec25fc96d17f99ba63115acf1cbbfb058d781/cmd-string.c#L211).

**Comment by nicm** [comment]
Sure, yes, it would...
