### ISSUE TITLE
Status bar in top doesn't work properly

### ISSUE THREAD

**Issue by dikiaap** [tmux/tmux#1446]
```
$ uname -sp && tmux -V && echo $TERM
Linux athlon
tmux master
xterm-256color
```

Config:
`set-option -g status-position top`

I just updated tmux to recent commit and the status bar position in top doesn't work, it just appears in a while then dissappears again.

But it works if I change it to bottom.

**Comment by nicm** [comment]
Try git pull now please and see if this is fixed.

**Comment by dikiaap** [comment]
It works now. Thank you!

**Comment by dikiaap** [comment]
Hi, @nicm.

Now I have a problem if mouse selection is on.
I want to select Download folder but it turns out Documents folder is selected.

```
set-option -g status-position top
set-option -g mouse on
```

![SS](https://user-images.githubusercontent.com/8542502/44379948-a2053c00-a532-11e8-8f83-940d470d0a3e.png)

**Comment by nicm** [comment]
Try again now please.

**Comment by dikiaap** [comment]
Fixed. Thanks again
