### ISSUE TITLE
M-Left or M-Right no longer working with Tmux 2.7

### ISSUE THREAD

**Issue by joerideg** [tmux/tmux#1448]
Hi, 
First of all thank you for your hard work, its an awesome tool keep it up!

Environment:
```shell
~ -> uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.7
screen-256color
```
Goal: I'm trying to (and believe I have in the past without problems) resize panes using `Alt + <arrow key>`

Reproduction:
- create ~/.tmux.conf
- add 
```
bind -n M-v split-window -h -c "#{pane_current_path}"
bind -n M-h split-window -v -c "#{pane_current_path}"
bind -n M-Down resize-pane -D
bind -n M-Up resize-pane -U
bind -n M-Left resize-pane -L
bind -n M-Right resize-pane -R
bind -n M-1 resize-pane -L
bind -n M-2 resize-pane -R
```
- source ~/.tmux conf
- split a vertical pane and a horizontal pane
- try to resize the pane(s) with `alt+<arrow key>`

Expectation:
I can resize a pane both vertically and horizontally using `alt+<arrow key>`

Actual:
I can resize a pane vertically using `alt+up` and `alt+down`
I *can not* resize a pane horizontally using `alt+left` and `alt+right`,
 but I *can* resize a pane horizontally using `alt+1` and `alt+2`

Additionally it seems no binding works when bound to M-Left or M-Right for example `previous-window`

**Comment by nicm** [comment]
Sounds like your terminal or WM is eating M-Left and M-Right. Does Escape then Left work instead?

**Comment by joerideg** [comment]
No it does not but I looked it up and it seems you are right! 
https://www.mankier.com/1/sakura#Keybindings_Support
I'm using the Sakura terminal since a couple of months, and its supposed to bind (if I'm reading the man correctly) to alt + cursor left / right. 
I'm going to see if I can disable the keybinding and test again.

**Comment by joerideg** [comment]
Ugh it was even worse, my new Linux Mint 19 install appearantly set Alt + Right and Alt + Left to positioning windows shortcuts by default now. Which i never noticed because I always run the terminal maximized. 
Closing the non-issue! 

Again thanks for your hard work!
