### ISSUE TITLE
The last line in Zsh tab-completion is not completely disappear

### ISSUE THREAD

**Issue by dikiaap** [tmux/tmux#1451]
Information:
- Shell: Zsh with Oh My Zsh
- [tmux-client-7444.log](https://github.com/tmux/tmux/files/2320811/tmux-client-7444.log)
- [tmux-out-7446.log](https://github.com/tmux/tmux/files/2320812/tmux-out-7446.log)
- [tmux-server-7446.log](https://github.com/tmux/tmux/files/2320813/tmux-server-7446.log)

```
$ uname -sp && tmux -V && echo $TERM
Linux athlon
tmux master
xterm-256color
```

Config:
`set-option -g status-position top`

This is happens when Zsh tab-completion with the status bar at the top enabled.
When canceling tab-completion, the last line in Zsh tab-completion is not completely disappear.

![ss](https://user-images.githubusercontent.com/8542502/44617553-a1500b00-a88e-11e8-9b24-7dd8024804d9.png)

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by dikiaap** [comment]
Ping @nicm

**Comment by nicm** [comment]
Is this the same as https://github.com/tmux/tmux/issues/931? Try this:
~~~~
tmux set -as terminal-overrides ',*:indn@'
~~~~
Then detach and reattach tmux and see if the problem goes away.

**Comment by dikiaap** [comment]
I put that in my configuration and still doesn't work.

I think since #1446

**Comment by nicm** [comment]
OK I think I know what it might be, I will look later in the week.

**Comment by dikiaap** [comment]
Yes, it does.

**Comment by nicm** [comment]
Great, applied, now.
