### ISSUE TITLE
Tmux crashed

### ISSUE THREAD

**Issue by NickHibma** [tmux/tmux#1452]
tmux crashed while being extremely reliable for months with accessing it many, many times from various devices in various screen sizes (150+x80+ (WXGA screen) as well as 25x40 (iPhone)). I assume the crash is in tmux (not in libevent) but the stack trace is incomplete. I'm afraid I cannot tell you much more about the circumstances as tmux was all of a sudden gone.

Versions:
   tmux 2.7
   libevent-2.1.so.6

FreeBSD violet.van-laarhoven.org 11.2-RELEASE-p2 FreeBSD 11.2-RELEASE-p2 #0: Tue Aug 14 21:45:40 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

(gdb) bt
#0  0x0000000800b6a1a7 in _pthread_mutex_init_calloc_cb () from /lib/libc.so.7
#1  0x0000000800b4fcd7 in _malloc_thread_cleanup () from /lib/libc.so.7
#2  0x0000000800b6bd5f in _pthread_mutex_init_calloc_cb () from /lib/libc.so.7
#3  0x0000000800b740b8 in realloc () from /lib/libc.so.7
#4  0x000000000045a0f2 in ?? ()
#5  0x000000000041def7 in ?? ()
#6  0x00000000004205e9 in ?? ()
#7  0x000000000042026c in ?? ()
#8  0x0000000000458f46 in ?? ()
#9  0x0000000000428304 in ?? ()
#10 0x0000000000430127 in ?? ()
#11 0x0000000000436f0f in ?? ()
#12 0x000000080109406f in event_base_assert_ok_nolock_ () from /usr/local/lib/libevent-2.1.so.6
#13 0x000000080108ff4e in event_base_loop () from /usr/local/lib/libevent-2.1.so.6
#14 0x000000000042f79a in ?? ()
#15 0x000000000043a4b3 in ?? ()
#16 0x0000000000407238 in ?? ()
#17 0x00000000004425c3 in ?? ()
#18 0x0000000000404a6f in ?? ()
#19 0x00000008006a1000 in ?? ()
#20 0x0000000000000000 in ?? ()

**Comment by nicm** [comment]
This doesn't show anything useful so unless you can reproduce, preferably
with master, there is nothing I can do here.

**Comment by NickHibma** [comment]
Yes, I figured that would be a problem, but I don't have more info unfortunately. In that case we can close this bug.

**Comment by unphased** [comment]
This issue's stack trace content inadvertently added a bunch of noisy references to other GitHub issues. recommend editing the OP message or something to clean that up.
