### ISSUE TITLE
Memory leak bugs. 

### ISSUE THREAD

**Issue by fangang190** [tmux/tmux#1453]
Hi, 

We've found some leak bugs in Tmux, please have a look. 
To save your precious time, I list all of them in this post. 

1 Place: cmd-run-shell.c : 94 
Description: 
cdata leaks when job_run fails. I've checked the code of job_run, it does not free cdata when fails. 

![image](https://user-images.githubusercontent.com/1679432/44649404-52cd7880-aa16-11e8-8798-2f51187aa41c.png)

2 Place: /cmd-if-shell.c : 101
Description: 
Same problem as above in cmd-if-shell.c

![image](https://user-images.githubusercontent.com/1679432/44649498-af309800-aa16-11e8-866e-36cf42930b9c.png)

3 Place: /cmd-load-buffer.c : 79
Description: 
Similar problem

![image](https://user-images.githubusercontent.com/1679432/44649543-d1c2b100-aa16-11e8-8172-935a5fb6a1ea.png)

4 Place: format.c: 1099
Description:

"found" is leaked when format_choose failed. 
![image](https://user-images.githubusercontent.com/1679432/44649684-236b3b80-aa17-11e8-9606-bbf5ede4ff72.png)

Thanks

GF
Sourcebrella

**Comment by nicm** [comment]
Fixed in OpenBSD now, thanks! Will be in GitHub a bit later.
