### ISSUE TITLE
After the vertical split, the artifacts is displayed on the command line.

### ISSUE THREAD

**Issue by asan13** [tmux/tmux#1456]
Hi, I'm running tmux master (b29028a9 at the time of this writing) and I'm noticing a issue in terminal.
The problem appeared after one of the latest updates, I can not say more precisely.

If we make a vertical split, then press the arrow several times to scroll through the story, then:
1. A row appears at the top
2. Type the text in the command line, go to the middle of the line (in mode vi), type symbols or use backspace - artifacts appear. Instead of inserting symbols are replaced; when deleted, symbols remain on the right;
3. etc 
![tmux](https://user-images.githubusercontent.com/3297311/44800647-9a433880-abbf-11e8-8cd5-38b466886d42.png)

shell bash with `set -o vi `

* Platform: Ubuntu 16.04
* Terminal: gnome-terminal
* TERM outside and inside tmux: xterm-256color

**Comment by nicm** [comment]
I can reproduce this, and I think it is a bug I have been seeing with emacs but could not find...

**Comment by nicm** [comment]
I think this is the fix, please try making this change:
~~~~
diff --git a/tty.c b/tty.c
index facf5814..ac24a7f2 100644
--- a/tty.c
+++ b/tty.c
@@ -1147,7 +1147,7 @@ tty_draw_pane(struct tty *tty, const struct tty_ctx *ctx, u_int py)
 	log_debug("%s: %s %u %d", __func__, tty->client->name, py, ctx->bigger);
 
 	if (!ctx->bigger) {
-		tty_draw_line(tty, wp, s, 0, py, nx, ctx->xoff, ctx->yoff);
+		tty_draw_line(tty, wp, s, 0, py, nx, ctx->xoff, ctx->yoff + py);
 		return;
 	}
 	if (tty_clamp_line(tty, ctx, 0, py, nx, &i, &x, &rx, &ry))

**Comment by asan13** [comment]
Yes, it looks like it helped. Thank you!

**Comment by nicm** [comment]
Great, applied now, thanks!
