### ISSUE TITLE
tmux crash in normal use at grid.c:421

### ISSUE THREAD

**Issue by smithp1** [tmux/tmux#1457]
See https://bugzilla.redhat.com/show_bug.cgi?id=1615933
for original report details.

Description of problem:
tmux crash in normal use

Version-Release number of selected component (if applicable):
tmux-2.7-1.fc28.x86_64

Fedora release 28 (Twenty Eight)
Linux 4.17.9-200.fc28.x86_64 #1 SMP Mon Jul 23 21:41:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

.tmux.conf is:

set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix
set-option -g status-bg yellow
set -g default-terminal "screen-256color"
set-window-option -g xterm-keys on
run-shell ~/workdirs/tmux-resurrect/resurrect.tmux

I believe TERM was:
xterm-256color

How reproducible:
occasional (twice now)

Steps to Reproduce:
1. open xfce4-terminal
2. tmux -2 attach
3. open multiple tabs, multiple edit vim/emacs sessions
4. resize terminal

Actual results:
tmux crash with coredump
 grid_get_cell1 (gl=0x55b77ca4ced0, px=px@entry=0, gc=gc@entry=0x7ffcdc16cc00) at grid.c:421

Expected results:
no crash

Additional info:
backtrace attached to bugzilla report above, summary below:

#0  grid_get_cell1 (gl=0x55b77ca4ced0, px=px@entry=0, gc=gc@entry=0x7ffcdc16cc00) at grid.c:421
#1  0x000055b77ae98146 in grid_reflow_join (target=target@entry=0x55b77cabe560, 
    gd=gd@entry=0x55b77c85c260, sx=sx@entry=25, yy=yy@entry=11, width=1, cy=0x7ffcdc16ccdc, 
    already=0) at grid.c:1031
#2  0x000055b77ae98ee9 in grid_reflow (gd=0x55b77c85c260, sx=25, cursor=cursor@entry=0x55b77c883364)
    at grid.c:1239
#3  0x000055b77aeaf360 in screen_reflow (new_x=<optimized out>, s=0x55b77c883348) at screen.c:472
#4  screen_resize (s=s@entry=0x55b77c883348, sx=<optimized out>, sx@entry=25, sy=<optimized out>, 
    sy@entry=10, reflow=<optimized out>) at screen.c:206
#5  0x000055b77aed0049 in window_pane_resize (wp=wp@entry=0x55b77c8831f0, sx=25, sy=10)
    at window.c:1070
#6  0x000055b77aea1b31 in layout_fix_panes (w=w@entry=0x55b77c876830, wsx=wsx@entry=173, 
    wsy=wsy@entry=42) at layout.c:284
#7  0x000055b77aea1f78 in layout_resize (w=w@entry=0x55b77c876830, sx=sx@entry=173, sy=sy@entry=42)
    at layout.c:517
#8  0x000055b77aea9c1c in recalculate_sizes () at resize.c:149
#9  0x000055b77aeb04a3 in server_client_dispatch (imsg=0x7ffcdc16ee50, arg=0x55b77ca175e0)
    at server-client.c:1487
#10 0x000055b77aea9161 in proc_event_cb (fd=<optimized out>, events=<optimized out>, 
    arg=0x55b77ca95360) at proc.c:92
...

**Comment by nicm** [comment]
Does this still happen if you build from master?

**Comment by smithp1** [comment]
Working on that ... the crash is very infrequent but seems to have something to do with resizing. For now this is all I have but will add more if/when there is another.

**Comment by nicm** [comment]
Looks like it might be ba31d3a88c8c76ec3c76d9a91373fa24e64797cd.

**Comment by nicm** [comment]
Please comment again if you can reproduce with master and I shall reopen.
