### ISSUE TITLE
zoomed pane in copy mode when scrolling briefly flashes layout-grid of unzoomed window

### ISSUE THREAD

**Issue by frosencrantz** [tmux/tmux#1458]
On linux with tmux built from head of github master

When scrolling a zoomed pane in copy mode, I see the layout grid for the non-zoomed window briefly flash.
So when a line scrolls on/off the screen, there is a brief flash of the unzoomed frames of the other panes in the window.

There were similar problems fixed over the pass week related to zoomed panes, but there seems to be  at least one unfixed bug.

**Comment by nicm** [comment]
Works OK for me, you will need to give more information.

**Comment by frosencrantz** [comment]
Let me get more details, which will take a little time.  Before that, here is something more descriptive. It happens when scrolling with a mouse wheel.  I can get it to happen also when scrolling from the keyboard, but it only seems to happen with repeated scrolling, so keeping the key  pressed allowing it to happen repeatedly.

**Comment by frosencrantz** [comment]
Here are the commands:
tmux -vv -Ltest -f/dev/null new
tmux split-pane -v
tmux split-pane -h
tmux select-layout "b069,212x55,0,0[212x27,0,0,0,212x27,0,28{106x27,0,28,1,105x27,107,28,2}]"
tmux select-pane -t 1
tmux resize-pane -Z


Once in zoomed mode, I build up an offscreen buffer that is more than 30 lines by just hitting return at my prompt.  I scroll to the very top of the buffer and then scroll down to the bottom of the buffer by pressing and holding the j key, at some point during the scroll, I get brief flash of horizontal line across.  If I scroll slowly it doesn't happen.

**Comment by avih** [comment]
Seems I can semi reproduce it in vim.:

- Have several panes, vim with some content in it in one pane (have in `~/.vimrc`: `set mouse=a` and `set ttymouse=xterm2` to get all mouse events), and then zoom the vim pane.
- Starting to select content in vim with the mouse
- while keeping the mouse button down, move the mouse around the screen quickly (such that it updates the vim selection quickly).

For me, this result in periodical (typically more than once every 5 seconds) brief flashes of (some parts of) the unzoomed pane borders showing up.

It looks to me like it starts to draw the unzoomed borders, and then aborts mid-way and then renders the correct zoomed content.

**Comment by avih** [comment]
As far as I can tell, this patch fixes this issue for me:
```diff
diff --git a/screen-redraw.c b/screen-redraw.c
index 1f51e743..e6a1a90b 100644
--- a/screen-redraw.c
+++ b/screen-redraw.c
@@ -440,7 +440,8 @@ screen_redraw_screen(struct client *c)
        if (flags & (CLIENT_REDRAWWINDOW|CLIENT_REDRAWBORDERS)) {
                if (ctx.pane_status != CELL_STATUS_OFF)
                        screen_redraw_draw_pane_status(&ctx);
-               screen_redraw_draw_borders(&ctx);
+               if (~c->session->curw->window->flags & WINDOW_ZOOMED)
+                       screen_redraw_draw_borders(&ctx);
        }
        if (flags & CLIENT_REDRAWWINDOW)
                screen_redraw_draw_panes(&ctx);

```

**Comment by nicm** [comment]
Ah yes you are right, this is the same sort of thing, but I think we should restore the window_pane_visible checks. Please try this instead: [x.diff.txt](https://github.com/tmux/tmux/files/2370857/x.diff.txt)

**Comment by avih** [comment]
> Please try this instead: x.diff.txt

Your patch also seems to work.

However, I added some logging where my patch touched, and `flags & CLIENT_REDRAWBORDERS` is true (while zoomed). It's not being actually drawn, but I think it's not nice to have incorrect flag bits set and then ignoring them later under some conditions.

**Comment by nicm** [comment]
No the flag is OK, it just means redraw any borders that are visible. It so
happens that the only way they are invisible is zoom at the moment, but it
didn't used to be like that.

**Comment by avih** [comment]
> redraw any borders that are visible

Hmm.. delicate semantics. Is it mentioned anywhere? :)

**Comment by avih** [comment]
Actually, I think your approach is better, because:
- It uses less control variables (only visibility), and probably more generic.
- It doesn't  try to draw invisible panes in `screen_redraw_draw_panes`.

**Comment by nicm** [comment]
No but all the redraw flags are set from anywhere to tell the server
loop/screen redraw code what to redraw, it is up to that code to decide how
to do that or even not to do it at all.

**Comment by nicm** [comment]
Applied now, please let me know if you continue to see issues.
