### ISSUE TITLE
Allow one line panes

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#1459]
Linux x86_64
tmux 2.2
xterm-256color

panes must have a minimum of 2 lines, can this be relaxed so "resize-pane -t 1 -y 1" works?

**Comment by nicm** [comment]
Scroll regions need to be at least two lines in height. In theory we could just redraw the whole pane to allow one line panes, I'll add it to the TODO file.

**Comment by nkh** [comment]
Great!

I want to use it as a status line for something running in another pane. 2 lines minimum plus the separation line (can that one be removed in some way already?). I have 2 of those status lines so  lines are used, I need a bigger screen! :)
