### ISSUE TITLE
Nested sessions allowed?

### ISSUE THREAD

**Issue by rkoch** [tmux/tmux#146]
I just installed v2.1 on Mac OS X 10.10, iTerm 2 via homebrew.

On v2.0 it was not possible to create nested sessions:
```
$ tmux
sessions should be nested with care, unset $TMUX to force
```

Now on v2.1, this seems to have changed and nested sessions are possible by default, although it wasn't mentioned in the release notes. Is this expected or a bug?

Thanks for clarifying.

**Comment by nicm** [comment]
Works for me, does it work if you do:

tmux -f/dev/null -Ltest sh -c 'tmux -Ltest new; sleep 1000'

**Comment by rkoch** [comment]
Sorry, didn't have the time to test it until now.

It works fine when I run the command above without the `sh`. Could this be something with my configs?

**Comment by nicm** [comment]
But does exactly what I said work?

**Comment by rkoch** [comment]
In that case not:

```sh
$ tmux -f/dev/null -Ltest sh -c 'tmux -Ltest new; sleep 1000'
ambiguous command: sh, could be: show-buffer, show-environment, show-messages, show-options, show-window-options
```

**Comment by nicm** [comment]
OOps, sorry it should be:

tmux -f/dev/null -Ltest new sh -c 'tmux -Ltest new; sleep 1000'

**Comment by rkoch** [comment]
Okay this works!

A new tmux session is started and the usual `sessions should be nested with care, unset $TMUX to force` message is printed on the screen.

**Comment by nicm** [comment]
What if you just do this:

tmux -f/dev/null -Ltest new

Then try "tmux -Ltest new" yourself inside that tmux. Does it work?

**Comment by rkoch** [comment]
This works as well:

Inside the new tmux session:
```sh
$ tmux -Ltest new
sessions should be nested with care, unset $TMUX to force
```

**Comment by nicm** [comment]
Ok so it is probably your config somehow. Does it still not work with
your full config? What is in your .tmux.conf?

**Comment by rkoch** [comment]
Hm that's soo weird - now it works! My system was probably in a weird state before..

Anyway thanks for your help & sorry for the false alarm :)
