### ISSUE TITLE
Terminal.app proxy icon in tmux with TERM="tmux-256color"

### ISSUE THREAD

**Issue by CallumHoward** [tmux/tmux#1462]
Problem: 
I'm trying to get [proxy icons](https://alerante.net/features/vim-title/) working in the macOS Terminal.app within tmux. It works with `TERM="screen-256color"` from within tmux using [this script](https://github.com/dmmalam/dotty/blob/0a1fdc0e9e8d3ff4227b7d82a73ceb600413292a/bin/set-title) (and there is also [this one](https://github.com/sorin-ionescu/prezto/blob/master/modules/terminal/init.zsh#L91-L117) which doesn't seem to work).

That's great, however I use `TERM="tmux-256color"` so I can have italics in nvim, and with this set, it does not work. So my question is, __how can I get proxy icons working in tmux with `TERM="tmux-256color"` (or some terminfo supporting italics)?__

I installed [this](https://github.com/CallumHoward/dotfiles/blob/master/tmux-256color.ti) terminfo file with `tic tmux-256color.ti` and it is compiled in this structure:
```
~/.terminfo
└── 74
   ├── tmux
   └── tmux-256color
```
I also tried installing the tmux-256color terminfo from the tmux repo [here](https://github.com/tmux/tmux/files/1725937/tmux-256color.terminfo.txt) (again, using `tic tmux-256color.terminfo`).

Platform: macOS 10.13.5, Terminal.app 2.8.2
Config:
```shell
# allow dynamic cursor and italics in vim
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
```
TERM: tmux-256color inside tmux, xterm-256color outside of tmux

**Comment by nicm** [comment]
You need to change the script to check for tmux* as well as screen*...

**Comment by CallumHoward** [comment]
Oh, yes that was it, I should have seen that. Thanks!
