### ISSUE TITLE
Cycling between panes

### ISSUE THREAD

**Issue by karakays** [tmux/tmux#1463]
Is there a way to map key binding for pane cycling to another mapping?
It's mapped to `<prefix> o`, by default - how can I override that in .tmux.conf?
I am aware of `last-pane` command, but it doesn't help if there are more than two panes. Is there a similar command that I can use in .tmux.conf to cycle between panes?

**Comment by ThomasAdam** [comment]
Same way you would for any other command:

```
bind-key ... select-pane -t :.+
```
