### ISSUE TITLE
feature discussion? allow pane to continue to execute and buffer when browsing its history in copy-mode

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#1467]
Hi, I find that sometimes I have a long running script which I neglected to redirect to a logfile, and whenever I peruse its intermediate output (in copy mode), new output would cause the streams to block. 

It would be super duper cool if there was a special option we could trigger for a pane to allow it to continue to execute with the output hidden and continuing to append. That way we could freely browse earlier output without worry. 

There may be implications based on the history limit being hit. Maybe then we could start to block the streams.

**Comment by nicm** [comment]
Added to TODO list.
