### ISSUE TITLE
tmux --help should do something

### ISSUE THREAD

**Issue by ggascoigne** [tmux/tmux#1468]
Help for tmux is hard to find, if you already know that `tmux list-commands` lists the possible command line options then you are already ahead of the curve.

It would be nice if there was a standard help option that was obvious and easy to find that guides users somewhat.

--

FYI:

$ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.7
xterm-256color

**Comment by nicm** [comment]
The standard help option is "man tmux"...
