### ISSUE TITLE
2.1 set mouse to `copy-selection -x`.

### ISSUE THREAD

**Issue by NHDaly** [tmux/tmux#147]
Hi, I cannot seem to get the `copy-selection -x` command to work for overriding the mouse's exit-copy-mode-on-selection behavior.

I tried this, but it wasn't able to change the behavior of click-drag selecting some text:

```
bind -n -tvi-copy  MouseUp1Pane copy-selection -x
bind -n -tvi-copy MouseDrag1Pane copy-selection -x
```

Just to be sure, i tried setting these to a different command:
```
bind -n -tvi-copy  MouseUp1Pane scroll-up
bind -n -tvi-copy MouseDrag1Pane scroll-up
```
and click-drag-release *still* performs the same behavior: copy and exit copy-mode. Simply clicking without dragging will do execute the `scroll-up`.

So I think there is a problem with not being able to override the MouseDrag1Pane inputs.

**Comment by nicm** [comment]
Bindings in vi-copy and emacs-copy only work inside copy mode, you need to bind the keys outside copy mode. But there is no way to do what you want.
