### ISSUE TITLE
Static build fails in Linux platform [Arch Linux]

### ISSUE THREAD

**Issue by fr0xk** [tmux/tmux#1470]
While playing around source code, I tried to build "tmux" as a standalone binary which I did in past a couple of times. I am not sure if it is a distro specific issue.
I used the latest tarball provided in the wiki page, the build report is [here](http://0x0.st/swZN.build
)

**Comment by fr0xk** [comment]
However, no problem with shared library builds

**Comment by nicm** [comment]
Looks like you are missing static libevent and ncurses...

**Comment by fr0xk** [comment]
Oops, looks like distro specific issue...
Arch Linux does not ship many static libraries.

**Comment by fr0xk** [comment]
Issue can be closed now
