### ISSUE TITLE
Mouse events ignore zoom mode (after 2.8)

### ISSUE THREAD

**Issue by avih** [tmux/tmux#1471]
Steps to reproduce:

1. Build latest tmux (8598fd1b)
2. Set `./tmp.conf` to have only one line - enable the mouse: `set-option -g mouse on`
3.  run `tmux -f ./tmp.conf -2 new-session -A -s main`
4. Split left-right (`C-b %`).
5. Select (click) the _right_ pane with the mouse.
6. Zoom it (`C-b z`)
7. Select text with the mouse at the _left_ half of the terminal (e.g. the prompt).

Expected result:
- The text on screen is being selected.

Actual result:
- tmux goes out of zoom mode and selects at the left pane.

This also happens if the right pane has an application running which handles mouse events - like vim. Once the right pane is zoomed, any mouse events at the left half of the terminal (where the unzoomed left pane would be) triggers exiting zoom mode.

FWIW, mouse events at the right half while zoomed (like selection at the end of some line in vim) works as expected - selects the text under the mouse pointer and doesn't exit zoom mode.

**Comment by nicm** [comment]
This should be fixed by a618271e1287c90653cdda4442868c2d4e94de49 and 5aa435a9f04fd6e4bab6f564b8af7fe2e8c7719c.

**Comment by avih** [comment]
Confirmed fixed. Thanks.

I'll open another issue on a possibly related issue (which exists also in 2.8) where mouse events are ignored in zoom mode over chars which, when unzoomed, are part of top-bottom split-lines.
