### ISSUE TITLE
Zoom Mode Changed for Synchronized Panes

### ISSUE THREAD

**Issue by aauren** [tmux/tmux#1472]
I noticed that recently, when I zoom a pane while I have the synchronize-pane window option enabled that it still causes keyboard input to be sent to the un-zoomed panes. This is a change in functionality from what tmux used to have. Previously, even though panes were synchronized, if I zoomed a pane, it caused the synchronization to stop until the pane was un-zoomed and then it would put it back to synchronized.

I'm not sure if this is a bug, or if this is a change in design for tmux that is intended. But, for what it's worth, the previous functionality felt more natural as it means that I'm not typing in panes that I cannot see. And I used to use the zoom pane functionality, many times as a quick way to break synchronization for a specific pane.

I usually build off of master and run it for a couple of months, so I'm not entirely sure when it changed. All I can say, is that my previous build of tmux which had the previous functionality was built from master about 2 - 3 months ago, and the current one that I'm testing with was built from master on 9/4.

For the time being, I've put together a work-around for my synchronize pane shortcut that works ok, although it doesn't take into account whether the pane was previously synchronized before the zoom.
```
bind z resize-pane -Z\; if-shell -F "#{window_zoomed_flag}" "set-window-option synchronize-panes off" "set-window-option synchronize-panes on"
```

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/2364554/x.diff.txt)

**Comment by nicm** [comment]
Great, applied, thanks.
