### ISSUE TITLE
2.8 missing from release page and wiki

### ISSUE THREAD

**Issue by craigbarnes** [tmux/tmux#1474]
It seems like `2.8` has been tagged and is mentioned in the `CHANGES` file, but the [wiki] still suggests downloading `2.7` and the GitHub [releases] page only lists `2.8-rc`. Is `2.8` still in rc or is it a final release...?

[wiki]: https://github.com/tmux/tmux/wiki
[releases]: https://github.com/tmux/tmux/releases

**Comment by craigbarnes** [comment]
Oh, fair enough. I just thought whilst reading:

> CHANGES FROM 2.8 to master
> ...
> CHANGES FROM 2.7 to 2.8

...that it seemed like it had been released.

**Comment by nicm** [comment]
Right it needs to read "2.7 to 2.8" eventually and there is no sense in going around changing loads of places from "2.8-rc" to "2.8" so might as well change it for 2.8-rc.

**Comment by craigbarnes** [comment]
Ok, understood. Sorry for the noise.
