### ISSUE TITLE
the shell started by tmux does not match user's login shell

### ISSUE THREAD

**Issue by HouzuoGuo** [tmux/tmux#1476]
The host is Linux Subsystem For Linux running the latest stable Debian distribution. Tmux version is 2.3.

According to getent, user's login shell is fish:

   > getent passwd $USER
   howard:x:1000:1000:,,,:/home/howard:/usr/bin/fish

Which also matches environment variable's definition:

<pre>
ConEmuBuild=180626
ConEmuPID=27272
EDITOR=vim
GOPATH=/home/howard/gopath
GOROOT=/home/howard/go
HOME=/home/howard
HOSTTYPE=x86_64
LANG=en_US.UTF-8
LOGNAME=howard
NAME=howard-dot-gg-xmg-laptop
PAGER=less
PATH=/home/howard/gopath/bin:/home/howard/go/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
PS1=\u@\h \w \$
PS2=>
PWD=/mnt/c/Users/guoho
SHELL=/usr/bin/fish
SHLVL=4
TERM=xterm-256color
USER=howard
XDG_DATA_DIRS=/home/howard/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
</pre>

Unfortunately, tmux spawns bash instead of fish for every new window and panel:

<pre>
 howard@howard-dot-gg-xmg-laptop /mnt/c/Users/guoho $ env
HOSTTYPE=x86_64
LANG=en_US.UTF-8
EDITOR=vim
USER=howard
PAGER=less
GOPATH=/home/howard/gopath
PWD=/mnt/c/Users/guoho
HOME=/home/howard
GOROOT=/home/howard/go
NAME=howard-dot-gg-xmg-laptop
TMUX=/tmp/tmux-1000/default,13362,11
XDG_DATA_DIRS=/home/howard/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
TERM=xterm-256color
SHELL=/bin/bash
TMUX_PANE=%11
SHLVL=4
LOGNAME=howard
ConEmuBuild=180626
PATH=/home/howard/go/bin:/home/howard/gopath/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
ConEmuPID=28816
PS1=\u@\h \w \$
PS2=>
_=/usr/bin/env
howard@howard-dot-gg-xmg-laptop /mnt/c/Users/guoho $ ps
  PID TTY          TIME CMD
13990 pts/2    00:00:00 bash
14003 pts/2    00:00:00 ps
howard@howard-dot-gg-xmg-laptop /mnt/c/Users/guoho $
</pre>

There is no `~/.tmux.conf`. Here's the verbose output log file: https://clbin.com/MlY0G

**Comment by HouzuoGuo** [comment]
Identical behaviour was also observed on an office workstation running Ubuntu 18.04, i.e. tmux 2.6.

**Comment by nicm** [comment]
Are you sure you restarted tmux completely after you changed your shell?

**Comment by HouzuoGuo** [comment]
Both the laptop and office computers have rebooted many times since the shell was changed from bash to fish.

**Comment by nicm** [comment]
What does this show:

tmux -Ltest -f/dev/null start\; show -g default-shell

**Comment by krader1961** [comment]
FWIW, I use fish with tmux on macOS without problems. And nicm's command outputs `default-shell "/usr/local/bin/fish"` for me. Note that your tmux log file shows fish being spawned and doesn't have a single mention of bash.

**Comment by nicm** [comment]
Oh I didn't see the log at all, yes it appears that tmux is correctly running fish.

**Comment by HouzuoGuo** [comment]
It appears that ConEmu somehow persuaded tmux into believing that user's shell is bash, other terminal emulators don't have this problem. I'll take it to ConEmu.
