### ISSUE TITLE
Setting '-g prefix C-a' breaks window cycling with n/p

### ISSUE THREAD

**Issue by martopoulos** [tmux/tmux#1478]
I'm using C-a as my prefix (see my tmux.conf below), which seems to break window cycling with C-a n and C-a p.  C-a p sometimes works, but C-a n never does.  Only C-a [i]  functions consistently.  I've confirmed this behavior in both tmux 2.7 and 1.9 on Debian stretch and jessie, respectively.

My ~/.tmux.conf has the following lines:

unbind C-b
set -g prefix C-a
bind a send-prefix

**Comment by nicm** [comment]
Are you sure you aren't pressing C-a C-n?

**Comment by chros73** [comment]
It always worked here since v1.8 on Ubuntu 14.04 (now I'm using v2.7).

**Comment by martopoulos** [comment]
I'm sure I'm not pressing C-a C-n.  When I remove my ~/.tmux.conf, C-b n and C-b p cycle through the windows as expected...

**Comment by nicm** [comment]
Show tmux logs and full config please.

**Comment by martopoulos** [comment]
@nicm I posted my full config in the OP, but how do I show logs...?

**Comment by tessus** [comment]
@martopoulos start tmux with `tmux -vvv` and  attach the log file here.

**Comment by martopoulos** [comment]
[tmux-client-2613.log](https://github.com/tmux/tmux/files/2386092/tmux-client-2613.log)
[tmux-out-2615.log](https://github.com/tmux/tmux/files/2386093/tmux-out-2615.log)
[tmux-server-2615.log](https://github.com/tmux/tmux/files/2386094/tmux-server-2615.log)
Ah, cool.  Done.

**Comment by nicm** [comment]
Every time you press C-a n or C-a p it appears to be working:

1537045737.320641 /dev/pts/1: keys are 1 (\001)
1537045737.470507 /dev/pts/1: keys are 1 (n)
1537045737.470614 cmdq_next <0x55d2c8178f10>: command[next-window] (0), flags 0

Sometimes you are pressing C-a C-n though:

1537045737.920829 /dev/pts/1: keys are 1 (\001)
1537045738.048147 /dev/pts/1: keys are 1 (\016)

Or C-a C-p:

1537045732.992872 /dev/pts/1: keys are 1 (\001)
1537045733.120656 /dev/pts/1: keys are 1 (\020)

These won't work.

**Comment by martopoulos** [comment]
Looks like I flub it sometimes when I'm typing rapidly.  Apparently, the C-a C-n/p combinations also work in 'screen' so I never noticed/was affected my sloppiness.  Thanks for breaking it down for me.
