### ISSUE TITLE
Issue with numeric pad

### ISSUE THREAD

**Issue by smutel** [tmux/tmux#1479]
_TMUX version_
```
2.7
```
_UNAME_
```
Linux x86_64
```
_TERM_
```
xterm-256color
```
_Issue description_
```
Char / * - + does not work from the numeric pad
Don't have this issue with terminal
```

**Comment by nicm** [comment]
Works for me.

**Comment by lwpeters** [comment]
I've got the same issue. Is there any troubleshooting you can recommend?

xterm-256color

Distro: CentOS 6.4

TMUX version: 2.9a

**Comment by thlor** [comment]
Same issue.

tmux version 2.6
Ubuntu 18.04.3 LTS
