### ISSUE TITLE
tmux resize-pane doesn't resize to PANE_MINIMUM

### ISSUE THREAD

**Issue by nmeum** [tmux/tmux#1480]
The minimum pane size is defined in `tmux.h` as follows:

```C
/*
 * Minimum layout cell size, NOT including separator line. The scroll region
 * cannot be one line in height so this must be at least two.
 */
#define PANE_MINIMUM 2
```

Creating a new pane with this minimum pane size using `tmux split-window -l 2` is possible and works as expected. Unfortunately, resizing an existing pane created using `tmux split-window` to the minimum pane size with `tmux resize-pane -y 2` does not work as expected. The `tmux resize-pane` command only seems to be able to resize an existing pane to a size of 3 lines.

I can reproduce this with `tmux 2.7` and Git HEAD `2.8-66-g71d2ab18` (using the default configuration and urxvt (`TERM=rxvt-unicode-256color`) on Alpine Linux. In `tmux 1.9` on Debian Jessie both `resize-pane` and `split-window` work as expected with the default configuration.

Is this intended or do you consider this a bug?

**Comment by nicm** [comment]
Not intentional. Funny that -x works though.

**Comment by nmeum** [comment]
I am also wondering if the comment above the `PANE_MINIMUM` macro is actually correct. I don't know much about the tmux internals but is it really necessary for the scrollbar to be at least two lines in height? At least with my configuration it only takes up one line in height.

**Comment by nicm** [comment]
Terminal scroll region cannot be one line. We do support terminals without
scroll region now however so it would be possible to have one line panes
and use the same method (redraw instead of scrolling).

**Comment by nmeum** [comment]
> [ …] so it would be possible to have one line panes and use the same method […]

That would be nice, I personally have a use-case for using tmux with panes which are one line in height.

---

I also investigated the original issue further, the bad behavior was introduced in 2.3.  To be more specific commit f8cc48a43f1fd5fe082fde86b429c2cda5bcf1b0 seems to have introduced this issue.

To be even more specific the following statement added to the `layout_resize_check` function seems to be the issue:

```C
minimum += layout_need_status(lc,
  options_get_number(w->options,
  "pane-border-status") == 1);
```

Commenting out this statement makes `tmux resize-pane -y 2` work as expected again (even on the master branch).

As stated above I don't know enough about the tmux internals to figure out why and if it is necessary to increase the minimum pane height when a border-status is enabled but since this is wrapped in a layout-check-if-statement this might also explain why `-x` works as expected.

**Comment by nicm** [comment]
Yes you are right, try this please: [x.diff.txt](https://github.com/tmux/tmux/files/2411389/x.diff.txt)

**Comment by nmeum** [comment]
Your patch works for me. Meaning `tmux resize-pane -y 2`works as expected now.

**Comment by nicm** [comment]
Great - applied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by nmeum** [comment]
Thanks!

> We do support terminals without scroll region now however so it would be possible to have one line panes and use the same method (redraw instead of scrolling).

Is there any chance that this will be implemented in the future as well?

**Comment by nicm** [comment]
> Is there any chance that this will be implemented in the future as well?

Maybe, it is just a matter of checking if the pane size is 1 and redrawing instead of scrolling in tty.c.

**Comment by nmeum** [comment]
I came up with the following:

```patch
diff --git a/tmux.h b/tmux.h
index 4ae6d6ad..9660da2b 100644
--- a/tmux.h
+++ b/tmux.h
@@ -64,10 +64,10 @@ struct tmuxproc;
 #endif
 
 /*
- * Minimum layout cell size, NOT including separator line. The scroll region
- * cannot be one line in height so this must be at least two.
+ * Minimum lyaout cell size, NOT including separator line. A scroll region
+ * cannot be one line in height thus it is disabled for panes of this size.
  */
-#define PANE_MINIMUM 2
+#define PANE_MINIMUM 1
 
 /* Minimum and maximum window size. */
 #define WINDOW_MINIMUM PANE_MINIMUM
diff --git a/tty.c b/tty.c
index f3cbbf23..0d3a8982 100644
--- a/tty.c
+++ b/tty.c
@@ -1448,7 +1448,8 @@ tty_cmd_insertline(struct tty *tty, const struct tty_ctx *ctx)
 	    !tty_pane_full_width(tty, ctx) ||
 	    tty_fake_bce(tty, ctx->wp, ctx->bg) ||
 	    !tty_term_has(tty->term, TTYC_CSR) ||
-	    !tty_term_has(tty->term, TTYC_IL1)) {
+	    !tty_term_has(tty->term, TTYC_IL1) ||
+	    ctx->wp->sy == 1) {
 		tty_redraw_region(tty, ctx);
 		return;
 	}
@@ -1470,7 +1471,8 @@ tty_cmd_deleteline(struct tty *tty, const struct tty_ctx *ctx)
 	    !tty_pane_full_width(tty, ctx) ||
 	    tty_fake_bce(tty, ctx->wp, ctx->bg) ||
 	    !tty_term_has(tty->term, TTYC_CSR) ||
-	    !tty_term_has(tty->term, TTYC_DL1)) {
+	    !tty_term_has(tty->term, TTYC_DL1) ||
+	    ctx->wp->sy == 1) {
 		tty_redraw_region(tty, ctx);
 		return;
 	}
@@ -1531,7 +1533,8 @@ tty_cmd_reverseindex(struct tty *tty, const struct tty_ctx *ctx)
 	    !tty_pane_full_width(tty, ctx) ||
 	    tty_fake_bce(tty, wp, 8) ||
 	    !tty_term_has(tty->term, TTYC_CSR) ||
-	    !tty_term_has(tty->term, TTYC_RI)) {
+	    !tty_term_has(tty->term, TTYC_RI) ||
+	    ctx->wp->sy == 1) {
 		tty_redraw_region(tty, ctx);
 		return;
 	}
@@ -1556,7 +1559,8 @@ tty_cmd_linefeed(struct tty *tty, const struct tty_ctx *ctx)
 	if (ctx->bigger ||
 	    (!tty_pane_full_width(tty, ctx) && !tty_use_margin(tty)) ||
 	    tty_fake_bce(tty, wp, 8) ||
-	    !tty_term_has(tty->term, TTYC_CSR)) {
+	    !tty_term_has(tty->term, TTYC_CSR) ||
+	    ctx->wp->sy == 1) {
 		tty_redraw_region(tty, ctx);
 		return;
 	}
@@ -1593,7 +1597,8 @@ tty_cmd_scrollup(struct tty *tty, const struct tty_ctx *ctx)
 	if (ctx->bigger ||
 	    (!tty_pane_full_width(tty, ctx) && !tty_use_margin(tty)) ||
 	    tty_fake_bce(tty, wp, 8) ||
-	    !tty_term_has(tty->term, TTYC_CSR)) {
+	    !tty_term_has(tty->term, TTYC_CSR) ||
+	    wp->sy == 1) {
 		tty_redraw_region(tty, ctx);
 		return;
 	}
diff --git a/window-copy.c b/window-copy.c
index 383f2c4e..78e6aa9a 100644
--- a/window-copy.c
+++ b/window-copy.c
@@ -1299,7 +1299,8 @@ window_copy_write_line(struct window_pane *wp, struct screen_write_ctx *ctx,
 	style_apply(&gc, oo, "mode-style");
 	gc.flags |= GRID_FLAG_NOPALETTE;
 
-	if (py == 0) {
+	/* scroll region cannot be one line */
+	if (py == 0 && s->rupper < s->rlower) {
 		if (data->searchmark == NULL) {
 			size = xsnprintf(hdr, sizeof hdr,
 			    "[%u/%u]", data->oy, screen_hsize(data->backing));
```

Which seems to work, the only problem being that the cursor position seems a bit strange when scrolling up.

**Comment by nicm** [comment]
Looks good can you upload it as a file please or open a PR, whichever you
like.
