### ISSUE TITLE
Right cropped pane in alternate screen mode overwrites left pane

### ISSUE THREAD

**Issue by frosencrantz** [tmux/tmux#1481]
I have window-size set to largest, and create a window with a horizontal split, so there are two panes, 
 left&right.

I then connect to the window from a client that is narrower than the window, but wider than either pane.
Position the client's view of the window such that the right-most part of the right window is not visible.  In the right pane run a program (e.g. htop, vim) that puts the pane in the alternate screen mode.  The rightmost output from the right pane is now displaying over the left edge of the left pane in this client (one line down). Connect from a client that is as large as the window at the same time, there will be no issue in that larger client.

The output of the alternate screen is not being truncated on the right.

I'm using the latest version of master.
 
(Also the other earlier issue I reported with the brief flash has been fixed. Thank you!)

**Comment by frosencrantz** [comment]
This is from the version of master.

**Comment by nicm** [comment]
Logs?

**Comment by nicm** [comment]
Never mind, I see it, it has to be exactly the right size.

**Comment by nicm** [comment]
RHS trim calculation is not right, try this please: [xyz.diff.txt](https://github.com/tmux/tmux/files/2405358/xyz.diff.txt)

**Comment by frosencrantz** [comment]
Doesn't help. Still seeing the overwrites.

**Comment by nicm** [comment]
Logs then please.

**Comment by frosencrantz** [comment]
Sorry no logs yet.  This is still an issue.

One additional observation, is that it doesn't show everything, but if there is a string of text being shown of one color, tmux is cropping after the end of the text in that color.  So there might be an issue with the code that displays text in a non-default color.

**Comment by frosencrantz** [comment]
Simple test case:
```
$ tmux list-clients
/dev/pts/15: 0 [110x11 screen-256color] (utf8)
/dev/pts/12: 0 [161x11 screen-256color] (utf8)
$ tmux list-panes
0: [67x10] [history 51/2000, 14647 bytes] %0
1: [93x10] [history 1827/2000, 790281 bytes] %1 (active)
# from the right screen run this command;
# the sleeps give tmux a chance to change the offset of the screen in the cropped client
# also after the final sleep, on my screen it cleans things.
sleep 1 ; tput cup 1 1 ; tput bold ; echo the quick brown fox jumped over the lazy dog. And then the dog woke up and ran after the fox.  ; sleep 10       
```

**Comment by nicm** [comment]
This looks fine to me.

**Comment by frosencrantz** [comment]
You still need the setup from the initial  comment, and then with the window and pane sizes in the last comment.

**Comment by frosencrantz** [comment]
atttached logs.
[issue-1481.tar.gz](https://github.com/tmux/tmux/files/2428904/foo.tar.gz)

**Comment by nicm** [comment]
Aha, I think this is it: [Uploading x.diff.txt…]()
~~~~
diff --git a/tty.c b/tty.c
index 510a442a..86f0d722 100644
--- a/tty.c
+++ b/tty.c
@@ -1739,7 +1739,8 @@ tty_cmd_cells(struct tty *tty, const struct tty_ctx *ctx)
 		return;
 
 	if (ctx->bigger &&
-	    (ctx->ocx < ctx->ox || ctx->ocx + ctx->num > ctx->ox + ctx->sx)) {
+	    (ctx->xoff + ctx->ocx < ctx->ox ||
+	    ctx->xoff + ctx->ocx + ctx->num > ctx->ox + ctx->sx)) {
 		if (!ctx->wrapped ||
 		    !tty_pane_full_width(tty, ctx) ||
 		    (tty->term->flags & TERM_EARLYWRAP) ||

**Comment by frosencrantz** [comment]
Yes, that fixed it. Thank you.

Any ideas on why the the simple test case didn't work?

**Comment by nicm** [comment]
No... it showed up a different problem for me though. I guess it was hitting the redraw case already...

**Comment by nicm** [comment]
Applied now, thanks!
