### ISSUE TITLE
No visual indicators that a client is cropping a window

### ISSUE THREAD

**Issue by frosencrantz** [tmux/tmux#1483]
This is more a feature request.  When attaching to a window from a different sized client there is a visual indication if the window is smaller than the client, there is a field of dots on the right/bottom edges.
If the window is larger than the client there is no visual indication from tmux.  You might be able to figure out from the panes.

Some possible places to add indicators:

- Edges that are cropped could have a light-grey line along that edge, making it clear that edge of the screen is cropped.
- cropped pane borders could show an arrow (e.g. <>) showing there is more to that edge
- status line and pane status line could get new formats that make it possible to show the screen is cropped.

Without a visual indicator using a large window with a small pane can be perplexing.

**Comment by nicm** [comment]
I do not want to lose space on screen to an indicator. We could add a format and show it in the status line.

**Comment by nicm** [comment]
I added a window flag ("B") showing when a window is bigger than visible.

**Comment by frosencrantz** [comment]
Would it be possible to add something that can be put in the left or right status, like pane_synchronized?
I would like to be able to add a different color indicator in the status bar if the current client is cropping the window.

The window flag is not so useful, what happens is that all the windows listed in the status bar have a B, (or now a '+') , so  each window status is taking more space in the center part of the status bar, and it is not clear to me how I can use that to change the color of the status bar.

**Comment by nicm** [comment]
I added some formats and changed to show offset in status-right for windows that are larger.

**Comment by frosencrantz** [comment]
Good to have a visual indicator.  I can use the window_bigger format to add a color indicator I want.  Thank you, Nicholas!
