### ISSUE TITLE
Iterm's trigger "send text" with tmux sends text two times

### ISSUE THREAD

**Issue by nikit0z** [tmux/tmux#1484]
Hey, 
I'm trying to use tmux together with iterm's "triggers", e.g. when I log in somewhere - trigger "send text" will send my username to the promt. When I use this with tmux the send text happens twice, e.g.

`Username: username1username1`
instead of 
`Username: username1`

Any idea what could cause this? Thanks

Versions:
tmux 2.6
iterm2 3.2.0

**Comment by nicm** [comment]
Show tmux logs please from reproducing.

**Comment by AlexVKO** [comment]
Same here, did you guys figure that our?
