### ISSUE TITLE
Why  does tmux does not yet have mouse support ?

### ISSUE THREAD

**Issue by whatdhack** [tmux/tmux#1486]
It is so much more  effort and time efficient to click mouse  on a screen to work in that.   Currently to do the same requires ctrl-b  q  d   - four key strokes and a  metal load to get the proper d .     

What is so much more difficult about mouse vis-a-vis a keyboard ?

**Comment by whatdhack** [comment]
Not even a single comment on why it was closed ?  Is the problem solved - no.  Is the problem heard - probably not.

**Comment by nicm** [comment]
You are either trolling or almost criminally lazy.

**Comment by whatdhack** [comment]
That  is very cynical view.  Keyboard only support may have been ok couple of decades ago, certainly not now.  I use tmux a lot, and find the lack of support for mouse a  big productivity  hit. Is it technically not possible , or is it something else ?

**Comment by nicm** [comment]
Are you still using tmux 0.7?
