### ISSUE TITLE
How to change tmux `status line` working directory at startup?

### ISSUE THREAD

**Issue by cevhyruz** [tmux/tmux#1488]
I notice when running tmux, it always starts at `/home/user/` directory regardless of the current working directory of shell where tmux started.

I confirmed this by running `pwd` at statusline:
 

    set -g status-right "#(pwd)"

I want to run some shell scripts at the statusline but I don't want to manually handle the changing-directory stuff for all my scripts.

 What I want is for tmux to change directory to where it started/invoked.

 How can I do just that?

**Comment by nicm** [comment]
Try this please which will make #() use the same rules used for new panes as of b9a6162d2f9bea63c3ad421e9c3969eea2852b00: [x.diff.txt](https://github.com/tmux/tmux/files/2416313/x.diff.txt)

**Comment by cevhyruz** [comment]
Tried the tarball but still same results.. running `#(pwd)` confirms that it still in the `/home/user` directory.

**Comment by nicm** [comment]
Are you sure you restarted tmux entirely?

**Comment by cevhyruz** [comment]
Well I tried rebooting my pc to be sure, still the same.. 

What do you mean by `use the same rules used for new panes`?  creating new panes is working alright (starting from working directory where tmux is invoked) but still not the `#(pwd)` command inside tmux status.

I confirmed tarball is installed by `tmux -V` returning `tmux 2.8-rc`.

also I don't have tmux config at home directory, I'm only using the system-wide one at `/etc/tmux.conf`.

**Comment by nicm** [comment]
Please be more specific what you are trying. This works for me with the patch:
~~~~
cd /tmp
tmux kill-server
tmux new
tmux set status-left '#(pwd)'
~~~~~
As you can see:
![xxx](https://user-images.githubusercontent.com/304243/46064057-3b44f500-c166-11e8-9056-03eb38586ca2.png)

**Comment by cevhyruz** [comment]
basically I'm trying to run an executable shell script inside the statusline that displays git stream status if the current working directory is a git repository. 

The script runs fine when called inside the gnome-terminal but not inside the tmux statusline, so I check it by running `pwd` inside the statusline and turns out that the working directory is pointing at `/home/user`

I can't post screenshot right now but trying your snippet didn't change it at all.

**Comment by nicm** [comment]
Are you sure you are running the correct binary after you rebuild?

**Comment by cevhyruz** [comment]
Upon checking again, I really am invoking the wrong binary, sorry for that as I'm new to this kind of stuff :p. I rebuilt it again with your previous diff:  [` b9a6162 `](url): [x.diff.txt](https://github.com/tmux/tmux/files/2416313/x.diff.txt). and now it's working..

Thanks for the time and patience.  Kudos!
