### ISSUE TITLE
`lost server` when creating a new session with `-n`

### ISSUE THREAD

**Issue by nmeum** [tmux/tmux#1489]
tmux git master 7cf00d6b7206bcf75c626551bd2c008c2df2e387 currently crashes when creating a new session with a given window name.

```
$ tmux -vv -Ltest new-session -s mysession -n mywindow
lost server
```

With `tmux 2.7` the session is created as expected.

Logs:

* https://files.8pit.net/tmp/tmux-client-28139.log
* https://files.8pit.net/tmp/tmux-out-28142.log
* https://files.8pit.net/tmp/tmux-server-28142.log

**Comment by nmeum** [comment]
> Does the following fix things?

Yes, it does indeed.

**Comment by nicm** [comment]
I have reverted the change which caused this instead, I didn't really like it when it came to use it.
