### ISSUE TITLE
Feature: bookmark lines in tmux buffer and navigate among these points like Emacs

### ISSUE THREAD

**Issue by hajimezhao** [tmux/tmux#149]
Hi tmux developers,
I am a fan of tmux. My desired feature (show me if existed) is to bookmark lines/locations in tmux buffer, so can I jump among these points like Emacs.
Do we have it now in tmux (not clue in Google)? Or any plan to implement this feature?

Thank you very much!
Cheers,
Khon

**Comment by nicm** [comment]
Try http://pastebin.ca/raw/3207913 please. One mark, set with m and jump to with j.

**Comment by rjungemann** [comment]
@nicm, your link no longer works.
