### ISSUE TITLE
select-pane -m doesn't work at 641191a

### ISSUE THREAD

**Issue by koie** [tmux/tmux#1490]
I'm using select-pane -m.
In current version, selecdt-pane -m doesn't work.
I'd checked three revisions whether select-pane -m works.
* a00cdcdfcbc7 NG (head revision)
* 641191ab2047 NG (it's seems breaking revision)
* bf03197e185b OK (last working revision)

The following patch reverting 641191ab2047 partially fixs this problem in my environ.
```
diff --git a/cmd-select-pane.c b/cmd-select-pane.c
--- a/cmd-select-pane.c
+++ b/cmd-select-pane.c
@@ -119,7 +119,8 @@ cmd_select_pane_exec(struct cmd *self, s
        }

        if (args_has(args, 'm') || args_has(args, 'M')) {
-               if (args_has(args, 'm'))
+               /*if (args_has(args, 'm'))*/
+               if (args_has(args, 'm') && !window_pane_visible(wp))
                        return (CMD_RETURN_NORMAL);
                lastwp = marked_pane.wp;
```

**Comment by nicm** [comment]
Yes, fixed now, thanks.
