### ISSUE TITLE
"bind-key -n S-Left previous-window" doesn't work in 2.7 and master

### ISSUE THREAD

**Issue by qwc** [tmux/tmux#1491]
Hi, 
My keybinding for switching tmux windows or tabs does not work anymore.
tmux version is 2.7, but I also tried master

I am using following configuration
```run-shell "powerline-daemon -q"
source "/usr/lib/python3.6/site-packages/powerline/bindings/tmux/powerline.conf"
unbind C-b
set -g prefix C-Space
bind-key C-Space send-prefix
# Vim style
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -p && xsel -o -p | xsel -i -b"
bind-key p run "xsel -o | tmux load-buffer - ; tmux paste-buffer"
set -g mouse on
set -g history-limit 50000
bind-key r source-file ~/.tmux.conf
set -g default-command "${SHELL}"
#urxvt tab like window switching (-n: no prior escape seq)
bind-key -n S-Down new-window
bind-key -n S-Left previous-window
bind-key -n S-Right next-window
bind-key -n C-Left swap-window -t -1
bind-key -n C-Right swap-window -t +1
set -g set-titles on
set -g set-titles-string "#T"
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/vim-tmux'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-logging'
# set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-resurrect'


# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```
Of course I also already tried disabling all plugins. Also checked all global keyboard shortcuts of my KDE environment, with the conclusion that Shift+Left|Right|Down is not used anywhere and therefor nothing is capturing this shortcut before tmux could.

Environment is Arch Linux, normal console is xterm-256color, within tmux it's screen-256color.
As terminal GUI I use either Yakuake or Konsole.
Server log where i started tmux with empty config and added the keybinding and tried it can be found here: https://gist.github.com/qwc/b62398f14b5b6be3e88ee5cb1f7bc446

**Comment by nicm** [comment]
Did you press the key in this log? I don't see it.

If you run cat outside tmux then press S-Left, what do you see?

**Comment by qwc** [comment]
Yes I did press the keys, `cat` shows nothing when I press those key combinations. Looks like I have to worry now?

**Comment by nicm** [comment]
Does it show anything if you open a new terminal?

**Comment by qwc** [comment]
Nope.

**Comment by qwc** [comment]
Okay, **BIG WTF** moment.

Just checkt the Yakuake profiles again, because I thought, wtf is happening here. I have **never changed** the keyboard settings of those profiles, but ... it was set to "Linux-Konsole". Setting this to "Standard (XFree 4)" solves the problem, of course.

Sorry for disturbing, looks like a ordinary monday problem...
