### ISSUE TITLE
mouse wheel and cursor pos question

### ISSUE THREAD

**Issue by mckellyln** [tmux/tmux#1493]
Hi,
Just a question really -  When I scroll in copy-mode-vi with mouse wheel, is it possible to not move the cursor to where pointer is when the wheel is rotated, but leave cursor where it was ?  And if so then I'd want to next figure out when a selection is present to continue the selection with the scroll.

Is there a better place to ask questions like this ?
thx for awesome tmux,
-m

**Comment by nicm** [comment]
No the mouse is always moved on any event at the moment. You can try this:
~~~~
diff --git a/window-copy.c b/window-copy.c
index 78667b1e..e35e6070 100644
--- a/window-copy.c
+++ b/window-copy.c
@@ -529,7 +529,7 @@ window_copy_command(struct window_pane *wp, struct client *c, struct session *s,
 		return;
 	command = args->argv[0];
 
-	if (m != NULL && m->valid)
+	if (m != NULL && m->valid && !MOUSE_WHEEL(m->b))
 		window_copy_move_mouse(m);
 
 	if (args->argc == 1) {

**Comment by mckellyln** [comment]
@nicm yes, this is perfect, thanks.  I can select and scroll now :-)
What do you think of making this an option ?

**Comment by nicm** [comment]
I think it should probably just be like this by default, will take a look again later.

**Comment by nicm** [comment]
Changed it now, thanks!
