### ISSUE TITLE
SUSE - Building Master Branch from Source - Configure Fails

### ISSUE THREAD

**Issue by holmanbph** [tmux/tmux#1496]
Trying to build from source gives the following error:
`configure: error: "libevent not found"`

platform: **SUSE 12 (x86_64)**
description:
**I ran `sh autogen.sh`, followed by `./configure`.  The configure script failed to find `libevent`, despite the fact that `libevent` is available (provided via rpm `libevent-2_0-5` - version 2.0.21).**

**Comment by nicm** [comment]
What am I supposed to do with so little information? Where's the full configure output? Where's config.log?

**Comment by reverendhomer** [comment]
> Trying to build from source gives the following error:
> `configure: error: "libevent not found"`
> 
> platform: **SUSE 12 (x86_64)**
> description:
> **I ran `sh autogen.sh`, followed by `./configure`. The configure script failed to find `libevent`, despite the fact that `libevent` is available (provided via rpm `libevent-2_0-5` - version 2.0.21).**

Have you tried to install `libevent-devel`?
