### ISSUE TITLE
Add the ability to pass environment variables to `new-session`

### ISSUE THREAD

**Issue by ismell** [tmux/tmux#1498]
When creating a session I haven't found a clean way of setting up the environment for a session before the initial command is executed. Instead I need to set the environment variable in the global environment, create the session, then use set-environment after the session has been created.

```shell
tmux set-environment -g MY_VAR foo \; \
     new-session -d -s foo watch 'echo $MY_VAR; tmux show-environment MY_VAR' \; \
     set-environment -t =foo MY_VAR foo \; \
     set-environment -g MY_VAR bar \; \
     new-session -d -s bar watch 'echo $MY_VAR; tmux show-environment MY_VAR' \; \
     set-environment -t =bar MY_VAR bar \; \
     set-environment -gu MY_VAR \;

```

I propose adding a new flag to new-session to allow setting the environment. i.e.,

```shell
tmux new-session -d -s foo -e MY_VAR=foo watch 'echo $MY_VAR; tmux show-environment MY_VAR' \; \
     new-session -d -s bar -e MY_VAR=bar watch 'echo $MY_VAR; tmux show-environment MY_VAR' \;
```

I can't use `update-environment` because I only want the session variable to be set on creation and not updated when reattached.

**Comment by nicm** [comment]
Added to TODO file.

**Comment by nicm** [comment]
Try this please: [tmux-environ-arg.diff.txt](https://github.com/tmux/tmux/files/3121768/tmux-environ-arg.diff.txt)

Note that -e is space or comma separated so you can't have environment variable values with spaces or commas in them.

**Comment by ismell** [comment]
I'll try it out this week. Thanks!

**Comment by nicm** [comment]
A variant of the PR was applied instead of my patch so you can now build from master and use -e.

**Comment by ismell** [comment]
Even better. Thanks!
