### ISSUE TITLE
Feature Request: Allow specifying which pane to merge/expand on `kill-pane`

### ISSUE THREAD

**Issue by xelxebar** [tmux/tmux#1499]
## Overview

When working with many panes, sometimes we want a litte more control over how the layout changes when killing a pane closes.

```
                               Figure 1

+---------+---------+    +---------+---------+    +---------+---------+
|   Top   |  Top    |    |   Top   |  Top    |    |   Top   |         |
|   Left  |  Right  |    |   Left  |  Right  |    |   Left  |         |
+---------+---------+    +-------------------+    +---------|  Right  |
|  Bottom |  Bottom |    |                   |    |  Bottom |         |
|  Left   |  Right  |    |      Bottom       |    |  Left   |         |
+---------+---------+    +-------------------+    +---------+---------+
         2x2                  Full Bottom              Full Right
```

For example, assume we start from a `2x2` layout as in the figure above and wish to kill the `Bottom Right` pane. Depending on how we initially split the panes, we will end up in either one of the `Full Bottom` or `Full Right` layouts.

However, it would be nice to let this be user specifiable at `kill-pane` time instead of fixing it at `split-window` time.

## Proposal

The dumbest/simplest API change here would be to simply add a switch to `kill-pane`

```
kill-pane [-a] [-s src-pane] [-t target-pane]
```

where `src-pane` expands into the empty slot left by `target-pane`.  The obvious issue here is that there are nonsense values for `src-pane`. In the example from `Figure 1`,  the `Top Left` pane simply cannot expand into the `Bottom Right` space. So the implementation needs to be aware of pane topology.

Specifically, this would entail a change of `layout.c/layout_destroy_cell`, which currently just selects from neighboring `TAILQ` entries. As such, an implementation of this proposal would instead require checking that `src-pane` and `target-pane` share an equally-sized edge.

I'm unable to judge how much work this would actually require, but does it seem reasonable?

## Version Information

For posterity and good measure:

```
$ lsb_release --all
Distributor ID: VoidLinux
Description:    Void Linux
Release:        rolling
Codename:       void

$ uname -a
Linux lang 4.18.13_1 #1 SMP PREEMPT Wed Oct 10 15:39:06 UTC 2018 x86_64 GNU/Linux

$ tmux -V
tmux 2.7
```

**Comment by ThomasAdam** [comment]
Use hooks to do this.

**Comment by xelxebar** [comment]
@ThomasAdam 
Could you please elaborate a bit more? Hook on which notification and do what exactly?

**Comment by nicm** [comment]
This is the same as https://github.com/tmux/tmux/issues/918 which is already in the TODO file. Adding a flag to kill-pane is OK by me.
