### ISSUE TITLE
Usability: Add a better visual indicator to copy-mode

### ISSUE THREAD

**Issue by YoloClin** [tmux/tmux#1500]
Unless I'm missing something, the only visual indicator of copy-mode is the line-count in the top right-hand corner. I regularly end up in copy-mode and feel like a shell has hung - Would it be possible to add functionality to change the status-bar color (or better yet, the background color) when in copy-mode?

I've tried `setw -g mode-style "fg=red,bg=blue"` but that really doesn't fix the issue.

**Comment by nicm** [comment]
You can't change the whole status line colour easily but you could change part of it by using the pane_mode format.

**Comment by nicm** [comment]
Actually you could change the status line colour entirely using the pane-mode-changed hook.

**Comment by YoloClin** [comment]
`set-hook -g  'pane-mode-changed' 'set -g status-style "#{?#{==:#{pane_mode},copy-mode},red,blue}"'` triggers, but does not evaluate on trigger (ie the logic is not parsed)

`set -g status-left '#[bg=blue]#[fg=colour0]#{?#{==:#{pane_mode},copy-mode},#[bg=red],} AAAAA '` works seemingly pretty reliably, but I'd prefer the whole line if at all possible, but 
`set -g status-style "bg=blue,#{?#{==:#{pane_mode},copy-mode},#[bg=red],}"` also doesn't appear to evaluate. 

Any ideas on a workaround?

**Comment by nicm** [comment]
set-option does not expand formats by default, you need -F:
~~~~
set-hook -g 'pane-mode-changed' 'set -gF status-style "bg=#{?#{==:#{pane_mode},copy-mode},red,blue}"'

**Comment by YoloClin** [comment]
Cool that worked! Thanks :)
