### ISSUE TITLE
RFC: session-local buffers

### ISSUE THREAD

**Issue by tureba** [tmux/tmux#1501]
Hi,

This came up on irc today and it sounded like a fairly sane use case, but I couldn't find any other issue with a similar discussion. So I'm starting one, if only for documentation.

The user expected/wanted the buffer list to be per-session and independent from each other. But instead, there is one buffer list shared among all sessions in a server. In the end, the user went on to use different servers to get this behavior, but it still is an improvement point for tmux.

If the user has one session for each line of work they're working on, it makes sense for these workspaces to be more independent and almost disjoint. I'd say it's akin to hitting the up arrow in a shell and seeing the current running shell's history, but not the other running shells' histories (at least until each of them exits and saves their own history in the histfile they all read from). Some shells give the option to update the histfile on each command execution, so they all get the shared history, but that's opt-in. I believe both behaviors regarding buffers are sane and could be available (keeping the current shared as default, of course).

I was going to suggest the user to rebind all buffer-facing commands to have the session name as prefix, such as `#S:bufferNNNN`, so as their bindings would behave as if using different default buffers for each session. However, it turns out that:
* some commands aren't accepting buffer names, for instance `copy-selection` takes no args and passes NULL down to `window_copy_copy_selection()`
* generating non-overlapping numbers NNNN would be very troublesome, needing a small script
* buffers filled like so would not be cleaned up when reached `buffer-limit`, requiring yet more scripting to get the same behavior

I think it would make sense to have a session/server config indicating if the session's buffers (and perhaps other resources?) are shared or local. If local, make commands use a different prefixed set of buffers by default. Sketched as:
* new config session_local_buffers, true/false, default false
* in `paste.c:paste_add()/xasprintf()`, if the config is set, use `#S:bufferNNNN` (possibly with a per-session `paste_next_index`); otherwise use `bufferNNNN` like now
* in `choose-buffer`, if the config is set, then the default filter -f would be an fnmatch() on `#S:buffer*`; otherwise no filter, like now
* if it makes sense for `buffer-limit` to be per session as well, then also in `paste.c:paste_add()`, if the config is set, only free buffers that are automatic _and_ of the same session
* on session close, free up all of its automatic buffers
* and probably other similar changes

Thoughts?

**Comment by ThomasAdam** [comment]
I really think this is a niche use-case.  So I really don't think we need to worry about writing any code in tmux.

What you could do is explicitly name the paste-buffer with the appropriate session in the name, and then use a means of appropriating these per session.

**Comment by nicm** [comment]
I agree, your suggestion of per-session buffers is far too much infrastructure for a feature that very very few users will need. It makes better sense that they are global, and this is the first time any change has come up.

I would suggest just making changes so it could be configured as you first thought:
- Make the various copy mechanisms able to take a prefix to use when generating an automatic name (so instead of "buffer" you would specify "#{session_name}" or similar).
- I don't think it matters if session X automatic buffers are X_0,X_1,X_5 and session Y is Y_2,Y_3,Y_4 but if you care you could make the numbering use the first missing number with the given prefix instead, or the next number after the highest with the given prefix (this might be better).
- I don't think it matters about buffer-limit either but since automatic buffers are flagged you could also make it per prefix, so it applies separately to automatic buffers named "X_*" and "Y_*".

This way there would be little change to how it works now, but people who multiple different set of automatic buffers (whether per session or something else) could configure tmux to create them with different prefixes.

**Comment by tureba** [comment]
True. I thought it might be a big set of changes for such a small feature. The prefix approach is also very nice.

p.s.: The point I tried to make about independent indexes for each session was not about the numbers per se. I thought I'd read the code resetting that index counter after 10000, in which case a session could advance it faster than the others, making them stumble on many collisions on the loop around the xasprintf. It's clear to me now that I misread the code earlier.

**Comment by nicm** [comment]
Added to TODO file.

**Comment by moritzdietz** [comment]
> I would suggest just making changes so it could be configured as you first thought:
> 
> * Make the various copy mechanisms able to take a prefix to use when generating an automatic name (so instead of "buffer" you would specify "#{session_name}" or similar).

FYI: The IRC user with that question/need would be me in this case.
This suggestion would most certainly work just fine for me; I could then use `choose-buffer` with a filter for the session name and have my "local" session buffers but also could have normal access to all the other buffers like you would normally.

**Comment by nicm** [comment]
Try this please [tmux-buffer-prefix.diff.txt](https://github.com/tmux/tmux/files/3013272/tmux-buffer-prefix.diff.txt), which allows you to specify a prefix (formats expanded) to copy-selection and friends, for example:
~~~~
send -X copy-selection "#{session_name}_"
~~~~
You will need latest master for the patch to apply.

**Comment by moritzdietz** [comment]
I'll give it a try and report back. Thanks!

**Comment by moritzdietz** [comment]
So after a bit of testing and after applying the latest master branch that includes the fixes what we talked about on IRC yesterday evening, this works like a charm. Thanks for implementing this!

**Comment by nicm** [comment]
I have applied this now, thanks!
