### ISSUE TITLE
Please do not clear scrollback history on RIS

### ISSUE THREAD

**Issue by vnagarnaik** [tmux/tmux#1505]
- tmux version: 2.8
- platform (Linux, OS X, or whatever): Linux

Issue:
The following commit changed behavior on RIS for tmux:
80bdd898560db81baa1430e0b093b896a09b542e

I use tmux for developing on kernels and some bootloaders seem to want to send RIS to the terminal in order to clear history. But I don't want to clear my history in case the kernel crashes or a reboot.

I also use 'reset' to set the terminal state if some copy/paste operation ends up messing with the terminal settings. But even in this case I don't want scrollback history to disappear.

I started using tmux in 2011 when I found that it doesn't clear the scrollback history on RIS like gnome-terminal or other terminals. Since then I have grown to love and use all its other aspects for terminal management.

Intended Behavior:
I would be happy if the commit was reverted. Or at least there was some option added to prevent RIS from clearing history.

Thanks.

**Comment by nicm** [comment]
There will be no option for this, whether or not to keep it as it is I'm undecided.

**Comment by vnagarnaik** [comment]
To nudge you in the "right" direction: screen 4.06.02 (latest on debian testing) still does not clear scrollback history.

More seriously, I have come to rely on tmux to not clear scrollback history on 'reset' since 2011. Currently I am pinning to tmux 2.7 for the time being. If you decide to keep this change, I will have to use private builds like @systemmonkey42 reverting the patch.

**Comment by avih** [comment]
Clearing the history can sometimes be desired too, and I think most terminals do clean history on reset, therefore I think it should be the default.

That being said, I agree sometimes it's useful to reset the terminal also without clearing the history.

I'm not maintaining tmux so it's easy for me to say, but I think allowing behavior toggle per pane via some tmux command could be useful, while defaulting to "reset clears history".

**Comment by nicm** [comment]
There will not be an option for this.

I think it is an error for bootloaders to send this, how do they even know the terminal is VT100 compatible?

**Comment by vnagarnaik** [comment]
I think bootloaders don't know anything about the terminal but they send the reset anyway.

This brings back to my original comment on the bug where I started using tmux specifically to prevent clearing scrollback history either accidentally or by using 'reset'.

So I still don't get the reason why tmux needs to adhere to this small detail of standard after so many years of not implementing it. tmux users didn't care about it at least till the 2.8 release. I also don't see anyone really insisting on enabling this feature. Is there really a use case/usability issue where clearing the scrollback history is desirable? The 'reset' or 'clear' commands already wipe the displayed text on the terminal (while keeping scrollback history) which is perfectly fine for usability reasons.

**Comment by nicm** [comment]
I have reverted this for the moment, although I suggest you report this to the bootloaders in question and ask them not to send it.

**Comment by vnagarnaik** [comment]
Thank you for reverting the patch.
