### ISSUE TITLE
Cannot navigate to session when list is too long

### ISSUE THREAD

**Issue by diegospendit** [tmux/tmux#1508]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

Hi all,

my list of sessions is long. Pressing Ctrl-b-s I see the following list:

0
1
2
....
8
9
M-a
M-b
M-c

I can select a session just pressing a number (0 to 9). However, I cannot select a session named M-a or M-b. I tried several things but nothings works. 

Operating System: MacOS
Default Terminal
Darwin i386
tmux 2.7
screen-256color

I am running Fish shell.

Minimal config to reproduce it:
unbind C-b
set -g prefix C-a
bind C-a send-prefix

**Comment by nicm** [comment]
What things did you try? Was one of them pressing M-a?

**Comment by diegospendit** [comment]
I tried Crtl-a+s, then pressing again Crtl-a. M-a looks for me like Crtl-a.

I tried as well, pressing Ctrl-a+s, then pressing again Ctrl+a+a, it did not work either.

How should I select such a sessions?

**Comment by diegospendit** [comment]
@nicm I tried of course just pressing "a". It did not work either.
In previous versions (sorry, I do not know which ones) the sessions after 9 were named just with one letter (a, b, c ,d....).

**Comment by nicm** [comment]
M-a is not Ctrl-a, it is Meta-a. Meta is usually Alt. Try Alt-a or Escape then a.

**Comment by diegospendit** [comment]
Hi @nicm, I am on MacOS. I tried Option-a, I understand Option is Alt in Mac. 
Pressing Escape then a did not work. Escape causes to close the list of sessions.

**Comment by nicm** [comment]
I don't know what the meta key is on OS X.

**Comment by diegospendit** [comment]
Hi @nicm,
I just found the solution. Option should be configured in MacOS as the Metakey.
http://osxdaily.com/2013/02/01/use-option-as-meta-key-in-mac-os-x-terminal/

The issue can be closed.

Thanks for your help!
