### ISSUE TITLE
tmux 2.1 breaks iterm2 shortcut commands

### ISSUE THREAD

**Issue by joshuarubin** [tmux/tmux#151]
I have the following in my `.tmux.conf`:

```
set -g prefix C-a
bind-key H resize-pane -L
bind-key J resize-pane -D
bind-key K resize-pane -U
bind-key L resize-pane -R
```

I have configured iterm2 with the following shortcut keys (`0x01` is `C-a`):

```
<ctrl-shift-H> => Send Hex Codes: 0x01 0x48
<ctrl-shift-J> => Send Hex Codes: 0x01 0x4a
<ctrl-shift-K> => Send Hex Codes: 0x01 0x4b
<ctrl-shift-L> => Send Hex Codes: 0x01 0x4c
```

This worked fine with tmux < 2.1 but now stopped working. Perhaps it's a timing issue?

**Comment by nicm** [comment]
Turn down assume-paste-time

-------- Original message --------

**Comment by joshuarubin** [comment]
Worked beautifully, thanks!
