### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#1511]
Hi

I am trying to do following and it's not working, but I could be doing something wrong, or just not understanding.

#{b:pane_current_path} will display current dir --> this is good.

what I would like to get, if I am in my home dir just display '#' if I change dir to something else then display ```# + current_dir```.

I tried using ```#{s/my_home_dir//b:pane_current_path}``` but it showed nothing, if I remove b: it was showing this /Users//some_dir.

I have tested it with ```tmux display-message -p -F "#{s/text to remove//:pane_current_path}" -t0```
displays /Users//code, running same command but adding b:pane_current_path display nothing.

Thanks.

**Comment by lanox** [comment]
@ncim doh I though that would just remove text,

Thank you so much.
I am trying to incorporate above in my current settup.

setw -g window-status-format "#[fg=colour243] #I#[fg=colour243]#{?window_name, #{window_name},}"
setw -gF window-status-current-format "#[fg=colour106,bold]#{?window_name,#{window_name},}#[fg=colour009,bold]#{?window_zoomed_flag, ZOOMED,}"

but I cant seem to work it out, and to be honest I do not understand it all completely.

**Comment by nicm** [comment]
If you put the whole of this bit:
~~~~
#{?#{==:#{pane_current_path},$H},##,#{?#{m:$H/*,#{pane_current_path}},##,}#{b:pane_current_path}}
~~~~
Where you want the path it should work.

**Comment by lanox** [comment]
Hi @nicm thanks so much for all the help and support you provide, this is where I am stuck,

```
setw -g window-status-format "#[fg=colour243] #I#[fg=colour243]#{?window_name, #{window_name} ,}"
setw -g window-status-current-format "#[fg=colour106,bold]#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H},,#{?#{m:$H/*,#{pane_current_path}},,}#{b:pane_current_path}}}#[fg=colour009,bold]#{?window_zoomed_flag, ZOOMED,}"
```
this is what it looks like
<img width="919" alt="screen shot 2018-10-28 at 9 29 04 pm" src="https://user-images.githubusercontent.com/7599183/47614740-94eb6700-daf8-11e8-807d-af7e990a927a.png">

however if I change to second to other window it looks like this

<img width="922" alt="screen shot 2018-10-28 at 9 29 23 pm" src="https://user-images.githubusercontent.com/7599183/47614747-b2b8cc00-daf8-11e8-8a62-02d2b19289cc.png">
is it possible while I am on window "2" to show current dir.

Thanks so much.

Do you have donation section of tmux ?

**Comment by nicm** [comment]
window-status-format looks OK to me. I don't see a dot when I try it, did you change automatic-rename-format as well?

**Comment by lanox** [comment]
@ncim, I have managed to pin point it down to having multiple windows, if I have a single window no "dot" next to top command, if I have multiple windows "dot" appears next to top commmand.
This is my entire status bar config.
```
set -wg automatic-rename-format "#{s/zsh//:pane_current_command}"
setw -g window-status-format "#[fg=colour243]#I #[fg=colour243]#{?window_name,#{window_name},}#{?#{==:#{pane_current_path},$H},,#{b:pane_current_path}}"
setw -g window-status-current-format "#[fg=colour106,bold]#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H}, ,#{?#{m:$H/*,#{pane_current_path}}, ,}#{b:pane_current_path}}}#[fg=colour009,bold]#{?window_zoomed_flag, ZOOMED,}"
```

**Comment by nicm** [comment]
There is always a current process, do you mean if the process is zsh so window_name is empty? Yes, you can show window_name unless it is empty then show pane_current_path instead. You already do similar in window-status-format?

**Comment by nicm** [comment]
Does this show the dot if you run it from the shell inside tmux?
~~~~
tmux lsp -aF '#{pane_current_command}'

**Comment by lpuljic** [comment]
> Does this show the dot if you run it from the shell inside tmux?
> 
> ```
> tmux lsp -aF '#{pane_current_command}'
> ```

@nicm,  nop this is what it shows,

while top is running in other window
tmux lsp -aF '#{pane_current_command}'
top
tmux

**Comment by lpuljic** [comment]
> There is always a current process, do you mean if the process is zsh so window_name is empty? Yes, you can show window_name unless it is empty then show pane_current_path instead. You already do similar in window-status-format?

<img width="1258" alt="screen shot 2018-10-29 at 9 03 05 pm" src="https://user-images.githubusercontent.com/38928237/47642941-1ce77480-dbbe-11e8-8073-8bba8562f757.png">
in above image you can see that nvim is running and status bar is showing correctly.

In the image below.
<img width="1258" alt="screen shot 2018-10-29 at 9 03 21 pm" src="https://user-images.githubusercontent.com/38928237/47642992-430d1480-dbbe-11e8-8581-9d5f7af371e7.png">
you can see that I have changed to another window in the tmux and you can see that status bar is now showing ```1 nvim dotfiles```, what I was asking is would it be possible , if the nvim is running to show only nvim, but if there is no process running show dir only.

**Comment by nicm** [comment]
I don't understand what you want to see now? What do you want to see for current window and not current windows?

**Comment by lpuljic** [comment]
sorry, 

Scenario 1
Currently showing ```1 nvim dotfiles```, I want to see only ```1 nvim```. 
Scenario 2 
If there is no process running only show ``` 1 dotfils```

**Comment by nicm** [comment]
Right so for (1) why don't you do sometihng like #{?window_name,#{window_name},#{path stuff}}.

**Comment by nicm** [comment]
You are missing a } at the end?

**Comment by lpuljic** [comment]
it looks fine if I add another } it actually shows it on statusbar.

**Comment by nicm** [comment]
Uh? What do you have now?

**Comment by lpuljic** [comment]
this is what I have
```#{?window_name,#{window_name} ,}#{?#{==:#{pane_current_path},$H},,#{b:pane_current_path}}``` and it seems to be working, I could swear that I tried this and it did not work.

Hrm still puzzled about top command, but what ever.

I think I can leave you alone now :)  Thank you so much.

**Comment by lpuljic** [comment]
sorry it's still not working  I am still seeing `` 1 {pane_current_command} {pane_current_path}```

**Comment by nicm** [comment]
But this is not going to work, you need to put the pane_current_path bit inside the ?:
~~~~
#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H},,#{b:pane_current_path}}}

**Comment by lpuljic** [comment]
Yep, it's working.  UGH, thanks heaps, you my friend are amazing in helping out. tmux community is genuinely lucky to have you.
