### ISSUE TITLE
Self report current path to tmux for split panes, windows, etc.

### ISSUE THREAD

**Issue by casr** [tmux/tmux#1512]
I am currently on OpenBSD and I really miss not having `pane_current_path`. I have seen #126 in the issue tracker and, as the feature was unpredictable, it won't be returning.

But I wonder if the variable could be re-purposed to have the current shell report the CWD to tmux. I believe that Terminal.app on macOS supports something similar so that it can open tabs with the same directory. In Terminal.app a special escape sequence makes this possible and is the same sequence that xterm uses to set its title:

    ESC]2;${PWD}BEL

or using OpenBSD's default shell you can do something like:

    export PS1="\e]2;\${PWD}\a$ "

Would this approach or similar be a way that could bring back this functionality on OpenBSD?

**Comment by nicm** [comment]
If you do that then you can use pane_title.

**Comment by casr** [comment]
This solution of using `pane_title` for the starting directory has worked pretty well this last year, however, there is one area I've noticed it fall down.

A programme, like Vim, can still set its own title which breaks the behaviour. I find myself having to <kbd>Ctrl</kbd>+<kbd>z</kbd> out of such programmes, so that the shell can take the title back over, and then split the window.

You can work around this in Vim by using `set titlestring=%{getcwd()}` but setting this per programme might get troublesome. Would a self-reported `pane_current_path` to separate the concerns of title and working directory start to make sense in this scenario?

**Comment by nicm** [comment]
You can run -current and use OSC 7/pane_path instead.

**Comment by casr** [comment]
Ah it landed quite recently in https://github.com/tmux/tmux/commit/f3dc38dcae472286c7d7c2708e4dbfe70a6c2d57

That's great to hear and glad to see it's in the [OpenBSD version] too. Thanks @nicm!

[OpenBSD version]: https://cvsweb.openbsd.org/src/usr.bin/tmux/format.c?rev=1.214&content-type=text/x-cvsweb-markup
