### ISSUE TITLE
After change pane first input char missing

### ISSUE THREAD

**Issue by gilberg-vrn** [tmux/tmux#1513]
Hello

I encountered with unexpected behavior in tmux 2.7:
When i'm copy some text from one pane and change pane to another (`prefix + up`) and paste from clip (`ctrl+shift+v`) first char is missing (`s -la` instead `ls -la`, as example), if i wait for expire repeat-time - works fine

On another system with indentically preference (os, .tmux.conf, zsh, etc. in same verisions) it works as expected.

I tried to remove `.tmux.conf`, login as user without any config files, update tmux to 2.8, but it showed nothing.

My [.tmux.conf](https://raw.githubusercontent.com/gilberg-vrn/dotfiles/master/tmux.conf)

Thanks.

**Comment by nicm** [comment]
If you end a set of repeating keys with a key press that isn't repeating, it doesn't execute the command and it isn't inserted. I have a feeling it didn't used to work like this...

**Comment by gilberg-vrn** [comment]
On another system (with similar config) it works correctly:
https://asciinema.org/a/7neOkRaMH4zFOGzUnlabZH9Hu

Maybe, other settings can break that?

**Comment by nicm** [comment]
Are you sure you aren't using different versions?

**Comment by nicm** [comment]
This might fix it:
~~~~
diff --git a/server-client.c b/server-client.c
index 410b8c02..aa4dd0f5 100644
--- a/server-client.c
+++ b/server-client.c
@@ -1042,7 +1042,7 @@ try_again:
                        server_client_set_key_table(c, NULL);
                        c->flags &= ~CLIENT_REPEAT;
                        server_status_client(c);
-                       table = c->keytable;
+                       first = table = c->keytable;
                        goto table_changed;
                }
                log_debug("found in key table %s", table->name);

**Comment by gilberg-vrn** [comment]
It didn’t help

**Comment by nicm** [comment]
Please show tmux logs from reproducing with the patch applied.

**Comment by gilberg-vrn** [comment]
Session with one window of two horizontal panes. Patch was applied.
I’m switching from bottom pane to top (prefix + UP) and typing `asd`

tmux-server.log
```
1541020361.957036 @0 active pane changed // after prefix + UP
1541020361.957211 format '#{pane_current_command}' -> 'bash'
1541020361.957228 format '' -> ''
1541020361.957236 format '#{?pane_in_mode,[tmux],#{pane_current_command}}#{?pane_dead,[dead],}' -> 'bash'
1541020361.957253 @0 name not changed (still bash)
1541020361.957312 /dev/pts/0: wrote 1119 bytes (of 1119)
1541020361.957324 /dev/pts/0: waiting for redraw, 0 bytes left
1541020361.957333 cmdq_next <global>: empty
1541020361.957342 cmdq_next <0x12e8db0>: empty
1541020361.957354 @0 active pane not changed
1541020362.174589 /dev/pts/0: read 1 bytes (already 0) // type "a"
1541020362.174620 /dev/pts/0: keys are 1 (a)
1541020362.174630 /dev/pts/0: next key is 1 (a) (expired=0)
1541020362.174639 /dev/pts/0: complete key a 0x61
1541020362.174652 session $0 0 activity 1541020362.174646 (last 1541020361.950607)
1541020362.174662 cmd_find_from_session: s=$0 0
1541020362.174669 cmd_find_from_session: wl=0 1 w=@0 bash
1541020362.174675 cmd_find_from_session: wp=%0
1541020362.174681 cmd_find_from_session: idx=none
1541020362.174688 session 0 not pasting
1541020362.174697 key table prefix (pane %0)
1541020362.174703 currently repeating
1541020362.174711 not found in key table prefix
1541020362.174719 key table root (pane %0)
1541020362.174725 not found in key table root
1541020362.174734 cmdq_next <global>: empty
1541020362.174742 cmdq_next <0x12e8db0>: empty
1541020362.174749 /dev/pts/0: redraw status
1541020362.174754 /dev/pts/0: redraw needed
1541020362.174768 screen_write_start: size 363x1, no pane
1541020362.174827 screen_write_collect_flush: flushed 0 items (0 bytes)
1541020362.174835 screen_write_stop: 363 cells (363 written, 0 skipped)
1541020362.174982 format '[#S] ' -> '[0] '
1541020362.175009 unref client 0x12e8db0 (2 references)
1541020362.175168 format '' -> ''
1541020362.175196 format '#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}"#{=21:pane_title}" 00:12 01-Nov-18' -> '"localhost.localdomain" 00:12 01-Nov-18'
1541020362.175219 unref client 0x12e8db0 (2 references)
1541020362.175321 format '#{window_flags}' -> '*'
1541020362.175330 format '#I:#W#{?window_flags,#{window_flags}, }' -> '0:bash*'
1541020362.175351 unref client 0x12e8db0 (2 references)
1541020362.175363 screen_write_start: size 8x1, no pane
1541020362.175375 screen_write_collect_flush: flushed 0 items (0 bytes)
1541020362.175382 screen_write_stop: 8 cells (8 written, 0 skipped)
1541020362.175400 screen_write_start: size 363x1, no pane
1541020362.175425 screen_write_collect_flush: flushed 0 items (0 bytes)
1541020362.175436 screen_write_stop: 43 cells (40 written, 3 skipped)
1541020362.175474 screen_redraw_set_context: /dev/pts/0 @0 ox=0 oy=0 sx=363 sy=101 1/0
1541020362.175488 /dev/pts/0: redraw added 0 bytes
1541020362.175500 @0 active pane not changed
1541020362.294604 /dev/pts/0: read 1 bytes (already 0) // type "s"
1541020362.294644 /dev/pts/0: keys are 1 (s) 
```

**Comment by nicm** [comment]
Where is the rest of the log?

**Comment by gilberg-vrn** [comment]
Full log in gist
https://gist.github.com/gilberg-vrn/4b7f900523fe726fd9061bb845933618

**Comment by nicm** [comment]
Hmm yes you are hitting the other case, but if we change it we are reverting something that was added for a reason. I will need to go and figure out what problem this was originally solving.

**Comment by nicm** [comment]
Actually I am not sure what is happening with your key presses. I will look again tomorrow if I have time. I think the mechanism added in 92a77e7654286a8aa4734b36f74ea49f9494311b is interfering - if a key is not in the prefix table, we check the root table, but if it also isn't there, we don't want to pass it on to the pane. But in your case we do want to pass it to the pane.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/2536567/x.diff.txt)

**Comment by gilberg-vrn** [comment]
It didn’t help, again

**Comment by gilberg-vrn** [comment]
https://gist.github.com/gilberg-vrn/4592816ad27b12433c26aee853e8af79

**Comment by nicm** [comment]
Are you sure you ran a binary with the latest diff? There is no sign of the extra logging I added in this log.

**Comment by gilberg-vrn** [comment]
Sure. Terminal output of build and run patched version, just in case
Compile - https://gist.github.com/gilberg-vrn/09d69e934cd987f777e74c02268069cd
Run - https://gist.github.com/gilberg-vrn/76a0e40f6a62f303ea87a978e4f34b39

**Comment by nicm** [comment]
OK try this instead please and show logs again: [y.diff.txt](https://github.com/tmux/tmux/files/2537836/y.diff.txt)

**Comment by gilberg-vrn** [comment]
Yes, it does. Thanks!
[tmux-server-25046.log](https://github.com/tmux/tmux/files/2540095/tmux-server-25046.log)

**Comment by nicm** [comment]
So this fixes it?

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
