### ISSUE TITLE
Pressing Esc while another attached session is scrolling will send an Up key instead

### ISSUE THREAD

**Issue by Yonsh** [tmux/tmux#1514]
Platform: Linux
tmux version: Any version after [c48440fd](https://github.com/tmux/tmux/commit/c48440fd40992bab1ead8ec5aeadba5ba073359e)

To reproduce this bug easier, please have `escape-time` option set to `0`.

I noticed this bug when I was coding with vim while having other terminal compiling something. It can cause quite a bit of troubles at certain circumstances.

Reverting [c48440fd](https://github.com/tmux/tmux/commit/c48440fd40992bab1ead8ec5aeadba5ba073359e) seems to be able to stop this issue from happening.

![peek 2018-10-27 16-30](https://user-images.githubusercontent.com/3953982/47601586-a7d13f00-da05-11e8-9ff4-8dde7ad1c23e.gif)

**Comment by nicm** [comment]
This change has nothing to do with key presses. More likely tmux is just
busier when a session is scrolling so it is more likely to get keys split
or combined across read()s, although since you didn't  include any logs it
is hard to tell exactly. If you use escape-time 0 you will get keys
misinterpreted from time to time because you are disabling the mechanism to
avoid it, although it can still happen anyway. Try escape-time 10 instead.

**Comment by Yonsh** [comment]
Hi, I've been digging into this issue, and might have found out the problem with a possible solution.

The first keycode sent within `tty_cmd_scrollup` seems to be interpreted as a combination key with `Esc` if I was typing `Esc` in another session. In fact, even if I set `escape-time` to a higher number, it will still send the same combination if I don't type anything in that period. I've to put a `\0` before sending any keycode, and it seems to be working fine, though there might be better solutions.

Here's what I've been put into the code:
[x.diff.txt](https://github.com/tmux/tmux/files/2522521/x.diff.txt)

Here's a comparison of some different server logs:
The left pane was using c48440fd reverted version, the middle and right panes were using the master branch, while the right pane had the status bar turned off.
![server-log-comparison](https://user-images.githubusercontent.com/3953982/47612179-1f5ba880-dab0-11e8-883b-069cafafd217.png)

**Comment by nicm** [comment]
Hmm, yes it looks funny. Does this fix it?
~~~~
--- a/tty-keys.c
+++ b/tty-keys.c
@@ -624,7 +624,7 @@ first_key:
         * If not a complete key, look for key with an escape prefix (meta
         * modifier).
         */
-       if (*buf == '\033') {
+       if (*buf == '\033' && len > 1) {
                /* Look for a key without the escape. */
                n = tty_keys_next1(tty, buf + 1, len - 1, &key, &size, expired);

**Comment by Yonsh** [comment]
Yes, it does. Thanks! :smiley:
