### ISSUE TITLE
`send-keys` executes multiple commands asynchronously (or `copy-pipe-and-cancel` does not wait for process completion)

### ISSUE THREAD

**Issue by intelfx** [tmux/tmux#1517]
- tmux version:
  ```
  $ uname -sp && tmux -V && echo $TERM
  Linux unknown
  tmux 2.8
  tmux-256color
  ```
- platform: GNU/Linux (Arch Linux)
- terminal: GNOME terminal
- `$TERM` inside tmux: `tmux-256color`
- `$TERM` outside tmux: `xterm-256color`

I have this snippet in my `tmux.conf`:
```
bind -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel "curl -F 'f:1=<-' ix.io | tmux load-buffer -btmp -" \; show-buffer -btmp
```

The intent of this sequence is to send selection to ix.io (a pastebin service) and then display the resulting link.

However, it does not work: first invocation of this sequence says "No buffer tmp", and the following invocations show the previous link. Obviously, the buffer is shown before it is loaded with data, i. e. `show-buffer -btmp` executes before `load-buffer -btmp -` in the shell pipeline.

Hence this bug report / RFE is about making the above sequence execute synchronously. I don't know if the problem is in `send-keys` implementation or `copy-pipe-and-cancel` implementation.

**Comment by nicm** [comment]
No it does not and I don't think it is worth it. Put everything you want to
be synchronous inside the copy-pipe argument.

**Comment by intelfx** [comment]
Well, at least it's straight to the point. :)

I know it's not a support forum, but how can I emulate running `show-buffer` inside tmux from a shell command?

**Comment by nicm** [comment]
Good question. You can use wait-for, but it doesn't know how to block the command queue, so it needs to be wrapped inside run-shell, something like:

~~~~
bind -Tcopy-mode Y send-keys -X copy-pipe-and-cancel "mycommand|tmux load-buffer -btmp -; tmux wait -S tmp" \; run "tmux wait tmp" \; show-buffer -btmp
~~~

(It would be better if wait-for could do it itself and it wouldn't be hard to make it work.)

**Comment by intelfx** [comment]
So "block the command queue" is a property of each individual command? Can't we just make `copy-pipe` "block the command queue" then?

**Comment by nicm** [comment]
Go on then.

**Comment by intelfx** [comment]
I'd appreciate a few pointers as to where to start looking.

**Comment by nicm** [comment]
For standard commands you can look at run-shell, it returns CMD_RETURN_WAIT
(or something like that) which tells the queue to stop executing subsequent
commands. Then when the command finishes and the job complete callback is
fired, it clears the wait flag and calls cmdq_continue.

For send-keys it will be a little different, you will need some mechanism
for the window-copy.c code to tell the send-keys code to block, I'm not at
home and I can't remember what the mode key press handler function returns,
possibly it could be changed to return a cmd_retval if it doesn't already.
Then it will need a similar dance to run-shell for when the job finishes.
The important thing will be to make sure you continue the right client but
otherwise it should be much the same idea.

**Comment by nicm** [comment]
This should be enough to make wait-for work inside tmux, which means you can drop the run-shell call and just do:
~~~~
bind -Tcopy-mode Y send-keys -X copy-pipe-and-cancel "mycommand|tmux load-buffer -btmp -; tmux wait -S tmp" \; wait tmp \; show-buffer -btmp
~~~~

~~~~
diff --git a/cmd-wait-for.c b/cmd-wait-for.c
index 396548a7..33600eda 100644
--- a/cmd-wait-for.c
+++ b/cmd-wait-for.c
@@ -170,7 +170,7 @@ cmd_wait_for_wait(struct cmdq_item *item, const char *name,
        struct client           *c = item->client;
        struct wait_item        *wi;

-       if (c == NULL || c->session != NULL) {
+       if (c == NULL) {
                cmdq_error(item, "not able to wait");
                return (CMD_RETURN_ERROR);
        }
@@ -198,7 +198,7 @@ cmd_wait_for_lock(struct cmdq_item *item, const char *name,
 {
        struct wait_item        *wi;

-       if (item->client == NULL || item->client->session != NULL) {
+       if (item->client == NULL) {
                cmdq_error(item, "not able to lock");
                return (CMD_RETURN_ERROR);
        }

**Comment by intelfx** [comment]
Oh, thanks for the hints and code example :) I'll take a look at weekend.

**Comment by nicm** [comment]
Great thanks.

**Comment by nicm** [comment]
I have applied my fix for wait-for so you can use it more effectively. If you change copy-pipe please open a PR. I will add it to the TODO file also in any case.
