### ISSUE TITLE
tmux is changing the utf character in a scripts written in tmux

### ISSUE THREAD

**Issue by PawarKishori** [tmux/tmux#1519]
The line of code written in python in original file:
hindi_punct=['‘','’']
The same above line when file opened in tmux:
hindi_punct=['_','_']

So, when I have a character in utf in some file, tmux is changing it internally.
This happens also when I have hindi language text opened in tmux. Earlier I thought tmux has problem for visualising utf text, but internally it changes its value too.
How to handle this?

**Comment by nicm** [comment]
tmux cannot change the contents of your files.
