### ISSUE TITLE
tmux 2.1 status bar variables not rendering

### ISSUE THREAD

**Issue by drn** [tmux/tmux#152]
I have the following tmux status bar configuration:
```
# configure status-line core
set -g status-utf8 'on'
set -g status-attr 'none'
set -g status-bg 'colour236'
set -g status-left-attr 'none'
set -g status-left '#(tmux-status left `tmux display -p "#{client_width}"`)'
set -g status-right-attr 'none'
set -g status-right '#(tmux-status right `tmux display -p "#{client_width}"`)'
# configure window list status-line component
set -g status-justify 'centre'
setw -g window-status-format '#(tmux-status center `tmux display -p "#{client_width}"`)'
setw -g window-status-current-format '#(tmux-status center-current `tmux display -p "#{client_width}"`)'
setw -g window-status-separator ''
```

I have a bash script that returns tmux status bar formatting like:
```
$ tmux-status left 178
#[fg=colour236,bg=colour103] #S ⮁ #F #[fg=colour103,bg=colour239,nobold,nounderscore,noitalics]⮀#[fg=colour253,bg=colour239] thanx #[fg=colour239,bg=colour236,nobold,nounderscore,noitalics]⮀#[fg=colour244,bg=colour236] 192.168.200.236
```
In tmux 2.0, the variables output by the bash script used to be rendered properly. However, tmux 2.1 is no longer rendering the variables. Instead of the justified variables, the values `#S`, `#F`, `#I`, `#W` are output themselves. The variables work when used directly in the status bar, but not when output via a bash script.

Any way around this?

**Comment by nicm** [comment]
Works fine for me, please cut down your .tmux.conf into minimum example that doesn't work and show me that.

**Comment by drn** [comment]
Thanks for the reply! Will do - will get back to you tomorrow

**Comment by phyber** [comment]
This will render the string `#30T` instead of the pane title limited to 30 chars. This used to work in tmux 2.0.
```
set -g set-titles on
set -g set-titles-string '#T'
setw -g window-status-format '#F#I:#30T'
setw -g window-status-current-format '#F#I:#30T'
```
Changing the `#30T` to `#{=30:T}` will render nothing at all. Removing the `30` and just having it use `#T` will work just fine. Or using `#{=30:pane_title}` will work just fine.

In my case, `#F` and `#I` render correctly at all times.

**Comment by nicm** [comment]
#nnX has been retired and replaced with #{=nn:foo}

**Comment by phyber** [comment]
I am happy with that answer and will update my configs. Thanks. If the retirement of `#nnX` is mentioned in the `CHANGES` somewhere, apologies for wasting your time. I did check the Incompatible/Deprecated Changes sections before posting.

**Comment by nicm** [comment]
I don't know if it was, it happened by mistake and nobody noticed for
ages and it is not worth adding back.

**Comment by nicm** [comment]
Oops reopen, someone else hijacked this issue not the original person.

**Comment by drn** [comment]
Hey @nicm,

Got around to checking out the minimal configuration necessary to reproduce it:

tmux.conf:
```
set -g status 'on'
set -g status-left '#(~/status)'
```
~/status
```
echo "#S > #F"
```

If i change `set -g status-left '#(~/status)'` to `set -g status-left '#(echo "#S > #F")'` the variables are picked up.

Maybe I'm doing something odd. Any thoughts?

**Comment by nicm** [comment]
Hmm, yes this doesn't work anymore. Try this please:

diff --git a/format.c b/format.c
index acfcb53..6b1ef29 100644
--- a/format.c
+++ b/format.c
@@ -244,7 +244,7 @@ format_job_get(struct format_tree *ft, const char *cmd)
 	if (ft->flags & FORMAT_STATUS)
 		fj->status = 1;
 
-	return (fj->out);
+	return (format_expand(ft, fj->out));
 }
 
 /* Remove old jobs. */
@@ -781,6 +781,8 @@ format_expand(struct format_tree *ft, const char *fmt)
 			memcpy(buf + off, s, slen);
 			off += slen;
 
+			free(s);
+
 			fmt += n + 1;
 			continue;
 		case '{':

**Comment by drn** [comment]
Thanks for taking a look at this. The changes solve my issue!

**Comment by nicm** [comment]
This should be changed now.
