### ISSUE TITLE
Continuation of stopped process in tmux

### ISSUE THREAD

**Issue by george-b** [tmux/tmux#1520]
I posted the following to -misc and although this isn't an issue I think this may be a better channel.

> It appears in handling SIGCHLD if the child is stopped due to SIGTSTP
> or SIGSTOP then it is continued. Indeed screen appears to do the same.
> Could someone kindly explain to me why this is done?
> 
> I ask as dvtm (another terminal multiplexer) hits an issue on MacOS
> where what would be called "panes" in tmux parlance hang on the shell
> exit due to being stopped. As to why the shells end up stopped on MacOS
> is something I've yet to fiugre out.
> 
> Many thanks,
> George

**Comment by george-b** [comment]
For example if you were to `echo $$` in one pane, then in another pane `kill -SIGSTOP` that PID it doesn't stop, or at least it's continued.

**Comment by nicm** [comment]
What use is it if it is stopped?

**Comment by george-b** [comment]
I don't take issue with the behavior but I'd like to understand why tmux takes this "responsibility" - for lack of a better term - to continue the process. The fact that screen also does this made me think there may be a specific reason that terminal multiplexers do this?

**Comment by nicm** [comment]
There is no other reason AFAIK.

**Comment by george-b** [comment]
Huh OK, thanks for the quick replies!
