### ISSUE TITLE
tty: top-left part of the screen doesn't refresh after window switch

### ISSUE THREAD

**Issue by nycko123** [tmux/tmux#1521]
### **platform**
ArchLinux
kernels: 4.19.arch1-1 and custom manually built 4.19 from sources
tmux: 2.8
terminal: tty
shell: bash
outside tmux: printenv TERM = linux
inside tmux: printenv TERM = screen

new test user without any ENVIRONMENTS set
### **steps to reproduce**
1. start tmux in tty (rich config or without any)
2. add a pane (vertical or horizontal)
3. add new window, switch to it and print anything in it (cat a file, journalctl -f, etc.)
4. switch back to window 0
5. pane 0 has a part of the output from window 1

### **logs**
tmux -vv -Ltest -f/dev/null new
[tmux-server-988.log](https://github.com/tmux/tmux/files/2544874/tmux-server-988.log)

### **exceptions**

- the issue does not exist on above kernels when using xserver terminal emulators
- the issue does not exist on kernels 4.18.16 and below (tty, xserver)

**Comment by nicm** [comment]
So if you change kernel version, the problem disappears? Sounds like a bug
in their terminal implementation.

**Comment by nycko123** [comment]
Yes, everything works great on kernels 4.18.16 and below.
Arch's kernel config of 4.19 doesn't differ from the 4.18.16 one, so maybe there was a change in the kernel upstream KMS method or in the way framebuffer works.
I have no knowledge or experience to check that

**Comment by nicm** [comment]
What do both of these show?
~~~~
printf 'abcdefghi\033[6D\033[Kxyz\n'
printf 'abcdefghi\033[6D\033[1Kxyz\n'
~~~~

**Comment by nycko123** [comment]
```
abcxyz
abcxyzghi
```

**Comment by nicm** [comment]
Seems fine. I don't know then, you will need to ask the kernel maintainers.

**Comment by nycko123** [comment]
Sure, will do. Thank you for your time.

**Comment by nycko123** [comment]
Please consider re-opening this issue. This bug is not Arch Linux specific. It happens on other distributions with kernel 4.19 too.

https://raw.githubusercontent.com/nycko123/ArchLinux/master/ss/tmux-bug/1.png
https://raw.githubusercontent.com/nycko123/ArchLinux/master/ss/tmux-bug/2.png
https://raw.githubusercontent.com/nycko123/ArchLinux/master/ss/tmux-bug/3.png

**Comment by nicm** [comment]
Right but it still seems like a kernel bug not a tmux bug, right?

**Comment by nicm** [comment]
There is nothing in the tmux logs that shows it sending anything incorrectly, it clears the existing content as expected, in the same way as every other terminal. And there is no way that would change purely based on kernel version. It seems very likely to be a terminal problem. Your best bet is to report it to the terminal maintainers.

If I could reproduce I could try to figure out what escape sequence it is handling incorrectly but there is no point in me faffing around to get a 4.19 kernel just for that.
