### ISSUE TITLE
set-window-option -g mode-fg black doesn't work

### ISSUE THREAD

**Issue by alexsxs** [tmux/tmux#1523]
Hi,
since the last update, the line `set-window-option -g mode-fg black` doesn't work anymore.
If i put `white` instead of `black`, it's work fine.
I didn't change anything, it happened suddenly.
Any solution ?
Tranks

**Comment by nicm** [comment]
Am I meant to guess what versions  you updated from and to?

**Comment by alexsxs** [comment]
in fact, it happened without updating. So I just updated version 2.8 and the problem is still there.

**Comment by nicm** [comment]
Works for me.
