### ISSUE TITLE
tmux can't copy long context text in copy-paste-mode

### ISSUE THREAD

**Issue by stardiviner** [tmux/tmux#1524]
When I copy very long text about 150 lines in copy-paste-mode. KDE clips only get half of the copied text. Don't know why, maybe tmux issue, maybe KDE clipboard limitation. But I tried very big text in program kate to copy and paste under KDE clipboard, no problem. So I think this might be tmux problem.

**Comment by prasadbiarca** [comment]
I see the same issue:
Copying(Command+c) huge text from System text file containing 1000 lines and pasting(Command+v) into one of the tmux pane window. The moment I press Command+v, vi editor stays in Insert mode in VI editor. I releases after few minutes and pasting the text. But the pasted text is not in proper format.

**Comment by prasadbiarca** [comment]
For this to work properly I have to copy the huge text from a non-tmux window and switch back to tmux pane and utilise it. Please let me know if you need any other info. This is definitely a difficulty using tmux for copy-paste

**Comment by nicm** [comment]
Open a proper issue please.
