### ISSUE TITLE
Custom-layout no longer honours pane split/placements (2.8+ including tmux-next)

### ISSUE THREAD

**Issue by ThomasAdam** [tmux/tmux#1526]
Hi,

I'm leaving this here as an aid-memoir, but with tmux 2.8 and beyond (including tmux-next) I've noticed that the following custom layout no longer creates the same pane structure it used to:

```
selectl -ttask:task 4ada,237x79,0,0[237x67,0,0{156x67,0,0,5,80x67,157,0[80x27,157,0,19,80x22,157,28,20,80x16,157,51,21]},237x11,0,68,22]
```

Prior to whatever changed in tmux, this used to create several split panes. Now, with the above, this creates several horizontally-split panes which no longer matches the previous layout.

I haven't found time to dig into this to investigate why yet -- and I'm not likely to any time soon.  I know tmux-2.7 worked fine with the above.  But fails on 2.8 and tmux-next.   If no one beats me to it, I'll figure it out myself in due course.

Thanks,
Thomas

**Comment by nicm** [comment]
It looks like this to me, is this wrong?
~~~~
![aaa](https://user-images.githubusercontent.com/304243/56368560-9700c980-61ef-11e9-85d6-f9079fc58587.png)

**Comment by ThomasAdam** [comment]
See attached shell script.

At some point, when calling 'tmux new', I've tried to bound the size of the session with `-x` and `-y` -- this was missing off my original report, above.

I've just tried the script against tmux-1.7 and the layout is applied correctly.  But 1.8+ definitely seems to be broken.  I appreciate it's probably not the layout code as that has been stable for years -- perhaps it is the window sizing which is causing the problem?  Certainly, I need the `-x` and `-y` sizes to be applied as the layout depends on that.
[tmux-layout.sh.txt](https://github.com/tmux/tmux/files/3125516/tmux-layout.sh.txt)

**Comment by nicm** [comment]
This script has too many panes? If I comment one of them out (and add quotes around the layout string), it seems to work for me.
~~~~
--- tmux-layout.sh.txt  Mon Apr 29 20:23:56 2019
+++ tmux-layout.sh      Mon Apr 29 20:22:36 2019
@@ -11,4 +11,4 @@
 $TMUXC splitw -ttask:task
-$TMUXC splitw -ttask:task
-$TMUXC selectl -ttask:task f18c,176x46,0,0[176x38,0,0{92x38,0,0,6,83x38,93,0[83x11,93,0,7,83x8,93,12,8,83x17,93,21,9]},176x7,0,39,10]
+#$TMUXC splitw -ttask:task
+$TMUXC selectl -ttask:task 'f18c,176x46,0,0[176x38,0,0{92x38,0,0,6,83x38,93,0[83x11,93,0,7,83x8,93,12,8,83x17,93,21,9]},176x7,0,39,10]'

**Comment by ThomasAdam** [comment]
Hmm. There's definitely been a change somewhere. I don't think it's worth worrying about though.
