### ISSUE TITLE
Support panes for tmux find-window in full-screen mode

### ISSUE THREAD

**Issue by bryden** [tmux/tmux#1527]
# System information
Personally tested in 2.6 and confirmed by random reddit user that it also exists in 2.8.

Linux basinview 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux.

```
# $TERM are identical inside and outside of tmux. Using xfce4-terminal
echo $TERM
xterm-256color
```

# Steps to reproduce

1. Create two tmux windows.
2. In one of the windows, create multiple panes.
3. In the window with multiple panes, choose your favourite pane and enter into full-screen mode.
4. Use your keyboard shortcut for tmux find-window, and select your 2nd favourite pane from the multi-pane window.
5. Nothing happens, instead of showing the pane that you selected as you would expect, you're left on the initial pane.

4. b) Use your keyboard shortcut for tmux find-window, and select the other window that has no other panes.
5. Result is as expected. Newly selected window is focused and full-screen.

**Comment by nicm** [comment]
Works fine for me.

**Comment by bryden** [comment]
Can you confirm it works when attempting to switch between two panes? Between windows works fine for me too.

**Comment by nicm** [comment]
Yes...

**Comment by nicm** [comment]
Found another bug though.

**Comment by nicm** [comment]
Try this please, against master:
~~~~
Index: cmd-switch-client.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-switch-client.c,v
retrieving revision 1.54
diff -u -p -r1.54 cmd-switch-client.c
--- cmd-switch-client.c 18 Oct 2018 08:38:01 -0000      1.54
+++ cmd-switch-client.c 6 Nov 2018 14:52:42 -0000
@@ -113,8 +113,11 @@ cmd_switch_client_exec(struct cmd *self,
                if (item->client == NULL)
                        return (CMD_RETURN_NORMAL);
                if (wl != NULL) {
-                       if (wp != NULL)
+                       server_unzoom_window(wl->window);
+                       if (wp != NULL) {
+                               window_redraw_active_switch(wp->window, wp);
                                window_set_active_pane(wp->window, wp);
+                       }
                        session_set_current(s, wl);
                        cmd_find_from_session(&item->shared->current, s, 0);

**Comment by bryden** [comment]
I'm not sure what the diff does that you added, but I can confirm that the bug I reported is not present in master.

**Comment by nicm** [comment]
It doesn't work right, whether or not it is the same problem isn't very important.

**Comment by bryden** [comment]
What do you mean by it doesn't work right? What are the expected results and what are you seeing?

**Comment by nicm** [comment]
I have applied this fix now, please try master and let me know if you still see any problems. Thanks!
