### ISSUE TITLE
Weird screen output with copy-pipe

### ISSUE THREAD

**Issue by LunarLambda** [tmux/tmux#1528]
In ~/.tmux.conf, I have this line:

bind-key -T copy-mode-vi 'Y' send-keys -X copy-pipe 'xsel -ib'

For some reason, when pressing Y in copy mode, it writes `<Esc>]52;;`, followed by a base64 dump of the text I had selected, to the screen.. What's up with that? It happens with other programs, too, like xclip, or cat.

I'm on Ubuntu 18.04.1, using Mate-Terminal 1.20.0, and tmux 2.6

**Comment by nicm** [comment]
Use the correct TERM or turn set-clipboard off.

**Comment by LunarLambda** [comment]
Thank you! :)
