### ISSUE TITLE
run-shell mangling man pages

### ISSUE THREAD

**Issue by aurorabbit** [tmux/tmux#1529]
``uname -sp && tmux -V && echo $TERM``
```
Darwin i386
tmux 2.8
xterm-256color
```

Hi, I'd like to use ``C-prefix /`` to open a man page over the current pane. I understand ``run-shell`` provides this behaviour, but the way it is displaying control characters is unreadable.

It looks to me that bold characters are doubled (**NAME** becomes ``NNAAMMEE``) and underlined characters have an underscore prepended (_expression_ becomes ``_e_x_p_r_e_s_s_i_o_n``)

Configs on the internet all seem to use ``new-window`` for man pages, but it would be ideal to have it replace the current pane instead of opening a new one and directing away from the other panes.

I did find [this tmux config](https://github.com/com/x/blob/master/etc/tmux/170-bind#L10) that uses the run-shell exec man combo, but it calls to [a recursive shell script](https://github.com/com/x/blob/master/bin/x-tmux-man) that I couldn't grok. As far as I can tell it doesn't seem to do anything special.

Here is my config:

``.tmux.conf``
```tmux

bind-key R source-file ~/.tmux.conf

# doesn't make a  difference for me
#set -g default-terminal "screen-256color"

# doesn't exist in this version
#set -g utf8 on

# Prefix+/ to open a man page
bind-key / command-prompt -p (man) "run-shell 'exec man %%'"
#bind-key / command-prompt -p (man) "new-window 'exec man %%'"
```

Steps to reproduce
1.  ``tmux -Ltest kill-server``
1.   ``tmux -Ltest -f/dev/null new``
1.   Control+B ``:run-shell exec man tmux``

![run-shell "exec man %%"](https://user-images.githubusercontent.com/37997236/48159345-c77c2900-e289-11e8-8d09-d918fc25dc65.png)
![new-window "exec man %%"](https://user-images.githubusercontent.com/37997236/48159356-cb0fb000-e289-11e8-8ac8-7960bfc5b715.png)

**Comment by nicm** [comment]
That is how man shows markup. You may be able to pipe through col -b to
remove it. Or convince man not to send it, perhaps there is a flag.

**Comment by krader1961** [comment]
Like @nicm said that is how `man` indicates text should be bolded or underlined. Note that `run-shell` is really the wrong tool for the job as it does not run the `man` command an an "interactive" shell. That is, stdin and stdout are attached to a socket (or pipe) which will keep `man` from running the output through your pager. It's roughly equivalent to running `man tmux < /dev/null >x 2>&1` followed by `cat x` to display the output in the pane. In fact if you do the former then type `cat -evt x` you'll see why the output is displayed oddly when you do it via `run-shell`. Your pager (e.g., `less`) normally recognizes the way that `man` marks-up the output and turns it into actual bold and underlined chars. As @nicm said if you pipe the output through `col -b` it will strip the markup. You won't see bold or underlined text but you also won't see the artifacts from the markup.
