### ISSUE TITLE
FEATURE REQUEST: Way to colorize the tree in choose-tree

### ISSUE THREAD

**Issue by jamespharvey20** [tmux/tmux#1530]
tmux 2.8, on up to date Arch Linux.  Using bash running in terminator, and `TERM` is `tmux-256color`.  Color works perfectly fine everywhere that it's supported.

I'd love to be able to colorize choose-tree.  I mean the tree itself, as the preview is properly colorized, if there is any.  I'd like to be able to have lines with windows, panes, and processes colorized differently.  By "lines... colorized", I'll admit I'm not sure if I'd prefer the entire line including the left-most parts that are not part of the `choose-tree` `format` string, such as the shortcut, session names, node expansion `-` and `+` characters, and tree line drawings like `|-->`.

I can't find any screenshots of it colorized, or anyone discussing that they've done it.  I'm not seeing anything in `man tmux` for it, but I acknowledge I might be missing it.  I searched it for `status` and `style`.  I tried running `tmux choose-tree -F '<string>'` with a modified format string with embedded ANSI codes.  I changed the default of:

`#{?pane_format,#{pane_current_command} "#{pane_title}",#{?window_format,#{window_name}#{window_flags} (#{window_panes} panes)#{?#{==:#{window_panes},1}, "#{pane_title}",},#{session_windows} windows#{?session_grouped, (group #{session_group}: #{session_group_list}),}#{?session_attached, (attached),}}}`

To:

`#{?pane_format,#{pane_current_command} "#{pane_title}",#{?window_format,^[[31m#{window_name}^[[0m#{window_flags} (#{window_panes} panes)#{?#{==:#{window_panes},1}, "#{pane_title}",},#{session_windows} windows#{?session_grouped, (group #{session_group}: #{session_group_list}),}#{?session_attached, (attached),}}}`

(Note the `^[[` is: `CTRL+ESC` which displays as `^[`; followed by a `[`.  Copy/paste splits `^[` which is actually a single character into separate `^` and `[` characters.  So, if you copy/paste this, you'd need to delete the two characters and insert `CTRL+ESC`.)

But, the ANSI codes aren't having an effect, so they must not be supported in the format string.

I'll also note using `-F ""` showed the left-most parts of each line are not part of the format string.  (Shortcut, session name, `-`, `+`, `|-->`, etc.)

I think the best way to do this would be to add options like the other color options, but I'd be fine with having to modify the format string if ANSI codes became supported in it.

Going the options route, the current line is currently shown using `mode-style` (default black text on yellow background.)  This doesn't bother me, but `mode-style` is also used for the highlighting of the line counter in copy-mode.  Perhaps the coloring of these two things should be split, but again, it doesn't bother me.

If it was desired to not add new options, and go the ANSI codes supported in format string route, I'd be fine if ANSI codes were stripped from the current highlighted line and `mode-style` was used.

**Comment by nicm** [comment]
You would need to make it use #[] like everything else not escape sequences. It may not be much more than changing screen_write_puts/strlen to the cnputs/cstrlen variants in mode-tree.c and window-tree.c and window-client.c.

**Comment by ThomasAdam** [comment]
So here's something which works:

https://github.com/ThomasAdam/tmux/commit/9abf44232fd006c801e9210e152a4baf08ccf99a.diff

This effects all choose-* commands.

However, one of the limitations is that for some commands (like choose-tree) which have a tree display, the -F option applies after that which means you can't change the colour of the entire line.

One approach to fixing this might be to expose the *_DEFAULT_FORMAT options via formats themselves, that way you can do:

```
-F '#[bg=red]#{choose_tree_default_format}#[bg=default] Foo'
```

I'm not sure whether it's worth it though.

Anyway, James, give that diff a whirl and see if it works OK for you.

**Comment by nicm** [comment]
I'm not really sure what your limitation means - you can't change the colour of the shortcut keys and the tree structure lines? I don't see any necessity for people to be able to change the colour of parts that they can't change with -F.

Having the default formats available might be nice however so people can see and use them easily. It would make it nicer to do simple things like colour sessions, windows and panes differently without changing the text.

**Comment by nicm** [comment]
The default format could be the same format name for all modes using the same mechanism as window_copy_add_formats. But that means it is only useful inside the mode itself.

**Comment by nicm** [comment]
Actually it could be the same and use different names - just thinking to avoid moving the #defines.

**Comment by ThomasAdam** [comment]
Heh, yes -- I had noted that #defines potentially would need moving, but I think your suggestion makes sense.

And yes, I was referring to the inability to change the colour of the shortcut keys as this is prepended to the default format.  But as you point out, that's currently outside of -F's remit anyway.

Do you want me to have a stab at the "default format" format bit?

**Comment by nicm** [comment]
Sure that'd be good.

**Comment by jamespharvey20** [comment]
I rebuilt tmux using your `9abf44` patch, both using 2.8 and git HEAD (`g849d06c0`) , closed all of tmux, installed it, and tried it out.  Even tried it out in a fresh install in a VM.

It's still just displaying window names without color, ignoring the `^[` character and displaying the rest of the ANSI sequence like:

    (1)  |-> 0: [31mbash[0m* (1 panes)...

To get it working, were you running this?  (just with typing `CTRL+ESC` single characters instead of the `^[`)

    tmux choose-tree -F '#{?pane_format,#{pane_current_command} "#{pane_title}",#{?window_format,^[[31m#{window_name}^[[0m#{window_flags} (#{window_panes} panes)#{?#{==:#{window_panes},1}, "#{pane_title}",},#{session_windows} windows#{?session_grouped, (group #{session_group}: #{session_group_list}),}#{?session_attached, (attached),}}}'

Double checked that the patch applied properly, and with the git version:

    $ tmux -V
    tmux next-2.9

**Comment by nicm** [comment]
Don't use escape sequences use #[]...

**Comment by nicm** [comment]
Applied now, thanks!
