### ISSUE TITLE
Feature request: RGB colour support

### ISSUE THREAD

**Issue by tanc** [tmux/tmux#1531]
It would be great if tmux itself rendered in RGB so that a user can provide hex colours and have them used for things like pane backgrounds without them being converted to the closest 256 term colour. This is following on from #299. See also #709 and #315. Thank you for your consideration!

**Comment by nicm** [comment]
This has been supported for years.

**Comment by tanc** [comment]
Are there some docs which describe how to use RGB colour in tmux for pane backgrounds? In my tests on tmux 2.8 I was not able to get a hex value to show as a pane background, instead it approximated to the nearest 256 colour value.

**Comment by krader1961** [comment]
You terminfo definitions probably don't include true-color support. Putting these in my *~/.tmux.conf* works for me:

```
set-option -ga terminal-overrides ",xterm*:Tc:smcup@:rmcup@"
set-option -ga terminal-overrides ",screen*:Tc:smcup@:rmcup@"
set-option -ga terminal-overrides ",tmux*:Tc:smcup@:rmcup@"
```

The `smcup@:rmcup@` is to disable the "alternate screen" which is a feature I hate. You may want to leave that out.

**Comment by tanc** [comment]
Thank you @krader1961 for the help. The background is correctly coloured (RGB) now but since that change I'm getting oddities where the background comes through white or yellow sometimes, both in vim and terminal panes, see screenshot:

![odd background colour](https://cl.ly/7286aee712bb/Image%202018-11-12%20at%208.36.25%20am.png)

Any ideas?

**Comment by nicm** [comment]
I think this is a bug, show your config please.

**Comment by tanc** [comment]
Thanks for the response @krader1961 but I don't have `colour256` set anywhere, maybe its not clear in that screenshot but it says `bg=colour236`

@nicm thanks for taking a look, my config is here: https://github.com/tanc/dotfiles/blob/master/.tmux.conf

**Comment by tanc** [comment]
With `Tc` set and with `set -g window-active-style 'fg=default,bg=colour235'` instead of a hex value I don't get those visual oddities. They only occur when specifying a hex value for the bg colour.

**Comment by nicm** [comment]
What terminal are you using?

**Comment by tanc** [comment]
I'm using iTerm2 but I just realised this issue only happens when using tmux with mosh, something like `mosh 192.168.1.27 -- tmux a`

**Comment by nicm** [comment]
This sounds like a bug in mosh.

There seems to be a similar bug in xterm.

My guess would be that it is not using the background colour correctly for SU. What do these show:
~~~~
printf '\033[H\033[48;2;255;0;0m\033[3S\033[0m'
printf '\033[H\033[44m\033[3S\033[0m'
printf '\033[H\033[48;5;88m\033[3S\033[0m'

**Comment by tanc** [comment]
The first one appears to print nothing, the second two colours:

![](https://cl.ly/8fe6c0008a65/Image%202018-11-14%20at%2012.14.21%20pm.png)

**Comment by nicm** [comment]
So they are not filling the background colour in correctly for scrolling
with RGB colours, xterm appears to have the same problem. You will need to
report this to the mosh developers.

**Comment by nicm** [comment]
This is how it should look:

![gt](https://user-images.githubusercontent.com/304243/48479615-bf7b3680-e7ff-11e8-9187-91506418db0c.png)

**Comment by tanc** [comment]
Excellent, I will do that, thanks for helping to debug

**Comment by tanc** [comment]
Sorted, turns out this is fixed in a development release of mosh 👍
