### ISSUE TITLE
Lost SIGHUP signals on OpenBSD?

### ISSUE THREAD

**Issue by nmeum** [tmux/tmux#1536]
On a single CPU system with OpenBSD 6.4 on amd64 a SIGHUP signal doesn't seem to be sent to all processes running in tmux windows of a tmux session when killing that session with `tmux kill-session`. This is only the case when quickly creating a session, killing it, creating a new session and killing it again. I am assuming that this caused by some kind of race condition and thus probably difficult to debug/reproduce.

I've created the following shell script to ease reproduction of this issue:

```
#!/bin/sh
set -x

for i in 1 2; do
        tmux new-session -d -s tmux-test \
          "/tmp/tmux-test/myscript.sh >>/tmp/tmux-test/log 2>&1"
        tmux kill-session -t tmux-test
done
```

And the script `myscript.sh` (save as `/tmp/tmux-test/myscript.sh`) which is started in the tmux sessions created by the above script.

```
#!/bin/sh

trap "echo received sighup ; exit" HUP

while :; do
        sleep 100
done
```

After running the first script one would expect the file `/tmp/tmux/test-log` to contain the line `received sighup` twice (as two sessions are started). Unfortunately, it only contains it once. Additionally, one `myscript.sh` process is still left running (as it didn't receive the SIGHUP), verify with `ps u | grep myscript `.

To me this looks like a bug as I would expect that both process started in the separate tmux sessions receive the SIGHUP and thus write to the file and terminate. Maybe I am missing something obvious or misunderstand something entirely. It's obvious to me that tmux doesn't know if a signal was delivered successfully, however, shouldn't it `wait(3)` for all children to terminate?

I can reproduce this on OpenBSD 6.4 with the builtin tmux version and with tmux built from git HEAD (0fd73f238d235d497389e7f530945949dac6bcd2). I cannot reproduce this on Linux though.

**Comment by nicm** [comment]
What are you doing to make sure the "tmux kill-session" is guaranteed to run after the "trap"?

**Comment by nmeum** [comment]
> What are you doing to make sure the "tmux kill-session" is guaranteed to run after the "trap"?

That's a flaw indeed. The signal could be send to the `myscript` process before the signal handler was set. This would explain why only a single `received hup` shows up in the `log` file.

However, if the SIGHUP arrives before a signal handler was installed by `trap` the default action would be terminating the process, right? So this doesn't explain why one process is still running after receiving the SIGHUP, or I am missing something?

**Comment by nicm** [comment]
Which script process is still running? Is it the one that wrote to the file or the one that didn't? You can see if you make the trap write $$.

Is the sleep running?

**Comment by nicm** [comment]
Are you sure it is still running and not a zombie?

**Comment by nmeum** [comment]
> Which script process is still running? Is it the one that wrote to the file or the one that didn't? 

It's the one which didn't write to the file.

> Are you sure it is still running and not a zombie?

The state of the process as reported by `ps(1)` is `Ip`. So the sleep is running and it's not a zombie.

**Comment by nicm** [comment]
So the sleep process is running? Or just the script?

**Comment by nmeum** [comment]
Sorry, I assumed that sleep is a shell builtin (which it isn't). The sleep process is still running, yes.

**Comment by nicm** [comment]
Try running the shells with ktrace and see if they get HUP, if they do then do the same with the sleeps and see if they do. You can do eg "ktrace -f /tmp/ktrace.out.$$ sh myscript".

**Comment by nicm** [comment]
Show me the kdump from the sleep which didn't get HUP.

**Comment by nicm** [comment]
Your $$ would be the same for both parents, try putting $i in the ktrace
output file name as well.

**Comment by nmeum** [comment]
I updated the original comment.

> Show me the kdump from the sleep which didn't get HUP.

https://files.8pit.net/tmp/kdump-sleep.8872.txt

**Comment by nicm** [comment]
Show me the kdump for the two sh as well please. You should be able to get
them for both if you use different filenames (either add $i or escape $$ so
it is evaluated for the child not the top level shell).

**Comment by nmeum** [comment]
Here is a `script(1)` recording of a new run: https://files.8pit.net/tmp/tmux.typescript

ktrace.1 seems to be the one failing. After waiting 100s it looks like this: https://files.8pit.net/tmp/kdump.1

**Comment by nicm** [comment]
Show both please.

**Comment by nmeum** [comment]
They are both contained in the typescript. But here is kdump.2 https://files.8pit.net/tmp/kdump.2

**Comment by nicm** [comment]
Can you kdump with timestamps? kdump -R

**Comment by nmeum** [comment]
Didn't store the ktrace files from the last run. Generated new ones:

* https://files.8pit.net/tmp/kdump.R.1
* https://files.8pit.net/tmp/kdump.R.2

**Comment by nicm** [comment]
Do have a tmux session already running before starting your script?

If you don't, the tmux server will exit after the first kill-session and be restarted by the next new-session. Does it make any difference if you stop it exiting by having a third session already open (with a different name obviously)?

**Comment by nmeum** [comment]
It doesn't seem to make a difference. Even if a tmux session (with a different name) exists before running the script it still creates a process which only exits after 100s.

**Comment by nicm** [comment]
Yes, I don't think this is a tmux problem. Even if I start two entirely separate tmux servers, I see the same:
~~~~
set -x

T="./tmux"

S=$(mktemp)
trap "rm -f $S" 0

cat <<EOF >$S
trap "echo HUP \$\$ >>/tmp/log" HUP
$T -L\$1 wait -S \$1
ktrace -fktrace.sleep.out.\$1 sleep 100
EOF
rm -f /tmp/log

for i in 1 2; do
        $T -L$i new-session -d -stest$i "ktrace -fktrace.out.$i $SHELL $S $i"
        $T -L$i wait $i
        $T -L$i kill-session -ttest$i
done

**Comment by nicm** [comment]
I think this is either ksh or kernel issue.

With bash on OpenBSD and on Linux, both sleeps are left running. With mksh on Linux, both are killed.

**Comment by nicm** [comment]
If I add in both sleeps, it works.
~~~~
set -x

rm tmux*.log
T="./tmux -vv"

S=$(mktemp)
trap "rm -f $S" 0

cat <<EOF >$S
trap "echo HUP \$\$ >>/tmp/log" HUP
$T -L\$1 wait -S \$1
ktrace -fktrace.sleep.out.\$1 sleep 100 &
EOF
rm -f /tmp/log

i=1
$T -L$i new-session -d -stest$i "ktrace -fktrace.out.$i $SHELL -x $S $i"
$T -L$i wait $i
$T -L$i kill-session -ttest$i
#sleep 1

i=2
$T -L$i new-session -d -stest$i "ktrace -fktrace.out.$i $SHELL -x $S $i"
$T -L$i wait $i
$T -L$i kill-session -ttest$i
#sleep 1

**Comment by nmeum** [comment]
> I think this is either ksh or kernel issue.

Yeah, I agree. What do you think, should this be reported elsewhere? I personally don't have enough knowledge of the OpenBSD kernel (if it's indeed a kernel issue) to investigate this further.

**Comment by nicm** [comment]
It would be nice to think of a way to reproduce without tmux.

**Comment by nmeum** [comment]
```shel
#!/bin/sh

for i in 1 2; do
        sleep 100 &
        kill -HUP 0
done
```

**Comment by nicm** [comment]
I think this is a problem in ksh. This script is better I think:
~~~~
sleep 100 &
sleep 100 &
kill -HUP 0
~~~~
Sometimes one or both sleeps will be left and sometimes not.

If I instrument ksh, sometimes I see trapsig() being called with the PID that ends up being the sleep process. If this happens, a sleep is left behind. So I think if the HUP arrives after the shell calls fork() but before execve(), it is ignoring it - it seems like it looks at the running jobs but since it is not their parent it doesn't kill them (and it really needs to kill itself anyway).

I suspect this will be annoying and complicated to fix so I don't want to look at it any further right now. And it seems like a relatively minor problem in any case.
