### ISSUE TITLE
Improved faking of BCE

### ISSUE THREAD

**Issue by blueyed** [tmux/tmux#1537]
I've noticed that the faking of BCE appears to cause problems with Kitty, where mouse selection will contain the spaces to the end of the line, and the line ending does not appear to be recognized (https://github.com/kovidgoyal/kitty/issues/1137).  This happens when using `set -g default-terminal "tmux-256color"` (but not with "tmux"), or `setw -g window-style "bg=colour18"`.

In https://github.com/kovidgoyal/kitty/issues/1137#issuecomment-438523826 it was noted that Kitty has a protocol extension that allows for setting style in regions more easily: https://sw.kovidgoyal.net/kitty/protocol-extensions.html#setting-text-styles-colors-in-arbitrary-regions-of-the-screen

Is that something that tmux could make use of?

**Comment by nicm** [comment]
Not unless other terminals take it up. tmux will only clear with spaces when it has no other option anyway, any terminal that supports this should support BCE.
