### ISSUE TITLE
Italics broken in tmux next-2.9

### ISSUE THREAD

**Issue by vedantroy** [tmux/tmux#1539]
I am using Ubuntu 18 LTS, gnome-terminal, and tmux next-2.9 (compiled from source)

Italics is broken:

![tmux_sc](https://user-images.githubusercontent.com/8407819/48523556-e743bc00-e84a-11e8-9731-9f3d7d585163.png)

Outside of tmux,` $TERM` is "xterm-256color" and inside of tmux, `$TERM` is "screen-256color". I don't know why $TERM is xterm-256color outside of tmux, considering I don't have xterm installed. I probably accidentally changed the value of $TERM.

The relevant portion of my .tmux.conf is:
`set -g default-terminal "screen-256color"`

Here is the log file:

[tmux-server-8906.log](https://github.com/tmux/tmux/files/2583278/tmux-server-8906.log)

**Comment by vedantroy** [comment]
Update:

Changing set -g default-terminal "screen-256color" to set -g default-terminal "tmux-256color" fixes the italics issue but breaks vim.

Now when I launch vim, I get the following error:
![vim_tmux_sc_](https://user-images.githubusercontent.com/8407819/48524060-c0868500-e84c-11e8-90f3-29a30059948b.png)

![vim_tmux_sc_](https://user-images.githubusercontent.com/8407819/48524076-ced4a100-e84c-11e8-98be-d95125f2cbb8.png)

Not sure if this is a problem with tmux or vim.

**Comment by nicm** [comment]
Seems like your platform is missing the tmux terminfo entries, you probably need to update ncurses.

**Comment by vedantroy** [comment]
@nicm How do I update ncurses? I tried "sudo apt install libncurses5-dev libncursesw5-dev" but both of those packages were already up to date.

**Comment by nicm** [comment]
That is a question for your packing system.

Another option is to make your own: copy the screen one by doing "infocmp
-x screen-256color >file" then edit file to replace screen by tmux, then
install it with "tic -x file".

**Comment by nicm** [comment]
Or install this with tic -x: [tmux.txt](https://github.com/tmux/tmux/files/2588842/tmux.txt)

**Comment by nicm** [comment]
I don't know, any platform with ncurses 6.1 should have the tmux terminfo entry.

**Comment by vedantroy** [comment]
It may be worth noting that typing "infocmp tmux-256color" outputs:
```
#	Reconstructed via infocmp from file: /home/vedantroy/anaconda3/share/terminfo/t/tmux-256color
tmux-256color|tmux with 256 colors,
	am, hs, km, mir, msgr, xenl,
	colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
	acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=\r,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
	cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
	dl=\E[%p1%dM, dl1=\E[M, dsl=\E]0;\007, ed=\E[J, el=\E[K,
	el1=\E[1K, enacs=\E(B\E)0, flash=\Eg, fsl=^G, home=\E[H,
	hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
	il=\E[%p1%dL, il1=\E[L, ind=\n, indn=\E[%p1%dS,
	invis=\E[8m, is2=\E)0, kDC=\E[3;2~, kEND=\E[1;2F,
	kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D, kNXT=\E[6;2~,
	kPRV=\E[5;2~, kRIT=\E[1;2C, kbs=^H, kcbt=\E[Z, kcub1=\EOD,
	kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA, kdch1=\E[3~,
	kend=\E[4~, kf1=\EOP, kf10=\E[21~, kf11=\E[23~,
	kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q, kf15=\E[1;2R,
	kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\E[1~, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m,
	ri=\EM, ritm=\E[23m, rmacs=^O, rmcup=\E[?1049l, rmir=\E[4l,
	rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
	rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p5%t;2%;%?%p7%t;8%;m%?%p9%t\016%e\017%;,
	sgr0=\E[m\017, sitm=\E[3m, smacs=^N, smcup=\E[?1049h,
	smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m, smul=\E[4m,
	tbc=\E[3g, tsl=\E]0;, vpa=\E[%i%p1%dd,

```
inside and outside of tmux. I also uninstalled Anaconda, but the problem remains.

**Comment by nicm** [comment]
What do the vim developers say?
