### ISSUE TITLE
Emacs rectangular selection

### ISSUE THREAD

**Issue by MiJyn** [tmux/tmux#154]
Apparently rectangular selection is possible via vi-mode, but I'm wondering if it would be possible to implement it for emacs keys (C-x space)?

**Comment by nicm** [comment]
Yes it works in emacs too.

**Comment by MiJyn** [comment]
I haven't been able to find the option ... how do you invoke rectangular selection in copy mode with emacs keybindings then?

**Comment by nicm** [comment]
Press R.

**Comment by MiJyn** [comment]
Ah thank you! I looked everywhere for this, and was unable to find =/
