### ISSUE TITLE
colo scheme question

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#1541]
Hi, I run KDE/Konsole with color scheme "linux color" which had a slight grey background that I like because it lowers the contra and is easier on the eyes.

This has the unfortunate effect of making selection close to unreadable in Tmux. Had I chosen the black background it would look clear and crisp.

I have copied a color scheme in .config/ranger/colorschemes/myscheme.py and in ranger console run "set coloscheme nadim".

I don't get any change, I am probably not changing the right variables; there is no documentation about which one is the selection bar, AFAIK, any tips?

![screenshot_20181115_175839](https://user-images.githubusercontent.com/45409/48568926-cb9aed00-e900-11e8-80af-10af33b07f4f.png)

**Comment by nicm** [comment]
What does this have to do with tmux?

**Comment by nkh** [comment]
You're absolutely right, I posted in the wrong project (next tab in the browser) :)

thank you for your patience.
