### ISSUE TITLE
find-window or choose-tree fails silently when in copy mode

### ISSUE THREAD

**Issue by ScottRochford** [tmux/tmux#1542]
If you attempt a find-window or choose-tree when in copy mode, it just fails silently.

In my opinion this behaviour is illogical and unexpected; I'd expect it to just switch from copy mode to the window browser, and return to that pane copy mode when a selection is made or cancelled.

(I haven't tried 2.8 yet, apologies if this behaviour has recently changed)

**Comment by nicm** [comment]
I don't think a stack of modes would be particularly hard to add.

**Comment by nicm** [comment]
Well, there are a couple of bits that are fiddles:
- window_copy_init turns off reading from the pane, obviously window_copy_free doesn't want to turn it on again if there is another copy mode lower on the stack. A reference count would probably be the easiest thing to do.
- clock mode has a timer, this needs to do nothing if that mode is not top of the stack.
- Not sure about wp->searchstr.
Also everything in the modes looks at wp->mode and wp->modedata, changing all this to another object will be a big churn.

**Comment by nicm** [comment]
Added to TODO file.

**Comment by nicm** [comment]
This is done by https://github.com/tmux/tmux/commit/3f6bfbaf2babcc7f08f628a82ff31b0b52014e58.

**Comment by ScottRochford** [comment]
Thanks again Nicholas, looks great so far, after some cursory testing!
