### ISSUE TITLE
new-window no longer returns error if window already exists

### ISSUE THREAD

**Issue by scfarley** [tmux/tmux#1544]
In previous versions of tmux, attempts to create a new window with the same index would return an error.  Starting in v2.8, it just creates a new window.  Since the man page still says that an error will be returned, this appears to be a regression.

Details:
- tmux version:  v2.8 (from ports) and a7da2357a512d5a325aa12ca0d544df85530a4d3
- OS:  FreeBSD 11.2-STABLE r340347
- Terminal (outside / inside):  xterm-256color / screen-256color

Steps to reproduce:
- Run in a clean environment without a configuration file.  The Git checkout was built and run within a poudriere environment.
- Create a new window with the same name two times:
  ```shell
  ./tmux new-window -d -t 42
  ./tmux new-window -d -t 42
  ...
  ```

Expected results:
- Only one new window with the index of `42` will exist.  The first step creates a window, and the second step does not create a window yet returns an error.

Actual results:
- Two (or more) windows are produced.  The first is produced with the requested index.  Subsequent windows are created starting at the first open index.

EDIT:  updated to reflect that it was the `-t` option that was failing and not the `-n` option.

**Comment by nicm** [comment]
Are you sure you aren't mixing up new-window and new-session? Or window
names and indexes? There has never been any requirement that window names
be unique.

**Comment by scfarley** [comment]
I could very well be confused.  However, this is from the documentation for `new-window`:
```man
...
If -d is given, the session does not make the new window the
current window.  target-window represents the window to be
created; if the target already exists an error is shown, unless
the -k flag is used, in which case it is destroyed.
shell-command is the command to execute.  If shell-command is not
specified, the value of the default-command option is used.  -c
specifies the working directory in which the new window is
created.
...
```

The man page says it will report an error.  Also, tmux used to report an error that the window already existed when I did this in the past.

**Comment by nicm** [comment]
But target-window is -t not -n?

**Comment by scfarley** [comment]
To see if `-t` is the one failing, I just tried the following and received no errors:
```shell
tmux new-window -t 50
tmux new-window -t 50
```

**Comment by nicm** [comment]
Yes -t should fail and currently doesn't.

**Comment by yggi49** [comment]
I noticed this as well, and I would like to see the old functionality back.

**Comment by nicm** [comment]
Sorry for the long delay to look at this.

It looks like assigning the index just went missing from the case where the window exists. Please try this:
~~~~
diff --git a/cmd-find.c b/cmd-find.c
index 67f6dbe8..3c0085e0 100644
--- a/cmd-find.c
+++ b/cmd-find.c
@@ -453,6 +453,7 @@ cmd_find_get_window_with_session(struct cmd_find_state *fs, const char *window)
 		if (errstr == NULL) {
 			fs->wl = winlink_find_by_index(&fs->s->windows, idx);
 			if (fs->wl != NULL) {
+				fs->idx = fs->wl->idx;
 				fs->w = fs->wl->window;
 				return (0);
 			}

**Comment by nicm** [comment]
I have applied this, please let me know if you see any problems.
