### ISSUE TITLE
split-window/new-window behaviour changed when PWD differs from caller current directory

### ISSUE THREAD

**Issue by mikecrowe** [tmux/tmux#1549]
Consider running the following at a shell prompt in a tmux session:

```
cd /
PWD=/etc tmux split-window
```

With tmux 2.3 (Debian 9) the shell in the new split ends up with its current directory set to `/`, whereas with tmux 2.8 (Debian 10ish) the shell in the new split ends up with its current directory set to `/etc`.

Unfortunately, this breaks processes (such as openembedded's terminal.py) which change the current directory but don't change PWD.

This change in behaviour may relate to https://github.com/tmux/tmux/issues/1151 . It's probably a fact of life, but I thought that it's probably work documenting here for the benefit of others suffering from the problem.

**Comment by nicm** [comment]
We should probably only use PWD if it points to the same place as getcwd(). Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/2607061/x.diff.txt)

**Comment by mikecrowe** [comment]
I tested that change on top of the current master and it fixed the problem I originally reported. I also tested running split-window with my current directory being a path containing a symlink and the path was correctly preserved (rather than being rewritten by realpath or similar.)

Thanks!

Mike.

**Comment by nicm** [comment]
Applied now, thanks!
