### ISSUE TITLE
2.1: Missing backwards compatibility

### ISSUE THREAD

**Issue by anonimal** [tmux/tmux#155]
Quite an abrupt feature change or bug. If it's a new feature, then it has not been documented (or I can't find the documentation).
```bash
$ cat foobar.sh
#!/bin/bash
_foo="/bin/foo"
_bar="/bin/bar"
window_split() {
  tmux new-window "$1"
  tmux split-window -d "$2"
  tmux rename-window "$3"
  # Same results:
  # tmux new-window "$1" \; split-window -d "$2" \; rename-window "$3"
}
window_split "$_foo" "$_bar" "foo/bar"
#EOF
$ pidof tmux>/dev/null && if [ $? -eq 0 ]; then tmux attach; else tmux new ./foobar.sh; fi
[exited]
$
```
Where as in 2.0, a tmux window would appear and both foo and bar would be active in separate panes. This approach has worked for as long as I can remember.

Note: this problem only exists *when called from a script*. When issuing tmux commands directly on the cli (within an open session) there appears to be no issue.

**Comment by nicm** [comment]
The way the current pane is resolved changed, for commands run from a pane inside tmux it is always the pane where that command is run. It might change again, it is better in some ways but not as good in others (your example is one) so I haven't decided. It is better to be precise with the targets in scripts, perhaps something like:

P=$(tmux neww -dP -n "$3" "$1")
tmux splitw -t$P "$2"
[ -n "$TMUX" ] && tmux switchc -t$P

**Comment by anonimal** [comment]
Ah, thank you, that's much better for now. Will documentation be updated to reflect the change or did I miss something that's already there?

**Comment by nicm** [comment]
The old behaviour was not documented either, I don't think it is worth it.

**Comment by anonimal** [comment]
Note: to get mouse functionality working again with Midnight Commander (it worked OOB with 2.0) while maintaining desktop copy/paste control of other windows within tmux, append the following:
```bash
#!/bin/bash
_mc="mc -x"
_mc=$(tmux neww -dP -n "mc" $_mc)
[ -n "$TMUX" ] && tmux switchc -t $_mc && tmux set-option -t $_mc mouse-utf8 on
```
Possibly related to #157
