### ISSUE TITLE
Non-breaking space in word-separators not working

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#1551]
If I add a character like "=" to the default list of `word-separator` characters then it treats "=" as a word separator in copy mode, but if I add a non-breaking space, it does not:

```
# This one works:
set -ga word-separators "="
# This one (which is a non-breaking space) doesn't work...
set -ga word-separators " "
```
Funnily enough, non-breaking spaces used elsewhere in the config *do* seem to work; for example:

```
bind-key b copy-mode\; send-keys -X start-of-line\; send-keys -X search-backward " "
```
(In case you're wondering what all this is about, I have a non-breaking space in my shell prompt so that I can use the binding to jump back to previous command(s)).

**Comment by wincent** [comment]
This is tmux master branch (was 645fe90, but I am going to rebuild and see if it still repros) on macOS. `$TERM` is tmux-256color.

**Comment by nicm** [comment]
word-separators is not UTF-8, you would need to change at least window_copy_in_set.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/2619087/x.diff.txt)

**Comment by wincent** [comment]
@nicm: tested it with `set -ga word-separators " "` and it works. Thanks!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
