### ISSUE TITLE
ctrl+l does not work in next-2.9 (though 'clear' does)

### ISSUE THREAD

**Issue by stuart-little** [tmux/tmux#1554]
I'm on Slackware Linux 14.2, originally running tmux-2.1. I have also compiled the latest git tree, now showing as next-2.9. The program appears as `tmx` on my machine because I changed the name of both the executable and the man page so as not to clash with the original Slackware installation.  

- output of `uname -sp`
Linux Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
- output of `tmx -V`
tmx next-2.9
- problem, briefly: 
Start any tmux session and press `ctrl+l`. This results in a new line rather than clearing the screen. The command `clear` works as expected, so this is not identical to [this previously-noted problem](https://github.com/tmux/tmux/issues/1235). 
- I have temporarily moved my usual config, so there's no config in use as I write this. 
- my terminal is `xterm`, and the $TERM variable is:
 in / out = `screen` / `xterm` respectively.
- log attached
[tmux-server-1699.log](https://github.com/tmux/tmux/files/2613519/tmux-server-1699.log)
---
Additional info: 

- `Ctrl+l` works fine in `screen`, even though the $TERM variable is still `screen`. 

- I have tried a minimal config file containing just 
```
set -as terminal-overrides ',*:indn@'
```
as per [prior](https://github.com/tmux/tmux/issues/1235) [advice](https://github.com/tmux/tmux/issues/1419) (two different links). This has no effect for me. 

- Any other key combination I bind to `clear-screen` in my `.inputrc` behaves identically (registers as new line), e.g. 

```
"\C-t": clear-screen
```
in `.inputrc` causes `tmux` to produce new lines upon pressing  `ctrl+t`. So this is not so much about ctrl+l apparently, but about `clear-screen` misbehaving in tmux.

**Comment by nicm** [comment]
From your log:

1543180327.520679 xterm  41: indn: (string) \\033[%p1%dS

Are you sure you restarted tmux entirely after changing .tmux,conf?

**Comment by nicm** [comment]
Actually, forget that. This seems to me to be a problem with your shell. There is no evidence of it sending anything to clear the screen when you press C-l:

1543180331.789449 writing key 0xc (C-l) to %0
...
1543180331.789962 input_parse: %0 ground, 30 bytes: \r\nchirvasitua@chirva-slack:~$

I don't know what shell you are using and I can't imagine how you could configure it so that it works outside tmux and not inside, but I would take a look at your shell config.

Does the same happen if you create a new user with default shell profiles?

**Comment by nicm** [comment]
Oh it is bash, I don't know what you can do to stop this working, are you sure you didn't mess up the key bindings?

**Comment by stuart-little** [comment]
> Oh it is bash, I don't know what you can do to stop this working, are you sure you didn't mess up the key bindings?

I'm hardly sure of anything, but mess them up in what sense? 

It is indeed bash. The behavior is identical for a new user created with

```
useradd -s /bin/bash USER
```
`Ctrl+l` works like a charm outside of `tmux`, but not inside.

**Comment by nicm** [comment]
Bash isn't asking tmux to clear, I think you will need to ask the bash
developers why that would be, I can't see anything obvious in their docs.

**Comment by stuart-little** [comment]
I see. Well, for what it's worth, since I tried just now, here's the log file for the brand new user created as mentioned above (also with `-m`, which I initially forgot about). 

[tmux-server-5398.log](https://github.com/tmux/tmux/files/2613570/tmux-server-5398.log)

**Comment by stuart-little** [comment]
As a follow-up to my previous message: 

I created yet another user whose default shell is `tcsh`, with exactly the same results. So I am doubtful that this is `bash`-specific.. Log attached again (though the lines referring to `C-l` look very similar). 

[tmux-server-7545.log](https://github.com/tmux/tmux/files/2613585/tmux-server-7545.log)

**Comment by nicm** [comment]
What does infocmp inside tmux show?

**Comment by stuart-little** [comment]
Here's something funny: 

If I start `screen` and then start a `tmux` session *inside* that, then `ctrl+l` works as expected. 

I'm attaching the log from that (
[tmux-server-11996.log](https://github.com/tmux/tmux/files/2613634/tmux-server-11996.log)
). It's definitely looking better, but I don't have the expertise to track down the problem.. 

Anyway, the relevant entries (as per your messages above) seem to be:

```
1543189510.301613 writing key 0xc (C-l) to %0
...
1543189510.302183 input_parse: %0 ground, 34 bytes: \033[H\033[J<PROMPT>
```
That (i.e. `\033[H\033[J`) is the `clear` escape sequence from the `infocmp` output attached previously. 

Just as a sanity check: issuing `printf '\E[H\E[J'` or `printf '\033[H\033[J'` in any `tmux` pane does work as expected (clears the screen and moves the cursor home).

**Comment by stuart-little** [comment]
All right, I believe I might be getting warmer here. 

The 'dumb terminal' warnings sent me on a chase that led to [this stackoverflow post](https://stackoverflow.com/questions/30002988/terminfo-seems-to-not-work-in-csh). 

It tipped me off that in some distros (Slackware explicitly referenced) have their shells rely on the older `termcap` rather than `terminfo`. It also suggested running 

`ldd which <SHELL>`

to check. Sure enough, doing that for SHELL={bash,csh,tcsh} on my system returns among other things a line of the form

```
libtermcap.so.2 => /lib64/libtermcap.so.2 (EXTRA GARBAGE)
```
These shells all misbehave under TERM=screen as well as xterm-256color and a number of others I've tried. 

On the other hand, `ldd which zsh` returns no `termcap` references. And indeed `zsh` accepts `ctrl+l` just fine inside `tmux` (i.e. it's not subject to the problems reported here).

**Comment by stuart-little** [comment]
I believe that was it. Apparently, one solution is as follows: 

- I took the `screen` terminfo entry as returned by `infocomp` inside `tmux` (attachment [above](https://github.com/tmux/tmux/issues/1554#issuecomment-441483237)). 
- I re-formatted it so as to conform to [termcap conventions](https://www.gnu.org/software/termutils/manual/termcap-1.3/html_chapter/termcap_3.html).
- changed `clear` to `cl` in that entry.
- finally, inserted it into my `/etc/termcap` file as the attached file. 

[new-termcap-entry.txt](https://github.com/tmux/tmux/files/2614124/new-termcap-entry.txt)

`ctrl+l` works fine inside `tmux` now, with `bash`, `csh`, whatever.

So I suppose you were right @nicm about the terminal being at fault. It just wasn't a single terminal, but rather several, taking their terminal capabilities from the wrong source..

**Comment by nicm** [comment]
OK great. You don't need to do it manually, you can use tic -C to translate terminfo to termcap.
