### ISSUE TITLE
pipe-pane stops respawn from working

### ISSUE THREAD

**Issue by KrisShannon** [tmux/tmux#1555]
tmux v2.6
Ubuntu 64bit
TERM=xterm-color

With remain-on-exit on, when a pane whos output is being captured with pipe-pane dies then respawn doesn't work correctly.  It appears that the tmux server is closing the PTY master side almost immediately.

**Comment by KrisShannon** [comment]
Using [tmux-1555.conf.txt](https://github.com/tmux/tmux/files/2622037/tmux-1555.conf.txt) I ran `tmux -vv -2uL test -f /tmp/tmux-1555.conf attach` and waited for the pane to exit.  Attempting to respawn and the pane exits again straight away.

The server log is [tmux-server-25611.log](https://github.com/tmux/tmux/files/2622044/tmux-server-25611.log)

**Comment by KrisShannon** [comment]
I also can't replicate this on my laptop which is OSX (also tmux 2.6)

I will try to get current master compiled on Ubuntu and re-test but that might be a while.

**Comment by nicm** [comment]
Applied now.
