### ISSUE TITLE
Cursor shape reverts from line to block when status line redraws.

### ISSUE THREAD

**Issue by ddickstein** [tmux/tmux#1557]
Problem
--
I have Vim configured to change my cursor shape from a block to a line when I enter Insert mode, but if the tmux status line redraws when my cursor shape is a line, it reverts to a block.

Ex. if I use a %I:%M%P clock in my status line, the problem happens every minute, and if I use a %I:%M%S%P clock, the problem happens every second. I have `set-option -sg status-interval 1` in my tmux.conf file.

System info
--
**Platform:** Linux
**Tmux version:** 2.7
**Terminal:** Xfce Terminal
**$TERM**: xterm-256color outside tmux, screen-256color inside tmux.

I am using the vim plugin https://github.com/jszakmeister/vim-togglecursor/ to emit the appropriate escape sequences for changing the cursor shape inside tmux. It works correctly aside from this problem, which I think is due to an escape sequence being emitted on the status line redraw event to redraw the cursor irrespective of its current shape.

**Comment by nicm** [comment]
This script appears to use the bypass escape sequence, so this will happen. You will need to make it send the escape sequences to tmux directly.

**Comment by ddickstein** [comment]
Can you give an example of how to do that? I have the following lines in my vimrc on my mac but they don't seem to work in my linux setup.

```
    let &t_SI="\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI="\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
    let &t_SR="\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=2\x7\<Esc>\\"
```

These lines not working was my initial motivation for using that script.

**Comment by nicm** [comment]
Get rid of the DCS Ptmux wrapper and make sure Ss and Se are set correctly for your terminal using terminal-overrides. Look at the existing xterm entry for an example, for VTE terminals this should work too.

**Comment by nicm** [comment]
Actually, the fact that tmux is resetting the cursor probably means it is already set up, you just need to get rid of the tmux stuff. Try something like:
~~~~
    let &t_SI="\<Esc>[2 q\\"
~~~~
The numbers are:
~~~~
CSI Ps SP q
          Set cursor style (DECSCUSR), VT520.
            Ps = 0  -> blinking block.
            Ps = 1  -> blinking block (default).
            Ps = 2  -> steady block.
            Ps = 3  -> blinking underline.
            Ps = 4  -> steady underline.
            Ps = 5  -> blinking bar (xterm).
            Ps = 6  -> steady bar (xterm).

**Comment by ddickstein** [comment]
works beautifully, thank you!

**Comment by unphased** [comment]
Hi, I am having trouble with this. Could someone show me exactly what needs to be set in tmux and what I can echo to try to test it? This has been driving me nuts for 3 days now. 

I've got this: 

```
❯ tmux show -s terminal-overrides                        
terminal-overrides[0] xterm-256color-italic:Tc
terminal-overrides[1] "xterm-256color-italic:Se=\033[2 q"
terminal-overrides[2] "xterm-256color-italic:Ss=\033[5 q"
```

**Comment by unphased** [comment]
I think my problem might be related to my terminfo file... 

```
xterm-256color-italic|xterm with 256 colors and italic confd for 24bit in tmux,
        sitm=\E[3m, ritm=\E[23m, khome=\EOH, kend=\EOF, kbs=\177,
        use=xterm-256color,
```

**Comment by unphased** [comment]
I've also found this: https://superuser.com/a/1033297/98199

**Comment by unphased** [comment]
I found my solution here: https://github.com/neovim/neovim/issues/6778#issuecomment-302944787

`set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'`
