### ISSUE TITLE
Mouse scrolling does not enter copy mode with tmux 2.1

### ISSUE THREAD

**Issue by robled** [tmux/tmux#156]
I am using the following config with tmux 2.1:

> set -g mouse on

Scrolling with the mouse wheel does not enter copy mode in this scenario.  100% reproducible.  With tmux 2.0 the following config works as expected:

> set-window-option -g mode-mouse on
> set-window-option -g mouse-resize-pane on
> set-window-option -g mouse-select-pane on
> set-window-option -g mouse-select-window on

**Comment by wlhlm** [comment]
#145
