### ISSUE TITLE
tmux active window reporting is incorrect with multiple ssh sessions

### ISSUE THREAD

**Issue by oneindelijk** [tmux/tmux#1560]
When I execute tmux 'send-message -p %I', tmux sometimes reports another window as the active one. The returned window number corresponds to the active window, marked in the output fomr 'tmux list-windows'.
I have multiple local sessions and multiple ssh session and I use byobu on top of tmux.
This behaviour might arise after switching windows around using 'tmux swap-window -t2 -t3' or similar.
I have nothing in the configuration except the defaults, so I don't know which files to attach.
Here is a copy/paste of my terminal (where you can see in the bottom, the tmux windows with window 2 the active one:
 
`uIn [759]: !tmux rename-window -t:= "test$(date '+%S')"
In [760]: !tmux display-message -p '#I'
1

In [761]: !tmux list-windows
0: test42# (1 panes) [211x57] [layout c962,211x57,0,0,5] @5
1: test17* (1 panes) [135x37] [layout 640f,135x37,0,0,10] @9 (active)
2: test#Z (2 panes) [211x57] [layout ec11,211x57,0,0[211x27,0,0,3,211x29,0,28,2]] @2
3: -# (1 panes) [211x57] [layout c961,211x57,0,0,4] @4
4: test37# (1 panes) [135x37] [layout c7c3,135x37,0,0,6] @6
5: -#- (2 panes) [211x57] [layout 720a,211x57,0,0{105x57,0,0,7,105x57,106,0,9}] @7
6: telegram# (2 panes) [211x57] [layout f203,211x57,0,0{105x57,0,0,1,105x57,106,0,8}] @1

In [762]: 
0:test42  1:test17  2:test*Z 3:-- 4:test37# 5:-# 6:telegram#`

**Comment by nicm** [comment]
Show logs please from reproducing with no config please.
