### ISSUE TITLE
Potential NPD in function cmd_capture_pane_pending in source file cmd-capture-pane.c

### ISSUE THREAD

**Issue by wurongxin1987** [tmux/tmux#1561]
![image](https://user-images.githubusercontent.com/4220002/49778880-48738800-fd42-11e8-9742-81cf5cfc2ee4.png)

The above code is in the function cmd_capture_pane_pending in the source file cmd-capture-pane.c. It will lead to potential NPD problem. In Line 87, the variable **line** is assigned with the value from the return value of function **EVBUFFER_DATA** (based on the macro definition, it should be function **evbuffer_pullup**). It is possible that the return would be null pointer. Then, it will be dereferenced in Line 93. Please check the following figure.
![image](https://user-images.githubusercontent.com/4220002/49778974-aef8a600-fd42-11e8-8d0e-a2582228d9dc.png)
![image](https://user-images.githubusercontent.com/4220002/49778995-ba4bd180-fd42-11e8-90b0-5659a0653ac3.png)

By looking into this, I suspect this should be a potential NPD bug. Can you help to confirm whether this is a true bug?

Thanks very much. Look forward to your reply.

**Comment by nicm** [comment]
This can't happen because size is always -1 so the expression can't be true:
~~~
#define EVBUFFER_DATA(x) evbuffer_pullup((x), -1)

**Comment by wurongxin1987** [comment]
> This can't happen because size is always -1 so the expression can't be true:
> 
> ```
> #define EVBUFFER_DATA(x) evbuffer_pullup((x), -1)
> ```



> This can't happen because size is always -1 so the expression can't be true:
> 
> ```
> #define EVBUFFER_DATA(x) evbuffer_pullup((x), -1)
> ```

I wonder whether it is possible that buf->total_len can be 0 ? If so, this still can happen. Right?

**Comment by nicm** [comment]
If it was then linelen would also be 0 and we would never dereference the
data pointer.

**Comment by wurongxin1987** [comment]
Yes. You are right. I made a mistake. Thanks.

**Comment by nicm** [comment]
Thanks anyway!
