### ISSUE TITLE
first keystroke is ignored after swith window

### ISSUE THREAD

**Issue by matthoop** [tmux/tmux#1563]
hi, I use the following key binding
```
bind -r h select-window -t :-
bind -r l select-window -t :+
```
that way, i can go to prev window with `Ctrl-b` + `h`, and thanks for `-r`, i can repeat `h` to cycle through windows quickly ( in `repeat-time`).
My problem is: when i get to my desired window and released `h`, and want to input something,  the first key strike is always ignored: for example, i input `vim`, only the `im` appeared, `v` key is ignored. BUT if i didnot input `vim` too fast, like wait 1 or 2 seconds and then input `vim`, everything is fine.

that key strike is ignored when i tested in tmux-2.8,  BUT in tmux-2.3 there is no such trouble.

**Comment by mckellyln** [comment]
Just curious, what is your tmux repeat-time and escape-time set to ?
And like with zsh there is also KEYTIMEOUT to consider.

**Comment by matthoop** [comment]
hi @mckellyln these options are defaults, the `.tmux.conf` file just contains two lines
```
bind -r h select-window -t :-
bind -r l select-window -t :+
```
tested with zsh and bash, both have the trouble.

**Comment by nicm** [comment]
Does this still happen with master!

**Comment by matthoop** [comment]
@nicm  wow, after building tmux from master, everything works as expected!
thank you! issue closed.
