### ISSUE TITLE
Incorrect cursor position.

### ISSUE THREAD

**Issue by alishir** [tmux/tmux#1565]
platform: Ubuntu 16.04
tmux version: 2.1
config: I deleted `~/.tmux.conf`
terminal: alacritty, xterm and ttys
$TERM before tmux: xterm-256color
$TERM in tmux: screen
shell: fish and bash

when I start tmux in fish shell the cursor shown in next two lines:

![image](https://user-images.githubusercontent.com/978306/50150087-352c6380-02d2-11e9-853d-52941501857d.png)

[tmux-server-4206.log](https://github.com/tmux/tmux/files/2704901/tmux-server-4206.log)

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by alishir** [comment]
I updated the issue.

**Comment by nicm** [comment]
tmux 2.1 was released three years ago. Does this still happen with 2.8 or master?

**Comment by alishir** [comment]
@nicm thanks, problem resolved by installing 2.8.
