### ISSUE TITLE
Still experiencing missing character after window change

### ISSUE THREAD

**Issue by hetmankp** [tmux/tmux#1567]
I am running a build of the latest tmux as of commit: c9d482ab489d5d57d481858091608ee1b32e46ab

The following config is required to reproduce:
```
set -g repeat-time 1000
bind-key -r C-n next-window
```

Steps to reproduce:
1. Create additional window with: `C-b`
2. Switch window with: `C-b C-n`
3. Next typed character will be missing (I'm typing `ls` in the attached logs).

Importantly, this will not occur if window is switched with `C-b n`, hence the additional configuration.

Logs: [tmux-server-8013.log](https://github.com/tmux/tmux/files/2692841/tmux-server-8013.log)

System:
```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux next-2.9
screen
```

**Comment by nicm** [comment]
Yes I think the check for the first table is wrong, please try this instead: [x.diff.txt](https://github.com/tmux/tmux/files/2705569/x.diff.txt)

**Comment by hetmankp** [comment]
That doesn't seem to have helped: [tmux-server-11584.log](https://github.com/tmux/tmux/files/2706092/tmux-server-11584.log)

**Comment by nicm** [comment]
Works for me, are you sure you are running the right build?

**Comment by hetmankp** [comment]
Hmm, I need to do some more poking around. It is indeed resolved with the minimal config I supplied to reproduce the issue but still broken when I run this with my full configuration file... and only when I log in remotely over SSH (but the issue disappears when I'm running tmux in a terminal locally on the machine). I might need a bit of time to investigate this.

**Comment by nicm** [comment]
OK let me know.

**Comment by hetmankp** [comment]
Just following up. After some further digging this appears to have been an issue with my shell startup setup and not a problem with Tmux at all. Sorry about the false trail.
