### ISSUE TITLE
prefix-o makes my maximized panes to its original size

### ISSUE THREAD

**Issue by rockflying** [tmux/tmux#1569]
I have two panes in the same window, and I zoom one to the max size (prefix-z).
When I switch to the other pane (prefix-o), the two panes change to their original size before zooming.
But I want to keep their zoomed size. How does that happen?
tmux 1.8 is OK.
Thanks a lot.

**Comment by nicm** [comment]
Yes this is how it is meant to work. You can do something like:

if -F '#{window_zoomed_flag}' 'rotate-window; resize-pane -Z' 'rotate-window'
