### ISSUE TITLE
Unable to forward mouse events in mouse mode

### ISSUE THREAD

**Issue by anowell** [tmux/tmux#157]
In trying to get the scrolling behavior I want in 2.1, I'm finding that if mouse mode is on, `send-keys -M` isn't forwarding keys to alternate screens.

```
set -g mouse on
bind -T root WheelUpPane if -Ft = "#{alternate_on}" "select-pane -t =; send-keys -M; display 'Sending mouse events not working'" "select-pane -t =; copy-mode -e; send-keys -M"
```

WheelUp in `vim` or `less` displays the message but doesn't scroll. Disabling mouse mode works fine for alternate screens, so I tried disabling and reenabling mouse mode if alternate_on, but that turned into a dead end. I've also tried this snippet I've stumbled into in a few places - same problem.

```
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
```

For now I'm working around this by sending NPage/PPage on wheel actions, but it seems less-than-ideal:
```
bind -T root WheelDownPane if -Ft = "#{alternate_on}" "select-pane -t =; send-keys NPage"
bind -T root WheelUpPane if -Ft = "#{alternate_on}" "select-pane -t =; send-keys PPage" "select-pane -t =; copy-mode -e; send-keys -M"
```

**Comment by anonimal** [comment]
Have you tried ```mouse-utf8``` or, more specifically:
```
set-option -t $_yourtarget mouse-utf8 on
```
(I was just about to comment about this in another ticket).

**Comment by anowell** [comment]
still no dice with `mouse-utf8`, but thanks for the suggestion.

**Comment by cHoco** [comment]
Here's the mapping I use, should cover almost all cases:

``` tmux
# Check if copy-mode or any mouse flags, then send mouse events
# or check if we're in alternate screen end send navigation keys (up, down)
bind -n WheelUpPane if-shell -Ft= '#{?pane_in_mode,1,#{mouse_any_flag}}' \
        'send -Mt=' 'if-shell -Ft= "#{alternate_on}" \
        "send -t= Up" "copy-mode -et="'
bind -n WheelDownPane if-shell -Ft = '#{?pane_in_mode,1,#{mouse_any_flag}}' \
        'send -Mt=' 'if-shell -Ft= "#{alternate_on}" \
        "send -t= Down" "send -Mt="'
```

**Comment by anowell** [comment]
Thanks @cHoco. That's a better experience. I made one minor tweak by appending `; send -Mt=` after the `copy-mode -et=` so that the first wheelUp also begins scrolling.

The issue of sending mouse events to alternate panes may still be valid, but I'm satisfied with this work-around for now.
