### ISSUE TITLE
How to replace a substring of `pane_current_path`?

### ISSUE THREAD

**Issue by huyvohcmc** [tmux/tmux#1570]
Tmux version: 2.8
Shell: zsh
OS: MacOS 10.14

I have a status right like this:
```
set -g status-right "#{s|/Users/xyz|~|:pane_current_path}"
```
It will replace the value of `$HOME` with `~` in the result of `pane_current_path`. But I am hardcoding the value of `$HOME` and don't know how to make it more consistent by using the env variable instead of the hardcoded string.

**Comment by nicm** [comment]
~~~~
set -g status-right "#{s|$HOME|~|:pane_current_path}"
