### ISSUE TITLE
A potential NPD bug in source file tty.c

### ISSUE THREAD

**Issue by wurongxin1987** [tmux/tmux#1571]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

In Line 518 of  source file tty.c, there is a potential NPD bug. The variable **s** is likely to be NULL and is dereferenced in Line 518. 
![image](https://user-images.githubusercontent.com/4220002/50393422-2aba1000-0791-11e9-867d-b9f444266bf5.png)

We further tracked how **s** comes from. 
![image](https://user-images.githubusercontent.com/4220002/50393446-40c7d080-0791-11e9-927d-92468c76fdb4.png)

As we can see, **s** is from the return value of **tty_term_string2**. The following is the code snippet of **tty_term_string2**. As we can see, it is from the return value of the library function **tparm** (libtinfo5). The code snippet of tparm is shown below. 

![image](https://user-images.githubusercontent.com/4220002/50393486-7967aa00-0791-11e9-83e9-dd891bf0fbd7.png)

![image](https://user-images.githubusercontent.com/4220002/50393525-ca779e00-0791-11e9-87fb-b8d961168246.png)
![image](https://user-images.githubusercontent.com/4220002/50393532-d8c5ba00-0791-11e9-9720-3603df9c5909.png)

To make the tparm return NULL, we only need to guarantee that (char *) tty_term_string(term, code) to be NULL. The code snippet is as followings. As we can see, we only need to guarantee that **term->codes[code].value.string==NULL**. 

![image](https://user-images.githubusercontent.com/4220002/50393566-0f033980-0792-11e9-999e-db1408851901.png)

I wonder whether the above bug is likely to occur. Thanks very much.

**Comment by nicm** [comment]
tty_term_string cannot return NULL.

**Comment by wurongxin1987** [comment]
> tty_term_string cannot return NULL.

Can it be guarantee that **term->codes[code].value.string** is never to be NULL.

**Comment by nicm** [comment]
If it was NULL then tty_term_has would return false.

**Comment by wurongxin1987** [comment]
> If it was NULL then tty_term_has would return false.

Thanks for your kindly help. Your answers are very helpful. Thanks again.
