### ISSUE TITLE
Lags as non-root user

### ISSUE THREAD

**Issue by philippetev** [tmux/tmux#1575]
Debian 9.6 x64
Outside tmux:
```
philip@buildroot:~$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.3
xterm-256color
```
Inside tmux:
```
philip@buildroot:~$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.3
tmux-256color
```
My config has only
`set -g default-terminal "tmux-256color"`
inside it.

Here's the log, according to your FAQ:
[tmux-server-11146.log](https://github.com/tmux/tmux/files/2729523/tmux-server-11146.log)

Now, the problem: there are pretty good lags, especially in ncurses-based programs like mc and that happens only when I start tmux as non-root user. The root user has no such issues, everything inside tmux, incl. mc, works without any lag. I suspect some kind of a permission issue, but I can't be sure.

Tried several different distros (Debian, Ubuntu, Ubuntu Server) in different versions (16.04.5, 18.04 for Ubuntu and 9.6 for Debian) in VM (VMWare and Hyper-X) and all of them seem to have the same problem.

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by philippetev** [comment]
Master?

**Comment by philippetev** [comment]
They both have the same issue.

**Comment by nicm** [comment]
Can you show the log from master please

**Comment by philippetev** [comment]
There it is:
[tmux-server-651.log](https://github.com/tmux/tmux/files/2729672/tmux-server-651.log)

**Comment by nicm** [comment]
What do you mean lag? Drawing or when you press keys?

**Comment by philippetev** [comment]
It take three or four times to get the mc top menu and when I open one of them and start cycling between them, the lags become even more visible. When I press the Esc key to close the top menu, part of the menu remains on screen (and it should not do this). Also, when moving between the files in the folder with the arrow keys, the cursor hops for one file not to the next one, but the file after the next one and so on.
So... yeah, drawing issues mostly.

**Comment by philippetev** [comment]
Ok, I think I've solved it. The cause for the lags turned out to be the combination **tmux**+**mc**+**gpm**.

While digging over the net, I came across several forum posts about an old feud between **mc** and **gpm**. It seems those two have quite a story together. **mc** has no objection at all about the currently used terminal, but **gpm** is another story: it seems it works best on all **xterm***-based terminals and the user may experience issues, running **gpm** on another one.

So, in short, solved the issue by adding the following to .profile:
```
mc_tmux()
{
[[ -z $TMUX ]] && mc -c || TERM=xterm-256color mc -c
}
alias mc=mc_tmux
```
This way **mc** starts in **tmux**, using the **xterm-256color** terminal and starts outside **tmux**, using the current terminal. Of course, quitting **mc** will revert **TERM** back to **tmux-256color** (for it's a shell in a shell thing).
You know, it seems event the latest Linux distributions (like Ubuntu Server 18.04.1) have this problem with this particular combination. 

You may now close this issue as it's solved.
