### ISSUE TITLE
Can't resize vim splits inside tmux

### ISSUE THREAD

**Issue by fabiosantoscode** [tmux/tmux#1576]
I'm having issues moving vim split boundaries around when terser is running on my terminal. Check the video to see what I mean.

 * Version: 2.1
 * uname -sp: Linux x86_64
 * Terminal: ElementaryOS Terminal, but I've had this happen with ubuntu terminal too.
 * $TERM: xterm-256color
 * tmux logs: probably irrelevant here
 * config: can reproduce without config

How to reproduce the bug: https://www.youtube.com/watch?v=nrgzHOsttRg&feature=youtu.be

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by fabiosantoscode** [comment]
Sorry @nicm I didn't read the notification.

I can't test it with master as I can't run tmux due to a library problem.

I'm getting:

`tmux: error while loading shared libraries: libncursesw.so.6: cannot open shared object file: No such file or directory`

I've built libncurses with wide support but nothing works yet.

Could you test it? All you have to do is type `:set mouse=a` in vim and do some splits.

**Comment by fabiosantoscode** [comment]
I used make install so I suppose the library got to where it was supposed to be. Is there a way to use linuxbrew to install master? Linuxbrew's build was working fine.

**Comment by fabiosantoscode** [comment]
Nevermind, found the correct options for building curses. Yes, can confirm the issue occurs with master.

6 was harder to install since ubuntu only packages ncurses 5

**Comment by nicm** [comment]
OK can you do this please with master:

tmux -vvLtest -f/dev/null new

Then start vim, reproduce the problem once, then exit vim and tmux and send
me the tmux-server* log file from the directory where you started tmux.

**Comment by fabiosantoscode** [comment]
Here is the only tmux-server* log I got: https://pastebin.com/raw/TSAtgb9Y

**Comment by nicm** [comment]
It appears that vim is sending only the SM 1000 (\033[1000h) escape sequence to enable standard VT200 mouse mode, which doesn't support dragging. For dragging (motion events) it will need to send SM 1002 (\033[1002h).

**Comment by nicm** [comment]
I suspect you want to use xterm2: http://vimdoc.sourceforge.net/htmldoc/options.html#'ttymouse'.

**Comment by fabiosantoscode** [comment]
Thanks, you've solved the issue for me!

But now tmux is going to `/` every time I open it. Was it that weird command?

**Comment by fabiosantoscode** [comment]
Nevermind, I was opening an old tmux session every time
