### ISSUE TITLE
UX/doc request: clarify session versus group

### ISSUE THREAD

**Issue by treyharris** [tmux/tmux#1577]
Linux x86_64
tmux 2.6
screen-256color

After trying to use tmux-resurrect and getting some unusual behavior I was trying to diagnose, I was looking at some output of `tmux list-sessions` that looked like this:

```
6: 20 windows (created Mon Jan  7 18:37:44 2019) [211x50] (group 24)
9-25: 20 windows (created Mon Jan  7 18:37:48 2019) [211x50] (group 24)
9-30: 20 windows (created Mon Jan  7 18:37:41 2019) [211x50] (group 24)
default: 20 windows (created Mon Jan  7 18:37:13 2019) [211x50] (group 24) (attached)
```

I got the idea from this that I had several sessions (one of them above attached) all connected to the same group, `24`, and spent quite a bit of time going down a rabbit hole based on this misconception.

However, on Freenode's #tmux channel they clarified for me that the above actually means I have a single session, called `24`, and multiple groups, one named `default` and the others named with numbers.

Since the output of `tmux list-sessions -F '#{session_name}: #{session_group}" is:
```
6: 24
9-25: 24
9-30: 24
default: 24
```
this, combined with the (rather sparse) documentation on groups (which is confined to `new-session` and `FORMATS`) led me to erroneously believe that `session_name` was... the session name, and `session_group` was the group name.

Its being _exactly the opposite_ is extremely surprising!

Since it's clearly far too late to change these variable names to more-obvious `#{group_name}` and `#{group_session}` (though perhaps aliases might be a good idea), I'd request the docs clarify this situation. (I'm assuming groups are something that got added later, and for historical reasons had to take variables set aside for sessions or something like that?)

Also, instead of the default format for `list-sessions` including `(group #{session_group})`, it really should be `(session #{session_group})` or maybe `(grouped as #{session_group})` if that captures the notion better? When I read `(group 24)`, it's very hard for me _not_ to read that as "this is a session in group 24"; while I'd expect `list-sessions` output's first column to be the session name, if it can't be and it must be last, it really should have something less easily confused than the word `group` before it.

I don't know to what extent the default output formats are frozen, but if they're not set in stone, I hope you'll give some consideration to the idea that the `list-session` format should really be swapped around so the thing at the beginning with the colon after it _is_ the `session` being `list`'ed. Without the helpful folks on IRC, I would never have figured this out on my own!

**Comment by nicm** [comment]
It is not the opposite, you have one group called 24 and four sessions.

**Comment by nicm** [comment]
The output is interpreted exactly as you thought and the format names are
correct, it sounds like you are confused about something different.

**Comment by treyharris** [comment]
Okay, it seems I was on the right track in the first place and there isn't a strange reversal in variable names versus state. Sorry for wasting time with this!
