### ISSUE TITLE
tmux highlight does not respect pane boundaries.

### ISSUE THREAD

**Issue by horcrux2301** [tmux/tmux#1578]
I used iTerm's feature to highlight error keywords in Preferences -> Profiles -> Advanced -> Triggers
However this is not working as expected as the highlight does not respect the pane boundaries.

<img width="922" alt="screen shot 2019-01-09 at 6 16 02 pm" src="https://user-images.githubusercontent.com/25867561/50901018-f145fd80-143c-11e9-9074-4eb378f9e6b6.png">

Expected working:-

<img width="1440" alt="screen shot 2019-01-09 at 6 29 58 pm" src="https://user-images.githubusercontent.com/25867561/50900901-97453800-143c-11e9-87a2-b0c45987a23e.png">

Actual working:-

<img width="1440" alt="screen shot 2019-01-09 at 6 30 24 pm" src="https://user-images.githubusercontent.com/25867561/50900923-a75d1780-143c-11e9-98e0-bdcb49173939.png">

Is there any way to fix this?

System Details
Darwin i386
tmux 2.8
screen-256color
OS - MacOS 10.12.6
iTerm 3.1.5

**Comment by nicm** [comment]
This is an iterm2 feature, maybe you should ask them?
