### ISSUE TITLE
Selection is missing last character

### ISSUE THREAD

**Issue by jaroslawr** [tmux/tmux#1579]
If I select the text `abcd` in copy-mode, starting with the cursor on the `a` and extending the selection from left to right, so that in the end the cursor blinks on the `d`, visually it looks like the whole of `abcd` is selected (colored background under blinking cursor) but `tmux paste-buffer` pastes `abc` only. The same thing works correctly when selecting right to left (starting from the `d`). I am using tmux 2.9 on Linux and I reproduced this without any config.

**Comment by nicm** [comment]
Selection with emacs keys does not include the cursor.

**Comment by jaroslawr** [comment]
OK, perhaps it would be possible to correctly indicate this visually then (normal background under the blinking cursor, rather than the background of an active selection) ?

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/2755657/x.diff.txt)

**Comment by jaroslawr** [comment]
Works great, thanks!

**Comment by nicm** [comment]
Applied, thanks!
