### ISSUE TITLE
tmux 2.1 no longer scrolls pane in mouse mode

### ISSUE THREAD

**Issue by danielb2** [tmux/tmux#158]
*Steps to reproduce*

1. set-option -g mouse on
2. ls enough output for it to be scrollable
3. use mouse to scroll

*Expected result*

contents should scroll (as in 2.0)

*Actual result*

Nothing happens.

**Comment by sjourdan** [comment]
See #145

**Comment by danielb2** [comment]
:+1:   thank you @sjourdan
