### ISSUE TITLE
overflow in implicit constant conversion warning?

### ISSUE THREAD

**Issue by danindiana** [tmux/tmux#1580]
Sorry for the multiple entries for this ticket. My desktop lost power during the write up.

**Comment by danindiana** [comment]
Wondering what this means? Attempting to build on raspberrypi 3. 

test/regress_util.c:1416:5: warning: overflow in implicit constant conversion [-Woverflow]
  {  4294967296, "Sun, 07 Feb 2106 06:28:16 GMT"} /* 2^32 */,
     ^~~~~~~~~~
test/regress_util.c:1418:3: warning: overflow in implicit constant conversion [-Woverflow]
  {253402300799, "Fri, 31 Dec 9999 23:59:59 GMT"} /* long long future no one can imagine */,
   ^~~~~~~~~~~~

**Comment by krader1961** [comment]
I don't have that file in my copy of this project. Nor anything remotely like it. Are you sure those warnings are from building tmux?

**Comment by krader1961** [comment]
As for the warning it means you're building on a system where those constant values cannot be represented in the data type (e.g., `int`) they're being stored in. For example, 4294967296 is 2^32 and cannot be represented in a 32-bit integer regardless of whether the var is signed or unsigned. Which implies you're trying to build code that requires a 64-bit int type and your system doesn't support that.

**Comment by danindiana** [comment]
OK. You know what you are right. It appears I attempted to get clone and make rather than just sudo apt-get install. It appears to be working on the Pi. I'll close this out. My bad. 

OS: Raspbian 9.6 stretch
 Kernel: armv7l Linux 4.14.79-v7+
 Uptime: 57m
 Packages: 1566
 Shell: 17284
 CPU: ARMv7 rev 4 (v7l) @ 1.2GHz

 RAM: 81MiB / 669MiB

**Comment by krader1961** [comment]
@danindiana FWIW, in the future when opening issues (not just in this project) you should include all relevant info about your environment. In this instance that would include a) the tmux version (or git commit ID), b) the architecture you're building on (e.g., "arm" or "arm64"), and c) the OS version you're running.
