### ISSUE TITLE
Possible double free vulnerability

### ISSUE THREAD

**Issue by yiyuaner** [tmux/tmux#1581]
In tmux/client.c, inside function `client_connect`:
![1](https://user-images.githubusercontent.com/20484362/51300473-e9c9ba00-1a23-11e9-8087-ef65361f8262.png)
In line 158,  `lockfile` is passed to function `server_start`, in that function (in tmux/server.c), `lockfile` is freed at line 214:
![2](https://user-images.githubusercontent.com/20484362/51300605-6fe60080-1a24-11e9-8bf6-c9d286e42728.png)
 After returning from `server_start`, if `locked = 1`, then there will be a double free on `lockfile` at line 162, client.c.

**Comment by nicm** [comment]
Look at server.c line 174...

**Comment by yiyuaner** [comment]
Got it, my mistake.
