### ISSUE TITLE
Feature Request: quickly select word & copy to command line at once.

### ISSUE THREAD

**Issue by fschaef** [tmux/tmux#1582]
In copy mode, sometimes, I just want to copy a file name to the current command line. It would be great to have a shortcut for

-- select the word that surrounds the cursor
-- copy it, paste it to the command line (may be adding a space)
-- return to the position where the word has been selected.

This way, the command line could be quickly be composed.

**Comment by mckellyln** [comment]
Hi,
I do something like this.  I have Alt-LeftMouse mapped to enter copy-mode if not already in copy-mode, select word, copy it, exit copy-mode and paste it to cmd line with an optional trailing space.  I find it very useful

**Comment by fschaef** [comment]
Yeah, I was actually hoping for something that would allow me to get rid of
the mouse.

I miss to see the advantage of your solution over simply marking with the
mouse and paste by the middle button.

Best Regards
Frank Schäfer

Mark Kelly <notifications@github.com> schrieb am Do. 17. Jan. 2019 um 14:13:

**Comment by mckellyln** [comment]
Hi,
Well ok yes, it is like X select and paste but with less key strokes/clicks - but try to map a key sequence to this.
I agree to return to copy-mode at the same place as before would be a nice feature.
Perhaps that can be done.  I need to figure out how to save and restore the cursor pos.

**Comment by fschaef** [comment]
Hi,

You know, what would be really cool?: if there was a file name copy mode,
that detects file names on the screen, highlights them and sets a different
marker such as ‘<A>’, ‘<B>’, ... after each. Then, to copy them one would
only have to press the according letter and the file name is copied to the
command line.

Best Regards
Frank


Mark Kelly <notifications@github.com> schrieb am Fr. 18. Jan. 2019 um 05:47:

**Comment by nicm** [comment]
Did you get this configured?

**Comment by mckellyln** [comment]
Hi, I'll post what I have soon.  I've just been away sorry.
