### ISSUE TITLE
No linting errors from eslint (using ALE) showing up in Tmux

### ISSUE THREAD

**Issue by wir3** [tmux/tmux#1583]
Version: Tmux next-2.9
Platform: Linux (Arch)
Terminal: URXVT
$TERM (outside): rxvt-unicode-256color
$TERM (inside): rxvt-unicode-256color
uname -sp && tmux -V && echo $TERM:
Linux unknown
tmux next-2.9
rxvt-unicode-256color

Description: When I'm running ALE and eslint, when I make an error a '>>' should be shown in the gutter. This works perfectly ouside of Tmux, but when I run Vim inside of Tmux, no errors are shown.
Config: No config, fresh install of Tmux.

I have tried multiple terminals, and tried Neovim and Vim. I have tried to manually create a sign using :Sign which DID create a sign in Vim (inside Tmux) and I've also tried to create a list of errors rather than putting them in the Gutter. Inside Tmux, no errors are logged to the Error Buffer.

Logs attached!

**Comment by wir3** [comment]
[tmux-out-6986.log](https://github.com/tmux/tmux/files/2770345/tmux-out-6986.log)

**Comment by nicm** [comment]
It is incorrect to use any TERM inside tmux except screen, screen-256color,
tmux, tmux-256color or a variant.

**Comment by wir3** [comment]
Sorry that's my mistake when testing to see if anything changed. I can confirm at the moment I am seeing $TERM: screen-256color

**Comment by nicm** [comment]
Can you show me two screenshots (not video) please, one of what you expect
to see and one of what you actually see, and also the corresponding server
log.

**Comment by wir3** [comment]
Hi there, sure. I've attached two screenshots and also the log that was generated. As you can see on line at the bottom, eslint is warning me "semi: missing semicolon" and there is a sign in the gutter visible. Inside Tmux, I get neither of these and as I said there is a ALE command to put errors in a new buffer rather than in the gutter and this also shows no errors listed.

![no-tmux-vim](https://user-images.githubusercontent.com/12523984/51345949-44026380-1a94-11e9-935e-66614ff3f925.png)
![tmux-vim](https://user-images.githubusercontent.com/12523984/51345952-44026380-1a94-11e9-9366-6624b8af1b54.png)
[tmux-server-5994.log](https://github.com/tmux/tmux/files/2770415/tmux-server-5994.log)

**Comment by nicm** [comment]
This text "semi: missing semicolon" is not in the log, nor does the ">>", so it appears the application is not printing it. This does not seem to be a case of tmux displaying the text incorrectly, it is not being sent it all.

I don't use vim and I don't know what the various bits you are using all do, but are you sure there is not something missing from the environment inside that they depend on? Different PATH? Your best bet may be to ask the vim developers.

**Comment by wir3** [comment]
Yes, this was my hunch that Tmux isn't receiving the error information at all. Without Tmux, everything is working as I'd expect, so it seems that Vim is set up correctly. I have also tried neovim and the issue persists.

I left a bug report on ALE at first, but all the plugin information from ALE came back okay (ALE can see the eslint stuff it requires, etc.).

The last thing it can be is Vim I guess! Thanks for looking into it! Love Tmux :)
