### ISSUE TITLE
rev_parse_find:11: command not found: dirname

### ISSUE THREAD

**Issue by m-talha-khan** [tmux/tmux#1587]
Linux unknown
tmux 2.8
rxvt-unicode

The installation went without a glitch. 
($ ./configure && make 
$ sudo make install)
I have run tmux with and without the config files but show's same error inside tmux window.
It keeps on displaying rev_parse_find:11: command not found: dirname 
and maxing my cpu and memory out. I have to use kill command to kill the process
the dirname its in my path which located in /usr/bin/dirname
  
image below for more information 
https://ibb.co/9NB9FkZ

**Comment by nicm** [comment]
Seems like a problem with some of your shell profiles to me. Are you
running got or some other VCS?

**Comment by m-talha-khan** [comment]
Thanks for the response,  No I am not running VCS on my current box, But other hand you are correct about my shell profile I just test it with root account and tmux is running fine.

I have to debug which profiles are causing this issue,
Thanks for pointing me in the right direction
I have open this thread because of dirname was in your code files...
https://github.com/tmux/tmux/search?q=dirname&unscoped_q=dirname

I will close this thread EOD est time
