### ISSUE TITLE
Remap default ctrl+b binding slows down tab completion

### ISSUE THREAD

**Issue by krystian-wojtas** [tmux/tmux#1588]
Thanks for tmux, it is a great tool. I would like to use it more.

But default tmux key binding ctrl-b is not practical for me. Then I change it to ctrl-i this way
```
$ cat ~/.tmux.conf
set  prefix C-i
bind -g C-i send-prefix
unbind C-b
```

Then I noticed that tab completion is much slower. Sometimes it is not received and I have to press tab key more times. Tmux is then much less responding for tab key.

I also compiled from git repository and unfortunately behaviour is the same.

Os: Ubuntu 18.04

Package: tmux
Version: 2.6-3ubuntu0.1

Package: libevent-dev
Version: 2.1.8-stable-4build1

I build from git repo this particular commit: 4ab3b18b36ddd361e0e0030d9d3a2c98b754e88c

```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.6
xterm-256color
```

In a worst case I would like to hardcode ctrl-i into tmux source code instead of default ctrl-b. How can I do it?

**Comment by krystian-wojtas** [comment]
I built old version 1.2 and unfortunately it behaves the same as previous ones.

**Comment by nicm** [comment]
C-i and Tab are the same so you if you use it as prefix you will need to press Tab twice to send it to the application.

**Comment by krystian-wojtas** [comment]
Yes, that's it :D Another key binding ctrl-h works well.

Thank you very much for you answer.
