### ISSUE TITLE
Characters sent from terminal are garbled by tmux in 2.1

### ISSUE THREAD

**Issue by willvousden** [tmux/tmux#159]
My terminal emulator (ITerm2) has key mappings that character sequences, to make certain tmux actions a bit easier (e.g. cycling through windows).  For example, I have one that sends `0x06 0x70` (corresponding to a `C-f p` binding in tmux; my prefix is `C-f`).  (This is described [here](http://tangledhelix.com/blog/2012/04/28/iterm2-keymaps-for-tmux/)).

These worked fine in 2.0, but now tmux seems to be capturing the sequence in the wrong order, so that it comes through as `p C-f`.  I can't quite work out a pattern to when it does and doesn't work, but it seems to be something to do with the timing of how they're sent.

For example, if I create separate mappings in my terminal emulator for `C-f` and `p` and press them in sequence, it works fine.

**Comment by nicm** [comment]
turn down assume-paste-time

**Comment by willvousden** [comment]
Thanks, I wasn't aware of that option.

Still, its default value hasn't changed between 2.0 and 2.1 (and the key mappings still works with its default value of 1ms on remote machines running 2.0).  Why has tmux's behaviour changed?

**Comment by gusgard** [comment]
+1

**Comment by henrik** [comment]
To make things more explicit for the next person. Add this to your `~/.tmux.conf`:

```
set -g assume-paste-time 0
```

**Comment by ifyouseewendy** [comment]
+1
