### ISSUE TITLE
enable tab completion for user defined command-alias

### ISSUE THREAD

**Issue by fourjay** [tmux/tmux#1590]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

I've set up a few command-alias mappings.
It would be nice if those commands would tab-complete as the tmux built-ins do.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/2841117/x.diff.txt)e

**Comment by fourjay** [comment]
I had to make clean first, but it works :-)

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
