### ISSUE TITLE
set-option aggressive-resize meaning reversed in next-2.9

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#1591]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

HI,

I've upgraded to next-2.9 and noticed I can no longer create linked sessions with different window sizes.

With `set-option -gw aggressive-resize on`

Before:
xterm 1 - launch `tmux new-session`
xterm 2 - launch `tmux new-session -t 0`

At this point, you have the same display in both xterms (sized to the smaller xterm 1).

`Prefix c` (new-window) in xterm 2 results in a new window visible in xterm 2, correctly sized to the dimensions of xterm 2.  

After upgrading to `next-2.9`,  xterm 2 shows the new window briefly at the correct size, then it immediately resizes to the same as xterm 1 (window-size = smallest).

If I set `aggressive-resize` off, the behaviour returns to the same as pre-2.8 aggressive-resize-on behaviour.

I hope that makes sense.
Are we able to make aggressive resize behave the same in 2.7/2.8 and next-2.9?  

Thanks

**Comment by nicm** [comment]
Try this please:
~~~~
diff --git a/resize.c b/resize.c
index fef8feeb..2134165f 100644
--- a/resize.c
+++ b/resize.c
@@ -188,7 +188,7 @@ recalculate_sizes(void)
 		type = options_get_number(w->options, "window-size");
 		if (type == WINDOW_SIZE_MANUAL)
 			continue;
-		current = !options_get_number(w->options, "aggressive-resize");
+		current = options_get_number(w->options, "aggressive-resize");
 
 		changed = 1;
 		if (type == WINDOW_SIZE_LARGEST) {

**Comment by systemmonkey42** [comment]
Will do. I just landed in Japan so it might be a few days.
