### ISSUE TITLE
Feature request: A command to preview an alternate screen

### ISSUE THREAD

**Issue by snizovtsev** [tmux/tmux#1592]
Some terminals like xterm and macos terminal provides a feature that allows user to preview an alternate screen contents. Xterm: ctrl + middleclick "show alternate screen" menu, macos term: "global menu -> view -> show/hide alternate screen".
Some TUI programs implements this itself like vim's ":!", but some are not. It can be useful to have a command on tmux pane side that will work on every program, for example to see a program arguments.

**Comment by nicm** [comment]
I don't really see why tmux needs to implement this when you can just suspend the program.

**Comment by snizovtsev** [comment]
You are right - i didn't think about it.
