### ISSUE TITLE
tmux crashes when using "st+tmux+vim+this configuration of vim"

### ISSUE THREAD

**Issue by ali-hardan** [tmux/tmux#1593]
my `.vimrc` only includes this:
~~~vim
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"
~~~

This configuration changes the vim cursor shape in insert mode and replace mode. When I run "st+tmux+vim+this vim configuration", tmux crashes completly. When I remove this configuration from `.vimrc`, problem not happen.

OS: ArchLinux32, up2date. I haven't `.tmux.conf` file. tmux-server log attached.

I think #1264 and this problem have a common cause, because neovim try to change cursor shape as default, so this problem also happen on neovim without extra configuration.

~~~bash
[ali@ali-host ~]$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.8
st-256color
~~~

[tmux-server-10265.log](https://github.com/tmux/tmux/files/2824844/tmux-server-10265.log)

**Comment by Brottweiler** [comment]
tmux crashes for me as well in **st** even if running without a config using `nvim -u NONE`.

- `$TERM` outside of tmux: `st-256color`
- `$TERM` inside of tmux: `screen-256color`

**Comment by ali-hardan** [comment]
@nicm, It stil crash after add that to `.tmux.conf` and restart tmux.

**Comment by ali-hardan** [comment]
Yes my vim not crashes when I run tmux using this command: `TERM=screen-256color tmux`

But when I do this, cursor shape changing not works.

**Comment by Brottweiler** [comment]
@ali-hardan 
Cursor shape changing won't work and also italics won't work because tmux [will behave like screen](https://github.com/tmux/tmux/wiki/FAQ#i-dont-see-italics-or-italics-and-reverse-are-the-wrong-way-round), so to make it work you can add this to your `.tmux.conf`
```bash
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",tmux-256color:Tc"
```
then run tmux with `TERM=tmux-256color tmux`.

**Comment by ThomasDickey** [comment]
Arch Linux provides an incorrect terminal description for st.  The place to address that would be in their bug-reporting system.

**Comment by ali-hardan** [comment]
@Brottweiler, Thanks, It works.

@ThomasDickey, Where Arch Linux provided terminal description for st?

**Comment by ThomasDickey** [comment]
They're not using an up-to-date terminfo database, lacking a fix from last [February](https://invisible-island.net/ncurses/terminfo.src.html#t20180224).

**Comment by Foxboron** [comment]
This is a problem with the 32bit fork of Arch Linux. Not Arch Linux,

**Comment by ali-hardan** [comment]
@Foxboron, Yes I'm a user of 32bit fork of Arch Linux, But what is this problem from? Is it from 32bit fork?

Who can test this issue on Arch Linux, please test and post result here.

**Comment by Brottweiler** [comment]
@ali-hardan 
>Yes I'm a user of 32bit fork of Arch Linux
But I'm not... I'm running official Arch Linux 64bit. Why do I have this issue then?

**Comment by KJoke70** [comment]
The st readme says:

    Running st
    ----------
    If you did not install st with make clean install, you must compile
    the st terminfo entry with the following command:

        tic -sx st.info

    See the man page for additional details.

Running `tic -sx st.info` from within the st folder (where the st.info file is) fixes the issue for me. It creates the terminfo data in `~/.terminfo`.

**Comment by ali-hardan** [comment]
@KJoke70, Thanks, it fixed issue. Sorry for my mistake.

But change cursor shape not works, in vim and neovim.

**Comment by nicm** [comment]
By the sounds of it this is an Arch Linux or st problem.

**Comment by Brottweiler** [comment]
@ali-hardan 
>But change cursor shape not works, in vim and neovim.

I would still try to set 
```bash
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",tmux-256color:Tc"
```
in your `.tmux.conf` for cursor shape to work.

**Comment by aasril** [comment]
@Brottweiler do you have this issue fixed?

I'm on LinuxMint 18.3 with st 0.8.2 and tmux 2.8 and having this cursor shape change not working on vim on tmux but it works if vim is not running on tmux.

**Comment by Brottweiler** [comment]
@aasril nope, never found a solution.

**Comment by ali-hardan** [comment]
@aasril and @Brottweiler, put this into your .vimrc:

~~~vimrc
if exists('$TMUX')
	let &t_SI = "\<Esc>Ptmux;\<Esc>\e[6 q\<Esc>\\"
	let &t_SR = "\<Esc>Ptmux;\<Esc>\e[4 q\<Esc>\\"
	let &t_EI = "\<Esc>Ptmux;\<Esc>\e[2 q\<Esc>\\"
else
	let &t_SI = "\e[6 q"
	let &t_SR = "\e[4 q"
	let &t_EI = "\e[2 q"
endif
~~~

It make cursor shape change works on st+tmux+vim.

**Comment by aasril** [comment]
@ali-hardan this works, thank you!

**Comment by aasril** [comment]
@ali-hardan 
Unfortunately the workaround breaks my custom prompt. I have these lines on my inputrc (I'm using vi-mode)
```
set show-mode-in-prompt on
set vi-cmd-mode-string \1\e[1;33m\2◯◯◯\ \1\e[00m\2\1\e[0m\2\1\e[2\ q\2
set vi-ins-mode-string \1\e[1;34m\2___\ \1\e[00m\2\1\e[0m\2\1\e[6\ q\2
```
It looks like this ![this](https://user-images.githubusercontent.com/37625377/54660860-a6b2c280-4b0a-11e9-83ad-eefd52bfc1e0.png)

If I open vim on tmux and then switch to other panes or windows after, the cursor will retain the last shape it has on vim pane. It won't change when I switch mode from cmd to ins or vice versa. Interestingly, on Gnome Terminal the cursor will have the shape as on the last vim pane but after a blink it will correct itself to the current mode on the command prompt. As st (at least my build) doesn't have blink it doesn't happen.
