### ISSUE TITLE
Suggestion: change 24-bit-color.sh to use semicolon delimiter?

### ISSUE THREAD

**Issue by whereswaldon** [tmux/tmux#1596]
The color-testing scripts in `./tools` are great, and they've been very useful to me when testing whether I have things configured correctly in different terminal emulators. However, the `24-bit-color.sh` script uses `:` as the separator within escape sequences by default, and not all terminal emulators recognize that. I looked around (briefly), and it seems that most or all support using semicolons whereas only some support colons.

The needed change is miniscule:
```patch
From 72163b6c2eebd1c98a05bbf3f408f2dcbf503c0e Mon Sep 17 00:00:00 2001
From: Chris Waldon <Chris.Waldon@ibm.com>
Date: Wed, 6 Feb 2019 08:39:38 -0500
Subject: [PATCH] Assume semicolon delimiter for color sequences

---
 tools/24-bit-color.sh | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
 mode change 100644 => 100755 tools/24-bit-color.sh

diff --git a/tools/24-bit-color.sh b/tools/24-bit-color.sh
old mode 100644
new mode 100755
index 73cff60a..81d7cd41
--- a/tools/24-bit-color.sh
+++ b/tools/24-bit-color.sh
@@ -20,7 +20,7 @@ then
 else
     SEQ=seq
 fi	
-SEPARATOR=':'
+SEPARATOR=';'
 
 setBackgroundColor()
 {
-- 
2.20.1

```

I opened an issue instead of a pull request because I expect that I might not have all of the context on why the default is a colon now. Are there many terminal emulators that don't support semicolons that I just don't know about? Would it be more reasonable to add conditional logic to choose between the two delimiters based on some criteria? Or is the semicolon-only family of terminal emulators (in my case, `st`) just too small to warrant the change?

The above is from commit `c42e89a598aff8fc983b2468be3277aa3dcb71bd`, by way of a version number.

Thanks for a great tool!

**Comment by nicm** [comment]
This comes from iterm2 as it says at the start of the script.
