### ISSUE TITLE
(Documentation) The installation document should be more descrptive for beginner.

### ISSUE THREAD

**Issue by hayabusa425** [tmux/tmux#1597]
Subject : The installation document should be more descrptive for beginner.
I try installation tmux based on README, but I could not install correctly.

## Steps to reproduction
1. download libevent-2.1.8-stable.tar.gz
2. `$ ./configure`
3. I want to install latest version.
        `$ git clone https://github.com/tmux/tmux.git`
        `$ cd tmux`
        `$ sh autogen.sh`
        `$ ./configure && make`

## Actual result
I had to run more steps.
1. `$ sh autogen.sh` ...< error(1)
2. fix error(1)
3. `$ sh autogen.sh` ...< error(2)
4. fix error(2)
5. `$ sh autogen.sh`
6. `$ ./configure && make`
7. `$ tmux` ...< error(3)
8. fix error(3)
9. I successfully run tmux :)

### **error(1)**
    autogen.sh: line 15: aclocal: command not found
    aclocal failed
### **fix error(1)**
    $ brew install automake

### **error(2)**
    configure.ac:25: installing 'etc/compile'
    configure.ac:10: installing 'etc/config.guess'
    configure.ac:10: installing 'etc/config.sub'
    configure.ac:8: installing 'etc/install-sh'
    configure.ac:8: installing 'etc/missing'
    Makefile.am: installing 'etc/depcomp'
    configure.ac:90: error: possibly undefined macro: AC_SEARCH_LIBS
        If this token and others are legitimate, please use m4_pattern_allow.
        See the Autoconf documentation.
    autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
    autoreconf failed
### **fix error(2)**
    $ brew install pkg-config

### **error(3)**
    zsh: command not found: tmux
### **fix error(3)**
    $ make install

##  Expected result
Installation tmux that refer to only README.
Just typing `$ tmux` will allow tmux to run.

## Environment
OS X Mojave 10.14.2
Terminal zsh

**Comment by ThomasAdam** [comment]
Unfortunately, this isn't anything to do with tmux. The instructions as-is are perfectly adequate.

**Comment by nicm** [comment]
We make the assumption that those wishing to build from Git config have a reasonable understanding of how to use autotools on their platform, I don't think that is unreasonable given the tmux target audience. If you have specific platform-neutral suggestions we can consider them.
