### ISSUE TITLE
Bind-key executing command after `;`

### ISSUE THREAD

**Issue by silvioricardoc** [tmux/tmux#1598]
The following line in a `.tmux.conf` triggers a "no current target" warning:
```tmux
bind-key R source-file ~/.tmux.conf; display-message "Reloaded ~/.tmux.conf"
```

I imagine the ";" is being interpreted as "end of command" and the display-message command is being run while tmux is loaded. (Though triggering the bound key still calls display-message, so it is still being taken into account somehow).

Note that escaping ";" as "\\;" seems to solve this issue, so maybe this is an intended change in syntax? (But then why would display-message still be called when I trigger the bound key?)

---
Using tmux 2.6 in Linux Mint 19 (x86_64, kernel 4.15.0-43-generic), with TERM=screen-256color.

Issue replicated with an empty tmux.conf (only including the offending line) and HEAD of master (bdb7e48cbabe70a3b).

**Comment by nicm** [comment]
Use \\;.
