### ISSUE TITLE
Tmux if-shell slows down on one of my computer

### ISSUE THREAD

**Issue by Chun-Yang** [tmux/tmux#1603]
- environment
Darwin i386
tmux 2.7
xterm-256color
MacOS Mojave 10.14.2

- problem
I have the following configuration in my .tmux.conf file
```
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
```
So that I can switch between shell and vim panes in tmux.

The problem is that when I hit 'C-h', it take a while(~1s) to switch to another pane. It does not matter which pane was the original and which pane was I jump to.

If I change the configuration to the following, the pane switch would work without delay.
```
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R
```

Even I do not call a shell function like the following, the switching is still slow.
```
bind -n C-h if-shell "" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "" "send-keys C-l" "select-pane -R"
```

The strange part is that this problem only happen on my work computer, not on my own computer. I think this maybe related to security features on my work computer. But I do not know how to debug this issue. 

- logs from tmux (see below)

```
1550005505.757021 job write 0x7fdf99c09cf0: echo "zsh" | grep -iqE "(^|\\/)g?(view|n?vim?)(diff)?$", pid 58012, output left 0
1550005505.757037 cmdq_next <global>: empty
1550005505.757046 cmdq_next <0x7fdf9b801000>: empty
1550005505.757055 @0 active pane not changed

// this takes more than 500ms

1550005506.325784 job error 0x7fdf99c09cf0: echo "zsh" | grep -iqE "(^|\\/)g?(view|n?vim?)(diff)?$", pid 58012
1550005506.325844 cmdq_next <global>: empty
1550005506.325857 cmdq_next <0x7fdf9b801000>: empty
1550005506.325873 @0 active pane not changed
1550005506.326163 server_signal: Child exited: 20
1550005506.326189 job died 0x7fdf99c09cf0: echo "zsh" | grep -iqE "(^|\\/)g?(view|n?vim?)(diff)?$", pid 58012
1550005506.326211 free job 0x7fdf99c09cf0: echo "zsh" | grep -iqE "(^|\\/)g?(view|n?vim?)(diff)?$"
1550005506.326222 unref client 0x7fdf9b801000 (3 references)
```

Here is the full log: 
client: https://pastebin.com/6Xy8Bsvu
server: https://pastebin.com/m4e4mB0M

Could someone help with this? Thank you!

**Comment by krader1961** [comment]
Start by eliminating tmux as a variable. Assuming your shell is zsh run

```
time zsh -c 'echo "zsh" | grep -iqE "(^|\\/)g?(view|n?vim?)(diff)?$"'
```

You should verify which shell tmux is using by running `tmux show-options -g default-shell`.

**Comment by nicm** [comment]
Can you run this:
~~~~
pkill tmux
strace -ttt -ff -ostrace.out tmux -vv new
~~~~
Then reproduce and send me all the strace.out* files and corresponding tmux*.log files.

**Comment by nicm** [comment]
On Tue, Feb 12, 2019 at 02:03:39PM -0800, Kurtis Rader wrote:
>    Start by eliminating tmux as a variable. Assuming your shell is zsh run
> 
>  time zsh -c 'echo "zsh" | grep -iqE "(^|\\/)g?(view|n?vim?)(diff)?$"'
> 
>    You should verify which shell tmux is using by running tmux show-options
>    -g default-shell.

if-shell always uses /bin/sh.

**Comment by Chun-Yang** [comment]
Hi @nicm I am using a mac and I tried to use `dtruss tmux -vv new`. The tmux window instantaneously closed itself and I get the following partial log:
```
dtrace: system integrity protection is on, some features will not be available

SYSCALL(args) 		 = return
r1\0", 0x7FFEEB26A7E0, 0x0)		 = 0 0
```

I do not think this will help. Any other tips?

**Comment by Chun-Yang** [comment]
BTW I really appreciate your help @nicm @krader1961

**Comment by krader1961** [comment]
Sadly `strace` isn't available on macOS and `dtruss` isn't nearly as useful, or usable, for this type of task. Since @nicm reminded me that `if-shell` always uses */bin/sh* what do you see when you do

```
time /bin/sh -c 'echo "zsh" | grep -iqE "(^|\\/)g?(view|n?vim?)(diff)?$"'
```

It should run in 10 ms or less. This is what I see on my Macbook:

```
$ time /bin/sh -c 'echo "zsh" | grep -iqE "(^|\\/)g?(view|n?vim?)(diff)?$"'
        0.01 real         0.00 user         0.01 sys
```

If it's taking on the order of 0.50 real seconds then the problem doesn't involve tmux.

**Comment by Chun-Yang** [comment]
```
$ time /bin/sh -c 'echo "zsh" | grep -iqE "(^|\\/)g?(view|n?vim?)(diff)?$"'
/bin/sh -c 'echo "zsh" | grep -iqE "(^|\\/)g?(view|n?vim?)(diff)?$"'  0.00s user 0.00s system 99% cpu 0.007 total
```
I am not sure if the problem come from tmux, but the command runs fast.

**Comment by Chun-Yang** [comment]
I think this is definitely an extreme edge case. My other computer works fine with the same settings. If you think its very hard to diagnose, let's just close the issue then.

**Comment by nicm** [comment]
I can't help you much further with OS X, you will need to reproduce on Linux or *BSD or work out how to get the equivalent of strace working.

**Comment by nicm** [comment]
Are you sure there is nothing funny in any shell profiles?

**Comment by Chun-Yang** [comment]
I removed all dot files and the problem still exist. Thanks for the help.

**Comment by nicm** [comment]
Does it still happen if you run tmux as root or as a brand new user?

**Comment by Chun-Yang** [comment]
Still happens. I will use other bindings. I will try to resolve it later on if I get some free time. Thank you!
