### ISSUE TITLE
tmux changes color palette

### ISSUE THREAD

**Issue by tofuhead** [tmux/tmux#1604]
Linux x86_64
tmux 2.7 (also compiled git master to check)

outside:xterm-256color
inside:screen-256color

tmux displays colors a bit differently when I run vim. I attached a screenshot showing the difference. 
leftside is tmux with two panes, rightside two KDE terminals. 
I also ran a palette script which shows quite interesting gray spots .. I don't know if that is related somehow. and the colors don't "ease" quite as nicely in tmux screen, especially on reds, and the first rows look almost identical in all the boxes..

![tmuxcolors](https://user-images.githubusercontent.com/8156935/52758102-bcb2fc00-300f-11e9-9a9a-e940b85c98df.png)

.b

**Comment by nicm** [comment]
But you didn't think it worth including the script?

**Comment by tofuhead** [comment]
oh sorry... I somehow thought it's a known one to you .. found it somewhere on this tracker, anyways... here it is... (had to add .txt extension to allow it to be attached)

[256colors2.pl.txt](https://github.com/tmux/tmux/files/2868384/256colors2.pl.txt)

**Comment by nicm** [comment]
It looks like you don't have RGB colour enabled, try putting this in .tmux.conf:
~~~~
set -as terminal-overrides ',*:Tc'
