### ISSUE TITLE
`source`ing a cwd-relative path no longer works in 2.8 vs 2.7

### ISSUE THREAD

**Issue by owst** [tmux/tmux#1606]
In my tmux.conf, I source a cwd-relative "sub-config" file (in my real example I'm using `if-shell` to source a version-specific mouse-setup config file, but the issue is demonstrated here):
```
$ tree .
.
├── sub-configs
│   └── test.conf
└── tmux.conf

1 directory, 2 files

$ cat tmux.conf
source sub-configs/test.conf
```
This worked in 2.7:
```
$ tmux -V
tmux 2.7
$ tmux -v -f tmux.conf start-server
$ grep '\(test\|tmux\)\.conf\b' tmux-server-*.log
1550249824.196206 loading /usr/local/etc/tmux.conf
1550249824.196234 loading tmux.conf
1550249824.196292 tmux.conf: source sub-configs/test.conf
1550249824.203415 cmd_source_file_exec: ./sub-configs/test.conf
1550249824.203469 loading ./sub-configs/test.conf
```
In 2.8 however, it appears the cwd is assumed to be my home directory, which means the sub-config is not found:
```
$ tmux -V
tmux 2.8
$ tmux -v -f tmux.conf start-server
$ grep '\(test\|tmux\)\.conf\b' tmux-server-*.log
1550249955.301556 loading /usr/local/etc/tmux.conf
1550249955.301587 loading tmux.conf
1550249955.301662 tmux.conf: source sub-configs/test.conf
1550249955.301716 source-file: argv[1]=sub-configs/test.conf
1550249955.320598 cmd_source_file_exec: /Users/owenstephens/sub-configs/test.conf
1550249955.320661 cmdq_error: sub-configs/test.conf: No such file or directory
```
I can see [this commit](https://github.com/tmux/tmux/commit/b9a6162d2f9bea63c3ad421e9c3969eea2852b00) which looks relevant. Was this an expected side-effect of that change? Is there a way to source a file relative to the cwd in >= 2.8?

I don't think this is platform specific, but I'm on macOS.

**Comment by nicm** [comment]
Show me the full server log please.

**Comment by nicm** [comment]
Actually, never mind, this is intended. The current working directory of the tmux server is not used anymore because it could be anything. Unadorned paths will now always be relative to your home.

**Comment by nicm** [comment]
Really in your example it should be using the initial client WD, but we don't run the config file in that client context.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/2870405/x.diff.txt)

**Comment by owst** [comment]
Thanks for the quick response and patch @nicm - I can confirm it fixes my issue

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
