### ISSUE TITLE
Tmux sending random Up arrow code to sessions when printing output

### ISSUE THREAD

**Issue by Linkandzelda** [tmux/tmux#1608]
When having `status off` and any session (attached or detached) outputs something, then when I press Escape in another window it will also send an Up arrow key code ([[A]) if I time it right or just long hold it.

To test this I did `sleep 9999;` in one session while the other is just doing an endless ping. I hold down Escape on the sleep session and the output looks like this:

    [^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[[A^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[[A^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^

At first I thought this might be a keyboard failure, however if I do `set status on` in the session window which is outputting the ping results then the problem goes away in the session window running sleep. Note that even with status off/on in the sleep session the problem would not be resolved until I applied it to the one outputting.

In practice this occurs very often when working over SSH and in vim, and I am puzzled as to why such a thing occurs in the first place.

Term: termite
OS: Arch
Config: https://pastebin.com/raw/05GkHPp7

**Comment by nicm** [comment]
Logs?

**Comment by Linkandzelda** [comment]
Can you instruct me on how to get the logs?

**Comment by nicm** [comment]
Instructions here https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

**Comment by Linkandzelda** [comment]
Linux unknown
tmux 2.8
tmux-256color

[tmux-client-16487.log](https://github.com/tmux/tmux/files/2871887/tmux-client-16487.log)
[tmux-out-16467.log](https://github.com/tmux/tmux/files/2871888/tmux-out-16467.log)
[tmux-server-16467.log](https://github.com/tmux/tmux/files/2871889/tmux-server-16467.log)
[tmux-client-16465.log](https://github.com/tmux/tmux/files/2871890/tmux-client-16465.log)

**Comment by nicm** [comment]
Does this change fix the problem? Someone posted ir as a PR but with no way to reproduce and I wonder you are hitting this.
~~~~
diff --git a/tty-keys.c b/tty-keys.c
index 068c502f..53ccd3e2 100644
--- a/tty-keys.c
+++ b/tty-keys.c
@@ -464,6 +464,10 @@ tty_keys_find(struct tty *tty, const char *buf, size_t len, size_t *size)
 static struct tty_key *
 tty_keys_find1(struct tty_key *tk, const char *buf, size_t len, size_t *size)
 {
+	/* If no data, no match. */
+	if (len == 0)
+		return (NULL);
+
 	/* If the node is NULL, this is the end of the tree. No match. */
 	if (tk == NULL)
 		return (NULL);

**Comment by Linkandzelda** [comment]
I will give it a try and report back.

**Comment by Linkandzelda** [comment]
That seems to have fixed the problem. I tried with this code, without, and with. Both times the issue was not occurring.

**Comment by nicm** [comment]
Great! Applied to OpenBSD now, will be in GitHub later. Thanks!
