### ISSUE TITLE
tmux crashing after refocusing on the tmux session running vim with mouse enabled

### ISSUE THREAD

**Issue by binup28** [tmux/tmux#1609]
tmux crashes consistently after returning to the terminal running tmux. I can open files move around using both keyboard and mouse and edit etc in vim. However after I do some other work in other terminals/windows/browser etc and come back to the tmux terminal to continue working it just crashes.

Suspect it has something to do with mouse being enabled in vim. I use putty(term=xterm). Below are log files. I do not have a .tmux_conf file setup - so nothing from there. Any ideas?

My tmux details: I compiled from source using this link: http://jhshi.me/2016/07/08/installing-tmux-from-source-non-root/index.html#.XF977FUzbvs

tmux -V
tmux 2.8
Here is how I start tmux

tmux -vvvv 
tmux-server-34191.log:

1549962713.519987 @0 active pane not changed

<----- HERE I came back to the tmux terminal and the below were when it crashed ------->

1549962717.827661 client 0x1e224a0, status interval 15
1549962717.827675 cmdq_next <global>: empty
1549962717.827679 cmdq_next <0x1e224a0>: empty
1549962717.827689 screen_write_start: size 211x1, no pane
1549962717.827724 screen_write_collect_flush: flushed 0 items (0 bytes)
1549962717.827728 screen_write_stop: 211 cells (211 written, 0 skipped)
1549962717.827806 format '[#S] ' -> '[0] '
1549962717.827816 unref client 0x1e224a0 (2 references)
1549962717.827877 format ' "#{=21:pane_title}" 09:11 12-Feb-19' -> ' "PROJ_NAME" 09:11 12-Feb-19'
1549962717.827886 unref client 0x1e224a0 (2 references)
1549962717.827931 format '#{window_flags}' -> '*'
1549962717.827934 format '#I:#W#{?window_flags,#{window_flags}, }' -> '0:vim*'
1549962717.827942 unref client 0x1e224a0 (2 references)
1549962717.827947 screen_write_start: size 7x1, no pane
1549962717.827951 screen_write_collect_flush: flushed 0 items (0 bytes)
1549962717.827953 screen_write_stop: 7 cells (7 written, 0 skipped)
1549962717.827956 screen_write_start: size 211x1, no pane
1549962717.827962 screen_write_collect_flush: flushed 0 items (0 bytes)
1549962717.827965 screen_write_stop: 44 cells (40 written, 4 skipped)
1549962717.827978 @0 active pane not changed
1549962718.336657 /dev/pts/3: read 12 bytes (already 0)
1549962718.336665 /dev/pts/3: keys are 12 (\033[<0;137;24M)
1549962718.336668 /dev/pts/3: mouse input (SGR): \033[<0;137;24M
1549962718.336671 /dev/pts/3: complete key \033[<0;137;24M 0x10000005
1549962718.336676 session $0 0 activity 1549962718.336674 (last 1549962678.439002)
1549962718.336680 mouse 00 at 136,23 (last 0,0) (0)
1549962718.336683 down at 136,23
1549962718.336686 mouse at 136,23 is on pane %0
1549962718.336690 cmd_find_from_mouse: s=$0 0
1549962718.336692 cmd_find_from_mouse: wl=0 1 w=@0 vim
1549962718.336694 cmd_find_from_mouse: wp=%0
1549962718.336696 cmd_find_from_mouse: idx=none
1549962718.336700 writing key 0x1000000a (MouseDown1Pane) to %0
tmux-client-34189.log:

1549962672.798365 sending message 105 to peer 0x1def610 (29 bytes)
1549962672.798368 sending message 105 to peer 0x1def610 (35 bytes)
1549962672.798370 sending message 105 to peer 0x1def610 (53 bytes)
1549962672.798372 sending message 105 to peer 0x1def610 (88 bytes)
1549962672.798375 sending message 105 to peer 0x1def610 (107 bytes)
1549962672.798377 sending message 105 to peer 0x1def610 (75 bytes)
1549962672.798379 sending message 105 to peer 0x1def610 (67 bytes)
1549962672.798382 sending message 105 to peer 0x1def610 (77 bytes)
1549962672.798384 sending message 105 to peer 0x1def610 (38 bytes)
1549962672.798386 sending message 105 to peer 0x1def610 (32 bytes)
1549962672.798389 sending message 105 to peer 0x1def610 (71 bytes)
1549962672.798391 sending message 105 to peer 0x1def610 (21 bytes)
1549962672.798393 sending message 105 to peer 0x1def610 (16 bytes)
1549962672.798395 sending message 105 to peer 0x1def610 (42 bytes)
1549962672.798398 sending message 106 to peer 0x1def610 (0 bytes)
1549962672.798401 sending message 200 to peer 0x1def610 (4 bytes)
1549962672.798403 client loop enter
1549962672.815446 peer 0x1def610 message 207
1549962672.815456 sending message 208 to peer 0x1def610 (0 bytes)
1549962718.338531 client loop exit

Update 1: I just tried enabling mouse in tmux by creating a .tmux.conf file containing the below but still gave the same result

set -g mouse on
Update 2: It stopped crashing when I removed the mouse support from vim and the tmux mouse support I added in "Update 1". So it is something to do with mouse support for tmux. Any ideas?

**Comment by nicm** [comment]
Upload the full server log please.

Also does tmux leave a core file? You may need to run "ulimit -c unlimited"
right before starting it. Look for core, or core.* or *.core.

If so please do this and show me the output:


gdb -q tmux ./core-file-name
bt full
