### ISSUE TITLE
Preference for more columns than rows in tiled layout

### ISSUE THREAD

**Issue by rkowalick** [tmux/tmux#161]
I noticed tmux has a tiled window mode, but the layout seems to prefer having more rows over more columns: that is, If I had 6 windows, I would get the layout

```
---------
| 1 | 2 |
---------
| 3 | 4 |
---------
| 5 | 6 |
---------
```
Since most screens are wider than they are tall, I would expect most people would prefer:
```
-------------
| 1 | 2 | 3 |
-------------
| 4 | 5 | 6 |
-------------
```
It is a pretty straightforward change. Thoughts?

**Comment by dvanallen** [comment]
Please reconsider accepting this change.  I would love to use the tmux tiling layout, but this is a deal breaker for me.  I believe most tiling window managers default to preferring vertical splits - I know for sure that dwm and i3 do.  With Retina displays, this is a huge improvement, especially when working with files that have an 80-character line length limit.
