### ISSUE TITLE
Feature request: Smarter scrolling features when mouse mode is enabled

### ISSUE THREAD

**Issue by alxpettit** [tmux/tmux#1610]
I like to have a lot of mouse features in everything. To scroll through `less` and `vim` I will often use the scrollwheel. I also like to have mouse features enabled in `tmux`. As it stands, from the response in #1493, it seems like there is no way to fully satisfy this use case -- the one response I saw was a crude workaround which effectively "disabled" the mousewheel scrolling feature without _actually_ disabling it (which, I tried, and resulted in _much_ slower scrolling, sadly).

The most optimal solution I could think of for this use case would be to have a blacklist of applications on which Tmux should not intercept scroll signals (VIM, Less, More, etc). If a user finds she is forced to use pgup/pgdn in a paginated utility, she can simply add it.

Perhaps there is a better way of detecting pagination features in child processes, but I don't know of any. Let me know if this seems realistic, or if it's too complicated.

A simpler (but, in my opinion, functionally worse) solution would be to simply allow the user to disable scrollwheel features independently of mouse features -- and then make due with pgup/pgdn when scrolling through Tmux's buffer. Presumably the command to toggle that could even be bound to a key, which would allow the user to set a keybinding for it to switch between scroll buffers. Maybe useful to some people!

**Comment by nicm** [comment]
I don't know what you are talking about, if the application requests the
mouse then tmux will pass it on rather than handling it itself. Can you be
more specific,?

**Comment by alxpettit** [comment]
Okay, I didn't know that. Maybe this is a bug? In that case, I'll have to give system information.

`uname -a`: `Linux lithium 4.19.20-1-lts #1 SMP Wed Feb 6 21:46:51 CET 2019 x86_64 GNU/Linux`
OS: Arch Linux

[Current tmux.conf](https://gist.github.com/alxpettit/873648f959dfe3a5e2f245cf4961dd55).
Tmux version: 2.8

Steps to reproduce:
* Open `less` with any content.
* Attempt to scroll up/down with mousewheel
* Observe that Tmux intercepts requests.

**Comment by nicm** [comment]
less does not support the mouse, some terminals send up and down keys for
the mouse wheel by default but tmux doesn't do this. You can configure tmux
to do so, there are some examples but I can't dig one out right now.

**Comment by alxpettit** [comment]
Well, I mean, `less` works with mouse scrolling for me. I should mention that I'm using `uxterm`  with [this configuration](https://gist.github.com/alxpettit/50cc98cb796a0c9ee136361b25d4a748).

Hmmm... this might be a less general problem than I thought. Is there a debug app for printing/logging CLI-specific keypress codes? Something like `xev` but not for Xorg.

**Comment by krader1961** [comment]
> Is there a debug app for printing/logging CLI-specific keypress codes?

`od -tx1z` or, if you have the fish shell installed, its `fish_key_reader` program is handy for this.

**Comment by alxpettit** [comment]
@krader1961 Neither one of those are actually responding to scroll input. Strange.

**Comment by nicm** [comment]
Perhaps your less does turn on the mouse, please run "tmux -vvLtest -f/dev/null new" then run less, scroll with the mouse, then exit tmux and show me the tmux-server*.log file.

**Comment by krader1961** [comment]
> Neither one of those are actually responding to scroll input. Strange.

Not strange at all. Neither of those programs enable mouse scroll events. And the fact they don't report any bytes received simply means your terminal is not synthesizing keystrokes when you scroll the mouse.

I use `less` many times every day. AFAIK it does not enable mouse events. It certainly doesn't do anything when I scroll my mouse whereas I can do `:set mouse a` in `vim` in the same terminal and it does recognize mouse scroll events. I just checked the `less` source and find nothing to suggest it does so. It's possible your terminfo definition does so but that seems unlikely as it would cause problems for any program not prepared to handle such input. So when you say that you can use your mouse to scroll when running `less` outside of `tmux` I am skeptical.

**Comment by alxpettit** [comment]
[Here!](https://gist.github.com/alxpettit/f0755b47b9f41804d697f6e5120cb10b)

**Comment by nicm** [comment]
less is not requesting the mouse, so tmux is not sending it mouse sequences, this is correct. What do you see if you run "cat" outside tmux and then scroll the mouse? What if you do "tput smcup; cat" also outside tmux?

**Comment by nicm** [comment]
Actually never mind. You have configured xterm to send Up and Down keys for the mouse wheel:
~~~~
       alternateScroll (class ScrollCond)
               If “true”, the scroll-back and scroll-forw actions send
               cursor-up and -down keys when xterm is displaying the alternate
               screen.  The default is “false”.

               The alternateScroll state can also be set using a control
               sequence.
~~~~
You will need to configure tmux to also do this as I mentioned before. Look at this comment https://github.com/tmux/tmux/issues/1320#issuecomment-381952082.

**Comment by alxpettit** [comment]
Oh! Mystery solved! But this solution isn't really working that well, with the snippit from @T1T4N -- the scrolling is _much_ slower than with `uxterm`'s alternateScroll feature.

To give some sort of objective metric, I generated a test file by doing `seq 1 500 > test.txt` and tried scrolling to the bottom in `less`, and it took me around 4 seconds. With `less` opened inside `tmux`, it took more like 9. Is it possible to address this within tmux's existing feature set?

**Comment by nicm** [comment]
Its probably the grep that is slow, either change it to use if -F and the various format conditions so it doesn't need to run grep, or get rid of it entirely and just check #{alternate_on} (which is what xterm itself does).

**Comment by alxpettit** [comment]
Oh I didn't notice it was forking `grep` every single time the condition was being met... that's actually kind of horrific, but it explains the problem. What do you mean "change it to use if -F"? It should be noted that I don't understand `tmux`'s scripting language very well. You might have to point me at the right documentation.

**Comment by nicm** [comment]
Something like:
~~~~
bind-key -T root WheelUpPane if -F '#{?mouse_any_flag,1,#{pane_in_mode}}' 'send -M' 'if -F "#{alternate_on}" "send Up" "copy-mode -e"'

**Comment by alxpettit** [comment]
I just tried that code, and it's actually somehow not much faster than the code suggested by @T1T4N. About 7 seconds to scroll from top to bottom. Drat.

**Comment by mckellyln** [comment]
You could scroll more than one line also, by adding a -N 3 to the send-keys command for example.
I do this and also add a Alt- modifier to get faster scrolling, as in:
```
bind -T root         WheelDownPane \
	if-shell -Ft= "#{?pane_active,0,1}" "select-pane -t=" \
		"if-shell -Ft= \"#{mouse_any_flag}\" \
			\"send-keys -M\" \
			\"if-shell -Ft= '#{alternate_on}' \
				'send-keys -N 3 Down' \
				''\""

bind -T root         M-WheelDownPane \
	if-shell -Ft= "#{?pane_active,0,1}" "select-pane -t=" \
		"if-shell -Ft= \"#{mouse_any_flag}\" \
			\"send-keys -M\" \
			\"if-shell -Ft= '#{alternate_on}' \
				'send-keys -N 20 Down' \
				''\""
```

**Comment by soulofmischief** [comment]
@mckellyln's solution breaks shell scrollback because `copy-mode -e` isn't called if alternate-mode isn't on.

Here is a complete snippet with working scrollback which implements the `Alt` modifier suggested above:

```
# Scroll w/ arrow-keys using mouse in alternate mode.                                                                                                                   
bind -T root WheelUpPane \
	if -Ft= "#{?pane_active,0,1}" "select-pane -t=" \
		"if -Ft= \"#{mouse_any_flag}\" \
			\"send -M\" \
			\"if -Ft= '#{alternate_on}' \
				'send -N 3 Up' 'copy-mode -e' \""
bind -T root WheelDownPane \
	if -Ft= "#{?pane_active,0,1}" "select-pane -t=" \
		"if -Ft= \"#{mouse_any_flag}\" \
			\"send -M\" \
			\"if -Ft= '#{alternate_on}' \
				'send -N 3 Down' '' \""

# Alt modifier for quicker scroll
bind -T root M-WheelUpPane \
	if -Ft= "#{?pane_active,0,1}" "select-pane -t=" \
		"if -Ft= \"#{mouse_any_flag}\" \
			\"send -M\" \
			\"if -Ft= '#{alternate_on}' \
				'send -N 20 Up' 'copy-mode -e' \""

bind -T root M-WheelDownPane \
	if -Ft= "#{?pane_active,0,1}" "select-pane -t=" \
		"if -Ft= \"#{mouse_any_flag}\" \
			\"send -M\" \
			\"if -Ft= '#{alternate_on}' \
				'send -N 20 Down' '' \""
```

You may notice that `copy-mode` is only activated on `WheelUpPane`. If it were also activated on `WheelDownPane`, scrolling down at the end of the buffer would continuously toggle `copy-mode`.

We can assume that if we are not at the end of the buffer, we are already in `copy-mode`.

**Comment by mckellyln** [comment]
I showed only WheelDownPane for brevity, but included a comment that WheelUpPane is similar, except it also enters copy-mode if not alternate.  Not sure I see a diff to your post ?

**Comment by soulofmischief** [comment]
@mckellyln Ah I see, I didn't catch that. 

The difference would still be that my post offers a complete example which may be useful to others in the future who run into the same problem I did following your example. I still had to figure out how to parse the structure of the command and consult the tmux man page in order to figure out what I was missing.

I'm not bashing your post, I just thought a more complete example would be welcome.
