### ISSUE TITLE
How to change the name of a window which is not current

### ISSUE THREAD

**Issue by totoroow** [tmux/tmux#1614]
If I have two windows, in window A: I type this in a shell `sleep 10 && tmux rename-window foo`, and then I switch to window B and stay in there. After 10s, I see there's an activity in window A from the status line, but its window's name unchanged. I expect it to be `foo`. How to achieve this? or is this a bug?

**Comment by nicm** [comment]
Use -t$TMUX_PANE.

**Comment by totoroow** [comment]
Thanks @nicm . It works like a charm.
