### ISSUE TITLE
TMUX pane output/input freezes after "unclean" session disconnect, sleep...

### ISSUE THREAD

**Issue by orcinus** [tmux/tmux#1615]
- Ubuntu 18.04
- Fish
- Powerline bindings for Fish and Tmux
- bog standard config, only change is prefix remapped to Ctrl+A, and split horizontal/vertical remapped to H and V

Whenever i end a session "uncleanly" (e.g. just kill the terminal process), and **sometimes** when entering and resuming from standby, the panes end up frozen.

Tmux itself isn't frozen, it responds to keyboard and mouse events just fine. It's the contents of the panes that's frozen, both output and input. And, before anyone asks, no, i didn't freeze them by accident.

The issue is *exactly* the same, symptomwise as this closed one: https://github.com/tmux/tmux/issues/298

The only cure is to detach/kill the "right" session (that's seemingly causing this), although sometimes that is the only session active, so i basically have to kill tmux.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by orcinus** [comment]
It's been an issue for at least a year, so across all versions up until the current one. The pre-existing issue that was closed without resolution suggests this has been a problem for years. Additionally, as mentioned, it's a bog standard install, with no fluff. 

The logs don't really say much. The issue cannot be reproduced at will with 100% repetition rate.
Hence, i did not specify any of those items.

I admit the report is a bit too brief, though, and apologize for that.
Here's the output of `uname -sp; and tmux -V; and echo $TERM` from a machine with 2.6

```
Linux x86_64
tmux 2.6
screen-256color
```

Here's the output from a machine running 2.8

```
Linux x86_64
tmux 2.8
screen-256color
```

I'll post logs (note, again, that there appears to be nothing useful there) next time it happens.

**Comment by orcinus** [comment]
Compiling fresh from repo now.
