### ISSUE TITLE
has-session fails when multiple session names match pattern

### ISSUE THREAD

**Issue by jalexvig** [tmux/tmux#1618]
tmux version 2.6

```bash
tmux new -d -s foo0
tmux has-session -t foo
tmux new -d -s foo1
tmux has-session -t foo
```

The second `has-session` check returns 1 and error message `can't find session foo`.

This is because multiple session names now match the pattern `foo`.

From the man page on `has-session`: `Report an error and exit with 1 if the specified session does not exist.  If it does exist, exit with 0.`

I would expect no error if **any** session name matched the pattern (without the `=` of course).

Side Note: Documentation for the behavior of `has-session=foo` vs `has-session foo` would be great!

**Comment by nicm** [comment]
This is expected, -t behaves exactly like any other command l, look at the manual under TARGETS.

**Comment by jalexvig** [comment]
@nicm gotcha thanks - makes sense for consistency with other commands. For posterity, the relevant section in my manual is COMMANDS not TARGES.
