### ISSUE TITLE
Need to wait until repeat-time ends to enter first character in newly focused pane

### ISSUE THREAD

**Issue by chpmrc** [tmux/tmux#1621]
**Platform**
macOS 10.14.3
Darwin i386
tmux 2.8
`$TERM`: `xterm-256color`
`$TERM` (in tmux): `screen`

**Steps to reproduce**
In tmux version 2.7+:
- Open a new or attach to an existing session (`tmux`)
- Create a split (e.g. `Ctrl+b Ctrl+%`)
- Switch to the other pane (e.g. `Ctrl+b left`)
- **Immediately** try to enter a character.

What's supposed to happen: the character gets entered.
What happens instead: the character is not entered until the `repeat-time` interval is over.

This does not happen in Tmux versions 1.8 and 2.6 (the ones I tested) and was previously reported here: https://github.com/tmux/tmux/issues/1513 but doesn't seem to be fixed yet?

**Does it happen with a fresh installation of macOS?**
Yes.

**Does it happen with other terminal emulators (iTerm etc.)?**
Yes.

**Workaround (on macOS, installs tmux 2.6)**

`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/8d9782dfdf29a6d5934cf6496ef0fc7d29bfe262/Formula/tmux.rb`
`brew pin tmux` (Avoid upgrading)

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by chpmrc** [comment]
Oh my bad, I misread the release date of 2.8, thought it was released after the fix. Will try with master, thanks. Closing this for now.
