### ISSUE TITLE
Slow scrolling when not splitting window

### ISSUE THREAD

**Issue by MarcoStuurman** [tmux/tmux#1622]
In tmux 2.8 my terminal lags when scrolling up.

When I split the window in 2 panes it's fast again, even if I resize the second pane to almost nothing (2char width). When I remove the second pane the first pane is slow again.

[root@server ~]# uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.8
tmux

I'm using the windows 10 bash and tmux runs remote on my server which I SSH to.

**Comment by nicm** [comment]
Does this still happen in a different terminal such as putty?

**Comment by MarcoStuurman** [comment]
No, it's fast there

**Comment by nicm** [comment]
Sounds like a problem with the terminal then.

**Comment by MarcoStuurman** [comment]
It is solved for me, but there is a issue. Adding a pane with 2 characters width solves it, resizing the terminal 2characters down does not.

**Comment by nicm** [comment]
When you have panes split left-right tmux redraws the entire pane rather
than using the scroll region, sounds like the terminal scroll region is
very slow.
