### ISSUE TITLE
wrap no longer working ?

### ISSUE THREAD

**Issue by mckellyln** [tmux/tmux#1624]
Hi,
I am using next-2.9 built off latest master this morning.
Today it appears lines longer than the window no longer wrap.
Is there a new setting to enable wrap ?
I'm on ubuntu 16.04 hwe with 4.15.0-46 kernel, 
thx

**Comment by nicm** [comment]
Looks like a bug, I'll take a look.

**Comment by mckellyln** [comment]
Thx.
I use terminator with TERM set to screen-256color.
No changes in my config except for new build.

**Comment by nicm** [comment]
I think it is a bug in a change made this morning.

**Comment by nicm** [comment]
Here is the fix: [x.diff.txt](https://github.com/tmux/tmux/files/2956955/x.diff.txt)

But it will be in GitHub later if you just want to wait for an hour or so.

Thanks

**Comment by mckellyln** [comment]
Thank you as always for awesome tmux.
