### ISSUE TITLE
Feature Request: DECDHL, DECDWL, and DECSWL support

### ISSUE THREAD

**Issue by FractalBoy** [tmux/tmux#1625]
Please add support for DECDHL, DECDWL, and DECSWL. I would give it a stab, but I'm not sure where to start.

**Comment by nicm** [comment]
You could probably just make it an attribute like GRID_ATTR_BRIGHT etc, although it would need to go into the extended attributes like strikethrough. Almost no programs use these nowadays and very few terminals support them so it is probably a bit of a waste, what do you need them for?

**Comment by FractalBoy** [comment]
The application that I work with uses this. It's not critical, just a cosmetic thing. PuTTY supports this.

**Comment by nicm** [comment]
If you want to do it I will look at it, but I don't think it is worth it for what is now very few applications.

**Comment by nicm** [comment]
If you want to look take a look at how the other attributes work eg GRID_ATTR_STRIKETHROUGH.

**Comment by FractalBoy** [comment]
Makes sense - thanks.
