### ISSUE TITLE
Run tmux in a separate terminal window

### ISSUE THREAD

**Issue by xpz3** [tmux/tmux#1626]
I'm not reporting a bug. I'm writing a bash script which should have a main terminal window waiting for user input and tmux windows displaying outputs depending on user input on main terminal window from which the bash script runs.
Is there any option in tmux to start it in a separate terminal window so that the main window input won't be blocked.
I'm aware of the -d option to background the session. But in my case that will not show the output for the user to provide input depending on that.

**Comment by nicm** [comment]
Whats wrong with "xterm -e tmux new"?

**Comment by xpz3** [comment]
The user should choose between tmux or xterm. Targeting users without xterm. No gui mode...

**Comment by nicm** [comment]
tmux can't start itself in a terminal, you will need to do that.

**Comment by xpz3** [comment]
So the only solution is to run my main script inside the tmux window and have the outputs in windows next to it?

**Comment by xpz3** [comment]
I tried tmux new -s name & 
But this messes up tmux
Nohup also didn't work. Do you know of any alternate methods outside the scope of tmux?

**Comment by nicm** [comment]
You can run two tmux one inside the other, ie run your program+tmux inside the outer tmux with two panes side by side.

**Comment by xpz3** [comment]
Ya i know this. But i was trying to keep it simple for users who are not much aware of tmux. For them it would be easier to see the output in panes and select the option from main window.

Maybe i should run everything inside tmux as you said.

**Comment by nicm** [comment]
You can't have an attached tmux client and another program running in the same terminal.

**Comment by xpz3** [comment]
Yea i want those two to become separated. One terminal window with user input and another terminal window with tmux session.

**Comment by xpz3** [comment]
Is there any way i could make it work by using '&' or 'nohup'
Currently both are behaving indifferently

**Comment by nicm** [comment]
No. You need two separate terminal or you need something like tmux to split your one terminal into two.

**Comment by xpz3** [comment]
Ok thanks for the quick help.
