### ISSUE TITLE
status expansions in subshell races with window change, causing stale status

### ISSUE THREAD

**Issue by smemsh** [tmux/tmux#1627]
when using several `#(git -C #{pane_current_path} ...)` in status line, after changing window, status sometimes gets injected values from the wrong window (the old one), until the next `status-interval` or manual `refresh-client -S`.

tried hooking a `refresh-client -S` onto both `session-window-changed` and also `after-select-window` but neither had any effect.

using `run-shell -b "sleep 1; tmux refresh-client -S"` in the hook works, but changing the sleep to 0.5s works only sometimes, and by 0.2s it never works.

after reporting bug in freenode #tmux on Feb 14 7:08Z, @nicm noted (some lines omitted):

> switching window redraws the status line anyway
> if it runs #() and you try to redraw again before the #() has finished it will not run it again
> of course that depends whether it gets the same pane_current_path
> in newer versions it should run it again if the expanded form changes
> probably it is waiting for the #() to return
> it should redraw again when the command finishes
> you shouldn't need to faff around with -S
> if the #() is from the status line it will redraw when the #() finishes
> changing window itself should trigger a redraw, and then it should redraw again when your #() finishes by which time it should have the new output, so even if there was a redraw already scheduled it should use the new output

and after supplying server logs:

> looks like the previous #() is still running when you do last-window
> you can try this change

```
--- format.c    19 Nov 2018 13:35:41 -0000      1.165
+++ format.c    14 Feb 2019 13:04:57 -0000
@@ -296,7 +296,9 @@ format_job_get(struct format_tree *ft, c
                force = (ft->flags & FORMAT_FORCE);
        t = time(NULL);
-       if (fj->job == NULL && (force || fj->last != t)) {
+       if (force && fj->job != NULL)
+               job_free(fj->job);
+       if (force || (fj->job == NULL && fj->last != t)) {
                fj->job = job_run(expanded, NULL,
                    server_client_get_cwd(ft->client, NULL), format_job_update,
                    format_job_complete, NULL, fj, JOB_NOWAIT);
```

thanks for this patch, can we get it upstream? it works well and I have been using it, this opens up a lot of functionality to have different information coming into the status line synchronously when windows/panes are changed, without having to wait for `status-interval`.

(version for original report was 2.8)

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
