### ISSUE TITLE
Tmux gets killed when passing bash command

### ISSUE THREAD

**Issue by xpz3** [tmux/tmux#1629]
Using the current latest version from kali repository.
I'm opening a new session by typing following command

tmux new-session -s name "bash myscript.sh"

Above command just kills the tmux session
If you send the same command via send-keys to a background tmux session, it gets killed too.

Any other command works. For eg 
tmux new-session -s name "ls -l"
This works.
Is this a bug or am i doing something wrong?

Typing the bash myscript.sh command manually in tmux window works.
But i want to call it from another script.

**Comment by krader1961** [comment]
What do you mean "kills the tmux session"? Do you mean the session terminates? That is the expected behavior if the command terminates. So, for example, your `tmux new-session -s name "ls -l"` example also immediately terminates and thus the tmux session immediately terminates. This is no different from doing `tmux new-session -s name` to get an interactive shell within the tmux session and immediately typing `exit`. What do you expect to happen?

**Comment by nicm** [comment]
Logs? What's in the script? What tmux version?

**Comment by xpz3** [comment]
Im trying to run a very long script that takes input from users abd presents them with options to run other tools.
There's no way that a the script ends just after creating. 
Infact the same script works if i manually start the script by typing bash myscript.sh from inside the new tmux session.
If i start tmux session by sending bash myscript.sh as command

**Comment by xpz3** [comment]
Im trying to run a very long script that takes input from users abd presents them with options to run other tools.
There's no way that a the script ends just after creating. 
Infact the same script works if i manually start the script by typing bash myscript.sh from inside the new tmux session.
If i start tmux session by sending bash myscript.sh as command

**Comment by xpz3** [comment]
Accidently closed the issue

**Comment by nicm** [comment]
Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by xpz3** [comment]
`uname -sp && tmux -V && echo $TERM` outputs
```
Linux Unknown
tmux 2.8
xterm-256color
```

`uname -r` outputs `4.19.0-kali1-686-pae`

Regarding logging option 

`tmux -Ltest kill-server` outputs 
`error connecting to /tmp/tmux-0/test (No such file or directory)`
`tmux -vv -Ltest -f/dev/null new` opens a new session

But using the above scenario i cant reproduce the problem, as running `bash myscript.sh` from that tmux window or a normal tmux window does not have any issue.

The issue happens only when i try to give `bash myscript.sh` from a bash script. 
Any other commands that i give like `ls -l` shows the desired output.

**Comment by nicm** [comment]
... but what if you do:
~~~~
tmux -Ltest kill-server
tmux -vv -Ltest -f/dev/null new "bash myscript.sh"

**Comment by xpz3** [comment]
this is the log file
https://del.dog/asivoxeqod

**Comment by nicm** [comment]
Could you upload the file here please, or put it somewhere I can download it, rather than using the worst pastebin site I have ever seen?
