### ISSUE TITLE
feature request: make default formats customizeable via config

### ISSUE THREAD

**Issue by PlasmaHH** [tmux/tmux#1630]
Please consider making settings for all the default formats of commands that accept -F, which are currently hardcoded. This way one can more easily customize the view of list-sessions or choose-tree or similar without having to resort to aliases or keybindings

**Comment by nicm** [comment]
I don't think we should add options but that it would be better if command aliases could override builtin commands do you could do eg

set -s command-alias[99] "ls=ls -Fxyz"

**Comment by nicm** [comment]
Added to TODO file. Thanks.

**Comment by nicm** [comment]
Please try this [x.diff.txt](https://github.com/tmux/tmux/files/3051489/x.diff.txt) which allows you to do:
~~~~
set -s command-alias[100] "ls=list-sessions -Fmyformat"
set -s command-alias[101] "list-sessions=list-sessions -Fmyformat"
