### ISSUE TITLE
tmux set-window-option gives confusing error message when target is a window with a colon in the name and no session is specified

### ISSUE THREAD

**Issue by akleiman-stripe** [tmux/tmux#1631]
When I run a tmux command on a window with a colon in its name, tmux is unable to find the window in question:
```
-> % tmux new-window -t test-session -n name:with:colon
-> % tmux list-panes -t test-session -F '#{window_name}'
name:with:colon
-> % tmux set-window-option -t 'name:with:colon' remain-on-exit off
no such window: name:with:colon
-> % tmux list-panes -t name:with:colon -F '#{window_name}'
can't find session name
```

By contrast , running the same commands on a window with a more standard name works fine:
```
-> %  tmux set-window-option -t zsh remain-on-exit off
-> % echo $?
0
-> %  tmux list-panes -t zsh -F '#{window_name}'
zsh
```

The issue, as I see it, is that running these commands on a window with a colon in its name does not work -- the commands don't have the desired effect, and exit with a non-zero status.

Debugging info:
```
-> % uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.8
xterm-256color
```

I tried running `tmux -vv -Ltest -f/dev/null new` as requested in the contributing guide, but was unable to figure out how to get this to work in across the multiple commands I needed to run. If you would like me to run any additional commands, please let me know.

**Comment by krader1961** [comment]
From the tmux man page:

```
     target-window (or src-window or dst-window) specifies a window in the form
     session:window.  session follows the same rules as for target-session, and window is
     looked for in order as:
```

In other words, a target window name consists of a sesion name and window identifier separated by a colon. This should work: `tmux set-window-option -t 'test-session:name:with:colon' remain-on-exit off`.

**Comment by akleiman-stripe** [comment]
Ah, indeed it does. Now I feel like a fool, for if I'd used a name other than `name:with:colon`, I would have realized that the "name" in "can't find session name" is not part of a generic message, but rather the first component of "name:with:colon".

That being said, I think the "no such window: name:with:colon" is a rather confusing error message for `tmux set-window-option -t name:with:colon remain-on-exit off` case. The problem is _not_ that there isn't a window named "name:with:colon", but rather, that there is not a session named "name" (and if there was, that has a window named "with:colon").

I'm going to rename this issue to reflect the fact that the problem, if it is in fact agreed to be a problem, is in the error message displayed by `tmux set-window-option`.

**Comment by nicm** [comment]
set-option does doesn't have the split up form of the target and I don't think it is worth changing it to do so just to fix an error message like this.

I'll add a colon to "can't find session: name" though.

**Comment by akleiman-stripe** [comment]
That'll be helpful, too! I think with "can't find session: name", I would have been able to figure this out myself.

Thank you!
