### ISSUE TITLE
Unknown option: user-keys

### ISSUE THREAD

**Issue by mountainstorm** [tmux/tmux#1632]
If I enter the command: set -s user-keys[0] "\e[5;30012~"

I get the error "Unknown option: user-keys", equally if I attempt to bind "User0" it errors "Unknown key: User0".

I'm running tmux 2.8, on macOS, installed via brew, and if I "strings" the tmux binary I can see the string "user-keys" there; but it doesn't work

**Comment by mountainstorm** [comment]
Closing as it fixed itself.  Not sure what happened; I attached a debugger to my tmux instance and it wasn't stopping on any breakpoints.  So I killed it (my debugger stopped - so I know I was attached to the right instance), killed all the other tmux's I had running; and it worked the next time I ran tmux.

**Comment by nicm** [comment]
You probably still had an old tmux version running.
