### ISSUE TITLE
Feature request: capture output of choose-tree

### ISSUE THREAD

**Issue by petobens** [tmux/tmux#1634]
Hi! I was wondering if it is possible to add the ability to capture the output of `choose-tree` (in order for instance to pipe it to `fzf` preview as per this [so question](https://stackoverflow.com/q/51780445/2149400)) . Thanks in advance!

**Comment by ThomasAdam** [comment]
At the moment, this is not possible.

It would be nice to have mode-specific formats sent to STDOUT, but this is not possible.

**Comment by petobens** [comment]
Ok. Thanks anyways

**Comment by petobens** [comment]
One last question then: is it possible to replicate the generated tree by means of `tmux display-message -p  #{session_name}...`? (probably your last comment also meant that this isn't possible either but I might not have understood properly)

**Comment by nicm** [comment]
It would be good if there were formats to get the default formats for these, although in order to replicate them there would also need to be a flag to display-message to add extra, so you could specify session_format etc correctly.

For now you will need to get them from the code and use them directly.

**Comment by nicm** [comment]
Added to TODO file, note I am wrong and we do not need to add extra formats to display-message.

**Comment by petobens** [comment]
Great. Thanks!

**Comment by nicm** [comment]
I've added formats to get the default tree formats. You still have to jump through some hoops because display-message is always using a pane, so you need to use ls/lsw, something like this works:
~~~~
#!/bin/sh

tmux ls -F'#{session_id}'|while read s; do
        S=$(tmux ls -F'#{session_id}#{T:tree_mode_format}'|grep ^$s)
        echo ${S##$s}
        tmux lsw -t$s -F'#{window_id}'|while read w; do
                W=$(tmux lsw -t$s -F'#{window_id}#{T:tree_mode_format}'|grep ^$w)
                echo ${W##$w}
                tmux lsp -t$w -F'#{T:tree_mode_format}'
        done
done

**Comment by petobens** [comment]
Neat. I will try it. Thanks

**Comment by nicm** [comment]
This is a bit more efficient:
~~~~
#!/bin/sh

tmux ls -F'#{session_id} #{T:tree_mode_format}'|while read s; do
        set -- $s; s=$1; shift; echo "$@"
        tmux lsw -t"$s" -F'#{window_id} #{T:tree_mode_format}'|while read w; do
                set -- $w; w=$1; shift; echo "$@"
                tmux lsp -t$w -F'#{T:tree_mode_format}'
        done
done
