### ISSUE TITLE
after some time get `no server running on /tmp/tmux-0/default`

### ISSUE THREAD

**Issue by LuisBL** [tmux/tmux#1635]
Using the tmux packaged for synology by https://github.com/SynologyOpenSource/tmux

My usecase is:

- I run on a tmux session as root a long rsync, then detach.
- I right away I attach back it work well
- But if I attach  the day after I get this error:

```
root@NAS:~# tty
/dev/pts/3
root@NAS:~# tmux ls
no server running on /tmp/tmux-0/default
root@NAS:~# 
root@NAS:~# ll /tmp/tmux-0/
total 0
srw-rw----  1 root root    0 Mar 16 17:36 default
drwx------  2 root root   60 Mar 16 17:36 .
drwxrwxrwt 11 root root 1.7K Mar 17 10:36 ..
root@NAS:~# 
```
here is where the tmux is installed in synology, there is no .tmux.conf

```
root@NAS:~# which tmux
/usr/local/bin/tmux
root@NAS:~# ls /usr/local/bin/tmux -la
lrwxrwxrwx 1 root root 29 Mar 11 23:05 /usr/local/bin/tmux -> /usr/local/tmux/bin/tmux-utf8
root@NAS:~# ls $HOME/.tmux*
ls: cannot access /root/.tmux*: No such file or directory
root@NAS:~# 
```h
I did open an issue on https://github.com/SynologyOpenSource/tmux/issues/2 too

**Comment by LuisBL** [comment]
by the way the rsync process is still running (I see it on top)

**Comment by nicm** [comment]
If it is not running them either something is killing it or tmux is
crashing, start it with -vv and show me the logs please.

If it is still running then something is removing the socket (and another
tmux must be recreating it before you check), if so then send USR1 signal
to the server to recreate it.

**Comment by krader1961** [comment]
Define "attach a day after". Do you mean at least 24 hours after the previous attach? My guess is your system has a very aggressive policy for cleaning the */tmp* directory. For example, by default macOS removes files from */tmp* that have not been accessed in three days. From */etc/defaults/periodic.conf*:

```
# 110.clean-tmps
daily_clean_tmps_enable="YES"                           # Delete stuff daily
daily_clean_tmps_dirs="/tmp"                            # Delete under here
daily_clean_tmps_days="3"                               # If not accessed for
daily_clean_tmps_ignore=".X*-lock .X11-unix .ICE-unix .font-unix .XIM-unix"
daily_clean_tmps_ignore="$daily_clean_tmps_ignore quota.user quota.group"
                                                        # Don't delete these
daily_clean_tmps_verbose="YES"                          # Mention files deleted
```

@nicm It might be worth considering having the tmux server update the last access timestamp of the connection socket every 12 hours to mitigate this type of problem.
