### ISSUE TITLE
set-option - allow "user data" options (like environment) and "-p" pane specific options

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#1636]
I often automate tasks by launching them in panes, and use hooks to deal with panes exiting and handing cleanup.

I would like to be able to set generic "user" options, which are not meaningful tmux options but simply private data which can easily be retreived via #{...}.

In addition, the ability to set 'per pane' options would be excellent, even if "user data" options are the only ones supported initially.

For example, after creating a new pane and launching a process;

tmux set-option -p ${pane_id} "var[RESTART]" "true"

and later (in a hook) tmux show-options -p "var[RESTART]"
or even display-message -p "#{var:RESTART}"

This is just an example.  Do you see any merit in this?  I've often battled with the issue of tracking state and context when dealing with tasks in individual panes.

As an aside, is there a variant of 'show-options' which can show ONLY the value?
show-options -qw "var" suppresses errors, I would like an option to suppress the var NAME when querying a specific variable.

**Comment by nicm** [comment]
User options, and show -v (or use display-message).

**Comment by nicm** [comment]
I'm not going to support pane options, at least not in the short term, but the most common workaround is to use a window or session option with a suffix of the pane ID, for example @my_option_%1.
