### ISSUE TITLE
Allow window option 'window-size' to be set to "current"

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#1637]
Version: tmux next-29

The window option "window-size" supports "smallest" "largest" and "manual".

Please add "current" or "active" to the list of options.
When "window-size" is set to "current" or "active", ensure the window in the current terminal is always the correct size.   If I have the same window opened in three terminals, as I navigate between the terminals, the window show resize to always fit the active terminal

I am assuming you have some context to identify the active window.  The obvious options are

1. Last keyboard input
2. Mouse click
3. Focus events

Thanks

As an aside, "focus event" hooks would allow a user to implement manual window sizing on focus-gained if needed.

**Comment by nicm** [comment]
There is no current client at the moment, possibly it could use the one
with most recent input.

**Comment by nicm** [comment]
Try this please, window-size latest: 
[x.diff.txt](https://github.com/tmux/tmux/files/2998464/x.diff.txt)

**Comment by nicm** [comment]
I'm not convinced that looping over every window for each key press is a good idea however.

**Comment by tommie** [comment]
I just came across the same thing. I have a tmux over Mosh, and in a terminal. Server on my laptop and bigger client with bigger terminal on my desktop machine.

Right now, if I've done work on my laptop, I need to switch that client to another session so I can use the full size of my desktop monitor.

It would be nice if there was a `latest` mode that looked at which client made the last input. Maybe the `last_activity_time` could be used to short-circuit having to iterate over all windows:

```
int is_new_client = !timespec_equal(&c->activity_time, s->last_activity_time);

if (gettimeofday(&c->activity_time, NULL) != 0)
  fatal("gettimeofday failed");
session_update_activity(s, &c->activity_time);

if (is_new_client) {
  /* Make this the latest client. */
  RB_FOREACH ...
}
```

Depending on how `s->last_activity_time` is actually being used.

**Comment by nicm** [comment]
Did you try the patch?

**Comment by tommie** [comment]
No, I just had a look at it. It's functionally what I'm after, but your last comment indicated you weren't really happy with the current code:

> I'm not convinced that looping over every window for each key press is a good idea however.

So I suggested a path forward. :)

I can test your patch, or make a PR if you want.

**Comment by nicm** [comment]
Well if you test it first and if it works OK I'll take another look at it, if you have changes then sure open a PR.

**Comment by tommie** [comment]
The patch works fine for me. Created #1869 for review. There was one hunk failing in the patch, otherwise good against master.

Maybe it's a bit unexpected that the size changes even when I just send the tmux escape sequence, but that's probably good for consistency.
