### ISSUE TITLE
Feature request: sync only some panes of a window

### ISSUE THREAD

**Issue by adrianlzt** [tmux/tmux#1638]
Could be a nice feature to be able to select which panes will be in sync, so, for example, in the same window you can control two servers with a third window not synced.
Thanks!

**Comment by nicm** [comment]
You can do this using select-pane -d and -e.

**Comment by adrianlzt** [comment]
Yes, technically it can be done, but it is not very useful if you have several panes and want to be writing in the synced ones and in the others

**Comment by nicm** [comment]
I have no plans to extend this any further at the moment. Maybe if we ever add per-pane options (would be nice for the style as well).

**Comment by nicm** [comment]
I'll add it to the TODO file anyway.
