### ISSUE TITLE
How to use the mouse in tmux 2.1

### ISSUE THREAD

**Issue by morfikov** [tmux/tmux#164]
Hi, with the new version of tmux, the mouse behavior is really strange. I was looking for a solution that could solve my problems with the mouse, and I found some, but most of them don't work or work just partially. I just wanted to ask about a simple configuration of the mouse, and I know that many people would appreciate if someone would just explain us how to use the mouse in the new version of tmux.

I know that we can enable the mouse support via:

    set-option -g -q mouse on

But the mouse scrolling is really terrible. This is what I would expect from my mouse to do in tmux:

1. Enter the copy mode when scrolled up
2. Exit the copy mode when scrolled down to the bottom
3. Scroll the output up/down using the mouse scroll
4. Highlight some text and scroll up/down so I could highlight even more text
5. Highlight some text and move the mouse to the top/bottom edge of the screen and highlight more text
6. Highlight some text and use the middle button to paste the highlighted text
7. Customize the amount of lines that can be scrolled up/down, 5 could be good

I think that's it. Thank you in advance for any suggestions on how to implement such functionality in tmux.

**Comment by ThomasAdam** [comment]
In HEAD (after 2.1), we added a default binding to scroll which should fix your issue.  Anything else you'll have to bind yourself.

**Comment by taybin** [comment]
@ThomasAdam What was that default binding?
