### ISSUE TITLE
`window-status-current-style` doesn't work anymore

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1640]
- Operating system:     Ubuntu 16.04.6 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Tmux version:         tmux 2.8
 - `$TERM`:                rxvt-unicode-256color outside tmux, tmux-256color inside tmux
 - Shell:                zsh 5.7.1-dev-0 (x86_64-pc-linux-gnu)

Hello,

It seems that the `window-status-current-style` option has been broken recently.

Using this minimal `tmux.conf`:

    set -g prefix 'M-space'
    bind -T root M-l next
    bind -T root M-h prev
    set -gw window-status-current-format '#W'
    set -gw window-status-current-style 'bg=red'

I expect the title of the current window to be highlighted in red in the status line.
In [this commit](https://github.com/tmux/tmux/commit/1d6fe43c7b2250f042d0113da8545d5ebb75c01e), it's correctly highlighted:

![gif1](https://user-images.githubusercontent.com/8505073/54639661-3bc3a600-4a8e-11e9-9c74-719c4b9b26c1.gif)
But not anymore in [this one](https://github.com/tmux/tmux/commit/962f255ee8f271920e8901824ae30fa7a0b40804):

![gif](https://user-images.githubusercontent.com/8505073/54639681-42521d80-4a8e-11e9-8f5d-3f0b0e0b9008.gif)
Here are the logs captured with `$ tmux -vv -Ltest -f/tmp/.tmux.conf new`:
[tmux-client-23581.log](https://0x0.st/z84K.txt)
[tmux-server-23583.log](https://0x0.st/z848.txt)

**Comment by nicm** [comment]
Yes this should fix it: 
[x.diff.txt](https://github.com/tmux/tmux/files/2985579/x.diff.txt)

**Comment by lacygoill** [comment]
I can confirm that the patch fixes the issue. Thank you very much.

**Comment by mckellyln** [comment]
Thanks, this fixed it for me also.
