### ISSUE TITLE
Split panes vertical and horizontal reversed

### ISSUE THREAD

**Issue by saravanabalagi** [tmux/tmux#1641]
<kbd>Prefix</kbd> <kbd>%</kbd> splits right and <kbd>Prefix</kbd> <kbd>"</kbd> splits down. (And the separator lines think the other way?)

This happened when I did <kbd>Prefix</kbd> <kbd>%</kbd>

![image](https://user-images.githubusercontent.com/8567893/54684619-af0bfd00-4b0c-11e9-9f91-d747c8b9b95d.png)

- Ubuntu 18.04
- apt installed `tmux`

**Comment by nicm** [comment]
They are fine.

**Comment by mk-pmb** [comment]
@saravanabalagi It starts to make sense when you adjust your mental picture of % to ÷ but instead of considering the dots as the panes, think a very short bar, so it's looks more like ⋮. And for the " imagine there are a lot more of them """""""""""""""""""". ;-)
