### ISSUE TITLE
Extra column when switching pane in (neo)vim

### ISSUE THREAD

**Issue by siscia** [tmux/tmux#1642]
Info inside tmux:
```
$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.8
screen
```

Info outside tmux:
```
$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.8
xterm-256color
```

It is an issue that just appeared yesterday while using tmux and nvim together.

Basically if a split nvim, vertically, an empty column appear on the left of the right pannel when I switch tmux pane.

![Screenshot from 2019-03-20 14-36-36](https://user-images.githubusercontent.com/640555/54688982-f69b8480-4b1e-11e9-8409-8e62c1819cb7.png)

I believe the problem is tmux because it gives the same issue with neovim and vim. I could try some different program if necessary but I am not sure which one.

Tmux and (neo)vim are an essential part of my workflow... Having them not work well together anymore is a disaster for me!

I am not 100% sure that it is a tmux problem, but outside tmux nvim works perfectly.

I attached the log of tmux:
[tmux-server-8083.log](https://github.com/tmux/tmux/files/2988517/tmux-server-8083.log)

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by siscia** [comment]
Yes, exact same behaviour even in master on tag 0e0f2f765b762e5be7353c20fb408941116d3247

```
$ tmux -V
tmux next-2.9
```

**Comment by nicm** [comment]
I can't find the text in your screenshot in your server log, are you sure you opened the same file in vim?

**Comment by nicm** [comment]
Please reproduce this again with master, like this:
~~~~
tmux -vvv -Ltest -f/dev/null new
vim mytestfile
~~~~
Then reproduce the problem and when you have the problem on screen do C-b : kill-server.

Then send me the server log and the file you are using to test.

**Comment by siscia** [comment]
No it is not the same file, but it does exactly the same with any file.

**Comment by nicm** [comment]
Right but if it is not the same file, how am I meant to match up the log to what vim is sending?

**Comment by nicm** [comment]
Does this still happen in xterm?

**Comment by nicm** [comment]
Ie running tmux in xterm, not in xterm without tmux.

**Comment by siscia** [comment]
No, it does not happen in xterm! Which is a reasonable workaround!

Sending the logs as well!

**Comment by nicm** [comment]
OK what terminal are you seeing the problem in?

**Comment by siscia** [comment]
The default GNOME Terminal version: 3.18.3 on Ubuntu 16.04

**Comment by nicm** [comment]
Can you send me the tmux-out* file as well as the server log and I will see if I see a difference between xterm and gnome-terminal and figure out what it is doing wrong.

**Comment by siscia** [comment]
Here the logs for this image: 

![image](https://user-images.githubusercontent.com/640555/54693443-f4d5bf00-4b26-11e9-9a34-3a0b353af1d0.png)
[tmux-out-20496.log](https://github.com/tmux/tmux/files/2988720/tmux-out-20496.log)
[tmux-server-20496.log](https://github.com/tmux/tmux/files/2988721/tmux-server-20496.log)
[tmux-client-20494.log](https://github.com/tmux/tmux/files/2988722/tmux-client-20494.log)

**Comment by nicm** [comment]
I have this:
~~~~
$ gnome-terminal --version
# GNOME Terminal 3.30.2 using VTE 0.54.2 +GNUTLS
~~~
And I can't reproduce this by sending the same as tmux is sending. Can you try a newer VTE or a newer gnome-terminal?

Did you upgrade vte or gnome-terminal recently?

What if you set "TERM=vte" in gnome-terminal does that fix it?

**Comment by nicm** [comment]
I wonder if gnome-terminal things the line separators are two cells wide. If you go to the preferences and "Compatibility", there is an option "Ambiguous-width characters". What is that set to? If it is wide, try changing it to narrow:
![xxx](https://user-images.githubusercontent.com/304243/54694576-56465f80-4b20-11e9-8537-886b3cc1bb53.png)

**Comment by siscia** [comment]
Yeah! You are amazing!

Indeed it was the "Ambiguos-width characters" setting.
I was making some test with utf-8 and I changed it to Wide.

Changing it back to narrow seems to solve the issue!

**Comment by siscia** [comment]
Yeah! You are amazing!

Indeed it was the "Ambiguos-width characters" setting.
I was making some test with utf-8 and I changed it to Wide.

Changing it back to narrow seems to solve the issue!

Do you got PayPal? I would like to offer you a beer :beers:

**Comment by nicm** [comment]
Great stuff.
