### ISSUE TITLE
Change tmux default temporary location `/tmp/tmux-1000`

### ISSUE THREAD

**Issue by saravanabalagi** [tmux/tmux#1646]
I would like to change where `tmux` stores temp info. 

Currently it's storing at `/tmp/tmux-USERID`, is it possible to specify an `ENV` variable instructing tmux to store it there?

PS: If you were wondering why I would want to change this, I'm containerizing things, so writing to `tmp` is leaking things :(

**Comment by nicm** [comment]
Use -S or TMUX_TMPDIR.

**Comment by saravanabalagi** [comment]
I tried setting `TMUX_TMPDIR`, but I guess I need to restart tmux. I tried `pkill -USR1 tmux`, `pkill -f tmux`, and `tmux kill-server`. But it seems that it tries to persist where it is currently.

**Comment by nicm** [comment]
Yes you need to restart.

**Comment by saravanabalagi** [comment]
Sorry to open the issue again, but I couldn't get it working even after setting `TMUX_TMPDIR`. I tried killing tmux in the aforementioned ways, but couldn't get it to store it on `TMUX_TMPDIR`. Could you please give me more help in doing the same? Thanks

**Comment by nicm** [comment]
How are you setting TMUX_TMPDIR? What does this show:

tmux kill-server
mkdir /tmp/foo
export TMUX_TMPDIR=/tmp/foo
tmux new -d
tmux display -pF '#{socket_path}'

**Comment by saravanabalagi** [comment]
Works perfectly, thanks :)
