### ISSUE TITLE
Attach to another isolated session from existing session

### ISSUE THREAD

**Issue by xpz3** [tmux/tmux#1648]
I'm using 2.83 version from kali repo.
I have a question. I'm manually opening a tmux session from terminal. Then attaching to it. From inside that first session i run a script that creates another session in the background. Everything works till now. 
Question
Is it possible to programmatically switch to the newly created session from the script running on the first tmux session without user interaction and without unsetting the TMUX variable?

**Comment by nicm** [comment]
Use switch-client.

**Comment by xpz3** [comment]
Hey it worked and thanks again for the proooompt support!!!
