### ISSUE TITLE
Status line color behavior has changed.

### ISSUE THREAD

**Issue by h-michael** [tmux/tmux#1651]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

- your platform (Linux, OS X, or whatever)
Linux
- a brief description of the problem with steps to reproduce;
```
set-option -g display-panes-active-colour "#66d9ef"
set-window-option -g window-status-current-format "#[fg=default,bg=default,default] #I #W"
set-window-option -g window-status-current-style "fg=#000000,bg=#66d9ef"
```
Status line color behavior has change between commit hash 1d6fe43c7b2250f042d0113da8545d5ebb75c01e and [current master](0292243b296b40de6c4b010cc89c6a89b97e37c5).
And this occurred with [Alacritty](https://github.com/jwilm/alacritty).
But not occurred with xterm.

- a minimal tmux config, if you can't reproduce without a config;
```
set-option -g display-panes-active-colour "#66d9ef"
set-window-option -g window-status-current-format "#[fg=default,bg=default,default] #I #W"
set-window-option -g window-status-current-style "fg=#000000,bg=#66d9ef"
```

- your terminal, and $TERM inside and outside of tmux;
```
inside tmux with alacritty
$ echo $TERM
screen-256color
```

```
outside tmux with alacritty
$ echo $TERM
alacritty
```

But If I use xterm as terminal emulator.
This does not occured.
```
inside tmux with xterm
$ echo $TERM
screen
```

```
outside tmux with xterm
$ echo $TERM
xterm
```

**Comment by nicm** [comment]
...changed how?

**Comment by h-michael** [comment]
Sorry, I submit Gif tomorrow.

**Comment by h-michael** [comment]
1d6fe43c7b2250f042d0113da8545d5ebb75c01e
<img width="521" alt="スクリーンショット 2019-03-25 11 45 17" src="https://user-images.githubusercontent.com/4556097/54892093-7fd20300-4ef3-11e9-8822-b00ddadcb288.png">

current master 0292243b296b40de6c4b010cc89c6a89b97e37c5
<img width="521" alt="スクリーンショット 2019-03-25 11 43 14" src="https://user-images.githubusercontent.com/4556097/54892100-895b6b00-4ef3-11e9-93a6-a625a3fc16d7.png">

**Comment by nicm** [comment]
Does it fix it if you have TERM=xterm outside tmux in alacrity?

**Comment by nicm** [comment]
Actually your config options are wrong:
~~~~
set-window-option -g window-status-current-format "#[fg=default,bg=default,default] #I #W"
set-window-option -g window-status-current-style
~~~~
The default fg and bg in window-status-current-format will override window-status-current-style.

**Comment by nicm** [comment]
Or did you mean window-status-format?

**Comment by h-michael** [comment]
> Does it fix it if you have TERM=xterm outside tmux in alacrity?

No, same behavior occurs.

**Comment by h-michael** [comment]
I try with iTerm.
```
outside tmux
$ echo $TERM
xterm-256color
```

```
inside tmux
$ echo $TERM
screen
```

Same behavior occurred.

**Comment by nicm** [comment]
The newer screenshot is correct (default colour rather than blue) for the
config you gave me, is your problem that it is different in xterm? Are you
sure the config you showed is correct?

**Comment by h-michael** [comment]
> The newer screenshot is correct (default colour rather than blue) for the
config you gave me

Thanks for your helping me.
Does it means that current master behavior is intended behavior?
If that's, I'll fix my config and check behavior with alacrity, iTerm and xterm :)

**Comment by nicm** [comment]
Yes if you set the colour or attributes in window-status-format it will
override window-status-style, I don't know why if worked before. The way
default worked used to be a little different.

**Comment by h-michael** [comment]
@nicm My issue has resolved! Thanks :)

**Comment by execb5** [comment]
Hello, I'm having the same issue of the status-current being different in 2.9, but I'm having no luck in finding out which part of my config is the problematic one, can you guys help me?

```
# Colors
set-option -g status-style fg=white,bg=default,default
set-window-option -g window-status-style fg="#666666",bg=default,default
set-window-option -g window-status-current-style fg=red,bg=default,default
set-option -g message-style fg=white,bg=black,bright

# Status bar
set-option -g status-position bottom
setw -g window-status-format         ' #(echo "#{pane_current_command}") '
setw -g window-status-current-format ' #(echo "#{pane_current_command}") '
set -g status-right '%d/%m %H:%M'
```

These are my settings related to the status bar, the terminal I use is rxvt-unicode and the issue also happens in the xfce-terminal that I also have on my machine.

![Screenshot_2019-06-17_23-06-02](https://user-images.githubusercontent.com/6979113/59648243-c763d600-9154-11e9-91c2-85ec99b41466.png)

**Comment by nicm** [comment]
Does it still happen with master or 3.0-rc?

**Comment by execb5** [comment]
Tested with both master and 3.0-rc and still having the same issue. Originally I was using the one from pacman (manjaro).

Here is my full tmux.conf just in case I'm not seeing something that overrides that color.

```
set-window-option -g xterm-keys on


set -s escape-time 1


# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1


# Reload this file
bind r source-file ~/.tmux.conf \; display "Reloaded!"


# Split pane  to current directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"


# Movement keys (like vim)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


# Window list in left
set -g status-left " "
set -g status-justify left
set -g status-right " "


# Ohter window activitie
setw -g monitor-activity on
set -g visual-activity on


# Colors
set-option -g status-style fg=white,bg=default,default
set-window-option -g window-status-style fg="#666666",bg=default,default
set-window-option -g window-status-current-style fg=red,bg=default,default
set-option -g message-style fg=white,bg=black,bright


# Status bar
set-option -g status-position bottom
setw -g window-status-format         ' #(echo "#{pane_current_command}") '
setw -g window-status-current-format ' #(echo "#{pane_current_command}") '
set -g status-right '%d/%m %H:%M'


# Vim mode
setw -g mode-keys vi


# New window to current directory
bind c new-window -c "#{pane_current_path}"


# Disable renaming
set-option -g allow-rename off


# Increase terminal buffer
set-option -g history-limit 5000


# Set title of the window to the session
set-option -g set-titles on
set-option -g set-titles-string '#S'


# Fix tmux colors
set -g default-terminal "rxvt-unicode-256color"
set -ga terminal-overrides ',rxvt-unicode-256color:Tc'
```

**Comment by nicm** [comment]
You are resetting everything to default, styles are parsed from left to
right:
~~~~
set-window-option -g window-status-current-style fg=red,bg=default,default
~~~~

**Comment by execb5** [comment]
Damn!, I knew it must be something stupid!

It's working now, thank you!

**Comment by nriley** [comment]
I’m having trouble getting my configuration to work like it did prior to this change.  Particularly I want there to be an extra space of padding in the default background color (blue) before the highlighted text (either current or activity).

This previously worked:

```
set -g status-style "bg=blue,fg=white"
setw -g window-status-current-style "bg=black,bright"
setw -g window-status-activity-style "bg=red,bright"

setw -g window-status-format "#[bg=blue] #[default]#I #W"
setw -g window-status-current-format "#[bg=blue] #[default]#I #W"
```

I can make the current window’s format match the prior setup even if `#[default]` doesn’t default to `window-status-current-format`, but there is no `window-status-activity-format` so I can’t do the same for windows with activity  The best I can do is to remove the embedded styles completely from `window-status-format` but this means I have an extra highlighted space before the window title, which doesn’t look like what I want.

Before this change:

![939EC271-15C8-4616-9CB2-C85AD4946700](https://user-images.githubusercontent.com/68303/72211879-dddecf80-34a0-11ea-915b-2e9527810483.jpeg)

After this change, the best I can do is:
![ADE3AA9D-8F12-4DD6-BE4C-DA09EDCD74F3](https://user-images.githubusercontent.com/68303/72211908-1a123000-34a1-11ea-9453-fe9c5c577542.jpeg)

Is there any workaround for this? Thanks!

**Comment by nicm** [comment]
Your best bet would be to upgrade.

**Comment by nriley** [comment]
Sorry I must have been unclear. The 2nd screenshot "after this change" is tmux 3.0a.  The first screenshot "before this change" is tmux 2.3.  Is there any way to get tmux 3.0a to look like tmux 2.3?

**Comment by nicm** [comment]
No try master which has push-default. Otherwise you will need to use the
window_activity_flag format.

**Comment by nriley** [comment]
Thanks — "upgrade" did not equal "master" to me.  `push-default` (motivated in #1989, documented in #1912) works great in master:

```
setw -g window-status-format "#[push-default]#[bg=blue] #[default]#I #W"             
```

To see if I could make it work in 3.0a, I tried to use `window-activity-flag` but got stuck. It seems to be changing the foreground not the background color when I do this (without `window-status-activity-style` set):

```
setw -g window-status-format " #{?window_activity_flag,#[bg=red#,bright],}#I #W"   
```

<img width="99" alt="image" src="https://user-images.githubusercontent.com/68303/72224073-416e0900-3544-11ea-8020-111f4cf3ea92.png">
