### ISSUE TITLE
tmux 2.8 release tarball has wrong version string

### ISSUE THREAD

**Issue by living180** [tmux/tmux#1652]
The tmux 2.8 release tarball at https://github.com/tmux/tmux/releases/download/2.8/tmux-2.8.tar.gz contains a version string of `2.8-rc` in `configure.ac` instead of the expected `2.8`.  As a result, if tmux is built from this tarball, `tmux -V` reports `tmux 2.8-rc` instead of `tmux 2.8` as expected.

**Comment by nicm** [comment]
No it doesn't.

**Comment by living180** [comment]
So sorry for the noise - I've double-checked and you are right.  Somehow I must have been looking at the wrong file on my system. :flushed:
