### ISSUE TITLE
Bell Sound on Start and Stop

### ISSUE THREAD

**Issue by chrixm** [tmux/tmux#1654]
Tried this on both tmux 1.8 on CentOS 7 as well as tmux 2.8.1 from IUS repository on CentOS 7. With no custom configuration (i.e. no ~/.tmux.conf), whenever I start tmux from the shell using "tmux" I get a terminal bell sound and whenever I exit tmux I also get a terminal bell sound.

I have tried to create a "~/.tmux.conf" to disable bell-action, but I can't stop the bell sound. If it helps I am SSH'ing into the CentOS 7 box from PuTTY on Windows. I can of course disable the bell in PuTTY, but this stops legitimate bell sounds.

**Comment by nicm** [comment]
TERM? Logs?

**Comment by chrixm** [comment]
The TERM is set to xterm. 
[tmux-client-6909.log](https://github.com/tmux/tmux/files/3012444/tmux-client-6909.log)
[tmux-server-6911.log](https://github.com/tmux/tmux/files/3012445/tmux-server-6911.log)

**Comment by nicm** [comment]
tmux is not sending a BEL to the terminal at startup so your terminal
must be generating it as a side effect to some other escape sequence.

Does it go away if you use TERM=putty outside tmux instead?

**Comment by chrixm** [comment]
Yes it does.. :)
