### ISSUE TITLE
stop-selection not working for select-line and select-word

### ISSUE THREAD

**Issue by avih** [tmux/tmux#1655]
With current tmux master, I'm using this minimal config:
```
set-option -g mode-keys vi
set-option -g mouse on
bind -Tcopy-mode-vi S send -X stop-selection
```

Steps:
- Enter copy mode.
- With the mouse - double or triple click a word ( -> word or line selected, respectively).
- Press `S` to stop selection.
- Use the arrow keys to move the cursor down -- works fine and selection is not extended.
- Use the arrow keys to move the cursor up and beyond the selection -- selection is unexpectedly manipulated by the cursor movement.

My proposed patch which seems to fix it is:
```diff
diff --git a/window-copy.c b/window-copy.c
index 062d687f..63c5aa0a 100644
--- a/window-copy.c
+++ b/window-copy.c
@@ -610,8 +610,10 @@ window_copy_command(struct window_mode_entry *wme, struct client *c,
                                redraw = 1;
                        }
                }
-               if (strcmp(command, "stop-selection") == 0)
+               if (strcmp(command, "stop-selection") == 0) {
                        data->cursordrag = CURSORDRAG_NONE;
+                       data->lineflag = LINE_SEL_NONE;
+               }
                if (strcmp(command, "bottom-line") == 0) {
                        data->cx = 0;
                        data->cy = screen_size_y(sn) - 1;

```

On a somewhat related note, `select-line` is documented, but `select-word` is not.

**Comment by nicm** [comment]
Applied,  thanks.

**Comment by avih** [comment]
Eh.. the report/fix above was for commit 6ac84585 from two days ago, though current master has a rewrite of copy commands handling at 9f8d193b ... which makes my patch incompatible, though the exact same bug still exists even after the rewrite...

**Comment by avih** [comment]
> Applied, thanks.

Thanks, but for me master is 6861045d and the issue is not fixed in it. Do you have the fix commit applied elsewhere which will be mirrored to github later?

**Comment by nicm** [comment]
yes it will sync later
