### ISSUE TITLE
[feature request] search/line-selection through line-wrap

### ISSUE THREAD

**Issue by avih** [tmux/tmux#1656]
TERM inside and outside: xterm-256color
Tmux version: master

In (vi) copy mode, currently backlog search, select-line (command or triple click) and copy-line (command) operate on visible lines, which could be only part of the original line if it's wrapped by the view.

It would be nice if triple-click selected a full original line (multiple lines of the view if wrapped), and if back-search would search through the wrapping as if it wasn't wrapped.

The original line data does exist someplace, as evident by it being unwrapped correctly if the terminal or pane size are increased enough.

This issue was reported before for tmux 2.3: #843 , though I find the reply unsatisfactory because it's about lines which tmux itself wraps and therefore theoretically tmux has all the required data (rather than lines which an application outputs wrapped - where tmux doesn't necessarily know if it's wrapped or distinct lines).

**Comment by avih** [comment]
> This issue was reported before for tmux 2.3: #843

Actually it was not reported before. #843 is about terminal selection (e.g. using shift with xterm) through tmux's wrapped output, while this issue is about tmux's own line-select where the full original line is known.

**Comment by nicm** [comment]
This is in the TODO file already:
~~~~
        * searching in copy mode should unwrap lines, so if you search for "foobar"
          then it should be found even if it is now "foo\nbar" (if the WRAP flag
          is set on the line)
~~~~

**Comment by avih** [comment]
Right, though wrapped-line selection isn't as far as I can tell.

**Comment by nicm** [comment]
Once search unwraps can worry about that.
