### ISSUE TITLE
Failing to save/restore "DEC private mode values"

### ISSUE THREAD

**Issue by craigbarnes** [tmux/tmux#1658]
It seems as if tmux is failing to restore some "DEC Private Mode Values", as described by the xterm [ctlseq](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) page:

```
CSI ? Pm h
          DEC Private Mode Set (DECSET).
            ...
            Ps = 1 0 0 0  -> Send Mouse X & Y on button press and release
            Ps = 1 0 0 6  -> Enable SGR Mouse Mode, xterm.

CSI ? Pm s
          Save DEC Private Mode Values.  Ps values are the same as for
          DECSET.

CSI ? Pm r
          Restore DEC Private Mode Values.  The value of Ps previously
          saved is restored.  Ps values are the same as for DECSET.
```

If I use the following script:

```sh
#!/bin/sh

if test "$1" = enable; then
    # Save and enable mouse tracking
    printf "\033[?1000s"
    printf "\033[?1000h"
    # Save and enable SGR mouse protocol
    printf "\033[?1006s"
    printf "\033[?1006h"
elif test "$1" = restore; then
    # Restore
    printf "\033[?1006r"
    printf "\033[?1000r"
else
    echo "Usage: $0 enable|restore" >&2
    exit 1
fi
```

When running `tmux` inside `xterm`, after running `./mouse enable` and clicking the mouse keys, I can see the escape codes sent to the tty. However, if I then run `./mouse restore` and click the mouse again, the escape codes are _still_ being sent.

If I repeat the same process inside a plain `xterm` session, it behaves as expected -- after running `./mouse restore` clicking the mouse no longer spams the shell with escape codes.

It seems as if `tmux` is failing to save or restore (or forward to `xterm`) the private mode values. Are these control codes just not supported or is this a bug?

System info:

```
$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.8
screen-256color
```

**Comment by nicm** [comment]
tmux doesn't support these escape sequences, along with a few other private mode bits and pieces. Does anything use them?

**Comment by craigbarnes** [comment]
> Does anything use them?

I use the ones for saving/setting/restoring the xterm `metaSendsEscape` option in [dte](https://gitlab.com/craigbarnes/dte). I was considering also using the mouse codes mentioned above, but it's not really an option if tmux doesn't support them. I guess I'll have to fall back to enable/disable instead of save/enable/restore.

**Comment by nicm** [comment]
Well we can add them, they are harmless, but they are pretty esoteric and it seems a bit pointless if nothing uses them.

**Comment by nicm** [comment]
Why not just turn on the mouse modes you want and reset them on exit? That's what everything else does, including tmux. There is no expectation that applications necessarily leave the terminal the way they found it.

**Comment by craigbarnes** [comment]
Yeah that seems like the best option. I initially tried the save/enable/restore model because `dte` (optionally) does the same thing with window titles, but thinking about it more, with mouse modes there's really no reason to not just enable/disable.

Thanks for the quick reply :+1:
