### ISSUE TITLE
message from syslogd shows only on tmux

### ISSUE THREAD

**Issue by arty-hlr** [tmux/tmux#1659]
Hi,

I get these messages from syslogd after waking up from sleep, but only in tmux, and whether the terminal is attached to the session or not. My version of tmux is 2.8, I'm on Parrot OS, and I am using screen as TERM. Here is an example of what happens each time:

```
Message from syslogd@parrot at Mar 28 23:17:54 ...
 kernel:[177769.535034] mce: [Hardware Error]: CPU 0: Machine Check: 0 Bank 5: ee0000000040110a

Message from syslogd@parrot at Mar 28 23:17:54 ...
 kernel:[177769.535035] mce: [Hardware Error]: TSC 0 ADDR fef82240 MISC 78a0000086

Message from syslogd@parrot at Mar 28 23:17:54 ...
 kernel:[177769.535040] mce: [Hardware Error]: PROCESSOR 0:40651 TIME 1553811472 SOCKET 0 APIC 0 microcode 24

Message from syslogd@parrot at Mar 28 23:17:54 ...
 kernel:[177769.535044] mce: [Hardware Error]: CPU 0: Machine Check: 0 Bank 6: ee0000000040110a

Message from syslogd@parrot at Mar 28 23:17:54 ...
 kernel:[177769.535044] mce: [Hardware Error]: TSC 0 ADDR fef82300 MISC 78a0000086

Message from syslogd@parrot at Mar 28 23:17:54 ...
 kernel:[177769.535048] mce: [Hardware Error]: PROCESSOR 0:40651 TIME 1553811472 SOCKET 0 APIC 0 microcode 24
```

I tried `dmesg --console-off` but that didn't change it, it stills prints that, even though with a terminal without tmux running it doesn't.

Any idea why that happens only with tmux, and how to avoid it?

Thanks in advance!

**Comment by nicm** [comment]
Doesn't sound like anything to do with tmux. Did you try "mesg n" in the pane you are getting them on?

**Comment by arty-hlr** [comment]
Well I guess, the messages don't at least, but it only happens with tmux, and on all my sessions everytime, which is kinda annoying.

I just tried it, it says `write access to your terminal is denied`

**Comment by nicm** [comment]
It sounds like syslogd has decided that it should send these messages to a terminal rather than a file and that a pty inside tmux is the best place to send them. Are you sure you didn't restart syslogd from inside tmux?

I can't help you with syslogd on Linux, your best bet is to ask the syslogd developers or your platform's maintainers.

**Comment by nicm** [comment]
Oh is it going to every pane? Do you have tmux built with utempter? Maybe it is sending it to every logged in tty.

There is probably a way to turn it off. Ask the syslogd authors.

**Comment by arty-hlr** [comment]
It's going to one window on each session, attached or not, not on every pane, sorry if I was unclear.

I kinda see what you mean, I'll take this to syslogd then! Thanks for the help!
