### ISSUE TITLE
tmux 2.1 status bar: fixed-width window-status-format while switching?

### ISSUE THREAD

**Issue by lilydjwg** [tmux/tmux#166]
I have this:
```
set-window-option -g window-status-format "#I#F#W"
```

It rendered like this before 2.1:
```
0 zsh 1 zsh 2-git 3*zsh
```

But it renders like this now:
```
0zsh 1zsh 2-git 3*zsh
```

The `*` indicates the current window, and `-` the previous one. Nothing for others so I get an empty string now.  When I switch windows, many characters move, which is distracting for me.

I've read through the man page, but didn't find a way to accomplish a fixed-width format for the content.

**Comment by nicm** [comment]
It's in the default option...

#{?window_flags,#{window_flags}, }

**Comment by lilydjwg** [comment]
Thanks! So the empty string is also a false value?

**Comment by nicm** [comment]
Yes it is.
