### ISSUE TITLE
Question:  In vi copy mode, can `select-word` select entire word included part of breaking to next line?

### ISSUE THREAD

**Issue by fengyichui** [tmux/tmux#1661]
Hi,

In vi copy mode, can `select-word` select entire word included part of breaking to next line?

My `.tmux.conf`:
> set -g mouse on
  bind-key -T copy-mode-vi DoubleClick1Pane   select-pane -t= \; send -X select-word

Steps:
1. $ perl -e 'print "x"x400'
2. Double click the `xxx...`, but only one line is selected.
![1](https://user-images.githubusercontent.com/17896291/55317708-a5d34680-54a3-11e9-9aaa-703232c81ba0.png)

$ uname -sp && tmux -V && echo $TERM
> Linux x86_64
  tmux 2.6
  screen-256color

I tested the latest tmux version, the same phenomenon

**Comment by moritzdietz** [comment]
I believe this is already covered in the TODO file. See: https://github.com/tmux/tmux/blob/master/TODO#L39-L55

So currently this seems to be a not implemented functionality. But please correct me if my assumption is not right.

**Comment by fengyichui** [comment]
Thanks.
