### ISSUE TITLE
Key inputs are inconsistent

### ISSUE THREAD

**Issue by arielnmz** [tmux/tmux#1662]
If I open my normal terminal and do `$ cat` and then press `C-←`, for example, I see this:

`^[Od`

But when run in tmux I see:

`^[[1;5D`

`echo $TERM` inside tmux returns `screen-256color`, outside: `rxvt-unicode-256color`

This is my `.tmux.conf` file:

`set -g default-terminal "screen-256color"`

The results are the same with `screen/tmux-256color` even `rxvt-unicode-256color`

Platform: Fedora 29 Linux 5.0.4-200.fc29.x86_64
Tmux: tmux 2.8

Edit:
I'm using` zsh 5.6.2 (x86_64-redhat-linux-gnu)`

**Comment by krader1961** [comment]
Works for me. That is, `\e[1;5D` is the correct sequence for [ctrl-left-arrow] and is what I see both inside and outside of tmux. Also, a plain left-arrow should normally send `\eD` or `\eOD` not `\eOd`. I'm guessing you typed that info rather than copy/pasting and made a mistake.

Note that tmux won't change what your terminal sends when you press specific keys. So you're not doing what you think you're doing.

**Comment by arielnmz** [comment]
I think an image is worth more than words:

![image](https://user-images.githubusercontent.com/24735547/55599395-ce15ac00-5714-11e9-960f-0f45b63392b7.png)

I didn't type anything, I just copy-pasted from urxvt, btw I'm not saying that tmux is "changing what my terminal sends", just that the inputs received are inconsistent, Also, this only seems to happen with tmux+urxvt. I also tried with a "bare" zsh (no user settings loaded) and even bash. I tried it with Fedora 28 and 24 as well, and the result is the same. But, xterm and xfce4-terminal seem to work fine (and also display `^[[1;5D`, as you said), so what could be the problem with urxvt?

**Comment by krader1961** [comment]
> Also, this only seems to happen with tmux+urxvt.

Huh? Your screenshot shows that pressing [ctrl-left-arrow] sends the expected sequence when you are in a tmux session. It's the `\eOd` outside of tmux that is weird. The sequence you're seeing outside of tmux is what the terminal sends for [left-arrow] when in "application keypad mode" (also "application cursor key mode" and other variants on that theme). Which should not be enabled when at a shell prompt. It's meant to be enabled only when running an application that explicitly enables it. Starting a tmux session is causing the terminal to switch from application keypad mode to numeric keypad mode. See https://vt100.net/docs/vt102-ug/chapter5.html#S5.5.2.14

Do you see the weird, application keypad mode, `\eOd` in a fresh rxvt terminal in which you haven't run any program other than the shell? If so then you've somehow configured rxvt to default to application keypad mode. Which is a really bad idea.

**Comment by arielnmz** [comment]
Well, yeah, I was talking about the "discrepancy", not that urxvt was doing the right thing

> If so then you've somehow configured rxvt to default to application keypad mode

Well, of course it wasn't me. That's urxvt right from the fedora repos, maybe I shoudl file a bug over there? I guess it makes sense since I have seen this on Fedora 29, 28 and even all the way back to 24, and that it

> is a really bad idea.

as you say

**Comment by nicm** [comment]
Different terminals send different sequences for control keys. These are
both fine. rxvt derived terminals send C-Left as \033Od, xterm uses
\033[1;5D. tmux follows xterm here.

**Comment by nicm** [comment]
> I'm not saying that tmux is "changing what my terminal sends"

This is exactly what it is doing and is part of the purpose of tmux. If you
are to be able to detach tmux from xterm and attach it to rxvt without
restarting applications inside tmux, they have to see the same interface no
matter which terminal tmux is running in. It would be no good if you ran
"tmux attach" in xterm and suddenly all your applications stopped
recognising C-Left.

It isn't always that easy of course, there are sometimes keys that one
terminal just doesn't support at all, but there isn't much we can do about
that.

**Comment by arielnmz** [comment]
Guess that solves this, ty
