### ISSUE TITLE
tmux capture-pane doesn't capture first line

### ISSUE THREAD

**Issue by nmeum** [tmux/tmux#1663]
tmux git HEAD (e33b623f2171e7fefa8b24c4be6cac5b4d7899f8) does not include the first pane line in a `tmux capture-pane` output on Alpine Linux Edge when `remain-on-exit` is set under certain circumstances.

The following script creates a tmux session demonstrating this problem:

```shell
#!/bin/sh

tmux new-session -d -s test cat
tmux set-window-option -t test remain-on-exit on
pid=$(tmux list-panes -t test -F "#{pane_pid}")

tmux send-keys -t test foo Enter bar Enter C-d
wait "${pid}"

tmux capture-pane -p -t test
```

The output of this script is:

```
bar
foo
bar

<…>

Pane is dead (status 0, Fri Apr  5 11:57:10 2019)
```

I would have expected the output to be:

```
foo
bar
foo
bar

<…>

Pane is dead (status 0, Fri Apr  5 11:57:10 2019)
```

instead and if you attach to the session after invoking the script you well see that this is the actual output. Capturing the pane after an initial attach also produces the correct output.

I am not sure if this really a bug or if this is expected behavior, I duck around in `server-fn.c` and noticed that the following patch fixes this problem:

```patch
diff --git a/server-fn.c b/server-fn.c
index 90db7d51..c7cb220d 100644
--- a/server-fn.c
+++ b/server-fn.c
@@ -322,7 +322,6 @@ server_destroy_pane(struct window_pane *wp, int notify)
 		screen_write_start(&ctx, wp, &wp->base);
 		screen_write_scrollregion(&ctx, 0, screen_size_y(ctx.s) - 1);
 		screen_write_cursormove(&ctx, 0, screen_size_y(ctx.s) - 1, 0);
-		screen_write_linefeed(&ctx, 1, 8);
 		memcpy(&gc, &grid_default_cell, sizeof gc);
 
 		time(&t);
```

I have no idea though why the patch fixes it and why the linefeed is needed in the first place.

**Comment by nicm** [comment]
remain-on-exit scrolls the entire screen up by one line, so the first line (the "foo" you are missing) will be in the history. Without the linefeed the "Pane is dead" line will overwrite the last line of the screen.

You need to use add -S -1 to capture-pane.

**Comment by nmeum** [comment]
Oh, didn't realize that `-S` can take negative arguments as well, works now. Thanks for pointing that out and sorry for bothering you with this.
