### ISSUE TITLE
having trouble launching tmux on Mac

### ISSUE THREAD

**Issue by p-z-l** [tmux/tmux#1664]
**Version: tmux 2.8.1**

could not launch tmux successfully:

<img width="556" alt="Screen Shot 2019-04-05 at 8 20 55 PM" src="https://user-images.githubusercontent.com/43706386/55627328-7ba1c180-57e0-11e9-929b-e53a65913773.png">

**Comment by nicm** [comment]
Looks like you don't have the right ncurses library.

**Comment by p-z-l** [comment]
yeah. I tried installing ncurses using `brew install ncurses` install dyld by `brew install dyld-headers`
but still not working

**Comment by nicm** [comment]
Did you build tmux from source?

**Comment by p-z-l** [comment]
no. should I try?

**Comment by nicm** [comment]
No you would be best to whoever made the tmux package you are trying to use.
