### ISSUE TITLE
Request: Consider adding user command-aliases to 'list-commands' output

### ISSUE THREAD

**Issue by fourjay** [tmux/tmux#1665]
The trigger is trying to guess what level of quotes are passed down into a user command-alias. Lot's of guesses, with no real visibility of what's actually being passed into the command-alias :-)
This seems a useful addition for other user command-alias functions

Just for background, I'm trying to make a frictionless one-line background note taking command (using jrnl.sh). I can create an alias for run-shell -b, but not pass anything but static arguments to the command alias (no templating, another possible feature). I've tried experimenting with a command-prompt variant, but the right quoting is beyond my humble skills.

**Comment by nicm** [comment]
How would list-commands help with this problem? Also command-alias don't have a usage so I don't think they would fit.

command-alias is a direct substitution so quoting shouldn't come into it.
