### ISSUE TITLE
Support '%' vim binding when in copy mode (feature request)

### ISSUE THREAD

**Issue by chrisbarber** [tmux/tmux#1666]
Platform: macOS 10.13.6
**Tmux version: 2.8** (from homebrew)

```
$ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.8
xterm-256color
```

Config:
```
setw -g mode-keys vi
```

When entering copy mode to inspect compiler or runtime errors, it would be useful to have support for the '%' vim-binding, to find matching braces in complicated signatures or code listings.

**Comment by nicm** [comment]
You can probably do this with something like:
~~~~
bind -Tcopy-mode X set word-separators '()' \; send -X next-word \; set -u word-separators

**Comment by chrisbarber** [comment]
More is needed, unfortunately. For example, the correct behavior with cursor in the first position of `(())` is to jump to the fourth/last position. You really need to be able to read under the cursor, move around, do control flow/logic, and keep a counter variable etc.

I am looking at tmux extensibility and it looks like it is often done with bash scripts. While that answers the questions of control flow, counter variables, etc, it doesn't answer whether one can read under the cursor and move around arbitrarily in the scrollback buffer.

**Comment by nicm** [comment]
I think you or someone familiar with how it should work will need to implement this, or you'll need to give a much better explanation of what it does.

**Comment by chrisbarber** [comment]
I realized that if I wanted this I could just run a `:terminal` in vim within tmux. I was thinking `%` would be trivial to implement but may not be worth the effort. Closing own feature request.

**Comment by nicm** [comment]
Well it might be but you haven't really explained what it does and all I can really figure out is that it jumps to the next bracket.

**Comment by chrisbarber** [comment]
Sorry about that. I'm not sure how common of a feature it is outside of vim, in IDE's or other editors. I guess it is common maybe to highlight matching braces, but not necessarily jump between them.

Basically if the cursor is here:
```
( ( ) ( ( ) ) )
      ^
```
And you press `%`, it will jump to here:
```
( ( ) ( ( ) ) )
            ^
```
The basic procedure is, if on a '(', then scan forward, incrementing a counter (initialized to 1) for subsequent '(', and decrementing for ')'. If the counter goes to zero then move the cursor to that position, else if it never goes to zero before hitting the end of the string/buffer, then just leave the cursor where it is. If the cursor starts on ')', do the analogous thing scanning to the left. And do the analogous things also for other brace types, '[]' and '{}'.

All that's necessary is this counter, because it only concerns itself with one brace type (parens, square, curly) at a time, which can't have any issues other than being left open beyond one or both ends of the string. So if the cursor is here:
```
([{)]}
  ^
```
It will happily jump to here:
```
([{)]}
     ^
```
Checking for mismatched braces requires a stack, but like I said that's not what we're doing.

Anyways... Not too complicated to implement, but could require some thought about performance if the scroll back buffer is large.

**Comment by nicm** [comment]
Turns out this is C-M-f and C-M-b in emacs.

Try this please, forward search only for the moment: [tmux-next-bracket.diff.txt](https://github.com/tmux/tmux/files/3123012/tmux-next-bracket.diff.txt)

**Comment by nicm** [comment]
Oh this won't work with prefix != 1, but try it anyway and I'll fix that later.

**Comment by nicm** [comment]
Here is a better version please try this instead: [tmux-next-bracket2.diff.txt](https://github.com/tmux/tmux/files/3123040/tmux-next-bracket2.diff.txt)

**Comment by chrisbarber** [comment]
Nice! Here's a quick hack job to make it behave more like in vi (cumulative patch including your previous one):

[vi.diff.txt](https://github.com/tmux/tmux/files/3123398/vi.diff.txt)

I copied the wrap-detection code from elsewhere so there may be a more sensible way of doing it inline.

Here's some text which I `cat`ed inside tmux in order to test:

[matching-bracket-test.txt](https://github.com/tmux/tmux/files/3123401/matching-bracket-test.txt)

I haven't consulted vi or vim source for this, so there may be edge cases yet to consider. I can't think of any though, besides issues like line-wrapping and begin/end of file, which seem to be handled here. Vi's `%` seems to have awareness of braces that are inside strings, and emacs docs [also mentions](https://www.gnu.org/savannah-checkouts/gnu/emacs/manual/html_node/emacs/Moving-by-Parens.html) being aware of strings and comments, but none of that makes sense for generic scrollback buffer output.

I actually fired up emacs, though I'm not familiar at all, and it looks like one difference between this implementation and emacs is that emacs actually puts the cursor immediately after the matching brace, rather than right on it. (I didn't attempt to address that in my above patch)

**Comment by nicm** [comment]
emacs does the same (after word rather than on it) for next-word, that's
why we have next-word vs next-word-end.

I'll take a look at your additions later, yhanks.

**Comment by nicm** [comment]
Here is a tidied version of your changes, please check it still works: [a.diff.txt](https://github.com/tmux/tmux/files/3124069/a.diff.txt)

**Comment by chrisbarber** [comment]
The `goto retry;` needs to be moved back outside the if-statement, otherwise I get `[lost server]` for the wrapped case.

[vi2.diff.txt](https://github.com/tmux/tmux/files/3124231/vi2.diff.txt)

**Comment by nicm** [comment]
Try this please which adds previous as well: [tmux-next-bracket3.diff.txt](https://github.com/tmux/tmux/files/3124324/tmux-next-bracket3.diff.txt)

**Comment by chrisbarber** [comment]
Dangit, I missed a detail-- when a `next-matching-bracket` triggers a `previous-matching-bracket`, but fails, the cursor should stay where it was originally. Again, pardon my hacked-together demonstration:

[vi3.diff.txt](https://github.com/tmux/tmux/files/3124385/vi3.diff.txt)

After this change though it works perfectly as far as I can tell (I am only testing vi mode, not emacs)

**Comment by nicm** [comment]
Are you missing some brackets? What's the point in setting cp to NULL if you just replace it a couple of lines later? Or is the if (gc.data.size != 1 || (gc.flags & GRID_FLAG_PADDING)) bit redundant?

Could you also please add a comment to each of the vi bits in this function explaining what they are doing differently?

**Comment by nicm** [comment]
I think you do need it, take a look at this instead please: [abc123.diff.txt](https://github.com/tmux/tmux/files/3125485/abc123.diff.txt)

**Comment by chrisbarber** [comment]
Apologies, I misread the indentation of the if-statement with the (gc.data.size != 1 || (gc.flags & GRID_FLAG_PADDING)) condition. I was just trying to copy a segment of code which would fetch the character at the current cursor position and grabbed too much.

I think it should be like this: [vi4.diff.txt](https://github.com/tmux/tmux/files/3125501/vi4.diff.txt)
(added comments, removed redundant stuff)

Hopefully that is clearer. I tested and it still works for the case this is meant to cover (lookahead to closing bracket and failed followup search for previous match; cursor stays put).

**Comment by nicm** [comment]
Thanks, this is not quite what I meant. I don't need comments saying what the code does, I need just a couple of small comments saying WHY it does it - that is, in what way is vi different. For example just something saying "In vi move to the previous bracket if on a closing bracket. If this fails, return to the original cursor position.". And similar for the other MODEKEY_VI bits.

**Comment by chrisbarber** [comment]
Okay hopefully should be better: [vi5.diff.txt](https://github.com/tmux/tmux/files/3125518/vi5.diff.txt)

There are still the higher-level comments that say "behave like previous/next-word," without qualifying it as emacs-specific. But hopefully it is clear enough that vi is being called out as the special case in the 2 places that I noted, and so that part no longer applies.

**Comment by nicm** [comment]
I have applied this to OpenBSD now, it will be in GitHub in a few hours when it syncs. Thanks!
