### ISSUE TITLE
Set $TERM inside tmux dynamically according to parent $TERM

### ISSUE THREAD

**Issue by doronbehar** [tmux/tmux#1668]
I have a question as for `tmux`'s `$TERM` and `default-terminal`:

Tmux can be launched inside various environments, such as the bare ttys, or a terminal emulator like xterm and rxvt. Some programs, rely _only_ on `$TERM` in order to know if colors are available in this terminal or not, (Vim is a good example - last time I checked).

I launch tmux inside a terminal emulator and sometimes in a tty. Inside a tty, my `$TERM` is `linux-16color` and in the terminal emulators it ends with `-256color`. My question is: Is there a smart way make tmux set the `default-terminal` according to the parent `$TERM`? Ideally, it would have been best if the suffix of `$TERM` inside tmux will be set according to the suffix of the parent `$TERM` (for example: parent's `$TMUX` `linux-16color` -> tmux's `$TERM` `screen-16color`), by default.

I know I can but I'd prefer avoiding creating a shell wrapper that will have to write a temporary configuration file that will be `source`d in `~/.tmux.conf`.

- Tmux version: 2.8
- Platform: Linux
- `uname -sp`: `Linux unknown` (Arch Linux).

**Comment by nicm** [comment]
If you want to do this then you will need to write a script and run it from . tmux.conf or your shell profiles.

I'd personally just set TERM to tmux-256color or screen-256color and let tmux just figure out what to do if the terminal outside has fewer colours. Swapping TERM around every time you attach will have no effect on existing programs anyway, so you will always end up with some programs that have the wrong TERM.

**Comment by nicm** [comment]
You probably won't need a wrapper and can just do it with if-shell/run-shell.

**Comment by doronbehar** [comment]
Thanks, I used this at the end:
```
if-shell '[[ $TERM =~ "-16color" ]]' 'set -g default-terminal screen-16color'
if-shell '[[ $TERM =~ "-256color" ]]' 'set -g default-terminal tmux-256color'
```

When I've posted the issue I've reached the conclusion somehow that the `$TERM` variable read at the moment the shell code is evaluated is the same as inside tmux and not outside of it.

Cheers :beers:.

**Comment by unihon** [comment]
> Thanks, I used this at the end:
> 
> ```
> if-shell '[[ $TERM =~ "-16color" ]]' 'set -g default-terminal screen-16color'
> if-shell '[[ $TERM =~ "-256color" ]]' 'set -g default-terminal tmux-256color'
> ```
> 
> When I've posted the issue I've reached the conclusion somehow that the `$TERM` variable read at the moment the shell code is evaluated is the same as inside tmux and not outside of it.
> 
> Cheers 🍻.

You can achieve the same effect with `set -g default-terminal "$TMUX"` .
`"$TMUX"` is tmux global environment variable that copy form source "environment variable".
