### ISSUE TITLE
The select-word command is missing from the manual

### ISSUE THREAD

**Issue by pawel-slowik** [tmux/tmux#1669]
The `select-word` copy mode command is missing from the manual, `tmux.1` .

Tmux version: 2.8 and current master.

Fix:
```
diff --git i/tmux.1 w/tmux.1
index 0596da0c..627df180 100644
--- i/tmux.1
+++ w/tmux.1
@@ -1230,6 +1230,7 @@ The following commands are supported in copy mode:
 .It Li "search-forward-incremental <for>" Ta "" Ta "C-s"
 .It Li "search-reverse" Ta "N" Ta "N"
 .It Li "select-line" Ta "V" Ta ""
+.It Li "select-word" Ta "" Ta ""
 .It Li "start-of-line" Ta "0" Ta "C-a"
 .It Li "stop-selection" Ta "" Ta ""
 .It Li "top-line" Ta "H" Ta "M-R"
```

This is the only missing command, I checked the `window_copy_cmd_table` array.
`select-word` was introduced in 85d7afaefc1e2cf8008575a776ec70f51d24e1a6 .

**Comment by nicm** [comment]
Great - applied to OpenBSD now, will be in GitHub later. Thanks!
