### ISSUE TITLE
Pane zooming in and out produces unwanted window scrolling

### ISSUE THREAD

**Issue by oblitum** [tmux/tmux#167]
This issue relates to https://github.com/tmux-plugins/tmux-resurrect/issues/112. This was one description given there:

> It seems there's an issue with un-zooming and then zooming back, even if I do this myself, I don't get back exactly to my previous state, for example:
>
> 1. Get a window split into two panes horizontally.
> 2. Get to the top pane.
> 3. Zoom it.
> 4. Fill it with Enter, so that cursor goes to the bottom.
> 5. `clear`, so that cursor goes to the top.
> 6. Zoom out.
> 7. Zoom in.
> 
> In 5, cursor was at the top, in 7 it's not (at last for me), so the state is not being recovered without notice. With resurrect's save or continuum this turns into a sudden cursor jump.
>

**Comment by nicm** [comment]
Zooming is a pane resize, there is no guarantee the cursor will end up
in the same place, it rolls lines out of the history the same as if you
resize the window and then resize it back.

**Comment by oblitum** [comment]
I was suspecting it was unfeasible, but it's sad anyways because zooming/unzooming sequentially keeps pushing the cursor further down, which is weird.
