### ISSUE TITLE
Request: override built-in commands with command-alias

### ISSUE THREAD

**Issue by cevhyruz** [tmux/tmux#1673]
It would be nice to be able to override built-in commands with command-alias and (I think this should be how an alias behave). 

Or if it's not possible is there a way to temporarily turn off completion of ambiguous command on runtime?
if I have an alias like this:
`set command-alias[100] sp="display 'this is test'"`
it won't work at all as it will complete to `split-window`

**Comment by nicm** [comment]
Please test the patch in issue https://github.com/tmux/tmux/issues/1630.
