### ISSUE TITLE
[Question] How to change scroll speed?

### ISSUE THREAD

**Issue by karambaq** [tmux/tmux#1678]
MacOS Mojave 10.14.3
Tmux version: 2.8
I'm trying to change the scroll speed to 1 line per scroll, my config now looks like this:
Tried in iTerm2, Alacritty and Terminal.app
```
set -g mouse on
bind -Tcopy-mode WheelUpPane send -N1 -X scroll-up
bind -Tcopy-mode WheelDownPane send -N1 -X scroll-down
```

But scrolling is still 5 lines per scroll on, any other ways to set it to 1?

**Comment by nicm** [comment]
What does "tmux lsk|grep Wheel" show? Are you sure you restarted tmux entirely?

**Comment by karambaq** [comment]
Solved with 
```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @scroll-speed-num-lines-per-scroll 1

run -b '~/.tmux/plugins/tpm/tpm'
```
