### ISSUE TITLE
"Jittering" on leaving copy mode with scrollwheel

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#168]
![bug](https://cloud.githubusercontent.com/assets/7074/10717316/d9130d6c-7b4b-11e5-8164-94d9467807c9.gif)

I've upgraded to 2.1 and have tried to recreate the pre-2.1 mouse behavior. Part of this is that the scroll-wheel should work in copy mode _and_ if you scroll to the end of the copy buffer it should leave copy mode. Here's the config I _used_ to use:

```
set -g mouse-select-pane on
set -g mouse-select-window on
set -g mouse-resize-pane on
set -w -g mode-mouse on
```

And here's what I am using now, which attempts to get the old behavior back where the scrollwheel worked in Vim or in copy mode:

```
set -g mouse on

# Restore pre-2.1 behavior of scrolling with the scrollwheel in Vim or in copy
# mode, otherwise entering copy mode if not already in it.
bind-key -T root WheelDownPane \
  if-shell -Ft= '#{mouse_any_flag}' \
    'send-keys -Mt=' \
    'if-shell -Ft= "#{pane_in_mode}" "send-keys -Mt=" "copy-mode -et="'
bind-key -T root WheelUpPane \
  if-shell -Ft= '#{mouse_any_flag}' \
    'send-keys -Mt=' \
    'if-shell -Ft= "#{pane_in_mode}" "send-keys -Mt=" "copy-mode -et="'
```

If you look in the attached gif you'll see me scrolling to the bottom of the buffer with the scroll wheel, and on hitting the bottom you can see tmux flickering in and out of copy mode even after I stop.

My theory for what is happening is this: I'm using OS X and a track pad, so the "wheel" here is continuing to fire some events even after I stop moving because of the OS's "inertia" effect. That final nested `if-shell` command is being called repeatedly, once per event, and because of the `-e` switch passed to `copy-mode`, we're leaving it on one tick and then going straight back in on the next.

I don't think this is a tmux bug, but thought I should raise it here because:

- It should be possible to exactly replicate the pre-2.1 behavior using 2.1 config options.
- We might want to document the necessary settings to make this be the case.

Maybe, we might even want to expand the defaults to encompass this behavior so that no documentation is necessary. For reference, at the moment, the defaults consist of:

```
bind-key    -T root   MouseDown1Pane   select-pane -t = ; send-keys -M
bind-key    -T root   MouseDown1Status select-window -t =
bind-key    -T root   MouseDown3Pane   select-pane -m -t =
bind-key    -T root   MouseDrag1Pane   if-shell -F -t = #{mouse_any_flag} "if -Ft= "#{pane_in_mode}" "copy-mode -M" "send-keys -M"" "copy-mode -M"
bind-key    -T root   MouseDrag1Border resize-pane -M
```

**Comment by cHoco** [comment]
In your WheelDownPane binding you don't want to enter copy-mode if you want to emulate the pre-2.1 behaviour. That causes the flickering since you're eating copy-mode and at the same time exiting it (since you pass the -e option)

**Comment by wincent** [comment]
Wow, slick mapping; I don't think I could have figured that one out (I'm still fuzzy on exactly what circumstances `mouse_any_flag` is true). Thanks #cHoco; that resolves the issue.

I'll leave this ticket open for @nicm to decide whether documentation or augmentation of the default bindings is warranted.
