### ISSUE TITLE
Undocumented feature? Can set session option with a window option

### ISSUE THREAD

**Issue by sdondley** [tmux/tmux#1680]
On tmux, version 2.8 on a mac.

The "mouse" option is a session option. However,  running the `setw mouse off` turns off mouse option for all windows in my session. This doesn't appear to be documented so I'm unclear on why it works or why it turns off mouse operation for all windows and not just one.

**Comment by nicm** [comment]
tmux knows it is a session option so it doesn't care if you use set or setw.

**Comment by sdondley** [comment]
OK, so shouldn't this be documented? I couldn't find anything in the manual why this confusing operation magically works when "mouse" is not listed under "supported window options."

**Comment by nicm** [comment]
Possibly, but why does it matter? If you follow the man page and use set-option it works, if you don't and use set-window-option then it also works.

**Comment by sdondley** [comment]
I think accurate documentation matters. If it doesn't matter whatsoever if you use `set-window-option` or `set-option`, why even bother having the distinction in the manual if it "just works?"
From what I can tell, you can set a window option with plain old `set,` too.

**Comment by sdondley** [comment]
I think what's going on is that the manual is trying to maintain backward compatibility with ancient versions of tmux. I see an entry in the CHANGE log:

`* Avoid duplicating code by adding a -w flag to set-option, and show-options to
  set, and show window options. The commands set-window-option, and
  show-window-options are now aliases.`

**Comment by nicm** [comment]
set-window-option and show-window-option have been around for a long time and removing them probably isn't worth the hassle. They might be go at some point, but probably only if options handling changes substantially.

I don't particularly encourage people to rely on this behaviour, it's just a convenience if you forget whether an option is a server, session or window option. It can't work for user options and it doesn't work for show-option.

**Comment by sdondley** [comment]
OK, well, I'd suggest that behavior should at least be documented if even as a footnote somewhere maybe with some kind of warning to the effect of "you should not rely on this behavior when setting window variables as it is not officially supported." I'm living proof that it can be a source of confusion for users.

But I'll leave it up to you guys to decide that. I'm not qualified.

**Comment by nicm** [comment]
I made this work for show-options also and added a note to the manual.
