### ISSUE TITLE
colors in status broken  (2.8_1) (macOs using brew install tmux)

### ISSUE THREAD

**Issue by nbari** [tmux/tmux#1681]
After installing `tmux 2.8` on a macOS system, I notice that the ANSI escape codes were printed in the status bar. I updated a working system `brew update && brew upgrade` and notice same behavior, this is how it looks now:

<img width="737" alt="Screenshot 2019-04-16 at 16 05 42" src="https://user-images.githubusercontent.com/364199/56216420-b23dce80-6061-11e9-8900-2b7d1062a2ff.png">

```
$ brew info tmux
tmux: stable 2.8 (bottled), HEAD
Terminal multiplexer
https://tmux.github.io/
/usr/local/Cellar/tmux/2.8_1 (10 files, 705.4KB) *
  Poured from bottle on 2019-04-16 at 16:03:29
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tmux.rb
==> Dependencies
Build: pkg-config ✔
Required: libevent ✔, ncurses ✔
==> Options
--HEAD
        Install HEAD version
==> Caveats
Example configuration has been installed to:
  /usr/local/opt/tmux/share/tmux

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
```

later I tried in both systems with `brew install tmux --HEAD`:

```
$ brew install tmux --HEAD
==> Cloning https://github.com/tmux/tmux.git
Updating /Users/nbari/Library/Caches/Homebrew/tmux--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at e6ee3e9 Warning fixes from Carlo Marcelo Arenas Belón.
==> sh autogen.sh
==> ./configure --disable-Dependency-tracking --prefix=/usr/local/Cellar/tmux/HEAD-e6ee3e9_1 --sysconfdir=/usr/local/etc
==> make install
==> Downloading https://raw.githubusercontent.com/imomaliev/tmux-bash-completion/homebrew_1.0.0/completions/tmux
Already downloaded: /Users/nbari/Library/Caches/Homebrew/downloads/e069f5feda8ac439eb1c96ee32db3eacfb99b6d0a93568076ff762daa1270dc1--tmux
==> Caveats
Example configuration has been installed to:
  /usr/local/opt/tmux/share/tmux

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/tmux/HEAD-e6ee3e9_1: 10 files, 751.4KB, built in 36 seconds
```

<img width="1197" alt="Screenshot 2019-04-16 at 15 57 15" src="https://user-images.githubusercontent.com/364199/56216345-8de1f200-6061-11e9-9fc6-76146982941c.png">

`tmux` started to consume too many CPU resources and gets block like in the above picture, just printing that some `windows-status-*` options are invalid, just in case this are the lines I have been using:

https://github.com/nbari/dotfiles/blob/master/my-dotfiles/.tmux.conf#L29-L32

```
setw -g window-status-current-bg '#006994'
setw -g window-status-current-fg '#FFFFFF'
setw -g window-status-bg '#000000'
setw -g window-status-fg '#d3d3d3'
```

**Comment by nicm** [comment]
Show tmux logs please.

**Comment by nbari** [comment]
Hi @nicm,  how and where to get the logs, also is there any special option to add that could be more useful?

**Comment by nicm** [comment]
Please do this, then make sure there are the escape sequences in the status line, then exit tmux and add the tmux-server-*.log file from the current directory to this issue:
~~~~
tmux kill-server
tmux -vv new
~~~~

**Comment by nbari** [comment]
Hi, here are the logs:

[tmux-server-16875.log.gz](https://github.com/tmux/tmux/files/3085641/tmux-server-16875.log.gz)

**Comment by nicm** [comment]
These escape sequences are present in the output from your command:
~~~~
1555428157.507765 format_job_update: 0x7facc3905980 uptime | grep -o '..user.*': \033[01;31m\033[K2 users, load averages: 1.02 1.35 1.48\033[m\033[K
~~~~
Perhaps you should try "grep --color=never"?

**Comment by nbari** [comment]
The culprit was this line:

    export GREP_OPTIONS='--color=always'

Many thanks for your time on this 👍
