### ISSUE TITLE
Baud rate on pty

### ISSUE THREAD

**Issue by mpasternacki** [tmux/tmux#1682]
I run tmux 2.8 on FreeBSD-CURRENT (r346149 at the moment) amd64.

The problem I am experiencing is that I cannot paste or enter lines longer than 1920 characters in tmux on FreeBSD.

I managed to track down the behaviour to tty implementation: while `termios(4)` specifies that in canonical mode line cannot be longer than `MAX_CANON` and input queue is `MAX_INPUT` (both of which are defined to 255), it is a minimum and actual queue/line buffer is allocated to 1/5 baud rate, i.e. ~2s of input, which would make sense on an actual serial line.

`stty speed` in FreeBSD urxvt/tmux and over ssh session reports 38400; `stty speed` in tmux reports 9600. 9600/5 is 1920, which is consistent with the line limit. After I run `stty speed 38400`, I can input long lines.

With increased baud rate, the limit is still there, but 7.5 kilobytes is enough for me (side note: Linux actually also truncates input, at 4096 bytes by default. I didn't check if the length is hardcoded or depends on another parameter. This wasn't a problem in my work).

FreeBSD's default baud rate for a new tty (`TTYDEF_SPEED`) is 9600. I ran an experiment and pty returned from `forkpty()` is initialized at 9600Bd. On Linux, a new pty is initialized at 38400Bd.

I have a functioning workaround in my `.zshrc`, so it's not directly affecting my work anymore, but it could be considered an issue with tmux, at least from end user's perspective. URxvt and XTerm set the baud rate to 38400; GNU Screen copies client terminal's baud rate to window's pty, so window also gets 38400; not sure whether OpenSSH copies parent terminal's settings or injects its own, but the end result is the same.

Should tmux be setting a baud rate on window's PTY? If yes – what should be the intended behaviour? I can see some options:

 - Leave it as it is; user can set it in their shell profile or use hooks
 - After `forkpty()`, just set speed to 38400Bd (or to a hard–coded value configurable in compile time) to avoid this particular problem
 - Make it configurable in runtime, probably per window
 - Copy speeds (and possibly other settings) from parent terminal

While the last option seems safest, it is also complex in implementation: window's/pane's pty would need to be updated on reattachment, and if it's attached to multiple clients, there should be some logic to decide on speed (it's probably already implemented by GNU Screen, but I'm not sure I can read that source code without losing too many sanity points).

On the other hand, baud rate on a pty seems to be effectively meaningless number besides edge cases like this. It might be safe to just set 38400Bd (maybe make sure the default speed isn't higher) as the highest universally recognized speed.

I'd be happy to provide a pull request (maybe except the "update settings on reattachment" logic which seems complicated), but I don't know what is the desired behaviour here and if I'm missing some corner cases with other systems.

**Comment by nicm** [comment]
Why can't you just change it with stty if you don't like the default?

**Comment by mpasternacki** [comment]
That's exactly my question: would setting a saner baud rate on pty would even be in scope of tmux?

Con: as you wrote, I can set it with stty (and already updated my `.zshrc` to do that)
Pro: other tools (urxvt, tmux, openssh, screen) seem to be doing that, so it might be expected by user

**Comment by nicm** [comment]
Where does ssh set it?

I suspect this is something you should take up with the FreeBSD developers. Linux ptys appear to default to 38400 and OpenBSD defaults to 115200 (it sets it explicitly in tty_pty.c rather than using the default from ttydefaults.h).  I don't see any compelling reason for tmux to change the system default.

**Comment by mpasternacki** [comment]
I didn't inspect OpenSSH source, but: (a) FreeBSD creates pty initialized to 9600Bd; (b) when I ssh to a FreeBSD machine and run `stty`, it reports 38400Bd. _Something_ had to set it. Quick experiment shows it uses speed of client's controlling terminal if it is a known value, and falls back to 9600 if client's terminal is set to a non-standard value like 54321.

If you believe it's out of scope, feel free to close this issue as WONTFIX. I already have a good workaround – just wanted to ask if it's a bug in tmux, because other programs behave differently.

It would be nice if this issue was closed rather than removed, so if somebody else runs into this, they can find an explanation (I couldn't find any report of that beviour in Google, and after I decided to investigate, it was a full day of debugging that ended up in kernel source). I will be raising this with FreeBSD developers as well, along with some issues in documentation I found along my way.

Thank you for your comments! And for your work on tmux, obviously – I use it a lot nowadays, switched from Screen last year and never loooked back!

**Comment by nicm** [comment]
Are you sshing from Linux? OpenSSH will copy the rate from the tty where you ssh from, it doesn't make one up itself.

Anyway, I think this needs to be fixed in FreeBSD.

**Comment by mpasternacki** [comment]
I ssh from FreeBSD (don't have access to machine running Linux natively), but with ssh pseudoterminal is managed server-side anyway. Tried a couple different settings on client's terminal to see how pty on server side is configured.

Closing the issue then. Thanks!

**Comment by nicm** [comment]
I don't see any code in ssh to set the speed for the pty other than by copying it, if you can find it then I'll consider doing the same in tmux. But you should report this to FreeBSD anyway, 9600b is way too low for ptys.
