### ISSUE TITLE
`send -X copy-selection` unexpedtedly also clears it on-screen

### ISSUE THREAD

**Issue by avih** [tmux/tmux#1683]
Using a recent tmux master (a week or so) and this config:
```
set-option -g mode-keys vi
set-option -g mouse on

bind -Tcopy-mode-vi MouseDragEnd1Pane send -t= -X stop-selection \; send -t= -X copy-selection
```

Seeing that the original binding (in `key-bindings.c`) is:
```
bind -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel
```

I wanted to copy it but stay in copy-mode such that the selection is finished but kept visible on screen, and so I changed the command to `stop-selection` + `copy-selection`.

However, while copying and staying in copy-mode, it seems to clear the selection on screen.

If I use this instead:
```
bind -Tcopy-mode-vi MouseDragEnd1Pane send -t= -X stop-selection
```
Then it stays in copy-mode and visible, but the selection isn't copied.

As a work around, it appears that any `copy-pipe` also copies the selection, so this seems to achieve the goal of copying, and staying in copy-mode with the selection visible:
```
# Use dummy copy-pipe to copy and keep the selection visible
bind -Tcopy-mode-vi MouseDragEnd1Pane send -t= -X stop-selection \; send -t= -X copy-pipe ":"
```

However, I think this is undocumented (copy-pipe should be sending the selection to a pipe, not necessarily also copying it internally), and there's also there's the `send -X clear-selection`  command which seems to be clearing the selection on-screen while keeping the paste-buffer with its content unmodified.

Button line, it seems like `copy-selection` also does `clear-selection`, but I think it shouldn't.

**Comment by avih** [comment]
This was not extensively tested, but it seems to fix the issue:
```diff
diff --git a/window-copy.c b/window-copy.c
index aacea5c5..ca063afd 100644
--- a/window-copy.c
+++ b/window-copy.c
@@ -748,7 +748,6 @@ window_copy_cmd_copy_selection(struct window_copy_cmd_state *cs)

        if (s != NULL)
                window_copy_copy_selection(wme, prefix);
-       window_copy_clear_selection(wme);

        free(prefix);
        return (WINDOW_COPY_CMD_REDRAW);
```

**Comment by avih** [comment]
It also seems that `copy-selection` (without `-and-cancel`) is not used in any default binding, so while it does change the command's behavior, it doesn't affect the default behavior.

**Comment by nicm** [comment]
This is how copy-selection has always worked, the -and-cancel only
affects whether it leaves copy mode, it always clears the selection.

**Comment by avih** [comment]
Yes, I understand that `-and-cancel` leaves copy mode.

The fact that it's always worked like that doesn't necessarily make it the preferred behavior, though changing it does indeed add considerations of backward compatibility.

The point is, all (x) terminals leave the selection visible on screen after copying. Personally I find it useful, because selection is also occasionally used to "highlight" things even if you don't intend to copy them.

If one wanted similar behavior with tmux, even if this means staying in copy mode, then as far as I can tell it's currently impossible (at least not without using a dummy copy-pipe to emulate it, assuming it does emulate it in all cases).

Is it possible?

If it's possible only using a dummy copy-pipe, would you consider documenting that `copy-pipe ":"` does `copy-selection` without clearing it?

**Comment by nicm** [comment]
But lots of people use this, that's why it was added, not to mention that
emacs clears the selection. We're not changing it. copy-pipe should
probably clear too.

You'll need to add a new command.

**Comment by avih** [comment]
Any suggestion for a new command name? maybe `copy-selection-and-keep`? or `copy-selection-no-clear`? or anything else you prefer?

**Comment by nicm** [comment]
no clear is good I think

**Comment by avih** [comment]
Also, copy-pipe really shouldn't clear the selection IMHO. Because the `clear-selection` command does exist, and can be used after copy-pipe if one wants to clear it. But if copy-pipe would clear the selection then again there would be no way to do copy-pipe without clearing the selection.

**Comment by nicm** [comment]
Yes if we did it from the start then probably none of them should clear and
the keys should just be copy-selection;clear-selection but it is not worth
changing it and making everyone change their configs for this. So ideally
they should all be consistent and clear the selection.

Why don't we just leave it as it is for now since nobody has complained
about  copy-pipe not clearing? Then you can use copy-pipe?

**Comment by avih** [comment]
For consistency though, I could add `copy-pipe-no-clear` too and make `copy-pipe` clear the selection. Would you be OK with that?

**Comment by nicm** [comment]
Yes if you like that would be fine, don't forget to add them to tmux.1.

**Comment by avih** [comment]
I'll send a PR with those updates including tmux.1 . Thanks.
