### ISSUE TITLE
Tab character in “status-right” causes tmux to hang

### ISSUE THREAD

**Issue by bdesham** [tmux/tmux#1687]
When the tmux conf specifies either a literal tab or `\t` in `status-right`, tmux hangs when trying to create a new session. The entire screen goes blank; my typing is repeated back to me. Pressing Ctrl-C or Ctrl-Q have no effect. The tmux process has to be killed using `kill -9`.

Through `git bisect`, I’ve identified 979313832 as the first commit that shows the problem. The problem exists in the latest master revision (c86936613) and in revision 962f255e but not in revision 1d6fe43c. (Since I’m on Linux, I couldn’t test revision 979313832 directly, but the code in the previous merge commit works right and the code in the next merge commit shows the problem, so I assume that that’s the revision where the issue was introduced.)

I realize that putting a tab into `status-right` is an odd thing to do :-) I found the issue when I was trying to break a long line like

```
set-option -g status-right " #(a_really_long_command |\
	another_really_long_command) "
```

using a literal tab to indent the second line.

## My setup

OS: Linux, x86_64, Ubuntu 16.04.5 (also verified on CentOS 7.4.1708)

$TERM: screen

## Minimal configuration file

```
set-option -g status-right "\t"
# Replacing the \t with a literal tab gives the same effect.
```

## Log file

[tmux-server-13541.log](https://github.com/tmux/tmux/files/3113447/tmux-server-13541.log)

**Comment by nicm** [comment]
This should be fixed in OpenBSD now, will be fixed in GitHub in a few hours when it syncs. Thanks!

**Comment by bdesham** [comment]
It works great now. Thanks a ton!
