### ISSUE TITLE
Base index commands not doing anything

### ISSUE THREAD

**Issue by manasthakur** [tmux/tmux#169]
I am using tmux 2.1 installed using Homebrew on Mac OS X El Capitan (using in iTerm2). The commands to set the base index of windows to 1 are not working. I have tried the following:

```
set-option -g base-index 1
setw -g pane-base-index 1
setw -g base-index 1
```

There is no error while opening tmux, but the index starts at 0 only.

NOTE: There is something else that is weird as well. The session index continuously keeps on increasing, even if I quit and restart tmux. On my linux systems, though, it starts from 0. Can someone give a solution for this as well?

**Comment by ThomasAdam** [comment]
It works fine.  The fact that you claim the session_id keeps increasing means you're not killing the server first:

`pkill tmux ; tmux`

**Comment by manasthakur** [comment]
Killing tmux worked. It hanged my iTerm though!
This also solved my first problem; I think my changes in tmux.conf were not getting reflected because the instance was not getting killed. I assume the reason for this was that iTerm itself uses tmux.
