### ISSUE TITLE
bright colors not correct

### ISSUE THREAD

**Issue by mckellyln** [tmux/tmux#1690]
Hi,

it would seem with commit 6aa0bedad281cef0e9411f3530052d09bbc583f1 the colors with 'bright' in them no longer work correctly (ie such as brightyellow) - at least for my config.
I am on Ubuntu 4.15.0-48-generic
Using terminator terminal with TERM set to xterm outside tmux and screen-256color inside tmux.

% tmux info
Terminal 0: xterm [references=1, flags=0x0]:
   0: acsc: (string) ``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~
   1: AX: (flag) true
   2: bce: (flag) true
   3: bel: (string) \007
   4: blink: (string) \033[5m
   5: bold: (string) \033[1m
   6: civis: (string) \033[?25l
   7: clear: (string) \033[H\033[2J
   8: cnorm: (string) \033[?12l\033[?25h
   9: colors: (number) 8
  10: Cr: (string) \033]112\007
  11: Cs: (string) \033]12;%p1%s\007
  12: csr: (string) \033[%i%p1%d;%p2%dr
  13: cub: (string) \033[%p1%dD
  14: cub1: (string) \010
  15: cud: (string) \033[%p1%dB
  16: cud1: (string) \012
  17: cuf: (string) \033[%p1%dC
  18: cuf1: (string) \033[C
  19: cup: (string) \033[%i%p1%d;%p2%dH
  20: cuu: (string) \033[%p1%dA
  21: cuu1: (string) \033[A
  22: cvvis: (string) \033[?12;25h
  23: dch: (string) \033[%p1%dP
  24: dch1: (string) \033[P
  25: dim: (string) \033[2m
  26: dl: (string) \033[%p1%dM
  27: dl1: (string) \033[M
  28: E3: (string) \033[3;J
  29: ech: (string) \033[%p1%dX
  30: ed: (string) \033[J
  31: el: (string) \033[K
  32: el1: (string) \033[1K
  33: enacs: [missing]
  34: fsl: (string) \007
  35: home: (string) \033[H
  36: hpa: (string) \033[%i%p1%dG
  37: ich: (string) \033[%p1%d@
  38: ich1: [missing]
  39: il: (string) \033[%p1%dL
  40: il1: (string) \033[L
  41: indn: (string) \033[%p1%dS
  42: invis: (string) \033[8m
  43: kcbt: (string) \033[Z
  44: kcub1: (string) \033OD
  45: kcud1: (string) \033OB
  46: kcuf1: (string) \033OC
  47: kcuu1: (string) \033OA
  48: kDC: (string) \033[3;2~
  49: kDC3: (string) \033[3;3~
  50: kDC4: (string) \033[3;4~
  51: kDC5: (string) \033[3;5~
  52: kDC6: (string) \033[3;6~
  53: kDC7: (string) \033[3;7~
  54: kdch1: (string) \033[3~
  55: kDN: (string) \033[1;2B
  56: kDN3: (string) \033[1;3B
  57: kDN4: (string) \033[1;4B
  58: kDN5: (string) \033[1;5B
  59: kDN6: (string) \033[1;6B
  60: kDN7: (string) \033[1;7B
  61: kend: (string) \033OF
  62: kEND: (string) \033[1;2F
  63: kEND3: (string) \033[1;3F
  64: kEND4: (string) \033[1;4F
  65: kEND5: (string) \033[1;5F
  66: kEND6: (string) \033[1;6F
  67: kEND7: (string) \033[1;7F
  68: kf1: (string) \033OP
  69: kf10: (string) \033[21~
  70: kf11: (string) \033[23~
  71: kf12: (string) \033[24~
  72: kf13: (string) \033[1;2P
  73: kf14: (string) \033[1;2Q
  74: kf15: (string) \033[1;2R
  75: kf16: (string) \033[1;2S
  76: kf17: (string) \033[15;2~
  77: kf18: (string) \033[17;2~
  78: kf19: (string) \033[18;2~
  79: kf2: (string) \033OQ
  80: kf20: (string) \033[19;2~
  81: kf21: (string) \033[20;2~
  82: kf22: (string) \033[21;2~
  83: kf23: (string) \033[23;2~
  84: kf24: (string) \033[24;2~
  85: kf25: (string) \033[1;5P
  86: kf26: (string) \033[1;5Q
  87: kf27: (string) \033[1;5R
  88: kf28: (string) \033[1;5S
  89: kf29: (string) \033[15;5~
  90: kf3: (string) \033OR
  91: kf30: (string) \033[17;5~
  92: kf31: (string) \033[18;5~
  93: kf32: (string) \033[19;5~
  94: kf33: (string) \033[20;5~
  95: kf34: (string) \033[21;5~
  96: kf35: (string) \033[23;5~
  97: kf36: (string) \033[24;5~
  98: kf37: (string) \033[1;6P
  99: kf38: (string) \033[1;6Q
 100: kf39: (string) \033[1;6R
 101: kf4: (string) \033OS
 102: kf40: (string) \033[1;6S
 103: kf41: (string) \033[15;6~
 104: kf42: (string) \033[17;6~
 105: kf43: (string) \033[18;6~
 106: kf44: (string) \033[19;6~
 107: kf45: (string) \033[20;6~
 108: kf46: (string) \033[21;6~
 109: kf47: (string) \033[23;6~
 110: kf48: (string) \033[24;6~
 111: kf49: (string) \033[1;3P
 112: kf5: (string) \033[15~
 113: kf50: (string) \033[1;3Q
 114: kf51: (string) \033[1;3R
 115: kf52: (string) \033[1;3S
 116: kf53: (string) \033[15;3~
 117: kf54: (string) \033[17;3~
 118: kf55: (string) \033[18;3~
 119: kf56: (string) \033[19;3~
 120: kf57: (string) \033[20;3~
 121: kf58: (string) \033[21;3~
 122: kf59: (string) \033[23;3~
 123: kf6: (string) \033[17~
 124: kf60: (string) \033[24;3~
 125: kf61: (string) \033[1;4P
 126: kf62: (string) \033[1;4Q
 127: kf63: (string) \033[1;4R
 128: kf7: (string) \033[18~
 129: kf8: (string) \033[19~
 130: kf9: (string) \033[20~
 131: kHOM: (string) \033[1;2H
 132: kHOM3: (string) \033[1;3H
 133: kHOM4: (string) \033[1;4H
 134: kHOM5: (string) \033[1;5H
 135: kHOM6: (string) \033[1;6H
 136: kHOM7: (string) \033[1;7H
 137: khome: (string) \033OH
 138: kIC: (string) \033[2;2~
 139: kIC3: (string) \033[2;3~
 140: kIC4: (string) \033[2;4~
 141: kIC5: (string) \033[2;5~
 142: kIC6: (string) \033[2;6~
 143: kIC7: (string) \033[2;7~
 144: kich1: (string) \033[2~
 145: kind: (string) \033[1;2B
 146: kLFT: (string) \033[1;2D
 147: kLFT3: (string) \033[1;3D
 148: kLFT4: (string) \033[1;4D
 149: kLFT5: (string) \033[1;5D
 150: kLFT6: (string) \033[1;6D
 151: kLFT7: (string) \033[1;7D
 152: kmous: (string) \033[M
 153: knp: (string) \033[6~
 154: kNXT: (string) \033[6;2~
 155: kNXT3: (string) \033[6;3~
 156: kNXT4: (string) \033[6;4~
 157: kNXT5: (string) \033[6;5~
 158: kNXT6: (string) \033[6;6~
 159: kNXT7: (string) \033[6;7~
 160: kpp: (string) \033[5~
 161: kPRV: (string) \033[5;2~
 162: kPRV3: (string) \033[5;3~
 163: kPRV4: (string) \033[5;4~
 164: kPRV5: (string) \033[5;5~
 165: kPRV6: (string) \033[5;6~
 166: kPRV7: (string) \033[5;7~
 167: kri: (string) \033[1;2A
 168: kRIT: (string) \033[1;2C
 169: kRIT3: (string) \033[1;3C
 170: kRIT4: (string) \033[1;4C
 171: kRIT5: (string) \033[1;5C
 172: kRIT6: (string) \033[1;6C
 173: kRIT7: (string) \033[1;7C
 174: kUP: (string) \033[1;2A
 175: kUP3: (string) \033[1;3A
 176: kUP4: (string) \033[1;4A
 177: kUP5: (string) \033[1;5A
 178: kUP6: (string) \033[1;6A
 179: kUP7: (string) \033[1;7A
 180: Ms: (string) \033]52;%p1%s;%p2%s\007
 181: op: (string) \033[39;49m
 182: rev: (string) \033[7m
 183: RGB: [missing]
 184: ri: (string) \033M
 185: rmacs: (string) \033(B
 186: rmcup: [missing]
 187: rmkx: (string) \033[?1l\033>
 188: Se: (string) \033[2 q
 189: setab: (string) \033[4%p1%dm
 190: setaf: (string) \033[3%p1%dm
 191: setrgbb: [missing]
 192: setrgbf: [missing]
 193: sgr0: (string) \033(B\033[m
 194: sitm: (string) \033[3m
 195: smacs: (string) \033(0
 196: smcup: [missing]
 197: smkx: (string) \033[?1h\033=
 198: smso: (string) \033[7m
 199: Smulx: [missing]
 200: smul: (string) \033[4m
 201: smxx: [missing]
 202: Ss: (string) \033[%p1%d q
 203: Tc: [missing]
 204: tsl: (string) \033]0;
 205: U8: [missing]
 206: vpa: (string) \033[%i%p1%dd
 207: xenl: (flag) true
 208: XT: (flag) true

% infocmp
\#       Reconstructed via infocmp from file: /lib/terminfo/s/screen-256color
screen-256color|GNU Screen with 256 colors,
        am, km, mir, msgr, xenl,
        colors#256, cols#80, it#8, lines#24, pairs#32767,
        acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=^M,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
        cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, ed=\E[J, el=\E[K, el1=\E[1K,
        enacs=\E(B\E)0, flash=\Eg, home=\E[H, ht=^I, hts=\EH,
        ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L, ind=^J, is2=\E)0,
        kbs=\177, kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC,
        kcuu1=\EOA, kdch1=\E[3~, kend=\E[4~, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf2=\EOQ, kf3=\EOR, kf4=\EOS,
        kf5=\E[15~, kf6=\E[17~, kf7=\E[18~, kf8=\E[19~, kf9=\E[20~,
        khome=\E[1~, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM, rmacs=^O,
        rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[23m,
        rmul=\E[24m, rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        sgr=\E[0%?%p6%t;1%;%?%p1%t;3%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;m%?%p9%t\016%e\017%;,
        sgr0=\E[m\017, smacs=^N, smcup=\E[?1049h, smir=\E[4h,
        smkx=\E[?1h\E=, smso=\E[3m, smul=\E[4m, tbc=\E[3g,

Will upload server log.

**Comment by ThomasAdam** [comment]
Could you try being less specific?

**Comment by mckellyln** [comment]
I am still editting, sorry

**Comment by mckellyln** [comment]
I will run without a config except for setting say message-style bg=brightyellow to see if it still does not work ok

**Comment by nicm** [comment]
Hmm. Your TERM only has 8 colours, so we should never have been using aix colours at all..

**Comment by nicm** [comment]
Are you sure it wasn't 6aa0bedad281cef0e9411f3530052d09bbc583f1 that broke this for you?

**Comment by mckellyln** [comment]
I can display all 256 colors ok

**Comment by nicm** [comment]
Are you starting tmux with -2?

**Comment by mckellyln** [comment]
I'll keep digging, I run tmux via byobu and that sometimes causes strange things.

**Comment by mckellyln** [comment]
Yes tmux -2 for sure

**Comment by nicm** [comment]
That is why then, we'll need a fallback for that case (TERM < 16 colours but user says 256). Give me a minute.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3118435/x.diff.txt)

**Comment by mckellyln** [comment]
Yes, that works well, thanks.
Do you know why my xterm has or think there are only 8 colours ?

**Comment by nicm** [comment]
Because you have TERM=xterm outside tmux, for >8 colours you need TERM=xterm-256color

**Comment by mckellyln** [comment]
ok, thanks again for awesome tmux.  
I exec byobu/tmux so early I never gave the original TERM setting enough thought, hadn't touched that in years.

**Comment by nicm** [comment]
I have applied this fix now anyway. Thanks!
