### ISSUE TITLE
tmux not supporting options that worked previously

### ISSUE THREAD

**Issue by jeffdn** [tmux/tmux#1691]
I have two recent MacBook Pros, both running OS X 10.14. Both are using the latest version of iTerm2, with the same exact config. Both are running tmux 2.9, installed via homebrew. However, one of them is having an issue with not recognizing several commands, and I am completely stumped. The error message is as follows:

```
/Users/jeff/.tmux.conf:61: invalid option: pane-border-fg
/Users/jeff/.tmux.conf:62: invalid option: pane-active-border-fg
/Users/jeff/.tmux.conf:66: invalid option: message-bg
/Users/jeff/.tmux.conf:67: invalid option: message-fg
/Users/jeff/.tmux.conf:84: invalid option: status-attr
/Users/jeff/.tmux.conf:87: invalid option: window-status-fg
/Users/jeff/.tmux.conf:88: invalid option: window-status-bg
/Users/jeff/.tmux.conf:89: invalid option: window-status-attr
/Users/jeff/.tmux.conf:91: invalid option: window-status-current-fg
/Users/jeff/.tmux.conf:92: invalid option: window-status-current-bg
/Users/jeff/.tmux.conf:93: invalid option: window-status-current-attr
```

This just began occurring, seemingly from nowhere. I can't find any similar instances via Google!

**Comment by blueyed** [comment]
Removed in 2.9.

Use `*-style` instead.  Check the man page.

**Comment by blueyed** [comment]
=> https://github.com/tmux/tmux/issues/1689

**Comment by jeffdn** [comment]
Ah, sorry for missing the other issue. Thanks, I’ll give it a shot.
