### ISSUE TITLE
Behavior change with regard to "default" in window-status-current-format

### ISSUE THREAD

**Issue by blueyed** [tmux/tmux#1692]
I am using `"#[default]"` with `set -g window-status-current-format`.

This previously used the `reverse` from `setw -g window-status-current-style reverse` correctly, but now appears to use the "real" default.

Part of the config:
```
set -g window-status-current-format "#[default,noitalics,nounderscore]  #[bold]#I#[nobold]#F #[default]#{?window_zoomed_flag,#[underscore],}#{=50:?window_name,[#W],#T}#[default,noitalics,nounderscore]   "
setw -g window-status-current-style reverse
```

I've figured that this can be simplified and fixed - e.g. the new "terminal" can be used here, but just wanted to note this, since I could not find it in the changes.
I'd be happy to git-bisect if it is not known/expected.

**Comment by nicm** [comment]
This is expected.

**Comment by nicm** [comment]
The default for the whole status line is now status-style.
