### ISSUE TITLE
C-t no prefix Mac-OS Mojave moves letter around

### ISSUE THREAD

**Issue by MeisterTea** [tmux/tmux#1694]
- My platform: macOS Mojave 10.14 18A2063 x86_64
- Description: Hi, I am trying to use [fzf](https://github.com/junegunn/fzf)
I would like to use the Ctrl+T shortcut to invoke it.
When in tmux (only on mac) (even with an empty tmux.conf), Ctrl+T moves the letter under cursor to the right and also keeps the cursor on this letter.
I can confirm it's not isolated to my environnement, I have this same behavior on another mac.
Removing fzf does not change the behavior
- I can reproduce it with an empty tmux.conf (same when settings screen-256color)
- terminal: xterm-kitty (it also occures on stock mac terminal)
- uname... output: ```
Darwin i386
tmux 2.8
xterm-kitty```

I attached the tmux-server log
Please note in this section I only typed this : 'zzzhello' [CTRL + T] 'k'
[tmux-server-38619.log](https://github.com/tmux/tmux/files/3120335/tmux-server-38619.log)

**Comment by nicm** [comment]
C-t is transpose character in most Bourne shells in emacs mode, are you sure this is not what you are seeing?

**Comment by MeisterTea** [comment]
Well, it's possible but it only occures on mac and tmux.
Without tmux (on zsh), I don't have this behavior

**Comment by nicm** [comment]
This is a feature of your shell, it is nothing to do with tmux. Apparently you have your shell configured differently inside and outside tmux.

**Comment by MeisterTea** [comment]
Well, it is indeed due to "^T" bindkey.
Do you have any idea how I could make it ignore the transpose character but still call fzf ?
I  tried bindkey -r "^T" but it still doesn't call fzf.
I suspect that there still is something preventing fzf from getting the command inside tmux.
Why else would it work outside it ?

Thank you for your help

**Comment by nicm** [comment]
I don't understand what you are trying to do.

Are you expecting tmux to know what to do with C-t by magic? Where have you configured what you want C-t to do?

**Comment by MeisterTea** [comment]
Well, of course I don't except it to be _that_ magic.
Installing [fzf](https://github.com/junegunn/fzf) makes it available with Ctrl + t.
It does work out of the box.
It does work if I don't enable emacs mode but it's not the fix I seek

**Comment by nicm** [comment]
You will need to ask the fzf developers.

**Comment by MeisterTea** [comment]
Fine, I will report back here later then

**Comment by deepredsky** [comment]
@MeisterTea  r u using bash? it seems you have binding of \C-t to the transpose function. try running `bind -P | grep transpose` to check. Also u can check if the fzf file widget it bound or not by running 

```
bash-4.4$ bind -X
"\C-t": "fzf-file-widget"
```

**Comment by MeisterTea** [comment]
Yes, it is binded by default with emacs mode. It works fine outside os x though

**Comment by deepredsky** [comment]
@MeisterTea most likely u have the emacs binding setting *after* loading fzf bindings. in your bashrc, try moving `set -o emacs` after sourcing of the fzf bindings script

**Comment by MeisterTea** [comment]
> @MeisterTea most likely u have the emacs binding setting _after_ loading fzf bindings. in your bashrc, try moving `set -o emacs` after sourcing of the fzf bindings script

It worked like a charm, thank you !
