### ISSUE TITLE
113W Failed to send command data within the configured

### ISSUE THREAD

**Issue by joeto0** [tmux/tmux#1696]
Hi guys,
I have really strange issue and to be honest cant find out from where this error comes. Is that tmux related or it is from somewhere else?

It happens when I am using CyberArk with ssh proxy, and on completely random manner it appear on screen and terminal is not useful anymore (SSH connection is active). 
Same behavior I have also with screen, so I thing it is something in common but cant find this error anywhere :(. 

CyberArk guys said that thats not error coming from CyberArk itself :(. I read one google group that is not tmux related. But at the end I cant find the reason alone :(. Please if you have any idea or recommendation or something to check - tell me :). I am desperate right now ...

**Comment by nicm** [comment]
This is not a tmux error and I'm pretty sure it isn't a putty or OpenSSH error. It seems most likely it is a CyberArk problem and they are lying to you. You could try running strings on their binary or on other binaries on the proxy server and see if you can find the error message or anything like it.

**Comment by joeto0** [comment]
For me issue was terminal type. 
If it is xterm connection is randomly broken. 
If it is Linux everything works without problem.

It is 100% CyberArk problem

**Comment by joeto0** [comment]
just if somebody have same issue, somehow is related to history limit

set -g history-limit 16000

works for me
