### ISSUE TITLE
[tmux 2.9] status-right-style being shadowed by status-style

### ISSUE THREAD

**Issue by gpanders** [tmux/tmux#1699]
Platform: macOS

I understand that the `status-style` option now sets the value of `#[default]` in the status line, but apparently setting `status-right-style` does not change `#[default]` when setting `status-right`:

Minimal `.tmux.conf`:
```tmux
set -g status-style fg=yellow,bg=black
set -g status-right-style fg=black,bg=yellow

set -g status-right "#[fg=red]Foo#[default] Bar"
```

I would expect to see `Bar` in the right side of my status line colored as black on yellow, but instead it appears as yellow on black.

If this is _not_ a bug, then what is the purpose of `status-right-style` if it is ignored in favor of `status-style`?

**Comment by nicm** [comment]
It's not a bug. status-right-style sets the style in the absence of #[].

**Comment by gpanders** [comment]
This seems to be a change in 2.9 then, because in prior versions this was not the case.

I use plugins that add things to `status-right` and use `#[default]` to "reset" the colors. For example, I use the [tmux-prefix-highlight](https://github.com/tmux-plugins/tmux-prefix-highlight) plugin, so in my own .tmux.conf I have
```tmux
set-option -g status_right " #{prefix_highlight} #S "
```
which expands to

```tmux
"#[fg=colour7,bg=colour4]#{?client_prefix, ^A ,#[default,fg=default,bg=default]}#[default] #S"
```

This means that the colors I _want_ to use in `status-right` are not observed at all, and are instead colored by the settings of `status-style`. But I wish to style the right side of my status bar differently than the rest of the status bar, which has of course been supported by tmux for a long time. So how then should a plugin "reset" the colors to respect the value of `status-right-style` if not with `#[default]`?

**Comment by nicm** [comment]
Yes, it was changed in 2.9.

**Comment by nicm** [comment]
You could probably reset it with #[#{E:status-right-style}].

It would be possible to recover the old behaviour by having some way to say "this is the new default" that the format_draw code could see and update the default. Perhaps something like default=push default=pop. Then status-format could use it, so the #[align=left range=left #{status-left-style}] section would become #[align=left range=left default=push #{status-left-style}] and be ended by a #[] containing default=pop.

This would not be terribly difficult to implement, but I don't think I'm likely to do this soon however, and now that 2.9 is out it is a bit academic at least for the next 6 months.

**Comment by gpanders** [comment]
`#[#{E:status-right-style}]` seems to work, I will use that for now.

This seems to also apply to `window-status-format` as well, i.e. using `#[default]` within `window-status-format` or `window-status-current-format` uses `status-style` instead of `window-status-style`. I realize this is not a bug with the current implementation, but it does seem more intuitive (to me, at least) that `#[default]` should be context dependent and default to the `*-style` option corresponding to the `*-format` option it is used in.

**Comment by nicm** [comment]
It applies to all the status line options.

**Comment by nicm** [comment]
It may seem better to you but I'm actually not convinced it is to someone who doesn't already know how it worked before. Perhaps.

If someone wants to do the work to restore the old behaviour I will certainly look at it :-).
