### ISSUE TITLE
Switching to another session blows away target session's environment variables!

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#17]
_I was surprised to find my email to tmux-users mailing list bounced. But GitHub is a great new home for tmux. Welcome to GitHub!_

I had a workflow that I quite liked which was that I would create **grouped** sessions and treat them in this way: each session "belongs" to a piece of physical hardware. 

My laptop's session `mac` can stay on window 0, and my desktop's large portrait-oriented monitor can be used in session `putty` can stay on window 1. The beauty is that the list of windows are shared in the sessions and the dimensional constraints are lifted whenever the sessions focus on different windows. 

I began to leverage more behavior based on sessions having their own environments. This is covered well in the manpage under ENVIRONMENT. What I took a liking to was that I could set `$GIT_AUTHOR_NAME` to a different value per session. This is really great because I can now train my shell to call `tmux showenv` and differentiate at the command level whether I executed the command from the tmux session corresponding to my laptop or the tmux session corresponding to my desktop. Indeed, setting the `$GIT_AUTHOR_NAME` accomplishes this very easily for Git. 

OK. so this still works as well as it ever did -- that is to say, really well. 

But in recent git builds, I have been noticing something sinister. Now, when I use `choose-tree` or `switch-client` to switch from session A to session B, session B's environment is **completely overwritten** by session A's session environment. This happens whether A and B are grouped or not.

Now this isn't a really unforgivable behavior, and it does certainly seem to fall outside of specified behavior, as far as the man page is concerned. 

However, I do have to say that it is very useful to be able to temporarily switch to another session just to e.g. move it off to another window, in order to get screen space back, for instance. Now I do imagine that if I remain disciplined (maybe bind a key that does something tricksy to cause the other session to change its focused window, but without actually switching to it to blow away its environment) I can avoid the environment-nuking. But I think I have sufficiently described the use case at this point.

Thanks!

P.S. I have now also tested this without loading my (rather elaborate) `tmux.conf`, and also without running my (also elaborate) zsh shell with tmux by reverting my shell to bash. So, the behavior seems to be easily reproducible and this all but eliminates the possibility that other configuration is causing the behavior. Commit `f7598b8`, OS X 10.10.3.

**Comment by nicm** [comment]
Please give instructions to reproduce this from a fresh server (started
with "tmux -Ltest -f/dev/null new").

**Comment by unphased** [comment]
Okay, I guess even though I did a lot of testing I still did not do deep enough testing. 

I discovered that only the variables specified in `update-environment` are exhibiting this problem. I think this means that I was depending on behavior of a bug that has since been fixed.

**Comment by unphased** [comment]
So, now the problem is that there is no functioning workaround for this behavior that I was using before and which now has been removed. 

Now, when you switch sessions, tmux treats this action in the same way as attaching to that session. It overrides the existing environment variables in that session. I am now hoping for a way to configure Tmux so that it will leave the variables be if they are already set.

**Comment by leerocket** [comment]
Sorry been busy

**Comment by ThomasAdam** [comment]
I'm in no position to test this right now; not even sure it compiles, but try the following:

https://github.com/ThomasAdam/tmux/commit/a97fecc051e3db8b0fe5cdb0ff91e3febb2fefda.diff

**Comment by unphased** [comment]
I am making a PR and will link it here shortly, but I am unsure how to proceed about editing the manpage.

**Comment by unphased** [comment]
@ThomasAdam Thanks, that is something that would be useful to do, though I am not certain that leaving existing values in (for them to get stale over the course of a long lived tmux server lifetime) is actually prudent either! Let me know what you think of my PR

**Comment by ThomasAdam** [comment]
So then unset it rather than continue.  I dunno; your PR adds another option which isn't wanted in this case either.  I'm still unsure whether environ_update() shouldn't just change its logic for all other cases where it's called.

But I've no time/desire to look into this now.

**Comment by nicm** [comment]
Moved to PR 20.
