### ISSUE TITLE
Consider adding easy motion into tmux scroll mode?

### ISSUE THREAD

**Issue by phye** [tmux/tmux#170]
TMUX is great! I've been using it for several years and still enjoying all the conveniences it bring to me. Thank you all in advance for this brilliant project!

Here's something I found missing in tmux, quick movement in scroll mode. For example if I want to copy a word at the middle of a line, I can only do this either using mouse, or using word-by-word jump, or using the relative slow search. All these are not quick enough :smile: 

Easy motion in vim/Ace jump in emacs, makes it very convenient to move in 'visual mode'.  Take Ace jump as an example, say you want to move to the first j in Ace jump within this line, you can simply hit space bar, and Ace jump will prompt you with character you're interested, and you provide j, and Ace Jump prompt you with the character lists to input regarding to all 'j's and you supply the chars and you're there! Very convenient. 

So can you consider add this into the next tmux release? Thanks!

Here're the links.
http://www.vim.org/scripts/script.php?script_id=3526
http://www.emacswiki.org/emacs/AceJump

**Comment by nicm** [comment]
I don't think this is likely to come soon, but maybe someone will do it.

**Comment by IngoHeimbach** [comment]
Is it technically possible to write a tmux extension that would bring easy-motion to tmux or would it be necessary to modify tmux source code?
