### ISSUE TITLE
Issue with nnn

### ISSUE THREAD

**Issue by juliorcx** [tmux/tmux#1700]
Hi,

My system is,

```
Linux Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
tmux 2.7
screen
```

I have a problem with nnn file browser, because when I use it in st terminal, I can create new files with the names I want or even rename a file. But when I use tmux within st, I can create files, but I can not modify the name once I've pressed the key, i.e. I type some letter and I can't delete it. 

I'd like to know why this is happening.

Thanks for your reponse

[tmux-server-32226.log](https://github.com/tmux/tmux/files/3125507/tmux-server-32226.log)

**Comment by juliorcx** [comment]
Hi,

My system is,
`Linux Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
tmux 2.7
screen`

I have a problem with nnn file browser, because when I use it in st terminal, I can create new files with the names I want or even rename a file. But when I use tmux within st, I can create files, but I can not modify the name once I've pressed the key, i.e. I type some letter and I can't delete it. 

I'd like to know why this is happening.

Thanks for your reponse

[tmux-server-32226.log](https://github.com/tmux/tmux/files/3125507/tmux-server-32226.log)

**Comment by nicm** [comment]
This looks fine to me. Can you delete if you press ^H instead of Delete?

**Comment by juliorcx** [comment]
That works thanks :+1: 
But is more intuitive with Delete

Thank you for fast reponse

**Comment by nicm** [comment]
It sounds like nnn has the wrong idea about what key to expect for Delete.

What does "infocmp|grep kbs" show inside tmux?

Does running "TERM=tmux nnn" make any difference?

**Comment by juliorcx** [comment]
For `infocmp | grep kbs`
```
ind=\n, indn=\E[%p1%dS, is2=\E)0, kbs=^H, kcbt=\E[Z,
```

And `TERM=tmux nnn` does not do anything

**Comment by nicm** [comment]
So kbs is wrong inside tmux, but perhaps nnn is not looking at it anyway.

What do you have TERM set to inside tmux?

What does "infocmp tmux|grep kbs" show also?

**Comment by juliorcx** [comment]
For `infocmp tmux|grep kbs`
```
kPRV=\E[5;2~, kRIT=\E[1;2C, kbs=^H, kcbt=\E[Z, kcub1=\EOD,
```

I don't have any TERM set inside tmux, I use it within st

**Comment by juliorcx** [comment]
```
# Status theme
set -g message-style "bg=#d79921, fg=#000000"

set -g status-style "bg=#222222, fg=#999999"
set -g status-left "#[bg=#222222] #S "
set -g status-left-length 400
set -g status-right-length 600
set -g status-right "#{?client_prefix, C-a , } #[bg=#333333] #(whoami)@#h #[bg=#222222] %Y-%m-%d %H:%M "

set -g history-limit 2000

set -wg window-status-format " #I #W "
set -wg window-status-current-format " #I #W "
set -wg window-status-separator ""
set -wg window-status-current-style "bg=#005577, fg=#eeeeee"
set -wg window-status-last-style "bg=#333333, fg=#b3b3b3"

set -wg pane-active-border-style "fg=#005577"
set -wg pane-border-style "fg=#444444"

set-option -g prefix C-a
unbind C-b
bind-key C-a send-prefix
set -g exit-unattached on
# set -g destroy-unattached on
```

Here is my tmux config

**Comment by nicm** [comment]
You must have TERM set inside tmux or nothing would work - check with "echo
$TERM".

I thought the tmux terminfo had ^? for kbs but apparently not.

You could try doing this:

infocmp tmux >x

Then edit the x file and change kbs=^H to kbs=^? then install it with:

tic ./x

The you will need to set TERM=tmux inside tmux (or set -g default-terminal
tmux in .tmux.conf).

**Comment by juliorcx** [comment]
```
echo $TERM
screen
```

> Then edit the x file and change kbs=^H to kbs=^? then install it with: tic ./x

That works thank  you so much
