### ISSUE TITLE
tmux 2.9: select-pane null dereference

### ISSUE THREAD

**Issue by gnachman** [tmux/tmux#1701]
This affects all platforms and does not depend on tmux.conf (I have none). I have confirmed the crash still occurs on master.

tmux version 2.9 crashes in control mode with the command "select-pane" when there are multiple window panes in the current window.

To reproduce the crash:

1. Create two window panes
2. detach
3. `tmux -C`
4. `select-pane -t %0`

## Analysis

The reason is `tty->client` is `NULL` in `tty_window_bigger`. Its caller, `cmd_select_pane_redraw`, iterates over clients and calls passes it the client's tty. Control mode clients ttys don't have a pointer back to the client because the tty is not initialized in `server_client_dispatch_identify` since there isn't a tty attached.

**Comment by nicm** [comment]
What is the impact of this?

**Comment by rprimus** [comment]
Tue Apr 30 18:48:34 BST 2019

Tmux dies (started with `tmux -CC att -dt <session>`).   Please see:
https://gitlab.com/gnachman/iterm2/issues/7758

**Comment by nicm** [comment]
I wasn't asking you, and I wasn't asking what happens, I was asking what the impact is. Is every user going to see this or only a few?

**Comment by Jesin** [comment]
When you said "every user", did you mean "every user of [iTerm2](/gnachman/iTerm2)" or "every user of tmux"? I use tmux and I haven't personally encountered this problem so far (this is the first time I've heard of "control mode" or iTerm2), though a server segfault sounds like it could be pretty bad.

**Comment by gnachman** [comment]
iTerm2 users who use control mode (`tmux -CC`) experience crashes when switching between window panes. I don't have good numbers on how many people this affects as I don't have telemetry.

**Comment by nicm** [comment]
It happens to everyone who uses control mode though?

**Comment by nicm** [comment]
I have made a 2.9a release which fixes this and another bug with layouts.

@gnachman would it be OK if I CC iterm2-discuss@googlegroups.com on RC and release announcements? Clearly nobody who uses iTerm2 + tmux tried this before now.

**Comment by gnachman** [comment]
Provided they use split panes, they'll encounter the bug.

I would be very glad to get RC announcements. I always forget to keep up to date on them and sometimes get surprises. Thank you!

**Comment by nicm** [comment]
Alright, I'll try to remember! Thanks!
