### ISSUE TITLE
Crash when running `$ tmux show-options -g` from a shell script

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1704]
After a recent update, tmux doesn't start anymore. It seems to crash, and outputs this error message on the shell's command-line:

    lost server

It doesn't crash with no configuration, so I had to trim down my config until I could find a MWE.
Here's what I found.

Inside `/tmp/tmux.conf`, write these 2 lines:

    set -g @plugin 'foo'
    run '/tmp/sh.sh'

And inside `/tmp/sh.sh`, write these 2 lines:

    #!/bin/bash
    tmux show-options -g

Finally start tmux with the previous minimal tmux.conf:

    $ ./tmux -L test -f /tmp/tmux.conf new

Currently, this prevents me from starting tmux if I use one of these two plugins:

 - [tmux-copycat](https://github.com/tmux-plugins/tmux-copycat)
 - [tmux-open](https://github.com/tmux-plugins/tmux-open)

---

I'm on Linux, Ubuntu 16.04. My terminal is st, and outside tmux, my `$TERM` is `st-256color`.

Here is the output of `$ uname -sp && ./tmux -V && echo $TERM`:

    Linux x86_64
    tmux next-3.0
    tmux-256color

I've run `$ ./tmux -L test -f /tmp/tmux.conf -vv new`, and here's the output of [tmux-client-20522.log](https://0x0.st/zcQ3.txt), and [tmux-server-20524.log](https://0x0.st/zcQY.txt).

I've also tried to run `$ gdb -n -ex 'thread apply all bt full' -batch ./tmux ./core` to get [a backtrace](https://0x0.st/zcQg.txt).

Finally, I've tried to run `$ git bisect` to find the offending commit, and, I could be wrong, but it seems to be [`5489796`](https://github.com/tmux/tmux/commit/5489796737108cb9bba01f831421e531a50b946b).

**Comment by nicm** [comment]
Good bug report - fixed in OpenBSD now, will be in GitHub later, thanks!
