### ISSUE TITLE
[Feature Request] Allow to save history of each panel in a session

### ISSUE THREAD

**Issue by ioprotium** [tmux/tmux#1705]
Hello everyone.
I use tmux a lot at work and in personal life. I tend to create sessions and save the environment with **tmux resurrect plugin**. I think it will be awesome that after I "resurrect" the environment I can access to the last commands executed on each panel.

Best regards

**Comment by nicm** [comment]
tmux doesn't know what you ran I  each pane, only your shell does.

**Comment by nicm** [comment]
Or do you mean the scrolled history and pane content? You can save it already, just not quickly load it.

I would be open to a diff to support that but it isn't much use on its own, I'd like to see evidence it's going to be used for something.

**Comment by ioprotium** [comment]
Yes, the scrolled history will work as intended. 
Every time I restore the environment of a session I want to be able to just use the up arrow key or **!!** to see and execute the last commands that were executed in the pane. That's extremely useful when running long commands in different panes. 

I've just found that tmux resurrect is working on that [https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_shell_history.md](https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_shell_history.md) So you can close this issue.

Thanks!

**Comment by krader1961** [comment]
Your shell should be saving your command history. That isn't the responsibility of tmux. Not to mention there is no way for tmux to affect what command is retrieved by your shell when you press [up-arrow] ([ctrl-p], etc.). I only skimmed that code your linked to but it's mechanism for saving/restoring shell command history looks fragile.

**Comment by nicm** [comment]
No the up arrow key will not work, that is only known by your shell.
