### ISSUE TITLE
change the default pane_title

### ISSUE THREAD

**Issue by zzploveyou** [tmux/tmux#1706]
Default pane_title(#T) is the hostname(#H).

How can i change it to something else like #{pane_current_path}?

**Comment by nicm** [comment]
select-pane -T

**Comment by zzploveyou** [comment]
![Snipaste_2019-05-01_14-37-36](https://user-images.githubusercontent.com/22740824/57007932-d3381f00-6c1e-11e9-9ed4-f47c73c2b216.png)

default pane-title is hostname.

**Comment by nicm** [comment]
Yes I know. You can change the pane title either from inside the pane with the escape sequence or outside with select-pane -T.

**Comment by nicm** [comment]
You could also do something like this in your status-right:
~~~~
#{?#{==:#{pane_title},#{host_short}},mytitle,#{pane_title}}

**Comment by zzploveyou** [comment]
@nicm Thanks. This's exactly what I want.
