### ISSUE TITLE
Documentation for STYLES differs from actual usage

### ISSUE THREAD

**Issue by kenrachynski** [tmux/tmux#1707]
The documentation at http://man.openbsd.org/OpenBSD-current/man1/tmux.1#STYLES says the following (emphasis mine):

>A style may be the single term ‘default’ to specify the default style (which may inherit from another option) or **a space** or comma separated list of the following

In practice, however, the style options do not support a space separated list.

**Comment by nicm** [comment]
~~~~
$ tmux set -g status-style 'fg=red bg=blue
$ tmux show -g status-style
status-style fg=red,bg=blue
$
~~~~

**Comment by kenrachynski** [comment]
Interesting. I don't see that in the documented examples, though.

**Comment by nicm** [comment]
Eh? There is an example with spaces and an example with commas.

**Comment by kenrachynski** [comment]
The examples show spaces and commas, yes. I was referring to the need for quotes... oh hang on, you're doing it on the command line which requires spaces to be quoted. I was thinking of this as a config file. Documentation for config doesn't say "need quotes for spaces". At least near the section I was reading.

**Comment by nicm** [comment]
All commands where you want to include spaces in a single argument need
quotes.

**Comment by kenrachynski** [comment]
Alright, chalk me up for being dense about that.

**Comment by nicm** [comment]
No worries.
