### ISSUE TITLE
After upgrading to 2.9 pane layout is slightly broken

### ISSUE THREAD

**Issue by codesuki** [tmux/tmux#1708]
I always use C-b-SPC to choose a layout and since the upgrade, the lower right pane is a bit too low and there are weird shapes between the top and bottom pane that were not there before.
<img width="1680" alt="Screen Shot 2019-05-02 at 11 18 55" src="https://user-images.githubusercontent.com/5276006/57053974-b9edac00-6ccc-11e9-9da2-80d996f49fc9.png">

**Comment by nicm** [comment]
Does this still happen with 2.9a?

**Comment by codesuki** [comment]
What a timing! I'll try tomorrow. Didn't notice there was a new one yesterday.

**Comment by codesuki** [comment]
Fixed, perfect! Thank you.
