### ISSUE TITLE
Reverse video terminal default color in statusline broken after 2.9 (and 2.9a) upgrade

### ISSUE THREAD

**Issue by brendes** [tmux/tmux#1709]
```
~ $ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.9a
screen
```
* Terminal emulators: Terminal.app, iTerm2, xterm
* `$TERM`s outside tmux: `xterm`, `xterm-256color`, `vt100`

### Description
After upgrading from 2.8 to 2.9, my statusline, whose background and foreground contain the 'reverse' formatting attribute, is now blank where it contains no text, instead of being filled with the reverse-video color.

Setting the statusline background attribute to anything but `reverse` produces expected behavior: background color covering the entire width of the statusline, even when it is not filled by text.

### Screenshots
* An example of what it used to look like (OpenBSD server using base tmux):
![expected](https://i.imgur.com/Ol172f0.png)
* What it now looks like after upgrading to 2.9:
![current](https://i.imgur.com/RgXmnHS.png)

What I expect to see (and what I used to see) was the entirety of the statusline being filled with the specified background (`bg=default,reverse`), even where there is no next.

### Config
This new behavior persisted even after updating my tmux.conf to the new formatting syntax introduced by 2.9.

* Before upgrade: `set -ag status-style bg=default,reverse,fg=default,reverse`
* After upgrade: `set -g status-style bg=terminal,reverse,fg=terminal,reverse`

Please let me know if there's any other info I can provide to assist in diagnosing this issue.

**Comment by aswild** [comment]
I have a similar after upgrading from 2.8 to 2.9, it seems like `#[default]` doesn't inherit as expected anymore.

I have a semi-fancy theme generated by the [tmuxline](https://github.com/edkolev/tmuxline.vim) vim plugin, some relevant snippets:

```
setw -g window-status-style none,fg="colour187",bg="colour235"
setw -g window-status-activity-style none,fg="colour64",bg="colour235"
setw -g window-status-format "#[fg=colour235,bg=colour235,none]#[default] #I #{?window_zoomed_flag,[Z],}#W #[fg=colour235,bg=colour235,none]"
```


The idea is to use custom color styles for separator characters, then inherit window-status-style or window-status-activity-style for non-current windows.
In tmux 2.8, the `#[default]` applies the right formatting from window-status-style or window-status-activity-style, but in 2.9 it seems to apply the global default terminal style.

Any ideas how how `#[default]` is supposed to work?

**Comment by brendes** [comment]
@aswild 's comment reminded me to test another condition.

The setting `set -g status-style bg=green,reverse,fg=white,reverse` produces the following:
![green_reverse](https://i.imgur.com/MB46D21.png)

**Comment by nicm** [comment]
Yes, you're right. Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3139801/x.diff.txt)

~~~~
Index: status.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/status.c,v
retrieving revision 1.196
diff -u -p -r1.196 status.c
--- status.c	26 Apr 2019 11:38:51 -0000	1.196
+++ status.c	2 May 2019 20:17:41 -0000
@@ -372,7 +372,10 @@ status_redraw(struct client *c)
 
 			ov = options_array_get(o, i);
 			if (ov == NULL) {
-				screen_write_clearline(&ctx, gc.bg);
+				if (gc.attr & GRID_ATTR_REVERSE)
+					screen_write_clearline(&ctx, gc.fg);
+				else
+					screen_write_clearline(&ctx, gc.bg);
 				continue;
 			}
 			sle = &sl->entries[i];

**Comment by nicm** [comment]
You will probably need to apply this to master actually.

**Comment by brendes** [comment]
@ncim: Thank you. I did apply it to master, but to no avail.

**Comment by nicm** [comment]
Oops, I tested on the wrong machine. Try this instead please: [x.diff.txt](https://github.com/tmux/tmux/files/3139905/x.diff.txt)

**Comment by brendes** [comment]
No worries. Applied latest patch; behavior still persists.

**Comment by nicm** [comment]
Are you sure you restarted tmux entirely?

**Comment by brendes** [comment]
I'm pretty sure:
```
~/tmux[master] $ patch < ~/x.diff.txt
patching file status.c
~/tmux[master] $ ./autogen.sh && ./configure && make
~/tmux[master] $ ./tmux -V
tmux next-3.0
~/tmux[master] $ tmux ls
no server running on /private/tmp/tmux-629247714/default
~/tmux[master] $ rm -rf /private/tmp/tmux-629247714/
~/tmux[master] $ ./tmux
```

**Comment by nicm** [comment]
This fixes it for me, what exactly do you have in .tmux.conf?

**Comment by nicm** [comment]
Oh you are using fg=bg=terminal, this won't work...

**Comment by nicm** [comment]
Please try this instead: [z.diff.txt](https://github.com/tmux/tmux/files/3141002/z.diff.txt)

**Comment by brendes** [comment]
Eureka:

<img width="682" alt="Screen Shot 2019-05-03 at 5 42 35 AM" src="https://user-images.githubusercontent.com/3211522/57130157-a55df200-6d66-11e9-94e0-69c81db1a264.png">

Nicholas, thank you so much for your time on this as well as your work overall on this indispensable tool. I really appreciate your help.

**Comment by nicm** [comment]
Great - I have applied this to OpenBSD now, it will be in Git master later. Thanks!
