### ISSUE TITLE
set -g mouse on does not work in .tmux.conf

### ISSUE THREAD

**Issue by croessner** [tmux/tmux#171]
Hi,

I replaced my old mouse settings with just one line in the .tmux.conf file on Mac OS X 10.11.1:

set -g mouse on

It does not work. I also tried to use -s or leave the flage away. No changes. It only works to type tmux set mouse on in the tmux window itself.

~/.tmux.conf:

  set -g mouse on
  
  # Toggle mouse on
  bind m \
    set -g mouse on \;\
    display 'Mouse: ON'
  
  # Toggle mouse off
  bind M \
    set -g mouse off \;\
    display 'Mouse: OFF'

**Comment by nicm** [comment]
You probably didn't restart tmux properly

-------- Original message --------

**Comment by croessner** [comment]
I don't think so:

1. Open iTerm
2. Edit .tmux.conf
3. Save file
4. Type tmux
5. Type Ctrl+b %
6. Click at the other side and nothing happens
7. Type: tmux set -g mouse on
8. Try again clicking. This time it works

That is what I tried. I also tried the same in OS X Terminal.app with the exact same problem.

**Comment by nicm** [comment]
So pkill tmux first.

**Comment by croessner** [comment]
Thank you very much. I never knew that there still runs a tmux, even all terminals are closed. Tried it and it works.
