### ISSUE TITLE
MouseDrag ignores coordinates of first event

### ISSUE THREAD

**Issue by avih** [tmux/tmux#1710]
Using tumx master and this config:
```
set-option -g mode-keys vi
set-option -g mouse on
```

In many terminals (xterm, VTE-based, kitty, st, probably others):
- It's impossible to resize a pane by 1 cell by dragging its border, except by first dragging it 2 cells and then going back one cell.
- Similarly, it's impossible to drag-select (highlight) two cells, except by first selecting/highlighting 3 cells and then going back one cell.

Analysis:

The terminals where the issue exist report mouse move only when the cell changes. This means that with the text AB, if the mouse is pressed (and held) over A, and then dragged over to B, they report press at A -> move at B.

urxvt reports press at A -> move at A -> move at B and tmux behaves as expected. However, if the press was at the rightmost pixel of cell A, then the first move event will be at B, and the same issue will manifest.

I looked at the relevant tmux code, and it appears that the first drag event is always reported where the mouse was pressed and not where the move was reported by the containing terminal.

For later drag events, they're reported with correct coordinates.

I understand why tmux reports the first move where the mouse was pressed (to identify the cell which is the drag origin for pane-resize, selection, etc), however, this also effectively makes it ignore the real coordinates of the first drag event.

My idea for a solution is that the first terminal move event will send two tmux drag events: the origin (press) coordinates, followed by a drag with the actual new coordinates as reported by the terminal.

Additionally and optionally, tmux may ignore all move events which have the same coordinates as the previous event for the same button (be it press or move). This will make it behave like most terminals even if the containing terminal sends a move event for the same cell as the press.

However, I couldn't make this work with a simple patch.

**Comment by nicm** [comment]
Yes, you're right. This is a bit of a pain in the arse.

We have the drag update mouse key in the buffer, so I thought we could just leave it there and process it again (that is, first time we see it is drag-start and second is drag-update). I think that would work... except that the mouse_drag_update is not set until resize-pane -M is executed, which happens well after the key is processed fro the second time.

So we need to inject it from the command queue, I guess we can just copy the key and do it later...

**Comment by nicm** [comment]
This works but I don't really like it: [x.diff.txt](https://github.com/tmux/tmux/files/3140106/x.diff.txt)

It will also need to suppress the extra key from urxvt.

**Comment by nicm** [comment]
It might be nicer to leave the sequence in the key buffer and change to only process one key between goes at the command queue, which is probably a good idea anyway.

**Comment by avih** [comment]
Agreed. Not very nice, and the code doesn't make it easy to do this kind of input processing. I didn't test it, but if I understand it correctly, I think there's no need to filter with urxvt, as the extra event shouldn't do any harm.

I did write a simple patch to st which does exactly that, especially to handle this tmux issue: if st is about to report the first move event after a press, then first report a pseudo move at the press coordinates, and then report the real move event. It works fine but I thought ultimately this needs to be fixed in tmux, hence this report.

I don't think there's any urgency to fix it, but it does feel a bit awkward that the drag doesn't behave as one normally expects.

> It might be nicer to leave the sequence in the key buffer and change to only process one key between goes at the command queue, which is probably a good idea anyway

Yes, I did attempt this approach as well, though so far not at the right place (I tried duplicating the `bufferevent_write` under the right conditions at `input_key_mouse`, but apparently this is tmux reporting mouse events to client, not for tmux key table consumption).

**Comment by nicm** [comment]
It is easy to leave it in the buffer (just tell tty_keys_next not to call evbuffer_drain), the problem is that if won't help unless the command queue gets to run before it is processed so that the key binding command can set the cb. So that part needs to change. I haven't looked at it. It shouldn't be that difficult I think although will need to make sure there aren't any undesirable side effects.

**Comment by avih** [comment]
An alternative approach (didn't look at the relevant code yet), is to save the mouse-down coordinates, add some meta KEYC_MOUSEDRAG<N>_* handler which will be called with the real move coordinates, and this handler will then dispatch a pseudo drag event with the press coordinates and then KEYC_DRAGGING with the real coordinates. Though so far it's just yet another idea.

**Comment by nicm** [comment]
That could work yes because KEYC_DRAGGING doesn't have to do the full key
binding dance because you can only bind keys to drag start and end
(DRAGGING is just a marker to say "fire the callback"). But it would still
need to make sure the command for the initial drag start key binding had
been executed or the drag callback wouldn't be set.

We could probably just add a wrapper function  to set the drag update cb
which immediately fires it with x,y if they are different from the start
position. That would work quite well, I'll take a look later.

**Comment by nicm** [comment]
Please try this which seems to fix it: [y.diff.txt](https://github.com/tmux/tmux/files/3140903/y.diff.txt)

**Comment by avih** [comment]
> Please try this which seems to fix it: y.diff.txt

It does seem to work. Still trying to understand how, and why the generated first update needs to use a copy of the mouse struct...

**Comment by nicm** [comment]
It needs to change the x,y position, but what if there is a command
sequence and another command wants to use it?

I'm not sure that can usefully happen right now, but it's better to copy...

**Comment by avih** [comment]
I trust your judgment on this better than mine. I don't yet have a clear mental model of it, just a rough one.

**Comment by avih** [comment]
FWIW, I'm not yet convinced your solution 100% works. There _appears_ to be 1 cell offset introduced after dragging back and forth, though I'm still testing.

**Comment by avih** [comment]
Yeah, there's 1 cell offset which is introduced once in the direction of initial drag and seems to happen only with border drag. So dragging the border 1 cell works, but for the 2nd cell it behaves as if it was dragged 3 cells, and this offset stays till the mouse is lifted.

Selection seems unaffected.

**Comment by nicm** [comment]
Yes this is because resize-pane is incremental and it goes from the last x,y but when it gets the second drag the last x,y is the position of the actual last key, not the fake one. Maybe it is better to inject an actual fake key like my first attempt so everything gets updated as intended.

**Comment by avih** [comment]
> Yes this is because resize-pane is incremental and it goes from the last x,y but when it gets the second drag the last x,y is the position of the actual last key, not the fake one

Yes, and I tried to account for that by updating lx/ly as well accordingly, but I must be doing something wrong because an offset always rears its head at some point.

**Comment by nicm** [comment]
The mouse_event struct needs to stay unchanged after server_client_handle_key returns so you can't change lx,ly in it.

**Comment by avih** [comment]
Yeah, well... this data flow melts my brain. I think I'll leave it aside for now. I'll be available to test patches if you want.

**Comment by avih** [comment]
FWIW, the first patch does seem to work for selection and border drag.

It does catch an offset of 1 if dragging the border to the edge of the screen and back - but so does an unpatched tmux, so no regressions as far as I can tell.

**Comment by nicm** [comment]
Yes the mouse is a pain cos there is so much state.

It is a bit complicated but not that bad really. tty_keys_next and server_client_check_mouse build the struct mouse_event in struct tty. They are the only ones that should modify it. It holds the most recent mouse state.

When a key binding is found, it has a cmd_list attached. This needs to go onto the command queue. But a cmd_list may have multiple commands (eg if you bind a key to a command sequence like "lsk;lastp;killp" it has 3 commands). Each command needs to end up on the command queue separately - the reason for this is that some commands may generate other commands, and they need to go into the right place - so if you have "lsk;if-shell 'true' 'killp';swapp" the killp needs to after the lsk, not after the swapp - but the killp is only created when the if-shell is executed not when the key is pressed. So a cmd_list can't be placed on the command queue as one atomic item, it needs to be split up. We do this when we create a cmdq_item for the key - we actually create a list of items. See cmdq_get_command for this.

The mouse_event is copied into the cmdq_item but it is placed in a struct cmdq_shared which is shared by all the cmdq_items that were created for that key. So if you have the "lsk;lastp;killp" they all share the same mouse_event - so they can't modify it.

The thing that makes this problem kind of awkward is that keys are processed all in one go, so if you have bound key "a" to lsk and key "b" to lastp, then the two keys are processed before /either/ of the commands are executed. In this instance "a" is our real mouse event and it is bound to MouseDrag1Border which calls resizep -M which sets the drag callback. So we can't insert a fake key "b" to do anything which requires the drag callback, unless we make sure it is after the resizep -M is fired.

Now that I've noticed this, I don't like how this works. I think key bindings should go on the queue, so if you press "a" then "b", the lsk is fired before the "b" is processed. So I think I might change that, which might make this a bit easier to fix, although I don't think it will be any more elegant.

**Comment by avih** [comment]
Appreciate the info, and I (now) get the general gist, though it would take time (and re-reads, and tumbling through the code) before it sinks, if at all.

> So I think I might change that... although I don't think it will be any more elegant.

Sounds like it would be more correct though, so if it can be done in a non hacky way, even if still complex, then it sounds to me like a good idea.

**Comment by nicm** [comment]
This seems to fix it without having to faff around sending the key again? [z.diff.txt](https://github.com/tmux/tmux/files/3142749/z.diff.txt)

**Comment by avih** [comment]
z.diff gets an offset while dragging a pane border, similar to y.diff - from the 2nd dragged cell onward. Selection seems OK.

**Comment by nicm** [comment]
Here is a better diff: [zz.diff.txt](https://github.com/tmux/tmux/files/3142924/zz.diff.txt)

The problem is really that we write the x,y in server_client_check_mouse back into the mouse_event, so at the start of the drag we end up with x,y == lx,ly and the first part of the drag is lost. But there isn't any need to do that really. The drag code for copy mode and resizing already know to use lx,ly at the start of the drag; the x,y in server_client_check_mouse is only needed to make sure we pick the right key binding for drag start (Pane or Border or Status). So we can remove that and just leave x,y as the actual drag start in the mouse event. This seems to fix it for me.

**Comment by nicm** [comment]
You may need to wait for GitHub to sync from OpenBSD for this to apply because I've made some fixes to the mouse when the window is bigger than the client.

**Comment by avih** [comment]
Now tmux master (after the sync) got broken compared to before (drag border responds on 1st cell but gets an offset), and zz.diff fixes it to not have an offset (while keeping it responsive since first cell drag). Didn't test much but seems that both border drag and selection are OK with zz.diff .

**Comment by nicm** [comment]
Hmm yes. Anyway I have applied this now, let me know if you see any further problems. Thanks!

**Comment by avih** [comment]
Will do. Thanks!
