### ISSUE TITLE
Duplicate window-size entry in manpage

### ISSUE THREAD

**Issue by acr4** [tmux/tmux#1711]
`window-size` is listed twice (with slightly different verbiage) in the `set-window-option` sub-heading of the top-level `OPTIONS` heading.

This is seen in TMUX 2.9a.  I haven't checked other versions

**Comment by acr4** [comment]
`default-size` is also duplicated in the `set-option` sub-heading.

**Comment by nicm** [comment]
Yes you are right, this went missing in a merge and I then thought I hadn't added it so added it again. Will fix it up, thanks!

**Comment by acr4** [comment]
Better to document twice than to not document at all!
