### ISSUE TITLE
Duplicate window-size option entry in man page

### ISSUE THREAD

**Issue by tardypad** [tmux/tmux#1713]
Just saw this while reading the doc of that new option
https://github.com/tmux/tmux/blob/master/tmux.1#L3424
https://github.com/tmux/tmux/blob/master/tmux.1#L3454
I don't know which one should be kept

**Comment by nicm** [comment]
There was literally an issue about this yesterday...

**Comment by tardypad** [comment]
Ah sorry I didn't check :/
Not sure though why you closed the issue while it is not fixed yet, I would definitely have seen it then
