### ISSUE TITLE
user-keys not working in 2.9(a)

### ISSUE THREAD

**Issue by muhmud** [tmux/tmux#1714]
Mapping user-keys and binding doesn't seem to work in 2.9 and 2.9a. I've gone back to 2.8 in order to get it working like it used to.

This is what I'm doing:
```
set -s user-keys[8] "\e[00N9{"
bind -n User8 new-window
```

**Comment by nicm** [comment]
Logs, platform, terminal?

**Comment by nicm** [comment]
Actually, never mind, I see what is wrong.

This is the fix:
~~~~

**Comment by nicm** [comment]
Fix applied to OpenBSD now, will be in GitHub later. Thanks!
