### ISSUE TITLE
"Main" layout is unusable on 2.9

### ISSUE THREAD

**Issue by hbarcelos** [tmux/tmux#1716]
My environment:
- Linux 4.19.36-1-MANJARO #.1 SMP PREEMPT x86_64
- tmux: 2.9
- `$TERM`: screen-256color

I am able to reproduce the issue without any custom settings, so there's no `.tmux.conf` to show here.

When using split panes, the default 50-50 works just fine. I also like to work with the "main" layout, which I access by hitting <kbd>CTRL+B</kbd><kbd>ALT+4</kbd>. When I do that, however, the larger pane becomes unusable: 

![Main Layout](https://user-images.githubusercontent.com/16565602/57185371-777cc880-6ea0-11e9-836e-485058aacb01.png)

The same happens for <kbd>CTRL+B</kbd><kbd>ALT+3</kbd>.

![Vertical Main Layout](https://user-images.githubusercontent.com/16565602/57185438-e575bf80-6ea1-11e9-9a01-2f12de5e9795.png)

Bellow is the 50-50 layout for comparison:

![50-50 Layout](https://user-images.githubusercontent.com/16565602/57185429-bbbc9880-6ea1-11e9-8e6e-386b0859b3ff.png)

**Note:** even if I cycle the layouts with <kbd>CTRL+B</kbd><kbd>SPACE</kbd>, the results are still the same,

**Comment by nicm** [comment]
There is no 2.9-1 do you mean 2.9a?

**Comment by hbarcelos** [comment]
You are right.
`tmux -V` gives me `2.9` back.

I believe `2.9-1` is the package version in Arch Linux repository.

**Comment by nicm** [comment]
Does this still happen with 2.9a?

**Comment by aherrmann** [comment]
I've encountered the same issue on 2.9.

Furthermore, if in the upper right pane of the "main layout" as depicted [here](https://user-images.githubusercontent.com/16565602/57185371-777cc880-6ea0-11e9-836e-485058aacb01.png) I close my bash shell by pressing Ctrl-D, then tmux terminates unexpectedly, killing all open sessions, and causing all running tasks in all open tmux panes to terminate. (A following `tmux list-sessions` shows that there are no more active sessions).

I haven't tested this on 2.9a, yet.
