### ISSUE TITLE
Invalid demo config

### ISSUE THREAD

**Issue by arthurkiller** [tmux/tmux#1717]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

https://github.com/tmux/tmux/blob/e8f4ca6a52bdfb7d8e2b8c39b867f2e2528a7631/example_tmux.conf#L9

and I added this 

> set -g window-status-current-attr "underscore"

then tmux report this.

```bash
/Users/arthur/.tmux.conf:21: invalid option: window-status-current-attr
```

version:

```bash
arthur@ArthursMacBookPro:~$ tmux -V
tmux 2.9
arthur@ArthursMacBookPro:~$ brew info tmux
tmux: stable 2.9 (bottled), HEAD
Terminal multiplexer
https://tmux.github.io/
/usr/local/Cellar/tmux/2.9 (10 files, 748.4KB) *
  Poured from bottle on 2019-04-26 at 14:44:25
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tmux.rb
```

**Comment by nicm** [comment]
Yes, this is wrong. I'll change this when I get back on  Tuesday.

**Comment by nicm** [comment]
Thanks.

**Comment by arthurkiller** [comment]
thx for reply

By the way, I can't find this option in `CHANGELOG`, Is there any details about the usage?

**Comment by nicm** [comment]
I have fixed the example config now, thanks!

**Comment by arthurkiller** [comment]
@nicm where is the doc about these options usage?

**Comment by nicm** [comment]
In the manual?
