### ISSUE TITLE
`copy-mode -e` exits prematurely if the output grows before exit

### ISSUE THREAD

**Issue by avih** [tmux/tmux#1718]
Using tmux master and the following config:
```
set-option -g mode-keys vi
set-option -g mouse on
```

Run the following shell script when the prompt is already at the bottom of the pane:
```sh
(for i in $(seq 0 3 100); do
    printf "%s\n%s\n%s\n" "$i some" "$((i+1))   content" "$((i+2))      line"
    sleep 1
done)
```

Then scroll the mouse wheel up once (entering copy-mode -e), wait few seconds, scroll down once.

Expected result: tmux stays in copy mode because it has not reached the bottom of the output (as new lines were added after copy mode was entered).

Actual result: tmux exits copy mode.

The manual is not 100% clear to me, but I think it means "exit copy-mode when scrolling down if it would otherwise exactly overlap the live output or try to go beyond it" - which is indeed how it behaves when no new output was added while in copy mode.

But even if interpreting it as "exit when a line of the live visible screen is scrolled into view", then it still should not exit copy mode if more than one page of output was added - yet it exits also in this case.

**Comment by nicm** [comment]
Things would be better if copy mode just copied the screen rather than trying to use the live one. That would fix #1722 as well.

**Comment by nicm** [comment]
Although no doubt that would make  it a bit slow for all the people with history-limit 1000000000.

**Comment by avih** [comment]
If I understand correctly, right now copy mode is a view to the "live" history+screen? So the fact that it can't stay in copy-mode below where copy-mode was entered is basically just some end-condition which hopefully can be improved?

Between the two options (display from a static local copy vs providing a view to the live history), I think the live option is more user friendly, both because other terminals behave that way, but mainly because there are real world use cases where it matters, such as continuous output (e.g. long compilation) which you want to examine slowly while the output keeps growing.

**Comment by nicm** [comment]
Copy mode takes a snapshot of the visible portion of the screen then updates it from the live screen (called the backing screen) when it redraws (look at window_copy_write_line it calls screen_write_copy). I don't know why it is exiting early, probably it is using a cached value. If you look for scroll_exit you can see where it checks this.

**Comment by avih** [comment]
Well, it's not an exit condition specific to `copy-mode -e`, as it also manifests with normal copy mode, where you can't scroll below the position where copy-mode was entered, even if the live history has new lines below it (it stays in copy-mode, but behaves as if no new output was added).

**Comment by avih** [comment]
One data point I think I have so far is that AFAICT the backing screen size/position (grid->hsize, grid->hscrolled) do not update while in copy mode.

I assume it's so that copy mode does not have to re-calc its offsets, but at the very least it also prevents copy mode from seeing any new lines which should have been added since it was entered.

I think that if it's fixed to also consider such new lines, then the top-right "position" scheme (`[X/Y]`) would need some consideration too. Currently it's relative to where copy-mode was entered.

I think it can be either relative to the bottom of the live screen, at which case it would need to be updated whenever new line is added even if the user didn't scroll while in copy mode, or maybe keep it relative to the "origin" with identical display as now while above the origin, but display it as negative if scrolled below the origin position (where the "overall" part would change to show the count of lines added since copy mode was entered, and it will update whenever new lines are added).

**Comment by nicm** [comment]
I don't mind if the indicator changes when the backing screen changes.

**Comment by avih** [comment]
Here's a summary of how other terminals behave:

mlterm: scrollback fixed to view, scrolls down when history-limit is reached, returns to "live" move when scrolling back to the live area (bottom).

VTE (tested terminator, xfce4-terminal): similar to mlterm (fixed to view, back to normal when scrolling to the live area) but a bit buggy when reaching the history limit - view is updated only on redraws (selection, manual scroll).

urxvt: can be made like mlterm using the following invocation: `urxvt -si -sk -sw -sl 10` (don't scroll on output, scroll on keyboard, don't scroll-with-output (==scrollback fixed to view), and SavedLines (history) = 10 - for testing. A bit buggy when reaching the history limit.

xterm: when disabling scroll on output, it keeps the view at a fixed offset from the bottom of the "live" screen, so in backscroll mode it scrolls N lines whenever N lines of output were added even without reaching the history limit - not very useful. Scroll can be locked to view e.g. by adding `-xrm 'xterm*allowScrollLock: true'` and then pressing the scroll-lock key, but it also affects the normal/"live" mode, so not very useful either.

------

I think it's pretty clear that the main focus on good behavior should be when the history limit is not reached, because probably nothing can qualify as great when it is reached. When the limit is reached, I think the options are:
1. scroll the view unconditionally - like mlterm.
2. scroll the view on redraws - like VTE (not very useful if trying to select anything, but otherwise not bad).
3. keep a copy of the view which supports selection but snap to the history limit whenever scroll is triggered (manually).

1 is probably relatively least surprising, 2 is OK-ish but I think it will always look buggy when trying to select something, 3 could be better than both, but most probably not worth the effort.

**Comment by nicm** [comment]
Thanks for this, that is helpful. TBH though I don't really mind how this works, so if you want to fix it, do it however you like :-). I'll review whatever you come up with.

If not then I'll probably not look at this for a while since I'm working on some new stuff and this problem has been around forever.

**Comment by avih** [comment]
Yeah, I'll try to fix it when/if I can, but I'm not 100% on it, and I don't mind if you fix it whenever you can :p

I'm just looking at the code once in a while and collecting ideas/info.

You can close this issue if you don't want it lingering without immediate action. I don't mind adding comments (if I have anything new to add) also when it's closed.

**Comment by nicm** [comment]
No it can stay open and I'll look at it at some point. Thanks

**Comment by nicm** [comment]
I forgot that copy mode actually turns off reading from the pane, so the base screen will not be modified at all until copy mode exits.

**Comment by nicm** [comment]
I'm going to close this for the moment, it is on the todo list and may revisit later.
