### ISSUE TITLE
Flag silence only after activity

### ISSUE THREAD

**Issue by Bergfried** [tmux/tmux#172]
Currently, if `monitor-silence` is enabled, tmux always flags the window I just left as "silence detected" even if nothing happend in this window. This makes the `monitor-silence` feature hardly useful in my case because I cannot distinguish a window where nothing happend from a window that waits for user input or where a job has just been finished.

I would prefer it to flag windows as "silence detected" only if it currently *is* silent *and* activity has been detected beforehand (i.e. since the last time I visited it). Also, the "silence detected" flag and the "activity detected" flag should be mutually exclusive and set to whatever is currently applicable.

Since other users might be used to the current behavior, I prefer it to be optional.

Using tmux 2.1.

**Comment by ThomasAdam** [comment]
That's a subtle distinction, and I really don't think we need yet more options for this.

**Comment by nicm** [comment]
What you say makes some sense but I think it is better as it is, I like the flags being independent.

**Comment by Bergfried** [comment]
Thank you very much for the quick reply.

@ThomasAdam: Maybe there is a misunderstanding, but what exactly is this "subtle distinction" you are talking about? Note that I am *not* talking about telling apart "waits for user input" and "job finished".

For me, it currently looks like this: I start a job that produces some output while working. I want to easily spot windows like this one so I enable `monitor-activity` so I can see that something happend since the last time I visited this window. However, `monitor-activity` never tells me whether something is *still* going on there or not. Therefore, I also enable `monitor-silence`. However, with this option enabled, *all* windows are being highlighted (and marked with `~`), even idle ones. This is clutter for me as it makes it difficult to spot the windows that need my attention. Also, if a job produces some output now and then but somehow needed just a split second more time than the `monitor-silence` interval, the `~` flag is set but it is never reset on activity. In other words, this window will continue to look just like the ones where the job is actually finished. (The same goes for jobs that need some time directly after invocation until they start producing output.)

I know that having no dependencies between variables is often great, but in this case, it also greatly reduces the usefulness of `monitor-silence`. But this is just my point of view.
