### ISSUE TITLE
Performance with horizontally split panes over slow serial link

### ISSUE THREAD

**Issue by fghzxm** [tmux/tmux#1720]
Version: 2.8

I access my Raspberry Pi 3 B (running Fedora 30) through its [serial port](https://elinux.org/RPi_Serial_Connection), from my PC (running Windows version [`18362.86`](https://devblogs.microsoft.com/commandline/new-experimental-console-features/)).  The program I use on my PC is `picocom` on WSL.  I run tmux on my Pi.

`TERM=`:
* `tmux-256color` inside tmux,
* `xterm-256color` outside tmux, and
* `xterm-256color` outside `picocom` (this has to be identical to that on the Pi since `picocom` doesn't provide terminal emulation)

The problem: With the serial link configured to 115200 baud and no parity bit, tmux exhibits noticeable glitches on `htop` refresh when the `htop` pane is laid out horizontally with other panes, compared to when all panes in a window are stacked vertically (where `htop` refreshes appear almost instant)

My questions:
1. Is this performance cost an unavoidable result of how UNIX terminals work?
1. If 1. is not the case, does there exist a terminal emulator that, when properly configured, I can use instead of `conhost.exe/picocom` with `xterm-256color` to get better performance for my use case?
1. Does tmux _intend_ to be ergonomic on 115200 or fewer baud serial links such as mine (with serious pane splitting)?
1. If 3. is the case and 1. and 2. are not, are developers of tmux interested in addressing my issue?

**Comment by nicm** [comment]
Yes splitting left-right has a high performance cost in most terminals because scrolling requires redrawing (this is not the  case for top-bottom splits because of the scroll region). So scrolling a section of the terminal will potentially generate many hundreds of bytes of data depending on the terminal size (whereas for top-bottom splits with a scroll region it is typically tens of bytes at most).

Since your link is the bottleneck rather than the terminal itself, it's is likely most terminals will see the same problem to some extent. However, xterm (and I believe a few other terminals) supports margins which allow tmux to scroll vertical sections of the terminal without redrawing. xterm is overall a slow terminal but you would probably benefit from using it for this.

**Comment by nicm** [comment]
Of course htop might not actually be scrolling, if it isn't the performance should not really be that much different, although without logs I can't tell what it is doing. Perhaps your terminal has a problem - do you see the same issue in another terminal?

**Comment by nicm** [comment]
There are other things that are more expensive in left-right splits, such as clearing. Are you sure this problem is only visible over the serial link? Do you see it over ssh as well?

**Comment by fghzxm** [comment]
I'm not scrolling `htop`, but when I e. g. launch a program, causing it show up in `htop` among the first few rows (due to high CPU usage), subsequent rows will move downwards.  This situation may be akin to scrolling, though I'm not completely sure how `htop` implements this in terms of terminal characters and sequences.

> Do you see it over ssh as well?

I don't notice glitches running tmux even over a 300+ms RTT SSH link.  If I stare at `htop`, I might sometimes notice a glitch for a very brief moment, but not like over the serial link where, even without horizontally split panes, it takes 0.1s or so to finish "scrolling" a page.  (With horizontally split panes it can, in the worst observed case, take 1s on a 104x57 pane.)  I think the vastly superior bandwidth of the SSH link, as well as the fact that a network packet can transfer hundreds of characters at once makes tmux much more useable across networks than on the serial port.

Clearing the screen takes a long time regardless of whether tmux is in use, as you expected.  The amount of time it takes to clear a 104x57 screen is about 1s though, roughly equal to what it takes to scroll in a horizontal pane configuration.

**Comment by nicm** [comment]
You might try using xterm or seeing if you can find another terminal that supports DECLRMM but if you can't do that there are no real options, left-right split panes will generate a lot more data.

**Comment by fghzxm** [comment]
Do I have to use a specific `$TERM` to get tmux utilize `DECLRMM`?  Since I'm already declaring my terminal as `xterm`-compatible, I guess I can't just drop `xterm` in and get `DECLRMM` automatically working.

**Comment by nicm** [comment]
No it is VT420 feature, if the terminal says it is VT420 compatible tmux
will use it. It is unlikely your terminal is actually fully compatible with
xterm, more likely it supports the bare minimum to make applications work
with TERM=xterm.

You can see if the terminal is suitable by running eg "tmux -vvLtest new"
then look for the line containing "received DA" in the tmux-server-*.log
file.

**Comment by fghzxm** [comment]
Thanks for your advice.

**Comment by nicm** [comment]
Actually you don't need to look at the logs, you can use client_termtype. With tmux attached:
~~~~
$ tmux lsc -F '#{client_tty} #{client_termname} #{client_termtype}'
/dev/ttyp0 xterm-256color VT420
/dev/ttypc xterm-256color Unknown
/dev/ttypd rxvt-unicode-256color Unknown
