### ISSUE TITLE
Unexpected focus event sometimes sent to Vim

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1722]
Sometimes, trying to copy some multi-line text in the output of a Vim command makes the latter disappear.
I could be wrong but I think that's because tmux sends an unexpected focus event to Vim, which makes it redraw the screen and the command-line.

---

Here's a MWE.

Write these 2 lines in `/tmp/tmux.conf`:

    set -s focus-events on
    set -gw mode-keys vi

Write these 4 lines in `/tmp/vimrc`:

    let &t_ti = "\e[?1004h"
    let &t_te = "\e[?1004l"
    exe "set <S-F18>=\e[O"
    exe "set <S-F19>=\e[I"

Start tmux with the previous minimal tmux.conf:

    $ tmux -Ltest -f/tmp/tmux.conf new

Press `C-b ?` to make tmux list all its key bindings, then press `q` to quit the listing.

Start Vim with the previous minimal vimrc:

    $ vim -Nu /tmp/vimrc

On Vim's command-line, run this command whose output contains 2 lines, `foo` and `bar`:

    :echo "foo\nbar"

Finally, press `C-b [` to enter copy-mode, `k` to move one line up (which should position the cursor on the `bar` line), and `V` to select the current line, i.e. `bar`.
As soon as `V` is pressed, Vim redraws the screen, the contents of the command-line is erased, and I can't copy the output of the `:echo` command.

Here's a gif to illustrate.
![gif](https://user-images.githubusercontent.com/8505073/57261269-6fbb5080-7067-11e9-9b3a-65d7b3370130.gif)

---

The previous minimal vimrc is not very useful on its own, but it's a necessary step to [restore the `FocusGained` and `FocusLost` events](https://github.com/lacygoill/vim-term/blob/28d1933d96b5bf6a19f627b08a67af39572ee851/plugin/term.vim#L356-L357) which are missing in Vim (as opposed to gVim or Nvim).

---

The issue seems to be local to a pane, and only begins after `C-b ?` is pressed.
That is, if I don't press `C-b ?`, then I can copy the output of a multi-line Vim Ex command.
And if I have pressed `C-b ?`, then I can temporarily fix the issue by restarting Vim in another pane.

---

 - `$ tmux -V`: tmux 2.9a
 - `$ uname -sp`: Linux x86_64
 - terminal: st
 - `$TERM` outside tmux: st-256color
 - `$TERM` inside tmux: tmux-256color
 - logs from `$ tmux -L test -f /tmp/tmux.conf -vv new`:
   [tmux-client-11865.log](https://github.com/tmux/tmux/files/3150118/tmux-client-11865.log)
   [tmux-out-11867.log](https://github.com/tmux/tmux/files/3150119/tmux-out-11867.log)
   [tmux-server-11867.log](https://github.com/tmux/tmux/files/3150121/tmux-server-11867.log)

According to `$ git bisect`, the offending commit is [`3ec05e9`](https://github.com/tmux/tmux/commit/3ec05e940505f1d0b4e55413f949fdfaceddedde).

**Comment by lacygoill** [comment]
While trying to bisect the issue, I regularly check out a commit on which I can't compile tmux, because of a missing file. I get the following error message:

    sh: 0: Can't open autogen.sh

I tried to copy the `autogen.sh` file from master, but it lead to other missing files.

What's the best way to deal with this issue?
For the moment, I simply skip the commit:

    $ git bisect skip

But this often makes `$ git bisect` give several possible commits:

    There are only 'skip'ped commits left to test.
    The first bad commit could be any of:
    3f6bfbaf2babcc7f08f628a82ff31b0b52014e58
    3ec05e940505f1d0b4e55413f949fdfaceddedde
    We cannot bisect more!

Although in this case, I think it doesn't matter, since the two commits seem to be identical.

**Comment by nicm** [comment]
But when you press C-b ? vim isn't focused anymore, tmux is?

**Comment by nicm** [comment]
Why is vim clearing it's selection when it loses or gains focus? That seems
like a bug in vim.

**Comment by nicm** [comment]
Oh hold on you mean tmux selection in copy mode...

**Comment by nicm** [comment]
The reason this is happening is not because tmux sends an extra focus event - it is correctly sending focus out/in when you enter and exit copy mode. The problem is that when you start a selection it is updating the "copy" screen from the active screen and for some reason vim has cleared everything when it got the focus out event.

This is unfortunate but TBH it does seem like vim is being a bit stupid here. Why does it clear everything when it gets focus out?

**Comment by lacygoill** [comment]
I think you're right. It's probably a bug in Vim, because I can't reproduce in Nvim.
Besides, even without tmux copy mode, Vim redraws the screen and clears the output of a multi-line Ex command when I focus another tmux pane. Nvim doesn't do that.

I thought that it was a bug in tmux because Vim doesn't clear the screen as long as I haven't pressed `C-b ?` in the current pane.

I will try to submit a bug report on Vim's issue tracker, today or tomorrow, but I don't know whether it will be considered as a bug, because I think that my configuration is a hack. Vim in st doesn't support the `FocusGained` and `FocusLost` events:

> FocusGained			When Vim got input focus.  Only for the GUI
> version and a few console versions where this can be detected.
>
> FocusLost			When Vim lost input focus.  Only for the GUI
> version and  a few console  versions where this  can be detected.   May also
> happen when a dialog pops up.

I rely on the tmux option `focus-events` to restore them, by mapping the sequences sent by the terminal – `CSI O` and `CSI I` – to Vim function calls.

If they do consider it as a bug, and fix it, I'll update this issue and close it.
Thank you very much for your answer.

**Comment by lacygoill** [comment]
For reference, I've just reported the issue on Vim's issue tracker.

https://github.com/vim/vim/issues/4359
