### ISSUE TITLE
Unexpected motion of the end of the selection in copy mode

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1723]
Sometimes, in copy mode, the end of the selection jumps unexpectedly to the start of the line.

---

Here's a MWE.

Write this line in `/tmp/tmux.conf`:

    set -gw mode-keys vi

Start tmux with this command:

    $ tmux -Ltest -f/tmp/tmux.conf new

`$ cat` this [CHANGES file](https://github.com/tmux/tmux/blob/master/CHANGES):

    $ cat CHANGES

Press `C-b [` to enter copy mode.
Press `kk` to position the cursor on the last line of the file which contains the text:

    customisation.

Press `V` to select the line, then press `g` to move the start of the selection at the very top of the scrollback buffer.
Finally press `o` to make the cursor switch its position with the end of the selection.
The cursor is positioned on the **first** character of the last line of the file.
I would expect the cursor to be positioned on the **last** character of the last line of the file, because that's where it was right before pressing `g`.

Here's a gif to illustrate.
![gif](https://user-images.githubusercontent.com/8505073/57265379-bfa21380-7077-11e9-8409-6bc048498abf.gif)

For someone used to Vim, this is unexpected. In Vim, if I visually select the last line of a file, then press `gg` to move the start of the selection to the top, the whole file is selected as a result.
In tmux, if I visually select the last line of a file, then press `g`, the whole file is not selected; the last line is missing (except its first character).

This is also inconsistent with how tmux positions the end of the selection after other motions which scroll back.
For example, in copy mode, if I select the last line of a file by pressing `V`, then if I press `k` a few times to get a few lines above, at no point does tmux make the end of the selection move from its original position, i.e. the last character of the last line of the file.

Because of this unexpected motion of the end of the selection, I often miss some text when copying some lines in the output of a shell command.

---

 - `$ tmux -V`: tmux 2.9a
 - `$ uname -sp`: Linux x86_64
 - terminal: st
 - `$TERM` outside tmux: st-256color
 - `$TERM` inside tmux: tmux-256color
 - logs from `$ tmux -L test -f /tmp/tmux.conf -vv new`:
[tmux-client-17237.log](https://github.com/tmux/tmux/files/3150393/tmux-client-17237.log)
[tmux-out-17239.log](https://github.com/tmux/tmux/files/3150394/tmux-out-17239.log)
[tmux-server-17239.log](https://github.com/tmux/tmux/files/3150395/tmux-server-17239.log)

I tried to `$ git bisect` to see whether it was a regression, and I found that indeed tmux didn't behave like that in the past.
However, I can't tell you the exact commit from which the regression was introduced, because I can't compile tmux on some commits (some files are missing, the first of which is `autogen.sh`).

All I can tell is that it's one of those 4 commits:

[`0d1be2e`](https://github.com/tmux/tmux/commit/0d1be2e32838cfb4f4b528fc3f94ef850b47eda7)
[`7e6c2cb`](https://github.com/tmux/tmux/commit/7e6c2cb23868fbfec11adacdc5da7e670a9b8bdb)
[`84319aa`](https://github.com/tmux/tmux/commit/84319aa8f013238ccc1bbd6ea44b9e6be7c58db2)
[`a02d95a`](https://github.com/tmux/tmux/commit/a02d95a313e0a289a46c2b77eb59d6c6d1488012)

And this is what `$ git bisect` prints at the end:

    There are only 'skip'ped commits left to test.
    The first bad commit could be any of:
    0d1be2e32838cfb4f4b528fc3f94ef850b47eda7
    7e6c2cb23868fbfec11adacdc5da7e670a9b8bdb
    84319aa8f013238ccc1bbd6ea44b9e6be7c58db2
    a02d95a313e0a289a46c2b77eb59d6c6d1488012
    We cannot bisect more!

If you could tell me how to compile tmux on a commit where `autogen.sh` is missing, I could try to further reduce this number of commits.

**Comment by nicm** [comment]
The selection is anchored at the start of the line not the end, if you do other-end before you move to the start of the buffer it will work as you expected.

**Comment by nicm** [comment]
We do a dance for cursor-up and cursor-down to keep the selection right, we should do the same for history-top and history-bottom. Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3152494/x.diff.txt)

**Comment by lacygoill** [comment]
> The selection is anchored at the start of the line not the end,

Ah ok I didn't know that, I thought it was anchored at the end, because that's where the cursor is drawn.

> if you do other-end before you move to the start of the buffer it will work as you expected.

You're right, in this case it works as expected.

> We do a dance for cursor-up and cursor-down to keep the selection right, we should do the same for history-top and history-bottom. Try this please: x.diff.txt

I've just tried the patch, and it seems to fix the issue. The behavior of the selection is much more consistent now. Thank you very much.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
