### ISSUE TITLE
Window Status not centered{maybe}

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#1725]
Hi, 

Below is my config that I am using
tmux 2.9a

```
# this is to show if keys are binded in nested tmux
nested_keys_off="#[fg=colour009,bold]#([ $(tmux show-option -qv key-table) = 'off' ] && echo 'OFF')#[default]"
set -g status-right "#$nested_keys_off"
# How often status bar updates, default is 15 seconds.
set -g status-interval 1

# default statusbar colors
set -g status-bg default
set -g status-fg default
set -g window-status-activity-style bg=default
# set -g status-left ""

set-window-option -g automatic-rename on
set -g status-left-length 19
set-option -g status-left " #[fg=colour241]%b-%d %a | #[fg=colour241]%H:%M"

# This will display current command in statusbar if there is no current command it will display current dir you are in {
H="/Users/lpuljic" # this is needed to show pane_current_path  but to ignore home dir.
set-option -g status-justify centre
set -wg automatic-rename-format "#{s/zsh//:pane_current_command}"
setw -g window-status-format "#[fg=colour239][#I]#[fg=colour239]#{?window_name,#{window_name} ,#{?#{==:#{pane_current_path},$H},,#{b:pane_current_path}}}"
setw -g window-status-current-format "#[fg=colour106,bold]#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H},●,#{?#{m:$H/*,#{pane_current_path}},[#[fg=colour167]●#[fg=colour106]]-,}#{b:pane_current_path}}}#[fg=colour009,bold]#{?window_zoomed_flag, ZOOMED,}"
#}

```

However status-justify centre, to it doesn't look like its centered, please see the image below.

<img width="1680" alt="Screen Shot 2019-05-07 at 11 36 13 am" src="https://user-images.githubusercontent.com/38928237/57265880-f0586c00-70bc-11e9-8590-bb32039107e4.png">

So what I think it's happening is that center is calculated from red lines in the image above and not from the blue line ?  is that correct.

**Comment by nicm** [comment]
It is the centre of the space between status-left and status-right not the centre of the terminal.

**Comment by lanox** [comment]
hrm, not sure I quiet understand what you mean. However to my eye green dot, is not in the center, due to status-left having things showing ?

**Comment by nicm** [comment]
Yes it is in the middle of the space between status-left and status-right, if the terminal is 100 columns and status-left and 10 and status-right is 20 then the centre is at 10+(100-10-20)/2 = 45 not at 50.

**Comment by lanox** [comment]
Thanks it makes perfect sense what you said, however not having anything on the right side to center off the left makes it look like its not in the center.

**Comment by lanox** [comment]
It’s all good, I have made status-left width be same as right so it does the trick.

**Comment by nicm** [comment]
Yeah I know but if it was the real centre then it would look odd with both
left and right set. If your left is always around the same width you can
probably add spaces to the centre to get it to look like it's in the middle.

**Comment by lanox** [comment]
No problems I understand what you are saying. 

Thanks for all the work as usual.
