### ISSUE TITLE
Apparently 62.5 MB in memory leaks after a month's use

### ISSUE THREAD

**Issue by metayan** [tmux/tmux#1726]
After running tmux for almost a month:
```
Process:         tmux [4128]
Path:            ???
Load Address:    0x105cf7000
Identifier:      tmux
Version:         ???
Code Type:       X86-64
Parent Process:  launchd [1]
Date/Time:       2019-05-07 02:32:00.167 +0200
Launch Time:     2019-04-07 23:43:46.629 +0200OS
Version:         Mac OS X 10.13.6 (17G6030)
Report Version:  7
Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaksAnalysis
Tool Version:    Xcode 10.1 (10B61)

Physical footprint:         484.6M
Physical footprint (peak):  484.6M
----

leaks Report Version: 4.0
Process 4128: 556043 nodes malloced for 425485 KB
Process 4128: 82958 leaks for 65557008 total leaked bytes.
```

Leak distribution:
```
#     size
26888 1536
21996  352
 9271  304
 9188  688
 7260  544
 4216  608
 2962  272
  423   16
  285   32
  225   80
  206   48
   17  112
    9   96
    4 2048
    2  224
    2  144
    1  256
    1  240
    1  192
    1  128
```
Complete leak report file is available, as well as a `.graphmem` file.
The process is still running in case some more info is helpful, but I might reboot in a day or two.

tmux server version 2.8 (`tmux display-message -p "#{version}"`)
tmux 2.9a installed 2019-05-02 with Homebrew.
On macOS High Sierra (10.13.6), using `kitty` as terminal.

**Comment by nicm** [comment]
Please see if this still happens with 2.9a and if so please include your config and any additional information you have because this issue as it is doesn't really tell me anything that would help. Thanks.
