### ISSUE TITLE
Defining Macros

### ISSUE THREAD

**Issue by Mouradif** [tmux/tmux#1730]
(This issue is NOT related to issue #983 )

It would be nice to define macros like in vim and attach them to keyboard shortcuts. For example, I often want to clear the screen and the scroll log so I very very often type : 

c, l, e, a, r, <Enter>, Ctrl+B, :, c, l, e, a, r, -, h, i, s, t, o, r, y

so that's 21 keystrokes I would be super glad to attach to the custom command Ctrl+B, Ctrl+L

then of course if we had this feature, I think we can all very easily find lots of uses

**Comment by nicm** [comment]
send-keys...?

**Comment by nicm** [comment]
If you shell supports C-l it is probably easier, something like:
~~~~
bind C send C-l \; clear-history
