### ISSUE TITLE
lost server with main-horizontal when pane scrolled / size too small

### ISSUE THREAD

**Issue by tony** [tmux/tmux#1736]
# description

Tmux crashes with a split and main-horizontal layout

# Information

Please provide the following information:

* tmux version (`tmux -V`).  tmux 2.9a and 50d1d04  
* Platform (`uname -sp`). Darwin i386 / macOS Mojave 10.14.4 (18E226)
* $TERM inside and outside of tmux (`echo $TERM`).

Outside:

```
echo $TERM
xterm-256color
```

Inside: `screen`

More config info:

Cleared out `.tmux.conf` and `.zshrc` to be blank

Using Iterm2 (3.2.9) with xterm-256color

zsh --version
zsh 5.3 (x86_64-apple-darwin18.0)

### To recreate

- `tmux -vv new`
- `tmux split-w`  (required, must have at least one split window)
- `tmux select-l main-h`
- Then repeat ctrl-c to keep printing new prompts until the end of the pane (

   <img width="676" alt="Screen Shot 2019-05-11 at 2 33 35 PM" src="https://user-images.githubusercontent.com/26336/57574195-fc646680-73f9-11e9-9bb3-b0b8445dfe39.png">

   Above: The last line possible. The next time ctrl-c is pressed, the server is lost
- The final ctrl-c will lose server
   
    <img width="676" alt="Screen Shot 2019-05-11 at 2 34 28 PM" src="https://user-images.githubusercontent.com/26336/57574193-f3739500-73f9-11e9-8ae6-0219fb6c8b83.png">

### 2.9a:

[tmux-client-40776.log](https://github.com/tmux/tmux/files/3169411/tmux-client-40776.log)
[tmux-out-40778.log](https://github.com/tmux/tmux/files/3169412/tmux-out-40778.log)
[tmux-server-40778.log](https://github.com/tmux/tmux/files/3169413/tmux-server-40778.log)

### 50d1d04:

This one had a smaller terminal size, and crashed immediately after `selectl main-h` (no need for `ctrl-c`

![image](https://user-images.githubusercontent.com/26336/57574249-1eaab400-73fb-11e9-9cd5-35519224f4d5.png)

Press 'enter' on `tmux select-l main-h` and it'll end

![image](https://user-images.githubusercontent.com/26336/57574255-3e41dc80-73fb-11e9-9d93-e271f3e17684.png)

[tmux-client-46355.log](https://github.com/tmux/tmux/files/3169417/tmux-client-46355.log)
[tmux-out-46357.log](https://github.com/tmux/tmux/files/3169418/tmux-out-46357.log)
[tmux-server-46357.log](https://github.com/tmux/tmux/files/3169419/tmux-server-46357.log)

Second one, with a taller terminal, required pressing `ctrl-c`:

[tmux-client-46438.log](https://github.com/tmux/tmux/files/3169423/tmux-client-46438.log)
[tmux-out-46440.log](https://github.com/tmux/tmux/files/3169424/tmux-out-46440.log)
[tmux-server-46440.log](https://github.com/tmux/tmux/files/3169425/tmux-server-46440.log)

**Comment by NicolasCARPi** [comment]
I can confirm this bug on 2.9a on Arch Linux with rxvt-unicode ($TERM == 'rxvt').

**Comment by ThomasAdam** [comment]
Looks like we're overflowing here:

```
*ry = ctx->sy - *y;
```
```
(gdb) p ctx->sy 
$40 = 23
(gdb) p *y
$41 = 24
(gdb) p ctx->sy - *y
$42 = 4294967295
(gdb) 
```

Looks like the maths is off slightly.  Patch to follow...

**Comment by ThomasAdam** [comment]
Does the following help at all?

```
diff --git a/tty.c b/tty.c
index cc528e8e..40f1ea64 100644
--- a/tty.c
+++ b/tty.c
@@ -1061,7 +1061,7 @@ tty_clamp_area(struct tty *tty, const struct tty_ctx *ctx, u_int px, u_int py,
        } else {
                /* Right not visible. */
                *j = 0;
-               *y = (ctx->yoff + py) - ctx->oy;
+               *y = (ctx->yoff + py - 1) - ctx->oy;
                *ry = ctx->sy - *y;
        }
        if (*ry > ny)
```

I'm not saying this should be the final fix.

**Comment by NicolasCARPi** [comment]
@ThomasAdam I'm still able to reproduce this bug with your patch applied on the latest master.

**Comment by tony** [comment]
![image](https://user-images.githubusercontent.com/26336/57588326-32781800-74d8-11e9-8995-f580e830cd65.png)

@ThomasAdam 

It prevents the server from closing, at least.

699d9d2facd377c72c962e1f029f654530e8bba8 and

```diff
diff --git a/tty.c b/tty.c
index cc528e8e..40f1ea64 100644
--- a/tty.c
+++ b/tty.c
@@ -1061,7 +1061,7 @@ tty_clamp_area(struct tty *tty, const struct tty_ctx *ctx, u_int px, u_int py,
        } else {
                /* Right not visible. */
                *j = 0;
-           *y = (ctx->yoff + py) - ctx->oy;
+         *y = (ctx->yoff + py - 1) - ctx->oy;
                *ry = ctx->sy - *y;
        }
        if (*ry > ny)
```

[tmux-client-53098.log](https://github.com/tmux/tmux/files/3170608/tmux-client-53098.log)
[tmux-out-53100.log](https://github.com/tmux/tmux/files/3170609/tmux-out-53100.log)
[tmux-server-53100.log](https://github.com/tmux/tmux/files/3170610/tmux-server-53100.log)

**Comment by tony** [comment]
@NicolasCARPi Did the server close though? I think the patch only did enough to fix that. It'll still bleed into the status line.

Are you sure you did it with a new server?

**Comment by ThomasAdam** [comment]
Hmm.  Weird, since I can't trigger the original bug in the way you described, @tony -- rather, I just have to split the window and issue a new layout and it crashes.  I'll keep looking -- I hope this isn't two separate problems through.

**Comment by nicm** [comment]
It is likely the problem will be with the resulting layout from
main-horizontal. Check the sizes are OK and the parent cells,
layout_set_main_v should log it all when it finishes.

**Comment by tony** [comment]
>  rather, I just have to split the window and issue a new layout and it crashes. 

Try doing it with a terminal with bigger dimensions.

Yeah, I think this describes my second attempt at reproducing it (when I made my iterm2 window smaller): I didn't need to do ctrl-c at all. It crashed immediately after `tmux selectl main-h`

> I hope this isn't two separate problems through.

Maybe it's the same thing? I only had to do `ctrl-c` if the terminal was larger (giving the pane more space).

**Comment by nicm** [comment]
It doesn't look right that the two left panes are only 36 high but the right are 37. Not sure about the x because it may be fixed after it's logged.

1557603166.044512 layout_set_main_h: 0x7fbf794231e0 type TOPBOTTOM [parent 0x0] wp=0x0 [0,0 77x37]
1557603166.044522 layout_set_main_h:  0x7fbf79421aa0 type WINDOWPANE [parent 0x7fbf794231e0] wp=0x7fbf79421af0 [0,0 77x18]
1557603166.044530 layout_set_main_h:  0x7fbf79423230 type WINDOWPANE [parent 0x7fbf794231e0] wp=0x7fbf79423280 [0,19 77x18]
1557603166.044544 layout_set_main_h: 0x7fbf79701ac0 type TOPBOTTOM [parent 0x0] wp=0x0 [0,0 77x37]
1557603166.044553 layout_set_main_h:  0x7fbf79701fc0 type WINDOWPANE [parent 0x7fbf79701ac0] wp=0x7fbf79421af0 [0,0 77x24]
1557603166.044561 layout_set_main_h:  0x7fbf79702010 type WINDOWPANE [parent 0x7fbf79701ac0] wp=0x7fbf79423280 [0,25 77x13]

**Comment by NicolasCARPi** [comment]
> Did the server close though? Are you sure you did it with a new server?

Yes you're right, it wasn't a new server, the patch seems to prevent server crash, but the line is stil bad :)

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3174692/x.diff.txt)

**Comment by NicolasCARPi** [comment]
@nicm That seems to fix it! :+1:

**Comment by nicm** [comment]
Applied now, thanks!

**Comment by tony** [comment]
@nicm @ThomasAdam This works very well (as of 9228fead48b96598d4e0223e5fa0d1516fb96b73)
