### ISSUE TITLE
Clear doesn't work on console/terminal only installation

### ISSUE THREAD

**Issue by mrjayviper** [tmux/tmux#1737]
I'm running tmux version 2.6 on an Ubuntu server 18.04 installation.

When I ran clear command, my screen/console doesn't clear. The cursor just goes to the top.

Any advice? Thanks

**Comment by nicm** [comment]
Probably this is the same as https://github.com/tmux/tmux/issues/1419.

**Comment by mrjayviper** [comment]
I saw that post before I created this post and another one and both posts mentioned they were using konsole. I thought that could be related to the terminal emulator. which is different from my situation where I am using the terminal itself. no emulator.

I will try that. Thanks

**Comment by nicm** [comment]
The Linux console is still a terminal emulator.
