### ISSUE TITLE
pane-border-status Replacement

### ISSUE THREAD

**Issue by MichelfrancisBustillos** [tmux/tmux#1738]
# Issue description

I am trying to build a script that opens 3 panes, 1 for each machine that I work on daily (local + 2 remotes via Mosh/SSH) and am looking for a way to identify each pane (to keep from accidentally running a command in prod instead of dev, etc.). I came across `select-pane -t <paneNumber> -T <paneName>`, which would do exactly what I am looking for, however, it seems you must `set pane-border-status top` first. Whenever I try to do this, I receive an `unknown option: pane-border-status` error. Is there a way around this? Is there another way to easily differentiate panes from each other (besides changing all text or background color)? 

Alternative: Is there a way to change the color of a prompt per-pane instead off all text?  

* tmux version 2.9 (latest source, compiled from GitHub)
* Platform: Linux x86_64 (Ubuntu 16.04.6 on WSL)
* $TERM inside tmux: `screen` & outside: `xterm-256color`

**Comment by codisms** [comment]
What happens if you run the following command in the pane for your local machine?
```
tmux set pane-border-status top
```

**Comment by MichelfrancisBustillos** [comment]
That for some reason suddenly works. Not sure why it did not before. However, when I try to use the -T option in my script, the lines beneath it seem to be executing out of order.

The `send-keys` command under the pane being labeled `SanctuaryServer` executes in the pane labeled `KolasisServer`.

```
#!/bin/sh
tmux new -d -s Work
tmux rename-window Main
tmux set pane-border-status top
tmux split-window -h
tmux split-window -h
tmux select-layout even-horizontal
tmux select-pane -t 1 -T "MichelsSpectre"
tmux select-pane -t 2 -T "SanctuaryServer"
tmux send-keys 'mosh michel@192.168.1.201 -- tmux new -A -s Main'
tmux send-keys ENTER
tmux select-pane -t 3 -T "KolasisServer"
tmux send-keys 'mosh michel@192.168.1.156 -- tmux new -A -s Main'
tmux send-keys ENTER
tmux attach -t Work
```

**Comment by nicm** [comment]
Why don't you use -t on send-keys as well?
