### ISSUE TITLE
Odd DEC characters in vttest under tmux

### ISSUE THREAD

**Issue by rbanffy** [tmux/tmux#1739]
# Issue description

Running vttest under tmux results in some differences in characters being displayed from running vttest directly under a terminal window. Under tmux, the range "◆▒␉␌␍␊°±␤␋" renders as "◆▒bcde°±▒☃", as shown in the images below.

![Screenshot from 2019-05-14 18-47-07](https://user-images.githubusercontent.com/184714/57731146-f1c3fe80-7691-11e9-9b41-405aa7f1eb0a.png)

![Screenshot from 2019-05-14 18-46-35](https://user-images.githubusercontent.com/184714/57731161-f7b9df80-7691-11e9-8c73-24ed16d60057.png)

The issue was identified with the stock Ubuntu version (2.8-3) and a freshly built version from this tree. The same happened in xterm and in Gnome terminal. Font is https://github.com/rbanffy/3270font

![Screenshot from 2019-05-14 18-48-28](https://user-images.githubusercontent.com/184714/57731221-18823500-7692-11e9-811f-021e0c80c986.png)

# Information

* tmux version (`tmux -V`). 
  - tmux next-3.0

* Platform (`uname -sp`).
  - Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).
  - xterm-256color, screen respectively

* Logs from tmux (`tmux -vv new`).
  - [tmux-server-29121.log](https://github.com/tmux/tmux/files/3179829/tmux-server-29121.log)
  - [tmux-out-29121.log](https://github.com/tmux/tmux/files/3179830/tmux-out-29121.log)
  - [tmux-client-29119.log](https://github.com/tmux/tmux/files/3179831/tmux-client-29119.log)

**Comment by nicm** [comment]
tmux does not support bcde in ACS.

The last two look like problems with the UTF-8 characters in your font. Are
they correct if you set U8=0 with terminal-overrides?

**Comment by nicm** [comment]
Actually maybe we just have odd UTF-8 characters for hi, we are currently using:

	{ 'h', "\342\226\222" },	/* board of squares */
	{ 'i', "\342\230\203" },	/* lantern symbol */

Which are probably not the best choices.

**Comment by nicm** [comment]
What do these look like outside tmux with the standard xterm font?

**Comment by rbanffy** [comment]
This is default size xterm (330) as installed by Ubuntu:

![Screenshot from 2019-05-15 15-19-46](https://user-images.githubusercontent.com/184714/57782862-f1c10e80-7724-11e9-979a-def21d1cd545.png)

and with the latest tmux:

![Screenshot from 2019-05-15 15-21-39](https://user-images.githubusercontent.com/184714/57782964-2af97e80-7725-11e9-9f38-a9b0a5d67b8c.png)

The odd thing is a snowman (☃), not a lantern. This is what got me suspicious because I'm pretty sure DEC terminals never had snowmen in their fonts.

**Comment by nicm** [comment]
This is for the lantern symbol and I think it came from rxvt-unicode or
somewhere. Do you want to suggest a better UTF-8 symbol? Or we could just
remove it entirely.

**Comment by rbanffy** [comment]
The ones that appear when not under tmux are, in order, ␉, ␌, ␍, ␊, °, ±, ␤, and ␋. These all can be represented in UTF-8, but I'm not sure I got the notation used in tty-acs.c.

**Comment by nicm** [comment]
I think those are useless though so it'd be better to not have them.

**Comment by nicm** [comment]
I suppose they'll do, it's just octal UTF-8.

**Comment by rbanffy** [comment]
I used those symbols to more easily read dumps (in the late 80's) because they fit in a single character cell. I'd go for having them if it doesn't impact the complexity of the code significantly, if, for no other reason than consistency with the terminal's behavior when not under tmux. It's odd to see a snowman when you expect a ␋.

**Comment by nicm** [comment]
OK well if you dig out what the Unicode codepoints are then I'll change
them.

**Comment by rbanffy** [comment]
Thank you. That sounds awesome.

This is what xterm shows on all my machines (Ubuntu, Fedora and macOS):

\342\227\206 ◆
\342\226\222 ▒
\342\220\211 ␉
\342\220\214 ␌
\342\220\215 ␍
\342\220\212 ␊
\302\260 °
\302\261 ±
\342\220\244 ␤
\342\220\213 ␋

**Comment by nicm** [comment]
Try this please:
~~~~
Index: tty-acs.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/tty-acs.c,v
retrieving revision 1.6
diff -u -p -r1.6 tty-acs.c
--- tty-acs.c	15 May 2017 16:44:04 -0000	1.6
+++ tty-acs.c	15 May 2019 20:36:38 -0000
@@ -37,10 +37,14 @@ static const struct tty_acs_entry tty_ac
 	{ '0', "\342\226\256" },	/* solid square block */
 	{ '`', "\342\227\206" },	/* diamond */
 	{ 'a', "\342\226\222" },	/* checker board (stipple) */
+	{ 'b', "\342\220\211" },
+	{ 'c', "\342\220\214" },
+	{ 'd', "\342\220\215" },
+	{ 'e', "\342\220\212" },
 	{ 'f', "\302\260" },		/* degree symbol */
 	{ 'g', "\302\261" },		/* plus/minus */
-	{ 'h', "\342\226\222" },	/* board of squares */
-	{ 'i', "\342\230\203" },	/* lantern symbol */
+	{ 'h', "\342\220\244" },
+	{ 'i', "\342\220\213" },
 	{ 'j', "\342\224\230" },	/* lower right corner */
 	{ 'k', "\342\224\220" },	/* upper right corner */
 	{ 'l', "\342\224\214" },	/* upper left corner */

**Comment by rbanffy** [comment]
Thanks, @nicm. Your fix works as expected.
![Screenshot from 2019-05-16 21-10-07](https://user-images.githubusercontent.com/184714/57884035-accdd280-781f-11e9-8503-03f8ba2d53b4.png)
![Screenshot from 2019-05-16 21-11-15](https://user-images.githubusercontent.com/184714/57884036-ad666900-781f-11e9-815c-0b20dd2d530d.png)
![Screenshot from 2019-05-16 21-11-44](https://user-images.githubusercontent.com/184714/57884037-ad666900-781f-11e9-9619-be2e9f750811.png)
![Screenshot from 2019-05-16 21-13-14](https://user-images.githubusercontent.com/184714/57884039-ad666900-781f-11e9-84a5-037b09ac8f7b.png)

**Comment by nicm** [comment]
Applied now, thanks!
