### ISSUE TITLE
Mouse-drag copy not working in some copy-modes in next-3.0

### ISSUE THREAD

**Issue by townba** [tmux/tmux#1740]
# Issue description

In `tmux next-3.0` (built from latest source moments ago), mouse-drag copy does not work in copy mode for commands like `list-clients` and `list-keys`, though it does work for copy mode for scroll (history). It works correctly in 2.8.

To reproduce:
* Start a clean tmux: `TERM=xterm path/to/tmux -f /dev/null`
* Enable the mouse: press ^B : and run command `set -g mouse on`
* Enter copy mode for a command like `list-keys`: press ^B ?
* Try to copy text by clicking and dragging across text.

What should happen:
* Text should be highlighted and copied when the mouse button is released.

What actually happens:
* Nothing until the mouse button is released, then the mode is cancelled. No text is actually copied.

# Information

Please provide the following information:

* tmux version (`tmux -V`: `tmux next-3.0`).
* Platform (`uname -sp`: `Linux unknown`).
* $TERM inside and outside of tmux (`echo $TERM`: `xterm` outside, `screen` inside).
* Logs from tmux (`tmux -vv new`).
```
1557947259.898178 client started (39051): version next-3.0, socket /tmp/tmux-142132/default, protocol 8
1557947259.898201 on Linux 4.19.28-2rodete1-amd64 #1 SMP Debian 4.19.28-2rodete1 (2019-03-18 > 2018); libevent 2.1.8-stable (poll)
1557947259.898221 socket is /tmp/tmux-142132/default
1557947259.898233 trying connect
1557947259.898284 add peer 0x55eab85862a0: 6 ((nil))
1557947259.898381 sending message 100 to peer 0x55eab85862a0 (4 bytes)
1557947259.898389 sending message 101 to peer 0x55eab85862a0 (6 bytes)
1557947259.898393 sending message 102 to peer 0x55eab85862a0 (11 bytes)
1557947259.898397 sending message 108 to peer 0x55eab85862a0 (44 bytes)
1557947259.898403 sending message 104 to peer 0x55eab85862a0 (0 bytes)
1557947259.898408 sending message 107 to peer 0x55eab85862a0 (4 bytes)
1557947259.898412 sending message 105 to peer 0x55eab85862a0 (11 bytes)
1557947259.898416 sending message 105 to peer 0x55eab85862a0 (22 bytes)
1557947259.898420 sending message 105 to peer 0x55eab85862a0 (2218 bytes)
1557947259.898429 sending message 105 to peer 0x55eab85862a0 (34 bytes)
...
1557947259.898688 sending message 105 to peer 0x55eab85862a0 (19 bytes)
1557947259.898692 sending message 105 to peer 0x55eab85862a0 (9 bytes)
1557947259.898695 sending message 106 to peer 0x55eab85862a0 (0 bytes)
1557947259.898699 cmd_pack_argv: argv[0]=new
1557947259.898703 sending message 200 to peer 0x55eab85862a0 (8 bytes)
1557947259.898706 client loop enter
1557947259.899668 peer 0x55eab85862a0 message 207
1557947259.899680 sending message 208 to peer 0x55eab85862a0 (0 bytes)
1557947275.793424 peer 0x55eab85862a0 message 203
1557947275.793442 sending message 205 to peer 0x55eab85862a0 (0 bytes)
1557947275.793680 peer 0x55eab85862a0 message 204
1557947275.793689 client loop exit
```

**Comment by nicm** [comment]
Yes... weird, will have a look.

**Comment by nicm** [comment]
This should be fixed now. Thanks!

**Comment by townba** [comment]
Verified fixed in latest source.
