### ISSUE TITLE
coredump with old window-status-current-bg tmux.conf

### ISSUE THREAD

**Issue by ilf** [tmux/tmux#1744]
### Issue description

tmux 2.9 and 2.9a coredump when started with `window-status-current-bg` and `window-status-current-fg` in tmux config:

```
% sudo coredumpctl info 811
PID: 811 (tmux: server)
UID: 1234 (user)
GID: 1234 (user)
Signal: 11 (SEGV)
Timestamp: Tue 2019-04-30 10:30:36 CEST (1h 15min ago)
Command Line: tmux new-session -d -s name
Executable: /usr/bin/tmux
Control Group: /user.slice/user-1234.slice/session-1.scope
Unit: session-1.scope
Slice: user-1234.slice
Session: 1
Owner UID: 1234 (user)
Storage: /var/lib/systemd/coredump/core.tmux:\x20server.1234.54d03a393e694c7e971f9e4622eea7f5.811.1556613036000000.lz4
Message: Process 811 (tmux: server) of user 1234 dumped core.

Stack trace of thread 811:
#0 0x000055cff01ecb21 n/a (tmux)
#1 0x000055cff01d429b n/a (tmux)
#2 0x000055cff01d4587 n/a (tmux)
#3 0x000055cff01d12a9 n/a (tmux)
#4 0x000055cff0202776 n/a (tmux)
#5 0x000055cff01f7182 n/a (tmux)
#6 0x000055cff0202e74 n/a (tmux)
#7 0x000055cff01c8098 n/a (tmux)
#8 0x000055cff01c44e5 n/a (tmux)
#9 0x00007f976003ace3 __libc_start_main (libc.so.6)
#10 0x000055cff01c468e n/a (tmux)
```

See https://bugs.archlinux.org/task/62510

### Required information

* tmux version: tmux 2.9a
* Platform: Linux 5.1.2
* $TERM inside and outside of tmux: screen, st-256color

**Comment by nicm** [comment]
This stacktrace is no use, please run tmux in gdb like this:
~~~~
$ gdb --args tmux ...
(gdb) set follow-fork-mode child
(gdb) run
...
(gdb) bt full

**Comment by ilf** [comment]
Thanks for your feedback. I use tmux in production, so it's not easy for me to kill the tmux server in order to debug it.

AFAICT, anyone should be able to reproduce this crash with these two lines in tmux.conf:

```
set-window-option -g window-status-current-bg white
set-window-option -g window-status-current-fg black
```

**Comment by nicm** [comment]
I can't reproduce with your config.

You can start a new server with -L to test.

**Comment by hacker1db** [comment]
Hi know this in alfa version but I get this error everytime I go to start tmux with just tmux noramlly.. 
https://github.com/hacker1db/Dotfiles Config is located here:  
the only differece between my version is tmux2.9a I have another Mac with the previous version on it and I get this errror and my coloscheme does not get respected i.e I end up with green pane split lines which is the default. 
Thanks! let me know how I can help. 
/Users/username/.dotfiles/tmux/theme.sh:35: invalid option: window-status-fg
/Users/username/.dotfiles/tmux/theme.sh:36: invalid option: window-status-bg
/Users/username/.dotfiles/tmux/theme.sh:40: invalid option: window-status-current-fg
/Users/username/.dotfiles/tmux/theme.sh:41: invalid option: window-status-current-bg
/Users/username/.dotfiles/tmux/theme.sh:45: invalid option: pane-border-fg
/Users/username/.dotfiles/tmux/theme.sh:46: invalid option: pane-active-border-fg
/Users/username/.dotfiles/tmux/theme.sh:49: invalid option: message-bg
/Users/username/.dotfiles/tmux/theme.sh:50: invalid option: message-fg

**Comment by pabrahamsson** [comment]
@hacker1db I had the same issue, resolved it by reading through [this closed issue](https://github.com/tmux/tmux/issues/1689)
