### ISSUE TITLE
How do I use variables in a ternary statement in configuration file?

### ISSUE THREAD

**Issue by 3N4N** [tmux/tmux#1746]
### Issue description

I have following variable in my `~/.tmux.conf`
```
color_mild_grey="#5c6370"
```

And I use that variable in the following manner:
```
set -g window-status-format "#{?window_last_flag,#[bg=colour7]#[fg=colour0],#[bg=$color_mild_grey]#[fg=colour15]} #I:#W "

set -g status-left '#[bg=colour5]#[fg=colour0] #S #[bg=default]#[bg=colour0] #{?client_prefix,#[bg=colour1]#[fg=colour0],#[bg=default]#[fg=$color_mild_grey]} PREFIX #{?client_prefix,#[bg=colour0] ,}'
```
In the first case, the variable works properly. But in the second case, the one with the ternary instruction of checking for `client_prefix`, doesn't work. It works if I directly put `#[fg=5c6370]` instead of `#[fg=$color_mild_grey]`.

Since, the variable replacement works in the first case, I'm thinking it's a problem with the ternary operation. Maybe the ternary operation doesn't do variable replacement? I have no clue. Any help would be appreciated.

### Required information

Please provide the following information:

* tmux version (`tmux -V`)
```bash
$ tmux -V
tmux 2.8
```
* Platform (`uname -sp`)
```
$ uname -sp
Linux x86_64
```
* $TERM inside and outside of tmux (`echo $TERM`)
```
$ echo $TERM
st-256color
```
* Logs from tmux (`tmux kill-server; tmux -vv new`)
I will provide this info if needed later.

**Comment by nicm** [comment]
You are using " for the first example and ' for the second, variables are not expanded inside 's.

**Comment by 3N4N** [comment]
@nicm, thanks. It worked. Thanks for the quick response.
