### ISSUE TITLE
split-window -I is different than new-window -I

### ISSUE THREAD

**Issue by mathstuf** [tmux/tmux#1749]
### Issue description

The new `split-window -I` masks the `-I` flag for `new-window` (print the id of the created window/pane). This was originally an oversight, but has now been masked due to the input flag. Should `-i` be added to print the id or should input be moved over to `-i` and `-I` mapped to match `new-window`?

**Comment by nicm** [comment]
I don't get it. new-window has no -I. Do you mean new-window -P?

**Comment by mathstuf** [comment]
I don't know where I got that flag from; it's in my completion file. Sorry for the noise.
