### ISSUE TITLE
crash after `$ tmux show-options -w -t1`

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1751]
### Issue description

Tmux seems to crash when asking the value of a window local option for a non-existing window.

I can reproduce in a VM, on Ubuntu 18.04, after running:

	$ tmux -Ltest -f/dev/null new
	$ tmux show-options -w -t1

### Required information

 - `$ tmux -V`: tmux next-3.0
 - `$ uname -sp`: Linux x86_64
 - terminal: xfce4-terminal
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -L test -f /dev/null new`:
[tmux-client-6164.log](https://github.com/tmux/tmux/files/3208766/tmux-client-6164.log)
[tmux-out-6166.log](https://github.com/tmux/tmux/files/3208767/tmux-out-6166.log)
[tmux-server-6166.log](https://github.com/tmux/tmux/files/3208768/tmux-server-6166.log)

 - backtrace from `$ gdb -n -ex 'thread apply all bt full' -batch ./tmux ./core`:
[backtrace.txt](https://github.com/tmux/tmux/files/3208770/backtrace.txt)

 - possible offending commit(s) from `$ git bisect`:

         There are only 'skip'ped commits left to test.
         The first bad commit could be any of:
         1fd3b9ec1c61c96c6cd86f81a50470f4428eeafe
         2219f7cc73abc20407739e27ef191df393142795
         da31eddadc0c70875cd261d8925e4346c3e26590
         f3ab05e7cd9287d1e4be9a122687f568a8ef1f05
         3f189945d8838f98920a6d24a838bc8614ace636
         c660e46149d606bd5e52941081cbe155e493768b
         3c1f0cfc34d7dd87336e4a9a2c66435c02ecb847
         5b9211d827dec53c8a90f35846ff52d663d4c0d1
         e3b1358bbc616c1ba95414d6102c23bfcaa37687
         5943cd1907d20381c527d4b3b338df090cbbb1de
         78287e27c87ccdda1f8580382b336a0d02c26a03
         f980e868ddcafaa30cfa61c31b581edc592fa6d3
         e7827f8bc25e2051e6ed6ae3b5a5fba2cddb7ac0
         We cannot bisect more!

**Comment by nicm** [comment]
Great bug report, thanks. I think this is the fix: [x.diff.txt](https://github.com/tmux/tmux/files/3208845/x.diff.txt)
~~~~
--- cmd-show-options.c  12 May 2019 18:18:30 -0000      1.51
+++ cmd-show-options.c  22 May 2019 18:45:16 -0000
@@ -91,7 +91,14 @@ cmd_show_options_exec(struct cmd *self,

        window = (self->entry == &cmd_show_window_options_entry);
        if (args->argc == 0) {
-               options_scope_from_flags(args, window, fs, &oo, &cause);
+               scope = options_scope_from_flags(args, window, fs, &oo, &cause);
+               if (scope == OPTIONS_TABLE_NONE) {
+                       if (args_has(args, 'q'))
+                               return (CMD_RETURN_NORMAL);
+                       cmdq_error(item, "%s", cause);
+                       free(cause);
+                       return (CMD_RETURN_ERROR);
+               }
                return (cmd_show_options_all(self, item, oo));
        }
        argument = format_single(item, args->argv[0], c, s, wl, NULL);

**Comment by lacygoill** [comment]
I've just applied the patch and it seems to fix the issue. Now tmux correctly outputs the error message `no such window: 1`. Thank you very much for the quick answer and patch.

**Comment by nicm** [comment]
Great - applied to OpenBSD now, will be in GitHub later. Thanks!
