### ISSUE TITLE
tmux crash when odd number of panes arranged with one on top

### ISSUE THREAD

**Issue by grimm26** [tmux/tmux#1752]
### Issue description
tmux server crashes when an odd number of panes are arranged with one on top and the rest on bottom.  Once you switch to this layout, the next command issued in a pane in the bottom right pane will crash tmux.

### Required information

Please provide the following information:
Darwin i386
tmux 2.9a
xterm-256color

[tmux_logs.zip](https://github.com/tmux/tmux/files/3209377/tmux_logs.zip)

**Comment by nicm** [comment]
This is a poor description, it is not enough just to create panes as you describe - you don't even mention select-layout.

Anyway this looks like the same as https://github.com/tmux/tmux/issues/1736 which is fixed in master.

**Comment by grimm26** [comment]
thanks for the help.
