### ISSUE TITLE
crash after pasting a buffer starting with a multibyte character on tmux command-line

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1753]
### Issue description

Tmux seems to crash when you press `C-y` on tmux command-line, while the top buffer starts with a multibyte character. That is, the server quits, and `server lost` is written on the parent shell command-line.

To reproduce, run these shell commands:

    $ tmux -vv -Ltest -f/dev/null new
    $ tmux set status-keys emacs
    $ echo é | tmux load-buffer -

Then, enter tmux command-line by pressing `C-b` followed by `:`.
Finally, press `C-y` to insert the buffer (i.e. `é`).

### Required information

 - `$ tmux -V`: tmux 2.9a
 - `$ uname -sp`: Linux x86_64
 - terminal: st
 - `$TERM` outside tmux: st-256color
 - `$TERM` inside tmux: tmux-256color
 - logs from `$ tmux -vv -L test -f /dev/null new`:
[tmux-client-22048.log](https://github.com/tmux/tmux/files/3211737/tmux-client-22048.log)
[tmux-out-22050.log](https://github.com/tmux/tmux/files/3211738/tmux-out-22050.log)
[tmux-server-22050.log](https://github.com/tmux/tmux/files/3211739/tmux-server-22050.log)

 - logs from `$ strace -ttt -ff -ostrace.out tmux -Ltest -f/dev/null new`:
[strace.tar.gz](https://github.com/tmux/tmux/files/3211741/strace.tar.gz)

 - possible offending commit from `$ git bisect`: [`b29028a`](https://github.com/tmux/tmux/commit/b29028a914ba1c99a93fa51bc9a88b3d7b47dd09)

---

I can't get a backtrace, because tmux doesn't dump a core file, even though I have run `$ ulimit -c unlimited` before reproducing the crash.

    $ ulimit -a | grep core
    -c: core file size (blocks)         unlimited

    $ sysctl kernel.core_pattern
    kernel.core_pattern = |/usr/share/apport/apport %p %s %c %d %P

I've run `$ strace -ttt -ff -ostrace.out tmux -Ltest -f/dev/null new`, and all processes exit with code 0, except 3 which exit with code 1.
There's no `core dumped` in the logs from `$ strace`.
There's no mention of the crash in `/var/log/apport.log`.

---

I think there's another issue, which is related to this one.
If the top buffer doesn't start with a multibyte character, but contains one in the middle, when you paste it by pressing `C-y`, tmux doesn't crash; but it truncates the buffer right before the multibyte character.

Here's how to reproduce:

    $ tmux -Ltest -f/dev/null new
    $ tmux set status-keys emacs
    $ echo fooébar | tmux load-buffer -

Then, enter tmux command-line by pressing `C-b` followed by `:`.
Finally, press `C-y` to insert the buffer (i.e. `fooébar`); tmux doesn't crash but only inserts `foo` on the command-line instead of `fooébar`.

The offending commit could be [`ae5ddfd`](https://github.com/tmux/tmux/commit/ae5ddfdc1ae471f13c6d0e94ff4029d4fb29e1f4).
Here's the last output of `$ git bisect`:

    There are only 'skip'ped commits left to test.
    The first bad commit could be any of:
    9d191a6093673646c6c42a753ea3a337686b2b8d
    4a4daf13031673870341c68b990e20c314140118
    ff599f4004aaa6aae325ece5cbc996e2dc6f0b4f
    ae5ddfdc1ae471f13c6d0e94ff4029d4fb29e1f4
    We cannot bisect more!

**Comment by nicm** [comment]
Yes it stops at the first non-ASCII character - this is leftover from before UTF-8 was supported.

Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3212011/x.diff.txt)

**Comment by lacygoill** [comment]
Thank you for the answer.
I've just tested the patch, and it does fix the issue if I start with no config (`-f /dev/null`); but tmux doesn't start with my custom configurations, it seems frozen:

    $ ps aux | grep tmux
    user     10832  0.0  0.0  19356  3128 pts/1    S+   14:15   0:00 tmux
    user     10834  0.3  0.1  28428  3980 ?        Ss   14:15   0:00 tmux
    user     13995  0.0  0.0  19212  3024 pts/9    S+   14:19   0:00 ./tmux -Ltest
    user     13997  0.0  0.0  19884  3564 ?        Ss   14:19   0:00 ./tmux -Ltest
    user     14002  0.0  0.0   4508   712 ?        S    14:19   0:00 sh -c $HOME/.tmux/plugins/tpm/tpm
    user     14003  0.0  0.0  13012  2968 ?        S    14:19   0:00 bash /home/user/.tmux/plugins/tpm/tpm
    user     14019  0.0  0.0  19352  3148 ?        S    14:19   0:00 tmux show-environment -g TMUX_PLUGIN_MANAGER_PATH
    user     14142  0.0  0.0  14636  1088 pts/10   S+   14:19   0:00 grep --color=auto tmux

I'm going to bisect my tmux.conf, but I suspect it's going to take me some time to find the new issue, because it seems to involve something done by [tpm](https://github.com/tmux-plugins/tpm), so I also need to bisect tpm and see which command exactly triggers the issue.

**Comment by nicm** [comment]
Run tmux with -vv and show me the server log from it hanging please.

**Comment by lacygoill** [comment]
I've found a MWE:

    $ echo "run 'tmux show-environment -g \"\$FOO\"'" >/tmp/tmux.conf
    $ ./tmux -Ltest -f/tmp/tmux.conf

It seems the issue is that tpm runs [this command](https://github.com/tmux-plugins/tpm/blob/26d9ace1b47f4591b2afdf333442a498311b6ace/tpm#L21):

    tmux show-environment -g "$DEFAULT_TPM_ENV_VAR_NAME" >/dev/null 2>&1

Here are the logs with my custom configurations and the patched tmux:
[tmux-client-7815.log](https://github.com/tmux/tmux/files/3212160/tmux-client-7815.log)
[tmux-server-7817.log](https://github.com/tmux/tmux/files/3212162/tmux-server-7817.log)

**Comment by nicm** [comment]
OK I see it, looking now.

**Comment by nicm** [comment]
It looks like any command returning an error is not exiting:
~~~~
$ tmux set -g foobar
invalid option: foobar
...

**Comment by nicm** [comment]
Hmm weird it is happening on the build I'm running but not when I build again.

**Comment by nicm** [comment]
The marker on the queue telling the client to exit was being removed by accident because I changed how the group numbers are assigned. This is the fix:
~~~~
--- cmd-queue.c 23 May 2019 11:13:30 -0000      1.68
+++ cmd-queue.c 23 May 2019 13:07:37 -0000
@@ -181,6 +181,8 @@ cmdq_remove_group(struct cmdq_item *item
 {
        struct cmdq_item        *this, *next;

+       if (item->group == 0)
+               return;
        this = TAILQ_NEXT(item, entry);
        while (this != NULL) {
                next = TAILQ_NEXT(this, entry);

**Comment by lacygoill** [comment]
I've applied the second patch, on top of the first one; it fixes the initial issue, and now tmux can start with my custom configuration. However, I had this key binding:

    bind \ splitw -fh -c '#{pane_current_path}'

It worked prior to the patch, but now it doesn't work anymore, because `splitw` doesn't recognize a backslash as a valid key anymore:

    /home/user/.tmux.conf:655: unknown key:  splitw

I've fixed the issue by quoting the backslash key:

    bind '\' splitw -fh -c '#{pane_current_path}'

Thank you very much for your answers and patches.

**Comment by nicm** [comment]
Yes a backslash on its own now needs to be quoted.

**Comment by lacygoill** [comment]
@nicm: Sorry to comment on a closed issue, but I have had a few crashes today, after pasting the top buffer by pressing `C-y`, even though my tmux includes the patch which fixes the current issue.

I can't provide a MWE, because I can't reproduce reliably, and I don't have logs. However, I have [a backtrace](https://0x0.st/zaI5.txt). Is it enough to understand what is causing the crashes? Or do you also need logs?

**Comment by nicm** [comment]
What do you have in the buffer when it crashes?

Could you change -O2 to -O0 in Makefile.am and run autogen.sh and rebuild?
Then if you reproduce the backtrace will be more useful.

**Comment by lacygoill** [comment]
> What do you have in the buffer when it crashes?

It seems to happen randomly, and I copy a lot of text in tmux, so when it crashes it's hard to remember what was inside the buffer. I'm pretty sure it has happened without any multibyte characters in the buffer, but I could be wrong. I don't think it's only the buffer which is the issue, I think there's something else, maybe you need to create some windows, maybe you need to press some other key bindings before `C-y`. I often press `C-u`, `C-t`, `C-w`, `M-d` (this one doesn't work in tmux command prompt, but I'm too used to readline key bindings).

> Could you change -O2 to -O0 in Makefile.am and run autogen.sh and rebuild?

Ok, I've just done it.
I'm going to try to reproduce the issue. If I can, I'll post another backtrace.

**Comment by lacygoill** [comment]
It has happened again. Here's [another backtrace](https://0x0.st/zaU1.txt).
This time, I made sure to recompile tmux after replacing `-O2` with `-O0` in the makefile.

I've extracted the backtrace from the core file by running:

    $ gdb -n -ex 'thread apply all bt full' -batch ~/GitRepos/tmux/tmux ./core >~/backtrace.txt

---

I don't know what is in the buffer, because when it happens, I press `C-y` by accident. Most of the time, I want to press `C-t` (to transpose the last 2 characters), or `C-u` to kill from the cursor up to the start of the line. But the keys `t`, `y` and `u` are next to each other on my keyboard. So I regularly hit `y`, while I meant `u` or `t`.
I'm almost certain there're no exotic characters in the buffer.

It's hard to reproduce, and I'm reluctant to run `-vv` because the server log grows big over time, I don't know when the crash will occur, and I don't have much space left on my ssd.

Let me know if there's something else I can do to help debugging the issue.

**Comment by nicm** [comment]
Try this please:
~~~~
diff --git a/status.c b/status.c
index ce36cc3c..45bab941 100644
--- a/status.c
+++ b/status.c
@@ -865,7 +865,7 @@ status_prompt_paste(struct client *c)
 		if ((pb = paste_get_top(NULL)) == NULL)
 			return (0);
 		bufdata = paste_buffer_data(pb, &bufsize);
-		ud = xreallocarray(NULL, bufsize, sizeof *ud);
+		ud = xreallocarray(NULL, bufsize + 1, sizeof *ud);
 		udp = ud;
 		for (i = 0; i != bufsize; /* nothing */) {
 			more = utf8_open(udp, bufdata[i]);

**Comment by lacygoill** [comment]
I've just applied the patch; if tmux doesn't crash in the next few hours/days, I'll know whether it fixed the issue. Thank you very much for the patch.

**Comment by nicm** [comment]
I think this is right so I have applied it anyway, let me know if you still see issues.
