### ISSUE TITLE
status line format

### ISSUE THREAD

**Issue by illtown** [tmux/tmux#1754]
Hi, I'm writing a tmux theme and found some weird status line behavior, which I consider a bug, as it behaves the same on default config too.

### Issue description
Tmux version I use is 2.9a.
Here are the steps I reproduce it:
```
tmux -f /dev/null
tmux set status-justify centre
tmux set status-right '1234'
tmux set status-right-style 'align=centre'
tmux neww
tmux neww
```
Expected behavior:
status-right moves to the right of window-status (which is centered).

Observed behavior:
status-right gets mirrored to the right of window-status (which is centered) so that u get two copies of status-right: one is centered and one at default position - right corner.
Moreover, when you create new windows, the first character of status-right disappears if there are even number of windows.

I wasn't able to reproduce this bug for:
- status-left, it's fine.
- window-status and status-right moved left
- window-status moved left and status-right centered

**Comment by nicm** [comment]
Thanks. There are two errors with how we draw if there is text after the window list in the centre. Try this please: [tmux-list-right.diff.txt](https://github.com/tmux/tmux/files/3212677/tmux-list-right.diff.txt)

**Comment by illtown** [comment]
Awesome! works like a charm) Thanks

**Comment by nicm** [comment]
Great - applied to OpenBSD now, will be in GitHub later. Thanks!
