### ISSUE TITLE
Zsh prompt issues when prompt contains utf-8 characters and tmux is running

### ISSUE THREAD

**Issue by Jehops** [tmux/tmux#1756]
[Two](https://github.com/woefe/git-prompt.zsh) [different](https://github.com/olivierverdier/zsh-git-prompt) tools, which by default use utf-8 characters to show Git repository status in Zsh's prompt, cause issues with cursor placement after Zsh's prompt, but only when tmux (2.8 or 2.9a) is running.  If I am recalling correctly, before tmux version 2.8 there were no problems.  The most common issue I see is where an extra space is added after the prompt when PWD is a Git repository.  The simplest way I have been able to reproduce the problem is with an empty tmux configuration and only `PROMPT='✓> '` in `.zshrc`.
[Here](https://www.youtube.com/watch?v=H5VtaSbkOZo) is a short video.  You can see outside of the a Git repository everything looks OK, but when PWD is a Git repository (uft-8 character in the prompt), an extra space is added after the prompt.  I tried this with xterm, urxtv, and alacritty and the behaviour was the same for all three.

Required Information:

* tmux version (`tmux -V`)
tmux 2.9a

* Platform (`uname -sp`)
FreeBSD amd64

* $TERM inside and outside of tmux (`echo $TERM`)
screen-256color
rxvt-unicode-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-18022.log](https://github.com/tmux/tmux/files/3213434/tmux-client-18022.log)
[tmux-out-18024.log](https://github.com/tmux/tmux/files/3213439/tmux-out-18024.log)
[tmux-server-18024.log](https://github.com/tmux/tmux/files/3213437/tmux-server-18024.log)

**Comment by nicm** [comment]
The character appears to be \342\234\223 which your platform is telling tmux is width 2:
~~~~
1558632390.223620 input_top_bit_set 3 '\342\234\223' (width 2)
~~~~
However, on the platforms I have here it is width 1.

So this seems like an error in FreeBSD's locale implementation.

Did you try building tmux with utf8proc?

**Comment by Jehops** [comment]
> Did you try building tmux with utf8proc?
Yes.  The FreeBSD package defaults to building with utf8proc.  I will try to dig deeper with the locale.

**Comment by nicm** [comment]
Then it is a problem with utf8proc - try without it?

**Comment by Jehops** [comment]
Same behaviour without it.

Here is what `locale` says.
```
 % locale
LANG=en_CA.UTF-8
LC_CTYPE="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_ALL=
```

**Comment by nicm** [comment]
Are you sure whether or not you are using utf8proc? What does ldd `which tmux` show?

**Comment by Jehops** [comment]
I rebuilt the tmux package without utf8proc, then I uninstalled utf8proc from the target host, so I'm pretty sure.

Before
```
 % ldd /usr/local/bin/tmux
/usr/local/bin/tmux:
        libutil.so.9 => /lib/libutil.so.9 (0x8002d2000)
        libc.so.7 => /lib/libc.so.7 (0x8002e9000)
        libutf8proc.so.2 => /usr/local/lib/libutf8proc.so.2 (0x8006dc000)
        libulog.so.0 => /lib/libulog.so.0 (0x800728000)
        libevent-2.1.so.6 => /usr/local/lib/libevent-2.1.so.6 (0x80072c000)
        libncurses.so.8 => /lib/libncurses.so.8 (0x80077e000)
        libmd.so.6 => /lib/libmd.so.6 (0x8007d5000)
        libcrypto.so.111 => /lib/libcrypto.so.111 (0x8007f2000)
        libthr.so.3 => /lib/libthr.so.3 (0x800adf000)
```

After
```
% ldd /usr/local/bin/tmux
/usr/local/bin/tmux:
        libutil.so.9 => /lib/libutil.so.9 (0x8002d2000)
        libc.so.7 => /lib/libc.so.7 (0x8002e9000)
        libulog.so.0 => /lib/libulog.so.0 (0x8006dc000)
        libevent-2.1.so.6 => /usr/local/lib/libevent-2.1.so.6 (0x8006e0000)
        libncurses.so.8 => /lib/libncurses.so.8 (0x800732000)
        libmd.so.6 => /lib/libmd.so.6 (0x800789000)
        libcrypto.so.111 => /lib/libcrypto.so.111 (0x8007a6000)
        libthr.so.3 => /lib/libthr.so.3 (0x800a93000)
```

**Comment by nicm** [comment]
Do the logs without utf8proc also show width 2 if you do the same to generate the logs as you did before and then grep for top_bit_set?

**Comment by Jehops** [comment]
Apologies.  I believe the old tmux server must have been running or I was in a session sshed to another host.  All seems to be working without utf8proc.  Grepping the logs shows `/home/jrm/tmux-server-81759.log:1558637377.846541 input_top_bit_set 3 '\342\234\224' (width 1)`.

**Comment by Jehops** [comment]
I just tried updating the utf8proc FreeBSD package from version 2.2.0 to 2.4.0 and then build tmux with utf8proc.  All seems to be working well.  I will close this now, but if any more information from me is helpful, please let me know.

Thank you for your help and thank you for your work on tmux.
