### ISSUE TITLE
Custom aliases not recognized anymore (“unknown command”)

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1757]
### Issue description

Custom aliases don't seem to be recognized anymore.

To reproduce, run these shell commands:

    $ tmux -Ltest -f/dev/null new
    $ tmux info
    unknown command: info

    $ tmux set -s 'command-alias[100]' zoom='resize-pane -Z'
    $ tmux zoom
    unknown command: zoom

### Required information

 - `$ tmux -V`: tmux next-3.0
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Ltest -f/dev/null new`:
[tmux-client-25806.log](https://github.com/tmux/tmux/files/3218958/tmux-client-25806.log)
[tmux-out-25808.log](https://github.com/tmux/tmux/files/3218960/tmux-out-25808.log)
[tmux-server-25808.log](https://github.com/tmux/tmux/files/3218961/tmux-server-25808.log)

 - possible offending commit(s) from `$ git bisect`:
   [`bf2cf33`](https://github.com/tmux/tmux/commit/bf2cf33fc633dd6f28d0d57e669cbd0b109a5f2d)
   [`75aeb73`](https://github.com/tmux/tmux/commit/75aeb733f292639f8332df11315ca8280e5631fd)
   [`723010b`](https://github.com/tmux/tmux/commit/723010ba72e337832402f8e44981c02caa30b476)

**Comment by nicm** [comment]
Ugh yes, thanks. I actually wrote down that this needed to be done but then forgot about it.

Please try this: [tmux-list-merge.diff.txt](https://github.com/tmux/tmux/files/3219188/tmux-list-merge.diff.txt)

**Comment by nicm** [comment]
I have applied this so please just wait for GitHub to update and then test.

**Comment by lacygoill** [comment]
I've been able to [apply the patch](https://0x0.st/zam-.txt), but the [compilation failed](https://0x0.st/zami.txt).
At the moment, the script hasn't yet automatically applied the new commits to GitHub. When it will apply them, I'll try to compile the new version; thank you very much.

**Comment by lacygoill** [comment]
The latest batch of commits fixed the issue. Thank you very much.
