### ISSUE TITLE
tmux mouse and scrolling regressions

### ISSUE THREAD

**Issue by milosivanovic** [tmux/tmux#176]
All of these regressions are present in the latest master commit, currently c975de2e.

---

##### Regression 1 #####
Scrolling up one mousewheel unit enters copy mode only, instead of entering copy mode and scrolling up one unit simultaneously.
More detail: The copy mode status in the top-right of the pane displays [0/YYYY] on the first upwards scroll instead of [X/YYYY] where X is one mousewheel unit's worth of lines (X > 0) and YYYY is the number of history lines available in that session.

##### Regression 2a #####
Scrolling up (entering copy mode) and left-clicking in the same pane does not exit copy mode any more.

##### Regression 2b #####
If 2a is intentional, then: Scrolling up (entering copy mode), left-clicking in the same pane, then scrolling all the way back down in the same pane does not exit copy mode any more.

##### Regression 3 #####
There seems to be no way of configuring how many lines to scroll per unit mousewheel (the variable X in Regression 1).

---

If for whatever reason you are against fixing one or more of them, please specify the respective key bindings that would return this behaviour to match tmux version 2.0 so that tmux users can continue to enjoy this as they did before.

**Comment by alytvynov** [comment]
Would really appreciate some option for regression 3.
One line per tick (or whatever the number is) is really slow and hogs the CPU.

**Comment by nicm** [comment]
Nobody asked for this before 2.1 so it was dropped but you could try this http://pastebin.ca/raw/3209063

**Comment by nicm** [comment]
Sorry I missed you had other things in here;

1) It wasn't particularly intentional but it makes sense, you can probably use send-keys if you want to send additional commands in your mouse key bindings.

2) You may be able to bind left button up to cancel in copy mode bindings.

**Comment by rightaway** [comment]
Can having some option for number of lines to scroll per mouse tick be added? Having to patch tmux for such a basic and useful feature doesn't seem ideal.

**Comment by nicm** [comment]
It is never going to happen unless someone tests my patch.

**Comment by milosivanovic** [comment]
Please state your reason for closing this issue.

**Comment by milosivanovic** [comment]
In response to: 1) It wasn't particularly intentional but it makes sense, you can probably use send-keys if you want to send additional commands in your mouse key bindings.

No, scrolling up with your mouse and not actually scrolling does not make sense. This is a regression.

In response to:
2) You may be able to bind left button up to cancel in copy mode bindings.
Could you please specify how this can be done, as it was occurring by default before.

I tried your patch before opening this issue, and it appeared to not read the configured input correctly; hard-coding the number of repeats in the patch did however work. I will retest and post findings soon.

I needn't remind you that you have chosen to break functionality for no benefit by ignoring common sense and not specifying sane defaults in 2.1 to match 2.0 and earlier.
