### ISSUE TITLE
Tmux crashes issuing new-window -k in the same window

### ISSUE THREAD

**Issue by gsusrafael** [tmux/tmux#1760]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

To reproduce the issue you need to be in the window involved on the command below:
`new-window -k -t X:3 -n ' mail' 'mutt'`
this means if you are issuing this command, you need to be on the window 3 in the session X

this is my .tmux.conf:
[tmuxconf.txt](https://github.com/tmux/tmux/files/3223533/tmuxconf.txt)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
**tmux next-3.0**
* Platform (`uname -sp`).
**Linux x86_64**
* $TERM inside and outside of tmux (`echo $TERM`).
**screen-256color**
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-server-5574.log](https://github.com/tmux/tmux/files/3223508/tmux-server-5574.log)
[tmux-out-5574.log](https://github.com/tmux/tmux/files/3223509/tmux-out-5574.log)
[tmux-client-5572.log](https://github.com/tmux/tmux/files/3223510/tmux-client-5572.log)

**Comment by nicm** [comment]
Can you try this change please:
~~~~
--- spawn.c     25 May 2019 06:58:10 -0000      1.4
+++ spawn.c     27 May 2019 12:35:28 -0000
@@ -163,6 +163,7 @@ spawn_window(struct spawn_context *sc, c
                }
                sc->wl->session = s;
                winlink_set_window(sc->wl, w);
+               s->curw = sc->wl;
        } else
                w = NULL;
        sc->flags |= SPAWN_NONOTIFY;

**Comment by gsusrafael** [comment]
@nicm it's working flawlessly
