### ISSUE TITLE
multiple status lines

### ISSUE THREAD

**Issue by illtown** [tmux/tmux#1762]
### Issue description
Hi, I found a bug related to changing the number of status lines. It appears on both 2.9a and next-3.1

Steps to reproduce:
Complicated to describe, but I will try:
1. I start with default config:
tmux -f /dev/null
2. Change number of status lines:
tmux set status 2
3. Revert the changes either by:
tmux set status on
or
tmux set -u status
and here I see the second line (pane sizes by default), instead of the default one (left, windows and right), which is strange.

4. Next, if you wait for status line to refresh (either by changing/creating windows or just wait for status-right time to change), then it gets it's format updated from pane sizes to the default one, which is fine at first sight.

5. But if you add a status line again with
tmux set status 2
you end up with 2 lines, one being a true one, and other just a stale copy of it.

**Comment by illtown** [comment]
I've written a simple script which toggles the 'status' option between 'on' and the number of lines you wish to see, which you may bind to DoubleClick action. That's the reason behind that strange 'steps to reproduce'  if you are curious)

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/3229101/x.diff.txt)

~~~~
Index: status.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/status.c,v
retrieving revision 1.199
diff -u -p -r1.199 status.c
--- status.c	23 May 2019 12:47:52 -0000	1.199
+++ status.c	28 May 2019 18:09:38 -0000
@@ -348,10 +348,8 @@ status_redraw(struct client *c)
 	/* Resize the target screen. */
 	if (screen_size_x(&sl->screen) != width ||
 	    screen_size_y(&sl->screen) != lines) {
-		if (screen_size_x(&sl->screen) != width)
-			force = 1;
 		screen_resize(&sl->screen, width, lines, 0);
-		changed = 1;
+		changed = force = 1;
 	}
 	screen_write_start(&ctx, NULL, &sl->screen);

**Comment by illtown** [comment]
I'm impressed by your skills and the speed you fix these bugs)
Look like it does, yeah. Can't reproduce with that patch. Thanks

**Comment by illtown** [comment]
There is also one thing about 'status-format' option I'd like to mention. 
If you set status-format[1] to something in current context without -g flag, then line 0 gets vanished.
As to my understanding these options constitue one array variable, which can't be split between global and running config.
Can't treat it as a bug though. Maybe that behavior should be just stated in docs.

**Comment by nicm** [comment]
All options work like this, it is either session or global not both.

**Comment by nicm** [comment]
I've applied this fix to OpenBSD now, it'll be in GitHub in an hour to two. Thanks!

**Comment by illtown** [comment]
I see, ok. Thanks
