### ISSUE TITLE
Characters overflowing at DragonFly BSD

### ISSUE THREAD

**Issue by mazocomp** [tmux/tmux#1763]
This happens more than a year: https://transfer.sh/f0iSR/20190529_192303.jpg

Using different TERM values doesn't help, I guess that's a syscons issue, still I am sure this can be fixed with some workarounds in tmux because other ncurses applications work fine.

**Comment by mazocomp** [comment]
And yes I am always running latest tmux version available.

**Comment by mazocomp** [comment]
@nicm does that mean the bug is fixed in snapshot?

**Comment by nicm** [comment]
No it means you need to open a proper issue with an actual description of the problem.

**Comment by mazocomp** [comment]
@nicm ok. I'll try to describe shortly: the characters go beyond the screen and that makes them be printed on the next line. My guess that happens because some characters are unprintable and that makes them take extra space on the screen.

**Comment by nicm** [comment]
What TERM inside and outside tmux? What terminal? What characters - are they in your prompt, if so then what is it? Also please show tmux logs.

**Comment by mazocomp** [comment]
Inside tmux the TERM is "screen", outside tmux the TERM is "cons25". The characters I see at the end of line are referred to date, it appears it can't display month number:
https://transfer.sh/BuI2s/20190529_213736.jpg
https://transfer.sh/dcGYj/20190529_213742.jpg
Every time the status line updates it looks like this:
https://transfer.sh/2a9Bh/20190529_214211.jpg
And when I split pane, it looks like this:
https://transfer.sh/hujoc/20190529_214246.jpg
And here are logs I get:
https://transfer.sh/eNwfa/tmux-client.log
https://transfer.sh/5K0FM/tmux-server.log
https://transfer.sh/Mrvxp/tmux-out.log
You can also notice misplaced cursor position at photo due to this bug.

**Comment by nicm** [comment]
Does it fix it if you attach tmux like this so it doesn't show UTF-8:
~~~~
LANG= LC_ALL= LC_CTYPE= tmux attach
~~~~

This smells like a UTF-8 width issue or lack of support on your terminal. Do this please (the printf inside the new tmux):
~~~~
tmux -vvLtest new
printf "\320\274\320\260\321\217"
~~~~
Then show me the new server log.

**Comment by mazocomp** [comment]
Nope. The status line still can't be printed properly, that makes cursor misplaced again. Date is now printed properly. Also pane split can't be printed properly (and running clear erases its line).
https://transfer.sh/ymuff/20190529_231719.jpg
(on the second photo you can see successful printf)
https://transfer.sh/Q2oU0/20190529_232043.jpg
https://transfer.sh/b0u0s/tmux-server.log

**Comment by nicm** [comment]
What does "tmux lsc" show inside tmux when you test with "LANG= LC_ALL= LC_CTYPE= tmux attach"? Does it still show "(utf8)"?

**Comment by nicm** [comment]
Never mind, can see that in the log.

**Comment by mazocomp** [comment]
It shows: /dev/ttyv0: 0 [120x33 cons25]

**Comment by nicm** [comment]
Does tmux draw correctly if you use TERM=ansi or TERM=vt220? The pane border lines may be the wrong character, don;t worry about that, are they in the right place and does clear work?

**Comment by mazocomp** [comment]
It doesn't, the result is the same.

**Comment by nicm** [comment]
Hmm. Can you do this please:
~~~~
tmux -Ltest kill-server
tmux -vvLtest new -d
tmux -Ltest set -g status off
TERM=ansi tmux -Ltest attach
tmux -Ltest splitw
~~~~
Then show me a screenshot of it how it looks wrong and the server log.

If you need to do anything else to make it go wrong that's fine, tell me what you do. I just want the status to be off so it isn't in the logs.

**Comment by nicm** [comment]
It's definitely wrong with vt220 as well? vt220 has csr and cons25/ansi don't, vt220 has no indn and con25/ansi do, those are the biggest likely problems.

**Comment by mazocomp** [comment]
Yes, it is. I guess it's because DragonFly's console implementation is terrible. Without status line it looks fine even if I switch between panes:
https://transfer.sh/eVz14/20190529_235023.jpg
https://transfer.sh/aRrEN/20190529_235059.jpg
https://transfer.sh/PIRlx/tmux-server.log

**Comment by nicm** [comment]
OK I installed dfly and the reason for this I think is that this console is a non-xenl terminal and somewhere along the line the tmux xenl support stopped working (which is hardly surprising since there are almost no non-xenl terminals left around since FreeBSD and NetBSD replaced their consoles).

On non-xenl terminals there is no invisible cursor position at the right of the terminal, the cursor wraps as soon as it hits the last column. This means it is impossible to write into the bottom right cell of the terminal without scrolling, so tmux is meant to leave it without drawing it - but it has stopped doing so.

**Comment by nicm** [comment]
This seems to fix it for me but YMMV:
~~~~
diff --git a/tty.c b/tty.c
index 34403a1f..d92951bc 100644
--- a/tty.c
+++ b/tty.c
@@ -527,6 +527,12 @@ tty_putc(struct tty *tty, u_char ch)
 {
 	const char	*acs;
 
+	if ((tty->term->flags & TERM_EARLYWRAP) &&
+	    ch >= 0x20 && ch != 0x7f &&
+	    tty->cy == tty->sy - 1 &&
+	    tty->cx + 1 >= tty->sx)
+		return;
+
 	if (tty->cell.attr & GRID_ATTR_CHARSET) {
 		acs = tty_acs_get(tty, ch);
 		if (acs != NULL)
@@ -557,6 +563,11 @@ tty_putc(struct tty *tty, u_char ch)
 void
 tty_putn(struct tty *tty, const void *buf, size_t len, u_int width)
 {
+	if ((tty->term->flags & TERM_EARLYWRAP) &&
+	    tty->cy == tty->sy - 1 &&
+	    tty->cx + len >= tty->sx)
+		len = tty->sx - tty->cx - 1;
+
 	tty_add(tty, buf, len);
 	if (tty->cx + width > tty->sx) {
 		tty->cx = (tty->cx + width) - tty->sx;
@@ -1746,6 +1757,8 @@ void
 tty_cmd_cells(struct tty *tty, const struct tty_ctx *ctx)
 {
 	struct window_pane	*wp = ctx->wp;
+	u_int			 i;
+	struct grid_cell	 gc;
 
 	if (!tty_is_visible(tty, ctx, ctx->ocx, ctx->ocy, ctx->num, 1))
 		return;
@@ -1769,6 +1782,15 @@ tty_cmd_cells(struct tty *tty, const struct tty_ctx *ctx)
 	tty_margin_off(tty);
 	tty_cursor_pane_unless_wrap(tty, ctx, ctx->ocx, ctx->ocy);
 
+	if (tty->term->flags & TERM_EARLYWRAP) {
+		for (i = 0; i < ctx->num; i++) {
+			memcpy(&gc, ctx->cell, sizeof gc);
+			utf8_set(&gc.data, ((char *)ctx->ptr)[i]);
+			tty_cell(tty, &gc, ctx->wp);
+		}
+		return;
+	}
+
 	tty_attributes(tty, ctx->cell, ctx->wp);
 	tty_putn(tty, ctx->ptr, ctx->num, ctx->num);
 }

**Comment by mazocomp** [comment]
Mostly works. If locale is set to UTF-8, then pane split is broken.

**Comment by mazocomp** [comment]
Also status line can't print the last digit at date (locale doesn't matter here):
https://transfer.sh/AU9Th/20190530_025046.jpg

**Comment by nicm** [comment]
The first sounds like the console doesn't support UTF-8 line drawing properly, you can disable it with the U8 capability in terminal-overrides (I forget if it needs to be set to 0 or 1).

The latter (missing last cell) is just how it works, tmux can't draw into this cell without scrolling. If you don't like that you need a better terminal.

**Comment by nicm** [comment]
I have applied this now, let me know if you continue to see problems. Thanks!

**Comment by mazocomp** [comment]
@nicm is it possible to print date one column earlier then?

**Comment by nicm** [comment]
Yes you can add a space to the end of your status-right.
