### ISSUE TITLE
Previously valid command fails in 3.0-rc

### ISSUE THREAD

**Issue by gnachman** [tmux/tmux#1766]
### Issue description

The following command fails with a syntax error in 3.0-rc:

```
capture-pane -peqJ -t %1 -S -1000
```

I guess the parser has changed and now it wants quotes around `%1`. This will cause problems for anyone using control mode with a current version of iTerm2.

### Required information

Please provide the following information:

% uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.7
xterm-256color

Log snippet:
```
1559281522.231341 yylex_token: capture-pane
1559281522.231353 yylex_token: -peqJ
1559281522.231361 yylex_token: -t
1559281522.231369 yylex_get_word: %1
1559281522.231382 cmdq_append </dev/ttys017>: [control_error/0x10200ea00]
```
[tmux-server-66257.log](https://github.com/tmux/tmux/files/3239864/tmux-server-66257.log)

**Comment by nicm** [comment]
Yes, try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3239925/x.diff.txt)

This will still forbid stuff like %"abc" but I think that is OK.
~~~~
Index: cmd-parse.y
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-parse.y,v
retrieving revision 1.10
diff -u -p -r1.10 cmd-parse.y
--- cmd-parse.y	30 May 2019 10:04:33 -0000	1.10
+++ cmd-parse.y	31 May 2019 06:10:35 -0000
@@ -998,11 +998,15 @@ yylex(void)
 
 		if (ch == '%') {
 			/*
-			 * % is a condition unless it is alone, then it is a
-			 * token.
+			 * % is a condition unless it is all % or all numbers,
+			 * then it is a token.
 			 */
 			yylval.token = yylex_get_word('%');
-			if (strcmp(yylval.token, "%") == 0)
+			for (cp = yylval.token; *cp != '\0'; cp++) {
+				if (*cp != '%' && !isdigit((u_char)*cp))
+					break;
+			}
+			if (*cp == '\0')
 				return (TOKEN);
 			if (strcmp(yylval.token, "%if") == 0) {
 				free(yylval.token);

**Comment by nicm** [comment]
I have applied this, please let me know if you see any further problems. Thanks!

**Comment by gnachman** [comment]
LGTM
