### ISSUE TITLE
Why there are always breaking changes in tmux options?

### ISSUE THREAD

**Issue by tamlok** [tmux/tmux#1769]
Hi,

I use openSUSE Tumbleweed. After updating tmux to 2.9 version, it complains about the following invalid options which worked fine previously:

```
/home/tamlok/.tmux.conf:52: invalid option: window-status-current-fg
/home/tamlok/.tmux.conf:53: invalid option: window-status-current-bg
/home/tamlok/.tmux.conf:61: invalid option: message-fg
/home/tamlok/.tmux.conf:62: invalid option: message-bg
/home/tamlok/.tmux.conf:63: invalid option: message-attr
```

And this happened before. After updating tmux, there are always breaking options.

As a mature software, could we take the compability serious and mark it as higher priority? Introducing new, more clean options is great, but it would be better to keep the old options. Otherwise, users need to change their configs all the time and if they work at different platforms with multiple tmux versions, it is really painful!

Thanks!

**Comment by moritzdietz** [comment]
You can take a look here: https://github.com/tmux/tmux/wiki/FAQ#how-do-i-translate--fg--bg-and--attr-options-into--style-options
As well as #1689 and #1732 for some more context.

**Comment by nicm** [comment]
These options were kept for almost 5 years before being removed.
