### ISSUE TITLE
unknown option: mode-mouse

### ISSUE THREAD

**Issue by tanrax** [tmux/tmux#177]
![screen shot 2015-11-01 at 19 48 57](https://cloud.githubusercontent.com/assets/4553672/10870714/9d4e0710-80d1-11e5-8cf9-5dc5af6e09a1.jpg)

**Comment by nicm** [comment]
mode-mouse has been replaced.

**Comment by tanrax** [comment]
As it is now?

**Comment by wlhlm** [comment]
https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

**Comment by tanrax** [comment]
For others who have the same problem.

Replace `mode-mouse` to `mouse`

**Comment by deyaaeldeen** [comment]
I have this in my conf file: 
set-window-option -g mouse on
and then I do tmux source-file ~/.tmux.conf but still not able to scroll
