### ISSUE TITLE
Cant scroll in copy-mode-vi.

### ISSUE THREAD

**Issue by eraserpencil** [tmux/tmux#1770]
tmux v2.8
Linux x86_64
tmux-256color

my tmux-conf consists of https://github.com/hallazzang/tmux-reset + `set-window-option -g mode-keys vi`.

I did 
`vim .bashrc`
`Ctrl-b + [ ` 

I try to scroll up with the arrow keys and reach the limit of the current view i have. Unable to scroll passed whats shown.

**Comment by nicm** [comment]
What does it say in yellow in the top right corner?

**Comment by eraserpencil** [comment]
[0/0]

**Comment by nicm** [comment]
Right so you haven't scrolled any lines into the history so you can't view
them.

**Comment by eraserpencil** [comment]
how should i scroll any lines into history?

**Comment by nicm** [comment]
Move off the bottom of the terminal in the shell. Full screen applications like vim manage their own history and tmux has no access to it.

**Comment by eraserpencil** [comment]
Hmmm. Is using vim's copy and paste while in a file and tmux copy-mode while outside, along with sharing system's clipboard a standard workaround?

**Comment by nicm** [comment]
You can do that if you like.

**Comment by eraserpencil** [comment]
thanks :)
