### ISSUE TITLE
wheel and click don't work on tree mode.

### ISSUE THREAD

**Issue by koie** [tmux/tmux#1772]
### Issue description

In choose-buffer, I cannot move selected line by wheel and click.

### My hack

* WORKAROUND: It seems KEYC_MOUSEDOWN1_PANE doesn't arrive. 
    * BUG?  But, KEYC_DOUBLECLICK1_PANE  works.
* BUGFIX: wheelup/down was KEYC_NONE'ed .
```
--- a/mode-tree.c
+++ b/mode-tree.c
@@ -877,11 +877,16 @@ mode_tree_key(struct mode_tree_data *mtd
                }
                if (mtd->offset + y < mtd->line_size) {
                        if (*key == KEYC_MOUSEDOWN1_PANE ||
+                           *key == KEYC_MOUSEUP1_PANE ||
                            *key == KEYC_MOUSEDOWN3_PANE ||
                            *key == KEYC_DOUBLECLICK1_PANE)
                                mtd->current = mtd->offset + y;
                        if (*key == KEYC_DOUBLECLICK1_PANE)
                                *key = '\r';
+                       else if (*key == KEYC_WHEELUP_PANE ||
+                                *key == KEYC_WHEELDOWN_PANE) {
+                               goto hack;
+                       }
                        else {
                                if (*key == KEYC_MOUSEDOWN3_PANE)
                                        mode_tree_display_menu(mtd, c, x, y, 0);
@@ -895,6 +900,7 @@ mode_tree_key(struct mode_tree_data *mtd
                return (0);
        }

+ hack:
        line = &mtd->line_list[mtd->current];
        current = line->item;

```

**Comment by nicm** [comment]
MouseDown1Pane works for me. Show me logs please from pressing it in buffer mode.

I don't think WheelUp and WheelDown should select the item, shouldn't they move through the list?

**Comment by koie** [comment]
```
% cat test.conf
set-buffer 111
set-buffer 222
set-buffer 333
% ./tmux -f ./test.conf -v
```
C-b = MOUSEDOWN1 MOUSEUP1 q exit RET

terminal is PuTTY Release 0.69-jp20170506

[tmux-client-21059.log](https://github.com/tmux/tmux/files/3244661/tmux-client-21059.log)
[tmux-server-21061.log](https://github.com/tmux/tmux/files/3244662/tmux-server-21061.log)

About wheelup/down in buffer mode,
I don't mind if I can't select a list item with the wheel, but when I saw the code I thought it was implemented.

**Comment by nicm** [comment]
I don't see any mouse input being sent to tmux in these logs, are you sure
you pressed the mouse? Also you will need "set -g mouse on" in your config
to test.

**Comment by koie** [comment]
I'm sorry.  I forgot "set -g mouse on" for testing.
MouseDown1Pane problem is solved. 
In my patchworked ~/.tmux.conf, there is `bind-key -T root MouseDown1Pane select-pane`.
I read the default binding,,, `send-key -M` is needed.

**Comment by nicm** [comment]
Is the Wheel working for you as well now?

**Comment by koie** [comment]
There is no problem as I don't use the wheel in the buffer mode.
