### ISSUE TITLE
resize-pane does not adjust all splits

### ISSUE THREAD

**Issue by toddyamakawa** [tmux/tmux#1774]
### Issue description

Run these commands (easiest way is in a script):
```sh
tmux split-window -v
tmux split-window -h
tmux split-window -v
tmux resize-pane -y 999
```

Expected behavior: The final pane should be max height and the original pane should be minimum height
Actual behavior: The original pane size does not get resized

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).

```
tmux next-3.1
Linux unknown
xterm-256color
```

* Logs from tmux (`tmux kill-server; tmux -vv new`).

I have no idea how to grab the relevant snippet.

**Comment by nicm** [comment]
Yes, it doesn't adjust the size of panes outside of the direct containing pane.

**Comment by nicm** [comment]
It resizes pane 3 because that is the active pane and it resizes it up to the limit of the "cell" that contains it, which is the one that contains panes 2 and 3.

You can make pane 0 smaller as well but you will need to do it explicitly with resize-pane -t0.

**Comment by toddyamakawa** [comment]
Thanks for your help. What is a cell?

Note: I have `pane-base-index` set to `1`. Consider the following two cases where I call `resize-pane -y 999` from pane 3:

Case 1: this will not resize pane 1
```
tmux split-window -v
tmux split-window -h
tmux split-window -v -d
tmux resize-pane -y 999
```

Case 2: this will resize pane 1, the only difference is I have one less pane
```
tmux split-window -v
tmux split-window -h
tmux resize-pane -y 999
```

Is that expected behavior? My end goal is to "vertically maximize" my current pane. So does that mean I might have to manually set the height of all other panes? Is there a way to get all of the panes that are in a "column"?

**Comment by nicm** [comment]
Hmm I don't know if there is a reliable way to achieve this for every possible layout. But why would you want your other panes to be one line rather than just zooming and making them disappear altogether?

If you know which layouts you will have upfront you could do it.

**Comment by toddyamakawa** [comment]
Here's an example workflow:
In my left column I have 2-3 panes with different environments sourced in each pane.
In my right column I have 2-3 panes with code. One pane is usually code I'm editing, another pane will have some example code or something.

I always want at least one environment pane visible on the left and one code pane visible on the right, so I really just need a "vertical zoom", which I found resizing to work well. I then discovered it works really well if every time I do a `select-pane -D/-U` I run a `resize-pane -y 999` because it's effectively an automatic vertical zoom.

Finally, I discovered that I can do a `split-window -fv` and have two of my example workflows running in a single window! (I have other things that I need in the windows to the left and right.) However, this new split breaks my pseudo vertical zoom.

If I run `select-pane -D` (or `-U`) enough times, am I guaranteed to return to my starting pane no matter what my layout is?

**Comment by nicm** [comment]
I don't think there is a way to make this work with a full width split as it is at the moment. It would need to change to resize outside the parent cell, in the same way dragging with the mouse does.

**Comment by toddyamakawa** [comment]
I found a workaround for my use case. I simply have to resize a pane before switching:

```
bind-key -n M-k resize-pane -y 1 \; select-pane -U \; resize-pane -y 999
bind-key -n M-j resize-pane -y 1 \; select-pane -D \; resize-pane -y 999
``

**Comment by nicm** [comment]
This is not trivial to change, I have added it to the todo list to take a look at some time in future.
