### ISSUE TITLE
Prevent resize triggering activity

### ISSUE THREAD

**Issue by xim** [tmux/tmux#1779]
Hi,

I've noticed that each time I connect to my detached tmux session from a different computer, all the windows are marked with activity. Presumably this happens due to a resize of tmux, which again resizes the windows. The programs/shells redraw to fit the size, and all are marked as having activity.

I'd like a way to get around that, so I can see which windows *actually* have activity. Possible ways of doing this might include:

* Hooks before/after session resize that allow me to disable monitoring before resize, and reactivate it afterwards
* Lazy resizing of windows, so the window only gets resized once I move to it.

## To reproduce

* `tmux -f/dev/null`
* `tmux set -g monitor-activity on`
* `tmux set -g default-command 'exec /bin/bash --norc'` (prevent my exotic .bashrc from doing crazy stuff)
* Open a few extra windows inside screen
* Resize your terminal window

![image](https://user-images.githubusercontent.com/169057/58940850-e2a90b80-877a-11e9-9c5d-24662b91072b.png)

**Comment by nicm** [comment]
No there is no way to avoid this, tmux can't know if the program is updating because of a resize or not. It's best not to use monitor-activity with programs that redraw on resize.

**Comment by xim** [comment]
Although technically correct (the best kind of correct) there are at least two possible workarounds, as mentioned in the initial report:

>     * Hooks before/after session resize that allow me to disable monitoring before resize, and reactivate it afterwards
>     * Lazy resizing of windows, so the window only gets resized once I move to it.

**Comment by nicm** [comment]
Either would be fine with me.

**Comment by nicm** [comment]
I initially thought hooks would be easier but actually I think lazy resize might be.

You may not need to defer the entire resize, just the TIOCSWINSZ. So it is could be enough just to set a flag on windows that aren't the current window in any attached session and do the TIOCSWINSZ when it becomes current. That might not play nicely if the application does any output in the meantime, but it seems like that is a problem we already have since we already defer resizing if it happens quickly.

For hooks you will need to make sure the hooks fire before the resize happens. It would probably mean moving resize to happen from a callback on the global command queue.

**Comment by xim** [comment]
I might look into this at some point if you don't have the time / would prioritize it. Don't have time the coming weeks to dig into tmux internals, but I'll give a heads up here if I start working on it =)

**Comment by xim** [comment]
Did a quick test based on hooks. Using hooks for this might not be too great, as applications might take an arbitrary amount of time to complete resizing. Disabling notifications for e.g. a second after the start of a resize operation has a certain smell...

**Comment by xim** [comment]
Apparently, I couldn't stop thinking about the problem. Have a solution in the works. Options on how to go forward:

1. Implement an option for this (`lazy-window-resize on`)
   * `off` by default
   * `on` by default
2. Just make it default behaviour, don't add config.

I have some code that works for me (of the possibly-not-production-ready variant)

**Comment by nicm** [comment]
No new option, it needs to work by default.

**Comment by xim** [comment]
I'll just submit it as a pull req and we can take it from there
