### ISSUE TITLE
C-s and C-r default bindings do not work in tmux 3.0+ (including 3.0-rc2)

### ISSUE THREAD

**Issue by kaushalmodi** [tmux/tmux#1780]
Hello,

I had been on older tmux 2.9 until recently and I updated to tmux 3.0-rc1 and then 3.0-rc2.

After the update, I noticed that the C-r in copy-mode followed by typing the search term and then repeated C-r does not do the incremental reverse search, and the same for forward incremental search.

In the below GIF, I am first doing `C-r k` and then repeated `C-r`, and `C-r in` and then repeated `C-r`. But you can see that the search hit cursor remains stuck at the first found position.

![tmux_C-r_doesnt_work](https://user-images.githubusercontent.com/3578197/58979146-5ce98800-879b-11e9-9b42-26a1c5158f53.gif)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

```
tmux next-3.1
```

* Platform (`uname -sp`).

```
Linux unknown
```
My OS is Red Hat Enterprise Linux Workstation release 6.8 (Santiago).

* $TERM inside and outside of tmux (`echo $TERM`).
  - inside: `screen-256color`
  - outside: `xterm-256color`

* Logs from tmux (`tmux kill-server; tmux -vv new`).

I am holding off before killing the server after the recent update. Is there a way to get the required log without killing the server?

**Comment by nicm** [comment]
Yes I see this, don't worry about the log. It is odd because search-again still works and the code is basically the same.

**Comment by nicm** [comment]
I have found the problem and fixed it in OpenBSD, it will be in GitHub in an hour or so when it syncs up, then I'll merge it into the 3.0-rc branch. Thanks!
