### ISSUE TITLE
xclip running forever

### ISSUE THREAD

**Issue by drozdowsky** [tmux/tmux#1781]
### Issue description
When I copy in tmux (e.g. using mouse), on drag end there is still xclip instance running. It runs in background forever, I do not think it is proper behavior, no more than one instance is ever running but PID (of xclip) changes.
Is there any way to 'fix' this?

### Required information

```
++ oneluv ~/builds/st$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.9a
st
++ oneluv ~$ echo $TERM
st-256color
```
minimal .tmux conf:
```
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "xclip -i -sel c"
bind-key -Tcopy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -i -sel c -verbose'
set -g set-clipboard off
```

**Comment by nicm** [comment]
This is how xclip works, it doesn't exit properly.

**Comment by nicm** [comment]
You can stop it by redirecting stdout and stdin to /dev/null, so add >/dev/null 2>&1 to the xclip commands.

**Comment by drozdowsky** [comment]
Really fast response, thanks
I did:
```
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "xclip -i -sel c >/dev/null 2>&1"
bind-key -Tcopy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -i -sel c >/dev/null 2>&1'
```
```
$ pkill xclip
$ tmux source-file .tmux.conf
```
<selection with mouse>
but xclip is still running in the background

**Comment by nicm** [comment]
Does it still happen if you use xsel instead?

**Comment by drozdowsky** [comment]
Hi,
Yes. 
TIL: with my research I have found that Xorg is not storing the clipboard but the app that copied it (Xorg only has a reference), so when app exits clipboard is cleared too.
I think the solution to this is to increase upper limit of st's escape seq.
and:
`set -g set-clipboard on`
I really appreciate your help, thank you

**Comment by nicm** [comment]
Oh yeah I forgot that, it will always keep one process. The problem with it not exiting means tmux stops responding which is a different thing.

**Comment by drozdowsky** [comment]
@nicm Can I ask you one thing?
I have such script it work in interactive shell (it reads stdin & file) but it does NOT work with tmux's copy-pipe-and-cancel
I do not know if I should create another issue but it seems a bit related.

**Comment by mckellyln** [comment]
With xsel you can add a -t ms option to not continue running in the background forever.  But you can make it too small a timeout and miss an event also.  It's not really an issue to have it running like this.
But you can also modify xclip/xsel to do whatever you want.  I added to my xclip to optionally append a space for pasting to a cmd-line and some other things I like.
