### ISSUE TITLE
tmux crashing on rearranging panes (CTRL+B Space)

### ISSUE THREAD

**Issue by bgdnlp** [tmux/tmux#1783]
tmux 2.9a running on Mac, installed with MacPorts.

Steps to reproduce:
1. Start tmux
1. Split pane vertically (ctrl+b %)
1. Split right pane horizontally (ctrl+b ")
1. Go to lower right pane, do something to fill up the visible pane. Like `ls -al` a couple of times. This might not be necessary. With the terminal in full screen it didn't crash right away, but apparently it crashes if the window is small, like in the screenshot. Filling the left pane, the big one, also didn't crash it after a few tries.

<img width="697" alt="Screen Shot 2019-06-06 at 16 57 07" src="https://user-images.githubusercontent.com/4785225/59040907-4cf7a400-8880-11e9-98b3-57669a9177ac.png">

1. Rearrange panes a few times (ctrl+b space). Crashes consistently on third try, when panes should be arranged in a T shape.

* tmux version (`tmux -V`).
tmux 2.9a
* Platform (`uname -sp`).
Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`).
screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-1634.log.gz](https://github.com/tmux/tmux/files/3262058/tmux-client-1634.log.gz)
[tmux-out-1636.log.gz](https://github.com/tmux/tmux/files/3262059/tmux-out-1636.log.gz)
[tmux-server-1636.log.gz](https://github.com/tmux/tmux/files/3262060/tmux-server-1636.log.gz)

Edit: Tried a different shell (default bash and zsh), tried a different terminal (latest iTerm and terminal), restarted laptop. Same thing every time.

**Comment by ThomasAdam** [comment]
Try this on tmux from git, or the 3,0-rc2 release.

I think this is fixed.  Please reopen if not.
