### ISSUE TITLE
[Feature Request] Disabling line-wrap

### ISSUE THREAD

**Issue by MisterTicot** [tmux/tmux#1784]
The point of disabling line wrap is to be able to cleanly "preview" the first rows of a terminal output. With line wrap enabled, a 20 character width pane is a complete mess.

I use that while writing code on my netbook: left pane is the 80 characters width editor and right pane is the first 24 characters of tests or build in watch mode. This allows me to quickly notice when something is going wrong.

**Example:**
![](https://i.imgur.com/dM5rUFm.png)

I've been looking for that option on the web & the only solution I found was to do it at terminal level:

```
setterm --linewrap off
```

There's a limitation though: terminal linewrap delete content that overflow, so you can't get the full output by selecting the pane then `Ctrl-B + Z`. That's inconvenient: once an error happens, you generally want to review the full log.

I'm not sure if it is possible yet: maybe I just missed the solution. In any case, if it is not implemented yet, I think this is worth considering.

**Comment by nicm** [comment]
There is no current way to do this and I'm not sure it is a compelling feature. You could instead do something like "mycommand|tee logfile|cut -b-$COLUMNS" then just review the logfile when you see an error.

**Comment by MisterTicot** [comment]
If know about Unix commands. Unfortunately this solution doesn't fit my needs because:

1. You loose the color, which is the important information when shrinking output.
2. You need extra manipulations to get the data.

A linewrap off option in Tmux would do better.

**Comment by nicm** [comment]
I've added this to the todo list but I wouldn't expect it soon (unless you're going to write it :-)). Thanks.

**Comment by mk-pmb** [comment]
In case it helps, this sed script should limit lines to 20 bytes¹ length while preserving color. (¹ run sed with LANG=C to guard against some bugs; unfortunately I haven't found a way to deal with control chars reliably and still support multibyte characters.)

However, the script will fail if the input uses ESC chars for stuff other than color codes.

```sed
s~^(((\x1B[^A-Za-z]*[A-Za-z])*[^\x1B]){0,20}).~\1\n~
s~\n.*$~~
/\x1B/s~$~\x1B[0m~
```

I hope it helps!
