### ISSUE TITLE
copy-pipe script & window title is repeated

### ISSUE THREAD

**Issue by drozdowsky** [tmux/tmux#1787]
### Issue description
1. How to make a script that does work with copy-pipe?
For example this one does not work (it reads stdin and file):
```
#!/bin/sh
# reads stdin/file and copies it to clipboard
# clears it after 30s
exec 3<"${1:-/dev/stdin}"  # script gets stuck here: /dev/stdin : device or file not existing
cat <&3 | timeout 30 xclip -i -selection clipboard -verbose >/dev/null 2>&1 &
```
2. My window title is weirdly repeated (recursion), it looks like it contains old window titles. This does not happen on my other machine (I have the same .dotfiles but different distros & tmux version (bug occurs on older version)).
Screenshot:
![2019-06-08-124229_510x30_scrot](https://user-images.githubusercontent.com/22039170/59145987-b647f600-89eb-11e9-8533-c45f16ee55e6.png)

### Required information

```
++ oneluv ~/builds/st$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.7
st
++ oneluv ~$ echo $TERM
st
```
minimal .tmux conf:
```
set-option -g status off
set-option -g set-titles on
set-option -g set-titles-string "#S:#I:#W - \"#T\" #{session_alerts}"
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "cpb"
bind-key -Tcopy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'cpb'
set-option -g status-keys vi
set -g set-clipboard off
```

**Comment by nicm** [comment]
Does this still happen on master or 3.0-rc?

**Comment by drozdowsky** [comment]
just installed on both machines 3.0-rc
1. yes (both machines)
2. yes (only ubuntu) - I see that it happens when I enter and exit vim8 (I have neovim on void linux so maybe this is a difference)

**Comment by nicm** [comment]
With 1 probably your script is exiting prematurely, try removing the & from the end of the second line. But if that still doesn't work please open a separate issue for this.

Please show tmux logs from reproducing second problem with 3.0-rc or master.

**Comment by drozdowsky** [comment]
1. Fixed with:
```
text=`cat "${1:--}"`
echo "$text" | timeout 30 xclip -r -i -sel c -verbose >/dev/null 2>&1 &
```
Observations: 
Using "/dev/stdin" does not work, where "-" works. Bug? I had to remove redirection because it does not work with "-" (?)

2. Fixed with:
.vimrc:
`set notitle`

**Comment by nicm** [comment]
So this is all fixed now?

**Comment by drozdowsky** [comment]
If you do not treat /dev/stdin as bug this is resolved now.
You can open this anytime.
