### ISSUE TITLE
Crash after `$ tmux set-hook -gu 'pane-died[0]'`

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1788]
### Issue description

Tmux crashes after running these shell commands:

    $ tmux -Ltest -f/dev/null new
    $ tmux set-hook -gu 'pane-died[0]'

---

When a hook is triggered, tmux runs all the commands in the value of the array option with the same name. I was trying to find a command to remove one specific command out of the array, so I ran:

    $ tmux set-hook -gu 'pane-focus-out[1]'

And this made tmux crash.
As it turns out, it crashes no matter the index of the item passed to the array, and no matter the hook.
However, it doesn't seem to crash if you remove the `-g` flag passed to `set-hook`.

The command is probably wrong syntactically, but I still thought it was worth reporting something which can make tmux crash.

### Required information

 - `$ tmux -V`: tmux next-3.1
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Ltest -f/dev/null new`:
[tmux-client-1278.log](https://github.com/tmux/tmux/files/3268645/tmux-client-1278.log)
[tmux-out-1280.log](https://github.com/tmux/tmux/files/3268646/tmux-out-1280.log)
[tmux-server-1280.log](https://github.com/tmux/tmux/files/3268647/tmux-server-1280.log)
 - backtrace from `$ gdb -n -ex 'thread apply all bt full' -batch ./tmux ./core`: [backtrace.txt](https://github.com/tmux/tmux/files/3268644/backtrace.txt)

 - offending commit from `$ git bisect`: [`dfb7bb6`](https://github.com/tmux/tmux/commit/dfb7bb683057d08303955c49073f4b475bd0e2d6)

**Comment by nicm** [comment]
Fixed in OpenBSD, should be fixed in GitHub later. Thanks!
