### ISSUE TITLE
Empty lines sometimes added below the shell prompt when a file is opened in ranger

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1789]
### Issue description

To reproduce, run these shell commands:

    $ mkdir -p ~/.config/ranger/plugins/

    $ cat <<'EOF' >~/.config/ranger/plugins/plugin_fasd_log.py
    import ranger.api
    def hook_init(fm):
        def fasd_add():
            fm.execute_console("shell sleep .1")
        fm.signal_bind('execute.before', fasd_add)
    ranger.api.hook_init = hook_init
    EOF

    $ git clone https://github.com/ranger/ranger
    $ cd ranger
    $ python3 -m pip install --user --upgrade .
    $ tmux -Ltest -f/dev/null
    $ export PATH=~/.local/bin:$PATH
    $ EDITOR=nano ranger

Now that you're inside ranger, move your cursor over a text file, and press `l` to make ranger open it in nano.
Press `C-x` to quit nano, then `q` to quit ranger.
A whole screen of empty lines has been added between the old shell prompt and the new current one.
I would expect no empty lines to be added.

It only happens inside tmux, and I can reproduce on master.
I can also reproduce in various terminals: st, urxvt, xfce4-terminal, xterm.

The issue lies somewhere between [ranger](https://github.com/ranger/ranger), the [fasd integration ranger plugin](https://github.com/ranger/ranger/wiki/Integration-with-other-programs#fasd), and tmux.
It has nothing to do with the [fasd utility](https://github.com/clvv/fasd) because in the previous MWE I replaced the call to fasd with a call to `$ sleep`, and it still reproduces the issue.

I had a chat with a dev on the irc channel `#ranger`, and they told me:

 - all the fasd integration plugin does is run `fasd --add /some/path` in a subshell
 - there's nothing ranger does on purpose to add these empty lines

So, if the issue doesn't come from the terminal, nor from ranger, nor from the fasd integration plugin, all I have left is tmux.
Maybe it's some weird interaction between tmux and this ranger plugin in `~/.config/ranger/plugins/plugin_fasd_log.py`, I really don't know; but I thought you might have some idea of what is happening, and maybe how to prevent these empty lines from being added whenever I open a file in ranger + tmux.

To illustrate, here's what happens outside tmux (no empty lines added):
![gif](https://user-images.githubusercontent.com/8505073/59150931-3fcae880-8a2b-11e9-8d5d-7224d53ca8a3.gif)

And here's what happens inside tmux (whole screen of empty lines):
![gif2](https://user-images.githubusercontent.com/8505073/59150941-5cffb700-8a2b-11e9-8abf-1dc32436676b.gif)

### Required information

 - `$ tmux -V`: tmux next-3.1
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Ltest -f/dev/null new`:
[tmux-client-26925.log](https://github.com/tmux/tmux/files/3268836/tmux-client-26925.log)
[tmux-out-26927.log](https://github.com/tmux/tmux/files/3268837/tmux-out-26927.log)
[tmux-server-26927.log](https://github.com/tmux/tmux/files/3268838/tmux-server-26927.log)

**Comment by nicm** [comment]
This is because tmux does not restore the cursor when exiting the alternate screen if you are already outside the alternate screen, so the cursor is staying at the bottom of the terminal. Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3268949/x.diff.txt)

**Comment by lacygoill** [comment]
I have just test the patch, and it seems to fix the issue, thank you very much for your help.
