### ISSUE TITLE
Can no longer access hidden panes when using resize-pane -Z

### ISSUE THREAD

**Issue by sagara-** [tmux/tmux#179]
Previously (2.0), when one would invoke resize-pane -Z to hide all other panes, you could still use select-pane and tmux would cancel resize-pane -Z and switch to the proper pane; in 2.1 this is no longer the case.

I see no reference to this being intended in CHANGES, nor anything in the manpage regarding either resize-pane or select-pane, so filing this as a bug.

**Comment by dsummersl** [comment]
+1 I'm having this problem too. Can't see a way around it as there doesn't appear to be a way to explicitly 'unzoom only if zoomed'.

**Comment by nicm** [comment]
Well, you don't explain how to reproduce and selectp alone works fine for me, but I'm going to take a guess anyway and say that you are are using selectp -D, -U, -L or -R, which did not unzoom in 2.1 but are now fixed.

You can always do something like:

if -F '#{window_zoomed_flag}' 'resizep -Z; selectp -D' 'selectp -D'

**Comment by sagara-** [comment]
Ugh, my apologies. I should have checked the master branch before filling the report. Yes you're correct as to what I was referring to, and you've already fixed the issue with commit a05c27. Thank you very much.
