### ISSUE TITLE
Why the tmux don't use the environment variable "TERM"?

### ISSUE THREAD

**Issue by unihon** [tmux/tmux#1790]
tmux 3.0-rc
CentOS Linux release 7.6.1810 (Core)

---

> When the server is started, tmux copies the environment into the global environment; in addition, each session has a session environment. When a window is created, the session and global environments are merged. If a variable exists in both, the value from the session environment is used. The result is the initial environment passed to the new process.

On my host, environment variable "TERM" is "xterm-256color", but why the tmux don't use the environment variable "TERM".

![image](https://user-images.githubusercontent.com/42078581/59155932-b0264800-8ac5-11e9-85dc-03c356fba1bd.png)
▲ environment variable "TERM" is "xterm-256color"

![image](https://user-images.githubusercontent.com/42078581/59155936-c3d1ae80-8ac5-11e9-8f3d-2f39fa16121f.png)
▲ environment variable "TERM" is "screen" on tmux terminal.

![image](https://user-images.githubusercontent.com/42078581/59155950-e5329a80-8ac5-11e9-9d4e-100167ba8bd2.png)
▲ execute `show-environment -g` on tmux

![image](https://user-images.githubusercontent.com/42078581/59155953-f5e31080-8ac5-11e9-894f-f11e1f6b5246.png)
▲ execute `show-environment -s` on tmux

![image](https://user-images.githubusercontent.com/42078581/59155955-01363c00-8ac6-11e9-9e88-db573841b7fd.png)
▲ execute `show-environment ` on tmux

**Comment by nicm** [comment]
TERM is special and must be set to screen* or tmux* inside tmux. Obviously it makes no sense to copy TERM from outside tmux, tmux is not xterm, and unless you are running tmux inside tmux itself TERM outside will not be correct. You can set tmux's TERM by setting default-terminal but setting it to anything except screen or tmux or screen-256color or tmux-256color is likely to cause problems.

**Comment by krader1961** [comment]
Tmux does use the value of `$TERM`. It deliberately uses `screen` (or a variant such as `tmux` or `tmux-256color`) inside each tmux session. That allows tmux to map terminal sequences between what a program running inside a tmux session expects or emits and what the terminal attached to the seession expects.

**Comment by krader1961** [comment]
@unihon doesn't understand that one of the primary purposes of tools like `tmux` and `screen` is to allow different terminals to connect to a tmux (or screen) session and be able to correctly interact with the programs running in that session. Doing so requires mapping between the sequences sent or recognized by the external terminal and the programs running inside a tmux session. Hence the fact that `$TERM` is different inside a tmux session.

**Comment by unihon** [comment]
I have tried to use different types of terminals to attach to existing sessions, but I don't think about whether the terminal can work as expected. `tmux` and `screen` are more easily accepted by most types of terminals, so tmux deliberately uses `screen` by default...
Thanks!
