### ISSUE TITLE
Why the "[[]]" don't work on debian

### ISSUE THREAD

**Issue by unihon** [tmux/tmux#1791]
I execute the following commands on `centos` and `debian` respectively, and both are **tmux 3.0-rc**

`if-shell "[[ 'abc' == 'abc' ]]" "display-message yes"`

But `[[]]` doesn't seem to work on `debian`.

![gf](https://user-images.githubusercontent.com/42078581/59182143-90615380-8b9b-11e9-8092-f82cbf8123fc.gif)

And I excute `run-shell "[[ 'abc' == 'abc' ]]"` on `debian`, the result is as follows.

![image](https://user-images.githubusercontent.com/42078581/59182088-6e67d100-8b9b-11e9-9b2e-8ce2df781767.png)

**Comment by nicm** [comment]
if-shell always uses /bin/sh which is ash on Debian IIRC - [[ ]] is a bash extension.

**Comment by lacygoill** [comment]
Try this instead:

    $ tmux if-shell "[ 'abc' = 'abc' ]" "display-message yes"

**Comment by unihon** [comment]
`[ ]`  can work, and I also looking for ways to change the default shell If it can...

**Comment by unihon** [comment]
It seems that there is currently no support for changing the default shell for if-shell and run-shell...
If tmux can do it, you can leave a message and tell me, thanks 🙄
