### ISSUE TITLE
Can I call tmux function such as select-pane without prefix?

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#1794]
### Issue description

For instance I want switch to the specific pane 1 using `select-pane -t 1` when multiple panes exist in the current tmux window/tab like this:
~~~
bind M-1 select-pane -t 1
bind M-2 select-pane -t 2
bind M-3 select-pane -t 3
bind M-4 select-pane -t 4
...
~~~
But is it possible that I do this just using M-1/2/3/4 without hitting prefix key first?

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 2.9
* Platform (`uname -sp`). openSUSE Tumbleweed
* $TERM inside and outside of tmux (`echo $TERM`). screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by c02y** [comment]
Sorry that I did't google it first.

Use this:
~~~
bind -n M-1 select-pane -t 1
~~~
to call bindings without prefix.

**Comment by krader1961** [comment]
You also didn't bother to read the man page which says:

```
     bind-key [-nr] [-T key-table] key command [arguments]
                   (alias: bind)
             Bind key key to command.  Keys are bound in a key table.  By default (without
             -T), the key is bound in the prefix key table.  This table is used for keys
             pressed after the prefix key (for example, by default `c' is bound to
             new-window in the prefix table, so `C-b c' creates a new window).  The root
             table is used for keys pressed without the prefix key: binding `c' to
             new-window in the root table (not recommended) means a plain `c' will create
             a new window.  -n is an alias for -T root.  Keys may also be bound in custom
             key tables and the switch-client -T command used to switch to them from a key
             binding.  The -r flag indicates this key may repeat, see the repeat-time
             option.
```

**Comment by c02y** [comment]
Yeah, I'm currently busy with multiple tasks and this task came up to me all of sudden, I really didn't think that much, I only searched the issue page.

Sorry about opening this issue page, it won't happen again. @krader1961
