### ISSUE TITLE
Can't disable the mouse

### ISSUE THREAD

**Issue by grahamnicholls** [tmux/tmux#1795]
### Issue description
No matter what I put in the ~/.tmux.conf, my mouse (a laptop touchpad),  is active.  Mostly, it scrolls through the shell history, which at the very least I can't live with, but it also scrolls in vim if I run that (in character mode).

Scrolling the terminal output would be acceptable, but scrolling shell history is very dangerous behaviour - too easy to brush the touchpad and run an unintentional command.

* tmux version (`tmux -V`).
2.8 / 2.9
* Platform (`uname -sp`).
Linux x86_64 (Kubuntu 19.04)
* $TERM inside and outside of tmux (`echo $TERM`).

TERM=screen/tmux/xterm - no difference

* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-27689.log](https://github.com/tmux/tmux/files/3292063/tmux-client-27689.log)
[tmux-client-27696.log](https://github.com/tmux/tmux/files/3292064/tmux-client-27696.log)
[tmux-out-27698.log](https://github.com/tmux/tmux/files/3292065/tmux-out-27698.log)
[tmux-server-27698.log](https://github.com/tmux/tmux/files/3292066/tmux-server-27698.log)

$ cat ~/.tmux.conf
set -g prefix C-a
set -g base-index 1
unbind C-b
set -g default-terminal xterm  ( I've tried other settings)
#set -g pane-border-status top
set -g mouse off

 # splitting panes

bind | split-window -h
bind - split-window -v

 # moving between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Quick pane selection
 
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

**Comment by nicm** [comment]
This is probably a feature of your terminal, you will need to ask its
developers how to disable it.

**Comment by grahamnicholls** [comment]
Well, it only occurs when tmux is running.   Running Konsole without tmux behaves normally, so I suspect it is related to tmux.   In order to substantiate this theory, I have tried with other terminal emulators; all exhibit the same behaviour.

**Comment by nicm** [comment]
It probably only does it when the alternate screen is on and mouse is not.
This is not something tmux is doing, your terminal is sending Up and Down
keys for the mouse wheel. Does it happen in xterm?

**Comment by grahamnicholls** [comment]
Hmmm. No, in xterm it appears to put the terminal into copy mode.  What do you mean by "the alternate screen is on and mouse is not"?  Interestingly, screen seems to be exhibiting the same behaviour (I had thought that it wasn't, and that I could "downgrade").  It only happens when  running either screen or tmux, and having experimented, I agree that I think it's sending up/down keys.   Why only when running a multiplexer, though - or are you saying that both tmux and screen are responding to those keys, whereas raw konsole is not?   If that's the case, is it something I can switch off in config (or even in the code)?

**Comment by nicm** [comment]
This is something your terminal is sending, tmux can't tell the difference
between a fake Up key press from the mouse wheel or when you genuinely
press the Up key. You can configure tmux to ignore it but it will then
ignore both mouse wheel and arrow key presses.

You could try turning the mouse on in tmux and unbinding all the Mouse and
Wheel keys.

The other alternative is to use a different terminal or figure out how to
make your terminal not do this.

**Comment by grahamnicholls** [comment]
Well thanks, but I kind of realised that tmux wouldn't be able to distinguish between the two.  Since I use set -o vi to edit my command history, arrow keys are of zero use to me, so no loss.   Irrespective of whether I set -g mouse {off,on}, then mouse (with unbind left, right, up, down) scrolling puts me into copy mode.  What does set -g mouse _actually_ do?

**Comment by nicm** [comment]
You can see the default mouse keys with tmux lsk, look for Mouse and Wheel.

**Comment by nicm** [comment]
If the mouse wheel still enters copy mode, you have not managed to turn the mouse option off. Are you sure you restarted tmux completely or don't have it set in the session options?

**Comment by nicm** [comment]
Restarted completely if you only changed .tmux.conf of course. If you are changing it from the shell or command prompt then check both global and session options (set with and without -g).

**Comment by grahamnicholls** [comment]
Well, I've restarted tmux, and believe that I've switched the mouse off:
$ grep mouse .tmux.conf
set -g mouse off
grahamn@rockasus:~  ────────────────────────────────────Sat Jun 15 16:35:42]
$ ps ax | grep tmux
 6190 ?        Ss     0:00 gvim /home/grahamn/.tmux.conf
 7838 pts/6    S+     0:00 grep tmux
grahamn@rockasus:~  ───────────────────────────────────────────────────[Sat Jun 15 16:35:49]
$ tmux
[exited]

And inside tmux, the mouse scrolls through the shell history.  Outside of tmux, it moves the scroll bar.

**Comment by nicm** [comment]
I have already told you the obvious choices available to you to prevent this behaviour, you can:
- find out if your terminal has an option to disable it;
- use a different terminal that doesn't do this, like xterm, there are probably others;
- turn the mouse ON in tmux so your terminal stops sending the fake keys but unbind all the mouse and wheel keys so the mouse does nothing;
- bind Up and Down to do nothing in the root table (bind them to eg if -F "" "").

**Comment by nicm** [comment]
If you turn the mouse off in tmux, then tmux will not itself request mouse mode and has no control over what the mouse does, unless the application inside tmux also requests mouse mode in which case tmux will request it and pass on any input. This behaviour of sending fake Up and Down keys is a terminal feature and you need to configure it at the terminal. If it is off with tmux not running but on with then it must be turned on as a side effect of something else tmux requests, there is no way for tmux to control this or even know the terminal is doing it. I've mentioned a couple of possible workarounds that will let you hide the feature, the other thing you could try is:

~~~~
set -as terminal-overrides ',*:smcup@:rmcup@'
~~~~
Which will stop tmux requesting the alternate screen, which is possibly what your terminal is using to decide if it should send the fake keys. Leave mouse off in tmux for this. That's just a guess however, if it doesn't work your best bet is to ask the developers of your terminal.

**Comment by grahamnicholls** [comment]
OK, so with this all in .tmux.conf:

set -g mouse on
unbind Left
unbind Up
unbind Down 
unbind Right
unbind WheelUpPane
unbind WheelDownPane
unbind MouseDown1Pane
unbind MouseDrag1Pane
unbind MouseDragEnd1Pane
unbind WheelUpPane
unbind WheelDownPane
unbind DoubleClick1Pane
unbind TripleClick1Pane
unbind MouseDown1Pane
unbind MouseDrag1Pane
unbind MouseDragEnd1Pane
unbind WheelUpPane
unbind WheelDownPane
unbind DoubleClick1Pane
unbind TripleClick1Pane
unbind MouseDown1Pane
unbind MouseDown1Status
unbind MouseDown3Pane
unbind MouseDrag1Pane
unbind MouseDrag1Border
unbind WheelUpPane
unbind WheelUpStatus
unbind WheelDownStatus

(where all those values come from a tmux lsk | egrep -i "wheel|mouse")

Which I believe is what you suggested, and as I said, causes tmux to enter copy mode.  Last time I mentioned that, you suggested that I haven't switched mouse off properly.   BTW my email is graham@rockcons.co.uk if you want me to give any more details, etc.

**Comment by nicm** [comment]
You are missing -n (or -Troot) from these unbind commands. Look at "tmux lsk" to see what table they are bound in.

**Comment by nicm** [comment]
Mouse keys do not need the prefix key so they will mostly be in the root table.

**Comment by grahamnicholls** [comment]
For anyone else seeking to entirely disable the mouse in tmux (and who doesn't mind losing arrow keys to scroll through shell history (set o vi is much faster, anyway) ) the following (in ~/.tmux.conf) works for me:  

  1 set -g prefix C-a
  2 set -g base-index 1
  3 unbind -n C-b
  4 set -g default-terminal xterm
  5 set -g mouse on
  6 
  7 # splitting panes
  8 
  9 bind | split-window -h
 10 bind - split-window -v
 11 
 12 # moving between panes
 13 bind h select-pane -L
 14 bind j select-pane -D
 15 bind k select-pane -U
 16 bind l select-pane -R
 17 # Quick pane selection
 18 
 19 bind -r C-h select-window -t :-
 20 bind -r C-l select-window -t :+
 21 
 22 unbind -n Left
 23 unbind -n Up
 24 unbind -n Down
 25 unbind -n Right
 26 unbind -n  MouseDown1Pane
 27 unbind -n  MouseDrag1Pane
 28 unbind -n  MouseDragEnd1Pane
 29 unbind -n  WheelUpPane
 30 unbind -n  WheelDownPane
 31 unbind -n  MouseDown1Pane
 32 unbind -n  MouseDrag1Pane
 33 unbind -n  MouseDragEnd1Pane
 34 unbind -n  WheelUpPane
 35 unbind -n  WheelDownPane
 36 unbind -n  MouseDown1Pane
 37 unbind -n  MouseDown1Status
 38 unbind -n  MouseDown3Pane
 39 unbind -n  MouseDrag1Pane
 40 unbind -n  MouseDrag1Border
 41 unbind -n  WheelUpPane
 42 unbind -n  WheelUpStatus
 43 unbind -n  WheelDownStatus

Thank you for your help in this.  I know that other people will find it useful, although the loss of the use of the arrow keys may be an issue.

**Comment by nicm** [comment]
I think turning off alternate screen would also do it but then it doesn't preserve the content from outside tmux. Without an option in the terminal there is no way to disable this without losing something else .

**Comment by grahamnicholls** [comment]
Ah, sorry, was just updating my comment - what is the "alternate screen", please?

**Comment by nicm** [comment]
Alternate screen is a feature of terminals which allows full screen
applications to avoid overwriting what was on screen before they started
(it is saved and restored when exiting the alternate screen) and messing up
the scrollback (it is disabled in the alternate screen). My guess is
because the scrollback is disabled your terminal changes the wheel from
scrolling the scrollback to sending Up/Down keys. So if you disable the
alternate screen it will not do this.
