### ISSUE TITLE
ssh remote tmux always defaults to screen-256color

### ISSUE THREAD

**Issue by wltprgm** [tmux/tmux#1796]
Remote tmux version: 2.3-4
VPS: Debian 9

I tried to
```
set -g default-terminal "tmux-256color"
```
but it won't work at all. It always show $TERM "screen-256color"

I did not set $TERM in .bashrc in this remote VPS

I needed *italic* to work.

I have set up tmux `italic` to work on two machines so far, and they work great, **just to describe my experience with `tmux` so far**:

With the help of this guide: https://medium.com/@dubistkomisch/how-to-actually-get-italics-and-true-colour-to-work-in-iterm-tmux-vim-9ebe55ebc2be

One is my current laptop, with Debian Buster, tmux 2.8-3. I only `tic -x tmux-256color.terminfo` from that guide, and it works, since my `xfce4-terminal` already show `italic` by default. So I don't need `xterm-256color-italic.terminfo`. Local `.bashrc` does not set any TERM.

Another one is a jailshell on shared hosting environment, jailshell, .bashrc, following that guide, I have `tic -x` both `xterm-256color-italic.terminfo` and `tmux-256color.terminfo`, and put `export TERM=xterm-256color-italic` in `.bashrc`. This environment does not have `tmux` installed by the way. I use local `tmux` to ssh into it, so I needed to compile `tmux-256color.terminfo` in it.

**Comment by nicm** [comment]
Are you sure you restarted tmux entirely after changing .tmux.conf? If so then some shell profile must be changing it.

**Comment by lacygoill** [comment]
To test whether `$TERM` is changed by a file sourced by bash, you can try to run this:

    $ tmux neww 'bash --norc --noprofile'

`--norc` should disable `~/.bashrc` and `/etc/bash.bashrc`.
`--noprofile` should disable `/etc/profile`, `~/.bash_profile`, `~/.bash_login`, and `~/.profile`.

**Comment by lacygoill** [comment]
Another thing to consider is the value of the `'default-command'` option.
By default it's empty, which means that tmux starts a login shell, and some files specific to a login shell are sourced.
To prevent this, you can set the option with the value `$SHELL`:

    set -g default-command "$SHELL"

**Comment by wltprgm** [comment]
> Are you sure you restarted tmux entirely after changing .tmux.conf? If so then some shell profile must be changing it.

Hey, thanks for reminding me to kill all tmux. I forgot this possibility entirely.

Now I killed them, and `italic` is working already in the VPS.

And thanks @lacygoill for other information
