### ISSUE TITLE
normal user in st terminal

### ISSUE THREAD

**Issue by Jesse415** [tmux/tmux#1797]
* tmux version (`tmux -V`).
tmux 2.9a
* Platform (`uname -sp`).
Arch linux
* $TERM inside and outside of tmux (`echo $TERM`).
st-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
![pic](https://user-images.githubusercontent.com/40028171/59560469-bed8a600-9055-11e9-8356-7cf455b373da.jpg)

Every time I start tmux as a normal user I end up with that lost server and that indent. Anything I type after I can not see but I can see the output (ie. ls command does list what is in directory) I have tried google for a few days now to find the problem but have been unsuccessful. 

I have tried deleting .tmux.conf and running with no luck. Also reinstalling after uninstalling through pacman with no luck. However, it does run normally when I run $ sudo tmux. but I end up as root user. I greatly appreciate any guidance. Thank you

**Comment by nicm** [comment]
What does the server log show if you run with -vv? Kill tmux first with pkill tmux.

**Comment by Zepsylonum** [comment]
Do you have st terminfo entry? (`~/.terminfo/s/st-*`) If not and you didn't run `make install`, run `tic -sx st.info` and try again.

**Comment by Jesse415** [comment]
> 
> 
> What does the server log show if you run with -vv? Kill tmux first with pkill tmux.

when I run tmux -vv it brings up the same screen shot. I do however get tmux-client, tmux-out, and tmux-server logs. tmux-server.log has about 5101 lines. not sure what to look for in there.

**Comment by Jesse415** [comment]
> 
> 
> Do you have st terminfo entry? (`~/.terminfo/s/st-*`) If not and you didn't run `make install`, run `tic -sx st.info` in st sources directory and try again. (Assuming you didn't install it from AUR)

I did not install it using the AUR. I installed it using pacman. Upon searching there is a tmuxp pacage that I do not have installed. Not sure if that is needed or not. (described as tmux session manager. built on libtmux)

**Comment by nicm** [comment]
Right so show me the server log.

**Comment by Jesse415** [comment]
[tmux-server-2940.log](https://github.com/tmux/tmux/files/3293920/tmux-server-2940.log)

**Comment by nicm** [comment]
Nothing in the log so it must be crashing. If you do this:
~~~~
ulimit -cunlimited
tmux new
~~~~
Does it leave behind a core file?

If so, please load it until gdb and run bt full like this, then show me the output:
~~~~
gdb tmux *core*
bt full
~~~~

**Comment by Jesse415** [comment]
I ran these two commands:
> ```
> ulimit -cunlimited
> tmux new
> ```

but got nothing

**Comment by lacygoill** [comment]
According to the [archwiki](https://wiki.archlinux.org/index.php/Core_dump#Where_do_they_go?), the kernel “sends all core dumps to journald as part of the system logs”.
This should be the case if the output of `$ sysctl kernel.core_pattern` looks like `|/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e`.

To retrieve a core dump from the journal, you need to use `$ coredumpctl`.
And according to [`$ man coredumpctl`](https://jlk.fjfi.cvut.cz/arch/manpages/man/coredumpctl.1), you can run `$ coredumpctl debug` to invoke gdb on the last core dump; if that works, try running `bt full` inside gdb.

If it doesn't try one of the other commands given in the examples of the manpage:

    # list all the core dumps of the tmux program
    $ coredumpctl list tmux

    # extract the last core dump of the tmux program to a file named tmux.coredump
    $ coredumpctl -o tmux.coredump dump $(which tmux)

If nothing works, try running `$ strace`:

    $ strace -ttt -ff -ostrace.out tmux -Lx -f/dev/null new

You'll get a bunch of `strace.out.PID` files. You can group them inside an archive by running:

    $ tar -cvf strace.tar strace*

If tmux doesn't crash, remove the `-f/dev/null` part:

    $ strace -ttt -ff -ostrace.out tmux -Lx new

**Comment by Jesse415** [comment]
I was able to run $ coredumpctl debug and $ bt full. Here is what I got. Pardon my inexperience with this but I am not sure what I am looking for.

![Inkedpic-full-190618-1745-07_LI](https://user-images.githubusercontent.com/40028171/59663528-933ef280-91f2-11e9-8105-b5900d3bfaa6.jpg)
![Inkedpic-full-190618-1745-22_LI](https://user-images.githubusercontent.com/40028171/59663535-95a14c80-91f2-11e9-96c3-f7f154d3361b.jpg)

**Comment by nicm** [comment]
Oh this is the bug in the st terminfo entry, see https://github.com/tmux/tmux/issues/1593.

**Comment by Jesse415** [comment]
ok so I got it to work with this:

https://github.com/tmux/tmux/issues/1593#issuecomment-460043807

just wondering if there is or might eventually be a better way than running 

```
TERM=tmux-256color tmux
```
or should I just make a script to do so?

**Comment by nicm** [comment]
You should not run tmux like this unless you are running tmux inside tmux.

You should install a fixed st terminfo entry. Perhaps you can upgrade to
get one already, or talk to the package maintainer for your platform about
fixing the one they are installing.

**Comment by lacygoill** [comment]
FWIW, I use the terminfo description from the developer of ncurses, and st doesn't crash:

    $ curl -LO http://invisible-island.net/datafiles/current/terminfo.src.gz
    $ gunzip terminfo.src.gz
    $ tic -sx terminfo.src

**Comment by nicm** [comment]
You can use -e to tic to only compile st*, something like:
~~~~
tic -x -e st,st-256color terminfo.src

**Comment by Jesse415** [comment]
> 
> 
> FWIW, I use the terminfo description from the developer of ncurses, and st doesn't make tmux crash:
> 
> ```
> $ curl -LO http://invisible-island.net/datafiles/current/terminfo.src.gz
> $ gunzip terminfo.src.gz
> $ tic -sx terminfo.src
> ```

this definately worked. Thank you so much!
