### ISSUE TITLE
regression: can't create socket

### ISSUE THREAD

**Issue by ruv** [tmux/tmux#180]
When `tmux` is started without options it produces the following error:

    can't create socket: Permission denied

The `TMUX_TMPDIR`,`TMPDIR`, or `-L` option don't change this effect.

Although it runs normal with proper `-S` option.
This regression is observed in version 2.0 and 2.1 on Cygwin at the least.

**Comment by nicm** [comment]
Something is broken on your system, probably /tmp permissions.

-------- Original message --------

**Comment by ruv** [comment]
This issue is appeared after update of Cygwin (i.e., when tmux version was updated). So, it worked well on the previous version of tmux (I didn't remark what was the version exactly).

Also note that my Cygwin is configured to use [`noacl` option](https://cygwin.com/cygwin-ug-net/using-filemodes.html) for all the mounts. Consequently, it is impossible to get permission denied error for `/tmp`.

One possible reason is that now tmux tries to change some permissions and then checks whether they is changed. In case of `noacl` option the permissions cannot be changed. Could it be the problem for tmux?

**Comment by ruv** [comment]
I guess that the issue is in the following [code](/tmux/tmux/blob/a5e4d3a2d8c2fb288488ee5922a561a4a9e6803a/tmux.c#L146) of `makesocketpath` function:

    if (sb.st_uid != uid || (sb.st_mode & S_IRWXO) != 0) {
        errno = EACCES;
        return (NULL);
    }

The suspect commits are: d451502, e4dc156, bda970b

**Comment by nicm** [comment]
It is important that the socket directory is owned by you and not
accessible by everyone, or any user could use your tmux server. For a
while, tmux incorrectly skipped the access mode check, this was fixed in
2.0.

If your system doesn't support creating directories in /tmp with the
right ownership, you will have to use -S to point it explicitly to a
socket. The check is important and we are not going to support systems
that do not have Unix file permission semantics.

**Comment by ruv** [comment]
Thanks for clarification.
See also [workaround](/Alexpux/MSYS2-packages/pull/286) for the same issue in MSYS environment. Maybe it reasonable to introduce something like `TMUX_NOACL` environment variable for optionally skip the check in such specific cases.

**Comment by nicm** [comment]
I don't think we need anything like that, adding an environment variable
to bypass a security check is probably a poor choice. -S allows to get
around the problem in any case.
