### ISSUE TITLE
my screen seems error with tmux2.4

### ISSUE THREAD

**Issue by sddi** [tmux/tmux#1800]
With tmux2.4, sometimes, my screen shows this.
![1560848749151](https://user-images.githubusercontent.com/4221050/59680660-7ad7d380-9204-11e9-9c1b-190efae27bf1.png)

please help~~~~

**Comment by nicm** [comment]
Please provide more information.

**Comment by lacygoill** [comment]
[2.4](https://github.com/tmux/tmux/blob/master/CHANGES#L512) is more than 2 years old, a lot of issues have been fixed during that time.
Try to reproduce your issue on master; if you can, provide the information which were asked in the template when you posted your issue:

    Please provide the following information:

    * tmux version (`tmux -V`).
    * Platform (`uname -sp`).
    * $TERM inside and outside of tmux (`echo $TERM`).
    * Logs from tmux (`tmux kill-server; tmux -vv new`).
