### ISSUE TITLE
restore default xterm selection

### ISSUE THREAD

**Issue by ataiya** [tmux/tmux#1804]
I do not want tmux to interfere with the existing selection. In macOS Terminal.app, when I drag something a selection is maintained. After that you can use CMD+C for copying (see snapshot)

![Screen Shot 2019-06-20 at 3 13 50 PM](https://user-images.githubusercontent.com/4480573/59875166-0a4cc600-936e-11e9-9327-a1ef2a830581.png)

If I open a tmux within the same terminal, when I make a selection the same selection **disappears the second I lift my left mouse key**. I have attempted several variants of the following, but with no avail (respectively, stopping drag completely, or just forwarding the mouse keys to parent)
```
unbind -n MouseDrag1Pane
bind-key -T root MouseDrag1Pane send-keys -M
```

Note that **when mouse support is off, everything works as expected**
(but unfortunately I lose the ability to scroll the screen...)
```
set -g mouse off
```

Any suggestion?

### Required information
* tmux version 2.3
* Platform Darwin i386
* $TERM inside and outside of tmux #RM.

**Comment by nicm** [comment]
Some terminals let you hold down Shift or some other modifier key to bypass application mouse mode.

**Comment by ataiya** [comment]
@nicm but it seems that this should be controllable within tmux as well, as when `set -g mouse off` the behavior is the intended one? That's why I am asking the tmux gurus :)

**Comment by nicm** [comment]
No, it is not, tmux can either take over the mouse entirely or not.

**Comment by nicm** [comment]
You can turn the mouse on in tmux and then configure copy mode not to copy when you release the mouse button (change the key binding from copy-selection-and-cancel to just copy-selection, or unbind the key entirely so you have to press a key to copy).

If you want terminal selection then you need to turn the mouse off in tmux or hold down Shift or whatever other modifier your terminal supports.

**Comment by krader1961** [comment]
FWIW, I never enable mouse support in tmux. In part because I've been programming since 1978 and for most of my career mouse support by terminals was unavailable or broken. For scrolling, and searching, the tmux scrollback buffer I use a [alt-S] binding to enter copy mode:

```
bind-key -T root M-s copy-mode
# Disable mouse support. This way we can use it in the normal fashion to
# select text.
set-option -g mouse off
```

After pressing [alt-S] I then use [page-up] and [page-down], and related keys, to scroll and `/` to search.

**Comment by nicm** [comment]
The mouse is off by default :-).

**Comment by krader1961** [comment]
> The mouse is off by default :-).

Understood. Those lines in my *.tmux.conf* are to remind me why I don't enable it and make it easy to copy/paste an answer to people like the O.P. who don't seem to understand the fundamental problem with enabling it.

**Comment by ataiya** [comment]
@krader1961 sure, some of us started coding in the early 2000s :)

> You can turn the mouse on in tmux and then configure copy mode not to copy when you release the mouse button (change the key binding from copy-selection-and-cancel to just copy-selection, or unbind the key entirely so you have to press a key to copy).

@ncim This is what I was attempting to do, but I'm a bit unclear on the specifics. Do you need to just modify MouseDown1Pane for this, or is it MouseDrag1Pane, or both? Also in the existing keybindings, I do not see the "and-cancel" portion of it. Some pointers would be good :)

**Comment by nicm** [comment]
The default is:
~~~~
bind-key    -T copy-mode    MouseDragEnd1Pane     send-keys -X copy-selection-and-cancel
~~~~
You need to unbind this (unbind -Tcopy-mode MouseDragEnd1Pane) or bind it without the -and-cancel depending if you want to copy by leave the selection or not copy.

Change it in the copy-mode-vi table if you are using vi keys.

**Comment by ataiya** [comment]
Thanks!
```
unbind -T copy-mode MouseDragEnd1Pane
```
Generates the error `table copy-mode doesn't exist`

**Comment by nicm** [comment]
Your tmux is too old, I don't think you can do this in 2.3.

**Comment by ataiya** [comment]
Indeed, just tried on 2.9a, but still does not work super well.. :(
(tested in Terminal.app on macOS)

`bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection`
still makes selection disappear

`unbind -T copy-mode MouseDragEnd1Pane`
leaves the selection on screen, but CMD+C commands ignored.

I am now considering whether I should just `set -g mouse on` and find an alternative way to add scrollwheel control? I assume WheelUpPane / WheelDownPane could be configured to scroll the buffer (like it would happen with a keyboard interaction) -- but would this require mouse support to be enabled?

**Comment by nicm** [comment]
Oh yeah, sorry copy-selection without -and-cancel just doesn't exit copy mode, it still clears the selection.

You want copy-selection-no-clear but I think you will need tmux 3.0 for that.

The key to copy in tmux copy mode is C-w or M-w.

You will need to make sure your terminal supports OSC 52 and set-clipboard is on and Ms is configured in the terminfo entry (or via terminal-overrides) if you want it to set the system clipboard as well.

**Comment by nicm** [comment]
In order for tmux to do anything with the mouse, the mouse option will need to be enabled and then it will take over the mouse from the terminal.

**Comment by ataiya** [comment]
So mouse wheel events are not detected/processed when mouse is enabled?
Sigh, this seems like a lose-lose

**Comment by nicm** [comment]
You need to have realistic expectations here.

Either you can have tmux take over the mouse, in which case you get tmux's mouse configuration and key bindings and you have to use tmux to copy. tmux gets all mouse events, including the wheel, but it decides what to do with them. This means you will be able to enter the history for every pane, but you will either have to get used to the default tmux mouse configuration or spend some time learning how to configure it the way you want. Also in order for copy to work with the system clipboard you may need to do some configuration because this is not something that can work out of the box with most terminals.

Or you turn mouse off in tmux, in which case the terminal is responsible for the mouse. This means you can use the terminal to copy. However, most terminals turn off the scrollback when in full screen apps like tmux and even if they don't, tmux has no way to set the scrollback consistent, so it won't necessarily contain everything from programs inside tmux.

There is no picking and choosing between terminal and tmux, either tmux handles the mouse or it doesn't.

**Comment by ataiya** [comment]
@nicm just exploring options :)

What about a keybinding that toggles between mouse on/off?
Is `set -g mouse on` only valid on session start and cannot be changed at runtime?

This would more or less resolve it, as copy/paste only breaks once you enable mouse support.

**Comment by nicm** [comment]
That seems like something you could work out yourself pretty easily.

**Comment by ataiya** [comment]
Thanks, I was just thinking aloud; anyhow... in .tmux.conf
```
set -g mouse on
bind-key -n C-m set -g mouse on \; display-message "mouse on"
bind-key -n C-k set -g mouse off \; display-message "mouse off"
```

**Comment by lacygoill** [comment]
If you want to use the same key binding for enabling and disabling the mouse:

    set -g mouse on
    bind-key -n C-m set -g mouse \; display 'mouse: #{?#{mouse},ON,OFF}'
