### ISSUE TITLE
Alternative to #{pane_at_left} etc in tmux before 2.6 for select-pane edge wrap around

### ISSUE THREAD

**Issue by himat** [tmux/tmux#1806]
In https://github.com/tmux/tmux/issues/47 @gilgameshskytrooper provides useful tmux config commands to prevent the tmux inefficiency that doing `select-pane -L` when at the left-most pane wraps around to select the right-most pane (and similarly for the other edges).

But it uses properties like `#{pane_at_left}` which were added in tmux 2.6.
Is there a way to figure out whether a pane is at an edge in previous versions of tmux?
I use servers that have tmux 2.1 and I can't upgrade them.

**Comment by nicm** [comment]
You can probably look at pane_left etc if they existed in 2.1.
