### ISSUE TITLE
How to install tmux in path

### ISSUE THREAD

**Issue by himat** [tmux/tmux#1808]
I installed tmux on ubuntu from the 2.9a release tarball. 
And it installed fine with no errors.
But what is the proper way to link this installed tmux to my path tmux? Since if I just type `tmux` in my terminal, it uses the system tmux which is 2.1.
My system had tmux already installed at `/usr/bin/tmux` and I now have this newly built executable at `~/tmux-2.9a/tmux`.

Should I just make a softlink that overrides the `/usr/bin/tmux` and points to this local tmux 2.9a, or do I just copy `~/tmux-2.9a/tmux` into `/usr/bin/`?

Linux x86_64
system default installed tmux: tmux 2.1
xterm-256color

**Comment by lacygoill** [comment]
According to the [README](https://github.com/tmux/tmux#from-release-tarball), you should run `$ sudo make install`.

---

FWIW, I use `$ checkinstall`:

    $ sudo apt-get install checkinstall
    $ sudo checkinstall
    $ sudo checkinstall --pkgname tmux --pkgversion 2.9 --spec /dev/null ---backup=no -y

The benefit is that you get a debian package which you can manage with `apt-get`, like any regular (i.e. non-compiled) package.

Note that by default, `$ checkinstall` strips the binary from its debugging information, which greatly reduces its size but prevents you from getting a useful backtrace in case you need to report an issue related to a crash.

If that bothers you, you can prevent checkinstall from doing this by passing the `--strip=no` option:

    $ sudo checkinstall --pkgname tmux --pkgversion 2.9 --spec /dev/null ---backup=no --strip=no -y

**Comment by himat** [comment]
I did already use `sudo make install` and this was the output

```
:~/tmux-2.9a$ sudo make install
make[1]: Entering directory '/home/ubuntu/tmux-2.9a'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c tmux '/usr/local/bin'
make  install-exec-hook
make[2]: Entering directory '/home/ubuntu/tmux-2.9a'
if test xmdoc = xmdoc; then \
	sed -e "s|@SYSCONFDIR@|/etc|g" ./tmux.1 \
		>./tmux.1.mdoc; \
else \
	sed -e "s|@SYSCONFDIR@|/etc|g" ./tmux.1| \
		gawk -f ./mdoc2man.awk >./tmux.1.man; \
fi
/bin/mkdir -p /usr/local/share/man/man1
/usr/bin/install -c -m 644 ./tmux.1.mdoc \
	/usr/local/share/man/man1/tmux.1
make[2]: Leaving directory '/home/ubuntu/tmux-2.9a'
make[1]: Nothing to be done for 'install-data-am'.
make[1]: Leaving directory '/home/ubuntu/tmux-2.9a'
```

**Comment by lacygoill** [comment]
I could be wrong, but it looks like the binary was installed in `/usr/local/bin`. Is the latter directory in your `$PATH`? What's the output of `$ echo $PATH`?

**Comment by lacygoill** [comment]
Also, what's the output of `$ type -a tmux`?

**Comment by lacygoill** [comment]
If the output of `$ type -a tmux` looks like this:

    tmux is /usr/bin/tmux
    tmux is /usr/local/bin/tmux

You probably have two tmux binaries. The first one found in your `$PATH` will be used. You should probably remove the old tmux; the one you installed via `$ apt-get`.

    $ sudo apt-get purge tmux

**Comment by himat** [comment]
Oh I see you're right
```
:~/tmux-2.9a$  type -a tmux
tmux is /usr/local/bin/tmux
tmux is /usr/local/bin/tmux
tmux is /usr/local/bin/tmux
tmux is /usr/local/bin/tmux
tmux is /usr/bin/tmux
```

$PATH:
`/home/ubuntu/anaconda3/bin/:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/anaconda3/bin/:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/usr/local/mpi/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/home/ubuntu/src/cntk/bin:/usr/local/mpi/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/usr/local/mpi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

`/usr/local/bin` is in my path

**Comment by himat** [comment]
After removing the system tmux using your command
this still happens

```
ubuntu@ip-172-31-22-23:~/tmux-2.9a$ type -a tmux
tmux is /usr/local/bin/tmux
tmux is /usr/local/bin/tmux
tmux is /usr/local/bin/tmux
tmux is /usr/local/bin/tmux
ubuntu@ip-172-31-22-23:~/tmux-2.9a$ tmux -V
-bash: /usr/bin/tmux: No such file or directory
```

**Comment by lacygoill** [comment]
Try this:

    $ hash -d tmux

Or this:

    $ hash -r

See this link: https://unix.stackexchange.com/a/5610/289772

Or try to open a new shell/terminal.

**Comment by himat** [comment]
Thanks, opening a new shell fixed it!

**Comment by himat** [comment]
Thanks for all the help, I appreciate it!
