### ISSUE TITLE
Why is this not working?

### ISSUE THREAD

**Issue by budimanjojo** [tmux/tmux#1809]
Hello, I don't know if this is an issue or my own fault. But I'm trying to make a keybinding for copy-mode-vi if I have xsel installed in my system. This is the code:
```
if -b "command -v xsel > /dev/null 2>&1" " \
    bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'xsel -i -b'; \
    bind -T copy-mode-vi Y send -X copy-line; run 'tmux save-buffer - | xsel -i -b'; \
    bind -T copy-mode-vi D send -X copy-end-of-line; run 'tmux save-buffer - | xsel -i -b'; \
    bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'xsel -i -b'"
```
The problem is with `Y` and `D` where. It works only at the first time, and fails afterwards. I have to re-source my tmux config for it to work again.
Thanks before.

**Comment by nicm** [comment]
What tmux version?

**Comment by budimanjojo** [comment]
Sorry, I'm using Tmux 2.6

**Comment by lacygoill** [comment]
Not sure but try to escape the semicolons in front of the `run` commands:

    bind -T copy-mode-vi Y send -X copy-line \; run 'tmux save-buffer - | xsel -i -b'; \
                                             ^

    bind -T copy-mode-vi D send -X copy-end-of-line \; run 'tmux save-buffer - | xsel -i -b'; \
                                                    ^

**Comment by budimanjojo** [comment]
@lacygoill I tried and it still fails after first time. This is weird :(

**Comment by lacygoill** [comment]
@budimanjojo : Sorry, try to escape them twice (because of the double quotes).

**Comment by budimanjojo** [comment]
Thanks! It works. :D
