### ISSUE TITLE
I can scroll in ranger or vim, but I can not scroll in zsh!

### ISSUE THREAD

**Issue by acgtyrant** [tmux/tmux#181]
Tmux 2.1.

See my .tmux.conf or other config in https://github.com/acgtyrant/dotfiles please, thank you!

**Comment by ThomasAdam** [comment]
What do you mean by "cannot scroll in zsh" -- are you referring to using the mouse, or what?

**Comment by acgtyrant** [comment]
Using the mouse.

**Comment by nicm** [comment]
Probably your terminal pretends that scrolling the mouse wheel is the same as pressing the up and down keys but when tmux is running it stops doing this, you can make tmux do the same by adding send-keys Up to your WheelUp binding.

**Comment by acgtyrant** [comment]
No, no pretends that scrolling the mouse wheel is the same as pressing the up and down keys, because I press the up and down keys in the zsh of the termite, it only change the command in the cursor, no scroll int the termite.

However, I find I [can scroll in the copy mode instead](https://wiki.archlinux.org/index.php/Tmux#Scrolling_issues), if you do not care the bug, forget it.
