### ISSUE TITLE
crash when a pane option is set without `-g`, `-w`, `-p` in tmux.conf

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1810]
### Issue description

To reproduce, run these shell commands:

    $ echo 'set allow-rename' >/tmp/tmux.conf
    $ tmux -Lx -f/tmp/tmux.conf

It may be related to another issue which has been fixed recently.
A regression was introduced in [`c1ede50`](https://github.com/tmux/tmux/commit/c1ede507d954b98a73c40665e7aee6fe5f0c5bce), which made tmux crash when you set a window option without `-g` from your tmux.conf. I think it was fixed in [`cb5e681`](https://github.com/tmux/tmux/commit/cb5e681ef6f238a69ee6d366dd9760a49e28887b).

I also noticed that if the tmux binary is stripped from its symbols (with `$ strip`), and you don't pass `-vv` to `$ tmux`, tmux hangs instead of crashing.

### Required information

 - `$ tmux -V`: tmux next-3.1
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - [backtrace](https://github.com/tmux/tmux/files/3317451/bt.txt)

**Comment by nicm** [comment]
Nice, thanks. This is the fix (I have applied it):
~~~~
--- options.c   20 Jun 2019 18:13:04 -0000      1.51
+++ options.c   23 Jun 2019 10:00:08 -0000
@@ -784,7 +784,6 @@ options_scope_from_name(struct args *arg
                        }
                        break;
                }
-               scope = OPTIONS_TABLE_WINDOW;
                /* FALLTHROUGH */
        case OPTIONS_TABLE_WINDOW:
                if (args_has(args, 'g')) {
