### ISSUE TITLE
tmux `send-keys` very slow on FreeBSD

### ISSUE THREAD

**Issue by dgrisham** [tmux/tmux#1812]
### Issue description

`tmux send-keys` sends keys very slowly for me. Prior to this weekend, I was using `tmux` on Arch Linux (from the central repos). I use the `send-keys` command daily, and it always sent many keys virtually immediately (e.g. strings of [this size](https://github.com/dgrisham/wenv/blob/master/wenv#L154)).

I switched to FreeBSD over this weekend and installed `tmux` from the most recent ports tree (version `2.9a`). Now the `tmux send-keys` command sends much more slowly -- I have to wait a few seconds (at least) for all of the keys to finish sending to the client. This happens whether the client is running `zsh`, `bash`, or `sh`.

Obviously, the issue isn't necessarily strictly with `tmux` since it was working fine for me in Arch. I'm more looking for some guidance on how to debug this on this new system.

I made sure to test this on the most recent commit on master as well, which is reflected in the section below.

### Required information

```
$ uname -sp && tmux -V && echo $TERM
FreeBSD amd64
tmux next-3.1
xterm-256color
```

Tested by running:

```
$ tmux -Ltest kill-server
$ tmux -vv -Ltest -f/dev/null new
```

Then, in the resulting session (running `zsh`):

```
$ tmux send-keys 'echo hello this is a long enough message to show my problem here we are go go gog go go gog go'
```

That takes maybe ~2 seconds to print out. Corresponding logs (some of these logs were too big for pastebin, so I went with file.io):

`tmux-client-*.log`: https://file.io/jPswfE

`tmux-server-*.log`: https://file.io/gw9W5R

`tmux-out-*.log`: https://file.io/phyUNM

**Comment by lacygoill** [comment]
Maybe I have a network issue, but I can't read your log files, because of `404 Page not found` error.

**Comment by dgrisham** [comment]
Yeah, I just realized the files get deleted after the first download -- sorry, didn't read their docs haha. I'll get the log info on here in a different format in a few here.

**Comment by lacygoill** [comment]
If you want, you can also attach your files directly to your issue with a drag and drop.
https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

**Comment by dgrisham** [comment]
[tmux-client-38875.log](https://github.com/tmux/tmux/files/3322733/tmux-client-38875.log)
[tmux-server-38877.log](https://github.com/tmux/tmux/files/3322734/tmux-server-38877.log)
[tmux-out-38877.log](https://github.com/tmux/tmux/files/3322736/tmux-out-38877.log)

@lacygoill Perfect, thanks!

**Comment by nicm** [comment]
Does it make any difference if you do "stty speed 115200" in the pane before doing the send-keys?

**Comment by dgrisham** [comment]
@nicm looks the same to me. And, as you may have already guessed, it looks like the default speed is `9600` (based on the output of `stty speed` in a fresh shell).

**Comment by nicm** [comment]
tmux is sending all the text in a couple of hundred micros so this seems
like a libevent or freebsd problem. Can you run tmux with "ktrace -i",
reproduce the problem, then exit tmux and show me the output of "kdump"?

**Comment by dgrisham** [comment]
Sure thing -- [kdump.zip](https://github.com/tmux/tmux/files/3326816/kdump.zip)

**Comment by nicm** [comment]
Can you add -R to kdump so it has timestamps?

**Comment by nicm** [comment]
Also if possible could you do it again the same but without -vv so the logging doesn't end up in the kdump?

**Comment by dgrisham** [comment]
Done and done [kdump.zip](https://github.com/tmux/tmux/files/3326870/kdump.zip)

**Comment by krader1961** [comment]
FWIW, The `expect` utility on FreeBSD 11.1 seems to have problems with timeouts being too short. The [ksh](https://github.com/att/ast/) project had to disable all expect based unit tests on that platform and only that platform. The expect based tests work fine on OpenBSD, Linux, macOS, OpenIndiana, etc. I haven't had time (or the inclination) to dig into the `expect` source code and its behavior on FreeBSD but I would not be surprised if the two issues are related.

**Comment by nicm** [comment]
It looks to me like tmux is sending this in one go but there is too much going on with zsh and I can't see where it reads it from the pty, although it looks like it is being echoed back to tmux very quickly which doesn't make much sense if it is taking seconds for you to see it.

Could you do this again but instead of letting zsh run, can you run cat, so do something like:
~~~~
ktrace -i tmux new 'cat >/dev/null'
~~~~
Then do C-b : and paste your send-keys command at the command prompt.

Then exit tmux and show me the kdump -R for that.

**Comment by dgrisham** [comment]
Hm, it seems I was wrong -- this seems to *only* happen in `zsh`, and not `bash` or `sh`. It also worked fine with the `cat` approach you suggested, output for that one is attached.

[kdump.zip](https://github.com/tmux/tmux/files/3327359/kdump.zip)

**Comment by dgrisham** [comment]
Update: This happens only when I load `zprezto`. Just for completeness/anyone else who comes across this issue, I'll be sure to post my solution and/or link to this issue from one in the zprezto repo if it comes to that.

**Comment by dgrisham** [comment]
Turns out it's just a few zprezto modules that each slow down the input, and the aggregate is the result I mentioned here. Sorry for the noise, my initial debugging steps were a bit misguided and let me to the wrong place :)

**Comment by nicm** [comment]
OK cool.
