### ISSUE TITLE
Running htop in with tmux master segfaults htop

### ISSUE THREAD

**Issue by plewis110** [tmux/tmux#1813]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

| Requested Info | Inside | Outside |
| --- | --- | --- |
| tmux version (`tmux -V`). | `tmux next-3.1` | |
| Platform (`uname -sp`).  | `Linux x86_64` | |
| $TERM inside and outside of tmux (`echo $TERM`). | `xterm-256color` | `xterm-256color` |
| Logs from tmux (`tmux kill-server; tmux -vv new`). | | |

| Other Info | |
| --- | --- |
| Flags  | None |
| Config |  [.tmux.conf](https://gist.github.com/plewis110/e699566c2ef9d3439dd85ec6c22246cc) |
| Logs | [tmux-client-108684.log](https://gist.github.com/plewis110/9e2239bc4ef30d4c40712233e36ca481) |
|| [tmux-server-108686](https://gist.github.com/plewis110/bbf7425fcaa2befa272189ff77e4319e) |

Running latest code from repo:

```bash
> htop
zsh: segmentation fault (core dumped)  htop
>
```

**Comment by lacygoill** [comment]
Not sure whether this is related to your issue, but your report mentions that the value of `$TERM` inside tmux is `xterm-256color`.
It should be `screen`, `tmux`, or a variant (`screen-256color`, `tmux-256color`).
And according to your [tmux.conf](https://gist.github.com/plewis110/e699566c2ef9d3439dd85ec6c22246cc#file-tmux-L4):

    set -g default-terminal screen-256color

tmux should set `TERM` with the value `screen-256color`.
If that's not the value you observe, maybe zsh sources some init file which resets `TERM`.
What's the value of `$TERM` if you run:

    $ tmux neww 'zsh -f'

It should be 'screen-256color'.
Can you reproduce your issue when `TERM` has this value?

**Comment by lacygoill** [comment]
Btw, `default-terminal` is now a server option, so the right flag to pass to `set-option` is `-s` not `-g`:

    set -s default-terminal screen-256color
         ^

Although, it probably doesn't matter, because tmux should be able to infer the type of the option from its name.

From the documentation of `set-option` in `$ man tmux`:

> If the option  is not a user option,  -w or -s may be unnecessary  - tmux will
> infer the type from the option name, assuming -w for pane options.

**Comment by krader1961** [comment]
It is extremely unlikely this problem has anything to do with tmux. I run `htop` inside tmux sessions every single day. And given how tmux operates, and interacts with programs via a pty, I can't even imagine how tmux could cause htop to sigsegv. Incorrectly setting `TERM` inside a tmux session, like you did, will not cause a sigsegv failure.

@plewis110 If htop works outside of tmux on your system and consistently dies inside tmux look at differences between the environments. Starting with, but not limited to, env vars. By "not limited to" I mean that other aspects of the environment such as resource limits (look at the output of `ulimit -a`) could be the cause.

**Comment by plewis110** [comment]
> Not sure whether this is related to your issue, but your report mentions that the value of `$TERM` inside tmux is `xterm-256color`.
> It should be `screen`, `tmux`, or a variant (`screen-256color`, `tmux-256color`).
> And according to your [tmux.conf](https://gist.github.com/plewis110/e699566c2ef9d3439dd85ec6c22246cc#file-tmux-L4):
> 
>  ```
> set -g default-terminal screen-256color
> ```
> 
> tmux should set `TERM` with the value `screen-256color`.
> If that's not the value you observe, maybe zsh sources some init file which resets `TERM`.
> What's the value of `$TERM` if you run:
> 
> 
> ```
> $ tmux neww 'zsh -f'
> ```
> 
> It should be 'screen-256color'.
> Can you reproduce your issue when `TERM` has this value?

When I run 

```bash
$ tmux new 'zsh -f'
```
the `$TERM` variable is set to the correct `screen-256color`.
Also, the crash is reproducible when `$TERM` has this color.

In my `.zshrc` file, I do set the `$TERM` variable like so:

```bash
if [ -e /usr/share/terminfo/x/xterm-256color ]; then
    export TERM='xterm-256color'
else
    export TERM='xterm-color'
fi
```

**Comment by nicm** [comment]
This is an htop problem and you will need to ask the htop developers.

**Comment by plewis110** [comment]
> It is extremely unlikely this problem has anything to do with tmux. I run `htop` inside tmux sessions every single day. And given how tmux operates, and interacts with programs via a pty, I can't even imagine how tmux could cause htop to sigsegv. Incorrectly setting `TERM` inside a tmux session, like you did, will not cause a sigsegv failure.
> 
> @plewis110 If htop works outside of tmux on your system and consistently dies inside tmux look at differences between the environments. Starting with, but not limited to, env vars. By "not limited to" I mean that other aspects of the environment such as resource limits (look at the output of `ulimit -a`) could be the cause.

While you may not be experiencing the issue, that does not rule out the existence of an issue in the code of `tmux`.

Note that upgrading from a standard release of `tmux` 2.9 to the master branch caused `htop` to start crashing. I also use `htop` every day.

**Comment by plewis110** [comment]
> This is an htop problem and you will need to ask the htop developers.

So you don't think it is related to changes made in the `tmux` codebase?

**Comment by nicm** [comment]
It may well be related to changes made in tmux but a bug in tmux shouldn't make a program inside tmux crash.

**Comment by nicm** [comment]
What do you see if you strace htop?

**Comment by lacygoill** [comment]
> In my .zshrc file, I do set the $TERM variable like so:

Add a guard to prevent your code from being processed when you're inside tmux.
Maybe something like this:

    if [ -z "$TMUX" ]; then
        if [ -e /usr/share/terminfo/x/xterm-256color ]; then
            export TERM='xterm-256color'
        else
            export TERM='xterm-color'
        fi
    fi

**Comment by plewis110** [comment]
`strace htop` inside tmux output: [output.txt](https://gist.github.com/plewis110/bbf78ff9d976986cfdb69c82fb067ec9)

Another curiosity is that when `htop` segfaults it corrupts the sizing of the `tmux` window. It must be segfaulting during the configuration of the function's sizing or similar.

**Comment by plewis110** [comment]
> > In my .zshrc file, I do set the $TERM variable like so:
> 
> Add a guard to prevent your code from being processed when you're inside tmux.
> Maybe something like this:
> 
> ```
> if [ -z "$TMUX" ]; then
>     if [ -e /usr/share/terminfo/x/xterm-256color ]; then
>         export TERM='xterm-256color'
>     else
>         export TERM='xterm-color'
>     fi
> fi
> ```

Thank you, I'll do that.

**Comment by nicm** [comment]
I thought it might be getting something funny from TIOCGWINSZ but it doesn't look like it is even doing that. You are going to need to ask htop developers to help you debug this.

**Comment by plewis110** [comment]
Will do.

**Comment by lacygoill** [comment]
> Note that upgrading from a standard release of tmux 2.9 to the master branch caused htop to start crashing. I also use htop every day.

In that case, there are still 2 things which could make your report more helpful.

You could try to find the commit which introduced your issue, using [git-bisect](https://git-scm.com/docs/git-bisect).

Basically, in your local tmux repository, you run:

    $ git checkout master
    $ git bisect start
    $ git bisect bad
    $ git checkout 2.9
    $ git bisect good

*This assumes that the issue is present on master, but not on 2.9.*
From there, git should automatically checkout some commit for you.
Compile tmux, and try to reproduce your issue.
If you can't reproduce it, run `$ git bisect good`; if you can, run `$ git bisect bad`.
If you can't compile tmux on some particular commit, just run `$ git bisect skip` (this can happen several times consecutively).
Repeat the process until git tells you from which commit(s) your issue appeared.

---

You could also try to reproduce without any tmux config, by running:

    $ tmux -Lx -f/dev/null

If you can't, it means your issue is related to something in your tmux.conf.
In that case, copy your tmux.conf in `/tmp/tmux.conf` (`$ cp ~/.tmux.conf /tmp/tmux.conf`), then apply a [binary search](https://en.wikipedia.org/wiki/Binary_search_algorithm) algorithm.
Comment or delete the first half, and start tmux with:

    $ tmux -Lx -f/tmp/tmux.conf

If you can't reproduce, it means that the issue comes from the first half.
If you can, it means the issue comes from the second half.
Repeat the process on the remaining half, again and again, until you find the minimum amout of configuration necessary to reproduce.

**Comment by nicm** [comment]
My money would be on 1a9f9c09b4bcc9f99f10190ab91f1aea5206809b but it is hard to see why since the strace it doesn't even seem to fire TIOCGWINSZ.

**Comment by nicm** [comment]
Are you sure you didn't upgrade htop or ncurses at the same time? You aren't setting LD_LIBRARY_PATH for tmux are you?

**Comment by plewis110** [comment]
I am setting LD_LIBRARY_PATH, it can't find ncurses without it.

Oh my goodness, unsettting LD_LIBARY_PATH fixed it.

**Comment by plewis110** [comment]
Thank you all for the help.

**Comment by nicm** [comment]
This (libtinfo) is probably why, it must be from a different ncurses version or built with different options than the one htop was built with:
~~~~
open("/home/plewis110/src/dpkg/refroot/amd64/opt/bb/lib64/libtinfo.so.5", O_RDONLY) = 3
~~~~
