### ISSUE TITLE
Provide ability to fill background colour on full width of secondary, tertiary, etc status line rows

### ISSUE THREAD

**Issue by danemacmillan** [tmux/tmux#1815]
### Issue description

This is a feature suggestion, based on a conversation I had with @nicm on IRC. I'm jotting it down here for reference.

When the `set-option -g status 2|3|4|5` (new in 2.9+) option is set to a number, perhaps provide the ability to fill the background colour (`set-option -g status-format[1] "#[fill=colour240]"`) on full width of secondary, tertiary, etc status line rows. Right now the only way to fill the background color is to add a bunch of whitespace, or add text which likely won't span the entire width of the row. 

It was suggested to add this ability as a formatting option, à la `#[fill=colour240]`.

### Required information

* tmux version: 2.9a
* Platform: Darwin i386.
* $TERM inside and outside of tmux: screen-256color, xterm-256color

**Comment by nicm** [comment]
Try this please, against master: https://0x0.st/z2ko.diff

**Comment by danemacmillan** [comment]
The patch fails to apply:

```
ssh://vagrant@vagrant.test ~/tmp/tmux (master u=) # git apply z2ko.diff -v
Checking patch format-draw.c...
Checking patch style.c...
error: while searching for:
static struct style style_default = {
        { 0, 0, 8, 8, { { ' ' }, 0, 1, 1 } },

        STYLE_ALIGN_DEFAULT,
        STYLE_LIST_OFF,


error: patch failed: style.c:32
error: style.c: patch does not apply
Checking patch tmux.h...
Hunk #1 succeeded at 684 (offset 4 lines).
```

**Comment by nicm** [comment]
git apply is rubbish, just use patch...

**Comment by danemacmillan** [comment]
It doesn't seem to work. The new formatting option is `fill`?

Without `#[fill=colour4]`:

![](https://i.imgur.com/7E5U74m.png)

With #[fill=colour4]. It doesn't work:

![](https://i.imgur.com/i8DMmiC.png)

**Comment by nicm** [comment]
colour4 is 256 colour palette you want blue.

**Comment by danemacmillan** [comment]
I don't follow. Setting `#[fill=blue]` doesn't make it work, either.

**Comment by nicm** [comment]
It works for me. Are you sure you restarted tmux entirely?

What exactly did you put in your config?

**Comment by danemacmillan** [comment]
I recompiled again and used the binary directly from the `tmux` directory--and it works!

I previously ran `make install` as well, which I assumed would install it in my PATH, and probably did--but in retrospect it was almost certainly being ignored in favour of an overriding path entry.

I tested it on each row:

![](https://i.imgur.com/ipsiCUF.png)

**Comment by nicm** [comment]
I have applied this now. Thanks!
