### ISSUE TITLE
tmux quit autoly

### ISSUE THREAD

**Issue by gogeof** [tmux/tmux#1816]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 2.9
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): xterm
* Logs from tmux (`tmux kill-server; tmux -vv new`):
./tmux kill-server; tmux -vv new
no server running on /tmp/tmux-0/default
[exited]

[Uploading tmux-server-28414.log…]()

**Comment by gogeof** [comment]
the same result with tmux 2.9a 

after run command: tmux kill-server; tmux -vv new:

***here is the client log *** 

1561960246.605966 client started (26762): version 2.9a, socket /tmp/tmux-0/default, protocol 8
1561960246.606019 on Linux 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018; libevent 2.0.21-stable (poll)
1561960246.606090 socket is /tmp/tmux-0/default
1561960246.606110 trying connect
1561960246.606142 connect failed: Connection refused
1561960246.606162 lock file is /tmp/tmux-0/default.lock
1561960246.606221 flock succeeded
1561960246.606231 got lock (6)
1561960246.606243 trying connect
1561960246.606265 connect failed: Connection refused
1561960246.606569 add peer 0xa963e0: 7 ((nil))
1561960246.606729 sending message 100 to peer 0xa963e0 (4 bytes)
1561960246.606744 sending message 101 to peer 0xa963e0 (6 bytes)
1561960246.606749 sending message 102 to peer 0xa963e0 (11 bytes)
1561960246.606755 sending message 108 to peer 0xa963e0 (6 bytes)
1561960246.606762 sending message 104 to peer 0xa963e0 (0 bytes)
1561960246.606767 sending message 107 to peer 0xa963e0 (4 bytes)
1561960246.606773 sending message 105 to peer 0xa963e0 (21 bytes)
1561960246.606778 sending message 105 to peer 0xa963e0 (33 bytes)
1561960246.606783 sending message 105 to peer 0xa963e0 (11 bytes)
1561960246.606788 sending message 105 to peer 0xa963e0 (16 bytes)
1561960246.606793 sending message 105 to peer 0xa963e0 (14 bytes)
1561960246.606798 sending message 105 to peer 0xa963e0 (33 bytes)
1561960246.606804 sending message 105 to peer 0xa963e0 (19 bytes)
1561960246.606809 sending message 105 to peer 0xa963e0 (10 bytes)
1561960246.606814 sending message 105 to peer 0xa963e0 (1436 bytes)
1561960246.606824 sending message 105 to peer 0xa963e0 (11 bytes)
1561960246.606829 sending message 105 to peer 0xa963e0 (26 bytes)
1561960246.606835 sending message 105 to peer 0xa963e0 (65 bytes)
1561960246.606840 sending message 105 to peer 0xa963e0 (10 bytes)
1561960246.606845 sending message 105 to peer 0xa963e0 (17 bytes)
1561960246.606850 sending message 105 to peer 0xa963e0 (23 bytes)
1561960246.606855 sending message 105 to peer 0xa963e0 (8 bytes)
1561960246.606860 sending message 105 to peer 0xa963e0 (11 bytes)
1561960246.606865 sending message 105 to peer 0xa963e0 (13 bytes)
1561960246.606870 sending message 105 to peer 0xa963e0 (51 bytes)
1561960246.606876 sending message 105 to peer 0xa963e0 (35 bytes)
1561960246.606881 sending message 105 to peer 0xa963e0 (28 bytes)
1561960246.606886 sending message 105 to peer 0xa963e0 (24 bytes)
1561960246.606891 sending message 105 to peer 0xa963e0 (9 bytes)
1561960246.606909 sending message 105 to peer 0xa963e0 (23 bytes)
1561960246.606915 sending message 106 to peer 0xa963e0 (0 bytes)
1561960246.606928 cmd_pack_argv: argv[0]=new
1561960246.606934 sending message 200 to peer 0xa963e0 (8 bytes)
1561960246.606939 client loop enter
1561960246.631271 peer 0xa963e0 message 207
1561960246.631302 sending message 208 to peer 0xa963e0 (0 bytes)
1561960246.716350 peer 0xa963e0 message 203
1561960246.716366 sending message 205 to peer 0xa963e0 (0 bytes)
1561960246.716720 peer 0xa963e0 message 204
1561960246.716732 client loop exit

**Comment by arty-hlr** [comment]
@nicm Why was this closed? I have the exact same issue at the moment, and it's pretty frustrating...

Was it solved in tmux3.0? That version hasn't been pushed in arch repositories though.

**Comment by arty-hlr** [comment]
I can confirm I have the exact same issue still with tmux3.0 from github!

**Comment by nicm** [comment]
Open a proper issue then please rather than trying to hijack this one (which doesn't have any information anyway!).
