### ISSUE TITLE
Numeric key bindings not working in copy mode

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1817]
### Issue description

To reproduce, run this shell command:

    $ EDITOR=vim tmux -Lx -f/dev/null

Then press `C-b ?` to display the default key bindings in copy mode.
Finally, press `8e`.
I would expect the cursor to move on the last character of the 8th following word.
In practice, it moves on the last character of the current word.
If I press `e` a second time, right after `8e` (which gives the sequence `8ee`), then the cursor correctly moves 8 words further.

It's as if tmux had reversed the order of the keys.
That is, instead of pressing the count then the motion, it first presses the motion, then the count. Which means that the count is not applied to the motion typed right afterward, but to the second motion.
This is confirmed by the fact that if you press `8ej`, tmux moves the cursor on the last character of the current word, then 8 lines below (which matches the sequence `e8j`).

---

I can't reproduce by simply running `:send -N 8`, then pressing `e`, from copy mode.
But I can by running `:command-prompt -N -I 8 'send -N %%'`
This makes me think that the issue is related to `:command-prompt`.

The numeric key bindings still worked as expected a few months ago, and according to `$ git bisect`, it seems to be a regression introduced by [`fff85d8`](https://github.com/tmux/tmux/commit/fff85d854e7a29ab1fbf0b3867a38b52b5cf60c8).
The output of `$ git bisect` is:

    $ git bisect skip
    There are only 'skip'ped commits left to test.
    The first bad commit could be any of:
    33298d6df67e2ba3d90abdc94250eeaa963c3730
    4bb48998e075017707b0fd8d61499409bd144c6d
    5d9e591ae8ebf60bdabd9535877af96ce1ca9980
    cf6075fb29fcd86f11a1f2cc6e906c62f39d4032
    fff85d854e7a29ab1fbf0b3867a38b52b5cf60c8
    We cannot bisect more!

### Required information

 - `$ tmux -V`: tmux next-3.1
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:
[tmux-client-12157.log](https://github.com/tmux/tmux/files/3347617/tmux-client-12157.log)
[tmux-out-12159.log](https://github.com/tmux/tmux/files/3347618/tmux-out-12159.log)
[tmux-server-12159.log](https://github.com/tmux/tmux/files/3347619/tmux-server-12159.log)

---

Unrelated, but the `-N` flag of `command-prompt` is not documented.
I think it means that you can only press 1 key, and that it will not be used to replace `%%`; instead it will simply be typed after the template command has been run. But I could have misunderstood something.

**Comment by lacygoill** [comment]
Ah no, `-N` lets you press as many keys as you want, but they must all be numeric, and they're not used to replace the placeholder `%%` but as a prefix/count.

**Comment by nicm** [comment]
This seems to work OK for me.

The number does replace %% so the command is "send -N8" which sets the prefix for the next command.

**Comment by nicm** [comment]
Actually it appears maybe it doesn't work the first time you use it, only the second and subsequent times?

**Comment by lacygoill** [comment]
I think the reason why it seems to work the second time, is because tmux reverses the count and the motion.
So, if you press `8ee`, tmux presses `e8e`. The trailing `8e` is what you wanted initially, but it's still wrong.
If you press `8ej`, tmux presses `e8j`; this time the end of the sequence is `8j`, which is not what you typed initially.
Sorry if I'm not explaining things clearly, I can post 2 gifs to illustrate if you want (one before the commit broke the key bindings, one after).

**Comment by lacygoill** [comment]
For some reason, `:command-prompt` sends the count after the template command, while in the past it correctly sent it before.

**Comment by nicm** [comment]
Oh yes, I see what you mean.

command-prompt puts its command at the end of the command queue but by that time the following key press is already in the queue and it puts its command right after itself so it ends up with the command prompt command after it.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3349305/x.diff.txt)

**Comment by lacygoill** [comment]
The patch fixes the issue entirely. Thank you very much for your help.
