### ISSUE TITLE
support for box drawing characters for pane borders

### ISSUE THREAD

**Issue by ratheesh** [tmux/tmux#1818]
Not sure if this is asked before, it is possible to support box drawing Unicode characters to be used as pane borders?

**Comment by krader1961** [comment]
AFAICT (as far as I can tell) this has not been asked before: https://github.com/tmux/tmux/issues?utf8=%E2%9C%93&q=is%3Aissue+box+drawing. But what exactly do you want? Do you want to be able to specify arbitrary characters for each legacy VT100 box drawing code point? How would that work if the client did not support those code points or the width was something other than one?

**Comment by nicm** [comment]
tmux uses UTF-8 line drawing characters by default.

**Comment by ratheesh** [comment]
I was looking at an option to use different Unicode characters to draw pane borders.
Following is the unicode box drawing characters I got from https://en.wikipedia.org/wiki/Box-drawing_character
![405px-Unicode_Box_Drawings_(2500_-_27FF) svg](https://user-images.githubusercontent.com/70958/60496514-95b04a80-9cd0-11e9-821f-95c14a2f7803.png)

For example currently, the horizontal character is Unicode 0x2500 in VT100 line drawing. Is it possible to set this to 0x2550 which is double line character?
I tried creating new terminfo with modified acsc string(xterm-256color) and did not work.
I wanted to ask if this is possible.

**Comment by nicm** [comment]
You need to patch tmux like in this PR https://github.com/tmux/tmux/pull/1785.

**Comment by ratheesh** [comment]
Thank you.

**Comment by nicm** [comment]
I have added support for this and it will be in tmux 3.2 - `pane-border-lines` option.
