### ISSUE TITLE
`select-word` selects the previous word when the cursor is on the first character of a word

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1820]
### Issue description

To reproduce, run these shell commands:

    $ cat <<'EOF' >/tmp/tmux.conf
    set -gw mode-keys vi
    bind -T copy-mode-vi i switch-client -T text-object
    bind -T text-object w if -F '#{selection_present}' { send -X select-word }
    bind -T copy-mode-vi v if -F '#{selection_present}' { send -X clear-selection } { send -X begin-selection }
    EOF
    $ tmux -Lx -f/tmp/tmux.conf
    $ cat /tmp/tmux.conf

Enter copy mode, and position your cursor on the first character of a word – for example on the `b` in `begin-selection` – then press `viw`.
I would expect the text `begin-selection` to be selected, but in practice it's the previous word which is selected, here `-X`.
![gif](https://user-images.githubusercontent.com/8505073/60626974-c1285780-9dec-11e9-889d-3006f52c4564.gif)

I don't know whether this is intended, but for someone used to Vim, it's surprising, because `viw` would select `begin-selection` (or just `begin`if `-` was not in `iskeyword`).
Although, there's nothing in the manual which suggests that `select-word` is meant to behave like `viw`, I'm under the impression that it should, because as soon as the cursor is not on the first character of a word, `select-word` does behave like `viw` (if one considers that the tmux option `word-separators` is the opposite of the Vim option `iskeyword`).
![gif1](https://user-images.githubusercontent.com/8505073/60626955-b241a500-9dec-11e9-8aee-3c4bb7530a78.gif)

Would it be possible to make `select-word` select the word whose character is under the cursor, regardless of whether that character is not the first in the word?

### Required information

 - `$ tmux -V`: tmux next-3.1
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/tmp/tmux.conf`:
[tmux-client-3872.log](https://github.com/tmux/tmux/files/3356933/tmux-client-3872.log)
[tmux-out-3874.log](https://github.com/tmux/tmux/files/3356934/tmux-out-3874.log)
[tmux-server-3874.log](https://github.com/tmux/tmux/files/3356935/tmux-server-3874.log)

**Comment by lacygoill** [comment]
Actually, I found a fix. You can simply move the cursor one character to the right:

    set -gw mode-keys vi
    bind -T copy-mode-vi v if -F '#{selection_present}' { send -X clear-selection } { send -X begin-selection }
    bind -T copy-mode-vi i switch-client -T text-object
    bind -T text-object w if -F '#{selection_present}' { send -X cursor-right ; send -X select-word }

Sorry for the noise.

**Comment by nicm** [comment]
This seems like a bug.

**Comment by nicm** [comment]
Try this please: [y.diff.txt](https://github.com/tmux/tmux/files/3457099/y.diff.txt)

**Comment by lacygoill** [comment]
The patch fixes the issue, thank you very much.

**Comment by nicm** [comment]
Applied, thanks!
