### ISSUE TITLE
`append-selection` doesn't work anymore

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1821]
### Issue description

To reproduce, run these shell commands:

    $ tmux -Lx -f/dev/null
    $ tmux set -gw mode-keys vi \; bind -T copy-mode-vi y send -X append-selection
    $ echo "foo\nbar"

Enter copy mode, select 'foo', and press `y` to append the selection in a tmux buffer.
Repeat the operation on 'bar'.
I would expect tmux to have created a buffer containing 'foo' and 'bar'.
In practice, there's no buffer, as confirmed by the empty output of `$ tmux lsb`.

![gif](https://user-images.githubusercontent.com/8505073/60658715-1186d000-9e54-11e9-9057-b9429925b739.gif)

### Required information

 - `$ tmux -V`: tmux next-3.1
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/tmp/tmux.conf`:
[tmux-client-23265.log](https://github.com/tmux/tmux/files/3358823/tmux-client-23265.log)
[tmux-out-23267.log](https://github.com/tmux/tmux/files/3358824/tmux-out-23267.log)
[tmux-server-23267.log](https://github.com/tmux/tmux/files/3358825/tmux-server-23267.log)
 - offending commit from `$ git bisect`: [`6a489fa`](https://github.com/tmux/tmux/commit/6a489fa7f6360bcd9c0d6b87546d3eb6b0a3654a)

**Comment by lacygoill** [comment]
No wait, I think it works, but not like before; it needs an existing buffer, while before it didn't any buffer.
I'm not sure this is a bug.

**Comment by lacygoill** [comment]
I'm trying to implement a key binding which appends the selection (or the current line) to a buffer.
If there's no buffer, I would like one to be created automatically.
I guess I could use a format variable to test the existence of a buffer, and use `copy-selection` or `append-selection` accordingly.
Although, I prefer the old behavior (i.e. create a buffer if there's none), I'm closing the issue for now; again, sorry for the noise.

**Comment by nicm** [comment]
Are you sure this used to create a buffer if one didn't exist? The code hasn't changed. What versions?

**Comment by nicm** [comment]
append-selection still creates a buffer if there is not one already for me.

If this didn't crash (which I will fix now), it shows this:
~~~~
tmux kill-server
tmux new
tmux copy-mode \; send -X cursor-up \; send -X start-of-line \; send -X begin-selection \; send -X end-of-line \; send -X append-selection
tmux lsb
~~~~

**Comment by lacygoill** [comment]
I don't understand what happened, but I can't reproduce anymore.
I tried to reproduce like you, with scripted commands:

    $ tmux copy-mode \; send -N7 -X cursor-up \; send -X start-of-line \; send -X begin-selection \; send -X end-of-line \; send -X append-selection \; send -X cursor-down \; send -X start-of-line \; send -X begin-selection \; send -X end-of-line \; send -X append-selection

And the issue was not there.
So, I tried to reproduce with interactive commands, like in the original report, and the issue was still there:
after the commit `6a489fa`, `append-selection` didn't create a buffer anymore if there was none on the stack.

I found that weird, considering that the commit doesn't seem to alter the code of `append-selection`, so I tried in a clean environment (no Xresources, no zshrc); and the issue was still there.

Finally, I tried to recompile my installed tmux binary, and now I can't reproduce anymore.

I must have made some mistake; sorry for the confusion.

---

Unrelated to the current issue, but I've noticed that `append-selection` doesn't accept the optional `<prefix>` argument.
This means that we have no control on the name of a buffer created by `append-selection` when there's no buffer on the stack.
For this reason, I keep inspecting the exit code of `tmux showb` to use `append-selection` only if there's a buffer on the stack, and `copy-selection` otherwise; the latter supports the optional prefix argument.

    if 'tmux showb' { send -X append-selection } { send -X copy-selection 'buf_' }

**Comment by lacygoill** [comment]
Ok, I understand everything now.

> append-selection still creates a buffer if there is not one already for me.

I think you were not able to reproduce for 3 reasons:

1. your tmux must have been compiled on this commit: be5af704ad4f80a3ae77281aa617284a5a802e0e
2. you must have edited `Makefile.am`, and replace `-O2` with `-O0` (`AM_CFLAGS += -std=gnu99 -O0`)
3. you must not use `send -X` commands from the shell; instead use interactive commands like in the gif in the original post (`C-b [`, `k`, `V`, `y`, ...)

If you compile tmux with `-O0` instead of `-O2`, you should notice that the commit `be5af70` did alter the behavior of `append-selection`.
However, the very latest commit `bc112a8`, did revert back the behavior of `append-selection`, even if you compile `-O0`.

Honestly, this is such a weird issue that I doubt you would consider it as a bug, so I let it closed.

**Comment by lacygoill** [comment]
> If this didn't crash (which I will fix now), it shows this:

I think that by fixing the crash you found, you've also fixed the behavior of `append-selection`.
Thank you very much for the fix.
