### ISSUE TITLE
Mouse not working correctly with status-position top and status 2

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#1822]
### Required information

Please provide the following information:

* tmux version `tmux 2.9a`.
* Platform `Darwin i386`.
* $TERM inside and outside of tmux `screen-256`.

Issue: While the `status-position top` is set Mouse is not aligned with the line you are trying to highlight.

eg:
hello world
foobar

If I have my cursor positioned in front of `hello world` and start highlighting it actually highlights `foobar`.

However if I have the `set-option -g status-position bottom` it works fine it will highlight `hello world`.

I have following config enabled - ( I do not think its anything to do with my config since it works fine when the status-position is on bottom.
```
# Options to enable mouse support in Tmux {
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g mouse on 
unbind-key -T copy-mode-vi M-w
bind-key -T copy-mode-vi C-w send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X stop-selection
# }
set-option -g status-position top
set-option -g status 2
set-option -g status-format[1] ""

#}
```

**Comment by nicm** [comment]
Does this still happen with master or 3.0-rc?

**Comment by lanox** [comment]
I am in transit now, I will test it when I get home and report back. Thanks

**Comment by nicm** [comment]
Never mind, I missed you had status 2, I see the problem now.

**Comment by nicm** [comment]
OK I added a statuslines member to struct mouse_event but apparently forgot to actually use it. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/3361692/x.diff.txt)

**Comment by lanox** [comment]
@nicm sorry this might be silly question, I install tmux via brew, how can I apply the fix  ?

**Comment by nicm** [comment]
~~~~
git clone https://github.com/tmux/tmux.git
cd tmux
patch -p1 </path/to/x.diff.txt
sh autogen.sh
./configure && make
~~~~
Then if you want tmux in /usr/local do "make install" otherwise copy ./tmux to wherever you want it, or run it from the build directory ("./tmux new").

**Comment by lanox** [comment]
@nicm I did that however patch part has been running for 5 min now and still going.

**Comment by nicm** [comment]
It should be instantaneous, kill it. Are you sure you pointed it to the file?

**Comment by lanox** [comment]
Definitely.

1) git clone the repo to my $HOME 
2)cd to tmux
3) patch -p1 ~/Desktop/x.diff.txt

but it hangs on patch. I tried it few times.

**Comment by nicm** [comment]
You are missing < before the filename.

**Comment by lanox** [comment]
ugh to be honest  I dunno what to say that was quiet embarrassing.

anyway that kind of worked.

I got this

```
can't find file to patch at input line 8
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: cmd-resize-pane.c
|===================================================================
|RCS file: /cvs/src/usr.bin/tmux/cmd-resize-pane.c,v
|retrieving revision 1.37
|diff -u -p -r1.37 cmd-resize-pane.c
|--- cmd-resize-pane.c  3 May 2019 18:42:40 -0000       1.37
|+++ cmd-resize-pane.c  5 Jul 2019 08:02:19 -0000
--------------------------
File to patch:
```

**Comment by nicm** [comment]
Try without -p1

**Comment by lanox** [comment]
Thanks that worked. 
When would you be pushing this change to brew ?

**Comment by nicm** [comment]
I'll apply it to tmux later today, I don't know when packagers will update.

**Comment by lanox** [comment]
as always thanks so much.

**Comment by nicm** [comment]
This should be applied now, thanks!
