### ISSUE TITLE
A potential memory leak in the source file control.c

### ISSUE THREAD

**Issue by wurongxin1987** [tmux/tmux#1824]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).  2.6
* Platform (`uname -sp`).  Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

In the source file control.c, there is a potential memory leak at Line 85.  At Line 80, evbuffer_readln may return an allocated heap memory to store the char array. In most of the cases, it will be freed at Line 100. However, there is an exception case when *line == '\0', it will break the loop and the allocated heap memory is not deallocated. Although the memory leakage is very tiny, please consider to fix it. Thanks. 

![image](https://user-images.githubusercontent.com/4220002/60751915-8d1d8400-9ff0-11e9-95a2-87a59ecd48f1.png)

**Comment by nicm** [comment]
Fixed now, thanks!
