### ISSUE TITLE
A potential issue in cmd-capture-pane.c

### ISSUE THREAD

**Issue by wurongxin1987** [tmux/tmux#1825]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).  2.6
* Platform (`uname -sp`). Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).  xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

In the source file cmd-capture-pane.c, at Line 87, **_line_** may be assigned with a null pointer (Please see the following code about EVBUFFER_DATA). At Line 102, the variable **### line** with null pointer value can be passed to cmd_capture_pane_append function. Then, this null pointer may be used in the ### **memcpy**. Although the linelen is 0, it is still not recommended to use a null pointer in memcpy (Please see the discussion: https://stackoverflow.com/questions/5243012/is-it-guaranteed-to-be-safe-to-perform-memcpy0-0-0). 

![image](https://user-images.githubusercontent.com/4220002/60752075-2fd70200-9ff3-11e9-9371-d23ff110d5b0.png)

![image](https://user-images.githubusercontent.com/4220002/60752078-3796a680-9ff3-11e9-968c-0beaa9dd4a0c.png)

![image](https://user-images.githubusercontent.com/4220002/60752082-4f6e2a80-9ff3-11e9-951e-005ba0233138.png)

![image](https://user-images.githubusercontent.com/4220002/60752084-59902900-9ff3-11e9-916a-ae8e5acb212b.png)

![image](https://user-images.githubusercontent.com/4220002/60752086-60b73700-9ff3-11e9-8fc8-f5582efb8dab.png)

![image](https://user-images.githubusercontent.com/4220002/60752116-fb177a80-9ff3-11e9-9dea-f949b1d8bacd.png)

**Comment by nicm** [comment]
This is fine, I am not interested in supporting any platform where memcpy with 0 size is unsafe.
