### ISSUE TITLE
A potential NPD bug in cmd-show-messages.c

### ISSUE THREAD

**Issue by wurongxin1987** [tmux/tmux#1826]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 2.6
* Platform (`uname -sp`). Linux x86_64 
* $TERM inside and outside of tmux (`echo $TERM`). xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

In the source file cmd-show-messages.c, at Line 113, the method call to **### ctime** may return null pointer value, if msg->msg_time contains some error format of the data. Thus, the variable **### tim** might be null. If this is passed to the method call **### strchr**, it will cause a null pointer dereferences. Please see the detailed code snippets. 

![image](https://user-images.githubusercontent.com/4220002/60753144-01f8ba00-a001-11e9-8831-1a364d3628db.png)

![image](https://user-images.githubusercontent.com/4220002/60753152-10df6c80-a001-11e9-8ccf-2c006fa46e21.png)

![image](https://user-images.githubusercontent.com/4220002/60753156-1a68d480-a001-11e9-9f72-8015115a39e4.png)

![image](https://user-images.githubusercontent.com/4220002/60753161-22c10f80-a001-11e9-8f2e-724e90660a3c.png)

![image](https://user-images.githubusercontent.com/4220002/60753174-4ab07300-a001-11e9-8579-3e08180cde06.png)

![image](https://user-images.githubusercontent.com/4220002/60753230-e5a94d00-a001-11e9-8ba6-89f50a4cd781.png)

**Comment by nicm** [comment]
Thanks but this cannot happen because msg_time is set to time(NULL) which cannot return an invalid time, so ctime cannot fail.
