### ISSUE TITLE
map [ j, k ] in display-menu?

### ISSUE THREAD

**Issue by cevhyruz** [tmux/tmux#1828]
* tmux version (`tmux next-3.1`).

since display-menu supports navigation using <kbd>arrow</kbd> keys, is it possible
to map it to other keys like <kbd>j</kbd> and <kbd>k</kbd>?

**Comment by nicm** [comment]
Yes we could I suppose, try this please:
~~~~
--- menu.c      18 Jun 2019 11:08:42 -0000      1.10
+++ menu.c      8 Jul 2019 20:31:51 -0000
@@ -208,6 +208,7 @@ menu_key_cb(struct client *c, struct key
        }
        switch (event->key) {
        case KEYC_UP:
+       case 'k':
                if (old == -1)
                        old = 0;
                do {
@@ -220,6 +221,7 @@ menu_key_cb(struct client *c, struct key
                c->flags |= CLIENT_REDRAWOVERLAY;
                return (0);
        case KEYC_DOWN:
+       case 'j':
                if (old == -1)
                        old = 0;
                do {

**Comment by lacygoill** [comment]
FWIW, I wasn't able to apply the patch with `$ patch`:

    $ patch </tmp/x.diff
    patching file menu.c
    Hunk #1 FAILED at 208.
    Hunk #2 FAILED at 220.
    2 out of 2 hunks FAILED -- saving rejects to file menu.c.rej

So, I applied it manually, and it works.

Pressing `j` and `k` while a menu is displayed makes tmux select the next/previous entry.
Like the arrows, `j` and `k` wraps around the edges of the menu (e.g. if you're selecting the last entry, pressing `j` will make tmux select the first).

However, if the key shortcut of one of your item is `j` and `k`, they will be ignored; i.e. pressing `j` and `k` will still make tmux select the next/previous entry; it won't make tmux run the command bound to the item.

Which means that you can't bind an item to `j` nor `k` anymore. That would break one of my item (I use `k` to display the key bindings). I'm not sure what's the best way to tackle this issue; maybe giving the priority to the user key shortcut – in case of conflict – would be enough. I don't know.

**Comment by nicm** [comment]
Yeah try this instead: [x.diff.txt](https://github.com/tmux/tmux/files/3372233/x.diff.txt)

**Comment by lacygoill** [comment]
I've just tested the new patch, and it fixes the issue.
You can still press `j` and `k` to select the next/previous entry in the menu, but in case of conflict with a user key shortcut, the latter wins.
Thank you very much for the patch.

**Comment by nicm** [comment]
Great applied, thanks!
