### ISSUE TITLE
tmux crashes on window change

### ISSUE THREAD

**Issue by jeffwhite530** [tmux/tmux#1829]
### Issue description

I have noticed that tmux sometimes crashes when either:

1. The terminal I am using is moved from one monitor to another or,
2. The terminal is automatically moved because a monitor is shut off

The two monitors use different resolutions.  I am using konsole 17.12.3 on Ubuntu 18.04.2 LTS.

I tried compiling the latest release, 2.9a, and the issue continued.  I then compiled from the master branch at commit be5af70, the issue continued.

### Required information

* tmux version (`tmux -V`).

tmux next-3.1

* Platform (`uname -sp`).

Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).

outside: xterm-256color
inside: screen

* Logs from tmux (`tmux kill-server; tmux -vv new`).

Which of these files do you need and how to I scrub them to remove confidential information?

tmux-client-31405.log
tmux-out-31407.log
tmux-server-31407.log

Here is my .tmux.conf:
```# Change the main key to CTRL+a
unbind C-b
set -g prefix C-a

# Change panes with alt+arrows
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable CTRL+arrow to jump cursor between words
set-window-option -g xterm-keys on

set -g clock-mode-style 24

# Colors
set -g pane-border-style 'fg=#00B2E9'
set -g pane-active-border-style fg=red
set -g window-style 'bg=#333333'
set -g window-active-style 'bg=black'

# Disable the status bar
set -g status off
```

**Comment by nicm** [comment]
Show me the server log please.

**Comment by jeffwhite530** [comment]
[tmux-server-31407.log.gz](https://github.com/tmux/tmux/files/3368900/tmux-server-31407.log.gz)

**Comment by nicm** [comment]
Hmm. Can you reproduce? If you run "ulimit -cunlimited" before starting tmux for the first time (that is, before starting the tmux server), does it leave a core?

**Comment by lacygoill** [comment]
If tmux leaves a core, you can extract a backtrace from it by running:

    $ gdb -n -ex 'thread apply all bt full' -batch /path/to/tmux /path/to/core >backtrace.txt

---

If you want the backtrace to contain even more info, you can edit the file `Makefile.am`, and replace `-O2` with `-O0`. Then recompile tmux, reproduce the crash and extract the backtrace from the core left behind.

---

If tmux doesn't leave a core file, try this:

    $ gdb -q --args /path/to/tmux -Lx -f/dev/null new
    (gdb) set follow-fork-mode child
    (gdb) run
    # reproduce the crash
    (gdb) set logging on
    (gdb) bt full
    (gdb) quit

The backtrace should be in `gdb.txt`.

---

Once you have a backtrace post it here.

**Comment by jeffwhite530** [comment]
Here's the backtrace.

[backtrace.txt](https://github.com/tmux/tmux/files/3372972/backtrace.txt)

**Comment by nicm** [comment]
How easily can you reproduce? Can you run tmux in valgrind (valgrind --log-file=v.out tmux new) and reproduce and send me the valgrind log file?

**Comment by jeffwhite530** [comment]
> How easily can you reproduce?

It's random.  Might work for days, might crash multiple times a day.  I cannot trigger the crash, it just happens.  Waiting for it to crash with Valgrind now.

**Comment by jeffwhite530** [comment]
Valgrind log attached.
[v.txt](https://github.com/tmux/tmux/files/3379446/v.txt)

**Comment by nicm** [comment]
Thanks. Clearly it has got the wrong idea about the line length, but it is a bit funny because it is never complaining a bit earlier so the line must be at least 1 in length. It must be some edge case because I am not seeing it here whatever I do and nobody else seems to be seeing it either.

Are you doing anything particular when this happens or have any specific layout?

**Comment by nicm** [comment]
Could you apply this please to add some more logging: [x.diff.txt](https://github.com/tmux/tmux/files/3381612/x.diff.txt)

Then similarly run with -vv as before (don't need valgrind) and when it crashes send me the server log, or the last 100000 or so lines of it would probably do if it is very big.

Thanks

**Comment by jeffwhite530** [comment]
New Valgrind and server log attached.  This tmux was compiled from master at commit c921649 plus the logging patch.
[tmux-server-20616.log.gz](https://github.com/tmux/tmux/files/3382844/tmux-server-20616.log.gz)
[v.txt](https://github.com/tmux/tmux/files/3382845/v.txt)

**Comment by nicm** [comment]
Hmm it shouldn't really reflow when the width hasn't changed but it shouldn't crash either. It looks like tmux's notion of the available space on a line is wrong. Can you run with this instead please [y.diff.txt](https://github.com/tmux/tmux/files/3383431/y.diff.txt)? I don't need valgrind but can you do "ulimit -c unlimited" and show me the backtrace again after it crashes?

**Comment by jeffwhite530** [comment]
> Are you doing anything particular when this happens or have any specific layout?

Nope.  As I mentioned the crash happens when the screen my terminal emulator is on turns off or on and gets moved to another screen which has a different resolution.  I think in the crashes I have uploaded here I had multiple tmux windows (if that's the right term) each split into 4 quadrants.

New core and log attached.  This time I don't think the screen was turned off, tmux just died anyway.
[core.gz](https://github.com/tmux/tmux/files/3386844/core.gz)
[tmux-server-32340.log.gz](https://github.com/tmux/tmux/files/3386845/tmux-server-32340.log.gz)

**Comment by nicm** [comment]
Can you load the core into gdb and show me the backtrace please? I can't use the core file itself.

**Comment by jeffwhite530** [comment]
tmux now crashes as soon as I run Terraform (which has a large amount of output).  backtrace2.txt was from a session where I can confirm 100% that the screen did not resize at all, tmux still crashed.  At this point tmux is completely unusable.

[backtrace.txt](https://github.com/tmux/tmux/files/3386914/backtrace.txt)
[backtrace2.txt](https://github.com/tmux/tmux/files/3386917/backtrace2.txt)

**Comment by nicm** [comment]
I think I have reproduced this...

**Comment by nicm** [comment]
Yes, it will crash a lot easier now if you hit the problem because I added the assert()s to make it crash.

**Comment by nicm** [comment]
You can revert all the patches now I'll give you another one to try please in a bit.

**Comment by nicm** [comment]
Can you try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3386994/x.diff.txt)

**Comment by jeffwhite530** [comment]
There's a new problem.  tmux suddenly hung and I couldn't do anything with it.  Couldn't type a new command, couldn't CTRL+C, couldn't move between panes, opening a second tmux window hung.  I killed it with SIGILL to produce a new core, which is attached.  I had a single window open which was split horizontally.  Nothing else.

[backtrace.txt](https://github.com/tmux/tmux/files/3387238/backtrace.txt)
[tmux-server-10630.log.gz](https://github.com/tmux/tmux/files/3387241/tmux-server-10630.log.gz)

**Comment by nicm** [comment]
Was this with the most recent patch?

**Comment by jeffwhite530** [comment]
Yes, with the last x.diff.txt added to master at c921649.

**Comment by nicm** [comment]
Can you reproduce the new problem? Or the old one with the patch?

**Comment by nicm** [comment]
Any joy? I think this fix is correct so I am interested to know if it causes another problem or if that is separate.

**Comment by jeffwhite530** [comment]
I will let you know if I experience the problem again.

**Comment by nicm** [comment]
I have applied this now, thanks!

**Comment by jeffwhite530** [comment]
The hanging issue happened again.  Something with the patch from 5 days ago is causing this.  Logs attached again.

[backtrace.txt](https://github.com/tmux/tmux/files/3402451/backtrace.txt)
[tmux-server-13199.log.gz](https://github.com/tmux/tmux/files/3402452/tmux-server-13199.log.gz)

**Comment by nicm** [comment]
I don't think this patch is the cause, the backtrace is nowhere related.

Does it recover if you send signals to the tmux server? Try SIGUSR1, SIGWINCH?

Your libevent is very old, does it go away if you upgrade to a 2.x version?

**Comment by jeffwhite530** [comment]
Manually sending a SIGWINCH seems to fix it when it hangs.

**Comment by nicm** [comment]
This is probably an issue with libevent signal delivery, try a newer libevent and see if it still happens.
