### ISSUE TITLE
How to copy text to clipboard with mouse in tmux 2.1?

### ISSUE THREAD

**Issue by rightaway** [tmux/tmux#183]
Prior to tmux 2.1 copying text to the clipboard was possible by holding down Shift and the left mouse button, and selecting the text to be copied. When letting go of the left mouse button, the selected text would automatically be copied to the clipboard for pasting elsewhere.

In tmux 2.1 I can't duplicate this behavior. How do you copy text using the mouse?

**Comment by nicm** [comment]
This behaviour had nothing to do with tmux and is a feature of your terminal.

**Comment by rightaway** [comment]
I see, you're right. Actually it's still working I've realized, with a strange behavior.

Before 2.1, if I just selected text in tmux it would be highlighted in yellow (tmux higlighting). But if I held Shift and selected text, it would be higlighted in grey (terminal highlighting), and would be copied to the clipboard.

In 2.1, if I hold Shift and select text, it will be highlighted in grey (and the grey part would be copied to the clipboard), but tmux highlighting will also occur and select different lines in yellow. So what I've got is my actual selection highlighted in grey, and a few lines before and/or after my selection being randomly highlighted in yellow. Not sure if I've described this clearly.

Is there a way to not do the tmux highlighting when selecting text with Shift, as before 2.1?

**Comment by nicm** [comment]
On Thu, Nov 05, 2015 at 01:45:58AM -0800, rightaway wrote:
>    I see, you're right. Actually it's still working I've realized, with a
>    strange behavior.
> 
>    Before 2.1, if I just selected text in tmux it would be highlighted in
>    yellow (tmux higlighting). But if I held Shift and selected text, it would
>    be higlighted in grey (terminal highlighting), and would be copied to the
>    clipboard.
> 
>    In 2.1, if I hold Shift and select text, it will be highlighted in grey
>    (and the grey part would be copied to the clipboard), but tmux
>    highlighting will also occur and select different lines in yellow. So what
>    I've got is my actual selection highlighted in grey, and a few lines
>    before and/or after my selection being randomly highlighted in yellow. Not
>    sure if I've described this clearly.
> 
>    Is there a way to not do the tmux highlighting when selecting text with
>    Shift, as before 2.1?

It seems like your terminal is both selecting AND passing through the
mouse to tmux when you use Shift, this is unusual. What terminal is it?

**Comment by rightaway** [comment]
It's urxvt on archlinux `rxvt-unicode (urxvt) v9.21 - released: 2014-12-31`.

Any ideas, could it be some misconfiguration in my .tmux.conf? Or rather my .Xresources where I configure urxvt?

**Comment by nicm** [comment]
Does it work if you move your config files and try with no configs?

**Comment by rightaway** [comment]
If I remove .tmux.conf and try highlighting without shift, it works perfectly (higlights in grey and gets copied to keyboard). If I highlight with shift however, it's weird, it still highlights in grey but wherever I start the selection, it creates a big selection to that point from wherever I last clicked shift.

But there's no more yellow highlighting (tmux highlighting) that I can see. What would you suggest, should I add back parts to my .tmux.conf until I isolate what causes the problem?

**Comment by nicm** [comment]
What if you create a .tmux.conf with JUST "set -g mouse on"?

**Comment by rightaway** [comment]
Interesting, in that case I get the same problem as I originally posted.

If I start selecting text without shift, yellow highlighting appears and selects exactly what I want within the pane (rather than breaking through to adjacent panes) but unfortunately the highlighted text doesn't get copied to the clipboard.

If I start selecting text with Shift held down, then it's the same issue as before. There's overlapping grey and yellow highlighting. The grey highlighting selects exactly what I wanted to select, and gets copied to the keyboard. That's great.

But the yellow highlighting appears on top of it, and its selection continues from the previous place highlighting ended (therefore highlighting too much) and overlaps with the grey highlighting. Fortunately the yellow highlighting doesn't get copied to the clipboard, only the grey does.

**Comment by rightaway** [comment]
Also, with shift held down, the grey highlighting does break through to adjacent panes while the overlapping yellow highlighting (while still selecting too much) stays within the original pane.

**Comment by nicm** [comment]
The terminal is sending the mouse to tmux as well as doing its own
selection, this is probably wrong.

**Comment by rightaway** [comment]
Could it have something to do with the upgrade to tmux 2.1? Because when using an older version (not sure if I upgraded from 2.0 or the one before it) it works fine, even though the terminal hasn't changed.

**Comment by nicm** [comment]
In 2.1, tmux requests the terminal send it mouse input all the time if
the "mouse" option is on, in 2.0 it would request less often. Probably
it always happened but you didn't notice because tmux didn't have the
mouse enabled so often.

You can disable tmux entering copy mode when dragging by unbinding the
MouseDrag1Pane key binding.

**Comment by rightaway** [comment]
Thanks for this suggestion, I'll try it. Could you please show what command I should put in my .tmux.conf to unbind that binding? I can't find an example of unbinding actions (only keys).

**Comment by nicm** [comment]
It is a key:

unbind -n MouseDrag1Pane

**Comment by rightaway** [comment]
Thanks! Looks to work, now it only gives the grey highlighting and copies to the clipboard.
