### ISSUE TITLE
question about extra space.

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#1830]
* tmux version (`tmux next-3.1`).
* Platform (`darwin`).

I dunno if this is to do with my config but its just annoying a hell out of me. 

If you look at the pictures below

This is what its expected to be single space in between the icon
<img width="897" alt="Screen Shot 2019-07-09 at 12 38 19 am" src="https://user-images.githubusercontent.com/7599183/60819969-daae1280-a1e3-11e9-897b-22fe4bb7f1a9.png">

However this is what it looks like when I ma in directory, it seems like I get extra space at the end of a dir name.

<img width="895" alt="Screen Shot 2019-07-09 at 12 38 48 am" src="https://user-images.githubusercontent.com/7599183/60820024-f31e2d00-a1e3-11e9-955c-e0b1df63c1d7.png">

I think this is coming from` #{b:pane_current_path}` but I am not sure.
```
set-option -g status-justify left
H="/Users/apolo" # this is needed to show pane_current_path  but to ignore home dir.
set-window-option -g window-status-format "#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H},,#{b:pane_current_path}}}"
set-window-option -g window-status-current-format "#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H},,#{?#{m:$H/*,#{pane_current_path}},,}#{b:pane_current_path}}}#[fg=colour009,bold]#{?window_zoomed_flag, ,}"
```

**Comment by nicm** [comment]
window-status-separator?

**Comment by lanox** [comment]
@nicm hrm I did not have `window-status-separator` set anywhere in my config, however after exiting completely from tmux and re-arranging few things around no longer space is there, I dunno . sorry for annoyance.

**Comment by lanox** [comment]
@nicm hrm I did not have `window-status-separator` set anywhere in my config, however after exiting completely from tmux and re-arranging few things around no longer space is there, I dunno . sorry for annoyance.

**Comment by lanox** [comment]
sorry, I did not fix it, it is still there.

**Comment by krader1961** [comment]
@lanox, From the man page:

```
window-status-separator string
Sets the separator drawn between windows in the status line.
The default is a single space character.
```

If you set it to an empty string do you get the behavior you want?

**Comment by lanox** [comment]
@krader1961  thanks helping out,  no it doesn't seem like it makes any difference, this is doing my head, this is my minimal setup.

```
bind-key C-o last-window # I miss ^O^O
set -g base-index 1
setw -g pane-base-index 1
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set-window-option -g allow-rename off
set-window-option -g automatic-rename-format "#{s/zsh//:pane_current_command}"
set-window-option -g automatic-rename on
set-option -g status 2
set-option -g status-position top
set-option -g status-interval 1
bind r source-file ~/.tmux.conf \; display-message 'Reloaded ~/tmux.conf'
set-option -g status-right-length 80
set-option -g status-right "#[fg=colour244]#{?pane_dead,#{pane_dead_status} ,}#{window_index}/#{session_windows}#[fg=colour108]#[fg=colour244] #{session_name}#[fg=colour108]#[fg=colour244] #(date '+%x %H:%M')"
set-option -g status-left ''
set-option -g status-left-length 20
set-option -g window-status-activity-style bg=default
set -g window-status-separator ' '
H="/Users/apolo" # this is needed to show pane_current_path  but to ignore home dir.
set-option -g status-justify left
set -g window-status-separator ''
set-window-option -g window-status-format "#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H},, #{b:pane_current_path}}}"
set-window-option -g window-status-current-format "#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H},,#{?#{m:$H/*,#{pane_current_path}},,} #{b:pane_current_path}}}#[fg=colour009,bold]#{?window_zoomed_flag, ,}"
set-option -g status-format[1] ""
set -g window-style "bg=#3C3836"
set -g window-active-style "bg=#282828"
set-option -g status-style "fg=#bdae93,bg=#282828"
set-window-option -g window-status-style "fg=#bdae93,bg=default"
set-window-option -g window-status-current-style "fg=#fabd2f,bg=default"
set-option -g pane-border-style "fg=#504945,bg=#3C3836"
set-option -g pane-active-border-style "fg=#504945,bg=#3C3836"
set-option -g message-style "fg=#d5c4a1,bg=#3c3836"
set-option -g display-panes-active-colour "#b8bb26"
set-option -g display-panes-colour "#fabd2f"
set-window-option -g clock-mode-colour "#b8bb26"
set-window-option -g mode-style "fg=#bdae93,bg=#504945"
set-window-option -g window-status-bell-style "fg=#3c3836,bg=#fb4934"
```
this is what it looks like 
<img width="729" alt="Screen Shot 2019-07-09 at 11 05 42 am" src="https://user-images.githubusercontent.com/7599183/60852249-3905e000-a23a-11e9-89ae-5c368704ce9a.png">

I am not sure why | are overlapping ? while the first one is not ?

**Comment by lanox** [comment]
Well i have changed to multiple icons and its the same effect.

all I am trying to do it |icon|icon|

**Comment by nicm** [comment]
What terminal are you using?

**Comment by lanox** [comment]
I am using iTerm Build 3.3.20190626-nightly

**Comment by nicm** [comment]
Can you show me an example yha doesn't work without any #{}, just use text and icons?

**Comment by lanox** [comment]
sorry @nicm not sure I understand what you mean. 

Do you mean to remove all things such as #{?window_name,#{window_name}

**Comment by nicm** [comment]
Replace them with text like MYWINDOWNAME. Or you could show me the tmux
logs instead.

**Comment by lanox** [comment]
here are the logs.
[tmux-client-48689.log](https://github.com/tmux/tmux/files/3371988/tmux-client-48689.log)
[tmux-out-48691.log](https://github.com/tmux/tmux/files/3371990/tmux-out-48691.log)
[tmux-server-48691.log](https://github.com/tmux/tmux/files/3371991/tmux-server-48691.log)

**Comment by nicm** [comment]
I suspect this is to do with tmux and the terminal or font disagreeing about the width of the UTF-8 characters, but there are too many UTF-8 characters in your logs to work out which.

What exact symbol are you having trouble with? Can you create a MINIMAL example config with no #{}, for example is this correct:
~~~~
set -g status-justify left
set -g window-status-format "abc"
set -g window-status-current-format "#{E:window-status-format}"
set -g window-status-separator ''

**Comment by lanox** [comment]
here it is

```
set -g window-status-format " abc   sdfs    "
set -g window-status-current-format "#{E:window-status-format}"
set -g window-status-separator ''
```

<img width="249" alt="Screen Shot 2019-07-09 at 7 26 39 pm" src="https://user-images.githubusercontent.com/7599183/60876641-a720c600-a27f-11e9-9b96-f66990281013.png">

As yo can see in the image things dont align, I would of expected to see all equal spaces

**Comment by nicm** [comment]
Can you please show me the server log from running tmux with just those three lines in the config and then doing this inside tmux:
~~~~
tmux display -p '#{window-status-format}'

**Comment by nicm** [comment]
The block character is U+F039 which is in the PUA, probably your platform is telling tmux it is width 1 - since it is actually width 2, you will need to make sure that every occurrence of this character has a space after it yourself. You are missing a space after the last one in your window-status-format.

**Comment by lanox** [comment]
sorry for the late response I was driving home, here is the server log.

[tmux-server-51330.log](https://github.com/tmux/tmux/files/3372855/tmux-server-51330.log)

**Comment by lanox** [comment]
Hrm I am not sure if that will work so if I do this 

```
set -g window-status-format "  abc     sdfs     "
set -g window-status-current-format "#{E:window-status-format}"
set -g window-status-separator ''
```
this is what it looks like

<img width="307" alt="Screen Shot 2019-07-09 at 10 16 33 pm" src="https://user-images.githubusercontent.com/7599183/60887273-49987380-a297-11e9-8cd8-5fef540a21a1.png">

**Comment by nicm** [comment]
It looks to me like either the block character doesn't take up a full two spaces or the vertical line is not centred horizontally in the cell.
What do you see if you do this outside tmux:
~~~~
printf "|||"

**Comment by lanox** [comment]
I see this.

<img width="232" alt="Screen Shot 2019-07-09 at 11 00 54 pm" src="https://user-images.githubusercontent.com/7599183/60889891-6e8fe500-a29d-11e9-833d-9913073b865f.png">

**Comment by nicm** [comment]
Hmm looks OK, what if you  add another space:
~~~~
printf "| ||"

**Comment by lanox** [comment]
<img width="232" alt="Screen Shot 2019-07-09 at 11 00 54 pm" src="https://user-images.githubusercontent.com/7599183/60889996-ae56cc80-a29d-11e9-937d-4c2e405c7240.png">

**Comment by nicm** [comment]
That looks the same, are you sure you added the space?

**Comment by lanox** [comment]
ugh sorry wrong screenshot I need to clean up my desktop.
<img width="241" alt="Screen Shot 2019-07-09 at 11 12 18 pm" src="https://user-images.githubusercontent.com/7599183/60890641-0d691100-a29f-11e9-87a0-89670e493a9a.png">

**Comment by nicm** [comment]
OK it looks like the  character takes up about 1.5 cells not 2, so you will not be able to pad it evenly with spaces.

Even if you changed tmux to know takes up two cells it wouldn't help because your terminal will still print it aligned to the left of the first cell.

I think you will need live with this or pick a different character or use it in a different way.

**Comment by lanox** [comment]
right, no problems sorry for waisting you time,  and you are amazing in how you provide support.

**Comment by nicm** [comment]
no worries
