### ISSUE TITLE
Question/feature: last non-blank character command in copy-mode

### ISSUE THREAD

**Issue by petobens** [tmux/tmux#1831]
The `end-of-line` command in copy mode allows precisely to select/copy to the end of the line (where the cursor goes just after the last character in the line). I was wondering if it possible to add (somehow) a mapping/command to select/copy to the last non-blank character in the line (as in vim's `g_` map). Thanks!

**Comment by lacygoill** [comment]
Sorry, I'm probably confused, but doesn't `end-of-line` already does that?
I mean, for example, when my cursor is on a line with trailing spaces, inside a Vim buffer in a tmux pane in copy-mode, and I run `:send -X end-of-line`, the cursor jumps right after the last non-blank character (to include the newline).
Do you mean, that you want a mapping which would exclude the newline? That is simply move one character to the left after jumping to the end of the line?
If so, you could try this:

    bind -T copy-mode-vi g switchc -T copy-mode-vi-g
    bind -T copy-mode-vi-g _ send -X end-of-line \; send -X cursor-left

**Comment by petobens** [comment]
That does the trick indeed. Thanks @lacygoill
