### ISSUE TITLE
Sending mouse events in control mode

### ISSUE THREAD

**Issue by brads55** [tmux/tmux#1832]
When using control mode it doesn't seem to be possible to properly send mouse events with large (>0x7f) coordinates (CSI M CbCxCy in particular, however it affects most mouse events with coordinates, when using the default X10 encodings for the coordinates).

This is because the control sequences for such an event contain bytes >0x7f which get re-encoded as UTF-8 (https://github.com/tmux/tmux/blob/master/input-keys.c#L187), producing invalid control sequences.

An example of this:

`send-keys 0x001b 0x005b 0x004d 0x0020 0x0080 0x0021`

Gives:

`1b 5b 4d 20 c2 80 21`

It would be great if there was a way to use send-keys without UTF-8 encoding the keys. (Apologies if there is another way of doing this I couldn't see what it would be, and it seems iTerm2 also falls foul of this issue).

**Comment by nicm** [comment]
I think it would be more useful if there was a way to pass x,y,b to tmux and it would send the appropriate mouse sequence to the application.

**Comment by brads55** [comment]
That would also work, perhaps not ideal for my use case as it means I now need to intercept and interpret control sequences rather than just passing them straight through, but I can see how this is more generally useful.

**Comment by nicm** [comment]
Yeah I was just thinking that, it would be easier to add a way to pass through anyway.

**Comment by nicm** [comment]
Bit more complicated than I thought because keys are always Unicode so we need a flag to say that they aren't. Please try this, you can use two -l (send-keys -ll) to send literal keys rather than UTF-8: [x.diff.txt](https://github.com/tmux/tmux/files/3372954/x.diff.txt)

**Comment by brads55** [comment]
It's possible that I'm missing something here, but this doesn't seem to work. Upon sending any key > 0x7f tmux ends up just sending 0x3f to the client.

(Using ``send-keys -ll -t %0 [M �.`` for example. Also it might be nicer if this could be done using hex values rather than literal characters).

Additionally, using $ in the command results in:

```
--> send-keys -ll $
<-- %begin 1562678448 922 1
<-- parse error: invalid or unknown command: send-keys -ll $
<-- %error 1562678448 922 1
```

**Comment by nicm** [comment]
You will need to quote $ of course.

Does it help if you add a (u_char) cast to the assignment in input_key:
~~~~
        if (key & KEYC_LITERAL) {
                ud.data[0] = (u_char)key;
                bufferevent_write(wp->event, &ud.data[0], 1);
                return;
        }

**Comment by nicm** [comment]
Hex would be better, I'll take a look.

**Comment by brads55** [comment]
Turns out I was missing something, I had a stale tmux server running..

Regardless, I'm finding that with the current master, even without this patch, send-keys doesn't seem to be doing anything at all, i.e. the clients are not responding at all, has something changed with the way send-keys works since 2.8?

**Comment by nicm** [comment]
No send-keys definitely works.

**Comment by nicm** [comment]
This accepts -H and each argument must then be a hex number which is sent [y.diff.txt](https://github.com/tmux/tmux/files/3373278/y.diff.txt).
~~~~
$ ./tmux send -H 44 55 66; cat
DUf
~~~~

**Comment by nicm** [comment]
It works for me:
~~~~
$ ./tmux -Ltest -C new
%begin 1562680303 252 0
%end 1562680303 252 0
%window-add @0
%sessions-changed
%session-changed $0 0
%window-renamed @0 tmux
%output %0 nicholas@yelena:~/tmux/OpenBSD/tmux$
send -H 44 a
%window-renamed @0 ksh
%begin 1562680308 259 1
%end 1562680308 259 1
%output %0 D
%output %0 \015\015\012
%output %0 ksh: D: not found\015\012
%output %0 nicholas@yelena:~/tmux/OpenBSD/tmux$
~~~~

**Comment by brads55** [comment]
Turns out I had something in an old tmux config that was breaking things, no idea what. But yes this patch works like a charm and is much cleaner as hex, thanks very much :)

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
