### ISSUE TITLE
Feature request: Filter %output from control mode

### ISSUE THREAD

**Issue by zdykstra** [tmux/tmux#1834]
I've written a tool that uses/abuses control mode and session groups. It's nominally used to break windows out from local or remote sessions into individual terminals. Because of how the tool works, I don't use/consume the `%output` line from the control mode feed. Instead, I create session groups and attach a tmux instance with a specific window in focus. 

I'd like to add a flag/option to allow filtering of `%output` lines in tmux, before they reach the control mode output.  The motivation for this is to try to reduce the amount of network traffic that is produced when this is run through SSH.  However, before I attempt this patch, I'd like to confirm that upstream would even consider merging it.

[tmuxc](https://github.com/zdykstra/tmuxc/) is the tool in question that could benefit from this proposal.

**Comment by ThomasAdam** [comment]
Hi,

I’d hope not.  Control mode I about representing the state of tux, and eliding parts as you’re suggesting would be confusing.  By all means filter it out if it’s not useful to your tmuxc program.

— Thomas Adam

**Comment by zdykstra** [comment]
I don't see how it'd be confusing. There aren't many tools actually utilizing control mode, and those that are don't stumble there by accident.  I'm not suggesting changing the default operation mode, but simply adding a feature flag to `-C` to accomplish this.

I obviously currently filter it after I receive it over the wire - I'd just like to avoid sending it over SSH if possible.

**Comment by nicm** [comment]
I would be open to a flag to refresh-client to set flags for control mode
(like "refresh-client -L no-output").

**Comment by nicm** [comment]
I think it would often be nice to do without %output, also a flags mechanism would let us make other changes to the protocol without necessarily breaking iterm2.

**Comment by zdykstra** [comment]
I'll see if I can make any progress on doing it through the refresh-client mechanism. I'll run a branch through here for early review if I can get something functional. Thanks!

> I think it would often be nice to do without %output, also a flags mechanism would let us make other changes to the protocol without necessarily breaking iterm2.

**Comment by nicm** [comment]
There is no mechanism at the moment, I mean you will need to add one.

**Comment by zdykstra** [comment]
Right. The `refresh-client` command exists - which is what I was going to start extending.

**Comment by ThomasAdam** [comment]
You could try the attached patch.

I haven't tested it, I've only checked it compiles.
[x.diff.txt](https://github.com/tmux/tmux/files/3374735/x.diff.txt)

**Comment by zdykstra** [comment]
The supplied patch seems to work correctly after a brief round of testing!  I applied the patch to the current head of tmux, and pointed my tmuxc tool to it with a modification to not skip `%output` but instead print it. 

As expected on startup, the normal control mode operation is there. All `%output` and other lines are present. When I change the mode via:

`tmux refresh-client -F no-output -t $( tmux lsc | grep "session-control" | cut -d : -f 1 )` 

no further `%output% lines show up in my control mode session.  I can provide more detailed output if that's required, otherwise this appears to do exactly what is needed.

**Comment by nicm** [comment]
Applied with some minor changes, thanks!
