### ISSUE TITLE
Is there a way to specify META key?

### ISSUE THREAD

**Issue by banderlog** [tmux/tmux#1835]
* tmux version: 2.6
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color

I am running i3 windows manager with a lot of keybindings containing Alt key. From it I am running tmux and I am unable to use any default M-smth keybindings. Thus I have to rebind every keybinding with META key or redefine META key for tmux.

From [CHANGES](https://github.com/tmux/tmux/blob/a0e2c1b4cae9269d04ee2e80e1d1cb8adc78cd8a/CHANGES):
>20 September 2007
>
>* Specify meta via environment variable (META).

But no instructions, what I have to pass to this env var. I tried passing keycode (grepped via xev) and  just keyname but it did not work.

Is this feature still working? Could I redefine META for tmux? How I could do this?

**Comment by nicm** [comment]
This is not from the tmux CHANGES file.

You can't specify the Meta key in tmux itself, you need to do it in your terminal or in X (xmodmap).

**Comment by nicm** [comment]
Oh sorry it is from the CHANGES file. That didn't mean the meta key as in M-x, M-y it meant what is now called the prefix key (C-b).

**Comment by banderlog** [comment]
OK, thanks for reply
