### ISSUE TITLE
copy-pipe puts wrong data into clipboard

### ISSUE THREAD

**Issue by purpleP** [tmux/tmux#1837]
I have this issue for a while now (like half a year I think). I'm on ubuntu 19.04 on latest master of tmux  `c9216493cfa3b62b6edc9dae11892a071e56fa5c`

```
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe 'xclip -in -selection clipboard'
```
If I use `copy-pipe-and-cancel` the pasted text is correct.

```
echo $TERM
xterm-256color
```

**Comment by nicm** [comment]
What is wrong about it? Do you have set-clipboard on as well?

**Comment by purpleP** [comment]
@nicm No I don't have `set clipboard on`. I don't think I can see pattern clearly but I guess it uses wrong selection and also it seems to maybe append to clipboard instead of replacing content, I don't know...

**Comment by nicm** [comment]
Are you sure set-clipboard is off? It defaults to on, and double or
truncated clipboard is a common symptom. What does "tmux show -g
set-clipboard" show?

**Comment by purpleP** [comment]
Oh, then it must be on. I'll check.

сб, 13 июл. 2019 г., 11:13 Nicholas Marriott <notifications@github.com>:

> Are you sure set-clipboard is off? It defaults to on, and double or
> truncated clipboard is a common symptom. What does "tmux show -g
> set-clipboard" show?
>

**Comment by purpleP** [comment]
@nicm 
```
$ tmux show -g set-clipboard
unknown option: set-clipboard
```
and after experimenting I can see that everything works properly after adding `set -g set-clipboard off`

**Comment by nicm** [comment]
SOrry it is a server option so -s not -g

**Comment by purpleP** [comment]
That's default on my machine right now.
```
$ tmux show -s set-clipboard
set-clipboard external
```

**Comment by nicm** [comment]
Yes the problem is that if set-clipboard is enabled and working then both the terminal and xclip will try to set the clipboard. Often this is harmless but with some terminals it can work incorrectly. It is best to turn set-clipboard off if you are using a separate tool to update the clipboard from tmux.
