### ISSUE TITLE
Cannot bind C-h

### ISSUE THREAD

**Issue by Jorengarenar** [tmux/tmux#1838]
As in title. No matter what, I am unable to bind C-h to anything, be it inside .tmux.conf or by command.

**Most minimal _.tmux.conf_**
```tmux
bind-key -n C-h select-pane -L
```
and results from `list-keys`:
```sh
$ tmux list-keys | grep C-h
bind-key    -T copy-mode-vi C-h               send-keys -X cursor-left
bind-key    -T root         C-h               select-pane -L
```
Looks fine, but in normal mode, the first binding also takes place, and moves cursor left (I've checked it by inserting few spaces and then pressing C-h).

---
### Specs

OS: Arch Linux (_5.2.0-arch2-1-ARCH_)
Terminal: XTerm (347)

```sh
$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.9a
screen-256color
```
```sh
$ tmux -V
tmux 2.9a
```
```sh
$ echo $TERM
screen-256color
```

**Comment by nicm** [comment]
C-h is Backspace try binding that (BSpace) instead.

**Comment by Jorengarenar** [comment]
Indeed, now it works, but I cannot use backspace button normally.
What can I do to use [vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator) without changing its default key mapping?

**Comment by nicm** [comment]
Most terminals send ^? for backspace now for this reason, you can configure
your xterm to do this too, look for xterm options (may also need to change
VERASE with stty).

**Comment by nicm** [comment]
Looks like you want to set backarrowKey to false in Xresources/Xdefaults.

**Comment by Jorengarenar** [comment]
This in .Xresources solved problem:
```xdefaults
XTerm*ttyModes:         erase ^?
XTerm*VT100.Translations: \
        #override <Key>BackSpace: string(0x7f) \n\
		  <Key>Delete:    string(0x1b) string("[3~")
```

I would never guess this was the issue. Thank you for help
