### ISSUE TITLE
Windows loose zoom when swapping panes

### ISSUE THREAD

**Issue by net** [tmux/tmux#1839]
swap-pane causes the involved windows to reset their zoom. This is jarring and frustrating when working on a zoomed pane. I believe a more preferable behavior would be to maintain each window's zoom status—similar to how swapped panes adapt to their new windows' layouts.

**Comment by lacygoill** [comment]
It's on the [TODO list](https://github.com/tmux/tmux/wiki/Contributing#small-things):

> It would be good if select-pane had a -Z flag to preserve zoom state (if already zoomed, stay zoomed).

In the meantime, you can inspect the `#{window_zoomed_flag}` format to preserve the zoom state of the window.

As an example, to make `;` – which is bound to `last-pane` by default – zoom the last pane after focusing it:

    bind ';' if -F '#{window_zoomed_flag}' 'last-pane ; resize-pane -Z' 'last-pane'

**Comment by net** [comment]
@nicm what’s the verdict? The item on the todo list is for select-pane, not swap-pane. Those two commands, in my mind, have slightly different behavioral expectations.

**Comment by nicm** [comment]
If we do one we can do them all.

**Comment by net** [comment]
👍🏼

**Comment by nicm** [comment]
last-pane is the same as select-pane. I think select-pane, join-pane, swap-pane, break-pane and perhaps kill-pane.

I would add an API so you could do something like `state = server_push_zoom(w, args_has(args, 'Z'));` at the start of each where it currently calls `unzoom_window` and `server_pop_zoom(w, state);` at the end.

I am on the fence if we need a -Z flag or this should just be the default. I think it makes sense to unzoom for select-pane so it would need a -Z flag, but the others I'm not so sure.

**Comment by nicm** [comment]
Try this please, select-pane and swap-pane only for the moment: [tmux-zoom.diff.txt](https://github.com/tmux/tmux/files/3457454/tmux-zoom.diff.txt)

**Comment by net** [comment]
Thanks, that works well!

I suggest that zoom-preservation is a better default for select-pane and especially for swap-pane. 

Unzooming is a trivial action to be performed separately if desired. Most often, a user who needs to unzoom when performing these actions will need to unzoom *before* the action because they will use context from the visible panes in their action—e.g. they need to know which pane to swap with; if the user has not unzoomed when they perform the action, it is reasonable to assume they wish to preserve their zoomed state. If the user then does proceed to unzoom, it is because they wished to perform the action *and* to unzoom, not because the action itself necessitates unzooming. We would not make split-window a default action performed on switch-window, even though there are many times those actions are performed together.

A system where each command does only one thing is cleaner. The visual change when zooming is jarring, especially when it occurs unprompted.

Of course, the question of defaults is not as important for scripting where additional commands or flags are happily used.

Either way, as long as the flag is present, the tmux user can customize their environment to their liking.

**Comment by nicm** [comment]
This [tmux-Z.diff.txt](https://github.com/tmux/tmux/files/3472462/tmux-Z.diff.txt) does rotate-window and switch-client as well. The other pane commands (join-pane, break-pane, kill-pane, resize-pane, split-window) all change the layout in some way so I don't think a -Z flag is useful.

**Comment by lacygoill** [comment]
FWIW, I've applied the patch to test it, and `rotate-window` works as expected; when you rotate the panes in a window by pressing `C-b C-o`, the window stay zoomed.

I haven't been able to test `switch-client` because I couldn't find an example where it would modify the zoomed state of a window. If I have 2 sessions, each with one single zoomed window, when I run `:switchc -n` to focus the next session, the window already stay zoomed even without `-Z`.

Also, I may have missed it, but `last-pane` seems to missing from the patch.

**Comment by nicm** [comment]
last-pane is the same as select-pane. switch-client you need to specify a
pane target (-t:.6)

**Comment by lacygoill** [comment]
Ok, so `last-pane` doesn't support `-Z` but you can get the desired result by passing `-l` to `select-pane`, which gives:

    $ tmux select-pane -lZ
                         ^

As for `switch-client`, it indeed unzooms a window but only if it received the `-t` argument, and not in combination with the `-n` or `-p ` flags:

    $ tmux switch-client -t:.0

And in that case, `-Z` does indeed preserve the zoomed state of the window:

    $ tmux switch-client -t:.0 -Z
                               ^^

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by net** [comment]
Thank you!
