### ISSUE TITLE
`displayp -d 0` is not terminated by a keypress

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1841]
### Issue description

To reproduce, run these shell commands:

    $ tmux -Lx -f/dev/null
    $ tmux displayp -d 0

Then press a key.

I would expect the `tmux displayp` process to be terminated, because the manpage says:

> A duration of zero means the indicator stays until a key is pressed.

But in practice it keeps going on – as well as the indicator – and I haven't found a way to end it properly, so I just end up killing the tmux server.

### Required information

 - `$ tmux -V`: tmux next-3.1
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:
[tmux-client-26414.log](https://github.com/tmux/tmux/files/3399100/tmux-client-26414.log)
[tmux-out-26416.log](https://github.com/tmux/tmux/files/3399101/tmux-out-26416.log)
[tmux-server-26416.log](https://github.com/tmux/tmux/files/3399103/tmux-server-26416.log)

 - backtrace from `$ gdb -q /path/to/running/tmux PID`, `set logging on`, `bt full`: 
[backtrace.txt](https://github.com/tmux/tmux/files/3399098/backtrace.txt)

 - possible offending commit from `$ git bisect`: https://github.com/tmux/tmux/commit/87ea14328ce60fdfb8bd0aef15b7e3b3bdccb1ed

**Comment by lacygoill** [comment]
Sorry, I've misunderstood the change introduced by the commit.

**Comment by nicm** [comment]
I think others should still clear the display, try this please:
~~~~
--- server-client.c     6 Jul 2019 20:56:34 -0000       1.292
+++ server-client.c     17 Jul 2019 05:52:10 -0000
@@ -1226,6 +1226,7 @@ server_client_handle_key(struct client *
                                return (0);
                        }
                }
+               server_client_clear_overlay(c);
        }

        /*

**Comment by lacygoill** [comment]
I've just tested the patch, and now when you press any key, the `$ tmux displayp` process is ended, and the indicators are cleared.

Thank you very much.
