### ISSUE TITLE
`if-shell -b` never runs any tmux command

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1843]
### Issue description

To reproduce, run these shell commands:

    $ tmux -Lx -f/dev/null
    $ tmux if -b true 'run "echo true >/tmp/file"'

I would expect the text `true` to have been written in `/tmp/file`, but in practice the file is not created.

---

If I remove the `-b` flag, the command works as expected:

    $ tmux if true 'run "echo true >/tmp/file"'

---

I thought that maybe `run-shell` somehow inherited the `-b` flag of `if-shell`, and that for some reason it prevented the shell from redirecting the output in a file.
So I tried to run a simple `$ sleep`:

    $ tmux if -b true 'run "sleep 99"'

And looked for its pid with `$ pidof sleep`.
But the output was empty.

---

I thought that maybe `-b` was altering the test, so I added a second `$ sleep`:

    $ tmux if -b true 'run "sleep 99"' 'run "sleep 99"'

But the output of `$ pidof sleep` was still empty.

---

I thought that maybe `if-shell -b` was not meant to be combined with `run-shell`, so I tried with 3 other commands: `kill-server`, `set-option` and `clear-history`.

    $ tmux if -b true 'kill-server' 'kill-server'
    $ tmux if -b true 'clear-history' 'clear-history'
    $ tmux if -b true 'set -g @foo bar' 'set -g @foo bar'

The first command failed, because the tmux server was not killed.
The second command failed, because the scrollback buffer was not cleared.
The third command failed, because the output of `$ tmux show -g @foo` was empty.

---

I thought that maybe the syntax of my commands was wrong, so I tried to find usage examples in the repository:

    $ vim
    :vimgrep /\m\C\<if\%(-shell\)\=.*-b\>/gj ./**/*
    :cw

But I couldn't find one.

---

Is there a bug in the `-b` flag which can be passed to `if-shell`?
If not, then how should it be used to run a tmux command in case of success or failure of a shell command started in the background?

### Required information

 - `$ tmux -V`: tmux next-3.1
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:
[tmux-client-10034.log](https://github.com/tmux/tmux/files/3399701/tmux-client-10034.log)
[tmux-out-10036.log](https://github.com/tmux/tmux/files/3399704/tmux-out-10036.log)
[tmux-server-10036.log](https://github.com/tmux/tmux/files/3399705/tmux-server-10036.log)

**Comment by nicm** [comment]
Try this please:
~~~~
--- cmd-if-shell.c      18 Jun 2019 11:08:42 -0000      1.64
+++ cmd-if-shell.c      17 Jul 2019 05:58:01 -0000
@@ -121,7 +121,10 @@ cmd_if_shell_exec(struct cmd *self, stru
                cdata->cmd_else = NULL;
        memcpy(&cdata->mouse, m, sizeof cdata->mouse);

-       cdata->client = item->client;
+       if (!args_has(args, 'b'))
+               cdata->client = item->client;
+       else
+               cdata->client = c;
        if (cdata->client != NULL)
                cdata->client->references++;

**Comment by lacygoill** [comment]
I've just tested the patch and it works; i.e. now `if -b` is able to run a tmux command.

However, if I run `$ sleep` in a tmux command:

    $ tmux if -b true 'run "sleep 5"'

I get back the shell prompt, but while the `$ sleep` process is running, it seems that all the keys that I press are sent to some typeahead buffer.

As soon as `$ sleep` ends, the keys in this buffer are typed/processed.
So, for example, if I type the 3 keys `l`, `s`, `Enter`, then when `$ sleep` ends, tmux presses those keys, and I get the listing of the current directory.
It seems instantaneous, but it's not. If I increase the sleeping time, press keys to start Vim, write some text in a buffer, save it in a file, and quit, when `$ sleep` ends, I can briefly see the Vim interface, which means that Vim had not been started up to this point.

I'm not sure whether it's intended or expected by the user.
It's not a big issue though, because one can still pass `-b` to `run-shell` in addition of `if-shell`:

    $ tmux if -b true 'run -b "sleep 5"'
                           ^^

In this case, not only do you get back the shell prompt, but your keypresses are also processed immediately instead of being sent to a typeahead buffer.

Thank you very much for the patch.

**Comment by nicm** [comment]
I think this is OK, run without -b will block the queue of the client it is running on so commands will be delayed until it finished, this includes key presses.

**Comment by lacygoill** [comment]
I agree with what you said. The only thing which I find confusing is the fact that we get the shell prompt back, which makes me – wrongly – think that I can go on typing and running commands immediately, while in reality I have to wait for `run` to finish.

When you don't pass `-b` to `if-shell`, you don't get back the shell prompt, so there's no confusion.

Anyway, this is a minor point. I just thought it was worth being mentioned.

**Comment by nicm** [comment]
If you run with if-shell -b then the command is run in the context of the
attached client, not the command client you started by typing "tmux if ..."
into the shell. So run-shell will block the attached client not the command
client. That's why you get the shell prompt back immediately.
