### ISSUE TITLE
$TERM doesn't change to the terminal's default value in a new tmux session on a different terminal

### ISSUE THREAD

**Issue by Necktwi** [tmux/tmux#1844]
I connect to remote Linux server from my mac or windows pc. My Mac terminal's default value is `xterm-24Mcolor-italic` and putty on windows' default value is `xterm`. I open a tmux session on my mac's terminal whose `TERM` becomes `tmux.xterm-24Mcolor-italic` and then open a **new** tmux session on putty on windows but its TERM also set to `tmux.xterm-24Mcolor-italic` instead of `tmux.xterm`.

**Comment by Necktwi** [comment]
can you please comment?

**Comment by nicm** [comment]
No tmux version, no configs, no description of how you are setting TERM - please don't open issues like this.

**Comment by Necktwi** [comment]
@nicm I've updated the missing, please open the issue

**Comment by nicm** [comment]
You are running the script from .tmux.conf but it is only read when the server starts not when a new session is created on an existing server. You'd be better to do this in your shell profile.

**Comment by Necktwi** [comment]
How to find if the shell is started by `tmux` without using `$TERM`?

**Comment by krader1961** [comment]
Check if the `TMUX` env var is set?

**Comment by Necktwi** [comment]
thanks, that worked.

**Comment by Necktwi** [comment]
but tmux is setting TERM=screen. how to stop tmux touching the TERM var?

**Comment by nicm** [comment]
tmux always sets it BEFORE your shell profiles are run so changing it in
them will replace it.

Anyway it has to be screen* or tmux* inside tmux.

**Comment by Necktwi** [comment]
Is there anyway to know actual TERM in a `tmux` session? Instead of just overwriting the TERM with some default value, I would suggest you to leave the TERM untouched. Is there a plan to implement terminal demultiplexer to render the same shell on different terminals?

**Comment by krader1961** [comment]
> Is there anyway to know actual TERM in a tmux session?

No. Why would you need that value?

> Instead of just overwriting the TERM with some default value, I would suggest you to leave the TERM untouched.

That wouldn't work. I'm getting the sense you don't understand what tmux's core feature is; i.e., it's primary purpose.

> Is there a plan to implement terminal demultiplexer to render the same shell on different terminals?

I can't make sense of that question.  You seem to be asking if tmux supports different terminal types attaching to a particular tmux session. For example, tmux clients running in iTerm2 and Konsole both attaching to the same tmux session. Tmux already supports that. In fact, that is its core feature. It's why the `TERM` value inside the tmux session has to be something like `screen`. That allows a program like `vim` or `emacs` to work and produce correct output regardless of the tmux client terminal.

**Comment by Necktwi** [comment]
In emacs on iTerm2, I use 32bit color; I've a terminfo named tmux.xterm-24Mcolor-italic as per the emacs documentation to support 32bit color. if TERM=screen then my color configuration in emacs is not working.

**Comment by krader1961** [comment]
@Necktwi First, you should be using `screen-256color` or `tmux-256color`. Then tell tmux that it should enable true-color support by setting a terminal override. See the "RGB" section in the [FAQ](https://github.com/tmux/tmux/wiki/FAQ).
