### ISSUE TITLE
`search-reverse` doesn't wrap around the start of the pane contents when the search matches its very beginning

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1845]
### Issue description

To reproduce, run these shell commands:

    $ tmux -Lx -f/dev/null
    $ tmux set -gw mode-keys vi \; set -gw wrap-search on \; run -b 'echo "foo\nbar\nfoo\nbar\nfoo\nbar"'

Then, search for `foo`: you should jump onto the second occurrence.
Next, press `N` to jump onto the first occurrence.
Finally, press `N` again to jump onto the last occurrence: the cursor stays where it is.

![gif](https://user-images.githubusercontent.com/8505073/61481023-72a3bd00-a997-11e9-93e2-504d287b0630.gif)

Since the option 'wrap-search' is on, I would expect `search-reverse` to wrap around the start of the pane contents and make the cursor jump onto the third occurrence of `foo`.

If I search for `bar` instead of `foo`, then `N` does wrap around the start of the pane contents, which suggests that the issue is specific to a search matching the very beginning of the buffer.

### Required information

 - `$ tmux -V`: tmux next-3.1
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:
[tmux-client-22681.log](https://github.com/tmux/tmux/files/3407826/tmux-client-22681.log)
[tmux-out-22683.log](https://github.com/tmux/tmux/files/3407827/tmux-out-22683.log)
[tmux-server-22683.log](https://github.com/tmux/tmux/files/3407831/tmux-server-22683.log)

**Comment by lacygoill** [comment]
The same issue seems to apply to `search-again` if the search was initiated by `search-backward` instead of `search-forward`.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3456982/x.diff.txt)

**Comment by lacygoill** [comment]
The patch fixes the issue, thank you very much.

**Comment by nicm** [comment]
Applied, thanks!
