### ISSUE TITLE
Feature request: bind-key -T choose-tree

### ISSUE THREAD

**Issue by benknoble** [tmux/tmux#1846]
I find some of the functionality in `choose-tree` to use bizarre mappings (I'm so used to vim that I usually hit `/` to search, which works in all tmux output panes *except* `choose-tree`).

Obviously, we could fix this one little issue.

But it would be more interesting to expose a `choose-tree` table for key bindings, à la `copy-mode`, to allow custom `choose-tree` mappings. This would likely require exposure of the native choose-tree functionality as commands (such as `choose-tree-search`, which AFAIK is not available as a tmux command. It could be designed to fail if not in `choose-tree`?).

### Required information

Please provide the following information:

* tmux version (`tmux -V`) 2.9a
* Platform (`uname -sp`) Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`)
  - screen256-color
  - xterm256-color
* Logs from tmux (`tmux kill-server; tmux -vv new`) N/A, surely.

**Comment by ThomasAdam** [comment]
Not convinced.  We unified these commands so that there could be a consistent mapping between them.

**Comment by nicm** [comment]
/ is not used for anything so it could be search as well if you want to add it but I don't want a key table for the choose modes.

**Comment by benknoble** [comment]
@ThomasAdam @nicm Fair feedback. As I attempted to explain, this mostly stemmed from a bit of cognitive dissonance between tmux output like `Prefix+?` and `choose-tree` (`Prefix+s`).

I thought one solution might be to allow users to create their own "cognitive unification." In the meantime, I would be satisfied if `/` and `?` worked as searching. Other nitpicks include `g` and `G` to jump to top and bottom (number keys really aren't my thing).

I'm happy to try to contribute these patches if someone points me towards the appropriate source file.

**Comment by nicm** [comment]
mode-tree.c:mode_tree_key for common keys and the others in window-tree.c:window_tree_key and similar in window-client.c and window-buffer.c.
