### ISSUE TITLE
`$ tmux send-keys` parses a quoted trailing semicolon as a command termination

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1849]
### Issue description

I'm not sure this is a bug, but there seems to be an inconsistency in the way `send-keys` parses a string terminated by a semicolon.

If I run:

    # 1
    $ tmux send 'ls;' C-m

The command fails with the error message `unknown command: C-m`.
This is probably because the semicolon was interpreted as a command termination, and thus `C-m` was interpreted as a new command after `send-keys`. And since `C-m` is not a valid tmux command, it fails.

Now if I run any of these 3 commands (`$` = run from the shell, `:` = run from tmux command prompt):

    # 2
    :send 'ls;' C-m

    # 3
    $ tmux send 'ls; ' C-m

    # 4
    :send 'ls; ' C-m

They all work as expected:

   - the semicolon is parsed as a literal key to send, not as a command termination
   - `C-m` is parsed as a key to send, not as a tmux command
   - `$ ls` is run

And if I run any of these 2 commands:

    # 5
    $ tmux send 'ls;ls' C-m

    # 6
    :send 'ls;ls' C-m

Again, they all work as expected.
The only difference with the previous commands is that `$ ls` is run twice.

---

The issue is in the command `#1`.
It's the only one to fail, and I don't understand why.
It seems inconsistent.

The semicolon is inside quotes, so the shell should not interfere, and I would expect tmux to send it as a literal key.

---

I tried to compare the server log for the six previous commands.
Here are the relevant lines:

        $ tmux send 'ls;' C-m

    cmd_unpack_argv: argv[0]=send
    cmd_unpack_argv: argv[1]=ls;
    cmd_unpack_argv: argv[2]=C-m
    cmd_parse_from_arguments: argv[0]=send
    cmd_parse_from_arguments: argv[1]=ls;
    cmd_parse_from_arguments: argv[2]=C-m
    cmd_parse_from_arguments: at 1: argv[0]=send
    cmd_parse_from_arguments: at 1: argv[1]=ls
    cmd_parse_from_arguments: at 2: argv[0]=C-m
    cmd_parse_build_commands: 0 send
    cmd_parse_build_commands: argv[0]=ls
    cmd_parse: send-keys: argv[0]=send
    cmd_parse: send-keys: argv[1]=ls
    cmd_parse_build_commands: 0 C-m

        :send 'ls;' C-m

    yylex_token: send
    yylex_token: ls;
    yylex_token: C-m
    cmd_parse_build_commands: 0 send
    cmd_parse_build_commands: argv[0]=ls;
    cmd_parse_build_commands: argv[1]=C-m
    cmd_parse: send-keys: argv[0]=send
    cmd_parse: send-keys: argv[1]=ls;
    cmd_parse: send-keys: argv[2]=C-m
    cmd_parse_build_commands: send-keys "ls;" C-m

        $ tmux send 'ls; ' C-m

    cmd_unpack_argv: argv[0]=send
    cmd_unpack_argv: argv[1]=ls; 
    cmd_unpack_argv: argv[2]=C-m
    cmd_parse_from_arguments: argv[0]=send
    cmd_parse_from_arguments: argv[1]=ls; 
    cmd_parse_from_arguments: argv[2]=C-m
    cmd_parse_from_arguments: at 0: argv[0]=send
    cmd_parse_from_arguments: at 0: argv[1]=ls; 
    cmd_parse_from_arguments: at 0: argv[2]=C-m
    cmd_parse_build_commands: 0 send
    cmd_parse_build_commands: argv[0]=ls; 
    cmd_parse_build_commands: argv[1]=C-m
    cmd_parse: send-keys: argv[0]=send
    cmd_parse: send-keys: argv[1]=ls; 
    cmd_parse: send-keys: argv[2]=C-m
    cmd_parse_build_commands: send-keys "ls; " C-m

        :send 'ls; ' C-m

    yylex_token: send
    yylex_token: ls; 
    yylex_token: C-m
    cmd_parse_build_commands: 0 send
    cmd_parse_build_commands: argv[0]=ls; 
    cmd_parse_build_commands: argv[1]=C-m
    cmd_parse: send-keys: argv[0]=send
    cmd_parse: send-keys: argv[1]=ls; 
    cmd_parse: send-keys: argv[2]=C-m
    cmd_parse_build_commands: send-keys "ls; " C-m

        $ tmux send 'ls;ls' C-m

    cmd_unpack_argv: argv[0]=send
    cmd_unpack_argv: argv[1]=ls;ls
    cmd_unpack_argv: argv[2]=C-m
    cmd_parse_from_arguments: argv[0]=send
    cmd_parse_from_arguments: argv[1]=ls;ls
    cmd_parse_from_arguments: argv[2]=C-m
    cmd_parse_from_arguments: at 0: argv[0]=send
    cmd_parse_from_arguments: at 0: argv[1]=ls;ls
    cmd_parse_from_arguments: at 0: argv[2]=C-m
    cmd_parse_build_commands: 0 send
    cmd_parse_build_commands: argv[0]=ls;ls
    cmd_parse_build_commands: argv[1]=C-m
    cmd_parse: send-keys: argv[0]=send
    cmd_parse: send-keys: argv[1]=ls;ls
    cmd_parse: send-keys: argv[2]=C-m
    cmd_parse_build_commands: send-keys "ls;ls" C-m

        :send 'ls;ls' C-m

    yylex_token: send
    yylex_token: ls;ls
    yylex_token: C-m
    cmd_parse_build_commands: 0 send
    cmd_parse_build_commands: argv[0]=ls;ls
    cmd_parse_build_commands: argv[1]=C-m
    cmd_parse: send-keys: argv[0]=send
    cmd_parse: send-keys: argv[1]=ls;ls
    cmd_parse: send-keys: argv[2]=C-m
    cmd_parse_build_commands: send-keys "ls;ls" C-m

In all of them, the semicolon is preserved, except in the first block.
It's lost on this line:

    cmd_parse_from_arguments: at 1: argv[1]=ls

I had a look at the `cmd_parse_from_arguments()` function, but I don't understand the YACC language.
If I had to guess, I would say the issue comes from this line:
https://github.com/tmux/tmux/blob/47712fc113fbc602e27aa1f24e5ada3c2f061a94/cmd-parse.y#L802

Because it seems to inspect the last character of a token, and compare it to a semicolon.
I wonder whether the function is somehow confused by a trailing semicolon in a token.

---

Note that before the commit https://github.com/tmux/tmux/commit/723010ba72e337832402f8e44981c02caa30b476 , all the previous commands had the same output, except `#2`, which failed like `#1`. So it seems that the commit has fixed one of the 2 cases, but not both.

---

In practice, because of this issue, when you write a plugin and you need to send some keys, you need to make sure that no string passed to `$ tmux send` ends with a trailing semicolon. And if one of them does, you need to make sure it's escaped.
It's a pitfall which can lead to bugs such as: https://github.com/jebaum/vim-tmuxify/issues/11

### Required information

 - `$ tmux -V`: tmux next-3.1
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:
[tmux-client-10565.log](https://github.com/tmux/tmux/files/3410895/tmux-client-10565.log)
[tmux-out-10567.log](https://github.com/tmux/tmux/files/3410896/tmux-out-10567.log)
[tmux-server-10567.log](https://github.com/tmux/tmux/files/3410897/tmux-server-10567.log)

**Comment by nicm** [comment]
Yes this is just how the command parser works. If you do any of these:
~~~~
tmux send a\; b
tmux send 'a;' b
tmux send "a;" b
~~~~
tmux receives the same thing from the shell - two arguments 'a;' and 'b'.

There is no way for tmux to tell whether you intended this to be two separate commands or one command with two arguments.

For the shell you need to escape the ; so that tmux receives 'a\;'.

In retrospect it would perhaps have been better to forbid ; unless it is an argument entirely on its own (so "tmux send a \; b" works but not "tmux send a\; b") but I don't think this is important enough to be worth the disruption of changing it now.
