### ISSUE TITLE
Curious issue with True Color - true colour works but $TERM isn't updated to reflect that.

### ISSUE THREAD

**Issue by noidawt** [tmux/tmux#1850]
### Here's the info:

![image](https://user-images.githubusercontent.com/46407739/61555864-3b491500-aa58-11e9-9e81-893e250badf7.png)

As you can see in the top two terminals, true color is working perfectly fine both in tmux (whether or not it's started with -2) and without tmux. However, the $TERM environment variable isn't changed to reflect that by the line:
`set -g default-terminal "tmux-256color"`

This means applications aren't aware and hence the terrible looking vim color theme .-.

If I were to force set TERM to be "tmux-256color", everything works perfectly, so I'm wondering why it is that tmux doesn't set it so automatically, and what I can do to set things appropriately. It'd be less than optimal to set TERM to be tmux-256color in say my .bashrc or something like that, because in some cases the clients I use don't support true color.

**Comment by noidawt** [comment]
Well, this is quite funny, but, after an hour, two hours of tinkering with this and deciding to post an issue here looking for help, literally 5 minutes after I posted this I found the problem - so I'm just hoping this can help someone else in the future:

Provided you have everything set up correctly in your .tmux.conf, as in:

`
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"
`

That should do the trick, but if it doesn't, it's worth investigating first under what circumstances color actually works and what $TERM is inside and out of tmux, but if all else fails - check your profile scripts! .bashrc, .profile, /etc/profile - one of them might be sneakily changing your TERM.
A quick way to test for this is by running

`
tmux neww 'bash --norc --noprofile'
`

Anyways, with that out of the way - why is it that only "xterm-256color" seems to work with vim? Otherwise ("screen-256color" or "tmux-256color") it's just black and white, even though `tput colors`, `echo $TERM` , `infocmp` and the color test all work as you may hope?

**Comment by lacygoill** [comment]
I don't think you should use `xterm-256color` as the value of your 'default-terminal' option.
From the [FAQ](https://github.com/tmux/tmux/wiki/FAQ):

> Inside tmux TERM must be "screen", "tmux" or similar (such as "tmux-256color").

This may lead to other issues in tmux in the future. 'tmux-256color' was a better value.
Besides 'default-terminal' is not session option but a server one, so the `-s` flag would be more appropriate than the `-g` flag:

    set -s default-terminal "tmux-256color"
        ^^

---

> Anyways, with that out of the way - why is it that only "xterm-256color" seems to work with vim?

Which terminal are you using and how are you enabling true colors in Vim?

Try adding this to your vimrc:

    set tgc
    let &t_8f = "\e[38;2;%lu;%lu;%lum"
    let &t_8b = "\e[48;2;%lu;%lu;%lum"

**Comment by nicm** [comment]
Seems likely vim is special casing xterm*, you will need to ask them about it.

**Comment by nicm** [comment]
Or possibly xterm* has the RGB capability and tmux* and screen* don't.

**Comment by nicm** [comment]
Actually that's not true, only xterm -direct has it, not xterm-256color.
