### ISSUE TITLE
home/end doesn't work in status command

### ISSUE THREAD

**Issue by FractalBoy** [tmux/tmux#1851]
### Issue description

the status line in tmux doesn't recognize the home and end keys even though my terminfo is correct:

```
#       Reconstructed via infocmp from file: /usr/share/terminfo/s/screen-256color
screen-256color|GNU Screen with 256 colors,
        am, km, mir, msgr, xenl,
        colors#256, cols#80, it#8, lines#24, pairs#32767,
        acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=^M,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
        cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
        dl1=\E[M, ed=\E[J, el=\E[K, el1=\E[1K, enacs=\E(B\E)0,
        flash=\Eg, home=\E[H, ht=^I, hts=\EH, ich=\E[%p1%d@,
        il=\E[%p1%dL, il1=\E[L, ind=^J, initc@, is2=\E)0, kbs=\177,
        kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, **kend=\E[4~**, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf2=\EOQ, kf3=\EOR, kf4=\EOS,
        kf5=\E[15~, kf6=\E[17~, kf7=\E[18~, kf8=\E[19~, kf9=\E[20~,
        **khome=\E[1~**, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM, rmacs=^O,
        rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[23m,
        rmul=\E[24m, rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        sgr=\E[0%?%p6%t;1%;%?%p1%t;3%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;m%?%p9%t\016%e\017%;,
        sgr0=\E[m\017, smacs=^N, smcup=\E[?1049h, smir=\E[4h,
        smkx=\E[?1h\E=, smso=\E[3m, smul=\E[4m, tbc=\E[3g,
```

![image](https://user-images.githubusercontent.com/2024233/61564984-55c1c500-aa3d-11e9-8b89-d8476371a791.png)

i'm using putty standard home and end keys- if i change to rxvt controls, home works, but end doesn't (end is just 7?).

from what i can tell, tmux should be figuring out what is home and end though terminfo, which matches what showkey is telling me:

```
kb mode was UNICODE
[ if you are trying this under X, it might not work
since the X server is also reading /dev/console ]

press any key (program terminates 10s after last keypress)...
^[[1~^[[4~
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 2.9
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
outside: xterm, inside: screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-out-23738.log](https://github.com/tmux/tmux/files/3412700/tmux-out-23738.log)
[tmux-client-23736.log](https://github.com/tmux/tmux/files/3412701/tmux-client-23736.log)
[tmux-server-23738.log](https://github.com/tmux/tmux/files/3412702/tmux-server-23738.log)

**Comment by lacygoill** [comment]
I could be wrong, but I think what matters is the terminal description of the outer terminal.
Maybe the sequences stored in the `khome` and `kend` capabilities are not correctly set in the latter.
What's the output of:

    $ infocmp -x $(tmux display -p '#{client_termname}') | grep 'khome\|kend'

Maybe try to configure putty so that it uses a different terminal type; one for which the capabilities are correctly described.
See: https://superuser.com/a/104001/913143

Or try to update the terminal description of the outer terminal.
I don't know how to do this on Windows.
On Linux, you could run:

    $ curl -LO http://invisible-island.net/datafiles/current/terminfo.src.gz
    $ gunzip terminfo.src.gz
    $ tic -sx -e <your outer terminal> terminfo.src

**Comment by nicm** [comment]
Probably want TERM=putty outside tmux.

You can see xterm is incorrect in the server log:
~~~~
1563569464.850082 xterm 137: khome: (string) \\033OH

**Comment by FractalBoy** [comment]
i switched to TERM=putty outside tmux but that screws up colors a bit. i'll play around with other solutions. thanks!
