### ISSUE TITLE
Tmux pane-border-format does not reinvoke script when argument values change

### ISSUE THREAD

**Issue by natechan** [tmux/tmux#1852]
### Issue description

A pane-border-format consisting of string interpolation of variables such as

```
set -g pane-border-format "#{pane_current_command}(#{pane_pid}) #{pane_current_path}"
```

results in a new value being calculated whenever one of the involved variables (here, `pane_current_command`, `pane_pid`, and `pane_current_path`) change.

That behavior, however, breaks down when those same variables are passed as arguments to a shell script which just echoes the same string:

```
set -g pane-border-format "#(bash /path/to/script/pane_title_simple #{pane_current_command} #{pane_pid} #{pane_current_path})"
```

where 

```
$ cat /path/to/script/pane_title_simple
echo "${1}(${2}) ${3}"
```

When a script is invoked, the status does not update when the variables passed to the script change.  

In fact, one can actually see the variables change and the script not be reinvoked if the string interpolation consists of both the script invocation and the variables themselves:

```
set -g pane-border-format "#(bash ~/path/to/script/pane_title_simple #{pane_current_command} #{pane_pid} #{pane_current_path}) #{pane_current_command}(#{pane_pid}) #{pane_current_path}"
```

which can result in statuses such as

```
fish(39122) /Users/username fish(39122) /Users/username/Documents
```

after `cd`ing from `~` into Documents:

<img width="682" alt="screenshot" src="https://user-images.githubusercontent.com/982704/61585289-cedc1d80-ab0c-11e9-96e2-26fc22741b43.png">

Of note, sending prefix does result in the pane status refreshing.

### Required information

Please provide the following information:

```
$ tmux -V
tmux 2.9a (Logs are from a build of master at 47712fc113fbc602e27aa1f24e5ada3c2f061a94)
```
```
$ uname -sp
Darwin i386
```

Inside TMUX:
```
$ echo $TERM
screen
```

[tmux-server-50168.log](https://github.com/tmux/tmux/files/3414065/tmux-server-50168.log)
[tmux-client-50166.log](https://github.com/tmux/tmux/files/3414066/tmux-client-50166.log)
[tmux-out-50168.log](https://github.com/tmux/tmux/files/3414067/tmux-out-50168.log)

**Comment by nicm** [comment]
The problem is not that the command is not being run, the problem is that tmux will not redraw the pane status when it finishes, it updates if you make it redraw manually. Add "tmux refresh -S" to the end of your script and it should work.

**Comment by nicm** [comment]
Or try this which will do it automatically:
~~~~
? tmux
? tmux-client-99807.log
? tmux-out-78681.log
? tmux-server-78681.log
Index: screen-redraw.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/screen-redraw.c,v
retrieving revision 1.64
diff -u -p -r1.64 screen-redraw.c
--- screen-redraw.c	26 Jun 2019 13:03:47 -0000	1.64
+++ screen-redraw.c	22 Jul 2019 12:05:33 -0000
@@ -266,7 +266,7 @@ screen_redraw_make_pane_status(struct cl
 
 	fmt = options_get_string(w->options, "pane-border-format");
 
-	ft = format_create(c, NULL, FORMAT_PANE|wp->id, 0);
+	ft = format_create(c, NULL, FORMAT_PANE|wp->id, FORMAT_STATUS);
 	format_defaults(ft, c, NULL, NULL, wp);
 
 	expanded = format_expand_time(ft, fmt);

**Comment by natechan** [comment]
@nicm Thank you very much!

Adding `tmux refresh -S` to the end of the script makes things much better.  Using the basic script above, I haven't encountered any issues at all!

Changing screen-redraw.c to pass FORMAT_STATUS to format_create works as well.  Subjectively there didn't seem to be a difference, but that might be because the script I'm running invokes git a couple of times and so it is the choke point I'm seeing.  Is that a change you would consider making?

**Comment by natechan** [comment]
Does invoking `tmux refresh -S` from the script result in the script getting run again resulting in endless asynchronous refreshes?

**Comment by nicm** [comment]
Applied this change now, thanks!
