### ISSUE TITLE
Allow color configuration for marked pane

### ISSUE THREAD

**Issue by kevr** [tmux/tmux#1853]
Currently, tmux uses an inversed colorscheme for marked pane borders. This seems to be hardcoded, cited: https://unix.stackexchange.com/questions/301890/turn-off-color-inversion-for-marked-pane-in-tmux

Would you guys be open to a PR allowing configuration of these colors with defaults falling back to inverted colors?

Thanks for reading, and thanks for creating this great piece of software.

**Comment by nicm** [comment]
I'm not wild about more options for obscure bits of the UI, but I suppose we could add it. Maybe it could use the same style as something else.
