### ISSUE TITLE
Feature Request/Question

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#1856]
Hi, 
Would it be possible to do this at all, I would like to be able to fade inactive pane rather than change window-style/window-active-style.

here is the image from VIMADE plugin for vim where it fades the pane in vim while in tmux split pane mode.
<img width="1920" alt="Screen Shot 2019-07-25 at 4 59 22 pm" src="https://user-images.githubusercontent.com/7599183/61852953-09272f80-aefe-11e9-8ae7-e47acf9c58c2.png">

can tmux do something like that now?

**Comment by nicm** [comment]
You can change pane default fg and bg with select-pane -P (or set -p window-style in master).

**Comment by lanox** [comment]
It kind of works but other coloured text is not changed, as you can see some text is dimmed some not.

<img width="909" alt="Screen Shot 2019-07-25 at 8 50 27 pm" src="https://user-images.githubusercontent.com/7599183/61868973-ead12c00-af1d-11e9-8f0b-594da008672a.png">

**Comment by nicm** [comment]
There is no way to change these from outside the pane at the moment (from inside you could do it by changing the palette).
