### ISSUE TITLE
Feature Request: Visual identifier when panes synchronized

### ISSUE THREAD

**Issue by andres-lowrie** [tmux/tmux#1858]
Thanks for this tool; it's amazing and I don't know how I would be so productive without it, so yeah... thanks to everyone !!! ❤️ ❤️ 

Is there a way to visually display something on the status bar in the window when panes are synchronized, similar to how a `Z` is added to the window name when zoomed.

**Comment by lacygoill** [comment]
You could leverage the format variable `pane_synchronized` documented in the `FORMATS` section of the manual. For example, you could include this snippet in the value of your `'window-status-current-format'` and `'window-status-format'` options:

    #{?pane_synchronized,S,}
