### ISSUE TITLE
Terminal display confusion

### ISSUE THREAD

**Issue by huangjianchun69** [tmux/tmux#1859]
$ tmux -V
tmux 2.8

$ uname -sp
Linux x86_64

$ echo $TERM
xterm-256color

Problem：
Execute command :  sudo atop 1
It will display confusion in a moment.
How should I do？

**Comment by krader1961** [comment]
Works for me. You need to provide more information. Also, if that is the value of `TERM` inside the tmux session that is wrong.

**Comment by huangjianchun69** [comment]
> Works for me. You need to provide more information. Also, if that is the value of `TERM` inside the tmux session that is wrong.

----------------
Thanks, now i know what happened. The `TERM` is wrong inside the tmux.
~/.tmux.conf config file need setting `set -g default-terminal screen-256color`.
Now that runs very well. thanks!
