### ISSUE TITLE
save-buffer no longer works as expected

### ISSUE THREAD

**Issue by aaronjensen** [tmux/tmux#186]
Using master. I have this binding:

```
bind-key u capture-pane \; save-buffer /tmp/active_tmux_buffer \; new-window -n urlview '$SHELL -c "urlview < /tmp/active_tmux_buffer && rm /tmp/active_tmux_buffer"'
```

save-buffer prints that it cannot find /home/user/tmp/active_tmux_buffer

**Comment by nicm** [comment]
Hmm, yes, try this please:

Index: cmd-load-buffer.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-load-buffer.c,v
retrieving revision 1.35
diff -u -p -r1.35 cmd-load-buffer.c
--- cmd-load-buffer.c	31 Oct 2015 08:13:58 -0000	1.35
+++ cmd-load-buffer.c	10 Nov 2015 21:42:00 -0000
@@ -77,7 +77,10 @@ cmd_load_buffer_exec(struct cmd *self, s
 	else
 		cwd = ".";
 
-	xasprintf(&file, "%s/%s", cwd, path);
+	if (*path == '/')
+		file = xstrdup(path);
+	else
+		xasprintf(&file, "%s/%s", cwd, path);
 	if (realpath(file, resolved) == NULL)
 		f = NULL;
 	else
Index: cmd-save-buffer.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-save-buffer.c,v
retrieving revision 1.31
diff -u -p -r1.31 cmd-save-buffer.c
--- cmd-save-buffer.c	31 Oct 2015 08:13:58 -0000	1.31
+++ cmd-save-buffer.c	10 Nov 2015 21:42:00 -0000
@@ -103,7 +103,10 @@ cmd_save_buffer_exec(struct cmd *self, s
 	if (args_has(self->args, 'a'))
 		flags = "ab";
 
-	xasprintf(&file, "%s/%s", cwd, path);
+	if (*path == '/')
+		file = xstrdup(path);
+	else
+		xasprintf(&file, "%s/%s", cwd, path);
 	if (realpath(file, resolved) == NULL)
 		f = NULL;
 	else

**Comment by aaronjensen** [comment]
Now it prints the correct path, but it still fails.

**Comment by nicm** [comment]
Does save-buffer alone work?

**Comment by nicm** [comment]
Oh this is because glibc realpath is stupid, I'll fix it shortly.

**Comment by nicm** [comment]
should be fixed now.

**Comment by aaronjensen** [comment]
Confirmed, thank you!
