### ISSUE TITLE
TMUX Zoom doesn't redraw lines

### ISSUE THREAD

**Issue by muthugopal** [tmux/tmux#1860]
Hi ,

I see an issue in latest tmux,
before zooming a pane if I 'cat <150-characters-line-txt-file>' single line wraps around.
When I zoom it, it doesn't redraw/adjust the texts based zoomed size.
It is working fine till July-15 commit but broken on latest.

tmux -V                     :                 tmux next-3.1
TERM-outside-tmux:  "xterm-256color-italic"
uname -sp                :       Linux x86_64
TERM-inside-tmux   :  tmux-256color
Last Working Commit: 
    https://github.com/tmux/tmux/commit/a786a5917651397455110e5bf3b339b6ba1b5d4d
(if I git reset hard on my local build tmux dir to "c921649 + eac055b commit a786a5917651397455110e5bf3b339b6ba1b5d4d", it works fine)

Thanks
mg

**Comment by nicm** [comment]
Hmm yes odd, will take a look tomorrow.

**Comment by nicm** [comment]
This check is wrong, it can be removed:
~~~~
--- grid.c      16 Jul 2019 10:30:56 -0000      1.98
+++ grid.c      1 Aug 2019 07:07:56 -0000
@@ -1220,10 +1220,6 @@ grid_reflow(struct grid *gd, u_int sx)
        struct grid_cell         gc;
        u_int                    yy, width, i, at, first;

-       /* Do not reflow to the same size. */
-       if (sx == gd->sx)
-               return;
-
        /*
         * Create a destination grid. This is just used as a container for the
         * line data and may not be fully valid.

**Comment by nicm** [comment]
I have applied this now, let me know if you still see problems, thanks!
