### ISSUE TITLE
Display issues with ncurses after patchlevel 20190630 

### ISSUE THREAD

**Issue by rfrancoise** [tmux/tmux#1861]
Hi,

In Debian we have at least two reports ([#933514](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933514), [#933572](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933572)) of tmux exhibiting display corruption or glitches when running with recent version of ncurses.

This is apparently caused by a change to the `screen` terminfo definition which occurred in patchlevel 20190630 and added the following:

```
rin: NULL, '\E[%p1%dT'.
```

Any idea who to blame here? Thanks.

**Comment by nicm** [comment]
tmux does not support this escape sequence, it will need to be added.

**Comment by ThomasDickey** [comment]
actually I'll have to re-review the `ecma+index` changes as well, to address short-term effects (that affected the `tmux` entry because it inherits from `screen`, for which it was correct).

**Comment by nicm** [comment]
Try this please (lightly tested): [tmux-sd.diff.txt](https://github.com/tmux/tmux/files/3455651/tmux-sd.diff.txt)

**Comment by nicm** [comment]
OK that one was slightly wrong because apparently margins don't apply to SD (unlike SU) so it doesn't work with horizontal splits. Try this instead please: [tmux-sd2.diff.txt](https://github.com/tmux/tmux/files/3455686/tmux-sd2.diff.txt)

**Comment by nicm** [comment]
Oh wait, they do apply, I just turned them off :-).

**Comment by nicm** [comment]
Right, so if I actually set them correctly, we can also use margins when using RI as well as SD. Please try this: [tmux-sd3.diff.txt](https://github.com/tmux/tmux/files/3455788/tmux-sd3.diff.txt)

However, something funny is going on, xterm 348 seems to be turning off DECLRMM whenever I resize the window which I am sure didn't happen before. @ThomasDickey is this new?

**Comment by nicm** [comment]
This fixes the resize issue as well:
~~~~
--- tty.c	16 Jul 2019 14:11:52 -0000	1.329
+++ tty.c	1 Aug 2019 09:04:12 -0000
@@ -1879,6 +1879,8 @@ tty_invalidate(struct tty *tty)
 	tty->rlower = tty->rright = UINT_MAX;
 
 	if (tty->flags & TTY_STARTED) {
+		if (tty_use_margin(tty))
+			tty_puts(tty, "\033[?69h"); /* DECLRMM */
 		tty_putcode(tty, TTYC_SGR0);
 
 		tty->mode = ALL_MODES;

**Comment by nicm** [comment]
Confirmed this is new in xterm 348, I still have 347 and 344 xterms running and they don't do it.

**Comment by ThomasDickey** [comment]
perhaps [this](https://invisible-island.net/xterm/xterm.log.html#xterm_348):
>ensure that when resetting margins, to also reset DECLRMM. This affects DECCOLM, DECALN (although DEC STD 070 mentions only top/bottom margins), and DECSTR.

**Comment by nicm** [comment]
I guess it makes sense to reset it on resize because it does on DECCOLM but it is a bit unfortunate, I can make tmux set it again every time it resizes but there is no way to stop tmux using margins if they are available and it only turns them on when it first sets up the terminal, so older tmux versions will need the user to manually detach and reattach after resizing.

**Comment by ThomasDickey** [comment]
yes... the preceding item was what prompted this change:
>corrected order of reset/move when setting DECCOLM, and make it more consistent by always resetting margins, rather than only when the mode is changed (report by James Holderness).

and once having studied STD 070, I noticed the comments about margins, and realized that it was probably DEC's intention to do that.

**Comment by nicm** [comment]
OK well I will apply this fix and anyone using an older tmux with xterm 348 or later will just need to upgrade tmux or downgrade xterm.

**Comment by nicm** [comment]
I guess they could use -ti or decTerminalID to stop tmux using margins, that would be a workaround.

**Comment by rfrancoise** [comment]
I was able to reproduce the issue using mutt in termit with `master`, and after applying `tmux-sd3.diff.txt`, everything works just fine again. And tmux seems to be behaving normally, generally. So definitely a thumbs-up from me.

The diff is a bit large to carry as a backport in the Debian package, though. Not sure how I'll handle that yet.

Thanks!

**Comment by nicm** [comment]
If I was you I would patch terminfo to add rin@ (that is, remove rin) to screen* (or at least to tmux*). Screen users have managed without it for years and a bit more time until tmux versions with SD get out there won't hurt.

**Comment by nicm** [comment]
I'm away this weekend but I will apply the SD patch on Monday. Thanks!

**Comment by rfrancoise** [comment]
I will ask the ncurses maintainers. Thanks.

**Comment by nicm** [comment]
I have applied these changes now, thanks!
