### ISSUE TITLE
Verbose logging rollover/rotate

### ISSUE THREAD

**Issue by jimbobmcgee** [tmux/tmux#1863]
When running `tmux -v`, it writes to a log file in the initial working directory.  For a long-running server process, that log can grow indefinitely.  

If I apply a logrotate config to rotate that log file (or even if I rename the file manually), tmux continues to write to the renamed file.  I understand this is due to the process keeping hold of the file descriptor, and is relatively normal.

To overcome this, many daemon processes offer a means to refresh the file descriptor/reopen the log, such as handling a SIGHUP or SIGUSR1 sent to the process via `kill`, `pkill`, etc.

Is there a command or signal I can send to the tmux server process, to re-establish the log file, without killing the tmux server or any client processes?  

If not, could there be?

* tmux version (`tmux -V`). **tmux 2.4**
* Platform (`uname -sp`). **Linux x86_64** (CentOS 7)
* $TERM inside and outside of tmux (`echo $TERM`). **screen-256color**
* Logs from tmux (`tmux kill-server; tmux -vv new`). **n/a**

**Comment by nicm** [comment]
You can turn logging on and off with SIGUSR2 if you use a new enough tmux.

**Comment by jimbobmcgee** [comment]
@nicm - that's good to know.  

Does that mean sending SIGUSR2 twice in a logrotate PostRotate step do what I am looking for?

And any ideas how new is new enough?  2.4 doesn't seem to be...

**Comment by nicm** [comment]
Can't remember, maybe look at the CHANGES file or Git log. Logs are for debugging and will make tmux very slow, you shouldn't be logging all the time unless you are trying to find a bug.

**Comment by jimbobmcgee** [comment]
Some point between 2.5 and 2.6, apparently.  Looks like it turns on `vvvv` logging (which I imagine *would* be slow); I was only using single-`v` logging, and I didn't notice any major perf hit but, with it running for a few months, I had a 4GB tmux-server logfile and I wanted to rotate better.

(Was trying to run a permanent log to capture what appears to be an intermittent crash that only seems to affect a colleague of mine, when we share a server.  Not sure if bug or user-issue at this stage and cannot forcibly-recreate, so haven't raised it here.)

Would definitely appreciate a more rotation-friendly logging approach, though, in general.

**Comment by nicm** [comment]
SIGUSR2 is all we are going to do for this for the moment.
