### ISSUE TITLE
terminal clipboard not set when `set-clipboard` is 'external'

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1864]
### Issue description

To reproduce, run these shell commands:

    $ tmux -Lx -f/dev/null
    $ tmux set -s set-clipboard external
    $ printf 'foo' | xsel -i -b
    $ printf '\e]52;c;%s\x07' $(printf 'bar' | base64)
    $ xsel -b

The output of the last `$ xsel` command is 'foo', while I would expect 'bar', because according to the manpage, tmux should attempt to set the terminal clipboard if `set-clipboard` is 'external':

> If set to external, tmux will attempt to set the terminal clipboard but ignore
> attempts by applications to set tmux buffers.

I send an OSC 52 sequence to the terminal via `$ printf` in a shell script, and I set `set-clipboard` to 'external' instead of 'on' to prevent tmux from creating a buffer.
I can work around the issue by wrapping the OSC 52 sequence inside a DCS sequence with the prefix `tmux;`:

    $ printf '\ePtmux;\e\e]52;c;%s\x07\e\\' $(printf 'bar' | base64)

Or by setting `set-clipboard` to 'on'.

I'm not sure this is a bug, and I may have misunderstood how `set-clipboard` affects an OSC 52 sequence sent manually via `$ printf`, so feel free to close the issue if it's working as intended.

### Required information

 - `$ tmux -V`: tmux next-3.1, commit 9b3fefc43529666b1f6adc5efc89f6a5f127f274
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:
[tmux-client-9303.log](https://github.com/tmux/tmux/files/3474709/tmux-client-9303.log)
[tmux-out-9305.log](https://github.com/tmux/tmux/files/3474710/tmux-out-9305.log)
[tmux-server-9305.log](https://github.com/tmux/tmux/files/3474711/tmux-server-9305.log)

I also have these lines in `~/.Xresources`:

    XTerm*disallowedWindowOps: 20,21,SetXprop
    XTerm*selectToClipboard: true

**Comment by nicm** [comment]
You want "on" not "external" if you want to set it using OSC 52 inside tmux.
