### ISSUE TITLE
Render window list in different on 2.9a

### ISSUE THREAD

**Issue by david50407** [tmux/tmux#1866]
### Required information

Please provide the following information:

* tmux version (`tmux -V`): 2.9a
* Platform (`uname -sp`): FreeBSD amd64
* $TERM inside and outside of tmux (`echo $TERM`): inside `xterm-256color`, outside `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): (nothing output)

Render underscore on window list is different between 2.8 and 2.9a.
As screenshot below, in 2.8, underscore will be applied on full width of statusbar, but in 2.9a, underscore will only be applied on where has rendered a word.

2.8:
![image](https://user-images.githubusercontent.com/841969/62680520-faef0e00-b9e9-11e9-89a5-4c5a09c45be8.png)

2.9a:
![image](https://user-images.githubusercontent.com/841969/62680533-02aeb280-b9ea-11e9-9e4d-db06a8aa2cf4.png)

Does tmux 2.9a change the mechanism of rendering? Or I just missed some new options?

(Both test environment are FreeBSD 11.2, and the result of 2.1 is as same as 2.8)

`.tmux.conf` to reproduce:

```
# UTF-8
setw -gq utf8 on

# base configuration
set -g base-index 1
set -g bell-action none
set -g default-terminal "screen-256color"

setw -g automatic-rename on
setw -g monitor-activity on

set -g set-titles-string "#W #{session_alerts}"

# Statusbar
set -g status-position top
set -gq status-style fg=magenta,bg=black,underscore
setw -gq status-fg magenta
setw -gq status-bg black
setw -gq status-attr underscore

setw -g automatic-rename on
setw -g window-status-separator ''

STATUS_FORMAT="#I #T"
setw -g window-status-format " $STATUS_FORMAT "
setw -g window-status-current-style fg=brightyellow
setw -g window-status-current-format '#[nounderscore]/'$STATUS_FORMAT'\'

set -g status-left ""
set -g status-right "#[nounderscore] #[fg=yellow]%Y/%m/%d #[fg=magenta]%I:%M %p"
```

**Comment by nicm** [comment]
Does this still happen with 3.0 or master?

**Comment by david50407** [comment]
wow, it works on 3.0-rc4 ( https://github.com/tmux/tmux/releases/download/3.0/tmux-3.0-rc4.tar.gz ), sorry to bother but when will 3.0 (stable) be released?

**Comment by nicm** [comment]
great, release will probably be in October.

**Comment by david50407** [comment]
@nicm Another render question (on 3.0-rc4), if I applied `#[default]` on `window-status-format`, the bell highlight will be removed... Is that expected?

Like this (on window 2):
![image](https://user-images.githubusercontent.com/841969/62700415-6e0d7a00-ba14-11e9-94a4-e0102464481d.png)

And the relatived tmux conf below:
```
ICON='<some-icon-here>#{?#{window_active},#[default]#[nounderscore]#[fg=brightyellow],#[default]}'
HOST_OR_COMMAND="#{?#{==:#T,},#W,$ICON#T}"
STATUS_FORMAT="#I $HOST_OR_COMMAND"
setw -g window-status-format " $STATUS_FORMAT "
```

**Comment by nicm** [comment]
window-status-format will now override window-*-style, look at the ordering of them in status-format[0].
