### ISSUE TITLE
Vertical Zoom

### ISSUE THREAD

**Issue by uoee** [tmux/tmux#1868]
It would be useful to allow a pane to zoom to the maximum available vertical space. The current zoom takes up the entire screen. This has its uses but is often more than necessary.

So, for example, a vertical zoom would cover one column in a standard two-column layout, and, more generally, cover any panes having a X offset and width equal to the pane from which the zoom is initiated.

The only way I can think of currently achieving something similar would be to move and resize various panes (then move them all back again),  so a temporary vertical zoom would be handy.

I sadly can't comment to the practicalities of implementing this, so this is a mere suggestion of a feature tmux could have one day.

**Comment by lacygoill** [comment]
This is not exactly what you want, because there will still be one visible line above and/or below from a neighbor pane, but in the meantime, I would try this key binding:

    bind -n M-z if -F '#{@layout}' \
        {run 'tmux select-layout "#{@layout}" \; set -uw @layout'} \
        {set -Fw @layout "#{window_layout}" ; run 'tmux resizep -y "#{window_height}"'}

![gif](https://user-images.githubusercontent.com/8505073/62836268-bf5e7900-bc61-11e9-836c-f5fd30eec533.gif)

**Comment by lacygoill** [comment]
This is not exactly what you want, because there will still be one visible line above and/or below from a neighbor pane, but in the meantime, I would try this key binding:

    bind -n M-z if -F '#{@layout_save}' \
        {run 'tmux select-layout "#{@layout_save}" \; set -up @layout_save'} \
        {set -Fp @layout_save "#{window_layout}" ; run 'tmux resizep -y "#{window_height}"'}

![gif](https://user-images.githubusercontent.com/8505073/62836268-bf5e7900-bc61-11e9-836c-f5fd30eec533.gif)

**Comment by uoee** [comment]
Thank you for the workaround suggestion. I have tried this sort of approach in the past:

  tmux resizep -y $window_height 

However, one problem I found was that certain programs could fail and exit immediately because the pane height was too low for the program to function correctly. (the mpd clien ncmpcpp is one example)

My thinking was that a vertical zoom would avoid this by instead removing those other panes from view, as well as handling the problem of the partial visibility of the "hidden" panes as you mentioned

**Comment by nicm** [comment]
I bet you could move the panes above and below to a temporary session and then move them back, although getting them back in the right place might be tricky.

**Comment by uoee** [comment]
Yes, quite possible some convoluted script I engineer may eventually achieve some buggy but tolerable outcome – though your use of the word "tricky" gives me pause.

Anyway, I think the idea is good one for inclusion in tmux core. You're the boss, and so I'll leave the matter with you to include vertical zoom one day if you care do so. Thanks very much for tmux in general.

**Comment by nicm** [comment]
Added to todo list.

**Comment by net** [comment]
I think the best implementation of this would not be an explicit vertical zoom, but zoom to cover the nearest horizontal or vertical stack, perhaps repeatable up to the full window.

For example, a window first split horizontally (split -h) then in each pane split vertically (split -v) would, in any given pane, zoom vertically, at least first; however, a pane first split _vertically_ then horizontally would first zoom horizontally.
