### ISSUE TITLE
display corruption (regression, bisected)

### ISSUE THREAD

**Issue by gobenji** [tmux/tmux#1871]
commit b89f2f28bb5f ("Fix grid clear code to correctly clear with the default background colour rather than ending up with the used count higher than the total size, GitHub issue 1829.") introduced a regression that results in corrupted output.

I can reproduce it reliably with mutt. When openning a [certain message](https://lore.kernel.org/netdev/20190806161128.31232-1-gregkh@linuxfoundation.org/), some of the screen content is a "ghost" of the previous content. Hitting ^L redraws the screen and gets rid of the garbage.

This screenshot shows where the background content comes from:
![screenshot-1](https://user-images.githubusercontent.com/254681/63076785-4f0d6b80-bf71-11e9-92af-b87ecb079199.png)

I then open the message and this screenshot shows the problem:
![screenshot-2](https://user-images.githubusercontent.com/254681/63076786-4f0d6b80-bf71-11e9-9560-17fb00d289dc.png)

To reproduce the issue I compile from commit b749a39cdb4b ("Merge branch 'obsd-master'").

```
ben@f1:/tmp$ uname -sp
Linux x86_64
ben@f1:/tmp$ echo $TERM
rxvt-unicode-256color
# inside tmux
ben@f1:/tmp$ echo $TERM
screen
```
I've also attached compressed logs.

[logs.tar.gz](https://github.com/tmux/tmux/files/3504504/logs.tar.gz)

Around the same time I started to notice that problem, I also started to notice some strangeness with bash line editing that might be related (didn't find a way to reproduce that one).

**Comment by nicm** [comment]
Does it go away if you revert the first hunk in grid-view.c (add back the grid_clear)?

**Comment by gobenji** [comment]
> Does it go away if you revert the first hunk in grid-view.c (add back the grid_clear)?

Yes, the problem goes away by reverting that hunk.

**Comment by nicm** [comment]
Hmm this is weird because grid_move_cells is meant to clear any moved cells that were not replaced, meaning the grid_clear shouldn't be necessary. There must be a case where either it isn't working as intended or in fact it doesn't do what I think it does...

**Comment by nicm** [comment]
I have reverted this part anyway, thanks!
