### ISSUE TITLE
sort order of paste buffers changed

### ISSUE THREAD

**Issue by gobenji** [tmux/tmux#1872]
Commit 7bcc0d16f24 resulted in a change to the order of the buffers when doing `choose-buffer -O name` because the buffer index is no longer 0-padded.

For example, with "bind = choose-buffer -O name -N -F "#{buffer_sample}", the order used to be:
![screenshot-old](https://user-images.githubusercontent.com/254681/63079626-d232bf80-bf79-11e9-9acc-41fa9817f7b5.png)

After that commit, the order is:
![screenshot-new](https://user-images.githubusercontent.com/254681/63079630-d65edd00-bf79-11e9-8b75-9a3fb7fe4b4f.png)

I don't believe it's possible to get the old behavior from config.

**Comment by nicm** [comment]
I like the new names better, use -O time if you want it in the order the buffers were created.

**Comment by gobenji** [comment]
What I don't like with -O time is that it's in fact the reverse order from -O name:

![screenshot-time](https://user-images.githubusercontent.com/254681/63083253-39a13d00-bf83-11e9-87bc-c442be52b532.png)

I like the buffers to appear in chronological order (newest buffer on bottommost line). Can we have a "--reverse" option on that sort :)

**Comment by nicm** [comment]
Yes I am fine with having a way to reverse sort and it would not be hard to add. Either add new sort types reverse-time etc or add a separate -r flag, the former would probably be better because you wouldn't need a new key binding when using the modes interactively.
