### ISSUE TITLE
rate-limiting problem

### ISSUE THREAD

**Issue by msAlcantara** [tmux/tmux#1874]
### Issue description

According of documentation of [tmux 2.9 changes](https://raw.githubusercontent.com/tmux/tmux/2.9/CHANGES), the `The c0-* options for rate-limiting have been removed`. From that information, how can I configure my `~/.tmux.conf `to remove limit from my screen? When I have a web server with a lot of logs running in my terminal from a long time, I can't stop the program with Ctrl+c. In my searchs to fix this problem, this is a great old solution, but I can't do this in the last version of tmux. Can you help me to fix this problem?

### Required information

Please provide the following information:

* tmux version (`tmux 2.9a`).
* Platform (`Linux x86_64`).
Inside tmux: * $TERM inside and outside of tmux (`screen`).
Outside tmux: (`xterm-256color`)

**Comment by nicm** [comment]
There is no replacement option, the way this works has been completely changed.
