### ISSUE TITLE
vim's statusline becomes weird in tmux

### ISSUE THREAD

**Issue by Ejgwg0629** [tmux/tmux#1876]
### Issue description
I use vim(vim-airline) + tmux(2.9a) + CentOS(4.?), and statusline of vim appears longer than my pane.

![vim_statusline_length](https://user-images.githubusercontent.com/6130964/63211720-27b3cb80-c136-11e9-9006-f62ad9a0b87b.PNG)

Here is how it looks when I open vim under and out of tmux. The statusline becomes wired in tmux.
Out of tmux, the statusline looks OK (though there is a glyph not supported):
![outofTmux](https://user-images.githubusercontent.com/6130964/63211749-795c5600-c136-11e9-9122-b7a1c89589c7.PNG)

In tmux, part of the statusline goes out of margin:
![inTmux](https://user-images.githubusercontent.com/6130964/63211747-7497a200-c136-11e9-83a6-06d46b955ab3.PNG)

### Required information

* tmux version (`tmux -V`).
2.9a

* Platform (`uname -sp`).
Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).
screen-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-12911.log](https://github.com/tmux/tmux/files/3512107/tmux-client-12911.log)
[tmux-out-12913.log](https://github.com/tmux/tmux/files/3512108/tmux-out-12913.log)
[tmux-server-12913.log](https://github.com/tmux/tmux/files/3512109/tmux-server-12913.log)

**Comment by nicm** [comment]
What terminal is this? Does this still happen in xterm or gnome-terminal?

**Comment by Ejgwg0629** [comment]
> What terminal is this? Does this still happen in xterm or gnome-terminal?

It's [tera term](https://ttssh2.osdn.jp/index.html.en).
I don't know for xterm, but I used ubuntu at home, it doesn't happen in gnome-terminal.

**Comment by nicm** [comment]
Can you try a different terminal on the same box? Maybe putty? This seems
most likely to be a bug in the terminal's Unicode support.

**Comment by Ejgwg0629** [comment]
> Can you try a different terminal on the same box? Maybe putty? This seems most likely to be a bug in the terminal's Unicode support.


Thank you so much, I tried putty and MobaXterm, it didn't happen.

I don't really understand what do you mean with the `terminal's Unicode support`, actually it displays Japanese characters well, and it could even display the symbols my used font has. 
I mean, could you please tell me how would you describe the problem to the Teraterm developers if you are going to create a issue to them?

Anyway, sorry for having created this issue in the wrong place. 
Does it need to be the issuer who close the issue? If so, I'll close it after your next reply.

**Comment by nicm** [comment]
It looks to me like it is putting the cursor in the wrong place after
printing something in the vim status line, my suspicion would be the
Unicode characters. Perhaps tmux and the terminal have different ideas of
the character widths, or perhaps it is something else.
