### ISSUE TITLE
Changed behavior of swap-window

### ISSUE THREAD

**Issue by HalosGhost** [tmux/tmux#1879]
### Issue description

With a build of `tmux` from git-master, `swap-window` has changed its behavior from the last major release. Namely, instead of the window being swapped and the focus following the window that was originall focused, the windows are swapped and focus changes to the window it was swapped with.

*edit for clarity*: suppose I have two windows in this state: `[A]B` (`[]` denoting focus). Previously, I would do `swap-window -t +1` which would result in `B[A]` (A and B are swapped and A remains focused). When doing so now, the result is `[B]A` (this windows are swapped, but the focus stays in the first position, so it is no longer on A). Passing `-d` in addition does not seem to change the behavior at all.

I use tmux's windows similar to tabs, so being able to move a window multiple times is a common use-case for me. Now, I would either need to know how far I want to move the window right away, or I need to swap windows, switch focus, and repeat till I have the windows in the order I would like. If I am going about this the WrongWay™, and there is a preferred method for accomplishing this, I would be happy to switch.

### Required information

- Linux unknown
   - Archlinux rolling release, using `tmux-git` from the AUR
- tmux next-3.1
- tmux-256color / st-256color

### Minimal configuration example:

```
bind -n S-down new-window
bind -n S-left prev
bind -n S-right next
bind -n C-left swap-window -t -1
bind -n C-right swap-window -t +1
```

-----

I am not able to post the logs at the moment (as I have work open in `tmux` for `$DAYJOB`, but I will try to remember to do this when I get home and can provide them:

**Comment by nicm** [comment]
The behaviour was fixed to what was intended (and what swap-pane does). Use -d to keep the current window the same.

**Comment by nicm** [comment]
I think the change was wrong, please try this: [x.diff.txt](https://github.com/tmux/tmux/files/3540322/x.diff.txt)

**Comment by nicm** [comment]
Applied now, thanks!
