### ISSUE TITLE
split pane switch to pane_current_path

### ISSUE THREAD

**Issue by liuyang1** [tmux/tmux#188]
In 1.9 Version,
`bind - splitw -v -c "#{pane_current_path}"`
will split pane with path of current pane.

But in 2.1 version.
when run command in current pane, liake "man man". splitw will change to `/usr/share/man` path.

This is annoying. How to config it? or rollback?
Thanks!

**Comment by nicm** [comment]
What platform?

**Comment by liuyang1** [comment]
ubuntu 14.04.

**Comment by nicm** [comment]
pane_current_path is not necessarily going to be reliable with programs that change the working directory themselves, like man. You could try reverting osdep-linux.c to the 2.0 version and see if it helps but it probably won't.

**Comment by liuyang1** [comment]
OK, I will try. Thanks.

**Comment by liuyang1** [comment]
I add this patch to fix this problem.

**Comment by edi9999** [comment]
@liuyang1 have you found an other way to fix this (eg without patching tmux ?)

The real underlying issue is : why does man change directory ??

**Comment by liuyang1** [comment]
@edi9999 sorry for so late reply
`man` call `chdir`. This system calling will change its cwd.
The `cwd` is varying based on program's behavior with `chdir`.

Looks like this issue is still open. You can try my patch, it works.
