### ISSUE TITLE
Programs report incorrect terminal size after resizing panes

### ISSUE THREAD

**Issue by j-tai** [tmux/tmux#1880]
Under certain circumstances, the program inside tmux will think the terminal is a different size than it really is. This can cause it to display things incorrectly, e.g. `pv` displaying a progress bar that's too long.

I'm pretty sure this is an issue with tmux, but if it isn't, please direct me to a better place to report this issue :)

I'm not quite sure how to reproduce this exactly, but the following seem to be contributing factors:

* Having more than one window in the session.
* Having more than one pane in the visible window.
* Having something running and printing text in the other window.
* Having one of the panes in raw mode (e.g. `read -n1`).
* Resizing the panes using the mouse.

I attached a video recording (below) of this issue occurring. In the video, I perform the following steps:

* I split the window horizontally, then vertically.
* In the bottom-left pane, I run the command `read -n1`.
* In the right pane, I run the command `pv -L1K /dev/zero > /dev/null`.
* I create another window, and in it, I run the command `while sleep 0.5; do echo "$COLUMNS by $LINES"; done`.
* In the first window, in the top-left pane, I run the same command.
* I use the mouse to resize the three panes.
* Now, the command in the top-left pane is reporting an incorrect terminal size. I use `C-b q` to have tmux show the actual size of the pane.
* Also, `pv`'s progress bar in the right pane isn't filling the entire width anymore---this is a sign that it is also getting the wrong terminal size. (Usually, the progress bar resizes to fit the screen.)
* Then, I stop the command in the top-left pane and use `tput` to get the terminal size. It also reports an incorrect size.
* After using `C-b q` to show the actual size again, the issue appears to have randomly fixed itself---notice that `pv`'s progress bar is filling the entire screen width again.

***

* `tmux -V`: `tmux 2.9a`
* `uname -sp`: `Linux unknown`
* `$TERM` outside tmux: `xterm-256color`
* `$TERM` inside tmux: `screen`
* OS: Arch Linux
* .tmux.conf:
    ```
    set -g mouse on
    set -g status-left ' '
    set -g status-right ' '
    ```
* Logs:
  * [tmux-client-7239.log](https://github.com/tmux/tmux/files/3527708/tmux-client-7239.log)
  * [tmux-out-7241.log](https://github.com/tmux/tmux/files/3527709/tmux-out-7241.log)
  * [tmux-server-7241.log](https://github.com/tmux/tmux/files/3527710/tmux-server-7241.log)
* Video: [tmux-issue.flv.gz](https://github.com/tmux/tmux/files/3527712/tmux-issue.flv.gz)

**Comment by nicm** [comment]
If you strace the program running inside tmux, does it receive the SIGWINCH?

**Comment by j-tai** [comment]
It receives a single SIGWINCH when I first start dragging the mouse, but no further SIGWINCH signals after that.

It seems that tmux avoids sending many SIGWINCH's in a short time, so it holds off on sending it until I finish resizing the panes. But, when this issue occurs, that last SIGWINCH never gets sent, or it gets sent much later.

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/3531240/x.diff.txt)

**Comment by j-tai** [comment]
Nope, that didn't fix it.

**Comment by nicm** [comment]
Can you show me the server log from master with the diff applied please?

**Comment by j-tai** [comment]
Here you go:

* [tmux-out-29966.log](https://github.com/tmux/tmux/files/3535657/tmux-out-29966.log)
* [tmux-server-29966.log](https://github.com/tmux/tmux/files/3535656/tmux-server-29966.log)

**Comment by nicm** [comment]
Hmm I think the problem is it keeps pushing the timer back if there is anything that wakes it up, not necessarily that you are resizing. Please apply this and show me the server log from reproducing again [x.diff.txt](https://github.com/tmux/tmux/files/3541614/x.diff.txt)

**Comment by nicm** [comment]
Try this please: [y.diff.txt](https://github.com/tmux/tmux/files/3542559/y.diff.txt)

**Comment by nicm** [comment]
I have applied this, thanks!
