### ISSUE TITLE
tmux exiting and showing no client

### ISSUE THREAD

**Issue by arty-hlr** [tmux/tmux#1881]
EDIT: The same issue happens with tmux 3.0!

tmux version: 2.9a
system: linux 5.0.21-rt16-MANJARO

So, after a few months without issue from tmux, it started recently to create a new empty tmux even though I already had a tmux running with sessions which were attached in terminals. At first I thought it was because I used `tmux new -A -s main` in my .bashrc with some conditions, but taking that out and going back to just opening a terminal and either `tmux new -s main` or `tmux attach` gives the same behaviour. After some amount of time, sometimes a few minutes and sometimes a few days, I would have some sessions open, and trying to attach just tells me `no sessions`, as if tmux had exited, but I can still access the sessions that are open in the other terminal, create panes, windows etc.

I tried to recreate that after running tmux with `-vv`, here are the log files:
[logs](https://github.com/arty-hlr/pastebin)

I saw another issue regarding the same problem [here](https://github.com/tmux/tmux/issues/1816) but it was closed without explanation.

**Comment by nicm** [comment]
Where are the logs?

**Comment by arty-hlr** [comment]
@nicm on my pastebin github, the link above is working (logs), [here](https://github.com/arty-hlr/pastebin) it is again.

**Comment by nicm** [comment]
It wasn't working when you linked it earlier, why not just add them to the issue?

**Comment by nicm** [comment]
This server has died because it has been sent SIGTERM:

1566488834.559739 server_signal: Terminated

So something is killing the tmux server.

**Comment by nicm** [comment]
Are you sure something isn't removing the tmux socket in /tmp? What happens if you do "pkill -USR1 tmux" after you get "no sessions"? Can you attach then?

**Comment by arty-hlr** [comment]
Well one of them is huge, so can't copy paste, and can't drag and drop from here, I figured putting them on a public github would be easier.

**Comment by arty-hlr** [comment]
I guess something is, but without closing the session that I'm in, so that's weird. 

Let me try that.

**Comment by arty-hlr** [comment]
Ok that worked I killed tmux with USR1 and attached afterwards to my open session, so I guess that's a temporary fix I can use to recover my open sessions, I still don't understand why that's happening though.

**Comment by arty-hlr** [comment]
I don't have anything removing stuff from `/tmp` though.

**Comment by nicm** [comment]
It seems like something is removing the tmux sockets from /tmp but leaving the server running.

**Comment by arty-hlr** [comment]
Yes, I'll try to monitor that, thanks for your help!
