### ISSUE TITLE
Using variable in window-status

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#1884]
Hi,

`set-option -g pane-border-format "#[fg=#5e5855]#(ps -o args= -t $(tmux display-message -p '#{pane_tty}') -c | sed 's/-zsh//')"`
Above works as expected it `shows nvim test.txt`

However if I do something like below, it doesn't work.

`current_command="#(ps -o args= -t $(tmux display-message -p '#{pane_tty}') -c | sed 's/-zsh//')"`

and I use `$corrent_command` as a variable in as follow `#{?#{s/zsh//:$current_command},:,}#{s/zsh//:$current_command}` in window-status-current-format I get nothing.

running following commend gives me,

```
ps -o args= -t $(tmux display-message -p '#{pane_tty}') -c | sed 's/-zsh//'

nvim test.txt
ttys001 -c
```

**Comment by nicm** [comment]
Show exact config that doesn't work please not bits of it.

**Comment by lanox** [comment]
Hi @nicm 

Sorry about that. 

Here is the exact config.

```
current_command="#(ps -o args= -t $(tmux display-message -p '#{pane_tty}') -c | sed 's/-zsh//')"


H="/Users/lanox"
set-option -g status-justify left

set-window-option -g window-status-format "#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H},●, #{b:pane_current_path}}}#{?#{s/zsh//:pane_current_command},:,}#{s/zsh//:pane_current_command} "
set-window-option -g window-status-current-format "#{?window_name,#{window_name},#{?#{==:#{pane_current_path},$H},●,#{?#{m:$H/*,#{pane_current_path}},,} #{b:pane_current_path}}}#{?#{s/zsh//:$current_command},:,}#{s/zsh//:$current_command}"
set-option -g status-format[1] ""
#}
```

What I want is to show current dir:running command and if any arguments.

If you think there is better way then how I am doing it happy for you to let me know.

**Comment by nicm** [comment]
#() doesn't work inside #{}, you will need to do the s/zsh// bit as part of your shell script rather than afterwards.

**Comment by lanox** [comment]
do you mean that this #(ps -o args= -t $(tmux display-message -p '#{pane_tty}') -c | sed 's/-zsh//')" entire line will not work or just the sed part.

**Comment by nicm** [comment]
No you are doing #{s/zsh//:#(...)}. You can't use #() inside #{}.

**Comment by lanox** [comment]
Ah right, I see what you mean.

What I am doing is that okay or do you suggest better way ?
