### ISSUE TITLE
Is after-kill-pane hook available

### ISSUE THREAD

**Issue by OliverLew** [tmux/tmux#1885]
I saw a accepted answer on stackoverflow: https://stackoverflow.com/a/43332267, And in the answer he used a hook
```tmux
set-hook -g after-kill-pane 'select-layout even-horizontal'
```
But now this seems not working for me. So is this hook till there in tmux now?

**Comment by nicm** [comment]
No there is no after-kill-pane hook but you can probably use pane-died/pane-exited for the process exiting and just change your key binding for kill-pane for it.

Or try this change:
~~~~
--- cmd-kill-pane.c     10 Apr 2018 10:48:44 -0000      1.26
+++ cmd-kill-pane.c     26 Aug 2019 10:55:15 -0000
@@ -37,7 +37,7 @@ const struct cmd_entry cmd_kill_pane_ent

        .target = { 't', CMD_FIND_PANE, 0 },

-       .flags = 0,
+       .flags = CMD_AFTERHOOK,
        .exec = cmd_kill_pane_exec
 };

**Comment by OliverLew** [comment]
Yah I think I can just change the keybinding, thank you for answering!
