### ISSUE TITLE
How to use status-format[1]

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#1886]
Hi 

I have read the Man page as well as the changelog, but for life of me I can't seem to work out how do you set below for status[1] and is it even possible 

```

set-window-option -g window-status-format
set-window-option -g window-status-current-format
set-option -g status-right
```

I would like to have a blank line above status[0], I would have assumed having 2 status bars that numbering would go from bottom to top such as 0,1

**Comment by lacygoill** [comment]
I'm not sure this is what you want, but this command should add a second blank line in the status line, above the one currently used:

    $ tmux set -Fg 'status-format[1]' '#{status-format[0]}' \; set -g 'status-format[0]' '' \; set -g status 2

In tmux.conf, it would give:

    set -Fg 'status-format[1]' '#{status-format[0]}'
    set -g 'status-format[0]' ''
    set -g status 2

**Comment by nicm** [comment]
Status line numbering goes from the top.

**Comment by lanox** [comment]
Thanks @lacygoill.

@nicm so do I do what lacygoill said or is there way to set the 

```

set-window-option -g window-status-format
set-window-option -g window-status-current-format
set-option -g status-right
```

**Comment by nicm** [comment]
What do you mean?

**Comment by lanox** [comment]
I know I can use windwo-format[2] to customise second status bar but that is for current format.

But how do I  set

```
set-window-option -g window-status-format
set-option -g status-right
```

**Comment by nicm** [comment]
There are no separate variables for window-status-format and friends for status-format[1], if you copy it from status-format[0] it will use the same ones, otherwise you will need to change status-format[1] itself either to put the values in directly or to use your own user variables.

**Comment by lanox** [comment]
Ah okay thanks.

**Comment by lanox** [comment]
@lacygoill  That worked like a charm, however doing reload of the config while in tmux make the status bar go blank.

**Comment by lacygoill** [comment]
You need a guard to prevent the code from being sourced once the server has been started.

Usually, I use this guard:

    if '[ "$TERM" != "#{default-terminal}" ]' { ... }

Because the first time the server starts, the value of `$TERM` is different than the value of the `'default-terminal'` option. Afterward, they are identical.

In your case, you could also check the value of `'status'` which by default is `on`, not `2`.
This would give:

    if -F '#{!=:#{status},2}' {
        set -Fg 'status-format[1]' '#{status-format[0]}'
        set -g 'status-format[0]' ''
        set -g status 2
    }

Note that your tmux needs to be recent enough to support braces.
If it doesn't, try this instead (which is slightly less readable):

    if -F '#{!=:#{status},2}' " \
        set -Fg 'status-format[1]' '#{status-format[0]}' ;\
        set -g 'status-format[0]' '' ;\
        set -g status 2 \
        "

**Comment by lanox** [comment]
Thanks @lacygoill , I amaze my self of how knowledgeable people are.
