### ISSUE TITLE
patch for Makefile.am for ctags

### ISSUE THREAD

**Issue by mmjo** [tmux/tmux#1888]
'make ctags' does not include the compat/* files

The patch included, splits off compat/*[.ch] from EXTRA_DIST into dist_EXTRA_tmux_SOURCES

This will include these files in the distrubution targets, and only add the conditionally needed sources/objects to the tmux binary. (via AC_LIBOBJ and LIBOBJS)

Patch applies against 6640790b

[Makefile.am.patch.txt](https://github.com/tmux/tmux/files/3554585/Makefile.am.patch.txt)

Regards, Mike

**Comment by nicm** [comment]
Applied now, thanks!
