### ISSUE TITLE
pane_current_path stays the same for bindings

### ISSUE THREAD

**Issue by Nondv** [tmux/tmux#1889]
* tmux 2.8
* Mac OS 10.14
* $TERM is `xterm-256color` outside and `xterm` is inside tmux
* Fish shell

I have these in my config:

```
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
# This is for debug purposes. Shows an error with a content of pane_current_path
bind t show '#{pane_current_path}'
```

So my splitting suddenly stopped working and I have no idea why. Now it creates a pane with the path tmux was started in.

The command itself works if I put it like
`tmux split-window -h -c '#{pane_current_path}'`

but the binding doesnt. This is why I added the last binding. When I `cd` into some directory the binding displays the initial path, not the current one. Entering command as `tmux show '#{pane_current_path}` shows the current one.

Any ideas?

**Comment by nicm** [comment]
Does it still happen in master?

Logs?

**Comment by shaynez** [comment]
I have the same issue,  "tmux show '#{pane_current_path}' " always print out my home dir no matter what the real dir it is.

**Comment by shaynez** [comment]
BTW, My tmux version is 3.1, from manual page, I can't find #{pane_current_path}, which mean this variable not support now?

**Comment by lanox** [comment]
I am using tmux next-3.1  and I do not seem to have that issue.

`bind | split-window -h -c '#{pane_current_path}'` works perfectly fine.

**Comment by shaynez** [comment]
It looks like the problem not related with tmux version, I have test in my another server, it work well.
And, I have rollback my tmux version to 2.9, the problem still there. Maybe something changed(maybe update?) in OS level, how can I collect log for it in tmux? Thanks.

**Comment by Nondv** [comment]
@lanox what OS do you use?

@shaynez same question, what os do you use? When searching manual, look for `pane_current_path`. Curly braces are just for interpolation

Also, to my first post, the splitting works just fine if there's a process running (for example, some server)

**Comment by shaynez** [comment]
@Nondv 
Server with problem(company interal server):                                                                                                                                                    
  CentOS Linux release 7.5.1804 (Core)
Server without problem(aliyun):
  CentOS Linux release 7.6.1810 (Core)

**Comment by caksoylar** [comment]
I also run into this issue, but using `bash` as my default shell and disabling setting `default-command` to fish in my tmux.conf avoids it. https://github.com/fish-shell/fish-shell/issues/5699 seems to me like the culprit.
