### ISSUE TITLE
Wrong description about global options in man page

### ISSUE THREAD

**Issue by Splarv** [tmux/tmux#1890]
Now in man

> The tmux server has a set of global options which do not apply to any particular window or session.  These are altered with the set-option -s command, or displayed with the show-options -s command.

Obviously in this context must be not '-s', but '-g'. Or 'server options', not 'global options'.

**Comment by nicm** [comment]
No they are global options belonging to the tmux server.

**Comment by Splarv** [comment]
Obviously there is misdirection or misterm. Compare two cite from the man page:

- First
> The tmux server has a set of global options which do not apply to any particular window or session.  These are altered with the set-option -s command, or displayed with the show-options -s command.

- Second
> set-option [-aFgoqsuw] [-t target-session | target-window] option value
> (alias: set) Set a window option with -w (equivalent to the set-window-option command), a server option with -s, otherwise a session option.  If -g is given, the global session or window option is set.  -F expands formats in the option value.  The -u flag unsets an option, so a session inherits the option from the global options (or with -g, restores a global option to the default).

**Comment by nicm** [comment]
Personally I think these are fine, "global options" are not something in
themselves - there are global session options, global window options and
global server options. Server options are just always global because
there is only one server. But if it is bothering you then feel free to
suggest better text for one or both places.

**Comment by Splarv** [comment]
I don't know English well, but why not:

> The tmux server has a set of server options which do not apply to any particular window or session. These are altered with the set-option -s command, or displayed with the show-options -s command.

**Comment by nicm** [comment]
I changed it to "global server options". Thanks!
