### ISSUE TITLE
Issue on the right hand side

### ISSUE THREAD

**Issue by itwars** [tmux/tmux#1893]
### Issue description

I got always a shift on the right:

![image](https://user-images.githubusercontent.com/353918/64077585-26f06d00-ccd2-11e9-96dd-febeedf33f29.png)

Even more, at first start some of my script won't get informations I need to be displayed, and I got some strings unless I do a "reload"!

![image](https://user-images.githubusercontent.com/353918/64077632-8484b980-ccd2-11e9-97b4-d1f0c4ff6130.png)

### Required information

* tmux version (`tmux -V`): tmux 2.9a
* Platform (`uname -sp`): Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`): screen-256color
* iTerm2 Build 3.3.3beta2

### My setup

```
set -g status-interval 60

IPINT="#(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | awk '{ print $2}')"
IPEXT='#(dig +short myip.opendns.com @resolver1.opendns.com)'
IPS="#(whois $IPEXT|grep -m1 descr|sed 's/descr://g'|sed 's/ //g')"

set -g status-left-length 60
set -g status-left "#[default][#[fg=colour9]🏠$IPINT 🚀 $IPEXT 😈 $IPS#[default]]"

WEATHER='#(curl -s wttr.in/Bordeaux\?format\="%%l:+%%c%%20%%t%%60%%w&period=60")'
DATETIME='%a %d/%m ⏰  %H:%M'
BATT='#(pmset -g batt|grep -o '[0-9]*%%')'

set -g status-right-length 60
set -g status-right "$WEATHER #[default][#[fg=colour9]$DATETIME#[default]]-(#[fg=colour9]🔋 :$BATT#[default])"
```

Best regards

**Comment by nicm** [comment]
Please show tmux logs.

**Comment by itwars** [comment]
[?25l[Hvrabah@sushi:~\ [32m[1mΩ (B[m[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;231m[48;5;56m
Configuration reloaded                                                                                                                      (B[m[1;19H[Hvrabah@sushi:~\ [32m[1mΩ (B[m[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[38;5;231m[48;5;56m
[[38;5;9m🏠172.16.4.68 🚀 ;; connection timed out; no servers could [39m[20X[38;5;231m[20C[1→bash][39m[21X[38;5;231m[21C [[38;5;9mLun 09/09 ⏰  13:47[38;5;231m]-([38;5;9m🔋 :43%[38;5;231m)(B[m[1;19H[?12l[?25hdéconnexion
[1;40r(B[m[?1l>[H[2J]112[?12l[?25h[?1000l[?1002l[?1006l[?1005l[?1049l[23;0;0t[exited]

**Comment by nicm** [comment]
I need the tmux server log.

**Comment by itwars** [comment]
How to get them?

**Comment by nicm** [comment]
No no no, look here: https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md#how-do-i-get-logs-from-tmux

**Comment by itwars** [comment]
[tmux-server-51524.log](https://github.com/tmux/tmux/files/3590634/tmux-server-51524.log)

**Comment by nicm** [comment]
Great, thanks. Can you please run tmux with -vv in the same way but do this inside tmux:
~~~~
print "=\360\237\217\240=\360\237\232\200=\342\206\222=\342\217\260=\360\237\224\213=\n"
~~~~
Then show me the new server log.

**Comment by itwars** [comment]
I'm not sure to undestand: print is not a bash command?

**Comment by nicm** [comment]
printf not print, sorry.

**Comment by itwars** [comment]
[tmux-server-57109.log](https://github.com/tmux/tmux/files/3591384/tmux-server-57109.log)

And it display a nice: =🏠=🚀=→=⏰=🔋=

**Comment by nicm** [comment]
It looks like your platform has the wrong width for a couple of these symbols. This is what I see in your logs:
~~~~
input_top_bit_set 3 '\342\206\222' (width 1)
input_top_bit_set 3 '\342\217\260' (width 1)
input_top_bit_set 4 '\360\237\217\240' (width 2)
input_top_bit_set 4 '\360\237\224\213' (width 2)
input_top_bit_set 4 '\360\237\232\200' (width 2)
~~~~
But this is what I get here:
~~~~
input_top_bit_set 3 '\342\206\222' (width 1)
input_top_bit_set 3 '\342\217\260' (width 2)
input_top_bit_set 4 '\360\237\217\240' (width 2)
input_top_bit_set 4 '\360\237\224\213' (width 2)
input_top_bit_set 4 '\360\237\232\200' (width 2)
~~~~
So it appears that your platform is telling tmux that ⏰ is only one column wide when in fact it is two.

From your screenshot it looks like a couple of the other codepoints are also too small and cross into the next column, but it is so small I can't see very well.

Did you try building tmux with utf8proc?

**Comment by itwars** [comment]
I use Macos with iterm2. tmux came from *brew*

**Comment by nicm** [comment]
Show me the server log now with blank options please.

**Comment by itwars** [comment]
Hi,
In fact it seems the problem only appear with iTerm2 and not with Terminal on my macbook, when empty?

**Comment by nicm** [comment]
Did you ask
