### ISSUE TITLE
ssh Breaks vim Color Scheme When Using tmux

### ISSUE THREAD

**Issue by ZaydH** [tmux/tmux#1894]
### Issue description

My terminal's `vim` color scheme changes after connecting then immediately disconnecting from a remote server via `ssh`.  The exact command sequence is:

```
tmux
vim <my_file>  # vim colors correct
ssh <my server> 
exit  # Immediately disconnect
vim <my_file> # vim colors WRONG
```

*Note*: No difference was observed between `tmux` and `tmux -2`.  I also saw no difference in `tmux info` before and after the ssh connection.

I am unable to determine why connecting/disconnecting via `ssh` affects how `vim` runs on my local machine.  This only happens with `tmux`.  It does not happen with my normal terminal.

### Color Comparison

![image](https://user-images.githubusercontent.com/6292018/64082643-ffe06e00-ccc6-11e9-9f0c-167751a8d373.png)

### Version Info

* tmux version: 2.9a (installed with `brew`) and latest `master`
* vim version: 8.1
* Terminal: Apple (vanilla) v. 2.9.5:
* Shell: [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh)
* MacOS Version: Mojave 10.14.6
* Platform: Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`).
  * Outside tmux: `xterm-256color`
  * Inside tmux: `screen-256color` (If I set it to `xterm-256color` in .tmux.conf the colors in vim are never right).  This was verified before and after the `ssh` call above.

### Minimal .vimrc

```
"     Vundle Start
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'morhetz/gruvbox'
call vundle#end() 
filetype plugin indent on
"     Vundle END

syntax on

colorscheme gruvbox
set background=dark
```

### Minimal .tmux.conf

Needed to select `screen-256color`

```
set-option -g default-shell /usr/local/bin/zsh
set -g default-terminal "screen-256color"
```

### Logs from tmux

[tmux-client-83608.log](https://github.com/tmux/tmux/files/3563912/tmux-client-83608.log)
[tmux-out-83610.log](https://github.com/tmux/tmux/files/3563913/tmux-out-83610.log)
[tmux-server-83610.log](https://github.com/tmux/tmux/files/3563914/tmux-server-83610.log)
[tmux_info.txt](https://github.com/tmux/tmux/files/3563944/tmux_info.txt)

**Comment by ZaydH** [comment]
We were able to track down the root cause of the issue. The `.zshrc` file on the remote server calls [gruvbox_256palette_osx.sh](https://github.com/morhetz/gruvbox/blob/master/gruvbox_256palette_osx.sh).  `"${TERM%%-*}"` equals `screen`.  However, on the remote server, `$TMUX` is unset so it was loading the wrong settings.  

I assume this is not a `tmux` issue.  Before I closed, I wanted your feedback and confirmation.

**Comment by JamesKid** [comment]
How you slove this issue? i got this problem too.
