### ISSUE TITLE
tmux %if seems to have its logic inverted

### ISSUE THREAD

**Issue by konomikitten** [tmux/tmux#1896]
> The argument to %if and %elif is expanded as a format and if it evaluates to false (zero or empty), subsequent lines are ignored until the next %elif, %else or %endif.

````
bash ~
$ cat ~/.tmux.test
display-message -p "#{session_name}"
display-message -p "#{!=:#{session_name},Default}"
%if #{!=:#{session_name},Default}
display-message -p "True"
%else
display-message -p "False"
%endif

bash ~
$ tmux source ~/.tmux.test
Default
0
True
bash ~
$ 
````

* tmux version (tmux 3.0-rc4).
* Platform (Linux unknown).
* $TERM inside tmux (tmux-256color).
* $TERM outside tmux (xterm-256color).

**Comment by konomikitten** [comment]
Okay so after some further investigation.

The file:
````
display-message -p "#{session_name}"
display-message -p "#{!=:#{session_name},Default}"
%if #{!=:#{session_name},Default}
display-message -p "True"
%else
display-message -p "False"
%endif
````

On tmux 2.8:
`:source ~/.tmux.test`
````
Default
0
True
````

`tmux source ~/.tmux.test`
````
Default
0
True
````

On tmux 3.0-rc4:
`:source ~/.tmux.test`
````
Default
0
False
````

`tmux source ~/.tmux.test`
````
Default
0
True
````

**Comment by nicm** [comment]
It is not inverted, the problem is that when you run it from the command line there is no session available. Please try this: [tmux-if-fs.diff.txt](https://github.com/tmux/tmux/files/3590433/tmux-if-fs.diff.txt)

**Comment by konomikitten** [comment]
After patching:

I didn't test tmux 2.8 because the patch wasn't made for it.

On tmux 3.0-rc4:
`:source ~/.tmux.test`
````
Default
0
False
````

`tmux source ~/.tmux.test`
````
Default
0
False
````
Seems fixed to me, thanks for your time.

**Comment by nicm** [comment]
I have applied this now, thanks!
