### ISSUE TITLE
how to change the choose-buffer key binds

### ISSUE THREAD

**Issue by adrian-amaglio** [tmux/tmux#1897]
### Issue description
I love the vi mode that allow to use hjkl to move around in vi copy mode or choose-buffer mode.
However, I’m using a dvorak-like keymap and I tried to remap the key used to move.
I did it for copy mode but I can’t find how to do it in choose-buffer mode…

I red the man page without finding information.
If it works like copy-mode there should be a bind table name choose-mode-vi or something like this but when I do `lsk` there is no such a table.

What I’d like to do is remaping some keys like:
```
bind -T choice-mode-vi s send-keys -X cursor-down
bind -T choice-mode-vi r send-keys -X cursor-up
```

Is that implemented? If so where is it documented?
Else, is it possible to add the functionality? Although it is not much needed.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
2.9 just downloaded from github
* Platform (`uname -sp`)."
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
`screen` inside tmux, `xterm` outside
* Logs from tmux (`tmux kill-server; tmux -vv new`).

Thank you for your work!

**Comment by nicm** [comment]
It is not possible to change the key bindings in the choose modes.
