### ISSUE TITLE
Bind C-t and C-W are casse insensitive

### ISSUE THREAD

**Issue by adrian-amaglio** [tmux/tmux#1898]
### Issue description
I started tmux with the following config file:
```
# Open and close window (tab)
bind -n C-t new-window -c "#{pane_current_path}"
bind -n C-W kill-pane
```

I can now open a window pressing Ctrl+t or Ctrl+T and I can close a window pressing Ctrl+w or Ctrl+W
Which is a bit annoying since Ctrl+w is a shortcut to delete a word in bash…

I tried to add another set of keymap:
```
# Open and close window (tab)
bind -n C-t new-window -c "#{pane_current_path}"
bind -n C-W kill-pane

# switch panes
bind -n M-T select-pane -L
bind -n M-N select-pane -R
bind -n M-R select-pane -U
bind -n M-S select-pane -D
```

And only the Meta-Uppercase version of these shortcuts is working. Which is the expected behavior.

Why `C-t` and `C-w` keybinds are casse insensitive ?

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
`2.9`
* Platform (`uname -sp`).
`Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`).
`screen` inside tmux and `xterm` outside.
* Logs from tmux (`tmux kill-server; tmux -vv new`).
Running tmux I used C-T C-t and C-w keys but there is no logs…
```
$ ./tmux killserver ; ./tmux -vv new
no server running on /tmp/tmux-1000/default
[exited]
```

Thank you!

**Comment by nicm** [comment]
Because of how ctrl keys are represented, there are no uppercase control
keys on most terminals, C-w and C-W are the same. Meta is represented
differently so M-w and M-W are not the same.

**Comment by adrian-amaglio** [comment]
Too bad for me…
Thank you for the quick answer!
