### ISSUE TITLE
Entering commands in one tmux panel causes the other to scroll

### ISSUE THREAD

**Issue by pansila** [tmux/tmux#1903]
### Issue description

If I enter a command in one tmux panel, the other panel scrolls down from where it is currently at. I tried tmux 2.3 and the latest version from git repo, and could see the issue both.
I searched around and found a similar issue reported for [alacritty](https://github.com/jwilm/alacritty/issues/2396) which is not my case.

### Required information

* tmux version: `tmux next-3.1`.
* Platform: `Raspbian 9 armv7l`.
* Terminal tool: `putty` on Windows 7
* $TERM inside tmux: `screen`.
* $TERM outside tmux: `xterm`.
* Screenshot GIF:
![issue](https://user-images.githubusercontent.com/5125601/64590986-5c384180-d3db-11e9-8565-2abf142c7cd5.gif)
* Logs from tmux:
[tmux-client-20961.log](https://github.com/tmux/tmux/files/3594201/tmux-client-20961.log)
[tmux-out-20963.log](https://github.com/tmux/tmux/files/3594202/tmux-out-20963.log)
[tmux-server-20963.log](https://github.com/tmux/tmux/files/3594203/tmux-server-20963.log)

**Comment by nicm** [comment]
Does using TERM=putty instead of xterm outside tmux make any difference?

**Comment by pansila** [comment]
@nicm Yes, it works, what is the theory behind the $TERM? Thansk a lot.

**Comment by nicm** [comment]
Must be something in the xterm TERM that putty doesn't support or supports in a different way from xterm, I don't know what.
