### ISSUE TITLE
:mdoc warning: Using a macro as first argument cancels effect of .Ic

### ISSUE THREAD

**Issue by Splarv** [tmux/tmux#1904]
Issue is in the man page. Every time I open the man page `man tmux` I see

> :mdoc warning: Using a macro as first argument cancels effect of .Ic (#3374)

OS is MacOS, tmux installed by homebrew:
$ tmux -V
tmux 2.9a
$ man -V
man, version 1.6c

**Comment by nicm** [comment]
Does this still happen with tmux.1 from master?

**Comment by Splarv** [comment]
> Does this still happen with tmux.1 from master?

Not sure, the warning is different:

`$ nroff -mdoc tmux.1|more`
> :tmux.1:1440: warning [p 12, 2.7i]: can't break line
> tmux.1:1478: warning [p 12, 9.0i]: can't break line

**Comment by nicm** [comment]
OK I don't see anything obviously wrong on those lines and mandoc doesn't complain so I think we can just ignore them. Thanks

**Comment by austintraver** [comment]
Still having this issue, also running macOS

**Comment by reentim** [comment]
Seeing this too, tmux 2.9a / man 1.6c. Probably related: using less's search within tmux's man page sometimes doubles lines / corrupts output. e.g. I type `man tmux<CR>/file<CR>` and I see:

```
-f file       Specify an alternative configuration file.  By default,
-f file       Specify an alternative configuration file.  By default,
              tmux loads the system configuration file fromoks for a user
              /usr/local/etc/tmux.conf, if present, then looks for a user
              configuration file at ~/.tmux.conf.
              The configuration file is a set of tmux commands which are
              The configuration file is a set of tmux commands which are
```

this persists when scrolling by line or half page, but returns to normal after a full page up or down.

**Comment by austintraver** [comment]
I noticed that too, I bet those two things are related

**Comment by Splarv** [comment]
I checked with man from homebrew worked fine.
MacOS man:
man, version 1.6c
HomeBrew man:
man 2.8.5

**Comment by jfelchner** [comment]
@Splarv I'm not finding a `man` package in homebrew, how did you install and upgraded version of `man`?

**Comment by Splarv** [comment]
> @Splarv I'm not finding a `man` package in homebrew, how did you install and upgraded version of `man`?

A package "man-db" perhaps. :)
