### ISSUE TITLE
window-status styles not working properly

### ISSUE THREAD

**Issue by johnmiked15** [tmux/tmux#1909]
```sh
# uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux next-3.1
xterm-256color
# ./tmux
# echo $TERM
tmux-256color
```

Using tmux 2.9a (as well as current tmux 3.1-next), the format styles for the window status seem to be lost when a window status format is specified. See the configuration here:

```
set-option -g status-style fg=colour18,bg=colour20
set-window-option -g window-status-format "#[fg=colour18,bg=colour20] #I:#[default]#W#[fg=colour18,bg=colour20]#F"
set-window-option -g window-status-current-style bg=green,bold
set-window-option -g window-status-last-style bg=yellow
set-window-option -g window-status-style bg=red
```

This produces the following in current tmux, after creating a new session, then immediately creating 3 additional windows:

<img width="518" alt="No colors other than current" src="https://user-images.githubusercontent.com/394891/64873837-8eca8000-d60f-11e9-8786-2779390fe268.png">

Without the format line, this is what appears, and what *should* appear if the format option is set, other than the window number and flags being the same fg/bg as the rest of the status bar:

<img width="518" alt="Screen Shot 2019-09-13 at 10 18 28 AM" src="https://user-images.githubusercontent.com/394891/64874026-dfda7400-d60f-11e9-8ecc-1342367180d7.png">

Prior to tmux 2.9a (maybe it was in 2.8 as well, but definitely as of 2.7), this worked as intended. The `#[default]` in the format should cause tmux to revert back to the style it would be normally, but that appears to not be working for the non-active window.

[tmux-client-22130.log](https://github.com/tmux/tmux/files/3610604/tmux-client-22130.log)
[tmux-out-22132.log](https://github.com/tmux/tmux/files/3610605/tmux-out-22132.log)
[tmux-server-22132.log](https://github.com/tmux/tmux/files/3610606/tmux-server-22132.log)

**Comment by nicm** [comment]
Default is always status-style now.

**Comment by nicm** [comment]
You will need to either configure with -format or with the various -style options, not both.

**Comment by johnmiked15** [comment]
> You will need to either configure with -format or with the various -style options, not both.

This is not clear from the documentation. Specifically for the style of `#[default]`:

> A style may be the single term `default' to specify the default style
     (which may inherit from another option) or a space or comma separated
     list of the following:

This implies that using `#[default]` in a format line should let the default style be used, which should be `window-status-last-style` for the last window, or `window-status-style` for the others.

If what you say is true, then why does `#[default]` work for the *current* window? Seems like `#[default]` would make it match `status-style` even for the current window, which it doesn't. In my config, the current window is still properly styled with a green background. I think there's either a documentation ambiguity here that should be corrected, or this is in fact a bug.

**Comment by nicm** [comment]
You don't set window-status-current-format so there is nothing in there to override window-status-current-style.

**Comment by johnmiked15** [comment]
Something still isn't connecting here. What you're saying does not line up with the documentation.

Using the `#[default]` style in a format option should *reset* the styles previously set in the format option, when read from left to right. Instead, it's just setting it to the `status-style`. This doesn't work if you want different styles for windows that have the last, activity, or bell status set. You have a special format option for the current window, but none for last, activity, or bell.

How do we use a format string to customize the text and arrangement of the fields, while still being able to select different styles based on the status? If it's possible, then it needs to be clearer in the documentation. To recreate the same status line with very simple options (one format line, and different styles for the different statuses), I think what you're saying is that we need a nested list of boolean conditionals that check the flags and set different styles based on them. And doing so may or may not exactly mimic the *default* way of doing it. If we just want to override the styles for different statuses while using a custom format, it's no longer possible.

This is just an extremely confusing change that was made. What were the reasons for making `#[default]` no longer fall back to the style that would have been there if no format option was specified like the behavior was in 2.8 and before? It has become needlessly complex and very hard to understand. The man page and documentation needs a clarification on the fact that format options cause tmux to ignore any style options set for the status, and that current and *the other 3 statuses* are different.

**Comment by nicm** [comment]
There is now only one default for the status line and that is status-style, that's what #[default] changes to. This is because the status line is now built in one go and the other options are inserted into status-format directly as if they were in #[], there is no longer different sections of the status line with different defaults. I recommend either using the options or using #[], not both.

**Comment by johnmiked15** [comment]
Then you need to update the documentation to make this explicit. The following does not say what you're saying here:

> A style may be the single term `default' to specify the default style
(which may inherit from another option) or a space or comma separated
list of the following:

It does not inherit from another option any longer. It set it *to* `status-style` which is defaulted if not specified.

If I want to recreate the nested logic for determining which style is applied to text in a format string, how would I do so? This means the combination of last, activity, and bell. What was the default prior to 2.9?

**Comment by nicm** [comment]
It inherits from status-style in the status line.

**Comment by johnmiked15** [comment]
That's not clear. It says "from another option", not "from status-style". This needs to be updated. And you didn't answer my question about how to recreate the nested logic to determine which style to apply based on the different possible flags. The ordering of how it was chosen prior to 2.9 is not special

**Comment by nicm** [comment]
In choose modes it inherits from mode-style and in pane-border-format from pane-border-style or pane-border-active-style.

You can look at status-format[0] to see how the individual style options are applied.

I considered at one point adding push-default and pop-default style flags and using them in status-format but by then 2.9 was released and it so far doesn't seem that this makes a difference to that many people. Still, I would be open to including it, and it wouldn't be that much work for someone.

**Comment by johnmiked15** [comment]
Having the ability to push and pop styles would be useful for being able to customize the format with differently colored text than what was setup by the default `status-format[0]`, and being able to go back to what was there before after the text that needs the color override is done.

Are you saying we could do something like:

```
set-window-option -g window-status-format "#[push-default,fg=colour18,bg=colour20]#I:#[pop-default]#W#{?window_flags,#{window_flags}, }"
```

And this would presumably make the window index and the color always have the specified colors, but the title and flags would go back to whatever was set up by the default format string? If this is what you meant, then I would love this feature.

I'm willing to take a look at implementing this if you point me in the right direction.

**Comment by nicm** [comment]
You will need to add them to struct style and code to parse/print them in style.c. The format is processed in format-draw.c.

**Comment by nicm** [comment]
Yes you could then do exactly what you suggest but also they could go into status-format to push the new default right before the format option is included and pop if afterwards.
