### ISSUE TITLE
Powerline symbols and other character not displaying correctly

### ISSUE THREAD

**Issue by cHoco** [tmux/tmux#191]
Hello, just compiled the last HEAD version and I'm experiencing problems with text rendering.
I patched my font to include Powerline Symbols and other additional characters (these glyphs are store in the extended section of a font usually) and that worked fine until last version. But with last head these characters don't get rendered, or get rendered incorrectly. 

Here's the log from the server if you guys wanna take a look:
https://gist.github.com/721c36849fbf23d425c4

I can reproduce it with both Terminal.app and iTerm on OS X. It works as expected with tmux 2.1 or outside tmux

**Comment by nicm** [comment]
Are you printing these characters inside tmux? Tell me what you are
printing to get them, or show me the output of print 'characters'|cat -v.

**Comment by cHoco** [comment]
Yes printing inside tmux, actually it's vim that's printing them.
If I try to print them using the command you mentioned:

- Inside tmux DOESN'T print the character and the cat command returns: `-^B?`
- Outside tmux it prints the character and the cat command returns: `?M-^B?`

If I redirect the output to hex dump to see what exactly the command return in both cases there are the same bytes:
```
$ print 'BREAKING_CHARACTER' | cat -v | hexdump
0000000 ee 4d 2d 5e 42 b0 0a                           
0000007
```

**Comment by nicm** [comment]
This is not valid UTF-8.

0xee is the start of a 3-byte UTF-8 character, but 0x4d and 0x2d are not
valid continuation bytes.

That doesn't matter for the moment because tmux does not validate
anything but the first byte right now (but it should).

0x42 is 'B' which is fine.

But 0xb0 is not valid UTF-8 at all, there is no UTF-8 character 0xb0, so
tmux will ignore it.

**Comment by cHoco** [comment]
These glyphs are store in the Private Use Area https://en.wikipedia.org/wiki/Private_Use_Areas so they are not assigned by the standard. Would it be possible to support this? I think lots of people use these characters, and they're actually supported in some mainstream fonts (i.e. Sourcecode Pro, etc...)

**Comment by nicm** [comment]
These characters are not in the private use areas, they are just invalid
UTF-8. If they were in the private use area they would be fine (by
definition, they would be valid Unicode and therefore have a valid UTF-8
representation).

**Comment by cHoco** [comment]
But the character is surely inside the private use area :/ Here's the command I'm using
```
echo -e "\UE0B0" | cat -v
```
and the output is the one above

**Comment by nicm** [comment]
Ah you hexdump the wrong thing, there is no point in "cat -v|hexdump".

U+E0B0 is in the private use area, yes, and it is UTF-8 0xee 0x82 0xb0,
I'll have a look.

**Comment by nicm** [comment]
Yes, the PUA has been redefined as width 0, I will change it back to
width 1.

**Comment by cHoco** [comment]
Thank you again for your work!

**Comment by texai** [comment]
So, how can we fix ours Powerline symbols?

**Comment by tttwwy** [comment]
The problem still in tmux 2.2, is there any way to fix it ?

**Comment by nicm** [comment]
The UTF-8 code was changed in 2.2 to use the system wcwidth() so more
likely you are finding that your platform has a poor implementation of
Unicode locales. You can try tmux from Git master which may fix it.
