### ISSUE TITLE
unexpected cursor position when focusing a tmux pane where characters are concealed in a Vim buffer

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#1910]
### Issue description

To reproduce, run these shell commands:

    $ tmux -Lx -f/dev/null

    $ cat <<'EOF' >/tmp/zsh.zsh
    `one` `two` `three` `four` `five`, the backticks should be concealed
    EOF

    $ vim -Nu NONE  \
    --cmd 'syn region zshCommentCodeSpan matchgroup=Comment start=/\z(`\+\)/ end=/\z1/ concealends containedin=zshComment' \
    +'setl cocu=n cole=3' \
    +'norm! fb' \
    /tmp/zsh.zsh

Notice that the cursor is positioned on the `b` character in the `backticks` word:

    `one` `two` `three` `four` `five`, the backticks should be concealed
                                           ^

Finally, press `C-b "` to open a new horizontal tmux pane, and then press `C-b ;` to focus back the tmux pane where Vim is running. Notice that this time, the cursor is positioned on the `s` character in the `should` word:

    `one` `two` `three` `four` `five`, the backticks should be concealed
                                                     ^

It looks as if the cursor has moved ten characters forward:

![gif](https://user-images.githubusercontent.com/8505073/64874582-9c9df680-d64b-11e9-9ef9-0377fd0ebfe7.gif)

But I suspect that it's only a visual error, because if I press `l` to move the cursor 1 character forward, then the cursor moves onto the `a` character in the word `backticks`, meaning that in reality the cursor was still correctly positioned on the `b` of `backticks`, but for some reason it was not drawn in that position.

The more characters are concealed on the line, the further away from its correct position the cursor is drawn.

I can reproduce with no custom configuration (in Vim, in the shell or in Tmux).

### Required information

 - `$ tmux -V`: tmux next-3.1, commit a5e36a4bd6b81678e419dfc18ec6cec30fb415ad
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:

[tmux-client-553.log](https://github.com/tmux/tmux/files/3610671/tmux-client-553.log)
[tmux-out-555.log](https://github.com/tmux/tmux/files/3610673/tmux-out-555.log)
[tmux-server-555.log](https://github.com/tmux/tmux/files/3610674/tmux-server-555.log)

**Comment by nicm** [comment]
Hi

This seems like a vim bug - I can reproduce outside tmux. If I resize the xterm where vim is running then the cursor similarly jumps to the wrong position.

**Comment by lacygoill** [comment]
Ah that's good to know. I close this issue, and I'll try to reproduce outside Tmux to write a bug report on Vim's issue tracker.
