### ISSUE TITLE
Bold attribute is losen for color degradation from 256 to 8 colors

### ISSUE THREAD

**Issue by shunlir** [tmux/tmux#1911]
### Issue description

for color degradation from 256 color to 8 color, some colors lose the `bold` attribute while others note, the result is inconsistency and confusing.
e.g., `colour34` has issue:
```tmux
setw -g window-status-current-style fg=colour34,bold # fg=green3,bold fallback to 2(green), losing bold
```
while `colour40` is okay:
```tmux
setw -g window-status-current-style fg=colour40,bold # fg=green3,bold fallback to 10 then to 2(green)+bold
```
To reproduce, also ensure the terminal emulator enables bold font/text (or both bold and bright) for ANSI colors
I had a simple look at the source code (https://github.com/tmux/tmux/blob/9b3fefc43529666b1f6adc5efc89f6a5f127f274/tty.c#L2371), seems it interprets `bold` attr as `bright`, meaning more colors, however, the standard indicates it can be both `bold` and `bright`.

### Required information

* tmux version: `2.6`
* Platform: `Linux x86_64`
* $TERM inside tmux is `tmux`, outside is `xterm`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Using 256 colours inside tmux on 8 colour terminals is best effort only.

**Comment by shunlir** [comment]
@nicm, if so, I think it's better to not clear the `bold`/`bright` setting(https://github.com/tmux/tmux/blob/9b3fefc43529666b1f6adc5efc89f6a5f127f274/tty.c#L2380), because it corresponds to SGR code 1, the it means depends on the terminal emulator's capabilities or settings, TMUX shouldn't simply use it for 8 extra colors in 8 colors terminal

**Comment by nicm** [comment]
OK send a diff?
