### ISSUE TITLE
Checking for mulitiple conditionals

### ISSUE THREAD

**Issue by ksalman** [tmux/tmux#1913]
### Issue description
This is more of a question rather then an issue.

I have a somewhat complex window-status-format where I'd like to put different icons based on bell or activity in addition to changing color.  The conditionals can be nested but that requires a lot of repeated code. I came up with this monstrosity and I wonder if there is a better way to do it, something like #{?window_bell_flag, ?window_activity_flag}, to check for more than one condition.

```
set -g window-status-format "#[fg=colour237,bg=colour239,noitalics]"
set -ag window-status-format "#{?window_bell_flag,#[fg=colour237 bg=#d79921],}"
set -ag window-status-format "#{?window_activity_flag,#[fg=colour237 bg=#d79921],}"
set -ag window-status-format ""
set -ag window-status-format "#[fg=colour223,bg=colour239]"
set -ag window-status-format "#{?window_bell_flag,#[fg=colour237 bg=#d79921],}"
set -ag window-status-format "#{?window_activity_flag,#[fg=colour237 bg=#d79921],}"
set -ag window-status-format "#I"
set -ag window-status-format "#[fg=colour223, bg=colour239]"
set -ag window-status-format "#{?window_bell_flag,#[fg=colour237 bg=#d79921],}"
set -ag window-status-format "#{?window_activity_flag,#[fg=colour237 bg=#d79921],}"
set -ag window-status-format "#{?window_activity_flag,🞺,}"
set -ag window-status-format "#{?window_bell_flag,🔔,}"
set -ag window-status-format "#W"
set -ag window-status-format "#[fg=colour239, bg=colour237, noitalics]"
set -ag window-status-format "#{?window_bell_flag,#[fg=yellow bg=colour237],}"
set -ag window-status-format "#{?window_activity_flag,#[fg=yellow bg=colour237],}"
set -ag window-status-format ""

```

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.0-rc4
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
You can use &&?

**Comment by nicm** [comment]
Or || might be more it.

**Comment by ksalman** [comment]
Could you give me an example of what that would looks like? Looking at the man page, I came up with this but it does not work
```
set -ag window-status-format "#{#{||:#{?window_bell_flag},#{?window_activity_flag}},#[fg=colour237 bg=#d79921],}"
```

**Comment by nicm** [comment]
You what #{window_bell_flag} not #{?...

**Comment by ksalman** [comment]
I get the same results with that
```
set -ag window-status-format "#{#{||:#{window_bell_flag},#{window_activity_flag}},#[fg=colour237 bg=#d79921],}"
```

**Comment by nicm** [comment]
You left the ? out of the outer conditional.

**Comment by nicm** [comment]
Look at the default status-format[0] it has some.

**Comment by ksalman** [comment]
The outer ? is what I was missing all along. Thanks a bunch!
