### ISSUE TITLE
FR: Option to make all sessions "views" implicitly ..

### ISSUE THREAD

**Issue by avamsi** [tmux/tmux#1916]
.. without having to create a dummy "view" session using

    tmux new-session -t $existing_session -s $another_view_for_existing_session

My actual problem: When I'm viewing the same tmux session from multiple clients with different screen sizes, window is sized w.r.t the smallest screen which is not ideal (I know I could detach that client, but it is mosh and if I keep detaching then there's no point in using mosh)

**Comment by nicm** [comment]
"View" is not a tmux term, I assume you mean session groups...

I don't see a need for an option like this, your best bet is to use a shell alias.

If you want tmux to size sessions differently when attached to multiple client, use the window-size option.

**Comment by avamsi** [comment]
Thanks for your response!

> "View" is not a tmux term [...]

I understand, I was just trying to convey what I meant using a common programming term (hence the quotes and FR).

> [...] I assume you mean session groups

Unless I'm missing something (admittedly, I don't use session groups all that much), they're quite different from what I want to do.. right?

> I don't see a need for an option like this, your best bet is to use a shell alias.

That works for the first session I open but if I switch to a different session (say from the session list), I'm back to square one. Also, I just now found https://github.com/zolrath/wemux -- although I'm yet to try it, it's rouge mode seems to be exactly what I want.

> If you want tmux to size sessions differently when attached to multiple clients, use the window-size option (you probably want to set it to "largest").

I didn't know this existed. Presumably, then the smaller client would only see partial window?

**Comment by avamsi** [comment]
I tried wemux and that suffers from the same problem (back to square one when I switch sessions). GNU Screen's "multi display mode" (-x) seems to be doing what I want.

**Comment by avamsi** [comment]
Hey @nicm, I'm curious what warranted closing this FR (I'm not familiar with tmux's policy and README or CONTRIBUTING.md doesn't mention anything)? Seems to me like a valid FR that tmux in it's current state doesn't support.

**Comment by nicm** [comment]
If you want an option to automatically create session groups like in your example command, we are not going to add that, use a shell alias.

If you want sessions to size to the largest rather than the smallest client, use 2.9 and the window-size largest option (or master and window-size latest).

**Comment by nicm** [comment]
Sorry I didn't see your question about window-size, yes if it is largest the smaller clients will see only a section.

**Comment by avamsi** [comment]
I ended up building from head and using window-size latest -- works perfectly, thanks!
