### ISSUE TITLE
New windows open with incorrect window-size

### ISSUE THREAD

**Issue by avamsi** [tmux/tmux#1917]
### Issue description

I have my window-size set to latest. I have multiple clients open and on the larger one, when I open a new window, it's window-size defaults to the smaller size instead of the expected larger size and it *stays* small even after I execute some commands in it (expected to switch to larger size at least now since this is the "latest" window). Switching to a different window (same or different session, doesn't seem to matter) and switching back fixes the issue (now larger size as expected).

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  * tmux next-3.1
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
  * xterm-256color (both inside and outside)
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by avamsi** [comment]
I can't kill tmux ATM, I'll try to attach logs when I can and this is happening on our corp distro, so skipping Platform as well.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3641088/x.diff.txt)

**Comment by avamsi** [comment]
AFAICT, seems to be working! Thanks for the quick fix!

(Also, now that I restarted the server, please let me know if you need any logs)

**Comment by nicm** [comment]
I have applied this now, thanks!
