### ISSUE TITLE
Consecutive order for session numbers

### ISSUE THREAD

**Issue by sksd509** [tmux/tmux#1918]
This could be a known issue, but since I didn't get to see any direct document referring the same so asking it here.
Basically, even if previous sessions of tmux were close and then we open new sessions of tmux I am not seeing the previous session numbers being used for the new sessions.
As an example, if I have sessions such as 4,5 and 6 now then any **new** sessions should be ideally using 1,2 and 3 **first** and then if active sessions were found on that then try going for using sessions no 7,8,9 or so.

Some other info :
**tmux.bin 2.6
Linux x86_64
xterm-256color**

**Comment by nicm** [comment]
Sessions do not have numbers, they have names. If you do not specify a name then they are named using a counter that increases for every new session.

**Comment by sksd509** [comment]
For every new session?
Do you mean I should restart tmux itself for getting the older sequences being used now?

**Comment by nicm** [comment]
Or you can specify the name you want with new-session -s.
