### ISSUE TITLE
Add support for querying background color via OSC 11

### ISSUE THREAD

**Issue by blueyed** [tmux/tmux#1919]
`'\e]11;?\007'` can be used to query the background color of a terminal (OSC 11), but it is not supported in tmux: https://github.com/tmux/tmux/blob/06683cdd592b877ecdd3d30dc69d398402b73ef2/input.c#L2379-L2398

It would be nice if tmux would respond to it with the current window's background color.

This is used by Neovim to automatically set its background setting to "dark" or "light".

(I've also tried wrapping it in the "Ptmux" sequence (`printf '\ePtmux;\e\e]11;?\007\e\\'`) without success - likely because tmux interprets the response then itself somehow/parly?)

**Comment by nicm** [comment]
Yes, this would not be hard to add, but would be best to add it for 10 and 12 also.

**Comment by nicm** [comment]
Try this please - it will only respond to ? if you have set the colour in the first place: [x.diff.txt](https://github.com/tmux/tmux/files/3652793/x.diff.txt)
