### ISSUE TITLE
Tmux 2.1 Seems to No Longer Be Loading /usr/local/etc/tmux.conf

### ISSUE THREAD

**Issue by jfelchner** [tmux/tmux#192]
I put a very simple `tmux.conf` in `/usr/local/etc/tmux.conf` and no dice.  This worked fine on `1.9`.  This is a fresh install of El Capitan.

**Comment by nicm** [comment]
tmux never loaded this file, you must have changed the source when you
built, or someone else did.

**Comment by jfelchner** [comment]
@nicm I'm installing from homebrew. And after install it's in the man page. I'm heading to bed now but I'll dig in in the morning and report back. 

Thanks for the reply. :)

**Comment by jfelchner** [comment]
@nicm if it's compiled like so:

![image](https://cloud.githubusercontent.com/assets/285582/11167081/f7783e26-8b18-11e5-860b-667f05e0f184.png)

Is that what would cause the change in the man page?

![image](https://cloud.githubusercontent.com/assets/285582/11167082/05ca1616-8b19-11e5-894d-d8c3e243cac9.png)

Seems like it's specified properly, but it's not being loaded.

**Comment by nicm** [comment]
Yes but I don't know why we do this because we don't change it in the source and we have never done so.

**Comment by jfelchner** [comment]
@nicm ok that's cool. It's strange because this used to work fine. So I should put the global file where? `/etc/tmux.conf`? And if so, unfortunately that location is now protected on Macs by the rootless protection in El Capitan. :-/ Any other suggestions?

**Comment by nicm** [comment]
I guess your package system changed it in the code but doesn't anymore.

You can try this:

diff --git a/configure.ac b/configure.ac
index a2b9e05..888d267 100644
--- a/configure.ac
+++ b/configure.ac
@@ -22,6 +22,7 @@ AC_PROG_INSTALL
 
 # Default tmux.conf goes in /etc not ${prefix}/etc.
 test "$sysconfdir" = '${prefix}/etc' && sysconfdir=/etc
+AC_DEFINE_UNQUOTED(SYSCONFDIR, "$sysconfdir")
 
 # Is this --enable-debug?
 found_debug=yes
diff --git a/tmux.h b/tmux.h
index f259e6f..3ff60d1 100644
--- a/tmux.h
+++ b/tmux.h
@@ -49,7 +49,7 @@ struct tmuxpeer;
 struct tmuxproc;
 
 /* Default global configuration file. */
-#define TMUX_CONF "/etc/tmux.conf"
+#define TMUX_CONF SYSCONFDIR "/tmux.conf"
 
 /*
  * Minimum layout cell size, NOT including separator line. The scroll region
