### ISSUE TITLE
<S-Left> or <S-Right> is not working properly in vim

### ISSUE THREAD

**Issue by codeMonkeyss** [tmux/tmux#1923]
### Issue description
<S-Left> or <S-Right> is not working properly in vim

### Required information
* tmux 2.1
* Linux x86_64
* xterm-256color

**Comment by krader1961** [comment]
Tmux 2.1 is extremely old. Even OpenSuse, which is extremely conservative, is shipping tmux 2.2.

You didn't provide enough information for anyone to debug your problem. What is the `TERM` value outside and inside your tmux session? What do you mean "is not working properly"? Why does this only affect vim? What do you see when running `od -tx1z` and pressing <S-Left> inside and outside of a tmux session?

**Comment by codeMonkeyss** [comment]
The TERM value is screen-256color inside my tmux session, and xterm-256color outside my tmux session. I can't run `od -tx1z` on ubuntu16.04.

**Comment by codeMonkeyss** [comment]
I think that I have solved it. if the TERM value is xterm-256color, <S-Left/Right> is working properly. Thank you for solving my problem.
