### ISSUE TITLE
tmux does not support bright Base16/ANSI colors

### ISSUE THREAD

**Issue by notuxic** [tmux/tmux#1926]
System
---

**OS** FreeBSD 12-RELEASE amd64
**Terminal** vt (FreeBSDs virtual console)
**tmux version** 2.9a
**$TERM inside** screen
**$TERM outside** xterm

Problem
---

Most colors inside tmux as screwed up. All programs are set up to use ANSI base16 colors (ie. the 16 basic terminal colors), none use 256 colors or TrueColor. When running the 256 colors test script from [print256colours.sh](https://gist.github.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/) I noticed that inside tmux the bright versions of the 8 base colors are replaced by the 8 base colors themselves (see attached pictures).

I noticed, that when running tmux with "-2" flag the colors are correctly displayed. This is a ugly fix though, as the terminal does not support 256 colors (vt supports only the base 16 ANSI colors, although their value can be configured, just like in a graphical terminal emulator), and I don't know if this could fool programs running inside tmux to assume they can use 256 colors, even though only the base 16 are supported.

![DSC_0082](https://user-images.githubusercontent.com/6146545/66073286-15abb200-e557-11e9-9e29-5c8c99d63161.JPG)
![DSC_0083](https://user-images.githubusercontent.com/6146545/66073287-16444880-e557-11e9-8939-496225ddd131.JPG)

**Comment by nicm** [comment]
TERM=xterm does not specify 16 colours, it specifies 8 colours.

**Comment by notuxic** [comment]
Interesting. It is the $TERM set by vt which does support 16 colors, and other applications work fine. But now that behavior seems reasonable. Guess I'll just use the "-2" switch when using it in vt then. Does that switch only affect tmux' behavior, or might applications run inside assume there's 256 color support? Because setting another $TERM seems like an even worse idea...

**Comment by nicm** [comment]
-2 only affects tmux (it is equivalent to colors#16 in terminfo), applications inside tmux will (should) decide whether to use 256 colours based on the TERM inside tmux, and if that is screen rather than screen-256color then they shouldn't.

You could use terminal-overrides to set colors#16 for xterm but then you will get tmux's translation of the 256 colour palette rather than the terminal - if you are happy with the job the terminal does you may as well do -2 or use xterm-256color outside tmux.

**Comment by notuxic** [comment]
Thanks for the quick help. I'll use -2 then, changing the TERM=xterm-256color will definitely create more problems. On my side this issue would be solved now.

**Comment by nicm** [comment]
If you are already using TERM=xterm outside tmux then there is no difference between tmux -2 and using xterm-256color, they will both cause tmux to send the same escape sequences for 256 colours.
