### ISSUE TITLE
respawn-pane / respawn-window no longer restart with the window's command

### ISSUE THREAD

**Issue by jbarbero** [tmux/tmux#1928]
In tmux-2.7, I would start new windows in a startup file like this:

tmux new-window -d -n HOST ssh HOST -t bash -l -c "\\"tmux -2 .....\\""

I would get a series of nested tmux sessions over ssh in windows 0, 1, 2, etc.

Every time my laptop got disconnected from the network, I would run `respawn-pane -k` (bound to a shortcut). tmux would re-run the command and I would get my remote session back. This is a workflow I ported over from my GNU screen days.

Yesterday I built tmux from HEAD and the behavior has changed. I tried both respawn-pane and respawn-window but they just start a new shell window. To get my session back, I have to re-run my `tmux new-window ... ssh ...` command, then move it into place again. This is a regression that makes using tmux way more painful.

Is this a deliberate change or just a bug? If deliberate, is there a way to get tmux to re-run the command when I do respawn-pane / respawn-window, the way it used to work?

Thanks!

**Comment by nicm** [comment]
Works for me. Logs?

**Comment by jbarbero** [comment]
I'm still working on logs, but I was able to narrow it down by bisecting my .tmux.conf options. The problem is this:

if-shell "uname | grep -q Darwin && which /usr/local/bin/reattach-to-user-namespace" "set -g default-command '/usr/local/bin/reattach-to-user-namespace -l $SHELL'"

It looks like set -g default-command is overriding respawn-pane's behavior. This is a change from 2.7. I've had this conf option on under 2.7 and respawn-pane would still restart my ssh sessions correctly. In 3.1, default-command is what is invoked.

Attached are log files at -vv and -v verbosity, plus a minimal conf file to reproduce.

[tmux.conf.minimal.txt](https://github.com/tmux/tmux/files/3692291/tmux.conf.minimal.txt)
[tmux-v-server-37820.log](https://github.com/tmux/tmux/files/3692293/tmux-v-server-37820.log)
[tmux-v-client-37818.log](https://github.com/tmux/tmux/files/3692294/tmux-v-client-37818.log)
[tmux-vv-out-37041.log](https://github.com/tmux/tmux/files/3692295/tmux-vv-out-37041.log)
[tmux-vv-server-37041.log](https://github.com/tmux/tmux/files/3692296/tmux-vv-server-37041.log)
[tmux-vv-client-37039.log](https://github.com/tmux/tmux/files/3692297/tmux-vv-client-37039.log)

**Comment by nicm** [comment]
Try this please:
~~~~
diff -u -p -r1.9 spawn.c
--- spawn.c     23 Sep 2019 15:41:11 -0000      1.9
+++ spawn.c     6 Oct 2019 14:55:09 -0000
@@ -253,7 +253,7 @@ spawn_pane(struct spawn_context *sc, cha
         * Now we have a pane with nothing running in it ready for the new
         * process. Work out the command and arguments.
         */
-       if (sc->argc == 0) {
+       if (sc->argc == 0 && (~sc->flags & SPAWN_RESPAWN)) {
                cmd = options_get_string(s->options, "default-command");
                if (cmd != NULL && *cmd != '\0') {
                        argc = 1;

**Comment by jbarbero** [comment]
Works perfectly, thanks!

**Comment by nicm** [comment]
Applied now, thanks!
