### ISSUE TITLE
Make it possible to implement fzf as the actual list chooser

### ISSUE THREAD

**Issue by chrisjohnson** [tmux/tmux#1929]
### Issue description
Provide some tooling to export the preview pane portion of tmux to be consumed in fzf, or find some way to run fzf as just the list section and map up/down in fzf to update teh tmux preview pane

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 2.9a
* Platform (`uname -sp`).Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`). inside:screen-256color outside:xterm-256color

**Comment by nicm** [comment]
You are going to have to be much more specific.

What is fzf and what does it do? What list chooser, you mean choose-tree?
How would this work? What exact changes or new commands or flags to
existing commands are you suggesting?

**Comment by chrisjohnson** [comment]
Sorry, I mean `choose-tree` that's exactly right. Historically the nicer session choosers were implemented externally by passing the list of sessions/windows/panes to fzf which is a general-purpose fuzzy matcher.

However with choose-tree providing a preview window, it's hard to maintain parity between the two ; I can either use tmux's `choose-tree` list picker logic which isn't as nice to use as fzf, or I can export the list to fzf and lose tmux's preview.

My hunch is that the exact changes I'm asking for is the ability to get the output of that preview window that `choose-tree` shows for a given session/window/pane so I can feed it into fzf's own preview window module. I can manage the rest

**Comment by nicm** [comment]
You can get the contents of a pane using capture-pane.

**Comment by chrisjohnson** [comment]
That's not what `choose-tree -Zw` is using though, which is what I'm asking about. All the color is lost, the little overlays that show the titles aren't present, and in general it doesn't look like what the `choose-tree -Zw` pane looks like.

It also doesn't help for session and window level previews.

**Comment by nicm** [comment]
capture-pane -e will give you colours. You can get the titles and pane IDs and whatnot for the overlays with formats. Window and session previews are just made up of multiple pane previews.

**Comment by chrisjohnson** [comment]
Right, and the request I'm asking for is to expose the wrapper that does that already, so I don't have to reinvent the wheel in a much more brittle way :)

**Comment by nicm** [comment]
I don't mind having a flag to capture-pane to only capture a rectangular portion of a pane (it could default to the area around the cursor like the preview does) if you want to add that but trying to make a way to export exactly what choose-tree shows would be a lot of effort for something of such narrow use.

**Comment by chrisjohnson** [comment]
I don't really get why something like `capture-pane` is ok but an e.g. `capture-session` is not? It doesn't have to be *exactly* how choose-tree does it if you're saying choose-tree applies some extra layers that a `capture-session` would not, but it certainly seems helpful to be able to capture at the higher level.

Either way, I don't really see how I can specify the target session in a `capture-pane` command. When I try `tmux capture-pane -s "$target_session" -e -J -b "dump-$target_session-$target" -t "$target"
` I get `capture-pane: illegal option -- s`

And if I try `tmux -s "$target_session" capture-pane -e -J -b "dump-$target_session-$target" -t "$target"` I get `tmux: illegal option -- s`

**Comment by nicm** [comment]
What do you mean? Sessions have no content of their own, they are just
containers for panes and you can get their content with capture-pane. There
is no point in an additional command that does nothing more than loop over
the panes in a window or windows in a session.

You use -t to specify the pane to capture-pane.

**Comment by chrisjohnson** [comment]
Right, I am specifying the pane with -t in the example I pasted, but how do I specify the session that I'm pulling the pane from? Or is there some more complete form of pane selector that inherently includes the session the pane comes from?

> What do you mean? Sessions have no content of their own, they are just
containers for panes and you can get their content with capture-pane. There
is no point in an additional command that does nothing more than loop over
the panes in a window or windows in a session.

I'm here demonstrating the use-case for the command? I'm not sure where the confusion is coming from. And if it were "nothing more than looping over the panes" then it seems like your earlier premise that it would be a lot of effort to lift it up isn't necessarily true?

**Comment by nicm** [comment]
You specify the session with -t same as all the other commands, look at
https://man.openbsd.org/tmux.1#COMMANDS.

We are not adding a way to export all or part of what tmux draws for tree
mode wholesale, it is too much effort for such a narrow use case. I am open
to adding  features to make it easier to produce similar using the data
from capture-pane  (if I was doing it I would want to be able to capture
only a rectangle around the cursor). These would be both less effort and
more generally useful.

If you want exactly what tmux draws, you can always create a temporary tmux
session, put it in tree mode and attach it in your own pty but personally I
think it'd be easier and more reliable to use capture-pane.

**Comment by nicm** [comment]
If I had time I would write a script to do this for you but I am really
busy this week so I can't. But if I was doing it this is what I would do
using Python or something:

- Walk the output of tmux ls, lsw, lsp to build a tree of sessions, windows
and panes. You can use -F to specify the formats to get exactly what you
want rather than parsing the default, eg tmux ls
-F'#{session_name};#{session_id}'

- For each pane I wanted to look at (however you are going to know this,
command line I guess?), use capture-pane -ep to get the current content.
Parse the SGR escape sequences (tmux will only send SGR from capture-pane)
and build a grid of (attributes, colours,character) tuples.

- Then I can draw all or part of the pane content anywhere I like, so I'd
use ncurses or more likely just plain ACS line drawing to draw everything
the way I wanted and include bits of the panes I want from the grid I built
earlier.

It should definitely be possible, would probably take a day to get it right.

**Comment by kevinhwang91** [comment]
![2020-02-28-12-53-50-lanczos](https://user-images.githubusercontent.com/17562139/75512933-fba2cc80-5a2d-11ea-8259-17420ba60b1b.gif)
@chrisjohnson @nicm  I think I had implemented this demand.
Here is the script:
https://github.com/kevinhwang91/dotfiles/blob/master/script/shell/fzf_panes.tmux
If you want to test the script, please add these three lines to conf:
```tmux
set -s focus-events on
set-hook -g pane-focus-in "run -b 'sh script_path update_mru_pane_ids'"
bind w run -b 'sh script_path new_window'
```
if you want to access the path of the current buffer of vim dynamically in fzf field of cmd, please set these two lines in your conf of vim:
```vim
set title
set titlestring=%(%m%)%(%{expand(\"%:~:.:h\")}%)\/%t
```
