### ISSUE TITLE
Tmux 2.1 doesn't work with iTerm shortcuts that send hex codes

### ISSUE THREAD

**Issue by samuelsimoes** [tmux/tmux#193]
The Tmux version 2.1 doesn't work anymore with iTerm hex code shortcuts (feature described here http://www.codeography.com/2013/05/16/tmux-iterm-keybindings.html). I don't know if it's a issue related to Tmux or iTerm. I compiled the version 2.0 and everything was running smoothly, after this version the shortcuts stopped working.

_My iTerm version is 2.1.4 running on El Captain._

**Comment by nicm** [comment]
Turn down assume-paste-time or try tmux from Git.

**Comment by orebokech** [comment]
Do you know off the top of your head which commit in Git fixes this?

**Comment by samuelsimoes** [comment]
Thanks @nicm, `set -g assume-paste-time 0` did work. :+1:
