### ISSUE TITLE
Server crash with `tty_clamp_area: y too big`

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [tmux/tmux#1930]
###  Description

tmux server reproducibly crashes with `fatal: tty_clamp_area: y too big, 4294967295 > 0` error when outputting text from command that overflows pane height, being run from specific pane layout.

### Runtime

* OS = macOS 10.12
* Terminal = iTerm2 v3.3.5beta3
* tmux version = `next-3.1` @ 341b330a04959bc4bce47c50f73493c26fcd0b60
* `$TERM` inside tmux = `screen-256color`
* `$TERM` outside of tmux = `xterm-256color`

### Reproduction steps

1. `$ tmux -vvv -f empty_file` (`empty_file` is just empty file, to ensure that case is not `tmux.conf` dependent)
2. `$ tmux splitw`
3. `$ tmux splitw -h`
4. `$ tmux select-layout 3b9d,364x98,0,0\[365x63,0,0,19,365x35,0,64\{181x35,0,64,20,183x35,182,64,21\}\]`
5. `$ python --help`
    Situation before pressing `<CR>`
    ![image](https://user-images.githubusercontent.com/2079110/66260529-7c83d200-e7c8-11e9-976d-3ff628644b42.png)
6.  Server is lost upon pressing `<CR>` 
    ![image](https://user-images.githubusercontent.com/2079110/66260532-89082a80-e7c8-11e9-9714-1fd97fabcc00.png)

### Logs

[tmux-server-46468.log](https://github.com/tmux/tmux/files/3693679/tmux-server-46468.log) _N.B. Lightly redacted `ENV` setup_
[tmux-client-46466.log](https://github.com/tmux/tmux/files/3693680/tmux-client-46466.log)
[tmux-out-46468.log](https://github.com/tmux/tmux/files/3693681/tmux-out-46468.log)

---

Issue looks very similar to https://github.com/tmux/tmux/issues/1736 . At first I thought that just having `2.9a` + https://github.com/tmux/tmux/commit/38b8a198bac62c16d351c54ed83ead29a2e0ecc8 would be sufficient to mitigate, however it persisted even in `master`.

Possible some reports after https://github.com/tmux/tmux/issues/1811#issuecomment-531164984 may also be caused by this problem.

Don't have currently time to bisect but the `2.6` version is __not affected__.

**Comment by nicm** [comment]
How did you generate this layout?

**Comment by aleksandrs-ledovskis** [comment]
The layout come from a [tmuxinator](https://github.com/tmuxinator/tmuxinator) configuration & previously wasn't observed to cause issues

Value `3b9d,364x98,0,0\[365x63,0,0,19,365x35,0,64\{181x35,0,64,20,183x35,182,64,21\}\]` was observed using `$ tmux list-windows` after a manual resizing (some long time ago, probably pre `2.6` even)

**Comment by nicm** [comment]
This layout is not valid, you can see the width of the inner cells is too big - 365 rather than 364. There must have been (or possibly still is) a bug allowing the layout to be created. I expect older versions of tmux were more tolerant of this - before panes could be partly hidden it didn't really have to care.

You can see that a similar correct layout has the right width throughout (143 for both the top cell and the two top-bottom splits): 1b1e,143x42,0,0[143x35,0,0,0,143x6,0,36{70x6,0,36,1,72x6,71,36,2}]

I think it is relatively simple to just fix this, so we should do that, and also add a check to detect and reject any layouts where the size of inner cells are wrong.

Please try this diff: [x.diff.txt](https://github.com/tmux/tmux/files/3694498/x.diff.txt)

**Comment by aleksandrs-ledovskis** [comment]
@nicm Applying patch over current `master` does indeed help. I cannot reproduce the issue anymore, both with reported repro lean steps and real-life scenario. 👏

For reference, here are couple additional layouts from my tmuxinator projects that also seem to exhibit invalid width

- `0007,240x86,0,0[241x28,0,0{120x28,0,0,77,120x28,121,0,84},241x28,0,29{120x28,0,29,85,120x28,121,29,86},241x29,0,58{120x29,0,58,87,120x29,121,58,88}]` (240 < 241)
-  `2674,272x66,0,0[273x33,0,0{136x33,0,0,5,136x33,137,0,22},273x33,0,34{136x33,0,34[136x16,0,34,18,136x16,0,51,23],136x33,137,34[136x16,137,34,19,136x16,137,51,24]}]` (272 < 273)

These two were also generated by `$ tmux list-windows` (of version `2.5` probably, since I just recently moved to `2.9a`,`3.1` territory), so it doesn't look like a very rare occurrence.

---

Waiting for patch to land in Git and will then make a PR to Homebrew with both fixes over `2.9a`.

**Comment by nicm** [comment]
Applied now, thanks!

**Comment by aleksandrs-ledovskis** [comment]
Great. For reference, the Git commit/fix is bbe8ebf9c26e45fd8c402627b84b3646db445d45

**Comment by zyy7259** [comment]
Will there be a patch release for this?

**Comment by nicm** [comment]
It will be in 3.0 although I am undecided when that will be released.

**Comment by zyy7259** [comment]
OK

Here is a [solution](https://github.com/yarnpkg/yarn/issues/1882#issuecomment-421372892) for anyone who want to use an older version of tmux via homebrew
