### ISSUE TITLE
tmux sometimes reorders mouse button presses and releases

### ISSUE THREAD

**Issue by fornwall** [tmux/tmux#1931]
* tmux version (`tmux -V`):
Verified on `2.9a` and `2.7`.
* Platform (`uname -sp`).
`Linux x86_64`.
* $TERM inside and outside of tmux (`echo $TERM`).
`xterm-256color` and `screen-256color`.
* tmux.conf:
`setw -g mouse on`

[Termux](https://termux.com/), a terminal emulator for Android, under certain conditions (related to handling finger touch events) writes mouse button press and release events directly after another, here shown using SGR mouse tracking: `\e[<0;5;5M\e[<0;5;5m`.

It seems that sometimes/quite often tmux reorders these sequences, sending the button release sequence (`m`) before the button pressed (`M`) one, as seen in this recording: https://asciinema.org/a/9RECJwPr2eVUN4NfwVun8nUUQ

Minimal steps to reproduce here:
- Install Termux.
- Run tmux (either on the device or ssh into another machine running tmux) with mouse enabled (`setw -g mouse on`).
- Touch the screen repeatedly to send mouse events while inspecting the escape sequences received from tmux.
- Expected: The button pressed sequence (`M`) should always come before the released one (`m`).
- Actual: The button released sequence (`m`) sometimes comes before the pressed one (`M`).

**Comment by nicm** [comment]
Logs?

**Comment by nicm** [comment]
Also does this still happen with master?

**Comment by nicm** [comment]
I can't reproduce with master...

**Comment by fornwall** [comment]
@nicm I can't reproduce with master either, so it seems to be fixed. Nice work!

Do you know of any specific commit if I would try patching a `2.9a` version? Otherwise I can just await 3.0, it doesn't look so far away :).

**Comment by nicm** [comment]
Great - I don't know, if you can't figure it out best bet is to wait.

**Comment by fornwall** [comment]
For reference, this seems to be the fixed (verified by building a 2.9a version with that patch applied): https://github.com/tmux/tmux/commit/33298d6df67e2ba3d90abdc94250eeaa963c3730.patch
