### ISSUE TITLE
Statusline layout to fit window list into visible area

### ISSUE THREAD

**Issue by jbarbero** [tmux/tmux#1932]
It would be nice if there was a status layout option that would cause the statusline to display all windows, but fit them into the visible area by cutting off their widths. The behavior would be similar to browser tabs or taskbars, rather than the current GNU screen-like behavior. I think some users would prefer the option for all windows to show up.

A related style option that would be nice would be to have all the windows displayed in the statusline start with the same width, even if it means padding with spaces when the window title is short. This is the way tab bars and taskbars behave: tabs have a minimum width, and they all stay the same size when they shrink, even if the text they have to display is shorter.

These features would make tmux windows easier to visualize as having a concrete size and location, which I think helps make the UI more intuitive.

**Comment by nicm** [comment]
This would be difficult because it would need trimming based on the total width which would be hard to express in status-format.

It would be relatively easy to make names have a fixed width by adding a modifier to do it that could then be used for each in status-format.

**Comment by jbarbero** [comment]
Thanks! I think it could be done with a bit of shell given these other features:
- a hook for after-kill-window
- a way to combine =width: and =E:, so that I could trim the result of an expression rather than just a named variable.
- ideally, but not essential, a way to trim the result of an expression based on another format variable

Yeah, I can see that doing it within tmux would be involved. Maybe by keeping a per-session tmux format variable to express the size of an autofit window. It would be (client_width - status-left-width - status-right-width) / session_windows. It would have to be updated on every statusline redraw. Then it would still need the trimming enhancements above.

Anyway, it all sounds complicated, so feel free to close, there are probably much more interesting enhancements to work on. thanks!

**Comment by nicm** [comment]
None of those would be hard to add individually. window-unlinked is probably the hook you want rather than after-kill-window. But what about stuff like automatic rename?
