### ISSUE TITLE
Search in copy mode doesn't find matches wrapped across lines

### ISSUE THREAD

**Issue by wellle** [tmux/tmux#1935]
Hey. I just got confused because searching in copy mode didn't find what I was expecting to be visible on screen. Turns out it was there, but visually broken into two parts by a line break because a long line gets wrapped.

Here's an example to reproduce. Type some characters to get close to the end of right border of the pane. Then start typing a long word so it gets wrapped. In my case it now looks like this:

![Screenshot 2019-10-11 12 21 23](https://user-images.githubusercontent.com/474504/66644729-f7fade80-ec21-11e9-9a44-fc9740464cef.png)

Now enter copy mode and search backwards for your word, `bbbbbbbb` in my case. It doesn't find it because it's visually split.
- [ ] this match should still be found

For context, when I change the pane width so that the target word is no longer split, like this:

![Screenshot 2019-10-11 12 21 45](https://user-images.githubusercontent.com/474504/66644819-2b3d6d80-ec22-11e9-8d61-9567ea9aea57.png)

If I enter copy mode now and search for `bbbbbbbb` it finds it now as expected.

* tmux version (`tmux -V`). `tmux 2.9a`
* Platform (`uname -sp`). `Darwin i386`
* $TERM inside and outside of tmux (`echo $TERM`). `screen-256color`

**Comment by laxdog** [comment]
I can confirm this behaviour on 
`tmux next-3.1` @ 7323ffee
macOs : 10.14.6
$TERM = `xterm-256color` (inside and out)

**Comment by nicm** [comment]
Yes this is already known and on the todo list:
~~~~
- Searching in copy mode should handle wrapping, so a search for "foobar" then
  it should be found even if wrapped into "foo\nbar" (that is, the
  GRID_LINE_WRAPPED flag is set on the line).
