### ISSUE TITLE
BiDirectional text support

### ISSUE THREAD

**Issue by XVilka** [tmux/tmux#1936]
In the modern world, the support for some languages that are right-to-left and mixing them with left-to-write words and numbers is crucial for a different software. At some point, this should be supported everywhere, including the console.

I started to gather the information about BiDi support in various console terminals (and programs) in analogy with true color crusade at https://gist.github.com/XVilka/a0e49e1c65370ba11c17

New [console BiDi specification](https://terminal-wg.pages.freedesktop.org/bidi/) was recently implemented in libvte by @egmontkob: https://terminal-wg.pages.freedesktop.org/bidi/implementations.html#vte

Note, that with the release of [GNOME 3.34](https://www.gnome.org/news/2019/09/gnome-3-34-released/) the support of BiDi is available in Gnome Terminal out of the box, which makes testing/implementing it in the other programs, such as tmux way easier.

**Comment by nicm** [comment]
OK thanks.

**Comment by XVilka** [comment]
Closed as "wont fix" or what?

**Comment by nicm** [comment]
I am not planning to work on this in the short term but perhaps at some
point.
