### ISSUE TITLE
Search for tmux.conf also in ~/.config/tmux/tmux.conf

### ISSUE THREAD

**Issue by astier** [tmux/tmux#1939]
It would be nice if tmux would search for the conf-file also in *~/.config/tmux/tmux.conf*. This follows the XDG standard and many people prefer to keep their config files in *~/.config* because this helps to keep the home-directory clean. tmux.conf is currently one of the few config-files which I still store in the home-directory.

love your program <3 thx

**Comment by nicm** [comment]
No we are not going to do this, you can use -f if you want tmux to load a different config.

**Comment by astier** [comment]
Ok I respect your decision. Out of interest, are there any specif reasons?

**Comment by nicm** [comment]
Everyone has their own preference for where stuff goes. Hidden files in ~ are the standard so that is what we do by default.

**Comment by astier** [comment]
Oh no, I didn't mean that this should be the new default. The default should be kept. I just meant that if the config file couldn't be found in ~ then it could be searched in ~/.config This way both preferences would be supported while keeping the default behavior.

**Comment by nicm** [comment]
Right but what if someone wants it somewhere else, do we add that too?
We're not adding any more options, there is -f to specify wherever you want.

**Comment by astier** [comment]
Thank for the reply.

**Comment by FranklinYu** [comment]
@astier You may also be interested in #142.

**Comment by astier** [comment]
@FranklinYu thanks. the decision not to support its still doesn't make sense to me.

**Comment by FranklinYu** [comment]
@astier I agree, but good luck persuading the maintainers. They seem very determined.

**Comment by astier** [comment]
I would like to propose another solution. This would be to export an environment variable like `TMUXRC` with the path to the config-file. Tmux the just must check if this variable is set then it should use the defined config-file. This would solve this issue ones and for all and all other future potential requests for all kinds of tmux.conf-directories in a very easy way.

This approach use many other projects like conda, readline, pylint.

**Comment by FranklinYu** [comment]
FYI this was proposed in https://github.com/tmux/tmux/issues/142#issuecomment-222522107

**Comment by nicm** [comment]
I don't want any more horrible environment variables. A configure option to change ~/.tmux.conf would be OK.

**Comment by nicm** [comment]
You can try this which makes tmux treat TMUX_CONF as a list and expand any leading ~ or $FOO: [tmux-cfg.diff.txt](https://github.com/tmux/tmux/files/3944652/tmux-cfg.diff.txt)

This means you can just patch Makefile.am with the list of paths you want:

~~~~

~~~~

**Comment by nicm** [comment]
Try this please, this is the version with `~/.config/tmux/tmux.conf`: [tmux-cfg2.diff.txt](https://github.com/tmux/tmux/files/3944694/tmux-cfg2.diff.txt).

**Comment by nicm** [comment]
I have applied this, so you only need to do this now:
~~~~
--- a/Makefile.am
+++ b/Makefile.am
@@ -11,7 +11,8 @@ EXTRA_DIST = \
 dist_EXTRA_tmux_SOURCES = compat/*.[ch]

 # Preprocessor flags.
-AM_CPPFLAGS += @XOPEN_DEFINES@ -DTMUX_CONF="\"$(sysconfdir)/tmux.conf\""
+AM_CPPFLAGS += @XOPEN_DEFINES@
+AM_CPPFLAGS += -DTMUX_CONF="\"$(sysconfdir)/tmux.conf:~/.tmux.conf:~/.config/tmux/tmux.conf\""

 # Additional object files.
 LDADD = $(LIBOBJS)

**Comment by astier** [comment]
I tried it and it seems to work. Thank you very much for your work.

**Comment by nicm** [comment]
Great I have changed it now, thanks!

**Comment by kevinhwang91** [comment]
@nicm btw, please support XDG_CONFIG_HOME.
