### ISSUE TITLE
Copy text from copy mode, always ending the line with $

### ISSUE THREAD

**Issue by lowking** [tmux/tmux#1941]
### Issue description
- Copy text from copy mode, always ending the line with $。
- Text copied from copy mode is always wrapped automatically。
### Required information

Please provide the following information:

* tmux version (`tmux -V`)：2.9a
* Platform (`uname -sp`)：Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`)：screen
* Logs from tmux (`tmux kill-server; tmux -vv new`)：xterm-256color

**Comment by lowking** [comment]
like this：
> this is a longgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg string in a line

copy result from copy mode:
>this is a longgggggggggggggggggggggggggg$  
gggggggggggggggggggggggggggggggggggggggg$
gggggggggggggggggggggggggggggggggggggggg$ gggggggggggggggggggggggggggggggggggggggg$
ggggggggggggg string in a line

**Comment by nicm** [comment]
Works OK for me.

**Comment by lowking** [comment]
![image](https://user-images.githubusercontent.com/33308659/66969443-19dde080-f0bc-11e9-9d94-530eb6929548.png)
That's what happens when scrolling

**Comment by nicm** [comment]
Your original comment didn't mention scrolling. Please describe exactly
what you are doing to reproduce, also please show tmux logs.

**Comment by lowking** [comment]
- Connect to the server
- view the log
- press prefix+[ (copy mode)
- scroll with the touchpad
this is log file:[tmux.log](https://github.com/tmux/tmux/files/3737849/tmux.log)

**Comment by nicm** [comment]
Does this still happen with tmux built from master?

**Comment by lowking** [comment]
I dont know. 
I installed it by command(brew install tmux). It is master branch?

**Comment by nicm** [comment]
If tmux -V says 2.9a then it is not master, please try to build from Git master and see if the problem still exists.

**Comment by lowking** [comment]
![image](https://user-images.githubusercontent.com/33308659/67061893-4c5b0c80-f194-11e9-957f-bdb16d532343.png)
$ is gone.but the copied text is wrapped automatically

**Comment by lowking** [comment]
tmux next-3.1


> ![image](https://user-images.githubusercontent.com/33308659/67061893-4c5b0c80-f194-11e9-957f-bdb16d532343.png)
> $ is gone.but the copied text is wrapped automatically

**Comment by nicm** [comment]
How are you copying the text?

**Comment by lowking** [comment]
select with cursor，than press command+c

**Comment by nicm** [comment]
You need to use tmux's copy with C-w in copy mode if you want line wrapping to be preserved in all cases.

**Comment by lowking** [comment]
press ctrl+w in copy mode still warp automatically.
when i press ctrl+w in copy mode then it exit copy mode.

**Comment by nicm** [comment]
You need to select text by starting with C-Space first.

**Comment by lowking** [comment]
ctrl+space is switch input method, can not enter select mode.

**Comment by nicm** [comment]
You can use Space instead with vi keys otherwise you will need to change the key binding. Or turn on the mouse in tmux and use it.

**Comment by lowking** [comment]
![image](https://user-images.githubusercontent.com/33308659/67091253-c1ebca80-f1de-11e9-9864-011e208438c2.png)

I tried.But not what I wanted.
This is my mode-keys: emacs, I do not like to use vi.
My need just is copy a long sql in log without warpped. How can I do this?

**Comment by lowking** [comment]
I found the way.
Modify ~/.tmux.conf, append
`set-option -g terminal-overrides ',xterm*:smcup@:rmcup@'`
then can use terminal scrollbar， but when you tail -f your log file, can not scroll by touchpad to view it, only use pageup or pagedown in copy mode.
