### ISSUE TITLE
nested tmux scrolling page output was messed

### ISSUE THREAD

**Issue by lvii** [tmux/tmux#1942]
### Issue description

Nested tmux scrolling page output was messed.
After refreshed page by `<prefix> r` , it would be right.

If I only used outside tmux, NOT nested a new tmux, there was NO this problem.

![img_nested_tmux_scroll_page_messed](https://i.imgur.com/BXurEhK.png)
![img_nested_tmux_scroll_page_refreshed](https://i.imgur.com/9NYglGp.png)

### Required information

nested inside tmux info

* tmux version (`tmux -V`). `tmux 2.7`
* Platform (`uname -sp`). `Linux x86_64` **CentOS 8**
* $TERM inside and outside of tmux (`echo $TERM`). `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`). **NO output**

outside tmux info

* tmux version (`tmux -V`). `tmux 1.8`
* Platform (`uname -sp`). `Linux x86_64` **CentOS 7**
* $TERM inside and outside of tmux (`echo $TERM`). `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`). **NO output**

**Comment by nicm** [comment]
tmux 1.8 is too old and does not support some terminal features used by later tmux versions. Use a newer tmux outside.
