### ISSUE TITLE
/tmux/tmux/archive/ VS /tmux/tmux/releases/download/

### ISSUE THREAD

**Issue by tjt263** [tmux/tmux#1946]
Hi, just wanted to know real quick, the difference between:

- https://github.com/tmux/tmux/archive/

- https://github.com/tmux/tmux/releases/download/

For example:
- 
```
curl -fLs https://github.com/tmux/tmux/archive/2.9a.tar.gz | 
shasum -a 256

0d9cdebe9226d2745a46c018a01cd87aa996b32349335650afba638f42013f1c
```
```
curl -fLs https://github.com/tmux/tmux/releases/download/2.9a/tmux-2.9a.tar.gz | 
shasum -a 256

839d167a4517a6bffa6b6074e89a9a8630547b2dea2086f1fad15af12ab23b25
```
Both links output a file titled: `tmux-2.9a.tar.gz`.

**Comment by nicm** [comment]
You will need to ask GitHub about that.
