### ISSUE TITLE
configure script should check for `yacc`

### ISSUE THREAD

**Issue by ThomasHabets** [tmux/tmux#1947]
### Issue description

```
$ ./configure
[… no errors …]
$ make
[…]
./etc/ylwrap: line 175: yacc: command not found
$ sudo apt install bison
$ make
[… success …]
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
```
$ git show HEAD
commit fb7ce5b5d509db244111e130224f366ced28b228
```

* Platform (`uname -sp`).
Linux Debian 9

**Comment by nicm** [comment]
I've looked at half a dozen configure.ac files that use AC_PROG_YACC (including several GNU ones) and none of them have a separate check for YACC, so it seems rather like just letting it fail is the way it is usually done. I don't particularly mind having an extra check though, perhaps you can suggest what it should look like?

**Comment by JamesKid** [comment]
in centos , use ' yum install byacc '

**Comment by howhow** [comment]
I has same problem for ubuntu-1804, after I install `bison`, it works
