### ISSUE TITLE
Restore of a heavy session leads to [lost server]

### ISSUE THREAD

**Issue by Artem-Schander** [tmux/tmux#1948]
Im sorry to bother you but i could not find a solution by my own. And it bugs me a lot that i can not rely in restoring my session.

Here are the required outputs
![2019-10-18-161132_511x530_scrot](https://user-images.githubusercontent.com/1243826/67101471-f8ffb300-f1c1-11e9-999e-7bc4d9a7f52c.png)

After running tmux -vvv und trying to restore the last session (via resurrect), the last line of the [tmux-server-log](https://gist.github.com/Artem-Schander/8c921c76188be2f83771745608c717dd#file-tmux-server-log)  says: "fatal: offset too big"

I've already checked all i could find (#1675 amongst others) but without success.
BTW. This problem does not occur on my macOs computer.

**Comment by nicm** [comment]
Does this still happen with master? If so please show the whole log file.

**Comment by Artem-Schander** [comment]
Unfortunately yes.
BTW. after it crashes the shell and the promt beak also.
![2019-10-18-174426_320x230_scrot](https://user-images.githubusercontent.com/1243826/67108618-30c12780-f1cf-11e9-8d77-d5c8300762dc.png)
It will not take any input correctly. Just gibberish.

**Comment by Artem-Schander** [comment]
The log file is to large. Pastebin wont take it.
Here it is on my own dotfiles repo: [logfile](https://raw.githubusercontent.com/Artem-Schander/dotfiles/master/tmux-client-9599.log)

**Comment by nicm** [comment]
This log is from 2.9a not master?

**Comment by nicm** [comment]
Can you make this change in grid.c please and show me the log from master?

Please gzip the log and attach it to this issue, I only need the tmux-server*.log file.

~~~~
--- grid.c      24 Sep 2019 20:44:58 -0000      1.100
+++ grid.c      18 Oct 2019 18:10:54 -0000
@@ -112,7 +112,7 @@ grid_extended_cell(struct grid_line *gl,
        if (~gce->flags & GRID_FLAG_EXTENDED)
                grid_get_extended_cell(gl, gce, flags);
        else if (gce->offset >= gl->extdsize)
-               fatalx("offset too big");
+               fatalx("offset too big: %u >= %u", gce->offset, gl->extdsize);
        gl->flags |= GRID_LINE_EXTENDED;

        gcp = &gl->extddata[gce->offset];

**Comment by Artem-Schander** [comment]
Sorry about the wrong version. I followed the steps in your readme.
I‘ll add the zipped log file next monday.

**Comment by Artem-Schander** [comment]
First time i ran the restore in v3 it worked, but than it didn't.
Here is the log.
[tmux-server-25165.log.gz](https://github.com/tmux/tmux/files/3746387/tmux-server-25165.log.gz)

**Comment by nicm** [comment]
I think this is an issue with reflowing a pane to 1 column.

**Comment by Artem-Schander** [comment]
Is there something i can do about it?
How does it come that it worked the first time after updating to v3?

**Comment by nicm** [comment]
I'll take another look sometime this week.

**Comment by Artem-Schander** [comment]
I think the issue is gone.
After I downgraded back to 2.9 and played with my config I can restore my session. The strange thing is that the config is now tha same as it was before.
So I'm closing this issue for now (but it could be that I'll need to reopen it in some time since I did not fix anything)

Thanks for your help.

**Comment by Artem-Schander** [comment]
After some more tries it stopped working again but I think I found the reason.
So if someone stumbles upon this issue while searching for a solution; in my case it was the _restoring pane content config_ from resurrect: `set -g @resurrect-capture-pane-contents 'on'`
