### ISSUE TITLE
OS X Terminal.app crashes on window resize when "Unicode East Asian Ambiguous characters are wide" option is set

### ISSUE THREAD

**Issue by cgull** [tmux/tmux#195]
This is obviously not a tmux bug, but perhaps tmux could avoid triggering it.

I've opened an Apple bug, `rdar://23550420`, for this.
### Steps to Reproduce:
Install tmux 2.1 with Homebrew.

In Terminal.app Preferences, select or create a profile with default settings.

Select that profile, click Advanced tab, click the bottom radio button for "Unicode East Asian Ambiguous characters are wide".

In another terminal emulator (iTerm2, xterm, ...) start/attach a tmux session.

In Terminal.app, open a window with the profile you've modified above (i.e.  Shell -> New Window -> profile-name)

In that window, attach to the same tmux session.

Resize the window (by dragging the lower-right corner) to be larger than the first tmux window, so that tmux shows an outline and filler dots around the smaller shared window size.

Resize the window to be smaller than the first tmux window.  Terminal.app will crash as you drag through the point where the windows match in size.
### Tmux issues:
Tmux is using '·' as filler dots, and Unicode characters from the Box Drawing block.  These are all ambiguous-width characters, and so rendering is a mess when wide ambiguous characters are selected, and I suspect Terminal.app gets itself confused and crashes because of the ambiguous-width characters.  Perhaps tmux could (optionally) use different characters and/or colored borders instead?  The corrupted display (and crash) isn't a big issue for me but I imagine it is for East Asian users.

**Comment by nicm** [comment]
So you are telling me about a bug in Terminal.app (not tmux) when you turn on an option (in Terminal.app) that you don't want to use? :-)

I don't think we need to change anything in tmux. The intent of using box drawing characters is clear and if terminals make a mess of them it is not really up to tmux to solve that.

**Comment by cgull** [comment]
Fair enough. :)  I probably selected the option while I was working on some Unicode bug in Mosh, and then forgot about it.  The Terminal.app crash is entirely out of our hands, but I wanted to document it here in case anyone ran into it.

But I think there is a clear Unicode/i18n issue with tmux drawing ambiguous-width characters and expecting them to always be displayed single-width regardless of the user's terminal configuration.  Perhaps that should be a separate issue.

**Comment by nicm** [comment]
Perhaps it should, but we have been using UTF-8 for ACS for five years and so far you are the only person to mention it, and you don't need it anyway. I expect the best solution would be to just not use UTF-8 for ACS, IIRC it is only for putty anyway.

**Comment by cgull** [comment]
Mosh also doesn't support ACS and requires Unicode for line drawing.

Googling "tmux ambiguous width" shows several pages about the issue, including a patch at https://gist.githubusercontent.com/waltarix/1399751/raw/8c5f0018c901f151d39680ef85de6d22649b687a/tmux-ambiguous-width-cjk.patch, so it's clearly an issue for some people.

**Comment by joeytwiddle** [comment]
My terminal font does not have all the Unicode characters.

I would be happy if I could configure the borders to use plain ASCII characters instead of block characters, as a kind of fallback. For example, `|` and `-` and `+`.

But maybe I'm the only person in the world who wants this.

**Comment by nicm** [comment]
Most fonts should support Unicode line drawing, it is relatively common, I don't particularly want to provide an option to work around those that don't. If you can't choose another font, you can either prevent tmux seeing your terminal as UTF-8 by unsetting LANG, LC_ALL, LC_CTYPE before running tmux, or you should be able to force tmux to always use ACS characters by making a code change like this:

~~~~
--- a/tty-acs.c
+++ b/tty-acs.c
@@ -81,7 +81,7 @@ tty_acs_get(struct tty *tty, u_char ch)
        struct tty_acs_entry *entry;

        /* If not a UTF-8 terminal, use the ACS set. */
-       if (tty != NULL && !(tty->flags & TTY_UTF8)) {
+       if (1) {
                if (tty->term->acs[ch][0] == '\0')
                        return (NULL);
                return (&tty->term->acs[ch][0]);
