### ISSUE TITLE
Feature Request: Change sessions by clicking on session name in status bar

### ISSUE THREAD

**Issue by 0xACE** [tmux/tmux#1956]
Hey, I have thought on this for a while and I figured it's time I ask here...

I find myself frequently using the mouse to click on various `windows` in the status bar to quickly glance over various information, this feature has been good to me.

The problem is though that sometimes I want to switch to another session and doing it without the keyboard is troublesome.

Therefore I would suggest that if you click the `session name` in the tmux status bar: tmux will essentially bring up `<LEADER>s` (basically: `choose-tree -Zs`) allowing me to switch to another session/window without reaching for the keyboard first...

**Comment by nicm** [comment]
You can easily bind this yourself or right-click and use rename from the menu.

**Comment by 0xACE** [comment]
> You can easily bind this yourself or right-click and use rename from the menu.

Alright, I didn't know this was possible.

For anyone else googling this in the future this is what I added to my `~/.tmux.conf`:

`bind -n MouseDown1StatusLeft choose-tree -Zs`
