### ISSUE TITLE
choose-mode is missing documentation in the man page

### ISSUE THREAD

**Issue by jfelchner** [tmux/tmux#196]
I finally upgraded to 2.1 and I always look over the change log to see what needs updated in my configs.  I noticed a new `choose-mode` introduced but when viewing the man page, there's no mention of it.

**Comment by nicm** [comment]
I don't know what you're talking about at all.

**Comment by ThomasAdam** [comment]
We don't document bindings for {emacs,vi}-choice.  However, a lot of these are already bound, hence:

tmux lsk -tvi-choice

For example.

**Comment by jfelchner** [comment]
@nicm [here](https://github.com/tmux/tmux/blob/master/CHANGES#L73)

`choose-window`, `choose-buffer`, `choose-tree`, `choose-session`, `choose-client` all have man entries so I assumed `choose-mode` should also have a man entry.

**Comment by nicm** [comment]
Where does it say choose-mode is a command? Does it work if you try to use it as a command?

**Comment by nicm** [comment]
It should just be read "Choose mode" not "choose-mode".

**Comment by ThomasAdam** [comment]
Yes, that's my fault.  I clearly had 'foo-bar' as a pattern on my typing fingers as I was composing those notes.  Oh well.  I'm not changing it now.
