### ISSUE TITLE
TPM plugins not working

### ISSUE THREAD

**Issue by steakhutzeee** [tmux/tmux#1960]
### Issue description
Hello :)

I'm on Windows 10 using WSL - Ubuntu.

Installed tmux and tpm, the plugins are installed, i can see them in the /plugins directory. Prefix + I is working.

But i don't know why, my plugins are not working... i try to use tmux-resurrect keys to save/restore, but nothing happens.

Installed continuum too, but it's not working. I added info about it in the status bar but that is not working either. I see only 'Continuum Status:'.

Here is my .tmux.conf: https://pastebin.com/V70rVw2T

What i'm doing wrong?

Thanks in advance!
[tmux-client-131.log](https://github.com/tmux/tmux/files/3794976/tmux-client-131.log)
[tmux-out-133.log](https://github.com/tmux/tmux/files/3794977/tmux-out-133.log)
[tmux-server-133.log](https://github.com/tmux/tmux/files/3794978/tmux-server-133.log)

### Required information

Please provide the following information:

* tmux version (`tmux 2.6`).
* Platform (`Linux x86_64`).
* $TERM (`Inside tmux: screen-256colour. Outside: xterm-256color`).
* Logs from tmux (`Logs attached`).

**Comment by nicm** [comment]
I don't know anything about this, you will need to ask the tpm developers.
