### ISSUE TITLE
How to reset palette in specific pane

### ISSUE THREAD

**Issue by jason0x43** [tmux/tmux#1961]
### Issue description

This issue is related to #1894 (it's really the same issue, but that one was closed with no resolution). I use base16-shell on a couple of different systems to manage terminal themes. It sets a theme by using escape codes to change the terminal's color palette. The theme setting scripts check whether they're running in tmx or a regular terminal and use the pass through escape code when necessary.

The issue is that when I log into one of my remote systems, it activates a theme, but when I disconnect, I can't restore my local theme.

When the theme activation script runs on the remote system, it doesn't know it's running in tmux, so it sends the normal terminal escape sequences. This causes the theme to be updated, seemingly permanently, that that specific tmux pane (the one where I'm ssh-ing).

What I _think_ is happening is that, since the remote system is sending normal escape codes instead of using the tmux pass through code, it's updating the palette of the individual pane. That's actually fine (preferable, even). Unfortunately, I haven't figured out any way to restore the default palette in the pane.

Is there any way to reset a pane's state (ideally without destroying the contents), or to read out the current palette values so they can be restored later?

### Required information

Please provide the following information:

* tmux version: `2.9a`
* Platform: `Darwin i386`
* $TERM inside and outside of tmux: inside is `tmux-256color`, outside is `xterm-kitty`

**Comment by nicm** [comment]
If you send the palette reset OSC sequence with empty arguments, so "\033]104\033\\", it will reset the entire palette. 

Or do "send -R' in tmux.

**Comment by jason0x43** [comment]
A `printf "\033]104\033"` has no apparent effect, and while `send -R` does clear the pane, it doesn't reset the colors, so maybe I'm wrong about what's happening.

![2019-11-01 08 33 53](https://user-images.githubusercontent.com/1042866/68025167-86430d00-fc82-11e9-8a64-538386aa1115.gif)

One solution I came up with was to just have the base16-shell script always send non-tmux codes. While that does ensure that the colors in each pane are set properly, it breaks tmux's ability to change the background color in inactive panes, which I find useful.

![2019-11-01 08 35 53](https://user-images.githubusercontent.com/1042866/68025219-ab378000-fc82-11e9-99cf-0e209fcad90a.gif)

**Comment by nicm** [comment]
Sounds like it isn't actually changing the palette then.

**Comment by jason0x43** [comment]
Hmmm...  This is what the script is doing (on the remote system):

```sh
put_template() { printf '\033]4;%d;rgb:%s\033\\' $@; }
put_template_var() { printf '\033]%d;rgb:%s\033\\' $@; }
put_template_custom() { printf '\033]%s%s\033\\' $@; }

put_template 0  $color00
put_template 1  $color01
put_template 2  $color02
...
put_template_var 10 $color_foreground
put_template_var 11 $color_background
put_template_custom 12 ";7" # cursor (reverse video)
```

**Comment by jason0x43** [comment]
Here's a [full script](https://github.com/chriskempson/base16-shell/blob/master/scripts/base16-ashes.sh).

**Comment by jason0x43** [comment]
In my case, on the remote system TERM is "tmux-256color" and TMUX isn't set, while on the local system TERM is also "tmux-256color" and TMUX is set, so the versions of the `put_` functions that are used are the tmux ones and the defaults.

**Comment by nicm** [comment]
Well, palette set and reset works for me:
~~~~
printf '\033[38;5;10mabc\033[0m\n'
printf '\033]4;10;rgb:ff/00/ff\033\\\n'
printf '\033]104\033\\\n'
~~~~

**Comment by jason0x43** [comment]
Ok, that does work, so something else is going on. This is good, though; I have a bit more to experiment with. 😄 

![2019-11-01 09 39 31](https://user-images.githubusercontent.com/1042866/68028554-8f84a780-fc8b-11e9-8951-a072e5ecc39a.gif)

**Comment by jason0x43** [comment]
Ah, it's something to do with the foreground/background block after the palette colors have been set.

**Comment by jason0x43** [comment]
Yeah, setting the foreground or background color is what's causing the issue. Once they're set, tmux is no longer able to set them to the active/inactive colors, or to the underlying terminal fg/bg. 

Is there a way to easily reset those?

**Comment by nicm** [comment]
selectp -P default

**Comment by jason0x43** [comment]
Ah, perfect! This does the trick:

```
printf '\033]104\033\\\n' && tmux selectp -P default
```

Thank you for the quick response!
