### ISSUE TITLE
next-3.1 mouse mode determines current active-pane in a different way with 2.9a

### ISSUE THREAD

**Issue by zozowell** [tmux/tmux#1962]
### Issue description

When you select another pane with mouse, before `select-pane` command takes effect, I understand the default `target-pane` of all commands should be still the old pane in active. This is the behavior of previous version, like 2.9a. But in `next-3.1` the `target-pane` is by default set to the pane where mouse down event happens, no matter before or after `select-pane` command.

For example, I have following config (snippet), it basically implements that, when you change pane, if the old pane is in copy-mode, yank selection and quit from copy-mode.  This works well in 2.9a or previous, but it breaks in next-3.1, for the reason that, I can't send message to last pane by default, while it can be achieved via calling command explicitly with `-t!` option. 

I'm not sure whether it is a regression or incompatibility.

```
bind -n MouseDown1Pane \
     if-shell -Ft= '#{pane_active}' \
       "if-shell -F '#{alternate_on}' \
         \"send-keys -M\" \
	 \"copy-mode ; send-keys -X clear-selection\"" \
       "display-message 'before pane change  #{pane_id}' ; if-shell -F '#{==:#{pane_mode},copy-mode}' \"send-keys -X copy-pipe-and-cancel $yank\" ; \
       select-pane -t= ; display-message 'after pane change #{pane_id}'"
```

output when select another pane (pane 0) with mouse:
```
Fri Nov  1 14:58:00 2019 before pane change  %0
Fri Nov  1 14:58:00 2019 after pane change %0
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`).  tmux next-3.1
* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`). xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
This is what we want - if someone does:
~~~~
tmux selectp -U \; killp
~~~~
It should kill the newly selected pane, not the original pane.

I can't see why this would have changed from 2.9 though.

You should be able to use the mouse target (-t= or -t'{mouse}') which should still be the last pane (although you will need to be running master for it to work inside if-shell). Or use -t! or -t'{last}' like you suggest.

**Comment by zozowell** [comment]
Thanks for the response @nicm ! 

>You should be able to use the mouse target (-t= or -t'{mouse}') which should still be the last pane

In a mouse button down event like `MouseDown1Pane`, the default target pane (i.e. -t= or -t'{mouse}') should be the new pane selected by mouse down, right? tmux manual says as following, and this is a proven truth in a few of my config lines . So, how could `-t=` still be the last pane? 
```
target-session, target-window or target-pane may consist entirely of the 
token ‘{mouse}’ (alternative form ‘=’) to specify the session, window or pane
where the most recent mouse event occurred.
```
> you will need to be running master for it to work inside if-shell

I don't quite follow, what do you mean by `running master` please ?


Anyway, with further testing, I finally found one misunderstanding which is the root of all my confusion, it is : **I always thought `-t'{mouse}'`is opposite side of `-t'{last}'`** . But it is not, the former always targets the pane where mouse down. The later always targets the last active pane before last `select-pane` happened. But mouse down doesn't mean active pane change at all.
 
**In the `MouseDown1Pane` event (and alike events), the default target pane of all commands is not active pane, it's `{mouse}`**.  So, when you mouse down on a new pane, there is no direct way to send command to the current active pane at all. Only way to do it is `select-pane -t= \; send-keys -t! ...`

**Comment by nicm** [comment]
It is the mouse target, ie the pane where the mouse event occurred. So yeah
if you want the previous pane you will need to use -t '{last}'. There is no
way to specify active pane explicitly, that's because all the mouse keys
that care do select-pane before anything else.

**Comment by zozowell** [comment]
@nicm thanks for the confirmation. Close the issue then.
