### ISSUE TITLE
regression: splitting panes does not cause a resize in backgrounded tmux

### ISSUE THREAD

**Issue by asottile** [tmux/tmux#1963]
### Issue description

I've bisected this to 1a9f9c09b4bcc9f99f10190ab91f1aea5206809b which looks intentional however this breaks my usage of `tmux`.  The related issue appears to be #1782 / #1779 

I'm using `tmux` as a test harness for a [`curses` based application](https://github.com/asottile/babi) via a library [`hecate`](https://github.com/DRMacIver/hecate).

The basics for the test are:
- spin up tmux in the background
- interact with tmux in a selenium-webdriver-like way (via `send-keys, etc. to send text / commands / etc.)
- using `capture-pane` to assert output

One particular class of tests I have is testing window resizing. I'm currently using the following approach to validate this:

1. Start tmux at the original size (usually 80x24, but it doesn't really matter)
2. Compute the size split(s) would need to size down the window
3. Use [`split-window`](https://github.com/asottile/babi/blob/6031aed43236d563d57e9beb6f5b266e31cd702c/tests/babi_test.py#L132-L160) to make pane 0 the proper size
4. (afterwards, kill the unneeded panes)

After the patch above, pane 0 is never resized and continues to display at the full width

Here's a simple reproduction using only `tmux` and `nano` -- in this demo `tmux` is started with
enough characters

```bash
#!/usr/bin/env bash
set -euo pipefail

TMUX="${1:-tmux}"

tmux_cmd() { "${TMUX}" -u -L demo-session "$@"; }
msg() { echo -e "\033[1m+ $*\033[m"; }

msg tmux version
"${TMUX}" -V

msg starting tmux...
tmux_cmd new-session -d -x 80 -y 8 nano --ignorercfiles
sleep .5
tmux_cmd send-keys -t0 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
tmux_cmd send-keys -t0 Enter
sleep .5

msg 'this is nano at full width:'
tmux_cmd capture-pane -pt0

tmux_cmd split-window -ht0 -l 50 sleep infinity
sleep .5

msg 'this is nano at smaller width (should have "Modified" + $ at eol):'
tmux_cmd capture-pane -pt0

msg cleaning up...
tmux_cmd kill-pane -t1
# quit nano to exit tmux
tmux_cmd send-keys -t0 '^X'
tmux_cmd send-keys -t0 'n'
sleep .5
tmux_cmd kill-session >& /dev/null || true
```

#### with tmux 2.6

```console
$ ./t.sh /usr/bin/tmux 
+ tmux version
tmux 2.6
+ starting tmux...
+ this is nano at full width:
  GNU nano 2.9.3                      New Buffer                      Modified

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa



^G Get Help  ^O Write Out ^W Where Is  ^K Cut Text  ^J Justify   ^C Cur Pos
^X Exit      ^R Read File ^\ Replace   ^U Uncut Text^T To Spell  ^_ Go To Line
+ this is nano at smaller width (should have "Modified" + $ at eol):
     New Buffer    Modified

aaaaaaaaaaaaaaaaaaaaaaaaaaaa$



^G Get He^O Write ^W Where Is
^X Exit  ^R Read F^\ Replace
+ cleaning up...
```

#### with master

```console
$ ./t.sh ./tmux
+ tmux version
tmux next-3.1
+ starting tmux...
+ this is nano at full width:
  GNU nano 2.9.3                      New Buffer                      Modified

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa



^G Get Help  ^O Write Out ^W Where Is  ^K Cut Text  ^J Justify   ^C Cur Pos
^X Exit      ^R Read File ^\ Replace   ^U Uncut Text^T To Spell  ^_ Go To Line
+ this is nano at smaller width (should have "Modified" + $ at eol):
  GNU nano 2.9.3

aaaaaaaaaaaaaaaaaaaaaaaaaaaaa



^G Get Help  ^O Write Out ^W
^X Exit      ^R Read File ^\
+ cleaning up...
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  ```console
  $ ./tmux -V
  tmux next-3.1
  ```
* Platform (`uname -sp`).
  ```console
  $ uname -sp
  Linux x86_64
  ```
* $TERM inside and outside of tmux (`echo $TERM`).
  ```console
  $ # outside
  $ echo $TERM
  xterm-256color
  $ # inside
  $ echo $TERM
  screen
  ```
* Logs from tmux (`tmux kill-server; tmux -vv new`). (they aren't relevant to my issue which is a behavioural change)

### alternatives?

Is there some other way to have it resize?

**Comment by nicm** [comment]
Hmm no there is no way to make it resize aside from attaching.

**Comment by asottile** [comment]
then probably the patch should be reverted?

**Comment by nicm** [comment]
No it is staying, possibly add a way to ask to resize, or a timeout.

**Comment by asottile** [comment]
seems pretty bad that an optimization breaks this very useful feature

**Comment by nicm** [comment]
Don't exaggerate, it'll be fixed but I'm not just reverting it

**Comment by nicm** [comment]
I think it might be best just to always resize all panes if the window is not in an attached session - the only way windows that are only in unattached sessions can be resized is if someone explicitly asks for it to happen (with splitw, resizew or whatnot).

The target of this change is attached sessions which are being resized a lot (dragging X window to resize or a window manager that is crazy with resizing), so this will keep that and make your use case work.

Can you try this please and see if it fixes it? [tmux-resize.diff.txt](https://github.com/tmux/tmux/files/3799424/tmux-resize.diff.txt)

**Comment by asottile** [comment]
yep that fixes it :tada: 

```
$ bash t.sh ./tmux
+ tmux version
tmux next-3.1
+ starting tmux...
+ this is nano at full width:
  GNU nano 2.9.3                      New Buffer                      Modified

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa



^G Get Help  ^O Write Out ^W Where Is  ^K Cut Text  ^J Justify   ^C Cur Pos
^X Exit      ^R Read File ^\ Replace   ^U Uncut Text^T To Spell  ^_ Go To Line
+ this is nano at smaller width (should have "Modified" + $ at eol):
     New Buffer    Modified

aaaaaaaaaaaaaaaaaaaaaaaaaaaa$



^G Get He^O Write ^W Where Is
^X Exit  ^R Read F^\ Replace
+ cleaning up...
```

**Comment by nicm** [comment]
Applied now, thanks!
