### ISSUE TITLE
Potential NULL dereference

### ISSUE THREAD

**Issue by ManSoSec** [tmux/tmux#1966]
We found the following inconsistency in the code, which may lead to NULL dereference:

It seems this check `if (item != NULL)` is missed here:

https://github.com/tmux/tmux/blob/4408df1e8aa1662b197117e1eee13344d4c1d63e/notify.c#L89-L94

As it is checked here:

https://github.com/tmux/tmux/blob/4408df1e8aa1662b197117e1eee13344d4c1d63e/cmd-queue.c#L144-L148

**Comment by nicm** [comment]
I don't think item in notify_insert_hook can ever be NULL, how are you seeing this?

**Comment by ManSoSec** [comment]
Does it mean the `if (item != NULL)` in tmux/cmd-queue.c is unnecessary? The semantic of both code snippets are the same, except their parameters are handled in different ways in the caller. Thanks

**Comment by nicm** [comment]
I think it probably is since it is never called with item == NULL.
