### ISSUE TITLE
[FR] GPM (plain tty) mouse support

### ISSUE THREAD

**Issue by JuniorJPDJ** [tmux/tmux#1967]
Hi guys.
It would be very nice if you could use mouse in tmux without X11/wayland - in plain tty terminal.
GPM provides mouse support in tty, but tmux seems not to work with it.
It could be very handy e.g. in arch linux live usb.
There is similar issue on stackoverflow: https://unix.stackexchange.com/questions/281101/tmux-and-gpm-on-bare-tty#309773

**Comment by nicm** [comment]
I am not particularly keen on adding special code to tmux to make mouse support work on a single terminal, particularly one most people don't really use for long periods, but I would probably accept a diff that did so if it wasn't too invasive.

I think GPM is entirely the wrong approach. The kernel should be reading mouse events and providing escape sequences via the tty in the same way it does for the keyboard.

Another solution would be to write a wrapper program than opens a pty and runs a program inside, forwarding data between the application and the terminal but inserting any mouse events from GPM as escape sequences. Sort of how luit does for Unicode. This would then work for any application, not just tmux.

**Comment by JuniorJPDJ** [comment]
It looks like GPM is providing this events to tty.. At least it should but it doesn't bcs of conflicting with tmux $TERM var. Please take a look in research done in stackoverflow question.
I'm interested in making it work, but I'm not sure how to start.

**Comment by JuniorJPDJ** [comment]
It seems like calling `export TERM=linux` in tmux makes vim interpret mouse events from GPM, but I still can't send this events to remote SSH tmux session. (tmux-ssh-tmux)

**Comment by nicm** [comment]
Oh you're right, it looks like the Linux console does have some
conventional mouse support. If you turn mouse on and the TERM outside has
kmous (which "linux" does) then tmux will use it.

**Comment by JuniorJPDJ** [comment]
I misunderstood how it does work in the first place. It works because vim uses libgpm and connects to gpm daemon directly, even inside tmux (when I set term to linux).
I'll go for wrapper.
