### ISSUE TITLE
tmux resizing issue

### ISSUE THREAD

**Issue by isgy** [tmux/tmux#1968]
### Issue description
the tmux session became unresponsive (due to an application inside it running out of disk space and hanging). I resized the terminal (alacritty) window while it was frozen and then closed it. The application resumed when it had enough disk space. I attached another terminal to the tmux session but it won't fill the entire window (only a small part of the window the same size it was when I closed it).
screencast: https://asciinema.org/a/280011
.tmux.conf: https://hastebin.com/jilevetofu

### Required information

Please provide the following information:

* tmux version: 2.9a
* Platform: archlinux 5.3.7
* $TERM inside and outside of tmux: rxvt-unicode-256color
* Logs from tmux:
tmux-client:
https://hastebin.com/qohibapoqa
tmux-server:
https://hastebin.com/cejepeqena.coffeescript

**Comment by nicm** [comment]
You need to kill or detach the tmux client that was attached in the alacritty window you closed because it is limiting the size. Try C-b D (shift-d) or "tmux detach -a" or "tmux attach -d".

**Comment by isgy** [comment]
thanks, I was just confused because normally it would detach when the window closes..

**Comment by nicm** [comment]
Normally yes, but if the terminal takes a while to go away it will not
detach. Most commonly if using ssh the TCP connection can take a long time
to time out, but could be other reasons.
