### ISSUE TITLE
Leave VERASE setting at the user's preference

### ISSUE THREAD

**Issue by Rhialto** [tmux/tmux#1969]
### Issue description

tmux  (last tested on version 2.9a) forces the VERASE character to be DELETE, instead of leaving it alone at the user's preference. It even forcefully changes typed backspace characters into DELETE, breaking all my terminal settings.

For decades I have set backspace ^H as the erase character, and forced my keyboards to produce the backspace character from the key which is clearly marked backspace.

Tmux seems to think it knows my preferences better than me and forces its own ideas upon me.  My systems are consistent and tmux messes it up.
So I have local patches to fix it: it leaves the VERASE setting alone, so it stays the way you like it. It also doesn't translate keys into DEL any more. I would like these changes included upstream.

If you like DEL as your erase character, there is of course no change from the patch, as you will have set your terminals accordingly already.

I have included my patches below. 
### Required information
```
$ uname -sp && tmux -V && echo $TERM
NetBSD x86_64
tmux 2.9a (problem exists at least in version 2.4 already)
screen (the issue does not depend on this)
```
### Patches that demonstrate how to fix this problem
To neatly apply them you can of course delete the lines of code instead of just stubbing them out like I did.
```
$NetBSD$

Don't mess up the erase character.

--- tty-keys.c.orig	2017-05-16 13:10:11.000000000 +0000
+++ tty-keys.c
@@ -541,7 +541,9 @@ tty_keys_next(struct tty *tty)
 	struct timeval	 tv;
 	const char	*buf;
 	size_t		 len, size;
+#if 0
 	cc_t		 bspace;
+#endif
 	int		 delay, expired = 0, n;
 	key_code	 key;
 
@@ -654,6 +656,7 @@ partial_key:
 complete_key:
 	log_debug("%s: complete key %.*s %#llx", c->name, (int)size, buf, key);
 
+#if 0
 	/*
 	 * Check for backspace key using termios VERASE - the terminfo
 	 * kbs entry is extremely unreliable, so cannot be safely
@@ -662,6 +665,7 @@ complete_key:
 	bspace = tty->tio.c_cc[VERASE];
 	if (bspace != _POSIX_VDISABLE && (key & KEYC_MASK_KEY) == bspace)
 		key = (key & KEYC_MASK_MOD) | KEYC_BSPACE;
+#endif
 
 	/* Remove data from buffer. */
 	evbuffer_drain(tty->in, size);

$NetBSD$

Don't mess up the erase character.

--- window.c.orig	2017-05-29 07:12:06.000000000 +0000
+++ window.c
@@ -919,7 +919,9 @@ window_pane_spawn(struct window_pane *wp
 			fatal("tcgetattr failed");
 		if (tio != NULL)
 			memcpy(tio2.c_cc, tio->c_cc, sizeof tio2.c_cc);
+#if 0
 		tio2.c_cc[VERASE] = '\177';
+#endif
 #ifdef IUTF8
 		tio2.c_iflag |= IUTF8;
 #endif
```

**Comment by nicm** [comment]
No. tmux presents the same interface to applications inside for a key no matter what the terminal outside generates and \177 is what it generates for delete. This is not changing.

**Comment by nicm** [comment]
I am not averse to an option to specify what tmux generates for backspace although instead of changing tty-keys.c you will need to change input-keys.c to special case KEYC_BSPACE.

**Comment by Rhialto** [comment]
Hm, changing the output of the backspace key is a rather roundabout way to make it delete letters. If it would still set DEL for VEREASE it would not even work to make BACKSPACE generate BACKSPACE.  It would me much simpler if it simply followed user preferences (as evidenced in the termios settings). To be very clear: programs that "know better" are very irritating.

**Comment by nicm** [comment]
There is no "know better", if you attach from terminal A which sends \177 for Backspace and terminal B which sends \010 and terminal C which sends something else, tmux can't change what it sends because running programs have already decided what they expect. tmux has to be consistent - backspace is no different here than any other key. tmux needs to figure out what the terminal outside is going to send and translate that to what applications inside should expect. It uses VERASE to work out the former because kbs is often wrong, and always sends \177 for the latter. I don't mind having an option for what it should send but it will be one setting, it will not change depending what the outside terminal sends.

**Comment by Rhialto** [comment]
Let me try to see this in another way. Some programs expect to see ^H to offer certain functionality. Emacs is "famous" for using ^H for is HELP function. I have configured various programs to expect ^H for whatever (typically erase a character but it is not really relevant).
But if tmux translates all instances of ^H to ^?, I have no way of typing ^H any more!

From a viewpoint of consistency, I have come to my setup to specifically because I wanted to have everything consistent. At the university where I grew up on Unix (some 30 years ago) there was lots of different inconsistent equipment to access my Unix account. But there were more methods where ^H for VERASE was practical, so I standardised on that. ^? was probably even used for VINTR on some systems (4.2BSD liked that there, iirc).

**Comment by nicm** [comment]
Thinking about it, we don't actually need any code change, you could just change what it sends yourself with something like:
~~~~
bind -n BSpace send C-h

**Comment by Rhialto** [comment]
Ah interesting approach. Let me try that for a bit.

**Comment by Rhialto** [comment]
I experimented with that for a bit and got some interesting insights. It was so long ago that I initially set this up that I had forgotten some of the details. For instance, the terminal setting for VERASE does not come from my login scrips, but it is set for my xterms in my .Xresources file (and gettytab for consoles).
```
xterm.ttyModes:                 erase ^h
xterm.backarrowKey:             on
xterm.backarrowKeyIsErase:      off
xterm.ptyInitialErase:          off
```
So if I just have `bind -n BSpace send C-h` and start a tmux in a fresh xterm, the internal VERASE character is still ^? because my shell login scripts don't override that.

But even if we put that aside, there would be another problem. If I log in remotely from a "DEL environment" (where the key produces DEL and VERASE is set to match that), tmux would translate ^? to ^H, leaving me no way to type ^? if I really want to.

So I've started to think we are forced to choose between two poisons. If things work "your way", pressing "the key" will indeed erase a character. But in some cases (when logging in from an "opposite environment") there is a character you can't type (either ^H or ^?, depending (ignoring for the moment any other choices for VERASE)).

On the other hand, if things work "my way", then, if I log in from an "opposite environment" and I press "the key", I will get something that does not delete a character. But on the other hand, I can type both ^H and ^? if I really want to (and can find them on the keyboard in front of me).

I can only think of one way to avoid both problems at once, and it is a bit hacky. It would need extra code: if translating the VERASE character effectively maps it into a different character, then there should automatically be made another mapping which is the reverse. So then possibly I can type ^H by sending ^? and vice versa. I haven't looked at what sort of code would be involved for that, or what settings could be involved, or how usable it would be in practice, but I did wan to mention it.

**Comment by nicm** [comment]
You can either configure tmux to send C-h for Backspace (and the opposite as well if you like) and change VERASE in your shell profile as you like, or I would accept a diff adding a single option to tmux to control what it sends for Backspace (and that will also be what it will put in VERASE).

It is not OK to copy VERASE from outside, it needs to be set to what tmux is going to send, and it needs to be the same whether you create the session attached or detached.

When you use a single sequence - whether it be ^H or ^? - for two keys, there will be one of the keys you won't be able to bind no matter what tmux does.

**Comment by Rhialto** [comment]
> It is not OK to copy VERASE from outside

I could not disagree more with that. What the erase character should be is a highly sensitive user preference, and holy wars have been fought over it. The user preference should absolutely be followed in all cases. And the user preference is reflected in the termios settings. I think that in the overwhelming number of cases, when a session is first created, the erase character is set the way the user likes it. (Later, remote, accesses may differ)

I agree that a standardised environment must be presented inside tmux, but it should be standardised according to how the user likes it. After all, **all other** termios special characters are copied (and rightly so). This includes important keys like the VINTR key, which does not have to be ^C but might just as well be ^? (and then it would conflict with the use of ^? as erase). So it cannot reasonably be defended that VERASE is totally exceptional compared to the other *Canonical Mode Input Processing Special Characters* and absolutely must be ^?.

See here some manual fragments from 2.9BSD, 4.2BSD and SUN Unix 0.4 which illustrate how defaults can differ. And yes, I did use 4.2BSD, and my choice of ^H is influenced by that.

https://minnie.tuhs.org/cgi-bin/utree.pl?file=4.2BSD/usr/man/man1/stty.1
```
.BI erase \ c\fR
set erase character to
.I c
(default `#', but often reset to ^H.)
.br
.ns
.TP 10
.BI kill \ c\fR
set kill character to
.I c
(default `@', but often reset to ^U.)
.br
.ns
.TP 10
.BI intr \ c\fR
set interrupt character to
.I c
(default DEL or ^? (delete), but often reset to ^C.)
```
https://www.freebsd.org/cgi/man.cgi?query=stty&apropos=0&sektion=0&manpath=Sun+UNIX+0.4&arch=default&format=html
```
       *erase* /c/	 set erase character to	/c/ (default `^H').
```
https://minnie.tuhs.org/cgi-bin/utree.pl?file=2.9BSD/usr/man/cat1/stty.1
```
     erase _c   set erase character to _c (default `#', but often
               reset to ^H.)
     kill _c    set kill character to _c (default `@', but often
               reset to ^U.)
     intr _c    set interrupt character to _c (default DEL or ^?
               (delete), but often reset to ^C.)
```

**Comment by nicm** [comment]
It would be confusing for VERASE to default inside tmux to something
different from what tmux itself sends for Backspace, and also if it ends up
different for sessions created from somewhere with a tty and those created
from somewhere without.

The difference from the rest of the termios keys is that tmux needs to
recognize Backspace for its own use and it needs to translate it for
programs inside. This is not the case for the other termios keys which
don:t have their own key on the keyboard that tmux needs to understand. TBH
copying the rest of termios was a mistake and is contrary to how tmux
usually works (each pane is a clean environment unless explicitly told
otherwise) but it is done now.

The only good solution is to add an option allowing you to configure what
tmux sends for Backspace. This is no different from what other terminals
like xterm offer. TBH this is something that affects so few users it is a
bit borderline but a single option will not be very much code so it'd be OK.

**Comment by nicm** [comment]
Try this please, you will need to use master: [tmux-bs.diff.txt](https://github.com/tmux/tmux/files/3838195/tmux-bs.diff.txt)

**Comment by Rhialto** [comment]
Thank you, that works nicely when I tried it out just now. I can even set the backspace option from a wrapper script or something, so I can even derive it from the current terminal settings if I just write that wrapper.

I realise that this is as far in my direction as you're willing to go, so I will stop bothering you further and thank you again.

**Comment by nicm** [comment]
Applied now, thanks!
