### ISSUE TITLE
Mouse Scroll No Longer Enters Copy Mode

### ISSUE THREAD

**Issue by jfelchner** [tmux/tmux#197]
In 1.9 when mouse support was turned on, you could swipe up and down (and I'm assuming use the scroll wheel although I don't have a mouse, only a trackpad) and tmux would automatically enter copy mode and scroll through the history.

It seems as though all the mouse options have been removed with only a `mouse` option.  Unfortunately when that is turned on, scrolling via the mouse no longer enters copy mode.

Once _in_ copy mode, the scroll works just fine.

I also looked under `MOUSE SUPPORT` in the man page, but doesn't look like anything there will allow me to perform a binding which will enter copy-mode on scroll.

**Comment by nicm** [comment]
This has been discussed enough already and a key binding added in git.

**Comment by jfelchner** [comment]
@nicm I missed the previous issue. Sorry about that.
