### ISSUE TITLE
Cross Translation Unit (CTU) Static Analysis of Tmux with Clang

### ISSUE THREAD

**Issue by martong** [tmux/tmux#1971]
Dear Tmux Community,

(I am comminicating here because I am not sure if the googlegroups mail list is still active or not.)

[Clang's CTU static analysis](https://clang.llvm.org/docs/analyzer/user-docs/CrossTranslationUnit.html) has evolved a lot in this year. We have chosen Tmux
as one of the projects which we continuously analyze in our CI loop to
safeguard the quality of CTU analysis. We thought that the results might be
interesting for you Tmux developers too. So, we stored the [results for one run on a
 demo server for version 3.0](http://codechecker-demo.eastus.cloudapp.azure.com/Default/#run=tmux_3.0_CTU&review-status=Unreviewed&review-status=Confirmed&detection-status=New&detection-status=Reopened&detection-status=Unresolved&tab=tmux_3.0_CTU). Please use demo/demo to log in. If you find
any false positive or if you have any other comments then we would be happy to receive
your feedback.

Sincerely,
Gabor Marton (CTU developer)

**Comment by martong** [comment]
@dkrupp @gyorb

**Comment by nicm** [comment]
These are almost all false positives although admittedly some of them would be hard for a code checker to work out:

window-client.c - data->item_list can't be NULL unless data->item_size is 0
imsg.c - likewise, if imsg->data is NULL, datalen is 0
options.c - OPTIONS_IS_COMMAND(o) can't be false on line 370 and 389 and then true on line 411 in the same function; this code is a bit confusing however (GCC gets this wrong also) and the code has been changed in master to be clearer
window-tree.c - same as window-client.c
cmd-queue.c - cmd->group can never be 0 (it comes from cmd_list_next_group via the cmdlist) so shared will always be initialized on the first loop; it is probably a bit much to expect a static checker to know this though
mode-tree.c - this can only happen if there are no entries in the list and that should never happen, although it is hard to prove
grid.c - grid_string_cells it is a requirement that lastgc is set if with_codes is true - there are only two callers
spawn.c - in spawn_window, if sc->flags & SPAWN_RESPAWN is false on line 94, then ~sc->flags & SPAWN_RESPAWN cannot also be false on lines 149 and 179. this looks very strange, does it think that (x & a) == (~x & a)?
tty-keys.c - tty_keys_build, the loop upper bound is static and fits well within a u_int
tty-keys.c - tty_keys_clipboard, absolutely nobody cares about this

I don't have time to look at the rest.

**Comment by martong** [comment]
> These are almost all false positives although admittedly some of them would be hard for a code checker to work out:
> 
> window-client.c - data->item_list can't be NULL unless data->item_size is 0
> imsg.c - likewise, if imsg->data is NULL, datalen is 0
> options.c - OPTIONS_IS_COMMAND(o) can't be false on line 370 and 389 and then true on line 411 in the same function; this code is a bit confusing however (GCC gets this wrong also) and the code has been changed in master to be clearer
> window-tree.c - same as window-client.c
> cmd-queue.c - cmd->group can never be 0 (it comes from cmd_list_next_group via the cmdlist) so shared will always be initialized on the first loop; it is probably a bit much to expect a static checker to know this though
> mode-tree.c - this can only happen if there are no entries in the list and that should never happen, although it is hard to prove
> grid.c - grid_string_cells it is a requirement that lastgc is set if with_codes is true - there are only two callers
> spawn.c - in spawn_window, if sc->flags & SPAWN_RESPAWN is false on line 94, then ~sc->flags & SPAWN_RESPAWN cannot also be false on lines 149 and 179. this looks very strange, does it think that (x & a) == (~x & a)?
> tty-keys.c - tty_keys_build, the loop upper bound is static and fits well within a u_int
> tty-keys.c - tty_keys_clipboard, absolutely nobody cares about this
> 
> I don't have time to look at the rest.

Thank you for your feedback. We are going to investigate the false positive results and we are going to find out if we can improve the analyzer to avoid similar false positives in the future.

**Comment by martong** [comment]
> mode-tree.c - this can only happen if there are no entries in the list and that should never happen, although it is hard to prove

Just a quick note, an `assert(...)` on that condition could guide the analyzer to avoid a false assumption.
See for example how bitcoin guys solves some of the warnings in their code:
https://github.com/bitcoin/bitcoin/issues/17454#issuecomment-553100712

**Comment by nicm** [comment]
I don't really want to clutter the code with that sort of stuff. Maybe if that was the only warning left :-).
