### ISSUE TITLE
Google group locked or disappeared?

### ISSUE THREAD

**Issue by hmijail** [tmux/tmux#1972]
The README.md mentions the tmux-users Google Group, but when I try to access it I get a message saying 
> This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.

Either the mention of the group should be removed, or some instructions need to be added about how to access it.

**Comment by krader1961** [comment]
I'm guessing you don't have a Google account. The ksh-users (Korn shell users) mailing list I setup a year ago also inadvertently did not flag the discussion group as publicly visible (i.e., to people without a Google account). What you describe is similar to a discussion group visibility issue the ksh project recently resolved. If you don't have a Google account the fix by the discussion group owner is simple. If you do have a Google account then everything I just wrote is irrelevant.

**Comment by hmijail** [comment]
I do have a Google account and I am logged in.

**Comment by krader1961** [comment]
@hmijail Then are you saying that `https://groups.google.com/forum/#!forum/tmux-users` doesn't work? Or are you referring to some other link?

**Comment by hmijail** [comment]
Yep, that link shows the message I mentioned.
For comparison, I can access https://groups.google.com/forum/#!forum/consul-tool just fine.

**Comment by nicm** [comment]
Try now please.

**Comment by hmijail** [comment]
Now it works, thank you.
