### ISSUE TITLE
memory leak on big buffer even after :clear-history

### ISSUE THREAD

**Issue by ik5** [tmux/tmux#1973]
When having big history buffer (using `tail -f` ) a lot of memory is slowly allocated.
When doing `:clear-history`, the output is trimmed, but tmux keeps on allocating new memory for output, never releasing it back.
Only closing all windows and panes (making tmux to closed) release back the memory to the system. 
If I only kill all the panes and kill a session, if there are additional sessions, the memory was not freed for me.

---

### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 2.9a`
* Platform (`uname -sp`): `Arch Linux 5.3.10-arch1-1 x86_64`
* $TERM inside and outside of tmux (`echo $TERM`): `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
glibc is very poor about releasing memory back to the kernel. You could try playing with M_TRIM_THRESHOLD_ (see mallopt(3) environment variables).
