### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by michaelklachko** [tmux/tmux#1976]
Feature request: scroll bar in mouse mode.

I use tmux 2.6 in Windows 10 WSL console window to launch long running simulations which produce a lot of output. Currently when I enter scroll mode with `Ctrl + B, [`  with mouse mode on I don't see a scroll bar. So I have to either use up/down buttons, or mouse scrolling wheel, neither of which is fast.

**Comment by nicm** [comment]
tmux has no control over the terminal scroll bar (except for an experimental feature in mintty and I haven't got around to looking at this yet) and I don't really want to add an internal scroll bar.

**Comment by michaelklachko** [comment]
I'm confused: when I open WSL console window, there's a scroll bar. As soon as I type tmux, it disappears. Can you prevent this from happening? 

Any specific reasons you don't you want to add a scroll bar to tmux (if there's no way to prevent tmux to interfere with initial console scroll bar)? I mean you added mouse support, so it would make sense to have a scroll bar if you have a mouse, don't you think?

**Comment by nicm** [comment]
tmux has no control over the terminal scroll bar, when it chooses to hide
it is up to the terminal. Probably it is hiding it in cursor positioning
mode which is sensible since there is no scrollback.

I don't mind having a scrollbar in copy mode but it would be a bit of work
and I don't have any inclination to do it particularly. If you want to do
it, go ahead :-).

**Comment by nicm** [comment]
This makes tmux set up the application scrollbar in mintty but it only supports the arrow buttons, not "click to go here" which requires further work: [sb.diff.txt](https://github.com/tmux/tmux/files/3868926/sb.diff.txt)

You need `set -as terminal-overrides ',*:Asb'` in .tmux.conf.

I don't intend to work on this any further right now but I am putting it here so I don't lose it.
