### ISSUE TITLE
Poor Man's Padding

### ISSUE THREAD

**Issue by jfelchner** [tmux/tmux#1978]
### Issue description

I looked in the man page and can see how to truncate a variable expansion, but I can't see how to pad a variable expansion.  Unfortunately I want to do this in `choose-client` via `-F`.  I tried using the shell expansion (so that I can use `printf`) but that isn't working since every use of it shows "not ready" (eg `printf '%s' 'foo' not ready`).

Is there a hacky way to make this work?  I've tried using the `E` flag to expand twice, etc, but can't find a combination that works.

Here's an example of what I would like:

```
choose-client -F '#{=30:session_name}'
```

Where session name would be truncated to 30 if it was too long, or padded to 30 if it was too short.

I'm fine with hacky, so even if doing something like this:

```
choose-client -F '#{=30:#{session_name}                           }'
```

would be fine with me.  Unfortunately the above does not work.

Thanks!

**Comment by nicm** [comment]
I don't think there is a way to do this for choose-client, you would have to add a padding modifier so tmux can do it for you.

I think you could do it if either substitution or trimming expanded their arguments as formats but they don't.

**Comment by jfelchner** [comment]
@nicm is this something that might be a feature or you're not looking to do that?

**Comment by nicm** [comment]
I am happy to have it, but I don't have time to write it myself right now. If you want to do it you need to change format_build_modifiers and format_replace. We have utf8_padcstr to do right padding but if you want left you will need to implement a similar function to do that.

**Comment by nicm** [comment]
Try this please: [tmux-pad.diff.txt](https://github.com/tmux/tmux/files/3886179/tmux-pad.diff.txt)

**Comment by nicm** [comment]
If you want to ensure the width is  always exactly X you need to give both =X and pX.

**Comment by nicm** [comment]
I have applied this change now, it will be in GitHub later on. Thanks!

**Comment by jfelchner** [comment]
@nicm I hadn't looked at my notifications and just saw this now.  Thank you SO MUCH! ❤  I will test this out in the next couple days.
