### ISSUE TITLE
Tmux 2.1 prefix + repeat

### ISSUE THREAD

**Issue by vaxXxa** [tmux/tmux#198]
OS X 10.10.4
iTerm 2 (Build 2.9.20151114-nightly)
Tmux 2.1

My config:
```
# Setting the prefix from C-b to C-f
unbind C-b
set -g prefix C-f
bind C-f send-prefix

# Increase repeat time for repeatable commands
set -g repeat-time 500

# Quick pane selection
unbind l
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
```

Before version 2.1 I can use repeat feature easily: just press **prefix + j/h/k/l** (any time with delta time < 500 ms).. When I'm not sure, is repeat duration ended or not – I always can press again *prefix* and after that use my move commands (j/h/k/l).

Now in version 2.1, if I press **prefix + j/h/k/l** and after that immediately press **prefix + j/h/k/l** – tmux think, that I want to send command `^F` and it's annoying. (I know, that's beacause I use "bind C-f send-prefix" but before tmux 2.1 everything works fine).

So, if I finish my command (for exmaple **prefix + j**) and repeat duration is not finished, tmux must manage **prefix + SOMECOMMAND** correctly.

**Comment by nicm** [comment]
Does it work in tmux from git?

**Comment by vaxXxa** [comment]
Thanks. That works for me (custom build from the latest git repo works fine). Will waiting for new official release with this fix on the brew repos.
