### ISSUE TITLE
Crash with SIGSEGV on `send-keys` to messages pane

### ISSUE THREAD

**Issue by amiryal** [tmux/tmux#1980]
### Issue description

If there is a bad configuration option, tmux server crashes when a client issues `send-keys`, as described in this Ubuntu bug report: https://bugs.launchpad.net/ubuntu/+source/tmux/+bug/1847484

The same issue was reproduced in a fresh 3.0-rc5 build.

### Required information

```
$ uname -sp && ./tmux -V && echo $TERM
Linux x86_64
tmux 3.0-rc5
xterm-256color
```

The following logs are the result of:

1. `echo badconf > ~/.tmux.conf`
2. `./tmux -vv new`
3. Detach from session without closing the error message about bad configuration (output: `[detached (from session 0)]`)
4. `./tmux -vv send-keys -t 0 q` (output: `server exited unexpectedly`)

[tmux-server-16882.log](https://github.com/tmux/tmux/files/3868412/tmux-server-16882.log)
[tmux-out-16882.log](https://github.com/tmux/tmux/files/3868411/tmux-out-16882.log)
[tmux-client-16880.log](https://github.com/tmux/tmux/files/3868409/tmux-client-16880.log)
[tmux-client-16924.log](https://github.com/tmux/tmux/files/3868410/tmux-client-16924.log)

(The first client log is from initial session creation; the second client log is from the `send-keys` operation.)

Further logs and stack traces are available on the Launchpad bug report page linked above.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3868764/x.diff.txt)

**Comment by nicm** [comment]
Whoops this is the right one: [y.diff.txt](https://github.com/tmux/tmux/files/3868799/y.diff.txt)

**Comment by amiryal** [comment]
OK, I can confirm it doesn’t crash with the patch applied, but accepts the `q` key and closes the messages. Now, I am not sure if this is the desired behaviour, as the keystrokes were meant for a particular pane but get hijacked by the messages buffer. I think it would be better to simply deny the client request instead.

**Comment by nicm** [comment]
This is how it is meant to work, if you are in a mode then send-keys sends the keys to the mode.

**Comment by amiryal** [comment]
Thanks. Fair enough.

So, unless there is a better suggested way, any automation script that launches tmux needs to check for `#{pane_in_mode}` before sending keystrokes, which creates a race condition and would not bee obvious to new users. May I suggest a new flag to the `send-keys` command, that will force the operation to be performed outside of any mode? I can do that on a separate Github issue.

**Comment by nicm** [comment]
I'm not convinced there is any need for this.

If you're writing a script for personal use, then you shouldn't have errors in your config file, right?

If you're using tmux to automate something, you should be using a dedicated tmux server with -L or -S and using -f/dev/null so you don't get whatever random stuff the user has in their .tmux.conf. Or at least starting the server up front and creating a new session.

**Comment by nicm** [comment]
I have applied this now, thanks!
