### ISSUE TITLE
[FeatureRequest] Set hook after prefix+command

### ISSUE THREAD

**Issue by kevinhwang91** [tmux/tmux#1981]
>I use pane-border-status instead of the status bar that I had set status off.  pane-border-format can indicate the prefix key was pressed. Not only active pane but all pane will show the prefix icon, I hope only active pane shows the prefix icon.

This flawed method annoys me and I have plan b. Use the `pane-active-border-style` to change the active pane color to indicate the prefix key was press,  after executing a command the color restore. It's easy to change color by using `tmux bind -n 'C-b' 'set -g pane-active-border-style fg=blue\; switchc -Tprefix'` to bind the prefix key.
But no way to restore the color, so I hope to add the hook after prefix+command to restore the color back.

btw, support pane border status align center.

**Comment by nicm** [comment]
Doesn't something like this work:

#{&&:#{pane_active},#{client_prefix}}

**Comment by kevinhwang91** [comment]
Now plan a is perfect.  Please give the option to align the pane border, please!!
