### ISSUE TITLE
Crash when using layouts

### ISSUE THREAD

**Issue by emilecantin** [tmux/tmux#1983]
### Issue description

I believe this is a previously-reported and fixed issue, but I'd like to put a bit more urgency behind a potential release. It's becoming a very annoying bug for me, and I managed to isolate it to very few steps on a "base" tmux (so it's probably not caused by any weird config).

Steps to reproduce:
1. Launch tmux with an empty config file (`tmux -f empty`)
2. Open a split (`<Ctrl-b>` `"`)
3. Open the tmux command (`<Ctrl-b>` `:`)
4. Select a layout: (`select-layout main-horizontal`)
5. In the bottom window, do something that'll output many lines, like `ls -la` in your home directory

Expected behavior: The window scrolls
Actual behavior: The tmux server crashes.

It should be noted that I have some color stuff in my prompt (zsh), not sure if it's related.

There no crash when skipping step 4.

System information:
tmux version: 2.9a
platform: macOS Mojave 10.14.6
$TERM: xterm-256color

Last few lines of logs:
```
1574479241.360072 screen_write_collect_flush: flushed 0 items (0 bytes)
1574479241.360081 /dev/ttys003: \033[26;63r
1574479241.360105 fatal: tty_clamp_area: y too big, 4294967295 > 0
```

**Comment by nicm** [comment]
This is already fixed in master.

**Comment by nicm** [comment]
Or should be anyway, can you still reproduce with master?

**Comment by emilecantin** [comment]
I cannot reproduce it with master, so it does seem fixed, indeed. I'm asking for the maintainers to consider doing a release soon, because it's a very annoying bug that makes you lose all your work state.

**Comment by nicm** [comment]
3.0 is released now.

**Comment by emilecantin** [comment]
Thank you.
