### ISSUE TITLE
`select-window` can select on title prefixes, unless there are multiple matches

### ISSUE THREAD

**Issue by alienth** [tmux/tmux#1984]
### Issue description

`select-window`'s `-t` flag can be used to navigate to a window based on a prefix of its title. For example, if you have a window created named `test`, then one can use `select-window -t te` to navigate to it.

However, if the prefix you pass to `select-window` matches multiple windows, the command bails with `Can't find window`. Steps to repro:

1. Create a window named `test` and a window named `test2`.
2. `select-window -t te`
3. `Can't find window` error will occur.

Under gnu screen, this same scenario with the `select` command would cause screen to navigate to the most-recently-used window which matches the prefix.

`select-window`s inconsistent behaviour here can lead to confusion. I think there's also an opportunity to match feature parity with how gnu screen handles this.

A common scenario where this is encountered in the real world would be multiple windows named for various different servers which have been logged into. Server names tend to share common prefixes. In this scenario, it can be incredibly helpful to be able to quickly navigate back to, for example, the last accessed window beginning with `db-`. While `find-window` can accomplish this, it requires the extra step of using buffer mode.

### Required information

```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.9
xterm-256color
```

**Comment by alienth** [comment]
Based on this comment, seems like erroring if multiple matches is intentional: https://github.com/tmux/tmux/blob/master/cmd-find.c#L465

Think there is opportunity to adjust this behaviour, or would it break other things?

**Comment by nicm** [comment]
I prefer this the way it is TBH. You can easily script it to pick the most recently active if you want.

**Comment by alienth** [comment]
@nicm If it is desired that the behaviour not be changed, I wonder if perhaps the error message should be changed? As a new user of tmux, it was rather confusing that this command would error that it couldn't find a window when a window clearly existed which matched on prefix (which the docs say can be used).

**Comment by nicm** [comment]
Possibly but it may be fiddly to have a specific error just for this case, and the rules are documented in the manual. I don't have strong feelings about this really, if you want to change the behaviour go for it, send a patch. It would be silly for anyone to write a script that depends on this behaviour. You will need to make sure session name matching works the same way.

**Comment by nicm** [comment]
Personally I think the nicest thing would be too show a list of potential matches like it does if you do an ambiguous command like "tmux c".

**Comment by alienth** [comment]
> the rules are documented in the manual

Unless I'm missing something, I believe the docs only cover a multi-match failure for the `target-session` case: https://github.com/tmux/tmux/blob/0d3f306c8e00465e5ffa7b31b99645c9c3c90c3f/tmux.1#L670

**Comment by nicm** [comment]
What reason would you have to think it was different?

**Comment by alienth** [comment]
`target-session` has its own rules on ordering, and the caveat regarding multiple matches is listed there mentioning only sessions. The `target-window` docs have different rules for ordering, and there is no mention of caveats for multiple matches.

**Comment by nicm** [comment]
I don't mind if you want to changing the behaviour or the text of the
manual or both.
