### ISSUE TITLE
tmux over ssh with zsh adds an empty line btw input and prompt

### ISSUE THREAD

**Issue by Incubatio** [tmux/tmux#1987]
```uname -sp && tmux -V && echo $TERM```
Linux x86_64
tmux 3.0  ```// problem also happens on tmux 2.4 and 2.6```
screen-256color ```// also happens with screen, tmux-256color and tmux```
zsh version 5.7.1 ```// also happens with zsh 5.4.2```

Problem:
---------

  When starting tmux over ssh with a zsh shell, the input for command somehow get displayed on top of the prompt label.
![zsh_tmux_over_ssh](https://user-images.githubusercontent.com/179066/69736936-78f23480-1101-11ea-927f-06bd34c6ced6.PNG)

steps to reproduce:
--------------------

  - Install a fresh ubuntu18 with ssh-server (on vm or dedicated server)
  - connect to your ubuntu18 over ssh
  - install tmux, zsh
  - change default shell to zsh (chsh)
  - start tmux
  (config of zsh and tmux are empty)

Note: zsh over ssh doesn't have the problem.

**Comment by Incubatio** [comment]
nvm it's probably an issue with my terminal client.
(it doesn't reproduce on another OS).

**Comment by nicm** [comment]
Could be https://github.com/tmux/tmux/issues/1952?

**Comment by Incubatio** [comment]
nope, my problem only happened while using "cmder" terminal emulator on windows.
With other terminal (or a recent version of ConEmu), no problem.
