### ISSUE TITLE
Behavior of "default" attributes changed (and not documented?)

### ISSUE THREAD

**Issue by ericpruitt** [tmux/tmux#1989]
### Issue description

In older versions of tmux, using "default" in the output of the "status-left" command would cause the attributes to switch to the values defined in my configuration file as

```
set-option -g status-left-bg colour4
set-option -g status-left-fg colour15
```

but in tmux 3.0, when I have `set-option -g status-left-style bg=colour4\ fg=colour15` using "default" in the "status-left" command does NOT use colour4/colour15. I use the status bar to show the number of unread messages, and when I'm SSH'd into my workstation a notification when my desktop is unlocked. When the my desktop is unlocked and there are 2 messages in my Inbox, my "status-left" command will emit `#[bg=red][UNLOCKED]#[default] Inbox [2]`. In older versions of tmux, "Inbox [2]" would have a blue background (colour4) and white foreground (colour15), but in tmux 3.0, "Inbox [2]" ends up gray/white -- the default status line colors.

Before upgrade:

Before upgrade: ![before-upgrade](https://user-images.githubusercontent.com/481184/69768554-db652800-1135-11ea-8f69-8ba34cb16601.png)

After upgrade: ![after-upgrade](https://user-images.githubusercontent.com/481184/69768566-e6b85380-1135-11ea-989c-c257ec55ecce.png)

Is this expected? Is there some way for me to make "default" use colour4/colour15 so I don't have to add "#[bg=... fg...]" to the "status-left" output? I reviewed the output of `man tmux | fgrep -w default -C3` and found "A style may be the single term ‘default’ to specify the default style (which may inherit from another option)..." but I don't see an explanation of how inheritance is supposed to work.

### Required information

```
~$ tmux -V
tmux 3.0
~$ uname -sp
Linux unknown
```
TERM in tmux is tmux-256color.
TERM outside of tmux is st-256color

Logs: [tmux-log-snippet.log](https://github.com/tmux/tmux/files/3899297/tmux-log-snippet.log)

**Comment by nicm** [comment]
Does this still happen with master?

Are you sure this wasn't the same in 2.9?

**Comment by ericpruitt** [comment]
Yes, it happens in master. I upgraded from 2.7 to 3.0, so I have no clue what the behavior was in 2.9.

**Comment by ericpruitt** [comment]
Here are the relevant bits from my tmux configuration file:
```
set-option -g status-interval 1
set-option -g status-left "#(tmux-status-left)"
set-option -g status-left-length 40
set-option -g status-right ""

set-option -g window-status-current-style "bold bg=brightwhite"
set-option -g window-status-current-format "[#I#F#{?window_zoomed_flag, ,}#{=40:pane_title}]"
set-option -g window-status-format "#I#{?window_zoomed_flag, ,}#F#{?window_flags,, }#{?window_zoomed_flag, ,}#{=20:pane_title}"

set-option -g pane-active-border-style "fg=colour247"
set-option -g pane-border-style "fg=colour235"
set-option -g status-style "bg=colour7 fg=colour16"
set-option -g status-left-style "bg=colour4 fg=colour15"
set-option -g window-status-current-style "bg=colour15 fg=colour16 bold"
```

**Comment by nicm** [comment]
I think we need push-default and pop-default before status-left and
status-right in status-format as well.

**Comment by nicm** [comment]
Does this help? [x.diff.txt](https://github.com/tmux/tmux/files/3900259/x.diff.txt)

**Comment by ericpruitt** [comment]
No, that didn't fix it. The result is the same as the "After:" picture I posted above.

**Comment by nicm** [comment]
Show me the server log from master please.

**Comment by ericpruitt** [comment]
Log: [tmux-server-20173.log](https://github.com/tmux/tmux/files/3900361/tmux-server-20173.log)

**Comment by nicm** [comment]
Show me the full log please.

**Comment by ericpruitt** [comment]
[tmux-server-27540.log](https://github.com/tmux/tmux/files/3900433/tmux-server-27540.log)

**Comment by nicm** [comment]
This log is from 3.0, can you try with master please and show me the log?
Thanks

**Comment by nicm** [comment]
It matters because push-default is not in 3.0 :-).

**Comment by ericpruitt** [comment]
I think it works on master, but I ran into an infinite loop that kept tmux from starting with a few of my builds before I got a functional one (sorry, no logs). I'll do a completely fresh clone & build in the morning my time (~8h) and get back with a confirmation, but I think it's probably safe to commit the change since it seems like the broken builds were a fluke.

**Comment by nicm** [comment]
I have applied this and it will be in GitHub when it syncs up and will be in 3.1.

If you want to use your config unchanged in the meantime you will need to run master, continue with 2.8, or backport the change in 63e07b245f898af17657c4655f1251aa43e19d0c as well as this fix when it appears. push-default and pop-default were added in https://github.com/tmux/tmux/pull/1912.

**Comment by ericpruitt** [comment]
Thanks, building from master restores the old default behavior.
