### ISSUE TITLE
automatic-rename doesn't work on some conditions

### ISSUE THREAD

**Issue by adam8157** [tmux/tmux#199]
enviorment:
"automatic-rename" is on, "automatic-rename-format" remains default
the shell is bash, PATHTITLE='\[\ek\W\e\\\]', PS1="${PATHTITLE}${PS1}"

reproducing step:
simply run a command, like "htop".

actual result:
window title remains "\W", which is the current directory.

why it's not right:
window title changed to "htop" successfully when there is no "PATHTITLE", but what's the difference? PS1 hasn't been run again before running "htop", why isn't the window title renamed to "pane_current_command"?

**Comment by nicm** [comment]
Once you rename the window explicitly, automatic-rename is turned off for that window.

**Comment by adam8157** [comment]
ah, can I keep it on?

I was intending to automatically naming window as  "current directory or current command if it's not bash" by combining "automatic-rename" and PATHTITLE. Is there another way which works?

**Comment by nicm** [comment]
Do it all together in PS1 by using "tmux display -p '#{pane_current_command}'" to get the current command.

**Comment by adam8157** [comment]
that seems not right, PS1 won't be invoked when running a command I suppose.

screen's "shelltitle" feature keeps renaming window title, also I saw lots of people asking for an alternative of "shelltitle" in tmux, so, could tmux add it in todo or wishlit? thanks!

**Comment by nicm** [comment]
It would be better to add substitutions to formats, so you could do #{s/ksh/whatever/:pane_current_command} in automatic-rename-format.

**Comment by nicm** [comment]
Try http://pastebin.ca/raw/3257979

**Comment by adam8157** [comment]
patch does not apply to master, will make a time to port and test it.

I guess automatic-rename also use escape sequences, so can I replace it to "\W"? or only normal string like #(pwd)

**Comment by ThomasAdam** [comment]
@adam8157 -- it does.  You just didn't apply it properly, I suspect.  See:

https://github.com/ThomasAdam/tmux/commit/276ee5073a69b0b8160234d84cd1cb19d825669d

**Comment by adam8157** [comment]
@ThomasAdam @nicm tested that patch under Mac OS X, #{s/bash/string/:pane_current_command} works, but "\W" or "#(pwd)" doesn't.

**Comment by nicm** [comment]
\W won't work of course, it is a shell feature. pwd will give you the tmux server cwd, you can try #{pane_current_path}.

**Comment by adam8157** [comment]
On Wed, Nov 18, 2015 at 11:56:09PM -0800, Nicholas Marriott wrote:
> \W won't work of course, it is a shell feature. pwd will give you the tmux
> server cwd, you can try #{pane_current_path}.

#(pwd) returns "#(pwd)", #{pane_current_path} returns "#{pane_current_path}",
might need an "eval" in the code.

BTW, pane_current_path is too long, most of people rather need
pane_current_directory I suspect.

**Comment by nicm** [comment]
Works for me.
