### ISSUE TITLE
invalid option: after-kill-pane

### ISSUE THREAD

**Issue by Mr-Jack82** [tmux/tmux#1991]
### Issue description
Tmux throws a message:  invalid option: after-kill-pane

Fragment of .tmux.conf file with this error:
`set-hook -g 'after-kill-pane'    'run-shell -b "if [ \#{window_zoomed_flag} -eq 1 ]; then tmux set status off; else tmux set status on; fi"'`

System information:
tmux version: 3.0
platform: Arch Linux
$TERM: xterm-256color

**Comment by nicm** [comment]
Did this used to work?

**Comment by nicm** [comment]
You can do this, but this option wouldn't have worked on older tmux:
~~~~
--- options-table.c     28 Nov 2019 08:38:04 -0000      1.114
+++ options-table.c     28 Nov 2019 10:54:32 -0000
@@ -811,6 +811,7 @@ const struct options_table_entry options
        OPTIONS_TABLE_HOOK("after-copy-mode", ""),
        OPTIONS_TABLE_HOOK("after-display-message", ""),
        OPTIONS_TABLE_HOOK("after-display-panes", ""),
+       OPTIONS_TABLE_HOOK("after-kill-pane", ""),
        OPTIONS_TABLE_HOOK("after-list-buffers", ""),
        OPTIONS_TABLE_HOOK("after-list-clients", ""),
        OPTIONS_TABLE_HOOK("after-list-keys", ""),

**Comment by Mr-Jack82** [comment]
Thanks for quick response! I recompile tmux from source with this option included and so far all works just fine. 
p.s. on tmux 2.9 "after-kill-pane" hook works from the "box", at least with this option set tmux don't throw an error.

**Comment by nicm** [comment]
OK thanks, I intend to do a 3.0a release at some point and this will be included.
