### ISSUE TITLE
bindkey \ not working after latest Arch Linux update

### ISSUE THREAD

**Issue by phenomenal-ab** [tmux/tmux#1992]
### bindkey \ not working after latest Arch Linux update

![2019-11-28-153805_1366x768_scrot](https://user-images.githubusercontent.com/22402557/69799209-d5844b00-11f8-11ea-896a-e898d321c8a2.png)
![2019-11-28-153817_1366x768_scrot](https://user-images.githubusercontent.com/22402557/69799211-d7e6a500-11f8-11ea-9553-2047059d82a7.png)

I have binded \ key to create a split at the right hand side.
It worked till yesterday, but broke after latest update on my Arch Linux box.

**Info**<br/>
tmux version : 3.0
Platform: Arch Linux
$TERM (outside) : xterm-256color
$TERM (inside)  : xterm-256color

**Comment by nicm** [comment]
Did you check your binding for \ doesn't need to be fixed as mentioned in the CHANGES file and the release announcement email?

**Comment by phenomenal-ab** [comment]
Sorry, i checked CHANGES for 3.0 to X.X i could find \ to be escaped in 2.9 to 3.0 ...
Thanks for helping

**Comment by phenomenal-ab** [comment]
I replaced it bindkey \ , to bindkey \\ and it seems to work now, i had to escape it.

**Comment by nicm** [comment]
If you do bind '\' it will work on older tmux also.
