### ISSUE TITLE
alt-3 layout incorrect

### ISSUE THREAD

**Issue by dylan-chong** [tmux/tmux#1998]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.0a

* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`). inside: screen-256color, outside: xterm-kitty
* Logs from tmux (`tmux kill-server; tmux -vv new`).

With 3 panes, pressing `prefix, alt-3` , the bottom 2 panes allow you to type onto the statusline. area.

<img width="1280" alt="Screenshot 2019-12-02 at 11 33 33 AM" src="https://user-images.githubusercontent.com/17482349/69921541-9e16e680-14f7-11ea-96a7-9dc93ffa0239.png">

this problem doesnt happen with the other layouts

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by dylan-chong** [comment]
Sorry forgot about this. Just tried on master and bug wasn't replicated. Then just tried again on latest version without my tmux-resurrect setup and its not replicating either

I just tried again using master with my resurrected layouts and its not happening.

I'll keep on the lookout for what replicates the bug when it happens again.
