### ISSUE TITLE
Solaris does not define _PATH_DEFPATH in paths.h

### ISSUE THREAD

**Issue by ericvw** [tmux/tmux#1999]
When attempting to upgrade  `tmux >= 3.0` on Solaris 10, [`spawn.c`](https://github.com/tmux/tmux/blob/master/spawn.c) fails to compile due to `_PATH_DEFPATH` being undefined.

Specifically, the code in question is: https://github.com/tmux/tmux/blob/edf96b06a5aede19e796ace18b4915d973e96e55/spawn.c#L311-L312

From Solaris's [`man paths.h(3HEAD)`](https://docs.oracle.com/cd/E86824_01/html/E54772/paths.h-3head.html), `_PATH_DEFPATH` is not defined.  When `grep`ping through `/usr/include`, I have been unable to find an alternative define that provides something similar to `/usr/bin:/bin`.

Environment:
```
$ uname -sp
SunOS sparc
```

Relevant compilation output:
```
[...]
source='spawn.c' object='spawn.o' libtool=no \
        DEPDIR=.deps depmode=none /bin/sh ./etc/depcomp \
        /scrubbedprefix/bin/cc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"3.0a\" -DPACKAGE_STRING=\"tmux\ 3.0a\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"3.0a\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DH
AVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_PATHS_H=1 -DHAVE_STDINT_H
=1 -DHAVE_SYS_TREE_H=1 -DHAVE_DIRFD=1 -DHAVE_SYSCONF=1 -DHAVE_ASPRINTF=1 -DHAVE_CLOSEFROM=1 -DHAVE_GETPROGNAME=1 -DHAVE_MEMMEM=1 -DHAVE_SETENV=1 -DHAVE_STRCASESTR=1 -DHAVE_STRLCAT=1 -DHAVE_STRLCPY=1 -DHAVE_STRNDUP=1 -DHAVE_STRSEP=1 -DHAVE_NCURSES_H=1 -DHAVE_B64_NTOP=1 -DHAVE_LIBXNET=1 -DHAVE_D
AEMON=1 -DHAVE_DECL_OPTARG=1 -DHAVE_DECL_OPTIND=1 -DHAVE_DECL_OPTRESET=0 -DHAVE___PROGNAME=1 -I.  -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED -DTMUX_CONF="\"/etc/tmux.conf\""    -D_XPG4_2   -I/scrubbedprefix/include -I/scrubbedrprefix/include/ncurses   -erroff=E_EMPTY_DECLARATION -m64 -xtarget=generic -features=e
xtensions -c -o spawn.o spawn.c
"tmux.h", line 612: warning: anonymous union declaration
"spawn.c", line 309: undefined symbol: _PATH_DEFPATH
"spawn.c", line 309: warning: improper pointer/integer combination: arg #3
cc: acomp failed for spawn.c
[...]
```

I have worked around this with `-D_PATH_DEFPATH=\"/usr/bin:/bin\"` when compiling `tmux`.

It's not my first choice, but would hardcoding the string literal "/usr/bin:/bin" be a suitable option?  I'm happy to create a pull request for the change.

**Comment by nicm** [comment]
Yes it needs to go in compat.h.

**Comment by ericvw** [comment]
I am happy to work on the change and provide a pull request.

**Comment by nicm** [comment]
Well I can't test it so it'd be handy if you did. Don't we have some other
_PATH stuff in compat.h already?

Thanks

**Comment by ericvw** [comment]
> Don't we have some other _PATH stuff in compat.h already?

Yeah, I see some `_PATH` stuff.  I'll dig into what is going on and provide an appropriate patch.

**Comment by nicm** [comment]
I think it would be grand just to change the #ifndef HAVE_PATHS_H around the _PATH_* defs in compat.h into individual #ifndef _PATH_X around each one.

**Comment by nicm** [comment]
The #include <paths.h> would need to be moved earlier though

**Comment by ericvw** [comment]
I'm still investigating the current behavior because I *believe* it should have worked.

I'll make the change to break-out the `#ifndef` for each `_PATH_*` once I better understand what is going on.

**Comment by nicm** [comment]
It'll only work if paths.h is missing entirely, if it is present but doesn't include these defines it won't work.

**Comment by ericvw** [comment]
Ahh — I didn't realize `AC_CHECK_HEADERS` was what was defining `HAVE_PATHS_H`.  Everything makes sense now.

Working on the change, testing, and a resulting pull request.
