### ISSUE TITLE
meta backspace no longer works in tmux

### ISSUE THREAD

**Issue by aaronjensen** [tmux/tmux#200]
Running latest master as of this morning and opt-backspace no longer deletes words. It works outside of tmux. I'm currently using +esc in iterm2. Here is my .tmux.conf https://github.com/aaronjensen/dotfiles/blob/master/tmux.conf

**Comment by aaronjensen** [comment]
I tried to bisect, and a number of the commits are missing autogen.sh for some reason so I couldn't narrow it down. It seems it is one of these:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
4f88344df30bca9fbcf670f1bf749ddba3f42397
e71a9154126c7ee853b9a657678de40d475279eb
f2d03f4fddddbdbc96566c55f92718c1f4319b33
a209ea3953ba16742f6f6bb19b76ffdb1200960e
c5689a5a4031a43769b8b721cafa6d1eab6abc44
1da7475d0e2cbfb8b301fcad5cbcfb3ee4c087bb
531869bd92f0daff3cc3c3cc0ab273846f411dc8
b2f19c9d06ed845f35d52ad78e2fe3a49238e1f7
5f483499f3a7b98da9ac67cd62ed91034a5949ed
d6daf37df4ccd7589d2d8f6911bf7270f12d1672
0cc812ae342d1a71c0337db8ffb4d7701668cb38
a7027ed8e5d8fd314c1fafaf0c809b575a753a09
c41673f3fae397e872214880bd005cce631cf11b
1b86f520ea1620628e569ea833c7b13306c18a4e
3df4959f51a444a83e92894c390182dd48e02025
a0f3999ce7b6df32324b493fa3c8007de93d2c48
69e0b8326ad0a983759518b90ed8632146341acf
e2917b2627f1aa07a8e1e1b7510452e87c9ecbe3
b7397bf413643768a44a79d9a32fb887b9a80cde
```

**Comment by ThomasAdam** [comment]
Don't do that. It's due to how I sync from OpenBSD.

**Comment by nicm** [comment]
Show me what you see when you run cat then press M-Backspace inside and outside tmux.

**Comment by aaronjensen** [comment]
@nicm I don't see anything in either.

**Comment by aaronjensen** [comment]
<kbd>esc</kbd><kbd>backspace</kbd> does appear to work in both tmux and outside of it.

**Comment by nicm** [comment]
So your terminal is not sending anything for M-Backspace.

**Comment by nicm** [comment]
Run:

 tmux -vvvvLtest -f/dev/null new

Then press M-Backspace, then type exit to exit tmux and send me the tmux-server*.log file.

**Comment by aaronjensen** [comment]
Emailed you the log, @nicm

**Comment by nicm** [comment]
Ah right this is a mistake, you can do this:

Index: input-keys.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/input-keys.c,v
retrieving revision 1.48
retrieving revision 1.49
diff -u -p -r1.48 -r1.49
--- input-keys.c	14 Nov 2015 11:45:43 -0000	1.48
+++ input-keys.c	16 Nov 2015 22:57:51 -0000	1.49
@@ -161,7 +161,7 @@ input_key(struct window_pane *wp, key_co
 	 * if necessary. If it is a UTF-8 key, split it and send it.
 	 */
 	justkey = (key & ~KEYC_ESCAPE);
-	if (key != KEYC_NONE && justkey < 0x7f) {
+	if (key != KEYC_NONE && justkey <= 0x7f) {
 		if (key & KEYC_ESCAPE)
 			bufferevent_write(wp->event, "\033", 1);
 		ud.data[0] = justkey;

**Comment by aaronjensen** [comment]
Thanks, this fixed it! The two hardest problems in computer science....
