### ISSUE TITLE
[Feature Request] Analog Clock with proper numbering and a second hand

### ISSUE THREAD

**Issue by Donboscow** [tmux/tmux#2002]
- [x] Already tmux has **Big Digital Clock** (12 & 24 hour) when we press **Prefix Key + t** 
- [ ]  But It's lacking an analog clock with proper numbering ( 1 to 12) and a second hand. Please add this feature.

**Comment by krader1961** [comment]
> Please add this feature.

Why? How should that behavior be enabled? Are you going to write the code to implement the feature?

**Comment by Donboscow** [comment]
* We already can set up the **Big Clock** mode 
 with this two options in our .tmux.conf file
```
set -g clock-mode-style 12
set -g clock-mode-colour red
```
* Now we need to add Analog Clock (12 & 24 hour) with proper numbering (1 to 12) and a second hand. To enable this we need to implement these configs recognized by tmux
```
set -g clock-mode-style-digital
set -g clock-mode-style-analog
```
I'm very badly missing these features. Please add this feature. @krader1961

**Comment by nicm** [comment]
Haha no we are not adding any more clocks.

**Comment by Donboscow** [comment]
Actually I'm obsessed with simple analog clock and I'm missing this feature in tmux. What i need to know to (coding & documentations) implement a simple analog clock with proper numbering in tmux? @nicm

**Comment by nicm** [comment]
You'd be better to write an analogue clock program using ncurses and run it in a pane. There might even be one already.

**Comment by Donboscow** [comment]
If I create an analog clock following proper coding standard and documentation, will you merge this feature in mainline tmux versions? @nicm

**Comment by nicm** [comment]
No, the only reason the existing clock still exists is because we use the numbers for other things.
