### ISSUE TITLE
tmux fails to build

### ISSUE THREAD

**Issue by mananapr** [tmux/tmux#2003]
### Issue description
I am using `KISS Linux`, `Kernel v5.4.1` and `musl` libc. When trying to build `v3.0a` or `v3.0`, the build fails with the following error:
```
cmd-pipe-pane.c:161:44: error: dereferencing pointer to incomplete type 'struct bufferevent'
  161 |    wp->pipe_off = EVBUFFER_LENGTH(wp->event->input);
      |                                            ^~
```
The strange thing is that it did use to build earlier just fine. In fact, I am running `v3.0` now which I compiled when it got released. I encountered this issue when trying to update to `v3.0a`. Now, even build for `v3.0` fails for some reason. Any idea what could be going on here?

### Required information
* Full Logs for the build can be found [here](https://pst.moe/paste/pcpzrv)
* Platform (`uname -sp`).
```
KISS Linux. Kernel 5.4.1
```
* tmux version (`tmux -V`). [Not relevant to this case]
```
-> tmux -V
tmux 3.0
```
* $TERM inside(`xterm-256color`) and outside of tmux (`st-256color`). [Not relevant to this case]

**Comment by nicm** [comment]
This seems like something wrong with your libevent install. Are you starting the tmux build from a clean tree?

**Comment by mananapr** [comment]
> This seems like something wrong with your libevent install

I reinstalled `libevent` and it seems to be compiling now. Thanks
On a different note, would `libev` clash with `libevent`? Because I installed `libev` a few days back...

**Comment by nicm** [comment]
Maybe it could if libev has libevent compat headers and is installed
incorrectly.
