### ISSUE TITLE
Resizing tmux pane doesn't update terminfo

### ISSUE THREAD

**Issue by jason0x43** [tmux/tmux#2005]
### Issue description

Resizing a tmux pane doesn't update the terminfo within the pane -- `tput` will continue to report the original number of lines and columns after a pane is resized. Sometimes it will update after one resize, but not more than that. Detaching and reattaching to a session will update the terminfo.

To reproduce:

1. Start a tmux session
2. Split the window horizontally
3. Note the number of columns reported by `tput cols`
4. Resize the pane
5. Check `tput cols` again
6. Repeat 4 and 5. Note that the column count doesn't update.
7. Detach and reattach. Note that `tput cols` has been updated.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  * **3.0a**
* Platform (`uname -sp`).
  * **Darwin i386**
* $TERM inside and outside of tmux (`echo $TERM`).
  * Inside: **tmux-256color**
  * Outside: **xterm-kitty**
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
tmux doesn't have to do anything other than what it does (TIOCSWINSZ), anything else would be up to the shell.

Does `stty -a` show the right size? Does `eval \`resize\`` fix tput?

**Comment by mckellyln** [comment]
If I resize a pane I do see my $COLUMNS and tput cols change values accordingly.  But I'm on zsh in terminator.

**Comment by jason0x43** [comment]
`stty -a` shows the same value as `tput cols` (the incorrect value).

I'm on a Mac, so no `resize` (and I'm not sure what the Mac equivalent would be).

> anything else would be up to the shell.

Hmmm...is the shell involved with `tput` or terminfo? In any case, why would detaching and re-attaching from a running session cause the line and column counts to update to the proper values?

**Comment by nicm** [comment]
Does "tmux lsp" show the right size?

Does this still happen with tmux master? There was some problem about not resizing if there was output.

**Comment by jason0x43** [comment]
`tmux lsp` works. Tmux seems to be aware of its own size; `tmux lsp` always shows the correct pane size. The issue is that at least some apps running within the pane don't know 

I haven't tried master yet.

Hmmm...some apps obviously know what the proper pane size is (fullscreen apps like vim). However, other things, like zsh (which updates the `COLUMNS` env var when the window size changes) and node (which can report columns as `process.stdout.columns`), do not. Both of these apps do detect window size changes when running directly in a terminal window (as opposed to in a tmux pane).

**Comment by jason0x43** [comment]
Ok, so I killed my active tmux server and started a new one, and now it appears to be behaving properly, at least for a simple case with one window and a couple of panes.

**Comment by jason0x43** [comment]
I restored a resurrect-saved session, and it's still working. Interestingly, it's not 100% -- every once in a while after I resize a pane, the shell won't notice, but usually it does.

**Comment by nicm** [comment]
Try master please and see if you still have the problem.
