### ISSUE TITLE
split-window -h throwing error and failing to split window

### ISSUE THREAD

**Issue by Pheric** [tmux/tmux#2006]
### Issue description
Since updating to the latest tmux version, I get an error when starting tmux: "unknown key:  split-window". My ~/.tmux.conf is attached.

When I change the bind key on line 5 from `\` to `"`, it opens up a horizontal split in the screen, same as when I use `-` on line 6. When I use `\` or `/`, it seemingly does nothing at all.

### Required information

Please provide the following information:

* tmux version: `3.0a`
* Platform (`uname -s0v`): `Linux #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 GNU/Linux`
* CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
* $TERM inside:outside: `xterm-256color`:`screen`

[tmux.conf.txt](https://github.com/tmux/tmux/files/3933983/tmux.conf.txt)

[tmux-out-192297.log](https://github.com/tmux/tmux/files/3933965/tmux-out-192297.log)
[tmux-client-192295.log](https://github.com/tmux/tmux/files/3933964/tmux-client-192295.log)
[tmux-server-192297.log](https://github.com/tmux/tmux/files/3933966/tmux-server-192297.log)

**Comment by nicm** [comment]
This is covered in the CHANGES file, the release announcement and the pinned issue about 3.0a.

**Comment by Pheric** [comment]
My mistake. Missed it in the CHANGES file and never saw the pinned issue
