### ISSUE TITLE
has-session: undocumented behavior when testing for panes/windows

### ISSUE THREAD

**Issue by lehmanju** [tmux/tmux#2007]
### Issue description

The current man documentation for tmux does not include following, tested behavior when using the `has-session` command.

https://unix.stackexchange.com/questions/524600/how-to-test-if-a-pane-exists-in-tmux

As stated in the answer it is possible to test for specific panes windows by using `$<session>:@<window>.%<pane>` as target for `-t`.

If this is intended behavior, this should be documented or else removed. It could be useful to remove this behavior for this specific command as the name already implies it is only testing for sessions. But one could add another command named differently testing for panes and windows.

### Required information

* tmux version (`tmux -V`): master

**Comment by nicm** [comment]
I think it is fine as it is TBH.
