### ISSUE TITLE
[feature-request] Switching between panes

### ISSUE THREAD

**Issue by syntaxler** [tmux/tmux#2008]
### Proposing a new kind of behavior when switching between panes in the situation shown in the screenshot

Problem: If i go from pane 0 to 2, then from 2 to 3 and then send select-pane -U (through whatever key you have bound it to), then 0 is selected, because it is ambiguous what upper pane to select since there are two panes touching the upper border of 3 and 0 was last used of the two. I find this unnerving, since optically it is obvious that 1 is the pane to the top of 3 and not 0.

I propose: If in doubt which pane to select, select the one that takes up more than half of the border of current pane. Only if this condition is not met, the last used pane should be selected. This way switching between one big pane and several small panes stays in the current (for this case useful) behavior. 

If you think this will break peoples habits (it probably will), I think it'd still be worth creating a config option that switches tmux to the proposed behavior.

Screeny:
![tmux](https://user-images.githubusercontent.com/58639608/70380694-a6c84c00-193f-11ea-8022-2333ba4e0fa6.png)

### Required information
* tmux version: tmux 3.0a
* Platform: Linux x86_64
* $TERM inside tmux: xterm
* $TERM outside of tmux: xterm
(setting $TERM to "xterm" both locally (msys Mingw-w64 64 bit) and on server outside and inside of tmux solved lots of issues for me but is probably completely irrelevant for this request, I hope you forgive me for not setting it to screen)

Logs (probably also irrelevant, but here you go):
[tmux-out-10741.log](https://github.com/tmux/tmux/files/3935578/tmux-out-10741.log)
[tmux-server-10741.log](https://github.com/tmux/tmux/files/3935579/tmux-server-10741.log)
[tmux-client-10739.log](https://github.com/tmux/tmux/files/3935580/tmux-client-10739.log)

**Comment by nicm** [comment]
This behaviour has changed a couple of times and I don't want to change it again, I like it how it is now. It should be relatively easy to write a script to do what you suggest.

**Comment by nicm** [comment]
I thought about this a bit more and I don't mind if it changes, so if you have a patch please open a PR.
