### ISSUE TITLE
3.0a Question regarding swap-window

### ISSUE THREAD

**Issue by nrhodes91** [tmux/tmux#2009]
Going from tmux v2.9_a-4 to any 3.0 build changes how swap-window works. Previously the currently active window would follow the swap, i.e. swap active window 1 with window 2, would result in window 2 being the currently active window with the content of the previous window 1. This meant the following binding allowed to quickly reorder windows:
```
bind -n M-N swap-window -t :+
bind -n M-P swap-window -t :-
```

Now the active window does not change index, so the above binding just swaps the same two windows back and forth. I couldn't see this mentioned in the changelog.

**Comment by nicm** [comment]
This was changed in 39c55d5 to match the original intention and swap-pane.

**Comment by nrhodes91** [comment]
@nicm thanks for the quick response and confirming the intention.
