### ISSUE TITLE
has-session is overeager

### ISSUE THREAD

**Issue by ethagnawl** [tmux/tmux#201]
If I have an active Tmux session called "first-second" and execute: `tmux start-server\; has-session -t first 2>/dev/null`, then $? will be 0 (i.e. the session exists).

I'm seeing this behavior while using version 2.0.

**Comment by nicm** [comment]
That's how -t works, but you can use =.

**Comment by DanielArndt** [comment]
@nicm What version of tmux was the `=` option added in? I tried to track it down in the source but I'm obviously not very proficient at that. It does not appear to be working for me in v1.8.
