### ISSUE TITLE
Status bar is rendered multiple times with Jigsaw Puzzle Piece emoji

### ISSUE THREAD

**Issue by voda** [tmux/tmux#2011]
### Issue description

If I put the [Jigsaw Puzzle Piece 🧩](https://emojipedia.org/jigsaw-puzzle-piece/) emoji in a window name, every change in the status bar "duplicates" the bar (see screen). This is the only emoji where it happens, some other work fine. This happens when moving the cursor while renaming the window or when the status bar contains a clock and the time changes. The issue started appearing after upgrading iTerm.

![image](https://user-images.githubusercontent.com/290157/70443394-5adcea80-1a98-11ea-82be-c196623fcba0.png)

### Required information
System: iTerm2 version 3.3.7 on Mac
```
uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 3.0a
screen-256color
```
Reproduced with latest git version and no tmux config.

**Comment by nicm** [comment]
Logs?

**Comment by voda** [comment]
Here are the logs:
[tmux-client-33474.log](https://github.com/tmux/tmux/files/3940211/tmux-client-33474.log)
[tmux-out-33476.log](https://github.com/tmux/tmux/files/3940212/tmux-out-33476.log)
[tmux-server-33476.log](https://github.com/tmux/tmux/files/3940213/tmux-server-33476.log)

**Comment by nicm** [comment]
Your system C library does not have the width for this character, so tmux assumes it is width 1:
~~~~
1575902782.572874 Unicode 1f9e9, wcwidth() -1
~~~~
You can either see if you can upgrade your system to support Unicode 11, or try building tmux against utf8proc (configure with --enable-utf8proc).

**Comment by voda** [comment]
Tried `--enable-utf8proc`, but that behaves the same. Have found similar issues for iTerm
https://gitlab.com/gnachman/iterm2/issues/7901
> Emoji width is a particularly broken part of Unicode. But the important thing is that the terminal emulator and the application running within it agree about the width

So I assume this is not the case now and iterm & tmux have a different width for this.

I will probably not use this emoji and try to find another.
Thanks for your help.
