### ISSUE TITLE
 choose-buffer should be able to display UTF8 in preview 

### ISSUE THREAD

**Issue by koie-hidetaka** [tmux/tmux#2017]
### Issue description

In the current version,
choose-buffer preview does not support UTF8,
so UTF8 characters are displayed as `\ooo`.

I have written a patch to handle UTF8.

[choose-buffer-utf8.txt](https://github.com/tmux/tmux/files/3959547/choose-buffer-utf8.txt)

**Comment by nicm** [comment]
Great, applied to OpenBSD with some minor changes, will be in GitHub later. Thanks!
