### ISSUE TITLE
[Feature request] Run other shell

### ISSUE THREAD

**Issue by lexasub** [tmux/tmux#2018]
I want run shells in tmux. tmux -c OTHER_SHELL_EX_ZSH_FISH don't run shell with tmux(it's run only shell)

**Comment by nicm** [comment]
I don't think you -c does what you think it does.

**Comment by lexasub** [comment]
and how i can run fish in tmux on default?

**Comment by krader1961** [comment]
> how i can run fish in tmux on default?

Put this in your *~/.tmux.conf*:

```
set-option -g default-command /usr/local/bin/fish
```

**Comment by lexasub** [comment]
thanks
