### ISSUE TITLE
build failure for g52b6ca57

### ISSUE THREAD

**Issue by picgla** [tmux/tmux#2019]
### Issue description

with today's github contents (g52b6ca57), the build fails on ubuntu 19.10 with an error in file.c:
unable to find imsg.h.  on my ubuntu 19.10 system, imsg.h does not appear to be available in
standard repos.

in file.c, i changed the include definition of imsg.h to point to "compat/imsg.h" and
the build succeeded.  exercising the resulting tmux binary, i have found no issues.

i realize this is a brute force solution and does not distinguish between bsd and
linux systems (or windows).  could a more general conditional build directive be used
to handle bsd vs non-bsd systems?

### Required information

uname -sp && tmux -V && echo $TERM && lsb_release -a
Linux x86_64
tmux next-3.1  or  3.0a-175-g52b6ca57
xterm-256color
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan

### a patch

cat file.c.patch.tmux
--- file.c.orig 2019-12-16 11:18:15.502463015 -0800
+++ file.c      2019-12-16 11:01:24.626550692 -0800
@@ -21,13 +21,14 @@
 
 #include <errno.h>
 #include <fcntl.h>
-#include <imsg.h>
+/* #include <imsg.h> /**/
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
 #include <unistd.h>
 
 #include "tmux.h"
+#include "compat/imsg.h"
 
 static int     file_next_stream = 3;

**Comment by nicm** [comment]
Fixed now, thanks!
