### ISSUE TITLE
installation fails on centos 5.8

### ISSUE THREAD

**Issue by marsh160** [tmux/tmux#202]
[root@vnc tmux-master]# ./configure && make
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for egrep... grep -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for glibc... yes
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking bitstring.h usability... no
checking bitstring.h presence... no
checking for bitstring.h... no
checking curses.h usability... yes
checking curses.h presence... yes
checking for curses.h... yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking ndir.h usability... no
checking ndir.h presence... no
checking for ndir.h... no
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking pty.h usability... yes
checking pty.h presence... yes
checking for pty.h... yes
checking for stdint.h... (cached) yes
checking sys/dir.h usability... yes
checking sys/dir.h presence... yes
checking for sys/dir.h... yes
checking sys/ndir.h usability... no
checking sys/ndir.h presence... no
checking for sys/ndir.h... no
checking sys/tree.h usability... no
checking sys/tree.h presence... no
checking for sys/tree.h... no
checking term.h usability... yes
checking term.h presence... yes
checking for term.h... yes
checking util.h usability... no
checking util.h presence... no
checking for util.h... no
checking for library containing flock... none required
checking for dirfd... yes
checking for flock... yes
checking for setproctitle... no
checking for sysconf... yes
checking for cfmakeraw... yes
checking for library containing clock_gettime... -lrt
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBEVENT... no
checking for library containing event_init... -levent
checking for library containing setupterm... -lcurses
checking utempter.h usability... no
checking utempter.h presence... no
checking for utempter.h... no
checking for b64_ntop... no
checking for b64_ntop with -lresolv... yes
checking for library containing inet_ntoa... none required
checking for library containing socket... none required
checking for socket in -lxnet... no
checking for CMSG_DATA... yes
checking for library containing imsg_init... no
checking for library containing forkpty... -lutil
checking for closefrom... no
checking for daemon... yes
checking for setenv... yes
checking for strlcpy... no
checking for strlcat... no
checking for asprintf... yes
checking for fgetln... no
checking for fparseln... no
checking for strcasestr... yes
checking for strsep... yes
checking for strtonum... no
checking for stravis... no
checking for cfmakeraw... (cached) yes
checking for openat... yes
checking for getopt... yes
checking whether optarg is declared... yes
checking whether optind is declared... yes
checking whether optreset is declared... no
checking for BSD-style unsigned types... yes
checking whether TAILQ_PREV is declared... yes
checking whether TAILQ_REPLACE is declared... no
checking for __progname... yes
checking whether F_CLOSEM is declared... no
checking for /proc/$$... yes
checking platform... linux
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
gcc  -D_GNU_SOURCE -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wnested-externs -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign     -o tmux  alerts.o arguments.o attributes.o cfg.o client.o cmd-attach-session.o cmd-bind-key.o cmd-break-pane.o cmd-capture-pane.o cmd-choose-buffer.o cmd-choose-client.o cmd-choose-tree.o cmd-clear-history.o cmd-command-prompt.o cmd-confirm-before.o cmd-copy-mode.o cmd-detach-client.o cmd-display-message.o cmd-display-panes.o cmd-find.o cmd-find-window.o cmd-if-shell.o cmd-join-pane.o cmd-kill-pane.o cmd-kill-server.o cmd-kill-session.o cmd-kill-window.o cmd-list-buffers.o cmd-list-clients.o cmd-list-keys.o cmd-list-panes.o cmd-list-sessions.o cmd-list-windows.o cmd-list.o cmd-load-buffer.o cmd-lock-server.o cmd-move-window.o cmd-new-session.o cmd-new-window.o cmd-paste-buffer.o cmd-pipe-pane.o cmd-queue.o cmd-refresh-client.o cmd-rename-session.o cmd-rename-window.o cmd-resize-pane.o cmd-respawn-pane.o cmd-respawn-window.o cmd-rotate-window.o cmd-run-shell.o cmd-save-buffer.o cmd-select-layout.o cmd-select-pane.o cmd-select-window.o cmd-send-keys.o cmd-set-buffer.o cmd-set-environment.o cmd-set-option.o cmd-show-environment.o cmd-show-messages.o cmd-show-options.o cmd-source-file.o cmd-split-window.o cmd-string.o cmd-swap-pane.o cmd-swap-window.o cmd-switch-client.o cmd-unbind-key.o cmd-wait-for.o cmd.o colour.o control.o control-notify.o environ.o format.o grid-view.o grid.o input-keys.o input.o job.o key-bindings.o key-string.o layout-custom.o layout-set.o layout.o log.o mode-key.o names.o notify.o options-table.o options.o paste.o proc.o resize.o screen-redraw.o screen-write.o screen.o server-client.o server-fn.o server.o session.o signal.o status.o style.o tmux.o tty-acs.o tty-keys.o tty-term.o tty.o utf8.o window-choose.o window-clock.o window-copy.o window.o xmalloc.o xterm-keys.o osdep-linux.o  compat/imsg.o compat/imsg-buffer.o compat/closefrom.o   compat/strlcat.o compat/strlcpy.o  compat/fgetln.o compat/fparseln.o compat/getopt.o   compat/vis.o compat/unvis.o compat/strtonum.o     -lutil -lcurses -levent -lrt  -lresolv
xmalloc.o: In function `xreallocarray':
/root/tmux-master/xmalloc.c:83: undefined reference to `reallocarray'
collect2: ld returned 1 exit status
make: *** [tmux] Error 1
[root@vnc tmux-master]# uname -a
Linux vnc.rothamsted.ac.uk 2.6.18-308.24.1.el5 #1 SMP Tue Dec 4 17:43:34 EST 2012 x86_64 x86_64 x86_64 GNU/Linux
[root@vnc tmux-master]# more /etc/redhat-release
CentOS release 5.8 (Final)

**Comment by nicm** [comment]
Yeah git is broken for the moment it'll be fixed at some point

**Comment by marsh160** [comment]
Ok , thanks nick.

  Regards

    Mark H.

**Comment by nicm** [comment]
reallocarray should be there now, so it should be fixed.

**Comment by marsh160** [comment]
installed ok now - thanks
