### ISSUE TITLE
crash when choosing a menu item

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2021]
### Issue description

To reproduce, run this shell command:

    tmux -Lx -f<(cat <<'EOF'
    bind i display-menu -y 0 'server options' s { show -s }
    EOF
    )

Press `C-b i` to open the menu, then `s` choose the `server options` item.

The server crashes.
I think it's a regression because the code did not cause a crash in the past.

However, I was not able to find the exact commit from which the regression was introduced; according to `$ git bisect`, it should be one of these:

    2b2b19379110fd90f4d84fb973628900f2d3fd4d
    5134666702ce972390f39e34bed9b60fe566263a
    7922f4ee7bd4c18509c6774971fd007a4c5a10e3
    268f2b047a6e9b932a0ff51aa526e1df61d54165
    dcf41ec9275a2a1a87a5943d9ba189d83de67a89
    c284ebe0ade7cc85ad6c3fe5ce7ed5108119222d
    58908b045b48b224063ce04d3db63741d32d0898

### Required information

 - `$ tmux -V`: tmux next-3.1, commit 3879509426d8d269acb7b2aec3eb04f5b5a141d3
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f<(...)`:
[tmux-client-5137.log](https://github.com/tmux/tmux/files/3972868/tmux-client-5137.log)
[tmux-out-5140.log](https://github.com/tmux/tmux/files/3972872/tmux-out-5140.log)
[tmux-server-5140.log](https://github.com/tmux/tmux/files/3972873/tmux-server-5140.log)

 - backtrace from `$ gdb -n -ex 'thread apply all bt full' -batch ./tmux ./core`:
[backtrace.txt](https://github.com/tmux/tmux/files/3972875/backtrace.txt)

**Comment by nicm** [comment]
This is the fix, I have applied it and it will be in GitHub later. Thanks!
~~~~
--- cmd-queue.c 12 Dec 2019 11:39:56 -0000      1.76
+++ cmd-queue.c 17 Dec 2019 11:42:57 -0000
@@ -512,7 +512,7 @@ cmdq_print(struct cmdq_item *item, const
                wme = TAILQ_FIRST(&wp->modes);
                if (wme == NULL || wme->mode != &window_view_mode)
                        window_pane_set_mode(wp, &window_view_mode, NULL, NULL);
-               window_copy_vadd(wp, fmt, ap);
+               window_copy_add(wp, "%s", msg);
        }

        free(msg);
