### ISSUE TITLE
when build with --enable-utempter, does not call utempter_add_record

### ISSUE THREAD

**Issue by pschellenbach** [tmux/tmux#2022]
### when build with --enable-utempter, does not call utempter_add_record

Sorry, I am not a tmux user, but was browsing the code for examples of how to use utempter to update utmp file and discovered possible bug in current tmux version.

In commit [5ece38](https://github.com/tmux/tmux/commit/5ece386cdf84b692c1f28b5bf018ac619d067fde) the call to utempter_add_record was removed however the calls to utempter_remove_record remain.

This code was previously in window_pane_spawn:

```
#ifdef HAVE_UTEMPTER
	xsnprintf(s, sizeof s, "tmux(%lu).%%%u", (long) getpid(), wp->id);
	utempter_add_record(wp->fd, s);
	kill(getpid(), SIGCHLD);
#endif
```
Looks like it should now be inserted after the label 'complete' in spawn.c.

### Required information

Please provide the following information:

* tmux version: commit 4223293

**Comment by nicm** [comment]
Shows how many people care about utempter, eh. Fixed now, thanks!
