### ISSUE TITLE
Override bind in specific case with source-file wildcard and unbind

### ISSUE THREAD

**Issue by jj-kim** [tmux/tmux#2023]
### Issue description

The yacc single parser change (commit 723010ba72e337832402f8e44981c02caa30b476) seems to have broken a specific case involving `source-file`, `unbind`, and `bind`.  If a `source-file` takes a wildcard path where two files set a binding and one file's binding should override the other, the overriding doesn't work anymore.  Here are the configuration files for repro:

```tmux
# ~/sandbox/tmux/1+2.conf
source-file "$HOME"/sandbox/tmux/*.tmux
```

```tmux
# ~/sandbox/tmux/1.tmux
unbind -a
bind % split-window -h
bind l break-pane
```

```tmux
# ~/sandbox/tmux/2.tmux
bind l select-pane -R
```

I worked off of two versions, *bad* and *good*:

  * *bad*: commit bf2cf33fc633dd6f28d0d57e669cbd0b109a5f2d (or `refs/tags/3.0~74`)
  * *good*: commit 7ca2e2fe88cd282d3e8faea3f2000ad15972f71d (or `refs/tags/3.0~76`)

I ran tmux as follows while in the repository checkout having built either *bad* or *good*:

```sh
TZ='Etc/GMT' ./tmux -f ~/sandbox/tmux/1+2.conf -vv
```

1. Do a vertical split with `C-b`-`%`
1. Do `C-b`-`l`:

   * On *bad*, expect `break-pane` to take place
   * On *good*, expect `select-pane -R` to take place

`break-pane` should not be expected because `source-file` should read `1.tmux` first then `2.tmux`, causing `bind l select-pane -R` to execute after `bind l break-pane` and override it.  Strangely, the `unbind -a` also plays a part in causing this: without it, things work fine.  Similarly with the `source-file` wildcard, doing separate `source-file`s for each file resolves things.

### Required information

* tmux version:

  * *bad*: `tmux next-3.0`
  * *good*: `tmux next-3.0`
  * (It should also fail for `3.0a`.)

* Platform (`uname -sp`):

  ```
  Linux unknown
  ```

* $TERM inside and outside of tmux (`echo $TERM`):

  * inside tmux: `screen`
  * outside tmux: `rxvt-unicode-256color`
  * (It should also fail when `TERM` inside tmux is `tmux-256color`.)

* Logs from tmux (note I have removed several lines from server logs (e.g. lines with `input_parse_buffer`)):

  * [*bad* tmux-client.log](https://gist.github.com/jj-kim/3d37360ccca2ab45fd7b8e2b96dfc286/raw)
  * [*bad* tmux-server.log](https://gist.github.com/jj-kim/c1781e1a47d04012398da5900e1e2573/raw)
  * [*good* tmux-client.log](https://gist.github.com/jj-kim/2003220ecde51d9cae4a328c5e0e5f86/raw)
  * [*good* tmux-server.log](https://gist.github.com/jj-kim/d6bf88a3bf4c0ecb04020fbb42e66c75/raw)

**Comment by nicm** [comment]
It is not inserting after the correct last item when there are multiple items in the cmd_list, try this please: [x.diff.txt](https://github.com/tmux/tmux/files/3977344/x.diff.txt)

**Comment by jj-kim** [comment]
I applied that patch on commit 4223293ed862843e15af89b4257c638dce53e1b9, and it seems to do the trick.  It even solves various issues with my personal configuration files.  Thanks for the quick fix.

**Comment by nicm** [comment]
Applied to OpenBSD now with some minor additions (need to do the same for cmdq_append), will be in GitHub later. Thanks!
