### ISSUE TITLE
3.0a freeze/crash run-shell in combination with fzf-tmux

### ISSUE THREAD

**Issue by Ikke** [tmux/tmux#2025]
Since Tmux 3.0(a), whenever I execute the following keybinding, the current session freezes:

```
bind -n C-f run-shell "tmux list-sessions -F \"##S\" | fzf-tmux -d15 | xargs tmux switch-client -t || true" 
```

I see the pane appear with the expected output, but it no longer responds to input, though the output still seems to be updated (time in the status bar)

It still happens when I reduce it to:

```
bind -n C-f run-shell "echo a | fzf-tmux -d15" 
```

In a new terminal, I can still attach to the same session and I can interact with it again.

When I kill the tmux-server, I see the clients exiting, but the server remains and I have to force kill it (SIGKILL),

Additional information:
* Archlinux
* urxvt
* `uname -sp && tmux -V && echo $TERM`
```
Linux unknown
tmux 3.0a
screen
```
* I removed all other config from my .tmux.conf except that one line
* Log output:
    * [tmux-client-5069.log](https://github.com/tmux/tmux/files/3987429/tmux-client-5069.log)
    * [tmux-out-5071.log](https://github.com/tmux/tmux/files/3987430/tmux-out-5071.log)
    * [tmux-server-5071.log.gz](https://github.com/tmux/tmux/files/3987431/tmux-server-5071.log.gz)

**Comment by nicm** [comment]
Are you sure the command you run with run-shell is exiting? Without -b, the client will not run any further tmux commands or process any key bindings until it does.

**Comment by Ikke** [comment]
Yes, after you selected an item and pressed enter, it will return the selected item. But now there is no possibility anymore to even select something.

**Comment by nicm** [comment]
You will not be able to press any keys until it exists unless you use
run-shell -b.

**Comment by Ikke** [comment]
Thanks. Adding `-b` fixes the issue. I was not aware that it was necessary as it worked before (and kind of assumed you could not interact with things running in the background).

**Comment by nicm** [comment]
Previously key presses were not queued with commands, so if you were only
pressing keys you wouldn't have noticed, but this was changed so they are
ordered correctly with any commands they run.
