### ISSUE TITLE
[Feature Request] More format variables for viewing attached clients

### ISSUE THREAD

**Issue by tculp** [tmux/tmux#2026]
### Premise

Lately, I have found myself collaborating with multiple clients and sessions attached to the same session group. Since there are many people viewing the same group of windows, it would be nice to know which how many clients are viewing the current window and session group. This information could be part of the window list in the status bar, but format options do not exist for this.

There are several format options that perform similar features, but do not quite fulfill my desire. For example, there is a session_attached variable, to show the number of clients attached to the session, but no session_group_attached variable. Similarly, there is a window_active variable, but no window_attached variable.

Currently, in order to achieve what I would like, I would most likely have to make a script to call many tmux commands and perform several math operations on them.

### Proposal

I think it would make sense for some of the session variables to also be useable for session groups and windows, such as:

     session_group_attached   -   Number of clients session group is attached to
     session_group_many_attached   -   1 if multiple clients attached
     session_attached_list   -   List of clients attached to session
     session_group_attached_list   -   List of clients attached to session group
     window_active_count   -   Number of clients viewing the window
     window_linked_count   -   Number of sessions (or session groups) window is linked to
     window_linked_list   -   List of sessions (or session groups) the window is linked to
     window_active_list   -   List of clients viewing the window
     
Thoughts?

**Comment by nicm** [comment]
OK sure. Anything with a loop needs to be a callback format though (look at the others in format.c).
