### ISSUE TITLE
can't run tmux as user root

### ISSUE THREAD

**Issue by dodona2** [tmux/tmux#2027]
### Issue description
invoking tmux as user root with TERM={linux|xterm-256color|xterm} or normal user with term={linux} always aborts tmux with the message

**error connecting to /tmp/tmux-0/default (No such file or directory)**

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

starting a {linux|xterm-256color|xterm} session as user root 
invoking tmux 
returns: error connecting to /tmp/tmux-0/default (No such file or directory)

### Required information

* tmux version (`tmux -V`).
tmux 2.9a

* Platform (`uname -sp`).
Linux x86_64
Ferdora 31

* $TERM inside and outside of tmux (`echo $TERM`).
outside: {linux|xterm-256color|xterm}
inside (as normal user(xterm*)): screen

* Logs from tmux (`tmux kill-server; tmux -vv new`).
no logs

**Comment by nicm** [comment]
Do you have /tmp and does it have the right permissions?

**Comment by dodona2** [comment]
there is a  /tmp and it does have the right permissions.

**Comment by nicm** [comment]
Run this to reproduce please and attach the strace.out* files:

tmux kill-server
strace -tt -ff -ostrace.out tmux new

**Comment by dodona2** [comment]
23:17:33.432770 getpid()                = 57602
23:17:33.432859 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
23:17:33.432933 rt_sigaction(SIGTSTP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, 8) = 0
23:17:33.432982 rt_sigaction(SIGTTIN, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, 8) = 0
23:17:33.433027 rt_sigaction(SIGTTOU, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, 8) = 0
23:17:33.433103 rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, {sa_handler=0x559cfac4fe60, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, 8) = 0
23:17:33.433146 rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, 8) = 0
23:17:33.433186 rt_sigaction(SIGTERM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, {sa_handler=0x559cfac4f940, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fccd3be36b0}, 8) = 0
23:17:33.433221 rt_sigaction(SIGCHLD, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fccd3be36b0}, {sa_handler=0x559cfac32d20, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fccd3be36b0}, 8) = 0
23:17:33.433257 rt_sigaction(SIGCHLD, {sa_handler=0x559cfac32d20, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fccd3be36b0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fccd3be36b0}, 8) = 0
23:17:33.433294 rt_sigaction(SIGINT, {sa_handler=0x559cfac50230, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fccd3be36b0}, 8) = 0
23:17:33.433336 dup2(4, 1)              = 1
23:17:33.433363 close(4)                = 0
23:17:33.433389 close(3)                = 0
23:17:33.433493 rt_sigprocmask(SIG_BLOCK, NULL, [], 8) = 0
23:17:33.433573 write(1, "/root\n", 6)  = 6
23:17:33.433662 exit_group(0)           = ?
23:17:33.433774 +++ exited with 0 +++

**Comment by dodona2** [comment]
I wonder that a strace -tt -ff -ostrace.out tmux new invokes a working tmux, whereas a tmux new dies immediately with 
**no server running on /tmp/tmux-0/default**

**Comment by nicm** [comment]
This is not all of all the files?

**Comment by dodona2** [comment]
indeed as github software doesn't allow me to upload a .tar,gz.

**Comment by nicm** [comment]
You are not making sense, does it work with strace or not? The strace you uploaded is not the full output from either a working or not working tmux, please show all the full strace* files.

**Comment by dodona2** [comment]
meanwhile the problem disappeared.

@nicm please read me comment above yours.
