### ISSUE TITLE
Pane border side styles are not configurable using inline styles in pane-border-format

### ISSUE THREAD

**Issue by tculp** [tmux/tmux#2028]
### Issue description

Currently, there seems to be no way to configure the style of the outside area of pane borders using inline styles in the pane-border-format variable. This also means there is no way to set the style dynamically based on variables.

My test tmux.conf:

```
set -g pane-border-status bottom
set -g pane-border-style ""
set -g pane-active-border-style ""
set -g pane-border-format "#[#{?#{pane_active},bg=red fill=red,bg=blue fill=blue}]"
```

A screenshot of the result is attached.

<img width="1282" alt="Screen Shot 2019-12-22 at 10 30 24 PM" src="https://user-images.githubusercontent.com/19711877/71334242-4b838580-250b-11ea-9ac9-805503dc24ee.png">

As you can see, the vertical bars are not styled according to the inline style, as well as the right and left side of the bottom-bars.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.0a
* Platform (`uname -sp`).
Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`).
inside: screen-256color
outside: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
no logs

**Comment by nicm** [comment]
Yes I know, how would it look though? I suppose we could have an "indent" member of the style that controls how many cells left of the pane edge it draws the border. Or always draw it at 0 and have some way to specify border characters in the format.

**Comment by tculp** [comment]
Well since the bottom status bar always draws with 0 implicit margin on both sides, I think it would make sense if the pane border also didn't have any horizontal margin.

I'm not sure of how best to do the sides in code. From a user's pov, maybe the background / foreground of the status would just carry over to the sides, or maybe it would require a push-default. Any ideas?

Note: I just tested changing the border indent and the default style looked better with the indent in place (green text on black background), but my style (with an orange/blue background color) looked fine without the indent. Maybe it would be fine for the indent to be an option, something like pane-border-indent, defaulted to 2.

**Comment by nicm** [comment]
We are moving away from having options for every little thing, so I don't want pane-border-indent, it needs to be expressed in the style, which would also allow it to be used in other contexts.

I don't think it would be very intuitive to make it work out the colour from the format.

I think it would be better to have a style like "fill" (perhaps "indent", or "padding" might be better if it was doing both sides), then the default pane-border-style could be "padding=2".

You can look at 2da050413c17e587be8bede710112096ce6b5f5a if you want to see how fill was implemented, basically you need a member in struct style and associated parsing code in style.c then you need to handle it in format-draw.c:format_draw. For this, at least screen-redraw.c:screen_redraw_make_pane_status and screen_redraw_draw_pane_status will need to change to use the full width, possibly other bits in the same file.

**Comment by tculp** [comment]
Rather than defining a new style type, wouldn't it make sense to just make "#[align=left]──" and "#[align=right]──" part of the default pane border format? That makes it just part of the existing format, which it already really was.

And with your mention of fill (which only does the background), would it make sense to also have something like fill-fg to do the foreground? This would allow people to basically do what the default pane border does, which is have the horizontal line fill all the way to the end.

**Comment by nicm** [comment]
align left and right

**Comment by tculp** [comment]
I'm not sure, because padding would be a weird mix of style and format if you are specifying characters. 

I tested out getting the offset to 0 and it wasn't difficult, just replacing a few +2s here and there in style.c.

Also, do you mean you can't specify those characters in the style, or in general? I tested adding the horizontal line chars (─) to my pane border by pasting the character in and it worked fine. The command I used was: `tmux setw -g pane-border-format "#[align=left]──testing #[align=right bold]──"`

**Comment by nicm** [comment]
Those are Unicode horizontal lines, not ACS characters, they will only display properly on terminals which support Unicode.

**Comment by tculp** [comment]
Ah, so those are provided and generated by ncurses, and just rendered and copyable as unicode?

**Comment by nicm** [comment]
No it is a terminal feature. tmux will use Unicode if the terminal supports it.

But we can't implement a solution to let you move the position of status-format that doesn't work on terminals which don't have UTF-8. So it would need to use ACS rather than requiring UTF-8 in status-format.

**Comment by tculp** [comment]
So there seems to be several possible features that could be added.

1. Adding a style option to support filling the foreground, such as fill-fg.

2. Adding a way of specifying ACS characters (that use UTF-8 when possible). This would be especially useful if #1 was implemented.

3. Adding a style option to support padding, though if #2 were implemented then this seems more or less unnecessary to me, especially if the offset for pane borders was made 0.

4. Adding a way of specifying the foreground and background of the pane borders in a more dynamic way than the current style.

Do these seem like good features to you / would you add these to master if written?

**Comment by nicm** [comment]
I don't know what you mean for (4).

I don't mind having all of (1) (2) and (3), but I think (3) is the nicest solution - pane-border-style will just become `pad=2` instead of `default` and if you want the text at offset 0 you just change it to `default`.

If we did (2) then pane-border-format would need to become something like `#[acs]qq#[noacs]...` which will break anyone's config who just changes pane-border-format, not to mention making no sense unless you know which ACS character is which.

I don't really see why you need fill-fg and I think it will be fiddly to express it in a style because you will need to specify all three of a foreground colour, attributes and a character.

Adding ACS would be very simple - you just need to add an acs attribute to the style which sets GRID_ATTR_CHARSET. You don't need to worry about UTF-8, if it ends up as a grid_cell with GRID_ATTR_CHARSET set and an ACS character (like 'x' or 'q') in the data, then tmux will translate it to UTF-8 if needed.

**Comment by tculp** [comment]
For (4), I'm referring to the original reason my my creating this issue, where you cannot configure the pane sides with variables.

Also I wanted to ask: is there a particular reason why styles are forced to be static, and not parsed exactly like inline styles in formats? This would solve this issue by itself, as well as eliminate the need for certain copies of styles, such as pane-border-style and pane-active-border-style, which would help satisfy "moving away from having options for every little thing".

I think it would also not break any existing configs (until options are removed/deprecated) since functionality would be added, but wouldn't interfere with any statically-defined styles.

I also think it would make more sense from a user's perspective, in that inline styles would have the exact same syntax (minus the #[]) as the -style attributes.

What would you think of that?

**Comment by nicm** [comment]
Oh you want to change the vertical borders as well, I thought you just meant the bits to the left and right of the text.

Yes you could change it so that styles are parsed at time of use as well as when they are set, but I think it should only happen for styles containing #{ otherwise it will add a lot of time.

You could probably just save the style string in struct style and change options_get_style to take a format_tree and do the expansion if the style has any #{.

**Comment by tculp** [comment]
Sounds good, I'll start looking into that.

**Comment by nicm** [comment]
Are you still working on this?

**Comment by nicm** [comment]
I have added this to the todo list for the moment, let me know if you make any progress. Thanks!

**Comment by tculp** [comment]
Hey, I worked on this but it could still use some work. I would appreciate if you took a look
