### ISSUE TITLE
[Feature Request] read tmux.conf from URL

### ISSUE THREAD

**Issue by deitch** [tmux/tmux#2033]
Is it possible to read `tmux.conf` from a URL? The use case I am thinking is launching a container or cloud VM, where my `.tmux.conf` likely doesn't exist, but `tmux` itself is becoming standard on more and more distros.

If I could `ssh user@host tmux -f https://raw.github.com/user/repo/tmux.remote.conf` (or similar), I could save that as a profile standard or alias and not worry about transmitting my `tmux.conf` with each connection.

I did look in the man pages and the issues and not see it anywhere; if I missed it, feel free to point out the error and close this.

Of course, always open to new ways of doing it.

**Comment by nicm** [comment]
No you will need to download it first.

**Comment by tculp** [comment]
Something like `ssh -tt user@host '/usr/local/bin/wget https://raw.github.com/user/repo/tmux.remote.conf -O ~/.tmux.remote.conf &>/dev/null && /usr/local/bin/tmux -f ~/.tmux.remote.conf'` would likely work

**Comment by deitch** [comment]
Yeah I think you’re right. Nice to have it built in.
