### ISSUE TITLE
tmux3.0a doesn't work

### ISSUE THREAD

**Issue by yguo33** [tmux/tmux#2036]
* Platform (`uname -sp`):
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`):
xterm
* Logs from tmux (`tmux kill-server; tmux -vv new`):
`error connecting to /tmp/tmux-10000/default (No such file or directory)
*** Error in `tmux': corrupted size vs. prev_size: 0x0000000001c87a60 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x80f87)[0x7fd396dcff87]
/lib64/libc.so.6(+0x82485)[0x7fd396dd1485]
/lib64/libc.so.6(__libc_calloc+0xb4)[0x7fd396dd5564]
tmux[0xtmux[0x437c42]
tmux[0x4079a7]
tmux[0x404999]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fd396d71505]
tmux[0x404be7]
======= Memory map: ========
00400000-00492000 r-xp 00000000 fd:01 667805                             /usr/local/bin/tmux
00691000-00692000 r--p 00091000 fd:01 667805                             /usr/local/bin/tmux
00692000-00693000 rw-p 00092000 fd:01 667805                             /usr/local/bin/tmux
00693000-0069a000 rw-p 00000000 00:00 0
01c7d000-01c9e000 rw-p 00000000 00:00 0                                  [heap]
7fd38c000000-7fd38c021000 rw-p 00000000 00:00 0
7fd38c021000-7fd390000000 ---p 00000000 00:00 0
7fd3903f3000-7fd390408000 r-xp 00000000 fd:01 657577                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fd390408000-7fd390607000 ---p 00015000 fd:01 657577                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fd390607000-7fd390608000 r--p 00014000 fd:01 657577                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fd390608000-7fd390609000 rw-p 00015000 fd:01 657577                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fd390609000-7fd396b33000 r--p 00000000 fd:01 657744                     /usr/lib/locale/locale-archive
7fd396b33000-7fd396b4a000 r-xp 00000000 fd:01 657592                     /usr/lib64/libpthread-2.17.so
7fd396b4a000-7fd396d49000 ---p 00017000 fd:01 657592                     /usr/lib64/libpthread-2.17.so
7fd396d49000-7fd396d4a000 r--p 00016000 fd:01 657592                     /usr/lib64/libpthread-2.17.so
7fd396d4a000-7fd396d4b000 rw-p 00017000 fd:01 657592                     /usr/lib64/libpthread-2.17.so
7fd396d4b000-7fd396d4f000 rw-p 00000000 00:00 0
7fd396d4f000-7fd396f12000 r-xp 00000000 fd:01 657566                     /usr/lib64/libc-2.17.so
7fd396f12000-7fd397112000 ---p 001c3000 fd:01 657566                     /usr/lib64/libc-2.17.so
7fd397112000-7fd397116000 r--p 001c3000 fd:01 657566                     /usr/lib64/libc-2.17.so
7fd397116000-7fd397118000 rw-p 001c7000 fd:01 657566                     /usr/lib64/libc-2.17.so
7fd397118000-7fd39711d000 rw-p 00000000 00:00 0
7fd39711d000-7fd397133000 r-xp 00000000 fd:01 660249                     /usr/lib64/libresolv-2.17.so
7fd397133000-7fd397332000 ---p 00016000 fd:01 660249                     /usr/lib64/libresolv-2.17.so
7fd397332000-7fd397333000 r--p 00015000 fd:01 660249                     /usr/lib64/libresolv-2.17.so
7fd397333000-7fd397334000 rw-p 00016000 fd:01 660249                     /usr/lib64/libresolv-2.17.so
7fd397334000-7fd397336000 rw-p 00000000 00:00 0
7fd397336000-7fd39737c000 r-xp 00000000 fd:01 667796                     /usr/lib64/libevent-2.0.so.5.1.9
7fd39737c000-7fd39757b000 ---p 00046000 fd:01 667796                     /usr/lib64/libevent-2.0.so.5.1.9
7fd39757b000-7fd39757c000 r--p 00045000 fd:01 667796                     /usr/lib64/libevent-2.0.so.5.1.9
7fd39757c000-7fd39757d000 rw-p 00046000 fd:01 667796                     /usr/lib64/libevent-2.0.so.5.1.9
7fd39757d000-7fd39757e000 rw-p 00000000 00:00 0
7fd39757e000-7fd3975a3000 r-xp 00000000 fd:01 657638                     /usr/lib64/libtinfo.so.5.9
7fd3975a3000-7fd3977a3000 ---p 00025000 fd:01 657638                     /usr/lib64/libtinfo.so.5.9
7fd3977a3000-7fd3977a7000 r--p 00025000 fd:01 657638                     /usr/lib64/libtinfo.so.5.9
7fd3977a7000-7fd3977a8000 rw-p 00029000 fd:01 657638                     /usr/lib64/libtinfo.so.5.9
7fd3977a8000-7fd3977aa000 r-xp 00000000 fd:01 660948                     /usr/lib64/libutil-2.17.so
7fd3977aa000-7fd3979a9000 ---p 00002000 fd:01 660948                     /usr/lib64/libutil-2.17.so
7fd3979a9000-7fd3979aa000 r--p 00001000 fd:01 660948                     /usr/lib64/libutil-2.17.so
7fd3979aa000-7fd3979ab000 rw-p 00002000 fd:01 660948                     /usr/lib64/libutil-2.17.so
7fd3979ab000-7fd3979cd000 r-xp 00000000 fd:01 657552                     /usr/lib64/ld-2.17.so
7fd397bb9000-7fd397bbe000 rw-p 00000000 00:00 0
7fd397bc9000-7fd397bcc000 rw-p 00000000 00:00 0
7fd397bcc000-7fd397bcd000 r--p 00021000 fd:01 657552                     /usr/lib64/ld-2.17.so
7fd397bcd000-7fd397bce000 rw-p 00022000 fd:01 657552                     /usr/lib64/ld-2.17.so
7fd397bce000-7fd397bcf000 rw-p 00000000 00:00 0
7ffe1e530000-7ffe1e551000 rw-p 00000000 00:00 0                          [stack]
7ffe1e5f0000-7ffe1e5f3000 r--p 00000000 00:00 0                          [vvar]
7ffe1e5f3000-7ffe1e5f5000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)`

`which tmux`: /usr/local/bin/tmux
`tmux`: server exited unexpectedly
`tmux -V`: tmux 3.0a
`tmux ls`: error connecting to /tmp/tmux-10000/default (No such file or directory)

**Comment by nicm** [comment]
How did you build tmux? Are you sure you are using the same libevent version as you built against?
