### ISSUE TITLE
Conditional evaluation not working as expected

### ISSUE THREAD

**Issue by petobens** [tmux/tmux#2037]
Hi! I guess this is more a question than a request since I'm probably missing something. Consider the following scenario:
```
> tmux display-message -p '#I'
4
> tmux display-message -p '#{==:#{I},4}'
0
> tmux display-message -p '#{==:#{I},}'
1
```
Why is that `#{I}` is empty (I would've expect it to be equal to 4)? Thanks in advance

**Comment by nicm** [comment]
#I not #{I}.

**Comment by petobens** [comment]
Ohh right. Thanks!
