### ISSUE TITLE
I use CTRL + L , it can't be clear the screen

### ISSUE THREAD

**Issue by JamesKid** [tmux/tmux#2039]
### Issue description
I use CTRL + L , it can't be clear the screen. 

### Required information

Please provide the following information:

* tmux version next-3.1
* Platform (`centos8`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).
![图片](https://user-images.githubusercontent.com/6158899/71512581-d8df2500-28d1-11ea-9363-0d76ec192e5e.png)

when i exit tmux, then i use CTRL+L it's ok.

**Comment by nicm** [comment]
What terminal are you using? Sounds like https://github.com/tmux/tmux/issues/931 and various other issues. Either upgrade your terminal or put this in .tmux.conf and entirely restart tmux:
~~~~
set -as terminal-overrides '*:indn@'

**Comment by JamesKid** [comment]
ok, many thanks.
