### ISSUE TITLE
Support linking of windows from remote tmux sessions

### ISSUE THREAD

**Issue by BlacklightShining** [tmux/tmux#204]
Currently, the best solution I have for managing multiple long-running processes across different machines is to run a tmux session on each machine, and then nest them (`tmux new-window ssh $foo tmux attach`). Sure, I could open other terminal windows and invoke `ssh ...` in them, but that defeats part of the purpose of using `tmux`—i.e. to be able to have _one_ terminal with everything in it.

Being able to link windows from remote sessions would be really nice. (Maybe over `ssh`? I have passwordless `ssh` set up, and I'm sure many others do, too.) `tmux` might also notice when a connection had failed and handle reconnecting automatically.

**Comment by nicm** [comment]
It is never going to happen without ssh for sure.

The way to do this would be to write a tmux client that could use control mode from several servers, but I'm not sure that is likely either.

**Comment by BlacklightShining** [comment]
That was quick. Sorry, what? This response seems a bit vague, and…I dunno. I guess I was expecting _some_ discussion before being shot down.

**Comment by nicm** [comment]
Well, you are not being shot down but what discussion would you like? Yes, it might be nice to have this. No, it would not be acceptable without using ssh - making tmux use the network unencrypted is not going to happen, nor is building encryption into tmux.

Other than that, it is a significant amount of work. I suggest first looking at what iterm2 does and using control mode, I'd probably try to make tmux have some sort of concept of a "remote session" which is entirely from another server.

**Comment by BlacklightShining** [comment]
I don't see a problem with using `ssh` for transport (I did suggest it, after all). I'm definitely not advocating for using the network without good, strong crypto in some form or another.

**Comment by dustymabe** [comment]
@nicm I'd be interested in your thoughts on what the tmate guys are doing and how it relates to a possible solution to this issue. https://tmate.io/ --> scroll down to "Technical Details" section.

It looks like they have a remote tmux server and a local tmux server tunneled through ssh? It would be really awesome if we could have something like:

```
tmux remote-attach bob@foobar.com -t 1
```

and then if the connection ever goes down just loop retry the ssh/attach.

**Comment by nicm** [comment]
We already have a protocol for control mode, making tmux itself use control
mode would be the best solution. This would be similar to how tmate does it
I think.

**Comment by dustymabe** [comment]
Let me see if I understand this. If we made tmux use control mode natively then it wouldn't really matter if the tmux server were remote or local? 

I tried to do a poor mans workaround for this by using ssh socket forwarding. It works for control mode (which means it probably could work), but doesn't work for tmux itself:

```
LOCAL# ssh -L /tmp/footmux:/tmp/tmux-1000/default 192.168.2.100
REMOTE# tmux # This starts the server
```

```
LOCAL# tmux -S /tmp/footmux attach
open terminal failed: not a terminal
```

I am currently using an older version in fedora so forgive me if things have changed significantly since then: `tmux-1.9a-5.fc22.x86_64`

**Comment by nicm** [comment]
Right, although I think I would probably try to do it at session level
rather than letting you mix windows in remote and local sessions.
.

**Comment by dustymabe** [comment]
I assume "right" was the answer to my only question above. Do you see this as something useful? Should I add it as a TODO item? Here is some example text to add to TODO:


_"Make tmux use control mode natively. Tmux could then talk with remote or local tmux servers via control mode and the tmux client could be used to attach to remote sessions. "_


On a side note, with my ssh socket forwarding approach from above, is there any way to get that to work with tmux as it is now?

**Comment by nicm** [comment]
No and no.

**Comment by dustymabe** [comment]
OK, thank you for your time.

**Comment by mfarrugi** [comment]
Should this be handled by an alternative client? Why is it undesirable for the native tmux client to support this?

**Comment by dunemkk** [comment]
I would love to connect to a remote tmux session. Now the only solution I know is to ssh and imitate nesting (remote sesion in local window; different prefix and so on).

**Comment by Krever** [comment]
What is the status of this issue? I see that it is closed but I see no explanation for it. Form my point of view it is very interesting feature and I'm probably not alone in this opinion.

**Comment by dunemkk** [comment]
At this point I think we all use Tmuxinator and opening different sessions (local and remote) from it. Couldn't see any changes for this in nearly a year.

**Comment by tmccombs** [comment]
What's wrong with having the tmux client support control mode natively?

**Comment by eugene-yang** [comment]
To be honest, I don't see why there would be some security issues by making local tmux able to connect to remote tmux server via ssh. 

The ssh connection would still be specified by end user and the credentials will never be touched by tmux. By just letting tmux to connect to remote server via user-specified connecting command to perform reversed tunnel like what @dustymabe suggested, I think this idea is feasible.
I'm really wondering what are the main concerns here.

**Comment by nicm** [comment]
The main concern is that nobody has written any code, I have said how I think this should work (control mode over ssh) and where I would look for the first steps. I am not planning to implement this myself in the near future.

**Comment by dustymabe** [comment]
I think part of the mixed message here is from https://github.com/tmux/tmux/issues/204#issuecomment-210561628 where the answer to the *"Do you see this as something useful? Should I add it as a TODO item?"* from https://github.com/tmux/tmux/issues/204#issuecomment-210559355 was *"No and no."*

We could maybe get a contributor to work on a patch if they thought there was a chance it would get accepted. If someone wrote a patch for *Make tmux use control mode natively*, would you possibly accept it?

**Comment by nicm** [comment]
That was no it should not go in the TODO and no there is no way to make it work with the existing tmux socket. I think it is clear from other messages that this idea might be a nice thing to have.

It will be a large and complex change and you will need to come and discuss it with me once you have a good idea how you think it will look or a first cut of some code, and then it will need work over time to go in probably in stages. It is likely to take a while.

**Comment by anatoli26** [comment]
Any change in the status of this feature request? Does it make sense to set a bounty for it so those who know tmux internals could dedicate time to implement it in the near future?

**Comment by ThomasAdam** [comment]
Status still the same.  tmux needs to use control mode to implement this.

We don't need bounties for this.  It will happen if/when it happens, just like everything else we do in tmux.
