### ISSUE TITLE
Is tmux supposed to save commands to .bash_history?

### ISSUE THREAD

**Issue by kplachkov** [tmux/tmux#2040]
### Issue description
I open tmux, execute some commands and after I reboot the system, none of the commands are in the history. Is that the normal behavior of tmux?

### Required information
[.tmux.conf](https://github.com/kplachkov/dotfiles/blob/master/.tmux.conf)
```
$ uname -sp && tmux -V && echo $TERM                                                                                          
Linux x86_64                                                                                                                                       
tmux 2.9a                                                                                                                                          
xterm-256color  
```

**Comment by nicm** [comment]
This has nothing to do with tmux, it is entirely up to Bash what commands it saves in its history and when.

**Comment by kplachkov** [comment]
Yes, thanks
