### ISSUE TITLE
[Feature request: slightly improved messages on unexpected exit] I would like to suggest to show a bit more information when tmux fails instantly upon starting

### ISSUE THREAD

**Issue by rubyFeedback** [tmux/tmux#2041]
tmux version: 3.0a

Platform: Linux (slackware, but I compiled most of it from source at this point; only glibc is quite old, version 2.23, rest is current stable)

TERM is xterm.

This is a feature request.

Commandline invocation:

    > tmux

Result:

one-line output:

**server exited unexpectedly**

To me this is not very useful. Three words, and I have no real idea what to do with this.

I do not know what the problem is, but it may be related to curses/ncurses (I installed
ncurses following the LFS guide here: http://www.linuxfromscratch.org/lfs/view/development/chapter06/ncurses.html)

So here is what I would like to suggest - feel free to disregard if it is too much work or not worth the additional time investment.

1) I propose adding some option like --verbose or so in the long run, so that more text can be shown when things go awry, such as in this case. But this is just a loose idea.

2) I propose that more information is shown. Right now the "server exited unexpectedly" really does not tell me much at all. I have to wonder WHY it died. I think any information shown more here may be useful - to tell the user why it died. This could be put in parentheses such as:

    server exited unexpectedly (could not draw ncurses terminal pane)

or something like that. This would not be ideal either, but it would be an improvement over the current status quo, IMO. That is to provide the user with information that may be of help.

I'd even propose to show a lot more information, as much as possible, but I guess this is a design decision how much information you want to show. But as it stands, these three words alone really don't tell me much; and "strace tmux" is a bit cumbersome to use. Admittedly I gave up on that part; I may try at some later point in time but I have always found it simpler to move on and come back at a problem at a later time. Thank you for reading - please feel free to close this issue at any moment in time as you see fit.

**Comment by ThomasAdam** [comment]
Usually with a sever error, it's a bug or segfault which causes it.  In those cases, we already have `-v` to produce logging.

To do what you're describing would ultimately need us to write more code, which is not necessary given tmux logging already providing the relevant information,

**Comment by nicm** [comment]
There is no information, when this happens this message is all the client knows. If the server was able to send more information then it would be able not to exit.

**Comment by krader1961** [comment]
@nicm How about including in that message a permalink to a [FAQ](https://github.com/tmux/tmux/wiki/FAQ) entry about what the user can do to collect more information when this situation occurs?

When I starting working on the Korn shell two years ago there were so many SIGSEGV failures when executing unit tests on Travis CI it was quite discouraging. So I implemented a SIGSEGV handler that produces a backtrace so we'd have at least some idea why the SIGSEGV occurred. Here's an example of a NULL pointer dereference I deliberately introduced to show what happens:

```
KSH PROMPT:1: echo $SECONDS
### 67086 Function backtrace:
1   handle_sigsegv (in ksh) (fault.c:72)
2   _sigtramp (in libsystem_platform.dylib) + 29
3   0x0000ffff (in ksh)
4   nv_getv (in ksh) (nvdisc.c:71)
5   nv_getval (in ksh) (name.c:2408)
6   varsub (in ksh) (macro.c:1377)
7   copyto (in ksh) (macro.c:598)
8   sh_macexpand (in ksh) (macro.c:250)
9   arg_expand (in ksh) (args.c:1009)
10  sh_argbuild (in ksh) (args.c:870)
11  sh_exec (in ksh) (xec.c:980)
12  exfile (in ksh) (main.c:517)
13  sh_main (in ksh) (main.c:315)
14  main (in ksh) (pmain.c:39)
15  start (in libdyld.dylib) + 1
fish: 'src/cmd/ksh93/ksh' terminated by signal SIGABRT (Abort)
```

The code that does that is pure ANSI C and works on BSD and Linux:

https://github.com/att/ast/blob/5abcbd06612d28d2070e6e9d06e8ebe834a72a1d/src/lib/libast/misc/debug.c#L347-L352

**Comment by nicm** [comment]
I don't think this is necessary, this doesn't happen that often and most people are able to use the existing tools. I would be happy to see an FAQ entry with a summary.

**Comment by krader1961** [comment]
> this doesn't happen that often and most people are able to use the existing tools.

I haven't seen this failure mode in a very long time (easily > 5 years). And while I regularly install a tmux binary built from the source "head" I use a small subset of tmux features (I don't use panes, for example). Yet this failure mode does seem to get reported on a semi-regular basis. And the typical tmux user who reports this doesn't seem to be aware of how to proceed and how to provide useful information when it does occur. And while logging will typically provide enough info to determine root cause that a) isn't always the case, and b) users don't typically have logging enabled which means that if the failure is hard to reproduce you lose a chance to quickly resolve the issue. At Google the sort of SIGSEGV handler I proposed is known as collecting a "death rattle". No guarantee the info it provides will help determine root cause but it is certainly better than no info about the failure.

**Comment by nicm** [comment]
Yes, I know, I have done this before, but I don't want it in tmux, it is gross and not portable.

I'd be happy to have an FAQ entry with this message and next steps, do you want to suggest some text? I would be OK with either a single question in FAQ.md or an entirely new  page.

We can't link to the FAQ from the code, the binary should be self-contained and not rely on websites. But it would give anyone who searches something to find.

We should also list all of the detach/exit messages in the manual with some further explanation.

**Comment by krader1961** [comment]
> Yes, I know, I have done this before, but I don't want it in tmux, it is gross and not portable.

FWIW, the code I wrote for ksh works on Linux, macOS, OpenBSD, FreeBSD and OpenIndiana (a Solaris fork). It does require build time feature tests for the `addr2line` and `atos` programs to get backtraces that include line numbers rather than just function name + offset. It also needs a build time feature test for whether `backtrace()` is in libc or libexecinfo. But that's it.

> We should also list all of the detach/exit messages in the manual with some further explanation.

Yeah, that would be good. Perhaps a section headed "EXIT MESSAGES" either before "ENVIRONMENT" or "EXAMPLES". In fact, if that section has sufficient detail a wiki FAQ entry may not be necessary. Perhaps something along these lines:

```
server exited unexpectedly

The connection between the tmux client and server was severed unexpectedly. This usually means the tmux server died. This should not happen unless you deliberately killed the server (e.g., with the kill command). Please confirm the tmux server is no longer running; e.g., `ps waux | grep '[t]mux'` should produce no output. Then restart the server with `tmux -vvv` and attempt to reproduce the failure. When the failure occurs again open an issue at https://github.com/tmux/tmux/issues/ and attach the server and client log files. If you know how to do so it may be useful to enable core dumps (e.g., `ulimit -c unlimited`) since a likely reason for this failure mode is the tmux server being killed by a SIGSEGV which will result in a core dump if they are allowed.
```

Then the client exit message could refer the user to that section of the man page.

**Comment by ThomasAdam** [comment]
Using `kill-server` won't produce these error states; it's misleading to think otherwise, so I'd elide that.  Personally, I don't think this needs any over-egging, other than to say we should document the error states as simply as needed, and move on with our lives.

I'm sure we all have a life to be getting on with...

**Comment by krader1961** [comment]
I meant kill(1)/pkill(1) but, yes, it doesn't matter much if that verbiage is present.

**Comment by krader1961** [comment]
And for those following this issue there are several messages a tmux client might display when it terminates as defined here:

https://github.com/tmux/tmux/blob/566ab9aa286f6d0468d2d5196367eb6d3c658270/client.c#L176-L211

Documenting all of them is ideal but given that the only error message I can recall being reported with any regularity is "server exited unexpectedly" documenting the others in any but a cursory fashion is probably hard to justify.

**Comment by nicm** [comment]
It has only been "server exited unexpectedly" for one release, before that
it was "lost server" so it is probably worth mentioning also in the FAQ.

But yes we should document them all with a couple of sentences each in the
manual also.

I'll take a look when I am home in a few days, thanks.

**Comment by nicm** [comment]
I have added an FAQ entry here: https://github.com/tmux/tmux/wiki/FAQ#tmux-exited-with-server-exited-unexpectedly-or-lost-server-what-does-this-mean

I have added a section to tmux.1:
~~~~
EXIT MESSAGES
     When a tmux client detaches, it prints a message.  This may be one of:

     [detached (from session ...)]
             The client was detached normally.

     [detached and SIGHUP]
             The client was detached and its parent sent the SIGHUP signal
             (for example with detach-client -P).

     [lost tty]
             The client's tty(4) or pty(4) was unexpectedly destroyed.

     [terminated]
             The client was killed with SIGTERM.

     [exited]
             The server exited when it had no sessions.

     [server exited]
             The server exited when it received SIGTERM.

     [server exited unexpectedly]
             The server crashed or otherwise exited without telling the client
             the reason.
