### ISSUE TITLE
[Feature Request] Sizing should disregard read-only clients

### ISSUE THREAD

**Issue by MaxBarraclough** [tmux/tmux#2042]
Proposal
--------

I suggest that sizing should disregard any read-only clients. This way, read-only clients are truly read-only.

Implementation
--------------

I originally saw this idea in an old blog post [0], which gives a one-line implementation.

In the modern tmux codebase, it seems to be single line change in tmux.h, adding `CLIENT_READONLY` to `CLIENT_NOSIZEFLAGS`. This seems to work fine for me, at least.

[0] https://brianmckenna.org/blog/guest_tmux

**Comment by nicm** [comment]
Yes, OK. If you add it to CLIENT_NOSIZEFLAGS does it work?

**Comment by MaxBarraclough** [comment]
@nicm  Yes, it worked for me, compiling without issue and giving the behaviour I'm suggesting.

Resizing my read-only client doesn't affect sizing, resizing my ordinary client causes the read-only client to see its new size.

It was just a brief test though; I can't speak to whether it subtly breaks anything.

**Comment by nicm** [comment]
I was more getting at what happens to the read only client. We couldn't have done this before because having the size set by a larger client would mean the smaller would not draw correctly, but now it works OK. I have changed this now in OpenBSD, it will be in GitHub later. Thanks!

**Comment by MaxBarraclough** [comment]
Splendid, thanks @nicm
