### ISSUE TITLE
boarder hide part of content

### ISSUE THREAD

**Issue by itetao** [tmux/tmux#2043]
*tmux version: tmux 2.9a
*Platform: fedora 30 Linux x86-64
*terminal: gnome terminal
*echo $TERM: xterm-256color
*config file: not set

Hi, 
I open two panel, right panel's content not display all contents by ls command
boarder has hide some contents, I don't known how to solve it, need your help, very thanks
![Screenshot from 2019-12-30 11-00-26](https://user-images.githubusercontent.com/46645709/71566875-23d98200-2af6-11ea-833f-db91052e8d42.png)

**Comment by nicm** [comment]
Does this happen in other terminals like xterm?
