### ISSUE TITLE
Typo in style options FAQ entry (wiki page)

### ISSUE THREAD

**Issue by nicoder** [tmux/tmux#2045]
in https://github.com/tmux/tmux/wiki/FAQ#how-do-i-translate--fg--bg-and--attr-options-into--style-options it says:

```
set -g mode-bg yellow
set -g mode-fg red
set -g mode-attr blink,underline
```

Should be changed to:

```
set -g mode-style fg=yellow,bg=red,blink,underline
```

=> fg and bg are inverted?

_Originally posted by @nicm in https://github.com/tmux/tmux/issues/1689#issuecomment-486732891_

**Comment by nicm** [comment]
FIxed, thanks!
