### ISSUE TITLE
window activity and silence flags

### ISSUE THREAD

**Issue by illtown** [tmux/tmux#2047]
I find it weird being able to see both of these flags set at the same time, shouldn't one reset the other? That way we could achieve more dynamic styling of background windows if someone has different styles for these two flags defined.
I'm not sure how internally these flags are coded and if they are one-time checks, though. Consider this issue as a feature request, please.

Steps to reproduce:
```
tmux -f /dev/null
tmux setw monitor-activity
tmux setw monitor-silence 2
sleep 3; echo 'some activity'
ctrl-b c     # switch to new window
tmux display -p '#{W:#{window_flags} }'    # default window format displays flags too
```
which gives `#~- *`

**Comment by nicm** [comment]
A window may have been active and then silent or vice versa so I don't see
why it shouldn't have both flags set. If you don't want to see them both,
you can use a custom window-status-format to show what you want.

**Comment by illtown** [comment]
And if the window have been active then silent for a duration specified and then active again?
My goal is to reflect these changes dynamically and I can't figure out how to achieve that with just format language.

**Comment by nicm** [comment]
You will probably need a script that looks at the difference between
window_activity and the current time.

**Comment by illtown** [comment]
Ok, got it. You may close the issue if you find it irrelevant, thanks.
