### ISSUE TITLE
`tmux send-keys ^BSpace` seems to silently do nothing

### ISSUE THREAD

**Issue by asottile** [tmux/tmux#2049]
### Required information

Please provide the following information:

* tmux version (`tmux -V`).

(built from source today)

```console
$ ./tmux -V
tmux next-3.1
$ git rev-parse HEAD
6b0091e1850d25ccd47143c9df18e1dddef2f4d4
```

* Platform (`uname -sp`).

```console
$ uname -sp
Linux x86_64
```

* $TERM inside and outside of tmux (`echo $TERM`).

```console
$ echo $TERM
screen-256color
$ echo $TERM
xterm-256color
```

* `.tmux.conf`

```
set -g default-terminal screen-256color
set -g mouse on
set -g status-right "'#(hostname)' #(date --rfc-3339=seconds)"
```

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-9286.log](https://github.com/tmux/tmux/files/4022208/tmux-client-9286.log)
[tmux-out-9288.log](https://github.com/tmux/tmux/files/4022209/tmux-out-9288.log)
[tmux-server-9288.log](https://github.com/tmux/tmux/files/4022210/tmux-server-9288.log)

### Reproduction

Start tmux and then use these commands in another window:

```bash
tmux send-keys abc
tmux send-keys BSpace  # notice it deletes the c
tmux send-keys ^H  # notice it deletes the b
tmux send-keys ^BSpace  # appears to do nothing
```

I may be misunderstanding something here though.

Outside of tmux I get the following behaviour:

- type `abc`
- hit <kbd>backspace</kbd> (c disappears)
- hit <kbd>^H</kbd> (b disappears)
- hit <kbd>^backspace</kbd> (a disappears)

using [`curses`](https://github.com/asottile/t/blob/master/2019-09-29-curses-key-detector/t.py), I've confirmed that both ^H and ^Backspace send `\x08` (`curses.keyname(0x8)` -> `b'^H'`)

**Comment by nicm** [comment]
C-BSpace is not a key with its own escape sequence, if you want ^H then
send C-h, not C-BSpace.

**Comment by asottile** [comment]
then I expect `tmux send-keys` to exit nonzero and produce an error instead of silently doing nothing

for what it's worth, there are other things which resolve to the same escape sequence that are supported by `tmux send-keys` today, some examples:

```bash
# both send ^J
tmux send-keys $'\n'
tmux send-keys '^J'
# both send ^M
tmux send-keys $'\r'
tmux send-keys '^M'
# both send ^[
tmux send-keys 'Escape'
tmux send-keys '^['
```

**Comment by nicm** [comment]
C-BSpace sending ^H is a feature of your terminal, the examples you give are intrinsic parts of the terminal protocol - Escape always sends ^[, C-BSpace does not always send ^H.

**Comment by asottile** [comment]
cool, but silently eating the error case and doing nothing seems pretty unacceptable -- can `tmux send-keys` exit nonzero and produce an error message?

**Comment by nicm** [comment]
Maybe. I though xterm might send something unique with modifyOtherKeys 2, but it doesn't it just sends whatever Backspace isn't (so ^H if ^?, ^? if ^H).

**Comment by ThomasDickey** [comment]
The[ informational page](https://invisible-island.net/xterm/modified-keys.html) I made a few months ago might help.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/4051391/x.diff.txt)

Instead of reporting an error, I chose to treat the key as a string like any other unrecognised input:
~~~~
$ ./tmux send BSpce; cat
BSpce^C
$ ./tmux send C-BSpace; cat
C-BSpace^C

**Comment by asottile** [comment]
cool, that works! (tried out the patch locally)

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
