### ISSUE TITLE
Tmux inner session binds

### ISSUE THREAD

**Issue by disarmer** [tmux/tmux#205]
I have few binds for tmux inner session manipulating, for example:
bind-key -n M-Down send-prefix \; send-key c
Previously, they worked fine, but with tmux 2.1 they just prints "c" in inner session

Steps to reproduce:
1. Add this bind to ~/.tmux.conf
2. Start inner tmux inside tmux session (TMUX= tmux)
3. Press alt+down
In tmux 2.0 and before it creates new window. But in version 2.1 it just print "c"

**Comment by nicm** [comment]
Please try tmux from git.

**Comment by disarmer** [comment]
Same issue with git version (2.2)

**Comment by nicm** [comment]
You made the inner tmux the one from git, right?

**Comment by disarmer** [comment]
Yes, both tmux servers use version from git. Can you reproduce problem?

**Comment by nicm** [comment]
I fixed it but apparently the change hasn't made it to GitHub yet.

**Comment by disarmer** [comment]
Great! Thank you very much
