### ISSUE TITLE
Status bar shell commands being disowned instead of closed when forcing status bar refresh

### ISSUE THREAD

**Issue by PrincessRTFM** [tmux/tmux#2050]
As requested (https://github.com/tmux/tmux/issues/1997#issuecomment-570913310) I'm opening a separate issue about this. Original description:

> In the right side of my tmux status line, I have a pair of `#()` elements, running commands that stay open and periodically print additional text to their standard output (one is `tail -n 1 -F` for instance, to show the status of a particular cronjob I have set for every ten minutes). Any time that tmux's `refresh-client -S` command is run (it's part of a couple of my keybinds), those two processes are disowned and new copies are started. I can see this by opening `htop`, hitting my tmux prefix, and doing `:refresh-client -S` - the two processes are suddenly direct children of `init` and there's a new pair running under `tmux`. On top of that, no SIGHUP is sent; I have to manually `kill -s HUP` them, at which point they terminate normally. Is there something I'm missing in my tmux configuration, or a different signal being sent to the processes?

As instructed, I added a new element consisting of `#(while true; do date; sleep 1; done)` to the status bar and tried again. When forcing the status bar to refresh via `:refresh-client -S`, that element does not linger. According to `htop`, the two that _do_ linger are disowned and the shells that were opened to run them terminate, as shown here:

![](https://i.imgur.com/05DYfZg.png)

The yellow highlighted processes are the ones written in my configuration file. The top two are directly owned by `init`. Given the difference between my original subprocesses (the shell exists only to run the program itself, which then continues to run in the background) versus the line I was told to add (the shell is itself running a loop that spawns two short-lived processes repeatedly), is the problem maybe that the _shell_ is terminating appropriately but its children aren't?

### Required information

From outside tmux:

```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 3.0a
xterm-256color
```

From inside tmux:
```
$ echo $TERM
xterm-256color
```

Log files, from a completely fresh session, following `tmux kill-server` and with nothing but keybinding/statusbar setup and a single `:refresh -S` command:

- [tmux-client-10750.log](https://github.com/tmux/tmux/files/4023552/tmux-client-10750.log)
- [tmux-server-10752.log](https://github.com/tmux/tmux/files/4023554/tmux-server-10752.log)
- [tmux-out-10752.log](https://github.com/tmux/tmux/files/4023553/tmux-out-10752.log)

**Comment by nicm** [comment]
So it works with the example I gave? I'll look at the log later, it shows
the commands that don't work, right?

**Comment by PrincessRTFM** [comment]
Well, a quick `grep ddate tmux-*.log` returns 250 (on the dot, huh...) lines of output, and a look at the tail end of it gives me a bunch of lines from `tmux-server-10752.log` that do contain the entire command. If that's not enough, I can also give you the config for the status bar, but it's complex enough that it's in a separate `.tmux.theme.conf` file sourced at the end of my default config file. It's pretty heavily bastardised from a configuration package I found on someone else's repo.

**Comment by nicm** [comment]
ddate doesn't stay around though, it exits immediately. Which is the #() that you are keeping in the background? tail -f?

It looks fine to me, tmux is killing the previous process when the new one is started. Is the one that is left around still running or is it a zombie?

**Comment by PrincessRTFM** [comment]
Ah, that's a custom ddate script I wrote myself - the `-L` makes it do live updates every sixty seconds, sleeping in between. Both of them definitely stay around, the custom ddate and the tail. In any case, if it's working for you, then I guess I must've broken something on my system... are you testing on WSL Ubuntu? I know WSL can be wonky at times.

Okay, I just tested again, and the ones I highlighted in yellow are the old processes that stuck around after `refresh -S`:

![](https://i.imgur.com/zRM5fjU.png)

BUT the tail process terminated a minute or two later, while I was writing this. I left it for another ten minutes or so, but my ddate script didn't, so tail must be doing something I'm not - or I'm doing something it isn't. I just checked the node online docs on a hunch and saw that SIGPIPE is ignored by default - I'm going to try adding a handler for it to terminate the script, see if that does it.

**Comment by PrincessRTFM** [comment]
Yeah, that was it. The intermediary shell is terminated, any children of it that are still running are apparently disowned, and when they try to write output they get SIGPIPE and (_usually_) terminate. Node is weird in that its default action on SIGPIPE is to _ignore_ it instead of the standard of terminating. The reason I kept seeing tail sticking around in my earlier tests is that it wasn't writing until the cronjob ran.
