### ISSUE TITLE
100% cpu on one core and blank screen on start

### ISSUE THREAD

**Issue by anlx-sw** [tmux/tmux#2053]
### Issue description
I can't pinpoint the exact time - but tmux stopped working on my ubuntu 19.10 server.
if i start tmux with tmux -vv new the screen freezes and nothing is displayed. i see from another session that the process is using 100% cpu on one core and can only be killed with a sigkill (sigterm not working). I can't find the cause when reviewing the logs.

I tried to purge the package and reinstall - didn't help.

I tried also to use the latest tmux from git (built it under /tmp/tmux, chmod a+x tmux and ran it - same issue)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 2.9a (actually its tmux (2.9a-3build1) from the ubunto eoan repos)

* Platform (`uname -sp`).
Linux x86_64

* lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan

* $TERM inside and outside of tmux (`echo $TERM`).
xterm (outside) - can't run anything inside as the window freezes)

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-41965.log](https://github.com/tmux/tmux/files/4035279/tmux-client-41965.log)
[tmux-out-41968.log](https://github.com/tmux/tmux/files/4035280/tmux-out-41968.log)
[tmux-server-41968.log](https://github.com/tmux/tmux/files/4035281/tmux-server-41968.log)

**Comment by nicm** [comment]
Show the log from the tmux built from Git please.

**Comment by anlx-sw** [comment]
* logs from 3.1-next:
[tmux-server-50039.log](https://github.com/tmux/tmux/files/4035679/tmux-server-50039.log)
[tmux-client-50035.log](https://github.com/tmux/tmux/files/4035680/tmux-client-50035.log)

**Comment by nicm** [comment]
Please do `ulimit -c unlimited` in the terminal before starting tmux using the build from Git, then kill it with `kill -ABRT`. It should leave a core file, load it into gdb with `gdb ./tmux *core*` then do `bt full` and show me the output.

**Comment by nicm** [comment]
Never mind, I have reproduced.

**Comment by nicm** [comment]
OK the reason is the you have an invalid UTF-8 character in your date: 08-J\344n-20.

\344 is not valid UTF-8. I assume you are after ä which is \344 with Latin1, but it should be \303\244 with UTF-8.

I am going to fix this so tmux doesn't hang, but it will just omit the invalid character which is probably not what you want. I think you will need to configure your locale to UTF-8 so that date generates the correct UTF-8 output.

**Comment by nicm** [comment]
Yes you have no character encoding specified in LANG:
~~~~
LANG=de_AT
~~~~
Try configuring this to `de_AT.UTF-8`.

**Comment by anlx-sw** [comment]
thanks for the fast debugging! 

This makes sense - with the switch to Jän-2020 which stands for "january 2020" in german it broke it seems. I think it would be best to to handle invalid characters by omiting them because this could be hard to troubleshoot for users with a similar errors in other languages.

* Verified with tmux 2.9a:
The problem could be fixed by switching the locale from de_AT to de_AT.utf8.
