### ISSUE TITLE
tmux session freezes if I select text with the mouse

### ISSUE THREAD

**Issue by wizonesolutions** [tmux/tmux#2054]
### Issue description

The first or second time I select text with the mouse, the selection freezes (clicking/ctrl-C/typing does not show any changes in the window re-painting).

If I close the tab tmux is running in and reattach to the session, then I can see that input was registered (keypresses will show up on the command line, etc.).

However, this makes it hard to copy/paste text inside of tmux. I turned off plugins like tmux-yank (everything except resurrect/continuum), thinking they might have been breaking things, but now the only thing influencing that behavior should be mouse-mode itself, hence filing an issue here.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
`tmux 3.0a`

* Platform (`uname -sp`).
`Linux unknown` (it's Manjaro)

* $TERM inside and outside of tmux (`echo $TERM`).
`screen-256color` (both)

* Logs from tmux (`tmux kill-server; tmux -vv new`).
`server exited unexpectedly`

.tmux.conf:

```
set -g history-limit 999999999

set -ga update-environment ' SSH_ASKPASS DESKTOP_SESSION EDITOR XDG_CURRENT_DESKTOP'

# Just let bash set the environment, then drop to fish.
set-option -g default-command '/bin/bash -i -c /usr/bin/fish'

set-option -g mouse on
set-option -g prefix C-a

bind -n M-PgDn select-window -n
bind -n M-PgUp select-window -p


# https://gist.github.com/spicycode/1229612
# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R


set -g @resurrect-capture-pane-contents 'on'
#set -g @resurrect-processes '"~python /usr/bin/sshuttle"'
#set -g @continuum-boot 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
```

**Comment by nicm** [comment]
This is https://bugs.kde.org/show_bug.cgi?id=415249.

**Comment by wizonesolutions** [comment]
That looks exactly right. I'll install Konsole from the AUR, and hopefully that'll solve everything. Thanks.
