### ISSUE TITLE
[Feature Request] get config as an arg 

### ISSUE THREAD

**Issue by qiisziilbash** [tmux/tmux#2055]
Changing configs and key shortcuts in new systems is very time-consuming. 

Proposal:
Add a config export option that exports all lock configurations in a file
Add an option that one can run tmux with a config file as an input

Thanks

**Comment by nicm** [comment]
This makes no sense to me, what do you want it to export that you can't get
from list-keys and show-options?

**Comment by qiisziilbash** [comment]
Well, the reason I mentioned exporting option is the second option (config import); otherwise, yes,  list-keys and show-options can export what is necessary for the import.

That's to say, I think it would be helpful to run tmux as following:
tmux -c  config-file.cfg

in which tmux uses the key bindings and configurations defined in config-file.cfg

**Comment by nicm** [comment]
You mean like source-file?

**Comment by qiisziilbash** [comment]
Yes. Thanks. I think it is what I want. 
I close the issue.
