### ISSUE TITLE
`swap-window` command changes the currently seen window

### ISSUE THREAD

**Issue by p1100i** [tmux/tmux#2056]
#### Disclaimer
I've checked the CHANGES and couldn't find any related notes, I haven't added server logs since repro steps are quite straightforward but let me know if you need anything more.

#### Reproduction steps (w/o any specific config):
1. Start a tmux session
2. Open a new window (:new-window)
3. Start a blocking program (e.g top) to see different window titles
4. Swap the two opened window (:swap-window -t -1)

#### Current behavior
The window positions - in window-list - get swapped, however the currently seen window changes, so the user ends up seeing a new window after the swap command (the one which were on the swap target position).

#### Expected behavior
The currently seen window should stay the same, as the one before issuing the swap command.

#### Extra info
1. This is an undocumented change between `2.9a` to `3.0` (and still an issue on `3.0a`, on the master branch - after 3.0a tag - I haven't found any commit related to this)
2. With the current behavior - when having multiple windows open - it is confusing to swap around windows if you like to do it by repeating in such a `+1`, `-1` steps.

#### Environment info
```
# uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 3.0a
screen-256color
```

**Comment by nicm** [comment]
swap-window and swap-window -d have exchanged meanings to match the other commands.

**Comment by p1100i** [comment]
Thanks for the reply @nicm , adding `-d` for the command restores the earlier behavior. Did I miss that in the [CHANGES](https://github.com/tmux/tmux/blob/master/CHANGES)?

**Comment by nicm** [comment]
I thought it was there but it must have been missed.

**Comment by aicioara** [comment]
Thank you @p1100i for flagging this. It fixed my issue as well. I did a search through the CHANGES file as well and could not find the altered behavior.
