### ISSUE TITLE
Tmux + zsh + mc -> how to export TERM

### ISSUE THREAD

**Issue by Jorman** [tmux/tmux#2057]
Hi, I searched a bit and tried some but I don't know how to fix this little problem.

I used to connect to my nas over ssh and by default my console is zsh, so on it I've installed tmux and mc.
The problem occur when I run mc inside tmux, I can't use the mouse correctly. The only way to use the mouse like on normal mc outside tmux is to `export TERM=xterm` and then if I launch mc all works.

How can I set this option by default?
Any idea?

J

**Comment by nicm** [comment]
This seems like a problem with mc, presumably it is only enabling the mouse if TERM is xterm, you will need to ask the mc developers how to enable the mouse when TERM is tmux or screen.

**Comment by lacygoill** [comment]
Try to set the variable via an alias:

    alias mc='TERM=xterm mc'

**Comment by Jorman** [comment]
Thanks both for your reply, I'll try to ask to mc guys in order to ask
