### ISSUE TITLE
How do I run commands in a tmux detached session from a Batch script outside the session?

### ISSUE THREAD

**Issue by Muddz** [tmux/tmux#2058]
I have made a batch script which basically just kills and starts a new Tmux session and then It should starts my webserver app executable when a new version of it is deployed to my Ubuntu server.

But when I run the script it sucessfully kills tmux and starts a new tmux session, but from there it just hang and do nothing more.  

```
#!/bin/bash
tmux kill-session -t MyAppService
tmux new -s MyAppService -d
## [What to prefix here?] cd home/myUser/apps/MyAppProject
## [What to prefix here?] chmod +x MyWebApp
## [What to prefix here?] ./MyWebApp
```

**Comment by nicm** [comment]
send-keys -tMyAppService: abcdef Enter

**Comment by Muddz** [comment]
@nicm is the ENTER to simulate a human interacting with the tmux window session?

**Comment by nicm** [comment]
Sends the Enter key, otherwise the shell won't know when the command ends.
