### ISSUE TITLE
set-hook -g after-kill-pane 'selectl -E' gets ignored

### ISSUE THREAD

**Issue by astier** [tmux/tmux#2060]
### Issue description

I created the following minimal tmux.conf:

```
set-hook -g after-kill-pane 'selectl -E'
```

Setting a hook like in the minimal tmux.conf should execute `select -E` every time the command `killp` gets executed with the effect that every open pane has the same size after killing a pane. However, this hook seems to do nothing.

### Steps to reproduce

1. Create minimal tmux.conf as described above
2. Open tmux
3. Open new pane via `:splitw`
3. Open new split again via `:splitw ; selectl -E`
Notice how every pane has the same size.
4. Kill bottom pane via `:killp`
5. Notice how the two remaining panes don't have the same size although they should have due to the hook in the tmux.conf

### Required information

* tmux 3.0a
* Arch Linux
* $TERM inside `tmux-256color`
* $TERM outside `st-256color`

[tmux-client-152158.log](https://github.com/tmux/tmux/files/4079802/tmux-client-152158.log)
[tmux-out-152160.log](https://github.com/tmux/tmux/files/4079803/tmux-out-152160.log)
[tmux-server-152160.log](https://github.com/tmux/tmux/files/4079805/tmux-server-152160.log)

**Comment by nicm** [comment]
This hook did not work in 3.0a, you will need to use master.
