### ISSUE TITLE
Add usage of start-server command in man page

### ISSUE THREAD

**Issue by yasuhirokimura** [tmux/tmux#2061]
In man page of tmux *start-server* command is explained as following.

>     start-server
>                   (alias: start)
>             Start the tmux server, if not already running, without creating
>             any sessions.

I read it and understood how this command works. But I couldn't imagin how it is expected to be
used. Then I checked source archives of tmux and found following description in *CHANGES*.

> * New command, start-server (alias "start"), to start the tmux server and do
>   nothing else. This is good if you have a configuration file which creates
>   windows or sessions (like me): in that case, starting the server the first
>   time tmux new is run is bad since it creates a new session and window (as
>  it is supposed to - starting the server is a side-effect).
> 
>   Instead, I have a little script which does the equivalent of:
> 
>         tmux has -s0 2>/dev/null || tmux start
>         tmux attach -d -s0
> 
>   And I use it to start the server if necessary and attach to my primary
>   session.

By reading this entry I understood purpose of this command very well. Therefore I think such
explanation of usage should also be added to man page.

**Comment by nicm** [comment]
I have expanded it to say this:
~~~~
     start-server
                   (alias: start)
             Start the tmux server, if not already running, without creating
             any sessions.

             Note that as by default the tmux server will exit with no
             sessions, this is only useful if a session is created in
             ~/.tmux.conf, exit-empty is turned off, or another command is run
             as part of the same command sequence.  For example:

                   $ tmux start \; show -g
