### ISSUE TITLE
Setting variables inside if-shell command sequence causes syntax error

### ISSUE THREAD

**Issue by avielsh** [tmux/tmux#2062]
Hi,
When setting a shell variable inside an if-shell command sequence, I get a syntax error (shell variable is the second component of the command sequence)
I.E:
```if-shell true "display 'test' ; myvar=1" ```
Produces a syntax error

On tmux 2.6 I do not observe this behavior.
 
* tmux version (tmux 3.0a).
* Platform (Darwin i386).
* $TERM inside and outside of tmux (screen-256color).

**Comment by krader1961** [comment]
I don't know why the behavior changed and whether it was intentional or not. But you can rewrite it so it works: `if-shell true "display 'test' ; set-environment -g myvar 1"`

**Comment by avielsh** [comment]
> I don't know why the behavior changed and whether it was intentional or not. But you can rewrite it so it works: `if-shell true "display 'test' ; set-environment -g myvar 1"`

Thanks @krader1961, It does work that way, although I've looked for some indications why it was changed in [Changes](https://raw.githubusercontent.com/tmux/tmux/master/CHANGES) or the manual and couldn't find anything.
Even though this method works, using the shorthand method is more intuitive and getting a syntax error is rather confusing. 
I think it should either be classified as an issue, or mentioned somewhere in the docs...

**Comment by nicm** [comment]
Try this please: 
[x.diff.txt](https://github.com/tmux/tmux/files/4112726/x.diff.txt)

**Comment by avielsh** [comment]
I confirm that the issue is resolved after applying the patch to the 0eb7b54731e35180c7569891379bf3626ed35a02

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
