### ISSUE TITLE
Tmux pane wont resize when opened via script in detached mode

### ISSUE THREAD

**Issue by danielk514** [tmux/tmux#2063]
I open a new session using 
`tmux new-session -s my_session -n my_window -d`
which also uses ssh to log into some-box using password.
`tmux send-keys -t my_session 'ssh some-box' C-m`
`tmux send-keys -t my_session password C-m`

The issue I am having is that my pane will not resize with the attached session. If I used vim or less inside the ssh session to some-box, it will stay 80x24. If I specify an initial size with `-x` and `-y` then it remains that size. If my terminal is smaller, the viewable area behaves strangely. If it is larger, there is unused space in the terminal. 

I would very much like to use tmux scripting to automate my workspace, but it does not seem to work the same. I do not have the same issues if I manually create this session in attached mode and ssh into the box.

I have tried this in both tmux 2.9a and tmux 3.0a
platform: Darwin i386
term: xterm-256color (inside and out)

**Comment by nicm** [comment]
What terminal? How are you resizing? How do you attach?

**Comment by dankasierertmc** [comment]
Apple Terminal (version 2.9.5). I am not resizing, the session just doesnt size correctly to the attached terminal. I use `tmux a -t my_session` to attach.

**Comment by nicm** [comment]
If you are not attaching, what attached terminal do you expect it to resize to?

**Comment by nicm** [comment]
Oh wait you are not reszing not not attaching.

What happens if you do "pkill -WINCH tmux", does it resize?

**Comment by danielk514** [comment]
It doesnt seem to make a difference. I feel like its not an issue with the size of tmux but somehow the size of the ssh session inside of tmux. If I manually ssh into a box with an already attached session, it seems to work fine. I dont know how window sizes work with ssh or how the tmux pane size is communicating to the terminal, but somehow its messed up.

**Comment by nicm** [comment]
Does the tmux status line resize properly?

**Comment by danielk514** [comment]
Yes, that resizes correctly.

**Comment by nicm** [comment]
And if you resize tmux, ssh doesn't resize? What if you send SIGWINCH to the ssh process?

**Comment by dankasierertmc** [comment]
No, it does not resize. I can try that on another computer, but on this one, I get `Operation not permitted`. I tried on both the host mac and the remote linux. These are work computers so I do not have admin rights.

**Comment by nicm** [comment]
You should be able to signal the ssh process you are connecting with on the local machine, if you can't then tmux won't be able to either. Make sure you are using the ssh process not the sshd.

**Comment by danielk514** [comment]
I was trying `pkill -WINCH ssh` which seems to have been trying sshd. I used `ps -ef | grep ssh` to find the specific session and used `pkill -WINCH {pid}` where {pid} is the ssh session. This didnt seem to resize at all. I tried both without being connected to the tmux session as well as splitting the pane and running the command locally while the ssh session was visible.
I shouldnt need to run this on the host that I ssh-ed onto, would I?

**Comment by nicm** [comment]
pkill does not work with PIDs, use kill once you have the PID.

tmux resizes the pty of the local ssh which will get the signal and forward
it to the remote sshd, so try the local ssh first.

**Comment by danielk514** [comment]
Still not being resized. I tried locally with `kill -SIGWINCH {pid}` as well as on the remote host (I could only run it for the pts session since it was the only ssh process my user has permission for)

**Comment by danielk514** [comment]
Back to the main issue. This doesnt happen if I am attached to the session and ssh in manually. It is only if I ssh from a send-keys command to a detched session.

I have created a session with an ssh session inside (from send-keys). I have then attached to this session and split the pane and ssh into the same box while attached. In the top pane (the ssh via send-keys) the connection seems to be sized incorrectly. In the bottom pane (manual ssh while attached) the connection sizing is dynamic as expected.

**Comment by nicm** [comment]
Can you reproduce with tmux built from master?

If so, please see if you can reproduce with a small script like this:
~~~~
rm tmux*.log
tmux -vv -f/dev/null -Ltest new -d 'ssh myhost'
sleep 1
tmux -Ltest send mypassword C-m
tmux attach
~~~~
Then do "stty -a" to confirm ssh has not got the right size, then "C-b : kill-server", then send me the tmux-server*.log file.

If you can't reproduce with this script please modify it to reproduce and send me both the new script and the server log.

**Comment by danielk514** [comment]
I believe in my case, this was an issue with expect rather than with tmux. I simplified my example too far and left out the exact cause of the issue. I have found articles that expect ignores SIGWINCH unless a trap is set specifically. After I have added this trap, I believe the issue is resolved. Thank you for helping me to see that tmux was not at fault here.
