### ISSUE TITLE
Shift mouse events not working

### ISSUE THREAD

**Issue by Ergus** [tmux/tmux#2065]
Hi:
Afted updating tmux to 3.0a the shift+mouse_motion events stopped working. When I try to select a region with Shift+mouse_motion the region is not highlighted during the motion. Whe selected region is highlited only when I free the mouse button at the end.

When I use only xterm it works perfectly, so the problem seems to be that tmux is not sending the shift+motion events to xterm during motion. I am not sure if this a tmux issue or an xterm problem; So I will report also to xterm just in case.

* tmux version (`tmux -V`). tmux 3.0a
* Platform (`uname -sp`). Linux unknown (Arch Linux)
* $TERM inside and outside of tmux (`echo $TERM`).
outside: xterm-256color
inside: tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Using Shift with the mouse in xterm has nothing to do with tmux and in fact bypasses it entirely.

**Comment by Ergus** [comment]
Yes actually there is a bug in xterm that Thomas Dickey (the xterm developer) found already.
