### ISSUE TITLE
Backslash is doubled up in format expansion

### ISSUE THREAD

**Issue by winny-** [tmux/tmux#2070]
### Issue description

When expanding `#{pane_title}` it appears backslashes are doubled. Tested with xterm.

#### tmux.conf

```
set -g set-titles on
set -g set-titles-string "#{pane_title}"
set -g status-right "#{pane_title}"
```

#### Commands tried

```
printf '\033]2;%s\033\\' '\'   # Results in xterm title, status-right text set to "\\"
printf '\e]0;%s\a' '\' # Same as above
```

#### screenshots

![1](https://user-images.githubusercontent.com/3893828/73242065-7fd10e00-4169-11ea-8089-0c1ed3b471fc.png)
![2](https://user-images.githubusercontent.com/3893828/73242069-82cbfe80-4169-11ea-8426-e5fe5d1751ed.png)

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `next-3.1`, `tmux 3.0a`
* Platform (`uname -sp`): `Linux AMD FX(tm)-8350 Eight-Core Processor`
* $TERM inside and outside of tmux (`echo $TERM`).
  - Inside: `screen`
  - Outside: `xterm`
* Logs from tmux (`tmux kill-server; tmux -vv new`). [See this gist](https://gist.github.com/winny-/d34c1c42120befd1fe49765378a1d54b).

**Comment by nicm** [comment]
This is because we pass the title through strvis() before we set it. However, I don't think that is necessary, it is probably enough just to ignore titles containing control characters or invalid UTF-8 instead, and utf8_isvalid() will do that for us. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/4121241/x.diff.txt)

**Comment by winny-** [comment]
Tested 265164d251f427bf9275c355a4f205c781d70b20. It appears to work with backslashes as expected. Thank you for the quick suggestion & response. I regret responding so late, thank you for your patience.

![fixed](https://user-images.githubusercontent.com/3893828/73805766-30a06400-478d-11ea-9dc1-d537e9b457f8.png)

Thanks!

---

Here is information about [ticket # references](https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls) and [closing tickets from commits](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
