### ISSUE TITLE
Unresponsive client when running shell command that communicates with server during launch

### ISSUE THREAD

**Issue by butwerenotthereyet** [tmux/tmux#2073]
### Issue description

On master (6f0241e64522d751ccd19cb70b23e8bf56f306c6), running the following results in a hung client:

```
tmux -f /dev/null -L test new-session \; if-shell '[ $(tmux -l test list-sessions | wc -l) -gt 0 ]' "attach" "new-session"
```

The server can be separately attached to

```
tmux -L test attach
```

and killed.

This used to work without issue, for example, in tmux 3.0a.

**Comment by nicm** [comment]
Can't reproduce. Logs?

**Comment by butwerenotthereyet** [comment]
The problem looks to involve something in the machine's `$PATH`.  The above invocation works without issue off master so long as `export PATH=/bin:/usr/bin` is set first.  That said, from the 3.0a tag, the invocation launches a session without modifying the path.

I'm going to try modifying the path to narrow down the issue.  Logs attached.


[logs.zip](https://github.com/tmux/tmux/files/4151463/logs.zip)

**Comment by butwerenotthereyet** [comment]
The problem looks to be having another version of tmux in the PATH.

**Comment by nicm** [comment]
Do you have an old tmux binary in your PATH? Make sure you are not mixing
3.0a client and master server or vice versa.

**Comment by butwerenotthereyet** [comment]
@nicm Thank you for the explanation!  Removing the old tmux from my path solved the problem.  Sorry for the noise!
