### ISSUE TITLE
installation wiki copy paste error

### ISSUE THREAD

**Issue by jan-glx** [tmux/tmux#2077]
At the end of https://github.com/tmux/tmux/wiki/Installing#building-dependencies

`export PATH=$HOME/local/lib:$LD_LIBRARY_PATH` should probably read 
`export PATH=$HOME/local/lib:$PATH`

**Comment by nicm** [comment]
Fixed now, thanks!

**Comment by jan-glx** [comment]
Wow that was fast! Sorry, too fast: it should read:
`export PATH=$HOME/local/`**`bin`**`:$PATH`

**Comment by nicm** [comment]
oh yeah changed that too
