### ISSUE TITLE
Losing environment on tmux start

### ISSUE THREAD

**Issue by edaustin** [tmux/tmux#2078]
On previous installs on other machines never issues (many machines), however here, when I start a tmux session I lose all access to nvidia/CUDA drivers, and all my previous pip installed software, it seems an entirely new environment is created without any knowledge of my base environment.  This has never been a problem with tmux before as I have never encountered the issue. The machine is a GCP pre-built instance. The new environment cannot see anything, even the base GPU CUDA drivers.

* tmux version (`tmux -V`).
tmux 2.3

* Platform (`uname -sp`).
Linux unknown (actually #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21))

* $TERM inside and outside of tmux (`echo $TERM`).
outside: xterm-256color
inside: screen

* Logs from tmux (`tmux kill-server; tmux -vv new`).
shows nothing (just starts new session)

Many thanks, I am sure I am missing something obvious!

**Comment by nicm** [comment]
I expect you must have started the tmux server from a shell without this
stuff so it didn't get put in the global environment. Restart tmux and make
sure you create the first session from a shell after you have configured
the environment how you want.
