### ISSUE TITLE
Readable output from `tmux list-keys`

### ISSUE THREAD

**Issue by brandondrew** [tmux/tmux#208]
The output of `tmux list-keys` is not (reliably) readable by tmux, even though it looks like it is meant to be.

If it *is* meant to be, then this is a bug report.  If it is *not* meant to be, then this is a feature request.

For a few examples (though there may be others), if anything is bound to `#`, `'`, or `"`, these lines will not be read properly when fed back to tmux in the form of a *.tmux.conf* or the object of a `source-file` command.  The `#` must be escaped to be read, or else it will initiate a comment in the file, while the `'` and `"` must be quoted (double- and single-quoted respectively, of course) or else will be interpreted as beginning a quotation.

It would be very helpful if this could be done automatically when running `list-keys`, perhaps by feeding it an option like `-q` (for "quoted"), or `-e` (for "escaped"), or `-c` (for "configuration file").

**Comment by nicm** [comment]
Yes it would be nice if it escaped quotes, added to TODO file.
