### ISSUE TITLE
tmux server exits immediately

### ISSUE THREAD

**Issue by semchapeu** [tmux/tmux#2081]
I'm trying to run tmux without a terminal. I'm trying to do it like this `tmux new -d -s foobar /bin/sh`, however it seems like the tmux server keeps exiting immediately. When trying to interact with the session I get: "no server running on /tmp/tmux-33/default" and sometimes "server exited unexpectedly" or "lost server". Imagine a webserver (apache2) executes shell commands like this: ` <?php echo passthru($_REQUEST['cmd']); ?>` that's my interface. The idea is that I can simulate an interactive shell through that, getting output with `tmux capturep` and sending input via `tmux send-keys`.

tmux versions 2.6 (Ubuntu 18.04) and 3.0a (Debian Testing)

**Comment by krader1961** [comment]
The trailing `/bin/sh` in your tmux command shouldn't be necessary. Tmux always starts a default shell in a new session. That default shell will usually be the one you want. By specifying `/bin/sh` as the command to run all you are doing is creating a nested shell environment. If you really need to ensure the session is running `/bin/sh` rather than the default shell then, given what you're trying to do, you should instead do `tmux new -d -s foobar 'exec /bin/sh'` or use `tmux send-keys` to ensure the desired shell is running.

The above, however, doesn't really answer your question. To do so requires more information. Which you can provide by running `tmux -vvv new -d -s foobar` and attaching the corresponding tmux server log file to this issue. Assuming, of course, that simply doing that results in the same unexpected behavior; i.e., the tmux server dying rather than continuing to run with a single new session.

**Comment by nicm** [comment]
You need to set the exit-empty option off to allow the tmux server to exist
without any sessions.

**Comment by semchapeu** [comment]
Thanks to both of you I've been able to debug the issue further.
I can now make the server survive by putting `set exit-empty off` in my `.tmux.conf` file, however it is now clear that it's the session that immediately exits. It appears that the issue is that the user in this case (www-data) has `/usr/sbin/nologin` as its login shell. I tried to change the shell by adding `set -g default-command "exec /bin/bash"` into my `.tmux.conf``, however the issue remains. I also tried setting the `SHELL` environment variable to `/bin/sh`, but it still appears as `/usr/sbin/nologin` in the logs.

So the question now is, how do I effectively change the shell here?

When using the www-data user with an actual terminal (`su -l www-data -s /bin/sh`) tmux works fine.

Here's the server log when trying to create a session:

`1581622086.027611 add peer 0x55cd131e5240: 6 (0x55cd131e4960)
1581622086.027662 new client 0x55cd131e4960
1581622086.027672 cmdq_next <global>: empty
1581622086.027947 peer 0x55cd131e5240 message 100
1581622086.027997 client 0x55cd131e4960 IDENTIFY_FLAGS 0
1581622086.028003 peer 0x55cd131e5240 message 101
1581622086.028008 client 0x55cd131e4960 IDENTIFY_TERM 
1581622086.028012 peer 0x55cd131e5240 message 102
1581622086.028017 client 0x55cd131e4960 IDENTIFY_TTYNAME 
1581622086.028021 peer 0x55cd131e5240 message 108
1581622086.028029 client 0x55cd131e4960 IDENTIFY_CWD /tmp
1581622086.028034 peer 0x55cd131e5240 message 104
1581622086.028039 client 0x55cd131e4960 IDENTIFY_STDIN 8
1581622086.028044 cmdq_next <global>: empty
1581622086.028076 peer 0x55cd131e5240 message 107
1581622086.028103 client 0x55cd131e4960 IDENTIFY_CLIENTPID 25086
1581622086.028109 peer 0x55cd131e5240 message 105
1581622086.028114 client 0x55cd131e4960 IDENTIFY_ENVIRON PWD=/tmp
1581622086.028118 peer 0x55cd131e5240 message 105
1581622086.028123 client 0x55cd131e4960 IDENTIFY_ENVIRON HOME=/tmp
1581622086.028127 peer 0x55cd131e5240 message 105
1581622086.028132 client 0x55cd131e4960 IDENTIFY_ENVIRON APACHE_LOG_DIR=/var/log/apache2
1581622086.028137 peer 0x55cd131e5240 message 105
1581622086.028142 client 0x55cd131e4960 IDENTIFY_ENVIRON LANG=C
1581622086.028146 peer 0x55cd131e5240 message 105
1581622086.028151 client 0x55cd131e4960 IDENTIFY_ENVIRON INVOCATION_ID=be26c653514d4e8fbc4fdc417c3f5872
1581622086.028156 peer 0x55cd131e5240 message 105
1581622086.028161 client 0x55cd131e4960 IDENTIFY_ENVIRON APACHE_PID_FILE=/var/run/apache2/apache2.pid
1581622086.028166 peer 0x55cd131e5240 message 105
1581622086.028171 client 0x55cd131e4960 IDENTIFY_ENVIRON APACHE_RUN_GROUP=www-data
1581622086.028175 peer 0x55cd131e5240 message 105
1581622086.028181 client 0x55cd131e4960 IDENTIFY_ENVIRON APACHE_LOCK_DIR=/var/lock/apache2
1581622086.028185 peer 0x55cd131e5240 message 105
1581622086.028190 client 0x55cd131e4960 IDENTIFY_ENVIRON SHLVL=1
1581622086.028195 peer 0x55cd131e5240 message 105
1581622086.028200 client 0x55cd131e4960 IDENTIFY_ENVIRON APACHE_RUN_DIR=/var/run/apache2
1581622086.028205 peer 0x55cd131e5240 message 105
1581622086.028210 client 0x55cd131e4960 IDENTIFY_ENVIRON JOURNAL_STREAM=9:142938
1581622086.028215 peer 0x55cd131e5240 message 105
1581622086.028220 client 0x55cd131e4960 IDENTIFY_ENVIRON APACHE_RUN_USER=www-data
1581622086.028235 peer 0x55cd131e5240 message 105
1581622086.028242 client 0x55cd131e4960 IDENTIFY_ENVIRON PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
1581622086.028246 peer 0x55cd131e5240 message 105
1581622086.028251 client 0x55cd131e4960 IDENTIFY_ENVIRON OLDPWD=/var/www/html
1581622086.028259 peer 0x55cd131e5240 message 105
1581622086.028264 client 0x55cd131e4960 IDENTIFY_ENVIRON _=/usr/bin/tmux
1581622086.028268 peer 0x55cd131e5240 message 106
1581622086.028272 client 0x55cd131e4960 name is client-25086
1581622086.028278 peer 0x55cd131e5240 message 200
1581622086.028284 cmd_unpack_argv: argv[0]=new
1581622086.028288 cmd_unpack_argv: argv[1]=-d
1581622086.028292 cmd_unpack_argv: argv[2]=-s
1581622086.028296 cmd_unpack_argv: argv[3]=foobar
1581622086.028300 cmd_parse_from_arguments: argv[0]=new
1581622086.028304 cmd_parse_from_arguments: argv[1]=-d
1581622086.028308 cmd_parse_from_arguments: argv[2]=-s
1581622086.028312 cmd_parse_from_arguments: argv[3]=foobar
1581622086.028317 cmd_parse_from_arguments: at 0: argv[0]=new
1581622086.028321 cmd_parse_from_arguments: at 0: argv[1]=-d
1581622086.028325 cmd_parse_from_arguments: at 0: argv[2]=-s
1581622086.028329 cmd_parse_from_arguments: at 0: argv[3]=foobar
1581622086.028334 cmd_parse_build_commands: 0 new
1581622086.028339 cmd_parse_build_commands: argv[0]=-d
1581622086.028343 cmd_parse_build_commands: argv[1]=-s
1581622086.028347 cmd_parse_build_commands: argv[2]=foobar
1581622086.028353 cmd_parse: new-session: argv[0]=new
1581622086.028357 cmd_parse: new-session: argv[1]=-d
1581622086.028361 cmd_parse: new-session: argv[2]=-s
1581622086.028365 cmd_parse: new-session: argv[3]=foobar
1581622086.028373 cmd_parse_build_commands: new-session -d -s foobar
1581622086.028379 cmdq_get_command: [new-session/0x55cd131da210] group 1459
1581622086.028384 cmdq_append <client-25086>: [new-session/0x55cd131da210]
1581622086.028389 cmdq_append <client-25086>: [server_client_command_done/0x55cd131ca3a0]
1581622086.028394 cmdq_next <global>: empty
1581622086.028398 cmdq_next <client-25086>: enter
1581622086.028403 cmdq_next <client-25086>: [new-session/0x55cd131da210] (0), flags 0
1581622086.028409 cmdq_fire_command <client-25086>: (1459) new-session -d -s foobar
1581622086.028414 cmd_find_target: target none, type session, item 0x55cd131da210, flags QUIET,CANFAIL
1581622086.028419 cmd_find_best_session: 0 sessions to try
1581622086.028424 cmd_find_target: error
1581622086.028432 format_defaults: c=client-25086
1581622086.028437 format_defaults: s=none
1581622086.028440 format_defaults: wl=none
1581622086.028444 format_defaults: wp=none
1581622086.028455 format_expand1: expanding format: foobar
1581622086.028461 format_expand1: result is: foobar
1581622086.028468 unref client 0x55cd131e4960 (4 references)
1581622086.028479 new session foobar $1
1581622086.028485 session $1 foobar activity 1581622086.028483 (last 0.000000)
1581622086.028490 spawn_window: [new-session/0x55cd131da210], flags=0
1581622086.028494 spawn_window: s=$1 wl=none wp0=none idx=-1
1581622086.028498 spawn_window: name=none
1581622086.028508 @1 alerts timer reset 0
1581622086.028514 @1 alerts flags added 0x2
1581622086.028519 window_add_ref: @1 winlink_set_window, now 1
1581622086.028523 spawn_pane: [new-session/0x55cd131da210], flags=0x10
1581622086.028527 spawn_pane: s=$1 wl=0 wp0=none idx=-1
1581622086.028531 spawn_pane: name=none
1581622086.028540 window_add_pane: @1 at start
1581622086.028557 spawn_pane: shell=/usr/sbin/nologin
1581622086.028566 spawn_pane: cmd=exec /bin/bash
1581622086.028570 spawn_pane: cwd=/tmp
1581622086.028574 spawn_pane: argv[0]=exec /bin/bash
1581622086.028578 spawn_pane: environment APACHE_LOCK_DIR=/var/lock/apache2
1581622086.028583 spawn_pane: environment APACHE_LOG_DIR=/var/log/apache2
1581622086.028587 spawn_pane: environment APACHE_PID_FILE=/var/run/apache2/apache2.pid
1581622086.028591 spawn_pane: environment APACHE_RUN_DIR=/var/run/apache2
1581622086.028595 spawn_pane: environment APACHE_RUN_GROUP=www-data
1581622086.028599 spawn_pane: environment APACHE_RUN_USER=www-data
1581622086.028607 spawn_pane: environment HOME=/tmp
1581622086.028611 spawn_pane: environment INVOCATION_ID=be26c653514d4e8fbc4fdc417c3f5872
1581622086.028615 spawn_pane: environment JOURNAL_STREAM=9:142938
1581622086.028635 spawn_pane: environment LANG=C
1581622086.028649 spawn_pane: environment OLDPWD=/var/www/html
1581622086.028655 spawn_pane: environment PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
1581622086.028660 spawn_pane: environment PWD=/tmp
1581622086.028664 spawn_pane: environment SHELL=/usr/sbin/nologin
1581622086.028668 spawn_pane: environment SHLVL=1
1581622086.028672 spawn_pane: environment TERM=screen
1581622086.028676 spawn_pane: environment TMUX=/tmp/tmux-33/default,25072,1
1581622086.028680 spawn_pane: environment TMUX_PANE=%1
1581622086.028684 spawn_pane: environment _=/usr/bin/tmux
1581622086.028950 window_set_active_pane: pane %1
1581622086.029025 cmd_find_best_winlink_with_window: window is @1
1581622086.029040 cmd_find_from_session_window: s=$1 foobar
1581622086.029054 cmd_find_from_session_window: wl=0 1 w=@1 bash
1581622086.029065 cmd_find_from_session_window: wp=%1
1581622086.029081 cmd_find_from_session_window: idx=0
1581622086.029107 session_add_ref: foobar notify_add, now 2
1581622086.029116 window_add_ref: @1 notify_add, now 2
1581622086.029123 session_add_ref: foobar notify_add, now 3
1581622086.029150 cmdq_append <global>: [notify_callback/0x55cd131d73a0]
1581622086.029165 cmd_find_from_session: s=$1 foobar
1581622086.029173 cmd_find_from_session: wl=0 1 w=@1 bash
1581622086.029180 cmd_find_from_session: wp=%1
1581622086.029186 cmd_find_from_session: idx=none
1581622086.029200 session_add_ref: foobar notify_add, now 4
1581622086.029210 session_add_ref: foobar notify_add, now 5
1581622086.029221 cmdq_append <global>: [notify_callback/0x55cd131cb240]
1581622086.029229 recalculate_sizes: @1 is 80,24
1581622086.029237 cmd_find_from_session: s=$1 foobar
1581622086.029246 cmd_find_from_session: wl=0 1 w=@1 bash
1581622086.029253 cmd_find_from_session: wp=%1
1581622086.029259 cmd_find_from_session: idx=none
1581622086.029274 running hook after-new-session (parent 0x55cd131da210)
1581622086.029296 unref client 0x55cd131e4960 (3 references)
1581622086.029322 cmdq_next <client-25086>: [server_client_command_done/0x55cd131ca3a0] (1), flags 0
1581622086.029335 unref client 0x55cd131e4960 (2 references)
1581622086.029343 cmdq_next <client-25086>: exit (empty)
1581622086.029349 cmdq_next <global>: enter
1581622086.029362 cmdq_next <global>: [notify_callback/0x55cd131d73a0] (1), flags 0
1581622086.029371 notify_callback: window-linked
1581622086.029379 notify_insert_hook: window-linked
1581622086.029389 session_remove_ref: foobar notify_callback, now 4
1581622086.029398 window_remove_ref: @1 notify_callback, now 1
1581622086.029406 session_remove_ref: foobar notify_callback, now 3
1581622086.029413 cmdq_next <global>: [notify_callback/0x55cd131cb240] (1), flags 0
1581622086.029420 notify_callback: session-created
1581622086.029427 notify_insert_hook: session-created
1581622086.029434 session_remove_ref: foobar notify_callback, now 2
1581622086.029441 session_remove_ref: foobar notify_callback, now 1
1581622086.029448 cmdq_next <global>: exit (empty)
1581622086.029455 cmdq_next <client-25086>: empty
1581622086.029462 cmdq_next <global>: empty
1581622086.029468 cmdq_next <client-25086>: empty
1581622086.029476 sending message 203 to peer 0x55cd131e5240 (4 bytes)
1581622086.029490 @1 active pane changed
1581622086.029595 format_expand1: expanding format: #{?pane_in_mode,[tmux],#{pane_current_command}}#{?pane_dead,[dead],}
1581622086.029648 format_expand1: found #{}: ?pane_in_mode,[tmux],#{pane_current_command}
1581622086.029662 format_replace: condition is: pane_in_mode
1581622086.029677 format_replace: condition 'pane_in_mode' found
1581622086.029686 format_replace: condition 'pane_in_mode' is false
1581622086.029697 format_expand1: expanding format: #{pane_current_command}
1581622086.029707 format_expand1: found #{}: pane_current_command
1581622086.029750 format_replace: format 'pane_current_command' found: nologin
1581622086.029786 format_replace: replaced 'pane_current_command' with 'nologin'
1581622086.029797 format_expand1: result is: nologin
1581622086.029805 format_replace: replaced '?pane_in_mode,[tmux],#{pane_current_command}' with 'nologin'
1581622086.029815 format_expand1: found #{}: ?pane_dead,[dead],
1581622086.029824 format_replace: condition is: pane_dead
1581622086.029833 format_replace: condition 'pane_dead' found
1581622086.029840 format_replace: condition 'pane_dead' is false
1581622086.029849 format_replace: replaced '?pane_dead,[dead],' with ''
1581622086.029856 format_expand1: result is: nologin
1581622086.029872 @1 new name nologin (was bash)
1581622086.029884 cmd_find_best_session_with_window: window is @1
1581622086.029891 cmd_find_best_session: 1 sessions to try
1581622086.029898 cmd_find_best_winlink_with_window: window is @1
1581622086.029905 cmd_find_best_winlink_with_window: window is @1
1581622086.029911 cmd_find_from_window: s=$1 foobar
1581622086.029921 cmd_find_from_window: wl=0 1 w=@1 nologin
1581622086.029928 cmd_find_from_window: wp=%1
1581622086.029934 cmd_find_from_window: idx=0
1581622086.029941 window_add_ref: @1 notify_add, now 2
1581622086.029948 session_add_ref: foobar notify_add, now 2
1581622086.029956 cmdq_append <global>: [notify_callback/0x55cd131ca3a0]
1581622086.029984 cmdq_next <global>: enter
1581622086.029998 cmdq_next <global>: [notify_callback/0x55cd131ca3a0] (1), flags 0
1581622086.030005 notify_callback: window-renamed
1581622086.030013 notify_insert_hook: window-renamed
1581622086.030021 window_remove_ref: @1 notify_callback, now 1
1581622086.030028 session_remove_ref: foobar notify_callback, now 1
1581622086.030035 cmdq_next <global>: exit (empty)
1581622086.030042 cmdq_next <client-25086>: empty
1581622086.030049 cmdq_next <global>: empty
1581622086.030056 cmdq_next <client-25086>: empty
1581622086.030063 @1 active pane not changed
1581622086.030245 %1 has 42 bytes
1581622086.030283 @1 alerts timer reset 0
1581622086.030294 screen_write_start: size 80x24, pane %1 (at 0,0)
1581622086.030302 input_parse_buffer: %1 ground, 42 bytes: This account is currently not available.\r\n
1581622086.030311 screen_write_collect_end: 40 This account is currently not available. (at 0,0)
1581622086.030320 input_c0_dispatch: '\r'
1581622086.030326 input_c0_dispatch: '\n'
1581622086.030333 screen_write_linefeed: at 0,0 (region 0-23)
1581622086.030340 screen_write_collect_flush: flushed 1 items (40 bytes)
1581622086.030347 screen_write_stop: 40 cells (40 written, 0 skipped)
1581622086.030355 cmdq_next <global>: empty
1581622086.030361 cmdq_next <client-25086>: empty
1581622086.030367 @1 active pane changed
1581622086.030373 @1 name timer queued (499128 left)
1581622086.030431 %1 error
1581622086.031869 cmd_find_best_session_with_window: window is @1
1581622086.031937 cmd_find_best_session: 1 sessions to try
1581622086.031949 cmd_find_best_winlink_with_window: window is @1
1581622086.031957 cmd_find_best_winlink_with_window: window is @1
1581622086.031968 cmd_find_from_window: s=$1 foobar
1581622086.031976 cmd_find_from_window: wl=0 1 w=@1 nologin
1581622086.031986 cmd_find_from_window: wp=%1
1581622086.031993 cmd_find_from_window: idx=0
1581622086.032001 cmd_find_from_pane: s=$1 foobar
1581622086.032010 cmd_find_from_pane: wl=0 1 w=@1 nologin
1581622086.032016 cmd_find_from_pane: wp=%1
1581622086.032021 cmd_find_from_pane: idx=0
1581622086.032032 session_add_ref: foobar notify_add, now 2
1581622086.032044 cmdq_append <global>: [notify_callback/0x55cd131ca3a0]
1581622086.032064 cmd_find_best_session_with_window: window is @1
1581622086.032074 cmd_find_best_session: 1 sessions to try
1581622086.032081 cmd_find_best_winlink_with_window: window is @1
1581622086.032087 cmd_find_best_winlink_with_window: window is @1
1581622086.032093 cmd_find_from_window: s=$1 foobar
1581622086.032099 cmd_find_from_window: wl=0 1 w=@1 nologin
1581622086.032105 cmd_find_from_window: wp=%1
1581622086.032110 cmd_find_from_window: idx=0
1581622086.032120 window_add_ref: @1 notify_add, now 2
1581622086.032138 session_add_ref: foobar notify_add, now 3
1581622086.032148 cmdq_append <global>: [notify_callback/0x55cd131c4d60]
1581622086.032157 window_lost_pane: @1 pane %1
1581622086.032194 cmd_find_best_winlink_with_window: window is @1
1581622086.032218 cmd_find_from_session_window: s=$1 foobar
1581622086.032226 cmd_find_from_session_window: wl=0 1 w=@1 nologin
1581622086.032232 cmd_find_from_session_window: wp=none
1581622086.032241 cmd_find_from_session_window: idx=0
1581622086.032251 session_add_ref: foobar notify_add, now 4
1581622086.032257 window_add_ref: @1 notify_add, now 3
1581622086.032263 session_add_ref: foobar notify_add, now 5
1581622086.032274 cmdq_append <global>: [notify_callback/0x55cd131c7650]
1581622086.032281 window_remove_ref: @1 winlink_remove, now 2
1581622086.032287 session foobar destroyed (session_detach)
1581622086.032296 cmd_find_best_session: 0 sessions to try
1581622086.032305 session_add_ref: foobar notify_add, now 6
1581622086.032312 cmdq_append <global>: [notify_callback/0x55cd131cbb20]
1581622086.032321 session_remove_ref: foobar session_destroy, now 5
1581622086.032339 server_signal: Child exited
1581622086.032396 cmdq_next <global>: enter
1581622086.032424 cmdq_next <global>: [notify_callback/0x55cd131ca3a0] (1), flags 0
1581622086.032435 notify_callback: pane-exited
1581622086.032443 notify_insert_hook: pane-exited
1581622086.032455 cmd_find_best_session: 0 sessions to try
1581622086.032463 session_remove_ref: foobar notify_callback, now 4
1581622086.032470 cmdq_next <global>: [notify_callback/0x55cd131c4d60] (1), flags 0
1581622086.032477 notify_callback: window-layout-changed
1581622086.032484 notify_insert_hook: window-layout-changed
1581622086.032492 cmd_find_best_session: 0 sessions to try
1581622086.032501 window_remove_ref: @1 notify_callback, now 1
1581622086.032507 session_remove_ref: foobar notify_callback, now 3
1581622086.032515 cmdq_next <global>: [notify_callback/0x55cd131c7650] (1), flags 0
1581622086.032523 notify_callback: window-unlinked
1581622086.032529 notify_insert_hook: window-unlinked
1581622086.032535 cmd_find_best_session: 0 sessions to try
1581622086.032541 session_remove_ref: foobar notify_callback, now 2
1581622086.032548 window_remove_ref: @1 notify_callback, now 0
1581622086.032555 window @1 destroyed (0 references)
1581622086.032562 session_remove_ref: foobar notify_callback, now 1
1581622086.032569 cmdq_next <global>: [notify_callback/0x55cd131cbb20] (1), flags 0
1581622086.032575 notify_callback: session-closed
1581622086.032582 notify_insert_hook: session-closed
1581622086.032589 cmd_find_best_session: 0 sessions to try
1581622086.032595 session_remove_ref: foobar notify_callback, now 0
1581622086.032603 cmdq_next <global>: exit (empty)
1581622086.032610 cmdq_next <client-25086>: empty
1581622086.032633 cmdq_next <global>: empty
1581622086.032641 cmdq_next <client-25086>: empty
1581622086.032655 session foobar freed (0 references)
1581622086.032746 lost client 0x55cd131e4960
1581622086.032782 remove peer 0x55cd131e5240
1581622086.032801 unref client 0x55cd131e4960 (1 references)
1581622086.032810 free client 0x55cd131e4960 (0 references)
1581622086.032815 cmdq_next <global>: empty
`

**Comment by krader1961** [comment]
Have you tried `set -g default-shell /bin/sh`?

**Comment by semchapeu** [comment]
@krader1961 Thank you so much! This worked!
