### ISSUE TITLE
Pane selection issues with pane-border-status enabled

### ISSUE THREAD

**Issue by stanspas** [tmux/tmux#2082]
### Issue description

I have enabled a status bar for each of my panes like this:

```
set -g pane-border-status top
set -g pane-border-format "#{pane_index} #{pane_current_command}"
```

When I split a tmux window vertically in two like this (`!` denotes the screen's border, as opposed to a 
character printed on the terminal):
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!──0 bash──────────────────────!
!user@host:~$                  !
!──1 bash──────────────────────!
!user@host:~$                  !
![session] 0:bash        status!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Then, `select-pane -t {bottom}` correctly selects the bottom pane.
However, `select-pane -t {top}` does nothing and outputs:
```
Can't find pane: top
```

If I disable the `pane-border-status`, then everything works correctly, and I am able to select either pane using the `top`/`bottom` mnemonics.

### Root cause

I instrumented `window_find_string`  and `window_get_active_at` in ` window.c` with some debug output. It looks like the top pane is considered to begin at `yoff=1`, rather than `yoff=0` (due to the extra status-border line). However, `window_find_string` does not account for that, and ends up invoking `window_get_active_at(w, x, y)` with `y=0`.

As a result, the top pane no longer matches and instead gets incorrectly skipped due to below `if`-condition being true (`(y=0) < (wp->yoff=1)`):

```
                if (y < wp->yoff || y > wp->yoff + wp->sy) {
                        continue;
                } 
```

### Required information

* tmux version (`tmux -V`): `tmux next-3.2` (built from commit [`6c28d0dd06`](https://github.com/tmux/tmux/commit/6c28d0dd064da5b4f50814df30df95d76025b9df))
* Platform (`uname -sp`): `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color`, outside: `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): *Nothing relevant to show here.*

**Comment by nicm** [comment]
Yes... try this please: [tmux-top-bottom.diff.txt](https://github.com/tmux/tmux/files/4204485/tmux-top-bottom.diff.txt)

**Comment by stanspas** [comment]
I tested the provided patch, and can confirm that it solves the issue. Thank you!

**Comment by nicm** [comment]
Applied now, thanks!
