### ISSUE TITLE
Feature request: native sessions tunnelled over a remote connection?

### ISSUE THREAD

**Issue by jkp** [tmux/tmux#2084]
### Issue description

I'm not sure how you deal with feature requests but I wanted to ask if you had considered adding the kind of functionality outlined by the poster [here](https://superuser.com/questions/878890/attach-a-tmux-session-to-a-remote-machine?noredirect=1&lq=1). They phrased it better than I could so I'll repost here.  Thoughts?

----

I am using tmux on my local machine and usually have several sessions simultaneously.

What I usually do is I have a session with different windows to work locally and the other sessions in which I connect several windows to one host per session.

A session / window tree would look like this in the daily use I make of tmux:

    (TMUX on my local machine)
     |
     +- session 1: local
     |  \_ window 1: local shell
     |  \_ window 2: local shell
     |  \_ ...
     |
     + session 2: somehost
     |  \_ window1: ssh user@somehost
     |  \_ window2: ssh user@somehost
     |  \_ ...
     |
     + session 3: someotherhost
        \_ window1: ssh user@someotherhost
        \_ window2: ssh user@someotherhost
        \_ ...

Is there a way to make session 2 & session 3 some sort of remote sessions connecting to a tmux session created on somehost & someotherhost?

The above tree would look like this:

    (TMUX on my local machine)
     |
     +- session 1: local
     |  \_ window 1: local shell
     |  \_ window 2: local shell
     |  \_ ...
     |
     + session 2 linked to an existing session on somehost
     |  \_ window1: shell on somehost
     |  \_ window2: shell on somehost
     |  \_ ...
     |
     + session 3 linked to an existing session on someotherhost
        \_ window1: shell on someotherhost
        \_ window2: shell on someotherhost
        \_ ...

I found this topic but I am not sure this is what I want to do: [Is sharing a tmux sockets between hosts possible?](https://superuser.com/questions/358943/is-sharing-a-tmux-sockets-between-hosts-possible)

I suppose what I am looking for would require me to have the same tmux configuration on my local machine, somehost & someotherhost but that would not be a problem.

**Comment by nicm** [comment]
This has come up several times, most notably https://github.com/tmux/tmux/issues/1643 and https://github.com/tmux/tmux/issues/204. A reasonable implementation would be to support what you suggest - adding remote sessions is somewhere in complexity between panes (not hard but useless) and full integration of the remote server state (a lot of work).

There is also https://github.com/tmate-io/tmate but I'm not really sure exactly what it does and nobody has ever approached me about integrating it with tmux.

**Comment by jkp** [comment]
Not surprised it has been asked before. I recently went through the journey of figuring out how to run nested tmux sessions, which is a workable solution but not as neat as it could be.  I run the remote sessions inside an [enternal termina](http://eternalterminal.dev) connection (mosh is another option) so that they stay seamlessly connected when my machine wakes up from sleep. This works nicely but again, it would be amazing to see tmux extended to support this natively.

**Comment by nicm** [comment]
It is possible to script things to make using nested tmux more comfortable, for example: swapping the prefix key when in a pane with a remote tmux so you don't have to press it twice, or hiding the status line. How much this is worth it depends on how much you use nested tmux.
