### ISSUE TITLE
tmux split line jumping after install oh-my-bash please help

### ISSUE THREAD

**Issue by jaden0747** [tmux/tmux#2085]
**Issue description**
tmux split line weird behaviour after installing oh-my-bash and gnome themes: 

- Oh My Bash: https://github.com/ohmybash/oh-my-bash

- High Ubunterra https://www.gnome-look.org/p/1207015/ and 

- XONE Catalina Night: https://www.gnome-look.org/p/1215571/

- MacOS icon theme: https://www.gnome-look.org/p/1334878/

![image](https://user-images.githubusercontent.com/45776059/74809362-9c530700-531f-11ea-9d40-71c91e95813c.png)

![image](https://user-images.githubusercontent.com/45776059/74809402-ad9c1380-531f-11ea-8de5-6a2b8ceca58f.png)

**Required information**
uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.6
xterm-256color

~/.tmux.conf:
//remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

//split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

//reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

//switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

//Enable mouse mode (tmux 2.1 and above)
set -g mouse on

log client: https://www.dropbox.com/s/y3ncorjpkka27oz/tmux-client-27380.log?dl=0
log out: https://www.dropbox.com/s/r1dkv6bkfq5ifgh/tmux-out-27382.log?dl=0
log server: https://www.dropbox.com/s/usf0dy3u9ld4utb/tmux-server-27382.log?dl=0

**Comment by nicm** [comment]
tmux 2.6 was released three years ago. Does this still happen with 3.0, 3.1-rc or master?

**Comment by jaden0747** [comment]
the issue still there with 3.0, I haven't tested with 3.1/master yet.

**Comment by nicm** [comment]
Can you show me the log from 3.0 please? Please add it to the issue instead of using an upload site, when I try to download your links all I get is a load of HTML.

**Comment by nicm** [comment]
Just the server log is enough.

**Comment by jaden0747** [comment]
Hi, the log file is exceed the limit of the comment so please try this google drive link https://drive.google.com/file/d/19MLOLzMmh_6MdKiydsZcPUoaVk54njM2/view?usp=sharing

And here is a snapshot :

1582098738.691449 server started (5432): version 3.0a, socket /tmp/tmux-1000/default, protocol 8
1582098738.691516 on Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020; libevent 2.1.8-stable (poll)
1582098738.691631 yylex_token: bind
1582098738.691645 yylex_token: C-b
1582098738.691656 yylex_token: send-prefix
1582098738.691685 cmd_parse_build_commands: 0 bind
1582098738.691695 cmd_parse_build_commands: argv[0]=C-b
1582098738.691704 cmd_parse_build_commands: argv[1]=send-prefix
1582098738.691719 cmd_parse: bind-key: argv[0]=bind
1582098738.691727 cmd_parse: bind-key: argv[1]=C-b
1582098738.691735 cmd_parse: bind-key: argv[2]=send-prefix
1582098738.691753 cmd_parse_build_commands: bind-key C-b send-prefix
1582098738.691766 cmdq_get_command: [bind-key/0x561727093650] group 5
1582098738.691776 cmdq_append <global>: [bind-key/0x561727093650]
1582098738.691786 yylex_token: bind
1582098738.691795 yylex_token: C-o
1582098738.691804 yylex_token: rotate-window
1582098738.691816 cmd_parse_build_commands: 0 bind
1582098738.691825 cmd_parse_build_commands: argv[0]=C-o
1582098738.691833 cmd_parse_build_commands: argv[1]=rotate-window
1582098738.691842 cmd_parse: bind-key: argv[0]=bind
1582098738.691851 cmd_parse: bind-key: argv[1]=C-o
1582098738.691859 cmd_parse: bind-key: argv[2]=rotate-window
1582098738.691873 cmd_parse_build_commands: bind-key C-o rotate-window
1582098738.691884 cmdq_get_command: [bind-key/0x561727093f30] group 8
1582098738.691892 cmdq_append <global>: [bind-key/0x561727093f30]
1582098738.691907 yylex_token: bind
1582098738.691916 yylex_token: C-z
1582098738.691926 yylex_token: suspend-client
1582098738.691936 cmd_parse_build_commands: 0 bind
1582098738.691944 cmd_parse_build_commands: argv[0]=C-z
1582098738.691953 cmd_parse_build_commands: argv[1]=suspend-client
1582098738.691962 cmd_parse: bind-key: argv[0]=bind
1582098738.691970 cmd_parse: bind-key: argv[1]=C-z
1582098738.691978 cmd_parse: bind-key: argv[2]=suspend-client
1582098738.691992 cmd_parse_build_commands: bind-key C-z suspend-client
1582098738.692003 cmdq_get_command: [bind-key/0x5617270946e0] group 11
1582098738.692012 cmdq_append <global>: [bind-key/0x5617270946e0]
1582098738.692021 yylex_token: bind
1582098738.692029 yylex_token: Space
1582098738.692038 yylex_token: next-layout
1582098738.692048 cmd_parse_build_commands: 0 bind
1582098738.692057 cmd_parse_build_commands: argv[0]=Space
1582098738.692065 cmd_parse_build_commands: argv[1]=next-layout
1582098738.692074 cmd_parse: bind-key: argv[0]=bind
1582098738.692083 cmd_parse: bind-key: argv[1]=Space
1582098738.692091 cmd_parse: bind-key: argv[2]=next-layout
1582098738.692105 cmd_parse_build_commands: bind-key Space next-layout
1582098738.692116 cmdq_get_command: [bind-key/0x561727094dc0] group 14
1582098738.692124 cmdq_append <global>: [bind-key/0x561727094dc0]
1582098738.692134 yylex_token: bind
1582098738.692142 yylex_token: !
1582098738.692152 yylex_token: break-pane
1582098738.692162 cmd_parse_build_commands: 0 bind
1582098738.692170 cmd_parse_build_commands: argv[0]=!
1582098738.692179 cmd_parse_build_commands: argv[1]=break-pane
1582098738.692188 cmd_parse: bind-key: argv[0]=bind
1582098738.692196 cmd_parse: bind-key: argv[1]=!
1582098738.692204 cmd_parse: bind-key: argv[2]=break-pane
1582098738.692218 cmd_parse_build_commands: bind-key ! break-pane
1582098738.692228 cmdq_get_command: [bind-key/0x5617270952a0] group 17
1582098738.692236 cmdq_append <global>: [bind-key/0x5617270952a0]
1582098738.692250 yylex_token: bind
1582098738.692259 yylex_token: "
1582098738.692268 yylex_token: split-window
1582098738.692278 cmd_parse_build_commands: 0 bind
1582098738.692286 cmd_parse_build_commands: argv[0]="
1582098738.692295 cmd_parse_build_commands: argv[1]=split-window
1582098738.692304 cmd_parse: bind-key: argv[0]=bind
1582098738.692312 cmd_parse: bind-key: argv[1]="
1582098738.692320 cmd_parse: bind-key: argv[2]=split-window
1582098738.692334 cmd_parse_build_commands: bind-key \\" split-window
1582098738.692344 cmdq_get_command: [bind-key/0x561727095700] group 20
1582098738.692353 cmdq_append <global>: [bind-key/0x561727095700]
1582098738.692374 yylex_token: bind
1582098738.692383 yylex_token: #
1582098738.692392 yylex_token: list-buffers
1582098738.692402 cmd_parse_build_commands: 0 bind
1582098738.692411 cmd_parse_build_commands: argv[0]=#
1582098738.692420 cmd_parse_build_commands: argv[1]=list-buffers
1582098738.692429 cmd_parse: bind-key: argv[0]=bind
1582098738.692437 cmd_parse: bind-key: argv[1]=#
1582098738.692446 cmd_parse: bind-key: argv[2]=list-buffers
1582098738.692459 cmd_parse_build_commands: bind-key \\# list-buffers
1582098738.692469 cmdq_get_command: [bind-key/0x561727095a00] group 23
1582098738.692478 cmdq_append <global>: [bind-key/0x561727095a00]
1582098738.692487 yylex_token: bind
1582098738.692496 yylex_token: $
1582098738.692505 yylex_token: command-prompt
1582098738.692514 yylex_token: -I#S
1582098738.692525 yylex_token: rename-session -- '%%'
1582098738.692536 cmd_parse_build_commands: 0 bind
1582098738.692544 cmd_parse_build_commands: argv[0]=$
1582098738.692553 cmd_parse_build_commands: argv[1]=command-prompt
1582098738.692561 cmd_parse_build_commands: argv[2]=-I#S
1582098738.692570 cmd_parse_build_commands: argv[3]=rename-session -- '%%'
1582098738.692579 cmd_parse: bind-key: argv[0]=bind
1582098738.692587 cmd_parse: bind-key: argv[1]=$
1582098738.692596 cmd_parse: bind-key: argv[2]=command-prompt
1582098738.692604 cmd_parse: bind-key: argv[3]=-I#S
1582098738.692612 cmd_parse: bind-key: argv[4]=rename-session -- '%%'
1582098738.692639 cmd_parse_build_commands: bind-key \\$ command-prompt "-I#S" "rename-session -- '%%'"
1582098738.692650 cmdq_get_command: [bind-key/0x5617270960d0] group 26
1582098738.692659 cmdq_append <global>: [bind-key/0x5617270960d0]
1582098738.692669 yylex_token: bind
1582098738.692678 yylex_get_word: %
1582098738.692687 yylex_token: split-window
1582098738.692696 yylex_token: -h
1582098738.692706 cmd_parse_build_commands: 0 bind
1582098738.692715 cmd_parse_build_commands: argv[0]=%
1582098738.692723 cmd_parse_build_commands: argv[1]=split-window
1582098738.692732 cmd_parse_build_commands: argv[2]=-h
1582098738.692741 cmd_parse: bind-key: argv[0]=bind
1582098738.692749 cmd_parse: bind-key: argv[1]=%
1582098738.692757 cmd_parse: bind-key: argv[2]=split-window
1582098738.692765 cmd_parse: bind-key: argv[3]=-h
1582098738.692781 cmd_parse_build_commands: bind-key % split-window -h
1582098738.692791 cmdq_get_command: [bind-key/0x561727096320] group 29
1582098738.692800 cmdq_append <global>: [bind-key/0x561727096320]
1582098738.692814 yylex_token: bind
1582098738.692823 yylex_token: &
1582098738.692832 yylex_token: confirm-before
1582098738.692843 yylex_token: -pkill-window #W? (y/n)
1582098738.692852 yylex_token: kill-window
1582098738.692863 cmd_parse_build_commands: 0 bind
1582098738.692871 cmd_parse_build_commands: argv[0]=&
1582098738.692880 cmd_parse_build_commands: argv[1]=confirm-before
1582098738.692889 cmd_parse_build_commands: argv[2]=-pkill-window #W? (y/n)
1582098738.692897 cmd_parse_build_commands: argv[3]=kill-window
1582098738.692906 cmd_parse: bind-key: argv[0]=bind
1582098738.692914 cmd_parse: bind-key: argv[1]=&
1582098738.692922 cmd_parse: bind-key: argv[2]=confirm-before
1582098738.692931 cmd_parse: bind-key: argv[3]=-pkill-window #W? (y/n)
1582098738.692939 cmd_parse: bind-key: argv[4]=kill-window
1582098738.692960 cmd_parse_build_commands: bind-key & confirm-before "-pkill-window #W? (y/n)" kill-window
1582098738.692970 cmdq_get_command: [bind-key/0x561727096ac0] group 32
1582098738.692979 cmdq_append <global>: [bind-key/0x561727096ac0]
1582098738.692989 yylex_token: bind
1582098738.692997 yylex_token: '
1582098738.693007 yylex_token: command-prompt
1582098738.693016 yylex_token: -pindex
1582098738.693026 yylex_token: select-window -t ':%%'
1582098738.693037 cmd_parse_build_commands: 0 bind
1582098738.693045 cmd_parse_build_commands: argv[0]='
1582098738.693054 cmd_parse_build_commands: argv[1]=command-prompt
1582098738.693063 cmd_parse_build_commands: argv[2]=-pindex
1582098738.693071 cmd_parse_build_commands: argv[3]=select-window -t ':%%'
1582098738.693088 cmd_parse: bind-key: argv[0]=bind
1582098738.693096 cmd_parse: bind-key: argv[1]='
1582098738.693104 cmd_parse: bind-key: argv[2]=command-prompt
1582098738.693113 cmd_parse: bind-key: argv[3]=-pindex
1582098738.693121 cmd_parse: bind-key: argv[4]=select-window -t ':%%'
1582098738.693141 cmd_parse_build_commands: bind-key \\' command-prompt -pindex "select-window -t ':%%'"
1582098738.693151 cmdq_get_command: [bind-key/0x561727096f10] group 35
1582098738.693160 cmdq_append <global>: [bind-key/0x561727096f10]
1582098738.693170 yylex_token: bind
1582098738.693178 yylex_token: (
1582098738.693187 yylex_token: switch-client
1582098738.693195 yylex_token: -p
1582098738.693205 cmd_parse_build_commands: 0 bind
1582098738.693213 cmd_parse_build_commands: argv[0]=(
1582098738.693222 cmd_parse_build_commands: argv[1]=switch-client
1582098738.693230 cmd_parse_build_commands: argv[2]=-p
1582098738.693239 cmd_parse: bind-key: argv[0]=bind
1582098738.693247 cmd_parse: bind-key: argv[1]=(
1582098738.693255 cmd_parse: bind-key: argv[2]=switch-client
1582098738.693263 cmd_parse: bind-key: argv[3]=-p
1582098738.693278 cmd_parse_build_commands: bind-key ( switch-client -p
1582098738.693288 cmdq_get_command: [bind-key/0x5617270972b0] group 38
1582098738.693296 cmdq_append <global>: [bind-key/0x5617270972b0]
1582098738.693311 yylex_token: bind
1582098738.693320 yylex_token: )
1582098738.693329 yylex_token: switch-client
1582098738.693337 yylex_token: -n
1582098738.693346 cmd_parse_build_commands: 0 bind
1582098738.693355 cmd_parse_build_commands: argv[0]=)
1582098738.693363 cmd_parse_build_commands: argv[1]=switch-client
1582098738.693371 cmd_parse_build_commands: argv[2]=-n
1582098738.693380 cmd_parse: bind-key: argv[0]=bind
1582098738.693388 cmd_parse: bind-key: argv[1]=)
1582098738.693396 cmd_parse: bind-key: argv[2]=switch-client
1582098738.693404 cmd_parse: bind-key: argv[3]=-n
1582098738.693419 cmd_parse_build_commands: bind-key ) switch-client -n
1582098738.693429 cmdq_get_command: [bind-key/0x561727097720] group 41
1582098738.693437 cmdq_append <global>: [bind-key/0x561727097720]
1582098738.693447 yylex_token: bind
1582098738.693455 yylex_token: ,
1582098738.693464 yylex_token: command-prompt
1582098738.693472 yylex_token: -I#W
1582098738.693483 yylex_token: rename-window -- '%%'
1582098738.693493 cmd_parse_build_commands: 0 bind
1582098738.693501 cmd_parse_build_commands: argv[0]=,
1582098738.693509 cmd_parse_build_commands: argv[1]=command-prompt
1582098738.693518 cmd_parse_build_commands: argv[2]=-I#W
1582098738.693526 cmd_parse_build_commands: argv[3]=rename-window -- '%%'
1582098738.693535 cmd_parse: bind-key: argv[0]=bind
1582098738.693543 cmd_parse: bind-key: argv[1]=,
1582098738.693551 cmd_parse: bind-key: argv[2]=command-prompt
1582098738.693559 cmd_parse: bind-key: argv[3]=-I#W
1582098738.693567 cmd_parse: bind-key: argv[4]=rename-window -- '%%'
1582098738.693588 cmd_parse_build_commands: bind-key , command-prompt "-I#W" "rename-window -- '%%'"
1582098738.693597 cmdq_get_command: [bind-key/0x561727097de0] group 44
1582098738.693606 cmdq_append <global>: [bind-key/0x561727097de0]
1582098738.693616 yylex_token: bind
1582098738.693624 yylex_token: -
1582098738.693633 yylex_token: delete-buffer
1582098738.693642 cmd_parse_build_commands: 0 bind
1582098738.693674 cmd_parse_build_commands: argv[0]=-
1582098738.693686 cmd_parse_build_commands: argv[1]=delete-buffer
1582098738.693696 cmd_parse: bind-key: argv[0]=bind
1582098738.693703 cmd_parse: bind-key: argv[1]=-
1582098738.693711 cmd_parse: bind-key: argv[2]=delete-buffer
1582098738.693725 cmd_parse_build_commands: bind-key - delete-buffer
1582098738.693735 cmdq_get_command: [bind-key/0x561727097a00] group 47
1582098738.693744 cmdq_append <global>: [bind-key/0x561727097a00]
1582098738.693754 yylex_token: bind
1582098738.693762 yylex_token: .
1582098738.693771 yylex_token: command-prompt
1582098738.693781 yylex_token: move-window -t '%%'
1582098738.693792 cmd_parse_build_commands: 0 bind
1582098738.693800 cmd_parse_build_commands: argv[0]=.
1582098738.693809 cmd_parse_build_commands: argv[1]=command-prompt
1582098738.693828 cmd_parse_build_commands: argv[2]=move-window -t '%%'
1582098738.693838 cmd_parse: bind-key: argv[0]=bind
1582098738.693846 cmd_parse: bind-key: argv[1]=.

**Comment by nicm** [comment]
This log file is easily small enough to upload to GitHub.

Anyway, your prompt contains a UTF-8 character  (\356\202\260), does the problem go away if you remove it?

**Comment by jaden0747** [comment]
Do you know how to remove them? all I did in the session are spliting the window horizontally and switching between panels.

**Comment by nicm** [comment]
In bash the prompt is in PS1, you can try `PS1=$ `.

Or you might be best to open an issue with oh-my-bash and see if they can help you.

tmux thinks these Unicode characters are width 1, my guess would be the terminal thinks they are width 2. But unless you can figure out how to remove them and see if the problem goes away, it is hard to say for sure.

**Comment by jaden0747** [comment]
Uninstalled oh-my-bash didn't bring my tmux back. I reset everything to default by 'dconf reset -f /' and the split lines displayed correctly.

**Comment by nicm** [comment]
OK your best bet is to ask them if you want to try it again.
