### ISSUE TITLE
[FEATURE REQUEST] Specifying keybind for the current session only

### ISSUE THREAD

**Issue by lord-re** [tmux/tmux#2088]
One cool feature would be **a way to create ephemeral keybinding for the current session**.
Those keybinds shouldn't work in other existing or future sessions.
It could be done with a flag (maybe -t for target ?).

This would open a lot new things to do with tmux.

It could be used to create simple TUI where you launch a shell script launching tmux with special keybinds. Those keybinds could use "display-menu" to create a lighweight interface to many send-keys commands.

**Comment by nicm** [comment]
Create a new key table and then set the key-table option for the session.

**Comment by lord-re** [comment]
One of the goal is to define keybinds in the root table to not use any prefix.

**Comment by nicm** [comment]
?

**Comment by nicm** [comment]
key-table sets default table for the session, default is root.

**Comment by lord-re** [comment]
Ok i see.
Thanks and sorry for the issue.
