### ISSUE TITLE
[Feature Request] add shortcuts to reorder window in window list

### ISSUE THREAD

**Issue by wlx65003** [tmux/tmux#2089]
![image](https://user-images.githubusercontent.com/19600697/75127604-ef9bcf80-56fa-11ea-9074-d54bb525702d.png)

For example, I can press `ctrl + shift + left/right` to move windows up and down.

I've tried `bind-key -n C-S-Left swap-window -t -1`, but it seems not work in window list. it only works when enter in specific window.

**Comment by nicm** [comment]
See https://github.com/tmux/tmux/issues/2029, I think the diff should still apply.

**Comment by wlx65003** [comment]
> See #2029, I think the diff should still apply.

Thanks, cue me here if you've released it.
