### ISSUE TITLE
Option to disable UTF8 Mouse in non UTF8 consoles.

### ISSUE THREAD

**Issue by estebanz01** [tmux/tmux#209]
Hello,

After the implementation of the global flag `mouse`, the `mouse-utf8` no longer exists, having issues using mouse like this: http://superuser.com/questions/417027/why-are-random-characters-inserted-into-my-tmux-session

Is there any way to disable UTF8 mouses in ~~tmux 2.1~~ the latest tmux github code ?

Thanks in advance.

**EDIT:** I'm using the latest github code available in the tmux repo.

**Comment by ThomasAdam** [comment]
This looks more like you need to turn off clipboard.

**Comment by nicm** [comment]
mouse-utf8 was still there in 2.1, it only went away in Git.

**Comment by estebanz01** [comment]
@ThomasAdam when I click the console, random characters appears. Is it trying to load something from the clipboard?

@nicm uhm... I just clone the github project and compile from source. It will be nice to have an option to disable this thing thought the tmux conf file.

**Comment by nicm** [comment]
You aren't using 2.1 then. What terminal are you using?

**Comment by estebanz01** [comment]
Terminator 0.97-2ubuntu0.1.

**Comment by nicm** [comment]
mouse-utf8 is now always on by default and tmux should parse the UTF-8 coming back.

What exactly are you seeing when you click the mouse?

Please run "tmux -vvvvLtest new" then click the mouse so it shows the characters, then exit tmux and send me the tmux-server-*.log file from the current directory.

**Comment by estebanz01** [comment]
I'm seeing this every time I click in any of the windows/panes:
![tmux chars](https://cloud.githubusercontent.com/assets/2417465/11344836/8f64c00a-91e1-11e5-8c37-e23fb0669411.png)

And this is the log (just change the ext to upload the file here).

[tmux-server-1756.txt](https://github.com/tmux/tmux/files/41871/tmux-server-1756.txt)

**Comment by nicm** [comment]
Some of the keys are being picked up correctly, but there is some of this:

1448301274.519255 keys are 6 (\033[M#\310K)
1448301274.519280 complete key \033[ 0x20000000005b
1448301274.519296 session 0 activity 1448301274.519292 (last 1448301274.416122)
1448301274.519304 session 0 not pasting
1448301274.519314 writing key 0x20000000005b (M-[) to %0
1448301274.519325 keys are 4 (M#\310K)
1448301274.519332 complete key M 0x4d
1448301274.519339 session 0 activity 1448301274.519336 (last 1448301274.519292)
1448301274.519345 session 0 pasting (flag 0)
1448301274.519352 writing key 0x4d (M) to %0
1448301274.519358 keys are 3 (#\310K)
1448301274.519364 complete key # 0x23
1448301274.519371 session 0 activity 1448301274.519369 (last 1448301274.519336)
1448301274.519382 session 0 pasting (flag 1)
1448301274.519390 writing key 0x23 (#) to %0
1448301274.519398 keys are 2 (\310K)
1448301274.519406 discard key \310K 0x23

Where tmux is getting a mouse key but not recognising it. However, oddly, if I feed the sequence into tmux myself, it works fine, with or without a UTF-8 client.

Does anything change if you do "tmux -uLtest new" instead?

**Comment by nicm** [comment]
Ok I think I know what is wrong.

**Comment by nicm** [comment]
Yes, the problem is that it is impossible to tell the difference between UTF-8 and non-UTF-8 mouse input, so we cannot support it without an option. Your terminal is just sending standard mouse input. I think we should drop support for the UTF-8 mouse input extension entirely, it is a poor design and the SGR format is much superior.

**Comment by estebanz01** [comment]
Running `tmux -uLtest new` does the same behaviour. I agree with you @nicm, it's better to move to a better and cleaner implementation. Thanks for the help.

**Comment by ailin-nemui** [comment]
even though the SGR implementation is much cleaner several programs are (still) working with the utf-8 one (which is not limited in screen width unlike the byte-based one), I think it seems more obvious to drop support for non-utf-8 in an utf-8 terminal but as you said it is not possible to support both of them automatically

**Comment by nicm** [comment]
If we don't support non-UTF-8 then lots of things break (as in, they actually don't work), and they are likely to be older programs which may be hard to update. If we drop support for UTF-8 then a few things can't address more than 223 columns, and most should be things that are still alive and can be converted to use SGR. I think that is a better idea.

**Comment by ailin-nemui** [comment]
as far as I understand you are only breaking *terminals* which do or don't support utf8 (i.e they support only the old protocol and neither utf8 nor SGR, or only support utf8 but not SGR). Applications running inside tmux will be unaffected since they request whether they want to use utf8 or sgr mode, correct?

**Comment by nicm** [comment]
Actually, you are right, we can remove support for UTF-8 outside tmux
but keep it inside, I'll do that.

**Comment by nicm** [comment]
Please try to update from master now and see if your problem is fixed.

**Comment by estebanz01** [comment]
Code up to date and the issue no longer exists. Thank you all for the help. :+1:
