### ISSUE TITLE
-c "#{pane_current_path}" ignored by new-session

### ISSUE THREAD

**Issue by jonrward** [tmux/tmux#2091]
### Description

`-c "#{pane_current_path}"` ignored by new-session

### Steps to reproduce:

```bash
rm -f tmux*.log; mkdir -p ~/foo ~/bar; cd foo; tmux kill-server; tmux -vv -f/dev/null new # outside tmux
cd ~/bar # inside tmux
```
Press `Ctrl-B` `:`, type `new-session -c "#{pane_current_path}"`

### Expected outcome:
Opens a new session in the dir `~/bar`, just as when running `new-session -c ~/bar` as was the behaviour in 2.8 and earlier. Or, alternatively, an error if this is no longer supported.

### Actual outcome
Opens a new session in `~`.

### General info
tmux version: `tmux 3.1-rc` (also reproduced in various other 3.x builds)
platform: `Linux bud 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux`
$TERM inside tmux: `xterm`
$TERM outside tmux: `screen`
Logs:
[tmux-out-9422.log](https://github.com/tmux/tmux/files/4260647/tmux-out-9422.log)
[tmux-client-9420.log](https://github.com/tmux/tmux/files/4260648/tmux-client-9420.log)
[tmux-server-9422.log](https://github.com/tmux/tmux/files/4260645/tmux-server-9422.log)

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/4261207/x.diff.txt)

**Comment by jonrward** [comment]
@nicm Thanks! Works perfectly.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
