### ISSUE TITLE
[Feature Request] Implement capture pane with zoom status.

### ISSUE THREAD

**Issue by kevinhwang91** [tmux/tmux#2092]
I wrote a script to implement this demand https://github.com/tmux/tmux/issues/1929.
I found that I can't capture the pane with zoom status and lose some preview detail in fzf.

**Comment by nicm** [comment]
I don't know what you are asking for?

**Comment by kevinhwang91** [comment]
Using `capture-pane` only capture the pane with the size of the current layout, it will miss information when the size of the preview in fzf larger than the captured pane's.
Such as the height of the target pane is 10, but the height of the preview in fzf is 50.

**Comment by nicm** [comment]
So you want it to capture the size of the pane unzoomed even when it is zoomed?

**Comment by kevinhwang91** [comment]
Yes

**Comment by nicm** [comment]
How would tmux know what the bigger pane looked like if the application had redrawn it to be smaller again?

**Comment by kevinhwang91** [comment]
Could tmux make an option to zoom the pane no matter what size it is and resize after capturing?
I'm not sure if tmux is easy to do that.

**Comment by nicm** [comment]
But you could just zoom the pane and capture and unzoom it afterwards yourself?

**Comment by kevinhwang91** [comment]
Ok, I try it just now when using fzf preview, it can zoom the pane of a shell, but not the tui application such as vim, ranger.
And then I invoke `choose-tree -Z`, press `:` to enter command-prompt and run `resize-pane -Z` , but the result is the same with fzf.

**Comment by nicm** [comment]
If you want to capture a pane fully zoomed, you will need to zoom it, wait for a short period to let the application inside get the SIGWINCH and redraw, then do capture-pane, then unzoom (if the window was not previously zoomed), something like:
~~~~
zoomed=$(tmux display -p '#{window_zoomed_flag}')
test $zoomed -ne 1 && tmux resizep -Z
sleep 0.5
tmux capturep -p >captured-output
test $zoomed -ne 1 && tmux resizep -Z

**Comment by kevinhwang91** [comment]
The script makes a flicker although it works. 
I found that the tui application only is zoomed while its pane is activated, I must switch the pane to do that.
Could you provide an idea to avoid the flicker?

**Comment by nicm** [comment]
No, tmux has to resize the pane to zoom it and that will make it redraw, and it has to leave it zoomed for a while to let the application itself redraw or there will not be anything to capture, so there is no way to avoid it flickering. You can try a shorter sleep but if it is too short there will not be time for the application to redraw to the bigger size.

**Comment by kevinhwang91** [comment]
Thank for your patient explanation!
