### ISSUE TITLE
Split panes ratio get reset if tiling window is resized too much

### ISSUE THREAD

**Issue by NicolasCARPi** [tmux/tmux#2094]
### Issue description

**Summary**: If the window is split at a ratio different than 50%, after resizing the window, the ratio is set at 50% instead of keeping it at the set value.

**How to reproduce**:
Start new session with freshly built tmux: `./tmux -vv -Ltest -f/dev/null new`
Split the window unevenly: `Ctrl-b :` `split-window -v -p 30`
Spawn a bunch of other windows so the tmux window will get shrinked (I use awesomeWM tiling WM). **Note**: see the new data below, it appears that resizing a floating window doesn't trigger this bug!
Close the other windows to get back the tmux window at full size.

Expected: the split is still at 30%

Actual: the split is at 50%.

I have recorded a video to illustrate. Note that in the video I'm using my tmux.conf but the issue is also here without it. In the video, I start with uneven splits (vertical and horizontal), then open a bunch of new windows and close them. When the tmux window is again the only one, we can see that the vertical split is now at 50%. ~~Interestingly, the horizontal split conserved the correct ratio!~~ Horizontal split also has incorrect ratio.

video: https://gfycat.com/regularqueasyadeliepenguin (make sure to set in HD and fullscreen)

~~**New data**: it appears that if the window is a floating window and is resized manually **this bug doesn't appear**: the ratio of the split stays the same, see gif for a floating window:~~

![out](https://user-images.githubusercontent.com/3043706/75700979-38332a00-5cb3-11ea-991e-b262173d1174.gif)
edit: in this gif the ratio is not conserved

This issue is happenning with xterm and urxvt.

Also, I tried to go back to previous versions of tmux to try and see if I could find a version that doesn't have this bug, but all of them showed this bug. Whereas before (maybe before 3.0a), this issue didn't exist, the ratio was always conserved. As I said, at that point I'm not even sure if it's a bug in tmux or something that changed in my environment that now makes this bug appear. Any insight on what could go wrong would be great, as I hate to have to resize my panes (first world problems you know :p)

### Required information

Please provide the following information:

* tmux version (`tmux -V`): all from 2.1 to latest from master
* Platform (`uname -sp`): linux unknown (archlinux)
* $TERM inside and outside of tmux (`echo $TERM`): `rxvt` or `xterm` outside, `screen` inside
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-356954.log](https://github.com/tmux/tmux/files/4262560/tmux-client-356954.log)
[tmux-out-356956.log](https://github.com/tmux/tmux/files/4262561/tmux-out-356956.log)
[tmux-server-356956.log](https://github.com/tmux/tmux/files/4262562/tmux-server-356956.log)

**Comment by nicm** [comment]
tmux does not remember that you had a 50% split so it is not guaranteed to stay 50% if you resize, particularly if you resize multiple times, although it should stay broadly the same.

It is impossible to make anything out in your video, please show an example with a smaller terminal.

**Comment by NicolasCARPi** [comment]
> tmux does not remember that you had a 50% split so it is not guaranteed to stay 50% if you resize

Ok that's good to know, I assumed it did. When a window is resized, does tmux knows about it?

> It is impossible to make anything out in your video

Did you click the HD button in bottom right and put in fullscreen?

**Comment by nicm** [comment]
Yes tmux knows when the window is resized, but pane proportions are not fixed.

Yes there is too much going on in this video and it is too small, can you please 1) show with a smaller terminal or larger font 2) preferably with no tmux config (`tmux -Ltest -f/dev/null new`) 3) don't do so much moving things about and with so many panes 4) upload it to this issue instead of putting it on some external website.

**Comment by NicolasCARPi** [comment]
> Yes tmux knows when the window is resized, but pane proportions are not fixed.

Interesting, maybe there is something to add here: like "when redraw, make sure the panes split ratio is conserved".

Please find a better gif here with big font size and smaller terminal and no .tmux.conf from latest master (ccd24c9cb242b):

![out](https://user-images.githubusercontent.com/3043706/75763227-39f50000-5d3c-11ea-9f8c-44d31f25944e.gif)

In this gif, the terminal is resized only in the "x" axis, so only the horizontal split is affected, but it would have been the same if the terminal was resized in a different axis.

Note: with a floating window the split also appears to move around contrary to what I said earlier.

**Comment by nicm** [comment]
You are resizing the window so small that the two panes end up taking up half each out of necessity, when they are resized up again the new space is added to each pane evenly, so they will end up around half of the window each.

**Comment by NicolasCARPi** [comment]
@nicm Indeed that is the behaviour observed. I would expect that when the window is resized up again, the panes manage to get back to the correct ratio that was set during the split.

Now the question is: would it be a good idea to track the split ratio so that we can restore it if enough space is available (after a resize has forced it to change), or is it too cumbersome/complicated to implement?

**Comment by nicm** [comment]
It would be a good idea but it would not be easy to implement, layouts don't work like that at the moment.

**Comment by NicolasCARPi** [comment]
Ok, then I'll close this issue and live with this behavior.

Cheers,
~Nico
