### ISSUE TITLE
Bind-key seems not work on TTY

### ISSUE THREAD

**Issue by Paquity** [tmux/tmux#2095]
Hello,

Recently I try to rebind some keys in tmux and, as I described in the issue, it seems to not work on TTY (but work fine in terminals emulators). After some test, I noticed that we only can unbind keys on TTY and the `bind-key` function have not affect.
The problem comes from my side?

There is my configuration file:
```
bind-key -n S-Left next-window
bind-key -n S-Right previous-window

bind-key -n C-Left select-pane -L
bind-key -n C-Right select-pane -R
bind-key -n C-Up select-pane -U
bind-key -n C-Down select-pane -D
```

#### Required information:
* tmux version: `tmux 3.0a`
* Platform: `Arch Linux (kernel linux 5.5.7) (x86_64)`
* $TERM inside of tmux: `screen-256color`
* $TERM outside of tmux: `linux` (TTY) / `xterm-256color` (terminal emulators)
* Logs from tmux: `Nothing relevant to show here.`

**Comment by nicm** [comment]
Probably your terminal doesn't send any sequences or the right sequences for these keys but without logs that is just a guess.

**Comment by Paquity** [comment]
Oops, sorry for the log :sry:

Here are my logs (using `tmux kill-server; tmux -vv new`) from tmux in TTY and terminal emulators after executing this sequence:
```
CTRL-b + c	(create new windows)
SHIFT + Left	(try to move to the next window, nothing happened here)
SHIFT + Right	(try to move to the previous window, nothing happened here)
CTRL-b + %	(create new pane)
CTRL + Left	(try to move to the left pane, nothing happened here)
CTRL + Right	(try to move to the right pane, nothing happened here)
CTRL + d	(kill session)
CTRL + d	(kill session)
CTRL + d	(exit from tmux)
```
[tmux_log_020320.zip](https://github.com/tmux/tmux/files/4277871/tmux_log_020320.zip)

**Comment by nicm** [comment]
It looks like one of these terminal emulators (Linux console, I assume) does not support S-Left and S-Right or C-Left or C-Right. All that is in the log is:
~~~~
1583181874.310581 /dev/tty2: keys are 3 (\033[C)
1583181866.294692 /dev/tty2: keys are 3 (\033[C)
~~~~
`\033[C` is Right, without any modifiers.

But in your X terminal emulator:
~~~~
1583181974.911416 /dev/pts/0: keys are 6 (\033[1;2C)
1583181981.330022 /dev/pts/0: keys are 6 (\033[1;5C)
~~~~
This is correct.

So you will not be able to use these keys, unless you can figure out how to make it send the right xterm-style sequences, or at least something different from a key press without modifiers.
