### ISSUE TITLE
Copying text with panes in a vertical split

### ISSUE THREAD

**Issue by michaelklachko** [tmux/tmux#2096]
When there are two panes in a vertical split, selecting text and copying it in one pane will automatically copy the corresponding lines from the second pane. Currently to work around it I need to press C + b, then z to expand the current pane, but even then copying the text from it will include empty lines or something weird). Typically I have to edit my copied text in an editor to make it look right.

Can this be fixed? I mean so that I could copy text properly and without expanding panes?

**Comment by nicm** [comment]
If you want copying that is aware of panes you need to use copy mode, tmux has no control over the outside terminal's copy and paste.

**Comment by michaelklachko** [comment]
Can you please explain? I just tried `C + b, [` is that how I get into "copy mode"? Nothing changed - I still have to press Shift when I select text with a mouse, and the lines from the second pane are still being copied.

**Comment by nicm** [comment]
tmux has no control over the terminal's own copy, copy mode is entirely
separate. I'm not going to repeat the documentation about copy mode, you
can look in the manual or the (only partly finished) document here
https://github.com/tmux/tmux/wiki/Getting-Started#copy-and-paste. The
manual is https://man.openbsd.org/tmux#WINDOWS_AND_PANES.

If you want to use the mouse you can turn on the `mouse` option. If you
want it to integrate with the X clipboard, you need to either use the
`set-clipboard` option which may need some configuration, or
xclip/xsel/pbcopy.

**Comment by michaelklachko** [comment]
I want to perform a simple basic task - copy text with my mouse when there's vertical pane split. The current way to do this in tmux is very annoying. The mouse mode is on. What exactly am I supposed to look for in the manual? If the default terminal I'm using in Ubuntu does not work well with tmux, what should I use instead?

**Comment by nicm** [comment]
If copying in one pane copies text in the other, you are using the terminal copy and paste rather than tmux's own (copy mode). This doesn't know anything about panes and tmux has no way to tell it.

**Comment by michaelklachko** [comment]
I'm fine with using whatever mode/terminal/etc you want me to, as long as I can copy text with a mouse when there's a vertical pane split. I'm still not sure if you're saying this can or cannot be done. If not, ok, I can live with that, just wanted to report a basic usability issue.

**Comment by nicm** [comment]
Yes it can be done, if you turn on the `mouse` option it is the default. Try:

~~~~
tmux -Ltest -f/dev/null new \; set -g mouse on
~~~~

Then you will be able to drag to select text, it will be copied when you release the mouse.

If this works and your default config does not, you have probably changed some of the mouse key bindings.

**Comment by nicm** [comment]
gnome-terminal does not support `set-clipboard` so if you want the copied text to go to the X clipboard as well as a tmux paste buffer you will either need to configure tmux to use `xclip` or `xsel`, or use a different terminal that does support it (like xterm).

**Comment by michaelklachko** [comment]
Here's my tmux.conf (I have no idea what any of those "sane scrolling" options are, I copied it from somewhere a while ago):

`set -g mouse on                                                                                                                                                                                                                       # sane scrolling:                                                                                                                                                                                                                     bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"                                                                                       set-option -g history-limit 100000`
                                                                                                                                                                                                                                                                                                                                                                                                                
I'm actually using WSL terminal on Windows 10 to ssh to the Ubuntu 18.04 server, where I installed tmux 3.0a. 

Anyway, I deleted the above config, exited tmux and then started it again using your command. I'm getting exactly the same behavior as before: after I split panes vertically, when I select text it's not being copied - I have to press Shift, and as soon as I do that text from the adjacent pane gets selected.

**Comment by nicm** [comment]
If you press Shift you are using terminal copy and paste, which will not work with panes in any terminal.

If you do not use Shift, you are using tmux copy and paste, which copies to a tmux buffer. If you want this to also go to the X or Windows clipboard, you need to configure that. If you were running tmux locally, you could use xclip or xsel or similar. Since you aren't you will need a terminal that supports OSC 52 and use the tmux set-clipboard option. On some terminals this works by default, some it doesn't work at all, and some it will need to be configured. The only terminal I am sure supports it on Windows is mintty, for others you will need to figure out if OSC 52 is supported, if you need to change an option to turn it on, and if you need to tell tmux to add the Ms capability to tmux with terminal-overrides.

**Comment by michaelklachko** [comment]
OK, so if I install mintty to run WSL on Windows to ssh to Ubuntu and start tmux there, I won't have to press shift and everything will be properly copied to windows clipboard, right?

**Comment by nicm** [comment]
Possibly, it definitely supports OSC 52 and it is on by default in tmux, but I don't know if you will need to do any other configuration, you'll have to try it and see.

**Comment by michaelklachko** [comment]
Installed WSLtty, put the same .tmux.conf as what I showed above - no luck. Still the same problem.

**Comment by michaelklachko** [comment]
Actually I see something strange: selecting text with a mouse in the left pane works differently from doing the same in the right pane: on the right when I select text it stays selected (shown in yellow), and the only way to deselect it is to click q. On the left, simple left click starts the selection mode (yellow highlighting), which disappears after a second click. Weird, but neither provides what I want.

**Comment by nicm** [comment]
What is TERM outside tmux?

**Comment by michaelklachko** [comment]
How can I check this?

**Comment by michaelklachko** [comment]
![image](https://user-images.githubusercontent.com/981619/75763018-73078300-5cf0-11ea-927b-060583c1079d.png)

**Comment by nicm** [comment]
echo $TERM

**Comment by michaelklachko** [comment]
michael@Pascal:~$ echo $TERM
screen

**Comment by michaelklachko** [comment]
wait, if I exit tmux:

michael@Pascal:~$ echo $TERM
xterm-256color

**Comment by nicm** [comment]
With TERM xterm-256color outside tmux, it will work by default, you need to find a terminal that supports OSC 52 or figure out how to enable it in the terminals you have.

**Comment by michaelklachko** [comment]
Here's some info that might be relevant: https://github.com/mintty/wsltty/issues/21
