### ISSUE TITLE
Weird bashrc + termux sudo su bug 

### ISSUE THREAD

**Issue by p4yl0ad** [tmux/tmux#2098]
Found a really annoying thing that happens 
I have my bashrc settings to attach or start a tmux session with 
'tmux a'
'tmux new -s STARTUP'
and when increasing permissions with 'sudo su'
then downgrading back to the user with 'sudo su p4yl0ad'
an odd recursion happens , which is unable to be exited unless the process is killed 

tmux 3.0a
Linux p4yload 5.4.18-1-MANJARO #1 SMP PREEMPT Thu Feb 6 11:41:30 UTC 2020 x86_64 GNU/Linux
manjaro linux

echo $TERM (inside tmux) = screen
echo $TERM (outside tmux) = xterm-termite

**Comment by nicm** [comment]
You are probably attaching tmux inside tmux and because there is a `sudo` in between the `TMUX` environment variable is lost so tmux can't stop you.
