### ISSUE TITLE
tmux session_attached with sway, i3

### ISSUE THREAD

**Issue by zdmgmail** [tmux/tmux#2099]
set -g status-left " Sessions: #{S:#{?session_attached,*,}#{session_name} }

When using tmux I use this line configuration to add * know where I am focusing

I want tmux to only add * in the current focus terminal, but in sway / i3 , * will be added to the tmux terminal of other workspaces

Is there a way to solve this problem

**Comment by nicm** [comment]
How is tmux supposed to know which attached session you are looking at?

**Comment by zdmgmail** [comment]
> How is tmux supposed to know which attached session you are looking at?

I always want to attach to the terminal that the current workspace is displaying

I heard that this is a problem with irc. I don't know ..

**Comment by nicm** [comment]
tmux can't know what the workspace and which sessions are attached on which workspaces is unless somehow you tell it.

**Comment by zdmgmail** [comment]
> tmux can't know what the workspace and which sessions are attached on which workspaces is unless somehow you tell it.

OK,thanks
