### ISSUE TITLE
Key bound to C-j occasionally gets unbound

### ISSUE THREAD

**Issue by fphilipe** [tmux/tmux#21]
Every now and then the command I've configured to run on `C-j` no longer works and a normal line feed (which is the code `C-j` produces) is triggered. When I look up the configured keys, everything is there except for `C-j`. It simply vanishes. This hasn't happened for any other key binding.

I'm really not sure how to reproduce this, but my gut feeling tells me that it happens when I'm using PostgreSQL's psql shell. Not sure whether it is technically possible that psql would mess with the keys. When I run the `bind-key` command as I have it in my `.tmux.conf` everything works again.

**Comment by nicm** [comment]
Are we expected to guess your tmux version and what OS you are using?

It is extremely unlikely that psql is removing a key binding. I expect have something, somewhere that is removing the binding (cron? shell startup?), or you are mixing up tmux configs, or tmux servers. Run tmux with -vvvv and after the C-j binding disappears look in the logs for something like:

cmdq 0x7f04ae80: unbind-key C-j (client 12)

Or for anything else weird.

**Comment by nicm** [comment]
Also show me your full .tmux.conf please.

**Comment by fphilipe** [comment]
Sorry for the half-assed report. Here's what you're asking for.

Version: 2.0
.tmux.conf: https://github.com/fphilipe/dotfiles/blob/master/tmux.conf

 I'll run tmux with `-vvvv` from now on to see if I catch it.

**Comment by nicm** [comment]
Thanks, don't see anything weird in config. Try run wirh -vvv and send me the tmux-server* log after the key disappears.

**Comment by bruno-** [comment]
Hi,
I just accidentally saw this issue. @fphilipe I see you're running some tmux plugins scripts. This is likely due to this [tmux-copycat issue](https://github.com/tmux-plugins/tmux-copycat/issues/62).

I'm sorry this is wasting time for tmux core maintainers, we should probably document this better.
