### ISSUE TITLE
tmux version should show version

### ISSUE THREAD

**Issue by ORESoftware** [tmux/tmux#2100]
we have these commands

```
tmux ls
tmux kill-window
tmux version
```

in order to get the version we have to do `tmux -V` which is not expected...what is more common for CLI tools with a subcommand pattern is to do:

``` bash
$ tool version
```
so

```bash
$ tmux version #  should work fine
```

on the same subject:

```bash
tmux help # should work too
```

**Comment by nicm** [comment]
Rubbish.

**Comment by ORESoftware** [comment]
@nicm lol

**Comment by ORESoftware** [comment]
you know what's rubbish? `tmux -V` lol what a joke
