### ISSUE TITLE
DECRQSS support

### ISSUE THREAD

**Issue by craigbarnes** [tmux/tmux#2101]
Would it be possible to support the [`DECRQSS`](https://vt100.net/docs/vt510-rm/DECRQSS.html) control sequence? I searched the issue tracker and it doesn't seem to have been mentioned here before. The use case is for querying the current cursor style (`DECSCUSR`), but some of the other requests would be useful if they were more widely supported.

I've tried xterm, xfce4-terminal, termite, etc. and they all seem to support it, but with tmux in the mix the requests seem to get dropped with no response.

**Comment by nicm** [comment]
Someone asked about one of these recently, maybe it was the background colour or something.

tmux could relatively easily support this when the cursor style or colour or whatever has been set inside tmux, but when it hasn't it would need to query the outside terminal and I think this is more trouble than its worth for something hardly anyone uses and there is really hardly any use for.

**Comment by nicm** [comment]
It was https://github.com/tmux/tmux/issues/1919.
