### ISSUE TITLE
[Feature Request] Support more operations in format strings

### ISSUE THREAD

**Issue by tculp** [tmux/tmux#2102]
### Premise

It would be useful to perform math operations in format strings, such as modulus, addition, multiplication, etc.

### Background

I wish to have my windows in the window-list alternate colors to be able to easily differentiate where they start and stop. This would generally be done with a comparison of 0 and the modulus of the window index / 2 (assuming renumber-windows is set to on). However, there is currently no obvious way within the format system to perform modulus or any other math operation.

**Comment by nicm** [comment]
I'm OK with adding more, it shouldn't be too difficult - take a look at format.c:format_build_modifiers and format.c:format_replace.

**Comment by tculp** [comment]
What do you think would be best for the modifiers? Here are my proposed options:

#{M:equation}  :   The most versatile and understandable option, where everything after an M: (for Math) can be parsed as an entire equation. This is my personal favorite option, due to it's versatility and only using up a single format modifier.

M+ M- M* M/ M%   :   Similar to the above, however this greatly limits the math functionality to a single operation each, and each type of operation would use up a format modifier.

+ - * / %   :   The only issue is / is used by replacement.

++ -- ** // %%   :   A little odd, but doesn't collide with the other format modifiers.

**Comment by nicm** [comment]
I think the second is better, for the first you would need either to make
an infix parser which is going to be a fair bit of extra code, or make it
postfix which is annoying for normal people to use.

The second option can use the existing parsing code.

You could make it one format letter followed  by an operator as the first
argument, so eg:

#{e|+:#{window_index},1}

Or:

#{e|%:#{status-left-length},7}

I would probably make the default integers, if you also want to support FP
then you could add a second argument flags with one to specify an FP result
eg #{e|/|f:...}.
