### ISSUE TITLE
list=right-marker with length greater than one is handled oddly

### ISSUE THREAD

**Issue by tculp** [tmux/tmux#2103]
### Required information

* tmux version: next-3.2 (latest git)
* Platform: Darwin i386
* $TERM inside: screen-256color
* $TERM outside: xterm-256color

### Problem

When the list=right-marker size is greater than 1, it get placed at the wrong index and eats into the style-right area. The left-marker works as expected.

Behavior with default right-marker:
![Screen Shot 2020-03-06 at 12 15 08 PM](https://user-images.githubusercontent.com/19711877/76106529-08cb3880-5fa5-11ea-923c-3538e39beec1.png)

Behavior with longer right-marker:
![Screen Shot 2020-03-06 at 12 16 34 PM](https://user-images.githubusercontent.com/19711877/76106560-1da7cc00-5fa5-11ea-95e5-414c2d8df0e8.png)

Example .tmux.conf to repoduce:

`set -g status-format[0] "#[align=left range=left #{status-left-style}]#[push-default]#{T;=/#{status-left-length}:status-left}#[pop-default]#[norange default]#[list=on align=#{status-justify}]#[list=left-marker]<...#[list=right-marker]...>#[list=on]#{W:#[range=window|#{window_index} #{window-status-style}#{?#{&&:#{window_last_flag},#{!=:#{window-status-last-style},default}}, #{window-status-last-style},}#{?#{&&:#{window_bell_flag},#{!=:#{window-status-bell-style},default}}, #{window-status-bell-style},#{?#{&&:#{||:#{window_activity_flag},#{window_silence_flag}},#{!=:#{window-status-activity-style},default}}, #{window-status-activity-style},}}]#[push-default]#{T:window-status-format}#[pop-default]#[norange default]#{?window_end_flag,,#{window-status-separator}},#[range=window|#{window_index} list=focus #{?#{!=:#{window-status-current-style},default},#{window-status-current-style},#{window-status-style}}#{?#{&&:#{window_last_flag},#{!=:#{window-status-last-style},default}}, #{window-status-last-style},}#{?#{&&:#{window_bell_flag},#{!=:#{window-status-bell-style},default}}, #{window-status-bell-style},#{?#{&&:#{||:#{window_activity_flag},#{window_silence_flag}},#{!=:#{window-status-activity-style},default}}, #{window-status-activity-style},}}]#[push-default]#{T:window-status-current-format}#[pop-default]#[norange list=on default]#{?window_end_flag,,#{window-status-separator}}}#[nolist align=right range=right #{status-right-style}]#[push-default]#{T;=/#{status-right-length}:status-right}#[pop-default]#[norange default]"
`

**Comment by nicm** [comment]
Yes, I see - try this please:
~~~~
--- format-draw.c       8 Jan 2020 14:40:52 -0000       1.14
+++ format-draw.c       6 Mar 2020 20:04:01 -0000
@@ -142,7 +142,8 @@ format_draw_put_list(struct screen_write
                width -= list_left->cx;
        }
        if (start + width < list->cx && width > list_right->cx) {
-               screen_write_cursormove(octx, ocx + offset + width - 1, ocy, 0);
+               screen_write_cursormove(octx, ocx + offset + width -
+                   list_right->cx, ocy, 0);
                screen_write_fast_copy(octx, list_right, 0, 0, list_right->cx,
                    1);
                width -= list_right->cx;

**Comment by tculp** [comment]
Yeah, that fixed it!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
