### ISSUE TITLE
echo $TERM never shows tmux-256color-italic even though it is set.

### ISSUE THREAD

**Issue by faxotherapy** [tmux/tmux#2107]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.0a
* Platform (`uname -sp`): Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`).
   - Inside: xterm-256color-italic
   - Outside: xterm-256color-italic (yes, still the same and I don't understand why)
* Logs from tmux (`tmux kill-server; tmux -vv new`). [see below]

Here's my main tmux config to use italics and 256 colors using **MacOS Terminal** (set as `xterm-256color` from Terminal app. pref. panel):
```shell
set -g default-terminal "tmux-256color-italic"
set -as terminal-overrides ',xterm-256color-italic:Tc:sitm=\E[3m'
```
Above excerpt is used in conjunction with:
```shell
$ cat <<EOF > xterm-256color-italic.terminfo
# A xterm-256color based TERMINFO that adds the escape sequences for italic.
xterm-256color-italic|xterm with 256 colors and italic,
  sitm=\E[3m, ritm=\E[23m,
  use=xterm-256color,
EOF

$ tic -x xterm-256color-italic.terminfo

$ cat <<EOF > tmux-256color-italic.terminfo
# A xterm-256color based TERMINFO that adds the escape sequences for italic.
tmux-256color-italic|tmux with 256 colors and italic,
  ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
  use=xterm-256color, use=screen-256color,
EOF

$ tic -x tmux-256color-italic.terminfo
```
I make sure I always kill tmux server before testing.

Unfortunately, even though the above config I always have, **inside** tmux:
```
$ echo $TERM
xterm-256color-italic
```
Whereas I should normally have `tmux-256color-italic` (if my understanding is right)

Further output:
```
$ tmux info | grep Tc
 206: Tc: (flag) true
```

Also, if I have _italics_ enabled, I've got strange gradient (obtained from within tmux **and** outside of tmux):
![FailedGradient](https://user-images.githubusercontent.com/6538008/76347845-2d097b00-62ff-11ea-8ded-691f598133ee.gif)

Log file in connexion with this config:
- [tmux-client-38789.log](https://github.com/tmux/tmux/files/4314300/tmux-client-38789.log)
- [tmux-server-38791.log](https://github.com/tmux/tmux/files/4314302/tmux-server-38791.log)
- [tmux-out-38791.log](https://github.com/tmux/tmux/files/4314305/tmux-out-38791.log)

If I want to have a much better gradient, I have to use the following instead, in my tmux config:
```
set -g default-terminal "tmux-256color-italic"
set -as terminal-overrides ',xterm-256color:Tc:sitm=\E[3m'
```

Result (obtained from within tmux):
![BetterGradient](https://user-images.githubusercontent.com/6538008/76348081-8376b980-62ff-11ea-89e5-97b6f32e4539.gif)

But then, I can no longer use `xterm-256color-italic`.

Unfortunately, the gradient is not as good as found [here](https://github.com/tmux/tmux/issues/696) though.

Of course, I still have, inside tmux:
```
$ echo $TERM
xterm-256color-italic
```

Further output:
```
$ tmux info | grep Tc
 206: Tc: [missing]
```

Log file in connexion with this 2nd config:
- [tmux-client-31659.log](https://github.com/tmux/tmux/files/4314226/tmux-client-31659.log)
- [tmux-server-31661.log](https://github.com/tmux/tmux/files/4314229/tmux-server-31661.log)
- [tmux-out-31661.log](https://github.com/tmux/tmux/files/4314231/tmux-out-31661.log)

---

The test script—obtained from [here](https://github.com/tmux/tmux/issues/696) or [there](https://apple.stackexchange.com/a/295584)—is:
```
$ cat test.sh
# Test Italics
echo `tput sitm`italics`tput ritm`
# Test Colour (should be smooth gradient)
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s s s s s s s s s s s s s s s s;
    for (colnum = 0; colnum<256; colnum++) {
        r = 255-(colnum*255/255);
        g = (colnum*510/255);
        b = (colnum*255/255);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```

**Comment by nicm** [comment]
If it is in default-terminal and `tmux show -s default-terminal` shows it but `TERM` is something else in new panes, then it is being changed in one of your shell profiles.

**Comment by faxotherapy** [comment]
Should I leave `export TERM=xterm-256color-italic` in my `.zshrc` file or remove it?
Thanks.

**Comment by nicm** [comment]
If you want TERM to be something else inside tmux you will either need to remove it or guard it as something like `[ -z "$TMUX" ] && export TERM=xterm-256color-italic`.

**Comment by faxotherapy** [comment]
Using `[ -z "$TMUX" ] && export TERM=xterm-256color-italic` in my `.zshrc` file I now have:
- `tmux-256color-italic` as `TERM` inside tmux
- `xterm-256color-italic` as `TERM` when no longer inside of tmux.

Thanks for the suggestion.
