### ISSUE TITLE
Please consider a command-line switch for vi mode

### ISSUE THREAD

**Issue by kajukenbo** [tmux/tmux#2108]
I'd think this is more of a feature request.

Please consider a command line switch to turn on vi mode on startup.

First thing I do is edit a config to make the prefix less inconvenient.
Second thing is to try to remember the syntax to configure the vi mode.

I doubt I am the only one.

Thanks for tmux.

**Comment by krader1961** [comment]
What would this mean for a tmux server that is already running? If the tmux server is already running, and which is using emacs bindings, and you run a `tmux` command with the new flag would it change the behavior of all existing sessions to vi bindings? Also, this proposal shouldn't be needed by most vi users since 

> The default is emacs, unless the VISUAL or EDITOR environment variables are set and contain the string `vi'.

Too, if the first thing you "do is edit a config to make the prefix less inconvenient" I don't see why adding adding the set option commands for `status-keys` and `mode-keys` is un undue burden. Thus, I am confused by your requested change.

**Comment by nicm** [comment]
Are you any more likely to remember a command like switch than remember the name of an option? Or remember how to configure the prefix?

I don't want to be duplicating options on the command line.

**Comment by kajukenbo** [comment]
I guess the suggestion isn't necessary.

I've never noticed the quoted VISUAL / EDITOR behavior in my sessions, nor did I run across it in the man pages when I read them.  Of course that was years ago.  

I will pay more attention to VISUAL / EDITOR setting on the systems I work on and see how it goes.

Thanks for the tip.

**Comment by nicm** [comment]
Well I was trying to think of a way to make it easier, but I don't want to end up with a load of command line options just to replace stuff like `tmux set -g mode-keys vi` or similar.

**Comment by kajukenbo** [comment]
FWIW, I have done some _very_ basic testing and the behavior seems to be inconsistent - at least on tmux v1.8.
Yes, I know it is an old version but it is the version that ships with RHEL/CentOS 7.

$ tmux show-options -g | grep key ;tmux show -g | grep ^prefix; echo "VISUAL=$VISUAL EDITOR=$EDITOR"
---
status-keys emacs
prefix C-b
prefix2 none
VISUAL=vi EDITOR=vi

$ tmux -V
---
tmux 1.8

This could explain part of my confusion.

It came up as "status-keys vi" on an alternate run.

I will play with it but I understand that this version is probably unsupported, development-wise.

Thanks again

**Comment by nicm** [comment]
1.8 is far too old now, you will need to try a later version.

**Comment by kajukenbo** [comment]
Changing versions is not an option on the hundreds of Prod servers in our environment.

I will play with it and see if I can reproduce the desired behavior.

Thanks

**Comment by nicm** [comment]
Well, then you are stuck because even if we added a command line option or made any change at all, you will not be able to use it.

**Comment by nicm** [comment]
I don't remember how VISUAL and EDITOR worked in 1.8, but it should be the same. Did you restart tmux entirely (`tmux kill-server`)? They are only looked at when the server is started.

**Comment by kajukenbo** [comment]
You are right, of course.
I was thinking about the future.

For anyone in the same boat, the solution may be around setting `export VISUAL=vim` or `export VISUAL=vi` and *not* `export EDITOR=`

`EDITOR` does not seem to have an effect.

**Comment by nicm** [comment]
VISUAL is checked first and if it is present (even if empty), EDITOR is not checked, but they definitely both work.

**Comment by kajukenbo** [comment]
> VISUAL is checked first and if it is present (even if empty), EDITOR is not checked, 

That was they key. 

`unset VISUAL` before starting tmux v1.8 and it behaves as you stated.
Just setting `VISUAL=''` was not sufficient.
