### ISSUE TITLE
can use tmux in windows10 cmd ?

### ISSUE THREAD

**Issue by zihaoxingstudy1** [tmux/tmux#2109]
tmux is a very powerful tool.  can use tmux in windows10 cmd ?

**Comment by krader1961** [comment]
No. From the README:

> This release runs on OpenBSD, FreeBSD, NetBSD, Linux, OS X and Solaris.

It can be used in the Windows 10 WSL (windows subsystem for linux) environment but not a "native" Windows 10 `cmd` window.

**Comment by nicm** [comment]
I believe you can use tmux with Cgywin but I don't use Windows so I can't help you any further with this.
