### ISSUE TITLE
ZSH Echos last run command

### ISSUE THREAD

**Issue by btcrooks** [tmux/tmux#211]
I'm having an issue in which ZSH echo's my last command after installing tmux.
I've tried the **set -g default-terminal "xterm"** fix in the .tmux.conf file to no avail.

**Comment by ThomasAdam** [comment]
Setting your default-terminal to anything other than screen (or its derivatives) inside tmux is not what you should be doing.  That's wrong.   Why did you think that would solve your problem?

What's TERM set to outside of tmux?  Which OS is this?  Which terminal are you using?  I presume if this checks out to be true (and you're not doing something silly with TERM) that there's something in your ZSH profile causing this.

**Comment by btcrooks** [comment]
To be honest I have no idea (lol). It was the only proposed solution I've found online.

- Outside of tmux, TERM is set to **screen-256color**
- I am running **Mac OS X El Capitan (v10.11)**
- I amusing the default MAC OS X terminal
- Outside of changing the theme to "cobolt2", ZSH has all of it's default settings.

**Comment by nicm** [comment]
Sounds like a zsh problem to me.

**Comment by btcrooks** [comment]
Gotcha. I'll follow up with the ZSH devs. Thanks!
