### ISSUE TITLE
Got "server exited unexpectedly" for "master" branch

### ISSUE THREAD

**Issue by SchweinDeBurg** [tmux/tmux#2111]
How to reproduce: just build from "master" branch, install package and try to launch.

* tmux version (`tmux -V`).
tmux next-3.2
* Platform (`uname -sp`).
Linux x86_64 (this is Fedora 27 booted into runlevel 3)
* $TERM inside and outside of tmux (`echo $TERM`).
linux
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-21234.log](https://github.com/tmux/tmux/files/4327741/tmux-client-21234.log)
[tmux-server-21236.log](https://github.com/tmux/tmux/files/4327742/tmux-server-21236.log)
tmux-out-21236.log is empty

I've tried to investigate this situation and found that if I revert commit 6571dd50f86927595b6edd2d6fe4a8982b61d8c6 and then revert 516f6099fc2e928587e573176cd753ce3de5806b - tmux launches and works pretty fine. Probably 516f6099fc2e928587e573176cd753ce3de5806b is the real show-stopper.

**Comment by nicm** [comment]
I think this is the fix, should be in GitHub later today. Thanks!
~~~~
diff -u -p -r1.60 -r1.61
--- cmd-run-shell.c     12 Mar 2020 13:25:45 -0000      1.60
+++ cmd-run-shell.c     13 Mar 2020 06:19:33 -0000      1.61
@@ -114,7 +114,8 @@ cmd_run_shell_exec(struct cmd *self, str

        cdata->cwd = xstrdup(server_client_get_cwd(item->client, s));
        cdata->s = s;
-       session_add_ref(s, __func__);
+       if (s != NULL)
+               session_add_ref(s, __func__);

        evtimer_set(&cdata->timer, cmd_run_shell_timer, cdata);

@@ -203,7 +204,8 @@ cmd_run_shell_free(void *data)
        struct cmd_run_shell_data       *cdata = data;

        evtimer_del(&cdata->timer);
-       session_remove_ref(cdata->s, __func__);
+       if (cdata->s != NULL)
+               session_remove_ref(cdata->s, __func__);
        free(cdata->cwd);
        free(cdata->cmd);
        free(cdata);

**Comment by SchweinDeBurg** [comment]
Thank you very much! Commit fa36e9bc88cab7f721911bc56b397b9fd55dc038 fixes this issue.
