### ISSUE TITLE
cmd line append with two asterisks when I using tmux in Windows 10

### ISSUE THREAD

**Issue by MichaelDiao** [tmux/tmux#2113]
Hi,

The trouble is following as the picture:
![image](https://user-images.githubusercontent.com/19757545/76685756-193c7c80-6651-11ea-9891-afeeb4fd800a.png)

The two asterisks are always appended to the prompt and directories.  I do not understand what this is all about. Curiously, with the same configure, it is normal  in mac os, and using git bash in windows 10. So I do not know what the problem is.

My system is Windows 10, and the terimal is conemu-cyg-64.  It is normal when using conemu-cyg-64 without tmux. 

I would appreciate it if you give me some advice. Thanks!

**Comment by nicm** [comment]
Am I supposed to guess the tmux version? Where are the logs?
