### ISSUE TITLE
"other-end" sometimes resets start of selection in copy mode

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2117]
### Issue description

When using the `other-end` command in copy mode, sometimes Tmux unexpectedly resets the start of the selection.

To reproduce, run these shell commands:

    tmux -Lx -f/dev/null
    printf "foo\nbar\nbaz\n"
    tmux copy-mode \; send -X select-line \; send -X -N3 cursor-up \; send -X other-end

Only 1 line is selected.  I would expect 4 lines to be selected; that is the `foo`, `bar`, `baz` lines and the shell prompt line.

### Required information

 - `$ tmux -V`: tmux next-3.2, commit 45be93f6044e9315e066c7ebd75bdd9c54a97498
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - [`$ tmux info`](https://github.com/tmux/tmux/files/4338099/tmux.txt)
 - logs from `$ tmux -vv -Lx -f/dev/null`:

     [tmux-client-7861.log](https://github.com/tmux/tmux/files/4338109/tmux-client-7861.log)
     [tmux-out-7863.log](https://github.com/tmux/tmux/files/4338110/tmux-out-7863.log)
     [tmux-server-7863.log](https://github.com/tmux/tmux/files/4338111/tmux-server-7863.log)

Tmux didn't behave like that in the past, and Vim doesn't behave like that either in visual mode, so it's probably a regression.  I tried to bisect it; it could have started from any of these commits:

    8be179de4669a76464d664d9af6b3301ca3f286d
    f65b9c0d36e40ded66d4366b473cc2529e1aa8f8
    ccd24c9cb242b736aa4431ed002ccdc491c49b92

But I suspect this is [the relevant one](https://github.com/tmux/tmux/commit/f65b9c0d36e40ded66d4366b473cc2529e1aa8f8).

**Comment by topcat001** [comment]
This is very interesting, thanks for reporting it! If @nicm doesn't mind I'll take a look at it.

**Comment by nicm** [comment]
Go for it

**Comment by topcat001** [comment]
I have found the issue, and a fix. Will create a PR soon. Thanks for the detailed test case! With this fix the behaviour is the same as tmux-3.0a (tested on Arch Linux and macos Catalina).

**Comment by lacygoill** [comment]
The test case is fixed, but the overall issue is still present.

Here is another MWE:

    printf "a\nb\nc\nd\n"
    tmux copy-mode \; send -X -N4 cursor-up \; send -X select-line \; send -X cursor-down \; send -X other-end \; send -X cursor-up \; send -X other-end

Expected behavior: the 3 lines `b`, `c` and `d` should be selected.
Actual behavior: the 2 lines `b` and `c` are selected.

In fact, it's worse now; after you use `other-end`, and you move the end of the selection in the direction of the other end, at one point, you end up controlling the latter.  That's not what Vim does, nor what tmux did in the past.

**Comment by topcat001** [comment]
Thanks for the detailed feedback. I understand the issue. It's a little tricky to add this feature while keeping existing behaviour so the feedback helps a lot.

The good news is that I think we can fix this, given the cleanup we did already. Let's discuss this further in a new PR I'll create to address this.

**Comment by topcat001** [comment]
Hi, please test this patch and see if it solves the issue, thanks!

[git-diff.txt](https://github.com/tmux/tmux/files/4356476/git-diff.txt)

**Comment by lacygoill** [comment]
After playing with the patch a little, I haven't been able to reproduce anything which is unexpected, so I think it fixes the issue entirely; thank you very much.
