### ISSUE TITLE
[Request] bind-key -T choose-tree

### ISSUE THREAD

**Issue by forgetmenotz** [tmux/tmux#2118]
I realize this issue was closed soon after a specific area was resolved; and although the original subject of the request was quickly dismissed, given that it was not really discussed last year, I hope it can be considered a new issue.

I don't use the standard vim binds, but IJKL (o for insert), similar to WASD - so obviously I want these keys to work in choose-tree. I often use non standard keybinds, like instead of a tmux prefix I use sxhkd to bind a two key sequence to switch tmux to key-table sequences. That's the great thing of oss of course. 

With that in mind, I will attempt to make these changes, but I only recently discovered choose-tree and it just seems like the best feature of tmux to me in terms of workflow...so I was just wondering if it was regarded as a bad idea or could be considered. I think it would useful to have customizable key binds.

**Comment by nicm** [comment]
tmux used to support changing the keys in the choose modes but it is a lot of code for something barely anyone wants to do so I do not want to bring it back. There are a couple of things you could do:

- send-keys works in modes (except copy mode), so you can bind your keys like this:
   ~~~~
   bind -n U if -F '#{m/r:(tree|client|buffer)-mode,#{pane_mode}}' 'send Up' 'send U'
   ~~~~
- Patch tmux to use the keys you want, look at mode-tree.c:mode_tree_key for the common keys and the individual key function in window-{tree,buffer,client}.c for the rest.

**Comment by forgetmenotz** [comment]
Send keys, of course. That sorted it perfectly. That example is a good insight into the format arguments as well. Awesome! Thank you thank you.

**Comment by nicm** [comment]
Great stuff.
