### ISSUE TITLE
Regression in 2.0 and above

### ISSUE THREAD

**Issue by 5paceToast** [tmux/tmux#212]
1.9a is currently standards compliant.
However, 2.0 and above is no longer possible to compile with [musl](https://github.com/cloudius-systems/musl) due to glibc-isms.

The following are causing problems:
- <sys/cdefs.h> is not meant to be used by applications (as it is an implementation detail, see [this](http://wiki.musl-libc.org/wiki/FAQ#Q:_I.27m_trying_to_compile_something_against_musl_and_I_get_error_messages_about_sys.2Fcdefs.h)). In this case you don't seem to be doing anything but that, so that's fairly easy to patch out.
- <sys/queue.h> is a self-contained header-only library. Musl does not include it [due to this](http://wiki.musl-libc.org/wiki/FAQ#Q:_why_is_sys.2Fqueue.h_not_included_.3F). It is fully self-contained, so outright referencing it (e.g the "latest" git variant from [here](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=misc/sys/queue.h;hb=HEAD) is fine. Moreover, after outright removing it from the includes, tmux seems to be functioning just fine, and compiled correctly. Is it even being used?

Here's a [tentative patch](http://sprunge.us/YQhK?diff) to fix all abovementioned issues (compiles and starts up fine, but I have not done any tests (make check apparently needs nothing done, so I'm assuming no tests are around to be performed) beyond simply starting it up and running a couple of tentative commands.

**Comment by nicm** [comment]
Well, they are not glibc-isms, this code comes from OpenBSD. Also you are presumably not talking about 2.0 and above, because proc.c only appeared after 2.1.

But we can fix these anyway. proc.c should not have sys/queue.h in portable - it is definitely being used, but a substitute is available, so we can remove the #include.

And we can just remove the DECLS stuff entirely in vis.h, it will never be used from C++.

**Comment by nicm** [comment]
Actually, I lie, proc.c doesn't need sys/queue.h in portable, because it doesn't include imsg.h, but in any case it can be removed.

I have changed these now, thanks.

**Comment by 5paceToast** [comment]
2.0 and 2.1 failed to compile, but I only investigated into current git.
Only one regression may have been present in 2.0 (or maybe it had yet another that has gotten patched in 2.1+). Either way, it compiles and functions normally now.
