### ISSUE TITLE
Handle gracefully a non-existing default-shell

### ISSUE THREAD

**Issue by dbdr** [tmux/tmux#2120]
When the value of `default-shell` is not an existing executable, tmux just exits without an explanation:

```
$ tmux set-option -g default-shell /does-not-exist
$ tmux
[exited]
$
```

It would be nice to get some error message about it, maybe something like:
`The value of default-shell is '/foo' which is not a valid shell`.

Maybe more importantly, I can envision a situation where someone set tmux as their login shell, or automatically start it. In that case, if something goes wrong (e.g. shell package deleted by accident, configuration copied from another system, ...) they might be locked out of their system. Would it make sense to try `/bin/sh` if default-shell does not exist?

Tested with tmux 2.8 on Linux.

PS: thanks for your work on tmux, fantastic software!

**Comment by nicm** [comment]
tmux can't really tell why a pane has exited, only that it has, there is no general way to tell when a pane exits whether the user intended it to or not.

**Comment by dbdr** [comment]
There must be code that fetches the value of `default-shell` and starts a process for it. Couldn't that code check that the file exists and is executable?

**Comment by nicm** [comment]
Yes, we already check if it is set to tmux. So we could replace it with /bin/sh if it was invalid as well. But we can't warn about it.

**Comment by nicm** [comment]
Well, we can actually because tmux won't be exiting.

**Comment by nicm** [comment]
Try this please against master: [x.diff.txt](https://github.com/tmux/tmux/files/4342350/x.diff.txt)

**Comment by dbdr** [comment]
Wow that's fast! :)

I built master with the patch. It does use /bin/sh which is great. However I don't see the warning, is it supposed to be printed on screen? (no pun intended)

**Comment by nicm** [comment]
You will only see a warning when the server is started, make sure you kill it entirely and set default-shell in .tmux.conf.

**Comment by nicm** [comment]
Here is a better change which does the check when the option is set: [y.diff.txt](https://github.com/tmux/tmux/files/4343039/y.diff.txt)

**Comment by dbdr** [comment]
I just tried y.diff.txt, I see the error message when I start a new server, and also when I source tmux.conf.

Also, now it uses $SHELL instead of /bin/sh.

Looks good to me, thanks!

**Comment by nicm** [comment]
Applied now, thanks!
