### ISSUE TITLE
Missing configure check for ncurses.h?

### ISSUE THREAD

**Issue by dbdr** [tmux/tmux#2121]
I tried building tmux from master (with the patch from #2120). ./autogen.sh and ./configure succeed, but then make fails with:
```
tty-term.c:24:10: fatal error: ncurses.h: No such file or directory
 #include <ncurses.h>
```
That's fixed after I installed libncurses-dev, so no big deal, but is this expected? My understanding is that such missing dependencies are supposed to be caught earlier, not during make. Is there a check that is missing in the autogen/configure stages?

**Comment by nicm** [comment]
If you install the ncurses libraries but don't have the headers it will detect ncurses but then not build. The failure is clear enough it doesn't matter if it during configure or make, there is no rule that says configure has to be the thing that fails.

**Comment by dbdr** [comment]
OK, fair enough. For libevent it was configure that failed (indeed it seems I did not have it at all, not just the headers missing). I found this more friendly. I tend to consider configure failing as "your system is missing some dependency", while make failing would be a bug in the code. But that might not be the standard view, and it's definitely minor. Closing.

**Comment by nicm** [comment]
Right, but your package maintainers chose to split ncurses into several packages, normally it comes as one piece - if the library exists so do the headers. We can't test for everything in configure. Probably the .pc file is in the -dev package as well so tmux can't find it with pkg-config and falls back to looking for the libraries itself.

Saying that, I don't mind having a check for the headers as well if you want to open a PR. It minds checking for ncurses.h or curses.h depending whether tmux finds ncurses, curses or terminfo.

**Comment by dbdr** [comment]
I think it's pretty common in the Linux (at least Debian and derivatives) world to split the headers in a separate -dev package. Probably it's a cultural difference with BSD and possibly other Linux distributions. But it's not a big deal.
