### ISSUE TITLE
cursor shape not set as expected when entering/leaving insert mode in (N)Vim

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2122]
### Issue description

I have configured Vim and Nvim to change the shape of the cursor from a full block in normal mode, to a vertical line in insert mode.  It works outside tmux; it also worked inside tmux until recently, but not anymore.

To reproduce, write this in `/tmp/vimrc`:

    set noshowmode
    set showcmd
    set rtp-=~/.vim
    set rtp-=~/.vim/after
    let &t_EI = "\e[2 q"
    let &t_SI = "\e[6 q"
    let &t_ti = "\e[2 q"..&t_ti
    let &t_te = "\e[2 q"..&t_te

Then start tmux with no config:

    tmux -Lx -f/dev/null

Then start Vim with the previous minimal vimrc:

    vim -Nu /tmp/vimrc

The cursor's shape is a full block, which is expected.

Press `i` to enter insert mode; the cursor's shape is reset to a vertical line, which is still expected.
Press `abc` to enter some text.
Press `Escape` to get back to normal mode.

The cursor moves back one column back (still expected), but it keeps its vertical line shape, which is not expected.  It should have been reset to a full block.

Press `h` to move the cursor one column backward:  the cursor's shape is finally reset to a full block.  This is expected, but too late.

### Required information

 - `$ tmux -V`: tmux next-3.2, commit cae2dfc95aef190523112a95c16d22311de7320c
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:

    [tmux-client-1933.log](https://github.com/tmux/tmux/files/4343297/tmux-client-1933.log)
    [tmux-out-1938.log](https://github.com/tmux/tmux/files/4343298/tmux-out-1938.log)
    [tmux-server-1938.log](https://github.com/tmux/tmux/files/4343299/tmux-server-1938.log)

 - [`$ tmux info`](https://github.com/tmux/tmux/files/4343294/tmux.info.txt)

Nvim suffers from a similar issue.  Although, the behavior seems more unpredictable.
But overall, it's worse; sometimes, the cursor's shape is not changed at all (from normal mode to insert mode), and when it is, it can keep its insert mode shape while in normal mode much longer than in Vim.

Tmux didn't behave like that in the past; it's a regression caused by 37b7a29ccac2e8f37a37b8c4ad8e9ceedee25ee9.

**Comment by lacygoill** [comment]
> Nvim suffers from a similar issue.  Although, the behavior seems more unpredictable.
> But overall, it's worse; sometimes, the cursor's shape is not changed at all (from normal mode to insert mode), and when it is, it can keep its insert mode shape while in normal mode much longer than in Vim.

Actually, I think Nvim needs this setting:

    set -as terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[2 q'

I forgot about it during my tests; so, I'm not sure what I wrote about Nvim is entirely correct.
Nevertheless, Nvim is affected by the issue, even with this setting, while everything was working fine before 37b7a29ccac2e8f37a37b8c4ad8e9ceedee25ee9.

**Comment by nicm** [comment]
Try just deleting these two lines:
~~~~
--- tty.c       16 Mar 2020 10:49:06 -0000      1.344
+++ tty.c       17 Mar 2020 12:12:58 -0000
@@ -668,8 +668,6 @@ tty_update_mode(struct tty *tty, int mod
                mode &= ~MODE_CURSOR;

        changed = mode ^ tty->mode;
-       if (changed == 0)
-               return;
        log_debug("%s: update mode %x to %x", c->name, tty->mode, mode);

        if (changed & MODE_BLINKING) {

**Comment by lacygoill** [comment]
I think this patch fixes the issue entirely; thank you very much for the quick fix.

**Comment by nicm** [comment]
Applied now, thanks!
