### ISSUE TITLE
stuck on command-prompt when entering copy mode while a special character is present on the screen of the st terminal

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2124]
### Issue description

Entering copy mode while some unicode character is present on the screen makes tmux enter the command prompt; sometimes, I can't find a way to leave it.

To reproduce, compile the latest code of the `st` terminal:

    git clone https://git.suckless.org/st && cd st && make

Start an st terminal:

    ./st

Start tmux with no config:

    tmux -Lx -f/dev/null

Run this `curl(1)` command:

    curl -Ls https://0x0.st/iarD.txt

Press `C-b [` to enter copy mode.

The command prompt is automatically entered.
And there doesn't seem to be a way to leave it; at least none that I could find (I tried `Esc`, `C-c`, `C-\`, `C-d`).

---

If you start tmux with this minimal `tmux.conf`:

    # in /tmp/tmux.conf
    bind -T copy-mode-vi ? command-prompt -ip '?' { send -X search-backward-incremental '%%%' }

    $ EDITOR=vim tmux -Lx -f/tmp/tmux.conf

Then, the command prompt is still automatically entered; however, 2 things change:

   - as soon as you insert a character, the prompt is indefinitely populated with the 2-characters sequence `6c`
   - if you keep pressing `C-c` long enough, eventually, you can leave the prompt

![gif](https://user-images.githubusercontent.com/8505073/77092859-7eee8700-6a0a-11ea-9c57-05ac00938c15.gif)

### Required information

 - `$ tmux -V`: tmux next-3.2, commit c15396459b4f73ac81e9947d242b695c0fc1dedb
 - `$ uname -sp`: Linux x86_64
 - terminal: st
 - `$TERM` outside tmux: st-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/tmp/tmux.conf`: [tmux_logs.tar.gz](https://github.com/tmux/tmux/files/4355814/tmux_logs.tar.gz)
 - `$ tmux info`: [tmux.info.txt](https://github.com/tmux/tmux/files/4355864/tmux.info.txt)
 - `$ infocmp -1x`: [infocmp.txt](https://0x0.st/iazo.txt)

---

I think the character which triggers the issue is:

    	SINGLE CHARACTER INTRODUCER

---

I think there is a bug in st, because as soon as `curl(1)` writes its output on the terminal, the sequence `6c` is unexpectedly written on the shell prompt, and I can't reproduce in xterm.  But I suspect that the bug in st triggers another bug in tmux, because I can't reproduce the issue on old tmux versions.

According to `$ git bisect`, the change should have started from one of these commits:

     04eee2410df4a85005c9562db13a1fec93d7c2e4
     835a6c0cf088437e318783c96b142c7dc26c290f
     8457f54edcdfdf7b6e48a291808135258abfe5b8

**Comment by nicm** [comment]
This is a problem with st, it is sending DA responses (`\033[6c`) when it gets this Unicode character. It is not a bug in tmux, the reason you don't see it in older versions is because tmux processed all of the DA responses, now it only processes the first one.

**Comment by lacygoill** [comment]
Ok, thank you very much for the explanation.
