### ISSUE TITLE
"cursor-right" selects a word after "select-word" has been used

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2126]
### Issue description

In copy mode, `cursor-right` selects a word after `select-word` has been used.

To reproduce, run these shell commands:

    tmux -Lx -f/dev/null
    echo 'foo bar baz'
    tmux copy-mode \; send -X search-backward '^foo' \; send -X select-word \; send -X cursor-right

Expected result:

`foo` and the following space are selected; the cursor is drawn on the space.

Actual result:

`foo`, the following space, and `bar` are selected; the cursor is drawn on the space.

### Required information

 - `$ tmux -V`: tmux next-3.2, commit 5b71943f8993e3778d5337a1185efd08f09633ee
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:
    [tmux-client-7613.log](https://github.com/tmux/tmux/files/4360343/tmux-client-7613.log)
    [tmux-out-7615.log](https://github.com/tmux/tmux/files/4360345/tmux-out-7615.log)
    [tmux-server-7615.log](https://github.com/tmux/tmux/files/4360346/tmux-server-7615.log)
 - `$ tmux info`: [tmux.info.txt](https://github.com/tmux/tmux/files/4360339/tmux.info.txt)

Vim doesn't behave like that, nor did Tmux in the past; the change started from bd0342b0a7ac4b5dc00ffc9cce7f9b0fbeb7ec91.

**Comment by nicm** [comment]
This is intentional when you do select-word or select-line you enter word or line selection mode. Do begin-selection/next-word if you want to stay in character selection mode.

**Comment by lacygoill** [comment]
So, the equivalent of the old `select-word` is:

    previous-word
    begin-selection
    next-word-end

This should work; although `previous-word` is wrong if the cursor is already on the first character of a word.  How to detect that it is?

**Comment by lacygoill** [comment]
Never mind, I'll try that:

    cursor-right
    previous-word
    begin-selection
    next-word-end
