### ISSUE TITLE
Tmux compile issue

### ISSUE THREAD

**Issue by descendingnerdliness** [tmux/tmux#2127]
Kubuntu 18.04 After downloading the master, compiling results in the following.
```
/bin/bash ./etc/ylwrap cmd-parse.y y.tab.c cmd-parse.c y.tab.h `echo cmd-parse.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output cmd-parse.output -- yacc  
./etc/ylwrap: line 175: yacc: command not found
Makefile:848: recipe for target 'cmd-parse.c' failed
make: *** [cmd-parse.c] Error 127

```
Similarly, tmux-3.1-rc3 yields this compile result:
```
/bin/bash ./etc/ylwrap cmd-parse.y y.tab.c cmd-parse.c y.tab.h `echo cmd-parse.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output cmd-parse.output -- yacc  
./etc/ylwrap: line 175: yacc: command not found
Makefile:847: recipe for target 'cmd-parse.c' failed
make: *** [cmd-parse.c] Error 127
```
I have installed the two prerequisites. Configure seemed to complete normally. 
Please tell me what else I am missing?

* Platform (`uname -sp`).
Linux x86_64

**Comment by nicm** [comment]
You now also need to install `bison`. I'll add it to the instructions.

**Comment by descendingnerdliness** [comment]
OK, Thanks! 
bisonc++ 6.01 is in the Ubuntu 18.04 repo. Will that do?

**Comment by nicm** [comment]
No that is for C++. You should definitely have bison, try:
~~~~
apt-get install bison
~~~~
If that doesn't work, try byacc instead of bison.

**Comment by descendingnerdliness** [comment]
It ran with the Ubuntu versioning of bison 2:3.0.4.dfsg-1build1.
Thanks!
