### ISSUE TITLE
Horizontal and vertical window splitting are reversed

### ISSUE THREAD

**Issue by ThomS8312** [tmux/tmux#213]
The <code>split-window -h</code> command splits the window vertically instead of horizontally, and <code>split-window -v</code> splits it horizontally instead of vertically.

**Comment by nicm** [comment]
Haha.

**Comment by ThomS8312** [comment]
I don't understand the response...can you explain?

**Comment by nicm** [comment]
It's fine as it is.

**Comment by ailin-nemui** [comment]
Some people/editors think of "horizontal" as "the split results in a windows vertically split, so the dividing line looks like the horizon"

**Comment by orebokech** [comment]
To avoid this (very common) confusion, in Emacs the functions were renamed: `split-window-vertically` became `split-window-below` and `split-window-horizontally` became `split-window-right`.

**Comment by ThomS8312** [comment]
You mean that's intentional? The man page states:
<pre>
...Create a new pane by splitting target-pane: -h does a horizontal split
and -v a vertical split...
</pre>

The "split" is the line dividing the window. Either that line goes left to right (like the x-axis, which is a horizontal division/"split") or up and down (like the y-axis, which is a vertical division/"split").

Horizontal is defined as "parallel to the plane of the horizon; level; flat" and vertical is "at right angles to the horizon; perpendicular; upright". Those are <a href="http://dictionary.reference.com/browse/horizontal">dictionary</a> <a href="http://dictionary.reference.com/browse/vertical">definitions</a> (British Dictionary). Tmux even has the "h" and the "v" as the letters for those options making it even more misleading. They go directly against the meaning of the words they are supposed to represent.

Why the reluctance in making these commands match their definition?

**Comment by nicm** [comment]
You are misinformed. The "split" is not the line dividing the window, and neither we nor the dictionary define it as so. "Split" means the act of splitting the window into two. When you split horizontally, you divide into two along the horizontal axis; vertically, along the vertical axis. The meaning of these flags is not going to change.

**Comment by ThomS8312** [comment]
I see. A line created on the x-axis will be vertical and a line created on the y-axis will be horizontal.

Neither of us is "wrong", but since my perspective is very common, it's reflective of what's normally expected even though your perspective is correct at a technical level. My perspective sees it in the same sense as a horizontal/vertical incision, so the split (line) wouldn't go <i>along</i> the axis, the split would <i>be</i> a representation of the axis itself.

Tmux's method, though correct, goes against the grain compared to other terminal splitting applications I'm use to. Without knowing the reason behind tmux's behavior, it's easy to conclude that something is wrong.

**Comment by cipri-tom** [comment]
I searched everywhere why `split-window -h` doesn't do a "horizontal" split ... Until I thought of checking the `-v` part and saw they are "reversed".

The emacs renaming is a good, less confusing, choice of words
