### ISSUE TITLE
Cross compiling issue: No rule to make target 'compat/forkpty-linux.c'

### ISSUE THREAD

**Issue by midiwidi** [tmux/tmux#2132]
I'm trying to cross compile tmux for a arm-uclinux (cortex-m3) target on my x86_64 linux host machine.

I managed to cross compile static libraries of libevent and ncurses and installed them into the directory /home/midiwidi/Downloads/tmux_workdir. This is the content of the directory.

```
/tmux_workdir/
|-- bin
|   |-- captoinfo -> tic
|   |-- clear
|   |-- event_rpcgen.py
|   |-- infocmp
|   |-- infotocap -> tic
|   |-- ncurses6-config
|   |-- reset -> tset
|   |-- tabs
|   |-- tic
|   |-- toe
|   |-- tput
|   `-- tset
|-- include
|   |-- evdns.h
|   |-- event.h
|   |-- event2
|   |   |-- buffer.h
|   |   |-- buffer_compat.h
|   |   |-- bufferevent.h
|   |   |-- bufferevent_compat.h
|   |   |-- bufferevent_struct.h
|   |   |-- dns.h
|   |   |-- dns_compat.h
|   |   |-- dns_struct.h
|   |   |-- event-config.h
|   |   |-- event.h
|   |   |-- event_compat.h
|   |   |-- event_struct.h
|   |   |-- http.h
|   |   |-- http_compat.h
|   |   |-- http_struct.h
|   |   |-- keyvalq_struct.h
|   |   |-- listener.h
|   |   |-- rpc.h
|   |   |-- rpc_compat.h
|   |   |-- rpc_struct.h
|   |   |-- tag.h
|   |   |-- tag_compat.h
|   |   |-- thread.h
|   |   |-- util.h
|   |   `-- visibility.h
|   |-- evhttp.h
|   |-- evrpc.h
|   |-- evutil.h
|   `-- ncurses
|       |-- curses.h
|       |-- cursesapp.h
|       |-- cursesf.h
|       |-- cursesm.h
|       |-- cursesp.h
|       |-- cursesw.h
|       |-- cursslk.h
|       |-- eti.h
|       |-- etip.h
|       |-- form.h
|       |-- menu.h
|       |-- nc_tparm.h
|       |-- ncurses.h -> curses.h
|       |-- ncurses_dll.h
|       |-- panel.h
|       |-- term.h
|       |-- term_entry.h
|       |-- termcap.h
|       |-- tic.h
|       `-- unctrl.h
|-- lib
|   |-- libevent.a
|   |-- libevent.la
|   |-- libevent_core.a
|   |-- libevent_core.la
|   |-- libevent_extra.a
|   |-- libevent_extra.la
|   |-- libform.a
|   |-- libform_g.a
|   |-- libmenu.a
|   |-- libmenu_g.a
|   |-- libncurses++.a
|   |-- libncurses++_g.a
|   |-- libncurses.a
|   |-- libncurses_g.a
|   |-- libpanel.a
|   |-- libpanel_g.a
|   |-- pkgconfig
|   |   |-- libevent.pc
|   |   |-- libevent_core.pc
|   |   `-- libevent_extra.pc
|   `-- terminfo -> ../share/terminfo
`-- share
    |
    ...
```

I've already gotten over different hurdles with tmux like unnamed unions which my c99 compiler doesn't support. Now I'm getting the error 

`make: *** No rule to make target 'compat/forkpty-linux.c', needed by 'compat/forkpty-linux.o'.  Stop.`

compat/forkpty-linux.c doesn't exist and I tried different things like disabling pkg-config but I cant get it to compile. I think forkpty is included in libutils, so I tried to specify include and library path of uClibc in my cross toolchain, but it didn't help either.

1. What could I do to solve the compile issue?
2. Is forkpty needed for tmux? The cortex-m3 is a MMU-less sytem and doesn't have fork(), only vfork(), and might also not have forkpty (I don't know yet).

These are the environment variables and configure parameters I used
```
# if not already done
cd /home/midiwidi/My_Projects/Git_CloneDir/CSIROSat-1/software/linux-m2s
source ACTIVATE.sh
cd /home/midiwidi/Downloads

git clone https://github.com/tmux/tmux.git

cd tmux

./autogen.sh

export CFLAGS='-O2 -mcpu=cortex-m3 -mthumb -std=c99 -I/home/midiwidi/Downloads/tmux_workdir/include -I/home/midiwidi/Downloads/tmux_workdir/include/ncurses'
export CC=arm-uclinuxeabi-gcc
export LDFLAGS='-mcpu=cortex-m3 -mthumb -L/home/midiwidi/Downloads/tmux_workdir/lib'
export STRIP=arm-uclinuxeabi-strip
export PKG_CONFIG=/bin/false

export LIBTINFO_CFLAGS='-O2 -mcpu=cortex-m3 -mthumb -std=c99 -I/home/midiwidi/Downloads/tmux_workdir/include -I/home/midiwidi/Downloads/tmux_workdir/include/ncurses'
export LIBTINFO_LIBS='-lncurses'

export LIBS='-L/home/midiwidi/Downloads/tmux_workdir/lib -lncurses -lcrypt -lutil  -levent -lrt'

patch < ../tmux_patch/tmux_h.patch
patch < ../tmux_patch/grid_c.patch
patch < ../tmux_patch/input_c.patch
patch < ../tmux_patch/screen-write_c.patch

./configure --build=x86_64 --host=arm-uclinux --enable-static --prefix=/home/midiwidi/Downloads/tmux_workdir

make
```

Here is the configure script log file
[config.log](https://github.com/tmux/tmux/files/4369842/config.log)

Kind regards,
Markus Wiedemann

**Comment by nicm** [comment]
glibc has forkpty (either in libc or in libutil) so there is no forkpty-linux.c, you will need to either find it or write your own.

**Comment by midiwidi** [comment]
Thanks for your reply Nicholas. 
What I don't understand is how the file (forkpty-linux.c) is supposed to get into the tmux/compat directory. There are already similar files like forkpty-aix.c or forkpty-sunos.c. Is the configure script supposed to locate it somewhere in the system and to copy it into the tmux/compat directory?

**Comment by nicm** [comment]
configure looks for forkpty in libutil. If it exists then it is used. If it
doesn't exist, it assumes there will be a file for the platform in compat/.
For example AIX had no forkpty so it uses compat/forkpty-aix.c. Linux
normally has forkpty so there is no need for forkpty-linux.c. You will not
be able to build tmux without a working forkpty, either one from libc or
libutil or a compatibility one which you will have to write.

**Comment by nicm** [comment]
If your platform has eg vfork and posix_openpt, you can write a forkpty
that uses them. Or it may be it needs to do some dance using the ptm/pty
nodes in /dev.

**Comment by nicm** [comment]
Well actually vfork may not work without some changes to the places tmux
calls forkpty to stop it looking at bits of memory from the parent process
before calling exec.

**Comment by midiwidi** [comment]
Thanks for those explanations and hints. It's much clearer now. I'll look into it.
