### ISSUE TITLE
How to only use mouse scroll and select, but not copy?

### ISSUE THREAD

**Issue by fred214** [tmux/tmux#2133]
Hi, I'm a Xshell user, when using tmux I only want to use mouse scroll and select. and use Xshell copy instead of.
So how can I disable copy action when I set "set-option -g mouse on"

Thanks a lot

**Comment by nicm** [comment]
tmux can't choose, it either takes all events or none. Most terminals let you bypass application mouse by holding Shift or some other modifier key.

**Comment by fred214** [comment]
@nicm Thanks for your reply.  I have find a workaround.
```
Restrict Mouse Use at Terminal with Shift Key
Some applications such as ‘vi’ and ‘mc’ can use mouse click and drag to make a selection or
change the directory. When this option is selected, press the Shift key while using the mouse and
Xshell uses the mouse input to perform actions such as making selection on the screen
```
