### ISSUE TITLE
how do I reset `tmux set-options -g xxx` to default values?

### ISSUE THREAD

**Issue by JiaRu2016** [tmux/tmux#2135]
### Issue description

I run `tmux set-option -g default-command bash` to try to solve some problems but I reget. How can I reset the `default-command` to its orginal value?  I could not find any evidence in `~/.tmux.conf` file, it seems that `tmux set-option -g` did not modify my `~/.tmux.conf`

A more general question, what's the "medicine for regret" of `set-option -g` ?

### Required information

$ tmux -V
tmux 2.6

$ uname -sp
Linux x86_64

$ echo $TERM
xterm-256color

$ tmux kill-server; tmux -vv new
lost server

**Comment by nicm** [comment]
Kill and restart tmux, or use `-u`: `tmux set -gu default-command`.

**Comment by JiaRu2016** [comment]
> Kill and restart tmux, or use `-u`: `tmux set -gu default-command`.

it works, thanks!
