### ISSUE TITLE
Weird backspace behavior in zsh

### ISSUE THREAD

**Issue by jrwrigh** [tmux/tmux#2137]
### Issue description

When using `set -g default-terminal "tmux-256color"` and zsh, the backspace character will create spaces instead of deleting characters.

Below is a demonstration of the behavior of typing 1234 and backspacing 4 times inside and outside of `tmux`:
![Peek 2020-03-27 13-01](https://user-images.githubusercontent.com/20801821/77790803-123b4400-702b-11ea-81b3-568f8e26a8d7.gif)

### Required information
* tmux version (`tmux -V`). 3.0a and 2.9
* Platform (`uname -sp`). `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`). 
Outside: `xterm-256color` for xfce4-terminal, `konsole-256color` for Konsole, and `xterm` for URXVT
Inside: `tmux-256color`

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[Filebin link here](https://filebin.net/ux99sp4ncta4kmq0) since the server log is 12k lines long.

### Notes
* I'm doing this to try and get italics working in my tmux session as [described in the FAQ](https://github.com/tmux/tmux/wiki/FAQ#i-dont-see-italics-or-italics-and-reverse-are-the-wrong-way-round)
* I originally ran into issues identical to this [SO question](https://stackoverflow.com/questions/45931164/duplicated-characters-and-non-updating-input-using-tmux-in-zsh), but found the above behavior for a completely blank `.zshrc`. I'm hoping that solving this problem will also solve the SO problem.
* Relevant config files:
`.tmux.conf`: `set -g default-terminal "tmux-256color"`
`.zshrc` is blank
* The issue is *not* present with bash
* The issue does not effect vim/nvim. Backspace works normally there
* I am able to get italics working for when using `tmux-256color` inside tmux

### Things I've tried

* Setting up a manual `tmux-256color` terminfo file, as suggested in #597. This did not change the effect, in addition to already having a valid `tmux-256color` terminfo file present
* Three different terminals (for three different `$TERM` definitions outside tmux): xfce4-terminal, konsole, and urxvt

**Comment by nicm** [comment]
What do `infocmp tmux-256color` and `stty -a` show outside tmux?

**Comment by jrwrigh** [comment]
`infocmp tmux-256color`:
```
portal1% infocmp tmux-256color
#	Reconstructed via infocmp from file: /users/jrwrigh/.local/share/terminfo/t/tmux-256color
tmux-256color|tmux with 256 colors,
	am, hs, km, mir, msgr, xenl,
	colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
	acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=\r,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
	cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
	dl=\E[%p1%dM, dl1=\E[M, dsl=\E]0;\007, ed=\E[J, el=\E[K,
	el1=\E[1K, enacs=\E(B\E)0, flash=\Eg, fsl=^G, home=\E[H,
	hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
	il=\E[%p1%dL, il1=\E[L, ind=\n, indn=\E[%p1%dS,
	invis=\E[8m, is2=\E)0, kDC=\E[3;2~, kEND=\E[1;2F,
	kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D, kNXT=\E[6;2~,
	kPRV=\E[5;2~, kRIT=\E[1;2C, kbs=^H, kcbt=\E[Z, kcub1=\EOD,
	kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA, kdch1=\E[3~,
	kend=\E[4~, kf1=\EOP, kf10=\E[21~, kf11=\E[23~,
	kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q, kf15=\E[1;2R,
	kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\E[1~, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m,
	ri=\EM, ritm=\E[23m, rmacs=^O, rmcup=\E[?1049l, rmir=\E[4l,
	rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
	rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=\E[0%?%p6%t;1%;%?%p1%t;7%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;            5%;%?%p5%t;2%;m%?%p9%t\016%e\017%;,
	sgr0=\E[m\017, sitm=\E[3m, smacs=^N, smcup=\E[?1049h,
	smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m, smul=\E[4m,
	tbc=\E[3g, tsl=\E]0;, vpa=\E[%i%p1%dd,
```

`stty -a`:
```
portal1% stty -a
speed 38400 baud; rows 62; columns 238; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke
```

**Comment by nicm** [comment]
Try building your own tmux-256color but changing kbs=^H to kbs=^? and see
if it helps.

**Comment by jrwrigh** [comment]
No dice (no change in behavior). I also confirmed via `infocmp` that the change in `kbs` did stick:

```
portal1% infocmp                                                                                                                                                                                                                             
#       Reconstructed via infocmp from file: /users/jrwrigh/.local/share/terminfo/t/tmux-256color
tmux-256color|tmux with 256 colors,
        am, hs, km, mir, msgr, xenl,
        colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
        acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
        cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, dsl=\E]0;\007, ed=\E[J, el=\E[K,
        el1=\E[1K, enacs=\E(B\E)0, flash=\Eg, fsl=^G, home=\E[H,
        hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
        il=\E[%p1%dL, il1=\E[L, ind=\n, indn=\E[%p1%dS,
        invis=\E[8m, is2=\E)0, kDC=\E[3;2~, kEND=\E[1;2F,
        kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D, kNXT=\E[6;2~,
        kPRV=\E[5;2~, kRIT=\E[1;2C, kbs=^?, kcbt=\E[Z, kcub1=\EOD,
        kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA, kdch1=\E[3~,
        kend=\E[4~, kf1=\EOP, kf10=\E[21~, kf11=\E[23~,
        kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q, kf15=\E[1;2R,
        kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
        kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
        kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
        kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
        kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
        kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
        kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
        kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
        kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
        kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
        kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
        kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
        kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
        kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
        kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\E[1~, kich1=\E[2~,
        kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        kri=\E[1;2A, nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m,
        ri=\EM, ritm=\E[23m, rmacs=^O, rmcup=\E[?1049l, rmir=\E[4l,
        rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
        rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        sgr=\E[0%?%p6%t;1%;%?%p1%t;7%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;            5%;%?%p5%t;2%;m%?%p9%t\016%e\017%;,
        sgr0=\E[m\017, sitm=\E[3m, smacs=^N, smcup=\E[?1049h,
        smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m, smul=\E[4m,
        tbc=\E[3g, tsl=\E]0;, vpa=\E[%i%p1%dd,
```

**Comment by nicm** [comment]
What does stty -a show inside tmux?

Where did you get this tmux-256color? Copied the default one you have
installed already?

**Comment by krader1961** [comment]
> No dice (no change in behavior). I also confirmed via infocmp inside tmux that the change in kbs did stick:

Did you start a new shell after compiling the updated terminfo file? Any existing zsh instance will continue to use the old definition.

**Comment by jrwrigh** [comment]
`stty -a` inside tmux:
```
portal1% stty -a                                                                                                                                                                                                                             
speed 38400 baud; rows 61; columns 238; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke
```

> Where did you get this tmux-256color? Copied the default one you have
installed already?

This was an edit of the `tmux-256color` that it was trying to load already. I installed it myself, but it's been awhile. According to the script I used to install it, it's probably from installing `ncurses-6.1`.

**Comment by jrwrigh** [comment]
> Did you start a new shell after compiling the updated terminfo file? Any existing zsh instance will continue to use the old definition.

Yep. Killed the whole ssh session and restarted it.

**Comment by nicm** [comment]
There are only two ways a program could work out what backspace is and that is from terminfo and from termios and they are both `^?` which is `\177`.

Or it could guess from `TERM`, but space seems like an odd choice if it is doing that.

Anyway, when tmux sends backspace, zsh is sending a space and nothing more:
~~~~
1585335665.785579 writing key 0x10000085 (BSpace) to %0
1585335665.785587 found key 0x10000085: "\177"
...
1585335665.785739 input_parse_buffer: %0 ground, 1 bytes:
1585335665.785747 screen_write_collect_end: 1   (at 13,0)
~~~~
So it does seem like this is a zsh problem.

If this was something happening all the time then everyone would be complaining. Did you try a newer zsh version?

**Comment by jrwrigh** [comment]
I'm not admin on my machine, so I can't easily install newer versions. I've run it on `5.0.7` and `5.7.1` and both have the same behavior. I'll see if there's a way to get any different versions working.

**Comment by nicm** [comment]
This is a zsh issue, to go any further you will need to report it to the zsh developers but I expect they will want you to try the latest version.

**Comment by jrwrigh** [comment]
I just duplicated the setup on my laptop and it works fine.
`tmux`: 3.0a
`zsh`: 5.7.1

`stty -a` is identical between the two, but the terminfos are different:

```
BrickManjaro% infocmp
#       Reconstructed via infocmp from file: /usr/share/terminfo/t/tmux-256color
tmux-256color|tmux with 256 colors,
        am, hs, km, mir, msgr, xenl,
        colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
        acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
        cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, dsl=\E]0;\007, ed=\E[J, el=\E[K,
        el1=\E[1K, enacs=\E(B\E)0, flash=\Eg, fsl=^G, home=\E[H,
        hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
        il=\E[%p1%dL, il1=\E[L, ind=\n, indn=\E[%p1%dS,
        invis=\E[8m, is2=\E)0, kDC=\E[3;2~, kEND=\E[1;2F,
        kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D, kNXT=\E[6;2~,
        kPRV=\E[5;2~, kRIT=\E[1;2C, kbs=^H, kcbt=\E[Z, kcub1=\EOD,
        kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA, kdch1=\E[3~,
        kend=\E[4~, kf1=\EOP, kf10=\E[21~, kf11=\E[23~,
        kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q, kf15=\E[1;2R,
        kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
        kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
        kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
        kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
        kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
        kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
        kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
        kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
        kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
        kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
        kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
        kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
        kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
        kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
        kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\E[1~, kich1=\E[2~,
        kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        kri=\E[1;2A, nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m,
        ri=\EM, ritm=\E[23m, rmacs=^O, rmcup=\E[?1049l, rmir=\E[4l,
        rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
        rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        sgr=\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p5%t;2%;%?%p7%t;8%;m%?%p9%t\016%e\017%;,
        sgr0=\E[m\017, sitm=\E[3m, smacs=^N, smcup=\E[?1049h,
        smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m, smul=\E[4m,
        tbc=\E[3g, tsl=\E]0;, vpa=\E[%i%p1%dd,
```

Only difference is with the `pairs` and `sgr`entries. Note that if try and run `tic` on this terminfo on the remote machine (the one that's having issues), I get a warning/error message:
```
"tmux-256color.terminfo_BrickManjaro", line 5, col 61, terminal 'tmux-256color': limiting value of `pairs' from 0x10000 to 0x7fff
```
Any ideas what that could mean? Or is it just a red herring?

**Comment by jrwrigh** [comment]
version of`tic`: ncurses 6.1.20180127

**Comment by nicm** [comment]
Probably the machines have different ncurses versions, pairs could only be
16 bits until relatively recently. It might even be a compile time option,
I can't remember. This could be an ncurses problem I guess if zsh uses
ncurses.

**Comment by ThomasDickey** [comment]
The warning is normal, and unrelated to backspace behavior.

**Comment by jrwrigh** [comment]
From [this random zsh building guide](https://www.drewsilcock.co.uk/compiling-zsh) (and a few others I saw), it appears that zsh does require ncurses to build.

Regardless, I just built a new version of ncurses (6.2.20200212) and it still isn't working (though that doesn't completely remove that possibility since I didn't build a new zsh with the new ncurses). Trying to build the desktop version of `tmux-256color` still came up with the same error.

---
For the lols, I did a nested tmux session: one at the remote machine (remote1) I've been dealing with, then another one to a different machine (remote2). (so `ssh remote1; tmux new; ssh remote2; tmux new`)

I initially got the same behavior (backspace turning into spaces, as well as the strange character substitutions mentioned in the original StackOverflow question) on remote2's tmux, but that's because remote2 didn't have a `tmux-256color` terminfo.

I copied my *desktop's* `tmux-256color.term` to remote2 and compiled it there. And now everything works on remote2; backspace acts normally, no doubling of characters (when doing fancier .zshrc things), and italics now works.

Here's the kicker:
`tmux -V`: 1.9 
`zsh --version`: 5.0.2
`tic -V`: ncurses 5.9.20130511

So we use old as dirt everything and it suddenly works. Even compiling the new terminfo didn't return errors even through it's ~5 years older. IDK if this is supposed to be surprising, but I found it quite funny.
It also does work with tmux 3.0a, but I found it more humorous that it worked perfectly fine with 1.9.

**Comment by ThomasDickey** [comment]
zsh is using only the low-level interface to terminfo, which "should" give it exactly the data seen by infocmp.  Just recompiling the small chunks shown shouldn't be a problem with tic.  If you recompiled the whole terminfo.src file from ncurses 6.2, using an older version of ncurses -- that wouldn't work well.  Whether it produces a warning message or not doesn't matter.

ltrace might show the return-values from tigetstr, tigetflag and tigetnum.

**Comment by jrwrigh** [comment]
Where would I run `ltrace`?

**Comment by ThomasDickey** [comment]
You'd have to install it of course (works with "any" Linux system, but not installed by default), and then run it to capture calls from zsh, e.g.,

`ltrace -o trace.log zsh`

**Comment by jrwrigh** [comment]
`ltrace` was already installed (version 0.7.3), but there weren't any instances of `tige*` in the logs.

**Comment by ThomasDickey** [comment]
Well (aside from building a comparable configuration and debugging that), no quick answers.

A likely problem is that (in at least one of the stages from your local terminal to the end system), one of the shells/programs expects to send a backspace **character** (^H) and it's being transformed into the backspace **key** (which happens to not be ^H).  Character 127 (^?) doesn't do anything to the *terminal* when you print it, but character 8 (^H) does move the cursor.

tmux gets its sense of backspace from the shell's `erase` value (which you can inspect with `stty -a`).  That happens to be a **key** that you might type on the keyboard, calling it "backspace".  If you're ssh'ing into some remote system which sets that differently, it'll confuse tmux, because tmux expects the "backspace" to be echoed in some way that moves the cursor to the left.  If the remote system doesn't do that, tmux and the shell will disagree on what happened.

**Comment by jrwrigh** [comment]
Well I can't give you access to my remote machine, but if you want any additional logs or for me to check on any other things, let me know. I'll contact my admin to see if he did anything weird when compiling. I had to  request it special, so there may have been some oddities in the installation process.

**Comment by nicm** [comment]
I am closing this because this is not a tmux problem and there is nothing else for me to do here.

**Comment by jrwrigh** [comment]
Fair. I'll update this if I figure out anything.
