### ISSUE TITLE
How to display the last directory of the current path to tmux status bar?

### ISSUE THREAD

**Issue by huyvohcmc** [tmux/tmux#2138]
Edit: with `path/to/dir/` I want to display `dir` on the status bar.

**Comment by nicm** [comment]
Use the basename format modifier `b:`.

**Comment by huyvohcmc** [comment]
Sorry by last directory I mean the current directory: with `path/to/dir/` I want to display `dir` in the status bar. @nicm

**Comment by nicm** [comment]
You will need to do it with a bit of shell script in #() then.

**Comment by jrwrigh** [comment]
Not sure if this is exactly what you mean by "current path", but `${b:pane_current_path}` works just fine for me:

For putting it as the name of the window:
```
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'
```

For having on the left/right status bar:
```
set-option -g status-left '#{b:pane_current_path}'
```

For whatever reason, the `pane_current_path` variable is not on the [OpenBSD documentation page](https://man.openbsd.org/tmux.1). Any ideas why that is? It's still in the repository and I can't find any obvious contact at OpenBSD to double-check with them on it.

**Comment by nicm** [comment]
I'm not sure now either, I thought he wanted b: but then when he said not I
thought he meant second last component which would need a script

pane_current_path is not supported on OpenBSD, there were concerns over its
security when used by default, although I probably didn't need to remove
the format as well.

**Comment by jrwrigh** [comment]
> pane_current_path is not supported on OpenBSD, there were concerns over its
security when used by default, although I probably didn't need to remove
the format as well.

Gotcha. So the current `CONTRIBUTING.md` points to the OpenBSD man page (which doesn't include that option). Not sure if that's what caused the confusion here, but it might be worthwhile self-hosting a webpage version of the manpage or pointing to somewhere else (like the [linux man pages site](http://man7.org/linux/man-pages/man1/tmux.1.html)).

Self-hosting wouldn't be too awful if you just went through github.io. You could even just have a site that has a single page that's just the manpage. There are a few manpage to HTML tools out there.
