### ISSUE TITLE
new install of tmux is un-responsive on remote mac os X 

### ISSUE THREAD

**Issue by aswistonjr** [tmux/tmux#2139]
I installed tmux on a remote mac pro running catalina via homebrew.  I didn't have any issues.  I used the example config file at ~/.tmux.config .  The machine is behind a corporate VPN.

To (re)produce the problem:
1) ssh into the remote machine, authenticate
2) try to open a session ($ tmux), nothing happens.  No new window, no errors, just an infinitely hanging terminal cursor.  same is true for tmux -v, tmux -vv .  $ killall tmux does list the dozen or so sessions I created trying to diagnose. 

Any suggestions?  Is this a casualty of the corporate security suite? Does zsh vs bash matter?

Huge thanks.

### Required information
tmux version: 3.0a_1
mac os X catalina Darwin i386
xterm-256color
no logs from tmux available (see above)

**Comment by topcat001** [comment]
I'm running tmux 3.0a from homebrew on Catalina, as well as the latest git master code. I haven't seen this issue. This is a mac laptop which I ssh in to sometimes (as well as using it from the console) and tmux works.

Have you tried rebooting the system? Are you absolutely certain all existing tmux processes are terminated and all socket files are removed? What about running it without any config file?

**Comment by aswistonjr** [comment]
I certainly wish I was free to visit the console and reboot it.  (The
corporate security posture only allows sudo rights on console for a few
hours, so i can't $shutdown -r over ssh)

Will $killall tmux ensure that all processes are terminated?  I have tried
with the example config file, and commenting out every line.  Deleting the
file also didn't help.

When you ssh into your 'remote' resource (I assume via tmux on your local
machine), do you get a new tmux session within the same terminal window, or
is an entirely new window created?  On my local machine (identical OS X
setup), tmux is working just fine, and sessions open within the existing
terminal window;  I am wondering if because of ssh, on my remote machine
there are a few dozen tmux sessions/windows open, waiting for me after
COVID-19.

Deeply appreciate your time and insights!

**Comment by topcat001** [comment]
Hi, please try
`ps aux | grep tmux`
to make sure there are no leftover processes. If so try
`killall -9 tmux`
to kill them and remove the socket files as well. My ssh sessions don't automatically start tmux.

**Comment by nicm** [comment]
Does `tmux -f/dev/null -Ltest new` work?

What if you do `tmux -f/dev/null -S$HOME/tmux-socket new`?

Does tmux work as another user or as root?
