### ISSUE TITLE
Accidental DoS when searching for the string "..."

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#2140]
### Issue description

I had some output from a program that I wanted to jump between, so I searched for the string `...`. This completely CPU pegged my terminal, so I terminated it, and then it pegged the tmux server, so I had to terminate the server as well at this point.

I understand very well that the "issue" is that the search term is a regex, and that `.` matches any character, and furthermore that a sequence of dots could generate a set of matches that apparently begins to overwhelm the terminal. I assume it's because for a given string "string", the pattern "..." matches "str", as well as "tri", and so on, and it may produce some kind of overlapping highlight sequence or something, which may trigger a runtime blowup somehow. I was hoping that it was just my terminal (Alacritty) that was choking on the escape sequences returned by the search results, but a significant amount of time was being spent processing this search by the tmux server as well so I killed it after a minute or so.

The buffer probably had between 90K and 100K lines in it, as 100K is what I set the history size of my tmux panes to, and I'd been using that pane enough to have it already filled. If each line has on average 500 bytes (that's quite pessimistic though), this is on the order of 50MB of buffer. 

Anyway, I will definitely remember that the search is a regex pattern from now on, but maybe it would be good to place some kind of timeout plus a message displayed upon hitting the timeout, so that the server session isn't lost when a user accidentally searches with too heavy a regex? 

* tmux version (`tmux -V`) `tmux next-3.2`
* Platform (`uname -sp`) `Darwin i386`
* $TERM inside and outside of tmux (`echo $TERM`). `tmux-256color-italic`
* Logs from tmux (`tmux kill-server; tmux -vv new`) -- don't think it's necessary

**Comment by topcat001** [comment]
Searching for `...` triggers lots of matches and for very large buffers this can be slow. It will eventually complete as can be seen by using a small buffer. Nonetheless, this is a problem. There are two things we can do perhaps:
- Use a configurable timeout, so that the search routine will exit once the timeout is exceeded.
- Add an option to turn off regex matching for regular searches. Incremental searches do not use regex.

**Comment by nicm** [comment]
I think we should add a 5 or 10 second timeout, there is no need for it to be configurable.

**Comment by topcat001** [comment]
Hi, can you please run your test case with the attached patch? Thanks!
[git-diff.txt](https://github.com/tmux/tmux/files/4406287/git-diff.txt)

**Comment by nicm** [comment]
This looks good but:

- I would not use clock() - instead use time() or gettimeofday() so you are measuring real time. I know the clock could jump but I think that isn't a big problem here since there is another exit condition (and `CLOCK_MONOTONIC` is not portable enough to be worth the trouble just for this).

- I wouldn't bother with `TIMEOUT_FREQ` myself and just check every line, unless you are finding it makes a big big difference.

- Also please call the define `WINDOW_COPY_SEARCH_TIMEOUT`.

**Comment by topcat001** [comment]
Hi, I have updated the patch, thanks for the comments!
[git-diff.txt](https://github.com/tmux/tmux/files/4409943/git-diff.txt)

**Comment by m42e** [comment]
Even if not using a regex pattern searching is rather slowed down since the commit 4ea07716de541aea5b8118ac0cfc4bc3bd30cb80
I have a buffer of a few lengthy lines and it completely freezes for seconds. While if the commit is reverted it works.

**Comment by nicm** [comment]
This works OK for me, but I think it is a bit confusing that the search just stops, so I think we should at least clear all the search results and probably display a message saying the search took too long.

**Comment by nicm** [comment]
There are a couple of ways we could do this:

1) We could just store a flag saying the search failed and show that with the indicator in the top right until another search is done or the marks would be cleared anyway. This might be easiest solution and we could also use it to avoid repeating the same failing search on resize.

2) We could return something to show failure like -1 from window_copy_search_marks and then try to display a message using status_message_set, but it is not clear to me where that would be called from.

**Comment by m42e** [comment]
I personally would like to see an option to completely disable the regex feature.

**Comment by m42e** [comment]
Just try the following, use the 3.1-rc3 and do the following:

´´´
curl https://gitlab.com/foundrynet/dnd5e/-/raw/master/packs/monsters.db
´´´
Then enter copy mode and search for ´acolyte´

Then revert the commit  4ea07716de541aea5b8118ac0cfc4bc3bd30cb80 and build it and try again. The difference is huge (imho) and the amount of buffer is about 11000 lines.

**Comment by nicm** [comment]
@m42e please open a new issue with some specific examples, we are not discussing it on a bunch of other issues

**Comment by m42e** [comment]
ok

**Comment by topcat001** [comment]
Thanks, I like option 1. Will report back with an update.

**Comment by nicm** [comment]
It could just show "(timed out)" where it usually shows the number of results if the number of results is -1 or something.

**Comment by nicm** [comment]
I was wondering if a match limit might be better instead of, or as well as, a timeout?

Also perhaps it could be a second argument to search-backward, so you could do:
~~~~
send -X search-backward foo 1000
~~~~
To only return the first 1000 matches (the default could be all matches).

What do you think?

**Comment by topcat001** [comment]
Yes, a match limit is a good idea. We should probably also have a timeout in case the search is run with no limit to prevent a hang. In case of a timeout, we can indicate an error.

**Comment by nicm** [comment]
Yes, I think a timeout as well is a good idea, it can be relatively large. If you want to do both - as two separate changes or together, I don't mind - that would be great.

Someone suggested a line limit in https://github.com/tmux/tmux/pull/1545 but it got side tracked with talk of the grid block change which is very complicated so hasn't happened yet. I think a match limit is a better idea and would have the same effect anyway.

**Comment by topcat001** [comment]
Sounds good! I'll create separate PRs for the timeout and the match limit bits and link here.

I agree we can set the timeout larger once it's implemented the way you suggested, since the failed search would not be run repeatedly.

**Comment by unphased** [comment]
Perhaps having an interactive prompt show up once either X matches are encountered, or T seconds are elapsed, giving the user the option to continue or terminate the search, that is perhaps the most polished possible behavior. Personally I'd be fine with X and T being hardcoded to 1000 and 10s respectively; even on a raspberry pi it shouldn't hang the machine for too long. But these 2 quantities seem pretty easy to add as configurables too.

**Comment by nicm** [comment]
A prompt would be fiddly to do and is probably more effort than this is worth. I think just a fixed 10 second timeout and a configurable match limit (I'd probably default to 10000 or something) would be enough.

**Comment by topcat001** [comment]
Hi, here is an initial implementation of the timeout bit, set to 10 secs. Please have a look, thanks!
[git-diff.txt](https://github.com/tmux/tmux/files/4414114/git-diff.txt)

**Comment by nicm** [comment]
Looks good, I have applied this now with a couple of minor changes ("timed out" instead of "Timeout!", and move the define to window-copy.c since it is only used in that file). Thanks!

**Comment by topcat001** [comment]
Hi, attached is an implementation of the search limit, set to 10,000 by default. Please have a look, thank you!
[git-diff.txt](https://github.com/tmux/tmux/files/4419555/git-diff.txt)

**Comment by topcat001** [comment]
I have a question about wrapping past the last highlighted result. Should we not jump to matches which are not highlighted when running `search-again`?

**Comment by nicm** [comment]
Hmm, the code in this diff looks good, but I'd forgotten that the highlighting works from top to bottom (duh) so it isn't as useful as I imagined. I was thinking that a match limit of 100 would highlight the bottom 100 results not the first 100 - so you could see them on the terminal - but of course it doesn't.

There are a few options I guess:

1) Keep the change as you have it and just use it as a safety net.

2) Change search_marks to work backwards so the bottom N results are highlighted.

3) Or change search_marks to JUST search the visible screen - it is already repeated on resize and on search-again so that wouldn't need to change, we would just need to make it also repeat when the screen is scrolled (vi keys don't clear it on cursor motion but emacs do).

I don't know how hard (2) would be. I think (3) would be easy enough and would save a lot of unnecessary searching?

What do you think?

**Comment by topcat001** [comment]
Yes thanks for laying out the issue explicitly. This is where I got stuck as well. If we highlight a subset of the results using either strategy (2) or (3), a subsequent `search-again` should not show results outside the highlighted block? Right now in this diff it shows results past the highlighting, which is a little confusing.

**Comment by nicm** [comment]
I'm not too worried about that, to be honest. I think it is fine if `search-again` jumps to results which are not highlighted - with the default match limit people are hardly going to do `search-again` 10000 times, and if they use a lower limit they will be aware when they move off the "end" of the highlighted region. I don't think it will be a very common case anyway.

If we change to (3) to only highlight terms on the visible part of the screen - `search-again` regenerates the matches so if it causes a scroll, the highlighting will include anything now visible.

**Comment by topcat001** [comment]
If we just search the visible screen I wonder if we still need the search limit? The visible area should have a relatively small number of matches, unless I am missing something.

**Comment by nicm** [comment]
Please take a look at this which only searches the visible screen: [x.diff.txt](https://github.com/tmux/tmux/files/4422288/x.diff.txt)

It makes the "N results" report pretty useless but I don't mind removing that (or changing it to say "N results shown").

**Comment by nicm** [comment]
Yeah I think we could probably do without it.

**Comment by nicm** [comment]
Here is one which actually works when the first line wraps: [y.diff.txt](https://github.com/tmux/tmux/files/4422300/y.diff.txt)

**Comment by nicm** [comment]
I think a match limit might still be sensible perhaps, perhaps lower like only 200 or 500 visible? If I do a search for `.` I can still get 9000 results even with a relatively small terminal, although it doesn't make tmux unresponsive.

**Comment by topcat001** [comment]
I think window_copy_scroll_up/down also need to b updated. Apart from that it works great, thanks. Also the match indicator now only refers to onscreen matches which is fine.

I wonder if anyone would still like to see all the matches in one go like before.

**Comment by nicm** [comment]
Ah yes, I have changed scroll_up and scroll_down also, thanks. I have applied this now to OpenBSD, it will be in GitHub later - I don't know why I didn't think of this before.

I don't think we should give people the option of the old behaviour, this is just how it is now.

Do you think we should have the match limit anyway? I don't really mind either way.

Also if it bothers you that `search-again` can find terms not highlighted, then of course feel free to write a diff to change it - I don't mind, I'm just not worried about it myself.

**Comment by topcat001** [comment]
Thanks! I'm okay with not having the search limit. I think my issue about `search-again` is also resolved because in the current diff the highlighting is reapplied when I jump past the last one on screen.

**Comment by nicm** [comment]
OK great stuff. Anyway I can search for `...` and `.` and similar and it becomes a little slow but it doesn't stop tmux for a long time or prevent you canceling the search, so yes let's forget the limit for the moment unless some other problem appears. Thanks for your work on this!

Also @unphased thanks for the report, I am closing this issue now.

**Comment by topcat001** [comment]
Hi, very minor thing
 but I noticed that now I get results from the line just off the top (`gd->hsize - gd->oy - 1`). Do you think the attached diff is ok? It handles wrapped lines and fixes this for me. Thanks!

[git-diff.txt](https://github.com/tmux/tmux/files/4423629/git-diff.txt)

**Comment by nicm** [comment]
Looks good, applied, thanks!
