### ISSUE TITLE
Regex feature in search is slowing down search

### ISSUE THREAD

**Issue by m42e** [tmux/tmux#2143]
### Issue description

Searching in the copy mode blocks the client for quite a time, if it has more and especially long lines.

Reproduce:

1. Load an example file: https://gitlab.com/foundrynet/dnd5e/-/raw/master/packs/monsters.db
2. cat the file (`cat monsters.db`)
3. Then enter copy mode and search for ´acolyte´.

By reverting the  commit 4ea0771 (and build of course) this issue is no longer present. 
I discovered even longer times where it is blocked, but could not share the exact data.

### Required information

Please provide the following information:
* Linux x86_64
* tmux 3.1-rc3
* screen-256color
* Logs:
[tmux-server-60044.zip](https://github.com/tmux/tmux/files/4410305/tmux-server-60044.zip)
[tmux-client-60042.log](https://github.com/tmux/tmux/files/4410307/tmux-client-60042.log)

**Comment by nicm** [comment]
Thanks. This has been a problem for a long time for people with huge history-limit, and I can imagine regex search does make worse.

There was some work done to store history in blocks which would mean we could search on demand, but that was never finished (it is very complicated to do and copy mode is already quite complicated).

I'll have a look at the performance of regex search at some point. I think in any case we should add variants of the commands which work without regexs so people who routinely use a large history-limit can change their key bindings.

Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/4410360/x.diff.txt).

You will need to change your search key bindings to `search-backward-text` instead of `search-backward` and similarly for `search-forward` - look at `tmux lsk -Tcopy-mode-vi|grep search-`.

**Comment by m42e** [comment]
Ok, so I tried it and it works just as nice as before with rebinding the keys to the `-text` variant.

**Comment by nicm** [comment]
OK thanks, I will apply this in a bit.

The way tmux stores data is not ideal for searching with something like regexec which expects a string, so it will probably never be really fast, but I will take a look at some point and see if there is anything obvious.

**Comment by nicm** [comment]
A lot of the time spent in searching is memory allocation and some of it is unnecessary. This improves things a lot although you are still looking at seconds if you have a big history: [y.diff.txt](https://github.com/tmux/tmux/files/4411177/y.diff.txt)

Much of the remaining time is in regexec and there isn't much we can do about that.

**Comment by nicm** [comment]
Here is another diff with a couple more improvements: [z.diff.txt](https://github.com/tmux/tmux/files/4411290/z.diff.txt)

Around 50% of the time is now in regexec and the bulk of the rest is retrieving the cell data (grid_get_cell). I don't see scope for any more huge improvements:

<img width="820" alt="Screenshot 2020-03-31 at 20 58 43" src="https://user-images.githubusercontent.com/304243/78069743-8448bb80-7392-11ea-838e-9278c55cb9a8.png">

**Comment by m42e** [comment]
Thanks for your investigation. I'll give it a try, as soon as I am back to work tomorrow.

**Comment by nicm** [comment]
Here is a another slightly improved diff: [aa.diff.txt](https://github.com/tmux/tmux/files/4411696/aa.diff.txt)

**Comment by m42e** [comment]
@nicm You always develop as a team, you and you a few minutes later: "You will never be able to optimise this" .... "Look I optimised this" ... "incredible"

**Comment by topcat001** [comment]
Thanks for the fixes! I will do some testing as well.

**Comment by nicm** [comment]
We can actually hoist the regcomp outside the function that is looped over, this gets us under 3 seconds for my test case, 60% of the time in regexec: [ab.diff.txt](https://github.com/tmux/tmux/files/4411778/ab.diff.txt)

None of this is tested that much so there may be bugs. That's all I have time to do today anyway.

<img width="820" alt="Screenshot 2020-03-31 at 23 00 45" src="https://user-images.githubusercontent.com/304243/78079285-b57db780-73a3-11ea-9378-b3b59837f91a.png">

**Comment by topcat001** [comment]
Awesome! One quick comment: in line 186 of ab.diff.txt, the xrealloc call can be moved outside the while loop?

**Comment by nicm** [comment]
Do you mean here?

+		while (bufsize < newsize) {
+			bufsize *= 2;
+			buf = xrealloc(buf, bufsize);
+		}


The while loop will almost always not execute at all, so I think it is
better for the xrealloc to be inside.

**Comment by topcat001** [comment]
Looking great after some initial testing, and much faster. I didn't realise the incremental memory allocations would be so slow. I need to increase my buffer history to massive sizes :) Thank you very much for the optimisations.

**Comment by m42e** [comment]
So now I have been able to test with the real data once more. It is a whole lot faster as before. I would suggest to still have the `-text` versions available, too. If you don´t mind.

Two things to mention regarding my testcase:
- The real data is colored.
- My real test is on ubuntu, yesterday i tried it with mac.
Do you think that makes a difference, too?

**Comment by nicm** [comment]
Colours won't make any difference but UTF-8 will be slower.

The speed of your computer and the performance of the regex engine will
make a difference, OS X and Linux have different regexp implementations,
although for fixed text (no special characters in the pattern) I would hope
they are roughly the same performance. But they wouldn't turn 30 seconds
into 3 seconds or anything like that unless the computers are very
different in CPU frequency.

The -text versions are staying now. I will probably pull them back so they
are in 3.1. The optimizations I might also pull back but I'm not sure
because they are more complex.

**Comment by nicm** [comment]
Here is another small change that makes a surprisingly big difference, at least with clang 11 on OS X:
~~~~
--- a/window-copy.c
+++ b/window-copy.c
@@ -2476,8 +2476,9 @@ window_copy_cstrtocellpos(struct grid *gd, u_int ncells, u_int *ppx, u_int *ppy,
         while (cell < ncells) {
                cells[cell].d = window_copy_cellstring(gl, px, &cells[cell].dlen);
                 cell++;
-               px = (px + 1) % gd->sx;
-               if (px == 0) {
+               px++;
+               if (px == gd->sx) {
+                       px = 0;
                         pywrap++;
                        gl = grid_peek_line(gd, pywrap);
                }

**Comment by nicm** [comment]
75% of the time is now in regexec and there are no more obvious hotspots, I don't think we will get it any better unless there are ways to reduce how often we call regexec.

**Comment by nicm** [comment]
Here's an idea, there is no point in doing a regex search unless we have a regex:
~~~~
--- a/window-copy.c
+++ b/window-copy.c
@@ -2673,6 +2673,9 @@ window_copy_search(struct window_mode_entry *wme, int direction, int regex)
        free(wp->searchstr);
        wp->searchstr = xstrdup(data->searchstr);

+       if (regex && strchr(data->searchstr, "^$*+()?[].\\") == NULL)
+               regex = 0;
+
        fx = data->cx;
        fy = screen_hsize(data->backing) - data->oy + data->cy;

**Comment by nicm** [comment]
Er that is wrong, it needs to be strcspn...

**Comment by m42e** [comment]
That should be a great help, too. So it is determined automatically.

**Comment by nicm** [comment]
OK I have applied all of these (my original diff from last night and the % change and a working change to turn regex off if there are no special characters in the search string) to OpenBSD now, they will be in GitHub later on when it syncs up.

**Comment by nicm** [comment]
These are all in GitHub now, and I have pulled them back to the 3.1-rc branch so they will be in the next 3.1 release candidate and in 3.1 when it is released probably in May. Let me know if you see any problems with these changes.
