### ISSUE TITLE
display-menu -x W value reverts to 0 when having multiple status line

### ISSUE THREAD

**Issue by cevhyruz** [tmux/tmux#2145]
Hello there, 

I have noticed when having multiple statusbar and you moved window list into another the `display-menu` x point will be at 0 since the `W` argument only checks for the location of window list in `status-format[0]`.

Would it be possible to have it check for a hit in all status entries and adjust accordingly?
I've tried fiddling with the cmd-display-menu.c but i'm not that much adept at C lang.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/4415458/x.diff.txt)

**Comment by cevhyruz** [comment]
thanks! that did it. 
Can we also add a new flag or change the existing `W` to also get the y position of the window list?

**Comment by nicm** [comment]
What do you mean?

**Comment by cevhyruz** [comment]
I mean if I create 5 status line and move the windows list at the bottom statusline the menu seems so far. It's kind of nice to have the menu sitting at exactly the top of window list not the statusline. what do you think?

**Comment by nicm** [comment]
Yes we could do that, I'll take a look later.

**Comment by cevhyruz** [comment]
Thanks!

**Comment by nicm** [comment]
Well, I can put it above where the window list ranges are - if you don't
include them it has no way to tell what is the window list.

**Comment by cevhyruz** [comment]
Is by including you mean using `#[range=window|X]`?
yeah I do include them that way.

**Comment by nicm** [comment]
Try this please, instead of the previous (so a clean tree): [y.diff.txt](https://github.com/tmux/tmux/files/4416889/y.diff.txt)

**Comment by cevhyruz** [comment]
That's more like it, but the menus that use `S` value was affected as well.
so I think maybe the `S` value should remain as is, and have the `W` be accepted for both -x and -y flag?

**Comment by nicm** [comment]
Good point, I have changed this. It is in OpenBSD now, it will be in GitHub when it syncs in a few hours. Let me know if you see any problems. Thanks!
