### ISSUE TITLE
how to show the choose-window in window not in pane?

### ISSUE THREAD

**Issue by toothedsword** [tmux/tmux#2146]
When I run the choose-window command, the list is shown in one pane. So can the list be shown in whole window?

Thanks!

* tmux version 2.9a.
* Platform fedora30.

**Comment by nicm** [comment]
Did you change your key bindings? This should be the default. Add `-Z` to your `choose-tree` binding.

**Comment by toothedsword** [comment]
> Did you change your key bindings? This should be the default. Add `-Z` to your `choose-tree` binding.

Great! It is OK now. Thanks you so much!

**Comment by toothedsword** [comment]
Thank you so much!


Liang Peng





At 2020-04-02 01:30:28, "Nicholas Marriott" <notifications@github.com> wrote:

Did you change your key bindings? This should be the default. Add -Z to your choose-tree binding.
