### ISSUE TITLE
Scrolling sends arrow key sequences

### ISSUE THREAD

**Issue by matthew-nm** [tmux/tmux#2148]
When using Tmux with WSL (Windows Subsystem for Linux) Ubuntu and with the WSLtty terminal (based on Mintty), the touchpad scrolls up/down are interpreted as up/down arrow keys. When scrolling up/down with the touchpad, the shell history is cycled through, as if using the up/down arrows. Checking the escape codes with ^V verifies that they are indeed sending the same sequences.

However when using Tmux with WSL Ubuntu using the standard WSL shell, it does not send up/down arrow escape sequences and thus scrolling works properly.

Why would these two terminals interact with Tmux differently? Is this something Tmux should fix or something Mintty/WSLtty should fix?

I believe Kitty users are having the same issue: https://github.com/kovidgoyal/kitty/issues/249

See my WSLtty issue posting here: https://github.com/mintty/wsltty/issues/238

System:
* tmux version: 2.6
* Platform: WSL Ubuntu Linux x86_64
* $TERM inside and outside of tmux: xterm-256/xterm-256

**Comment by nicm** [comment]
Logs?

**Comment by nicm** [comment]
tmux 2.6 is too old, please try tmux 3.0 or master.

**Comment by nicm** [comment]
Preferably please show me logs from doing the same thing in both working and not working terminals, so do this, for example:
~~~~
tmux -Ltest kill-server
tmux -Ltest -f/dev/null new
(now inside tmux)
tmux set -g mouse on
(scroll up a few times)
exit
~~~~
tmux will write tmux-server-*.log files in the directory where you started it.

Then send me the two tmux-server-* logs, one where it entered copy mode and one where it scrolled up in the shell history.

**Comment by matthew-nm** [comment]
Tmux 2.6 was the lastest available on Ubuntu via `apt`, so I installed the master branch from here and now tmux version is "next-3.2".

To get log output I had to do `tmux -vvvv`. I attached those logs to this comment,
[tmux-client-30584.log](https://github.com/tmux/tmux/files/4428974/tmux-client-30584.log)
[tmux-out-30586.log](https://github.com/tmux/tmux/files/4428976/tmux-out-30586.log)
[tmux-server-30586.log](https://github.com/tmux/tmux/files/4428977/tmux-server-30586.log)

My actions were to start tmux, scroll up a bit, scroll back down a bit (this had the effect of scrolling back through my command history and then returning to empty command).

**Comment by nicm** [comment]
This is a terminal issue. From your first log - tmux is turning the mouse on:
~~~~
1585935600.832373 /dev/pts/2: \033[?1006h
1585935600.832379 /dev/pts/2: \033[?1002h
~~~~
But the terminal is not sending mouse events when you scroll, instead it is sending cursor keys:
~~~~
$ grep 'keys are' tmux-server-30586.log
1585935602.458861 /dev/pts/2: keys are 3 (\033OA)
1585935602.474762 /dev/pts/2: keys are 3 (\033OA)
1585935602.505651 /dev/pts/2: keys are 3 (\033OA)
...
~~~~
In your second log there are some mouse events, but the cursor keys are also present. tmux turns the mouse on in the same way in both logs.

**Comment by matthew-nm** [comment]
Ok, that all makes sense.

I first raised this issue with the WSLtty project, but was told it had to be tmux putting the terminal in a different mode, such as application keypad mode. I'm not sure what this means.

Is there a way to check what mode the terminal is in? Does tmux ask the terminal to be put in any particular mode? When scrolling in WSLtty outside of tmux, it does not send arrow keys, so somehow it's the interaction between the terminal and tmux that causes the terminal to think it should be sending arrows.

**Comment by nicm** [comment]
Application keypad mode controls what is sent for the cursor keys on the keyboard, it should not have any influence on the mouse wheel. It just turns the sequences from `\033[A` to `\033OA` (which tmux treats the same in any case) - it doesn't make it send cursor keys instead of mouse sequences. So it sounds like the wsltty developers have got the wrong end of the stick.

You can test outside tmux by doing this:
~~~~
printf '\033[?1006h\033[?1002h'
cat
~~~~
Then scrolling and seeing if you see mouse escape sequences (`^[[<65;82;30M`) or cursor keys (`^[OA` or `^[[A` or B, C, D).

If you do see mouse escape sequences for this, then try adding the application keypad sequence and see if it breaks it:
~~~~
printf '\033[?1h\033=\033[?1006h\033[?1002h'
cat
~~~~
If that is still correct, try putting it in alternate screen:
~~~~
printf '\033[?1049h\033[22;0;0t\033[?1h\033=\033[?1006h\033[?1002h'
cat
~~~~
If those are all OK, I don't know what it is. But this is a problem with the terminal and you will need to go back to the wsltty developers.

**Comment by matthew-nm** [comment]
The first two look very similar in native WSL and WSLtty, but the last one `printf '\033[?1049h\033[22;0;0t\033[?1h\033=\033[?1006h\033[?1002h'` (alternate screen) is very different and seems to match what I experience when scrolling in tmux.

In native WSL terminal, when I scroll up and down vigorously on the touchpad I get,
```
[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<65;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M[<64;70;7M
```

but when doing the same in WSLtty I get,
```
[B[B[B[B[B[B[B[B[A[A[A[A[B[B[B[B[B[B[B[B[A[A[A[<64;33;6M[A[A[A[A[B[B[B[B[B[A[A[A[A[A[A[A[A[B[B[B[B[B[B[A[A[A[A[A[B[B[B[B[A[A[A[A[A[B[B[B[B[B[B[A[A[A[A[A[B[B[B[A[B[B[B[B[B[B[<65;33;6M[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[<64;33;6M[A[A[A[A[A[A[A[A
```
 which looks like some scroll input with a lot of arrow input. This matches what I experience when scrolling in WSLtty + tmux, some scrolling (it does eventually enter copy mode and move around), but primarily arrow input.

**Comment by nicm** [comment]
OK well that means you can reproduce without tmux, to go any further you will need to talk to the terminal developers. tmux is sending exactly the same thing here to both working and not working terminals.

**Comment by matthew-nm** [comment]
Yup, got it. I will reference this thread in the future. Glad to know where cutoff is for this issue.

Thanks for the help uncovering the issue.
