### ISSUE TITLE
Binding a key in mode-table to multiple commands 

### ISSUE THREAD

**Issue by vnagarnaik** [tmux/tmux#215]
Recently I saw a request to make a pane more visible if it's in copy-mode. This is because sometimes the counter at the top which indicates copy-mode can be missed. I suggested the following:

Highlight pane and enter copy mode:
```
bind-key [ select-pane -t $TMUX_PANE -P 'bg=yellow' \; copy-mode
```
And to reset the styling after copying the selection:
```
bind-key -t vi-copy Enter copy-selection \; select-pane -t $TMUX_PANE -P default
```
However, the latter bind fails because only one command can be 
```
Not enough arguments.
```
Even the following bind fails:
```
bind-key -t vi-copy Enter select-pane -t $TMUX_PANE -P default
```

It seems this issue was brought up 2 years ago [here](http://tmux-users.narkive.com/9hgrusmu/can-t-bind-multiple-commands-with-bind-t) and it wasn't an allowed operation.

I think having bind in mode-table work like prefix table would be a pretty useful feature. Any plans on adding the support for it?

**Comment by nicm** [comment]
No no plans. You could probably make it work outside copy mode using if #{pane_in_mode} and send-keys.

**Comment by nicm** [comment]
Actually it might be a nice thing to do, although I'd prefer to get rid of the tables for choose and edit mode first.

**Comment by nicm** [comment]
I think I have an idea how it would look too...

**Comment by nicm** [comment]
I was thinking of just making a command to inject keys into copy mode and then just using a special key table if the pane was in copy mode, which would work pretty well for emacs but not for vi. I'd love to get rid of having vi key bindings builtin but a lot of people use them. The other problem is that the key table is per client but modes are per pane, but we could just run a key through two tables.

**Comment by vnagarnaik** [comment]
Thanks. I found that this works:

```
bind-key -t vi-copy p copy-selection
bind-key -Troot Enter if-shell -F "#{pane_in_mode}" "send-keys p \; select-pane -P default" "send-keys -l Enter"
```

I think it's hacky and multiple commands in any mode-table should be a good feature to have. But it works for now.

**Comment by vnagarnaik** [comment]
BTW I **love** tmux. Thanks for working on this and keeping it active.
