### ISSUE TITLE
Attach to different windows in the same session

### ISSUE THREAD

**Issue by Kyle-Thompson** [tmux/tmux#2150]
My current workflow involves one tmux session per project with the windows "code", "build", "git", and "shells". This works well but it would be very nice to be able to have two different terminal windows connected to two different tmux windows at the same time within the same session. For instance, having "build" and "code" open at the same time in a different terminal window each would make it much easier to debug build issues without having to switch back and forth between windows.

Is this already supported? If not, is such a feature possible? If it is not implemented but would be possible and doesn't conflict with tmux's design I'd be happy to try to implement it myself.

Features like rogue mode within wemux lead me to believe that something like this should be possible with plain tmux. I'd rather avoid using a big wrapper script if possible.

**Comment by topcat001** [comment]
Hi I use something similar. I create a main session:
`tmux new -s projA`
Then create a clone:
`tmux new -s projA1 -t projA`
Now you can attach to projA and projA1 from different terminals and view different windows. Does this help?

**Comment by Kyle-Thompson** [comment]
This is helpful and is since what I've adopted. The only thing is now I could have ten or twenty projects going on at once and in the view to switch sessions (prefix + s, let me know if there's a better one) I'll have double the amount to choose from. It would have been really helpful to have this feature enabled without having to create a separate session entirely. At the very least is there a way to search session groups rather than just sessions? Or perhaps can the list of sessions be filtered with a tool like fzf to quickly bring the list to a manageable size?

**Comment by nicm** [comment]
tmux only shows one session in each group in tree mode unless you use
choose-tree -G. Your tmux is probably too old.

**Comment by Kyle-Thompson** [comment]
Thanks. It seems like there should be enough existing functionality to get my desired workflow working. I'll close this issue and open a new one if a different problem comes up. Thanks for the help.

**Comment by Kyle-Thompson** [comment]
Actually, one last question. From the switch session thing, how can I choose which session within a group to connect to? If I have `my-project1` and `my-project2`, it seems to only allow me to connect to `my-project1` (which is the one created first.)

**Comment by topcat001** [comment]
You can bind a key to `choose-tree -G` which will expand out all the sessions, showing the windows in each session. Next press the shortcut displayed on the left side to pick the session. I'm on tmux git but I think it will work on older versions, but perhaps not too old :)
