### ISSUE TITLE
Creating New session from .sh file but can't see in terminal

### ISSUE THREAD

**Issue by Walshie1987** [tmux/tmux#2154]
Hi, 

I want to use tmux to start and process python scripts in parrellel on my site. So at a very basic level, a user clicks "Run Script" on a webpage, then the PHP triggers a command to execute a new tmux session specifically for that user (I name the session something unique) and then a python script runs inside that session. I then want the ability to login via a terminal (PuTTY) and be able to view the sessions, kill them etc.

I've done all the PHP and created the script and it all looks good. I can create a session and echo back the list of sessions that are running on the server. I create the sessions in PHP whilst logged in as root (I've confimed in SSH that the script is ran as root by using whoami and it returns "root")

The final piece of the puzzle that I just can't figure out is how to get the sessions to show using tmux ls when I login to a terminal. I log in as root and enter `tmux ls` and I get "no server running on /tmp/tmux-0/default"

I've tried everything I can think of, is there something that I'm missing or is this a bug?

Thanks in advance and I love TMUX, it's made thing so much easier!

Cheers
Chris

### Required information
* tmux version (`tmux -V`). - tmux 2.6
* Platform (`uname -sp`). - Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). - xterm
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Run this from PHP:
~~~~
tmux display -p '#{socket_path}'
~~~~
And see what socket it is actually using.

**Comment by Walshie1987** [comment]
Thanks for the reply:

/tmp/tmux-0/default

**Comment by nicm** [comment]
Are you sure the server is still running when you try to attach? Does `pgrep tmux` show it?

**Comment by Walshie1987** [comment]
Hopefully this helps a bit 
![Screenshot](https://user-images.githubusercontent.com/63238840/78558723-0447a900-780b-11ea-91bb-ee3087f8ab1f.jpg)

**Comment by Walshie1987** [comment]
pgrep tmux:

root@SecurityServerNew:/var/www/html# pgrep tmux
985
23205
24660
27171
29607

**Comment by nicm** [comment]
So what's the problem?

**Comment by Walshie1987** [comment]
Sorry I didn't expain. You can see from the PHP output that there are two session running when I run "tmux ls" on the webserver. But when I log into the server and enter "tmux ls" there is only one session, even thouhg I'm in as the same user, on the same socket

**Comment by nicm** [comment]
What are you showing me? If you can do `tmux ls` from putty and it works, what's the problem?

**Comment by nicm** [comment]
OK well probably you are not talking to the same server. So either it is actually using a socket somewhere else, or the socket has been removed and a new server started.

I would kill all tmux servers and remove /tmp/tmux-0 then create one from PHP. Then make sure `pgrep -lf tmux` only shows one server from putty, see if /tmp/tmux-0/default has been created, and see if `tmux ls` works.

**Comment by nicm** [comment]
Is PHP chrooted?

**Comment by Walshie1987** [comment]
No it's not chrooted - could be the issue?

O'll try the above too. Thanks so much for the help

**Comment by nicm** [comment]
No if it is not chrooted it should put the socket where it says it is in /tmp.

**Comment by nicm** [comment]
I'd kill all tmux and then make very sure you only start one tmux server (from PHP) and see if you can attach to it then.

**Comment by Walshie1987** [comment]
So I rebooted the server, did `pgrep tmux` and there was nothing there, ran the PHP, which said it created the session, range `pgrep tmux` again and got the following:

```
root@SecurityServerNew:~# pgrep tmux
1589
```

I them did `tmux ls` and got the below:

```
root@SecurityServerNew:~# tmux ls
error connecting to /tmp/tmux-0/default (No such file or directory)
```


Sp

**Comment by nicm** [comment]
OK if you do `ss -xp|grep tmux` what do you see?

**Comment by Walshie1987** [comment]
Nothing

...I've just spotted something in my php config output:

DOCUMENT_ROOT | /var/www/html

**Comment by Walshie1987** [comment]
Maybe this is the issue?

**Comment by nicm** [comment]
Does it work if you do `tmux -S/var/www/tmp/tmux-0/default ls`?

**Comment by Walshie1987** [comment]
root@SecurityServerNew:~# tmux -S/var/www/tmp/tmux-0/default ls
error connecting to /var/www/tmp/tmux-0/default (No such file or directory)

**Comment by nicm** [comment]
What if you do `pkill -USR1 tmux` then try `tmux ls` without any -S?

**Comment by Walshie1987** [comment]
root@SecurityServerNew:~# pkill -USR1 tmux
root@SecurityServerNew:~# tmux ls
error connecting to /tmp/tmux-0/default (No such file or directory)

**Comment by nicm** [comment]
Oh it says "No such file or directory" now, so it must be creating it somewhere else. What  if you do `find / -type d -name tmux-0` does it show the socket directory?

**Comment by Walshie1987** [comment]
Your knowledge is really showing through now! 

root@SecurityServerNew:~# find / -type d -name tmux-0
/tmp/systemd-private-7e355141f69b4a8aae4c19e26777a837-apache2.service-VrxXHI/tmp/tmux-0
/tmp/tmux-0

**Comment by nicm** [comment]
Try setting TMUX_TMPDIR to /tmp before you start tmux from PHP and it should use /tmp like normal.

**Comment by Walshie1987** [comment]
Sorry how do you do that?

**Comment by nicm** [comment]
It might be easier just to pass -S/tmp/tmux-1000/default TBH.

**Comment by Walshie1987** [comment]
tried this in the command.sh file, `tmux -S /tmp/tmux-1000/default new -d -s CWTest` and I get "Server Lost"

**Comment by Walshie1987** [comment]
I hate taking up all your time, escpecially when it's probably my error! Do you charge an hourly rate or anything? I could give you access to the server and pay you for an hour to fix it?

**Comment by nicm** [comment]
tmux-0 not 1000.

**Comment by nicm** [comment]
No its OK.

**Comment by Walshie1987** [comment]
Same issue, creates but in terminal:

```
root@SecurityServerNew:/var/www/html# tmux ls
error connecting to /tmp/tmux-0/default (No such file or directory)
```

**Comment by nicm** [comment]
Yes actually systemd is probably making it so that /tmp looks like /tmp to php but is actually a different directory. Your best bet might be to put the socket somewhere entirely different like `-S/root/tmux-socket` or `/var/www/tmux-socket`.

**Comment by Walshie1987** [comment]
Absolute Genius!

**Comment by Walshie1987** [comment]
I've been trying for days and days to get that working. I'm planning on using TMUX to start new instances for different users from PHP and then kill them off too. 

Really appreciate your help and thanks again for TMUX - without it I'd be struggling with my project!

Cheers
Chris

**Comment by nicm** [comment]
Great stuff.
