### ISSUE TITLE
3.1-rc4 compilation error

### ISSUE THREAD

**Issue by markuspeloquin** [tmux/tmux#2155]
I checked out the `3.1` tag and tried to build. [This commit](https://github.com/tmux/tmux/commit/a4e19bcd8020f655f613604361d0f30384edbdc0) added two arguments to the call of `job_run()`.

This was the only compilation error.

@nicm

**Comment by nicm** [comment]
Are you sure you are at the top of the branch? I fixed that already.

**Comment by nicm** [comment]
I have also moved the tag now. Thanks!

**Comment by markuspeloquin** [comment]
Yeah, my update script looks for the latest tag. Thanks!
