### ISSUE TITLE
Clipboard is messed up by tmux with X forwaring

### ISSUE THREAD

**Issue by laggardkernel** [tmux/tmux#2156]
### Required information

Please provide the following information:

* tmux version: tmux 3.1-rc
* Platform: macOS 10.13.6
* $TERM inside and outside of tmux:
    - local xterm-kitty
    - remote xterm-kitty
    - remote within tmux: tmux-256color
* [Logs from tmux](https://www.dropbox.com/s/g8ippputrfrc0ch/tmux-log.tgz?dl=0) (`tmux kill-server; tmux -vv new`). 

The problem only happens in the terminal kitty now. Here's the steps to reproduce this,

On my local machine, install and open XQuartz. Open kitty, connect to a remote server with X Forwarding enabled. `ssh -Y host`. (The X forwarding is used here to sync the clipboard between local and remote machine).

On the remote machine, start tmux. Select some text within tmux (`Ctrl-b [`), check the content in the local clipboard. Then do the selection again and check the content within the local clipboard.

The problem here is that after the 2nd selection, the selection is **appended** to the former. What we expect is the 2nd selection replace content in the clipboard, which is what happens on other terminal like iTerm and Alacritty in my test.

This could be also reproduced without any tmux plugin `tmux -f /dev/null new`.

I've reported this [issue under kitty](https://github.com/kovidgoyal/kitty/issues/2390#issuecomment-610167129). (There's more verbose steps in the issue under kitty) The author of kitty suggested it as a bug of tmux. So I come here.

**Comment by nicm** [comment]
This is a bug in Kitty, when using OSC 52 it appends to the selection rather than replacing it. I believe there maybe an option to change this behaviour.

However if you are using some mechanism to set the clipboard via X (such as `xsel` or `xclip`) it is pointless to also use OSC 52. You can stop tmux using it by turning off the `set-clipboard` option.

**Comment by laggardkernel** [comment]
I haven't know about `set-clipboard`. The `tmux-yank` plugin I'm using seems doesn't work with `set-clipboard` set `on` or `external`. Or to say it in another way, `tmux-yank`, in fact it's the dependency `xsel` or `xclip`,  is shadowed.

Disabling `set-clipboard` and making `tmux-yank` handle clipboard with `xsel` could avoid the bug temporarily.

Thanks for your help. I'll report the OSC 52 thing back to kitty.
