### ISSUE TITLE
Users Keys assgined via user-key[x] not sent to applications when unbound.

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#2157]
### Issue description

If I use the `set-option -s user-keys[0] ...` command to map an escape sequence to a `User0` key, I can bind User0 to perform functions as normal.

However, the *default* behaviour is to discard the key, rather than forward it to the foreground application.

For example.
If I create a `User0` with `<Esc>[Z` (which is sent by shift-tab on my setup).
I can successfully bind key to change panes for example;
```
bind -T prefix User0 select-pane -t {next}
```
However, the key sequence does not get forwarded to the shell, or foreground application because there is no binding for `-T root`

Can user-keys[*] be forwarded automatically to applications where there is no other binding in the root key table?

Thanks

### Required information

Please provide the following information:

* tmux version: tmux next-3.1
* Platform: Linux x86_64 (Ubuntu 18.04)
* $TERM: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Why don't you just bind BTab?

If you want user keys to send some text to the pane, you will need to bind them to `send-keys`.

**Comment by systemmonkey42** [comment]
In my case BTab doesn't match.  What is the terminfo code for BTab?  I'll try a terminal-override.

**Comment by nicm** [comment]
`kcbt` - xterm-256color should have it by default.

**Comment by systemmonkey42** [comment]
It certainly does
```
xterm-256color
    bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
    kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
```
It certainly does.   I've replaced the user-key with BTab.  Everything works normally now

I was hoping to avoid having to bind each `user-keys` escape sequence with a command to send the key in the `root` key table.  But, its not that big a deal.

Much appreciated
Thanks

**Comment by nicm** [comment]
What other keys do you want to send with user-keys that tmux doesn't already support?

**Comment by systemmonkey42** [comment]
This was the first, and it was clearly already handled by BTab, so none at the moment.

**Comment by nicm** [comment]
OK cool, mostly if there are keys that really exist and send a standard escape sequence then we should consider adding them in some way.
