### ISSUE TITLE
Session working directory variable

### ISSUE THREAD

**Issue by Joshuao95** [tmux/tmux#2159]
Hi,
I was wondering if there's anyway to programatically get the session working directory (as supplied to attach-session with -c)?

It seems in an older version "default-path" had this role.

Thanks

**Comment by nicm** [comment]
The `session_path` format was added in 2a4714e76b3a85b3391b05413f36623bcb1493f9 a few weeks ago. You will need to build and run tmux from master.

**Comment by Joshuao95** [comment]
Cheers Nicholas, don't know how I missed the patch!
