### ISSUE TITLE
Using tmux is changing my effective permissions?

### ISSUE THREAD

**Issue by ApproximateIdentity** [tmux/tmux#216]
I added my user to a certain linux group so that it could read `/var/log/syslog`. I logged out and back in so that it would take effect and in fact it did. But when I open a tmux screen it will not let me read the file and instead just says permission denied. What could be causing this?

P.S. If this is the wrong place to post this, I'm sorry. I tried the tmux-users google group, but there seems to be no way for me to post or reply even though I see no indication that the group is private or restricted.

**Comment by nicm** [comment]
You probably started tmux before you added the permissions.

**Comment by ApproximateIdentity** [comment]
Is there a way to get tmux to reload with these changes without closing all of my tmux servers?

**Comment by nicm** [comment]
No, programs can't increase their own permissions beyond what they are started with.

**Comment by ApproximateIdentity** [comment]
There is a way to do this actually. I'll share the solution I found for others who find their way to this thread: http://superuser.com/questions/272061/reload-a-linux-users-group-assignments-without-logging-out/345051#345051

In any case, thanks for the help!
