### ISSUE TITLE
Breaking functional changes from 2.9a to 3.0a

### ISSUE THREAD

**Issue by fredaas** [tmux/tmux#2160]
In 2.9a this would effectively move a window left/right and change its window id accordingly:

```
bind-key , swap-window -t -1
bind-key . swap-window -t +1
```

Thus pressing `,` multiple times would move the current window to the left and wrap around to the rightmost side.

In 3.0a the equivalent command swaps the current window with its neighboring window.

The behavior in 2.9a is great and I use it all the time. How can I achieve this in 3.0a?

tmux version: 3.0a
Platform: Linux 4.15.0-91-generic, Ubuntu 18.04.4 LTS

**Comment by fredaas** [comment]
This was solved by changing the original commands to:

```
bind-key , swap-window -t -1\; select-window -t -1
bind-key . swap-window -t +1\; select-window -t +1
```

Closing.

**Comment by nicm** [comment]
You can just add the `-d` flag which changed meaning to match the other commands.

**Comment by fredaas** [comment]
@nicm That's even better. Thanks!

**Comment by stdedos** [comment]
This is missing from Changelog - could someone add it?

(At least it's documented in http://man.openbsd.org/OpenBSD-current/man1/tmux.1)
