### ISSUE TITLE
Documentation comments and suggestions

### ISSUE THREAD

**Issue by nicm** [tmux/tmux#2163]
Please make any short comments on documentation on this issue:

- Something missing?
- Too confusing?
- Poorly explained?
- A suggestion?
- Want to write something?

Providing suggested text is helpful for any changes.

Primary tmux documentation is the following:

Document|URL|Purpose
---|---|---
Home page|https://github.com/tmux/tmux/wiki|Home page and wiki landing page.
Getting started|https://github.com/tmux/tmux/wiki/Getting-Started|How to get started with tmux. Focus on new users (bearing in mind tmux's target audience), interactive use and basic configuration.
Advanced use|https://github.com/tmux/tmux/wiki/Advanced-Use|Use of features beyond getting started, scripting, advanced configuration. Not finished yet!
The manual page|https://man.openbsd.org/OpenBSD-current/man1/tmux.1|System manual. Must stick to manual page style and conventions. Should document every command, flag, feature even briefly.
FAQ|https://github.com/tmux/tmux/wiki/FAQ|Quick answers to common questions.
Installing|https://github.com/tmux/tmux/wiki/Installing|How to build and install tmux.
README|https://github.com/tmux/tmux/blob/master/.github/README.md|Quick first look and summary.

**Comment by absorber** [comment]
Hi, I've noticed the use of short form commands / aliases in the wiki. I personally prefer the use of long form commands in documentation. To me it comes over as clearer and lets the user grasp the meaning of a command faster.

If you think so too, would you be ok if I contributed to the wiki in order to reflect that?

**Comment by nicm** [comment]
The idea behind this is that the text uses the long form and examples use
the alias so they illustrate what the alias is and are also closer to what
people would be likely to actually type when using the commands. If there
are examples where the full command name isn't mentioned in the surrounding
text then they should be changed.

**Comment by bcgraham** [comment]
This is all in reference to the man page documentation, since that’s what I check. Generally the state has been really good for my use case, these are just some minor points.

When searching pane contents in copy mode, search results kind of behave like selections and kind of don’t. I thought the difference between these could be made a little clearer in the documentation (e.g., `copy-selection` will copy a search result in the absence of an actual selection, but `copy-selection-no-clear` will clear search results in that case).

`select-pane` command documentation references a `target-window` in underlined styling, suggesting it is a parameter, but it hasn’t been a valid parameter in a long time. 

It also made sense after I realized what was happening, but it could be helpful, for people like me, to explain `select-pane` can’t be used to see and focus a pane in another window without an additional `select-window`.

`setw` is referenced in a man page example, but it’s no longer clear what that command is or does. 

When viewing the man page with `less`, it’s possible to skip to the command you’re interested in by searching for line beginning, four spaces, and the command name. That’s better than nothing, and I’m grateful for it. I would love love love if there could be something a little simpler to type. I’m aware of how low a priority it this must be, just saying. 

A comprehensive and centralized list of all hooks would be very appreciated.

**Comment by nicm** [comment]
If you are using OpenBSD or maybe mandoc on other platforms you can use tags in man to jump to a command name in less with `:t` then the command name. I don't think there is much we can do on other platforms, we are bound by the markup that mdoc offers and the features man/less offer.

I'll have a look at your other points later on, thanks.

**Comment by nicm** [comment]
> When searching pane contents in copy mode, search results kind of behave like selections and kind of don’t. I thought the difference between these could be made a little clearer in the documentation (e.g., copy-selection will copy a search result in the absence of an actual selection, but copy-selection-no-clear will clear search results in that case).

Both `copy-selection` and `copy-selection-no-clear` behave the same and clear the search results for me? I expect `-no-clear` probably shouldn't.

> select-pane command documentation references a target-window in underlined styling, suggesting it is a parameter, but it hasn’t been a valid parameter in a long time.

Fixed.

> It also made sense after I realized what was happening, but it could be helpful, for people like me, to explain select-pane can’t be used to see and focus a pane in another window without an additional select-window.

This is implied by `target-pane`, I don't want to repeat that a target can refer to any session/window/pane all over the place.

> setw is referenced in a man page example, but it’s no longer clear what that command is or does.

Fixed.

> A comprehensive and centralized list of all hooks would be very appreciated.

`tmux show-hooks -g` and `tmux show-hooks -gw` will list them all.

**Comment by bcgraham** [comment]
> I expect `-no-clear` probably shouldn't.

While I could see a case for that, and I would like it, it did make sense to me why they would behave the way they do currently (search results are not selections). And there’s a workaround (searching back and forth again). This wasn’t a backhanded feature request, honest!

**Comment by nicm** [comment]
I have changed the `-no-clear` commands not to clear the search marks now (in OpenBSD, will be in GitHub later). Thanks! Let me know if you have any other comments.

**Comment by bchallenor** [comment]
The man page for `select-pane` says "The marked pane is the default target for -s to join-pane, swap-pane and swap-window". This list should include `move-pane` now.

**Comment by nicm** [comment]
Fixed now, thanks.

**Comment by BruceMoustache** [comment]
Hi I want to suggest to put installation through package manager  in installation guide

**Comment by nicm** [comment]
What should it say though? Surely everyone knows how to run `apt-get install tmux`?

**Comment by MoonZ** [comment]
A small remark, about this section : https://github.com/tmux/tmux/wiki/Getting-Started#splitting-the-window

I know this follows the tool and man page direction (`tmux split-window -h` or `-v`), but I feel there's a confusion here.

If someone cuts something horizontally, parts are stacked vertically. If someone cuts something vertically, parts are stacked horizontally.
The documentation says in essence that by splitting a window horizontally, panes will be stacked horizontally.

In the end, [there's no answer that will be universally understood](https://twitter.com/FreyaHolmer/status/1279079339892658177) but the man page, key binding section, sidesteps this issue by phrasing it  : "Split the current pane into two, left and right." without mentioning the potentially confusing "vertical" and "horizontal" terms. I think it might be a better approach.

**Comment by nicm** [comment]
Yes... but the text does explicitly say what tmux means by horizointally and vertically:

> `C-b %` splits the current pane into two horizontally, _producing two panes next to each other, one on the left and one on the right._

I know that people have different understandings of splitting horizontally and vertically, but I think it is useful to mention how tmux defines them rather than removing the words altogether, because tmux's meaning maps to the `-h` and `-v` flags.

Do you have any suggested text that would be clearer?

**Comment by MoonZ** [comment]
OK, I thought my suggestion was clearer: since we agree this horizontal/vertical split is confusing, I suggest to reuse the man page approach to avoid it completely:
`Split the current pane into two, left and right.`
and
`Split the current pane into two, top and bottom.`

[Source](http://manpages.ubuntu.com/manpages/trusty/man1/tmux.1.html) (ctrl-f with "Split the current" to locate the quotes)

That way, no **vertical** or **horizontal** notions are brought up, and the description gains in clarity.

**Comment by nicm** [comment]
But the current text already says that, and if we don't mention horizontal and vertical it doesn't connect to the -h and -v flags.

**Comment by MoonZ** [comment]
When you know a mistake has been made, and you can't fix it yourself, you should look to mitigate it, not to make it worse. The man page description understood that (this avoidance is no coincidence). And the poll I've linked illustrates it's inverted for the majority (85% vs 15%).
Now, it's just a suggestion I've made, if you have your own reasons to maintain that confusion, I won't fight it :)

**Comment by nicm** [comment]
The tmux definitions of horizontal and vertical are correct. The idea is to avoid confusion with people who are used to a different definition, not to correct a mistake. If we remove one area of potential confusion by removing the terms horizontal and vertical completely, but introduce another by not linking the two types of split to the -h and -v flags, it is not an improvement.

**Comment by nicm** [comment]
The current full text we are talking about is:
> C-b % splits the current pane into two horizontally, producing two panes next to each other, one on the left and one on the right.
>
> C-b " splits the current pane into two vertically, producing two panes one above the other.

Which mentions *both* the terms "horizontally" and "vertically" and the result of the spot (left and right, or above each other). This was written carefully so it explains what tmux means by horizontal and vertical and also what actually happens. I think this is fine as it is, unless you have specific different wording to suggest.

**Comment by nkh** [comment]
The man page is long and the html man page doesn't contain an index (and here's still no standard way to access those). information accessible via info would be great, and textinfo lets one generate other type of documentation.

**Comment by nicm** [comment]
No I'm not changing the format of the documentation, particularly not to texinfo. It would be nice if GitHub would provide a way to generate a TOC and index on their pages but they do not.

**Comment by nkh** [comment]
pandoc generates texinfo so the documentation can be more or less written in anything.

**Comment by sevens-ef** [comment]
Hello, in the man page (tmux 3.1b), in the documentation of the `show-options` command ("OPTIONS" section), the last sentence is: "`value` depends on the option and may be a number, a string, or a flag (on, off, or omitted to toggle)."

Shouldn't this instead be part of the `set-option` command right above it?  (`show-options` has no `value` argument while `set-option` has, and the toggle behavior seems to work on flag options for `set-option`.)

**Comment by nicm** [comment]
Yes, fixed thanks!

**Comment by tessus** [comment]
In the documentation for [extended keys](https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys) `C-1` is mentioned as an extended key. What does that mean? What is `C-1`?
A link to an article or a list of extended keys would be beneficial.

**Comment by nicm** [comment]
`C-` is described in an earlier section of that document ("How tmux describes keys...") and in the man page under KEY BINDINGS.

**Comment by tessus** [comment]
Thanks for the info. I understood the `C-` part, but not why it was an extended key. In my mind `Ctrl+1` seemed like a valid combination, so I thought it might be something else like `PrintScreen` or something that doesn't follow the normal convention....

**Comment by nicm** [comment]
Oh right, I see. If you look at the sections about "Limitations of X keys", an extended key is anything apart from those really, exactly which keys depends a bit on the terminal. `C-1` is Ctrl+1 which normally can't be represented because there are only a few Ctrl keys.

**Comment by tessus** [comment]
After reading that part, it made sense. But when I clicked on the link for extended keys in the 3.2-rc discussion issue, I didn't see that part... If I had started to read that doc from the top, no problem. So maybe you could add a link to that "limitations" section somewhere in the section for extended keys.

**Comment by nicm** [comment]
I have linked to the ctrl key section and also to the spec for the keys. Thanks!

**Comment by andb0t** [comment]
I suggest an additional section on "Config migration from 2.x to 3.x", because more and more people will loose default access to the 2.x versions when upgrading to newer OS versions. This could be some of its content:


# Configuration file migration from version 2.x to 3.x
Most of this is mentioned in the [changelog](https://raw.githubusercontent.com/tmux/tmux/3.1b/CHANGES), but FAQs are mentioned here for clarity.

## Special characters
Special characters like `%-\}{` have to be escaped, e.g.

* `bind S-Left swap-pane -s {left-of}` -> `bind S-Left swap-pane -s '{'left-of'}'`
* `unbind %; bind - split-window -v` -> `unbind '%'; bind '-' split-window -v`

## Format styles
Keywords have become options. Replace e.g.

* `set -g pane-border-bg colour236` -> `set -g pane-border-style bg=colour236`

**Comment by nicm** [comment]
I would welcome a migration document for the wiki but saying "2.x" and "3.x" is not specific enough, it needs to list the exact version where the change was made, whether that is 2.8 -> 2.9 or 2.9 -> 3.0. There is not that much in recent versions so you can probably them from looking at the discussion issues for 3.0 and 3.1 which have a summary of changes: https://github.com/tmux/tmux/issues?q=%22questions+and+comments%22

**Comment by yugawara** [comment]
I wanted to leave a link to this excellent page:
https://sunaku.github.io/tmux-yank-osc52.html#osc-52-escapes-the-new-way
I had to spend a lot of time searching for information before finding the above.
For my combination NeoVim (nvim) + Tmux 3.1c + Winows Terminal (Preview) on Windows 10, running Guix on WSL2.
The above is the only way I have found so far that makes Clipboard copying from the Terminal to Windows to work.

**Comment by kadarmarton** [comment]
> 
> 
> The tmux definitions of horizontal and vertical are correct. The idea is to avoid confusion for people who are used to a different definition, not to correct a mistake. If we remove one area of potential confusion by removing the terms horizontal and vertical completely, but introduce another by not linking the two types of split to the -h and -v flags, it is not an improvement.

-h and -v are just letters. Why, what does -I stand for? certainly not obvious for me. But the documentation is clear on -I. If it is clear on -h and on -v then don't worry about missing words of 'horizontal' or 'vertical'. All I can say the current sense is counterintuitive for me. My trial and error rounds always begin with an error. So say what does what (done already), but do not use the counterintuitive words of horizontal / vertical.

**Comment by kadarmarton** [comment]
As 2 out of the 10 command line flags of tmux deal with the server socket location, specify the default in the manpage: `/tmp/tmux-$(id -u)`

**Comment by nicm** [comment]
The default is already mentioned under `-L`:
~~~~
                   tmux stores the server socket in a directory under
                   TMUX_TMPDIR or /tmp if it is unset.  The default socket is
                   named default.  This option allows a different socket name
                   to be specified, allowing several independent tmux servers
                   to be run.  Unlike -S a full path is not necessary: the
                   sockets are all created in a directory tmux-UID under the
                   directory given by TMUX_TMPDIR or in /tmp.  The tmux-UID
                   directory is created by tmux and must not be world
                   readable, writable or executable.
~~~~
