### ISSUE TITLE
"curses not found" even though built ncurses from source

### ISSUE THREAD

**Issue by aboode95** [tmux/tmux#2165]
I am trying to build tmux from source.

I have built **ncurses** and **libevent** from source in `/opt/ncurses` and `/opt/libevent` respectively.
I did so by running this for ncurses (and similar for libevent):
```
./configure --prefix=/opt/ncurses
make
sudo make install
```
After that I downloaded and extracted the tmux tar, and ran:
```
./configure CFLAGS="-I/opt/libevent/include -I/opt/ncurses/include/ncurses" \
LDFLAGS="-L/opt/libevent/lib -L/opt/ncurses/include/ncurses -L/opt/libevent/include" \
CPPFLAGS="-I/opt/libevent/include -I/opt/ncurses/include/ncurses/"
```
I was able to resolve "libevent not found" error but I end up with the "curses not found" even though it is installed.
I looked into config.log and it said curses.h was missing. I looked into the folder and it was there. I don't get why I am getting this error.

Here's the [config.log](https://github.com/tmux/tmux/files/4481008/config.log).

Can someone help with what I am doing wrong?
Thanks

Using Ubuntu 18.06 and kernel 5.3.0-46-generic.

**Comment by nicm** [comment]
-L needs lib not include:
~~~~
LDFLAGS="-L/opt/libevent/lib -L/opt/ncurses/include/ncurses -L/opt/libevent/include"
                                             ^--- ***lib***
~~~~
But it might be easier to look at https://github.com/tmux/tmux/wiki/Installing#building-dependencies.

**Comment by nicm** [comment]
Also:
~~~~
CPPFLAGS="-I/opt/libevent/include -I/opt/ncurses/include/ncurses/"
~~~~
curses.h/ncurses.h is in `/opt/ncurses/include` not in `/opt/ncurses/include/ncurses`.

Change this to `-I/opt/ncurses/include`.

**Comment by aboode95** [comment]
(1) changing to `/opt/ncurses/lib` didn't work.
(2) changing to `/opt/ncurses/include` didn't help as suspected.
I ran:
```
./configure CFLAGS="-I/opt/libevent/include -I/opt/ncurses/include" \
LDFLAGS="-L/opt/libevent/lib -L/opt/ncurses/lib -L/opt/libevent/include" \
CPPFLAGS="-I/opt/libevent/include -I/opt/ncurses/include"
```
as you can see the "curses.h" file is in `/opt/ncurses/include/ncurses`

![ncurses](https://user-images.githubusercontent.com/45560996/79337165-d9fe9580-7f46-11ea-9f3d-7be24edae773.png)

I did try without changing the (2). Did not work unfortunately.

**Comment by nicm** [comment]
Ah yes I see, yes you are right where ncurses.h is.

The error in your config.log is:
~~~~
/opt/ncurses/include/ncurses/curses.h:61:10: fatal error: ncurses/ncurses_dll.h: No such file or directory
~~~~
So your curses.h doesn't work. How did you build and install ncurses?

**Comment by nicm** [comment]
There should be a `ncurses` directory in the same place as the `curses.h` file, does it exist?

**Comment by aboode95** [comment]
I downloaded the ncurses tar from [here](https://invisible-island.net/ncurses/).
I extracted it and from the extracted directory I ran:
```
./configure --prefix=/opt/ncurses
```
which gave the output:
```
** Configuration summary for NCURSES 6.2 20200212:

       extended funcs: yes
       xterm terminfo: xterm-new

        bin directory: /opt/ncurses/bin
        lib directory: /opt/ncurses/lib
    include directory: /opt/ncurses/include/ncurses
        man directory: /opt/ncurses/share/man
   terminfo directory: /opt/ncurses/share/terminfo

** Include-directory is not in a standard location
```
*As you can see there was a warning that I ignored. I am unsure if it is the cause.*

I proceeded with the installation:
```
make
sudo make install
```
It completed with no error.

**Comment by aboode95** [comment]
There is no `ncurses` directory with the `curses.h` file.

**Comment by nicm** [comment]
I think the warning is fine, let me try.

**Comment by nicm** [comment]
Oh it installed curses.h and ncurses.h inside the ncurses directory.

Try adding `-I` for both `/opt/ncurses/include` and `/opt/ncurses/include/ncurses`.

This would be a lot easier if you used pkg-config like the instructions...

**Comment by aboode95** [comment]
I did try with pkg-config. But I could only solve the 'libevent not found" error. The "curses not found error" remained. I cannot find the "pkgconfig" for ncurses.
I ran:
```
PKG_CONFIG_PATH=/opt/libevent/lib/pkgconfig ./configure
```

**Comment by nicm** [comment]
Look at the instructions at https://github.com/tmux/tmux/wiki/Installing#building-dependencies. For ncurses:
~~~~
./configure --prefix=/opt --with-shared --enable-pc-files --with-pkg-config-libdir=/opt/lib/pkgconfig
~~~~
Then you will need both /opt/ncurses/lib/pkgconfig pkg-config and the libevent one in `PKG_CONFIG_PATH` for tmux configure.

**Comment by aboode95** [comment]
ah I see! I needed to do that before installing ncurses to create its pkgconfig file.

**Comment by nicm** [comment]
I meant /opt/ncurses not /opt/lib of course.

**Comment by aboode95** [comment]
Thank you @nicm ! It works! 

I ran:
```
./configure --prefix=/opt/tmux CFLAGS="-I/opt/libevent/include -I/opt/ncurses/include -I/opt/ncurses/include/ncurses" LDFLAGS="-L/opt/libevent/lib -L/opt/ncurses/lib -L/opt/libevent/include" CPPFLAGS="-I/opt/libevent/include -I/opt/ncurses/include -I/opt/ncurses/include/ncurses"
make
sudo make install
```
And then I followed the instruction of the page you shared; Added these lines to `~/.profile`:
```
export PATH=/opt/tmux/bin:$PATH
export LD_LIBRARY_PATH=/opt/libevent/lib:/opt/ncurses/lib:$LD_LIBRARY_PATH
export MANPATH=/opt/tmux/share/man:$MANPATH
```
logged out and logged back in and it is working. **Thank you again for your help @nicm!**

**Comment by nicm** [comment]
Great stuff.
