### ISSUE TITLE
styles in display-menu names gets reversed for current selected

### ISSUE THREAD

**Issue by cevhyruz** [tmux/tmux#2166]
It seems style parsing in display-menu gets reversed.
It would be awesome if it can support style on names just like in choose-tree.

Also I think the current highlight should get it's style from mode-style

**Comment by nicm** [comment]
Current item is always reversed.

**Comment by cevhyruz** [comment]
I know it should be. but if you add additional styles like this:
```
  display-menu -T "TITLE" -x 0 -y P \
  "#[push-default fg=red] Menu name one " 'Y' ""  \
  " Menu name two" 'N' "" \

```
somehow it also flips the added styles in menu name

**Comment by nicm** [comment]
I don't know what you mean, it looks fine for me. What do you want it to look like?

**Comment by cevhyruz** [comment]
I mean. I think it should behave more just like what you pass in -F argument.
like when you do this:
```
choose-tree -F "#[fg=yellow] #W"
```

**Comment by nicm** [comment]
You can add `noreverse`?

**Comment by cevhyruz** [comment]
What I really want to achieve is to put differently styled glyphs beside menu names that won't get reversed upon highlighting them.
```
 display-menu -T "TITLE" -x 0 -y P \
  "#[fg=red]  #[default] File " 'Y' ""  \
  "#[fg=blue]  #[default] Menu name two" 'N' "" \

```

**Comment by cevhyruz** [comment]
Tried `noeverse` but then I don't get a full-width highlight selection

**Comment by nicm** [comment]
How could it be both full width and not reversed?

**Comment by nicm** [comment]
Maybe you're right perhaps it would make sense for menus to use mode-style for the selected item.

**Comment by nicm** [comment]
Not sure what we would do with dim then though.

**Comment by nicm** [comment]
Try this please: [tmux-menu-mode-style.diff.txt](https://github.com/tmux/tmux/files/4482248/tmux-menu-mode-style.diff.txt)

**Comment by cevhyruz** [comment]
Yeah.. This is it!

**Comment by cevhyruz** [comment]
Thanks! I'll be closing this issue now. I'll comment again if I find something
