### ISSUE TITLE
tmux crashes after window resize: offset too big

### ISSUE THREAD

**Issue by luizribeiro** [tmux/tmux#2167]
### Issue description

I'm having issues with tmux crashing after resizing my iTerm2 window. I generally keep the terminal fullscreen, but after moving it to fill only half of the screen I'm getting tmux to crash with the following on the logs:

```
1586990024.884911 recalculate_sizes: @0 is 364,104
1586990024.884916 recalculate_sizes: @0 changed to 164,104
1586990024.884933 window_pane_resize: %0 resize 1x104
1586990024.884943 screen_reflow: cursor 0,790 is 4294967295,499
1586990024.886349 fatal: offset too big
```

### Required information

Please provide the following information:

* tmux version: `tmux 3.0a`
* Platform: `Linux x86_64`
* $TERM inside tmux: `screen-256color`
* $TERM outside tmux: `xterm-256color`
* Logs from tmux: see above

**Comment by nicm** [comment]
Full server log please.
