### ISSUE TITLE
event.h is deprecated

### ISSUE THREAD

**Issue by lhoenig** [tmux/tmux#2168]
"The <event.h> header is deprecated in Libevent 2.0 and later; please
  use <event2/event.h> instead.  Depending on what functionality you
  need, you may also want to include more of the other event2/
  headers."

As tmux depends on libevent2 anyways I see no problems adhering to this suggestion, other than a few extra include lines.

**Comment by nicm** [comment]
This is not going to happen for the moment because we still use libevent 1.4 on OpenBSD and it is not worth the portable goop until they actually remove the header.

**Comment by lhoenig** [comment]
I see, thank you for the quick reply!

**Comment by nicm** [comment]
I thought of doing it via -I in configure.ac but it would be a pain and probably be hard to make work properly, I'm not sure it is worth it for the moment. Thanks for mentioning it anyway :-).
