### ISSUE TITLE
Crash when trying to start long command

### ISSUE THREAD

**Issue by ferreum** [tmux/tmux#217]
Tmux always crashes for me when running the following bash command:
```
$ tmux new-session echo {1..38}asdfasdfasdfasdfasdfasdf
lost server
```
Afterwards all running tmux sessions are lost.
It does not crash when I reduce the arguments to {1..37}.
Tmux version is 2.1.r175.g3b83bda just built on arch linux with tmux-git aur package.

**Comment by ThomasAdam** [comment]
That's not a crash.  That's tmux `fatal`ing because of an xsnprintf() overflow:

```
1448543935.888734 continuing cmdq 0xd47770: flags 0, client 0xd4e500
1448543935.888761 fatal: xsnprintf: overflow: Success
```

**Comment by nicm** [comment]
Should be fixed soon.
