### ISSUE TITLE
drag scrolling support

### ISSUE THREAD

**Issue by scandum** [tmux/tmux#2170]
A toggle to scroll by dragging would be nice. Useful when using tmux on a phone / tablet.

**Comment by nicm** [comment]
No idea what this means.

**Comment by scandum** [comment]
Right now tmux selects when dragging the mouse. That is: press left mouse button and hold it, move mouse, release left mouse button.

Alternative behavior would be to scroll up/down/left/right depending on the direction and distance of the drag.

**Comment by nicm** [comment]
I don't want this behaviour builtin but you might be able to script it, the `mouse_y` format gives you the mouse y position so you could save it on `MouseDrag1Pane` and use it in `MouseDragEnd1Pane` to send the appropriate `copy-mode`/`send -X scroll-up` commands.

There isn't key binding for "drag in progress" though so it would only update when the drag was finished. It may be possible to add this however if the above works.
