### ISSUE TITLE
Difference in behavior of tmux send-keys -t command.

### ISSUE THREAD

**Issue by konono** [tmux/tmux#2171]
### Issue description

Difference in behavior of tmux send-keys -t when written in .tmux.conf and when not written.
I want to create a new pane and send commands to that pane with send-keys.
When tmux send-keys is executed in the console, it behaves ideally, but when it is written in .tmux.conf and called with a shortcut key, it behaves differently.

My tmux.conf.
```
bind \} run "source ~/senv && tmux split-window -h" \; send-keys -t :"${WIN_ID}"."${PANE_ID}" 'echo TEST' ENTER
```
```
❯ cat ~/senv
WIN_ID=`tmux list-windows |grep active |grep -o "^[0-9]"`
PANE_ID=`tmux list-panes |grep active |grep -o "^[0-9]"|xargs -I% echo %+1|bc`
```

Test result:
 - In console
```
tmux run "source ~/senv && tmux split-window -h" \; send-keys -t :"${WIN_ID}"."${PANE_ID}" 'echo TEST' ENTER
```
-> Echo test run on new pane

 - execute shortcut (C-b + })
-> Echo TEST is executed on the existing pane and a new pane is created

### Required information

Please provide the following information:
```
❯ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 3.0a
xterm-256color
```

**Comment by nicm** [comment]
I'll take look but why are you using grep to get the active pane? It's the default...

**Comment by konono** [comment]
Thank you for your support.

You are right.
So,  I didn't need "$ {WIN_ID}".
${PANE_ID} is a variable with +1 added to the active pane index.
```
PANE_ID=`tmux list-panes |grep active |grep -o "^[0-9]"|xargs -I% echo %+1|bc`
```

**Comment by nicm** [comment]
Doesn't "-t:.+1" work?

**Comment by konono** [comment]
I tried the below command but couldn't send-keys to the new pane.
tmux run "tmux split-window -h" \; send-keys -t :. + 1 'echo TEST'

**Comment by nicm** [comment]
You have extra spaces?

Try:

tmux splitw -h \; send -t:.+1 'echo TEST'

But is that what you want? To send it to the new pane + 1?

If you are trying to send it to the new pane itself, you don't need -t at
all.

**Comment by konono** [comment]
I understood that.
The behavior of the commands below was ideal.
```
tmux splitw -h \; send -t:. 'echo TEST'
```
However, if the above command is written in .tmux.conf and executed, it behaves differently :/
tmux.conf
```
bind \} run "source ~/senv && tmux split-window -h" \; send-keys -t :. 'echo TEST' ENTER
```

**Comment by nicm** [comment]
Command run inside run-shell won't update the default target, either run it
all in run-shell or all without run-shell.

**Comment by nicm** [comment]
Is this resolved?
