### ISSUE TITLE
crash when creating an empty pane from Vim

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2173]
### Issue description

Tmux crashes when creating an empty pane from Vim.

To reproduce, run these shell commands:

    tmux -Lx -f/dev/null
    vim -Nu NONE

From Vim, run this Ex command:

    :call system('tmux splitw -PF "" ""')

Finally, press some key; e.g. `i`.

### Required information

 - `$ tmux -V`: tmux next-3.2, commit dd5299841a87c0bf842488f7f9feb84b7e37c819
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - [logs](https://github.com/tmux/tmux/files/4512418/tmux.log.gz) from `$ tmux -vv -Lx -f/dev/null`
 - [backtrace](https://github.com/tmux/tmux/files/4512419/backtrace.txt) from `$ gdb -n -ex 'thread apply all bt full' -batch tmux ./core`
 - [`$ tmux info`](https://github.com/tmux/tmux/files/4512466/tmux.info.txt)
 - [`$ ps aux`](https://github.com/tmux/tmux/files/4512500/ps.aux.txt)
 - [`$ ~/bin/signals-disposition $(tmux display -p '#{pid}')`](https://github.com/tmux/tmux/files/4512490/signals.disposition.txt)

---

It's a recent regression introduced by one of these commits:

    135bb1edeeab3faae8001100aa7c173be9aa91e1
    c91b4b2e142b5b3fc9ca88afec6bfa9b2711e01b
    c706aadf52f746b695aed34297ad0a910d74eb1b

---

I've tried to get more info via `gdb(1)`:

    $ gdb -q --args tmux -Lx -f/dev/null
    (gdb) run
    $ vim -Nu NONE
    :call system('tmux splitw -PF "" ""')
    " press 'i'
    (gdb) p *ctx
    (gdb) p *ctx->s
    (gdb) p *ctx->s->grid

But all the commands output the same message:

    No symbol "ctx" in current context.

---

The issue disappears if `-PF` is not passed to `splitw`.

**Comment by nicm** [comment]
To run tmux in gdb you either need to do `set follow-fork-mode on` before `run`.

Or more reliable is to start tmux normally then find the server PID and attach gdb from outside:

~~~~
$ tmux display -p '#{pid}'
1234
$ gdb ./tmux 1234
(gdb) c
...
~~~~

Alternatively you can do the print (`p`) commands after you load the core into gdb. But the variables need to be in the current frame.

**Comment by nicm** [comment]
Please load the core into gdb and do `p *s` and show me the output. The `ctx` stuff was for your old backtrace.

**Comment by nicm** [comment]
Also `p *s->grid`.

**Comment by lacygoill** [comment]
> Please load the core into gdb and do p *s and show me the output.

I get this message:

    No symbol table is loaded.  Use the "file" command.

And the `file` command gives:

No executable file now.
No symbol file now.

**Comment by nicm** [comment]
That's odd, the tmux binary built in the source directory should have symbols. Did you point gdb to the fight binary? `gdb ./tmux ./core`

**Comment by lacygoill** [comment]
Pointing gdb to the tmux binary helps, but how can I redirect all the output in a file? I can't copy it.

**Comment by nicm** [comment]
Run gdb in tmux and copy with it? Or in script?

**Comment by lacygoill** [comment]
I'm not used to gdb, and I don't think I can run it inside tmux, since the latter crashes; anyway I used `set logging on`, and I ran these 4 commands:

    (gdb) p *ctx
    (gdb) p *ctx->s
    (gdb) p *ctx->s->grid
    (gdb) p *s->grid

Here is the output:

    $1 = {wp = 0xb6d1f0, s = 0xb6d3b8, sync = 0, item = 0xb98d80, scrolled = 0, 
      bg = 8, cells = 1, written = 0, skipped = 0}
    $2 = {title = 0xb9b150 "ubuntu", path = 0x0, titles = 0x0, grid = 0xb76570, 
      cx = 0, cy = 22, cstyle = 0, ccolour = 0xb9ac80 "", rupper = 0, rlower = 10, 
      mode = 28, saved_cx = 0, saved_cy = 2, saved_grid = 0xb951f0, saved_cell = {
        data = {data = "E", '\000' <repeats 16 times>, have = 1 '\001', 
          size = 1 '\001', width = 1 '\001'}, attr = 0, flags = 0 '\000', fg = 8, 
        bg = 8, us = 0}, saved_flags = 1, tabs = 0xb9a7b0 "", sel = 0x0, 
      write_list = 0xb71500}
    $3 = {flags = 0, sx = 80, sy = 11, hscrolled = 0, hsize = 1, hlimit = 2000, 
      linedata = 0xb71370}
    $4 = {flags = 0, sx = 80, sy = 11, hscrolled = 0, hsize = 1, hlimit = 2000, 
      linedata = 0xb71370}

**Comment by nicm** [comment]
OK thanks, the cursor is on line 22 which is outside the pane (height 11) which shouldn't happen, I'll take a look tomorrow.

**Comment by lacygoill** [comment]
Thanks, I hope it will also fix my Vim plugin.  It has always worked correctly up to a few days ago.  Now, it's stuck on [this line](https://github.com/lacygoill/vim-logevents/blob/9f3a9be1d86bfeb2f28dd04a8400151ce1ecd85e/autoload/logevents.vim#L365).

It runs something like this:

    tmux splitw -c '/run/user/1000/vim' -dI -h -p 25 -PF "#D"

I've always been able to run this command from Vim via the `system()` function.  Now, for some reason, when my plugin runs the same command, Vim hangs.  According to `git-bisect(1)`, the offending commit is one of the 3 mentioned in the OP.

If I remove the `-h` and `-p` arguments, and call `system()` without `:silent`, then Tmux crashes.  Here is what Vim's help says about the effect of `:silent` on `system()`:

    When prepended by |:silent| the terminal will not be set to
    cooked mode.  This is meant to be used for commands that do
    not need the user to type.  It avoids stray characters showing
    up on the screen which require |CTRL-L| to remove. >
            :silent let f = system('ls *.vim')
    <

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/4514057/x.diff.txt)

**Comment by lacygoill** [comment]
It fixes the crash, but something is still wrong. Vim still hangs when I run:

    :call system('tmux splitw -PF "" ""')

Note that I don't pass `-I` to `splitw`, and the same command works without blocking the shell when run outside Vim; i.e. I don't have to press `C-d`.  So what is Vim waiting for now?  And why didn't it need to wait in the past?

**Comment by nicm** [comment]
I think this is a different issue. Can you show me an updated server log?

**Comment by lacygoill** [comment]
Ah ok, if you want me to open a different report, let me know.

Here are updated logs: [tmux.logs.tar.gz](https://github.com/tmux/tmux/files/4514929/tmux.logs.tar.gz)

**Comment by lacygoill** [comment]
Ah sorry, I didn't use the right binary. Let me check again.

**Comment by lacygoill** [comment]
It looks like Vim doesn't hang anymore, which is good; but the tmux command fails when run from Vim; i.e. no pane is created.

**Comment by lacygoill** [comment]
I'll open a new report.  Thank you very much for fixing the crash.

**Comment by nicm** [comment]
Show me the server log please.

**Comment by lacygoill** [comment]
Ok, this is confusing because I get different results, probably because I'm using several servers with different binaries, and invoking the latter multiple times to reproduce the issue.  So, I've killed all the servers, and I've installed the patched binary with `$ sudo make install` so that I don't have to specify any particular path.

The result is that the crash is fixed, but Vim still hangs.  Here are new logs: [tmux.logs.tar.gz](https://github.com/tmux/tmux/files/4515019/tmux.logs.tar.gz)

**Comment by lacygoill** [comment]
I'm trying this patch generated by diff'ing the current `screen.c` with [this one](https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/usr.bin/tmux/screen.c?rev=1.66&content-type=text/plain):

```diff
diff --git a/screen.c b/screen.c
index a1dc52c8..f416ac37 100644
--- a/screen.c
+++ b/screen.c
@@ -21,6 +21,7 @@
 #include <stdlib.h>
 #include <string.h>
 #include <unistd.h>
+#include <vis.h>

 #include "tmux.h"

@@ -47,7 +48,7 @@ struct screen_title_entry {
 };
 TAILQ_HEAD(screen_titles, screen_title_entry);

-static void	screen_resize_y(struct screen *, u_int, int);
+static void	screen_resize_y(struct screen *, u_int, int, u_int *);
 static void	screen_reflow(struct screen *, u_int, u_int *, u_int *);

 /* Free titles stack. */
@@ -253,7 +254,7 @@ screen_resize_cursor(struct screen *s, u_int sx, u_int sy, int reflow,
                reflow = 0;

        if (sy != screen_size_y(s))
-		screen_resize_y(s, sy, eat_empty);
+		screen_resize_y(s, sy, eat_empty, cy);

        if (reflow)
                screen_reflow(s, sx, cx, cy);
@@ -280,7 +281,7 @@ screen_resize(struct screen *s, u_int sx, u_int sy, int reflow)
 }

 static void
-screen_resize_y(struct screen *s, u_int sy, int eat_empty)
+screen_resize_y(struct screen *s, u_int sy, int eat_empty, u_int *cy)
 {
        struct grid	*gd = s->grid;
        u_int		 needed, available, oldy, i;
@@ -329,6 +330,7 @@ screen_resize_y(struct screen *s, u_int sy, int eat_empty)
                        if (available > needed)
                                available = needed;
                        grid_view_delete_lines(gd, 0, available, 8);
+			(*cy) -= available;
                }
        }
```

But the compilation fails:

    screen.c:24:17: fatal error: vis.h: No such file or directory
    compilation terminated.
    Makefile:837: recipe for target 'screen.o' failed
    make: *** [screen.o] Error 1

I've tried to find all packages providing a `vis.h` file, and found these candidates:

    brickos: /usr/include/brickos/sys/vis.h
    freebsd-glue: /usr/include/freebsd/vis.h
    heimdal-multidev: /usr/include/heimdal/roken/vis.h
    libbsd-dev: /usr/include/bsd/vis.h

I installed them all, but the compilation still fails with the same error message.  Do you know which dependency needs to be installed for the compilation to succeed?

**Comment by lacygoill** [comment]
Never mind, the compilation succeeds from the latest github commit.  But Vim still hangs; I'll open a new issue for that.

**Comment by lacygoill** [comment]
Ok, I don't know which commit has fixed the issue, but it's completely fixed. Thanks again.
