### ISSUE TITLE
Tmux client hangs when displaying the id of a pane from a key binding

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2174]
### Issue description

To reproduce, run these shell commands:

    tmux -Lx -f/dev/null
    tmux bind f run "tmux display -pt':.{last}' '#{pane_id}' 2>/dev/null"

Finally, press `C-b f`.

### Required information

 - `$ tmux -V`: tmux next-3.2, commit dd5299841a87c0bf842488f7f9feb84b7e37c819
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`: [tmux.logs.tar.gz](https://github.com/tmux/tmux/files/4515296/tmux.logs.tar.gz)

---

This breaks the plugin [tmux-fingers](https://github.com/Morantron/tmux-fingers).

---

This is a regression introduced by one of these commits:

    135bb1edeeab3faae8001100aa7c173be9aa91e1
    c91b4b2e142b5b3fc9ca88afec6bfa9b2711e01b
    c706aadf52f746b695aed34297ad0a910d74eb1b

**Comment by nicm** [comment]
I can't reproduce this, when I follow your instructions I get:
~~~~
'tmux display -pt':.{last}' '%0' 2>/dev/null' returned 1
~~~~
If I create a new pane first it just displays `0` or `1`.

Both of these are what I would expect.

It is hard to tell what you are doing differently from the log, can you be more specific?

Can you add `-vv` to the `tmux display` inside the `run` which will make it generate a `tmux-client*.log`, and show me that log also?

**Comment by nicm** [comment]
Never mind, I can see this on Linux but not on OS X or OpenBSD.

**Comment by nicm** [comment]
We lost the bit that turns off epoll on Linux (epoll is broken on ttys).

I am not sure this fixes the problem, there seems to be something else funny happening now.
~~~~
--- a/tmux.c
+++ b/tmux.c
@@ -398,5 +398,5 @@ main(int argc, char **argv)
        free(label);

        /* Pass control to the client. */
-       exit(client_main(event_init(), argc, argv, flags, feat));
+       exit(client_main(osdep_event_init(), argc, argv, flags, feat));
 }
~~~~

**Comment by lacygoill** [comment]
I'm going to try the patch, and tell you whether it fixes the issue as well as tmux-fingers.

**Comment by nicm** [comment]
I've applied it now. It seems OK for me, the other problem I thought I saw was me doing something stupid... Let me know anyway.

**Comment by lacygoill** [comment]
Yes, it fixes the issue. Thank you very much for the quick fix.

**Comment by nicm** [comment]
OK great stuff, thanks!
