### ISSUE TITLE
TPM not working on next-3.2 

### ISSUE THREAD

**Issue by yamsu** [tmux/tmux#2175]
tmux -V :: tmux next-3.2
Linux XXXX 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
TERM (outside tmux) screen-256color

I just checked out the latest tmux from GitHub. I had no issue with the compilation and install. However, I was not able to run TPM, which provides useful plugins such as ressurect, etc.

If I run TPM the tmux startup is stuck and doesn't show any sessions. With -b argument tmux starts without any plugins and prefix+I/prefix+U don't work.
```
run -b "~/.tmux/tpm/tpm
```
There is no problem with my setup with tmux 3.0a, tarball release.

**Comment by nicm** [comment]
Logs?

Are you sure you have df1bce40f0863b024cbd6d8ad56fd3a8914e68ed?

**Comment by yamsu** [comment]
Yeah I tried that and now i'm on [d4826aa](https://github.com/tmux/tmux/commit/d4826aa1aae9b5a3efe6764f87d9c9b897f4723e)
All my terminal windows lose their prompt and i can't execute any commands once I run tmux.
[tmux-server-29505.log](https://github.com/tmux/tmux/files/4516127/tmux-server-29505.log)

**Comment by nicm** [comment]
Are you sure you are running the right tmux binary? This log is still using epoll. Make sure you kill tmux entirely (`pkill tmux` or `tmux kill-server`) and make sure you are running the latest build.

**Comment by yamsu** [comment]
I have checked its the same version, perhaps the previous log was older. I am attaching a new log, after doing the following:
```
git pull
./configure
make
./tmux -vv
```
Now i'm on [bb3177](https://github.com/tmux/tmux/commit/bb31776dd3b48fdd80e582deb7abc4e17d0dacf3)
Same issue persists but i'm able to get a tmux window after running to command from another terminal window, but there is no prompt and the plugin are not running.

[tmux-server-5069.log](https://github.com/tmux/tmux/files/4516234/tmux-server-5069.log)

**Comment by nicm** [comment]
Do you see your prompt if you run with `./tmux -f/dev/null new`?

**Comment by nicm** [comment]
Are you sure all these commands are running the new tmux as well? They aren't running `/usr/bin/tmux`?

**Comment by yamsu** [comment]
Yes! Again the first terminal window at I use to start =~/github/tmux/tmux= doesn't respond after running the command. on a second terminal window if i run =~/github/tmux/tmux -f/dev/null new= i can see the session and the prompt is also present. But tpm is not running.
I have tmux 3.0a installed.

**Comment by yamsu** [comment]
After installing tmux next-3.2, now its working!
I guess two version of tmux were competing with each other.
