### ISSUE TITLE
why is tmux getting slower and slower version 2.1

### ISSUE THREAD

**Issue by dongrixinyu** [tmux/tmux#2177]
### Issue description

start up a tmux session about several months ago, and the response 
is getting slower and slower.
reboot tmux session can not speed up.

what should i do?
cut logs? or ...

### Required information

ubuntu 16.04
tmux 2.1 / 1.*

**Comment by nicm** [comment]
tmux 2.1 is 6 years old and no longer supported, please try tmux 3.0a.

**Comment by dongrixinyu** [comment]
thx!
