### ISSUE TITLE
Question: safe delimiters to use when parsing `tmux list-* commands`

### ISSUE THREAD

**Issue by infokiller** [tmux/tmux#2179]
Hi,

I'm writing a shell script that parses the output of commands such as `list-panes` and `list-sessions`. In order to parse the fields in the output of each line, I'm using a delimiter in the format string, for example: `tmux list-panes -a -F "#{session_name}${delim}#{window_name}${delim}#{pane_title}"`.
Are there any delimiters that are safe to use, meaning they are guaranteed not to be part of the fields themselves (session name, pane title, etc.)?
I tried to use the null character, but it seems that tmux doesn't continue parsing the format argument after it encounters it. For example, `tmux list-panes -F $'before\0after'` will only print "before".
Using a tab character does work (`tmux list-panes -F $'before\tafter'`) and in my testing session/window/pane names won't contain it (even if set using `tmux rename-window $'\t'`).
Is this a good way to go?

Thanks!

**Comment by nicm** [comment]
Well... it is a bit inconsistent TBH.

Session names cannot have `:` or `.` in them. But window names can.

Window names can't have tabs in them (tmux will convert them to `\t`). But it doesn't do the same for session names:
~~~~
$ tmux renamew "a$(printf "\011")b"
$ tmux lsw -F'#{window_name}'
a\tb
$ tmux rename "A$(printf "\011")B"
$ tmux ls -F'#{session_name}'
A       B
~~~~
I will fix it so it sanitizes session names also, but that doesn't help you much with current tmux versions.

Personally I'd just use tab anyone silly enough to put them in their names can suffer.

If you want to be completely safe, a better way is to use IDs, which have a fixed form:
~~~~
$  tmux lsp -aF '#{session_id} #{window_id} #{pane_id}'
$0 @0 %0
$0 @1 %1
~~~~~
You can then get individual names with `display -p`:
~~~~
$ tmux display -pt'$0' '#{session_name}'
A       B
$ tmux display -pt'@1' '#{window_name}'
ksh
~~~~

**Comment by infokiller** [comment]
Thanks! I think I'll use tabs and hope no one uses them for naming.
I guess I could verify it (by first calling `tmux list-panes` without the delimiter) and give the user a warning, though this introduces a race condition (what if new panes were added since the first call?), which I don't think really matters in practice.

**Comment by nicm** [comment]
Tabs will be replaced in session names from tmux 3.2.
