### ISSUE TITLE
make error: dereferencing pointer to incomplete type ‘struct bufferevent’

### ISSUE THREAD

**Issue by shamilbi** [tmux/tmux#2180]
git branch = master
uname -sp = Linux Intel(R) Core(TM) i5-4430S CPU @ 2.70GHz
$TERM outside of tmux = echo $TERM = xterm-256color
gcc --version = gcc (GCC) 9.3.0

make log (short):
client.c:224:35: error: dereferencing pointer to incomplete type ‘struct bufferevent’
  224 |   left = EVBUFFER_LENGTH(cf->event->output);

make log (full):
[tmux-2020-04-25.log](https://github.com/tmux/tmux/files/4532524/tmux-2020-04-25.log)

**Comment by nicm** [comment]
What libevent version do you have? This seems like a problem with your
libevent install.

**Comment by shamilbi** [comment]
Sorry it was libevent, upgraded to 2.1.11 and the error disappeared
Closing issue
