### ISSUE TITLE
Unknown command with any .tmux.conf file

### ISSUE THREAD

**Issue by Espenol** [tmux/tmux#2181]
### Issue description
I can not use any configuration for tmux. Adding a .tmux.conf file will give me an `unknown command` error message no matter what I write in the configuration file. With the following .tmux.conf file: 

﻿
``` # List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm' 
```

I get the following error all the time: 
![bilde](https://user-images.githubusercontent.com/17748952/80281968-0ff20580-870f-11ea-80b3-d518fa5fdc20.png)
if I remove the first, commented line I get `unknown command: set`. What gives? 

### Required information
``` uname -sp: Linux unknown
tmux -V: tmux 3.1
echo $TERM outside tmux: xterm-256color
echo $TERM inside tmux: screen
tmux kill-server: no server running on /tmp/tmux-1000/default
tmux -vv new: /home/espenol/.tmux.conf:1: unknown command: 
```

Logs as follows. 
[tmux-server-417.log](https://github.com/tmux/tmux/files/4533112/tmux-server-417.log)
[tmux-client-415.log](https://github.com/tmux/tmux/files/4533113/tmux-client-415.log)
[tmux-out-417.log](https://github.com/tmux/tmux/files/4533114/tmux-out-417.log)

**Comment by nicm** [comment]
Has your editor put a Unicode BOM in the file? Are you sure it has Unix line endings? Check the file with `cat -v .tmux.conf` for strange characters.

**Comment by nicm** [comment]
Yes the first line of your file is a BOM, from the log which tmux doesn't understand:
~~~~
1587823846.711274 cmd_parse_build_commands: 1 \357\273\277

**Comment by Espenol** [comment]
Thank you! Opening `.tmux.conf` with vim and using the command `:set nobomb` successfully removed the bom characters at the start of the file, and now it runs properly.
