### ISSUE TITLE
tmux new-session command ignores a mount point

### ISSUE THREAD

**Issue by mudongliang** [tmux/tmux#2185]
### Issue description
```
mount_point/a/b/c $ tmux new -s example
--> 
mount_point $
```

if the current directory (i.e., `mount_point/a/b/c`) is under one mount point, the `pwd` of this new session will be the mount point (i.e., `mount_point`), other than `mount_point/a/b/c`. I could always reproduce this issue under my `Ubuntu 18.04 LTS` system.

### Required information
* tmux version (tmux 2.6).
* Platform (Linux x86_64).
* $TERM inside and outside of tmux (xterm-256color).

**Comment by nicm** [comment]
Does this still happen with tmux 3.1 or master?

**Comment by mudongliang** [comment]
I am sorry. It is not the issue of tmux. As this is server desktop, someone modified the `.bashrc` and added one command - "cd mount_point".
