### ISSUE TITLE
command line flag --version

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [tmux/tmux#2187]
I just had a weird experience. I tried to get my current version number by running `tmux --version` and it failed. So did `tmux -v`. This is maybe a trivial request, but would you add a simple versioninfo flag to the command line interface? `tmux -p {%version}`, or whatever it actually is, is unnecessarily arcane.

**Comment by nicm** [comment]
`tmux -V`.

**Comment by nicm** [comment]
`--version` is a GNU extension and `-v` is already used for "verbose logging". We use `-V` to match other *BSD projects like OpenSSH.
