### ISSUE TITLE
Can not scrollback in Ubuntu 15.04 

### ISSUE THREAD

**Issue by chaozhn** [tmux/tmux#219]
I use Ubuntu 15.04 and now I compiled tmux 2.1 on it. But I still can not get scrollback. I googled and also added the line: **set -ga terminal-overrides ',xterm*:smcup@:rmcup@"** in my .tmux.conf. Is there a bug on Ubuntu 15.04? Can you help me address?
Thanks a lot!

**Comment by nicm** [comment]
What are you trying and what are you expecting to happen?

**Comment by chaozhn** [comment]
@nicm I mean if the output in terminal is over screen and normally the scroll bar will be shorten and I can drag it up to see the history output, but I can get it in tmux. The issue doesn't exist in my MacOS. Hope you can understand what I said. Thanks!

**Comment by nicm** [comment]
Because tmux has multiple programs running in it and it is a full screen application, terminals may not get all the information they need to put lines into their scrollback. That's why tmux has it's own history for each pane.

**Comment by chaozhn** [comment]
@nicm I just want to know how I can get the same function in tmux to see the screen history, is there other shortcuts for scrollback?
Thanks

**Comment by nicm** [comment]
C-b [ enters copy mode.

**Comment by nicm** [comment]
Or C-b PageUp

**Comment by chaozhn** [comment]
@nicm Thanks a lot!
