### ISSUE TITLE
feature: foreground attached server mode

### ISSUE THREAD

**Issue by etosan** [tmux/tmux#2190]
### Issue description

As of now `tmux` cannot be easily supervised. Foreground server mode would allow for properly managed `tmux` server instances.

First background information. For several clients and user groups I implemented feature that could be called as "permanent shell session". It is often loved by my less experienced (unix) users. 

User has their tmux server constantly running, and when they login remotely (ssh), they are presented with `whiptail` scripted list of `tmux` sessions to join (dialog style). Later I found out `tmux` has even builtin session picker, but these less knowledgeable users alike like the `whiptail` "TUI" script look better. Being reminded that they have sessions running, users tend to manage them rather well. Anyway so far so good and this works splendidly.

The problem is when I need to terminate or otherwise (signal) control user's server (for whatever reason: update, jail/container/vm teardown, you name it). This is especially bad in jails, and "containers" but pops up even on normal systems, like my own box). 

In the setup I describe, one usually runs services "supervised", eg under some management scheme like systemd, runit, s6, monit, daemontools or what have you. Under such scheme actual service providing daemon **must not doublefork**, so that parent supervising process can send signals directly to child (eg. daemon) PID. Unfortunately besides `-C, control mode`, `tmux` always doubleforks.

Even in control mode, actual `tmux` daemon instance is not the one that remains attached to term, or supervisor pipes,  but the one that doubleforks from control mode listening `tmux` process. 

Even if handling instance remains running after all session are closed, with setting `exit-empty off`, it's impossible to supervise it sanely, because it always "forks away" from the supervisor.

Fortunately `tmux` provides `start-server` command and combined with above mentioned setting, this almost does what one wants ... but server still does the dreaded doublefork, escaping from within supervision.

### Suggested solution

Extend `start-server` with (for example) `-f, foregorund` flag. When started this way initiating process would exec right into actual tmux server, replacing the current process with it, instead of doubleforking. `fd0` should be expected to point to `/dev/null` and `fd1`, `fd2` to log subsystem pipes (journald, runit/s6/daemontools logpipes) or whatever. This would also prevent polluting `tmux -${flag}` namespace with foregrounding flag, but any solution is fine.

Service run script/command can now be constructed: `tmux start-server -f`

Now the spawning parent (supervisor, but also terminal even) can send signals directly to tmux daemon instance, notifying it when it should terminate it's children (in case of service shutdown) or whatever.

It would be cool if `tmux` could be instructed to log session connections/disconenctions along with `/dev/pts` to fd1, in this mode, but even staying put in foreground as is would be amazing. 

### Required information

* tmux version: tmux 3.0a, 3.1a
* Platform: Linux, Freebsd.

Thank you for your consideration.

**Comment by nicm** [comment]
I was just thinking about this this morning. It has come up before and I didn't like the idea but I think I would be OK with it now so long as it doesn't mess too much with the normal way of running. I don't intend to add it myself but perhaps you can dig out some of the older issues which had code changes.

I still don't really understand why people keep writing init systems that can't handle the process for becoming a daemon that has been in use essentially unchanged for 40 years, but if they can't do it then they can't do it.

**Comment by etosan** [comment]
Maybe the time is right then. If you are really willing to give in there are "pretty good" reasons.

Don't worry I understand you, I used to be skeptical myself (cca 7 years back), but by now I am fully "rotten" convert. I have been working on article about this for some time, maybe your interest in this could motivate me to finish it? Would there be will to read it? It's kinda long.

Anyway back to topic, you are saying if I dig out patches to do it, you are open to pulling it in right?  

Sounds like a challenge.

**Comment by nicm** [comment]
Try this against master please: [tmux-D.diff.txt](https://github.com/tmux/tmux/files/4567436/tmux-D.diff.txt)

**Comment by nicm** [comment]
Part of the reason this is now useful is that it ridiculously complicated to get gdb to work consistently on OS X, and lldb does not support `follow-fork-mode`.

**Comment by nicm** [comment]
Did you try this change? Here is an updated diff against master: [tmux-D2.diff.txt](https://github.com/tmux/tmux/files/4586105/tmux-D2.diff.txt)

**Comment by etosan** [comment]
I have to apologize first. Sorry for not reporting back right away, I had storage problems last week, basically had to rebuild storage anew. My daily driver is now fully restored.

I am now on  [tmux-D2.diff.txt](https://github.com/tmux/tmux/files/4586105/tmux-D2.diff.txt) and it seems to work perfectly! 

Supervision control with all major three suites: deamontools, runit and s6 works as intended.

SIGUSR1 regenerates deleted socket, SIGTERM teminates "gracefully" (whatever that means).

Question of mine is that is top level `-D` option better than `start-server -D` design wise?

**Comment by nicm** [comment]
OK thanks, I will look over this again and apply it next week. I looked at adding it to `start-server` but by the time `start-server` is run the server has already been started, so it means the client would need to look at the command flags which it currently doesn't do. I don't think it makes much difference having it as a `tmux` flag instead really.

**Comment by nicm** [comment]
The only thing I am unsure about is automatically setting `exit-empty` to off. It may be better not to do that and to instead allow a command, so you would do something like `tmux -D new` or `tmux -D start \; set exit-empty off`. But I'm not entirely sure which is better.

**Comment by etosan** [comment]
So basically by the time argv 'action-words' are "parsed", server is already forked, understood. 

One last thing, I noticed SIGHUP currently teminates, I guess this is intended. 

Although that is completely acceptable behavior, in many daemons that signal means reload config. I am aware it is by no means a rule set in stone, but I know at least two "professional" admins expecting that unified SIGHUP handling is universal.

Do you think it is worth at least ignoring it in server process?

**Comment by nicm** [comment]
`SIGHUP` is ignored by daemons, but with this `-D` flag tmux is not a daemon, it is a foreground process and with foreground processes `SIGHUP` means that the tty has disappeared and the process should exit, so I think that is the right thing to do.

**Comment by etosan** [comment]
Regarding the handling of `exit-empty` I am okay with anything you come up with. 

I am currently having it set to off in config.

I see this as very valuable, but rather specialty feature, that will be realistically used by at most 10% of tmux users. These will probably be hard-core advanced users, people doing "eternal sessions" and developers (you mentioned macOS). I hope these people will be able to configure `exit-empty` properly on their own.

Of course automatic switching logic (`set exit-empty off` when `-D`, behave normally otherwise) would be most convenient, but it is not a deal breaker.

**Comment by nicm** [comment]
Or to put it this way: if I run `tmux -D` over ssh and then do `~.` or the connection drops, I expect tmux to die - and that means it needs to exit on `SIGHUP`.

**Comment by nicm** [comment]
Yeah, I don't think there is much in it. Setting `exit-empty` is probably easier for most uses of this, but it is also a little different to how tmux normally works. So it could be confusing that tmux exits, or confusing that it doesn't, depending what different people expect. I'll think about it.

**Comment by etosan** [comment]
Okay. SIGHUP issue is now understood too. I admit such use case never occurred to me.

Regarding that, I think this exact wording should probably be mentioned in manual to explain why SIGHUP is handled the way it is. That's all form my side.

I will be using this daily in following weeks, but I think it is pretty usable as it is already.

**Comment by nicm** [comment]
Hmm, actually maybe you are right - I just looked at sshd and it doesn't exit on `SIGHUP` even with `-D`. I don't much like the idea of `tmux -D` hanging around without a tty though, not sure.

**Comment by nicm** [comment]
I think I will make it ignore `SIGHUP` like sshd does, but if it becomes a problem I might change it later.

**Comment by etosan** [comment]
In actual (and properly configured(!)) supervision schema, either root of supervison tree or supervising parent process will **turn** `stdin` to `/dev/null`, `stdout` and `stderr` will be pointed toward "always-on" logging pipes (that go into logger subsystem whatever that is and supervisor will make sure as long as it runs that those pipes are open) and no terminal will be associated with the processes (tmux children will of course get what tmux prepares for them). 

If I understand unix properly there is no way to get SIGHUP (besides direct adminsitrative action), once there is no controlling tty, or am gravely I mistaken?

**Comment by nicm** [comment]
Right but there is no guarantee people are going to be using this with a supervising program, they might be running it inside another tmux, or for debugging or testing. But I think ignoring `SIGHUP` is probably OK.

I just remembered, the main reason I decided not to do `start-server -D` or to allow commands together with `-D`, is that the initial command is passed by the first client - so if you do `tmux new-session` the `new-session` is sent by the client (the parent process that forks, but it sends it after the fork). With `-D` there is no first client, so there is nothing to send the initial command. So it would have to be changed around so the initial command for the client that starts the server is special. It would be nice to be able to pass commands though...

**Comment by etosan** [comment]
I see, there are multiple use cases involved and neither one is more important than the other. Seems like `dnsmasq` even grew two foreground options for that reason. Thank you.

**Comment by nicm** [comment]
I think I will leave it as it is without allowing commands, it would be kind of complicated to make passing a command (like `tmux -D new`) work and although it might be handy I don't think it is required for the most common uses - one can always do `tmux -D &` and then send commands. Although that currently crashes, so I guess something there is at least one bug :-).

**Comment by etosan** [comment]
Just reporting that I am not using `tmux -D &`, naturally.

When using `${svcdir}/run`:`#!/bin/sh`\n`exec tmux -D` as is customary in supervision schemes, and sending client commands from their own terminals/ptys, I see no crashes there whatsoever. It seems rock solid.

Also tmux commands to self (from within tmux server spawned "service" way) seems to work flawlessly.

Adding `sleep 1` in `sh` script with `tmux -D &` makes me think it's a race:
```
#!/bin/sh
/home/eto/projects/tui/tmux/tmux -D &
sleep 1
/home/eto/projects/tui/tmux/tmux new-session -s x-session
```

**Comment by nicm** [comment]
Well, if you do them immediately in a script then you will need a sleep yes.

But if you do them outside a script, it doesn't work.

The problem seems to be that the client passes its tty fd up to the server, but that tty is still the controlling tty for the server, so when it tries to read or write to it it gets `SIGTTOU` or `SIGTTIN`.

If I make the server drop the controlling tty it works, but then ^C doesn't work if the server is in the foreground.

**Comment by etosan** [comment]
Because tmux (server) is in background after all. So it's tty handling, makes sense now. 

I can't even imagine how to make that work to have both ctty (for ^C) and allow commands.

**Comment by nicm** [comment]
Yes, I don't think it is possible to make it work, I think I'll just have to make it reject clients on the same tty.

**Comment by nicm** [comment]
I don't think I can even do that, because I don't think there is a way for the server to reliably find out its own controlling tty.

**Comment by nicm** [comment]
I have just done a best effort - if stdin/stdout/stderr are still open, do not allow clients to attach on the same tty. Also ignore SIGTTIN and SIGTTOU so if the worst happens, the client is just killed rather than the server hanging.

This is in GitHub now, please let me know if you see any problems.

Thanks!

**Comment by nicm** [comment]
Actually don't try it just yet, realised I broke the normal use case :-/

**Comment by nicm** [comment]
OK, just a typo, that's fixed now too.

**Comment by etosan** [comment]
Seems working fine here, thank you very much for the hard work!
