### ISSUE TITLE
True color (16 million colors) not working.

### ISSUE THREAD

**Issue by Noxillio** [tmux/tmux#2191]
**Output of `uname -sp && tmux -V && echo $TERM`:**
```
Linux x86_64
tmux 2.6
screen-256color
```
**Platform:** Ubuntu 18.04
**Problem:** True color does not work in tmux, but will work otherwise. In tmux, I just get 256 colors rather than 16 million.
**Reproduction steps:**
1. Install Ubuntu.
2. apt install byobu
3. Run byobu **or** tmux.
4. Test using:
```
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```
**$TERM inside tmux:** `screen-256color`
**$TERM outside tmux:** (It doesn't display anything, just a blank line)
**Screenshots:**
![image](https://user-images.githubusercontent.com/40806092/80845015-061c4680-8bd6-11ea-89b9-32e42f2223da.png)
![image](https://user-images.githubusercontent.com/40806092/80845053-23511500-8bd6-11ea-958f-e3682b37765f.png)

**Comment by nicm** [comment]
Did you do this? Use `Tc` not `RGB` for your tmux version:

https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour

**Comment by Noxillio** [comment]
> Did you do this? Use `Tc` not `RGB` for your tmux version:
> 
> https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour

Do I use `gnome` like it says, or replace that with screen, etc.?

**Comment by nicm** [comment]
See what `echo $TERM` says outside tmux, then put that in instead of `gnome`. It will probably be `xterm-256color`.

**Comment by Noxillio** [comment]
> See what `echo $TERM` says outside tmux, then put that in instead of `gnome`. It will probably be `xterm-256color`.

I already specified that here. Anyway, I tried `gnome`, `screen`, and `screen-256color` and none of them worked.

**Comment by Noxillio** [comment]
That worked! Thanks a ton :)
