### ISSUE TITLE
fatal: tty_clamp_area: y too big, 4294967295 > 0

### ISSUE THREAD

**Issue by nbari** [tmux/tmux#2192]
### Issue description

After upgrading via `brew`, randomly it crashes with:

    fatal: tty_clamp_area: y too big, 4294967295 > 0

[tmux-server-23835.log](https://github.com/tmux/tmux/files/4567692/tmux-server-23835.log)

* tmux version: `tmux 3.1a`
* Darwin i386
* $TERM outise `xterm-256color` inside tmux `screen-256color`

```
$ brew info tmux
tmux: stable 3.1a (bottled), HEAD
Terminal multiplexer
https://tmux.github.io/
/usr/local/Cellar/tmux/HEAD-e078f97 (9 files, 894KB) *
  Built from source on 2020-05-02 at 10:51:56
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tmux.rb
```

**Comment by nicm** [comment]
This is not 3.1a, it is a build from master which has a lot of changes. I'll take a look at what's going on when I get home later.

**Comment by nicm** [comment]
This log does not have the `fatal` message you mentioned, and I can't make tmux crash with `display-message -a`.

Can you show me a log from it crashing?

**Comment by nbari** [comment]
From the attached log:

```
$ tail -n3 tmux-server-23835.log
1588420672.619270 screen_write_collect_flush: flushed 0 items (0 bytes) (screen_write_clearendofscreen)
1588420672.619285 /dev/ttys000: \033[2;30r
1588420672.619323 fatal: tty_clamp_area: y too big, 4294967295 > 0

```

The last line I have in the log:

    1588420672.619323 fatal: tty_clamp_area: y too big, 4294967295 > 0

**Comment by nicm** [comment]
Er, yes, sorry, I have too many log files from different issues and I opened the wrong one. Looking now...

**Comment by nicm** [comment]
Can you reproduce this easily or does it just happen at random? If you can still reproduce it, can you do it without a `.tmux.conf` (try `tmux -Ltest -f/dev/null new`)?

**Comment by nbari** [comment]
I just did `brew reinstall reattach-to-user-namespace` and for the last minutes is not crashing, I will continue using it and if it crashes again I come back with the logs, thanks.

**Comment by nicm** [comment]
I don't know what is happening, it is something to do with you having `\033[J` (clear-end-of-screen) in your prompt, but I set a similar prompt and I can't make it crash no matter what I do.

**Comment by nbari** [comment]
probably I have a bug in https://crates.io/crates/slick, is what I am testing for the prompt

**Comment by nicm** [comment]
No, tmux should not crash whatever output you send or what you put in your prompt.

**Comment by nicm** [comment]
It may be worth upgrading to latest tmux master which is cb1131a29481246c9cb9b68cb8591cc747fcdd9a, I just fixed a bug that makes it crash, but I don't think it is related.

**Comment by nbari** [comment]
Today I did:

    brew upgrade && brew cask upgrade

I started to get crashes, I closed my terminal did what described here https://github.com/tmux/tmux/issues/2188#issuecomment-622943265 

     $ tmux kill-server && tmux -vv new
     $ tmux display-message -a 
      crash

But since I reinstalled  `reattach-to-user-namespace` is not crashing probably a coincidence.

**Comment by nicm** [comment]
OK thanks, let me know.

**Comment by nbari** [comment]
I just upgraded and it crashes, I did:

     $ brew remove tmux
     $ brew install tmux --HEAD

```
$ brew info tmux
tmux: stable 3.1a (bottled), HEAD
Terminal multiplexer
https://tmux.github.io/
/usr/local/Cellar/tmux/HEAD-cb1131a (9 files, 894KB) *
  Built from source on 2020-05-02 at 16:41:52
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tmux.rb
```

This is what I did:

    $ tmux kill-server
    $ cd /tmp
    $ tmux -vv new
    $ tmux display-message -a 
     crash

Attached the log:

[tmux-server-48853.log](https://github.com/tmux/tmux/files/4567937/tmux-server-48853.log)

**Comment by nicm** [comment]
Does it happen if you do `tmux -f/dev/null -vv new`?

Also if you make your terminal smaller like 80x24, does it still happen?

**Comment by nbari** [comment]
Not crashing so far with  `tmux -f/dev/null -vv new`

**Comment by nicm** [comment]
OK can you show me your .tmux.conf?

**Comment by nbari** [comment]
Here it is: https://github.com/nbari/dotfiles/blob/master/my-dotfiles/.tmux.conf (thanks for your time on this)

**Comment by nicm** [comment]
Ahah, I see it now, you have the status line at the top.

**Comment by nicm** [comment]
It is enough to do:
~~~~
tmux set -g status-position top
seq $LINES
printf '\033[J'
~~~~

**Comment by nbari** [comment]
Can you please elaborate more, I am not properly following you.

The first line I think is ok: https://github.com/nbari/dotfiles/blob/master/my-dotfiles/.tmux.conf#L19
    
    tmux set -g status-position top

But what about:

    seq $LINES
    printf '\033[J'

**Comment by nicm** [comment]
Never mind, it is just an example of how to make it crash.

Can you upgrade to af69289e0ea2b4af80206bcde0574358fa1b9169 and see if it still happens?

**Comment by nbari** [comment]
I upgraded and not crashing 👍 

```
$ brew info tmux
tmux: stable 3.1a (bottled), HEAD
Terminal multiplexer
https://tmux.github.io/
/usr/local/Cellar/tmux/HEAD-af69289 (9 files, 894KB) *
  Built from source on 2020-05-02 at 17:24:29
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tmux.rb
```

Many thanks

**Comment by nicm** [comment]
Great stuff, let me know if you see any further problems. Thanks!
