### ISSUE TITLE
Toggle between specific layouts

### ISSUE THREAD

**Issue by rightaway** [tmux/tmux#2194]
The toggle feature is great but can we have an option to configure which layouts are toggled between with `space`? Instead of the 5 preset layouts if I just want to have two of them to toggle back and forth between, like `even-vertical` and `even-horizontal`.

Would be helpful to be able to do that with `ctrl-B` plus `space` regardless of which layout you're in at the moment, rather than `ctrl-B` plus `alt` plus `1` if you're currently in vertical, and `ctrl-B` plus `alt` plus `2` if you're currently in horizontal.

Or instead of a configuration to set which layouts are toggled between, something like a "switch to last layout" to also benefit people who are using a variety of different layouts but want to regularly jump back and forth between the last one and the current one quickly.

**Comment by nicm** [comment]
You can do something like this:
~~~~
bind Space if -F '#{==:#{@lastlayout},eh}' 'selectl even-vertical; set -w @lastlayout ev' 'selectl even-horizontal; set -w @lastlayout eh'
~~~~

**Comment by rightaway** [comment]
Thank you. The first time I have to hit Space twice for it to do anything though. Could this command be changed to have an effect the first time too? I always start from one of the two layouts (even-vertical or even-horizontal before switching to the other one) if it matters.

**Comment by nicm** [comment]
How do you start from one of the layouts? If you do it from `M-1` or `M-2`, just change them as well:
~~~~
bind M-1 selectl even-horizontal \; set -w @lastlayout eh
bind M-2 selectl even-vertical \; set -w @lastlayout ev

**Comment by rightaway** [comment]
I use tmuxinator as a tmux helper. As an example config. Any way to get it to work this way?

```yml
windows:
  - editor:
      layout: even-vertical
      panes:
        - script1
        - script2
```

**Comment by nicm** [comment]
You could make one of the panes run `tmux set -w @lastlayout eh` or `ev` before running your command?

**Comment by rightaway** [comment]
Main problem with that is I have easily dozens of tmux windows defined throughout my main system and even several others, so it would be nice not to have to define it at the window creation level as that would clutter all the helper config files and if anything changes I'd need to update it in many places. Would be great to define it at the tmux configuration level (in the config file), if not a built in feature itself.

Just found https://github.com/tmux/tmux/issues/859#issuecomment-294252790. If I bind `select-layout -o` to a key it works exactly as expected, but only if the layout starts in `even-horizontal`. In this case it switches between horizontal and vertical right from the very first time running the shortcut.

But if the layout starts from `even-vertical`, then the shortcut does nothing. It's so close to working perfectly. Would you consider this for a feature request? For example being able to define an array of layouts as our preferred ones, so toggling between layouts would cycle through only those layouts by default. Or just letting `select-layout -o` work when layout starts in `even-vertical` same as it does when starts in `even-horizontal`.

**Comment by nicm** [comment]
I don't think enough people would use this, what you want is too specific, and it is possible to script this although you're right it is a bit fiddly to do it everywhere.

**Comment by nicm** [comment]
I'll take a look at `select-layout -o`, I can't remember how it works.

**Comment by nicm** [comment]
You can give a layout argument as well to `select-layout -o` which will be the layout used if there was no previous layout, so you could do for example `select-layout -o even-horizontal`.

**Comment by rightaway** [comment]
Whether I set it to horizontal or vertical that command shows error `can't set layout: even-horizontal`. I'm using tmux ver 3.1b.

**Comment by nicm** [comment]
Oh wait, yes I read it wrong, never mind.

**Comment by nicm** [comment]
If you build tmux from master, you can use a after hook to save the last layout, something like:
~~~~
set-hook -g after-select-layout "run 'tmux set -w @lastlayout #{hook_argument_0}'"
bind Space if -F '#{==:#{@lastlayout},even-horizontal}' 'selectl even-vertical' 'selectl even-horizontal'

**Comment by nicm** [comment]
You need at least 9991a14e8105b0b8e6f2baaec3ed50d1fb54f009.

**Comment by rightaway** [comment]
Thank you will try in upcoming release.

**Comment by nicm** [comment]
OK let me know.
