### ISSUE TITLE
Home and End keys don't work as expected

### ISSUE THREAD

**Issue by lifeBalance** [tmux/tmux#2199]
### Issue description
When I'm in a Tmux session these two keys don't take the cursor to the beginning/end of the line: **Home** does nothing, **End** prints a tilde.

(They work as expected outside a Tmux session)

### Required information
* tmux version (`tmux -V`): **tmux 3.1b**
* Platform (`uname -sp`): **Darwin i386**
* $TERM inside and outside of tmux (`echo $TERM`): 
* Inside: **tmux-256color**
* Outside: **xterm-256color**
* Using iterm2
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[logs](https://gist.github.com/lifeBalance/50141c2328deb4ca34a94ac484576098)

**Comment by nicm** [comment]
There is no evidence of you pressing `Home` and `End` in this log. Please do this:

- Run `cat` outside tmux then press `Home` and tell me what you see.

- Run `tmux -Ltest -f/dev/null -vv new` then do the same: run `cat` and press `Home`, then press `^D` to kill `cat` and `exit` to exit tmux. Then attach the tmux-server-*.log file to this issue.

**Comment by lifeBalance** [comment]
* Home: `^[[H` and End `^[[F`
* Home: `^[[1~` End: `^[[4~`
[new logs](https://gist.github.com/lifeBalance/a5e9ac27b6787b3df7d38a2394d03ce2)

**Comment by nicm** [comment]
These are correct - tmux sends `^[[1~` for `Home` and `^[[4~` for `End`, and these are listed in the `tmux-256color` terminfo entry. It sounds like your shell is not correctly picking them up, do you need to edit `.inputrc`?

**Comment by lifeBalance** [comment]
My shell is not picking them up inside tmux, outside everything's fine. I use Bash version 5.0.1.
I haven't touched anything in the Readline configuration, I haven't even got an `.inputrc`.

**Comment by nicm** [comment]
Right but that is a shell problem, not  tmux problem, I don't really know how to configure bash... maybe try adding this to `.inputrc`:
~~~~
"\e[1~": beginning-of-line
"\e[4~": end-of-line
~~~~

**Comment by nicm** [comment]
Are you sure your `tmux-256color` is right? OS X doesn't have it by default, did you add it yourself? What does `infocmp|grep khome` show inside tmux?

**Comment by lifeBalance** [comment]
That fixes the problem when I'm using **Bash**, but the problem persist in **Neovim**. By the way I can't see how that's a Bash problem. That type of thing is handled by Readline(or whatever its name is in macOS) no?

**Comment by lifeBalance** [comment]
I set `tmux-256color` in tmux.conf.
```
$ infocmp|grep khome                                                                                                                                            [0/0]
infocmp: couldn't open terminfo file (null).
```

**Comment by nicm** [comment]
But you have no `tmux-256color` entry on your system, so it won't work? Try `screen-256color` instead.

**Comment by lifeBalance** [comment]
That totally fixed it everywhere! Thanks.

**Comment by nicm** [comment]
You can build your own `tmux-256color` by saving this file: https://gist.githubusercontent.com/nicm/ea9cf3c93f22e0246ec858122d9abea1/raw/37ae29fc86e88b48dbc8a674478ad3e7a009f357/tmux-256color

Then installing it with `tic -x <tmux-256color`.

You will find some things like `C-Left` and `C-Right` may not work with `screen-256color`.

**Comment by lifeBalance** [comment]
Thank you, I've already started reading about terminfo and the tix compiler. (I didn't know they even existed)
