### ISSUE TITLE
No emacs cursor when ran under a nested tmux.

### ISSUE THREAD

**Issue by Nothus** [tmux/tmux#22]
My cursor disappears when in a nested tmux session.  It does work under a single session.

To reproduce:
`$ tmux`
`$ unset TMUX`
`$ tmux`
`$ emacs`
No cursor.

tmux 2.0
GNU Emacs 24.5.1
iTerm 2.1.1
Also tried it under Terminal.app (OSX 10.10.4 Public Beta)

**Comment by nicm** [comment]
This is a bug, fixed in Git. Or use:

set -ag terminal-overrides ',screen*:cvvis=\E[34l\E[?25h'

**Comment by Nothus** [comment]
I used the terminal overrides and they worked!  Much better now.  Thank you.

**Comment by elanelango** [comment]
The terminal-overrides setting fixed the issue for me. But when I'm inside emacs inside a nested tmux, the cursor seems to quickly jump to the end of line every time I type a character and then come back. It's usable but the cursor is constantly jittering and it's very distracting. Any idea why that might happen?
