### ISSUE TITLE
Should list-commands work even if the server is not running?

### ISSUE THREAD

**Issue by booooh** [tmux/tmux#220]
I'm wondering if perhaps the list-commands command should work even if there is no currently running server.
I don't know if that's possible or not, but it could help people starting out with tmux (like me) seeing what commands are available, even when the server is not currently running.

**Comment by btcrooks** [comment]
**man tmux** would be the closest you can get without starting a server.

**Comment by booooh** [comment]
Agreed. And that is what I did (also just running tmux, and then running 'tmux lscm' is another valid workaround) .
I would still think that there's no reason to expect the server to be running in order to show the commands, but I could be mistaken.

**Comment by nicm** [comment]
How would you know to use list-commands without looking at man tmux first?

**Comment by booooh** [comment]
I probably won't, but the reason for having the list-commands command is to have a concise description of the available commands (otherwise, you could just redirect this command to execute 'man tmux').
Again, I believe that this information is valuable, and usable even if the tmux server is not running.

**Comment by nicm** [comment]
Done.

**Comment by booooh** [comment]
Thanks. I love tmux, and I think you're doing an awesome job!

**Comment by jungle-boogie** [comment]
I agree with @booooh!

:+1: :100:
