### ISSUE TITLE
New sessions are pushed to the end of the list, not ordered alphabetically.

### ISSUE THREAD

**Issue by aetos-tradeline** [tmux/tmux#2200]
tmux version: `tmux 3.1b`
Platform: MacOS Catalina `10.15.4` `Darwin i386`
$TERM: `screen`
Terminal Emulator: `Alacritty`

When I create a new tmux session, it is added to the end of the sessions list, regardless of the session's name.
This means that the only way to order the sessions the way I want, is to create them in a specific order.

Example: 

* Create a new sessions called 'BBB'
`tmux new -s 'BBB'`
* Detach from this session
`Ctrl+B` `D`
* Create a new sessions called 'AAA'
`tmux new -s 'AAA'`
* View all sessions
`Ctrl+B` `S`

The desired result would be that the sessions are alphabetically ordered. So the 'AAA' session will be first, and the 'BBB' sessions will be second.
But the sessions are **not** alphabetically ordered. Any new sessions added is pushed to the end of the list. So the result of the example above is the following:
```
(0)   + BBB: 1 windows
(1)   + AAA: 1 windows (attached)
```

**Comment by nicm** [comment]
Tree mode shows index order by default, press `O` to change sort order.

TBH index (creation) order is a bit useless for sessions, maybe we should sort them by name even when windows are by index.

**Comment by nicm** [comment]
You can change the `s` binding to do `choose-tree -sOname` if you want it to always to be in name order.

**Comment by aetos-tradeline** [comment]
@nicm thanks for the answer!

I added this line to my **tmux.conf** and everything works as expected!
`bind-key -T prefix s choose-tree -sOname`

Is this a recent change??
I am pretty sure that until recently it worked the other way around. I think that the last update was the one that changed it for me, but I could not find anything in the `CHANGES` file.

**Comment by nicm** [comment]
It has always been this way I think, sorting was added in tmux 2.6.

**Comment by jonallured** [comment]
Thanks both - I upgraded with brew the other day and this started happening to me and it was driving me crazy, haha. I added that line to tmux.conf as mentioned and all is well with the world again!! ❤️
