### ISSUE TITLE
How can I modify the key binding in tree mode

### ISSUE THREAD

**Issue by yyy33** [tmux/tmux#2201]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).tmux 3.0a

* Platform (`uname -sp`).Linux x550vc-yyy 5.6.4-arch1-1 #1 SMP PREEMPT Mon, 13 Apr 2020 12:21:19 +0000 x86_64 GNU/Linux

* $TERM inside and outside of tmux (`echo $TERM`).xterm-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).sessions should be nested with care, unset $TMUX to force

# I haven't found this feature after a long search

**Comment by nicm** [comment]
You can do it by binding keys using `if-shell -F` and the `pane_mode` format.

**Comment by yyy33** [comment]
> You can do it by binding keys using `if-shell -F` and the `pane_mode` format.

In fact, I want to modify the default key binding in the `tree-mode`, for example, the `l` is used to extend the session and window list by default, but the cursor will move down when the session or window list cannot be extended anymore. I want to modify it to automatically select the `window` or `pane` when the session or window cannot be extended, just like I pressed the `enter` key

**Comment by yyy33** [comment]
> You can do it by binding keys using `if-shell -F` and the `pane_mode` format.

How should I judge whether the session or window under the cursor can be expanded

**Comment by nicm** [comment]
I don't know what you mean? What keys are you trying to add?

**Comment by yyy33** [comment]
> I don't know what you mean? What keys are you trying to add?

- Please see picture 1, at this time I have a session and two window

![1](https://user-images.githubusercontent.com/51548147/81382885-b0015300-9141-11ea-9e49-b0350463662b.png)

- I press `l`, at this time the window list will be expanded, please see picture 2

![2](https://user-images.githubusercontent.com/51548147/81383127-15554400-9142-11ea-8f0b-1bd6ba50758c.png)

- The current window contains 4 panes, at this time I press `l`, the pane list will be expanded

![3](https://user-images.githubusercontent.com/51548147/81383369-83017000-9142-11ea-9c38-2043e6d2638a.png)

- At this point I press `l` again, the cursor will move down. Can I make it not move down but select the current pane directly, because I can use j to move down

![4](https://user-images.githubusercontent.com/51548147/81383710-0a4ee380-9143-11ea-8fec-8dbcba3f4191.png)

**Comment by nicm** [comment]
No, it is not possible to do this.

**Comment by yyy33** [comment]
> No, it is not possible to do this.

Ok, thanks for your reply

**Comment by nomasprime** [comment]
> You can do it by binding keys using `if-shell -F` and the `pane_mode` format.

Hi @nicm, I couldn't find any info on `pane_mode`. Would you give an example remapping `Up` to `k'?

**Comment by nomasprime** [comment]
Never mind, looks like this is already mapped but missing from man page.
