### ISSUE TITLE
Linking error during compilation

### ISSUE THREAD

**Issue by moravveji** [tmux/tmux#2202]
Hey guys

I am trying to build tmux statically on our cluster (CentOS 7.6 with Intel Skylake nodes). However I get a compilation error with v.3.1b. Apparently, some linking fails to happen and I get a massive pile of errors like the following (see attached logs):

```bash
osdep-linux.o: In function `osdep_event_init':
osdep-linux.c:(.text+0x1a6): undefined reference to `event_init'
collect2: error: ld returned 1 exit status
make: *** [tmux] Error 1
```

Whether or not I try with static build, I get the same result. 
I have also included my build script and the compilation logs.
Would you please let me know how to fix this?

Regards
Ehsan

[tmux.logs.tar.gz](https://github.com/tmux/tmux/files/4599446/tmux.logs.tar.gz)

**Comment by nicm** [comment]
Where are the libs:
~~~~
+ export LIBEVENT_LIBS=-L/myApps/software/libevent/2.1.8/lib
+ export LIBNCURSES_LIBS=-L/myApps/software/ncurses/6.1/lib
~~~~
You need `-levent` and `-lncurses` as well...

**Comment by moravveji** [comment]
Added them, and problem was solved. Thanks for the tip.

**Comment by moravveji** [comment]
ls
