### ISSUE TITLE
incremental search with regexp?

### ISSUE THREAD

**Issue by damnskippy** [tmux/tmux#2205]
(Compiled from latest sources, on Ubuntu 16)

Just a quick question: do the `-incremental` search commands using with `command-prompt -i` support regexp?  It didn't work when I tried and just wanted to confirm if it's a user error on my part or if this is something not supported?  Regex search works perfectly fine with normal search commands (`search-forward `& `search-backward`).  Somehow assumed `incremental` would work since `command-prompt -i` executes the command as input changes per help doc.  Fwiw, this is what I have for mapping to do incremental search:
`bind-key -n C-s copy-mode -e \; send -X start-of-line \; command-prompt -i -p "search up:" "send -X search-backward-incremental \"%%%\"" 
`

Help text doesn't seem to explicitly call this out one way or the other:

> The search commands come in several varieties: ‘search-forward’ and ‘search-backward’ search for a regular expression; the ‘-text’ variants search for a plain text string rather than a regular expression; -incremental’ perform an incremental search and expect to be used with the -i flag to the command-prompt command

Thank you.

**Comment by nicm** [comment]
There is no incremental regex search, the reason is that we copy emacs and it doesn't do that by default. There is no reason it couldn't be added as a separate command.

**Comment by damnskippy** [comment]
Thank you - would be a useful addition, IMHO.  FWIW, incremental search is what I tend to use by default as it provides instant feedback about whether the search is matching anything in the visible part of the scrollback.

Thanks again.

**Comment by nicm** [comment]
I have put this on the todo list and hopefully will get to it at some point. Thanks!
