### ISSUE TITLE
Display a message with different colors than those set by the options

### ISSUE THREAD

**Issue by runar** [tmux/tmux#2206]
I am trying to display a message with different foreground and background colors than those set by the `message-style` option. Or, in other words, reset the colors after the message is displayed.

The `display-message` command supports formats, but apparently not styles:

```bash
$ tmux display-message -v "#[fg=red]#W"
# expanding format: #[fg=red]#W
# found #W: window_name
# format 'window_name' found: zsh
# replaced 'window_name' with 'zsh'
# result is: #[fg=red]zsh
```

I have also tried setting the `message-style` option to the desired colors before displaying the message, then resetting the colors, like this:

```bash
$ tmux set-option message-style bg=red; tmux display-message 'test'; tmux set-option -u message-style
```

This kind of works, but the colors are reset right before or while the message is being displayed.

As far as I can tell, there are no "callbacks" for when a message disappears, is cleared, or is otherwise no longer visible.

What would be the best way to do what I am trying to do? I am running tmux next-3.2.

**Comment by nicm** [comment]
It would be nice if it supported formats, I'll take a look.

In the meantime, you could maybe do this:
~~~~
tmux set message-style bg=red \; display 'test' \; run -b "sleep 0.5; tmux set-u message-style"
~~~~
Where the sleep is for some period the same or a little longer than your `display-time`.

**Comment by nicm** [comment]
This patch against master allows you to use formats in the message: [x.diff.txt](https://github.com/tmux/tmux/files/4605463/x.diff.txt)

For example:
~~~~
$ tmux display '#[fill=blue bg=red align=centre]hello'

**Comment by nicm** [comment]
I have applied this now.
