### ISSUE TITLE
Executing "clear" on the command line also deletes tmux history

### ISSUE THREAD

**Issue by hsundara** [tmux/tmux#2207]
### Issue description

I am not sure if this is intended behaviour or not. I mostly hit Ctrl+L to clear my screen , but sometimes, I have things showing in a loop (kinda like `watch`) when monitoring something and I tend to include a clean in there.

`while true; do <some monitoring>; sleep 2; clear; done`

After this, the tmux history is completely gone. I can't hit prefix-[ and go back at all.

Is this expected behaviour? Is there anything I can do to change it?

### Required information

* 3.1
* Cygwin and linux
* xterm-256color

**Comment by nicm** [comment]
Either use the right `TERM` inside tmux (`screen-256color` or `tmux-256color`), or use `clear -x`.

**Comment by hsundara** [comment]
clear -x works. Appreciate the super prompt response
