### ISSUE TITLE
Bindings like M-1 or M-2 are not working in some linux terminals

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#2208]
* tmux version (`tmux -V`).
tmux 3.1b
* Platform (`uname -sp`). 
5.6.11-1-MANJARO x86_64 GNU/Linux
* $TERM inside and outside of tmux (`echo $TERM`).
screen-256color(using fish+tmux.conf) or screen(no tmux.conf, using bash)
* Logs from tmux (`tmux kill-server; tmux -vv new`).

I think this problem happens since v3.1a , but I'm not sure.

Yakuake(based on Konsole) is the terminal I use. I have my own "~/.tmux.conf" which contains a lot of configs, there are the following lines in the file:
~~~
bind M-1 select-window -t :=1
bind M-2 select-window -t :=2
bind M-3 select-window -t :=3
bind M-4 select-window -t :=4
bind M-5 select-window -t :=5
bind M-6 select-window -t :=6
bind M-7 select-window -t :=7
bind M-8 select-window -t :=8
bind M-9 select-window -t :=9
~~~
so I can use Prefix+M-1/2/3... to switch to the specific window.

But recently I found M-1/2/3... don't work anymore, it doesn't work when I hit Prefix-M-1 to switch to 1-window.

- I'm using fish+tmux+yakuake, and when I use bash instead of fish in yakuake, it is the same result
- when I remove my tmux.conf completely and use bash or fish, it is the same result.(there are M-1/2/3 bindings in builtin configuration)
- I tried Ctrl-Alt-F2, using fish+tmux, or bash+tmux, with ~/.tmux.conf  or without it, the M-1/2/3 works fine.
- I tried several other terminals, like Konsole, tilda, alacritty, st, and I found that M-1/2/3 is working fine in alacritty and st, but not working in Konsole, Yakuake and Tilda.

So does any one know anything about it?

The following logs are result of `tmux kill-server; tmux -vv new`, not using my .tmux.conf, in bash, just create pane and switch layout using builtin Prefix+M-1, inside Konsole, binding is not working.
[tmux-client-1293350.log](https://github.com/tmux/tmux/files/4605884/tmux-client-1293350.log)
[tmux-out-1293352.log](https://github.com/tmux/tmux/files/4605886/tmux-out-1293352.log)
[tmux-server-1293352.log](https://github.com/tmux/tmux/files/4605887/tmux-server-1293352.log)

**Comment by nicm** [comment]
There are no `M-` key presses in this log. This is what tmux received:
~~~~
1589123171.917062 /dev/pts/1: keys are 1 (\002)
1589123172.670621 /dev/pts/1: keys are 1 (")
1589123180.981231 /dev/pts/1: keys are 1 (\002)
1589123182.749572 /dev/pts/1: keys are 1 (\002)
1589123184.518282 /dev/pts/1: keys are 1 (\002)
1589123188.077790 /dev/pts/1: keys are 1 (x)
1589123189.813898 /dev/pts/1: keys are 1 (y)
1589123190.485344 /dev/pts/1: keys are 1 (x)
1589123190.749301 /dev/pts/1: keys are 1 (\r)
~~~~
Are you sure your terminal or window manager is not eating them now?

**Comment by nicm** [comment]
If you run `cat` outside tmux, and press `M-1`, what do you see? I see:
~~~~
$ cat
^[1

**Comment by c02y** [comment]
The following logs are result of alacritty terminal+bash+no-tmux.conf file, which M-1/2/3... are working fine:
[tmux-out-1354563.log](https://github.com/tmux/tmux/files/4606023/tmux-out-1354563.log)
[tmux-server-1354563.log](https://github.com/tmux/tmux/files/4606024/tmux-server-1354563.log)
[tmux-client-1354561.log](https://github.com/tmux/tmux/files/4606025/tmux-client-1354561.log)


`cat` +`M-1` in Yakuake which M-1/2/3 bindings are not working in tmux
~~~
# outside tmux
$ cat
~~~
nothing after `cat`

in alacritty terminal which M-1/2/3 bindings are working fine in tmux:
~~~
# outside tmux
$ cat
^[1
~~~

**Comment by c02y** [comment]
**UPDATE**:

Sorry about this, M-1/2/3 are bound to switch tabs for the Konsole/Yakuake/tilda terminal itself which are ignore since there is only one terminal tab.

I used to disable this setting in terminal Preference. I just forgot this process.

**Comment by c02y** [comment]
But don't why, they are still not working in Yakuake 

# outside tmux
$ cat

nothing after cat in yakuake
