### ISSUE TITLE
new-session -A and -d don't work together

### ISSUE THREAD

**Issue by rmeritz** [tmux/tmux#2211]
### Issue description

If you use `new-session -Ad` from within a running `tmux` session, then it exits with ` sessions should be nested with care, unset $TMUX to force` instead of attaching to the session in demonized mode if the session already exists.

Steps to reproduce:

```sh
tmux new-session -s foo 
tmux new-session -Ads foo  # From within the new foo session
```
Expected behavior: combining `-Ad` for an existing session should behave like doing nothing.

Actual behavior: prints the "nested with care" error message and exits.

### Required information

* tmux version (`tmux -V`): 2.8
* Platform (`uname -sp`): Linux unknown (Debian)
* $TERM inside and outside of tmux (`echo $TERM`): screen-256color

**Comment by nicm** [comment]
Why is your expected behaviour any more expected than what it does? Why should anyone think -d will take precedence over -A?
