### ISSUE TITLE
server version is too old for client

### ISSUE THREAD

**Issue by hktalent** [tmux/tmux#2212]
```
$ tmux -V
tmux 3.1b

$ tmux ls
server version is too old for client
server version is too old for client
server version is too old for client
```
https://github.com/tmux/tmux/blob/9d44df9da95452d985f6e5937dd3c4311bf33548/client.c#L869

**Comment by krader1961** [comment]
See https://github.com/tmux/tmux/issues/2189

You probably updated your installed tmux version in the past week or thereabouts and have a running tmux server from the prior version.

**Comment by hktalent** [comment]
I got it!
Because TMUX is updated after the server is started

**Comment by drevicko** [comment]
I don't suppose there's a way to temporarily run an older client so as to re-activate the old session?

**Comment by nicm** [comment]
When you upgrade you need to kill tmux entirely and then run the new version only from then on.

**Comment by rajeshisnepali** [comment]
`tmux kill-server` didn't work for me. 

I had to force kill `sudo kill -9 $(pgrep -f tmux)`

**Comment by drevicko** [comment]
I found that running `tmux attach` loaded the existing session without problems, allowing me to keep the session a while longer before restarting the tmux server. (I actually run it via byobu, so `byobu attach`, but I believe it's just passed through to tmux).

**Comment by staycreativedesign** [comment]
ok Im using TMATE 2.4.0 and then
tmux 3.1b

when I enter tmate and then tmux 3.1b I get server version is too old for client
