### ISSUE TITLE
Switching To Terminal.app Window that Owns a Tmux Session

### ISSUE THREAD

**Issue by boulderob** [tmux/tmux#2213]
This isn't a bug or feature request.  I'm looking for possible suggestions to solve a problem that i'm not having much luck with having searched the web extensively and read through all the tmux documentation.

Let's say i have 10 *different* tmux sessions attached to 10 *different* mac terminals (ie 10 separate terminal.app windows running under the macos vanilla terminal.app).  Put another way, each tmux session is attached to it's own tmux terminal client and all running under 1 instance of tmux.

I know i can use `switch-client -t S:W.P` to **swap in** a different session, window, pane into the current physical terminal which would mean that same session is now currently attached to and being displayed in two different terminal windows. It works fine and I can switch back to my Last session fairly easily.

But if instead i wanted to use the -t S:W.P target to **go to** the other physical terminal.app window (client) that the owns that session target  (ie basically switching the terminal.app window) vs swapping the client in my current terminal, how would i do this?  i basically like the fact that each session is tied to a given window in the terminal app and would prefer to switch at the macos terminal level when switching to other targeted sessions vs always switching it into (attching it to) the current terminal window.  I hope that makes sense.   It's clear to me. 

Part of this is happening inside tmux and the other part is outside at the macos / terminal.app  window level so it's not the concern of the tmux project.   I just thought i'd see if anybody here had any thoughts.

If i can find the terminal app window (process?) that "owns" the tmux session i'm targeting, i *might* be able to script (oa script???) a way to then target and switch to that terminal app window instead.  But that's the mysterious part.

Any thoughts greatly appreciated.  Thanks

Current config:

tmux 3.0a
macos:Darwin i386
screen-256color

**Comment by nicm** [comment]
You can probably get the terminal by getting the pty from `client_tty` for the client you want and then looking for the process that owns the other end of the pty. But you will need to figure out how to make that terminal window available yourself.

**Comment by nicm** [comment]
The other thing you could probably do that would give the same effect is just use `detach -P` to kill the terminal window containing the session you want then create a new one with that session attached.

**Comment by boulderob** [comment]
hey thanks for the rapid reply @nicm.  i didn't know about client_tty and i just used it to successfully reach back to the pid of the terminal.app window of the session.  but as you say, mapping that to "some code" that switches to that app window is nebulous at best.

your second suggestion seems like a decent workaround which is why i asked the question. 

quick followup related to processes and tmux.  i usually kill my tmux panes by manually typing `exit` in the shell.  this seems like a "clean" way to exit the panes and or kill the window if the pane is the only one in a window.  but is there any reason to use a tmux kill related command over 'exit'?  i wouldn't think so but i've been working a lot lately with tmux and the underlying processes / ttys and for whatever reason one of my panes / ttys has like 20 listings in ps even though it's only got one fg process like vim running in it currently.  if i quit the fg process i still have the same 20 processes tied to that tty.  if start the fg process i get 20 plus the fg process. all my other panes / tty / ps combos look normal with either a bash shell or a single fg process.  i just thought i might be abandoning processes or stg using exit

Thanks

**Comment by nicm** [comment]
Either is fine, if you type `exit` the shell will kill all its child processes, if you kill the tmux pane or window or session or server the kernel will send them all `SIGHUP` after tmux closes the pty.

**Comment by boulderob** [comment]
Thanks!
