### ISSUE TITLE
what does this error mean: server version is too old for client

### ISSUE THREAD

**Issue by thomasd3** [tmux/tmux#2214]
I'm on MacOS and just did an update (through brew).

I get this now:

```
~ ᐅ tmux -v
server version is too old for client

```

and I get the same error when running xpanes.

here's more info:

```
~ ᐅ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 3.1b
screen-256color
```

**Comment by nicm** [comment]
If you upgrade tmux, you need to restart it.

**Comment by thomasd3** [comment]
that was the issue; thanks.
