### ISSUE TITLE
Can't use ":h modifyOtherKeys" in Vim inside Tmux

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2216]
### Issue description

On a recent enough Vim, one can make Vim distinguish between keys which are usually conflated; e.g. `C-i` and `Tab`.  This is documented at `:h modifyOtherKeys`.  It works in xterm, and can be tested with this shell command:

    vim -Nu NONE +'nno <C-i> :echom "C-i was pressed"<cr>' +'nno <tab> :echom "Tab was pressed"<cr>'
    " press C-i:  "C-i was pressed" is displayed
    " press Tab:  "Tab was pressed" is displayed

But it doesn't work inside Tmux:

    tmux -Lx -f/dev/null
    vim -Nu NONE +'nno <C-i> :echom "C-i was pressed"<cr>' +'nno <tab> :echom "Tab was pressed"<cr>'
    " press C-i:  "Tab was pressed" is displayed
    " press Tab:  "Tab was pressed" is displayed

I thought the issue was because Vim didn't set some terminal options, because `TERM` is not `xterm` inside Tmux.  So, I tried to set them correctly, but Vim still conflates `C-i` with `Tab`:

    tmux -Lx -f/dev/null
    vim -Nu NONE --cmd 'let [&t_TI, &t_TE] = ["\<Esc>[>4;2m", "\<Esc>[>4;m"]' +'nno <C-i> :echom "C-i was pressed"<cr>' +'nno <tab> :echom "Tab was pressed"<cr>'
    " press C-i:  "Tab was pressed" is displayed
    " press Tab:  "Tab was pressed" is displayed

Not sure whether they're relevant but I've also tried to set the recent `extended-keys` option, as well as the `Eneks` terminal capability.

    tmux -Lx -f <(cat <<'EOF'
        set -s extended-keys on
        set -as terminal-overrides '*:Eneks'
    EOF
    )
    vim -Nu NONE --cmd 'let [&t_TI, &t_TE] = ["\<Esc>[>4;2m", "\<Esc>[>4;m"]' +'nno <C-i> :echom "C-i was pressed"<cr>' +'nno <tab> :echom "Tab was pressed"<cr>'
    " press C-i:  "Tab was pressed" is displayed
    " press Tab:  "Tab was pressed" is displayed

Same result.

As a last resort, I've tried to start Vim with `TERM` set to `xterm` so that Vim thinks it's running inside xterm and sets all the terminal options like it would if it was not running inside Tmux.  Again, same result.

Is it a bug, or am I missing some Tmux configuration?

### Required information

 - `$ tmux -V`: tmux next-3.2, commit c2167c5ee81022ddf9f02cfe189fcea736026ced
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:

[tmux-client-5143.log](https://github.com/tmux/tmux/files/4637850/tmux-client-5143.log)
[tmux-out-5145.log](https://github.com/tmux/tmux/files/4637851/tmux-out-5145.log)
[tmux-server-5145.log](https://github.com/tmux/tmux/files/4637852/tmux-server-5145.log)

 - `$ tmux info`: [tmux.info.txt](https://github.com/tmux/tmux/files/4637854/tmux.info.txt)

**Comment by lacygoill** [comment]
I've just tried to wrap the sequences `\033[>4;2m` and `\033[>4;m` inside the DCS sequence `\033Ptmux;seq\033\\` (where all the escapes are doubled in `seq`), with the idea that maybe Tmux was wrongly consuming the sequences sent by Vim to xterm:

    vim -Nu NONE --cmd 'let [&t_TI, &t_TE] = ["\ePtmux;\e\e[>4;2m\e\\", "\ePtmux;\e\e[>4;m\e\\"]' +'nno <C-i> :echom "C-i was pressed"<cr>' +'nno <tab> :echom "Tab was pressed"<cr>'

But Vim still conflates `C-i` and `Tab`.

**Comment by nicm** [comment]
This is not a regression though right? tmux would have ignored these sequences before.

tmux only supports `modifyOtherKeys` = 1 which does not distinguish `C-i` and `Tab`.

Try a key like `C-1` instead.

**Comment by lacygoill** [comment]
Oh, I didn't know that Tmux only supported `modifyOtherKeys = 1` and not `modifyOtherKeys = 2`.  That's probably the explanation for the issue.  No, I don't think it's a regression; at least, it's not a recent one, because I can reproduce on Tmux 3.0.

Thank you for the explanation.  I don't really mind that Tmux does not support `modifyOtherKeys = 2`, because the feature is buggy in Vim anyway, so I don't use it.  I was just curious as to why it didn't work in a simple test.

**Comment by nicm** [comment]
Well, I just found a bug in tmux's implementation so it doesn't actually work properly now, but it should work... posssibly even if you force it to 2 by changing `Eneks`.

**Comment by lacygoill** [comment]
Interesting, I'll keep an eye on the next commits and make some quick tests to try and make it work.

**Comment by nicm** [comment]
It should work now, however there is one other change I want to make.

**Comment by nicm** [comment]
OK it is changed now.

You can't use `modifyOtherKeys` = 2 - tmux would need explicit support because that option translates all keys including stuff like `C-c` and tmux would need to translate them back for programs that don't support it which would be tricky.

`modifyOtherKeys` = 1 should work, but you only get keys like `C-1` and `C-Enter`, not `C-i`.

**Comment by lacygoill** [comment]
I've just tried https://github.com/tmux/tmux/commit/53c84fd4aa87b4ff80e79ef79155f13c69f1aebc, but I can't make it work.  Part of the issue is that I don't know what is needed:

   - do I need to set `Eneks`?
   - do I need to set `extended-keys`?
   - do I need to wrap the sequences inside a DCS sequence?

This is what I've tried:

    tmux -Lx -f <(cat <<'EOF'
        set -s extended-keys on
        set -as terminal-overrides '*:Eneks'
    EOF
    )

    vim -Nu NONE --cmd 'let [&t_TI, &t_TE] = ["\e[>4;2m", "\e[>4;m"]' +'nno <C-Enter> :echom "C-Enter was pressed"<cr>'

    vim -Nu NONE --cmd 'let [&t_TI, &t_TE] = ["\ePtmux;\e[>4;2m\e\\", "\ePtmux;\e\e[>4;m\e\\"]' +'nno <C-Enter> :echom "C-Enter was pressed"<cr>'

Both Vim commands fail to recognize `C-Enter`.  Logs:

[tmux-client-10856.log](https://github.com/tmux/tmux/files/4637949/tmux-client-10856.log)
[tmux-out-10858.log](https://github.com/tmux/tmux/files/4637950/tmux-out-10858.log)
[tmux-server-10858.log](https://github.com/tmux/tmux/files/4637951/tmux-server-10858.log)

**Comment by nicm** [comment]
Look here for instructions: https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys

- No DCS.
- No `modifyOtherKeys` in `.Xresources` or `.Xdefaults`.
- `set -g extended-keys on`
- If xterm --version < 354, then `set -as terminal-features 'xterm*:extkeys'`.

Then try this (for `C-1`):
~~~~
$ printf '\033[>4;1m'
$ cat
^[[49;5u
~~~~
If that works but not vim, then you need to configure vim.

**Comment by lacygoill** [comment]
Can confirm.  This makes it possible to make Vim recognize `C-Enter`:

    tmux -Lx -f <(cat <<'EOF'
        set -s extended-keys on
        set -as terminal-features 'xterm*:extkeys'
    EOF
    )

    vim -Nu NONE --cmd 'let [&t_TI, &t_TE] = ["\e[>4;2m", "\e[>4;m"]' +'nno <C-Enter> :echom "C-Enter was pressed"<cr>'

I think the issue was with this line:

    set -as terminal-overrides '*:Eneks'

Not sure why `Eneks` didn't work, but I should have used this instead:

    set -as terminal-features 'xterm*:extkeys'

---

I've quickly read the wiki, and there seems to be a small typo:

    $ cat
    ^[[49;5u
          ^

On my machine, the sequence which is printed is identical except for the 5 which is a 6:

    $ cat
    ^[[49;6u
          ^

Although, maybe the actual sequence depends on the xterm version and/or its terminfo description, so it may not be a typo after all.

**Comment by nicm** [comment]
No, `C-1` is definitely `5`. `6` is `S-C-1`, does your keyboard have 1 as a shifted key?

**Comment by nicm** [comment]
`Eneks` is not a flag, it is a string capability that you need to set to `\E[>4;1m`. But since your tmux is new enough to have it, you should use `terminal-features` instead.

**Comment by lacygoill** [comment]
> No, C-1 is definitely 5. 6 is S-C-1, does your keyboard have 1 as a shifted key?

Ah yes.  I can only press `1` with the shift modifier (well, I could also use the keypad but it's too far from the home row).  It's on the same key as `&`; so to generate `1`, I always press `S-&`.

> Eneks is not a flag, it is a string capability that you need to set to \E[>4;1m. But since your tmux is new enough to have it, you should use terminal-features instead.

Oh, I thought it was a boolean option, while it's a string one.  Yes, you're right, this works:

    tmux -Lx -f <(cat <<'EOF'
        set -s extended-keys on
        set -as terminal-overrides '*:Eneks=\E[>4;1m'
        set -as terminal-overrides '*:Dseks=\E[>4;m'
    EOF
    )

    vim -Nu NONE --cmd 'let [&t_TI, &t_TE] = ["\e[>4;1m", "\e[>4;m"]' +'nno <C-Enter> :echom "C-Enter was pressed"<cr>'

Thank you for all the explanations.

**Comment by nicm** [comment]
Yes, a weakness of this scheme is that it is dependent on keyboard layout, so one person's `C-1` is anothers `C-S-1`.
