### ISSUE TITLE
tmux-3.1: error message when ~/.config is a file

### ISSUE THREAD

**Issue by Polynomial-C** [tmux/tmux#2218]
* tmux version (`tmux -V`).

`tmux 3.1b`

* Platform (`uname -sp`).

`Linux Quad-Core AMD Opteron(tm) Processor 2389`

* $TERM inside and outside of tmux (`echo $TERM`).

inside: `screen-256color`
outside: `xterm-256color`

I had accidentally copied an old `.config` kernel configuration file into my root user's home directory. After upgrade to tmux-3.1{,a,b} when starting a tmux session as root, I get the following error message:
```
/root/.config/tmux/tmux.conf: Not a directory
```
and I cannot use tmux until I have pressed `CTRL + C` or `q` once.

**Comment by nicm** [comment]
I think it is better to give a warning for people who want a config in .config to be found than ignore it for people who have accidentally created .config as a file...
