### ISSUE TITLE
file descriptors not cleaned when pane closed (but when window)

### ISSUE THREAD

**Issue by unhammer** [tmux/tmux#222]
To reproduce, do

     tmux
     mkdir /tmp/needle
     cd /tmp/needle
     tmux split-window
     cd $HOME
     tmux kill-pane -t 0

Actual result:

     $ lsof |grep needle
tmux      29457       user   11r      DIR               0,32       40   12583314 /tmp/needle

Expected result: fd closed after kill-pane. 

The fd does get closed after killing the window though.

(This is an annoyance when trying to unmount a volume and having to remember which window at some point had a pane that was in that volume.)

**Comment by nicm** [comment]
Try tmux from git master please.

**Comment by unhammer** [comment]
That seems to solve it, thanks nicm :-)
