### ISSUE TITLE
[ Question ] is there any way to hide the square bar at the splits ?

### ISSUE THREAD

**Issue by rjshrjndrn** [tmux/tmux#2221]
![image](https://user-images.githubusercontent.com/2563385/82409366-30ea1400-9a8b-11ea-99a8-1940305480fc.png)

Is there any way to hide the square black bar at the split line ?

* tmux version (`tmux -V`).
```
❮ tmux -V
tmux 3.1b
```
* Platform (`uname -sp`).
arch linux
* $TERM inside and outside of tmux (`echo $TERM`).
```
❯ echo $TERM
screen-256color
```

Note: I'm using below settings to higlight active windows
```
set-window-option -g window-active-style bg=terminal,fg=terminal
set -g pane-border-bg colour235
set -g pane-border-fg colour238
set -g pane-active-border-bg colour236
set -g pane-active-border-fg colour51
set-window-option -g window-style        fg=colour247,bg=colour236
```

**Comment by nicm** [comment]
You can change the border colour but not remove it.

**Comment by nicm** [comment]
Are you sure you didn't mark the pane? Try pressing `C-b M`.

**Comment by rjshrjndrn** [comment]
@nicm You're the man.. that was the issue. thank you very much
