### ISSUE TITLE
Session no longer available after being detached ("no server running on...")

### ISSUE THREAD

**Issue by netw0rkf10w** [tmux/tmux#2222]
### Issue description

I have recently experienced some strange tmux's behavior on a server. When I detach a session, and come back a few minutes later, it's gone: 

`no server running on /home/user/tmp/tmux-300840/default`

I check `/home/user/tmp/tmux-300840/default` and the file is there.
 
I found a solution to retrieve the sessions that I started:

```
ps -aef | fgrep -i tmux
kill -s USR1 <process_id>
```

But doing this every few minutes is very frustrating. I already tried to install the latest version (3.1b) but the same issue happens. I would like to know if somebody could help me to completely get rid of this issue. 

Thank you very much in advance for your help!

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.1b`
* Platform (`uname -sp`): `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`): inside: `screen`, outside: `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`):

`tmux kill-server` gives `no server running on /home/user/tmp/tmux-300840/default`  while `tmux -vv new` shows nothing.

**Comment by nicm** [comment]
Something is deleting the tmux socket, you need to figure out what is doing that and stop it.

**Comment by netw0rkf10w** [comment]
@nicm Thank you very much for your prompt reply! I have checked with our sys admin but we haven't found anything yet.

In the above I said "`tmux -vv new` shows nothing", but now I have just realized that I have logs in my home directory. The most recent log file is attached here: [tmux-server-79400.log](https://github.com/tmux/tmux/files/4657844/tmux-server-79400.log) whose last lines are appended below. I hope it gives more information about the issue.
```
1589983284.909042 @0 alerts timer reset 0
1589983284.909071 screen_write_start: size 195x52, pane %0 (at 0,0)
1589983284.909090 input_parse_buffer: %0 ground, 10 bytes: \r\nlogout\r\n
1589983284.909103 input_c0_dispatch: '\r'
1589983284.909113 input_c0_dispatch: '\n'
1589983284.909125 screen_write_linefeed: at 0,0 (region 0-51)
1589983284.909141 screen_write_collect_end: 6 logout (at 0,1)
1589983284.909159 input_c0_dispatch: '\r'
1589983284.909168 input_c0_dispatch: '\n'
1589983284.909181 screen_write_linefeed: at 0,1 (region 0-51)
1589983284.909200 /dev/pts/4: \r
1589983284.909256 /dev/pts/4: \n
1589983284.909273 /dev/pts/4: logout
1589983284.909291 screen_write_collect_flush: flushed 1 items (6 bytes)
1589983284.909304 screen_write_stop: 6 cells (6 written, 0 skipped)
1589983284.909321 cmdq_next <global>: empty
1589983284.909333 cmdq_next </dev/pts/4>: empty
1589983284.909343 /dev/pts/4: \r
1589983284.909359 /dev/pts/4: \n
1589983284.909377 @0 active pane changed
1589983284.909388 @0 name timer queued (440708 left)
1589983284.909451 %0 error
1589983284.909607 cmd_find_best_session_with_window: window is @0
1589983284.909646 cmd_find_best_session: 1 sessions to try
1589983284.909660 cmd_find_best_winlink_with_window: window is @0
1589983284.909671 cmd_find_best_winlink_with_window: window is @0
1589983284.909684 cmd_find_from_window: s=$0 0
1589983284.909696 cmd_find_from_window: wl=0 1 w=@0 bash
1589983284.909706 cmd_find_from_window: wp=%0
1589983284.909718 cmd_find_from_window: idx=0
1589983284.909728 cmd_find_from_pane: s=$0 0
1589983284.909738 cmd_find_from_pane: wl=0 1 w=@0 bash
1589983284.909748 cmd_find_from_pane: wp=%0
1589983284.909757 cmd_find_from_pane: idx=0
1589983284.909770 session_add_ref: 0 notify_add, now 2
1589983284.909786 cmdq_append <global>: [notify_callback/0xd4fd90]
1589983284.909804 cmd_find_best_session_with_window: window is @0
1589983284.909818 cmd_find_best_session: 1 sessions to try
1589983284.909830 cmd_find_best_winlink_with_window: window is @0
1589983284.909841 cmd_find_best_winlink_with_window: window is @0
1589983284.909852 cmd_find_from_window: s=$0 0
1589983284.909862 cmd_find_from_window: wl=0 1 w=@0 bash
1589983284.909876 cmd_find_from_window: wp=%0
1589983284.909887 cmd_find_from_window: idx=0
1589983284.909899 window_add_ref: @0 notify_add, now 2
1589983284.909910 session_add_ref: 0 notify_add, now 3
1589983284.909923 cmdq_append <global>: [notify_callback/0xd51af0]
1589983284.909935 window_lost_pane: @0 pane %0
1589983284.910020 cmd_find_best_winlink_with_window: window is @0
1589983284.910030 cmd_find_from_session_window: s=$0 0
1589983284.910040 cmd_find_from_session_window: wl=0 1 w=@0 bash
1589983284.910050 cmd_find_from_session_window: wp=none
1589983284.910059 cmd_find_from_session_window: idx=0
1589983284.910068 session_add_ref: 0 notify_add, now 4
1589983284.910078 window_add_ref: @0 notify_add, now 3
1589983284.910087 session_add_ref: 0 notify_add, now 5
1589983284.910098 cmdq_append <global>: [notify_callback/0xd47650]
1589983284.910110 window_remove_ref: @0 winlink_remove, now 2
1589983284.910121 session 0 destroyed (session_detach)
1589983284.910133 cmd_find_best_session: 0 sessions to try
1589983284.910147 session_add_ref: 0 notify_add, now 6
1589983284.910158 cmdq_append <global>: [notify_callback/0xd492c0]
1589983284.910169 session_remove_ref: 0 session_destroy, now 5
1589983284.910232 /dev/pts/4: wrote 10 bytes (of 10)
1589983284.910395 server_signal: Child exited
1589983284.910620 cmdq_next <global>: enter
1589983284.910653 cmdq_next <global>: [notify_callback/0xd4fd90] (1), flags 0
1589983284.910665 notify_callback: pane-exited
1589983284.910675 notify_insert_hook: pane-exited
1589983284.910687 cmd_find_best_session: 0 sessions to try
1589983284.910702 session_remove_ref: 0 notify_callback, now 4
1589983284.910713 cmdq_next <global>: [notify_callback/0xd51af0] (1), flags 0
1589983284.910724 notify_callback: window-layout-changed
1589983284.910735 notify_insert_hook: window-layout-changed
1589983284.910748 cmd_find_best_session: 0 sessions to try
1589983284.910762 window_remove_ref: @0 notify_callback, now 1
1589983284.910772 session_remove_ref: 0 notify_callback, now 3
1589983284.910783 cmdq_next <global>: [notify_callback/0xd47650] (1), flags 0
1589983284.910793 notify_callback: window-unlinked
1589983284.910802 notify_insert_hook: window-unlinked
1589983284.910811 cmd_find_best_session: 0 sessions to try
1589983284.910822 session_remove_ref: 0 notify_callback, now 2
1589983284.910832 window_remove_ref: @0 notify_callback, now 0
1589983284.910844 window @0 destroyed (0 references)
1589983284.910862 session_remove_ref: 0 notify_callback, now 1
1589983284.910878 cmdq_next <global>: [notify_callback/0xd492c0] (1), flags 0
1589983284.910891 notify_callback: session-closed
1589983284.910901 notify_insert_hook: session-closed
1589983284.910912 cmd_find_best_session: 0 sessions to try
1589983284.910924 session_remove_ref: 0 notify_callback, now 0
1589983284.910941 cmdq_next <global>: exit (empty)
1589983284.910954 cmdq_next </dev/pts/4>: empty
1589983284.910966 cmdq_next <global>: empty
1589983284.910978 cmdq_next </dev/pts/4>: empty
1589983284.910990 cmd_find_best_session: 0 sessions to try
1589983284.911002 cmdq_append <global>: [notify_callback/0xd25390]
1589983284.911016 sending message 203 to peer 0xd563f0 (4 bytes)
1589983284.911048 session 0 freed (0 references)
1589983284.911166 cmdq_next <global>: enter
1589983284.911198 cmdq_next <global>: [notify_callback/0xd25390] (1), flags 0
1589983284.911208 notify_callback: client-detached
1589983284.911221 notify_insert_hook: client-detached
1589983284.911238 cmd_find_best_session: 0 sessions to try
1589983284.911253 unref client 0xd55aa0 (2 references)
1589983284.911265 cmdq_next <global>: exit (empty)
1589983284.911280 cmdq_next </dev/pts/4>: empty
1589983284.911295 cmdq_next <global>: empty
1589983284.911306 cmdq_next </dev/pts/4>: empty
1589983284.912437 peer 0xd563f0 message 205
1589983284.912704 sending message 204 to peer 0xd563f0 (0 bytes)
1589983284.912748 cmdq_next <global>: empty
1589983284.912759 cmdq_next </dev/pts/4>: empty
1589983284.912807 cmdq_next <global>: empty
1589983284.912818 cmdq_next </dev/pts/4>: empty
1589983284.924396 lost client 0xd55aa0
1589983284.924646 remove peer 0xd563f0
1589983284.924749 unref client 0xd55aa0 (1 references)
1589983284.925020 free client 0xd55aa0 (0 references)
1589983284.925042 cmdq_next <global>: empty
1589983284.925058 server loop exit
```

**Comment by netw0rkf10w** [comment]
There's another file which I don't understand what it's for: 
[tmux-out-79400.log](https://github.com/tmux/tmux/files/4657866/tmux-out-79400.log). When I do `cat tmux-out-79400.log` it sends me to a tmux session, from which I cannot detach.

**Comment by nicm** [comment]
The logs won't say anything useful. If you can't attach and then sending `SIGUSR1` to tmux fixes it, something is removing the socket. The logs won't tell you what is doing that and tmux never removes the socket itself.

You could put the socket outside `/tmp` using the `-S` flag and see if that works. You will need to make sure you always use `-S` though.

**Comment by nicm** [comment]
Or use `TMUX_TMPDIR` instead of `-S`.

**Comment by netw0rkf10w** [comment]
Hmm... I had already set a custom `TMUX_TMPDIR` value, but it doesn't resolve the issue :( 

This is what I currently have in my `bash_profile`:

```
export TMPDIR=$WORK/tmp
export TMUX_TMPDIR=$WORK/tmp
```

In the above, `$WORK` point to some partition on the server. Let me try setting `TMUX_TMPDIR` to be different than `TMPDIR` to see if it works...

**Comment by nicm** [comment]
Is `$WORK` a network file system?

**Comment by netw0rkf10w** [comment]
No it doesn't seem so. The command `df -P -T $WORK | tail -n +2 | awk '{print $2}'` gives me this: `gpfs`.

**Comment by netw0rkf10w** [comment]
Just to make sure I understand what you meant by "something is deleting the tmux socket". The socket `$WORK/tmp/tmux-300840/default` always existed when I checked (it still does), but has size 0. So I guess you meant something is deleting the **content** of the file?

**Comment by nicm** [comment]
Either something is deleting the file entirely and you are creating a new tmux server which recreates it (even if that server is only transient), or something is preventing tmux from connecting to it until you tell it to recreate it with `SIGUSR1`. It's a Unix domain socket, it doesn't have any content.

**Comment by nicm** [comment]
gpfs is a network file system, what if you point `TMUX_TMPDIR` to a local filesystem?

**Comment by netw0rkf10w** [comment]
The default `/tmp` is `xfs`. Let me try resetting `TMUX_TMPDIR` back to that value to see if it works. Could you tell me if I have to close all existing tmux sessions before doing so? Sorry this seems to be a stupid question, but I just want to make sure not doing something wrong (I once upgrading tmux without closing all the sessions and then obtained a `version mismatch` error). Thanks a lot for your help!

**Comment by nicm** [comment]
Yes you will need to completely restart tmux if you change TMUX_TMPDIR.

**Comment by netw0rkf10w** [comment]
It seems to behave better when changing `TMUX_TMPDIR` back to `/tmp`. Last week I changed to `$WORK/tmp` because of a similar issue (`no server running` still, but after a few days, instead of a few minutes). Maybe `/tmp` is cleaned every few days. Let me check this with the server's admin.

**Comment by netw0rkf10w** [comment]
I consider this issue as resolved as the remaining problem with `/tmp` has nothing to do with tmux. Thank you so much again, @nicm!
