### ISSUE TITLE
Some long lines in vim are wrapping incorrectly with tmux 3.1b

### ISSUE THREAD

**Issue by Forcer78** [tmux/tmux#2223]
### Issue description

I found an anomalous line of text ([test.txt](https://github.com/tmux/tmux/files/4665906/test.txt)) that displays incorrectly in vim when running inside tmux.

In the following animated GIF (click for full size), I first show the file opened in vim outside tmux. Resizing the window wraps the line correctly. I then repeat this inside tmux, where the line is immediately incorrect with the wrap overwriting the start. The problem comes and goes as the window is resized. The emoji may be the issue, as spacing around the character is different inside and outside tmux.

![output](https://user-images.githubusercontent.com/17772853/82628154-15315b80-9bba-11ea-849d-3443d8b58415.gif)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
```
tmux 3.1b
```
* Platform (`uname -sp`).
```
Darwin i386
```
* $TERM inside and outside of tmux (`echo $TERM`).
```
screen-256color  (inside)
xterm-256color   (outside)
```
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-6832.log](https://github.com/tmux/tmux/files/4666155/tmux-client-6832.log)
[tmux-out-6834.log](https://github.com/tmux/tmux/files/4666156/tmux-out-6834.log)
[tmux-server-6834.log](https://github.com/tmux/tmux/files/4666157/tmux-server-6834.log)

**Comment by krader1961** [comment]
> The emoji may be the issue, as spacing around the character is different inside and outside tmux.

Yes, the width of emoji code points is a perennial source of fun and irritation :smile: A likely explanation for your problem is that your terminal and tmux are using different Unicode specifications. Thus affecting how the respective programs decide the width of a emoji code point. What code point is that emoji? Knowing the Unicode code point will make it possible to determine if its width has changed between two Unicode specs.

**Comment by Forcer78** [comment]
> What code point is that emoji?

[Ear](https://dict.emojiall.com/en/code/1F442), U+1F442, UTF-8 representation 0xF09F9182. I've found a few more examples, all with (different) emoji, but I can't limit it to them yet.

**Comment by nicm** [comment]
Logs?

**Comment by Forcer78** [comment]
> Logs?

I didn't initially notice that they were written to the working directory. Adding them to the first post.

**Comment by nicm** [comment]
There is no evidence of this Unicode character in this log at all, are you sure it was displayed while you were logging?

**Comment by Forcer78** [comment]
I just opened a new session and quit, since I didn't realize that was the point. In the logged session, do you want me to resize the window as in the GIF?

**Comment by nicm** [comment]
It would be best if you reproduce the problem but if you at least show this symbol then we can see if it has the right width.

**Comment by Forcer78** [comment]
Log files updated. While generating them I noticed a new piece of information: /usr/bin/vim (version 7.4) does not seem to show this problem. The vim from homebrew (version 8.2) does, though only in tmux. Outputs from both are included.

**Comment by nicm** [comment]
tmux correctly knows that this character is width 2. Can you show me a log with just the broken vim not both, also please use a smaller terminal, eg start with 80x24 and resize it smaller.

**Comment by Forcer78** [comment]
As requested. I'm including a screenshot of the logged session showing the broken output (the line that the emoji would have appeared on is incorrect) along with a copy of the correct text itself (with embedded HTML comments to prevent Markdown autolinking).

[tmux-client-7520.log](https://github.com/tmux/tmux/files/4668584/tmux-client-7520.log)
[tmux-out-7522.log](https://github.com/tmux/tmux/files/4668585/tmux-out-7522.log)
[tmux-server-7522.log](https://github.com/tmux/tmux/files/4668586/tmux-server-7522.log)
<img width="697" alt="screenshot" src="https://user-images.githubusercontent.com/17772853/82677521-2740e780-9c16-11ea-8f4d-109fa6c8d830.png">

> @davemark: Steve Jobs, 2003, vehemently:  “People have told us over and over and over again, they don’t want to rent their music.”  And:  “That just doesn’t fly with customers. They don’t want subscriptions!”  Listen to embedded video with sound on. Amazingly prescient. 👂 //@BrianRoemmele https://twitter.com/effspablo/status/1225747813704896519	| https://twitter.com/davemark/status/1225784437692157952

**Comment by nicm** [comment]
I tried exactly what vim is sending to tmux and it shows fine. The log matches the screenshot, right? So you started vim with this text at inside tmux at 80x24 and it was immediately incorect, you didn't need to resize?

Can you attach the actual text file you are using?

What terminal are you using, Terminal.app? Is it the same in another terminal like iTerm2?

Does this still happen if you build tmux from master?

**Comment by Forcer78** [comment]
> The log matches the screenshot, right?

Right.

> So you started vim with this text at inside tmux at 80x24 and it was immediately incorect, you didn't need to resize?

Exactly.
 
> Can you attach the actual text file you are using?

It's linked in the first post.

> What terminal are you using, Terminal.app?

Yes.

> Does this still happen if you build tmux from master?

Haven't tried yet, I use Homebrew in order to avoid having to do that.

**Comment by nicm** [comment]
OK well let me know if it still happens with tmux from master and with a different terminal.

**Comment by nicm** [comment]
vim 8.2 is fine with this file in Terminal.app with tmux master and 3.1b, are you sure you haven't got anything strange in your vim config?

**Comment by Forcer78** [comment]
I ran these tests with no .vimrc. Which version of macOS did you test under? That might be a factor.

Do you think I should cross-post this to the vim project?

**Comment by nicm** [comment]
You can try if you like.

You should try tmux from master, and if you currently have a tmux built with utf8proc then try without.

**Comment by Forcer78** [comment]
Built `tmux next-3.2` from master (without utf8proc, I can't get it to find Homebrew's lib at the moment), same problem.

**Comment by nicm** [comment]
This is something to do with your system or your config, I have:
~~~~
Darwin macbook-pro 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

**Comment by Forcer78** [comment]
Switched to the system default font, no change. I would have been surprised if that was the problem, since `cat` and the older `vim` display the text correctly.

My kernel is 16.7.0 as I'm running macOS 10.12.6.

**Comment by nicm** [comment]
Do you see this with a different terminal like xterm or urxvt or iTerm2?

Terminal.app has a few bugs and it is possible (if perhaps unlikely) that Apple have fixed something.

**Comment by Forcer78** [comment]
iTerm2, same behavior with vim74 and vim82 (shown):

<img width="697" alt="iterm2" src="https://user-images.githubusercontent.com/17772853/82689816-164da180-9c29-11ea-9c90-c574a2f71be8.png">

**Comment by nicm** [comment]
Very strange. I don't know. I can't reproduce this with your file and vim 8.2 and any terminal with either tmux 3.1b or master. And if I take what vim is sending from the tmux log and print it into tmux, it is also fine. All the character widths in your log also match what I have.

If you press `C-b r` after reproducing, does tmux redraw and fix the problem? What about if you press `C-l` in vim instead?

**Comment by Forcer78** [comment]
Tmux redraw actually does fix the display, until the text or window frame changes. Vim redraw doesn't fix it.

Something I just noticed: When adding spaces to the beginning of the line, the emoji will disappear after every 8 added chars. The corruption of the line containing the emoji and those after it are not fixed when the emoji reappears, however.

**Comment by nicm** [comment]
Hmm OK if `C-b r` fixes it, then it is something to do with tmux, it is strange I can't reproduce it.

**Comment by nicm** [comment]
Well, it might be, it could be something else... the fact that `C-b r` works means that tmux's internal screen is OK, so the problem is when it is initially drawn to the terminal.

**Comment by Forcer78** [comment]
I just checked out and built tmux 3.1a, this problem doesn't seem to be present in that version.

**Comment by nicm** [comment]
There is no difference between 3.1a and 3.1b that could in any way cause this, are you sure you are running the versions you think you are?

If I take the output tmux is sending to your terminal from your `tmux-out-7522.log` and send it to Terminal.app here, it is also fine. Can you download this file please: [tmux-out-test.txt](https://github.com/tmux/tmux/files/4669386/tmux-out-test.txt)

And then make an 80x24 terminal and do this:

~~~~
cat tmux-out-test.txt; sleep 1000
~~~~

And see if it looks OK or is wrong.

**Comment by Forcer78** [comment]
Cat results:

<img width="697" alt="sleep" src="https://user-images.githubusercontent.com/17772853/82692639-169c6b80-9c2e-11ea-8713-a3e2e7bc352b.png">

However, something is very very strange. I rebuilt 3.1b and then next-3.2, which I definitely tested in this thread, and their output is now correct. Is this because I haven't quit my other tmux session before testing? But that session is still displaying the problem, I'm going to try restarting everything.

**Comment by nicm** [comment]
Make sure you are running the server version you expect by doing:

~~~~
tmux display -p '#{version}'
~~~~

Or make sure you kill tmux entirely before testing (`tmux kill-server` or `pkill tmux`)

I don't think this is a problem with tmux - the `tmux-out-test.txt` file is fine for me and that is what tmux is actually sending to the terminal when you run it.

I can't think of anything you could do that would give problems with multiple terminals. Do you have anything funny in your shell profiles? What does `stty -a` say before you cat the file?

**Comment by Forcer78** [comment]
I think I have it. I've built two versions of tmux next-3.2 at commit e71c5ef, one through Homebrew --HEAD and one by hand checkout. The only difference seems to be that the brew version is using its own utf8proc (v2.5.0) and perhaps ncurses, while the git checkout isn't using utf8proc.

When the Homebrew version is run, the error surfaces. Subsequent tmux clients (including the git version) that are run without killing the server first inherit the error, which explains some of the bizarre behavior observed.

When the git non-utf8proc server is run, the error is gone. Subsequent tmux clients (including the Homebrew version) run fine.

Finally, I built a version of the git checkout including the Homebrew utf8proc and the error became universal.

This doesn't explain why `tmux-out-test.txt` cats fine on your Terminal and not on mine. stty -a:

```
speed 9600 baud; 81 rows; 362 columns;
lflags: icanon isig iexten echo echoe -echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	-extproc
iflags: -istrip icrnl -inlcr -igncr ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

Maybe utf8proc is introducing output that bugs out only on my system version (across multiple terminal apps?). I am including the logs from the working tmux git build for comparison with post 11's.

[tmux-client-60790.log](https://github.com/tmux/tmux/files/4669834/tmux-client-60790.log)
[tmux-out-60792.log](https://github.com/tmux/tmux/files/4669835/tmux-out-60792.log)
[tmux-server-60792.log](https://github.com/tmux/tmux/files/4669836/tmux-server-60792.log)

**Comment by nicm** [comment]
The difference between the working and nonworking one is that the \360\237\221\202 character is width 2 in the nonworking and width 1 in the working one. This character is meant to be width 2 (and that is what I see it as), but OS X's libc is notoriously bad for character widths so probably it is telling everything it is width 1 and that is what your terminals and perhaps vim itself expect.

**Comment by Forcer78** [comment]
Fantastic job, Apple. Well, at least I have a workaround for now.

Thank you for all your patience and your help.

**Comment by nicm** [comment]
The fact that tmux and the terminal disagree in width means that tmux thinks it has reached the end of the line and wrapped to the next one when in fact it has not, which means the next line overwrites the same line line instead of appearing on the next lineo.

**Comment by Forcer78** [comment]
So utf8proc is actually doing the right thing, and I'm relying on apparent misbehavior to keep working.

**Comment by nicm** [comment]
Yes, sort of... the possibilities are:

1) utf8proc is using a newer Unicode version, and this character has changed width. So both are right, but libc is out of date.

2) utf8proc is right and libc is wrong. Apple's locale implementation is missing or has incorrect widths for a lot of characters. It definitely has one for this one (tmux would say if it didn't), I don't know if it is wrong.

**Comment by nicm** [comment]
In any case, if you have mismatches in character widths between terminal, tmux, applications and font then you will see funny stuff like this. It happens a lot when new Unicode versions are released because it takes years for everyone to catch up.

**Comment by Forcer78** [comment]
I see, thanks. Just as a final question, what downsides could I see by patching utf8proc out of tmux's brew formula going forward? It looks like it's optional anyway in the configure.

**Comment by nicm** [comment]
The only difference is how tmux works out character widths, the default is to use libc's wcwidth, the only reason to use utf8proc is if you have terminal and applications which are using a newer Unicode version than libc. There is no advantage to using one or the other so long as the character widths match between all the programs you are using.

**Comment by Forcer78** [comment]
Great. Thanks again.
