### ISSUE TITLE
Automatic rename tab title format

### ISSUE THREAD

**Issue by Wsine** [tmux/tmux#2224]
Is it possible for setting the tab title in below format?

`set-option -g automatic-rename-format '#{?some_flag,#{pane_current_command},#{b:pane_current_path}}'`

I want it to show the current long-term command (e.g. vim/compilation/...) when the active pane is busy and show the current path if it is not.

I have searched and tried a lot about FORMATS sections in `man tmux`but failed.

Are there anyone know the solution? Thanks.

**Comment by nicm** [comment]
You could look at `window_activity` and compare it to the current time but you would need to write a script, tmux doesn't have a way to do it builtin, although it is a nice idea.
