### ISSUE TITLE
How to use `status-format[]` to customize a multiple status line?

### ISSUE THREAD

**Issue by Ma-Nu-El** [tmux/tmux#2225]
# Table of Contents

1.  [preamble](#org37ba164)
2.  [issue: example of multiple status line](#org269827f)
    1.  [what I'd like to see in the status line:](#org1fe8b2b)
    2.  [what I need to get where I want](#org1e04439)
    3.  [where I am right now](#org2d4549a)
3.  [system info](#org0b87540)
    1.  [Required for issue](#orgcb8279b)
    2.  [Sensible for the context as far as I understand](#orge68c00e)
4.  [my tmux config](#orge83020c)
    1.  [general](#orgf742862)
        1.  [quick reloading](#orge7b7697)
        2.  [no escape delay for vim](#orgc31a82b)
        3.  [necessary for things to work fine](#orgca0d118)
    2.  [status line [where the issue begins]](#orge7aae17)
        1.  [general](#org61012ef)
        2.  [line specific [here lies the issue]](#org340a53d)

<a id="org37ba164"></a>

# preamble

I've already read the manual a lot of times only to solve this and
I've tried different configurations for the `status-format[]` option
but still can't get it to work.

Also, this is my very first issue so if I've missed something crucial
please let me know.

<a id="org269827f"></a>

# issue: example of multiple status line

<a id="org1fe8b2b"></a>

## what I'd like to see in the status line:

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">row</th>
<th scope="col" class="org-left">info about</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">Top</td>
<td class="org-left">tmux session and windows</td>
</tr>

<tr>
<td class="org-left">Bottom</td>
<td class="org-left">system and hardware</td>
</tr>
</tbody>
</table>

<a id="org1e04439"></a>

## what I need to get where I want

I need to know how to manipulate the text contained in this areas,
which until now I don't.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">top left</th>
<th scope="col" class="org-left">top center</th>
<th scope="col" class="org-left">top right</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">bottom left</td>
<td class="org-left">bottom center</td>
<td class="org-left">bottom right</td>
</tr>
</tbody>
</table>

<a id="org2d4549a"></a>

## where I am right now

All I've been able to do for now is

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">"top"</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">"bottom"</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

by using the following in my .tmux.conf

    set-option -g status 2 
    set-option -g status-format[0] "top" 
    set-option -g status-format[1] "bottom"

<a id="org0b87540"></a>

# system info

<a id="orgcb8279b"></a>

## Required for issue

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">`echo $TERM (outside tmux)`</td>
<td class="org-left">`xterm-256color`</td>
</tr>

<tr>
<td class="org-left">`echo $TERM (inside tmux)`</td>
<td class="org-left">`xterm-256color`</td>
</tr>

<tr>
<td class="org-left">`uname -sp`</td>
<td class="org-left">`Linux x86_64`</td>
</tr>

<tr>
<td class="org-left">`tmux -V`</td>
<td class="org-left">`tmux 3.0a`</td>
</tr>
</tbody>
</table>

<a id="orge68c00e"></a>

### log files
https://github.com/tmux/tmux/files/4672314/tmux-server-27311.log
https://github.com/tmux/tmux/files/4672312/tmux-client-27309.log
https://github.com/tmux/tmux/files/4672313/tmux-out-27311.log

## Sensible for the context as far as I understand

    $ screenfetch
    
    OS: Ubuntu 20.04 focal
    Kernel: x86_64 Linux 5.4.0-31-generic
    Shell: bash 5.0.16
    DE: KDE 5.68.0 / Plasma 5.18.4
    WM: KWin
    GTK Theme: Breeze [GTK2/3]
    Icon Theme: breeze

<a id="orge83020c"></a>

# my tmux config

<a id="orgf742862"></a>

## general

<a id="orge7b7697"></a>

### quick reloading

    bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

<a id="orgc31a82b"></a>

### no escape delay for vim

    set -sg escape-time 0 

<a id="orgca0d118"></a>

### necessary for things to work fine

    set-window-option -g xterm-keys on 
    set -s default-terminal "xterm-256color"

<a id="orge7aae17"></a>

## status line [where the issue begins]

<a id="org61012ef"></a>

### general

    set-option -g status-position bottom
    set-option -g status-interval 1

<a id="org340a53d"></a>

### line specific [here lies the issue]

    set-option -g status 2 
    set-option -g status-format[0] "top" 
    set-option -g status-format[1] "bottom"

**Comment by Ma-Nu-El** [comment]
[tmux-client-27309.log](https://github.com/tmux/tmux/files/4672312/tmux-client-27309.log)
[tmux-out-27311.log](https://github.com/tmux/tmux/files/4672313/tmux-out-27311.log)
[tmux-server-27311.log](https://github.com/tmux/tmux/files/4672314/tmux-server-27311.log)

**Comment by nicm** [comment]
You need to combine two things, embedded styles, formats and commands in `#()`. Look at: https://github.com/tmux/tmux/wiki/Getting-Started#colours-and-styles and https://github.com/tmux/tmux/wiki/Formats

For example:
~~~~
set -g status-format[1] '#(uname)#[align=right]xyz'
~~~~

**Comment by Ma-Nu-El** [comment]
wow quick reply, thanks a lot! I'll take a look at that.

**Comment by Ma-Nu-El** [comment]
YES! That's exactly what I wanted to do! Thank you very much!

I'll paste the config that made the trick:

    set -g status-format[0] '#[align=left]Top left'
    set -ag status-format[0] '#[align=centre]Top center'
    set -ag status-format[0] '#[align=right]Top right'
    set -g status-format[1] '#[align=left]Bottom left'
    set -ag status-format[1] '#[align=centre]Bottom center'
    set -ag status-format[1] '#[align=right]Bottom right'

And the result of that

![tmux-multi-status](https://user-images.githubusercontent.com/51767176/82738862-e70e6180-9d08-11ea-93cd-f40d70b3c148.png)
