### ISSUE TITLE
[Question] Yanking text highlighted from search

### ISSUE THREAD

**Issue by iovis** [tmux/tmux#2227]
Now that we have regex searches (which is awesome), I was wondering if there was a way to yank the highlighted text from a search.

For instance, let's say I run rspec and I fetch the failing specs:
![IMG_0328](https://user-images.githubusercontent.com/6660202/82762284-1044f580-9dce-11ea-9768-af1e0288b797.png)

I made a keybinding to make this search and highlight the results but I haven't found a way to yank it (in vim I can for instance do `ygn` to yank the current one). In this particular case I could just yank the line, given that the unwanted text will be computed as a comment, but I have to manually select if I'm looking for IPs or something like that.

**Comment by nicm** [comment]
If you are using master then copy will use the current search match if there is no selection.

**Comment by iovis** [comment]
That's amazing, I'm guessing it'll be released as 3.2?
