### ISSUE TITLE
C_B M can not popup menu 

### ISSUE THREAD

**Issue by xspeed1989** [tmux/tmux#2229]
tmux version:tmux 2.9a
Platform:Linux x86_64  (centos 7)
 $TERM inside:  screen-256color, outside:xterm-256color

**Comment by nicm** [comment]
Because they weren't supported until 3.0?

**Comment by xspeed1989** [comment]
> Because they weren't supported until 3.0?

I think 3.0 has the same issue

**Comment by nicm** [comment]
You think it does, or it does?

**Comment by xspeed1989** [comment]
> You think it does, or it does?

yes, I test again
I get the same issue on  tmux 3.1b

**Comment by nicm** [comment]
`C-b m` does not popup a menu, do you mean `C-b <` or `C-b >`?

**Comment by xspeed1989** [comment]
> `C-b m` does not popup a menu, do you mean `C-b <` or `C-b >`?
![image](https://user-images.githubusercontent.com/5162926/82787877-f670e480-9e99-11ea-9288-bbd7e3952d1a.png)
This menu is popup when I right-click on tmux

**Comment by nicm** [comment]
>The key binding for that menu is `C-b >`.

**Comment by xspeed1989** [comment]
> > The key binding for that menu is `C-b >`.

OK! thanks

**Comment by xspeed1989** [comment]
> > The key binding for that menu is `C-b >`.

C-b > didn't work when I use it in ssh by git bash

**Comment by nicm** [comment]
Are you sure you are running tmux 3.0 or later on the remote host?

**Comment by xspeed1989** [comment]
> Are you sure you are running tmux 3.0 or later on the remote host?

tmux 3.0 work fine
