### ISSUE TITLE
Zsh 5.1+ bracketed paste and tmux command prompt

### ISSUE THREAD

**Issue by rmats** [tmux/tmux#223]
On zsh 5.1+, the newly introduced bracketed paste mode adds unwanted characters to text pasted on tmux's command prompt, for example if `new-window` is copied into the clipboard, then pasted into the tmux command prompt (`<prefix>:`), it comes out as:

`200~new-window201~`

A workaround is to disable bracketed paste on .zshrc:

```shell
if [ ${TMUX} ]; then
 unset zle_bracketed_paste
fi
```

Text pasted elsewhere inside tmux works as it's supposed to. Observed this behavior on Fedora 23 with tmux 2.0 and zsh 5.1.1.

From zsh's README:

```
Incompatibilites between 5.0.8 and 5.1

The default behaviour when text is pasted into an X Windows terminal has
changed significantly (unless you are using a very old terminal emulator
that doesn't support this mode).  Now, the new "bracketed paste mode"
treats all the pasted text as literal characters.  This means, in
particular, that a newline is simply inserted as a visible newline; you
need to hit Return on the keyboard to execute the pasted text in one go.
See the description of zle_bracketed_paste in the zshparams manual for
more.  "unset zle_bracketed_paste" restores the previous behaviour.
```

**Comment by nicm** [comment]
tmux doesn't support bracketed paste on input.
