### ISSUE TITLE
Kill Tmux session when on tmux session

### ISSUE THREAD

**Issue by rajeshisnepali** [tmux/tmux#2230]
I know the process to kill any session when in detached mode or killing session having a window or pane.

But suppose I have 2 panes in 3 windows each. And I want to close the session by staying inside the session. Is it possible?

I've heard somewhere hitting `prefix + x` kills the session but that kills my pane.

**Comment by nicm** [comment]
You can either `detach-on-destroy` to `off`, or change to a different session first with `C-b s` or `switch-client` and then kill the previous session.

**Comment by rajeshisnepali** [comment]
I think, I'll go with the second one.
