### ISSUE TITLE
Window listing doesn't respect window-status-format

### ISSUE THREAD

**Issue by Racle** [tmux/tmux#2235]
### Issue description
After setting 
```
set -g window-status-format '#I:#(pwd="#{pane_current_path}"; echo ${pwd####*/})>#{pane_current_command}#F'
set -g window-status-current-format '#I:#(pwd="#{pane_current_path}"; echo ${pwd####*/})>#{pane_current_command}#F'
```
I can see changes in bottom window titles.
When I press my Leader (Ctrl+a) and after that `w` I can see window listing. 
That listing has only running app name, not window title what I've configured, making it basically useless.
ex. I have vim opened in three windows. I have `current_folder>vim` showing in bottom row, but window list shows only `vim` . 

[Full .tmux.conf here](https://raw.githubusercontent.com/Racle/dotfiles/master/tmux/.tmux.conf)
Disabling theme doesn't affect this issue.

### Required information

Please provide the following information:

* tmux version: 3.0a
* Platform: LInux X86_64 (pop_os 20.04)
* $TERM inside and outside of tmux: inside: screen-256color, outside: xterm-256color

**Comment by nicm** [comment]
No, the format for tree mode is set with `choose-tree -F`, it does not use the status line options.

**Comment by Racle** [comment]
> No, the format for tree mode is set with `choose-tree -F`, it does not use the status line options.

You're right. I searched manual for "window list" and couldn't find anything related to this.

Maybe it's just me, but seems logical to have same window format on tree view as it's on windows itself

After adding 
```sh
bind w 'choose-tree -ZwF "#{b:pane_current_path}>#{pane_current_command}"'
bind C-w 'choose-tree -ZwF "#{b:pane_current_path}>#{pane_current_command}"'
```
everything works just as I like it
