### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [tmux/tmux#2236]
Would you like to add more error handling for return values from functions like the following?
- [fclose](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [file_write](https://github.com/tmux/tmux/blob/a4cb700269e033b5ad429275d7c61d3c3c2f1af3/file.c#L269)
- [fputs](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fputs.html "Put a string on a stream.") ⇒ [status_prompt_save_history](https://github.com/tmux/tmux/blob/a4cb700269e033b5ad429275d7c61d3c3c2f1af3/status.c#L139)

**Comment by nicm** [comment]
I don't really see much point. What would tmux do when fclose fails?

**Comment by elfring** [comment]
I suggest to report an error similar to other failed function calls.

-----

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by nicm** [comment]
Nah, fclose never usefully fails. I don't see much worry about fputs failing in the history save bit either really.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by nicm** [comment]
Don't worry about fclose, it is OK to assume it won't fail, and if it does, what are the consequences? I think the fputs is fine also.
