### ISSUE TITLE
When an attached window is resized, panes from non-attached windows are only redrawn when the terminal emulator is resized.

### ISSUE THREAD

**Issue by rmo20** [tmux/tmux#2237]
### Issue description

Let **`(a)`** denote a workspace with a terminal emulator whose shell is attached to a `tmux` session **`(b)`**.

When opening a new window in **`(a)`** and closing it. The pane from the current window from **`(b)`** is redrawn while the panes from the windows which are not attached are not redrawn. In order to redraw the panes from all windows, I need to resize the terminal emulator at least one time in any attached window.

You might understand better the statement presented above with this gif.

![image](https://s7.gifyu.com/images/2020_05_28__04_08_23.gif)

As you can see in the gif, I had multiple apps on a `tmux` session. I opened a window and the current attached window was redrawn. However, when visiting the other windows, the panes were not redrawn. They were only redrawn when I resized the terminal emulator.

Isn't it possible to make `tmux` redraw all panes without having the user to manually resize the terminal emulator?

Minimal `tmux` configuration

```
set-option -g default-terminal "tmux-256color"
```

### Required information

__`tmux` version__

```
$ tmux -V
tmux 3.1b
```

__Platform__

```
$ uname -sp
Linux unknown
```

```
$ uname -sr
Linux 5.6.13-arch1-1
```

Terminal emulator

```
$ st -v
st 0.8.2
```

Window manager

```
$ dwm -v
dwm-6.2
```

__`$TERM` inside and outside of tmux__

Outside `tmux`

```
$ [ -z $TMUX ] && echo $TERM
st-256color
```

Inside `tmux`

```
$ [ ! -z $TMUX ] && echo $TERM
tmux-256color
```

__Logs from `tmux`__

After executing the following command (see below) and exit the `tmux` session

```
$ tmux kill-server ; tmux -vv new
no server running on /tmp/tmux-1000/default
[exited]
```

three files were created with the following names

```
$ wc -l * | head -n -1
    84 tmux-client-17721.log
   304 tmux-out-17723.log
 14470 tmux-server-17723.log
```

I think the following would be relevant information for this specific issue

```
$ grep -n -e '\<TERM\>' -r
tmux-server-17723.log:10650:1590657041.471646 client 0x555cb22faaf0 IDENTIFY_ENVIRON TERM=st-256color
tmux-server-17723.log:11208:1590657041.473533 spawn_pane: environment TERM=tmux-256color
```

Complete log files wil be shared if asked.

**Comment by nicm** [comment]
Does this still happen with master? There was a fix for something like this.

**Comment by facadeproof** [comment]
Yes, still happening on latest master on Void Linux.

**Comment by nicm** [comment]
Show me the tmux server log from reproducing with master please.

**Comment by facadeproof** [comment]
Now working correctly, I had to delete my previous sessions.

**Comment by rmo20** [comment]
@nicm It is solved now. I'm attaching a gif as a proof that the problem has already been solved. The gif was performed with the same configuration file as the previous gif (i.e. the minimal tmux configuration presented in the issue description)

![image](https://s7.gifyu.com/images/2020_05_28__14_28_27.gif)

The gif starts when the notification with content "Gif started" appears.

**Comment by nicm** [comment]
OK great stuff, thanks.
