### ISSUE TITLE
Cant new a Session

### ISSUE THREAD

**Issue by www516717402** [tmux/tmux#2238]
It can run well for the first time, However，When reinstall tmux, It donsnt work. Like follows:

- tmux -V
> tmux 2.6

- tmux new -s python37

![image](https://user-images.githubusercontent.com/30460509/83134140-7efbb900-a116-11ea-9fd2-6fd7e07c1644.png)
> Cant open a session. stuck always.

**Comment by nicm** [comment]
Does this still happen with a newer tmux version?

**Comment by www516717402** [comment]
@nicm sorry reply late. This question since huge session not killed. When I kill all session, this issue will be disappear.
