### ISSUE TITLE
Upgrading from 2.9 to 3.0: message-style now requiring all fields to be set is not documented

### ISSUE THREAD

**Issue by dmonopoly** [tmux/tmux#2239]
$ tmux -V
tmux 3.0a

My old version was tmux 2.9. I noticed a couple issues when my machine force-updated.

I used to have
```
set -g message-style bg=colour100,fg=colour232
```

but this broke. It now requires all fields to be populated, it seems:
```
set -g message-style bg=colour100,fg=colour232,bright
```

This took a while to figure out. The error message only printed the syntax without clearly indicating it was required. 

I think there's a fundamental communication or migration issue in tmux updates, as this is the third time my tmux conf has unexpectedly broken in tmux updates. I am also in a work setup where tmux may update under-the-hood without my desire for when, so it's not a great experience.

**Comment by nicm** [comment]
This sounds like a bug, does it still happen with tmux 3.1 or master?
