### ISSUE TITLE
Border not displaying correctly?

### ISSUE THREAD

**Issue by sbacic** [tmux/tmux#224]
Here are some screenshots:

https://imgur.com/a/Ljmz2

Basically, every time the rightmost panel is selected, the border does not go all the way. There are also some (possibly unrelated) issues with mouse text select with the select overflowing into other panes.

I'm running tmux inside a docker container (ubuntu:trusty). The same issue does not exist on the host system (Elementary OS Freya).

**Comment by nicm** [comment]
tmux version? terminal? TERM inside and outside tmux? Are you using UTF-8?

**Comment by sbacic** [comment]
Tmux version is 2.0 in container, 1.8 on host, but I'm reasonably sure that I had that problem on 1.8 as well (probably why I upgraded to 2.0, thinking it would go away). 
TERM returns the same on both host and container - xterm outside and screen inside tmux.
For UTF-8, I tried printing the EURO sign, works fine on both host and container.

Not sure what you mean by terminal...

I've also noticed a one other things that might help; if I open something like midnight commander in the right pane, it shows the borders fine, but if I open in the left and then switch focus between them I get something like this: https://imgur.com/tvSd4h8.

**Comment by nicm** [comment]
What terminal are you running tmux inside?

**Comment by sbacic** [comment]
You mean the host OS terminal application? That would be pantheon-terminal.

**Comment by nicm** [comment]
Does it still happen in xterm?

**Comment by sbacic** [comment]
Installed xterm on host. The issue persists.

**Comment by nicm** [comment]
Hmm. Please run "tmux -vvvv -f /dev/null -Ltest new" then reproduce the problem and send me the tmux-*.log files.

**Comment by sbacic** [comment]
Here are the log files. All I did was open tmux, created another pane and switched between them. 
http://s000.tinyupload.com/index.php?file_id=02153881842721797464

**Comment by nicm** [comment]
If you put just this in terminal-overrides, does it fix the problem:

set -ag terminal-overrides '*:cud1=\E[1B'

**Comment by nicm** [comment]
I edited the previous comment, make sure you include the comma:

set -ag terminal-overrides ',*:cud1=\E[1B'

**Comment by sbacic** [comment]
I've just tested the fix you provided and it appears to be working properly now. The border is displaying properly and there is no graphical anomalies. Can you tell me what happened?

**Comment by nicm** [comment]
Something has a bug and is treating LF (\n) like CRLF (\r\n). In non-canonical mode, LF should just move the cursor one line down, it should not also move it to the start of the line. Since it is the same in xterm I suspect it is not the terminal itself, what else is getting the data between tmux and xterm?

**Comment by sbacic** [comment]
First off, I ran this from pantheon-terminal, not xterm. And the only thing between them is the docker container (without any processes running, other than bash).

**Comment by nicm** [comment]
But you tried it in xterm earlier right and the bug was still there?

**Comment by sbacic** [comment]
Yes, of course. Both the bug and solution work in xterm and pantheon-terminal. As far as I'm concerned, this problem is solved you can close this issue.

In case somebody with this same problem Googles the issue (broken border/graphic artifacts in tmux under docker), here's the solution: just add 

> set -ag terminal-overrides ',*:cud1=\E[1B'

to your .tmux.conf file (mine is in ~/.tmux.conf).

**Comment by nicm** [comment]
I expect this is a bug in docker or in your Linux install, you may see other problems too since \n is not behaving as expected.

**Comment by tarvos21** [comment]
Hi, anyone there, I have the same problem with the pane border line, when I split the screen into left and right panes, then split the right pane into up and down panes, the **horizontal** border line does not work properly, it **expands to the left pane** which has not been split.
My tmux is 2.1, on Ubuntu 16.04, not container. I use default Ternimal on Ubuntu.

**Comment by sbacic** [comment]
Hi there, sorry for the late reply. I've moved on from the setup described in the issue so I'm afraid I can't help you much. Sorry :(

**Comment by hitochan777** [comment]
@tarvos21 I had a similar issue as yours. I fixed the problem by changing "ambiguous-width chars" setting from "full width" to "half width" in gnome terminal. ("Edit" -> "Profile Preferences" -> "Compatibility" -> "Ambiguous-width chars").
I don't know if you have this option because I use Japanese remix version.
