### ISSUE TITLE
Issue #1299 persisting?

### ISSUE THREAD

**Issue by pvalena** [tmux/tmux#2241]
> Running a command from tree mode uses EITHER the selected pane or the tagged pane, not both. They will both be passed as -t to join-pane; if you want to specify -s you need to mark the pane (-s will use the marked pane by default).

_Originally posted by @nicm in https://github.com/tmux/tmux/issues/1299#issuecomment-377165190_

I've experienced this with:
tmux-3.0a-2.fc32.x86_64

I'm not sure when was the patch applied. It crashed the server.

I've run (with the window menu displayed) `:join-pane -s 2`

**Comment by nicm** [comment]
Does this still happen with tmux 3.1 or master?

**Comment by pvalena** [comment]
Ah, I've updated to 3.1, it's fixed. :) Thanks.
