### ISSUE TITLE
Window size keeps changing when sharing a session

### ISSUE THREAD

**Issue by gcapizzi** [tmux/tmux#2243]
### Issue description

When sharing a tmux session over SSH, tmux used to resize the window to the smallest of the two terminals, showing a dots padding to the user with the biggest terminal. With the latest version, tmux keeps resizing the window to the size of the terminal of the person that is typing. This means the person with the smallest terminal gets their content clipped. We first noticed this on 3.1b, but it persists on HEAD.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux next-3.2`
* Platform (`uname -sp`): `Darwin i386`
* $TERM inside and outside of tmux (`echo $TERM`): `screen`
* Logs from tmux (`tmux kill-server; tmux -vv new`): [tmuxlogs.tar.gz](https://github.com/tmux/tmux/files/4700937/tmuxlogs.tar.gz)

**Comment by nicm** [comment]
Change `window-size` to `smallest` or `largest`.

**Comment by gcapizzi** [comment]
@nicm Oh! I see the `latest` value has been introduced and maybe it's the default now? Pretty sure `smallest` had been default until now, any particular reason this was changed?
