### ISSUE TITLE
tmux lost server on tmux 2.6 ubuntu after clean install without .conf files

### ISSUE THREAD

**Issue by dvirginz** [tmux/tmux#2244]
I've deleted `~/.tmux.conf`, 
Then tried installing using `apt`:
`sudo apt-get remove tmux` and `sudo apt-get install tmux`
Which didn't work. (error tmux lost)
After that tried from source 
`git clone https://github.com/tmux/tmux.git->cd tmux->sh autogen.sh->./configure && make`
which did not work either.
I've probably changed something in the system because tmux used to work, But I have no idea what.
I've seen the previous topics about `lost server` on startup, but all discuss config files, and I deleted mine just-in-case.

* tmux version (`tmux -V`). 2.6 and 3.1b
* Platform (`uname -sp`) Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`). lost server lost server (2.6) and server exited unexpectedly (tmux 3.1b)

**Comment by nicm** [comment]
tmux 2.6 is too old, please try tmux 3.1b or master and see if the problem still exists.

**Comment by dvirginz** [comment]
as specified, I also used a fresh git pull and installed from source.
I have now also built from the 3.1b release, with the following error
`server exited unexpectedly`

**Comment by krader1961** [comment]
What command are you running? You should also provide log files from starting a client and server with the `-vv` flag? Have you actually verified there isn't an old tmux server running when you attempt to use a tmux client to start a new session?

**Comment by krader1961** [comment]
Also, it would increase our confidence you were using tmux built from the source "head" if you provided the output of `tmux -V`.

**Comment by dvirginz** [comment]
Hi, thanks a lot for helping!:)
Following other issues, I've added the following lines to ~/.tmux.conf to try and fix the problem
```
set exit-empty off
set -g default-shell /bin/sh
```
When running (with or without those lines
`tmux -v` or `tmux -vv` or `tmux -vvv` I get `server exited unexpectedly` immediately.
When running `tmux -V` I get `tmux 3.1b`

**Comment by dvirginz** [comment]
I've fixed it!
`sudo rm -rf /tmp/tmux*`
and
`tmux kill-server` did the job.

**Comment by krader1961** [comment]
> tmux -v or tmux -vv or tmux -vvv I get server exited unexpectedly immediately.

Yes, but you should also have tmux log files in your CWD. You also did not say you had confirmed no existing tmux server was running at the time you reproduced the problem.

**Comment by krader1961** [comment]
> tmux kill-server did the job.

Which is why I asked if you had confirmed there was no tmux server running before you ran the tmux client command that reported the error. :smile:.

**Comment by dvirginz** [comment]
Hi, I just want to put it here again as it happened to me.
If for some reason you have active tmux sessions, and kill the user using `killall -u`, trying to `tmux kill-server` without deleting the cache `sudo rm -rf /tmp/tmux*` does not work for me.
Leaving it here for future reference
