### ISSUE TITLE
tmux error after detaching from split-pane

### ISSUE THREAD

**Issue by kevingunn-wk** [tmux/tmux#2246]
### Issue description

After detaching a session, I get this error message:

> set -t $2 @iterm2_size 170,24; refresh-client -C 170,24; list-windows -F "#{window_id} #{window_layout} #{window_flags}"
set: can't change option: -t

I'm running tmux 3.1b and iterm 3.3.9 with zsh

### Steps to Reproduce

* Open iterm2
* Run `tmux -CC`
* In tmux session, type the following:
```
$ tmux split-pane
$ tmux detach
```
* Note the error returned after detaching

### Required information

Please provide the following information:

* tmux version: `3.1b`
* Platform: `macOS 10.15 (Darwin i386)`
* $TERM inside and outside of tmux: `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`):
[tmux-client-98821.log](https://github.com/tmux/tmux/files/4703992/tmux-client-98821.log)

**Comment by nicm** [comment]
This is just the client log, please kill tmux completely and run with `-vv` and then show me the server log file.

**Comment by kevingunn-wk** [comment]
[tmux-server-52247.log](https://github.com/tmux/tmux/files/4711462/tmux-server-52247.log)
Sorry, attaching server log.

**Comment by nicm** [comment]
This error (`set: can't change option: -t`) is coming from the shell rather than from tmux, it must be because there is stray input from iTerm2 left after tmux detaches, I don't know why that would be - @gnachman?

**Comment by gnachman** [comment]
There's an unavoidable race condition when tmux decides to initiate detach. When you create a new pane, iTerm2 needs to ask tmux about its size, history, etc. In this case it looks like the detach happened so soon after split-pane that those commands got sent to the shell instead of tmux.

The problem of iTerm2 spamming your shell after tmux exits is a semi-frequent complaint. There are many different cases that cause this. For example, exiting the shell in the last window pane will do it sometimes. I've taken steps to mitigate the problem, such as waiting a half second after the last pane terminates before sending a command, but such heuristics will always be imperfect. 

@nicm  We could fix 99% of it by requiring a control mode client to confirm `%exit`. A simple solution would be for `client.c` to read from stdin after sending `%exit` until it gets a blank line. But we'd need to make sure not to break old versions of iTerm2 if we do something like that.

**Comment by nicm** [comment]
We could just add a flag to enable this behaviour (like `no-output`).

**Comment by gnachman** [comment]
Command line flag or `set -g` option? It would be hard to get adoption for a command line flag since everyone would need to change their configs.

**Comment by nicm** [comment]
`refresh-client -f` (or `-F`) like `no-output`, you can send it as soon as you attach.

**Comment by gnachman** [comment]
Oh, I see. Yeah, that would be great.

**Comment by nicm** [comment]
Can you try this please and see if it meets your needs? [tmux-wait-exit.diff.txt](https://github.com/tmux/tmux/files/4764209/tmux-wait-exit.diff.txt)

You will need to send `refresh-client -fwait-exit` (you can send it as part of the existing `refresh-client -f` for `pause-after` - they are comma separated). Then tmux should wait after `%exit` for an empty line.

You can check if the flag was set if you need to by looking at `tmux display -p '#{client_flags}'`:
~~~~
...
%output %0 nicholas@yelena:/usr/src/usr.bin/tmux2$
refresh-client -fpause-after=33,wait-exit
%begin 1591871744 267 1
%end 1591871744 267 1
display -p '#{client_flags}'
%begin 1591871747 268 1
attached,control-mode,wait-exit,pause-after=33,UTF-8
%end 1591871747 268 1
detach
%begin 1591871750 269 1
%end 1591871750 269 1
%exit

**Comment by nicm** [comment]
Oh there is an `#include <vis.h>` I left in client.c by accident which may not build on some platforms, here it is with this removed: [tmux-wait-exit2.diff.txt](https://github.com/tmux/tmux/files/4764243/tmux-wait-exit2.diff.txt)

**Comment by gnachman** [comment]
I don't get `%exit` at all with this patch when the last pane in a session exits, regardless of if `wait-exit` is enabled. It seems to hang the client.

[tmux-06-13-2109.zip](https://github.com/tmux/tmux/files/4775837/tmux-06-13-2109.zip)

**Comment by gnachman** [comment]
Removing `bufferevent_disable(cs->read_event, EV_READ|EV_WRITE);` fixed it well enough to make it testable, it looks good.

**Comment by nicm** [comment]
I had to add that or the tmux server might consume the newline before the client sees it. I'll take a look tomorrow.

**Comment by nicm** [comment]
The line you removed should just be `EV_READ` not both. Please try this: 
[tmux-wait-exit3.diff.txt](https://github.com/tmux/tmux/files/4779564/tmux-wait-exit3.diff.txt)

**Comment by gnachman** [comment]
That works great. I've committed support for it in https://github.com/gnachman/iTerm2/commit/a07cc35e04bfca7116d0add49fddaf87134d445c

**Comment by nicm** [comment]
Great stuff. I have applied this to OpenBSD now, it should be in GitHub later. Thanks!
