### ISSUE TITLE
Unicode switch is not working when used in new-session

### ISSUE THREAD

**Issue by megapro17** [tmux/tmux#2249]
Test command:
`tmux -u new-session -d -s test sh -c "echo Unicode test: 😂✅🤦‍♂️🍙; busybox ### sh"`
Output:
```
Unicode test: ______


BusyBox v1.30.1 () built-in shell (ash)

root@OpenWrt:~#
```

My terminal supports Unicode, if I write it without tmux, I can see emoji correctly, if I just use `tmux -u` unicode works

### Required information
Please provide the following information:

* tmux version (`tmux -V`). tmux 3.1b
* Platform (`uname -sp`). Linux unknown (it is Openwrt router, mipsel)
* $TERM inside and outside of tmux (`echo $TERM`).
Inside: screen
Outside: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-11458.log.gz.gz](https://github.com/tmux/tmux/files/4706916/tmux-client-11458.log.gz.gz)
[tmux-out-11461.log.gz.gz](https://github.com/tmux/tmux/files/4706917/tmux-out-11461.log.gz.gz)
[tmux-server-11461.log.gz.gz](https://github.com/tmux/tmux/files/4706918/tmux-server-11461.log.gz.gz)

**Comment by nicm** [comment]
Are you sure you passed `-u` when you created these log files?

**Comment by megapro17** [comment]
> Are you sure you passed `-u` when you created these log files?

Like this? `tmux kill-server; tmux -u -vv new`
[tmux.zip](https://github.com/tmux/tmux/files/4711490/tmux.zip)

**Comment by nicm** [comment]
Hmm. tmux is definitely sending the flag from the client and your example works for me. Does this still happen for you if you build tmux from master?

**Comment by megapro17** [comment]
Didn't tried. Most likely it's busybox fault then...

**Comment by nicm** [comment]
No, tmux will replace UTF-8 with `_` if it thinks the client doesn't support UTF-8, but from your log it looks like that shouldn't be the case. There have been some changes to how flags are stored in master, so it would be worth seeing if it is fixed.
