### ISSUE TITLE
Segfault with Tmux 1.9

### ISSUE THREAD

**Issue by nicoolas** [tmux/tmux#225]
Hello,

In case this can be of any help, I just had a one-time tmux segfault.

I had the tmux server running for 49 days, and was playing with joining panes (command join-pane) when tmux crashed.

**Syslog traces:**
tmux[15177]: segfault at c ip 00007f37673c7da7 sp 00007ffe19b6c4e0 error 4 in tmux[7f37673a2000+69000]

**$ tmux -V**
tmux 1.9

**$ uname -a**
Linux xxx 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13) x86_64 GNU/Linux

**$ cat /etc/debian_version**
8.0

**Comment by nicm** [comment]
Try later tmux version.
