### ISSUE TITLE
Text input duplication

### ISSUE THREAD

**Issue by cinerea0** [tmux/tmux#2250]
### Issue description

My tmux configuration, which was previously working just fine previous versions, is now producing very strange results. The best way to put it is that text I input gets duplicated on subsequent keystrokes. For example, here is what happens when I enter the text "exit" and then press the backspace key four times to erase that text:

![text_error](https://user-images.githubusercontent.com/49368915/83342803-11e94e80-a2e3-11ea-90ac-c1084318e43e.png)

[tmux.conf.txt](https://github.com/tmux/tmux/files/4706983/tmux.conf.txt)

### Required information

* tmux version: tmux 3.1b
* Platform: Linux unknown (actually Void Linux)
* $TERM inside and outside of tmux: alacritty / tmux-256color
* Logs from tmux: 
[tmux-client-23111.log](https://github.com/tmux/tmux/files/4706963/tmux-client-23111.log)
[tmux-out-23113.log](https://github.com/tmux/tmux/files/4706964/tmux-out-23113.log)
[tmux-server-23113.log](https://github.com/tmux/tmux/files/4706965/tmux-server-23113.log)

**Comment by nicm** [comment]
I don't see any backspace keys in your server log file, are you sure you reproduced the problem when you were logging?

**Comment by cinerea0** [comment]
It's possible I didn't. I just reproduced the exact error I show in the screenshot in my initial post while logging; the logs are attached. Also, to clarify something I left out of my original post: This error does not occur when running tmux without a configuration file.
[tmux-client-16570.log](https://github.com/tmux/tmux/files/4712855/tmux-client-16570.log)
[tmux-out-16572.log](https://github.com/tmux/tmux/files/4712862/tmux-out-16572.log)
[tmux-server-16572.log](https://github.com/tmux/tmux/files/4712863/tmux-server-16572.log)

**Comment by nicm** [comment]
This seems like a problem with your shell, are you sure it is configured to accept `C-?` (`\177`) as backspace and not expecting `C-h`? When you press `C-h` does it backspace properly?

**Comment by nicm** [comment]
Maybe it looks at `TERM` for `kbs` and your platform patches `screen` but not `tmux`. What does this show:
~~~~
infocmp -x screen tmux|grep kbs
~~~~

**Comment by cinerea0** [comment]
The output looks like this: "infocmp: couldn't open terminfo file /usr/share/terminfo/t/tmux."
I take it that means my system doesn't even have terminfo for tmux? Running `infocmp -x screen|grep kbs` results in the following output: "ind=\n, indn=\E[%p1%dS, is2=\E)0, kbs=^H, kcbt=\E[Z,"

**Comment by nicm** [comment]
Right, you don't have the `tmux` or `tmux-256color` terminfo entries. You will need to install them or use `screen` or `screen-256color` instead.

**Comment by cinerea0** [comment]
Changing to `screen-256color` fixed it. I'll have to find a way to edit the `tmux` package in my distro to include the terminfo file. Thanks!
