### ISSUE TITLE
Option equivalent to tmux -u in latest version?

### ISSUE THREAD

**Issue by Kabouik** [tmux/tmux#2251]
### Issue description

I built tmux from git for SailfishOS and it seems to work mostly fine, but somehow it only supports utf-8 characters when I run it with the `-u` argument. I tried `set utf8 on` in `tmux.conf`, but the option is unknown. I couldn't find the right option in the man page

### Required information

Please provide the following information:

* tmux next-3.2
* Sailfish OS
* xterm-color

**Comment by Kabouik** [comment]
I got an answer on #IRC. There is no such option.

**Comment by nicm** [comment]
Make sure LANG, LC_ALL or LC_CTYPE are set to an appropriate UTF-8 locale.
