### ISSUE TITLE
ANSI Escape sequences filtered, any reason for that?

### ISSUE THREAD

**Issue by zokrezyl** [tmux/tmux#2254]
### Issue description

Tmux is filtering unknown escape sequences and that is making it unusable for the following purpose:

I was intending to use tmux on top of a new opengl terminal https://github.com/zokrezyl/asciterm . Asciterm is using libvterm for rendering text, but also is randering OpenGL shaders received as ANSI escape sequences.

My question is:
* is there any trick to disable this filtering, and let tmux pass them to the underlying terminal or
* would a patch that modifies the behavior be accepted 

### Required information
platform: Linux x86_64
tmux: 3.0a

**Comment by nicm** [comment]
You can use the DCS passthrough sequence to pass stuff, for example:
~~~~
printf "\033Ptmux;abcdef\033\\"
~~~~
You need to double any `\033` in the sequence you want to pass.

**Comment by zokrezyl** [comment]
Thanks for the quick answer. So the idea is in case environment variable TERM=tmux is defined, to send DCS pass through. Will test it and report back.

**Comment by nicm** [comment]
Better to check for `TMUX` than `TERM`.

**Comment by zokrezyl** [comment]
Thanks for the advice. Can confirm the DSC pass through worked. Though I just bumped in other limitations I did not think about in my current design.
