### ISSUE TITLE
Pasting in neovim causes tmux to crash

### ISSUE THREAD

**Issue by dewijones92** [tmux/tmux#2255]
commit 191a836560f1b1996c4976eb496b27a6d428ba21
* tmux version (`tmux -V`):
tmux next-3.2

* Platform (`uname -sp`)
Linux unknown

uname -a
Linux DEWILAPTOP 5.6.2-arch1-1-macbook #1 SMP PREEMPT Tue Apr 7 09:15:07 BST 2020 x86_64 GNU/Linux

* $TERM inside and outside of tmux (`echo $TERM`).
inside: screen
outside: alacritty

Pasting the following in to neovim (NVIM v0.4.3) crashes tmux
`location /websocket/ {

    proxy_pass ​http://backend_host;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 86400;

}`

[tmux-client-559399.log](https://github.com/tmux/tmux/files/4715850/tmux-client-559399.log)
[tmux-out-559401.log](https://github.com/tmux/tmux/files/4715851/tmux-out-559401.log)
[tmux-server-559401.log](https://github.com/tmux/tmux/files/4715852/tmux-server-559401.log)

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/4715955/x.diff.txt)

**Comment by dewijones92** [comment]
@nicm 
yes thanks.
What is the best way forward? Will that patch be applied upstream or?

**Comment by dewijones92** [comment]
@nicm 
also if you could please explain the thought process behind that patch? :D

**Comment by nicm** [comment]
UTF-8 codepoints with width 0 are not allowed but for keys we don't want to fatal(), instead we want to return an error so they are processed as separate keys.

Applied the fix to OpenBSD now, it will be in GitHub later. Thanks!
