### ISSUE TITLE
'output' hook not working

### ISSUE THREAD

**Issue by noscript** [tmux/tmux#2259]
### Issue description

There is `%output` control mode notification which should also act as a hook. But `show-hooks -g` does not list it, assigning a command also fails:
```
$ tmux set-hook -g output 'display "output hook"'
invalid option: output
```

### Required information

* tmux version: 81ba6477

**Comment by nicm** [comment]
`%output` is not a hook and it would be too slow to make it so. You will need to use control mode if you want `%output`.

**Comment by noscript** [comment]
Ok, thanks.
