### ISSUE TITLE
Add support for configurable symbols for window_flags

### ISSUE THREAD

**Issue by sanscore** [tmux/tmux#226]
## My current problem.
I'd like to change the character representation for various window_flags. However, as far as I am aware, there doesn't exist a way to configure the symbols used for flags. One can use `#{?window_*_flag,yes,no}`, but this a particularly nasty and complicated way to handle these cases.

I can do something simple like the following which will allow me to insert a space when there are no `window_flags` present. `setw -g window-status-format '#I#{?window_flags,#{window_flags}, }#W'`

If I wanted to do something more complicated, such as changing bell from '!' to '🔔' and to change zoomed from 'Z' to '⦾', then things would get more complicated beacuse I could no longer use the `window_flags` variable. Instead I would have to list out each possible flag like as so. `setw -g window-status-format '#I#{?window_active,*,}#{?window_bell_flag,🔔,}#{?window_zoomed_flag,⦾,}#{...etc...}#W'`

## Status Quo
Currently, in tmux 2.1, there is a set of various indicators that are associated with the window_flags variable. According 'Table 4' of the manpage, they are:

```
Symbol	Meaning	 	 	 
*	Denotes the current window.	 	 	 
-	Marks the last window (previously selected).	 	 	 
#	Window is monitored and activity has been detected.	 	 	 
!	A bell has occurred in the window.	 	 	 
~	The window has been silent for the monitor-silence interval.	 	 	 
Z	The window's active pane is zoomed.
```

## Proposal

I am proposing that the following settings are added to tmux which will allow users to easily customize the flag presentation. Borrowing from the existing `window_*_flag` variables (including window_active), a session `window_*_symbol` options should be created. Then the user can use a command like `set -g window_bell_symbol '🔔'` or whichever character makes sense to them.

In addition to the existing flags, I'd like there to be a *default* or *fallback* symbol so that it is easy to configure the presentation in the absence of a window flag.

Here are the proposed settings with their default values
```
window_default_symbol ''
window_active_symbol '*'
window_activity_symbol '#' 	 	 	 	 
window_bell_symbol '!'
window_last_symbol '-'
window_silence_symbol '~'
window_zoomed_symbol 'Z'
```

**Comment by nicm** [comment]
I really see a need for this, you can do it with the format flags, and certainly not seven new options.

**Comment by sanscore** [comment]
> I really see a need for this, you can do it with the format flags, and certainly not seven new options.

I'm assuming you meant "I **don't** really see a need for this,.." (correct?) because the statement doesn't make sense without it.

I realize that one can use format_flags which is why I gave examples on how to do it. The problem with that is that if you want to customize just one, then you have to do them all; even if you want to keep the defaults.

So, if I wanted to keep everything the same except the bell symbol, I would end up with this:
```
setw -g window-status-format '#I#{?window_flags,, }#{?window_active,*,}#{?window_activity_flag,#,}#{?window_bell_flag,XYZ,}#{?window_last_flag,-,}#{?window_silence_flag,~,}#{?window_zoomed_flag,Z,}#W'
```

If there's a better way, please, demonstrate.



As for adding an X number of options, it could just as easily be done with one option.

String example w/ 'Open Box' to demonstrate whitespace as the fallback/no-flag.
```
window_flag_symobls '*#!-~Z␣'
```

However, one of the great things about tmux is the readability and ease of configuration, that seems to go into the non-intuitive configuration territory.

**Comment by nicm** [comment]
I'd probably accept a patch to add one option.

**Comment by sanscore** [comment]
Cool, thanks. I'll look into it.

On Thu, Dec 3, 2015 at 10:13 AM, Nicholas Marriott <notifications@github.com
> wrote:

> I'd probably accept a patch to add one option.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tmux/tmux/issues/226#issuecomment-161736036>.
>



-- 
-grant welch
-gwelch925@gmail.com
