### ISSUE TITLE
Crash when copy emoji from Windows 10 to vim in tmux of WSL

### ISSUE THREAD

**Issue by DovahYol** [tmux/tmux#2263]
### Issue description
It crashes when I copy ✔️ to vim within it, with error `server exited unexpectedly` being printed.
I can copy ✔️ to vim that's not in tmux. 
I copy using Ctrl-Shift-V, which is a Windows Terminal shortcut for paste.

### Additional information

WSL
Ubuntu 16.04.6 LTS
Windows Terminal
Vim 7.4

### Required information

* tmux version (`tmux -V`).
tmux next-3.2
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
xterm-256color
screen
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-27833.log](https://github.com/tmux/tmux/files/4750431/tmux-client-27833.log)
[tmux-out-27835.log](https://github.com/tmux/tmux/files/4750433/tmux-out-27835.log)
[tmux-server-27835.log](https://github.com/tmux/tmux/files/4750434/tmux-server-27835.log)

**Comment by nicm** [comment]
tmux in this log did not crash. Are you sure you reproduced when you were creating this log?

**Comment by DovahYol** [comment]
> tmux in this log did not crash. Are you sure you reproduced when you were creating this log?

OK, I've reproduced and updated logs again.

**Comment by nicm** [comment]
Can you do this please:
~~~~
tmux -f/dev/null -Ltest -vv new
~~~~
Then:
~~~~
printf "\342\234\224\357\270\217"
exit
~~~~
Then show me the tmux-server*.log file. It may or may not crash, show me the log file anyway.

**Comment by DovahYol** [comment]
Not crashed and printed ✔️
[tmux-client-29326.log](https://github.com/tmux/tmux/files/4751071/tmux-client-29326.log)
[tmux-out-29328.log](https://github.com/tmux/tmux/files/4751072/tmux-out-29328.log)
[tmux-server-29328.log](https://github.com/tmux/tmux/files/4751073/tmux-server-29328.log)

**Comment by nicm** [comment]
Are you sure your tmux is up to date? Do you have 2a4d4bda2b94602e9f999ff0b59efa92613f75a9?

**Comment by DovahYol** [comment]
I installed it via apt, I'll try to build and install from the latest source.

**Comment by DovahYol** [comment]
I built and installed from the latest source, and I can still reproduce the error.
[tmux-out-2650.log](https://github.com/tmux/tmux/files/4751599/tmux-out-2650.log)
[tmux-server-2650.log](https://github.com/tmux/tmux/files/4751601/tmux-server-2650.log)
[tmux-client-2648.log](https://github.com/tmux/tmux/files/4751603/tmux-client-2648.log)

**Comment by nicm** [comment]
Can you make this change in utf8.c and rebuild then reproduce and show me the log:
~~~~
--- utf8.c      9 Jun 2020 08:34:33 -0000       1.54
+++ utf8.c      9 Jun 2020 10:36:14 -0000
@@ -130,7 +130,7 @@ utf8_from_data(const struct utf8_data *u
        u_int   index;

        if (ud->width > 2)
-               fatalx("invalid UTF-8 width");
+               fatalx("invalid UTF-8 width: %u", ud->width);

        if (ud->size > UTF8_SIZE)
                goto fail;

**Comment by DovahYol** [comment]
OK

[tmux-client-6586.log](https://github.com/tmux/tmux/files/4751665/tmux-client-6586.log)
[tmux-out-6588.log](https://github.com/tmux/tmux/files/4751666/tmux-out-6588.log)
[tmux-server-6588.log](https://github.com/tmux/tmux/files/4751667/tmux-server-6588.log)

**Comment by nicm** [comment]
This log does not have the new logging, are you sure you are running the binary you built with the change?

**Comment by DovahYol** [comment]
I found that I forgot to `make install` to `/usr/local/bin/tmux`, which was still the executable I built at 6/1/2020. After I installed the latest, the problem was gone. 

I'm sorry for that I reported a fixed bug : (.

And you can add `sudo make install`  to `README.md`.
```
git clone https://github.com/tmux/tmux.git
cd tmux
sh autogen.sh
./configure && make
sudo make install
```

**Comment by nicm** [comment]
OK great stuff, thanks.
