### ISSUE TITLE
Is it possible to highlight/ring bell of "current" window?

### ISSUE THREAD

**Issue by hisnawi** [tmux/tmux#2264]
I am on tmux 3.1 and trying to figure out of there is any way to ring the bell of the current window with:
echo -e "\a" 
And keep the window name postfixed with ! until cleared.

I am noticing that you could only do that with an inactive window.

The reason I am trying to achieve this is that I have nested remote tmux session that I want to be able to notify the outer session (local tmux) and the bell (window name change) is the only way to do that, but I also like to be able to do that while the remote session is visible.

**Comment by nicm** [comment]
No, alerts are not shown for the current window.

You could set some user option on the `alert-bell` hook and use that to change the colour or mark the window in the status line.
