### ISSUE TITLE
status bar is not showing my window-status-current-format and window-status-format configuration

### ISSUE THREAD

**Issue by AradAlon** [tmux/tmux#2265]
After adding to much info to the right side of my status bar I decided to use `status-format[]`.
The top line is for all the info while the bottom one is for widows management.

Now, the two lines status bar have all of my custom info except to the widows section 
![Screenshot from 2020-06-09 11-46-19](https://user-images.githubusercontent.com/30626852/84126708-f13d9900-aa46-11ea-84dc-bf94c9e65814.png)

What am I missing?

 ```
 $ uname -sp && tmux -V && echo $TERM
 
Linux x86_64
tmux next-3.2
screen-256color
 ```

[tmux-client-3007.log](https://github.com/tmux/tmux/files/4750891/tmux-client-3007.log)
[tmux-out-3009.log](https://github.com/tmux/tmux/files/4750894/tmux-out-3009.log)
[tmux-server-3009.log](https://github.com/tmux/tmux/files/4750896/tmux-server-3009.log)

part of my tmux.conf - the status bar section:
```
# Customize the status
#set -g status "on"
set -g status 2
set -g status-fg colour82
set -g status-bg colour0

# Refresh status line every 1 seconds
set -g status-interval 1

# Window indexing should start at 1 and not skip index
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows "on" 

# Length of tmux status line
set -g status-left-length 30
set -g status-right-length 150

# Current window title colours
set-window-option -g window-status-current-style bg=colour82,fg=colour0

# Current window
set-window-option -g window-status-current-format "\
#[fg=colour0, bg=colour2]\
#[fg=colour0, bg=colour2] #I \
#[fg=colour0, bg=colour2] #W \
#[fg=colour2, bg=colour0]"

# other windows
set-window-option -g window-status-format "\
#[fg=colour0,bg=colour239,noitalics]\
#[fg=colour223,bg=colour239] #I \
#[fg=colour223, bg=colour239] #W \
#[fg=colour239, bg=colour0]"

#set upper right status line
set -g status-format[0] '\
#[align=right]\
#[fg=colour82, bg=colour0]\
#[fg=colour82] #(~/.tmux_scripts/network.sh) \
#[fg=colour82, bg=colour0]\
#[fg=colour190] #(~/.tmux_scripts/tunnel.sh) \
#[fg=colour82,bg=colour0]\
#[fg=colour82] #(~/.tmux_scripts/cpu.sh)\
#[fg=colour82, bg=colour0]\
#[fg=colour82] #(~/.tmux_scripts/ram.sh) \
#[fg=colour82, bg=colour0]\
#[fg=colour82, bg=colour0] %d/%m/%y \
#[fg=colour82, bg=colour0] %T '

#set lower left status line
set -g status-format[1] "\
#[align=left]\
#[fg=colour7, bg=colour241]#{?client_prefix,#[bg=colour6],} ❐ #S \
#[fg=colour241, bg=colour0]#{?client_prefix,#[fg=colour6],}\
#[fg=colour2 bold] ♥ #(~/.tmux_scripts/battery.sh)#{?window_zoomed_flag, 🔍,} "

# Message info colour
set-option -g message-style bg=colour1,fg=colour255

```
Thanks!

**Comment by nicm** [comment]
You didn't put a window list in `status-format[0]`?

**Comment by AradAlon** [comment]
why status-format[0] and not status-format[1]?
I added `set -g status-justify left`
and `#[line=on align#{status-justify}]` to the end of status-format[1]

when I reopen Tmux I get - 
```
home/user/.tmux.conf:85: ambiguous option: status-format[0]#[align=right]#[fg=colour82, bg=colour0]#[fg=colour82] <'~/.tmux_scripts/network.sh' not ready> #[fg=colour82, bg=colour0]#[fg=colour190][0/0]
.tmux_scripts/tunnel.sh' not ready> #[fg=colour82,bg=colour0]#[fg=colour82] <'~/.tmux_scripts/cpu.sh' not ready>#[fg=colour82, bg=colour0]#[fg=colour82] <'~/.tmux_scripts/ram.sh' not ready> #[fg=colour8
2, bg=colour0]#[fg=colour82, bg=colour0] %d/%m/%y #[fg=colour82, bg=colour0] %T
```

Every thing is messed up now (although I do see the window list now :smile:)
![Screenshot from 2020-06-09 14-36-40](https://user-images.githubusercontent.com/30626852/84143156-bfd0c780-aa5e-11ea-99de-4ea0767443cd.png)

I want the window list after the 100% in the bottom line.

**Comment by nicm** [comment]
Whichever one you like. You are missing an `=` after `align`.

**Comment by nicm** [comment]
For the window list you need a #{W: section like in the default, I'd start with something simpler perhaps and build it up.

**Comment by AradAlon** [comment]
Ok,
it is starting to look as I imagine, only need to do some colour adjustment to the window list

Thanks!
