### ISSUE TITLE
[Format request] Detect if a search is currently active

### ISSUE THREAD

**Issue by sgleizes** [tmux/tmux#2268]
I've been playing around with the current tmux 3.2 (built ~2 weeks ago) and its awesome features. I have a request about the following change: `Also a change so that if a copy key is pressed with no selection, the current match (if any) is copied.`

This is great, but I was previously using the following binding:
```
# Copy the current selection to a new buffer or start one if none is active.
bind -T copy-mode 'Space' {
  if -F '#{selection_active}' {
    send -X copy-pipe
  } {
    send -X begin-selection
  }
}
```

The issue with this is that when entering search mode, the current match is technically not considered a "selection", so with this snippet pressing space will `begin-selection` instead of copying the current match.

So, I was looking for a way to detect if a search is currently active (e.g. a `search_active` format), but I could not find a way to achieve this. Such a format could probably have other interesting applications and could be a starting point for other search-related formats, e.g. `search_match` and friends.

**Comment by nicm** [comment]
Yes, try this please: [tmux-search-formats.diff.txt](https://github.com/tmux/tmux/files/4765221/tmux-search-formats.diff.txt)

**Comment by sgleizes** [comment]
Awesome, the patch works perfectly.

However the latest version broke other parts of my configuration. It seems to be related to the changes that were made to processing `{}` in configuration files.

I was previously using this feature to embed small shell snippets into my tmux configuration, for instance the following (simplified) snippet:
```
run {
  for cmd in "$TMUX_COMMAND_DIR"/*; do
    "$cmd"
  done
}
```
Becomes: `for cmd in <home>/.config/tmux/command/* ; do ; '' ; done`
Which doesn't work due to parameter expansion and the removed newlines.

I understand the benefits of these changes to `{}` though, so it seems I should go back to using single quotes, however newlines are also removed so the following doesn't work either:
run '
  for cmd in "$TMUX_COMMAND_DIR"/*; do
    "$cmd"
  done
'
Becomes: `for cmd in "$TMUX_COMMAND_DIR"/*; do"$cmd"done`, which the shell fails to parse.

I can still make it work by removing the newlines, but shouldn't the strings be left intact (at least in single quotes) if there is no explicit line continuation, like it used to be? I fear this change might break a lot of configuration files.
That's an entirely different topic though, do you prefer I open a separate issue?

**Comment by nicm** [comment]
If you use `\` at the end of lines you don't want to be joined with `;` it should work.

**Comment by nicm** [comment]
We could perhaps be clever and skip the `;` if the following item is not a valid tmux command since there should be few or no overlap between tmux and shell commands.

**Comment by sgleizes** [comment]
Using `\` at the end of lines inside `{}` indeeds prevents lines from being joined with `;`, but `$cmd` is still expanded during command parsing so the snippet also fails in this case. Using `\$cmd` prevents the expansion, but `\$` is included literally in the string instead of just `$`.

**Comment by sgleizes** [comment]
Then I also have a case like this:
```
set -g @resurrect-hook-post-restore-all {
  ...
  { sleep 1; tmux set -g monitor-activity on; } &
}
```
Which now results in a syntax error from tmux (also without the `&`). This might be another example of where tmux and shell feature overlap.

**Comment by nicm** [comment]
Stuff on {} really needs to be valid tmux commands syntax now, for some shell stuff you will have to use single quotes. Single quotes will strip leading spaces after a newline so you will need ;s in the right place for the shell.

**Comment by nicm** [comment]
I would like it if `{}` was able to handle shell but there are big benefits to using the same parser as tmux commands. I wonder if we could make a way to do something like:
~~~~
{ :literal:
...
}
~~~~
Or `:shell:` or something. I don't really want to have to make it understand shell syntax though and there are always going to be problems with finding the final `}`...

I'll have a look at some point but I think just using `'` is probably better.

**Comment by sgleizes** [comment]
I agree, it's more coherent to have stuff in `{}` behave like a tmux configuration scope rather than an alternative way to single-quote like it used to be. After all, the tmux configuration is not the place for extensive shell scripting, and having to quote these parts makes it much more explicit that this is shell code and not tmux configuration.

For reference, this is what I've ended up doing:
```
run '
  # Comments can still be included and will be removed by tmux.
  for cmd in "$TMUX_COMMAND_DIR"/*; do \
    "$cmd";
  done
'
```
Note the `\` which is necessary to avoid stripping leading spaces.

**Comment by sgleizes** [comment]
Back to the search formats, the patch perfectly addresses my initial request so feel free to close this once integrated into master.

**Comment by nicm** [comment]
It should be there now. Thanks!

**Comment by nicm** [comment]
Can you try this please: [tmux-literal.diff.txt](https://github.com/tmux/tmux/files/4769087/tmux-literal.diff.txt)

This allows:
~~~~
bind x run { :literal:
  { sleep 1; tmux set -g monitor-activity on; } &
}
~~~~
There are a still a few caveats:

- `{` and `}` must match up. Also no doubt I have forgotten to include a few special characters.
- multiple spaces are compressed to a single space.

No doubt I have also missed a few special characters or whatnot that will need to be included.

I don't much like `:literal:` because it it isn't really literal, also I might make it `%literal%` since `%` is already special for `%if` and there is no point in making `:` special as well...

**Comment by nicm** [comment]
Hmm it will also insert spaces around ; and { and }. Not sure I can do much about that, it can either always insert them or always remove them but by the time the parser sees it the lexer has already removed them.

**Comment by nicm** [comment]
Maybe I'll make it %shell% and explicitly say it is for shell scripts...

**Comment by nicm** [comment]
OK here is an updated diff with a few tweaks and change to `%shell%` instead of `:literal:`: [tmux-literal2.diff.txt](https://github.com/tmux/tmux/files/4769131/tmux-literal2.diff.txt)
~~~~
bind x run { %shell%
        { sleep 1;
                tmux set -g monitor-activity on;
                { foo }
        } &
}

**Comment by nicm** [comment]
Stuff in ' and " are probably going to be an issue...

**Comment by nicm** [comment]
Yeah never mind, maybe this is impossible to do. When the parser gets a token there isn't really a way for it to know whether it was surrounded by ' or "...

**Comment by nicm** [comment]
Well it could know but you would need to escape $ and \ and other stuff that tmux expands, but that's no different from other tools like make I guess.

**Comment by nicm** [comment]
This should fix quoting too, please test: [tmux-literal3.diff.txt](https://github.com/tmux/tmux/files/4769287/tmux-literal3.diff.txt)
