### ISSUE TITLE
Unable to bind C-DoubleClick1Pane

### ISSUE THREAD

**Issue by sgleizes** [tmux/tmux#2269]
### Issue description

I've been trying to bind `C-DoubleClick` as I've seen a few examples doing this.

I'm using the following config snippet:
```
# Zoom/unzoom the selected pane.
bind -T root 'C-DoubleClick1Pane' resize-pane -Zt=
```

Unfortunately, it seems that tmux picks up a regular `DoubleClick1Pane` input sequence when I try this out. My understanding is that it's probably related to my terminal emulator (`konsole`) and not really related to tmux itself, but since it's related to tmux usage I thought I could ask for guidance here.

I've tried to look for ways to configure my `konsole` to send the right input sequences, but although the keyboard sequences can be greatly configured, it does not seem to offer any configuration regarding mouse inputs.

Any ideas as to what is causing this and/or how to address it?

### Required information

* tmux next-3.2 (built ~2 weeks ago)
* Arch Linux
* tmux-256color & xterm-256color
* `konsole` terminal emulator

**Comment by nicm** [comment]
Probably your terminal doesn't support it. 

tmux logs?

Does it work in any other terminals?

**Comment by sgleizes** [comment]
Tmux logs show a DoubleClick1Pane event picked up, confirming that it's really a terminal emulator issue. And it does work in `termite`.

I guess there is no way to workaround this limitation then. I will close this, sorry for the inconvenience.
