### ISSUE TITLE
Issues with bell while detached

### ISSUE THREAD

**Issue by tobbez** [tmux/tmux#227]
I found this after upgrading from 1.9 to 2.1. I have not checked if it happens in 2.0.

If you get a bell in the current window when the session is attached, then re-attach, switch to a different window and trigger a bell, then tmux will show a bell indicator for the previous window.

To reproduce:
Start a new tmux session: `tmux`
Run the following command `sleep 3; echo -e "\a"`
Detach the session before the sleep command has completed (`C-b d`).
Re-attach the session after the sleep command has completed: `tmux attach`.
Create a new window (`C-b c`).
Run `echo -e "\a"`
You now have a bell indicator for window 0.

In addition, you no longer get a bell when attaching if a bell was sent while detached (you used to). Whether the bell was in the current window or not is not a factor.

**Comment by nicm** [comment]
Does this happen in git master?

**Comment by ThomasAdam** [comment]
Does this fix it?

```
diff --git a/alerts.c b/alerts.c
index 55e7044..e5a6b33 100644
--- a/alerts.c
+++ b/alerts.c
@@ -145,8 +145,10 @@ alerts_check_bell(struct session *s, struct winlink *wl)

        if (!(w->flags & WINDOW_BELL) || wl->flags & WINLINK_BELL)
                return (0);
-       if (s->curw != wl || s->flags & SESSION_UNATTACHED)
+       if (s->curw != wl || s->flags & SESSION_UNATTACHED) {
                wl->flags |= WINLINK_BELL;
+               w->flags &= ~WINDOW_BELL;
+       }
        if (s->flags & SESSION_UNATTACHED)
                return (0);
        if (s->curw->window == w)
```

**Comment by tobbez** [comment]
Yes, this happens in the git master.

The patch fixes the first issue, however it breaks something else - if you get a bell in a non-current window while detached, you don't get a bell indicator (at all).

The bell on re-attach if a bell occurred while detached is also still gone.

Also, please be careful when copying and pasting patches. The one in your comment has tabs replaced with spaces, so it doesn't apply cleanly.

**Comment by ThomasAdam** [comment]
That's because if the session is unattached we ignore the check.  Try:

```
diff --git a/alerts.c b/alerts.c
index 55e7044..dd11788 100644
--- a/alerts.c
+++ b/alerts.c
@@ -145,10 +145,10 @@ alerts_check_bell(struct session *s, struct winlink *wl)

        if (!(w->flags & WINDOW_BELL) || wl->flags & WINLINK_BELL)
                return (0);
-       if (s->curw != wl || s->flags & SESSION_UNATTACHED)
+       if (s->curw != wl || s->flags & SESSION_UNATTACHED) {
                wl->flags |= WINLINK_BELL;
-       if (s->flags & SESSION_UNATTACHED)
-               return (0);
+               w->flags &= ~WINDOW_BELL;
+       }
        if (s->curw->window == w)
                w->flags &= ~WINDOW_BELL;
```

As for tabs versus spaces, I don't care at all.  This isn't being submitted as-is, it's just for you to test it.

**Comment by tobbez** [comment]
Still doesn't work. In addition, if you get a bell in a background window when attached, bells are completely broken in that window after that - if you switch to it and trigger a bell, nothing happens at all. You also don't get bell indicators at all.

Regarding tabs versus spaces: obviously. The point was that it's easier to test when you can apply the patch directly, rather than editing the code to do it manually.

**Comment by ThomasAdam** [comment]
Hmm.  Well, this works for me.

**Comment by tobbez** [comment]
Sorry, guess I should have worked against master and not 2.1.

Running against master I still get the following issues with the latest patch:
* You never get a bell indicator in the status bar.
* If you're attached, you can hear bells from background windows, but (as per the previous point) you don't get indicators on the status bar.
* You still don't hear a bell when re-attaching if one occurred while detached.

**Comment by ThomasAdam** [comment]
On Wed, Dec 02, 2015 at 03:51:37AM -0800, Torbjörn Lönnemark wrote:
> Sorry, guess I should have worked against master and not 2.1.
> 
> Running against master I still get the following issues with the latest patch:
>
> * You never get a bell indicator in the status bar.
> * If you're attached, you can hear bells from background windows, but (as per the previous point) you don't get indicators on the status bar.
> * You still don't hear a bell when re-attaching if one occurred while detached.

If you try this as:

`/path/to/tmux/tmux -Lx -f/dev/null`

Does that help?  I get the opposite to what you're claiming with the patch
provided which is odd, given your observations.

-- Thomas Adam

**Comment by tobbez** [comment]
Nope, that gives the same behaviour.

**Comment by ThomasAdam** [comment]
Then I can't help you.  All I can say is that the patch as given, addresses your points for me, and clearly shows them without (i.e., running HEAD on master).

Are you *sure* there's nothing else you've not told me which could affect this?

**Comment by tobbez** [comment]
I'm fairly certain there's nothing else that should be affecting this.

Now I've even tried it on two different machines with different distributions (Ubuntu 14.04 and Gentoo). I also tried with two different terminal emulators on both (gnome-terminal and PuTTY). I'm still getting the same results.

**Comment by nicm** [comment]
You will not get a bell when detached, or when you reattach after a bell.

Thomas' patch fixes your original issue for me, and I still see a bell if I generate one when attached.

**Comment by nicm** [comment]
I would be nice though if bells when detached appeared in the status line after reattach, did that used to work? That is a separate problem though.

**Comment by ThomasAdam** [comment]
@nicm, I don't believe bells used to work like that.  I could be wrong though.

**Comment by tobbez** [comment]
I found the source of confusion - I misspelled `w->flags` as `wl->flags` when manually applying the patch.

@ThomasAdam, bells used to work that way, and as far as I can tell they still do with the latest patch in this issue.

When comparing 1.9a and the git HEAD with the patch applied now, the only change in behaviour is that tmux no longer sends an audible bell when re-attaching, if one was sent in the current window while detached.

**Comment by ThomasAdam** [comment]
OK, I'll take a look. Please watch this space.

**Comment by ThomasAdam** [comment]
Please try this:

https://github.com/ThomasAdam/tmux/commit/f997f595cca5d843f06e7450f05def1128899fc3.diff

It now skips updating sessions when they're detached, and upon reattaching will sound the bell (if applicable), etc.

**Comment by tobbez** [comment]
That works as far as I can tell.

It does send an audible bell when attaching if one happened in a background window while detached, while it previously didn't. I guess that's fine though.

**Comment by ThomasAdam** [comment]
Yes, that's a good and intentional change, when making this deferred whilst sessions are detached.

@nicm, do you want me to send this to the ML, or are you happy to pick it up here?

**Comment by ThomasAdam** [comment]
Sent to the ML.
