### ISSUE TITLE
Japanese garbled in tmux.

### ISSUE THREAD

**Issue by ofofofofo** [tmux/tmux#2272]
### Issue description
`日本語`garbled, shown as `______`.
only happend when sshed from windows.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
```
> tmux -V
tmux 3.0a
```
* Platform (`uname -sp`).
```
> uname -sp
Darwin i386
```
* $TERM inside and outside of tmux (`echo $TERM`).
#### outside
```
> echo $TERM
xterm-256color
```
#### inside
```
> echo $TERM
screen
```
* Logs from tmux (`tmux kill-server; tmux -vv new`).
I think the relevant part is below.

![image](https://user-images.githubusercontent.com/46468086/84722170-6e27c000-afbd-11ea-8bc8-5c82cf4c5462.png)

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-utf-8
