### ISSUE TITLE
Tmux conf

### ISSUE THREAD

**Issue by nicinu111** [tmux/tmux#2273]
why every time i get a newer version of Tmux the configs no longer works and is really annoying to fix them every time. why not let them the same for god sake is the hotkeys i speak about. this no longer works again:

# Use Alt-arrow keys to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

i had to reinstall my linux and it come with the latest version so this really annoys my a lot, i have no idea what version was before since i dint check this is my bad. any help to fix this without needing to read all of your patch notes every time??

**Comment by nicm** [comment]
Are we meant to guess what version you are using?

**Comment by nicinu111** [comment]
what is the latest?? 3.1b

**Comment by nicm** [comment]
Is that what you are running? What does `tmux -V` show?

**Comment by nicinu111** [comment]
i just told you tmux 3.1b above but werever

**Comment by nicm** [comment]
No you didn't, you asked what the latest was.

None of the commands you give have changed for years and they should still work with 3.1b.

What does this show inside tmux?
~~~~
tmux lsk -Troot M-Left
~~~~

And if you run `cat` outside tmux and press `M-Left` what do you see?

What if you run `cat` inside tmux and press `M-Left`?

**Comment by nicinu111** [comment]
tmux lsk -Troot M-Left is giving my 
bind-key -T root -M-Left select-pane -L
even FK selecting with the mouse the text is becoming deselect at the end. WORST VERSION EVEN 3.1BAD
ouside tmux
cat M-left No such file direc....
inside tmux
cat M-left No such file direc....

**Comment by krader1961** [comment]
> WORST VERSION EVEN 3.1BAD

Why did you run `cat M-left`? You shouldn't open issues when drunk and angry. This is the worst problem report I've ever seen.

**Comment by nicm** [comment]
This is just a waste of time.
