### ISSUE TITLE
New appimage version for 3.1 releases

### ISSUE THREAD

**Issue by leachim** [tmux/tmux#2275]
Hey, really appreciate your work. Tmux has become one of my goto tools for developing. Would it be possible to continue to provide newer releases of tmux in the appimage format? This would be super helpful for installing this on older servers where I otherwise have to install all the tooling manually in order to build it there. 

I saw there is an older thread on this (#1172), but looks like newer releases have not been updated?
Can you comment on this @nelsonenzo?

**Comment by nicm** [comment]
I suggest you move this issue to https://github.com/nelsonenzo/tmux-appimage, if there are new binaries let me know and I can attach them to the release.

**Comment by nelsonenzo** [comment]
Hello.  Sorry for being remiss, my github notifications were getting filtered incorrectly.
I have added appimage releases for 3.1a and 3.1b 
https://github.com/nelsonenzo/tmux-appimage/releases

**Comment by nicm** [comment]
Thanks I have added the 3.1b one to the release as well. I wouldn't encourage people to use 3.1a now so I will leave it.
