### ISSUE TITLE
Tmux 3.1 window/pane not redrawing on macOS and iTerm2

### ISSUE THREAD

**Issue by autonomic** [tmux/tmux#2276]
### Issue description

I upgraded tmux from 3.0a to 3.1b from Pkgsrc on my Mac (macOS 10.15.5). After performing this upgrade I noticed that the windows/panes would draw incorrectly and not refreshing after my computer was locked for a while or came out of sleep (see screenshots).

I have a Macbook Pro 13" (2020) that's connected to a 27" external 4K display. I have my iTerm2 window running on the 27" display. When my Mac is locked or goes to sleep, the display will go into power saving mode and the iTerm2 window will temporarily move to 13" retina display. When I wake my Mac from sleep or unlock it, the external display will power back on and iTerm2 will then move back from the 13" retina display to the 27" external display. It's at this time that tmux has issues drawing/refreshing and sections of the windows/panes are not drawing properly (garbled).

I thought it might be an issue with the Pkgsrc package that I installed so I decided to uninstall it and compile/install from source. I did this with 3.1b and noticed the same issue so I uninstalled and did the same with 3.0a. With version 3.0a I'm not seeing this issue and it's behaving as expected.

In the screenshots you'll see that a weechat window is all garbled and the second screenshot are two panes that have vi running which you'll notice are missing line numbers beyond 44.

<img width="1811" alt="tmux_refresh_issue_2" src="https://user-images.githubusercontent.com/13229225/85230501-83c62c80-b3a5-11ea-987d-be7b9d03859c.png">
<img width="1916" alt="tmux_refresh_issue_1" src="https://user-images.githubusercontent.com/13229225/85230504-86c11d00-b3a5-11ea-83f9-dd1f0fc60749.png">

I've attached the requested logs.

[tmux-client-96361.log](https://github.com/tmux/tmux/files/4809860/tmux-client-96361.log)
[tmux-out-96363.log](https://github.com/tmux/tmux/files/4809861/tmux-out-96363.log)
[tmux-server-96363.log](https://github.com/tmux/tmux/files/4809862/tmux-server-96363.log)

### Required information

Darwin i386
tmux 3.1b
tmux-256color

**Comment by nicm** [comment]
Does this still happen if you build from master?

**Comment by autonomic** [comment]
@nicm I built from master last night and it appears to be fine. It's just version 3.1b that has this issue.

Also, I forgot to mention in my original post that I had run the tests with my own tmux config and without it (`tmux -Ltest -f/dev/null new`) and both produced the same issue in 3.1b.

**Comment by nicm** [comment]
OK that's great, thanks.

**Comment by nicm** [comment]
This may have been fixed by 574a9e4b6c7a419b60668c30916327aa7e65d2c8 or d919fa1ed0ea3b167ffc811abba26a2dbcd20631.
