### ISSUE TITLE
A way to detect control mode

### ISSUE THREAD

**Issue by akkartik** [tmux/tmux#2277]
In my configuration I often use `$TMUX` to check for whether a program is running inside `tmux`.

Recently, tmux added support for [control mode](https://github.com/tmux/tmux/wiki/Control-Mode). However, some configuration that used to make sense in tmux (e.g. sending keys to specific windows) no longer makes sense with the iTerm2 integration that uses control mode.

Is there some way to detect when a program is running inside a tmux session that is in control mode?

**Comment by nicm** [comment]
Control mode is per client not per session. You can look at the
client_control_mode format to see if a client is in control mode and look
at client_session to see which session is attached to it, although of
course the same session may be attached to multiple clients.

**Comment by akkartik** [comment]
Thank you!

**Comment by akkartik** [comment]
For any future readers, the command I ended up with is:

```
tmux display-message -p '#{client_control_mode}'
```

[Example in Vim.](https://github.com/akkartik/mu/commit/85eb81672548f8be71b6a51f3267afcd9f132489)

**Comment by paulirish** [comment]
The above snippet detects that it's running inside of Control Mode.

Before entering Control Mode is there any way to detect that a terminal client supports it? 

For example, the [Secure Shell chrome extension](https://chrome.google.com/webstore/detail/secure-shell-app/pnhechapfaindjhompbnflcldabbghjo?hl=en) just hangs without output after running `tmux -CC`. (I don't expect that client to ever support -C, fwiw) I'd like to write a script that invoked tmux with control mode but only if the user running it is using a supporting term client.
