### ISSUE TITLE
Unicode characters not appearing properly in tmux 3.0a

### ISSUE THREAD

**Issue by nitin-gyany** [tmux/tmux#2278]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). - 3.0a
* Platform (`uname -sp`). Ubuntu 20.04
* $TERM inside and outside of tmux (`echo $TERM`). outside - term-256color. inside - screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
tail tmux-client-9192.log 
1592826070.565363 sending message 106 to peer 0x5585e6e49bc0 (0 bytes)
1592826070.565386 cmd_pack_argv: argv[0]=new
1592826070.565406 sending message 200 to peer 0x5585e6e49bc0 (8 bytes)
1592826070.565424 client loop enter
1592826070.571540 peer 0x5585e6e49bc0 message 207
1592826070.571577 sending message 208 to peer 0x5585e6e49bc0 (0 bytes)
1592826083.080255 peer 0x5585e6e49bc0 message 203
1592826083.080330 sending message 205 to peer 0x5585e6e49bc0 (0 bytes)
1592826083.080768 peer 0x5585e6e49bc0 message 204
1592826083.080783 client loop exit

The unicode characters like powerline symbols are not shown inside tmux, while that are visible outside.

**Comment by nicm** [comment]
This is the client log, where is the server log?

**Comment by nitin-gyany** [comment]
I solved it by calling tmux with tmux -u
