### ISSUE TITLE
[help] run bind-key command after run tmux

### ISSUE THREAD

**Issue by roachsinai** [tmux/tmux#2282]
I'm using tmux-copycat which default use `M-h` to do hash serach, but I want to use `M-h` to select left pane.

I had make a issue about it https://github.com/tmux-plugins/tmux-copycat/issues/149.

As now didn't find a way to make it. I found there are some tmux hooks.

Which works is `after-split-window`, the setting is: `set-hook -g after-split-window 'bind-key -T prefix M-h select-pane -L'`

But above setting seems each time I split a window, tmux will run the setting `bind-key -T prefix M-h select-pane -L`. But what I want is run it only once create a session.

Now QUESTION for me is: Why `session-created` hook not work? Or is there a hook work for only run `bind-key` once?

**Comment by roachsinai** [comment]
I mean why `set-hook -g session-created 'bind-key -T prefix M-h select-pane -L'` can not cover the setting `M-h` by plugin `tmux-copycat`?

Thanks in advanced! :)

**Comment by nicm** [comment]
Why don't you just change the key binding to what you want in .tmux.conf after tmux-copycat has changed it?

**Comment by roachsinai** [comment]
> Why don't you just change the key binding to what you want in .tmux.conf after tmux-copycat has changed it?

I tried, I have paste `bind-key -T prefix M-h select-pane -L` to the end of .tmux.conf, but `tmux list-keys` still shows `M-h` used by `copycat` plugin.

**Comment by nicm** [comment]
You could try something like:

~~~~
run 'sleep 2; tmux bind-key ...'
~~~~

Although I don't know why session-created doesn't work. Is the hook shown in `show-hooks` after you start tmux?

**Comment by roachsinai** [comment]
No, it didn't! But show copycat `M-h` option.

and you mean I add `run 'sleep 2; tmux bind-key ...'` to .tmux.conf?

**Comment by roachsinai** [comment]
Add `run 'sleep 2; tmux bind-key ...'` to the end of .tmux.conf not work, either. lol.

**Comment by roachsinai** [comment]
minimal .tmux.conf

```
set -gu prefix2
unbind C-\\
unbind C-b
set -g prefix C-\\
bind C-\\ send-prefix

bind-key -T prefix v split-window -h
bind-key -T prefix q kill-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-copycat'
run -b '~/.tmux/plugins/tpm/tpm'
set-hook -g session-created 'bind-key -T prefix M-h select-pane -L'
```

**Comment by nicm** [comment]
What tmux version?

**Comment by roachsinai** [comment]
`local/tmux 3.1_b-1` on Manjaro.

**Comment by nicm** [comment]
These `session-created` hook works for me, are you sure tmux-copycat isn't also using a hook to set its key bindings? What does `tmux show-hooks -g` show?

**Comment by roachsinai** [comment]
I got this:

![image](https://user-images.githubusercontent.com/9500049/85415861-614c3300-b5a0-11ea-8fe8-37f77d8d39ad.png)

**Comment by roachsinai** [comment]
no hook for `bind-key -T prefix M-h select-pane -L` but if I use `after-split-windwo` I got hook like below:

![image](https://user-images.githubusercontent.com/9500049/85416166-b8ea9e80-b5a0-11ea-9128-becc25823f6b.png)

**Comment by nicm** [comment]
Is there a session-created hook at all?

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/85417243-0582a980-b5a2-11ea-9a59-da5e5c4f8f85.png)

Yeah, check for the last one in above pic, session-created hook works, and that is the only session-created hook in the list.

**Comment by nicm** [comment]
So does it work or not work??

**Comment by roachsinai** [comment]
```
set-hook -g session-created 'bind-key -T prefix M-h select-pane -L'
set-hook -g session-created "bind-key -T prefix C-b splitw -h -p 40 -b -c '#{pane_current_path}' nnn -e"
```

First not work, second works.

**Comment by nicm** [comment]
OK well it must be changing the key binding after the session is created, so you will not be able to use this hook.

**Comment by roachsinai** [comment]
So it's the choice by plugin copycat?

**Comment by nicm** [comment]
You will need to ask the plugin developers how it works, I don't know, but if session-created works with a different key binding then it must be changing it after the session is created.

**Comment by roachsinai** [comment]
OK, thanks for all your help!
