### ISSUE TITLE
Disable mouse select by drag but keep mouse scroll - is it possible?

### ISSUE THREAD

**Issue by adams-family** [tmux/tmux#2283]
### Issue description

I'm running tmux via ssh on a linux (remote) machine from an iTerm2 on macOS.

I've configured `.tmux.conf` in order to get mouse wheel scrolling inside of tmux via the following:

```
set -g mouse on
```

I like the mouse wheel scolling but I don't like the automatic clipboard copy on mouse drag because it doesn't work. I am very satistfied with the built in copy to clipboard functionality of my iTerm2 and I would like to disable tmux's mouse drag handler.

Is it possible while keeping the mouse wheel scrolling?
### Required information

Please provide the following information:

* tmux version: `tmux 2.8`
* Platform: `Linux unknown`
* $TERM outside of tmux: `xterm-256color`
* $TERM inside of tmux: `screen-256color`
* Logs from tmux - tmux kill-server; tmux -vv new — just opens a new tmux window, which logs should I pull?

**Comment by nicm** [comment]
Copy on mouse drag definitely works.

You can stop tmux copying on the mouse by unbinding the `MouseDrag1Pane` key in the root table (`unbind -Troot MouseDrag1Pane`) and also the copy-mode and copy-mode-vi tables if you want it to be disabled in copy mode as well.

There is no way for tmux to tell iTerm2 that you want clicks but not drags, you can either have all or none (`mouse` on or off). However, if you hold down one of the modifiers (I forget which, maybe option?), then iTerm2 will bypass application mouse mode.
