### ISSUE TITLE
new-window -a/-b target window needs to exist

### ISSUE THREAD

**Issue by rfrancoise** [tmux/tmux#2284]
Debian users [are reporting](https://bugs.debian.org/944778) that in tmux versions before 3.0, this snippet used to work:

```
bind-key C new-window -n ROOT -a -t 50 sudo su -
```

The intent is apparently to have root shells in a group of windows with indices 50+. Starting with tmux 3.0, an error is now returned (`Couldn't get a window index`), indicating that the target window now needs to exist for the command to work the first time. Manually creating a window at index 50 to get past the first error works.

Tested with tmux 3.2-rc.

Thanks.

**Comment by nicm** [comment]
I think this will change it back:
~~~~
--- a/cmd-new-window.c
+++ b/cmd-new-window.c
@@ -68,10 +68,8 @@ cmd_new_window_exec(struct cmd *self, struct cmdq_item *item)
        before = args_has(args, 'b');
        if (args_has(args, 'a') || before) {
                idx = winlink_shuffle_up(s, wl, before);
-               if (idx == -1) {
-                       cmdq_error(item, "couldn't get a window index");
-                       return (CMD_RETURN_ERROR);
-               }
+               if (idx == -1)
+                       idx = target->idx;
        }

        memset(&sc, 0, sizeof sc);

**Comment by rfrancoise** [comment]
Works for me. Thanks!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
