### ISSUE TITLE
Can't pass data to set-buffer if data begins with -

### ISSUE THREAD

**Issue by Technik-J** [tmux/tmux#2285]
When passing data to `set-buffer` that starts with `-`, tmux tries to use it as an option for command and fails.

This:
```bash
tmux set-buffer "-some-data"
```
Will result in this:
```bash
tmux: unknown option -- s
usage: set-buffer [-a] [-b buffer-name] [-n new-buffer-name] data
```

Tested on tmux version 3.1b.

**Comment by nicm** [comment]
Either use `--` or pipe to load-buffer.

**Comment by nicm** [comment]
Of course -- works, don't put it in quotes, it is an argument on its own. This is the same for almost every Unix command.

**Comment by Technik-J** [comment]
Thank you. I didn't knew that.
Yes, it's works:
```bash
$ tmux set-buffer -- "-some-data"
$ tmux paste-buffer
-some-data
```
