### ISSUE TITLE
3.2-rc UTF key binding issue

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#2286]
I love the idea behind the 3.2 discussion, ticket, though I don't think this belongs there specifically.

Up to release 3.1, I've been using

bind-key -T root   0xXXXX   .... commands ...

to bind UTF codes to actions. 

As at the current tip of master, any keys bound to utf characters in this style are ACCEPTED (ie, no errors) but don't appear when using 'tmux list-keys', and are not acted on when the code is sent.

I use UTF codes which can't be typed as part of an automation suite,

Sample command; (in .tmux.conf)
```
bind-key    -T root         0x0173                   if-shell "\$HOME/bin/tmux-session -sI #{pane_tty}" "send-keys 0x0173" "select-pane -t \\{next\\} ; if-shell \"\$is_vim\" \"send-keys \\\\w0\""
```
tmux list-keys prior to v3.2
```
bind-key    -T root         ų                    if-shell "\$HOME/bin/tmux-session -sI #{pane_tty}" "send-keys 0x0173" "select-pane -t \\{next\\} ; if-shell \"\$is_vim\" \"send-keys \\\\w0\""
```

tmux list-keys at v3.2
```
bind-key    -T root         ''                   if-shell "\$HOME/bin/tmux-session -sI #{pane_tty}" "send-keys 0x0173" "select-pane -t \\{next\\} ; if-shell \"\$is_vim\" \"send-keys \\\\w0\""
```

Note the `''` where the UTF character used to be.

Thanks

**Comment by nicm** [comment]
I'll take a look but why not use the `\u` and `\U` forms which were actually intended to work?

**Comment by systemmonkey42** [comment]
No reason, other than I started using this method long before \uXXXX was available or documented (at least in the tmux manual), and never got around the changing it.

FYI, changing it to \uXXXX doesn't fix the problem.

**Comment by nicm** [comment]
\uXXXX works for me.

**Comment by systemmonkey42** [comment]
My apologies, my test was faulty because I connected to a running tmux instead of starting a new one.
I can confirm \uXXXX works as expected.

I'll close this ticket and update my conf.

Thanks.

**Comment by nicm** [comment]
It looks like `0x` was actually intended anyway, and it is broken... looking at it now.

**Comment by systemmonkey42** [comment]
Thanks,  Nice to know I wasn't going crazier than usual.

I'll re-open so I can track and test the result.

**Comment by nicm** [comment]
This should fix it: [x.diff.txt](https://github.com/tmux/tmux/files/4840286/x.diff.txt)

**Comment by nicm** [comment]
Funny U+0173 is ų but iTerm2 gives me ř... probably my font.

**Comment by systemmonkey42** [comment]
Confirmed fix.  Using the old format 0xXXXX is worked as before.

Thanks again for your solid support!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
