### ISSUE TITLE
On OSX writes are slow when two characters entered in cbreak mode

### ISSUE THREAD

**Issue by thomasballinger** [tmux/tmux#229]
When I run a program in tmux that writes to stdout and reads from stdin in cbreak mode, it takes much longer to write when I press two keys at once.

    tomb@tom-mba (master) tmux$ ./tmux -V
    tmux 2.2
    tomb@tom-mba (master) tmux$ cat slow.py
    import time
    import tty
    import os
    import sys

    tty.setcbreak(sys.stdin)
    try:
        while True:
            sys.stdin.read(1)
            t0 = time.time()
            sys.stdout.write('\n')
            for _ in range(10000):
                sys.stdout.write(' \r')
                sys.stdout.flush()
            print time.time() - t0
    finally:
        os.system('reset')
    tomb@tom-mba (master) tmux$ python slow.py

    0.0318839550018

    0.509894132614

    0.0365719795227

Once the program starts I press one key and writing takes .03 seconds. Then I press two keys simultaneously and the first of the two triggered writes takes a lot longer, .5 seconds.

Any thoughts on what's going on?

**Comment by nicm** [comment]
Can't reproduce, perhaps it is a quirk of your platform, terminal or
TERM, ncurses version, python version, or something else.

**Comment by nicm** [comment]
Also if you are trying it over ssh, try it without.

**Comment by thomasballinger** [comment]
I'm using OSX 10.11.1 with iTerm 2 and Terminal.app. I see the issue using tmux on this machine normally and when I ssh into this machine. I can't reproduce on Ubuntu servers over ssh. Here's a [a video](https://www.youtube.com/watch?v=ST5qtaOQOMs).

Here's a similar c program that has the same behavior:

  #include <stdlib.h>
  #include <stdio.h>
  #include <sys/time.h>

  int main() {
    struct timeval begin, end;

    system("stty cbreak");

    while (1) {
      char c = getchar();
      if (c == 'q') {
        break;
      }

      putchar('\n');
      gettimeofday(&begin, NULL);
      for (int j = 0; j < 10000; j++){
        putchar('x');
        putchar('\r');
        fflush(stdout);
      }
      gettimeofday(&end, NULL);
      double elapsed = (end.tv_sec - begin.tv_sec) +
                    ((end.tv_usec - begin.tv_usec)/1000000.0);
      printf("%f\n", elapsed);
    }
    system("reset");
  }

**Comment by nicm** [comment]
It is fine for me, so I expect it is just OS X.

**Comment by thomasballinger** [comment]
After a certain point while working on updating the screen after the second key is pressed while output is being printed, input_parse in the logs stop looking like this:

    ...
    1449535019.549459 %0 has 28 bytes
    1449535019.549468 @0 alerts timer reset 0
    1449535019.549475 @0 alerts flags added 0x2
    1449535019.549485 input_parse: %0 ground, 28 bytes: x\rx\rx\rx\rx\rx\rx\rx\rx\rx\rx\rx\rx\rx\r
    ...

and start being only one byte at a time:

    ...
    1449535019.551499 %0 has 1 bytes
    1449535019.551508 @0 alerts timer reset 0
    1449535019.551516 @0 alerts flags added 0x2
    1449535019.551525 input_parse: %0 ground, 1 bytes: \r
    ...

while in logs without simultaneous key pressing `has 1 bytes` almost never occurs.

**Comment by nicm** [comment]
Send me the full log please.
