### ISSUE TITLE
Suggestion for naming of RC tags

### ISSUE THREAD

**Issue by alekseyrybalkin** [tmux/tmux#2290]
Hello, tmux contributors! Thank you for such a useful piece of software, which I use happily every day.

This issue is about tags in tmux repository. Things right now:
- RC tags are tagged as "3.2" and not as e.g. "3.2-rc1"
- When the new RC is released, tag "3.2" is deleted and re-created on a new commit with new RC, e.g. rc2
- When the final release 3.2 is ready the tag is deleted and re-created again

For automatic tools which check for new versions of packages from their repositories (e.g. [1], and others, including my personal checking tool) this causes some problems:
- Auto-fetching from git repository fails because tag is overwritten (the solution is first to delete the old "3.2" tag, and then fetch new one from repo, which is hard to automate)
- Automatic tool can't easily distinguish RC release from final releases based on tag name

Is it possible to change the tagging scheme in tmux repo in such a way as to:
- Make all tags stable, once they are created, they are never deleted and never change the commit they refer to
- Make tag names for RC releases different from tag names for final releases
?

One possible scheme is using tags "3.2-rc1", "3.2-rc2", etc.. for RC releases and one and only tag "3.2" for final release.

[1] https://release-monitoring.org/project/4980/

**Comment by nicm** [comment]
I could make an RC tag and move it and then delete it and replace it with the release tag I suppose, it looks like GitHub allows the tag on the release to be changed.

But the release is the tarball not the tag, so you would be better to check if it exists, the tag is just for convenience...

**Comment by alekseyrybalkin** [comment]
In my opinion both tarball and repository tag _are_ releases, because you can build a binary from a repository by cloning and checking out the tag. And in normal situation (not for tmux right now) the built binary will behave like a binary from tarball. In current tagging scheme for tmux this is not true, because right now by building code from 3.2 tag I will get RC1 instead (and something else next time the 3.2 tag changes).
> I could make an RC tag and move it and then delete it and replace it with the release tag I suppose, it looks like GitHub allows the tag on the release to be changed.
In my opinion the best solution is to rename current tag "3.2" into "3.2-rc1" and from now on use the new naming scheme and never rename/delete any created tags for any future RCs and final releases again.

But of course, it is for you to decide what works best. I just think this will remove some confusion and make life easier for automated tools.

**Comment by nicm** [comment]
>  In current tagging scheme for tmux this is not true, because right now by building code from 3.2 tag

There is no 3.2 until it is released. I would have thought it was better to get the release candidates for the 3.2 tag rather than nothing, until 3.2 is actually released. But I don't really mind, I can use an RC tag and delete it once the release is made. I'm not leaving dozens of useless tags around.

The tag should be at or close to the release so you should be OK to build from it although I don't particularly encourage it.

**Comment by nicm** [comment]
I'll try and remember to do this for the next release or release candidate.

**Comment by alekseyrybalkin** [comment]
Thanks!
