### ISSUE TITLE
Selection Mode is malfunctioning

### ISSUE THREAD

**Issue by freddieventura** [tmux/tmux#2291]
Selection mode is malfunctioning , it wont navigate with h , j , k , l anymore (although I can use the cursors)
When trying to begin the selection y press <spacebar> it will send the cursor the line right above the cursor line.
After that I press <enter> and it wont exit selection mode until I press <q>. 

```
$uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 3.1
xterm-256color
```
Unkown meaning Kali Linux 2020.2 , desktop environment  KDE.
My installed plugins are
```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
```
[tmux-out-18251.log](https://github.com/tmux/tmux/files/48
[tmux-client-18249.log](https://github.com/tmux/tmux/files/4861498/tmux-client-18249.log)
61492/tmux-out-18251.log)
[tmux-server-18251.log](https://github.com/tmux/tmux/files/4861493/tmux-server-18251.log)

Thanks
Please find attached the log files[
[tmux-client-18249.log](https://github.com/tmux/tmux/files/4861490/tmux-client-18249.log)
](url)

**Comment by nicm** [comment]
Does this still happen if you use tmux without a config, ie run `VISUAL=vi EDITOR=vi tmux -Ltest -f/dev/null new`?
