### ISSUE TITLE
Update tmux for Ubuntu

### ISSUE THREAD

**Issue by gustawdaniel** [tmux/tmux#2293]
I have quite old version 

```
tmux -V
tmux 2.6
```

And can't install newest

```
apt-cache policy tmux
tmux:
  Installed: 2.6-3ubuntu0.2
  Candidate: 2.6-3ubuntu0.2
  Version table:
 *** 2.6-3ubuntu0.2 500
        500 http://pl.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.6-3 500
        500 http://pl.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

How to fix it?

**Comment by ThomasAdam** [comment]
Hi,

This is a question for your Linux distribution (Ubuntu).  Tmux doesn't control how or when they release software.

**Comment by gustawdaniel** [comment]
# Fixed but I have question

### How to install tmux and tmuxinator on ubuntu

I temporary fixed by

```
sudo apt remove tmux
```

Download version from release:

Then:

https://stackoverflow.com/questions/21926202/libevent-not-found-error-in-tmux

```
sudo apt install libevent-dev
```

Then:

```
./configure && make
```

I had some warning:

```
warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(tty_log_fd, buf, len)
```

https://stackoverflow.com/questions/48687315/warning-ignoring-return-value-of-write-declared-with-attribute-warn-unused-r

```
sudo make install
```

Then

```
tmux -V
tmux 3.1b
```

But I lost access to tmuxinator

```
tmuxinator 
bash: /usr/bin/tmuxinator: No such file or directory
```

So I fixed by

```
gem install tmuxinator
```

And then

```
sudo apt install tmuxinator
```

---

### question

So who is responsible for delivering tmux to ubuntu package system?

**Comment by gustawdaniel** [comment]
Update, there was also required reset of server

https://github.com/tmux/tmux/issues/2212

**Comment by drevicko** [comment]
There is also an "AppImage" installer [here](https://github.com/nelsonenzo/tmux-appimage). This builds tmux in a docker container, from which you can then install the binary (instructions included in the linked repo).
