### ISSUE TITLE
3.2-rc server does not start with select-pane -t %0

### ISSUE THREAD

**Issue by mmjo** [tmux/tmux#2295]
### Issue description

3.2-rc server does not start with `select-pane -t %0`
without the select-pane, there is no problem.

.tmux.conf contains:
```
set -s default-terminal tmux-256color
new-session -A -D
split-window
select-pane -t %0
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
 tmux 3.2-rc 
(git commit is 629ba1b8)
* Platform (`uname -sp`). 
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). 
inside: tmux-256color; outside: xterm-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).
logs from `tmux -L foo kill-server; tmux -vv -L foo attach`
[tmux-client-20709.log](https://github.com/tmux/tmux/files/4866490/tmux-client-20709.log)
[tmux-server-20711.log](https://github.com/tmux/tmux/files/4866492/tmux-server-20711.log)

the tmux-out logfile is empty.

Regards, Mike

**Comment by nicm** [comment]
This should fix it, will be in GitHub later on today. Thanks!
~~~~
diff -u -p -r1.62 cmd-select-pane.c
--- cmd-select-pane.c   26 May 2020 08:47:50 -0000      1.62
+++ cmd-select-pane.c   3 Jul 2020 06:59:23 -0000
@@ -205,7 +205,7 @@ cmd_select_pane_exec(struct cmd *self, s
                return (CMD_RETURN_NORMAL);
        }

-       if (c->session != NULL && (c->flags & CLIENT_ACTIVEPANE))
+       if (c != NULL && c->session != NULL && (c->flags & CLIENT_ACTIVEPANE))
                activewp = server_client_get_pane(c);
        else
                activewp = w->active;
@@ -214,7 +214,7 @@ cmd_select_pane_exec(struct cmd *self, s
        if (window_push_zoom(w, args_has(args, 'Z')))
                server_redraw_window(w);
        window_redraw_active_switch(w, wp);
-       if (c->session != NULL && (c->flags & CLIENT_ACTIVEPANE))
+       if (c != NULL && c->session != NULL && (c->flags & CLIENT_ACTIVEPANE))
                server_client_set_pane(c, wp);
        else if (window_set_active_pane(w, wp, 1))
                cmd_find_from_winlink_pane(current, wl, wp, 0);

**Comment by mmjo** [comment]
confirmed, thx!
