### ISSUE TITLE
M-Left etc. is not correctly received anymore in vim

### ISSUE THREAD

**Issue by mmjo** [tmux/tmux#2296]
### Issue description

The "Alt - Cursor key" bindings are not working as before in vim.
This is the case since commit 340fd691 upto the latest 3.2-rc (5661346c).

Example .tmux.conf:
```
set -s default-terminal tmux-256color

## Switching between panes and vim-windows
## See: https://github.com/christoomey/vim-tmux-navigator
set -s default-terminal tmux-256color
set -g default-command bash
set -g default-shell /bin/bash

set-environment -g -r is_vim
is_vim="/bin/ps -o state= -o comm= -t '#{pane_tty}' \
	| /bin/grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|vi|n?vim?x?)(diff)?$'"
bind -T root M-Left if "$is_vim" "send-keys M-Left" "select-pane -L"

new-session -A -D
split-window -h vi
```
If `cat -v` is started from within vim, then I see `^[^[[D` when I press M-Left.

Attached logs show a session in which I type: 

- M-Left (in vim, does not work anymore)
- M-right (goes to the pane with bash)
- M-left (goes back to the vi-pane)

M-left is not special, the problem happens (at least) for all M-<cursorkey> combinations.

### Required information

* tmux version (`tmux -V`).
tmux 3.2-rc
(git commit is 5661346c)

* Platform (`uname -sp`).
Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).
inside: tmux-256color outside: xterm-256color (gnome-terminal)

* Logs from tmux (`tmux -L foo kill-server; tmux -L foo -vv att`).
[tmux-client-6444.log](https://github.com/tmux/tmux/files/4871491/tmux-client-6444.log)
[tmux-out-6446.log](https://github.com/tmux/tmux/files/4871492/tmux-out-6446.log)
[tmux-server-6446.log](https://github.com/tmux/tmux/files/4871493/tmux-server-6446.log)

Regards, Mike

**Comment by nicm** [comment]
Yes... we should be sending `\033[1;3C`. I'll take a look.

**Comment by nicm** [comment]
Can you try this please? [tmux-meta-fix.diff.txt](https://github.com/tmux/tmux/files/4873020/tmux-meta-fix.diff.txt)

**Comment by mmjo** [comment]
Great job, it works!

Thanks, Mike

**Comment by mmjo** [comment]
It seems that list-keys for symbolic names also fail on the same commit (340fd691).
From within tmux:bash `tmux lsk -T prefix Left`
says: `unknown key: Left`

Do you want another issue opened for this?

**Comment by nicm** [comment]
I'll take a look at that later.

**Comment by nicm** [comment]
I have applied this now and a fix for `list-keys`. Let me know if you still see any problems. Thanks!

**Comment by mmjo** [comment]
It works now. Thanks!
