### ISSUE TITLE
Extra highlighting in output

### ISSUE THREAD

**Issue by marchaesen** [tmux/tmux#2298]
When I run the grep command within a tmux session, the last part of the output lines are highlighted.
The 'grep -r test' command executed in a folder containing the tmux sources, gives the following output screen:

![image](https://user-images.githubusercontent.com/62388258/86562057-50b59880-bf62-11ea-9cf6-eeda96ced957.png)

After doing a Ctrl+b PgUp and Ctrl+b PgDown, the end-of-line highlighting disappears:

![image](https://user-images.githubusercontent.com/62388258/86562197-8eb2bc80-bf62-11ea-9858-6228a40da037.png)

The tmux version is the current master version (c0d9eaff9bd8c2a87dd95a860ed659f472a9ddf4).
The last commit that did not have this problem is 9edef17698118533ea66e6f1a7a788eddcb15d4e. So the problem has been introduced in commit d90ca7ecd61ee2f1376801acd61252c03caef3ca.

❯ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux next-3.3
screen-256color

Tmux is running inside st

Here are the log files after having run the grep (tmux -vv -Ltest -f/dev/null new):
[tmux-server-4007813.log](https://github.com/tmux/tmux/files/4877120/tmux-server-4007813.log)
[tmux-out-4007813.log](https://github.com/tmux/tmux/files/4877122/tmux-out-4007813.log)
[tmux-client-4007811.log](https://github.com/tmux/tmux/files/4877123/tmux-client-4007811.log)

**Comment by nicm** [comment]
Here is a shorter test case:
~~~~
printf "xxx\033[m\033[K\033[45m\033[K\033[m\033[K\r\n"

**Comment by nicm** [comment]
The check for whether a clear is redundant is wrong and doing it right would probably not be worth the cost, so let's remove it. Try this please: [tmux-no-redundant.diff.txt](https://github.com/tmux/tmux/files/4878113/tmux-no-redundant.diff.txt)

**Comment by marchaesen** [comment]
This patch indeed solves this problem.
Thanks.

**Comment by nicm** [comment]
I have applied this now, thanks!
