### ISSUE TITLE
tmux reports "unknown option: status-utf8" on startup

### ISSUE THREAD

**Issue by kevinushey** [tmux/tmux#230]
I have, in my `.tmux.conf`:

```
set -g status-utf8 on
```

but the latest version of `tmux` (installed with `brew install tmux --HEAD`) reports that this option is unknown. Am I missing something?

**Comment by nicm** [comment]
It is no longer necessary.

**Comment by kevinushey** [comment]
Got it, thanks.

**Comment by pizzaops** [comment]
For those who still run into this, and don't have that line in their .tmux.conf, I found it in `lib/python/site-packages/powerline/bindings/tmux/powerline-base.conf` on my Mac.

Relative path given since it'll be different between `--user` and non-`--user` installs of `powerline-status`.

**Comment by Atcold** [comment]
I noticed that on my Mac, the unicode is not visualised inside `tmux`. Any suggestion?

**Comment by dserodio** [comment]
Sorry to dig this old issue, but in which version was this option removed? I can't find it in [CHANGES](https://github.com/tmux/tmux/blob/master/CHANGES)
