### ISSUE TITLE
Unexpected permission error when using `TMUX_TMPDIR`

### ISSUE THREAD

**Issue by zepalmer** [tmux/tmux#2300]
### Issue description

There appear to be undocumented requirements on the permissions of the `$TMUX_TMPDIR` directory.  Consider the following sequence of commands:

```bash
export TMUX_TMPDIR="$(pwd)/example1.dir"
mkdir -p "$TMUX_TMPDIR"
tmux new-session -d
chmod u+rwx,go-r+wx $(find "$TMUX_TMPDIR" -type d)
tmux -v list-clients
```

The `chmod` command should recursively mark the `$TMUX_TMPDIR` writable and executable such that, if the full path of the socket were to be shared with another user, that user would be able to join the `tmux` session (but users who do not know the name of the socket would be unable to list the directory).  In my actual use case, `$TMUX_TMPDIR` contains sufficient randomization to be unguessable and is placed in a similarly unlistable directory.

In the above, the final `tmux -v list-clients` command fails with the message `error creating {{snip}}/example1.dir/tmux-1000 (Permission denied)`.  At the time this command fails, `example1.dir` and the `tmux-1000` directory it contains have permissions `rwx-wx-wx`.  If I do not run the `chmod`, then the permissions are the *more restrictive* `rwx------` and the command *does not* fail.

This appears to be specific to setting `$TMUX_TMPDIR` because another scenario using `-S` behaves differently.  Consider the following commands:

```bash
export SOCKET_DIR="$(pwd)/example2.dir"
mkdir -p "$SOCKET_DIR"
tmux -S "$SOCKET_DIR/socket" new-session -d
chmod u+rwx,go-r+wx $(find "$SOCKET_DIR" -type d)
tmux -S "$SOCKET_DIR/socket" list-clients
```

The above executes successfully whether the `chmod` command is included or not.  This approach is insufficient for my purposes because the socket here is named on the command line and so is visible in `/proc` to all users.  (In the previous example, the socket name was visible only through the environment variables, which is sufficient in my use case.)

### Required information

* `tmux` version: Both `2.8` as well as `next-3.3` (a5f99e14c6f264e568b860692b89d11f5298a3f2, which is `HEAD` on `master` at the time of this writing)
* Debian 10 stable
* `$TERM` is `xterm-256color` outside of tmux (`echo $TERM`); it is `screen` inside of `tmux`
* The above command is not producing a log file despite being run with `-v`.

### Expected behavior

I would either expect the first example to work correctly or I would expect documentation to indicate the permissions required of the `$TMUX_TMPDIR` directory and/or its contents.  I've attempted for some time to find such documentation to no avail, but I may have missed it.

### Potential workaround

I may be able to work around this by using private symlinks to the sockets in tandem with the `-S` flag; this way, the symlink (which is not visible to the rest of the world) is displayed publicly in `/proc` but the socket to which it links is not.  I am not yet sure if this will work.  Much better would be the ability to set the socket using an environment variable such as `TMUX_SOCKET`, though I expect that isn't a priority for most users.

**Comment by zepalmer** [comment]
As a follow-up, it appears from [reading the source code](https://github.com/tmux/tmux/blob/a5f99e14c6f264e568b860692b89d11f5298a3f2/tmux.c#L473) that the `TMUX` environment variable functions in part like the `TMUX_SOCKET` variable I hypothesized above.  That is, I can run

```bash
TMUX=/some/location/socket tmux
```

and that `tmux` server appears to use the provided socket path.  The parsing of this variable is somewhat more complicated, though; it seems to permit a comma following the socket path and that information is ignored when determining the socket.  Is there documentation of what the `TMUX` variable does?  All I could find in the manual page was that `update-environment` may have some impact on this variable.

My potential workaround above is unlikely to function in the long run as `tmux` clobbers the symbolic link, so I was relieved to discover this functionality.  Am I interpreting it correctly?

**Comment by nicm** [comment]
tmux doesn't check the permissions of `/tmp` or `TMUX_TMPDIR`, but the `tmux-*` directory inside must not be world accessible for obvious reasons.

I don't recommend using TMUX` to specify the socket path, the form of `TMUX` is not guaranteed to stay the same. If you must have a world readable socket, use `-S` and change the permissions after the socket is created.

**Comment by zepalmer** [comment]
I didn't realize that `TMUX` was used only internally; that explains the lack of documentation.  It's lucky for me that it happens to work for my use case for now!  But you are of course correct: it's not a long term solution.

Unfortunately, `-S` doesn't work for me in this case.  I am writing some simple scripts to permit novice users to share `tmux` sessions.  I need the users to be able to join each other's sessions without third parties jumping in.  But the sharing of terminals will be ad-hoc and dynamic, so I can't just create user groups for this.

Instead, I am creating `tmux` sockets with a randomly-generated name.  The sockets are contained within a directory which is world-executable but not world-readable.  As a consequence, another user can connect to the `tmux` socket if the user knows the socket's name, but the user can't go browsing for the socket by listing the directory.  The randomly generated name is sufficiently long as to be unguessable.

If I use the `-S` option, then the name of the socket will be visible through `/proc/$TMUX_PID/cmdline` and anyone will be able to connect to it.  By using `TMUX`, the name of the socket is only visible to `root` and the user who owns the process.  This is why I was so fortunate that this variable works in the way it does for now.

Would you consider allowing a variable `TMUX_SOCKET` to act equivalent to `-S` in a future version of `tmux`?  If the `TMUX` variable had not existed, I was prepared to clone and patch the source in this repository to satisfy my requirement.  If you don't object, I'd be happy to submit a PR when I find the time; it would give me a long term solution to my problem.

Thanks for the help!

**Comment by nicm** [comment]
It seems like for you, the best option would be to use `TMUX_TMPDIR` but to put all the users you want to use your sockets into a common group and make `tmux-*` mode 330 or 730.

**Comment by nicm** [comment]
I don't know about adding another environment variable, it seems like we have enough ways to specify the socket and I don't think many people would use it.

**Comment by zepalmer** [comment]
Alrighty; that's fair.  Thanks for the suggestion above, as well.

I think, then that the original point of the issue still stands: I have found no documentation that `tmux` requires the socket to be contained within a directory which is not world readable.  This requirement appears to apply only when `TMUX_TMPDIR` is used (and not when `-S` is used).  `tmux` responds to this situation with a `permission denied` message (rather than e.g. `socket directory must not be world readable`).  I suggest that the manual page should mention this requirement and that the error message in this situation more clearly indicate the problem.

Thanks for the discussion and for the outstanding application.  :)

**Comment by nicm** [comment]
I think it is common sense not to allow world-readable sockets in /tmp, but if you want to suggest some text for the man page then that is fine. It will probably need to go under `-L socket-name`.

TBH I don't know if it is worth a custom error message as well, EACCES seems pretty clear to me. It is the same as you get for other permissions issues:
~~~~
$ tmux -S /root/x new
error connecting to /root/x (Permission denied)

**Comment by nicm** [comment]
We could say something like this:
~~~~
--- tmux.1      6 Jul 2020 09:14:20 -0000       1.788
+++ tmux.1      10 Jul 2020 14:00:30 -0000
@@ -169,8 +169,17 @@ independent
 servers to be run.
 Unlike
 .Fl S
-a full path is not necessary: the sockets are all created in the same
-directory.
+a full path is not necessary: the sockets are all created in a directory
+.Pa tmux-UID
+under the directory given by
+.Ev TMUX_TMPDIR
+or in
+.Pa /tmp .
+The
+.Pa tmux-UID
+directory is created by
+.Nm
+and must not be world readable, writable or executable.
 .Pp
 If the socket is accidentally removed, the

**Comment by zepalmer** [comment]
This text addresses my concern; thank you!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
