### ISSUE TITLE
Matches from regex searches seem to overlap

### ISSUE THREAD

**Issue by toupeira** [tmux/tmux#2301]
### Issue description

When trying out the new regex search I noticed some weirdness, here are steps to illustrate the problem:

1. Run `echo foo bar` to generate some content
2. Enter copy-mode with `Ctrl-b [`
3. Start a search with `?` and enter `\w+`
4. Press `n` until the current match is on `foo`
5. Press `N` to go back to `bar`

On step 4 you'll see that only the first letter of each match is highlighted as current, rather than the whole word.

On step 5 it moves the match to the `o` in `foo` rather than back to `bar`. If you keep pressing `N` it moves back one letter at a time.

This also indirectly affects the copy-pipe commands as they only copy the first letter.

Note that I also ran into a few tmux crashes when calling the search and copy commands, but I haven't found a reliable way to reproduce that yet. But I wonder if it's related to these bugs.

### Required information

* tmux version (`tmux -V`): `tmux 3.2-rc`
* Platform (`uname -sp`). `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`). `xterm-256color` / `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
It works fine for me, although I tried `[a-z]+` because `\w` is not POSIX regex syntax.

**Comment by toupeira** [comment]
@nicm ah sorry I didn't realize, but I get the same behaviour with `[a-z]+`. This is with a blank tmux configuration, and I also forgot to mention that I'm using the package from Debian unstable.

I recorded a screencast, please excuse the horrible encoding.

This first part shows a search for `[a-z]+`, moving backward with `N` (correctly), and moving forward with `n` (incorrectly). Notice that only the first letter of each match becomes magenta (inverted because of the cursor), everything else stays cyan:

![tmux-issue-2301-part1](https://user-images.githubusercontent.com/6501/87231600-bc5f9180-c3b8-11ea-8838-b5239c78d449.gif)

This part shows a search for `foo` where everything works as expected, including the current match highlighting.:

![tmux-issue-2301-part2](https://user-images.githubusercontent.com/6501/87231601-c1bcdc00-c3b8-11ea-8550-a610e1cc26b4.gif)

I also ran into the crash again, it seems to happen when the buffer contains emoji characters. Searching for `foo` still works, but it seems anything that could match the emoji causes a crash, like `[a-z]` in this example:

![tmux-issue-2301-part3](https://user-images.githubusercontent.com/6501/87231611-e1ec9b00-c3b8-11ea-8696-17dbb55fe139.gif)

The logfiles for the full session are below, the relevant error seems to be `fatal: xmalloc: zero size` in the server log:

- [tmux-client-27113.log](https://github.com/tmux/tmux/files/4907456/tmux-client-27113.log)
- [tmux-out-27115.log](https://github.com/tmux/tmux/files/4907457/tmux-out-27115.log)
- [tmux-server-27115.log](https://github.com/tmux/tmux/files/4907458/tmux-server-27115.log)

**Comment by toupeira** [comment]
Oh and in case you can reproduce, I guess a possible fix could be to start the `search-forward` on the first character after the current match, rather than the cursor position.

**Comment by nicm** [comment]
Does this fix the crash? [x.diff.txt](https://github.com/tmux/tmux/files/4911815/x.diff.txt)

**Comment by toupeira** [comment]
@nicm it does, thanks! :+1:

I can also match emojis using e.g. `[[:graph:]]`, so that works too.

**Comment by nicm** [comment]
I don't know that what tmux is doing here is wrong. If I have "foo" and search for [a-z]+ then "oo" and "o" are just as much a match as "foo".

**Comment by nicm** [comment]
Try this please which fixes it to work like emacs - when you search forward the cursor finishes at the end of the match and backwards at the start: [tmux-search-down.diff.txt](https://github.com/tmux/tmux/files/4958602/tmux-search-down.diff.txt)

**Comment by toupeira** [comment]
> Try this please which fixes it to work like emacs - when you search forward the cursor finishes at the end of the match and backwards at the start: tmux-search-down.diff.txt

@nicm finally got around to testing this, thanks! :+1: 

This *almost* works as I would expect, but when switching directions the first `search-forward` first places the cursor after the end of the current match, and then another `search-forward` actually goes to the next match:

![tmux-search](https://user-images.githubusercontent.com/6501/88714115-98bc7b00-d11c-11ea-99f1-7ad6f2f23380.gif)

I have no idea how the search is implemented in tmux, but is it maybe possible to start the search from the cursor position after the current match, without actually moving the cursor first?

> I don't know that what tmux is doing here is wrong. If I have "foo" and search for [a-z]+ then "oo" and "o" are just as much a match as "foo".

Sure, technically that's perfectly correct, but it doesn't feel very *useful* to me :grinning: 

My use case for this is replacing https://github.com/tmux-plugins/tmux-copycat, so I have different keymaps to search for paths, URLs, IP addresses etc. and just want to navigate them with `n` / `N` before yanking the one I want.

I'm not familiar with Emacs' default behaviour here, my reference for this is Vim and `evil-mode` which both work as I described. But I just tried it out with `emacs -q` and it seems to behave more like your original implementation when searching backwards (moving one letter at a time), and like your patched version when searching forward (moving one match at a time, because the cursor is placed after the current one). This feels very confusing to me too.

Let me know what you think, I also don't mind if we leave this issue open for a while until we hear some more use cases from other people.

**Comment by nicm** [comment]
When you change direction it should swap ends of the current match - compare with C-r and C-s in emacs.

**Comment by toupeira** [comment]
Ah ok I was using the "Regexp Forward" / "Repeat Forward" / "Repeat Backwards" options from the Edit menu for testing, not sure which commands these correspond to.

The C-r / C-s searches don't seem to support regex so I can't reproduce the partial-matching behaviour with them.

**Comment by nicm** [comment]
Regex with M-C-r and M-C-s.

The last diff doesn't search forward properly for me, it should move to end of current match but it seems to do an extra search. I'll take a better look tomorrow.

**Comment by nicm** [comment]
Here is a version that fixes that problem so forward and backward are now consistent: [x.diff.txt](https://github.com/tmux/tmux/files/4994907/x.diff.txt)

This now behaves like emacs for me. It would be possible to make it behave like vi if that is different with vi keys but I don't really know if it is worth it.

**Comment by toupeira** [comment]
@nicm thanks! :+1: 

With this patch, `search-forward` does work the same here as M-C-s in Emacs.

`search-backward` moves to the beginning of the current match and stays there when searching again, while M-C-r in Emacs moves backwards one letter/submatch at a time (still using the `[a-z]+` example).

If I remap `n` to move left first, it again works the same way as in https://github.com/tmux/tmux/issues/2301#issuecomment-665267994:

```
bind -T copy-mode-vi n 'send-keys -X cursor-left; send-keys -X search-again'
```

I still have to press `N` twice when switching directions though, and I also noticed that copying the current match doesn't work reliably when the cursor is at the end of the match (I get a previous/earlier match instead).

Maybe another way to solve this would be adding commands to move to the beginning/end of the current match, which could be scripted with `send-keys -X`? But generally I think this works well enough now that I think your latest patch would be worth merging.

**Comment by nicm** [comment]
Try this instead please and see if it fixes reverse search: [xyz.diff.txt](https://github.com/tmux/tmux/files/5021242/xyz.diff.txt)

**Comment by toupeira** [comment]
@nicm it does! :+1: 

(i.e., the `cursor-left` workaround is not necessary anymore)

**Comment by nicm** [comment]
I have applied this now, thanks!
