### ISSUE TITLE
tmux domain hijacked

### ISSUE THREAD

**Issue by TAbdiukov** [tmux/tmux#2303]
### Issue description

tmux's sourceforge page, [https://sourceforge.net/projects/tmux/](https://sourceforge.net/projects/tmux/) lists the website as [https://tmux.sourceforge.io/](https://tmux.sourceforge.io/) . The latter URL redirects to [http://www.gigastudio.com.ua/](http://www.gigastudio.com.ua/) .

I thought the tmux dev team should be notified

### Required information

~~Please provide the following information:~~ - not applicable.

**Comment by nicm** [comment]
I don't have any control over what SourceForge do.
