### ISSUE TITLE
Delete all paste-buffers

### ISSUE THREAD

**Issue by ierdnah** [tmux/tmux#2305]
Hi,

Sometimes I have a command in the paste-buffer from a server and by mistake I paste it on another server and it may do a lot of damage.
Is there a way to clear all the paste-buffers ?
I need to make a shortcut key to clear all tmux paste-buffers and I can't find a way to iterate over all paste-buffers and delete them.

Thank you

**Comment by nicm** [comment]
You can enter buffer mode and the  just keep pressing `d` or tag them all with `C-t` then delete with `D`.

Or write a little shell script something like `tmux lab -F '#{buffer_name}'|while read i; do tmux deleteb -b "$i"; done`.
