### ISSUE TITLE
Tmux prints wrong color when trying to print too many 24 bit colors

### ISSUE THREAD

**Issue by simnalamburt** [tmux/tmux#2307]
### Issue description
Tmux prints wrong color if one tries to print too many 24-bit colors.

![image](https://user-images.githubusercontent.com/4435445/87400238-80fcd700-c5f3-11ea-8454-4b20f0962bae.png)

Execute following bash script in tmux session to reproduce this issue:
```bash
curl -s https://raw.githubusercontent.com/simnalamburt/snippets/master/python/24bit-color.py | python3
```

### Required information
* tmux version (`tmux -V`): Reproducible in `tmux 2.8`, `tmux 3.2-rc`, and `tmux next-3.3` (commit 405b71e0166aeb98741f7b507163134f427e9f1b)
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`): Both are `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): [logs.tar.gz](https://github.com/tmux/tmux/files/4917451/logs.tar.gz)

###### References
- https://github.com/simnalamburt/snippets/blob/master/python/24bit-color.py

**Comment by nicm** [comment]
Well, yes and no. You are sending invalid escape sequences, so tmux can do what it likes. As it happens it ignores the 38 or 48 and parses the rest as SGR, so for example 38;2;42;85;309 is parsed as SGR 2 then SGR 42 and so on.

If you want tmux to discard the entire SGR 38 when it is invalid, you can use the : form - so send `38:2:42:85:309` instead.

**Comment by simnalamburt** [comment]
Omg couldn’t catch that I’ll try your fix

2020년 7월 14일 (화) 18:00, Nicholas Marriott <notifications@github.com>님이 작성:

**Comment by simnalamburt** [comment]
![image](https://user-images.githubusercontent.com/4435445/87407550-4730ce00-c5fd-11ea-88f9-bb6e0d1d52e9.png)

You fix worked. By the way, it was sad to know that only few terminal emulators treats colon as delimeter.

###### Reference
- https://gist.github.com/XVilka/8346728
