### ISSUE TITLE
tmux [server exited] coming out of sleep on OSX

### ISSUE THREAD

**Issue by phiche** [tmux/tmux#231]
My first experience of this issue was documented here https://github.com/tmux/tmux/issues/189 

Since that issue is closed I wanted to track this issue properly. 

**Environment**
I'm using OSX 10.10.5 (MacBook Pro Retina, 15-inch, Late 2013), tmux 2.1, zsh with oh-my-zsh in iTerm2. 

Here is my .tmux.conf

```
unbind C-b
set -g prefix C-a

# 256 colors for vim
set -g default-terminal "screen-256color"

# Start window numbering at 1
set-option -g base-index 1
set-window-option -g pane-base-index 1

# resize pane with arrow keys after pressing prefix
# -r: can be repeated without pressing prefix again
#     (500ms after last '-r' action or prefix)
unbind Left
unbind Right
unbind Down
unbind Up
bind -r h resize-pane -L 2
bind -r l resize-pane -R 2
bind -r j resize-pane -D 2
bind -r k resize-pane -U 2

# smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"

# Use vim keybindings in copy mode
setw -g mode-keys vi
set-window-option -g mode-keys vi

# add powerline
source /usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf

# Sane scrolling
set -ga terminal-overrides 'xterm*:smcup@:rmcup@'

# reload tmux config
bind-key r source-file ~/.tmux.conf

# allow scrolling with mouse in tmux
set -g mouse on
set -g @scroll-speed-num-lines-per-scroll "1"

# allow copy text by highlighting with v and yanking with y
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-pipe "pbcopy"

# prefix i to copy mode
unbind [
bind-key -c i copy-mode

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'nhdaly/tmux-scroll-copy-mode'

# restore tmux session on server start
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# Install new plugin with prefix I
run '~/.tmux/plugins/tpm/tpm'
```

**Description**
tmux randomly exits when my laptop resumes from sleep. Here is what was on my prompt this morning:
```
10:33:39 ~  » tmux                                                                                                                                                          
[server exited]
7:44:16 ~  »
```
The 10:33:39 timestamp was from yesterday morning, last time I ran tmux.
7:44:16 was this morning when my laptop resumed from sleep.

**Means to reproduce**
So far, I have never seen the exit occur when my computer is at my desk, plugged into power when I manually put the computer to sleep from hitting ctrl-shift-power.

I have only seen the problem occur after I've disconnected from power and the computer has been left sleeping for some hours before resuming.

This problem occurs around, I guess, around 25%-33%  of the time resuming from sleep. It feels like it happens are around every 2nd or 3rd day. 

**Additional information**
This article give a bit more information about sleep mode. 
https://support.apple.com/en-us/HT201714
Unfortunately it doesn't really indicate what sleep state the CPU might be going into.

I'm also using vim with a bunch of plugins. Vim was open each time in at least one window during every tmux exit.

Here is the grep from my system.log
```
9:06:52 ~  » grep '7:44' /var/log/system.log                                                                                                                                
Dec  9 07:44:13 Laptop kernel[0]: vm_compressor_record_warmup (28566 - 37807)
Dec  9 07:44:15 Laptop kernel[0]: vm_compressor_flush - starting
Dec  9 07:44:15 Laptop kernel[0]: vm_compressor_flush completed - took 39185 msecs
Dec  9 07:44:15 Laptop kernel[0]: hibernate_flush_memory: buffer_cache_gc freed up 8178 wired pages
Dec  9 07:44:15 Laptop kernel[0]: hibernate_alloc_pages act 152426, inact 587968, anon 208141, throt 0, spec 4087, wire 427937, wireinit 149476
Dec  9 07:44:15 Laptop kernel[0]: hibernate_setup(0) took 46125 ms
Dec  9 07:44:15 Laptop kernel[0]: IO80211AWDLPeerManager::doDisable   source [handleSIOCSIFFLAGS]
Dec  9 07:44:15 Laptop kernel[0]: en0: BSSID changed to f0:99:bf:0a:54:03
Dec  9 07:44:15 Laptop kernel[0]: en0: channel changed to 36,80
Dec  9 07:44:15 Laptop kernel[0]: AirPort: Link Down on awdl0. Reason 1 (Unspecified).
Dec  9 07:44:15 Laptop kernel[0]: IO80211AWDLPeerManager::doDisable   source [setLinkState]
Dec  9 07:44:15 Laptop kernel[0]: ARPT: 36387.309324: wl0: leaveModulePoweredForOffloads: Wi-Fi will turn off.
Dec  9 07:44:15 Laptop kernel[0]: AirPort: Link Down on en0. Reason 8 (Disassociated because station leaving).
Dec  9 07:44:15 Laptop kernel[0]: en0::IO80211Interface::postMessage bssid changed
Dec  9 07:44:15 Laptop kernel[0]: en0: 802.11d country code set to 'X3'.
Dec  9 07:44:15 Laptop kernel[0]: en0: Supported channels 1 2 3 4 5 6 7 8 9 10 11 12 13 36 40 44 48 52 56 60 64 100 104 108 112 116 120 124 128 132 136 140 149 153 157 161
Dec  9 07:44:15 Laptop kernel[0]: Bluetooth -- LE is supported - Disable LE meta event
Dec  9 07:44:15 Laptop kernel[0]: AppleCamIn::systemWakeCall - messageType = 0xE0000340
Dec  9 07:44:15 Laptop kernel[0]: hibernate_page_list_setall(preflight 0) start 0xffffff83740b7000, 0xffffff8374137000
Dec  9 07:44:15 Laptop kernel[0]: hibernate_teardown started
Dec  9 07:44:15 Laptop kernel[0]: hibernate_teardown: wired_pages 428041, free_pages 3690778, active_pages 2799, inactive_pages 38180, speculative_pages 31, cleaned_pages 0, compressor_pages 41
Dec  9 07:44:15 Laptop kernel[0]: hibernate_teardown_pmap_structs done: last_valid_compact_indx 250601
Dec  9 07:44:15 Laptop kernel[0]: hibernate_teardown: mark_as_unneeded_pages 4096, 57184, 34885
Dec  9 07:44:15 Laptop kernel[0]: hibernate_teardown completed - discarded 96165
Dec  9 07:44:15 Laptop kernel[0]: hibernate_page_list_setall time: 1660 ms
Dec  9 07:44:15 Laptop kernel[0]: pages 1054237, wire 308743, act 2799, inact 38179, cleaned 0 spec 31, zf 1, throt 0, compr 41, xpmapped 40000
Dec  9 07:44:15 Laptop kernel[0]: did discard act 108962 inact 443522 purgeable 147903 spec 4056 cleaned 0
Dec  9 07:44:15 Laptop kernel[0]: WARNING: hibernate_page_list_setall skipped 34210 xpmapped pages
Dec  9 07:44:15 Laptop kernel[0]: hibernate_page_list_setall found pageCount 349794
Dec  9 07:44:15 Laptop kernel[0]: IOHibernatePollerOpen, ml_get_interrupts_enabled 0
Dec  9 07:44:15 Laptop kernel[0]: IOHibernatePollerOpen(0)
Dec  9 07:44:15 Laptop kernel[0]: encryptStart 14010
Dec  9 07:44:15 Laptop kernel[0]: bitmap_size 0x7f508, previewSize 0x6ff7e8, writing 347659 pages @ 0x792d00
Dec  9 07:44:15 Laptop kernel[0]: hibernate_rebuild started
Dec  9 07:44:15 Laptop kernel[0]: hibernate_rebuild_pmap_structs done: last_valid_compact_indx 250601
Dec  9 07:44:15 Laptop kernel[0]: hibernate_rebuild completed - took 88 msecs
Dec  9 07:44:15 Laptop kernel[0]: booter start at 944 ms smc 0 ms, [12, 0, 0] total 623 ms, dsply 0, 0 ms, tramp 886 ms
Dec  9 07:44:15 Laptop kernel[0]: hibernate_machine_init: state 2, image pages 308530, sum was ec02108d, imageSize 0x206de000, image1Size 0x171cb000, conflictCount 3992, nextFree 1042
Dec  9 07:44:15 Laptop kernel[0]: hibernate_newruntime_map time: 0 ms, IOHibernatePollerOpen(), ml_get_interrupts_enabled 0
Dec  9 07:44:15 Laptop kernel[0]: IOHibernatePollerOpen(0) 5 ms
Dec  9 07:44:15 Laptop kernel[0]: hibernate_machine_init reading
Dec  9 07:44:15 Laptop kernel[0]: PMStats: Hibernate read took 227 ms
Dec  9 07:44:15 Laptop kernel[0]: hibernate_machine_init pagesDone 349581 sum2 fd99144a, time: 227 ms, disk(0x20000) 671 Mb/s, comp bytes: 64192512 time: 48 ms 1266 Mb/s, crypt bytes: 156315648 time: 37 ms 3943 Mb/s
Dec  9 07:44:15 Laptop kernel[0]: Wake reason: EC.LidOpen (User)
Dec  9 07:44:15 Laptop kernel[0]: vm_compressor_fastwake_warmup (28566 - 37807) - starting
Dec  9 07:44:15 Laptop kernel[0]: AppleCamIn::systemWakeCall - messageType = 0xE0000320
Dec  9 07:44:15 Laptop kernel[0]: AppleCamIn::systemWakeCall - messageType = 0xE0000340
Dec  9 07:44:15 Laptop kernel[0]: AppleCamIn::wakeEventHandlerThread
Dec  9 07:44:15 Laptop kernel[0]: No interval found for . Using 8000000
Dec  9 07:44:16 --- last message repeated 3 times ---
Dec  9 07:44:15 Laptop kernel[0]: Previous sleep cause: 5
Dec  9 07:44:15 Laptop kernel[0]: Previous shutdown cause: 5
Dec  9 07:44:15 Laptop kernel[0]: AppleThunderboltNHIType2::prePCIWake - power up complete - took 1 us
Dec  9 07:44:15 Laptop kernel[0]: AppleThunderboltGenericHAL::earlyWake - complete - took 15 milliseconds
Dec  9 07:44:15 Laptop kernel[0]: com_apple_driver_AppleUSBCardReaderUMC[0xffffff802af91800] - Device termination caused by a wake from hibernation or standby!
Dec  9 07:44:15 Laptop kernel[0]: No interval found for . Using 8000000
Dec  9 07:44:16 --- last message repeated 7 times ---
Dec  9 07:44:15 Laptop kernel[0]: TBT W (2): 0x0040 [x]
Dec  9 07:44:15 Laptop kernel[0]: IOThunderboltSwitch<0xffffff802a616c00>(0x0)::listenerCallback - Thunderbolt HPD packet for route = 0x0 port = 11 unplug = 0
Dec  9 07:44:15 Laptop kernel[0]: IOThunderboltSwitch<0xffffff802a616c00>(0x0)::listenerCallback - Thunderbolt HPD packet for route = 0x0 port = 12 unplug = 0
Dec  9 07:44:15 Laptop kernel[0]: en0: channel changed to 1
Dec  9 07:44:15 Laptop kernel[0]: AirPort: Link Up on awdl0
Dec  9 07:44:13 Laptop.local watchdogd[392]: [watchdog_daemon] @(         pm_callback) - ref=0x0 msg_type=0xe0000320 msg=0x0
Dec  9 07:44:13 Laptop.local configd[51]: [0x7fc4d2614140] [m]DNS query timeout (query time = 36458.007984), [6TE]
Dec  9 07:44:13 Laptop.local configd[51]: [0x7fc4d2725f10] [m]DNS query timeout (query time = 36459.593353), [6TE]
Dec  9 07:44:13 Laptop.local UserEventAgent[42]: Captive: [CaptiveHandleRedirect:1645] Timed out on en0 (wifi-mofo), assuming online
Dec  9 07:44:14 Laptop.local UserEventAgent[42]: Captive: CNPluginHandler en0: Authenticated
Dec  9 07:44:15 Laptop kernel[0]: ARPT: 36389.610812: AirPort_Brcm43xx::powerChange: System Wake - Full Wake/ Dark Wake / Maintenance wake
Dec  9 07:44:15 Laptop kernel[0]: AppleCamIn::systemWakeCall - messageType = 0xE0000340
Dec  9 07:44:15 Laptop kernel[0]: AppleCamIn::wakeEventHandlerThread
Dec  9 07:44:14 Laptop.local WindowServer[149]: CGXDisplayDidWakeNotification [36389830831659]: posting kCGSDisplayDidWake
Dec  9 07:44:14 Laptop.local WindowServer[149]: handle_will_sleep_auth_and_shield_windows: Reordering authw 0x7ff37c1b0920(2000) (lock state: 3)
Dec  9 07:44:14 Laptop.local WindowServer[149]: handle_will_sleep_auth_and_shield_windows: err 0x0
Dec  9 07:44:16 Laptop.local Karabiner[659]: observer_NSWorkspaceScreensDidWakeNotification
Dec  9 07:44:16 Laptop com.apple.xpc.launchd[1] (com.apple.bsd.dirhelper[15463]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.bsd.dirhelper
Dec  9 07:44:16 Laptop.local identityservicesd[283]: <IMMacNotificationCenterManager: 0x7f98b2727020>: notification observer: com.apple.iChat   notification: __CFNotification 0x7f98b4b05d80 {name = _NSDoNotDisturbDisabledNotification}
Dec  9 07:44:16 Laptop.local imagent[342]: <IMMacNotificationCenterManager: 0x7fa76a61d660>: notification observer: com.apple.FaceTime   notification: __CFNotification 0x7fa76a41a2a0 {name = _NSDoNotDisturbDisabledNotification}
Dec  9 07:44:16 Laptop.local identityservicesd[283]: <IMMacNotificationCenterManager: 0x7f98b2727020>:    NC Disabled: NO
Dec  9 07:44:16 Laptop.local sharingd[315]: 07:44:16.735 : Discoverable mode changed to Contacts Only
Dec  9 07:44:16 Laptop.local sharingd[315]: 07:44:16.736 : BTLE scanning started
Dec  9 07:44:16 Laptop.local sharingd[315]: 07:44:16.736 : Scanning mode Contacts Only
Dec  9 07:44:16 Laptop.local identityservicesd[283]: <IMMacNotificationCenterManager: 0x7f98b2727020>:   DND Enabled: NO
Dec  9 07:44:16 Laptop.local imagent[342]: <IMMacNotificationCenterManager: 0x7fa76a61d660>:    NC Disabled: NO
Dec  9 07:44:16 Laptop.local identityservicesd[283]: <IMMacNotificationCenterManager: 0x7f98b2727020>: Updating enabled: YES   (Topics: (
Dec  9 07:44:16 Laptop.local sharingd[315]: 07:44:16.744 : BTLE scanner Powered Off
Dec  9 07:44:16 Laptop.local imagent[342]: <IMMacNotificationCenterManager: 0x7fa76a61d660>:   DND Enabled: NO
Dec  9 07:44:16 Laptop.local imagent[342]: <IMMacNotificationCenterManager: 0x7fa76a61d660>: Updating enabled: YES   (Topics: (
Dec  9 07:44:16 Laptop.local dirhelper[15469]: /var/folders/y1/7960pnnn1pvd9pv7qc8487rc0000gn/T/vV7PhHG: walk() error: No such file or directory
Dec  9 07:44:17 Laptop kernel[0]: USBMSC Identifier (non-unique): 000000000820 0x5ac 0x8406 0x820, 3
```

It looks like running ```tmux -vvvv``` creates some log files:
tmux-client-34820.log
tmux-out-34822.log
tmux-server-34822.log

Is this the right way to capture the error? 

I'll run like this for a while and get back to you next time it happens.

**Comment by nicm** [comment]
This is not a tmux problem. The "[server exited]" message means that the tmux server was sent SIGTERM which tells it to exit. You need to find out what on your system is killing tmux.

**Comment by phiche** [comment]
will running ```tmux -vvvv``` give some insight to this?

**Comment by nicm** [comment]
No.

**Comment by nicm** [comment]
There is no practical way for tmux itself to tell where the SIGTERM came from but you might be able to figure it out with dtrace.

**Comment by nicm** [comment]
For example:

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/kill.d.1m.html

**Comment by phiche** [comment]
Finally I get to use dtrace for something :)
Cheers.

**Comment by noahfrederick** [comment]
@phiche Please do share your findings.

**Comment by phiche** [comment]
It's a bit of a project actually :/

My probe isn't quite correct yet. I was hoping I could find a way to probe signals just to or from tmux, but I haven't figured out how to do that yet. So far this is what I've tested with, which slows the system quite a lot:
```dtrace -qn 'proc:::signal-send { printf("%s (PID=%d) sent signal %d to PID %d\n", execname, pid, arg1, args[1]->pr_pid) } proc:::signal-handle { printf("%s (PID=%d) was sent signal %d\n", execname, pid, arg0)}'```

But my main problem is this happened when my laptop was suspended:
```dtrace: processing aborted: Abort due to systemic unresponsiveness```

So I probably need to figure out how to run the probe with launchd early in the resume process.

**Comment by timotheecour** [comment]
I seem to be having the same problem, which only started < 2months ago

**Comment by nickbnf** [comment]
Yes, same thing here, on 10.11.1. This seems to have started quite recently too, a month or so ago, possibly around the same time I upgraded to 10.11.

It also happens when resuming, and seems to happen when the machine has been left sleeping for a while (e.g. overnight).

**Comment by nicm** [comment]
I expect OS X has started killing things it doesn't like when it sleeps, you should probably go and talk to Apple about this.

**Comment by philbert** [comment]
I wanted to follow up on this since others have the issue as well. 

Basically since my last comment 24 days ago (so github tells me which makes it 12th December), I seem to have stopped seeing the problem. 

I checked my changelog to my tmux.conf and there is really not much to say about it. Sorry my Dotfiles are private so I can't show you them, but here are the unexciting changes I made to tmux.conf:

I changed my prefix from C-a to C-s 
```
-set -g prefix C-a
+set -g prefix C-s
```

set utf8 on since I have a Swedish keyboard
```
+set -g utf8
+set status-utf8 on
+set-window-option -g utf8 on
```

Added a message when the config was reloaded
```
-bind-key r source-file ~/.tmux.conf
+bind-key r source-file ~/.tmux.conf \; display "tmux config reloaded!"
```

prompt for confirmation before killing a pane with C-d
```
+unbind C-d
+bind -n C-d confirm-before -p "kill-pane #P? (y/n)" kill-pane 
```

And that's it. 

All my other changes were in my vimrc, and it seems plausible that the source of the problem could actually have be coming from vim, because I was running definitely running vim in tmux when the server exited coming out of sleep.

So it really looks config related, but maybe not necessarily tmux.conf related. If the problem reappears I'll drop another update.

**Comment by aerosol** [comment]
@philbert thanks for the updates, I started experiencing the same issue just recently. FWIW I'm on 10.10.5.

**Comment by blueshogun** [comment]
I have also been experiencing this on 10.10.5.

I have begun launching separate servers for each tmux instance to see if a specific server is crashing 

    tmux -L java-dev
    tmux -L macports

, but they all exit together, always after resuming from a long sleep.  Vim may be running in e.g. java-dev, but is definitely not running in all sessions.  They all go down, so I don't think vim is at fault.

**Comment by johnsonch** [comment]
I'm seeing the same issue doesn't matter what is running or not and the number of sessions don't seem to make a difference.  I have no idea how to troubleshoot this and it's super annoying.

**Comment by philbert** [comment]
It's definitely not ideal, but I'm using these plugins that makes life a little better when tmux exists unexpectedly.
```
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
```
FWIW I only remember seeing this problem once since my last post, so it definitely hasn't gone away, but it's about as stable as the rest of my system which I've just learned to live with.

**Comment by dblarons** [comment]
Sam issue here. `tmux-resurrect` and `tmux-continuum` make it only _slightly_ less painful, but losing running local servers, Redis, vim buffers, etc. is a hassle.

**Comment by nicm** [comment]
It seems clear from the errors that I have seen that tmux is receiving SIGTERM so there is not much I can do about this, you probably need to talk to Apple.

**Comment by NigoroJr** [comment]
I don't know if this helps, but I've seen this significantly more often when I have Chrome running when going into sleep, and rarely does this happen when I have only Terminal running.

**Comment by jimeh** [comment]
I've been having the same `server exited` issue ever since I upgraded to Tmux 2.1. I've just downgraded to 2.0 to see if that might solve it, and I'll post back here in a few days/weeks when I know if it's still happening or not.

**Comment by jimeh** [comment]
Ok, so I used Tmux 2.0 for 5 days, didn't have it exit on it's own a single time, and I put my machine to sleep around 15 times during those 5 days. I upgraded to Tmux 2.1 again yesterday, and it's exited on it's own 2 out of 3 times I've put it to sleep since.

So it definitely only happens with Tmux 2.1, now if that's cause there's a bug with 2.1, or OSX treats 2.1 differently and thinks it can safely kill it while going to sleep or something, I don't know.

**Comment by tnguyen14** [comment]
I am experiencing this as well. Since @jimeh thinks that it could be a 2.1 bug, should this issue be reopened?

**Comment by nicm** [comment]
It is not a tmux bug, tmux is receiving SIGTERM and shutting down,
that's what it is supposed to do and there isn't really any way around
it.

**Comment by jimeh** [comment]
@nicm @tnguyen14 I understand that it's not a Tmux issue. However I updated to Tmux 2.2 earlier this week, and it hasn't happened since.

So it might not be an issue with Tmux itself, but my guess is that something in OSX is telling Tmux to die when the machine goes to sleep. If I recall OSX gained the ability to just kill apps with Lion, as they also added the ability for apps to save state and resume similar to how iOS apps work.

**Comment by tnguyen14** [comment]
I'll try to upgrade to 2.2 now. Is it available on homebrew yet? (It's still telling me 2.1 is the latest)

**Comment by jimeh** [comment]
@tnguyen14 I ended up hacking up the 2.1 formula myself to install 2.2 for me. The install of the bash completion script failed so I just commented that stuff out. I did end up with a `tmux` executable at v2.2 at the end at least.

Here's a gist with my formula: https://gist.github.com/jimeh/3c1dab418c022995893319809b5db525

You should be able to install it with:

    brew install https://gist.githubusercontent.com/jimeh/3c1dab418c022995893319809b5db525/raw/236362deeacdf57c8e848e138d85493099c31d3e/tmux.rb

**Comment by PatMyron** [comment]
Update: Homebrew is on tmux 2.8 now
