### ISSUE TITLE
Focusing into terminal window triggers mouse mode briefly

### ISSUE THREAD

**Issue by FractalBoy** [tmux/tmux#2310]
### Issue description

When clicking into a pane to refocus into my terminal window, mouse mode is triggered. When clicking in the pane a second time, mouse mode is not triggered (desired behavior).

I have a script that copies to my clipboard on highlight, so when attempting to refocus into the terminal, my buffer gets wiped out.

Would it be possible to treat the first click into a pane the same as subsequent clicks?

Minimal steps to reproduce:

1. `tmux -Ltest -f/dev/null new`
2. `tmux set -g mouse on`
3. Click out of window
4. Click back into window - notice that page numbers display briefly
5. Click a second time - page numbers do not display

[tmux-client-28166.log](https://github.com/tmux/tmux/files/4921748/tmux-client-28166.log)
[tmux-out-28169.log](https://github.com/tmux/tmux/files/4921749/tmux-out-28169.log)
[tmux-server-28169.log](https://github.com/tmux/tmux/files/4921750/tmux-server-28169.log)

### Required information

```
[root@vm-mreisner ~]# tmux -V && uname -sp
tmux 3.2-rc
Linux x86_64
```

Inside tmux:
```
[root@vm-mreisner ~]# echo $TERM
screen-256color
```

Outside tmux:
```
[root@vm-mreisner ~]# echo $TERM
xterm-256color
```

**Comment by nicm** [comment]
What terminal are you using? It looks like it is sending a drag mouse sequence when I presume you are focusing the window, there is no way for tmux to tell this is any different from a drag when you have the window already focused.

Does this still happen in xterm?

**Comment by FractalBoy** [comment]
I'm using PuTTY. I don't have xterm readily available to use (this is a headless VM).

**Comment by FractalBoy** [comment]
Looking into the PuTTY source code, this appears to be a bug on their end. Clicking out of the window and then back in triggers a WM_MOUSEMOVE message, which is being interpreted as a drag. This is likely a Windows idiosyncrasy that needs to be worked around.
