### ISSUE TITLE
Allow spelling "colour" as "color" in config files

### ISSUE THREAD

**Issue by verhovsky** [tmux/tmux#2313]
In config files you have to use the American spelling to specify the terminal

```
set -g default-terminal "screen-256color"
```

but then use the correct spelling everywhere else

```
set-option -g status-style fg=colour255,bg=black
```

In some of the checked-in test config files people use "color" in comments but have to use "colour" in the config variables https://github.com/tmux/tmux/search?q=color+colour&unscoped_q=color+colour. This situation causes confusion for some https://superuser.com/a/668027

I prefer the American spelling, and would like to use it in my tmux config files. It would be nice if tmux let you use either spelling and used the Queen-approved one internally

**Comment by ntnn** [comment]
Just to note - `set -g default-terminal "screen-256color"` isn't a decision by tmux devs. That's just the name of the terminfo.

**Comment by nicm** [comment]
OK do you want to open a PR?
