### ISSUE TITLE
-: Bad file descriptor on show-buffer

### ISSUE THREAD

**Issue by Luiserebii** [tmux/tmux#2314]
### Issue description

I've been having an issue where tmux would lock up suddenly and stop responding to any input (not caused by `CTRL+S`, since `CTRL+Q` wouldn't restore it). After some looking around, I located it to pressing a particular keybind I have in my `.tmux.conf`: `bind C-c run "tmux save-buffer - | xclip -sel clip -i"`. Whenever I had something selected from Copy Mode, I would use this to try to copy it into my system clipboard. So, I decided to peer into what was happening, and managed to (what I hope) isolate the issue: attempting to view this saved buffer with `show-buffer` results in `-: Bad file descriptor`.

The steps are simple to reproduce, and do not require any special configuration:
1. Enter Copy Mode with `CTRL+B` `[`
2. Select text with `CTRL+Space`
3. Copy text with `Alt+W`
4. Enter Command mode with `CTRL+B` `:` and enter `show-buffer`, which displays `-: Bad file descriptor`

I've been using tmux 3.1b, but have cloned the latest build from master (as of 70a674d) and have been able to reproduce this. I have provided logs from both sets of versions.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  * tmux 3.1b
* Platform (`uname -sp`).
  * Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
  * screen
* Logs from tmux (`tmux kill-server; tmux -vv new`).
  * [tmux-logs.zip](https://github.com/tmux/tmux/files/4943053/tmux-logs.zip)

I hope I've provided all needed information, and am not missing anything. Thank you!

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/Clipboard#common-issues---xclip1

**Comment by Luiserebii** [comment]
@nicm Ohhh, thank you... I'm embarrassed to say that I missed this, and didn't think that the issue might be something to do with xclip. Is the `-: Bad file descriptor` behavior normal? It's the only thing that seems to persist

**Comment by nicm** [comment]
Where are you running `show-buffer -`?

**Comment by nicm** [comment]
Oh never mind, you said you are using the command prompt. I'll take a look later on.

**Comment by nicm** [comment]
This is because when `show-buffer` was changed to be the same as `save-buffer -` it stopped working inside tmux. Try this please: 
[x.diff.txt](https://github.com/tmux/tmux/files/4945835/x.diff.txt)

**Comment by Luiserebii** [comment]
@nicm Applied the diff, appears to work perfectly now. Thank you!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
