### ISSUE TITLE
Compare integer values with #{<=:a,b}

### ISSUE THREAD

**Issue by sashaweiss** [tmux/tmux#2318]
* tmux version (`tmux -V`): `tmux 3.1b`
* Platform (`uname -sp`): `Darwin i386`

Is there a way to do integer/number comparison in `tmux`? Specifically, I want to have a time format string in my status line, but when the window size is small I want to show a shorter time format to give more space to my windows. When I try:
```
#{<=:#{window_width},100}
```
it seems to be doing a lexicographic comparison - and so 99 is larger than 100 etc.

Is there another operator I should try, or a method I could call for this? I couldn't find anything in the man pages.

Thanks in advance for your advice!

**Comment by nicm** [comment]
There are no numeric comparisons at the moment. You may be able to do it by matching with a regex.

**Comment by sashaweiss** [comment]
Gotcha, thanks. I put together a simple regex to match 2-digit numbers to detect <100 width windows.

`#{?#{m/ri:^[0-9][0-9]$,#{window_width}},<short_format>,<long_format>}` for posterity!

**Comment by ytian81** [comment]
It would be great to have integer comparison!
