### ISSUE TITLE
[Feature Request] overlapping panes?

### ISSUE THREAD

**Issue by ChristianTacke** [tmux/tmux#2319]
Currently, windows/panes can only be tiled in the available space. But they cannot be overlapping, and freely arranged.
If such a feature exists, it is poorly documented. And should have better advertising.

The idea is a bit like what finch (instant messenger, TUI part of pidgin) allows.
* Each pane can have a free position in the window
* Each pane can have a different size in the window
* There is an order of them. The top most is always visible fully. Lower ones maybe be obscured by upper ones.

This is basically what we have with X11 window managers as well: tiling vs. non-tiling ones.

**Comment by nicm** [comment]
This would be very complicated and invasive to do and I am not convinced there is any need for it.

**Comment by ChristianTacke** [comment]
If this is an official "non goal", then I would ask you to have a "non goal" section in your FAQ.

**Comment by nicm** [comment]
I don't think that is necessary.
