### ISSUE TITLE
[Feature Request] "allow-rename" option for pane titles

### ISSUE THREAD

**Issue by Technik-J** [tmux/tmux#2320]
Tmux has an option to disable window title rename via terminal escape sequence.
Will it be possible to implement the same option for pane titles?

**Comment by nicm** [comment]
No, I don't want this. Applications are allowed to change the pane title, it is meant to be changed by applications.

**Comment by Technik-J** [comment]
But they still will do that, only user will be able control this behavior.

**Comment by nicm** [comment]
I don't see a need for the user to be able to control it. The pane title is there for applications to set and there is no reason to prevent them.

**Comment by Technik-J** [comment]
But what if the user sets the pane title themselves and don't want applications overwriting it?

**Comment by nicm** [comment]
The point of the pane title is that applications can set it, if you want something that applications can't change then use a user option.

**Comment by Technik-J** [comment]
Ok, I see your point. Thank you.
