### ISSUE TITLE
Crash before entering customize-mode

### ISSUE THREAD

**Issue by kevinhwang91** [tmux/tmux#2321]
### Issue description

Reproduce:
1. `tmux -vv -f/dev/null`
1. `vim`
2. `prefix+C` invoke customize-mode -Z
3. crash and output `[server exited unexpectedly]`

### Required information

Please provide the following information:

* tmux version: tmux next-3.3(latest commit)
* Platform: ArchLinux Lts kernel
* $TERM inside and outside: xterm-256color, tmux-256color
* Logs from tmux:
[tmux-client-124307.log](https://github.com/tmux/tmux/files/4965293/tmux-client-124307.log)
[tmux-out-124309.log](https://github.com/tmux/tmux/files/4965294/tmux-out-124309.log)
[tmux-server-124309.log](https://github.com/tmux/tmux/files/4965295/tmux-server-124309.log)

**Comment by nicm** [comment]
Do you have a core file, if so can you show me the backtrace from gdb?

**Comment by kevinhwang91** [comment]
> Do you have a core file, if so can you show me the backtrace from gdb?

No, there is no core file. I found this issue about `tmux show -p`, I use zsh and can't reproduce with the empty config.

You can reproduce by following my above steps when the .zshrc like the below snippet:
```zsh
if  [[ -z $TMUX ]]  || [[ ! $- =~ i ]]; then
    return
fi
tmux_preexec() {
    tmux set -p '@abc' 'test'
}
autoload -U add-zsh-hook
add-zsh-hook preexec tmux_preexec

```

**Comment by nicm** [comment]
This should be fixed now, please try.
