### ISSUE TITLE
'layout-change' not available as hook

### ISSUE THREAD

**Issue by pbartyik** [tmux/tmux#2323]
### Issue description

`man tmux` states `All the notifications listed in the CONTROL MODE section are hooks (without any arguments), except %exit`

Unable to set hook for `%layout-change`  with `set-hook -g layout-change "run-shell echo blah"`

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `next-3.3`
* Platform (`uname -sp`). Linux unknown (arch)

**Comment by nicm** [comment]
It is window-layout-changed.

**Comment by pbartyik** [comment]
Thanks! can you please point me towards the direction where I can find this in tmux or the documentation so I can avoid opening up further issues for this type of questions?

**Comment by nicm** [comment]
You can look at `show-hooks -g` and `show-hooks -wg` to see a list of books.

**Comment by pbartyik** [comment]
thanks for the prompt support!
