### ISSUE TITLE
Toggle right-click and shift-right-click keybinding

### ISSUE THREAD

**Issue by blueray453** [tmux/tmux#2328]
* tmux version `tmux 3.0a`
* Platform (`Linux x86_64`).
* $TERM inside (`tmux-256color`) and outside of tmux (`xterm-256color`).

I want to have regular right-click with right-click & tmux right-click with shift-right-click. How to change the keybindings to achieve that?

**Comment by nicm** [comment]
What the terminal does with mouse buttons it doesn't pass to tmux is not something tmux can control.

**Comment by blueray453** [comment]
I have to use shift to right click or select test, when I use tmux. Otherwise, I can right click and select normally.
I used `unbind-key -T root MouseDown3Pane`, now the menu is not there but still I have to use shift-right-click.
Is there any remedy to **pressing shift** to select text or get regular right click. I mean I do not want to press the shift button.

**Comment by nicm** [comment]
Do `set -g mouse off` in .tmux.conf.

**Comment by blueray453** [comment]
I would at least like to have the scrolling. Is there any way I can have it.

**Comment by nicm** [comment]
Either tmux handles the mouse and you use Shift to bypass tmux and have the terminal handle it, or tmux doesn't handle the mouse and the terminal handles it itself. There is no way to mix.
