### ISSUE TITLE
keys bindings are working differently when tmux is executed inside terminal and used as startup command in Terminal Setting

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#2329]
### Issue description
I set a few lines inside my ~/.tmux.conf
```
bind M-s copy-mode
bind -n -Tcopy-mode M-a send-keys -X page-up
bind -n -Tcopy-mode M-z send-keys -X page-down
```
I used to set tmux as my startup command in terminal setting, when I launch my terminal, it starts tmux, the bindings are work as expected, when I `prefix-M-s` to switch into copy-mode, and then use `M-a/z` to scroll up/down.

But recently I switch to another environment (not using Konsole/Yakuake/Alacritty, and not even using the same DE), 
so I start tmux command manually, and found that in copy-mode after using `prefix-M-s` into copy-mode, `M-a/z` bindings are not working at all.

and after some time of googling, I found out changing the config to:
```
bind M-s copy-mode
bind -n -Tcopy-mode-vi M-a send-keys -X page-up
bind -n -Tcopy-mode-vi M-z send-keys -X page-down
```
works, so after I switch to the KDE Plasma, I changed my config to `copy-mode-vi` too (I use git, just sync the config file), since in KDE Plasma desktop, I use tmux as start command for my command, the `copy-mode-vi` doesn't work.

I don't know if I expressed myself clearly.

**Summary:**

If I use 
```
bind M-s copy-mode
bind -n -Tcopy-mode M-a send-keys -X page-up
bind -n -Tcopy-mode M-z send-keys -X page-down
```
and tmux as my terminal start command, `M-a/z` in copy-mode to scroll up/down are working OK.

If I use 
```
bind M-s copy-mode
bind -n -Tcopy-mode-vi M-a send-keys -X page-up
bind -n -Tcopy-mode-vi M-z send-keys -X page-down
```
and execute tmux inside terminal to launch tmux, `M-a/z` to scroll up/down in copy-mode are work OK.

Since I have to use two ways to launch tmux in two different environments, is there some kind of configuration for `M-a/z` inside copy-mode to scroll up/down working for both situations?

I tried Konsole/Yakuake/Alacritty, the issue happens for all the three terminals.

I don't know this is a bug, or it it the problem of my desktop/terminals.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.1b
* Platform (`uname -sp`).
5.7.10-1-MANJARO + KDE Plasma
* $TERM inside and outside of tmux (`echo $TERM`).
screen-256color
* terminal:
Konsole/Yakuake/Alacritty
* Logs from tmux (`tmux kill-server; tmux -vv new`).

Two kinds of logs which `M-a/z` are not working for two situations:
steps:
1. after tmux is launched, `ll /bin` to get a long buffer
2. `prefix-M-s` into copy-mode
3. `M-a/z` to scroll up/down (not working for both situations)

logs:

1. `tmux -vv new` as start command for Yakuake terminal and with config:
```
bind M-s copy-mode
bind -n -Tcopy-mode-vi M-a send-keys -X page-up
bind -n -Tcopy-mode-vi M-z send-keys -X page-down
```
[tmux-server-657610.log](https://github.com/tmux/tmux/files/4996001/tmux-server-657610.log)
[tmux-client-657607.log](https://github.com/tmux/tmux/files/4996013/tmux-client-657607.log)
[tmux-out-657610.log](https://github.com/tmux/tmux/files/4996014/tmux-out-657610.log)

2. clear the start command for Yakuake terminal and execute `tmux kill-server; tmux -vv new` inside terminal to launch tmux with the following config:
```
bind M-s copy-mode
bind -n -Tcopy-mode M-a send-keys -X page-up
bind -n -Tcopy-mode M-z send-keys -X page-down
```

[tmux-server-663090.log](https://github.com/tmux/tmux/files/4996050/tmux-server-663090.log)
[tmux-client-663088.log](https://github.com/tmux/tmux/files/4996054/tmux-client-663088.log)
[tmux-out-663090.log](https://github.com/tmux/tmux/files/4996055/tmux-out-663090.log)

**Comment by nicm** [comment]
Giving both -n and -T to `bind-key` is wrong but it doesn't make any difference here because `-T` wins.

In the first log, you are not using vi keys, so you need to bind the keys in the `copy-mode` table not `copy-mode-vi`.

In the second log, you are using vi keys, so you need to bind the keys in the `copy-mode-vi` table not `copy-mode`.

It seems likely you have `EDITOR` or `VISUAL` set to `vi` in one terminal and not in the other.

Why don't you put `set -g mode-keys vi` or `set -g mode-keys emacs` in `.tmux.conf` so you always get the keys you want?

**Comment by nicm** [comment]
Yes in one you have `EDITOR` set to `vim` and in the other to `/usr/bin/nano`.

**Comment by c02y** [comment]
> Yes in one you have `EDITOR` set to `vim` and in the other to `/usr/bin/nano`.

I don't know why `EDITOR` is set to `nano` since I set my `EDITOR` manually in my ~/.bashrc, I never set it to nano, I never use nano.

Like I said, the only things I did are:

~~~
1. after tmux is launched, ll /bin to get a long buffer
2. prefix-M-s into copy-mode
3. M-a/z to scroll up/down (not working for both situations)
~~~

I used the same ~/.bashrc, the same ~/.tmux.conf, the same terminal, the same terminal setting( except that one situation used tmux as the start command in the terminal setting and the other didn't, this is the only difference)


> Giving both -n and -T to `bind-key` is wrong but it doesn't make any difference here because `-T` wins.
> 
> In the first log, you are not using vi keys, so you need to bind the keys in the `copy-mode` table not `copy-mode-vi`.
> 
> In the second log, you are using vi keys, so you need to bind the keys in the `copy-mode-vi` table not `copy-mode`.
> 
> It seems likely you have `EDITOR` or `VISUAL` set to `vi` in one terminal and not in the other.
> 
> Why don't you put `set -g mode-keys vi` or `set -g mode-keys emacs` in `.tmux.conf` so you always get the keys you want?

Thanks, after I use the following lines, the problem is gone.
~~~
set -g mode-keys emacs
bind M-s copy-mode
bind -T copy-mode M-a send-keys -X page-up
bind -T copy-mode M-z send-keys -X page-down
~~~
The `M-a/z` are working for both situations.
