### ISSUE TITLE
Feature Request delaying commands

### ISSUE THREAD

**Issue by network-shark** [tmux/tmux#2330]
### Issue description

Hello folks,
I'm really do a lot of networking stuff and sometimes it is necessary to copy 1500 lines of configuration to a cisco cli . If the internet connection is good every command is send to the device, but if the connection have delay sometime the session beaks up or a few 100 lines are skipped. With secureCRT I'm able to delay each line for X ms to work around this problem.

Can we get that in tmux as well ?

thank you !

**Comment by nicm** [comment]
You could write a script to do this using `send-keys`. I don't think it is generally useful enough to be builtin.

**Comment by network-shark** [comment]
Ok , thank you I will check it out.
