### ISSUE TITLE
exit in zoomed paned kills the window

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#2331]
Please provide the following information:

* tmux version (`tmux -V`). -> 3.0a
* Platform (`uname -sp`). -> linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). -> xterm-256color

description:
when not zoomed, exiting one pane in a window closes just that pane
when zoomed, exiting a pane while t is zoomed closes the window and all its panes

expected: only the zoomed pane is closed and the containing window displayed

**Comment by nicm** [comment]
Does this still happen with master?

Logs?
