### ISSUE TITLE
attach to a session and cd to a path

### ISSUE THREAD

**Issue by blueray453** [tmux/tmux#2332]
* tmux version `tmux 3.0a`
* Platform (`Linux x86_64`).
* $TERM inside (`tmux-256color`) and outside of tmux (`xterm-256color`).

We figured out `tmux new-session -c $PWD` open a new tmux session in current directory.

`tmux attach -t 0 -c $PWD \; new-window \;` attach to existing session and open a new window with current directory.

What command shall I use to attached to a session and run `cd /a/particular/path` in active window's active pane. So, that when we attach to the session it is **cd**ed to the path I have provided.

**Comment by nicm** [comment]
tmux cannot change the working directory of existing child processes. You will need to ask the shell to do it (perhaps with `send-keys`).

**Comment by blueray453** [comment]
So, I guess the question becomes, how can I use the `send-keys` to tell the shell run `cd /a/particular/path` in active window's active pane. So, that when we attach to the session it is **cd**ed to the path I have provided.

**Comment by nicm** [comment]
`send-keys cd /tmp Enter`

**Comment by blueray453** [comment]
Sorry. Is it `tmux attach send-keys cd /tmp Enter` or `tmux attach  \;send-keys cd /tmp Enter`\; ?

**Comment by blueray453** [comment]
I found

```
tmux new -d -s mySession
tmux send-keys -t mySession.0 "cd /tmp" Enter
tmux a -t mySession
```

But there is a little problem. What if there is already something written in the buffer.

How can I clear the buffer before running `tmux send-keys -t mySession.0 "cd /tmp" Enter`

**Comment by nicm** [comment]
Try something like `send M-# cd /tmp Enter`.
