### ISSUE TITLE
Can not paste text copied from external text file

### ISSUE THREAD

**Issue by blueray453** [tmux/tmux#2333]
* tmux version `tmux 3.0a`
* Platform (`Linux x86_64`).
* $TERM inside (`tmux-256color`) and outside of tmux (`xterm-256color`).

Apparently I have read https://github.com/tmux/tmux/wiki/Clipboard

My Config is
```
# Clipboard tmux 3.2 and later
# set -s set-clipboard off
# set -s copy-command 'xsel -i' 

# Clipboard Prior to 3.2
set -s set-clipboard off
bind -Tcopy-mode Enter send-keys -X copy-pipe-and-cancel "xsel -i --clipboard"
bind -Tcopy-mode C-w               send -X copy-pipe-and-cancel 'xsel -i'
bind -Tcopy-mode M-w               send -X copy-pipe-and-cancel 'xsel -i'
bind -Tcopy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel 'xsel -i'
```
If I copy something in copy mode, I can paste in my text file.
However, If I copy from the text file or web browser, I can not paste it inside tmux.

What might be wrong here?

**Comment by blueray453** [comment]
by the way the following did not work

```
bind -Tcopy-mode C-w               send -X copy-pipe-and-cancel 'xsel -i'
bind -Tcopy-mode M-w               send -X copy-pipe-and-cancel 'xsel -i'
bind -Tcopy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel 'xsel -i'
```

I had to use:
```
bind -Tcopy-mode C-w               send -X copy-pipe-and-cancel 'xsel -i --clipboard'
bind -Tcopy-mode M-w               send -X copy-pipe-and-cancel 'xsel -i --clipboard'
bind -Tcopy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel 'xsel -i --clipboard'
```

**Comment by nicm** [comment]
There is no way for tmux to copy from the X clipboard automatically. You can use the `load-buffer` command to load clipboard from a file or piped from `xsel`. Or you can use `refresh-client -l` to ask the terminal to send it (if it supports it).

**Comment by blueray453** [comment]
Can you please show me how to do that with whichever method you prefer. I started tmux day before yesterday. Would be great if you could show me the steps.

**Comment by nicm** [comment]
You should be able to see what you copied with `xsel -ob` from the shell, so you can load it into tmux with `xsel -ob|tmux loadb -`.

**Comment by blueray453** [comment]
thank you very much.
