### ISSUE TITLE
Every time a character is entered, the tmux client restarts

### ISSUE THREAD

**Issue by century6** [tmux/tmux#2337]
Please provide the following information:

* tmux version: 3.1.
* Platform: Linux aarch64.
* $TERM inside and outside of tmux: xterm-256color.

description:
    In the text mode installation phase of the operating system, when tmux is started through systemd to attach to an anaconda session, entering any character will cause the tmux client to restart. But when I manually enter the shell command (tmux -u attach -t anaconda), this problem does not occur.

Logs:
    https://github.com/century6/issues_files

**Comment by nicm** [comment]
Please show the server log from starting tmux with `-vv`.
