### ISSUE TITLE
choose-tree didn't toggle pane-focus event after using for a while in a session

### ISSUE THREAD

**Issue by kevinhwang91** [tmux/tmux#2338]
### Issue description
Using `choose-tree` to select a pane could toggle pane-focus event normally at first, but after using for a while(uncertain time) It couldn't.

Although `choose-tree` worked as unexpected, `select-pane` could toggle pane-focus event as normal at that moment.

I can create a new session and it works as expected, but the old session still couldn't toggle pane-focus by using `choose-tree` to select pane.

This issue has confused me for a long time, but I couldn't reproduce it easily. Could you have a few clues and give me some tips?

It appeared randomly, so I didn't enable log beforehand.

### Required information

Please provide the following information:

* tmux version: `tmux next-3.3`
* Platform: `ArchLinux`
* $TERM inside and outside of tmux: `tmux-256color` && `alacritty`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
I don't understand what you mean.

**Comment by kevinhwang91** [comment]
I haven't exited the broken session yet, here is asciicast:

https://asciinema.org/a/351763

**Comment by nicm** [comment]
I can't reproduce this, can you trigger it again?

**Comment by kevinhwang91** [comment]
I don't know the trigger condition, but it has reproduced several times since this month.
Should I start tmux server with `-C`?

**Comment by nicm** [comment]
If you can reproduce with `-vv` and show me the log it would be good.

**Comment by kevinhwang91** [comment]
I have switched other ArchLinux PC and I can't reproduce for now.

If I can reproduce again with log in the future, I will reopen this issue.

**Comment by kevinhwang91** [comment]
Today I encounter this issue again.
I found that `tmux show-hooks` output below message, but I don't set any configuration and execute any tmux command about these hooks. 
```
client-detached[0] run-shell "kill -USR1 234089 200529 236938 223235 232617 236215 233138 217028 231701 98406 196805 235914 234906"
client-session-changed[0] run-shell "kill -USR1 234089 200529 236938 223235 232617 236215 233138 217028 231701 98406 196805 235914 234906"
session-window-changed[0] run-shell "kill -USR1 234089 200529 236938 223235 232617 236215 233138 217028 231701 98406 196805 235914 234906"
```
Other sessions without these hooks work as expected.

**Comment by nicm** [comment]
tmux didn't add these hooks?

**Comment by kevinhwang91** [comment]
I am checking my system, but no ideas how and when tmux set these hooks.

**Comment by nicm** [comment]
tmux doesn't, you have some plugin or script that does it.

**Comment by kevinhwang91** [comment]
Could tmux trace any hooks from the log?

**Comment by nicm** [comment]
Logging will show when they are set and if there are other commands around the same time and what is in the environment where the client is run which might give you a hint.

**Comment by kevinhwang91** [comment]
After `rg` under my home directory recursively, I found that this issue is caused by [ueberzug](https://github.com/seebye/ueberzug).
https://github.com/seebye/ueberzug/blob/7df7f182aaff033a6a66395d2ab2876e72e07cc3/ueberzug/layer.py#L100-L139

**Comment by kevinhwang91** [comment]
After `rg` under my home directory recursively, I found that this issue is caused by [ueberzug](https://github.com/seebye/ueberzug).
https://github.com/seebye/ueberzug/blob/7df7f182aaff033a6a66395d2ab2876e72e07cc3/ueberzug/layer.py#L100-L139
