### ISSUE TITLE
Feature to prevent text going into copy-mode buffer

### ISSUE THREAD

**Issue by smprather** [tmux/tmux#2340]
Hi Tmux--

This is an obscure request I am sure, but I may as well ask. I am in a situation where I am working with very long PWD strings. So I played around with making my shell prompt always print the PWD at the top of the terminal(pane), and then place the prompt back at the bottom (using ANSI sequences). I got it to work, but I am corrupting the copy-mode buffer in the process. I was wondering if you guys could co-opt some unused ANSI sequence to tell tmux to start ignoring text for copy mode, and then another to stop ignoring.

Thanks!
--Myles

**Comment by nicm** [comment]
You could use the pane status line?

**Comment by smprather** [comment]
Yes, I started with that, even though pane_current_path and host_short are undocumented. I found them with 'strings <path-to-tmux>' | grep ... . But I had a visual problem with always wanting to see the path *in* the pane I'm working in. Ie, I found it difficult to move my eyes to static-bottom-right. I think I just need some repetition.

set -g status-right "#{pane_current_path} #{host_short}"

You know, it doesn't matter. The "ANSI cursor moving in prompt" is wreaking havoc on tcsh. Things like <tab> completion listing and command recall are fubar. So I'm going to have to abort.

I'll stick with the tmux status line and see if I can make it work. Please close the issue.

Thanks @ncim!

**Comment by nicm** [comment]
Pane status line can be top or bottom, how is it any different from printing it at the top of the pane yourself? Are you thinking of the pane title in the bottom right of the status line?

**Comment by nicm** [comment]
~~~~
set -g pane-border-status top
set -g pane-border-fornat '#{pane_current_path}'
~~~~
If you don't like `pane_current_path` you can set a user option from inside the pane.

**Comment by smprather** [comment]
You make some great points, but nothing quite works. When I was echo'ing the pwd at the top of the terminal, I would be able to see the whole pwd due to line wrapping (I have long!!! pwd paths). My panes aren't wide enough to get the whole path. The bottom window status line is though.

[detach tmux]
% tput cols
320

Also, I find this very useful. Not just for me, but when I am screen sharing with co-workers, then can follow my pane movements easily. I get a nice bold red border all the way around my current pane.

set -g pane-active-border-style "bg=red fg=red"

But it does not work correctly when trying to put text in the border. This is close, but not quite there.

set -g pane-active-border-style "bg=red fg=white"

What I would really like is to:
* Always have a full enclosing "colored block" border around my selected pane
* Be able to insert text in the border with the same background color as the "colored blocks"
* No "line art" in the active pane border (probably requires a new option to set the style of characters used to draw the active border

But I understand that everyone wants to have something slightly different and you'd go nuts trying to support everything.

Here's a sample of how I work now (via a kitty ssh terminal).

![](https://user-images.githubusercontent.com/6503931/89466930-53aad100-d73a-11ea-81b9-23e0757a79cd.png)

**Comment by nicm** [comment]
If you install master or 3.2-rc you can change the style of the border.

You can make the pane status line the same colour as the border using `fill`.

There is no way to make it wrap, you will need to trim the path.

**Comment by smprather** [comment]
Thanks so much for your help @nicm ! It seems there is no perfect solution. The best one I have come up so far is to just make the pwd easily accessible in my normal shell work-flow.
```
alias p     'pwd'
alias cd    'cd \!* && ls && pwd'
```
