### ISSUE TITLE
ctrl scroll to zoom terminal emulator using tmux

### ISSUE THREAD

**Issue by blueray453** [tmux/tmux#2345]
I am using the following tmux keybindings to zoom using the mouse wheels.

```
# Ctrl Scroll to Zoom
bind-key -T root C-WheelUpPane { 
       run-shell "xdotool key Ctrl+plus"
}

bind-key -T root C-WheelDownPane { 
       run-shell "xdotool key Ctrl+minus"
}

bind-key -T root C-MouseDown2Pane { 
       run-shell "xdotool key Ctrl+0"
}
```

However, I am having a little issue with `Ctrl` key situated on the left hand side. It works properly with the right hand side `Ctrl` key. However, the left `Ctrl` key is acting as if I am letting go of the key. And instead of zooming, it is suddenly entering tmux copy-mode.

Yes I have checked with a new keyboard and mouse. It does not seem to be a hardware issue.

### Required information

Please provide the following information:

* tmux version (`tmux 3.0a`).
* Platform (`Linux x86_64`).
* $TERM inside and outside of tmux (`tmux-256color`).

**Comment by nicm** [comment]
Attach the server log file rather than pasting.

**Comment by blueray453** [comment]
[tmux-server-5743.log](https://github.com/tmux/tmux/files/5057494/tmux-server-5743.log)
[tmux-out-5743.log](https://github.com/tmux/tmux/files/5057495/tmux-out-5743.log)
[tmux-client-5741.log](https://github.com/tmux/tmux/files/5057497/tmux-client-5741.log)

**Comment by nicm** [comment]
There are not mouse events in this log. Are you sure you reproduced the problem?

**Comment by blueray453** [comment]
Just to be clear. I have to start tmux. Then do the actions I need to do to reproduce the bug. Then run `tmux kill-server; tmux -vv new`. Right?

**Comment by blueray453** [comment]
I started tmux. Then do the actions I need to do to reproduce the bug. Then run `tmux kill-server; tmux -vv new` from within that session. Created one file.

[tmux-client-11182.log](https://github.com/tmux/tmux/files/5057700/tmux-client-11182.log)

Again I started tmux. Then do the actions I need to do to reproduce the bug. Then run `tmux kill-server; tmux -vv new` from another terminal which is not using tmux. Created the following three files.

[tmux-client-11793.log](https://github.com/tmux/tmux/files/5057709/tmux-client-11793.log)
[tmux-out-11797.log](https://github.com/tmux/tmux/files/5057710/tmux-out-11797.log)
[tmux-server-11797.log](https://github.com/tmux/tmux/files/5057711/tmux-server-11797.log)

**Comment by nicm** [comment]
There is no mouse in this file either. You need to do `tmux kill-server` then `tmux -vv new`, then reproduce the problem, then exit tmux (`tmux kill-server` again or `exit` at the shell), then send me the server log.

**Comment by blueray453** [comment]
This time followed your steps.
Reproduced the bug.
Used both left and right `ctrl` key, so that you can compare.

[tmux-client-12487.log](https://github.com/tmux/tmux/files/5057775/tmux-client-12487.log)
[tmux-out-12490.log](https://github.com/tmux/tmux/files/5057776/tmux-out-12490.log)
[tmux-server-12490.log](https://github.com/tmux/tmux/files/5057778/tmux-server-12490.log)

**Comment by blueray453** [comment]
Yes, this time **tmux-server-12490.log** has the mouse events.

**Comment by nicm** [comment]
There is too much in this and it is hard to tell what is what, could you do this:
- `tmux kill-server; tmux -vv new`
- Scroll up once with the left ctrl key.
- Type `aaa`.
- Scroll up once with the right ctrl key.
- Exit tmux.
That way I can tell the difference between left and right by looking for `aaa` and also if you only do each once there is no extra keys.

**Comment by blueray453** [comment]
I am attaching the log with your instruction.

[tmux-client-14958.log](https://github.com/tmux/tmux/files/5057993/tmux-client-14958.log)
[tmux-out-14961.log](https://github.com/tmux/tmux/files/5057994/tmux-out-14961.log)
[tmux-server-14961.log](https://github.com/tmux/tmux/files/5057995/tmux-server-14961.log)

With left `ctrl` key I have scroll a little more to create the issue. I scrolled as less as I could.

**Comment by blueray453** [comment]
Just for your convenience I have `echo "start showing left ctrl behaviour"` Then created bug. Then `echo "start showing right right behaviour"`. Then showed normal behaviour.

[tmux-client-16582.log](https://github.com/tmux/tmux/files/5058047/tmux-client-16582.log)
[tmux-out-16584.log](https://github.com/tmux/tmux/files/5058048/tmux-out-16584.log)
[tmux-server-16584.log](https://github.com/tmux/tmux/files/5058049/tmux-server-16584.log)

**Comment by nicm** [comment]
This seems like a problem with your terminal or WM. When you press left ctrl it is only sending one ctrl mouse event and then one without. With right ctrl it sends several with ctrl.

With left ctrl:
~~~~
1597162046.195485 /dev/pts/2: mouse input (SGR): \033[<80;36;7M
1597162047.085486 /dev/pts/2: mouse input (SGR): \033[<64;29;6M
~~~~
Buttons are first 80 which is 64+16 which means wheel and ctrl. Then 64 which is just wheel, no ctrl.

With right ctrl:
~~~~
1597162071.874460 /dev/pts/2: mouse input (SGR): \033[<80;32;8M
1597162080.656265 /dev/pts/2: mouse input (SGR): \033[<80;27;10M
~~~~
So just 64+16. There are a few more then as well with wheel down (81) instead of wheel up (80).

**Comment by nicm** [comment]
Does this still happen in xterm?

**Comment by blueray453** [comment]
I just tested. It also happens with xterm.

**Comment by nicm** [comment]
What if you try a different WM?

**Comment by blueray453** [comment]
Currently I am using gnome-terminal

**Comment by blueray453** [comment]
I just tested. alacritty also has the same issue.

**Comment by nicm** [comment]
Right but you are using them all in Gnome?

**Comment by blueray453** [comment]
Please give me some time to check how to change the window manager. Let me change that, and then I will In-Shah-Allah report back to you.

**Comment by blueray453** [comment]
I think if I try to change the WM in Linux Mint, it might crush.

Can you please check whether the keybindings work in your machine or not.

If it works in your machine then I might create an issue in Linux Mint's (or appropriate) repo.

**Comment by nicm** [comment]
Yes it works for me but I only have a MacBook.

**Comment by blueray453** [comment]
Then whom shall I report this issue?
