### ISSUE TITLE
Enabling UTF-8 through config file

### ISSUE THREAD

**Issue by i0x71** [tmux/tmux#2347]
Hi
Is there any way to enable UTF-8 from config file, instead of running "tmux -u" ?

There used to be an option "set -g utf8 on" but its gone now.
Thanks

* tmux 3.1b
* Linux unknown

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-utf-8

**Comment by i0x71** [comment]
Fixed by setting to proper locale.
Thanks
