### ISSUE TITLE
resolve key conflict temporarily

### ISSUE THREAD

**Issue by zchrissirhcz** [tmux/tmux#2348]
### Issue description

I'm using `C-x` (control + x) as prefix, which is also the "exit key" for nano editor. I can't exit nono editor by pressing `C-x` or `C-x C-x`. I don't like to change my prefix key. **How can I exit nano editor elegantly (i.e. not using `kill` or `pkill` command for nano).**

To reproduce:
step1: prepare a ubuntu 16.04, or other linux system that there is `nano` editor no it.

step2: create new tmux session
```bash
tmux new -s test
```

step3: yank nano command in that tmux session
```bash
nano
```

step4: how to exit nano now?

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
2.1

* Platform (`uname -sp`).
Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).
xterm-256color

**Comment by krader1961** [comment]
The usual solution is to bind the key to send the prefix. For example, this is from my *~/.tmux.conf*:

```
# Use [ctrl-space] rather than [ctrl-A] because the latter conflicts with
# emacs key bindings. And I find [ctrl-space] is easier to type on my various
# keyboards than [ctrl-b].
set-option -g prefix C-Space
unbind C-b
bind C-Space send-prefix
```

Obviously replace `C-Space` with `C-X`. However, you might want to consider using `C-Space` because it is less likely to ever need to be passed to a program running inside a tmux session.

**Comment by zchrissirhcz** [comment]
@krader1961 Great! Thanks for your shared config, it works for me.
