### ISSUE TITLE
why can't i install tmux on windows

### ISSUE THREAD

**Issue by AshutoshSajan** [tmux/tmux#2349]
i want to use tmux on windows. is there a way to install this on windows?

**Comment by iphelf** [comment]
As far as I know, you need a unix-like environment to be able to build and run tmux. Here are several ways to achieve this:
- Install [MSYS2](https://www.msys2.org/), and then install the tmux package with its package manager `pacman`. 
- Similar as the previous one, you can use [Cygwin](https://cygwin.com/index.html) to install tmux package.
- Install [Git for windows](https://gitforwindows.org/), and then build tmux from source ([tmux for windows](https://github.com/hongwenjun/tmux_for_windows)) in git bash.
- Windows Subsystem for Linux. Refer to [tmux on Windows 10](https://leanpub.com/the-tao-of-tmux/read#appendix-windows-bash) section of *The Tao of tmux*.
