### ISSUE TITLE
Cannot copy text to clipboard with mouse on Terminal.app

### ISSUE THREAD

**Issue by Blosberg** [tmux/tmux#2350]
**Background info** (Following instructions from [here](https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md) )
```
$uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 3.1b
screen
```
(after manually entering `$export TERM=screen` explicitly inside tmux); outside of tmux `$echo $TERM` produces `xterm-256color`. System: OSX 10.15.5; I completely removed my `.tmux.conf` file and entered only the single command: `set -g mouse on` and reproduced the problem.

**Log files:**
[tmux-client-41021.log](https://github.com/tmux/tmux/files/5090476/tmux-client-41021.log)
[tmux-out-41023.log](https://github.com/tmux/tmux/files/5090477/tmux-out-41023.log)
[tmux-server-41023.log](https://github.com/tmux/tmux/files/5090478/tmux-server-41023.log)

**The problem:**
Thank you for this resource. Unfortunately, I can't copy text with the mouse. When I hold shift+ mouse click and drag there is no highlighting appearing at all. I've tried with option, alt, and essentially all other combionations of plausible keys. From the current tmux terminals there is really no way at all to get text onto the system clipboard. Is there some new binding? Thanks for any help you can offer.

**Comment by nicm** [comment]
What terminal are you using?

**Comment by Blosberg** [comment]
Default OSX terminal Version 2.10 (433)

**Comment by nicm** [comment]
Terminal.app does not appear to have a bypass key for the mouse, you will need to choose one of:

- Use tmux's mouse support (`set -g mouse on`) and configure it to set the system clipboard using `pbcopy`, see https://github.com/tmux/tmux/wiki/Clipboard#external-tools.

- Turn off mouse support in tmux and use the terminal's native copy.

- Use a different terminal that does have a bypass key, such as iTerm2.

**Comment by Blosberg** [comment]
> Use a different terminal that does have a bypass key, such as iTerm2.

Thanks for the answer. ok, I'll take door #3. The Resulting behaviour is _almost_ perfect, except mouse-over automatically dumps to system clipboard without waiting for any confirmation (like `command+c `or `shift` or anything). 

That's a bit overly eager, as it might lead to unintentional over-writing of the clipboard. Is there an option to allow for mouse-highlighting (without touching the clipboard), but clipboard-copying upon some extra step (e.g. shift, or command+c, or something like that)? Thanks again for your help and for maintaining this great resource.

**Comment by nicm** [comment]
If you are using the terminal copy you will need to look at the terminal options to configure it rather than tmux.

**Comment by Blosberg** [comment]
> you will need to look at the terminal options to configure it rather than tmux.

There is an specific option for "Copy to pasteboard on selection" which, when de-selected, makes the desired change in regular terminal mode. Within tmux, however, this option is apparently being overwritten such that selection automatically prompts copying to pasteboard. The only other option is to disable access to clipboard entirely, but that prevents any possibly copying.

Anyway, the main issue is 99% solved, I'll just have to be careful to only highlight when I'm sure I have nothing important in the clipboard. Thanks for your help.

**Comment by nicm** [comment]
tmux has no control over what the terminal does when you hold down option to bypass it.
