### ISSUE TITLE
Mapping to resize pane left | Prefix + CTRL + h is not working - All the other mappings work

### ISSUE THREAD

**Issue by danushk** [tmux/tmux#2352]
### Title says it - All the mappings including h key other than this mapping works following is the gist of tmux.conf

https://gist.github.com/danushk/dd2880d4a46998755881e2da5e60333b

* tmux version (`tmux 3.1b`).
* Platform (`Lubuntu 20.04`).
* $TERM inside and outside of tmux .
    inside - screen-256color:: command not found
    outside - xterm-256color: command not found
* Logs from tmux (`tmux kill-server; tmux -vv new`).
   https://gist.github.com/danushk/19e3b31d0e865dc8b05486b608fe1ff1#file-tmux-log

**Comment by nicm** [comment]
What does `stty -a` show outside tmux?

**Comment by danushk** [comment]
Hi nicm - thanks for reply - here it is

dan@acer2:~$ stty -a
speed 38400 baud; rows 32; columns 134; line = 0;
intr = ^C; quit = ^\; erase = ^H; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S;
susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc

**Comment by nicm** [comment]
Your system (or terminal emulator) is configured to use C-h for Delete rather than C-h. Either configure it to use Delete (^?), bind Delete in tmux instead of C-h, or use a different key.

**Comment by danushk** [comment]
Thanks nicm - without your help - i would have been in a total mess.
