### ISSUE TITLE
RFE: last pane flag

### ISSUE THREAD

**Issue by altblue** [tmux/tmux#2353]
I'd like to be able to visually mark _the last (previously active) pane_ in order to help determining where _“move to the previously active pane”_ combo (`‹prefix›+;`) lands.

Mimicking `window_last_flag`, we could use a new `pane_last_flag` to affect panes status lines, e.g.:
```
tmux set-option -w -g pane-border-format "… #{?pane_last_flag,⎗,} …"
```
Thanks!

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/5121657/x.diff.txt)

**Comment by altblue** [comment]
> Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/5121657/x.diff.txt)

Thank you, Nicholas, using `tmux set-option -w -g -a pane-border-format "#{?pane_last,⎗,}"` in a build incorporating your patch does exactly what I mean.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
