### ISSUE TITLE
[Feature Request] Add style for copy_cursor_word and copy_cursor_line

### ISSUE THREAD

**Issue by kevinhwang91** [tmux/tmux#2354]
### Issue description

Similar to highlight under keyword and cursor line in vim, It will improve efficiency in copy mode.

**Comment by nicm** [comment]
I have no idea what this means.

**Comment by kevinhwang91** [comment]
![image](https://user-images.githubusercontent.com/17562139/91058652-4b6bf480-e65b-11ea-874e-79855fc8ce7c.png)

`split` is the `keyword` under the current cursor, `bind s split-window -v` is the cursor line.

**Comment by nicm** [comment]
I don't have time to do this now, I've added it to the todo list, thanks.
