### ISSUE TITLE
[Feature Request] display-panes can jump to more than 9 panes

### ISSUE THREAD

**Issue by phongvcao** [tmux/tmux#2355]
Hi,

Is there anyway I can configure `display-panes` to be able to jump to panes larger than pane 9 (e.g. pane 10, 11, 12, etc.)? Right now I can show all panes using `display-panes`, but can only jump to pane [1-9] by pressing the [1-9] number in the `display-panes` mode.

If only a single key-press is allowed, can this be implemented such that it also accept characters such as [a-zA-Z], and let users specify which keys to use to display/number panes (to avoid conflicts with existing users' keybindings, especially in copy-mode-vi)? There's a Vim plugin [vim-choosewin](https://github.com/t9md/vim-choosewin) for jumping vim splits that implements this idea.

Monitors are getting higher resolutions nowadays and it's not uncommon to have 15-20 panes open on a single monitor. Back in the day maybe 9 panes are max but now my 4k monitors can easily handle 20 panes in a window and still be able to see & code in all of them. I hope this feature would be implemented since our dev team love Tmux. Thanks for the great work!

**Comment by nicm** [comment]
Try this please which allows you to use `M-a` to `M-z` for higher pane indexes, like in choose mode: [x.diff.txt](https://github.com/tmux/tmux/files/5136483/x.diff.txt)

I'm not completely happy about how it displays the key, it might be better if they were just below the pane index rather than in the top left.

**Comment by phongvcao** [comment]
So I have to patch this in tmux? Thanks for the patch but can we bake this into next tmux version?

**Comment by nicm** [comment]
If you don't test it then it won't go in.

**Comment by phongvcao** [comment]
Of course I'm testing it. Just wondering if it would go in or not. I'm compiling it right now.

**Comment by nicm** [comment]
Yes if it works although I might move the position of the key text, I will take another look at that later, but let me know if the patch works OK for you.

**Comment by nicm** [comment]
It is too late for the next release but it will go into the one after that.

**Comment by phongvcao** [comment]
@nicm It works fantastically. One question though: Can you change the display-panes number above 10 to actually be letters? Is that possible? If one would like to use [a-z] he/she would have to do quick conversion from Dec (base-10) to Hex(abcdef). Even at that point, for keys that are more than 16 (e.g. 20), that would be some hard conversion. So internally tmux still use numeric to represent the panes, but the display of the panes for "display-panes" would have an option to opt for letters instead of numbers? This letter-display mode is for displaying only - nothing changes underneath.

**Comment by nicm** [comment]
No I don't want to add a full alphabet of letters as well as the numbers.

**Comment by phongvcao** [comment]
I think for the sake of conformity and user-friendliness, we can probably eliminate the meta key? I think if we can press [1-9], we can probably press [a-z] by itself without meta right? I think after looking at the code, I don't think this would interfere with vi-mode somehow.

**Comment by phongvcao** [comment]
If implementing 26 chars is too much work, how about whenever display-panes is invoked, tmux echo this line to the message prompt:

```
Key: a: 10 ; b: 11 ; c: 12 ; ... ; z: 35?
```

If a person needs to use more than 9 panes, he/she must have a wide enough monitor to show this list of keys in the message prompt.

**Comment by phongvcao** [comment]
Maybe this prompt is better:

```
Pane -> Key: [1-9] -> [1-9] ; 10 -> a ; 11 -> b ; 12 -> c ; ... ; 35 -> z?
```

**Comment by nicm** [comment]
Yes, I used meta to match choose mode but we can probably do without it here actually. I don't what to show it in the status line but I think it would be better to show the key above or below the pane index so they are together. I'll take a look either tomorrow or next week.

**Comment by phongvcao** [comment]
that's awesome. Thanks nicm for your help. I don't think human eyes would ever get above 4K so this solution would probably last a lifetime lol.

**Comment by nicm** [comment]
Try this instead please: [y.diff.txt](https://github.com/tmux/tmux/files/5140578/y.diff.txt)

**Comment by phongvcao** [comment]
yeah this patch is great! Thank you for your work.

This is definitely good enough for me I'll probably use this version from now on lol.

On a side note, why do you choose to right-aligned text instead of center or left-aligned? Maybe center alignment at the bottom would be faster to spot.

**Comment by nicm** [comment]
Left aligned looks funny when you use it with the `1` character which only takes up the right column, the key ends up 6 columns to the left in empty space.

**Comment by phongvcao** [comment]
I think maybe a center-aligned would be the best (if possible & you have time). This patch is great.

**Comment by phongvcao** [comment]
`display-panes` is probably among the most convenient thing about Tmux... I use it a lot.

**Comment by nicm** [comment]
I think centre would look funny with numbers that start with a 1 as well.

**Comment by phongvcao** [comment]
how about removing the parentheses ()? I think just displaying the letter would be good. Maybe also replacing it with capital letter (A, B) so it looks bigger? Later on if we want to use capital letters for real, we can add "S-A" (stand for Shift-A)? What do you think?

**Comment by nicm** [comment]
I think it is too hard to see without the () maybe but I will take another look. The keys in tmux are always called `a` and `A` not `A` and `S-A`.

**Comment by phongvcao** [comment]
maybe adding spaces between the () and a? (e.g. `( a )`)? Just my suggestion.

**Comment by nicm** [comment]
This removes the brackets. I like it in the bottom right below the number. I'm not sure if we can do anything to make it easier to see, I tried making it bright but the problem with that is it then doesn't match the numbers, and people can configure that themselves anyway. The default blue is quite dark on many terminals, perhaps we should change it to brightblue.

This also fixes a bug with cursor alignment. [z.diff.txt](https://github.com/tmux/tmux/files/5141469/z.diff.txt)

**Comment by phongvcao** [comment]
yeah this one looks great. I think it's perfect now. Thanks @nicm for the work.

**Comment by nicm** [comment]
Applied now, thanks!
