### ISSUE TITLE
Is there an API for the large text in the middle of the display when `:clock-mode`? 

### ISSUE THREAD

**Issue by keiohtani** [tmux/tmux#2356]
Hi there, 

Is there an API to interact with the large text that shows up in the middle of the screen when you run either `:clock-mode` or `:display-panes`? I wanted to display a custom text in the middle of the pane, but I don't see any information about it. 

![image](https://user-images.githubusercontent.com/35276788/91358188-62782700-e7c0-11ea-9717-e75c190bc0e3.png)

Thanks.

**Comment by nicm** [comment]
No there is not, and it only has numbers anyway.

**Comment by keiohtani** [comment]
When clock-mode-style is set to 12, it also shows either AM or PM as well. 

![image](https://user-images.githubusercontent.com/35276788/91442465-e1607480-e83f-11ea-9977-5f30fc145a8b.png)

Could exposing this API be a possible feature enhancement? It would be useful to replace some of the messages displayed with the display-message command. 



Thanks.

**Comment by nicm** [comment]
So you want to be able to show the word MAP? Or PAM?

I don't want to add a full set of letters. You might be able to find a separate program to draw them.

**Comment by keiohtani** [comment]
I don't know MAP nor PAM, but it sounds like the font for the clock-mode is not in the fonts on the computer but generated differently then? I wouldn't ask to add a whole set of letters for this, but yes, if you could lead me in the right direction for adding another program to render texts, that would be great. Thanks.

**Comment by nicm** [comment]
It has 0-9 : A P M, not any other characters.

What about figlet? http://www.figlet.org/

**Comment by keiohtani** [comment]
That should be fine. As long as it shows custom texts, the look doesn't matter. How does the integration with tmux look like? 

Thanks.

**Comment by nicm** [comment]
Dunno, just run it in a pane? Or in a popup if you are using master?

**Comment by keiohtani** [comment]
I will check that out. Thanks.
