### ISSUE TITLE
[portability] marking functions that don't return

### ISSUE THREAD

**Issue by krader1961** [tmux/tmux#2357]
FWIW, I was surprised to see the build warnings below on macOS using clang 11.0.3 (masquerading as gcc). Those warnings wouldn't be emitted if not for a compatibility issue with macOS. The unexpected warning is because the macOS system *sys/cdefs.h* header does `#define __dead` if not already defined. That keeps the tmux definition of `__dead` from being used. Note that macOS also does `#define __dead2 __attribute__((__noreturn__))`. Although I can't vouch for when those definitions were introduced.

Since GCC based systems do not define either pseudo-keyword, AFAICT, the simplest change to make that attribute work on macOS is to change *compat.h* to use `__dead2` rather than `__dead`.

```
options.c:160:8: warning: variable 's' is used uninitialized whenever switch case is taken
      [-Wsometimes-uninitialized]
                case OPTIONS_TABLE_STRING:
                     ^~~~~~~~~~~~~~~~~~~~
options.c:164:11: note: uninitialized use occurs here
                return (s);
                        ^
options.c:161:8: warning: variable 's' is used uninitialized whenever switch case is taken
      [-Wsometimes-uninitialized]
                case OPTIONS_TABLE_COMMAND:
                     ^~~~~~~~~~~~~~~~~~~~~
options.c:164:11: note: uninitialized use occurs here
                return (s);
                        ^
options.c:136:9: note: initialize the variable 's' to silence this warning
        char    *s;
                  ^
                   = NULL
```

**Comment by nicm** [comment]
I looked at this before but I'm not sure it is worth the hassle of potentially breaking various macOS versions just to hide some warnings. Especially since Apple are very likely to change this in some other stupid way in future.

**Comment by krader1961** [comment]
Changing `__dead` to `__dead2` (or just `_dead`, a single leading underscore) is very unlikely to cause problems on macOS, Linux, or other BSD systems. And doing so means that building tmux on current versions of macOS won't emit spurious warnings. Alternatively, just change the declaration to include an initializer.

**Comment by nicm** [comment]
Really? What release did they add __dead2 in?

**Comment by krader1961** [comment]
> What release did they add __dead2 in?

I don't see why that matters. If someone is building tmux on a macOS version that predates the introduction of the `__date2` symbol it will still compile and work. Albeit with the warning we're seeing on current macOS versions. And your point applies to GNU platforms. Or, for that matter, any other BSD platform.

**Comment by nicm** [comment]
We can't use __dead2 without knowing whether it will compile on older versions. I suppose we could do:
~~~~
#ifdef __dead2
#undef __dead
#define __dead __dead2
#elif !defined(__dead)
#define __dead
#endif

**Comment by krader1961** [comment]
> We can't use __dead2 without knowing whether it will compile on older versions.

You seem to be concerned that older versions of gcc or clang that we still want to support might have defined a `__dead2` symbol.  That is certainly possible; albeit unlikely. Regardless, the solution is the same as the current tmux definition of `__dead`. That is, predicate the tmux definition on whether the platform has already defined a `__dead2` symbol. Change this in *compat.h*

```
#ifndef __dead
#define __dead __attribute__ ((__noreturn__))
#endif
```

to

```
#ifndef __dead2
#define __dead2 __attribute__ ((__noreturn__))
#endif
```

Then use `__dead2` in the handful of places that currently use `__dead`. I was not implying in my earlier comments that `__dead` should be an alias for `__dead2`. In fact, given that the compilers supported by tmux might define either, neither, or both of these symbols it might be better to use something like `__tmux_noreturn`.

**Comment by nicm** [comment]
No I am concerned that older macOS do not have __dead2. We're not changing tmux to use __dead2 outside of compat.h because OpenBSD uses __dead.

**Comment by krader1961** [comment]
> because OpenBSD uses __dead

Are you saying that OpenBSD (whether old or current version) defines `__dead` to be something other than `__attribute__ ((__noreturn__))`? Why does that matter unless the compiler on that platform does not support `__attribute__((...))`?

I'm a grey beard who has been programming for a living since 1979 and appreciate the challenges of making software like this work on a broad range of platforms with a minimum of problems -- including build warnings. My proposal should do nothing other than suppress bogus warnings on any modern system; including a recent version of OpenBSD. Is the issue that old platforms tmux still wants to support do not recognize `__attribute__ ((__noreturn__))` but might provide an equivalent definition for `__dead` in its standard headers?

**Comment by nicm** [comment]
OpenBSD uses __dead for attribute noreturn. This is what tmux uses because it is an OpenBSD project. So __dead is staying as it is - the only changes we can make are in compat.h for portable tmux.

**Comment by nicm** [comment]
TBH warnings on non-free platforms like macOS are very low down my list of concerns, we can hide them but only if it can be done in compat.h and without making unnecessary work (ie without breaking older macOS versions and without cluttering up the tmux codebase).

**Comment by krader1961** [comment]
> without breaking older macOS versions

I don't grok that since the current mechanism presumes every platform, other than OpenBSD apparently, supports `__attribute__ ((__noreturn__))` or ignores it. And, AFAIK, every version of macOS that still needs to be able to build tmux from source supports that mechanism.

**Comment by nicm** [comment]
No, you are getting two different things mixed up.

Every compiler that tmux supports either handles __attribute__ ((__noreturn__). or does not define __GNUC__ so we do not use it.

But not every platform has __dead2 and we don't know if older macOS versions have it. So we can't rely on __dead2 existing.

And we can't change tmux to use __dead2 outside of compat.h because OpenBSD uses __dead for __attribute__ ((__noreturn__)) so that is what tmux uses.

It looks like Apple got __dead2 from FreeBSD rather than inventing it, although it looks like FreeBSD rather more sensibly do not define __dead away but leave it undefined.

Something like this would be the best solution probably: [x.diff.txt](https://github.com/tmux/tmux/files/5166466/x.diff.txt)

**Comment by krader1961** [comment]
> Something like this would be the best solution probably: x.diff.txt

That works for me; that is, building with that patch eliminates the unexpected warning. Thus keeping someone like myself from proposing adding an unneeded var initialization.

**Comment by nicm** [comment]
Applied now, thanks!
