### ISSUE TITLE
show-environment hangs while loading plugins via TPM

### ISSUE THREAD

**Issue by harshasrisri** [tmux/tmux#2360]
### Issue description
`tmux show-environment -g TMUX_PLUGIN_MANAGER_PATH` hangs while loading tmux plugins via TPM. 
Without TPM in the picture, I could reproduce it loading a null `tmux.conf` using `strace`

My setup is: `macOS -> Alacritty -> ssh -> Ubuntu 20.04 -> tmux`
Here is my typical [.tmux.conf](https://github.com/harshasrisri/dotRC/blob/master/dot/tmux.conf)

I've raised an issue on TPM too: https://github.com/tmux-plugins/tpm/issues/175

### Required information
Inside Tmux launched with `tmux -Ltest -f/dev/null new`
```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 3.1b
screen
```
Outside Tmux
```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 3.1b
xterm-256color
```

### Logs
[tmux-client-1121870.log](https://github.com/tmux/tmux/files/5152828/tmux-client-1121870.log)
[tmux-server-1121872.log](https://github.com/tmux/tmux/files/5152829/tmux-server-1121872.log)
[strace.tmux.log](https://github.com/tmux/tmux/files/5152856/strace.tmux.log)
tmux-out-*.log is empty

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by harshasrisri** [comment]
No it didn't. 
[tmux-client-3850309.log](https://github.com/tmux/tmux/files/5157189/tmux-client-3850309.log)
[tmux-out-3850311.log](https://github.com/tmux/tmux/files/5157190/tmux-out-3850311.log)
[tmux-server-3850311.log](https://github.com/tmux/tmux/files/5157191/tmux-server-3850311.log)

**Comment by nicm** [comment]
It doesn't still happen or it does still happen?

**Comment by harshasrisri** [comment]
Sorry about the unclear reply. I couldn't reproduce the issue with master. I can use tmux + TPM as expected. Standalone invocations of `tmux show-environment` didn't block like earlier, too.

**Comment by nicm** [comment]
OK great, if you can make sure it still works with 3.2-rc also it would be helpful.

**Comment by harshasrisri** [comment]
Just tried 3.2-rc and it looks good, too. Couldn't reproduce this issue.

**Comment by nicm** [comment]
OK great stuff, 3.2 will be released in a few months. Thanks!
