### ISSUE TITLE
[Suggestion] tmux a -t 1 -> tmux a1

### ISSUE THREAD

**Issue by EaseTheWorld** [tmux/tmux#2361]
1. attach-session is the most used command for me(maybe others, too).
This morning, I typed 'tmux a -t 1' as usual, I thought 'tmux a1' would do the job faster.
This could be applied to others command which requires '-t target-session' or other primary digit option.
AFAIK, no tmux command includes digits which makes it easier.

2. If above can be accepted, 'tmux a#' could list all current sessions so user can selects.
this will help much less typing. 'tmux ls(CR)' && 'tmux a -t 1(CR)' becomes 'tmux a#(CR)1(CR)'
'#'  could be other character as long as it doesn't conflicts with shell.

### Required information
* tmux version (`tmux -V`). : 3.1b(but applicable for all)
* Platform (`uname -sp`). : Redhat 7 Linux(but applicable for all)

**Comment by nicm** [comment]
You could add command-alias for this.

**Comment by EaseTheWorld** [comment]
Thank you. I didn't know command-alias.
I tried tmux set -s command-alias[0] a0='a -t 0', it works nicely.
