### ISSUE TITLE
[Feature Request] Multi Cursor Sessions

### ISSUE THREAD

**Issue by casonadams** [tmux/tmux#2362]
### Description
Currently tmux supports multi window sessions
#### Create session
```
tmux new -s shared
```
#### Connect with multi window session
```
tmux new -s pair -t shared
```

### Feature request
Connect to an existing tmux session with individual cursors
#### Create session
```
tmux new -s shared
```
#### Connect with multi cursor session (Example)
```
tmux attach -t shared -m
```

This would allow clients to navigate the same window / pane with individual cursors

**Comment by nicm** [comment]
You can use `tmux attach -factive-pane` but you need master or 3.2-rc.

**Comment by casonadams** [comment]
This is awesome thank you!  

Are there plans for multi cursor support in a single pane?  As an example pair programming in `vi` with 2+ cursors?

**Comment by nicm** [comment]
No there is no way for that to work.

**Comment by casonadams** [comment]
Okay so I think we are good to close this one out yeah?
