### ISSUE TITLE
escape sequence misbehaving

### ISSUE THREAD

**Issue by pbartyik** [tmux/tmux#2363]
### Issue description

From shell within tmux ```echo -e "\033]52;c;$(base64 <<< hello)\a"``` gets `hello` into clipboard on remote system connecting to tmux.
However when doing <prefix>```:run 'echo -e "\033]52;c;$(base64 <<< hello2)\a"'``` just prints the output

### Required information

Please provide the following information:

* tmux version `next-3.3`
* Platform `Arch`
* $TERM inside `tmux-256color` and outside `alacritty`

**Comment by nicm** [comment]
Programs run with `run-shell` are not connected to a terminal.

**Comment by pbartyik** [comment]
I have `set -s set-clipboard on` in tmux.conf, also the terminal client supports it. When I do `tmux set-buffer` it does not get propagated back to the remote system. Is this only supposed to work from copy mode?

**Comment by nicm** [comment]
Yes, OSC 52 is only sent for buffers created from copy mode (or by an application inside tmux).

**Comment by pbartyik** [comment]
is there a way to trigger this externally with a tmux command?

**Comment by nicm** [comment]
No there is no way at the moment, we could add a flag to `set-buffer` to do it.

**Comment by pbartyik** [comment]
that would be awesome. if not a flag, then a named buffer like `tmux set-buffer -b osc52` ot avoid possible issues?

**Comment by nicm** [comment]
No it would need to be a flag, because you would need to be able to specify which client to use. I'll take a look at some point.

**Comment by nicm** [comment]
Try this please: 
[x.diff.txt](https://github.com/tmux/tmux/files/5161387/x.diff.txt)

You can give `-w` to `set-buffer` or `load-buffer`. `-t` can be used to set the clipboard for a particular client, if not given it will follow the normal rules to pick the best client if any.

**Comment by pbartyik** [comment]
built as per https://github.com/tmux/tmux#from-version-control , added `git apply x.diff.txt` before building. `tmux set-buffer -w` yields `unknown option -- w`

Am I missing something obvious?

**Comment by nicm** [comment]
Did you install or are you running from the build directory? Did you make sure to restart tmux entirely so the new build is running?

**Comment by pbartyik** [comment]
sorry, was running `tmux set-buffer -w asd` instead of `./tmux set-buffer -w asd`.
works like a charm, although i haven't tested `load-buffer` as I have no need for it.

**Comment by nicm** [comment]
Applied now. Thanks!

**Comment by pbartyik** [comment]
That was fast, thanks!
