### ISSUE TITLE
tmux - Python training script gets killed automatically 

### ISSUE THREAD

**Issue by naren-mohan** [tmux/tmux#2364]
When I try to run a python script to train my deeplearning model via tmux, after sometime, the process gets killed with just a simple "Killed" console output. 
The code runs properly without tmux. 

After doing a bit of research, I found out that my python script is deliberately getting killed by OOM-killer.
Does this mean that the allocated memory to tmux session is less than required? And if so, how will I be able to do it? 

OS : Ubuntu 16.0.4 AWS EC2 instance
tmux 2.1

**Comment by nicm** [comment]
Are you sure your ulimits are the same inside and outside tmux?

**Comment by krader1961** [comment]
Another possibility is you've configured tmux with an unreasonably large window history (see the `history-limit` option) and your python program is writing a large amount of text to the terminal. That could theoretically cause the tmux process to consume enough memory that, in combination with the memory used by your python program, it triggers an OOM condition.

**Comment by naren-mohan** [comment]
Hey, sorry guys. My bad. My dataset was too much for the code to handle. It actually didn't work when I tried to run without tmux as well. (I ran earlier with different dataset and assumed that it would work with this dataset as well. Sorry. My bad.) Thanks to both of you. My problem is now solved and I'm able to run the script now.
