### ISSUE TITLE
split-window -h -l 80 != 80 columns

### ISSUE THREAD

**Issue by mmjo** [tmux/tmux#2365]
### Issue description

split-window -h -l 80 is not honoring the number of columns
config attached
[tmuxresize.txt](https://github.com/tmux/tmux/files/5163591/tmuxresize.txt)

tmux -L foo -vv -f tmuxresize.txt attach
[tmux-client-10589.log](https://github.com/tmux/tmux/files/5163607/tmux-client-10589.log)
[tmux-out-10592.log](https://github.com/tmux/tmux/files/5163608/tmux-out-10592.log)
[tmux-server-10592.log](https://github.com/tmux/tmux/files/5163611/tmux-server-10592.log)

### Required information

* tmux version (`tmux -V`).
tmux next-3.3
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
inside: screen
outside: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

Regards, Mike

**Comment by nicm** [comment]
You are running `attach-session` after splitting the window and that will resize the layout to fit the terminal size.

**Comment by mmjo** [comment]
The attach-resizing is a bit unexpected.
Since it is the same terminal, so same size.

Is it the case that the 'new-session -A -D' in the config file does not attach the client?

**Comment by mmjo** [comment]
Aha, so the command line attach has no terminal yet.
Or do you mean that the new-session -A -D does not have a terminal? (but the -D is not detaching)

I want tmux to start up with one window with two panes, one of it having 80 columns,
But does all of this means that any sizes i specify in the config file will always be undone?

**Comment by mmjo** [comment]
Ah, i see then, why that is not going to work.

Thanks for the explanation!
