### ISSUE TITLE
question on tmux show -g

### ISSUE THREAD

**Issue by pbartyik** [tmux/tmux#2367]
`tmux.conf` 
```
set -g @thumbs-regexp-1 'Vlan\d+'
set -g @thumbs-regexp-2 '[abcdef\d]{4}\.[abcdef\d]{4}\.[abcdef\d]{4}'
```
`tmux show -g | grep regexp`
```
@thumbs-regexp-1 Vlan\\d+
@thumbs-regexp-2 "[abcdef\d]{4}\.[abcdef\d]{4}\.[abcdef\d]{4}"
```

Why does tmux add `"` sometimes and not the other times?
Is there a way to enforce one or the other behaviour (no `"` around entries or all entries with `"`)?

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `latest git` `next-3.3`
* Platform (`uname -sp`). `Arch`
* $TERM inside `tmux-256color` and outside `alacritty`

**Comment by nicm** [comment]
"s are added if there are special characters in the string. Space # ' " ; $ { } are special characters.
