### ISSUE TITLE
When tmux support Windows?

### ISSUE THREAD

**Issue by Shicheng-Guo** [tmux/tmux#2368]
When tmux support Windows? Thanks.

### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
tmux will never support Windows natively, you can use Cygwin.

**Comment by shivanshu3** [comment]
@nicm If I make changes to add native support for Windows, would you guys consider accepting them? Or do you intentionally want to keep it posix only for easier maintenance and stuff?

**Comment by nicm** [comment]
If you can keep the changes mainly confined to compat/ and compat.h and not put `#ifdef WIN32` all over the main codebase then I'm likely to accept it. But I am not sure how easy it will be, although I don't really know anything about Windows terminal applications. Does the Windows console support VT100 escape sequences and are Windows applications running inside tmux able to send them to tmux? libevent works on Windows, but how are you going to pass control of the console from tmux client to server?

**Comment by shivanshu3** [comment]
@nicm Windows console has a pretty advanced API. I'm familiar with some subset of it, but not everything.

https://docs.microsoft.com/en-us/windows/console/console-functions

I'll play around with the tmux codebase in a couple weeks when I get some time and then get back to you with my findings.
