### ISSUE TITLE
[Feature Request] allow retroactively attaching a note to already specified keybindings, without binding a new command (bind -N "note" <key>)

### ISSUE THREAD

**Issue by mstr3336** [tmux/tmux#2369]
### Issue description

I upgraded to 3.1b because I was excited about the utility afforded by `bind-key`.

I was very excited to see this addition, as in previous versions `list-keys` always gave me a headache and I had been contemplating rolling my own cheatsheet widget w/ inline docstring parsing [a la regolith's remointoire](https://github.com/regolith-linux/remontoire/blob/master/src/arg_parser.vala) .

This being said, I don't really like the idea of having to update every single one of my tmux installations in order for them to be compatible with my configuration files, should I choose to annotate my keybindings, especially given that this is more of a presentation detail than new functionality.

I was hoping to annotate each of my bindings on the condition that tmux > 3.1, as in

```bash
## Toggle mouse
bind m set -g mouse on  \; display 'Mouse: ON'
bind M set -g mouse off \; display 'Mouse: OFF'

# There's no command being specified!
if-shell -b '[ "$(echo "$TMUX_VERSION >= 3.2" | bc)" = 1 ]' \
  "bind-key -N 'Toggle mouse mode ON' m; \
  bind-key -N 'Toggle mouse mode OFF' M"

# And so on
```

*Side note: am I correct in thinking that as of tmux 3.0, can i express the above as follows?*

```sh
if-shell -b '[ "$(echo "$TMUX_VERSION >= 3.2" | bc)" = 1 ]'  {
  bind-key -N 'Toggle mouse mode ON' m
  bind-key -N 'Toggle mouse mode OFF' M
}

```

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/5181713/x.diff.txt)

**Comment by mstr3336** [comment]
thank you for supplying this! 
I will try it when I'm back at my workstation.
 
If all goes well with this, do you anticipate mainlining it to a future release? cheers

**Comment by mstr3336** [comment]
By the way - I checked out master & applied this. 

It all worked as expected, but I realized I wasn't sure whether I was supposed to apply this to a release, so I checked out 3.1b & tried it and it didn't work there. 

All seems fine on master though, I was able to add a note to some bindings pre-defined in my `tmux.conf`, and they come up with `list-keys -N`. 
Thanks!

**Comment by nicm** [comment]
Applied now, thanks!
