### ISSUE TITLE
Upstream terminfo value that advertises 24-bit color support

### ISSUE THREAD

**Issue by bchallenor** [tmux/tmux#2370]
Some applications, like Vim, allow you to force the output of 24-bit color regardless of what the terminal advertises. But other applications, like Emacs, rely on the terminal advertisement.

There is an unreleased [Emacs patch](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=41846) to add support for `COLORTERM`, but in the meantime, as I understand it, the only way to get Emacs to output 24-bit color is through terminfo.

With `TERM=tmux-256color`, Emacs is limited to 256 colors. Setting `TERM=xterm-direct` inside tmux causes Emacs to output 24-bit color. However, the tmux FAQ [recommends](https://github.com/tmux/tmux/wiki/FAQ) a tmux-specific `TERM` value, which currently means either `tmux` or `tmux-256color`.

Would you consider upstreaming a terminfo value of `tmux-direct` as well? Or do you consider `tmux-256color` with `COLORTERM` to be the way forward?

I'm not sure how you would want to define it, but the following works for me with Emacs:

```
$ cat tmux-direct
tmux-direct|tmux with direct-color indexing,
        use=xterm+direct, use=tmux,

$ tic -x -o ~/.terminfo tmux-direct

$ infocmp -x tmux-256color tmux-direct
comparing tmux-256color to tmux-direct.
    comparing booleans.
        RGB: F:T.
    comparing numbers.
        colors: 256, 16777216.
    comparing strings.
        setab: '\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m', '\E[%?%p1%{8}%<%t4%p1%d%e48\:2\:\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&%d\:%p1%{255}%&%d%;m'.
        setaf: '\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m', '\E[%?%p1%{8}%<%t3%p1%d%e38\:2\:\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&%d\:%p1%{255}%&%d%;m'.
```

**Comment by bchallenor** [comment]
Relevant Debian/ncurses discussion: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895754

**Comment by nicm** [comment]
Thanks. Can you give me a diff against ncurses misc/terminfo.src and I will talk to @ThomasDickey about it?

Also probably worth including `setal` as in mintty-direct, tmux uses `Setulc` but `setal` is already there so we might as well change to use it.

I wouldn't recommend using COLORTERM.

**Comment by nicm** [comment]
`setal` in the mintty entry is set to `setal=\E[5%p1%dm` but this is wrong - SGR 5x is not used for underline colours. Only the entry in mintty-direct is correct.

**Comment by bchallenor** [comment]
Sorry for the delay on that patch. Is this what you were looking for?

```
$ cat tmux-direct.patch
--- a/misc/terminfo.src
+++ b/misc/terminfo.src
@@ -7679,6 +7679,11 @@ tmux|tmux terminal multiplexer,
 tmux-256color|tmux with 256 colors,
        use=xterm+256setaf, use=tmux,

+tmux-direct|tmux with direct-color indexing,
+       setal=\E[%?%p1%{8}%<%t5%p1%d%e58\:2\:\:%p1%{65536}%/%d\:%p1
+             %{256}%/%{255}%&%d\:%p1%{255}%&%d%;m,
+       use=xterm+direct, use=tmux,
+
 #### Dvtm

 # dvtwm 0.15
```

**Comment by nicm** [comment]
Thanks, will take a look next week.

**Comment by nicm** [comment]
This looks good and works for me, @ThomasDickey what do you think, could you add this? Thanks.

**Comment by ThomasDickey** [comment]
it looks okay (no apparent inconsistencies).

**Comment by nicm** [comment]
This was added in ncurses 20201003 (https://github.com/mirror/ncurses/commit/349761f30e7fc0b4bf2718f7fc3da34e09ea6735). Thanks!
