### ISSUE TITLE
pane-focus-in couldn't be triggered in copy-mode

### ISSUE THREAD

**Issue by kevinhwang91** [tmux/tmux#2372]
### Issue description

When a pane is in `copy mode`, switching panes from other panes will not trigger the `pane-focus-in` event.
I'm not sure if this is related to `pane-focus-in` because tmux triggers `pane-focus-in` after exiting `copy-mode`.

If this is normal logic, how can I immediately make tmux trigger event when I switch to the pane which is in `copy mode`.

### Required information

Please provide the following information:

* tmux version: `tmux next-3.3`
* Platform: `ArchLinux`
* $TERM inside and outside of tmux: `tmux-256color` && `alacritty`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Does this fix it?
~~~~
--- server-client.c     28 Oct 2020 10:09:10 -0000      1.362
+++ server-client.c     30 Oct 2020 08:28:32 -0000
@@ -1590,10 +1590,6 @@ server_client_check_pane_focus(struct wi
        if (wp->window->active != wp)
                goto not_focused;

-       /* If we're in a mode, we're not focused. */
-       if (wp->screen != &wp->base)
-               goto not_focused;
-
        /*
         * If our window is the current window in any focused clients with an
         * attached session, we're focused.

**Comment by kevinhwang91** [comment]
Yes, It works as expected!

**Comment by nicm** [comment]
Great stuff, applied to OpenBSD now, will be in GitHub later. Thanks!
