### ISSUE TITLE
[Feature request] Allow -F format specifier for list-keys output

### ISSUE THREAD

**Issue by matthewstrasiotto** [tmux/tmux#2374]
### Issue description

HI there. 
I'd like to be able to parse list-keys more easily, and I wonder if you'd be open to allowing it to emit JSON, or some other structured text format?

**Comment by nicm** [comment]
No JSON. We could add -F to list-keys so you could specify the format, like the other list commands.

**Comment by mstr3336** [comment]
as in `list-keys -F "format_string"`? That would be acceptable to me.

What would the specifiers be? "#{table} #{keys} #{modifiers??} #{note} #{command}" ?

**Comment by nicm** [comment]
Try this please: [tmux-list-keys-F.diff.txt](https://github.com/tmux/tmux/files/5400906/tmux-list-keys-F.diff.txt)

The default format is:
~~~~
#{?key_list_notes,#{?key_note,#{p/#{key_prefix_width}:#{key_prefix}} #{p/#{?key_list_all,#{key_width},#{key_width_notes_only}}:key} #{key_note},#{?key_list_all,#{p/#{key_prefix_width}:#{key_prefix}} #{p/#{key_width}:key} #{key_command},}},bind-key #{?key_repeat_all,#{?key_repeat,-r,  },} -T #{p/#{key_table_width}:key_table} #{p/#{key_width}:key} #{key_command}}
~~~~
But you will probably only want something like `#{key_table} #{key} "#{key)note}" "#{key_command}"`:
~~~~
$ tmux lsk -Tprefix -F'#{key_table} #{key} "#{key_note}" "#{key_command}"'
prefix C-b "Send the prefix key" "send-prefix"
prefix C-o "Rotate through the panes" "rotate-window"
prefix C-z "Suspend the current client" "suspend-client"
prefix Space "Select next layout" "next-layout"
...
