### ISSUE TITLE
tmux in detached mode (-d) displays cluttered output

### ISSUE THREAD

**Issue by brewme** [tmux/tmux#2379]
### Issue description
When I run the ffuf (which has live status updates) tool in tmux detached mode, the output is not the same as if I attach to an tmux session and run then the ffuf tool.

After running: `tmux -vv  new -d './ffuf -u https://example.de/FUZZ -w ~/Borderland/Resources/Content-Discorvey/20k.txt'` I get the follownig cluttered output: 
<img width="769" alt="ffuf" src="https://user-images.githubusercontent.com/69966449/93016460-9c6b6a80-f5c1-11ea-9002-2afe7356591d.png">

So normally the Progress: [8/100001] appears but then gets replaced with the new progress e.g. [49/100001] so the user know how much fuzzing has already be done. So when running without the -d flag tmux workes correctly in the sense that one only sees one line of proress instead of many.

My endgoal is to run several tmux sessions with different ffuf targets. So: Is there flag how to run tmux -d but with the same display options as when you run it in not-detached mode? (My assumtion is that tmux shows the cluttered output because it ignores ANSI control chars, which might make sense for other use-cases when starting detached tmux-sessions from a script.)

I had the same problem with the tool dirsearch too (https://github.com/maurosoria/dirsearch).

(https://stackoverflow.com/questions/63793818/how-to-run-tmux-in-detached-mode-d-without-getting-cluttered-output)

### Required information
Please provide the following information:
➜  ffuf git:(master) tmux -V
tmux 3.1b
➜  ffuf git:(master) uname -sp
Darwin i386 # os x 10.15.6
➜  ffuf git:(master) echo $TERM
xterm-256color # outside tmux
➜  ffuf git:(master) echo $TERM
screen # inside tmux

[tmux-client-3096.log](https://github.com/tmux/tmux/files/5213957/tmux-client-3096.log)
[tmux-out-3098.log](https://github.com/tmux/tmux/files/5213958/tmux-out-3098.log)
[tmux-server-3098.log](https://github.com/tmux/tmux/files/5213959/tmux-server-3098.log)

**Comment by nicm** [comment]
This program does not adapt its output to the terminal width. When you create a session with `-d` you will get the default 80x24 size, and it is attempting to print around 100 characters, so it will wrap.

Try adding `-x 200` to `new-session`.

**Comment by brewme** [comment]
This solves this! Thanks a lot!!
