### ISSUE TITLE
On Linux, many TTY-related functions cannot be found as of 38cc1a18

### ISSUE THREAD

**Issue by ericpruitt** [tmux/tmux#238]
As of commit 38cc1a18, I cannot build tmux on Debian Linux 8 (Jessie). The compilation process fails with "undefined reference to tigetflag", "... setupterm", "... tparm" and other TTY-related functions. If I revert 38cc1a18, tmux builds without issue. Here are the last lines of the build process:

    gcc  -I/home/developer/static-tmux/tmux-src/../libevent/build/include -D_GNU_SOURCE -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wnested-externs -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes    -L/home/developer/static-tmux/tmux-src/../libevent/build/lib              -L/home/developer/static-tmux/tmux-src/../libevent/build/include -static  -o tmux alerts.o arguments.o attributes.o cfg.o client.o cmd-attach-session.o cmd-bind-key.o cmd-break-pane.o cmd-capture-pane.o cmd-choose-buffer.o cmd-choose-client.o cmd-choose-tree.o cmd-clear-history.o cmd-command-prompt.o cmd-confirm-before.o cmd-copy-mode.o cmd-detach-client.o cmd-display-message.o cmd-display-panes.o cmd-find.o cmd-find-window.o cmd-if-shell.o cmd-join-pane.o cmd-kill-pane.o cmd-kill-server.o cmd-kill-session.o cmd-kill-window.o cmd-list-buffers.o cmd-list-clients.o cmd-list-keys.o cmd-list-panes.o cmd-list-sessions.o cmd-list-windows.o cmd-list.o cmd-load-buffer.o cmd-lock-server.o cmd-move-window.o cmd-new-session.o cmd-new-window.o cmd-paste-buffer.o cmd-pipe-pane.o cmd-queue.o cmd-refresh-client.o cmd-rename-session.o cmd-rename-window.o cmd-resize-pane.o cmd-respawn-pane.o cmd-respawn-window.o cmd-rotate-window.o cmd-run-shell.o cmd-save-buffer.o cmd-select-layout.o cmd-select-pane.o cmd-select-window.o cmd-send-keys.o cmd-set-buffer.o cmd-set-environment.o cmd-set-hook.o cmd-set-option.o cmd-show-environment.o cmd-show-messages.o cmd-show-options.o cmd-source-file.o cmd-split-window.o cmd-string.o cmd-swap-pane.o cmd-swap-window.o cmd-switch-client.o cmd-unbind-key.o cmd-wait-for.o cmd.o colour.o control.o control-notify.o environ.o format.o grid-view.o grid.o hooks.o input-keys.o input.o job.o key-bindings.o key-string.o layout-custom.o layout-set.o layout.o log.o mode-key.o names.o notify.o options-table.o options.o paste.o proc.o resize.o screen-redraw.o screen-write.o screen.o server-client.o server-fn.o server.o session.o signal.o status.o style.o tmux.o tty-acs.o tty-keys.o tty-term.o tty.o utf8.o window-choose.o window-clock.o window-copy.o window.o xmalloc.o xterm-keys.o osdep-linux.o  compat/imsg.o compat/imsg-buffer.o compat/closefrom.o   compat/strlcat.o compat/strlcpy.o  compat/fgetln.o compat/fparseln.o compat/getopt.o   compat/vis.o compat/unvis.o compat/strtonum.o    compat/reallocarray.o  -lutil -lncurses  -L/home/developer/static-tmux/tmux-src/../libevent/build/lib -levent -lncurses  -lutempter -lresolv
    cmd-string.o: In function `cmd_string_expand_tilde':
    /home/developer/static-tmux/tmux-src/cmd-string.c:346: warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    /home/developer/static-tmux/tmux-src/cmd-string.c:332: warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    tty-term.o: In function `tty_term_string1':
    /home/developer/static-tmux/tmux-src/tty-term.c:572: undefined reference to `tparm'
    tty-term.o: In function `tty_term_string2':
    /home/developer/static-tmux/tmux-src/tty-term.c:578: undefined reference to `tparm'
    tty-term.o: In function `tty_term_ptr1':
    /home/developer/static-tmux/tmux-src/tty-term.c:584: undefined reference to `tparm'
    tty-term.o: In function `tty_term_ptr2':
    /home/developer/static-tmux/tmux-src/tty-term.c:591: undefined reference to `tparm'
    tty-term.o: In function `tty_term_find':
    /home/developer/static-tmux/tmux-src/tty-term.c:409: undefined reference to `setupterm'
    /home/developer/static-tmux/tmux-src/tty-term.c:446: undefined reference to `tigetnum'
    /home/developer/static-tmux/tmux-src/tty-term.c:469: undefined reference to `cur_term'
    /home/developer/static-tmux/tmux-src/tty-term.c:469: undefined reference to `del_curterm'
    /home/developer/static-tmux/tmux-src/tty-term.c:439: undefined reference to `tigetstr'
    /home/developer/static-tmux/tmux-src/tty-term.c:453: undefined reference to `tigetflag'
    collect2: error: ld returned 1 exit status
    Makefile:687: recipe for target 'tmux' failed

Please let me know if you need any more information to look into this.

**Comment by nicm** [comment]
Full build log including configure please.

**Comment by ericpruitt** [comment]
I am building tmux statically using this repository: https://github.com/ericpruitt/static-tmux . However, tmux still fails to build if I revert my custom changes.

Logs:
- [config.log.txt](https://github.com/tmux/tmux/files/60239/config.log.txt)
- [build-log.txt](https://github.com/tmux/tmux/files/60240/build-log.txt)

**Comment by nicm** [comment]
You need this for --enable-static to work:
`````
diff --git a/configure.ac b/configure.ac
index 824b4ab..82e8a45 100644
--- a/configure.ac
+++ b/configure.ac
@@ -18,6 +18,7 @@ AM_PROG_CC_C_O
 AC_PROG_CPP
 AC_PROG_EGREP
 AC_PROG_INSTALL
+PKG_PROG_PKG_CONFIG

 # Default tmux.conf goes in /etc not ${prefix}/etc.
 test "$sysconfdir" = '${prefix}/etc' && sysconfdir=/etc
@@ -47,6 +48,7 @@ AC_ARG_ENABLE(
 )
 if test "x$found_static" = xyes; then
        LDFLAGS="$LDFLAGS -static"
+       PKG_CONFIG="pkg-config --static"
 fi

 # Is this gcc?

**Comment by ericpruitt** [comment]
Thanks. I have confirmed that I am able to build tmux with your most recent change.
