### ISSUE TITLE
Question about history buffer 

### ISSUE THREAD

**Issue by network-shark** [tmux/tmux#2387]
Hey , 

I came across a tmux behaviour I would like to discuss if I get that right. 

Setup:
One pane , four splits ,
 1 vim 
 2 salt master ( deamon ) 
 3 salt minion 
 4 command line 

(2) I'm running a deamon (saltstack ) master  in foreground and debug mode. 

(4) I send some commands to the server and the master/ deamon answered like it should .

(2 ) Than I got a problem and need to search something in the debug log. I scrolled back in history using ( CTRL + B + page up ) .  

(1) Fixed my code.

(4) Ran the command again against the server , but nothing happened. 

(2) Than I saw that the pane where I ran the server was still in history mode . I quit history mode and than I imidiatley got a response.... (4 ) & (3)

My question does tmux pause a deamon running in forground mode or how is this behaviour explainable ?

**Comment by nicm** [comment]
Yes but this was changed after 3.1, try building 3.2-rc or master.

**Comment by network-shark** [comment]
Thank you @nicm for your answer and all the work you are doing to make tmux even more awesome :-)
