### ISSUE TITLE
The cursor after search next is unexpected in master branch.

### ISSUE THREAD

**Issue by kevinhwang91** [tmux/tmux#2391]
### Issue description

Reproduce:
1. Run below shell script;
2. Enter `copy-mode` and then make the cursor go to the top line of script output;
3. Press `/` and input `^[0-9]+\s*$`;
4. Cursor jump doesn't match the highlighted line.

```sh
for (( i = 0; i < 20; i++ )); do
    echo $i
    echo '  ==================  '
done
```

The cursor jumps to the highlighted line as expected in other stable releases.

Btw, I think this issue is caused by https://github.com/tmux/tmux/commit/df7fbcd7a5a775586522380a70530721d1f2c151, I'm not sure that you have seen my request about enabling that feature only in `mode-keys` is emacs. 

Force vimer to adapt to emacs's regex searching behavior is not a good idea.

### Required information

Please provide the following information:

* tmux version: `tmux next-3.3`
* Platform: `ArchLinux`
* $TERM inside and outside of tmux: `tmux-256color` && `alacritty`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
I think `\s` is a GNU extension, do you see the same thing with `^[0-9]+[[:space:]]*$`?

**Comment by kevinhwang91** [comment]
Yes, the result is the same.

`search-reverse`  works as expected by using both `^[0-9]+\s*$` and `^[0-9]+[[:space:]]*$` pattern.

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/5260038/x.diff.txt)

**Comment by kevinhwang91** [comment]
Yes, this issue is gone after patching.

I miss the vim behavior when using `search-forward`.

**Comment by nicm** [comment]
OK great, applied now, thanks. This is complicated and I don't want to have two behaviours.

**Comment by kevinhwang91** [comment]
It seems that the cursor behavior after using `select` and `search`  is so Inconsistent in copy mode.

The cursor in  `select` behavior is included, and in `search-forward` is excluded.

This behavior also breaks another behavior. After `search-forward`, the cursor is at the end of the matched but excluded.

If the user wants to jump back the search result by using `search-backward`, must press double `N` for now.

**Comment by nicm** [comment]
Yes if you reverse the search direction the cursor will move to the start or end of the match first.
