### ISSUE TITLE
[Feature request] Protect input for password

### ISSUE THREAD

**Issue by mcasashi-aso** [tmux/tmux#2394]
### Issue description

Hello. This is for the Mac, and I'm not sure if it's the same for other environments.

When we use `sudo`, we need to enter the password. When we do this, the password is not shown, nor the number of characters in the password. This is good for social engineering, but not for the system.

[Keycastr](https://github.com/keycastr/keycastr) makes it easy to find out what you keyed in. However, if you type a password without using tmux in the Mac's standard Terminal, you'll find that Keycastr doesn't show it.

I don't know how to implement this feature, and I think there is a difference in what Terminal and tmux can implement, so it may not be feasible. However, I will tell you that it may be detrimental to security and I hope that this feature will be added.

**Comment by nicm** [comment]
Sudo does not show the password, if you use a separate program to records the keystrokes there is little tmux can do about that. Perhaps the program has a special case to detect terminal.app, you will need to ask them.

**Comment by mcasashi-aso** [comment]
I see.

One thing I would point out is that I don't think Keycastr is detecting Terminal.app.
The [NSSecureTextField](https://developer.apple.com/documentation/appkit/nssecuretextfield) and the text field (input) of a web page with type set to password are not captured by keycastr as well as Terminal. However, Terminal.app doesn't use them, so it must be calling a function that protects the input prepared somewhere. It would be nice if I could figure that out and call it from tmux as well.

**Comment by nicm** [comment]
How would tmux know when to call it? sudo should be calling it.
