### ISSUE TITLE
Enhance update-environment to understand globs

### ISSUE THREAD

**Issue by stdedos** [tmux/tmux#2397]
### Issue description

By reading https://github.com/tmux/tmux/blob/a0fee328bf7d2cefe047f3911e7e29955f14a75a/cmd-set-environment.c, https://github.com/tmux/tmux/blob/63390d2dd65e3294d958b579fbdff365a5eabe76/environ.c, it appears to me that the `update-environment` should be an explicit list of environment variables to update.

I was wondering if it would make sense to accept globs, e.g. `set-option -ga update-environment " LC_*"`
(I understand that the example is a dummy, as probably `LC_*` does not change _that_ frequently.)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Sure, go for it.

**Comment by nicm** [comment]
Try this please: [tmux-update-environment-fnmatch.diff.txt](https://github.com/tmux/tmux/files/5326691/tmux-update-environment-fnmatch.diff.txt)

**Comment by stdedos** [comment]
Is there a way to update an existing tmux server with a new version and keep all my terminals, or do I need to start a new instance of _something_? (In my use cases, there is 1-1 relationship between PC-and-"tmux server instance")

**Comment by nicm** [comment]
You will need to restart the server entirely (`tmux kill-server`) or start an entirely new one by giving a different socket name (`tmux -Ltest new`).

**Comment by stdedos** [comment]
I think I did exactly what I was supposed to (I patched against 3.1b), but it does not seem to be working.

However, at the same time, I cannot/don't know how to see whether what I applied has been taken in. I used `show-options -gw/-s/(plain)`, but there is not a single `update-environment` key (let alone _the_ updated key).

**Comment by nicm** [comment]
What did you put in .tmux.conf?

**Comment by stdedos** [comment]
As on the issue: `set-option -ga update-environment " LC*"`

**Comment by nicm** [comment]
Works for me:
~~~~
$ tmux set-option -ga update-environment " LC*"
$ tmux show -g update-environment
update-environment[0] DISPLAY
update-environment[1] KRB5CCNAME
update-environment[2] SSH_ASKPASS
update-environment[3] SSH_AUTH_SOCK
update-environment[4] SSH_AGENT_PID
update-environment[5] SSH_CONNECTION
update-environment[6] WINDOWID
update-environment[7] XAUTHORITY
update-environment[8] LC*
$

**Comment by stdedos** [comment]
Okay, if I use `tmux show -g update-environment` I see the value added.

And, also I had some logical error in my test (I tried to re-use the pane to check, which meant I would forever fork from an "old environment").

LGTM, verified as working. Thank you!

**Comment by nicm** [comment]
Applied now, thanks!
