### ISSUE TITLE
[Feature request] Support systemd socket activation

### ISSUE THREAD

**Issue by msharov** [tmux/tmux#2398]
There is currently a race condition in trying to attach to the same session of tmux from two processes; there is no way to guarantee that only one tmux is launched. This happens, for example, when launching tmux as a persistent service and then attaching to it from an xterm. Both of these occur at login and while X startup provides some delay between the invocations, it is not a hard guarantee.

The problem could be solved if tmux could be started by socket activation. Systemd would launch tmux when the socket is accessed and pass its file descriptor via sd_listen_fds. Tmux could use the fd name, obtained using sd_listen_fds_with_names, as the name of the session. Subsequent starts would connect to the socket, set in the environment, instead of launching a new tmux, thus eliminating race conditions.

**Comment by nicm** [comment]
You should not be able to end up with two tmux listening on the same socket path. Please show logs (both servers and the clients which start them) from this happening.

**Comment by msharov** [comment]
You are right, I didn't think of that. Just specifying the socket would be sufficient to prevent two tmux servers being launched. (No, I did not observe this happening and would not know how to set it up to catch such a timing error)

However, this does not entirely solve the problem, because it is still undetermined which invocation launches the server. I want to always end up with the tmux service running as the server and with the xterm running the client, but if the xterm-invoked tmux got to locking the socket first, it would fork off the server and the systemd tmux service would end up as a client, connected to an unparented server process.

With socket activation, tmux server would explicitly be launched as such, using the -D option (which you ought to document on the man page), and the xterm activation would only be able to launch the client. This way the tmux server process would be properly supervised by systemd and there would be no ambiguity about when and by what it is launched.

**Comment by nicm** [comment]
You don't need to specify the socket, you should not be able to get two servers running which think they are listening on the same socket whether or not you specify the socket.

I think there are a couple of things you can do:

- Set it up so that X is always started after tmux, there may be some way to say that it is a dependency. Most init systems have some way to express dependencies.

- Wrap your xterm tmux in a script that stops it starting tmux, for example something as simple as `while ! tmux has 2>/dev/null; do sleep 1; done; tmux new` would probably work.

**Comment by msharov** [comment]
systemd certainly does have dependency management. Unfortunately it does not work here because a systemd service is considered started immediately after it is forked off, while the tmux control socket is not created until a little later. One way to solve this would be to launch tmux as type notify and use sd_notify API in tmux to tell systemd when it is really ready.

This is a common problem, of course; X server also takes time to start as does a window manager, and there is no way to detect when either is done. With socket activation the critical task of creating the socket is done first and the service handling it can be launched later while connections to the socket can queue up and wait.

Either socket activation or sd_notify would work here; I suggested socket activation because I though it would be less invasive. After looking at the code, I'm not so sure. tmux `main` does not have a clear separation between launching the server and connecting the client. To setup a server socket from a passed in fd, I would expect to have to untangle that first, moving the first half of `client_main` into `main`, with `client_connect` split in two, clearly delineating the server and client code paths. I do think that would make the code cleaner, but it is quite a bit of work. On the other hand, with `sd_notify`, the solution is just one call to `sd_notify (1, "READY=1")` after the `listen` in `server_create_socket`. In conjunction with the -D flag, this would make tmux a usable systemd service, with dependencies working as they should.

So do you think either option would be acceptable?

**Comment by nicm** [comment]
I think this is a problem that should be solved outside tmux, not by modifying tmux with platform-specific code.

**Comment by nicm** [comment]
Why don't you write a little helper program that calls sd_notify and have tmux run it by doing something like `run "/path/to/my/helper"` at the end of .tmux.conf? It is guaranteed that the server will be started by that point.

**Comment by msharov** [comment]
Because ugly hacks like that merely serve to illustrate the need for a universal "I'm started" indicator for processes. If we have to write a custom launcher for every service, we may as well just go back to initscripts. But I'm obviously asking the wrong project here; tmux is apparently a part of BSD, and you fellows don't like new features over there. I'll just write a launcher as you suggest.

**Comment by nicm** [comment]
You aren't suggesting a universal "I'm started" indicator though, you're suggesting something that will only work on one platform - and for a subset of users - not a general solution. It isn't even part of libc on Linux! I don't want to add systemd-specific code to tmux that as far as I can tell is only serving to work around limitations in systemd that can be solved with one line of sh.

**Comment by nicm** [comment]
What you could do, is add it into existing nonportable/Linux-only code, for example we have osdep-darwin.c which has a bunch of stuff Apple require to make their tools work inside tmux, you could add a similar daemon-linux.c and anything extra you want when the server daemonizes in there, that would work. This is how I was going to do the systemd goo to stop it killing tmux but that became unnecessary, there is an issue somewhere with a patch.

**Comment by msharov** [comment]
systemd service API is not in any way linux-specific. It consists of checking environment variables and socket fds in the process. The code is not even a library; you just copy it into your project. sd_notify is ~30 lines of code. There is no specific dependency on systemd or linux and it is permissively licensed.

Secondly, this is not about working around limitations of systemd; it is a limitation of tmux - the inability to tell when the service is actually started. Sure, BSD doesn't need this feature, but that's because BSD doesn't have a service supervisor at all, just initscripts. If you wrote one, you'd want to be able to know when a service started too.

**Comment by nicm** [comment]
What platforms apart from Linux does systemd work on?

You can tell when tmux is started - you run a command like `tmux has` and it will tell you.

**Comment by nicm** [comment]
Well, the fact that systemd isn't portable doesn't actually matter. I don't mind adding one or two lines of code, preferably in compat/ and but I'm not going to add 30 lines.

**Comment by nicm** [comment]
It just seems a bit silly to do it for something that should be so easy to solve without changing tmux...

**Comment by nicm** [comment]
Well saying that I don't mind 30 lines if it is in compat, I just don't want the main codebase littered with nonportable stuff.

**Comment by msharov** [comment]
My point was that the sd-daemon API is not systemd-specific. It is not nonportable outside of linux, merely unimplemented there. If you want to write a service supervisor, there is every reason to adopt this existing notification API (as well as the file descriptor passing for socket activation) instead of inventing your own. There are, after all, no alternative standards here that only BSD supports.

But, as I've said, I'm asking the wrong project. I've closed the issue and will let it lie.

**Comment by nicm** [comment]
Well, if it doesn't do anything anywhere else it is a bit academic, but you're right any other project would be sensible to choose a similar API. Although that is not a guarantee they will!

I didn't say I wouldn't accept any changes, just that I thought it would be better if this was solved outside tmux. I don't know why you're getting snippy because I am offering alternatives, it's not like you mentioned them up front, initially you were asking about some entirely different problem. But I don't mind either way, let's leave it for the moment.
