### ISSUE TITLE
command completion is not working as expected

### ISSUE THREAD

**Issue by tnyblom** [tmux/tmux#24]
tmux neither shows the possible completions (probably due to a single line available) nor does it cycle through possible completions.

IE: ":list-" doe nothing useful

learning curve would be reduces if a completion existed.

**Comment by ntnn** [comment]
Completions are rarely part of the software, if you're using `zsh` tmux completions should be builtin, `bash` has an external script that provides better completion for many many commands.

**Comment by Boruch-Baum** [comment]
I've written a pretty exhaustive bash completion script for all tmux commands. Are you interested in adding to this repository somehow, or should I turn to the 'bash completion' package, or some-where some-thing else?

**Comment by ThomasAdam** [comment]
This doesn't belong with tmux.  If these bash completion scripts are a thing external to bash itself, ask there.
