### ISSUE TITLE
Enter is not working properly

### ISSUE THREAD

**Issue by HenryGiraldo** [tmux/tmux#240]
When terminal ask for an asnwer and is needed enter, enter is not working. Example:
<pre>
A debugging session is active.

        Inferior 1 [process 10155] will be killed.

Quit anyway? (y or n) ^M^Mq^Mq^My^M^M^M^Mççç^M^M^My^My^My^M^M^Mq^Mq^Mq^Mq^Mq^Mq^Mq^C^M^Mq^My^My^My^My^My^My^My^My^M^[
Please answer y or n.
</pre>
Using Alt+Enter to solve it.

**Comment by nicm** [comment]
Works for me...

**Comment by HenryGiraldo** [comment]
Using Linux, 4.2.0-1-amd64 , XTERM and zsh.

**Comment by krader1961** [comment]
This is usually because your shell has custom key bindings and/or `stty -icrnl` has been run. It is most definitely not a tmux problem. The [enter] key is supposed to send a \cM (aka \r) character.
