### ISSUE TITLE
tmux kill-server doesnt die

### ISSUE THREAD

**Issue by leenooks** [tmux/tmux#2401]
### Issue description
Howdy, I use `tmux kill-server` when I've changed my tmux.conf, but it never dies. Instead it responds to new tmux commands with `server exited unexpectedly`.

It seems the problem is that child processes that update the task bar are not dying - because when I kill them manually the parent actually dies and then I'm good to go again:

```
╰─$ ps -Af|grep tmux
  501 15217     1   0 Fri01pm ??        16:37.91 tmux start-server; show-option -g base-index; show-window-option -g pane-base-index;
  501 15544 15217   0 Fri01pm ??         0:05.02 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
  501 15572 15217   0 Fri01pm ??         0:34.76 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _loadavg; sleep 10; done
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
```╰─$ tmux -V
tmux 3.1b
```
* Platform (`uname -sp`).
```╰─$ uname -sp
Darwin i386
```
* $TERM inside and outside of tmux (`echo $TERM`).
```
╰─$ echo $TERM
xterm-256color
```
* Logs from tmux (`tmux kill-server; tmux -vv new`).
```
╰─$ tmux kill-server; tmux -vv new
server exited unexpectedly
server exited unexpectedly
```
(But killing 15544 and 15572 above - it then shows):
```
╰─$ tmux kill-server; tmux -vv new
no server running on /private/tmp/tmux-501/default
```

**Comment by krader1961** [comment]
Help an old man out. Why are you piping the output of `cut -c3- ~/.tmux.conf` into `sh -s`? That makes literally no sense. You're removing the first three characters of each line in *~/.tmux.conf* then telling `sh` to treat the result as a shell script. On my system that results in the expected shell errors:

```
> cut -c3- ~/.tmux.conf | sh -s wtf
/bin/sh: line 1: Start: command not found
/bin/sh: line 2: t: command not found
/bin/sh: line 4: Use: command not found
/bin/sh: line 5: emacs: command not found
/bin/sh: line 6: keyboards: command not found
/bin/sh: line 7: t-option: command not found
/bin/sh: line 9: nd: command not found
/bin/sh: line 11: syntax error near unexpected token `('
/bin/sh: line 11: `Use my custom terminfo that enables italic support (from'
```

**Comment by leenooks** [comment]
Oh, yeah, I guess without context that doesnt help :) I'm using `https://github.com/gpakosz/.tmux`, so my [tmux.conf](https://github.com/gpakosz/.tmux/blob/master/.tmux.conf) is from this repository (which gives me a nice UI). And the result of the cut -c3- means that the functions (that generate the bottom components) are executed and updated regularly.

**Comment by krader1961** [comment]
Different strokes for different folks but that is an incredibly convoluted, fragile, confusing, expensive mechanism for executing shell functions. Did you notice that the owner of that project committed https://github.com/gpakosz/.tmux/commit/a439667d6501d926666dee315e2220cb802aee19 yesterday which seems to address your problem?

**Comment by krader1961** [comment]
That project also has a lot of baggage needed only to support old (really old) versions of tmux. Such as detecting whether you have the `reattach-to-user-namespace` utility installed. Tmux hasn't needed that utility in a long time.

**Comment by leenooks** [comment]
Ahh, OK. Thanks. I hadnt seen that commit from yesterday, and it indeed does fix the problem. I only came across that project a few days ago, and it it does provide a nice environment. (I havent been using tmux long either - but I've been using screen for years.) If there are others out there that are more efficient, I'll happily take recommendations.
