### ISSUE TITLE
Variables aren't available in confirm-before

### ISSUE THREAD

**Issue by nomasprime** [tmux/tmux#2402]
### Issue description

Expected the following to work but it looks like the variable's undefined in this context:

```
bind-key M-R confirm-before -p "rename-window #{b:pane_current_path}? (y/n)" "rename-window #{b:pane_current_path}"
```

### Required information

Please provide the following information:

* tmux 3.1b
* Darwin i386
* screen-256color (in) xterm-256-color (out)

PS Should terms be the same?

**Comment by nicm** [comment]
I don't think confirm-before expands formats, but you can wrap it in run-shell which does.

**Comment by nomasprime** [comment]
Thanks @nicm.

Tried various permutations of `bind-key M-R confirm-before -p "rename-window #{b:pane_current_path}? (y/n)" "run-shell tmux rename-window #{b:pane_current_path}"` without success.

**Comment by nicm** [comment]
~~~~
bind M-R run 'tmux confirm-before -p "rename-window #{b:pane_current_path}? (y/n)" "rename-window #{b:pane_current_path}"'

**Comment by nomasprime** [comment]
Ah! You beat me to it except I ended up with `bind-key M-R confirm-before -p "rename-window #{b:pane_current_path}? (y/n)" 'run-shell "tmux rename-window #{b:pane_current_path}"'`. I'll update to your solution.

Thanks again. Only just started using tmux :)

**Comment by nomasprime** [comment]
Just in case someone else is doing something similar, there's also the option of `bind-key M-r command-prompt -I "#{b:pane_current_path}" "rename-window '%%'"` which allows further modification.
