### ISSUE TITLE
high tmux memory usage

### ISSUE THREAD

**Issue by svalaskevicius** [tmux/tmux#2408]
### Issue description

After using tmux for a while, I need to restart all my sessions due to the amount of memory tmux is using.

![2020-10-04-170344_1162x117](https://user-images.githubusercontent.com/893660/95020643-3c1d9500-0664-11eb-8fdd-00f180540ef5.png)

It could be related to the tmux history, but the memory has not been freed up after I ran `:clear-history`, even though `tmux lsp -aF '#{history_bytes}'` was showing much smaller numbers after it. surprisingly, the memory usage was not affected at all - even if the history that was cleared was high..

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
`tmux 3.1b`

* Platform (`uname -sp`).
`Linux unknown` - NixOS 20.09, with tmux coming from the latest (master) nixpkgs recipe.

* $TERM inside and outside of tmux (`echo $TERM`).
screen-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).
As it is not a crash, is this needed?

**Comment by nicm** [comment]
tmux frees memory when you clear history but it is up to libc when to return it to the kernel and glibc is very bad at this. You can perhaps try playing with some of its options.

**Comment by svalaskevicius** [comment]
Looking at https://stackoverflow.com/questions/2215259/will-malloc-implementations-return-free-ed-memory-back-to-the-system I am not sure what options to try.. The unreleased memory is more than 128k, which I could live with.. (I have also checked glibc manual / tunables section..) 

Do you have any starting points?

**Comment by nicm** [comment]
You could try adding a call to malloc_trim(0) to the end of the grid_free
function in tmux, that might help.

**Comment by svalaskevicius** [comment]
Ok, I'll try, thanks :)

**Comment by nicm** [comment]
Can you try this please: [tmux-malloc-trim.diff.txt](https://github.com/tmux/tmux/files/5326424/tmux-malloc-trim.diff.txt)

I don't have any Linux boxes to try so can you first check that in the configure output this says `yes`:
~~~~
checking if free doesn't work very well... no
~~~~
And also that tmux builds, you can create and kill windows, etc.

**Comment by svalaskevicius** [comment]
thanks!

I've updated the patch a bit - changed the include / define order so that the define was picked up: https://github.com/svalaskevicius/nixpkgs/blob/69852f09388d8fc855eda29ad64a8e1d53d94d8c/pkgs/tools/misc/tmux/malloc_trim.patch

with the above change the line now says "yes" and I've compiled and using this version (still based on 3.1b release).

I'll let you know how it goes later, and if it works out, I'll make a pr to nixpkgs adding the patch until it's upgraded to a version that works well :)

**Comment by svalaskevicius** [comment]
have done some more testing:

ran this in a few panes:
```
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 320 | head -n 2000000
```

tracked memory usage, and after `:clear-history` the memory goes back :) 

I guess the next test is a few weeks of usage, but this change is definitely making things better :) thanks!

**Comment by nicm** [comment]
OK, I have applied this to master now with your change, let me know if you see any problems. Thanks!

**Comment by svalaskevicius** [comment]
just an update - after running for a while, 52KB :) thanks again!
