### ISSUE TITLE
RedHat Install Fails Building from Source: libtinfo.so.6: cannot open shared object

### ISSUE THREAD

**Issue by a59** [tmux/tmux#2409]
### Building from Source Fails

I am trying to build tmux from source using the instructions here. It all seems to go fine until I try to run tmux when I get the following error

tmux: error while loading shared libraries: libinfo.so.6: cannot open shared object file: No such file or directory.

There is no file libinfo.so.6, but there is a libinfo.so.5.9

I used the latest ncurses-6.2 and libevent-2.1.12-stable.

### Required information

Please provide the following information:

* tmux version : 3.1b
* Platform : Linux x86_64 (RedHat 7.6)
* $TERM xterm-256color

**Comment by nicm** [comment]
Did you build your own ncurses and install it outside the system lib directories? Did you remember to set LD_LIBRARY_PATH?
