### ISSUE TITLE
Separate indicator for zoomed window

### ISSUE THREAD

**Issue by manasthakur** [tmux/tmux#241]
I found that probably there is no way to just have an indicator 'Z' for a zoomed window, without enabling all the window flags.
I customize my tmux bar and already have an indicator for the current window (using different colors), and I guess most tmux users do so.
In such a case, I would just like to have an additional 'Z' symbol when I have zoomed in a pane. Please consider adding this feature. Or is already there some way?

**Comment by nicm** [comment]
You can use the window_zoomed_flag format: #{?window_zoomed_flag,Z,}

**Comment by manasthakur** [comment]
Thanks a lot! Solved.
