### ISSUE TITLE
tmux server immediately exits on new session

### ISSUE THREAD

**Issue by joeminicucci** [tmux/tmux#2410]
# Problem Description
I am unable to open an attached or detached tmux session with an initial command invocation. tmux immediately exits when the new session is attempted, without verbose information in stderr.

For example, the following command exits before the session can be interacted with :
```
admin@box:~$ tmux new-session -s session1 'cd /home/admin/'
[exited]
```
As another example, a detached session with the same type of invocation attempt does not result in a session creation:

```
admin@box:~$ tmux new-session -d -s session1 'cd /home/admin/'
admin@box:~$ tmux list-sessions
no server running on /tmp/tmux-1000/default
```

# Requested Info

## Platform / Version Info
Debian Stretch
`Linux 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 x86_64`
- tmux 2.3
- TERM: xterm-256color

## Server Log
[tmux-server-16673.log](https://github.com/tmux/tmux/files/5344731/tmux-server-16673.log)

## Configuration
I added these 2 lines per a previous github issue raised: #2081 
`set -g default-shell /bin/sh`
(Also tried /bin/bash)

**Thank you so much for your time! 👍**

**Comment by krader1961** [comment]
That's the expected behavior. The `cd` command ran and the shell exited. Thus terminating the session. You can add `set -g remain-on-exit on` to your *~/.tmux.conf* but that will simply show you the shell running the the session terminated (with status zero if the directory exists, otherwise non-zero). You're effectively running `/bin/sh -c 'cd /home/admin'`. Do that from a shell prompt (no tmux) and observe the /bin/sh process immediately terminates.

There are several ways to do what you're trying. The solution I like is to use `tmux send-keys`. Another solution is to use a feature of the bash shell:

```
tmux new-session -s session1 'exec bash --init-file <(echo cd /tmp)'
```

**Comment by krader1961** [comment]
Also, I'm curious why you're even trying to run `cd /home/admin` as the first command run by an interactive shell spawned by tmux. That doesn't make much sense so I'm wondering if you chose that as a placeholder for whatever you're really trying to do. In which case see http://xyproblem.info/.

**Comment by joeminicucci** [comment]
> 
> 
> That's the expected behavior. The `cd` command ran and the shell exited. Thus terminating the session. You can add `set -g remain-on-exit on` to your _~/.tmux.conf_ but that will simply show you the shell running the the session terminated (with status zero if the directory exists, otherwise non-zero). You're effectively running `/bin/sh -c 'cd /home/admin'`. Do that from a shell prompt (no tmux) and observe the /bin/sh process immediately terminates.
> 
> There are several ways to do what you're trying. The solution I like is to use `tmux send-keys`. Another solution is to use a feature of the bash shell:
> 
> ```
> tmux new-session -s session1 'exec bash --init-file <(echo cd /tmp)'
> ```

Kurtis,
First of all thanks so much for your prompt support of my issue!
What you are saying completely makes sense. I was not aware that the inline command invocation's return code was respected by tmux. The `exec bash` method also appears to exit as soon as the `cd` program complete. 

The "solution" to my operator error appears to be solved by the `tmux send-keys` method you offered, for example:

`tmux send-keys -t session1.0 "cd /home/admin" ENTER`


> 
> 
> Also, I'm curious why you're even trying to run `cd /home/admin` as the first command run by an interactive shell spawned by tmux. That doesn't make much sense so I'm wondering if you chose that as a placeholder for whatever you're really trying to do. In which case see http://xyproblem.info/.

You are completely correct, I did create an XYProblem here. The program I originally was running was not `cd`, but rather a custom binary that hangs up the active tty. The binary was not doing this, and I misunderstood `tmux`, so here we are. Thanks again for your patience/assistance.

Cheers,
Joe

**Comment by joeminicucci** [comment]
> 
> 
> That's the expected behavior. The `cd` command ran and the shell exited. Thus terminating the session. You can add `set -g remain-on-exit on` to your _~/.tmux.conf_ but that will simply show you the shell running the the session terminated (with status zero if the directory exists, otherwise non-zero). You're effectively running `/bin/sh -c 'cd /home/admin'`. Do that from a shell prompt (no tmux) and observe the /bin/sh process immediately terminates.
> 
> There are several ways to do what you're trying. The solution I like is to use `tmux send-keys`. Another solution is to use a feature of the bash shell:
> 
> ```
> tmux new-session -s session1 'exec bash --init-file <(echo cd /tmp)'
> ```

Kurtis,
First of all thanks so much for your prompt support of my issue!
What you are saying completely makes sense. I was not aware that the inline command invocation's return code was respected by tmux. The `exec bash` method also appears to exit as soon as the `cd` program complete. 

The "solution" to my operator error appears to be solved by the `tmux send-keys` method you offered, for example:

`tmux send-keys -t session1.0 "cd /home/admin" ENTER`


> 
> 
> Also, I'm curious why you're even trying to run `cd /home/admin` as the first command run by an interactive shell spawned by tmux. That doesn't make much sense so I'm wondering if you chose that as a placeholder for whatever you're really trying to do. In which case see http://xyproblem.info/.

You are completely correct, I did create an XYProblem here. The program I originally was running was not `cd`, but rather a custom binary that hangs up the active tty. The binary was not doing this, and I misunderstood tmux, so here we are. Thanks again for your patience/assistance.

Cheers,
Joe
