### ISSUE TITLE
Make tmux accept Super ("windows") key for bindings

### ISSUE THREAD

**Issue by e-pirate** [tmux/tmux#2411]
I was not able to use Super ("windows" key actually returning Super_L as detected by xev) in combination with any other key in tmux 3.1b to invoke any action. The idea is to make tmux treat Super just as any other "modifier" key like Ctrl, Shift and Alt and make some use of it. For example bind SPR+1 switch to 1 window.

**Comment by nicm** [comment]
No terminal supports this, look at the first section of https://github.com/tmux/tmux/wiki/Modifier-Keys.

**Comment by e-pirate** [comment]
Well, at least xterm (xterm-256color) in konsole does. The specified recepie with cat shows:
``
$ cat
^X@s1
''

**Comment by nicm** [comment]
What key are you pressing?

**Comment by e-pirate** [comment]
"Windows" key between Ctrl and Alt + "1". xev recognizes it as Super_L.

**Comment by nicm** [comment]
No, I mean what key combination are you pressing. What do you see when you press Super-A or Super-B like you would press Ctrl-A or Ctrl-B?

If you just want to use it as a key on its own and not a modifier you can use user-keys.

**Comment by nicm** [comment]
You will need to add the keys using the user-keys option, most terminals do not support Super so there is no way for tmux to use it consistently.

**Comment by krader1961** [comment]
See also https://superuser.com/questions/1238236/super-key-combinations-cause-weird-input-in-konsole which explains this is a quirk of Konsole and, AFAICT, is not an established standard means of handling the Super/Windows key.
