### ISSUE TITLE
mode style setting for copy-mode cursor color while highlighting

### ISSUE THREAD

**Issue by longspell** [tmux/tmux#2412]
### Issue description

I'm looking to confirm if a setting exists for the cursor style while selecting/highlighting text in copy-mode.

In iterm when entering copy-mode-vi and navigating with the keyboard, pressing space and highlighting text has different appearance than in alacritty.  It seems alacritty is more closely following the actual style defined, but it's very easy to miss the final copied character, especially if it's empty as the background under the cursor does not change color.  For example you can highlight the first space between `Oct` and `8` in the screenshots without any visual cue that you've actually highlighted more than `Oct`.

Looking to know what setting can change the cursor's background color without changing the already highlighted text's color. Or if there's a style similar to vim's visual selection where the cursor remains in the normal styte (inverting fg/bg) while selecting. If it's worth mentioning, before pressing space and beginning selection in tmux's copy-mode-vi, the cursor does just invert the fg and bg.

Examples (copying the text up to and including the `:`)

iTerm:
![image](https://user-images.githubusercontent.com/60353706/95496359-b30da300-096e-11eb-984d-b68dd6771dbd.png)

Alacritty:
![image](https://user-images.githubusercontent.com/60353706/95496372-b739c080-096e-11eb-956d-0d64cffa4b6e.png)

### Required information

Screenshots produced with `tmux -f /dev/null new`

* tmux version: tmux 3.1b
* Platform: OSX (Darwin i386)
* $TERM inside and outside of tmux: xterm-256color / screen-256color

**Comment by longspell** [comment]
This can be ignored, discovered the applicable settings in alacritty.

Incase anyone else comes across this:
https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L196

**Comment by npearson72** [comment]
@longspell what alacritty settings did you use to correct this? I'm having the same issue but can't seem to configure things to work.
