### ISSUE TITLE
tmux goes into infinite loop

### ISSUE THREAD

**Issue by geza-herman** [tmux/tmux#2416]
### Issue description

Tmux goes into infinite loop, when double clicking on a word which is at the top of the screen.

Use this `.tmux.conf`:
```
set-option -g mouse on
bind-key -T root DoubleClick1Pane copy-mode -M \; send-keys -X select-word
```

Here are the steps to reproduce:
 - Start a new tmux session
 - Execute `echo`, it causes an empty line.
 - Execute something which fills the screen, like `seq 200`.
 - Position the mouse at the very top of the terminal screen, and double click on some word (which is at the top of the screen).

This will enter copy mode, select the word. But after this, the screen starts scrolling upwards automatically, and starts selecting the text upwards (no matter where the mouse is moved during the scrolling, it keeps going). When the selection reaches the empty line (made by `echo`), tmux goes into an infinite loop, and causes all tmux clients to hang. If there is no empty line (`echo` step is skipped), then it doesn't go into infinite loop.

I checked and the problem is in `window-copy.c`, in the function `window_copy_cursor_previous_word_pos`. The `px` variable is `0`, and `py` doesn't change, so it can never leave the loop. There's a suspicious code (line 4123):
```
				py--;

				py = screen_hsize(data->backing) + data->cy -
				    data->oy;
```
This decreases `py`, but after this, it puts the original value back.

### Required information

* tmux version (`tmux -V`): `tmux 3.1b`
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`): `screen`, `rxvt-unicode-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): no logs produced by this command (I have to manually kill the server by using `kill`, and afterwards I don't see `tmux -vv new` printing anything, it just starts a new session)

### Screencast
![freeze](https://user-images.githubusercontent.com/27892988/95658350-053ef780-0b1a-11eb-97ae-47cf50e9970c.gif)

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by geza-herman** [comment]
> Does this still happen with master?

Nice, it doesn't, I should have checked it.

The auto scrolling is still there, though. I'd understand this behavior, if I pressed and held a button, but for a double-click, I'd prefer if it didn't scroll. Is it by design?

**Comment by nicm** [comment]
You are using copy-mode -M which passes the mouse event on to copy mode. A
mouse event at the top of the screen with start scrolling. Remove the -M.

**Comment by geza-herman** [comment]
Awesome, thank you!
