### ISSUE TITLE
Can't set pane-border-status as panel local

### ISSUE THREAD

**Issue by Ergus** [tmux/tmux#2417]
### Issue description

>Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

>If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

>Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

The option `pane-border-status` can't be set panel local. I am trying to add pane text to a single pane and it seems I can only set it up to window granularity. 

According to the name it seems like a pane option, but I can't set it for a single panel.

When I do:

```
tmux set -p pane-border-status top
```

I get this:

```
$ tmux show-option -w
pane-border-status top
```
And this:

```
$ tmux show-option -p
```

And of course the text is set in all the panes of current window.

Is this intended? 

>Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.1b

* Platform (`uname -sp`).
Linux unknown (Linux Ergus 5.8.14-arch1-1 #1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000 x86_64 GNU/Linux)

* $TERM inside and outside of tmux (`echo $TERM`).
tmux-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Correct, either all panes have a status line or none do.
