### ISSUE TITLE
True color doesn't work in kitty anymore with 3.2-rc

### ISSUE THREAD

**Issue by trygveaa** [tmux/tmux#2418]
### Issue description

As of 3.2-rc true color doesn't work in the kitty terminal emulator, while in 3.1b it worked.

The issue can be reproduced with this script: https://github.com/mfontani/tmux-kitty-colors-bug/blob/master/colortest.sh

3.1b:
![tmux 3.1b](https://github.com/mfontani/tmux-kitty-colors-bug/raw/master/kitty_0.19.1_tmux_3.1b__truecolor_ok.png)

master:
![tmux master](https://github.com/mfontani/tmux-kitty-colors-bug/raw/master/kitty_0.19.1_tmux_3.2-rc2__truecolor_not_ok.png)

I bisected the issue to commit c91b4b2e142b5b3fc9ca88afec6bfa9b2711e01b, specifically to the change from:

```
if ((tty_term_flag(term, TTYC_TC) || tty_term_has(term, TTYC_RGB)) ||
    (tty_term_has(term, TTYC_SETRGBF) &&
    tty_term_has(term, TTYC_SETRGBB)))
```

to:

```
if ((tty_term_flag(term, TTYC_TC) || tty_term_has(term, TTYC_RGB)) &&
    (!tty_term_has(term, TTYC_SETRGBF) ||
    !tty_term_has(term, TTYC_SETRGBB)))
```

I'm not sure, but from what I can see `SETRGBF`/`SETRGBB` is an older way of detecting true color support while `RGB` is a newer one. It seems strange that you're requiring either `SETRGBF` or `SETRGBB` to not be set? Is this intentinal?

Kittys terminfo specifies all of these three as far as I know.

### Required information

* tmux version (`tmux -V`): tmux next-3.2/next-3.3 (c91b4b2e/master)
* Platform (`uname -sp`): Arch Linux
* $TERM inside and outside of tmux (`echo $TERM`): outside: `xterm-kitty`, inside: reproducable with both `screen` and `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): This doesn't produce any output.

Reproducable without any `tmux.conf`.

**Comment by nicm** [comment]
This looks OK to me. We only want to replace `setrgbf` and `setrgbb` if `Tc` or `RGB` is set and they are not already provided (either is missing). Show me the server log file please.

**Comment by trygveaa** [comment]
Here: 
[tmux-server-32369.log](https://github.com/tmux/tmux/files/5364147/tmux-server-32369.log)

**Comment by nicm** [comment]
It looks like the terminfo entry you are using provides its own `setrgbb` and `setrgbf` (it also provides `Tc` but not `RGB`), so tmux does not replace them. They look fine though, so I don't know why it doesn't work. If you do this outside tmux:
~~~~
tput setrgbf 100 150 0
~~~~
Does the colour change (it should be a light green)?

Also can you show me the server log from doing (where the second and third line are inside tmux):
~~~~
tmux -Ltest -f/dev/null new
printf '\033[38:2:100:150:0m'
exit
~~~~

**Comment by nicm** [comment]
Er actually if you have a fancy prompt make that:
~~~~
printf '\033[38:2:100:150:0mabcdef'
~~~~
So there is some text in this colour.

**Comment by trygveaa** [comment]
> Does the colour change (it should be a light green)?

Yes
![image](https://user-images.githubusercontent.com/601966/95730884-25d49200-0c7f-11eb-84b5-7c460013a4cb.png)

> Also can you show me the server log from doing (where the second and third line are inside tmux):
> 
> ```
> tmux -Ltest -f/dev/null new
> printf '\033[38:2:100:150:0m'
> exit
> ```

[tmux-server-35158.log](https://github.com/tmux/tmux/files/5364268/tmux-server-35158.log)

**Comment by nicm** [comment]
Does it appear in green the same way when you try it inside tmux?

**Comment by trygveaa** [comment]
It looks similar, but it's slightly darker inside tmux:
![image](https://user-images.githubusercontent.com/601966/95732099-a6e05900-0c80-11eb-864f-837d12f809ef.png)

**Comment by nicm** [comment]
OK yes I see what is happening. If a terminal provides its own setrgbf/setrgbb we still need to set the flag or it will get converted down to 256 colours. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/5364367/x.diff.txt)

**Comment by trygveaa** [comment]
Yup, it works with that. Thanks.

**Comment by trygveaa** [comment]
I'm wondering why you don't consider `SETRGBF` and `SETRGBB` to be enough to enable true color though (as you did before). Why do `TC` or `RGB` also have to be set?

**Comment by nicm** [comment]
This check is not about enabling RGB colour, it is about whether tmux should use the terminfo setrgbf and setrgbb or its own versions, but you are right we should separate the tests, like this:
~~~~
--- tty-term.c  5 Oct 2020 09:53:01 -0000       1.84
+++ tty-term.c  12 Oct 2020 13:11:59 -0000
@@ -578,6 +578,9 @@ tty_term_create(struct tty *tty, char *n
            (!tty_term_has(term, TTYC_SETRGBF) ||
            !tty_term_has(term, TTYC_SETRGBB)))
                tty_add_features(feat, "RGB", ",");
+       if (tty_term_has(term, TTYC_SETRGBF) &&
+           tty_term_has(term, TTYC_SETRGBB))
+               term->flags |= TERM_RGBCOLOURS;

        /* Apply the features and overrides again. */
        tty_apply_features(term, *feat);
~~~~
We could probably get rid of the flag altogether TBH, it is only used in two places.

**Comment by trygveaa** [comment]
Right, that seems more reasonable.
