### ISSUE TITLE
Tmux was not running due to bad file descriptor ...

### ISSUE THREAD

**Issue by duytrung** [tmux/tmux#2419]
### Issue description

Tmux was not running and display a message
![image](https://user-images.githubusercontent.com/2046672/95743619-94463e00-0cd9-11eb-8709-d16266861591.png)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

![image](https://user-images.githubusercontent.com/2046672/95743856-f30bb780-0cd9-11eb-8cfd-95c3e0af675f.png)

What was the cause of these error? Thanks for considering

**Comment by nicm** [comment]
Where did you get this tmux build from?

**Comment by duytrung** [comment]
This build was located in Msys2 repo and I installed it using "pacman -S tmux".
Thanks

**Comment by nicm** [comment]
What tmux version is it?
