### ISSUE TITLE
How would I get the last key pressed in a plugin?

### ISSUE THREAD

**Issue by leighmcculloch** [tmux/tmux#242]
How would I get the last key pressed?

I'm wanting to get the last key pressed and insert it into the status bar, so that on shared tmux sessions one user can see what the other user is typing when training.

**Comment by zackp30** [comment]
I don't think this is possible as of yet.

There's work in progress support for hooks being implemented as we speak, which *could* allow for something like this, probably a "key pressed" hook, and then feed that into the `tmux` status bar.

@nicm Is a "key pressed" hook for tmux on the radar?

@leighmcculloch hooks will probably be "stable" in some time, the current progress can be seen in the `hooks` branch, only a few hooks are implemented and not the one you want, but I would imagine that it would be implemented (I'm not part of the team and thus cannot say officially)

**Comment by zackp30** [comment]
FYI I didn't mean to imply it was planned, and quoted from IRC:

> (180540)   thomas_adam | No, it's not planned.

It indeed isn't planned, sorry.

**Comment by leighmcculloch** [comment]
@zackp30 Thanks for the reply. No worries, I've managed to implement this by intercepting every key press by binding every possible key, calling out to a script, then resending the key. Has worked remarkably well so far, although hacky conceptually.

**Comment by leighmcculloch** [comment]
I can understand several reasons why you wouldn't want events on key presses, it'd be too easy to attach a keylogger for nefarious reasons.

**Comment by nicm** [comment]
It'd be easy enough to add a format for this I think.
On 24 Dec 2015 18:20, Leigh McCulloch <notifications@github.com> wrote:I can understand several reasons why you wouldn't want events on key presses, it'd be too easy to attach a keylogger for nefarious reasons.
