### ISSUE TITLE
cannot copy into system clipboard in vi-copy mode in macOS built-in Terminal app

### ISSUE THREAD

**Issue by NitroCao** [tmux/tmux#2420]
* tmux version: `tmux next-3.3`.
* platform: macOS 10.15
* application: system built-in Terminal app.
* $TERM inside: xterm-256color, outside: xterm-256color
* related configuration:
```
# bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'    # This is for macOS. Maybe you should install **xclip** if not
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe 'reattach-to-user-namespace pbcopy'    # This is for macOS. Maybe you should install **xclip** if not
#bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'    # This is for Linux. Maybe you should install **xclip** if not
```

If I use iTerm2, everything works fine.

**Comment by nicm** [comment]
If you do `set -g set-clipboard off` does it stop working in iTerm2 as well?

**Comment by NitroCao** [comment]
> If you do `set -g set-clipboard off` does it stop working in iTerm2 as well?

Yeah. I just add the option and restart tmux, it stop working in iTerm2.

**Comment by nicm** [comment]
Terminal.app doesn't support `set-clipboard` so it is working in iTerm2 using `set-clipboard` not `pbcopy`. Does it work if you remove `reattach-to-user-namespace` from the command (so it is just `pbcopy`)? You will want to leave `set-clipboard` off if you are using `pbcopy`.

**Comment by NitroCao** [comment]
> Terminal.app doesn't support `set-clipboard` so it is working in iTerm2 using `set-clipboard` not `pbcopy`. Does it work if you remove `reattach-to-user-namespace` from the command (so it is just `pbcopy`)? You will want to leave `set-clipboard` off if you are using `pbcopy`.

It works. Thanks for your quick reply!

**Comment by nicm** [comment]
OK great stuff.

**Comment by NitroCao** [comment]
Sorry that I have a problem again. When I use ssh command to connect to the tmux server on my remote CentOS 8, it does not work again.
The ssh command is `ssh -t nitro@10.1.1.22 "tmux attach"`.
tmux version on CentOS 8: `tmux next-3.3`.
related configuration:
```
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
```
It also works fine in iTerm2.

**Comment by krader1961** [comment]
I'm going to assume you have `ForwardX11` enabled in your ssh configuration since you say it "also works fine in iTerm2. The problem is likely due to the tmux session having a cached copy of the `DISPLAY` env var. When you establish a new ssh connection the `DISPLAY` env var will be different. See the `attach-session -E` option and the `update-environment` config option.

**Comment by NitroCao** [comment]
> I'm going to assume you have `ForwardX11` enabled in your ssh configuration since you say it "also works fine in iTerm2. The problem is likely due to the tmux session having a cached copy of the `DISPLAY` env var. When you establish a new ssh connection the `DISPLAY` env var will be different. See the `attach-session -E` option and the `update-environment` config option.

I doesn't have `ForwardX11` option in my ssh configuration. it just has `User` and `IdentifyFile` options. And there is no `DISPLAY` env var. My remote CentOS 8 doesn't have a desktop environment.

**Comment by krader1961** [comment]
You've probably left out some important information. Google "x11 display forwarding". That's how things like `xclip` work over a SSH connection. Also, macOS uses a proprietary display manager, not X11. So the only way this would work is if you also installed [XQuartz](https://www.xquartz.org/). See also https://support.apple.com/en-us/HT201341.

Also, you don't necessarily have to have `ForwardX11` in your *~/.ssh/config* file. It might be set in the */etc/ssh/ssh_config* file or might be enabled by default on your system.

**Comment by NitroCao** [comment]
In `/etc/ssh/ssh_config` `ForwardX11` is also disabled.
I don't use XQuartz, it indeed works fine in iTerm2 ......

**Comment by krader1961** [comment]
> it indeed works fine in iTerm2

I can't figure out what you are saying "works fine." There is no `xclip` command on macOS and macOS does not support X11 (the protocol used by `xclip`). Are you saying that if you `ssh -t nitro@10.1.1.22`, and do not involve tmux, that running `xclip -in -selection clipboard` works? When I do, from within iTerm on macOS, `ssh -X -t opensuse42` (the `-X` explicitly enables X11 forwarding) then run `xclip -in -selection clipboard` I get the expected error: `Error: Can't open display: (null)`.

**Comment by NitroCao** [comment]
Sorry not to describe the process clearly. Open a new tab on iTerm2 and execute `ssh -t nitro@10.1.1.22 "tmux attach"`. Then copy text in vi-copy mode in the opened tmux session. The result is that the text copied is now in the system clipboard of macOS.

**Comment by krader1961** [comment]
@NitroCao Your last comment seems to describe what you want to happen. I was asking what actually happens when you ssh to your CentOS system, do not do `tmux attach`, and run the `xclip` command. Earlier you implied that worked. I don't see how that could work.

**Comment by NitroCao** [comment]
run the `xclip` command outside tmux session and its output is `Error: Can't open display: (null)`.
Yeah, my last comment describes what I want to happen and it indeed happens when I use iTerm2, so I said `it indeed works fine in iTerm2`. But it doesn't happen when I use Terminal app.

**Comment by NitroCao** [comment]
This is the configuration of tmux on my Mac:
```
#List of plugins
# The following three lines are plugins and the plugin manager is **tpm**
set -g @plugin 'tmux-plugins/tpm'    # This is for tpm plugin manager
set -g @plugin 'jimeh/tmux-themepack'    # This plugin is a collection of themes
set -g @plugin 'tmux-plugins/tmux-resurrect'    # This plugin is to store and restore the status of tmux
set -g @plugin 'schasse/tmux-jump'

set -g history-limit 10000
set -g default-terminal "xterm-256color"
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @jump-key 'g'
#set-option -g default-command "reattach-to-user-namespace -l bash"

# The following lines starting with bind or bind-key are for keybings.
# The default prefix key is Ctrl-b.
# The style of moving is vim-style.
bind r source-file ~/.tmux.conf \; display "Configuration Reloaded!"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L 10    # The following uppercase letters are for resize the window
bind L resize-pane -R 10
bind K resize-pane -U 5
bind J resize-pane -D 5
bind '"' split-window -c '#{pane_current_path}'
bind '%' split-window -h -c '#{pane_current_path}'
bind p previous-window
bind-key a last-window


set -s escape-time 0
# The following lines are for copying.
# If you want to enter copy-mode, just enter <prefix><Esc> or <prefix><C-[> (<ESC> is equal with <Ctrl-[>), and then operate just like vim,
# such as typeing V for selecting, then type y to copy the selecting contents, just like vim you know.
bind Escape copy-mode
#bind -t vi-copy v begin-selection
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi WheelUpPane send -N1 -X scroll-up
bind-key -T copy-mode-vi WheelDownPane send -N1 -X scroll-down
#bind -t vi-copy y copy-selection
#bind-key -T copy-mode-vi 'y' send -X copy-selection
#unbind p
set -sg escape-time 0
set -g mode-keys vi
#bind -t vi-copy y copy-pipe 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi 'y' send -X copy-pipe 'pbcopy'    # This is for macOS. Maybe you should install **xclip** if not
#bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'    # This is for Linux. Maybe you should install **xclip** if not

set -g mouse on    # enable mouse support

# The following lines beginning with set-(window)-option are for the style of status bar.
# You must install the theme plguin at first if you want it to become beautiful.
set -g @themepack 'powerline/double/yellow'
run '~/.tmux/plugins/tpm/tpm'
```

This is the configuration file of tmux on my CentOS 8:
```
#List of plugins
# The following three lines are plugins and the plugin manager is **tpm**
set -g @plugin 'tmux-plugins/tpm'    # This is for tpm plugin manager
set -g @plugin 'jimeh/tmux-themepack'    # This plugin is a collection of themes
set -g @plugin 'tmux-plugins/tmux-resurrect'    # This plugin is to store and restore the status of tmux
set -g @plugin 'schasse/tmux-jump'

set -sa terminal-overrides ',xterm-256color:RGB'
set -g history-limit 10000
set -g default-terminal "screen-256color"
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @jump-key 'g'
#set-option -g default-command "reattach-to-user-namespace -l bash"

# The following lines starting with bind or bind-key are for keybings.
# The default prefix key is Ctrl-b.
# The style of moving is vim-style.
bind r source-file ~/.tmux.conf \; display "Configuration Reloaded!"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L 10    # The following uppercase letters are for resize the window
bind L resize-pane -R 10
bind K resize-pane -U 5
bind J resize-pane -D 5
bind '"' split-window -c '#{pane_current_path}'
bind '%' split-window -h -c '#{pane_current_path}'
bind p previous-window
bind-key a last-window


set -s escape-time 0
# The following lines are for copying.
# If you want to enter copy-mode, just enter <prefix><Esc> or <prefix><C-[> (<ESC> is equal with <Ctrl-[>), and then operate just like vim,
# such as typeing V for selecting, then type y to copy the selecting contents, just like vim you know.
bind Escape copy-mode
#bind -t vi-copy v begin-selection
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi WheelUpPane send -N1 -X scroll-up
bind-key -T copy-mode-vi WheelDownPane send -N1 -X scroll-down
#bind -t vi-copy y copy-selection
#bind-key -T copy-mode-vi 'y' send -X copy-selection
#unbind p
set -sg escape-time 0
set -g mode-keys vi
#bind -t vi-copy y copy-pipe 'xclip -in -selection clipboard'
#bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'    # This is for macOS. Maybe you should install **xclip** if not
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'    # This is for Linux. Maybe you should install **xclip** if not

set -g mouse on    # enable mouse support

# The following lines beginning with set-(window)-option are for the style of status bar.
# You must install the theme plguin at first if you want it to become beautiful.
set -g @themepack 'powerline/double/yellow'
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by krader1961** [comment]
@NitroCao I still don't know what you mean by "it indeed happens when I use iTerm2". If you mean what happens is an error message and the system clipboard on your macOS system is unchanged the, yes, "it indeed happens."

Regarding the behavior you expect... What you expect will not work unless you install XQuartz (or an equivalent X11 server) on your macOS system. Neither ssh or xclip work with the macOS display manager. Please note that I'm typing this comment on a macOS server.

**Comment by nicm** [comment]
I don't think you can use X11 forwarding to set the clipboard on macOS, so your only option is OSC 52 (`set-clipboard`) which is not supported by Terminal.app. If you want this to work over ssh you will need to use iTerm2.

**Comment by krader1961** [comment]
> I don't think you can use X11 forwarding to set the clipboard on macOS...

In theory you can use X11 forwarding by using XQuartz (an X11 server for macOS), but the last time I used it successfully for this sort of thing was ~6 years ago. I'm certain @NitroCao has not successfully used `xclip` on CentOS via an SSH connection from a macOS system outside of tmux. Despite what they wrote earlier that implies they have done so. As often happens, especially where English is not someone's native language, I think they confused the behavior they desire with the behavior they see.

**Comment by krader1961** [comment]
This Github gist is relevant and interesting: https://gist.github.com/yudai/95b20e3da66df1b066531997f982b57b

**Comment by NitroCao** [comment]
Terminal app sucks. Back to iTerm again. The problem has been solved perfectly ... Thanks for your replies bro.

**Comment by krader1961** [comment]
@NitroCao Terminal.app does not "suck". It is not as feature rich as iTerm (which I use every day on three different systems) but it is a reasonably good terminal emulator. More importantly, you didn't explain what we wrote that solved your problem. See also, issues like https://github.com/microsoft/terminal/issues/2946 that involve MS Windows and are applicable to this issue. I understand that you would like this to "just work.". But that isn't realistic.
