### ISSUE TITLE
Tmux has-session does not match exact string

### ISSUE THREAD

**Issue by aonemd** [tmux/tmux#2421]
### Issue description

Tmux does not perform the correct string search on session name for command `has-session` (aliased as `has`).

Steps to reproduce:

- Make sure no sessions are running:

```bash
tmux kill-server

tmux ls  # no server running on /tmp/tmux-1000/default
```

- Create a new session `abc`:

```bash
tmux new-session -d -s abc
```

- Check if session exists using different patterns:

```bash
tmux has-session -t 'abc'
tmux has-session -t 'ab'
tmux has-session -t 'a'
tmux has-session -t ''
```
all return without errors (return 0) which means the session 'abc' is matched in all cases.

- Test for session not found:

```bash
tmux has-session -t 'ad' # can't find session: ad
```
this one returns -1 with an error message as above.

I'm trying to hack on the code of Tmux to find and fix the issue so any help in the right direction is greatly appreciated. Thanks!

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
Git master (tmux next-3.3)

* Platform (`uname -sp`).
Linux 5.8, Arch Linux

* $TERM inside and outside of tmux (`echo $TERM`).
Outside Tmux: xterm-256color
Inside Tmux: xterm-256color

**Comment by nicm** [comment]
The rules for targets are in the man page: https://man.openbsd.org/OpenBSD-current/man1/tmux.1#COMMANDS

You need to use `=` if you want an exact match only.
