### ISSUE TITLE
tmux session disappear after ssh close

### ISSUE THREAD

**Issue by hqabcxyxz** [tmux/tmux#2423]
### Issue description

I install a tmux which complie from github on my server,then I use laptop connect my server and open the tmux session,after I close ssh then connect again,I find tmux show that `no server running on /tmp/tmux-1000/default`......

but when I try annother server which has a  tmux 2.6 and install by `apt`,it does have this problem.

I use oh-my-tmux,there is my tmux config link:
https://github.com/hqabcxyxz/.tmux

there is  diffirent from oh my tmux:
```
# ---my set ------------------------------------------------------------------
# List of plugins
set -g @tpm_plugins '          \
   tmux-plugins/tpm             \
   tmux-plugins/tmux-sensible   \
   tmux-plugins/tmux-resurrect  \
   tmux-plugins/tmux-open      \
   tmux-plugins/tmux-yank      \
   christoomey/vim-tmux-navigator \
'
set -g @resurrect-processes 'ssh'
set -g @resurrect-capture-pane-contents 'on' # 开启恢复面板内容功能
set -g @resurrect-save-shell-history 'on'
# 为了能用vim-tmux-clipboard
set-option -g focus-events on


# 兼容neovim显示
#set-option -sa terminal-overrides ',xterm-256color:RGB'
set-option -ga terminal-overrides ',xterm-256color:Tc'

# 关闭tmux默认重命名机制
setw -g automatic-rename off
setw -g allow-rename off

# F12 切换状态栏开关
bind-key F12 set-option status


# 开启256色支持
set -g default-terminal "screen-256color"
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

```
### Required information

Please provide the following information:

* tmux version (`tmux -V`). **tmux next-3.3 and tmux 3.2-rc2**
* Platform (`uname -sp`). **Linux x86_64**
* $TERM inside and outside of tmux (`echo $TERM`). **xterm**
* Logs from tmux (`tmux kill-server; tmux -vv new`). 

there is my `tmux-server.log`
https://gist.github.com/hqabcxyxz/f0fc8226b4dedd94ac1a765bcc67839d

**Comment by nicm** [comment]
If you do `pkill -USR1 tmux` after you see the `no server ...` message, does it then work?

**Comment by hqabcxyxz** [comment]
> If you do `pkill -USR1 tmux` after you see the `no server ...` message, does it then work?

is doesnt work....   I use `tmux new -s hq` open a tmux session,then close the ssh connect,
after I connect again, use `tmux a -t hq`   but my terminal show that `no sessions`,
I try `pkill -USR1 tmux`  ,no thing happened and problen is still exist

**Comment by nicm** [comment]
Is tmux still running? What if you do `pgrep -lf tmux`, does it show tmux?

**Comment by hqabcxyxz** [comment]
> Is tmux still running? What if you do `pgrep -lf tmux`, does it show tmux?


it just show that 
```
2598 tmux: client
```
If  I use `tmux list-session` show that
```
no server running on /tmp/tmux-1000/default
```

**Comment by nicm** [comment]
Are you sure tmux had exited in this log file?

**Comment by hqabcxyxz** [comment]
> Are you sure tmux had exited in this log file?

`tmux-server-32296.log` is the newest log at that time...  
It seem that because my network condition is not good,and some network packet loss...   
After I try use tmux though ssh in a good network place, this problem do not happen....

**Comment by nicm** [comment]
Can you do this please:
~~~~
tmux kill-server
strace -tt -fostrace.out tmux -f/dev/null new
~~~~
Then reproduce the problem so tmux exits, and show me the strace.out and tmux-server*.log files.
