### ISSUE TITLE
Request: predictable name for appimage release

### ISSUE THREAD

**Issue by infokiller** [tmux/tmux#2424]
The latest (stable) release AppImage file is named using the version, for example right now it's `tmux-3.1b-x86_64.AppImage`. That makes it harder to write a script that automatically downloads and installs the latest release.
For example, if the file was always named `tmux-x86_64.AppImage`, one could download and install it using: 

```sh
wget https://github.com/tmux/tmux/releases/tag/latest/tmux-x86_64.AppImage

```

Thanks!

**Comment by nicm** [comment]
I don't think this is a good idea, I think it is pretty standard and useful to have the version number in the file names.

**Comment by infokiller** [comment]
I see the usefulness of having the version number in the name... `tmux-3.1` is more meaningful than `tmux` and less likely to cause some confusion.
That said, it's harder to automate installation. I could use `git ls-remote` to fetch the latest tag, but that feels a bit brittle, unless it's guaranteed that the tag format is `<major>.<minor>a?-rc` (and `<major>.<minor>` for stable releases). Is that the case?

**Comment by nicm** [comment]
It will probably always be `[0-9]+.[0-9][a-z]?` for releases.

**Comment by nicm** [comment]
You could do something with:
~~~~
curl -s https://api.github.com/repos/tmux/tmux/releases/latest|grep AppImage

**Comment by infokiller** [comment]
Thanks!
