### ISSUE TITLE
Escape isn't cancelling command prompt

### ISSUE THREAD

**Issue by Technik-J** [tmux/tmux#2426]
### Issue description
Man pages describe that Escape is used to cancel command prompt, but in version 3.1b and in version from the last commit I cannot do that. When I hit `Esc` command prompt just changes colour. I loaded tmux with default configuration with `tmux -f /dev/null` to be sure that the problem is not with my configuration. I still can cancel command prompt with `ctrl+c`.

Here how it looks:
![tmux-esc-bug](https://user-images.githubusercontent.com/17809291/96349473-61c98600-10c9-11eb-98bf-8047de8cb125.gif)

### Required information

* tmux version from commit 61258008
* Platform Linux x86_64, Linux Mint 19.3
* $TERM inside `xterm-256color` and outside of tmux `screen`
* Logs from tmux
[tmux-client-18935.log](https://github.com/tmux/tmux/files/5396160/tmux-client-18935.log)
[tmux-out-18937.log](https://github.com/tmux/tmux/files/5396161/tmux-out-18937.log)
[tmux-server-18937.log](https://github.com/tmux/tmux/files/5396162/tmux-server-18937.log)

**Comment by krader1961** [comment]
> Man pages describe that Escape is used to cancel command prompt 

You missed the part of the documentation that says it does so in emacs mode.

The problem is due to a conflict with how vi mode works since in vi mode the escape key switches from insert to command mode when editing a command. I use Vim most of the time but within tmux I use emacs mode, in part because of this quirk. From my *~/.tmux.conf*:

```
# Use emacs style keyboard shortcuts. Both because vi mode has some bugs and
# because for trivial editing tasks the emacs mode is easier to use;
# notwithstanding the fact I use Vim.
set-option -g status-keys emacs
set-window-option -g mode-keys emacs
```

**Comment by Technik-J** [comment]
> You missed the part of the documentation that says it does so in emacs mode.

My man pages on my system said otherwise.
![image](https://user-images.githubusercontent.com/17809291/96357894-b812e500-111a-11eb-93f6-9b8b010dedb6.png)

But you right I checked https://man.openbsd.org/OpenBSD-current/man1/tmux.1 and it list other keys for vi mode.
Setting `status-keys emacs` fixes my problem.

Thank you.

**Comment by krader1961** [comment]
`git blame tmux.1` reports that the documentation was corrected with this [change](../commit/b8b48e2e3):

```
b8b48e2e3 tmux.1    (Nicholas Marriott 2020-03-12 09:49:43 +0000 5293) .It Li "Cancel command prompt" Ta "q" Ta "Escape"
```
