### ISSUE TITLE
WINCH signal is not sent to inactive windows

### ISSUE THREAD

**Issue by randomizedthinking** [tmux/tmux#2427]
### Issue description

Active windows under a tmux will receive `WINCH` signal when the terminal size changes, but not the inactive windows. Here I recorded a video to show the problem. Basically, I used the `test-winch.c` provided by @nicm in another thread. We can see that: when the test-winch program is in the current active window, it receives the size change information; but when it is in an inactive window, the `WINCH` signal is not populated to it.

![screenshot](https://user-images.githubusercontent.com/5283430/96361387-1ff50b80-10da-11eb-9775-f309c6116881.gif)

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.1b
* Platform (`uname -sp`): Linux unknown (Debian bullseye/sid)
* $TERM inside and outside of tmux (`echo $TERM`). tmux-256color, rxvt-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
This is intentional, there is no point in resizing panes unnecessarily. They should be resized when their window becomes active.

**Comment by randomizedthinking** [comment]
But it could trigger some problems. For instance, if someone has a vim session in an inactive window, then we have to initialize a screen update manually when switching to it after a terminal size change.

**Comment by nicm** [comment]
No, it should be resized when it becomes the current window.

**Comment by randomizedthinking** [comment]
It won't refresh at least based on what I observed. Not only vim, other terminal programs, like `tig`, will suffer from the same issue. Here I record another video -- where tig is used to show the problem. We can see that: the terminal size changed while tig is not the active window, then if we switch to the tig window, the program is not refreshed properly.

![screenshot](https://user-images.githubusercontent.com/5283430/96372014-bb59a100-1119-11eb-808d-9e51307251d1.gif)

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by randomizedthinking** [comment]
Good. This issue is now resolved by the current master: `next-3.3`. So I will close this issue.

Thanks a lot for the help!
