### ISSUE TITLE
ctrl-k does not copy from shell (zsh, bash)

### ISSUE THREAD

**Issue by jedipunkz** [tmux/tmux#2428]
* tmux version:  tmux 3.0a
* Platform: Linux xwing 5.4.0-51-generic #56-Ubuntu SMP
* $TERM: xterm-256color
* Logs from tmux: none

I can not copy shell by pressing 'ctrl-k' on tmux 3.0a. I read CHANGES and certainly I can copy on Tmux 2.x. Should I need some special configurations? I remove all of .tmux.conf configuration, but same result.

## on native shell (zsh or bash)

```shell
$ aaaaa # <- input some text
$ # press ctrl-k, then it clears text
$ # press ctrl-y, then yank text
$ aaaaa
```

## on tmux 3.0a

```shell
$ aaaaa # <- input some text
$ # press ctrl-k, then it clears text
$ # press ctrl-y, then not yank text. because ctrl-k does not copy from shell.
$ 
```

**Comment by nicm** [comment]
Does this still happen if you start tmux with no .tmux.conf:
~~~~
tmux -vvLtest -f/dev/null new
~~~~

**Comment by jedipunkz** [comment]
This problem does not happen with that command. Following configuration conflict `ctrl-k` shortcut.

```shell
bind-key -n C-y run "xclip -o | tmux load-buffer - ; tmux paste-buffer"
```

I change key binding like below.

```shell
bind-key -n C-v run "xclip -o | tmux load-buffer - ; tmux paste-buffer"
```

But I don't know when these configuration conflict each other.

Thanks, I close this issue.
