### ISSUE TITLE
Tmux gets frozen with RHEL8 and v3.1b

### ISSUE THREAD

**Issue by sksd509** [tmux/tmux#2430]
### Issue description

_Tmux gets frozen_ was reported by me [here](https://github.com/tmux/tmux/issues/2380). I moved to one of the later versions and the freezing has minimised for sure. Still, I see it happening for like maybe ~2 per day in any of the weekdays(when I work :) ).

Can we please **minimise** it more and more?
what would be some awesome **tmux conf** suggestions for the same and I saw some people mention about `c0-change-trigger` but at the same time I get to know it is not available now(post `v2.2`), so please suggest what to do?

### Required information

Please provide the following information:

* tmux version (`tmux -V`) : **tmux.bin 3.1b**
* Platform (`uname -sp`) : **Linux x86_64**
* $TERM inside and outside of tmux (`echo $TERM`) :  **xterm-256color**
* Logs from tmux (`tmux kill-server; tmux -vv new`) : **NA**

**Comment by nicm** [comment]
Logs?

**Comment by sksd509** [comment]
> Logs?

This is something difficult as of now, cause I would have to finish many things running in my tmux as of now.
Let me see when can I get them(depends on when can I finish some important stuff running as of now in my current tmux session).

Any general recommendation is there to prevent freezing of tmux sessions?

**Comment by nicm** [comment]
> Any general recommendation is there to prevent freezing of tmux sessions?

How would I know, you have given virtually no information.

**Comment by sksd509** [comment]
> > Any general recommendation is there to prevent freezing of tmux sessions?
> 
> How would I know, you have given virtually no information.

Sure, @nicm  I understand. Let me come back with logs on this issue as soon as I can get it! 👍

**Comment by nicm** [comment]
What does your .tmux.conf look like?

**Comment by sksd509** [comment]
my tmux.conf is very minimal as of now

```
#for having color support
set -g default-terminal "screen-256color"
#for having scrollback limit set to a limit as u desire
set -g history-limit 10000000

#tmux2.1 and above mouse support
set-option -g mouse on
# make scrolling with wheels work
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

#tmux2.1 and below mouse support
#set -gq mode-mouse on
#set -gq mouse-resize-pane on
#set -gq mouse-select-pane on
#set -gq mouse-select-window on
```

**Comment by nicm** [comment]
I don't see anything in your config, I'm going to close this now, please comment again if you can reproduce with logs.

**Comment by sksd509** [comment]
@nicm , please see the memory it takes when this happens 

 [0s][~]> free -m
```
              total        used        free      shared  buff/cache   available
Mem:          31981        9651         479          19       21850       21855
Swap:         32767        2242       30525
```
Does this help you some say to solve my issue ?

**Comment by nicm** [comment]
No I was thinking more what tmux itself is using, you can see in `top`.

Does the freeze go away if you reduce `history-limit` back to say `10000`?
