### ISSUE TITLE
Source ~/.tmux.conf "syntax error" when having select-layout binding

### ISSUE THREAD

**Issue by edi9999** [tmux/tmux#2431]
### Required information

Please provide the following information:

* tmux version (`tmux -V`). **3.2-rc2** (same issue on master)
* Platform (`uname -sp`). **Linux x86_64**
* $TERM inside and outside of tmux (`echo $TERM`). : Inside : screen-256color , Outside screen-256color 
* Logs from tmux (`tmux kill-server; tmux -vv new`). : No logs from this command
  

With this .tmux.conf : 

```
bind M-6 select-layout cf4d,190x56,0,0{134x56,0,0,19,55x56,135,0,20}
```

When starting tmux, I get : `/home/edgar/.tmux.conf:1: syntax error`.

This line worked well on tmux 3.1b, seems like some kind of regression ?

**Comment by nicm** [comment]
{} needs to be valid tmux syntax. Put it in single quotes.

**Comment by edi9999** [comment]
Ok thanks, works better now :)

It would be cool to have a more precise error, such as : 

```
bind M-6 select-layout cf4d,190x56,0,0{134x56,0,0,19,55x56,135,0,20}
```
