### ISSUE TITLE
Selection text with Shift+Mouse is not working

### ISSUE THREAD

**Issue by airvzxf** [tmux/tmux#2432]
I discovered that the selection mouse is not working usually I selected the text holding the SHIFT button and then the first click on the mouse moving across the screen but I notice today that it's not working anymore, I did my own research, testing the configuration and I noticed that the problem is the option `set -g mouse on` in the file `.tmux.conf` means if I comment this line and close all the xterm/tmux windows then open again a tmux console, all is working again. Also, I discovered that the problem is not at all your code because your last upgrade was on August 2020 but I noticed there is a recent upgrade from xterm, maybe there is some incompatibility between the upgrade and tmux.

tmux 3.1b
Linux unknown
screen
`uname -a`
Linux MSIGT73EVR7RF 5.8.14-arch1-1 #1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000 x86_64 GNU/Linux

Evidence:

History of the upgrades in pacman (package system on ArchLinux).
[2020-09-25T23:12:33-0500] [ALPM] upgraded xterm (358-1 -> 360-1)
[2020-05-04T16:40:43-0500] [ALPM] upgraded tmux (3.0_a-1 -> 3.1_b-1)
[2020-10-06T13:38:46-0500] [ALPM] upgraded xterm (360-1 -> 360-2)
[2020-10-15T12:00:54-0500] [ALPM] upgraded xterm (360-2 -> 361-1)

[tmux-client-932374.log](https://github.com/tmux/tmux/files/5406420/tmux-client-932374.log)
[tmux-client-932641.log](https://github.com/tmux/tmux/files/5406421/tmux-client-932641.log)
[tmux-out-932376.log](https://github.com/tmux/tmux/files/5406422/tmux-out-932376.log)
[tmux-out-932643.log](https://github.com/tmux/tmux/files/5406423/tmux-out-932643.log)
[tmux-server-932376.log](https://github.com/tmux/tmux/files/5406424/tmux-server-932376.log)
[tmux-server-932643.log](https://github.com/tmux/tmux/files/5406425/tmux-server-932643.log)

**Comment by nicm** [comment]
This is a problem with your terminal, tmux does not control what happens
with Shift-Mouse.
