### ISSUE TITLE
{next} and {previous} behaviour inconsistent between 2.8 and 3.0a

### ISSUE THREAD

**Issue by bobf32** [tmux/tmux#2433]
### Issue description

I am having an issue using 3.0a with a WSL install of Ubuntu 20.04 LTS. My tmux conf has the following which works fine in other WSL instances:

`bind-key -n S-PageUp selectw -t {previous}`
`bind-key -n S-PageDown selectw -t {next}`

However in 3.0a hitting e.g. S-PageDown gives an error:

Can't find window: next

Similar if I hit S-PageUp.

I notice that if I change the bindings to:

`bind-key -n S-PageUp selectw -t \{previous\}`
`bind-key -n S-PageDown selectw -t \{next\}`

it works in 3.0a but not 2.8.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
30.a
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
Outisde: xterm-256color
Inside: xterm
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-14048.log](https://github.com/tmux/tmux/files/5434659/tmux-client-14048.log)

**Comment by nicm** [comment]
Put them in single quotes (`'`).

**Comment by bobf32** [comment]
> Put them in single quotes (`'`).

You mean like this?

`bind-key -n S-PageDown selectw -t '{next}'`

It seems to work, but I'm wondering why I haven't needed to do it before?

**Comment by nicm** [comment]
The syntax changed in 3.0.

**Comment by bobf32** [comment]
> The syntax changed in 3.0.

Thanks, that would explain it! Would you mind pointing me to the relevant bit of doc (am guessing it's in the man page somewhere but I'm blowed if I can find it.

**Comment by nicm** [comment]
It was changed to add {} for command sequences, look at the PARSING SYNTAX
section. The fact that { needs to be in quotes was mentioned in the CHANGES
file and IIRC in the release announcement and the discussion issue.

**Comment by bobf32** [comment]
Many thanks.
