### ISSUE TITLE
Nesting format with sed style replacements (like `s/x/y/:#{p10:session_name}`)

### ISSUE THREAD

**Issue by infokiller** [tmux/tmux#2434]
Do sed-like expressions in formats support nesting?
I'm trying to do something like: `s/x/y/:#{p10:session_name}`
Using `s/x/y/:session_name}` (i.e. without nesting) works fine, but the former does not. I fully read the man pages but didn't find an answer. For example, with a session named `CFG` I get:

![image](https://user-images.githubusercontent.com/10516814/97168688-855b9300-1791-11eb-8aa2-426cb11e6e97.png)

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.1b`
* Platform (`uname -sp`): `Linux 5.8.16.a-1-hardened`
* $TERM inside and outside of tmux (`echo $TERM`). Inside `tmux-256color`, outside `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Yes it works but you may need a newer tmux.

**Comment by infokiller** [comment]
Thanks, great, just tested on master and it works indeed. Since I was on the latest stable version, I thought it should work there too.
