### ISSUE TITLE
SIGQUIT not propagating through tmux

### ISSUE THREAD

**Issue by ramn** [tmux/tmux#2435]
### Issue description

Sending SIGQUIT with ctrl-\ no longer propagates to my process. The regression stems from https://github.com/tmux/tmux/commit/82c65e3f3705c2922e88049f9336333781a26e55 - if I comment out the added line in that commit and recompile tmux, I can once again send SIGQUIT to my process.

**Comment by nicm** [comment]
This was added for a reason - which is in the commit message - and is not being reverted. What are you trying to do?

**Comment by ramn** [comment]
I'm trying to send SIGQUIT to my process using `ctrl-\`. Why should this no longer be supported? A rather significant change which forces me to maintain a fork of tmux.

**Comment by nicm** [comment]
This change only prevents you sending C-\ to the tmux client, why would you need to do that?

**Comment by ramn** [comment]
My scenario is: I'm sitting in tmux, I am running a bash script, in which I have trapped SIGQUIT. This worked before, the trap caught SIGQUIT when I pressed `ctrl-\`. After the aforementioned patch, the trap no longer receives SIGQUIT.

**Comment by ramn** [comment]
The change does not only prevent sending `ctrl-\` to the tmux client - it prevents sending `ctrl-\` at all.

**Comment by nicm** [comment]
Are you running tmux from the script?

**Comment by ramn** [comment]
No

**Comment by nicm** [comment]
I think the corresponding bit in proc_clear_signals is missing, does it work if you add that?

**Comment by nicm** [comment]
Add this to the "if (defaults)":
~~~~
               sigaction(SIGQUIT, &sa, NULL);

**Comment by ramn** [comment]
Yes I figured it out, it needs to be set back to `SIG_DFL`. With that change it works!

I'll update my PR

**Comment by nicm** [comment]
It's ok I will apply the fix now.

**Comment by ramn** [comment]
Updated https://github.com/tmux/tmux/pull/2436 in any case.
Thanks for the help!

**Comment by nicm** [comment]
I have applied this fix to OpenBSD now, it should be in GitHub soon. Thanks!
