### ISSUE TITLE
Send prefix to 3rd session (why C-b C-b C-b C-b works ?)

### ISSUE THREAD

**Issue by GuillaumeSeren** [tmux/tmux#2437]
Hey,
thank you for this great project tmux is an awesome tool.

I use tmux for quite some time and there this issue I wanted to fix,
I try to share my configuration between hosts.

My use case is simple,
I use tmux on my laptop, on a pane I connect with ssh to a remote machine (per-project) I have a tmux session there as well,
and sometime this project force me to work on other machine where I also set a tmux session.

That's working fine but, but I used to have a different binding for those machines,
because the expected c-b c-b c-b didn't worked (at least that what I thought).

Today I discovered that to send prefix to the 3rd,
you are supposed to use is 4 and not the expected 3 c-b, with the help of this plugin,
that let you display the active session / prefix combo tmux-plugins/tmux-prefix-highlight.

So my question, is what is c-b c-b c-b supposed to do ?

**Comment by nicm** [comment]
With three nested tmux you will need four C-b. You need two C-b at the first tmux to send one C-b to the second, and you need two C-b at the second tmux to send one to the third. So:

- First tmux C-b C-b C-b C-b -> send C-b C-b to second tmux
- Second tmux C-b C-b -> send C-b to third tmux

**Comment by GuillaumeSeren** [comment]
Ah sure that is well explained,
thank you @nicm
