### ISSUE TITLE
Race condition loading config file when starting server + session

### ISSUE THREAD

**Issue by thomasjm** [tmux/tmux#2438]
### Issue description

I first mentioned this issue on #2196 and was advised to file a bug report.

The problem seems to happen when you create a server with `tmux new-server` and then immediately start a session with `tmux new-session`. There seems to be some kind of race condition that results in `~/.tmux.conf` sometimes being loaded in the resulting session, and sometimes not. For example, if your config file changes your status bar color, sometimes it will be changed and sometimes it will be the default green color.

I made a nice Docker repro here: https://github.com/thomasjm/tmux-race-repro

The repro builds `tmux` `3.1b` (or `master` if you edit the `Dockerfile`) inside a Ubuntu 20.04 image and then launches it the way I describe. If you launch it several times you should see the race condition happening.

The odds seem to be about 50/50 on `3.1b`. Strangely on `master` it seems to be more consistent, failing to load the config every time.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): my repro works (with slightly different problems) on on either `3.1b` or `master`
* Platform (`uname -sp`): `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`). `screen-256color` outside of tmux. Inside, it's either `screen` or `screen-256color`, depending which side of the race condition wins :)
* Logs from tmux (`tmux kill-server; tmux -vv new`). I'm not seeing log files appear for some reason...

**Comment by nicm** [comment]
You will need to get logs from reproducing. Are you sure tmux is not running before you start it with -vv, and that you are looking for the logs in the directory where you started tmux?

**Comment by nicm** [comment]
I can't reproduce by doing this with master:
~~~~
rm tmux*.log; ./tmux -Ltest -vv start-server & ./tmux -Ltest -vv new -t session1
~~~~
Can you reproduce like this?

**Comment by nicm** [comment]
If you can reproduce like above, does the problem go away if you do this first?
~~~~
mkdir tmptmp; export TMUX_TMPDIR=$PWD/tmptmp
~~~~

**Comment by thomasjm** [comment]
Thanks for the quick response! A couple thoughts:

* Oh, I couldn't find the logs because of a typo in my Dockerfile. Just pushed a fix. Attached are the logs from a failure:

[tmux-client-6.log](https://github.com/tmux/tmux/files/5450730/tmux-client-6.log)
[tmux-client-7.log](https://github.com/tmux/tmux/files/5450731/tmux-client-7.log)
[tmux-out-9.log](https://github.com/tmux/tmux/files/5450732/tmux-out-9.log)
[tmux-server-9.log](https://github.com/tmux/tmux/files/5450733/tmux-server-9.log)

* I've been using the Docker approach because it makes it easier to try different versions. I haven't built tmux outside of Docker but I can do that if it would help. Did the Docker repro not work for you?
* For me, `master` and `3.1b` have slightly different failures. `master` fails to load `~/.tmux.conf` **every time**. `3.1b` fails sometimes and succeeds sometimes.
* When using `mkdir tmptmp; export TMUX_TMPDIR=$PWD/tmptmp`:
  * On `3.1b` it makes no difference
  * On `master` it also makes no difference

**Comment by nicm** [comment]
I don't really have time to set up other programs to test with. There is no point in testing with 3.1b because it is now done and will not change, please test with master.

**Comment by nicm** [comment]
I think this is something to do with `start-server`...

**Comment by nicm** [comment]
It doesn't look like it is running the config correctly.

**Comment by nicm** [comment]
OK I think this is the problem, you are right that there is a race. If the second client is added before the first finishes identifying, then we skip loading the config.

I don't think we need to make sure there are no other clients, only if the client is the first on the list. Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/5450964/x.diff.txt)

**Comment by thomasjm** [comment]
Hmm that diff is not applying for me on latest `master`...

**Comment by nicm** [comment]
Works for me:
~~~~
$ git pull
Current branch master is up to date.
$ patch </home/nicholas/x.diff.txt
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|Index: server-client.c
|===================================================================
|RCS file: /cvs/src/usr.bin/tmux/server-client.c,v
|retrieving revision 1.361
|diff -u -p -r1.361 server-client.c
|--- server-client.c    22 Sep 2020 05:23:34 -0000      1.361
|+++ server-client.c    28 Oct 2020 09:50:08 -0000
--------------------------
Patching file server-client.c using Plan A...
Hunk #1 succeeded at 2245 with fuzz 2 (offset 2 lines).
Hunk #2 succeeded at 2260 (offset 2 lines).
done
$
~~~~

**Comment by thomasjm** [comment]
Oh, I was trying to use `git apply` instead of `patch`. Works now, testing...

**Comment by thomasjm** [comment]
Awesome, seems to fix `master`! Thanks for the quick turnaround!

I would really like a way to backport the fix to `3.1b` (or latest stable release) though, until a new release with the fix comes out. Would that be hard do you think? (The patch doesn't apply cleanly.)

**Comment by thomasjm** [comment]
Actually nvm, seems easy to adapt to `3.1b`

**Comment by nicm** [comment]
I think it will apply to 3.1b if you remove the indentation change at the start.

**Comment by thomasjm** [comment]
`3.1b` seems to be fixed too! Hallelujah

**Comment by nicm** [comment]
This is applied now, thanks!
