### ISSUE TITLE
Persistent right click menu

### ISSUE THREAD

**Issue by teodor440** [tmux/tmux#2439]
Feature request

So all applications in gnome display a right-click menu that persists after on mouse up and can select options by left click or make it dissaper if clicked outside its boundaries. It would be nice if tmux would be consistent with that.

More precisely: 
- after right clicking and leaving the menu box it will remain opened
- if clicked outside the borders the menu will close
- it should be hard to make accidental clicks on the menu

**Comment by nicm** [comment]
I like it the way it is.

**Comment by teodor440** [comment]
Ah oki
Where I can find the event that closes the menu when the mouse is released? I'm still thinking about modifying it and maybe do a PR for other users to be able to choose which behavior it will have

**Comment by nicm** [comment]
Look at menu.c:menu_key_cb. You could add a flag like MENU_STAYOPEN and then pass it based on a command argument to display-menu.

**Comment by teodor440** [comment]
Thanks :)

**Comment by teodor440** [comment]
So I might be doing sth wrong, when I try to parse a command line arg I edit `cmd_display_menu_entry.args = { "c:t:T:x:y:O", 1, -1 }`, check inside `cmd_display_menu_exec` `if args_has(args, 'O')`, and when I pass the argument in `.tmux.conf` I am able to pass it only like : `bind-key  -T root  MouseDown3Status -O      display-menu -T "#[align=centre]#{window_index}:#{window_name}" -t = -x W -y S ...` but I thought I was supposed to pass it like `bind-key  -T root  MouseDown3Status       display-menu -O -T "#[align=centre]#{window_index}:#{window_name}" -t = -x W -y S ...`. Is it ok to do it like this?

**Comment by teodor440** [comment]
I don't really see an error, it just ignores my option argument, let me check a little further

**Comment by nicm** [comment]
Do you want to check if the argument exists or doesn't exist?

**Comment by teodor440** [comment]
If it is provided. Actually it is a problem in my config file only for one menu, the others are ok
```
# Pane
bind -n MouseDown3Pane  if -Ft= '#{||:#{mouse_any_flag},#{&&:#{pane_in_mode},#{?#{m/r:(copy|view)-mode,#{pane_mode}},0,1}}}' { select-pane -t=; send -M } { display-menu -O -t= -xM -yM -T '#[align=centre]#{pane_index} (#{pane_id})' \
	" '#{?#{m/r:(copy|view)-mode,#{pane_mode}},Go To Top,}' '<' {send -X history-top}" \
	" '#{?#{m/r:(copy|view)-mode,#{pane_mode}},Go To Bottom,}' '>' {send -X history-bottom}" \
	" ''" \
	" '#{?mouse_word,Search For #[underscore]#{=/9/...:mouse_word},}' 'C-r' {if -F '#{?#{m/r:(copy|view)-mode,#{pane_mode}},0,1}' 'copy-mode -t='; send -Xt= search-backward \"#{q:mouse_word}\"}" \
	" '#{?mouse_word,Type #[underscore]#{=/9/...:mouse_word},}' 'C-y' {copy-mode -q; send-keys -l -- \"#{q:mouse_word}\"}" \
	" '#{?mouse_word,Copy #[underscore]#{=/9/...:mouse_word},}' 'c' {copy-mode -q; set-buffer -- \"#{q:mouse_word}\"}" \
	" '#{?mouse_line,Copy Line,}' 'l' {copy-mode -q; set-buffer -- \"#{q:mouse_line}\"}" \
	" ''" \
	" 'Horizontal Split' 'h' {split-window -h}" \
	" 'Vertical Split' 'v' {split-window -v}" \
	" ''" \
	" '#{?#{>:#{window_panes},1},,-}Swap Up' 'u' {swap-pane -U}" \
	" '#{?#{>:#{window_panes},1},,-}Swap Down' 'd' {swap-pane -D}" \
	" '#{?pane_marked_set,,-}Swap Marked' 's' {swap-pane}" \
	" ''" \
	" 'Kill' 'X' {kill-pane}" \
	" 'Respawn' 'R' {respawn-pane -k}" \
	" '#{?pane_marked,Unmark,Mark}' 'm' {select-pane -m}" \
	" '#{?#{>:#{window_panes},1},,-}#{?window_zoomed_flag,Unzoom,Zoom}' 'z' {resize-pane -Z}" \
	}, \
```

**Comment by nicm** [comment]
Not sure, looks OK to me.

**Comment by nicm** [comment]
Show me the code changes you have.

**Comment by teodor440** [comment]
I have workaround for this but it loses some functionality, I'll look more into it and hopefully I'll come with a PR tonight

**Comment by teodor440** [comment]
I leave here a gist with my current config file that enables the desired behavior [gist](https://gist.github.com/teodor440/37109df401afa03d03075df85f9aaac7)

**Comment by nicm** [comment]
Closing this as we have moved discussion to PR.
