### ISSUE TITLE
[Question/Feature Request] Synchronize only specific panes

### ISSUE THREAD

**Issue by ThaDaVos** [tmux/tmux#2440]
### Issue description

The synchronize panes feature is really cool but it would be cooler if one could choose which panes to synchronize. Currently I've got a lot of mono-repo projects with submodules and I split my tmux as follows;

| Project Mono | SubProject 1 | SubProject 2 | SubProject 3 |
| - | - | - | - |
| Docker | Docker | Docker | NPM |
| gitsh | gitsh | gitsh | gitsh |

Sometimes I want to run a command only on the all of the SubProject panes, for example `composer install`
Other times I want to run a command inside the three `gitsh` of the subprojects, for example `pull` to pull the latest changes.

If it's possible, how would one only synchronise a portion of their panes? And if now, would it be possible to add this?

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.1b
* Platform (`uname -sp`). Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). screen-256color and screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
You can stop panes being synchronized by disabling them with `select-pane -d`.
