### ISSUE TITLE
[Question/Feature Request] Set copy-mode line numbers to start from the top.

### ISSUE THREAD

**Issue by Joshuao95** [tmux/tmux#2441]
Hi,
When in copy mode, is there a way to have the line number `[0 / 30]` start counting from the top, rather than the bottom?
e.g: When you first enter copy mode, it should show `[x/x]` , and if you scroll all the way to the top it should be `[0/x]`

This would be nice for me, because the line numbers at the moment aren't particularly useful, since they change as more lines are added.

**Comment by nicm** [comment]
No the intent is to show how far you are into the history.

**Comment by Joshuao95** [comment]
Is there any chance it could be made a config?

I understand that logic, but it does go against most implementations of line numbering.

And I think "This line is 3000 lines from the start of history" is more often useful than "This happened 3000 lines ago".

**Comment by nicm** [comment]
I don't think we need two ways of showing the same thing. The most recent text is at the bottom, you scroll up from the bottom. It makes sense to number from the bottom.

**Comment by Joshuao95** [comment]
It's not really the same thing though.

If you want to refer back to a line again, you have to currently remember:
1. The number your line was at when you saw it previously
2. The number of total lines when you saw it previously
Then you have to subtract 1. from 2. to get the offset and minus that from the current number of lines.

That's a lot of steps to refer to a previous historical line, which is presumably the main point of a scrollback history.
At the moment, the convinience is placed on "going back a specific number of lines from the bottom", which I dare say is almost never useful.

**Comment by nicm** [comment]
No the main point is to show how far you are back through the history. You would have the same problem if lines were numbered from the top because they are removed from the top when they are added to the bottom. There is no static line number that always refers to the same line.

**Comment by nicm** [comment]
We could make it a format but I am not convinced there is much point at the moment since it seems like all the possible things you could show in there are just the same thing shown in different ways.

Someone talked about adding timestamps to the lines and that would be useful - then we could show the time of the newest or oldest visible line, which would be fixed.

**Comment by nicm** [comment]
Give this a try which will try to show the time the top line was scrolled into the history: [tmux-time.diff.txt](https://github.com/tmux/tmux/files/5457261/tmux-time.diff.txt)

This does need a bit of further work (not least what to show if the time was yesterday, or a month ago).

**Comment by Joshuao95** [comment]
Okay, thanks for that, I'll take a look.
I'll close.
