### ISSUE TITLE
tmux exits immediately

### ISSUE THREAD

**Issue by pcwilcox** [tmux/tmux#2443]
### tmux exits immediately on start

tmux won't start for me, even with minimal or no .tmux.conf defined. When I attempt to start it, the display briefly shows the tmux screen, then it returns to the shell with the following:

```
❯ tmux new -s start
[exited]
```

The behavior is the same for me either with no config, or when my config is just the following:

```
set -g default-terminal "screen-256color"
set -g default-shell "/bin/zsh"
```

### Required information

```
❯ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 3.1b
xterm-256color
```

Interestingly the terminal doesn't seem to change if I include the `default-terminal` directive in the .conf file:
```
❯ tmux -c "echo $TERM"
xterm-256color
```

Collecting logs:
```
❯ tmux -Ltest kill-server
no server running on /private/tmp/tmux-501/test

❯ tmux -vv -Ltest -f/dev/null new
[exited]
```

I'm sure I've just messed up something in my config or something but I can't for the life of me figure out what it is.

[tmux-client-99129.log](https://github.com/tmux/tmux/files/5460864/tmux-client-99129.log)
[tmux-out-99131.log](https://github.com/tmux/tmux/files/5460865/tmux-out-99131.log)
[tmux-server-99131.log](https://github.com/tmux/tmux/files/5460866/tmux-server-99131.log)

**Comment by nicm** [comment]
Nothing obvious in logs, but most likely is your shell is exiting.

Does it still exit if you do:
~~~~
tmux new -- sleep 100
~~~~
What if you use a different shell? Or tell it to run without loading profile files?

**Comment by pcwilcox** [comment]
`tmux new -- sleep 100` causes it to open the tmux display for the sleep period before exiting.

I've tried a couple of different shells and they're all exiting from tmux immediately.

Hunted through profile files and found an errant one that said `source ~/.bashrc`. After removing that one, and changing the `default-shell` directive to `/bin/sh`, tmux will open. However I still can't load into either bash or zsh.

**Comment by nicm** [comment]
What if you open tmux with /bin/sh and then run bash or zsh manually? Does it work?

What if you do `tmux new -- bash --noprofile --norc`?

**Comment by krader1961** [comment]
Given what you've reported so far I would expect `script x /bin/zsh` to exit immediately as well. That is, it should output something like this without giving you a zsh interactive prompt:

```
> script x /bin/zsh
Script started, output file is x
Script done, output file is x
```

There might be something written between those two lines which could be illuminating. What happens if you just run `/bin/zsh` from a shell prompt? Do you get a nested shell as shown by the value of `$SHLVL`?

**Comment by pcwilcox** [comment]
> What if you open tmux with /bin/sh and then run bash or zsh manually? Does it work?

No, which was illuminating. The next thing I tried was to open tmux with /bin/sh and then run both with -x set e.g. `/bin/zsh -x` and this seems to have identified a problem in one of my dotfiles. It's curious that this doesn't prevent zsh from loading outside of tmux but does prevent it inside of tmux. 

> What if you do tmux new -- bash --noprofile --norc?

This gives me a working bash shell.

```
> script x /bin/zsh
Script started, output file is x
Script done, output file is x
```

This gives me an interactive shell in between with `$SHLVL == 2`.

I think I have identified that the error is in my dotfile configurations (as I expected tbh), should I close this or would more input be helpful?

**Comment by krader1961** [comment]
> This gives me an interactive shell in between with $SHLVL == 2.

That is surprising given what else you've written about this problem. Regardless, you should document the root cause of your problem to help others who might stumble upon this issue then close it.

**Comment by pcwilcox** [comment]
So it turns out this was a dotfile configuration issue where I was setting a flag when a particular set of steps was completed, and checking for that flag prior to beginning those steps. Here is a minimal example:

```
 if [ ${X+x} ]; then
     exit
fi
```

What I did not realize is that setting this flag was carrying over to the tmux session, causing the session to hit this condition with `X` being set, and thus exiting. This caused tmux to work when running with no profile files in place and fail when they were loaded even though regular shells would load fine. So I guess my suggestion for debugging this would be to first check the steps suggested earlier in this thread, and then to try setting `-x` in your profile files and seeing if the execution is different between a regular shell and within a tmux.

Thanks for your help figuring this out!

**Comment by krader1961** [comment]
@pcwilcox, I consider using the expression `[ ${X+x} ]` to determine if a var is set to be an anti-pattern. That is, something to be avoided for many reasons. In your case it's a problem because `X` is an env var and thus "carrying over to the tmux session" because that is how env vars work -- they are inherited.

Using your shell initialization dot files, in conjunction with env vars, for this type of logic is always a really bad idea. As you just learned :smile:

**Comment by nicm** [comment]
X should only be an actual environment variable if it is exported, otherwise it should be internal to the shell. Or maybe zsh doesn't differentiate?
