### ISSUE TITLE
Selection is missing last character

### ISSUE THREAD

**Issue by EivindYN** [tmux/tmux#2444]
* tmux version (`tmux -V`): tmux 2.6 (newest)
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): inside = screen, outside = xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`): [server exited]

The same issue as this one: https://github.com/tmux/tmux/issues/1579  
Can you either add a setting for changing this behaviour, or change the default behaviour. It's frustrating missing the last letter every time I copy paste because of this.

**Comment by nicm** [comment]
If you want vi style selection you will need to use vi mode.

**Comment by EivindYN** [comment]
How would you do that? I tried: `set-window-option -g mode-keys vi` but then I couldn't copy at all. I also have this in my tmux.config:
```
# Lets you scroll and switch pane by mouse click
set -g mouse on
## Clipboard integration
# send marked text to clipboard
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection-and-cancel \; run -b "tmux show-buffer | clip.exe" # \; select-pane -M
# ctrl+v or right click to paste from clipboard
bind -T root MouseDown3Pane run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer" \; select-pane -M
bind -T root C-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer" \; select-pane -M
```
Which may ruin something.

I'm pretty inexperienced so any guidance would be super helpful!

**Comment by nicm** [comment]
`set -g mode-keys vi` is correct, but you will need to use vi keys to navigate and copy. Look at https://github.com/tmux/tmux/wiki/Getting-Started#copy-mode-key-bindings.

If you use emacs keys then the selection does not include the cursor.
