### ISSUE TITLE
[Feature Request] Pinned copy buffers.

### ISSUE THREAD

**Issue by hq6** [tmux/tmux#2446]
Currently, when we use the standard tmux copy functionality, everything previously copied gets bumped down by one buffer and the last item drops off the list.

I think it would be useful to be able to mark a copy buffer as "pinned" so that it never drops off.
For example, if I am copying and pasting several items, but there is one item I frequently paste, I'd like to keep that one from being removed.

**Comment by nicm** [comment]
Man page:
~~~~
     tmux maintains a set of named paste buffers.  Each buffer may be either
     **explicitly** or automatically named.  Explicitly named buffers are named
     when created with the set-buffer or load-buffer commands, or by renaming
     an automatically named buffer with set-buffer -n.  Automatically named
     buffers are given a name such as ‘buffer0001’, ‘buffer0002’ and so on.
     When the buffer-limit option is reached, the oldest automatically named
     buffer is deleted.  **Explicitly named buffers are not subject to
     buffer-limit** and may be deleted with the delete-buffer command.

**Comment by hq6** [comment]
Thanks, sorry I missed that part!
