### ISSUE TITLE
window-active-style defaults to window-style

### ISSUE THREAD

**Issue by pbartyik** [tmux/tmux#2447]
### Issue description
I'm trying to get a solution going where I differentiate between active/inactive panes by background color.
My default terminal background is transparent with Alacritty. Initially I wanted to change levels of transparency for inactive panes to dim them a bit, however appears to be that this is not possible (please do let me know if this can be accomplished).

Case 1 settings:
```
set -g window=style 'fg=default,bg=default'
set -g window-active-style 'fg=default,bg=#1f2d3a
```
Case 1 achieves active pane to be solid color, inactive pane to be transparent.
However the reverse settings is not true.

Case 2 settings:
```
set -g window-style 'fg=default,bg=#1f2d3a'
set -g window-active-style 'fg=default,bg=default'
```
Case 2 gets both active and inactive panes to be solid color, instead of active pane being transparent (also tried with `set -g window-active-style default`).

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `next-3.3` (latest git)
* Platform (`uname -sp`). `Linux unknown` (Arch)
* $TERM inside and outside of tmux (`echo $TERM`). inside `tmux-256color` outside `alacritty`
* Logs from tmux (`tmux kill-server; tmux -vv new`). I don't think this is needed for this issue.

**Comment by nicm** [comment]
If you want it to use their terminal default colour instead of inheriting from other options, use `terminal` not `default`.

**Comment by pbartyik** [comment]
thanks!
