### ISSUE TITLE
Move tmux.vim to separate repo

### ISSUE THREAD

**Issue by keith** [tmux/tmux#245]
Any chance tmux.vim could be moved to a separate repo so that vim plugin managers could import it correctly? I've been lightly maintaining a [fork](https://github.com/keith/tmux.vim) of the tmux vim runtime files from this repo so that I could import it in vim. It's also even gotten [some contributions](https://github.com/keith/tmux.vim/pulls?q=is%3Apr+is%3Aclosed). I think it would be great if the runtime files were in their own repo so that users could easily pull them in through whatever vim plugin manager they use. And now that there's an org on github this is the perfect opportunity!

**Comment by ThomasAdam** [comment]
Grief, no.

**Comment by nicm** [comment]
If someone will maintain it outside tmux we could remove it from the tmux repo.

**Comment by keith** [comment]
@ThomasAdam ?

@nicm I would definitely be happy to help maintain it. It also seems like at this point most of the maintenance is just keeping up with keywords.

**Comment by ThomasAdam** [comment]
I really wouldn't want a separate repository just for tmux.vim---which is how things read originally.  But if someone else wants to maintain it, and drag it closer to vim, I'm all for that.  Beyond keeping it in sync with keyword changes coming out of tmux, what more work is there to be done on it, which isn't happening already?

**Comment by keith** [comment]
I can't think of any other big maintenance pains. Again the only reason it would be nice to be in its own repo is for vim package managers which expect the specific folder structure, along with not having to download the entire tmux source to include the vim files.

**Comment by nicm** [comment]
I do not want another tmux repository for it but if someone wants to take it away and maintain it elsewhere so we can add a URL to the README file and never hear of it again - sure, that'd be good.
On 23 Dec 2015 18:40, Keith Smiley <notifications@github.com> wrote:I can't think of any other big maintenance pains. Again the only reason it would be nice to be in its own repo is for vim package managers which expect the specific folder structure, along with not having to download the entire tmux source to include the vim files.

**Comment by keith** [comment]
Alright, if you wouldn't like a new tmux repo for this than I'll keep maintaining mine! https://github.com/keith/tmux.vim

Thanks!

**Comment by nicm** [comment]
Sure, does this mean you are ok with being the official tmux.vim and we can remove our copy?
On 23 Dec 2015 19:03, Keith Smiley <notifications@github.com> wrote:Alright, if you wouldn't like a new tmux repo for this than I'll keep maintaining mine! https://github.com/keith/tmux.vim

Thanks!

**Comment by ThomasAdam** [comment]
On Wed, Dec 23, 2015 at 11:57:09AM -0800, Nicholas Marriott wrote:
> Sure, does this mean you are ok with being the official tmux.vim and we can remove our copy?

Be wary of adding this to our README file, since these sort of
"official" documents get moved around/deprecated/sent upstream all the
time, and keeping a URL around for this seems pointless, IMO.

-- Thomas Adam

-- 
"Deep in my heart I wish I was wrong.  But deep in my heart I know I am
not." -- Morrissey ("Girl Least Likely To" -- off of Viva Hate.)

**Comment by keith** [comment]
I'd be happy to. But I also think people would feel better about @ThomasAdam's point if this were a repo under the tmux org.

**Comment by ThomasAdam** [comment]
On Wed, Dec 23, 2015 at 12:02:18PM -0800, Keith Smiley wrote:
> I'd be happy to. But I also think people would feel better about
> @ThomasAdam's point if this were a repo under the tmux org.

No.  I'm not advocating for this at all.

-- Thomas Adam

-- 
"Deep in my heart I wish I was wrong.  But deep in my heart I know I am
not." -- Morrissey ("Girl Least Likely To" -- off of Viva Hate.)

**Comment by keith** [comment]
Yea, I was just saying that things getting moved around is less likely to happen under an official org. I'm still happy to have this URL, or not, point to my repo.

**Comment by nicm** [comment]
Ok I have linked to your repo instead.

**Comment by keith** [comment]
Thanks!
