### ISSUE TITLE
wrong bright color if client uses TERM with 24bit color

### ISSUE THREAD

**Issue by nia1048596** [tmux/tmux#2450]
### Issue description

I used TERM `konsole-direct` outside tmux and `tmux-256color` inside tmux.

In tmux if I type `tput setaf 9; echo 123` it should print text `123` with bright red foreground color but I got a black text `123` instead.

From the attached tmux output log file, the command `tput setaf 9 | xxd` confirmed that it produced `^[[91m` and the command `tput setaf 9; echo 123` produced `^[[38;2;0;0;9m123`. So somehow tmux changed the escape sequence to `^[[38;2;0;0;9m`. (And in fact it was not a black `123` but a `#000009` colored `123`.)

If I detach tmux and re-attach with client TERM set to `xterm-256color` the text `123` will show the correct bright red color.

I browsed the source code:
https://github.com/tmux/tmux/blob/ffe39edf2fdd8f0489c05022ca8f6e9994396881/tty.c#L2551-L2559

My guess is that tmux went to line `tty_putcode1(tty, TTYC_SETAF, gc->fg - 90 + 8);` and referring to `konsole-direct` terminfo entry:
```
$ infocmp | grep setaf
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e38;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%d%;m,
```
it produced `^[[38;2;0;0;9m123`.

Changing the line `if (tty->term->flags & TERM_256COLOURS) {` to include direct color as well may solve the problem.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
3.1b
* Platform (`uname -sp`).
Linux Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
* $TERM inside and outside of tmux (`echo $TERM`).
inside: tmux-256color
outside: konsole-direct
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-3637186.log](https://github.com/tmux/tmux/files/5470496/tmux-client-3637186.log)
[tmux-out-3637188.log](https://github.com/tmux/tmux/files/5470497/tmux-out-3637188.log)
[tmux-server-3637188.log](https://github.com/tmux/tmux/files/5470498/tmux-server-3637188.log)

**Comment by nicm** [comment]
Does this still happen with master? If so please show me the server log  from master.

**Comment by nia1048596** [comment]
The master doesn't have this issue anymore.

Using git bisect gives me 5e38d262 with correct behavior. Somewhere in

- 5ec80bd2
- 4744aa43
- b2443aa2

fixed the issue.
