### ISSUE TITLE
Search for strikethrough text in copy mode

### ISSUE THREAD

**Issue by dbogdanov** [tmux/tmux#2451]
### Issue description

Is there a way to search for stikethrough text inside the copy mode? 

Entering the copy mode, search up and search down do not recognize text which is strikethrough. 

### Required information

Please provide the following information:

* tmux 3.1b
* Darwin i386
* TERM = `screen-256color` inside tmux, `xterm-256color` outside.

**Comment by nicm** [comment]
Works fine for me with master.

**Comment by dbogdanov** [comment]
Sorry, my fault, I've figured it out.
