### ISSUE TITLE
Location is a little bit off after upgrade to tmux 3.1c

### ISSUE THREAD

**Issue by frankxzhang** [tmux/tmux#2452]
### Issue description

After upgraded from tmux 3.1b to tmux 3.1c, the location shown on status bar at the bottom is a little bit off. For example, I am in Canton MA, before upgrade, it was the right location. But after upgrade, it shows Brockton MA. When I took my computer to another town, I have the same problem, the location is not right.

### Required information

Please provide the following information:

* tmux version: tmux 3.1c
* Platform: Darwin i386
* $TERM inside and outside of tmux: xterm-256color

**Comment by nicm** [comment]
You will need to talk to whoever wrote the script you are using.

**Comment by frankxzhang** [comment]
> You will need to talk to whoever wrote the script you are using.

Thanks, good to know.
