### ISSUE TITLE
Characters in output while running vbs script

### ISSUE THREAD

**Issue by RobinHarteveld** [tmux/tmux#2454]
^[OP^[OP shown in windows with VBS script active

I have a VBS script active with a sendkeys command to keep my windows machine from locking. (I send a scrolllock every 5 minutes). But when I use tmux I get strange characters inside de session. The characters are passed to the cli of the device. (which results in input/cli errors during config-work

Do you recognise the characters? What could cause it?

* tmux version 2.6
* Platform Ubuntu Linux x86_64
* Xterm / screen

**Comment by nicm** [comment]
`^[OP` is `F1`.

**Comment by RobinHarteveld** [comment]
Hello Nicolas, thanks for your reply.
But I do not send the functionkey F1 in my script.

And when I only open putty (without tmux session) I do not get the error.

**Comment by nicm** [comment]
What do you send? Where are the logs from tmux showing this?

**Comment by RobinHarteveld** [comment]
I use a VBS-script like the one on:
https://superuser.com/questions/329758/how-can-i-prevent-a-policy-enforced-screen-lock-in-windows

The command I use is: objShell.sendkeys("{SCROLLLOCK}"). 

As a result I get the ^[OP^[OP inside the active window (SSH session to a network device) So not in logs, but as input to the window.
Problem is during configuration it is added to my input. Sometimes it messes up my commands

"sh^[OP^[OPow ip int br" results in a syntax error because of the extra input. If I connect directly to the SSH device (without TMUX) there is no problem while running the VBS.

**Comment by nicm** [comment]
No I mean tmux logs. Run for example:
~~~~
tmux -vvLtest -f/dev/null new
~~~~
Then reproduce the problem and when it happens, kill tmux and look for the tmux-server-*.log file in the directory where you started tmux. Add the log file to this issue and I will look and see what keys it is receiving.

**Comment by RobinHarteveld** [comment]
Thanks for helping me.

[tmux-server.log](https://github.com/tmux/tmux/files/5523226/tmux-server.log)


For the test I started a ping to an unreachable address. Between the 5th en 7th ping, I saw the OPOP in the session.

Unfortunatly I am not allowed to upload the complet log. I attached a portion of it. Hope its in there.

**Comment by nicm** [comment]
tmux is definitely receiving the keys. You could just bind F1 to do nothing: `bind -n F1 send`

**Comment by RobinHarteveld** [comment]
Ok, that's a good work-around for me.

Thanks a lot!!!

**Comment by nicm** [comment]
OK. This seems most likely to be a problem with your terminal or something rather than tmux but there are so many pieces it is probably more trouble than it is worth to track down if you don't need the F1 key to work.
