### ISSUE TITLE
[Feature Request] Reorder windows from choose-tree

### ISSUE THREAD

**Issue by habys** [tmux/tmux#2456]
### Ability to reorder windows from choose-tree

While in choose-tree, it would be very useful to be able to "drag" the current window to a new location via S-Up, S-Down.

I tried to do this via `bind -T choose-tree S-Up swap-window -t -1` but I don't think that's correct.

**Comment by nicm** [comment]
This is already one the todo list, but it is not easy.

The best way at the moment is to mark the pane or window with `m` and then do `: swap-pane` or `: swap-window`.
