### ISSUE TITLE
Lose mouse support if use ctrl-c to terminate a fzf popup

### ISSUE THREAD

**Issue by Aloxaf** [tmux/tmux#2458]
### Issue description

The mouse support is lost and cannot be enabled again if I terminate a popup with fzf running in it.

https://github.com/tmux/tmux/commit/ce2b6ff40e13fd25f359cfe3faad49b094aad115 is ok, but https://github.com/tmux/tmux/commit/ffe39edf2fdd8f0489c05022ca8f6e9994396881 has this bug.

### Steps to reproduce

- run tmux in konsole
- enable mouse support with `tmux set -g mouse on`
- run `tmux popup -KE -R "fzf"` to get a popup
- use `Ctrl-C` to terminate it
- mouse support is lost

### Required information

```
❯ uname -sp && ./tmux -V && echo $TERM
Linux unknown
tmux next-3.3
xterm-256color
❯ konsole --version
konsole 20.08.3
```

[tmux-server-920569.log](https://github.com/tmux/tmux/files/5502419/tmux-server-920569.log)
[tmux-out-920569.log](https://github.com/tmux/tmux/files/5502420/tmux-out-920569.log)
[tmux-client-920567.log](https://github.com/tmux/tmux/files/5502422/tmux-client-920567.log)

**Comment by carlocab** [comment]
I was just about to file this issue. I have the same problem, on macOS 10.15.7 `Darwin i386`.

I can reproduce it by running `tmux -Ltest -f/dev/null`, and then, once in tmux,

    tmux set mouse on
    tmux popup -KER fzf

Scrolling up after activating the mouse enters copy mode, but only seems to send up arrow keys to my terminal after the second command. (iTerm2 scrolls back using its own buffer. Alacritty cycles through the command history.)

I was initially under the impression that this bug emerges when you run shell commands that capture mouse events, but this isn't true. Running Neovim in a popup window (and scrolling around to check that it registers the mouse) doesn't result in the same problem.

**Comment by Aloxaf** [comment]
A temporary workaround: add `--no-mouse` to fzf's args.

**Comment by carlocab** [comment]
I've also found that detaching then re-attaching works, though that can get annoying to do.

**Comment by carlocab** [comment]
I think this might be an fzf issue, and not a problem with tmux: https://github.com/junegunn/fzf/issues/2161

Unless you can reproduce it with another app, @Aloxaf? I haven't managed to do so.

**Comment by Aloxaf** [comment]
> Unless you can reproduce it with another app in a popup, @Aloxaf? I haven't managed to do so.

No, except skim, which is fzf's fork.

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/5509170/x.diff.txt)

**Comment by Aloxaf** [comment]
> Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/5509170/x.diff.txt)

Yes. This patch works well.
Thank you very much!

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
