### ISSUE TITLE
nano corrects a buggy display in tmux ?

### ISSUE THREAD

**Issue by Raizo62** [tmux/tmux#2459]
Hi

I use (and develop) the linux distribution [LiveRaizo](https://sourceforge.net/projects/live-raizo/)

In LiveRaizo, there is a the gui emulator "GNS3" which contains a VM called Debian. This VM uses tmux (3.1c-1~bpo10+1)

Out of tmux, the command "ip a" displays correctly :
![without_tmux1](https://user-images.githubusercontent.com/7449584/98847881-3714e800-2451-11eb-9d70-d1b3e2c5f260.PNG)
But if i start "tmux" and do the same command, the display is not correct :
![in_tmux1](https://user-images.githubusercontent.com/7449584/98848770-7d1e7b80-2452-11eb-86a3-6f8e5f7ec286.PNG)
I don't know exactly how to reproduce, but the green tab can go up :
![in_tmux2](https://user-images.githubusercontent.com/7449584/98848031-69bee080-2451-11eb-9100-0002f023c3ff.PNG)

if i start nano in tmux, the bug is still there

But, if i reboot the VM (to reinitialize all).

I start "nano" and exit it.
i start "tmux", the command "ip a"  displays correctly :
![with_nano_in_tmux1](https://user-images.githubusercontent.com/7449584/98849061-e605f380-2452-11eb-80c6-f9dbd342cba3.PNG)

To information,

- GNS3 uses serial access to the console of the VM.
- the XTERM is linux

I didn't find the linux command, or the tmux config to correct the display in tmux without start "nano" before.

I added the command "tput rmam" if shell is in tmux (/etc/zsh/raizo.zshrc). It works if LiveRaizo is in VirtualBox, but not in more power PC.

Do you have an idea ?

**Comment by nicm** [comment]
Are you sure `linux` is the correct `TERM` for this terminal emulator? Can you reproduce on a real Linux console with the same `TERM`?

Does it fix it if you add `set -as terminal-overrides '*:am@'` to .tmux.conf and restart tmux (`tmux kill-server`)?

**Comment by Raizo62** [comment]
> Are you sure linux is the correct TERM for this terminal emulator?

I have tried "xterm-256color" to solve this problem, but in tmux, in nano, i couldn't can use the digits of my numpad

> Can you reproduce on a real Linux console with the same TERM?

I really need to use it in this VM.
I have tried to remove all my configs of zsh/bash/tmux. no change.

> Does it fix it if you add set -as terminal-overrides '*:am@' to .tmux.conf and restart tmux (tmux kill-server)?

no change :-(

**Comment by nicm** [comment]
If `xterm-256colour` fixes it, then it sounds like `linux` is not the correct `TERM`. `linux` is typically only used for the Linux console and if you are connecting with serial then it is not a Linux console emulator. Do you know what actual terminal emulator GSN3 is based on?

**Comment by ThomasDickey** [comment]
That might be [solar-putty](https://docs.gns3.com/docs/using-gns3/beginners/the-console-terminal/) (whose differences from putty are of course undocumented).  I'd start with `TERM=putty`, and redirect ***all*** complaints after that to GNS3's developers.

**Comment by Raizo62** [comment]
> I have tried "xterm-256color" to solve this problem, but in tmux, in nano, i couldn't can use the digits of my numpad

No, "xterm-256color" does not fix it. But, i used "nano" to modify the value before to understood that "nano" fixed the problem, and not "xterm-256color"

> That might be solar-putty (whose differences from putty are of course undocumented). I'd start with TERM=putty, and redirect all complaints after that to GNS3's developers.

Putty is more on Windows
And that's work without tmux, or after to launch "nano"

**Comment by nicm** [comment]
Shoe tmux server log please from reproducing.

**Comment by Raizo62** [comment]
> Show tmux server log please from reproducing.

how do i do to get the log ? (sorry)

**Comment by nicm** [comment]
Look here https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md#how-do-i-get-logs-from-tmux.

**Comment by Raizo62** [comment]
1. 
```
tmux -Ltest kill-server ; tmux -vv -Ltest -f/dev/null new
```
give me theses log (then without nano)
[tmux-client-391.log](https://github.com/tmux/tmux/files/5531753/tmux-client-391.log)
[tmux-out-393.log](https://github.com/tmux/tmux/files/5531754/tmux-out-393.log)
[tmux-server-393.log](https://github.com/tmux/tmux/files/5531755/tmux-server-393.log)

2. 

```
reboot
nano
tmux -Ltest kill-server ; tmux -vv -Ltest -f/dev/null new
```
give me theses log (then with nano)
[tmux-client-393.log](https://github.com/tmux/tmux/files/5531761/tmux-client-393.log)
[tmux-out-395.log](https://github.com/tmux/tmux/files/5531762/tmux-out-395.log)
[tmux-server-395.log](https://github.com/tmux/tmux/files/5531763/tmux-server-395.log)

**Comment by Raizo62** [comment]
Perhaps that nano turns off the automatic margins : We see that without nano, the lines finish with "q0", but with nano, the lines finish with "ql" (for "qlen 1000").

But why is the display not good with the "q0" in tmux ?

**Comment by nicm** [comment]
But your first screenshot shows q0 outside tmux also? Are you saying the first screenshot (outside tmux) is also wrong?

**Comment by nicm** [comment]
If you put this in .tmux.conf and then restart tmux (`tmux kill-server`), does the problem go away?
~~~~
set -as terminal-overrides '*:xenl@'
~~~~

**Comment by Raizo62** [comment]
> But your first screenshot shows q0 outside tmux also? Are you saying the first screenshot (outside tmux) is also wrong?

I want to say that the display of command "ip a" is not ugly in "tmux after nano" because, perhaps, nano turns off the automatic margins.
I suppose that the first screenshot (q0) is the correct/default display, even if i prefer the display "ql" (qlen 1000) because i see all the informations.

> `set -as terminal-overrides '*:xenl@'`

I have the display "qlen"...I suppose that is better than ugly display.
But, if i play with tab and nano in tmux, i have always the green tab which goes up
![green_up](https://user-images.githubusercontent.com/7449584/98979226-6728bd80-251b-11eb-8716-7f3370f63e40.PNG)


With this config of tmux : 
```
bind-key -n C-right next
bind-key -n C-left prev
bind-key -n S-Left swap-window -d -t -1
bind-key -n S-Right swap-window -d -t +1
bind-key -n C-S-left select-pane -L
bind-key -n C-S-right select-pane -R
bind-key -n C-S-up select-pane -U
bind-key -n C-S-down select-pane -D
set -as terminal-overrides '*:xenl@'
```

and the command (after a reboot)
`tmux -vv new`

i have these logs files
[tmux-out-388.log](https://github.com/tmux/tmux/files/5532441/tmux-out-388.log)
[tmux-server-388.log](https://github.com/tmux/tmux/files/5532443/tmux-server-388.log)
[tmux-client-386.log](https://github.com/tmux/tmux/files/5532444/tmux-client-386.log)

**Comment by nicm** [comment]
Can you build tmux from master please and see if the problem still exists, you will need this with master (not `xenl`):
~~~~
set -as terminal-overrides '*:am@'
~~~~
If the problem still exists with master please show me the logs from running `ip` same as before.

**Comment by Raizo62** [comment]
Ok, i will do that. Thanks

**Comment by Raizo62** [comment]
cat /etc.tmux.conf :
```
bind-key -n C-right next
bind-key -n C-left prev
bind-key -n S-Left swap-window -d -t -1
bind-key -n S-Right swap-window -d -t +1
bind-key -n C-S-left select-pane -L
bind-key -n C-S-right select-pane -R
bind-key -n C-S-up select-pane -U
bind-key -n C-S-down select-pane -D
set -as terminal-overrides '*:am@'
```

master version of tmux (commit e94bd5ccff42361788e71acb2315b9b10112cae1)

```
reboot
tmux -vv new
```

In /etc/zshrc :  "export TERM='linux'"

I play with tab and nano in tmux, i have always the green tab which goes up

[tmux-out-386.log](https://github.com/tmux/tmux/files/5540596/tmux-out-386.log)
[tmux-server-386.log](https://github.com/tmux/tmux/files/5540597/tmux-server-386.log)
[tmux-client-384.log](https://github.com/tmux/tmux/files/5540598/tmux-client-384.log)

**Comment by nicm** [comment]
OK so the line wrap problem is gone? If you use `export TERM=putty` outside tmux does the scrolling problem go away as well?

**Comment by nicm** [comment]
Or `export TERM=xterm`?

**Comment by nicm** [comment]
Also can you see if removing `csr` as well as `am` makes any difference:
~~~~
set -as terminal-overrides '*:am@:csr@'

**Comment by Raizo62** [comment]
> OK so the line wrap problem is gone?

My VM doesn't like `export TERM=putty` : it doesn't know "putty"

with `export TERM=xterm`, the green bar problem  stays here.

> OK so the line wrap problem is gone?

I don't know : it display  "qlen 1000" which seems not to be the default display. But it is more nice that with big holes....

**Comment by Raizo62** [comment]
I will test : set -as terminal-overrides '*:am@:csr@'

**Comment by nicm** [comment]
tmux should wrap lines and show `qlen 1000` regardless of what the terminal outside does, so it seems like removing `am` does fix that.

**Comment by Raizo62** [comment]
with `export TERM=xterm` and  `set -as terminal-overrides '*:am@:csr@'`  : 

- "ip a" displays "q". It doesn't display the 0 after q
- the green bar goes up

**Comment by nicm** [comment]
OK. What do you see if you do this outside tmux:
~~~~
printf '\033[c\033[>c';cat
~~~~

**Comment by Raizo62** [comment]
![image](https://user-images.githubusercontent.com/7449584/99146672-94d84880-267a-11eb-8181-de7db57dfee9.png)

**Comment by nicm** [comment]
OK this is probably xterm. If you open another terminal and look for the PID of the problem xterm with ps or pgrep or top and then do `cat /proc/PID/cmdline` what do you see?

If you open a normal xterm and eg ssh into the VM then tmux is OK?

**Comment by Raizo62** [comment]
![image](https://user-images.githubusercontent.com/7449584/99146900-a91d4500-267c-11eb-843a-0e0b551e7c68.png)

![image](https://user-images.githubusercontent.com/7449584/99146916-c2be8c80-267c-11eb-8501-4611fc78f527.png)

You are right : if i open an xterm on LiveRaizo, and i connect to the VM with ssh, i have no green bar problem, (and i have "qlen 1000", but it is not a problem)

**Comment by nicm** [comment]
So it seems like either GNS3 is running xterm with some strange arguments or has a modified xterm. If we can figure out what arguments it is using then we can work out what `TERM` to use or how to customize it. You could look at /proc/PID/cmdline you might see what arguments it is using.

**Comment by Raizo62** [comment]
The "xterm" is the xterm of Debian. I doesn't believe that "my" GNS3 starts an other xterm (i build GNS3 from github source)

> You could look at /proc/PID/cmdline you might see what arguments it is using.

Sorry, i doesn't understand what i must do different from the lasts screenshots ?

**Comment by nicm** [comment]
It must be starting it with different arguments because if it was just starting it normally then it would work the same.

If you run GNS3 then open another xterm on the same box and run (without ssh):
~~~~
ps -aelf|grep xterm
~~~~

**Comment by nicm** [comment]
The other thing is you can look at the GNS3 source and see how it starts xterm. Try to grep in the source and see how it runs xterm.

**Comment by Raizo62** [comment]
Perhaps that the problem is that xterm does a telnet on a python program of GNS3.
I will see with the teams of GNS3 and i will be back...
Thanks for your times.

**Comment by ThomasDickey** [comment]
If I were investigating a problem like this, I'd set up a simple test, capturing _typescript_ files by running `script` on each of the local and remote connections, and use [unmap](https://invisible-island.net/misc_tools/index.html#item:unmap) to render the resulting _typescript_ files in readable form.

The problem could be any of
- differences in xterm versions (bug fixes or regressions)
- terminfo entry differences (used by tmux)
- tmux differences
- none of the above (e.g., shell differences)

**Comment by Raizo62** [comment]
It seems that the issue comes from the option "-nographic" of qemu.

Sorry to have lost your times and thanks you for your help
