### ISSUE TITLE
[Feature Request] Official AppImage build

### ISSUE THREAD

**Issue by michaellee8** [tmux/tmux#2460]
I can see from https://github.com/tmux/tmux/issues/1172 that @nelsonenzo already provides an AppImage build in https://github.com/nelsonenzo/tmux-appimage, and there is an official version of AppImage build in 3.0. However, there are no offical ones from other versions.

By any chance an "official" AppImage build can be provided for newer versions? It would be great if people who need to work in environment with no package manager granted/available to get the latest tmux working without compiling from source (sometimes not even possible if you don't have apt-get). I know there is a third-party one from @nelsonenzo but a official hence verified build would be more trusted.

I guess I can help to do this if this suggestion can be accepted. Perhaps a build job in Travis CI would be enough.

**Comment by nicm** [comment]
Your best bet is to talk to @nelsonenzo, if you automatically build them and then open an issue or email me then I will add them to the release.

**Comment by michaellee8** [comment]
@nicm Please look at my PR

**Comment by nicm** [comment]
Moved to PR.
