### ISSUE TITLE
Scrolling characters pasted to terminal after closing remote tmux session 

### ISSUE THREAD

**Issue by cebor** [tmux/tmux#2462]
### Issue description

When i connect to a remote via ssh where a tmux session is running and the connections gets closed by the remote (reboot / timeout) wired characters are pasted to the terminal.

Scrolling and clicking is not possible anymore, until restarting the terminal emulator.

.tmux.conf
```
set-option -g mouse on
```

Video:
[![asciicast](https://asciinema.org/a/Fp5A1GDvhpPr2zYQphY1CWOFn.svg)](https://asciinema.org/a/Fp5A1GDvhpPr2zYQphY1CWOFn)

When i end the connection with `exit` this does not happen.

### Required information

* tmux version (`tmux 3.0a`).
* Platform Remote (`Linux x86_64`).
* Platform Local (`Darwin i386`).
* $TERM inside and outside of tmux Remote(in: `screen-256color` out: `xterm-256color`).
* $TERM Local no tmux (`xterm-256color`).
* Logs from tmux (`no sessions [server exited]`).

**Comment by nicm** [comment]
There is no way to avoid this and also have tmux respond to the mouse, either make sure to exit tmux cleanly so it can turn the mouse off or do `set -g mouse off`.

**Comment by nicm** [comment]
You can usually run `reset` to clear the mouse flags and restore the terminal to normal.

**Comment by iam-TJ** [comment]
I've recently encountered this issue with tmux 3.0a on Xubuntu 20.04 amd64. The problem is that the unexpected control characters in the invoking `bash` shell after cleanly exiting tmux are there even though I do `<prefix>-:` + `set -g mouse off` before `exit` from the single tmux window used to test this.
