### ISSUE TITLE
crashes on openbsd

### ISSUE THREAD

**Issue by wujiang** [tmux/tmux#2464]
### Issue description
* tmux version (`tmux -V`): 
  `tmux openbsd-6.8`
* Platform (`uname -sp`): 
  `OpenBSD amd64`
* $TERM inside and outside of tmux (`echo $TERM`): 
  `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`)
[tmux-client-99375.log](https://github.com/tmux/tmux/files/5533768/tmux-client-99375.log)
[tmux-server.log](https://github.com/tmux/tmux/files/5533837/tmux-server.log)

Tmux crashes but not sure what exactly caused the crash. Looks like it has something to do with `FocusOut` here https://github.com/tmux/tmux/blob/ca5afb34bfdcaddbaed12e7375b48c05019e4c18/input-keys.c#L559

**Comment by 4xposed** [comment]
I'm getting the same on MacOS 10.15.7.

```
$ tmux -V
tmux next-3.3
$ uname -sp

**Comment by wujiang** [comment]
@4xposed A temporary workaround I'm using is disabling `focus-events` (`set -g focus-events off`).

**Comment by nicm** [comment]
How do you reproduce this?

**Comment by wujiang** [comment]
1. start `tmux`
2. use emacsclient to open a file
3. switch to another application

**Comment by nicm** [comment]
Show me the full server log please.

**Comment by wujiang** [comment]
Sure thing.
[tmux-server-46278.log](https://github.com/tmux/tmux/files/5548073/tmux-server-46278.log)

**Comment by nicm** [comment]
I can't reproduce this, does it still happen if you build tmux from -current?

**Comment by wujiang** [comment]
hmm, I'm running a openbsd VM inside of a macbook and sshing into it. I built tmux from https://github.com/openbsd/src/tree/master/usr.bin/tmux and it has the same problem.

**Comment by nicm** [comment]
I have reproduced now, it only happens when the application has also enabled extended keys. This should be fixed by input-keys.c r1.81. Thanks!

**Comment by wujiang** [comment]
Thank you @nicm! Closing.
