### ISSUE TITLE
Disable 'w' window selection screen from zooming

### ISSUE THREAD

**Issue by davehouser1** [tmux/tmux#2467]
How do I stop the windows selection screen from zooming in 3.1b and work the way it did in 2.6?

**Version 2.6:**
- when {bind} w, which ever pane this was selected, the windows selection screen would appear, but only render in that pane no matter what the size.

**Version 3.1b**
- when {bind} w, pane will zoom into window selection screen in selected pane.

Work around (I would rather have tmux operate the way it did in 2.6):
- {bind} z, zoom into pane
- {bind} w, windows selection screen
- {bind} z, unzoom the pane

**Comment by nicm** [comment]
Bind the keys without the -Z flag.

**Comment by davehouser1** [comment]
@nicm I do not understand.
First of all is the behavior I am seeing in 3.1b expected?
Second I do not use {bind} Z for anything, Z does not appear to be for anything. Did you mean lowercase z? If so , {bind} z is the default for zoom. Are you suggesting I change the default {bind} z to something else?
Are you also saying there is no way to change the behavior for 3.1b for the window select screen to act the way it did in 2.6?

**Comment by nicm** [comment]
Change the w key binding to remove -Z.

**Comment by davehouser1** [comment]
@nicm
I like using "w" as the key binding. 
There is no way to disable this functionality without changing the key binding?
Also I tried changing the key binding to test but tmux does not appear to recognize the change. What is the exact syntax to change? Tried `bind -n C-p select-window`. Then tried to `tmux source ~/.tmux.conf`, also tried closing out tmux. Tmux does not recognize my change.

**Comment by nicm** [comment]
Why would you change the C-p key binding? You are pressing w, change that key binding. Look at `tmux lsk w` and remove the -Z.

**Comment by nicm** [comment]
~~~~
bind w choose-tree -w

**Comment by davehouser1** [comment]
Thanks, did not know :lsk existed.  
I added `bind-key -T prefix w choose-tree -w` in my ~/.tmux.conf and it worked.
Sorry for the confusion.
