### ISSUE TITLE
frozen tmux 3.1c on macOS Big Sur (11.0.1)

### ISSUE THREAD

**Issue by ebenezar-mccoy** [tmux/tmux#2468]
Running tmux 3.1c on macOS Big Sur (11.0.1) 
I seem to experience similar symptoms reported in #1352 and #2324

Symptoms:

    I have upgraded system to Big Sur.
    Reinstalled tmux.
    Trying to launch new tmux gets stdin locked up. Pressing Ctrl+C doesn't stop it so I must kill the terminal tab/process.
    CPU usage is 98-100%

[tmux-client-14468.log](https://github.com/tmux/tmux/files/5550462/tmux-client-14468.log)

**Comment by ebenezar-mccoy** [comment]
this line from .zshrc is causing issues:
`
unlimit
`

**Comment by nicm** [comment]
Does it still hang if you do this:
~~~~
pkill tmux
tmux -vvLtest -f/dev/null new
~~~~
If so please attach both client and server logs.

**Comment by ebenezar-mccoy** [comment]
yes it does

my .zshrc

`
unlimit # tmux bad boy
limit stack 8192
limit core 0
limit -s
`
[tmux-client-23544.log](https://github.com/tmux/tmux/files/5553565/tmux-client-23544.log)
[tmux-server-23546.log](https://github.com/tmux/tmux/files/5553566/tmux-server-23546.log)

**Comment by nicm** [comment]
Show me `ulimit -a` and `ulimit -aH` before starting tmux.

**Comment by nicm** [comment]
Oh this is probably because of a ridiculous file descriptor limit.

**Comment by nicm** [comment]
Hmm no we don't use that.

**Comment by ebenezar-mccoy** [comment]
ulimit -a:
```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       8352
-n: file descriptors                unlimited
```

ulimit -aH
```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             65532
-c: core file size (blocks)         unlimited
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       8352
-n: file descriptors                unlimited
```

**Comment by nicm** [comment]
Apple have changed this so it returns a stupid number of file descriptors now. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/5554842/x.diff.txt)

**Comment by ebenezar-mccoy** [comment]
patch seems do the work, thanks !

any chance to have it added to master branch ?

**Comment by nicm** [comment]
Applied now, thanks!

**Comment by gaving** [comment]
Got burned by this the other day and gave up investigating, thanks for sorting this!
