### ISSUE TITLE
server exited unexpectedly when running tmux command

### ISSUE THREAD

**Issue by rvnsource** [tmux/tmux#2469]
### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

Output:-ravi@sjc-ads-228:/router/bin#tmux
server exited unexpectedly
ravi@sjc-ads-228:/router/bin#tmux -V
tmux.bin 3.1b
ravi@sjc-ads-228:/router/bin#uname -sp
Linux x86_64
ravi@sjc-ads-228:/router/bin#echo $TERM
xterm-256color
ravi@sjc-ads-228:/router/bin#tmux kill-server; tmux -vv new
server exited unexpectedly
server exited unexpectedly
ravi@sjc-ads-228:/router/bin#

After I issued 'tmux kill-session' (when there was'nt' any session) this issues started appearing.
Any idea how to fix this.

**Comment by nicm** [comment]
Logs?

**Comment by nicm** [comment]
Do `pkill tmux` then `tmux -vv -f/dev/null new`.

**Comment by rvnsource** [comment]
ravindsh@sjc-ads-228:/bin#pkill tmux
ravindsh@sjc-ads-228:/bin#tmux -vv -f/dev/null new
server exited unexpectedly
ravindsh@sjc-ads-228:/bin#tmux -vv -f/dev/null new .
server exited unexpectedly
ravindsh@sjc-ads-228:/bin#tmux -vv -f/dev/null new.
server exited unexpectedly

**Comment by nicm** [comment]
Right so where is the log file?

**Comment by rvnsource** [comment]
sure, but can I know in which path I will get log file for tmux?

**Comment by nicm** [comment]
In the current directory where you ran tmux.

**Comment by rvnsource** [comment]
no logs except "server exited unexpectedly" on running tmux command

**Comment by nicm** [comment]
Do this please:
~~~~
pkill tmux
strace -tt -fostrace.out tmux new
~~~~
Then show me any strace.out* files.

**Comment by VincentJing** [comment]
I have the same problem, the log as follows:
<img width="999" alt="CleanShot 2020-11-19 at 10 06 05@2x" src="https://user-images.githubusercontent.com/20381269/99611583-eef85580-2a4e-11eb-8d8e-403c92384733.png">

**Comment by krader1961** [comment]
@VincentJing, What does `ls -ld /tmp/tmux-1000` output? What about `ls -l /tmp/tmux-1000/default`? What is your current user ID; i.e., what does `id` report?

**Comment by VincentJing** [comment]
@krader1961 
![CleanShot 2020-11-19 at 11 23 45@2x](https://user-images.githubusercontent.com/20381269/99617224-d9d4f400-2a59-11eb-8518-267fa9f9488c.png)

**Comment by krader1961** [comment]
I have no idea what to make of that screen grab other than that the directory containing the UNIX socket is owned by user `jzf` and you cannot access its contents because you are apparently not user `jzf`. You don't show us what your current user ID is. Please, don't post screen grabs except when absolutely essential to understanding the problem.

**Comment by krader1961** [comment]
@VincentJing: Capturing the syscalls that tmux makes, per @nicm's previous [comment](https://github.com/tmux/tmux/issues/2469#issuecomment-729568510), should tell us what is going wrong on your system.

**Comment by thornycrackers** [comment]
I was getting all the same error messages and symptoms. Removing `/tmp/tmux-1000/default` fixed it for me.
