### ISSUE TITLE
[Feature Request] resize-window option in conf file

### ISSUE THREAD

**Issue by casonadams** [tmux/tmux#2470]
While remote pairing tmux sessions with different sizes cause a (bounce) effect when each session user interacts with the terminal.  A solution I have come up with as a band-aid is to add the following to my `tmux.conf` file

```conf
set-option -g status-left '#(tmux resize-window -a)'
```

This forces the tmux window size to always be the smallest connected width and height.  I would be nice to not have to embedded this in to a status option but rather just configure it to be one of the many options for `tmux resize-window`

Maybe there is a way to do this and I don't know about it.  Would love some insight / potential feature.

**Comment by nicm** [comment]
Why don't you set `window-size` to `smallest` or `manual`?

**Comment by casonadams** [comment]
I don't follow.  How would I go about doing this?  I kind of want it to not be manual.

**Comment by nicm** [comment]
Set the `window-size` option...

**Comment by casonadams** [comment]
```

**Comment by nicm** [comment]
You only need to restart if you changed .tmux.conf, if you do it from the command prompt it should take effect immediately.
