### ISSUE TITLE
Perfect forwarding of arguments not possible with popups

### ISSUE THREAD

**Issue by alexherbo2** [tmux/tmux#2475]
Perfect forwarding of arguments is possible with [`split-window`] but not [`display-popup`], as `-R` reads the shell command as a single argument.

Possible with [`split-window`]:

```
tmux split-window -- sh -c 'some-command "$@"' -- "$@"
```

Not possible with [`display-popup`]:

```
tmux display-popup -d "$PWD" -K -E -R -- sh -c 'some-command "$@"' -- "$@"
```

Use case is with Kakoune: https://github.com/mawww/kakoune/issues/3878

[`split-window`]: http://man.openbsd.org/OpenBSD-current/man1/tmux.1#split-window
[`display-popup`]: http://man.openbsd.org/OpenBSD-current/man1/tmux.1#display-popup

**Comment by nicm** [comment]
Please try this which adds a `-r` flag (as an alternative to `-R`) with this behaviour: [tmux-popup-r.diff.txt](https://github.com/tmux/tmux/files/5622258/tmux-popup-r.diff.txt)

**Comment by nicm** [comment]
I wonder if we should get rid of the ability to give custom lines and pass a key to a command and just make this the default behaviour. The idea was that people could do it completely with tmux, so stuff like:
~~~~
popup 'if -F "#{!=:#{popup_key},n}" "lsk"' "#[bg=red]Are you sure?"
~~~~
But I can't think of many uses for this that aren't covered by either `confirm-before`/`command-prompt` or just writing a shell script to run in the popup.

**Comment by nicm** [comment]
I have changed this now.

**Comment by alexherbo2** [comment]
Hello @nicm,

Perfect forwarding is still not possible.

You can try the following command:

``` sh
tmux display-popup -d "$PWD" -K -E -R -- sh -c 'vi "$@"' -- file.txt
```

**Comment by nicm** [comment]
`-K` and `-R` have been removed so this command doesn't work anymore. Without them, it seems fine to me.

But I can't guess what problem you are seeing. What are you expecting to happen compared with what is actually happening?
