### ISSUE TITLE
tmux buffer breaks when the output is larger than the terminal length/buffer

### ISSUE THREAD

**Issue by Arszilla** [tmux/tmux#2477]
### Issue description
sometimes when using `tmux` with `urxvt` & `oh-my-zsh` in Kali Linux, if the output buffer is longer than the terminal length/buffer, the buffer breaks, causing a massive space between the buffer. An example of a broken buffer:

![tmux-1](https://user-images.githubusercontent.com/22989170/100060842-33fcfd00-2e3e-11eb-94a1-ce184844cc69.png)

The correct buffer:

![tmux-2](https://user-images.githubusercontent.com/22989170/100060854-395a4780-2e3e-11eb-93d2-67f1867ceac6.png)

I've taken the 2nd screenshot in `urxvt` without tmux running. When `tmux` isn't running, everything works fine. At first, I thought it was `oh-my-zsh`'s default plugins breaking my `tmux`, but that wasn't the case as I couldn't find any basis for my claims. For context, this is my `.zshrc`:

```
export ZSH="/home/arszilla/.oh-my-zsh"

ZSH_THEME="clean"

# Plugins 
plugins=(git zsh-autosuggestions zsh-completions)
autoload -U compinit && compinit

setopt +o nomatch

alias openvpn="sudo openvpn"
alias nmap="sudo nmap"
alias pbcopy="xsel --clipboard --input"
alias pbpaste="xsel --clipboard --output"
alias wireguard="sudo wireguard"
alias wg-quick="sudo wg-quick"

source $ZSH/oh-my-zsh.sh
```

As you can see, there's no import of the plugins used my `oh-my-zsh`:

```
/home/arszilla/.oh-my-zsh/custom/plugins/zsh-completions/src/_tmuxinator
/home/arszilla/.oh-my-zsh/custom/plugins/zsh-completions/src/_tmuxp
/home/arszilla/.oh-my-zsh/plugins/tmux
/home/arszilla/.oh-my-zsh/plugins/tmux-cssh
/home/arszilla/.oh-my-zsh/plugins/tmuxinator
/home/arszilla/.oh-my-zsh/plugins/tmux/README.md
/home/arszilla/.oh-my-zsh/plugins/tmux/tmux.extra.conf
/home/arszilla/.oh-my-zsh/plugins/tmux/tmux.only.conf
/home/arszilla/.oh-my-zsh/plugins/tmux/tmux.plugin.zsh
/home/arszilla/.oh-my-zsh/plugins/tmux-cssh/README.md
/home/arszilla/.oh-my-zsh/plugins/tmux-cssh/_tmux-cssh
/home/arszilla/.oh-my-zsh/plugins/tmuxinator/README.md
/home/arszilla/.oh-my-zsh/plugins/tmuxinator/_tmuxinator
/home/arszilla/.oh-my-zsh/plugins/tmuxinator/tmuxinator.plugin.zsh
/home/arszilla/.oh-my-zsh/plugins/zsh-navigation-tools/znt-tmux.zsh
```

### Required information
* `tmux` version: tmux 3.1c
* Platform: Linux kali 5.9.0-kali2-amd64 x86_64
* `$TERM` outside of `tmux`: `rxvt-unicode-256color`
* `$TERM` inside of `tmux`: `screen`
* Logs from `tmux`:

[tmux-server-23544.log](https://github.com/tmux/tmux/files/5588078/tmux-server-23544.log)
[tmux-client-23542.log](https://github.com/tmux/tmux/files/5588079/tmux-client-23542.log)
[tmux-out-23544.log](https://github.com/tmux/tmux/files/5588081/tmux-out-23544.log)

**Comment by nicm** [comment]
If you press `C-b r` in tmux, does the missing text appear?

**Comment by Arszilla** [comment]
> If you press `C-b r` in tmux, does the missing text appear?

Sadly no. The broken buffer remains the same.

**Comment by nicm** [comment]
I do not see the text in your screenshots in the log, are you sure the log matches what you did in the screenshot?

**Comment by Arszilla** [comment]
Oh. I just created a new log for the sake of it. Apologies about that. I've created a new set of log files with the command being ran:

[tmux-client-31095.log](https://github.com/tmux/tmux/files/5591999/tmux-client-31095.log)
[tmux-out-31097.log](https://github.com/tmux/tmux/files/5591997/tmux-out-31097.log)
[tmux-server-31097.log](https://github.com/tmux/tmux/files/5591998/tmux-server-31097.log)

**Comment by nicm** [comment]
Your screenshot is not showing the tmux status line, are you scrolling up into the terminal scrollback? This will not be complete when tmux is running, you have to use copy mode instead.

**Comment by Arszilla** [comment]
I had the images above cropped, but yes, initially I scroleld up. Usually `tmux` outputs the buffer without a hitch but this started to happen a lot lately hence this. So judging by your response, I was using `tmux` wrong, and opted to scroll up instead of doing `CTRL+ B + [`. I'll experiment around  bit to see if this fixes my issue or not, because if I recall right, even in copy mode, I had a few broken buffers. I might be misrecalling, hence the need for experimentation.

Regardless, thanks for the assist @nicm. I'll let you know if this fixes it.

**Comment by nicm** [comment]
OK let me know, thanks.
