### ISSUE TITLE
Line-wrapped commands insert new lines when yanked.

### ISSUE THREAD

**Issue by tuv7041** [tmux/tmux#2478]
Hi! I'm experiencing the issue described in https://github.com/tmux-plugins/tmux-yank/issues/13. I saw that there's this issue reported https://github.com/tmux/tmux/issues/530 but it seems it got closed due to inactivity.

The patch that you uploaded in that issue got formatted wrongly and I seem to be unable to try it out. Could you please re-upload it and maybe I can test it? I understand that the issue has been fixed in tmux-yank but I try to avoid tmux plugins whenever possible, and copy/pasting is working perfectly except for this issue. It also comes up when reverse searching with ctrl-r as well (and I that quite frequently). 

I'm using tmux next-3.3 on debian testing. 
My $TERM is rxvt-unicode-256color.

I'll put the steps to reproduce the issue that @willvousden reported just in case:

1. Type a long command into a shell prompt (also IPython, etc.) in a tmux session so that it wraps around to a new line.
2. Move the cursor back across the line-wrap.
3. Move the cursor forward across the line-wrap.
4. Enter tmux copy mode and yank the complete command that you typed (or any part of it that crosses the line-wrap).
5. Execute the command, or do whatever to clear the shell prompt.
6. Paste the tmux buffer.

Thanks!

**Comment by nicm** [comment]
This was the change but I don't remember the details so no idea if it will work:
~~~~
--- screen-write.c      9 Nov 2020 08:42:43 -0000       1.188
+++ screen-write.c      1 Dec 2020 11:37:50 -0000
@@ -1240,8 +1240,6 @@ screen_write_linefeed(struct screen_writ
        gl = grid_get_line(gd, gd->hsize + s->cy);
        if (wrapped)
                gl->flags |= GRID_LINE_WRAPPED;
-       else
-               gl->flags &= ~GRID_LINE_WRAPPED;

        log_debug("%s: at %u,%u (region %u-%u)", __func__, s->cx, s->cy,
            s->rupper, s->rlower);

**Comment by nicm** [comment]
I have applied this now, let me know if you see any problems. Thanks!
