### ISSUE TITLE
does not swap window as expected in tmux 3.0a in ubuntu 20.04

### ISSUE THREAD

**Issue by akashrpo** [tmux/tmux#2479]
Hi,
I used to earlier swap the tmux window and place it in the proper position as needed. However, in ubuntu 20.04 tmux version 3.0a when I use the command "swap-window -t +1" it swaps the window but my position stays in the fix position i.e my view does not swap along with my window i.e if I swap window 2 and 3 currently being on 2nd window then after the swap of window 2 and 3 I stay at window 2 only and does not move to window 3 along with my window. This is not the case in my other Debian Buster with tmux version 2.8.

In ubuntu 20.04
* tmux version (`tmux -V`) - `tmux 3.0a`
* Platform (`uname -sp`) - `Linux x86_64`
* $TERM inside  - `screen` and outside of tmux - `xterm-256color`
![image](https://user-images.githubusercontent.com/64877812/100082622-7807f600-2e6e-11eb-9f24-f621c1f25470.png)
After swapping
![image](https://user-images.githubusercontent.com/64877812/100082724-9a9a0f00-2e6e-11eb-8e11-88b14a72829f.png)

In Debian Buster
* tmux version (`tmux -V`) - `tmux 2.8`
* Platform (`uname -sp`) - `Linux x86_64 GNU/Linux`
* $TERM inside  - `screen` and outside of tmux - `xterm-256color`
![image](https://user-images.githubusercontent.com/64877812/100082824-bdc4be80-2e6e-11eb-8c67-682199ae825b.png)
After swapping (Expected Result)
![image](https://user-images.githubusercontent.com/64877812/100082899-ccab7100-2e6e-11eb-8d81-504e7912d21c.png)

**Comment by nicm** [comment]
Add or remove `-d`, this was fixed to match all the other commands.

**Comment by akashrpo** [comment]
adding -d in the command as "swap-window -t +1 -d" resolves the issue in ubuntu 20.04 but then the Debian Buster has the issue with this and now behaves just like Ubuntu 20.04. The issue has been reversed in between the OS. Isn't there a generic fix for this?

**Comment by nicm** [comment]
No, it was incorrect in the old versions.

**Comment by akashrpo** [comment]
Thanks! Hope the above command works when the tmux 3.0a version comes in the Debian Buster repo.

**Comment by nicm** [comment]
It was fixed in 39c55d5b6fcafd9476528ebc1064192c90f559a4 for 3.1.
