### ISSUE TITLE
Compile error! it seems that libncurse had renamed an interface, from del_curterm to del_curterm_sp

### ISSUE THREAD

**Issue by stark-zhang** [tmux/tmux#2481]
I tried to compile tmux 3.2-rc with libncurse 6.2(the latest version). And I got an error:
> /opt/binutils/x86_64/2.32/bin/ld: tty-term.o: undefined reference to symbol 'del_curterm'
/opt/binutils/x86_64/2.32/bin/ld: /host/workdir/local/lib//libtinfo.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

I found an interface named `del_curterm_sp`, not `del_curterm` in libncurse.so, I think this interface was renamed.

And I will rollback my libncurse and retry to compile.

**Comment by nicm** [comment]
No it was not removed. Show me config.log?

**Comment by stark-zhang** [comment]
well, I had rollbacked to  tmux 3.1c and libncurse 5.9 to finish compiling so I have no config.log about this issue. I think that's my problem in my own problem as you said.
