### ISSUE TITLE
`tmux popup -yC` creates popup at the top, rather than the centre, of the window

### ISSUE THREAD

**Issue by carlocab** [tmux/tmux#2482]
### Issue description

`tmux popup` and `tmux popup -yC` open a popup at (or close to) the top of the window. Screenshot attached at the end for reference.

This is no longer a problem when I pass the `-h` flag with a small enough value for the height (somewhere less than 50%, whether given as a percentage or not). The popup opens roughly around the centre of the window in this case.

### Required information

Please provide the following information:

* `tmux next-3.3`
* `Darwin i386` macOS 11.0.1
* `tmux-256color` and `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`):

[tmux-client-32370.log](https://github.com/tmux/tmux/files/5603043/tmux-client-32370.log)
[tmux-out-32372.log](https://github.com/tmux/tmux/files/5603044/tmux-out-32372.log)
[tmux-server-32372.log](https://github.com/tmux/tmux/files/5603045/tmux-server-32372.log)

Using `tmux -Ltest -f/dev/null`:
<img width="682" alt="Screenshot 2020-11-26 at 12 31 15" src="https://user-images.githubusercontent.com/30379873/100351437-5a0fd200-2fe3-11eb-9582-521f2a420d01.png">

**Comment by nicm** [comment]
I think this is the fix:
~~~~
--- cmd-display-menu.c  3 Nov 2020 08:09:35 -0000       1.21
+++ cmd-display-menu.c  26 Nov 2020 13:05:49 -0000
@@ -155,7 +155,7 @@ cmd_display_menu_get_position(struct cli
        else
                format_add(ft, "popup_centre_x", "%ld", n);
        n = (tty->sy - 1) / 2 + h / 2;
-       if (n + h >= tty->sy)
+       if (n >= tty->sy)
                format_add(ft, "popup_centre_y", "%u", tty->sy - h);
        else
                format_add(ft, "popup_centre_y", "%ld", n);

**Comment by carlocab** [comment]
Oh, I see you've already applied this patch to master. No wonder trying to apply the patch didn't work.

Anyway, I can see that it's fixed now. Thanks for getting to it so quickly.
