### ISSUE TITLE
Is it possible not to disconnect the popup window from window resizing?

### ISSUE THREAD

**Issue by casprwang** [tmux/tmux#2484]
### Issue description

Really enjoying using popup so far, great feature. One thing I notice is resizing the term would trigger a disconnect(SIGHUP?). I wonder if there's a way not to send the disconnect call and repaint in scale. In many cases we might want to keep it open.

**Comment by nicm** [comment]
Popups can't be offscreen so they would need to be moved/resized. Not hugely difficult but not trivial either. I've added this to the todo list.

**Comment by nicm** [comment]
This has been done now.
