### ISSUE TITLE
after 61e55fa, when 'monitor-activity' is 'on', the string '#[pop-default]' appears in window names

### ISSUE THREAD

**Issue by mtk** [tmux/tmux#2485]
### Issue description

after 61e55fa5, when 'monitor-activity' is 'on', the string '#[pop-default]' appears in window names in the status bar.  turning off 'monitor-activity' suppresses this failure.  this can be seen with a command like:

tmux -f ../monitor-on.conf -L tester new-session -n session1 \; new-window -n win1 \; new-window -n win2

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

tmux next-3.3

* Platform (`uname -sp`).

Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).

outside: xterm-256color (kde/plasma konsole)
inside: tmux

* Logs from tmux (using the example command above):=

[tmux-client-23320.log](https://github.com/tmux/tmux/files/5609012/tmux-client-23320.log)
[tmux-server-23322.log](https://github.com/tmux/tmux/files/5609013/tmux-server-23322.log)
[tmux-out-23322.log](https://github.com/tmux/tmux/files/5609016/tmux-out-23322.log)

**Comment by nicm** [comment]
There are two problems.

`monitor-activity` uses `#` as a marker. If this is inserted into the format then if it is subsequently followed by a `#[` it will be interpreted as escaping that `#[`. So we need to escape the initial `#` as `##`.

But replacement of `##` when styles are drawn is inconsistent. If it is `##[` then it is replaced by `#[`, but anything else like `##-` is left alone.

Please try this [x.diff.txt](https://github.com/tmux/tmux/files/5615044/x.diff.txt) which makes two changes: 1) add a flag (`e`) to the `q` format modifier to escape `#`s and use it for `window_flags` and 2) consistently replace `##` with `#` when drawing.

**Comment by mtk** [comment]
works perfectly.  thanks!

**Comment by nicm** [comment]
Great - applied to OpenBSD now, will be in GitHub later. Thanks!
