### ISSUE TITLE
Pane titles shown in the choose-tree screen is not updated

### ISSUE THREAD

**Issue by tyrak** [tmux/tmux#2487]
### Issue description

If I go to the `choose-tree` view, it will display (among other things) the title of the active pane for each window. Now if that title gets updated (say by the process running in that pane) then the `choose-tree` view continues to display to initial title.

This might sound like an insignificant issue (and it probably is), but this prevents me for accomplishing a workflow that can be accomplished with GNU Screen: I have a bunch of processes that take a long time to complete (think of something like build scripts), and all of them indicate their progress by updating the xterm window title as they run. With GNU screen, I can run all of them in different windows and then go to the screen's window list view and see the titles of all of those windows. If I stay in that view, the titles shown will get updated automatically so I can see the progress of all of those tasks in real time.

To try this, run the following command in a tmux pane and then switch to the `choose-tree` view:

    for n in {0..3599}; do printf '\e]2;%s\a' "$n"; sleep 1; done

You will notice that the title will not update. OTOH, if you run the above command in a GNU screen window and then go to window list view by pressing `Ctrl-A` followed by `"` (you might need to add `windowlist string "%3n %h%=%f"` in your `screenrc`).

### Required information

Please provide the following information:

* tmux version: 3.1c.
* Platform: Linux x86_64.
* $TERM outside: `xterm-256color` (gnome-terminal 3.36.2, VTE 0.60.3).
* $TERM inside: `screen-256color`.

**Comment by nicm** [comment]
The simplest thing to do here is to update the modes when the status line is redrawn, because that will already be triggered when any useful format variable that could appear is changed. Please try this: [tmux-update-modes.diff.txt](https://github.com/tmux/tmux/files/5622471/tmux-update-modes.diff.txt)

**Comment by tyrak** [comment]
I did try your patch against master (4724702d4eef9e9d7c1bfa39e85b8aeed37a0d12) and it does indeed address the above issue with the pane titles. Thanks!

On a somewhat related issue, it would also be nice if tmux could detect when the contents of one of the panes shown in the preview window in `choose-tree` have changed and update the preview window as well. Here's a simple script that demonstrates this:

    #!/usr/bin/env bash
    
    ./tmux -f /dev/null new-session -ds test
    ./tmux new-window -t test sh -c '
    	while true; do
    		printf "\r%s" "$(date)";
    		sleep 1
    	done
    '
    ./tmux choose-tree -t test
    ./tmux attach -t test

When you run this script, you will see in the preview window of `choose-tree` a timestamp produced by `date`, but the preview window will not get updated as new timestamps are printed by the while loop.

**Comment by nicm** [comment]
I have applied this to OpenBSD now, will be in GitHub later. Thanks!

I don't really like the idea of updating the preview, I think it is better if it is a snapshot, and it would need to be rate limited anyway which would be more complicated than it is worth. You can always update it yourself by pressing `<` or `>`.

**Comment by tyrak** [comment]
> I have applied this to OpenBSD now, will be in GitHub later. Thanks!

Thanks again!

> I don't really like the idea of updating the preview, I think it is better if it is a snapshot, and it would need to be rate limited anyway which would be more complicated than it is worth. You can always update it yourself by pressing `<` or `>`.

Makes sense.
