### ISSUE TITLE
tmux on cygwin crashes

### ISSUE THREAD

**Issue by tkn777** [tmux/tmux#2488]
### Issue description

I am using `tmux 3.1b-1` with cygwin on Windows 10.
* It takes a long time to start (~4-5 seconds) even I have a very fast system (Using WSL2/Debian it starts within a fraction of a second)
* Sometimes (mostly after hours or days) it crashes with "lost connection to server".

What can I do? Any ideas? TIA!

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  `tmux 3.1b`  (cygwin package version: `3.1b-1`)

* Platform (`uname -sp`).
  cygwin / Windows 10 Pro (latest)

* $TERM inside and outside of tmux (`echo $TERM`).
  outside: `xterm-256color`   inside: `screen`

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-705.log](https://github.com/tmux/tmux/files/5618240/tmux-client-705.log)
[tmux-out-707.log](https://github.com/tmux/tmux/files/5618241/tmux-out-707.log)
[tmux-server-707.log](https://github.com/tmux/tmux/files/5618242/tmux-server-707.log)

**Comment by nicm** [comment]
In this server log, tmux has not crashed, it has exited normally. Can you show me a log from it crashing?

When it takes a long time to start, do you mean when you start tmux when it is previously not running, when you attach to an existing session, or when you create a new window or pane?

**Comment by tkn777** [comment]
> In this server log, tmux has not crashed, it has exited normally. Can you show me a log from it crashing?

This a a log of starting.

A log of crash is hard to deliver. Because it usually takes many hours until it crashes.
Is there some option I can start tmux with, just to log the crash?

> When it takes a long time to start, do you mean when you start tmux when it is previously not running, when you attach to an existing session, or when you create a new window or pane?

I mean, when I start tmux when it is previously not running.

**Comment by nicm** [comment]
There is nothing I can do about the crash unless you can provide more information, whether that is a -vv log from tmux when it crashes, or a backtrace from a core file, or a way to reproduce it. Also please check if it still crashes if you build tmux from master.

For it starting slowly, please do this:
~~~~
tmux kill-server
strace -tt -fostrace.out tmux -f/dev/null new
exit
~~~~
Then show me the strace.out file.

**Comment by tkn777** [comment]
Since opening this task I always run tmux in debug mode (and trash my hard disk with the logs).

Interesting is that somehow this has prevented any crashes at all until now. :)

If there is one again, I will contact you with the debug-log attached.
