### ISSUE TITLE
send-keys -F format expansion undefined behavior

### ISSUE THREAD

**Issue by caribpa** [tmux/tmux#2489]
### Issue description

`send-keys -F` key expansion produces undefined behavior when trying to expand a conditional format.

Examples:
```text
# Selects the whole screen
bind-key -T copy-mode-vi 'v' send-keys -F '#{?selection_present,Escape,Space}'
```

```text
# Hangs tmux in an infinite loop
bind-key -T copy-mode-vi 'v' send-keys -F '#{?selection_active,Escape,Space}'
```

In these two examples I was trying to simplify the following:
```text
bind-key -T copy-mode-vi 'v' if-shell -F '#{selection_active}' "send-keys 'Escape'" "send-keys 'Space'"
```
which simulates the following for default *'Space'* and *'Escape'*:
```text
bind-key -T copy-mode-vi 'v' if-shell -F '#{selection_active}' "send-keys -X 'clear-selection'" "send-keys -X 'begin-selection'"
```

and also doesn't work (but nothing happens) with the simplified conditional:
```text
bind-key -T copy-mode-vi 'v' send-keys -FX '#{?selection_active,clear-selection,begin-selection}'
```

### Required information

* tmux version: **3.1c**
* Platform: **Linux unknown** (*x86_64*) - Tested in both Arch Linux and Debian
* $TERM inside: **screen-256color** and outside of tmux: **xterm-256color**
* Logs from tmux: n/a

**Comment by nicm** [comment]
This is not what `-F` does. `-F` only works with `-X` and expands formats in copy mode commands `search-forward` and `search-backward`. It doesn't expand `send-keys` arguments.

It hangs because you have bound `v` to send the `v` key again (there is a "v" in "active").

If you want to do this you can use `run-shell` to expand for you, something like:
~~~~
run "tmux send-keys '#{?selection_active,Escape,Space}'"

**Comment by caribpa** [comment]
I guess this is what `where appropriate` means in the manual:
```text
-X is used to send a command into copy mode - see the WINDOWS AND
PANES section.  -N specifies a repeat count and -F expands formats
in arguments where appropriate.
```
(This could be better documented, btw 😉)

@nicm thanks for your suggestion but I am trying to avoid spawning a shell... I guess I'll stick with:
```text
bind-key -T copy-mode-vi 'v' if-shell -F '#{selection_active}' "send-keys -X 'clear-selection'" "send-keys -X 'begin-selection'"
```
