### ISSUE TITLE
Seeing tmux splits in other panes

### ISSUE THREAD

**Issue by gblock0** [tmux/tmux#249]
I have `tmux 2.1`, iTerm `Build 2.9.20151227-nightly`, Neovim `NVIM v0.1.1-17-g158dc2b (compiled Dec 12 2015 11:44:03)`.

When splitting tmux panes I am seeing the tmux split in other panes like shown here. I thought it was something I had changed in my tmux setting so I went back to a much earlier revision that I know it was not happening during and that did not help. I've tried playing around with iTerm settings but that doesn't seem to help either. I also think that airline is overflowing to another pane and the red arrow showing where to type on the command line not showing up when a different pane is selected are symptoms of the same issue. If I were to do some work in Vim the pane split will go away, but it does come back when I switch to a different pane.

![Tmux Screenshot](https://cloud.githubusercontent.com/assets/1434705/12020264/f711e2cc-ad3f-11e5-8e13-72297ae83d2f.png)

[Here](https://github.com/gblock0/dotfiles/blob/master/tmux/tmux.conf.symlink) is my current tmux.conf file.

**Comment by nicm** [comment]
TERM?

**Comment by gblock0** [comment]
`xterm-256color`

**Comment by gblock0** [comment]
I forgot to mention I installed this patch for true color support 

```
# Get true colors in tmux until the PR is merged (https://github.com/tmux/tmux/pull/112)
# brew edit tmux
# paste the following before def install
# run `brew install --with-truecolors tmux`

option "with-truecolor", "Build with truecolor patch enabled"
patch do
	url "https://gist.githubusercontent.com/zchee/9f6f2ca17acf49e04088/raw/0c9bf0d84e69cb49b5e59950dd6dde6ca265f9a1/tmux-truecolor.diff"
	sha1 "8e91ab1c076899feba1340854e96594aafee55de"
end if build.with? "truecolor"
```

**Comment by nicm** [comment]
Does it work with stock tmux?

**Comment by gblock0** [comment]
Yes. I just uninstalled it from homebrew, deleted all the files, and reinstalled. Still happening.

**Comment by nicm** [comment]
What do these say inside tmux:

echo $TERM
tmux lsc
tmux showw -g utf8

**Comment by gblock0** [comment]
![screen shot 2015-12-28 at 11 10 00 am 2](https://cloud.githubusercontent.com/assets/1434705/12022244/9ac70128-ad53-11e5-9b27-3fa11956c233.png)

**Comment by nicm** [comment]
IS this still happening? Does it happen in xterm and terminal.app or only in iterm?

**Comment by gblock0** [comment]
It does not seem to be happening in terminal.app and I do not have xterm so I cannot try it out in there.

I just updated to the latest iTerm nightly and it is still happening.

**Comment by nicm** [comment]
Seems like either an iterm bug or your TERM is wrong in iterm.

**Comment by gblock0** [comment]
How would I go about checking my TERM in iTerm? My profile says to report terminal type as `xterm-256color`. Is there something else it should be?

**Comment by nicm** [comment]
echo $TERM

Dunno, seems like xterm-256color should be right...

**Comment by nicm** [comment]
Splits are UTF-8 characters so it sounds like an iterm problem with UTF-8 characters. Particularly if you only see it in iterm.

**Comment by rumbletumjum** [comment]
was having a similar problem, go to iterm preferences -> profiles -> text and make sure "treat ambiguous-width characters as double width" is unchecked. i had checked this while trying to fix some strange airline problem.

**Comment by gblock0** [comment]
@rumbletumjum YESSS!!!!!!!!!!!! Thank you so much! It was driving me bananas!
