### ISSUE TITLE
[feature request] Style for active window

### ISSUE THREAD

**Issue by smprather** [tmux/tmux#2490]
I have developed a work-flow which uses a lot of tmux windows 10+. I am having a very difficult time spotting the '*' that designates the active window. I would like to be able to control the FG/BG colors of the active window text so that it jumps out at me. As far as I can tell, this is not currently possible.

Is there some feature request ranking page where I can bump this if it already exists?

Thanks!
--Myles

**Comment by nicm** [comment]
You should be able to do this by setting a user option on the window with the colour and then using it in `window-status-format`, for example:

**Comment by nicm** [comment]
~~~~
set @myfg red
set -g window-status-format '#[fg=#{@myfg}]#{window_name}'

**Comment by smprather** [comment]
Actually, this is what I need:  window-status-current-style. I checked the docs before coming here, but I totally missed it.

My bad. Sorry to waste your time!
