### ISSUE TITLE
Compilation failed due to the conflict of the keyword '__unused'

### ISSUE THREAD

**Issue by hasegawa-yuta-jaea** [tmux/tmux#2492]
### problem
I was trying to make tmux on CentOS7 with GCC, but the compilation failed with the error like:

```
In file included from /usr/include/fcntl.h:77:0,
                 from compat/closefrom.c:26:
/usr/include/bits/stat.h:106:31: error: expected identifier or ‘(’ before ‘[’ token
     __syscall_slong_t __unused[3];
                               ^
/usr/include/bits/stat.h:164:31: error: expected identifier or ‘(’ before ‘[’ token
     __syscall_slong_t __unused[3];
                               ^
make: *** [compat/closefrom.o] Error 1
```

It seems the keyword '__unused' conflicts with the GCC standard libraries, and I tried to replace the keyword, as like:

``` bash
sed -i -e 's/__unused/test_replacing___unused/g' ./*.{c,h} ./*/*.{c,h}
./configure && make
```

and then, I succeeded to compile tmux.

### what I want ask:
Is it a toolchain problem or known issue?
Otherwise could you fix it? (or should I make a pull request?)

Thank you in advance.

**Comment by micchy326** [comment]
I have same problem.
I bisected this issue.
Then I found this commit  that caused this problem.
bfdc4373d71895a5f454834da4b0bd92ab964dd4

**Comment by nicm** [comment]
Does this fix it?
~~~~
--- a/compat/closefrom.c
+++ b/compat/closefrom.c
@@ -14,8 +14,6 @@
  * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
  */

-#include "compat.h"
-
 #ifndef HAVE_CLOSEFROM

 #include <sys/types.h>
@@ -50,6 +48,8 @@
 # include <libproc.h>
 #endif

+#include "compat.h"
+
 #ifndef OPEN_MAX
 # define OPEN_MAX      256
 #endif

**Comment by hasegawa-yuta-jaea** [comment]
Yes, everything went fine on my env. Thank you!

**Comment by nicm** [comment]
Great, applied, thanks!

**Comment by lonelykid** [comment]
@nicm Looks like you accidentally moved the `compat.h` back to the top again when you do merging.

**Comment by nicm** [comment]
Fixed, thanks.
