### ISSUE TITLE
Please add session-wide window options

### ISSUE THREAD

**Issue by g-raud** [tmux/tmux#2495]
According to the last manual there can be global window options, window-local window options but not session-wide (or session-local) window options.

A particular use-case is being able to easily change the style of a particular session's status line by setting the session option "status-style" and the window option "window-status-current-style" for the session only.  Inside the reconfigured session, at present the window option must be explicitely set on each window creation.

It is certainly already possible to automate this by using session-wide user options and the comand "run-shell" to create a new window.  However having session-wide window options would be much more convenient, in particular to be able to reconfigure easily the style of a particular session on a default tmux install without an already written config file that would define the bind to create a new window respecting the session style.

Thanks

**Comment by nicm** [comment]
I have added this to the todo list but it is not simple so I wouldn't hold your breath.
