### ISSUE TITLE
Can't find in FAQ how to get new panes use the same working directory

### ISSUE THREAD

**Issue by achempion** [tmux/tmux#2498]
The wiki section has FAQ but I haven't found how to make tmux use same working directory for new panes or windows.

I searched repository and other wiki pages as well.

I've found solution how to make tmux persist working directory on pane creation [here on StackOverflow](https://unix.stackexchange.com/questions/12032/how-to-create-a-new-window-on-the-current-directory-in-tmux).

The solution has 320 upvotes, I suppose it's really common case to make it part of FAQ section.

In order to enable keeping the same working directory for the new pane, you need to remap pane creation shortcut to use the same working directory.

~/.tmux.conf
```
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
```

Also, it mentions that it should already be working by default but not in my case. I've installed tmux with `brew install tmux` on pretty much new system with `zsh` as a main shell with oh-my-zsh and iterm2 (iterm2 has this option enabled as well).

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.1c

* Platform (`uname -sp`).
Darwin i386

* $TERM inside and outside of tmux (`echo $TERM`).
`xterm-256color` outside, `screen` inside

* Logs from tmux (`tmux kill-server; tmux -vv new`).
Didn't show anything.

**Comment by nicm** [comment]
tmux does not do this by default.

**Comment by achempion** [comment]
Maybe tmux did it couple of years ago. The comment was:

> A relevant feature landed in the tmux SVN trunk in early February 2012. In tmux builds that include this code, tmux key bindings that invoke new-window will create new a window with the same current working directory as the current pane’s active processes

**Comment by nicm** [comment]
Ah maybe it did, well it doesn't anymore, you need to configure it.

**Comment by nicm** [comment]
Do you want to suggest some text for the FAQ? Or maybe just this page https://github.com/tmux/tmux/wiki/Recipes?

**Comment by achempion** [comment]
@nicm I want to suggest a text for the FAQ, content can be copied from the original post but I can rewrite it if you think something is missing.

Can't send a PR because wiki pages is out of scope with git.

**Comment by nicm** [comment]
I have added this here, thanks: https://github.com/tmux/tmux/wiki/Recipes#create-new-panes-in-the-same-working-directory
