### ISSUE TITLE
How to command-prompt from a shell script?

### ISSUE THREAD

**Issue by mohkale** [tmux/tmux#2499]
### Issue description

I'm currently trying to write a script to interactively pipe-panes. Part of this involves asking the user which direction they want the pipe to go (`in, out, both`), followed by the command name and confirming whether they'd like to kill an open pipe.

`command-prompt` by itself doesn't have a flag to output the result to stdout so I've been trying to do indirectly through `display-message` but It seems to me that the `command-prompt` command implicitly runs a subshell which captures the output preventing my script from recieving it.

For example I have a script `~/tmux-pipe-ctrl` which I've bound to | (`bind | $HOME/tmux-pipe-ctrl`) containing this:

```sh
choice=$(tmux command-prompt -1 -p "Direction (i|o|b):" "display-message -p '%%'")
```

How do I access the command-prompt result from within my script? 

If there's no way (as of yet) I'd like to propose a flag that dumps the prompts result to stdout.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux next-3.3
* Platform (`uname -sp`). Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`). screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
You could either 1) write the result into a file and either use `wait-for` or poll for the file appearing or 2) write your script in two parts and have `command-prompt` run the second part when it finishes (or run the same script with some argument saying it should continue).

**Comment by nicm** [comment]
An option to print result to stdout would be good but I don't know how hard it would be offhand.

**Comment by mohkale** [comment]
@nicm

> write the result into a file and either use wait-for or poll for the file appearing.
> write your script in two parts and have command-prompt run the second part when it finishes

I considered the second option before opening the issue but my main concern is the quoting of shell characters. Seeing as I'll be using command prompt to read shell commands how can I properly escape them before they get passed to `display-message` or `run-shell` before being redirected into a file?.

**Comment by nicm** [comment]
You can try the `q` format modifier.

**Comment by nicm** [comment]
It may be difficult to use it with the result of `command-prompt` however. You may be best to use a popup to prompt the user instead.

**Comment by nicm** [comment]
I have added this to todo list but I wouldn't expect it anytime soon.
