### ISSUE TITLE
seeing automatically zoom out by mouse click 

### ISSUE THREAD

**Issue by muthugopal** [tmux/tmux#250]
I split single pane into 3 or 4 windows. Selected one window
When I click Ctl B z  it zooms into selected window, but as soon as i click anywhere in the zoomed window it zooms out automatically. It is not working. 
So I've to go back to "git checkout `git rev-list -1 --before="2015-12-13" master` revision and it is working fine.

Do you know anything broken or I need to do special settings in my tmux.conf file?

Thanks in advance

**Comment by nicm** [comment]
This should be fixed in Git as soon as it syncs from OpenBSD.
