### ISSUE TITLE
ctrl + b doesn't work

### ISSUE THREAD

**Issue by mohkhz2001** [tmux/tmux#2500]
hello 
i install tmux from apt and ctrl + b doesn't work

**Comment by nicm** [comment]
C-b definitely works.

**Comment by mohkhz2001** [comment]
but doesn't work

**Comment by nicm** [comment]
... what do you press and what do you expect to happen?

**Comment by krader1961** [comment]
@mohkhz2001 You need to provide more information. What tmux version? If you have a *~/.tmux.conf* file show its contents and if not you should tell us you don't have a custom config. And, finally, as @nicm, points out you didn't even tell us what you tried, what the result was, and what result you expected.

**Comment by mohkhz2001** [comment]
my tmux version is tmux 3.0a
I press ctrl + b +% then i expect to split the current pane into two.
(I don't ~/.tmux.conf file )

**Comment by krader1961** [comment]
@mohkhz2001 It works for me. Are you by any chance holding down the Ctrl key when you press `%`? If yes, don't do that. It's Ctrl-b then `%`. Assuming you're on Linux what do you see if you run, outside of a tmux session, `od -tx1z`, then press Ctrl-b, Enter, Ctrl-d? You should see this:

```
0000000 02 0a                                            >..<
0000002
```

Where the `02` shows the expected char was received when you press Ctrl-B.

**Comment by mohkhz2001** [comment]
yes I got exactly this.
this mean Ctrl+B work correctly right?

**Comment by krader1961** [comment]
> this mean Ctrl+B work correctly right?

Yes, it means it sends the expected character; e.g., you haven't done something to your terminal config that is causing it to send the wrong thing. Assuming you're still having problems you'll need to run `tmux -vv` and upload the log files as documented [here](https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md).

**Comment by mohkhz2001** [comment]
[tmux-client-42272.log](https://github.com/tmux/tmux/files/5691718/tmux-client-42272.log)
[tmux-out-42274.log](https://github.com/tmux/tmux/files/5691719/tmux-out-42274.log)
[tmux-server-42274.log](https://github.com/tmux/tmux/files/5691720/tmux-server-42274.log)

**Comment by krader1961** [comment]
@mohkhz2001 Your tmux server log is incomplete. When reproducing a problem of this nature you almost always need to cleanly terminate tmux; such as by exiting all shells. The server log should end with "server loop exit". We're looking for lines like this one (from my server log when I pressed Ctrl-b then %):

```
1607989498.773701 /dev/ttys000: keys are 1 (\002)
...
1607989499.612550 /dev/ttys000: keys are 1 (%)
```

**Comment by mohkhz2001** [comment]
I  copied (tmux -Ltest kill-server) to terminal then type (tmux -vv -Ltest -f/dev/null new) and then saved the 3 log file in my home directory.
[tmux-client-6392.log](https://github.com/tmux/tmux/files/5694688/tmux-client-6392.log)
[tmux-out-6394.log](https://github.com/tmux/tmux/files/5694689/tmux-out-6394.log)

**Comment by mohkhz2001** [comment]
I copied (tmux -Ltest kill-server) to terminal then type (tmux -vv -Ltest -f/dev/null new) and then saved the 3 log file in my home directory.
[tmux-client-6392.log](https://github.com/tmux/tmux/files/5694756/tmux-client-6392.log)
[tmux-out-6394.log](https://github.com/tmux/tmux/files/5694759/tmux-out-6394.log)
[tmux-server-6394.log](https://github.com/tmux/tmux/files/5694761/tmux-server-6394.log)

**Comment by nicm** [comment]
All you are pressing in this file is C-b (`\002`):
~~~~
1608024330.226397 /dev/pts/2: keys are 1 (\002)
1608024330.826502 /dev/pts/2: keys are 1 (\002)
1608024330.867771 /dev/pts/2: keys are 1 (\002)
1608024330.908332 /dev/pts/2: keys are 1 (\002)
1608024330.949236 /dev/pts/2: keys are 1 (\002)
1608024330.990496 /dev/pts/2: keys are 1 (\002)
1608024331.031094 /dev/pts/2: keys are 1 (\002)
1608024331.072463 /dev/pts/2: keys are 1 (\002)
1608024331.113382 /dev/pts/2: keys are 1 (\002)
1608024331.154607 /dev/pts/2: keys are 1 (\002)
1608024331.194464 /dev/pts/2: keys are 1 (\002)
1608024331.235063 /dev/pts/2: keys are 1 (\002)
1608024331.274762 /dev/pts/2: keys are 1 (\002)
1608024331.314796 /dev/pts/2: keys are 1 (\002)
1608024331.354908 /dev/pts/2: keys are 1 (\002)
1608024331.394810 /dev/pts/2: keys are 1 (\002)
1608024331.435008 /dev/pts/2: keys are 1 (\002)
1608024331.476033 /dev/pts/2: keys are 1 (\002)
1608024331.517996 /dev/pts/2: keys are 1 (\002)
1608024331.558413 /dev/pts/2: keys are 1 (\002)
1608024331.598776 /dev/pts/2: keys are 1 (\002)
1608024331.639588 /dev/pts/2: keys are 1 (\002)
1608024331.679731 /dev/pts/2: keys are 1 (\002)
1608024331.720561 /dev/pts/2: keys are 1 (\002)
1608024331.761031 /dev/pts/2: keys are 1 (\002)
1608024331.802191 /dev/pts/2: keys are 1 (\002)
1608024331.842986 /dev/pts/2: keys are 1 (\002)
1608024331.884056 /dev/pts/2: keys are 1 (\002)
1608024331.925021 /dev/pts/2: keys are 1 (\002)
1608024331.966393 /dev/pts/2: keys are 1 (\002)
1608024332.006768 /dev/pts/2: keys are 1 (\002)
1608024332.669440 /dev/pts/2: keys are 1 (\002)
1608024507.642660 /dev/pts/2: keys are 1 (e)
1608024507.918756 /dev/pts/2: keys are 1 (x)
1608024508.410681 /dev/pts/2: keys are 1 (i)
1608024508.992564 /dev/pts/2: keys are 1 (t)
1608024509.989191 /dev/pts/2: keys are 1 (\r)

**Comment by mohkhz2001** [comment]
@nicm  but nothing happens. I don't know what should I do

**Comment by nicm** [comment]
You need to press C-b then another key like % or c.

**Comment by mohkhz2001** [comment]
I pressed C-b+%
[tmux-out-28670.log](https://github.com/tmux/tmux/files/5696369/tmux-out-28670.log)
[tmux-server-6394.log](https://github.com/tmux/tmux/files/5696371/tmux-server-6394.log)
[tmux-server-28670.log](https://github.com/tmux/tmux/files/5696397/tmux-server-28670.log)

**Comment by nicm** [comment]
No you didn't, or your terminal didn't send it. Try pressing `C-b` then release all keys then press `c` and show me the log from that.

**Comment by mohkhz2001** [comment]
[tmux-client-2648.log](https://github.com/tmux/tmux/files/5696804/tmux-client-2648.log)
[tmux-out-2650.log](https://github.com/tmux/tmux/files/5696805/tmux-out-2650.log)
[tmux-server-2650.log](https://github.com/tmux/tmux/files/5696806/tmux-server-2650.log)

I think its get ok. at first I pressed C-b after release  that pressed % then worked

**Comment by nicm** [comment]
Right, that is how it is meant to work.

**Comment by mohkhz2001** [comment]
thank you all to spend your time for my problem @nicm @krader1961 
How do I know that the tmux settings will not be lost after rebooting the system?

**Comment by krader1961** [comment]
You should place any tmux customizations you want to be persistent in a file named *~/.tmux.conf*. Any changes you make interactively will be lost when the tmux server is restarted. There are tools like https://github.com/tmux-plugins/tmux-resurrect but I don't use them. I prefer a simple shell script that uses `tmux send-keys` and similar commands to create my initial set of tmux sessions, windows, initial working directory, running commands, etc.
