### ISSUE TITLE
Select-window with marked window doesn't work across sessions?

### ISSUE THREAD

**Issue by mohkale** [tmux/tmux#2502]
### Issue description
I've setup a binding to let me quickly toggle between my last window and the currently marked window but tmux seems to silently fail when the marked-window is in a different session.

```
bind -r "'" select-window -T -t '{marked}'
```

### Required information

Please provide the following information:

* tmux version (tmux -V). tmux next-3.3
* Platform (uname -sp). Linux unknown
* $TERM inside and outside of tmux (echo $TERM). screen-256color
* Logs from tmux (tmux kill-server; tmux -vv new).

**Comment by nicm** [comment]
select-window does not work across sessions. You need to use switch-client.

**Comment by nicm** [comment]
I'm not sure if switch-client will work with {marked} directly you may need to use both select-window and switch-client or use a script to convert {marked} to a target for switch-client.

**Comment by mohkale** [comment]
@nicm 

All right, I was hoping there was a built in way to do this. Personally I don't see a reason for switch-window to be limited to the current session (from a user POV), but perhaps the code-base seems to enforce the requirement and we'll just have to live with it.

I'll create a script and post it here before closing the issue. Thnx.

**Comment by nicm** [comment]
Most of the time one wants to change window without attaching to a different session, even if there is a client to change. The built-in way to do this is switch-client but I am not certain if will work with {marked}.

**Comment by nicm** [comment]
You could easily script your switch command that saves the current session/window in a user option and your own last command which restores it.

**Comment by mohkale** [comment]
Oooh, didn't think of saving as a user-option. Issue re-opened.

**Comment by mohkale** [comment]
Okay after some rudimentary hacking I've gotten something working. Here's `jump-marked` which I've bound as `bind "'" run -b "$TMUX_HOME/cmds/jump-marked || true"`.

```sh
#!/bin/sh
# A tiny script to let you toggle between the marked window and your
# current window. This works effectively the same as the tmux command
# `select-window -T -t '{marked}'` except this works across sessions.

# The environment variable where we keep track of the last window
# from which we jumped.
MEM=TMUX_LAST_MARKED_JUMP

if [ -z "$TMUX" ]; then
  echo "jump-marked: error: can only be run from within tmux" >&2
  exit 1
fi

current=$(tmux display-message -p '#{window_id}')
if ! marked=$(tmux display-message -p -t '{marked}' '#{window_id}'); then
  tmux display-message "No marked target"
  exit 1
fi

if [ "$current" != "$marked" ]; then
  # Store current position then jump to the marked pane
  tmux set-environment -g "$MEM" "$current" \; switch-client -t "$marked"
else
  last=$(tmux show-environment -g "$MEM")
  last="${last#*=}" # strip leading prefix
  if [ -z "$last" ]; then
    tmux display-message "No last jump target exists, skipping marked jump"
  else
    # Erase memory variable and then jump to the previous point
    tmux set-environment -gu "$MEM" \; switch-client -t "$last"
  fi
fi
```
