### ISSUE TITLE
[Question] Tmux Ctrl+C delay

### ISSUE THREAD

**Issue by scmanjarrez** [tmux/tmux#2503]
### Issue description
Is it possible to change tmux behaviour capturing Ctrl+C? I've read that c0-* options were removed in 2.1 and now backoff option is used. In order to change backoff parameter, should I recompile again?
Right now, if i'm running a process and send Ctrl+C, it takes some time after it catch the signal (or immediately if I alt-tab terminal window).

### Required information

Please provide the following information:
* tmux version (`tmux -V`): tmux 3.1b
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): inside screen-256color, outside xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
What terminal are you using?

**Comment by scmanjarrez** [comment]
Gnome-terminal, Guake and xfce4-terminal. It happens in both terminals.

**Comment by nicm** [comment]
Looks like they are all VTE terminals so they are all the same.

It was definitely OK for me with gnome-terminal a while back, maybe they have changed something.

How are you generating the output and how long does it take? Are you using ssh?

**Comment by scmanjarrez** [comment]
No, no ssh. I'm creating a python gui using PySimpleGUI, it doesn't output anything in the terminal, but Ctrl+C takes some time. Here is a small example (the time taken to close the process increase proportional to code length).
```python
#!/usr/bin/env python

import PySimpleGUI as sg


w = sg.Window('test', [
    [sg.TabGroup([
        [sg.Tab('test1', [
            [sg.InputText('hello world')]])],
        [sg.Tab('test2', [
            [sg.Cancel()]])]
    ])]], finalize=True)

while True:
    ev, val = w.read()

```
![Peek 2020-12-14 17-55](https://user-images.githubusercontent.com/9284124/102110601-a78a9c80-3e35-11eb-9081-ab78f3be7710.gif)
(At the end, I alt-tabbed to other window so the Ctrl-C was received inmediately)

**Comment by nicm** [comment]
Well that is nothing to do with backoff because it isn't sending any output, just seems like the UI is taking a while to respond to SIGINT. Are you sure it doesn't need some UI activity before it does? Can you reproduce with a simpler Python program like:
~~~~
import signal, sys, time

signal.signal (signal.SIGINT, lambda x,y: sys.exit (0))
while 1:
    time.sleep (1)

**Comment by nicm** [comment]
Or since it gets `KeyboardInterrupt` presumably it is not even adding its own signal handler and using Python's, so just try:
~~~~
import time

while 1:
    time.sleep (1)

**Comment by scmanjarrez** [comment]
Doesn't happen with your examples. So it's related with tkinter... thank you very much.
