### ISSUE TITLE
How to change the cursor color when selecting text?

### ISSUE THREAD

**Issue by npearson72** [tmux/tmux#2504]
### Issue description

First of all, thank you for the amazing tool.

My issue is that the cursor color is not visible when selecting text. This affects only the last character when selecting text. It didn't work this way before, but unfortunately I don't know what version of tmux I was on before upgrading to 3.1.

I've attached a demonstration (hope it helps):

![Kapture 2020-12-15 at 21 29 56](https://user-images.githubusercontent.com/1323414/102264312-23601400-3f1e-11eb-8bed-ca5be002ed39.gif)

### Required information

Please provide the following information:

* tmux version: `tmux 3.1c`
* Platform: `Darwin i386`
* $TERM inside and outside of tmux: `screen-256color`
* Logs from tmux: `The log files did not generate for me`

In addition, I'm using:
* alacritty: `0.6.0`

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by npearson72** [comment]
@nicm, Yes I'm afraid it does.

**Comment by npearson72** [comment]
Here's another gif demonstrating with `next-3.3` and with default alacritty (i.e. all custom configs disabled).

**Comment by npearson72** [comment]
I figured I'd also share my `tmux.conf` just in case:

```
# Source config (reload)
bind -n M-R source-file ~/.config/.tmux.conf \; display-message "Config reloaded..."

# Sessions
bind -n M-s choose-session

# Command prompt
bind -n M-: command-prompt

# Windows
bind -n M-t new-window -c "#{pane_current_path}"
bind -n M-] next-window
bind -n M-[ previous-window
bind -n M-w confirm-before -p "kill-pane #P? (y/n)" kill-pane
bind -n M-r command-prompt -I "#W" "rename-window -- '%%'"

set -g renumber-windows on

# Zoom window toggle (o = open window)
bind -n M-o resize-pane -Z

# Panes
bind -n M-| split-window -h -c "#{pane_current_path}"
bind -n M-_ split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

set -g pane-active-border-style fg=colour235
set -g pane-border-style fg=colour235

# Set history
set -g history-limit 50000

# Clear history
bind -n 'C-\' send-keys -R \; send-keys C-l \; clear-history

# Enable mouse mode
setw -g mouse on

# Fix esc lag in vim
set -sg escape-time 0

# Define vi copy mode
set -g status-keys vi

bind -n M-/ copy-mode
bind -T copy-mode-vi C-l send -X end-of-line
bind -T copy-mode-vi C-h send -X start-of-line
bind -T copy-mode-vi C-k send -X previous-paragraph
bind -T copy-mode-vi C-j send -X next-paragraph
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Colors
set -g default-terminal "screen-256color"
set -sa terminal-overrides ",*256col*:RGB"

# Status bar
set -g status-position bottom
set -g status-justify centre
set -g status-bg colour235

# Unselected tabs
set -g window-status-format " #I: #W "
set -g window-status-style fg=colour8

# Selected tabs
set -g window-status-current-format " #I: #W "
set -g window-status-current-style fg=colour2

set -g status-left " #S "
set -g status-left-style fg=colour0,bg=colour2

set -g status-right " %a %h %d, %Y %l:%M %p "
set -g status-right-style fg=colour8
```

**Comment by npearson72** [comment]
I also just tried tag `2.9` and same issue. Wondering if maybe it's an alacritty thing?

**Comment by kchibisov** [comment]
I think it could be alacritty's logic to invert color based off contrast, which as recently added. Maybe it should relaxed even more or adjusted a bit.

So, not a tmux bug, I'd say.

**Comment by npearson72** [comment]
Thanks @kchibisov and @nicm. Indeed the issue is resolved in https://github.com/alacritty/alacritty/issues/4576
