### ISSUE TITLE
Mouse mode does not work on OSX

### ISSUE THREAD

**Issue by R1kk3r** [tmux/tmux#2505]
### Issue description

I did a fresh tmux install through `brew`, created two vertical panes et enabled mouse mode `set -g mouse on`. I tried to select text from one pane but it selects everything from the Terminal.

### Required information

* tmux 3.1.c
* Darwin i386 (OSX 10.15.7)
* $TERM outside (xterm-256color) and inside (screen) 
* Cannot provide logs

**Comment by nicm** [comment]
What terminal are you using?

**Comment by R1kk3r** [comment]
The default terminal app (Terminal 2.10)

**Comment by nicm** [comment]
Works fine for me. I don't remember when Terminal.app started supporting the mouse though.

**Comment by R1kk3r** [comment]
It was been working for me for the past 3 years at least. But recently, it stopped working.

Steps to reproduce:
- tmux 3.1c installed with brew
- no tmux.conf or other config
- start Terminal
- start tmux
- enable mouse: Ctl+b, :set -g mouse on
- split pane and try switch pane by clicking with the mouse or try selecting lines for one pane (should select the whole terminal aka both pane if it does not work)

Does it work for you?

**Comment by nicm** [comment]
Does it work if you build tmux from master?

**Comment by R1kk3r** [comment]
Brew update may have broken things. After a reboot, everything is working fine again.
