### ISSUE TITLE
Using pane_path requires stripping out the beginning to make it useful

### ISSUE THREAD

**Issue by casr** [tmux/tmux#2506]
As I understand it, use of OSC 7 is de facto based on how Terminal.app on macOS implemented it. In the options for Terminal.app, it gives us this description:

> **Programs notify Terminal of the current working directory and document by sending it commands. You may need to configure your shell or other programs to enable this behaviour.**
>
> The working directory and location of the current document may be set using the Operating System Command (OSC) escape sequence:
>
>     ESC ] Ps ; Pt BEL
>
> The parameter Ps is either 6 (document) or 7 (working directory) and Pt is a “file:” URL. The URL should include a hostname to disambiguate local and remote paths, and characters must be percent-encoded as appropriate.
>
> When both the working directory and document are set only the document is displayed.

<details>
<summary>Expand for the code provided by Apple in <code>/etc/zshrc_Apple_Terminal</code></summary>

```
# zsh support for Terminal.


# Working Directory
#
# Tell the terminal about the current working directory at each prompt.

if [ -z "$INSIDE_EMACS" ]; then

    update_terminal_cwd() {
	# Identify the directory using a "file:" scheme URL, including
	# the host name to disambiguate local vs. remote paths.

	# Percent-encode the pathname.
	local url_path=''
	{
	    # Use LC_CTYPE=C to process text byte-by-byte. Ensure that
	    # LC_ALL isn't set, so it doesn't interfere.
	    local i ch hexch LC_CTYPE=C LC_ALL=
	    for ((i = 1; i <= ${#PWD}; ++i)); do
		ch="$PWD[i]"
		if [[ "$ch" =~ [/._~A-Za-z0-9-] ]]; then
		    url_path+="$ch"
		else
		    printf -v hexch "%02X" "'$ch"
		    url_path+="%$hexch"
		fi
	    done
	}

	printf '\e]7;%s\a' "file://$HOST$url_path"
    }

    # Register the function so it is called at each prompt.
    autoload add-zsh-hook
    add-zsh-hook precmd update_terminal_cwd
fi
```

</details>

This will result in, for example, `file://mycomputername/Users/casr/Projects`.

When opening new splits, I would like them to make use of `pane_path` to establish the starting directory so I have this setup in my `.tmux.conf`:

```
bind-key '"' split-window -v -c "#{s@file.//#H@@:pane_path}"
bind-key % split-window -h -c "#{s@file.//#H@@:pane_path}"
```

Which performs a regex the removes the unnecessary parts and leaves just the directory. (btw, I wasn't able to work out how to escape a colon character, `:`, so I ended up just using the match-any character, `.`)

The question I have is whether I should continue to do the regex approach or should tmux take on that side of things internally?

<details>

<summary>Expand for requested details</summary>

macOS Catalina 10.15.7

```
$ uname -sp && tmux -V
Darwin i386
tmux 3.1c

$ echo $TERM  # outside tmux
nsterm

$ echo $TERM  # inside tmux
tmux-256color
```

</details>

**Comment by nicm** [comment]
Last time I checked there is no agreement on what exactly it should look like so tmux just passes it through and you can handle it how you want.

**Comment by casr** [comment]
That's fair enough. I can see that dealing with different hostnames, say for instance a connection over SSH, adds its own complications that should be handled by the user. Thanks for the reply!
