### ISSUE TITLE
Can't get some hex colors to show up in tmux status

### ISSUE THREAD

**Issue by oblitum** [tmux/tmux#2507]
### Issue description

I can't get the color `#FCE8C3` to display in tmux status line, this happens for other colors, but we can use this one as example. I have my status line like this (weird chars are powerline characters):

```conf
set -g default-terminal 'tmux-256color'

# Enable 24 bit true colors
set -ga terminal-overrides ',*:RGB'

FGL1="#FCE8C3"
FGL2="#FCE8C3"
FGL3="#FCE8C3"
FGR1="#FCE8C3"
FGR2="#FCE8C3"
FGR3="#FCE8C3"
FGLC="#ffffff"
BGL1="#3A3A3A"
BGL2="#262626"
BGL3="#303030"
BGR1="#3A3A3A"
BGR2="#303030"

set -g status "on"
set -g status-style "none"
set -g status-style bg="$BGL2"
set -g status-justify "left"
set -g status-left-style "none"
set -g status-left-length "100"
set -g status-right-style "none"
set -g status-right-length "100"
set -g message-style fg="$BGL1"
set -g message-style bg="$BGL2"
set -g message-command-style fg="$BGL1"
set -g message-command-style bg="$BGL2"
set -g pane-border-style fg="$BGL2"
set -g pane-active-border-style fg="$BGL3"
setw -g window-status-style "none"
setw -g window-status-style fg="$BGL1"
setw -g window-status-style bg="$BGL2"
setw -g window-status-separator ""
setw -g window-status-activity-style "none"
setw -g window-status-activity-style fg="$BGL1"
setw -g window-status-activity-style bg="$BGL2"
set -g status-left "#[fg=#ff0000,bg=$BGL1,bold] XXX #[fg=$FGL1,bg=$BGL1,bold]#S #[fg=$BGL1,bg=$BGL2,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=$FGLC,bg=$BGL2,bold]#I#[fg=$BGL2,bg=$BGL3,nobold,nounderscore,noitalics]#[fg=$FGL3,bg=$BGL3]#W #[fg=$BGL3,bg=$BGL2,nobold,nounderscore,noitalics]"
setw -g window-status-format "#[fg=$FGL2,bg=$BGL2]#I#[fg=$BGL2,bg=$BGL3,nobold,nounderscore,noitalics]#[fg=$FGL3,bg=$BGL3]#W #[fg=$BGL3,bg=$BGL2,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=$FGR3,bg=$BGL2]#H #[fg=$BGR2,bg=$BGL2,nobold,nounderscore,noitalics]#[fg=$FGR2,bg=$BGR2] %k:%M #[fg=$BGR1,bg=$BGR2,nobold,nounderscore,noitalics]#[fg=$FGR1,bg=$BGR1] %d/%m "
```

The session name (`#S`) that comes after `XXX`, doesn't take the `$FGL1` (`#FCE8C3`) color, it seems some internal error happens, and instead of getting that color it instead picks the colors of the previous segment. `XXX` is in `#ff0000`, so `#S` is also  `#ff0000`. If I change `#FCE8C3` to `#ECE8C3`, this doesn't happen.

I have true colors working inside tmux, already tested with https://unix.stackexchange.com/questions/404414/print-true-color-24-bit-test-pattern. It seems #315 may be related to this.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  tmux 3.1c
* Platform (`uname -sp`).
  Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`).
  tmux-256color, alacritty
* Logs from tmux (`tmux kill-server; tmux -vv new`).
  [tmux-out-56467.log](https://github.com/tmux/tmux/files/5705462/tmux-out-56467.log), [tmux-server-56467.log](https://github.com/tmux/tmux/files/5705464/tmux-server-56467.log), [tmux-client-56465.log](https://github.com/tmux/tmux/files/5705465/tmux-client-56465.log)

**Comment by oblitum** [comment]
Sorry, I'm updating the issue, clicked enter by accident.

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by oblitum** [comment]
Yes.

**Comment by nicm** [comment]
Can you trim your config down to one option that shows the problem?

**Comment by nicm** [comment]
It's just `status-left`?

**Comment by nicm** [comment]
Oh this is because `#F` is the short alias for `#{window_flags}`.

**Comment by oblitum** [comment]
@nicm so it's a bug, there's no alternative way to set these colors?

**Comment by nicm** [comment]
Try `##F` or `#fce8c3` instead.

**Comment by oblitum** [comment]
Yes, lowecase circumvents the issue. Feel free to close it, or let it open in case of providing a fix for uppercase color codes.
