### ISSUE TITLE
Clarify definition of "server version"

### ISSUE THREAD

**Issue by gnachman** [tmux/tmux#2509]
### Issue description

I have been under the impression that `display-message -p "#{version}` would return the tmux version, such as `3.1`. However, according to https://gitlab.com/gnachman/iterm2/-/issues/9375 on OpenBSD it may return a string like `openbsd-6.8`.

This is a problem for my app (iTerm2) because it cares very much about the tmux version for the control mode integration.

The man page's description of `version` simply says `Server version`, which is too vague to be useful.

Is OpenBSD doing the wrong thing here? If not, is it possible to map from the openbsd version to the "real" version?

In the spirit of making this an issue rather than a cry for help, it would be great for the man page to be more specific about what you can expect from the `version` variable.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). openbsd-6.8
* Platform (`uname -sp`). OpenBSD
* $TERM inside and outside of tmux (`echo $TERM`). n/a
* Logs from tmux (`tmux kill-server; tmux -vv new`). n/a

**Comment by kamat1z** [comment]
Just FYI, since tmux is developed by the OpenBSD team as part of OpenBSD, "openbsd-6.8" *is* the server version, I believe.  The release of tmux on other platforms is. . . platform dependent.

**Comment by nicm** [comment]
Right, I have never bothered to match up portable and OpenBSD versions, although I guess I could do so.

**Comment by nicm** [comment]
The description of the version number is here: https://github.com/tmux/tmux/wiki/FAQ#how-often-is-tmux-released-what-is-the-version-number-scheme

**Comment by nicm** [comment]
I'm not sure what I can change to help you. I mean in future we could add a flags variable or something to detect features you care about, but it doesn't help you much with previous versions. Although given that this has not been an issue up to now, I guess very few people are using iTerm2 with tmux on OpenBSD so those that do will be using a recent OpenBSD version.

**Comment by gnachman** [comment]
Thanks for the explanation.

It looks to me like the OpenBSD code doesn't correspond to a tagged version in git. Is there any way to see when it was forked and what changes were cherrypicked? This would make it easier to figure out what changes I need to make to my version number-dependent code.

**Comment by gnachman** [comment]
Hm, I think the faq is wrong. OpenBSD 6.7 is the first version that supports `-V`.

![image](https://user-images.githubusercontent.com/427546/102702428-556fbf80-4217-11eb-98e0-b5e82f7f9730.png)

**Comment by nicm** [comment]
> It looks to me like the OpenBSD code doesn't correspond to a tagged version in git.

Yes the releases will not necessarily match up exactly. Every change is synced from OpenBSD a few hours after if is committed. Then for the portable release I will make a tag and a release candidate at some point and cherry pick fixes into it until the release is made. OpenBSD follows a different process where the tree is locked for testing a month or so before release and then tagged and unlocked a few weeks later and released after all the builds are ready.

The only way to match them up would probably be to look for the matching commit around the time of the first release candidate and look at the `CHANGES` file to try and work out what was added afterwards. Here are the most recent:
~~~~

Aug 29  2017 tmux-2.6-rc.tar.gz
Sep 10  2017 tmux-2.6-rc2.tar.gz
Sep 11  2017 tmux-2.6-rc3.tar.gz
Oct  5  2017 tmux-2.6.tar.gz
Mar 22  2018 tmux-2.7-rc.tar.gz
Apr 13  2018 tmux-2.7.tar.gz                                    Aug 17  2018 tmux-2.8-rc.tar.gz                                 Oct 17  2018 tmux-2.8.tar.gz                                    Mar 26  2019 tmux-2.9-rc.tar.gz                                 Apr  2  2019 tmux-2.9-rc2.tar.gz                                Apr 11  2019 tmux-2.9-rc3.tar.gz                                Apr 24  2019 tmux-2.9.tar.gz                                    May  1  2019 tmux-2.9a.tar.gz                                   Jun  5  2019 tmux-3.0-rc.tar.gz                                 Jun 14  2019 tmux-3.0-rc3.tar.gz                                Jul 29  2019 tmux-3.0-rc4.tar.gz                                Sep 16  2019 tmux-3.0-rc5.tar.gz                                Nov 26  2019 tmux-3.0.tar.gz                                    Dec  1  2019 tmux-3.0a.tar.gz                                   Feb  4  2020 tmux-3.1-rc.tar.gz                                 Mar 11  2020 tmux-3.1-rc2.tar.gz                                Mar 18  2020 tmux-3.1-rc3.tar.gz                                Apr  6  2020 tmux-3.1-rc4.tar.gz                                Apr 24  2020 tmux-3.1.tar.gz                                    Apr 29  2020 tmux-3.1a.tar.gz                                   May  4  2020 tmux-3.1b.tar.gz                                   Oct 30 12:16 tmux-3.1c.tar.gz                                   ~~~~

There is an OpenBSD git mirror somewhere that would probably be easier than using CVS.

Or if you tell me what you are looking for I can probably work it out?

> Hm, I think the faq is wrong. OpenBSD 6.7 is the first version that supports -V.

I might have got it confused, I'll change it.

**Comment by gnachman** [comment]
I think I found everything I care about and was able to find good enough correspondences between openBSD and portable versions. The only case that is hard to handle is future releases; I know that tmux 3.2 will trigger a bunch of new logic because of pausing. It's kinda risky to assume that'll be in all OpenBSD > 6.8. The features I need to detect specifically are:

* `refresh-client -B` to (un)subscribe to formats
* `refresh-client -fpause-after`
* In control mode, tmux waits for a newline before closing the connection after `%exit`

**Comment by nicm** [comment]
You could just assume it will be in 6.9, people using 6.8 will be no worse
off than they are today.

**Comment by gnachman** [comment]
The risk is that if for some reason 6.9 does not pick up these features, the tmux integration will be completely broken. If you're highly confident that it'll make the cut, I'll go with that.

**Comment by nicm** [comment]
Well unless we discover it is broken after 6.8 is tagged in April or so when it is too late to fix, it will be in 6.9. You could wait for 7.0 if you want to be really safe, by then tmux 3.2 should be released so the code will have had more testing. I doubt it will make a difference to many people.

**Comment by kamat1z** [comment]
Seeing as how this is completely busted for OpenBSD 6.8 users, and I'm apparently one of two people affected (and 6.8 came out over two months ago), I'd vote to make the assumption 6.9 will have this as well, and if it turns out it doesn't, we can revert after the fact :-).

**Comment by gnachman** [comment]
Sounds good. I'll be optimistic for now and I can always ship a bugfix release in the event of a water landing.

It would be great to have the ability to query for the availability of features since version numbers aren't a great solution to the problem. The ideal api would let me ask if a command accepts an argument without actually having to run the command. For example, `set-option` gained `-p` in tmux 3.0. If I could do something like `introspect set-option -p` and it returns `true` if `-p` is a support argument or `false` if not then I wouldn't need to use version numbers at all in the future. I think you've already got all the info needed in the various `cmd_entry` structs.

**Comment by nicm** [comment]
If you use -? you will get the usage string you could look at that?

**Comment by gnachman** [comment]
`set-option -?` gives an error but does also show usage. I think I can parse that and find what I need. That works as long as `-?` will never be a valid flag in the future.

**Comment by nicm** [comment]
-? will never be valid and the format of the usage string is standard and
won't change.
