### ISSUE TITLE
tmux select window with Alt<number> (i.e., allow to use numbers on keybindings)

### ISSUE THREAD

**Issue by evandrocoan** [tmux/tmux#2510]
Originally requested on:
1. https://unix.stackexchange.com/questions/352436/tmux-select-window-with-altnumber
1. https://unix.stackexchange.com/questions/102170/how-can-i-bind-ctrl-alt-0-9-in-tmux

> In tmux to select a window, the default behavior is `C-b <number>`.
> I would like to avoid the prefix by using alt+<number> for faster selecting.
> 
> I did it for the next and previous window, and it works:
> 
>      bind -n M-n select-window -n
>      bind -n M-p select-window -p
> 
> For the selection by id, I did the same, but it does not work:
> 
>     bind -n M-0 select-window -t 0
>     bind -n M-1 select-window -t 1
>     bind -n M-2 select-window -t 2
>     bind -n M-3 select-window -t 3
>     bind -n M-4 select-window -t 4
>     bind -n M-5 select-window -t 5
>     bind -n M-6 select-window -t 6
>     bind -n M-7 select-window -t 7
>     bind -n M-8 select-window -t 8
>     bind -n M-9 select-window -t 9
> 
> Is there an easy way to make it work?

**Comment by nicm** [comment]
It certainly does work.

**Comment by nicm** [comment]
I don't believe you even tried your own example.

**Comment by systemmonkey42** [comment]
I would like to add, it works for me.  I literally pasted what you posted into a file, sourced it from within tmux, and ALT 1-9 worked as you described.

However,  I would also like to add, PLEASE don't make this a default.  <kbd>M-1</kbd> - <kbd>M-9</kbd> and <kbd>M-0</kbd> are used by bash during command line editing.  Losing that would be very annoying.

**Comment by nicm** [comment]
This will not be the default and I don't think anyone is suggesting it.

**Comment by evandrocoan** [comment]
> I would like to add, it works for me.

If it is working then, I am closing it. Thanks for trying it out.
