### ISSUE TITLE
`display-message -p` (writing to stdout) doesn't work when called from within another command

### ISSUE THREAD

**Issue by cipriancraciun** [tmux/tmux#2512]
### Issue description

`display-message -p some-format` doesn't work when called as a consequence of another command, which is itself run from the terminal (i.e. `tmux some-command 'display-message -p some-format'`).

The following works as expected (i.e. `test` is correctly piped to `base64`):
~~~~
tmux display-message -p test | base64
~~~~

The following doesn't work as expected, `base64` receives nothing as input, and instead the `display-message` command is run just like `run-shell` "in the background" and it's output is displayed in copy-mode:
~~~~
tmux choose-tree 'display-message -p %%' | base64
~~~~

(I use here `base64` to make sure that the output is actually given to `tmux`'s stdout as opposed to writing it into the pane.)

This issue might be related to #2499, although that discusses `command-prompt` and stumbles into the same issue as this one.  I don't think this is actually a duplicate, because perhaps a proper solution of that issue might be adding a similar `-p` flag to `command-prompt`.

### Required information

Please provide the following information:

* tmux version (`tmux -V`) -- `tmux 3.1c`
* Platform (`uname -sp`) -- `Linux 5.9.12-1-default x86_64`
* `$TERM` inside and outside of tmux (`echo $TERM`) -- `rxvt-unicode` (external) and `screen` (internal);

**Comment by nicm** [comment]
It would be very complicated to make `display -p` work when run from `choose-tree` and I do not see it happening. Use a temporary file.

**Comment by nicm** [comment]
I have added this to todo list but I wouldn't expect it anytime soon, thanks.

**Comment by cipriancraciun** [comment]
Out of curiosity where is the TODO list managed?

(I've tried to look for a TODO file in the repository, but failed to find one.)

**Comment by nicm** [comment]
Here: https://github.com/tmux/tmux/wiki/Contributing#code-contributions

Funnily enough it used to be in a TODO file but I moved it to the wiki when someone was complaining about something and pretended they would contribute instead of complaining if only the documentation was better :-).
