### ISSUE TITLE
[feature request]  Add a variant of `remain-on-exit` that keeps open only failed panes

### ISSUE THREAD

**Issue by cipriancraciun** [tmux/tmux#2513]
It would be nice to have something like `remain-on-failed` variant of `remain-on-exit` that would keep a pane open only if the command exited with a non-zero status.

At the moment this can be simulated by using:
~~~~
set -g remain-on-exit on
set-hook -g pane-died { if-shell -F "#{pane_dead_status}" {} { run-shell "tmux kill-pane -t #{pane_id}" } }
~~~~

**Comment by nicm** [comment]
Try this please: [tmux-remain-on-exit.diff.txt](https://github.com/tmux/tmux/files/5746689/tmux-remain-on-exit.diff.txt)

**Comment by cipriancraciun** [comment]
I've tried to apply that patch (on top of master at `f72deb092a559224b9226a49550d15507685e508`) and for some reason it doesn't quite work regardless of the exit status (i.e. it behaves just like `off` would have been set).

Here is how I've tested it (basically I've made sure that my configuration and environment doesn't poison the test):
~~~~
env -i TERM=linux ./tmux -L test -f /dev/null -- set-option -g remain-on-exit failed ';' new-session exit 1
~~~~

Now I've patched your code so that if `failed` is set, the `case 2` option, I've added the following debugging statements:
~~~~
f = fopen("/tmp/tmux-status.txt", "a");
fprintf(f, "%d %d\n", wp->status, WEXITSTATUS(wp->status));
fclose(f);
~~~~

Then I've commented the `if ... break` so `case 2` behaves just like `case 1`.

Then I've looked at the contents of the `/tmp/tmux-status` file and for some reason it contains two lines:
~~~~
0 0
256 1
~~~~

It seems that something calls the `server_destroy_pane` twice, once with an invalid status, most likely the default `0` which confounds with the actual exit code of 0.

**Comment by nicm** [comment]
Hmm it worked for me, I'll take a look.

**Comment by nicm** [comment]
Your example works for me, although you end up with the session detached. Is that what you are seeing or do you see the server actually exiting?

**Comment by nicm** [comment]
I wonder why `failed` detaches but `on` does not...

**Comment by nicm** [comment]
Hmm sometimes it does exit actually, never mind.

**Comment by nicm** [comment]
OK simple enough, `off` checks for the `PANE_STATUSREADY` flag but `failed` does not which means it can fail if the pty is closed before the SIGCHLD is received. Try this instead please: [tmux-remain-on-exit-2.diff.txt](https://github.com/tmux/tmux/files/5756941/tmux-remain-on-exit-2.diff.txt)

**Comment by cipriancraciun** [comment]
I can confirm that now it works as expected.

Thanks.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
