### ISSUE TITLE
[feature request]  Add an option to expand "formats" in an quoted string (at command parsing time, not at command execution time)

### ISSUE THREAD

**Issue by cipriancraciun** [tmux/tmux#2514]
This feature is related to something I've stumbled while reporting #2513, namely using any "formats" (things like `#{pane_id}` or `#{pane_status}` from hooks) with commands that don't support themselves format expansion (like `kill-pane -t #{pane_id}` for example).

Currently the following hook doesn't work because `kill-pane` itself doesn't know to expand the `-t` argument value:
~~~~
set -g remain-on-exit on
set-hook -g pane-died { if-shell -F "#{pane_dead_status}" {} { kill-pane -t "#{pane_id}" } }
~~~~

At the moment one has to use `{ run-shell "tmux kill-pane -t #{pane_id}" }` which not only involves an extra `sh` and `tmux` execution, but it might also break if one would have used for example `#{session_id}` which expands to something like `$5` which then shell would have tried to expand.  (In fact one would need to use `{ run-shell "tmux kill-pane -t #{q:pane_id}" }` to actually be correct.

Thus perhaps a new "meta-character" would be useful in quoted strings that would apply the "formats" syntax at command parsing time.  For example something like `$#{format}`, thus the previous use-case would simply be:
~~~~
set -g remain-on-exit on
set-hook -g pane-died { if-shell -F "#{pane_dead_status}" {} { kill-pane -t "$#{pane_id}" } }
~~~~

**Comment by systemmonkey42** [comment]
Hi All

I've struck this particular problem today and came here to offer a suggestion.

I'm currently working around the problem using
```
run-shell 'tmux <tmux command requiring format expansion>'
```

A cleaner, better supported method could be:
```
run-shell -F  <tmux command requiring format expansion>
```

The would be a elegant solution allowing someone to : 

1.  Arbitrarily fabricate commands via format expansion (bad example:  `#{?somevar,swap,join}-pane -t #{somevar}` )
2.  Avoid launching an unnecessary shell


Regards

**Comment by systemmonkey42** [comment]
As an aside, when TMUX is launched, is the correct path to TMUX available in a variable or setting somewhere?

When testing, tweaks I may have a couple of builds, and any macros which invoke `run-shell tmux <command>` often get the wrong tmux build and end up breaking.

**Comment by nicm** [comment]
Adding `run -F` is good idea, although I wouldn't be too worried about an extra shell, it isn't expensive.

An env var with the tmux binary is also a good idea although I am not sure there is a portable way for an application to discover its own executable path so it may not be possible.

**Comment by cipriancraciun** [comment]
Adding that `run-shell -F` would be nice, especially since it would remove the extra shell execution.

(BTW, executing an extra shell indeed isn't much of an issue performance wise, however I always find it strange when tools need to invoke `sh -c` even for simple tasks.)

Moreover the `run-shell -F` feature although technically would solve the problem, it opens other potential problems due to quoting;  for example if one would be to expand the window title and if that window title contains "strange things" it would badly interact with `sh` quoting and thus create all sorts of problems.

**Comment by systemmonkey42** [comment]
Good point about the quoting.

I've had so many problems with quoting I almost always use 'run' and 'if-shell' to invoke a script to query tmux options (like window and pane titles) and perform the required actions

I suspect a generic "#{q:#{window_title}}" modifier which performed magic quoting similar to `printf %q` under `bash`
```bash
printf "%q\n"  'a long "name"'
a\ long\ \"name\"
```

This would allow the use of automatic quoting when it was important.

Thanks

**Comment by nicm** [comment]
If you are concerned about characters in things like `pane_title`, the solution is to write a separate shell script that reads `pane_title` with `display -p` and run it with `run-shell`. I don't mind adding convenience features but we are not trying to fix every potential problem, tmux is intended to work with sh, not to replace it.

**Comment by nicm** [comment]
`#{q:pane_title}` already exists of course.

**Comment by systemmonkey42** [comment]
> `#{q:pane_title}` already exists of course.

Of course it does.  I was literally digging though to the documentation to find it.  searching for 'q:' finds it quickly.

**Comment by nicm** [comment]
Try this for `run -F` please: [tmux-run-shell-F.diff.txt](https://github.com/tmux/tmux/files/5757080/tmux-run-shell-F.diff.txt)

**Comment by systemmonkey42** [comment]
Thanks for that.

The patch passes my limited testing (using #{} expansion in "swap-pane")
```
$ tmux-run-test set-option -w @pane %1
$ tmux-run-test swap-pane -t #{@pane}
tmux-run-test: option requires an argument -- t
usage: swap-pane [-dDUZ] [-s src-pane] [-t dst-pane]
$ tmux-run-test run -F 'swap-pane -t #{@pane}'
$
```

I'll try a few other things and let you know if I have a problem.

Cheers

**Comment by nicm** [comment]
I have applied this to OpenBSD now, but I chose to use `-C` rather than `-F` because it is not exactly the same as `if-shell` or the other `-F` flags. It will be in GitHub later when it syncs up.

**Comment by cipriancraciun** [comment]
So now we have a `run-shell` that if given `-C` it will first expand the argument with "formats syntax" and then run that string as an internal command (as opposed to invoking `sh -c`)?

----

However even though this technically solves my proposal I still do think that the `tmux` interpreter lacks an "orthogonal" string expansion capability.

Why do I say so?  For all programming languages out-there (from `sh` to `ruby`) if one uses "special quotes" that allows "expansion" then that expansion will happen always, regardless of the "command" that string is argument of.

Here `tmux` provides the double quote `"` which allows the expansion of `$ENV` tokens.  However it also introduces another expansion syntax, the "formats syntax" (plus the `%%` and `%%%` for select commands), which is applied only for some commands (by default) and for other commands at explicit request through custom flags.  Therefore, at least a beginner, will  find the expansion rules very confusing.

Thus this feature request that would add an `$#{...}` (or similar) syntax that would always expand using the "formats syntax" regardless of the executed rule.

**Comment by nicm** [comment]
We could actually add something that is expanded in all arguments when they are parsed (that is just, after getopt) but I'm not sure how much use it would be because most format variables will not be available in the config file. So it would only be of real use in commands which parse again (if-shell, run-shell, etc) and we can just make them expand formats (most of them do already).

**Comment by cipriancraciun** [comment]
@nicm Sorry I didn't follow through...  Will the patch land in GitHub at a later time?

**Comment by nicm** [comment]
`run-shell -C` should be there now.
