### ISSUE TITLE
show-hooks picks up user options

### ISSUE THREAD

**Issue by carlocab** [tmux/tmux#2515]
### Issue description

Running `tmux show-hooks -g` also returns user options. For example, in a `tmux.conf` file that contains only

    set -g @foo bar

running `tmux show-hooks -g | head` returns
```
@foo bar
after-bind-key
after-capture-pane
after-copy-mode
after-display-message
after-display-panes
after-kill-pane
after-list-buffers
after-list-clients
after-list-keys
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `tmux next-3.3`
* Platform (`uname -sp`). `Darwin i386` macOS 11.1
* $TERM inside and outside of tmux (`echo $TERM`). `tmux-256color` and `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-66952.log](https://github.com/tmux/tmux/files/5743338/tmux-client-66952.log)
[tmux-out-66955.log](https://github.com/tmux/tmux/files/5743339/tmux-out-66955.log)
[tmux-server-66955.log](https://github.com/tmux/tmux/files/5743340/tmux-server-66955.log)

These logs were produced by running

    ❯ tmux -vv -Ltest -f/tmp/test.conf new

where
```
❯ cat /tmp/test.conf
set -g default-shell /bin/bash
set -g @foo bar
```
I set the default shell to avoid some issues related to my `zshrc` depending on the contents of my usual `tmux.conf`.

**Comment by nicm** [comment]
This should be fixed in OpenBSD now, will be in GitHub later. Thanks!
