### ISSUE TITLE
setenv does not update global environment at start

### ISSUE THREAD

**Issue by Nomarian** [tmux/tmux#2517]
### Issue description

When trying to source a file at tmux start, the file changes directories between hosts
a clear way of loading it is by setting a variable

```
setenv -g file /tmp/tmux.conf
source $file
```

this however fails. however, what is supposed to be the equivalent, = actually works

```
file=/tmp/tmux.conf
source $file
```

### Required information

* Version: tmux 3.1c
* Platform: Raspbian Buster

**Comment by nicm** [comment]
https://man.openbsd.org/OpenBSD-current/man1/tmux.1#COMMAND_PARSING_AND_EXECUTION

`$file` is replaced when the config file is parsed, `setenv` does not change it until it is executed.

**Comment by Nomarian** [comment]
Shouldn't it change it? the man page does state


> Environment variables preceded by $ are replaced with their value from the global environment (see the GLOBAL AND SESSION ENVIRONMENT section).

**Comment by nicm** [comment]
What has that got to do with setenv?

**Comment by nicm** [comment]
`setenv` changes it when it (`setenv`) is executed. `$file` is replaced when the config file is parsed. The config file is parsed first.

**Comment by Nomarian** [comment]
Well... you're the expert, it seems inconsistent to me. but I got what I wanted with =. so you can close the issue if you want.
