### ISSUE TITLE
Crashing on pane resize with oh-my-zsh

### ISSUE THREAD

**Issue by setho246** [tmux/tmux#2518]
### Issue description

When resizing a pane smaller than "what is reasonable", server occasionally crashes. I believe it may have something to do with either ligatures or emoji, as these seem to generate crashes more consistently.

I am using ZSH with oh-my-zsh and [Spaceship Prompt/Theme](https://github.com/denysdovhan/spaceship-prompt).

I'm encountering the problem with TMUX 3.1b, with both my personal config file and without any config file.

As mentioned above, I believe it may have something to with wrapping ligatures/emoji, as my prompt normally looks like this, with project folder, git branch, and docker version in the prompt:
![image](https://user-images.githubusercontent.com/11419173/103326347-13ab0880-4aa4-11eb-9afb-f7e6181ed23c.png)

My steps for recreating have been:
Open 2 panes side by side
Change both panes into a directory with a prompt that has git/docker
Use key binds to grow the left pane/shrink the right pane until the right pane cannot be any smaller.
Attempt to shrink right pane more.
Server Crashes.

I have run the `tmux -vv` new both with and without my config. Running with my config has a line at the bottom of the server logs about `fatal: offset too big`, but the default-config logs do not, even though the error is the same. Because of this, I have attached both.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

TMUX 3.1b

* Platform (`uname -sp`).
Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).
Outside: xterm-256color
Inside: screen

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[withConfig.zip](https://github.com/tmux/tmux/files/5752831/withConfig.zip)
[withoutConfig.zip](https://github.com/tmux/tmux/files/5752832/withoutConfig.zip)

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by nicm** [comment]
This was possibly fixed by https://github.com/tmux/tmux/commit/212c0c1f7212b537aafc6f83d848ecf0b804696d.

**Comment by setho246** [comment]
Perfect, looks like its fixed for me!

**Comment by nicm** [comment]
Good stuff.
