### ISSUE TITLE
[Feature Request] Allow multiple '%%' expansions under display-panes / choose-tree

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#2520]
I'm trying to bind a menu (display-menu) to a chosen pane (result of choose-tree / display-panes)

The displayed menu requires the target `%%` to be expanded in each menu option command, however only the first
is ever expanded.

As a workaround, the following seems to work;
```tmux
display-panes set-option -w @target %% \; display-menu -T title "option 1" 1 run-shell 'tmux select-pane -t #{@target}'
```

This isn't terribly efficient, its impossible to clean up `@target` and quoting is proving to be unmanageable.

Thanks

**Comment by nicm** [comment]
Doesn't `%1` replace multiple?

**Comment by systemmonkey42** [comment]
> Doesn't `%1` replace multiple?

So it does. Thank for that.

`%1` is documented under `command-prompt`.  I had no idea it worked elsewhere.

**Comment by nicm** [comment]
They (`%%` and `%n`) use the same code. They predate formats, if I was doing it now I would make it `#{replace1}` or something. At some point we should probably merge it into formats and make `%n` an alias.

**Comment by systemmonkey42** [comment]
I was thinking about the implications of this..

Where 
```
display-panes swap-pane -t %%
```
was replace with
```
display-panes swap-pane -t #{replace1}
```

You have two options 
- swap-pane (and every other command) supports '#{...}' in every parameter, or 
- expand all '#{...}' (like the run -F patch) at parse time, and NO commands need to parse their parameters.

There is now the risk that a command which changes a variable, or a setting, or the state of a window/pane may not work as expected because the `#{...}` fields were expanded at parsing time, rather than at run-time.

You could selectively expand only those which touch `replaceN`, however that is difficult where `#{?pane_in_mode,#{replace1},#{replace2}}` style expansions change their outcome based on commands executed during the macro.

The following command would need some sort of escaping because replace1 is used initially when selecting the target pane, and again when selecting the source pane...
```
display-panes "set-option -w @original #{replace1} ; display-panes \"swap-pane -s #{replace1} -t #{@original}\""
```
Even with run-time (rather than parse time) expansion, there will need to be an option to preserve parameters by assigining them to a holding variable for later processing.

Currently I do something like
```
$ tmux display-panes "set-option -w @original %1 ; display-panes \"display-message 'swap-pane -s %\061 -t #{@original}'\""
```
Where `%\061`  is the only incantation i've been able to use to delay expansion.  (replace `display-message` with r`un -F` :-) )

**Comment by nicm** [comment]
The few commands that use `%%` and `%%%` would need to change to expand formats instead in those arguments.

I don't think it is practical to expand all formats at parse time (if that is what you are suggesting) because almost all current uses expect them to be expanded at execution time and would need them to be escaped. So it would break any existing config using formats.

You could avoid your %\061 stuff by putting the inner command in a separate shell script and running it with `run-shell`.

Another way to tidy it up would be if `set-hook -R` supported firing a user option. Then you could split your command across multiple user options.

Possibly that might work with `run -F` actually, although I haven't tried...

**Comment by systemmonkey42** [comment]
I guess I'm saying leave all expansion to run-time, but make sure all commands support it.

I'm thinking a range of issues stem from `-s` and `-t` options not supporting format expansion by default.
Any time a session/window/pane target id is resolved, it makes sense expand formats before resolving the target.   

BTW,  I just realised that since %% only expands the first occurence, in my example above, using %% instead of %1 works fine.

**Comment by martinvonwittich** [comment]
> Doesn't `%1` replace multiple?

This worked for me with `choose-tree`, and really should be documented in the manpage. Could the issue be reopened and adapted as a documentation ticket?
