### ISSUE TITLE
[feature request]  Add a warning in the `tmux` manual that a colon at the end of an argument is interpreted as a command separator

### ISSUE THREAD

**Issue by cipriancraciun** [tmux/tmux#2522]
If one runs the following, one correctly gets a new `tmux` session and window with the name `hello ; world`:
~~~~
env -i TERM=linux tmux -L test -f /dev/null -- new-session -n 'hello ; world' -- sleep 1s
~~~~

However if one runs the following, `tmux` fails, most likely due to argument ending in `;` (colon):
~~~~
env -i TERM=linux tmux -L test -f /dev/null -- new-session -n 'hello ;' -- sleep 1s
~~~~

Adding a `-v` results in the following:
~~~~
1609615255.440516 client started (2110): version 3.1c, socket /run/tmux/10101/test, protocol 8
1609615255.440537 on Linux 5.9.14-1-default #1 SMP Sat Dec 12 06:57:32 UTC 2020 (c648a46); libevent 2.1.12-stable (poll)
1609615255.440563 socket is /run/tmux/10101/test
1609615255.440571 trying connect
1609615255.440583 connect failed: Connection refused
~~~~

To correctly make `tmux` run, one has to add an extra `\` before the colon, as in:
~~~~
env -i TERM=linux tmux -L test -f /dev/null -- new-session -n 'hello \;' -- sleep 1s
~~~~

----

BTW, I've stumbled upon this issue while trying to get `tmux new-session -- some-command arg1 ; arg2` running (i.e. creating a window whose command takes as argument a single `;`) as part of a wrapper script.

**Comment by nicm** [comment]
Yes, this is treated as a command separator.

**Comment by cipriancraciun** [comment]
@nicm I perfectly understand that `;` is a command separator;  however here we have `;` as a suffix of an argument, i.e. `hello ;`.

Thus by my reading of the manual, when one invokes `tmux` via `execve` (i.e. for example from `sh`) then each argument is treated individually, thus a non-empty string suffixed by `;` should work.  For example a string prefixed by `;`, like `; hello` works without an issue.

**Comment by nicm** [comment]
There is no way for tmux to tell the difference between `tmux ls; lsk` and `tmux 'ls;' lsk` so they are treated the same way.

**Comment by cipriancraciun** [comment]
> There is no way for tmux to tell the difference between tmux ls; lsk and tmux 'ls;' lsk so they are treated the same way.

Here I'm not speaking of a `sh` quoting issue.  I'm speaking of an actual `tmux` argument handling.

For example let's take my example above and run it through `strace`:
~~~~
env -i TERM=linux PATH="${PATH}" strace -f -e execve -- tmux -L test -f /dev/null -- new-session -n 'hello ;' -- sleep 1s
~~~~

The following is the actual syscall:
~~~~
execve("/usr/bin/tmux", ["tmux", "-L", "test", "-f", "/dev/null", "--", "new-session", "-n", "hello ;", "--", "sleep", "1s"], 0x7ffef422fbc8 /* 2 vars */) = 0
~~~~

I.e. `tmux` actually receives the argument `hello ;` as a single `char*` value.

**Comment by nicm** [comment]
Right and what is the difference between the two examples I gave?

**Comment by nicm** [comment]
A trailing colon is treated the same whether it is in quotes or not, there is no way for tmux to tell whether or not it was quoted after it receives it from the shell.

**Comment by cipriancraciun** [comment]
So should I understand that a command separator (when the commands are received as arguments via `main`) is also accepted at the end of an argument?  As in the following are equivalent from `tmux`'s point of view:
* `tmux -- 'one;' 'two'`
* `tmux -- one ';' two`

Because if this is the case then the manual is misleading in making one think that (when commands are received as arguments via `main`) the command separator must be an individual argument.  (Look at the examples where `tmux` is invoked with multiple commands.)

In this case perhaps a warning somewhere in the manual would be helpful.

**Comment by nicm** [comment]
Yeah that's right, although I recommend doing it as an individual argument.

The reason is that it is a bit annoying having to do separate `;` at the command prompt and it is meant to parse roughly the same way as the shell. In retrospect it would have been better just to require it to be a separate argument but it's done now and I'm not sure it is worth changing.

**Comment by cipriancraciun** [comment]
I understand now the "situation", and indeed this is not a bug.

However, please consider adding a warning in the manual about this behaviour (i.e. when the colon is at the end of a token, like in `some-argument;`), because even though I've carefully read the manual, and I'm no stranger to shell quoting, it kind of surprised me... :)

**Comment by nicm** [comment]
Do you want to suggest some text for the man page and where it should go?

**Comment by cipriancraciun** [comment]
Hmm... Strange, the manual doesn't explicitly state that when running from shell the `;` should be quoted.  (It just provides examples.)

Thus how about adding a paragraph after:
> Each command is terminated by a newline or a semicolon (;).  Commands separated by semicolons together form a ‘command sequence’ - if a command in the sequence encounters an error, no subsequent commands are executed.

The new paragraphs should state:
> It is strongly recommended that the semicolon (;) (when used as a command separator) should be written as an individual token (surrounded by whitespaces), like for example: `one ; two`.  However please note that a trailing semicolon would also be interpreted as a command separator, thus the following is equivalent with the previous example: `one; two`.
>
> If one wants to use a semicolon as an argument, it should be escaped with a backslash, like for example `one\;two`.
>
> When running `tmux` from the shell extra care must be taken to properly quote semicolons:
> * individual semicolons that should be interpreted as a command separator should be escaped accordingly to the shell conventions;  for example in case of `sh` wrapped in quotes or preceded by a backslash, like for example: `tmux command-one ';' command-two` or `tmux command-one \; command-two`;
> * individual semicolons, or trailing semicolons, that should be interpreted as arguments should be escaped twice: once according to shell conventions, and a second-time for the tmux parser by preceeding it with a backslash;  for example: `tmux command 'argument-one\;' argument-two` or `tmux command argument-one\\\; argument-two`;
> * semicolons that are not individual tokens or trailing another token, should only be escaped once according to shell conventions;  for example `tmux command argument-with-\;-semicolon` or `tmux command 'argument-with-;-semicolon`;)

----

BTW, given the following commands, as written in the configuration file, how would the semicolon be interpreted?
* (1) `one ; two` -- two commands `one` and `two`;
* (2) `one; two` -- two commands `one` and `two`;
* (3) `one\; two` -- one command with tokens `one;` and `two;`
* (4) `;one two` -- an empty command and then another one with tokens `one` and `two`;
* (5) `one;two` -- two commands `one` and `two`;

I ask because in this case the quoting when used inside the configuration file, and when called via shell, are quite different...  For example in case one calls `tmux -- {paste verbatim the tokens bellow}` the semicolon has a different meaning:
* (1) `one \; two` -- two commands `one` and `two`;
* (2) `one\; two` -- two commands `one` and `two`;
* (3) `one\\\; two` -- one command with tokens `one;` and `two;`
* (4) `\;one two` -- one command with tokens `;one` and `two`;  **DIFFERENT**
* (5) `one\;two` -- one command `one;two`;

**Comment by nicm** [comment]
OK your text is good, thanks. I have tweaked it a bit, mainly to trim it a little, to apply mdoc formatting and also to make the examples more concrete (although I wasn't always able to come up with realisitic arguments though!). Please take a look at this, particularly mdoc also requires ;s to be escaped so please check I have the right number of \s:
~~~~
     Each command is terminated by a newline or a semicolon (;).  Commands
     separated by semicolons together form a `command sequence' - if a command
     in the sequence encounters an error, no subsequent commands are executed.

     It is recommended that a semicolon used as a command separator should be
     written as an individual token, for example from sh(1) one of:

           $ tmux neww \; splitw
           $ tmux neww ';' splitw

     Or from the tmux command prompt:

           neww ; splitw

     However, a trailing semicolon is also interpreted as a command separator,
     such as both these sh(1) commands:

           $ tmux neww\; splitw
           $ tmux 'neww;' splitw

     As in these examples, when running tmux from the shell extra care must be
     taken to properly quote semicolons:

     1.      Semicolons that should be interpreted as a command separator
             should be escaped according to the shell conventions. For sh(1)
             this typically means quoted (such as `neww ';' splitw') or
             escaped (such as `neww \; splitw').

     2.      Individual semicolons or trailing semicolons that should be
             interpreted as arguments should be escaped twice: once according
             to the shell conventions and a second time for tmux; for example:

                   $ tmux neww 'foo\;' bar
                   $ tmux neww foo\\; bar

     3.      Semicolons that are not individual tokens or trailing another
             token should only be escaped once according to shell conventions;
             for example:

                   $ tmux neww 'foo-;-bar'
                   $ tmux neww foo-\;-bar

**Comment by nicm** [comment]
> (4) ;one two -- an empty command and then another one with tokens one and two;
> (5) one;two -- two commands one and two;

Yes, there are some differences. .tmux.conf is not a shell script, even though it tries to work vaguely the same way, it is just a best effort.

The idea is that if I type something at the tmux command prompt or in the config file it should look pretty similar to how I would type it at a normal Bourne-style shell prompt, I shouldn't have to use a completely different syntax. But there are differences especially around semicolons and quoting, it isn't strict and it isn't really practical to be.

**Comment by forbesmyester** [comment]
Here's my attempt, I'm not sure it's better and the formatting is off too. Maybe there's bits of both to take.

My core feeling is that:

 * It's confusing to discuss two kinds of escaping together, so I've tried to seperate them.
 * I think \n's are the same, and that they're no discussed much in the above (nor have I).

```
Each command is terminated by a newline or a semicolon (;).

Commands separated by semicolons (and maybe \n's) together form a `command
sequence' - if a command in the sequence encounters an error, no subsequent
commands are executed.

It is recommended that a semicolon used as a command separator should be
written as an individual token, for example, from the tmux command prompt:

      neww foo ; splitw

Or from sh(1) one of:

      $ tmux neww foo ';' splitw
      $ tmux neww foo \; splitw

NOTE: From your shell, you will still need to follow it's escaping conventions.
That is to say, in sh(1), if you want a semicolon to be passed through to
tmux you will need to quote it (';'), or escape it (\\;) as above.

However, a trailing semicolon is also interpreted as a command separator:

      $ tmux 'neww foo;' splitw

As in these examples, when running tmux from the shell extra care must be
taken to properly quote semicolons:

 1. Semicolons that should be interpreted as a command separator
    should not be escaped:

        $ tmux neww 'foo;' splitw

 2. Individual semicolons or trailing semicolons that should be literal semicolons must be escaped 

        $ tmux 'neww foo\;'
```

**Comment by nicm** [comment]
I'll take a better look later but note that man pages must be written in the third person.

**Comment by forbesmyester** [comment]
It's sure a tough problem.

I'm happy to help, if I can, though clearly I'm not as familiar with the technical details but in some ways that may help.

Do you think we should re-open this and close my issue?

**Comment by nicm** [comment]
I will look at it later, thanks.

**Comment by nicm** [comment]
I have applied my text with some minor tweaks, if it is still confusing we can tweak it later. Thanks!
