### ISSUE TITLE
[feature request]  Add a `check-server` companion to `start-server` that verifies that the server is actually working

### ISSUE THREAD

**Issue by cipriancraciun** [tmux/tmux#2523]
It would be lovely to have a command like `check-server` that would verify that a `tmux` server is already executing at the given socket, and fail otherwise (i.e. exit with 1).

This is extremely helpful when one explicitly starts a `tmux` server with `start-server` and uses `set -g exit-empty off` as part of a supervisor process (like `tmux`).  In this case when one issues `new-session` we must be sure that the session is created under an already running server that was started by that supervisor.

Checking if the socket already exists is not an option as it seems that when `tmux` exits it fails to remove the socket file.

----

Alternatively (or in addition to this `check-server` command), it would be helpful to have an argument to `new-session` that does this check, because all the other "session level" commands already fail if there is no server running.

**Comment by nicm** [comment]
If `new-session` would work, why not `has-session`?

**Comment by cipriancraciun** [comment]
`has-session` doesn't work because it fails if there is no actual session but there is an already started server.  For example:
~~~~
tmux -L test -- has-session
no server running on /run/tmux/10101/test
# exit code 1

tmux -L test start-server ';' set -g exit-empty off

tmux -L test -- has-session
no current target
# exit code 1
~~~~

Thus one can't identify (without parsing the output of `has-session`) if there is no server running or there is no session.

**Comment by nicm** [comment]
Well then a flag to `new-session` wouldn't work either.

**Comment by cipriancraciun** [comment]
> Well then a flag to new-session wouldn't work either.

(But an additional `check-server` or similar individual command would?)

Why wouldn't a flag for `new-session` work?  (For example if the session (with the given name) already exists, and one hasn't mentioned `-a` then it fails;  thus the new extra flag would behave is a similar way but check if the server is already running.)

**Comment by nicm** [comment]
Hmm this is not necessarily an easy one because most of the code here is shared by multiple commands and we don't want to change them all (`has-session` and `start-server` are the obvious commands to do this and they both do basically nothing and rely on behaviour that happens anyway).

**Comment by nicm** [comment]
Can't you just run a non-starting command like `lscm` and if it succeeds then the server is running?

**Comment by cipriancraciun** [comment]
OK, then forget the extra flag for `new-session`.  How about the `check-server` individual command?

(For example as an additional use-case it could be used as a "heartbeat" to make sure that the `tmux` server is already using.)

----

About the running of a non-starting command, I've though of that however, I've failed to find a command that wouldn't output something totally surprising.

For example `list-commands` would output the commands and make the user of the wrapper script think something is broken.

I've thought of using `display-message "starting whatever"` which does not have an surprising output, however that fails if there is no session running (but a server is indeed running).

**Comment by nicm** [comment]
No we are not adding a new command for this, if we made a change then best would be a flag to `start-server`. But I do not see any convenience to this over something like `tmux lscm >/dev/null 2>&1`.

**Comment by cipriancraciun** [comment]
A flag to `start-server` that should check if it is already started would do.

----

> But I do not see any convenience to this over something like tmux lscm >/dev/null 2>&1.

I'll give you my use-case:  I'm writing a wrapper script for `tmux` that implements something similar to `dtach`, for example `dtach-w exec some-long-running-command`.  This wrapper script uses a `tmux -f ~/.dtach.conf -- start-server` (whose config makes sure it stays when there are no sessions) which is run as a `systemd` service, thus not part of the desktop environment.

So my wrapper script ends up calling `tmux -S {some-socket} -- new-session -s {token} -A -- some-long-running-command`.  Thus if I were to add an `list-commands` before the `new-session` I would see a list of commands before in my shell.

Of course I could run two commands as in `tmux -S {some-socket} -- list-commands` and `tmux -S {some-socket -- new-session`, but that would introduce a race condition between the time `list-commands` runs and `new-session` runs.

**Comment by nicm** [comment]
How about `refresh-client` instead? You will still get the `no server running` message but there is no way to avoid that.

**Comment by cipriancraciun** [comment]
> How about `refresh-client` instead? You will still get the `no server running` message but there is no way to avoid that.

Unfortunately it fails when the server is running but there are no clients:
~~~~
tmux -L test -- refresh-client
no server running on /run/tmux/10101/test

tmux -L test -- start-server ';' set -g exit-empty off

tmux -L test -- refresh-client
no current client
# exit code 1
~~~~

Thus, as in the case of `display-message` one can't discern if the command fails due to lacking a running server, or lacking an attached client.

**Comment by nicm** [comment]
What about something like `tmux show -qg @abcdef` where `@abcdef` doesn't exist?

Or `tmux if -F '0' ''`?

**Comment by cipriancraciun** [comment]
> What about something like `tmux show -qg @abcdef` where `@abcdef` doesn't exist?
> 
> Or `tmux if -F '0' ''`?

Well it kind-of doesn't work:
~~~~
tmux -L test-does-not-exist -- if -F '0' ''
no server running on /run/tmux/10101/test1
# exit code 1

tmux -L test-does-not-exist -- if -F '0' '' ';' new-session true
# starts a new session
# nothing is written after `tmux` exits
~~~~

This is really strange...  Shouldn't the `if` in the second case fail just like in the first one?  Because the `new-session` is to be executed only afterwards...  Instead it behaves like `new-session` triggers the creation of a new server before the `if` is executed...

**Comment by nicm** [comment]
Oh yeah, any command which starts the server in the command sequence will start the server. The client has to work it out and it can only look at the flags, it can't run the commands.

**Comment by nicm** [comment]
The only way to do this I think would be to add a flag to `tmux` itself to prevent the start server flag taking effect, so you would do:
~~~~
tmux -N new ...
~~~~
And it would act as if `new-session` does not have the start server flag set and fail with `no server running` if there was no server. You could then similarly use `start-server` to test if the server was running without doing anything if it was (since it is a no-op with a server running already).

**Comment by cipriancraciun** [comment]
> Oh yeah, any command which starts the server in the command sequence will start the server. The client has to work it out and it can only look at the flags, it can't run the commands.

OK, now it all makes sense...

So then my proposed `check-server` would actually be meaningless when used with `new-session` like in `tmux -- check-server ';' new-session`.

Then how about adding a flag to the `tmux` client itself which disables the creation of the server regardless of what commands are given.

For example `tmux -Z -- new-session` (where `-Z` is the "magic" flag) would fail to start a session if the server is not actually running.

----

BTW, running `start-server` while there is another server running does not fail.

**Comment by nicm** [comment]
Yes I think that is the only choice. It would be nice if new-session and friends didn't start the server until they actually run, but there is no practical way to do this or at least none that is worth the cost.

**Comment by nicm** [comment]
Why don't you just start up the server in your script though? Starting the server when it is already running is a no-op.

**Comment by cipriancraciun** [comment]
> Why don't you just start up the server in your script though? Starting the server when it is already running is a no-op.

I want to be able to run the `tmux` server in a different context (as in Linux `cgroup` / namespaces) than the desktop environment or `ssh`.  Therefore I must be sure that the server has been properly started.

**Comment by nicm** [comment]
Try this please which adds `-N`: [tmux-N.diff.txt](https://github.com/tmux/tmux/files/5763819/tmux-N.diff.txt)

**Comment by cipriancraciun** [comment]
@nicm Will the patch land in GitHub at a later time?  Thanks!

**Comment by nicm** [comment]
Does it work for you?

**Comment by cipriancraciun** [comment]
> Does it work for you?

Sorry, I should at least bother to check!  :)

Yes it works as expected.  Thanks!

----

So I've applied the patch on-top of the latest commit on GitHub, and tried the following:
~~~~
> ./tmux -N -L test -- new-session
no server running on /tmp/tmux-10101/test
# exit code 1, as expected

> ./tmux -N -L test -- has-session
no server running on /tmp/tmux-10101/test
# exit code 1, as expected

> ./tmux -D -L test

> ./tmux -N -L test -- has-session
no current target
# exit code 1, as expected

> ./tmux -N -L test -- new-session
# starts a new session
# detach

> ./tmux -N -L test -- has-session
# exit code 0, as expected
~~~~

BTW, thanks also for the `-D` flag.  (That would have been another feature request.)

**Comment by nicm** [comment]
OK great I'll apply it next week. Thanks!

**Comment by nicm** [comment]
This is in now, thanks!
