### ISSUE TITLE
Why we can not you "." in session title?

### ISSUE THREAD

**Issue by Haetsal-Lee** [tmux/tmux#2524]
I want to know the reason.

**Comment by nicm** [comment]
: and . are special in targets.

**Comment by Haetsal-Lee** [comment]
> : and . are special in targets.

Could you elaborate some example usage of special characters (: and .) ?

**Comment by krader1961** [comment]
@Haetsal-Lee, A colon separates the session name from the window name. A period separates the pane number. See the discussion of `target-window` and `target-pane` in the man page at the start of the "COMMANDS" section of the man page. For example (from the tmux man page): `mysession:mywindow` and `mysession:mywindow.1`.

On the other hand I don't really understand your initial question. Why do you mean by

> Why we can not you (use) "." in session title?

Can you provide an example of what you are trying to do?

**Comment by Haetsal-Lee** [comment]
> @Haetsal-Lee, A colon separates the session name from the window name. A period separates the pane number. See the discussion of `target-window` and `target-pane` in the man page at the start of the "COMMANDS" section of the man page. For example (from the tmux man page): `mysession:mywindow` and `mysession:mywindow.1`.
> 
> On the other hand I don't really understand your initial question. What do you mean by
> 
> > Why we can not you (use) "." in session title?
> 
> Can you provide an example of what you are trying to do?

It seems that I have misunderstood the session title.
I have used a "session title" to descript a session. (like "GCN lr=0.1, mult=0.5". so that I can quickly read what current session is about.)
But, now I understand, session titles are used as ID.
