### ISSUE TITLE
when i do tmux,then i ssh remote server,how can i ctrl +b +% copy ssh conn

### ISSUE THREAD

**Issue by lavendder** [tmux/tmux#2526]
### Issue description
1、tmux
2、ssh XXX
3、ctrl +b +%

how can i copy ssh conn and keep conn?

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:
* tmux version (`tmux -V`). tmux verson 3.1
* Platform (`uname -sp`).mac
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
If you are running tmux on host A and you ssh into host B inside, you can't have that ssh in two panes.

You can either:

- Run tmux on host B, then you can split windows with shells on that host.

- ssh into host B again from the new pane on host A (if you use ControlMaster in ssh it will only use one connection).

**Comment by lavendder** [comment]
ok！！ thanks for you reply！！
