### ISSUE TITLE
Style directives sometimes leak through

### ISSUE THREAD

**Issue by mathstuf** [tmux/tmux#2527]
### Issue description

Running tmux commit 5a2db4c7e8ba94fadb31075e6813cf53b87b5366 (Jan 2021)

`0.0:—firefox 1.0#[default]:—ssh 2.1#[default]:—rsync 3.0-:erythro—bash (4.0*:—mutt)`

When a flag is set, the `#[default]` directive "leaks" and is rendered rather than changing the style. I believe I had previously been running c80fc6bf9e44baaad1e6f4a4c83ec47823e96c1b (May 2020).

I have not yet bisected, but can try doing that (once I have a better stopping point to do so).

My status settings are:

```tmux
# Configuration of the current window
set-window-option -g window-status-current-format "#[fg=colour196,bold](#[fg=colour71]#I#[default].#[fg=colour71]#P#[fg=colour118,bold]#F#[default]:#[fg=colour220]#T#[default]—#[fg=colour220]#W#[fg=colour196,bold])#[default]"
set-window-option -g window-status-format "#[fg=colour71]#I#[default].#[fg=colour71]#P#[fg=colour118,bold]#F#[default]:#[fg=colour100]#T#[default]—#[fg=colour100]#W#[default]"
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `tmux next-3.3`
* Platform (`uname -sp`). `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`). outside: `rxvt-unicode-256color` inside: `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`). Can get if required.

**Comment by nicm** [comment]
I fixed something similar to this recently, must be something else, I'll take a look later in the week.

**Comment by nicm** [comment]
This is because one of the flags is `#` which confuses things. You need to replace `#F` with `#{q/e:window_flags}` which will escape it appropriately (see 9a74bba007a60b93d1fdf68772e5cfb61b3558ff).

**Comment by mathstuf** [comment]
Thanks, that seems to work. Is it worth a mention in the release notes (even if retroactive?) Should the `#F`/`#{window_flags}` expansion have a warning attached?

**Comment by nicm** [comment]
It isn't in any release yet.

**Comment by nicm** [comment]
I am wondering if we can make it always return # as ##, there are probably more people using it like you are in status formats than using it for something else that doesn't need escaping.

**Comment by nicm** [comment]
I took another look at this and I will make this change: [tmux-window-flags2.diff.txt](https://github.com/tmux/tmux/files/5834834/tmux-window-flags2.diff.txt)

- Change `window_flags` to automatically escape `#` as `##`.
- Add a format `window_raw_flags` (not wild about the name) which is the old version without escaping.
- Leave `q/e` but add `q/h` as an alias (`h` for hash) which makes a bit more sense (only document `q/h`).
- Change some of the flag and function names and whatnot in format.c to make more sense.

So you (and the other person who reported this, I will dig out the issue after I apply this) will need to change back to plain `#F` or `#{window_flags}` but the majority of people who currently use `window_flags` in the status line will not need to change anything - only people who use it in formats given to `list-keys` or similar which should be many fewer.

**Comment by nicm** [comment]
I have applied this now, so when you update you will need to go back to #{window_flags}.
