### ISSUE TITLE
Double escaping of quotation marks in command-prompt template

### ISSUE THREAD

**Issue by IngoMeyer441** [tmux/tmux#2528]
* tmux version (`tmux -V`): 3.1.c
* Platform (`uname -sp`): Manjaro Linux
* $TERM inside and outside of tmux (`echo $TERM`):`tmux-256color`,  `xterm-kitty`

---

Currently, I develop an [easy-motion plugin for tmux](https://github.com/IngoMeyer441/tmux-easy-motion). For this I need to query an arbitrary key and pass this key to a `run-shell` command:

```bash
tmux bind-key -T easy-motion "f" command-prompt -1 -p "character:" "run-shell -b \"${SCRIPTS_DIR}/easy_motion.sh \\\"f\\\" \\\"%%%\\\"\""
```

This works well for all keys except `"` because it must be double escaped to be passed correctly to the shell script. An alternative form is:

```bash
tmux bind-key -T easy-motion "f" command-prompt -1 -p "character:" "run-shell -b '${SCRIPTS_DIR}/easy_motion.sh \"f\" \"%%%\"'"
```

which works for `"` but not for `'`. I don't know how to solve this problem for all possible keys. Is there a form of double escaping for quotation marks?

**Comment by nicm** [comment]
It is a bit of a mess but this works for me:
~~~~
bind -n "f" command-prompt -1 -p "character:" {
    set -g @tmp "%%%'"
    run-shell 'sh my-script "#{q:@tmp}"'
}
~~~~
But you will need to undo the escaping and/or trim off the trailing `'` yourself in your script.

I discussed recently with someone that perhaps `command-prompt` could expanded format and put the key in a variable, then you could probably just use `#{q:key}` instead of `%%%`. But it isn't supported at the moment.

**Comment by IngoMeyer441** [comment]
Thanks for your fast response! Maybe I am just stupid, but the brace form does not work for me from the command line:
```bash
tmux bind-key "f" command-prompt -1 -p "character:" \{ run-shell "sh script.sh \"%%%\"" \}
```
gives
```
usage: command-prompt [-1kiN] [-I inputs] [-p prompts] [-t target-client] [template]
```
Does the brace form only work in tmux configuration files?

**Comment by nicm** [comment]
It works from the command line but it will need to be parsed as one argument which will be a pain to quote, it would be easier to do something like:
~~~~
cat <<EOF|tmux source -
bind f command-prompt ... {
...
}
EOF
~~~~

**Comment by IngoMeyer441** [comment]
Thank you very much, now I have a working solution! :+1: 
For anyone who is interested, this works for me (in bash):
```bash
# `tmux source` allows to use the { } form for commands
# Set a temporary variable to avoid escaping issues of quotes
# See https://github.com/tmux/tmux/issues/2528 for details
tmux source - <<-EOF
    bind-key -T easy-motion "f" command-prompt -1 -p "character:" {
        set -g @tmp-easy-motion-argument "%%%"
        run-shell -b '${SCRIPTS_DIR}/easy_motion.sh "f" "#{q:@tmp-easy-motion-argument}"'
    }
EOF
```
Then in `easy_motion.sh`, single quotes are received escaped, so I strip leading back slashes and additionally escape double quotes for later use:
```bash
# First undo escaping of any character
if [[ "${motion_argument:0:1}" == "\\" ]]; then
    motion_argument="${motion_argument:1}"
fi
# Then, escape double quotes, since they need to be escaped when passed to `pane_exec`
if [[ "${motion_argument}" == "\"" ]]; then
    motion_argument="\\\""
fi
```
