### ISSUE TITLE
Configure fails with libev

### ISSUE THREAD

**Issue by orbea** [tmux/tmux#253]
With libev-4.22  tmux fails to get past configure.
```
checking for LIBEVENT... no
checking for library containing event_init... no
configure: error: "libevent not found"
make: *** No targets specified and no makefile found.  Stop.
make: *** No targets specified and no makefile found.  Stop.
```
Additionally since libevent was removed this library is missing.
```
/usr/bin/tmux:
	libevent-2.0.so.5 => not found
```
Is there any way to compile tmux with libev instead of libevent?  Thanks!
http://software.schmorp.de/pkg/libev.html

**Comment by nicm** [comment]
No libev is not supported.
