### ISSUE TITLE
Maximizing Window , Restoring window .... causing text cloning 

### ISSUE THREAD

**Issue by vaibhav135** [tmux/tmux#2530]
Hii, 
I've recently started using tmux I don't know if this is a bug but maximizing, restoring the window, and also view split on left/right is causing text cloning (I don't know how to explain it so I am calling it text cloning).

OS: Ubuntu 20.04 Lts
tmux version: 3.1b 

my shortcut keys for:
Maximizing window: super + UP arrow key
Restore window: super + DOWN arrow key
view split on left: super + LEFT arrow key
view split on right: super + RIGHT arrow key

So here is what happening before and after using the above shortcut keys

**Before**

![Screenshot from 2021-01-10 09-15-24](https://user-images.githubusercontent.com/39329182/104113923-947bc700-5324-11eb-9e8f-689a02d49316.png)

**After**
![Screenshot from 2021-01-10 09-18-17](https://user-images.githubusercontent.com/39329182/104113952-cc830a00-5324-11eb-9e0a-a7dd1c59a16b.png)

I would like to mention this issue but I didn't understand much so you can take a look:
Pane resizing breaks bash, zsh, csh prompts. #516

Here's my .tmux.conf
['.tmux.conf.txt'](https://github.com/tmux/tmux/files/5792196/tmux.conf.txt)

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by vaibhav135** [comment]
@nicm Yes sir. I mean at least happening to me. Could you reproduce it on your system.

**Comment by vaibhav135** [comment]
Btw, please if you have any solution can you give it to me

**Comment by nicm** [comment]
Show me tmux server log from reproducing with master please.

**Comment by vaibhav135** [comment]
[tmux-client-13965.log](https://github.com/tmux/tmux/files/5795320/tmux-client-13965.log)

 @nicm is this a log...????

**Comment by nicm** [comment]
Yes but I need the server log, you need to kill tmux and restart it with `-vv` then reproduce the problem.

**Comment by vaibhav135** [comment]
[Uploading tmux-server-77844.log…]()

**Comment by vaibhav135** [comment]
[tmux-server-77594.log](https://github.com/tmux/tmux/files/5795361/tmux-server-77594.log)

**Comment by nicm** [comment]
This log is from 3.1b, not from master?

**Comment by vaibhav135** [comment]
[tmux-server-95728.log](https://github.com/tmux/tmux/files/5797506/tmux-server-95728.log)
Sorry for before, I've installed the new one from the repo now.
tmux -V  => tmux next-3.3

**Comment by vaibhav135** [comment]
Hello @nicm did you find the issue

**Comment by vaibhav135** [comment]
> [tmux-server-95728.log](https://github.com/tmux/tmux/files/5797506/tmux-server-95728.log)
> Sorry for before, I've installed the new one from the repo now.
> tmux -V => tmux next-3.3

hii @nicm did you check the log now this one is from master branch I think

**Comment by nicm** [comment]
Thanks, I'll have a look when I get time.

**Comment by nicm** [comment]
Can you show me what in your `PS1`? Do `echo $PS1`.

**Comment by vaibhav135** [comment]
yes this is the result of echo $PS1:

 \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$

**Comment by nicm** [comment]
For me it is fine if I remove the debian_chroot bit, does that help you:
~~~~
export PS1='\[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

**Comment by vaibhav135** [comment]
hmmm do I have to paste this in .bashrc

**Comment by nicm** [comment]
Yes you can try that.

**Comment by vaibhav135** [comment]
Naah it's not working

**Comment by altjx** [comment]
Also facing some very similar issues.

**Comment by nicm** [comment]
Show me `echo PS1` now please. What shell are you using? Bash? What version?

**Comment by carlocab** [comment]
zsh has known issues with terminal window resizing: https://github.com/romkatv/powerlevel10k/issues/175

Perhaps a similar issue affects bash?

**Comment by vaibhav135** [comment]
@carlocab yes, but the issue you have referenced is I guess related to the power level theme. Well but you are right about the similar effect, do you have any idea how to do a workaround this problem

**Comment by Alucherdi** [comment]
Same problem, really annoying when using nvim

Did a video showing the problem: https://streamable.com/4diav6

(zsh)
PS1: %(?:%{%} :%{%} ) %{$fg[cyan]%}%~%{$reset_color%} $(git_prompt_info)

Persists after removing theme configuration

echo $TERM (inside tmux)
screen-256color

**Comment by Alucherdi** [comment]
Is there any solution or workaround for this?

**Comment by carlocab** [comment]
> yes, but the issue you have referenced is I guess related to the power level theme. Well but you are right about the similar effect, do you have any idea how to do a workaround this problem

@vaibhav135 No, it's not related to the theme. It's a problem in zsh, as explained in the issue I linked above. The workaround for zsh is to patch the bug out of Zsh. If bash has the same problem, then it probably needs to be patched as well.

**Comment by nicm** [comment]
Is this still a problem or is it clearly a shell bug?
