### ISSUE TITLE
Use Circled digit for window title

### ISSUE THREAD

**Issue by eladeyal-intel** [tmux/tmux#2532]
Unicode has code points such as "Circled digit one", "Circled digit two" etc. :  ① ②  [link](http://shapecatcher.com/unicode/info/9313) and also reversed characters Unicode Character “❺” (U+277A) [link](https://www.compart.com/en/unicode/U+277A) etc

[Nerd fonts](https://www.nerdfonts.com/cheat-sheet) have additional characters such as `nf-mdi-numeric_6_box` and `nf-mdi-numeric_6_box_outline`

![image](https://user-images.githubusercontent.com/20379005/104128564-f4985a80-5370-11eb-8d6a-90639c5610d6.png)

I was wondering if it's possible to use these for encoding `#I` - I was not able to find a way to do it.

**Comment by nicm** [comment]
You can do something like `#{?#{==:#{window_index},1},①,#{?{==:#{window_index},2,②,...}` or write a script and run it with eg `#(sh my-script.sh #{window_index})`.

**Comment by eladeyal-intel** [comment]
Ah cool. I wrote this (for working with a nerd font)

```
DIGITS=(         )                                                                          2 echo ${DIGITS[$1]}    
``` 

And used in the format string `#(bash $HOME/bin/.fmtnum.sh #I)`

It does show "is not ready" momentarily when I create a new window - Is there a way to hide it?

**Comment by nicm** [comment]
No, you can't get rid of the not ready but it should disappear as soon as the script is finishes running for the first time.

**Comment by eladeyal-intel** [comment]
Yes it disappears quickly. Future readers of this issue might wonder why not using `tr`. Apparently it does not support multi byte characters so we'll.
