### ISSUE TITLE
show "-bash-4.2$" when start tmux

### ISSUE THREAD

**Issue by zyoohv** [tmux/tmux#2533]
### Issue description

when I start tmux, the cmd shows:

```
-bash-4.2$
```

but I want to get:

```
username@systemname: $workdir >
```

![image](https://user-images.githubusercontent.com/16134679/104268240-6508be00-54ce-11eb-9887-88de5eeeff04.png)

### Required information

Please provide the following information:

* tmux version (tmux 3.1).
* Platform (`Linux x86_64`).
* $TERM inside and outside of tmux (`xterm-256color`).

**Comment by krader1961** [comment]
What does this have to do with tmux? It seems like you are asking how to configure bash to produce your desired prompt. Does running `bash` in a terminal without the involvement of tmux produce the output you expect?
