### ISSUE TITLE
Tmux doesn't display properly over Amazon Web Services (AWS) Systems Manager (SSM)

### ISSUE THREAD

**Issue by altjx** [tmux/tmux#2535]
Over the last two months, one issue I've been seeing pretty repetitively is that tmux doesn't seem to work too well if my connection to the system is over AWS SSM rather than SSH.

For example, when splitting panes, panes bleed over into each other, etc. It's quite interesting. It doesn't matter which host I connect from, or which SSM agent I connect to, the issue is pretty persistent.

Here's what a normal vertically split Tmux window looks like over SSH:

![Screen Shot 2021-01-16 at 3 59 40 PM](https://user-images.githubusercontent.com/4023423/104822882-d8366b00-5813-11eb-9ea5-ef168bf1a71c.png)

However, here's what it looks like from an AWS SSM session:

![Screen Shot 2021-01-16 at 3 59 55 PM](https://user-images.githubusercontent.com/4023423/104822886-e1bfd300-5813-11eb-880b-596c825a282c.png)

In these two examples, I'm using the `htop` command, but this issue persists with any command that has a lot of content returned from it. Here's another example of me running `vim` on the right hand side. On the left hand side, I cleared the window with "cmd + L", but as you can see, the text didn't clear properly.

![Screen Shot 2021-01-16 at 4 01 22 PM](https://user-images.githubusercontent.com/4023423/104822919-159af880-5814-11eb-99a7-f33f09ff24c1.png)

Here's what it looks like over SSH:

![Screen Shot 2021-01-16 at 4 01 55 PM](https://user-images.githubusercontent.com/4023423/104822928-29465f00-5814-11eb-90a0-388852766a5b.png)

I spent quite awhile trying to narrow this down and thought it may have had something to do with Powerline, but I guess it's possibly something related to the tmux session?

Any help would be greatly appreciated. I'm running Tmux version 2.9a and all of the clients I use this on are running Ubuntu and Kali Linux.

I tried attaching to the session with `tmux -vvv a -t [session]` but the log files don't really point to anything that indicates something is wrong:

```
# cat tmux-client-184121.log
1610831383.141354 client started (184121): version 2.9a, socket /tmp/tmux-0/default, protocol 8
1610831383.141416 on Linux 5.3.0-kali2-amd64 #1 SMP Debian 5.3.9-3kali1 (2019-11-20); libevent 2.1.11-stable (poll)
1610831383.141466 socket is /tmp/tmux-0/default
1610831383.141492 trying connect
1610831383.141649 add peer 0x5587ba76f7d0: 6 ((nil))
1610831383.141779 sending message 100 to peer 0x5587ba76f7d0 (4 bytes)
1610831383.141798 sending message 101 to peer 0x5587ba76f7d0 (15 bytes)
1610831383.141810 sending message 102 to peer 0x5587ba76f7d0 (11 bytes)
1610831383.141821 sending message 108 to peer 0x5587ba76f7d0 (16 bytes)
1610831383.141835 sending message 104 to peer 0x5587ba76f7d0 (0 bytes)
1610831383.141848 sending message 107 to peer 0x5587ba76f7d0 (4 bytes)
1610831383.141859 sending message 105 to peer 0x5587ba76f7d0 (16 bytes)
1610831383.141870 sending message 105 to peer 0x5587ba76f7d0 (14 bytes)
1610831383.141882 sending message 105 to peer 0x5587ba76f7d0 (25 bytes)
1610831383.141894 sending message 105 to peer 0x5587ba76f7d0 (19 bytes)
1610831383.141905 sending message 105 to peer 0x5587ba76f7d0 (20 bytes)
1610831383.141916 sending message 105 to peer 0x5587ba76f7d0 (13 bytes)
1610831383.141926 sending message 105 to peer 0x5587ba76f7d0 (21 bytes)
1610831383.141937 sending message 105 to peer 0x5587ba76f7d0 (11 bytes)
1610831383.141948 sending message 105 to peer 0x5587ba76f7d0 (17 bytes)
1610831383.141966 sending message 105 to peer 0x5587ba76f7d0 (1519 bytes)
1610831383.141990 sending message 105 to peer 0x5587ba76f7d0 (23 bytes)
1610831383.142002 sending message 105 to peer 0x5587ba76f7d0 (20 bytes)
1610831383.142014 sending message 105 to peer 0x5587ba76f7d0 (10 bytes)
1610831383.142025 sending message 105 to peer 0x5587ba76f7d0 (8 bytes)
1610831383.142037 sending message 105 to peer 0x5587ba76f7d0 (19 bytes)
1610831383.142048 sending message 105 to peer 0x5587ba76f7d0 (28 bytes)
1610831383.142059 sending message 105 to peer 0x5587ba76f7d0 (66 bytes)
1610831383.142070 sending message 105 to peer 0x5587ba76f7d0 (14 bytes)
1610831383.142081 sending message 105 to peer 0x5587ba76f7d0 (51 bytes)
1610831383.142092 sending message 105 to peer 0x5587ba76f7d0 (20 bytes)
1610831383.142103 sending message 105 to peer 0x5587ba76f7d0 (16 bytes)
1610831383.142114 sending message 105 to peer 0x5587ba76f7d0 (13 bytes)
1610831383.142126 sending message 106 to peer 0x5587ba76f7d0 (0 bytes)
1610831383.142138 cmd_pack_argv: argv[0]=a
1610831383.142148 cmd_pack_argv: argv[1]=-t
1610831383.142158 cmd_pack_argv: argv[2]=alton
1610831383.142169 sending message 200 to peer 0x5587ba76f7d0 (15 bytes)
1610831383.142180 client loop enter
1610831383.143056 peer 0x5587ba76f7d0 message 207
1610831383.143078 sending message 208 to peer 0x5587ba76f7d0 (0 bytes)
1610831386.615836 peer 0x5587ba76f7d0 message 201
1610831386.615863 sending message 205 to peer 0x5587ba76f7d0 (0 bytes)
1610831386.616188 peer 0x5587ba76f7d0 message 204
1610831386.616206 client loop exit
```

How do I troubleshoot what could possibly be causing this?

**Comment by nicm** [comment]
What is SSM? Is it a terminal or do you run it inside a terminal like ssh? Most likely either it's terminal implementation is buggy or you are using wrong TERM outside tmux. Did you try some very simple TERM settings outside tmux like ansi or vt220?

**Comment by altjx** [comment]
SSM is Amazon's "ssh-like" tool that can be used as substitute. Once you connect over SSM, you're at a prompt just like you would be from SSH. 

I have tried setting the `TERM` env variable to `screen` just like it's set in the SSH session's environment variable, but no luck there. The original value was `xterm-256color`

**Comment by nicm** [comment]
Try `ansi` or `vt220` and see if they work. Make sure you set it outside tmux.

**Comment by altjx** [comment]
Perfect!! Thanks a lot. Setting it to `ansi`. When I tried `vt220`, the same issue persisted along with no colors.

Just looks like I need to hardcode this to `ansi` going forward. Much appreciated!!

**Comment by nicm** [comment]
If ansi works and vt220 does not then I would guess it is either missing support for scroll regions (`csr`) or it needs no `xenl` flag. You could figure out which by removing them with `terminal-overrides` but if ansi works then probably no point. ansi is very simple so you will find function keys and whatnot won't work.

**Comment by altjx** [comment]
Gotcha. Thanks so much @nicm

**Comment by altjx** [comment]
Hey @nicm, if you don't mind me asking, any idea why using the same TERM value from within an SSH instance vs another instance would have any different effect on something like Tmux? Seems that I was able to get this resolved on the VM itself, but not within the docker container. Not necessarily the best place here for that, but just wanted to get any thoughts if you had any related to this.

**Comment by nicm** [comment]
TERM has to match the capabilities of the terminal each program is talking to.

ssh (except Windows SSH) just passes through data unchanged so TERM should match the actual terminal you running ssh in.

If you are using a program that modifies the data between tmux and the actual terminal, then you may need a different TERM. This is apparently the case with Amazon SSM.

Or you will need a different TERM for different terminals.

Is Docker a terminal or does it run in your normal terminal? If it is a terminal it will probably either have its own terminfo entry or emulate one of the common ones like xterm or maybe linux. If it is using the existing terminal and doesn't work with your normal TERM for that terminal then you may need to experiment with less capable TERM values like ansi.

**Comment by altjx** [comment]
Perfect. Thanks so much for this explanation. Very helpful!!
