### ISSUE TITLE
tmux loses output when changing window size

### ISSUE THREAD

**Issue by gregrwm** [tmux/tmux#2536]
### Issue description
Describe the problem and the steps to reproduce.

Launch xterm 353-1ubuntu1
inside it launch tmux-3.1b-x86_64.AppImage -vv new
Stretch the xterm to 57x226 (or probably almost any generous size).
Output 100 lines:  for a in {0..99};do echo $a;done
Start less:  echo foo|less
Shrink the xterm to 15x59 (or probably almost any modest size).
Exit less:  q
tmux will have just eaten output lines 59-99.

By contrast screen 4.8.0-1 behaves similarly tho slightly better, tossing the new current position amidst the prior output.  indeed it's preferable to be tossed into the midst of recent output rather than to lose it outright.

Meanwhile xterm 353-1ubuntu1 by itself (with neither tmux nor screen intervening) goes through the above sequence with all output lines remaining intact, none are lost, and the current position returns properly to the bottom.

### Required information
TERM outside tmux:  xterm
TERM inside tmux:  screen

  $  uname -sp && tmu -V
Linux x86_64
tmux 3.1b
  0$  cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
  0$  head -9999v tmux-c*
==> tmux-client-12236.log <==
1610825603.780387 client started (12236): version 3.1b, socket /tmp/tmux-444/default, protocol 8
1610825603.780412 on Linux 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021; libevent 2.0.21-stable (poll)
1610825603.780434 socket is /tmp/tmux-444/default
1610825603.780441 trying connect
1610825603.780457 connect failed: Connection refused
1610825603.780465 lock file is /tmp/tmux-444/default.lock
1610825603.780488 flock succeeded
1610825603.780491 got lock (7)
1610825603.780496 trying connect
1610825603.780501 connect failed: Connection refused
1610825603.780693 add peer 0x133a2c0: 8 ((nil))
1610825603.780793 sending message 100 to peer 0x133a2c0 (4 bytes)
1610825603.780812 sending message 101 to peer 0x133a2c0 (6 bytes)
1610825603.780821 sending message 102 to peer 0x133a2c0 (11 bytes)
1610825603.780827 sending message 108 to peer 0x133a2c0 (11 bytes)
1610825603.780834 sending message 104 to peer 0x133a2c0 (0 bytes)
1610825603.780839 sending message 107 to peer 0x133a2c0 (4 bytes)
1610825603.780844 sending message 105 to peer 0x133a2c0 (16 bytes)
1610825603.780849 sending message 105 to peer 0x133a2c0 (17 bytes)
1610825603.780854 sending message 105 to peer 0x133a2c0 (25 bytes)
1610825603.780858 sending message 105 to peer 0x133a2c0 (25 bytes)
1610825603.780864 sending message 105 to peer 0x133a2c0 (48 bytes)
1610825603.780869 sending message 105 to peer 0x133a2c0 (20 bytes)
1610825603.780899 sending message 105 to peer 0x133a2c0 (22 bytes)
1610825603.780904 sending message 105 to peer 0x133a2c0 (10 bytes)
1610825603.780910 sending message 105 to peer 0x133a2c0 (3111 bytes)
1610825603.780929 sending message 105 to peer 0x133a2c0 (16 bytes)
1610825603.780934 sending message 105 to peer 0x133a2c0 (35 bytes)
1610825603.780939 sending message 105 to peer 0x133a2c0 (22 bytes)
1610825603.780944 sending message 105 to peer 0x133a2c0 (11 bytes)
1610825603.780950 sending message 105 to peer 0x133a2c0 (6 bytes)
1610825603.780955 sending message 105 to peer 0x133a2c0 (15 bytes)
1610825603.780960 sending message 105 to peer 0x133a2c0 (15 bytes)
1610825603.780964 sending message 105 to peer 0x133a2c0 (10 bytes)
1610825603.780969 sending message 105 to peer 0x133a2c0 (21 bytes)
1610825603.780975 sending message 105 to peer 0x133a2c0 (11 bytes)
1610825603.780980 sending message 105 to peer 0x133a2c0 (34 bytes)
1610825603.780984 sending message 105 to peer 0x133a2c0 (11 bytes)
1610825603.780989 sending message 105 to peer 0x133a2c0 (13 bytes)
1610825603.780994 sending message 105 to peer 0x133a2c0 (12 bytes)
1610825603.780999 sending message 105 to peer 0x133a2c0 (15 bytes)
1610825603.781004 sending message 105 to peer 0x133a2c0 (16 bytes)
1610825603.781009 sending message 105 to peer 0x133a2c0 (16 bytes)
1610825603.781014 sending message 105 to peer 0x133a2c0 (554 bytes)
1610825603.781019 sending message 105 to peer 0x133a2c0 (260 bytes)
1610825603.781023 sending message 105 to peer 0x133a2c0 (47 bytes)
1610825603.781028 sending message 105 to peer 0x133a2c0 (25 bytes)
1610825603.781032 sending message 105 to peer 0x133a2c0 (25 bytes)
1610825603.781036 sending message 105 to peer 0x133a2c0 (32 bytes)
1610825603.781041 sending message 105 to peer 0x133a2c0 (34 bytes)
1610825603.781046 sending message 105 to peer 0x133a2c0 (23 bytes)
1610825603.781050 sending message 105 to peer 0x133a2c0 (11 bytes)
1610825603.781055 sending message 105 to peer 0x133a2c0 (20 bytes)
1610825603.781060 sending message 105 to peer 0x133a2c0 (22 bytes)
1610825603.781065 sending message 105 to peer 0x133a2c0 (23 bytes)
1610825603.781070 sending message 105 to peer 0x133a2c0 (466 bytes)
1610825603.781075 sending message 105 to peer 0x133a2c0 (32 bytes)
1610825603.781080 sending message 105 to peer 0x133a2c0 (35 bytes)
1610825603.781084 sending message 105 to peer 0x133a2c0 (294 bytes)
1610825603.781089 sending message 105 to peer 0x133a2c0 (7 bytes)
1610825603.781094 sending message 105 to peer 0x133a2c0 (15 bytes)
1610825603.781099 sending message 105 to peer 0x133a2c0 (11 bytes)
1610825603.781105 sending message 105 to peer 0x133a2c0 (20 bytes)
1610825603.781110 sending message 105 to peer 0x133a2c0 (8 bytes)
1610825603.781123 sending message 105 to peer 0x133a2c0 (23 bytes)
1610825603.781128 sending message 105 to peer 0x133a2c0 (24 bytes)
1610825603.781132 sending message 105 to peer 0x133a2c0 (11 bytes)
1610825603.781137 sending message 105 to peer 0x133a2c0 (17 bytes)
1610825603.781142 sending message 105 to peer 0x133a2c0 (23 bytes)
1610825603.781146 sending message 105 to peer 0x133a2c0 (46 bytes)
1610825603.781151 sending message 105 to peer 0x133a2c0 (30 bytes)
1610825603.781156 sending message 105 to peer 0x133a2c0 (10 bytes)
1610825603.781161 sending message 105 to peer 0x133a2c0 (23 bytes)
1610825603.781166 sending message 105 to peer 0x133a2c0 (65 bytes)
1610825603.781171 sending message 105 to peer 0x133a2c0 (16 bytes)
1610825603.781176 sending message 105 to peer 0x133a2c0 (104 bytes)
1610825603.781181 sending message 106 to peer 0x133a2c0 (0 bytes)
1610825603.781187 cmd_pack_argv: argv[0]=new
1610825603.781192 sending message 200 to peer 0x133a2c0 (8 bytes)
1610825603.781196 client loop enter
1610825603.818945 peer 0x133a2c0 message 207
1610825603.818959 sending message 208 to peer 0x133a2c0 (0 bytes)
1610825637.373928 sending message 208 to peer 0x133a2c0 (0 bytes)
1610825672.272050 peer 0x133a2c0 message 203
1610825672.272087 sending message 205 to peer 0x133a2c0 (0 bytes)
1610825672.272674 peer 0x133a2c0 message 204
1610825672.272696 client loop exit
  0$  l tm*
-r-x------ 1 g greg  675816 2020-06-24 Wed 13:31:29 tmux-3.1b-x86_64.AppImage*
-rw-rw-r-- 1 g greg    5544 2021-01-16 Sat 13:34:32 tmux-client-12236.log
-rw-r--r-- 1 g greg    3412 2021-01-16 Sat 13:34:32 tmux-out-12245.log
-rw-rw-r-- 1 g greg 1116480 2021-01-16 Sat 13:34:32 tmux-server-12245.log
  0$

tmux-server-* is large, and
tmux-out-* contains nonprintable control characters.
i'll try logging in via lubuntu desktop and see if i can drag/drop.

**Comment by nicm** [comment]
Is it in the history?

**Comment by gregrwm** [comment]
[tmux-out-12245.log](https://github.com/tmux/tmux/files/5825328/tmux-out-12245.log)
[tmux-server-12245.log](https://github.com/tmux/tmux/files/5825329/tmux-server-12245.log)

do these attachments answer your question?

**Comment by nicm** [comment]
No, when you enter copy mode and scroll up is the text complete?

Also, if you do this (using the same text and the same terminal sizes) without running less, does the result after resizing look the same?

**Comment by gregrwm** [comment]
ah.  no.  the lines are just gone.
it's easy to do.  try it (see OP).

without running less (or vim or...) lines don't disappear when resizing.  or with running less but without tmux, lines don't disappear when resizing.

**Comment by nicm** [comment]
No, of course it works fine for me.

In your log, the output after you quit less also look fine. The terminal is 59x14 and is showing lines 46-59 on the first 13 lines, followed by your shell prompt on line 14.

Show me a screenshot of what you see immediately after you press `q` to exit less.

**Comment by nicm** [comment]
Oh wait, I see what you  mean now, you think it should show 99 at the bottom.

**Comment by nicm** [comment]
OK there are a few assumptions made when we return from the alternate screen that are not necessarily correct if the terminal has been resized. I think we should just resize back to what the screen was when we entered alternate screen regardless of whether it is now bigger or smaller, and then resize to the new size.

Please try this and see if it fixes your problem: [tmux-alternate-resize.diff.txt](https://github.com/tmux/tmux/files/5826397/tmux-alternate-resize.diff.txt)

**Comment by gregrwm** [comment]
is that easily applied within the appimage build process (https://github.com/nelsonenzo/tmux-appimage)?

**Comment by nicm** [comment]
I don't know, it would probably be easier just to build tmux normally.

**Comment by nicm** [comment]
I think this is right, so I have applied it even though you didn't test it, let me know if you see any problems. Thanks!

**Comment by gregrwm** [comment]
way better, thank you!

tho i think there's still a bit of a bug or 2.
i applied tmux-alternate-resize.diff.txt to tmux-3.2-rc3/screen.c, hope that was right, all 3 hunks matched.

try it with the sequence in the OP.
when i shrink the xterm and exit less, what i see right after my prompt is from 5 lines earlier in my bash history, what i would expect to see if i hit the uparrow 5 times.  maybe some spurious output from tmux that the shell caught?

and then i went back into less (to have a peek at my bash history), re-expanded the xterm in less, then exited less, and then the most recent two command lines were missing.  so now a couple lines missing after an expansion, rather than after a contraction.

**Comment by gregrwm** [comment]
i just tried it all again, and the results were a tad different.  i followed the sequence in the OP, plus re-entering less, re-expanding the xterm, and exiting less (as in the prior comment).  what i see then is mostly the output lines 50 to 99 and my most recent 2 commands, but 4 of the lines from the less display mixed in.

**Comment by nicm** [comment]
I can't see anything wrong now, please give exact instructions and also show me the server log from reproducing.

**Comment by gregrwm** [comment]
```
  $  echo $TERM;uname -sp
screen
Linux x86_64
  $  cat /etc/centos-release
CentOS Linux release 7.8.2003 (Core)
```
Launch the tmux built from the diff you sent:
```
  $  ./.tmux-3.2-rc3+alternate-resize -V
.tmux-3.2-rc3+alternate-resize 3.2-rc3
  $  ./.tmux-3.2-rc3+alternate-resize -vv new
  $  echo $TERM
screen
```

Stretch the xterm to 57x226 (or probably almost any generous size).
Key in "<ctrl-r>.9" so this line is found from history:
`  $  for a in {0..99};do echo inside tmux $a;done`
Key in "<ctrl-r>foo" so this line is found from history:
`  $  echo foo|less`

Shrink the xterm to 15x59 (or probably almost any modest size).
Exit less:  `q`

See screenshot, note extra (this time blank) lines just above new prompt
Use attachment "h56":
`  $  less h56`

ReStretch the xterm to 57x226.
Exit less:  `q`

See screenshot, note "inside tmux 94" is missing and we mysteriously see 5 lines of my history from my less session.

![2021-01-28-155129_844x767_scrot](https://user-images.githubusercontent.com/1555756/106209157-25a6c680-618a-11eb-8f66-989d4bdae531.png)
![2021-01-28-154411_368x220_scrot](https://user-images.githubusercontent.com/1555756/106209159-263f5d00-618a-11eb-8ea1-a1ca9b20df00.png)
[h56.txt](https://github.com/tmux/tmux/files/5890438/h56.txt)
[tmux-client-120925.log](https://github.com/tmux/tmux/files/5890439/tmux-client-120925.log)
[tmux-out-120927.log](https://github.com/tmux/tmux/files/5890440/tmux-out-120927.log)
[tmux-server-120927.log](https://github.com/tmux/tmux/files/5890441/tmux-server-120927.log)

**Comment by nicm** [comment]
I still can't reproduce this, do you still see it if you build tmux from master now (without any patches)?

**Comment by gregrwm** [comment]
yes.  it reproduces on either centos7 or ubuntu 20.04/focal.  same details as my prior comment except:
```
  $  ./.tmux-master2021-02-04Thu20\:09 -V
.tmux-master2021-02-04Thu20:09 next-3.3
  $
```
[tmux-out-544608.log](https://github.com/tmux/tmux/files/5930027/tmux-out-544608.log)
[tmux-server-544608.log](https://github.com/tmux/tmux/files/5930028/tmux-server-544608.log)
[tmux-client-544606.log](https://github.com/tmux/tmux/files/5930029/tmux-client-544606.log)

**Comment by nicm** [comment]
Can you reproduce if you use smaller sizes like use 100x50 and 50x25? 226 is too many columns for me.

If you do this:
~~~~
tmux clear-history; seq -s"A\n" 100; seq 100
~~~~
Then do the less, resize stuff, what is the text that appears in the wrong place?

**Comment by nicm** [comment]
Oh wait does it only happen if you use your

**Comment by nicm** [comment]
Well it works for me even with that file.

**Comment by nicm** [comment]
This is very strange, I thought maybe the stray lines were data that had not been written by tmux at the time of entering or exiting the alternate screen, but there is no evidence of that in the log. I guess it is something to do with resize but I don't know where it is getting those lines from because they should have been destroyed.

**Comment by nicm** [comment]
The first extra blank lines are full of spaces, but `echo foo|less` does not print spaces.

Can you please reproduce this just up to exiting the `echo foo|less` (so you see the extra blank lines), but before you start, please do this:

~~~~
tmux clear-history; printf '\033#8'
~~~~

Also please make sure to start with a new tmux server (`tmux kill-server` first).

**Comment by gregrwm** [comment]
using 100x50 instead of 226x57 produces nearly the same results, after shrinking to 59x50 and exiting less there's only one extra line instead of two, and after re-expanding and exiting less there's only 3 mysterious lines instead of 5.

[tmux-client-580700.log](https://github.com/tmux/tmux/files/5935195/tmux-client-580700.log)
[tmux-out-580702.log](https://github.com/tmux/tmux/files/5935196/tmux-out-580702.log)
[tmux-server-580702.log](https://github.com/tmux/tmux/files/5935197/tmux-server-580702.log)

Not sure where you wanted tmux clear-history, doesn't make sense before entering tmux, upon starting tmux the history is still blank, right?  Tried it various places, no change in results.

Not sure where you wanted printf '\033#8'.  if before entering tmux, tmux wipes it away.  if before using for..echo..done or seq, they wipe it away, and the end result is the same.

**Comment by gregrwm** [comment]
Oh, doing `printf '\033#8'` just before `less h56.txt` is interesting, see the new end result screenshot:

[tmux-client-581591.log](https://github.com/tmux/tmux/files/5935280/tmux-client-581591.log)
[tmux-out-581593.log](https://github.com/tmux/tmux/files/5935281/tmux-out-581593.log)
[tmux-server-581593.log](https://github.com/tmux/tmux/files/5935282/tmux-server-581593.log)
![2021-02-05-144745_612x670_scrot](https://user-images.githubusercontent.com/1555756/107087777-93be3f80-67c1-11eb-96fe-dd8edf871c94.png)

**Comment by nicm** [comment]
Don't do the second less with the file, it is only confusing the issue. The extra blank lines after you first exit less are the problem.

**Comment by gregrwm** [comment]
ok..
[tmux-out-583010.log](https://github.com/tmux/tmux/files/5935409/tmux-out-583010.log)
[tmux-client-583008.log](https://github.com/tmux/tmux/files/5935410/tmux-client-583008.log)
[tmux-server-583010.log](https://github.com/tmux/tmux/files/5935411/tmux-server-583010.log)
with the not-quite-so-huge starting size of 100x50 there's only one blank line after shrinking and exiting less:
![2021-02-05-152318_367x216_scrot](https://user-images.githubusercontent.com/1555756/107090751-4abcba00-67c6-11eb-8bba-d0af70278fa9.png)

**Comment by nicm** [comment]
I see the blank line too:

- xterm 100x50
- tmux new
- seq 100
- echo foo|less
- resize xterm to 59x14
- q

Not sure it is the same problem actually but let me work out what is happening.

**Comment by nicm** [comment]
I only see this with bash, not with zsh or ksh.

**Comment by nicm** [comment]
I only see this with bash *and* if I look for the `echo foo|less` in the history with ^R, I don't see it if I type it again.

**Comment by nicm** [comment]
This is because bash delete cells on the line and when tmux deletes it extends the "used" count of characters on the line to the end, effectively filling it with spaces. There is no need to do this if the background colour is default. Please try this: [tmux-move.diff.txt](https://github.com/tmux/tmux/files/5943625/tmux-move.diff.txt)

I am not sure this will fix both problems however, but let me know.

**Comment by gregrwm** [comment]
```
  $  tmu -V
.tmux-master2021-02-08Mon17:51+move.diff next-3.3
```
The only sequence i'm noticing now where several lines of prior output disappear is when i use the printf command you suggested:
Shrink xterm to 59x15
```
  $  tmu -vv new
  $  for a in {0..99};do echo inside tmux $a;done
...
  $  printf '\033#8'
EEE...
  $  less h56:
```
expand xterm to 100x50
`q`
![2021-02-08-191009_788x312_scrot](https://user-images.githubusercontent.com/1555756/107307140-c24f4b00-6a4b-11eb-884d-1d128dbe6ceb.png)
```
  $  ^d
[exited]
```
[tmux-client-789149.log](https://github.com/tmux/tmux/files/5948329/tmux-client-789149.log)
[tmux-out-789151.log](https://github.com/tmux/tmux/files/5948330/tmux-out-789151.log)
[tmux-server-789151.log](https://github.com/tmux/tmux/files/5948331/tmux-server-789151.log)

And yes if i pull the less command from bash history then there's that extra line when i shrink the window and exit less, but that's hardly any issue:
Expand xterm to 100x50
```
  $  tmu -vv new
  $  for a in {0..99};do echo inside tmux $a;done
...
  $  echo foo|less
```
shrink xterm to 59x15
`q`
(Still a blank line.)
```
  $  ^d
[exited]
```
[tmux-client-788764.log](https://github.com/tmux/tmux/files/5948352/tmux-client-788764.log)
[tmux-out-788766.log](https://github.com/tmux/tmux/files/5948353/tmux-out-788766.log)
[tmux-server-788766.log](https://github.com/tmux/tmux/files/5948354/tmux-server-788766.log)

**Comment by gregrwm** [comment]
i had no trouble building tmux from master on centos7 on 02-08 at 18:00 CT.
Trying now to build tmux from master on ubuntu 16.04 this is what i get:
```
./configure
...
checking for working strnlen... yes
checking for working reallocarray... no
checking for working recallocarray... no
checking for library containing clock_gettime... none required
./configure: line 5473: syntax error near unexpected token `newline'
./configure: line 5473: `PKG_CHECK_MODULES('
```

**Comment by nicm** [comment]
Do you have pkg-config installed?

**Comment by gregrwm** [comment]
didn't really need that for centos7.  but now that i've got
```
$ sudo apt install -y automake
$ sudo apt install -y bison
$ sudo apt install -y build-essential
$ sudo apt install -y pkg-config
$ sudo apt install -y libevent-dev
$ sudo apt install -y libncurses5-dev
```
it builds and runs.

before i launch it i make sure there's no other tmux already running.
even so, when it comes up it says:
`protocol version mismatch (client 7, server 8)`
but it works anyway.

**Comment by nicm** [comment]
That message probably means something is still running a very old tmux from somewhere, are you sure you don't have an RPM of tmux still installed?

**Comment by gregrwm** [comment]
yes ok sorry my bashrc is probing the distro tmux.

**Comment by gregrwm** [comment]
Trying to build on centos8 now getting this again:
```
  #  dnf install libevent-devel ncurses-devel gcc make bison pkg-config
Last metadata expiration check: 20:42:56 ago on 2021-02-14T19:29:40 CST.
Package libevent-devel-2.1.8-5.el8.x86_64 is already installed.
Package ncurses-devel-6.1-7.20180224.el8.x86_64 is already installed.
Package gcc-8.3.1-5.1.el8.x86_64 is already installed.
Package make-1:4.2.1-10.el8.x86_64 is already installed.
Package bison-3.0.4-10.el8.x86_64 is already installed.
Package pkgconf-pkg-config-1.4.2-1.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
  0#
```
```
  $  cd tmux-master/tmux
  0$  sh autogen.sh
  0$  ./configure
... yes
checking for working reallocarray... yes
checking for working recallocarray... no
checking for library containing clock_gettime... none required
./configure: line 5461: syntax error near unexpected token `newline'
./configure: line 5461: `PKG_CHECK_MODULES('
  2$
```

**Comment by gregrwm** [comment]
old packages.  sorry.  updated, works!  Thank you!
