### ISSUE TITLE
tmux occasionally drops out of copy mode

### ISSUE THREAD

**Issue by gregrwm** [tmux/tmux#2538]
### Issue description

tmux occasionally drops out of copy mode.  not often, and so far i've no idea how to reproduce it, but i've had it happen a fair number of times, most recently in tmux-3.1b-x86_64.AppImage.  it might be related to switching away from the window that's in copy mode and switching back, but that alone isn't enough to make it happen repeatably.

TERM outside tmux: xterm
TERM inside tmux: screen

$ uname -sp && tmu -V
Linux x86_64
tmux 3.1b
0$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
0$

**Comment by nicm** [comment]
Immediately or after waiting for a while? There was a timer but I don't remember if it was removed in 3.1 or later.

**Comment by nicm** [comment]
The timer was removed after 3.1, so you need to run 3.2-rc or master. In older versions copy mode will exit after 180 seconds of inactivity.
