### ISSUE TITLE
Help wanted: How long does tmux refresh the current window? 

### ISSUE THREAD

**Issue by stark-zhang** [tmux/tmux#2539]
As title said. I am in Tmux 3.1c.

I just want to know how long the tmux would refresh current window on the screen if I take no operation for long time. and I'd like make this time be shorter than default. But I find how long the status line update, not window updates.

Could you give me some solutions?

**Comment by nicm** [comment]
tmux will not redraw the window if nothing has changed. Why would it?

**Comment by stark-zhang** [comment]
well, I use VIM in Tmux and enabled mouse in VIM.

It looks very no influently when I select something in visual mode using mouse, so I want to redraw the window periodically.

**Comment by nicm** [comment]
Are you sure the selection is being made? Are you sure vim is displaying it in the right colour? Does it appear if you press C-l or C-b r?

**Comment by stark-zhang** [comment]
yes, the selection is effective when I released the mouse, and color of vim is right.

what's the usage of C-I and C-b r? I took the try but nothing changed.

**Comment by nicm** [comment]
This sounds like a problem with vim. Are you sure you have configured the mouse correctly?

**Comment by stark-zhang** [comment]
yes and vim is displaying right if not in tmux pane.

**Comment by nicm** [comment]
That doesn't mean it is correct because tmux is not the same as your outside terminal.

**Comment by stark-zhang** [comment]
I know that and I don't think this is a bug.

and this problem sounds no solution now, doesn't it?

**Comment by nicm** [comment]
Well it doesn't seem like you have tried very hard. What have you set mouse and ttymouse to in vim? What is TERM inside and outside tmux? Where are the tmux logs?
