### ISSUE TITLE
extra highlighting in the active pane border

### ISSUE THREAD

**Issue by objectivephoenix** [tmux/tmux#2540]
### Required information

Please provide the following information:

* tmux version `tmux 3.1c`
* Platform (`Linux unknown`). I'm using Arch Linux.
* $TERM inside and outside of tmux (`xterm-kitty` outside tmux and `tmux-256color` inside tmux).

Is the highlight overflow in the active pane intentional? If yes, can I get rid of it? It has been bugging me ever since I started using tmux. 😅 This also happens without any custom config.

![2021-01-20T02:52:28,338360953+05:30](https://user-images.githubusercontent.com/67443683/105094740-ba466000-5aca-11eb-992b-b4906ccd1ac5.png)

**Comment by nicm** [comment]
There is no way to have one character in two different colours.

**Comment by objectivephoenix** [comment]
> There is no way to have one character in two different colours.

Sorry, I didn't get what you meant. Is the overflow because of a separate character?

I'm expecting the overflow not be red but the inactive pane color in the screenshot.

**Comment by nicm** [comment]
There is one character┣, it cannot be half red and half black.

**Comment by objectivephoenix** [comment]
Oh, got it.

Can I change the border style to dotted lines or dashes instead of lines? That should eliminate this issue right?

**Comment by nicm** [comment]
If you install master or 3.2-rc you can change `pane-border-lines` to different line styles but there are no dotted or dashed options because there are no suitable Unicode characters for those types of lines.

**Comment by objectivephoenix** [comment]
I don't think that option will solve this issue though.
The `pane-boder-lines` [commit](https://github.com/tmux/tmux/commit/31621036ad38ef3a2d88da838eb021430ea3c944#diff-729d4b69eea536ab59e6d25cb26c08a77533471f36b183f1ae00e6fd933e443aR111) also uses ┣ even if it's set to ASCII simple.

Anything else I can do?

**Comment by nicm** [comment]
No I don't think so. ASCIi should use + for the joins.

**Comment by objectivephoenix** [comment]
Ok.

Thanks for the help.
