### ISSUE TITLE
Tmux does not have environment variables when spawned directly

### ISSUE THREAD

**Issue by lonelykid** [tmux/tmux#2541]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

I use Alacritty terminal(https://github.com/alacritty/alacritty). It gives the option to set tmux as the default shell, and spawn it directly. This way tmux does not inherit environment variables from shells. Of course, in the interactive session, I still get the shells correctly. But for ``run xxx.sh``, the script inherits envs from tmux not from the shell, this breaks scripts. For example, https://github.com/tmux/tmux/issues/937, I use the script to rename sessions. This does not work unless I specify absolute path for every executable. This is not really a bug. I'm not sure which side I should report it to. Could you give me some suggestion about how to get this to work without hardcoding absolute path?

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.1c
* Platform (`uname -sp`). Darwin hostname 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
* $TERM inside and outside of tmux (`echo $TERM`). inside: screen-256color outside:xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by krader1961** [comment]
What does `run xxx.sh` do and in what context do you execute that command? I suspect you are running the tmux `run-shell` command (via it's `run` alias). If that is true then, yes, that command inherits the tmux env vars. There is no way for tmux to know anything about the env vars of the process running the tmux session:window:pane.

**Comment by lonelykid** [comment]
Yes. You understand my issue correctly. Because tmux does not have full envs, the script does not get full envs. I have to manually assign absolute path. this is not ideal. Maybe something like ``run 'bash -login xxx.sh'`` will also work. I just want to know the best practice since I'm new to tmux. Is it not good to set tmux as default shell?

**Comment by nicm** [comment]
We should probably set PATH to the system default if it does not exist for run-shell and friends.

**Comment by nicm** [comment]
Try this please: [tmux-defpath.diff.txt](https://github.com/tmux/tmux/files/5840824/tmux-defpath.diff.txt)

**Comment by lonelykid** [comment]
@nicm Thanks for the prompt patch. But this does not solve the problem. System default PATH is available without the patch. But things like tmux are not in the default PATH. They are added in shell configs. 
PATH echoed from spawned shell(with or without the patch applied): ``/usr/bin:/bin:/usr/sbin:/sbin``
PATH echoed from shell within tmux:``/Users/username/miniconda3/bin:/Users/username/miniconda3/condabin:/Users/username/scripts:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin``

**Comment by nicm** [comment]
There is no way for tmux to get PATH from shells that are already running. If you want a custom PATH you need to either configure it in your scripts, make your scripts source your shell profile, or add your PATH to the global environment (or possibly `update-environment`) in .tmux.conf.

**Comment by nicm** [comment]
Or start tmux from a shell which has your PATH - make alacritty run `bash -c "exec tmux"` instead of just `tmux`.

**Comment by lonelykid** [comment]
Thank you! ``bash -c "exec tmux"`` seems to double the loading time. adding ``tmux set-environment -g PATH $PATH`` to shell config might be a good option. ``update-environment`` seems irrelevant.
