### ISSUE TITLE
Fresh repo clone  misses 3.1c tag

### ISSUE THREAD

**Issue by s4uliu5** [tmux/tmux#2542]
Hi,

freshly cloned repo misses 3.1c tag as well commit 25cae5d86f01d0deb050243842ed5d967b3dc411 to which this tag is pointing,
according https://github.com/tmux/tmux/releases/tag/3.1c .

Thank you.

**Comment by nicm** [comment]
3.1c tag is there for me in a fresh checkout.

**Comment by s4uliu5** [comment]
Sorry, indeed, I recloned and indeed tag exists. 
Thank you.
Closing this (not) issue.
