### ISSUE TITLE
Conflict between t_Cs expected by vim and Cs provided by tmux terminfo

### ISSUE THREAD

**Issue by jihbuomj** [tmux/tmux#2543]
### Issue description

Outside tmux:
![t_CS-OutTMUX](https://user-images.githubusercontent.com/1842387/105270582-01ccfa80-5b64-11eb-96fb-90af0c2b197b.png)

Inside tmux:
![t_CS-InTMUX](https://user-images.githubusercontent.com/1842387/105270583-0396be00-5b64-11eb-8414-0b546907ea5b.png)

Outisde tmux, my error highlighting in vim includes an underline. Inside, there is no underline. The highlighting attempts to use an undercurl. Outside tmux, `t_Cs` and `t_Ce` are not set so vim falls back to `t_us` and `t_ue` for normal underlines. Inside tmux, vim picks up `t_Cs` as `^[]12;%p1%s^G`, the `Cs` terminfo extension in tmux, which implements a different feature. Therefore, it does not fallback to `t_us` and `t_ue` and I lose my underline.

In vim, `:help terminal-output-codes` gives some helpful output.

`default-terminal` set to `'tmux-256color'` causes this issue.

`default-terminal` set to `'screen-256color'` does not cause this issue.

Outside tmux, `echo &t_Cs` outputs nothing.
Inside: 
```
:echo &t_Cs
^[]12;%p1%s^G
```

This in my `.vimrc` does mitigate the issue.
```
if exists('$TMUX')
	let &t_Cs = ''
	let &t_Ce = ''
endif
```

My question, is this the proper way to handle it, or would some type of `terminal-override` be better?

### Required information
I am running fully up-to-date Arch Linux

`tmux-no-underline.conf`
```
set -g default-terminal 'tmux-256color'
```
`uname -sp && tmux -V && echo $TERM`

Outside tmux:
```
Linux unknown
tmux 3.1c
st-256color
```
Inside tmux:
```
Linux unknown
tmux 3.1c
tmux-256color
```
Output from ``:
[tmux-out-9321.log](https://github.com/tmux/tmux/files/5846321/tmux-out-9321.log)
[tmux-server-9321.log](https://github.com/tmux/tmux/files/5846322/tmux-server-9321.log)
[tmux-client-9319.log](https://github.com/tmux/tmux/files/5846323/tmux-client-9319.log)

**Comment by nicm** [comment]
`terminal-overrides` only affects what tmux uses, not programs inside tmux.

You will need to configure vim to not use these, or create a custom version of `tmux-256color` without them to use inside tmux.

`Cs` and `Cr` are for cursor colour not underline and were added to tmux in 2011, it would be best if vim didn't use them for something else, or if it uses them internally, not read them from terminfo.

**Comment by jihbuomj** [comment]
Unsetting the variables works, and so does moving to neovim.
