### ISSUE TITLE
Launching tmux truncates my bash history file

### ISSUE THREAD

**Issue by nawarnoori** [tmux/tmux#2544]
I have customised my bash session so that the history file doesn't ever get truncated with the following settings:

```
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
export HISTFILE=~/.bash_eternal_history
# Force prompt to write history after every command.
shopt -s histappend
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
# Ignore dupilicated commands
export HISTCONTROL=ignoreboth:erasedups
```

Right now my bash history file is about 2MB big and I back it up from time to time. However, I've recently noticed that when I boot up my computer and launch tmux in bash, it gets truncated to about 4000 lines of code. At first I thought some configuration setting or plugin was causing it but even after removing all plugins and my personal `tmux.conf` file, it still happens. 

# Steps to reproduce

In bash, I would restore my history file from the back up:
```
[~]$ cat .bash_eternal_history.bck > .bash_eternal_history
```

Make sure it's the expected size:
```
[~]$ ls -l .bash_eternal_history
-rw------- 1 nawarnoori nawarnoori 2136448 Jan 21 10:07 .bash_eternal_history
```

Launch `tmux` as normal:
```
[~]$ tmux
```

And then if I were to check the size inside tmux, I'd notice it's been truncated:
```
[~]$ ls -l .bash_eternal_history
-rw------- 1 nawarnoori nawarnoori 67162 Jan 21 10:08 .bash_eternal_history
[~]$ wc -l .bash_eternal_history
3999 .bash_eternal_history
[~]$ 
```

I just pulled from master and rebuilt tmux and I can see it's still happening. I'd be happy to attach logs but I worry it might be exporting some sensitive data (such as env vars).

My vanilla tmux environment (no plugins and config files) is as follows:

```
[~]$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux next-3.3
screen
[~]$ 
```

**Comment by nicm** [comment]
tmux starts login shells by default, are you sure this is being set in .bash_profile?

**Comment by nawarnoori** [comment]
I've never had to have `.bash_profile` and not had that problem before, is this a recent change? I don't have `.bash_profile` in my home directory, just `.profile` and `.bashrc`.

**Comment by nicm** [comment]
.profile then, it is the same thing.

**Comment by nawarnoori** [comment]
Would I need to explicitly tell `tmux` to source my `.bashrc` file on start up? It's set there, rather than `.profile` (I try not to put stuff there if I can help it). By default `.profile` does source `.bashrc` if `BASH_VERSION` is set:

```
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi
```

**Comment by nicm** [comment]
You will need to look at the bash docs to see how to make it source the right bits for login shells. If you put the config you want in .profile to test, does it fix it?

**Comment by nawarnoori** [comment]
If it's a shell issue, that's fine, I didn't realise tmux was using a login shell on start-up, I'll set it up in `.profile` and test, thank you.

**Comment by nicm** [comment]
If you set `default-command` then tmux will run that instead of the default login shell, so you were probably ending up with a non-login shell which loads .bashrc.

I don't really know exactly what bash loads and when but it sounds like your bit in .profile to load .bashrc may not be working as intended (it looks ok to me though).

**Comment by nawarnoori** [comment]
I think that did it, I'll close the issue.
