### ISSUE TITLE
Have the same issue with xfce4-terminal and vim.

### ISSUE THREAD

**Issue by ericcurtin** [tmux/tmux#2545]
uname -sp && tmux -V && echo $TERM && lsb_release -a

Linux x86_64
tmux 3.0a
xterm
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

It's xubuntu and xfce4-terminal to be specific:

My tmux.conf:

set -g mouse on

Have the same issue with gnome terminal and vim.
Without tmux I'm able to resize splits. With tmux not. I can use any mouse feature in vim except dragging stuff.

Guess it is a bug in tmux somehow

_Originally posted by @alwinmarkcf in https://github.com/tmux/tmux/issues/880#issuecomment-463141579_

**Comment by ericcurtin** [comment]
Can click, but can't resize windows in vimdiff, seems to occur in tmux3+ on xubuntu 20.04 using xfce4-terminal

**Comment by ericcurtin** [comment]
Closed, but why?

**Comment by nicm** [comment]
Copying comments from issues closed three years ago does not a bug report make. Please see https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md#what-should-i-include-in-an-issue

**Comment by ericcurtin** [comment]
Apologies, it's an option in Github I used, I can follow your template later
