### ISSUE TITLE
some cells no longer cleared with current background color when Vim outputs multiline message

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2547]
### Issue description

To reproduce, run these shell commands:

    $ tmux -Lx -f/dev/null
    $ vim -Nu NORC +'colo blue | com'

As shown in the gif below, notice that some cells are not correctly highlighted in blue:

![gif](https://user-images.githubusercontent.com/8505073/105450956-e9500380-5c7b-11eb-8bc3-40c281baf02b.gif)

The issue only happens inside tmux, and started a few days ago.

### Required information

 - `$ tmux -V`: tmux next-3.3, commit [`9ff017e`](https://github.com/tmux/tmux/commit/9ff017e908243f3e24e0e26769c8e5aadfa3cb57)
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:

 [tmux-client-6122.log](https://github.com/tmux/tmux/files/5853766/tmux-client-6122.log)
 [tmux-out-6124.log](https://github.com/tmux/tmux/files/5853767/tmux-out-6124.log)
 [tmux-server-6124.log](https://github.com/tmux/tmux/files/5853769/tmux-server-6124.log)

 - regression introduced in [`66da51b`](https://github.com/tmux/tmux/commit/66da51b6310baf408d805e0ec2f36f35bdb85339)
 - [`$ tmux info`](https://github.com/tmux/tmux/files/5853765/tmux.info.txt)

It's not an issue which can be fixed by tweaking a Vim terminal option.  I saved the values of every such option outside tmux, then applied these values while Vim was running inside tmux; but the issue persists.

**Comment by lacygoill** [comment]
I forgot to mention the version of the Vim binary; it's 8.2.2389.

Also, here is a slightly better command to reproduce:

    $ vim -Nu NONE +'colo blue | version'

**Comment by lacygoill** [comment]
I can't reproduce any longer.  I think the issue was fixed by one of the latest commits.

Probably this one: https://github.com/tmux/tmux/commit/9fcf413d877731bdd8ac75fe756a5f80f97aa52e

**Comment by nicm** [comment]
Yes I reverted the problem change for the moment until I can fix it.

**Comment by nicm** [comment]
Here is the change I am going to make instead, appears to work with your vim test: [tmux-screen-write-trim4-freelist.diff.txt](https://github.com/tmux/tmux/files/5860039/tmux-screen-write-trim4-freelist.diff.txt)

**Comment by lacygoill** [comment]
I've just applied the patch, and I can confirm that it works fine; all empty cells are correctly highlighted.  Thank you very much.

**Comment by nicm** [comment]
Great stuff let me know if you see any problems.
