### ISSUE TITLE
how do I set my cursor shape/style?

### ISSUE THREAD

**Issue by objectivephoenix** [tmux/tmux#2548]
I tried doing

```set -sa terminal-overrides ",xterm-kitty:RGB,*:Ss=\033[4 q"```

but that doesn't help. The cursor does change to underline when opening tmux but soon reverts back to block after I switch between windows and panes.

The cursor in the kitty terminal is already set to underline.

### Required information

* tmux 3.1c
* Arch Linux 5.10.9-arch1-1
* `$TERM` is `xterm-kitty` outside tmux and `tmux-256color` inside tmux

**Comment by nicm** [comment]
You probably need to set Se to whatever you want the default to be.

**Comment by ThomasDickey** [comment]
The code and existing documentation for cursor-style in kitty don't mention a way to do this via escape sequences.

**Comment by objectivephoenix** [comment]
> You probably need to set Se to whatever you want the default to be.

Thanks, that helped.
