### ISSUE TITLE
tmux does not clean up /tmp

### ISSUE THREAD

**Issue by ole-tange** [tmux/tmux#255]
A program should clean up tmp files that it no longer needs instead of leaving unused files for the user to clean up:

$ rm /tmp/tmux-1000/bar
$ tmux1.9 -L bar new-session -d 'sleep 1'
$ sleep 2
$ ls -l /tmp/tmux-*/bar 
srw-rw---- 1 tange tange 0 Feb 15 00:33 /tmp/tmux-1000/bar

The above become a reals problem when using -L with random values: Every single invocation will cause a new file.

**Comment by nicm** [comment]
We are not going to do this because it is hard to remove the files race free and in practice there are no issues with leaving the files around.
