### ISSUE TITLE
Option to disable copy mode while scrolling

### ISSUE THREAD

**Issue by engineer22** [tmux/tmux#2550]
I would like to be able to scroll without entering copy mode at all.

When I'm not in tmux, I simply scroll up, highlight something if I want, and right click to copy the text. Is it possible to use my bash terminal behavior/color palette  while in tmux and not have copy mode enabled while scrolling?

I don't want to disable mouse mode, because I need to scroll, click and change pane or resize the windows. I tried using:

set -g mouse-select-window on
set -g mouse-select-pane on
set -g mouse-resize-pane on

but to my understanding this is no longer possible due to rewrite of the mouse on command. I'm aware we can press down Shift and temporarely disable mouse mode so we can use the native copy/paste context menu, but I want to do this while in tmux mouse mode enabled.

- Debian 10
- TMUX 2.8
- Configuration file:

_enable colour support for tmux_
set -g default-terminal "screen-256color"

_split panes using alt + '|' and alt + '-'_
unbind '"'
unbind '%'
bind -n M-\ split-window -h -c "#{pane_current_path}"
bind -n M-- split-window -v -c "#{pane_current_path}"

_switch between panes with alt + 'I/J/K/L' (arrowkeys-style)_
bind -n M-l select-pane -L
bind -n M-j select-pane -R
bind -n M-i select-pane -U
bind -n M-k select-pane -D

_disable the status bar_
set -g status off

_kill focused pane with alt + 'x'_
bind -n M-x kill-pane

_enable mouse mode_
set -g mouse on

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#i-want-to-use-the-mouse-to-select-panes-but-the-terminal-to-copy-how

**Comment by engineer22** [comment]
@nicm adding **unbind -Troot MouseDown1Status** in .tmux.conf and restarting, makes no difference.

**Comment by Qyriad** [comment]
Correct me if I'm wrong, but it seems to me that OP is asking for two different things:

1. The ability to scroll in tmux without entering copy mode.
2. The ability to scroll with the mouse wheel in tmux but select text with their terminal without e.g. holding shift.

The latter has been explained to be impossible, but the former is not resolved (and is something I also would greatly like).

**Comment by engineer22** [comment]
I really want to know too. I wanted the latter, but if i can at least achieve the former is good enough.

**Comment by krader1961** [comment]
@engineer22, You wrote "I wanted the latter" by which I assume you're referring to the second point in this [comment](https://github.com/tmux/tmux/issues/2550#issuecomment-770145500). The "latter" in this case would only be possible if there was a single tmux pane. You explicitly asked that it work when there is more than one pane. How would you expect scrolling in the native terminal window to work when there is more than one tmux pane in that terminal window since each tmux pane has its own scroll history that is invisible to your terminal?

**Comment by engineer22** [comment]
@krader1961 i expect nothing.

I just want this behavior and if it's possible great, if not, i will continue using it.

**Comment by nicm** [comment]
There is no way to mix any terminal mouse behaviours and tmux mouse behaviours. Either the terminal handles the mouse or tmux does. This includes scrolling with the mouse wheel, dragging to select text, clicking on anything. There is no way for tmux to trigger terminal scrolling. There is no way for tmux to let the terminal select text when you drag. If you want tmux to handle the mouse to select panes when you click, you need it to handle scrolling as well which means using copy mode.
