### ISSUE TITLE
Pane is dead

### ISSUE THREAD

**Issue by nlj0011** [tmux/tmux#2552]
When execute “exit“ command, it display logout and pane is dead. Then I could not execute any other operation. How could I solve it?
tmux 1.8
Linux
xterm-256color

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
What would you like it to do??

**Comment by nlj0011** [comment]
> What would you like it to do??
In this case, I can only re-login by ssh, and then tmux kill this session, then the original session can return to normal...
So I wish when execute “exit“ command, it could return the original terminal interface...

**Comment by nicm** [comment]
Did you turn `remain-on-exit` on?

**Comment by nlj0011** [comment]
> Did you turn `remain-on-exit` on?

I comment it and tmux source ~/.tmux.conf.   when I exit, it still could not exclute any operation...
![image](https://user-images.githubusercontent.com/15311051/106442179-efcd4f00-64b5-11eb-82f9-03763c224e01.png)

**Comment by nicm** [comment]
You need to restart tmux entirely (`tmux kill-server`) after changing .tmux.conf, or instead run `tmux set -g remain-in-exit off` from a shell.

If you have a pane that is dead, you can kill it with `C-b x` as normal or respawn it with `C-b : respawn-pane`.
