### ISSUE TITLE
Pane-border-format containing conditional #{?pane_input_off} does not update

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#2554]
### Issue description
Conditional formats using `#{?pane_input_off,,}` are not triggered automatically.

### Required information

Please provide the following information:

* tmux version: next-3.3
* Platform: Linux x86_64
* $TERM inside (screen) and outside (xterm-256color)
* Logs from tmux: (If requested)

This default `pane-active-border-style` includes dynamic checks for `pane_in_mode` and `synchronize_panes`
which appear to trigger a border colour change immediately.

However when I add "pane_input_off" into the mix with;

```
set-option -gw pane-active-border-style "#{?pane_in_mode,fg=yellow,#{?synchronize-panes,fg=red,#{?pane_input_off,fg=colour17,fg=green}}}"
```

The colour changes for `pane_input_off` do not happen until you navigate away from the pane, and return.

Using the following command
```
sleep 2; tmux set-option synchronize-pane; sleep 2; tmux set-option synchronize-pane; sleep 2
```
The pane border visible changes after 2 seconds, and changes back after another 2 seconds.  The sleep was to ensure that
keyboard interaction wasn't triggering the refresh.

The following command
```
sleep 2; tmux select-pane -d; sleep 2; tmux select-pane -e; sleep 2
```
Should trigger the pane border to become `colour17` (a shade of blue), however it doesnt happen.

Incidentally, If `pane-border-status` is enable, eg `set-option -w pane-border-status top`, then the colour changes
are applied immediately.

Thanks

**Comment by nicm** [comment]
Yes this does not trigger a redraw, try this please: [x.diff.txt](https://github.com/tmux/tmux/files/5923997/x.diff.txt)

**Comment by systemmonkey42** [comment]
Thanks for that.  The patch didnt seem to help.

If you look lower in the file (about line 193 in the patched file) there is another set of `if` statements handling the `-e` and `-d` options.

Replicating the patch there (changing `lastwp` to `wp`) seemed to do the trick

**Comment by nicm** [comment]
Oh yeah the first one is for last-pane.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
