### ISSUE TITLE
Can't build on older macOS

### ISSUE THREAD

**Issue by 097115** [tmux/tmux#2555]
### Issue description

After the usual routine:

    git clone https://github.com/tmux/tmux
    cd tmux
    ./autogen.sh
    ./configure
    make

fails with the following error:

    gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"next-3.3\" -DPACKAGE_STRING=\"tmux\ next-3.3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"next-3.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_BITSTRING_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIBPROC_H=1 -DHAVE_PATHS_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_UTIL_H=1 -DHAVE_SYS_SIGNAME=1 -DHAVE_LIBM=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_PROC_PIDINFO=1 -DHAVE_SYSCONF=1 -DHAVE_ASPRINTF=1 -DHAVE_CFMAKERAW=1 -DHAVE_FGETLN=1 -DHAVE_GETDTABLESIZE=1 -DHAVE_GETLINE=1 -DHAVE_GETPROGNAME=1 -DHAVE_MEMMEM=1 -DHAVE_SETENV=1 -DHAVE_STRCASESTR=1 -DHAVE_STRLCAT=1 -DHAVE_STRLCPY=1 -DHAVE_STRNDUP=1 -DHAVE_STRSEP=1 -DHAVE_EVENT2_EVENT_H=1 -DHAVE_NCURSES_H=1 -DHAVE_B64_NTOP=1 -DHAVE_DAEMON=1 -DHAVE_FORKPTY=1 -DHAVE___PROGNAME=1 -DBROKEN___DEAD=1 -DBROKEN_CMSG_FIRSTHDR=1 -I.  -D_DARWIN_C_SOURCE -I/opt/local/include -I/opt/local/include -DTMUX_VERSION='"next-3.3"' -DTMUX_CONF='"/etc/tmux.conf:~/.tmux.conf:$XDG_CONFIG_HOME/tmux/tmux.conf:~/.config/tmux/tmux.conf"' -DDEBUG -iquote.       -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes -Wno-unused-result -Wno-format-y2k   -MT tmux.o -MD -MP -MF $depbase.Tpo -c -o tmux.o tmux.c &&\
    	mv -f $depbase.Tpo $depbase.Po
    tmux.c:248:6: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
            if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0)
                ^
    tmux.c:248:20: error: use of undeclared identifier 'CLOCK_MONOTONIC'
            if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0)
                              ^
    tmux.c:249:17: error: use of undeclared identifier 'CLOCK_REALTIME'
                    clock_gettime(CLOCK_REALTIME, &ts);
                                  ^
    1 warning and 2 errors generated.
    make: *** [tmux.o] Error 1

While googling, have found this https://github.com/eclipse/paho.mqtt.c/issues/546#issuecomment-423508921, which may be of some interest concerning the possible workaround.

### Required information

* tmux version: commit 3dd2e85
* Platform macOS 10.11

**Comment by 097115** [comment]
@ncim, Thanks for your help and interest!

After applying the patch and re-running `autogen.sh/configure`, the compilation now breaks with the following error:

    gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"next-3.3\" -DPACKAGE_STRING=\"tmux\ next-3.3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"next-3.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_BITSTRING_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIBPROC_H=1 -DHAVE_PATHS_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_UTIL_H=1 -DHAVE_SYS_SIGNAME=1 -DHAVE_LIBM=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_PROC_PIDINFO=1 -DHAVE_SYSCONF=1 -DHAVE_ASPRINTF=1 -DHAVE_CFMAKERAW=1 -DHAVE_FGETLN=1 -DHAVE_GETDTABLESIZE=1 -DHAVE_GETLINE=1 -DHAVE_GETPROGNAME=1 -DHAVE_MEMMEM=1 -DHAVE_SETENV=1 -DHAVE_STRCASESTR=1 -DHAVE_STRLCAT=1 -DHAVE_STRLCPY=1 -DHAVE_STRNDUP=1 -DHAVE_STRSEP=1 -DHAVE_EVENT2_EVENT_H=1 -DHAVE_NCURSES_H=1 -DHAVE_B64_NTOP=1 -DHAVE_DAEMON=1 -DHAVE_FORKPTY=1 -DHAVE___PROGNAME=1 -DBROKEN___DEAD=1 -DBROKEN_CMSG_FIRSTHDR=1 -I.  -D_DARWIN_C_SOURCE -I/opt/local/include -I/opt/local/include -DTMUX_VERSION='"next-3.3"' -DTMUX_CONF='"/etc/tmux.conf:~/.tmux.conf:$XDG_CONFIG_HOME/tmux/tmux.conf:~/.config/tmux/tmux.conf"' -DDEBUG -iquote.       -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes -Wno-unused-result -Wno-format-y2k   -MT tmux.o -MD -MP -MF $depbase.Tpo -c -o tmux.o tmux.c &&\
    	mv -f $depbase.Tpo $depbase.Po
    tmux.c:248:42: error: invalid operands to binary expression ('void' and 'int')
            if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~
    1 error generated.
    make: *** [tmux.o] Error 1

**Comment by nicm** [comment]
In compat.h, change:
~~~~
/* clock_gettime.c */
void             clock_gettime(int, struct timespec *);
~~~~
To:
~~~~
/* clock_gettime.c */
int              clock_gettime(int, struct timespec *);
~~~~
And see if it works then.

**Comment by 097115** [comment]
Woohoo, it works!

    ./tmux -V
    tmux next-3.3

Closing this?

**Comment by nicm** [comment]
Great, applied now, thanks!
