### ISSUE TITLE
Invalid option errors with fresh installation of tmux on MacOS

### ISSUE THREAD

**Issue by alexmakovetski** [tmux/tmux#2557]
### I just installed tmux on my MacOS and have not created any custom configuration yet. When I create new tmux session I am getting the following errors printed 
```
invalid option: pane-active-border-bg
invalid option: pane-border-bg
```

As far as I know those properties were deprecated in 2.9 version and they have to be updated to *-style version. But I do not have any custom configuration yet so I cannot update them.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.1c
* Platform (`uname -sp`)
Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`)
xterm-256color-italic and screen 
* Logs from tmux (`tmux kill-server; tmux -vv new`).
no logs are printed using that command

**Comment by alexmakovetski** [comment]
After building tmux from master using the following commands
```
git clone https://github.com/tmux/tmux
cd tmux
./autogen.sh
./configure
make
```

I am getting different errors printed
```
__color:23: command not found: tmux
__color:24: command not found: tmux
__color:25: command not found: tmux
__color:26: command not found: tmux
```

**Comment by nicm** [comment]
Show tmux server log file please.

**Comment by alexmakovetski** [comment]
Here it is
[server-log.zip](https://github.com/tmux/tmux/files/5935586/server-log.zip)

**Comment by nicm** [comment]
There is nothing about pane-border-bg in this log that I can see.

The __color thing seems like a problem with your shell config, is it expecting tmux to be installed somewhere different from where you installed it?

**Comment by alexmakovetski** [comment]
Thank you for your assistance!

I just install tmux using command
```
make install tmux
```
and now errors about invalid options are back
```
invalid option: pane-active-border-bg
invalid option: pane-border-bg
```
Here is server log file that should contain them
[server-log.zip](https://github.com/tmux/tmux/files/5936441/server-log.zip)

**Comment by nicm** [comment]
You have something in your shell startup files or shell config that is doing this.

**Comment by alexmakovetski** [comment]
Thank you, then I will continue my attempt to fix this.
I tried that in both zsh and bash but got the same errors, also I tried to search for using `pane-active-border-bg` and `pane-border-bg` keywords in anything related to shell startup files and failed with that 

There should be exact match of those properties, right?
Do you have any ideas what it could be if I am using default config of  iTerm2 + zsh + oh-my-zsh?

**Comment by nicm** [comment]
No I don't know but something is running tmux to set these options when you start a new shell. It is the shell inside tmux not the shell where you run tmux first. Does it happen if you remove oh-my-zsh?

**Comment by alexmakovetski** [comment]
You are right. 
If I disable oh-my-zsh there are no those errors
I should search for exact usage of `pane-active-borger-bg` option, right? Or there might be other property used that under the hood cause that issue?

I am closing that issue. 
Thank you for your assistance!

**Comment by nicm** [comment]
Perhaps there is a later version where this is fixed?

**Comment by alexmakovetski** [comment]
Unfortunately I am using the latest one.
I will drop a comment there if I resolve the issue in case if anyone else will also have such issue.
Thank you for your assistance @nicm !

**Comment by alexmakovetski** [comment]
Yeah, I found the issue that was a custom plugin that I downloaded some time ago 😒 
I was not able to find as I used `ag` which ignores files *.zsh 

That you for you help once again! And sorry for wasting your time
