### ISSUE TITLE
terminal-features option is ignored

### ISSUE THREAD

**Issue by aorith** [tmux/tmux#2559]
New `terminal-features` option seems to be ignored.

### Env

tmux next-3.3 [39904f7](https://github.com/tmux/tmux/commit/39904f7fc6e64356fe23de6264d5b03bec280d75)
Darwin i386, Big Sur 11.2
TERM outside: xterm-256color
TERM inside:  screen-256color or screen

```sh
$ locale
LANG="C.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

### Desc

I'm trying to set `RGB` and `UTF-8`, it doesn't work inside the config file with `set -as terminal-features ",*:UTF-8"`, neither by using the `-T` flag.

For example, forcing UTF-8 with `-u` works:

```sh
cd /tmp
tmux -f /dev/null -v -u
exit
grep 'using UTF-8 for ACS' tmux-*.log
# output: tmux-server-60129.log:1612615341.326919 /dev/ttys000: using UTF-8 for ACS
rm tmux-*.log
```
And of course UTF-8 characters are rendered correctly.

Forcing it with `-T UTF-8` doesn't:

```sh
cd /tmp
tmux -f /dev/null -v -T UTF-8
exit
grep 'using UTF-8 for ACS' tmux-*.log
# output: 
rm tmux-*.log
```

**Comment by nicm** [comment]
Logs?

**Comment by nicm** [comment]
Oh UTF-8 is not a terminal feature, that is an error in the man page, you need to test with RGB.

**Comment by aorith** [comment]
Oh ok, then UTF-8 can only be forced using `-u` flag.

Attaching the logs after running:

```
/usr/local/bin/tmux -vv -f /dev/null -T RGB
$ tmux info | grep RGB
196: RGB: [missing]
exit
```
[tmux-logs.tar.gz](https://github.com/tmux/tmux/files/5936845/tmux-logs.tar.gz)

**Comment by nicm** [comment]
It doesn't change the RGB capability, it just sets setrgbf and setrgbb.

**Comment by nicm** [comment]
~~~~
1612616728.908859 applying terminal feature: RGB
1612616728.908865 adding capability: AX
1612616728.908873 adding capability: setrgbf=\\E[38;2;%p1%d;%p2%d;%p3%dm
1612616728.908882 adding capability: setrgbb=\\E[48;2;%p1%d;%p2%d;%p3%dm
1612616728.908889 adding capability: setab=\\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m
1612616728.908895 adding capability: setaf=\\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m

**Comment by aorith** [comment]
Oh sorry, I see it sets setrgbf and setrgbb the same way `terminal-overrides ",*256*:RGB"` does, but in a more convenient way I guess

**Comment by nicm** [comment]
Right, the features just bundle together some  capabilities with the usual values so people can just set one feature rather than having to set a bunch of different capabilities to values that most people don't necessarily know.

**Comment by aorith** [comment]
Thank you! Closing the "issue" then :)
