### ISSUE TITLE
:clock-mode crashes the server

### ISSUE THREAD

**Issue by andrey-starodubtsev** [tmux/tmux#256]
subj, server fails with following stack cause `wp == NULL`

    #0  window_pane_set_mode (wp=wp@entry=0x0, mode=0x45c680 <window_clock_mode>) at window.c:1094
    #1  0x00000000004097bd in cmd_copy_mode_exec (self=0x13b90c0, cmdq=0x13978e0) at cmd-copy-mode.c:69
    #2  0x000000000040f9d2 in cmdq_continue_one (cmdq=0x13978e0) at cmd-queue.c:204
    #3  cmdq_continue (cmdq=0x13978e0) at cmd-queue.c:243
    #4  0x000000000040fb29 in cmdq_run (cmdq=<optimized out>, cmdlist=<optimized out>, m=m@entry=0x0) at cmd-queue.c:163
    #5  0x0000000000409433 in cmd_command_prompt_callback (data=0x13b5040, s=<optimized out>) at cmd-command-prompt.c:157
    #6  0x0000000000436b6d in status_prompt_key (c=c@entry=0x139d6e0, key=key@entry=13) at status.c:1103
    #7  0x000000000042f114 in server_client_handle_key (c=0x139d6e0, key=13) at server-client.c:582
    #8  0x00000000004383c6 in tty_keys_next (tty=tty@entry=0x139d7c0) at tty-keys.c:624
    #9  0x0000000000439270 in tty_read_callback (bufev=<optimized out>, data=0x139d7c0) at tty.c:179
    #10 0x00007fd6464fdf53 in event_base_loop () from /usr/lib/libevent-1.4.so.2
    #11 0x000000000042a9bf in proc_loop (tp=0x1392a40, loopcb=loopcb@entry=0x4315a0 <server_loop>) at proc.c:220
    #12 0x0000000000431b17 in server_start (base=base@entry=0x1392030, lockfd=lockfd@entry=6, lockfile=0x1392f80 "/home/darkmist/.tmux.conf") at server.c:186
    #13 0x0000000000406601 in client_connect (base=base@entry=0x1392030, path=0x1392010 "/tmp/tmux-1000/default", start_server=start_server@entry=1) at client.c:157
    #14 0x00000000004069b7 in client_main (base=0x1392030, argc=argc@entry=0, argv=argv@entry=0x7ffd0f72d8c0, flags=flags@entry=65536, shellcmd=shellcmd@entry=0x0) at client.c:268
    #15 0x0000000000403ba2 in main (argc=0, argv=0x7ffd0f72d8c0) at tmux.c:338

**Comment by nicm** [comment]
Fixed in OpenBSD, will be GitHub soon, thanks.
