### ISSUE TITLE
Tmux 3.1 not opening a new window

### ISSUE THREAD

**Issue by PenTestical** [tmux/tmux#2560]
### Issue description

Tmux 3.1 on Kali Linux 2020.4 does not open a new window when trying to press Ctrl-b + c (hotkey). Typing out the full command does work. I can use all other hotkeys like split screen, etc., but none related to "windows". Instead of opening a new window, it'll just have the same effect like pressing enter. 

### Required information

* tmux version 3.1c-1
* Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux
* $TERM=screen (inside tmux), $TERM=xterm-256color (outside tmux)

![image](https://user-images.githubusercontent.com/57206134/107165038-cf1f6080-69b1-11eb-98ec-ec6910e028ba.png)

**Comment by nicm** [comment]
Logs?

**Comment by PenTestical** [comment]
How to I get them? Could not see any when using the given command (tmux -vv new).

**Comment by nicm** [comment]
https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md#how-do-i-get-logs-from-tmux

**Comment by PenTestical** [comment]
server log file: 

1612778202.028300 server started (1237): version 3.1c, socket /tmp//tmux-0/default, protocol 8
1612778202.028361 on Linux 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29); libevent 2.1.12-stable (poll)
1612778202.028452 yylex_token: bind
1612778202.028465 yylex_token: -N
1612778202.028476 yylex_token: Send the prefix key
1612778202.028486 yylex_token: C-b
1612778202.028497 yylex_token: send-prefix
1612778202.028519 cmd_parse_build_commands: 0 bind
1612778202.028528 cmd_parse_build_commands: argv[0]=-N
1612778202.028536 cmd_parse_build_commands: argv[1]=Send the prefix key
1612778202.028544 cmd_parse_build_commands: argv[2]=C-b
1612778202.028552 cmd_parse_build_commands: argv[3]=send-prefix
1612778202.028565 cmd_parse: bind-key: argv[0]=bind
1612778202.028574 cmd_parse: bind-key: argv[1]=-N
1612778202.028607 cmd_parse: bind-key: argv[2]=Send the prefix key
1612778202.028616 cmd_parse: bind-key: argv[3]=C-b
1612778202.028624 cmd_parse: bind-key: argv[4]=send-prefix
1612778202.028657 cmd_parse_build_commands: bind-key -N "Send the prefix key" C-b send-prefix
1612778202.028670 cmdq_get_command: [bind-key/0x55efe7aefd10] group 5
1612778202.028679 cmdq_append <global>: [bind-key/0x55efe7aefd10]
1612778202.028688 yylex_token: bind
1612778202.028696 yylex_token: -N
1612778202.028707 yylex_token: Rotate through the panes
1612778202.028715 yylex_token: C-o
1612778202.028724 yylex_token: rotate-window
1612778202.028735 cmd_parse_build_commands: 0 bind
1612778202.028743 cmd_parse_build_commands: argv[0]=-N
1612778202.028752 cmd_parse_build_commands: argv[1]=Rotate through the panes
1612778202.028759 cmd_parse_build_commands: argv[2]=C-o
1612778202.028767 cmd_parse_build_commands: argv[3]=rotate-window
1612778202.028777 cmd_parse: bind-key: argv[0]=bind
1612778202.028811 cmd_parse: bind-key: argv[1]=-N
1612778202.028820 cmd_parse: bind-key: argv[2]=Rotate through the panes
1612778202.028828 cmd_parse: bind-key: argv[3]=C-o
1612778202.028836 cmd_parse: bind-key: argv[4]=rotate-window
1612778202.028855 cmd_parse_build_commands: bind-key -N "Rotate through the panes" C-o rotate-window
1612778202.028866 cmdq_get_command: [bind-key/0x55efe7af08f0] group 8
1612778202.028874 cmdq_append <global>: [bind-key/0x55efe7af08f0]
1612778202.028889 yylex_token: bind
1612778202.028897 yylex_token: -N
1612778202.028908 yylex_token: Suspend the current client
1612778202.028916 yylex_token: C-z
1612778202.028925 yylex_token: suspend-client
1612778202.028935 cmd_parse_build_commands: 0 bind
1612778202.028944 cmd_parse_build_commands: argv[0]=-N
1612778202.028952 cmd_parse_build_commands: argv[1]=Suspend the current client
1612778202.028960 cmd_parse_build_commands: argv[2]=C-z
1612778202.028968 cmd_parse_build_commands: argv[3]=suspend-client
1612778202.028998 cmd_parse: bind-key: argv[0]=bind
1612778202.029010 cmd_parse: bind-key: argv[1]=-N
1612778202.029048 cmd_parse: bind-key: argv[2]=Suspend the current client
1612778202.029056 cmd_parse: bind-key: argv[3]=C-z
1612778202.029064 cmd_parse: bind-key: argv[4]=suspend-client
1612778202.029084 cmd_parse_build_commands: bind-key -N "Suspend the current client" C-z suspend-client
1612778202.029094 cmdq_get_command: [bind-key/0x55efe7af1400] group 11
1612778202.029106 cmdq_append <global>: [bind-key/0x55efe7af1400]
1612778202.029120 yylex_token: bind
1612778202.029128 yylex_token: -N
1612778202.029138 yylex_token: Select next layout
1612778202.029161 yylex_token: Space
1612778202.029173 yylex_token: next-layout
1612778202.029184 cmd_parse_build_commands: 0 bind
1612778202.029192 cmd_parse_build_commands: argv[0]=-N
1612778202.029201 cmd_parse_build_commands: argv[1]=Select next layout
1612778202.029209 cmd_parse_build_commands: argv[2]=Space
1612778202.029217 cmd_parse_build_commands: argv[3]=next-layout
1612778202.029226 cmd_parse: bind-key: argv[0]=bind
1612778202.029234 cmd_parse: bind-key: argv[1]=-N
1612778202.029243 cmd_parse: bind-key: argv[2]=Select next layout
1612778202.029250 cmd_parse: bind-key: argv[3]=Space
1612778202.029258 cmd_parse: bind-key: argv[4]=next-layout
1612778202.029277 cmd_parse_build_commands: bind-key -N "Select next layout" Space next-layout
1612778202.029300 cmdq_get_command: [bind-key/0x55efe7af1c50] group 14
1612778202.029310 cmdq_append <global>: [bind-key/0x55efe7af1c50]
1612778202.029319 yylex_token: bind
1612778202.029326 yylex_token: -N
1612778202.029337 yylex_token: Break pane to a new window
1612778202.029345 yylex_token: !
1612778202.029354 yylex_token: break-pane
1612778202.029364 cmd_parse_build_commands: 0 bind
1612778202.029372 cmd_parse_build_commands: argv[0]=-N
1612778202.029381 cmd_parse_build_commands: argv[1]=Break pane to a new window
1612778202.029389 cmd_parse_build_commands: argv[2]=!
1612778202.029397 cmd_parse_build_commands: argv[3]=break-pane
1612778202.029406 cmd_parse: bind-key: argv[0]=bind
1612778202.029435 cmd_parse: bind-key: argv[1]=-N
1612778202.029446 cmd_parse: bind-key: argv[2]=Break pane to a new window
1612778202.029454 cmd_parse: bind-key: argv[3]=!
1612778202.029462 cmd_parse: bind-key: argv[4]=break-pane
1612778202.029481 cmd_parse_build_commands: bind-key -N "Break pane to a new window" ! break-pane
1612778202.029492 cmdq_get_command: [bind-key/0x55efe7af2720] group 17
1612778202.029500 cmdq_append <global>: [bind-key/0x55efe7af2720]
1612778202.029514 yylex_token: bind
1612778202.029523 yylex_token: -N
1612778202.029533 yylex_token: Split window vertically
1612778202.029541 yylex_token: "
1612778202.029549 yylex_token: split-window
1612778202.029560 cmd_parse_build_commands: 0 bind
1612778202.029568 cmd_parse_build_commands: argv[0]=-N
1612778202.029593 cmd_parse_build_commands: argv[1]=Split window vertically
1612778202.029605 cmd_parse_build_commands: argv[2]="
1612778202.029613 cmd_parse_build_commands: argv[3]=split-window
1612778202.029622 cmd_parse: bind-key: argv[0]=bind
1612778202.029630 cmd_parse: bind-key: argv[1]=-N
1612778202.029639 cmd_parse: bind-key: argv[2]=Split window vertically
1612778202.029646 cmd_parse: bind-key: argv[3]="
1612778202.029654 cmd_parse: bind-key: argv[4]=split-window
1612778202.029673 cmd_parse_build_commands: bind-key -N "Split window vertically" \\" split-window
1612778202.029707 cmdq_get_command: [bind-key/0x55efe7af2d40] group 20
1612778202.029716 cmdq_append <global>: [bind-key/0x55efe7af2d40]
1612778202.029725 yylex_token: bind
1612778202.029733 yylex_token: -N
1612778202.029743 yylex_token: List all paste buffers
1612778202.029751 yylex_token: #
1612778202.029759 yylex_token: list-buffers
1612778202.029769 cmd_parse_build_commands: 0 bind
1612778202.029778 cmd_parse_build_commands: argv[0]=-N
1612778202.029786 cmd_parse_build_commands: argv[1]=List all paste buffers
1612778202.029795 cmd_parse_build_commands: argv[2]=#
1612778202.029805 cmd_parse_build_commands: argv[3]=list-buffers
1612778202.029818 cmd_parse: bind-key: argv[0]=bind
1612778202.029827 cmd_parse: bind-key: argv[1]=-N
1612778202.029835 cmd_parse: bind-key: argv[2]=List all paste buffers
1612778202.029843 cmd_parse: bind-key: argv[3]=#
1612778202.029851 cmd_parse: bind-key: argv[4]=list-buffers
1612778202.029870 cmd_parse_build_commands: bind-key -N "List all paste buffers" \\# list-buffers
1612778202.029880 cmdq_get_command: [bind-key/0x55efe7af3190] group 23
1612778202.029889 cmdq_append <global>: [bind-key/0x55efe7af3190]
1612778202.029898 yylex_token: bind
1612778202.029906 yylex_token: -N
1612778202.029916 yylex_token: Rename current session
1612778202.029924 yylex_token: $
1612778202.029933 yylex_token: command-prompt
1612778202.029941 yylex_token: -I#S
1612778202.029952 yylex_token: rename-session -- '%%'
1612778202.029963 cmd_parse_build_commands: 0 bind
1612778202.029972 cmd_parse_build_commands: argv[0]=-N
1612778202.029980 cmd_parse_build_commands: argv[1]=Rename current session
1612778202.029988 cmd_parse_build_commands: argv[2]=$
1612778202.029997 cmd_parse_build_commands: argv[3]=command-prompt
1612778202.030005 cmd_parse_build_commands: argv[4]=-I#S
1612778202.030013 cmd_parse_build_commands: argv[5]=rename-session -- '%%'
1612778202.030023 cmd_parse: bind-key: argv[0]=bind
1612778202.030030 cmd_parse: bind-key: argv[1]=-N
1612778202.030070 cmd_parse: bind-key: argv[2]=Rename current session
1612778202.030079 cmd_parse: bind-key: argv[3]=$
1612778202.030088 cmd_parse: bind-key: argv[4]=command-prompt
1612778202.030095 cmd_parse: bind-key: argv[5]=-I#S
1612778202.030104 cmd_parse: bind-key: argv[6]=rename-session -- '%%'
1612778202.030134 cmd_parse_build_commands: bind-key -N "Rename current session" \\$ command-prompt "-I#S" "rename-session -- '%%'"
1612778202.030145 cmdq_get_command: [bind-key/0x55efe7af3bf0] group 26
1612778202.030153 cmdq_append <global>: [bind-key/0x55efe7af3bf0]
1612778202.030167 yylex_token: bind
1612778202.030175 yylex_token: -N
1612778202.030186 yylex_token: Split window horizontally
1612778202.030194 yylex_get_word: %
1612778202.030203 yylex_token: split-window
1612778202.030210 yylex_token: -h
1612778202.030221 cmd_parse_build_commands: 0 bind
1612778202.030229 cmd_parse_build_commands: argv[0]=-N
1612778202.030238 cmd_parse_build_commands: argv[1]=Split window horizontally
1612778202.030246 cmd_parse_build_commands: argv[2]=%
1612778202.030278 cmd_parse_build_commands: argv[3]=split-window
1612778202.030287 cmd_parse_build_commands: argv[4]=-h
1612778202.030296 cmd_parse: bind-key: argv[0]=bind
1612778202.030304 cmd_parse: bind-key: argv[1]=-N
1612778202.030312 cmd_parse: bind-key: argv[2]=Split window horizontally
1612778202.030320 cmd_parse: bind-key: argv[3]=%
1612778202.030328 cmd_parse: bind-key: argv[4]=split-window
1612778202.030335 cmd_parse: bind-key: argv[5]=-h
1612778202.030355 cmd_parse_build_commands: bind-key -N "Split window horizontally" % split-window -h
1612778202.030365 cmdq_get_command: [bind-key/0x55efe7af4130] group 29
1612778202.030374 cmdq_append <global>: [bind-key/0x55efe7af4130]
1612778202.030383 yylex_token: bind
1612778202.030391 yylex_token: -N
1612778202.030401 yylex_token: Kill current window
1612778202.030408 yylex_token: &
1612778202.030440 yylex_token: confirm-before
1612778202.030452 yylex_token: -pkill-window #W? (y/n)
1612778202.030461 yylex_token: kill-window
1612778202.030472 cmd_parse_build_commands: 0 bind
1612778202.030480 cmd_parse_build_commands: argv[0]=-N
1612778202.030489 cmd_parse_build_commands: argv[1]=Kill current window
1612778202.030497 cmd_parse_build_commands: argv[2]=&
1612778202.030505 cmd_parse_build_commands: argv[3]=confirm-before
1612778202.030514 cmd_parse_build_commands: argv[4]=-pkill-window #W? (y/n)
1612778202.030522 cmd_parse_build_commands: argv[5]=kill-window
1612778202.030531 cmd_parse: bind-key: argv[0]=bind
1612778202.030539 cmd_parse: bind-key: argv[1]=-N
1612778202.030547 cmd_parse: bind-key: argv[2]=Kill current window
1612778202.030555 cmd_parse: bind-key: argv[3]=&
1612778202.030600 cmd_parse: bind-key: argv[4]=confirm-before
1612778202.030610 cmd_parse: bind-key: argv[5]=-pkill-window #W? (y/n)
1612778202.030618 cmd_parse: bind-key: argv[6]=kill-window
1612778202.030644 cmd_parse_build_commands: bind-key -N "Kill current window" & confirm-before "-pkill-window #W? (y/n)" kill-window
1612778202.030654 cmdq_get_command: [bind-key/0x55efe7af4980] group 32
1612778202.030663 cmdq_append <global>: [bind-key/0x55efe7af4980]
1612778202.030678 yylex_token: bind
1612778202.030686 yylex_token: -N
1612778202.030698 yylex_token: Prompt for window index to select
1612778202.030706 yylex_token: '
1612778202.030715 yylex_token: command-prompt
1612778202.030724 yylex_token: -pindex
1612778202.030734 yylex_token: select-window -t ':%%'
1612778202.030745 cmd_parse_build_commands: 0 bind
1612778202.030753 cmd_parse_build_commands: argv[0]=-N
1612778202.030762 cmd_parse_build_commands: argv[1]=Prompt for window index to select
1612778202.030770 cmd_parse_build_commands: argv[2]='
1612778202.030778 cmd_parse_build_commands: argv[3]=command-prompt
1612778202.030786 cmd_parse_build_commands: argv[4]=-pindex
1612778202.030795 cmd_parse_build_commands: argv[5]=select-window -t ':%%'
1612778202.030804 cmd_parse: bind-key: argv[0]=bind
1612778202.030812 cmd_parse: bind-key: argv[1]=-N
1612778202.030845 cmd_parse: bind-key: argv[2]=Prompt for window index to select
1612778202.030860 cmd_parse: bind-key: argv[3]='
1612778202.030868 cmd_parse: bind-key: argv[4]=command-prompt
1612778202.030876 cmd_parse: bind-key: argv[5]=-pindex
1612778202.030884 cmd_parse: bind-key: argv[6]=select-window -t ':%%'
1612778202.030911 cmd_parse_build_commands: bind-key -N "Prompt for window index to select" \\' command-prompt -pindex "select-window -t ':%%'"
1612778202.030921 cmdq_get_command: [bind-key/0x55efe7af51f0] group 35
1612778202.030930 cmdq_append <global>: [bind-key/0x55efe7af51f0]
1612778202.030939 yylex_token: bind
1612778202.030950 yylex_token: -N
1612778202.030964 yylex_token: Switch to previous client
1612778202.030972 yylex_token: (
1612778202.030981 yylex_token: switch-client
1612778202.030988 yylex_token: -p
1612778202.030999 cmd_parse_build_commands: 0 bind
1612778202.031007 cmd_parse_build_commands: argv[0]=-N
1612778202.031016 cmd_parse_build_commands: argv[1]=Switch to previous client
1612778202.031024 cmd_parse_build_commands: argv[2]=(
1612778202.031033 cmd_parse_build_commands: argv[3]=switch-client
1612778202.031041 cmd_parse_build_commands: argv[4]=-p
1612778202.031050 cmd_parse: bind-key: argv[0]=bind
1612778202.031058 cmd_parse: bind-key: argv[1]=-N
1612778202.031067 cmd_parse: bind-key: argv[2]=Switch to previous client
1612778202.031074 cmd_parse: bind-key: argv[3]=(
1612778202.031083 cmd_parse: bind-key: argv[4]=switch-client
1612778202.031090 cmd_parse: bind-key: argv[5]=-p
1612778202.031110 cmd_parse_build_commands: bind-key -N "Switch to previous client" ( switch-client -p
1612778202.031121 cmdq_get_command: [bind-key/0x55efe7af56f0] group 38
1612778202.031129 cmdq_append <global>: [bind-key/0x55efe7af56f0]
1612778202.031143 yylex_token: bind
1612778202.031152 yylex_token: -N
1612778202.031162 yylex_token: Switch to next client
1612778202.031169 yylex_token: )
1612778202.031178 yylex_token: switch-client
1612778202.031208 yylex_token: -n
1612778202.031222 cmd_parse_build_commands: 0 bind
1612778202.031231 cmd_parse_build_commands: argv[0]=-N
1612778202.031239 cmd_parse_build_commands: argv[1]=Switch to next client
1612778202.031247 cmd_parse_build_commands: argv[2]=)
1612778202.031255 cmd_parse_build_commands: argv[3]=switch-client
1612778202.031263 cmd_parse_build_commands: argv[4]=-n
1612778202.031272 cmd_parse: bind-key: argv[0]=bind
1612778202.031280 cmd_parse: bind-key: argv[1]=-N
1612778202.031288 cmd_parse: bind-key: argv[2]=Switch to next client
1612778202.031296 cmd_parse: bind-key: argv[3]=)
1612778202.031304 cmd_parse: bind-key: argv[4]=switch-client
1612778202.031312 cmd_parse: bind-key: argv[5]=-n
1612778202.031331 cmd_parse_build_commands: bind-key -N "Switch to next client" ) switch-client -n
1612778202.031342 cmdq_get_command: [bind-key/0x55efe7af5d90] group 41
1612778202.031350 cmdq_append <global>: [bind-key/0x55efe7af5d90]
1612778202.031359 yylex_token: bind
1612778202.031367 yylex_token: -N
1612778202.031377 yylex_token: Rename current window
1612778202.031384 yylex_token: ,
1612778202.031393 yylex_token: command-prompt
1612778202.031401 yylex_token: -I#W
1612778202.031411 yylex_token: rename-window -- '%%'
1612778202.031421 cmd_parse_build_commands: 0 bind
1612778202.031430 cmd_parse_build_commands: argv[0]=-N
1612778202.031462 cmd_parse_build_commands: argv[1]=Rename current window
1612778202.031471 cmd_parse_build_commands: argv[2]=,
1612778202.031479 cmd_parse_build_commands: argv[3]=command-prompt
1612778202.031487 cmd_parse_build_commands: argv[4]=-I#W
1612778202.031496 cmd_parse_build_commands: argv[5]=rename-window -- '%%'
1612778202.031505 cmd_parse: bind-key: argv[0]=bind
1612778202.031513 cmd_parse: bind-key: argv[1]=-N
1612778202.031522 cmd_parse: bind-key: argv[2]=Rename current window
1612778202.031530 cmd_parse: bind-key: argv[3]=,
1612778202.031538 cmd_parse: bind-key: argv[4]=command-prompt
1612778202.031546 cmd_parse: bind-key: argv[5]=-I#W
1612778202.031554 cmd_parse: bind-key: argv[6]=rename-window -- '%%'
1612778202.031618 cmd_parse_build_commands: bind-key -N "Rename current window" , command-prompt "-I#W" "rename-window -- '%%'"
1612778202.031640 cmdq_get_command: [bind-key/0x55efe7af6590] group 44
1612778202.031650 cmdq_append <global>: [bind-key/0x55efe7af6590]
1612778202.031664 yylex_token: bind
1612778202.031672 yylex_token: -N
1612778202.031685 yylex_token: Delete the most recent paste buffer
1612778202.031692 yylex_token: -
1612778202.031701 yylex_token: delete-buffer
1612778202.031711 cmd_parse_build_commands: 0 bind
1612778202.031720 cmd_parse_build_commands: argv[0]=-N
1612778202.031729 cmd_parse_build_commands: argv[1]=Delete the most recent paste buffer
1612778202.031737 cmd_parse_build_commands: argv[2]=-
1612778202.031745 cmd_parse_build_commands: argv[3]=delete-buffer
1612778202.031754 cmd_parse: bind-key: argv[0]=bind
1612778202.031762 cmd_parse: bind-key: argv[1]=-N
1612778202.031771 cmd_parse: bind-key: argv[2]=Delete the most recent paste buffer
1612778202.031779 cmd_parse: bind-key: argv[3]=-
1612778202.031787 cmd_parse: bind-key: argv[4]=delete-buffer
1612778202.031806 cmd_parse_build_commands: bind-key -N "Delete the most recent paste buffer" - delete-buffer
1612778202.031816 cmdq_get_command: [bind-key/0x55efe7af6920] group 47
1612778202.031825 cmdq_append <global>: [bind-key/0x55efe7af6920]
1612778202.031834 yylex_token: bind
1612778202.031841 yylex_token: -N
1612778202.031852 yylex_token: Move the current window
1612778202.031859 yylex_token: .
1612778202.031868 yylex_token: command-prompt
1612778202.031929 yylex_token: move-window -t '%%'
1612778202.031945 cmd_parse_build_commands: 0 bind
1612778202.031953 cmd_parse_build_commands: argv[0]=-N
1612778202.031962 cmd_parse_build_commands: argv[1]=Move the current window
1612778202.031970 cmd_parse_build_commands: argv[2]=.
1612778202.031978 cmd_parse_build_commands: argv[3]=command-prompt
1612778202.031986 cmd_parse_build_commands: argv[4]=move-window -t '%%'
1612778202.031995 cmd_parse: bind-key: argv[0]=bind
1612778202.032003 cmd_parse: bind-key: argv[1]=-N
1612778202.032011 cmd_parse: bind-key: argv[2]=Move the current window
1612778202.032019 cmd_parse: bind-key: argv[3]=.
1612778202.032027 cmd_parse: bind-key: argv[4]=command-prompt
1612778202.032035 cmd_parse: bind-key: argv[5]=move-window -t '%%'
1612778202.032058 cmd_parse_build_commands: bind-key -N "Move the current window" . command-prompt "move-window -t '%%'"
1612778202.032068 cmdq_get_command: [bind-key/0x55efe7af7280] group 50
1612778202.032077 cmdq_append <global>: [bind-key/0x55efe7af7280]
1612778202.032091 yylex_token: bind
1612778202.032100 yylex_token: -N
1612778202.032110 yylex_token: Describe key binding
1612778202.032117 yylex_token: /
1612778202.032127 yylex_token: command-prompt
1612778202.032135 yylex_token: -kpkey
1612778202.032145 yylex_token: list-keys -1N "%%%"
1612778202.032156 cmd_parse_build_commands: 0 bind
1612778202.032164 cmd_parse_build_commands: argv[0]=-N
1612778202.032173 cmd_parse_build_commands: argv[1]=Describe key binding
1612778202.032181 cmd_parse_build_commands: argv[2]=/
1612778202.032189 cmd_parse_build_commands: argv[3]=command-prompt
1612778202.032197 cmd_parse_build_commands: argv[4]=-kpkey
1612778202.032205 cmd_parse_build_commands: argv[5]=list-keys -1N "%%%"
1612778202.032214 cmd_parse: bind-key: argv[0]=bind
1612778202.032222 cmd_parse: bind-key: argv[1]=-N
1612778202.032231 cmd_parse: bind-key: argv[2]=Describe key binding
1612778202.032238 cmd_parse: bind-key: argv[3]=/
1612778202.032246 cmd_parse: bind-key: argv[4]=command-prompt
1612778202.032254 cmd_parse: bind-key: argv[5]=-kpkey
1612778202.032262 cmd_parse: bind-key: argv[6]=list-keys -1N "%%%"
1612778202.032286 cmd_parse_build_commands: bind-key -N "Describe key binding" / command-prompt -kpkey "list-keys -1N \\"%%%\\""
1612778202.032297 cmdq_get_command: [bind-key/0x55efe7af7990] group 53
1612778202.032305 cmdq_append <global>: [bind-key/0x55efe7af7990]
1612778202.032341 yylex_token: bind
1612778202.032349 yylex_token: -N
1612778202.032358 yylex_token: Select window 0
1612778202.032366 yylex_token: 0
1612778202.032375 yylex_token: select-window
1612778202.032383 yylex_token: -t:=0
1612778202.032393 cmd_parse_build_commands: 0 bind
1612778202.032409 cmd_parse_build_commands: argv[0]=-N
1612778202.032418 cmd_parse_build_commands: argv[1]=Select window 0
1612778202.032425 cmd_parse_build_commands: argv[2]=0
1612778202.032433 cmd_parse_build_commands: argv[3]=select-window
1612778202.032441 cmd_parse_build_commands: argv[4]=-t:=0
1612778202.032451 cmd_parse: bind-key: argv[0]=bind
1612778202.032459 cmd_parse: bind-key: argv[1]=-N
1612778202.032467 cmd_parse: bind-key: argv[2]=Select window 0
1612778202.032474 cmd_parse: bind-key: argv[3]=0
1612778202.032482 cmd_parse: bind-key: argv[4]=select-window
1612778202.032490 cmd_parse: bind-key: argv[5]=-t:=0
1612778202.032510 cmd_parse_build_commands: bind-key -N "Select window 0" 0 select-window -t:=0
1612778202.032520 cmdq_get_command: [bind-key/0x55efe7af7e40] group 56
1612778202.032529 cmdq_append <global>: [bind-key/0x55efe7af7e40]
1612778202.032538 yylex_token: bind
1612778202.032546 yylex_token: -N
1612778202.032556 yylex_token: Select window 1
1612778202.032563 yylex_token: 1
1612778202.032624 yylex_token: select-window
1612778202.032636 yylex_token: -t:=1
1612778202.032646 cmd_parse_build_commands: 0 bind
1612778202.032655 cmd_parse_build_commands: argv[0]=-N
1612778202.032664 cmd_parse_build_commands: argv[1]=Select window 1
1612778202.032672 cmd_parse_build_commands: argv[2]=1
1612778202.032680 cmd_parse_build_commands: argv[3]=select-window
1612778202.032688 cmd_parse_build_commands: argv[4]=-t:=1
1612778202.032697 cmd_parse: bind-key: argv[0]=bind
1612778202.032705 cmd_parse: bind-key: argv[1]=-N
1612778202.032713 cmd_parse: bind-key: argv[2]=Select window 1
1612778202.032721 cmd_parse: bind-key: argv[3]=1
1612778202.032753 cmd_parse: bind-key: argv[4]=select-window
1612778202.032762 cmd_parse: bind-key: argv[5]=-t:=1
1612778202.032783 cmd_parse_build_commands: bind-key -N "Select window 1" 1 select-window -t:=1
1612778202.032793 cmdq_get_command: [bind-key/0x55efe7af83b0] group 59
1612778202.032802 cmdq_append <global>: [bind-key/0x55efe7af83b0]
1612778202.032816 yylex_token: bind
1612778202.032825 yylex_token: -N
1612778202.032834 yylex_token: Select window 2
1612778202.032858 yylex_token: 2
1612778202.032868 yylex_token: select-window
1612778202.032875 yylex_token: -t:=2
1612778202.032886 cmd_parse_build_commands: 0 bind
1612778202.032894 cmd_parse_build_commands: argv[0]=-N
1612778202.032903 cmd_parse_build_commands: argv[1]=Select window 2
1612778202.032910 cmd_parse_build_commands: argv[2]=2
1612778202.032918 cmd_parse_build_commands: argv[3]=select-window
1612778202.032926 cmd_parse_build_commands: argv[4]=-t:=2
1612778202.032935 cmd_parse: bind-key: argv[0]=bind
1612778202.032959 cmd_parse: bind-key: argv[1]=-N
1612778202.032968 cmd_parse: bind-key: argv[2]=Select window 2
1612778202.032976 cmd_parse: bind-key: argv[3]=2
1612778202.032984 cmd_parse: bind-key: argv[4]=select-window
1612778202.032991 cmd_parse: bind-key: argv[5]=-t:=2
1612778202.033025 cmd_parse_build_commands: bind-key -N "Select window 2" 2 select-window -t:=2
1612778202.033039 cmdq_get_command: [bind-key/0x55efe7af89f0] group 62
1612778202.033047 cmdq_append <global>: [bind-key/0x55efe7af89f0]

**Comment by nicm** [comment]
Please attach the files to the issue rather than pasting them into a comment.

**Comment by PenTestical** [comment]
[tmux-client-1235.log](https://github.com/tmux/tmux/files/5942844/tmux-client-1235.log)
[tmux-out-1237.log](https://github.com/tmux/tmux/files/5942846/tmux-out-1237.log)
tmux server log (was too big to upload):
https://easyupload.io/li5lq0

**Comment by nicm** [comment]
Your log should not be so big from simply starting tmux, pressing C-b c and exiting. Please do that only and send the log, so do:
~~~~
tmux kill-server
tmux -vv new
~~~~
Then inside tmux try to create a window to show the problem, then exit:
~~~~
C-b c
exit
~~~~

**Comment by PenTestical** [comment]
[tmux-client-1511.log](https://github.com/tmux/tmux/files/5943118/tmux-client-1511.log)
[tmux-out-1513.log](https://github.com/tmux/tmux/files/5943119/tmux-out-1513.log)
[tmux-server-1513.log](https://github.com/tmux/tmux/files/5943120/tmux-server-1513.log)

**Comment by nicm** [comment]
You are pressing `C-b C-c` not `C-b c`. Make sure you release `Ctrl` before pressing `c`.

**Comment by PenTestical** [comment]
Ahh, thank you for your help. Tried to release it a few times without result. I have a german keyboard if that is relevant! Could you look into the new logs please?

[tmux-client-1964.log](https://github.com/tmux/tmux/files/5943508/tmux-client-1964.log)
[tmux-out-1966.log](https://github.com/tmux/tmux/files/5943509/tmux-out-1966.log)
[tmux-server-1966.log](https://github.com/tmux/tmux/files/5943510/tmux-server-1966.log)

**Comment by nicm** [comment]
You are sending `C-b c` now, but your prefix is not `C-b` it is `C-a`:
~~~~
1612785405.736214 loading /root/.tmux.conf
1612785405.736242 yylex_token: set
1612785405.736252 yylex_token: -g
1612785405.736262 yylex_token: prefix
1612785405.736271 yylex_token: ^a
~~~~

**Comment by PenTestical** [comment]
Oh my god, I tried to fix this for a few hours now. Thank you!!! That was a great and quick help. Thank you!!

Worked now :)

**Comment by nicm** [comment]
OK great!
