### ISSUE TITLE
Feature request: Hyperlinks (continued)

### ISSUE THREAD

**Issue by Mellbourn** [tmux/tmux#2563]
This feature request is a continuation of https://github.com/tmux/tmux/issues/911 which was opened in May 2017 and locked in March 2020.

tmux does not implement hyperlinks using the OSC 8 format, see https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda 

The previous feature request discusses many points
* Is it simple or not to implement? Some answers imply that it would be simple.
* Some answers make it sound that it should already work "FAIK tmux has always ignored unknown escape sequences.", but it does not work (at least on iTerm and Terminal on macOS)
* Whether or not terminal hyperlinks will be widely implemented or used. In my opinion, it has become a common feature and well supported by many terminal emulators, see link above.

There exists at least one fork of tmux supporting hyperlinks https://github.com/dandavison/tmux

So, I think that this feature deserves a second look. If there is a better forum to bring this up, please advice. The previous request is the top Google hit if you search for "tmux hyperlinks"

**Comment by nicm** [comment]
https://github.com/tmux/tmux/pull/2403#issuecomment-707674012
