### ISSUE TITLE
Possible wrong character width with "🄼"?

### ISSUE THREAD

**Issue by dsedivec** [tmux/tmux#2564]
### Issue description

I *suspect* that tmux master branch (I didn't test earlier) may be using the wrong width for "🄼".  Steps to reproduce:

1. Start iTerm on macOS with a 24x80 terminal
2. `tmux -f/dev/null -vv -Ltest new env TERM=screen-256color bash --norc`
3. `echo '🄼-------------------------------------------------------------------------------'`
4. Do something that involves moving the cursor away then back to where it should be, such as up arrow then down arrow (back and then forward in Bash history), or <kbd>C-b</kbd> : ls <kbd>Enter</kbd> q

Expected behavior: cursor is on line three

Observed behavior: cursor seems to be on line four

For example, here's the result of pressing up arrow then down arrow (history back/forward) at the Bash prompt:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/95333/107423091-8bc40f80-6ae1-11eb-96fe-014b3b35692b.png">

Unfortunately you can't see where the cursor is in that screen shot, but it's on line 5, just under the "e" in the second "echo", whereas it should be on line 4 just after the "$" in the second prompt.

I actually ran across this problem because I use this character in my Emacs status line and I noticed it was broken within tmux:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/95333/107423361-d5acf580-6ae1-11eb-9433-ec8b70f294e3.png">

That "-" is not supposed to be in the third-to-last line there.  For comparison, here's Emacs looking correct outside of tmux, still in the exact same iTerm window:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/95333/107426560-0131df00-6ae6-11eb-8ee2-d9270d2104f3.png">

(It sure *looks* like it should be 2 cells wide, but I guess Unicode tells us it's only 1?  I guess I need to live with it being cramped, I'm fine with that.  BTW, font here is Fira Mono 8 pt, iTerm horizontal character spacing set to "100".)

I don't think I really know what I'm doing here, but I cooked up a little C program that may or may not provide you with useful information:

```c
#include <stdio.h>
#include <wchar.h>
#include <locale.h>
#include <utf8proc.h>

int main(int argc, char *argv[])
{
  setlocale(LC_ALL, "en_US.utf-8");
  wint_t ch = getwchar();
  printf("\nwcwidth=%d\nutf8proc_charwidth=%d\n", wcwidth(ch),
         utf8proc_charwidth(ch));
  printf("%d\n", utf8proc_category(ch));
  return 0;
}
```

<img width="134" alt="image" src="https://user-images.githubusercontent.com/95333/107423574-1a389100-6ae2-11eb-93de-1fe6fb74b4da.png">

### Required information

Please provide the following information:

* tmux next-3.3 (20210209-c6215b5) built with libutf8proc 2.6.1
* `uname -sp`: Darwin i386
* Outside tmux `TERM=xterm-256color`, inside tmux TERM defaults to `screen`, but above you can see I forced it to `screen-256color`
* Logs from `env - TERM=xterm-256color LANG=en_US.utf-8 PATH=/bin:/usr/bin:/opt/local/bin tmux -f/dev/null -vv -Ltest new env TERM=screen-256color /opt/local/bin/bash --norc`:
[tmux_logs_20210209_2045Z.zip](https://github.com/tmux/tmux/files/5954132/tmux_logs_20210209_2045Z.zip)

I think these might be relevant iTerm settings, I'm running iTerm 3.4.3:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/95333/107424915-d9da1280-6ae3-11eb-97c2-7e701323a6c4.png">

I've been pouring over other bugs, here and elsewhere, regarding UTF-8 character widths, so I'm totally open to this problem being with iTerm, or with macOS, or something else entirely I haven't thought of.

**Comment by nicm** [comment]
tmux gets widths from either wcwidth or utf8proc, if they are wrong there is not much it can do about it.

**Comment by dsedivec** [comment]
> tmux gets widths from either wcwidth or utf8proc, if they are wrong there is not much it can do about it.

Understood, but I've compiled with libutf8proc, and I *think* `utf8proc_charwidth` thinks the width is 1 (based on my C program, see above), and it sure looks like iTerm thinks its width is 1, so why does it seem like tmux still thinks it's 2?  Does tmux use widths from libutf8proc (when built with libutf8proc, of course)?

**Comment by nicm** [comment]
Looks like the code to call utf8proc has got lost, probably a bad merge.

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/5956923/x.diff.txt)

**Comment by dsedivec** [comment]
> Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/5956923/x.diff.txt)

That works perfectly in both Bash and Emacs.  Thank you so much!

**Comment by nicm** [comment]
Great thanks.
