### ISSUE TITLE
freezero compat should use `memset_s` or leak confidential information

### ISSUE THREAD

**Issue by TomMD** [tmux/tmux#2565]
While playing around with [a CI tool](https://console.muse.dev/result/TomMD/tmux/01EY4P0CH1TTF043Q79G8498AP?t=CustomTool%20%22Cobra%22%7CConfidentialMemoryLeaks&tab=results), I saw an instance of `memset(); free();` which doesn't make much sense (memset can get optimized away).  Is there something I'm missing about the build environment or should we change this to `memset_s()`? the `_s` version ensures the compiler won't optimize it away.

**Comment by nicm** [comment]
freezero is only used by imsg and tmux doesn't put anything in imsgs you couldn't find by digging around elsewhere in its memory, it does not try to make anything secret. The freezero calls are meant to support processes that do care about what is in imsgs.

**Comment by rillig** [comment]
What is the purpose of `freezero` then, compared to a simple `free`? To me, it looked like an obvious oversight of an inexperienced programmer, so it might be better to remove it from the code entirely, to avoid this impression.

**Comment by nicm** [comment]
The purpose is not to have to carry unnecessary differences from the upstream imsg code.

**Comment by rillig** [comment]
If I am correct that upstream is OpenBSD, you should replace the `memset` with `explicit_bzero`, since that's [what OpenBSD does](https://github.com/openbsd/src/blob/a316e13129736f6960bf2f3538d9af057cb70ccf/lib/libc/stdlib/malloc.c#L1475).

**Comment by nicm** [comment]
explicit_bzero is not portable.

**Comment by rillig** [comment]
That's probably why tmux has included it in `compat/explicit_bzero.c`.

**Comment by nicm** [comment]
I guess either I added that after freezero or I forgot about it.
