### ISSUE TITLE
When using tmux in Windows Bash, there are many extra dash lines.

### ISSUE THREAD

**Issue by deeperlearner** [tmux/tmux#2566]
### Issue description
When using pylint inside VIM, if the pylint message contains dash lines, the tmux window will got extra dash lines.
The extra dash lines can only be removed by redraw the screen.
![1](https://user-images.githubusercontent.com/30494216/107739726-80245300-6d44-11eb-8e21-882f49b6f46c.png)
![2](https://user-images.githubusercontent.com/30494216/107739727-80bce980-6d44-11eb-905f-dbc50d09a818.png)
This only happens in Windows Subsystem for Linux.

### Required information

* tmux version (`tmux -V`).
tmux 3.0a
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-419.log](https://github.com/tmux/tmux/files/5970158/tmux-client-419.log)
[tmux-out-421.log](https://github.com/tmux/tmux/files/5970159/tmux-out-421.log)
[tmux-server-421.log](https://github.com/tmux/tmux/files/5970160/tmux-server-421.log)

**Comment by nicm** [comment]
I don't see this character being printed in the tmux server log at all, are you sure you reproduced the problem when logging?

**Comment by deeperlearner** [comment]
sorry, I update the log

**Comment by nicm** [comment]
The system is telling tmux this character is width 1 but from the screenshot it looks like the font or terminal believe it to be width 2.

You could try building tmux with utf8proc, or try a different font.

**Comment by deeperlearner** [comment]
Changing font did solve this problem. Thanks a lot!!
