### ISSUE TITLE
OSC sequences

### ISSUE THREAD

**Issue by mintty** [tmux/tmux#2567]
I suggest tmux should recognise OSC colour setting and other control sequences and pass them through to the underlying terminal implicitly, without the troublesome need of embedding them into an obscure pass-through sequence which is especially getting hard to manage in the case of nested tmux/screen instances as discussed elsewhere (e.g. #846).

**Comment by nicm** [comment]
What sequence?

**Comment by mintty** [comment]
Basically all of them, unless there are specific cautions.
Particularly
ESC ] 4 ; color-number ; color-spec BEL/ST
ESC ] 10/11/12 ; foreground/background/cursor color BEL/ST
ESC ] 104/110/... ; reset color BEL/ST
ESC ] 2 ; window-title BEL/ST
ESC ] 50 ; font BEL/ST
etc.

**Comment by mintty** [comment]
Likewise all SGR sequences, whether known or not, e.g. `ESC [ 4:3 m` for curly underlined.

**Comment by nicm** [comment]
If we pass through SGR then they will be lost as soon as tmux redraws or the user detaches and reattaches. So that is not going to happen. tmux supports curly underlines already anyway.

tmux supports OSC 2, 10/11/12, 104/112 natively so we are not passing them through.

I need to look at the others you mention. I could be convinced to pass through sequences that do things there is no need or no way for tmux to maintain after detach/reattach.

**Comment by nicm** [comment]
Basically we can only pass through things that change the terminal state in such a way that tmux doesn't need to know about it, if you see what I mean - otherwise tmux will just mess it up as soon as it needs to redraw, the user detaches and rettaches or suspends, or whatever else.

**Comment by nicm** [comment]
tmux supports OSC 4 as well but it can only work on terminals which support RGB because terminals only have one palette so without RGB tmux can't support palette setting with multiple panes.

**Comment by nicm** [comment]
I think we could safely pass through OSC 50 if the terminal looks xterm-like.

**Comment by mintty** [comment]
About SGR, you could perhaps store attributes regardless of whether they are known; or complete the set of known attributes (https://github.com/mintty/mintty/wiki/Tips#text-attributes-and-rendering).
Neither curly underline nor OSC 10/11/4 work for me in tmux. This is tmux 3.1b on cygwin.

**Comment by nicm** [comment]
Well, possibly, but this would be a lot of effort for a few SGR that tmux doesn't support. And if tmux doesn't know what an attribute does, how would it know what the terminal outside would do with it?

3.1 is too old for tmux to autodetect mintty (you need master) so you will need to add the terminfo entry yourself (in .tmux.conf):
~~~~
set -as terminal-overrides 'xterm*:Smulx=\E[4::%p1%dm'
~~~~

OSC 10/11 should work out of the box. What exactly are you sending? This works for me:
~~~~
printf '\033]11;rgb:30/00/30\007'
~~~~

OSC 4 works for me also, perhaps you need to add the RGB flag also:
~~~~
set -as terminal-overrides 'xterm*:RGB'
~~~~

**Comment by mintty** [comment]
Ah, so it's a matter of colour spec syntax; I was using something like 
`echo -e '\e]11;blue\a'` or `echo -e '\e]11;#102030\a'`. Please consider to support those.

**Comment by nicm** [comment]
Hmm, IIRC I didn't write the support, I guess the person who did didn't know or didn't care about those forms. I'll have a look, the second should be easy enough, I guess the first is the X11 colour list.

**Comment by mintty** [comment]
I suggest a tweak as follows:
```
/* Parse colour from OSC. */
static int
input_osc_parse_colour(const char *p, u_int *r, u_int *g, u_int *b)
{
	if (sscanf(p, "rgb:%02x/%02x/%02x", r, g, b) == 3)
		;
	else if (sscanf(p, "rgb:%04x/%04x/%04x", r, g, b) == 3) {
		*r >>= 8;
		*g >>= 8;
		*b >>= 8;
	}
	else if (sscanf(p, "#%02x%02x%02x", r, g, b) == 3)
		;
	else if (sscanf(p, "%d,%d,%d", r, g, b) == 3)
		;
	else
		return 0;

	if (*r > 255 || *g > 255 || *b > 255)
		return 0;

	log_debug("%s: %s = %02x%02x%02x", __func__, p, *r, *g, *b);
	return (1);
}
```
This includes also the decimal triple format like `100,200,255`. The previously supported 1- or 3-digit rgb: formats could be easily added but I doubt those are valid formats specified anywhere, neither are mixed-length rgb values.
I'll add menmonic colour names (the X11 list) as well.

**Comment by mintty** [comment]
New patch:
```
static struct {
	u_char r, g, b;
	const char * name;
} x11colours[] = {
// include file to be generated with this command (if rgb.txt is installed):
//	sed -e 's,	, ,g' -e 's/ *\([0-9][0-9]*\) *\([0-9][0-9]*\) *\([0-9][0-9]*\) *\([^ ].*[^ ]\) */	{\1, \2, \3, "\4"},/' /usr/share/X11/rgb.txt > rgb.t
#include "rgb.h"
};

/* Parse colour from OSC. */
static int
input_osc_parse_colour(const char *p, u_int *r, u_int *g, u_int *b)
{
	float c, m, y, k = 0;

	if (sscanf(p, "rgb:%02x/%02x/%02x", r, g, b) == 3)
		;
	else if (sscanf(p, "rgb:%04x/%04x/%04x", r, g, b) == 3) {
		*r >>= 8;
		*g >>= 8;
		*b >>= 8;
	}
	else if (sscanf(p, "#%04x%04x%04x", r, g, b) == 3) {
		*r >>= 8;
		*g >>= 8;
		*b >>= 8;
	}
	else if (sscanf(p, "#%02x%02x%02x", r, g, b) == 3)
		;
	else if (sscanf(p, "%d,%d,%d", r, g, b) == 3)
		;
	else if (sscanf(p, "cmy:%f/%f/%f", &c, &m, &y) == 3
		|| sscanf(p, "cmyk:%f/%f/%f/%f", &c, &m, &y, &k) == 4
		)
	{
		if (c >= 0 && c <= 1 && m >= 0 && m <= 1 && y >= 0 && y <= 1 && k >= 0 && k <= 1) {
			*r = (1 - c) * (1 - k) * 255;
			*g = (1 - m) * (1 - k) * 255;
			*b = (1 - y) * (1 - k) * 255;
		}
		else
			return 0;
	}
	else {
		int coli = -1;
		int len = strlen(p);
		while (len && p[len - 1] == ' ')
			len--;
		for (u_int i = 0; i < nitems(x11colours); i++)
			if (0 == strncasecmp(p, x11colours[i].name, len)) {
				*r = x11colours[i].r;
				*g = x11colours[i].g;
				*b = x11colours[i].b;
				coli = i;
				break;
			}
		if (coli < 0)
			return 0;
	}

	if (*r > 255 || *g > 255 || *b > 255)
		return 0;

	log_debug("%s: %s = %02x%02x%02x", __func__, p, *r, *g, *b);
	return (1);
}
```

**Comment by nicm** [comment]
Can you give me this as a diff file please?

**Comment by mintty** [comment]
Attached:
[tmux-colour-formats.zip](https://github.com/tmux/tmux/files/5975392/tmux-colour-formats.zip)
You'll have to integrate the generation of the include file into the tmux build environment.
Generation command is included in the source as a comment.

**Comment by nicm** [comment]
Thanks, mostly looks good. Here is a diff with a few changes from yours:

- Move the colour names list into a function in colour.c.
- Make input_osc_parse_colour return a colour number instead of separate R, G, B which means it can be more compact.
- Join together some identical cases in the input_osc_parse_colour.

[tmux-colour-names.diff.txt](https://github.com/tmux/tmux/files/5975499/tmux-colour-names.diff.txt)

I am not particularly wild about about adding 600 LOC and 30 KB in text for colour names... maybe tmux can load X11's rgb.txt, but it isn't always in the same place. I'll think about this.

Thanks for the test files, they all parse but I didn't check it was generating the right colours - will do that next week and build them into a regression test.

**Comment by mintty** [comment]
Thanks;
test files should all produce the same colour, so they can easily be tested visually.
Except x0 of course for colour reset; note it contains two sequences as I found the reset sequences (OSC 111 in this case) are not supported, maybe that could be added too.

**Comment by mintty** [comment]
... and, by the way, X11 rgb.txt is not necessarily installed at all, so including the table is the safer way. What I do for my projects with such tables is to provide a generation script (or make rule) but still put them in the repository, so nobody will have trouble with them when building from sources. There exist libraries to include and work with tables in compressed format but I didn't spend time to deal with their API.

**Comment by nicm** [comment]
Yeah I know it might not be installed, if it doesn't exist then people would have to add it. But it isn't ideal.

I don't see any need to generate it at all, it has changed about three times in the last 20 years.

**Comment by nicm** [comment]
Here is an updated diff [c.diff.txt](https://github.com/tmux/tmux/files/5980618/c.diff.txt):

- Fix some errors from my previous on (wrong return value from `input_osc_parse_colour` and some other bits);
- Add regression test.
- Add OSC 111.
- Do not include 200 greys in the table, generate them instead.
- Accept X11 colour names for tmux colours where we do not already have a colour name (`set -g status-bg 'DarkOrange'`).

The CMYK tests are not quite the same colour as the rest due to rounding but I doubt anyone in the world cares about CMYK in the terminal so I am not inclined to worry about it.

**Comment by nicm** [comment]
I have applied this to OpenBSD now, it should be in GitHub later. Thanks!

**Comment by mintty** [comment]
Thank you very much. For your info, I added support for SGR CMY(K) variants (and consequently OSC CMY(K) redefinitions) to mintty as they are listed in standard ISO 8613-6, filling the gap between SGR 38/48:2:... and :5:..., more or less for fun. The standard is also known as ITU-T T.416 and can be downloaded for free from https://www.itu.int/ITU-T/recommendations/rec.aspx?id=2546.

**Comment by nicm** [comment]
Thanks. So what else are you missing from OSC/SGR? OSC 50?

**Comment by mintty** [comment]
I'd say, OSC 50 is nice-to-have and might be troublesome to implement (as you may need to remember font names, which may not be available when taking up a suspended session...).
For SGR, I'd add CMY(K) support for the balance (with OSC); I took a look but the code looks a bit more fiddly there, so I didn't come up with a quick patch.
Otherwise, I'd appreciate if you take a look through the list linked above (https://github.com/mintty/mintty/wiki/Tips#text-attributes-and-rendering). I don't have a complete overview what tmux knows already, but I guess the mintty-specific attributes and sub-attributes shadowed and overstrike, superscript and subscript, and emoji style aren't included.
Also running tmux, I see the following do not work:
italic, blinking, rapidly blinking, doubly underlined via SGR 21, and alternative fonts.
Thanks for considering.

**Comment by nicm** [comment]
Yes for OSC 50 I am concerned about not being able to reapply it after reattaching. We could just remember the font name I guess. What applications are you using that use this?

I don't think we should add CMYK SGR until there are at least a few relatively popular applications using it. I did take a look at the text attributes list but I don't see anything there we don't have that is widely supported.

**Comment by mintty** [comment]
OK, I would appreciate however the ones mentioned last to work out of the box:
italic (it can be configured somehow but should work by default if the underlying terminals supports it), blinking attributes (rapid may be mapped to normal if the underlying terminal does not have it), maybe the legacy doubly underlined; also alternative fonts 1..10 are only indices to preconfigured fonts, without the complexity considerations of OSC 50.

**Comment by nicm** [comment]
Italics, blinking, double underline are all supported.

For italics you must have `default-terminal` set to `tmux` or `tmux-256color` otherwise tmux will emulate screen (so no italics): `set -g default-terminal tmux-256color`

Blinking works if the terminal outside supports it - does `tmux info|grep blink` show a capability set?

I don't know of any applications that use blinking really, so I'm not sure we need rapid blinking as well. Do you have any in mind?

SGR 21 is possible, I don't think there is a terminfo entry though but we could add an externsion. We could map it to SGR 4:2 if that is present.

**Comment by nicm** [comment]
Yes we could make rapid blinking the same as normal blinking, that's a good idea.

**Comment by mintty** [comment]
Doubly underlined works via SGR 4:2 but not via the legacy SGR 21, mapping would be fine. Some legacy terminals used to take it for non-bold, however, so if you prefer not to support it, that's also OK.
I still don't see blinking work, with default-terminal xterm or mintty.

**Comment by nicm** [comment]
OK here is a diff which makes SGR 6 the same as SGR 5 and SGR 21 the same as SGR 4:2: [x.diff.txt](https://github.com/tmux/tmux/files/5982011/x.diff.txt)

I don't think it is worth adding an extension terminfo capability for SGR 21 - it is enough to map it to SGR 4:2. I don't think there are many terminals that support it or applications that use it, and for the few that are out there, I doubt there are many users who would go to the effort of configuring tmux to send it. And if they wanted to I think they could do it with a suitable `Smulx` entry that ignored everything except 2.

**Comment by nicm** [comment]
For blinking, what does `tmux info|grep blink` inside tmux show?

**Comment by nicm** [comment]
Sorry that was the wrong diff file, [x.diff.txt](https://github.com/tmux/tmux/files/5982023/x.diff.txt)

But I will just apply it in a minute anyway I think.

**Comment by mintty** [comment]
tmux info says: no server running on /tmp/tmux-197610/default

**Comment by nicm** [comment]
Run it from a shell inside tmux?

**Comment by mintty** [comment]
6: blink: (string) \033[5m
but there is no blinking

**Comment by nicm** [comment]
Weird, I just tried it in xterm and it works for me.

**Comment by nicm** [comment]
What tmux version are you using (`tmux -V`)?

**Comment by mintty** [comment]
tmux next-3.3
Italic works in xterm but not in mintty. Tried set -g default-terminal tmux or xterm or mintty, which are however all mapped to TERM=tmux inside tmux. Also tried TERM=xterm or TERM=mintty with both before running tmux.

**Comment by nicm** [comment]
`default-terminal` has to match tmux* or it will not send italics, regardless of what `TERM` is set to. `TERM` outside needs to have `sitm`/`ritm` which `xterm` normally does.

Can you do this (in mintty where italics aren't working):
~~~~
tmux kill-server
tmux -vv new
printf '\033[5mblink\033[3mitalics\033[0m'
exit
~~~~
Then attach the tmux-server*.log file which should be in the current directory to this issue and I will have a look.

**Comment by mintty** [comment]
[tmux-no-blink.zip](https://github.com/tmux/tmux/files/5982871/tmux-no-blink.zip)
(italics work with given default-terminal)

**Comment by nicm** [comment]
As far as I can tell tmux is writing SGR 5 to the external pty:
~~~~
1613407110.032417 input_parse_buffer: %0 ground, 24 bytes: \033[5mblink\033[3mitalics\033[0m
...
1613407110.032492 /dev/pty0: \033[5m
1613407110.032503 /dev/pty0: blink
1613407110.032512 /dev/pty0: \033[3m
1613407110.032521 /dev/pty0: italics
~~~~
Can you check if mintty is receiving it?

**Comment by nicm** [comment]
I assume it works outside tmux? Is there anything that tmux could be sending that would disable it?

**Comment by mintty** [comment]
Hmm, it seems that blinking is broken on one of my systems. On another, it also works inside tmux, so we can settle the issue here. Sorry, it's mysterious, though.

**Comment by nicm** [comment]
OK, thanks.
