### ISSUE TITLE
sh autogen.sh fails with error - possibly undefined macro: AC_SEARCH_LIBS

### ISSUE THREAD

**Issue by Jonher937** [tmux/tmux#257]
Today I cloned the git repo and followed the steps on the wiki, however, on the third step (autogen.sh) it failed with the error message below.

```shell
➜ P4n73r @ tmux:git:(master) sh autogen.sh
Useless use of /d modifier in transliteration operator at /usr/local/share/automake-1.9/Automake/Wrap.pm line 60.
configure.ac: installing `etc/install-sh'
configure.ac: installing `etc/missing'
configure.ac:8: installing `etc/config.guess'
configure.ac:8: installing `etc/config.sub'
Makefile.am: installing `etc/compile'
Makefile.am: installing `etc/depcomp'
configure.ac:109: error: possibly undefined macro: AC_SEARCH_LIBS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1
autoreconf failed
```

I have also tried to run "autoreconf -i --force" as mentioned in #72  

```shell
➜ P4n73r @ tmux:git:(master) autoreconf -i --force
configure.ac:109: error: possibly undefined macro: AC_SEARCH_LIBS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1
```

If i run "aclocal", "sh autogen.sh" seems to be error-free, but then the next step breaks instead...
```shell 
➜ P4n73r @ tmux:git:(master) sh autogen.sh
Useless use of /d modifier in transliteration operator at /usr/local/share/automake-1.9/Automake/Wrap.pm line 60.
Useless use of /d modifier in transliteration operator at /usr/local/share/automake-1.9/Automake/Wrap.pm line 60.
➜ P4n73r @ tmux:git:(master)
➜ P4n73r @ tmux:git:(master) ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
-- Cut away some log, see link below block for full output --
checking for library containing clock_gettime... no
./configure: line 4582: syntax error near unexpected token `newline'
./configure: line 4582: `PKG_CHECK_MODULES('
```

Full output of "./configure" can be found here: https://gist.github.com/Jonher937/5834deb07e75c26b7b8a

I have verified that pkgbuild is installed on my Mac running OS X 10.11.2
Please let me know if you require any additional info.

Thank you in advance!

**Comment by ThomasAdam** [comment]
Install pkg-config

**Comment by Jonher937** [comment]
I have it installed, tried reinstalling xcode and it's command line tools as well, no difference.
```shell
➜ P4n73r @ tmux:git:(master) sh autogen.sh
Useless use of /d modifier in transliteration operator at /usr/local/share/automake-1.9/Automake/Wrap.pm line 60.
configure.ac: installing `etc/install-sh'
configure.ac: installing `etc/missing'
configure.ac:8: installing `etc/config.guess'
configure.ac:8: installing `etc/config.sub'
Makefile.am: installing `etc/compile'
Makefile.am: installing `etc/depcomp'
configure.ac:109: error: possibly undefined macro: AC_SEARCH_LIBS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1
autoreconf failed
➜ P4n73r @ tmux:git:(master) pkg-config --version
0.28
```

Is there anything else I can check?

**Comment by ThomasAdam** [comment]
No idea.  I don't know (nor want to know!) anything about OSX.  See this though:

http://superuser.com/questions/421396/cant-compile-tmux-with-iterm-support

But we're way outside the scope of your original question.

**Comment by kenshinji** [comment]
@ThomasAdam  I ran into the same problem with @Jonher937 , after installing `pkg-config`, it works!

**Comment by jakirkham** [comment]
Had the same issue on OS X that the OP reported in the first traceback. Needed the following to build it correctly. Then everything went smoothly.

* `autoconf`
* `automake`
* `m4`
* `libtool`
* `libevent`
* `perl`
* `pkg-config`

**Comment by raphnguyen** [comment]
@jakirkham's tip saved me from endless debugging.

**Comment by PrithivirajDamodaran** [comment]
@jakirkham thanks a heap !

**Comment by sylvaine** [comment]
@jakirkham: in order to solve my pb, I also had to install `perl-Event-Lib` (perl wrapper around libevent).

**Comment by wagnerikeda** [comment]
Thank you very much @jakirkham !
I successfuly built tmux on MacOS 10.13.
I installed from source all the packages you mentioned, except Perl.
I bumped into [https://github.com/tmux/tmux/issues/72](url) which was solved with **autoreconf -i --force && ./configure** as mentioned by @ThomasAdam there.

**Comment by victor-yarema** [comment]
Some info here - https://github.com/tmux/tmux/issues/602 .

**Comment by mikepiman** [comment]
> Had the same issue on OS X that the OP reported in the first traceback. Needed the following to build it correctly. Then everything went smoothly.
> 
> * `autoconf`
> * `automake`
> * `m4`
> * `libtool`
> * `libevent`
> * `perl`
> * `pkg-config`



> Had the same issue on OS X that the OP reported in the first traceback. Needed the following to build it correctly. Then everything went smoothly.
> 
> * `autoconf`
> * `automake`
> * `m4`
> * `libtool`
> * `libevent`
> * `perl`
> * `pkg-config`

This finally allowed libwebp to build!  Thank you!  So it seems that my MSYS environment could be more complete out of the box.

I simply updated all in that list, by uttering:
pacman -S autoconf
..
and so on, for all in that list.
