### ISSUE TITLE
Line wrapping with regex search not working as expected

### ISSUE THREAD

**Issue by aaronjensen** [tmux/tmux#2570]
### Issue description

It seems like search wrapping (i.e. #1935) is partially working but doesn't work properly with wildcards.

For example:

```sh
echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab
```

Ensure it's wrapping by sizing your pane accordingly.

Then search backward for `a*b`.

The first match will be only the second half of the wrapped line. The second match will be only the first half of the wrapped line. Neither of these will do the right thing when copy-pipe is used.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux next-3.3
* Platform (`uname -sp`): Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color inside and xterm-256color-italic outside
* Logs from tmux (`tmux kill-server; tmux -vv new`): I did this, but don't know where the logs go

**Comment by nicm** [comment]
I am not sure if this is meant to work yet, @topcat001?

**Comment by aaronjensen** [comment]
Another thing of note that I forgot to mention is that the highlighting is correct, but, as you can see in this picture, the cursor is at the beginning of the second line, rather than the first. If I hit `n` it unhighlights the second line and only the first is highlighted.

<img width="768" alt="CleanShot 2021-02-16 at 00 49 54@2x" src="https://user-images.githubusercontent.com/8588/108028109-e7662f80-6ff0-11eb-84d2-b05c4138df15.png">

**Comment by topcat001** [comment]
Wrapping support for wildcard searches is not fully done yet. I think I need to go over this case in more detail. I'll report back with an update after I've had a chance to review what was done. Thanks for the examples!

**Comment by topcat001** [comment]
Hi can you please try the attached diff? It should apply cleanly to master.
[a.diff.txt](https://github.com/tmux/tmux/files/6018975/a.diff.txt)

**Comment by aaronjensen** [comment]
Looks to work perfectly for me, that's awesome.

**Comment by nicm** [comment]
Applied now, thanks! Let me know if you see any problems.
