### ISSUE TITLE
tmux pane hangs on entry to specific directories

### ISSUE THREAD

**Issue by jrwrigh** [tmux/tmux#2572]
### Issue description
**Note:** This is more a question than a bug. I doubt tmux has any blame to have for the actual problem, I'm just trying to figure out what to look for.

When opening a new window/pane to a specific directory (so `:neww -c /nobackup/jrwrigh7`), the tmux pane just hangs. Looking at the logs, the server doesn't do anything, it's just waiting to receive input but doesn't get anything. The problem does appear to be shell related, as the behavior is fine on bash, but with it fails with zsh (for versions 5.0.5 and 5.8).

Based on the shell dependence and the logs, it's almost certainly not _really_ a tmux issue, but rather how tmux interacts with zsh. However, I haven't been able to recreate the issue outside of tmux. The directory is perfectly accessible via `cd`, and using `neww -c [...]` for other (supposedly) identically setup directories work as expected. 

So my primary question is how exactly does tmux handle the `-c` flag for `new-window` and `split-window`? Does it pass the path to the shell or "change directory" within the program and then launch the shell (note my knowledge of how C interacts with the system is pretty limited)? Is there a way to recreate this action outside of tmux?

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.1b`
* Platform (`uname -sp`): `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`): _Note these were created with empty config_(`-f /dev/null`)
[tmux-server-15226.log](https://github.com/tmux/tmux/files/5997314/tmux-server-15226.log)
[tmux-out-15226.log](https://github.com/tmux/tmux/files/5997315/tmux-out-15226.log)

**Comment by nicm** [comment]
It just calls chdir after fork but before exec which is entirely standard. It also sets PWD because that helps if the cwd is a symlink. Maybe zsh doesn't like that. Does it still happen if you do:
~~~~
neww -c /whatever -- env -i $SHELL
~~~~
Or:
~~~~
neww -c /whatever -- env PWD= $SHELL
~~~~

**Comment by jrwrigh** [comment]
Well... it works fine now. Been dealing with the issue for two days, debugging all morning, then it decides to work. Oh well.

Probably doesn't mean much, but the first method came up with the following message: `dircolors: no SHELL environment variable, and no shell type option given`, but ultimately did work correctly. The second works without any odd messages. Though both of those results are probably null and void since it works normally now.

Thanks for the quick response though!
