### ISSUE TITLE
Vim background detection fails within tmux

### ISSUE THREAD

**Issue by lonelykid** [tmux/tmux#2574]
### Issue description

1. Run tmux in a terminal with dark bg, set TERM to screen-256color.
2. Open vim with default setting.
3. Query `:set backgrond?` shows light

Why matters? 
- This causes light scheme used by default which is hard to read in dark bg

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.1c
* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`). screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`). 
<details>
<summary>tmux-client-70485.log</summary>
```
1613696023.315515 client started (70485): version 3.1c, socket /private/tmp/tmux-501/default, protocol 8
1613696023.315593 on Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64; libevent 2.1.12-stable (select)
1613696023.315647 socket is /private/tmp/tmux-501/default
1613696023.315672 trying connect
1613696023.315708 connect failed: Connection refused
1613696023.315823 lock file is /private/tmp/tmux-501/default.lock
1613696023.315939 flock succeeded
1613696023.315951 got lock (6)
1613696023.315962 trying connect
1613696023.315980 connect failed: Connection refused
1613696023.316693 add peer 0x7ffa46531000: 7 (0x0)
1613696023.319823 sending message 100 to peer 0x7ffa46531000 (4 bytes)
1613696023.319919 sending message 101 to peer 0x7ffa46531000 (16 bytes)
1613696023.319943 sending message 102 to peer 0x7ffa46531000 (13 bytes)
1613696023.319966 sending message 108 to peer 0x7ffa46531000 (15 bytes)
1613696023.320018 sending message 104 to peer 0x7ffa46531000 (0 bytes)
1613696023.320046 sending message 107 to peer 0x7ffa46531000 (4 bytes)
1613696023.320071 sending message 105 to peer 0x7ffa46531000 (37 bytes)
1613696023.320091 sending message 105 to peer 0x7ffa46531000 (21 bytes)
1613696023.320106 sending message 105 to peer 0x7ffa46531000 (1271 bytes)
1613696023.320134 sending message 105 to peer 0x7ffa46531000 (9 bytes)
1613696023.320153 sending message 105 to peer 0x7ffa46531000 (25 bytes)
1613696023.320169 sending message 105 to peer 0x7ffa46531000 (57 bytes)
1613696023.320185 sending message 105 to peer 0x7ffa46531000 (19 bytes)
1613696023.320204 sending message 105 to peer 0x7ffa46531000 (13 bytes)
1613696023.320220 sending message 105 to peer 0x7ffa46531000 (22 bytes)
1613696023.320236 sending message 105 to peer 0x7ffa46531000 (66 bytes)
1613696023.320255 sending message 105 to peer 0x7ffa46531000 (83 bytes)
1613696023.320288 sending message 105 to peer 0x7ffa46531000 (34 bytes)
1613696023.320321 sending message 105 to peer 0x7ffa46531000 (156 bytes)
1613696023.320350 sending message 105 to peer 0x7ffa46531000 (54 bytes)
1613696023.320378 sending message 105 to peer 0x7ffa46531000 (34 bytes)
1613696023.320399 sending message 105 to peer 0x7ffa46531000 (19 bytes)
1613696023.320551 sending message 105 to peer 0x7ffa46531000 (14 bytes)
1613696023.320597 sending message 105 to peer 0x7ffa46531000 (19 bytes)
1613696023.320620 sending message 105 to peer 0x7ffa46531000 (8 bytes)
1613696023.320674 sending message 105 to peer 0x7ffa46531000 (20 bytes)
1613696023.320707 sending message 105 to peer 0x7ffa46531000 (16 bytes)
1613696023.320730 sending message 105 to peer 0x7ffa46531000 (24 bytes)
1613696023.320754 sending message 105 to peer 0x7ffa46531000 (20 bytes)
1613696023.320772 sending message 105 to peer 0x7ffa46531000 (22 bytes)
1613696023.320823 sending message 105 to peer 0x7ffa46531000 (30 bytes)
1613696023.320850 sending message 105 to peer 0x7ffa46531000 (11 bytes)
1613696023.320865 sending message 105 to peer 0x7ffa46531000 (8 bytes)
1613696023.320881 sending message 105 to peer 0x7ffa46531000 (32 bytes)
1613696023.320897 sending message 105 to peer 0x7ffa46531000 (19 bytes)
1613696023.320915 sending message 105 to peer 0x7ffa46531000 (63 bytes)
1613696023.320932 sending message 105 to peer 0x7ffa46531000 (46 bytes)
1613696023.320949 sending message 105 to peer 0x7ffa46531000 (7 bytes)
1613696023.320963 sending message 105 to peer 0x7ffa46531000 (11 bytes)
1613696023.320978 sending message 105 to peer 0x7ffa46531000 (54 bytes)
1613696023.320993 sending message 105 to peer 0x7ffa46531000 (14 bytes)
1613696023.321025 sending message 105 to peer 0x7ffa46531000 (22 bytes)
1613696023.321047 sending message 106 to peer 0x7ffa46531000 (0 bytes)
1613696023.321061 cmd_pack_argv: argv[0]=new
1613696023.321092 sending message 200 to peer 0x7ffa46531000 (8 bytes)
1613696023.321106 client loop enter
1613696023.406997 peer 0x7ffa46531000 message 207
1613696023.407032 sending message 208 to peer 0x7ffa46531000 (0 bytes)
1613696037.316242 peer 0x7ffa46531000 message 203
1613696037.316287 sending message 205 to peer 0x7ffa46531000 (0 bytes)
1613696037.316726 peer 0x7ffa46531000 message 204
1613696037.316753 client loop exit
```
</details>

[tmux-server-70487.log](https://github.com/tmux/tmux/files/6006890/tmux-server-70487.log)

Related:
https://github.com/tmux/tmux/issues/384
https://github.com/tmux/tmux/issues/699
https://github.com/vim/vim/issues/869

I open again because I figured out Vim background color detection is the problem, which you could possibly solve by adding support for bg query control sequence.

**Comment by lonelykid** [comment]
I tried this patch. https://github.com/tmux/tmux/issues/1919 . The control sequence does not seem to work. If it could work, I think it would be easy for vim developers to add support for tmux.

**Comment by nicm** [comment]
It only work if you have set the background, because otherwise tmux does not know it.

**Comment by lonelykid** [comment]
Never considerred this. Tmux inherits color of underlying terminals. I tried `set -g window-style 'fg=yellow,bg=blue'`. `'\e]11;?\007'` still shows no results.

**Comment by nicm** [comment]
I don't think this was added until after 3.1, so it will be in 3.2.

**Comment by lonelykid** [comment]
OK. I applied your patch in that issue to the version at that time. It seems not working. Anyway, thanks for your work. Hope 3.2 will fix this issue.

**Comment by nicm** [comment]
You can try to build from master.

**Comment by lonelykid** [comment]
I tried `set -g window-style bg=red` and `select-pane -P 'bg=red'` not working
<img width="912" alt="Screen Shot 2021-02-19 at 1 53 29 AM" src="https://user-images.githubusercontent.com/2936633/108468937-72dffa80-7255-11eb-9f70-e2caa6c2d464.png">

**Comment by nicm** [comment]
`red` is not an RGB colour, so tmux doesn't know what colour it is. Set it to `#ff0000`.

I guess we could make it send the default RGB value for red, but terminals all have different palettes so it would only occasionally be accurate.

**Comment by nicm** [comment]
tmux colour names are the same as X11 for colours less than 8 (so the default terminal palette), so we could just return that (ie `red`). We assume terminals support the default xterm 256 colour palette, so we know the RGB values for those.

The difficult ones are the default colour (8) and the bright colours (90-97) which do not have a clear X11 equivalent, and tmux doesn't know the RGB colour.

**Comment by lonelykid** [comment]
Thank you! hex RGB works! 256 colors like `colour233` is not working, because that also depends on the palette.

I doubt Vim can handle color names like 'Red'

https://github.com/vim/vim/blob/master/src/testdir/test_termcodes.vim#L1558-L1600

Inaccurate RGB is OK for determining dark or light in Vim. So far Vim is the only place I want to query bg. But other people might want more accurate results.

**Comment by nicm** [comment]
This will make the 256 colour palette work as well: [x.diff.txt](https://github.com/tmux/tmux/files/6020623/x.diff.txt)

I don't see a solution for the default/terminal background unless we query the terminal and I don't think that is worth it for something hardly any applications use. It won't tell us the palette for the ANSI and aixterm colours anyway.
