### ISSUE TITLE
Can't use tmux properly with large outputs

### ISSUE THREAD

**Issue by PenTestical** [tmux/tmux#2576]
### Issue description

The tmux output, especially when trying to scroll up inside the terminal, get's cutted. But sometimes even without any scrolling, if the output is too large to fit the screen. When doing an nmap scan, a few parts of the results are splitted (see image). How do I fix this in a manner that I can use my mouse (or at least keyboard) to scroll up and down? If possible, I would like to use my terminal as it was before using tmux (like scrolling with my mouse and see the history). I already put this line into my config file:

`set -g history-limit 10000
`
which has not helped much.

I'm pretty new to tmux and this might be a noob question, so thanks in advance! Researched a while and could not solve this on my own.

![image](https://user-images.githubusercontent.com/57206134/108604209-c57ffa80-73ac-11eb-8096-9351ff1c4534.png)

### Required information

* tmux 3.1c
* Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux
* $TERM inside: screen, and outside of tmux: xterm-256color
* Logs from tmux: 
[tmux-out-9856.log](https://github.com/tmux/tmux/files/6015935/tmux-out-9856.log)
[tmux-server-9856.log](https://github.com/tmux/tmux/files/6015936/tmux-server-9856.log)
[tmux-client-9854.log](https://github.com/tmux/tmux/files/6015937/tmux-client-9854.log)
* tmux configuration file:
[tmux_config.txt](https://github.com/tmux/tmux/files/6015939/tmux_config.txt)

**Comment by nicm** [comment]
You need to use copy mode to look back at the history https://github.com/tmux/tmux/wiki/Getting-Started#copy-and-paste. If you turn on the mouse you will be able to enter it and scroll with the mouse wheel and select text with the mouse.

**Comment by PenTestical** [comment]
Wow, thank you! I can use PgUp and PgDown button now to scroll, but it jumps a bit "too much". May I ask, how I can customize this to just a half of it?

**Comment by nicm** [comment]
You can change the key bindings in copy mode to do halfpage-up or cursor-up/scroll-up instead of page-up.
