### ISSUE TITLE
Core dump with commit 0cd5ed9

### ISSUE THREAD

**Issue by alealv** [tmux/tmux#2577]
### Issue description

Latest commit on master generates core dump

```sh
tmux on  master 
➜ tmux ls
[1]    76281 segmentation fault (core dumped)  tmux ls
```

### Required information

Please provide the following information:

* tmux version: master branch 
* Platform: Linux x86_64
* $TERM inside and outside of tmux: xterm-256color

**Comment by nicm** [comment]
Please try now.

**Comment by alealv** [comment]
It works fine now!
Sorry for the late response.
