### ISSUE TITLE
crash when running "tmux display -a" in st terminal

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2583]
### Issue description

Tmux crashes when running `tmux display -a` in the st terminal.

To reproduce, open a st terminal.  Then, run these shell commands:

    tmux -Lx -f/dev/null
    tmux display -a

### Required information

 - `$ tmux -V`: tmux next-3.3, commit a7d4703bfe822f58dd14ee26cb9137d23f967a8c
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs:

[tmux-client-30043.log](https://github.com/tmux/tmux/files/6053725/tmux-client-30043.log)
[tmux-out-30045.log](https://github.com/tmux/tmux/files/6053726/tmux-out-30045.log)
[tmux-server-30045.log](https://github.com/tmux/tmux/files/6053727/tmux-server-30045.log)

 - [backtrace](https://github.com/tmux/tmux/files/6053723/backtrace.txt)
 - [`$ tmux info`](https://github.com/tmux/tmux/files/6053724/tmux.info.log)

It looks like a regression introduced in one of these commits:

    There are only 'skip'ped commits left to test.
    The first crash commit could be any of:
    8986c8dfcd0083e5c767b8a247c119a25e1f8093
    e858270006a9041b9016ed9e6cc12d622ac8fe31
    cb7e6698f3241cecfac31a045b907988a4c286f1
    We cannot bisect more!

I suspect it's [this one](https://github.com/tmux/tmux/commit/e858270006a9041b9016ed9e6cc12d622ac8fe31).

**Comment by lacygoill** [comment]
> terminal: xterm
   > $TERM outside tmux: xterm-256color

Sorry, I meant:

    terminal: st
    $TERM outside tmux: st-256color

Also, here is the output of [`$ infocmp -1x`](https://github.com/tmux/tmux/files/6053734/infocmp.txt) in st.

**Comment by nicm** [comment]
Should be fixed as soon as GitHub syncs up, thanks! Here is the change:
~~~~
--- format.c    26 Feb 2021 21:53:41 -0000      1.279
+++ format.c    27 Feb 2021 06:28:16 -0000      1.280
@@ -1368,8 +1368,11 @@ format_cb_client_termname(struct format_
 static void *
 format_cb_client_termtype(struct format_tree *ft)
 {
-       if (ft->c != NULL)
+       if (ft->c != NULL) {
+               if (ft->c->term_type == NULL)
+                       return (xstrdup(""));
                return (xstrdup(ft->c->term_type));
+       }
        return (NULL);
 }
