### ISSUE TITLE
getdtablesize still defined without sysconf replacement in imsg.c - causes compile errors

### ISSUE THREAD

**Issue by Zackptg5** [tmux/tmux#2585]
### Issue description

When cross-compiling for Android using the NDK, compile will fail due to the presence of getdtablesize in comat/imsg.c. getdtablesize has been replaced with sysconf(_SC_OPEN_MAX) since lollipop (api 21) and so doing that replacement led to a successful compile.

In compat/closefrom.c, this has already been addressed with the following:
```
#ifdef HAVE_SYSCONF
	maxfd = sysconf(_SC_OPEN_MAX);
#else
	maxfd = getdtablesize();
#endif /* HAVE_SYSCONF */
```
So can't the same kind of thing be added to imsg.c and then the variable used instead of the direct call? I attached a modded imsg.c with what I was thinking - compiles fine with it
[imsg.c.txt](https://github.com/tmux/tmux/files/6055020/imsg.c.txt)

### Required information

Please provide the following information:

* tmux: version 3.1c
* Platform: aarch64-linux-android
* $TERM inside and outside of tmux: n/a
* Logs from tmux: n/a

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by Zackptg5** [comment]
> Does this still happen with master?

Yup, same thing: https://github.com/tmux/tmux/blob/master/compat/imsg.c#L76

**Comment by nicm** [comment]
No, try master please.

**Comment by nicm** [comment]
This should be fixed by 991d5a9c74f658225cc82e0b08d168c092eefdbe.

**Comment by Zackptg5** [comment]
Ok, looks like it should be fixed by that commit. I can't compile with master though, looks a check was added to clang that's preventing me from cross-compiling at line 5989 of configure so I can't test it :/
Looks fine though so I'll close it

**Comment by nicm** [comment]
Your configure is generated by autogen.sh and it will be different from everyone else so line 5989 doesn't help, what is on that line?

**Comment by Zackptg5** [comment]
It's this part:
```
# Clang sanitizers wrap reallocarray even if it isn't available on the target
# system. When compiled it always returns NULL and crashes the program. To
# detect this we need a more complicated test.
{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for working reallocarray" >&5
printf %s "checking for working reallocarray... " >&6; }`
```
A conditional was added that has it abort if cross compiling. It doesn't really matter though since tmux segfaults anyways, probably just not compatible with the android environment in general
