### ISSUE TITLE
How to set choose-tree window titles to show current working directory?

### ISSUE THREAD

**Issue by lostrouter** [tmux/tmux#2586]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

machine 1
* tmux version (`tmux -V`). tmux 3.1c
* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`).  screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

machine 2
* tmux version (`tmux -V`). tmux 3.1c
* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`).  xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

both machines have oh-my-tmux using default config

on both machines i have a folder underneath user home `~/some/folder`. in each tmux session i have navigated to that folder.

on machine 1, when i open choose-tree  i see 
```
(0)  - 0: 1 windows (attached)
(1)  └─> 1: zsh* (1 panes) "lostrouter.home"
```

on machine 2 i see
```
(0)  - 0: 1 windows (attached)
(1)  └─> 1: zsh* (1 panes) "lostrouter@machinename:~/some/folder"
```

I would like machine 1 to behave the same as machine 2. how can i achieve this?

**Comment by nicm** [comment]
Hi

The bit in `"`s is the pane title which is being set by your shell, you need to configure your shell to do it on both boxes.

**Comment by lostrouter** [comment]
> Hi
> 
> The bit in `"`s is the pane title which is being set by your shell, you need to configure your shell to do it on both boxes.

I'm not exactly sure where to look for that setting. I am using zsh, so would i look in my .zshrc file for that?

**Comment by lostrouter** [comment]
other findings today. 
when in a "plain" iterm session, i get a window title like `lostrouter@machinename:~/some/folder`, but after i open tmux i get window titles like `lostrouter.home`.

**Comment by lostrouter** [comment]
found the answer today.

`set -g default-terminal "xterm-256color"`
