### ISSUE TITLE
tmux hangs on select-copy action rarely

### ISSUE THREAD

**Issue by mizhka** [tmux/tmux#2587]
I would like to report this bug report as holder for information because I couldn't gather full debug information to identify root cause. 

### Issue Description

Sometimes (few times a year) tmux can hang when you select text by mouse to copy it into buffer. 
It's hard to reproduce. Next time I will try to generate core dump. 
Backtrace by pstack:

```
2601: /usr/local/bin/tmux
----------------- thread 100621 (running) -----------------
    0x25cc75 in tmux	grid_line_length + 35
    0x290200 in tmux	window_copy_cursor_previous_word_pos + 140
    0x292234 in tmux	window_copy_synchronize_cursor_end + 84
    0x291edd in tmux	window_copy_set_selection + 5d
    0x290d64 in tmux	window_copy_scroll_down + a4
    0x290793 in tmux	window_copy_cursor_up + 93
    0x2948fd in tmux	window_copy_cmd_scroll_up + 2d
 0x7fffffffdc18 ????????
    0x247b7a in tmux	cmd_send_keys_exec + 17a
    0x245007 in tmux	cmdq_next + 377
    0x27a45d in tmux	server_loop + 4d
         0x1 ????????
    0x279d2d in tmux	server_start + 1fd
    0x23575a in tmux	client_main + 40a
    0x282cf2 in tmux	main + 772
    0x232e80 in tmux	_start + 100
```

It looks like infinite loop inside window_copy_cursor_previous_word_pos / window_copy_synchronize_cursor_end

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.1c
* Platform (`uname -sp`): FreeBSD amd64
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`): weren't gathered

**Comment by nicm** [comment]
This is already fixed in master.

**Comment by mizhka** [comment]
Sorry. Thank you for quick reply.
