### ISSUE TITLE
windows: AF_UNIX with ancillary data is not supported

### ISSUE THREAD

**Issue by skyline75489** [tmux/tmux#2588]
The WinSocks2 API has terrible support for AF_UNIX. Basically you can't use `sendmsg` or `recvmsg` with `AF_UNIX` type of socket. While `send` and `recv` work, ancillary data wrapped in `CMSG_DATA` is not available.

This is the first big blocking issue for Windows port, I guess.

See: https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/#unsupportedunavailable

**Comment by nicm** [comment]
You will need to pass control of the terminal to server from client. On Unix this is by passing the file descriptor, Cgywin we just reopen the client's pty device in the server by name. You will need to figure out a similar mechanism for Windows. This is the only use of file descriptor passing.

**Comment by skyline75489** [comment]
I'm new to the codebase. Please bare with me if I say something stupid. 

So my understanding is that the fd is only thing being passed using ancillary data. If I can pass the fd in some other way, I could bypass the WinSock limitation? This sounds reasonable. 

I dont't quite understand "pass control of the terminal to server from client". My current undetstanding of the code is that client sends commad to the server via imsg interfaces, which is backed by AF_UNIX sockets. The AF_UNIX socket is then based on files. The fd you mentioned, is it just the fd of the actual file, or fd of the socket?

**Comment by nicm** [comment]
The way tmux works is that the server process manages all the terminals on behalf of the client. When you run `tmux new` or `tmux attach` you are starting a new tmux client process. When it is started, that client process has a controlling terminal it can access both through the `/dev/tty` device which is connected to the terminal of the process that opens the device, and usually through the stdin, stdout and stderr file descriptors. With tmux, the client needs to let the server manage (that is, read and write from) its controlling terminal. On Unix, this done by passing a file descriptor for the client's terminal from client to server with `SCM_RIGHTS`.

It isn't required that it be passed over the socket. On Cygwin, which does not have working `SCM_RIGHTS` either, we just pass the *name* of the terminal device (eg `/dev/ttyp7` or whatever) from client to server and the server then opens that device itself.

So you don't necessarily need to pass a file descriptor around, but you need some way for the server to take control of the terminal where the client was started. The end result must be that the server has file descriptor which it can read from and write to to communicate with the client's terminal. It doesn't matter exactly what mechanism it uses to get it.

**Comment by nicm** [comment]
Let me know if you have any other questions about this.
