### ISSUE TITLE
[feature request] Add zoom option to split-window.

### ISSUE THREAD

**Issue by alanxoc3** [tmux/tmux#2591]
I have a use case where I want a pane zoomed in when it's created. Technically, I'm able to achieve this like so:
```bash
tmux split-window 'tmux resize-pane -Z; fzf'
```

But, I can visually tell that for a split second, fzf is using the non-zoomed size before the `resize-pane -Z` is processed. It would be nice if there was a '-Z' option for split-window. That way the pane size could be maximized at startup.

I noticed that the zoom option was added to a few other subcommands over time. I think this is another subcommand that could benefit from that option.

**Comment by nicm** [comment]
I am OK with having this.

**Comment by nicm** [comment]
Try this please: 
[tmux-splitw-Z.diff.txt](https://github.com/tmux/tmux/files/6069631/tmux-splitw-Z.diff.txt)

**Comment by alanxoc3** [comment]
Thanks for the quick response. I tried that patch out & it almost worked. Now when I startup programs, it seems to use the entire screen except for one line initially. Idk how to explain it, here's an asciinema recording:

https://asciinema.org/a/tf4AMuFUsucWnHzWq3Mif2bpr

You can see it goes down 1 line after about half a second with a few different fullscreen apps.

**Comment by nicm** [comment]
Is this better? 
[tmux-splitw-Z-2.diff.txt](https://github.com/tmux/tmux/files/6075948/tmux-splitw-Z-2.diff.txt)

**Comment by alanxoc3** [comment]
No, that seems to behave the same as the previous patch...

**Comment by nicm** [comment]
Show me server log from reproducing this please with the patch applied, preferably with no config (`tmux -Ltest -vv -f/dev/null new`).

**Comment by alanxoc3** [comment]
Here it is: https://gist.github.com/alanxoc3/903c534b68ba0ce9a77c64a6c49e2d35

My keystrokes were something like:
```
./tmux split-window -Z vi
:q
<ctrl>+d
```

**Comment by nicm** [comment]
Hmm, does this help: 
[tmux-splitw-Z-3.diff.txt](https://github.com/tmux/tmux/files/6107509/tmux-splitw-Z-3.diff.txt)

**Comment by alanxoc3** [comment]
Yep, that worked perfectly. Thanks for figuring it out.

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
