### ISSUE TITLE
3.2 release candidates discussion (part 2)

### ISSUE THREAD

**Issue by nicm** [tmux/tmux#2592]
### Ask or discuss any quick questions here about 3.2 release candidates only please.

Bug reports please open a new issue with full information, see [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md).

3.2-rc is a release candidate for 3.2.

**[The CHANGES file is here](https://raw.githubusercontent.com/tmux/tmux/3.2-rc/CHANGES).**

---

There will be a **lot** of changes in this release, these are the most notable, for more see the CHANGES file:

- How data is sent to control mode clients has been completely revamped to both be more fair with multiple panes and to prevent huge amounts of data being backed up; this feature is used by default when tmux is attached with the latest iTerm2 nightly builds.

- Configuration file parsing has changed slightly: the contents of the new {} syntax introduced in 3.1 must now be valid tmux command syntax; and to allow formats to be annotated, strings given with quotes may now contain newlines (leading spaces and comments are stripped).

- A new customize mode available with `C-b C` (`C-b S-c`) which allows options and key bindings to be browsed and changed interactively.

- Support for extended keys offered by some terminals (xterm, mintty, iTerm2), see https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys.

- A `pane-border-lines` option to change the characters used to draw the pane border separators.

- How UTF-8 data is stored has been rewritten to reduce memory use for characters in the BMP.

- The message log (`C-b ~`) has been changed to be per server instead of per client and to have some useful content.

- Client flags have been extended (`refresh-client -F` becomes `-f` and also added for `attach-session` and `new-session`), and a `read-only` flag added (same as `-r` to `attach-session`).

- A new `active-pane` client flag that if given allows a client to have its own active pane for each window rather than being tied to the server's active pane.

- Improved `command-prompt` completion including showing a menu of completions.

- All style options can now be formats, for example the default `pane-active-border-style` now changes colour depending on `pane_in_mode` and `synchronize-panes`.

- Search match count has come back in copy mode, as well as performance improvements and additional styles for marking of search terms.

- Try `$XDG_CONFIG_HOME/tmux/tmux.conf` as well as `~/.config/tmux/tmux.conf`.

- Window and pane hooks such as `window-layout-changed` and `pane-exited` are now window or pane options instead of session options.

- `copy-pipe` and friends can now be given with no arguments in which case they get the command from a new `copy-command` option. The default copy commands all now use `copy-pipe`. This makes it much easier to configure `copy-pipe` for all copy key bindings.

- Terminal detection and feature code has been rewritten. tmux now collects sets of related terminfo(5) capabilties together with sensible default values into named "terminal features" which makes them easier to configure via a new `terminal-features` option or `-T` flag to tmux itself.  tmux can detect and will automatically configure a number of common, modern terminal emulators.

- Support for per-client overlay popups with a new `display-popup` command. A popup is also used for an `e` key binding in buffer mode to edit a buffer using the editor given in the new `editor` option (filled in from the `EDITOR` or `VISUAL` environment variables by default).

- `DoubleClick` and `TripleClick` mouse key bindings have changed so that only one is fired. Behaviour similar to the old double-click key binding is now available as `SecondClick`. There are now default double- and triple-click bindings to copy a word or line, and a default middle-click binding to paste the top buffer.

- When a server socket is given with `-S`, it is now created with umask 177 rather than 117.

---

**Note the following known potentially-incompatible changes:**

- The {} syntax added in tmux 3.1 has changed so that the contents must follow the syntax of tmux commands.

- The `DoubleClick` key binding is not fired on the way to `TripleClick`; only one is fired. The new `SecondClick` key binding behaves similarly to the old `DoubleClick`.

- `status-fg` and `status-bg` are now applied before `status-style` rather than instead of; this means that if either is set to `default` the `status-style` colour will be used. To fix, replace `status-bg default` with `status-style bg=default`.

**Comment by nicm** [comment]
Previous issue is https://github.com/tmux/tmux/issues/2280.

**Comment by Aloxaf** [comment]
Hello, may I ask a question about `display-popup`? I noticed that the program in the popup cannot get the remaining user input before the popup starts. 

I'm not sure if I made myself clear. Here is an example.

**original command**

```zsh
sleep 3; seq 10 | fzf
```

Run the command above and type something before fzf starts, fzf will still get those I typed.

**with popup**

```zsh
sleep 3; tmux popup -E "seq 10 | fzf"
```

Now with popup, those characters I typed before popup starts won't be read by fzf. Instead, they are put into my next command line.

Is there any way to solve this problem?

**Comment by nicm** [comment]
No there isn't, tmux has to flush tty input when it starts.

**Comment by sivaramn** [comment]
Popup behaviour seems to be inconsistent with the changes;  it works in wsl ubuntu but not in cygwin

`bind-key -N "Toggle persistent popup shell" \
         -n F4 if-shell -F '#{==:#{session_name},float}' { detach-client } \
         { popup -w70% -h70% -E \         
         'tmux attach -t float || tmux new -s float \; \
         display-message "Press PF4 to toggle floating popup or Ctrl-D to kill it"'\
         }`

This just brings a black floating box in cygwin.

basic details below after `tmux -vv` run
[tmux-server-181.log.gz](https://github.com/tmux/tmux/files/6084815/tmux-server-181.log.gz)

`
   sivaram@DESKTOP:/tmux$ tmux -V
    tmux 3.2-rc
    sivaram@DESKTOP:/tmux$ git status
    HEAD detached at 3.2-rc
    sivaram@DESKTOP:/tmux$ git log
    commit b30989a9649699ba08908a1a9aa08b0ecc7b24d1 (HEAD, tag: 3.2-rc)
    Author: Nicholas Marriott <nicholas.marriott@gmail.com>
    Date:   Mon Jul 6 14:03:33 2020 +0100
    Pull 3.2-rc up to master.

`

**Comment by sivaramn** [comment]
> 
> 
> Can you open a new issue please? I don't want to add 20 comments to this one it is meant for quick questions.

ok, will do

**Comment by nicm** [comment]
Actually before you do that, it looks like your tmux is not new enough. It should say `3.2-rc4`.

**Comment by sivaramn** [comment]
> 
> 
> Actually before you do that, it looks like your tmux is not new enough. It should say `3.2-rc4`.

I dont see `3.2-rc4` when I do a `git tag` on `master`

**Comment by nicm** [comment]
No, I mean, if you had installed the latest 3.2-rc then `tmux -V` would say `3.2-rc4`; master would say `next-3.3`. Are you sure you didn't either not rebuild your tmux from a new enough checkout, not run the right tmux binary, or not kill the old server after upgrading?

**Comment by sivaramn** [comment]
> No, I mean, if you had installed the latest 3.2-rc then `tmux -V` would say `3.2-rc4`; master would say `next-3.3`. Are you sure you didn't either not rebuild your tmux from a new enough checkout, not run the right tmux binary, or not kill the old server after upgrading?

I had to do a `make clean`  and then `make` again to get the tmux version as `3-2-rc4`.  Now I have a different issue, which I will open a new issue for.   The popup hangs if any command output like `ls -al` puts out more than the number of lines of the popup size.  This issue is not there in the wsl instance of `rc4`

**Comment by balta2ar** [comment]
@nicm I wonder if it's possible to include hyperlinks support, see this comment: https://github.com/haya14busa/hyperlink/issues/1#issuecomment-668566537. I'm a little lost about the conclusion in this issue, it's a pretty big read: https://github.com/tmux/tmux/issues/911. Are you waiting for more terminal apps to pick it up?

**Comment by nicm** [comment]
It's not trivial, the code to do it isn't complete and I don't think enough applications support it to make it a priority.

**Comment by kevinhwang91** [comment]
Could you support make the popup become the same size for the pane?  By an option for canceling the border or allowing partial popup outside the tmux window.
For now, the popup with the border can't overlap the target pane completely.

**Comment by nicm** [comment]
I don't really want to allow the border to be customizable. What does it matter if it can't overlap the pane?

**Comment by kevinhwang91** [comment]
I want to capture the content and redirect it to neo/vim's terminal.
I'm not meaning tmux copy mode is not good enough, but I'm more familiar with doing funny thing in neovim.

**Comment by nicm** [comment]
But why not just run the popup in the middle of the screen then? You can still only interact with one popup at a time no matter where it is. It seems like it would just be confusing to make it look like the pane.

**Comment by nicm** [comment]
I'd quite like a command for copy mode to run `editor` in a popup with the selection/full history like `e` in buffer mode does. Although obviously editing/saving it would not do anything.

**Comment by kevinhwang91** [comment]
Make my eyes focus on the target pane.
There is another scenario that is only a single pane in a window, the border makes nvim smaller than the pane.

**Comment by kevinhwang91** [comment]
Thanks:)

**Comment by vbauerster** [comment]
@nicm I have issue with setting up [extended keys](https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys).

Following is a bit of config I have:

```
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -g default-terminal tmux-256color

set -s user-keys[0] "\e[45;5u" # C-_
bind -n User0 lsk
```

iTerm2 is set to report `CSI u` and `TERM=xterm-256color` outside of tmux.

Test with `cat` reports none of the `CSI u` are printed, until I explicitly issue `printf '\033[>4;1m'`.
Is it expected to do extra step with `printf '\033[>4;1m'` to actually enable `CSI u` reporting via tmux?
I'm long user of `CSI u` with tmux 3.1 and it worked seamlessly there. I mean I didn't have to explicitly issue `printf '\033[>4;1m'`.

`User0` binding <kbd>ctrl</kbd><kbd>-</kbd> doesn't work at all no matter if `printf '\033[>4;1m'` issued.
Do I miss something?

**Comment by nicm** [comment]
tmux itself should recognise the extended keys as you have it configured but in order to see them inside tmux, the application inside has to request them with the escape sequence.

**Comment by vbauerster** [comment]
> the application inside has to request them with the escape sequence.

I'm not sure that every application which supports `CSI u` will request for that. For example I use [kakoune](https://github.com/mawww/kakoune/) editor which can handle `CSI u` and it actually worked seamlessly with tmux 3.1. Now I tried tmux 3.2 and surprise my shortcuts don't work anymore. Why not just enable it without explicit request from application?

> tmux itself should recognise the extended keys

Then `User0` binding with extended key in my case should have fired, but it didn't.

**Comment by nicm** [comment]
Applications that want the keys need to turn them on in xterm and tmux is no different.

If you want it to work as before where you need to use `user-keys` then just don't turn `extended-keys` on.

**Comment by nicm** [comment]
Oh actually that won't work because tmux will recogniy them anyway and that will win over `user-keys`. Maybe we should not look for them unless `extended-keys` is on.

**Comment by vbauerster** [comment]
> If you want it to work as before where you need to use `user-keys` then just don't turn `extended-keys` on.

I didn't use `user-keys` before just set it for test purposes. With `extended-keys` set to off `CSI u` sequences still not passed through as before with tmux 3.1. So it looks like that now user is forced to turn `extended-keys` on and then additionally call `printf '\033[>4;1m'` to let `CSI u` sequences to pass through.

**Comment by nicm** [comment]
OK you can't bind `user-keys` to extended keys, you need to bind the correct key instead.

Yes you will need the application to request extended keys using the escape sequence, this is like other terminals.

**Comment by vbauerster** [comment]
Do you aware of any application that is actually requesting for `extended-keys`?

**Comment by nicm** [comment]
emacs

**Comment by nicm** [comment]
Perhaps it is worth making `1` the default if `extended-keys` is on. The problem we had before was that we did not have it behind any option so hundreds of applications suddenly started getting keys they could not understand and people complained. But since you need it change `extended-keys` anyway perhaps that is no issue, although it still might be a pain in the arse for anyone who wanted it only for a couple of applications out of dozens. Why don't you ask kakoune to send the escape sequence?

**Comment by vbauerster** [comment]
> Why don't you ask kakoune to send the escape sequence?

I will. Just trying to understand the purpose of request by application. As you pointed out that:

> hundreds of applications suddenly started getting keys they could not understand

That makes sense. But in that case if application requested for `extended-keys` then it should restore the state back on exit. Does emacs restore the state of a terminal on exit? If not then it pointless as another application which don't understand `extended-keys` may be launched in the same session where `extended-keys` were left on.

**Comment by nicm** [comment]
Not sure what emacs does but tmux turns it off on exit or detach.

I don't know how many problems it could cause to have it on my default with `extended-keys`, it just seems like asking for trouble when it is only a couple of applications and they can just turn it on and off themselves.

**Comment by nicm** [comment]
Maybe emacs doesn't turn it on by default, I'll have a look later.

**Comment by vbauerster** [comment]
What is a key sequence to turn off?

**Comment by nicm** [comment]
Send the same escape sequence but with value of `0` so `\033[>4;0m`. tmux uses extension terminfo capabilities `Eneks` and `Dseks` for this but they are not in any actual entries at this point (tmux sets them up internally for terminals it recognises support this).

**Comment by vbauerster** [comment]
It would be nice to support `user-keys`, so that `set -s user-keys[0] "\e[46;5u"` has effect.

**Comment by nicm** [comment]
Why do you want to use `user-keys` instead of binding the key directly?

**Comment by vbauerster** [comment]
Yes because of less confusion. For example if I want to bind <kbd>ctrl</kbd><kbd>shift</kbd><kbd>.</kbd> what's the right binding `C->` or `C-S-.`? There is a guesswork, instead I would prefer `set -s user-keys[0] "\e[62;5u"` then bind to `User0` key.

**Comment by nicm** [comment]
That does not sound very convincing to me, it will take at most a couple of tries to find the right key, it would take longer to find out what the escape sequence is. It wouldn't do any harm to allow it to work, although I don't know how easy it would be, I'll have to take a look.

**Comment by nicm** [comment]
See how you get on with Kakoune turning it on/off itself and if they don't want to do it or you don't get anywhere get back to me and I will think about it again.

**Comment by ghallberg** [comment]
Sorry for asking a probably stupid question:

Is there a timeline of some kind for a full release of 3.2? I don't know how tmux releases work, but 3.2 has an important fix for me (config loading race condition).

Thanks for the great work!

**Comment by nicm** [comment]
Usually around May and Oct but there were a lot of changes since the last release and doing releases is time consuming so I will see.

**Comment by ghallberg** [comment]
Ok, thank you :) @nicm

**Comment by gitqlt** [comment]
I assume that the shortcut commands like `-ls`, `-lsc`,... have their default FORMAT string accordingly. Could you publish those format strings in the man page and Format Wiki? Thank you.

By the way, you could enable Github Discussions for this repo.
> Discussions 
Discussions is the space for your community to have conversations, ask questions and post answers without opening issues.

**Comment by systemmonkey42** [comment]
When an application which generates lots of output runs in a pane, I find that the entire client can hang for a while without updates.  One of the symptoms is that the cursor will sit in the stop left corner of the screen, even while typing into the active pane. (and the one generating the output volume is inactive)

Hitting ctrl-s in the pane generating the output returns everything to normal, then pressing ctrl-q will see it resume, and after a short while, tmux will start hanging again.

In my case, the remote session is at the other end of a 20Mb/s WAN link.

Can we discuss if and how throttling is performed?   

I would imaging tmux would have an input buffer per pane, and an output buffer to the actual terminal.    Individual panes (which update their internal representation and generate output on the screen) which generate more than some arbitrary amount (or percentage) of traffic must trigger tmux to collect the output, and simply refresh the pane every so often.  Especially if its not the active pane (active pane gets priority)

Clearly, some kind of throttling is done otherwise `cat 500000line_file.txt` wouldn't complete in 5 seconds over a wan link, however when I run rsync as
```
rsync -a --info=progress2  src/ dest/
```
I get very different behaviour.   I suspect it may be related to how it useds carriage return to overwrite the same line repeatedly, rather than newline.

**Comment by nicm** [comment]
Hi

How long does it take for C-s to take effect? Can you switch to other panes or windows?

What is the difference in behaviour between rsync and cat? What if you write the rsync output to a file and then cat that instead of running rsync directly? Are you using master or the latest release candidate (which should have lower output data volume than before for overwriting text)?

Which terminal are you using?

The way it works is (broadly) that tmux monitors the output buffer to the client and if it feels it is too big, it switches to a mode where instead of updating the terminal individually for each change, it redraws it entirely periodically. I can't check now but I believe it is a maximum of 10 times/second, although it will not start another redraw until the data from the previous is consumed so it could be much slower.

**Comment by systemmonkey42** [comment]
> Are you using master or the latest release candidate (which should have lower output data volume than before for overwriting text)?

I'm using master.  Should I test with 3.2-rc?

**Comment by nicm** [comment]
No master is better.

**Comment by systemmonkey42** [comment]
> The way it works is (broadly) that tmux monitors the output buffer to the client and if it feels it is too big, it switches to a mode where instead of updating the terminal individually for each change, it redraws it entirely periodically.

I would say that this matches my experience.  I suspect I was hoping the _pane_ would get the special treatment which reduced the I/O load, and the other panes would be less affected.

I created a test file with 2million lines (250M).  Using _scp_ to transfer the file from the remote host shows 2.5-3MB/s and an ETA of about 3 minutes.

Using `time cat` in a tmux pane under putty takes 5.6 seconds, so clearly tmux is doing a great job.

Replacing all linefeeds with carriage returns (to more closely resemble the output of rsync) took even less time to `cat` at 4.9 seconds.

Capturing `rsync` output to a file, then using `cat` produces no lag, and completes in a few seconds.

I definitely can't fault tmux, its clearly working as designed, so my apologies for the noise.
I will have to look elsewhere for whatever is happening.

Regards

**Comment by nicm** [comment]
I tried to make it per pane but I never got it to work effectively. Although if you have a terminal that supports DECSLRM margins it can make a big difference to scrolling with multiple panes because then tmux does not need to redraw entire panes to scroll.

It is all a balance between throughout and responsiveness, there is no point in a cat taking 30 seconds instead of 60 if you then need to wait for the whole 30 seconds before you can change pane or press C-c.

I'm not really clear exactly what problem you are seeing, but the speed of your terminal can be a factor. xterm is slow. alacritty and rxvt-unicode are fast. Terminals that do a lot of fancy output processing like iTerm2 can be slow or fast depending.

Lots of other things can have an effect too. For example macOS can be slower because its tty buffer size is only 1 KB (rather than 4 KB on most other platforms) which gives tmux fewer opportunities for optimization.

Also the longer pipe and more processes you have between tmux and the terminal then of course the more data can be sitting outside tmux before it realises the terminal can't keep up. That all has to be consumed before tmux can respond to new key presses.

There are a few formats like client_discarded/client_written which will show how much tmux is throwing away due to the client buffer getting too big, although you will probably need to look at the code to work out what they mean exactly. There are also a couple of defines in tty.c which control the switch to redrawing.

**Comment by nicm** [comment]
*Are* you using iTerm2? The symptom of the cursor sitting in the corner with no updates may be a consequence of synchronized updates. Try adding `set -as terminal-overrides 'Sync@'` to .tmux.conf.

**Comment by nicm** [comment]
I mean `set -as terminal-overrides '*:Sync@'` of course.

**Comment by systemmonkey42** [comment]
> _Are_ you using iTerm2? The symptom of the cursor sitting in the corner with no updates may be a consequence of synchronized updates. Try adding `set -as terminal-overrides '*:Sync@'` to .tmux.conf.

No,  its putty under windows.  I am starting to suspect the LAG I was seeing was packet loss/throttling on the WAN side.

**Comment by nicm** [comment]
OK no worries, not that then :-).

**Comment by toddyamakawa** [comment]
> Could you support make the popup become the same size for the pane? By an option for canceling the border or allowing partial popup outside the tmux window.
> For now, the popup with the border can't overlap the target pane completely.

@kevinhwang91 I wrote a plugin [tmux-scratchpad](https://github.com/toddyamakawa/tmux-scratchpad) to do that

**Comment by jorgeOmurillo** [comment]
On Mac Big Sur, v3.1 automatically loaded my config file in `~/.config/tmux/tmux.conf`, but v3.2 doesn't and I need to manually source the configuration to get it working `tmux source-file /Users/myUser/.config/tmux/tmux.conf`. Any help?
