### ISSUE TITLE
status-bg default green in 3.2-rc4

### ISSUE THREAD

**Issue by iovis** [tmux/tmux#2593]
I upgraded from 3.1c to 3.2-rc4 and `set -g status-bg default` renders green instead of transparent (also reproducible in current master):

```tmux
# ~/.tmux.conf
set -g status-bg default
set -g status-fg white
```

3.1c:
![1E549235-6C09-4A09-8121-158CABE99E5E](https://user-images.githubusercontent.com/6660202/109753523-6aba8000-7bb0-11eb-84a0-5800f0283d46.jpeg)

3.2-rc4:
![032B8296-C7D0-43FE-ACB8-D0EF3358FE1B](https://user-images.githubusercontent.com/6660202/109753543-77d76f00-7bb0-11eb-9f2a-385c3a8ef6df.jpeg)

Not sure if I'm doing something wrong or if there's a new way of doing this.

**Comment by nicm** [comment]
You need to use status-style for default, status-bg is now applied after it
instead of instead of it.

**Comment by iovis** [comment]
It worked!

Changing those two lines to the following, seemed to fix the issue:
```tmux
set -g status-style 'bg=default,fg=white'
```

Thanks!

**Comment by nicm** [comment]
Great stuff.
