### ISSUE TITLE
Logging to file with a terminal emulator missing content

### ISSUE THREAD

**Issue by mtwomey** [tmux/tmux#2595]
### Issue description

I'm trying to switch from screen to tmux, but I'm running into this issue. I frequently need to log a remote ssh session to disk for audit purposes. I've typically used the logging feature on my terminal emulator (currently iTerm2) to do this. With screen this works fine, however with tmux - some of the output is not being sent across the wire back to my terminal. When using screen / tmux, I tent to use a single window/pane and switch between shells that way. When I need to log, I enable logging to file in my terminal.

My expectation was that if an application sent data to stdout / stderr (baring any redirection), that data would be sent to my terminal. However, It appears that due to newer performance features in tmux, that is not always the case. I believe this is related to #1019.

I'm posting this issue primarily to log this use case, but also to see if any additional consideration has been given to this and the other use cases where it's desirable to have _all_ data sent to stdout / stderr sent to the terminal.

### Required information

```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 3.1c
screen-256color
```

**Comment by nicm** [comment]
You will need to use tmux's internal features to do this, or in iTerm2 you could possibly use control mode.

**Comment by mtwomey** [comment]
It does seem odd to me that there is no goal to send everything written to stdout to the connecting client. However, I do understand from that other thread / issue that this is indeed not a goal for tmux. This makes things unnecessarily complicated as compared to a non-tmux (or screen based) terminal session.

I will try the patch you suggested in that issue. Please add my desire for an option to disable this behavior to the list of folks who want this capability in case it some day makes sense to pursue to tmux.

**Comment by mtwomey** [comment]
For future folks that run into this: I've created an Ubuntu PPA with the patch suggested in #1019, which solves this problem:

https://launchpad.net/~mtwomey/+archive/ubuntu/tmux-nodrop
