### ISSUE TITLE
cygwin tmux 3.2-rc4 popup issue

### ISSUE THREAD

**Issue by sivaramn** [tmux/tmux#2596]
with `3.2-rc4`  on cygwin, if I do the following sequence of operations, it hangs and doesnt respond to any key inputs and i have forcibly close the `mintty` terminal.  Issue doesnt seem to be there in wsl ubuntu

- launch `tmux --vv new`
- press F4 to launch a popup and enter `ls -al` or `du -h` that causes lots of output , at least more than the popup number of lines
- F4 triggers the following code 
   
[tmux-server-1529.log.gz](https://github.com/tmux/tmux/files/6085616/tmux-server-1529.log.gz)
bind-key -N "Toggle persistent popup shell" \
         -n F4 if-shell -F '#{==:#{session_name},float}' { detach-client } \
         { popup -w70% -h70% -E \
         'tmux attach -t float || tmux new -s float \; \
         display-message "Press PF4 to toggle floating popup or Ctrl-D to kill it"'\
         }
popup freezes and no interaction is possible anymore. smaller commands that show output that fits within the popup size seems to work; the moment large output text is generated,popup freezes.

**Comment by nicm** [comment]
And you are sure this used to work?

Does just the popup freeze or does tmux entirely freeze? If you try without `-E` can you still close the popup with `C-c` or `Escape`?

**Comment by nicm** [comment]
How are you running `ls -al`? Are you doing `tmux popup -- ls -al` or are you doing `tmux popup` and then `ls -la` in the shell? Do both behave the same?

**Comment by sivaramn** [comment]
> And you are sure this used to work?

yes

> 
> Does just the popup freeze or does tmux entirely freeze? If you try without `-E` can you still close the popup with `C-c` or `Escape`?

entire tmux freezes, with or without `-E`. Interesting the blink option that i enabled for tracking windows works.  The entire tmux hangs with no key interaction possible  and I'm left with a hung application with the status blinking.

**Comment by sivaramn** [comment]
> How are you running `ls -al`? Are you doing `tmux popup -- ls -al` or are you doing `tmux popup` and then `ls -la` in the shell? Do both behave the same?

I launch tmux
after I get the shell prompt, i hit F4 to get a popup and wait for the shell prompt  and then enter `ls -al`
previously hitting F4 makes the popup disappear and appear depending on whether it was there or not.  Now am seeing the errors described earlier

**Comment by nicm** [comment]
Can you reproduce if you don't run tmux in the popup but just run a shell and then run ls?

**Comment by sivaramn** [comment]
> Can you reproduce if you don't run tmux in the popup but just run a shell and then run ls?

If i launch tmux and at the shell prompt I do  `tmux popup -- ls -al` , it works; as in I got a popup with the result and hitting `esc` removes the popup in cygwin and in wsl.

it appears now that doing  `tmux popup -- ls` works but if I launch a shell within the popup via
`bind-key -N "Toggle persistent popup shell" \
         -n F4 if-shell -F '#{==:#{session_name},float}' { detach-client } \
         { popup -w70% -h70%  \
         'tmux attach -t float || tmux new -s float \; \
         display-message "Press PF4 to toggle floating popup or Ctrl-D to kill it"'\
         }
`
it fails when there is lots of output text of any command like `ls, du` etc.  This issue seems to be there with cygwin and not in wsl tmux.

**Comment by nicm** [comment]
Right but your command is complicated and I need you to find a simpler way to reproduce. Does it happen if you do:
~~~~
tmux popup
~~~~
And then run `ls -al` from that shell.

What if you bind just `popup` to a key and use it instead?

**Comment by sivaramn** [comment]
running `tmux popup` and then `ls -al` in the popup does not produce the freeze.  I was able to run multiple long output listings without an issue and `esc` cleared the popup too.

**Comment by nicm** [comment]
OK so it is only when you run tmux in the popup.

**Comment by nicm** [comment]
It is strange because the mechanics of how it works is the same, only the syntax has changed.

I'll take another look later on.

**Comment by nicm** [comment]
I don't see anything in this change that could affect this.

If you checkout `9cd45ddad3141370e0dac117388984a3f026c097` and build from that (don't forget to kill tmux entirely), does it work again?

**Comment by sivaramn** [comment]
`tmux -V`  after building `3.2-rc`  branch gives `tmux 3.2-rc5`

on wsl `tmux` 
---------------
`$tmux popup` works as expected with a  new bug; `ctrl -D` doesn't make the popup go away. I have to hit an additional `esc` to make the killed popup go away.  which is suboptimal. `F4` mapping too works and with the same `ctrl-D` bug

on cygwin `tmux`
-------------------
`$tmux popup` works as expected with a  new bug; `ctrl -D` doesn't make the popup go away. I have to hit an additional `esc` to make the killed popup go away.  `F4` mapping still has the same issue as written earlier

**Comment by sivaramn** [comment]
> 
> 
> I don't see anything in this change that could cause this.
> 
> If you checkout `9cd45ddad3141370e0dac117388984a3f026c097`

I missed this.  How do I checkout only this commit version?

**Comment by sivaramn** [comment]
> 
> 
> I don't see anything in this change that could cause this.
> 
> If you checkout `9cd45ddad3141370e0dac117388984a3f026c097` and build from that (don't forget to kill tmux entirely), does it work again?

No it doesnt.  On this commit, `tmux popup` or `F4` brings a black popup with no shell prompt. `esc` makes it go away

`20:37: /dev/pty0 key ~: show-messages                                                                                                       [0/0]

20:37: /dev/pty1 command: display-popup

20:37: /dev/pty0 key MouseDown1Pane: send-keys -M

20:37: /dev/pty0 key MouseDown1Pane: select-pane -t =

20:37: /dev/pty0 message: Unknown command: tmux

20:37: /dev/pty0 key F4: display-popup -h 70% -w 70% "tmux attach -t float || tmux new -s float \\;          display-message \"Press PF4 to toggl
e floating popup or Ctrl-D to kill it\""

20:37: /dev/pty0 key F4: if-shell -F "#{==:#{session_name},float}" detach-client "popup -w70% -h70% \"tmux attach -t float || tmux new -s float \
\\\;          display-message \\\"Press PF4 to toggle floating popup or Ctrl-D to kill it\\\"\""

20:37: /dev/pty0 command: new-session -A -s cyg
`

**Comment by nicm** [comment]
You will need to go back to using -KER in that commit, it is before the new syntax.

**Comment by sivaramn** [comment]
> You will need to go back to using -KER in that commit, it is before the new syntax.

on this commit with the `KER`, `tmux popup` just shows a floating black popup with no shell prompt(`esc` makes it go away). `F4` launches a popup with a shell prompt which freezes on long output of `du -h`.

Also this: if I'm on the last line of the popup screen and do a `ls`, it scrolls up as usual with the output of at least 12 lines; if I issue a `du -h` it freezes after 5-6 lines of the output after hitting the bottom of the screen. 
 `ls` output is fairly small , `du -h|wc -l` is about 3K lines

**Comment by nicm** [comment]
OK so this was broken before the syntax changes. Can you try some further back changes and see if it works, for example does it work with a3011be0d267a090c8bfa01a4ebe093bc203a1c4?

Make sure both the tmux you start and the tmux that is run by your popup command are the same binary.

**Comment by sivaramn** [comment]
~/tmux$ git status
    HEAD detached at a3011be0
    $ make  && make install

Problem is the same as before after installing the new binary in `/usr/local/bin`

     git checkout b96c5e3687d36cea7b575a7e151326f1b82824d2
     ./configure
     make
     make: *** No rule to make target 'Makefile.am', needed by 'Makefile.in'.  Stop.

Not sure why `make` is now giving issues.  How do I fix this?

**Comment by nicm** [comment]
Some commit will not build because they are sync commits.

So a3011be0d267a090c8bfa01a4ebe093bc203a1c4 does not work... that was quite a long time ago.

Do you know which is the last release candidate that did work? Here are the old tarballs if you want to try them:

[tmux-3.2-rc.tar.gz](https://github.com/tmux/tmux/files/6147577/tmux-3.2-rc.tar.gz)
[tmux-3.2-rc2.tar.gz](https://github.com/tmux/tmux/files/6147578/tmux-3.2-rc2.tar.gz)
[tmux-3.2-rc3.tar.gz](https://github.com/tmux/tmux/files/6147580/tmux-3.2-rc3.tar.gz)
