### ISSUE TITLE
choose-tree is extremely slow

### ISSUE THREAD

**Issue by svalaskevicius** [tmux/tmux#2597]
### Issue description

choose-tree is extremely slow. e.g. it reacts in 1-2s after pressing <up/down>

I've looked at perf top while using the choose-tree:
![2021-03-04-205553_1918x702](https://user-images.githubusercontent.com/893660/110029512-759a1f80-7d2c-11eb-92cb-f3b5a0c267af.png)

Could the earlier memory related fix (#2408) have caused this? or maybe syscalls?

Normal tmux usage is quite good otherwise.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 
`tmux 3.1c` + malloc trim patch from earlier fix

* Platform (`uname -sp`).
NixOS

* $TERM inside and outside of tmux (`echo $TERM`).
tmux-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Is this better in master? Format evaluation should be a lot quicker.

Is it better if you turn off the preview?

**Comment by svalaskevicius** [comment]
actually perf top is quite similar when choose-tree is not running... or wait, is that a separate process?

**Comment by svalaskevicius** [comment]
turning the preview off didnt help btw

**Comment by nicm** [comment]
Oh yeah malloc_trim, looks like the same as https://github.com/tmux/tmux/issues/2551.

**Comment by nicm** [comment]
Try this patch https://github.com/tmux/tmux/issues/2551#issuecomment-783217480.

**Comment by svalaskevicius** [comment]
hmm actually.. not sure yet.. pls wait a bit, :) I might be onto something.. will do an strace (may have been too hasty creating this :) )

**Comment by svalaskevicius** [comment]
hmm so strace got both tmux and itself frozen (I probably shouldn't have tried to run it from within tmux?)

anw, when I was watching htop, I saw the continuum plugin being invoked when browsing the tree.

after tmux restart, and this commented out, choose-tree is fast again:
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'

sorry for opening the issue without researching enough... I'll close it for now, and only reopen if the issue reappears and I am sure it's not the plugin :)

**Comment by svalaskevicius** [comment]
right, I've restarted it again with continuum on, and choose tree is still fast.. so it looks it was slow because that tmux process was "old enough"... 

I'll wait until it becomes slow again and reopen this with any more info... if you have any tips of what could help I'd appreciate :)

**Comment by nicm** [comment]
Run master with the patch I pointed you to. There is no point in reproducing with 3.1c now.

**Comment by svalaskevicius** [comment]
will do, thanks

**Comment by unphased** [comment]
It usually takes a few days for the problem I analyzed to creep up. You have to fragment the heap enough for it to become slow. It's not an issue after changing the call to malloc_trim from hundreds or more times a second to only once an hour. It's capable of halving the allocated space of the program in one call!

Thanks @nicm
