### ISSUE TITLE
ANSI parsing state machine hangs easily

### ISSUE THREAD

**Issue by cernekee** [tmux/tmux#26]
I am working with a development board that occasionally spews junk characters to the terminal.  On occasion I've noticed that this hangs my tmux and screen windows.  I isolated one sequence that does this consistently; the test case is:

```
echo -ne "\ek"
```

Basically the issue is that the state machine in input.c thinks that we're trying to rename the current window, so it collects input characters until it sees "\e\\\\".  If the "\ek" came from another source, it is unlikely that "\e\\\\" will ever arrive.

Characters typed while the window is "hung" will still be passed to the terminal, but the terminal's responses won't be displayed.

Usually a lone "\e" character is enough to get tmux out of this state, so typing something like this will work:

```
echo -ne "\ek"
echo -ne "\e"
```

The second command won't be echoed to the terminal, but it will take effect.

Also, having ANSI sequences or colors in your $PS1 prompt could mitigate the problem.

I'm not sure on the best way to handle these sorts of sequences in tmux.  Some possibilities include:

* Implement a timeout that ends an ANSI escape sequence.
* Implement a max character count.  e.g. if tmux sees 100+ characters entered for the window title, it's probably not a valid window title.
* Allow unexpected characters, such as '\n', to abort the rename sequence.

**Comment by nicm** [comment]
There is already a length limit but a 1 second timeout or something would be fine.
