### ISSUE TITLE
tmux window_name(#W) shows long path in windows-status-format

### ISSUE THREAD

**Issue by Marslo** [tmux/tmux#260]
I'm using CentOS 7, and Tmux 2.0. I found the windows-status-format shows $PS1:
![tmux2](https://cloud.githubusercontent.com/assets/5822057/12096182/9362ed38-b34e-11e5-99bc-e9a92b221150.png)

I checked the [tmux manual](http://man7.org/linux/man-pages/man1/tmux.1.html#FORMATS), it shows:

    window_name #W Name of window

I don't understand why it works in RHEL6.6 (in RHEL6.6, tmux 1.6, the tab name shows "bash"), but it shows path in CentOS 7. And How can I restore the same format?

My tmux configuration: https://github.com/Marslo/LinuxStuff/blob/master/Configs/HOME/Tmux/.tmux.conf

Thanks in advanced.

**Comment by nicm** [comment]
#W is the window name, probably your shell is renaming it, set
allow-rename to off in tmux to prevent it.

**Comment by Marslo** [comment]
Hi @nicm, Really appreciate your answer. 
I'm using PuTTy, my $ps1 is:
```shell
# ┌─ (USERNAME@HOSTNAME PATH) ->
# └─ $
if [ -z "$DISPLAY" ]
then
  export PS1="\n\[\033[30;1m\]┌─ (\u@\h \[\033[31;1m\]\w\[\033[30;1m\]) ->\n└─ \`if [ \$? = 0 ]; then echo \[\e[1\;30m\]\\$\[\e[1m\]; else echo \[\e[1\;31m\]\\$\[\e[0m\]; fi\` \[\033[0m\]"
  export PS2="\[\033[30;1m\] ->\[\033[30;1m\] \[\033[0m\]"
else
  export PS1="\n\[\033[30;1m\]\[\033(0\]l\[\033(B\]\[\033(0\]q\[\033(B\] (\u@\h \[\033[31;1m\]\w\[\033[30;1m\]) ->\n\[\033(0\]m\[\033(B\]\[\033(0\]q\[\033(B\] \`if [ \$? = 0 ]; then echo \[\e[1\;30m\]\\$\[\e[1m\]; else echo \[\e[1\;31m\]\\$\[\e[0m\]; fi\` \[\033[0m\]"
  export PS2="\[\033[30;1m\] ->\[\033(0\]q\[\033(B\] \[\033[0m\]"
fi
```

And [this](https://github.com/Marslo/LinuxStuff/blob/master/Configs/HOME/.marslo/.marslorc) is my linux environment configuration.

**Comment by Marslo** [comment]
Oh my god!!!!!!!! It works!!!!!!!!!!
Thanks a lot!!!
