### ISSUE TITLE
Cannot find window if name is duplicated

### ISSUE THREAD

**Issue by agguser** [tmux/tmux#2601]
### Issue description

`select-window -t $name` cannot find a window if the name is of multiple windows!

```sh
$ tmux -f /dev/null
$ tmux neww -n vim vim   # create a window with a name
$ tmux selectw -t vim   # OK, found
$ tmux neww -n vim vim    # create another window with the same name
$ tmux selectw -t vim   # ERROR
can't find window: vim
```

If this is by design, please add an option to switch to a window with such name, instead of error and do nothing.

### Required information

```sh
$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux next-3.3
screen
```

**Comment by nicm** [comment]
Yeah targets can't be ambiguous, they need to exactly specify one pane, window or session. If tmux can't narrow it down to one it doesn't just pick one.

**Comment by agguser** [comment]
So could you please add an option to switch to any matching window (preferably to the most recently used (MRU)). (And without the option, change the error message when multiple matches found to something like "can't uniquely find window: …".)

**Comment by nicm** [comment]
Maybe, not sure that is a good idea TBH.

**Comment by nicm** [comment]
What do you need this for? I don't recommend doing this in scripts.

**Comment by agguser** [comment]
Just like in the example, I sometimes open multiple vims and name them the same, and I just want tmux to switch to "any" vim to edit a file. (Even I name them vim1, vim2, …, I think `tmux selectw -t vim` should switch to any vim!)

**Comment by bpsib** [comment]
I ran into this issue when using `send-keys`. I tried `send-keys -t sh C-c` to send Ctrl+c to all windows named `sh` and was wondering why it was saying `Can't find pane: sh`. I now realize it only works if the name only exists once. I think it should support ambiguous targets where appropriate.

**Comment by nicm** [comment]
Added to todo list.
