### ISSUE TITLE
copy-and-cancel after search-reverse does not work

### ISSUE THREAD

**Issue by aaronjensen** [tmux/tmux#2602]
### Issue description

`search-reverse` has a few odd behaviors. First, when it's used along with a `search-backward`, it goes from the beginning of the selected term to the end, rather than going to the next term.

Next, when you press enter to copy the selection, it copies nothing. `copy-pipe-and-cancel` likewise receives nothing.

This also appears to happen with `search-again` and `search-forward`.

To reproduce:

1. Run:
  ```sh
  tmux -vv -Ltest -f/dev/null new
  tmux setw -g mode-keys vi
  ```
2. Press `C-b [`
3. Press `?t`
4. Press `Enter`
5. Press `nN`
6. Press `Enter`

[tmux-client-4261.log](https://github.com/tmux/tmux/files/6096454/tmux-client-4261.log)
[tmux-out-4263.log](https://github.com/tmux/tmux/files/6096455/tmux-out-4263.log)
[tmux-server-4263.log](https://github.com/tmux/tmux/files/6096456/tmux-server-4263.log)

### Required information

Please provide the following information:

Darwin i386
tmux next-3.3
tmux-256color

**Comment by nicm** [comment]
The `search-reverse` behaviour is intentional, it should swap ends of the current term first before moving to the next.

Copying the match also works for me, but I will look at your log later.

**Comment by aaronjensen** [comment]
Is there a way to disable that behavior? I get that it's roughly how isearch works, but it's not how search works in vim. I don't often have a use for swapping ends of a selection while searching.

**Comment by aaronjensen** [comment]
Also, my repro is more complicated than it needs to be... really all you need to do is `search-forward`.

**Comment by aaronjensen** [comment]
df7fbcd7a5a775586522380a70530721d1f2c151 is the bad commit for me (it's also the one that introduces the search behavior change)

As an aside, why do several commits lack `autogen.sh`? It makes it hard to bisect. Is there a good work around for this?

**Comment by nicm** [comment]
I think it is hard to see how this makes much difference, we have too many special cases for vim behaviour already.

**Comment by aaronjensen** [comment]
Fair enough, but it makes a pretty big difference in terms of navigating back and forth between search results. If you pass the result you wanted then come back it is quite jarring to end up on the same result but in a different place. It means one had to get used to NN to go back one if one already went forward. 

For me in particular I have a special copy mode for urls and files. J/k go up and down between results. This just breaks that experience slightly but I can work around it by making my mapping more complicated. Basically, I could previous previous next instead of just previous for my previous binding. It’s just odd to have to do that.

**Comment by nicm** [comment]
I suppose it won't do any harm adding another check for vi keys, but I don't plan to do it, do you want to take a look?

**Comment by aaronjensen** [comment]
I may, but the bigger issue is the fact that copy doesn’t work. It repros with emacs bindings as well. 

C-n c-s for something, m-w and no copy happens.

**Comment by nicm** [comment]
Yes I will look at this when I have time.

**Comment by aaronjensen** [comment]
I don't know how any of it works, but form some brief debugging, `window_copy_match_at_cursor` returns early here:

```
	if (data->searchmark[at] == 0)
		return (NULL);
```

Copy it be that it's not finding the search result because the cursor is no longer at the beginning of the result, but at the end instead?

**Comment by nicm** [comment]
I think you are right, nicely spotted. Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/6107032/x.diff.txt)
~~~~
--- window-copy.c	9 Mar 2021 08:24:09 -0000	1.319
+++ window-copy.c	9 Mar 2021 08:40:11 -0000
@@ -3366,8 +3366,11 @@ window_copy_match_at_cursor(struct windo
 	cy = screen_hsize(data->backing) - data->oy + data->cy;
 	if (window_copy_search_mark_at(data, data->cx, cy, &at) != 0)
 		return (NULL);
-	if (data->searchmark[at] == 0)
-		return (NULL);
+	if (data->searchmark[at] == 0) {
+		/* Allow one position after the match. */
+		if (at == 0 || data->searchmark[--at] == 0)
+			return (NULL);
+	}
 	window_copy_match_start_end(data, at, &start, &end);
 
 	/*

**Comment by aaronjensen** [comment]
That fixes it for me!

**Comment by nicm** [comment]
Great, applied, thanks!
