### ISSUE TITLE
tmux-256color terminfo does not set XT capability

### ISSUE THREAD

**Issue by vimpostor** [tmux/tmux#2606]
So vim and neovim (and probably other programs too) check terminfo for the XT Boolean flag and if it is found they enable the focus tracking features.
Outside tmux my terminal has the XT capability (`tput XT` runs successfully). Inside tmux the same command returns the error:
```tput: unknown terminfo capability 'XT'```

However clearly tmux has focus tracking capability, since I explicitly enabled it with `set -g focus-events on`, so I would expect it to set the XT capability.
I tried using `terminal overrides`: `set -as terminal-overrides ",*:Tc:XT"`
But this doesn't work, probably because this only overrides the outside terminal terminfo.

Is there any workaround how I can use `tmux-256color` and have the `XT` capability set? My current workaround is to use `set -g default-terminal "xterm-256color"`, which does set the `XT` capability.

* tmux version: `next-3.3`
* $TERM inside and outside of tmux: Outside: xterm-256color, Inside: tmux-256color

P.S.: screen-256color does not set XT as well.

**Comment by nicm** [comment]
You would need to create a custom terminfo entry.

`XT` is technically only meant to advertise xterm title setting (Xterm Titles) but tmux used to use it to cover various xterm-like features like focus reporting so no surprise other applications do also.

**Comment by vimpostor** [comment]
Well creating a new terminfo is kinda a bit overkill just so that I can get focus tracking. I know using `set -g default-terminal "xterm-256color"` is heavily discouraged, but are there really any practical problems with it? I used that setting for years by accident and didn't notice any problems. So I feel like putting that in the tmux config would be much more easy than creating a whole new terminfo entry.

**Comment by nicm** [comment]
Some applications will draw incorrectly, most common is irssi. But why not just configure vim to do it anyway?

**Comment by nicm** [comment]
You can stick with xterm-256color and ignore any problems, make a modified version of tmux-256color yourself, or configure vim to turn in focus reporting when TERM is tmux-256color. Those are the only practical options, you can't configure it any other way in tmux itself.

**Comment by vimpostor** [comment]
OK thanks for the answer. I will then probably just stick to force enabling the option from vim.
For posteriority sake, here is how to do it:

```vim
" .vimrc
let &t_fe = "\<Esc>[?1004h"
let &t_fd = "\<Esc>[?1004l"
```
Also relevant: https://github.com/vim/vim/pull/7673#issuecomment-763974778
