### ISSUE TITLE
Use freedesktop specification for config

### ISSUE THREAD

**Issue by ajyotirmay** [tmux/tmux#2607]
### Issue description

This issue addresses presence of `~/.tmux.conf`. By the standards, config files should be in `$XDG_CONFIG_HOME/tmux.conf`, and to not cause a problem to existing configs, my recommendation should be prioritized when checking for config, and then fallback to the present day method of readin `~/.tmux.conf`

[Freedesktop Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

### Required information

Please provide the following information:

* tmux version (`tmux 3.1c`).
* Platform (`Linux x86_64 Debian`).
* $TERM inside and outside of tmux (`xterm-256color`).

**Comment by nicm** [comment]
tmux is not a Gnome application and does not have to take any particular notice of their guidelines, particularly when they are silly. But as it happens we do now look at XDG_CONFIG_HOME in master.

**Comment by ajyotirmay** [comment]
Didn't know it's a gnome-spec. I normally don't agree with decisions made at Gnome, but this one seems like a sane default to me, since it keeps all configs under a single directory, and keeps `~` clean.

**Comment by nicm** [comment]
Configs are hidden files so they are hardly untidy.

**Comment by nicm** [comment]
Xdg is a red hat/xorg/gnome thing. But anyway we support it in master so you can use it if you like :-).

Iiic in 3.1 you can use .config but not XDG_CONFIG_HOME.

**Comment by ajyotirmay** [comment]
Thanks :innocent:
