### ISSUE TITLE
unintentionally sending keys to application

### ISSUE THREAD

**Issue by eworm-de** [tmux/tmux#2608]
### Issue description

I use `tmux` to split the terminal and show several `htop` side by side. Resizing the panes (With `Ctrl`-`b` and arrow) often results in the nice value to change, also the selection moves down.

![Screenshot_2021-03-12_07-59-15](https://user-images.githubusercontent.com/970853/110905179-6148ba80-830a-11eb-92af-c130c9c53b24.png)

I can't remember having seen this with latest stable version, I think it is a regression in current rc (running a build from 3.2-rc4 tarball).

In `htop` these keys are used to control the process priority:
```
F7 ]: higher priority (root only)
f8 [: lower priority (+ nice)
```

Possibly this is broken escape sequences escaping to `htop`?

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.2-rc4`
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`): outside: `xterm` - inside: `screen`

**Comment by eworm-de** [comment]
Just wanted to collect some logs and observed more strange behavior:

![Screenshot_2021-03-12_08-23-32](https://user-images.githubusercontent.com/970853/110906645-81797900-830c-11eb-8e6b-aee301bfe41c.png)

Some more broken escape sequences?

**Comment by eworm-de** [comment]
> tmux version (tmux -V): tmux: unknown option -- V- possibly another bug? Running a build from 3.2-rc4 tarball.

That was caused by an alias... So please ignore. Updating above.

**Comment by nicm** [comment]
This seems very likely to be a bug in htop but show me tmux server logs please.

**Comment by eworm-de** [comment]
Ok, here we go... Uploaded to my web server as the file is quite large (~ 55MB):
https://www.eworm.de/tmp/tmux-server-52157.log

The issue happened in the right pane.

**Comment by topcat001** [comment]
I don't know how useful this is but if you run several splits with `cat` and enter a `Ctrl+V` in each split, and then resize/move the panes, then any leakage of escape sequences would show up explicitly. I don't see this happening at all.

**Comment by eworm-de** [comment]
Perhaps this is related to `htop`'s massive screen updates?

However... Started `htop` in a terminal window without `tmux` and constantly resized the window with my mouse. Could not reproduce... So `tmux` is definitely involved to trigger the issue.

**Comment by nicm** [comment]
tmux does not appear to be sending any stray function keys to htop:
~~~~
$ grep 'writing key ' tmux-server-52157.log
1615539285.686078 writing key 0x73 (s) to %0
1615539285.854916 writing key 0x73 (s) to %0
1615539285.958079 writing key 0x68 (h) to %0
1615539286.022399 writing key 0x20 (Space) to %0
1615539286.206132 writing key 0x6d (m) to %0
1615539286.254090 writing key 0x61 (a) to %0
1615539286.366172 writing key 0x72 (r) to %0
1615539286.502732 writing key 0x9 (Tab) to %0
1615539287.014896 writing key 0x30 (0) to %0
1615539287.078137 writing key 0x31 (1) to %0
1615539287.190264 writing key 0x9 (Tab) to %0
1615539287.670259 writing key 0xd (Enter) to %0
1615539289.070291 writing key 0x68 (h) to %0
1615539289.150284 writing key 0x74 (t) to %0
1615539289.214327 writing key 0x6f (o) to %0
1615539289.254285 writing key 0x70 (p) to %0
1615539289.694369 writing key 0xd (Enter) to %0
1615539292.318635 writing key 0x73 (s) to %1
1615539292.462624 writing key 0x73 (s) to %1
1615539292.542608 writing key 0x68 (h) to %1
1615539292.630802 writing key 0x20 (Space) to %1
1615539292.814538 writing key 0x6d (m) to %1
1615539292.870572 writing key 0x61 (a) to %1
1615539292.982717 writing key 0x72 (r) to %1
1615539293.230677 writing key 0x9 (Tab) to %1
1615539293.854648 writing key 0x30 (0) to %1
1615539294.134662 writing key 0x32 (2) to %1
1615539294.374644 writing key 0x9 (Tab) to %1
1615539294.766671 writing key 0xd (Enter) to %1
1615539299.095179 writing key 0x68 (h) to %1
1615539299.175185 writing key 0x74 (t) to %1
1615539299.287133 writing key 0x6f (o) to %1
1615539299.751162 writing key 0x70 (p) to %1
1615539300.111115 writing key 0xd (Enter) to %1
1615539309.871907 writing key 0x2010000000ae (C-Left) to %1
1615539316.320419 writing key 0x71 (q) to %1
1615539316.960496 writing key 0x71 (q) to %1
1615539317.801371 writing key 0x4 (C-d) to %1
1615539318.088512 writing key 0x3 (C-c) to %1
1615539319.008631 writing key 0x4 (C-d) to %1
1615539320.105406 writing key 0x4 (C-d) to %1
1615539320.632735 writing key 0x71 (q) to %0
1615539320.944725 writing key 0x4 (C-d) to %0
1615539321.112759 writing key 0x4 (C-d) to %0
~~~~
tmux does resize a few times fairly quickly, so perhaps htop doesn't like that:
~~~~
1615539308.147914 window_pane_send_resize: %1 resize to 151,64
1615539308.415600 window_pane_send_resize: %1 resize to 152,64
1615539308.665064 window_pane_send_resize: %1 resize to 154,63
1615539308.916946 window_pane_send_resize: %1 resize to 156,64
~~~~
Does this happen if you are careful to leave some time between each resize?

**Comment by eworm-de** [comment]
Ah, this is easy to reproduce: Just open `htop` in `tmux` and press `C-left` (without `C-b`).
This does not happen without `tmux`.

**Comment by topcat001** [comment]
What are the escape sequences being sent while running with and without tmux when you press `C-left` (as shown by `C-v C-left`)? If they differ (they don't for me) that can explain this. `TERM` should be `tmux` or `tmux-256color` inside `tmux` and the application should honour the escape sequences sent by `tmux`. However I have seen this not to be the case for some applications.

**Comment by eworm-de** [comment]
Looks like the escape sequence is always the same. `C-v` `C-left` gives `^[[1;5D` with and without `tmux`.

The behavior goes away if I set `TERM` to `tmux`. However man page says:

> The TERM environment variable must be set to ‘screen’ or ‘tmux’ for all programs running inside tmux.  New windows will
> automatically have ‘TERM=screen’ added to their environment, but care must be taken not to reset this in shell start-up files or
> by the -e option.

So why is `screen` the default, not `tmux`?

**Comment by nicm** [comment]
`tmux` doesn't exist on all platforms.

**Comment by eworm-de** [comment]
Good point... Perhaps this should change for newer releases or depending on whether or not terminfo `tmux` is available at compile time.

For now I added this to `tmux.conf`:
```
set -g default-terminal tmux
```

How are distributions supposed to handle this if terminfo `tmux` is available?

And back to the initial issue... Who's fault is it?

**Comment by topcat001** [comment]
So just to be clear `TERM=tmux` fixes the issue you are having?

**Comment by eworm-de** [comment]
Yes, it does.

**Comment by eworm-de** [comment]
I am not happy with closing this... I would consider it a workaround at best.

Being the maintainer for the Arch Linux package I would like to see a proper fix.
Perhaps a configure option to select the default? Or build time detection?

**Comment by nicm** [comment]
Detect what? There is no way for tmux to know whether the application inside will understand these keys. 

The only thing we could do is not send xterm-style function keys unless `default-terminal` is set to `tmux*` but that will cause problems for far more people than it helps.

**Comment by eworm-de** [comment]
Looks like setting `default-terminal` to `tmux` works better if it is available. We know that terminfo `tmux` is shipped with `ncurses` `v6.0` and later. So we can make `tmux` the default if proper ncurses is detected.

Or let's just add configuration option, something like `--with-default-terminal=tmux`.

This should not break anything as long as terminfo `tmux` is really available, no?

**Comment by nicm** [comment]
I think there are still too many platforms without it to change the default. Even the latest macOS doesn't have it, and there are tons of old Solaris boxes and even Linux (RHEL6?) out there that people routinely ssh into from inside tmux. I think the default should still err on the side of avoiding problems here rather than causing them.

Detecting it at build time has the same problem, people (including me) often run their main laptop or desktop machine from a much newer OS version than the boxes they then want to ssh into. Also there is again macOS where there might be a packages ncurses with it but a system ncurses without.

I don't mind a configure switch to set it, although if you want to change it it is trivial to patch options-table.c. Maybe you could do that for Arch and see how it goes?

**Comment by eworm-de** [comment]
Ah, I missed the fact that the **remote** side of a ssh connection needs to have the terminfo available.
So yes, better keep the default as-is for the time being. 😜

Thanks for clarification!
