### ISSUE TITLE
When set set -g mouse on then cant paste inside tmux inside tmux on WSL2.0

### ISSUE THREAD

**Issue by kangarooo** [tmux/tmux#2610]
Windows 10 WSL2.0 tmux3.0a
ssh into shell tmux 2.3
tmuxed into
ssh tmux 3.0a Ubuntu 20.04
ssh tmux 2.6 Ubuntu 18.04
Linux x86_64
screen-256color
Windows 10 WSL2.0

When i add
set -g mouse on
then cant paste with left mouse click

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#i-want-to-use-the-mouse-to-select-panes-but-the-terminal-to-copy-how

**Comment by kangarooo** [comment]
> https://github.com/tmux/tmux/wiki/FAQ#i-want-to-use-the-mouse-to-select-panes-but-the-terminal-to-copy-how

THX. Shift works.
