### ISSUE TITLE
Feature request: allow calling option format modifiers for command output

### ISSUE THREAD

**Issue by imomaliev** [tmux/tmux#2611]
### Issue description
Hi! 
Is there a way to call option format modifiers like `=N` for command in `status` ? 
What I want is to be able to do `#{=2:#(mycmd)}`, to render only first 2 letters of `mycmd` output, similar to `#{=2:pane_title}`. I know that the same functionality could be achieved with tools like `cut -c` or `head -c`, but maybe this feature is already exist, but I didn't find it or it will be possible to add it in future?

### Required information

* tmux version (`tmux -V`).
 `tmux 3.1c`
* Platform (`uname -sp`).
  `Darwin i386`
* $TERM inside and outside of tmux (`echo $TERM`).
  outside: `xterm-256color`
  inside: `tmux-256color`

**Comment by nicm** [comment]
I am not sure there is much use for this - if you are running a command anyway you may as well use cut like you suggest. You could maybe do this:

#(tmux set -g @foo bar)#{=2:@foo}

**Comment by imomaliev** [comment]
Yeah, this also is one way of doing it. I also think this is a niche feature, but thought maybe it is already possible. Thank you for replay and all the work you and tmux team does!
