### ISSUE TITLE
Question: filtering when using choose-window

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#2612]
### Issue description

Hi, I'd like to use select-window to select windows from a specific version; I see that ther are two parameters -f and -F but I am not sure I can achieve the result I want.

also note, in my version the man page shows some choose-xxx functions while the command completion shows other

### Required information

Please provide the following information:
tmux 3.0a

**Comment by nicm** [comment]
I don't understand your question.

**Comment by nkh** [comment]
I have multiple sessions, say A and B, I want to chose a window from session B only, I tried to filter away session A without success.

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/Recipes#make-c-b-w-binding-only-show-the-one-session

**Comment by nicm** [comment]
You can do without the `run` and just use `choose-tree -f` with a similar expession if you want one session that is not the current one.
