### ISSUE TITLE
Run shell with -C crashes tmux server

### ISSUE THREAD

**Issue by mohkale** [tmux/tmux#2613]
### Issue description

Any command with run-shell `-C` seems to crash my tmux server. For example:

```sh
tmux bind g run -b -C 'echo hello world'
```

### Required information

* tmux version (`tmux -V`): tmux next-3.3
* Platform (`uname -sp`): Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`): st-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`):  [tmux-client-808575.log](https://github.com/tmux/tmux/files/6137683/tmux-client-808575.log), [tmux-out-808577.log](https://github.com/tmux/tmux/files/6137685/tmux-out-808577.log), [tmux-server-808577.log](https://github.com/tmux/tmux/files/6137686/tmux-server-808577.log)

**Comment by topcat001** [comment]
I took a quick look at it. If the command is run in the background `-b` then `cdata->item` is `NULL` which is used by `cmdq_error` to retrieve client info, which causes the crash. The `-C` flag means this will produce an error since `echo` is not a tmux command. It will not crash if the command is valid.

**Comment by mohkale** [comment]
@topcat001 

Thank you for investigating. 

> It will not crash if the command is valid.

What do you mean by this? You seem to be indicating you can only run tmux commands (eg: `set status-position bottom`) but `run` is short for `run-shell` so I don't really think that's what you mean. Could you share an example of a valid command :?

**Comment by topcat001** [comment]
The `-C` flag accepts a tmux command instead of a shell command. So `echo` produces an error. If you drop the `-C` in your binding, then it will run in the shell and you will be able to get the output.

**Comment by mohkale** [comment]
@topcat001 

Oh, that's my bad.

```man
     run-shell [-bC] [-d delay] [-t target-pane] [shell-command]
                   (alias: run)
             Execute shell-command or (with -C) a tmux command in the background without creating a window.
             Before being executed, shell-command is expanded using the rules specified in the FORMATS sec‐
             tion.  With -b, the command is run in the background.  -d waits for delay seconds before starting
             the command.  If -C is not given, any output to stdout is displayed in view mode (in the pane
             specified by -t or the current pane if omitted) after the command finishes.  If the command
             fails, the exit status is also displayed.
```

I thought `-C` caused tmux to discard the output of the command and not show any output in a view-pane. Is there a different command for that? I've got a script which is calling another script but that other script is disregarding any redirections (eg. `>/dev/null`) and writing to the terminals stdout which causes tmux to show its output. I'd like to just ignore the output.

**Comment by topcat001** [comment]
I don't know for sure if the output can be disabled, but you could redirect it using `-t` to a pane which is in the background as a workaround.

**Comment by nicm** [comment]
You can disable output using `/dev/null` the way you would with any shell script.

This crash should be fixed however.

**Comment by nicm** [comment]
Oh you said your other script is misbehaving. Is it opening `/dev/tty`?  Hmm, I'm not sure what you can do about that... Maybe run it in `script` or something else that opens another pty.

**Comment by topcat001** [comment]
In the crashing case we could simply bypass `cmdq_error` and directly print a message on the status bar. The attached diff fixes the crash. Please have a look.
[a.diff.txt](https://github.com/tmux/tmux/files/6140010/a.diff.txt)

**Comment by nicm** [comment]
Great stuff, applied now, thanks!

**Comment by mohkale** [comment]
@nicm 

> Oh you said your other script is misbehaving. Is it opening /dev/tty?

I thought it was... but now I'm no longer experiencing this issue so I'm not sure anymore. For now this issue can be closed. Thank you.
