### ISSUE TITLE
Question: A way to know which config file was used

### ISSUE THREAD

**Issue by imomaliev** [tmux/tmux#2615]
### Issue description

The are currently few issues with how https://github.com/tmux-plugins/tpm reloads plugins. Main one being that it doesn't have a way to know which config file was used? Is there a way to know programatically from env variable or some tmux option what file was passed to `tmux -f wantedfile.conf`?

### Required information

* tmux version (`tmux -V`).
 `tmux 3.1c`
* Platform (`uname -sp`).
  `Darwin i386`
* $TERM inside and outside of tmux (`echo $TERM`).
  outside: `xterm-256color`
  inside: `tmux-256color`

**Comment by nicm** [comment]
Someone else asked for this. In master, you can look at the `config_files` format variable (the file names are separated by commas).

There is also a change to add a variable for the current config file *inside* the file which you could then save. But I have not applied it yet.

**Comment by imomaliev** [comment]
Got it, thanks.
