### ISSUE TITLE
mouse mode fails after ssh broken pipe with nested tmux session

### ISSUE THREAD

**Issue by lonelykid** [tmux/tmux#2616]
### Issue description

1. use tmux locally. 
2. ssh to a remote machine.
3. start tmux on remote machine.
3.1 disconnect network. wait for ssh connection to break by itself.
3.2 OR use `Enter  ~  .` to break ssh connection.
3.3 OR `pkill ssh` locally
6. try scrolling the window or left/right click. the sequence is printed to shell
![image](https://user-images.githubusercontent.com/2936633/111514552-3b674f80-8728-11eb-9e16-886a5d15014b.png)

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux next-3.3 compiled from master branch
* Platform (`uname -sp`). local macos 11.2.3 remote centos 7
* $TERM inside and outside of tmux (`echo $TERM`). outside: xterm-256color inside: tmux-256color remote: tmux-256color the tmux-256color terminfo is shared by Nicholas in his gist. the bug still happens when TERM set to screen-256color.
* Logs from tmux (`tmux kill-server; tmux -vv new`): it's a little complex. I will get the logs if necessary.
* terminal: alacritty with tmux as first level shell. But I've tried other setting. The bug is the same. So I think it's not because of the terminal.

**Comment by nicm** [comment]
If the connection drops tmux will not be able to turn the mouse off. You can run `reset` at the shell or `C-b : send -R` in tmux to fix it.

**Comment by lonelykid** [comment]
Thank you. Resetting shell solves the issue. It has nothing to do local tmux. I just tried without local tmux. 
is it possible to make it just work without resetting?

**Comment by nicm** [comment]
No, tmux has no way to know that ssh is going to disconnect, so it can't turn the mouse off.
