### ISSUE TITLE
$TERM different for first window than later windows

### ISSUE THREAD

**Issue by rightaway** [tmux/tmux#2617]
### Issue description

In tmux.conf I have a `source powerline.conf` and some more lines before `set -g default-terminal "tmux"`. The first tmux session that I open (from `.xsession` file) shows `$TERM` of `screen`. All later windows I open in tmux have `$TERM` of `tmux`. I have to put the `default-terminal` line as the first line of the config file to prevent this and show all windows as `tmux`.

I don't start any tmux service in advance, I just start tmux from the terminal started in `.xsession`. Is there a different recommended way to start tmux to prevent this race condition?

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 3.1c
* Platform (`uname -sp`). Linux
* $TERM inside and outside of tmux (`echo $TERM`). tmux
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Make sure you set `default-terminal` before you create any sessions.

**Comment by rightaway** [comment]
Would adding `export TERM="tmux"` to my zsh config files be recommended instead of setting `default-terminal` in tmux config file, or does `default-terminal` do more than just set `TERM`?

**Comment by nicm** [comment]
It allows italics to work, but no reason you can't do both. You should make the bit in .zshrc conditional on `$TMUX` being set though.

**Comment by rightaway** [comment]
How do you suggest to start `default-terminal` before creating any sessions? In `.xsession` file which runs startup programs I do like `kitty tmuxinator start mysession1` and `kitty tmuxinator start mysession2`. Do I need a new line before those to set `default-terminal`? How should it look outside of a tmux config file?

**Comment by nicm** [comment]
> I have to put the default-terminal line as the first line of the config file to prevent this and show all windows as tmux.

What's wrong with this?

**Comment by rightaway** [comment]
Not sure it is wrong. Is it the recommended way or do I set it before I create any sessions as you said?

It looks like there's a race condition as I saw when I do the `source` command, so putting it at the first line could be working by luck and could sometimes have the wrong `$TERM`?

**Comment by nicm** [comment]
Sorry I didn't see your reply.

You can set `TERM` however you like so long as it ends up as `screen`, `screen-256color`, `tmux` or `tmux-256color` inside tmux. You need to set `default-terminal` to `tmux` or `tmux-256color` if you want italics to work.

`.tmux.conf` should be read before any panes are created when the server is first started so putting it on the first line should be fine.
