### ISSUE TITLE
Add macOS package managers to installation instructions

### ISSUE THREAD

**Issue by jrjsmrtn** [tmux/tmux#2618]
### Issue description

`tmux` has been available on macOS and maintained in multiple macOS package managers for years. The [Installing > Binary packages](https://github.com/tmux/tmux/wiki/Installing#binary-packages) table in the Wiki does not mention any of those package managers.

### Wiki patch

As I cannot submit a Wiki PR, here is a patch to add the MacPorts and Homebrew package managers:

```
$ git diff 14e0b1d8ebd64f3afa10c8200ef0194da15e3e79
diff --git a/Installing.md b/Installing.md
index 827d88f..c78e987 100644
--- a/Installing.md
+++ b/Installing.md
@@ -13,6 +13,8 @@ RHEL or CentOS|`yum install tmux`
 Debian or Ubuntu|`apt install tmux`
 Arch Linux|`pacman -S tmux`
 openSUSE|`zypper install tmux`
+macOS (using MacPorts)|`port install tmux`
+macOS (using Homebrew|`brew install tmux`

 Some thirdparty binary packages are available: [AppImage](Installing#appimage-package) and
 [RPMs](Installing#red-hat-enterprise-linux--centos-rpms).
```

**Comment by nicm** [comment]
Good stuff, added thanks!
