### ISSUE TITLE
Tabs being displayed using spaces breaks copy/paste to graphical applications

### ISSUE THREAD

**Issue by vv221** [tmux/tmux#2619]
### Short issue description

Tabs (the indentation character) are displayed using spaces in tmux panes, this breaks graphical copy-paste.

### Issue description

When displaying the contents of a text file using tabs for indentation inside tmux, the tabs are displayed in the terminal using spaces. Displaying the contents of the same file outside of tmux uses the tab character instead.

It causes issues when trying to copy-paste the content of the tmux pane using mouse selection (either selection + middle clic or any copy-paste keyboard shortcut). Because a series of spaces is copied instead of the tabs, what is pasted is not the actual file contents.

This is of course only an issue when copying tmux pane content to another graphical application, copy-paste not relying on what the terminal displays preserve the tabs, as expected.

Old issue #978 was probably already about tabs being displayed using spaces.

### Environment

* Debian Bullseye/Sid
* tmux 3.1c
* $TERM inside tmux: `tmux-256color`
* $TERM outside tmux: `xterm-256color`

**Comment by nicm** [comment]
A tab character is an instruction to move the cursor, tmux does not send them or send spaces, it simply moves the cursor if necessary.

**Comment by vv221** [comment]
It seems you did not understand the issue.

tmux displays tabs, as it displays any character. By that, I mean a printable character after a tab will be displayed farther to the right than the same character without a preceding tab.

Normal terminal behaviour is to push the character to the right using a single blank character that has a long width. Tmux behaviour is to instead push this character using multiple instances of one-character-wide spaces.

The difference is obvious during selection using the mouse cursor:
- outside of tmux, only the full tab can be selected, as it is a single character
- inside tmux, increments can be selected, as the tab has been displayed using multiple spaces

Outside of tmux, the blank space uses the following unicode character:
```
U+0009 <control>
UTF-8: 09 UTF-16BE: 0009 Decimal: &#9; Octal: \011

Category: Cc (Other, Control); East Asian width: N (neutral)
Unicode block: 0000..007F; Basic Latin
Bidi: S (Segment Separator)
```
Inside tmux, it is instead using multiple repetitions of the following character:
```
U+0020 SPACE
UTF-8: 20 UTF-16BE: 0020 Decimal: &#32; Octal: \040
                                                                               
Category: Zs (Separator, Space); East Asian width: Na (narrow)
Unicode block: 0000..007F; Basic Latin                                         
Bidi: WS (Whitespace)                 
```

**Comment by nicm** [comment]
A tab simply moves the cursor to the next tab stop. tmux will almost never use spaces for this, your terminal is inferring spaces from whatever cursor movement sequence tmux does choose to use. It is not practical for tmux to map tabs received inside to tabs sent outside.

**Comment by vv221** [comment]
I see we’re just going to repeat #978 with an unexplained "wontfix", and tmux still breaking the ability to copy file contents for another 3 years. I’m out of here then.

**Comment by nicm** [comment]
Yes the conclusion is the same. Using tabs to move the cursor outside tmux
does not make sense for various reasons. It would be possible to track them
and attempt to preserve them for copying with copy mode but nobody has done
it, and it would take a little thought (for example, what happens if the
tab stops were changed between two tabs).
