### ISSUE TITLE
Feature Request: scroll-up and scroll-down adjustable

### ISSUE THREAD

**Issue by maikelmeyers** [tmux/tmux#262]
Hi,

would be nice if one of them could work:
`bind-key -t vi-mode PPage scroll-up ; scroll-up` or
`bind-key -t vi-mode PPage scroll-up 2`
since `half-page-up` is too fast and `scroll-up` is too slow.
I wonder why it is not possible to send more than one copy-mode command with a bound key.

Best Regards

**Comment by orrsonn** [comment]
I am using shift + mousewheel to scroll faster.. works nice in combination

    bind -t vi-copy    S-WheelUpPane   halfpage-up
    bind -t vi-copy    S-WheelDownPane halfpage-down

**Comment by maikelmeyers** [comment]
Yes, but as I wrote already, `half-page-up` is too much for my taste.

Using commands in copy-mode is very limited. There is no way to send more than 1 command or to start an external script (there is no run command). Also commands like scroll-up can not be called from the outside (`tmux scroll-up` does not work). So there is no way for scripting the copy-mode.

**Comment by bechampion** [comment]
this might be too late but wouldn't we could add a new modkeycopy 

(MODKEYCOPY_QUARTERPAGEUP/DOWN) on mode_key.c and add something like:
```url
https://github.com/tmux/tmux/blob/master/window-copy.c#L499
```
but with the exception of dividing total y /4
```C
n = screen_size_y(s) / 4;
```

i think that should work would it?
PS:I'm just getting familiar with tmux code.

**Comment by bechampion** [comment]
it worked: this is what i did
```C
$ grep QUP * -I -sn --color
mode-key.c:102:	{ MODEKEYCHOICE_QUP, "qup" },
mode-key.c:156:	{ MODEKEYCOPY_QUP, "qup" },
tmux.h:498:	MODEKEYCHOICE_QUP,
tmux.h:549:	MODEKEYCOPY_QUP,
window-copy.c:426:	    cmd != MODEKEYCOPY_QUP &&
window-copy.c:499:	case MODEKEYCOPY_QUP:
```
the function itself is in window-copy.c:
```C
        case MODEKEYCOPY_QUP:
                n = screen_size_y(s) / 4;
                for (; np != 0; np--) {
                        if (data->oy + n > screen_hsize(data->backing))
                                data->oy = screen_hsize(data->backing);
                        else
                                data->oy += n;
                }
                window_copy_update_selection(wp, 1);
                window_copy_redraw_screen(wp);
                break;
```
and then bound the action to some random key:

```
bind -t vi-copy    X qup
```
and it moves the cursor half of halfpage-up , qup == quarter up.... dont know how much of this could be really moved to stable tmux but if i get green lights i don't mind fixing the code and do it.

**Comment by maikelmeyers** [comment]
Yes, I also did something similar as a workaround. I changed the code line for half page-up from `n = screen_size_y(s) / 2;` to `n = 10;`  10 lines is a good value for me. For others it might be another value, so I would prefer a selectable scroll value...

**Comment by bechampion** [comment]
i still think it would be a nice feature to have ,  an adjustable scrolling size or something like that.

**Comment by nicm** [comment]
A couple of people asked for this and I wrote some code to allow the repeat count to be specified as part of the binding but I can't find it now, it is probably linked to from some issue. Still, that is the way to do it probably.

**Comment by bechampion** [comment]
i think i would use it personally  , thanks!

**Comment by nicm** [comment]
http://pastebin.ca/raw/3209063 but I don't know if it'll still apply.

**Comment by booooh** [comment]
Is this still an active feature request? This feature (specify the number of lines in the binding) definitely gets a +1 from me.

**Comment by thegranddesign** [comment]
Personally for me the scroll speed is way too slow.  I understand that it's a personal taste and it sounds like @nicm's proposal to add repeat count to the binding would be the proper underlying feature to be added.

**Comment by thegranddesign** [comment]
Perhaps we should close this issue and open a new one for adding the repeated bindings to Tmux proper?

**Comment by nicm** [comment]
This is the diff updated to master [tmux-mode-repeat.diff.txt](https://github.com/tmux/tmux/files/242698/tmux-mode-repeat.diff.txt).

People with mice that have scroll wheels need to test this and see if it solves their problem, because I don't have any mice with scroll wheels and I don't really mind how they work.

Try something like this:

tmux bind -temacs-copy -R5 WheelUpPane scroll-up
tmux bind -temacs-copy -R5 WheelDownPane scroll-down

I would like to change how mode key bindings work entirely so that they are just a normal tmux keytable where you could bind any tmux command, but until that time this is the best option.

**Comment by rightaway** [comment]
> tmux bind -temacs-copy -R5 WheelUpPane scroll-up
> tmux bind -temacs-copy -R5 WheelDownPane scroll-down

Do we run these in the terminal or does it have to be in the config file? If I run it in tmux 2.2 I get:

```
tmux: unknown option -- R
usage: bind-key [-cnr] [-t mode-table] [-T key-table] key command [arguments]
```

**Comment by jfelchner** [comment]
@nicm FWIW, the changes you made in 2.3 work brilliantly for this.  Thank you very much for adding it.  It was one of my few daily annoyances. :heart:
