### ISSUE TITLE
How detect size of serial console in tmux ?

### ISSUE THREAD

**Issue by Raizo62** [tmux/tmux#2620]
Hi

I use (and develop) the linux distribution [LiveRaizo](https://sourceforge.net/projects/live-raizo/)

In LiveRaizo, there is the gui emulator "GNS3" which contains a VM called Debian. GNS3 uses the serial console to access to the console of the VM.

To know the size of the console, i use "resize" of the package "xterm" : After each command of the user, i run "resize" in "hidden mode" to know this size.

But, in tmux, "resize" doesn't see that the size of the console has changed. I must detach, run "resize", and attach again ("tmux a").
But my students never remember.

Do you know a method, or have you an idea to know the size of the serial console inside of tmux ?

Thank you

**Comment by nicm** [comment]
Does tmux see the size change if you do `pkill -WINCH tmux`?

**Comment by Raizo62** [comment]
No. because, even outside TMUX, with the signal WINCH, the serial console doesn't detect the change. I must run "resize" which prints characters to see the limit of the screen.
(But I have tested again to verify)

**Comment by nicm** [comment]
There isn't really a practical way to make this work inside tmux because even if you used the bypass escape sequence to ask for the size, you wouldn't see the result. You would need to patch tmux to do this itself the same way resize does.

One idea might be to set `lock-command` to resize and see if that works, then you could bind a key to run `lock-client` or even maybe run `lock-server` yourself. I am not certain this would work however.

**Comment by Raizo62** [comment]
To test, i have add in /etc/tmux.conf
```
set-option -g lock-command  /opt/raizo/bin/sizeConsole
bind L lock-session
```
(sizeConsole calls resize.)

In TMUX, after CTRL+B L, tmux learns the new size of the console :-)

Is there a way to say to TMUX to do this after each user's command ? (I m in zsh, then zsh can run automatically commands after user's command)

But, i afraid it will blink a lot

**Comment by nicm** [comment]
You can run one of the lock commands eg `tmux lock-client` from zsh (maybe only if `$TMUX`) is set but yes it will blink a lot.

**Comment by Raizo62** [comment]
I believe that i will keep the hot key to run the lock-command
Thanks you for your help.
