### ISSUE TITLE
Tab button wont unbind

### ISSUE THREAD

**Issue by lucianjones** [tmux/tmux#2622]
Just getting started with tmux and really liking it except for one issue, the tab button doesn't work in it, and instead I have to press shift tab to get a normal tab. I tried unbinding the tab button in my conf, but it didn't change anything. Here is my config file: https://github.com/lucianjones/tmux/blob/93dfad9b9d21e8263c0b575c712e1e73ae31f84e/tmux.conf

Any help would be appreciated, and sorry in advanced if it's some dumb mistake. thanks

* tmux version (`tmux -V`): 3.1c
* Platform (`uname -sp`): arch linux
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color, tmux-256color

**Comment by nicm** [comment]
> bind -n C-i select-pane -U

`C-i` and `Tab` are the same so this will prevent `Tab` from working.

**Comment by minhduc0711** [comment]
is there any way to separate these two?

**Comment by nicm** [comment]
You could perhaps configure your terminal to send something different for `Tab`, but you would need to configure it in tmux (and every application you use outside tmux).
