### ISSUE TITLE
Statusline overflows on using multibyte characters

### ISSUE THREAD

**Issue by ayogakar** [tmux/tmux#2623]
### Issue description

Tmux statusline overflows when using a multibyte character. Each statusline redraw keeps on flooding the screen.

![tmux-statusline](https://user-images.githubusercontent.com/10193845/112132678-e24c5f80-8bf0-11eb-8d59-4d0bae28b4e5.png)

Minimal `.tmux.conf` for reproducing the issue -
```
set-option -g status-right "#(printf '\U0001F50b') %H:%M "
```

### Required information

Please provide the following information:

* tmux version (`tmux 3.1c`)
* Platform (`Linux x86_64`). It's RHEL 7.9
* $TERM inside (`screen`) and outside of tmux (`xterm-256color`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-server-39017.log](https://github.com/tmux/tmux/files/6188726/tmux-server-39017.log)
[tmux-out-39017.log](https://github.com/tmux/tmux/files/6188728/tmux-out-39017.log)
[tmux-client-39015.log](https://github.com/tmux/tmux/files/6188729/tmux-client-39015.log)

**Comment by nicm** [comment]
Try building tmux with utf8proc.

**Comment by ayogakar** [comment]
Still same result (Using master this time instead of the latest release)

**Comment by nicm** [comment]
Show me logs from starting tmux and then doing the printf at the shell inside tmux and then exiting tmux please.

**Comment by ayogakar** [comment]
[tmux-client-17259.log](https://github.com/tmux/tmux/files/6189116/tmux-client-17259.log)
[tmux-out-17261.log](https://github.com/tmux/tmux/files/6189117/tmux-out-17261.log)
[tmux-server-17261.log](https://github.com/tmux/tmux/files/6189118/tmux-server-17261.log)

**Comment by nicm** [comment]
Your platform libc does not recognise this character (wcwidth is returning -1), so tmux assumes it is width 1 when in fact it looks like it is actually width 2.

If utf8proc doesn't have the correct width either, you will need to either upgrade one of libc or utf8proc and see if that helps, choose a different character, or see if there is a terminal or font that does have this as width 1.

**Comment by ayogakar** [comment]
Thanks for looking into it.

I can't update my platform's libc however i'm using separate toolchain(gcc, cmake etc) to build everything from scratch (tmux & utf8proc included). Also i'm using latest utf8proc.

Is there any way to have check for specific characters and pass them as 2 width like maybe in `utf8.c`  line 251?

**Comment by nicm** [comment]
You could patch tmux to do that if you like.

**Comment by ayogakar** [comment]
My previous build was referencing wrong utf8proc. After fixing that some multibyte characters are fine now however some single width icons are still causing the overflow. The width reported by `utf8proc_wcwidth`  is 1 which is correct for this character but it's still overflowing.
 
```
set-option -g status-right "#(printf '\U0001F5F2') "
```

![Screenshot (20)](https://user-images.githubusercontent.com/10193845/112609611-bd026000-8e41-11eb-9931-f388fed79bdf.png)

Logs -
[tmux-client-43294.log](https://github.com/tmux/tmux/files/6210613/tmux-client-43294.log)
[tmux-out-43296.log](https://github.com/tmux/tmux/files/6210614/tmux-out-43296.log)
[tmux-server-43296.log](https://github.com/tmux/tmux/files/6210615/tmux-server-43296.log)

**Comment by nicm** [comment]
You have to print the character at the shell because tmux does not log the width if it is only in the status line.

**Comment by ayogakar** [comment]
[tmux-client-62944.log](https://github.com/tmux/tmux/files/6212477/tmux-client-62944.log)
[tmux-out-62946.log](https://github.com/tmux/tmux/files/6212479/tmux-out-62946.log)
[tmux-server-62946.log](https://github.com/tmux/tmux/files/6212480/tmux-server-62946.log)

**Comment by nicm** [comment]
Can you show me logs + screenshot from doing this inside tmux please?
~~~~
printf 'a\360\237\227\262b\n'
~~~~

**Comment by ayogakar** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/10193845/112684592-3ed1a800-8e99-11eb-9e94-101c0a91926c.png)

[tmux-client-16602.log](https://github.com/tmux/tmux/files/6213988/tmux-client-16602.log)
[tmux-out-16604.log](https://github.com/tmux/tmux/files/6213990/tmux-out-16604.log)
[tmux-server-16604.log](https://github.com/tmux/tmux/files/6213991/tmux-server-16604.log)

**Comment by nicm** [comment]
If you do `C-b r` after that printf, does it redraw correctly (the text in the pane, not the status line)?

**Comment by nicm** [comment]
This is strange because tmux has the correct width (1) and it is moving the cursor correctly:
~~~~
1616787535.446348 screen_write_collect_end: 1 a (at 0,2)
...
1616787535.446385 screen_write_collect_end: 1 b (at 2,2)
~~~~
The a is at 0 and the b at 2 which means it has correctly worked out that that 🗲 is width 1.

So I am not sure why it is printing an extra space at the end of the status line.

Does it make any difference if you do without the `#()` in `status-right`:
~~~~
set-option -g status-right "\U0001F5F2"
~~~~

**Comment by nicm** [comment]
Oh you have an extra space at the end of status-right... duh.

**Comment by nicm** [comment]
If you do the `printf 'a\360\237\227\262b\n'` outside tmux, how does it look?

**Comment by ayogakar** [comment]
> 
> 
> This is strange because tmux has the correct width (1) and it is moving the cursor correctly:
> 
> ```
> 1616787535.446348 screen_write_collect_end: 1 a (at 0,2)
> ...
> 1616787535.446385 screen_write_collect_end: 1 b (at 2,2)
> ```
> 
> The a is at 0 and the b at 2 which means it has correctly worked out that that 🗲 is width 1.
> 
> So I am not sure why it is printing an extra space at the end of the status line.
> 
> Does it make any difference if you do without the `#()` in `status-right`:
> 
> ```
> set-option -g status-right "\U0001F5F2"
> ```

removing the #(printf) call doesn't make any difference with or without the extra space at the end.

outside of tmux -
![Screenshot (22)](https://user-images.githubusercontent.com/10193845/112687097-f5835780-8e9c-11eb-95bf-fbd205893c5d.png)

**Comment by nicm** [comment]
What terminal are you using? Is this the same xterm?

**Comment by ayogakar** [comment]
windows terminal + ssh

**Comment by nicm** [comment]
Can you try it in a different terminal and see if it is the same?

I take it the status line is OK if you don't put any Unicode in status-right?

**Comment by ayogakar** [comment]
Same result with konsole.

Status line is fine if i use basic latin symbols and some unicode onces too like battery icon "\U0001F50B"

**Comment by nicm** [comment]
What do you see if you do this outside tmux, show me a screenshot please (you may need to do `eval $(resize)` first).
~~~~
printf "\033#8\033[${LINES};$(expr $COLUMNS)H\360\237\227\262\033[H"

**Comment by ayogakar** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/10193845/112688557-0e8d0800-8e9f-11eb-9217-efac175123e7.png)

**Comment by nicm** [comment]
Looks like your terminal is not handling this character correctly, it should not be wrapping the line (unless automargins are off and then it would be the same with any character). Maybe your font has an incorrect width or something? Does it work with a different font?

**Comment by nicm** [comment]
I assume it doesn't wrap if you do, for example:
~~~~
printf "\033#8\033[${LINES};${COLUMNS}HZ\033[H"

**Comment by ayogakar** [comment]
Yeah, strange. Its not wrapping with this but using a different font doesn't make any difference. The one with the unicode still wraps around.

**Comment by nicm** [comment]
It seems like a terminal or font problem anyway, none of the terminals I have here wrap.

**Comment by ayogakar** [comment]
Ok. Thanks for your help. Will try some more fonts as i don't believe both windows terminal and console are suffering from same problem. Otherwise will dig around to make it work on my setup.

**Comment by ayogakar** [comment]
Posting here for anyone else who runs into this. It was an issue with both the terminals. Using [terminus](https://github.com/Eugeny/terminus) solved it.
