### ISSUE TITLE
Unknown command: window-size 

### ISSUE THREAD

**Issue by 1mamute** [tmux/tmux#2624]
### Issue description
I use VS Code terminal when I'm coding but sometimes I leave a Gnome Terminal open to watch the logs in full screen. Since i'm using the same session, I looked for a way to resize the window dynamically if i'm in VSCode terminal (smaller) or gnome terminal (full screen).

The setting `setw -g aggressive-resize on` worked but I arrived in another problem. The window size is filled with dots in accord to the smallest window open, in this case, the VSCode terminal. 

I wanted to automatically resize the window following the latest window. If i switch to Gnome Terminal, I want tmux to be full screen, and If i go to the vscode terminal, I want tmux to be the smaller.

Seems like **aggressive-resize** default behavior is to follow the smallest window open in the session, so in the man pages of tmux I find the setting `window-size largest | smallest | manual | latest` which **latest** seems to be exactly what I'm looking for.

I tried the above, but none seems to work, it shows "unknown command" or "unknown option", any ideias to achieve to this behavior?

`setw -g window-size latest`
`set-option -wg window-size latest`

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux next-3.3
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): Inside tmux: xterm-256color / Outside tmux: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`): I don't see any logs.

**Comment by nicm** [comment]
Your tmux is too old.

**Comment by 1mamute** [comment]
> Your tmux is too old.

I cloned this repository and builded from the source before opening the issue. My tmux -V returns tmux next-3.3, is there any new version?

**Comment by nicm** [comment]
Are you sure you are running the tmux you actually built and that you killed the old one properly before starting the new?

**Comment by 1mamute** [comment]
Just noticed I had two tmux binaries in my system as you can see in the print below.

I found them using `sudo find . -executable -type f -name "tmux"`
![image](https://user-images.githubusercontent.com/22196761/112634445-5cf7c380-8e19-11eb-9cb5-8f6ebf8843fb.png)

Running `/usr/bin/tmux -V` returned tmux 2.6 and running `/usr/local/bin/tmux -V` returned tmux next-3.3. The new tmux version I compiled from the source was thrown in the **/usr/local/bin** directory and I was using the old one.

The fix was to kill every running session running in tmux and make a backup of the old version I had of tmux (just in case)
`sudo cp /usr/bin/tmux /usr/bin/tmux-bkp`

Copy the new version in my local folder to the usr folder
`sudo cp /usr/local/bin/tmux /usr/bin/ `

After that, the `setw -g window-size latest` setting is running as intended and will help a lot with my workflow,

Thanks for the help!
