### ISSUE TITLE
[Feature Request] Add an option for `display` to keep message no matter key is pressed

### ISSUE THREAD

**Issue by kevinhwang91** [tmux/tmux#2625]
### Issue description

I add a task to another session and display a message when it's finished. But when I was typing quickly, I can't see the message totally.
I want to keep the message to respect `display-time` or `-d delay` option.

### Required information

Please provide the following information:

* tmux version `tmux next-3.3`
* Platform `ArchLinux`
* $TERM inside and outside of tmux `tmux-256color` and `alacritty`

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/6295422/x.diff.txt)

**Comment by kevinhwang91** [comment]
It works! Feel free to close this issue if merged.

**Comment by nicm** [comment]
Great - applied to OpenBSD now, will be in GitHub later. Thanks!
