### ISSUE TITLE
TMUX Keeps Exiting and killing all my sessions.

### ISSUE THREAD

**Issue by iAmG-r00t** [tmux/tmux#2626]
Hello so I have a script that creates a tmux session then run some few commands, so it actually works really great but the problem is tmux keeps exiting and killing all sessions, I have tried to debug but to be honest I really don't know what is the issue and the tmux logs understanding them is also a pain. Kindly assist, below are the details of my enviroment.

```sh
# Tmux version
tmux 3.0a

# Linux Box version
Linux x86_64

# TERM outside tmux
xterm-256color

# TERM inside tmux
screen-256color
```

- Attached are also the logs, kindly assist, I also googled and I thought it was about the default shell and placed the following: `set -g default-shell /bin/bash` in my tmux config file but nothing has changed.

**Comment by nicm** [comment]
Does this still happen if you build tmux from master?

**Comment by iAmG-r00t** [comment]
That's what I want to try now, let me try and build from master, I had installed it with apt.

**Comment by iAmG-r00t** [comment]
So if I build from source it still exits out.

**Comment by iAmG-r00t** [comment]
Also the new version of tmux doesn't understand either -v or -vv for logs, so I can't get any logs.

**Comment by nicm** [comment]
You put the `-v` after the `tmux` and before the `new-session`.

**Comment by iAmG-r00t** [comment]
It still exits when I build from source, and it only provides client logs and not server logs, why ?

**Comment by iAmG-r00t** [comment]
I really don't understand what can be the issue please help.

**Comment by nicm** [comment]
If it only provides client logs, it means that you didn't kill the server properly. Make sure you do `tmux kill-server` before testing.

**Comment by iAmG-r00t** [comment]
Ohhh okay let me repeate that again, but I noticed that it exits unexpectedly when I ran this command to get the silence flags for the windows: `tmux lsw -t MassScan -F '#{window_silence_flag} #{window_name}'`

**Comment by iAmG-r00t** [comment]
@nicm I killed the tmux server properly, started my script, and still tmux exits after a while and tmux only provides the client log and no server log. This is the tmux version that I built from the master.

**Comment by nicm** [comment]
Are you absolutely sure there was no tmux running?

Are you checking for the log file in the directory where tmux was first started?

What is in your script?

**Comment by iAmG-r00t** [comment]
Yeah, I killed the server before running tmux, I actually even went ahead and deleted tmux the socket folder path at `/tmp`, but I have started the script again and I can see it has created the server log, I am currently waiting for the server to exit so that I can send the logs. and yes I was checking for the log file in the directory where tmux was first started.

My script basically checks if there is a session named masscan and if there isn't it creates it, then proceeds creating several windows and then sends commands to be executed on each window.

It has a status logic where it check the pid's of those commands if they are present in `/proc` folder and if there are not present it means the commands are done then proceeds to check the silence flag for each window and if the flag for each window is 1 it sends a notification to inform me that the commands have completed successfully, then clears the silence flags then proceeds executing other commands on the windows.

That's basically what's in my script.

**Comment by nicm** [comment]
You didn't attach a link?

**Comment by iAmG-r00t** [comment]
[Here](https://gofile.io/d/5Qp7O3) attached.

**Comment by nicm** [comment]
This log is still from tmux 3.1c, not from master. Can you show me the log from master? You can just first show me the last 10,000 lines (`tail -10000 tmux-server*.log >newlog.txt`).

**Comment by iAmG-r00t** [comment]
I built it from github release files, that isn't the latest version??

**Comment by iAmG-r00t** [comment]
Because at first I was installing tmux from apt and the version was 3.0a

**Comment by nicm** [comment]
You need to install autoconf.

**Comment by nicm** [comment]
Also automake.

**Comment by iAmG-r00t** [comment]
I have started the script, made sure I have killed the tmux server, but I haven't seen any tmux-server file created but just a tmux client file. So will it create the tmux server log file when it exits or ??

**Comment by nicm** [comment]
No it should create it when it starts same as before.

**Comment by iAmG-r00t** [comment]
It doesn't create the tmux server log file.

I am executing the -v option on tmux -v new -s $session_name -n main.. should I place the -v option on the start-server command.

**Comment by nicm** [comment]
Yes you have to have -v when the tmux server is started whether that be start-server or new-session.

**Comment by iAmG-r00t** [comment]
What if I am only using it on new session only??

**Comment by nicm** [comment]
If the server is already started then you will not get a server log, you must use -v on whichever command starts the server.

**Comment by iAmG-r00t** [comment]
Ohhh that's why, let me edit and rerun the script again.

**Comment by iAmG-r00t** [comment]
Okay, waiting for it to fail, the server log file has been created.

**Comment by nicm** [comment]
It exited because there are no sessions. It doesn't look like you created
any. Are you sure the is the same server you are using in your script?

**Comment by iAmG-r00t** [comment]
Yep I am let me send another log file, it exits alot of times for sure.

**Comment by iAmG-r00t** [comment]
Here are the logs ...

[tmux-client-34290.log](https://github.com/tmux/tmux/files/6239253/tmux-client-34290.log)
[tmux-client-34299.log](https://github.com/tmux/tmux/files/6239255/tmux-client-34299.log)
[tmux-server-34292.log](https://github.com/tmux/tmux/files/6239256/tmux-server-34292.log)

**Comment by iAmG-r00t** [comment]
and from this screenshot, this is my script in debug mode and as you can see the server exited unexpectedly!!

![image](https://user-images.githubusercontent.com/29776892/113207058-d7d93800-9278-11eb-9969-1974005180e0.png)

**Comment by nicm** [comment]
This server also exited because there were no sessions remaining, I guess
all the programs you are running in tmux have exited. I can look more
closely tomorrow.

**Comment by iAmG-r00t** [comment]
Sure, thanks alot.

**Comment by nicm** [comment]
The word "MassScan" does not appear in your server log. I don't think you are getting the right server to log. Try adding -v to all the times you use start-server or new-session and see if you get multiple server logs.

**Comment by iAmG-r00t** [comment]
Sure let me do so right now on the test servers that are failing.

**Comment by iAmG-r00t** [comment]
![image](https://user-images.githubusercontent.com/29776892/113210383-d578dd00-927c-11eb-9d93-87ded83d3ba1.png)

Will this work ...

**Comment by iAmG-r00t** [comment]
Yep, I can see multiple server logs, let me wait for it to exit out then send the log files.

**Comment by iAmG-r00t** [comment]
Here are the logs that contain the word "MassScan" for both the clients and servers from two different servers.
[tmux-server-30042_10k.log](https://github.com/tmux/tmux/files/6239883/tmux-server-30042_10k.log)
[tmux-server-36772_10k.log](https://github.com/tmux/tmux/files/6239884/tmux-server-36772_10k.log)
[tmux-client-30047.log](https://github.com/tmux/tmux/files/6239887/tmux-client-30047.log)
[tmux-client-36777.log](https://github.com/tmux/tmux/files/6239888/tmux-client-36777.log)

**Comment by nicm** [comment]
OK so neither of these servers existed properly but there is no fatal error. If you do `ulimit -cunlimited` before you run the test, does tmux leave a core file (look for something called `*core*` in the same place as the logs)?

**Comment by iAmG-r00t** [comment]
Wait, so I kill the server then run `tmux ulimit -cunlimited` or just `ulimit -culimited` ?

**Comment by nicm** [comment]
Kill the server, then do `ulimit -cunlimited` at the shell, then run your test from the same shell.

**Comment by iAmG-r00t** [comment]
Nop, I don't get any file called with the word `*core*`

**Comment by iAmG-r00t** [comment]
This is what I did, run the command then executed the script.

![image](https://user-images.githubusercontent.com/29776892/113260283-bf980600-92d6-11eb-8559-3fc042b8fdcd.png)

**Comment by nicm** [comment]
Why are you doing start-server and source-file here? new-session will create a server by default and it will load .tmux.conf.
~~~~
tmux -v start-server && tmux -v new -d -s Default -n main && tmux source-file $HOME/.tmux.conf 
~~~~

Anyway, please install strace and run tmux using it:
~~~~
strace -tt -fostrace.out tmux new -d -s Default -n main
~~~~
If you do need the source-file you can add it as well after this (`&& tmux source-file $HOME/.tmux.conf`).

Then kill tmux and run your script and when it exits unexpectedly show me the strace.out file.

**Comment by iAmG-r00t** [comment]
Okay, let me edit the first line and let it only have: 

`tmux -v new -d -s Default -n main && tmux source-file $HOME/.tmux.conf`

I am sourcing the `tmux.conf` file to make sure the config has been sourced because I want to make sure some settings have been placed because they are being used in the script logic.

So I have a question, should I add the strace command in my script, and if yes should I add it when its creating the masscan session or both (masscan and default) sessions.

Also should I first run this command first: `strace -tt -fostrace.out tmux new -d -s Default -n main
` then run the script without editing it / adding the strace command as I have asked above?

**Comment by nicm** [comment]
You should add it to whichever command starts the server. If there is no server running then the first session you create will start the server so you should add it to that. But it can do no harm to add it to both so long as you use different filenames (so change `strace.out` to something else for each one).

**Comment by iAmG-r00t** [comment]
Ohhh okay then, let me do that.

**Comment by iAmG-r00t** [comment]
My script keeps exiting, trying to run the two commands in the background but doesn't work, any way you know I can execute strace and for my script to still continue ...

**Comment by nicm** [comment]
Why do you need to run tmux in the background?

**Comment by nicm** [comment]
No it doesn't...
~~~~
$ strace -fostrace.out tmux new -d
$
~~~~

**Comment by nicm** [comment]
Oh wait sorry you are right! I had an existing server.

**Comment by iAmG-r00t** [comment]
I will send the logs once it errors out.

**Comment by iAmG-r00t** [comment]
So at first it was weird that tmux was not exiting, which it hasn't but now I have an issue with strace, giving me this error: `strace: default_strace.out: No space left on device`. What should I do??

**Comment by nicm** [comment]
This means strace has filled up your disk with the log file. You should probably stop it and maybe try again.

**Comment by iAmG-r00t** [comment]
Okay, the sessions are still there, they haven't exited. but my script exitied hence I will have to start it again. But one of the strace files exited out but the session is still there.
[masscan_strace.log](https://github.com/tmux/tmux/files/6251186/masscan_strace.log)

**Comment by nicm** [comment]
If tmux did not exit unexpectedly then the strace is of no use. But it's funny but didn't.

**Comment by iAmG-r00t** [comment]
Okay let me restart it again, I think I will focus with one strace file for one session if that's okay

**Comment by iAmG-r00t** [comment]
Yep, we have a log. It exited. find attached.
[masscan_strace.log](https://github.com/tmux/tmux/files/6251380/masscan_strace.log)

**Comment by iAmG-r00t** [comment]
Hey @nicm have you checked out the log file??

**Comment by nicm** [comment]
This strace is far too short to be from the tmux server and does not include forking any child processes, this looks like an strace from a single client. Are you sure you used `-f` with strace, and are you sure you used strace the very first time you started tmux (ie when you created the server)?

**Comment by iAmG-r00t** [comment]
I think I know what the issue is, the command that starts the server is the one that gave me this error: `strace: default_strace.out: No space left on device`. So let me start it again and send that log file.

**Comment by iAmG-r00t** [comment]
Is there any other way to get the log without it giving me an this error: `strace: default_strace.out: No space left on device`. The log is 22GB how they hell do I send all that ...??

**Comment by nicm** [comment]
If it is getting to 22 GB without exiting then I guess probably it is not going to exit. I think you will need to show me your script.

**Comment by iAmG-r00t** [comment]
Hey I have a log of about 11gigs, tmux has exited out now question is how do I send you the log??

**Comment by nicm** [comment]
Show me the last 20000 lines or so first. You can attach them to the issue.

**Comment by iAmG-r00t** [comment]
both last and first or just last??

**Comment by iAmG-r00t** [comment]
Plus you want the logs from the command that started the server right??

**Comment by iAmG-r00t** [comment]
Here are the first and last 20000 lines...

[strace_last.log](https://github.com/tmux/tmux/files/6259453/strace_last.log)
[strace_first.log](https://github.com/tmux/tmux/files/6259455/strace_first.log)

**Comment by nicm** [comment]
Looks like PID 58222 was the tmux server to me.
~~~~
58222 +++ killed by SIGKILL +++
~~~~
Are you sending the server SIGKILL?

**Comment by iAmG-r00t** [comment]
nop, it exits by itself. My script just checks if the session is present that's it. Doesn't send any SIGKILL.

![image](https://user-images.githubusercontent.com/29776892/113673798-167c5180-96c2-11eb-86e0-ee23f1c11f2b.png)

**Comment by iAmG-r00t** [comment]
See the error... server exited unexpectedly.

**Comment by nicm** [comment]
Something is sending it SIGKILL, either it is you or your script doing it by accident or the kernel is doing it. Are you killing anything with `kill -9` or `kill -KILL` in your script?

**Comment by iAmG-r00t** [comment]
Nop, my script doesn't have any `kill -9` or `kill -KILL`

**Comment by iAmG-r00t** [comment]
I have around 20 plus servers running the script and from the 20 there are about 7 servers where the server exits unexpectedly, so I don't think its my script from my end because if it was my script all 20 plus servers will be having the same issue.

**Comment by nicm** [comment]
tmux never sends itself SIGKILL so something is. Are you sure the OOM killer isn't killing it?

**Comment by iAmG-r00t** [comment]
what is OOM??

**Comment by iAmG-r00t** [comment]
How does it kill it while the error tmux gives me is `server exited unexpectedly` ??

**Comment by nicm** [comment]
That error comes from the tmux client, it means the tmux server exited when it did not expect it to, it is consistent with either tmux crashing or being killed with -9.

**Comment by iAmG-r00t** [comment]
So it can be tmux crashing right

**Comment by iAmG-r00t** [comment]
Can tmux caused to crash because of the server overloading??

**Comment by nicm** [comment]
Yes but if tmux was crashing it would say "SIGSEGV" or "SIGILL" or something in the strace, not "SIGKILL" which means something else killed tmux.

If you run out of memory then the OOM killer will kill processes. *Are* you running out of memory?

**Comment by iAmG-r00t** [comment]
Yeah I think I am running out of memory, let me run the script again and check

**Comment by iAmG-r00t** [comment]
Hmmmmm, can this cause the OOM killer to kill the processes.

![image](https://user-images.githubusercontent.com/29776892/113705028-9962d380-96e5-11eb-95ad-6c44f092a82a.png)

**Comment by nicm** [comment]
I don't know what you are showing me, what does `top` say on the Mem/Swap lines?

**Comment by iAmG-r00t** [comment]
Mem: 485M/981M ... the server doesn't have `Swp`.

**Comment by nicm** [comment]
It should not be killing anything with only half the memory used, so unless the memory is increasing to the maximum, it must be something else.

**Comment by iAmG-r00t** [comment]
How can I debug this ??

**Comment by nicm** [comment]
Check the syslog messages on the servers where tmux is exiting, is there anything funny? If it is hitting OOM, it will be logged. Likewise if tmux crashes you may get a log message.

**Comment by iAmG-r00t** [comment]
the second logs could you check them and see if its the same thing ...

[strace_last.log](https://github.com/tmux/tmux/files/6264973/strace_last.log)
[strace_first.log](https://github.com/tmux/tmux/files/6264974/strace_first.log)

**Comment by nicm** [comment]
Yes PID 62682 is tmux server, you can tell because for example it binds to the socket
~~~~
62682 bind(6, {sa_family=AF_UNIX, sun_path="/tmp/tmux-0/default"}, 110) = 0
62682 umask(022)                        = 0117
62682 listen(6, 128)                    = 0
~~~~
And it is killed:
~~~~
62682 +++ killed by SIGKILL +++
~~~~

**Comment by iAmG-r00t** [comment]
Yep you were right, I have found the culprit.

![image](https://user-images.githubusercontent.com/29776892/113719186-054d3800-96f6-11eb-9df1-daf94a77e01a.png)

OOM kills tmux server because the server ends because the server runs out of memory.

**Comment by nicm** [comment]
Do you have a really big `history-limit` configured and lots of output?

**Comment by nicm** [comment]
You need more memory or fewer processes if OOM is killing tmux for only using 400 MB...

**Comment by iAmG-r00t** [comment]
Yeah, let me work on that. Thanks alot man.
