### ISSUE TITLE
Any way to enable some sort of TouchScreen scrolling ?

### ISSUE THREAD

**Issue by Eluminae** [tmux/tmux#2627]
Hello there,

I'm trying to configure tmux on a phone device and I'm looking for a simple way to scroll. 

I'd like to know if there is a way to use MouseDrag1 to grab a line and make the panel scroll on dragging by example. Or if some configs would allow this kind of scroll.

Thanks a lot for replies !

**Comment by lockejan** [comment]
Hey,
have you checked the man page? 
I would try using `set -g mouse on` in `.tmux.conf`.
I use this for trackpad scrolling.
Could work as well for your case...

**Comment by Eluminae** [comment]
Of course I am using `set -g mouse` in my `.tmux.conf`…

What I am a talking here is not related to wheel up/down events. I talk about mouse button1 grabbing to scroll the pane content.

**Comment by nicm** [comment]
Try this, you will need to be running master and you will need to enter copy mode first (it should be simple to make similar key bindings for the root table to enter copy mode):
~~~~
set -g mouse on
unbind -Tcopy-mode MouseDrag1Pane
bind -Tcopy-mode MouseDown1Pane set -gF @drag_start '#{mouse_y}'
bind -Tcopy-mode MouseDragEnd1Pane run -C {
    if -F '#{e|>:#{mouse_y},#{@drag_start}}' {
        run -C {
            send -XN '#{e|-:#{mouse_y},#{@drag_start}}' scroll-down
        }
    } {
        run -C {
            send -XN '#{e|-:#{@drag_start},#{mouse_y}}' scroll-up
        }
    }
}
~~~~

**Comment by Eluminae** [comment]
Very nice ! With very few tweaks I got : 

```
set -g mouse on
unbind -Tcopy-mode MouseDrag1Pane
unbind -Tcopy-mode MouseDragEnd1Pane
bind -Troot MouseDown1Pane copy-mode
bind -Tcopy-mode MouseDown1Pane set -gF @drag_start '#{mouse_y}'
bind -Tcopy-mode MouseDrag1Pane run -C {
    if -F '#{e|>:#{mouse_y},#{@drag_start}}' {
        run -C {
            send -XN '#{e|-:#{mouse_y},#{@drag_start}}' scroll-up
            set -gF @drag_start '#{mouse_y}'
        }
    } {
        run -C {
            send -XN '#{e|-:#{@drag_start},#{mouse_y}}' scroll-down
            set -gF @drag_start '#{mouse_y}'
        }
    }
}
```

I only got sometime a message "repeat range too small". Any idea of the reason ?

**Comment by nicm** [comment]
If you don't drag far enough it will end up with a repeat count of 0 which is too small, you could fix that by checking for 0 in the send and replacing with 1, something like (not tested):
~~~~
            send -XN '#{?#{e|!=,#{mouse_y},#{@drag_start}},#{e|-:#{mouse_y},#{@drag_start}},1}' scroll-up

**Comment by Eluminae** [comment]
Here probably is my final word:

* double tap to start copy-mode
* finger scroll 
* double tap to start selection
* release to copy and go back to root mode

```
set -g mouse on
unbind -Tcopy-mode MouseDragEnd1Pane
bind -Tcopy-mode MouseDragEnd1Pane run -C {
    if -F '#{selection_active}' {
        send -X copy-pipe-and-cancel
    }
}
unbind -Troot DoubleClick1Pane
bind -Troot DoubleClick1Pane copy-mode
unbind -Tcopy-mode DoubleClick1Pane
bind -Tcopy-mode DoubleClick1Pane run -C {
    select-pane; send -X begin-selection
}
bind -Tcopy-mode MouseDown1Pane set -gF @drag_start '#{mouse_y}'
unbind -Tcopy-mode MouseDrag1Pane
bind -Tcopy-mode MouseDrag1Pane run -C {
    if -F '#{e|>:#{mouse_y},#{@drag_start}}' {
        run -C {
            send -XN '#{e|-:#{mouse_y},#{@drag_start}}' scroll-up
        }
    }
    if -F '#{e|<:#{mouse_y},#{@drag_start}}' {
        run -C {
            send -XN '#{e|-:#{@drag_start},#{mouse_y}}' scroll-down
        }
    }
    set -gF @drag_start '#{mouse_y}'
}
```

I'm not sure if I really have to unbind keys but, meh
