### ISSUE TITLE
Process exits if it cannot write to log file

### ISSUE THREAD

**Issue by surlyhacker** [tmux/tmux#2630]
### Issue description

Honestly I am just logging this issue to feel better about myself and feel whole again, but hopefully it is at least contributing an idea worth considering. =)

tmux [explicitly exits](https://github.com/tmux/tmux/blob/4208641de7045299a10f51209bec4623cbea6744/log.c#L120) if it cannot write to its log file (when configured to log).  In particular, this happens on 32-bit systems (which maybe are no longer even supported) when the log file reaches 2,147,483,647 bytes, which is 1 byte less than 2GB.  I suspect this is because `fprintf()` fails in such a situation.  My request would be for it to not exit but keep running and perhaps report the logging error in some other way if possible.  (inject it into the first tmux window?  report it to the parent shell on user-initiated process exit?).  I know it's debatable whether this is a good idea. (who would want to log for that long?; who still uses 32-bit? etc)

Backstory: 
My tmux (via byobu) hung and would not accept new clients.  It was taking up 100% CPU.  So I happened to find this bug #2053.
So I decided to take on the challenge of restoring the process via gdb.  After reading the [code change](https://github.com/tmux/tmux/commit/36eb16ce7db2db71b510964a2e453e6b349b03f0) that seems to have been used to fix the bug, and a few hours of tinkering, I successfully used gdb to dynamically change the relevant register used in the call to (in my case) `format_trim_left()` from format-draw.c and got the code to exit the infinite loop cleanly, and my tmux was restored to life and would accept new clients and worked fine.  Of course I then forgot that a few hours earlier I had sent SIGUSR2 to enable logging, and so eventually the log hit the aforementioned limit and the process exited.  So sad.  Also no idea what caused the invalid UTF-8 char that triggered the bug.

Sorry I did not bother reproducing this.

Please provide the following information:

* tmux version: tmux 2.9a (but this code is present in 3.2)
* Platform: Linux i686 (yes 32-bit is relevant here)
* $TERM inside and outside of tmux: screen-256color and xterm
* Logs from tmux.  Here is the last line logged:
`1616996777.780218 format_expand1: found #{}: T:wi` (no CR/LF made it in)

**Comment by nicm** [comment]
Yes this is silly I'll remove it.

**Comment by nicm** [comment]
Changed in OpenBSD now, will be in GitHub later. Thanks!

**Comment by surlyhacker** [comment]
Thanks so much.  I am honored.
