### ISSUE TITLE
[Feature Request] Disabling line-wrap

### ISSUE THREAD

**Issue by dpacbach** [tmux/tmux#2635]
This has been requested before but the issues are locked so I cannot +1 them ;-)  There are use cases where using a terminal-level or shell-script-level (e.g. pipes) solution is not ideal.  The way this would ideally work is that each pane would have a line-wrapping toggle.  When line-wrapping is on, it would behave as it does now.  When it is off, lines would be cut off at the column width, but the remainder of the cropped lines would still be available if either line-wrapping is disabled in the pane or if the user expands the size of the pane to reveal more.

**Comment by topcat001** [comment]
Other software (editors come to mind) which allow line wrapping also allow horizontal scrolling when wrapping is turned off. A proper implementation would need to add this feature as well I think.
- We would need to add a horizontal offset to all the code to be able to position the visible area on the backing grid, and this would become a two dimensional problem in copy mode. Of course we could support it only in live mode but it would be a bit odd then.
- There is also the question of how selections/highlighting would be handled. I can see some tricky edge cases.

It's already in the TODO list but it's a fair bit of work.

**Comment by nicm** [comment]
I think it would be a lot of work for something that is rarely of practical use.

**Comment by dpacbach** [comment]
As a first step, to make things easier for the implementer, I think we can omit horizontal scrolling when wrapping is off.  If the user then wants to see the remainder of the lines, they can enable wrapping temporarily to take a look, then go back to disabled wrapping.  This would basically solve most use cases I think while hopefully making it easier to implement.

**Comment by nicm** [comment]
This is already in the TODO file, but TBH unless you are going to do it, I probably wouldn't expect it anytime soon. Thanks!
