### ISSUE TITLE
Ability to display an error post-configuration

### ISSUE THREAD

**Issue by deliciouslytyped** [tmux/tmux#2637]
I'm on tmux 3.1c and there doesn't appear to be a decent default way to raise an error message from the tmux config. display-message seems to work but disappears rather quickly, and I don't want to mess with other parts of the user's config.

I've tried messing around with buffers and such, but none of that seems to work while in tmux's configuration phase.

What I'd like is to be able to show a popup, or something of the sort, where one can then press a key to continue.
Using a menu with a session-created hook *almost* works, but with whatever happens, it also disappears immediately.

**Comment by nicm** [comment]
In master you could maybe do something with `run -bd`. But how would you like it to work?

**Comment by deliciouslytyped** [comment]
I forgot to say, I would be happy with something like tmux's current interface for when it experiences some kind of error (the one where you get a pane with the error message), but I couldn't figure out how to replicate that as a user.

**Comment by nicm** [comment]
We should make it so display-message during config execution goes to the config messages list.

**Comment by deliciouslytyped** [comment]
Is it possible to cause the same kind of behaviour while in "normal" mode?

**Comment by nicm** [comment]
`run "echo foo"` or `tmux run -t$TMUX_PANE "echo foo"`.

**Comment by deliciouslytyped** [comment]
Ok the behaviour of the colon parameter to `-t` is something I tried to search for and couldn't find. The man page says 
```
Af‐
             ter it finishes, any output to stdout is displayed in copy mode (in the pane specified by -t or the current pane if omitted). 
```
I tried searching for everything except "copy mode".

**Comment by nicm** [comment]
You just need to specify some pane because without `-t` it will use the client's stdout.

**Comment by deliciouslytyped** [comment]
I also didn't know it's called copy mode. I tried seaching for stuff like "scrollback buffer" to no avail. :P

Anyway, what I'd like to get working is then something like, for example:
```
if-shell 'test -f "$nestcode_root"/active-row.conf' '' 'run -t: "The path is not configured correctly."'
```

(though the specific test will become irrelevant with https://github.com/tmux/tmux/issues/2638 )

**Comment by nicm** [comment]
Try this please: [y.diff.txt](https://github.com/tmux/tmux/files/6269894/y.diff.txt)

**Comment by deliciouslytyped** [comment]
It doesn't seem to do anything? I'm not sure which variant I should be trying.
Currently I'm doing `run -t: "echo hi"` in the config and there is no output.

**Comment by nicm** [comment]
No, with this patch use `display`.

**Comment by deliciouslytyped** [comment]
Sweet, LGTM I guess.

**Comment by nicm** [comment]
I have applied this now, thanks!
