### ISSUE TITLE
Configuration path variables

### ISSUE THREAD

**Issue by deliciouslytyped** [tmux/tmux#2638]
I'm on tmux 3.1c.

It would be useful for configuration if I could get the path of the currently "executing" (?) configuration file, as well as the main file tmux was asked to run with (e.g. what is passed to -f for example).

This would allow making "add-ins" that can use scripts relative to themselves, in their directory, as well as branching on which tmux configuration is currently selected, or being able to default to files located in the directory of the in-use configuration.

**Comment by nicm** [comment]
You will need to use master for this.

**Comment by nicm** [comment]
Actually maybe the change for current file didn't go in because the person who asked for it didn't test it, I'll dig it out later and you can try it.

**Comment by deliciouslytyped** [comment]
I started digging around in the source meanwhile and found this https://github.com/tmux/tmux/blame/12cfd0d22b630ead9c6d739b13c3409485ea551c/format.c#L2614 , is that (part of) what I need?

**Comment by nicm** [comment]
That is start up config files, but you want active config file, right?

**Comment by deliciouslytyped** [comment]
Yeah.

**Comment by deliciouslytyped** [comment]
Well, I don't know if that was clear; in case something gets sourced, I'd like to be able to get that path correctly from the code in the source as well.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/6269770/x.diff.txt)

**Comment by deliciouslytyped** [comment]
The nix build system stuff should be largely irrelevant; I can't figure out how to apply the patch correctly, or maybe I'm trying to apply it to the wrong revision (master)?:

```
$ nix-shell -p 'tmux.overrideAttrs (old: { patches = (old.patches or []) ++ [ (builtins.fetchurl { url = "https://github.com/tmux/tmux/files/6269770/x.diff.txt"; }) ]; src = fetchGit { url = "https://github.com/tmux/tmux/"; }; })'
these derivations will be built:
  /nix/store/9p909c91d95d4bdbn7573cghnq0dd2n9-tmux-3.1c.drv
building '/nix/store/9p909c91d95d4bdbn7573cghnq0dd2n9-tmux-3.1c.drv'...
unpacking sources
unpacking source archive /nix/store/991q6lpagpjnkpggg6rlhxivz8dxws04-source
source root is source
patching sources
applying patch /nix/store/3dp1vxkvmq727mp7yb0pf6b15nabsjad-x.diff.txt
can't find file to patch at input line 9
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|? tmux
|Index: cfg.c
|===================================================================
|RCS file: /cvs/src/usr.bin/tmux/cfg.c,v
|retrieving revision 1.82
|diff -u -p -r1.82 cfg.c
|--- cfg.c      22 Feb 2021 08:18:13 -0000      1.82
|+++ cfg.c      7 Apr 2021 07:33:48 -0000
--------------------------
File to patch:
Skip this patch? [y]
Skipping patch.
4 out of 4 hunks ignored
can't find file to patch at input line 74
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: tmux.1
|===================================================================
|RCS file: /cvs/src/usr.bin/tmux/tmux.1,v
|retrieving revision 1.831
|diff -u -p -r1.831 tmux.1
|--- tmux.1     1 Apr 2021 06:37:46 -0000       1.831
|+++ tmux.1     7 Apr 2021 07:33:49 -0000
--------------------------
File to patch:
Skip this patch? [y]
Skipping patch.
1 out of 1 hunk ignored
builder for '/nix/store/9p909c91d95d4bdbn7573cghnq0dd2n9-tmux-3.1c.drv' failed with exit code 1
error: build of '/nix/store/9p909c91d95d4bdbn7573cghnq0dd2n9-tmux-3.1c.drv' failed

```

**Comment by nicm** [comment]
You need to checkout master from Git.

**Comment by deliciouslytyped** [comment]
Ok, yeah, those are against master (but I'll double check I didn't mess something up in the expresion), and it just passes the patch to patch -p1; https://github.com/NixOS/nixpkgs/blob/0582cc9cc6c4dc1947a8dbeb0adc479b6ebcbeaf/pkgs/stdenv/generic/setup.sh#L948

I don't know how to debug `patch` failures.

**Comment by deliciouslytyped** [comment]
Ok I *think* it worked with `-p0`. It said the patches applied and I'm compiling now.

**Comment by deliciouslytyped** [comment]
Is there a cleaner way to format into a variable than: `run "setenv -g nestcode_root $(basename #{current_file})"`?

**Comment by nicm** [comment]
There is a modifier for basename and you can use run -C.

**Comment by nicm** [comment]
Or setenv -gF

**Comment by deliciouslytyped** [comment]
I see, very nice.
Also I keep saying basename when I mean dirname, but it's fine either way.

Am I missing something? Does run-shell expose different arguments when run from the config? If I run `tmux run-shell --help` it doesn't show the `-C` argument.

I got as far as `run -C "setenv -g nestcode_root #{d:current_file}"` working correctly, once in a session the variable is set, but the following errors:

```
run -C "setenv -g nestcode_root #{d:current_file}"
source "$nestcode_root"/active-row.conf
```
with
```
<my path>/tmux.conf:3: /active-row.conf: No such file or directory 
```

**Comment by deliciouslytyped** [comment]
(Ok it looks like tmux run-shell _outside_ a session doesn't list -C while inside it does.)

**Comment by nicm** [comment]
> (Ok it looks like tmux run-shell outside a session doesn't list -C while inside it does.)

You are running an old tmux binary outside.

Something like this should work:

setenv -gF nestcode_root '#{d:current_file}'
source -F '#{nestcode_root}/active-row.conf'

**Comment by deliciouslytyped** [comment]
`which tmux` seems to report the same binary both inside and outside, so unless tmux itself is somehow doing a different lookup internally...

Anyway, I didn't realize I can pass -F to setenv, or that env vars will show up in formats (makes sense I guess). 
That works now, thanks! I think everything looks good here.

**Comment by deliciouslytyped** [comment]
Ok one last question, the variable is `config_files`, why the plural? Should I be expecting a colon separated list or somesuch? How does tmux get multiple config files? - or does this enumerate every sourced file during the config phase?

**Comment by nicm** [comment]
config_files is comma-separated and you can have multiple because it can load /etc/tmux.conf, ~/.tmux.conf.

**Comment by nicm** [comment]
I applied this change also, thanks!
