### ISSUE TITLE
Statusbar contains weird characters

### ISSUE THREAD

**Issue by PenTestical** [tmux/tmux#2639]
### Issue description

The statusbar on tmux does not work as supposed to. I wasn't able to fix it. Any suggestions how to get it working?

![image](https://user-images.githubusercontent.com/57206134/113931813-352e3580-97f3-11eb-88ed-07c1a06bfcaf.png)

I am simply using the cyan [powerline statusbar](https://github.com/jimeh/tmux-themepack) from jimeh. Thanks in advance!

### Required information

* tmux version 3.1c
* Parrot OS 4.11, Debian 10
* $TERM inside: screen-256color, $TERM outside: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-server-21041.log](https://github.com/tmux/tmux/files/6274364/tmux-server-21041.log)
[tmux-client-21039.log](https://github.com/tmux/tmux/files/6274366/tmux-client-21039.log)
[tmux-out-21041.log](https://github.com/tmux/tmux/files/6274367/tmux-out-21041.log)

**Comment by nicm** [comment]
You probably need a different font?

**Comment by PenTestical** [comment]
How can I figure that out?

**Comment by nicm** [comment]
I don't know, ask the person who wrote the config? Doesn't powerline have its own font?

**Comment by PenTestical** [comment]
Doesn't require any special font, unfortunately.

**Comment by PenTestical** [comment]
Oh my god, I am dumb. There was a font needed. Thank you, solved the issue !!
