### ISSUE TITLE
[Feature Request] command for next session

### ISSUE THREAD

**Issue by ask-github** [tmux/tmux#2640]
i want to switch to next session without preview all sessions like next window

now, tmux can use choose-tree and use up, down arrow to navigate, it is slow.

is there a method to switch to next session directly?

**Comment by nicm** [comment]
Yes, defaults:
~~~~
bind-key    -T prefix       (                    switch-client -p
bind-key    -T prefix       )                    switch-client -n
bind-key    -T prefix       L                    switch-client -l

**Comment by ask-github** [comment]
thanks a lot
