### ISSUE TITLE
Tmux Tabline Colors Not Working

### ISSUE THREAD

**Issue by 0xd4y** [tmux/tmux#2641]
I cannot change the color of the tmux tabline. I tried experimenting with multiple colors, but the colors simply do not change for some reason. I included the snippet below to show that my terminal can display many colors. I'd really appreciate your help!

![image](https://user-images.githubusercontent.com/77868212/114230672-0cb35200-993f-11eb-9863-6a00a4552232.png)

.tmux.conf:

# vim style tmux config

# use C-a, since it's on the home row and easier to hit than C-b
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix
set -g base-index 1

# Easy config reload
bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# vi is good
setw -g mode-keys vi

#Set escape time to 30 miliseconds
set -sg escape-time 50
# mouse behavior
#set -g mode-mouse on
# allow terminal scrolling

set-option -g terminal-overrides 'xterm*:smcup@:rmcup@'
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g default-terminal "xterm-256color"
#set-option -g default-terminal xterm-256color
#setw -g window-status-current-style fg=black,bg=white

bind-key : command-prompt
bind-key r refresh-client
bind-key L clear-history
set-option -g history-limit 3000

bind-key space next-window
bind-key bspace previous-window
bind-key enter next-layout

# use vim-like keys for splits and windows
bind-key v split-window -h
bind-key s split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim$' && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim$' && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim$' && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim$' && tmux send-keys C-l) || tmux select-pane -R"
bind -n 'C-\' run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim$' && tmux send-keys 'C-\\') || tmux select-pane -l"
bind C-l send-keys 'C-l'

bind-key C-o rotate-window

bind-key + select-layout main-horizontal
bind-key = select-layout main-vertical

set-window-option -g other-pane-height 25
set-window-option -g other-pane-width 80
set-window-option -g display-panes-time 1500
#set-window-option -g window-status-current-style fg=magenta
set-window-option -g xterm-keys on

bind-key a last-pane
bind-key q display-panes
bind-key c new-window
bind-key t next-window
bind-key T previous-window

bind-key [ copy-mode
bind-key ] paste-buffer

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Status Bar
set-option -g status-interval 1
#set-option -g status-style bg=black
#set-option -g status-style fg=white
set -g status-left '#[fg=green]#H #[default]'
set -g status-right '%a%l:%M:%S %p#[default] #[fg=blue]%Y-%m-%d'

#set-option -g pane-active-border-style fg=yellow
#set-option -g pane-border-style fg=cyan

# Set window notifications
setw -g monitor-activity on
set -g visual-activity on

# Enable native Mac OS X copy/paste
set-option -g default-command "/bin/bash -c 'which reattach-to-user-namespace >/dev/null && exec reattach-to-user-namespace $SHELL -l || exec $SHELL -l'"

set-option -ga terminal-overrides ",rxvt-unicode-256color:Tc"
# Allow the arrow key to be used immediately after changing windows
set-option -g repeat-time 0
bind-key z resize-pane -Z \; choose-tree -u -c "resize-pane -Z \; select-window -t '%%'"
set -g @plugin "arcticicestudio/nord-tmux"
run "~/.tmux/plugins/tpm/tpm"
#run-shell "~/.tmux/themes/nord-tmux/nord.tmux"

**Comment by nicm** [comment]
Does it work if you start with an empty config and just set the
status-style option?

**Comment by 0xd4y** [comment]
> 
> Does it work if you start with an empty config and just set the status-style option?

Hi nicm! Thank you for the quick reply! It works, but it is a little bit strange:
![image](https://user-images.githubusercontent.com/77868212/114249717-003ff100-9961-11eb-9175-27d9a7ec14c3.png)

Note how I changed the active tab background to red in the config file, but the background is blue instead. I'd really appreciate your help!

**Comment by nicm** [comment]
Are you sure your terminal palette isn't different from what tmux expects?
Is it the same if you open a new terminal? What if you use a different
terminal entirely?

**Comment by 0xd4y** [comment]
> 
> Are you sure your terminal palette isn't different from what tmux expects? Is it the same if you open a new terminal? What if you use a different terminal entirely?
 
Hi nicm! Yes, I am sure the terminal palette I use isn't different from what tmux expects. I have used both MATE and GNOME terminals, but the output is the exact same for both.

**Comment by nicm** [comment]
Are you restarting tmux entirely in order to test?

**Comment by 0xd4y** [comment]
> 
> 
> Are you restarting tmux entirely in order to test?

Hi nicm! Thank you for trying to help! I did restart tmux entirely. I just ended up giving up and used a tmux theme that is compatible with the terminal that I have. I really appreciate you going out of your way to try to help!
