### ISSUE TITLE
how to create custom command in tmux?

### ISSUE THREAD

**Issue by woodgear** [tmux/tmux#2643]
### Issue description
i'm try to write helper command like tmux-jumto-pane-by-regex
```bash
tmux-list-pane() {
    ## use by tmux-jumpto-panel-by-regex
    ## -s show all window's panel -F show as format
   tmux list-panes -s -F "#{session_name}:#{window_name}:#{window_index}:#{pane_title}:#{pane_index}" 
}

tmux-jumpto-panel-by-regex() {
    name=$1
    pane=$(tmux-list-panel |grep $name)
    pane_index=${pane##*-}
    target_window_index=$(tmux-list-pane |grep $name |cut -d ':' -f 3) 
    current_window_index=$(tmux list-windows|grep '*' |cut -d ':' -f 1)
    echo $target_window_index
    echo $current_window_index
    # if we are in different window jumpto it first
    if [[ $target_window_index == $current_window_index ]] then
        tmux select-panel -t $pane_index
    else
        tmux select-window -t $target_window_index && tmux select-panel -t $pane_index
    fi
}
```
it did work, but I also want eval it in tmux command prompt(just like the emacs command), i did see sth like https://github.com/ershov/tmux but i'm not sure is that recommend or is that still being maintained. 
so my question is: is there some tmux way to add custom command?
### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.0a
* Platform (`uname -sp`). linux  x86_64
* $TERM inside and outside of tmux (`echo $TERM`). xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
You can create your own custom command prompt that fires your command with
the command-prompt command or create an alias that runs your script with
the command-alias option.
