### ISSUE TITLE
Manual - Control Mode - flags documentation missing

### ISSUE THREAD

**Issue by AntonGepting** [tmux/tmux#2646]
Hello, thank you for developing and supporting this great program! I’m daily using and enjoying it.

I was writing a parser for tmux output in control mode and it looks like some small documentation part in tmux manual is missing.

tmux manual explains that the output block in control mode has **two arguments**:
>%begin and matching %end or %error have two arguments: an integer time (as seconds from epoch) and command number.  For example:
>```
>%begin 1363006971 2
>0: ksh* (1 panes) [80x24] [layout b25f,80x24,0,0,2] @2 (active)
>%end 1363006971 2
>```

But if I use `tmux 3.1c` I’m getting **three arguments** after `%begin/%end/%error` keywords instead of two.
```
$ tmux -C attach -t 0
%begin 1618306932 3338 0
%end 1618306932 3338 0
%session-changed $0 0
```

Call chain in tmux sources looks like (cmd-queue.c):
```
... cmdq_fire_command() ... -> ... cmdq_guard() ... -> ... evbuffer_add_printf() ...
```

Passing arguments to the last function (cmd-queue.c):
```
...
evbuffer_add_printf(c->stdout_data, "%%%s %ld %u %d\n", guard, (long)item->time, item->number, flags);
...
```

I noticed the last `flags` argument is used but currently not mentioned in control mode chapter of tmux manual. It's not so important, but it may be helpful for better understanding to have some small hint about it in manual, if output of the `flags` argument is on purpose. Thank you!

Environment:
```
$ uname -sp
Linux unknown
$ uname -a 
Linux pc_3_linux 5.10.0-5-amd64 #1 SMP Debian 5.10.24-1 (2021-03-19) x86_64 GNU/Linux
$ tmux -V
tmux 3.1c 
$ echo $TERM
xterm-256color
```

**Comment by nicm** [comment]
Yes this is an error in the man page (it is out of date), I'll fix it later. Look here instead: https://github.com/tmux/tmux/wiki/Control-Mode#commands

Althought even that says flags should always be 1, not sure why you are getting 0...

**Comment by AntonGepting** [comment]
Thx

**Comment by nicm** [comment]
I changed the man page now. Thanks!
