### ISSUE TITLE
Tmux 3.2 M-Left and M-Right unbinding issues

### ISSUE THREAD

**Issue by maneyko** [tmux/tmux#2647]
### Issue description
I cannot unbind `M-Left` and `M-Right`. Below is a screenshot of what happens when I try to unbind the keys then do `M-a` + `M-Left` of `M-a` + `M-Right` (where `M-a` is my leader prefix).
![Screen Shot 2021-04-13 at 10 13 50 AM](https://user-images.githubusercontent.com/14032795/114577844-ff011380-9c41-11eb-9b04-2598bb013620.png)
I am, on the other hand, able to do `tmux unbind-key -n 'M-1'` or bind it to some other command.

I use `M-Left` and `M-Right` as readline shortcuts and do not want `tmux` to use them. In my `~/.inputrc` I have them mapped as the following:
```inputrc
"\e[1;3D":  backward-word
"\e[1;3C":  forward-word
```

### Required information

Please provide the following information:
```bash
$ tmux -V
tmux 3.2

$ uname -sp
Darwin i386

$ echo $TERM
xterm-256color
```
Logs from `tmux -vv new`:
* [tmux-server-40852.log](https://github.com/tmux/tmux/files/6304791/tmux-server-40852.log)

### Additional Information
Here is a link to my [`tmux.conf`](https://github.com/maneyko/dotfiles/blob/master/tmux.conf).

**Comment by nicm** [comment]
There is no evidence of you attempting to unbind `M-Left` or `M-Right` in this log file.

**Comment by maneyko** [comment]
Here is a session where I do `tmux unbind-key -n 'M-Left'` then do `M-Left` and experience the issue. Thank you for your feedback.

[tmux-server-52597.log](https://github.com/tmux/tmux/files/6304924/tmux-server-52597.log)

**Comment by nicm** [comment]
What does `tmux lsk M-Left` show after you unbind?

**Comment by maneyko** [comment]
I get the following:
```
┌─[maneyko:~/tmp]
└[$]› tmux lsk 'M-Left'
bind-key    -T copy-mode    Left send-keys -X cursor-left
bind-key    -T copy-mode-vi Left send-keys -X cursor-left
bind-key -r -T prefix       Left select-pane -L
```

**Comment by nicm** [comment]
I see this too, very strange.

**Comment by nicm** [comment]
No, I see `list-keys` is wrong, but `unbind` works:
~~~~
$ tmux lsk|grep M-Left
bind-key -r -T prefix       M-Left               resize-pane -L 5
$ tmux unbind M-Left
$ tmux lsk|grep M-Left
$

**Comment by maneyko** [comment]
I get that same response but then do `M-a` + `M-Left` and still go into the undesired mode as shown in the screenshot in the issue description.

**Comment by nicm** [comment]
Please show me log from starting tmux and then pressing `M-a` + `M-Left` then exiting tmux.

**Comment by nicm** [comment]
After you have unbind it of course.

**Comment by maneyko** [comment]
I did the following:
```
$ tmux -vv new

# New tmux session opens ...

$ tmux unbind-key 'M-Left'
```
then pressed `M-a` + `M-Left` on my keyboard and went into the undesired vi-copy mode. Then pressed `Enter` to get out of vi-copy then did `exit` to quit the session.

[tmux-server-68318.log](https://github.com/tmux/tmux/files/6305208/tmux-server-68318.log)

**Comment by nicm** [comment]
You are not pressing `M-Left`, you are pressing a key which generates `\033[1;9D`. This is not a valid xterm function key (they only go up to 8 which would be `M-S-C-Left`, not 9), so tmux is interpreting it as `M-[` which you have bound to `copy-mode`.

What terminal are you using?

**Comment by nicm** [comment]
OK it is iTerm2, are you pressing one of the Apple special keys + `Left`?

**Comment by maneyko** [comment]
I was pressing `Option` + `Left`. My iTerm2 configuration had `Left Option` and `Right Option` modifiers to be `Esc+` as shown in the screenshot below.

By adding the following mapping to `Option` + `Left` in the iTerm2 preferences I was able to resolve my issue:
<img width="664" alt="Screen Shot 2021-04-13 at 11 32 45 AM" src="https://user-images.githubusercontent.com/14032795/114588477-573d1300-9c4c-11eb-9df2-4d5af7ca8135.png">

I am using iTerm2 build 3.4.4. This is more likely an issue with iTerm2 in that case?

**Comment by nicm** [comment]
Well I guess it sends 9 for Option which is fairly logical, but tmux does not understand it. I could make it ignore it or maybe just treat it as Meta.

**Comment by maneyko** [comment]
I can't comment on mapping specific escape sequences because I don't know how they are applied on different platforms, etc.

My issue has been resolved though with a simple keymapping override in my terminal emulator. Thank you so much for your quick and detailed help @nicm! Really says a lot about this project.

I will leave it to you to close this issue.

**Comment by nicm** [comment]
I can't find where in the source iTerm2 sets these defaults so I can't work out if they have changed or what exactly it means for `9` (I assume it is just the `Option` key). My iTerm2 does not send it but I may have configured it not to. @gnachman perhaps you can give me a hint?

**Comment by gnachman** [comment]
If your profile doesn't have a setting for it (switch it to xterm defaults in **Prefs > Profiles > Keys > Load Preset**) then the modifier value is set here:

https://github.com/gnachman/iTerm2/blob/c52136b7c0bae545436be8d1441449f19e21faa1/sources/VT100Output.m#L647

Whether you get 9 or 3 hinges on `_optionIsMetaForSpecialKeys`. This is true by default, but there's an advanced preference if you prefer option to be alt instead.

![image](https://user-images.githubusercontent.com/427546/114824346-9ae16b00-9d79-11eb-9ba1-b71f8232708d.png)

As I recall someone complained about this many years ago but by then this had been the default for so long that I couldn't change it without breaking lots of people's settings. I added the advanced pref for those who care. I wish there were a better answer.

**Comment by gnachman** [comment]
If anyone can explain what the difference between 3 and 9 is actually supposed to be, I would love to know! I have never found a good reference for this info.

**Comment by nicm** [comment]
Hah it turns out I am on crack and xterm does go up to 9:
~~~~
                  Code     Modifiers
                  ---------+---------------------------
                     2     | Shift
                     3     | Alt
                     4     | Shift + Alt
                     5     | Control
                     6     | Shift + Control
                     7     | Alt + Control
                     8     | Shift + Alt + Control
                     9     | Meta
                     10    | Meta + Shift
                     11    | Meta + Alt
                     12    | Meta + Alt + Shift
                     13    | Meta + Ctrl
                     14    | Meta + Ctrl + Shift
                     15    | Meta + Ctrl + Alt
                     16    | Meta + Ctrl + Alt + Shift
                  ---------+---------------------------

**Comment by nicm** [comment]
On most terminals on most PCs, Alt and Meta are the same, so everyone just uses 3.

**Comment by nicm** [comment]
I wonder why it used to work in tmux, because even if I was masking off the Meta, 9 would still not have ended up as 3.

**Comment by nicm** [comment]
@gnachman I think it is as simple as some ancient terminals or computers had different keys, from ctlseqs.txt:
~~~~
Alt and Meta Keys

Many keyboards have keys labeled "Alt".  Few have keys labeled "Meta".
However, xterm's default translations use the Meta modifier.  Common
keyboard configurations assign the Meta modifier to an "Alt" key.  By
using xmodmap one may have the modifier assigned to a different key, and
have "real" alt and meta keys.

**Comment by nicm** [comment]
tmux has never supported separate Alt and Meta keys and nobody has ever asked for it so I suspect it is quite rare these days.

**Comment by gnachman** [comment]
I must have guessed wrong back when this was written, but people don't complain about it so I have assumed that it works enough of the time that it's not worth the risk of changing it.

**Comment by nicm** [comment]
Yeah, I mean they are both "right" really I guess.

I am going to map 9 to Meta as well as 3 for the next tmux release. I am not sure why it ever worked, I can't see anything obvious, but I guess I broke it at some point. I don't think I will bother with 10-15 until someone asks for them.

**Comment by nicm** [comment]
Changed in master now, thanks both!
