### ISSUE TITLE
Some commands with braces result in syntax error when sourced from file

### ISSUE THREAD

**Issue by sschlesier** [tmux/tmux#2649]
Some commands result in syntax errors when they are sourced from a file but not when entered via command line.

To repro

Start by echoing a problematic command into a file

`echo 'bind -n M-n split-window -b -t :.{top-left} -c "#{pane_current_path}"' > testit.conf`

Then launch tmux 

`tmux -Ltest -f/dev/null new`

Then source the test file

`tmux source testit.conf`

This will result in a syntax error.   I've attached syntax-error.tar.gz with the logs for the above.

If you quit and relaunch a config free tmux as above and then issue the bind command directly

`tmux bind -n M-n split-window -b -t :.{top-left} -c #{pane_current_path}`

It will work fine.  I've also attached success-cli.tar.gz with the logs for command line success.

### Required information

Please provide the following information:

Darwin arm
tmux 3.2
xterm-256color
[success-cli.tar.gz](https://github.com/tmux/tmux/files/6308089/success-cli.tar.gz)
[syntax-error.tar.gz](https://github.com/tmux/tmux/files/6308090/syntax-error.tar.gz)

**Comment by krader1961** [comment]
Did you verify the content of *testit.conf*? I ask because your `echo` command to populate that file uses an unquoted string which contains shell meta-characters. Which means the content of the file is not likely to be equal to the original unquoted string.

**Comment by sschlesier** [comment]
In reality I created testit.conf via copy pasting to an editor, and I wasn't careful about writing the echo command above.  Thanks for pointing that out.  I've quoted the echo to correct the command.

**Comment by nicm** [comment]
You need to quote it as `-t ':.{top-left}'`.

**Comment by sschlesier** [comment]
Yes.  Quotes do fix the parsing issue.

I tried quotes in the original file on the first problem line.  That caused the parser error to move to to a later line.  I didn't realize that the whole file needs to parse successfully before any lines are applied so I believed that the corrected line was parsing correctly but still not working.

After quoting all the lines in my conf files 3.2 is working fine for me.
