### ISSUE TITLE
.tmux.conf file not sourced implicitly nor explicitly from a launch script

### ISSUE THREAD

**Issue by jecompton** [tmux/tmux#265]
I wrote a simple shell script to launch a dev environment. It is something like
```bash
tmux new-session -s rubydev -n dev -d
tmux source-file ~/.tmux.conf
tmux attach -t rubydev
```
However, no settings are begin pulled from my .tmux.conf. If I launch tmux from the command line normally, .tmux.conf loads as expected.

I compared both runs using strace, and I noticed that .tmux.conf isn't being sourced whether or not I include the ```tmux source-file ~/.tmux.conf``` line.

I'm running Ubuntu 15.10. I tried this with both the Ubuntu tmux for that version (2.0) as well as compiled from source from git (2.2).

Perhaps my understanding of ```source-file``` is incorrect, but I wanted to mention this in case it's a bug.

**Comment by nicm** [comment]
Works for me:

$ cat test.sh
tmux new -dsfoo
tmux source ~/test.conf
tmux a -tfoo
$ cat test.conf
set -g status off
$ tmux kill-server
no server running on /tmp/tmux-1000/default
$ tmux new -d
$ tmux show -g status
status on
$ sh test.sh
$ tmux show -g status
status off

**Comment by jecompton** [comment]
I see now. I needed to add the '-f' option in my strace to see the daemon sourcing the conf file. So yes, my original rubydev script always did source it.

My specific problem still remains which is that my .tmux.conf file gives me 256 colour if I start tmux directly with

$ tmux

but doesn't when sourced from a script. Now that I can see that it is actually being sourced, it must be a lack of understanding of how style gets applied and not an issue at all.

Thanks!
