### ISSUE TITLE
list-keys -N does not show correct information

### ISSUE THREAD

**Issue by terminalmage** [tmux/tmux#2650]
### Issue description

I have remapped my prefix key, but `list-keys -N` incorrectly shows `C-b` as the prefix.

I'm not sure what else is inaccurate, so it is possible that there is other keybinding information that is also not being correctly reported. See the below section for replication instructions.

### Required information

```
% tmux source .tmux.conf
% fgrep prefix .tmux.conf
# change command key from C-b, leaving C-k as fallback prefix
set-option -g prefix `
set-option -g prefix2 C-k
# double-backtick sends literal backtick (needed since ` is the prefix)
bind-key ` send-prefix
% tmux list-keys -N | fgrep prefix
` C-b     Send the prefix key
% tmux -V
tmux 3.2
% uname -sp
Linux unknown
% echo $TERM
screen-256color
```

Logs:
- [tmux-out-2888286.log](https://github.com/tmux/tmux/files/6311652/tmux-out-2888286.log)
- [tmux-server-2888286.log](https://github.com/tmux/tmux/files/6311653/tmux-server-2888286.log)
- [tmux-client-2888284.log](https://github.com/tmux/tmux/files/6311654/tmux-client-2888284.log)

**Comment by terminalmage** [comment]
This might have something to do with how `set-option` is setting the prefix. It appears to just be doing a `bind-key` under the hood, and not unbinding the default global `send-prefix` keybinding. When you list all keybindings, you get:

```
% tmux list-keys -a | grep send-prefix
bind-key    -T prefix       C-b                  send-prefix
bind-key    -T prefix       `                    send-prefix
```

So, `C-b` remains in the keybindings, but is superseded by the backtick. `C-b` doesn't _actually_ send the prefix when I use it.

It seems like 2 things are happening here:

1. The default `send-prefix` is not being removed when `set-option -g prefix $some_key` is used
2. The `set-option` configures your prefix by adding a `bind-key` _perhaps without notes_, thus keeping it from being displayed in `list-keys -N`

But I'm not even confident about this, because if I manually unbind `C-b` and then manually bind `send-prefix` with a `-N` option to add notes, that keybinding is _still_ not present in `list-keys -N`.

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#why-is-c-b-the-prefix-key-how-do-i-change-it

**Comment by terminalmage** [comment]
OK, fair, I have been overriding the prefix in this way for about 10 years, and probably didn't see that part of the docs on the old sourceforge site, if they existed at the time.

However, `list-keys -N` is still broken:

### From .tmux.conf
```
set-option -g prefix `
unbind-key C-b
bind-key -N 'Send the prefix key' ` send-prefix
```

### On new tmux server instance
Note that my custom keybinding for clearing the current pane's scrollback history (for which I also used `-N`) is properly shown in the `list-keys -N` output.

```
% tmux list-keys -N | fgrep prefix
% tmux list-keys -a | fgrep send-prefix
bind-key    -T prefix       `                    send-prefix
% tmux list-keys -N | fgrep scrollback
` H       Clear pane scrollback history
```

**Comment by nicm** [comment]
It works for me. Does it work with master?
~~~~
$ tmux lsk -N|grep prefix
` `       Send the prefix key

**Comment by terminalmage** [comment]
Ahh, nevermind, the following lines from the example that I posted in the OP still remained in the config file:

```
# double-backtick sends literal backtick (needed since ` is the prefix)
bind-key ` send-prefix
```

That's on me, the lines were just past the bottom of my terminal and I didn't scroll. That `bind-key` came after (and overrode) the one I added with the `-N` [earlier](https://github.com/tmux/tmux/issues/2650#issuecomment-819682835).

Thanks for the link! Gonna close this.
