### ISSUE TITLE
Escape Key Interference (even with `set -sg escape-time 0`)

### ISSUE THREAD

**Issue by w0ryn** [tmux/tmux#2652]
### Issue description
Even after `set -sg escape-time 0`, the ESC key still works as the prefix for any `prefix` key table bindings when typed quickly. To reproduce, open a clean session and set the escape-time as described. Pressing `Escape` (or `^[`) and then `c` quickly will open a new window.

Although setting the escape time to 0 fixes many issues with a `vi`-like workflow, this often causes stuttering in my workflow. My suggestion is to allow for an escape-time of `-1` or some way to entirely unbind the `Escape` key from a session.

### Required Information
tmux version | `tmux 3.2`
--- | ---
Platform  | `Linux unknown` (arch)
$TERM inside | `tmux-256color`
$TERM outside | `xterm-kitty`

**Comment by nicm** [comment]
I have no idea what you mean by this, the default prefix is C-b and has nothing to do with Escape.

**Comment by w0ryn** [comment]
Whoops, my `$EDITOR` is set to `vi`, which seems to set the `mode-keys` to `vi`. This results in the described behavior.

**Comment by nicm** [comment]
I don't know what you are asking. If you set the prefix to Escape then of course Escape c will open a new window.

**Comment by w0ryn** [comment]
I'm confused. When `mode-keys` are set to `vi`, `Escape` is set to the prefix? `C-b` still works as the default prefix and is not affected by `escape-time` settings. Can I unbind the `Escape` key as the prefix if this is set by the `mode-keys`?

**Comment by nicm** [comment]
There is no prefix in copy mode, because there is no edit mode, you are always in command mode.

**Comment by w0ryn** [comment]
Sorry, I'm still not quite following.

With `mode-keys` set to `vi`, I can still enter command mode by pressing `C-b :`, but I don't understand where the `Escape` key becomes the prefix key _in addition to `C-b`_. I would like to use `vi`-like bindings (particularly for copy mode), but I do not want `Escape` to function as a prefix key under any circumstances.

**Comment by nicm** [comment]
If you use vi keys at the command prompt (is status-keys set to vi) then Escape will enter command mode because that is how vi editing works. If you don't want vi keys at the command prompt, set status-keys to Emacs.

**Comment by w0ryn** [comment]
My command mode works as expected. When I'm not in command mode, for some reason `Escape` is sending a prefix signal to the session, but I have not bound `Escape` to be the prefix key, and I cannot seem to unbind `Escape` as a prefix key.

**Comment by nicm** [comment]
Show logs from reproducing please.

**Comment by w0ryn** [comment]
[tmux-out-2899187.log](https://github.com/tmux/tmux/files/6313589/tmux-out-2899187.log)
[tmux-server-2899187.log](https://github.com/tmux/tmux/files/6313590/tmux-server-2899187.log)
[tmux-client-2899185.log](https://github.com/tmux/tmux/files/6313591/tmux-client-2899185.log)

**Comment by w0ryn** [comment]
Is the Escape key being read as a Meta-key input?

**Comment by nicm** [comment]
There is no evidence of you pressing `M-c` or `Escape` in this log:
~~~~
1618432858.051238 /dev/pts/1: keys are 1 (\002)
1618432858.291328 /dev/pts/1: keys are 1 (:)
1618432859.035316 /dev/pts/1: keys are 1 (b)
1618432859.107612 /dev/pts/1: keys are 1 (i)
1618432859.147192 /dev/pts/1: keys are 1 (n)
1618432859.243286 /dev/pts/1: keys are 1 (d)
1618432859.451390 /dev/pts/1: keys are 1 (-)
1618432859.707768 /dev/pts/1: keys are 1 (k)
1618432859.779267 /dev/pts/1: keys are 1 (e)
1618432859.867235 /dev/pts/1: keys are 1 (y)
1618432859.947177 /dev/pts/1: keys are 1 ( )
1618432861.115245 /dev/pts/1: keys are 1 (M)
1618432861.291204 /dev/pts/1: keys are 1 (-)
1618432861.355360 /dev/pts/1: keys are 1 (c)
1618432861.491750 /dev/pts/1: keys are 1 ( )
1618432866.107314 /dev/pts/1: keys are 1 (n)
1618432866.211155 /dev/pts/1: keys are 1 (e)
1618432866.275148 /dev/pts/1: keys are 1 (w)
1618432866.371124 /dev/pts/1: keys are 1 (-)
1618432866.515237 /dev/pts/1: keys are 1 (w)
1618432866.587120 /dev/pts/1: keys are 1 (i)
1618432866.643192 /dev/pts/1: keys are 1 (n)
1618432867.299303 /dev/pts/1: keys are 1 (d)
1618432867.355121 /dev/pts/1: keys are 1 (o)
1618432867.475127 /dev/pts/1: keys are 1 (w)
1618432868.491202 /dev/pts/1: keys are 1 (\r)
1618432875.395098 /dev/pts/1: keys are 1 (\004)

**Comment by w0ryn** [comment]
Hmmm maybe I exited too quickly? My new log shows the following:
```
1618433978.897355 /dev/pts/1: keys are 13 (\033[>1;4000;19c)
1618433980.305926 /dev/pts/1: keys are 1 (\002)
1618433980.705503 /dev/pts/1: keys are 1 (:)
1618433981.281544 /dev/pts/1: keys are 1 (b)
1618433981.329479 /dev/pts/1: keys are 1 (i)
1618433981.369363 /dev/pts/1: keys are 1 (n)
1618433981.449869 /dev/pts/1: keys are 1 (d)
1618433981.721452 /dev/pts/1: keys are 1 (-)
1618433981.905496 /dev/pts/1: keys are 1 (k)
1618433981.969492 /dev/pts/1: keys are 1 (e)
1618433982.065905 /dev/pts/1: keys are 1 (y)
1618433982.121465 /dev/pts/1: keys are 1 ( )
1618433983.849532 /dev/pts/1: keys are 1 (-)
1618433983.969496 /dev/pts/1: keys are 1 (n)
1618433984.065495 /dev/pts/1: keys are 1 ( )
1618433984.297509 /dev/pts/1: keys are 1 (M)
1618433984.481502 /dev/pts/1: keys are 1 (-)
1618433984.793477 /dev/pts/1: keys are 1 (c)
1618433985.257877 /dev/pts/1: keys are 1 ( )
1618433985.737588 /dev/pts/1: keys are 1 (n)
1618433985.785426 /dev/pts/1: keys are 1 (e)
1618433985.849714 /dev/pts/1: keys are 1 (w)
1618433986.025471 /dev/pts/1: keys are 1 (-)
1618433986.305493 /dev/pts/1: keys are 1 (w)
1618433986.393443 /dev/pts/1: keys are 1 (i)
1618433986.457693 /dev/pts/1: keys are 1 (n)
1618433986.521403 /dev/pts/1: keys are 1 (d)
1618433986.625410 /dev/pts/1: keys are 1 (o)
1618433986.681442 /dev/pts/1: keys are 1 (w)
1618433986.793746 /dev/pts/1: keys are 1 (\r)
1618433988.705376 /dev/pts/1: keys are 1 (\033)
1618433988.745550 /dev/pts/1: keys are 2 (\033c)
1618433991.513430 /dev/pts/1: keys are 1 (\004)
1618433992.033380 /dev/pts/1: keys are 1 (\004)

```

**Comment by nicm** [comment]
Are you sure you have escape-time 0? If you do and are still pressing Escape and c fast enough that tmux thinks it is M-c then there is not much you can do.

**Comment by w0ryn** [comment]
I didn't realize that meta keys signals were just a combined 2-character signal. I notice this problem most over remote connections, so maybe there's no way to fix this. Strange that the log shows both `\033` and `\033c`. If you don't think there's anything that can fix this, then I suppose the issue is resolved. Thank you for your time!

**Comment by nicm** [comment]
\033 will be the escape and the \033c after tmux has waited for escape-time to expire.

**Comment by w0ryn** [comment]
`show-option escape-time` says `escape-time 0` and I still have the issue

**Comment by w0ryn** [comment]
But I've noticed on logs that the `\033` is not always captured separately. I'll bet you're right about there not being any way around this.

**Comment by nicm** [comment]
If they come in together then even escape-time 0 cannot help, there has to be some gap.

**Comment by w0ryn** [comment]
Thanks again for your help!
