### ISSUE TITLE
Tmux 3.2 capture-pane hangs

### ISSUE THREAD

**Issue by toxeus** [tmux/tmux#2653]
### Issue description

Tmux version 3.2 breaks `capture-pane`. A downgrade to 3.1c makes it work again.

```sh
# hangs forever since 3.2
tmux capture-pane -J -p | grep foo
```

### Required information

* tmux version (`tmux 3.2`).
* Platform (`Linux unknown`).
* $TERM inside and outside of tmux (`xterm`/`tmux-256color`).

**Comment by nicm** [comment]
Logs?

**Comment by toxeus** [comment]
Nothing is logged when the command is executed. But if you need them I'm happy to attach them.

**Comment by nicm** [comment]
Yes please.

**Comment by toxeus** [comment]
[tmux-client-368348.log](https://github.com/tmux/tmux/files/6313573/tmux-client-368348.log)

**Comment by nicm** [comment]
That's just the client log, please show me the server log.

**Comment by toxeus** [comment]
There's no server log. It should be in `$HOME`, right?

**Comment by nicm** [comment]
No it will be in the directory where you started tmux. Make sure you are killing tmux entirely (`tmux kill-server`) before you test.

**Comment by toxeus** [comment]
Now, it doesn't work at all anymore :sweat_smile: 
![image](https://user-images.githubusercontent.com/7702854/114776884-476c1e80-9d73-11eb-9451-9cd2181da169.png)

**Comment by nicm** [comment]
Make sure you have no tmux processes running at all and make sure you are running the 3.2 tmux binary and then do -vv and show me any server and client logs it creates.

**Comment by toxeus** [comment]
You were right, there was a tmux process still stuck in the background. Killing it solved the original issue too. Thanks and sorry for the noise.

**Comment by nicm** [comment]
No worries.
