### ISSUE TITLE
URXVT Colors Messed Up Inside Tmux

### ISSUE THREAD

**Issue by ChrispyChris** [tmux/tmux#2654]
* tmux config: https://pastebin.com/HmGf8NLy
* tmux screenshot:
![tmux](https://user-images.githubusercontent.com/13801530/114882470-d51e2d00-9db8-11eb-9322-5c74916790cc.png)

* tmux version (`tmux -V`): **tmux 3.2**
* Platform (`uname -sp`): **Linux unknow** _I run Arch, x86_64 is the architecture_
* $TERM inside and outside of tmux (`echo $TERM`):
**Outside tmux: rxvt-unicode-256color**
**Inside tmux: screen**
_I've tried changing this but to no avail. **Although on my 3.1c (during downgrade AND on my laptop which works still at 3.1c) it says screen as well, so no difference there._**
* Logs from tmux (`tmux kill-server; tmux -vv new`):
[tmux-client-29540.log](https://github.com/tmux/tmux/files/6318492/tmux-client-29540.log)
[tmux-out-29542.log](https://github.com/tmux/tmux/files/6318493/tmux-out-29542.log)
[tmux-server-29542.log](https://github.com/tmux/tmux/files/6318494/tmux-server-29542.log)

I've tested to make sure, and 3.1c fixes the issue after downgrading from 3.2 and then upgrading back to 3.2 brings the issue back again, as expected.

I imagine that others using tmux within URXVT will have the same issue as more people upgrade. I upgrade daily so maybe that's why I'm the first to complain haha. I could be wrong, but my system isn't extremely unique or super riced out. I run URXVT within i3-gaps and that's about it. If you want any other information, just let me know :).

**Comment by nicm** [comment]
You are changing the palette but not using RGB colour. What does it look like if you add this to .tmux.conf and restart tmux entirely:
~~~~
set -as terminal-overrides 'rxvt*:RGB'
~~~~

**Comment by ChrispyChris** [comment]
> ```
> set -as terminal-overrides 'rxvt*:RGB'
> ```

Awesome, that's a super good start. My URXVT colors are pretty close. When I open VIM, I get an issue now though, which was something I experienced yesterday when playing around with settings. Here is a picture, I printed out the pallet for you as well!
![tmux](https://user-images.githubusercontent.com/13801530/114908755-3f42cc00-9dd1-11eb-944e-8fae6180c7cd.png)

**Comment by nicm** [comment]
What TERM are you using inside tmux?

**Comment by nicm** [comment]
What TERM are you using inside tmux?

**Comment by ChrispyChris** [comment]
> What TERM are you using inside tmux?

It says screen, which on all of my machines it has always been this way. Only now have I ever noticed since the issue became apparent. On 3.1c it never caused any problems that I ever **_noticed_** inside tmux and vim, but obviously the update was pretty big so I am wondering if that's the issue or something else.

**Comment by nicm** [comment]
If you set it to `tmux-256color` does it change anything with vim?

**Comment by nicm** [comment]
This is probably a tmux bug because colours 1-14 do not look right. Can you show me the server log from running the command you have in your screenshot?

**Comment by ChrispyChris** [comment]
![image](https://user-images.githubusercontent.com/13801530/114931456-1fb89d00-9deb-11eb-9cb7-6c9823bba1dd.png)

Sure, but quick question: do you mean to run that color command inside tmux and then do the logs again or?? Sorry for the confusion :)

**Comment by nicm** [comment]
Kill tmux, run with -vv, run the colour command you did before, then exit tmux and attach the server log.

**Comment by ChrispyChris** [comment]
Roger that. This should be correct! 
[tmux-server-9945.log](https://github.com/tmux/tmux/files/6320879/tmux-server-9945.log)


Thanks for your time, by the way.

**Comment by nicm** [comment]
Hmm. tmux seems to be sending the right thing. You set color3 to RGB 232,93,90:
~~~~
1618517301.586367 input_exit_osc: "4;3;#E85D5A" (end ST)
1618517301.586371 input_osc_parse_colour: #E85D5A = #e85d5a
~~~~
Then tmux prints it: 
~~~~
1618517310.851094 /dev/pts/0: \033[38;2;232;93;90m
1618517310.851106 /dev/pts/0: color3
~~~~
What do you see if you do this inside and outside tmux:
~~~~
printf '\033[38;2;232;93;90mcolor3\033[0m\n'
~~~~

**Comment by nicm** [comment]
Can you try running this script https://raw.githubusercontent.com/tmux/tmux/master/tools/24-bit-color.sh as well outside tmux and see what it show?

**Comment by dbeley** [comment]
Hello, I have the same issue and just ran the script on a terminal with and without tmux:
![1618569893](https://user-images.githubusercontent.com/6568955/115014184-84363380-9ea1-11eb-83c7-39b57a1589e2.png)

**Comment by nicm** [comment]
Except you didn't configure RGB colours...

**Comment by dbeley** [comment]
Sorry I didn't mention that `set -g default-terminal "tmux-256color"` and `set -as terminal-overrides 'rxvt*:RGB'` are both set in my `.tmux.conf`.
I just tried with a minimal `.tmux.conf`:
![1618570550](https://user-images.githubusercontent.com/6568955/115015455-2f93b800-9ea3-11eb-9e8f-94ff96d0844f.png)

**Comment by nicm** [comment]
Show server log from doing this with your minimal config please.

**Comment by dbeley** [comment]
With the minimal `.tmux.conf` and only running the colours script, here's the log: 
[tmux-server-18365.log](https://github.com/tmux/tmux/files/6324591/tmux-server-18365.log)

**Comment by nicm** [comment]
Your `TERM` does not match `rxvt*`, it is `xterm-256color`.

**Comment by dbeley** [comment]
That was it! Thanks a lot for your quick help, and sorry to have hijacked this issue, it was totally a misconfiguration on my side.
Thanks again!

**Comment by LoLei** [comment]
Any info on how to fix this in alacritty? I assume `set -as terminal-overrides 'rxvt*:RGB'` didn't work for me because that's for urxvt. In kitty it still works out of the box. I could just use that as my terminal, but I'd prefer it working in alacritty as well. I can also open a new issue if that's preferred.

**Comment by ChrispyChris** [comment]
printf '\033[38;2;232;93;90mcolor3\033[0m\n' inside and outside of tmux.
![2021-04-16_13-05](https://user-images.githubusercontent.com/13801530/115078439-7807a180-9eb4-11eb-9368-e6f0366e4ae3.png)

**Comment by nicm** [comment]
Looks like a bug in your rxvt-unicode, the text should be red outside tmux. Are you using the latest version?

Is it different if you do this instead:
~~~~
printf '\033[38:2:232:93:90mcolor3\033[0m\n'

**Comment by ChrispyChris** [comment]
Yeah, I just checked on that and it's up to date as well. 
![new](https://user-images.githubusercontent.com/13801530/115079271-c8cbca00-9eb5-11eb-859b-41e63120c5df.png)

**Comment by nicm** [comment]
OK you will either need to talk to the rxvt-unicode developers. Or you just not set the palette inside tmux (and either turn off or don't use RGB colour).

**Comment by ChrispyChris** [comment]
Alright, I appreciate you giving so much of your time for this. Last question I suppose then, just to get all the info I can, so what do you see the issue as being in your understanding? Yours is clearly much better than mine hahaha. That way I can try taking that to other people or dig around more.

**Comment by nicm** [comment]
The colour sequence is meant to be red, there isn't much more to it. Try it in a different terminal that supports RGB colour.

**Comment by nicm** [comment]
The terminal only has one palette, but tmux can have multiple panes which could all have different palettes. So if you set the palette so colour 3 is RGB E85D5A in a pane, tmux can't use colour 3 for it anymore and has to use RGB colour. But rxvt-unicode is using the wrong colour, not the one tmux asked for.

**Comment by ChrispyChris** [comment]
Awesome, thanks. I suppose I could close this but I was curious about one more thing, because this all did work previously to this update to tmux. Do you know what changed in tmux source code, maybe I could patch that bit out myself so I could stay up to date with the new changes, rather than being stuck at 3.1c forever :(, although that's still probably more than I need feature-wise haha.

Regardless, thanks for so much help, I appreciate it and I'll close this after :). Thanks!

**Comment by nicm** [comment]
tmux didn't used to recognise the #rrggbb form of colour you are using for
palette setting.

**Comment by nicm** [comment]
You can remove it from input.c look at the OSC 4 function, there is a
sscanf for #.

**Comment by ChrispyChris** [comment]
I feel like a pain in the ass at this point. I went through 3.1c and took that OSC4 function and copied it to the cloned repo of the current branch, replacing the new function with the old, and then ran through the build instructions, but am coming up with an issue now.

After running the commands and lastly, running make, I see this:
[chris@sublime ~/Downloads/tmux]$ make
/bin/sh ./config.status --recheck
running CONFIG_SHELL=/bin/sh /bin/sh ./configure --no-create --no-recursion
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
./configure: line 4689: syntax error near unexpected token `newline'
./configure: line 4689: `    '''
make: *** [Makefile:726: config.status] Error 2

I only copied to input.c and didn't mess with configure at all. Do you happen to have more time, or should I go and maybe track down the guy that built the package for Arch?

Thanks again regardless, you've gotten me closer!

**Comment by nicm** [comment]
You don't need to copy the whole function, just do this:
~~~~
--- input.c     18 Feb 2021 13:30:24 -0000      1.188
+++ input.c     19 Apr 2021 05:14:11 -0000
@@ -2444,12 +2444,12 @@ input_osc_parse_colour(const char *p)
        char    *copy;

        if ((len == 12 && sscanf(p, "rgb:%02x/%02x/%02x", &r, &g, &b) == 3) ||
-           (len == 7 && sscanf(p, "#%02x%02x%02x", &r, &g, &b) == 3) ||
+           (0 && len == 7 && sscanf(p, "#%02x%02x%02x", &r, &g, &b) == 3) ||
            sscanf(p, "%d,%d,%d", &r, &g, &b) == 3)
                colour = colour_join_rgb(r, g, b);
        else if ((len == 18 &&
            sscanf(p, "rgb:%04x/%04x/%04x", &r, &g, &b) == 3) ||
-           (len == 13 && sscanf(p, "#%04x%04x%04x", &r, &g, &b) == 3))
+           (0 && len == 13 && sscanf(p, "#%04x%04x%04x", &r, &g, &b) == 3))
                colour = colour_join_rgb(r >> 8, g >> 8, b >> 8);
        else if ((sscanf(p, "cmyk:%lf/%lf/%lf/%lf", &c, &m, &y, &k) == 4 ||
            sscanf(p, "cmy:%lf/%lf/%lf", &c, &m, &y) == 3) &&
~~~~
Best bet is to start from a completely clean checkout and make sure that you run `autogen.sh`.

**Comment by ChrispyChris** [comment]
Awesome, that did it. Thanks for everything :). Closing issue.
