### ISSUE TITLE
window-size latest doesn't resize after detach when multiple clients are still connected

### ISSUE THREAD

**Issue by trygveaa** [tmux/tmux#2657]
### Issue description

If I have window-size set to latest and just two clients with different sizes connected to the server, when I disconnect one of them, tmux is immediately resized to the remaining window. This is the behavior I want.

However, if I have three or more clients connected, no resizing is done when I detach one of the clients. This may leave tmux with a size that is not desirable for any of the clients until I make an action.

It would be great if tmux could do this resizing even when multiple clients are still connected. It would of course have to choose one of the client sizes to resize to. If all of the remaining clients are the same size, this is not an issue. If the remaining clients are different sizes, I think a good solution would be to pick the smallest of them.

This happens without any tmux.conf.

### Required information

Please provide the following information:

* tmux version: tmux 3.2
* Platform: Arch Linux
* $TERM inside and outside of tmux: outside: xterm-kitty, inside: screen
* Logs from tmux:
[tmux-client-116464.log](https://github.com/tmux/tmux/files/6323798/tmux-client-116464.log)
[tmux-out-116466.log](https://github.com/tmux/tmux/files/6323799/tmux-out-116466.log)
[tmux-server-116466.log](https://github.com/tmux/tmux/files/6323803/tmux-server-116466.log)

**Comment by nicm** [comment]
It shoud pick the MRU.

**Comment by trygveaa** [comment]
@nicm: Immediately when I detach?

Say I have three clients, 1, 2 and 3. 1 and 2 are large, while 3 is small. I am active on client 3 so that is the current size. Then I detach client 3, and when I do this I would like it to resize to 1 or 2 without performing any activity on them. Currently it stays the size of 3 until I perform an activity on 1 or 2.

If this is not how it works for you, do you have any way I can debug it?

**Comment by nicm** [comment]
No I mean, we should change it so it does.

From: Trygve Aaberge ***@***.***>
Reply to: tmux/tmux ***@***.***>
Date: Friday, 16 April 2021 at 10:17
To: tmux/tmux ***@***.***>
Cc: Nicholas Marriott ***@***.***>, Mention ***@***.***>
Subject: Re: [tmux/tmux] window-size latest doesn't resize after detach when multiple clients are still connected (#2657)


@nicm<https://github.com/nicm>: Immediately when I detach?

Say I have three clients, 1, 2 and 3. 1 and 2 are large, while 3 is small. I am active on client 3 so that is the current size. Then I detach client 3, and when I do this I would like it to resize to 1 or 2 without performing any activity on them. Currently it stays the size of 3 until I perform an activity on 1 or 2.

If this is not how it works for you, do you have any way I can debug it?

**Comment by trygveaa** [comment]
Aha, that would be great!

**Comment by nicm** [comment]
It is funny it works with two clients, not really sure why that is.

Does this help: [x.diff.txt](https://github.com/tmux/tmux/files/6324097/x.diff.txt)

**Comment by trygveaa** [comment]
Hm, seems like that patch is already committed in master (bbb3509b)? I tried building and running tmux from master now, and it has the same behavior.

I'm not sure how that patch is relevant though, as it seems to have to do with processing of the ctrl key.

**Comment by nicm** [comment]
Oh sorry, wrong file. Try this: 
[x.diff.txt](https://github.com/tmux/tmux/files/6324208/x.diff.txt)

**Comment by trygveaa** [comment]
Nice, that seems to work great, thanks!

**Comment by trygveaa** [comment]
It seems to pick the smallest client, not the most recent one though. Even though you apparently check activity_time 🤔

**Comment by trygveaa** [comment]
Hm, no, not necessarily smallest. I'm not sure what determines which one is picked, but it's not necessarily the last with activity for me.

**Comment by nicm** [comment]
Try doing this:
~~~~
-			    timercmp(&s->activity_time, &found->activity_time,
+			    timercmp(&loop->activity_time, &found->activity_time,
~~~~

**Comment by trygveaa** [comment]
With that it uses the least recently used client.

**Comment by nicm** [comment]
Or it needs to be > not <.

**Comment by nicm** [comment]
~~~~
                        if (found == NULL ||
                            timercmp(&loop->activity_time, &found->activity_time,
                            >))
                                found = loop;

**Comment by trygveaa** [comment]
Perfect, now it works great, thanks.

**Comment by nicm** [comment]
Applied now, thanks!
