### ISSUE TITLE
`tmux ls | cat` hangs forever when tmux 3.2 connects to tmux 3.1c server

### ISSUE THREAD

**Issue by ivan** [tmux/tmux#2659]
### Issue description

`tmux ls` 3.2 appears to be incompatible with a tmux 3.1c server, but there is no error indicating e.g. "server version is too old for client".

To repro the `tmux ls | cat` hang I see, run a tmux 3.1c server with e.g. `/nix/store/ipmhgk98ih4h7j3rznm3v89qpwmka2y1-tmux-3.1c/bin/tmux` and then in another terminal, run a tmux 3.2 `tmux ls | cat` on Linux and observe that `cat` hangs forever holding on to a pipe whose other end is the **tmux server** and not `tmux ls`. This should repro reliably all the time without reliance on timing issues.

```
at@dev:/home/at# tmux ls | cat
0: 1 windows (created Sat Apr 17 07:27:42 2021) (attached)
^Z
zsh: done       tmux ls |
zsh: suspended  cat

at@dev:/home/at# ps auxw | grep cat
at        353379  0.0  0.0 227332  1452 pts/8    T    07:27   0:00 cat

at@dev:/home/at# ls -l /proc/353379/fd/0
lr-x------ 1 at at 64 2021-04-17 07:28 /proc/353379/fd/0 -> pipe:[368260]

at@dev:/home/at# lsof -n | grep 368260
tmux:\x20 353342                             at   11w     FIFO               0,11      0t0     368260 pipe
cat       353379                             at    0r     FIFO               0,11      0t0     368260 pipe
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 3.1c server and 3.2 client
* Platform (`uname -sp`). NixOS master
* $TERM inside and outside of tmux (`echo $TERM`). xterm-256color outside, screen inside
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
You need to restart tmux entirely when you upgrade.

**Comment by ivan** [comment]
Well, if I were aware that I upgraded tmux, this would have been a lot easier to debug :)

**Comment by nicm** [comment]
I don't think I can really help you with that... :-)
