### ISSUE TITLE
setting xterm escape sequence causes char+112 on prompt

### ISSUE THREAD

**Issue by atomi** [tmux/tmux#266]
Using tmux 2.0
If I type ```echo -ne "\e]12;orange1\a"``` I get a char+112 on my prompt randomly appearing 
![screenshot 2016-01-13 15 30 31](https://cloud.githubusercontent.com/assets/83137/12311998/74b42438-ba10-11e5-974f-7dda8410d093.png)

I believe it's related to this issue https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1435905

However I already have libvte-2.90-9, yet this issue still occurs but only in tmux. I've tried this on gnome-terminal and roxterm and both do this only under tmux. xterm terminal however seems to work as intended both with or without tmux.

**Comment by nicm** [comment]
Default Cr (colour reset) is \033]112\007, probably gnome-terminal does not support this so either you will need to set Cr to something it does support (you can use terminal-overrides) or turn off the cursor colour escape sequences (either in terminal-overrides or with the right TERM).

**Comment by atomi** [comment]
I thought I would try using terminal-overrides to change Cr
```set-option -g terminal-overrides ',xterm*:Cr=\E]12;gray\007'```

$TERM is
```xterm-256color```

The \033]112\007 persists. Though, I might have the incorrect syntax.

**Comment by atomi** [comment]
Yeah. You're right.

Setting Cr
   set-option -g terminal-overrides ',xterm*:Cr=\E]12;gray\007'

This solution works for me.
Thank you!

**Comment by nicm** [comment]
Ok, great. You probably want set -ag if you have a leading comma.
