### ISSUE TITLE
How to set display width of session name?

### ISSUE THREAD

**Issue by deeperlearner** [tmux/tmux#2661]
### Issue description
When session name larger then 8 characters, the session name will display like this.
![image](https://user-images.githubusercontent.com/30494216/115115297-43840a80-9fc6-11eb-8b49-73fe01bca530.png)
I have searched many sites but still can not find the option to set the display width of session name.
Can someone kindly tell me how to let the [bracket] display correctly?
Thanks!

### Required information

* tmux version (`tmux -V`).
tmux 3.1c
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
inside: screen-256color
outside: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
status-left-length
