### ISSUE TITLE
Regression: `split-window` broken when used as a command line argument

### ISSUE THREAD

**Issue by dithpri** [tmux/tmux#2662]
### Issue description

When using `split-window` as a tmux command line argument (not from within tmux), the newly created window's size is incorrect. Example:
```sh
tmux new-session \; \
set-option exit-unattached on \; \
split-window -v -l 10 \; \
send-keys 'echo This window should be 10 lines tall' C-m \; \
split-window -h -l 80 \; \
send-keys 'echo This window should be 80 columns wide' C-m
```

* tmux 3.1c:
<details>

![image](https://user-images.githubusercontent.com/16628163/115158964-19e3e580-a091-11eb-94ad-28f712a0dc57.png)

</details>

* tmux 3.2:
<details>

![image](https://user-images.githubusercontent.com/16628163/115158985-308a3c80-a091-11eb-84f6-346cc7e45744.png)

</details>

#### git bisect:
```
57fe03dc5a132ee131de457afa5724ec735ae811 is the first bad commit
commit 57fe03dc5a132ee131de457afa5724ec735ae811
Author: Nicholas Marriott <nicholas.marriott@gmail.com>
Date:   Sat May 16 14:57:36 2020 +0100

    Move lazy resize from the pane to the window, there is no point in resizing the
    window unless it is the current window, and if we do and don't resize the pane
    until later there are problems if the size changes from A to B then back to A.

 resize.c        | 25 ++++++++++++++++++-----
 server-client.c | 62 ++++++++++++++++++++++++++++++---------------------------
 tmux.h          |  6 ++++++
 window.c        |  5 +++--
 4 files changed, 62 insertions(+), 36 deletions(-)
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.2`
* Platform (`uname -sp`): `Linux unknown` (Arch Linux)
* $TERM inside and outside of tmux (`echo $TERM`): `xterm-kitty`, `screen`
* Logs from tmux. (Note: I ran tmux with the example command from above)
[tmux-out-239851.log](https://github.com/tmux/tmux/files/6332081/tmux-out-239851.log)
[tmux-client-239849.log](https://github.com/tmux/tmux/files/6332082/tmux-client-239849.log)
[tmux-server-239851.log](https://github.com/tmux/tmux/files/6332083/tmux-server-239851.log)

**Comment by dithpri** [comment]
Related: https://github.com/tmux/tmux/issues/2645#issuecomment-820763361

**Comment by Flexximilian** [comment]
I tried giving -x- and -y- as per https://github.com/tmux/tmux/issues/2645#issuecomment-820903158, and it does the trick.

e. g. `tmux new-session -n test -x- -y- \; split-window -dvb -l1`

**Comment by dithpri** [comment]
Unless I'm reading the manual wrong, none of those switches is required (ie. `new-session` does not require *either* `-d ` or `-x`/`-y` to be specified). Passing `-x-`/`-y-` solves the issue for me.
However, this still seems to be a regression – or at least an undocumented change: [that part of the man page hasn't changed in years](https://github.com/tmux/tmux/blame/6f6b7f82611368c9b6f69b8c4fb0af0dacc6fa0a/tmux.1#L1228-L1252), but the behaviour did in the latest release.

Also, giving either of `-x-` or `-y-` works, even if the second switch isn't used:
`tmux new-session -x- -n test \; split-window -dvb -l1`
`tmux new-session -y- -n test \; split-window -dvb -l1`
both work.

**Comment by nicm** [comment]
Try this please: 
[x.diff.txt](https://github.com/tmux/tmux/files/6333617/x.diff.txt)

**Comment by dithpri** [comment]
> Try this please:
> [x.diff.txt](https://github.com/tmux/tmux/files/6333617/x.diff.txt)

Yup, this patch works for me! Do you need logs?

**Comment by nicm** [comment]
No its OK thanks, let me know if you see anything strange with it and I will apply it in a day or so.

**Comment by nicm** [comment]
This is applied now, thanks!
