### ISSUE TITLE
Can't get tmux with true color working with alacritty

### ISSUE THREAD

**Issue by darioisthebest** [tmux/tmux#2665]
### Issue description
I Can't get tmux with true color working in alacritty, I tried all the possible solutions but I can't get that working

### Required information

* tmux version tmux 3.1c.
* Platform Linux unknown.
* $TERM inside and outside of tmux outside: xterm-256color, inside: tmux-256color.

**Comment by ashemedai** [comment]
Does it work if you add a `set-option -sa terminal-overrides ',xterm-256color:RGB'` to your tmux.conf?

**Comment by nicm** [comment]
I don't have time to play guessing games, what have you tried? Where are the logs?

**Comment by darioisthebest** [comment]
No, the `set-option -sa ...` doesn't work

LOG: 
[tmux-client-10689.log](https://github.com/tmux/tmux/files/6343430/tmux-client-10689.log)
[tmux-client-10738.log](https://github.com/tmux/tmux/files/6343431/tmux-client-10738.log)
[tmux-client-10743.log](https://github.com/tmux/tmux/files/6343432/tmux-client-10743.log)
[tmux-client-10790.log](https://github.com/tmux/tmux/files/6343433/tmux-client-10790.log)
[tmux-out-10691.log](https://github.com/tmux/tmux/files/6343434/tmux-out-10691.log)

**Comment by nicm** [comment]
This is only client logs, please make sure you kill tmux entirely before you run with `-vv`.

**Comment by darioisthebest** [comment]
I had also server log but github deleted it because are empty files (during uploading)

**Comment by nicm** [comment]
It should not be empty.

**Comment by darioisthebest** [comment]
I don't know but github can't upload .tar.xz files

**Comment by nicm** [comment]
Your server log file should not be too big. Do this:
~~~~
rm *.log
tmux kill-server
tmux -vv new
~~~~
Then `exit` to exit tmux, and attach the server log file.

**Comment by afh** [comment]
@darioisthebest I have tmux's master branch running with True Color in alacritty 0.7.2 on macOS.
Here's my related tmux config section, maybe you find it helpful:
```
# server options
set-option -gs default-terminal "xterm-256color"
# FYI: check for true color support using tmux info | ag Tc and verify using true-color-support
# Enable True Color and RGB support
set-option -gas terminal-overrides "*:Tc"
set-option -gas terminal-overrides "*:RGB"
# Enable double/curly underline
set-option -gas terminal-overrides '*:Smulx=\E[4::%p1%dm'
set-option -gas terminal-overrides '*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
```

<details><summary><code>termcolors</code></summary>

```
emulate -L zsh

#-fman Display terminal colors and text styles
# USAGE: $0 [-b]
#
# -b: Show color bands

#set -x

local columns=${COLUMNS:-$(tput cols || echo 80)}

local cawk='BEGIN{ for (color = start; color<=end; color++) { printf "\033[48;5;%dm  ", color }  printf "\033[0m\n" }'

systemcolors() {
  print 'System colors:'
  awk -v start=0 -v end=7 $cawk
  awk -v start=8 -v end=15 $cawk
}

colorcube() {
  local cs=6
  print "Color cube, ${cs}x${cs}x${cs}:"
  awk -v cs=$cs 'BEGIN{
    bo = cs * cs;
    bl = cs - 1;
    for (ri=0; ri<cs; ri++) {
      for (bi=0; bi<cs; bi++) {
        bs = 16 + ( bo * bi ) + ( cs * ri );
        be = bs + bl
        for (i=bs; i<=be; i++) {
          printf "\033[48;5;%dm  ", i
        }
        printf "\033[0m";
      }
      print
    }
    printf "\033[0m"
  }'
}

grayscale() {
  print 'Grayscale ramp:'
  awk -v start=232 -v end=255 $cawk
}

truecolor() {
  # https://unix.stackexchange.com/questions/404414/print-true-color-24-bit-test-pattern/404415#404415
  print 'Truecolor ramp:'
  local tawk='BEGIN{
    for (colnum = 0; colnum<term_cols; colnum++) {
        r = 255-(colnum*255/term_cols);
        g = (colnum*510/term_cols);
        b = (colnum*255/term_cols);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum%2+1,1);
    }
    printf "\n";
  }'
  awk -v s="  " -v term_cols="${columns}" $tawk
  awk -v s="/\\\\" -v term_cols="${columns}" $tawk
  awk -v s="  " -v term_cols="${columns}" $tawk
}

textstyles() {
  print 'Text styles:'
  print '• \e[1mBold (\\e[1m)\e[0m'
  print '• \e[2mStandout (\\e[2m)\e[0m'
  print '• \e[3mItalic (\\e[3m)\e[0m'
  print '• \e[4mUnderline (\\e[4m)\e[0m'
  print '• \e[4:2mDoubleUnderline (\\e[4:2m)\e[0m'
  print '• \e[9mStrikethrough (\\e[9m)\e[0m'
  print '• \e[7mReverse (\\e[7m)\e[0m'
  print '• \e[8mHidden\e[0m  (\\e[8m Hidden)'
}

colorbands() {
  print 'Colors bands:'
  #( x=`tput op` y=`printf %$((${COLUMNS}-6))s`;for i in {0..256};do o=00$i;echo -e ${o:${#o}-3:3} `tput setaf $i;tput setab $i`${y// /=}$x;done; )
  (( columns = $columns - 10 ))
  awk -v start=0 -v end=256 "BEGIN{
      for (color=start; color<end; color++) {
        printf \"\033[48;5;%dm% ${columns}s\033[0m\n\", color, \"\"
      }
    }" \
    | nl -v0
}

print TERM=$TERM
systemcolors;print
colorcube;print
grayscale;print
truecolor;print
textstyles;print
[ "$1" = "-b" ] && colorbands
```

</details>


<img width="899" alt="image" src="https://user-images.githubusercontent.com/16507/115753692-c2e55580-a39b-11eb-9f2d-993d89974076.png">

**Comment by darioisthebest** [comment]
@afh Sorry but your script is not working

**Comment by darioisthebest** [comment]
LOG FILES:
[tmux-client-52901.log](https://github.com/tmux/tmux/files/6385143/tmux-client-52901.log)
[tmux-out-52903.log](https://github.com/tmux/tmux/files/6385145/tmux-out-52903.log)
[tmux-server-52903.log](https://github.com/tmux/tmux/files/6385146/tmux-server-52903.log)

**Comment by darioisthebest** [comment]
SCREENSHOT:
![tmux screenshot]](https://user-images.githubusercontent.com/76775977/116256521-8dfa4980-a773-11eb-8d59-e3e156877e27.png)

**Comment by nicm** [comment]
You have not configured RGB colour correctly. See here: https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour

Replace `gnome` with the `TERM` you are using outside tmux, in your case it is `alacritty`.

**Comment by darioisthebest** [comment]
So I should do:
```sh
set -as terminal-features ",gnome*:RGB"
```
But doesn't work

**Comment by nicm** [comment]
...log?

**Comment by darioisthebest** [comment]
New tmux session says
```
/home/dario/.tmux.conf:20: invalid option: terminal-features
```

**Comment by nicm** [comment]
You need 3.2 for terminal-features, read the FAQ entry I pointed you to.

**Comment by darioisthebest** [comment]
The latest tmux release for fedora is 3.1c .....

**Comment by darioisthebest** [comment]
I need to build it from source, it may take some time

**Comment by nicm** [comment]
Or try the other command given in the FAQ for earlier versions??

**Comment by darioisthebest** [comment]
It works fine!!!!!!!!!!!!!

![%b_%d_%H_%M](https://user-images.githubusercontent.com/76775977/116270268-3c57bc00-a77f-11eb-8980-34c4d8a3697b.png)

**Comment by darioisthebest** [comment]
This solutions works in kitty and in alacritty!

Thanks!

**Comment by nicm** [comment]
OK great stuff.
