### ISSUE TITLE
Binding key as "hex code"

### ISSUE THREAD

**Issue by dimitrik-fr** [tmux/tmux#2667]
It looks like it's no more possible in tmux to bind keys as hex code ? 

for ex. worked fine before :
```
bind -n 0x00f2 swap-window -t -1
bind -n 0x00f3 swap-window -t +1
```

which is not working anymore in tmux 3.2 -- is there any workaround ? 
or it's not more supported ?

thank you for any insight !

Rgds, -Dimitri

**Comment by nicm** [comment]
What key is `0x00f2` supposed to be?

**Comment by nicm** [comment]
It appears to work for me:
~~~~
bind-key    -T root         ò                    swap-window -t -1
~~~~

**Comment by dimitrik-fr** [comment]
The problem with typing such letters in text could make them "invisible" in (some) editors, so if you did not pay attention during editing, you'll just loose the initial settings ;-))

Having possibility to use hex code is much more "friendly" and should be easy to add, no ?
any special reason why it was removed ?

NOTE: it's just about supporting hex code as before, regardless the keys used in example above -- it can be any key "configured" in Terminal app to transform whatever pressed keys combinations into a single hex code, just to make it work on remote SSH sessions where remote side don't understand any Alt/Ctrl/Shift combinations ;-))

Rgds, -Dimitri

**Comment by nicm** [comment]
I didn't suggest you change them, I told you that hex codes works for me.

**Comment by nicm** [comment]
BTW you can't enter modifier keys using hex codes, only plain UTF-8. If you want to use modifier keys, you will need to use the `\u` form, for example `bind M-\u00f2 lsk`.

But hex codes still work for me, so you will need to give more information...

**Comment by dimitrik-fr** [comment]
Hmm.. curiously for me even if I paste the line from your example:
```
bind-key    -T root         ò                    swap-window -t -1
```
still not working in tmux 3.2
and using "\u00f2" instead of single letter not working either..

is there any way to trace/debug to see which key tmux is receiving when I'm pressing keys ?

Rgds, -Dimitri

**Comment by nicm** [comment]
Do you see the key binding when you do `tmux lsk`?

**Comment by dimitrik-fr** [comment]
No. Seems like the setting was just ignored.

**Comment by nicm** [comment]
Show me server log please.

**Comment by dimitrik-fr** [comment]
Forgot to mention that key binding is not seen from `tmux lsk`, but on normal start tmux is complaining about "unknown key" (but I think you'll see it from the server log anyway)..
[tmux-server-14297.log](https://github.com/tmux/tmux/files/6351656/tmux-server-14297.log)

**Comment by nicm** [comment]
Can you attach your actual config file please?

**Comment by nicm** [comment]
I have this in .tmux.conf and all work correctly:
~~~~
bind 0x00f2 lsk
bind \u00f2 lsk
bind ò lsk
~~~~

**Comment by nicm** [comment]
Oh, you are not entering the right thing. U+00F2 is UTF-8 `\303\262` - your file has a literal \362 (0xf2) byte which is incorrect.

**Comment by nicm** [comment]
I think you are expecting your terminal to be able to send a literal 0xf2 byte as a key. tmux will only accept UTF-8 keys. You will need to configure your terminal to send UTF-8.

**Comment by dimitrik-fr** [comment]
But this all is working just fine in 1.8 and in 2.3 versions ;-))
just started to look for upgrading to 3.2 and blocked by this..

does it mean that in older versions 0xf2 was kind of "accepted", but then was fixed for correctness, and this is the reason why it's not working now ?

**Comment by nicm** [comment]
It was never really intended to be accepted at least in newer versions, but the way that UTF-8 is stored was changed at some point and part of that made the hex code check stricter.

**Comment by dimitrik-fr** [comment]
Wait, but 0xf2 is still in 0-255 range of ASCII table, right ? 
so, why tmux would refuse it ?
or is there any other ways to enter such letters ?
(before simple 0xf2 was just enough)

**Comment by nicm** [comment]
But 0xf2 is not valid UTF-8, in UTF-8 anything outside of 0-126 is two bytes not one.

**Comment by dimitrik-fr** [comment]
Heh, but it's exactly what I prefer to avoid in SSH sessions -- when connection latency is already high, sending 2 bytes for every character is twice worse interaction ;-)) 

also, people well survived before without UTF8, right ? -- and this is the reason why ASCII table is going higher than just 127 chars, and goes to 255 without any problem (all pseudo-graphics in Terminals worked in the past this way ;-)) -- so, any reason you're truncating tmux capacity to deal with this ?

**Comment by nicm** [comment]
Dealing with dozens of top-bit-set encodings is a lot of work for little gain. UTF-8 is almost 20 years old now and it falls back gracefully to plain 7-bit ASCII. We're not going back, sorry.

**Comment by dimitrik-fr** [comment]
ok, understand, np ;-))
I'm closing this issue then ! -- and THANKS A LOT for so quick and valuable help !
tmux is a true life changer, thank you for all great stuff you're doing !

Rgds, -Dimitri

**Comment by nicm** [comment]
If it is only a few keys you might be able to do it with user-keys, try:
~~~~
set -as user-keys[0] "\327"
bind User0 send "\327"
~~~~
But I would encourage you to get a UTF-8 capable terminal instead...

**Comment by krader1961** [comment]
@dimitrik-fr: FWIW, ASCII only covers the range 0 thru 127 decimal. The range 128 thru 255 is defined by standards such as [ISO 8859](https://en.wikipedia.org/wiki/ISO/IEC_8859). One of the worst standards ever created. It caused far more problems than it solved. Not to mention it only codifies "latin" languages (english, french, german, etc.) which means that Asian languages (often known by the acronym CJK) are handled by other standards. Note, for example, that the byte 0xF2 is a different character in [ISO 8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) (the code page most likely to be used by an American) and [ISO 8859-8](https://en.wikipedia.org/wiki/ISO/IEC_8859-8). There is no such ambiguity with Unicode and UTF-8.

**Comment by dimitrik-fr** [comment]
> If it is only a few keys you might be able to do it with user-keys, try:
> 
> ```
> set -s user-keys[0] "\327"
> bind -n User0 send "\327"
> ```

this workaround is really cool !!! -- thank you !

**Comment by dimitrik-fr** [comment]
> @dimitrik-fr: FWIW, ASCII only covers the range 0 thru 127 decimal. The range 128 thru 255 is defined by standards such as [ISO 8859](https://en.wikipedia.org/wiki/ISO/IEC_8859). One of the worst standards ever created. It caused far more problems than it solved. Not to mention it only codifies "latin" languages (english, french, german, etc.) which means that Asian languages (often known by the acronym CJK) are handled by other standards. Note, for example, that the byte 0xF2 is a different character in [ISO 8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) (the code page most likely to be used by an American) and [ISO 8859-8](https://en.wikipedia.org/wiki/ISO/IEC_8859-8). There is no such ambiguity with Unicode and UTF-8.

Sorry, it looks like I probably bring some misunderstanding here..
- I don't want to "print" these characters (0xf2, 0xf1, etc.) on the screen ;-))
- I just want to get tmux recognizing them as they are (single char in 128-255 range)
- so I could "remap" whatever keyboard combination in my Terminal app to a single key like this and then get it to be accepted on "remote" tmux

that's all ;-))

while for ASCII, the chars between 128-255 are simple called as "Extended ASCII" -- http://www.asciitable.com
(but I'm not an expert ;-)) and really don't care as long as the stuff is doing what I need ;-))

Rgds, -Dimitri
