### ISSUE TITLE
Alacritty key_bindings stopped working in tmux after a system update

### ISSUE THREAD

**Issue by mroavi** [tmux/tmux#2669]
After a `sudo pacman -Syu`, a subset of my programmed Alacritty key_bindings stopped working in tmux. They do work outside of a tmux session.

I verified with `alacritty --print-events` that the correct codes are being received by Alacritty while inside a tmux session:

```
[2021-04-20 22:50:26.947918396] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-04-20 22:50:26.948005505] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-04-20 22:50:27.139672569] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 16845, tv_nsec: 758990222 }, requested_resume: None })
[2021-04-20 22:50:27.139888167] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: SHIFT | CTRL }) }
```

Here is an example of a key-binding that does not work (as defined in my alacritty.yml config file):

```
key_bindings:
  - { key: Return,  mods: Control|Shift, chars:  "\x1b[27;6;51~"    }
```
If I open a tmux pane, type `CTRL-v` and then `CTRL-SHIFT-ENTER`, nothing is displayed. If I do this same test outside of a tmux session, then `^[[27;6;51~` is entered.

Any idea what could have happened?

* tmux version: tmux 3.2
* Platform: Linux unknown
* $TERM inside of tmux: tmux-256color
* $TERM outside of tmux: xterm-256color
* OS: Manjaro Linux x86_64
* Alacritty Version: 0.7.2 (5ac8060)

**Comment by mroavi** [comment]
This seems to be related to https://github.com/tmux/tmux/issues/2645#issuecomment-818656539

**Comment by nicm** [comment]
Where is the tmux server log?

**Comment by mroavi** [comment]
[tmux-client-4958.log](https://github.com/tmux/tmux/files/6348850/tmux-client-4958.log)
[tmux-out-4960.log](https://github.com/tmux/tmux/files/6348851/tmux-out-4960.log)
[tmux-server-4960.log](https://github.com/tmux/tmux/files/6348852/tmux-server-4960.log)

**Comment by nicm** [comment]
There is no sign in this log of you pressing any of these keys:
~~~~
1618989841.415232 /dev/pts/0: keys are 12 (\033[>0;1300;1c)
1618989845.630798 /dev/pts/0: keys are 1 (l)
1618989845.726620 /dev/pts/0: keys are 1 (s)
1618989845.790464 /dev/pts/0: keys are 1 (a)
1618989845.926767 /dev/pts/0: keys are 1 (\r)
1618989859.532945 /dev/pts/0: keys are 3 (\033[O)
1618989860.345336 /dev/pts/0: keys are 3 (\033[I)
1618989860.839179 /dev/pts/0: keys are 12 (\033[<0;112;40M)
1618989860.934224 /dev/pts/0: keys are 12 (\033[<0;112;40m)
1618989862.111224 /dev/pts/0: keys are 3 (\033[O)
1618989863.508867 /dev/pts/0: keys are 6 (\033[I\033[O)
1618989863.509029 /dev/pts/0: keys are 3 (\033[O)

**Comment by mroavi** [comment]
Updated logs with `CTRL-SHIFT-ENTER` presses.
[tmux-server-8942.log](https://github.com/tmux/tmux/files/6349033/tmux-server-8942.log)
[tmux-client-8940.log](https://github.com/tmux/tmux/files/6349031/tmux-client-8940.log)
[tmux-out-8942.log](https://github.com/tmux/tmux/files/6349032/tmux-out-8942.log)

**Comment by nicm** [comment]
This key is `C-S-3`, not `C-S-Enter`:
~~~~
1618991620.946281 /dev/pts/0: keys are 10 (\033[27;6;51~)
~~~~
However, 3.2 will incorrectly see this as `S-3`. If you build tmux from master it should see it as `C-S-3`.

**Comment by nicm** [comment]
`C-S-Enter` would be `\033[27;6;13~` (but you will need master or tmux will think it is `S-Enter`).

**Comment by mroavi** [comment]
Hmm thanks a lot for looking into this. This "hack" was the only way I found to get this (and other similar key combinations) working with the previous version of tmux. Where can I look up the right set of codes for different key combination strokes?

**Comment by mroavi** [comment]
This info is very helpful. I will build tmux from master and try to get this working. Thanks again.

**Comment by nicm** [comment]
I am changing tmux to add an option `extended-keys always` which will make it always send extended key sequences even if the application does not request them. I will be done in about 10 minutes.

So I'd suggest you wait for that, then build from master. Then if you do
~~~~
set -g extended-keys always
~~~~
In .tmux.conf, tmux will recognise and send these keys.

The only caveat is that tmux uses the `u` form rather than the `27` form when it sends the keys inside, so you will need to change any programs inside to expect that if you have configured them. For example, C-S-Enter is:
~~~~
^[[13;6u

**Comment by nicm** [comment]
This is done now:
~~~~
     extended-keys [on | off | always]
             When on or always, the escape sequence to enable extended keys is
             sent to the terminal, if tmux knows that it is supported.  tmux
             always recognises extended keys itself.  If this option is on,
             tmux will only forward extended keys to applications when they
             request them; if always, tmux will always forward the keys.

**Comment by mroavi** [comment]
I confirm that my old "hacks" work well with the latest master version after setting the `extended-keys` option. I will try to find the correct codes from the links you shared above to get rid of the hacks. Thanks again.
