### ISSUE TITLE
Tmux mouse support with Wayland

### ISSUE THREAD

**Issue by mrrhq** [tmux/tmux#267]
Hello,

would it be relatively easy to implement Tmux's mouse support in Wayland? Setting the prefix and using all the key commands work just fine, but this is one of the few things holding me back from using it on Wayland.

On the plus side, it works great on X!

**Comment by nicm** [comment]
Mouse support is a function of the terminal emulator tmux is running in, not the display protocol. You need to talk to the developers of whatever terminal you are using.
