### ISSUE TITLE
`nano` bug after window resize

### ISSUE THREAD

**Issue by bpsib** [tmux/tmux#2670]
### Issue description
Cursor position is not restored correctly after the terminal window size is reduced during a `nano` session if the history buffer is above the height of the window. Part of the history buffer ends up lost because of this. The strange thing is this bug only seems to occur with `nano`.

Steps to reproduce:
1. Fill the tmux window until it's past the height that the window is set
2. Open `nano`
3. Maximize then restore the terminal window
4. Exit `nano`

### Required information

* tmux version: 3.0a
* Platform: N/A (bug occurs on all platforms)
* $TERM inside of tmux: `screen` outside of tmux:  `xterm-256color`

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by bpsib** [comment]
> 
> 
> Does this still happen with master?

I have just installed tmux 3.2 from the release tarball and this bug seems to be fixed.

**Comment by nicm** [comment]
OK good stuff.
