### ISSUE TITLE
Can no longer set max width or height limit after `force-width` and `force-height` options removed

### ISSUE THREAD

**Issue by bpsib** [tmux/tmux#2671]
### Issue description

I find it really annoying that the `force-width` and `force-height` options got removed from version 2.9. This means I can no longer set the maximum limit of the width or height and still have it reduce when reducing the window size below the limit.

It says in the changelog the `resize-window` option does the same thing but it doesn't. It sets `window-size` to manual which I don't want. There needs to be `limit-width` and `limit-height` options that do the same as what the `force-width` and `force-height` options did.

### Required information

Please provide the following information:

* tmux version: 3.0a
* Platform: Ubuntu.
* $TERM inside of tmux : `screen` . Outside of tmux: `xterm-256color`.

**Comment by nicm** [comment]
You can now do this with `resize-window` whether you like it changing `window-size` or not. We are not having two ways to do the same thing.

**Comment by nicm** [comment]
I would be open to including a `manual-or-smallest` choice for `window-size` that picks manual unless there any clients with a smaller size. I don't think it would be a big effort to implement.

**Comment by nicm** [comment]
Added this to todo list.
