### ISSUE TITLE
3.2 regression: enum values need to fit in 32 bits

### ISSUE THREAD

**Issue by ericvw** [tmux/tmux#2672]
Previous issue: https://github.com/tmux/tmux/issues/864 back in 2017.  When this surfaced, https://github.com/tmux/tmux/issues/864#issuecomment-295849226 was mentioned as the fix on `master`.

On SunOS Sparc (`uname -sp`), for tmux >= 3.2, typing in the terminal does not result in any output.

`git bisect` indicates this merge introduces the issue https://github.com/tmux/tmux/compare/a46916b45250ef21d22d7a1fc1bb7a89bd0a3645...588865152a1bb70d77758b68a2869b794aa31dd4.  

The C language standard requires that all values fit in an int.  However, it is implementation-defined behavior for the compiler to choose either signed or unsigned `int`.  [`gcc` defaults to `unsigned int` if there are no negative values ](https://gcc.gnu.org/onlinedocs/gcc/Structures-unions-enumerations-and-bit-fields-implementation.html#Structures-unions-enumerations-and-bit-fields-implementation)specified, which may be why this issue didn't surface earlier.

It appears the path forward is to either change `KEYC_BASE` to a different value or use global constants.  

@nicm, how would you like to proceed?  I'm happy to contribute a patch once I know how you would like to address this.

**Comment by nicm** [comment]
key_code is explicitly unsigned:

    typedef unsigned long long key_code;

If KEYC_BASE is being stored in an int, that code should be changed to use key_code.


From: "Eric N. Vander Weele" ***@***.***>
Reply to: tmux/tmux ***@***.***>
Date: Thursday, 22 April 2021 at 15:04
To: tmux/tmux ***@***.***>
Cc: Nicholas Marriott ***@***.***>, Mention ***@***.***>
Subject: [tmux/tmux] 3.2 regression: enum values need to fit in 32 bits (#2672)


Previous issue: #864<https://github.com/tmux/tmux/issues/864> back in 2017. When this surfaced, #864 (comment)<https://github.com/tmux/tmux/issues/864#issuecomment-295849226> was mentioned as the fix on master.

On SunOS Sparc (uname -sp), for tmux >= 3.2, typing in the terminal does not result in any output.

git bisect indicates this merge introduces the issue a46916b...5888651<https://github.com/tmux/tmux/compare/a46916b45250ef21d22d7a1fc1bb7a89bd0a3645...588865152a1bb70d77758b68a2869b794aa31dd4>.

The C language standard requires that all values fit in an int. However, it is implementation-defined behavior for the compiler to choose either signed or unsigned int. gcc defaults to unsigned int if there are no negative values <https://gcc.gnu.org/onlinedocs/gcc/Structures-unions-enumerations-and-bit-fields-implementation.html#Structures-unions-enumerations-and-bit-fields-implementation> specified, which may be why this issue didn't surface earlier.

It appears the path forward is to either change KEYC_BASE to a different value or use global constants.

@nicm<https://github.com/nicm>, how would you like to proceed? I'm happy to contribute a patch once I know how you would like to address this.

**Comment by ericvw** [comment]
The problem is the special key codes enum:

https://github.com/tmux/tmux/blob/7a6446ac1788bb6676087001da83efc65cf5d096/tmux.h#L168-L170

On Solaris, the `enum` type is a signed `int` and the value of `KEYC_BASE` is outside the range of `INT_MAX`.

> "./tmux.h", line 170: warning: enumerator value overflows INT_MAX (2147483647)

I don't know if there is a way to force an `enum`'s type at the C language level to be unsigned.

**Comment by ericvw** [comment]
I'll take a stab at a patch and try and get something for review later today.

**Comment by nicm** [comment]
OK thanks.

**Comment by ericvw** [comment]
@nicm, sorry to bother you.  When I tried backporting the patch to the 3.2 release, rebinds of the prefix broke.  I'm presuming there is additional context on `master` needed.  What are your plans to release a patch version of 3.2?

**Comment by nicm** [comment]
Is it fixed now by 32c97a7f2f12a6689b8ffc5596484860ac8fbbec?

**Comment by ericvw** [comment]
Yes — it is fixed with that subtle change.  Thank you!
