### ISSUE TITLE
`AC_RUN_IFELSE` prevents cross-compiling

### ISSUE THREAD

**Issue by lopsided98** [tmux/tmux#2674]
### Issue description

3.2 adds several usages of `AC_RUN_IFELSE` to the configure script with no fallback for cross-compiling. Since `AC_RUN_IFELSE` needs to run an executable on the host platform, this can not work when cross-compiling. To fix this, you could add a hardcoded default for the `action-if-cross-compiling` parameter. Alternatively, I have seen people use a cache variable to allow the user to manually specify the correct value for their platform, for example in cpython: https://github.com/python/cpython/blob/39258d3595300bc7b952854c915f63ae2d4b9c3e/configure.ac#L5030

**Comment by nicm** [comment]
https://github.com/tmux/tmux/pull/2651

**Comment by nicm** [comment]
If you get together with the other people who are crosscompiling in https://github.com/tmux/tmux/pull/2651 and figure out a fix that works for everyone, I will apply it. Thanks!
