### ISSUE TITLE
tmux crashes after creating a second session.

### ISSUE THREAD

**Issue by Federico-Ciuffardi** [tmux/tmux#2675]
### Issue description
After the second execution of following line:
```
$TERMINAL -e tmux
```
tmux crashes.

Tried with `$TERMINAL = st` and `$TERMINAL = alacritty`.

### Required information
* tmux version: tmux next-3.3
* Platform: Linux unknown (I use arch btw)
* $TERM inside tmux: st-256color
* $TERM outside tmux: st-256color
* Logs from tmux: 
[tmux-client-24296.log](https://github.com/tmux/tmux/files/6362606/tmux-client-24296.log)
[tmux-out-24298.log](https://github.com/tmux/tmux/files/6362607/tmux-out-24298.log)
[tmux-server-24298.log](https://github.com/tmux/tmux/files/6362608/tmux-server-24298.log)

**Comment by krader1961** [comment]
What does "tmux crashes" mean? Providing the logs in the manner you did makes accessing them needlessly difficult. Just attach them to this issue. Also, I took a quick look at the sole tmux server log you provided and it shows no indication of a problem.

P.S., It is unlikely to be relevant to your problem but setting `$TERM` inside tmux to the same value you use outside of tmux is unlikely to work reliably. Not even if you never use more than one terminal type.

**Comment by Federico-Ciuffardi** [comment]
> What does "tmux crashes" mean?

I don't know how to explain it better, maybe it helps to know that if I run `tmux` in a new instance of a terminal (after running `tmux` on another instance), both the client and server tmux processes don't run anymore, and `server exited unexpectedly` is printed on stderr.

> Providing the logs in the manner you did makes accessing them needlessly difficult. Just attach them to this issue.

Thanks, I didn't know that, I'll do it next time!

 > P.S., It is unlikely to be relevant to your problem but setting $TERM inside tmux to the same value you use outside of tmux is unlikely to work reliably. Not even if you never use more than one terminal type.

I think I was using different values before, but I changed it due to some problems with the colors in the terminal. Can you recommend me some values to use, or point me to a source about `$TERM`?

**Comment by krader1961** [comment]
> ... and server exited unexpectedly is printed on stderr.

That helps us understand your problem. Nonetheless, the logs you provided in your original comment does not show the behavior you describe, AFAICT. Your server log shows that the tmux server is still running unless it was killed by something like signal `SIGKILL` (e.g., `kill -9 $tmux-server-pid`) which would have kept it from logging the reason it died. I suspect you are doing something extremely unusual in your use of tmux. Also, I would expect at least two tmux client logs given your description of how to reproduce the problem. Can your reproduce the problem if you specify an empty config file: `tmux -f /dev/null"?

**Comment by Federico-Ciuffardi** [comment]
On one terminal I executed:
``` 
tmux kill-server; tmux -f /dev/null -vv new
```
On another terminal I executed:
```
tmux
```
It crashed (server exited unexpectedly is printed on stder) again.

The following logs were generated:
[tmux-client-60140.log](https://github.com/tmux/tmux/files/6362729/tmux-client-60140.log)
[tmux-out-60142.log](https://github.com/tmux/tmux/files/6362730/tmux-out-60142.log)
[tmux-server-60142.log](https://github.com/tmux/tmux/files/6362731/tmux-server-60142.log)

**Comment by krader1961** [comment]
It might help if you started the second tmux client with `-vv`. It is also unclear whether the error message was printed on the first, second, or both tmux client terminals. Your most recent logs, again, don't show anything unusual AFAICT. You should probably ensure you can create core dumps. Which might mean running `ulimit -c unlimited` in each terminal session you run `tmux` and otherwise configuring your OS distro to allow the creation of user process core dumps.

**Comment by Federico-Ciuffardi** [comment]
The error message was printed on both tmux client terminals.

> It might help if you started the second tmux client with -vv

New logs:
[tmux-client-68322.log](https://github.com/tmux/tmux/files/6362779/tmux-client-68322.log)
[tmux-client-68400.log](https://github.com/tmux/tmux/files/6362780/tmux-client-68400.log)
[tmux-out-68324.log](https://github.com/tmux/tmux/files/6362781/tmux-out-68324.log)
[tmux-server-68324.log](https://github.com/tmux/tmux/files/6362782/tmux-server-68324.log)

> You should probably ensure you can create core dumps.

I am using arch and from what I read at https://wiki.archlinux.org/index.php/Core_dump I think core dumps are enabled by default.

**Comment by nicm** [comment]
Are you sure tmux is not leaving a core file?

Try with for example `xterm -e 'ulimit -cunlimited; tmux new'`.

Some systems put them in strange locations now.

**Comment by nicm** [comment]
Does this fix the problem?
~~~~
--- a/resize.c
+++ b/resize.c
@@ -136,7 +136,7 @@ clients_calculate_size(int type, int current, struct client *c,
         * For latest, count the number of clients with this window. We only
         * care if there is more than one.
         */
-       if (type == WINDOW_SIZE_LATEST)
+       if (type == WINDOW_SIZE_LATEST && w != NULL)
                n = clients_with_window(w);

        /* Loop over the clients and work out the size. */

**Comment by Federico-Ciuffardi** [comment]
The patch didn't apply, but I installed the lastest version from git and now it works (I think you already committed the changes to master). 

Thanks @krader1961 and @nicm!
