### ISSUE TITLE
Neovim doesn't render lines correctly after switching from a maximized pane 

### ISSUE THREAD

**Issue by gregorias** [tmux/tmux#2677]
#### Actual Behavior

When I switch from a maximized pane with neovim to another pane, the neovim pane starts rendering new lines offset by one. The video explains it:

https://user-images.githubusercontent.com/722385/115953149-f8985480-a4e9-11eb-9f95-6669de33a6b9.mp4

In the video: 

1. I open two vertically split panes with neovim in the left pane.
2. I maximize the neovim pane.
3. I switch to the pane on the right side. You can see that the top bar disappears after a second.
4. I switch back to the neovim pane and change cursorlines. You can see that cursorline renders a line that was previously one line up.
5. After going through the entire file, I refresh neovim with <Ctrl-l> and scroll again.

#### Some Debugging

* The bug was introduced by [this commit from June 2020](https://github.com/tmux/tmux/commit/d919fa1ed0ea3b167ffc811abba26a2dbcd20631). Previous commits do not exhibit this behavior.
* I can "fix" this issue by maximizing and minimizing the terminal window. I suspect that forces some kind of a full refresh.
* I don't have this issue with vim.
* The bug appears on suckless and alacritty terminals.

### Required information

Please provide the following information:

* tmux version: [3.2](https://github.com/tmux/tmux/commit/43c292fa91b22fd8422cc1c4b67e2d2ac3fab767).
* Platform (`uname -sp`): Linux
* $TERM inside and outside of tmux: inside (screen-256color), outside (st-256color)
* Logs from tmux (`tmux kill-server; tmux -vv new`):  (Sorry this file is too large, 30+ MB, I can work on making it smaller in case it's necessary for further debugging)

**Comment by nicm** [comment]
Try without a .tmux.conf and see if that gives you a smaller server log, also you can gzip it.

**Comment by nicm** [comment]
If a pane is resized multiple times but ends up the same size as it started (or there is a risk this happened) tmux will resize it to height - 1 and back to force the application to redraw. It is probable neovim is not handling this correctly but perhaps there is another problem or it is not necessary in this case.

**Comment by gregorias** [comment]
[tmux-server-15849.log](https://github.com/tmux/tmux/files/6369318/tmux-server-15849.log) here's a server log from a session that triggered this bug.

Tmux resizing the application to height-1 sounds like a behavior that is relevant to this issue. However it seems that the old code also did this, yet the bug only appears after https://github.com/tmux/tmux/commit/d919fa1ed0ea3b167ffc811abba26a2dbcd20631, so this fact on its own can't be the root cause.

**Comment by timtyrrell** [comment]
I have been wondering about this one for a while. I always open a horizontal tmux split and then close it to resolve the neovim funkiness. I would love to get this figured out.

**Comment by nicm** [comment]
Hmm yes I expect this is the problem:
~~~~
1619256316.734465 window_pane_send_resize: %0 resize to 106,58
1619256316.985136 window_pane_send_resize: %0 resize to 106,59
~~~~
It seems likely neovim is not correctly handling the second resize. However, it doesn't seem that it is actually necessary for tmux to do this in this case so I am not sure why it is choosing to resize like this.

I am not wild about how this works in tmux TBH so I might change it a bit.

**Comment by nicm** [comment]
Can you try this please and see if it fixes the problem or introduces any additional problems? We may need to bump up this line:
~~~~
+               tv.tv_usec = 10000;
~~~~
If vim is still having problems, although hopefully tmux will correctly recognise it does not need to resize more than once.

Any problems please show me the server log.

**Comment by nicm** [comment]
Forgot to attach the diff: [tmux-resize.diff.txt](https://github.com/tmux/tmux/files/6383122/tmux-resize.diff.txt)

**Comment by gregorias** [comment]
> Forgot to attach the diff: [tmux-resize.diff.txt](https://github.com/tmux/tmux/files/6383122/tmux-resize.diff.txt)

The diff helped. After I've I applied the patch, I can no longer reproduce the buggy behavior.

**Comment by nicm** [comment]
OK I have applied this now, let me know if you see any problems. Thanks!

**Comment by mmngreco** [comment]
I have the same issue using `xterm`, I've installed `tmux` from the source (this commit `a971d - (4 days ago)`) but I continue experiencing this issue.

I have the following in my `tmux.conf`

```ini
set-option -sa terminal-overrides ',xterm-256color:RGB'
set-option -g default-terminal "xterm-256color"
```

I've added the last line in order to check if could fix the issue but it doesn't.

Any workaround ?
