### ISSUE TITLE
Pane border help

### ISSUE THREAD

**Issue by bechampion** [tmux/tmux#268]
Hi all.
I've been looking to add the pane index #P to the border of the pane some how ,  some way to identify the pane index you're currently working on , i know you can add it onto the state bar but i would like it as a pane tittle some how.

Do you know if this is done already or what file should be the one i should start taking a look to?

Thanks!

**Comment by nicm** [comment]
There is no way to do this at the moment.

**Comment by bechampion** [comment]
Thanks  , do you know if someone else asked for this before?

Thanks!

**Comment by nicm** [comment]
Yes there have been a couple of patches around to add a status line to each pane, one of them got to the point of working quite well but there are still some problems and it was never finished.

**Comment by bechampion** [comment]
Thanks mate ill keep an eye on it :)

**Comment by bechampion** [comment]
i guess i can close this too  , Thanks again.
