### ISSUE TITLE
Default paste buffer limit is 50. This is not mentioned in the manual.

### ISSUE THREAD

**Issue by bpsib** [tmux/tmux#2680]
The default number of buffers kept in the paste buffer history (set by `buffer-limit`) is 50. This is mentioned nowhere at all in the manual. I had to find out by myself that this is the default limit.

**Comment by nicm** [comment]
Yes we do not list all the defaults in the manual because it is too much hassle to maintain and it is easy to see the see the defaults from tmux itself.

**Comment by bpsib** [comment]
It would have been pretty time consuming if I hadn't enabled mouse support and used the mouse to find out this default limit so I think it's worth having it in the manual (unless a simpler way exists that I missed).

**Comment by nicm** [comment]
I don't intend to put all the defaults in the manual, sorry. You can see them with `show-options` or (in 3.2) in customize mode (`C-b C`).

**Comment by bpsib** [comment]
> 
> 
> I don't intend to put all the defaults in the manual, sorry. You can see them with `show-options` or (in 3.2) in customize mode (`C-b C`).

I found it now by using `show-options -s`.
