### ISSUE TITLE
[RFC/Feature Request]: Pane/window metadata

### ISSUE THREAD

**Issue by pschmitt** [tmux/tmux#2681]
### Issue description 

> This is a feature request. Nothing is wrong with TMUX :)

Heyhey, I'm the author of [tmux-slay](https://github.com/pschmitt/tmux-slay).

**TL;DR tmux-slay's purpose is to schedule long-running commands with tmux, ie it is [adbuco](https://github.com/martanne/abduco) but with a tmux backend**

### 👉 hashtag-my-wish.com

I'd like to be able to read/write a pane or window's metadata ie. something like this:

```shell
pane_id="$(tmux display-message -p '#{pane_id}')"
tmux set-metadata -t "${pane_id}" 'EXIT_CMD=notify-send "pane killed"'
tmux get-metadata -t "${pane_id)"
# EXIT_CMD=notify-send "pane stopped"
```

I'm not asking for a whole list of properties, just a string one could read/write.
This will probably be useful for other plugins as well.

In its current implementation my script is creating panes/windows with a [start command that contains said metadata via commented env vars that are appended to the command being run](https://github.com/pschmitt/tmux-slay/blob/master/tmux-slay#L380-L393). It works fine, but it feels unnecessarily hackish.

If there's any better, more "correct" way to do what I am trying to achieve, please let me know. Thanks for maintaining tmux and making it better every release.

**Comment by nicm** [comment]
You mean like user options?

**Comment by pschmitt** [comment]
Oh. Yes. How did I miss this?! That sounds *exactly* like what I was after.
Ignore this issue!

**Comment by nicm** [comment]
Great stuff.

**Comment by pschmitt** [comment]
Exactly. I even implemented parsing of the said "metadata" and all in tmux-slay. Had a total blackout there. What a waste of time :facepalm:
Urgh.
