### ISSUE TITLE
Cursor blinking discrepancy on Linux

### ISSUE THREAD

**Issue by topcat001** [tmux/tmux#2682]
This is a strange one I recently hit. I have set custom cursor shapes in vim as follows:
`let &t_SI = "\e[5 q" " Blinking bar.`
`let &t_EI = "\e[1 q" " Blinking box.`
This works fine in a bare xterm, outside tmux. In tmux I have set:
`set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[1 q'`
In OpenBSD (my primary desktop, running the latest snapshot) this works perfectly when running vim from inside tmux. Also, when entering copy-mode tmux resets the cursor to a blinking block as expected. Using the system tmux here (OpenBSD-6.9). git master also works fine.

I have an identical setup on Arch Linux, also fully updated. I think it worked fine till recently (can't pinpoint when it broke since I don't boot into it very often). However recently blinking has stopped working inside tmux. It works as expected in a bare xterm. Inside tmux, the cursor shape is being set correctly, but it is a steady cursor. As soon as I quit tmux, the cursor starts blinking again. Using the Arch package here (tmux-3.2).

The issue can also be reproduced on git master.

* tmux version (`tmux -V`): tmux next-3.3.
* Platform (`uname -sp`): OpenBSD amd64, Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`): xterm outside, tmux-256color inside
* Logs from tmux (`tmux kill-server; tmux -vv new`): Attached.
[linux-logs-broken.tar.gz](https://github.com/tmux/tmux/files/6371195/linux-logs-broken.tar.gz)
[openbsd-logs-working.tar.gz](https://github.com/tmux/tmux/files/6371196/openbsd-logs-working.tar.gz)

I just realised that TERM is set to `xterm-256color` in the above logs. This is just something I was testing, and it does not make a difference as far as the issue is concerned (`tmux-256color` produces the same behaviour).

**Comment by topcat001** [comment]
As discussed with @nicm, reverting https://github.com/tmux/tmux/commit/e8224fb0d123ca9042b0703a35e1a33f0787d327 partially fixes the issue. When I enter insert mode in vim the vertical line blinks, but when I escape to normal mode the block cursor does not blink for almost 30 secs, then it starts blinking. It stops again (when in normal mode) on any keyboard activity. The insert mode cursor appears to be blinking normally.

**Comment by nicm** [comment]
- tmux could be sending something different when working and not working. Look for when it sends (the contents of) the outside TERM's cnorm, cvvis, civis and Ss/Sr. What it sends will be shown with the tty name in the logs eg `/dev/ptyX:`. I also added extra logging in the same commit so you can see that too.

- If it sending something different or the same things but in a different order, why? Is vim sending its cursor sequences in a different order? Look for the inside TERM's sequences in the pane `input_parse` logging. Or is tmux getting the wrong idea.

- If nothing is different, xterm must be behaving differently. Is it the same xterm version? Can you same output as tmux manually to reproduce using the shell printf?

Once we know what is happening we can decide on the fix. The Ss escape sequence that you are using "implies" cursor blinking but there is a separate and much older escape sequence to set blinking using sent with cvvis. Perhaps they are interfering with each other on some xterm versions.

I can take a look next week if you don't have time to see if you can figure it out.

**Comment by nicm** [comment]
Personally I'd concentrate on what is happening without the diff reverted between working/not working platforms, because the change fixes a problem so if would be better to fix it rather than reverting it, but it is a good clue to confirm the problem once we know what it is.

**Comment by nicm** [comment]
Also I suspect your problem *with* it reverted is something different entirely...

**Comment by topcat001** [comment]
> If nothing is different, xterm must be behaving differently. Is it the same xterm version? Can you same output as tmux manually to reproduce using the shell printf?

xterm -version reports `XTerm/OpenBSD(367)` and `XTerm(367)`, respectively. However Arch builds it with different options (an example is sixel support) so there _might_ be some differences.
 
> Once we know what is happening we can decide on the fix. The Ss escape sequence that you are using "implies" cursor blinking but there is a separate and much older escape sequence to set blinking using sent with cvvis. Perhaps they are interfering with each other on some xterm versions. If you can get printf that works on one xterm but not another we can look to see if something was fixed in xterm.
> 
> I can take a look next week if you don't have time to see if you can figure it out.

Thanks for the suggestions! This looks like a good debugging and learning opportunity! I'll start working on this next and see if I can figure it out; will report back soon.

> Personally I'd concentrate on what is happening without the diff reverted between working/not working platforms, because the change fixes a problem so if would be better to fix it rather than reverting it, but it is a good clue to confirm the problem once we know what it is.

Agreed. I reverted it just to see if there is any connection, since it seems to manipulate blinking. All my tests will be performed with the current master.

> Also I suspect your problem _with_ it reverted is something different entirely...

Yes, not sure what is happening there but for now I'll focus on the main issue.

**Comment by nicm** [comment]
Did you get anywhere with this?

It looks like for me xterm resets blinking on `cnorm` even if the cursor style was changed with DECSCUSR.

But has this changed in recent versions? You can try:
~~~~
printf '\033[5 q'; tput cnorm
~~~~

I deliberately made tmux do it this way round to fix a problem if they are done the other way round.

But I think we will need to be more sophisticated and understand what the different cursor styles mean rather than just passing them through, so it can set the blinking flag correctly.

**Comment by nicm** [comment]
How about something like this? So tmux understands which cursor styles imply blinking and uses them instead of setting the blinking flag separately: 
[tmux-cursor.diff.txt](https://github.com/tmux/tmux/files/6384475/tmux-cursor.diff.txt)

**Comment by topcat001** [comment]
Hi, I didn't have a chance to look at this, sorry. However, this diff fixes the issue completely for me. Both bare terminal and vim now display the blinking cursor properly, thanks! I'll try to pinpoint the difference in xterm behaviour. The existing code seems to work in all older xterms (more than a few months old).

**Comment by topcat001** [comment]
In my tests, the "working" OpenBSD xterm does not reset blinking if I run `tput cnorm`. However on the "non-working" Arch Linux xterm `cnorm` causes the cursor to stop blinking. I think this is probably the reason.

**Comment by ThomasDickey** [comment]
"xterm -v" prints a patch number (see the [change-log](https://invisible-island.net/xterm/xterm.log.html)).

OpenBSD's ncurses (and terminal database) are very old (and may lack the tmux-related features), but on each system you can produce an output for the terminal description using "infocmp -x".

**Comment by topcat001** [comment]
Thanks for the pointers! The patch version is 367 for both systems. Attached is a diff of the infocmp output. I included an image because it makes it very easy to see the differences. However I don't know enough to tell if any of these is causing my issue.
![infocmp-diff](https://user-images.githubusercontent.com/22438522/116305770-19b2ac80-a759-11eb-9b13-3710527adc33.png)

**Comment by ThomasDickey** [comment]
I don't *see* any interesting differences: the tmux-related ones (margin, cursor) appear the same.  The one on the left looks like the current version, while the one on the right I'm assuming is OpenBSD (an older version with tmux-related capabilities patched-in).   The diff would be shorter if the `-1` (dash-one) option were used to format the output into a single column.  And having the diff in text makes it easier to study.

**Comment by topcat001** [comment]
Here is a text version of the diff. Left is Linux, right is OpenBSD: http://ix.io/3gO4

**Comment by ThomasDickey** [comment]
That agrees with what I read from the picture: there are differences, but none related to the cursor (`Se`, `Ss`).
In that comparison, except for `kmous` (which uses a feature not supported in OpenBSD's old version of ncurses), the lines beginning with **`k`** aren't interesting.

tmux may have some feature-detection which makes an assumption based on the present of margin-support (`mgc`, `smglr`) or title-stack (the differences in `smcup` and `rmcup`).

**Comment by topcat001** [comment]
Thanks! There is still the differing behaviour if I run `printf '\033[5 q'; tput cnorm` just from a bare xterm. This will result in a blinking vertical line in OpenBSD, but a solid vertical line in Linux. `cnorm` is resetting the blinking state in the later case.

**Comment by nicm** [comment]
The diff fixes both platforms though, yes? It should because we are always reapplying the style after `cnorm` and not using `cvvis` if the cursor style always sets blinking.

**Comment by topcat001** [comment]
Yes, Linux is fixed, and OpenBSD still works properly.

**Comment by nicm** [comment]
`cnorm` inside tmux should still turn off blinking though, does it not?

**Comment by topcat001** [comment]
Yes it does on both platforms.

**Comment by nicm** [comment]
I'm not entirely sure if the cursor style blinking and the SM ?12 blinking should be the same TBH. I'll wait to see if the way xterm seems to work now was intentional :-).

**Comment by nicm** [comment]
If you do `printf '\033[5 q\033[?12l'` instead of adding `cnorm` is it the same? If not, try `\033[?25h` instead.

**Comment by topcat001** [comment]
If I use the above command, which if I understand correctly runs RM 12 after setting the cursor, OpenBSD xterm does not turn off blinking. Is that a bug? In fact on OpenBSD RM/SM 12 does not seem to have any effect. The cursor styles work correctly and blink/not blink as appropriate.

On Linux, RM 12 turns blinking off. If I then run SM 12 as `printf \033[?12h` then it turns on blinking as expected.

**Comment by nicm** [comment]
Does SM ?12 turn on blinking on OpenBSD? Maybe OpenBSD has a patch to disable blinking...

**Comment by nicm** [comment]
Yes: https://man.openbsd.org/xterm#OPENBSD_SPECIFICS

OpenBSD has cursorBlink default to never.

**Comment by nicm** [comment]
Funny how the DECSCUSR still works.

But anyway, I think this tmux change is correct and there should only be one blink flag, it fixes your original problem on Linux.

**Comment by topcat001** [comment]
No, once the cursor is in a non-blinking state for example `printf \033[2 q` then `printf [?12h` will not turn blinking on in OpenBSD.

**Comment by nicm** [comment]
I guess cursorBlink:never must turn off the SM/RM and not DECSCUSR (since that still blinks for you).

**Comment by nicm** [comment]
I think you should be able to get the same behaviour as Linux by changing the X resource or using `-bc`.

**Comment by topcat001** [comment]
Indeed it is not a bug! Actually, because of the XOR `xterm +bc` produces the Linux behaviour (SM 12 blinks, RM 12 stops blinking). I was getting confused between `false` and `never` earlier. The latter also disables RM12/SM12 on Linux.

**Comment by topcat001** [comment]
So I think with this diff everything is working consistently inside tmux. Thanks!

**Comment by topcat001** [comment]
I tested with vim and some other programs as well and cannot find any problems so far.

**Comment by nicm** [comment]
Great, applied now, thanks!

**Comment by topcat001** [comment]
Thanks! I will test it further once I install the update on all my hosts.

**Comment by nicm** [comment]
It's only in GitHub ATM I'll put it into OpenBSD when the tree unlocks.

**Comment by topcat001** [comment]
No problem! I usually have a git master build.
