### ISSUE TITLE
S-M-<key> binding no longer works on tmux 3.2

### ISSUE THREAD

**Issue by ronaldsuwandi** [tmux/tmux#2684]
After upgrading to tmux 3.2 `S-M-<key>` binding no longer works

I used to set up my the following keys to switch between panes

```
# Custom keys to change pane without using prefix
bind -n S-M-Left select-pane -L
bind -n S-M-Right select-pane -R
bind -n S-M-Up select-pane -U
bind -n S-M-Down select-pane -D
```

Now if I press `Shift+Meta+<arrow>` it just won't execute the command and I got `[1;10B[1;10C[1;10A[1;10D` instead

My current option is either to use `M-<arrow>`, `S-<arrow>` or revert back to tmux 3.1b

```
~ ☕️ tmux -V
tmux 3.2
~ ☕️ uname -sp
Darwin i386
~ ☕️ echo $TERM
xterm-256color
```

Attached are the logs. I pressed S-M-Down, S-M-Right, S-M-Up, S-M-Left before quitting tmux

Thanks!

[tmux-client-81995.log](https://github.com/tmux/tmux/files/6381441/tmux-client-81995.log)
[tmux-out-81997.log](https://github.com/tmux/tmux/files/6381442/tmux-out-81997.log)
[tmux-server-81997.log](https://github.com/tmux/tmux/files/6381443/tmux-server-81997.log)

**Comment by krader1961** [comment]
@ronaldsuwand: FYI, there has been a lot of changes to the code in the past few weeks that are relevant to this issue. So it's more important than usual that you actually verify the problem using a tmux built from git head.

**Comment by trofi** [comment]
I think I see a similar change of behaviour:

tmux-3.1c (ok):
```
$ cat -v
# press Shift-F5
^[[15;2~
```
tmux-3.2 and git master (broken):
```
$ cat -v
# press Shift-F5
^[[31~
```

Outside `tmux`: `TERM=xterm-256color`, inside `tmux`: `TERM=screen`. Terminal: xterm-367.

Initially noticed as non-working keys in `mc-4.8.26`.

**Comment by trofi** [comment]
Bisected down to

```
commit 340fd691cbd6f575fc1169269dfa675f30ce71d3
Author: Nicholas Marriott <nicholas.marriott@gmail.com>
Date:   Fri May 15 12:16:41 2020 +0100

    Separate key flags and modifiers, log key flags, make the "xterm" flag more
    explicit and fix M- keys with a leading escape.
```

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by trofi** [comment]
Yes, on `3.2-33-gc03b5746` `Shift-F5` still generates `^[[31~`

**Comment by nicm** [comment]
But this issue is about the arrow keys?

**Comment by trofi** [comment]
Oh, I'll delete my comments then.

**Comment by nicm** [comment]
Please open a new issue with logs and I will take a look, I don't think it is the same thing because \033[31~ is a correct output for some Shift function keys sometimes.

**Comment by ronaldsuwandi** [comment]
@nicm why is it closed? There's a log in the initial issue isn't it? The issue is binding with `S-M-<arrow>` doesn't work. Apologies, I should've made it clearer

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by ronaldsuwandi** [comment]
not sure with master, at the moment I only use the official release for my work laptop... Just hope that on the next release this is fixed
