### ISSUE TITLE
Feature Request: Allow use to have the usable area centered

### ISSUE THREAD

**Issue by dpacbach** [tmux/tmux#2687]
When connected to a tmux session from two clients, one of which has a smaller screen, tmux will shrink the size of the usable area on the larger screen, which is expected.

However, it places this usable area in the upper-left part of the larger screen.

Add an option to center it, so that way the unusable area (with all of the little dots) would be like a "picture frame" around the usable area when viewed on the larger screen.

**Comment by nicm** [comment]
This would be very complicated and I don't see much need for it now that the default `window-size` has been changed.

**Comment by dpacbach** [comment]
> This would be very complicated

Oh that is surprising... I expected that it would be an easy change :)

**Comment by dpacbach** [comment]
I just tried the latest version of tmux and set `window-size` to `latest` and that works nicely for me, so yeah I guess I agree there is not much need for this anymore.
