### ISSUE TITLE
Do not wrap lines when saving to file

### ISSUE THREAD

**Issue by evandrocoan** [tmux/tmux#2688]
### Issue description

I use `capture-pane -S - \; save-buffer /tmp/tmux` to save my current terminal buffer to a file, but this saves the lines wrapped. For example, this prints 3 lines in my tmux because of my screen width is narrow.
```
$ for (( index=0; index< 500; index++ )); do printf -; done; printf '\n';
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------
```
But when saving it to a file, it also saves 3 lines, while its should only save 1 because there is only one line printed:
```
$ for (( index=0; index< 500; index++ )); do printf -; done; printf '\n';
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Is there some other command other than `capture-pane -S - \; save-buffer /tmp/tmux`, I can use to save the buffer without these hardline wrapps added by tmux due to my screen witdth?

I see that this was fixed for tmux buffer rewidth: https://superuser.com/questions/346408/tmux-refresh-display-after-terminal-width-change

### Required information

Please provide the following information:

* tmux version (`tmux -V tmux next-3.3`).
* Platform (`uname -sp Linux x86_64`).
* $TERM inside and outside of tmux (`echo $TERM xterm-256color`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

Related:
1. https://github.com/tmux/tmux/issues/530 - Don't yank newlines in line-wrapped commands
2. https://github.com/tmux/tmux/commit/8903c1f167839569b7514508b38988aa6486575c - Automatically reflow wrapped lines when a pane is resized, requested by

**Comment by nicm** [comment]
`capture-pane -J`.

**Comment by evandrocoan** [comment]
Doing `capture-pane -J; save-buffer /tmp/tmux` works saving the full lines, but it only saves the current visible window, instead o the whole buffer.

Doing `capture-pane -S -; save-buffer /tmp/tmux` correctly saves the whole buffer but had the problem of inserting hard new line wraps.

I tried doing `capture-pane -J -; save-buffer /tmp/tmux` it it gives me an error saying I am not using it correctly:
![image](https://user-images.githubusercontent.com/5332158/116612621-262c3600-a90e-11eb-9410-760973c14d6a.png)

**Comment by nicm** [comment]
Come on...

`capture-pane -J -S- -E-`

**Comment by evandrocoan** [comment]
Thanks, it is now saving full buffer with the full lines without the hard wraps, but all the lines have a bunch of trailing whitespaces. I did not have this problem with `capture-pane -S -; save-buffer /tmp/tmux`

Is there a reason for that ?
![image](https://user-images.githubusercontent.com/5332158/116615375-938d9600-a911-11eb-8465-cbb980d9013a.png)

**Comment by nicm** [comment]
`-J` does not trim whitespace, if it was printed then it gets saved.

**Comment by nicm** [comment]
You could do eg `run "tmux capture-pane -pJ -S -E-|sed -E 's| +$||' >/tmp/xyz"`.

**Comment by evandrocoan** [comment]
Thanks! It is working now. I created this key bind:
```
bind-key v 'capture-pane' \; run "tmux capture-pane -pJ -S- -E-|sed -E 's| *$||' >/tmp/tmux" \; display "Buffer saved to /tmp/tmux!" \;
```

I tried running the old example and the new one with a buffer with 1.000.000 lines, but I could not see much performance difference:

![image](https://user-images.githubusercontent.com/5332158/116636468-c21e6780-a937-11eb-8e1a-86d5f590569e.png)
