### ISSUE TITLE
A possible divide by zero bug

### ISSUE THREAD

**Issue by yiyuaner** [tmux/tmux#2689]
Hi, in the function `window_tree_draw_window` (at  [window-tree.c](https://github.com/tmux/tmux/blob/master/window-tree.c#L663)), we have code like:

```
total = window_count_panes(w);
...
if (sx / total < 24) {
...
}

```

However, the function `window_count_panes`(defined at [window.c](https://github.com/tmux/tmux/blob/master/window.c#L773)) may return 0. Notice that, we have code that explicitly checks its return value. For example, the function `cmd_join_pane_exec` checks its return value against 0 (see [here](https://github.com/tmux/tmux/blob/master/cmd-join-pane.c#L164)) .

Maybe we should check the value of `total` before using it in division?

**Comment by topcat001** [comment]
Is that really true? I didn't look too closely, but it seems that unlike `cmd-join-pane` where the number of panes in a window is changing and may become zero, when `window_tree_draw_window` gets a window to draw, it must have at least one pane, or else it would not exist. Can you think of any case where you actually get a division by zero?

**Comment by yiyuaner** [comment]
Thanks for clarification. It should be safe.
