### ISSUE TITLE
tmux equivalent of screen `nonblock` option.

### ISSUE THREAD

**Issue by phyber** [tmux/tmux#269]
Hi,

First, apologies if `tmux` already has this option under another name or behaves this way by default.

Recently I've seen an odd thing happening inside my `tmux` session when I disconnect. My disconnect isn't clean, I just close my laptop or sleep my computer and let `ssh` timeout. This hasn't been an issue for me since I started using `tmux`, but seems to have become one recently.

I believe the issue I've been seeing is applications running within `tmux` becoming blocked because there is nothing there any more to accept their output (until `ssh` finally times out and `tmux` realises that it's gone). In this case, the blocking causes the application to drop connections to other servers.
Server logs (`auth.log`) showing when the `ssh` connections finally drop correlate with timestamps within the application showing it becoming active again.

After thinking about it for a while, I remembered that I had to solve a similar issue long ago in `screen`. `screen` has the `nonblock` option which is useful in this situation. Searching for `tmux nonblock` I see a single request for this feature from long ago, where the `tmux` author asked "What does it do?", to which there was no response from the requester. From the `screen` manpage.

       nonblock [on|off|numsecs]

       Tell screen how to deal with user interfaces (displays) that  cease  to
       accept output. This can happen if a user presses ^S or a TCP/modem con‐
       nection gets cut but no hangup is received. If nonblock is off (this is
       the default) screen waits until the display restarts to accept the out‐
       put. If nonblock is on, screen waits until the timeout is  reached  (on
       is  treated  as  1s).  If the display still doesn't receive characters,
       screen will consider it "blocked" and stop sending characters to it. If
       at  some time it restarts to accept characters, screen will unblock the
       display and redisplay the updated window contents.

Again, apologies for the request if this already exists or behaves this way by default. If not, would this option be possible?

Thanks.

**Comment by nicm** [comment]
What tmux version?

**Comment by phyber** [comment]
Oops, `tmux` version is `2.1`.
```shell
$ tmux -V
tmux 2.1
```

**Comment by nicm** [comment]
If you go to window.c and comment out the bufferevent_setwatermark() call on line 925, does it fix your problem?

**Comment by phyber** [comment]
Sorry about the progress here, I'm trying hard to reproduce this with a `tmux` I compiled myself, but I haven't had any luck so far.

I can reproduce this issue no problem with the `tmux` included with Debian Stretch, the package is `2.1-3`.

I'll continue to try.

**Comment by nicm** [comment]
Let me know if you can reproduce.
