### ISSUE TITLE
Is it possible to stop it displaying dots to fill the space when a smaller client attaches?

### ISSUE THREAD

**Issue by bpsib** [tmux/tmux#2690]
Is it possible to stop tmux from displaying the dots that fill the space when a client with a smaller window attaches? The dots cause problems with some terminals such is MinTTY. They can cause it to respond very slowly.

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#why-do-i-see-dots-around-a-session-when-i-attach-to-it
