### ISSUE TITLE
Tmux 3.2 does not support colons in config file name

### ISSUE THREAD

**Issue by akervinen** [tmux/tmux#2691]
### Issue description

Loading a config file using `-f` switch fails when the file path contains colons. It seems to relate to `expand_paths` splitting the path list by colons.

### Required information

tmux version, platform and `$TERM`:
```
❯ tmux -V && uname -sp && echo $TERM
tmux 3.2
Darwin i386
xterm-kitty
```

Command line:
```
tmux -vv -f "/Users/me/.config/zsh/.zinit/snippets/OMZP::tmux/tmux.extra.conf"
```

Logs:
```
...
1619777161.392309 peer 0x7f8312531000 message 106
1619777161.392314 client 0x7f8313009600 name is /dev/ttys004
1619777161.392350 tty_resize: /dev/ttys004 now 104x47 (16x38)
1619777161.392361 cmdq_append </dev/ttys004>: [cfg_client_done/0x7f83126155e0]
1619777161.392366 loading /Users/me/.config/zsh/.zinit/snippets/OMZP
1619777161.392391 loading 
1619777161.392398 loading tmux/tmux.extra.conf
1619777161.392416 cmdq_append <global>: [cfg_done/0x7f8312617cf0]
...
```

Output:
```
/Users/me/.config/zsh/.zinit/snippets/OMZP: No such file or directory
: No such file or directory
tmux/tmux.extra.conf: No such file or directory
```

Trying to escape with \ does not work either:
```
❯ tmux -vv -f "/Users/akervinen/.config/zsh/.zinit/snippets/OMZP\:\:tmux/tmux.extra.conf"

/Users/me/.config/zsh/.zinit/snippets/OMZP\: No such file or directory
\: No such file or directory
tmux/tmux.extra.conf: No such file or directory
```

**Comment by nicm** [comment]
I think that is OK TBH.

**Comment by voldemortensen** [comment]
If it's OK then it should be documented that it's a breaking change from previous behavior. There is no documentation that multiple config files can be specified by using a colon separated list. The man page suggests a singular alternative config file can be specified. It's also not mentioned in the CHANGES file.

```     
-f file       Specify an alternative configuration file.  By default, tmux loads the system configuration file from
                   /usr/local/etc/tmux.conf, if present, then looks for a user configuration file at ~/.tmux.conf.

                   The configuration file is a set of tmux commands which are executed in sequence when the server is first started.
                   tmux loads configuration files once when the server process has started.  The source-file command may be used to load
                   a file later.

                   tmux shows any error messages from commands in configuration files in the first session created, and continues to
                   process the rest of the configuration file.
```

On the other hand, it seems pretty naive to blindly split on a colon with no regard for string quoting or escaping. This breaks at least anyone using zinit to load the tmux plugin from OMZ.

**Comment by krader1961** [comment]
While I'm inclined to agree that the value passed to the `-f` flag should be treated as a literal path that does not undergo any transformations by tmux (such as being processed by `expand_paths()`) this statement doesn't make any sense:

> On the other hand, it seems pretty naive to blindly split on a colon with no regard for string quoting or escaping.

Unlike on MS Windows the UNIX process model has the shell being responsible for dealing with quoted strings and tokenizing command arguments before passing those tokens (via the "argv" vector) to the program being launched. Tmux never sees the quotes or backslashes as shown in the O.P.'s examples.

**Comment by nicm** [comment]
I don't mind whether `-f` doesn't support `:`s, has a way to escape them, or it is merely noted in tmux.1.

Using `:`s in filenames is clearly a bit silly, I don't think many people do it.

**Comment by krader1961** [comment]
> Using :s in filenames is clearly a bit silly, I don't think many people do it.

I agree. But see https://dwheeler.com/essays/fixing-unix-linux-filenames.html for a thorough discussion why allowing arbitrary bytes in a filename causes far more problems than it solves. I can't see any reasonable use case for treating the tmux `-f` CLI option value as a colon separated list of pathnames. Treating it as such causes problems with no offsetting benefit.

**Comment by nicm** [comment]
Maybe this: [x.diff.txt](https://github.com/tmux/tmux/files/6413720/x.diff.txt)

**Comment by nicm** [comment]
Did you try it?

**Comment by voldemortensen** [comment]
Personally, I'm entirely unfamiliar with tmux development, but I'll go figure it out if it will get this fixed.

**Comment by voldemortensen** [comment]
That patch does fix the issue for me.

**Comment by nicm** [comment]
Did you restart tmux entirely? What are you running exactly?

**Comment by nicm** [comment]
I'll apply it later, thanks.

**Comment by voldemortensen** [comment]
Thanks!

**Comment by nicm** [comment]
Applied now, thanks!
