### ISSUE TITLE
Shift-F5 changed escape from `^[[15;2~` to `^[[31~`, broke mc.

### ISSUE THREAD

**Issue by trofi** [tmux/tmux#2696]
### Issue description

Before `tmux-3.2` Shift-F5 generated `^[[15;2~` sequence in `xterm`. `tmux-3.2` and master generate `^[[31~`. That breaks `mc` application.

Change bisected down to

```
commit 340fd691cbd6f575fc1169269dfa675f30ce71d3
Author: Nicholas Marriott <nicholas.marriott@gmail.com>
Date:   Fri May 15 12:16:41 2020 +0100

    Separate key flags and modifiers, log key flags, make the "xterm" flag more
    explicit and fix M- keys with a leading escape.
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.2`
* Platform (`uname -sp`): `Linux Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz`
* $TERM inside and outside of tmux (`echo $TERM`): `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`):
  - [tmux-client-56.log](https://github.com/tmux/tmux/files/6413651/tmux-client-56.log)
  - [tmux-out-58.log](https://github.com/tmux/tmux/files/6413652/tmux-out-58.log)
  - [tmux-server-58.log](https://github.com/tmux/tmux/files/6413654/tmux-server-58.log)

**Comment by nicm** [comment]
I suspect you are sending an xterm-key but the flag telling tmux to reflect that in the output is getting lost somewhere so it is sending then non-xterm `S-F5`,

**Comment by trofi** [comment]
Test that seems to illustrate the problem:

```
# xterm as is:
$ echo $TERM
xterm-256color
$ cat -v
^[[15;2~

# tmux in xterm:
$ tmux
$ echo $TERM
screen
$ cat -v
^[[31~
```

**Comment by bpsib** [comment]
Same problem here on WSL. `mc` now sees `Shift`+`F3` through `tmux` as `Shift`+`F5`. This wasn't a problem in previous `tmux` versions.

**Comment by nicm** [comment]
I think we should just always send the xterm(1) keys now, so we should remove the old ones. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/6420740/x.diff.txt)

**Comment by trofi** [comment]
The patch works. Thank you!

**Comment by nicm** [comment]
Applied now, thanks!
