### ISSUE TITLE
Kitty terminal copy bug resolution

### ISSUE THREAD

**Issue by casonadams** [tmux/tmux#2697]
### Update wiki page on clipboard

To correct the bug with kitty term never clearing the clipboard with tmux add or modify the following in the `kitty.conf` file

```
clipboard_control write-primary write-clipboard no-append
```

Adding the `no-append` fixed this for me.

I then had to add the following to my `.tmux.conf` file

```
set-option -g mode-keys vi
set-option -s set-clipboard off
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe 'xclip -se c -i'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -se c -i'
```

I am not sure why the `tmux-yank` plugin wasn't working for me.  I will have to research it further.

**Comment by nicm** [comment]
Changed, thanks!
