### ISSUE TITLE
`set -g mouse on`: it is not possible to rename an inactive window

### ISSUE THREAD

**Issue by 0x8b** [tmux/tmux#2699]
Output of `uname -sp && tmux -V && echo $TERM`:

```
Linux x86_64
tmux 3.2
xterm-256color
```

Configuration:

```
set -g mouse on
```

Steps to reproduce:

- create 2 windows; `one` and `two`, `one` is active window
- right mouse button on `two` in status line; a popup titled 'two' appears
- select `Rename (n)`
- type `whatever`
- the title of the active window (`one`) has changed to `whatever`

**Comment by nicm** [comment]
Yes, `command-prompt` needs to preserve the `cmdq_item` that triggered it, or at least the state it contains.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/6439683/x.diff.txt)

**Comment by 0x8b** [comment]
Works.

**Comment by nicm** [comment]
Applied now, thanks!
