### ISSUE TITLE
Marked Pane border style?

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#27]
It took me a while to figure out why my borders seemed totally messed up. 

The marked pane's border colors are inversed.

The problem I have with this is that I think that the marked pane border-inverting should not trump the active pane border colors. IMHO, the active pane should be the pane with unbroken active-border-color on its border, and the inverting of the marked pane should not be allowed to encroach upon that.

Similarly, I think that maybe there should be an additional border style for the marked pane that we can specify colors for. using inverse for it seems limited and confusing as it was for me.

**Comment by ThomasAdam** [comment]
Marked panes are completely transient in their use---that they just inverse the colours serves well enough, IMO.  Adding code to support this style seems utterly useless to me.

**Comment by unphased** [comment]
Hmm well I just found it confusing is all. I don't anymore now that I know what marked panes are, and so on.

**Comment by unphased** [comment]
Note about [halfway down the page](http://www.alanflavell.org.uk/unicode/unidata25.html), there are quarter blocks and half blocks. Those are all we need...

**Comment by ThomasAdam** [comment]
That's not really relevant.
