### ISSUE TITLE
tmux hangs on load-buffer

### ISSUE THREAD

**Issue by powellb** [tmux/tmux#270]
I am having an issue with load-buffer. If I do the following:

echo "test" | tmux load-buffer -

It hangs (it seems maybe it doesn't think that STDOUT has been closed?). Even Ctl-c will not kill it. I just recompiled libevent 2.0.x (stable) and tmux-2.1 (tarball, not git) and the behavior remains. This is on CENTOS 6.4.

No matter how I pipe information, it hangs:

cat file.txt | tmux load-buffer -

However, tmux load-buffer file.txt does work. Unfortunately, I need to pass output into the buffer, not a file. This behavior works fine using MacOS X; however, on my linux cluster, it does not work. I am happy to provide more information as needed.

**Comment by nicm** [comment]
Please build tmux from Git master and if the problem still exists, run:

pkill tmux
tmux -vvvLx new -d
echo xyz|tmux loadb -

Then show me the tmux-server-* log file.

**Comment by nicm** [comment]
Er, make that:

pkill tmux
tmux -vvv new -d
echo xyz|tmux loadb -

**Comment by powellb** [comment]
Recompiling with the current git branch has solved the issue. I consider it closed.
