### ISSUE TITLE
Script does nothing inside tmux

### ISSUE THREAD

**Issue by jhessin** [tmux/tmux#2700]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.2
* Platform (`uname -sp`).
Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`).
outside: xterm-256color
inside: screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-84028.log](https://github.com/tmux/tmux/files/6431024/tmux-client-84028.log)
[tmux-out-84030.log](https://github.com/tmux/tmux/files/6431025/tmux-out-84030.log)
[tmux-server-84030.log](https://github.com/tmux/tmux/files/6431026/tmux-server-84030.log)

I have a script that can be found [here](http://ix.io/3lUg). I have no problem running it outside of tmux, nor do I have a problem inside tmux on my linux machine, but for some reason when running on my mac the script does nothing. Not sure what the cause could be.

**Comment by jhessin** [comment]
Update: I looked at my linux box and it has tmux 3.0a.

As an experiment I compiled that version for my mac and the script still doesn't run - this seems to be a mac only issue.

**Comment by krader1961** [comment]
Insufficient information. Define "does nothing"? What happens if you run it via `zsh -x`? Also, the link to your script is obviously incomplete since the last line is `elif [ "$downstream" = true`.

**Comment by krader1961** [comment]
@jhessin, Check my updated comment above (not just the email of that comment you read). My initial guess is that there is a difference in the environment variables in your tmux and non-tmux shells. So I would start by running `env` in both environments and comparing their output.

**Comment by jhessin** [comment]
Okay - first the script - the pastebin I was using doesn't seem to work so here it is:
```zsh
#!/usr/bin/env zsh

autoload colors; colors
red=${fg[red]}
green=${fg[green]}
yellow=${fg[yellow]}

# First check for non-default branch
branch=$(git branch --show-current)

# echo "starting branch = $branch"

# split the branch into different parts (zsh)
sep=/
branch_array=("${(ps.$sep.)branch}")

# split the branch into different parts (bash)
# old_ifs=$IFS
# IFS='/'
# read -ra branch_array <<< $branch

# remove the origin/ part of the branch name
if [[ "${branch_array[0]}" = *"origin"* ]]; then
  branch=${branch_array[1]}
fi

# echo "ending branch = $branch"

source ~/.functions.sh

#new workflow

# get updates from upstream
git fetch

# check for upstream changes
if [[ $(git diff HEAD origin/$branch --stat) != '' ]]; then
  downstream=true
else
  echo "${green}There are no upstream changes$reset_color"
fi

# check differences with working tree
if [[ -n $(git status -s) ]]; then
  upstream=true
else
  echo "${green}Tree is clean$reset_color"
fi

if [ "$upstream" = true ] && [ "$downstream" = true ]; then
  echo "${red}need to merge different things$reset_color"
  # gdiff
  git status -s
  # prompt for continue, or cancel
  if confirm "Would you like to commit this" ; then
    echo commiting changes
    git add -A
    git commit -a
  fi

  # compare with upstream
  # gdiff HEAD origin/$branch
  git status -s -- HEAD origin/$branch
  if confirm "Would you like to merge this" ; then
    echo MERGING CHANGES
    git merge origin/$branch
  fi
  echo "PUSHING CHANGES UPSTREAM"
  git push
elif [ "$upstream" = true ]; then
  echo "${yellow}Tree is dirty$reset_color"
  # gdiff
  git status -s

  # prompt for continue, or cancel
  if confirm "Would you like to commit this" ; then
    echo commiting and pushing changes
    git add -A
    git commit -a
    git push
  fi
  echo "PUSHING CHANGES UPSTREAM"
  git push
elif [ "$downstream" = true ]; then
  echo "${yellow}There are upstream changes that need to be pulled downstream$reset_color"
  git pull
  git push # Just in case
fi
IFS=old_ifs
```

**Comment by jhessin** [comment]
As far as clarification goes 'does nothing' is as clear as I can be. I type the command press enter and nothing happens - it just gives me the prompt again. No errors - nothing. Even when running with the '-x' option nothing happens.

As far as the env variable I will look into that and get back with you.

**Comment by jhessin** [comment]
okay... 2 things.

First - I dumped and sorted my env from inside/outside tmux on both machines and here are the results:
[inside_env.txt](https://github.com/tmux/tmux/files/6434678/inside_env.txt)
[linux_inside_env.txt](https://github.com/tmux/tmux/files/6434679/linux_inside_env.txt)
[linux_outside_env.txt](https://github.com/tmux/tmux/files/6434680/linux_outside_env.txt)
[outside_env.txt](https://github.com/tmux/tmux/files/6434681/outside_env.txt)

Next - I feel kinda stupid for not realizing how to run with zsh +x (I thought I had to put it in the script) after running with zsh +x properly the script runs without issue (what's up with that?)

**Comment by nicm** [comment]
If you comment out this bit `autoload colors; colors`, does it work?

**Comment by jhessin** [comment]
nope

**Comment by nicm** [comment]
This does not seem like it is anything to do with tmux, your script does not even use tmux. Why don't you ask the zsh developers?

**Comment by nicm** [comment]
Your `PATH` is not the same inside and outside tmux, are you sure you are running the same zsh and the same git?

**Comment by jhessin** [comment]
Well the script runs outside tmux without issue - I'm sure they would just send me back to you. I can always ask though.

As far as your other questions running `zsh --version` and `git --version` inside and outside result in the same answers. As well as `which zsh` and `which git`.

it should be noted that the zsh version is darwin specific: 
zsh 5.8 (x86_64-apple-darwin20.1.0)

**Comment by nicm** [comment]
tmux does not control what programs inside it do, it only reads what they send.

**Comment by jhessin** [comment]
I found the issue: my script's name `gsync` is identical to a program in `/usr/local/bin`! I have no clue what this program does, but evidently I have been running it instead of my script in tmux because of the order of the PATH variable.

**Comment by jhessin** [comment]
Thanks for your help troubleshooting @nicm.
