### ISSUE TITLE
Memory leaks with long-running tmux sessions

### ISSUE THREAD

**Issue by DirtYiCE** [tmux/tmux#2701]
### Issue description
This has been bugging me for a while, but lately it got worse on one of my computers (maybe because I ran some different workloads recently). For example right now tmux is using 4801M memory according to htop after running for a week. Last week I killed it after leaking 6GB. I might try to reproduce it with a newer version or a different config, but it's going to take some time.

Here's my tmux.conf
```
# Set the prefix to ^E.
unbind C-b
set -g prefix ^F
bind f send-prefix
bind ^F send-prefix
bind ` select-window -t :0

set -sg escape-time 10
set-option -g status-bg magenta
set-option -g status-fg white
set-option -g pane-active-border-style fg=magenta

set-option -g mouse on
set-option -g bell-action any
set-option -g set-titles on
set-option -g status-interval 0
set-option -g status-right "\"#T\""

set-option -g status-right-length 80
set-option -wg window-status-current-format "#[bg=black,fg=white,bold]#I:#W#F"
set-option -g history-limit 100000
set-option -g update-environment "DISPLAY SSH_ASKPASS WINDOWID XAUTHORITY XDG_CONFIG_DIRS XDG_DATA_DIRS XDG_MENU_PREFIX XDG_SESSION_COOKIE DBUS_SESSION_BUS_ADDRESS DESKTOP_AUTOSTART_ID DESKTOP_SESSION XDG_SESSION_PATH XCURSOR_THEME XCURSOR_SIZE SESSION_MANAGER DESKTOP_STARTUP_ID"

set-option -g detach-on-destroy no
set-option -g default-terminal tmux-256color

# set mouse stuff
bind-key -T root WheelUpPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
bind-key -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"

# Left click in the pane followed after a region selection copies that selection
# to the clipboard using xclip
bind -T root MouseUp1Pane run -b "tmux show-buffer | xclip -i"

# Middle click in a pane to paste
bind -T root MouseDown2Pane run -b "exec </dev/null; xclip -o | awk 1 ORS=' ' | tmux load-buffer - ; tmux paste-buffer"

# fuck you 2.7
set-window-option -g allow-rename on
# normal search
bind -Tcopy-mode C-r command-prompt -p'(search up)' 'send -X search-backward "%%%"'
bind -Tcopy-mode C-s command-prompt -p'(search down)' 'send -X search-forward "%%%"'

# 24bit
set-option -ga terminal-overrides ",rxvt-unicode-256color:Tc"

new
```

My history limit might be a bit high, but even if I close the windows I have open, the memory usage only decreases by a couple ten of megabytes at maximum. If I run `tmux lsp -aF '#{history_bytes}'` (from #1261) I get
```
1111843
5819281
10018568
6343371
39149493
2016
393105
15662625
6675983
35993809
```
Summing that I get ~115 MB, not 4 GB. Anything else I should try while I still have this session?

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.1c` (gentoo stable)
* Platform (`uname -sp`): `Linux Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz`
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
glibc is very bad at returning memory to the kernel. tmux can ask it to, and in 3.2 and later it does, but asking it to is very slow, so it only does so once an hour. So if you upgrade to 3.2 or master, the memory will go down eventually.

You could try messing with the malloc options but nobody has ever reported any success doing this.

**Comment by DirtYiCE** [comment]
I've updated to f2951bd4a560692048e68bf29a5b0a288346a7d4 and fixed my tmux config (`set-option -g detach-on-destroy off`), I'll report again in a week, I guess.

**Comment by nicm** [comment]
OK let me know.

**Comment by nicm** [comment]
No you would need to change the code to make it faster, once a minute seems
fast enough TBH.
