### ISSUE TITLE
Buffer load and save hang with port_associate failure on Illumos

### ISSUE THREAD

**Issue by whorfin** [tmux/tmux#2702]
### Issue description
I noticed that `vim` "fakeclip" package was badly misbehaving.  And I tracked it down to a very simple repro case:
```
$ tmux load-buffer test.txt
[warn] port_associate: Not owner
```
I don't always get the `port_associate` message, but when I do, it's not just a warning - the tmux command hangs and must be manually killed.  Sometimes it works fine.
Something is annoyingly, intermittently amiss.

`tmux show-buffer` is similarly affected, although I have found that this always works:
```
$ tmux show-buffer
```
while redirection sometimes triggers the `port_associate` hanging "warning"
```
$ tmux show-buffer >/tmp/busted
[warn] port_associate: Not owner
[warn] port_associate: Not owner
```
This is all with master, currently f2951bd4a560692048e68bf29a5b0a288346a7d4
This happens with or without (ie tmux -Ltest -f/dev/null new) my `.tmux.conf`
I pulled down and built from source some previous versions
tmux-3.2 and tmux-3.1c are all similarly broken
tmux-3.0a _works fine_ so this is a regression

Originally reported to https://github.com/joyent/smartos-live/issues/988 but clearly this is upstream, ie "not their fault"

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  tmux next-3.3  (see above - built from f2951bd4a560692048e68bf29a5b0a288346a7d4, but also 3.2 and 3.1c)

* Platform (`uname -sp`).
"SunOS i386", but that isn't what you probably really want, which is
SunOS serverbox 5.11 omnios-r151030-5bd7739fe4 i86pc i386 i86pc illumos

* $TERM inside and outside of tmux (`echo $TERM`).
"xterm-256color" outside tmux, "screen" inside tmux launched w/o my configuration file
"screen-256color" inside tmux launched w/ my configuration file

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-13415.log](https://github.com/tmux/tmux/files/6446343/tmux-client-13415.log)
[tmux-out-13418.log](https://github.com/tmux/tmux/files/6446344/tmux-out-13418.log)
[tmux-server-13418.log](https://github.com/tmux/tmux/files/6446345/tmux-server-13418.log)

**Comment by nicm** [comment]
tmux never calls this function so it seems most likely to be either a libevent or libc issue.

**Comment by nicm** [comment]
Does this go away if you kill tmux entirely and set `EVENT_NOEVPORT`:
~~~~
tmux kill-server
export EVENT_NOEVPORT=1
tmux new
~~~~

**Comment by whorfin** [comment]
Whoa, yes indeed that fixes it.
It is interesting however that `tmux-3.0a` works fine?!
I will report back to joyent...

**Comment by nicm** [comment]
It might be worth reporting to libevent. But we can just turn evports off for tmux on SunOS and use poll instead (we do that for buggy/incomplete notification mechanisms like epoll on Linux or kqueue on macOS).

**Comment by nicm** [comment]
Not sure why it worked in 3.0, tmux did change so that files are opened by the client rather than server, but that only affects files and not stdout which was always managed by the client. Perhaps we just used stdio previously rather than adding stdout to libevent.

Anyway that mechanism should work fine so best bet is to probably just use poll or select.

**Comment by whorfin** [comment]
Groovy
This probably explains another thing which was bizarre and annoying - resizing ssh'd terminals caused illumos tmux client panes to hang for random intervals.  I could not figure that out, but not realize it correlated exactly with the load/save buffer hangs.
Cheers

**Comment by nicm** [comment]
Try this  please [x.diff.txt](https://github.com/tmux/tmux/files/6446411/x.diff.txt)

**Comment by whorfin** [comment]
That's a bingo - fixes it up right nice

**Comment by nicm** [comment]
Applied now, thanks!
