### ISSUE TITLE
crash when resourcing tmux.conf with syntax error in key binding

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2707]
### Issue description

Tmux crashes when resourcing the `tmux.conf` file if the latter has been edited to include a key binding with a broken syntax.

To reproduce, run these shell commands:

    $ cat <<'EOF' >/tmp/tmux.conf
        bind C-r source '/tmp/tmux.conf'
    EOF

    $ tmux -Lx -f/tmp/tmux.conf

    $ cat <<'EOF' >>/tmp/tmux.conf
        bind x { : >/dev/null
                    ; :
               }
    EOF

Finally, press `C-b C-r`; tmux crashes.

### Required information

 - `$ tmux -V`: tmux next-3.3, commit 4ca6b42c241c9bb6769417ca1dc4fada521f3db8
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs:
 [tmux-client-36874.log](https://github.com/tmux/tmux/files/6463392/tmux-client-36874.log)
 [tmux-out-36876.log](https://github.com/tmux/tmux/files/6463393/tmux-out-36876.log)
 [tmux-server-36876.log](https://github.com/tmux/tmux/files/6463394/tmux-server-36876.log)
 - [backtrace](https://github.com/tmux/tmux/files/6463390/backtrace.txt)
 - [`$ tmux info`](https://github.com/tmux/tmux/files/6463391/info.txt)

**Comment by nicm** [comment]
Nice one, should be fixed now. Thanks!

**Comment by markus-oberhumer** [comment]
I've been bitten by this as well but did not find the time to track it down.

Commit f03b27c72 might be a good candidate for inclusion in a stable update release.

Thanks!
