### ISSUE TITLE
Tmux rectangle copy-mode (via keyboard) broken for EOL selection on short lines.

### ISSUE THREAD

**Issue by ffernand** [tmux/tmux#2709]
### Issue description

When attempting to copy a rectangular block using keyboard navigation, tmux erroneously wraps around the terminal when attempting to expand on a rectangle selection using a line that is shorter than the others in the block.

![01_keyboard-block](https://user-images.githubusercontent.com/69479/118128435-e31b9980-b3c8-11eb-8dd9-786e0e9ad4a9.png)

![02_keyboard-block](https://user-images.githubusercontent.com/69479/118128447-e747b700-b3c8-11eb-94c7-4e271932397a.png)

Using the mouse, it's possible to create the desired block for copy without issue, though it's awkward using both the mouse and keyboard combination to select and activate rectangle selection in copy-mode (I'm aware that you can create bindings to lessen the burden).

There is a work-around using the keyboard, by 
1. moving down the rectangle first towards the longest line on the first column
2. then move over to the end of the longest line horizontally towards the end
3. move the cursor downwards continuing the expansion.

![03_keyboard-block](https://user-images.githubusercontent.com/69479/118128597-1d853680-b3c9-11eb-9ce6-bbaf561dad2d.png)

![04_keyboard-block](https://user-images.githubusercontent.com/69479/118128603-1eb66380-b3c9-11eb-9206-d2be44fe28a8.png)

It should be noted that for both mouse & keyboard selection, the last character of the block is also trimmed away (ie. `xtables-version.h` is trimmed to `xtables-version.`). Visually, it looks as if it should be included in the copy.  It's possible to include an extra character column using the mouse to compensate, but not with the keyboard as the block wraps to the left side of the terminal.

Minimal configuration used to reproduce the above:
```
setw -g mouse on
setw -g mode-keys emacs
setw -g status-keys emacs

set -g status-right ""
set -g status-right-length 0
set -g status-right-style default
```

This was also tested against tmux next-3.3 (git commit id 022d0210c5afa4e516183bf19715316ccca5d240)
### Required information

* tmux 3.2
* ArchLinux up-to-date
* $TERM inside = *screen*, $TERM outside = *xterm-256color*

**Comment by topcat001** [comment]
Thanks for reporting this. I'll take a look this weened.

**Comment by topcat001** [comment]
This is probably my fault since I don't use rectangle mode too much :-). `cursor-right` needs to check if this mode is set and do the right thing. @nicm question: When rectangle mode is on the cursor is supposed to go all the way to the end of the pane line. Is this desirable even if there is no active selection? Thanks!

**Comment by nicm** [comment]
I think rectangle mode should only do anything if you are making a selection, it shouldn't change anything if you aren't.

**Comment by topcat001** [comment]
@ffernand can you please test the following diff? Thanks!
[a.diff.txt](https://github.com/tmux/tmux/files/6488821/a.diff.txt)

**Comment by ffernand** [comment]
Thank you @topcat001 ... this patch is definitely an improvement!!  Though there's still some weirdness over a rectangle selection depending on how you start the selection every-time it involves the end of line.

If you start in rectangle mode and being your selection vertically, then horizontally, everything seems to work as intended as you can see in the images below.

![20210516T081242_maim](https://user-images.githubusercontent.com/69479/118397014-199f2180-b620-11eb-9a61-fef6a71db82c.png)

![20210516T081431_maim](https://user-images.githubusercontent.com/69479/118397018-1d32a880-b620-11eb-87b3-ad96342df4ab.png)

But if you try to select horizontally first... selection doesn't always work out depending on the length of the selection.

![20210516T081834_maim](https://user-images.githubusercontent.com/69479/118397030-26bc1080-b620-11eb-98cd-4683f7baa8ec.png)

![20210516T082016_maim](https://user-images.githubusercontent.com/69479/118397034-2a4f9780-b620-11eb-8e90-018052b78062.png)

This behaviour isn't always consistent either.  If I were to continue grabbing a couple characters more to the right, it's either not  reproducible, or the block-width *increases* by a couple of characters when I start to traverse vertically.

Though in the end, it's still definitely an improvement.  Whenever it does jump around like that, I can still navigate and force it into a selection that I want.  And if I start my selection vertically, before going horizontally, it JUST WORKS!

**Comment by topcat001** [comment]
Of course! I also need to update `cursor-down` and `cursor-up`. Please try the attached diff.
[b.diff.txt](https://github.com/tmux/tmux/files/6490154/b.diff.txt)

**Comment by ffernand** [comment]
@topcat001 Thank you very much!  It's working great!

I've tried every manner of rectangular selection I could think of that included EOL's and it all worked flawlessly!

**Comment by topcat001** [comment]
Thanks for testing! I'm also running some tests myself but hopefully we can merge it if there are no further issues.

**Comment by nicm** [comment]
Applied this now, thanks!
