### ISSUE TITLE
Session "index/numbering" changes when session closed

### ISSUE THREAD

**Issue by eduncan911** [tmux/tmux#2710]
### Problem description

I have not used tmux in Linux for about a year.  So, perhaps a recent upgraded to Ubuntu's apt and/or upgrades between Ubuntu 19.10, 20.04, 20.10 changed this behavior.

There has been a change to the Session's Indexing/quick-shortcut keys, perhaps even purposely.  I tried searching through PRs and Issues but didn't find a reference to this change.

**Previous behavior**: When closing a session at a lower index, that lower index disappeared and remained open to start a new session at that new index.  E.g., with 5 sessions open at indexes 0,1,2,3,4, and you close the session in index "1", your indexes were now 0,2,3,4.  "1" is now open, and a new session would fill "1".

**New behavior:** Now, when you close the session at index "1", all other sessions get re-ordered to fill that spot.  So now, it would be 0,1,2,3.

_This is a problem for someone like me who has about 40 sessions, and has memory-muscled dozens of projects all according to their Session Shortcut key.  But closing a session now completely re-indexes the entire lot, seriously screwing with my mental capacity as I scroll and scroll and scroll now looking for whatever new index/session number I was previously at.  Argh!_

### Expected Behavior

...with 5 sessions open at indexes 0,1,2,3,4, and you close the session in index "1", your indexes should be 0,2,3,4.  "1" is now open, and a new session would fill "1".

### Suggested Resolution

Place this re-indexing/re-ordering behind a feature flag.  It can even be defaulted to on/true.

Just allow us that do not want this, feature/reordering, to turn it off (set to false).

### Steps to reproduce:

1. Create 3 or 4 sessions: ctrl-b, ":", "new"
2. View the sessions, and note the ordering/quick keys: ctrl-b, s (they will be 0,1,2,etc)
3. Switch to the 2nd session, at index 1: ctrl-b, s, 1 (<- note, this index is "1")
3. Let's rename the 2nd session, at index 1, so we can keep track of it: ctrl-b, $, "2nd session"
4. Now, switch to the 1st session, at index 0: "ctrl-b, s, 0"
5. Close it by typing "exit" in the terminal.
6. This will exit tmux as well, but it's still running. Reattach: `tmux att`

Now, you can see the problem by viewing the sessions again: ctrl-b, s

You'll see the "2nd session" has moved from index 1, to now index 0.

### Required information

```
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 3.1b
screen-256color
```

**Comment by nicm** [comment]
Neither of `choose-tree` nor `choose-session` (which it replaced in 2012) have ever allowed gaps in the shortcut keys so I don't know where you are getting this from.

If you build from master you can assign the keys yourself with `choose-tree -sK` but you will have difficulty because there is no "session index", so you either have to change the code to add a format for that or give your sessions a name or user option that you could use instead.

**Comment by nicm** [comment]
If you are using many long-running sessions, I suggest you give each one a key explicitly with for example:
~~~~
set -tsession1 @my_session_key 'M-a'
set -tsession2 @my_session_key 'M-b'
set -tanother_session @my_session_key '0'
~~~~
And then tell `choose-session` to use those instead of the normal shortcut keys:
~~~~
bind s choose-tree -ZsK "#{?session_format,#{@my_session_key},}"
~~~~
You will still need to build from master, of course.

**Comment by eduncan911** [comment]
Not sure how that would play with the tmux.resurrect plugin.

Also, the sessions, while long running, are often "reset" by using the procedure I outlined above: switch to session, exit, create new session in its place - named/used for the same thing.

It is (was) very fluid to also exit a session/project, and create a new session in its place - for another project.  I often used this trick to even organize my sessions in groups (prefixes).

Managing all of those sessions names (often with spaces in them), sync'd to hardcoded shortcut keys in a config file - that has to be reloaded constantly - seems like an anti-pattern.  Especially when it worked perfectly fine before this recent change.

**Comment by nicm** [comment]
It never worked the way you are suggesting.

**Comment by nicm** [comment]
You can sort the sessions by name if you want them always in the same order in tree mode.

**Comment by eduncan911** [comment]
Let me install an older Ubuntu and try.  I must be missing something.

**Comment by eduncan911** [comment]
> You can sort the sessions by name if you want them always in the same order in tree mode.

Ah, that's the problem.  I just tested it in Ubuntu 18.04, and it's sorted by default via name. 

It seems I was right, an updated to 3.x broke/changed this behavior - and others are also having the same issues:

https://unix.stackexchange.com/a/615565/87206

I can confirm the code below reverts this unexpected behavior back to sorting by name by default:

```
bind s choose-tree -s -O name
```

**Comment by nicm** [comment]
Sorting was added in 2017 so it was probably changed at that point.
