### ISSUE TITLE
FORMAT #{e|<=:1,1} evaluates to 0

### ISSUE THREAD

**Issue by mrincredibleu** [tmux/tmux#2712]
### Issue description

The format #{e|<=:1,1} is replaced with 0, but should be replaced with 1. For reference #{e|>=:1,1} is replaced with 1 as expected:

```
$ tmux run-shell "echo #{e|<=:1,1}"
0
$ tmux run-shell "echo #{e|>=:1,1}"
1
```
This reflects the faulty definition of the operator <= in format.c in the function format_replace_expression():

https://github.com/tmux/tmux/blob/022d0210c5afa4e516183bf19715316ccca5d240/format.c#L3993-L3996

Tested on commit 022d0210c5afa4e516183bf19715316ccca5d240.

### Required information
```
$ tmux -V && uname -sp && echo $TERM
tmux 3.2
Linux unknown
screen-256color
```
Will provide tmux logs if relevant.

**Comment by nicm** [comment]
Fixed now, thanks!
