### ISSUE TITLE
Can't create tmux session with command passed to shell

### ISSUE THREAD

**Issue by TurboSlayer** [tmux/tmux#2713]
* Version: not working on tmux 3.2 from tarball and tmux 3.0a from apt
* Platform: Ubuntu 20.04.2, Linux x86_64
* $TERM inside: screen, $TERM outside: xterm-256color

When running `tmux new 'command'` a session does not start. Instead it gives this output: 
`[exited]` 
and the terminal seemingly "types" this: 
`65;1;9c`. 

This is similar to issue #1538, however, my values for default shell and default command are not 'nonsense'. Running `tmux new` without the extra argument works just fine. I can assure you that the command being passed is not nonsense either.

**Comment by nicm** [comment]
Am I meant to guess what command you are running and what's in your config?

**Comment by TurboSlayer** [comment]
> Am I meant to guess what command you are running and what's in your config?

I've tried common commands like `ls`, `cp`, `cd`. None of them work. 

As for the config, it's the default one. I've exported it into the config file in the home directory since it didn't generate one for me... but that shouldn't make a difference right? 

I did have to change the value of default command to '' since it was completely blank after creating that file. I've tried both before and after I made the file anyway so that probably rules out the config being the problem. In case you'd like to know the contents of my config file anyway [here it is](https://pastebin.com/qX6HKx64).

Also, upon giving it another test, I've found out that instead of `65;1;9c` it now says `65;6003;1c` which is really weird.

**Comment by nicm** [comment]
But these commands all exit immediately, so tmux will exit. What if you run `sleep 1000`?

**Comment by TurboSlayer** [comment]
When I run `sleep 1000` a blank terminal shows up. I'm guessing this means it is indeed working as intended. Sorry for wasting your time.

Extra question though: For commands that exit immediately, then is there a way to actually see the outputs of these commands and continue using the terminal?

**Comment by nicm** [comment]
If you want the pane to stay around after the command exits, you can set the `remain-on-exit` option.

If you want it to be left at a shell, you can either run a shell after the command, for example `tmux new "ls; exec $SHELL"`, or send the command to the shell, for example `tmux new \; send ls Enter` (you may need to delay in some shells, for example `tmux new \; run -d1 \; send ls Enter`).

**Comment by TurboSlayer** [comment]
Alright thanks, I'll test them out. I'll close this now.
