### ISSUE TITLE
Pane sizing does not behave as documented

### ISSUE THREAD

**Issue by raffitz** [tmux/tmux#2714]
### Issue description

If I attempt to create a pane with a width of 10% of the terminal columns, it becomes 80 plus 10% of width - 160.

If I attempt to create a pane with a height of 10% of the terminal lines, it becomes 23 plus 10% of width - 48.

If I attempt to create a pane with a width lower than 80 columns, the width is automatically raised to 80.

If I attempt to create a pane with a height lower than 24 lines, the height is automatically raised to 23.

This behaviour is fundamentally different from how tmux behaved in version 3.1c.

#### 3.1c screenshots:

`tmux new \; splitw -v -l 10% \; splitw -h -l 10%`

![image](https://user-images.githubusercontent.com/9017709/118673028-984ab900-b7f0-11eb-9ca0-2eea47bc5611.png)

Image of tmux 3.1c running on a 239x70 lines terminal, with the inner pane being sized at 23x6

---

`tmux new \; splitw -v -l 90% \; splitw -h -l 90%`

![image](https://user-images.githubusercontent.com/9017709/118673397-e1027200-b7f0-11eb-834f-85bf860d9486.png)

Image of tmux 3.1c running on a 239x70 lines terminal, with the inner pane being sized at 215x62

---

`tmux new \; splitw -v -l 1 \; splitw -h -l 1`

![image](https://user-images.githubusercontent.com/9017709/118673903-4b1b1700-b7f1-11eb-9f42-dc0ca1c55c4e.png)

Image of tmux 3.1c running on a 239x70 lines terminal, with the inner pane being sized at 1x1

---

`tmux new \; splitw -v -l 67 \; splitw -h -l 237`

![image](https://user-images.githubusercontent.com/9017709/118674270-90d7df80-b7f1-11eb-81c5-8ae3fedb7b65.png)

Image of tmux 3.1c running on a 239x70 lines terminal, with the inner pane being sized at 237x67

#### 3.2 screenshots:

`tmux new \; splitw -v -l 10% \; splitw -h -l 10%`

![image](https://user-images.githubusercontent.com/9017709/118674631-da282f00-b7f1-11eb-99af-c54e4ed9784d.png)

Image of tmux 3.2 running on a 239x70 lines terminal, with the inner pane being sized at 87x24

---

`tmux new \; splitw -v -l 90% \; splitw -h -l 90%`

![image](https://user-images.githubusercontent.com/9017709/118675042-33905e00-b7f2-11eb-94a1-bdbc189e563d.png)

Image of tmux 3.2 running on a 239x70 lines terminal, with the inner pane being sized at 151x43

---

`tmux new \; splitw -v -l 1 \; splitw -h -l 1`

![image](https://user-images.githubusercontent.com/9017709/118675429-810ccb00-b7f2-11eb-8e09-543a6189b631.png)

Image of tmux 3.2 running on a 239x70 lines terminal, with the inner pane being sized at 80x23

---

`tmux new \; splitw -v -l 67 \; splitw -h -l 237`

![image](https://user-images.githubusercontent.com/9017709/118676194-1dcf6880-b7f3-11eb-87dc-63545195b246.png)

Image of tmux 3.2 running on a 239x70 lines terminal, with the inner pane being sized at 157x44

#### Reproducing in a smaller terminal

If I take the same steps within a terminal of size 80x24, the two tmux versions (3.1c and 3.2) behave identically. If I maximize the terminal, though, the issue reoccurs for 3.2 only.

### Required information

* tmux version (`tmux -V`) is `tmux 3.2`.
* Platform (`uname -sp`) is `Linux unknown` (i use arch, btw, the package is [this one](https://archlinux.org/packages/community/x86_64/tmux/), version 3.2-1).
* $TERM inside and outside of tmux (`echo $TERM`) is `screen-256color` and `rxvt-unicode-256color` respectively. If I use xterm and reproduce the exact same steps, the exact same thing happens but $TERM outside tmux is `xterm`.
* Logs from tmux (`tmux kill-server; tmux -vv new`): `tmux -vv new \; splitw -v -l 10% \: splitw -h -l 10%`: [server log](https://atreides.caladan.space/tmux-logs/tmux-server-28783.log), [out log](https://atreides.caladan.space/tmux-logs/tmux-out-28783.log), [client log](https://atreides.caladan.space/tmux-logs/tmux-client-28780.log)

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by raffitz** [comment]
> Does this still happen with master?

It does not.

**Comment by raffitz** [comment]
This is a #2662 duplicate, sorry.
