### ISSUE TITLE
increase FORMAT_LOOP_LIMIT

### ISSUE THREAD

**Issue by mrincredibleu** [tmux/tmux#2715]
### Issue description

In 83024f57 when using FORMAT expressions sub-expressions even as high as the 10th level get silently formatted to an empty string due to a very low FORMAT_LOOP_LIMIT.

https://github.com/tmux/tmux/blob/83024f57a6dcad690da5bdd559df07ef10d44ccd/format.c#L105-L106

https://github.com/tmux/tmux/blob/83024f57a6dcad690da5bdd559df07ef10d44ccd/format.c#L4444-L4445

This causes confusing behavior when working with even moderately complex nested arithmetic expressions and FORMAT expressions in general:

```
$ tmux run-shell "echo #{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,1}}}}}}}}"
9
$ tmux run-shell "echo #{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,1}}}}}}}}}"
10
$ tmux run-shell "echo #{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,#{e|+:1,1}}}}}}}}}}}"
9
```
I would suggest to increase the FORMAT_LOOP_LIMIT and to add a call to format_log() to ease debugging or to outright fail to parse expressions nested beyond FORMAT_LOOP_LIMIT. Also a hint in the man page could indicate that nesting is not arbitrary.

I ran into this issue when working with arithmetic expressions trying to create a status line that adapts to #{client_width} and want to prevent others from running into this too :)

### Required information

```
$ tmux -V && uname -sp && echo $TERM
tmux 3.2
Linux unknown
screen-256color
```

**Comment by nicm** [comment]
I have bumped it to 100 and added a log message, thanks!
