### ISSUE TITLE
tmux not displaying properly on WSL & Windows Terminal

### ISSUE THREAD

**Issue by norogoth** [tmux/tmux#2717]
In Tmux on WSL using Windows terminal. 
Linux x86_64
tmux 3.0a
screen when in tmux, xterm-256color when out of tmux

When I clear a terminal in tmux, it will not clear the whole thing but it will instead only clear line by line as a I go. This also happens when I open then close nvim. 
![2021-05-24 07_57_42-Window](https://user-images.githubusercontent.com/52639031/119370750-7cb93580-bc6a-11eb-8028-4a0e51b10050.png)

Later the terminal became a mess. I had two windows open and the command line spanned across them anyway.
![2021-05-24 08_21_47-Window](https://user-images.githubusercontent.com/52639031/119370755-7e82f900-bc6a-11eb-89e7-afc55b941619.png)

Using WSL directly (without Windows terminal) resulting in the text becoming very low-res whenever I ran an npm command.

**Comment by norogoth** [comment]
I will close as I believe this is related to issue #2530

**Comment by nicm** [comment]
Most likely `xterm-256color` is not the correct `TERM` for this terminal, or it pretends to be xterm without actually supporting all xterm features.

**Comment by norogoth** [comment]
@nicm Do you know how to tell what is the correct TERM for my terminal?

**Comment by nicm** [comment]
Does the problem go away if you try some simple ones like `vt220` or `ansi`?

**Comment by lockheadone** [comment]
>

**Comment by lockheadone** [comment]
https://github.com/tmux/tmux/issues/2717#issuecomment-852198252

**Comment by norogoth** [comment]
I haven't noticed it going away but I want the 256 color support for nvim appearance.
