### ISSUE TITLE
[comments][patch] improved italics handling

### ISSUE THREAD

**Issue by drurowin** [tmux/tmux#2718]
I expanded on the italics & screen code a little. Instead of seeing "screen*" and giving up, I figured a good check would be to see if *both* `sitm` and `smso` are present in the termcap description, such as if a user patched their termcap files. It should work for any terminal, but I guarded it with a check to see if we're getting around screen's bug anyways.

[001.improved-italics-handling.txt](https://github.com/tmux/tmux/files/6537364/001.improved-italics-handling.txt)

C isn't my native language... how does this look? I tested it (iTerm2 3.3, tmux 9ea971dc + edit) and it works as expected with original unpatched and patched screen termcap files.

**Comment by nicm** [comment]
What good is it to check if `smso` is present in the terminfo entry outside tmux? It almost always will be available, and that doesn't tell us whether the program inside expects us to send italics or standout.

All you are really doing here is making tmux send `sitm` when `default-terminal` is `screen` as well as when it isn't.

**Comment by drurowin** [comment]
Oh... that isn't what I was trying to do. I was wanting to examine the `default-terminal`'s terminfo to see if it distinguished `smso` from `sitm`, not the outer one. I'm not sure how I got it to work the first time aside from operator error.

I'm not really following how `tty->term` is constructed to provide a similar variable to map inner terminfo to outer, and it's probably more work than it's worth.

For a mostly non-code change... for the FAQ, what if the PLEASE NOTE part at the top was changed to say inside TERM _should_ be `tmux*` and only `screen*` if the tmux ones aren't available, and just default `default-terminal` to `tmux` instead of `screen`?

**Comment by nicm** [comment]
I don't think it is time to change the default for `default-terminal` yet, there are too many systems without it.
