### ISSUE TITLE
NVIM esc-key lag

### ISSUE THREAD

**Issue by retfloww** [tmux/tmux#2719]
Issue description

Poor responsiveness in nvim on tmux. When pressing esc, it takes sometime to change to normal mode. 
As you can see in the video(top:tmux | bottom:shell)

https://user-images.githubusercontent.com/67190487/119550370-a2445d00-bd98-11eb-930a-f70389e9d118.mp4

Info:
tmux 3.0a
Linux x86_64
xterm-256color

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#what-is-the-escape-time-option-is-zero-a-good-value

**Comment by retfloww** [comment]
> https://github.com/tmux/tmux/wiki/FAQ#what-is-the-escape-time-option-is-zero-a-good-value

Thank you very much. I have must forgotten the FAQ section
