### ISSUE TITLE
split-window command vs directory

### ISSUE THREAD

**Issue by gbishop** [tmux/tmux#272]
This first bind does what I expect, opening the new pane in the same folder, even when pane_current_path is empty as it is in my home directory.

    bind-key v split-window -h -c "#{pane_current_path}"

But this second bind fails for the same pane. I see the pane split but the new split immediately closes.

    bind-key V split-window -h "#{pane_start_command}"

The second bind works in a pane that has a non-empty pane_start_command. 

The difference appears to be the way empty strings are handled. -c "" ignores the "" but when it is interpreted as a command, it isn't ignored.

I can workaround with the addition of a `run` to force an additional layer of shell quote handling but it seems like a bug.

**Comment by nicm** [comment]
It is not a bug. There is a difference between, for example, 'cat' and
'cat ""' and the same applies to tmux.

You should be able to do something like:

    "#{?pane_start_command,#{pane_start_command},/bin/sh}".

**Comment by nicm** [comment]
Or if you just leave out the quotes it might work:

    bind V splitw-h -- #{pane_start_command}

**Comment by gbishop** [comment]
I think the raw # would get interpreted as a comment, right?

    bind V split-window -h \#{pane_start_command}

appears to fail in the same way, which surprises me.

I'll try to work out the ? variant.

**Comment by gbishop** [comment]
I've got myself even more confused now.

This displays as expected
```
~$ tmux display-message -p "#{?pane_start_command,#{pane_start_command},/bin/bash}"
/bin/bash
```
And this splits the window as expected.
```
~$ tmux split-window /bin/bash
```

But none of these work...
```
~$ tmux split-window "#{?pane_start_command,#{pane_start_command},/bin/bash}"
~$ tmux split-window \#{?pane_start_command,\#{pane_start_command},/bin/bash}
~$ tmux split-window '#{?pane_start_command,#{pane_start_command},/bin/bash}'
```

**Comment by ThomasAdam** [comment]
Surely you need -F before the format?

**Comment by nicm** [comment]
-F is optional for display-message and not needed for split-window.

**Comment by gbishop** [comment]
Yes, -F appears to apply to the formatting of the output printed by the -P option. 

Could it be that variable expansion simply doesn't work in the command field?

**Comment by nicm** [comment]
Hmm I assumed you had it working with other formats, but you are right, commands are not expanded.

**Comment by nicm** [comment]
You will need to do it using run-shell.

**Comment by gbishop** [comment]
Ah, that explains it.
