### ISSUE TITLE
pane-border-lines "off" option is missing

### ISSUE THREAD

**Issue by 205g0** [tmux/tmux#2720]
Why? To have a minimal look.

Having no pane borders—I did this by giving bg, pane border's fg and bg all the same color—works surprisingly well reducing even more visual noise and clutter. This is not for someone who just started out with tmux but once you're a bit more advanced, I could imagine that I am not the only one who appreciates a clean, minimal look. It's also quite easy for the eye to know where panes are, either by just their nature, running apps, line numbers, white space, text alignment, etc. but usually because of a distinct, colorful prompt.

Since I often switch between a dark and light terminal throughout the day, it would be easier if there was a pane-border-lines "off" option because it would be too tedious to change the pane colors in order to make them invisible every time.

**Comment by nicm** [comment]
This is not currently supported.
