### ISSUE TITLE
Control mode not echoing on Cygwin

### ISSUE THREAD

**Issue by wildmichael** [tmux/tmux#2725]
### Issue description

On Cygwin the following worked with version 3.1b:

*Terminal 1*:
```sh
$ tmux new -s mysession
```

*Terminal 2*:
```sh
$ tmux -C attach -t mysession
split-window
split-window -h
```

*Terminal 1*:
```sh
$ echo "Hello, World!"
```

With this sequence of commands, the window in Terminal 1 would split in three panes and in Terminal 2 the commands and output coming from Terminal one would be echoed with the `%output` prefix.

However, now with version 3.2 (and master) this last part doesn't work anymore. The window in Terminal 1 still gets split into three panes, however the Terminal 2 does not echo anymore and is also not responding to `CTRL-C`.

### Required information

```sh
$ uname -sp && tmux -V && echo $TERM
CYGWIN_NT-10.0 unknown
tmux 3.2
xterm-256color
```

### Log files

[tmux-server-5446-TERMINAL1.log](https://github.com/tmux/tmux/files/6571328/tmux-server-5446-TERMINAL1.log)
[tmux-client-5444-TERMINAL1.log](https://github.com/tmux/tmux/files/6571329/tmux-client-5444-TERMINAL1.log)
[tmux-out-5446-TERMINAL1.log](https://github.com/tmux/tmux/files/6571330/tmux-out-5446-TERMINAL1.log)
[tmux-client-5486-TERMINAL2.log](https://github.com/tmux/tmux/files/6571327/tmux-client-5486-TERMINAL2.log)

**Comment by nicm** [comment]
Are you sure you are testing the same Cygwin version? If you build 3.1c without changing anything else, does it still work?

**Comment by wildmichael** [comment]
I didn't try 3.1c, but with 3.1b it works as expected.

**Comment by wildmichael** [comment]
I bisected the history and it appears that the merge a4cb700269e033b5ad429275d7c61d3c3c2f1af3 introduces the problem into the `master` branch.

**Comment by nicm** [comment]
Oh yeah, we pass the file descriptor for stdout up to the server now. Cgywin does not support file descriptor passing so this will no longer work on Cygwin.

**Comment by wildmichael** [comment]
So, I assume this is a won't-fix?  The problem is that the broken control mode causes the [mosh](https://github.com/mobile-shell/mosh) test suite to fail/hang.

**Comment by nicm** [comment]
Dunno, we have a workaround for the tty file descriptor, maybe that would work for this too.

**Comment by nicm** [comment]
Does this fix it?
~~~~
--- a/server-client.c
+++ b/server-client.c
@@ -2305,6 +2305,7 @@ server_client_dispatch_identify(struct client *c, struct imsg *imsg)

 #ifdef __CYGWIN__
        c->fd = open(c->ttyname, O_RDWR|O_NOCTTY);
+       c->out_fd = dup(c->fd);
 #endif

        if (c->flags & CLIENT_CONTROL)

**Comment by wildmichael** [comment]
My limited testing at least shows output being echoed. I'll prepare a patched test package and ask whether mosh is fixed by this and will come back to you with the results.

Thanks a ton for the quick response!

**Comment by wildmichael** [comment]
Unfortunately, this simple fix doesn't work when `stdout` is redirected. The person who reported this issue for Cygwin came up with this partial fix with which now half of the mosh test suite runs, the other half hangs up for yet unclear reasons:
```diff
--- origsrc/tmux-3.2/server-client.c    2021-06-05 09:29:04.102404100 +0200
+++ src/tmux-3.2/server-client.c        2021-06-05 11:36:50.162975600 +0200
@@ -2269,7 +2269,16 @@ server_client_dispatch_identify(struct c
        log_debug("client %p name is %s", c, c->name);

 #ifdef __CYGWIN__
        c->fd = open(c->ttyname, O_RDWR|O_NOCTTY);
+       if (0 < c->pid) {
+         /* UNIX domain sockets can't be used to transfer open fd on Cygwin yet */
+         char *fdnstr = NULL;
+         int fdnsz = asprintf(&fdnstr, "/proc/%u/fd/1", c->pid);
+         if (0 < fdnsz) {
+           c->out_fd = open(fdnstr, O_RDWR|O_NOCTTY);
+           free(fdnstr);
+         }
+       }
 #endif

        if (c->flags & CLIENT_CONTROL)
```

**Comment by nicm** [comment]
Yes that would probably do it.

**Comment by wildmichael** [comment]
Any inkling as to what could cause the hangs?

**Comment by nicm** [comment]
Not without any information.

**Comment by wildmichael** [comment]
I'll try to make some time to see myself what's going on there and what specific scenario triggers the hangs.

**Comment by nicm** [comment]
Nothing?
