### ISSUE TITLE
nnn fails to redraw when inside tmux

### ISSUE THREAD

**Issue by dbolgheroni** [tmux/tmux#2726]
### Issue description

In *i3*, when opening a new window with *splitv* layout (when the second window appears in the bottom) or *stacking* layout (when the second window appears on top of the previous window), and then close this second window, *nnn* (`sysutils/nnn` from ports) fails to redraw.

At first the problem seems to be *nnn*-related, but the same operation outside *tmux* causes no problem.

### Steps to reproduce

1. in *i3*, open a xterm
2. enter *tmux*
3. open *nnn* on it
4. change layout to *splitv* or *stacking*
5. open a second *xterm* and then close
6. check that *nnn* inside tmux will garble chars
6.1. follow steps 1, 3, 4, 5 and check that it's OK without *tmux*

### Required information

* *tmux openbsd-6.9* (-current, #39: Sun May 30 15:59:42 MDT 2021)
* *OpenBSD amd64*
* *screen-256color* inside and outside *tmux*

### Other relevant information

* *nnn* v4.0

### Logs

[tmux-client-76743.log](https://github.com/tmux/tmux/files/6572574/tmux-client-76743.log)
[tmux-out-97861.log](https://github.com/tmux/tmux/files/6572575/tmux-out-97861.log)
[tmux-server-97861.log](https://github.com/tmux/tmux/files/6572576/tmux-server-97861.log)

**Comment by nicm** [comment]
Does this still happen if you build tmux from Git master?

**Comment by dbolgheroni** [comment]
> Does this still happen if you build tmux from Git master?

Yes.

### Screenshots

Before:
![ss-20210601092257](https://user-images.githubusercontent.com/1566650/120324039-8838dc00-c2bc-11eb-8460-77ae35c14eb3.png)

Opening a new window in *i3* with *splitv* layout:
![ss-20210601092302](https://user-images.githubusercontent.com/1566650/120324061-90911700-c2bc-11eb-8bdd-de7a8e728ea3.png)

After. Redrawing the screen with `^L` won't have any effect when inside *tmux*. Hitting `j` or `k` to move between files will further break the layout:
![ss-20210601092309](https://user-images.githubusercontent.com/1566650/120324077-95ee6180-c2bc-11eb-8b32-d1c274bd2984.png)

**Comment by nicm** [comment]
Show tmux server log from master please.

**Comment by dbolgheroni** [comment]
Sure.

[tmux-client-74952.log](https://github.com/tmux/tmux/files/6576656/tmux-client-74952.log)
[tmux-out-60118.log](https://github.com/tmux/tmux/files/6576657/tmux-out-60118.log)
[tmux-server-60118.log](https://github.com/tmux/tmux/files/6576658/tmux-server-60118.log)

**Comment by nicm** [comment]
tmux is definitely asking it to resize:
~~~~
1622554930.923966 window_pane_send_resize: %0 resize to 193,27
1622554932.958084 window_pane_send_resize: %0 resize to 193,57
~~~~
Can you attach `ktrace` to `nnn` and make sure it is getting the `WINCH` signals:
~~~~
ktrace nnn
... reproduce the problem
... exit nnn
kdump|grep WINCH
~~~~
You will see something like:
~~~~
 35326 top      PSIG  SIGWINCH caught handler=0xe844ee09660 mask=0<>
~~~~

**Comment by dbolgheroni** [comment]
The *kdump* output:
```
 92666 nnn      CALL  sigaction(SIGWINCH,0,0x7f7ffffbc5d8)
 92666 nnn      CALL  sigaction(SIGWINCH,0x7f7ffffbc5e8,0)
 92666 nnn      PSIG  SIGWINCH caught handler=0x7dee7967440 mask=0<>
 92666 nnn      PSIG  SIGWINCH caught handler=0x7dee7967440 mask=0<>
```

**Comment by nicm** [comment]
OK so this seems like a bug in `nnn`.

**Comment by dbolgheroni** [comment]
I'll have to double check because the same thing does not occurs when not in *tmux*.

Anyway, thank you.

**Comment by nicm** [comment]
Whether it does or not, tmux is doing what it should.
