### ISSUE TITLE
Feature request: Escape sequence support in tmux config files

### ISSUE THREAD

**Issue by khenriks** [tmux/tmux#2732]
### Issue description

I would like a way to specify a character in the tmux config file as an escape sequence (e.g. \uxxxx) instead of having to encode the character directly. Ideally it would support at least the standard [C escape sequences](https://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences).

Generally speaking, non-ascii characters cannot be as reliably shared and distributed as ascii. Fonts may have inconsistent sets of available glyphs, which means that a file one can edit in the terminal with one font may not show up correctly when edited in a text editor with a different font. Trying to copy and paste something from the internet into an SSH session may not work correctly. It's just more painful to deal with.

If tmux supported escape sequences, it would bypass this issue by letting the config file be represented purely with ascii characters.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 2.8
* Platform (`uname -sp`): Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`). screen-256color inside, xterm-256color outside
* ~~Logs from tmux (`tmux kill-server; tmux -vv new`)~~

**Comment by khenriks** [comment]
After thinking about it, I think this should be done when the string is used, rather than when reading the config file. It should be used when interpreting strings like the setting for status-left and status-right, for example. This is so that commands like set-option and show-options work correctly, and round-trip values properly.

**Comment by krader1961** [comment]
How would this affect backward compatibility? Are there any tmux config files which contain backslashes whose interpretation would be affected by your proposal? I would bet the answer is yes. That would make this proposal a non-starter. Too, it seems to me most of the places where you might use this feature you can already do so.

You should probably provide at least a couple of concrete examples for how this would be useful. It's also a Unicode world and tmux explicitly only supports UTF-8. Ignoring, of course, features like the tmux `-u` option but I think those are mostly irrelevant with respect to this proposal. I long ago assumed any config file I deal with uses UTF-8 encoding. And I say that as a grey beard who earned my first paycheck as a programmer in 1979; which is before Unicode existed.

**Comment by khenriks** [comment]
Is the behavior described in the [FORMATS](https://man.openbsd.org/OpenBSD-current/man1/tmux.1#FORMATS) section of the manual page set in stone? How do you deal with adding new functionality in that regard? I believe that any configuration adversely affected by this change could be extremely easily updated. Using this syntax also has the benefit of behaving as users expect from other tools (for example, see [vim](http://vimdoc.sourceforge.net/htmldoc/eval.html#expr-quote)).

I don't believe that's the only possible option here, though. An expansion to the `#{}` syntax could be devised, for example.

As far as concrete examples, I am trying to set up a fancy status line à la [this article](https://medium.com/hackernoon/customizing-tmux-b3d2a5050207) using [these symbols](https://github.com/ryanoasis/nerd-fonts), and it's much more difficult than it should be because as I said non-ascii characters are not reliably preserved. For example, take this symbol: . Without the right fonts, it doesn't show up correctly at all (for example, this comment). It should look like a leftward-pointing triangle. If I paste it into a local shell session, I get the correct result (after installing appropriate fonts). If I paste it into a remote shell session inside a tmux session through SSH, I do not get the correct result; the character is corrupted along the way.

Even saying everything should be UTF-8, you run into things like [Normal forms](https://en.wikipedia.org/wiki/Unicode_equivalence#Normal_forms) that mean the same glyphs can have distinct byte sequences, so it's not quite so simple.

**Comment by krader1961** [comment]
> Without the right fonts...

In my web browser symbol "", \ue0b2, does not render as you described; i.e. a leftward-pointing triangle. I see a block with alternating horizontal lines and spaces. That is because your Unicode character is in the Unicode "private use area" for code points and thus is inherently private to your situation. I would expect you proposed change to tmux config file syntax to result in the same outcome.

**Comment by nicm** [comment]
https://man.openbsd.org/OpenBSD-current/man1/tmux.1#PARSING_SYNTAX

**Comment by nicm** [comment]
>Outside of quotes and inside double quotes, these replacements are performed:
>    Environment variables preceded by $ are replaced with their value from the global environment (see the GLOBAL AND SESSION ENVIRONMENT section).
>    A leading ~ or ~user is expanded to the home directory of the current or specified user.
>    \uXXXX or \uXXXXXXXX is replaced by the Unicode codepoint corresponding to the given four or eight digit hexadecimal number.
>    When preceded (escaped) by a \, the following characters are replaced: \e by the escape character; \r by a carriage return; \n by a newline; and \t by a tab.
>    \ooo is replaced by a character of the octal value ooo. Three octal digits are required, for example \001. The largest valid character is \377.
>    Any other characters preceded by \ are replaced by themselves (that is, the \ is removed) and are not treated as having any special meaning - so for example \; will not mark a command sequence and \$ will not expand an environment variable.

**Comment by khenriks** [comment]
Thank you Nicholas! It seems my feature request has already been fulfilled, and works exactly the way I had originally expected. I guess this use case must have already come up before.

I didn't see that section of the manual, and when I tried doing this locally it didn't work. However, it seems my version of tmux (2.8 from Debian stable) is just too old. When a found and tried out a newer version, it works as expected. Thanks again!
