### ISSUE TITLE
tmux not forwarding extended keys to applications

### ISSUE THREAD

**Issue by ek234** [tmux/tmux#2733]
tmux session receives keys of the form C-S-... properly but doesn't send to applications.

I use alacrity. My alacrity config includes:
```
> key_bindings:
>   - { key: O,         mods: Control|Shift,  chars: "\x1b[79;6u"                     }
```
minimal tmux config:
```
set-option -g default-terminal "screen-256color"
set -s extended-keys on
set -as terminal-features '*:extkeys'
```

Inside tmux, `tmux bind -n C-S-O lsk` recognizes the key combination perfectly.
Then I started a new session (so C-S-O was no longer bound). Nothing is shown when I press the key combination in cat inside tmux. ( in cat outside tmux, it prints `^[[79;6u` as expected. )

https://github.com/tmux/tmux/wiki/Modifier-Keys#troubleshooting-steps suggests making sure there are no bindings for the key in the root table.

What is the root table referring to?

If it is referring to `tmux list-keys` table, I do not have any bindings for C-S-O in `tmux list-keys`. So what might the issue be?

Perhaps there is some additional configuration that I need to add but I couldn't find anything.

Thanks a lot

Tested on latest code in git.

* tmux version (`tmux -V`): tmux next-3.3
* Platform (`uname -sp`): Linux x86_64
* $TERM inside of tmux (`echo $TERM`): screen-256color
* $TERM outside of tmux (`echo $TERM`): xterm-256color

**Comment by nicm** [comment]
The application inside has to request the keys, or you set `extended-keys` to `always`.

**Comment by ek234** [comment]
> The application inside has to request the keys, or you set `extended-keys` to `always`.

thanks.. it works perfectly now.

Btw was this specified anywhere? I couldn't find it. In case I have similar doubts, where should I look?

**Comment by nicm** [comment]
It was added after 3.2 so it was not change log yet, you could have found it in past issues or the man page. It will be in CHANGES file and release notes for 3.3 or maybe 3.2a.

**Comment by ek234** [comment]
ohh I see.

Thanks
