### ISSUE TITLE
is there a possible to remove verticle border line on  popup window

### ISSUE THREAD

**Issue by ask-github** [tmux/tmux#2734]
### Issue description
i want to copy lines in popup, but the verticle border line, it is can;t be done
![image](https://user-images.githubusercontent.com/72971953/121136545-5bf6ff80-c868-11eb-85c7-f6c94fed17f5.png)

copy output of command will include the border lines

thanks

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux next-3.3
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
xterm
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Not at the moment, no.

**Comment by ask-github** [comment]
is there a plan to develop it.

can't copy lines in popup windows is annoying

**Comment by nicm** [comment]
It is on the todo list but don't hold your breath.

**Comment by LiquidityC** [comment]
Some terminals have great block selection when holding ctrl. This might solve your problem.

**Comment by tty5** [comment]
> Some terminals have great block selection when holding ctrl. This might solve your problem.

i need copy the orignal multi lines from output of command. the lines may be long. it can't be split
