### ISSUE TITLE
Odd behavior from scrolling region in horizontal split

### ISSUE THREAD

**Issue by LiquidityC** [tmux/tmux#2735]
### Issue description

I'm having a super specific issue with an application I'm building/using. It concerns scrolling regions. My application maintains a scrolling region from line 2 to *whatever fits the terminal* when outputting text (mud client). This all works great in all configurations and pane setups.
Recently I added a scroll split feature where we create a smaller scrolling region for output whilst printing scroll history "manually" above that region.

This works fine on a "fullscreen pane" but when you run the mud client in a split (**ctrl+%**) the smaller scrolling region will behave oddly by not scrolling within the scroll region and printing lines on top of lines. The large "non-scrolled" scroll region that the client maintains when not scrolling is not impacted by splits or anything like that.

I made this gif recording to help clarify the issue:
![scrolling-tmux-split](https://user-images.githubusercontent.com/164039/121155129-d19ea380-c847-11eb-8182-cf3040ff6e2b.gif)

The way the mud client prints new lines to output is as follows (same for regular mode and scrolled mode):
- Go to outputline, col 1
- Print `\n`
- Print the output line

I tested replacing the `print \n` step with the escape sequence for scroll-up (1) but it did not change this behavior.
When coding I ran a split within vim (term) inside tmux and then it does work as intended but perhaps that's just vim taking over the rendering.

### Required information
* tmux version (`tmux -V`): **tmux 3.2**
* Platform (`uname -sp`): **Linux unknown** (archlinux, freshly updated) (gnome-terminal)
* $TERM inside and outside of tmux (`echo $TERM`):
    * xterm-256color (outside)
    * tmux-256color (inside)
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-924143.log](https://github.com/tmux/tmux/files/6614993/tmux-client-924143.log)
[tmux-out-924145.log](https://github.com/tmux/tmux/files/6614994/tmux-out-924145.log)
[tmux-server-924145.log](https://github.com/tmux/tmux/files/6614995/tmux-server-924145.log)

**Comment by nicm** [comment]
If you press `C-b r` after reproducing the problem, does tmux redraw the terminal correctly or does nothing change?

**Comment by nicm** [comment]
I cannot make this happen with a simple version of what you are doing:
~~~~
printf "\033[34;42r\033[42;1H\nabcdef\033[42;1H\n$(date)\033[H"
~~~~
Can you try this and see if it still happens for you? Or modify it to reproduce?

**Comment by LiquidityC** [comment]
I can confirm that `C-b r` does redraw correctly, I should have thought to try that earlier.

**Comment by nicm** [comment]
What terminal are you using? Does this still happen in tmux when running in xterm?

When you split horizontally, tmux can no longer use the scroll region except on terminals with margins so it has to redraw all or some of the pane.

**Comment by LiquidityC** [comment]
gnome-terminal

I downloaded xterm and there it does work as intended. The scrolling at least. I don't have a good xterm config.

I'm not aware of what margins are. Do they allow tmux to offload the scroll region rendering onto the terminal even in horizontal splits?

**Comment by nicm** [comment]
DEC margins allow the scroll region to only apply to some columns. xterm does support margins, can you try it in another terminal that does not like maybe rxvt (not another VTE terminal)?

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/6616334/x.diff.txt)

**Comment by LiquidityC** [comment]
Let me test it. I'll get back to you. Need to setup your build first :smile:

**Comment by LiquidityC** [comment]
Tested the patch. Sorry. Didn't help.

**Comment by nicm** [comment]
OK apply this instead please and reproduce and show me the server log. Please type something unique like "abcdef" to reproduce so I can find it in the log file. 
[x.diff.txt](https://github.com/tmux/tmux/files/6623348/x.diff.txt)

**Comment by LiquidityC** [comment]
Ok, so this is embarrassing but when I tested this diff it worked. Since the only difference between the previous and this diff was the logline I retested the previous one and made sure I did everything right. Eg.

```bash
tmux kill-server
./tmux
```
and then it worked. So yes. Your original patch worked. Sorry for the confusion and obviously sloppy testing.

**Comment by nicm** [comment]
OK great, I have applied this now, let me know if you see any further problems. Thanks!

**Comment by LiquidityC** [comment]
Thank you for excellent support. 😊
