### ISSUE TITLE
send-keys -T option to send to pane title

### ISSUE THREAD

**Issue by bhougland18** [tmux/tmux#2738]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.2
* Platform (`uname -sp`): Nixos 21.05
* $TERM inside and outside of tmux (`echo $TERM`): alacritty
* Logs from tmux (`tmux kill-server; tmux -vv new`).

I would like an option to use the send-keys command with a named pane instead of the index by using a -T flag.  For instance, if I use my editor (Kakoune) to start a repl session I am creating the named pane "repl".  However, the send-keys command doesn't have a -T option like the select-pane command, where I can use the title as a more reliable way to target a pane.  

Thank you!

**Comment by nicm** [comment]
-T sets the pane title not name. You could do this with a script, something like:
~~~~
p=$(tmux lsp -F '#{pane_title} #{pane_id}'|awk '/^title %/ {print $2}')
tmux send -t$p hello
~~~~

**Comment by bhougland18** [comment]
i appreciate the script, but would it be possible to add an option for this feature?

**Comment by nicm** [comment]
Maybe, pane titles are not a very reliable way of targetting panes.

**Comment by bhougland18** [comment]
I most cases I would agree with you, but when you are programmatically targeting a specific pane from another program I would argue it is more reliable.  Often times the other program is the one that is creating the pane in the first place, as is the case when I open a new pane so it can be used as a repl.  The initiation of pane creation is comming from another program, then it send commands (selected text) to the new pane (in this case a repl).  I currently use Kitty for this purpose because I can target a named pane (or window in it's case).  No matter what session I am in I always know that I am target a specific pane, whereas it could be index 1 in one session and index 3 in another, depending on the other panes I have open.

As a side note, I am blown away by how little issues are open on such a big project and the response time (especially when I am essentially just begging for an enhancement).  I do love Tmux and want to switch away from Kitty but this is the feature that prevents me from doing so.

**Comment by bhougland18** [comment]
Thank you!

**Comment by nicm** [comment]
Is this working OK for you?
