### ISSUE TITLE
copy-pipe unknown command

### ISSUE THREAD

**Issue by gbishop** [tmux/tmux#274]
I'm trying to get the selection piped into a command on MouseUp or Drag with

    bind-key -n MouseUp1Pane copy-pipe 'yank > {#pane_tty}'

but I'm getting copy-pipe unknown command when I attempt to define it. But I use copy-pipe in other bindings... Is it only defined in some contexts?

**Comment by nicm** [comment]
Yes that is wrong, it is only available for the copy mode key bindings.
