### ISSUE TITLE
feature: customize key bindings in mode-tree

### ISSUE THREAD

**Issue by qx-juilliard** [tmux/tmux#2742]
With my use case, I use the search function in the tree-view frequently, allowing me to navigate between sessions with ease.

As such, I would like to be able to configure custom key bindings in my `~/.tmux.conf` to facilitate my workflow.

After digging into the documentation and source code, I found that relevant functions have been hard-coded into the following section:

https://github.com/tmux/tmux/blob/c03b57465bdf850026b3a5c478a63ca62212720f/mode-tree.c#L1165

For now I guess I just have to edit the source code and recompile tmux myself. However, is it possible to add the functionality such that users can define key bindings that control behaviors in mode-tree, overriding the default ones?

**Comment by nicm** [comment]
You should be able to add keys by binding keys in the root table that check pane-mode.

**Comment by qx-juilliard** [comment]
> You should be able to add keys by binding keys in the root table that check pane-mode.

Cool! Problem solved ...

For future reference:

- #2201
- [How to change Tmux session list shortcuts?](https://stackoverflow.com/questions/61676573/how-to-change-tmux-session-list-shortcuts)

**Comment by nicm** [comment]
You can now change the shortcut keys (but not other keys) using `-K` , see https://github.com/tmux/tmux/wiki/Recipes#change-shortcut-keys-in-tree-mode.
