### ISSUE TITLE
terminal closed when adjust window tiling

### ISSUE THREAD

**Issue by lfishRhungry** [tmux/tmux#2745]
i can not be sure where the bug is.
when  i open tmux in alacritty, and use neovim. if tiling the window to left or right, the window will be closed with pressing any key after that.

i do not know whats wrong with that. this will not happen when i just use tmux or neovim. and this will not happen when i adjust window with other policy.

and my shortcut to tiling window left or right is meta+left or meta+right

**Comment by lfishRhungry** [comment]
> The alacritty window closes, or tmux detaches?

alacritty closes. and i  can attach my session after reopen alacritty

**Comment by nicm** [comment]
How do you normally run tmux? Do you start it with alacritty or do you open alacritty and then type "tmux attach"?

**Comment by lfishRhungry** [comment]
> How do you normally run tmux? Do you start it with alacritty or do you open alacritty and then type "tmux attach"?

i normally start and attach tmux in alacritty. i use tmux just in local.

**Comment by nicm** [comment]
If you start tmux yourself rather than having alacritty starting it, it sounds like alacritty itself is closing rather than tmux making it close. So this is probably an issue with alacritty or your WM, not with tmux.

**Comment by lfishRhungry** [comment]
> If you start tmux yourself rather than having alacritty starting it, it sounds like alacritty itself is closing rather than tmux making it close. So this is probably an issue with alacritty or your WM, not with tmux.

i actually start tmux in alacritty, this is my only terminal in my computer

**Comment by nicm** [comment]
I don't know what you mean. Do you configure alacritty to run tmux, or do you type `tmux ...` into alacritty?

**Comment by lfishRhungry** [comment]
> I don't know what you mean. Do you configure alacritty to run tmux, or do you type `tmux ...` into alacritty?

i type tmux to start tmux in alacritty.

**Comment by nicm** [comment]
I think this is an alacritty or WM problem.

**Comment by lfishRhungry** [comment]
> I think this is an alacritty or WM problem.

thanks.
i will check it again :)
