### ISSUE TITLE
vim status line will disappear while scroll down when run vim in tmux

### ISSUE THREAD

**Issue by ask-github** [tmux/tmux#2746]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* tmux next-3.3
* Platform (`uname -sp`).
* Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
* xterm
* Logs from tmux (`tmux kill-server; tmux -vv new`).
<img width="686" alt="1" src="https://user-images.githubusercontent.com/72971953/122150694-c58e9380-ce90-11eb-98c3-c1c4e215fe08.png">
<img width="818" alt="2" src="https://user-images.githubusercontent.com/72971953/122150702-caebde00-ce90-11eb-93a5-2e326d91fa08.png">

**Comment by krader1961** [comment]
You didn't say how to reproduce the problem. What do you mean by "scroll down"? What keys or mouse events did you generate? You also didn't provide the value of `$TERM` inside the tmux session (I'm assuming `xterm` is the value outside of tmux). Also, your first screen shot does not show the tmux status line while the second does show it. Why?

**Comment by ask-github** [comment]
sorry for miss
$TERM inside and outside of tmux (echo $TERM).
xterm both

reproduce step
1. tmux new -s one
2. vim filename to open file
3. use ctrl d in vim to scroll down in file(the file has many lines)
4. the status line of vim is partial disappear

the first screen shot is work fine vim status line run vim in normal console, not in tmux
the sec screen shot is indicate status line of vim is partial disappear

**Comment by krader1961** [comment]
It's wrong to set `TERM` to `xterm` inside a tmux session. You can sometimes get away with doing so but it can cause problems for non-trivial use cases. Such as your situation. Try setting it to `screen` or `screen-256colors` (better is `tmux` or `tmux-256colors` if your system has those terminfo definitions).

**Comment by ask-github** [comment]
i set TERM inside tmux, but still has this problem

#echo $TERM
screen-256color
#vim tmux-server-14150.log

**Comment by krader1961** [comment]
Nicm is probably going to ask you for the tmux client and server logs. I'll point out I can't reproduce your problem; i.e., Ctrl-D in Vim in a tmux session works fine for me. These types of problems are sometimes due to a bug the actual terminal you are using. Since it's unlikely you're using the original xterm program what terminal are you actually using? Also, can you reproduce if you start tmux (make sure no tmux server is running) without a *~/.tmux.conf* file?

**Comment by nicm** [comment]
What terminal are you using? Does this also happen in xterm?

**Comment by ask-github** [comment]
xshell

**Comment by ask-github** [comment]
but why vim is work fine outside of tmux?
term is win10 xshell 7
@nicm

**Comment by nicm** [comment]
Seems like a problem with the terminal if putty is OK. What is `TERM` set to outside tmux?

**Comment by ask-github** [comment]
$TERM inside and outside of tmux (echo $TERM).
xterm both

putty in win10 is work fine.

reproduce step
use win10 xshell to connect
1. create new centos vm
2. git clone tmux and compile, install
3. set .vimrc to
set laststatus=2
set statusline=%F%m%r,\ %Y,\ [%{&fileformat}],\ [%{getcwd()}],\ row=%l,\ col=%c%V,\ %p%%,\ [%{(&fenc==\"\")?&enc:&fenc}],\ ASCII=\%b,\ HEX=\%B
4. create new tmux with command tmux
5. use vim to open a many line file
6. ctrl d to scroll down of file

if set statusline=%F%m%r,\ %Y,\ [%{&fileformat}],\ [%{getcwd()}],\ [%{(&fenc==\"\")?&enc:&fenc}]
do not with long statusline. it also work fine.

but with long statusline, it is work fine in normal shell

so it maybe bug of vim, xshell, tmux. not sure

**Comment by nicm** [comment]
Does it still happen if you set TERM outside tmux to something basic like vt220?

**Comment by ask-github** [comment]
set TERM like vt220 outside tmux still has problem
thanks

**Comment by nicm** [comment]
Show me the tmux server log from reproducing with TERM=vt220 please.

**Comment by ask-github** [comment]
server log with TERM=vt220
[tmux-server-34784.log](https://github.com/tmux/tmux/files/6684374/tmux-server-34784.log)

**Comment by nicm** [comment]
What if you add this to .tmux.conf:
~~~~
set -as terminal-overrides '*:csr@'
~~~~
Then restart tmux (`tmux kill-server`). Does it fix the problem?

**Comment by ask-github** [comment]
it is work fine
what's the problem it is?

**Comment by nicm** [comment]
Seems like the terminal does not correctly support the scroll region, or their support is buggy.

**Comment by ask-github** [comment]
do you means it is the bug of xshell in win10?

**Comment by nicm** [comment]
That seems most likely yes.

**Comment by ask-github** [comment]
thanks very much
