### ISSUE TITLE
choose-tree: document support for %1

### ISSUE THREAD

**Issue by martinvonwittich** [tmux/tmux#2748]
### Issue description

As discussed in #2520:

`choose-tree` supports `%1`, just like `command-prompt` does. `%1` effectively does the same thing as `%%`, but can be expanded multiple times, ie. this here doesn't work because `%%` is only expanded once:

```
bind-key S choose-tree -Zs "move-window -t '%%'; switch-client -t '%%'"
```

But this does:

```
bind-key S choose-tree -Zs "move-window -t '%1'; switch-client -t '%1'"
```

`command-prompt` properly documents this feature in the manpage:

> Before the command is executed, the first occurrence of the string ‘%%’ and all occurrences of ‘%1’ are replaced by the response to the first prompt, all ‘%2’ are replaced with the response to the second prompt, and so on for further prompts.  Up to nine prompt responses may be replaced (‘%1’ to ‘%9’). ‘%%%’ is like ‘%%’ but any quotation marks are escaped.

But  `choose-tree` does not, it only says:

> After a session, window or pane is chosen, ‘%%’ is replaced by the target in template and the result executed as a command.  If template is not given, "switch-client -t '%%'" is used.

The support for `%1` should be documented for `choose-tree` too, because at least to @systemmonkey42 and me it wasn't obvious.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

	tmux 3.0a

* Platform (`uname -sp`).

	Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).

	xterm-256color
	screen

* Logs from tmux (`tmux kill-server; tmux -vv new`).

	I'll skip this because I don't think it is relevant to this issue.

**Comment by nicm** [comment]
Fixed, thanks.
