### ISSUE TITLE
[FEATURE REQUEST] - unbind all

### ISSUE THREAD

**Issue by reisraff** [tmux/tmux#2750]
### Unbind all

Since I am a common user I like to do things on my way. so I added a `unbind` for all the keys on my `.tmux.conf` and then I started to `bind` only the ones I want.

If there is a way to `unbind all` It would be awesome to me because I would reduce my `.tmux.conf` file from 282 lines to 66 lines.

[]s

**Comment by nicm** [comment]
`unbind -a`
