### ISSUE TITLE
There are 0 fzf history in the tmux pop-up.

### ISSUE THREAD

**Issue by nabezokodaikon** [tmux/tmux#2752]
### Required information

Please provide the following information:

* tmux version: 3.2a
* Platform: Darwin i386
* $TERM inside and outside of tmux: screen-256color

### Expected
The fzf history is displayed in the tmux pop-up.

I tried the following command.
```bash
$ tmux popup '$(history -r | fzf --layout=reverse --no-sort +m --query "$LBUFFER" --prompt="History > ")'
```
Then, the number of pop-up history was 0.
How can I get rid of 0 history?
<img width="963" alt="スクリーンショット 2021-06-18 22 12 57" src="https://user-images.githubusercontent.com/3197942/122566310-5d070880-d082-11eb-8266-82cbf894d7c5.png">

**Comment by nicm** [comment]
popup makes a new shell, how would it know the history of your previous shell?

**Comment by nicm** [comment]
You will need to write the history to a tmp file before you run tmux popup and then point fzf to that file.

**Comment by nabezokodaikon** [comment]
I've tried so far, but the line selected from the pop-up window is not returned.
Could you give me some more advice?
```bash
function select-history() {
  tmux popup 'LANG=C; BUFFER=$(cut -f2 -d";" ~/.zsh_history | fzf --layout=reverse --no-sort +m --query "$LBUFFER" --prompt="History > "); CURSOR=$#BUFFER'
}
zle -N select-history
bindkey '^f' select-history
```

**Comment by nicm** [comment]
How would it be returned? You will need to have fzf put it in a file and then use that from the shell that opened the popup.

**Comment by nabezokodaikon** [comment]
The list is displayed for the time being,
<img width="963" alt="スクリーンショット 2021-06-19 0 02 22" src="https://user-images.githubusercontent.com/3197942/122581237-cd695600-d091-11eb-93c6-57279d2c2be2.png">
After selecting an item, the pop-up will be blank.
<img width="961" alt="スクリーンショット 2021-06-19 0 02 36" src="https://user-images.githubusercontent.com/3197942/122581322-e3771680-d091-11eb-9775-40324d6110e0.png">

**Comment by nicm** [comment]
Right but I don't know what fzf is meant to do there, but tmux won't send any of its output back to the original shell, you will need to arrange that yourself. Use `popup -E` if you want tmux to close the popup when fzf exits.

Why don't you look at some of the existing scripts that use fzf for tmux?

**Comment by nabezokodaikon** [comment]
Solved.
I used `fzf-tmux` which is included in `fzf`.
```bash
function select-history() {
  BUFFER=$(history -n -r 1 | fzf-tmux -p --layout=reverse --no-sort +m --query "$LBUFFER" --prompt="History > ")
  CURSOR=$#BUFFER
}
zle -N select-history
bindkey '^f' select-history
```
