### ISSUE TITLE
No more complete syntax highlighting under fish shell on tmux/byobu after update 3.2-1 to 3.2_a-1

### ISSUE THREAD

**Issue by sulivanShu** [tmux/tmux#2753]
Hello, no more complete syntax highlighting under fish shell on tmux/byobu after update 3.2-1 to 3.2_a-1. No more light or dark blue colors, only some sorte of dark cyan color. Red, green and yellow seem OK.

```
fish -v
fish, version 3.2.2
byobu -v
byobu version 5.133
tmux 3.2a
uname -a # I'm on Pinebook pro
Linux manjaro 5.12.11-1-MANJARO-ARM #1 SMP Wed Jun 16 10:48:53 UTC 2021 aarch64 GNU/Linux
```

Fish’s syntax highlighting without tmux/byobu is OK.

Seem to be a tmux’s problem because no update for fish or byobu this time, only tmux. If not, we can send the bug report to fish or byobu programmers.

**Comment by nicm** [comment]
Logs?

**Comment by sulivanShu** [comment]
Excuse me, the problem changed after restarting the machine.

Now colors work well under X, with or without tmux.

On the other hand, they do not work well under tty with or without tmux. Also, the keyboard layout is bad under tty: cannot type characters like: é, è, à, €, although the keyboard is normally in azerty (fr layout).

Maybe it's not a tmux issue deep down.

[tmux-client-79047.log](https://github.com/tmux/tmux/files/6682322/tmux-client-79047.log)
[tmux-out-79049.log](https://github.com/tmux/tmux/files/6682323/tmux-out-79049.log)
[tmux-server-79049.log](https://github.com/tmux/tmux/files/6682324/tmux-server-79049.log)

**Comment by nicm** [comment]
What is TERM set to on the tty?

**Comment by sulivanShu** [comment]
```
echo $TERM
linux
```

This is an aarch64 plateform.

**Comment by sulivanShu** [comment]
In tmux:
```
echo $TERM
screen
```

out tmux:
```
echo $TERM
linux
```

**Comment by nicm** [comment]
I do not see you type any of é, è, à, € in this log. The Linux console only support the eight ANSI colours, so if you use the 256 colour palette it will either not work or be mapped to the closest ANSI colour.

**Comment by sulivanShu** [comment]
Thank you for your help, although it is not a tmux problem per se.

The point is that first my X terminal went to 8 colors after a Manjaro update, then the problem resolved itself after a reboot.

Then, the virtual consoles supported 256 colors before the update, then 8 colors after. It's a regression, but 8 colors is the default configuration for virtual consoles, so that's okay.

Regarding the accented characters in tty, this is strange.

`printf \u20AC # € character`

print ?^J out tmux and ?? in tmux.

Still, it's the correct unicode character, it's just that tty fails to display it correctly.

When I type, tty convert some charaters in others:

é -> {
è -> }
€ -> e
ç -> \
° -> ]
¨ -> <
£ -> >
...
However, the keyboard layout is azerty.

[tmux-out-668378.log](https://github.com/tmux/tmux/files/6688589/tmux-out-668378.log)

**Comment by nicm** [comment]
Seems like if the terminal (the Linux console) cannot handle UTF-8 then tmux is right not to display it.
