### ISSUE TITLE
Compare two tmux variables

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#2754]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.2a
* Platform (`uname -sp`). Linux unknown(Manjaro-Linux)
* $TERM inside and outside of tmux (`echo $TERM`).screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-log.zip](https://github.com/tmux/tmux/files/6690874/tmux-log.zip) (execute the command and then execute  the following tmux-display command and exit, get the log files)

I need to compare two tmux variables and do different actions based on the result, but I'm confused with the result:

```
>> tmux display -p '#{pane_width}x#{pane_height}; #{>=:#{pane_width},#{pane_height}}'
120x38; 0
```

The actual expression I use in my `~/.tmux.conf` is 
```
bind Enter if '#{>=:#{pane_width},#{pane_height}}' 'split-window -p 50 -h -c "#{pane_current_path}"' 'split-window -p 50 -c "#{pane_current_path}"'
```
compare `pane_width` and `pane_height`, if `pane_widht` is greater-or-euqal to `pane_height`, Split the current pane horizontally using `prefix+Enter`, otherwise split it vertically.

But it doesn't work as expected, you can see from the first command I posted. 

I check the issues and https://github.com/tmux/tmux/wiki/Formats#comparisons, I don't know why it doesn't work, ain't I using it correctly?
```
>> tmux set @foo 2
>> tmux set @bar 3
>> tmux display -p '#{<=:#{@foo},#{@bar}}'
1
>> tmux set @bar 1
>> tmux display -p '#{<=:#{@foo},#{@bar}}'
0
>>
```

---------------------------------------
**UPDATE:**
I managed to get what I need from https://www.reddit.com/r/tmux/comments/38k5ln/how_to_get_pane_size/crvzqyj?utm_source=share&utm_medium=web2x&context=3
```
bind Enter run "[[ $(($(tmux display -p '8*#{pane_width}-20*#{pane_height}'))) -lt 0 ]] && tmux splitw -v -c '#{pane_current_path}' || tmux splitw -h -c '#{pane_current_path}'"
```
And numbers 8 and 20 make the result more accurate than simple `pane_height` and `pane_width`(I was struggling with them). 

I still don't know why the original comparation-command doesn't work.

**Comment by krader1961** [comment]
```
>> tmux display -p '#{pane_width}x#{pane_height}; #{>=:#{pane_width},#{pane_height}}'
120x38; 0
```

From the man page:

> String comparisons may be expressed by prefixing two comma-separated alternatives by
> `==`, `!=`, `<`, `>`, `<=` or `>=` and a colon.

Note the "string" at the start of that sentence. Since "1" is less than "3" the result if zero (false) since you asked if "1" was equal to or greater than "3". See the next paragraph:

> Numeric operators may be performed by prefixing two comma-separated alternatives with
> an `e` and an operator.

For example,

```
> tmux display -p '#{pane_width}x#{pane_height}; #{>=:#{pane_width},#{pane_height}}'
200x39; 0
> tmux display -p '#{pane_width}x#{pane_height}; #{e|>=|:#{pane_width},#{pane_height}}'
200x39; 1
```

**Comment by krader1961** [comment]
Also, OMFG! :smile: The "answer" you found from an Internet search  is awful. Binding the `Enter` key to run an external shell command to test whether the current pane width is larger than its height, and do something depending on the answer, is gross and incredibly inefficient.

**Comment by c02y** [comment]
> Also, OMFG!  The "answer" you found from an Internet search is awful. Binding the `Enter` key to run an external shell command to test whether the current pane width is larger than its height, and do something depending on the answer, is gross and incredibly inefficient. Although, it might have made sense six years ago since that ancient version of tmux may not have supported the solution I documented in my previous comment.

Indeed, wrapping `tmux` inside `~/.tmux.conf` is not recommended.

Thank you.
Here is the final version if anyone is interested:
```
bind Enter if -F '#{e|>=|:#{e|*|:8,#{pane_width}},#{e|*|:20,#{pane_height}}}' 'split-window -p 50 -h -c "#{pane_current_path}"' 'split-window -p 50 -c "#{pane_current_path}"'
```
