### ISSUE TITLE
Underscore problem in session names in VSCode terminals

### ISSUE THREAD

**Issue by canertol** [tmux/tmux#2756]
### Issue description

When I rename a tmux session that runs in the VSCode terminal, underscores are invisible in the session name.
![Screenshot from 2021-06-22 10-08-38](https://user-images.githubusercontent.com/36196040/122940100-2bbc6000-d342-11eb-9c27-868c10cb0629.png)
**VSCode information:**
* Version: 1.57.1
* Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
* Date: 2021-06-17T13:26:56.255Z
* Electron: 12.0.7
* Chrome: 89.0.4389.128
* Node.js: 14.16.0
* V8: 8.9.255.25-electron.0
* OS: Linux x64 5.8.0-55-generic

**tmux information**
* tmux version (`tmux -V`).
**tmux 3.0a**
* Platform (`uname -sp`).
 **Linux x86_64**
* $TERM inside and outside of tmux (`echo $TERM`).
  **outside: xterm-256color
  inside: screen**
* Log files
[tmux-client-34911.log](https://github.com/tmux/tmux/files/6694885/tmux-client-34911.log)
[tmux-out-34913.log](https://github.com/tmux/tmux/files/6694886/tmux-out-34913.log)
[tmux-server-34913.log](https://github.com/tmux/tmux/files/6694887/tmux-server-34913.log)

**Comment by nicm** [comment]
Looks like it is drawing the underscores outside the background of the cell, so if the text colour is black and the background around the cell is also black, then it will be invisible. You need to report this to the terminal developers.

**Comment by canertol** [comment]
Ok, thank you!
