### ISSUE TITLE
Ctrl-space (NUL) being treated as "0x0" in control mode using iTerm2

### ISSUE THREAD

**Issue by dfr** [tmux/tmux#2757]
### Issue description

When using 'tmux -CC' on iTerm2 version 3.4.8, when I press ctrl-space in the terminal, I expect a NUL character to be sent. Instead, the three characters '0', 'x', '0' are sent which makes applications that use this key (specifically emacs) unusable.

This issue seems to be specific to control mode - a non-control mode tmux passes the key-press through normally. The issue seems to be new in tmux-3.2 (and is present in 3.2a) and downgrading to tmux-3.1c restores the expected behaviour. 

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 3.2
* Platform (`uname -sp`). FreeBSD-13.0-RELEASE
* $TERM inside and outside of tmux (`echo $TERM`). outside xterm-256color, inside screen
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by dfr** [comment]
So far I only tested with 3.2a since this was super easy to do with the FreeBSD ports tree and I'm lazy. I'll pull a copy of master and build it manually to check.

**Comment by dfr** [comment]
Testing with master (b1a8c0fe022e99cffb0fb4f321740464f35bc6b9) doesn't have the issue.

**Comment by nicm** [comment]
OK good stuff.
