### ISSUE TITLE
Can't join empty name session using enter key

### ISSUE THREAD

**Issue by adgross** [tmux/tmux#2758]
### Issue description

0) Running tmux with `tmux -Ltest -f/dev/null new`
1) Create a new session (:new) and rename it to "" (empty string)
2) Join the first session (prefix+s, select it)
3) Now try to join the session with empty name using the enter key, tmux will fallback to your current session

- In the session list, using "x" to kill or :attach to join still works
- tmux attach from new clients are able to join the session too

- Related: When inside the empty name session using :attach from session list, notice that tmux fail to attach to another session using enter key the first time we try

### Required information

* tmux version (`tmux -V`): tmux 3.2a
* Platform (`uname -sp`): Linux unknown. archlinux x86_64
* $TERM inside and outside of tmux (`echo $TERM`):
	inside: screen
	outside: alacritty (Alacritty), xterm-kitty (Kitty) and xterm-256color (XFCE Terminal Emulator)

### Additional information

Testing in Ubuntu 20.04, that have tmux 3.0a, trying to rename the session to empty name, it fail with "Bad session name"

**Comment by nicm** [comment]
Do not give sessions an empty name.

**Comment by nicm** [comment]
This seems useless, so we may as well forbid it. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/6714634/x.diff.txt)

**Comment by adgross** [comment]
It works and don't allow to create a session with empty name.

Given the string is empty, instead of the error message "invalid session: ", don't you think it will be easier for the user to identify the cause with something like "invalid session **name**: " ?

Thanks for the fix. you can close this issue.

**Comment by nicm** [comment]
Applied now, thanks!
