### ISSUE TITLE
Sixel support

### ISSUE THREAD

**Issue by timsofteng** [tmux/tmux#2759]
Hello. I know tmux currently doesn't support sixel. Is it any way to implement it?

**Comment by nicm** [comment]
I did a bit of work on it and someone talked about helping (they were going to write some code to scale SIXELs properly which tmux needs), but they disappeared and I didn't continue it. IMO SIXEL is too slow to work in practice anyway for anything more than tiny images.

**Comment by timsofteng** [comment]
@nicm is any good alternative protocol exist to display images in terminal?

**Comment by nicm** [comment]
Not supported by tmux.

**Comment by pagerc** [comment]
I've been reviewing the old requests, and I liked the idea from https://github.com/tmux/tmux/issues/1613#issuecomment-562139529 where sixel graphics are output, but for the scroll-back buffer an asci-art equivalent is generated for the image.

Chafa seems like the new game in town for ascii-art generation that supports sixel output, if it supports sixel input too, there's some real promise.
https://hpjansson.org/blag/2021/01/18/chafa-1-6-0-wider/#comment-8989
