### ISSUE TITLE
[exited] automatically on termux

### ISSUE THREAD

**Issue by REXX-dev** [tmux/tmux#2760]
![Screenshot_20210629-004047_Termux.png](https://user-images.githubusercontent.com/79816772/123674413-2b592300-d874-11eb-8660-d9b1b28f2fec.png)

In my case i use Android 11, i have running some script on termux

every time i turn off the screen, it just keeps killing the process running on tmux itself

I have to turn of App background limiter on settings

**Comment by nicm** [comment]
tmux can't help you if something else is killing it...

**Comment by REXX-dev** [comment]
> tmux can't help you if something else is killing it...

I mean what cause case is it, why it exited automatically

**Comment by nicm** [comment]
Sounds like Android is killing it?
