### ISSUE TITLE
SHIFT+UP/DOWN produce same key code

### ISSUE THREAD

**Issue by saurakh** [tmux/tmux#2761]
[tmux-client-696222.log](https://github.com/tmux/tmux/files/6734012/tmux-client-696222.log)
[tmux-server-696224.log](https://github.com/tmux/tmux/files/6734013/tmux-server-696224.log)
1. Create tmux.conf with 'set -g default-terminal "tmux-256color"'
2. Create new session 'tmux new -s TEST'
3. Type 'cat' and press enter
4. Press shift+up then shift+down

result:
key presses produce the same output
```
% cat
^[[1;2A
^[[1;2A
```

If you repeat with CTRL key codes are correct
```
% cat
^[[1;5A
^[[1;5B
```

So right now you cant use shift+up/down keys because they are the same. 

* tmux 3.2a
* Arch Linux 5.12.12  x86_64
* $TERM inside = tmux-256color, outside = rxvt-256color

**Comment by nicm** [comment]
Logs?

**Comment by saurakh** [comment]
> Logs?
attached

**Comment by nicm** [comment]
tmux looks for `kind` and `kri` as well as the more modern `kUP` and `kDN`. Your terminfo entry has both but has `kind` and `kri` the opposite way round from normal.

Try this:
~~~~
set -as terminal-overrides 'rxvt*:kri@:kind@'

**Comment by saurakh** [comment]
This workaround worked, thank you.

I have the same behavior on fresh install of CentOS 7 with tmux-3.2-1
If I downgrade it to package from official repos(tmux-1.8-4) problem does not reproduce.

**Comment by saurakh** [comment]
It seems I'm confused how terminfo works. 
Tested on arch and el7.

With rxvt-unicode(9.26-2) if I change to xterm, it works:
```
% echo $TERM
rxvt-256color
% cat
^[[1;2A
^[[1;2A
```

```
% export TERM=xterm-256color
% echo $TERM
xterm-256color
% tmux new -s TEST
% cat
^[[1;2A
^[[1;2B
```

In gnome-terminal (3.40.2-1) it works with both rxvt* and xterm*
```
% echo $TERM
rxvt-256color
% tmux new -s TEST
 cat
^[[1;2A
^[[1;2B
```

**Comment by nicm** [comment]
xterm is correct for gnome-terminal so it works.

xterm is wrong for rxvt-unicode (it does not send the sequences it gives)
but tmux has the right ones builtin so it understands them anyway.

Same for rxvt in gnome-terminal.

**Comment by saurakh** [comment]
Checked package dependencies for urxvt. Found `rxvt-unicode-terminfo` which provided `rxvt-unicode-256color`.
Problem does not reproduce with empty 'tmux.conf '

I don't remember where I get the notion to use `rxvt-256color` provided by `ncurses`.
So it seems problem is resolved on my end, thank you for your time.

**Comment by nicm** [comment]
OK great.
