### ISSUE TITLE
Looks like iTerm2 is doing this:

### ISSUE THREAD

**Issue by lockheadone** [tmux/tmux#2762]
Looks like iTerm2 is doing this:
~~~~
1614793412.622728 control_read_callback: /dev/ttys038: resize-window -x 80 -y 50 -t @0
~~~~
@gnachman?

_Originally posted by @nicm in https://github.com/tmux/tmux/issues/2594#issuecomment-790314142_

**Comment by gnachman** [comment]
> Looks like iTerm2 is doing this:
> 
> ```
> 1614793412.622728 control_read_callback: /dev/ttys038: resize-window -x 80 -y 50 -t @0
> ```
> 
> @gnachman?
> 
> _Originally posted by @nicm in [#2594 (comment)](https://github.com/tmux/tmux/issues/2594#issuecomment-790314142)_

Nicholas said he was going to work on a change to tmux so I don't need to do this. I'm waiting on that.

**Comment by nicm** [comment]
I think he opened this issue accidentally.
