### ISSUE TITLE
Not setting buffer with setb if data starts with minus

### ISSUE THREAD

**Issue by aserowy** [tmux/tmux#2764]
### Issue description

Using setb is not working if the given data starts with a minus. The same behaviour for single and double quotes. The man page does not specify handling minuses. When i try to escape the minus, the \ is written into the buffer.

![image](https://user-images.githubusercontent.com/8199164/124219817-193de580-dafd-11eb-9e62-81d8938aad49.png)

It seems like tmux tries to use the data as argument:

```log
5199267.423910 cmd_unpack_argv: argv[0]=set-buffer
1625199267.423915 cmd_unpack_argv: argv[1]=- random
1625199267.423920 cmd_parse_from_arguments: argv[0]=set-buffer
1625199267.423924 cmd_parse_from_arguments: argv[1]=- random
1625199267.423929 cmd_parse_from_arguments: at 0: argv[0]=set-buffer
1625199267.423933 cmd_parse_from_arguments: at 0: argv[1]=- random
1625199267.423939 cmd_parse_build_commands: 0 set-buffer
1625199267.423944 cmd_parse_build_commands: argv[0]=set-buffer
1625199267.423948 cmd_parse_build_commands: argv[1]=- random
1625199267.423955 cmd_parse: set-buffer: argv[0]=set-buffer
1625199267.423959 cmd_parse: set-buffer: argv[1]=- random
1625199267.423968 cmdq_append </dev/pts/14>: [cmdq_error_callback/0x1e4a420]
1625199267.423974 cmdq_next <global>: empty
1625199267.423978 cmdq_next </dev/pts/3>: empty
1625199267.423983 cmdq_next </dev/pts/14>: enter
1625199267.423987 cmdq_next </dev/pts/14>: [cmdq_error_callback/0x1e4a420] (1), flags 0
1625199267.423992 cmdq_error: usage: set-buffer [-aw] [-b buffer-name] [-n new-buffer-name] [-t target-client] data
1625199267.423998 message: /dev/pts/14 message: usage: set-buffer [-aw] [-b buffer-name] [-n new-buffer-name] [-t target-client] data
1625199267.424006 sending message 303 to peer 0x1eac870 (12 bytes)
```

### Required information

Tmux runs on Linux 5.4.72-microsoft-standard-WSL2 (debian).

For versions, look in the picture above. The bug was produced in ```sh tmux -vv -Ltest -f/dev/null new```.

[tmux-out-31539.log](https://github.com/tmux/tmux/files/6752044/tmux-out-31539.log)
[tmux-server-31539.log](https://github.com/tmux/tmux/files/6752045/tmux-server-31539.log)
[tmux-client-31537.log](https://github.com/tmux/tmux/files/6752046/tmux-client-31537.log)

Kind regards and thx for your work!
Alexander

**Comment by nicm** [comment]
Use -- or use load-buffer instead.

**Comment by aserowy** [comment]
-- produces an error as well. How can I use load-buffer without tmp files?

**Comment by nicm** [comment]
Pipe the data to it, echo foo|tmux loadb -

**Comment by aserowy** [comment]
Good workaround for this issue! echo -n "-- asdfasd" | tmux loadb - had the same behaviour (if anyone stumbles across this).

**Comment by nicm** [comment]
Great stuff.
