### ISSUE TITLE
Extend `-S` option to `new-window`

### ISSUE THREAD

**Issue by qsmodo** [tmux/tmux#2766]
From 3.2:

```
* Add a -S flag to new-window to make it select the existing window if one
  with the given name already exists rather than failing with an error.
```

It would be great if that flag had that effect with `-t target-window` too, so that these nifty bindings could work (jump to a window if it exists, creating it if necessary):

```
bind-key 1 select-window -S -t 1
bind-key 2 select-window -S -t 2
bind-key 3 select-window -S -t 3
```

I'm assuming there is currently no (easy) way to do that. I have tried `new-window ... \; select-window ...`, but as documented the sequence is interrupted if a command fails, so no dice.

**Comment by nicm** [comment]
You can probably do something like `run "tmux selectw -t1 || tmux neww -t1"`.

**Comment by qsmodo** [comment]
Thank you, I consider that a solution. This can be closed if you don't find the `-S -t` proposal worth the trouble.

**Comment by nicm** [comment]
I have added to todo list so it may be done at some point. Thanks!
