### ISSUE TITLE
Allow transparency in both active and inactive panes while they have different background hues

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2767]
I like transparent terminals. Tmux works well till I want to do this: Set the background color of active and inactive panes be different hues (colors) while still keeping both of them transparent. So far I haven't come across any solution that lets both active and inactive panes to be different color while both being transparent.

Given I don't intend to set different transparency levels, all that is needed is inheriting the existing transparency at the time of loading tmux, and applying that transparency while color of panes are changed within tmux. Tmux already inherits transparency of terminal as of today, but does not maintain it if one changes color of active/inactive panes.

**Comment by nicm** [comment]
There is no mechanism for tmux to set different parts of the terminal to transparent.

**Comment by krader1961** [comment]
@reportaman, To expand on @nicm's reply I will point out that there is nothing in the ANSI X3.64 standard, or the extensions to that standard implemented by various terminals, that supports transparent backgrounds. If I am wrong about that please provide links to the relevant documents.

**Comment by reportaman** [comment]
@nicm Just to clarify, I am not asking for different transparency levels for different parts. I am asking tmux to not override transparency of the underlying terminal window when focused pane is colored separately from rest of the panes.

For instance when the following line is present in .tmux.conf:

```
tmux_conf_theme_focused_pane_fg="terminal"
tmux_conf_theme_focused_pane_bg="#192954"
```

the focussed pane loses the underlying terminal's transparency (while rest of the panes remain transparent).

@krader1961 Is there some kind of color blending in that standard? Maybe that could work... Am not a terminal expert :)

**Comment by nicm** [comment]
There is no way for tmux to set transparency for different parts of the terminal, either thr background is the default colour (which may be transparent) or it is a colour tmux specifies. If you want the latter to be transparent as well you need your terminal to do it, not tmux.

**Comment by reportaman** [comment]
Ok, is something like https://github.com/TaDaa/vimade possible? It works with transparent terminals too.

**Comment by nicm** [comment]
You can modify the default colours for a pane (`window-style`) but there is currently no way to apply an adjustment to all colours in a pane.

**Comment by reportaman** [comment]
@nicm iTerm2 has a setting "Keep background colors opaque", unchecking it and sliding the transparency bar applies transparency to all the background colors in terminal. In the following video, I have two tmux panes open next to each other, and tick tock the focus between them. As can be seen there is transparency of background while having different backgrounds in focussed and unfocussed windows. Also, given you mention "...no way to apply an adjustment to >>all colours<< in a pane.", I wonder if there was miscommunication. All one would need is ability to specify a single transparency value that applies to all pane's main background, while still maintaining different hues like we see in this video. I think I have same feature in other terminals like WezTerm...

https://user-images.githubusercontent.com/71736629/126857960-dad18692-61e5-49b4-843e-80fc8076d8ec.mp4

**Comment by nicm** [comment]
There is no way for tmux to specify transparency at all.

**Comment by reportaman** [comment]
@nicm @krader1961 The effect I wanted to achieve has become possible with recent Alactritty commit (https://github.com/alacritty/alacritty/commit/c24d7dfd0d2d8849f0398d7cb1a65d6562ee7a0d) using its settings: ``window.opacity`` (float number between 0.0-1.0), and ``colors.transparent_background_colors`` (boolean true/false). 

![Screen Shot 2021-08-22 at 11 08 40 PM](https://user-images.githubusercontent.com/71736629/130398626-72034e61-9f89-4ec1-ad6d-a1f20dee3a99.png)
