### ISSUE TITLE
Share options within group? or create group-scoped options

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2768]
While working on a PR for tmux-resurrect, I realized that it would be nice to have group-scoped options. Once set, the options will be visible from all member sessions of a group.

Is there a way to do that already? If not please consider adding this.

**Comment by nicm** [comment]
I don't think this is likely to happen, in the end my goal is to get rid of session groups in their current form entirely. This also seems like it would be very complicated to express and of limited use.

**Comment by reportaman** [comment]
@nicm Good to know. Btw how will the effect mentioned [here](https://stackoverflow.com/a/54653755/15087532) & [here](https://unix.stackexchange.com/questions/24274/attach-to-different-windows-in-session/24288#24288) be achieved:

> Where it may be useful? Depends on your workflow. For example this answer describes how this feature enables having different windows of the same session in different terminals.

**Comment by nicm** [comment]
Well, the idea would be that instead of having a copy of the session like with a session group, you would simply be able to attach an existing session but have an independent current window, like the way you can now have an independent active pane by attaching with `-factive-pane`.

**Comment by reportaman** [comment]
@nicm Ok cool. If your change is coming in near future, then I won't worry about an edit to a PR that required a corner case to iterate over all sessions in current (attached) group to find a variable that was set in one of them...

**Comment by nicm** [comment]
I don't know about soon but I don't want to add complex extra features to session groups in the meantime.

**Comment by reportaman** [comment]
Closing as groups will not be supported in future, and for now I am iterating over sessions in a group to find the value of a option that is not guaranteed to be in the focussed session of the group.
