### ISSUE TITLE
Documentation has ambiguity regarding show-option -t

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2769]
The documentation of ``show-options`` is a bit ambiguous. It asserts that ``-t `` is to be passed a target-pane. But when I pass a session name as target, it correctly returns session option. Does tmux guarantee this behavior will persist, and is it expected? If yes, then documentation should reflect that. What all can be passed as targets to ``-t``? Thanks :)

```
     show-options [-AgHpqsvw] [-t target-pane] [option]
                   (alias: show)
             Show the pane options (or a single option if option is provided) with -p, the window options with -w, the server options with -s, otherwise the session options.  If the option is not a
             user option, -w or -s may be unnecessary - tmux will infer the type from the option name, assuming -w for pane options.  Global session or window options are listed if -g is used.  -v
             shows only the option value, not the name.  If -q is set, no error will be returned if option is unset.  -H includes hooks (omitted by default).  -A includes options inherited from a
             parent set of options, such options are marked with an asterisk.
```

**Comment by nicm** [comment]
It seems pretty unambiguous to me:
>Show the pane options (or a single option if option is provided) with -p, the window options with -w, the server options with -s, otherwise the session options.

**Comment by reportaman** [comment]
@nicm I mean ``[-t target-pane]`` is ambiguous because passing target-session to -t like ``-t target-session`` also works.

**Comment by nicm** [comment]
Passing a session as a pane always works, tmux will use the session's current window's active pane if it needs a pane.

Technically we should say `target-session | target-window | target-pane` but what's the point? That is ugly and confusing and the text clearly says what flags you need to give for the different types of options. Not to mention this is something anyone unsure could try themselves in 30 seconds.

Command usage in the man page is not meant to be exhaustive, you have to read the text as well.

**Comment by nicm** [comment]
Really,`target-pane` is correct, because it is parsed as a pane. So if you do `tmux show -wt0`, you will get the window options for the window containing pane 0 (that is, the current window), not for window 0.

**Comment by nicm** [comment]
`tmux show -wt:0` will be window 0 whether it is `target-pane` or `target-window`. This is why if you are writing scripts you should use either unambiguous (fully defined) targets, or use pane, window and session IDs.

**Comment by reportaman** [comment]
@nicm 

> Not to mention this is something anyone unsure could try themselves in 30 seconds. Command usage in the man page is not meant to be exhaustive, you have to read the text as well.

IMHO, you will keep more such questions in future for this. The syntax section of commands should be more clear :) Perhaps a more innovative alternative to ``[target-session | target-window | target-pane]`` could be to say ``[target*]`` with a brief statement in description that target* can be any of session/window/pane.

> Really,target-pane is correct, because it is parsed as a pane. So if you do ``tmux show -wt0``, you will get the window options for the window containing pane 0 (that is, the current window), not for window 0.

That seems to contradict the first line of description "Show the pane options with -p, the window options with -w, the server options with -s, otherwise the session options."

From the above description ``tmux show -wt0`` would show window options for window 0 is what one would think. Because if 0 does mean pane, then the question is for which window? Similarly for session. A statement like ``tmux show-options -t blablabla`` where the session name is blablabla works, and if -t is indeed name of pane then why does it return session blablabla's option ;)

**Comment by nicm** [comment]
> That seems to contradict the first line of description "Show the pane options with -p, the window options with -w, the server options with -s, otherwise the session options."

It clearly says that if you give `-w` you will get window options. It does not say "window options with -w, unless you give a pane to -t", it just says "window options with -w". This cannot be more clear.

It is actually wrong to say `target*` because it is never a session target, it is always a pane target.

Do not use ambiguous targets unless you are happy for tmux to make its best guess based on what you give it and the type of target (`target-session`, `target-window` or `target-pane`).

**Comment by reportaman** [comment]
Let's take a real world use case that I just coded. In my [pending PR for tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect/pull/390/commits/21de0b35cdb90418887932b76d8015b433ad8a09), I needed to iterate over tmux sessions belonging to the group (if any) of attached session. I ended up doing the following, and it just worked. 

```
tmux show-options -qv -t home/Desktop/textfiles/projectx   @resurrect-dir
tmux show-options -qv -t home/Desktop/textfiles/projectx-1 @resurrect-dir
tmux show-options -qv -t home/Desktop/textfiles/projectx-2 @resurrect-dir
tmux show-options -qv -t home/Desktop/textfiles/projectx-3 @resurrect-dir
tmux show-options -qv -t home/Desktop/textfiles/projectx-4 @resurrect-dir
tmux show-options -qv -t home/Desktop/textfiles/projectx-5 @resurrect-dir
```

> Do not use ambiguous targets unless you are happy for tmux to make its best guess based on what you give it and the type of target (target-session, target-window or target-pane).

If this is an ambiguous/illegal pattern, then please consider adding support for such patterns so they are legal. If this is legal, then please don't call this ambiguous, and rather add the behavior to the document. Because a hidden feature ("tmux to make its best guess") cannot be permanent. Ideally in APIs such as these (and TMUX is very useful), there shouldn't be need for guess, i.e. the interface should be sufficient enough for user to query information without API having to guess.

**Comment by reportaman** [comment]
Perhaps tmux is doing this: If only session name is given, then first-pane/focussed-pane of first-window/focussed-window is inferred. If window name is given, then first-pane/focussed-pane of window is inferred.

**Comment by nicm** [comment]
This is not good practice, you are telling tmux to look for a pane target "home/Desktop/textfiles/projectx-1"  but in fact you want a session by that name. It works in this case because there is no available window or pane that can match.

If you want a session you should tell tmux this explicitly, in this case the easiest way to do that is to add a :, so `-t home/Desktop/textfiles/projectx-1:`.

See https://github.com/tmux/tmux/wiki/Advanced-Use#the-default-target and https://github.com/tmux/tmux/wiki/Advanced-Use#command-targets, notably:
>If neither : nor . appears in the target, tmux interprets it differently depending what the command needs. If the command wants target-pane then -t1 would be tried first as a pane and only as a window if there is no pane 1 found; if the command wants target-window then -t1 will only look for the window at index 1. For example note how the window changes from @1 to @8 after pane 1 is created:
> ...
>This behaviour is effective when tmux is used interactively but for scripting care must be taken that targets are correct. This is best done by noting whether a command wants a session, a window or a pane and by using IDs and the full target the command needs.

**Comment by reportaman** [comment]
@nicm Thanks a lot, please consider adding at least part of that document to ``man tmux``... Now it seems clear.

As a 🥇 to myself (just joking), then it is correct that ``[-t target*]`` can be any target depending on the pattern :)

**Comment by reportaman** [comment]
Also, I will fix my PR tomorrow :)

**Comment by nicm** [comment]
tmux always resolves targets into session, window and pane. `target-pane` just starts from the assumption that you are giving it a pane - it still ends up finding a session, window and pane. If the command then chooses to only use the session that is separate from how the target works which is always the same for any `target-pane`.
