### ISSUE TITLE
Stacking mode for panes under a window?

### ISSUE THREAD

**Issue by tmpm697** [tmux/tmux#2770]
info:

* tmux version: tmux next-3.3
* Platform: archlinux up-to-date
* $TERM inside and outside of tmux: xterm-256color (alacritty)

I share idea about stacking mode for panes [here](https://www.reddit.com/r/tmux/comments/ogq3s2/stack_mode_for_panes_in_tmux/h4lam41/) in reddit.

Currently I want to simulate i3wm/swaywm's stacking mode for its windows with panes under a window in tmux. I find it very useful when in middle of very busy panes under a window, quick switch to stacking mode and then bring back original state of panes when we're done with that mode.

I'm not gonna going to implement this feature request but I believe it's nice to have feature to tmux users in general so this issue to keep track in case.

**Comment by nicm** [comment]
This means nothing to me.

**Comment by tmpm697** [comment]
Idk it might useful. 

Workflow from i3wm already overlap some with tmux/screen.

**Comment by nicm** [comment]
You are not helping. What is i3wm? What does it do? What is stacking mode?

**Comment by tmpm697** [comment]
It's a layout of windows in a workspace/screen called "stacking". 

The layout similar as below:

Window1
Window2
Window3

Each window collapse into a bar with its title. When user select one of them, it will stretch out of other window to display its content. 

Imagine windows above like panes in tmux. And title like pane_title.

**Comment by nicm** [comment]
How is that different from tree mode which shows one window per line?

**Comment by tmpm697** [comment]
Tree mode is for windows and its tree mode window contains other info like sessions ..etc and it draws new window to display tree. 

This is for panes under a window. Should draw in current window. 

Most of time I need panes to visible as currently in my workflow, but there's still a case for stacking panes I think.

**Comment by nicm** [comment]
Tree mode shows panes also, or you could zoom the pane? I don't really understand what this does, show me a screenshot.

**Comment by tmpm697** [comment]
You can check this video with time frame for stacking mode in i3wm: https://youtu.be/j1I63wGcvU4?t=07m50s

**Comment by nicm** [comment]
This just looks like zoom with a pane title line.

**Comment by toddyamakawa** [comment]
You could probably just bind a key for that (warning, untested code):

```
bind-key p "select-pane -U \; resize-pane -Z"
bind-key n "select-pane -D \; resize-pane -Z"
```

I'm not sure if there's a way built-in to tmux to select the "next pane", but you could write a script to do that.

**Comment by nicm** [comment]
`select-pane` now has `-Z` which preserves the zoom, you should be able to do `select-pane -UZ`.
