### ISSUE TITLE
Session persistence on multi servers

### ISSUE THREAD

**Issue by Insomnia1437** [tmux/tmux#2771]
### Issue description

Say server A and server B both mount disk C using NFS, and my home directory locates at disk C. So I have two different tmux sessions on server A and B as the `/tmp` is server-specific.

As I want to use only one session on these servers, I think I should change the socket path to my home directory, like,
```
mkdir ~/.tmux/tmp
export TMUX_TMPDIR=~/.tmux/tmp
```
tmux works fine one server A, but when I try to attach to tmux on server B,
```
# on server B
$ tmux a
no sessions

$ tmux -S ~/.tmux/tmp/tmux-12681/default attach-session
no sessions

$ tmux ls
no server running on /my/home/directory/.tmux/tmp/tmux-12681/default

$ tmux display -pF '#{socket_path}'
/my/home/directory/.tmux/tmp/tmux-12681/default
```
And after trying to attach from server B, I also fail to attach from server A.

So, I am wondering whether tmux support this feature? If not, I may use only server A to attach tmux in the future...

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.1b
* Platform (`uname -sp`). Linux x86_64 (both CentOS 6.10)

**Comment by nicm** [comment]
You shouldn't use the same socket file on two different servers, when you start tmux on A it will delete the socket for the tmux on B and vice versa.

**Comment by Insomnia1437** [comment]
OK, I understand, thanks for your reassurance.
