### ISSUE TITLE
default-size behaviour change from 3.2 to 3.2a

### ISSUE THREAD

**Issue by utdemir** [tmux/tmux#2772]
### Issue description

I use tmux for testing a CLI app on different terminal sizes. I noticed that after upgrading to 3.2a from 3.2, the `-x` and `-y` parameters I pass to `tmux new-session -d` does not take effect.

The below command outputs are from terminals with the same size:

```
$ tmux -V
tmux 3.2a
$ rm bar; tmux new-session -d -x 20 -y 10 'tput cols > bar'; sleep 0.1; cat bar
174
```

```
$ tmux -V
tmux 3.2
$ rm bar; tmux new-session -d -x 20 -y 10 'tput cols > bar'; sleep 0.1; cat bar
20
```

Also, the default size has also changed, where `3.2` always spawns a detached window of width 80 regardless of the terminal size, however `3.2a` uses the width of the terminal I used to spawn it.

I couldn't see a relevant change at the "CHANGES FROM 3.2 TO 3.2a" section of the [CHANGELOG](https://raw.githubusercontent.com/tmux/tmux/3.2a/CHANGES).

Please let me know if I was relying on some undefined behaviour and if there is a better way to achieve what I want (run a command on a detached session of a certain size).

### Required information

```
$ uname -sp && echo $TERM
Linux unknown
xterm-kitty
```

I do not have a tmux configuration.

**Comment by utdemir** [comment]
I feel like this commit might be relevant: https://github.com/tmux/tmux/commit/4cf595a4023acfd9fce2e589f0d01de3e7b5eff7

**Comment by nicm** [comment]
Does this fix it?
~~~~
--- cmd-new-session.c   6 Jul 2021 08:18:38 -0000       1.137
+++ cmd-new-session.c   13 Jul 2021 08:57:33 -0000
@@ -280,7 +280,8 @@ cmd_new_session_exec(struct cmd *self, s
        memset(&sc, 0, sizeof sc);
        sc.item = item;
        sc.s = s;
-       sc.tc = c;
+       if (!detached)
+               sc.tc = c;

        sc.name = args_get(args, 'n');
        sc.argc = args->argc;

**Comment by utdemir** [comment]
> Does this fix it?

Yes, that does seem to fix it. Thank you for having a look!

**Comment by nicm** [comment]
Great, applied now, thanks!
