### ISSUE TITLE
set TERM=screen-256color by default

### ISSUE THREAD

**Issue by dilyanpalauzov** [tmux/tmux#2773]
tmux sets $TERM to `screen`.

https://github.com/drwetter/testssl.sh/issues/1928 suggests, that setting by default `TERM=screen-256color` is better.

**Comment by nicm** [comment]
I don't think it is time for this yet.

**Comment by nicm** [comment]
Although Apple and CentOS 6 do now have it, I wonder about Solaris though.

**Comment by nicm** [comment]
I think we will try this now and see how we get on.
