### ISSUE TITLE
Feature request: set-option pane-minimum-height

### ISSUE THREAD

**Issue by toddyamakawa** [tmux/tmux#2775]
### Feature description

```
tmux set-option -g pane-minimum-height <number>
```

Shells like `zsh` and `fish` don't handle having a height of 1 very well. Ideally there would be a way to make sure that even if I tried to resize a pane down to a height of 1, it will go to some minimum height, e.g. 2.

Relevant reddit thread: https://www.reddit.com/r/zsh/comments/nkrflc/how_do_i_disable_redraw_on_resize/

**Comment by nicm** [comment]
You could change `PANE_MINIMUM` in `tmux.h`. It used to be 2 because that is the minimum height of a scroll region but we support 1 now.

I'm not convinced about having an option. How do these shells handle it with other terminals? Almost every terminal lets you resize to 1 row high.

**Comment by toddyamakawa** [comment]
I'll try changing the macro when I get a chance. I don't actually know if there are any terminal emulators that support a minimum height. What I do know is that when I resize those to a height of 1, neither shell likes it (it doesn't matter whether it's tmux or or terminal)

**Comment by nicm** [comment]
I think the shells should be fixed to handle this properly rather than adding something to tmux that hardly anyone will use...

**Comment by toddyamakawa** [comment]
Makes sense. I haven't gotten a chance to test `PANE_MINIMUM` but that would just be a hack to workaround broken shells instead of actually fixing the shells.
