### ISSUE TITLE
Question/Bug: How to specify default background color for popup window?

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2776]
I am using Alacritty terminal with transparent background. My tmux window has different colors set for focussed and unfocused panes. So essentially everything within tmux has a solid background (no transparency). When I open a tmux popup window it still uses transparent background color from Alacritty. Is this a bug? or is there a way to specify color for popup windows?

Also, is <Ctrl-c> the only way to kill the popup window? When I type ``exit<CR>``, it does not close the popup window.

**Comment by nicm** [comment]
Popups get the default background colour same as a pane. The program in the popup should be able to set it. It is not a bad idea to have a flag to `display-popup` to set it (and `display-menu` for that matter).

You need `-E` if you want popups to close when the program exits.

**Comment by nicm** [comment]
OK we do not currently support setting the background and foreground colour with OSC inside popups because that state is attached to the pane. Although you could still emulate it for programs that do not set it themselves by doing something like:
~~~~
tmux popup "printf '\033[42m\033[2J'; exec $SHELL"

**Comment by nicm** [comment]
I have added this to the todo list (there are a number of other things we can improve about popups as well).

**Comment by reportaman** [comment]
@nicm Just to confirm... "Popups get the default background colour same as a pane. " is not true for now, right? I sense that from your following comment "OK we do not currently support..."  Because I don't see the popup inheriting color from pane it was called from. I rather see terminal's original color (before tmux was launched).

**Comment by nicm** [comment]
Default means the default colour, ie the terminal's default colour.

**Comment by reportaman** [comment]
@nicm Ah thanks for the clarification :)
