### ISSUE TITLE
Tmux kill server does not kill everything

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2778]
```
>> lsof -U | grep '^tmux'
tmux      99036 reportaman    9u  unix 0x570ea09cc94aadd1      0t0      /private/tmp/tmux-501/default
tmux      99036 reportaman   10u  unix 0x570ea09cc94ae611      0t0      /private/tmp/tmux-501/default
tmux      99036 reportaman   14u  unix 0x570ea09cc94acf69      0t0      ->0x570ea09cc94ad8c9
tmux      99851 reportaman    9u  unix 0x570ea09cc94aad09      0t0      ->0x570ea09cc94aadd1
```

I recently added this to my alacritty.yml config file.

```yaml
shell:
  program: /opt/homebrew/bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux new-session -s alacritty"
```

Then when I open alacritty & close it right away, and repeat the process 2-4 times, I see increase in number of entries returned by ``lsof -U`` than I had seen the first time I opened alacritty.

The behavior of ``>>tmux kill-server`` also changes. If I had opened alacritty only once, running ``>>tmux kill-server`` kills server and closes the window. But after two ``/private/tmp/tmux-501/default`` entries appear, running ``>>tmux kill-server`` seems to kill one of the ``/private/tmp/tmux-501/default``, and tmux session (with same name) continues to exist. All the while, there seems to be only one session visible in session list loaded by pressing ``<tmux_prefix>s``.

I got this alacritty-tmux recipe from https://github.com/alacritty/alacritty/issues/2956.

**Comment by nicm** [comment]
Am I meant to guess your tmux version? What does `pgrep -f tmux` show? Does this still happen if you try without a .tmux.conf?

**Comment by reportaman** [comment]
@nicm 

```
>> tmux -V
tmux 3.2
```

Here's what pgrep -lf tmux shows at various points of time:

1. After opening Alacritty first time:
```
❯ pgrep -lf tmux
4881 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
5674 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
6117 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
6703 tmux new-session -s alacritty
7099 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
7148 tmux new-session -s alacritty
7540 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
```

2. After closing and reopening Alacritty 2-3 more times:
```
❯ pgrep -lf tmux
5674 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
6117 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
7099 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
7148 tmux new-session -s alacritty
7540 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
```

3. After performing tmux-killserver from within Alacritty's running tmux for first time (window doesn't close, am returned to another session of same name apparently?)
```
❯ pgrep -lf tmux
7099 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
7540 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
8066 tmux new-session -s alacritty
8119 tmux new-session -s alacritty
8541 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
```

4. After performing tmux-killserver second time (this time window quits):
```
❯ pgrep -lf tmux
7099 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
7540 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
8541 sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
```

Haven't tried without .tmux.conf, can try that later...

**Comment by nicm** [comment]
If you wait 60 seconds for all the sleeps in your scripts to return, do these processes disappear?

**Comment by reportaman** [comment]
@nicm Not sure what that means, I am new to shell scripting. I don't know where this: ``sh -s _uptime; sleep 60;`` is coming from, and what you want me to try.

**Comment by nicm** [comment]
They are something @gpakosz's script is running. I mean after you do kill-server, wait for 60 seconds and see if the scripts exit after that.

**Comment by gpakosz** [comment]
They will exit

**Comment by gpakosz** [comment]
Maybe I should trap `SIGHUP` as well

**Comment by reportaman** [comment]
@gpakosz: No, I waited for a 2-3 minutes, one of them lasted till I did tmux kill-server.

**Comment by gpakosz** [comment]
They do exit.

That being said, I think I should trap `EXIT` and not `TERM`, this way the background jobs will exit immediately upon `kill-server`/`SIGTERM`.

**Comment by reportaman** [comment]
@gpakosz Btw, in my further testing, these running processes also interfere with tmux-resurrect in a way that one needs to enter a key or two before being able to actually type after restoring tmux-resurrect (as if user manually pressed escape or double escape). This behavior is highly dependent on the pane number and  programs that launch in the panes. If I make sure to kill all ``.tmux`` processes before doing tmux-resurrect, it doesn't have that problem.
