### ISSUE TITLE
Feature request: add a function similar to navi cheat sheet

### ISSUE THREAD

**Issue by fengdaolong** [tmux/tmux#2779]
Anyone who has used [navi](https://github.com/denisidoro/navi) knows that the cheat sheet function of navi is very convenient and easy to use. It can easily enter the commands collected by itself into the console through shortcut keys, and it can also interactively enter every parameter of the executed command.
But navi has a disadvantage, it can only be used in the local shell, when I enter the interactive command console (for example, I enter gdb to enter the console), or when I connect to other machines via ssh, I will no longer be able to use it navi.

Tmux is my indispensable tool. I very much hope to implement navi-like cheat sheet functions in tmux. Because tmux has inherent advantages, it is a framework, all programs opened by tmux are in this framework. Tmux can use its own The shortcut keys to search and call the cheat sheet, and then send commands to the console in its window, so it can overcome the shortcomings of navi. Interactive consoles such as gdb, ssh, mysql, python, radare can be opened through tmux and sent to them the commands in the cheat sheet.

For the cheat sheet function, I hope tmux can achieve the following functions in the early stage:
* Ability to customize the cheat sheet and be compatible with navi syntax;
* Use a shortcut key to quickly search the content in the cheat sheet like navi;

what do you think about this?

**Comment by nicm** [comment]
Not really sure what you are suggesting. Maybe it would be easiest to modify navi to run in a tmux popup and understand how to open tmux panes and send keys to them?

**Comment by fengdaolong** [comment]
Maybe you said this way is the easiest, but the combination of tmux and navi is always not so good.
I think it would be better if tmux natively supports its own cheat sheet function, the cheat sheet is a necessary efficiency improvement tool for people who often use the console. The powerful function of tmux adds a cheat sheet function, which is simply even more powerful.

**Comment by nicm** [comment]
I don't think this is something tmux should support natively, but you could write it as a script that used tmux commands to control tmux.

**Comment by fengdaolong** [comment]
The function of tmux to increase the cheat sheet is just my personal suggestion, for reference and discussion only, it doesn't matter if you don't accept it.

I want to ask, is there any way for tmux to customize shortcut keys to execute custom scripts? I want to try how to call navi through tmux.

**Comment by nicm** [comment]
Yes you can use run-shell or display-popup.

**Comment by fengdaolong** [comment]
How to send the content specified in the pop-up window to the current window, can you give an example?

For example, use the `display-popup` command to pop up a window in the current window, enter the `echo 'ls'` command in the popup window, and then return the output result `ls` to the current window?

**Comment by nicm** [comment]
You will need to use a temporary file, you can use the `wait-for` command to have the caller wait for the popup.

**Comment by fengdaolong** [comment]
Is there a more elegant way of not using temporary files? Or can tmux be improved later to achieve such a function?

**Comment by nicm** [comment]
Do something like:
~~~~
X=$(mktemp)
tmux popup -E "sleep 1; echo foo >$X; tmux wait -S $X"
tmux wait "$X"
cat $X
rm -f $X
~~~~

**Comment by fengdaolong** [comment]
Thank you! 
Inspired by you, I initially realized the combination of tmux and navi. I can use the "prefix + g" shortcut to satisfy various interactive console operations. But about the role of tmux's various parameters, (for example: tmux display-popup -E) I still don't know.



~/.tmux.conf
```
bind-key g run-shell '~/.tmux/tmux-navi.sh'
```


~/.tmux/tmux-navi.sh
```
#!/usr/bin/env bash

X=/tmp/navi.tmp
tmux display-popup -d $(pwd) -w 90% -h 90% -E "navi --print >$X; tmux wait-for -S $X;"
tmux wait-for "$X"
tmux send-keys "$(cat $X)"
rm -f $X
```

**Comment by fengdaolong** [comment]
I saw the description of each option of tmux in the help manual.
tmux only needs to do its own dedicated functions, let other programs do the cheat sheet functions, and the problem can be closed.

**Comment by fengdaolong** [comment]
I have seen the description of each option of tmux in the help manual.
tmux only needs to do its own dedicated functions, let other programs do the cheat sheet functions, and the problem can be closed.
