### ISSUE TITLE
error compiling when using configure option --enable-static

### ISSUE THREAD

**Issue by tessus** [tmux/tmux#278]
When I configure tmux with the option `--enable-static`, I get the following error when compiling:

```
gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"2.2\" -DPACKAGE_STRING=\"tmux\ 2.2\" -DPACKAGE_BUGREPORT$
\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"2.2\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLI$
_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_CURSES_H$
1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NCURSES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAV$
_SYS_DIR_H=1 -DHAVE_TERM_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_SYSCONF=1 -DHAVE_CFMAKERAW=1 -DHAVE_CFMAKERAW=1 -DHAVE_BSD_TYPES=$
 -DHAVE_PROC_PID=1  -I.   -I/home/tessus/work/tmux-static/local/include -DTMUX_CONF="\"/etc/tmux.conf\"" -DDEBUG -iquote.    -I/hom$
/tessus/work/tmux-static/local/include -I/home/tessus/work/tmux-static/local/include/ncurses -D_GNU_SOURCE -std=gnu99 -O2 -g -Wno-l$
ng-long -Wall -W -Wnested-externs -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshad$
w -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign $
Wno-attributes   -MT arguments.o -MD -MP -MF $depbase.Tpo -c -o arguments.o arguments.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from tmux.h:37:0,
                 from arguments.c:25:
compat.h:203:7: error: expected identifier or ‘(’ before ‘__extension__’
 char  *strsep(char **, const char *);
       ^
In file included from tmux.h:37:0,
                 from arguments.c:25:
compat.h:203:653: error: expected identifier or ‘(’ before ‘)’ token
 char  *strsep(char **, const char *);




                                                                                                                             ^
make: *** [arguments.o] Error 1
```

I'm using git master (ca29dc9abc5c90da1a56d06ecb692b35a3766bc0).

Please note that I did not have this problem with 2.1 on Linux, so I checked the commits since then and found the culprit:

After reverting commit 92f187d1c2d84322860dc595da604260999a52f0 everything works perfectly.
Any idea what is going on here?

Also, I sent 3 emails to tmux-users@googlegroups.com, but they never showed up in googlegroups.

**Comment by ThomasAdam** [comment]
Works fine for me.  What version of pkg-config et al., do you have?

**Comment by tessus** [comment]
```
$ pkg-config --version
0.28

$ rpm -qa |grep auto
automake-1.13.4-6.fc20.noarch
autoconf-2.69-15.fc20.noarch
```
But I really don't understand what this has to do with my problem. If I remove the 2 lines added by 92f187d, everything works just fine.
So for whatever reason you added the 2 lines, this change had an adverse effect for me.

Also, why would I need pkg-config, when I point to the 2 dependencies (libevent, ncurses) manually:
```
BASEDIR=${HOME}/work/tmux-static
TMUXTARGET=${BASEDIR}/local
./configure --prefix=$TMUXTARGET --enable-static CFLAGS="-I${TMUXTARGET}/include -I${TMUXTARGET}/include/ncurses" LDFLAGS="-L${TMUXTARGET}/lib -L${TMUXTARGET}/include -L${TMUXTARGET}/include/ncurses" LIBEVENT_CFLAGS="-I${TMUXTARGET}/include" LIBEVENT_LIBS="-L${TMUXTARGET}/lib -levent"
```

**Comment by nicm** [comment]
Full config.log and build output please.

**Comment by tessus** [comment]
Here's the [config.log](http://pastebin.com/8DAHDYuu) (link valid for 1 week).

Here's the make output:

```
depbase=`echo alerts.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"2.2\" -DPACKAGE_STRING=\"tmux\ 2.2\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"2.2\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_CURSES_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NCURSES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_TERM_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_SYSCONF=1 -DHAVE_CFMAKERAW=1 -DHAVE_CFMAKERAW=1 -DHAVE_BSD_TYPES=1 -DHAVE_PROC_PID=1  -I.   -I/home/tessus/work/tmux-static/local/include -DTMUX_CONF="\"/etc/tmux.conf\"" -DDEBUG -iquote.    -I/home/tessus/work/tmux-static/local/include -I/home/tessus/work/tmux-static/local/include/ncurses -D_GNU_SOURCE -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wnested-externs -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes   -MT alerts.o -MD -MP -MF $depbase.Tpo -c -o alerts.o alerts.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo arguments.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"2.2\" -DPACKAGE_STRING=\"tmux\ 2.2\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"2.2\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_CURSES_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NCURSES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_TERM_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_SYSCONF=1 -DHAVE_CFMAKERAW=1 -DHAVE_CFMAKERAW=1 -DHAVE_BSD_TYPES=1 -DHAVE_PROC_PID=1  -I.   -I/home/tessus/work/tmux-static/local/include -DTMUX_CONF="\"/etc/tmux.conf\"" -DDEBUG -iquote.    -I/home/tessus/work/tmux-static/local/include -I/home/tessus/work/tmux-static/local/include/ncurses -D_GNU_SOURCE -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wnested-externs -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes   -MT arguments.o -MD -MP -MF $depbase.Tpo -c -o arguments.o arguments.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from tmux.h:37:0,
                 from arguments.c:25:
compat.h:203:7: error: expected identifier or ‘(’ before ‘__extension__’
 char  *strsep(char **, const char *);
       ^
In file included from tmux.h:37:0,
                 from arguments.c:25:
compat.h:203:653: error: expected identifier or ‘(’ before ‘)’ token
 char  *strsep(char **, const char *);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^
make: *** [arguments.o] Error 1
```

**Comment by nicm** [comment]
We started using pkg-config for ncurses as well as libevent a while ago
and the change you mention is needed for static builds.

Did you try adding LIBNCURSES_CFLAGS/LIBNCURSES_LIBS like you have
LIBEVENT_CFLAGS/LIBEVENT_LIBS?

**Comment by tessus** [comment]
No, I haven't. But the change I mentioned is not needed for static builds, otherwise I would get an error. But I get the error because of it. Do you understand what I am saying?
Without the required change - no error / everything's fine.
With the required change - error occurs.

**Comment by nicm** [comment]
It is required for static builds with pkg-config...

**Comment by tessus** [comment]
Ok, I have added the following flags to the configure line: `LIBNCURSES_CFLAGS="-I${TMUXTARGET}/include" LIBNCURSES_LIBS="-L${TMUXTARGET}/lib -lncurses"`. 
This seems to fix the problem. But I still don't understand why I need this, because I have `pkg-config` installed. Maybe I have to change the `PKG_CONFIG_PATH`. In that case I shouldn't need any options in the configure line at all.

**Comment by nicm** [comment]
You can do one of several things:

- Don't set any CFLAGS or LIBS or other environment variables and just
  use pkg-config with the system libraries.

- Set LIBNCURSES_* and LIBEVENT_* to point pkg-config to your local
  installs.

- Set PKG_CONFIG_PATH to point pkg-config path to the *.pc files for
  your local libevent and ncurses installs.

- Get rid of pkg-config entirely, or try to tell configure not to use it
  somehow and just use basic CFLAGS and LIBS for both ncurses and
  libevent.

What won't (apparently) work on your system is setting LIBEVENT_* to use
your local libevent, but not setting LIBNCURSES_*, so pkg-config thinks
you want to use the system ncurses.

**Comment by tessus** [comment]
I tried all your test cases:

> - Don't set any CFLAGS or LIBS or other environment variables and just use pkg-config with the system libraries. 

Does not work. Error.

> - Set LIBNCURSES_* and LIBEVENT_* to point pkg-config to your local installs. 

Does work.

> - Set PKG_CONFIG_PATH to point pkg-config path to the *.pc files for your local libevent and ncurses installs. 

Does not work. Error.

> - Get rid of pkg-config entirely, or try to tell configure not to use it somehow and just use basic CFLAGS and LIBS for both ncurses and libevent.

Not sure how to do that.

The only way a static compile works is as follows:

`./configure --prefix=$TMUXTARGET --enable-static CFLAGS="-I${TMUXTARGET}/include -I${TMUXTARGET}/include/ncurses" LDFLAGS="-L${TMUXTARGET}/lib -L${TMUXTARGET}/include -L${TMUXTARGET}/include/ncurses" LIBEVENT_CFLAGS="-I${TMUXTARGET}/include" LIBEVENT_LIBS="-L${TMUXTARGET}/lib -levent" LIBNCURSES_CFLAGS="-I${TMUXTARGET}/include" LIBNCURSES_LIBS="-L${TMUXTARGET}/lib -lncurses"`

The following does not work (which is the correct pkg-config way and I guess the reason for your change):

```
export PKG_CONFIG_PATH="${TMUXTARGET}/lib/pkgconfig"
./configure --prefix=$TMUXTARGET --enable-static
```

**Comment by nicm** [comment]
Ok well when you figure out why sure let me know.

**Comment by tessus** [comment]
Hmm, I don't know how I would figure it out. It makes no sense. If `PKG_CONFIG_PATH` is set, no other option should be needed for the configure line. That's the only reason for pkg-config.

But, if I revert your "needed" change, the following works and pkg-config uses my libs.
```
export PKG_CONFIG_PATH="${TMUXTARGET}/lib/pkgconfig"
./configure --prefix=$TMUXTARGET --enable-static
```

This tells me that 92f187d is not needed and actually screws up the static build, unless you specify all the compile and linker options manuallly in the configure line, which in turn renders the use of pkg-config useless.

I'm sorry, but 92f187d does not fix static builds, it makes them fail (unless you specify everything manually).

**Comment by tessus** [comment]
Closing this issue is not ok, since it hasn't been resolved.

**Comment by nicm** [comment]
This change is needed. --static is necessary:

$ pkg-config --libs ncurses
-lncurses
$ pkg-config --libs --static ncurses
-lncurses -ltinfo

I am not going to revert it.

**Comment by tessus** [comment]
Have you even tried to compile a static binary?

**Comment by nicm** [comment]
Of course I did.

**Comment by tessus** [comment]
And for you this works?

```
export PKG_CONFIG_PATH=<PATH_TO_YOUR_PC_FILES>
./configure --enable-static
```

**Comment by nicm** [comment]
A static build with the system libraries and the system *.pc files fails. Because without --static, pkg-config will not add -ltinfo. This change was made for a reason.

I don't know why it fails for you. You need to figure out why pkg-config is not letting you override them without also overriding LDFLAGS and CFLAGS; or why your local *.pc files do not work.

**Comment by tessus** [comment]
This is very interesting.

I don't even have a tinfo library.

```
[tessus@atvie01s 0 ~/work/tmux-static/local/lib]$ ll
total 12016
-rw-r--r-- 1 tessus tessus 2212368 Oct 19 06:17 libevent.a
-rw-r--r-- 1 tessus tessus 1391760 Oct 19 06:17 libevent_core.a
-rwxr-xr-x 1 tessus tessus     917 Oct 19 06:17 libevent_core.la
-rw-r--r-- 1 tessus tessus  820680 Oct 19 06:17 libevent_extra.a
-rwxr-xr-x 1 tessus tessus     920 Oct 19 06:17 libevent_extra.la
-rwxr-xr-x 1 tessus tessus     902 Oct 19 06:17 libevent.la
-rw-r--r-- 1 tessus tessus  195988 Oct 19 06:17 libevent_openssl.a
-rwxr-xr-x 1 tessus tessus     941 Oct 19 06:17 libevent_openssl.la
-rw-r--r-- 1 tessus tessus   22006 Oct 19 06:17 libevent_pthreads.a
-rwxr-xr-x 1 tessus tessus     929 Oct 19 06:17 libevent_pthreads.la
-rw-r--r-- 1 tessus tessus  134086 Oct 19 06:21 libform.a
-rw-r--r-- 1 tessus tessus  906948 Oct 19 06:21 libform_g.a
-rw-r--r-- 1 tessus tessus   69934 Oct 19 06:21 libmenu.a
-rw-r--r-- 1 tessus tessus  502540 Oct 19 06:21 libmenu_g.a
-rw-r--r-- 1 tessus tessus  712794 Oct 19 06:21 libncurses.a
-rw-r--r-- 1 tessus tessus  160302 Oct 19 06:21 libncurses++.a
-rw-r--r-- 1 tessus tessus 4086096 Oct 19 06:21 libncurses_g.a
-rw-r--r-- 1 tessus tessus  700638 Oct 19 06:21 libncurses++_g.a
-rw-r--r-- 1 tessus tessus   28572 Oct 19 06:21 libpanel.a
-rw-r--r-- 1 tessus tessus  306472 Oct 19 06:21 libpanel_g.a
drwxrwxr-x 2 tessus tessus      93 Oct 19 06:17 pkgconfig
```
ncurses did not create a .pc file:

```
[tessus@atvie01s 0 ~/work/tmux-static/local/lib/pkgconfig]$ ll
total 12
-rw-r--r-- 1 tessus tessus 393 Oct 19 06:17 libevent_openssl.pc
-rw-r--r-- 1 tessus tessus 353 Oct 19 06:17 libevent.pc
-rw-r--r-- 1 tessus tessus 398 Oct 19 06:17 libevent_pthreads.pc
```

**Comment by nicm** [comment]
You may need to build ncurses with --enable-pc-files.

**Comment by tessus** [comment]
FYI:

libevent:

`./configure --prefix=$TMUXTARGET --disable-shared`

ncurses:

`./configure --prefix=$TMUXTARGET --with-default-terminfo-dir=/usr/share/terminfo --with-terminfo-dirs="/etc/terminfo:/lib/terminfo:/usr/share/terminfo"`

**Comment by tessus** [comment]
Aha, just saw your last message. Yes, I'll try that. This still won't create a tinfo library, will it?

**Comment by nicm** [comment]
No, I don't know how to make a separate libtinfo offhand, but some packagers break terminfo and ncurses into different libraries.

**Comment by nicm** [comment]
On those systems tinfo would be a dependency of ncurses so for dynamically linked binaries ld.so will pull in both if they are just linked against ncurses, but statically linked binaries need to be linked against both or the ld will not find the symbols in libtinfo.

**Comment by pbesedm** [comment]
$ yum search glibc
... ...
glibc-common.x86_64 : Common binaries and locale data for glibc
compat-glibc.x86_64 : Compatibility C library
compat-glibc-headers.x86_64 : Header files for development using standard C libraries.
glibc.i686 : The GNU libc libraries
glibc.x86_64 : The GNU libc libraries
glibc-devel.i686 : Object files for development using standard C libraries.
glibc-devel.x86_64 : Object files for development using standard C libraries.
glibc-headers.x86_64 : Header files for development using standard C libraries.
... ...
glibc-utils.x86_64 : Development utilities from GNU C library
... ...

Try to install these packets, it works for me.
BTW I don't use configure option --enable-static, but still get the identical errors.

**Comment by Janixman** [comment]
I was getting this same error on CentOS release 6.8 (Final).

I finally performed a

`yum install ncurses*`

which obtained the `-static` version, and the static build worked well.

**Comment by tessus** [comment]
@Janixman thanks for the info, but I was actually using my own statically compiled ncurses libraries.
as you can see in above output, I've been compiling libevent and ncurses alongside tmux.
