### ISSUE TITLE
tmux 3.2a no longer recognizes CSI u sequences

### ISSUE THREAD

**Issue by RealSaltyFish** [tmux/tmux#2780]
### Issue description

After upgrading to tmux 3.2a from 3.1c (I skipped 3.2), my vim keybindings `<S-CR>` (`^[[13;2u`) and `<C-CR>` (`^[[13;5u`) stopped working. I checked that `cat` shows nothing when I send these sequences inside tmux but these sequences can be correctly received outside tmux. I tried `set -s extended-keys on` and `set -as terminal-features 'xterm*:extkeys'` but it still does not work.

### Required information

* tmux version: `tmux 3.2a`
* Platform: `Darwin i386`
* $TERM inside and outside of tmux: `xterm-256color`(out) `screen-256color`(in)
* Logs from tmux:
[tmux-client-483.log](https://github.com/tmux/tmux/files/6822162/tmux-client-483.log)
[tmux-out-487.log](https://github.com/tmux/tmux/files/6822165/tmux-out-487.log)
[tmux-server-487.log](https://github.com/tmux/tmux/files/6822166/tmux-server-487.log)

**Comment by nicm** [comment]
The program inside tmux needs to enable extended keys if it wants them, or you need to set `extended-keys` to `always`.

**Comment by RealSaltyFish** [comment]
It works! Thanks.
