### ISSUE TITLE
Missing documentation: can't use -f without attaching

### ISSUE THREAD

**Issue by rambip** [tmux/tmux#2781]
I have a tmux.conf file .tmux-custom.conf like so: 
```
# this scripts start a tmux session silently, and set attach hooks.
new-session -d -s example

run "true > /tmp/tmux-var"
# other stuff ...
# set attach hook
```

I'm just looking for the right way to instantiate the server without attaching to a session.
If I do `tmux -f .tmux-custom.conf`, 2 sessions get created.
If I try to do `tmux -f .tmux-custom.conf exit` or something like that I get no sessions.
Why does `tmux -f ` asume I want to attach to a default session, and how can I change that ?

**Comment by nicm** [comment]
tmux(1):

>command [flags]
>    This specifies one of a set of commands used to control tmux, as described in the following sections. If no commands are specified, the new-session command is assumed.

You want `start-server` not `new-session`.

**Comment by rambip** [comment]
@nicm 
Is that a command I have to use to invoke tmux or in the configuration file ?

**Comment by rambip** [comment]
Could you give a quick example of a config starting a server with a hook, and which command to use to start this config file without attaching ?

**Comment by nicm** [comment]
~~~
echo 'new' >.tmux.conf.test
tmux kill-server
tmux -ftmux.conf.test start
tmux attach
~~~~

**Comment by rambip** [comment]
Thank's !
I'm surprised I wasn't able to find it in the documentation, but we can
close the issue I guess.

Le ven. 16 juil. 2021 10:16, Nicholas Marriott ***@***.***> a
écrit :
