### ISSUE TITLE
Repeated emoji modifier causing rendering problems in iTerm2

### ISSUE THREAD

**Issue by gnachman** [tmux/tmux#2784]
### Issue description

I received the following issue in iTerm2:
https://gitlab.com/gnachman/iterm2/-/issues/9807

My question is how tmux expects the terminal to handle this. I am puzzled why tmux sends [male][vs16] after backspacing, and whether this is intentional behavior or a bug.

Apple's unicode APIs consider `[shrug][zwj][male][male][vs16]` to be two grapheme clusters with a break between the `[male]` modifiers, so it's going to be tricky to make this work correctly.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 3.2a
* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`). xterm-256color, xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`). [Logs.zip](https://github.com/tmux/tmux/files/6842770/Logs.zip)

**Comment by nicm** [comment]
You could try the change in https://github.com/tmux/tmux/issues/1605#issuecomment-628597637 but I am not sure it will still apply.

**Comment by nicm** [comment]
This change [tmux-zwj.diff.txt](https://github.com/tmux/tmux/files/6848087/tmux-zwj.diff.txt) still works and (with utf8proc) causes tmux to correctly view this as a single character.

macOS libc doesn't seem to report the correct widths. utf8proc and OpenBSD libc both give:
~~~~
1626783122.120622 input_top_bit_set 4 '\360\237\244\267' (width 2)
1626783122.120743 input_top_bit_set 3 '\342\200\215' (width 0)
1626783122.120778 input_top_bit_set 3 '\342\231\202' (width 1)
1626783122.120967 input_top_bit_set 3 '\357\270\217' (width 0)
~~~~
But macOS libc reports:
~~~~
1626783295.798413 input_top_bit_set 4 '\360\237\244\267' (width 2)
1626783295.798481 input_top_bit_set 3 '\342\200\215' (width 1) [actually it reports an error but tmux assumes 1]
1626783295.798497 input_top_bit_set 3 '\342\231\202' (width 1)
1626783295.798655 input_top_bit_set 3 '\357\270\217' (width 1)
~~~~
I don't think this matters though, macOS libc wcwidth is probably a lost cause. I'm a bit tempted to refuse to build without utf8proc on macOS.

**Comment by gnachman** [comment]
utf8proc makes sense to me. iTerm2 uses its own width tables that are generally up to date and will play nicer with utf8proc than the ancient wcwidth in libc.

**Comment by nicm** [comment]
The person who reported this to you must have built tmux with utf8proc because with libc wcwidth you do see the symbol (it just doesn't stay in the right place if it needs to be redrawn).

This seems OK to me but if you can get them to test this diff then it would be good.

**Comment by kolbe** [comment]
Hi! I reported the iTerm2 issue. I'm using tmux from homebrew, and their "[formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/tmux.rb)" indeed suggests that they are building with utf8proc:

```
  def install
    system "sh", "autogen.sh" if build.head?

    args = %W[
      --disable-dependency-tracking
      --prefix=#{prefix}
      --sysconfdir=#{etc}
    ]

    args << "--enable-utf8proc" if MacOS.version >= :high_sierra

    ENV.append "LDFLAGS", "-lresolv"
    system "./configure", *args

    system "make", "install"

    pkgshare.install "example_tmux.conf"
    bash_completion.install resource("completion")
  end
```

I will try to build with the patch and will let you know the results!

**Comment by nicm** [comment]
I have applied this change now since it seems better than nothing. I have also changed so that tmux will refuse to build without utf8proc on macOS unless forced to. Thanks!
