### ISSUE TITLE
Feature/Question: Don't halt rendering tmux windows behind popup

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2786]
### Issue description

When I launch popup window, the rest of the windows in behind popup do not render. While the process is still running, and making progress, it can be even more useful if the progress is visible. For instance, while using some admin programs, if there is something I am keeping an eye on, I don't want the popup to cause me to miss that. This also seems to happen with other modes, like when entering a command. Though one is definitely expected to be in command mode for shorter duration. I intend to use popup window for writing notes in a scratchpad (by running a vim instance in it), and it would be make more sense to do that if tmux windows behind popup don't freeze.

### Required information

* tmux version (`tmux -V`): tmux 3.2
* Platform (`uname -sp`): Darwin arm
* terminfo (`$TERM`) xterm-256color outside, tmux-256color inside

**Comment by nicm** [comment]
This is on the todo list already but do not expect it in the near future.
