### ISSUE TITLE
Partial escape sequence? causes user to hit C-c before proceeding

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2787]
### Issue description

I think this started happening since I started using tmux pane coloring, though am not 100% confident. It also does not happen all the time so it's hard to reproduce & detail steps, though I'll do my best to explain.

At times when I do tmux attach or use tmux resurrect to resurrect new session (which I guess does tmux attach), and if cursor settles in a pane that is my login shell, then it behaves as if I entered some partial escape sequence, and shell is waiting for me to complete it. Most keys on the keyboard do not do anything, pressing ``a`` or ``C-c`` or ``Enter`` moves it out of unresponsiveness & I am able to then type command in shell as usual.

I suspect this has something to do with the way escape sequences are being emitted by tmux to color the focussed pane, though am not sure. Here are two screenshots:

1) Right after attaching tmux (arrow turned left indicates user is entering escape sequence):
![focussed coloring](https://user-images.githubusercontent.com/71736629/126557178-a54876e3-3b56-4295-a63b-488264eb1645.png)

2) This is how it normally looks (arrow turned right if user is not entering an escape sequence):
![coloring_focussed2](https://user-images.githubusercontent.com/71736629/126557187-62d3130e-97ef-4f28-9f0c-4543c7ccde6e.png)

As a sidenote, how can I translate those numbers to RGB-256?

Also, I observe this mostly when there are two panes: left and right, and right pane has neovim running, and focussed pane is the left pane which just has login shell. Though I haven't tested exhaustively.

### Relevant information

* tmux version (`tmux -V`): tmux 3.2
* Platform (`uname -sp`): Darwin arm
* terminfo (`$TERM`) xterm-256color outside, tmux-256color inside
* OS: macOS 11.4 BigSur
* `$SHELL`: /bin/zsh
* Fancy arrow behavior: https://github.com/zdharma/zinit

**Comment by nicm** [comment]
Are you saying this text is within the pane? That is, if you split the pane or do `C-b r` does it stay around?

**Comment by reportaman** [comment]
@nicm Will try that when I get the same behavior next time. Though what I remember trying is clicking mouse on another pane (nvim), working there, and clicking back on the login shell with this behavior (which always happens to be the last pane focussed after attaching). Doing that had not helped, and the reverse arrow stayed the way it did till I pressed either ``C-c`` or ``Enter``. Will report again the next time it happens again.

**Comment by reportaman** [comment]
@nicm Yes I confirm, it happened again and I both split the pane successfully, and entered ``<prefix>r``. The behavior remains the same, so yes the test is within the pane.

**Comment by nicm** [comment]
Then this is something being sent to tmux from within the pane, perhaps by your shell.

**Comment by nicm** [comment]
Or it could be a response from tmux to a query for the background colour. Check if your shell is sending a query.

**Comment by reportaman** [comment]
@nicm I just disabled zinit and retried, the problem remains, so at least it has nothing to do with zinit. I tried that because in a bug I had filed on wezterm, zinit was playing with ``stty``: https://github.com/wez/wezterm/issues/822#issuecomment-847969385

**Comment by reportaman** [comment]
Perhaps the source if tmux-resurrect's restore.sh: https://github.com/tmux-plugins/tmux-resurrect/blob/master/scripts/restore.sh

+ @bruno- As he might be interested.

**Comment by nicm** [comment]
I don't even know what zinit is.

**Comment by nicm** [comment]
I don't see anything in that script that queries the background colour.

**Comment by nicm** [comment]
If you reproduce and show tmux logs we can see what exactly is being sent.

**Comment by reportaman** [comment]
@nicm Its a zsh plugin manager that is fast, here's the entire description: https://github.com/zdharma/zinit#zinit. There are nice completion plugins and what not...

Regarding color: I set focussed, and unfocussed pane colors with https://github.com/gpakosz/.tmux's setup:

File ~/.tmux.conf.local:
```
tmux_conf_theme_highlight_focused_pane=true

# focused pane colours:
tmux_conf_theme_focused_pane_bg="terminal"
tmux_conf_theme_focused_pane_bg="#192954"
```

**Comment by reportaman** [comment]
@nicm How can I produce relevant logs for you?

**Comment by nicm** [comment]
https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md#how-do-i-get-logs-from-tmux

**Comment by reportaman** [comment]
@nicm Here we go:

[tmux-client-66071.log](https://github.com/tmux/tmux/files/6858978/tmux-client-66071.log)
[tmux-out-66073.log](https://github.com/tmux/tmux/files/6858979/tmux-out-66073.log)
[tmux-server-66073.log](https://github.com/tmux/tmux/files/6858980/tmux-server-66073.log)

Steps performed:
1) tmux kill-server
2) tmux -vv new
3) Launch a resurrect session

Then I typed ``w`` 8 times to check if it prints in the login shell in the left pane, and it didn't print anything as I expected.

**Comment by nicm** [comment]
Whatever is running in pane %2 is requesting the terminal background colour using the bypass escape sequence which means the result will go as key presses to whatever pane is the active pane when it is received:
~~~~
1626903696.036945 input_dcs_dispatch: "tmux;\033]11;?\a"
~~~~

**Comment by reportaman** [comment]
@nicm nvim is running in pane-2 and nothing in pane-1. Can anything be done about this?

**Comment by nicm** [comment]
Configure it not to do it, you will need to look at its docs or ask the neovim developers how.

**Comment by reportaman** [comment]
@nicm Filed a bug on neovim: https://github.com/neovim/neovim/issues/15148

**Comment by reportaman** [comment]
@nicm This does not happen in neovim version ``NVIM v0.6.0-dev+nightly-481-g6f48c018b``. When I reported the issue, I was using ``NVIM v0.5.0-dev+nightly-356-gb28d458f8``. Perhaps someone fixed it in between. Perhaps its safe to close this issue, unless you would like to keep it open for a day or two of more real life testing.
