### ISSUE TITLE
Feature request: support utf8 characters in tty display mode

### ISSUE THREAD

**Issue by fengdaolong** [tmux/tmux#2788]
Since the Linux kernel itself does not support unicode characters, utf8 characters cannot be displayed on the tty pure character console. The usual method is to use the `fbterm` tool to let the tty support the display of utf8 characters. Can you get rid of this dilemma through tmux?

**Comment by krader1961** [comment]
> Can you get rid of this dilemma through tmux?

No. If anything written by the programs you run inside tmux writes non-ASCII UTF-8 those bytes are simply passed through. Similarly, if you have configured tmux to use Unicode chars in the status line that will cause problems if your terminal does not support those code points.

Also, what exactly could tmux do that would be useful? If you are outputting non-ASCII the only thing tmux could do is replace those chars with an ASCII char or drop them completely. Neither option is going to be very useful.
