### ISSUE TITLE
Commands don't work when there are a lot of printouts on another window

### ISSUE THREAD

**Issue by codergr** [tmux/tmux#279]
Hi guys , thanks for an amazing tool. 

During a lengthy process i.e unzip, or build etc which generates a lot of console prints I have noticed that I cannot change windows i.e. Ctlr+B + Ctrl+Q doesn't work until the process which generates the printous terminate. 

Any one else has the same issue? Is there a way to solve this?

Thanks
Sotiris

**Comment by nicm** [comment]
Are you using tmux over SSH?

What terminal are you using?

**Comment by codergr** [comment]
Hi Nicholas, 

Your assumptions are correct, it happens only over SSH and with SecureCRT terminal.

Didn't happen accessing with Putty ( seems Putty gives priority to Ctrl key ) or from a Linux machine ( tested with SLES12 and Ubuntu ).

From within the machine ( i.e. no SSH ) doesn't happen.

Thanks
Sotiris
