### ISSUE TITLE
window-linked should be a session hook

### ISSUE THREAD

**Issue by vincentbernat** [tmux/tmux#2790]
### Issue description

Since 9cbe9675ea8a8efb01dcc5f267e6d5853b2cd58f, `window-linked` is a window option. This makes the following configuration snippet fails:

```
tmux set-hook window-linked "set-window-option remain-on-exit on"
```

I suppose the hook is only installed on the current window and not at the session level.

Maybe I am mistaken about the cause. It was working in 3.1c and it does not with 3.2a.

### Required information

* tmux version (`tmux -V`): 3.2a
* Platform (`uname -sp`): Linux

**Comment by vincentbernat** [comment]
My bad, that's the `remain-on-exit` option which does not work.

**Comment by vincentbernat** [comment]
Well, after testing a bit more, there is really an issue with the hook:

```
tmux set-hook window-linked "set-window-option remain-on-exit on"
tmux new-window
tmux showw
```

This should display `remain-on-exit on`, this does not.

**Comment by nicm** [comment]
I think you are probably right. Does this work?
~~~~
--- options-table.c     14 Jul 2021 08:56:00 -0000      1.145
+++ options-table.c     26 Jul 2021 09:10:41 -0000
@@ -1161,10 +1161,10 @@ const struct options_table_entry options
        OPTIONS_TABLE_HOOK("session-renamed", ""),
        OPTIONS_TABLE_HOOK("session-window-changed", ""),
        OPTIONS_TABLE_WINDOW_HOOK("window-layout-changed", ""),
-       OPTIONS_TABLE_WINDOW_HOOK("window-linked", ""),
+       OPTIONS_TABLE_HOOK("window-linked", ""),
        OPTIONS_TABLE_WINDOW_HOOK("window-pane-changed", ""),
        OPTIONS_TABLE_WINDOW_HOOK("window-renamed", ""),
-       OPTIONS_TABLE_WINDOW_HOOK("window-unlinked", ""),
+       OPTIONS_TABLE_HOOK("window-unlinked", ""),

        { .name = NULL }
 };

**Comment by vincentbernat** [comment]
Yes, it works fine this way!

**Comment by nicm** [comment]
Applied now, thanks!
