### ISSUE TITLE
Sending `Alt + UpArrow`/`Alt + DownArrow` to Zsh in Tmux

### ISSUE THREAD

**Issue by stevenxxiu** [tmux/tmux#2791]
### Issue description
In recent *Linux* kernel versions, the `Shift + PageUp`/`Shift + PageDown` key to scroll up/down in a TTY have been removed. For this reason I'm using *Tmux* again, and thought I might as well set it up properly, so using the TTY is a bit more pleasant.

I'm not quite sure how I can configure *Tmux* to pass the `Alt + UpArrow`/`Alt + DownArrow` escape sequences onto *Zsh*. I use these to go up/down history using the *history-substring-search* extension. They work fine in a TTY outside of *Tmux*.

I managed to forward `Ctrl` with arrow keys in *Tmux* with `set-option -g xterm-keys on`, but this doesn't appear to forward the `Alt` key combos.

I do get the correct key sequences show up with `showkey -a` in the TTY, after using my custom keymap file and using `loadkeys`:

- `Alt + UpArrow`: `^[^[[A`
- `Alt + DownArrow`: `^[^[[B`

My *Tmux* config:

```
set-option -g history-limit 10000
set-option -g xterm-keys on

set-option -s user-keys[0] "\e[5;2~"
bind-key -n User0 copy-mode -u
set-option -s user-keys[1] "\e[6;2~"
bind-key -n User1 send-keys Pagedown
```

### Required information
* tmux version (`tmux -V`). `tmux 3.2a`
* Platform (`uname -sp`). `Linux unknown` (*Arch Linux* kernel 5.13.4-arch1-1 x86_64).
* $TERM inside and outside of tmux (`echo $TERM`). Inside (in a TTY): `screen`. Outside: `xterm-256color`.
* Logs from tmux (`tmux kill-server; tmux -vv new`). N/A

**Comment by lockheadone** [comment]
#2789 

> 

>

**Comment by nicm** [comment]
The Linux console is not `xterm-256color`, it is `linux`.

**Comment by stevenxxiu** [comment]
> The Linux console is not `xterm-256color`, it is `linux`.

Ah I was just using *WezTerm* there for testing. Didn't say it too clearly.

**Comment by nicm** [comment]
Show logs please, don't forget to press the keys.

**Comment by stevenxxiu** [comment]
I'll close this, as I moved over to `extended-keys` from `xterm-keys` now.
