### ISSUE TITLE
`Shift + Enter` isn't working when using extended keys

### ISSUE THREAD

**Issue by stevenxxiu** [tmux/tmux#2792]
### Issue description
Due to problems encountered in https://github.com/tmux/tmux/issues/2791, I attempted to bind the keys I use to escape sequences in http://www.leonerd.org.uk/hacks/fixterms/, as suggested by https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys.

I bind `Shift + Enter` in my *Zsh* settings to enter a new line. This works outside *Tmux* (both in TTY and my terminal emulator *WezTerm*), but not inside *Tmux*.

When I run `cat`, nothing shows up when I press `Shift + Enter`.

I believe `Shift + Enter` should be bound to `\033[13;2u`.

This happens both in TTY, with the following keymap file that gets loaded by `loadkeys -s us personal.map`:

```
shift keycode 28 = F40              # `Shift + Enter`
string F40 = "\033[13;2u"
```

and in my terminal emulator *WezTerm* with my config:

```
local wezterm = require 'wezterm';

return {
  keys = {
    {key='Enter', mods='SHIFT', action=wezterm.action{SendString='\x1b[13;2u'}},
    ...
  }
  ...
}
```

Config that reproduces the issue:

```
set-option -s extended-keys on
set-option -as terminal-features 'xterm*:extkeys'
```

### Required information
* tmux version (`tmux -V`). `tmux 3.2a`
* Platform (`uname -sp`). `Linux unknown` (*Arch Linux* kernel 5.13.4-arch1-1 x86_64).
* $TERM inside and outside of tmux (`echo $TERM`). Inside: `screen`. Outside: `xterm-256color`.
* Logs from tmux (`tmux kill-server; tmux -vv new`). Getting nothing logged.

**Comment by nicm** [comment]
The application inside tmux needs to request extended keys from tmux, or you need to set `extended-keys` to `always`.

**Comment by stevenxxiu** [comment]
Thanks! Setting `extended-keys` to `always` works.
