### ISSUE TITLE
Arrow keys printing `ABDC`

### ISSUE THREAD

**Issue by stevenxxiu** [tmux/tmux#2793]
### Issue description
I'm using `extended-keys`. These keys are bound to the escape sequences:

- Up: `^[[A`
- Down: `^[[B`
- Left: `^[[C`
- Right: `^[[D`

When I press the arrow keys inside *Tmux*, Up/Down/Left/Right, I'm getting `ABDC` printed on the terminal.

To produce the logs, I pressed `RightArrow`, `BackSpace`, `q`, `Enter`.

A single `C` was printed after I pressed `RightArrow`.

A minimal *Tmux* config:

```
set-option -s extended-keys always
```

My terminal emulator's *WezTerm*. The same happens in a TTY.

### Required information
Please provide the following information:

* tmux version (`tmux -V`). tmux 3.2a
* Platform (`uname -sp`). Linux unknown (Arch Linux 5.13.4-arch2-1).
* $TERM inside and outside of tmux (`echo $TERM`). `xterm-256color` outside and `screen` inside.
* Logs from tmux (`tmux kill-server; tmux -vv new`).

  - [tmux-client-304049.log](https://github.com/tmux/tmux/files/6878785/tmux-client-304049.log)
  - [tmux-out-304052.log](https://github.com/tmux/tmux/files/6878786/tmux-out-304052.log)
  - [tmux-server-304052.log](https://github.com/tmux/tmux/files/6878787/tmux-server-304052.log)

**Comment by nicm** [comment]
Whatever you are running in the pane is sending `smkx` which means tmux sends `\033OC` for `Up`, not `\033[C`.

**Comment by stevenxxiu** [comment]
Hmm I'm not sure how I'd fix this situation. I have this code from https://github.com/ohmyzsh/ohmyzsh/blob/079e7bb5e0a79171f3356d55d3f6302a82645a39/lib/key-bindings.zsh:

```
# Make sure that the terminal is in application mode when ZLE is active, since only then values from `$terminfo` are
# valid.
if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
  function zle-line-init {
    echoti smkx
  }
  function zle-line-finish {
    echoti rmkx
  }
  zle -N zle-line-init
  zle -N zle-line-finish
fi
```

Should I remove it, or should I add bindings to `\033OC` as well?

**Comment by nicm** [comment]
If you want to use terminfo then you need to send smkx or the values in terminfo won't match what is sent.

**Comment by stevenxxiu** [comment]
Ah I don't think I can include that code anyway, as it's part of *Oh-My-Zsh*.

I just bound my functions to the alternative escape sequences when `smkx` is active. Thanks!
