### ISSUE TITLE
Feature: autocommands

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2794]
Implement vim-inspired autocommand interface. With at the very least:

SessionAttach - Triggered when a session is attached
SessionDetach - Triggered when a session is about to be detached
WinEnter - After entering a window
WinLeave - Before leaving a window
PaneEnter - After entering a pane
PaneLeave - Before leaving a pane
FocusGained - After client gains focus
FocusLost - After client loses focus

Such a scheme of auto commands can help creating innovative plugin, for example: to track how much time one spends in a session/project, and even finer information like what nature of task/app does one spend time on while working on a project. Imagine WakaTime on steroids: https://wakatime.com.

The way I was thinking this could work is that user can specify a shell script for each autocommand they are interested in, perhaps using "tmux run-shell". When a autocommand triggers, its script will be queued to run asynchronously or synchronously (whichever way you think makes more sense). Such a scheme would require that somehow a strict order of autocommand execution is maintained. An autocommand's script start running till the previous autocommand's script exits. Not sure if there could be another way...

**Comment by nicm** [comment]
We already have hooks.

**Comment by reportaman** [comment]
@nicm Thanks, will play with it and get back if I need more information. For now the documentation on hooks is good enough to start.

**Comment by reportaman** [comment]
@nicm A question:``#{hook_session_name}``, and ``#{hook_window_name}`` seems to be not reliable (it is empty string at times for pane-focus-in/out). Is it valid to use ``#{session_name}``,``#{window_name}``, and ``#{pane_id}`` like in following? They seem to yield correct results in my testing, though if I add ``export HOOK_PANE_PID=\"\#{pane_pid}\"; \``, it doesn't work well.

```
set-hook -g pane-focus-in 'run-shell "\
    export HOOK_SESSION_NAME=\"\#{session_name}\"; \
    export HOOK_WINDOW_NAME=\"\#{window_name}\"; \
    export HOOK_PANE=\"\#{pane_id}\"; \
    ~/somescript; \
    "'
set-hook -g pane-focus-out 'run-shell "\
    export HOOK_SESSION_NAME=\"\#{session_name}\"; \
    export HOOK_WINDOW_NAME=\"\#{window_name}\"; \
    export HOOK_PANE=\"\#{pane_id}\"; \
    ~/somescript; \
    "'
```

**Comment by nicm** [comment]
Use `hook_pane`, you can get the rest from that using `display-message -pt`.

**Comment by reportaman** [comment]
@nicm Ok thanks. Also, is there a way to guarantee strict order in events? It would be easier to process a log if ``pane-focus-out`` appears strictly before the next ``pane-focus-in``.

**Comment by reportaman** [comment]
Also, ``hook_pane`` is empty for hook ``client-session-changed``. Is it guaranteed that hook is called after the session has changed? Do I now use ``hook_session_name`` to find the rest of the information? Or simply use ``session_name``? will the latter be functionally correct all the time, is it unpreferred? 

If I get this right, not all hooks fill all of ``hook_*``  values, and depending on context one has to capture one of the relevant ``hook_*`` values, and use ``tmux display-message`` to get the rest?

**Comment by nicm** [comment]
What you get will depend on the type of hook.

**Comment by reportaman** [comment]
@nicm Yep, I get that. Though I would imagine at least ``hook_session`` & ``hook_session_name`` are available for ``client-session-changed``? If thats not expected, is there any other usual ``hook_*`` information available for that hook?

**Comment by reportaman** [comment]
@nicm Is there a way to use wait-for to order pane-focus-out, pane-focus-in, and client-session-changed?

**Comment by nicm** [comment]
No.

**Comment by reportaman** [comment]
@nicm Ok, in that case having an additional event hook ``client-focus-out`` would help.

Let me explain why. Here's the technique I am thinking to implement (to log time spent in each pane):

On each pane-focus-in or client-session-changed event, write a line with duration to a file for which focus was in last pane by looking at last ``@focusintime`` and ``@focuspaneid``. Then update ``@focusintime`` & ``@focuspaneid`` to current time, and current pid respectively.

This technique works as long as the focus does not go outside the client. In that case, if I were to just trigger at pane-focus-in, then it will also log the time spent outside of the tmux client as time spent within the last pane.

**Comment by nicm** [comment]
When focus is lost from tmux entirely you should get `pane-focus-out` same as if you change the pane, assuming your terminal supports focus events. If your terminal doesn't support focus events then tmux can't trigger anything when focus is lost except when you change a pane inside tmux.

**Comment by reportaman** [comment]
@nicm Yep I am aware of that. Though pane-focus-out triggers even when switching between panes. In my testing it sometimes triggers after pane-focus-in and sometimes before it. Given it also triggers when focus is within the window, and given it's order is not known (in relation to pane-focus-in), it's complicated to work with. Is there a way to know which client is "currently
focused" i.e. current-client. Maybe if you don't like the idea of adding another focus lost event, then an option #{current_client} that is empty when no client is focused will also work well to detect if focus went outside tmux. As of now, unless I enable activity monitoring (which I don't see a point to), I cannot cleanly  detect if focus did go out of tmux & do something special.

**Comment by nicm** [comment]
Well that is a lie because there is a `client_focused` flag, we just don't expose it as a format. But there is no "current client". 

We could add events when a client gets focus in/out as well as when a pane does, it is similar to the change in this issue https://github.com/tmux/tmux/pull/2803 except it the notify_client would be fired from the end of `tty_keys_next` where it does the "Check for focus events" bit.

**Comment by reportaman** [comment]
@nicm Yes client focus in/out would be great to have!

**Comment by nicm** [comment]
Please try this [x.diff.txt](https://github.com/tmux/tmux/files/6936405/x.diff.txt).

You should also already be able to see if a client is focused already by doing, for example: `#{m/r:focused,#{client_flags}}`

**Comment by reportaman** [comment]
@nicm So far I have been using homebrew's tmux. Here's what I get when I reach the make command in the manual install steps you mention for fresh install from GitHub repo:

```
checking dependency style of gcc... gcc3
./configure: line 4713: syntax error near unexpected token `newline'
./configure: line 4713: `    '''
make: *** [config.status] Error 2

```

![Screen Shot 2021-08-05 at 1 17 29 AM](https://user-images.githubusercontent.com/71736629/128317205-1c6dc7c5-3c28-400d-8680-ea5ff9e6e427.png)

**Comment by nicm** [comment]
Seems like your autoconf or shell is broken.

**Comment by reportaman** [comment]
@nicm Now I get error that these hooks are not found:

```
set-hook -g client-focus-out ...
set-hook -g client-focus-in ...
```

**Comment by nicm** [comment]
are you sure you're killed tmux entirely before upgrading and that you are
running the binary you just built and not the old one?

**Comment by reportaman** [comment]
@nicm It worked! Hit some weird problem: after rebuilding & installing tmux I had put an alias tmux=/usr/local/bin/tmux in my .zshrc. But for some reason that did not get picked up by some tmux scripts or plugins in my workflow, probably because they use bash instead of zsh & in $PATH the homebrew version of tmux was ahead of one I installed in /usr/local/bin, though I don't know... Seems like I should never use aliases...

**Comment by nicm** [comment]
Great, applied now, thanks!
