### ISSUE TITLE
When I use tmux in Arm linux , it's some question

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [tmux/tmux#2796]
### Issue description
tmux is master version; When I run ; tmux: need UTF-8 locale (LC_CTYPE) but have ANSI_X3.4-1968, my system can not set UTF-8, 
Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by wangwenqiangGitHub** [comment]
![image](https://user-images.githubusercontent.com/28779327/127413722-db2653d7-1fa2-4aff-bc02-60704dd7f2a8.png)

**Comment by krader1961** [comment]
You didn't provide any of the information requested in the issue template and you left the entire template in place. **Don't do that.** Also, the error message seems self explanatory. Your locale is essentially ASCII, not UTF-8. See https://stackoverflow.com/questions/48743106/whats-ansi-x3-4-1968-encoding. Tmux requires a UTF-8 locale. For example:

```
> locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by wangwenqiangGitHub** [comment]
> You didn't provide any of the information requested in the issue template and you left the entire template in place. **Don't do that.** Also, the error message seems self explanatory. Your locale is essentially ASCII, not UTF-8. See https://stackoverflow.com/questions/48743106/whats-ansi-x3-4-1968-encoding. Tmux requires a UTF-8 locale. For example:
> 
> ```
> > locale
> LANG="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_CTYPE="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_ALL=
> ```

my Arm linux no locale order, it not suport

**Comment by krader1961** [comment]
I don't understand what you mean by "no locale order". If you don't have a `locale` command you should be able to find it in an optional package that you should install. If you mean you don't have any UTF-8 locales installed, again, find the package that contains locale definitions for your system and install it. Note that on most Linux systems the locale definitions can be found in */usr/share/locale*. Finally, if you have not set an of the locale env vars it may be that your system defaults to ANSI_X3.4-1968. In which case simply `export LANG=en_US.UTF-8` (or whatever locale is appropriate for your situation).

**Comment by wangwenqiangGitHub** [comment]
> I don't understand what you mean by "no locale order". If you don't have a `locale` command you should be able to find it in an optional package that you should install. If you mean you don't have any UTF-8 locales installed, again, find the package that contains locale definitions for your system and install it. Note that on most Linux systems the locale definitions can be found in _/usr/share/locale_. Finally, if you have not set an of the locale env vars it may be that your system defaults to ANSI_X3.4-1968. In which case simply `export LANG=en_US.UTF-8` (or whatever locale is appropriate for your situation).

My linux file system don't have a `locale` command ;
 /usr/share/locale: No such file or directory
how can I transplant `locale` in arm linux

**Comment by krader1961** [comment]
> how can I transplant locale in arm linux

I don't know because you haven't told us which Linux distro you are using. What does `uname -a` output? Regardless, this isn't really an appropriate question for the tmux community since we're not going to have expertise with every Linux distro. You'll get better help from whatever support forum your distro provides or perhaps https://superuser.com/.

**Comment by wangwenqiangGitHub** [comment]
> > how can I transplant locale in arm linux
> 
> I don't know because you haven't told us which Linux distro you are using. What does `uname -a` output? Regardless, this isn't really an appropriate question for the tmux community since we're not going to have expertise with every Linux distro. You'll get better help from whatever support forum your distro provides or perhaps https://superuser.com/.

Linux ww@ww_SDK 6.0.2.0 #3 SMP PREEMPT Mon May 10 17:13:14 CST 2021 ww armv7l GNU/Linux

**Comment by krader1961** [comment]
I have no idea what distro "ww" is as I've never seen it before. On ubuntu2004, for example, I can find that package `libc-bin` provides the */usr/bin/locale* command:

```
> uname -a
Linux ubuntu2004-64 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> dpkg-query -S /usr/bin/locale
libc-bin: /usr/bin/locale
```

Again, you should use either the SuperUser site or whatever forum your "ww" distro provides to get help on installing UTF-8 locale definitions.

**Comment by krader1961** [comment]
@wangwenqiangGitHub, I'm curious if you are using Linux on something like a smartphone (e.g., an Android phone) or other non-traditional device. That would explain the strange "ww" distro name and the fact that you don't have a `locale` command installed by default or any locale definitions in */usr/share/locale*.

**Comment by krader1961** [comment]
@wangwenqiangGitHub, This has been asked once before: #1044. In that case the user was apparently using a Linux emulator written in Javascript which provided a very limited Linux environment. If you're using something like that there is probably no way to get tmux to work other than by modifying the source code to special-case locale `ANSI_X3.4-1968` as a generic UTF-8 locale.

**Comment by wangwenqiangGitHub** [comment]
> @wangwenqiangGitHub, This has been asked once before: #1044. In that case the user was apparently using a Linux emulator written in Javascript which provided a very limited Linux environment. If you're using something like that there is probably no way to get tmux to work other than by modifying the source code to special-case locale `ANSI_X3.4-1968` as a generic UTF-8 locale.

this linux is on Embedded System

**Comment by krader1961** [comment]
> this linux is on Embedded System

In other words, it is on a proprietary Linux distro that is optimized to minimize its size and therefore eliminates many features. Features that users of typical Linux distros take for granted. Obviously everyone reading this issue should have known that information given your initial problem statement. /sarcasm

The only way to make tmux work on your Frankenstein Linux "ww" distro is to modify the tmux source code to special-case locale `ANSI_X3.4-1968`. See the `main()` function:

https://github.com/tmux/tmux/blob/63f9f3113c731b7a7ced2f10b047722647d7b544/tmux.c#L341-L348

@nicm, Perhaps this unusual locale should be treated as a pass thru UTF-8 locale by default as is done for `C.UTF-8`.

**Comment by wangwenqiangGitHub** [comment]
> > this linux is on Embedded System
> 
> In other words, it is on a proprietary Linux distro that is optimized to minimize its size and therefore eliminates many features. Features that users of typical Linux distros take for granted. Obviously everyone reading this issue should have known that information given your initial problem statement. /sarcasm
> 
> The only way to make tmux work on your Frankenstein Linux "ww" distro is to modify the tmux source code to special-case locale `ANSI_X3.4-1968`. See the `main()` function:
> 
> https://github.com/tmux/tmux/blob/63f9f3113c731b7a7ced2f10b047722647d7b544/tmux.c#L341-L348
> 
> @nicm, Perhaps this unusual locale should be treated as a pass thru UTF-8 locale by default as is done for `C.UTF-8`.
I build tmux again, 
missing or unsuitable terminal: xterm-256color

**Comment by krader1961** [comment]
> missing or unsuitable terminal: xterm-256color

That is because the value of your `TERM` env var is invalid for your system. That is, it does not have a terminfo definition for `xterm-256color`. This is probably due to the same reason tmux did not recognize the `ANSI_X3.4-1968` locale name. Your Linux distro is customized to minimize its size and not install things most of us take for granted like all the known terminfo definitions.

**Comment by wangwenqiangGitHub** [comment]
> > missing or unsuitable terminal: xterm-256color
> 
> That is because the value of your `TERM` env var is invalid for your system. That is, it does not have a terminfo definition for `xterm-256color`. This is probably due to the same reason tmux did not recognize the `ANSI_X3.4-1968` locale name. Your Linux distro is customized to minimize its size and not install things most of us take for granted like all the known terminfo definitions.

How can I deal with this problem

**Comment by krader1961** [comment]
@wangwenqiangGitHub, you wrote

> I build tmux again

You did not tell us what changes you made to the source code.  So we have no idea what how your new tmux program differs from the official version. You really need to think more about including relevant information in your comments. Such as the changes your made to the source code in your new "build".

You then asked, with respect to your invalid `TERM` env var value problem,  this question:

> missing or unsuitable terminal: xterm-256color
> How can I deal with this problem

I have no idea. And neither will anyone else since you are using a private, highly customized, Linux distro that does not include features most Linux users assume will be present. Such as the ability to install terminfo definitions.

**Comment by wangwenqiangGitHub** [comment]
> @wangwenqiangGitHub, you wrote
> 
> > I build tmux again
> 
> You did not tell us what changes you made to the source code. So we have no idea how your new tmux program differs from the official version. You really need to think more about including relevant information in your comments. Such as the changes your made to the source code in your new "build".
> 
> You then asked, with respect to your invalid `TERM` env var value problem, this question:
> 
> > missing or unsuitable terminal: xterm-256color
> > How can I deal with this problem
> 
> I have no idea. And neither will anyone else since you are using a private, highly customized, Linux distro that does not include features most Linux users assume will be present. Such as the ability to install terminfo definitions.

ok . thinks

**Comment by wangwenqiangGitHub** [comment]
> > > this linux is on Embedded System
> > 
> > 
> > In other words, it is on a proprietary Linux distro that is optimized to minimize its size and therefore eliminates many features. Features that users of typical Linux distros take for granted. Obviously everyone reading this issue should have known that information given your initial problem statement. /sarcasm
> > The only way to make tmux work on your Frankenstein Linux "ww" distro is to modify the tmux source code to special-case locale `ANSI_X3.4-1968`. See the `main()` function:
> > https://github.com/tmux/tmux/blob/63f9f3113c731b7a7ced2f10b047722647d7b544/tmux.c#L341-L348
> > 
> > @nicm, Perhaps this unusual locale should be treated as a pass thru UTF-8 locale by default as is done for `C.UTF-8`.
> > I build tmux again,
> > missing or unsuitable terminal: xterm-256color
