### ISSUE TITLE
Nesting command-prompt or best way to do conditional interaction via command-prompt? (back to back command-prompt's)

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2798]
Currently I am trying to do a conditional command-prompt that seems to nest but not plug the correct values upon nesting.

Spec: 
Prompt for option-1
if option-1 has a certain special value
prompt for option-2

```
tmux command-prompt -p "Set option-1:" "%if #{==:%1,foo} set-option @option1 foo %else command-prompt -p 'Option-2:' 'set-option @option2 %1' %endif"
```

When I pass values other than foo for the outer command-prompt, it does call inner command-prompt, but the value passed to option2 is one passed to outer command prompt.

If do this in a script like:

```
tmux command-prompt -p "Set option-1:"set-option @option1 %1"
option1=$(tmux show-option @option1)
if option1 equals something
tmux command-prompt -p "Set option-2:"set-option @option2 %1"
```

that doesn't work either as the script exits upon completion of first command-prompt. Is there a way to not make the script exit at the end of first command prompt?

**Comment by nicm** [comment]
All %1 are replaced in the command when the first prompt finishes, try using %% instead (only the first %% will be replaced).

**Comment by reportaman** [comment]
@nicm Thanks! ``%%`` worked.
