### ISSUE TITLE
Feature: Non-cancelling copy-line and copy-end-of-line

### ISSUE THREAD

**Issue by neightchan** [tmux/tmux#2799]
### Issue description
When copying the selection, one has two options:
- `copy-selection`
- `copy-selection-and-cancel`
The first of these just copies the selected text into a new buffer.  The second copies the select text into a new buffer and also cancels out of copy mode.

For copying a line, one only has
- `copy-line`
That command copies the text on the line with the cursor into a new buffer and also exits out of copy mode.  There is no way to just copy the line into a new buffer and stay in copy mode.

The same limitation exists for copying from the cursor's current position to the end of the line.  In that case, one only has `copy-end-of-line`.

It would be nice to be able to copy the current line (or from the cursor's current position to the end of its line) without cancelling out of copy mode.

### Required information
tmux 3.1c

**Comment by nicm** [comment]
You can probably do this by binding start-of-line, begin-selection, end-of-line, copy-selection as a sequence, but it would be nice to have builtin commands.

**Comment by nicm** [comment]
Try this please: [y.diff.txt](https://github.com/tmux/tmux/files/6936657/y.diff.txt)

**Comment by neightchan** [comment]
This patch worked delightfully for me.  I set

```
bind-key -T copy-mode-vi y switch-client -T copy-mode-vi_y
bind-key -T copy-mode-vi_y y send-keys -X copy-line
bind-key -T copy-mode-vi_y $ send-keys -X copy-end-of-line
```

and had even more vi goodness.  Thank you!

**Comment by nicm** [comment]
Applied now, thanks!
