### ISSUE TITLE
Doc for select-pane -P style settings

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#28]
I guess this is rather new functionality, but I couldn't find very specific information in the manpage about exactly what is supported by the -P flag. It seems like I can send it `default`, colors for `bg` and `fg`, but I don't know what else I can do. I was sort of hoping that maybe I can control border colors for specific panes, but that does not appear to be the case.

**Comment by ThomasAdam** [comment]
No, it's just for the pane itself.  Borders are separate, as they have their own style.

**Comment by unphased** [comment]
Sure.. that makes sense. Could you comment on what in addition to the "bg" is settable? Presumably "fg" is as well, looking at the source. Can I make all the text in a given pane bold?
