### ISSUE TITLE
Bracketed Paste mode should be set independently for each pane and window

### ISSUE THREAD

**Issue by jonasbb** [tmux/tmux#280]
Sorry if there is documentation describing the bracketed paste feature for tmux in detail, but I could not find any resources on how good and extended the claimed support is. The only mentionings are in the changelog for 1.7: "* Support for bracketed-paste mode." and the man page under 'paste-buffer'.

Steps to reproduce:
Open byobu with two windows.
Open vim and enter insert mode. This enables bracketed paste in my configuration.
Switch to second window and paste something there.

Result:
Instead of pasting the string '#Test' the string '[200~#Test[201~' is pasted.
This clearly shows, that the bracketed paste mode is not disabled when switching windows and the terminal emulator then uses unknown escape sequences unknown to the application.
I am running byobu version 5.97 with tmux 2.0 on Fedora 23.
I get similar results on Debian 7.9 with byobu version 5.91 and tmux 1.6, except there the pasted string if '0~#Test1~'

As bracketed paste is an optional feature which has to explicitly enabled by each application this feature should not be forced onto other applications. Therefore, to correctly emulate multiple terminals the current state of the bracketed paste option has to be known per terminal. If this state changes when changing panes or windows tmux must inform the terminal emulator and enable/disable this feature.

**Comment by nicm** [comment]
I do not know anything about byobu and tmux 1.6 is way too old, please
reproduce with a current tmux.

**Comment by jonasbb** [comment]
tmux 2.0 is not new enough?
I will try to reproduce it with tmux 2.1 later this evening. But as there is no other mentioning in the changelog I would be surprised to find any changes.

byobu is just a selection of scripts which do all the heavy work of configuring tmux to be well usable. But I don't think it causes this bug. http://byobu.co/

**Comment by nicm** [comment]
Try 2.1 or master please but try without byobu, or better without any config:

    tmux -Ltest -f/dev/null new

**Comment by jonasbb** [comment]
I can reproduce this on git master (ca29dc9)
I started tmux as you suggested. Strangely I see the same effects like the older 1.6 version. So any paste of '#Test' into bash will print '0~#Test1~'.

Here are the exact steps I took.
```
$ ./tmux -Ltest -f/dev/null new

vim <Enter> i <Enter>
<C-b> :new-window <Enter>
# Any paste will have the same bracketed paste mode markers
<C-b> 0 <Esc>
# wait for a second until the terminal has processed the escape code
<C-b> 1
# terminal is no longer in bracketed paste mode
```

If you want to reproduce this by yourself, I use this code inside my .vimrc file.
https://github.com/ConradIrwin/vim-bracketed-paste/blob/master/plugin/bracketed-paste.vim

**Comment by nicm** [comment]
OK so you are saying it is only the first time you change window,
subsequent times it does clear the mode?

**Comment by jonasbb** [comment]
No, I can switch back and forth between both windows. As long as vim is in insert mode (entering insert mode starts the bracketed paste mode) the bracketed paste mode will be used in the second window too. If I exit from insert mode (the <Esc>) and wait until the escape code is processed everything is back to normal again.

Without any knowledge of tmux internals here, just a guess. It seems to me as tmux just passes through these escape codes to its terminal, thus activating the bracketed paste. But tmux does not keep track on which window (or pane) requested the bracketed paste. So if I switch to another window (or pane) the state of the bracketed paste in the terminal emulator stays the same.
The correct solution would be for tmux to recognize the escape sequence and set a flag per pane and every time the panes are switched either enable or disable the bracketed paste mode in the terminal emulator again.

As I sad, I could not find any mentionings of bracketed paste and tmux beside those two entries, so I do not know what the supposed state of support should be. So maybe it is not a bug but a feature request of supporting a nice little feature.

**Comment by nicm** [comment]
Of course tmux keeps track, the same as it does for bold or colour or
mouse. It never just passes something through unless explicitly asked to by
the application.

Do you see the same if you do

printf "\033[?2004h"

instead of running vim?

**Comment by jonasbb** [comment]
No, I do not. In this case everything works correctly.
I am sorry. I just got frustrated in searching for a solution, because there are so few information.
Could you explain what you mean by "It never just passes something through unless explicitly asked to by the application." and how this works or where to find this information?

Apparently the script is the problem. Maybe this WrapForTmux does this pass through, so I would like to be able to fix this script.

**Comment by nicm** [comment]
Yes the \033Ptmux;xyz\033\\ sequence will pass through whatever is inside (xyz). If you remove that wrapper bit it should work.
