### ISSUE TITLE
The pane divider becomes the letters q and x

### ISSUE THREAD

**Issue by 3026187875** [tmux/tmux#2800]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information
My ssh client is putty
ubnutu20.04 server 
The first use is normal, but when I use it the next day, it becomes q and x

Please provide the following information:

* tmux version (`tmux -V`).    tmux3.0a
* Platform (`uname -sp`).      Linux aarch64
* $TERM inside and outside of tmux (`echo $TERM`).   xterm
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by 3026187875** [comment]
now，I know why.Because there is LANG=C in my environment variable. what can l do to make the two exist at the same time？



---Original---
From: "Nicholas ***@***.***&gt;
Date: Mon, Aug 2, 2021 17:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tmux/tmux] The pane divider becomes the letters q and x (#2800)




 
Does this still happen with master?

**Comment by nicm** [comment]
You might try these:

https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-utf-8

https://github.com/tmux/tmux/wiki/FAQ#why-are-tmux-pane-separators-dashed-rather-than-continuous-lines
