### ISSUE TITLE
How to suppress cursor initial flickering on `tmux popup (e.g. fzf)`

### ISSUE THREAD

**Issue by mudox** [tmux/tmux#2801]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
    3.3
* Platform (`uname -sp`).
    Darwin arm64
* $TERM inside and outside of tmux (`echo $TERM`).
    screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

When running `tmux popup fzf`, I always saw the cursor flicker (once) at top left corner of the popup window __before__ fzf ui show up.

I wonder if there is a standard way to suppress this?

**Comment by reportaman** [comment]
The usual way to suppress cursor on terminal is ``tput civis``, and to show it back ``tput cnorm``. Perhaps this is a issue for fzf, especially given fzf already comes with that functionally built in with command `` fzf-tmux -p`` (you don't need to type tmux popup fzf)

**Comment by mudox** [comment]
@reportaman  thanks
