### ISSUE TITLE
Read-only pane

### ISSUE THREAD

**Issue by srezasm** [tmux/tmux#2804]
Please add a shortcut for making a pane read-only

**Comment by nicm** [comment]
I don't think we need a default key binding for this

**Comment by srezasm** [comment]
Is there any manual way to use this feature? I need it every day.

**Comment by nicm** [comment]
Bind it to a key?

**Comment by srezasm** [comment]
Yes, but not specifically

**Comment by nicm** [comment]
I don't know what you mean.

**Comment by srezasm** [comment]
Is there currently any way to make a pane read-only?

**Comment by nicm** [comment]
selectp -d and -e

**Comment by srezasm** [comment]
Thanks @nicm 

Making read-only
`selectp -t [paneNumber] -d`

Reset default
`selectp -t [paneNumber] -e`
