### ISSUE TITLE
Feature: don't exit script from which tmux command-prompt exits

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2805]
I was writing a script that does a bunch of processing, and asks questions based on user input. The logic is too complex to be put in a tmux command-prompt template to do a series of questions. As of now, if a tmux command-prompt were called from a shell script, the shell script exits when the first encountered command-prompt exits, thus making it impossible to code the logic in shell script to do multiple command prompts. The ticket is to enhance the way we get to interact with command-prompt that enables it to be used in such cases. To avoid a flickering of the status/command bar (in between two back to back tmux command-prompts), a possible solution could be to add commands that explicitly open command prompt mode, and close it again. For instance tmux command-prompt-start, tmux command-prompt-exit.

As an example, in the following script, the second tmux command-prompt will never be reached.
```
#!/opt/homebrew/bin/zsh

tmux command-prompt -p "Set option-1:" "%if #{==:%%,foo} set-option @option1 foo %else command-prompt -p 'Option-2:' 'set-option @option2 %%' %endif"

tmux command-prompt -p "Set option-1:" "%if #{==:%%,foo} set-option @option1 foo %else command-prompt -p 'Option-2:' 'set-option @option2 %%' %endif"

```

**Comment by nicm** [comment]
command-prompt does not block the calling client until it finishes, you need to use some other mechanism like wait-for or checking for a file to do that.

Although it might not be hard to make command-prompt do it natively.

**Comment by reportaman** [comment]
@nicm Yes, after trying a bunch of positions for ``tmux wait-for``, I figured the position it works well in. And for the flickering/stuttering effect, I think one can empty the status-bar for while doing multiple queries in succession. Will check that with .tmux repo.

**Comment by reportaman** [comment]
@nicm Seems like confirm-before blocks the calling client until it finishes? Is it guaranteed that confirm-before's command will finish execution before the calling script continues?
