### ISSUE TITLE
Panes change size when computer wakesup from sleep

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2806]
Depending on the layout, and size of the panes, some panes spuriously change size if computer is put to sleep and woken up.

Here are the images from before and after sleep:

1) before:
![Screen Shot 2021-08-03 at 3 38 59 PM](https://user-images.githubusercontent.com/71736629/128095680-af549804-7a40-408c-bd66-729f89e7101d.png)

2) after:
![Screen Shot 2021-08-03 at 3 39 50 PM](https://user-images.githubusercontent.com/71736629/128095660-04ee3dbd-830f-41f0-808a-015aa39ac7c9.png)

``>>tmux -V`` returns: tmux 3.2

``>>neofetch`` returns:
```
                    'c.          reportaman@Mac-mini.local
                 ,xNMM.          ------------------------------
               .OMMMMo           OS: macOS 11.5 20G71 arm64
               OMMM0,            Host: Macmini9,1
     .;loddo:' loolloddol;.      Kernel: 20.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 4 hours, 21 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 1 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 3840x2160
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: tmux
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 2064MiB / 16384MiB
       .cooc,.    .,coo:.
```

**Comment by nicm** [comment]
Logs?

**Comment by reportaman** [comment]
@nicm Here we go...

[tmux-client-5520.log](https://github.com/tmux/tmux/files/6936143/tmux-client-5520.log)
[tmux-out-5522.log](https://github.com/tmux/tmux/files/6936144/tmux-out-5522.log)
[Uploading tmux-server-5522.log…]()

**Comment by nicm** [comment]
Can you do this again but type something like `aaa` immediately before you suspend and then `bbb` after you resume so I can see when it happens in the log?

It looks like something is resizing your terminal window, which will cause the panes to resize:
~~~~
1628141349.590796 tty_resize: /dev/ttys001 now 260x77 (12x27)
1628141350.293017 tty_resize: /dev/ttys001 now 260x77 (12x27)
1628141409.309947 tty_resize: /dev/ttys001 now 159x37 (12x27)
1628141416.632520 tty_resize: /dev/ttys001 now 260x77 (12x27)
1628141448.203431 tty_resize: /dev/ttys001 now 260x77 (12x27)

**Comment by reportaman** [comment]
@nicm Here we go again... This time GitHub won't allow loading the files probably because server log is big. So here's the google drive folder with all the 3 relevant files: https://drive.google.com/drive/folders/1wmPcV23wPbWpTDatGYBCwvnwh0n9kAPk?usp=sharing

**Comment by nicm** [comment]
Looks like something is resizing your terminal when you suspend and restoring it when you resume. Are you running tmux on an external monitor?
~~~~
1628146373.363751 /dev/ttys000: keys are 1 (a)
1628146373.541963 /dev/ttys000: keys are 1 (a)
1628146373.677145 /dev/ttys000: keys are 1 (a)
1628146382.188067 /dev/ttys000: keys are 3 (\033[O)
1628146403.286107 tty_resize: /dev/ttys000 now 159x37 (12x27)
1628146410.648471 tty_resize: /dev/ttys000 now 260x77 (12x27)
1628146417.168995 /dev/ttys000: keys are 3 (\033[I)
1628146419.477557 /dev/ttys000: keys are 1 (b)
1628146419.757612 /dev/ttys000: keys are 1 (b)
1628146420.027000 /dev/ttys000: keys are 1 (b)

**Comment by reportaman** [comment]
@nicm Yes I have a Mac mini desktop that does not have an inbuilt monitor by design (https://www.apple.com/mac-mini/). I have connected it to a LG 27 inch monitor via USB-C port.

**Comment by nicm** [comment]
You will need to figure out how to stop it resizing tmux when you suspend, detach tmux before suspending, or fix the layout afterwards.

**Comment by reportaman** [comment]
@nicm Thanks, thats interesting that it would do that. At least when the monitor powers up there is no animation to suggest that it resizes the screen. Maybe the screen is first resized, and then I get to see the result after resizing has taken effect.

I confirm that detaching tmux before suspending makes sure not to hit this problem.

Does this happen with all machines where tmux is running on an external monitor? Have you also seen such behavior on linux machines? or is it the first time.

I see

**Comment by reportaman** [comment]
Also, is there a detach-all command that would detach all clients? I will look into writing an automator script to run before machine goes to sleep to automatically detach any tmux client.

**Comment by nicm** [comment]
Nobody has reported this to me before, it sounds a bit like typical Apple stupidity but maybe it happens on Linux too.

**Comment by reportaman** [comment]
Updating this here for other users: If the terminal window is maximized (i.e made full screen) then putting Mac to sleep and waking it up does not cause the already maximized window to resize again! Which means just maximize the client's terminal window before putting Mac to sleep and panes won't resize when computer wakes up from sleep. Perhaps this can be a few lines of automator script to automate...
