### ISSUE TITLE
googlegroups not working

### ISSUE THREAD

**Issue by tessus** [tmux/tmux#281]
I have been trying to send an email to tmux-users@googlegroups.com since 2016-01-22 17:01 EST, but nothing happens.

**Comment by nicm** [comment]
Did you join the group?

**Comment by tessus** [comment]
Yes, and you can see that I have sent messages to the group before.

**Comment by nicm** [comment]
What is your email address?

**Comment by nicm** [comment]
Never mind I see them, they are pending.

**Comment by nicm** [comment]
Your gmail address is not subscribed so it was moderated, the others have been marked as spam for some reason. I'll let them through.

**Comment by tessus** [comment]
You can delete them, since I opened issues instead.

The gmail address was a test to see, if it works with a gmail address.
