### ISSUE TITLE
Feature: multiple popup windows, and ability to continue working in panes

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2810]
### Issue description

An ability to have multiple popup windows, which do not grab focus when they popup & let the user continue working on their work can help realize a notification system like https://github.com/rcarriga/nvim-notify. Currently nvim-notify can be used for this purpose, but with the limitation that notifications won't be visible to the user unless they are in a window with nvim open. Having it at tmux level makes more sense for a terminal based notification system, then user will get notification from wherever they are in tmux. nvim-notify is inspired from https://neovim.discourse.group/t/wip-animated-notifications-plugin/448

Perhaps it can be a flag or two with display popup to let pane programs continue, and not get the focus when it is launched. I think this could be possible after this commit: https://github.com/tmux/tmux/commit/93cc8df6929e0a7c63ce2f0403276a064c290adb

**Comment by nicm** [comment]
Not in the short term.

**Comment by nicm** [comment]
Allowing you to continue typing in other panes might be possible but multiple popups would be difficult, although it would let us show a menu for each popup which I would like.

**Comment by nicm** [comment]
Added to todo.
