### ISSUE TITLE
[Bug] : `zsh-autosuggestion` color not detect with tmux

### ISSUE THREAD

**Issue by ayoubelmhamdi** [tmux/tmux#2812]
when i use kitty only i get color of autosuggestion 
![kitty-1](https://user-images.githubusercontent.com/34358145/128751701-5dfbcf8c-244c-457c-bc96-d8f310638a9a.png)
but when i use tmux i can not get color of autosuggestion
![kitty-2](https://user-images.githubusercontent.com/34358145/128751771-7d93ddd9-2c8e-40ba-ac58-110e530c9fd1.png)
i test with `kitty` and `st (suckless-tools)` but color not work

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by ayoubelmhamdi** [comment]
if someone use `zsh autosuggestion ` and `tmux`,  you can confirm this bug

**Comment by ayoubelmhamdi** [comment]
when i search in `terminfo`, i don't have `tmux-256color`
```sh
$ ls /usr/share/terminfo/x | grep "tmux\|kitty"

xterm-kitty
```
but it fix with `set -g default-terminal xterm-kitty` in my `.tmux.conf` , instant of `tmux-256color`
