### ISSUE TITLE
copy-end-of-line not using copy-command 

### ISSUE THREAD

**Issue by gabriel376** [tmux/tmux#2813]
### Issue description

The `copy-end-of-line-and-cancel`, bound to `C-k` in `copy-mode`, does not use the option `copy-command`. It works as expected for `C-w` and `M-w` (`copy-pipe-and-cancel`).

### Info
Running `tmux 3.2a` on `Arch Linux`.
Output of `uname -sp && tmux -V && echo $TERM`:
```
Linux unknown
tmux 3.2a
tmux-256color
```

### Steps to reproduce
1. Set option `copy-command`: (from https://github.com/tmux/tmux/wiki/Clipboard)
```
tmux set -s copy-command 'xsel -i'
```
2. Enter `copy-mode`with `C-b [`
3. Select some text (`C-space`) and copy it with either `C-w`or `M-w`
4. Go to some other application and paste the data copied. It works as expected
5. Enter `copy-mode` again with `C-b [`
6. Go to some line and press `C-k` (`copy-end-of-line-and-cancel`)
7. Go to some other application and paste the data copied. It does not work as expected. The data was copied to tmux buffer (check with `C-b #`), but the `copy-command` was not executed.

Note: I did not tested other copy functions to check if they use `copy-command` or not.

**Comment by nicm** [comment]
Only copy-pipe without arguments uses `copy-command`.

**Comment by nicm** [comment]
Possibly they should, or should have a way to, however...

**Comment by nicm** [comment]
I have added `copy-pipe-` variants of the line copying commands which are used by default and to which `copy-command` applies. In OpenBSD now, will be in GitHub later.

**Comment by gabriel376** [comment]
Thank you!
