### ISSUE TITLE
Passthrough of data is affected by network quality?!

### ISSUE THREAD

**Issue by laggardkernel** [tmux/tmux#2814]
### Issue description

Update: The problem only happens when copying **large** amount of text.

I'm trying the OSC 52 yank support in tmux theses days. I find a problem that copying large chunk of text succeeds from my VPS over SSH. But it fails copying from my local virtual machine over SSH. I'm sure I've set same tmux config, ssh config, zsh config on both of the machines. And i'm sure text is copied with OSC 52 but not with clipboard syncing by SSH X forwarding. 

Besides, I've tested with [some osc 52 copy script](https://github.com/xPMo/OSC-52). The large chunk of text being copied successfully outside tmux but failed inside tmux.

Anyway. After some searching and testing, finally I targeted the cause to **network speed**.

When copy large chunk of text over SSH on my local machine, tmux issues "can't keep up" in the debug log. The virtual machine I use supports network simulation. After I changed the outgoing bandwidth from "Unlimited" to "Leased Line T1 (1.544 Mbps)" in the virtual machine settings panel, copying succeeded.

Why does copying large chunk of text fails over a good network but succeeds over a poor network? How network speed is related? 

```
# from local machine
1628533467.508775 /dev/pts/0: wrote 79360 bytes (of 235651)
1628533467.508792 /dev/pts/0: can't keep up, 156291 discarded

# from remote VPS
1628570310.352211 /dev/pts/0: wrote 235643 bytes (of 235643)
```

My test config

```
# vim:foldmethod=marker:foldlevel=0:shiftwidth=2
set-option -s set-clipboard on
set-option -g focus-events on

set-option -s escape-time 25
set-option -g history-limit 50000
set-option -g display-time 4000

# use zsh -f to skip loading user config
if-shell "command -v zsh >/dev/null 2>&1" \
  'set-option -g default-command "exec zsh -il -f"'
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 3.2a
* Platform (`uname -sp`): macOS 10.4, remote server Arch
* $TERM inside and outside of tmux: xterm-256color outside, tmux-256color inside
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Why would you quote bits of the logs but not attach them to the issue?

**Comment by laggardkernel** [comment]
@nicm [Here](https://www.dropbox.com/s/cvuyov7vyepxzjj/tmux-osc52-copy-failed.tar.gz?dl=0). A simple instructions is given in `info.txt`.

**Comment by nicm** [comment]
Yes, your terminal only manages to consume 80K which leaves the buffer size too large, whereas in the working case it manages to consume the entire buffer. Does this help? [x.diff.txt](https://github.com/tmux/tmux/files/6959797/x.diff.txt)

**Comment by nicm** [comment]
Actually try this instead, I think it is better: [y.diff.txt](https://github.com/tmux/tmux/files/6959823/y.diff.txt)

**Comment by laggardkernel** [comment]
Thanks. After compiling tmux with the patch `y.diff.txt` on my local virtual machine, the problem seems to be disappeared.

But I still don't understand why it formerly worked when SSH over my VPS but not on my local virtual machine.

**Comment by nicm** [comment]
Applied this now, thanks!
