### ISSUE TITLE
When there are 2 nvim windows opened and scrolling in one of them the content of the other disappear

### ISSUE THREAD

**Issue by mmngreco** [tmux/tmux#2818]
### Issue description

I use xterm as terminal and when I open two nvim windows inside tmux and I scroll over one of them the content of the other disappears. I've been experiencing this behavior for a while (at least two different versions of tmux), here's some related issues (https://github.com/neovim/neovim/issues/14434#issuecomment-846458263 and https://github.com/tmux/tmux/issues/2677#issuecomment-846458580)

https://user-images.githubusercontent.com/6231413/128976556-8c9f1b89-9876-4d77-8ece-0efd081d6ccb.mp4

I also tested using:

```bash
tmux -Ltest kill-server                                    
tmux -vv -Ltest -f/dev/null new
```

#### `tmux.conf`

```
unbind C-b
set -g prefix C-a
bind C-a send-prefix
set -g history-limit 30000
set -g base-index 1
setw -g pane-base-index 1
```

### Required information

Please provide the following information:

```bash
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 3.2a
xterm-256color
```
Logs:

- [tmux-client-23257.log](https://github.com/tmux/tmux/files/6966162/tmux-client-23257.log)
- [tmux-out-23259.log](https://github.com/tmux/tmux/files/6966163/tmux-out-23259.log)
- [tmux-server-23259.log](https://github.com/tmux/tmux/files/6966164/tmux-server-23259.log)

**Comment by nicm** [comment]
This looks like margins are not working, but you are using xterm. Did you configure xterm to emulate a vt3xx instead of vt4xx?

If so, this should be fixed in master.

**Comment by mmngreco** [comment]
@nicm Thank you for your quick response. 

I didn't change anything apart of the colors and fonts in `~/.Xresources`. I'm almost sure that I left it by default, as far I know it is vt100.

I've checked the man page and I've tried running `xterm +t`, but I've got the same issue.

How could I check that? and in case you know it, how could I change xterm to use vt3xx ?

**Comment by nicm** [comment]
What does:
~~~~
printf '\033[c\033[>c';cat
~~~~
show?

**Comment by mmngreco** [comment]
Here is:

```bash
$ printf '\033[c\033[>c';cat
^[[?64;1;2;6;9;15;16;17;18;21;22;28c^[[>41;353;0c  

```

**Comment by mmngreco** [comment]
The same as above, inside and outside tmux:

```bash
$ echo $TERM
xterm-256color
```

**Comment by nicm** [comment]
tmux is not xterm, `TERM` must be screen, screen-256color, tmux or tmux-256color.

**Comment by mmngreco** [comment]
I found the error, I have set in my `.bashrc` removing it all works propely! many thanks @nicm for your time.

**Comment by nicm** [comment]
Are you changing it in your shell profile? The best thing is to not do that, then in .Xresources:
~~~~
         XTerm*termName: xterm-256color
~~~~
And in .tmux.conf:
~~~~
set -g default-terminal 'tmux-256color'
~~~~
(Or `screen-256color` if your platform doesn't have `tmux-256color`).
