### ISSUE TITLE
Confirm-before does not seem to work from a script

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2819]
### Issue description

The following piece of code always prints ``@confirmation n`` even if I press 'y'.

```
#!/usr/bin/env zsh
tmux set-option @confirmation 'n'
tmux confirm-before -p "Save it as? (y/n)" "set-option @confirmation 'y'"
confirmation=$(tmux show-option @confirmation)
echo $confirmation

```

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux next-3.3.
* Platform (`uname -sp`) Darwin arm.
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color outside, tmux-256color inside.

**Comment by nicm** [comment]
Are you sure you are setting the option on the same session?

**Comment by reportaman** [comment]
I just double checked, I have just one session active on one client. So yes setting the same option on the same session.

**Comment by nicm** [comment]
You are not blocking the script to wait for `confirm-before` to finish...

**Comment by nicm** [comment]
I think we should make `confirm-before` and `command-prompt` block the invoking client like `run-shell` does by default.

**Comment by nicm** [comment]
You can do this in the meantime:
~~~~
#!/bin/sh
c=$$
echo $c
tmux set-option @confirmation 'n'
tmux confirm-before -p "Save it as? (y/n)" "set-option @confirmation 'y'; wait -S $c"
tmux wait $c
confirmation=$(tmux show-option @confirmation)
echo $confirmation

**Comment by reportaman** [comment]
@nicm That works only if the user enters ``y``, if he enters ``n`` then its a deadlock.

**Comment by nicm** [comment]
Good point, it needs a false case. But better to make it block, hold on a min.

**Comment by nicm** [comment]
Try this please: 
[tmux-confirm.diff.txt](https://github.com/tmux/tmux/files/6966690/tmux-confirm.diff.txt)

**Comment by reportaman** [comment]
@nicm Applied the patch, compiled & installed, checked the time stamp of ``/usr/local/bin/tmux`` & ``which tmux`` also points to it, killed and restarted tmux too, and restarted the machine.  It still hangs on ``n``.

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
