### ISSUE TITLE
tmux doesn't show feedback messages anymore

### ISSUE THREAD

**Issue by tessus** [tmux/tmux#282]
In older versions of tmux, I got a message in the status bar, if Iturned on/off mouse support or synchronize-panes.

I got something like
Set-option: synchronize-panes -> on
Set-option: synchronize-panes -> off

Now, I don't get any message at all.

**Comment by nicm** [comment]
It was only this message and they have been removed. You can do it with:

display-message '#{?synchronize-panes,on,off}'
