### ISSUE TITLE
Add missing information in syntax of select-pane

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2821]
### Issue description

``select-pane`` with ``-P`` option seems to be the only way of setting the pane styles of a different pane from one it is executed. Yet in the documentation ``-P`` is not mentioned in the definition of ``select-pane``.

I found out about ``select-pane -P`` from https://superuser.com/a/1181682

```
tmux select-pane -t <session>:<window>.<pane> -P 'bg=#36565e'
```

Current documentation of ``select-pane``:
```
     select-pane [-DdeLlMmRUZ] [-T title] [-t target-pane]
                   (alias: selectp)
             Make pane target-pane the active pane in its window.  If one of -D, -L, -R, or -U is used, respectively the pane
             below, to the left, to the right, or above the target pane is used.  -Z keeps the window zoomed if it was zoomed.
             -l is the same as using the last-pane command.  -e enables or -d disables input to the pane.  -T sets the pane
             title.

             -m and -M are used to set and clear the marked pane.  There is one marked pane at a time, setting a new marked
             pane clears the last.  The marked pane is the default target for -s to join-pane, move-pane, swap-pane and
             swap-window.
```

Are there more such undocumented switches?

### Required information

Please provide the following information:

* tmux version (`tmux -V`): next-3.3
* Platform (`uname -sp`) Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color & tmux-256color

**Comment by nicm** [comment]
-P has been superseded by the `window-style` option so it is no longer documented.

**Comment by reportaman** [comment]
@nicm They have different behavior. 

Let's say I have some default unfocussed and focussed window style set in my tmux conf file.

1. 
```
tmux set -p -t :.2 window-style 'bg=#36565e'
```
This sets the pane background color as ``bg=#36565e`` as long as it is not focussed. When it gets focussed, ``window-active-style `` color overrides this.

2.
```
tmux select-pane -t :.2 -P 'bg=#36565e'
```
This sets the pane background color as ``bg=#36565e`` both while focussed or unfocused, so ``window-active-style`` does not override this.

There is merit to 2) given a user might want to override this while still get ``window-active-style`` work in panes whose style has not been set explicitly with ``tmux select-pane`` when they get selected. I like it more than the behavior of 1.

**Comment by nicm** [comment]
-P just sets the two options to the same thing, nothing more:
~~~~
        style = args_get(args, 'P');
        if (style != NULL) {
                o = options_set_string(oo, "window-style", 0, "%s", style);
                ...
                options_set_string(oo, "window-active-styl\e", 0, "%s", style);
~~~~
It is deprecated and may be removed, don't use it.

**Comment by reportaman** [comment]
Ah I see, thanks!
