### ISSUE TITLE
Feature: make confirm-before tri-state or multi-state

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2822]
### Issue description

At times an operation can require multi-step interaction with the user, and at each step a script could wait for user input using commands like confirm-before. If the user wishes to cancel the query, i.e lets say when the user does not press either of: 'y' or 'n', it might be better served to interpret other key presses or just C-c as an intention of the user to cancel the operation.

Commands like confirm-before will be more expressive if they either pass their exit code to the calling shell, or expand user input in special string like ``%%`` of command-prompt (or both). Then the user can either tap into the exit code or the returned character to check if the user intended to cancel, just like the traditional prompt press ``y/n or any other key to cancel``, or ``y/n/a/c...``

At present confirm-before does not return correct exit code, but display-popup does, didn't check others...

**Comment by reportaman** [comment]
Oh actually that can be done with:

```
tmux set-option -g @confirmation 'n'
tmux command-prompt -k -p "Save it as? (y/n)" "set-option -g @confirmation '%1' ; wait-for -S promptdone"
confirmationcancel=$?
tmux wait-for promptdone
confirmation=$(tmux show-option -gvq @confirmation)
echo "$confirmation, canceled:$confirmationcancel"
tmux set-option -gu @confirmation
```

**Comment by nicm** [comment]
Does this make it return 0 or 1 for y/n? [x.diff.txt](https://github.com/tmux/tmux/files/6975043/x.diff.txt)

I don't think it should be tristate.

**Comment by reportaman** [comment]
@nicm It returns 0 for ``y``, 1 for rest of the keys. The thing is, given it returns 1 for ``n`` also, your change doesn't give more information to the developer from what they can already get from snippet above. It only reduces the lines of code.

✓ return code 0 for ``y``
✗ return code 1 for ``n``
✓ return code 1 for rest of the keys, or for keys like Esc/ C-c

Just this will make detecting "cancel" by looking at return code.
✓ return code 0 for ``n``

**Comment by nicm** [comment]
confirm-before is for yes/no questions, we are not changing it to do more than that.

**Comment by nicm** [comment]
If you want any key then use command-prompt, we should change it to block also which means you wouldn't need wait-for.

**Comment by nicm** [comment]
I've applied this so you get a return code from confirm-before and I have made command-prompt also block (without -b) so you do not need wait-for.

**Comment by reportaman** [comment]
Thanks!
