### ISSUE TITLE
Multiple OSC8 links per line are not displayed properly

### ISSUE THREAD

**Issue by SuperSandro2000** [tmux/tmux#2823]
### Issue description

Tmux has trouble displaying multiple OSC8 links in the same line correct. Normally my terminal prints them correct but in tmux the first on is displayed in the first line of the terminal

For this I commented everything out in my tmux config and killed the server to make sure nothing is causing issues.

I run the following command outside of tmux which worked flawlessly and I can click both links:
```ShellSession
$ printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\ A \e]8;;http://example.com\e\\This is a link\e]8;;\e\'
This is a link A This is a link
```

then I escaped the command and run the following which also still worked flawlessly:

```ShellSession
$ printf '\ePtmux;\e\e]8;;http://example.com\e\e\\This is a link\e\e]8;;\a\e\\'
This is a link
```

but when I combine two links it breaks:
```ShellSession
This is a link
$ printf '\ePtmux;\e\e]8;;http://example.com\e\e\\This is a link\e\e]8;;\a\e\\ A \ePtmux;\e\e]8;;http://example.com\e\e\\This is a link\e\e]8;;\a\e\\'
 A s is a link
```

![image](https://user-images.githubusercontent.com/7258858/129224865-cfdd5e01-73df-4ba7-bd36-c9437c21b444.png)

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.2a
* Platform (`uname -sp`): Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color and screen
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
tmux does not support these natively and if you use the bypass escape sequence you have to accept that tmux may issue over sequences that interfere with them.

**Comment by SuperSandro2000** [comment]
> tmux does not support these natively

Why does it not support them? I tend to use one of 4 terminals and all of them support it just tmux is blocking.

> if you use the bypass escape sequence you have to accept that tmux may issue over sequences that interfere with them.

But the problem is in tmux? This works like a charm outside and I am not fully sure if I use the bypass sequence correct. I couldn't find any good documentation on it.

**Comment by nicm** [comment]
Because I don't care about them, hardly any applications use them, and nobody else has finished implementing them.

If you use the bypass sequence to modify the terminal state then tmux doesn't know about your changes so it might change them or remove them.

**Comment by SuperSandro2000** [comment]
I want to use them to fancify issue/pull requests linkings in git commit messages to point to the right issue.

Why is it not possible for tmux to just forward all escape sequences it doesn't know? It would be a logical design decision for me and would avoid implementing all the sequences.

**Comment by nicm** [comment]
What happens if tmux forwards something it doesn't understand and then you detach and reattach? How does it put the state back the way it was?

**Comment by SuperSandro2000** [comment]
Can't it re-emit the same sequence at the same spot? That should yield the same state back. I don't think tmux needs to understand the sequence, it just needs to save it and keep it and probably for search it should ignore escape sequences.

**Comment by nicm** [comment]
What if later sequences have moved the text the sequence is meant to affect so the place it was originally written is no longer correct? Or the terminal size has changed or the pane has been moved to a new position? Or part of the content has been overwritten? Or you are scrolled up in the history?

It is impossible, tmux has to understand every escape sequence it receives in order to keep its copy of the terminal correct.

**Comment by nicm** [comment]
What if terminal A expects one sequence to do X but terminal B expects sequence Y? How does tmux translate? What if sending sequence X makes terminal B do something completely different?

**Comment by WSLUser** [comment]
OSC 8 is a spec written by the great egmontkob and is supported by many terminals, even on Windows. Tmux refusing to accept new sequences that terminals do does not seem a wise decision. https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

**Comment by SuperSandro2000** [comment]
> What if later sequences have moved the text the sequence is meant to affect so the place it was originally written is no longer correct? Or the terminal size has changed or the pane has been moved to a new position? Or part of the content has been overwritten? Or you are scrolled up in the history?

All this sounds like tmux should preserve the exact input sequences and replay them.

> It is impossible, tmux has to understand every escape sequence it receives in order to keep its copy of the terminal correct.

I am not asking about every. The most relevant ones are probably OSC7,8,52 and 1337.

> What if terminal A expects sequence X but terminal B expects sequence Y?

If you forward the sequences as is it is no longer tmux's problem. The difference would be visible in the TERM env most likely.

**Comment by nicm** [comment]
tmux has to understand every escape sequence that can modify the terminal so it can keep its own state correct.

**Comment by nicm** [comment]
Saying "its OK to pass through for some escape sequences" is very different from saying "tmux should pass through anything it doesn't understand". tmux needs to understand what is safe to pass through and what is not.

Even with OSC 8 - if you have two panes with applications that use the same ids, you would end up with links that are connected to the wrong cells.

tmux already supports OSC 7 and 52 itself.

This is all very much tmux's problem - part of tmux's job is to sort out what it is sent by applications inside and make it display sensibly on whatever terminal you attach it to.

**Comment by nicm** [comment]
Anyway, if you want to implement them you can finish the work in https://github.com/tmux/tmux/pull/2621, the remaining concerns are in this comment https://github.com/tmux/tmux/pull/2403#issuecomment-707674012.

**Comment by SuperSandro2000** [comment]
I would finish that if I had any prior experience in c.
