### ISSUE TITLE
Question: "Trim" char for excessive windows?

### ISSUE THREAD

**Issue by rodhash** [tmux/tmux#2825]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).
```sh
>> uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 3.2a
screen-256color
```

Hello,

I just have one question pls, what is this char used to "trim" the windows when too many are opened? By default it's ">".

I'm currently working on a theme and I'm trying to customize this char.

Here a print screen of "normal" amount of window:
![image](https://user-images.githubusercontent.com/29671981/129462208-ec0d8efc-6227-4232-b9e2-9863a788d267.png)

And here this ">" char (after window 4) when too many are opened and doesnt fit:
![image](https://user-images.githubusercontent.com/29671981/129462217-735b0a7e-03e2-4375-bbc3-2bc5434a6d9d.png)

I couldn't find much reference about it.. Is this something I can change? 

Thank you

**Comment by nicm** [comment]
The default is < and >, so you have already changed the default. You can configure it by changing status-format[0] (it is part of the list definition).

**Comment by rodhash** [comment]
I don't think we are talking about the same char, I'm referring to the one after window 4.. this one shows up only if we have too many window opened.

I tried many themes and they all suffer the same behavior, when too many window are opened, this simple ">" shows up as in my print screen.

**Comment by nicm** [comment]
Oh yes you didn't change it. The answer is the same anyway.

**Comment by rodhash** [comment]
Ok thanks, works as expected now.
