### ISSUE TITLE
Cursor in popup window flickers when current pane has text printing in it -- for some applications

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2826]
### Issue description
Let's say focus is a pane that is printing to stdout & we open popup while in that pane (as an example I use https://github.com/sainnhe/tmux-fzf ``<tmuxprefix>Shift-f``). The cursor in the popup flickers as text prints in the current pane -- for some applications like visualizer of https://github.com/ncmpcpp/ncmpcpp. If I close the popup and reopen it while focus is on a pane that does not have output being printed to stdout, I see no flickering of cursor inside popup. This might be a ncmpcpp issue or maybe not, it does need a review.

Logs:

https://drive.google.com/file/d/1G5PthFttVx1nWjhVfXofQ30JSvIbFazQ/view?usp=sharing, https://drive.google.com/file/d/1ffD2moL9zDo9r_GTxDLvIPITc0-Jivc-/view?usp=sharing, https://drive.google.com/file/d/1tvYw6SRmfQ9DwTVN-LSkqjYLT2MR2ZSg/view?usp=sharing 

Demo:

https://user-images.githubusercontent.com/71736629/129472017-8633aa67-bd1b-4c06-9772-5bfd5c015d83.mp4

### Required information

Please provide the following information:

* tmux version (`tmux -V`): next-3.3.
* Platform (`uname -sp`) Darwin arm.
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color inside, tmux-256color outside.

**Comment by nicm** [comment]
The cursor has to be moved and possibly turned off to draw stuff in other panes, if that takes a while then it will flicker.

**Comment by reportaman** [comment]
@nicm The cursor does not flicker while focus is in a different pane, or if the focus is in popup opened while in other pane. I have a longer video that shows what I am saying, which shows when cursor flickers and when it doesn't:


https://user-images.githubusercontent.com/71736629/129493314-c94657d8-28f7-43bb-94b7-3518c3ed117c.mp4

**Comment by nicm** [comment]
Does this make any difference:
~~~~
--- a/popup.c
+++ b/popup.c
@@ -553,6 +553,7 @@ popup_job_update_cb(struct job *job)
        if (size == 0)
                return;

+       tty_sync_start(&c->tty);
        if (pd->md != NULL) {
                c->overlay_check = menu_check_cb;
                c->overlay_data = pd->md;

**Comment by reportaman** [comment]
@nicm No, still the same.

**Comment by nicm** [comment]
Well this is wrong anyway so I have changed it.

**Comment by nicm** [comment]
Try this please:
~~~~
--- a/screen-write.c
+++ b/screen-write.c
@@ -197,6 +197,7 @@ screen_write_initctx(struct screen_write_ctx *ctx, struct tty_ctx *ttyctx,
                }
        }

+       sync = 1;/* XXX */
        if (ctx->wp != NULL &&
            (~ctx->flags & SCREEN_WRITE_SYNC) &&
            (sync || ctx->wp != ctx->wp->window->active)) {

**Comment by nicm** [comment]
Ah actually I see why it is working depending on where the active pane is, we only start to sync if drawing a pane that isn't active, which doesn't take into account overlays.

**Comment by reportaman** [comment]
@nicm "Well this is wrong anyway so I have changed it." does that mean you wanted me to remove the first patch before applying the second? I applied the second, and don't see the cursor flickering I reported anymore (though the tested binary has both your patches). 

> Ah actually I see why it is working depending on where the active pane is, we only start to sync if drawing a pane that isn't active, which doesn't take into account overlays.

Nice, does that mean I wait for a 3rd more elaborate patch? (given you also have ``/* XXX */`` as a comment).

**Comment by nicm** [comment]
You can try this instead: [y.diff.txt](https://github.com/tmux/tmux/files/6998133/y.diff.txt)

I am not that happy about this however. The idea is we do not want to sync all the time, because there is no point in sending 10 bytes or so to turn sync on and off when we just want to write to the active pane. But this is exactly what we are doing now for updates of a popup (both with and without my previous change which I am going to revert). So I think it needs to be more clever and only sync if 1) updating any pane but not the popup itself if a popup is enabled or 2) updating a nonactive pane if there is no popup.

**Comment by nicm** [comment]
Actually without my last change this is OK, since it only syncs if in a pane, not an overlay.

**Comment by nicm** [comment]
OK I think this should work, please try this without any of the other changes: [tmux-sync.diff.txt](https://github.com/tmux/tmux/files/6998304/tmux-sync.diff.txt)

**Comment by nicm** [comment]
Hmm actually, that means we don't sync in an overlay and we probably do want to for big commands...

**Comment by nicm** [comment]
Try this one instead please, I think this works in all three cases: [tmux-sync2.diff.txt](https://github.com/tmux/tmux/files/6998358/tmux-sync2.diff.txt)

**Comment by reportaman** [comment]
@nicm I just tried your latest patch alone tmux-sync2.diff.txt, that works too. Before this I had tried y.diff.txt, that had worked too, didn't get a chance to try tmux.sync.diff.txt.

**Comment by nicm** [comment]
I have applied this to OpenBSD now, will be in GitHub later. Thanks!
