### ISSUE TITLE
server segfaults when remain-on-exit is enabled and in control mode when the processes die (or do not start)

### ISSUE THREAD

**Issue by bensherman** [tmux/tmux#2828]
### Issue description

This is a deeply simplified example of a larger issue, but if I run the following command on a recent linux machine, tmux appears to segfault:
`tmux -C new foobar ';' setw -g remain-on-exit on`

If I run strace under it, the strace shows the segfault:

```[pid 1896733] write(5, "1629159395.339666 @1 active pane"..., 45) = 45
[pid 1896733] poll([{fd=4, events=POLLIN}, {fd=9, events=POLLIN}, {fd=6, events=POLLIN}, {fd=8, events=POLLIN}, {fd=10, events=POLLOUT}], 5, 3) = 2 ([{fd=4, revents=POLLIN}, {fd=10, revents=POLLOUT}])
[pid 1896733] writev(10, [{iov_base="%begin 1629159395 257 0\n%end 162"..., iov_len=284}], 1%begin 1629159395 257 0
%end 1629159395 257 0
%begin 1629159395 258 0
%end 1629159395 258 0
%begin 1629159395 259 0
%end 1629159395 259 0
%begin 1629159395 260 0
%end 1629159395 260 0
%window-add @0
%sessions-changed
%session-changed $0 0
%session-window-changed $0 @1
%window-add @1
) = 284
[pid 1896733] write(5, "1629159395.339947 control_write_"..., 84) = 84
[pid 1896733] write(5, "1629159395.339998 control_check_"..., 64) = 64
[pid 1896733] write(5, "1629159395.340049 control_write_"..., 98) = 98
[pid 1896733] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x120} ---
[pid 1896731] <... poll resumed> )      = 1 ([{fd=7, revents=POLLIN|POLLHUP}])
[pid 1896733] +++ killed by SIGSEGV +++
getpid()                                = 1896731
```

The more complicated version of this is that I am using overmind, which uses tmux, and this segfault started hitting us when users were stopping processes with sigint(^C). This sends overmind into a cleanup mode, but I think something bad is happening when the remian-on-exit flag is enabled.  This started with the most recent released version, and is happening across platforms. The full issue from overmind is at https://github.com/DarthSim/overmind/issues/115. I have been trying to replicate this without overmind and as little config as possible, and this issue is what I was able to reduce it to. I am almost positive this is directly related, but would like to be corrected if I'm wrong.

On an earlier version of tmux, this is what I get (and expect):
```
$ ./tmux -V
tmux 2.9a
$ ./tmux -C new foobar ';' setw -g remain-on-exit on
%begin 1629160801 235 0
%end 1629160801 235 0
%begin 1629160801 236 0
%end 1629160801 236 0
%window-pane-changed @0 %0
%window-add @0
%session-window-changed $0 @0
%sessions-changed
%session-changed $0 0
%output %0 bash: foobar: command not found\015\012
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux next-3.3` compiled with a minor change to force logging, but this is present in the release 3.2a
* Platform (`uname -sp`): `Linux unknown` this is recent debian release - `uname -a` output is `Linux ip-10-212-4-43 4.9.0-16-amd64 #1 SMP Debian 4.9.272-2 (2021-07-19) x86_64 GNU/Linux`
* $TERM inside and outside of tmux (`echo $TERM`): outside: xterm-256color inside: screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`). Logs attached.

[tmux-server-1898757.log.gz](https://github.com/tmux/tmux/files/6996126/tmux-server-1898757.log.gz)
[tmux-client-1898755.log.gz](https://github.com/tmux/tmux/files/6996127/tmux-client-1898755.log.gz)

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/6997788/x.diff.txt)

**Comment by bensherman** [comment]
That diff worked, I can no longer get it to fail on the short command nor in the overmind scenario - thank you for the quick response!

**Comment by nicm** [comment]
Great - applied to OpenBSD now, will be in GitHub later. Thanks!
