### ISSUE TITLE
tmux attaches to every session and dies

### ISSUE THREAD

**Issue by tomoguisuru** [tmux/tmux#283]
I'm having an issue after running `brew install tmux` it installed the latest 2.1 version but seems to be attaching tmux automatically to every new terminal session.

I have no special configurations installed and this really wouldn't be an issue except I'm getting this error, `no server running on /private/var/folders/w8/3fz9xvdd5fz7p2tft5t0bcs40000gn/T/tmux-501/default` on any new session and then the console automatically closes. There is currently no way for me to remove tmux through the console since it closes automatically since I've closed all previous sessions where tmux was not installed

This is HUGE issue and is a major bug. TMUX should never start automatically unless configured to do so

**Comment by tomoguisuru** [comment]
As a side note, since I couldn't uninstall tmux using the console, I had to open finder, select go and paste in `/usr/local/Cellar/` and move the tmux folder into the trash to get my console working again.

tmux took over and died on both iterm and terminal

**Comment by nicm** [comment]
Looks like GitHub lost my reply to this. Anyway:

tmux will never start automatically, you have configured it to do so somehow, either by making it your shell, or running it from .profile, or something else.
