### ISSUE TITLE
Commented lines does not show up in nested tmux session

### ISSUE THREAD

**Issue by nippyin** [tmux/tmux#2830]
Operating system/version: RHEL 8.4
Terminal name/version: Kitty
TERM environment variable screen

Steps to reproduce

Within tmux nested session when Using NVIM, try to open file /etc/chrony.conf I don't see commented lines. see below screen shot.
![image](https://user-images.githubusercontent.com/41337248/129818037-198cd7f2-65aa-4f12-9b8a-d944daffe9aa.jpeg)

If at the same nested session I to open same file using vi editor, as we can see it does show all lines.

![image](https://user-images.githubusercontent.com/41337248/129817972-cb1944c0-a6b4-43fc-b1c4-1d3e5fa3be44.jpeg)

Vim

VIM - Vi IMproved version 8.0.1763

Expected behavior

Expect to see all lines of config file, as it does work within single tmux session as show in the screen shot below.

![image](https://user-images.githubusercontent.com/41337248/129818007-655d9d4b-164e-4a80-b986-89c25c6d3c28.jpeg)

Actual behavior

Nested tmux session nvim does not show all lines of a file.
### Required information

Please provide the following information:

* tmux version (`tmux -V`).  tmux 2.7
* Platform (`uname -sp`). Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). screen
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Does this still happen with master or tmux 3.2a?

**Comment by nippyin** [comment]
Nope it just works fine. Only thing is compiling the code on each server is a tough job as 3.2a is not yet available on repo. Do you know easy way to update tmux to 3.2a from package manager ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nicm** [comment]
Make a static build?
