### ISSUE TITLE
pane-colours are not inherited by new panes or windows from the global pane-colours

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2831]
### Issue description

Setting global background/foreground window-style like in code below works well, any new windows+panes inherit the global background+foreground style. But the same is not true for the new feature 'pane-colours'. 

a) works:
```
tmux set -g window-style "bg=<background>, fg=<foregroun>"
tmux set -g window-active-style "bg=<background>, fg=<foregroun>"
```

b) doesn't work:
```
tmux set -g pane-colours\[1\]  "<color1>"
```

The newly created panes/windows still display old colors for ``pane-colours[0:15]``.

> As a sidenote, popups seem to inherit global pane-colours but don't seem to inherit the background+foreground colors set in a) I guess you are going to add a separate popup style & pane-colours option?

### Required information

Please provide the following information:

* tmux version (`tmux -V`). next-3.3.
* Platform (`uname -sp`) Darwin arm.
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color, tmux-256color.

**Comment by nicm** [comment]
Did you set a non-global pane-colours as well? Only the complete option is inherited, it won't merge the options (global and window and pane - the most specific wins entirely).

**Comment by reportaman** [comment]
@nicm No I did not set any non-global options. Here's a video for you. In the video, I do ``ls`` to print some sample colored string. Directories use color 12. I change the color 12 in the global pane colors and then create a new horizontal pane & do ls again in those panes. The newly created panes still use old RGB value for color 12. Each time I create the new pane, I have to manually perform a color change again in that pane to apply the global pane colors again.


https://user-images.githubusercontent.com/71736629/130187157-cb8ab4f8-db57-493b-8bb6-67dfc54431c2.mp4

**Comment by nicm** [comment]
This should be fixed now, please try it when GitHub syncs up.
