### ISSUE TITLE
Question: Keybinding Alt followed by character like 'c' doesn't work, but Alt followed by arrow keys work.

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2832]
### Issue description

Binding ``M-Down`` to run some script works well, but binding ``M-c`` does not. What setting could I be missing? Pressing ``M-c`` actually prints ``ç`` in a login-shell inside tmux.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 3.3-next
* Platform (`uname -sp`). Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color outside, tmux-256color inside

**Comment by reportaman** [comment]
What is weird about this problem is that it only doesn't show up in WezTerm 
(for which I use https://raw.githubusercontent.com/wez/wezterm/main/termwiz/data/wezterm.terminfo), the rest of the terminal emulators print ``ç``. The comment at https://github.com/kovidgoyal/kitty/issues/123#issuecomment-329344050 suggests this could be a macOS problem, will check and update here.

**Comment by nicm** [comment]
This is not a problem with tmux, it is a problem with your terminal.

**Comment by reportaman** [comment]
@nicm Yep, you are correct. I was able to successfully make this work in iTerm2 using the Esc+ setting shown at https://github.com/alacritty/alacritty/issues/1467, and Alacritty still doesn't support there is an open issue on it: https://github.com/alacritty/alacritty/issues/62.
