### ISSUE TITLE
Use Ctrl+Tab for switching windows 

### ISSUE THREAD

**Issue by BarkeH** [tmux/tmux#2833]
**Description**
Would it be possible to set Ctrl+Tab to switch between windows without using a terminal emulator such as xterm?

`bind-key -n C-Tab next-window` works in xterm but does not work in the regular terminal.

**Required Information**
* tmux version: 3.1c
* Platform: Linux x86_64(Fedora Desktop)
* $TERM: Inside = tmux-256color Outside = xterm-256color

**Comment by nicm** [comment]
xterm is not a regular terminal?

**Comment by BarkeH** [comment]
xterm isn't reflective of terminals that most people use and Ctrl+Tab only seems to work while using xterm and not anywhere else.

**Comment by nicm** [comment]
Maybe you should be talking to the developers of whatever mystery terminal most people are using?

**Comment by nicm** [comment]
Is it gnome-terminal? I am pretty sure it doesn't support `C-Tab` or any extended keys by default, but I'm not sure if it is possible to configure it to.

What do you see if you run `printf '\033[>4;1m';cat` outside tmux and then press C-Tab?

**Comment by YoloClin** [comment]
@BarkeH and I have solved the issue locally. It's hacky, but for those playing at home we ended up rebinding next/previous to F1/F2, then had our terminal emulator (Kitty) rewrite ctrl+tab/ctrl+shift+tab to call those keycodes. It's not elegant, but it works.

tmux conf:

```
bind-key -n F1 next-window
bind-key -n F2 previous-window
```

kitty conf:

```
map ctrl+tab              send_text all \033OP
map ctrl+shift+tab        send_text all \033OQ
```

@nicm please be aware your tone is offputting. You have no idea if who you're dealing with is a Unix veteran or a newbie, and either way sarcastic/aggressive responses really aren't a nice way to treat anybody. 

Feel free to close this thread.

**Comment by nicm** [comment]
Opening issues without logs and without basic information so I have to play guessing games is fairly offputting also.
