### ISSUE TITLE
Unable to inherit environment variables from parent process (kitty)

### ISSUE THREAD

**Issue by dhruvmanila** [tmux/tmux#2834]
### Issue description

So, I have a use case where I need to manipulate kitty programmatically (https://sw.kovidgoyal.net/kitty/remote-control/). It sets an environment variable (`KITTY_LISTEN_ON`) which needs to be used to send the command using the `kitty` CLI tool.

Now, when I open a new tmux session, the environment variable is correctly set. Then, I will detach and reopen the kitty terminal, the variable will be updated to listen on the new socket. But, after I attach the tmux session, the variable will contain the old value instead of the new one.

### Steps to reproduce

1. Open kitty and `echo $KITTY_LISTEN_ON` (output: `unix:/tmp/mykitty-4063`)
2. Create a new tmux session with `tmux -vv new`
3. `echo $KITTY_LISTEN_ON` in tmux (output: `unix:/tmp/mykitty-4063`)
4. Detach the session and restart the kitty terminal
5. `echo $KITTY_LISTEN_ON` (output: `unix:/tmp/mykitty-4644`)
6. Attach to the previous session `tmux attach`
7. `echo $KITTY_LISTEN_ON` (output: `unix:/tmp/mykitty-4063`)

Here, the variable is still pointing to the old value which means if I try to send commands to kitty, it will fail. Looking at the man page, I have tried another solution:

```tmux
set-option -g update-environment KITTY_LISTEN_ON
```

According to the man page on the above option:
> Set list of environment variables to be copied into the session environment when a new session is created or an existing session is attached.

This should basically solve my issue but it does not. Performing the same steps as above I get the same results. Although, when I create a new pane/window the variable is correctly set to the new value. Without the `update-environment` option, creating a new pane/window gives the same old value.

The docs mentions that the variables will be copied into the session environment when an existing session is attached but that does not happen or I must have misunderstood what it actually means.

### Required information

Please provide the following information:

* tmux version (`tmux -V`):  `tmux 3.2a`
* Platform (`uname -sp`): `Darwin i386`
* $TERM inside and outside of tmux (`echo $TERM`): `xterm-kitty`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
tmux cannot modify environment variables in programs that are already started. You will need to do it from inside the shell (you can get the updated value with `tmux showenv`);

**Comment by dhruvmanila** [comment]
Right, understood. So, if possible, can you tell me if there's an easy way to do that? For example, in a session with multiple panes and windows, updating the value for each one of them would become tedious. I know that I need to use `source <(tmux showenv -s)` to update the value, but that would only do it for the current pane.

**Comment by dhruvmanila** [comment]
I am also a bit confused regarding what the man page says. Does it mean it only sets the environment variables internally and not for the already started processes? So, for every process started later on (creating panes/windows), the variables will be correctly set.

**Comment by nicm** [comment]
Put it in your shell prompt. I probably wouldn't source everything but just set the one you want.

Yes there is no way for tmux to modify other running processes, only new ones get the updated environment.

**Comment by dhruvmanila** [comment]
Ok, understood. Thanks for the quick response. I will close this issue now.
