### ISSUE TITLE
select-window should create window if not present

### ISSUE THREAD

**Issue by ffaf1** [tmux/tmux#2835]
### To replicate

- open a fresh tmux session
- type `tmux select-window -t 8`
- you will get an error (`can't find window: 8`)

### My suggestion

- have tmux run `new-window` if the specified window is not present

This behaviour could be toggled by an option (e.g. `-c` for force create).

### Additional suggestion

This should also apply to `join-pane -d …`. If the window is not present, create it. 
### Required information

Please provide the following information:

* tmux version: 3.1c
* Platform: Debian stable (bullseye).
* $TERM: screen-it/rxvt-unicode-256-color.

**Comment by nicm** [comment]
This is already on the todo list, although I am not entirely sold because it is so trivial to script.

**Comment by ffaf1** [comment]
>  I am not entirely sold because it is so trivial to script.

[That is what I did indeed](http://ariis.it/static/articles/tmux-scripts/page.html). I filed the issue because I think it pertains to base UX. This is of course debatable, but if it is already on the todo list, it means there are other user who fancied the feature.

**Comment by nicm** [comment]
OK well it may be implemented at some point :-).
