### ISSUE TITLE
Opening choose-tree in a popup window

### ISSUE THREAD

**Issue by sriramkandukuri** [tmux/tmux#2836]
Hi,

Is it possible to open choose-tree in a popup window?

Thanks & Regards,
Sriram.K

**Comment by nicm** [comment]
No. Not sure what the point would be, it already automatically zooms the
active pane?

**Comment by sriramkandukuri** [comment]
Yes it does zoom the pane and opens choose-tree.

But if it can open in popup, it would be good as per user experience point of view

Thanks & Regards,
Sriram.K

**Comment by nicm** [comment]
But what is the difference to the user between a popup and a zoomed pane
except the popup is smaller?

**Comment by nicm** [comment]
I don't object to having the ability to open modes in popups (although I do not expect it to be implemented any time soon), I'm just not sure what extra benefit it offers.

**Comment by sriramkandukuri** [comment]
ok Thanks
