### ISSUE TITLE
can no longer specify command argument as string by surrounding it with braces

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2839]
### Issue description

Since a recent commit, we can no longer specify a command argument as a string by surrounding it with braces.

To reproduce, run this shell command:

    tmux -Lx -f<(cat <<'EOF'
        set -g -F status-style 'bg=blue'
        bind C-N if -F '#{window_end_flag}' {} { next }
    EOF
    )

Expected: The status line is blue.
Actual: The status line is green.

### Required information

 - `$ tmux -V`: tmux next-3.3, commit 4d3367e9657002c4b68867c8d58e2f5b7ae90612
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/tmp/tmux.conf`:
 [tmux-client-43768.log](https://github.com/tmux/tmux/files/7025733/tmux-client-43768.log)
 [tmux-out-43770.log](https://github.com/tmux/tmux/files/7025734/tmux-out-43770.log)
 [tmux-server-43770.log](https://github.com/tmux/tmux/files/7025735/tmux-server-43770.log)
 - regression introduced in: 84955e3d62691a67b2f1e58ad219615ad92e55bf
 - [`$ tmux info`](https://github.com/tmux/tmux/files/7025736/tmux.info.txt)

**Comment by lacygoill** [comment]
> we can no longer specify a command argument as a string by surrounding it with braces.

Actually, I'm not sure about that.  I haven't tested the key binding.  All I know is that all my config is ignored since a commit pushed yesterday.  I *guess* there is some syntax error in a key binding which causes tmux to discard the whole config.

**Comment by nicm** [comment]
{} must contain valid tmux commands and it is not valid if it is empty. It should complain about this.

**Comment by nicm** [comment]
I know it doesn't but it should.

**Comment by nicm** [comment]
This will allow empty command lists again:
~~~~
--- cmd-parse.y 21 Aug 2021 14:06:17 -0000      1.38
+++ cmd-parse.y 21 Aug 2021 17:00:05 -0000
@@ -808,6 +808,10 @@ cmd_parse_build_command(struct cmd_parse
                        break;
                case CMD_PARSE_COMMANDS:
                        cmd_parse_build_commands(arg->commands, pi, pr);
+                       if (pr->status == CMD_PARSE_EMPTY) {
+                               cmd_append_argv(&argc, &argv, "");
+                               break;
+                       }
                        if (pr->status != CMD_PARSE_SUCCESS)
                                return (NULL);
                        s = cmd_list_print(pr->cmdlist, 0);
~~~~
TBH I am not sure there is any point in ever complaining about empty commands, maybe we should just always treat them as a null command...

**Comment by nicm** [comment]
I have changed this so tmux doesn't care about empty commands and just treats them as nothing everywhere, like `if-shell` already did. Please let me know if you still see problems after GitHub syncs up.
