### ISSUE TITLE
cannot use braces to specify shell command argument

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2841]
### Issue description

Since a recent commit, we can no longer use braces to specify a shell command argument.

To reproduce, run this shell command:

    tmux -Lx -f <(cat <<'EOF'
        bind x split-window { echo 'test' }
    EOF
    )

Expected: no syntax error is given.
Actual: This syntax error is given:

    /tmp/tmux.conf:1: unknown command: echo

I think it should work because `man tmux` says that `split-window` accepts a shell command as argument:

    split-window [-bdfhIvPZ] [-c start-directory] [-e environment] [-l size]
            [-t target-pane] [shell-command] [-F format]
                             ^-------------^

And a command argument may be specified as a string surrounded by quotes or braces:

   > Command arguments may be specified as strings surrounded by single (')
   > quotes, double quotes (") or braces ({}).

Quotes still work:

    tmux -Lx -f <(cat <<'EOF'
        bind x split-window "echo 'test'"
        #                   ^           ^
    EOF
    )

But not braces.  They were working fine until recently.

### Required information

 - `$ tmux -V`: tmux next-3.3, commit 921991c98d6fd596c958b07b5f5aba7c434e8f9f
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/tmp/tmux.conf`:
 [tmux-client-134745.log](https://github.com/tmux/tmux/files/7026139/tmux-client-134745.log)
 [tmux-out-134747.log](https://github.com/tmux/tmux/files/7026140/tmux-out-134747.log)
 [tmux-server-134747.log](https://github.com/tmux/tmux/files/7026141/tmux-server-134747.log)
 - regression introduced in: 84955e3d62691a67b2f1e58ad219615ad92e55bf
 - [`$ tmux info`](https://github.com/tmux/tmux/files/7026138/info.txt)

**Comment by nicm** [comment]
No, in 3.2 {} was changed so that the contents must be valid tmux config syntax (not shell syntax) and it is now changing so it must be actual tmux commands.

Use normal quoting for shell scripts.

**Comment by lacygoill** [comment]
> Use normal quoting for shell scripts.

OK but this is going to be tricky:

    bind u capture-pane -b urlscan \; \
           split-window -l 10 {
                  tmux showb -b urlscan | \
                  urlscan --no-browser | \
                  head -c -1 | \
                  ifne urlscan --compact \
                          --dedupe \
                          --nohelp \
                          --regex "(http|ftp)s?://[^ '\">)}\\]]+" \
                ; tmux deleteb -b urlscan
            }

**Comment by nicm** [comment]
Maybe:
~~~~
bind u {
    capture-pane -b urlscan
    split-window -l 10 "
       tmux showb -b urlscan | \
       urlscan --no-browser | \
       head -c -1 | \
       ifne urlscan --compact \
                    --dedupe \
                    --nohelp \
                    --regex \"(http|ftp)s?://[^ '\\\">)}\\]]+\";
       tmux deleteb -b urlscan
    "
}
~~~~
I did write a form of {} for shell scripts at one point, maybe I will try to dig it out again.

**Comment by lacygoill** [comment]
> Maybe:

Yes, it seems better than what I came up with:

    bind u capture-pane -b urlscan \; \
           split-window -l 10 "
                  tmux showb -b urlscan | \
                  urlscan --no-browser | \
                  head -c -1 | \
                  ifne urlscan --compact \
                          --dedupe \
                          --nohelp \
                          --regex \"(http|ftp)s?://[^ '\\\">)}\\]]+\" \
                ; tmux deleteb -b urlscan
            "

It was not that difficult to fix;  it's just the [leaning toothpick syndrome](https://en.wikipedia.org/wiki/Leaning_toothpick_syndrome) which worries me:

    # before
    --regex \"(http|ftp)s?://[^ '\">)}\\]]+\" \
                                 ^

    # after
    --regex \"(http|ftp)s?://[^ '\\\">)}\\]]+\" \
                                 ^^^

Plus we lose syntax highlighting; before, only the regex was highlighted as a string (in Vim); now everything is highlighted as a string.

But I can see it's working as intended according to [this issue](https://github.com/tmux/tmux/issues/2737):

   > Configuration file parsing has changed slightly: the contents of the new {} syntax introduced in 3.1 must now be valid tmux command syntax; and to allow formats to be annotated, strings given with quotes may now contain newlines (leading spaces and comments are stripped).

It's a bit weird that it was still working up until now though.  Also, I'm not sure it's clearly documented in the manpage.  I'll have a look later; if it's not, I'll try to suggest a patch to improve the documentation.

---

> I did write a form of {} for shell scripts at one point, maybe I will try to dig it out again.

It would be nice, but TBH it's not urgent.  There are probably more important things to fix/implement.  I only have 1 such key binding in all my config.  Not a big deal.

**Comment by nicm** [comment]
It was working because you happened to have a bit of shell script that matched tmux syntax even though it was not actual tmux commands. Now it actually has to be tmux commands.
