### ISSUE TITLE
Popup window width is off by one column with -w 100%

### ISSUE THREAD

**Issue by bfrg** [tmux/tmux#2843]
### Issue description

Popup window width is wrong when `-w 100%` is specified. Setting the width manually using the value of `$COLUMNS` doesn't work either. The popup window is always one column shorter than the terminal width (_cf._ tmux's statusbar in the screenshot).

![screenshot-2021-08-22_195959](https://user-images.githubusercontent.com/6266600/130365269-f61815e0-7faf-4b1a-8d33-48049ba63eec.png)

### Required information

* tmux version `next-3.3`, commit 1dec1ca1
* Platform: Linux
* `$TERM` is set to `screen` inside and `xterm-256color` outside of tmux

**Comment by nicm** [comment]
Well spotted. This should be fixed in OpenBSD now, will be in GitHub later. Thanks!
