### ISSUE TITLE
crash when sourcing file from braces passed to "if-shell" command

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2845]
### Issue description

Tmux crashes when we source a file from inside braces passed as argument to the `if-shell` command.

To reproduce, run this shell command:

    tmux -Lx -f <(cat <<'EOF'
        if '0' { source '/path/to/file' }
    EOF
    )

### Required information

 - `$ tmux -V`: tmux next-3.3, commit 95a374d7d20dde938563a9f92c8ffc1e25bd4050
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs from `$ tmux -vv -Lx -f/dev/null`:
[tmux-client-37208.log](https://github.com/tmux/tmux/files/7033571/tmux-client-37208.log)
[tmux-server-37210.log](https://github.com/tmux/tmux/files/7033572/tmux-server-37210.log)
 - [backtrace](https://github.com/tmux/tmux/files/7033570/backtrace.txt) from `$ gdb -n -ex 'thread apply all bt full' -batch ./tmux ./core`:
 - regression introduced in: 95a374d7d20dde938563a9f92c8ffc1e25bd4050

**Comment by nicm** [comment]
Does this fix it?
~~~~
--- a/arguments.c
+++ b/arguments.c
@@ -497,11 +497,13 @@ args_make_commands_now(struct cmd *self, struct cmdq_item *item, u_int idx)

        state = args_make_commands_prepare(self, item, idx, NULL, 0, 0);
        cmdlist = args_make_commands(state, 0, NULL, &error);
-       args_make_commands_free(state);
        if (cmdlist == NULL) {
                cmdq_error(item, "%s", error);
                free(error);
        }
+       else
+               cmdlist->references++;
+       args_make_commands_free(state);
        return (cmdlist);
 }

**Comment by nicm** [comment]
This is right, so I have applied it, but let me know if it fixes your problem. Thanks!

**Comment by lacygoill** [comment]
The patch fixes the issue entirely.  Thank you very much for the quick fix.

**Comment by nicm** [comment]
Great, thanks!
