### ISSUE TITLE
Question command tmux starts a new server? when one is already running

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2846]
### Issue description

So far I assumed that running the command ``tmux`` in a new tty starts a new session in an existing server, but it doesn't  work that way always. At times it creates a new server...

Steps to reproduce:
1. Open 1st new terminal tab and run ``>>tmux``
2. Open 2nd terminal tab and run ``>>tmux -L new-socket``
3. Open 3rd terminal tab
4. Jump to 1st terminal tab and run ``>>tmux kill-server``
5. Jump to 3rd terminal tab and run ``>>tmux``

At step-5, one would assume that it would just create a new session in new-socket, but it actually creates a new server & starts a session in it. Is this the expected behavior? Like when tmux does not find a ``default`` socket, it creates one? I was assuming tmux would open a session in only running server...

This happens even if one runs the following sequence in different ttys: 1) ``tmux -L new-socket ``, 2) ``tmux``. I think 2) creates a ``default`` socket.

### Required information

Please provide the following information:

* tmux version (`tmux -V`) next-3.3.
* Platform (`uname -sp`) Darwin Arm.
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color, tmux-256color.

**Comment by nicm** [comment]
How would it know to use `new-socket` if you don't tell it?

**Comment by reportaman** [comment]
@nicm Was thinking tmux somehow knows if there is an existing server running & creates new session in that. From your question it seems thats not how it works.

**Comment by nicm** [comment]
No, it uses the socket you tell it.
