### ISSUE TITLE
Bad argument parsing

### ISSUE THREAD

**Issue by netei** [tmux/tmux#285]
When writing  tmux set-buffer '-M bar' , 

I get : 

tmux: unknown option -- M
usage: set-buffer [-a] [-b buffer-name] [-n new-buffer-name] data

However, when using quotes, the arguments should be seen as ['-M bar'] and not ['-M', 'bar']

The easy solution for this is to do 

`tmux set-buffer -- '-M bar'`

but still, isn't they something wrong with options parsing here ?

**Comment by nicm** [comment]
No, this is just how it works:

$ \ls '-M foo'
ls: unknown option -- M
usage: ls [-1AaCcdFfgHhikLlmnopqRrSsTtux] [file ...]

**Comment by netei** [comment]
Ok, right didn't know that :-)
