### ISSUE TITLE
hooks triggered differ depending on tty id, and terminal emulator

### ISSUE THREAD

**Issue by poetaman** [tmux/tmux#2850]
### Issue description

This is more of an observation than a bug that affects my code. Am describing it here just so you know, and maybe would like to change it. 

On either terminal:
If a session is detached by pressing ``prefix-d``, hooks triggered are ``pane-focus-out -> client-detached``. If subsequently one enters ``tmux attach``, the hooks triggered are ``pane-focus-in -> client-attached``. The differences in behavior are for the case where a tmux session detaches from client if terminal window were closed (instead of pressing ``prefix-d``).

On Alacritty:
Repeating the sequence 1) tmux attach, 2) close terminal window, 3) open terminal window, 4) tmux attach settles down with following sequence: ``client-detached -> client-attached -> client-detached -> client-attached -> ...``. No ``pane-focus-in`` or out are triggered. Each time Alacritty seems to be opening with tty=``/dev/ttys000``

On iTerm2:
1) Repeating the same sequence as for Alacritty while tty remains constant ( tty=``/dev/ttys000``), produces ``pane-focus-out -> client-detached -> pane-focus-in -> client-attached -> pane-focus-out -> client-detached ...``.

2) Repeating the same sequence with different tty each time results in additional ``client-focus-in -> pane-focus-in`` (to the same pane) between ``pane-focus-out`` and ``client-detached``.

Note: neither of these cases break it functionally as I will be using all the events in my case and can decipher the resulting state. But it might not be the expected behavior, so I am filing this. You had asked me to keep an eye on something strange after you changed the queuing of events to follow focus: https://github.com/tmux/tmux/issues/2808#issuecomment-898233117

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Does this still happen since focus hooks were reworked?
