### ISSUE TITLE
crash when passing braces to "command-prompt"

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2852]
### Issue description

Tmux crashes when we use braces to pass a string argument to `command-prompt`.

To reproduce, run this shell command:

    tmux -Lx -f <(cat <<'EOF'
        bind x command-prompt { }
    EOF
    )

Then press `CTRL-B` followed by `x` (to trigger the user key binding which invokes `command-prompt`).

### Required information

 - `$ tmux -V`: tmux next-3.3, commit 7fe3588e49b957b6749c6011a1328fdcd45adc75
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs:
[tmux-client-60474.log](https://github.com/tmux/tmux/files/7042645/tmux-client-60474.log)
[tmux-out-60476.log](https://github.com/tmux/tmux/files/7042647/tmux-out-60476.log)
[tmux-server-60476.log](https://github.com/tmux/tmux/files/7042648/tmux-server-60476.log)
 - [backtrace](https://github.com/tmux/tmux/files/7042643/backtrace.txt)
 - regression introduced in: 95a374d
 - [`$ tmux info`](https://github.com/tmux/tmux/files/7042644/tmux.info.txt)

**Comment by nicm** [comment]
Nice, this should be fixed now, please test when GitHub syncs up. Thanks!
