### ISSUE TITLE
In tmux session, conda: command not found 

### ISSUE THREAD

**Issue by Umaruchain** [tmux/tmux#2853]
### Issue description
could not find conda , I have already add path in bashrc, profile and bash_profile ( profile and bash_profile is empty though)
 tmux -vv new

conda：
-bash: conda: command not found
source activate：
-bash: activate: No such file or directory

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* tmux 2.3
* Platform (`uname -sp`).
* Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`).
* xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
This is a problem with your shell setup by the sound of it. Don't you need to source .bashrc from .bash_profile?

**Comment by Umaruchain** [comment]
hi，I do source .bashrc and I can conda activate in the basic terminal.

**Comment by krader1961** [comment]
I guarantee you this is not a problem (i.e., bug) with tmux. One explanation is you started tmux then edited your shell config files. The existing shell processes in the tmux server will not automatically reread those config files. Beyond that guess you have provided far too little information.

Start by making sure there are no active tmux sessions: `tmux kill-server` then check that `pgrep tmux` produces no output. Then start a tmux session and type `conda`. If it works, great! If not check that `echo $PATH` shows the directory containing that `conda` command.

P.S., You wrote "xterm-256color" for the question "$TERM inside and outside of tmux (echo $TERM)." If `$TERM` really is that value inside a tmux session you are doing something wrong and it's only by luck that the behavior of programs inside those tmux sessions doesn't exhibit problems.

**Comment by Umaruchain** [comment]
thanks a lot!!!!!! 
I do as what you say. I check the the result of the 'echo path' and I find that the path of  conda is not right. I have fixed it!   
It works!

**Comment by krader1961** [comment]
> It works!

I am glad to have helped. Please close the issue. Also, please check that the value of `$TERM` inside your tmux session(s) is either `screen-256color` or `tmux-256color`. If it isn't one of those values you are probably setting `$TERM` in your shell config which is a mistake which will cause problems.

**Comment by Umaruchain** [comment]
It is screen neither screen-256color nor screen-256color. Is it ok ?

**Comment by krader1961** [comment]
@Umaruchain, `screen` is okay. It might limit the colors available to the processes running inside the tmux sessions. However, it might also be an alias for one of the `-256coior` terminfo names in which case it doesn't matter. Do not worry about it.

**Comment by Umaruchain** [comment]
thanks for your help again. And I will close the issue then.
