### ISSUE TITLE
Feature: add a hook that gets triggered when user is inactive and activity monitoring is on

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2854]
### Issue description

It would be nice to have a hook that gets triggered when a tmux pane/client is focussed but does not receive any user input (keyboard or mouse) for a period of time. Activity monitors like WakaTime pause logging time when user has not pressed any keystrokes. The hook would be activated only when a pane/client is focussed but does not receive any user input for a certain length of time. 

The monitor-silence hook seems insufficient as it seems to not just track user input but program output too, and doesn't seem to care about being focussed pane or not.

### Required information

Please provide the following information:

* tmux version (`tmux -V`) 3.3-next.
* Platform (`uname -sp`) Darwin arm.
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color, tmux-256color.

**Comment by nicm** [comment]
So what you are asking for is:

- Something analagous to `monitor-silence` but *only* for user input, so `monitor-input`.

- Hooks related to this, like the hooks we already have for `monitor-*`.

Is that correct?

**Comment by reportaman** [comment]
@nicm That's correct, though its not per window. The ``monitor-input`` hook should be at client level or server level I guess. It would trigger if a focussed tmux client does not receive human keyboard input for X amount of time. Not sure if you can filter out the keys going from a tty to a pane inside focussed tmux client using ``tmux send-keys``, that shouldn't count as human input in ideal world.

**Comment by reportaman** [comment]
Also, I'll get back to your other questions in coming days as setting up tests for some of them is done when I have access to my desktop. Hope thats ok.

**Comment by nicm** [comment]
If you want it per client or session then I think it would be better to just add "input time" like activity time, then you can script the rest yourself.

**Comment by reportaman** [comment]
I think client level is most appropriate as client is the highest layer of interaction for human keyboard entry. After giving it some more thought, I think it should not be at a server level hook as multiple users could be pair programming in the same server using 2 different clients.

The hook should be fired only for a focused client not receiving human input for a certain length of time. That would simplify coding the hook a lot compared to hooks fired for unfocused clients, which would anyway be a waste.

**Comment by reportaman** [comment]
Alternatively it could be at the lowest unit of interaction: pane, because at the end of the day when a client is focused, a pane is focused and vice versa. Decide whichever makes more sense, perhaps there is something you can foresee which I cannot.

**Comment by nicm** [comment]
I don't want to add a whole level of monitoring at session/client level so the choices are:

- Add a `monitor-input` that works the same way as `monitor-activity` (that is, per pane).

- Timestamp clients, sessions on input like `client_activity` which you can then use to script your own monitoring.

**Comment by reportaman** [comment]
@nicm Currently all of the features of something like WakaTime, are possible with Tmux's event hooks (without having to read some state periodically). I think your first suggestion, pane based ``monitor-input`` will fit in the event model as it will be an event hook. If I understand your second option, that timestamp will be just available, but there won't be a event hook that fires. If thats the case then, per pane based ``monitor-input`` is preferable. Though I hope it will fire only for focussed pane, i.e. a pane that is focussed & has not received input for a user specified time.

**Comment by nicm** [comment]
I have added `monitor-input` to the todo list.
