### ISSUE TITLE
Feature: neovim/vim does not always trigger FocusLost/FocusGained when a client is detached/attached respectively

### ISSUE THREAD

**Issue by poetaman** [tmux/tmux#2856]
### Issue description

If vim/neovim were the applications running in a focused tmux pane when client is detached and reattached again, they do not necessarily see this to trigger their FocusLost/FocusGained autocommands. I saw it happen once or twice, but it can be reproduced by detaching and reattaching the client back to back. It would be helpful if tmux makes it look like to the application running in its client at the time of detaching that focus is lost, and as if focus is back again at the time client is reattached.

> Note: vim/neovim do trigger FocusLost/FocusGained when client session is changed, and vim/neovim was the application running in the focussed pane at the time of client session changed. So that's great!

### Required information

Please provide the following information:

* tmux version (`tmux -V`) next-3.3.
* Platform (`uname -sp`) Darwin arm.
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color, tmux-256color.

**Comment by reportaman** [comment]
@nicm Yes, but not in all cases. Here are the steps that should definitely reproduce this. @gnachman could opine if this has something to do with iTerm2.

1. Open iTerm2
2. ``>> tmux``
3.`` >> nvim``
4. Close iTerm2 window by pressing the close button (red color) in title bar of the window.

Add this to your .vimrc if you want to print the events to a file and ``tail -f `` that file.

```
augroup PrintWin
    autocmd!
    autocmd FocusGained * nested call system('echo FocusGained  '. &filetype .' >> ~/vimevents.log')
    autocmd FocusLost * nested call system('echo FocusLost  '. &filetype .' >> ~/vimevents.log')
augroup END
```

<img width="138" alt="Screen Shot 2022-03-06 at 6 53 52 PM" src="https://user-images.githubusercontent.com/71736629/156960608-f3441db9-04c9-4826-826d-60ff846ad247.png">

**Comment by gnachman** [comment]
Sorry for the delay in getting to this. After adding `tmux set-option -g focus-events on` I see that focus reporting is enabled in iTerm2. iTerm2 does *not* send a focus-lost code when the window is closed; it just closes it. I guess tmux sees this as a read file descriptor closing, and it could reasonably send focus lost to vim, I guess.

Another interesting thing I noticed is that control mode doesn't benefit from the focus-events option but it probably should.

**Comment by gnachman** [comment]
https://github.com/gnachman/iTerm2/commit/657db7f3e46a428e7d9bbda6c05f5b6075180358 enables focus reporting in tmux integration mode if `focus-events` is enabled in tmux.

**Comment by reportaman** [comment]
@gnachman Thanks, can you please attach a build somewhere? I don't have Xcode on my computer so can't build iTerm2.

**Comment by gnachman** [comment]
@reportaman https://iterm2.com/nightly/latest
