### ISSUE TITLE
cannot install copy mode key binding to look for pattern

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#2858]
### Issue description

I have a key binding in copy mode to look for a pattern using `search-forward-incremental` instead of the default `search-forward`.  It looks like this:

    bind -T copy-mode-vi / command-prompt -ip '/' { send -X search-forward-incremental '%%%' }

It has worked fine for months/years, until 6 commits ago (95a374d7).  5 commits ago, using the key binding could cause tmux to crash.  The crash was fixed 2 commits ago (c7266ca7), but the key binding remains broken.

To reproduce, run these shell commands:

    $ tmux -Lx -f <(cat <<'EOF'
        bind -T copy-mode-vi / command-prompt -ip '/' { send -X search-forward-incremental '%%%' }
    EOF
    )

    $ echo a

Then, press:

   - `CTRL-B [` to enter copy mode
   - `/` to use the key binding and start a search
   - `a` to look for the pattern `a`
   - `Enter` to validate the search

Expected: `a` is matched.
Actual: Nothing is matched.

### Required information

 - `$ tmux -V`: tmux next-3.3, commit c6375a0d4003d1008bb64e96e9c0c4433e4a5d13
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs:
[tmux-client-328444.log](https://github.com/tmux/tmux/files/7066616/tmux-client-328444.log)
[tmux-out-328446.log](https://github.com/tmux/tmux/files/7066617/tmux-out-328446.log)
[tmux-server-328446.log](https://github.com/tmux/tmux/files/7066618/tmux-server-328446.log)
 - [`$ tmux info`](https://github.com/tmux/tmux/files/7066615/info.txt)

**Comment by nicm** [comment]
Thanks!
