### ISSUE TITLE
tmux Breaks Border with st

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [tmux/tmux#2859]
### Issue description
I am having an issue where `tmux` will create a weird extra border between my terminal emulator, `st`, and the window border. For a better idea of what I am referring to [here is a screenshot](https://i.imgur.com/wEQdjey.png) (this screenshot is of the top of my terminal, but it also adds this spacing to the side of my terminal).

### Required information
Please provide the following information:

* tmux version (`tmux -V`): tmux next-3.3
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): inside - tmux-256color, outside - st-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`): 

I did see a prior post about this being an issue with a terminal called `pango-terminal`, or something like that, but I was unable to find a solution.

**Comment by nicm** [comment]
This screenshot is so small it is impossible to make anything out, please attach the image to this issue rather than using an awful website.

**Comment by FOSSilizedDaemon** [comment]
> This screenshot is so small it is impossible to make anything out, please attach the image to this issue rather than using an awful website.

Here is a better screenshot. It keeps saying can't process file no matter how many times I upload it or what format I use so hopefully this site is better: https://share.riseup.net/#VEjsUPgz7opMVRf8J6Td1A the grey spacing on the sides of the window is the issue I am referring to

**Comment by nicm** [comment]
This is not a very clear screenshot either. Are you talking about the grey border all the way round? There is no way tmux can cause this since it is less that one character in width and height. It seems like a n artifact of your terminal or window manager. Are you sure your font fits exactly into the window size?

**Comment by FOSSilizedDaemon** [comment]
> This is not a very clear screenshot either. Are you talking about the grey border all the way round? There is no way tmux can cause this since it is less that one character in width and height. It seems like a n artifact of your terminal or window manager. Are you sure your font fits exactly into the window size?

Yep, and it only happens when `tmux` is running.

**Comment by nicm** [comment]
tmux cannot control this, you will need to talk to the terminal developers.
