### ISSUE TITLE
Can we have pre-expanded # in #(my-shell-command "#{pane_thing}") ?

### ISSUE THREAD

**Issue by unhammer** [tmux/tmux#286]
There is a workaround shown in https://github.com/tmux/tmux/issues/85 :
`"#(tmux display-message -p "#{=50:pane_current_path}" | sed "s#$HOME#~#g")"`
but it feels a bit unintuitive. I'd prefer being able to write something like `#(munge "#{pane_current_path}")` instead.

Of course, suddenly interpreting `#{}` might break a configuration if someone actually has `#{` in one of their status bars, but it seems a bit unlikely since it's not used in regular shell and '#' is a comment character there and in most typical shell commands.

**Comment by nicm** [comment]
Don't understand what you're getting at, show me what doesn't work.

**Comment by unhammer** [comment]
The shell command sees the string "#{pane_current_path}", not "/home/me/stuff"

**Comment by nicm** [comment]
That depends where you use it...

**Comment by unhammer** [comment]
To make it more concrete, say I'm in /home/batman/cave

    tmux set status-left '#(echo "#{pane_current_path}"|tail -c10)'

then, since the #{}-expansion doesn't happen until after the outer expansion, the status-left part says `ent_path}` instead of `atman/cave`.

**Comment by nicm** [comment]
This works just fine for me:

tmux set status-left '#(echo "#{pane_current_command}"|tail -c10)'

**Comment by unhammer** [comment]
Sorry, PEBKAC, I had only tested in the version I got from Ubuntu (2.0); this works for me as well when I try my 404379049a4cb5480c2b1c19634c869e46feb220 checkout
