### ISSUE TITLE
Bug: tmux/linux loses characters in scroll buffer when scrolling up using Putty

### ISSUE THREAD

**Issue by Kumba42** [tmux/tmux#2860]
### Issue description

Using tmux-3.2a on a Gentoo Linux x86_64 system, connected via Putty-0.76 from a Windows 10 system, if I dump a decent bit of text to the screen and then scroll up using my mouse wheel, there are random bits of data missing.  I am using a single pane in tmux, and my config file is fairly sparse.  I am not a vi/vim oe emacs user (nano ftw).  I tried the tmux copy-mode stuff, but found it too difficult to adjust to and could not get the copied data to transfer to the Windows clipboard via Putty.

This issue is similar to the one described in #1019, and my use case is exactly the same as @heymoe's.  However, after doing some extensive debugging, I have worked out that this is indeed a bug of some kind, and affects tmux running on a Linux machine being connected to with Putty, as well as tmux on an OpenBSD 6.9 VM, also connected to with Putty.  I cannot reproduce this bug on a FreeBSD 13.0-REL machine with Putty.

I used git bisect to try and whittle down to the offending commit, and was able to get to within three commits.  I cannot get any closer because several of the bisections results in a source directory that is missing autogen.sh, configure.ac, and Makefile.am, so it was impossible to test compiling the code.  I am not familiar enough w/ the GNU automake/autoconf tools to recreate them in this case.

In any event, the likely bad git commits are:
```
13a0b6bb3fe05454cace81f5ec7624f6fd9021a5   Collect sequences of printable ASCII characters and process
7475165cd87d443da34da11298e638d3d17f43e9   Some other tidying bits.
e100d465daefd20da0bb5eea87c4b4896badff16   Add support for scroll up escape sequence (CSI S) and use it
```

Of those three, I suspect that the problematic commit is 13a0b6bb3fe0.  It is difficult to reverse this commit to test, however, especially with the build system files missing around that commit as well.

The issue is fairly easy to reproduce and does not require much data going into the scrollback buffer.  A simple `ls -l /dev` is enough in my case, which outputs ~180 lines on my Linux system.  Not every command that dumps data is affected, either.  Linux's 'dmesg' command seems to be unaffected, even if you spam it several times in a row, but redirecting dmesg's output to a text file, then cat'ing that file to the screen will cause the issue to happen.

Running tmux with -vv shows that the missing data has what appears to be garbage escape characters (at least, I cannot work out what they represent).  Here's an example of `ls -l --color=none /dev`:
```
crw--w---- 1 root tty       4,  42 Aug 25 19:19 tty42[K
crw--w---- 1 root tty       4,  43 Aug 25 19:19 tty43[K
crw--w---- 1 root tty[K[1;52r[51;22H[1;51r[1;1H[51Scrw--w---- 1 root tty       4,   9 Aug 25 19:19 tty9[K
crw-rw---- 1 root dialout   4,  64 Aug 25 19:19 ttyS0[K
crw-rw---- 1 root dialout   4,  65 Aug 25 19:19 ttyS1[K
```

With the above, I denote the `` character as `«ESC»`, and thus the normal lines all end with `«ESC»[K`, but the damaged line has `«ESC»[K«ESC»[1;52r«ESC»[51;40H`.  This output is similar in other instances, with slight variances.

I compared this logging output with what's on my FreeBSD system with the same `ls` command, and it looks like the strange escape character sequence is there as well, but no data is lost like on the Linux or OpenBSD systems.  There are rather large gaps of whitespace, however:
```
crw-------  1 root  wheel      0x5b Aug 25 12:05 ttyv9[K
crw-------  1 root  wheel      0x5d Aug 25 12:05 ttyva[K
crw-------  1 root  wheel      0x5f Aug 25 12:05 ttyvb[K
crw-------[K[1;52r[51;11H[1;51r[51;1H













[37;11H  1 root  wheel      0x43 Aug 25 12:05 ufssuspend
lrwxr-xr-x  1 root  wheel        9B Aug 25 12:05 ugen0.1@ -> usb/0.1.0[K
lrwxr-xr-x  1 root  wheel        9B Aug 25 12:05 ugen1.1@ -> usb/1.1.0[K
lrwxr-xr-x  1 root  wheel        9B Aug 25 12:05 ugen2.1@ -> usb/2.1.0[K
```

My only conclusion is this is a bonafide regression from tmux-2.3.  After reading the discussion in Issue #1019, I do not believe that the fact everything worked rather well in v2.3 was unintended behavior.  Rather, the new code should work much the same, but there is a yet-undiscovered bug that only manifests itself when tmux is running on Linux or OpenBSD and Putty on Windows is used as the main client.

**Comment by nicm** [comment]
There is no mechanism for tmux to control the terminal scrollback so it doesn't attempt to, if you want full history you will need to learn to use copy mode.

**Comment by Kumba42** [comment]
> There is no mechanism for tmux to control the terminal scrollback so it doesn't attempt to, if you want full history you will need to learn to use copy mode.

Apologies, but tmux's copy-mode is not a one-to-one replacement for the scrollable buffer in Putty.  As I already mentioned, it is apparently impossible to copy the selected text directly into the Windows clipboard via Putty (shift-click works, but then you cannot select+scroll, so no-go).  Second, trying to select text in copy-mode and scrolling to the bottom of the screen cancels the selection and exits copy-mode.  Third, releasing the mouse button while selecting text copies the text into Tmux's internal clipboard and then resets the scrollback to the bottom of the window.

I've tried looking for ways to disable the latter two issues, but a majority of answers on Google are specific to MacOS users or deal with older releases of tmux.  And given the polymorphic nature of tmux's config file, this makes it frustratingly-difficult to figure out what is applicable to the latest version and what isn't.  So unless tmux makes its copy-mode have greater parity with what I can do in Putty, then it is not something I can learn, as it slows my workflow down significantly and that is untenable.

The issue I am describing is a legit bug that was introduced with new code.  Just because Putty "accidentally" worked with the older code doesn't mean it should be ignored like this.  It's not my fault the older code may have been "wrong" somehow.

While I wish I could go back to the older code, the newer code obviously fixes some real issues that affected a lot of other people.  In my case, the newer code _almost_ works, which means it's probably some trivial corner case in the new code that should be easy to fix for someone who understands the code base and all of the inner-workings of terminals.

As far as I can determine, whenever these gaps happen, it looks like tmux is doing something with the mouse cursor position via tty_update_mode calls.  Which doesn't make sense to me, because I have terminal mouse support explicitly disabled.  What is the logic behind this?

And why might tmux on FreeBSD be unaffected?  Looking at the tmux-server*.log file, the output is broken up by these same tty_mode_update calls like on Linux, but for some reason, FreeBSD's terminal emulation either catches back up or has some subtle difference in its terminfo/termcap definitions that works around the issue.  It could be there's a particular difference here that "fixes" this issue and may be applicable to Linux, if it can be found out.

**Comment by nicm** [comment]
Older versions of tmux were less aggressive about removing data that does not affect the visible terminal, so there are likely to be fewer - or at least different - gaps in the scrollback. But no terminal offers tmux any practical way to control the contents of the scrollback, so it (intentionally) does not make any attempt to keep it coherant or complete and instead provides its own internal way to access history (copy mode). Copy mode is highly configurable and works in the same way across different terminals, with multiple different windows and panes, and after tmux is detached and reattached. This is impossible to achieve with the terminal scrollback.

**Comment by nicm** [comment]
The basic fact is that we are not going down the path of trying to work with terminal scrollback because it is impossible, as soon as you create a new window, or detach and reattach, the scrollback is useless. All other full screen terminal programs have the same issue, which is why you see most offer their own way of scrolling and copy and paste.

The only way to reliably get pane history is to use copy mode. If you don't like the specifics of how it works, most of them are configurable.

**Comment by Kumba42** [comment]
> The basic fact is that we are not going down the path of trying to work with terminal scrollback because it is impossible, as soon as you create a new window, or detach and reattach, the scrollback is useless. All other full screen terminal programs have the same issue, which is why you see most offer their own way of scrolling and copy and paste.

Loss of scrollback contents on a new window, detach/reattach, or even changing windows, I am actually fine with.  I'm used to that, and been used to it for 10+ years between tmux and previously, GNU screen.  I care more about some kind of guarantee of not losing scrollback data in the _immediate_ sense.  E.g., if I execute `ls -l` on a big directory and then want to immediately scroll up and copy that, I expect that data in Putty's scrollback buffer to be intact and not missing anything.  But after I switch windows or detatch my session, all bets are off.

It almost feels like this could be managed by a flag.  As long as the current session hasn't spawned or switched to a new window, nor detached, then tmux could dial down the aggressiveness of removing data by checking a boolean flag.  Upon new window, switch window, or detach, it clears the flag on that last window.  Additionally, this flag would only have meaning if there is a single pane open, since I know multiple panes makes maintaining the scrollback outside of tmux impossible.

The other option I can think of is a setting to control how "aggressive" tmux is in removing data, ranging from 0 to 100 (or some reasonable max value).  If set to 0, you basically get the tmux-2.3 behavior, while at the max value, you get the current behavior.  This might be the better approach, cause it doesn't seem like it'd be too difficult to modify the algorithm you have to accommodate this.

Sane/Insane?

>
> The only way to reliably get pane history is to use copy mode. If you don't like the specifics of how it works, most of them are configurable.

I can tell that tmux is highly configurable, but it's frustrating trying to find particular examples.  There's only so much banging-the-head-on-the-wall that I can do with Google on a given day.  As far as I can tell, I need to find solutions to several aspects to make copy-mode work for me:
  - Need to copy directly from tmux's buffer into the Windows clipboard via Putty.  This means I cannot rely on any X11 (xsel, xclip) or MacOS (pbcopy) solutions, which is a majority of the results that Google tries to show me.
  - Need to be able to mouse scroll while holding down the left-click to continuously expand the selection box.
  - Need to disable the exiting of copy-mode when I mouse scroll down to the bottom of the window so that I don't lose the selection and it gets copied into Windows' clipboard.
  - Need to disable the exiting of copy-mode if the mouse button is released after a drag and resetting of scrollback to the bottom.  E.g., I expect the current scroll position to stay where it is at and any currently-selected data to remain selected, even if new data is being appended below.  This is important if you're trying to grab something like glibc build commands out of a running compile on a fast (make -j14) machine.
  - Make right-mouse click paste clipboard contents directly instead of bringing up the in-tmux popup menu.

How many of the above are possible, and where are some pointers I can go and look at, other than the man page?  The critical one is getting data to Windows' clipboard.  I haven't found a solution for that yet, and it seems like it's simply not possible for some reason.

**Comment by Kumba42** [comment]
Also for the FreeBSD quirk, it looks like FreeBSD is not using a full terminfo database, but rather a minimal, old-school termcap implementation.  I recall reading somewhere that they may switch to a full terminfo in 14-CURRENT, so I suspect this glitch will start to manifest itself when that happens.

Since you have a much better understanding of termcap/terminfo, is there any thing you can think of that I should go looking for that may explain why FreeBSD seems to keep the scrollback consistent?  E.g., could there be a specific Cap-name or TCap-code that it doesn't implement when TERM is `xterm-256color` that may explain why it doesn't lose data?

As far as I can tell, and from reading more on #1019, when tmux's algorithm decides to try and toss out data, it switches to some kind of mouse cursor position update mode during the blocking, and then back to recording data.  I think that's where those `«ESC»[1;52r«ESC»[51;xxH` sequences are coming from.  I found at the bottom of tty_update_mode where tmux emits codes for handling bracketed-paste and other terminal bits, and those happen before the cursor codes emit.  Thus obviously the blocking start logic must happen before tty_update_mode fires, and I wonder if there's some code that is sent prior to that which FreeBSD is handling differently than Linux/OpenBSD would on a full terminfo database.

**Comment by nicm** [comment]
We're not adding flags or maintaining complex code for something that only works if you don't use tmux for any of its actual purposes.

There is no way to stop tmux only drawing content that actually changes the visible terminal, I don't know why FreeBSD is different, perhaps it is missing some of the scrolling sequences so tmux scrolls differently. You could try removing `indn` with `terminal-overrides`.

**Comment by nicm** [comment]
>Need to copy directly from tmux's buffer into the Windows clipboard via Putty. This means I cannot rely on any X11 (xsel, xclip) or MacOS (pbcopy) solutions, which is a majority of the results that Google tries to show me.

https://github.com/tmux/tmux/wiki/Clipboard

>Need to be able to mouse scroll while holding down the left-click to continuously expand the selection box.

I don't know what this means. 

>Need to disable the exiting of copy-mode when I mouse scroll down to the bottom of the window so that I don't lose the selection and it gets copied into Windows' clipboard.

You need to change the bindings to `copy-mode` without `-e`.

>Need to disable the exiting of copy-mode if the mouse button is released after a drag and resetting of scrollback to the bottom.

You need to change the key bindings from `copy-selection-and-cancel` to `copy-selection` or `copy-selection-no-clear` and similar for `copy-pipe-and-cancel`.

> Make right-mouse click paste clipboard contents directly instead of bringing up the in-tmux popup menu.

Change the `MouseDown3Pane` binding to the same as `MouseDown2Pane`.

**Comment by nicm** [comment]
Only `WheelUpPane` has `-e` so that is the only `copy-mode` binding you need to change.

**Comment by nicm** [comment]
>Need to be able to mouse scroll while holding down the left-click to continuously expand the selection box.

If you extend the selection to the bottom or top line, it should scroll.

**Comment by nicm** [comment]
I know changing `-e` and the `-and-cancel` key bindings is a bit of a pain but tmux's default bindings were not so complicated when they were added so it used to be easier, maybe it is time to add a `copy-flags` option.

**Comment by Kumba42** [comment]
> There is no way to stop tmux only drawing content that actually changes the visible terminal, I don't know why FreeBSD is different, perhaps it is missing some of the scrolling sequences so tmux scrolls differently. You could try removing `indn` with `terminal-overrides`.

Already had tried that Cap-name.  No change.  I ended up dumping the database for `xterm-256color` on both systems and mapped out which ones were different, then removed all of the ones Linux had defined from the Linux machine and still no change.  Even compared all `stty -a` flags between the two systems and matched those up, and still no change.  I also installed the full terminfo database on FreeBSD and it still doesn't have an issue.

I am left to wonder if it's something in the FreeBSD kernel, possibly related to the `pts(4)` driver for pseudo-terminals, that is smart(er) about things?  On the Linux side, the only other observation I have is that only output from tools from GNU coreutils seem to be affected, like `cat` and `ls`.  Tools like `dmesg` from util-linux, `ps` from procps, and classic `grep` do not have issues when outputting large blobs of text inside of a tmux session in Putty and then scrolling up.

So there is the possibility that how those tools handle writing output to the screen may be different and thus, possibly the bug may be in GNU coreutils.  That would also help explain @heymoe's issue in #1019, because he was focusing on using `cat` to dump large blobs of text out from a file and getting gaps in the data.  Although, that does not explain why I saw the same effect on OpenBSD's `ls` command, which should hew much closer to FreeBSD's instead of GNU...

One curiosity, on tmux's blocking code, should it be discarding entire lines of data when the blocking fires, or individual characters?  The output I am seeing shows lines being truncated halfway, more or less, sometimes.  If this is expected, then I can ignore that effect.

Thanks for the tips on copy-mode.  I will research those later on and see if I can adapt the copy-mode functions to supplant what I am used to.

**Comment by Kumba42** [comment]
Yeah, now that I go back and look at where OpenBSD's data is getting discarded by tmux, it is consistently on line boundaries.  In fact, `dmesg > x; cat x` on OpenBSD doesn't even put the top-half of dmesg into the scrollback buffer at all, but neatly cuts it right where the first line of text would fit onto my terminal screen.  Compared to the GNU coreutils tools, I am seeing stuff getting truncated in the middle of the line at random.  Sometimes it is on the first character, sometimes a quarter the way through, sometimes close to the end.  This suggests that there's a bug somewhere in how coreutils handles printing to the terminal that's having a bad interaction with tmux's discard logic.

I also tested printing a very large blob of text in Python on Linux, and no truncation by tmux.  On OpenBSD, it's discarding on whole lines, which I believe is what you would expect tmux's discard logic to do, right?

**Comment by nicm** [comment]
More likely one is writing line buffered and one is not.

**Comment by Kumba42** [comment]
> More likely one is writing line buffered and one is not.

Beats me.  I also checked a NetBSD VM, and it behaves exactly like FreeBSD and is unaffected.  Tried Alpine Linux as well, which uses musl libc, and it behaves like Linux w/ a glibc userland (wanted to see if different libcs had any effect).  So at this point, I am assuming it is something related to the kernels of each OS I tested.  In any event, something to play with another day.<br/><br/>


> > Need to copy directly from tmux's buffer into the Windows clipboard via Putty. This means I cannot rely on any X11 (xsel, xclip) or MacOS (pbcopy) solutions, which is a majority of the results that Google tries to show me.
> 
> https://github.com/tmux/tmux/wiki/Clipboard

I've followed this, but am still unable to get tmux to write copied data to Putty and thus, the Windows clipboard.  The `Ms` capability is set, but it seems like Putty ignores it and/or doesn't support it.  I tried with both `TERM=xterm-256color` and `TERM=putty-256color` in the outer console.  Some digging pulls up this "wish" item on Putty where the author states that they will never implement OSC support in Putty since they believe it to be a security issue (but they never call it OSC52, so unsure):
https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/osc.html

The only solution can I find involves a complex rig-up of constantly saving the tmux buffer to a file in /tmp and then using a virtual printer defined in Windows to pass the data through to Putty.  Which is just ugly.  There's gotta be a better way.

Might also just be time to look for a Putty replacement, too...<br/><br/>

> > Need to be able to mouse scroll while holding down the left-click to continuously expand the selection box.
> 
> I don't know what this means.

It looks like this is a misunderstanding on my part of how the mouse scrolling behaves when using click-drag.  It looks like the scrolling happens relative to the position of the mouse cursor.  If the cursor is closer to the bottom of the window, scrolling down has virtually no effect, but scrolling up does.  As I normally select from above and drag down, I guess I just need to get used to keeping my mouse cursor further up the window and let the scroll wheel expand the selection box until the end of the buffer, then (after fixing the next item), drag the cursor down to the bottom.<br/><br/>

> > Need to disable the exiting of copy-mode when I mouse scroll down to the bottom of the window so that I don't lose the selection and it gets copied into Windows' clipboard.
> 
> You need to change the bindings to `copy-mode` without `-e`.

Had to hunt for this one.  It was on the root `WheelUpPane` binding.<br/><br/>

> > Need to disable the exiting of copy-mode if the mouse button is released after a drag and resetting of scrollback to the bottom.
> 
> You need to change the key bindings from `copy-selection-and-cancel` to `copy-selection` or `copy-selection-no-clear` and similar for `copy-pipe-and-cancel`.

Found, thanks.  Will need to play with things to figure out what works best.<br/><br/>

> > Make right-mouse click paste clipboard contents directly instead of bringing up the in-tmux popup menu.
> 
> Change the `MouseDown3Pane` binding to the same as `MouseDown2Pane`.

Actually copied `MouseDown2Pane`'s logic to `MouseDown3Pane`, and then (for now), made `MouseDown2Pane` just select the entire line, which imitates what it does in Putty.  Not a 1:1 effect, but it'll work for now.

**Comment by nicm** [comment]
mintty might be an alternative that supports OSC 52.

**Comment by Kumba42** [comment]
Sorry, I got sidetracked.  I started testing out several of the commercial alternatives to PuTTY on Windows.  Of the several I tried, only SecureCRT supports OSC52, but only for copying data to the Windows clipboard.  Apparently no terminal emulation software on Windows supports pasting to a remote terminal via OSC52.

That said, it seems tmux has an issue with sending the copied data to SecureCRT when OSC52 support is enabled.  When testing a mouse double-click, a portion of the base64-encoded data that is supposed to be sent to SecureCRT gets echoed to the screen at the mouse cursor position and the Windows clipboard remains empty (or holds its previous value).

These are the bindings I am using to test with SecureCRT (basically the defaults with a slight tweak to only do copy-selection):
```
bind-key -T root DoubleClick1Pane \
        select-pane -t = \;\
        if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" \
                "send -M" "copy-mode -H ; send -X select-word ; run-shell -d 0.3 ; send -X copy-selection"

bind-key -T copy-mode DoubleClick1Pane \
        select-pane \;\
        send-keys -X select-word \;\
        run-shell -d 0.3 \;\
        send-keys -X copy-selection
```

Is there something I can change/tweak to get this to work?

**Comment by nicm** [comment]
Does this still happen even if you copy a small amount of text (like 4 or 5 characters)? Are you sure SecureCRT doesn't have a length limit on the amount of data it can handle?

**Comment by Kumba42** [comment]
> Does this still happen even if you copy a small amount of text (like 4 or 5 characters)? Are you sure SecureCRT doesn't have a length limit on the amount of data it can handle?

Yup.  This is a small snip of where I double-clicked on the device node `vcsu7` in an `ls -l /dev` output.  tmux is still in copy-mode, and just to the right of that node, you'll see the base64 characters `dmN` and a repeat of the device node, in color.  I am not sure if the color data from the ls output is being included, or if that's something the terminal is doing.  As soon as I exit copy-mode, this text goes away and the ls output looks normal, but nothing was copied to the clipboard.
![image](https://user-images.githubusercontent.com/29685010/132880850-cd81d3a8-b3ff-4327-b917-8660ac7f41fd.png)

Similar output here if I double-click on non-colorized text, the `crw-rw----` bit.  Just after that is the base64 string `Y3J3LXJ3LS0tLQ==` (but not the permissions string):
![image](https://user-images.githubusercontent.com/29685010/132881837-54b48fbf-886b-46be-bd61-30508987f9d8.png)

Strange thing is, I am using almost the same exact set of copy-mode commands for `TripleClick1Pane` (`select-line` for `select-word`), and that actually does copy data to the Windows clipboard through SecureCRT.  You do, however, see `DoubleClick1Pane` fire when doing the triple-click, so there seems to be a possible timing issue as well with how tmux reads double- and triple-click mouse events.
```
bind-key -T copy-mode TripleClick1Pane \
        select-pane \;\
        send-keys -X select-line \;\
        run-shell -d 0.3 \;\
        send-keys -X copy-selection
```

Last, similar effect on `MouseDragEnd1Pane` with the base64 text and no copying to the Windows clipboard, though this happens really fast and I had to repeat several times to actually catch the output in a screenshot:
![image](https://user-images.githubusercontent.com/29685010/132883101-d714f1b0-68f7-47f3-9c62-721615aa01bb.png)

Bind definition:
```
bind-key -T copy-mode MouseDragEnd1Pane \
        send-keys -X copy-selection
```

Can't rule out this is a bug in SecureCRT.  First time I've used this software, and it appears they only just recently added OSC52 support.  I'm in trial mode for ~30 days, so doubt I'll get any support unless I actually purchase a license (debatable if this doesn't work).

**Comment by nicm** [comment]
It looks to me like SecureCRT doesn't support OSC 52 properly, best bet is to ask them. Printing the Base64 sequence is definitely wrong.

**Comment by nicm** [comment]
Maybe it doesn't like the default terminator, try changing to the other one with `terminal-overrides`:
~~~~
set -as terminal-overrides '*:Ms=\E]52;%p1%s;%p2%s\E\\'

**Comment by nicm** [comment]
Or maybe it needs something specific in p1. Do their docs say anything?

**Comment by Kumba42** [comment]
It appears that I have partially solved the base64 text getting echoed to the screen.....I think.  The root `DoubleClick1Pane` I listed earlier seems to have been part of that issue.  By leaving that bind at the tmux default, I can still sometimes see the base64 text, but it quickly gets consumed or something and doesn't stay on the screen.

However, the core issue of moving copied data to Windows' clipboard is unsolved.  I am completely unsure why, but the bind for copy-mode `TripleClick1Pane` works fine to copy the selected line to Windows' clipboard, but not the copy-mode `DoubleClick1Pane`.  The only difference between the two is `send-keys -X select-line;`, which works, versus `send-keys -X select-word;`, which doesn't work.  And similarly, `MouseDragEnd1Pane` doesn't copy anything to the clipboard either.  With this, it doesn't matter what `Ms` terminator I use nor if I use `copy-selection*` or `copy-pipe*`.  All of these work for triple-clicks for the entire line, but not for double-clicking or mouse dragging.

At this point, I'm not terribly inclined to pay for a SecureCRT license when PuTTY just works.  I may have to give up using a terminal multiplexer entirely, as GNU Screen has a really nasty bug of its own that's remained unfixed for almost nine years (bug #35862 on savannah if you're curious).  Or just lock myself into tmux-2.3 for the next few years.

FWIW, I did try removing all of that TTY blocking code in tmux-3.2 and still had the original issue described.  So I don't think your blocking/discard algorithm is at fault here.  It really does seem to me that the screen/cell buffering code in ommit 13a0b6b may have some kind of subtle bug in it.  I may try removing that code again just to make sure I wasn't seeing things or running the wrong binary.  If you ever get the free time, maybe going over that logic again may be worth a few minutes?

**Comment by nicm** [comment]
did you try using mintty?

**Comment by Kumba42** [comment]
> 
> did you try using mintty?

mintty isn't a full-blown SSH client like PuTTY is, as far as I know.  I have it installed as part of the Windows release of git, but haven't messed with it much beyond its uses for git bash.

**Comment by nicm** [comment]
No but you can just run another ssh client like openssh inside?

**Comment by Kumba42** [comment]
> 
> No but you can just run another ssh client like openssh inside?

That is sub-optimal for my use-case.  I have multiple systems on my network, and I use a tabbed interface for PuTTY (MTPuTTY) to keep things organized.  I also use SSH keys cached by Pageant.  I lose all of that if I switch to running inside of multiple mintty's, which will clutter up my taskbar and not cache ssh keys for re-use.  This is kinda going a long way off from fixing what I think is a legit bug in tmux.

I'll try to take a look at mintty later on to test some of the above observations out on the copy-mode and OSC52 issues I'm having, but I don't really see this being viable in the long-term for my preferred workflow.  PuTTY with tmux should just work, and, in my humble opinion, scrollback buffering should remain intact for low-latency, local-area networks, especially when the machines I SSH into are literally 10ft behind me on a shelf.
