### ISSUE TITLE
make vim w, b, and e motions in copy-mode work over "WORDS" instead of "words" (feature request)

### ISSUE THREAD

**Issue by chrisbarber** [tmux/tmux#2861]
### Issue description

Currently the w, b, and e motions in copy mode in tmux work the same as W, B, and E, as far as I can tell. Vim defines these differently. For W, B, and E, the words are determined just by whitespace or not. For w, b, and e, they are aware of characters that look like identifiers. The implementation might be slightly nitpickier because there are 3 classes of characters (whitespace, identifier, nonidentifier) to consider, instead of just 2 (whitespace and nonwhitespace).

I'm not sure if it would be easier to implement based on understanding the functionality, or just lifting the code from vim. Here is an excerpt from the vim help explaining the difference between these motions:

```
==============================================================================
4. Word motions                                         *word-motions*

<S-Right>       or                                      *<S-Right>* *w*
w                       [count] words forward.  |exclusive| motion.

<C-Right>       or                                      *<C-Right>* *W*
W                       [count] WORDS forward.  |exclusive| motion.

                                                        *e*
e                       Forward to the end of word [count] |inclusive|.
                        Does not stop in an empty line.

                                                        *E*
E                       Forward to the end of WORD [count] |inclusive|.
                        Does not stop in an empty line.

<S-Left>        or                                      *<S-Left>* *b*
b                       [count] words backward.  |exclusive| motion.

<C-Left>        or                                      *<C-Left>* *B*
B                       [count] WORDS backward.  |exclusive| motion.
```
```
These commands move over words or WORDS.
                                                        *word*
A word consists of a sequence of letters, digits and underscores, or a
sequence of other non-blank characters, separated with white space (spaces,
tabs, <EOL>).  This can be changed with the 'iskeyword' option.  An empty line
is also considered to be a word.
                                                        *WORD*
A WORD consists of a sequence of non-blank characters, separated with white
space.  An empty line is also considered to be a WORD.
```

These motions are implemented here in vim:
https://github.com/vim/vim/blob/b9115da4bec5e6cfff69da85cc47c42dd67e42e4/src/textobject.c#L320-L554

I haven't looked at the tmux implementation of these motions (yet).

I notice this issue since I use tmux copy mode a lot and often want to move around based on "words" rather than "WORDS." E.g. if I have some test output that says that the unit test `module1.module2.module3.TestClassName.test_method_name` failed, I would enter copy mode, get to the beginning of this string, then hit `E` to go the end of it, but then `b` to get to the beginning of `test_method_name` so I can go to my vim window and search for this tag. But instead the `b` works like `B`, and puts me back tothe beginning of `module1`. So instead I have to do something like `T.` to get to the beginning of `test_method_name`. Or just hold down`h` and wait for the key-repeat to get me there.

Even as a heavy user of vim bindings across many tools (tmux, pdb, gdb, less, bash, etc etc), I consider this a low priority issue, because I noticed it immediately with tmux that this doesn't behave the same as vim (or the other tools I list, which are consistent with vim on these basic motions). But it didn't bother me enough to report this for at least a couple years. But since these are core motions and all the other linux tools are matching vim on how these motions work, I think implementing this would go a long way to giving others like me a smoother experience. These non-vim tools will never implement everything in vim, but if they are consistent on the really core things, one can converge on a core set of vim functionality across these tools, which, when consistent with vim across all tools, would provide a nice experience.

### Required information

```
Linux x86_64
tmux next-3.3
xterm-256color
```

**Comment by nicm** [comment]
You can probably do this by binding keys which set and restore the `word-separators` option before and after issuing the copy mode command.

Please do not copy code from vim, it has a weird custom license.

**Comment by nicm** [comment]
I don't know if you are correct because these keys have been bound to different things since forever:
~~~~
$ tmux lsk -Tcopy-mode-vi w
bind-key -T copy-mode-vi w send-keys -X next-word
$ tmux lsk -Tcopy-mode-vi W
bind-key -T copy-mode-vi W send-keys -X next-space
~~~~
And all this was considerably changed in 022d0210c5afa4e516183bf19715316ccca5d240. Are you sure you haven't changed your key bindings?

**Comment by chrisbarber** [comment]
Yes a quick look at #2693 looks like this was already done. Sorry I didn't find that via the issue search.

I am a bit puzzled because my tmux.conf doesn't set any of these keys nor does it set `word-separators`. It looks from that PR that the default is something like ``!\"#$%&'()*+,-./:;<=>?@[\\]^`{|}~``. This I find odd because I believe it would also have to include space, otherwise it behaves strangely in comparison to vim.

It also looks like I'm not getting that default. I'll do some more experimentation with a fresh tmux or check on another machine.

**Comment by nicm** [comment]
It includes space by default.
