### ISSUE TITLE
[question] Is buffer value secure for passing password?

### ISSUE THREAD

**Issue by bartoszek** [tmux/tmux#2862]
I wonder if buffer values are stored somewhere in the open text or shared between `tmux` sessions. Are they safe to use e.g: for passing sensitive values like passwords?

**Comment by nicm** [comment]
What do you mean safe?

**Comment by bartoszek** [comment]
Are they perhaps stored on disk or in shm, like bash history or vim shared registers? Can they be accessed by other programs running inside a tmux session without user interaction?

**Comment by nicm** [comment]
They are not on disk (unless tmux is paged out, but any program or user with access to your user account can completely control tmux including the paste buffers.
