### ISSUE TITLE
tmux doesn't display CP437/ANSI

### ISSUE THREAD

**Issue by ajrossnz** [tmux/tmux#2864]
### Issue description

I am a big fan of using retro equipment to do practical things. using Michael Brutman's TCP Telnet on an IBM DOS machine, I can telnet into my raspberry pi and from there, SSH to other boxes, or telnet to BBSes and play with them. It works great. However, I'd love to be able to switch tasks, and tmux is great for that (does anyone have any other better ideas?). Unfortunately, if I use telnet from within tmux on this machine, ANSI escape sequences are almost immediately corrupted. On the attached photo, you are supposed to be seeing a picture of the world, made up of extended ANSI CP437 chars. This is of a BBS.

Connecting this way works:

    telnet to pi, telnet to bbs
    telnet to pi, ssh to another machine, telnet to bbs

As soon as I add tmux in the mix, all the character handling turns to crap - does anyone know how to fix this? As you can see, I've already turned off my status line as that doesn't play nice with real 25 row displays!

### Required information

Please provide the following information:

*config (just one line!): 
set -g status off
* tmux version (`tmux -V`).
tmux 2.6
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
I've tried the following (both in and out):
screen
pcansi
ansi
[Image of issue:](https://preview.redd.it/xl2n78cbw6k71.jpg?width=4000&format=pjpg&auto=webp&s=5dece349225e1cea838c59643498e1734f353f60)

**Comment by krader1961** [comment]
First, tmux version 2.6 is extremely old. In general you're not going to get much interest in addressing an issue of an open-source project using a version that old. The exception being a company providing paid support for open-source software (e.g., RedHat, IBM, etc.).

Second, `tmux` by definition does support ASCII but not non-Unicode extended char sets such as most Windows code pages (e.g., [CP437](https://en.wikipedia.org/wiki/Code_page_437)) or the ISO 8859 standard.

**Comment by krader1961** [comment]
See https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-utf-8; although, I'll admit it is unclear and unfortunate that page does not mention "unicode" nor does the man page (other than one place irrelevant to this issue).

Also, the value of `$TERM` inside a tmux session should not be the same as the value outside of the session (ignoring nested tmux sessions). In other words, `TERM=ansi` inside a tmux session is wrong and will cause problems outside of the fact you're trying to use a non-Unicode compatible code set.

**Comment by ajrossnz** [comment]
This is for any version of tmux, 2.6 is on my stable server, I have newer versions on other boxes, the same issue applies.

So, does this mean that it will not be possible to use tmux properly with a machine that does not support UTF-8?

NB I tested TERM=screen first, then pcansi, then ansi, so have tested all with the same result. LANG also exported to UTF as well as C.

**Comment by krader1961** [comment]
> So, does this mean that it will not be possible to use tmux properly with a machine that does not support UTF-8?

Yes and no. Yes, tmux only supports UTF-8 (i.e., Unicode). No in as much as it looks like it is theoretically possible to support code sets like Windows CP437 in a degraded mode by forcing tmux to recognize only ASCII. Which means tmux will not correctly render any code points in the upper half of such a code set.

**Comment by nicm** [comment]
Please try tmux 3.2a or master, and please show tmux logs. 2.6 is too old and no longer supported.

tmux does not support CP437 so for top-bit-set characters to work you will need to use something like luit to translate them to UTF-8, or live with tmux removing them.

However, the ANSI escape sequences should still work. Please show logs from a newer tmux version.

**Comment by nicm** [comment]
If you use luit of course you will still need to use a UTF-8 terminal emulator for tmux. I would expect these two scenarios to be possible:

BBS -> telnet -> luit -> tmux -> xterm
(luit will map CP437 to UTF-8 which everything up the chain understands)

BBS -> telnet -> tmux -> telnet -> DOS
(tmux should remove top-bit-set characters it does not understand)

In the second case you will need to make sure that tmux knows the terminal is *not* UTF-8, so remove LANG, LC_ALL, LC_CTYPE from the environment. Make sure `tmux lsc` does not say "UTF-8". Also set `TERM` outside tmux to `ansi`.
