### ISSUE TITLE
Is there a way to fix the pane name

### ISSUE THREAD

**Issue by sriramkandukuri** [tmux/tmux#2865]
Hi,

I am working with multiple panes which show title in pane border,
I usually set the title to keep the context.

When I do ssh to any remote server from a pane, every command changes the pane title.

Is there a way to disable automatic renaming of pane title?

Thanks,
Sriram.K

**Comment by nicm** [comment]
Instead of using the pane title, set a user option and put it in the pane status line. Then the application inside the pane can't change it.

**Comment by sriramkandukuri** [comment]
Hi,
Thank you for the suggestion. Is there any example or reference to get more info on this?

Thanks,

**Comment by nicm** [comment]
Set the name with with for example `set -p @mypanename xyz` then put `#{@mypanename}` in `pane-border-format`.

**Comment by sriramkandukuri** [comment]
Thank you very much
