### ISSUE TITLE
Question/feature: change meaning of percentage dimension when spanning split is created, restore original pane dimensions when it is closed

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2866]
### Issue description

``split-window -f`` creates panes spanning entire width or height of the current client. Even though the span is of full window size, the percentage dimension passed to ``-l`` is relative to the currently focussed pane size. When the user passes ``-f``, I think percentages passed to ``-l`` should use window (client) size instead of focussed pane size.

Also, when such a spanning pane is closed, it would be nice to restore the original dimensions of the the panes at the time spanning split was created (unless user then goes ahead and manually changed the split sizes again when spanning split is open? this could be optional...). A more general solution would be to provide users a command like ``push-dimensions`` that pushes current pane dimensions+positions on a stack (perhaps as % of client window size), and ``restore-dimensions`` that pops the dimensions+positions (% of client window size) and applies them to the panes if they exist... Given ``push-dimensions``, and ``restore-dimensions`` can bring its own complexities (like what happens to  space of panes that no longer exit, or new that got created), an alternative could be an interface like ``save-view`` and ``restore-view`` that strictly restores the view (kills new panes created after ``save-view``, and opens new some of the saved panes were closed after ``save-view``). A third option could be like one of the vim plugins that remembers each time vim layout is changed, and allows user to navigate back and forth in layout.

### Required information

Please provide the following information:

* tmux version (`tmux -V`) 3.3-next.
* Platform (`uname -sp`) Darwin arm.
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color, tmux-256color.

**Comment by nicm** [comment]
Changed `-p`/`-l` now.
