### ISSUE TITLE
Spurious control-click events occurring with both terminal and iterm when switching between panes using tmux navigator with "focus-events" on

### ISSUE THREAD

**Issue by sdondley** [tmux/tmux#2867]
### Issue description

Out of the blue, a left click event is somehow getting triggered when using tmux navigator to switch between panes. This is happening in both iterm and the stock terminal app on my mac. As a side effect of the control-click, it can cause neovim to throw spurious errors when switching between panes or iterm to pop open a context menu.

Here's the weird part: it only happens if I hold the ctrl key down for an extended length of time. If I quickly release the ctrl key, I can't trigger the problem. Also, the problem is intermittent. It only happens maybe half the time. It doesn't appear to happen on all panes. On a freshly opened pane it may not happen immediately but after a while, it can start occurring. 

I didn't change any settings that I'm aware of that might have changed the behavior of tmux.

The fix is simple: set "focus-events" setting to "off". 

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

tmux 3.2a

* Platform (`uname -sp`).

Darwin i386

* $TERM inside and outside of tmux (`echo $TERM`).

"screen-256color" for both in an out

* Logs from tmux (`tmux kill-server; tmux -vv new`).

1630778692.596425 client started (19665): version 3.2a, socket /private/tmp/tmux-501/default, protocol 8
1630778692.596495 on Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
1630778692.596512 using libevent 2.1.12-stable (select); utf8proc 2.6.1; ncurses 6.2
1630778692.596548 flags are 0x18010000
1630778692.596559 socket is /private/tmp/tmux-501/default
1630778692.596577 trying connect
1630778692.596602 connect failed: Connection refused
1630778692.596814 lock file is /private/tmp/tmux-501/default.lock
1630778692.596907 flock succeeded
1630778692.596916 got lock (6)
1630778692.596942 trying connect
1630778692.596955 connect failed: Connection refused
1630778692.597564 add peer 0x7f8d30008000: 7 (0x0)
1630778692.599351 sending message 100 to peer 0x7f8d30008000 (4 bytes)
1630778692.599374 sending message 111 to peer 0x7f8d30008000 (8 bytes)
1630778692.599385 sending message 101 to peer 0x7f8d30008000 (15 bytes)
1630778692.599393 sending message 109 to peer 0x7f8d30008000 (4 bytes)
1630778692.599426 sending message 102 to peer 0x7f8d30008000 (13 bytes)
1630778692.599434 sending message 108 to peer 0x7f8d30008000 (20 bytes)
1630778692.599443 sending message 112 to peer 0x7f8d30008000 (58 bytes)
1630778692.599450 sending message 112 to peer 0x7f8d30008000 (5 bytes)
1630778692.599458 sending message 112 to peer 0x7f8d30008000 (5 bytes)
1630778692.599466 sending message 112 to peer 0x7f8d30008000 (6 bytes)
1630778692.599474 sending message 112 to peer 0x7f8d30008000 (6 bytes)
1630778692.599481 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.599489 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.599497 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599505 sending message 112 to peer 0x7f8d30008000 (14 bytes)
1630778692.599513 sending message 112 to peer 0x7f8d30008000 (19 bytes)
1630778692.599520 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.599528 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.599537 sending message 112 to peer 0x7f8d30008000 (15 bytes)
1630778692.599544 sending message 112 to peer 0x7f8d30008000 (21 bytes)
1630778692.599551 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599559 sending message 112 to peer 0x7f8d30008000 (7 bytes)
1630778692.599566 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599574 sending message 112 to peer 0x7f8d30008000 (7 bytes)
1630778692.599582 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599589 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.599596 sending message 112 to peer 0x7f8d30008000 (21 bytes)
1630778692.599604 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599611 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.599620 sending message 112 to peer 0x7f8d30008000 (16 bytes)
1630778692.599629 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599636 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.599644 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.599651 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599659 sending message 112 to peer 0x7f8d30008000 (8 bytes)
1630778692.599666 sending message 112 to peer 0x7f8d30008000 (8 bytes)
1630778692.599674 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599682 sending message 112 to peer 0x7f8d30008000 (7 bytes)
1630778692.599689 sending message 112 to peer 0x7f8d30008000 (7 bytes)
1630778692.599698 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.599705 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.599713 sending message 112 to peer 0x7f8d30008000 (15 bytes)
1630778692.599720 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599728 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599736 sending message 112 to peer 0x7f8d30008000 (8 bytes)
1630778692.599743 sending message 112 to peer 0x7f8d30008000 (14 bytes)
1630778692.599752 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.599773 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.599779 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.599785 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.599791 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.599796 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.599820 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.599825 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599830 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599835 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599841 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599845 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599850 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.599854 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.599858 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599863 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599867 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599872 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599878 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599883 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.599889 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599893 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599898 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599903 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599907 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599912 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599916 sending message 112 to peer 0x7f8d30008000 (8 bytes)
1630778692.599921 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.599926 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.599931 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.599935 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599940 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599945 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599949 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.599954 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599959 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599964 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599969 sending message 112 to peer 0x7f8d30008000 (8 bytes)
1630778692.599974 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599979 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599983 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599988 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.599994 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600000 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600005 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600011 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600016 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600031 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600038 sending message 112 to peer 0x7f8d30008000 (8 bytes)
1630778692.600042 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600048 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600053 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600057 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600060 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600064 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600068 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600073 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600079 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600123 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600133 sending message 112 to peer 0x7f8d30008000 (8 bytes)
1630778692.600139 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600145 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600151 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600157 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600162 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600167 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600172 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600176 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600180 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600184 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600189 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600193 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600197 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600203 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600206 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600211 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600216 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600220 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600225 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600230 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600234 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600238 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600243 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600247 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600253 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600258 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600263 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600268 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600274 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600279 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600285 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600289 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600293 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600298 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600302 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600307 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600312 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.600316 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600321 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600327 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600334 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600339 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600344 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.600348 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600353 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600358 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600362 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600367 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600371 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600376 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600381 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600386 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.600390 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600395 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600399 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600418 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600424 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600428 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600434 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.600440 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600445 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600450 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600455 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600460 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600464 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600469 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.600473 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600478 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600482 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600486 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600491 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600496 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600501 sending message 112 to peer 0x7f8d30008000 (11 bytes)
1630778692.600506 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600511 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600516 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600521 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600527 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600530 sending message 112 to peer 0x7f8d30008000 (21 bytes)
1630778692.600535 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600540 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.600545 sending message 112 to peer 0x7f8d30008000 (6 bytes)
1630778692.600552 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600557 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600562 sending message 112 to peer 0x7f8d30008000 (24 bytes)
1630778692.600567 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600572 sending message 112 to peer 0x7f8d30008000 (9 bytes)
1630778692.600577 sending message 112 to peer 0x7f8d30008000 (70 bytes)
1630778692.600582 sending message 112 to peer 0x7f8d30008000 (69 bytes)
1630778692.600587 sending message 112 to peer 0x7f8d30008000 (12 bytes)
1630778692.600591 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600595 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600600 sending message 112 to peer 0x7f8d30008000 (24 bytes)
1630778692.600604 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600609 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600613 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600618 sending message 112 to peer 0x7f8d30008000 (10 bytes)
1630778692.600622 sending message 112 to peer 0x7f8d30008000 (13 bytes)
1630778692.600628 sending message 112 to peer 0x7f8d30008000 (15 bytes)
1630778692.600632 sending message 112 to peer 0x7f8d30008000 (5 bytes)
1630778692.600647 sending message 104 to peer 0x7f8d30008000 (0 bytes)
1630778692.600654 sending message 110 to peer 0x7f8d30008000 (0 bytes)
1630778692.600659 sending message 107 to peer 0x7f8d30008000 (4 bytes)
1630778692.600664 sending message 105 to peer 0x7f8d30008000 (60 bytes)
1630778692.600668 sending message 105 to peer 0x7f8d30008000 (66 bytes)
1630778692.600673 sending message 105 to peer 0x7f8d30008000 (26 bytes)
1630778692.600677 sending message 105 to peer 0x7f8d30008000 (15 bytes)
1630778692.600682 sending message 105 to peer 0x7f8d30008000 (26 bytes)
1630778692.600687 sending message 105 to peer 0x7f8d30008000 (14 bytes)
1630778692.600691 sending message 105 to peer 0x7f8d30008000 (17 bytes)
1630778692.600695 sending message 105 to peer 0x7f8d30008000 (24 bytes)
1630778692.600700 sending message 105 to peer 0x7f8d30008000 (15 bytes)
1630778692.600718 sending message 105 to peer 0x7f8d30008000 (43 bytes)
1630778692.600724 sending message 105 to peer 0x7f8d30008000 (27 bytes)
1630778692.600729 sending message 105 to peer 0x7f8d30008000 (23 bytes)
1630778692.600734 sending message 105 to peer 0x7f8d30008000 (419 bytes)
1630778692.600741 sending message 105 to peer 0x7f8d30008000 (64 bytes)
1630778692.600746 sending message 105 to peer 0x7f8d30008000 (19 bytes)
1630778692.600751 sending message 105 to peer 0x7f8d30008000 (20 bytes)
1630778692.600755 sending message 105 to peer 0x7f8d30008000 (22 bytes)
1630778692.600760 sending message 105 to peer 0x7f8d30008000 (20 bytes)
1630778692.600764 sending message 105 to peer 0x7f8d30008000 (25 bytes)
1630778692.600769 sending message 105 to peer 0x7f8d30008000 (57 bytes)
1630778692.600794 sending message 105 to peer 0x7f8d30008000 (18 bytes)
1630778692.600799 sending message 105 to peer 0x7f8d30008000 (19 bytes)
1630778692.600804 sending message 105 to peer 0x7f8d30008000 (21 bytes)
1630778692.600808 sending message 105 to peer 0x7f8d30008000 (61 bytes)
1630778692.600812 sending message 105 to peer 0x7f8d30008000 (32 bytes)
1630778692.600817 sending message 105 to peer 0x7f8d30008000 (8 bytes)
1630778692.600822 sending message 105 to peer 0x7f8d30008000 (27 bytes)
1630778692.600827 sending message 105 to peer 0x7f8d30008000 (35 bytes)
1630778692.600832 sending message 105 to peer 0x7f8d30008000 (11 bytes)
1630778692.600855 sending message 105 to peer 0x7f8d30008000 (8 bytes)
1630778692.600859 sending message 105 to peer 0x7f8d30008000 (32 bytes)
1630778692.600863 sending message 105 to peer 0x7f8d30008000 (31 bytes)
1630778692.600867 sending message 105 to peer 0x7f8d30008000 (34 bytes)
1630778692.600870 sending message 105 to peer 0x7f8d30008000 (16 bytes)
1630778692.600874 sending message 105 to peer 0x7f8d30008000 (42 bytes)
1630778692.600877 sending message 105 to peer 0x7f8d30008000 (14 bytes)
1630778692.600881 sending message 105 to peer 0x7f8d30008000 (9 bytes)
1630778692.600885 sending message 105 to peer 0x7f8d30008000 (10 bytes)
1630778692.600890 sending message 105 to peer 0x7f8d30008000 (28 bytes)
1630778692.600894 sending message 105 to peer 0x7f8d30008000 (31 bytes)
1630778692.600899 sending message 105 to peer 0x7f8d30008000 (32 bytes)
1630778692.600903 sending message 105 to peer 0x7f8d30008000 (29 bytes)
1630778692.600908 sending message 105 to peer 0x7f8d30008000 (55 bytes)
1630778692.600912 sending message 105 to peer 0x7f8d30008000 (108 bytes)
1630778692.600918 sending message 105 to peer 0x7f8d30008000 (61 bytes)
1630778692.600922 sending message 105 to peer 0x7f8d30008000 (61 bytes)
1630778692.600926 sending message 105 to peer 0x7f8d30008000 (57 bytes)
1630778692.600936 sending message 105 to peer 0x7f8d30008000 (30 bytes)
1630778692.600941 sending message 105 to peer 0x7f8d30008000 (49 bytes)
1630778692.600945 sending message 105 to peer 0x7f8d30008000 (44 bytes)
1630778692.600950 sending message 105 to peer 0x7f8d30008000 (74 bytes)
1630778692.600954 sending message 105 to peer 0x7f8d30008000 (110 bytes)
1630778692.600959 sending message 105 to peer 0x7f8d30008000 (26 bytes)
1630778692.600963 sending message 105 to peer 0x7f8d30008000 (22 bytes)
1630778692.600968 sending message 105 to peer 0x7f8d30008000 (519 bytes)
1630778692.600973 sending message 105 to peer 0x7f8d30008000 (22 bytes)
1630778692.600980 sending message 106 to peer 0x7f8d30008000 (0 bytes)
1630778692.600998 cmd_pack_argv: argv[0]=new
1630778692.601008 sending message 200 to peer 0x7f8d30008000 (8 bytes)
1630778692.601013 client loop enter
1630778692.601120 client_signal: Child exited: 20
1630778692.673021 peer 0x7f8d30008000 message 207
1630778692.673035 sending message 208 to peer 0x7f8d30008000 (0 bytes)

**Comment by nicm** [comment]
Attach server log to this issue please.

tmux has no idea how long you have held down Ctrl so this seems like a terminal, or perhaps more likely macOS, issue.

**Comment by sdondley** [comment]
I just found the issue. It's my config. Buried in my config file I have this:

 set-hook -g pane-focus-in 'run-shell ~/bin/scene_switcher.pl'
 
 The script is dependent upon having specific tmux session names and panes open. I had been running under this tmux session for months. Since I am no longer using that tmux session, it's throwing errors. This would explain why I haven't seen this behavior until now.
 
 Commenting out the line above fixed the issue and everything still works with focus-events set to "on".
