### ISSUE TITLE
feature request: negative indexing for format vars #{=-12:pane_current_path}

### ISSUE THREAD

**Issue by unhammer** [tmux/tmux#287]
e.g. if pwd was "/home/atomicllamazombie/hacks/phdthesis" then `#{=-12:pane_current_path}`expands to  "ks/phdthesis"

**Comment by ThomasAdam** [comment]
At this point, use the shell.

**Comment by nicm** [comment]
Try this [xyz.diff.txt](https://github.com/tmux/tmux/files/109882/xyz.diff.txt)

**Comment by unhammer** [comment]
Nice, that works great =D

**Comment by nicm** [comment]
Applied now.
