### ISSUE TITLE
Can't find hicolor icons

### ISSUE THREAD

**Issue by gadefox** [tmux/tmux#2870]
Could you please provide icons (16x16, 24x24, 32x32 etc.) based on the left image in logo.svg. Thanks

**Comment by nicm** [comment]
I don't know what this means.

**Comment by nicm** [comment]
All the images are here https://github.com/tmux/tmux/tree/master/logo.

**Comment by gadefox** [comment]
Here's an example of what I mean: https://github.com/rockowitz/ddcutil/tree/master/icons/hicolor. Technically it's an SVG file without the text "tmux" (only the image) converted to PNG image w/ specific size..

**Comment by nicm** [comment]
OK you will need to make them yourself, you can probably do it with ImageMagick.

**Comment by gadefox** [comment]
I'm happy to upload all created icons. Please let me know..

**Comment by nicm** [comment]
If you add them to this issue I can put them in Git, I don't have any use for them myself but maybe other people will want them.  Thanks.

**Comment by gadefox** [comment]
[here](https://ulozto.net/tamhle/kyEVaSA8zUeb)

**Comment by nicm** [comment]
Thanks.
