### ISSUE TITLE
Feature: A way of specifying "parent pane" from a subprocess started from within that pane

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2871]
### Issue description

The way I know of referring to the pane id of the pane in which a process is started is ``-t :.``, for instance if one wants to set some pane option from the process, they would do ``tmux set-option -pt :. @optionname optionvalue``. This works well if the focus remains inside the pane while the process sets the pane options because ``current pane == parent pane``. If the user were to click on some other pane in the meanwhile, the process will end up setting the new pane's options because ``current pane != parent pane``. It would be nice to have some syntax to pass "parent pane" as the target pane from which a subprocess was run, that way the user need not wait for a slow command to complete before moving the focus to another pane that interests them.

### Required information

Please provide the following information:

* tmux version ``3.3-next``.
* Platform (`uname -sp`) ``Darwin arm``.
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color, tmux-256color.

**Comment by bfrg** [comment]
What about `$TMUX_PANE` or `-t '#{pane_id}'` (same as `-t '#D'`)?

**Comment by reportaman** [comment]
@bfrg ``-t $TMUX_PANE`` seems to always work, no need to worry about timing of focus! ``-t '#{pane_id}'`` or ``-t '#D'`` give an error by themselves ``no such pane: #D``. Even if pane id was captured sometime early in the process, if it is captured by implying "current pane", then that can go wrong. Seems like tmux is setting environment variable ``TMUX_PANE`` at the time pane is created, given its an environment variable, any process started from a shell in that pane will inherit it correctly. Will wait for @nicm to confirm, most likely you nailed it with ``-t $TMUX_PANE``.

**Comment by bfrg** [comment]
Indeed, using `#{pane_id}` is trickier than`$TMUX_PANE`. This is from `tmux(1)`:
```
The pane ID is passed to the child process of the pane in the TMUX_PANE environment variable.
```

**Comment by nicm** [comment]
tmux should work out the pane from the tty if you don't give `-t` or use `-t:.`, are you redirecting stdin? If so you will need to use `TMUX_PANE`.

**Comment by reportaman** [comment]
@nicm I see, thanks! No, I was not redirecting stdin, didn't know the behavior on not passing ``-t``. I'll continue using ``-t $TMUX_PANE`` as it is more explicit, and just works in my case. Could test without ``-t`` at some later point, didn't try that as am in a middle of some edits & ``-t $TMUX_PANE`` just works...
