### ISSUE TITLE
Eager argument parsing in `if-shell` makes it impossible to use it for backward incompatible changes

### ISSUE THREAD

**Issue by ilya-bobyr** [tmux/tmux#2872]
Change https://github.com/tmux/tmux/commit/210e71edf36198e3f22525e7f548a71a5681d25c modified, among other things, [behavior of the `if-shell` parsing logic][diff].

After the change, both command arguments are now parsed before the command is executed.
And they both need to be valid tmux commands, according to the current syntax.

I've used `if-shell` to have a config compatible with different versions of tmux, by first setting and then checking environment variables, that would hold the current version of tmux.

Something like this:
```bash
run-shell "tmux set-environment -g TMUX_VERSION_MAJOR $(tmux -V | cut -d' ' -f2 | cut -d'.' -f1 | sed 's/[^0-9]*//g')"
run-shell "tmux set-environment -g TMUX_VERSION_MINOR $(tmux -V | cut -d' ' -f2 | cut -d'.' -f2 | sed 's/[^0-9]*//g')"

if-shell 'test $TMUX_VERSION_MAJOR -le 1 -o \( $TMUX_VERSION_MAJOR -eq 2 -a $TMUX_VERSION_MINOR -lt 4 \)' 'bind-key -t vi-copy v begin-selection'
```

This approach would not work any more if  a command changes its argument syntax.
While `2.4` is a rather old version, and I can remove this particular fix, I wonder if there are any thoughts on supporting a similar kind of upgrades in the future.

I may have stock Ubuntu tmux on one machine, and a HEAD build on another.
If HEAD introduces an incompatible change in any of the commands that I call in my config, I can no longer use the same config.

This is not a blocker for me for the 3.2 migration, so I did not include it in [3.2a questions and comments](https://github.com/tmux/tmux/issues/2737).

[diff]: https://github.com/tmux/tmux/commit/210e71edf36198e3f22525e7f548a71a5681d25c#diff-30b7d96c9aaf10e02fdfffc5285e0652799028bb4f02a818ba5fd05bacbd22b0R92

**Comment by nicm** [comment]
This change will be in 3.3, not 3.2.

It doesn't change anything unless you use `{}` and even if did it only affects tmux command arguments.

Have you got a full example config that doesn't work with master?

**Comment by ilya-bobyr** [comment]
> It doesn't change anything unless you use {} and even if did it only affects tmux command arguments.

Yes, I am talking about the argument parsing.
I'v used `if-shell` to deal with incompatible changes in the command arguments.

> Have you got a full example config that doesn't work with master?

The one that I've posted.
In HEAD tmux `bind-key` does not have the `-t` switch anymore.
A shorter way to reproduce it would be:

```tmux
if-shell 'false' 'bind-key -t vi-copy v begin-selection'
```

With the HEAD tmux, running the above will print an error.
Before https://github.com/tmux/tmux/commit/210e71edf36198e3f22525e7f548a71a5681d25c it would do nothing.

I did not test specifically https://github.com/tmux/tmux/commit/210e71edf36198e3f22525e7f548a71a5681d25c, as it is on a branch that does not build on Ubuntu without additional changes.
I've tried corresponding merges on `master`.
 * Change https://github.com/tmux/tmux/commit/1dec1ca146882572e261f2f2f55d9060c06a0212
   - running the above command does nothing.
 * Change https://github.com/tmux/tmux/commit/95a374d7d20dde938563a9f92c8ffc1e25bd4050
   - pressing "Prefix+:" crashes the server.
 * Change https://github.com/tmux/tmux/commit/7fe3588e49b957b6749c6011a1328fdcd45adc75
   - pressing "Prefix+:" crashes the server.
 * Change https://github.com/tmux/tmux/commit/c7266ca78d5b9f9645ebbf22530cea85ecf2a584
   - running the above command produces a usage error:
     `Usage: bind-key [-nr] [-T key-table] [-N note] key [command [arguments]]`

I know that the behavior changed between https://github.com/tmux/tmux/commit/1dec1ca146882572e261f2f2f55d9060c06a0212 and https://github.com/tmux/tmux/commit/95a374d7d20dde938563a9f92c8ffc1e25bd4050, as I started seeing usage errors during tmux startup after pulling in https://github.com/tmux/tmux/commit/95a374d7d20dde938563a9f92c8ffc1e25bd4050.
And https://github.com/tmux/tmux/commit/1dec1ca146882572e261f2f2f55d9060c06a0212 prints no errors, so I was using it until I've updated the config.

There are 5 commits between these two merges:
```text
* | commit 95a3 (refs/bisect/bad)
|\| Merge: 1dec1 210e
| | Author: Thomas Adam <thomas@xteddy.org>
| | Date:   Mon Aug 23 16:06:46 2021 +0100
| |
| |     Merge branch 'obsd-master' into master
| |
| * commit 210e
| | Author: Nicholas Marriott <nicholas.marriott@gmail.com>
| | Date:   Mon Aug 23 12:33:55 2021 +0000
| |
| |     Move command argument parsing common functions and don't bother to parse
| |     again if given a command rather than a string.
| |
| * commit 03b83
| | Author: Nicholas Marriott <nicholas.marriott@gmail.com>
| | Date:   Mon Aug 23 11:48:21 2021 +0000
| |
| |     Key bindings steal a reference to the command instead of adding their
| |     own, it was correct not to add a reference when parsing, but the
| |     bind-key then needs to add one.
| |
| * commit 1f0c0
| | Author: Nicholas Marriott <nicholas.marriott@gmail.com>
| | Date:   Mon Aug 23 11:08:26 2021 +0000
| |
| |     Revert one of previous, for some reason it is being freed.
| |
| * commit 4a753
| | Author: Nicholas Marriott <nicholas.marriott@gmail.com>
| | Date:   Mon Aug 23 11:04:21 2021 +0000
| |
| |     Fix a few memory leaks.
| |
| * commit 3ed3
| | Author: Nicholas Marriott <nicholas.marriott@gmail.com>
| | Date:   Mon Aug 23 08:17:41 2021 +0000
| |
| |     Limit width and height to tty correctly, GitHub issue 2843.
| |
* | commit 1dec1 (working)
|\| Merge: bc71 2e9ba
| | Author: Thomas Adam <thomas@xteddy.org>
| | Date:   Sun Aug 22 18:01:18 2021 +0100
| |
| |     Merge branch 'obsd-master' into master
| |
```

I've looked at all 5 commits and https://github.com/tmux/tmux/commit/210e71edf36198e3f22525e7f548a71a5681d25c seems the only relevant one.
The other 4 are rather simple changes in areas that are not related to argument parsing.
Thought, maybe I did miss something.

P.S. It is a bit inconvenient that all the development commits are on a branch with a different build system.
Makes it harder for others to run `git bisect` among other things.

**Comment by nicm** [comment]
Oh yes, I see what you mean - without `-F` it stored the command and parsed it when the shell command finished.

Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/7140071/x.diff.txt)

I am only going to change `if-shell` and `run-shell -C` and leave `confirm-before` as it is now.

**Comment by nicm** [comment]
There is a bug in this, few minutes...

**Comment by nicm** [comment]
Try this instead please: [y.diff.txt](https://github.com/tmux/tmux/files/7140113/y.diff.txt)

**Comment by nicm** [comment]
To do the same thing in future you should be able to use `%if` and `#{version}`, for example:
~~~~
%if #{m/r:^3.[01]$,#{version}}
xyz
%endif
~~~~
I don't remember what versions these were added in though, fairly recently.

**Comment by ilya-bobyr** [comment]
> Try this instead please: [y.diff.txt](https://github.com/tmux/tmux/files/7140113/y.diff.txt)

Yes, after applying this change to master and running

```tmux
if-shell 'false' 'bind-key -t vi-copy v begin-selection'
```
the usage error is not shown any more

> [...]
> 
> I am only going to change `if-shell` and `run-shell -C` and leave `confirm-before` as it is now.

> To do the same thing in future you should be able to use `%if` and `#{version}`, for example:
> 
> ```
> %if #{m/r:^3.[01]$,#{version}}
> xyz
> %endif
> ```
> 
> I don't remember what versions these were added in though, fairly recently.

If there is a better way to do it, maybe do not apply this patch at all?
It does make the configuration language more complex if different commands parse their arguments at different points in time.

If using `%if` is the intended way to support this functionality going forward, here is a PR to update `tmux.1` with an example: https://github.com/tmux/tmux/pull/2873

**Comment by nicm** [comment]
> It does make the configuration language more complex if different commands parse their arguments at different points in time.

I don't think it makes any difference for `confirm-before`.

I kind of think it woud be better to drop support for string command arguments and require `{}` but that would be a big break in compatibility, plus we need an alternative or support for aliases, and it would probably close off some uses for `#{}`, We also kind of need `#{}` to be applied consistently to all string arguments across the board so that there is a common way for "variables" to be passed into commands at execution time, but that would be a big break too because suddenly `set` would behave like `set -F` and require escaping.

**Comment by nicm** [comment]
Well, the parser could easily remember whether a string argument was `"` or `'` and only expand `#{}` in `"`s. But this would break everyone's configs as well.

**Comment by nicm** [comment]
If we don't apply the patch, then `run-shell`, `if-shell`, `confirm-before` still parse when they are executed, but `command-prompt`, `display-panes` do it when they finish (in order to replace `%%`).

TBH in an ideal world I think what I would do is:

- Commands given to other commands are all parsed immediately at parse time, basically either they have to be `{}` or strings becomes treated like `{}`.  So `if-shell` never gets string arguments, only a commands argument.
- Parser tags string arguments as `"` or `'`.
- Before a command is executed, a callback is fired to get a format tree, then each `"` argument has formats expanded (other stuff could be expanded at the same time like `\n` which would simplify the parser).
- `%%` expansion would remain a second expansion step, it could also apply only to `"` arguments.
- All `-F` flags and inline format expansion become no-ops or removed.
- Options would need to support commands as native arguments for both user options and hooks.
- `command-alias` is replaced with something else where the name and commands are given separately so the commands can be parsed up front (more like a function). An equivalent to the shell's argument accessor stuff like `$1` and `"$@"` would need to be expanded at execution time.
- I think some way to do execution type parsing would need to remain, an equivalent of `eval` - maybe `run -C` stays like this.
 
This make tmux's command syntax significantly more consistent and allow some more powerful stuff in future, but it would break every config every written up to now.

**Comment by ilya-bobyr** [comment]
> If we don't apply the patch, then `run-shell`, `if-shell`, `confirm-before` still parse when they are executed, but `command-prompt`, `display-panes` do it when they finish (in order to replace `%%`).

Apparently, I am the only person who complained so far.
And if there is a better mechanism to support version compatibility, are there any other use cases for  lazy parsing in `if-shell`?
As for `run-shell -C` and `confirm-before`, I am not sure if lazy parsing there is a good thing.

Maybe, some more complicated cases could benefit from a dedicated `eval` command.
 
> TBH in an ideal world I think what I would do is:
> 
>     * Commands given to other commands are all parsed immediately at parse time, basically either they have to be `{}` or strings becomes treated like `{}`.  So `if-shell` never gets string arguments, only a commands argument.
> 
>     * Parser tags string arguments as `"` or `'`.
> 
>     * Before a command is executed, a callback is fired to get a format tree, then each `"` argument has formats expanded (other stuff could be expanded at the same time like `\n` which would simplify the parser).
> 
>     * `%%` expansion would remain a second expansion step, it could also apply only to `"` arguments.
> 
>     * All `-F` flags and inline format expansion become no-ops or removed.
> 
>     * Options would need to support commands as native arguments for both user options and hooks.
> 
>     * `command-alias` is replaced with something else where the name and commands are given separately so the commands can be parsed up front (more like a function). An equivalent to the shell's argument accessor stuff like `$1` and `"$@"` would need to be expanded at execution time.
> 
>     * I think some way to do execution type parsing would need to remain, an equivalent of `eval` - maybe `run -C` stays like this.
> 
> 
> This make tmux's command syntax significantly more consistent and allow some more powerful stuff in future, but it would break every config every written up to now.

I think, making the language more consistent is a good thing to do.
It reduces the mental burden for the users.  Even if they need to make an adjustment at some point.

There are probably ways to make the breakage somewhat gradual.
For example, when switching from lazy to eager parsing, the command could do both parsing for a number of releases.
Eager parsing results are just stored next to the argument.
When doing the lazy parsing, compare the result to the eager parse result.
If the results are not identical, show a warning.
The warning could tell in which version the command is going to switch to eager mode.
Link to some documentation.  And maybe even offer an option on how to suppress the warning for some time.

It is all additional work.  So, for some changes, it is probably OK to just break compatibility.
Version checks can be used if one wants a config compatible with multiple versions of tmux.

As for the implementation details, I am not really familiar with tmux source code enough to suggest anything =)
When you describe seems reasonable.
Though, if lazy parsing is limited to a single dedicated `eval` command, maybe it would be OK for the parser to support just this command in a special way.  And all the other commands that take commands as arguments would expect a parse tree.

**Comment by nicm** [comment]
Yes it could probably be done in stages, although that does add a lot of work.

`run -C` is basically an `eval` command at the moment, the point is that if all parsing moved to being up front, that would need to be preserved or an alternative added.

I think I will apply this change, there is no point in breaking stuff unnecessarily.

I have put this on the todo list and will revisit it at some point.

Thanks!
