### ISSUE TITLE
Feature: add pane_current_command_full or change the definition of pane_current_command or add pane_current_command_pid

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2874]
### Issue description

Am unable to figure out full "current command" of a pane reliably on macOS using ``ps`` (``ps`` on maOS is limited, and there is no gnu ``ps`` port for macOS), so this ticket is to request a ``pane_current_command_full`` or to change the definition of existing ``pane_current_command`` to return full command.

This also affects tmux-resurrect as it tries to find the process names using ``ps``.

> The specific problem I face with ``ps`` on macOS is that it does not have `` --sort`` switch, so one cannot sort child processes of a pane by their start time. Moreover I don't know how to find the child that is currently active in tty (was thinking start time would be a way to know, but that doesn't seem reliable). If there is a workaround that gives the current full active command on macOS I will be more than happy to just use that.

Another option would be to provide ``pane_current_command_pid`` so one can use whatever utility they want to use to find the full command. That would work I think?

### Required information

Please provide the following information:

* tmux version (`tmux -V`) 3.3-next.
* Platform (`uname -sp`) Darwin arm.
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color, tmux-256color.

**Comment by nicm** [comment]
I don't see a need for this in tmux itself and it would be a pain to implement it for every platform, not to mention that I can't easily see how to do it on macOS.

You should be able to work out the PID from the tty. Try something like `ps -t /dev/ttys007 -ostate,pid|awk '/\+ / {print $2};'`

**Comment by reportaman** [comment]
@nicm Thanks!!! that recipe ``ps -t pane_tty`` works very well!
