### ISSUE TITLE
[Bug?]: mouse events are not reported after the escape sequences [?1001s [?1002h [?1006h

### ISSUE THREAD

**Issue by gadefox** [tmux/tmux#2876]
Please try steps bellow:
-- launch tmux
-- launch mc (Midnight Commander)
-- you should be able to click on menu items etc. etc., but you can't..

**Explanation**: `mc` sends 3 escape sequences to the terminal after launching the app and before ending. You have to send all mouse events back to `mc` in this case via escape sequences and disable selection (yellow color)..

**See**: `mc` source code (file lib/mouse.c) and for example `st` terminal source code for more information..

**Comment by nicm** [comment]
What is the problem? Did you turn the `mouse` option on? Where are the logs?

**Comment by gadefox** [comment]
> Did you turn the mouse option on?

Of course!

Please launch `mc` from std terminal (gnome / st / xterm) and compare with tmux. You'll see the problem immediately. I believe this is not implemented or wrongly implemented becuase the mouse option is on, I can select panes w/ the mouse, but when I launch `mc` and I want to click menu, button or select the directory, I can't and the mouse event is blocked (handled) by tmux - which should no. This is how all terminals should work, but maybe `tmux` is an exception..

**Comment by nicm** [comment]
Show logs from reproducing please.

**Comment by gadefox** [comment]
I belive you don't need my logs to reproduce this behavior. Please follow the steps bellow or feel free to close this issue - I'm just the messenger..

1. [in my case it's Linux] Open your system terminal (in my case `st` or `gnome-terminal')
2. [in terminal] Run `tmux' command [mouse option is `on` in `tmux.conf`]
3. [Install `mc`.. Please note Midnight Commander `mc` is world known 'light' file mananger]
3. [in `tmux` pane] Run 'mc' command
4. [in `tmux` pane]Click w/ the mouse

**Problem** Clicking in the `tmux` pane w/ the mouse starts text (yellow) selection

**Expected behavious**: The mouse events should be sent to `mc` via escape seq.(s), so I can use `mc` w/ the mouse - no `tmux` (yellow) selection..
1. [in my case it's Linux] Open your system terminal (in my case `st` or `gnome-terminal')
3. [in terminal window] Run 'mc' command
4. [in terminal window]Click w/ the mouse

This is best I can do and I hope you don't need screenshots and / or logs to follow easy steps..

**Comment by nicm** [comment]
Look, before I spend time installing programs and terminals, figuring out how to configure them and trying to work out exactly what you are doing and whether it is the same as what I try, I want to see logs which will tell me in two minutes whether your program is sending the mouse escape sequences or not.

**Comment by nicm** [comment]
I need the server log, see here https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md#how-do-i-get-logs-from-tmux

**Comment by gadefox** [comment]
Okay, I'll send you the logs later..

**Comment by gadefox** [comment]
Please note I'll delete this [file](https://ulozto.net/tamhle/Rtg0saT4kmCR#!ZGOvZmR2Z2VjZJSxMwSyZQNkLwplA1WQoJg5JGEwoJW+DGMvAt==) in 24 hrs..

**Comment by gadefox** [comment]
You should find the following escape sequences: `ESC_STR "[?1001s" ESC_STR "[?1000h" ESC_STR "[?1006h"` or `ESC_STR "[?1001s" ESC_STR "[?1002h" ESC_STR "[?1006h"`

**Comment by nicm** [comment]
`mc` is not asking tmux to turn on the mouse, you will need to figure out how to configure it to do so. Maybe you want to use `mc -x`?

**Comment by gadefox** [comment]
Oh my.. Please let me explain, why I wasted your time and mine too.. I'm using the alias `mc --xterm` for `st` terminal and I don't need to use this option for `gnome` terminal, because I can see in their code they send these esc seq(s) automatically, see [here](https://github.com/MidnightCommander/mc/blob/master/lib/tty/tty.c).

`
return force_xterm
        || strncmp (termvalue, "**xterm**", 5) == 0
        || strncmp (termvalue, "konsole", 7) == 0
        || strncmp (termvalue, "rxvt", 4) == 0
        || strcmp (termvalue, "Eterm") == 0
        || strcmp (termvalue, "dtterm") == 0
        || strncmp (termvalue, "alacritty", 9) == 0
        || strncmp (termvalue, "foot", 4) == 0
        || strncmp (termvalue, ">>>screen<<<", 6) == 0
        || strncmp (termvalue, ">>>tmux<<<", 4) == 0;
`

But yes, the `--xterm` or `-x` option solves the problem. Tx a lot..

**Comment by nicm** [comment]
Maybe your mc version is too old for this check, or the check is broken.
