### ISSUE TITLE
Paste Duplicate issue.

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#2877]
### Issue description
Copy  export variables are duplicated

```
export AWS_SECRET_ACCESS_KEY=dfgdfgdfgdfgdfgdf
export AWS_DEFAULT_REGION=us-west-2
export WS_SESSION_TOKEN="sdfffffffffffffffffffffljkhasldkfjhklsadjfhlksadjfhlkasdjhflkjsdhflkjsdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
```
**With In TMUX**
<img width="1610" alt="Screen Shot 2021-09-13 at 10 28 13 am" src="https://user-images.githubusercontent.com/7599183/133008017-c19ba1ec-e8a4-49ab-8eaa-09849a95b706.png">

**Outside tmux**
<img width="1610" alt="Screen Shot 2021-09-13 at 10 27 24 am" src="https://user-images.githubusercontent.com/7599183/133007994-3567da0a-08e4-4200-8a0c-7fbaf1ea2391.png">
### Required information

Please provide the following information:

* tmux version (`tmux -V`). = tmux 3.2a
* Platform (`uname -sp`). = Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`).
(Inside tmux) screen-256color
(outside tmux)  xterm-256color
* Logs from tmux 
 
[tmux-client-63131.log](https://github.com/tmux/tmux/files/7150573/tmux-client-63131.log)
[tmux-out-63133.log](https://github.com/tmux/tmux/files/7150574/tmux-out-63133.log)
[tmux-server-63133.log](https://github.com/tmux/tmux/files/7150575/tmux-server-63133.log)

**Comment by nicm** [comment]
How long are these meant to be? This is what tmux is receiving from the terminal:
~~~~
1631491517.812231 /dev/ttys000: keys are 768 (export AWS_SECRET_ACCESS_KEY=dfgdfgdfgdfgdf
gdf\rexport AWS_DEFAULT_REGION=us-west-2\rexport WS_SESSION_TOKEN="sdffffffffffffffffffff
fljkhasldkfjhklsadjfhlksadjfhlkasdjhflkjsdhflkjsddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddd)
...
1631491517.869086 /dev/ttys000: keys are 350 (ddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddd"\r)
~~~~
So a total of 1118 bytes pasted.

**Comment by lanox** [comment]
@nicm  I am not sure I understand your question, that is literally how long is the key from AWS  all I have is just replaced the actual key with random text but the length is the same.

**Comment by nicm** [comment]
Right, so what is the problem?

**Comment by nicm** [comment]
tmux is receiving 1118 bytes and that seems to be what you are pasting. In the screenshot the shell prompt for `WS_SESSION_TOKEN` is six lines both with and without tmux, so it looks right to me?

**Comment by lanox** [comment]
I see what you are saying, but may I ask why do I see export doubling up ? in tmux as shown in the picture, but outside tmux I do not see that?

**Comment by nicm** [comment]
Seems like your shell is doing it, what shell are you using?

**Comment by lanox** [comment]
Also I just want to clarify something, as shown in the picture above while I am not in tmux if I copy and paste those 3 export lines they show as 3 lines, while in tmux pasting same 3 lines are been duplicated.

inside tmux
```
lpuljic λ echo $SHELL
/usr/local/bin/zsh
```
Outside tmux
```
lpuljic λ echo $SHELL
/usr/local/bin/zsh
lpuljic λ
```

**Comment by nicm** [comment]
Maybe the shell is turning on bracketed paste outside tmux but not inside?

**Comment by lanox** [comment]
So would that be tmux issue ? or do I need to do something? would you be able to point me in the direction to troubleshoot? 

do you have the same symptom if you copy and paste the text from the first message ?

**Comment by nicm** [comment]
It would be a shell problem. tmux is just sending what you paste to the shell and displaying what it prints.

**Comment by lanox** [comment]
Okay can I just confirm one thing before closing this issue. 

What is confusing me is that while I am in iTerm2 and using zsh as my default shell I do not see that problem as mentioned in my first post, however as soon as I start tmux I have that symptom, my question here is if its shell issue why am I not seen that while not in tmux?

sorry for all the question maybe I am just not seen something here.

Thanks

**Comment by nicm** [comment]
Maybe tmux sends the data as a big block and iTerm2 sends it line by line?

**Comment by lanox** [comment]
@ncim  sorry but your responses are confusing ? can you reproduce the same symptoms I have reported usin zsh shell ?

**Comment by nicm** [comment]
I don't use zsh and when I try it just shows the text highlighted:

![Screenshot 2021-09-14 at 12 17 39](https://user-images.githubusercontent.com/304243/133248153-f3ebd33c-e635-460f-964d-b1041e1452b0.png)

I don't know anything about zsh, why don't you ask the zsh developers?

It works fine for me with bash.

**Comment by lanox** [comment]
alright thank you very weird i will try and figure it out. 

It's very hard for me to ask them as soon as I tell them that it is working fine while I am not in tmux they will tell me to go and speak to tmux developer. 

But no drama I will try to work out what is going on. 

Thanks
