### ISSUE TITLE
User hooks

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2879]
### Issue description

At the moment, it is possible to set a user hook, but it doesn't run. This issue covers a couple of changes that would make user hooks more useful.

1. Make user hooks functional.
    For example running this does not do anything: ``tmux set-hook -gR @helloworld 'split-window'``. Though ``tmux show-hook -g  @helloworld`` does show ``@helloworld`` hook.

2. Clarify the ``-R`` option of ``set-hook``. By "immediately" does that mean: 
    a) the hook is enqueued in Tmux's event queue immediately, and will run in some start-end order with tmux's internal hooks,
    b) it completely disregards tmux's internal queues and will run without any ordering with tmux's internal hooks?

3. Proposal: If ``-R`` option of ``set-hook`` for user hooks does not work like 2.a but more like 2.b, then add support for 2.a where a ``set-hook -R`` inserts the user hook in tmux's event queue. Maybe a different option like ``-Q`` (enQueue) or ``-E`` (Enqueue) as a way for user to enqueue the hook in tmux's internal event queue if you wish to preserve the meaning of ``-R`` if it is like 2.b.

Rationale: This will ensure some ordering guarantees between an application's event hooks (autocommands of vim/nvim) running inside tmux, and tmux's own event hooks like pane-focus-in. Which will make it seamless to integrate any application's event model with tmux's, as if the application were a part of tmux. I am filing this after having considered external locks, locks are insufficient as they don't guarantee certain desired execution order, like a script launched by FocusGained autocommand of vim/nvim and a script launched by the corresponding pane-focus-in of tmux. If one wishes that the script launched by FocusGained starts execution after  script launched by pane-focus-in finishes, in that order, it is not guaranteed at the moment. There can be other more real examples...

### Required information

Please provide the following information:

* tmux version (`tmux -V`) next-3.3.
* Platform (`uname -sp`) Darwin arm.
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by ThomasAdam** [comment]
Hey @reportaman 

I suppose something like this will probably work:

```
diff --git a/cmd-set-option.c b/cmd-set-option.c
index fbe32cfae..23b2d80a1 100644
--- a/cmd-set-option.c
+++ b/cmd-set-option.c
@@ -100,13 +100,6 @@ cmd_set_option_exec(struct cmd *self, struct cmdq_item *item)
        /* Expand argument. */
        argument = format_single_from_target(item, args_string(args, 0));
 
-       /* If set-hook -R, fire the hook straight away. */
-       if (cmd_get_entry(self) == &cmd_set_hook_entry && args_has(args, 'R')) {
-               notify_hook(item, argument);
-               free(argument);
-               return (CMD_RETURN_NORMAL);
-       }
-
        /* Parse option name and index. */
        name = options_match(argument, &idx, &ambiguous);
        if (name == NULL) {
@@ -225,6 +218,11 @@ cmd_set_option_exec(struct cmd *self, struct cmdq_item *item)
 
        options_push_changes(name);
 
+       /* If set-hook -R, fire the hook straight away. */
+       if (args_has(args, 'R')) {
+               notify_hook(item, name);
+               goto out;
+       }
 out:
        free(argument);
        free(expanded);
```

**Comment by reportaman** [comment]
@ThomasAdam @nicm Are user-hooks without -R option inserted in the event hook queue? I don't remember the execution model. Is the hook at the front of the queue fired only after the previous hook has completed execution (am not asking for a feature, just curious). Or is the hook at the front of the queue fired in order, but doesn't wait for the completion of previous hook?

**Comment by nicm** [comment]
I don't think it is necessary to make set-and-run work. It is fine to require the hook to already exist for `-R`.

However, `-R` doesn't work for user hooks since hooks became arrays. I have fixed this now.

Hooks are always queued, there is no way to fire a command that does not go through the command queue.
