### ISSUE TITLE
feature request: #{window_pid} for pid of active command in that window

### ISSUE THREAD

**Issue by unhammer** [tmux/tmux#288]
I thought I could do with #{pane_pid} to format unselected windows in my `window-status-format` but that changes with whatever is the selected pane. Since #W knows the name of the process, I guess it shouldn't be too hard to get the pid?

**Comment by ThomasAdam** [comment]
Umm, what is it you're trying to do here?

**Comment by unhammer** [comment]
Sorry, PEBKAC, I somehow managed to test wrong. The `#{pane_pid}` variable does what I wanted.

**Comment by unhammer** [comment]
Sorry, PEBKAC, I somehow managed to test wrong. The `#{pane_pid}` variable does what I wanted.
