### ISSUE TITLE
Not able to use custom bash function in popup window

### ISSUE THREAD

**Issue by sriramkandukuri** [tmux/tmux#2883]
Hi,

I have custom bash function in my bash rc say
```sh
cheat()
{
    echo "test from popup"
}

tmch()
{
    tmux popup bash -c cheat
}
```
When running `tmch` popup is opening but it says `cheat: command not found`

Thanks,
Sriram.K

**Comment by nicm** [comment]
Typically new shells don't know about functions created in parent shells:
~~~~
$ qqq() { echo foo; }
$ qqq
foo
$ bash -c qqq
bash: qqq: command not found
~~~~
And if you use `bash -c` the new shell is noninteractive so it won't read `.bashrc`.

**Comment by sriramkandukuri** [comment]
Is there any solution for this? except having a file in some path?

**Comment by nicm** [comment]
You could try with `-i` (`bash -ic whatever`) and see if it loads your `.bashrc`.

**Comment by sriramkandukuri** [comment]
Yes that works, thank you.

One more question: is copy mode supported in popups?

**Comment by nicm** [comment]
No it is not.

**Comment by sriramkandukuri** [comment]
OK
