### ISSUE TITLE
`unknown command: left-of` when starting tmux off today's master branch

### ISSUE THREAD

**Issue by lanza** [tmux/tmux#2884]
Quite simply -- I have

```
bind H swap-pane -s {left-of}
bind L swap-pane -s {right-of}
```

in my config and it's reporting the error message in the title upon coming across it.

**Comment by krader1961** [comment]
From the *CHANGE* log:

```
* Parse {} as actual commands immediately, this means the contents of {} has to
  be valid tmux commands as well as matching the syntax.
```

Your commands are not valid tmux commands. Others have noted the same problem recently. See, for example, #2841 and #2839.

**Comment by nicm** [comment]
They need to be quoted and have done for several releases now.
