### ISSUE TITLE
Scrolling with arrow keys in one pane prints 0s or 6s in another pane

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2887]
### Issue description

Scrolling in one pane by pressing and holding Up/Down arrow keys prints spurious 0s/6s in another pane. Terminal in which this is observed is Alacritty & WezTerm, doesn't seem to happen in iTerm2. Here are the logs:

[tmux-client-54595.log](https://github.com/tmux/tmux/files/7174832/tmux-client-54595.log)
[tmux-out-54597.log](https://github.com/tmux/tmux/files/7174833/tmux-out-54597.log)
[tmux-server-54597.log](https://drive.google.com/file/d/1m4brvFJKCDFv8wyKM2DLAiXhkxboI4_S/view?usp=sharing)

Mp4 video:
https://drive.google.com/file/d/1LUnnJ5cAmMDiVXz8noPhhdoo1-JzUea6/view?usp=sharing (either download and view it, or select 1080 as the quality to make sure its legible)

Here's a screenshot from the video that shows the spurious 0s, and 6s (zoom and look at the left edge of the image):
![Screen Shot 2021-09-15 at 9 27 08 PM](https://user-images.githubusercontent.com/71736629/133549396-dd765d3e-372a-4ebb-9abb-9a4099b982fb.png)

### Required information

Please provide the following information:

* tmux version (`tmux -V`) next-3.3.
* Platform (`uname -sp`) Darwin arm.
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color, tmux-256color.

**Comment by nicm** [comment]
Does pressing `C-b r` to trigger tmux to redraw make the spurious characters disappear?

**Comment by nicm** [comment]
Can you reproduce on a smaller terminal please and show me the log? At most 100x40.

**Comment by nicm** [comment]
Does the same thing happen in iTerm2 if you add `set -as terminal-overrides '*:Enmg@:Dsmg@:Clmg@:Cmg@'` to .tmux.conf and restart tmux entirely?

**Comment by reportaman** [comment]
@nicm 

> Does pressing C-b r to trigger tmux to redraw make the spurious characters disappear?

Yes, that makes the spurious characters disappear!

> Can you reproduce on a smaller terminal please and show me the log? At most 100x40.

Tried, it is not reproducible at 100x40 or that neighborhood... The bug is reproducible at height 40 or less, but is reproducible only when number of columns are much larger than 100

> Does the same thing happen in iTerm2 if you add ``set -as terminal-overrides '*:Enmg@:Dsmg@:Clmg@:Cmg@'`` to .tmux.conf and restart tmux entirely?

Yes! adding that setting to .tmux.conf makes it happen in iTerm2. As a sidenote that makes me curious... what does this setting do?

**Comment by nicm** [comment]
Try width 200 or 210.

**Comment by reportaman** [comment]
@nicm Starts happening only at 219 or more columns... Can provide you logs at 219x40 or 220x40... any preference?

**Comment by nicm** [comment]
220

**Comment by reportaman** [comment]
@nicm Attached logs at 220x40:

[tmux-client-58156.log](https://github.com/tmux/tmux/files/7175786/tmux-client-58156.log)
[tmux-out-58158.log](https://github.com/tmux/tmux/files/7175787/tmux-out-58158.log)
[tmux-server-58158.log](https://github.com/tmux/tmux/files/7175790/tmux-server-58158.log)

**Comment by nicm** [comment]
This appears to be a problem with this text:
~~~~
Andrew Skeoch & Sarah Koschak - Birdsong on the Rainforested Island  6:240
~~~~
There is a Unicode character `\342\200\250` just before the 6. This is U+2028 LINE SEPARATOR. utf8proc tells tmux this is a zero width character, so it joins it onto the previous space; however, the terminal is choosing to print it as an actual space which means the cursor is out of position.

If your song titles contain this character, I suggest you remove them.

**Comment by reportaman** [comment]
@nicm Worked, removing the file from the playlist resolved this issue. It was part of mp3 file metadata, will message the author. I wonder what is the best terminal utility to visualize such troublesome characters & sanitize them upfront? Any suggestions?

**Comment by nicm** [comment]
No not really, you can use `cat -v` to see hidden characters.
