### ISSUE TITLE
hidden pane

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2888]
### Issue description

It would be nice to have hidden pane.

Rationale/Benefit: Tmux already provides a handy command ``swap-pane`` to swap two panes. Having a hidden pane (pane not linked to any window) will provide a way to create a "scratch shell" that can be shared between all the panes. Then one can toggle the scratch shell in any pane and toggle back to the original pane (by doing ``swap-pane`` again).

For example, in vim/nvim it is possible to create a "terminal" in a split, do some work in it, then toggle to show the previous buffer in the same split. In future, one can toggle to show the scratch terminal in same or different split. It will still show the work one did previously in it.

Currently it is possible to achieve this behavior by creating a "scratch" window and swap the target pane with the pane in scratch window. The only problem is that it occupies a window, so one needs to delete it before tmux resurrect kicks in to save the windows, doing so also affects last-window state that tmux resurrect saves, etc...

One would then press just one key to toggle between a scratch shell pane and program (like man/vim/etc) that is running in that space.

If there is any interest, this could also be implemented as a hidden window maybe? But thats just implementation detail...

**Comment by nicm** [comment]
I see no need for this, just create a temporary session to store your hidden panes in.

**Comment by reportaman** [comment]
@nicm Sure, though one thing would help: 1) either a way to know upfront what the next/previous/last sessions are that ``switch-client`` would jump to with ``-l / -n / -p`` switches, or 2) a way to pass a filter to ``switch-client`` like ``switch-client -p -f "#{!=:#{session_name},scratch}"`` so it filters out user specified "background"/"hidden"/"temporary" sessions. Luckily, most other commands support a filter for such a thing to make a scratch session not visible. If any interest, I think 2) would require minimal change on plugin writers end for existing codebase.

**Comment by nicm** [comment]
Why not do it afterwards:
~~~~
bind n { switch-client -n ; if -F '#{==:#{session_name},hidden}' switch-client -n }
