### ISSUE TITLE
Crash when calling kill-session with destroy-unattached set

### ISSUE THREAD

**Issue by serban** [tmux/tmux#2889]
## Environment

Key           | Value
------------- | -----
OS            | macOS Big Sur 11.6
Architecture  | ARM 64-bit
iTerm2        | 3.4.10
$TERM Outside | xterm-256color
$TERM Inside  | tmux-256color
tmux          | ~ 3.3-rc (409e121cace098810836e7286a3a55a125424db5 from September 16, 2021)

Also reproducible on Debian testing, x86 64-bit.

## Reproduce

Run the following commands in separate terminals:

```
tmux -vv -f /dev/null new-session -s crash
```

```
tmux new-session -t =crash -s smash \; set-option destroy-unattached
```

```
tmux kill-session -t =smash
```

### Observed Behavior

tmux crashes with `server exited unexpectedly`.

## Logs

* [tmux-server-15656.log](https://github.com/tmux/tmux/files/7180280/tmux-server-15656.log)
* [tmux-client-15654.log](https://github.com/tmux/tmux/files/7180283/tmux-client-15654.log)
* [tmux-out-15656.log](https://github.com/tmux/tmux/files/7180284/tmux-out-15656.log)

**Comment by serban** [comment]
Actually, you don't need the second session. This will suffice:

```
tmux -vv -f /dev/null new-session -s crash \; set-option destroy-unattached
```

```
tmux kill-session -t =crash
```

**Comment by nicm** [comment]
This should be fixed by this change, will be in GitHub later today. Please let me know if you see any further problems. Thanks!
~~~~
--- session.c   13 Aug 2021 06:52:51 -0000      1.89
+++ session.c   17 Sep 2021 07:19:15 -0000
@@ -205,6 +205,9 @@ session_destroy(struct session *s, int n
        struct winlink  *wl;

        log_debug("session %s destroyed (%s)", s->name, from);
+
+       if (s->curw == NULL)
+               return;
        s->curw = NULL;

        RB_REMOVE(sessions, &sessions, s);
