### ISSUE TITLE
When I want to edit past commands, while typing tmux seems to overwrite characters

### ISSUE THREAD

**Issue by donkeysharp** [tmux/tmux#289]
While using tmux, for example I execute something like this:

`mr -rf some/directory/to/remove/*.txt`

Whoops! it was `rm` no `mr`

* Up arrow to edit the command
* I move the cursor to the beginning

The issue comes here, let's say I don't delete "mr" and I write directly rm the result while writing should be:

`rmmr -rf some/directory/to/remove/*.txt`

It should push text to the right, but when I type rm it's like it overwrites characters as if the Insert key would be activated and it looks like:

`rm -rf some/directory/to/remove/*.txt`

I execute it, and the terminal shows this

`rmmr command not found`

and if I go up with up arrow it shows me

`rmmr -rf some/directory/to/remove/*.txt`

The right behavior should be that when I type `rm` it pushes `mr -rf ...`  to the right and not giving that illusion of "overwritting".
Sometimes it seems that it doesn't happen, it pushes text to the right but suddenly it comes again.

**Note**
It does not happen only when setting the cursors on the beggining of the line, it also happens when I type in the middle of a previous command.

I'm using xfce4-terminal on Debian Jessie but the same happens on terminator and xterm, I tested using a .tmux.conf file and without it, the same happens. If it can help this is my .tmux.conf file.

```
set -g base-index 1
set -g pane-base-index 1

bind '%' split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
```

**Comment by nicm** [comment]
Your TERM inside tmux is probably wrong.

**Comment by donkeysharp** [comment]
Do you mean the TERM env-variable?

**Comment by nicm** [comment]
Right

**Comment by donkeysharp** [comment]
what should be the value of TERM variable on tmux?

**Comment by donkeysharp** [comment]
Sorry for the inconvenience, you were right it was TERM, in my .profile it was always setting TERM to xterm-color and ignoring screen value for TERM
