### ISSUE TITLE
[bug] If use tmux, kitty's key map cannot work

### ISSUE THREAD

**Issue by Freed-Wu** [tmux/tmux#2893]
### Issue description

According to <https://stackoverflow.com/questions/16359878/how-to-map-shift-enter/42461580#42461580>:

> Kitty, in ~/.config/kitty/kitty.conf:
> map shift+enter send_text all \x1b[13;2u
> map ctrl+enter send_text all \x1b[13;5u

If don't use tmux, it can work:

```shell
❯ showkey -a

Press any keys - Ctrl-D will terminate this program

^[[13;5u 	27 0033 0x1b
  91 0133 0x5b
  49 0061 0x31
  51 0063 0x33
  59 0073 0x3b
  53 0065 0x35
  117 0165 0x75
^[[13;2u 	27 0033 0x1b
  91 0133 0x5b
  49 0061 0x31
  51 0063 0x33
  59 0073 0x3b
  50 0062 0x32
  117 0165 0x75
```

Press `<C-CR>` and `<S-CR>` will print correct ansi escape code.

However, if use tmux, it cannot work:

```shell
❯ showkey -a

Press any keys - Ctrl-D will terminate this program
```

Press `<C-CR>` and `<S-CR>` will not print anything.

### Required information

* tmux version (`tmux -V`): 3.2a
* Platform (`uname -sp`): Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`): tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`):

```
[261 00:57:38.910834] Application escape mode is not supported, the extended keyboard protocol should be used instead
[261 00:57:38.911013] Application escape mode is not supported, the extended keyboard protocol should be used instead
```

**Comment by nicm** [comment]
What if you set `extended-keys` to `always`?

**Comment by Freed-Wu** [comment]
Thanks!
