### ISSUE TITLE
Color usage has changed between 3.2a and 3.3-rc

### ISSUE THREAD

**Issue by yasuhirokimura** [tmux/tmux#2894]
While testing 3.3-rc I found that color usage has changed between 3.2a and 3.3-rc

1. Debian 11.0 (bullseye) amd64
   1. Console of VirtualBox VM (UEFI)
      1. without tmux
![Debian-11 0-console-no-timux](https://user-images.githubusercontent.com/5249848/133844623-4200b52f-f976-45fe-b079-98a48a59ae72.png)
      2. tmux 3.2a
![Debian-11 0-console-timux-tmux-3 2a](https://user-images.githubusercontent.com/5249848/133844649-20859ed0-49ce-415c-8981-0f1fb24227a5.png)
      3. tmux 3.3-rc
![Debian-11 0-console-timux-tmux-3 3-rc](https://user-images.githubusercontent.com/5249848/133844667-dc7787ca-e1a2-45a3-9c00-76fb02433f4f.png)
   2. PuTTY (https://www.chiark.greenend.org.uk/~sgtatham/putty/)
      1. without tmux
![Debian-11 0-PuTTY-no-timux](https://user-images.githubusercontent.com/5249848/133844754-d4f200ba-2d3c-41ea-bbf1-a27914222fc9.png)
      2. tmux 3.2a
![Debian-11 0-PuTTY-timux-3 2a](https://user-images.githubusercontent.com/5249848/133844802-b8dd8631-05da-489c-acea-31e2caf72d85.png)
      3. tmux 3.3-rc
![Debian-11 0-PuTTY-timux-3 3-rc](https://user-images.githubusercontent.com/5249848/133844820-c5c2564a-f3ff-4c63-bda2-e268c499f56e.png)
   3. RLogin (https://kmiya-culti.github.io/RLogin/)
      1. without tmux
![Debian-11 0-RLogin-no-timux](https://user-images.githubusercontent.com/5249848/133844851-2b96cf66-0b1c-46c5-9415-9aeafed24839.png)
      2. tmux 3.2a
![Debian-11 0-RLogin-timux-3 2a](https://user-images.githubusercontent.com/5249848/133844877-b9cec444-c02d-4c82-b482-cad7c7cf9a17.png)
      3. tmux 3.3-rc
![Debian-11 0-RLogin-timux-3 3-rc](https://user-images.githubusercontent.com/5249848/133844893-b4e25719-7313-4bc6-9a0b-599d3e6b6dfe.png)
2. FreeBSD 13.0-RELEASE amd64
   1. Console of VirtualBox VM (UEFI)
      1. without tmux
![FreeBSD-13 0-RELEASE-console-no-timux](https://user-images.githubusercontent.com/5249848/133845034-bab5d857-64ad-4e04-8254-c17f3d49e86f.png)
      2. tmux 3.2a
![FreeBSD-13 0-RELEASE-console-tmux-3 2a](https://user-images.githubusercontent.com/5249848/133845078-781433e9-0387-44fa-9d2d-6f6cf026bf21.png)
      3. tmux 3.3-rc
![FreeBSD-13 0-RELEASE-console-tmux-3 3-rc](https://user-images.githubusercontent.com/5249848/133845109-0fc16d84-5fb7-4da4-b151-d3727f733aab.png)
   2. PuTTY (https://www.chiark.greenend.org.uk/~sgtatham/putty/)
      1. without tmux
![FreeBSD-13 0-RELEASE-PuTTY-no-timux](https://user-images.githubusercontent.com/5249848/133845162-e3d3bb2e-dc27-4ead-9b22-b6a1708eea40.png)
      2. tmux 3.2a
![FreeBSD-13 0-RELEASE-PuTTY-timux-3 2a](https://user-images.githubusercontent.com/5249848/133845191-d5df9879-6f52-4023-b82a-64b4367218d1.png)
      3. tmux 3.3-rc
![FreeBSD-13 0-RELEASE-PuTTY-timux-3 3-rc](https://user-images.githubusercontent.com/5249848/133845232-8c3fe111-a05b-4b89-b064-fd06ae450d1f.png)
   3. RLogin (https://kmiya-culti.github.io/RLogin/)
      1. without tmux
![FreeBSD-13 0-RELEASE-RLogin-no-timux](https://user-images.githubusercontent.com/5249848/133845278-676eb356-2989-4a6a-9d98-04e4e812d0ed.png)
      2. tmux 3.2a
![FreeBSD-13 0-RELEASE-RLogin-tmux-3 2a](https://user-images.githubusercontent.com/5249848/133845301-b4a5ed6d-7408-4b64-a06f-778880adc532.png)
      3. tmux 3.3-rc
![FreeBSD-13 0-RELEASE-RLogin-tmux-3 3-rc](https://user-images.githubusercontent.com/5249848/133845346-0b56cd46-1525-4d4c-ac04-32a5a1b961a7.png)

As you can see, color usage of 3.2a is almost same as the one without tmux. But 3.3-rc is obviously
different from them. Is is intended change of 3.3?

**Comment by nicm** [comment]
Logs?

**Comment by yasuhirokimura** [comment]
> Logs?

Are only logs of 3.3-rc enough or ones of 3.2a also necessary?

**Comment by nicm** [comment]
3.3 only for the moment.

**Comment by yasuhirokimura** [comment]
Ok I'll take them.

**Comment by yasuhirokimura** [comment]
Logs of  FreeBSD and VirtualBox VM console.

https://www.utahime.org/tmux/tmux-client-2066.log
https://www.utahime.org/tmux/tmux-server-2068.log

Please let me know if you need other cases.

**Comment by nicm** [comment]
This application is sending 256 colour sequences to tmux but your terminal outside is not 256 colour so tmux is forced to translate.

Probably you are getting caught by the fact that the default `TERM` inside tmux is now `tmux-256color` or `screen-256color`.

You can either change `default-terminal` back to `screen` or `tmux`, or if the terminal outside tmux supports 256 colours then set an appropriate `TERM` outside tmux.

**Comment by yasuhirokimura** [comment]
In my case `TERM` is `xterm` outside and `tmux-256color` inside. And if I add `set-option -g default-terminal tmux` to `.tmux.conf` then 3.3-rc behaves same as 3.2a.
Does this mean that something has changed between 3.2a and 3.3-rc about how tmux detects if outside terminal supports 256 color?
