### ISSUE TITLE
pair programming, question/feature

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2895]
So far reading online forums suggests that tmux can be used for pair programming. What does not seem possible is to have two users type in independent panes of the same window at the same time. Am totally shooting in dark, but given tmux has ``Sync`` feature, is it now possible to do that? User-1 typing in pane-1, user-2 typing in pane-2 at the same time, and both being able to see what what either of them is doing? [Wemux](https://github.com/zolrath/wemux) seems to have have a "rogue mode", but chatter on stackoverflow seems to suggest that the users can only type at the same time in different windows not different panes in the same window.

If this is not supported, and is doable, then please consider this also as a feature request.

**Comment by nicm** [comment]
attach -factive-pane

**Comment by reportaman** [comment]
@nicm Wow, thanks! Looks like the ultimate pair programming solution... 

A question from 

>  A client with the active-pane flag allows the active pane to be selected independently of the window's active pane
     used by clients without the flag.  This only affects the cursor position and commands issued from the client;
     other features such as hooks and styles continue to use the window's active pane.

a) Number of simultaneous typing panes: This isn't limited to 2 at a time right, there can be 3 individuals typing in 3 different panes?
b) Hooks: What happens to hooks like pane-focus-in, etc when there are 2 individuals moving around in same shared session? Do either/both of their activities emit these hook events? I don't have a pair programmer colleague right now to test this right away, just curious given I am writing plugin that heavily relies on hooks...

**Comment by nicm** [comment]
The flag means there is a separate active pane for that client, there is still a "real" active pane (used by any clients without -factive-pane) which will be used as the default active pane if tmux has to guess what it is. I'm not sure exactly what will happen with different hooks, you could test it by using a nested tmux and send-keys/run-shell -d.
