### ISSUE TITLE
tmux doesn't always resize popups when the terminal window is resized

### ISSUE THREAD

**Issue by bfrg** [tmux/tmux#2898]
### Issue description

tmux does not always resize the popup windows when the underlying terminal window is resized.

I'm using the tiling window manager [i3](https://github.com/i3/i3) on Linux. Basically, windows can be put in two different modes: **tiling mode** and **floating mode**. Tiling mode is similar to tmux's panes. GUI windows are maximized in the workspace until another window is opened which will split the screen size in half either horizontally or vertically. Floating mode is like what traditional window managers do. Windows can be dragged around on the screen. Floating mode is like tmux's popup windows.

When a terminal window is split horizontally while in **tiling mode**, the tmux popup window is resized correctly but the status bar disappears. When I change the terminal window width the popup is automatically adjusted but the status bar won't appear until the terminal window's width is changed to its original size.

When a terminal window is placed in **floating mode** and its size is changed, the tmux popup window is never resized (see screenshot and logs below).

I have tested this with three different terminals: [xfce4-terminal](https://github.com/xfce-mirror/xfce4-terminal), [alacritty](https://github.com/alacritty/alacritty), [st](https://st.suckless.org) -- always with the same result. I don't know if this has something to do with my tiling window manager.

### Screenshot

![screenshot-2021-09-17_001612](https://user-images.githubusercontent.com/6266600/133692963-77eeca46-07f2-4f87-b2ee-70bbf71a0fbe.png)

### Required information

* tmux version: `next-3.4`
* Platform: Gentoo Linux, [i3](https://github.com/i3/i3) tiling window manager, `xfce4-terminal`
* $TERM: inside `tmux-256color` and outside of tmux `xterm-256color`
* Logs:
  - [tmux-client-6361.log](https://github.com/tmux/tmux/files/7189860/tmux-client-6361.log)
  - [tmux-out-6363.log](https://github.com/tmux/tmux/files/7189861/tmux-out-6363.log)
  - [tmux-server-6363.log](https://github.com/tmux/tmux/files/7189862/tmux-server-6363.log)

**Comment by nicm** [comment]
It is hard to see what you are doing from this log, can you do something like this:
~~~~
tmux -f/dev/null -vvLtest new
tmux popup -E -x0 -yS -w100%
~~~~
Then resize *only once* to show the problem. If possible please type `aaa` before you resize and `bbb` afterwards so I can find it in the log. Then kill tmux (`tmux -Ltest kill-server`) and show me the server and client logs.

**Comment by bfrg** [comment]
[tmux-client-31033.log](https://github.com/tmux/tmux/files/7201813/tmux-client-31033.log)
[tmux-out-31035.log](https://github.com/tmux/tmux/files/7201814/tmux-out-31035.log)
[tmux-server-31035.log](https://github.com/tmux/tmux/files/7201815/tmux-server-31035.log)

**Comment by nicm** [comment]
Hmm tmux is definitely resizing the popup.

What does the window look like before and after you do the same as you did in this log? Does the status line disappear?

If you do something like `ls` in the popup, is it correctly bound to the popup or does it overwrite other panes?

**Comment by bfrg** [comment]
The popup window looked similar to the one in the above screenshot (except that I only increased the width). The status line did **not** disappear. 

The output of `ls` will not overwrite other panes. Everything stays in the popup.

**Comment by nicm** [comment]
OK so what is wrong in this log? What are you expecting the popup to be resized to?

**Comment by bfrg** [comment]
I can't say what is wrong in the logs because I don't understand them. I assumed the popup window are always resized when the underlying terminal window is resized. This is clearly not happening here. This is what the popup looks like before and after I go into full screen:
#### Before resizing
![screenshot-2021-09-21_111853](https://user-images.githubusercontent.com/6266600/134145669-71078aa3-f6d8-4348-aebf-c8fac3c2245f.png)

#### In fullscreen mode
![screenshot-2021-09-21_111903](https://user-images.githubusercontent.com/6266600/134145670-60172a19-91f4-4a7c-8cdc-799cb9e02f0c.png)

[tmux-client-3925.log](https://github.com/tmux/tmux/files/7202000/tmux-client-3925.log)
[tmux-out-3927.log](https://github.com/tmux/tmux/files/7202001/tmux-out-3927.log)
[tmux-server-3927.log](https://github.com/tmux/tmux/files/7202002/tmux-server-3927.log)

**Comment by nicm** [comment]
No, popups will only be resized if there is not enough room for them. They will only ever be made bigger if they have been made smaller by a previous resize.

**Comment by bfrg** [comment]
The following screenshots show when the status line disappears:

#### Before (terminal window is maximized)
![screenshot-2021-09-21_112410](https://user-images.githubusercontent.com/6266600/134146789-8d20d182-dfba-498c-95ba-7178a9dda4c1.png)

#### After opening a second window
![screenshot-2021-09-21_112419](https://user-images.githubusercontent.com/6266600/134146793-e19a5ac8-c010-4bd7-9e9c-8bf0bb63eb69.png)

[tmux-client-4324.log](https://github.com/tmux/tmux/files/7202036/tmux-client-4324.log)
[tmux-out-4326.log](https://github.com/tmux/tmux/files/7202037/tmux-out-4326.log)
[tmux-server-4326.log](https://github.com/tmux/tmux/files/7202038/tmux-server-4326.log)

**Comment by bfrg** [comment]
> No, popups will only be resized if there is not enough room for them. They will only ever be made bigger if they have been made smaller by a previous resize.

Okay. I thought when specifying its size in percent, like `-w 100%`, the popup would always keep that percentage of the window.

**Comment by nicm** [comment]
No it means 100% at the time it is opened.
