### ISSUE TITLE
Resizing panes in linux virtual console is not possible

### ISSUE THREAD

**Issue by riesebie** [tmux/tmux#29]
On Linux vt's (TERM=screen) it is not possible to resize panes via C-Up, C-Down, C-Left, C-Right nor M-Up, M-Down, M-Left, M-Right. 

-- 
   Elimar

**Comment by ntnn** [comment]
Should work fine. Did you start tmux with and empty file (`tmux -f $emptyfile`) to try, which OS are you using and which terminals did you try? Also, which version of tmux are you using?

**Comment by ThomasAdam** [comment]
Alt won't work since it's not part of VT100.  Rebind the actions you need to not use that key.

**Comment by nicm** [comment]
Did you try with TERM=linux outside tmux?

**Comment by riesebie** [comment]
* Nicholas Marriott <notifications@github.com> [2015-06-17 00:47 -0700]:

> Did you try with TERM=linux outside tmux?

What do you want me to try outside tmux?

On the console (TERM=linux)

<ctrl> <left>/<right> does nothing
<alt> <left>/<right> scrolls through the vt's.

**Comment by nicm** [comment]
Make sure TERM=linux and run tmux and see if your problem is still there.

If so then please try to run "cat" outside tmux and press C-Up, what do you see?

**Comment by riesebie** [comment]
* Nicholas Marriott <notifications@github.com> [2015-06-17 10:29 -0700]:

> Make sure TERM=linux and run tmux and see if your problem is still there.
> 
> If so then please try to run "cat" outside tmux and press C-Up, what do you see?

^[[A

**Comment by nicm** [comment]
That is no different from plain Up without Ctrl so you will not be able to use Ctrl+Arrows in this terminal.

-------- Original message --------
