### ISSUE TITLE
run-shell does not substitute client_* variables

### ISSUE THREAD

**Issue by marek-j-wrobel** [tmux/tmux#290]
Issue the following commands inside tmux:

`:display-message "#{session_name}"`
(session name is displayed)

`:display-message "#{client_tty}"`
(tty name is displayed)

`:run-shell "echo #{session_name}"`
(session name is echoed)

`:run-shell "echo #{client_tty}"`
(empty string is echoed, should be tty name)

This can be fixed by passing `cmdq->client` as the second argument of `format_defaults()` in `cmd_run_shell_exec()`.

**Comment by nicm** [comment]
try this please:

~~~~
Index: cmd-run-shell.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-run-shell.c,v
retrieving revision 1.35
diff -u -p -r1.35 cmd-run-shell.c
--- cmd-run-shell.c     14 Dec 2015 00:31:54 -0000      1.35
+++ cmd-run-shell.c     5 Feb 2016 10:10:12 -0000
@@ -93,7 +93,7 @@ cmd_run_shell_exec(struct cmd *self, str
        else
                cwd = NULL;
        ft = format_create(cmdq, 0);
-       format_defaults(ft, NULL, s, wl, wp);
+       format_defaults(ft, cmdq->state.c, s, wl, wp);
        shellcmd = format_expand(ft, args->argv[0]);
        format_free(ft);

**Comment by nicm** [comment]
Actually don't bother, this is wrong I think.

**Comment by nicm** [comment]
No actually it is right, please try that.

**Comment by marek-j-wrobel** [comment]
It works.

**Comment by nicm** [comment]
Applied now, thanks.
