### ISSUE TITLE
 `pane-focus-in` can't be fired in popup pane

### ISSUE THREAD

**Issue by kevinhwang91** [tmux/tmux#2903]
### Issue description
Reproduce steps
1. `tmux set -s focus-events on`
2. `tmux set-hook -g pane-focus-in 'display -F "#D"'`
3. `tmux popup -E nvim +'au FocusGained * echo "hello"'`

In the normal pane, tmux prompt will show the id, and nvim in the target pane will say `hello` (by `tmux neww`), but in the popup pane, nothing will happen.

### Required information

Please provide the following information:

* tmux version: tmux next-3.4
* Platform: ArchLinux
* $TERM inside and outside of tmux (`echo $TERM`): alacritty/tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Popups are not panes and do not fire focus hooks.

**Comment by kevinhwang91** [comment]
> Popups are not panes and do not fire focus hooks.

There may be glitches for my tmux script and neovim that depend on  `pane-focus-in` in popup. Is there another hook like `pane-focus-in` in popup ?

**Comment by nicm** [comment]
No there is no equivalent for popups.

**Comment by kevinhwang91** [comment]
Thanks for the explanation. Can my script detect whether in popup to avoid some glitches?

**Comment by nicm** [comment]
Hmm. You can check if `tty` is in `tmux lsp -aF '#{pane_tty}'`?

**Comment by nicm** [comment]
Or `TMUX_PANE` shouldn't be set.

**Comment by kevinhwang91** [comment]
Thanks
