### ISSUE TITLE
Question: how to bind [C-x o] and do not hide any other key sequences started with C-x

### ISSUE THREAD

**Issue by idanko** [tmux/tmux#2904]
Good day, it's more question rather than issue. I'm an Emacs user and I wish to enhance user experience a bit by adding custom behavior when `C-x o` is pressed.
Let's say I need to run `split-window` on the key sequence described above. So I came up with something like:
```sh
bind-key -Tmy-keys o split-window
bind-key -Troot C-x switch-client -Tmy-keys
```
While it satisfies the requirements, the issue is, I'm no longer able to run another Emacs command which starts with C-x sequence (eg, `C-x 5 0` is no longer available).
Is there any way to do not hide any sub key sequence start with C-x prefix except those defined explicitly in a configuration?

**Comment by mohkale** [comment]
>  the issue is, I'm no longer able to run another Emacs command which starts with C-x sequence

You're binding your custom keymap into the root keymap `bind-key -Troot C-x switch-client -Tmy-keys` which means its available without hitting your `prefix-key`.

You should do `bind-key C-x switch-client -Tmy-keys` and then hit `prefix C-x o`.

If the goal was to hit `C-x o` in tmux but also support `C-x 0 5` in emacs at the same time then I don't believe that's supported. That would mean tmux monitors input sequences and when you hit a key sequence that isn't bound it sends that sequence through to the current pane, which is likely to be confusing.

**Comment by nicm** [comment]
There is an `Any` key you can bind but I do not think we have a way to forward whatever that key is to the pane, I'll check next week, it may not be hard to add.

**Comment by idanko** [comment]
Thank you for the answers. This forward any keystrokes but those in user defined keymap feature would leverage Emacs terminal experience drastically.

**Comment by nicm** [comment]
Try this please against master: [x.diff.txt](https://github.com/tmux/tmux/files/7234358/x.diff.txt)

Then you can do this:
~~~~
bind -Tmy-keys o split-window
bind -Tmy-keys Any { send C-x; send }
bind -Troot C-x switch-client -Tmy-keys

**Comment by idanko** [comment]
@nicm wow, now It's possible to do similar to [vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator) by using the [C-x o] keybinding to walk through both tmux and emacs splits:
tmux.conf:

```sh
is_emacs='echo "#{pane_current_command}" | grep -iqE "emacs"'
bind -Temacs-keys o if-shell "$is_emacs" "send C-x; send" "select-pane -t :.+"
bind -Temacs-keys Any { send C-x; send }
bind -Troot C-x switch-client -Temacs-keys
```

init.el:
```lisp
(defun id/tmux-window-next ()
  "Switch to the next window if opened, otherwise select next tmux pane."
  (interactive)
  (if (eq (next-window) (get-buffer-window))
      (call-process "tmux" nil nil nil "select-pane" "-t" ":.+")
    (other-window 1)))

(global-set-key [remap other-window] #'id/tmux-window-next)
```

**Comment by nicm** [comment]
`if -F '#{m/ri:emacs,#{pane_current_command}}' ...` would be faster than using grep.

**Comment by idanko** [comment]
good to know

**Comment by nicm** [comment]
I will commit this at some point, it is too close to OpenBSD release right now. Thanks!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
