### ISSUE TITLE
vi-mode search and pressing escape repeatedly crashes tmux

### ISSUE THREAD

**Issue by jmatsushita** [tmux/tmux#2905]
### Issue description

Setting `set-window-option -g mode-keys vi` (via conf or interactively), then `ctrl-b [` followed by `/` or `?` and repeated `esc` presses leads to:
```
[tmux server exited unexpectedly]
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `tmux 3.2a`
* Platform (`uname -sp`). `Linux unknown` (`nixos 21.05`)
* $TERM inside and outside of tmux (`echo $TERM`). Inside `screen`, outside `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
```
[tmux server exited unexpectedly]
```

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by jmatsushita** [comment]
I'm afraid it does. Just built master and same problem.

**Comment by nicm** [comment]
I can't reproduce, show logs from master please, also a backtrace if there is a core, see https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md#how-do-i-get-logs-from-tmux and https://github.com/tmux/tmux/wiki/FAQ#tmux-exited-with-server-exited-unexpectedly-or-lost-server-what-does-this-mean

**Comment by jmatsushita** [comment]
There you go!

[tmux-client-6249.log](https://github.com/tmux/tmux/files/7271287/tmux-client-6249.log)
[tmux-out-6251.log](https://github.com/tmux/tmux/files/7271288/tmux-out-6251.log)
[tmux-server-6251.log](https://github.com/tmux/tmux/files/7271289/tmux-server-6251.log)

```
Core was generated by `tmux -vv -Ltest -f/dev/null new'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc84bf8dace in __memmove_avx_unaligned_erms () from /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6
(gdb) bt full
#0  0x00007fc84bf8dace in __memmove_avx_unaligned_erms () from /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6
No symbol table info available.
#1  0x0000000000464a48 in status_prompt_key ()
No symbol table info available.
#2  0x000000000045abff in server_client_handle_key ()
No symbol table info available.
#3  0x0000000000468619 in tty_keys_next ()
No symbol table info available.
#4  0x000000000046a160 in tty_read_callback ()
No symbol table info available.
#5  0x00007fc84c16cc38 in event_process_active_single_queue ()
   from /nix/store/lzhfnmhiimkfjcqbabdb5931ixa6m6ng-libevent-2.1.12/lib/libevent_core-2.1.so.7
No symbol table info available.
#6  0x00007fc84c16d2f7 in event_base_loop () from /nix/store/lzhfnmhiimkfjcqbabdb5931ixa6m6ng-libevent-2.1.12/lib/libevent_core-2.1.so.7
No symbol table info available.
#7  0x000000000044ed5f in proc_loop ()
No symbol table info available.
#8  0x000000000045dc37 in server_start ()
No symbol table info available.
#9  0x000000000040a693 in client_main ()
No symbol table info available.
#10 0x0000000000406320 in main ()
No symbol table info available.
```

**Comment by nicm** [comment]
This log is from 3.2a not from master.
