### ISSUE TITLE
default status-right of "localhost" in Android -- maybe $(getprop ro.product.model) would be better?

### ISSUE THREAD

**Issue by cnst** [tmux/tmux#2906]
I'm using tmux within one Android device to connect to tmux on another Android device, and I've noticed that both of them display `"localhost"` in the status bar next to the clock:
```
[0] 0:zsh*Z 1:zsh-                                   "localhost" 23:22 26-Sep-21
```

Tracking down `tmux show-options -g status-right`, it's confusingly revealed to be originating not directly from the hostname, but from `pane_title`, which, in turn, defaults to the hostname, but could be re-set with `tmux select-pane -T "title"`, i.e., `tmux select-pane -T "$(getprop ro.product.model)"` in zsh in tmux within Termux on Android:
```
[0] 0:zsh*Z 1:zsh-                                  "Pixel 2 XL" 23:21 26-Sep-21
```

Given that it may not be possible to modify the hostname on Android away from `localhost`, what would be the best way to replace `hostname` with `getprop ro.product.model` in tmux on Android to avoid `pane_title` of `localhost` on each Android device in each pane?

**Comment by nicm** [comment]
We could do this, but to do it in code would mean:

1) replacing hostname entire on Android via `AC_LIBOBJ` so both the initial pane title and the `host` and `host_short` format are changed;

2) or adding an `osdep_default_pane_title` or something to each osdep-*.c file with `hostname` and a new osdep-android.c (or an `#ifdef` in the osdep-linux.c one might do if it is using that at the moment).

Alternatively you could put something like in your shell profile:
~~~~
[ -n "$TMUX" ] && tmux selectp -T "$(getprop ro.product.model)"
~~~~
Or:
~~~~
printf '\033]2;$(getprop ro.product.model)\033\\'
~~~~
Or you could just change `status-right` in .tmux.conf:
~~~~
set -g status-right '#(getprop ro.product.model)'

**Comment by cnst** [comment]
Thank you!  I'll be adding this to my `~/.zshrc` for the short-term:

`[ -n "$TMUX" ] && [ "$(tmux display -p '#{pane_title}')" = "localhost" ] && tmux selectp -T "$(getprop ro.product.model)"`

Might look more into [`osdep-linux.c`](https://github.com/tmux/tmux/blob/master/osdep-linux.c) (and/or adding `osdep-android.c`) later on.  BTW, why does it have `$OpenBSD$` if the file is missing from OpenBSD? :)  Evidently, even [`osdep-openbsd.c`](https://github.com/tmux/tmux/blob/master/osdep-openbsd.c) is missing from OpenBSD, too.

**Comment by nicm** [comment]
osdep-openbsd.c is in OpenBSD but it is called procname.c, the others I
probably just copied the header from another file :-).
