### ISSUE TITLE
Can command-prompt take in prompts as separate commands or possible to simulate it? [question]

### ISSUE THREAD

**Issue by boulderob** [tmux/tmux#2907]
### Question

This is purely a question.  I couldn't find the answer anywhere online and I'm not sure it can be done.  I know that `command-prompt` can take multiple prompts that run in sequence which allows you to plug multiple "placeholder" vars in the final command like this:

```
command-prompt -p 'man page name:','search term:' "splitw -f man '%%'; send-keys / %2 Enter"
```

But I'd like to use the `choose-tree` command twice in a row like we use prompts.  This way I can save the first pane picked in the first run of `choose-tree` as `%1` and then a second pane picked immediately after it in the second `choose-tree` invocation as `%2`, then plug it into a final third command template as

```
 join-pane -s %1 -t %2
```

I hope that's clear.  I can do what I want outside of tmux in the shell by saving the output of two consecutive fzf commands as input to the final `join-pane` command.  But I'm trying to find a *native* way from within tmux to do the same thing using it's already builtin pickers (choose-tree or similar) and the fact that they can *already* natively return the placeholder vars to more easily plug directly into the third `join-pane` command.

If there is some other way to do this within tmux without `command-prompt` that's fine too.  I'm just looking for a native way to do it.

Thanks

### Required information

```
 tmux -V
tmux 3.1c

 uname -a
Darwin mbpmes-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

echo $TERM
screen-256color
```

**Comment by nicm** [comment]
You could use choose-tree twice, something like:
~~~~
tmux set -u @one
tmux choose-tree 'set @one "%%%"'
one='$(tmux display -p '#{@one}')"
[ -n "$one" ] || exit
... same for @two/$two ...
tmux joinp -s$one -t$two

**Comment by boulderob** [comment]
Thanks @ncim.  I wasn't aware of the use of `set` like that in tmux.  Your solution might be close to what I'm looking for but it is 100% back in and requires the shell to pass the return values of the two invocations of `choose-tree` which mimics exactly what I can already do with fzf.   

Since most of your solution is indeed native tmux subcommands, is there a way to transform it to a *one-liner* with `;` as separators between the subcommands that could be used as the right-hand side of a key bind to trigger it in `tmux.conf`?  I believe tmux has it's own native `if` conditional construct that might be able to replace the shell check of `$one` and `$two` but I'm not sure it can be chained like this natively.

As an aside and just to be clear.  I'm not 100% certain but I think that `command-prompt` is sort of "basic" in the sense that it can only prompt you to *manually* type in a value.  What I'm trying to clarify is if there is a way to *config the prompts to be actual "smart pickers" or commands like (`choose-tree`) themselves*.  Since both `choose-tree` and `command-prompt` are both already native within tmux, the "plumbing" is already there to do it.  But I don't think `command-prompt` is natively wired like this yet to connect the two.  Is that correct?  

Thanks

**Comment by nicm** [comment]
No, you need to use choose-tree.

**Comment by nicm** [comment]
You can use -Ttarget or -Twindow-target to change how tab completion works but if you want choose-tree you will need to write a shell script.
