### ISSUE TITLE
new-session causes SEGFAULT since 5caec30

### ISSUE THREAD

**Issue by mgraczyk** [tmux/tmux#291]
Running new-session with an invalid target session causes the tmux server to segfault. This error was introduced in commit `5caec30`. This bug is extremely annoying because all sessions are lost when the server crashes.

**Steps To Reproduce:**
- Checkout tmux at current HEAD and make sure server is not running.

 ```
cd tmux
git checkout 404379049a4cb5480c2b1c19634c869e46feb220
git clean -xdf
./autoconf.sh && ./configure && make -j
pkill tmux
```

- Create a named detached session.

```
./tmux new-session -d -s name
```
-  Check that tmux server is running

```
ps -A | grep tmux
```
- Try to create a new session grouped with a non-existent session

```
./tmux new-session -s new_name -t nonexistent_name
```

**Expected Results:**
The tmux client started in step 4 should output "no current session" and exit.

**Actual Results:**
The tmux server crashes with a segfault at `session.c:578` because target is NULL.
The tmux client outputs "lost server".

**Analysis**
From bisecting, it looks like the problem was introduced in commit `5caec30`. The problem appears to be this change:

```
-               if (cmd_find_session(cmdq, args_get(args, 't'), 0) == NULL)
-                       return (CMD_RETURN_ERROR);
+               /*
+                * cmd_prepare() will fail if the session cannot be found,
+                * hence always return success here.
+                */
```

In fact, cmd_prepare_state_flag does not fail when the session is not found.
I am not familiar enough with the code to know for sure that this is the cause or what the solution should be. Please take it with some skepticism. 

My bisect script is attached.
[bisect.sh.txt](https://github.com/tmux/tmux/files/110650/bisect.sh.txt)

I am particularly concerned with this bug and others like it because it caused me to lose my tmux server state. That is the emotional equivalent of dropping a stack of papers with no page numbers down a flight of stairs.

**Comment by jungle-boogie** [comment]
Hi,

I can't reproduce this and I'm on head. 

`% tmux new-session -s new_name -t nonexistent_name`
`can't find session nonexistent_name`

**Comment by mgraczyk** [comment]
@jungle-boogie Are you sure you followed the steps completely? I just reproduced on a fresh Ubuntu 15.10 VM using exactly the above steps.

**Comment by nicm** [comment]
Try this please [x.diff.txt](https://github.com/tmux/tmux/files/110723/x.diff.txt)

**Comment by mgraczyk** [comment]
@nicm With your patch, the crash does not occur.

**Comment by jungle-boogie** [comment]
Hi @mgraczyk,

You are right. I don't know what mistake I made last time. Thanks for your help in finding the problem.

I confirm the patch will display the expected results.

**Comment by nicm** [comment]
Applied thanks.
