### ISSUE TITLE
Port ncurses dependency to notcurses instead

### ISSUE THREAD

**Issue by WSLUser** [tmux/tmux#2916]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). Any
* Platform (`uname -sp`). All
* $TERM inside and outside of tmux (`echo $TERM`). Any terminal
* Logs from tmux (`tmux kill-server; tmux -vv new`). N/A

Per https://github.com/tmux/tmux/issues/2575#issuecomment-784844240

Biggest problem in supporting Windows has been ncurses dependency. However there are any number of reasons to switch from ncurses to notcurses. But the most important is the support it has for Windows in addition to Linux and BSD/Mac. Another would be the enormous performance  boost you'll gain from using notcurses.  

See https://github.com/dankamongmen/notcurses to learn more about what notcurses can do for you.

**Comment by nicm** [comment]
Biggest problem in supporting Windows is not ncurses, it is file descriptor passing.

**Comment by WSLUser** [comment]
Perhaps not, but there are still many other benefits to using notcurses. It removes at least one hurdle though. It produces an Msys2 binary so it's possible that the fd passing may be handled by the msys2 binary. Would need to look  deeper into that. 

Despite this: Just from a pure LInux perspective,  there are many advantages that ncurses doesn't have and wasn't intended for. I imagine that if it was adopted, it would be very noticeable to users in a good way.

**Comment by WSLUser** [comment]
https://stackoverflow.com/questions/48685185/ftruncate-is-not-working-properly-with-msys2 and related links contained within seem to imply msys2 does support file descriptors and simply does the conversions to the windows equivalent. I guess you'd need to try to give it a spin, even with ncurses, you could test this out. But notcurses would still be better to use as a terminal library.

**Comment by nicm** [comment]
What benefits are there to tmux?

**Comment by nicm** [comment]
tmux uses ncurses for access to terminfo, notncurses also uses ncurses for access to terminfo so there doesn't seem to be any benefit there.

If this had existed when tmux had started it might have been a reasonable base to start with, because unlike ncurses it appears to allow multiple terminal file descriptors to be used at the same time, but it would need a lot of work to replace tmux's output path at the moment and I don't see any practical benefit.

**Comment by WSLUser** [comment]
Performance, better graphic protocol support (you have none) and unicode support among the top 3 benefits that spring to mind for me.

**Comment by ThomasDickey** [comment]
hmm _"unlike ncurses it appears to allow multiple terminal file descriptors to be used at the same time,"_ doesn't gibe with [`setupterm`](https://invisible-island.net/ncurses/man/curs_terminfo.3x.html#h3-Initialization):

> The **`setupterm`** routine stores its information about the  terminal  in  a
**`TERMINAL`**  structure  pointed to by the global variable **`cur_term`**.  If it
detects an error, or decides that the terminal is unsuitable  (hardcopy
or  generic),  it discards this information, making it not available to
applications.

One description per **`SCREEN`**, of course.  Merging would be done by `tic`.

**Comment by nicm** [comment]
Hah I didn't know it did that. Well anyway we are not changing to use
either ncurses for drawing or anything else.

**Comment by nicm** [comment]
I don't think you know how tmux works.

**Comment by nicm** [comment]
I suspect that even if I had released 10-odd years ago that ncurses could do this, I would have moved away from it at some point, I think there are advantages for a program like tmux doing its own terminal management. It is done now in any case :-).

**Comment by nicm** [comment]
You can try, but I don't think it is a good idea, you will struggle to do all that tmux does with notncurses at its current point and it very likely it will be slower.
