### ISSUE TITLE
How to fix vim colors on mac terminal

### ISSUE THREAD

**Issue by GenaANTG** [tmux/tmux#2919]
### Issue description

First of all i want respect you for this config. <3
And question is: **How to fix background highlight in normal vim mode?**
Outside of tmux i have no those highlights.

<img width="722" alt="Screenshot 2021-10-08 at 15 15 31" src="https://user-images.githubusercontent.com/12715550/136557296-43b99e6d-26d6-459e-9e61-313db250d9fd.png">

### Required information

Please provide the following information:

* tmux version: tmux 3.2a
* Platform: Darwin i386
* $TERM inside and outside of tmux: outside -> xterm-256color; inside -> screen-256color

**Comment by nicm** [comment]
Could be it wants them to be italics. You could try using `tmux-256color` instead of `screen-256color`.

**Comment by nicm** [comment]
You will need to change `default-terminal`.
