### ISSUE TITLE
24 bit color mode not works well with select

### ISSUE THREAD

**Issue by lvht** [tmux/tmux#292]
use this script to generate colorful output
```shell
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```

and then make tmux select any part of the colorful output, the select area will be totally black.

<img width="842" alt="2016-01-31 10 43 40" src="https://cloud.githubusercontent.com/assets/2030591/12699865/99307bf4-c807-11e5-870b-d5b6385c1d3d.png">

under both mac(iTerm2 Build 2.9.20160129-nightly) and linux(st)

https://github.com/neovim/neovim/issues/4133

my tmux is built from 404379049a4cb5480c2b1c19634c869e46feb220

and the conf I used
```
set -ga terminal-overrides ",*:Tc"
```

**Comment by nicm** [comment]
Try this please [x.diff.txt](https://github.com/tmux/tmux/files/111196/x.diff.txt)

**Comment by lvht** [comment]
@nicm It does not work, actually.

**Comment by nicm** [comment]
Then I am going to need a proper bug report, a screenshot is not enough.

**Comment by lvht** [comment]
@nicm I pasted the script to generate the colorful output.

**Comment by ThomasAdam** [comment]
No.   You need to tell us *what* the problem us, what terminal you're
using.  What config changes you may have made, etc.

We need detail, not vagueness with ESP thrown in at our end.

**Comment by lvht** [comment]
@ThomasAdam sorry for trouble. More detail has been added. Thanks.

**Comment by nicm** [comment]
I think this is it:
~~~~
Index: screen-write.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/screen-write.c,v
retrieving revision 1.84
diff -u -p -r1.84 screen-write.c
--- screen-write.c      19 Jan 2016 15:59:12 -0000      1.84
+++ screen-write.c      31 Jan 2016 10:09:20 -0000
@@ -994,7 +994,9 @@ screen_write_cell(struct screen_write_ct
                utf8_copy(&tmp_gc.data, &gc->data);
                tmp_gc.attr = tmp_gc.attr & ~GRID_ATTR_CHARSET;
                tmp_gc.attr |= gc->attr & GRID_ATTR_CHARSET;
-               tmp_gc.flags = gc->flags & ~(GRID_FLAG_FG256|GRID_FLAG_BG256);
+               tmp_gc.flags = gc->flags;
+               tmp_gc.flags &= ~(GRID_FLAG_FGRGB|GRID_FLAG_BGRGB);
+               tmp_gc.flags &= ~(GRID_FLAG_FG256|GRID_FLAG_BG256);
                tmp_gc.flags |= s->sel.cell.flags &
                    (GRID_FLAG_FG256|GRID_FLAG_BG256);
                ttyctx.cell = &tmp_gc;

**Comment by lvht** [comment]
@nicm :+1:

**Comment by nicm** [comment]
Applied now, thanks

**Comment by lvht** [comment]
Do you @nicm  create a PR?
