### ISSUE TITLE
popup: mouse copy to clipboard instead of buffer

### ISSUE THREAD

**Issue by silicali** [tmux/tmux#2921]
I use MAC-OS(kitty terminal) ---ssh-to-linux---->tmux session-------right-click-status-menu--->open below command

 "Settings "        e   "run -C {popup -xC -yC -w'90%' -h'90%' -E -E  \"tmux new -n settings 'nvim ~/.config/tmux/tmux.conf'\"}" \

above option is from display-menu (bind to  MouseDown3Status) with list of commands

everything works as expected only difference whenever I use mouse selection(MouseDrag/Double Click/Tripple Click) in side nvim(selection is highlighted) but copies to buffer instead of clipboard.

It doesn't look like bug at all. either missing an option or it is not supported when using popup

Is there any option to copy to clipboard directly?

**Comment by silicali** [comment]
tmux version (tmux -V). -> built from Oct 8 master@latest 7ca863c5af3dbbb78d45bec5b113a69f983f2fdc
❯ tmux -V
tmux next-3.4
Platform (uname -sp).
❯ uname -sp
Linux x86_64
$TERM inside and outside of tmux (echo $TERM).
in tmux:
❯ echo $TERM
xterm-kitty
outside tmux:
❯ echo $TERM
xterm-kitty
Logs from tmux (tmux kill-server; tmux -vv new).
let me know, i'll provide restarting tmux.

"Settings " e "run -C {popup -xC -yC -w'90%' -h'90%' -E -E "tmux new -n settings 'nvim ~/.config/tmux/tmux.conf'"}" \

is the above command options are correct ? 

right now the clipboard is working across tmux pane/windows, and inside tmux + vim also. but when I open tmux.conf using popup it copies to buffer than clipboard.

**Comment by nicm** [comment]
OSC 52 is not supported in popups, but there is no reason it couldn't work, I'll take a look at some point.

**Comment by silicali** [comment]
ok. thanks
I've two options use pop-up and copy using "kitty-terminal"'s rectangle copy to clipboard
or use tmux new-winodw instead of popup window.
