### ISSUE TITLE
Update Contributing wiki page

### ISSUE THREAD

**Issue by afh** [tmux/tmux#2923]
* The request for _"[a] flag to select-window to create the window, or to new-window to select (#2766)"_ can be removed from the [**Contributing Small Things**](https://github.com/tmux/tmux/wiki/Contributing#small-things) wiki section as it has been added with be471c328.

* The reference to #2484 can be removed from the [**Contributing Medium Things**](https://github.com/tmux/tmux/wiki/Contributing#medium-things) wiki section as it has been [done](https://github.com/tmux/tmux/issues/2484#issuecomment-898599573) f0e02387b2e13ba2a924b4a6c47da38b22bd8d3e.

* I believe the request for the display-popup `-c` to set the working directory can be removed from the [**Contributing Medium Things**](https://github.com/tmux/tmux/wiki/Contributing#medium-things) wiki page as tmux offers the `-d` flag to set the start directory.

* If #2924 is accepted, then the reuest for the -e flag to set environment for popup can be removed from the [**Contributing Medium Things**](https://github.com/tmux/tmux/wiki/Contributing#medium-things) wiki page.

* If #2927 is accepted, then the reference to #2776 can be removed from the "Popup improvements" on the [**Contributing Medium things**](https://github.com/tmux/tmux/wiki/Contributing#medium-things) wiki page.

**Comment by nicm** [comment]
I can't find some of these (maybe I removed them and forgot `git push`...) but I have removed the others. Thanks!
