### ISSUE TITLE
Bash prompt not wrapping correctly in tmux

### ISSUE THREAD

**Issue by alexanderajju** [tmux/tmux#2926]
without Tmux
![image](https://user-images.githubusercontent.com/64595534/136693057-05ba9fd1-56a8-4807-9073-8ec3d7fb771e.png)

with Tmux
![image](https://user-images.githubusercontent.com/64595534/136693089-e55f4a19-207a-49ec-84a9-ba2a65c7d728.png)

**Comment by krader1961** [comment]
You left out all the information that is asked for when opening a new issue. We have no magic ability to read your mind. What version of tmux are you using? What is the value of TERM inside and outside tmux? What terminal emulator are you using? Etcetera.

**Comment by alexanderajju** [comment]
> You left out all the information that is asked for when opening a new issue. We have no magic ability to read your mind. What version of tmux are you using? What is the value of TERM inside and outside tmux? What terminal emulator are you using? Etcetera.
version:-tmux 3.1c
TERM outside: xterm-256color
TERM inside tmux: screen
terminator
Parrot OS

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-utf-8
