### ISSUE TITLE
[Feature request] Underline color support in `capture-pane -e`

### ISSUE THREAD

**Issue by gnachman** [tmux/tmux#2928]
### Issue description

iTerm2 has gained support for underline color. `capture-pane -e` does not emit this control sequence, which causes underline colors to be lost when attaching in control mode.

### Required information

Please provide the following information:

* tmux version - I'm at commit aff2a473ec3c16396d6be9d61c5e5dc1201a725b, the current head of master on github.
* Platform - Darwin i386
* $TERM - xterm-256color, screen

I think `grid_string_cells_code()` needs to be changed. It has special handling for foreground and background color, and this is a novel third color dimension.

**Comment by nicm** [comment]
This should be supported now (when GitHub syncs up), please let me know of any problems. Thanks!
