### ISSUE TITLE
Trim menu item's name if it exceeds screen width?

### ISSUE THREAD

**Issue by 097115** [tmux/tmux#2933]
### Issue description

If a menu item's name is longer than the screen's width, then the menu is not displayed. May be it would be great to trim menu items name in such a case? It seems that the limit should be the screen's width (like,`tput cols`) minus 8 characters.

(Sure, nobody actually uses such long names for their menu items :) But if a menu is auto-generated...)

### Required information

* tmux version: 264fe7f, reports as `tmux next-3.4`

**Comment by 097115** [comment]
@afh,

Thanks for your interest!

Yeah, it seems to be working. However, it trims the key, too -- like `(1)` in this example:
![](https://i.imgur.com/brFoiJu.png)

Also, as you mentioned, adding something like `...` at the end would be a nice little touch :)

Anyway, great work, and thanks again!

**Comment by afh** [comment]
Thanks for trying this out. I did not think of the keys, thanks for bringing this up!
Let me re-iterate on the change in the PR.

**Comment by afh** [comment]
@097115 I've updated #2936, so that the menu key will still be visible and truncated menu items show a `>` at the end.
