### ISSUE TITLE
Session names get modifed after creation

### ISSUE THREAD

**Issue by tami5** [tmux/tmux#2943]
### Issue description

Session names get modified after creation. Basically, a number is appended at the end of the session name. 

```
tmux new-session -t work # work-0
tmux new-session -t w # w-1
```

Is there a way to disable this annoying behavior 

Thanks

### Required information

Please provide the following information:

* tmux version (`tmux 3.2a`).
* Platform (`Darwin arm64`).
* $TERM inside and outside of tmux (`xterm-256color/xterm-256color`).

**Comment by nicm** [comment]
You can't have more than one session with the same name so when you create a grouped session the new session has to be named differently from the original. You should still be able to give your own name with `-s`.

**Comment by tami5** [comment]
Thanks a lot @nicm  `-s` what I missed
