### ISSUE TITLE
tmux crashes when I try to switch between sessions

### ISSUE THREAD

**Issue by lamp0chka** [tmux/tmux#295]
Hi,

tmux crashes when I try switch between sessions, if session was created via:
``
tmux new-session -A -s vitaly
``
I can easily reproduce via these steps:
1) No tmux running
2) tmux new-session -A -s vitaly
3) create new session via prefix + \:new
4) open new tab in iterm (crashes in terminal as well) 
5) in new tab tmux new-session -A -s vitaly
6) prefix + s (to switch session) kills tmux with [lost server]

What I'm trying to achieve is: new tab in iTerm is always starting tmux or joining to existing session. Btw, if I do exactly same steps, but instead of new-session issue:
```
tmux attach -t vitaly || tmux new -s vitaly
```
everything works flawlessly.

I'm running tmux 2.2 on OS X El Capitan 10.11.2 (15C50).

**Comment by nicm** [comment]
Try this please: [x.txt](https://github.com/tmux/tmux/files/117418/x.txt)

**Comment by lamp0chka** [comment]
yes, this did the trick, works as expected now.

**Comment by nicm** [comment]
Thanks
