### ISSUE TITLE
Menu is dismissed when terminal font size is changed

### ISSUE THREAD

**Issue by afh** [tmux/tmux#2953]
### Issue description

**Steps to reproduce:**

* Build and run tmux from master (as of this writing 3934d9b2): `./tmux -vv -f/dev/null -Ltest`
* Open a menu: `./tmux menu foo '' '' bar '' ''`
* Change the font size of the terminal (tested with Terminal.app and Alacritty) using `⌘ +`

**Expected behaviour:**
The terminal font size is increased and all displayed content in tmux, including the menu, remains visible

**Expected behaviour:**
The terminal font size is increased and the menu is dismissed

@nicm, not sure if this is an issue with the terminals I used or something within tmux.
Getting too late for me to look into deeper this now, so I tracking this here to get the conversation going.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux next-3.4 (compiled from 3934d9b2)
* Platform (`uname -sp`): Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`): inside: `tmux-256color` outside: `alacritty`, `xterm-256c`
* Logs from tmux (`tmux kill-server; tmux -vv new`):
  - [tmux-client-56613.log](https://github.com/tmux/tmux/files/7412997/tmux-client-56613.log)
  - [tmux-out-56615.log](https://github.com/tmux/tmux/files/7412998/tmux-out-56615.log)
  - [tmux-server-56615.log](https://github.com/tmux/tmux/files/7412999/tmux-server-56615.log)

**Comment by nicm** [comment]
I have added this to the todo list here https://github.com/tmux/tmux/wiki/Contributing, thanks!
