### ISSUE TITLE
about italic display

### ISSUE THREAD

**Issue by HaibaraMegumi** [tmux/tmux#2955]
the italic not display completed
![image](https://user-images.githubusercontent.com/60850531/138823233-2f8da664-adb3-4bd4-891b-d3e92b1a5eec.png)

the letterspacing of terminal named hyper is 5
![image](https://user-images.githubusercontent.com/60850531/138823472-742f92c3-4272-4742-a7c6-9c87de37a0ad.png)

tmux version
![image](https://user-images.githubusercontent.com/60850531/138823560-f5c36731-fb4d-4726-b999-e0065a646e20.png)

Platfor:
Linux x86_64

$TERM:
inside
![image](https://user-images.githubusercontent.com/60850531/138823721-41f5a98b-966a-4962-ba36-f711d6be528a.png)
outside:
![image](https://user-images.githubusercontent.com/60850531/138823813-c829f15e-65b2-485f-893c-740feb17520d.png)

Logs:
given command not dispaly anything

tmux.conf:

![image](https://user-images.githubusercontent.com/60850531/138824237-19bdc657-49ef-4065-ad51-f252a40f06b0.png)

**Comment by rod-stuchi** [comment]
Hi @HaibaraMegumi, Thank you so much for sharing this tips
I managed to get this working with this (also true colors)

**.tmux.conf**
![image](https://user-images.githubusercontent.com/19471811/139948317-db4c8ef1-e6ea-4024-95ad-9d7ffdcbe375.png)

**In pure Alacritty**
![image](https://user-images.githubusercontent.com/19471811/139948398-675a2e3d-9fe3-4660-87ca-d3e74203ea05.png)

**In Tmux 3.2a**
![image](https://user-images.githubusercontent.com/19471811/139948699-ada8507d-fa8f-417a-b710-1d14c7ea5ef9.png)
