### ISSUE TITLE
Feature: Way to attach to existing session in .tmux.conf

### ISSUE THREAD

**Issue by spease** [tmux/tmux#2963]
I'd like to set tmux as my default shell, however I'd also like to have it automatically attach to a session if one exists. It would seem like `new-session -A -s0` should do what I want, but putting this at the top of .tmux.conf does not cause it to attempt to attach to the specified session.

Currently my alternative is to launch tmux via shell startup script.

**Comment by nicm** [comment]
.tmux.conf is only read when tmux starts so by definition there cannot be
any existing sessions.

You could put your commands in a separate config and start tmux as "tmux
source /my/conf".

**Comment by spease** [comment]
Thanks. Unfortunately under macOS it doesn't appear to be possible to specify arguments when using the `chsh` command.

**Comment by nicm** [comment]
You will need to write a wrapper script and chsh to that.
