### ISSUE TITLE
printf '\ek\e\\' doesn't clear window title.

### ISSUE THREAD

**Issue by glitchub** [tmux/tmux#2964]
Recently upgraded to debian 11 which took tmux from 2.8 to to 3.1c, and discovered that  `printf '\ek\e\\'` no longer clears an existing window title. 

Looks like it came in with f18cd5b19. 
```
$ git diff f18cd5b19~ -- input.c | awk '/input_exit_rename/,/^ }/'
 input_exit_rename(struct input_ctx *ictx)
 {
+       struct window_pane      *wp = ictx->wp;
+       struct options_entry    *o;
+
+       if (wp == NULL)
+               return;
        if (ictx->flags & INPUT_DISCARD)
                return;
        if (!options_get_number(ictx->wp->options, "allow-rename"))
@@ -2287,9 +2392,17 @@ input_exit_rename(struct input_ctx *ictx)

        if (!utf8_isvalid(ictx->input_buf))
                return;
-       window_set_name(ictx->wp->window, ictx->input_buf);
-       options_set_number(ictx->wp->window->options, "automatic-rename", 0);
-       server_status_window(ictx->wp->window);
+
+       if (ictx->input_len == 0) {
+               o = options_get_only(wp->window->options, "automatic-rename");
+               if (o != NULL)
+                       options_remove_or_default(o, -1, NULL);
+               return;
+       }
+       window_set_name(wp->window, ictx->input_buf);
+       options_set_number(wp->window->options, "automatic-rename", 0);
+       server_redraw_window_borders(wp->window);
+       server_status_window(wp->window);
 }
```
Note windows_set_name() and friends are now skipped if input_len == 0. 

FWIW if unicode is enabled then a workaround is `printf '\ek\u80\e\\'`.

tmux -V = tmux 3.1c
uname -sp = Linux unknown 
TERM = tmux-256color over xterm-256color

**Comment by nicm** [comment]
Correct, it now turns `automatic-rename` back to default.

**Comment by glitchub** [comment]
Yes that's true, but since I have automatic-rename disabled the only effect is it now fails to call window_set_name() in the zero-length case.

**Comment by nicm** [comment]
I don't really see any use for setting an empty name though, what are you using it for?

**Comment by glitchub** [comment]
I have window-status-format set to #I:#W and my .bashrc contains:
```
if [[ $TMUX && $(ps -q$PPID -ocmd=) == tmux* ]]; then
    trap 'printf "\ek%s\e\\" ${BASH_COMMAND%% *}' DEBUG
    PS1+='\[\ek\e\\\]'
fi
```
I.E. if the current shell is a direct child of tmux then arrange to set the window title to the first token from the command line when entered, and clear it when showing the command prompt. 

So by default the status line is `1: 2: 3: ...`. If I run `some command` then it becomes `1: 2:some 3: ..` until the command exits.

Conceptually similar to automatic rename but shows the command I typed instead of what ran as a result, and works with aliases and shell functions.

**Comment by nicm** [comment]
I have changed this so that if `automatic-rename` is off, you can set the window name to empty with the escape sequence. It will be in GitHub later on when it syncs up.

You could also use `tmux renamew` instead of the escape sequence, since this will only work on the local machine anyway.
