### ISSUE TITLE
TMUX pop up menu

### ISSUE THREAD

**Issue by wojciechGaudnik** [tmux/tmux#2969]
Hi,
I have on kali that nice pop-up menu:
![image](https://user-images.githubusercontent.com/32289094/140652969-95068507-283d-46c4-abaa-17b56bd4acea.png)
tmux 3.2a
Kernel: x86_64 Linux 5.10.0-kali9-amd64
xterm-256color <--- inside and out side 

I wonder why on kali this works and on ubuntu doesn't 
tmux 3.1c
Kernel: x86_64 Linux 5.13.0-20-generic
xterm-256color <--- in and out

On kali, there isn't any .tmux.conf.
Is this a matter of version or is there some way to add something into .tmux.conf to run it on ubuntu?

**Comment by nicm** [comment]
The feature was added in 3.2.
