### ISSUE TITLE
Setting of PATH variable is unexpected

### ISSUE THREAD

**Issue by Elentirith** [tmux/tmux#2972]
Had some confusion because python3 was /usr/bin/python3 in terminal but /opt/homebrew/bin/python3 in tmux. I tracked it down to tmux producing an unexpected $PATH. This example is with Terminal.app on Big Sur. The relevant line in .zprofile is

```eval "$(/opt/homebrew/bin/brew shellenv)"```

and I have no .tmux.conf or .zshrc file. In regular terminal my $PATH is

```/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin```

and when entering tmux it is 

```/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/homebrew/bin:/opt/homebrew/sbin```

I'm not sure why but I was able to fix this by setting default-command to /bin/zsh in .tmux.conf. I could not find anything in the manual about this behavior.

Darwin arm
tmux 3.2a
$TERM is xterm-256color in Terminal.app and screen in tmux

**Comment by nicm** [comment]
Seems like your shell is setting PATH differently when it is a login shell and not.

**Comment by Elentirith** [comment]
I suppose but when I compare $PATH with the login shell it gives me vs typing zsh it's the same. Verified by checking ```echo $0``` in both. Plus tmux doesn't seem to take that into account since it spawns a login shell regardless of which one is active. Best resolution I can guess for now is to force tmux to not give me a login shell.

**Comment by kwsp** [comment]
I have the exact same issue. When I open tmux (regardless of which terminal emulator, which shell), a bunch of things are prepended to my PATH: `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:`. I cannot figure out where they are added. Have tried killing the tmux server, running without a config file etc.

**Comment by nicm** [comment]
For new panes created from a key binding, tmux just fills in PATH from the global environment, the rest is up to your shell. For new panes created with `tmux splitw`, it is copied from the environment of the running shell -  then the new shell in the pane may modify it.
