### ISSUE TITLE
Dolphin SIGINT signal doesn't work in tmux

### ISSUE THREAD

**Issue by iTrooz** [tmux/tmux#2973]
When using tmux as the default shell in Dolphin integrated terminal, the SIGINT signal used by Dolphin to reset command line before using cd isn't caught by bash
This can cause cd commands to be interpreted as arguments for an already-written command

Steps to reproduce :
- Change default shell for Dolphin (I do it through Konsole in my KDE installation)
- Open dolphin and an integrated shell ('F4' in my installation)
- Write a command like `rm -rf `
- Click on a directory in Dolphin GUI
- The folder has been deleted, because Dolphin integrated terminal executed `rm -rf cd /your/dir` 

![Screenshot](https://user-images.githubusercontent.com/42669835/141455421-347ec3fe-6980-4ba2-9010-a227f825528e.png)

Tmux version :  3.2a
Plateform : ArchLinux KDE, kernel 5.10 LTS
TERM : screen

Fix suggestion : make the tmux client forward the signal SIGINT (and maybe some others ?) signals to bash

**Comment by nicm** [comment]
This is a problem with the terminal or the shell, not with tmux.

**Comment by nicm** [comment]
Is it actually and bizarrely trying to send `INT` to tmux or is it sending the `C-d` key?

**Comment by iTrooz** [comment]
> Is it actually and bizarrely trying to send `INT` to tmux or is it sending the `C-d` key?

I monitored tmux with strace, and it is the tmux client that is receiving the SIGINT signal

**Comment by nicm** [comment]
This program should not be sending SIGINT to random programs running in the terminal. How does it know it is a shell? How does it know what SIGINT does?

**Comment by iTrooz** [comment]
> This is a problem with the terminal or the shell, not with tmux.


I don't think this is a problem with bash because it doesn't even receive anything, and I don't think Dolphin should be responsible for interacting with tmux to know which shell to send the signal to (maybe I'm wrong tho)

**Comment by nicm** [comment]
tmux has no responsibility to forward SIGINT or any signal sent to it anywhere.

**Comment by iTrooz** [comment]
> This program should not be sending SIGINT to random programs running in the terminal. How does it know it is a shell? How does it know what SIGINT does?

I believe Dolphin only does it when the parent process runs in the foreground, so it only do it with shell programs

**Comment by iTrooz** [comment]
> tmux has no responsibility to forward SIGINT or any signal sent to it anywhere.

Okay, do you think I should report this to Dolphin then ?

**Comment by nicm** [comment]
Yes you should probably report it to them.
