### ISSUE TITLE
tmux corrupts .Xmodmap settings

### ISSUE THREAD

**Issue by benibilme** [tmux/tmux#2974]
Hello,

I am using latest manjaro with  kernel  5.10.70-1 and running KDE. 

Plasmashell: 5.22.5
Qt: 5.15.2
KDE Frameworks: 5.87.0

I am using Turkish-F keyboard and I have customized my keyboard with .Xmodmap file to access frequently used symbols in programming which are difficult to reach.

My settings works as expected for years. I have recently started to use tmux.

When I open a new terminal, my settings are enabled and active as expected, however  as soon as I start tmux within the terminal, I lose my settings or my settings corrupts.

Following is my .tmux.conf file

````
# activate mouse support
set -g mouse on

# start window index at 1 instead of 0
set -g base-index 1

setw -g pane-base-index 1

# highlight window when it has new activity
setw -g monitor-activity on
set  -g visual-activity  on

# re-number windows when one is closed
set -g renumber-windows on

set -g default-command "${SHELL}"

set -g set-clipboard on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel 'xsel -b'
````

My `.Xmodmap` settings are as follows. In these settings basically, I change the positions of  `Alt` and `AltGr` along with the positions of some symbols.

````
keycode  31 = n N n N less less VoidSymbol
keycode  32 = h H h H greater greater degree
keycode  34 = q Q q Q at at
keycode  43 = t T t T U20BA VoidSymbol U20BA VoidSymbol t T U20BA VoidSymbol
keycode  44 = k K k K braceleft braceleft braceleft braceleft k K braceleft braceleft
keycode  45 = m M m M bracketleft bracketleft bracketleft bracketleft m M bracketleft bracketleft
keycode  46 = l L l L bracketright bracketright bracketright bracketright l L bracketright bracketright
keycode  47 = y Y y Y braceright braceright braceright braceright y Y braceright braceright

remove mod1 = Alt_L Meta_L
remove mod5 = ISO_Level3_Shift Mode_switch
keysym Alt_L Meta_L = ISO_Level3_Shift Mode_switch
keysym ISO_Level3_Shift Mode_switch = Alt_L Meta_L
add mod1 = Alt_L Meta_L
add mod5 = ISO_Level3_Shift Mode_switch
````

As soon as I start tmux in the terminal, specifically I lose switching of Alt-AltGr. They return to original positions.  After I exit from the tmux, the settings have also gone for the terminal. I have to manually apply the command xmodmap ~/.Xmodmap to recover the setting for the current terminal or in tmux.

Normally I apply  `xmodmap ~/.Xmodmap` in bash_profile. But after having these problems, I added `xmodmad .Xmodmap` command in the end of the `.bashrc` file.

I have asked this question in tmux mailing list but could not solve the problem.

**Comment by nicm** [comment]
Logs?

**Comment by benibilme** [comment]
Hello,

I could not respond sorry, I  do not know how to capture logs you needed or meaning of tmux logs. I have seen a plugin which captures screen session.  Please give me some directions how to do it and I will post the logs. The problem affects whole system. After starting tmux it infects other applications and shells as well.

**Comment by nicm** [comment]
Did you try not running xmodmap if inside tmux:
~~~~
[ -z "$TMUX" ] && xmodmap ...

**Comment by benibilme** [comment]
I have tried previously following based on a reply from the mailing list, but it did not help. I would like to emphasize that my settings only corrupted just after starting tmux in a normal working terminal.  

`[[ $DISPLAY ]] && [[ $TMUX ]] && [[ -f $HOME/.Xmodmap ]] && xmodmap $HOME/.Xmodmap`

**Comment by nicm** [comment]
tmux does not touch the X key mappings and has no way to do so, so this is completely a problem with your shell startup files. Are you sure you added this check this to every `xmodmap` in your shell profiles?

**Comment by benibilme** [comment]
Yes, It only used to be in my .bash_profile only. After having these problems, which started after I started to use tmux, I put it in the end of my .bashrc file.  To the best of my knowledge, .bashrc should cover every possibility since I am using bash shell default.

**Comment by nicm** [comment]
Try `chmod -x $(which xmodmap)` as root just before starting tmux and see if the problem goes away when you start tmux, if it does then you are still running xmodmap from somewhere.

**Comment by benibilme** [comment]
In my system, xmodmap seems to have the correct permissions. 
````
$ which xmodmap
/usr/bin/xmodmap
$ ls -l /usr/bin/xmodmap
-rwxr-xr-x 1 root root 43112 May 16  2020 /usr/bin/xmodmap
````
However, I did what you suggested.
````
ls - /usr/bin/xmodmap
-rw-r--r-x 1 root root 43K May 16  2020 /usr/bin/xmodmap
````
The problem still persists. 

I just want to point out again: 

The interesting thing is  while the terminal is functioning properly, just after I start tmux, xmodmap bindings are gotten lost in tmux, but also when I exit from tmux, the binding are lost in the terminal as well. If I specifically give the command xmodmap $HOME/.Xmodmap in the terminal or in tmux the settings are restored. This behavior  is not 100% consistent, rarely tmux function properly. I noticed that when the problem occurs, tmux starts but does not give the prompt easily, it lags for a while and then gives the prompt.

**Comment by nicm** [comment]
You need remove all the x bits from xmodmap so it cannot work (or move it somewhere else might be better, then you can still run it manually).

I can't really help you that much here other than to tell you something is running xmodmap or some command to change this, either from a shell profile or some other script that is being invoked when tmux starts.

**Comment by benibilme** [comment]
Hello,

I  removed execute permissions. When I start tmux in the terminal, I receive  `/usr/bin/xmodmap permission denied.`  because of the setting in bashrc. I believe there are no other xmodmap running. The problem also persists. plocate in my system also reports one xmodmap executable in mysystem. 

````
$ plocate xmodmap
/usr/bin/xmodmap
/usr/share/bash-completion/completions/xmodmap
/usr/share/licenses/xorg-xmodmap
/usr/share/licenses/xorg-xmodmap/COPYING
/usr/share/man/man1/xmodmap.1.gz
/usr/share/vim/vim82/ftplugin/xmodmap.vim
/usr/share/vim/vim82/syntax/xmodmap.vim
/usr/share/zsh/functions/Completion/X/_xmodmap
````

**Comment by nicm** [comment]
But you shouldn't get an error, because you are guarding xmodmap by checking TMUX?

**Comment by benibilme** [comment]
I receive error after I start tmux, message is displayed in tmux terminal, since following settings in the .bashrc, and now xmodmap has no execute permissions. I do not receive error  in the normal terminal as expected since normal terminal is guarded by TMUX environment variable.   

`[[ $DISPLAY ]] && [[ $TMUX ]] && [[ -f $HOME/.Xmodmap ]] && xmodmap $HOME/.Xmodmap`

**Comment by nicm** [comment]
No, you want to run xmodmap *outside* tmux, not inside. Your check is the wrong way round.

**Comment by benibilme** [comment]
Hello,

I have been literally sick of this fragile .Xmodmap configuration and have been wanting to replace it with custom keyboard layout. I spent a long night and created  custom console and x keyboard layouts. After activating them, tmux worked  fine. I brutally swapped the Alt and AltGr keycodes in console and X environment.  Swapping Alt and AltGr with .Xmodmap has proved to be very fragile.  There are many options to switch alt(left alt) or altgr (right alt) keys with different keys in xkb but not a direct swapping between them as an option. The safest approach seemed to be switching keycodes witch solved my problem along with other mappings. I believe tmux somehow triggers X in a way that my local settings are overridden.

I am leaving links that partially helped me. Thank you for the responses. 

[Arch Keyboard Configuration Wiki](https://wiki.archlinux.org/title/Linux_console/Keyboard_configuration)
[Blog Post](https://people.uleth.ca/~daniel.odonnell/Blog/custom-keyboard-in-linuxx11)

**Comment by nicm** [comment]
OK great.

tmux doesn't interact with X at all and it has no way to do so, the only things that can be doing this are your shell profiles or your terminal.
