### ISSUE TITLE
tmux doesn't render any of Power10k icons

### ISSUE THREAD

**Issue by TheZadok42** [tmux/tmux#2975]
### Issue description
Using tmux with Power10k (on oh-my-zsh) doesn't render any of the icons

### Required information

Please provide the following information:

* tmux version `tmux 3.2a`
* Platform `Linux Unknown` (Manjaro).
* inside - `screen-256color`
* outside - `xterm-256color`

[client.log](https://pastebin.com/pmURxAuW)

![image](https://user-images.githubusercontent.com/28902371/141640057-b175c03a-699f-497c-8b12-b5114a020c7f.png)

**Comment by nicm** [comment]
Show tmux server log please.

**Comment by hanjialeOK** [comment]
I have the same problem with zsh! But I solve it by `tmux -u new` and `tmux -u attach 0`. `-u` means force using utf8.

**Comment by TheZadok42** [comment]
This worked!  
Thank you @hanjialeOK

**Comment by hanjialeOK** [comment]
Besides, I also got the other problem: [Zsh tab completion duplicating command name](https://stackoverflow.com/questions/11916064/zsh-tab-completion-duplicating-command-name). 
On ubuntu, I used `export LANG=C.UTF-8` to fix the two problems fundamentally. `-u` is no longer needed.
