### ISSUE TITLE
choose-tree: glitchy navigation with scrolling trees + vi bindings

### ISSUE THREAD

**Issue by frenchy64** [tmux/tmux#2976]
### Issue description

When a `choose-tree` exceeds the boundaries of the screen (after disabling the file preview with `v`) and becomes "scrollable", there are some issues with vi bindings.

1. `k` (up) navigation sometimes shifts the view of the tree a few elements up.
- to reproduce, create a tree with about 20 elements, and zoom in until only 10 elements are visible  (after `v`). now hold `k` and every few times the tree loops around the view will "skip" upwards. Contrast with `j` which scrolls smoothly.
2. `g` only selects the top viewable element (instead of the tree's top element), and then skips the view up after a few seconds
- to reproduce, create a tree that has at least 2 elements not viewable (after `v`). Select the bottom of the tree so several top nodes are hidden. Press `g` and wait a few seconds. Notice the top node is not selected and the screen has scrolled twice.
3. `G` only selects the bottom viewable element (instead of the tree's bottom element)
- to reproduce, create a tree that has at least 2 elements not viewable (after `v`). Select the top of the tree so several bottom nodes are hidden. Press `G`. Notice the bottom node is not selected.

### Required information

```
uname -sp && tmux -V && echo $TERM

Darwin i386
tmux 3.2a
xterm-256color
```

**Comment by nicm** [comment]
`g` and `G` are page up/down so they may not necessarily leave you on the very first or last line. The line chosen seems correct to me (if I have height + 2 lines and I press `g` from the last line I end up on the second line and from the second last line I end up on the first line, and vice versa for `G`). However for me when using `g` leaves me on the second line, pressing any other key will move to the first line, that is presumably the skipping you mention, not sure why that is happening.

I don't see anything funny with `k` but I didn't try too hard yet.

**Comment by nicm** [comment]
For copy mode, `g` and `G` are history start/end and `C-b` and `C-f` are page up/down, so probably we should change tree mode to be the same.

**Comment by frenchy64** [comment]
> I don't see anything funny with k but I didn't try too hard yet.

The `k` issue was something I found while trying to describe the `g`/`G` inconsistency from copy mode. Not as big a deal.

**Comment by nicm** [comment]
Does this make g and G behave as you expect? [x.diff.txt](https://github.com/tmux/tmux/files/7632641/x.diff.txt)

**Comment by nicm** [comment]
I have applied this now, thanks!
