### ISSUE TITLE
Getting weird characters when scrolling or using arrow keys

### ISSUE THREAD

**Issue by KoB-Kirito** [tmux/tmux#2979]
Hey, I get weird chars displayed when I scroll or press arrow keys while in tmux.
<img width="1044" alt="Bildschirmfoto 2021-11-18 um 19 10 06" src="https://user-images.githubusercontent.com/51691757/142492966-c48bc9ab-35cb-4738-abec-2b0789623bfb.png">
I use Mac Terminal. Could someone help me?

* tmux version (`tmux -V`).
3.1c

* Platform (`uname -sp`).
Linux unknown. Should be Debian 11.

* $TERM inside and outside of tmux (`echo $TERM`).
outside: xterm-256color, inside: screen-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).
Can't kill it right now.

**Comment by nicm** [comment]
Try detaching and reattaching tmux, or running the `reset` command inside tmux or after detaching it.
