### ISSUE TITLE
Remap keys while in `choose-tree`

### ISSUE THREAD

**Issue by pchabros** [tmux/tmux#2983]
Is it possible to remap keys while being in `choose-tree`?

For example it's possible to remap some keys while being in `copy-mode` with:

`bind -T copy-mode-vi`

Is there an equivalent for `choose-tree`?

I tried `choose-tree`, `choose-mode` and `choose-tree-mode` but for all I got an error `table chose-mode doesn't exist`.

**Comment by nicm** [comment]
No there is no equivalent for choose modes.

You can make simple changes by binding keys in the root table, for example something like (not tested):

~~~~
bind -n x if -F '#{==:#{pane_mode},tree-mode}' { send Up } { send x }
~~~~

**Comment by pchabros** [comment]
Thank you. This is the exact code that worked:

```
bind-key -T root  j if -F "#{==:#{pane_mode},tree-mode}" "send h" "send j"
bind-key -T root  k if -F "#{==:#{pane_mode},tree-mode}" "send j" "send k"
bind-key -T root  l if -F "#{==:#{pane_mode},tree-mode}" "send k" "send l"
bind-key -T root \; if -F "#{==:#{pane_mode},tree-mode}" "send l" "send \;"
```
