### ISSUE TITLE
A late response to a secondary DA request gets passed on to the client

### ISSUE THREAD

**Issue by romkatv** [tmux/tmux#2984]
If the outer TTY takes longer than a second to reply to `[>0c` (secondary DA request), the eventual reply (e.g., `\033[>0;10;1c`) gets passed to the client and may end up in unexpected places -- perhaps in a file that one has opened in an editor.

Execution flow goes like this:

1. tmux starts.
2. tmux sends `[>0c` to the outer TTY (`tty_send_requests`) and starts a 1s timer.
3. when the timer expires (`tty_start_timer_callback`), tmux sets `TTY_HAVEDA` bit.
4. when the reply eventually arrives, `tty_keys_device_attributes` doesn't look at it because `TTY_HAVEDA` is set.

Unfortunately, I don't have logs. I've reconstructed this from a bug report from a user of my code (https://github.com/romkatv/zsh4humans/issues/177#issuecomment-975568582).

**Comment by nicm** [comment]
What terminal takes more than a second to respond to this?

**Comment by romkatv** [comment]
I don't know which terminal but it's on Windows 11. I'm 100% with you that it's not normal for a terminal to take over a second to reply. My response from the bug I linked above:

> A proper fix would be to figure out why your terminal takes so long to reply and fix it.

I've implemented a workaround in my code so that `\033[>0;10;1c` at random times doesn't break me. I've opened this issue in case you'll find this information useful. It's fine with me if you deprioritize or close it.

**Comment by nicm** [comment]
We can probably bump it to 2 or 5 seconds or something, I'll take a look next week.

**Comment by shah** [comment]
@nicm this was happening for me on `Windows 11` using `Windows Terminal 1.11.2921.0`.

**Comment by nicm** [comment]
I have bumped the timeout to three seconds, the change will be in GitHub when it syncs later on. If this still happens I think you will need to either live with it or talk to the terminal developers about why it is taking so long. Thanks!
