### ISSUE TITLE
Vi backspace=indent,eol,start?

### ISSUE THREAD

**Issue by ascpeter** [tmux/tmux#2985]
Problem: Backspace key is difficult to use in tmux's vi copy-mode. It behaves like backspace in vi, which is understandable. But I would like to be able to modify it to behave like the vi setting:

`set backspace=indent,eol,start`

This modifies backspace to delete-char-to-left beyond the start of input. I searched many sites, tried a lot of keybindings and still have not found a solution. 

Version: 3.2a
Platform: zsh, Mac
$TERM out of Tmux: "xterm-256color"
$TERM in Tmux: "screen"

Thanks!

**Comment by nicm** [comment]
I don't really understand what behaviour you are trying to describe, you may be able to simulate it by binding the key to a combination of other commands.

**Comment by ascpeter** [comment]
Basically I was looking for a way to allow normal backspace, even if the content being backspaced was from a prior insert (`set backspace=start` behavior for vim). But I found that this works fine to simulate the same behavior:

`bind -n BSpace send-keys Left Delete`

Closing this.

**Comment by ascpeter** [comment]
The above causes weirdness across lines. I came to realize that it's more of a bash issue (sorry, Tmux-newbie error!) and found this fix that works way better:

https://unix.stackexchange.com/questions/368231/going-over-start-of-insert-action-in-z-shell-vi-mode

Basically, edit .bashrc/.zsh/etc with:

```
bindkey -M viins '^?' backward-delete-char
bindkey -M viins '^H' backward-delete-char
```
