### ISSUE TITLE
tmux crash at renaming session

### ISSUE THREAD

**Issue by sheeaza** [tmux/tmux#2986]
* tmux version 3.2a
* Platform: nixos-unstable
* $TERM inside and outside of tmux (`echo $TERM`): both xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`)
[tmux-client-46150.log](https://github.com/tmux/tmux/files/7609305/tmux-client-46150.log)
[tmux-out-46152.log](https://github.com/tmux/tmux/files/7609306/tmux-out-46152.log)
[tmux-server-46152.log](https://github.com/tmux/tmux/files/7609307/tmux-server-46152.log)
.
reproduce step:
1. < prefix > + $
2. < ctrl >+< leftkey >, press about 3 or 4 times
3. tmux crash

**Comment by bfrg** [comment]
Can you try it with the latest github version? I've had similar issues in the past which have been fixed by now.

**Comment by sheeaza** [comment]
> Can you try it with the latest github version? I've had similar issues in the past which have been fixed by now.

Yep, I tried the package from master branch, `next-3.4` , there is no such issue
So will close this issue.
Thanks
