### ISSUE TITLE
`lsw -F "#{window_name}"` reports incorrectly when used in run-shell, if-shell

### ISSUE THREAD

**Issue by 097115** [tmux/tmux#2987]
### Issue description

Open a session with a few different windows. Check that `tmux lsw -F "#{window_name}"` actually reports all those different names. Now, create the following binding:

    bind-key x if-shell 'tmux lsw -F "#{window_name}" | grep SOME_INACTIVE_WINDOW_NAME' 'display-message yay' 'display-message nay'

Press `<Prefix>x`, observe `nay` in the status-line.

To debug, can try the following:

    bind-key x if-shell 'tmux lsw -F "#{window_name}" > /tmp/test' 'display-message yay' 'display-message nay'

Press `<Prefix>x` again (it will obviously display `yay` but that doesn't matter), and then open `/tmp/test`: it will contain the name of the active window repeated on as many lines as many windows are actually present.~

**EDIT:**

Or, just compare this:

    tmux lsw -F "#{window_name}"

and this:

    tmux run-shell 'tmux lsw -F "#{window_name}"'

### Required information

Please provide the following information:

* tmux version: 3.3, 3.4, latest master
* Platform: macOS, Ubuntu, etc.

**Comment by nicm** [comment]
if-shell also expands so you will need to escape the # if you want list-windows to do it instead.

**Comment by 097115** [comment]
@nicm, I'm not sure I follow you.

    bind-key x if-shell 'tmux lsw -F "\#{window_name}" ....

obviously doesn't work, too.

**Comment by nicm** [comment]
##

**Comment by 097115** [comment]
Oh. Thanks :)
