### ISSUE TITLE
Broken chars on panes with constant log output

### ISSUE THREAD

**Issue by CaptainCannabis** [tmux/tmux#2988]
I am running several tmux session with different linux users on a Ubuntu 20.04.3 LTS. Sometimes some of the panes inside the sessions show broken charsets like in the screenshot attached. It always happens in panes that show constant output like logs of a running docker pod or a simple tail -f.

![image](https://user-images.githubusercontent.com/5312061/144090689-6a119cac-ed5b-476a-975b-29c21f770451.png)

Only solution atm is to close the pane and restart the process in a new one. How to prevent that this happens or maybe reload the output without killing the pane/process?

**Comment by nicm** [comment]
Seems like you are writing data which contains binary escape sequences to the terminal which is never a good idea.

You could pipe through `cat -v`.

You can do `C-b : send -R` to reset (or run `reset` from the shell), although this will clear the pane as well.

**Comment by CaptainCannabis** [comment]
> Seems like you are writing data which contains binary escape sequences to the terminal which is never a good idea.
> 
> You could pipe through `cat -v`.
> 
> You can do `C-b : send -R` to reset (or run `reset` from the shell), although this will clear the pane as well.

Thank you for such a quick response and the hints. Will report if `cat -v` to transform non printable characters will fix my problems.
