### ISSUE TITLE
Add support for RGB UI colors

### ISSUE THREAD

**Issue by landaire** [tmux/tmux#299]
With 427b820 tmux finally has support for RGB colors but the code which returns an `int` color from a string eventually calls `colour_find_rgb()` which returns the nearest color from the 256 color set. I traced this back from [`cmd_set_option_set()`](https://github.com/tmux/tmux/blob/dc42c35f1f04d3bd431c52dde0906965c6db2d6c/cmd-set-option.c#L330-L334), `OPTIONS_TABLE_COLOUR`, which is the type for most of the UI elements.

I wouldn't mind submitting a patch to make this check to see if more than 256 colors are supported but is there a suggested way to go about this? I noticed that in `cmd_set_option_set()` and `colour_fromstring()` there doesn't seem to be any way to get the `struct tty` which would make it trivial to determine if TC is supported.

Mentioning issue #34 in case someone else comes across this.

**Comment by nicm** [comment]
I suggest you make it a 32-bit value with flags in the top byte showing
whether it is a 256 or RGB or plain colour, something like:

#define COLOUR_VALUE(c) ((c) & 0xffffff)
#define COLOUR_256 (1<<31)
#define COLOUR_RGB (1<<30)

Then change colour_fromstring and colour_tostring to use them rather
than setting bit 8 for 256 colours.

You will need to change the screen-write.c functions that support
#[bg=red] and also anything that uses colour values from options (but I
think most will be using style_apply or some of the other style
functions now).

You should not need to do any conversion when you read the colour from
the option, if you set up the grid_cell correctly it will be converted
when written to the terminal if needed.

**Comment by nicm** [comment]
Please drop me an email if you need any further help.

**Comment by landaire** [comment]
Will do. Thanks for the suggestions. I'll try to take a stab at it this weekend.
