### ISSUE TITLE
Different environment vars inside tmux session vs tmux run-shell

### ISSUE THREAD

**Issue by primeapple** [tmux/tmux#2992]
### Issue description

So I have my issue nailed down to the following:
I get different environment variables from within tmux vs `tmux run-shell`

When I run `echo $PATH` inside tmux I get:
```
/home/me/.asdf/shims:/home/me/.asdf/bin:/home/me/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```
However when running `tmux run-shell 'env'`, a lot less variables. The PATH I get is:
```
/home/me/.asdf/installs/tmux/3.2a/bin:/usr/local/bin:/usr/bin
```

I have tmux 3.2a installed through [asdf](https://github.com/aphecetche/asdf-tmux). I know this may be part of the problem. I'm willing to fix it myself. However, I need to know, where tmux gets its environment variables from when running `tmux run-shell`.  
Does it parse your `.bashrc`, `init.fish`, whatever? Does it use the current defined env vars from the shell you are running the command from?  
This alone would help me fix this issue :)

### Required information

Please provide the following information:
```shell
tmux -V
# tmux 3.2a

which tmux
# /home/me/.asdf/shims/tmux

cat /etc/os-release
# NAME="Manjaro Linux"
# ... (not relevant, I guess)

fish --version
# fish, version 3.3.1

echo $TERM #outside tmux
# xterm-kitty

echo $TERM #inside tmux
# screen-256 color

asdf --version
# v0.8.1
```
You will get logs, if needed, currently I think this is a bit overkill for my question :)

**Comment by nicm** [comment]
`run-shell` uses the global environment, you should treat it as running a noninteractive shell from a separate program, not as running a program directly from the current shell.

**Comment by systemmonkey42** [comment]
How are launching `tmux`?  As a login shell replacement?  From your .bashrc/fishrc or interactively?

If you launch it as a login whell replacement, I would suggest that is why you have only a bare environment.

Normally your shell environment is set up as part of the ".bash_login" and ".bash_rc/fishrc" parsing process.  Only at the end of that should you launch tmux.

tmux itself will never parse your shell profiles.

**Comment by primeapple** [comment]
Hmm. Lets test it.
Lets start with a fresh fish shell (I source the asdf wrappers in `config.fish`), with no tmux server running
```sh
tmux has-session
# no server running on /tmp/tmux-1000/default
echo $PATH
# /home/me/.asdf/shims /home/me/.asdf/bin /home/me/.bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
```
For now this is exactly how it should be.  
Let's start tmux
```
tmux
# now inside tmux
echo $PATH
# /home/me/.asdf/shims /home/me/.asdf/bin /home/me/.bin /home/me/.asdf/installs/tmux/3.2a/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
# notice how we got an additional entry for the actual tmux binary
tmux run 'echo $PATH'  # same result with ':' instead of space between the paths, when running PREFIX ->  :run 'echo $PATH'
# /home/me/.asdf/installs/tmux/3.2a/bin /home/me/.asdf/shims /home/me/.asdf/bin /home/me/.bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
# notice how the additional tmux binary entry now went in front of the path
```
This is the main problem I have. The wrong tmux binary has now precedence. See:
```
# still in tmux
which tmux
# /home/me/.asdf/shims/tmux
# this is the binary I want
tmux run 'which tmux'
# /home/me/.asdf/installs/tmux/3.2a/bin/tmux
# this is NOT the binary I want :(
```

The `.asdf/shims/tmux` file is just a wrapper to make asdf call the currently selected tmux version. This is the the one in `.asdf/installs/tmux/3.2a/bin/tmux`.  
However, I need to get the `.asdf/shims/tmux` script to be returned by `which tmux`.

What do you think about this?

**Comment by systemmonkey42** [comment]
> What do you think about this?
man fish

This is clearly not a tmux issue.

**Comment by primeapple** [comment]
So at least it seems, that tmux adds the tmux binary to the path, is this right?
Why is this done?

I don't see exactly why fish is supposed to be the problem? Just tested it and it behaves the same in MacOS. I started a bash shell from my fish shell and it behaved exactly the same.  
Do you have any argument for fish being the problem?

**Comment by nicm** [comment]
run-shell uses the global/session environment so you will get whatever is
in there.

**Comment by primeapple** [comment]
Thank you. I'll try to investigate further and reopen this if the problem persists on a minimal config.

**Comment by primeapple** [comment]
Hey @systemmonkey42 , the issue is also in Bash, with a clean .tmux.conf on a clean system.

Referencing https://github.com/asdf-vm/asdf/issues/1114 , I guess it is a mixed problem between asdf and tmux

I would like to keep this open until we get it to work in any of the issues, if thats fine.

**Comment by systemmonkey42** [comment]
> Hey @systemmonkey42 , the issue is also in Bash, with a clean .tmux.conf on a clean system.

I struggle to understand how you claim the issue is with `asdf` installer, then claim its a tmux issue, and a fish issue, and a bash issue. 

Just for fun, I installed and played with `asdf` and installed three things

  vim
```
asdf plugin add vim
asdf install vim
$ which vim
/home/admin/.asdf/shims/vim
$ vim +'!which vim'
/home/admin/.asdf/installs/vim/8.2.3757/bin/vim
```

  nodejs
```
asdf plugin add nodejs
asdf plugin install nodejs
$ which node
/home/admin/.asdf/shims/node
$ node -e "child_process.exec('which node',(_,o)=>console.log(o))"
/home/admin/.asdf/installs/nodejs/17.2.0/bin/node
```

  tmux
```
asdf plugin add tmux
asdf plugin install tmux
$ which tmux
/home/admin/.asdf/shims/tmux
$ tmux new-session -d
$ tmux run-shell 'which tmux'
/home/admin/.asdf/installs/tmux/3.2a/bin/tmux
```

Again, Not a tmux bug.  Not a bash bug.  Not a fish bug.  Not an asdf bug.  Not a asdf tmux plugin bug.
Everything is working as designed.

What *exactly* is the problem you are trying to solve?

**Comment by primeapple** [comment]
First of, thank you so much for your reply and your walkthroughs.  
So let me get this straight.

> I struggle to understand how you claim the issue is with asdf installer, then claim its a tmux issue, and a fish issue, and a bash issue.

I don't know exactly where the issue is coming from. These were potential problematic applications, that COULD produce the bug.

The problem I have is, whenever I run scripts, that reuse the tmux executable, within tmux via `run shell`.  
This sounds a little complicated, right? So an actual case is installing the [tmux-continuum plugin](https://github.com/tmux-plugins/tmux-continuum).  
This will (with a certain setting) create a systemd unit file, to autostart a tmux server at bootup. This systemd unit file is created by using `which tmux` to figure out the current tmux executable. See this line: https://github.com/tmux-plugins/tmux-continuum/blob/912149820bf48a3a128732854815009352dd2598/scripts/handle_tmux_automatic_start/systemd_enable.sh#L14  
So when `which tmux` does not point to the tmux shim, but on the actual tmux binary (`/home/admin/.asdf/installs/tmux/3.2a/bin/tmux` in your case), it does NOT work on systemstart, because some asdf environment variables are not set. It has to be set to the tmux shim to work.

I hope you now understand my problem better.

> I personally see a potential problem, where your shell RC file (~/.bashrc for example) sources ~/.asdf/asdf.sh on shell startup, thus removing ~/.asdf/shims from your path, and re-inserting it at the beginning.

What you found here is very valuable. It seems that every application, that calls a shell command, has it's actual version set in the path before it's shim. I would argue, that this is an undesired behaviour, but I'm not sure, maybe the asdf guys have a reason to implement it like this.  
I'll add your finds to the asdf issue, and play around with your solution, to see if it works. 

Will report back, your answer was already very helpful, thank you!

**Comment by primeapple** [comment]
Hmm, I answered yesterday, but it seems my answer got somehow removed. Anyway, here again:

The fix of @systemmonkey42 is not working for me. On empty manjaro VM with bash as default and the suggested code added to the `.bashrc`, I get:

In normal shell:
```sh
echo $PATH
# /home/me/.asdf/shims:/home/me/.asdf/bin:/home/me/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
which tmux
# /home/me/.asdf/shims/tmux
```

In normal shell, executing tmux commands:
```sh
tmux new-session -d
tmux run "echo $PATH"
# /home/me/.asdf/shims:/home/me/.asdf/bin:/home/me/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
tmux run "which tmux"
# /home/me/.asdf/installs/tmux/3.2a/bin/tmux
```

In tmux:
```sh
tmux
echo $PATH
# /home/me/.local/bin:/home/me/.asdf/installs/tmux/3.2a/bin:/home/me/.asdf/shims:/home/me/.asdf/bin:/home/me/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
which tmux
# /home/me/.asdf/installs/tmux/3.2a/bin/tmux
```

I think this issue is by design of `asdf` and there is nothing tmux can do.  
So if you don't have anything more to say or suggest, you are free to close it.

Thank you all for your responses! I love tmux <3

**Comment by systemmonkey42** [comment]
>I think this issue is by design of asdf and there is nothing tmux can do.

Firstly,  you are still failing to articulate what problem, if any, are *actually* having.

Secondly, the output clearly show that `which tmux` and `tmux run "which tmux"` now return the same information.  Based on your description of what you thought was causing your problem in your original message, this means its solved.

If you believe the problem is that TMUX is modifying yoor path, or worse, that TMUX _should_ modify your path, then you are simply mistaken.

If you think the problem is `asdf` is modifying your path, then you are correct.  Consider upgrading to `asdf` v0.9.0

**Comment by primeapple** [comment]
This is the problem:

`which tmux` outside of tmux gives `/home/me/.asdf/shims/tmux`, which I want  
`which tmux` inside of tmux gives `/home/me/.asdf/installs/tmux/3.2a/bin/tmux`, which I don't want

I want this because of: 

> The problem I have is, whenever I run scripts, that reuse the tmux executable, within tmux via run shell.
This sounds a little complicated, right? So an actual case is installing the tmux-continuum plugin.
This will (with a certain setting) create a systemd unit file, to autostart a tmux server at bootup. This systemd unit file is created by using which tmux to figure out the current tmux executable. See this line: https://github.com/tmux-plugins/tmux-continuum/blob/912149820bf48a3a128732854815009352dd2598/scripts/handle_tmux_automatic_start/systemd_enable.sh#L14
So when which tmux does not point to the tmux shim, but on the actual tmux binary (/home/admin/.asdf/installs/tmux/3.2a/bin/tmux in your case), it does NOT work on systemstart, because some asdf environment variables are not set. It has to be set to the tmux shim to work.

I DONT want tmux to modify my path, however it clearly does, because it adds the actual asdf tmux binary to it.  
It seems to be because of asdf, I'll check 0.9

**Comment by nicm** [comment]
What is actually in `/home/me/.asdf/shims/tmux`? Does it change `PATH`?

Whatever is in `PATH` before running tmux will go into the global environment, that is what `run-shell` will start with and it is unlikely a noninteractive `/bin/sh` will change it.

**Comment by systemmonkey42** [comment]
>What is actually in /home/me/.asdf/shims/tmux? Does it change PATH?

A script that points your PATH to the correct version of tmux, and launches it.

`asdf` allows you to install multiple versions of an application like `tmux`, and specify which version you want to launch.

If you run `asdf install tmux 3.2a` then `asdf install tmux 3.3-rc`, you can choose the default version via 
`asdf global tmux 3.2a`.

However in a sub-directory (like ~/work), you can specify a "local version" via `asdf local tmux 3.3-rc`.

So.. if I am in the ~/work directory  and type `tmux`, it launches the shim, which detects I want the '3.3-rc' release,
pushes the path to the 3.3-rc build onto the head of $PATH, and launches tmux with any arguments provided.

Once inside tmux, if I change OUT of the ~/work directory, and I run 'tmux split-window` for example, the changes
to `PATH` ensure the 3.3-rc version is run.

@primeapple  says
> The problem I have is, whenever I run scripts, that reuse the tmux executable, within tmux via run shell.

and goes on to explain about somehow integrating `asdf`, `tmux-continuum` and `systemd` which will never
work without practically re-writing them, because `tmux-continuum` is not written to understand how `asdf` packages 
applications, and `asdf` is not written to be launched from `systemd`.

Quite frankly, if @primeapple just installed a supported tmux package, I suspect everything would just work.  Its the lack of understanding about how `asdf` does its thing which is making it all so difficult.

**Comment by nicm** [comment]
Right but I didn't ask what it did, I asked what was in it.

**Comment by systemmonkey42** [comment]
My bad..

```
#!/usr/bin/env bash
# asdf-plugin: tmux 3.2a
exec ${HOME}/.asdf/bin/asdf exec "tmux" "$@"
```

**Comment by nicm** [comment]
I don't see anything in `bin/asdf` that modifys `PATH` but it should be easy enough to test, do something like:
~~~~
pkill tmux
env -i TERM=$TERM PATH=/usr/bin:/bin /home/me/.asdf/shims/tmux new -d /bin/cat
/home/me/.asdf/shims/tmux showenv -g
~~~~
And see if it shows `PATH` and what it is set to.

**Comment by systemmonkey42** [comment]
>I don't see anything in bin/asdf that modifies PATH but it should be easy enough to test, do something like:

`bin/asdf` launched `lib/commands/command-exec.bash` which in-turn calls `with_shim_executable` in `lib/utils.bash` which in turn calls `with_plugin_env` in the same file, which sets the PATH.

```
$ env -i ASDF_DIR=$ASDF_DIR TERM=$TERM PATH=/usr/bin:/bin ~/.asdf/shims/tmux new -d /bin/cat
$ /home/me/.asdf/shims/tmux showenv -g
ASDF_DIR=/home/me/.asdf
PATH=/home/me/.asdf/installs/tmux/3.2a/bin:/usr/bin:/bin
PWD=/home/me
SHLVL=0
TERM=xterm-256color
```

`asdf` does update PATH.  There is no question about that. Its by design.

**Comment by nicm** [comment]
Right so this doesn't seem like a problem at all then really.

If you use `run-shell` you will need to fix up `PATH` yourself or (by the look of it) source `asdf.sh` to do it, same as any noninteractive shell really.

**Comment by nicm** [comment]
Or another option is to do `tmux setenv -g PATH "$PATH"` from a shell where PATH is set to what you want in order to replace the value in the global environment.

**Comment by primeapple** [comment]
Thank you guys for your time.

I've come up with the conclusion to just not use `asdf` to manage tmux. 
Even tho, TMUX-Continuum can be configured to work with asdf manged tmux, it requires a lot of bugfixing, at least on system that use systemd. I don't even want to think about what happens when I would switch the tmux version. So just use the tmux version provided by the package manager.

Thank you, again.
