### ISSUE TITLE
Feature Request: Allow customization of popup window border style

### ISSUE THREAD

**Issue by fritzrehde** [tmux/tmux#2993]
"I don't want to provide customization or style of the border, I want to keep that standard. Or at least, it should apply to menus also."

_Originally posted by @nicm in https://github.com/tmux/tmux/issues/1842#issuecomment-602012904_

I do not understand why @nicm does not want to provide customization for the border style of the popup window, I personally think it would be a very useful feature. The command `display-popup` could either receive a flag `--color=...` or, preferably, an option `popup-border-style` could be used.

**Comment by nicm** [comment]
This was done months ago and will be in the next release.
