### ISSUE TITLE
Feature request/binding help for moving a pane/window to top of stack

### ISSUE THREAD

**Issue by mbpowers** [tmux/tmux#2994]
I have been using `swap-pane -D` and `swap-pane -U` to move panes around, but when the last/first is swapped with the first/last pane or window respectively it messes up the order (which is as intended but I don't like it).

For example if I continually swap-pane with pane `a` it will result in
```
a b c d
b a c d
b c a d
b c d a
a c d b
``` 
Instead of swapping from the last and first I want to find a way to insert it at the beginning of the stack so that when the pane wraps around it returns to order `a b c d` instead of `a c d b`. Same thing goes for window ordering.

Not sure if some sort of insert-pane/window feature or a flag to swap-pane/window or something would be necessary but it is an idea. I admit this is quite minor and can be avoided by going back through the list instead of trying to wrap around, but I feel this would be more natural for most users.

If it is just me that's annoyed by this and someone could help with a hacky binding solution that would be much appreciated! I tried my hand at it without luck. 

Love tmux, thanks!

**Comment by nicm** [comment]
I don't really understand this, what ordering are you talking about? Panes are ordered by their position.

**Comment by mbpowers** [comment]
I am talking about the order based on their position. I am looking for a way to move the pane up and down like a stack instead of just swapping their position. This would mean when a pane is pushed down the stack from the last position, it would be placed at the top of the stack pushing the others down.

For example
```
pos before after
 1    a     (d)
 2    b      a
 3    c      c
 4   (d)     b
```
where d is the active pane being pushed down.

**Comment by nicm** [comment]
Do you want `rotate-window`?

**Comment by mbpowers** [comment]
I want to have a single keybinding that swaps unless it is going past the bottom (or top if in the opposite direction), in which case it would rotate.
```
pos initial swapped swapped swapped rotated
 1    (a)      b       b       b      (a)
 2     b      (a)      c       c       b
 3     c       c      (a)      d       c
 4     d       d       d      (a)      d
```
like the behavior of a stack. Is there any way to do this with a single bind?

**Comment by nicm** [comment]
I think you will need to write a script to do this.

**Comment by mbpowers** [comment]
Okay thanks I will look into that.
Just to make sure there are no conditionals possible in binds correct?

**Comment by nicm** [comment]
You can do conditionals with `if -F`, look at https://github.com/tmux/tmux/wiki/Formats. But I would probably just write a shell script and bind it with `run-shell`.

**Comment by mbpowers** [comment]
Thanks very much! Will post my script back here if I get it working in case someone else wants it.
