### ISSUE TITLE
Manual - Control mode notifications - unlinked-window documentation partially missing

### ISSUE THREAD

**Issue by AntonGepting** [tmux/tmux#2996]
Hello, 

thank you for such a great tool as tmux!

### Issue description

It looks like few following notifications are undocumented in manual (in control mode chapter), but they can be used in `control-notify.c`:

* `%unlinked-window-close` https://github.com/tmux/tmux/blob/10b3cd17fa94e3ac129080e68c69d2130b015fb2/control-notify.c#L107
* `%unlinked-window-renamed` https://github.com/tmux/tmux/blob/10b3cd17fa94e3ac129080e68c69d2130b015fb2/control-notify.c#L144-L145

Not important, but I've submitted it anyway. Thank you!

### Required information

* `tmux 3.2a` (`tmux -V`).
* `Linux unknown` (`uname -sp`).
* `Linux pc_3_linux 5.14.0-4-amd64 #1 SMP Debian 5.14.16-1 (2021-11-03) x86_64 GNU/Linux` (`uname -a`).
* `screen-256color` (`echo $TERM`).

**Comment by nicm** [comment]
Added now, thanks!
