### ISSUE TITLE
Constant server crash: server exited unexpectedly

### ISSUE THREAD

**Issue by adrianmihalko** [tmux/tmux#2997]
I am constantly getting tmux server crash.

Client: iTerm2 - > mosh -> Ubuntu 18.04 server running tmux 3.3-rc.

<img width="1280" alt="Screenshot 2021-12-04 at 21 27 59" src="https://user-images.githubusercontent.com/733361/144723864-f20517ca-1c6e-4365-92a0-f4d480bd51a3.png">

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.3-rc
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
xterm-color (inside: see config)
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-out-29710.log](https://github.com/tmux/tmux/files/7654647/tmux-out-29710.log)
[tmux-client-29708.log](https://github.com/tmux/tmux/files/7654648/tmux-client-29708.log)
[tmux-server-last-200-line.log](https://github.com/tmux/tmux/files/7654649/tmux-server-last-200-line.log)

Config:

```
new-session
set-option -g mouse on
set-option -g status-right-length 200
setw -g automatic-rename on

set -s default-terminal 'tmux-256color'

set -g history-limit 30000
setw -g mouse on

set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'dracula/tmux'
# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, network, network-bandwidth, weather, time
set -g @dracula-plugins "cpu-usage network-bandwidth weather time"
set -g @dracula-show-timezone false
set -g @dracula-fixed-location 'Štúrovo'
set -g @dracula-network-bandwidth 'ens160'
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-fahrenheit false

# TMUX PLUGIN MANAGER
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by systemmonkey42** [comment]
tmux-3.4 has been available for about a month.  Are you able to build from the most recent commit and re-test?

Also, confirm the crash occurs without plugins (comment out the last line and compare).  The plugins themselves are automatically fetched from github and it is impossible to know what version you are running.

**Comment by nicm** [comment]
Yes - does this still happen with master?

**Comment by adrianmihalko** [comment]
Sorry for the late reply. I found out that the crash is happening when I am trying to click on links (both in Kitty and iTerm2).

Screen recording:

https://www.youtube.com/watch?v=eeAHCsnSwjU

**Comment by nicm** [comment]
Show logs from master please.

**Comment by adrianmihalko** [comment]
It seems to be fixed in master. Same problem as https://github.com/tmux/tmux/issues/3007
