### ISSUE TITLE
set-option -p pane-border-format changes border text in all panes in the same window

### ISSUE THREAD

**Issue by denizevrenci** [tmux/tmux#2999]
### Issue description

Looking at the manual, `-p` is used set pane options but `pane-border-format` applies to all of the panes in a window with `-p`, `-w`, `-s`, and without a flag; while `-g` applies the format to all windows. Is there a way to set the border format for a single pane?

### Required information

* tmux version: 3.2a
* Platform: "Linux unknown". Tested in WSL2 with an arch linux distribution.
* $TERM inside tmux: tmux-256color
* $TERM outside tmux: xterm-256color

**Comment by nicm** [comment]
Yes it is a window option, not a pane option. Does this make it work: [x.diff.txt](https://github.com/tmux/tmux/files/7659931/x.diff.txt)

**Comment by denizevrenci** [comment]
Yes, I confirmed that it works.
There is another issue though: the other flags and no flag commands with `set-option pane-border-format` does not alter the previously set format with `set-option -p pane-border-format`.  I don't know if this works the same with other pane options.

**Comment by damnskippy** [comment]
@nicm, just wondering if this change above will be merged into mainline?  Not sure, just wanted to confirm.Thank you.

**Comment by nicm** [comment]
Applied now, thanks!

**Comment by denizevrenci** [comment]
@nicm I had a question regarding the mechanics of this change.
> There is another issue though: set-option pane-border-format without a flag and with -w, -s, -g do not alter the previously set format with set-option -p pane-border-format.

I would expect that a wider option like `-w`, `-s`, or `-g` to override the previous setting applied with `-p`.

**Comment by nicm** [comment]
Most specific option scope wins.
