### ISSUE TITLE
Quitting copy mode with `q` doesn't redraw the status line

### ISSUE THREAD

**Issue by kballard** [tmux/tmux#300]
When exiting copy mode with `q`, tmux doesn't redraw the status line. This is problematic if the `status-left` or `status-right` values test the `pane_in_mode` variable, because it means the status line will be incorrect until the `status-interval` elapses and it redraws.

Reproduced with tmux 2.1 on OS X 10.11.3.

**Comment by ThomasAdam** [comment]
I'd say this is entirely correct.  If you want to call client-refresh -S,
you can do so in a binding.

**Comment by kballard** [comment]
How is this at all correct? I shouldn't have to rebind my q key just because my status uses the pane_in_mode variable. Entering copy mode refreshes it automatically, as does exiting copy mode by scrolling when using `copy-mode -e`. Since the variable exists and it's perfectly reasonable to use it in my status, the status should refresh when it changes. Heck, it's already refreshing every time I press the prefix key (presumably because of the existence of the variable that is 1 when the prefix key has been pressed) so obviously there's no real worry about refreshing it in response to the input state changing in general.

Really this just feels like an oversight to me, as in "oops I didn't think of people using that in the status".

**Comment by nicm** [comment]
Try this please:

~~~~
Index: window.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/window.c,v
retrieving revision 1.156
diff -u -p -r1.156 window.c
--- window.c    19 Jan 2016 15:59:12 -0000      1.156
+++ window.c    12 Feb 2016 12:17:19 -0000
@@ -1085,6 +1085,8 @@ window_pane_set_mode(struct window_pane
        if ((s = wp->mode->init(wp)) != NULL)
                wp->screen = s;
        wp->flags |= (PANE_REDRAW|PANE_CHANGED);
+
+       server_status_window(wp->window);
        return (0);
 }

@@ -1099,6 +1101,8 @@ window_pane_reset_mode(struct window_pan

        wp->screen = &wp->base;
        wp->flags |= (PANE_REDRAW|PANE_CHANGED);
+
+       server_status_window(wp->window);
 }

 void

**Comment by nicm** [comment]
Will be applied later.
