### ISSUE TITLE
tmux AppImage using github action

### ISSUE THREAD

**Issue by menash134** [tmux/tmux#3000]
Hi,
Could you please add a github action for generating appImage ? It is super easy and can be automated without extra efforts.

You might be able to automate the process easily using GH Actions: https://dev.to/tyu1996/automate-stuffs-with-github-actions-on-publishing-appimage-4pl1

https://appimage-builder.readthedocs.io/en/latest/hosted-services/github-actions.html

Please do that and it would be helpful.

Thanks

**Comment by nicm** [comment]
You can use @nelsonenzo's AppImage packages here: https://github.com/nelsonenzo/tmux-appimage/releases

**Comment by menash134** [comment]
But he stopped generating. He generated lastly for 3.1b and somebody raised an issue there at 15th july 2021 to generate the new App image for tmux but he hasn't respond.

**Comment by menash134** [comment]
but way to go would be github actions.. as it is easier and automated

**Comment by nicm** [comment]
OK maybe you should generate them?

**Comment by menash134** [comment]
I cannot add workflow to the repository which I don't own. 
So I can fork it, merge it time to time and do it. Hence it is not simple.

**Comment by nicm** [comment]
You can build them and provide the packages in your own repo, or you can come up with the necessary instructions and scripts for me to set it up.

**Comment by nicm** [comment]
Someone started working on this here https://github.com/tmux/tmux/pull/2465 perhaps you can use their work for inspiration.
