### ISSUE TITLE
Feature request: configure whether it's allowed to drop passthrough sequences

### ISSUE THREAD

**Issue by sergei-grechanik** [tmux/tmux#3001]
Currently tmux may discard data sent using the passthrough sequence (Ptmux) if the client is slow. This makes this method of sending data to the terminal unreliable, especially when there is a lot of data (like images). It would be nice to make a configuration option to disable this behavior or to adjust timeout/buffer size/etc.

**Comment by nicm** [comment]
Does this help?
~~~~
--- a/tty.c
+++ b/tty.c
@@ -2096,6 +2096,7 @@ void
 tty_cmd_rawstring(struct tty *tty, const struct tty_ctx *ctx)
 {
        tty_add(tty, ctx->ptr, ctx->num);
+       tty->client->redraw = ctx->num;
        tty_invalidate(tty);
 }

**Comment by sergei-grechanik** [comment]
No, it doesn't.

**Comment by nicm** [comment]
Try with += instead of =.

**Comment by sergei-grechanik** [comment]
Still doesn't, although it's better, and it usually breaks at about ~900KB instead of ~20KB (can transmit a 500KB image most of the time now, but can't transmit a 1.1MB image).

**Comment by nicm** [comment]
Please try this change instead: [x.diff.txt](https://github.com/tmux/tmux/files/7675425/x.diff.txt)

**Comment by sergei-grechanik** [comment]
It works with this patch, thanks!

btw, what do you think about allowing sending passthrough sequences from inactive panes? It used to work, but the behavior changed at some point (probably in 9605b080f6c942ff2e51a2ba538cccc91c91c161).

**Comment by nicm** [comment]
Applied now, thanks!

I don't mind if we send passthrough from inactive panes, do you want to fix it?

**Comment by sergei-grechanik** [comment]
Yeah, I can take a look into this.

**Comment by sergei-grechanik** [comment]
I actually meant _invisible_ panes, not just inactive panes (sending pass-through sequence from inactive but visible panes already works). So, allowing this is very questionable since passthrough sequences sent from hidden windows may affect rendering of the currently active window, if used for something like custom attributes or image display. Something like data transfer should be ok though, unless the terminal wants to respond, in which case it will respond to the wrong pane (sending from visible but inactive panes is also problematic for this case). So, now I tend to think that this might be a bad idea, but nevertheless here is the patch: 
[tmux-passthrough-from-invisible.patch.txt](https://github.com/tmux/tmux/files/7742737/tmux-passthrough-from-invisible.patch.txt) and the [branch](https://github.com/sergei-grechanik/tmux/tree/passthrough-from-invisible)

**Comment by nicm** [comment]
Yes, I don't think passthrough from invisible windows is a good idea, it would be very confusing, not to mention security concerns. I think if you want that you should maintain it privately :-).
