### ISSUE TITLE
incorrect character width for c1 control characters

### ISSUE THREAD

**Issue by doy** [tmux/tmux#3002]
### Issue description

tmux appears to believe that characters such as `U+0099` have a width of 1, but as far as i can tell, this is incorrect (they should have a width of 0). this leads to display corruption if these characters are printed - for instance, you can reproduce this by running `echo -e 'foo\xc2\x99bar'` and moving the copy mode selection around. i can reproduce this on latest git (commit 10b3cd17), under both alacritty and xterm.

running this code:

```c
#include <utf8proc.h>
#include <stdio.h>
#define _XOPEN_SOURCE
#include <wchar.h>

int main(int argc, char *argv[])
{
    printf("%d\n", utf8proc_charwidth(0x99));
    printf("%d\n", wcwidth(0x99));
}
```
produces this output:
```
0
-1
```
on my system, so i don't think this is an underlying library issue, although i'm not entirely sure how tmux uses this information. looking through the logs, i see this:
```
1638778097.748305 UTF-8 \302\231, wcwidth() -1
1638778097.748312 input_top_bit_set 2 '\302\231' (width 1)
```
which sounds like it's getting -1 from wcwidth, but using a width of 1 anyway? not at all familiar with the tmux codebase though.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  * `tmux next-3.4`
* Platform (`uname -sp`).
  * `Linux unknown` (arch linux)
* $TERM inside and outside of tmux (`echo $TERM`).
  * inside tmux is `screen`, outside is either `alacritty-direct` under alacritty or `xterm` under xterm
* Logs from tmux (`tmux kill-server; tmux -vv new`).
  * attached
[tmux-client-2741948.log](https://github.com/tmux/tmux/files/7659122/tmux-client-2741948.log)
[tmux-out-2741950.log](https://github.com/tmux/tmux/files/7659123/tmux-out-2741950.log)
[tmux-server-2741950.log](https://github.com/tmux/tmux/files/7659124/tmux-server-2741950.log)

**Comment by nicm** [comment]
We use width 1 when wcwidth fails as best effort. Seems like you can just use utf8proc though if you want.

**Comment by doy** [comment]
is 1 actually a reasonable default here? the documentation for `wcwidth` says that it only returns -1 for non-printable characters, which makes it sound like 0 would be a more appropriate default in this case. alternately (if the documentation isn't quite accurate), it seems like tmux should be able to know that characters in the `Control` category are non-printing, and should never have a non-zero width? that feels like a different case from width data being missing from new characters or whatever.

my operating system package doesn't use utf8proc, and i'm not super excited about maintaining my own separate build/installation/:

**Comment by nicm** [comment]
Most characters are width 1 so it seems the most sensible default if wcwidth doesn't know. Building this kind of character information into tmux itself defeats the purpose of using an external library. And if tmux should know, why shouldn't libc know as well?

**Comment by nicm** [comment]
In theory, tmux should discard these characters entirely. But this means that on platforms with poor or out-of-date libc (macOS, or commonly others when a new Unicode standard appears), tmux will discard useful characters.

We now require utf8proc on macOS but I really don't see that this is pressing enough to change for all platforms.

**Comment by nicm** [comment]
Saying that, it doesn't seem that onerous to discard C0 and C1. Perhaps you'd like to cook up a diff?

**Comment by nicm** [comment]
Or maybe the `#ifdef` in `utf8_width` should include Linux? Not sure if that will hurt anyone...
