### ISSUE TITLE
How to filter control characters from tmux pipe-pane

### ISSUE THREAD

**Issue by sriramkandukuri** [tmux/tmux#3005]
### Issue description

I am using minicom in one pane and piping the output in another pane to do selective logging.

I am using below command

```sh
tmux pipep -o -t temp:0.1 "cat >> /tmp/temp.txt"
```

when I cat file it looks good, but when I edit using vi some special characters are appearing.

![image](https://user-images.githubusercontent.com/5476956/145074138-270f2742-0d4e-4845-8875-e04e8f2e0906.png)

Is there a way to trim all such unwanted characters?

Thanks,
Sriram.K

**Comment by bew** [comment]
You could use the program `ansifilter`, which by default removes all escape sequences.
(repo: https://gitlab.com/saalen/ansifilter)
It should be available on all major package managers

**Comment by sriramkandukuri** [comment]
any solution with sed ?

**Comment by sriramkandukuri** [comment]
even with ansifilter these are not removed, looks like these are minicom special characters.

**Comment by nicm** [comment]
No these are standard cursor movement escape sequences, there should be some program that will remove them or you could try with sed.

**Comment by sriramkandukuri** [comment]
Hi

below steps working fine to remove the unwanted characters
```sh
tmux pipep -o -t temp:0.1 "cat >> /tmp/temp.txt
cat /tmp/temp.txt | sed $'s,[\x01-\x1F\x7F][[0-9;]*[a-zA-Z],,g'
```

But is there a way to do it directly in tmux shell-command?

I am trying below thing but no output in output file

```sh
tmux pipep -o -t temp:0.1 "exec cat -| sed $'s,[\x01-\x1F\x7F][[0-9;]*[a-zA-Z],,g'  >> /tmp/temp.txt"
```
Any suggestions would be very much appreciated.

Thanks,
Sriram.K

**Comment by nicm** [comment]
You need to get the escaping right. It'd probably be easier just to put the whole command in a script and run it with `pipe-pane`.

**Comment by sriramkandukuri** [comment]
The escaping is correct, but there are two issues here.

sed by default runs in buffered mode so untill it gets the full buffer its not processing and dumping to file.
This can be foxed bu using -u option for sed.

Another one is sed dont process line untill newline character is seen. so i am not getting lastline in output file.

So used cat command only in pipe-pane.

When ever i want log, I am using sed on that file in another command.

So practically if pipe-pane used with cat and sed we miss lastline.
