### ISSUE TITLE
Cs / Cr - why is Cs expecting a color name instead of reusing existing schemes?

### ISSUE THREAD

**Issue by christianparpart** [tmux/tmux#3006]
```
Cs, Cr  Set the cursor colour.  The first takes a single string
             argument and is used to set the colour; the second takes no
             arguments and restores the default cursor colour.  If set, a
             sequence such as this may be used to change the cursor
             colour from inside tmux:

                   $ printf '\033]12;red\033\\'
```

This is an excerpt from the man page. I could not find out why this is expecting a color string (name?) such as "red" (as used in the example). 

This spec is sadly not saying what color names should be supported or if "string" means also numbers, such as "34". I'm just asking because I feel a little dazed and confused. 

I think it might be worth extending the man page with the outcoming details of this ticket. :)

Many thanks,
Christian.

**Comment by nicm** [comment]
This escape sequence is an xterm extension so (if your tmux is new enough) it accepts an X11 colour name or (older tmux as well) something like `rgb:ff/ff/ff`. See XParseColor(3) or https://en.m.wikipedia.org/wiki/X11_color_names.

**Comment by christianparpart** [comment]
Aaaaah. That was THIS one. Many thanks for the info. Do you think that makes sense to be added to the man-page?

Do you happen to know who else is implementing it?

**Comment by nicm** [comment]
xterm has it, see https://invisible-island.net/xterm/ctlseqs/ctlseqs.html,
I don't know who else.

It might be worth a note in the man page.

**Comment by nicm** [comment]
I added a line to the man page. Thanks!
