### ISSUE TITLE
Server exiting unexpectedly in 3.3-rc with tmux.conf that worked in 3.2

### ISSUE THREAD

**Issue by FractalBoy** [tmux/tmux#3007]
### Issue description

I use a kind of convoluted system to copy text from tmux on my Linux machine into my local Windows desktop. I have a server running on my Windows desktop, listening, and when it receives data, it places it on my clipboard.

I have my tmux.conf set up so that mouse mode is on and if I select or double click text, it pipes it to a Perl script that sends to the data to my desktop.

I recently upgraded to 3.3-rc and the tmux server is now crashing when I double click text. It does not crash when I select text by dragging.

This is the minimal reproducible tmux.conf. I have replaced my command to use my Perl script with a simple call to `cat`. This causes a crash as well.

```
set -g mouse on

%hidden clipboard_command='cat'

bind -n DoubleClick1Pane \
    select-pane \; \
    copy-mode -M \; \
    send-keys -X select-word \; \
    run -d 0.04 \; \
    send-keys -X copy-pipe-and-cancel "#{clipboard_command}"
```

This tmux.conf works fine:

```
set -g mouse on

%hidden clipboard_command='cat'

bind -n MouseDown1Pane \
    select-pane \; \
    set -g @mouse_triggered_copy_mode 1 \; \

bind -T copy-mode-vi MouseDragEnd1Pane \
    send-keys -X copy-pipe "#{clipboard_command}" \; \
    if-shell -Ft= "#{@mouse_triggered_copy_mode}" 'send-keys -X cancel' 'send-keys -X clear-selection' \; \
    set -g @mouse_triggered_copy_mode 0 
```

Steps to reproduce:

1. tmux -ftmux.conf new (using the first tmux.conf above)
2. Double click text in terminal
3. tmux crashes, looks something like this, seems to be stuck in raw mode:
```
[mreisner@vm-mreisner[server exited unexpectedly]
                                                 [mreisner@vm-mreisner ~]$
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.3-rc

* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
Outside: xterm-256color
Inside: tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-2549644.log](https://github.com/tmux/tmux/files/7695877/tmux-client-2549644.log)
[tmux-out-2549646.log](https://github.com/tmux/tmux/files/7695878/tmux-out-2549646.log)
[tmux-server-2549646.log](https://github.com/tmux/tmux/files/7695879/tmux-server-2549646.log)

**Comment by nicm** [comment]
Does this still happen if you build from master?

**Comment by FractalBoy** [comment]
Haven't tried, let me check.

**Comment by FractalBoy** [comment]
Seems to be fixed in master!

**Comment by FractalBoy** [comment]
Was it an issue with `if-shell`? Another thing in my tmux.conf that used `if-shell` also caused a crash, but I didn't need it anyway, so I just removed it.

**Comment by nicm** [comment]
Great. I don't know what the problem was, the last rc was months ago, probably time for another one.

**Comment by systemmonkey42** [comment]
> I use a kind of convoluted system to copy text from tmux on my Linux machine into my local Windows desktop. I have a server running on my Windows desktop, listening, and when it receives data, it places it on my clipboard.

Can you elaborate how you transfer the clipboard data?
I currently use X clipboard but the integration is slow (over 100ms to set and retrieve data from the primary selection) and spotty in applications.

Does the. Clipboard exchange in both directions?
