### ISSUE TITLE
Set window name to top-left pane

### ISSUE THREAD

**Issue by nml11c** [tmux/tmux#3008]
I'm trying to name my window based on the path of the top left pane. This is what I've tried:
```
set-option -g automatic-rename on
set-option -g automatic-rename-format "#(tmux display -p -t '{top-left}' '#{b:pane_current_path}')"
```

Unfortunately, it doesn't work as expected, looks like it set the name of window to the current pane instead. 
Also, if I run `tmux display -p -t '{top-left}' '#{b:pane_current_path}'` from the shell, it works as expected, showing the path of the top-left pane.

* tmux version: `3.2a`
* Platform: `Darwin i386`
* $TERM inside and outside of tmux:  `xterm-256color`

**Comment by nicm** [comment]
You could  try `#{s/ .*//:#{P:#{pane_current_path} }}`.

**Comment by nml11c** [comment]
Yep, that was it. Thank you!
