### ISSUE TITLE
Wrong colors in tmux, unless launched with -2 option

### ISSUE THREAD

**Issue by adrianmihalko** [tmux/tmux#3009]
I am trying to find solution to this problem for days now, but I have no idea what cause this. The colors in tmux are totally wrong, unless I launch with -2 option. The $TERM is the same in both cases.

Let me demonstrate.

Default terminal (**without tmux**):

<img width="1018" alt="Screenshot 2021-12-15 at 00 15 26" src="https://user-images.githubusercontent.com/733361/146095140-91f0877a-ef87-4b06-a4aa-3b5f6ae600c8.png">

Tmux launched with -2 option (**$tmux -2**):

<img width="969" alt="Screenshot 2021-12-15 at 00 16 31" src="https://user-images.githubusercontent.com/733361/146095247-06078bd5-a204-401c-8f18-96ec4e9cb72e.png">

Tmux launched normally (**$tmux**):

<img width="987" alt="Screenshot 2021-12-15 at 00 15 57" src="https://user-images.githubusercontent.com/733361/146095271-d3154870-8b38-48e9-a3ae-25ffae217e05.png">

As you can see colors are totally wrong in the last case. Any ideas what cause this?

- tmux version (tmux -V).
tmux 3.3-rc
- Platform (uname -sp).
Linux x86_64
- $TERM inside and outside of tmux (echo $TERM).
screen-256color

**Comment by nicm** [comment]
`xterm-color` is not a 256-colour `TERM`, try `xterm-256color`.

**Comment by adrianmihalko** [comment]
@nicm "Default terminal (**without tmux**)"  - Ubuntu's default terminal xterm-color and 256 color works here fine. 

The relevant screenshots are the second (`$tmux -2`) and third (`$tmux`).

**Comment by nicm** [comment]
`TERM` outside tmux matters.
