### ISSUE TITLE
Hide tab count in bar

### ISSUE THREAD

**Issue by harrysolovay** [tmux/tmux#3010]
Apologies for the seemingly-basic question. Searched for a while and could not find an answer.

How can I hide this fellow (the count)?

<img width="52" alt="Screen Shot 2021-12-18 at 7 52 59 AM" src="https://user-images.githubusercontent.com/4893548/146641820-8f26760e-3c4d-4b52-a015-e80bfc3905f2.png">

**Comment by bew** [comment]
That's not the tab count, it's the default session name, try to rename it with `Ctrl-b` then `$`

**Comment by harrysolovay** [comment]
Ah yes! Thank you!

Went with `set -g status-left ""` in my `.tmux.conf` –– that did the trick.
