### ISSUE TITLE
why does color look like that in tmux

### ISSUE THREAD

**Issue by rzksobhy78** [tmux/tmux#3011]
![Sat Dec 18 17:58:37 EET 2021](https://user-images.githubusercontent.com/94202082/146647486-4b180042-1656-463a-a0ca-d297b0adea57.png)
what is the problem with tmux colors I used
`set -g default-terminal "screen-256color"` in my .tmux.conf
but still doesn't work
it suppose to look like that
![Sat Dec 18 18:00:26 EET 2021](https://user-images.githubusercontent.com/94202082/146647535-a4b0f985-8e15-4f4e-9aad-0251ed6a4b57.png)

**Comment by nicm** [comment]
What is TERM outside tmux?

**Comment by rzksobhy78** [comment]
what do you mean ?

**Comment by nicm** [comment]
what does "echo $TERM" show before you start tmux?

**Comment by rzksobhy78** [comment]
alacritty

**Comment by nicm** [comment]
Show server log from tmux please.

**Comment by rzksobhy78** [comment]
nah its fine I already fixed it thanks
