### ISSUE TITLE
The TMUX session closes automatically after 15 minutes

### ISSUE THREAD

**Issue by oldfive-wang** [tmux/tmux#3013]
First of all, I'm sorry that due to my limited English level, part of the text is translated by computer

system: Linux x86_64 ubuntu18
software: tmux 2.6
TERM: xterm

On this computer, after the TMUx session is opened, the TMUX session is closed when there is no internal command running after 15 minutes (testing foreground and background)

The following is the system log

#
1639996944.926467 cmdq_next <global>: empty
1639996944.926540 @tmux_session active pane not changed
1639997004.312522 %0 has 43 bytes
1639997004.312624 @tmux_session alerts timer reset 0
1639997004.312664 screen_write_start: size 144x29, pane %0
1639997004.312698 input_parse: %0 ground, 43 bytes: \atimed out waiting for input: auto-logout\r\n
1639997004.312724 input_c0_dispatch: '\a'
1639997004.312751 @tmux_session alerts timer reset 0
1639997004.312777 @tmux_session alerts flags added 0x1
1639997004.312803 window_add_ref: @tmux_session alerts_queue, now 2
1639997004.312826 alerts check queued (by @tmux_session)
1639997004.312864 screen_write_collect_end: 40 timed out waiting for input: auto-logout (at 26,3)
1639997004.312895 input_c0_dispatch: '\r'
1639997004.312954 input_c0_dispatch: '\n'
1639997004.312981 screen_write_linefeed: at 0,3 (region 0-28)
1639997004.313007 screen_write_collect_flush: flushed 1 items (40 bytes)
1639997004.313031 screen_write_stop: 40 cells (40 written, 0 skipped)
1639997004.313064 cmd_find_from_winlink: s=$0
1639997004.313090 cmd_find_from_winlink: wl=0 1 w=@tmux_session bash
1639997004.313110 cmd_find_from_winlink: wp=%0
1639997004.313130 cmd_find_from_winlink: idx=none
1639997004.313155 session_add_ref: 0 notify_add, now 2
1639997004.313178 window_add_ref: @tmux_session notify_add, now 3
1639997004.313200 session_add_ref: 0 notify_add, now 3
1639997004.313227 @tmux_session alerts check, alerts 0x1
1639997004.313250 window_remove_ref: @tmux_session alerts_callback, now 2
1639997004.313302 cmdq_next <global>: enter
1639997004.313329 cmdq_next <global>: callback[notify_callback] (1), flags 0
1639997004.313351 notify_callback: alert-bell
1639997004.313378 session_remove_ref: 0 notify_callback, now 2
1639997004.313401 window_remove_ref: @tmux_session notify_callback, now 1
1639997004.313422 session_remove_ref: 0 notify_callback, now 1
1639997004.313444 cmdq_next <global>: exit (empty)
1639997004.313465 cmdq_next <global>: empty
1639997004.313491 @tmux_session active pane changed
1639997004.313691 format '#{pane_current_command}' -> 'bash'
1639997004.313734 format '' -> ''
1639997004.313764 format '#{?pane_in_mode,[tmux],#{pane_current_command}}#{?pane_dead,[dead],}' -> 'bash'
1639997004.313812 @tmux_session name not changed (still bash)
1639997004.313914 %0 error
1639997004.317294 cmd_find_from_window: s=$0
1639997004.317372 cmd_find_from_window: wl=0 1 w=@tmux_session bash
1639997004.317399 cmd_find_from_window: wp=%0
1639997004.317425 cmd_find_from_window: idx=0
1639997004.317454 cmd_find_from_pane: s=$0
1639997004.317478 cmd_find_from_pane: wl=0 1 w=@tmux_session bash
1639997004.317499 cmd_find_from_pane: wp=%0
1639997004.317520 cmd_find_from_pane: idx=0
1639997004.317551 session_add_ref: 0 notify_add, now 2
1639997004.317595 cmd_find_from_window: s=$0
1639997004.317624 cmd_find_from_window: wl=0 1 w=@tmux_session bash
1639997004.317647 cmd_find_from_window: wp=%0
1639997004.317672 cmd_find_from_window: idx=0
1639997004.317701 window_add_ref: @tmux_session notify_add, now 2
1639997004.317729 session_add_ref: 0 notify_add, now 3
1639997004.317754 window_lost_pane: @tmux_session pane %0
1639997004.317817 cmd_find_from_session_window: s=$0
1639997004.317849 cmd_find_from_session_window: wl=0 1 w=@tmux_session bash
1639997004.317875 cmd_find_from_session_window: wp=none
1639997004.317896 cmd_find_from_session_window: idx=0
1639997004.317919 session_add_ref: 0 notify_add, now 4
1639997004.317941 window_add_ref: @tmux_session notify_add, now 3
1639997004.317963 session_add_ref: 0 notify_add, now 5
1639997004.317994 window_remove_ref: @tmux_session winlink_remove, now 2
1639997004.318026 session 0 destroyed (session_detach)
1639997004.318053 session_add_ref: 0 notify_add, now 6
1639997004.318086 session_remove_ref: 0 session_destroy, now 5
1639997004.318139 server_signal: Child exited
1639997004.318284 cmdq_next <global>: enter
1639997004.318330 cmdq_next <global>: callback[notify_callback] (1), flags 0
1639997004.318403 notify_callback: pane-exited
1639997004.318435 session_remove_ref: 0 notify_callback, now 4
1639997004.318462 cmdq_next <global>: callback[notify_callback] (1), flags 0
1639997004.318484 notify_callback: window-layout-changed
1639997004.318510 window_remove_ref: @tmux_session notify_callback, now 1
1639997004.318541 session_remove_ref: 0 notify_callback, now 3
1639997004.318568 cmdq_next <global>: callback[notify_callback] (1), flags 0
1639997004.318612 notify_callback: window-unlinked
1639997004.318726 session_remove_ref: 0 notify_callback, now 2
1639997004.318752 window_remove_ref: @tmux_session notify_callback, now 0
1639997004.318772 window @tmux_session destroyed (0 references)
1639997004.318795 session_remove_ref: 0 notify_callback, now 1
1639997004.318825 cmdq_next <global>: callback[notify_callback] (1), flags 0
1639997004.318845 notify_callback: session-closed
1639997004.318868 session_remove_ref: 0 notify_callback, now 0
1639997004.318897 cmdq_next <global>: exit (empty)
1639997004.318922 cmdq_next <global>: empty
1639997004.318987 server loop exit
#
Looking forward to your reply

**Comment by oldfive-wang** [comment]
During the test, I found that `$TMOUT` is 900 on this computer. Does this value affect the connection time of TNUX

**Comment by nicm** [comment]
`TMOUT` will make your shells exit and if all the programs inside tmux are shells and they all exit, tmux will exit.

**Comment by oldfive-wang** [comment]
Thank you for your reply and solving my doubts
