### ISSUE TITLE
tmux session list (prefix+s) missing border colors

### ISSUE THREAD

**Issue by ZeekDaGeek** [tmux/tmux#3014]
### Issue description

Windows Terminal is missing the color for borders. This probably happens as a result of Windows Terminal taking no color assigned as invisible instead of ForegroundColor, but maybe there something that can be set in `tmux.conf` to change the color of the borders?

Windows Terminal screenshot:
![3FD1F](https://user-images.githubusercontent.com/1709288/146898701-fbce51da-8c30-4a8a-bdd9-7e4cf869d3f1.png)

wsltty screenshot (desired result):
![kKaP7](https://user-images.githubusercontent.com/1709288/146898890-33a7f8cc-0442-4388-95a4-e9e7bc0f837d.png)

### Required information

Please provide the following information:

* tmux version: **3.2a**
* Platform: wsl 2 - debian + windows 10
* $TERM inside and outside of tmux:
    - inside: screen-256color (not forced in tmux.conf)
    - outside: xterm-256color

**Comment by nicm** [comment]
More likely it does not correctly support UTF-8 line drawing or ACS characters. Try this in .tmux.conf:
~~~~
set -as terminal-overrides ",*:U8=0"
~~~~
Then restart tmux completely (`tmux kill-server`).

If that doesn't help try `U8=1`.

**Comment by ZeekDaGeek** [comment]
Neither of those two options seemed to work, I attempted to download this UTF-8 demo (https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt) and when running cat it appears to display correctly, even specially the box characters:

![image](https://user-images.githubusercontent.com/1709288/146904735-2ed11db7-df5c-4e11-b58b-9e54f4256047.png)

Copying the empty space around the text it seems to copy the special character, eg: ` [1] local (sort: index) ────`

However, copying them back into the terminal they're invisible again.
![KTjDQ](https://user-images.githubusercontent.com/1709288/146905450-21774541-a3d6-46d0-9435-b1ef761cd504.png)

**Comment by ZeekDaGeek** [comment]
Oh wait, apparently I'm bad at spot the difference. Looking back at the UTF-8 demo it appears that the thick borders are drawing, but the thin borders are invisible.

Desired output would be:
![WmThR](https://user-images.githubusercontent.com/1709288/146905950-b15bd5d1-90d0-4f5a-9f8f-d53899d5ebb2.png)

All my problems come from font rendering differences in the two programs, one size up and all of the invisible lines are visible.
![rQ00o](https://user-images.githubusercontent.com/1709288/146906188-a10276f8-b38a-437a-94fa-56afbf2fdc67.png)


I feel embarrassed that I submitted this issue, but hopefully it helps someone down the line.

Solution: Consolas 8pt != Consolas 8pt because magic.

**Comment by nicm** [comment]
Seems like a bug in the terminal TBH, lines should really be visible at all font sizes.

**Comment by ZeekDaGeek** [comment]
I'll report the issue on the Windows Terminal side.
