### ISSUE TITLE
When using the cat command on tmux window, the contents of the file are lost

### ISSUE THREAD

**Issue by MF-ReStart** [tmux/tmux#3016]
### Issue description

After I use tmux, when I use the cat command in the tmux window to view a large file, the content is lost and not all the content of the file is printed on my screen, but when I don't use tmux, I can view all the content of the file normally.

### Required information
This is how I can read the contents of the file using the cat command when I am not using tmux and there is no problem
![image](https://user-images.githubusercontent.com/50358485/147345481-4d2db0e9-5fd8-4024-89a8-f6e8371bb316.png)

But when I use it in the tmux window, it changes and the contents of the file are incomplete
![image](https://user-images.githubusercontent.com/50358485/147345519-d6dda6f3-91cc-47c2-bb2f-b4ba495cc6e7.png)

This is the same system and the same file, the environment is the same, I use tmux window will have the problem of content loss

* tmux version: tmux 3.0a
* Platform: Ubuntu 20.04.3 LTS
* $TERM: internal and external are linux
* Logs from tmux: There are no logs for error reporting

**Comment by nicm** [comment]
Does the text appear when you use copy mode (`C-b [`)?

**Comment by MF-ReStart** [comment]
我使用(C-b [)时，我复制然后粘贴到文件中，内容也是丢失的。

**Comment by MF-ReStart** [comment]
> 使用复印模式 ( `C-b [`)时是否出现文本？

Hello, when I use C-b [to enter copy mode, the content is displayed normally, but I scroll back up in my terminal is lost, why is this?

**Comment by MF-ReStart** [comment]
> > 使用复印模式 ( `C-b [`)时是否出现文本？
> 
> Hello, when I use C-b [to enter copy mode, the content is displayed normally, but I scroll back up in my terminal is lost, why is this?

I am using iterm2 terminal software and have Unlimited scrollback enabled

**Comment by nicm** [comment]
tmux does not attempt to keep the terminal scrollback consistent, if output will not affect the visible pane then it is not necessarily sent to the terminal. You will need to either use copy mode or use iTerm2's tmux integration.

**Comment by MF-ReStart** [comment]
Will this be possible in the future? What should I do if I use iterm2's tmux integration?

**Comment by nicm** [comment]
No, tmux does not attempt to preserve the terminal scrollback because it would be a lot of effort, it would make performance worse and it is completely incompatible with two of tmux's main features (panes and detach/reattach). tmux provides its own per-pane scrollback accessed using copy mode, see https://github.com/tmux/tmux/wiki/Getting-Started#copy-and-paste. Copy mode is highly configurable.

You also maye like to try iTerm2's tmux integration which makes tmux look like an iTerm2 window including its scrollback, but I don't really know how to use it, you will need to take a look at the iTerm2 help.

**Comment by MF-ReStart** [comment]
I rolled back in the terminal to view the file intranet display is not normal, and then use C-b [into copy mode, the contents of the file looks normal, but I selected the text after C-w, I vim a 000 file, use C-b ] paste the contents of my copy, but get and I copy is not the same, is there a problem with my operation?

Here is the link to my operation video, sorry, this video is too big I do not know how to upload to github

https://hercules-gitbook-image.oss-cn-shenzhen.aliyuncs.com/bug/2021-12-27-18.20.01.mov

**Comment by nicm** [comment]
If you do `tmux showb|less` or do `C-b =` then `e`, does the text look OK? If so it seems like a vim problem.

**Comment by MF-ReStart** [comment]
I've been using tmux painfully and happily for a long time. tmux's separate rollback buffer and the fact that it's not shared with the system pasteboard are two reasons why I almost gave up on tmux. the terminal rollbacks I see are not 100% correct, which breaks me, so what's the point of it all? tmux's copy mode configuration and configuration of mouse support seem to work for the average person Not so friendly, I know it works fine with copy mode, but it's too much of a hassle. Now I'm very happy with iterm2's tmux integration and it's working well, my problem is solved, thank you!
