### ISSUE TITLE
new feature, is there a short key to jump to windows listed by subcommand list-windows

### ISSUE THREAD

**Issue by ask-github** [tmux/tmux#3017]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

use arrow key need many time press to move 

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux next-3.3
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
C-b w

**Comment by ask-github** [comment]
i find command choose-tree -Zs can use 1 2 3 to jmp window
but after tenth window, need use meta a, meta b meta c to jmp. meta a, b, c is hard to press
is there a method that use a b c to jmp tenth window

**Comment by nicm** [comment]
No, use C-b ' or use the meta keys in C-b w or bind your own keys.

**Comment by ask-github** [comment]
> 

in the window list, it is easy to jmp 1, 2, 3, windows. but it is hard to jmp meta a, meta b, windows

is there a methon that jmp meta a meta b window easyly the use a key, like a, b, c, d

**Comment by nicm** [comment]
You can try this https://github.com/tmux/tmux/wiki/Recipes#change-shortcut-keys-in-tree-mode

**Comment by ask-github** [comment]
> can try

it is work very good. thanks very very much.

i am really appreciate with u.
