### ISSUE TITLE
request: in display-pane, option to use [a-z] as indicator and keys instead of [0-9] 

### ISSUE THREAD

**Issue by damnskippy** [tmux/tmux#3018]
For display-pane indicators it might be slightly more easier to type alphabets without leaving the home row than to type numbers.  Currently this does not seem configurable (hope I didn't overlook) and seems hard coded to [0-9].  Wonder if there could be an optional argument to display-pane to use a-z, given 0-9 has to be retained to be backward compatible.  Also for those who might create more than 10 panes in one window, would the hotkeys to choose the pane work beyond 9?
Thank you.

**Comment by nicm** [comment]
I don't want to add more large characters and I don't really think this level of customization is necessary, I think more than 10 panes in a window will be pretty unusual. If you have more than 10 routinely you can bind your own keys to select them.

**Comment by damnskippy** [comment]
Fully understood @nicm.  Indeed I currently have a script that helps me with this by listing panes and let me choose/jump, but I quite like and miss the visual feedback provided by display-panes that overlays the large indicator over the pane.  I personally almost never create 10+ panes, but in just one of my use cases routinely get up to 6/7 per window in order to be able to keep an eye on several things at once.  But you're right this perhaps verges on obsessive in terms of configuration/customization.

**Comment by damnskippy** [comment]
Just happened to see in the code that there is already support to handle >10 panes, the indicator switches a-z beyond 9.
Seems if I wanted to I can change it to move this up in place of 0-9 perhaps.  Thought I'd note here for the sake of completeness.  
https://github.com/tmux/tmux/blob/c6375a0d4003d1008bb64e96e9c0c4433e4a5d13/cmd-display-panes.c#L142
