### ISSUE TITLE
Unable to change layout after killing the selected-pane

### ISSUE THREAD

**Issue by jody-frankowski** [tmux/tmux#302]
Hi, 
It seems like I can't select a layout after having killed the pane that was executing the tmux commands.
This is the code I'm trying to make work:

```sh
pssh () {
for host in $* ; do
        tmux split-window -h "zsh -c \"ssh ${host}\""
done
    tmux set-window-option synchronize-panes on
    tmux kill-pane -t 0
    tmux select-layout -t tiled
}
```
Note that the last select-layout doesn't behave as expected.
I have also tried to select another pane before changing the layout, but with no success.

By the way I also need to activate synchronize-panes before killing the first pane (but maybe it deserves an issue of its own).

**Comment by nicm** [comment]
For a start, the -t flag to select-layout is wrong here.

But if you kill a pane that is running a script, then the script will be
killed and you can't guarantee that any later commands in the script
will run. They might, but it is not guaranteed.

You probably need to do something like:

P=$(tmux breakp -P -t:.0)
tmux selectl tiled
tmux killp -t$P

**Comment by jody-frankowski** [comment]
Yes, it actually was `tmux select-layout -t :$window tiled`, but i had removed the $window variable for the sake of simplicity.

I'm getting this error with break-pane
```
+pssh:28> pane=+pssh:28> tmux break-pane -P -t:.0
can't specify pane here
```

**Comment by nicm** [comment]
Oh it should be -s.

**Comment by jody-frankowski** [comment]
Ok, I managed to make break-pane work with `tmux breakp -P -s 0`, and I understand that the goal is to extract the pane, so it can continue its execution and not interfer with the select-layout command.

I'm able to make it work with this (notice the select-layout command needs the window target):
``` sh
window=$(tmux display-message -p '#I')

for host in $* ; do
    tmux split-window "zsh -c \"ssh ${host}\""
done

tmux set-window-option synchronize-panes on
pane=$(tmux break-pane -P -s 0)
tmux select-layout -t :$window tiled
tmux kill-pane -t ${pane}
```

Thank you very much.
