### ISSUE TITLE
[RFE] Support deep tree hierarchy

### ISSUE THREAD

**Issue by didib** [tmux/tmux#3021]
It would be nice to allow creating windows (not panes) that will appear, inside "choose-tree", to be sub-windows of existing ones. This would allow grouping windows per task/function more easily. A next item can be to add key bindings for collapsing/un-collapsing subtrees inside "choose-tree".

As to how it might look like/function, consider e.g. the "Tree Style Tab" extension [1] for firefox.

[1] https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

**Comment by nicm** [comment]
You can group windows by linking them to sessions.
