### ISSUE TITLE
[feature}: make tmux stop write to client pts temporary

### ISSUE THREAD

**Issue by ask-github** [tmux/tmux#3027]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* tmux 3.2a
* Platform (`uname -sp`).
* Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

i find tmux will write to client pts every 60s, even if the console has no output. maybe it is update the status line include the time stamp in status-right zone

i want to make tmux stop write to client pts temporary. and then make it continue to write to client pts. because of i want to write something to console client pts. avoid to mess with tmux output to client pts

is there a mehod to accompish it?

thanks

**Comment by nicm** [comment]
Turn status off?

**Comment by ask-github** [comment]
thanks. let me try

**Comment by ask-github** [comment]
> Turn status off?

this is not a good method.
set status off also will write client pts. and it is not a sync command.

means command tmux set status off return. the tmux is not write client pts finished.
tmux set -g status off
doing something
tmux set -g status on

doing something and tmux update status line running parellel

**Comment by nicm** [comment]
But that wasn't what you asked for, you asked for tmux not to update the pty every 60 seconds, and turning the status off will do that.

The way to stop tmux writing to the pty at all is to detach it.

**Comment by ask-github** [comment]
sorry for late. in the normal Scenario. i use tmux status line to switch window
in a new case. a app need write some binary data to the pts which tmux is running.
so i want the tmux stop running temporary to avoid tmux write data to pts parellel with the app

**Comment by ask-github** [comment]
now. i use kill -sigstop to tmux server so bypass this problem.
if there is a good method. it is wonderful

**Comment by nicm** [comment]
Sure, SIGSTOP will do basically the same as detaching.
