### ISSUE TITLE
Unable to begin-selection with mode-keys emacs

### ISSUE THREAD

**Issue by tigerjack** [tmux/tmux#3028]
### Issue description
I have the option `set-window-option -g mode-keys emacs` in the config file and `EDITOR="vim"` in my bashrc. In this way, it is impossible to select text from copy mode

Steps to reproduce

1. Create a simple `test.conf` file with a single line `set-window-option -g mode-keys emacs`
2. Run `EDITOR="vim" tmux -f test.conf`
3. Enter copy-mode with `C-b ]`
4. Try to begin the selection (with either `Space` or `C-Space`). Nothing happens.

Using instead `EDITOR="vim" tmux -f /dev/null` I can select text using `Space`.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). Tried with both `3.1c` and `3.2a`
* Platform (`uname -sp`). Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). Tried with kitty, urxvt and xterm
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-server.log](https://pastebin.com/Yg1ahkWt)
[tmux-client.log](https://pastebin.com/whAh1f1E)

EDIT:
Additional logs
[logs.tar.gz](https://github.com/tmux/tmux/files/7821999/logs.tar.gz)

**Comment by nicm** [comment]
There is no sign of you pressing `C-Space` in this log, are you sure your terminal supports it?

If you run `cat` outside tmux and press `C-Space`, what do you see?

**Comment by tigerjack** [comment]
> There is no sign of you pressing `C-Space` in this log, are you sure your terminal supports it?

Ok, maybe I forgot to press `C-Space` in that specific session, but I tried different configuration several times, and it was always the same behavior. I'll try to get a new log asap.

> If you run `cat` outside tmux and press `C-Space`, what do you see?
Nothing is printed on the terminal.

**Comment by nicm** [comment]
If you see nothing outside tmux when you press `C-Space`, tmux will be unable to act when you press `C-Space`. `C-Space` should show `^@`.

Are you sure your terminal or WM isn't stealing it for something else?

**Comment by tigerjack** [comment]
> If you see nothing outside tmux when you press `C-Space`, tmux will be unable to act when you press `C-Space`. `C-Space` should show `^@`.
> 
> Are you sure your terminal or WM isn't stealing it for something else?

I think you're right, opening tmux from a tty (i.e., without the WM) doesn't give problems. Now I should investigate more on which of my GUI app is stealing the hotkey.

Thanks for your quick help :)
