### ISSUE TITLE
[feature] flag to log complete sessions similar to screens -L

### ISSUE THREAD

**Issue by aleksandersumowski** [tmux/tmux#3029]
I'd like to be able to run a script in a screen session logging the commands issued and the output of the commands, eg:

```tmux -L -Logfile ingestion-`date -Iseconds`.log -S my_database_ingestion -dm runIngestion.sh```

The existing [plugin](https://github.com/tmux-plugins/tmux-logging) requires either to issue the command within the session to start recording or to know at what point to capture the buffer content

**Comment by nicm** [comment]
This is pretty unclear, what are you trying to do?

**Comment by aleksandersumowski** [comment]
I'd like to be able to have a script eg runingestion.sh that starts ingestion process in a detached session with all the output from the session stored in a log file

**Comment by nicm** [comment]
You can use `pipe-pane` to send output from a pane to a process or file.

**Comment by aleksandersumowski** [comment]
so eg?
```tmux new -d -s test MY_COMMAND
tmux pipe-pane -t test -o 'cat >> ./output.log'```

that would potentially miss the few initial lines but could work

**Comment by nicm** [comment]
Yes that will work, or:
~~~~
tmux new -dstest 'tmux pipe-pane "cat >>log"; mycommand'
~~~~

**Comment by aleksandersumowski** [comment]
Thanks a lot for help!
