### ISSUE TITLE
Unable to clear screen inside Tmux on MacOS

### ISSUE THREAD

**Issue by helins** [tmux/tmux#3030]
### Issue description

It seems trivial but I have been googling it for a while without success. Talks about the TERM variable were conclusive.

Using the Mac Terminal or iTerm2, clearing the screen does not work inside Tmux (e.g. CTRL-L). You can see that it is even greyed out in the menu options:

<img width="2560" alt="Screenshot 2022-01-08 at 11 54 20" src="https://user-images.githubusercontent.com/17478152/148641580-d6854f10-d61f-49ff-816b-4c1124ca0aa1.png">

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.2a

* Platform (`uname -sp`)
Darwin arm (Macbook Pro M1 Max)

* $TERM inside and outside of tmux (`echo $TERM`).
Outside: xterm-256color
Inside: screen (by default, but I've also tried setting it to screen-color256 and xterm-color256 in .tmux.conf but it doesn't change anything)

* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
It probably disables the menu option because it can't usefully clear the screen for full screen interactive programs like tmux which would just redraw it anyway.

C-l to make the shell clear should still work however.

**Comment by helins** [comment]
Yes, and I can't any single post or question mentioning this issue 🤔 
It must some colliding keybindings... In any case, thanks for your input.
