### ISSUE TITLE
tmux crashes after press g in copy mode (goto-line) and then hold down esc.

### ISSUE THREAD

**Issue by NCTU0210804** [tmux/tmux#3031]
### Issue description

tmux crashes after press g in copy mode (goto-line) and then hold down esc. These can be reproduced by the following steps.

Firstly, press g in the copy mode, which triggers the goto-line command.
Secondly, rapidly press [esc] several times continuously.

Then tmux will crash and leave a message: "[server exited unexpectedly]".

I believe that this is not considered a normal behavior, as this killed my other detached sections as well.

Note that holding down esc in the second step instead of keeping pressing might also make tmux crash, but not always.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).  -> tmux 3.2a
* Platform (`uname -sp`). -> Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`). -> Insider: "screen"; outside: "xterm-256color".
* Logs from tmux (`tmux kill-server; tmux -vv new`).  -> This can be reproduced without configuration file, so I used `tmux -Ltest kill-server; tmux -vv -Ltest -f/dev/null new` instead.
[tmux-client-40457.log](https://github.com/tmux/tmux/files/7835257/tmux-client-40457.log)
[tmux-out-40459.log](https://github.com/tmux/tmux/files/7835258/tmux-out-40459.log)
[tmux-server-40459.log](https://github.com/tmux/tmux/files/7835259/tmux-server-40459.log)

Other information that might be useful:

The information I listed above is tested on macOS Big Sur 11.5.2. However, I first found this bug on a Linux machine. Unfortunately, that machine is not mine, so I might not be able to test this bug on that machine again.

On the other hand, a friend of mine said he uses tmux 2.6 and that this does NOT happen on his side.

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by NCTU0210804** [comment]
Hi @nicm.
I've tried to build tmux cloned from the master, but it's not so easy to test that.
Here is part of the compiler error message that I consider meaningful.

```
ld: warning: ignoring file /usr/local/Cellar/libevent/2.1.12/lib/libevent_core.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_bufferevent_disable", referenced from:
      _control_write_callback in control.o
      _control_discard in control.o
      _job_write_callback in job.o
      _job_error_callback in job.o
      _server_client_loop in server-client.o
      _window_pane_read_callback in window.o
  "_bufferevent_enable", referenced from:
      _cmd_pipe_pane_exec in cmd-pipe-pane.o
```

Is there an easier way to test?

**Comment by nicm** [comment]
That seems like a problem with your build setup, are you sure you aren't mixing different libevent versions?

**Comment by NCTU0210804** [comment]
I've tried uninstalling libevent and installing it again using homebrew, but it still doesn't work. Is there any other way I can try?
BTW, I got a message from another friend that tmux 3.0a on Ubuntu does NOT trigger this either.

**Comment by nicm** [comment]
Show config.log.

**Comment by NCTU0210804** [comment]
[config.log](https://github.com/tmux/tmux/files/7840015/config.log)

**Comment by nicm** [comment]
> ld: warning: ignoring file /usr/local/Cellar/libevent/2.1.12/lib/libevent_core.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

It looks like your libevent is built for the wrong architecture.

**Comment by NCTU0210804** [comment]
I had to build the newest tmux (cloned just now) in a docker container (ubuntu), and that bug does NOT happen again.
I am looking forward to the release, and hopefully, this issue will no longer occur on any platforms in the new version.
(So far found this issue on Linux and macOS-arm64, both with the 3.2a version.)

**Comment by nicm** [comment]
OK great.
