### ISSUE TITLE
How to send CSI sequences from tmux configuration file ?

### ISSUE THREAD

**Issue by akharrou** [tmux/tmux#3032]
> ```zsh
> ❯ tmux -V
> tmux 3.2a
> ❯ uname -sp
> Darwin i386
> ❯ echo $TERM
> xterm-256color   # same for inside tmux
> ```

I'm trying to get a key press of `cmd+;` to send to the shell the CSI sequence of `59 9u`.

```properties
bind-key -n "M-;" send-keys '^[[59;9u'
```

Can someone point me towards the right direction to emit this CSI sequence ?

**Comment by nicm** [comment]
send Escape "[59;9u"

**Comment by akharrou** [comment]
I only get literal text outputting... not the escaped sequences

Here's what I get outside of tmux and inside (this is using the [kitty](https://github.com/kovidgoyal/kitty) terminal):

![Jan-11-2022 12-00-35](https://user-images.githubusercontent.com/36056254/148912393-5f8bc7e6-05fc-426e-a126-705a965866db.gif)

**Comment by akharrou** [comment]
Hey @nicm, real quick how would you bind a CSI sequence received by tmux to an action ?

E.g.:

```zsh
bind-key "[59;9u" next-window
```

**Comment by nicm** [comment]
Put them in user-keys, or for these sequences you can build from master and
turn on extended-keys option.
