### ISSUE TITLE
Does tmux support OSC 99

### ISSUE THREAD

**Issue by rameshsanth** [tmux/tmux#3034]
### Issue description

I tried this on 2 platforms.. on my Mac (tmux 3.2a) and after ssh to Redhat linux 7.9 running tmux next 3.4

I'm trying out desktop notification on kitty terminal. [https://sw.kovidgoyal.net/kitty/desktop-notifications/?highlight=desktop%20notification](https://sw.kovidgoyal.net/kitty/desktop-notifications/?highlight=desktop%20notification)

The below 2 commands generate a notification on OSX
```
printf '\x1b]99;i=1:d=0;Hello world\x1b\\'
printf '\x1b]99;i=1:d=1:p=body;This is cool\x1b\\'
```

Nothing seems to happen when i run inside tmux. But the desktop notifications work when run on native kitty terminal on OSX as well as an SSH to linux server

### Required information

Please provide the following information:

* tmux version (`tmux -V`)  tmux next-3.4, tmux 3.2a
* Platform Linux x86_64, Darwin i386 
* $TERM inside and outside of tmux (`echo $TERM`). inside "xterm-kitty" outside "xterm-kitty"
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-out-36927.log](https://github.com/tmux/tmux/files/7848971/tmux-out-36927.log)

**Comment by nicm** [comment]
This is exactly what the passthrough sequence is intended for, see the FAQ.
