### ISSUE TITLE
A potential bug of null pointer dereference

### ISSUE THREAD

**Issue by ash1852** [tmux/tmux#3035]
Hi,I found a bug of null pointer dereference in the source code of tmux.I apologize for not following your rules in CONTRIBUTING.md, as this is not a bug that has occurred (or has occurred but not been located), but does exist in the source code. Could you please take some time to check if this bug is true? Thank you very much for your patience and efforts!
**First is an overview of how this bug occurred**
![image](https://user-images.githubusercontent.com/87304478/149079276-7132a4d5-7a7e-4111-aa2a-8f80cd863f3b.png)
![image](https://user-images.githubusercontent.com/87304478/149083342-2c072e61-0f2e-4de8-9579-4b1ace81c6bc.png)

**Next are specific explanations of each step in the above diagram**

**step1**:
in file tmux/cmd-capture-pane.c , [line 78](https://github.com/tmux/tmux/blob/master/cmd-capture-pane.c#L78) to [line 85](https://github.com/tmux/tmux/blob/master/cmd-capture-pane.c#L85):
in these lines,  **pending**</font> is initialized but the **size**(or length) of pending can be **0**. And bug occurs when **size==0** because of explanation as follows.
![image](https://user-images.githubusercontent.com/87304478/149082041-0763488d-0771-4d2e-a3b0-30744a4214da.png)

**step 2:**
in file tmux/cmd-capture-pane.c , [line 87](https://github.com/tmux/tmux/blob/master/cmd-capture-pane.c#L87) :
pending is used as the 1st param of **EVBUFFER_DATA**,which is defined in libevent.
![image](https://user-images.githubusercontent.com/87304478/149082108-2e8f453a-37f9-4828-ba4a-7a1c866e01ec.png)

**step 3:**
in file libevent/include/event2/buffer_compat.h , line 112:
**EVBUFFER_DATA**(x) is defined as **evbuffer_pullup**((x), -1)(**note** , the value of  2nd param is -1)
![image](https://user-images.githubusercontent.com/87304478/149082156-0f0d2516-30c3-4d1d-a57e-5d983c525c47.png)

**step4:**
in file libevent/buffer.c, line 1348:
**result** is initialized to be **null**
![image](https://user-images.githubusercontent.com/87304478/149082211-e3aff9ba-74a0-4491-9957-a5753b0126fd.png)

**step5:**
in file libevent/buffer.c, line 1357:
select true branch , because size==-1.
![image](https://user-images.githubusercontent.com/87304478/149082248-66c78a59-51db-4b06-8475-6a0e678d0783.png)

**step6:**
in file libevent/buffer.c , line 1358:
size is redefined to be size of buf(pending),and because of step 1, **size can equal 0**
![image](https://user-images.githubusercontent.com/87304478/149082248-66c78a59-51db-4b06-8475-6a0e678d0783.png)

**step7:**
in file libevent/buffer.c , line 1362:
select ture branch because size can equal 0, and goto **done**
![image](https://user-images.githubusercontent.com/87304478/149082318-49c3f0a4-82cf-424c-82cc-a98ad658fe12.png)

**step8:**
in file libevent/buffer.c , line 1453:
return **result**(**null**) to caller
![image](https://user-images.githubusercontent.com/87304478/149082388-f8588234-5cc1-41c7-a242-ecf9e06fae4b.png)

**step 9:**
in file tmux/cmd-capture-pane.c , [line 87](https://github.com/tmux/tmux/blob/master/cmd-capture-pane.c#L87) :
**line** is redefined to be **null**
![image](https://user-images.githubusercontent.com/87304478/149082452-840f5402-2322-4f45-9af5-86fbeb262e86.png)

**step10:**
in file tmux/cmd-capture-pane.c , [line 101](https://github.com/tmux/tmux/blob/master/cmd-capture-pane.c#L101) :
**line** is used as 3rd paramter of cmd_capture_pane_append and in this call,line will be 2nd pamramter of **memset** unconditionally.
the definition of **cmd_capture_pane_append**  is in file tmux/cmd-capture-pane.c , [line 66](https://github.com/tmux/tmux/blob/master/cmd-capture-pane.c#L66) 
![image](https://user-images.githubusercontent.com/87304478/149082505-fdd181b2-acbd-467e-adf5-e27f5a14e702.png)
![image](https://user-images.githubusercontent.com/87304478/149082555-12d331db-60f3-4ebb-94ad-c8d7822afe5a.png)

**Comment by nicm** [comment]
How can `line` be `NULL` but `linelen` be nonzero? `memset(NULL, 0, 0)` is safe.

**Comment by ash1852** [comment]
> How can `line` be `NULL` but `linelen` be nonzero? `memcpy(x, NULL, 0)` is safe.

Thank you for your reply, you are right, this bug is false.
