### ISSUE TITLE
[feature] show all window in ui of cmd choose-tree

### ISSUE THREAD

**Issue by ask-github** [tmux/tmux#3036]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

if i have many windows in one session. i want to switch window of those use cmd choose-tree
it can't show all window index on one time

the right of the list of window is empty. use this zone to show all window is a good idea
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/72971953/149332118-7dac33c4-c70a-4e39-a976-b42d88001279.png">

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* tmux 3.2a
* Platform (`uname -sp`).
* x86_64 linux
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
I'll put it in the todo list btu I don't see this happening anytime soon.
