### ISSUE TITLE
error connecting to /tmp//tmux-0/default (No such file or directory)

### ISSUE THREAD

**Issue by vansh1** [tmux/tmux#3037]
### Issue description
I have had one running session which I wanted to connect again, but I am unable connect it to again i am getting this error i did tmux ls to reproduce this issue i wanted to connect again please help
### Required information

Please provide the following information:

* tmux version = tmux 3.0a
* Platform = Linux x86_64
* $TERM inside and outside of tmux = xterm

**Comment by nicm** [comment]
`/tmp//tmux-0/default` will be for root, did you start tmux as root?

Also see https://github.com/tmux/tmux/wiki/FAQ#tmux-says-no-sessions-when-i-try-to-attach-but-i-definitely-had-sessions.

**Comment by vansh1** [comment]
yes i did sudo su first then run that command

**Comment by vansh1** [comment]
plus i created new session it showing when i do tmux ls but it doesn't showing old session
