### ISSUE TITLE
[FeatureRequest] option to set timezone for tmux time format placeholders

### ISSUE THREAD

**Issue by loynoir** [tmux/tmux#3039]
Given system timezone is A, ssh user timezone is B

### Actual
```sh
$ tmux set-option -gq status-right '%T'
# time formated in timezone A

shell in tmux $ date
# time formated in timezone A
```

### Expected
```sh
$ tmux-set-option -gq placeholder-timezone B
$ tmux set-option -gq status-right '%T'
# time formated in timezone B

shell in tmux $ date
# time formated in timezone A
```

### Alternative
1. Seems not very graceful to spawn shell every 1s
```sh
$ tmux set -g status-right '#(TZ=B date +%%H:%%M:%%S)'
```

2. 
```sh
# tmux.conf
set-option -g default-command "env -u TZ /usr/bin/zsh"
```

```sh
# Must have no other tmux client on ssh server
$ TZ=B tmux
```

**Comment by nicm** [comment]
It is tricky to do timezone just for status line because you can only have one timezone for a process, we don't really want to be calling `tzset` all the time.

It sounds like you should just make sure `TZ` is set before you start tmux.

**Comment by loynoir** [comment]
Oh, I forgot to say, here is a `ssh` user situation.

**Comment by loynoir** [comment]
If it's not easy to implement, I'm OK to close. 😃

**Comment by nicm** [comment]
I think this is not easy to do and few people will want more than one timezone. Usually you can just make sure TZ is set before you start tmux.
