### ISSUE TITLE
Clarification on variables prefixed with global_ 

### ISSUE THREAD

**Issue by tony** [tmux/tmux#304]
Greetings tmux developers and users,

When variables like `global_environ`, `global_hooks`, `global_s_options`, etc are used, are these meant to be *server* wide?

Global can feel ambiguous, even after reading this::

     When the server is started, tmux copies the environment into the global
     environment; in addition, each session has a session environment.

*If* in fact they are strictly server wide, why use ``global``? As a user, I begin to question my own understanding how environment data persists: "Could global variables persist *across* multiple tmux servers through some other mean (saving it to a config file, or an ephemeral file in /tmp)", "Is global itself another concept outside of server/session/window/pane/client primitives I've grown familiar with?".

Before I get acclimated with the ``global_`` prefix, is there any reason why ``server_`` wasn't picked up? Isn't that more accurate?

**Comment by nicm** [comment]
They are global variables...

**Comment by nicm** [comment]
I don't think we want to rename stuff at this point. The various classes of options is documents in the OPTIONS section of the manpage.

**Comment by tony** [comment]
I am still a tad confused. Maybe I'm talking about two different things.

1. manpage clarification

  By "global environment" in the manpages under ENVIRONMENTS section, what is meant?

 So global environment means they persist only on the server?

 So, setting tmux global environment variables **will not** alter environment outside tmux, and  **do not** persist across multiple tmux servers (they are global only to the tmux server running)?

2. manpage clarification

  In OPTIONS, is the term global is thrown around a lot also. If its global, its to mean they are persisted throughout the runtime of the server?

3. code clarification

  > They are global variables...

  So in this context, it strictly means global application variables? It's not meant to infer anything that the data ends up persisting while the server is running?

**Comment by nicm** [comment]
Global is per server yes. I don't think there is anything that implies any of this stuff persists.

**Comment by nicm** [comment]
There is a global set of session options which are each applied to all sessions unless a session overrides an option in the set of local (per-session) session options. Likewise for the window options and much the same for the environment. Server options are unique in that there is one set for all sessions and they cannot be overridden. tmux does not do anything particularly unusual here, we are not using radical new meanings of global and local.

**Comment by tony** [comment]
thank you

Hm, without using the word persist: When setting global options / environment variables, they exist for the lifetime of the server. *That* is correct right?

**Comment by nicm** [comment]
Yes NOTHING is persistent beyond the lifetime of the server.
