### ISSUE TITLE
if-shell is not working as intended on Linux

### ISSUE THREAD

**Issue by ram-on** [tmux/tmux#3040]
The following is the contents of my $HOME/.tmux.conf on my Linux machine:
```
if-shell "[[ $(uname) == 'Linux' ]]" {
    set -g status-bg red
}
```

If I try to reload the configuration file by typing `tmux source ~/.tmux.conf`, the status bar color does not change on Linux.

I also have access to macOS in which I've set the `.tmux.conf` to:
```
if-shell "[[ $(uname) == 'Darwin' ]]" {
    set -g status-bg red
}
```

As soon as `tmux source ~/.tmux.conf` is executed: `if-shell` works perfectly on macOS and the status bar color is changed to red.

**Linux Specs:**
```bash
$ tmux -V
tmux 3.2a
$ uname -sp
Linux x86_64
$ echo $TERM
screen
$ echo $SHELL
/bin/bash
$ bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
```

**macOS Specs (just FYI):**
```bash
$ tmux -V
tmux 3.2a
$ uname -sp
Darwin i386
$ echo $TERM
screen
$ echo $SHELL
/usr/local/bin/bash
$ bash --version
GNU bash, version 5.1.16(1)-release (x86_64-apple-darwin21.1.0)
```

**Comment by nicm** [comment]
if-shell uses /bin/sh, are you sure your /bin/sh understands [[  ]]? Does
it work if you use [ ] or test?

**Comment by ram-on** [comment]
I can confirm that the below code works on Linux:
```
if-shell "[ $(uname) = 'Linux' ]" {
     set -g status-bg red
}
```

Which means that `if-shell` is using `/bin/sh`.  Is there a reason why `if-shell` is defaulting to `/bin/sh`?

(`if-shell` on macOS is not defaulting to `/bin/sh`)

**Comment by nicm** [comment]
if-shell always uses /bin/sh, are you sure it isn't a different shell on Linux and macOS?

**Comment by ram-on** [comment]
Well on macOS, the below config works perfectly, so it means that on macOS if-shell is not using /bin/sh
```
if-shell "[[ $(uname) == 'Darwin' ]]" {
    set -g status-bg red
}
```

**Comment by nicm** [comment]
No, it means that /bin/sh on macOS is probably a different shell that is not strictly POSIX conformant, or is set up differently from Linux.

**Comment by ram-on** [comment]
You are right, mystery solved :) - sh is just an old version of Bash:
```
$ /bin/sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by ram-on** [comment]
Suggestion: can you please make a reference within the if-shell section of `man tmux` which states that if-shell always uses /bin/sh ?

**Comment by nicm** [comment]
I have added a note to the man page now. Thanks!
