### ISSUE TITLE
Environment variables not correctly inherited from bash.

### ISSUE THREAD

**Issue by alexisfrjp** [tmux/tmux#3041]
I have a bash script exporting `TEST` env variable.
```shell
#!/bin/bash
export TEST=$1
tmux new-session -d -s $1
tmux send-keys -t $1:0 "echo \$TEST" C-m
```

Run:
```
# ./test.sh 123  #The tmux server is automatically launched
# ./test.sh 555
```

Results:
* `tmux a -t 123` shows `123`
* `tmux a -t 555` shows `123` instead of `555`!!!!

The session 555 must have TEST=555, it shouldn't have any knowledge of TEST=123 that was run previously for a previous session unrelated to this one.

That's quite surprising, how can I do to stop this non-sense behavior? What did I miss in the tmux's behavior? I believe that's a bug. Could you confirm?

https://manpages.debian.org/experimental/tmux/tmux.1.en.html#GLOBAL_AND_SESSION_ENVIRONMENT 
> When the server is started, tmux copies the environment into the global environment; in addition, each session has a session environment. When a window is created, the session and global environments are merged. If a variable exists in both, **the value from the session environment is used**.

**Comment by nicm** [comment]
You need to put `TEST` in `update-environment` or use `-e` to `new-session` if you want it to be set differently in a new session after the server is started

**Comment by alexisfrjp** [comment]
Yes... coming from screen and bash, I just discovered this counterintuitive non-sense design decision.
I'll need to be much more careful starting the tmux server at boot for a dummy session otherwise it might affect all the sessions created.
What's the common usage of tmux? How does people use tmux correctly?

* `update-environment` adds the variable after the first command is run => completely useless


I have to use tmux 1.8 in centos 7, `-e` doesn't exist...
>new-session [-AdDP] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [shell-command]
                   (alias: new)

Not sure I want to move to tmux anymore if that simple thing can't be done easily...
