### ISSUE TITLE
Virtual window/pane sizes

### ISSUE THREAD

**Issue by brianjmurrell** [tmux/tmux#3042]
It would be useful if windows/panes could have a virtual size in addition to their physical size.  One would be able to scroll the virtual window/pane inside the physical ones.  Or maybe one just needs a large virtual size (say, 120 chars) to prevent line wrapping but is only interested in seeing a portion of the virtual window, like say, just the left-side 80 characters.

**Comment by nicm** [comment]
Use the `resize-window` command.

**Comment by brianjmurrell** [comment]
On Thu, 2022-01-27 at 23:53 -0800, Nicholas Marriott wrote:
> Use the `resize-window` command.

That seems to make the pane jump around all over the place.  Not quite
what I was looking for.  I want the small physical "view" on top of the
larger physical pane to be static and only show the portion that small
view is covering.

**Comment by nicm** [comment]
You can use refresh-client -U/-D/-L/-R/-c as well, IIRC there are default
key bindings but I forget what they are (check lsk).
