### ISSUE TITLE
Show commands to reproduce session/window/pane

### ISSUE THREAD

**Issue by brianjmurrell** [tmux/tmux#3043]
### Issue description
Let's say I have spent a bit of time creating a session, or even just a window of panes, complete with sizes, commands running in them, etc.

It would be useful to be able to ask tmux what commands I need to reproduce that session or just window (of panes perhaps) even.

**Comment by damnskippy** [comment]
I understand OP would like tmux to output a list of commands to recreate the session.  This seems doable with a shell script using existing tmux commands as well?

**Comment by brianjmurrell** [comment]
@damnskippy Could you expand on how this could be done?  I haven't the foggiest of where to even start with that.

**Comment by damnskippy** [comment]
`list-sessions`, `list-windows`, `list-panes` should produce the details about the existing structure that can be parsed to rebuild things back.

**Comment by damnskippy** [comment]
BTW, there's also this plugin that might do exactly what you're looking to do: https://github.com/tmux-plugins/tmux-resurrect

**Comment by nicm** [comment]
There is no way to do this built into tmux, I suggest you look at the plugins as @damnskippy has suggested, or write a script to create your session.

**Comment by brianjmurrell** [comment]
> There is no way to do this built into tmux

I realize that.  This ticket was open as an RFE to add it.  It seems like pretty core functionality to me.

I have not tried the plugin yet, so hopefully it works as advertised, but I still think this should be core functionality and not require a plugin.  I am pretty sure you will disagree, but I just wanted to express my opinion on that and provide a ticket that people could upvote if they wanted to express the same.
