### ISSUE TITLE
In version 3.2a `C-b ;` says ```no last pane```

### ISSUE THREAD

**Issue by sahilrajput03** [tmux/tmux#3044]
### Issue description

 I used pacman to install:

```
sudo pacman tmux
```

and i can't use keybinding `C-b ;` which doesn't switch to last active pane.

### Required information

* tmux version: `3.2a`
* Platform: (uname -a): `Linux arch-os 5.15.13-arch1-1 #1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59 +0000 x86_64 GNU/Linux`
* $TERM inside and outside of tmux (`echo $TERM`): `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): nothing..

**Comment by nicm** [comment]
Do you have a last active pane?

**Comment by sahilrajput03** [comment]
![image](https://user-images.githubusercontent.com/31458531/151039720-c61783f6-5a46-4b4b-93b5-8f8ec1fd2dcb.png)
![image](https://user-images.githubusercontent.com/31458531/151039838-dea9ec1f-ad1b-415a-92f2-a30a0b2a91cd.png)

Yes!!

> Do you have a last active pane?

**Comment by nicm** [comment]
Are you sure? I only see one pane in these screenshots. Are you confusing window and pane?
