### ISSUE TITLE
Hide copy mode yellow scroll indicator

### ISSUE THREAD

**Issue by cerealXDD** [tmux/tmux#3045]
Is there anyway to hide this yellow indicator at the top right? As you can see from the image its getting in the way of reading. I'm using tmux display-message
![2022-01-26 19_27_17-Cmder](https://user-images.githubusercontent.com/97008719/151269620-195a9a29-7984-456a-acaa-79c3013b02a2.png)

**Comment by nicm** [comment]
copy-mode -H

I don't think there is a key binding to turn it off once you are in copy
mode.

**Comment by cerealXDD** [comment]
https://github.com/tmux/tmux/commit/7863445e5d6823ab21c49904b8e5ec5028264d39

Ok, according to this issue this change was introduced Mar 12 2020 after the release of tmux 3.0a. I'll close this issue then. Thank you @nicm

**Comment by cerealXDD** [comment]
Does display-message have a way to hide the yellow indicator? I've successfully hid it with copy mode after upgrading to tmux 3.2. But I need display-message to hide it as well.

**Comment by nicm** [comment]
No it doesn't at the moment.

**Comment by nicm** [comment]
I don't really want to add `-H` to `display-message`, but please try this which adds a `P` key to let you toggle the indicator when you are in copy mode: [tmux-toggle-position.diff.txt](https://github.com/tmux/tmux/files/7978207/tmux-toggle-position.diff.txt)

**Comment by nicm** [comment]
I have applied this now.
