### ISSUE TITLE
DELETEME

### ISSUE THREAD

**Issue by alexchaichan** [tmux/tmux#3046]
opend wrong issiue

**Comment by nicm** [comment]
Can you use them outside tmux?

**Comment by nicm** [comment]
OK, please show logs with you pressing one of the pair of keys that doesn't
work, also tell me which keys you are pressing (eg option and a).

**Comment by alexchaichan** [comment]
alt + for `|`

alt + 8 , 9 for `{ }`

shift + alt + 7 for backslash

okey.. i figured something out.

when i press alt + 5 which is basicly for `[` and then press 5 again a `[` apear. 
Same for all other signs. I have to press alt + 5 and then for e.g 7 to get a `|`.

Any ideas how to solve it?
