### ISSUE TITLE
Segfault when pressing Alt-1+Space+Space in command mode

### ISSUE THREAD

**Issue by stygian-coffee** [tmux/tmux#3048]
### Issue description

Tmux server segfaults when pressing Alt-1, Space, and Space in that order while in command mode. This occurs in Alacritty, but it does not occur when using xterm.

Steps to reproduce:
- Open tmux: `tmux -vv -Ltest -f/dev/null new`
- Enter command mode: Ctrl-B+:
- Press Alt-1, then Space, then Space

strace log of tmux server: [strace.log](https://github.com/tmux/tmux/files/7964676/strace.log)

### Required information

Please provide the following information:

* tmux version: `tmux 3.2a`
* Platform: `Linux unknown` (Arch Linux)
* $TERM outside of tmux: `alacritty`
* $TERM inside of tmux: `screen`
* Tmux logs: 
[tmux-client-51477.log](https://github.com/tmux/tmux/files/7964647/tmux-client-51477.log)
[tmux-out-51479.log](https://github.com/tmux/tmux/files/7964648/tmux-out-51479.log)
[tmux-server-51479.log](https://github.com/tmux/tmux/files/7964650/tmux-server-51479.log)

**Comment by nicm** [comment]
Does this still happen if you build from master?

**Comment by stygian-coffee** [comment]
I've just tested this on 6c0397f49769666c836a312c292e9c67adc41058 (most recent commit as of the time of this comment), and this behavior is still present.

**Comment by krader1961** [comment]
FWIW: I can't reproduce using tmux on iTerm2 on macOS. It would help a lot if you enabled core dumps (usually `ulimit -c unlimited`) then reproduced the problem. Find the resulting core file and examine it with the `gdb` utility and execute its `bt` command to get a backtrace.

**Comment by nicm** [comment]
Good stuff.
