### ISSUE TITLE
mode-keys won't change according to VISUAL or EDITOR

### ISSUE THREAD

**Issue by aleprovencio** [tmux/tmux#305]
My understanding from the manual is that if one of those environment variables are set to 'vi', the 'mode-keys' setting would follow that too. I can only get such behavior by explicitly setting `set -g mode-keys vi` on tmux.conf.

**Comment by krader1961** [comment]
Works for me.

**Comment by aleprovencio** [comment]
I run tmux 2.1, bash and Arch, what about @krader1961 ?
What's on you shell's rc, somethings like `export EDITOR=vi` and/or `export VISUAL=vi`?

**Comment by krader1961** [comment]
I'm running tmux 2.2. The distro shouldn't matter for an issue of this nature. I have both **EDITOR** and **VISUAL** set to */usr/local/bin/vim*. I verified tmux sets the default to vi-style correctly if only one of those is set and leaves the default as emacs-style if it isn't. But honestly I wouldn't, and don't, depend on this feature. I normally have the following in my *~/.tmux.conf* file:

```
# Use VI style keyboard shortcuts.
set-option -g status-keys vi
set-window-option -g mode-keys vi
```

**Comment by aleprovencio** [comment]
alright thanks for the advice!
