### ISSUE TITLE
Data pickled from inside tmux did not load from outside tmux

### ISSUE THREAD

**Issue by z-suri** [tmux/tmux#3052]
### Data pickled from inside tmux did not load from outside tmux

My experiment was specific to Pytorch but this could be a general issue. I save my model's state_dict but when I try to load it from outside tmux, it gives the following error

```
Exception has occurred: UnpicklingError

A load persistent id instruction was encountered, but no persistent_load function was specified
```

but it loads successfully from within a new tmux session. The Python environments were exactly the same ones in and outside of tmux.

### Required information

* tmux version (`tmux -V`). 3.2a
* Platform (`uname -sp`). Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
This is nothing to do with tmux itself, something is different in your
environment between inside and outside. Are you sure PATH is the same and
you are using the same python binary?
