### ISSUE TITLE
confirm-before does not parse style strings inside prompt parameter (possibly related to #2920)

### ISSUE THREAD

**Issue by atomicstack** [tmux/tmux#3054]
### Issue description

The `confirm-before` command accepts a ```-p "prompt"``` parameter, which specifies the text of the prompt to be displayed. The man page says:
```
If -p is given, prompt is the prompt to display; otherwise a prompt is constructed from command. It may
contain the special character sequences supported by the status-left option.
```
The `STYLES` section says:
```
In addition, embedded styles may be specified in format options, such as status-left, by enclosing them
in `#[' and `]'.
```
This suggests to me that it should be possible to add style sequences to the prompt parameter of `confirm-before`. However, on my recent build of tmux (6c0397f49769), the #S alias appears to be recognised, but the style sequence is not.

To replicate it:

```
tmux -L empty
tmux bind-key ^K confirm-before -p "#[fg=red]kill-session #S?#[default] (y/n)"
<press prefix-^K>
```

The displayed prompt will be like so:
`#[fg=red]kill-session 0?#[default] (y/n)`

i.e., the #S alias in the format string is being expanded to the session name, but the style specifiers are passed through as-is.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
`tmux next-3.4`
* Platform (`uname -sp`).
`Darwin i386`
* $TERM inside and outside of tmux (`echo $TERM`).
Outside: `xterm-256color`
Inside: `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
I will attach them later on today.

This commit (76f5d3364c8d) also appears to be related to ticket #2920, if that helps.

Cheers!

**Comment by nicm** [comment]
Right, it does not. Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/7992548/x.diff.txt)

**Comment by atomicstack** [comment]
The patch looks good to me - I can confirm that the style sequences are now also being parsed as expected.

Thanks!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
