### ISSUE TITLE
My mouse has more buttons, can tmux bind them?

### ISSUE THREAD

**Issue by daiaji** [tmux/tmux#3055]
My mouse has more buttons, 6 buttons in addition to the usual three.
![img](https://m.media-amazon.com/images/S/aplus-media/sc/5dddc143-499f-4fde-b0b5-0e132700a208.__CR0,0,970,600_PT0_SX970_V1___.jpg)
But the documentation tells me that only three mouse buttons seem to be able to be bound.

**Comment by nicm** [comment]
The terminal mouse protocol only supports three buttons (plus wheel up and
down) and to my knowledge no terminal has extended this.

**Comment by ThomasDickey** [comment]
Actually, xterm does this (see [script](url) giving the responses).

**Comment by nicm** [comment]
Ah yes and I see it in the docs now as well, thanks. I'll add it next week.

**Comment by nicm** [comment]
I have no mouse with more than two buttons with which to test this and it doesn't seem that many people need it, so I am going to close this until someone can verify it works.

**Comment by daiaji** [comment]
I compiled TMUX, but it seems that the sixth button cannot take effect.
```
cat ~/.tmux.conf
#set-option -g mouse on
bind -r MouseDown6Pane run "echo 1111 >> ~/11111.log"
```

**Comment by nicm** [comment]
OK please run tmux like this:

tmux -Ltest -f/dev/null -vv new \; set -g mouse on

Then click button 6 a few times, then exit tmux and send me the
tmux-server*.log file.


Are you using xterm?

**Comment by daiaji** [comment]
[tmux-server-69114.log](https://github.com/tmux/tmux/files/8080344/tmux-server-69114.log)

**Comment by nicm** [comment]
This is coming through as button 65 which is button 5 aka Wheel Down.

Can you try the same but press some of the other buttons?

**Comment by daiaji** [comment]
[tmux-server-91421.log](https://github.com/tmux/tmux/files/8081095/tmux-server-91421.log)

**Comment by nicm** [comment]
Your terminal is sending all these buttons as button 1 (the 0 in `[<0;` means button 1):
~~~~
1645025126.143937 /dev/pts/2: keys are 11 (\033[<0;25;30M)
1645025126.304012 /dev/pts/2: keys are 11 (\033[<0;25;30m)
1645025127.207927 /dev/pts/2: keys are 11 (\033[<0;76;30M)
1645025127.367996 /dev/pts/2: keys are 11 (\033[<0;76;30m)
~~~~
Are you sure your terminal supports this? You may have to use xterm.

**Comment by nicm** [comment]
This looks like Konsole which I bet does not support these buttons. You will need to try xterm instead.

**Comment by daiaji** [comment]
[tmux-server-95398.log](https://github.com/tmux/tmux/files/8081260/tmux-server-95398.log)
I switched to xterm.

**Comment by nicm** [comment]
OK this looks better:
~~~~
1645026388.087444 /dev/pts/1: keys are 12 (\033[<129;37;6M)
1645026388.239356 /dev/pts/1: keys are 12 (\033[<129;37;6m)
1645026388.471420 /dev/pts/1: keys are 12 (\033[<128;37;6M)
1645026388.647601 /dev/pts/1: keys are 12 (\033[<128;37;6m)
~~~~
This is button 8.

But tmux is not recognizing it... I'll take a look.

**Comment by nicm** [comment]
OK it is getting the mouse down, but not the mouse up.

Can you try this diff instead: [y.diff.txt](https://github.com/tmux/tmux/files/8081511/y.diff.txt)

Please try binding something to the button, for example by doing:
~~~~
tmux bind -n MouseDown8Pane lsk
~~~~
And see if clicking on a pane works. If not, please send me a log again.

**Comment by nicm** [comment]
I have applied this now, it will be in GitHub later when it syncs up.

You will need to talk to KDE if you want Konsole to support this. I don't know what terminals other than xterm support it now.

Thanks!
