### ISSUE TITLE
tmux display-popup defaults to incorrect shell

### ISSUE THREAD

**Issue by GZLiew** [tmux/tmux#3056]
### Issue description

I just updated my tmux from 3.1c to 3.2a
I have tmux with fish as my default shell and command

```bash
set-option -g default-command /usr/local/bin/fish
set-option -g default-shell /usr/local/bin/fish
```

when I tried running the following command below in my terminal

```bash
tmux display-popup "ls | fzf"
```

I get the message in the popup showing

```bash
sh: fzf: command not found
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.2a
* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`). xterm-256color

**Comment by krader1961** [comment]
I'll bet you $20 USD your issue has nothing to do with upgrading tmux. 😄 

Please kill any existing tmux server and start it with logging enabled as documented [here](https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md). Reproduce the problem and attach the logs to this issue.

**Comment by GZLiew** [comment]
@krader1961 Im well aware it has nothing to do with updating tmux

this was tmux-server logs
```bash
1644069205.953426 server_client_reset_state: cursor to 33,10
1644069205.953431 /dev/ttys000: \033[11;34H
1644069205.953443 server_client_check_pane_buffer: pane %0 is on
1644069205.953450 @0 active pane changed
1644069205.953455 @0 name timer already queued (267151 left)
1644069205.953505 /dev/ttys000: wrote 1024 bytes (of 3163)
1644069205.953512 /dev/ttys000: waiting for redraw, 2131 bytes left
1644069205.953538 job write 0x7f855571a840: ls | fzf, pid 68425, output left 0
1644069205.953559 screen_write_start_callback: size 63x16, with callback
1644069205.953569 screen_write_collect_end: 26 sh: fzf: command not found (at 0,0)
```

looks like I kind of fixed the problem when manually changing the settings for my terminal to default login shell

![image](https://user-images.githubusercontent.com/43195293/152645507-a6cfb5aa-099b-4444-b224-aa3aa9f5a075.png)

this looks more to be a problem with my terminal rather than tmux so im closing this now
