### ISSUE TITLE
sysmalloc on 3.2a when opening new-session

### ISSUE THREAD

**Issue by xeruf** [tmux/tmux#3057]
### Issue description

Sometimes when creating a new session I get a sysmalloc. Missing memory is definitely not an option:
```sh
❯ tmux new-session -s hedgedoc -d 'yarn run dev'
tmux: malloc.c:2539: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[1]    16945 abort (core dumped)  tmux new-session -s hedgedoc -d 'yarn run dev'
❯ free -h
               total        used        free      shared  buff/cache   available
Mem:            23Gi       3,5Gi        11Gi       589Mi       8,0Gi        18Gi
```
This issue tends to occur multiple times in succession, and then on random occurences it works again. Happening on multiple devices.

### Required information

* tmux version (`tmux -V`): 3.2a
* Platform (`uname -sp`): Arch
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color (also happens in kitty though)
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Show backtrace from the core in gdb please, see https://github.com/tmux/tmux/wiki/FAQ#tmux-exited-with-server-exited-unexpectedly-or-lost-server-what-does-this-mean.

**Comment by nicm** [comment]
What is `libstderred`? Do you have it in `LD_PRELOAD`?
