### ISSUE TITLE
PS1 and aliases not propagated into the tmux environment.

### ISSUE THREAD

**Issue by symbolix** [tmux/tmux#3058]
### Issue description

When starting a fresh tmux session within iTerm2 or Alacritty, the `aliases` and the `PS1` is not propagated into the freshly launched `tmux` session.

I'm using `/bin/bash` as my shell.

1. I start with a terminal session where `.bash_profile` is sourced.
2. Now I have bunch of env. variables and aliases set.
3. I run `tmux` as a non-login shell.
4. Now I'm inside `tmux` and `.bashrc` is sourced as we are running as a non-login shell.

Result:

- Environment variables from my original shell are retained.
- aliases and the $PS1 values are gone.

### Required information

Please provide the following information:

* tmux version (`tmux 3.2a`).
* Platform (`Darwin i386 (OSX 11.6)`).
* $TERM inside and outside of tmux (`xterm-256color`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
The environment for all panes is set from the global environment in tmux
which is copied from the shell where the tmux server was started. You can
have tmux update environment variables on attach with the
update-environment option. Aliases are internal to the shell so there is no
way for tmux to transfer them from one shell to another.

By default, tmux always runs login shells in new panes.

**Comment by symbolix** [comment]
Thank you. What about the $PS1 env. variable. I have seen some issues here already about that, but that is not getting picked up when I invoke tmux as a `non-login` shell, meaning the sequence is as the following `.bash_profile -> .bashrc`.

**Comment by nicm** [comment]
PS1 is treated no differently from any other environment variable, it is
not special to tmux. If it was exported from the shell where the tmux
server was started, it will be set to that value for processes in new panes.

You should probably set PS1 in a shell profile which will be used by shells
started by tmux.
