### ISSUE TITLE
Is it possible to make HOME and END send ^[[H and ^[[F?

### ISSUE THREAD

**Issue by for-coursera** [tmux/tmux#3059]
I have my custom tmux-256color-italic terminfo entry produced this way:

    ~> cat tmux.terminfo
    tmux-italic|tmux with italics,
        ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
        khome=\E[H, kend=\E[F,
        use=xterm, use=screen,
    
    tmux-256color-italic|tmux with italics and colors,
        use=xterm-256color, use=tmux-italic,

    ~> tic -x tmux.terminfo

And, if I set it in my terminal emulator, `export TERM=tmux-256color-italic`, HOME and END report expected values:

    ~> cat
    ^[[H^[[F

However, if I start tmux (and my `.tmux.conf` contains just one line, `set -g default-terminal tmux-256color-italic`), HOME and END keys report this:

    ~> cat
    ^[[1~^[[4~

Is it possible to fix this? I do understand, though, that these are still correct values, and it's not a bug or something like this. However, it conflicts with other applications, like sc or scim...

I also tried to add this line to `.tmux.conf`:

    set-option -ga terminal-overrides ',tmux-256color-italic:kend=\E[F:khome=\E[H:smkx=\E=:rmkx=\E>'

but without any noticeable results, unfortunately.

Would be grateful for a hint.

`tmux next-3.4`

**Comment by nicm** [comment]
tmux sends [1~ and [4~, your terminfo entry is wrong. You can't just make
up what you like, it needs to reflect tmux's actual capabilities. Base it
on screen-256color or tmux-256color alone, not on xterm.

**Comment by for-coursera** [comment]
@nicm 

Thanks for your advise, I corrected my terminfo entry.

But to send `^[[H` `^[[F` nothing can be done, right?

**Comment by nicm** [comment]
You could bind Home and End to send-keys these sequences. But defining a
terminfo entry for tmux based on xterm is wrong.

**Comment by for-coursera** [comment]
> But defining a terminfo entry for tmux based on xterm is wrong.

I agree, and it's not based on xterm any more :)

> You could bind Home and End to send-keys these sequences

I tried this:

    bind-key -n Home send Escape "[H"
    bind-key -n End send Escape "[F"

But it doesn't work. Probably this square bracket should be escaped somehow?

This works:

    bind-key -n Home send Escape "OH"
    bind-key -n End send Escape "OF"

But scim or sc still do not see those then (they do see `^[[F` and `^[[H` when launched outside tmux, though)

I also recall there was this option, `set-window-option -g xterm-keys on`, but it also won't help?

**Comment by for-coursera** [comment]
@nicm 

Could it be that in a tmux window and in tmux popup HOME and END send different sequences?

![](https://i.imgur.com/HLMkEQY.png)

This is the same tmux session, tmux window in the background, and tmux popup in the foreground.

**Comment by nicm** [comment]
send-keys bindings will not take effect when in a popup.

**Comment by nicm** [comment]
It seems to me like you should configure your applications to recognise
tmux's sequences (or read them from terminfo) rather than trying to change
what tmux sends.

**Comment by for-coursera** [comment]
@nicm , 

Unfortunately, those really aren't **my** applications :)

But yes, I do agree with your point that these problems should be solved from other end, and anyway the issue is resolved, thanks for your help.

Just wanted to clarify, are there any plans to make send-keys bindings work in popups? :)
