### ISSUE TITLE
split-window pane-size is not honored while splitting detached session's window

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3060]
### Issue description

This will help resolve a bunch of bugs of tmux-resurrect.

In my observation, ``tmux split-window -l <num>`` does not work correctly if the window being split is of a session that is started in detached state (with ``tmux new-session -d``. By does not work correctly, I mean ``<num>`` is not honored. This problem does not seem to occur if I split the window in an attached session.

Here's a test you can run yourself.

Run the following command in sequence:
```
tmux new-session -d
tmux split-window -v -f -b -l 1 -dP
tmux split-window -v -f -b -l 1 -dP
tmux split-window -v -f -b -l 1 -dP
.
.
.
tmux attach
```

Next kill the server, and try the same process on an attached session:
```
tmux new-session
tmux split-window -v -f -b -l 1 -dP
tmux split-window -v -f -b -l 1 -dP
tmux split-window -v -f -b -l 1 -dP
.
.
.
```

### Required information

Please provide the following information:

* tmux version: tmux next-3.4.
* Platform: Darwin arm64.
* $TERM: xterm-256color outside, tmux-256color inside.

**Comment by nicm** [comment]
Are you sure the size is the same when you create the session and when you
attach? Try "new-session -x- -y-".

**Comment by reportaman** [comment]
@nicm I see the problem. When a session is created in detached state ``-d``, tmux picks up size from ``default-size`` according to documentation. Then when such a session is attached using ``tmux attach``, its a different size, and panes  scale accordingly.

``new-session -x- -y-`` works only if I type it manually into terminal, it does not work if one were to create sessions from a script, like in tmux-resurrect.

**Comment by reportaman** [comment]
But, even if tmux is picking up the default size of 80x24, ``split-window -l1`` should allow 23 splits of the window. In my testing it varies, for my terminal size of 113x61, it allows only 12 splits, and then starts giving error on further attempts.

**Comment by nicm** [comment]
Each pane will be two lines so 12 is right for 80x24.

**Comment by nicm** [comment]
If you do splitw without -l1 twice the second one will be trying to split a
pane of 1 line high which isn't possible so it won't work. -d will not
change to the new pane so will be splitting the original pane again.

**Comment by nicm** [comment]
I mean with -l1 and without -d.
