### ISSUE TITLE
Question/feature: how to use display-message to print pane/window/session/server options?

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3061]
How to use ``display-message -F "<format>"``  to print pane/window/session/server options? Is there a special character combination to precede it with? If not, please consider adding.

There doesn't seem to be a modifier to say what kind of option we want displayed: https://github.com/tmux/tmux/wiki/Formats#summary-of-modifiers

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/Formats#options-and-environment-variables

**Comment by reportaman** [comment]
Given tmux allows that, I thought it would be worthwhile... thanks

**Comment by nicm** [comment]
I'll put a modifier to specify on the todo list but your best bet now is to use different names.
