### ISSUE TITLE
Mouse on by default

### ISSUE THREAD

**Issue by OlafvdSpek** [tmux/tmux#3063]
Could mouse support be enabled by default?

```
tmux 3.2a
Linux unknown
screen and linux
```

**Comment by OlafvdSpek** [comment]
Are there no parts of mouse support that don't have downsides / drawbacks?

**Comment by nicm** [comment]
If tmux turns it on, terminal mouse won't work at all, tmux will get all mouse events.

tmux can't turn it off when it is idle, so if people kill their ssh by doing `~.` in ssh, it is guaranteed to be left on and cause trouble.
