### ISSUE TITLE
OSC 133 (shell integration / semantic prompt) support

### ISSUE THREAD

**Issue by vimpostor** [tmux/tmux#3064]
It would be good if tmux supported OSC 133, which is a control sequence that specifies where the prompt ended, and where the output of the executed program starts and ends.
This can then be used for some really helpful features, such as automatically scrolling to the beginning of the output of the last shell command, cycling between the last prompt inputs or selecting the entire output of the last ran command.

The spec can be found here: https://gitlab.freedesktop.org/Per_Bothner/specifications/blob/master/proposals/semantic-prompts.md
An example terminal emulator that implements this feature is wezterm: https://wezfurlong.org/wezterm/shell-integration.html

I am mainly interested in the OSC 133 part, the OSC 7 part can be considered a separate issue.

Is this something that you would be willing to accept into the tmux codebase? If so, I can implement this myself in the near future.

This control sequence has to be supported from the shell, for example in the case of zsh one could use [powerlevel10k](https://github.com/romkatv/powerlevel10k) and enable it by setting `POWERLEVEL9K_TERM_SHELL_INTEGRATION=true`.

**Comment by nicm** [comment]
BTW tmux has supported OSC 7 since f3dc38dcae472286c7d7c2708e4dbfe70a6c2d57, but we do not currently do anything with it apart from make it available in a format variable.

**Comment by vimpostor** [comment]
I agree, the main selling point is being able to jump between the last commands. Other stuff like selecting the entire last output could easily be added later.

For cycling between the last commands I would add the following new commands (not sure if they should have a keybinding by default).
- `previous-command` (or maybe name it `previous-prompt` alternatively): Goes to the beginning of the previous command in history relative to the current position in copy-mode. If copy-mode is not currently active, enter copy-mode and go to the beginning of the last command.
- `next-command`: Go to the next command in history relative to the current position in copy-mode.

Both would position the view such that the prompt of the respective command is the first line visible in the window (at the top of the window).

**Comment by nicm** [comment]
If you add them as copy mode commands, then a key binding can be:
~~~~
copy-mode; send -X jump-to-previous-command
~~~~

**Comment by nicm** [comment]
I'm closing to close this for the moment but feel free to ask here if you have any further questions, or open a PR if you have code you want me to look at. Thanks!

**Comment by vimpostor** [comment]
Yes I will send a patch soon, don't worry I haven't abandoned the idea, just a little busy at the moment.
