### ISSUE TITLE
Feature Request: Kill last session

### ISSUE THREAD

**Issue by ktprograms** [tmux/tmux#3067]
Hi, could a `-l` option be added to the `kill-session` command, which will kill the last (most recently used) session?

Or is there already a way to do this that I haven't found?

Thanks!

**Comment by ktprograms** [comment]
On Tue Feb 15, 2022 at 9:15 PM +08, Nicholas Marriott wrote:

Hi, thanks for the reply!

> You could do something like:
>
> ~~~~
> if -F '#{client_last_session}' { kill-session -t "=#{client_last_session}:" }
> ~~~~

I added this key binding to my tmux config, but when I use the binding,
I get this error: "Can't find session: #{client_last_session}".

bind-key -T prefix	C-x	'if -F "#{client_last_session}" { kill-session -t "=#{client_last_session}:" }'

I looked in the tmux man page, and I can't find any reference to this
style of format string with = at the front and a : at the end.

**Comment by nicm** [comment]
Oh yeah sorry it needs to be:
~~~~
bind x if -F '#{!=:#{client_last_session},}' { run -C "kill-session -t '=#{client_last_session}:'" }
~~~~
Because `if-shell` will not expand the `client_last_session`, you need `run-shell` to do that.

Look under `COMMANDS`:
 
>If the session name is prefixed with an ‘=’, only an exact match is accepted (so ‘=mysess’ will only match exactly ‘mysess’, not ‘mysession’).

The `:` is not strictly necessary since it is a `target-session` but it makes it clear it is a session and not a window.

**Comment by ktprograms** [comment]
Thanks, that binding works, but I still think it would be more convenient if `kill-session` had a `-l` option.

**Comment by nicm** [comment]
I don't think it would fit very well because the last session is a client property (there is no last session if you detach), and it doesn't seem like something many people would need.

**Comment by ktprograms** [comment]
On Wed Feb 16, 2022 at 7:42 PM +08, Nicholas Marriott wrote:
> I don't think it would fit very well because the last session is a client property (there is no last session if you detach), and it doesn't seem like something many people would need.

The reason I originally requested this feature is because you can switch
to the last session with "switch-client -l", and I don't mind if
"kill-session -l" would also have "no last session" messages like
switch-client does.

Although it seems like "kill-window" doesn't have a "-l" flag either, so
it should probably be added to all the kill commands that it makes sense
for, if this feature gets implemented.

**Comment by nicm** [comment]
I don't think very many people need a quick way to kill the last window or session they were using, so I am not convinced this is very useful. For anyone who does want it, it is easy enough to script.

**Comment by ktprograms** [comment]
Ok, sure.

I'll close this issue then.
