### ISSUE TITLE
feature request: "add option to refresh-client to send osc52 response to a specified pane" was: osc52 read response not passed through

### ISSUE THREAD

**Issue by derbroti** [tmux/tmux#3068]
### Issue description

Tmux does not pass through the osc52 read response.
When issuing a passthrough read sequence: `printf '\ePtmux;\e\e]52;c;?\a\e\\'`, the response is grabbed by:
https://github.com/tmux/tmux/blob/df681390a6861b6a77d4623baf46d0a435729003/tty-keys.c#L681 
But shouldn't it pass the response through as well?

In my workflow I have `set-clipboard` set to `external` so tmux sets the clipboard on `copy-pipe` when run locally and I use a `copy-command` with an osc52 handling script when working through ssh.
The problem is that reading the clipboard does not work though ssh as tmux does not pass through the read response.

As a workaround, I surrounded that whole switch with an: 
`if (options_get_number(global_options, "set-clipboard") == 2)`.

### Required information

* tmux version tmux next-3.4.
* Platform Darwin arm.
* xterm-256color / tmux-256color.

**Comment by nicm** [comment]
tmux does not necessarily forward any escape sequences from the terminal, whether or not it understands them itself. In this case, how could it know this is a response to your query? It doesn't inspect the contents of the passthrough sequence.

**Comment by derbroti** [comment]
The distinction would be how I have set the `set-clipboard` option. In my mind "external" means, that I take care of it, so passing it through would make sense?

**Comment by derbroti** [comment]
But that is in regards to setting it, reading is not covered by the manual.

Ok, is it right to say that "external" means to not touch tmux buffers? 
Manual: "[...] ignore attempts by applications to set tmux buffers."

If so: what would be a sensible response to reading the clipboard - right now, "external" and "off" both set tmux buffers as a response to a osc52 read sequence.

**Comment by nicm** [comment]
You can't reliably use the passthrough escape sequence to query the external terminal, it is intended to work one way only. tmux doesn't look inside it so it has no way to know what you asked for or where to send the reply.

You're right that you shouldn't be able to make it set the clipboard using the passthrough sequence. tmux should probably remember if it issued the query and ignore responses if it did not, 

Really passthrough should be controlled by an option and off by default TBH.

**Comment by derbroti** [comment]
What scenarios can you think of where it would not be reliable? 
("it works for me", so I have not spend time checking any pitfalls) 

A passthrough option would be great!

**Comment by derbroti** [comment]
Oops, yeah, I misunderstood.

Ok, but the other part of your response: would "[...] ignore responses if it did not." mean to drop the response or to let the print through?

**Comment by nicm** [comment]
I think it should drop it. If you use the passthrough sequence then tmux has no way to know that you requested it, so as far as it knows the terminal sent it this stuff out of nowhere.

**Comment by derbroti** [comment]
That, unfortunately for me, makes sense.

Let me try a different route:

Would you be against giving "refresh-client" an option, like "-l" but to not store the response in a paste-buffer but to simply print it to stdout?

**Comment by nicm** [comment]
By "print to stdout" do you mean "send to a specific pane"? That would be fine, because then tmux would know both the client to request and the pane to send the result to.

It would also perhaps be nice to add an extension of OSC 52 that does something similar to this (maybe a `T` or something in the clipboard specifier). tmux would know the originating pane, but it would have to send to all attached clients with that pane (maybe only when the pane was in the current window?), so the application could get multiple responses.

It's a pity there is no way for a terminal to tell us when the clipboard changes, or tmux could keep it in sync automatically (it could have a special buffer for each client).

**Comment by nicm** [comment]
`display-message -p` does send to the client's stdout, but this would be more like `send-keys` or `paste-buffer` which write into a pane.

**Comment by nicm** [comment]
Try this please: [tmux-osc52-send.diff.txt](https://github.com/tmux/tmux/files/8157242/tmux-osc52-send.diff.txt)

This allows a pane argument to be specified to `-l`, for example `refresh-client -l %0`.

It sends the clipboard as an OSC 52 reply sequence; I am not really sure if that is best or it would be more useful to just send it as plain text (like `paste-buffer`).

**Comment by derbroti** [comment]
Thanks!

I can make the tmux server freeze completely with:

Starting from a clean slate (newly started server, no .tmux.conf):

- splitting the first window twice
- from command mode run, one after the other:
- - refresh-client -l %0
- - refresh-client -l %1
- - refresh-client -l %2
- 'select next pane in current window' a few times 

-> server does not respond, client freezes (attaching a new client does not work) 

[tmux-client-71351.log](https://github.com/tmux/tmux/files/8161554/tmux-client-71351.log)
[tmux-server-71353.log](https://github.com/tmux/tmux/files/8161555/tmux-server-71353.log)

**Comment by derbroti** [comment]
As for plain text or not: unless one can also specify the clipboard (the Pc parameter) in the request, the encoded version of the reply has no advantage.

**Comment by derbroti** [comment]
Note to self: think before posting :)

You are absolutely right! So is has to be the encoded version.

**Comment by nicm** [comment]
Does the problem still happen with this (I was not deleting the event when the reply arrived): 
[y.diff.txt](https://github.com/tmux/tmux/files/8176244/y.diff.txt)

Note I applied the arguments.c changes so you will need to either preserve them from the last diff or wait until GitHub syncs them up in a few hours.

**Comment by derbroti** [comment]
Does not crash anymore, but it returns the sequence with \033\\ instead of \007 although the if
`(ictx->input_end == INPUT_END_BEL)` in input.c should have, right? 
(I am surely missing something but I don't really understand how the INPUT_END_BEL enum works in the first place).

The logs show:
` 1646317165.014966 /dev/ttys001: keys are 39 (\033]52;;IHJlYWQgLXJzIC11MCAtZCQnXGEnIDwg\a)`

What I get is `^[]52;;IHJlYWQgLXJzIC11MCAtZCQnXGEnIDwg^[\` which is not nicely parsable with read.

**Comment by nicm** [comment]
No if you use `refresh-client -l` you will always get an ST ending.

**Comment by derbroti** [comment]
Ok, that's fine :) I can still parse it with `read` I just made a silly mistake earlier.

**Comment by derbroti** [comment]
It works fine - there is one thing: if the clipboard content is too large or rather the `escape-time` setting is too short the reply will be dumped into the requesting pane / or when executed from command mode into the currently active pane, not the specified one.

Not sure if this is fixable but it feels like I would rather receive an error than getting some pane flooded.

Btw: I read everywhere that there is a hard limit of 100k bytes for the encoded osc52 reply - this is arbitrary, right? 
-> I tested with "extremes" like 1M raw clipboard and 10s escape-time and it worked fine in my modified iTerm and vanilla Alacritty.
I found this [https://lists.suckless.org/dev/1708/32021.html](https://lists.suckless.org/dev/1708/32021.html) but there it also looks like "some round numbers".

**Comment by nicm** [comment]
There is no standard limit on size AFAIK, tmux will not accept escape sequences from applications that are more than 1 MB (the remainder will be discarded) or that take more than 5 seconds (the parser will reset at this point so anything new will be parsed from the ground state).

tmux will not handle OSC 52 responses that take more than 5 seconds to arrive (it will forget it had requested it), or that exceed `escape-time` (default 5 seconds).

We need some limit and these do not seem too low.

**Comment by derbroti** [comment]
> You will need to make sure your `escape-time` is large enough to accept the entire response, in theory we could spot the opening of OSC and extend the time but I don't plan to do that now.

This can be done manually, so it is fine - I am just worried a bit about guessing a too short escape time but going "really large" should also be fine.

but to be sure: the 5 seconds limit is a hard extra limit or defined by the `escape-time`? 

1 MB sounds reasonable - same question: this is a hard and non-configurable limit, right?

**Comment by nicm** [comment]
They are all hard limits except escape-time.

**Comment by nicm** [comment]
I have applied this to OpenBSD now, will be in GitHub later. Thanks!
