### ISSUE TITLE
Detached and not attachable

### ISSUE THREAD

**Issue by stroborobo** [tmux/tmux#307]
Might be a similar issue to #298, but I can't reproduce it unfortunately and it happens only once a week or so:

I'm disconnected from the server (pretty sure it's not done by me accidentally) and cannot attach again.

```
[detached (from session foo)]
> tmux attach
no sessions
> tmux ls
no server running on /private/var/folders/_l/q7lyqn4577d05ykp5nr4k8v40000gp/T/tmux-502/default
> ps aux | grep tmux
bo                871   0.0  0.4  2565604  69700   ??  Ss    3Feb16   8:05.31 tmux attach
```

How do I get some useful debugging information out of this?

tmux 2.1 with libevent 2.0.22 on OSX 10.11.3, installed via brew.

**Comment by nicm** [comment]
OS X plays silly buggers with TMPDIR, either run tmux from master where we don't use TMPDIR or set TMUX_TMPDIR.

**Comment by stroborobo** [comment]
Thanks so much, I'll do that! And thank you for building this great tool as well! :)
