### ISSUE TITLE
How to ensure that the tmux configurations of different users on a server are independent of each other

### ISSUE THREAD

**Issue by yougerli** [tmux/tmux#3071]
### Issue description

How to ensure that the tmux configurations of different users on a server are independent of each other

when I changed the prefix from "ctrl+b" to "ctrl+x" in my tmux session, other session's setting changed too! That confused me a lot!
### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by reportaman** [comment]
@yougerli I guess by server you mean a shared machine, not "tmux server". In that case you can make the copy of existing config file, make your changes to it, and load it using ``tmux -f ~/path/to/personal/config``. Here's an excerpt from ``man tmux``:

```
     -f file       Specify an alternative configuration file.  By default, tmux
                   loads the system configuration file from
                   /opt/homebrew/etc/tmux.conf, if present, then looks for a
                   user configuration file at ~/.tmux.conf,
                   $XDG_CONFIG_HOME/tmux/tmux.conf or ~/.config/tmux/tmux.conf.

                   The configuration file is a set of tmux commands which are
                   executed in sequence when the server is first started.  tmux
                   loads configuration files once when the server process has
                   started.  The source-file command may be used to load a file
                   later.

                   tmux shows any error messages from commands in configuration
                   files in the first session created, and continues to process
                   the rest of the configuration file.
```

**Comment by yougerli** [comment]
> @yougerli I guess by server you mean a shared machine, not "tmux server". In that case you can make the copy of existing config file, make your changes to it, save it in a personal directory and load it using `tmux -f ~/path/to/personal/config`. Here's an excerpt from `man tmux`:
> 
> ```
>      -f file       Specify an alternative configuration file.  By default, tmux
>                    loads the system configuration file from
>                    /opt/homebrew/etc/tmux.conf, if present, then looks for a
>                    user configuration file at ~/.tmux.conf,
>                    $XDG_CONFIG_HOME/tmux/tmux.conf or ~/.config/tmux/tmux.conf.
> 
>                    The configuration file is a set of tmux commands which are
>                    executed in sequence when the server is first started.  tmux
>                    loads configuration files once when the server process has
>                    started.  The source-file command may be used to load a file
>                    later.
> 
>                    tmux shows any error messages from commands in configuration
>                    files in the first session created, and continues to process
>                    the rest of the configuration file.
> ```

yes, we use a shared machine, but config is relevant to each other. I try the `tmux -f pathToMtyConfig`, but not works. New session started with "tmux -f " still has same config with other session.

**Comment by yougerli** [comment]
> @yougerli
> 
> If you and your team members want to use tmux on a shared machine, but its not required that all of you use the same "tmux server", then each user can have their own tmux server. For instance you can start tmux using `tmux -f pathToMyConfig -L newTmuxServerSocketName`. To make things simple you could enforce a policy in your team to have `tmux -f pathToMyConfig -L username`, that way everyone always works on their own instance of tmux, and the name of their server socket is easier to remember.
> 
> Settings from config file are loaded each time a new server is started, and is common for all users using the server afaik +@nicm. Perhaps you could make a feature request to @nicm if every user can opening a session can load a personal copy of settings without affecting the server settings.
> 
> Note: You will have to specify the socket name for all the usual commands like `tmux -L newTmuxServerSocketName attach` instead of `tmux attach`. Check `man tmux` for more info.

It works! I just need different tmux server with other users, and `tmux -f pathToMyConfig -L username` helps me to do that! Thanks!

**Comment by yougerli** [comment]
@reportaman 
It works! I just want different tmux server with other users and `tmux -f pathToMyConfig -L username` helps me to do that!
Thanks!

**Comment by krader1961** [comment]
@yougerli: Note that you don't need the `-f pathToMyConfig` unless your users are not using *~/.tmux.conf* as their personal config file. You only need the `-L` flag.
