### ISSUE TITLE
Feature: add a format variable socket_name

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3072]
### Issue description

Currently to get socket name one needs to run ``>> basename $(tmux display-message -p -F "#{socket_path}")``. That is well and fine. Though that doesn't work for plugins that ask user for format string for certain configurations. This would also compliment code that uses ``-L <socket_name>`` instead of ``-S <socket_name_with_path>``. Though am not sure what happens if the user mixes ``-S`` in some command with ``-L`` in another command, from the documentation:

```
     -S socket-path
                   Specify a full alternative path to the server socket.  If -S is specified, the
                   default socket directory is not used and any -L flag is ignored.
```

**Comment by nicm** [comment]
What's wrong with `#{b:socket_path}`?

**Comment by nicm** [comment]
Yes correct `-L` is just a convenience for people who want to run many tmux servers rather than using sessions which I do not particularly encourage now.
