### ISSUE TITLE
Outputting to a small, borderless popup crashes tmux

### ISSUE THREAD

**Issue by bcgraham** [tmux/tmux#3073]
### Issue description
A popup without borders with a height of 2 crashes tmux if it tries to output to the terminal:
```
tmux popup -B -h2 'printf foo'
```
The above crashes, while the below works:
```
tmux popup -B -h3 'printf foo'
```

This was reproduced on the latest build from master, using both fish and zsh.

* tmux version (`tmux -V`).
```
me:~> tmux -V
tmux next-3.4
```
* Platform (`uname -sp`).
```
me:~> uname -sp
Darwin i386
```
* $TERM inside and outside of tmux (`echo $TERM`).
outside:
```
me:~> echo $TERM
xterm-256color
```
inside:
```
me:~> echo $TERM
tmux-256color
```
* Logs from tmux (`tmux ki
[tmux-client-39488.log.gz](https://github.com/tmux/tmux/files/8098663/tmux-client-39488.log.gz)
[tmux-server-39490.log.gz](https://github.com/tmux/tmux/files/8098664/tmux-server-39490.log.gz)
[tmux-out-39490.log.gz](https://github.com/tmux/tmux/files/8098665/tmux-out-39490.log.gz)
ll-server; tmux -vv new`).

**Comment by nicm** [comment]
This should be fixed now (when GitHub syncs up) by this change. Thanks!
~~~~
--- popup.c     16 Feb 2022 18:55:05 -0000      1.45
+++ popup.c     22 Feb 2022 11:01:33 -0000
@@ -690,7 +690,7 @@ popup_display(int flags, enum box_lines
        }
        pd->border_cell.attr = 0;

-       screen_init(&pd->s, sx - 2, sy - 2, 0);
+       screen_init(&pd->s, jx, jy, 0);
        colour_palette_init(&pd->palette);
        colour_palette_from_option(&pd->palette, global_w_options);
