### ISSUE TITLE
Feature: enable -F format string option to show custom information for panes in display-panes command

### ISSUE THREAD

**Issue by poetaman** [tmux/tmux#3074]
### Issue description

Currently display-pane shows the pane size on the top right corner of the panes. It would be nice to have a way to specify a format string just like for many other commands that would print custom information for each pane. As a corollary bonus, tmux would figure out the size of longest line in the format string, and pad every line of format string to be right aligned, as shown in example below.

Example:
```
tmux display-panes -F "pane_id: #{pane_id}\n pane_pid: #{pane_pid}\n ..."
```

would print:
```
_______________________________________________
                              pane_id: 1      |
                              pane_pid: 23434 |
                              ...             |
                                              |
                                              |
                                              |
_______________________________________________
```

**Comment by ThomasAdam** [comment]
Considering we've already got other commands to display custom information, and now popup windows, etc., is this really going to be useful?

**Comment by reportaman** [comment]
@ThomasAdam Yes in the sense that all that if user has 4 panes open, it will show all the 4 pane's information together. It will be helpful while debugging tmux plugins at the very least.

Haven't tried sending stdout to all tmux panes together, maybe that is possible. A problem or intend behavior today with sending stdout to tmux pane is it doesn't respect coloring done with escape sequences (and ends up showing escape sequences instead). Maybe one can write a script that cycles through panes of current window, and sends stdout to that prints all the info. Though that won't overlay over the pane contents either like display-panes does...

**Comment by nicm** [comment]
Added this to todo list, although I don't think I would make it support newlines.

**Comment by afh** [comment]
I'd like to learn more about your use-case, @poetaman. Could elaborate a bit more how you'd like to use the proposed feature and what additional value it would bring over `list-panes`, e.g.:


```bash
% tmux list-panes -F 'pane_id: #{pane_id}, pane_pid #{pane_pid}'
pane_id: %107, pane_pid 44545
pane_id: %108, pane_pid 44663
```

**Comment by nicm** [comment]
It's just an option to control the text shown when you do `display-panes` in the top right of the pane, currently this is fixed to the pane size.

**Comment by afh** [comment]
Right, so this is very similar to `list-panes` yet the information presented is presented at the top of each pane, which places the information visually closer to its origin.

What are your objects towards supporting newlines, @nicm? I noticed that other format strings in tmux do not support these either…

**Comment by nicm** [comment]
It would be much more complicated to make newlines work and it seems unnecessary here.

**Comment by nicm** [comment]
You would need to add `display-panes-format` and store its value in `cmd_display_panes_data`, then change `cmd_display_panes_draw_pane` to use `format_draw` to a temporary screen (you can make it the full width of the pane) and then copy that to the terminal with `tty_draw_line` (similarly to how `menu_draw_cb` draws to a temporary screen). This would replace the `rbuf` drawn with `tty_putn`.

**Comment by nicm** [comment]
The default `display-panes-format` can be something like `#[align=right fg=#{?pane_active,#{display-panes-active-colour},#{display-panes-colour}]#{pane_width}x#{pane_height}`.

**Comment by nicm** [comment]
It's probably a bit late to ask you to test this but here it is: [disp-panes.diff.txt](https://github.com/user-attachments/files/28686710/disp-panes.diff.txt)

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
