### ISSUE TITLE
Feature: expose the counter variable for upcoming session_id

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3078]
### Issue description

Currently one can construe the session_id of the next session one is to create in a script by iterating over the session_ids of all the sessions and finding the max. Given the information is already there in tmux, it would be nice to have it exposed as a variable like ``session_id_next`` or ``session_id_max`` one could use in ``-F`` format strings. Thanks.

> Note: new-session command with -PF can return session_id of newly created information, though I am looking for that information before the session is created.

**Comment by nicm** [comment]
Iterating over all sessions is not a reliable way to do this because sessions may have been killed. I have added `next_session_id`, will be in GitHub when it syncs. Thanks!
