### ISSUE TITLE
Top and bottom status bar

### ISSUE THREAD

**Issue by stamate** [tmux/tmux#308]
Hello,

Is it difficult to have two status bars? A top one for the tabs and a bottom one that will show machine stats? Is this already done? If so please let me know where to look.

Best wishes,
Cosmin

**Comment by ThomasAdam** [comment]
Not yet.

**Comment by sanscore** [comment]
@stamate I had a similar idea which I reported a few days ago, #301. There's an existing TODO for this feature, https://github.com/tmux/tmux/blob/master/TODO#L134

Apparently, it's been there a while. https://github.com/tmux/tmux/commit/d6b5b644b83ad2a3cfc28dda0ae9af537da8b7f2
