### ISSUE TITLE
Way to manually set pane_current_command??

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3080]
### Issue description

I recently figured that using zsh hooks it is possible to get the command I enter in shell. It would be nice to be able to apply that to ``pane_current_command``, that way all tmux plugins that use that get the most accurate value. For CWD, there is OSC 7 sequence that works like charm, is there a sequence for "current command"? Or another way to set this Tmux variable ``pane_current_command``??

**Comment by nicm** [comment]
No there is no way to set it - use path, title or a user option.

**Comment by reportaman** [comment]
Yep, I am using user option. This was more of a feature request, maybe I made it sound like a question :)
