### ISSUE TITLE
SIGHUP won't exit tmux client if in control mode

### ISSUE THREAD

**Issue by revintec** [tmux/tmux#3084]
### Issue description

running `tmux attach` and send `SIGHUP` to it would cause it to exit cleanly, as expected.
however running `tmux -CC attach` in control mode and send `SIGHUP` to it nothing happens.

is this desired behavior? this would cause tmux client to be leftover when its controlling terminal already exits.
```
ps aux|grep 1465605
revin    1465605  0.0  0.0  25816  3380 pts/39   Ss+  22:17   0:00 tmux cnc

kill -HUP 1465605

ps aux|grep 1465605
revin    1465605  0.0  0.0  25816  3380 pts/39   Ss+  22:17   0:00 tmux cnc
```

### Required information

* tmux next-3.2
* linux debian 4.4.0-33.bm.1-amd64 1 SMP Wed, 24 Jan 2018 15:50:58 +0800 x86_64 GNU/Linux
* $TERM is screen

**Comment by nicm** [comment]
This should be fixed now by this change, it will be in GitHub as soon as it syncs up. Thanks!
~~~~
--- client.c    27 Aug 2021 17:25:55 -0000      1.156
+++ client.c    28 Feb 2022 09:34:41 -0000
@@ -530,7 +530,7 @@ client_signal(int sig)
        if (sig == SIGCHLD)
                waitpid(WAIT_ANY, &status, WNOHANG);
        else if (!client_attached) {
-               if (sig == SIGTERM)
+               if (sig == SIGTERM || sig == SIGHUP)
                        proc_exit(client_proc);
        } else {
                switch (sig) {
