### ISSUE TITLE
Feature: cycle back to "user layout" or add new command or command option to that does dry-run of layout select and asks for user confirmation

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3087]
After cycling through predefined window layouts, the next cycle doesn't begin from "user's layout". "user's layout" could be defined as a layout that was either not selected from predefined layouts, or has changed since?

Advantage: User can quickly cycle through layouts to see how it would look like & they like it without having to manually save the current layout and restore it. Ideal scheme would work with just one keybinding ``<tmux-prefix><Space>``. One could write a tmux or shell script and give it a special key binding, but that then takes an extra key binding, which is a precious resource.

ALTERNATIVE, perhaps maybe preferable and easier:

Another way to achieve this could be to have a new tmux command that just does a dry-run to show how the new layout would look like without actually changing to it till user confirms... It could also be an argument to the current command to cycle through layouts ``select-layout`` like ``select-layout -c`` where ``-c`` asks for user confirmation if user hits a key like escape while cycling through predefined layouts, maybe...

**Comment by reportaman** [comment]
Another way to implement this could be to have a layout select dry-run and not commit to it unless user confirms?

**Comment by nicm** [comment]
`select-layout -o` was added to allow easy revert to the previous layout, so you probably script this with something like:
~~~~
bind x { selectl -n; command -1p 'Keep?' { if -F "#{==:%%,y}" "" "selectl -o" } }
~~~~

**Comment by reportaman** [comment]
Ok thanks!
