### ISSUE TITLE
Tmux not copying buffers set via other programs into system clipboard

### ISSUE THREAD

**Issue by leelavg** [tmux/tmux#3088]
- Versions and related info (empty lines added manually), all are installed via package manager `dnf`
```
$ uname -sp; nvim -v | head -1; tmux -V; kitty -v; echo $TERM; tmux show -s | rg -i terminal

Linux x86_64

NVIM v0.6.0

tmux 3.1c

kitty 0.21.2 created by Kovid Goyal

xterm-kitty

default-terminal tmux-256color
terminal-overrides[0] "xterm*:XT:Ms=\\E]52;%p1%s;%p2%s\\007:Cs=\\E]12;%p1%s\\007:Cr=\\E]112\\007:Ss=\\E[%p1%d q:Se=\\E[2 q"
terminal-overrides[1] screen*:XT
terminal-overrides[2] screen-256color:Tc
```
- Corresponding options (empty lines added manually)
```
$ grep 'set clipboard' ~/.dotfiles/init.vim; grep 'clipboard' ~/.dotfiles/tmux.conf; grep 'clipboard_control' ~/.dotfiles/kitty.conf 

set clipboard+=unnamedplus                 " Use providers (~tmux) clipboard capabilities

set -g set-clipboard on

clipboard_control write-clipboard write-primary no-append
```

- Actual behaviour:
  - Yank text into unnamedplus register from vim inside a tmux session
  - Automatically yanked text should be available in system clipboard via tmux buffer

- Expected behaviour:
  - Yanked text is available in tmux buffer but not on system clipboard
  - It should be available on system clipboard as well

- What's working:
  - Only buffers copied via tmux in selection mode is available in system clipboard
  - Same behaviour in local and remote machines

- Logs:
  - [tmux.tar.gz](https://github.com/tmux/tmux/files/8145958/tmux.tar.gz)

- Additional Info:
  - As mentioned above, yanked text from vim is indeed available in tmux buffer
  - Even though setting tmux clipboard to `on` tmux doesn't seem to be allowing buffers be sent to terminal
  - `$TERM` values are changed to make kitty, tmux and neovim do not complain, so is this causing the issue? I want to set `xterm-kitty` throughout, however doing so raises red flags from neovim 😅

**Comment by nicm** [comment]
There are no clipboard set sequences in this server log, it looks like you may be using the `load-buffer` command instead. This does not set the external clipboard. Only using the OSC 52 sequence or copying from copy mode yourself will send OSC 52 to the external terminal.

**Comment by leelavg** [comment]
- ack, maybe `yy` of neovim is using `load-buffer` of tmux but not the OSC 52 sequence then.
- what can I do to confirm this behaviour? ie, `load-buffer` is being used but not OSC 52

**Comment by nicm** [comment]
It needs to use `load-buffer -w` (since 37b1600d9cf7076498760372dcc20f021e4c181a) to make tmux set the clipboard as well.

**Comment by leelavg** [comment]
- ack, thanks for the responses
- the referenced issue isn't part of tmux that I'm running, maybe upgrading to it when it's available via dnf would fix this
- will take a look how neovim doing this if possible

**Comment by nicm** [comment]
You could force it to add `-w` using an alias:
~~~~
set -s command-alias[99] 'load-buffer=load-buffer -w'

**Comment by nicm** [comment]
But yes you will need to to upgrade tmux to 3.2a or later.

**Comment by leelavg** [comment]
@nicm thanks a lot for prompt responses
- updated tmux to 3.2a in local and remote machines
- rather than making changes in neovim as per https://github.com/neovim/neovim/issues/14545 followed above set command to always use OSC 52 seq
- I just need to be cautious about what I copy from internal systems at the end 😅 
- bottom line, the feature is working and very smooth, thanks again 😄

just curious, is the num in brackets specifies weight or something of that sort? issue can be closed.

**Comment by nicm** [comment]
No it is just an array, I used 99 because it is well above the defaults but you can use any number.
