### ISSUE TITLE
send-keys command with shift modifiers doesn't work?

### ISSUE THREAD

**Issue by dtreiter** [tmux/tmux#309]
Is it possible to use a shift modifier with the send-keys command?

For example:
```$ tmux send-keys S-a```

I would expect this to send a capital 'A'. This doesn't seem to send any key events though. The other modifiers and special keys work fine.

Just skimming over this seems like shift modifiers should be supported:
https://github.com/tmux/tmux/blob/dc42c35f1f04d3bd431c52dde0906965c6db2d6c/key-string.c#L130-L134

**Comment by nicm** [comment]
S-a and A are different keys as far as tmux is concerned. If you want A,
send A.

Is it possible to use a shift modifier with the send-keys command?

For example:
$ tmux send-keys S-a

I would expect this to send a capital 'A'. This doesn't seem to send any
key events though. The other modifiers and special keys work fine.

Just skimming over this seems like shift modifiers should be supported:
https://github.com/tmux/tmux/blob/dc42c35f1f04d3bd431c52dde0906965c6db2d6c/key-string.c#L130-L134

—
Reply to this email directly or view it on GitHub
<https://github.com/tmux/tmux/issues/309>.

**Comment by nicm** [comment]
Shift modifiers are only really useful where there is a defined key, such
as S-Tab or function keys in some terminals.

**Comment by dtreiter** [comment]
@nicm S-a was just an example. S-Tab doesn't work for me either.

**Comment by dtreiter** [comment]
If it's useful, my test case has been:

1. Start tmux
2. Open Emacs inside tmux and run `M-x describe-key`. This will capture key events and display them. *(Note that I'm very confident the issue isn't with this. The key events don't work in other programs as well)*.
3. From a different terminal, run `tmux send-keys S-Tab`

**Expected behavior:** Presses Shift+Tab (recognized as `<backtab>` by Emacs).
**Actual Behavior:** Does nothing.

I have done this on Mac OS X with both Terminal.app and iTerm2. If I instead try something like `tmux send-keys M-Tab` it works fine. Also, pressing Shift+Tab directly in the terminal works fine.

I'm mostly trying to determine if this is some issue on my end, possibly a misunderstanding of how's tmux's shift modifier should work, *or* if there's a possible bug in tmux.

Thanks for the help.

**Comment by nicm** [comment]
Actually S-Tab generates a key called BTab so you should use that not
S-Tab.

**Comment by dtreiter** [comment]
Thanks for the tip. That resolves my biggest use case.

I'm still kind of confused on what the `S-` modifier is supposed to do. I realize that the way terminals handle shift is complex for certain keys though. Also, my use case is likely uncommon.

I'm fine if you want to close this issue now.

Thanks

**Comment by nicm** [comment]
It is isn't really that complex, basically there are no shift keys apart
from function keys and arrow keys.

tmux pretends like there is such a key as S-a internally, because it
needs to pretend Shift is a general modifier to represent real keys like
S-F1.

But actually there is no key S-a, it is just A. And no key S-Tab, it is
just BTab, and so on.

The same really applies to Ctrl, in almost all terminals there is no
such key C-S-a, it is just the same as C-a.

And for example things like C-" don't exist, but it makes more sense for
tmux just to treat it as if Ctrl can be applied to any key even if it
doesn't actually exist

**Comment by dtreiter** [comment]
Thanks for the explanation. Is there any reason it doesn't make sense to have the send-keys command internally map things like S-a to A, or S-Tab to BTab?

I have a program which compiles strings down to tmux's send-keys syntax and it's essentially doing this conversion itself - which I'm fine with. But it seems like it could also make sense for tmux to do?

I realize this may come across as a feature request, but I'm also fine with how it works now. My initial concern when opening the issue was that I had difficulty using things like S-Tab, but BTab works just fine.

**Comment by nicm** [comment]
I think there is no need to do that and it would be a maintenance
overhead for no reason.

**Comment by dtreiter** [comment]
Thanks for your help with this!
