### ISSUE TITLE
Erratic behaviour when accessing scrollback buffer and copy mode

### ISSUE THREAD

**Issue by ioogithub** [tmux/tmux#3092]
### Issue description

**Short description:** I am randomly being kicked out of copy mode and losing my scroll back buffer history.

**Detailed Description:**
- I am seeing erratic behavior when interacting with the scroll back buffer and copy mode. At first I thought it was some of my mouse settings but I see it with keyboard only interactions as well.
- When I enter copy mode and start to scroll back inside the buffer (cursor moving up the screen) I am unexpectedly kicked back to the command line mode. If I try to enter the copy mode again right away the buffer history has been cleared [0/0].
- A few times I entered the buffer after being kicked out and saw it was expectantly large [0/291] when I was expecting [0/65]
- A few times I generated 65 lines of scroll back buffer and I saw [0/0] when entering copy mode.
- I am seeing this strange behavior on both my local system (Tmux 3.0a) and remote hosts accessed with ssh (tmux 3.1c).
- I can reproduce this behavior with Konsole and a second terminal "Cool Retro Terminal" installed for testing.
- For the purpose of this test, I have cleared my .tmux.config file except for one line: `set -g default-terminal "screen-256color" and started with `tmux kill-server`.

**Test 1:**
0. create a text file with 50 lines of text (50lines.txt)
1. Start tmux `$ tmux`
2. Enter a command that will produce several lines of scrollback buffer (`$ cat 50lines.txt`)
3. Enter copy mode to interact with scrollback buffer (`prefix + [`)
4. Scrollback buffer displays [0/65] 
5. Press the` [Up Key]` and start to scroll back to the first line:
6. `[Up Key] [Up Key] [Up Key]`
7. after the 3rd press of the up key, I am kicked out of copy mode and returned to the command line.
8. Try to reenter the scrollback buffer (`prefix + [`)
9.  Scrollback buffer displays [0/0] 
10. Scrollback buffer has been lost.

**Test 2:**
11. repeat steps 2-6
12. This time I make it to line 20 before being kicked out.

**Test 3:**
13. repeat steps 2-6
14. This time I made it to line 1, I start to scroll back down` [Down Key]` 5 more lines before being kicked out. There appeared to be a slight shudder around the command line this time.

**Test 4:**
15. repeat steps 2-3
16. This time I briefly see `[0/65]` then I am kicked out of scrollback history before pressing any keys.

**Test 5:**
17. repeat steps 2-3
18. This time I see `[0/0]` even thought I just generated the same number of of scrollback buffer lines as the other tests. I can arrow key to the top of the screen but the buffer is lost.

**Test 6:**
15. repeat steps 2-6
16. This time I briefly see `[0/265]` ...where did all this buffer history come from? Same results as previous tests, scroll though a few tiles and kicked out of copy mode back to command.

**Analysis:**
There doesn't seem to be a pattern to how long I can stay in the scrollback buffer before being kicked out and losing the scrollback history. In one test the buffer was cleared before I could even enter copy mode and start scrolling back.

I have tried to distill the issue down as much as possible to illustrate the issue. This issue happen with any interactions with copy mode and scrollback buffer not just text output displayed with `cat`. The issue is even more prominent when using mouse mode, after a few clicks of the scroll wheel, I am kicked out of copy mode and the scrollback buffer history is lost `[0/0]`.

I am a new user so it is hard for me to know the difference between normal and expected behavior, configuration issues and bugs). Either way what I am seeing is an issue because it is impairing my ability to use tmux to interact with my processes and data in a reliable and deterministic way.

### Required information
Please provide the following information:
**Local system:**
tmux 3.0a
Linux x86_64
inside: xterm-256color
outside: screen-256color
terminal: Konsole  21.12.2
alternate terminal for testing: Cool Retro Term

**Remote system:**
tmux 3.1c
"Linux Unknown " (raspberry pi 4b arm64), Debian buster
inside: screen-256color
outside: xterm-256color
terminal: Konsole 21.12.2

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-out-1593004.log](https://github.com/tmux/tmux/files/8150222/tmux-out-1593004.log)
[tmux-server-1593004.log](https://github.com/tmux/tmux/files/8150223/tmux-server-1593004.log)
[tmux-client-1593002.log](https://github.com/tmux/tmux/files/8150224/tmux-client-1593002.log)

**Comment by nicm** [comment]
There is no sign of you entering copy mode in this log, are you sure you sent a log where you reproduced the problem?

Do you have `escape-time` set to 0? Are you using tmux on a slow connection? It is possible that tmux is interpreting the `Escape` in the `Up` key sequence as a real `Escape` which exits copy mode.

Does the problem go away if you put this in .tmux.conf and restart tmux entirely? You will need to use `q` to exit copy mode instead of `Escape`:
~~~~
unbind -Tcopy-mode Escape
unbind -Tcopy-mode-vi Escape

**Comment by ioogithub** [comment]
@nicm Thank you for taking time to assist with this issue. I appreciate it.

> There is no sign of you entering copy mode in this log, are you sure you sent a log where you reproduced the problem?

Sorry I misunderstood the log taking procedure. I have attached log files for new tests below.

> Do you have `escape-time` set to 0?
- No, for the initial tests I reported, I used a .tmux.config file with only a single option: `set -g default-terminal "screen-256color"`.
- I also see the problem with my regular .tmux.conf file. I do not have this option set. 

> Are you using tmux on a slow connection?

No: I can see the problem locally, all tests were conducted on a local copy (tmux 3.0a) although I see the same problems when accessing a remote host on the lan (tmux 3.1c).

> It is possible that tmux is interpreting the `Escape` in the `Up` key sequence as a real `Escape` which exits copy mode.

When I enable mouse mode (`set-option -g mouse on` ) and access copy mode by scrolling the mouse wheel, I also see the same problem. Does mouse mode send the same key sequences?

Also, there doesn't seem to be any patterns between the number of key presses (or mouse scroll wheel clicks) before I am kicked out of copy mode and sometimes the buffer is cleared before any key presses at all.

> Does the problem go away if you put this in .tmux.conf and restart tmux entirely? You will need to use `q` to exit copy mode instead of `Escape`:

I conducted all new tests attached with the following tmux config:
```
set-option -g mouse on 
set -g default-terminal "screen-256color"
unbind -Tcopy-mode Escape
unbind -Tcopy-mode-vi Escape
```
I see the same issues with the new config.

I have included 7 sets of logs. Here is the test setup:

1.Start tmux server:` tmux kill-server; tmux -vv new`
2. Generate scrollbakc history: `cat 60lines.txt`

**Test 1:**
3. waited around 5 seconds then entered: `C-b [`
4. The result: [0/0] of buffer history. The buffer was gone before I could even access it.

**Test 2:**
3. entered `C-b [ ` immediately
4. [0/16] buffer lines displayed. Less than a second I am kicked out of copy mode and back to the command line. 

**Test 3:**
3. entered `C-b [ ` immediately
4. [0/0] buffer lines displayed.
Note: similar result to test 1 (buffer gone immediately) only I did not wait before entering copy mode.

**Test 4:**
3. `C-b [` immediately
4. [0/16] buffer lines displayed
5. I was able to [Up Key] many times to the top line in the buffer, as soon as I pressed [Down Key] to scroll back down I was kicked back to command line.

Test 5:
3. entered `C-b [` immediately
4. I lasted much longer this time. I was able to scroll to the top of the buffer , scroll all the way down and scroll 1/2 way to the top again before being kicked out. When I entered copy mode again immediately after the buffer history was lost [0/0]

**Test 6:**
3. entered `C-b [` immediately
4. This time I was able to scroll up the screen to around line 6 in the buffer before being kicked out of copy mode.

**Test 7:**
3. For this test I used the mouse scroll wheel to enter copy mode:
4. [ScrollUp] shows [0/16] lines of buffer mod
5. [ScrollUp][ScrollUp][ScrollUp] at the top of the buffer
6. [ScrollDown][ScrollDown][ScrollDown] to the bottom of the buffer
7. [ScrollUp][ScrollUp] kicked out of copy mode.
8. buffer shows [0/0].

**Analysis:**
- The timing here was slightly different than the tests from the first post. In the first set the most common result I saw was being kicked out of copy mode after pressing [Key Up] 3-5 times then losing the buffer history. This time, the most common result is that I would entered copy mode and see an empty buffer `[0/0]` right away.

**Other observations:**
- Does the scrollback buffer automatically delete itself upon exiting copy mode? I noticed that I can simple generate scrollback history, then enter copy mode` [0/16],` immediately exit. When I enter again the buffer is gone `[0/0]`. Is this expected behavior?
- I saw in a doc on github somewhere (can't find it now) that I can see the buffers with `C-b =`. When I issue this command I do not get anything. Do I need to enable any options in tmux.conf to see this?

- Logs from tmux (tmux kill-server; tmux -vv new).
[tests.tar.gz](https://github.com/tmux/tmux/files/8155618/tests.tar.gz)

**Comment by nicm** [comment]
You have a script of some kind that is running `tmux clear-history`. I cannot tell what the script is called but it is run with working directory `/home/user/Scripts` and appears to be run without a tty:
~~~~
1646063695.457678 new client 0x5648a555fa20
...
1646063695.458137 client 0x5648a555fa20 IDENTIFY_CWD /home/user/Scripts
...
1646063695.462578 client 0x5648a555fa20 name is client-1759208
1646063695.462614 peer 0x5648a5540e40 message 200
1646063695.462652 cmd_unpack_argv: argv[0]=clear-history
~~~~

**Comment by ioogithub** [comment]
> You have a script of some kind that is running `tmux clear-history`. I cannot tell what the script is called but it is run with working directory `/home/user/Scripts` and appears to be run without a tty:

Thank you. I found it with `sudo ps aux | grep 'Scripts'`
user       143562  0.0  0.0   9500  3168 ?        S    Feb26   0:05 /bin/bash /home/home/Scripts/externalIP.sh

When I was generating the server logs I did see that clear-history but I don't have enough tmux experience yet to interpret the meaning.

I was attempting to use the panes feature of tmux to build a server dashboard. In one pane I had a simple one line script which was fetching the external IP address of the server then clearing the history so as to not generate a history for that pane.

As I was developing the script I started and stopped it several times with Ctrl +C.

I would like to prevent this from happening again. Do you know how the script run in this way can become detached from a tty? I was also implementing tmux-resurrect and tmux-continuum as the same time. Is it possible resurrecting a session that is running this script can cause it to become detached from a tty? Is there a special way to terminate scripts in tmux to ensure they terminate?

Regarding the `tmux clear-history` command, is it intended to clear the local pane where it was run or is it global? How is it possible that this running script was affecting every tmux session, even after the tmux server was killed and restarted. It was even affecting  tmux sessions running on tmux servers on remote hosts.

Thanks for the troubleshooting assistance!

**Comment by nicm** [comment]
clear-history will use the same rules to figure out the target as all
commands. If you don't specify it is likely to use the active pane in the
current window.

I don't know why it was not killed, presumably you did not have it trap the
right signals and the shell ignored them.

**Comment by ioogithub** [comment]
> clear-history will use the same rules to figure out the target as all commands. If you don't specify it is likely to use the active pane in the current window.
What rules decide which active pane should be cleared?
I looked at specifying the pane using the -t option however this would likely cause an issue if I rearrange the panes as it will no longer be clearing the correct pane. Is it possible to pass a variable to the `tmux clear-history -t` argument to grab the active pane?

I have been doing some additional testing. The script is currently running with with `pts/7`:
`user        5948  0.0  0.0   9632  3704 pts/7   S+   14:23   0:00 /bin/bash /home/user/Scripts/externalIP.sh
`
If I start counting panes where window 0, pane 0 = pts1 then pts/7 corresponds to the correct pane.

I am still seeing the scrollback buffer being cleared when the script is running but only on certain panes: 
- window 0 pane 0
- window 1 pane 2
- window 3 pane 1

I have a total of 12 panes.

If I exit the script and confirm it is not running with `ps aux | grep 'Scripts'` the scrollback buffer on those 3 panes ceases to be cleared. If I start the script again, it clears those specific panes.

**Comment by nicm** [comment]
use pane id which will not change no matter where the pane is moved

**Comment by ioogithub** [comment]
> use pane id which will not change no matter where the pane is moved
Okay so I tried using pane id. I wrote a small script that writes the pane id to the current pane and then runs clear-history with the #{pane_id} variable.

What I  see is that #{pane id} is displaying the id of the currently selected pane not the pane where the script was run. Here is the script:

```
trap 'exit 130' INT
while true;
    do
        tmux run "echo '#{pane_id}'"
        tmux clear-history -t $(tmux run "echo '#{pane_id}'")
        sleep 5s
    done
```

- I run the script in pane 1
- I generate bash history in pane 2.

Here is the output:

```
$ ~/Scripts/test.sh
%1
%2
%1
%2
%1
%2
```

When I click on pane 1 the output is %1
When I click on pane 2 the output is %2
When the output is  %2, that window's history is cleared.

I may be fetching pane id wrong, I tried many different variations to try to pass the #{pane_id} variable to `tmux clear-history -t` but nothing worked except the `tmux run "echo '#{pane_id}'"`

If this test is valid then it could explains my initially reported issue.

**Comment by ioogithub** [comment]
I noticed a user on stackoverflow commented:

`#{pane_id} is the id of the currently active pane and not the pane in which the script was run. `

on this page: https://stackoverflow.com/questions/25340314/is-there-a-way-to-get-the-active-pane-id-for-tmux-panes

This would seem to agree with the output of my script however the thread is over 6 years old so it may not be current.

Could you clarify?

**Comment by nicm** [comment]
Use TMUX_PANE or pass pane_id into the script when you start it rather than looking it up every loop (which will be the same as letting clear-history find it itself).

**Comment by nicm** [comment]
The behaviour of always choosing the active pane was originally to make things like:
~~~~
tmux splitw \; splitw
~~~~
Work as most people would expect (that is, the new pane is split as well as the original pane). It is no longer necessary for this case because we now update the target after `split-window`. But it would probably still cause more trouble to change than it is worth...
