### ISSUE TITLE
Configurations on Windows 11 under MSYS2

### ISSUE THREAD

**Issue by drazde** [tmux/tmux#3095]
### Config on MSYS2 (or Git Bash)
I'm trying to configure tmux under MSYS2 or Git Bush but also the simplest config seems doesn't work.

*.tmux.conf*:
```
# Change default prefix to Ctrl-a
unbind C-b
set-option -g prefix C-a
```

### Information
With *Git Bash*
```
$ uname -sp && tmux -V && echo $TERM
MINGW64_NT-10.0-22000 unknown
tmux 3.2a
screen
```
Inside tmux ```$TERM=screen```
Outside tmux ```$TERM=xterm```

**Comment by krader1961** [comment]
Tmux isn't supported as a native MS Windows app. From the readme: "This release runs on OpenBSD, FreeBSD, NetBSD, Linux, macOS and Solaris." In theory it could be made to run on Windows but so far no one has done the necessary work.

**Comment by drazde** [comment]
@krader1961 Ok sorry, I don't read ini file (mea culpa...). 
MSYS2 contains tmux and works good enough for waht I see.

**Comment by nicm** [comment]
Look here: https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
