### ISSUE TITLE
Window Indices / Numeration

### ISSUE THREAD

**Issue by RiiLoad** [tmux/tmux#3096]
Yesterday when configuring and playing around tmux I have found a bug (or missing feature).
When I have at least 2 windows open and then kill a window (or multiple windows) that is not the last one the window indices stay the same and do not change.
For example if I have 2 windows open then kill the window 0 the only window left is window 1.
Why is the window 1 not renamed then to window 0. The user will expect the first window to be window 0.
That way you always have to read the indices when changing windows.
Also for example if I have at least 3 windows open and kill some windows in between of them you get a gap in the numeration.
Wouldn't it be much more intuitive for the user when all window indices are named in 1 increments beginning at 0?

I understand that this may be faster for the processor in some case when you have for example 100 windows then kill window 0 all the other 99 will need to be renamed wich can be slow down the runtime. This could be solved by using a If statement.
Only change the indices if less than n windows open.

<img src="https://abload.de/img/tmux-bugdrjqu.png">
Now I kill window 0 
<img src="https://abload.de/img/tmux-bug-2zyjs5.png">
Window 1 is not renamed to 0 this irritates the user as you would expect the first window to be window 0
<img src="https://abload.de/img/tmux-bug-3hcjk9.png">
Create a bunch of windows
<img src="https://abload.de/img/tmux-bug-4gwj63.png">
Killing all windows in between
Window 9 is not renamed to window 1 which is not intuitive and irritates the user
<img src="https://abload.de/img/tmux-bug-59oj5t.png">
Now when creating new windows it first fills the gap  The windows 1-8 are left of window 9 even though the are newer.
They should be right of window 9 because they are newer. 
This can be fixed by updating the indices if a window is killed
0 1 2 3 4 5 6 7 8 9 ........

**Comment by derbroti** [comment]
To give another perspective: if I do task X in window 3, I want to be able to blindly switch back to task X by selecting window 3, regardless if I open or close any other window.

What if I first close window 1, then my old window 3 becomes 2, now I have to remember it being 2, then I close window 0, now my window moved again.

**Comment by nicm** [comment]
https://man.openbsd.org/OpenBSD-current/man1/tmux.1#renumber-windows
