### ISSUE TITLE
Feature: user configurable padding in panes

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3097]
It would be nice to on-the-fly configurable padding around contents in tmux pane. Rationale: While working, one might run different commands in a tmux pane. Most of them do not provide a way to add border padding to the the tty they run in. For instance one might have a wide pane while they are running command that prints a lot of log, later in the same pane they might  wants to run some command like man/lynx that is paragraph centric and a desirable width for paragraphs is much smaller. Changing stty settings doesn't seem to work well in my testing, resizing the terminal (if its a full width pane) or breaking the pane in chunks and rejoining them to get wide pane for the next command is a little painful...

Proposal: A possibility could be to add a flag to ``resize-pane`` command that does an internal resize by padding it without affecting the window layout (size and position of panes).

**Comment by reportaman** [comment]
@nicm Even just for the width?? IMHO heavy users of tmux might come up with similar requests in future. How about put it in long-term feature?

**Comment by nicm** [comment]
As you are the first person to suggest it so far it seems unlikely it is something in high demand.

I don't really think we should support borders wider than one characters either.

At some level it is up to the applications you use how they display what they want, I don't think tmux needs to be too keen to override that.

**Comment by reportaman** [comment]
Maybe no one ever gave it a thought, and there's always someone who comes up with an idea first. If there were some kind of poll, and heavy users of tmux do look at tmux polls then they might support the idea. I couldn't find any external program that would provide a virtual width inside an existing tty...

Tmux is a productivity tool, and enabling it here would benefit all applications -- not sure if application developers (hundreds if not thousands of them...) would update their apps.

**Comment by reportaman** [comment]
Also, not sure if this helps, but seems like there is new posix interface regarding windowsize: https://www.austingroupbugs.net/view.php?id=1151#c3856

I found it from the following footnote:
> A standard interface is slated to be included in an upcoming version of POSIX, with the tcgetwinsize and tcsetwinsize functions, easily implementable as wrappers to ioctl(TIOC[SG]WINSZ). See [here](https://www.austingroupbugs.net/view.php?id=1151#c3856) for details.

src: https://unix.stackexchange.com/questions/580362/how-are-terminal-information-such-as-window-size-sent-to-a-linux-program

**Comment by nicm** [comment]
seems a bit silly to me but there you go

**Comment by reportaman** [comment]
@nicm Your message ends with "there you go", did you forget pasting something after that?

**Comment by nicm** [comment]
no, that was the end. i mean "posix are always inventing stupid stuff and
there isn't much we can do about it".

**Comment by ThomasDickey** [comment]
Sure: all they had to do was bless the ~35-year-old code (see my [summary](https://invisible-island.net/ncurses/ncurses.faq.html#handle_resize)).

**Comment by reportaman** [comment]
@ThomasDickey Does this mean that that the feature requested in this thread is now possible somehow for a terminal multiplexer like tmux? or after Oct 2022?

> these related standardization features are expected to be in [P1003.1](https://standards.ieee.org/project/1003_1.html) issue 8 (October 2022):

As a sidenote, for someone starting to dive deeper in how ttys work, is there any book or manual other than reading manpages? I haven't come across any book that explains ttys.

**Comment by krader1961** [comment]
> As a sidenote, for someone starting to dive deeper in how ttys work, is there any book or manual other than reading manpages? I haven't come across any book that explains ttys.

The book known as APUE: "Advanced Programming in the UNIX Environment" is, at least historically, a must own if you're interested in topics like this.

I'm also a strong thumbs down on this proposed enhancement. As has been stated previously it adds a lot of complexity for a feature that almost no one will utilize. It definitely would not "benefit all applications". If you need a specific window/pane size you should simply set that size. Abusing a mechanism like pane padding to make the size smaller is gross. I fail to see why making the width smaller to force commands like `man` or `lynx` to alter how they render their output is desirable. And I say this as a grey beard who started programming for a living in 1979 (back when punch cards were still in widespread use).

**Comment by reportaman** [comment]
@krader1961 Please don't mention age/experience as a reason for any rational choices. Its gross, and can be considered age based bullying depending on the part of the world you come from. Sorry, there is no correlation between age and sound choices, or else we wouldn't see the war that was waged on Ukraine just recently by someone (Putin) who is 69 years old.

Also, software we write today is to fulfill the aspirations of new generation that has different ideas and different ways of solving problems. You personally don't want to use a feature doesn't make it gross either. I would avoid such judgements. Talk technology here, not your personal feelings.

**Comment by nicm** [comment]
this posix extension will not make any difference, it is just adding a new
way to do something that is already there

it is not as simple as just clamping TIOCWINSZ, if it was you could write
an LD_PRELOAD to do it, but there are escape sequences affected by the
width which applications will use, for example line wrapping, erasing. tmux
would need to make sure both that these happen at the right place  and that
the excess space in the pane remains blank

this is fairly complicated and i just don't see this is something that is
terribly useful. tmux already allows to create your own empty pane taking
up whatever space you like, as well as setting a limit on the window size,
and programs like man already obey COLUMNS or have additional flags (mandoc
has -O width)

**Comment by nicm** [comment]
what i am saying is - if you are proposing to do the work then, as ever, if
it is done in the right way, i will review it and probably accept it, but i
do not see any prospect of doing it myself
