### ISSUE TITLE
Question: How to emit OSC 7 sequence for tmux without doing :cd from neovim

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3098]
How to issue a OSC 7 sequence to tmux without actually changing directory with :cd in neovim. Rationale: I want to update the pane_current_path of tmux with every BufEnter, but not change the current working directory in nvim. I tried ``:call printf(’\e]7;%s\e’,’/Users/reportaman’)``, but it doesn’t change tmux pane_current_path. Changing directory with :cd in neovim does correctly change the pane_current_path option in tmux.

Note: pane_current_path is not directly settable by the user, it can only be set using something like OSC 7 escape sequence.

> I asked this same question at neovim discourse: https://neovim.discourse.group/t/how-to-emit-osc-7-sequence-for-tmux-without-doing-cd-from-neovim/2126. Though getting an answer here is more helpful as this would apply to other applications running inside tmux as well.

**Comment by nicm** [comment]
This seems like a vim question. tmux can't control how you make vim send
escape sequences.

**Comment by reportaman** [comment]
@nicm Sure I'll ask at vim GitHub repo. What you can perhaps answer is 1) where to send those sequences to? 2) is there any format requirement, or my format looks ok? I used a bunch of methods. including echo, printf, system from within vim, and nothing seems to work. My guess is its not going to the right place...

**Comment by nicm** [comment]
try writing it to /dev/tty

you can check the format by sending it to stdout using printf outside vim

**Comment by nicm** [comment]
the terminator should be either \007 (\g) or \033\\ (\e\\)

**Comment by reportaman** [comment]
@nicm I tried echoing from the shell, none of them worked.

This is totally unrelated to vim, try sending sequence from shell in one of the panes of tmux to tty of another:

```
echo -e '\e]7;/usr/local\e\\' >&/dev/ttys001
tmux display-message -p -t 0:1.1 -F "#{pane_current_path}"
```

> I tried same sequence without -e flag, and that doesn't work either. Can you please try and report sequence of bash or zsh commands that would work?

**Comment by nicm** [comment]
the escape sequence changes pane_path, not pane_current_path

**Comment by reportaman** [comment]
Ok, the reason I go confused is this: In vim/nvim doing ``:cd ~/some/path`` changes pane_current_path, while pane_path remains the same. Not sure why is that so given documentation does not say pane_current_path is changeable by applications, but it does for pane_path.

Try opening vim and run this command before and after doing ``:cd ~/some/path``

```
tmux display-message -p -t 0:1.1 -F "#{pane_path}...#{pane_current_path}..."
```

You will see pane_current_path changes, pane_path doesn't.

Echoing works well and changes pane_path, not sure why some app is changing pane_current_path while some other would change pane_path?

**Comment by nicm** [comment]
tmux works out pane_current_path itself, vim does not change it

**Comment by reportaman** [comment]
@nicm: Just out of curiosity, how does tmux know that directory has changed in vim?

**Comment by nicm** [comment]
It looks at /proc/PID/cwd on Linux, other mechanisms on other platforms,
look at osdep_get_cwd in osdep*.c.

**Comment by reportaman** [comment]
Ok thanks, I will :)
