### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by seyerian** [tmux/tmux#3099]
In the line just above this header: https://github.com/tmux/tmux/wiki/Getting-Started#killing-a-session-window-or-pane

I believe that

> Other than using client mode, the detach-client _**flag**_ has a -a flag to detach all clients other than the attached client.

should read

> Other than using client mode, the detach-client _**command**_ has a -a flag to detach all clients other than the attached client.

**Comment by nicm** [comment]
Nice one, fixed, thanks!
