### ISSUE TITLE
Error 'bad key' with prefix Ctrl + \ 

### ISSUE THREAD

**Issue by ElijahLynn** [tmux/tmux#31]
I have been using Ctrl + \ for a couple years now. Just in the past few days my prefix key stopped working and I get this error when opening Tmux. 

`/home/elijah/.tmux.conf:2: bad key: C-\\ `

**Comment by nicm** [comment]
This is an awful bug report. It just spontonaeously stopped working? Did you upgrade tmux? What versions?

**Comment by ThomasAdam** [comment]
Put it in single quotes, or double escape it.

**Comment by ElijahLynn** [comment]
@nicm, sorry, I had the version in the title and then was going to move it to the body but ended up deleting it. I am running 2.0.

I think it was upgraded recently but I don't pay attention that much to my updates since I get updates all the time from Ubuntu's repos which is how I installed it.  Yes, it just spontaneously stopped working.

Thanks @ThomasAdam, I previously had `set -g prefix C-\\` and just changed it to  set -g prefix 'C-\' and it works now!
