### ISSUE TITLE
combine commands in vi-copy mode

### ISSUE THREAD

**Issue by divramod** [tmux/tmux#310]
Hey, i try to automate select-line, copy-selection and sending this to another pane in vi-copy mode.

in the end, it should look like that:

```
bind-key -t vi-copy o select-line \; copy-selection \; copy-pipe "xargs -I{} tmux send-keys -t 1 ';call OpenTestFile(\"{}\")' Enter"
```

i have vim running in -t 1 and wrote a function OpenTestFile which is doing the rest of the work.
But when i load .tmux.conf i get an error:

```
.tmux.conf:133: not enough arguments
```

could someone help me out here?

**Comment by nicm** [comment]
You can't chain commands like that for mode key bindings.
