### ISSUE TITLE
Saving Sessions

### ISSUE THREAD

**Issue by aminam79** [tmux/tmux#3100]
I think it would be nice if there were an ability to save sessions and current `tmux` status.

For example, assume that I have 8 sessions, but I should reboot my device. Then after rebooting, I should make those sessions again, manual. But if I could save my sessions, then I could restore them easily.

I searched for this feature, but couldn't find it.

Does `tmux` support saving sessions ? If not, I think it would be welcomed.

**Comment by nicm** [comment]
I started working on this before long ago and it's very complicated and seems a little pointless since tmux can't restore the most important thing - what it running in the panes.

But there is https://github.com/tmux-plugins/tmux-resurrect which will do as much as it can.
