### ISSUE TITLE
Binding attach-session

### ISSUE THREAD

**Issue by boulderob** [tmux/tmux#3101]
This is really a question. I'm looking for some quick guidance.

When I manually do the following from within tmux

- `bindkey+:` to go to a command prompt in tmux
- followed by literally typing in `attach-session -t`

tmux presents me with a popup window to pick the current sessions and it switches the session.

I want to create a keybind map that basically automates all the typing up to and including entering in the final `-t` so that when i run the keybind, I'm immediately presented with that menu picker.  I'm basically trying to avoid having to type all the preliminary text so the map can take me straight to the picker or one `tab` key press away so i can switch my session.

In sum, how do you do you enter a "mostly finished command and stop without actually entering it"?  I can't get any of the following to work.  Command-prompt seems to require a "prompt" and ignores that literal `-t`.

```
unbind-key
bind-key a command-prompt "attach-session -t"
#bind-key a attach-session -t
```

Also, apparently my terminal setting is wrong as you can see in the bottom required information.  what should that be set to in 2022 on a macbook running bigsur assuming there is a defacto default answer?

Thanks

### Required information

 $ tmux -V
tmux 3.2a

 $ uname -a
Darwin MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

 $ `echo $TERM`
-bash: tmux-256color: command not found

**Comment by nicm** [comment]
it is not possible to trigger the completion menu from a key binding. maybe
you can use C-b s instead?

**Comment by nicm** [comment]
Use the -I flag to command-prompt.
