### ISSUE TITLE
Feature: Make jumping to last-prompt something we can implement

### ISSUE THREAD

**Issue by mohkale** [tmux/tmux#3102]
### Issue description

A common thing I'm finding I need more and more recently is the ability to jump to the last prompt in my current shell. This would be useful for example when you run a long command and it prints a lot of output, and you have to scroll to return to the start of it.

I'm not sure whether this would be better implemented in tmux itself (suppose tmux has an option `shell_prompt_regexp` which searches from the beginning of a line until the end of a users prompt) or whether tmux should be versatile enough that users can implement it themselves.

Atm I've got this rough implementation:
```
set -g @shell-prompt-regexp " " # Non breaking space, I put this at the end of my prompt.

bind M-k copy-mode\; send-keys M-k
bind -T copy-mode-vi -r M-k {
  send-keys -X start-of-line
  send-keys -XF search-backward "#{@shell-prompt-regexp}"
  send-keys -X cursor-right
}

bind M-j copy-mode\; send-keys M-j
bind -T copy-mode-vi -r M-j {
  send-keys -X end-of-line
  send-keys -XF search-forward "#{@shell-prompt-regexp}"
  send-keys -X cursor-right
}
```

but there's a few downsides to this approach:
1. There's no way to detect if a prompt search fails so there's no scriptable way to leave the cursor in a sensible place in this case.
2. There's no way to clear highlighting which I don't feel is necessary for this because my prompt is designed to be easily identifiable, and it always starts from the beginning of a line.
3. There's no way to restore the previous search string or intended search direction. If I search for `tmux` for example, and then realise I meant to find it from a few commands back, I can go-to the previous prompt like 5 times and then I hit `n` and it searches backwards to the next prompt where I'd really rather it just remembered the previous search string and direction.

I suppose you could simplify this issue as a request for tmux to support more generic motion commands. The current way to automate manually searching for things isn't ideal IMO.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux next-3.4
* Platform (`uname -sp`). Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`). tmux-24bit
* Logs from tmux (`tmux kill-server; tmux -vv new`).

Edit:

I've gottent a slightly more usable command for this now and added a regexp for both my own shell prompt and the default bash prompt you get with docker. Now we match from the beginning of the line all the way to the end of the prompt so it doesn't look as jarrring to have highlighting. I'd still like the ability to reset the search but for now this is pretty good :-).

```
set -g @shell-prompt-regexp "(^[^ ]+ )|(^\[[[:alnum:]]+@[[:alnum:]]+ .+\]# )"

bind M-k copy-mode\; send-keys M-k
bind -T copy-mode-vi -r M-k {
  send-keys -X start-of-line
  send-keys -XF search-backward "#{@shell-prompt-regexp}"
  # I have to use a subshell here because the width format specifier cannot
  # properly handle unicode prompt characters like λ or non-blocking spaces.
  if -F '#{!=:#{n:search_match},0}' {
    run-shell "sh -c 'tmux send-keys -F -N \${#1} -X cursor-right' -- #{q:search_match} >/dev/null 2>&1"
  }
}

bind M-j copy-mode\; send-keys M-j
bind -T copy-mode-vi -r M-j {
  send-keys -X end-of-line
  send-keys -XF search-forward "#{@shell-prompt-regexp}"
  if -F '#{!=:#{n:search_match},0}' {
    run-shell "sh -c 'tmux send-keys -F -N \${#1} -X cursor-right' -- #{q:search_match} >/dev/null 2>&1"
  }
}
```

**Comment by nicm** [comment]
I'm not at all clear what you are actually asking for by the bottom of this issue.

Jumping to shell prompt marked with the escape sequence is already on the todo list and also see this recent issue: https://github.com/tmux/tmux/issues/3064

**Comment by mohkale** [comment]
> I'm not at all clear what you are actually asking for by the bottom of this issue.

Sorry, I could've been a little clearer here :sweat:.

> There's no way to clear highlighting which I don't feel is necessary for this because my prompt is designed to be easily identifiable, and it always starts from the beginning of a line.

Basically a command to clear search highlights. Like vims `:nohlsearch`.

> There's no way to restore the previous search string or intended search direction.

+ Add a format code for inspecting the search direction (essentially which direction the `n` and `N` keys will go. For example `#{search_direction}` is 1 if `n` moves down the visible buffer and `0` otherwise.
+ Also allow setting both of these using `set-option`. For example atm I can't seem to `set -p pane_search_string "what the regexp was"`. It gives back `invalid option: pane_search_string`. This might be a bad idea since it would invalidate the existing search highlight if the pattern changes, maybe we should just clear it if the user tries to set that option.

> Jumping to shell prompt marked with the escape sequence is already on the todo list and also see this recent issue

Cool. I wasn't aware there was an OSC proposal for it. In which case I think that should be preferred to this issue :-).

**Comment by nicm** [comment]
Adding a format for `search_direction` is easy (add it in `window_copy_formats`).

I don't think we want options for these, instead the way to do it would be to have copy mode commands to change the search direction without searching and to set the search string that you could issue with `send -X`.

**Comment by mohkale** [comment]
> I don't think we want options for these, instead the way to do it would be to have copy mode commands to change the search direction without searching and to set the search string that you could issue with send -X.

Makes sense. How should we deal with highlights and trigerring a search when we set the search string? I don't think we should search forward or backwards when setting the search string. As for the highlights I'm fine with either clearing them or keeping the ones from before we set the search string.

**Comment by nicm** [comment]
They will probably need to be cleared, I can't remember whether the search string is used again or just saved for repeat search.

**Comment by mohkale** [comment]
> They will probably need to be cleared,

Great, I'll try to open a PR later this week :-).

**Comment by nicm** [comment]
I'm going to close this but if you have questions feel free to comment or to open a PR. Thanks!
