### ISSUE TITLE
tmux crash when passing TAB to "Prompt for window index to select"

### ISSUE THREAD

**Issue by Lonenso** [tmux/tmux#3103]
### Issue description
Press `CTRL-B` followed by `'` (to trigger Prompt for window index to select) and pass `<TAB>`

pass any letters followed by a `<TAB>` is OK.

[loom link](https://www.loom.com/share/954684e4c4e845f78b8b6a28e21a5695) 

PS: I was encountered the [same issue](https://github.com/tmux/tmux/issues/2749)  on tmux-3.2, after reading that, I tried `brew install --HEAD tmux`, and here I am.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux next-3.4, commit: f84f1c0
* Platform (`uname -sp`): Darwin i386
* terminal: iTerm2
* $TERM inside and outside of tmux (`echo $TERM`): both are xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-87337.log](https://github.com/tmux/tmux/files/8192312/tmux-client-87337.log)
[tmux-out-87339.log](https://github.com/tmux/tmux/files/8192313/tmux-out-87339.log)
[tmux-server-87339.log](https://github.com/tmux/tmux/files/8192314/tmux-server-87339.log)
* backtrace from lldb 
[backtrace.txt](https://github.com/tmux/tmux/files/8192333/backtrace.txt)

**Comment by nicm** [comment]
This shoule be fixed in OpenBSD now, will be in GitHub later. Thanks!
