### ISSUE TITLE
How do I map Shift + Enter to pass down to the terminal in Tmux?

### ISSUE THREAD

**Issue by Rofer11607** [tmux/tmux#3104]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

I have vim shift enter mapped to scroll down, however when I have a Tmux session open Tmux fails to pass the correct key code down to vim

In kitty:
cat, then press shift+ enter
Ouput:
"\x1b[13;2u"

in kitty, using Tmux
cat, the press shift+enter
nothing.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).
 Tmux 3.2a
Darwin arm
XTERM-KITTYjk

**Comment by nicm** [comment]
Try building from master and setting `extended-keys` to `always`.
