### ISSUE TITLE
place one status-bar at the top and one at the bottom?

### ISSUE THREAD

**Issue by bsferrazza** [tmux/tmux#3105]
I am looking to place one status-bar at the top and one at the bottom, but so far I have not seen any documentation on how or if this is possible. Though it appears from the screenshots of others that they've been able to accomplish this.

tmux 3.2a
Linux 4.18.0-240.1.1.el8_3.x86_64

**Comment by nicm** [comment]
no you can have status lines at top or bottom, plus one per pane at top or
bottom of each pane

**Comment by bsferrazza** [comment]
@nicm OK thank you for the prompt reply. Now that I think about it, that actually describes what I want after all. Are there examples on how to set the status-bar within a pane?

**Comment by reportaman** [comment]
@nicm 
1. For pane status bar it would be nice to have it as a per-pane option, currently ``tmux set -p pane-border-status top`` sets pane status for all panes in target window, as if it was a window option.
2. It would be nice to have this pane status line inside the pane's border. Having text as part of border lines is a little busy as a UI as there is no space between text of the pane above, and pane below.
