### ISSUE TITLE
Feature: suspend and reinstate specific or all keybindings for a pane -- i.e. enable application specify key-bypass

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3106]
During the course of running commands/using different TUI applications in the pane, one hits a situation where some default keybinding of an application conflict with user's tmux keybindings.

1) One workaround is to map all tmux keybindings to begin with a prefix like ``C-a``.
2) Another workaround is to remap the conflicting keybindings in the conflicting TUI applications config files.

1)) has similar ergonomic hazard as emacs's default keybindings do; 2) has multiple disadvantages: a) application creators put some thought in their default keybindings, we lose that built-in intelligence; b) depending on the key the work for maintaining keybindings in config files can be too much, we might as well have to create config files for apps we would otherwise not. For instance Fn keys in applications like htop, lynx, hackernews_tui, etc do something useful. I have bound some function keys to execute tmux scripts, but I would rather bypass those keys and pass them to a pane if htop, lynx, hackernews_tui are running in the focussed pane.

So the proposal is to have a way to suspend and reinstate certain or all keybindings in a pane. Bypassing all key bindings could enable a feature that with just one toggle-key one can either pass the keys directly to an application or let tmux catch & interpret them.

A more advanced version of this feature would allow user to specify key sets (groups), and then with a command suspend/reinstate them for a pane.

> Note: I call it suspend instead of unbind, because in the ideal world one would not have to do code duplication by calling bind key with the default binding that was specified in tmux config files. It might not even be possible to specify the bindings again using bind-key as they could be coming from different tpm plugins and would be hard to recreate if not impossible. Another way to look at the feature is that we set a filter to filter keys, when a filter is set, the keys in the filter are ignored by tmux and passed directly to a pane.

All/none toggle could also be seen as a way of making tmux a modal app like vim. In normal mode, tmux interprets keybindings to mean something and executes whatever user has bound them to using bind-key, in app mode tmux just passes the the keys directly to the app running in the focussed pane without executing what user had bound them to using bind-key. A variable that shows what's the current mode could be used to show the current mode in status line, just like vim enables. This extends the modes to 3: normal mode, copy mode, and app mode.

**Comment by nicm** [comment]
You can already do this either by using `if -F` and `pane_current_command` for individual keys or by using key tables for sets of keys.
