### ISSUE TITLE
Feature: Run both global hook, and pane hook if set

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3108]
I recently hit a situation where I already had the global hook for pane-focus-out set but also wanted to run another pane-focus-out hook only for a specific pane. In my testing it seems like if pane-focus-out is set globally, and is also set for a pane, then the only one that actually runs is the pane's local pane-focus-out hook.

There already is a -a (append) option for set-hook. If I set a global hook, and then do ``set-hook -a -p`` for the same hook, it should run both when hook_pane equals that pane? Or maybe add another flag to the command to achieve this.

Test Sequence:
```
tmux set-hook -g pane-focus-out <action-a>
tmux set-hook -ap pane-focus-out <action-b>
tmux set-hook -ap pane-focus-out <action-c>
```

The above sequence should run all of: \<action-a\>, \<action-b\>, \<action-c\>.

Additionally, 
```
tmux set-hook -g pane-focus-out <action-a>
tmux set-hook -p pane-focus-out <action-b>
tmux set-hook -ap pane-focus-out <action-c>
```

The above sequence can retain current behavior (which runs only \<action-b\>, and \<action-c\>).

**Comment by nicm** [comment]
We should change `set-hook -R` so you can use it to fire global hooks from non-global hooks, the patch in https://github.com/tmux/tmux/issues/2879 might do it, did you try it?

**Comment by reportaman** [comment]
@nicm What does -R mean for an event hook like pane-focus-out?

**Comment by nicm** [comment]
It means you can fire the global hook from a pane hook, or it would if it worked. You could do it now, just call the global hook something else.

**Comment by nicm** [comment]
I have fixed `set-hook -R` with user hooks. I do not see any point in running both pane and global hooks, it seems like you could just define a user hook and point both of them to it with `set-hook -R`.

It would be nice if `-gR` would run the global hook but it is very tricky to do so I think we can do without it.
