### ISSUE TITLE
tmux leaves zombies around

### ISSUE THREAD

**Issue by moosotc** [tmux/tmux#311]
Reproducer
$ tmux new-window true\&\;exec true; sleep 1; ps x | grep -c \[d]efunct; pkill -CHLD tmux; ps x | grep -c \[d]efunct
1
0

**Comment by nicm** [comment]
This is a side effect of using libutempter which puts in its own SIGCHLD handler; if the tmux child exits while utempter has its handler in, tmux will never get the SIGCHLD.

**Comment by moosotc** [comment]
Nicholas Marriott <notifications@github.com> writes:

> This is a side effect of using libutempter which puts in its own
> SIGCHLD handler; if the tmux child exits while utempter has its
> handler in, tmux will never get the SIGCHLD.
>

I do the above (more or less) in a script, my best bet, it seems it to
do a:
trap 'pkill -CHLD tmux' 0
or is there a better way?

-- 
mailto:moosotc@gmail.com

**Comment by nicm** [comment]
You can try this

diff --git a/window.c b/window.c
index a89b108..7a74afb 100644
--- a/window.c
+++ b/window.c
@@ -915,6 +915,7 @@ window_pane_spawn(struct window_pane *wp, int argc, char **argv,
 #ifdef HAVE_UTEMPTER
 	xsnprintf(s, sizeof s, "tmux(%lu).%%%u", (long) getpid(), wp->id);
 	utempter_add_record(wp->fd, s);
+	kill(getpid(), SIGCHLD);
 #endif
 
 	setblocking(wp->fd, 0);

**Comment by moosotc** [comment]
Nicholas Marriott <notifications@github.com> writes:

> You can try this
>
> diff --git a/window.c b/window.c
> index a89b108..7a74afb 100644
> --- a/window.c
> +++ b/window.c
> @@ -915,6 +915,7 @@ window_pane_spawn(struct window_pane *wp, int argc, char **argv,
>  #ifdef HAVE_UTEMPTER
>  	xsnprintf(s, sizeof s, "tmux(%lu).%%%u", (long) getpid(), wp->id);
>  	utempter_add_record(wp->fd, s);
> +	kill(getpid(), SIGCHLD);
>  #endif
>  
>  	setblocking(wp->fd, 0);
>

[..snip..]

Thank you. Think I'll stick with trap then; before the number of locally
modified (i.e. non distro/vanilla packages) grows out of proportion.

-- 
mailto:moosotc@gmail.com

**Comment by nicm** [comment]
Applied this anyway.
