### ISSUE TITLE
using tmux on ubuntu cloud image with no actual display

### ISSUE THREAD

**Issue by modyngs** [tmux/tmux#3111]
### Issue description
Hi,
I'm using Ubuntu cloud image on my openstack instance.
So i connect to my VM via Putty from windows!

Ubuntu CLoud image : https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img

So when i installed it via apt install tmux there is no ~/.tmux.conf file!!
and when i try to install it via git repo, it fails due to aclocal!

./autogen.sh: line 15: aclocal: command not found
aclocal failed

### Required information

Please provide the following information:

* tmux 2.6
* Linux x86_64
* I dont have Xterm! because of ubuntu cloud image!

**Comment by reportaman** [comment]
On macOS (I have aarch64 one), running autogen.sh always results in errors at config phase. Running in a git repo without autogen.sh, i.e. directly proceeding with ``./configure <arg>...`` works well.

**Comment by iiey** [comment]
Make sure the corresponding packages are installed. e.g.:
```sh
# ./autogen.sh: aclocal: not found
# ./configure: syntax error near unexpected token 'newline'.. PKG_CHECK_MODULES
# ./configure: libevent not found
# ./configure: ncurses not found
# make ../etc/ylwrap: line 175: yacc: command not found
sudo apt install autotools-dev automake pkg-config libevent-dev libncurses-dev bison
```

May take a look on *tmux wiki* installing from version control.
