### ISSUE TITLE
Difference in COLUMNS, LINES seen by shell-command of new-session, and new-window

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3112]
The value of environment variables COLUMNS and LINES seen by shell-command of new-session and new-window is different.

To reproduce:
1. start tmux (session 0)
2. do a vertical split
3. create session 1 in background with shell-command A (perform this from a pane of session 0 with ``new-session -d``)
4. create new window in background for session 1 with shell-command B (perform this from same pane of session 0 with ``new-window -d``)
5. read the values of environment variables COLUMNS and LINES seen by shell-command in A, B

For 3,4 one could add ``echo "$COUMNS, $LINES" >> ~/path/to/tempfile`` to the shell-command to print the values.

What is the difference?
Shell command for ``new-session -d`` sees width and height of pane of session 0 from which the command was executed. Shell command for ``new-window -d`` sees width and height of the entire client.

Not sure if this is intended or a bug...

**Comment by nicm** [comment]
tmux is not responsible for setting COLUMNS and LINES.

**Comment by reportaman** [comment]
But it is sending pane size for new-session and client size for new-window... the way I found this is while debugging a neovim issue. Neovim does not like window size change for some duration while launching. I was opening neovim in a "hidden pane" of a new window and swapping it with current pane. The race would not happen if new-window also saw current pane size for COLUMNS and LINES. The difficult hidden pane business... Currently the only solution seems to add a delay and send a sigwinch to neovim to bypass this race. The race wouldn't happen if there were a way to specify the virtual terminal size seen by shell-command (setting COLUMNS, LINES using -e or export doesn't work). Not sure if this happens with other apps too...

**Comment by nicm** [comment]
neovim and vim are both very bad at handling window size change, there is little tmux can do about this.
