### ISSUE TITLE
When `tmux kill-server` returns, are we sure the server is fully killed?

### ISSUE THREAD

**Issue by alexisfrjp** [tmux/tmux#3115]
I have a bash script killing an existing server and creating a new one right away.

```
tmux -L mysrv kill-server
tmux -L mysrv new-session -d
```

The `new-session` command doesn't always return 0, especially when my tmux has been running for a while. (lots of stdout I guess)
Also, the file `/tmp/XXX/mysrv` isn't automatically deleted.

Is that normal?

**Comment by nicm** [comment]
No there is no synchronization so the server may exist for a short while
after the command returns.

**Comment by alexisfrjp** [comment]
Is it a command working as a daemon? Or is it unrelated to tmux?
I couldn't find any mention of it in the manpage, I'll add a check after the kill-server.
Thank you.

**Comment by nicm** [comment]
I'm going to close this since it is working as expected but feel free to comment if you have questions or if you want to open another PR to improve this. Thanks!
