### ISSUE TITLE
[Feature request] Support systemd socket activation

### ISSUE THREAD

**Issue by ju1m** [tmux/tmux#3117]
### Issue description

Reopening https://github.com/tmux/tmux/issues/2398 because socket activation would enable to launch on-demand a [fully hardened and sand-boxed](https://wiki.archlinux.org/title/User:NetSysFire/systemd_sandboxing#Sandboxing_systemd_service_units) `tmux` (eg. to run a persisting `irssi`).
This is currently not possible with the usual `systemd-socket-proxyd` palliative [because](https://github.com/systemd/systemd/issues/22744) `tmux` uses `SCM_RIGHTS` [to get the file descriptor of the client's terminal](https://superuser.com/questions/358943/is-sharing-a-tmux-sockets-between-hosts-possible).

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.2a
* Platform (`uname -sp`).
Linux

**Comment by nicm** [comment]
Please see my reply to this recent issue: https://github.com/tmux/tmux/issues/3024

I will certainly accept changes that add systemd specific code by adding the code to a `forkpty-systemd.c` or `daemon-systemd.c` or `osdep-systemd.c` - this is how we support this kind of thing for macOS - but I don't intend to do any further work on systemd myself for the moment. 

There is a diff which does some systemd stuff in this comment and adds `--enable-systemd` here: https://github.com/tmux/tmux/issues/428#issuecomment-623491932.

Another thought is that Cygwin also does not support file descriptor passing and we work around that by reopening `/dev/tty` in the server process - perhaps a similar solution would work here?

Where are the systemd docs explaining this feature and the API? That would be useful if anyone does want to work on this.
