### ISSUE TITLE
status line have more than a line to display all windows

### ISSUE THREAD

**Issue by ask-github** [tmux/tmux#3118]
### Required information

Please provide the following information:
i have many windows, more than 30 windows for different work. is there a method that show all windows in two status line?

if there are two line window list. i can see all window and choose them easier

now in one window list line, some windows are hidden

![图片](https://user-images.githubusercontent.com/72971953/158401916-8ab41a77-9a05-4421-9a7e-a18a788eae8b.png)

thanks very much

* tmux version (`tmux -V`).
* tmux 3.2a
* Platform (`uname -sp`).
* linux
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by bew** [comment]
I'd rather suggest you to use multiple sessions for your various projects, and windows for various work on same project.
Then use the tmux cmd `choose-tree` to choose the session (and even the window/pane) to use.

Also, very important IMO to give names to your session & windows, having all of them named `bash` isn't useful AT ALL, I don't know how you can work with that..

**Comment by bfrg** [comment]
You can have up to 5 status lines, see options `status [off | on | 2 | 3 | 4 | 5]` and `status-format[] format`.

**Comment by nicm** [comment]
It would be possible to do this by changing the `W` operator in each `status-format` to only show a subset of windows on each status line, but yes sessions are a much better solution.

**Comment by ask-github** [comment]
> I'd rather suggest you to use multiple sessions for your various projects, and windows for various work on same project. Then use the tmux cmd `choose-tree` to choose the session (and even the window/pane) to use.
> 
> Also, very important IMO to give names to your session & windows, having all of them named `bash` isn't useful AT ALL, I don't know how you can work with that..

some days ago, i use two sessions for different project. but i find it is hard to switch.
for example.
i want to switch to session a, and window 5, first i need to know what is my current session. to determined whether need i switch session first. the choose-tree function also can use direct. but use up, down arrow to navigate is slow

in case of i use only one session. in any time, no need to care about which session is current.
i can goto any window use shortkey of choose tree, and then press 123...9abcd....z. it is very fast. this progress is no need to know the status of current.

**Comment by ask-github** [comment]
> It would be possible to do this by changing the `W` operator in each `status-format` to only show a subset of windows on each status line, but yes sessions are a much better solution.

thanks very much. it is winderful

**Comment by bew** [comment]
> i want to switch to session a, and window 5, first i need to know what is my current session. to determined whether need i switch session first. the choose-tree function also can use direct. but use up, down arrow to navigate is slow

I usually have about 5 projects (so 5 sessions) opened, and am using:
```
bind s choose-tree -Zsw -O time
```
To avoid what you mention. That `choose-tree` invocation will list the sessions in order of last usage, meaning that the current one os always at the top, the last one is the second, etc...
Note that in the choose-tree ui, you can quickly search, or use shortcut keys like for windows..
And if you give relevant names to your sessions, it's very easy to know at a glance where you want to go. 

I may post a small screenshot later to show what I mean.

**Comment by ask-github** [comment]
really thanks for your explanation.

my meaning is if only use one session, my eye don't need look anything. and no need to get info from screen. press key directly

if i want to switch build window, i press ^q to show choose-tree ui, and press 5
if i want to switch vim window, i press ^q to show choose-tree ui, and press 9
if i want to switch test script window, i press ^q to show choose-tree ui, and press d

during those progress, my brain do not think any. it is muscle memory. so it is easy.

it is like you are driving. no need to look at the accelerator and brake first, which is accelerator. 

step on it directly

thanks

**Comment by bew** [comment]
For a single project, I agree windows are a lot simpler and predictable.
If I need a window from another project (which is really not often), I'd link that window with both sessions (yes it's possible, iirc with `link-window`).
In a single project I usually use 2 panes (optionally zoomed) for vim and a testing shell, and other windows for other topics.

YMMV `¯\_(ツ)_/¯`

**Comment by nicm** [comment]
when i started tmux, a big idea was that i could have some common windows
(email, chat, project management, etc) linked into all my sessions... but
it turns out i am not so organized, and i just create a session for each
task and then make windows in it anyhow

**Comment by ask-github** [comment]
really thanks for yours help
