### ISSUE TITLE
Badly positioned split after closing top-bottom split

### ISSUE THREAD

**Issue by netei** [tmux/tmux#312]
This issue comes from here : https://github.com/junegunn/fzf/issues/201 , but is caused by tmux.

Here's a way to reproduce the problem

1. Open a tmux session
2. Run command `echo foo`
3. Clear your screen with `C-l`
4. Open a top-bottom split with `C-b` `"`
5. Close the bottom split with `C-d`

Now the window contains 

```
$ echo "foo"
foo
```

Even tough the screen was "cleared" before. 

They is a workaround by binding `C-l` to `clear; tmux clear-history` but this makes us loose the tmux history feature.

What do you think ?

**Comment by nicm** [comment]
When you resize a pane, tmux will fill with lines from the history if
possible, it is not a bug.

**Comment by netei** [comment]
Is they an option to disable this behaviour (eg do not fill lines when removing a split), or would you accept to add an option for this case ?

**Comment by ThomasAdam** [comment]
Why would you not want this?

**Comment by netei** [comment]
Because I find it disturbing because when I clear my screen, It would be better if it would stay cleared whenever I use fzf (which is basically a fuzzy finder that will open a top-bottom split, let you select a line, and close that split, and enter it into the command line)

**Comment by nicm** [comment]
We do not need an option for this. I wouldn't mind altering the default
behaviour if the change is small.

**Comment by kennykaye** [comment]
@nicm I would also support the addition/modification of this feature. Do you have plans to implement this?
