### ISSUE TITLE
[Feature request] Ability to run tmux without session-management/server

### ISSUE THREAD

**Issue by soystemd** [tmux/tmux#3120]
## Summary

Ability to run tmux without any server and session-management, only multiplexing (similar to dvtm).

## Details

tmux has great multiplexing and scrollback capabilities, but it's a shame that these features cannot be used alone, without tmux's server-client separation; 
since that separation **breaks stuff** like window swallowing in window managers, getting the cwd of a given window using xcwd, and it generally makes it a hassle to use tmux when session management is not needed.

## Required information

tmux 3.2a, Linux x86_64

**Comment by nicm** [comment]
No, this is never going to happen, detach/reattach is a core feature of tmux.

**Comment by soystemd** [comment]
> No, this is never going to happen, detach/reattach is a core feature of tmux.

Well that's a shame. 

Can you or anyone else give me directions on how to achieve this myself? The codebase is pretty big, I don't know where to begin.

Is this even realistically achievable?

**Comment by nicm** [comment]
Probably not easy to do at all.

**Comment by nicm** [comment]
How does it break anything in window managers? Window managers shouldn't care what the process inside a terminal is doing.

**Comment by nicm** [comment]
I don't know what xcwd does but it is hard to see how it breaks that either, if it rootles around in /proc to get the process cwd then it would rely on tmux figuring out the cwd for the active child process and setting it itself with `chdir`. And there is nothing stopping the server process telling the client to do that now.

**Comment by soystemd** [comment]
> How does it break anything in window managers? 

The "swallowing" feature in some window managers works by walking up the process tree to find the ancestor terminal window of a newly opened window's process, and make that new window "swallow" the terminal window. 
Of course tmux separates a terminal window from the shell, so this won't work by default.

Although the gap in the process tree can be jumped by parsing the output of `tmux list-clients -F '#{client_pid} #{pane_pid}'` to find the correlation between the tmux client and the actual shell process.

But I thought maybe somehow disabling tmux's session-management would be easier than to add tmux support to anything that might need to walk the process tree.
Apparently not.

> I don't know what xcwd does

xcwd does the same, but in reverse, in order to find the descendant processes of a window and their cwds.

> tmux figuring out the cwd for the active child process and setting it itself with `chdir`.

So you mean this might be implemented in the future?

**Comment by nicm** [comment]
But tmux is the the newly opened window's process, how does the window manager know the PID of the shell? Why doesn't it use the PID of the tmux client? Are you talking about running X programs from inside tmux?

> So you mean this might be implemented in the future?

I mean someone could implement it if they wanted.

**Comment by soystemd** [comment]
> Are you talking about running X programs from inside tmux?

Yes, that's what swallowing is for; Graphical programs started from inside a terminal (eg. a PDF viewer that is started by a terminal file manager).

> how does the window manager know the PID of the shell? 

It doesn't. what I meant by "shell" is any graphical program that is eventually started by the shell, and that shell normally would be a child or descendant process of the terminal.
The window manager of course knows the PID of any window's process, thus it can figure out if a newly opened window was started by a terminal window's process. 
Again, with tmux at play, this can't happen without any workarounds; since the shell that will start the graphical programs would be a child of the tmux server (and not the terminal).

**Comment by nicm** [comment]
OK. There is no way to make this "just work", there is no sensible way to make a tmux client be the parent of programs starting inside tmux, not to mention if there multiple clients.

What we could possibly do is add a command to run a process that *is* parented by the client, something similar to `detach -E` or `lock-command` but without replacing the client, instead it would be run by the client and left to get on with it. Of course you would lose access to stdout, and detaching tmux would orphan the processes, but it would probably be enough to allow you to start X programs from inside tmux without a gap in the process tree.

**Comment by soystemd** [comment]
> add a command to run a process that is parented by the client

That wouldn't do any good for the xcwd case, not to mention it's a hassle to make every terminal program use that command to run X programs.

Honestly if only the screen-related features of tmux (history, scrolling, etc.) could be separated (possibly into a completely separate program) that would be fantastic.

**Comment by nicm** [comment]
No, it would require a separate change to make xcwd work, as I suggested already.

I do not intend to make tmux able to run without detach/reattach and it would not be trivial to do so.

**Comment by soystemd** [comment]
> I do not intend to make tmux able to run without detach/reattach

Understandable, thanks anyway.

> it would not be trivial to do so.

Any particular reasons?
