### ISSUE TITLE
Toggling zoom state on a pane may send vim to background

### ISSUE THREAD

**Issue by zkrx** [tmux/tmux#3122]
Since not long ago (I would say my last arch linux update, so 1 month or a couple of months?), I have this weird bug when zooming on a pane. Vim gets sent to background sometimes. Here is how to consistantly reproduce:
- Have at least 2 panes in one tmux window.
- In one pane, start vim
- send vim to background by using ^z
- get vim to foreground by using "fg"
- zoom in (or out) on pane with ^b z
- vim is inadequately sent to background

I tried to reproduce with the "watch -n 1 ls" command (instead of vim) but couldn't reproduce.

To make sure that it wasn't a problem with my terminal emulator (guake), nor my tmux config file, I tried in xfce4-terminal by running tmux with the following command (although I didn't kill or restart the tmux-server because I cannot afford to lose my session):
tmux -f /dev/null

### Required information

[laptop]$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 3.2a
screen

Sorry, I cannot afford to kill my tmux server at the current time.

**Comment by nicm** [comment]
Can you do this with other programs in tmux? If not I would say this is very likely to be a vim problem.

**Comment by zkrx** [comment]
I cannot reproduce with commands like "less" or "git log" (paging), not even with the "vi" command. I opened a ticket on the vim project:
https://github.com/vim/vim/issues/9965

**Comment by nicm** [comment]
OK I will close this but do comment again if it is not vim.
