### ISSUE TITLE
Getting error `sessions should be nested with care, unset $TMUX to force` with `attach-session`

### ISSUE THREAD

**Issue by MarcelRobitaille** [tmux/tmux#3124]
### Issue description

I am trying to create a new session from within a script and attach my client to it, regardless of whether I am in tmux already. I read `man tmux`, and under the section `attach-session`, it says:

> If used from inside, switch the current client.

However, when I run `tmux attach-session my-session`, I get the error message `sessions should be nested with care, unset $TMUX to force`. I am not trying to nest sessions. I want to switch to that section, which is the expected behaviour according to the man page.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 3.2a
* Platform (`uname -sp`): Arch Linux (that command gives `Linux unknown` though)
* $TERM inside and outside of tmux (`echo $TERM`): `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): https://gist.github.com/MarcelRobitaille/15c2170b0cbc73aed0506bca6b56e66a

**Comment by nicm** [comment]
Use `switch-client` to change session from shells inside tmux.

**Comment by MarcelRobitaille** [comment]
Thanks @nicm. Isn't this wording in the docs confusing though? And wouldn't it be good to have a way to switch to a new session regardless of whether you're in a session?

**Comment by nicm** [comment]
you need to use switch-client from shells inside tmux, not attach-session
