### ISSUE TITLE
[feature request]Could you add "--enable-static" option for run configure and compile?

### ISSUE THREAD

**Issue by quaggalinux** [tmux/tmux#3125]
Hi,

Could you add "--enable-static" option for run configure and compile? Because some custom linux  systems lack dependencies.

Thank you!

**Comment by nicm** [comment]
Did you try it?

**Comment by quaggalinux** [comment]
Yes, it works now. Before I did not properly install dependencies.

following is my compile environment and command:

linux version is ubuntu-20.04.4-live-server-amd64.iso

install dependencies command:

apt update -y && apt install make gcc-multilib build-essential autoconf automake pkg-config libevent-dev ncurses-dev bison -y && apt upgrade -y

git clone https://github.com/tmux/tmux.git
cd tmux
sh autogen.sh
./configure --enable-static && make

This compiled binary file works perfectly in my NAS WD PR4100 os5 since this NAS is custom debian and it lacks dependencies

Thank you!
