### ISSUE TITLE
nvim tmux checkhealth test fails with $TERM set to alacritty 

### ISSUE THREAD

**Issue by EdmundsEcho** [tmux/tmux#3126]
### Required information

Please provide the following information:

* tmux version (`tmux -V`): 3.2a
* Platform (`uname -sp`): MacOS 12.3 (M1)
* $TERM inside and outside of tmux (`echo $TERM`): alacritty (both in and out of tmux)
* Logs from tmux (`tmux kill-server; tmux -vv new`).

### Issue description

`nvim`'s `:checkhealth` generates the following output:

```fish
   - INFO: $TERM: alacritty
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ
```

As best as I can tell, this error is a "false negative".  In other words, my terminal is working just fine despite the test failing.

My ability to confirm the correct color operation is based on the following:

1. running the following test reports what I would expect:
```fish
 > printf "\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m\n"
TRUECOLOR
```

2. When I go ahead and change the register in the `.tmux.conf` file to the recommended setting, the colors do not display correctly.

I recognize this is test fails in `nvim`, however, it's a `tmux` test that is failing... ideally, help/guidance on how to fix the test might best come from `tmux`?

**Comment by nicm** [comment]
TERM must be screen, screen-256color, tmux or tmux-256color inside tmux.

**Comment by EdmundsEcho** [comment]
I think I figured out how to resolve both what I was observing and the above understanding that "TERM must be screen... ".

1. I have alacritty in my system's terminfo database; something that can be confirmed using
```fish
❯ infocmp alacritty
... a non-null return value
```
In the event you get a `infocmp: couldn't open terminfo file (null).` error,  [go here](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo).

2. $TERM should *not* be set in my fishshell, nvim nor tmux config files (of course, but often a recommendation in various blogs), but nor in the alacritty configuration (see next step)

3. $TERM is set by alacritty to `alacritty` when alacritty is found in the system's terminfo db (otherwise it defaults to xterm-256color)
```fish
❯ echo $TERM
alacritty
```

4. tmux maps the $TERM value in alacritty to `screen-256color` using the system db
from inside the tmux session:
```fish
❯ echo $TERM
screen-256color
```

5.  For reasons I'm not fully clear on, we need to manually let tmux know how to lookup the `RGB` (or `Tc`) data entries for the **underlying** terminal (`alacritty` in my case).  
```bash
# nvim compatibility
set -sa terminal-overrides ',alacritty:RGB'
```

 6. Because I have a proper entry in my system db (step 1) for `alacritty`, it all works as expected in the `checkhealth` `tmux` result:
```bash
## tmux
 - ...
  - INFO: $TERM: screen-256color
```

Finally, in the event your `$TERM` value defaults to ` xterm-256color` because of a missing `terminfo` entry, the `tmux.conf` `RGB` setting as described in (5) will fail.

## Conclusion

I suspect the test depends on at least these 2 conditions:

1. aligning the value of the underlying $TERM value (in my case `alacritty`) with the `terminal-overrides` register for `RGB` or `Tc` (per the XXX instructions)

2. tmux's ability to map the underlying `$TERM` value using the information in the `terminfo` to one of the following per what @nicm described
> TERM must be screen, screen-256color, tmux or tmux-256color inside tmux

I was able to circumvent this validation by forcing the `$TERM` value inside the `tmux` context (either manually setting the env value while in tmux, or doing what I knew was a daft thing to do, set the $TERM value in my shell's config (in my case config.fish).  

Notwithstanding, the "daft" mistake on my part, because the `terminal-overrides` value was set correctly, and aligned with the `terminfo`, my color output worked as correctly, but failed the test likely because the second condition was not met.

Is there something here we can use to make the test assess the situation "more directly"?

**Comment by nicm** [comment]
Yes if TERM=alacritty does not have RGB/Tc or other capabilities you will
need to tell tmux about them manually.

**Comment by ThomasDickey** [comment]
alacritty-direct (as [documented](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo)) sets `RGB`.

**Comment by EdmundsEcho** [comment]
@ThomasDickey Agree.  From what I can gather  `alacritty` has properly set the `RGB` values in the `terminfo` db.

 `tmux` seems to need (i) to derive that the entry falls under one of the accepted values (ii) be told manually in `.tmux.conf` about the true color capability in order to work with `nvim` (using the `terminal-overrides` register).
