### ISSUE TITLE
OSC 7 passthrough

### ISSUE THREAD

**Issue by aimuz** [tmux/tmux#3127]
### Issue description

On macos, I'm using tmux in the "terminal.app", and during the process, I noticed that the terminal can't get the current directory anymore.

After troubleshooting, zsh, which is run directly from the terminal, will have a hook. `update_terminal_cwd`

```
➜  ~ echo $precmd_functions         
update_terminal_cwd omz_termsupport_precmd update_terminalapp_cwd _z_precmd _zsh_autosuggest_start _zsh_highlight_main__precmd_hook
```

This hook a key, this is his code.

```zsh
update_terminal_cwd () {
	local url_path='' 
	{
		local i ch hexch LC_CTYPE=C LC_COLLATE=C LC_ALL= LANG= 
		for ((i = 1; i <= ${#PWD}; ++i)) do
			ch="$PWD[i]" 
			if [[ "$ch" =~ [/._~A-Za-z0-9-] ]]
			then
				url_path+="$ch" 
			else
				printf -v hexch "%02X" "'$ch"
				url_path+="%$hexch" 
			fi
		done
	}
	printf '\e]7;%s\a' "file://$HOST$url_path"
}
```

When the hook is executed, it will issue OSC 7 when I add this hook to zsh inside tmux，Also not working

I tried to execute this command

```zsh
printf '\e]7;%s\a' "file://$HOST/etc"
```

There is no change and the system receives no information.

I checked the wiki and found that only by adding this prefix and suffix can I send out smoothly

https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it

```
printf '\033Ptmux;\033\e]7;%s\a\033\\' "file://$HOST$url_path"
```
When I executed this, cool, the "terminal.app" received the message and got the path correctly

I added a file `/etc/zshrc_tmux`

```zsh
if [ -z "$INSIDE_EMACS" ]; then

    update_terminal_cwd() {
	# Identify the directory using a "file:" scheme URL, including
	# the host name to disambiguate local vs. remote paths.

	# Percent-encode the pathname.
	local url_path=''
	{
	    # Use LC_CTYPE=C to process text byte-by-byte and
	    # LC_COLLATE=C to compare byte-for-byte. Ensure that
	    # LC_ALL and LANG are not set so they don't interfere.
	    local i ch hexch LC_CTYPE=C LC_COLLATE=C LC_ALL= LANG=
	    for ((i = 1; i <= ${#PWD}; ++i)); do
		ch="$PWD[i]"
		if [[ "$ch" =~ [/._~A-Za-z0-9-] ]]; then
		    url_path+="$ch"
		else
		    printf -v hexch "%02X" "'$ch"
		    url_path+="%$hexch"
		fi
	    done
	}

    printf '\033Ptmux;\033\e]7;%s\a\033\\' "file://$HOST$url_path"
    }

    # Register the function so it is called at each prompt.
    autoload -Uz add-zsh-hook
    add-zsh-hook precmd update_terminal_cwd
fi
```

When in the `tmux` environment, he will load it automatically.

After loading successfully, when I switch directories, he can work normally

The problem I started with was solved in this way.

I have a new problem, when I `ssh` the remote host, my remote host also has this one hook and he also sends 

```
printf '\e]7;%s\a' "file://$HOST/etc"
```

Yes, it's not working again. When I go to the remote server and manually change it to this, it works again.

```
 printf '\033Ptmux;\033\e]7;%s\a\033\\' "file://$HOST$url_path"
```

I was wondering if there is a way that I can hook the message I receive and then after processing it, automatically add the pass-through escaping.

Or is there another way to make OSC commands that tmux doesn't recognize, pass through directly? Because I found that it seems to be discarded without support at the moment? Or is there a better way to solve this problem?

### Required information

Please provide the following information:

* tmux version (`tmux 3.2a`).
* Platform (`Darwin i386`).
* $TERM inside and outside of tmux (`xterm-256color`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
tmux supports OSC 7 and puts it in the `pane_path` format variable, there is currently no support for passing this on to the external terminal, but it could be added (it would be very similar to the code to set the title).

**Comment by aimuz** [comment]
@nicm 
And what is the way to make it pass through again? Add a hook?

**Comment by nicm** [comment]
No it will need code changes, for the moment you will need to use the
passthrough sequence but obviously that will not update when you change
pane.

**Comment by aimuz** [comment]
I wrote a script to get the `pane_path` value from tmux and then pass it through escaping. I think it would work if there was a way to execute this script when the window changes.

```zsh
printf '\033Ptmux;\033\e]7;%s\a\033\\' "$(tmux display -p '#{pane_path}')"
```

I tried to add a hook to `zsh`'s `precmd `. But this only works for local, if you connect to a remote host, it still doesn't work. I think it would work if tmux had hooks that let me execute this script.

```zsh
update_terminal_tmux_cwd(){printf '\033Ptmux;\033\e]7;%s\a\033\\' "$(tmux display -p '#{pane_path}')"}
add-zsh-hook precmd  update_terminal_tmux_cwd
```

**Comment by nicm** [comment]
Try this please, against master: [x.diff.txt](https://github.com/tmux/tmux/files/8332778/x.diff.txt)

You will need to enable `set-titles` and also the `osc7` feature since tmux cannot automatically detect Terminal.app:
~~~~
set -g set-titles on
set -as terminal-features 'xterm*:osc7'
~~~~
(I am not wild about the name of the feature so I might change it.)

**Comment by nicm** [comment]
Actually please try this one which will set the path to empty when it is not set in the pane: [y.diff.txt](https://github.com/tmux/tmux/files/8332837/y.diff.txt)

**Comment by aimuz** [comment]
Thanks, do I need to recompile the build locally

**Comment by aimuz** [comment]
Great, I tested it on my computer, will this feature be merged to master?
