### ISSUE TITLE
Home and End key are not working inside neovim

### ISSUE THREAD

**Issue by budimanjojo** [tmux/tmux#3128]
### Issue description

Hello, I have these lines in my `tmux.conf`
```
set -g default-terminal "tmux-256color"                                                                   # 256 color
set -sa terminal-features ",*256col*:RGB"                                                                 # True color support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'                                                        # Undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m' # Underscore colors
```
When I'm inside neovim, `HOME` and `END` keys are not working. If I delete the `terminal-overrides` lines from tmux config, then it will work again.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.2a
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color and tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-server-210229.log](https://github.com/tmux/tmux/files/8313524/tmux-server-210229.log)

**Comment by nicm** [comment]
These options do not change Home and End, so most likely vim is changing its behaviour when `TERM` is `tmux-256color` rather than `screen-256color` (they both have the same value for `khome`).

**Comment by budimanjojo** [comment]
Sorry but I seem lost, now even when I delete all those lines the keys still don't work. I even deleted `~/.tmux.conf` and it still doesn't work. If I exit out tmux then it will work again. Is there any way to get a log of this?

**Comment by budimanjojo** [comment]
yes I did. I think this is related to: https://github.com/neovim/neovim/issues/13408 but I don't know exactly how to fix this.

**Comment by budimanjojo** [comment]
maybe I should file a bug report to neovim instead?

**Comment by budimanjojo** [comment]
changing my terminal emulator from kitty to alacritty also fixed this. although I have set both kitty and alacritty to be using xterm-256color

**Comment by budimanjojo** [comment]
Setting kitty to use `screen-256color` and tmux to `tmux-256color` also fixed this. I'm going to close this issue because it doesn't seem like tmux issue. But this terminal things are very weird, Thanks for the time @nicm

**Comment by budimanjojo** [comment]
Just want to update on this. The problem is caused by `libunibilium` used by neovim is not configured to handle `kitty` $TERMINFO reporting correctly. https://github.com/neovim/unibilium/commit/32ab8ef6ee6e903cbc3ae738580ccd198bb46f09

Ubuntu 20.04 is still using libunibilium v2.0.1 which doesn't include that commit. Manually compiling the latest libunibilium indeed solved this issue on my end.
