### ISSUE TITLE
[Bug] Possible buffer overrun in screen-write.c

### ISSUE THREAD

**Issue by yiyuaner** [tmux/tmux#3130]
In the file [screen-write.c](https://github.com/tmux/tmux/blob/964deae422e4127a64f60fa3b54e2bf47b8e074c/screen-write.c), the function `screen_write_collect_add` has the following [code](https://github.com/tmux/tmux/blob/964deae422e4127a64f60fa3b54e2bf47b8e074c/screen-write.c#L1804-#L1806):

```
void screen_write_collect_add(struct screen_write_ctx *ctx, const struct grid_cell *gc) {
    struct screen			*s = ctx->s;
    u_int				 sx = screen_size_x(s);

    ......
  
    if (s->cx > sx - 1) {
        ......
    }
    
    if (ci->used == 0)
        memcpy(&ci->gc, gc, sizeof ci->gc);
    if (ctx->s->write_list[s->cy].data == NULL)
	ctx->s->write_list[s->cy].data = xmalloc(screen_size_x(ctx->s));
    ctx->s->write_list[s->cy].data[s->cx + ci->used++] = gc->data.data[0];   
}
```
The buffer access `ctx->s->write_list[s->cy].data[s->cx + ci->used++]` may trigger a buffer overrun. Here is the analysis:

The variable `ctx->s->write_list[s->cy].data` is allocated to a buffer of size `sx`, because of the following statement:
```
ctx->s->write_list[s->cy].data = xmalloc(screen_size_x(ctx->s));
```
and the facts that `sx = screen_size_x(s)` and `s = ctx->s`. Also the above code explicitly check the value of `s->cx` against `sx` in the statement:
```
if (s->cx > sx - 1)
    ......
```

Now suppose in an execution we have `s->cx == sx - 1` and `ci->used == 1`, then access to the buffer `ctx->s->write_list[s->cy].data` is at the index `sx`, which is an off by one buffer overrun.

**Comment by nicm** [comment]
If `s->cx > sx - 1` then it calls `screen_write_collect_end` which will do:
~~~~
ctx->item = screen_write_get_citem();
~~~~
Meaning that `ci->used` will be zero.
