### ISSUE TITLE
Different color window label with zoomed pane

### ISSUE THREAD

**Issue by rightaway** [tmux/tmux#3132]
It's easy to forget you're in a zoomed pane and that the window has other panes if you've been in the zoomed pane for a while. Can we have configuration options for the color of a window label when a pane in that window is currently zoomed (only when it's the current window)? tmux themes can use it or we can set it in our configs. Having a different color can help remind you the context you're working in.

**Comment by nicm** [comment]
Yes you can configure this with `window-status-format`/`window-status-style` (and the two `current` ones).

**Comment by rightaway** [comment]
@nicm Are variables like `window-status-format` documented or listed somewhere where I can see which ones are possible to use?
