### ISSUE TITLE
A way to suspend a pane, show "pane suspended..." (like "pane dead..."), and continue it

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3133]
Ctrl-z based job control to suspend a foreground process in shell is limited in that it immediately takes away the contents being displayed by a foreground process from users eyes, and shows the prompt again. Then user can either manually type use ``>>fg`` command to continue the process, or have a shell keybinding to do the same. It would be nice to have a tmux command to suspend the pane and continue it without going back to the shell prompt. Just like a pane process which has died shows something like "pane dead...", while suspended a pane would show "pane suspended..." Perhaps this would suspend all the processes in the process tree of ``shell-command`` of a pane, as if computer went to sleep only for that process tree? And then continuing them will continue the entire process tree. While its ok even if this suspend/continue works only for foreground process, I think it would be more powerful to have it for entire process tree running under ``shell-command``.

Sidenote: Am not looking for Ctrl-s/Ctrl-q based flow control, that doesn't suspend a process.

**Comment by nicm** [comment]
I don't think this is something tmux should do when the shell can already
do it.

**Comment by reportaman** [comment]
Hmm, not sure how shell could do what I want to achieve. Is there a way to display  "pane suspended" overlayed over frozen contents of current pane contents (without hiding them), and accept a keybinding to continue the underlying process?
