### ISSUE TITLE
Improve commit messages

### ISSUE THREAD

**Issue by cibinmathew** [tmux/tmux#3134]
### Issue description

Thanks team for the efforts.

**What**
It would be better to ensure commit messages like **Merge branch 'xxxxx' into master** without any further description are avoided.

![image](https://user-images.githubusercontent.com/10793628/160269259-492e674a-409e-4039-9019-2e48a76cca77.png)

Just to start with, we can go with something like a relevant message with an additional one liner description is better.
![image](https://user-images.githubusercontent.com/10793628/160269214-364f9b05-51f9-47de-9218-9e06e40d3e61.png)

OR
include the clickable link for PR/Issue in the commit message or in the description

Please pitch in with suggestions. We can explore **github actions** to see if it can help enforce this.

**Why**
Many would go through the commit history to see what(feature/fixes/..) has gone into master recently to play around with the fix/feature
Not every time, change logs would be exhaustive enough

### Required information

NA

**Comment by nicm** [comment]
Git automatically generates merge commit messages, just ignore them, they don't include anything anyone needs to look at. You can do `git log --no-merges` and you will not see them.
