### ISSUE TITLE
After respawning an empty pane, the output send to that pane is messed up

### ISSUE THREAD

**Issue by bfrg** [tmux/tmux#3137]
### Issue description

After respawning an empty pane, the output send to the empty pane with `display-message` is messed up.

To reproduce, run:
```bash
$ tmux split-window -h '' \; set -p remain-on-exit on \; set -p remain-on-exit-format "" \; last-pane
$ ./myscript.sh | tmux display-message -I -t '{last}'
$ tmux respawn-pane -t '{last}'
$ ./myscript.sh | tmux display-message -I -t '{last}'
```
with the following script:
```bash
#!/bin/sh
for i in $(seq 200); do
    echo $i 'text text text text text text text text text text EOL'
done
```

The reason for running `respawn-pane ''` was to clear the entire pane. `clear-history` won't clear what is currently displayed. I've also tried running `respawn-pane -t '{last} clear`, but end up with the same result as with `respawn-pane -t '{last} ''` when I send output to that pane.

#### Screenshots

Before respawning the pane:
![screenshot-2022-03-29_215907](https://user-images.githubusercontent.com/6266600/160700639-59415125-31ef-4a4b-925a-2bca96c5660e.png)

After respawning the pane:
![screenshot-2022-03-29_215944](https://user-images.githubusercontent.com/6266600/160700317-18833322-3b54-48aa-ab94-59467c6d94ae.png)

### Required information

* tmux version `next-3.4`
* Platform Linux
* $TERM `tmux-256color` inside and `xterm-256color` outside of tmux

**Comment by nicm** [comment]
empty panes have a flag on them to treat CR as CRLF, respawn must
unintentionally clear it, I'll take a look in the next few days

**Comment by nicm** [comment]
I'm not sure respawning empty panes really works that well, but this seems to fix your case:
~~~~
--- screen.c    3 Nov 2021 13:37:17 -0000       1.78
+++ screen.c    30 Mar 2022 07:45:40 -0000
@@ -104,7 +104,7 @@ screen_reinit(struct screen *s)
        s->rupper = 0;
        s->rlower = screen_size_y(s) - 1;

-       s->mode = MODE_CURSOR|MODE_WRAP;
+       s->mode = MODE_CURSOR|MODE_WRAP|(s->mode & MODE_CRLF);
        if (options_get_number(global_options, "extended-keys") == 2)
                s->mode |= MODE_KEXTENDED;

**Comment by bfrg** [comment]
Thank you. This fixes the issue.

**Comment by bfrg** [comment]
The reason why I respawned the pane was because I thought that respawning an empty pane would clear the entire content and start with a clean pane again.

**Comment by nicm** [comment]
It will (and should) but there is some funny things, eg it seems it only works with `remain-on-exit` on.

**Comment by nicm** [comment]
I have applied this fix to OpenBSD now, will be in GitHub later. Thanks!

**Comment by bfrg** [comment]
One last question, shouldn't respawning the empty pane also clear its history? It seems currently only the visible part is cleared.

**Comment by nicm** [comment]
We don't clear history on normal respawn, I think it should be the same.
