### ISSUE TITLE
Commas in styles mess up conditions

### ISSUE THREAD

**Issue by roylez** [tmux/tmux#3138]
### Issue description

Working one with space separated styles within `#{?#{==:var,value},if-value,else-value}`. Interestingly if it is only `#{?cond,if-value,else-value}` it will work.

```
set -g status-left "#[fg=cyan]:#[fg=blue]:#[fg=red][ #{?#{==:#{client_key_table},root},#[fg=green bold]#h#[default],#[fg=yellow bold reverse]#{client_key_table}#[default]} #{?#(new_mail_count), #[fg=magenta#,bold#,reverse]#(new_mail_count)#[default] ,}#[fg=red]] " 
```
![screenshot 2022 03 30 0951](https://user-images.githubusercontent.com/62289/160724497-d480a558-73b6-4eed-91b5-38cc1e761d6b.jpg)

Non-working one with comma separated styles

```
set -g status-left "#[fg=cyan]:#[fg=blue]:#[fg=red][ #{?#{==:#{client_key_table},root},#[fg=green,bold]#h#[default],#[fg=yellow,bold,reverse]#{client_key_table}#[default]} #{?#(new_mail_count), #[fg=magenta#,bold#,reverse]#(new_mail_count)#[default] ,}#[fg=red]] " 
```

![screenshot 2022 03 30 0952](https://user-images.githubusercontent.com/62289/160724564-0b618952-4468-433d-92e0-741cd54da596.jpg)

### Required information

Please provide the following information:

* tmux: 3.2_a-1
* Platform: Archlinux
* $TERM inside and outside of tmux: tmux-256color, xterm-kitty
* Logs from tmux: nil

**Comment by nicm** [comment]
Why can't you use spaces?

**Comment by roylez** [comment]
I can, but a bug is a bug, right?

If commas cannot be safely used like spaces, it should not be mentioned at the same time in man page.

**Comment by nicm** [comment]
I don't think it's a bug any more than not being able to use `'` inside `'`s is a bug.

**Comment by roylez** [comment]
My bad. I missed the line saying that `,` has to be escaped with `#,`. I knew this before and has `#,` already in my config file but later forgot this completely.
