### ISSUE TITLE
Deceiving behavior of cursor in copy mode

### ISSUE THREAD

**Issue by jphalip** [tmux/tmux#3139]
I'm using tmux 3.2a on Mac OS. $TERM=screen-256color. I'm also using `mode-keys=emacs`.

The issue I'm having is very similar to #1579. If I select text from left to right, the cursor deceivingly highlights a character that is in fact not selected. So if you copy and paste, it seems as though the last character was not copied.

Based on the comments in #1579, it looks like that behavior should have normally been fixed in https://github.com/tmux/tmux/commit/34c0807be6add421bc4624d498adf9f55d00a120.

Am I missing something?

Thanks.

**Comment by nicm** [comment]
The cursor character is not part of the selection with emacs keys.

**Comment by jphalip** [comment]
It appears that the cursor is in fact included in the selection when selecting from right to left, but excluded from left to right. Is that inconsistency intended?

**Comment by nicm** [comment]
yes that is correct

**Comment by nicm** [comment]
it works the same way as emacs, if you want it to change then convince them
to change first

if you want vi behaviour then set mode-keys to vi

**Comment by jphalip** [comment]
Ok that makes sense. I think part of my problem is that my cursor is a non-blinking full block, which looks a lot like the selection highlight. By chance is there a way to change the cursor shape (eg. to an underscore or vertical line) during copy mode?

**Comment by nicm** [comment]
No this would need to be built into tmux, it would not be possible to do this with hooks. I've added to the todo list. Thanks!
