### ISSUE TITLE
select-pane: Add flag to zoom the new pane if the current pane is zoomed.

### ISSUE THREAD

**Issue by sanscore** [tmux/tmux#314]
I think the summary about covers it. I would like it if I could navigate around window without having to zoom, do work, navigate which forces unzoom, zoom, do work, navigate, etc....

Thanks.

**Comment by nicm** [comment]
You can do this by using something like if -F '#{window_zoomed_flag}' 'selectp -L; resizep -Z' 'selectp -L'

**Comment by sanscore** [comment]
Very nice. Thanks.

Just to complicate matters, I am using [christoomey/vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator) which recommends adding [these key bindings](https://github.com/christoomey/vim-tmux-navigator#tmux)

Here's my attempt to amend the `C-h` mapping.
`bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "if -F '#{window_zoomed_flag}' 'selectp -L; resizep -Z' 'selectp -L'"`

**Comment by sanscore** [comment]
Hmm. Nevermind, the problem is only with panes using vim.

**Comment by sanscore** [comment]
Thanks for the help. This is will work for me, even despite the unzoom from vim; I can probably customize vim-tmux-navigator or, if not, patch it. Though, I still think that it could be a useful feature to have.
