### ISSUE TITLE
Command History

### ISSUE THREAD

**Issue by colin99d** [tmux/tmux#3140]
### Issue description

When switching from one pane from another, I need to interact with the pane in another way before I can use `up` arrow for history. For example, if I switch back to a pane I now hit my `delete` key and then press the up arrow for command history. If I press the up arrow immediately no history is shown until I type into/click on the terminal.

A tmux config is not needed to recreate this issue. It is present even without a config.

`Darwin arm
tmux 3.2a
xterm-256color`

**Comment by reportaman** [comment]
Doesn't happen on my end, I tested with and without my config file. If I got the question right, you enter a partial command in a pane, then move the focus to another pane, and bring it back to the original pane, and hit delete/up keys. I don't need to enter carriage return/click on terminal for it to work. Also, @nicm asks for the TERM both inside and outside tmux. Also, given you are on Darwin arm, try using iTerm2 to see if it works there. Posting a screen recording might also help.

**Comment by nicm** [comment]
Bind the arrow keys without the repeat flag (-r) or change repeat-time to taste.

**Comment by colin99d** [comment]
<img width="337" alt="Screen Shot 2022-04-05 at 7 07 13 AM" src="https://user-images.githubusercontent.com/72827203/161740951-b46000c6-ef45-40c2-b26e-4cd2102565d8.png">
None of my keys use the -r flag and I added in the repeat-time setting but nothing changed. Also, I used Alacritty instead of the basic terminal, but does iTerm2 work better?

**Comment by nicm** [comment]
Set repeat-time to what you want it to be, not literal "taste". Come on.

The keys are bound with `-r` by default.

**Comment by nicm** [comment]
Bind the arrow keys without the repeat flag (-r) or change repeat-time to
taste.
