### ISSUE TITLE
tmux remote server: protocol version mismatch (client 7, server 8)

### ISSUE THREAD

**Issue by farzadmf** [tmux/tmux#3143]
### Issue description

Hi, I have a Mac computer and Linux server, to which I connect though SSH. I heavily use `tmux` on my client, and today I thought, since `tmux` has a client/server architecture, I should be able to connect from my local MacOS client to the remote Linux server.

A bit of research and I saw `ssh -t <server> tmux attach` should work, but this is what I do:
- I `ssh` to the Linux server
- I start a new `tmux` session
- I `detach-client` in the Linux server
- I logout from `ssh`
- On my local, I run the command I mentioned above
- I get the error in the title: `protocol version mismatch (client 7, server 8)`

As you see from the information below, both my local machine and the remote server are using `tmux 3.2a`, so I'm not sure why a protocol mismatch would happen between the two.

Thank you in advance for your help

### Required information

Please provide the following information:

* tmux version (`tmux -V`). server: `tmux 3.2a` | client :`tmux 3.2a`
* Platform (`uname -sp`). server: `Linux x86_64` | client: `Darwin i386`
* $TERM inside and outside of tmux (`echo $TERM`).
  * client: outside of tmux: `xterm-256color` | inside of tmux `tumx-256color`
  * server, when connected **without** a `tmux` session on the client:
    * outside of tmux: `xterm-256color` | inside of tmux: `tmux-256color`
  * server, when connected through a `tmux` session on the client:
    * outside of tmux: `tmux-256color` | inside of tmux: `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
I don't think the logs will be useful here (and since it's a company computer, I need to take care what I post from the logs), so please let me know if the logs you requested would help and I would look into providing something

**Comment by nicm** [comment]
You cannot connect a tmux client on one machine to a tmux server on
another. If you are using ssh you are running client and server on the same
machine, which will work.

You must be running different tmux versions somehow or you would not get
this error. Make sure you have restarted tmux entirely after upgrading.

**Comment by farzadmf** [comment]
Sorry, I'm a bit confused.

> You cannot connect a tmux client on one machine to a tmux server on another

So, this means that I cannot do what I'm trying to do?

> If you are using ssh you are running client and server on the same machine

Not sure I get this part; you mean if I `ssh` and then do `tmux`? If you mean that, then yeah, I understand that the client and the server are running on the same machine, and what I'm trying to do is connect my local MacOS `tmux` client to remote Linux server's `tmux` server.

So, just to double check: for example, Docker also has a client/server architecture and you can "attach" your local docker client to any docker daemon (local or remote), is that possible with tmux? from your first sentence, I get the feeling that it's not, but then, from your further explanations, I'm thinking that it would be somehow possible? 🤔 

Please let me know

**Comment by nicm** [comment]
You cannot connect tmux on one machine to tmux on another.

**Comment by nicm** [comment]
But if you are doing this:

 ssh -t <server> tmux attach

Then you are running both tmux server and client on the same machine
(<server>).

**Comment by farzadmf** [comment]
Oh right, now I get what you mean, so why is it the case that when I `ssh <server>` and run `tmux`, it's fine, but when I do `ssh <server> -t tmux`, it complains about protocol mismatch?

**Comment by krader1961** [comment]
It's because your first command starts an interactive shell. The second runs tmux directly. Your interactive shell is changing the `PATH` (e.g., in your *~/.bashrc*). So you have at least two different tmux commands in different directories. Try running `which -a tmux` and `locate tmux`.

**Comment by farzadmf** [comment]
> Try running `which -a tmux` and `locate tmux`.

Thank you @krader1961 , that was the issue, I've installed `tmux` using `brew` on my Linux machine, but when I do `ssh -t ...`, it's picking up the system's `tmux`, which is old of course and hence the protocol mismatch issue.

---

To @nicm 's point, I guess if I do `ssh <server> -t tmux ...`, I'm running the client/server both on the remote server and just attaching my local terminal to those.

So, the client/server archiecture of `tmux` is not like `docker` where I can connect my local client to any daemon that I want, is that correct?

**Comment by krader1961** [comment]
> To @nicm 's point, I guess if I do `ssh <server> -t tmux ...`, I'm running the client/server both on the remote server and just attaching my local terminal to those.

Yes, but you are still missing the point. If you do `ssh <server>`, then interactively run `tmux` you are still running the client/server processes on the same, remote, system. Tmux communicates between the tmux client and server using a "UNIX domain socket"; which, by definition, is only usable by processes running on the same system. This is client/server but only when both are running on the same system. Which is not what you apparently think is happening. I am honestly confused why you don't understand this.

**Comment by farzadmf** [comment]
> I am honestly confused why you don't understand this.

I did understand it, but maybe I wasn't clear when explaning (the text you quoted above is me trying to confirm that the client/server both are running on the same server (I did write that 🙂 )

> which, by definition, is only usable by processes running on the same system

If I'm not mistaken, Docker also uses sockets locally to interact between client and server, and I was hoping to get a smiliar functionality with tmux

> You don't understand nuances such as ...

I agree, I tried the internet and couldn't find much, so I opened this issue to hopefully get help from here. I guess if I did understand all the details, I wouldn't have needed to open the issue in the first place, don't you agree? 😛

**Comment by krader1961** [comment]
> I did understand it...

No, you did not understand it. Because you don't understand that some commands, such as `tmux` invoked as a "client" only communicate with a "server" running on the same system. But all of that is irrelevant. The main problem is that you don't understand the difference between `ssh <server>`, followed by running `tmux`, and `ssh -t tmux`.

**Comment by farzadmf** [comment]
I think I have an idea of the client/server communication on the same system using a Linux socket (but now that you mentioned a bunch of times that I don't udnerstand it, my confidence is gone and I'm not sure)

> some commands, such as `tmux` invoked as a "client" only communicate with a "server" running on the same system

I think that basically covers the case I was curious about and confirms that it's not possible. TBH, as I said in the issue, I've been using tmux for quite a while now (and I can't live without it in the terminal), but the clipboard sync between my Mac and Linux server is not very efficient (I need Xquartz on Mac that sometimes stops working etc.), and I thought I had one of those "aha moments", where I figured out that I can have my local `tmux` connect to the remote server and boom, I'll be happy! (but that doesn't seem to be possible unfortunately)

> you don't understand the difference between `ssh <server>`, followed by running `tmux`, and `ssh -t tmux`.

I guess I don't (again), I tried to guess, but I guess I was wrong. If you'd be kind enought to explain a bit, I'd appreciate it (if not, I understand of course)

**Comment by krader1961** [comment]
When you execute `ssh <server>` you are implicitly invoking your default interactive shell on `<server>` (the `-t` to run the shell attached to a pty is also implied). When you explicitly specify a command, as when running `ssh -t <server> tmux`, that command is run without directly on `<server>` without first running an interactive shell. Therefore, if your interactive shell modifies the value of `PATH` then it is possible for the two commands to select different versions of the `tmux` command.

As I said earlier you should start an interactive shell on `<server>` and run `which -a tmux` and/or `locate tmux`. You will find that you have a `tmux` command in two or more directories. And those tmux commands are not the same version.

**Comment by krader1961** [comment]
> the clipboard sync between my Mac and Linux server is not very efficient (I need Xquartz on Mac that sometimes stops working etc.), and I thought I had one of those "aha moments", where I figured out that I can have my local tmux connect to the remote server and boom, I'll be happy!

That's because you're relying on SSH to synchronize the clipboard via what is known as "X11 forwarding". See the description of the `-X` option in the ssh man page. The native macOS window manager does not implement the X11 protocol. XQuartz does. Google "macos xquartz x11 forwarding".
