### ISSUE TITLE
RFE: optionally show border on all sides of the active plane

### ISSUE THREAD

**Issue by samcramer** [tmux/tmux#3144]
### Issue description

It would be nice if it was possible to show a border on all sides of the active plane in order to draw attention to it.  I configure the active pane background to be different color than the other panes so there is a reasonable workaround, but a border on all sides would really make the active pane stand out.

Thanks for all the hard work on this wonderful tool!

### Required information

Since this is an RFE which I believe applies to all tmux versions and since it is not an actual bug, I'm not including what would normally be "required information".

**Comment by nicm** [comment]
I don't see much benefit to this really TBH so I don't see much chance of
it happening unless someone else does it and submits a PR.
