### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by seyerian** [tmux/tmux#3146]
In the "Resizing and zooming panes" section, the hotkey for zooming into a pane is described as `C-b Z` (uppercase Z) but is actually `C-b z` (lowercase z). I'm using version 3.2a; this is what I am experiencing and also what `list-keys` reports.

https://github.com/tmux/tmux/wiki/Getting-Started#resizing-and-zooming-panes

Thanks!

**Comment by nicm** [comment]
Fixed now, thanks!

**Comment by seyerian** [comment]
@nicm There were two instances that needed fixing. Now it says:

> A single pane may be temporarily made to take up the whole window with `C-b z`, hiding any other panes. Pressing **`C-b Z`** again puts the pane and window layout back to how it was.

I feel bad bothering you about such a small change. I'd fix it myself if I could! 😄

**Comment by nicm** [comment]
Whoops I should have searched for others. Fixed now, thanks!
