### ISSUE TITLE
detached new-session, -x/-y applied after window created

### ISSUE THREAD

**Issue by pcrow** [tmux/tmux#3147]
When creating a detached session and specifying a size with -x and -y, the sizes are applied to new windows, but not to the initial window for the session.  Reading the documentation, it would appear that you should be able to run a command in a detached session with a given size with the command:

`tmux new-session -d -x $X -y $Y ${MY_COMMAND}`

But to get that to actually work, you instead have to issue:

`tmux new-session -d -x $X -y $Y \; new-window ${MY_COMMAND} \; kill-window -t 0`

If this behavior can't be changed in the code, then it should be at least clarified in the man page.

**Comment by nicm** [comment]
~~~~
$ tmux -Ltest kill-server
$ tmux -Ltest new -x999 -y222 -d top
$ tmux -Ltest lsw
0: top* (1 panes) [999x222] [layout 934d,999x222,0,0,0] @0 (active)

**Comment by pcrow** [comment]
$ tmux -Ltest kill-server
error connecting to /tmp/tmux-.../test (No such file or directory)
$ tmux -Ltest new -x999 -y222 -d top
$ tmux -Ltest lsw
0: top* (1 panes) [80x23] [layout ae5d,80x23,0,0,0] @0 (active)

**Comment by nicm** [comment]
OK now the tmux version and logs?

**Comment by pcrow** [comment]
3.2a
What logs should I grab?  (I'm a bit of a newbie on tmux.)

**Comment by nicm** [comment]
Don't worry about logs actually. Since this works for me, it is probably already fixed. Please build tmux from master and see if it is fixed for you. Look at https://github.com/tmux/tmux/wiki/Installing#from-version-control.

**Comment by pcrow** [comment]
Yes, you're right!  Thanks.
(I'm running Gentoo, so I just added "app-misc/tmux **" to /etc/portage/accept-keywords, then emerged tmux-9999 which grabs the live version.)
