### ISSUE TITLE
How do I make pane lines thicker  

### ISSUE THREAD

**Issue by oison111** [tmux/tmux#3150]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

Pane line is very thin, the mouse is not convenient to locate, how to adjust thick
![image](https://user-images.githubusercontent.com/102855127/162482060-bb78bc97-9d7d-4572-889c-fbdb1e2c641d.png)

**Comment by bfrg** [comment]
It's described in the man page, search for `pane-border-lines` option:
```
     pane-border-lines type
             Set the type of characters used for drawing pane borders.  type may be one of:

             single  single lines using ACS or UTF-8 characters

             double  double lines using UTF-8 characters

             heavy   heavy lines using UTF-8 characters

             simple  simple ASCII characters

             number  the pane number

             ‘double’ and ‘heavy’ will fall back to standard ACS line drawing when UTF-8 is
             not supported.
```

**Comment by oison111** [comment]
> It's described in the man page, search for `pane-border-lines` option:
> 
> ```
>      pane-border-lines type
>              Set the type of characters used for drawing pane borders.  type may be one of:
> 
>              single  single lines using ACS or UTF-8 characters
> 
>              double  double lines using UTF-8 characters
> 
>              heavy   heavy lines using UTF-8 characters
> 
>              simple  simple ASCII characters
> 
>              number  the pane number
> 
>              ‘double’ and ‘heavy’ will fall back to standard ACS line drawing when UTF-8 is
>              not supported.
> ```

I don't have that option in my Man TMUx
![image](https://user-images.githubusercontent.com/102855127/162565419-6d2c63dd-fd40-4535-921b-bd088f29842f.png)
![image](https://user-images.githubusercontent.com/102855127/162565491-f40474fa-3f38-434d-94b2-b7ed3ca0d008.png)
