### ISSUE TITLE
Ask some questions as a beginner to use tmux. thanks.

### ISSUE THREAD

**Issue by Brannua** [tmux/tmux#3151]
Hello,

> I have tried to search Google but only have got few useless information, so I wonder if I can get some help from you. thanks.

Tmux is an execellent program, and I am learning how to use it in my daily work currently.
But I am really curious about:

 1. why the original terminal of tmux can not be scrolled, and why the designer of tmux didn't implement a scrollbar by default.
 2. I know tmux can be scrolled by tap `ctrl + b + [`, but how to implement a scroll bar ? does it the same as `ctrl + b + [` ?
 3. why the scroll function need to be triggered optionally instead of by default ?
 4. why every hot key need to start with `ctrl + b` ?

looking forward to your reply, thank you very much.

**Comment by nicm** [comment]
github lost this replay as well:


1 there is no mechanism for tmux to trigger the external terminal to scroll or to have any control over its scrollback

2 apart from mintty, no terminal provides a way for tmux to control its scrollbar. tmux implementing its own scrollbar is possible but it would be one character cell wide and take up space

3 what does "by default" mean? how would tmux know when to trigger it if you don't tell it?

4 if tmux used all the keys without c-b, how would you control the application inside tmux?

**Comment by Brannua** [comment]
> github lost this replay as well:
> 
> 1 there is no mechanism for tmux to trigger the external terminal to scroll or to have any control over its scrollback
> 
> 2 apart from mintty, no terminal provides a way for tmux to control its scrollbar. tmux implementing its own scrollbar is possible but it would be one character cell wide and take up space
> 
> 3 what does "by default" mean? how would tmux know when to trigger it if you don't tell it?
> 
> 4 if tmux used all the keys without c-b, how would you control the application inside tmux?

Thank you for your reply.

1. How can I implement a scrollbar inside tmux ?

2. If it is possible that you can control applications using hot key without c-b inside tmux when focusing on it ? If not, what's the main factor ?

**Comment by nicm** [comment]
1) I think you would need to read the code and come up with a proposal for how it would work. If you just want a scrollbar in copy mode, then it would not be too hard, look at `window-copy.c`, if you want it for every pane then it would need to make each pane one column narrower, a bit like the pane status line does (but makes it one row smaller).

2) I don't know what this means.

**Comment by Brannua** [comment]
> 1. I think you would need to read the code and come up with a proposal for how it would work. If you just want a scrollbar in copy mode, then it would not be too hard, look at `window-copy.c`, if you want it for every pane then it would need to make each pane one column narrower, a bit like the pane status line does (but makes it one row smaller).
> 2. I don't know what this means.

Thank you, I will try my best to read the code of `window-copy.c` even though It's a little difficult for me.
Besides, I means that If the prefix `c-b` can be ellipsis when your mouse is focusing on pane of tmux ?
(Sorry but I'm learning English, so my expression may cause your confusion. If you don't understand my words, just told me.)

**Comment by nicm** [comment]
When a terminal sends a key like `C-c` to tmux, nothing tells it whether it should handle it itself, or pass it to the application running inside. That's why you need the prefix.

**Comment by Brannua** [comment]
> When a terminal sends a key like `C-c` to tmux, nothing tells it whether it should handle it itself, or pass it to the application running inside. That's why you need the prefix.

Oh, I see ! Thank you very much !

**Comment by nicm** [comment]
1 there is no mechanism for tmux to trigger the external terminal to scroll
or to have any control over its scrollback

2 apart from mintty, no terminal provides a way for tmux to control its
scrollbar. tmux implementing its own scrollbar is possible but it would be
one character cell wide and take up space

3 what does "by default" mean? how would tmux know when to trigger it if
you don't tell it?

4 if tmux used all the keys without c-b, how would you control the
application inside tmux?
