### ISSUE TITLE
[Alt-Click Move Cursor Not Work] fail to move cursor in tmux

### ISSUE THREAD

**Issue by hiberabyss** [tmux/tmux#3152]
### Issue description

Terminal and iTerm2 both support use `alt-click` to move cursor, however, this feature doesn't work in tmux.

### Required information

Please provide the following information:

* tmux version (tmux 3.2a).
* Platform (Darwin arm).
* $TERM inside and outside of tmux (screen-256color).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
seems like more to do with them than with tmux,

**Comment by hiberabyss** [comment]
What kinds of issue may cause the problem? Any clue to solve it? Thanks!

**Comment by nicm** [comment]
probably the terminal disables it for full screen applications which
control the cursor themselves
