### ISSUE TITLE
feature: add option to show ansi colors in view mode

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3156]
Tmux run-shell "view mode" is great for displaying command outputs in a pane without interfering with the user's current I/o interaction with existing foreground process group in the pane (and in turn corrupting the state of the foreground process, etc). At the moment the run-shell command output displays raw escape sequences instead of interpreting them and showing colorized output. It would be nice to have an option for run-shell that would interpret the ansi color sequences and show colorized output.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/8497849/x.diff.txt)

**Comment by reportaman** [comment]
@nicm Didn't do anything... Try the following sequence:

```
tmux bind-key x 'run-shell "printf \"\e[0m\e[38;5;2m\e[3mHello World\e[0m\""'
```

Or use some other tool like [lolcat](https://github.com/jaseg/lolcat) to insert escape sequences like:

```
tmux bind-key x 'run-shell "echo helloworld | lolcat"'
```

**Comment by nicm** [comment]
Works for me, are you sure you are running the right tmux binary?

**Comment by bfrg** [comment]
@nicm Is that the right patch that you uploaded? Doesn't look like it's related to `run-shell`.

**Comment by nicm** [comment]
Ah yes it is wrong, let me find the right one.

**Comment by nicm** [comment]
Try this instead: [x.diff.txt](https://github.com/tmux/tmux/files/8499366/x.diff.txt)

**Comment by reportaman** [comment]
Still doesn't work...

**Comment by nicm** [comment]
Try this please: [y.diff.txt](https://github.com/tmux/tmux/files/8499400/y.diff.txt)

**Comment by reportaman** [comment]
@nicm Now one bind-key works, other doesn't. I wonder if there is something wrong with the pipe...

Works:
```
tmux bind-key x 'run-shell "printf \"\e[0m\e[38;5;2m\e[3mHello World\e[0m\""'
```

Doesn't work:
```
tmux bind-key x 'run-shell "echo helloworld | lolcat"'
```

**Comment by nicm** [comment]
You probably need to tell it to use colour even when stdout is not a tty eg
for git "git diff --color=always".

**Comment by reportaman** [comment]
@nicm Ah I see, works now with -f (force flag)!

```
tmux bind-key x 'run-shell "echo helloworld | lolcat -f"'
```

**Comment by reportaman** [comment]
@nicm There is one problem... tmux is collapsing multiple newlines into a single newline. Try the following:

```
tmux bind-key x 'run-shell "printf \"\n\n\n\n\n\n\e[0m\e[38;5;2m\e[3mHello\n\n\n\n\n\n World\e[0m\""'
```

**Comment by nicm** [comment]
Try doing this as well:
~~~~
@@ -227,7 +222,8 @@ cmd_run_shell_callback(struct job *job)
        int                              retcode, status;

        do {
-               if ((line = evbuffer_readline(event->input)) != NULL) {
+               line = evbuffer_readln(event->input, NULL, EVBUFFER_EOL_LF);
+               if (line != NULL) {
                        cmd_run_shell_print(job, line);
                        free(line);
                }

**Comment by reportaman** [comment]
@nicm The newline issue got fixed, clipping still remains. Try this, the text will get clipped at the width of the pane. Zooming the pane doesn't reveal the remaining text nor is it wrapped. Ideally it would be wrapped like in a text file

```
tmux bind-key x 'run-shell "printf \"\n\n\n\n\n\n\e[0m\e[38;5;2m\e[3mHello\n\n\n\n\n\nWorld...................................................................................xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\e[0m\""'
```

**Comment by reportaman** [comment]
Also, the view mode buffer seems to be in append mode. Try hitting <prefix>x multiple times back to back, it keeps on appending to the temporary view mode buffer. If it makes sense to keep it that way, then at least having a command to clear view mode would help. Just like ``clear`` command does in bash/zsh.

**Comment by nicm** [comment]
Clipping is just going to stay as it is for the moment. If you want to clear then exit and enter again.

**Comment by reportaman** [comment]
@nicm Ok thanks! Hope you would add enhancement item for view mode.

**Comment by nicm** [comment]
Applied now, thanks!
