### ISSUE TITLE
display-popup: make -t overlay the target pane/window?

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3158]
The man page lists ``-t target pane`` option. In my testing it doesn't seem to do visually do anything. What is its purpose? I was thinking that specifying ``-t target pane`` would size and overlay a popup on the target pane/window.

As a sidenote the documentation still says "Panes are not updated while a popup is present." which might need to be removed as they are updated now...

**Comment by reportaman** [comment]
Maybe -t paneid just changes the meaning of x/y position to be relative to that pane, and the % width/ %height to be relative to that pane.

**Comment by krader1961** [comment]
> Maybe -t paneid just changes the meaning of x/y position to be relative to that pane, and the % width/ %height to be relative to that pane.

It seems simple enough to perform some tests to verify (or refute) that hypothesis. Maybe do so then decide if the documentation should be reworded to clarify the behavior?

**Comment by nicm** [comment]
It was probably copied from `display-menu` but the only effect for `display-popup` is to set which pane formats are expanded for `-T`, it could probably be removed.

**Comment by nicm** [comment]
Oh I lie, its not just formats for `-T`, also formats for `-x` and `-y` for example `popup_pane_top`.

**Comment by reportaman** [comment]
For those who might come here looking for example usage. The following 4 commands will locate a popup that is 10% wide (10% of window size) at one of the 4 corners of a pane.

```
❯ tmux display-popup -y "#{popup_pane_top}" -x "#{popup_pane_right}" -w '10%'
❯ tmux display-popup -y "#{popup_pane_top}" -x "#{popup_pane_left}" -w '10%'
❯ tmux display-popup -y "#{popup_pane_bottom}" -x "#{popup_pane_left}" -w '10%'
❯ tmux display-popup -y "#{popup_pane_bottom}" -x "#{popup_pane_right}" -w '10%'
```
