### ISSUE TITLE
Tmux crashes when doing run-shell with a not existing pane

### ISSUE THREAD

**Issue by netei** [tmux/tmux#316]
If i'm in a completely new tmux session, without opening any extra splits or anything,

and run 

`tmux run-shell -t '%1' "ls"`

I get the message `[lost server]` and tmux crashes completely.

It also happens with an empty .tmux.conf

If the pane exists or the command returns 0, tmux doesn't crash.

Shouldn't the command rather output an error instead of completely crashing tmux ?

tmux -V is `tmux 2.1`

**Comment by nicm** [comment]
Does it happen in master from Git?

**Comment by netei** [comment]
I've just compiled it from master, and yes, the problem still appears

**Comment by ThomasAdam** [comment]
It doesn't crash for me.

Can you get a backtrace from a corefile for us to look at?

Thomas

**Comment by netei** [comment]
Indeed, my mistake, the problem doesn't appear anymore on the latest tmux
