### ISSUE TITLE
Cannot set window level after-rename-window hook

### ISSUE THREAD

**Issue by Frederick888** [tmux/tmux#3161]
### Issue description

According to manual:

> Like options different hooks may be global or belong to a session, window or pane.

However `after-rename-window` doesn't seem to be available on window level. For instance:

1. Start tmux with `tmux -f/dev/null -vv new`
2. Open a new window
3. `tmux set-hook -w 'after-rename-window' 'display-message hello'`
4. Back to the default window
5. `tmux show-hooks -w` output is empty
6. `tmux show-hooks` shows the hook created in Step 3
7. `tmux rename-window` triggers `display-message hello`

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `next-3.4` (built from e0c982c5adf54fcfc7c6e588b1350fd8ae474310)
* Platform (`uname -sp`). `Linux unknown` (Arch)
* $TERM inside and outside of tmux (`echo $TERM`). `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-1400895.log](https://github.com/tmux/tmux/files/8497157/tmux-client-1400895.log)
[tmux-out-1400897.log](https://github.com/tmux/tmux/files/8497158/tmux-out-1400897.log)
[tmux-server-1400897.log](https://github.com/tmux/tmux/files/8497159/tmux-server-1400897.log)

**Comment by nicm** [comment]
All after hooks are session hooks.

**Comment by Frederick888** [comment]
@nicm Should I submit a PR to remove this sentence?

**Comment by nicm** [comment]
It seems accurate to me. Some hooks are session, some window, some pane.

**Comment by Frederick888** [comment]
Oh 'all _after_ hooks'... Sorry it's getting late here and my mind is a tad foggy...

I'll close this then :) Thanks for the clarification.
