### ISSUE TITLE
Display error when opening a new window

### ISSUE THREAD

**Issue by JamesZhutheThird** [tmux/tmux#3162]
### Issue description

When using tmux with zsh, there is a bug as shown below
![2022-04-16 23-51-56](https://user-images.githubusercontent.com/35760593/163682165-4f60041e-2f86-4e08-8820-6b9b6e76ae2a.gif)

I've set `set -g default-terminal "screen-256color"` in `.tmux.conf`, thx a lot, and wish you a good day😊

### Required information

Please provide the
 following information:

* tmux version (`tmux -V`). `tmux 3.2a`
* Platform (`uname -sp`).  `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`). `xterm-256color` `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by reportaman** [comment]
Does this only happen with zsh inside tmux? I had a similar problem with zsh on a new user account on my machine, it had turned out that zsh plugin system I had installed was not able to find lua. When I added path to lua binary in my PATH environment variable in .zshrc, the problem went away.

**Comment by nicm** [comment]
This means nothing to me, what am I looking at? What is the bug? What terminal are you using? Where are the tmux logs?

**Comment by JamesZhutheThird** [comment]
Well actually I don't know how to explain this bug, when using zsh inside of tmux, the cursor is located in the line above.

Expected
<img width="915" alt="屏幕截图 2022-04-18 164003" src="https://user-images.githubusercontent.com/35760593/163782163-21055c8a-ed8a-4743-b8e0-d70f24628660.png">

Actual
<img width="920" alt="屏幕截图 2022-04-18 163116" src="https://user-images.githubusercontent.com/35760593/163782135-08c5dbed-6a22-404e-afec-85be1efb237f.png">

I use pycharm terminals in code UTF-8 and here are the log files
[tmux-server-1391.log](https://github.com/tmux/tmux/files/8504641/tmux-server-1391.log)
[tmux-client-1389.log](https://github.com/tmux/tmux/files/8504642/tmux-client-1389.log)
[tmux-out-1391.log](https://github.com/tmux/tmux/files/8504643/tmux-out-1391.log)

**Comment by nicm** [comment]
Are you sure `xterm-256color` is the right `TERM` outside tmux for this terminal? Does the problem go away if you set `TERM` outside tmux to `ansi` or `vt220`? Does this still happen in actual xterm?

**Comment by JamesZhutheThird** [comment]
> Are you sure `xterm-256color` is the right `TERM` outside tmux for this terminal?

As far as I'm concerned, `xterm-256color` is the default `TERM` in the terminal of pycharm. 

> Does the problem go away if you set `TERM` outside tmux to `ansi` or `vt220`? Does this still happen in actual xterm?

I try using the command `export TERM=vt220`, and the problem seems gone.

![outside](https://user-images.githubusercontent.com/35760593/164192654-4e5da814-3db6-4c5f-a1e9-8b0b14a532a8.png)

![inside](https://user-images.githubusercontent.com/35760593/164193178-865a0039-891d-4463-8594-f951cd49efd4.png)

But there are other compatibility issues(`no such terminfo capability`), and I think the problem was somehow hidden because of the error output. I've tried to use default `TERM` settings outside, and disable zsh plugins and themes, but the display problem remains.

Thank you again for your help.

**Comment by nicm** [comment]
This is almost certainly a problem with your terminal, my guess is that it does not support something in `xterm-256color` that it should.

Does it work if you keep `xterm-256color` but do this in .tmux.conf, then restart tmux entirely:
~~~~
set -as terminal-overrides ',xterm*:csr@'

**Comment by JamesZhutheThird** [comment]
Thanks a lot, the problem was solved perfectly using this command. 

> Why is it complaining about missing capabilities _inside_ tmux? Are you sure TERM is set to `screen-256color` inside tmux?

I think that's the key point, it seems the TERM was set to `screen-256color` inside tmux incompletely before.

**Comment by JamesZhutheThird** [comment]
I will report this problem to them later. BTW, what may be the potential impact on my usage after removing `csr`?

**Comment by JamesZhutheThird** [comment]
I think I can go with that. Anyway, thanks again for your help.
