### ISSUE TITLE
Fails matching an option during the start up (works after the reload, though)

### ISSUE THREAD

**Issue by 097115** [tmux/tmux#3163]
### Issue description

I have the following snippet in my `~/tmux.conf`:

    # Detect OS 
    %if "#{m:\/home*,$HOME}"
        set-option -g @OS 'linux'
    %else
        set-option -g @OS 'darwin'
    %endif 

And then, later in the `.tmux.conf`, I'm also trying to map some platform-dependent mappings like this:

    %if "#{m:*linux*,#{@OS}}"
        [linux-specific bindings]
    %else
        [darwin-specific bindings]
    %endif
    
However, the problem is that the conditional doesn't matches during the start up (while on `linux`, it still maps keys as it were `darwin`). But if I reload my configuration with `source-file ~/.tmux.conf`, everything becomes OK. The `@OS` option itself seems to be set correctly (`display-message "#{@OS}"` after the start up reports `linux` as it should).

### Required information

* tmux version: 58d1a206
* Platform (`uname -sp`): Linux x86_64

**Comment by nicm** [comment]
`%if` is handled when the config file is parsed but `@OS` will not be set until the `set-option` is executed which will be later on.

**Comment by 097115** [comment]
@nicm 

So, introducing this user option is actually redundant, and when doing anything platform-specific, I just have to detect it again and again (like, `keep doing %if "#{m:\/home*,$HOME}"...`)?

**Comment by nicm** [comment]
You can do that, or you could use an environment variable instead with something like `%hidden OS=linux`, but you cannot use a user option unless you use `if-shell -F` instead of `%if`.

The config file is parsed to generate a big list of commands and then those commands are executed. `%if` takes place at the first step.

**Comment by 097115** [comment]
Thanks for the explanation!
