### ISSUE TITLE
tmux is killing an application in x11 mouse mode because of the coordinate overflow

### ISSUE THREAD

**Issue by leonid-s-usov** [tmux/tmux#3164]
The x11 mouse mode with `kmous=\E[M` has a limitation for the maximum coordinates it can encode. Not only the button (first param) but also the Cx and Cy chars will only carry up to 222 maximum offset.

This is a sad limitation but wouldn't be fatal if not a bug in tmux. If tmux receives coordinates in the SGR mode, they can exceed 222; then tmux will [blindly translate those into x+33](https://github.com/tmux/tmux/blob/bf14bf6259a03d83502e281a34d88296faaa02dc/input-keys.c#L620) and happily send the result to the application.

The overflow of coordinates will inevitably get to sending \002 or \003 in place of the Cx or Cy, which will suspend or kill the application.

**Comment by nicm** [comment]
This is intentional as it gives greater range, but I'm not sure where it
came from - xterm clamps to 223, so perhaps we should too.

**Comment by nicm** [comment]
We used to clamp it but it was changed in bf635e774, I don't remember if this was due to a particular suggestion...

**Comment by nicm** [comment]
Oh wait read that wrong, that's only buttons too...

**Comment by nicm** [comment]
Ah it was changed in 66f4c60a8477e0cf9eb059e7687ca524f135e442.

**Comment by nicm** [comment]
I don't remember why this was done but even if it was useful, you are correct that we can't know if the application is going to interpret it as intended, and we now have SGR mouse mode anyway, so it can probably be safely restored.

**Comment by leonid-s-usov** [comment]
The old code you mentioned wasn't OK either, IMO. 
The problem with the version edited out by 66f4c60 is that it will avoid sending the event if any _one_ of the coordinates is above 222. I think it's a problem, cause we could've still benefited from the second meaningful coordinate even if one has reached the limit.

We could consider doing here 

    if (m->xb > 223 || (m->x > 222 && m->y > 222))
        return;

this would've made a bit more sense, as we'd just prevent sending repeated coordinates, although xterm does repeatedly send the clamped value IIRC.

**Comment by nicm** [comment]
I'd just clamp them to 222 but don't use min(), use an if or ?:
