### ISSUE TITLE
kitty like hints feature

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#3166]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).`tmux 3.2a`
* Platform (`uname -sp`). `Archlinux`
* $TERM inside and outside of tmux (`echo $TERM`). `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

Kitty terminal has a wonderful feature called [hints](https://sw.kovidgoyal.net/kitty/kittens/hints/), using some kitty bindings you can get almost any object in the visual text in the terminal such as `word`, `link`, `path`, `line`:
```
map kitty_mod+e open_url_with_hints
map kitty_mod+p>f kitten hints --type path --program -
map kitty_mod+p>shift+f kitten hints --type path
map kitty_mod+p>l kitten hints --type line --program -
map kitty_mod+p>w kitten hints --type word --program -
map kitty_mod+p>h kitten hints --type hash --program -
map kitty_mod+p>n kitten hints --type linenum
map kitty_mod+p>y kitten hints --type hyperlink
```
I know this feature may need a lot of work, how about implementing such feature inside tmux, so this can be done with any terminal, even when running tmux from remote server?

**Comment by nicm** [comment]
GitHub lost my reply to this:

How is this different from using capture-pane or display-message with formats to get information? How would such a feature actually look in tmux? What would it actually be useful for?

**Comment by c02y** [comment]
You can read the page for details https://sw.kovidgoyal.net/kitty/kittens/hints/

tmux `capture-pane` is to capture the content of a pane into stdout or a buffer/file, you need to do some data processing again to get the object in it.

tmux `display-message` has nothing to do with it.

It is used to copy or even open the object(word/link/line/path) without using mouse or move your keyword around inside the visual text in tmux panes.

I found a few third party plugins(https://github.com/fcsonline/tmux-thumbs, https://github.com/Morantron/tmux-fingers, https://github.com/laktak/extrakto) for tmux that implement such feature, but they are not working very well.

I believe tmux would be even greater with this feature included.
Check kitty's code for the hints implement https://github.com/kovidgoyal/kitty/tree/master/kittens/hints

**Comment by nicm** [comment]
Right, I can read it, but typically for kitty it is completely vague and next to useless (there is not even a sensible screenshot). To me this seems like nothing more than searching by regexp or using `capture-pane` with `grep` - both of which you can already do. So I am asking exactly what you would see changing in tmux - do you want to be able to have tmux show a menu with a list of search matches in the copy mode? Do you want it to have shortcut keys for visible matches? Or what?

**Comment by nicm** [comment]
So tmux-fingers seems to highlight stuff with a shortcut key to copy it? Is that what you're suggesting? What's wrong with tmux-fingers?

**Comment by c02y** [comment]
1: needs too many scripts or other dependencies (this is my personal problem, I like KISS)
2: some kinds of objects such as file name or simple string are not handled
3. only work inside **current** pane

**Comment by nicm** [comment]
You're making it too hard to guess what you'd like to see tmux do, I don't have time to read a load of web pages and try a bunch of other apps to figure it out.

**Comment by nicm** [comment]
All I've worked out so far is:

- you want tmux to be able to search for some stuff in panes, to me this seems like a list of different regexps (one for paths, one for URLs, etc);

- it's not like grep, `find-window`, the existing copy mode searching, etc;

- I assume you will trigger this with a key press? but its not clear if it is one key press for all regexps or one for each?

- it looks like it would highlight stuff it found in a pane, but somehow this will work across multiple panes?
 
- then you can choose each bit of stuff somehow (looks like by a shortcut key?), then it would do something - copy it?

There are lots of ways we could do extended searching, so how do you see this working? What commands would we add to tmux? What keys would you press and what would heppen?

**Comment by c02y** [comment]
Basically:
1. trigger a tmux key binding
2. different kinds of object such as link, file name, path, git commit id, will be highlighted and every object is started with 1 or more unique letters or numbers that user can type, the object the user typed will be copied to system clipboard, 
 

Demo of tmux-fingers:
![Peek 2022-04-28 15-29](https://user-images.githubusercontent.com/2135996/165701967-2a0c701b-ba3e-43f9-aa81-44f48d4419e3.gif)


Demo of kitty hints:
![Peek 2022-04-28 15-33](https://user-images.githubusercontent.com/2135996/165702006-c2ceb99c-6509-4b8e-b0b8-c8a6f28c2af4.gif)


BTW: `work across multiple panes` is not a must-have feature

**Comment by nicm** [comment]
What happens when you select one? Looks like it copies it? I think it would be better if it just jumped the cursor to it myself.

It seems that basically all we would need to do here is add shortcut keys to the first 10 matches of the current regex searching, then you could just bind keys with your own regexs, or create a menu of them, or whatever you like.

**Comment by nicm** [comment]
`0` to `9` keys are free in emacs mode and `M-0` to `M-9` free in vi mode, so we could just use them. We could number them as 0-9 then 00, 11, 22, ... (so if you are already on 0 and press 0, it goes to 00) - that would give us 20 which seems enough.

I think having shortcut keys for the first 20 matches would be a good start, then we could add some default keys or a menu with regexps for obvious stuff like paths etc.

It might be nice if there was a way to search for multiple regexps at the same time (like multiple arguments to `search-backward`).

Maybe this is all something @topcat001 is interested in looking at?

**Comment by c02y** [comment]
> What happens when you select one? Looks like it copies it? I think it would be better if it just jumped the cursor to it myself.

Copy it to system clipboard, I personally rarely use the current tmux's copy mode and select use key and copy, I would rather use my mouse and select.


> It seems that basically all we would need to do here is add shortcut keys to the first 10 matches of the current regex searching, then you could just bind keys with your own regexs, or create a menu of them, or whatever you like.

Sounds complicated, do the users need to the regex thing? Can the tmux identify the *useful objects* things under the hood and highlight them with letters/numbers.

**Comment by nicm** [comment]
No, everyone will have a different definition of useful, so we should make it so you can configure the regexps and then offer a sensible default list.

**Comment by c02y** [comment]
> `0` to `9` keys are free in emacs mode and `M-0` to `M-9` free in vi mode, so we could just use them. We could number them as 0-9 then 00, 11, 22, ... (so if you are already on 0 and press 0, it goes to 00) - that would give us 20 which seems enough.

Disable all vim or emacs modes when in this hints mode.

> 
> I think having shortcut keys for the first 20 matches would be a good start, then we could add some default keys or a menu with regexps for obvious stuff like paths etc.

If there are a small number of targets, use single numbers and letters, if single letters and numbers are not enough, use double numbers and letters or mixed of number/letters.

**Comment by c02y** [comment]
> No, everyone will have a different definition of useful, so we should make it so you can configure the regexps and then offer a sensible default list.

Maybe they are configurable into a list, such as filenames, links, IP, plain words, git commit ids or other types of objects.

**Comment by nicm** [comment]
I think this should fit in with copy mode and the way it works at the moment, not be a special mode.

It seems more useful if we add commands, so we have something like (not sure about the names):

- `search-backward-and-number`
- `jump-to-number`
- `copy-number-and-cancel`

Then we bind default keys like:

```
bind -Tcopy-mode U send -X search-backward-and-number useful-stuff-regexp1 useful-stuff-regexp2
bind -Tcopy-mode 0 if -F '#{==:#{search_number},0}' { send -X jump-to-number 00 } { send -X jump-to-number 0 }
````
So you can use `0` or `00` to jump directly to that match, and then use `C-w` to copy it as normal.

Or people who prefer can bind keys to copy the match directly.

I would probably make it so that if `search-backward-and-number` is called without arguments, it looks at an option, so we could put various default regexps in the option and people could easily change them without binding keys (same idea as for `copy-command`).

**Comment by nicm** [comment]
Or maybe you could just type the number and it moves to in incrementally, a bit like the way the repeat count/incremental search works, so when you type `1` it goes to match 1 then if you type `2` it goes to match 12. Then a non-number key will run a command. That would be easy enough to do I think.

**Comment by bfrg** [comment]
FWIW, I use the following to navigate between URLs in the current pane, and then open in `$BROWSER` or copy to clipboard:

```tmux
# Search for URLs in current pane with prefix+u:
#
#   - navigate with n/N
#   - open current match in $BROWSER with Enter
#   - copy current match with y (copy-mode-vi)
#
# See also:
#   https://github.com/tmux/tmux/wiki/Recipes#c-doubleclick-to-open-emacs1
#
set-option -g @url_pattern '\b((https?|ftp|news)://|git@\w+\.\w+:|www[0-9]?\.)[A-Za-z0-9&@#/%$?=~_!.,:;+-]*[A-Za-z0-9&@#/%=~_+-]'
bind-key -N 'Search for URLs in current pane' u {
    copy-mode
    send-keys -X start-of-line
    send-keys -X bottom-line
    send-keys -X -F search-backward '#{@url_pattern}'
}

# Open current match in BROWSER if and only if it looks like a URL
bind-key -T copy-mode-vi Enter {
    if-shell -F "#{&&:#{&&:#{search_present},#{search_match}},#{==:#{pane_search_string},#{@url_pattern}}}" {
        send-keys -X copy-pipe-no-clear 'sed -E "s/^git@(\\w+\\.\\w+):(.*)\$/https:\\/\\/\\1\\/\\2/" | xargs -I {} $BROWSER "{}"'
    } {
        send-keys -X copy-pipe-and-cancel
    }
}

# Copy current match to clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe 'xclip -i -selection clipboard'
```

It's KISS and the regex pattern can be extended to search for files, file locations like `/path/to/file:12:2:`, git sha, etc. The only downside is that you don't have those _hints_, instead you need to navigate with `n` or `N`, though you can use a count like `3n` to jump to the 3rd URL above the current only.

I don't know, maybe there's an even simpler way to do the above.

**Comment by nicm** [comment]
Yes because it is so easy to script I am thinking that we are 90% of the way there already, all we really need is a way to assign shortcut keys to search hits so you can jump to them directly rather than needing to step through them.

Then we can have a default builtin list of regexps easily enough, I'm not averse to that, but people will definitely want to change it.

**Comment by topcat001** [comment]
Yes, a concrete and useful first step would be to add hinting (i.e., display a short alphanumeric label) next to copy mode search results, in regexp mode or otherwise. Stepping through them is slightly tedious currently. The rest can possibly be just scripting regexes (we can include a few sensible keybindings OOTB).

I prefer keeping the core code as simple as possible so stuff like text objects (which might mean different things to different people) might be best handled by keybindings and regexes.

**Comment by nicm** [comment]
I have added this to the todo list.

**Comment by nicm** [comment]
How is this different from using capture-pane or display-message with
formats to get information? How would such a feature actually look in tmux?
What would it actually be useful for?

**Comment by topcat001** [comment]
Hi, I did not get to spend much time on this, but given existing functionality, this is at best a "nice to have". One use case I can think of is when there are many matches in the visible area and one wishes to quickly move the cursor to a particular match. Right now this requires running search-again a bunch of times to move the cursor. However, this is not really that different from an editor.

Besides kitty (which I have never used), qutebrowser has a nice hinting feature for keyboard based hyperlink navigation. Something like this could be overlaid on the search highlighting when a key is pressed (a hint toggle command).

________________________________________
