### ISSUE TITLE
Question: Are we sure delivery of winch is done after pane dimensions visible to shell have been updated?

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3167]
In a zsh-based terminal program that I am working on, if I increment the height of tmux by 1 and immediately decrement it (perhaps repeatedly), part of WINCH handler sees old height and other part see new height. This happens only once in a while, not all the time... I guess I have disabled nesting of winch handlers by setting ``trap '' WINCH`` in the beginning of handler itself. One suspicion seems to be that tmux delivers winch asynchronously w.r.t updating pane dimensions made available to shells running in panes (i.e. there is a race in updating pane dimensions and sending winch). Can you please check? 

iTerm2
zsh 5.8.1
tmux latest commit 58d1a206c6ae6b33059ea6b469c21dad92ea0841
xterm-256 outside, tmux-256 inside
source: closed source :(

**Comment by nicm** [comment]
tmux is not responsible for sending SIGWINCH, the kernel will do it when
tmux sets the pty size with TIOCSWINSZ

**Comment by reportaman** [comment]
Thanks, then this could be a question for some other forum. Before you close: Could it be that when a winch handler is active for first TIOCSWINSZ, that a new second TIOCSWINSZ interferes with ongoing handler for first TIOCSWINSZ? If two commands in the handler rely on COLUMNS & LINES variables, one could see the first value and the other could see the second value? If yes then seems like it would be ideal to use only one command ``stty -a <"$TTY"`` per handler to extract width and height for the WINCH (also not sure if COLUMNS and ROWS are updated atomically...).

**Comment by nicm** [comment]
That entirely depends on how the program handles it.

**Comment by reportaman** [comment]
Ok thanks!
