### ISSUE TITLE
status bar updates with new line every minute

### ISSUE THREAD

**Issue by rachamaduguravi** [tmux/tmux#3168]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

tmux next-3.4

* Platform (`uname -sp`).

Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).

tmux-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).

please can check screenshot for seeing the status bar issue

![tmux](https://user-images.githubusercontent.com/30033448/164992947-5c640d50-08e5-470d-ab23-6d5dfbf10559.jpg)

**Comment by rachamaduguravi** [comment]
hi, just now, the local internet provider restarted the near by router and above issue is resolved, thanks!

**Comment by nicm** [comment]
> $TERM inside and outside of tmux (echo $TERM).
> tmux-256color

You probably don't want to use TERM=tmux-256color outside tmux unless you
are running tmux inside tmux.
