### ISSUE TITLE
how can i get the resutl of send -t "xxx"

### ISSUE THREAD

**Issue by iakirago** [tmux/tmux#3169]
i have a question, 
1. tmux new -s demo -d
2. tmux send -t demo "ps -ef | grep nginx |grep -v grep | wc -l" C-m
how can i get the result of "ps -ef | grep nginx |grep -v grep | wc -l"

**Comment by nicm** [comment]
Use `capture-pane`.

**Comment by iakirago** [comment]
> Use `capture-pane`.

like this?

tmux send -t demo "tmux capture-pane -S >> ./gotest" C-m

but i got nothing when i use "cat ./gotest"

**Comment by iakirago** [comment]
> You need `-p` to send to stdout, so `capture-pane -p -S- -E-` will capture the entire pane, look at https://man.openbsd.org/OpenBSD-current/man1/tmux.1#capture-pane.

thank you very much!
