### ISSUE TITLE
RGB color test failure

### ISSUE THREAD

**Issue by assaf758** [tmux/tmux#317]
While trying 24bit-color support, I noticed there is some issue (when comparing to non-tmux terminal) - see http://ibin.co/2YAmCLcoBNRC.
Happens with two tests (see below) and two terminals (termite and gnome-terminal):
https://raw.githubusercontent.com/robertknight/konsole/master/tests/color-spaces.pl
https://github.com/gnachman/iTerm2/blob/master/tests/24-bit-color.sh

tmux version: git commit e9d369a09e48ea8f940958025c8444988d31e840
termite: v11 (latest on linux Manjaro)

**Comment by nicm** [comment]
Try this please 
[x.txt](https://github.com/tmux/tmux/files/152759/x.txt)
