### ISSUE TITLE
Sessions should not be allowed to nest themselves.

### ISSUE THREAD

**Issue by auoeke** [tmux/tmux#3170]
### Description
Sometimes I need to nest sessions (for example in order to manage a detached session and return to the parent session). When I occasionally unintentionally attach a session to itself, the display seems to recurse endlessly and I lose control of the session (I can only kill it externally; the prefix does not seem to do anything). tmux should not allow a session to be attached if any of its enclosing sessions is itself.

### Reproduction
- Run `tmux`.
- Run `TMUX= tmux attach-session -t $(tmux display-message -p "#S")`.

### Environment
- `uname -sp`: `Linux unknown`
- `tmux -V`: `tmux next-3.4`
- `echo $TERM` outside tmux: `xterm-256color`
- `echo $TERM` inside tmux: `screen-256color`
- Platform: Artix Linux
- [Logs](https://gist.github.com/auoeke/df9fb9b344991f35146dfb82944652aa)

**Comment by nicm** [comment]
It doesn't allow it unless you unset `TMUX`, so don't do that.

**Comment by auoeke** [comment]
Then I can't nest sessions at all and there does not seem to be an alternative beside running a new terminal that spares me the trouble of having to keep track of session names.

**Comment by nicm** [comment]
Switch the client to the session instead of nesting.

**Comment by auoeke** [comment]
That does the job; thanks.
