### ISSUE TITLE
whenever i start emacs, the mouse doesn't work.

### ISSUE THREAD

**Issue by SadSock** [tmux/tmux#3173]
### Issue description

I'm using tmux 3.2a on ubuntu 18.04. $TERM=screen-256color. I'm also using ``set -g mouse on

whenever i start emacs, the mouse doesn't work.

before i start emacs, i can switch panel by mouse.
Once I start emacs, I can't switch panel with the mouse.

### Required information

Please provide the following information:

* tmux version (`tmux 3.2a`).
* Platform (`ubuntu 18.04`).
* $TERM inside and outside of tmux (both `xterm-256color`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by SadSock** [comment]
whenever i start emacs, the shape of cursor will become I from arrow.
I'm using putty.

**Comment by nicm** [comment]
The mouse doesn't work in emacs or in tmux?

**Comment by SadSock** [comment]
> 
in tmux

**Comment by nicm** [comment]
Show logs please.
