### ISSUE TITLE
[server exited unexpectedly] with pipe-pane

### ISSUE THREAD

**Issue by bfrg** [tmux/tmux#3174]
### Issue description

Open a new tmux session:
```bash
$ tmux -Lfoo -f/dev/null
```

Inside tmux run the following commands:
```bash
$ tmux split-window date \; set-option -p remain-on-exit on \; last-pane
$ tmux pipe-pane -I -t '{last}' 'echo 10'
```

Result:
```
[server exited unexpectedly]
```

### Required information

* tmux version `next-3.4`
* Platform Linux
* $TERM inside `tmux-256color` and outside of tmux `alacritty`
* [tmux-client-10710.log](https://github.com/tmux/tmux/files/8597748/tmux-client-10710.log)
* [tmux-out-10712.log](https://github.com/tmux/tmux/files/8597749/tmux-out-10712.log)
* [tmux-server-10712.log](https://github.com/tmux/tmux/files/8597750/tmux-server-10712.log)

**Comment by topcat001** [comment]
Verified. I looked at it quickly and this is what is happening. When the pane with the date command dies, its event structure is freed in `server_destroy_pane`. Later, when something is written to this pane, the even structure is null leading to a crash in `cmd_pipe_pane_read_callback`. @nicm should we abort the write in this case, because the pane is already dead and hence logically const?

**Comment by topcat001** [comment]
Roughly something like this:
```
diff --git a/cmd-pipe-pane.c b/cmd-pipe-pane.c
index aac23a0f..e26fa619 100644
--- a/cmd-pipe-pane.c
+++ b/cmd-pipe-pane.c
@@ -189,6 +189,9 @@ cmd_pipe_pane_read_callback(__unused struct bufferevent *bufev, void *data)
        available = EVBUFFER_LENGTH(evb);
        log_debug("%%%u pipe read %zu", wp->id, available);
 
+       if (!wp->event)
+               return;
+
        bufferevent_write(wp->event, EVBUFFER_DATA(evb), available);
        evbuffer_drain(evb, available);
 ```
@bfrg this will ignore the echo and will avoid the crash. Just a suggestion.

**Comment by nicm** [comment]
The pipe pane should be made to do nothing if the pane is dead.

**Comment by topcat001** [comment]
Should it show an error if an attempt is made to write or just silently ignore it? Maybe an error since we are not supposed to write there.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nicm** [comment]
I don't mind, either would be fine.

**Comment by topcat001** [comment]
I'll post an update soon, thanks!

**Comment by topcat001** [comment]
Here we make `pipe-pane` print an error if the target pane is already dead:
```
diff --git a/cmd-pipe-pane.c b/cmd-pipe-pane.c
index aac23a0f..451a0dd3 100644
--- a/cmd-pipe-pane.c
+++ b/cmd-pipe-pane.c
@@ -67,6 +67,12 @@ cmd_pipe_pane_exec(struct cmd *self, struct cmdq_item *item)
 	struct format_tree		*ft;
 	sigset_t			 set, oldset;
 
+	/* Do nothing if pane is dead. */
+	if (wp->flags & PANE_EXITED) {
+		cmdq_error(item, "target pane is dead");
+		return (CMD_RETURN_ERROR);
+	}
+
 	/* Destroy the old pipe. */
 	old_fd = wp->pipe_fd;
 	if (wp->pipe_fd != -1) {
```
Please have a look, thanks!

**Comment by topcat001** [comment]
Let's leave the callback function as it is. If it crashes then it will help us catch other cases where it should not be called.

**Comment by nicm** [comment]
Applied now, I also made it check if `wp->fd == -1`. Thanks!
