### ISSUE TITLE
#{pane_current_path} is always empty in dead panes

### ISSUE THREAD

**Issue by bfrg** [tmux/tmux#3176]
### Issue description

`#{pane_current_path}` is always empty in dead panes.

Run:
```tmux
:splitw echo test ; set -p remain-on-exit on
:display '#{pane_current_path}'
```
Result: nothing is printed. 

On the other hand, running:
```tmux
:splitw sleep 30 ; set -p remain-on-exit on
:display '#{pane_current_path}'
```
will correctly print the current path, but only as long as the command is running.

I don't understand why `#{pane_current_path}` is cleared. When I respawn a pane, the command will run in the old directory. For example, if I'm in `/tmp` and run:
```tmux
splitw -c ~/ ls ; set -p remain-on-exit on
```
`ls` will be executed in `~/`. I can run `respawn-pane` and `ls` will always run in the same directory. So it seems that the path of the pane is saved internally, it's only `#{pane_current_path}` that is cleared for some reasons.

#### Additional context

I was trying to run `notify-send` inside a hook, something like:
```bash
$ tmux split-window make \; set -p remain-on-exit on \; set-hook -p pane-died "run-shell \"notify-send '#{pane_start_command}' '#{pane_current_path}'\"" \; last-pane
```
but it doesn't work.

### Required information

* tmux version next-3.4
* Platform Linux
* $TERM inside `tmux-256color` and outside of tmux `alacritty`

**Comment by nicm** [comment]
Yes, no process means nothing to get the path from. IIRC you want
pane_start_path.

**Comment by bfrg** [comment]
There's no variable `#{pane_start_path}`. There's only `#{pane_path}` but it's empty just like `#{pane_current_path}`.

**Comment by nicm** [comment]
oh yeah we have pane_start_command not _path, you would need to add it

**Comment by nicm** [comment]
I've added this now.
