### ISSUE TITLE
Where is the TODO list?

### ISSUE THREAD

**Issue by masaeedu** [tmux/tmux#3177]
Hi there. I've been looking at a few issues related to scrollback navigation, all of which were closed after a note indicating that the relevant feature request has been added to the TODO list:

- #3064
- #3102
- #1042

I can't seem to find a TODO list file in the repo, although it appears to have existed at one point. It was apparently removed in 831c67c2d8d18817f93d973ee9ab3b4f174f9dcd, with the note:

> Remove TODO, moving onto website.

Where can I find this website, or wherever it is this list of outstanding issues is currently maintained?

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/Contributing#code-contributions

**Comment by masaeedu** [comment]
Oh, I see. Thank you.
