### ISSUE TITLE
duplicate completion result in prompt

### ISSUE THREAD

**Issue by cevhyruz** [tmux/tmux#3178]
Happens when you define an alias that matches a command name.

```tmux
set-option -ag command-alias[19] choose-tree="choose-tree -F'#{E:_window_tree_format}'"
set-option -ag command-alias[20] choose-buffer="choose-buffer -F'#{E:_window_buffer_format}'"
```

* tmux version: tmux next-3.4

**Comment by nicm** [comment]
Yes, we need it to ignore duplicates when it adds the aliases.

**Comment by nicm** [comment]
Fixed now in master, please test and let me know if you see any problems.
