### ISSUE TITLE
[Feature Request] Allow custom format for tagged items in choose-* mode.

### ISSUE THREAD

**Issue by cevhyruz** [tmux/tmux#3179]
Currently, you can only identify tagged items by being bold and with the symbol `*` which may be a little hard to spot especially when you already have a custom formatted list.

![Screenshot from 2022-05-06 20-37-27](https://user-images.githubusercontent.com/20886353/167132746-50e30520-c38f-419c-8d29-825b841a77e6.png)

PS: FMO a simple reverse attribute will do but It will be really nice to have the custom format :)

**Comment by nicm** [comment]
I don't think we should make this configurable but we could change the style of tagged items to be more obvious.

**Comment by cevhyruz** [comment]
> but we could change the style of tagged items to be more obvious.

Maybe an inverted highlight that is not linked to mode-style?

**Comment by nicm** [comment]
TBH I think this is partly the fault of your colour scheme, making the all the text on the entire line bright *should* stand out much more, you have too little difference between bright and not bright.

But I doubt anyone will mind if we make it reverse as well as bold. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/8737426/x.diff.txt)
