### ISSUE TITLE
The "%" format for referencing panes no longer works break-panes

### ISSUE THREAD

**Issue by ericpruitt** [tmux/tmux#318]
When compiling from the latest version of tmux, attempting to use "break-pane" with "-t" and a "%" indexed pane fails with an error:

    ~$ tmux list-panes
    0: [119x68] [history 29/1048576, 3652 bytes] %3
    1: [119x34] [history 5/1048576, 240 bytes] %0
    2: [119x33] [history 63/1048576, 1799 bytes] %2 (active)
    ~$ tmux break-pane -t %0
    can't specify pane here

Using "%" pane references worked fine with tmux ~2.0

**Comment by ericpruitt** [comment]
To clarify what I mean by "latest version", I'm building tmux from Git hash e9d369a09e48ea8f940958025c8444988d31e840 .

**Comment by nicm** [comment]
The arguments to break-pane have changed and it now supports -s and -t;
-t is the target window. Use -s instead of -t.

**Comment by ericpruitt** [comment]
Thank you; that worked.
