### ISSUE TITLE
running sublimetext inside a reattached tmux (`tmux attach`) causes sublime to hang

### ISSUE THREAD

**Issue by timotheecour4** [tmux/tmux#3180]
### Issue description

This issue has reproducible instructions: https://github.com/sublimehq/sublime_text/issues/3147#issuecomment-590434482 ; copying from there:
```
Here is the reproduce step:

open Terminal.app;

open tmux in terminal;

run subl . in tmux, it shoud be successful.

logout the user;

login again;

open Terminal.app;

Use tmux attach to attach the existing tmux session started before;

run subl . in tmux, it will fail as the poster described: subl hangs, new Sublime Text window opens with empty content.
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
3.2a
 
* Platform (`uname -sp`).
Darwin i386

* $TERM inside and outside of tmux (`echo $TERM`).
screen, xterm-256color

**Comment by nicm** [comment]
Doesn't seem like this is a tmux problem?
