### ISSUE TITLE
`ctrl+tab` and `ctrl+shift+tab` doesn't work in xfce terminal

### ISSUE THREAD

**Issue by sahilrajput03** [tmux/tmux#3181]
### Issue description

`Ctrl+tab` and `ctrl+shift+tab` doesn't work in xfce terminal:

```bash
bind-key -n C-Tab next-window
bind-key -n C-S-Tab previous-window
```

### Required information

Please provide the following information:

* tmux version: tmux 3.2a
* Platform (`uname -a`): `Linux arch-os 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64 GNU/Linux`
* $TERM inside and outside of tmux: screen(inside), xterm-256color(outside) .
* Logs from tmux (`tmux kill-server; tmux -vv new`): I can't get logs idk why .. the command doesn't produce any logs..

**Comment by nicm** [comment]
Does it work on other terminals?

**Comment by sahilrajput03** [comment]
@nicm I don't know.., I don't know how to fix this...
Can you suggest some terminal I can try for which it works for you @nicm ?

**Comment by nicm** [comment]
No, most terminals don't send escape sequences for these keys, that's why I wondered which terminal you were using before to make you think it should work.

You may have luck building tmux on master and setting `extended-keys` to `on` but it will depend on your terminal.
