### ISSUE TITLE
The description of `new-window` in the manual may be outdated.

### ISSUE THREAD

**Issue by marchgithub** [tmux/tmux#3182]
### Issue description

Taken from the `new-window` command's explanation in the manual page:

> target-window represents the window  to be created; if the target already exists an error is shown,
             unless the -k flag is used, in which case it is destroyed.

With an active session named `mc`, with only one window at index 0 with the name `bash`, inputting the command `tmux new-window -t mc:win` gives the error message `can't find window: server`.

If it can't find the window shouldn't it create one?

### Required information

Please provide the following information:

* tmux 3.1c
* Platform (`uname -sp`): Linux unknown (tested on Debian 11 and Gentoo)
* $TERM inside and outside of tmux (`echo $TERM`): xterm (on both sides)
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
It is correct but not very descriptive, you are asking it to create a
window in the same position as one called `win`, which does not exist, so
it can't do it. If you want to create a window called `win` without
specifying a position, use `-n`.
