### ISSUE TITLE
tmux might try to put each pty/pane in a separate cgroup

### ISSUE THREAD

**Issue by mdengler** [tmux/tmux#3183]
From @benzea's comment in #3024:

> we want to separate each of the pty's into a separate cgroup. The purpose is so that when the OOM killer (i.e. systemd-oomd) kills an entire cgroup, only the processes for one pty are killed rather than also including tmux itself and all other pseudo terminals.
> [... it is actually solvable entirely without dbus ...]

_Originally posted by @benzea in https://github.com/tmux/tmux/issues/3024#issuecomment-1004166931_

I would love to help with this, as my tmux sessions are getting killed from time to time a la https://bugzilla.redhat.com/show_bug.cgi?id=1933494 .  I'm happy to help implement or just test anything.

I wanted to open this issue to continue the momentum from #3024.

**Comment by mdengler** [comment]
I see the code in https://gitlab.gnome.org/GNOME/vte/-/blob/master/src/systemd.cc but not sure how to implement that, or if that's the right thing anyway, given @benzea mentioned "without dbus"...

**Comment by nicm** [comment]
You can do pretty much whatever you like if you add a compat/forkpty-systemd.c or add appropriate minimal calls into functions in compat/systemd.c. tmux has a configure flag to link against systemd, but I don't want to link against dbus.

You can't copy VTE code because it is C++ and LGPL.

**Comment by benzea** [comment]
Hm, don't remember what I was referring to with "without dbus". What comes to mind right now is:
 * Launching using systemd-run (which can also allocate a pty)
 * Using cgroup delegation and managing it yourself (requires being a systemd service in the first place though)

But, we are linking against systemd. So using dbus through the systemd API is trivial.

**Comment by nicm** [comment]
Using dbus through systemd API is grand, I don't really want to add an explicit dependency on libdbus as well, but even then I don't mind too much so long as its still under `--enable-systemd`.

**Comment by nicm** [comment]
Running `systemd-run` with fork/exec or system is gross and not OK though :-).

**Comment by mdengler** [comment]
Understood about `systemd-run` via fork/exec; FWIW now I have something like this is my `.tmux.conf`:

```
...
new-window -d         -n mutt      "exec systemd-run --user  --pty --scope  mutt"
new-window -d         -n emacs     "exec systemd-run --user  --pty --scope  emacs -nw"
new-window -d         -n lab       "exec systemd-run --user  --pty --unit=jupyter-user --slice=jupyter.slice poetry run jupyter lab"
new-window -d         -n gc        "exec systemd-run --user  --pty --unit=chrome-user --slice=chrome.slice google-chrome"
```

**Comment by nicm** [comment]
I'm going to close this now but if you questions do ask or if you have anything to show please feel free to open a PR.
