### ISSUE TITLE
tmux not working anymore, showing [exited] 0;95;0c>

### ISSUE THREAD

**Issue by oscarcalderonc** [tmux/tmux#3185]
### Issue description

Suddenly tmux doesn't work anymore on my computer. I even uninstalled and installed again using brew but the issue persists. When I run the tmux command i get this output:

```
➜  ~ tmux
[exited]
➜  ~ 0;95;0c>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15hi>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15
zsh: command not found: 0
zsh: command not found: 95
zsh: command not found: 0c
➜  ~ tmux
[exited]
➜  ~ 0;95;0c>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15hi>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15
zsh: command not found: 0
zsh: command not found: 95
zsh: command not found: 0c
➜  ~ tmux
[exited]
➜  ~ 0;95;0c>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15hi>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15>|iTerm2 3.4.15
```

Initially it just showed 
```
[exited]
➜  ~ 0;95;0c>|iTerm2 3.4.15>
```
but the more times I press enter after that, and run `tmux` again, the length of that "output" increases. It seems like running `tmux` fails and throws that output `0;95;0c>` or something like that

### Required information

Please provide the following information:

* tmux version: tmux 3.2a.
* Platform: Darwin arm.
* $TERM inside and outside of tmux: xterm-256color outside, not able to run it inside as it doesn't start.
* Logs from tmux:

```
➜  ~ tmux kill-server; tmux -vv new
server exited unexpectedly
```

**Comment by krader1961** [comment]
The unexpected text being fed to your shell is the result of the "device attributes" CSI sequence that tmux sends to the terminal and tmux exiting before it can process the response from the terminal. Which causes your shell to attempt to process the response. See issue #3135.

**Comment by nicm** [comment]
This is probably a configuration error. Show tmux server log please.
