### ISSUE TITLE
new-window -c resolves symlinks

### ISSUE THREAD

**Issue by dlukes** [tmux/tmux#3186]
### Issue description

With the following directory layout...

```sh
mkdir foo
ln -s foo bar
```

... if I run the tmux commnad `new-window -c bar`, I end up in `foo` anyway (the symlink gets resolved). Same with `split-window`.

Is this intentional? Or can it be avoided? I'd like to keep the symlinked path if at all possible.

I know tmux can't keep track of the symlinked path on its own (https://github.com/tmux/tmux/issues/1282), but I thought if I provided it explicitly, it would honor it?

### Required information

* tmux version (`tmux -V`): tmux next-3.4 (built from 3b7dae9a5339c4495d30a4c1bb28ffe8aead0b27)
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): tmux-256color, xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`): [tmux-client-1479804.log](https://github.com/tmux/tmux/files/8688171/tmux-client-1479804.log), [tmux-out-1479806.log](https://github.com/tmux/tmux/files/8688173/tmux-out-1479806.log), [tmux-server-1479806.log](https://github.com/tmux/tmux/files/8688174/tmux-server-1479806.log)

**Comment by nicm** [comment]
The kernel only stores the resolved path. We used to set `PWD` as well so the shell would have the original path, but that doesn't seem to be there anymore. I'll have to figure out if it was removed by mistake or if there was a reason.

**Comment by dlukes** [comment]
Thanks for looking into this!

> The kernel only stores the resolved path.

I was a bit confused by this at first -- what does it matter what the kernel stores, if I provide the path manually? -- but then I realized tmux probably does something akin to this...

```python
import os
os.chdir("bar")
os.execl("/bin/bash", "/bin/bash")
```

... and that also lands me in `foo`, even though I asked for `bar`. Because how else would I inform an arbitrary process about the current working directory, other than having inherit it via what the kernel says it is. Thanks for making that clearer in my mind.

**Comment by nicm** [comment]
I think the `PWD` change was lost in the merge of the `spawn.c` change, so I think we can add it back, please try this: [x.diff.txt](https://github.com/tmux/tmux/files/8693732/x.diff.txt)

**Comment by dlukes** [comment]
Thank you for the quick response! The patch fixes the issue, but only partially -- as long as I provide an absolute path. So `new-window -c /absolute/path/to/bar` lands me in `bar`, but `new-window -c relative/path/to/bar` still lands me in `foo`. Is that expected?

**Comment by danjenson** [comment]
I'm also seeing problems with -c not being respected at all in tmux3.2a

**Comment by dlukes** [comment]
@danjenson Having read through https://github.com/nushell/nushell/issues/5050, that seems to be an issue with nushell failing to communicate the working directory in a standard way. Not only tmux is affected, but Tilix and other terminal emulators too. And conversely, other shells work perfectly fine in all of these.

So I don't think it's a tmux issue, or related to what we're discussing here.

> but `new-window -c relative/path/to/bar` still lands me in `foo`. Is that expected?

I guess for that to work, tmux would first have to read `PWD` from the shell's environment and set the path relative to that?

**Comment by nicm** [comment]
Try this to do relative paths please: [y.diff.txt](https://github.com/tmux/tmux/files/8707976/y.diff.txt)

**Comment by dlukes** [comment]
That works like a charm, thank you very much!

**Comment by nicm** [comment]
Applied now, thanks!

**Comment by nicm** [comment]
Yes exactly. Some shells will look for PWD if tmux sets it but for some
reason it doesn't do that anymore and I am not sure why.
