### ISSUE TITLE
Is it possible to support interactive command in run-shell?

### ISSUE THREAD

**Issue by kohnish** [tmux/tmux#3187]
Something like `tmux run-shell top` seems to fail by design because top fails to get tty.

I have something like this to use vim as pager for scroll back, but it'd be nice to do it in the same pane like kitty terminal does. 
```
bind-key [ run-shell 'tmux capture-pane -S - && tmux new-window "tmux show-buffer | vim -R -n -"'
```

**Comment by krader1961** [comment]
As you seem to realize `run-shell` isn't meant to run arbitrary commands in the current pane. If I've understood your question you want `send-keys`:

```
bind-key [ send-keys 'tmux capture-pane -S - -p | vim -R -n -' C-m
```

**Comment by kohnish** [comment]
I don't think that'll work over ssh and etc. Also run-shell is meant to run arbitrary  command that can work without tty. My question is if it's feasible to support it like kitty does, as I'm not aware of the architecture of tmux.

**Comment by krader1961** [comment]
Did you try it? Since your injecting that command pipeline into the pane as if you had manually typed it it is irrelevant whether you've connecting to the tmux session via ssh. The `run-shell` command is not meant to be able to run arbitrary commands. As you noticed, it can't be used to run commands that require a tty. That's intentional. Also, it's not at all obvious what you mean by "like kitty terminal does."

**Comment by nicm** [comment]
No, this is not what `run-shell` is for. Use a popup, or a new pane.

**Comment by kohnish** [comment]
By `A new pane`, I guess you mean `new-window` like the original example I posted.  
  
With popup, you could do something like this. Visually perfect but no tmux commands and hooks work there. Also all tmux action gets blcoked. It'd be nice if there was an option to allow these or run-shell option that mimics the feature.
```
bind-key [ run-shell "tmux capture-pane -S - && tmux display-popup -BE -h `tmux display -p '#{pane_height}'` -w `tmux display -p '#{pane_width}'` -x `tmux display -p '#{pane_left}'` -y $((`tmux display -p '#{pane_bottom}'` + 1)) 'tmux show-buffer | vim + -R -n -'"
```

**Comment by nicm** [comment]
I mean a new pane, but you can use a new window if you like.

Or it is trivial to create a new window and swap the pane there temporarily and back when you are done, I don't think we need any additional support for this.

**Comment by kohnish** [comment]
Neither split or swapping isn't ideal, as it changes existing layout, if I understood you correctly.  

I found a workaround to make popup work for some tmux commands. You'd lose popup, but at least specified tmux commands work.


Save this as `tmux-vim-pager` and set executable bit on and put it in the PATH.  

```
#!/bin/sh
if [[ $1 == "strip" ]]; then
    exec cat | sed -e :a -e '/./,$!d;/^\n*$/{$d;N;};/\n$/ba'
else
    reset_cmd='tmux bind c new-window &&
        tmux bind n next-window &&
        tmux bind Left select-pane -L &&
        tmux bind Up select-pane -U &&
        tmux bind Down select-pane -D &&
        tmux bind Right select-pane -R
        '
    tmux capture-pane -S -
    exec tmux display-popup -BE \
        -h `tmux display -p '#{pane_height}'` \
        -w `tmux display -p '#{pane_width}'` \
        -x `tmux display -p '#{pane_left}'` \
        -y $((`tmux display -p '#{pane_bottom}'` + 1)) \
        "tmux new-session -s popup \"
            tmux set-option status off &&
            tmux bind c run-shell 'tmux kill-session -t popup && tmux new-window -t ${session_name} && ${reset_cmd}' &&
            tmux bind n run-shell 'tmux kill-session -t popup && tmux next-window -t ${session_name} && ${reset_cmd}' &&
            tmux bind Left run-shell 'tmux kill-session -t popup && tmux select-pane -L -t ${session_name} && ${reset_cmd}' &&
            tmux bind Right run-shell 'tmux kill-session -t popup && tmux select-pane -R -t ${session_name} && ${reset_cmd}' &&
            tmux bind Down run-shell 'tmux kill-session -t popup && tmux select-pane -D -t ${session_name} && ${reset_cmd}' &&
            tmux bind Up run-shell 'tmux kill-session -t popup && tmux select-pane -U -t ${session_name} && ${reset_cmd}' &&
            tmux show-buffer | $0 strip | vim + -R -n -\""
fi
```

In add this to .tmux.conf.
```
bind [ run-shell 'tmux-vim-pager'
```
