### ISSUE TITLE
iterm2+tmux do not load /etc/profile

### ISSUE THREAD

**Issue by MF-ReStart** [tmux/tmux#3188]
I am logging into a terminal using tmux and the environment variables in /etc/profile are not loaded into my terminal, the environment variables in ~/.bashrc are successfully loaded into my terminal, do I have to run source /etc/profile every time I log into a terminal?

### Necessary information
I'm using iterm2 and the tmux integrated environment
* tmux 3.0a
* Linux x86_64 Centos7
* screen

**Comment by nicm** [comment]
did you change tmux not to start login shells?

**Comment by MF-ReStart** [comment]
I use the command to log in in iterm2: ssh -p '22' 'root@xx.xx.xx.xx' -t 'tmux -CC new -A -s main bash'

**Comment by nicm** [comment]
what's in your .tmux.conf?

**Comment by MF-ReStart** [comment]
There is no tmux.conf configuration file created on my local or remote server

**Comment by nicm** [comment]
You are running "bash" directly which will not be a login shell, just don't
specify "bash" and tmux will run a login shell.

**Comment by MF-ReStart** [comment]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/50358485/168538223-f1b02d1f-c7a3-4d61-8873-6e436524c201.png">
java environment variables written in /etc/profile will not work when tmux logs into the terminal, but writing them in .bashrc will work

**Comment by MF-ReStart** [comment]
Wow, my friend, problem solved! I love you 😘
