### ISSUE TITLE
Cursor disappears intermittently in Vim until dimensions are resized

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#319]
Sorry if this is a bit vague; I'll describe what I am seeing and if there is any specific info I can provide to make this reproducible, please let me know.

**The problem:** when in normal mode in Vim (ie. block cursor applies), cursor disappears and reappears intermittently. For example, I might see the cursor, hit `b` a couple of times, and the cursor will suddenly disappear (until I enter insert mode; then it switches to a line-cursor and reappears, and when I hit Escape, I am back in normal mode again with the block cursor visible). If I jump around in normal mode the cursor may or may not come back, briefly.

**Workaround:** change window size; the cursor is now redrawn and will stay redrawn, for a while, until the problem appears again.

**Set-up:** tmux `HEAD` of `master` installed via Homebrew on OS X 10.11.3. Vim 7.4 (patches 1-1147). Running inside iTerm 2 v3 (Build 2.9.20160229-nightly).

**Comment by nicm** [comment]
Does this also happen in Terminal.app?

**Comment by wincent** [comment]
I haven't seen it in Terminal.app, but I spend hours a day in iTerm and I've only just been trying Terminal.app for a few minutes now. I'll keep using it this morning and see if I can repro.

Also I haven't seen it outside of tmux, so perhaps it only manifests under tmux+ iTerm. But again, hard to say as I am almost always inside tmux.

**Comment by wincent** [comment]
I still haven't been able to repro it in Terminal.app yet. I added some comments to [a potentially related issue](https://gitlab.com/gnachman/iterm2/issues/3875) on the iTerm issue tracker, but I am still unsure of whether it's iTerm or tmux that is at fault here.

I with I could find a consistent repro, but at least for now, it appears that it only happens on tmux `HEAD` and not on another older machine where I have tmux 2.1 installed. If I could just get a consistent trigger for it I'd be able to bisect...

**Comment by nicm** [comment]
If you can't reproduce in Terminal.app or xterm it is a sign it is probably an iTerm issue.

**Comment by nicm** [comment]
Are you sure the cursor shape stuff is correct for iTerm in your terminal-overrides?

**Comment by wincent** [comment]
> If you can't reproduce in Terminal.app or xterm it is a sign it is probably an iTerm issue.

I agree that's possible. I've made some progress gathering data [on the iTerm front](https://gitlab.com/gnachman/iterm2/issues/3875). It that investigation proves fruitful I'll loop back here and let you know.

> Are you sure the cursor shape stuff is correct for iTerm in your terminal-overrides?

Not actually using any `terminal-overrides`.

**Comment by nicm** [comment]
tmux won't change the cursor style unless Ss and Se are set so they are
either in terminal-overrides or in the terminfo entry (TERM) you have
set outside tmux.

**Comment by wincent** [comment]
Ok, well let's close this optimistically and assume that the problem lies with iTerm. I'll reopen this with more info if I get any evidence to the contrary. Thanks for your help!
