### ISSUE TITLE
Move tmux window to a new terminal instance?

### ISSUE THREAD

**Issue by Barbaross93** [tmux/tmux#3190]
### Issue description
Just a question: Is it possible to transfer a tmux window to a new terminal instance? I'm aware of `movew` but it seems to only transfer windows between tmux sessions and not to entirely new terminal windows.

tmux version:`tmux 3.2a`

**Comment by cevhyruz** [comment]
@Barbaross93 try this one https://github.com/nelhage/reptyr/issues?q=is%3Aissue+author%3Acevhyruz

**Comment by cevhyruz** [comment]
@Barbaross93 try this https://github.com/nelhage/reptyr

**Comment by Barbaross93** [comment]
Thanks @cevhyruz , I was using `reptyr` as well but decided I wasn't a big fan of opening a potential security risk (enabling `ptrace` by disabling `ptrace_scope`)

**Comment by nicm** [comment]
You can attach an existing tmux session in another terminal window very easily, or create a new session in the new terminal and move or link your windows into it.

**Comment by Barbaross93** [comment]
@nicm , right I'm aware of that. It sounds like tmux is unable to do the thing I'm asking; it's not a big deal because it is as you said, it's easy to just start a new tmux session and transfer the window.
