### ISSUE TITLE
tmux should pass through OSC 52 selection parameters

### ISSUE THREAD

**Issue by duncf** [tmux/tmux#3192]
### Issue description

When running with the `set-clipboard` option enabled, tmux will intercept and decode OSC 52 commands. When it sees an OSC 52 command, tmux will copy the selection data to a buffer and then send new OSC 52 commands to set the user's clipboard. The net effect is that programs running inside tmux (e.g. editors), paired with an appropriate terminal emulator, can set the clipboard in the user's desktop environment.

The format of OSC 52 commands includes two fields; the first to select which buffers are to updated, and the second contains base64-encoded data. The [XTerm control sequence spec](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) says:

``` 
          The first [field] may contain zero or more characters from the
          set c , p , q , s , 0 , 1 , 2 , 3 , 4 , 5 , 6 , and 7 .  It is
          used to construct a list of selection parameters for
          clipboard, primary, secondary, select, or cut-buffers 0
          through 7 respectively, in the order given.  If the parameter
          is empty, xterm uses s 0 , to specify the configurable
          primary/clipboard selection and cut-buffer 0.
```

While OS X and Windows systems only support the "clipboard" buffer, X keeps three separate selection buffers:
 - the "clipboard" buffer, usually manipulated with Ctrl-C / Ctrl-V,
 - the "primary" buffer, typically used by highlighting text and middle-clicking to paste, and
 - the "secondary" buffer, which is rarely used.

The distinction between these buffers is useful on platforms that support them.

Currently tmux handles OSC 52 codes by parsing the data from the command, and throwing away the selection parameters. When generating new OSC 52 codes, tmux sets the selection parameter [to the empty string](https://github.com/tmux/tmux/blob/cf7e1c94dfa472f698cc5902d901ef1cef938f64/tty.c#L2104).

Instead, tmux should keep the selection parameters and pass them through for the generated OSC 52 commands. This will allow editors running inside tmux to set both the clipboard buffer and the primary buffer in supported environments.

### Repro steps

Inside tmux, using a terminal emulator with OSC 52 support (e.g. xterm, Kitty, etc), run:
```
$ printf "\033]52;c;$(printf "%s" "clipboard" | base64)\a"
$ printf "\033]52;p;$(printf "%s" "primary" | base64)\a"
```

Outside tmux, use `xsel -p` to see the contents of the primary buffer and `xsel -b` to see the contents of the clipboard. With Kitty (`TERM=xterm-kitty`), the current behavior is for both commands to update the clipboard.

Without tmux, the commands have the desired behavior.

**Comment by nicm** [comment]
I don't know that it is a good idea to pass them through because we don't know what the terminal outside supports. You can control which buffers tmux sets by modifying the `Ms` capability, but possibly we should make that easier to configure.

**Comment by nicm** [comment]
I don't know if it is worth doing anything here. What editors do this and how do they use it - do you have examples?

X's multiple selections is often seen as a misfeature and I can think of few applications aside from xterm which allow you to configure the target. I can't see many people wanting to change the default, and if they do they can either configure xterm (`selectToClipboard`?) or change `Ms` with `terminal-overrides`.

**Comment by duncf** [comment]
Thanks for looking into this!

I'm not looking to change or configure which selection buffer is used -- I'd like to use both, independently.

My goal is to get emacs, running in tmux over ssh, to update my local clipboard and primary selections (independently) just as if I was using it locally with a gui. There's already code in emacs to send the appropriate OSC 52 escapes to xterm to set the PRIMARY or CLIPBOARD selections (e.g `(gui-set-selection 'PRIMARY "primary text")`), but this doesn't work when emacs is running inside tmux, because tmux throws away the selection parameters.

I don't particularly care to use `set-clipboard` mode in tmux, but that's currently the only way to get tmux to pass through OSC 52 commands at all. If it's too complicated to support passing through OSC 52 commands and interpreting them for `set-clipboard` mode, would it be possible to just pass them through when `set-clipboard` is disabled? (Or possibly this could be a new `set-clipboard` mode?)

**Comment by nicm** [comment]
Passing them through when `set-clipboard` is disabled is no good, OSC 52 is enough of a potential security issue as it is.

Maybe we can just forward the first parameter but filter it for validity.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/8830837/x.diff.txt)

**Comment by duncf** [comment]
Thank you very much for the quick fix. I was able to test out the change and it worked as expected.
