### ISSUE TITLE
Tmux in control mode is irresponsive when there is a syntax error in config

### ISSUE THREAD

**Issue by JasonXJ** [tmux/tmux#3193]
### Issue description

When there is a syntax error in config, _tmux in control mode does not report an error. And when I run a `send-keys` command, it never produces a `%output` notification._ I am not sure if iterm2 has a different and better way to handle this, but in the app I am building, this means that the user does not see an error and does not see echo when they types.

To repro:

* Add a line with just `set` to `~/.tmux.conf` so that there is an syntax error
* run `tmux -C` (you might need to kill the server or run a new server)
* type `send-keys hello`

This is tmux's output:

```
lxj@lxj $ ./tmux -C -S /tmp/test_tmux
%begin 1653284531 259 0
%end 1653284531 259 0
%window-add @0
%sessions-changed
%session-changed $0 0
%pane-mode-changed %0
%window-renamed @0 [tmux]
%output %0 lxj@lxj:~$
send-keys hello
%begin 1653284536 267 1
%end 1653284536 267 1
```

If there is no syntax error in the config, the output should be the same except that at the bottom there should be a line `%output %0 hello`.

I think maybe tmux should report an error with `%error` at the beginning, just like `tmux -C attach` when there isn't a session to attach?

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 3.1c, 3.2a, ToT

**Comment by nicm** [comment]
The reason you are getting no output for `send-keys` is because the initial pane is in copy mode to show the errors, if you issue `copy-mode -q` it will work again.

Try this please which adds a client flag `no-show-errors` which will instead show them as `%config-error` rather than entering copy mode: [x.diff.txt](https://github.com/tmux/tmux/files/8796869/x.diff.txt)

**Comment by JasonXJ** [comment]
Hi, sorry for the late response. I applied the patch and it worked. But it seems that this requires the user to specify this flag in the command line (e.g. `tmux -CC new -f no-show-errors`), which is not great. Can we do something smarter here by turnings this on by default for control mode clients?

It seems that another thing that I can do is to monitor whether a pane is in copy mode, and get it out of it automatically when the user starts to interact with it. This will also make sure that we work fine when the user enters copy mode in a normal client. We will still need the change here so that we can warn the user about config error though.

P.S. I tried iterm2 and it suffered from the same issue.

**Comment by nicm** [comment]
No we cannot have this by default unless we confirm it is not going to break old iTerm2 versions. @gnachman?

**Comment by JasonXJ** [comment]
Sure, but I tested it and it is already broken in item2 (i.e. the user cannot interact with it when this happens). I suspect that this will be fine for iterm2 since an unknown notification (i.e. `%config-error`) will just be ignored?

**Comment by nicm** [comment]
I don't know how iTerm2 works or how it is intended to work here, you will need to talk to George.

**Comment by JasonXJ** [comment]
no worries. Let's wait for his response.

**Comment by nicm** [comment]
In the meantime you can probably set this flag by default for clients with `-C` fairly easily, I expect it will be OK I would just like to confirm.

**Comment by JasonXJ** [comment]
> In the meantime you can probably set this flag by default for clients with -C fairly easily, I expect it will be OK I would just like to confirm.

I not sure how this would work without the user setting the flag in the command line by themselves. If the user just run command `tmux -CC ...` without setting the flag, we will just enter the tmux control mode without the `%config-error` notification. The integration can send tmux a `attach-session -f no-show-errors` command to change the flag, but this will already be too late! The tmux server is already running and the config has been read at this point. It will not emit a `%config-error` again.

**Comment by nicm** [comment]
No, I mean you can patch your copy locally to set it.

**Comment by gnachman** [comment]
Sorry for the delay. Yes, `-f no-show-errors` is a good default for iTerm2. Currently it appears to be hung when there's an error in tmux.conf.

**Comment by nicm** [comment]
OK great, I have changed this to remove the flag and just to do this by default in control mode. Thanks!
