### ISSUE TITLE
all *.tmux files return 1 and do not run

### ISSUE THREAD

**Issue by pgosar** [tmux/tmux#3195]
Despite reinstalling multiple times, any *.tmux file when ran from .tmux.conf does not work, and returns 1.  This includes every plugin and even a simple file meant to display hello world. The issue persists even when the config file contains nothing but a command to run a .tmux file (run-shell test.tmux). There is no other config file besides my .tmux.conf.

Nothing I have seen about similar issues has been helpful. I have also tried installing from source (3.2a) and from the latest release as detailed in the readme. The same exact issue persists.

Running WSL2 Ubuntu 20.04 with TMUX 3.0a, $TERM is screen-256color
logs are attached but the TMUX server log file is over 2 million lines long and too big to be uploaded but its probably not helpful.

[tmux-client-90637.log](https://github.com/tmux/tmux/files/8776446/tmux-client-90637.log)
[tmux-out-90639.log](https://github.com/tmux/tmux/files/8776448/tmux-out-90639.log)

What really confuses me is miraculously everything worked perfectly with this exact configuration for a while a couple days ago after being broken, but it broke again after I exited TMUX and has not worked since. I did not update anything at all.

**Comment by nicm** [comment]
Show server log please.

**Comment by nicm** [comment]
There is no way a server log from simply starting tmux and then exiting it should be that big, especially if you gzip it.

**Comment by pgosar** [comment]
Alright, The error is recreated, I also got rid of all but one tmux plugin (I am not running it through tpm). 

This time the server log file was not dozens of megabytes, thankfully (it was even with only running a single tmux file last time).

[tmux-client-77730.log](https://github.com/tmux/tmux/files/8815961/tmux-client-77730.log)

[tmux-server-77732.log](https://github.com/tmux/tmux/files/8815959/tmux-server-77732.log)

**Comment by pgosar** [comment]
The systemd error was because I messed something up in my system in the weekend, the returning one issue happens without it

**Comment by nicm** [comment]
I think you'll need to instrument your scripts to work out why they are exiting with failure, or ask whoever wrote them.

**Comment by pgosar** [comment]
I thought the scripts were causing the issue originally as well, so I tried running a simple display message inside a tmux file as well, which did not run either. 

I think if this issue is not easily fixed or seems like an isolated incident it is fine since I was able to recreate most of the features I wanted just in my tmux.conf file.

**Comment by pgosar** [comment]
[logs.zip](https://github.com/tmux/tmux/files/8816152/logs.zip)

**Comment by nicm** [comment]
You are running this file with `run-shell` but it is not a shell script, either make it a shell script (`tmux display ...`) or use `source-file`.

**Comment by nicm** [comment]
That one (sidebar.tmux) is a shell script.

**Comment by pgosar** [comment]
That one returns 1 if I run it with run-shell like in the log files I uploaded though. Is there a way around that then?

**Comment by nicm** [comment]
You will need to figure out why the script fails, I can't tell you, it doesn't output any errors I can see.

Does it work if you run it manually?

**Comment by nicm** [comment]
Are you sure it is executable?

**Comment by pgosar** [comment]
It does not output an error, but it also does not actually do anything. It is executable. Since this is not a tmux issue, I can contact the individual plugin writers and see if there is something I can do.
