### ISSUE TITLE
New release plans?

### ISSUE THREAD

**Issue by rfrancoise** [tmux/tmux#3198]
Hi Nicholas,

We're coming up on 1 year since tmux 3.2a. 3.3 had a release candidate, but no official release.

Any plans for a new release? I was hoping that you would sync with OpenBSD 7.1 but it looks like it's not the case.

Thanks.

[This was prompted by this [Ubuntu bug report](https://bugs.launchpad.net/ubuntu/+source/tmux/+bug/1976110/)--an issue in 3.2a already fixed on master.]

**Comment by nicm** [comment]
I will do one soon...
