### ISSUE TITLE
Tmux windows with multiple panes cannot be re-attached by iTerm2

### ISSUE THREAD

**Issue by irdc** [tmux/tmux#3199]
I'm using tmux on OpenBSD 7.1 to run my text editor and compiler in a multi-pane window, to which I attach using iTerm2 on macOS using tmux control mode (`tmux -CC`). This works great while setting it up; however, when the SSH connection to my OpenBSD machine inevitably goes down and I reconnect, iTerm refuses to re-attach the multi-pane window. Windows with a single pane do get attached. If I attach a regular tmux client and close all but one of the panes on the window, iTerm does properly re-attach the window.

If I then reproduce the exact same scenario using tmux 3.2a on my Linux machine, attaching to it using the very same iTerm2 version (on the same Mac), it all works as expected and I get my multi-pane window back after a reconnect.

I'll attach the log sets in separate messages for clarity.

## Version affected
* tmux version (`tmux -V`): tmux openbsd-7.1
* Platform (`uname -sp`): OpenBSD aarch64
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color

## Version that's working
* tmux version (`tmux -V`): tmux 3.2a
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color

## `tmux.conf` (identical on both systems)
```
# use ^W as the prefix key
set -g prefix C-w
unbind C-b
bind C-w send-prefix

# easy reloading of config file
unbind r
bind r source-file ~/.tmux.conf \; display "User config reloaded!"
unbind R
bind R source-file /etc/tmux.conf \; display "System config reloaded!"

# window splitting
bind | split-window -h
bind - split-window -v

# pass through things useful for working on a desktop
set -g update-environment 'DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY DBUS_SESSION_BUS_ADDRESS'

# set titles
set -g set-titles off
set -g set-titles-string '#T (#P)'
set -g automatic-rename on
set -g automatic-rename-format "#{?#{==:#{pane_current_command},#{b:default-shell}},#T,#{USER}@#h - #{pane_current_command}}"

# anything less is silly nowadays
set -g default-terminal "xterm-256color"

set -wg window-size smallest
```

## iTerm
* iTerm version: 3.4.15
* iTerm platform: macOS 12.3.1

**Comment by irdc** [comment]
[Logs for the affected version](https://github.com/tmux/tmux/files/8792980/tmux-openbsd71.tar.gz)

**Comment by irdc** [comment]
[Logs for the version that's working](https://github.com/tmux/tmux/files/8792985/tmux-32a.tar.gz)

**Comment by irdc** [comment]
I've just managed to reproduce the issue with the current git version (cf7e1c94dfa472f698cc5902d901ef1cef938f64).

**Comment by nicm** [comment]
@gnachman any idea what this could be?

**Comment by watters** [comment]
Having the same/similar issue with iTerm2 connecting to a local tmux session on macOS, and, looking at the iTerm2 debug logs, it looks like iTerm2 may have been counting on the behavior of `show-options` before 7bd9cdf6f

iTerm2 invokes `show-options -v -p -t %%%d @uservars` [when attempting to open windows for the tmux session](https://gitlab.com/gnachman/iterm2/-/blob/master/sources/TmuxWindowOpener.m#L220), which, I believe, used to behave as if `-q` was passed, even when `-q` was omitted.

**Comment by gnachman** [comment]
Sorry for the delay in getting to this. I'm going to release an emergency 3.4.16 to fix this. Since it won't get any beta test coverage please give it a try and let me know if you see any issues, especially with tmux:

https://iterm2.com/adhocbuilds/iTerm2-0_20220624_160730-adhoc.zip

**Comment by gnachman** [comment]
@watters 3.4.16 was just released with the fix
