### ISSUE TITLE
Text selection with mouse stops when mouse goes off terminal window

### ISSUE THREAD

**Issue by ctrlrsf** [tmux/tmux#32]
If you start selecting text with mouse from bottom of buffer, if the mouse goes off the terminal window, tmux stops updating mouse selection and highlights from starting point up to the half of the screen. If you start selection from top of terminal/buffer going down and mouse goes off terminal window, tmux highlights starting point and up to half of the screen. When mouse re-enters window, tmux doesn't continue updating the end of the selection point.

Expected behavior is that if selecting text with mouse, if mouse goes off terminal window selection end point will stop updating, but when mouse re-enters window, it picks back up and continues highlighting up to wherever mouse has moved to.

This was tested on OS X (iTerm) with tmux -HEAD from homebrew.

**Comment by ctrlrsf** [comment]
After further testing today, I noticed this only occurs when mouse goes off the window on the left side. When mouse is off window on the right side and re-enters, the tmux continues updating highlighted/selected text as normal.

Below is screenshot of half-screen highlighted when cursor goes off screen:
![image](https://cloud.githubusercontent.com/assets/6004738/8370518/ad9b817e-1b96-11e5-9ada-0363274bf27a.png)

**Comment by nicm** [comment]
It works ok for me with xterm. Did you try xterm?

**Comment by ctrlrsf** [comment]
Sorry for late response but confirmed it does not happen in xterm under XQuartz. It also didn't happen with an older version of tmux in iTerm. Nevertheless, not a big deal anymore.
