### ISSUE TITLE
tmux does not execute particular line

### ISSUE THREAD

**Issue by shantanoo-desai** [tmux/tmux#320]
I am using `tmux` on __Raspberry Pi 2 Model B__ with __Debian Wheezy__

I installed it using `apt-get install tmux`

I have written a bash script which is called in `/etc/rc.local` which establishes a session to use mesh networking daemons: __ALFRED__ and __BATADV-VIS__

the Script looks as follows:

    # !/bin/sh
    tmux new-session -d -s piSession
    tmux new-window -d -n 'alfredHere' -t piSession:1 'alfred --interface wlan0' 
    # the line above doesn't get executed when called from /etc/rc.local
    tmux new-window -d -n 'batvisHere' -t piSession:2 'batadv-vis -s'

when executed from `/etc/rc.local` and doing `txmux ls`

the output shows __2 Windows__ when I expect 3 Windows:

1. 1x for ALFRED running the cmd: `alfred --interface wlan0`
2. 1x for BATADV-VIS running the cmd: `batadv-vis -s`
3. 1x common terminal

upon `txmux attach` I only see points __3 and 2__ somehow the `alfredHere` window is completely skipped

#### Observation

when I kill the session using `txmux kill-session`

and run the script `bash /path/myScript.sh` everything works well with __3 windows__ and the daemons work perfectly.

WHY?? what kind of read+write permission needs to be given to the path in order to execute using `/etc/rc.local`

This has also been posted on [RaspberryPi StackExchange](http://raspberrypi.stackexchange.com/questions/43375/tmux-not-executing-particular-line?noredirect=1#comment63320_43375)

Help would be really appreciated.

Thanks

**Comment by nicm** [comment]
Add ";sleep 2000" to the failing command and then attach to tmux and it
will show if it is exiting with an error.

**Comment by shantanoo-desai** [comment]
Hi @nicm how will sleep help me here since the Raspberry Pi will be in `sleep` I will not be able to get access to the terminal when I boot it using `/etc/rc.local`

**Comment by nicm** [comment]
This command is probably failing so tmux closes the window immediately:

tmux new-window -d -n 'alfredHere' -t piSession:1 'alfred --interface wlan0'

Change it to:

tmux new-window -d -n 'alfredHere' -t piSession:1 'alfred --interface wlan0; sleep 1000'

Then after boot attach to tmux and see if the window is open with an error message that will tell you why it exited.

**Comment by shantanoo-desai** [comment]
Hi @nicm ,

As you suggested I did it with:
   
    tmux new-window -d -n 'alfredHere' -t piSession:1 'alfred --interface wlan0; sleep 1000'

On 
__alfredHere__ : I get `sh:1 : alfred not found` and after the `sleep 1000` gets finished I get `Pane is dead`

__batvisHere__ : I get `Pane is dead`

Somehow I am running in bit of a circle.

**Comment by nicm** [comment]
"alfred" is not in the PATH when tmux is started from rc.local, use the full path like /usr/bin/alfred. (use "which alfred" to find it).

**Comment by shantanoo-desai** [comment]
So I found out that the path is `/usr/local/sbin/alfred` and `/usr/local/sbin/batadv-vis`

I used full paths but now it shows `Failed to open Interfaces` on __alfredHere__

**Comment by nicm** [comment]
I cannot help you debug a program I have never used and have no idea how it works, I suggest you look at its manual. Are you sure the wlan0 interface exists when rc.local is run?

Why do you need tmux? Can't these programs run in the background?

**Comment by shantanoo-desai** [comment]
Hi @nicm  I understand, I will look into these matters. The thing is both these are user specific daemons and are dependent on each other. For instance
    
    alfred -i wlan0
will start the daemon on `wlan0` using __UNIX sockets__ to gather local information like the topology of mesh network in the surrounding. 

    batadv-vis -s 
will start a  server on an interface called `bat0` which polls the mesh network using the __UNIX sockets__ that are already running on the `alfred`. In the end I get a the topology of the network in DOT or JSON when I ask for it.

Now these daemons keep running infinitely and when I want them to run on RPI as a standalone system I would like them to work in a tmux session which keeps on doing the polling and the end user can attach to the session to know who is in the network.

**Comment by shantanoo-desai** [comment]
Hi @nicm Thanks anyways. This issue needs to be closed have found out that both are `start-stop-daemon` types.

so commands like
   
    start-stop-daemon -b --exec --start /usr/local/sbin/alfred -- -i wlan0
    start-stop-daemon -b --exec --start /usr/local/sbin/batadv-vis -- -s

will work. But sadly I cannot make them run on bootup so this issue will not concern itself with `tmux`

Thanks for the help though.
