### ISSUE TITLE
Allow mouse scrolling without interfering with selecting

### ISSUE THREAD

**Issue by lvandeve** [tmux/tmux#3200]
### Issue description

Tmux gives you two choices:

-no mouse scroll support, but selection and copypaste works natively in your local VTE

-mouse scroll support, but selection and copypaste don't work natively in your local VTE and you have to hold shift while selecting instead

The second option is enabled with `set -g mouse on` in the tmux config. The first requires no config.

The issue is that this prevents the following combination:

-mouse scroll support, but selection and copypaste works natively in your local VTE (no holding shift needed)

So having a setting to individually enable/disable mouse scrolling support, and enable/disable the selection behavior would be useful here. Would be very nice to have new settings for this!

Both are useful for different use cases, but the combination that is now prevented is very close to how your VTE works locally, so that terminals behave less differently in tmux and outside of tmux. Thanks!

### Required information

Please provide the following information:

* 3.2a
* Linux (Archlinux and Debian)
* both are: xterm-256color

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#i-want-to-use-the-mouse-to-select-panes-but-the-terminal-to-copy-how

**Comment by lvandeve** [comment]
I see, it's a technical limitation, with terminals only allowing either to pass through all mouse events, or none. Such a shame that this is the case!

I now really wish that instead there was a standardized way all terminals supported for a virtual scrollback history, so that the native mouse events and scrollbar of the terminal could request the scrollback history to the application...
