### ISSUE TITLE
Issues with buffer handling (set-buffer and delete-buffer)

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#3205]
I've split this from https://github.com/tmux/tmux/issues/3203 because it applies to master, and possibly goes back a while. 

Hey, I've had a problem with buffers. It appears that

delete-buffer -b name
will delete buffer "name" if it exists, otherwise it will delete another seemingly random buffer. (maybe the next in the list)

Is this correct behaviour?

Update: Looking at the source... cmd_set_buffer_exec()

      bufname = args_get(args, 'b');
      if (bufname == NULL)
          pb = NULL;
      else
          pb = paste_get_name(bufname);
The 'else' should probably check if "paste_get_name()" returns NULL and abort the buffer deletion..

Update2: This patch seems to do the right thing for the delete case,
```
    if (cmd_get_entry(self) == &cmd_delete_buffer_entry) {
+       if( pb == NULL && bufname != NULL )
+           return (CMD_RETURN_ERROR);
        if (pb == NULL)
            pb = paste_get_top(&bufname);
        if (pb == NULL) {
```
Though as mentioned by @krader1961,
```delete-buffer```
without parameters will incorrectly grab a named buffer, and delete it, and, as I've since found; 
```set-buffer -n newname```
will rename the most recent buffer, even if it isn't automatic, and finally
```set-buffer -b oldname -n newname```
when `oldname` does not exists, will rename the most recent buffer (even if its already a named buffer).

Thanks to @krader1961 for pointing out this issue is broader than first expected.

**Comment by systemmonkey42** [comment]
In addition to the above, can I ask for the following,  when selecting an automatic buffer, _always_ skip named buffers.

Eg, 
```
tmux show-buffer
```
Shows the most recent buffer, even if it is a named buffer.  It makes sense to me that named buffers should only be shown
when asked for by name

I'm sure thats how it used to work, but with 3.3/master there seems to be a strange interaction. Scripts (and hooks) I've used for ages no longer behave.

Thanks

**Comment by systemmonkey42** [comment]
Ok, This is fascinating...
It appears the commit which introduced the feature which deleted a recent buffer if the specified one wasn't found was

62bb6e37e0bdc2de2a20f7adc38993d2ccfd8c11

which is 7 years old.  somewhere between release 2.0 and 2.1...
Which means as far am I'm concerned, it *always* worked this way.

I've wasted too much time on this, so I'll likely just find another way to do what I need to do.

**Comment by krader1961** [comment]
> I've wasted too much time on this, so I'll likely just find another way to do what I need to do.

I appreciate your assessment but it still seems to me that the current behavior is incorrect; even if it has been in place for seven years. If nothing else the documentation needs to be updated to reflect the current behavior.

**Comment by systemmonkey42** [comment]
> If nothing else the documentation needs to be updated to reflect the current behavior.

I totally agree.  I would change everything about how named buffers are handled, but I figure since its been so long, either its expected behaviour and I'm doing it wrong... or _nobody_ uses named buffers, so the issues were never noticed.

**Comment by krader1961** [comment]
I have never used named buffers. I am willing to bet real money that there are few users of named buffers and they have never explored their behavior vis-a-vis `delete-buffer`. Otherwise these problems would have been noticed long ago. Nonetheless, either the current behavior, or the documentation, needs to be changed.

**Comment by nicm** [comment]
This should be fixed in OpenBSD now, will be in GitHub later, thanks!

**Comment by systemmonkey42** [comment]
Can we fix the problem with "automatic buffer" selection selecting named buffers?

Currently if I select text, and paste it, everything is fine, but if I set a named buffer between the selection and the pasting, it will paste the named buffer instead, which really makes named buffers difficult to use.

It also affected 'set-buffer -n' which will happily rename a named buffer if one isn't specified, and `delete-buffer` which will happily delete a named buffer if one isn't selected.

At least in the case of 'delete-buffer', the man page explicitly says it will select "the most recently automatically named buffer", the others ('set-buffer' and 'delete-buffer' make no mention of how the buffer is selected.)

I would prefer that this behaviour changed :-)

For context, I am saving formatted data in a named buffer for later use, which is not meaningful when pasted to the console.  Having named buffers get used when trying to paste from the last automatically named buffer really messes things up.

**Comment by systemmonkey42** [comment]
> Yes I am OK with that, best probably change `paste_get_top` to take a flag which if set causes it to ignore named buffers.

I tried a few alternatives.   The extra flag is clearly the way to go, even though there are only two places where it matters.  One really just wants to check the list is non-empty (and could be optimised PB_ROOT()..) and one is unclear (the `format_defaults_paste_buffer` use case), which I suspect should return an automatic buffer, and is ok to be NULL if there are only named buffers.

**Comment by nicm** [comment]
That is OK but I would add `paste_is_empty` or `paste_no_buffers` which just returns 0 or 1 instead of `paste_get_head`.

**Comment by nicm** [comment]
I am not sure about `format_defaults`, it would probably be OK if it only added default formats for automatic buffers (so it can keep using `paste_get_top`).

**Comment by nicm** [comment]
Or if you are adding a flag *and* adding an is-empty function, then it doesn't need to change. I don't mind.

**Comment by systemmonkey42** [comment]
I've created a pull request based on you suggestions, but I have a concern about how buffers
are deleted when the maximum number of buffers is reached.

I will have to find and review the code, but I suspect it will discard named buffers in that scenario. I'm not sure if it should
consider consider named buffers to be part of the buffer liimit count, or only consider automatic buffers to be part of that.

If it only considers automatic buffers, it would be safe to have a much smaller limit, since its rare to look back beyond the first two or three automatic buffers.
