### ISSUE TITLE
`set -g extended-keys always` does not work

### ISSUE THREAD

**Issue by mrbeardad** [tmux/tmux#3207]
### Issue description
I have set my windows terminal that map `ctrl+shift+f` to `\u001b[70;5u`,
it works well outside tmux,
![image](https://user-images.githubusercontent.com/54128430/171563548-3cc4fb69-267d-467a-823f-75c70af35ec0.png)
but not inside tmux,
![image](https://user-images.githubusercontent.com/54128430/171563666-b050edda-f6eb-45fa-b487-d366846ddf99.png)

my test .tmux.conf:
```conf
set -g extended-keys always
```

### Required information

Please provide the following information:

* tmux version: `tmux next-3.4`
* Platform: `Linux x86_64`
* $TERM inside and outside of tmux: inside: `screen-256color`, outside: `xterm-256color`
* Logs from tmux:
  * [tmux-client-1709.log](https://github.com/tmux/tmux/files/8821195/tmux-client-1709.log)
  * [tmux-server-1711.log](https://github.com/tmux/tmux/files/8821196/tmux-server-1711.log)
  * [tmux-out-1711.log](https://github.com/tmux/tmux/files/8821197/tmux-out-1711.log)

**Comment by nicm** [comment]
That is not C-S-f, it is just C-f and since there is an existing
representation of that key, tmux uses it instead of the extended version.

**Comment by mrbeardad** [comment]
Oh god! I've waste a lot of time on this issue, thank you very much!
