### ISSUE TITLE
Version 3.3 buffer issue when deleting inputted characters

### ISSUE THREAD

**Issue by codeaftermath** [tmux/tmux#3210]
### Issue description

Not sure if anybody else is noticing this problem. Latest version started having issue when deleting inputted characters on the line. When attempting to delete inputs on the line, it visually adds a buffer space instead of removing the character right before the cursor. Rollback to using 3.2a release and it appears to be working normally with this version.

### Required information
* tux 3.3
* Darwin i386
* tmux-256color

**Comment by tudorpavel** [comment]
I'm experiencing this issue too. 👍 

My info:
- tmux 3.3
- iTerm on macOS

**Comment by nicm** [comment]
If you install 3.3 manually it will work too, this is a problem with how Homebrew builds tmux, see this comment https://github.com/Homebrew/homebrew-core/issues/102748#issuecomment-1145378599 and later.
