### ISSUE TITLE
"server exited unexpectedly" and "Connection refused" after Arch Linux upgrade using pacman while trying to start a new-session

### ISSUE THREAD

**Issue by p-scvtvlatvs** [tmux/tmux#3211]
### Outputs and Logs (Required information)

* `tmux -V`.  tmux 3.3
* `uname -sp`.   - Linux unknown
* `echo $TERM`. - xterm-256color
* `tmux kill-server; tmux -vv new`. - server exited unexpectedly
* `cat tmux-client-3891.log` -
1654274159.357209 client started (3891): version 3.3, socket /tmp/tmux-1000/default, protocol 8
1654274159.357242 on Linux 5.18.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 May 2022 17:53:11 +0000
1654274159.357253 using libevent 2.1.12-stable (poll); ncurses 6.3
1654274159.357274 flags are 0x18010000
1654274159.357280 socket is /tmp/tmux-1000/default
1654274159.357294 trying connect                                       
1654274159.357310 connect failed: Connection refused
1654274159.357320 lock file is /tmp/tmux-1000/default.lock
1654274159.357336 flock succeeded
1654274159.357341 got lock (6)
1654274159.357348 trying connect
1654274159.357356 connect failed: Connection refused
1654274159.357652 add peer 0x559146fab850: 7 ((nil))
1654274159.358142 sending message 100 to peer 0x559146fab850 (4 bytes)
...
1654274159.359682 sending message 106 to peer 0x559146fab850 (0 bytes)                                                                                                                                          
1654274159.359749 cmd_pack_argv: argv[0]=new                                                                                                                                                                    
1654274159.359756 sending message 200 to peer 0x559146fab850 (8 bytes)                                                                                                                                          
1654274159.359761 client loop enter                                                                                                                                                                             
1654274159.359784 client_signal: Child exited                                                                                                                                                                   
1654274159.594278 client loop exit

**Comment by ksletmoe** [comment]
I had a similar issue @p-scvtvlatvs . When I looked at the corresponding server log (`cat tmux-server-7977.log`), I noticed that it ended with:

```
1654278747.718213 cmdq_fire_command <global>: (2761) run-shell \\~/.tmux/plugins/tpm/tpm
1654278747.718217 cmd_find_best_session: 0 sessions to try
1654278747.718221 cmd_find_current_client: no target, return 0x0
1654278747.718224 cmd_find_best_session: 0 sessions to try
1654278747.718228 cmd_find_current_client: no target, return 0x0
1654278747.718232 cmd_find_best_session: 0 sessions to try
1654278747.718236 cmd_find_target: target none, type pane, item 0x7fdfd05193d0, flags QUIET,CANFAIL
1654278747.718240 cmd_find_best_session: 0 sessions to try
1654278747.718244 cmd_find_target: error
1654278747.718248 format_defaults: c=none
1654278747.718252 format_defaults: s=none
1654278747.718256 format_defaults: wl=none
1654278747.718259 format_defaults: wp=none
1654278747.718263 format_expand1: expanding format: ~/.tmux/plugins/tpm/tpm
1654278747.718268 format_expand1: result is: ~/.tmux/plugins/tpm/tpm
1654278747.718273 cmdq_next <global>: exit (wait)
1654278747.718287 cmdq_next </dev/ttys001>: enter
1654278747.718291 cmdq_next </dev/ttys001>: [cfg_client_done/0x7fdfd050c8e0] (1), flags 0
1654278747.718295 cmdq_next </dev/ttys001>: exit (wait)
1654278747.718299 cmdq_next <global>: waiting
1654278747.718303 cmdq_next </dev/ttys001>: waiting
1654278747.718621 job_run: cmd=~/.tmux/plugins/tpm/tpm, cwd=/Users/sletmoe
1654278747.718703 run job 0x7fdfd05191b0: ~/.tmux/plugins/tpm/tpm, pid 7978
1654278747.718711 cmdq_next <global>: waiting
1654278747.718716 cmdq_next </dev/ttys001>: waiting
1654278747.718742 job write 0x7fdfd05191b0: ~/.tmux/plugins/tpm/tpm, pid 7978, output left 0
1654278747.718751 cmdq_next <global>: waiting
1654278747.718755 cmdq_next </dev/ttys001>: waiting
1654278747.718860 job_run: cmd=~/.tmux/plugins/tpm/tpm, cwd=/Users/sletmoe
1654278747.725400 job error 0x7fdfd05191b0: ~/.tmux/plugins/tpm/tpm, pid 7978
1654278747.725433 server_signal: Child exited: 20
1654278747.725452 job died 0x7fdfd05191b0: ~/.tmux/plugins/tpm/tpm, pid 7978
```

I don't have a `~/.tmux` directory at all, but I have this line at the bottom of my tmux config:
```run·'~/.tmux/plugins/tpm/tpm'```

I suspect at some point I was using tpm (I somehow don't remember this lol). Either way, when I removed that line from my config, it solved my issues. Maybe you have a similar problem? I suspect there's something in your config the server doesn't like.

**Comment by ovitente** [comment]
The same issue here. Just updated to 3.3.
Fixed by commenting the same line as @ksletmoe .

**Comment by p-scvtvlatvs** [comment]
> I had a similar issue @p-scvtvlatvs . When I looked at the corresponding server log (`cat tmux-server-7977.log`), I noticed that it ended with:
> 
> ```
> 1654278747.718213 cmdq_fire_command <global>: (2761) run-shell \\~/.tmux/plugins/tpm/tpm
> 1654278747.718217 cmd_find_best_session: 0 sessions to try
> 1654278747.718221 cmd_find_current_client: no target, return 0x0
> 1654278747.718224 cmd_find_best_session: 0 sessions to try
> 1654278747.718228 cmd_find_current_client: no target, return 0x0
> 1654278747.718232 cmd_find_best_session: 0 sessions to try
> 1654278747.718236 cmd_find_target: target none, type pane, item 0x7fdfd05193d0, flags QUIET,CANFAIL
> 1654278747.718240 cmd_find_best_session: 0 sessions to try
> 1654278747.718244 cmd_find_target: error
> 1654278747.718248 format_defaults: c=none
> 1654278747.718252 format_defaults: s=none
> 1654278747.718256 format_defaults: wl=none
> 1654278747.718259 format_defaults: wp=none
> 1654278747.718263 format_expand1: expanding format: ~/.tmux/plugins/tpm/tpm
> 1654278747.718268 format_expand1: result is: ~/.tmux/plugins/tpm/tpm
> 1654278747.718273 cmdq_next <global>: exit (wait)
> 1654278747.718287 cmdq_next </dev/ttys001>: enter
> 1654278747.718291 cmdq_next </dev/ttys001>: [cfg_client_done/0x7fdfd050c8e0] (1), flags 0
> 1654278747.718295 cmdq_next </dev/ttys001>: exit (wait)
> 1654278747.718299 cmdq_next <global>: waiting
> 1654278747.718303 cmdq_next </dev/ttys001>: waiting
> 1654278747.718621 job_run: cmd=~/.tmux/plugins/tpm/tpm, cwd=/Users/sletmoe
> 1654278747.718703 run job 0x7fdfd05191b0: ~/.tmux/plugins/tpm/tpm, pid 7978
> 1654278747.718711 cmdq_next <global>: waiting
> 1654278747.718716 cmdq_next </dev/ttys001>: waiting
> 1654278747.718742 job write 0x7fdfd05191b0: ~/.tmux/plugins/tpm/tpm, pid 7978, output left 0
> 1654278747.718751 cmdq_next <global>: waiting
> 1654278747.718755 cmdq_next </dev/ttys001>: waiting
> 1654278747.718860 job_run: cmd=~/.tmux/plugins/tpm/tpm, cwd=/Users/sletmoe
> 1654278747.725400 job error 0x7fdfd05191b0: ~/.tmux/plugins/tpm/tpm, pid 7978
> 1654278747.725433 server_signal: Child exited: 20
> 1654278747.725452 job died 0x7fdfd05191b0: ~/.tmux/plugins/tpm/tpm, pid 7978
> ```
> 
> I don't have a `~/.tmux` directory at all, but I have this line at the bottom of my tmux config: `run·'~/.tmux/plugins/tpm/tpm'`
> 
> I suspect at some point I was using tpm (I somehow don't remember this lol). Either way, when I removed that line from my config, it solved my issues. Maybe you have a similar problem? I suspect there's something in your config the server doesn't like.

Thanks, @ksletmoe!  I checked my `.tmux.conf` and I had a call to `powerline-daemon`.  It started working again after commenting the call.

@ovitente, try to look into your .tmux.conf for any calls that might be interfering with the tmux server start.

**Comment by ovitente** [comment]
@p-scvtvlatvs 
yes, i have reference to
```
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
```

Trying to make `sensilbe` work without tpm I cloned plugin file itself and used like that
`run-shell ~/.tmux/plugins/tmux-sensible/sensible.tmux`
but tmux was still crashing.

But it started working after I commented these lines in the `sensible.tmux` file:

```
	# if ctrl-a is prefix then `ctrl-a + a` switches between alternate windows.
	# Works for any prefix character.
	# if key_binding_not_set "$prefix_without_ctrl"; then
	#   tmux bind-key "$prefix_without_ctrl" last-window
	# fi

	# # easier switching between next/prev window
	# if key_binding_not_set "C-p"; then
	#   tmux bind-key C-p previous-window
	# fi
	# if key_binding_not_set "C-n"; then
	#   tmux bind-key C-n next-window
	# fi

	# source `.tmux.conf` file - as suggested in `man tmux`
	# if key_binding_not_set "R"; then
	#   local tmux_config=$(get_tmux_config)

	#   tmux bind-key R run-shell " \
	#     tmux source-file ${tmux_config} > /dev/null; \
	#     tmux display-message 'Sourced ${tmux_config}!'"
	# fi
```

**Comment by nicm** [comment]
Try applying this fix: https://github.com/tmux/tmux/commit/18838fbc877b5c003449fa10df353405c024f0f5.diff
