### ISSUE TITLE
Suggestion: Put a screenshot on the tmux.github.io landing page

### ISSUE THREAD

**Issue by lundmar** [tmux/tmux#3213]
First impressions matters.

I suggest you put a screenshot of tmux in action on the tmux.github.io landing page (wiki home).

Maybe this one:
![](https://raw.githubusercontent.com/wiki/tmux/tmux/images/tmux_marked_pane.png)

Or this one:
![](https://raw.githubusercontent.com/wiki/tmux/tmux/images/tmux_tiled.png)

**Comment by lundmar** [comment]
Maybe even also add it to the repo README welcome section.

**Comment by nicm** [comment]
There used to be a couple of screenshots but I don't really see the point TBH, they can't really show much.

**Comment by lundmar** [comment]
Just put one screenshot. That's all you need to keep the attention of people who do not know what tmux is.

**Comment by nicm** [comment]
I don't think one screenshot is necessary, sorry. If someone does create a screenshot collection then let me know and I will link to it.
