### ISSUE TITLE
How to increase the size of session name in status bar?

### ISSUE THREAD

**Issue by henryhu712** [tmux/tmux#3215]
### Issue description

When starting a session in tmux like this:

    tmux new -s session-name

I get the name display the below, instead of the full name:

    [session-n

How to configure tmux to allow it to show the complete name of the session? At least, extends its length to an acceptable size.

### Required information

tmux 2.6
Linux x86_64

**Comment by krader1961** [comment]
See the description of variable `status-left-length` in `man tmux`. It defaults to 10.

**Comment by henryhu712** [comment]
I tested status-left-length in ~/.tmux.conf:

    set -g status-left-length 30

It worked in tmux version 3.2a.

But it does not work in 2.6 or 3.0a version. I got the error:

```
$ tmux new -f .tmux.conf -s mysession
tmux: unknown option -- f
usage: new-session [-AdDEP] [-c start-directory] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]
```

I could not use .tmux.conf in tmux 2.6 or 3.0a.
