### ISSUE TITLE
How to prevent DoS via /tmp/tmux-$UID

### ISSUE THREAD

**Issue by mgerstner** [tmux/tmux#3216]
### Issue description

Currently by default tmux uses `/tmp` for storing users' sockets like `/tmp/tmux-0/default` for root's socket. Other users in the system (even such with low privileges, like `nobody`) can pre-create these directories, causing tmux to fail to start:

```
nobody $ mkdir /tmp/tmux-0
root # tmux
directory /tmp/tmux-0 has unsafe permissions
```

This could be considered a local denial of service against arbitrary other users.

Is there some simple way to globally configure tmux in a way that e.g. /run/user/$UID/tmux is used to prevent this?

### Required information

* tmux version: tmux 3.3
* Platform: Linux unknown

**Comment by nicm** [comment]
It doesn't stop you using tmux - if someone creates your directory, just put your socket somewhere else until you get it sorted out.

**Comment by mgerstner** [comment]
> It doesn't stop you using tmux - if someone creates your directory, just put your socket somewhere else until you get it sorted out.

Yes I am aware of that. It's not really obvious though from the error message though, naive end users even might try to "fix" the permissions of the existing folder, giving way to even more serious problems. Therefore I'm looking for a way to avoid such situations by default.

**Comment by nicm** [comment]
You can set the `TMUX_TMPDIR` environment variable, patch tmux to change `TMUX_SOCK` in `tmux.h`, or build with `-DTMUX_SOCK` in `CPPFLAGS`.

Make sure the default directory has appropriate permissions and don't make tmux setuid or setgid.

**Comment by nicm** [comment]
Actually, I don't think this will do what you want. I thought you could use `$USER` in `TMUX_SOCK`, but it will only expand environment variables at the start of the path, so it doesn't really give any benefit over just setting `$TMUX_TMPDIR`.

I would accept a patch to make `expand_path` do a bit more expansion (I'd suggest supporting `%%`, `%h`, `%u`, `%U` like `ssh`), if you want to look at that.

**Comment by nicm** [comment]
Although it does already expand `~/` so you could put the socket somewhere in ~...

**Comment by mgerstner** [comment]
Thanks for the hints. I will investigate and see if I can contribute a patch if necessary. I will not be available the next weeks, however, so it will take a bit.

**Comment by nicm** [comment]
OK I will close this but feel free to open a PR if you have something ready. Thanks!
