### ISSUE TITLE
Suggestion: Verbosity option for showing all or relevant formatting options

### ISSUE THREAD

**Issue by akwan** [tmux/tmux#3217]
### Issue description

Suggestion: A verbose flag for sections that allow formatting that shows all available or non-empty key/value pairs. Example:

```tmux list-sessions -F "'$(man tmux | sed -n -e '/Variable name/,/^[A-Za-z]/p' | grep -ve "^[A-Z]" | awk '{print $1}' | sed '$ d' | sed -n '2,$p' | awk '{print $1"=#{"$1"}"}' | tr '\n' ' ')'" | tr ' ' '\n' | awk -F'=' '$2 != "" {print $0}'```

This extracts the available formatting variable names from tmux's documentation, runs them through the filter and then displays the key/values where the value isn't empty.

Something like:
```
tmux list-sessions -v # show all non-empty key/value pairs
tmux list-sessions -va #show all key/value pairs
```
to accomplish the same thing natively. `F` could be incorporated as well if needed to delineate other flag options.

### Required information

Please provide the following information:

* tmux version: 2.6
* Platform Linux x86_64.

**Comment by nicm** [comment]
You mean like display-message -a?

**Comment by akwan** [comment]
Just updated to 3.3 and yup. Thanks!
