### ISSUE TITLE
Wrong character width for some characters

### ISSUE THREAD

**Issue by xuancong84** [tmux/tmux#322]
When I am outside tmux, the cursor size for Chinese comma (full-width comma) '，' is correct.
However, when I am inside tmux, the cursor size for Chinese comma is incorrect, although the cursor size for other Chinese characters including the period '。' are still correct. For those characters with wrong character width, if you type them and press backspace, the cursor will move to the wrong position (even before the $), the display will also be corrupted.
The cursor size for ？！； etc. are also wrong. Simply type them and press backspace and see what happens.
This occurs on Tmux 2.2.

**Comment by nicm** [comment]
Hi

What does "locale -a" show on your system?

**Comment by nicm** [comment]
Also please do this:

tmux -vvvLtest new

Then inside tmux:

printf 'a\uff0cb\n'
exit

Then send me the tmux-server-* log from the current directory.

**Comment by xuancong84** [comment]
1.
locale -a shows:
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
es_CU.utf8
POSIX
zh_CN.utf8
zh_HK.utf8
zh_SG.utf8
zh_TW.utf8

2.
printf 'a\uff0cb\n' shows correct:
a，b

The display of all full-width characters is correct, the only error occurs in cursor navigation across those full-width characters. The cursor width is also correct as I see a wide cursor over '，' instead of a narrow cursor (such as over ','), however, the spacing between '，' is incorrect, '，，，' should be widely spaced, but instead, I see them packed as ',,,'. But then, when I move cursor across them, the cursor also moves at steps of full-width, which is also correct. But then, the cursor does not highlight at the right character position, it goes all the way back before the $.

**Comment by nicm** [comment]
tmux is not responsible for the cursor, your terminal is. What terminal
are you using?

**Comment by xuancong84** [comment]
I use the standard Ubuntu Terminal with $TERM=xterm.
Strangely, in the terminal outside tmux, I don't have this error.

**Comment by nicm** [comment]
Where is the log file?

**Comment by xuancong84** [comment]
[tmux-client-20688.log.txt](https://github.com/tmux/tmux/files/156750/tmux-client-20688.log.txt)
[tmux-server-20690.log.txt](https://github.com/tmux/tmux/files/156749/tmux-server-20690.log.txt)

**Comment by nicm** [comment]
In the log I see this:

1457009196.243540 input_utf8_close 3 '\357\274\214' (width 1)

Which means tmux thinks that Unicode 0xff0c is width 1, when it should be width 2.

Are you sure your tmux build is up to date with Git master?

On my system (also Ubuntu), I see this:

1457009572.570318 input_utf8_close 3 '\357\274\214' (width 2)

**Comment by xuancong84** [comment]
Sorry. I have just updated. Now it gives the correct width for all characters I have tried. Thanks a lot!

**Comment by nicm** [comment]
Great thanks
