### ISSUE TITLE
Add a comand line option to disable acl checking

### ISSUE THREAD

**Issue by andynd** [tmux/tmux#3220]
### Issue description

The `server-access` comand added in 3.3 adds new restrictions when connecting to a tmux socket.
I'm using tmux in a cross namespace way, meaning my tmux server runs inside a nspawn container.
I'm using user namespaces and random uid ranges for that (`--private-users=pick`). I'm attatching to the socket from outside the namespace.

This will result in a `access not allowed` error since my user outside of the namespace is not on the list.
I can not add the user beforehand since the uid mapping will map it to nobody in all cases.
I could probably allow access for `nobody` and hope that works, but I'd realy prefere to just disable this acl feature and relay on socket file permissions.

Therefor I propose to add a new switch `--disable-acl-checks` or something like that. If set it should allow any access via the socket and ignore any acl settings.

**Comment by nicm** [comment]
No, I don't think so. But try this which should remove the requirement for a user to exist and let you add by UID: [tmux-server-access.diff.txt](https://github.com/tmux/tmux/files/8889424/tmux-server-access.diff.txt)

**Comment by georgalis** [comment]
I don't understand why server-access is used vs socket permissions?

I am creating a service that insures a tmux server is running on a socket with shared group permissions, will I be required to maintain access control in BOTH /etc/groups and tmux.conf?

**Comment by andir** [comment]
I am in a similar boat with cross-namespace tmux sessions. The process that is executing tmux doesn't have any knowledge about the users that will be attaching. I can see how this is a nice feature for "regular" multi-user boxes where you want to be a bit more specific with users (than you can traditionally be with just permissions on the socket).

I'll try the above linked patch, but would much rather welcome if Tmux would gain the proposed switch. Furthermore, I could try writing that patch if that would be acceptable.

**Comment by andynd** [comment]
@nicm would you merge a pull request which adds such a switch?

**Comment by nicm** [comment]
I don't see what the problem is, just add the users. If you can't use user names then use the patch I wrote above and add UIDs instead.

**Comment by nicm** [comment]
I'd accept a patch to allow a wildcard user (`*`) to be added, or to allow groups to be added, but not to disable at build time.
