### ISSUE TITLE
Question: is it possible to swap two windows/panes?

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#3221]
I 'm writing a utility; I have a session and I want to swap panes between the current session and mine. I know that I can move windows 
( I wrote https://github.com/nkh/tmuxake) but I want them to end up at exactly the same place in the current window. The window may have a lot of panes that I have no control over, is there a single command to swap to windows/panes?

**Comment by nicm** [comment]
swap-pane?

**Comment by nkh** [comment]
hrrm yes! a command I have used before, 

sorry for wasting your time, my head is not where it should be lately.
