### ISSUE TITLE
tmux 3.3a breaks window options window-status-(current-)format

### ISSUE THREAD

**Issue by zenfailure** [tmux/tmux#3224]
### Issue description

Tmux 3.3a seems to break options window-status-format and window-status-current-format when the format is somewhat complex.
In tmux 3.2a, I used these functions to customize the formats:
```
function command:winformat
{
    source "${TMUX_THEMES_DIR}/colors"

    local bar='∙'

    local iflast='#{==:#I,#{last_window_index}}'
    local ifbefore='#{==:#{active_window_index},#{e|+:#I,1}}'

    local format sep

    sep="#{?#{||:${iflast},${ifbefore}},,${bar}}"
    sep="#{?${iflast},,${bar}}"
    sep="#[none,bg=${WINLIST_BG},fg=${WINLIST_FGN}]${sep}"

    format="#{?#{window_zoomed_flag},[#I:#W],#I:#W}"
    format="#{?#{window_bell_flag},#[fg=${BELL_FG}]${format},${format}}"
    format="#{?#{window_activity_flag},#[fg=${TELL_FG}]${format},${format}}"
    format=" ${format} ${sep}"

    echo -n "$format"
}

function command:winformatactive
{
    source "${TMUX_THEMES_DIR}/colors"

    local bar='∙'

    local iflast='#{==:#I,#{last_window_index}}'
    local ifbefore='#{==:#{active_window_index},#{e|+:#I,1}}'

    local format sep

    sep="#{?#{||:${iflast},${ifbefore}},,${bar}}"
    sep="#{?${iflast},,${bar}}"
    sep="#[none,bg=${WINLIST_BG},fg=${WINLIST_FGN}]${sep}"

    format="#{?#{window_zoomed_flag},[#I:#W],#I:#W}"
    format=" ${format} ${sep}"

    echo -n "$format"
}
```
Then the config sets both options
```
tmux set -gw window-status-format "$(script winformat)"
tmux set -gw window-status-current-format "$(script winformatactive)"
```
One noticeable thing is that now tmux enters copy mode to detail the format it seems not to like. Once you leave copy mode, the formats don't seem to take effect as intended.
I didn't try looking into it, but since it worked perfectly in tmux3.2a, I guess it does break functionality. So mb it's a bug, or perhaps a consequence of a new feature (intended or not). Either way, I thought I'd mention it.

**Comment by nicm** [comment]
This means nothing to me. What did it look like before and what does it look like now?

Please try to cut your example down to something much smaller.

**Comment by zenfailure** [comment]
I have a hard time figuring out what's happening. When I drop the `tmux set -gw window-status-format "$(script winformat)" and just replace the $() with the computed format, it works fine. The formats are generated from a script, but they re really just tmux styles and formats in the end, nothing fancy.

I dont know why or how it does work in 3.2a and not in 3.3a, but I have to admit, I don't wanna look into it so long this little workaround does the trick.
