### ISSUE TITLE
Cursor style not changing in fish vi mode

### ISSUE THREAD

**Issue by yochem** [tmux/tmux#3226]
### Issue description

Using fish in Vi mode, one is able to let the cursor change from a line/bar when in insert mode, to a block when in normal mode. This has always worked with tmux v3.2a, but not with v3.3a. Neovim, which is capable of the same cursor changing, works normal with the current version of tmux. The cursor is always a block while using fish.

> Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
> before opening an issue.
> Please include the output of: uname -sp && tmux -V && echo $TERM

Darwin i386
tmux 3.3a
screen-256color

> Your platform (Linux, macOS, or whatever).

MacOS

> A brief description of the problem with steps to reproduce.

Use tmux 3.3a with fish as shell and this in the fish config file:
```fish
fish_vi_key_bindings
fish_vi_cursor --force-iterm
set -g fish_cursor_insert line
set -g fish_cursor_default block
```

> A minimal tmux config, if you can't reproduce without a config.
can reproduce without config

> Your terminal, and $TERM inside and outside of tmux.
- iTerm2
- $TERM inside: screen-256color
- $TERM outside: xterm-256color

> Logs from tmux (see below). Please attach logs to the issue directly rather than using a download site or pastebin. Put in a zip file if necessary.

[tmux-client-56700.log](https://github.com/tmux/tmux/files/8910294/tmux-client-56700.log)
[tmux-out-56702.log](https://github.com/tmux/tmux/files/8910295/tmux-out-56702.log)
[tmux-server-56702.log](https://github.com/tmux/tmux/files/8910296/tmux-server-56702.log)

At most one or two screenshots, if helpful.

> If you have upgraded, make sure your issue is not covered in the CHANGES file
> for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Probably has something to do with `Add cursor-style and cursor-colour options to set the default cursor style
and colour.`

> Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
> built from the latest code in Git.

✅

**Comment by nicm** [comment]
Looks like it is using the passthrough escape sequence to change cursor shape which is no longer permitted by default.

**Comment by nicm** [comment]
They should be using DECSCUSR to change cursor shape (from https://invisible-island.net/xterm/ctlseqs/ctlseqs.html):
~~~~
CSI Ps SP q
          Set cursor style (DECSCUSR), VT520.
            Ps = 0  ⇒  blinking block.
            Ps = 1  ⇒  blinking block (default).
            Ps = 2  ⇒  steady block.
            Ps = 3  ⇒  blinking underline.
            Ps = 4  ⇒  steady underline.
            Ps = 5  ⇒  blinking bar, xterm.
            Ps = 6  ⇒  steady bar, xterm.
~~~~

**Comment by nicm** [comment]
Why are you doing `fish_vi_cursor --force-iterm`? tmux is not iterm.

**Comment by nicm** [comment]
Well, never mind that, I don't know how it works.

**Comment by yochem** [comment]
Otherwise the cursor also does not change outside of tmux. Although it seems there is a [fix on its way](https://github.com/fish-shell/fish-shell/commit/b41c0869842210ffea571246389513fff6a4a084).

**Comment by nicm** [comment]
The passthrough escape sequence has not been removed but is now disabled by default.

tmux supports `DECSCUSR` so you should use it inside tmux and let tmux work out if the terminal can support it.
