### ISSUE TITLE
feature request: make disabling 'synchronize-panes on' when zoomed in, configurable

### ISSUE THREAD

**Issue by jrg247** [tmux/tmux#3227]
When I zoom into a pane, the 'synchronize-panes on' switches to 'off' and returns to 'on' when I zoom off. This can create obstacles in some scenarios, please see below.

I know someone has requested that panes not to be synchronized when zoom is active in #1472, but there are good reasons why this behavior should be made optional:

- better scalability: I can have, say, 20 panes opened and fully zoomed into one, then switch panes one-by-one by zooming into them. This will fit in a console or term window compared to a case when I'd select tiled or similar view.

- using any pane split mode on a 80x25 character term/console is not really useful unless I have only a very few panes active

Hence I'd like to suggest an extra boolean option like 'synchronize-panes-on-when-zoomed'. It should default to off to preserve default behavior, but when set to on, it should still allow (at least) synchronized keyboard input updates even in currently not visible panes (due to zoom).

tmux 3.3a
Linux Intel(R) Celeron(R) M processor 1.00GHz
tmux-256color

**Comment by nicm** [comment]
I don't think it is a good idea to have `synchronize-panes` work when you can't see the panes. You can always script it instead.

**Comment by jrg247** [comment]
Please allow me to oppose here. For me, the support of the function I would like is absolutely essential.

I'd be fine even with 'synchronize-windows on' (which would, in fact, be exactly what I'm trying to mimic).

If you repeatedly maintain clusters of multiple (say, per 10) devices (lets say ethernet switches) with identical setup, you'd only want to occasionally peek if everything went smoothly, in particular moments. Just like you do with pssh, but with the only difference you need the interaction to eventually change the course (hence tmux). You cannot script becouse the interactive nature of peer systems may produce unexpected errors, but you'd always see when this happens provided that you maintain identical setups. And I'd prefer a solution "multiple interactive sessions, one of them visible" rather than trying to script/adhere to commercial, vendor-limited solution.

**Comment by nicm** [comment]
I don't think this is something tmux should support natively, but it ia trivial to script "send X to all windows" with tmux if that is what you want.

**Comment by jrg247** [comment]
If "X" is a predefined command, then this is no different from non-interactive input (which I dont need, the reasons why I've already told - becouse I can NOT "always script"). If "X" can be a "keyboard input", then please point me to the part of docs that describes how to accomplish that.

**Comment by nicm** [comment]
Use `command-prompt` to ask you for what to send.

**Comment by jrg247** [comment]
Thanks, will try to do.

**Comment by nicm** [comment]
Maybe we could do it and make `synchronize-panes` a three state option, but I am not wild about it at all, this seems like something that would be a dangerous feature to use so I do not think it should necessarily be easy.

Another option would be to create a new key table and use the `Any` key to forward the keys to all windows, but I don't remember if there is a way to access the actual key pressed from the `Any` key binding, so that would need to be added.

**Comment by nicm** [comment]
OK you can do this already. Try this:
~~~~
bind -Tall-windows Any run -C '#{W:send -t#{window_id};}'
bind x if -F '#{==:#{key-table},root}' { set key-table all-windows } { set -u key-table }
~~~~
Press `C-b x` to start sending to all windows and `C-b x` again to stop.

You will probably want to extend this to make it show a message or change something visible when enabled.

**Comment by nicm** [comment]
You should be able to do the same for panes by using the `P` modifier and `pane_id` instead.

**Comment by jrg247** [comment]
Thanks, [https://github.com/tmux/tmux/issues/3227#issuecomment-1158865460](url) seems to do the trick.
I'm just currently fighting with how to supply the last line (tmux bind x if -F '#{== ...) to a running tmux session through bash. When trying to feed it through the bash, tmux returns:

`command if-shell: too many arguments (need at most 3)`

I admit I'm quite puzzled what escaping should I use in that case...

**Comment by nicm** [comment]
You will need to add them to the all-windows table as well.
