### ISSUE TITLE
How to pass C-l to zsh?

### ISSUE THREAD

**Issue by dankelley** [tmux/tmux#3228]
### Issue description

I've been using tmux on macOS for years, and love it.  I have prefix bound to C-space because that's easy for my not-especially-young hands to type without error or pain.

A few days ago I was silly and told homebrew that I wanted to update all the things it had installed.  Now, I am finding that a terminal (either item2 or the mac terminal) does not understand C-l anymore.  Instead of clearing the terminal window, it repeats my zsh prompt.

I use C-l a lot, to clear out the screen so I can focus on what I'm doing at the moment.  I'd love to get it back, so I can start using tmux again without having to learn a new "chord" to type.  (I wouldn't mind if C-a and the other readline things also started to work again.)

My web searching has not turned up a way to disable C-l.  I tried
```
bind-key C-l send-keys 'C-l'
```
but that did not help.  (I have never understood tmux setup adequately, and so the above might not even be close to what I ought to be using ... it's just something I found online.)

Is there a way I can get C-l (and perhaps also C-a and a few other things) to be transmitted through tmux down to the terminal?

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
```
tmux 3.3a
```
* Platform (`uname -sp`).
```
Darwin i386
```
* $TERM inside and outside of tmux (`echo $TERM`).
```
xterm-256color # both inside and outside
```
* Logs from tmux (`tmux kill-server; tmux -vv new`). 
[tmux-client-62720.log](https://github.com/tmux/tmux/files/8929471/tmux-client-62720.log)

**Comment by nicm** [comment]
Read the second section at the top of this issue about macOS and see if it fixes it?

**Comment by nicm** [comment]
Oh you have TERM=xterm-256color inside tmux, that is wrong for a start.

**Comment by nicm** [comment]
Does it make any difference if you set TERM to tmux-256color or screen-256color inside tmux?

**Comment by dankelley** [comment]
Wow, so fast and so helpful!! Thanks, @nicm.  I did
```
TERM=screen-256color
```
in my tmux session, and the problem went away.  I wonder if I should have a setting in my `tmux.conf` or `.zshrc` to do this?  (Or maybe it's buried somewhere in my iterm2 settings?  I'll look...)

**Comment by dankelley** [comment]
In iterm2 settings, I have the following choices.  I wonder if I ought to switch to another.
<img width="531" alt="Screen Shot 2022-06-17 at 2 27 51 PM" src="https://user-images.githubusercontent.com/99469/174348675-347673a8-5f77-4d87-be65-d01f9c0b1bcc.png">

**Comment by nicm** [comment]
The best idea is usually not to set TERM at all and let the terminal do it, in this case you would not set TERM at all for tmux in your shell profiles and do `set -g default-terminal screen-256color` in .tmux.conf.

**Comment by dankelley** [comment]
If I unset TERM (checked with `echo $TERM`) and try to start tmux I get
```
➜  ~ tmux
open terminal failed: terminal does not support clear
```

**Comment by dankelley** [comment]
I tried setting the iterm2 terminal type to `linux` and I get my original problem of C-l not working.  For further information, when I launch tmux now I get
```
➜  ~ echo $TERM
tmux-256color
```
so the `default-terminal` didn't quite work since it referred to `screen-256color`.

**Comment by dankelley** [comment]
Please ignore https://github.com/tmux/tmux/issues/3228#issuecomment-1159102091; the setting was being over-written by something I found that purported to be a good default (installed by homebrew).  I had just naively copied that file, thinking that my own `.tmux.conf` was problematic.

I think this issue has been addressed.  I am not sure of the protocol on this forum, but I will go ahead and close the issue, to save someone else the hassle of having to do so. 

Thanks *very* much, @nicm, for your amazingly fast response and also for your patience.
