### ISSUE TITLE
Running cmd in SummaryWindow

### ISSUE THREAD

**Issue by mrx23dot** [tmux/tmux#3229]
### Issue description
Summary window [S] could contain running command, same way as htop does,
other way it's very **hard to say which window run what.**

Especially when there are so many printed text in each window that command is no longer visible.
![2022-06-18_123425_7H](https://user-images.githubusercontent.com/4163396/174435763-f65afe39-4958-4542-b150-080bd10dff0f.jpg)

(also why isn't there long line history in each window?)
PageUp only inputs extra characters:
![2022-06-18_123849_Qy](https://user-images.githubusercontent.com/4163396/174435825-6933ad84-3471-4aed-b3d3-c6a90b3441e7.jpg)
mouse scroll up goes back into cmd outside tmux, e.g. tmux a

versions:
tmux 3.1c
debian10
over Putty

**Comment by nicm** [comment]
You can customize this with `-f` but I think the default is just fine especially since I have no idea what change you are suggesting.

**Comment by nicm** [comment]
I think the default is fine, I don't want it too cluttered and for most people the running command in the active pane in the current window is irrelevant for choosing a session. If you want to show it then you can rebind the `s` and `w` keys with whatever format you like.
