### ISSUE TITLE
Running rake causes 'lost server'

### ISSUE THREAD

**Issue by drzel** [tmux/tmux#323]
Works fine in tmux 2.0, and outside of tmux, but in tmux 2.2 just compiled from head I get this:
![Screenshot](http://i.imgur.com/R1gfXcb.png)

**Comment by nicm** [comment]
Show me the -vvvv logs?

**Comment by drzel** [comment]
[Server](https://gist.github.com/drzel/b02f0ed2bade12c9b8ce)
[Client](https://gist.github.com/drzel/cefe22ec2e27d1d1ebdc)
[Out](https://gist.github.com/drzel/c079023d8b5021326450)

**Comment by nicm** [comment]
Thanks; does tmux leave a core? You may need to do "ulimit -c unlimited" first.

**Comment by drzel** [comment]
I'm not sure what you mean by does tmux leave a core (sorry). Running `unlimit` returns `unlimited`, and running `unlimit -c unlimited` both before launching tmux and while inside tmux had no effect.

**Comment by nicm** [comment]
After tmux crashes, is there a file matching *core* in the directory
where you started it. It may be 'tmux.core' or 'core.1234' or just
'core'.

**Comment by nicm** [comment]
Never mind, I reproduced it.

**Comment by drzel** [comment]
Cool. Was struggling to export the file, but yes, it was produced. (:

**Comment by nicm** [comment]
This should be fixed in master now.

**Comment by drzel** [comment]
Confirmed working. Thanks.
