### ISSUE TITLE
Tab switches client in grouped session

### ISSUE THREAD

**Issue by MNolan147** [tmux/tmux#3231]
I have created a tmux session `main` then connected to it with another session using `tmux new -t main` to create a session group. 

My current workspace has two terminal clients open, both connected to the same session group. Attempting to use tab to complete a command causes focus to change from one of the clients to the other. It only does this when the command was unsuccessfully completed (i.e. a list of possible completions is displayed).

### Required information

Version: `tmux 3.2a`
Platform: `Linux x86_64`
$TERM inside tmux: `xterm-256color`
$TERM outside tmux: `xterm-256color`

**Comment by nicm** [comment]
What do you mean by "focus change"?

**Comment by MNolan147** [comment]
@nicm the input switches from the first to the second and I have to click back on the first one to continue typing.

**Comment by nicm** [comment]
So the actual window manager focus changes? How could this be anything to do with tmux?

**Comment by nicm** [comment]
tmux has no way to affect which terminal window your window manager has in focus, it can only change what is inside the terminal window. This is an issue with your WM.

**Comment by nicm** [comment]
Show me a video of what is happening, also tmux logs.

**Comment by MNolan147** [comment]
Here is a video:

https://user-images.githubusercontent.com/45273913/174585210-3db73056-6953-4fce-b30f-fc1643827c84.mp4

Tmux client log:

> 1655684118.593424 client started (544611): version 3.2a, socket /tmp/tmux-1000/default, protocol 8
> 1655684118.593471 on Linux 5.15.0-35-generic #36-Ubuntu SMP Sat May 21 02:24:07 UTC 2022
> 1655684118.593485 using libevent 2.1.12-stable (poll); ncurses 6.3
> 1655684118.593541 flags are 0x18010000
> 1655684118.593559 socket is /tmp/tmux-1000/default
> 1655684118.593581 trying connect
> 1655684118.593607 connect failed: Connection refused
> 1655684118.593625 lock file is /tmp/tmux-1000/default.lock
> 1655684118.593669 flock succeeded
> 1655684118.593678 got lock (6)
> 1655684118.593691 trying connect
> 1655684118.593706 connect failed: Connection refused
> 1655684118.593977 add peer 0x56393b0ed600: 7 ((nil))
> 1655684118.594554 sending message 100 to peer 0x56393b0ed600 (4 bytes)
> 1655684118.594583 sending message 111 to peer 0x56393b0ed600 (8 bytes)
> 1655684118.594596 sending message 101 to peer 0x56393b0ed600 (15 bytes)
> 1655684118.594610 sending message 109 to peer 0x56393b0ed600 (4 bytes)
> 1655684118.594621 sending message 102 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.594638 sending message 108 to peer 0x56393b0ed600 (14 bytes)
> 1655684118.594650 sending message 112 to peer 0x56393b0ed600 (58 bytes)
> 1655684118.594666 sending message 112 to peer 0x56393b0ed600 (5 bytes)
> 1655684118.594677 sending message 112 to peer 0x56393b0ed600 (5 bytes)
> 1655684118.594687 sending message 112 to peer 0x56393b0ed600 (6 bytes)
> 1655684118.594696 sending message 112 to peer 0x56393b0ed600 (6 bytes)
> 1655684118.594707 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.594722 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.594733 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.594742 sending message 112 to peer 0x56393b0ed600 (14 bytes)
> 1655684118.594751 sending message 112 to peer 0x56393b0ed600 (19 bytes)
> 1655684118.594760 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.594770 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.594779 sending message 112 to peer 0x56393b0ed600 (15 bytes)
> 1655684118.594788 sending message 112 to peer 0x56393b0ed600 (21 bytes)
> 1655684118.594798 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.594807 sending message 112 to peer 0x56393b0ed600 (7 bytes)
> 1655684118.594827 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.594849 sending message 112 to peer 0x56393b0ed600 (7 bytes)
> 1655684118.594861 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.594881 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.594902 sending message 112 to peer 0x56393b0ed600 (21 bytes)
> 1655684118.594921 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.594934 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.594955 sending message 112 to peer 0x56393b0ed600 (16 bytes)
> 1655684118.594974 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.594995 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.595015 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.595036 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595057 sending message 112 to peer 0x56393b0ed600 (8 bytes)
> 1655684118.595078 sending message 112 to peer 0x56393b0ed600 (8 bytes)
> 1655684118.595089 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.595105 sending message 112 to peer 0x56393b0ed600 (7 bytes)
> 1655684118.595120 sending message 112 to peer 0x56393b0ed600 (7 bytes)
> 1655684118.595134 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.595150 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.595170 sending message 112 to peer 0x56393b0ed600 (15 bytes)
> 1655684118.595190 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.595210 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595232 sending message 112 to peer 0x56393b0ed600 (8 bytes)
> 1655684118.595252 sending message 112 to peer 0x56393b0ed600 (14 bytes)
> 1655684118.595272 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.595288 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.595321 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.595341 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.595358 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.595379 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.595401 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.595418 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595439 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595460 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595479 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595497 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595517 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.595538 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.595559 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595578 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595598 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595613 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595631 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595646 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.595661 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595681 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.595702 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.595723 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.595744 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.595759 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.595780 sending message 112 to peer 0x56393b0ed600 (8 bytes)
> 1655684118.595802 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.595823 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.595843 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.595865 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595880 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595892 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595912 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.595932 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.595952 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.595973 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.595994 sending message 112 to peer 0x56393b0ed600 (8 bytes)
> 1655684118.596012 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596034 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596054 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596071 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596090 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596110 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596125 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596168 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596190 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596213 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596231 sending message 112 to peer 0x56393b0ed600 (8 bytes)
> 1655684118.596254 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596273 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596287 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596303 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596320 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596332 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596348 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596367 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596388 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596409 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596473 sending message 112 to peer 0x56393b0ed600 (8 bytes)
> 1655684118.596494 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596514 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596533 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596553 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596573 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596596 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596618 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596641 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596662 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596683 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596703 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.596726 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596748 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596765 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.596787 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596810 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596831 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596855 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596875 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596889 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596941 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.596964 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.596987 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597005 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597024 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597045 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597067 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.597088 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.597110 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.597131 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597153 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597176 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597197 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597219 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597241 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597263 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.597278 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.597300 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597327 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597340 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597352 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597368 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597391 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.597413 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597433 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597453 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597464 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597479 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597496 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597531 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597687 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.597715 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.597745 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597777 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597805 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597829 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597861 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597890 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597914 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.597937 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.597962 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.597985 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598012 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598035 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598078 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598101 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.598125 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.598148 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598178 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598206 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598229 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598251 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598274 sending message 112 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.598303 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.598332 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.598360 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.598384 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.598408 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.598445 sending message 112 to peer 0x56393b0ed600 (21 bytes)
> 1655684118.598478 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.598503 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.598528 sending message 112 to peer 0x56393b0ed600 (6 bytes)
> 1655684118.598552 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598577 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.598600 sending message 112 to peer 0x56393b0ed600 (24 bytes)
> 1655684118.598616 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598634 sending message 112 to peer 0x56393b0ed600 (9 bytes)
> 1655684118.598659 sending message 112 to peer 0x56393b0ed600 (70 bytes)
> 1655684118.598685 sending message 112 to peer 0x56393b0ed600 (69 bytes)
> 1655684118.598702 sending message 112 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.598727 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.598739 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.598759 sending message 112 to peer 0x56393b0ed600 (24 bytes)
> 1655684118.598776 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598804 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.598828 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.598852 sending message 112 to peer 0x56393b0ed600 (10 bytes)
> 1655684118.598882 sending message 112 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.598909 sending message 112 to peer 0x56393b0ed600 (15 bytes)
> 1655684118.598934 sending message 112 to peer 0x56393b0ed600 (5 bytes)
> 1655684118.598948 sending message 104 to peer 0x56393b0ed600 (0 bytes)
> 1655684118.598973 sending message 110 to peer 0x56393b0ed600 (0 bytes)
> 1655684118.598992 sending message 107 to peer 0x56393b0ed600 (4 bytes)
> 1655684118.599013 sending message 105 to peer 0x56393b0ed600 (40 bytes)
> 1655684118.599038 sending message 105 to peer 0x56393b0ed600 (64 bytes)
> 1655684118.599058 sending message 105 to peer 0x56393b0ed600 (20 bytes)
> 1655684118.599075 sending message 105 to peer 0x56393b0ed600 (54 bytes)
> 1655684118.599082 sending message 105 to peer 0x56393b0ed600 (21 bytes)
> 1655684118.599086 sending message 105 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.599091 sending message 105 to peer 0x56393b0ed600 (16 bytes)
> 1655684118.599097 sending message 105 to peer 0x56393b0ed600 (28 bytes)
> 1655684118.599103 sending message 105 to peer 0x56393b0ed600 (19 bytes)
> 1655684118.599110 sending message 105 to peer 0x56393b0ed600 (48 bytes)
> 1655684118.599120 sending message 105 to peer 0x56393b0ed600 (17 bytes)
> 1655684118.599127 sending message 105 to peer 0x56393b0ed600 (18 bytes)
> 1655684118.599133 sending message 105 to peer 0x56393b0ed600 (16 bytes)
> 1655684118.599141 sending message 105 to peer 0x56393b0ed600 (268 bytes)
> 1655684118.599150 sending message 105 to peer 0x56393b0ed600 (18 bytes)
> 1655684118.599156 sending message 105 to peer 0x56393b0ed600 (19 bytes)
> 1655684118.599162 sending message 105 to peer 0x56393b0ed600 (15 bytes)
> 1655684118.599169 sending message 105 to peer 0x56393b0ed600 (50 bytes)
> 1655684118.599175 sending message 105 to peer 0x56393b0ed600 (22 bytes)
> 1655684118.599182 sending message 105 to peer 0x56393b0ed600 (20 bytes)
> 1655684118.599189 sending message 105 to peer 0x56393b0ed600 (13 bytes)
> 1655684118.599196 sending message 105 to peer 0x56393b0ed600 (17 bytes)
> 1655684118.599203 sending message 105 to peer 0x56393b0ed600 (26 bytes)
> 1655684118.599211 sending message 105 to peer 0x56393b0ed600 (16 bytes)
> 1655684118.599218 sending message 105 to peer 0x56393b0ed600 (147 bytes)
> 1655684118.599225 sending message 105 to peer 0x56393b0ed600 (31 bytes)
> 1655684118.599232 sending message 105 to peer 0x56393b0ed600 (15 bytes)
> 1655684118.599238 sending message 105 to peer 0x56393b0ed600 (23 bytes)
> 1655684118.599246 sending message 105 to peer 0x56393b0ed600 (25 bytes)
> 1655684118.599254 sending message 105 to peer 0x56393b0ed600 (19 bytes)
> 1655684118.599261 sending message 105 to peer 0x56393b0ed600 (25 bytes)
> 1655684118.599267 sending message 105 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.599275 sending message 105 to peer 0x56393b0ed600 (8 bytes)
> 1655684118.599282 sending message 105 to peer 0x56393b0ed600 (21 bytes)
> 1655684118.599289 sending message 105 to peer 0x56393b0ed600 (45 bytes)
> 1655684118.599298 sending message 105 to peer 0x56393b0ed600 (43 bytes)
> 1655684118.599304 sending message 105 to peer 0x56393b0ed600 (29 bytes)
> 1655684118.599310 sending message 105 to peer 0x56393b0ed600 (132 bytes)
> 1655684118.599316 sending message 105 to peer 0x56393b0ed600 (39 bytes)
> 1655684118.599321 sending message 105 to peer 0x56393b0ed600 (11 bytes)
> 1655684118.599325 sending message 105 to peer 0x56393b0ed600 (8 bytes)
> 1655684118.599330 sending message 105 to peer 0x56393b0ed600 (32 bytes)
> 1655684118.599336 sending message 105 to peer 0x56393b0ed600 (12 bytes)
> 1655684118.599339 sending message 105 to peer 0x56393b0ed600 (16 bytes)
> 1655684118.599345 sending message 106 to peer 0x56393b0ed600 (0 bytes)
> 1655684118.599352 cmd_pack_argv: argv[0]=new
> 1655684118.599357 cmd_pack_argv: argv[1]=-s
> 1655684118.599363 cmd_pack_argv: argv[2]=main
> 1655684118.599368 sending message 200 to peer 0x56393b0ed600 (16 bytes)
> 1655684118.599373 client loop enter
> 1655684118.599399 client_signal: Child exited
> 1655684118.641716 peer 0x56393b0ed600 message 207
> 1655684118.641746 sending message 208 to peer 0x56393b0ed600 (0 bytes)
> 1655684152.893620 peer 0x56393b0ed600 message 210
> 1655684152.893637 sending message 205 to peer 0x56393b0ed600 (0 bytes)
> 1655684152.894050 peer 0x56393b0ed600 message 204
> 1655684152.894062 client loop exit
>

**Comment by nicm** [comment]
Does this still happen if you start tmux without a `.tmux.conf` like this:
~~~~
tmux kill-server
tmux -f/dev/null new
~~~~
If so please show tmux server log.

**Comment by MNolan147** [comment]
Yes, it still happens.
Here is the server log:

[tmux-server-592115.log](https://github.com/tmux/tmux/files/8944723/tmux-server-592115.log)

I also tested some other situations, to see if it would happen in those:

1. creating a new session and attaching to it directly (`tmux new -s main` in one client, then `tmux attach -t main` in the other). It happened in this one as well.
2. Creating a session group and attaching to that (`tmux new -t main` in one, then `tmux new -t main` in the other, without creating a new window). It happened here as well.

**Comment by nicm** [comment]
This is a problem with your WM. There is no mechanism for tmux to change focus outside the window it is running in, and there is no evidence in the log of it running any external command which can do so.

Does this still happen if you use a different window manager?

**Comment by MNolan147** [comment]
Alright, I’ll look into it. I use sway so I’ll have a look for issues there. Thanks for helping me narrow down this issue. I’ll close it now.
