### ISSUE TITLE
Force redraw from the control mode

### ISSUE THREAD

**Issue by joshh101** [tmux/tmux#3233]
* tmux version: 3.0a
* Platform: Linux x86_64
* $TERM:  xterm-256color

I'm developing an web application that makes use of TMUX Control Mode for tmux sessions in a webpage.
I would like some help on how I could force a pane to redraw from the Control mode connection.

The reason why, is because I'm trying to monitor the output of all panes within a window, and display the contents of each pane to a web app and it needs to use a single ssh connection, instead of multiple attach tmux clients. 

The problem comes, when a command like 'htop' is running in a pane, if I try to attach a Control mode session, the control node will only receive the part of the screen that changes.  

However, if I create a normal CLI tmux client in gnome-terminal (or similar), it will some how be able to receive the previous session output, how it is able to do this, as that redrawn output is not show in the control mode logs?

**Comment by nicm** [comment]
Use `capture-pane -p` to retrieve the current pane contents and `-P` for any pending unprocessed output.

**Comment by joshh101** [comment]
@nicm This works, thank you so much. 

I do have another small question now, is there anyway to format the output from `capture-pane -p`? 
the current way the output is detected in my code is by looking for the `%output` notification event among the control mode session log
