### ISSUE TITLE
[question] mapping something to F13?

### ISSUE THREAD

**Issue by alex-popov-tech** [tmux/tmux#3234]
### Issue description

Hello!

Im trying to map F13 to something with following config lines:
```
# bind-key -n F13 list-keys
bind-key -n S-F1 list-keys
```
but pressing this button gives me 
```
57376u
```

and using `cat` and pressing same button gives me
```
> cat
^[[57376u
```

I tried to search for issues, code, wiki, and same things in terminal's repo, but didn't find examples on how to do that, or why my config is not working :(

### Required information

* terminal - kitty 
* tmux version (`tmux -V`). `tmux 3.3a`
* Platform (`uname -sp`). `Darwin i386`
* $TERM inside and outside of tmux (`echo $TERM`). `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

attached logs
[tmux-client-85131.log](https://github.com/tmux/tmux/files/8952886/tmux-client-85131.log)
[tmux-out-85253.log](https://github.com/tmux/tmux/files/8952887/tmux-out-85253.log)

i wasn't able to attach server log as its bigger than 25mb, but here may be lines which could say something:
```
...
1655846605.357507 cmdq_fire_command <global>: (2805) bind-key -n F13 list-keys
1655846605.357512 cmd_find_best_session: 0 sessions to try
1655846605.357516 cmd_find_current_client: no target, return 0x0
1655846605.357521 cmd_find_best_session: 0 sessions to try
1655846605.357525 cmd_find_current_client: no target, return 0x0
1655846605.357530 cmd_find_best_session: 0 sessions to try
1655846605.357534 cmd_find_best_session: 0 sessions to try
1655846605.357542 cmdq_error: unknown key: F13
1655846605.357549 cmdq_next <global>: [bind-key/0x7fcc62b09350] (0), flags 0
1655846605.357557 cmdq_fire_command <global>: (2808) bind-key -n S-F1 list-keys
1655846605.357562 cmd_find_best_session: 0 sessions to try
1655846605.357566 cmd_find_current_client: no target, return 0x0
1655846605.357571 cmd_find_best_session: 0 sessions to try
1655846605.357575 cmd_find_current_client: no target, return 0x0
1655846605.357580 cmd_find_best_session: 0 sessions to try
1655846605.357584 cmd_find_best_session: 0 sessions to try
1655846605.357589 yylex_token: list-keys
1655846605.357595 cmd_parse_build_commands 0:0: list-keys
1655846605.357601 args_parse: flags end at 1 of 1
1655846605.357606 cmd_parse_build_commands: list-keys
1655846605.357613 key_bindings_add: 0x40000010e195 S-F1 = list-keys
...
```

**Comment by nicm** [comment]
57376u looks like some nonsense Kitty key sequence. You'll either need
to configure Kitty to send something tmux recognises or bind it using
the tmux user-keys option.

**Comment by alex-popov-tech** [comment]
@nicm thank you for such rapid response!
it seems i was lucky to setup it like:
```
# F13
set -s user-keys[0] '57376u'
set-option -g prefix User0
```
for setting `F13` to `prefix`
thank you again! <3

**Comment by nicm** [comment]
You will probably want to make this `\e[57376u` since that is the full sequence.

**Comment by alex-popov-tech** [comment]
actually after i've achieved what i wanted i thought that its unwise to map tmux prefix to key i don't have on my macbook, it can cause difficulties if i won't have external keyboard around :D

**Comment by nicm** [comment]
You can have two prefix keys (or more).
