### ISSUE TITLE
tmux input problem

### ISSUE THREAD

**Issue by qytang2014** [tmux/tmux#3235]
when I enter tmux window, and I start to input, it occurs problem, like this:

https://user-images.githubusercontent.com/10326897/175449519-a93ae3cd-0c81-404e-a4bd-d97276abe2dc.mp4

Please provide the following information:

* tmux version : tmux 3.3a
* Platform (`uname -sp`): Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`). : tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`). 
[tmux-client-71756.log](https://github.com/tmux/tmux/files/8972742/tmux-client-71756.log)
[tmux-out-71758.log](https://github.com/tmux/tmux/files/8972743/tmux-out-71758.log)
[tmux-server-71758.log](https://github.com/tmux/tmux/files/8972744/tmux-server-71758.log)

**Comment by nicm** [comment]
I don't see you typing anything in this log apart from `exit` and that seems to be sent to the terminal fine.

**Comment by qytang2014** [comment]
you can watch the video that I upload. When I input ls , the terminal shows lls

**Comment by nicm** [comment]
Right but your log does not show this.

**Comment by qytang2014** [comment]
now it is normal, it is amazing
thank you for reply
