### ISSUE TITLE
auto closed window!

### ISSUE THREAD

**Issue by kache1995** [tmux/tmux#3236]
* tmux version  : tmux 3.2a
* Platform : Linux x86_64
* $TERM inside and outside of tmux: xterm

hello，I find if I not use the window or panel(no action for a long time)，it will be auto closed. why and how to keep the window or panel which no action for a long time

**Comment by nicm** [comment]
Your shell is probably exiting but how am I meant to tell anything without any logs?

**Comment by kache1995** [comment]
[tmux-client-38541.log](https://github.com/tmux/tmux/files/8975519/tmux-client-38541.log)

**Comment by nicm** [comment]
Show server log please.

**Comment by bew** [comment]
If you are using `bash`, check the environment variable `TMOUT`, if it's not 0, it's the time in seconds before bash will auto close itself.
You can disable this by setting `TMOUT=0` in your bashrc
