### ISSUE TITLE
inputs on remote shell when connecting with ssh

### ISSUE THREAD

**Issue by philipGaudreau** [tmux/tmux#3238]
When I ssh into server from my local machine (macOS 12.3.1), there seems to have an integration problem with kitty. I think it tries to send escape sequence, but somehow tmux catches it and input it as shell commands. See https://github.com/kovidgoyal/kitty/issues/5227.

This problem only arise with tmux 3.3+. I tested same thing being equals elsewhere with tmux 3.2a and it worked fine.

### Context
```
uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 3.3a (same behavior with tmux next-3.4)
tmux-256color (inside tmux)
xterm-kitty (outside tmux)
```
---

The problem can be reproduced with tmux 3.3a (empty config file), kitty 0.25.2 (empty config file) and fish 3.5.0 with following minimal `config.fish`:

```fish
function tmux_attach
    tmux has-session -t remote
    and tmux attach-session -t remote
end

function tmux_new_session
    tmux new-session -s remote
end

function initialize_tmux
    set PPID (ps -p %self -o ppid="" | xargs)

    if ps -p $PPID | grep -q ssh
        tmux_attach
        or tmux_new_session
        and kill -15 %self
        or echo "tmux failed to start; using plain fish shell"
    end
end

test -t 0 && initialize_tmux
```

**To reproduce**
1. From local machine: `kitty +kitten ssh <server>`. 
 
Logs from tmux (`tmux kill-server; tmux -vv new`):
[tmux-logs.zip](https://github.com/tmux/tmux/files/8981761/tmux-logs.zip)

**Comment by nicm** [comment]
This is Kitty sending this stuff so you will need to talk to them about it.
