### ISSUE TITLE
Powerline is not working

### ISSUE THREAD

**Issue by jdelgadoalfonso** [tmux/tmux#324]
Actually, UTF8 extended characters are not appearing with the version 6c35d17. I guess that, either [26945d7](https://github.com/tmux/tmux/commit/26945d7956bf1f160fba72677082e1a9c6968e0c) or [e304673](https://github.com/tmux/tmux/commit/e304673c65d774bb76e5d55c095c8c8e6b05ff91) merge commit, are causing this bad behaviour.

**Comment by nicm** [comment]
What character? -vvvv logs?

**Comment by nicm** [comment]
Also tell me your platform, and show me output of "locale -a".

**Comment by jdelgadoalfonso** [comment]
Digging into the problem, I could find what was wrong. Just changing tmux.c:193 setlocale(LC_CTYPE, "en_US.UTF-8") by my system UTF-8 code, which is "en_GB.UTF-8", and then compiling again, fixes my issue. So, both must coincide.

My system is: Linux 4.4.3-1-ARCH #1 SMP PREEMPT Fri Feb 26 15:09:29 CET 2016; libevent 2.0.22-stable (epoll)

**Comment by jdelgadoalfonso** [comment]
This commit 1f0b317 fixes the issue for me.

Thanks so much @nicm
