### ISSUE TITLE
send-keys fails to send functional keys after F12 (F13, F14, and so on)

### ISSUE THREAD

**Issue by for-coursera** [tmux/tmux#3244]
### Issue description

`send-keys` fails to send the functional keys that go after F12 (F13, F14, and so on). Instead of the corresponding escape sequence, it just sends the literal string (like, `F13`, `F14`, and so on). 

Below is the log of `cat` and the three consecutive commands, `send-keys F12`, `send-keys Enter`, `send-keys F13`:

    $ cat
    ^[[24~
    
    F13

### Required information

* tmux version: `tmux next-3.4` (the latest master, d8c527a)
* Platform: `Linux x86_64`
* $TERM inside of tmux: `screen-256color`

**Comment by nicm** [comment]
tmux does not support these as keys, you need to specify which modifier you want (`S-F1`, `C-F1` etc).

**Comment by for-coursera** [comment]
I see. Thanks :)
