### ISSUE TITLE
Extended keys (CSI u) work outside but not inside of tmux

### ISSUE THREAD

**Issue by danijar** [tmux/tmux#3246]
### Issue description

I'm using iTerm2 with "CSU u" mode enabled from my MacBook to SSH into a remote Linux machine that runs zsh:
- Running `cat` and presssing <kbd>Ctrl</kbd>+<kbd>L</kbd> shows `^L`, which is correct.
- Running `cat` and presssing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd> shows `^[[76;5u`, which is correct.

But when I open tmux with `set -g extended-keys always` on the remote machine, the behavior changes:
- Running `cat` and presssing <kbd>Ctrl</kbd>+<kbd>L</kbd> shows `^L`, which is correct.
- Running `cat` and presssing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd> also shows `^L`, which I is incorrect (as far as I understand).

The reason I'm trying to get CSI u to work is to that later I can bind `C-l` and `C-S-l` to different commands in my tmux config.

### Required information

* tmux version (`tmux -V`): `tmux 3.2a`
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`): Inside `screen-256color` and outside `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): No logs

**Comment by nicm** [comment]
Logs?

**Comment by danijar** [comment]
Somehow I don't see any logs. When opening tmux, the terminal refreshes as if `clear` was called. I'm trying to figure out where this could be coming from.

**Comment by moritzdietz** [comment]
There should be text files in your working directory prefixed with `tmux-` after exiting.

**Comment by danijar** [comment]
Cool, I see. Here are the logs:

- [tmux-server-850802.log](https://github.com/tmux/tmux/files/9030780/tmux-server-850802.log)
- [tmux-out-850802.log](https://github.com/tmux/tmux/files/9030781/tmux-out-850802.log)
- [tmux-client-850800.log](https://github.com/tmux/tmux/files/9030782/tmux-client-850800.log)

And here is my [tmux config](https://github.com/danijar/dotfiles/blob/34302f93c887af5b061e0a8e3ac005ad72836792/home/.config/tmux/tmux.conf).

**Comment by nicm** [comment]
There is no evidence in this file of you pressing `C-S-l`:
````
1656697201.519170 /dev/pts/1: keys are 29 (\033[>0;95;0c\033P>|iTerm2 3.4.15\033\\)
1656697201.519245 /dev/pts/1: keys are 19 (\033P>|iTerm2 3.4.15\033\\)
1656697203.421510 /dev/pts/1: keys are 1 (i)
1656697203.588595 /dev/pts/1: keys are 1 (l)
1656697203.676754 /dev/pts/1: keys are 1 (s)
1656697203.696954 /dev/pts/1: keys are 1 ( )
1656697203.965239 /dev/pts/1: keys are 1 (t)
1656697204.093315 /dev/pts/1: keys are 1 (m)
1656697204.260453 /dev/pts/1: keys are 1 (u)
1656697204.317291 /dev/pts/1: keys are 1 (x)
1656697204.532808 /dev/pts/1: keys are 1 (-)
1656697204.996299 /dev/pts/1: keys are 1 (\r)
1656697205.636277 /dev/pts/1: keys are 1 (k)
1656697205.836639 /dev/pts/1: keys are 1 (a)
1656697205.957297 /dev/pts/1: keys are 1 (*)
1656697206.213179 /dev/pts/1: keys are 1 (\r)
1656697207.945234 /dev/pts/1: keys are 3 (\033[O)
1656697262.489000 /dev/pts/1: keys are 3 (\033[I)
1656697265.595575 /dev/pts/1: keys are 3 (\033[O)
1656697273.081633 /dev/pts/1: keys are 3 (\033[I)
1656697275.044766 /dev/pts/1: keys are 1 (/)
1656697275.483565 /dev/pts/1: keys are 1 (h)
1656697275.643468 /dev/pts/1: keys are 1 (t)
1656697275.754090 /dev/pts/1: keys are 1 (t)
1656697275.819801 /dev/pts/1: keys are 1 (p)
1656697275.907406 /dev/pts/1: keys are 1 (\r)
1656697276.747170 /dev/pts/1: keys are 1 (b)
1656697277.298562 /dev/pts/1: keys are 1 (\r)
1656697278.420095 /dev/pts/1: keys are 3 (\033[O)

**Comment by nicm** [comment]
It looks like you have not got the `extended-keys` option turned on.
