### ISSUE TITLE
ability to modify whole lines in `choose-tree` (again) and improve tree view

### ISSUE THREAD

**Issue by DJCrashdummy** [tmux/tmux#3248]
### Issue description

finally i have upgraded my most regularly used servers to more recent OS versions, so i tend to suffer more frequently from this inconvenience (because i mainly use tmux on servers via ssh), which i noticed quite some time ago but hoped it would change over time.

don't get me wrong, it's really cool what `choose-tree` has become since 2.6 and up, but the one thing that annoys me immensely is the fact that i can no more modify the **whole** lines to my likings.
yes i know, beside `-F` there is also the `-K` option which even allows to modify the shortcut keys... but i'm talking about the issue that since then the index number at the beginning of the line (after the tree) got hard coded. :disappointed:

a long story short: i used to have a pretty similar formatting in the `choose-tree` view for windows as in the status line and because i easily overlook the flags, i simply put them in front of the index.

a part of my tmux status line:
![tmux-status](https://user-images.githubusercontent.com/26110463/176988139-96183b9f-e4fc-45bb-8837-16a16a22da5b.png)

my choose-tree with tmux <2.6:
![tmux-choose](https://user-images.githubusercontent.com/26110463/176988166-d25166ec-4828-4792-a5fb-d7f8f9dd2790.png)

is this somehow possible to accomplish again?

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.3a`
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color` & `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by DJCrashdummy** [comment]
BTW: a suggestion, as i'm not a power user and this might also help some newbies...

how about reintroducing the `-S` & `-W` and adding a similar `-P` option to `choose-tree` (additionally to `-F`, to keep it in line with the other `choose-...` commands)?

this would make things much easier for casual users which only want to alter a small piece of information of e.g. the pane lines as they don't have to deal with and understand the whole multiple line long and complicated default value of `-F`.
for sure, if implemented, `-S`, `-W` and `-P` have to overrule the corresponding part in `-F` as soon as they are used which might get tricky to implement, but on the other hand it gets easier for users and ensures long term backwards compatibility (as soon as it is possible to edit the whole line again). :wink:

**Comment by DJCrashdummy** [comment]
if you are concerned about the indicator for collapsed/expanded items (`+`/`-`) that it may get "lost" or confuse the user because of the possibility of unusual variables resp. characters at the beginning of a line, let me suggest to include it into the tree itself, which makes more sense since it is used as a starting point for expanded items.

so it would become something like this: *(included them into a pretty similar to the current tree or made it a little bit more widespread, which looks better IMHO)*
```
 +─> SESSION1					 +─> SESSION1
 -─> SESSION2					 -─> SESSION2
 ├──> WINDOW1					 ├───> WINDOW1
 ├+─> WINDOW2					 ├─+─> WINDOW2
 └-─> WINDOW3					 └─-─> WINDOW3
  ├──> PANE1					   ├───> PANE1
  └──> PANE2					   └───> PANE2
```

or perhaps it may be also interesting to use double/thick lines to indicate items with sub-items or (additionally) items which are able to be expanded:
```
 +═> SESSION1					 +━> SESSION1
 -═> SESSION2					 -─> SESSION2
 ├───> WINDOW1					 ├───> WINDOW1
 ╞═+═> WINDOW2					 ┝━+━> WINDOW2
 ╘═-═> WINDOW3					 └─-─> WINDOW3
   ├──> PANE1					   ├──> PANE1
   └──> PANE2					   └──> PANE2
```

as you can tell, i really like the **widespread variant** and the **double lines** look more natural to me...
the first idea of using the double/thick lines was to make it easier distinguishable from the `-` in an expanded line (hence always indicating items with sub-items), but only (additionally) indicating a collapsed item may also be reasonable. :thinking:

**Comment by nicm** [comment]
We could probably roll the name into the text, although the tricky bit would be removing the `:` if the remainder of the text was empty.

I am happy enough with how the tree looks so I don't think we make other changes. I don't like the idea of hiding the `+` inside the line and it is not genarally a good idea to use double lines becuase they are not part of the ACS set so they are not available on all terminals.

I don't want to add any duplicate flags.
