### ISSUE TITLE
incorrect sort orders of `choose-tree` (and improvement of doc)

### ISSUE THREAD

**Issue by DJCrashdummy** [tmux/tmux#3249]
### Issue description

these are some other issues i noticed while playing around with `choose-tree`, manly because of #3242:
- [ ] IMHO the **previews** should use the **same sort order** as the list, even if `-r` is set.
on the left top of the previews it states correctly e.g. `(sort: time, reversed)`, but always shows the previews ascending according to their index.
- [x] if i create my panes not in a straight order, the list of `choose-tree` got the order  e.g. 1, 3, 4 and 2 at the bottom. :open_mouth: *...but on top of the previews it still states `(sort: index)`.*
yes, i've set `setw -g pane-base-index 1` and since there is no pendant for panes also `set -g renumber-windows on`, but it shouldn't mater at all in this situation. and no, i didn't even touch any other options of `choose-tree` than `-Z`.
- [x] **if** the default sort order changed - which i doubt because using `choose-tree -Z -O 'index'` didn't change anything - it should at least be mentioned either in the changelog or the man page.
~~unfortunately there is also not **mention**ed in the man page what the **default** of `-O` is resp. should be.~~
- [x] BTW: as it seems that `-O 'time'` is not about the creation timestamp, but rather something like time since executing the last command or since something in the pane/window/session was active, **mentioning what "time" it really is**, would be even more important.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.3a`
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color` & `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**EDIT:** added a 4th item to the list.

**Comment by nicm** [comment]
I changed to sort panes by index, should be in GitHub when it syncs up later today.

**Comment by DJCrashdummy** [comment]
well... IMHO it is pretty simple: **all** items at the list **and** the preview should use the same order (especially if specified by `-O`) and even respect `-r` if set. else the statement on the top left of the previews is more misleading and confusing than anything else.

---

about the man page: when it is not clear what the default value of a option is, i would simply put `(default)` beside the correct one in the text while listing all possible values. ...but i'm not sure what the common practice is at the man page. :shrug:
> -O specifies the initial sort field: one of 'index' (default), 'name' or 'time'.

and if this is done, this would imply, mentioning the default value lacks at a lot of other options.

---

- [ ] BTW: as it seems that `-O 'time'` is not about the creation timestamp, but rather something like time since executing the last command or since something in the pane/window/session was active, mentioning what "time" it really is, would be even more important.

**Comment by nicm** [comment]
I've changed the man page to mention what `time` applies to.

**Comment by DJCrashdummy** [comment]
> I think I prefer the previews to show the actual content and not reflect the sort order of the list.

sorry, i don't get what you mean in particular with "show the actual content"?
i never meant to change something in the preview! just the sorting order of the previews should match with the sorting order of the list (and with the one stated in their top left).

in case we are talking past each other, i'll add a screenshot to make things more clear: (it's exact the same for panes in the window preview)
![choose-tree preview](https://user-images.githubusercontent.com/26110463/177704762-d879eb81-f6b6-48cc-ad7b-94038775d5c4.png)


> I have moved away from mentioning defaults in the man page since they tend to get out of sync and are trivial to figure out yourself.

i'm ok with that... seems reasonable to me. :+1: *at other programs with which you actually manipulate files or the like, it's probably more important to have the default mentioned in the man page.*

> Although I don't feel particularly strongly about the sort order so if you or someone else wants to open a PR to change it, I will accept it.

unfortunately i'm not a dev, else i would attempt to match the preview sort order. :frowning_face:
