### ISSUE TITLE
refresh-client -A '%0:off' never causes tmux to stop reading pane

### ISSUE THREAD

**Issue by brads55** [tmux/tmux#3250]
Looking back at #2217, sending `refresh-client -A '%0:off'` in control mode (as the sole client) was supposed to cause tmux to stop reading from the pane in question (by disabling EV_READ), this however no longer happens. It seems like during some of the refactoring that happened, this was broken. (Apologies, I've only recently come back to this on a newer version and noticed this!)

It looks like what is happening is, in `control_pane_offset` where the off flag is ultimatly checked, when `CONTROL_PANE_OFF` is set, `off` is set to one as it should be, but this function then returns `NULL`. In `server_client_check_pane_buffer` where this function is called, we have:

```
int        off = 1, ...
.....
wpo = control_pane_offset(c, wp, &flag);
if (wpo == NULL) {
    off = 0;
    continue;
}
if (!flag)
    off = 0;
```

Here `off` gets set to 0 when `control_pane_offset` has returned `NULL`, which it always will when `CONTROL_PANE_OFF` has been set.

**Comment by nicm** [comment]
Does it fix it if you change that from `off = 0` to `off = flag`?

**Comment by brads55** [comment]
Yep, that does indeed fix it, thanks.

**Comment by nicm** [comment]
Actually, I think this is the right fix - I don't think we should be setting `off` to `1` again once it has gone to `0`:
````
--- server-client.c     30 May 2022 12:55:25 -0000      1.395
+++ server-client.c     6 Jul 2022 07:00:32 -0000
@@ -2221,7 +2221,8 @@ server_client_check_pane_buffer(struct w
                }
                wpo = control_pane_offset(c, wp, &flag);
                if (wpo == NULL) {
-                       off = 0;
+                       if (!flag)
+                               off = 0;
                        continue;
                }
                if (!flag)
````
Does this work as well?

**Comment by brads55** [comment]
That also works, yes.

**Comment by nicm** [comment]
Applied now - sorry for the delay. Thanks!
