### ISSUE TITLE
Tmux obliterates current line and pastes twice when I try to paste something

### ISSUE THREAD

**Issue by smerrill** [tmux/tmux#3252]
### Issue description

When I paste a string into tmux, it often (but not always; it seems to often work right after a new tmux session starts, but will stop working in a matter of hours) obliterates the current line I have typed and instead double-pastes the text in my clipboard, once not highlighted, and once highlighted. This is a huge interruption to my workflow. I have observed this behavior happen both on WSL in wsltty and on macOS under iTerm.

Example: I type `git checkout ` and then hit paste once, and this happens. 
![image](https://user-images.githubusercontent.com/156815/177605273-52e6ae07-ab33-479a-8781-707cbff4c96e.png)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
`tmux next-3.4` (built from e77e11ec6bad1207ab15ee0f148b6a084d9f091c)
* Platform (`uname -sp`).
`Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`).
Inside: `screen-256color`
Outside: `xterm`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
```
[server exited]
```

**Comment by nicm** [comment]
Logs?

**Comment by smerrill** [comment]
This still happens with current master (dc6bc0e95acc04cdf43e869294ecba897a11d850) but in this case it took a week for it to show up; I'm attempting to get logs, but it can take a long time

![image](https://user-images.githubusercontent.com/156815/179824605-1f6971e5-5aed-40ff-8d84-89ac3df4bebb.png)
