### ISSUE TITLE
problem with text

### ISSUE THREAD

**Issue by KydaZ** [tmux/tmux#3254]
### Issue description

Initially i installed tmux via pacman then i tried to compile it and in both cases the text has something wrong

![2022-07-07_23-42](https://user-images.githubusercontent.com/77192166/177877762-4dd3ed03-0277-4e7f-8e5b-8bc8e3ce88f0.png)

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.3a`
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`). inside: NOT READABLE - outside: `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
What is TERM inside tmux?

**Comment by KydaZ** [comment]
$TERM inside and outside of tmux (echo $TERM). inside: `screen-256color` - outside: `xterm-256color`

`locale`:
LANG=it_IT.UTF-8
LC_CTYPE="it_IT.UTF-8"
LC_NUMERIC="it_IT.UTF-8"
LC_TIME="it_IT.UTF-8"
LC_COLLATE="it_IT.UTF-8"
LC_MONETARY="it_IT.UTF-8"
LC_MESSAGES="it_IT.UTF-8"
LC_PAPER="it_IT.UTF-8"
LC_NAME="it_IT.UTF-8"
LC_ADDRESS="it_IT.UTF-8"
LC_TELEPHONE="it_IT.UTF-8"
LC_MEASUREMENT="it_IT.UTF-8"
LC_IDENTIFICATION="it_IT.UTF-8"
LC_ALL=

**Comment by nicm** [comment]
Looks like the program you are running inside tmux is turning on ACS (alternate character set). You will need to work out why it is doing that.
