### ISSUE TITLE
Weird tmux behavior when using modern watch command program

### ISSUE THREAD

**Issue by budimanjojo** [tmux/tmux#3256]
### Issue description

I can confirm this problem is happening in both [viddy](https://github.com/sachaos/viddy) and [hwatch](https://github.com/blacknon/hwatch/) with the latest kitty terminal.

To reproduce:
1. Create a new tmux-pane (vertical/horizontal doesn't matter)
2. Do something with `hwatch` or `viddy`, `viddy echo "hello"` will do.
3. Notice other  tmux-pane will behave like crazy, sometimes it resize itself following mouse movement, sometimes it goes into selection mode following mouse movement.

I recorded the behavior here: https://github.com/blacknon/hwatch/issues/51

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.3a`
* Platform (`uname -sp`): `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`). outside: `xterm-256color` inside: `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-398039.log](https://github.com/tmux/tmux/files/9076204/tmux-client-398039.log)
[tmux-out-398041.log](https://github.com/tmux/tmux/files/9076205/tmux-out-398041.log)
[tmux-server-398041.log](https://github.com/tmux/tmux/files/9076206/tmux-server-398041.log)

**Comment by budimanjojo** [comment]
Forgot something, it's happening only after kitty v0.25.0 onwards, I don't know if this is because of kitty or tmux, I haven't try in other terminal emulator.

**Comment by nicm** [comment]
Please see if you can reproduce in xterm.

**Comment by budimanjojo** [comment]
I can't get xterm to work with tmux keybindings, maybe because I haven't configure it.
But I just tested alacritty v0.9 and it doesn't happen with alacritty. So this means it's kitty related?

**Comment by nicm** [comment]
Sorry, GitHub lost my email reply (again)...

Yes, if you cannot reproduce in other terminals then this seems like an issue with Kitty's mouse handling.

**Comment by budimanjojo** [comment]
Thanks! I'll close this for now and probably will report there if I have time (i'm currently smooth sailing `wezterm` without this problem anyway).

**Comment by nicm** [comment]
Yes sounds like kitty's mouse support is strange. Does the mouse work OK in
tmux in alacritty?
