### ISSUE TITLE
How to create a detached emulated terminal larger than the console?

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#3257]
I want to run  a program letting in a very large terminal, possibly thousands of rows, non interactively but in an niteractive terminal as the program output depends on the terminal size.

I noticed that "new-session" has -x and -y options which led to believe that it was possible but after running the command below the 
size seems to be the size of my host terminal not the one I passed as argument

tmux new-session -x 600 -y 200 -d "tmux display -p '#{pane_top} #{window_width} #{pane_height} #{pane_width} #{pane_left}' > tmux_size"

**Comment by nicm** [comment]
https://man.openbsd.org/OpenBSD-current/man1/tmux.1#resize-window
