### ISSUE TITLE
Drag flag

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#326]
The change to the mouse drag behavior added in 54ea8f74ae4ae3 is great, but I can't see any way to distinguish between a `MouseUp` during a drag and a `MouseUp` that's part of a normal, non-drag click.

What do you think of setting a flag that we'd be able to check from inside a binding and then switch behavior accordingly? In my case, I'd like to configure `MouseUp` on drag to do nothing, but otherwise have `MouseUp` exit copy mode. Something like:

```
bind-key -t vi-copy MouseUp1Pane \
  if-shell -Ft= "#{drag_active}"  "send -t= Escape" ""
```

(Or something like that; it's obviously untested as there is no `drag_active` flag.)

**Comment by nicm** [comment]
Why not configure MouseDown to exit copy mode? You can't have MouseUp
without MouseDown.

**Comment by wincent** [comment]
The effect I'm trying to achieve here is:

- Click in copy mode to exit.
- Unless it's a drag, in which case you should stay in copy mode.

I often want to highlight things in copy mode (for example, while talking with a colleague), so I drag over a region to highlight it. I don't want that action to take me out of copy mode, because I may have scrolled and this will reset the scroll position, requiring me to scroll back up (possibly having to search as well).

On the other hand, I still do want a way to easily get out of copy mode. Right now I can use `Enter`, `C-c` or `Escape` for that, but it would be nice to be able to just click (ie. no drag) to do that as well, seeing as my hand may already be on the mouse.

**Comment by nicm** [comment]
Ok, but a format wouldn't help you, because you can't bind if-shell in the mode key tables.

We originally thought of using a new key (MouseXDragEnd), perhaps that would be better.

**Comment by nicm** [comment]
Try this [x.txt](https://github.com/tmux/tmux/files/178821/x.txt)

**Comment by nicm** [comment]
last was the wrong diff, try this one [x.txt](https://github.com/tmux/tmux/files/178824/x.txt)

and do, for example

tmux unbind -temacs-copy MouseDragEnd1Pane
tmux bind -temacs-copy MouseUp1Pane cancel

**Comment by wincent** [comment]
> try this one

Thanks. It works perfectly, based on my brief testing.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub at next sync. Thanks

**Comment by codybuell** [comment]
Hopefully a quick question that doesn't need a new issue.  I'm using the example listed above but would like to send what is selected to the clipboard.  Adding `bind-key -t vi-copy MouseDragEnd1Pane copy-pipe "pbcopy"` after the unbind does the trick, but it instantly goes out of copy mode.  Any way to keep it in copy mode until the MouseUp1Pane event?
