### ISSUE TITLE
hebrew characters display incorrectly with horizontal split window

### ISSUE THREAD

**Issue by wedaly** [tmux/tmux#3262]
### Issue description

Certain Hebrew characters output in the left pane appear "swapped" with characters in the right pane.

![Screenshot from 2022-07-16 12-04-55](https://user-images.githubusercontent.com/2948394/179368853-5d92105e-6078-4d60-9f67-e47f029af5d0.png)

Steps to reproduce:
1. In a new tmux window, split horizontally (`split-window -h`)
2. In the left pane, `cat left.txt` ([left.txt](https://github.com/tmux/tmux/files/9126423/left.txt))
3. In the right pane, `cat right.txt` ([right.txt](https://github.com/tmux/tmux/files/9126424/right.txt))

I have reproduced this issue on several platforms/terminal emulators:
* Linux Fedora 35, Gnome terminal Version 3.42.3 for GNOME 41 Using VTE version 0.66.2 +BIDI +GNUTLS +ICU +SYSTEMD
* Windows 11, Windows Terminal 1.12.10983.0
* macOS Terminal Version 2.11 (440)

The only terminals where I was *not* able to reproduce the issue were rxvt and alacritty:
* rxvt-unicode (urxvt) v9.26 - released: 2021-05-14
* alacritty 0.10.1

![Screenshot from 2022-07-16 12-05-41](https://user-images.githubusercontent.com/2948394/179369031-a7f34807-6deb-4ed0-aadd-e2b0de97d59a.png)

I suspect this is because rxvt and alacritty aren't handling bidi (can see that the characters שרה appear in reverse order in rxvt compared to gnome-terminal above)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
I've reproduce this issue on both v3.2a, as well as on tmux built from the master branch (commit  dc6bc0e95acc04cdf43e869294ecba897a11d850)

* Platform (`uname -sp`).
Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).
Inside: tmux
Outside: xterm-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-180143.log](https://github.com/tmux/tmux/files/9126431/tmux-client-180143.log)
[tmux-out-180145.log](https://github.com/tmux/tmux/files/9126432/tmux-out-180145.log)
[tmux-server-180145.log](https://github.com/tmux/tmux/files/9126433/tmux-server-180145.log)

**Comment by wedaly** [comment]
I see a few other issues that mention that tmux doesn't fully support bidi (https://github.com/tmux/tmux/issues/1936 and https://github.com/tmux/tmux/issues/2425), so completely understand if this is a known issue / out-of-scope. Thanks for maintaining such an awesome tool!

**Comment by nicm** [comment]
Did you try `set -as terminal-overrides ',xterm*:Bidi'` so that tmux sends isolates?

I don't plan to work on bidi any further in the near future.

**Comment by wedaly** [comment]
Adding `set -as terminal-overrides ',xterm*:Bidi'` to tmux.conf and restarting tmux fixes the issue for me. Seems like this is a duplicate of https://github.com/tmux/tmux/issues/2425 after all!

Thanks @nicm !
