### ISSUE TITLE
Question: configuring display-menu controls

### ISSUE THREAD

**Issue by ndsizeif** [tmux/tmux#3264]
Great work with the ```display-menu``` feature. I find the menu workflow 
preferable to assigning bindings everywhere. 

### Issue description 
I'm currently building a menu system and I had a few questions regarding
the implementation of display-menu controls before I dig too deep.

#### Question 
**Are vi keys enabled by default in menus? Is there a way for a user to disable?**

I noticed navigation using k and j for up and down worked immediately for me 
(which was convenient). This does preclude assigning k or j to a display-menu 
command key as it would trigger the command rather than navigate. Not an real
issue (just don't use them as commands) but I attempted disable them to see if 
another user might be able to.

```
set -g mode-keys emacs
set -g status-keys emacs
````
```sh
export EDITOR=nano
```
The functionality remained. I searched, but didn't see any other setting in
the manual that might impact the behavior.  Apologies if I missed it.

#### Another Question 
**Can the built in display-menu functions be assigned to arbitary keys?**

from the manual...
```
The following keys are also available:

Key	Function
Enter	Choose selected item
Up	Select previous item
Down	Select next item
q	Exit menu
```
These keys can also be set as a display-menu command key including
Up and Down (separately from k and j).  Is it possible to do this:
```
Key	Function
l	Choose selected item
k	Select previous item
j	Select next item
Q	Exit menu
```
Thank you for your time.

```
Linux unknown
tmux 3.3a
alacritty
```

**Comment by nicm** [comment]
If you use `j` or `k` or `Up` as a shortcut key it will take priority over navigation.

There is no way to customize the navigation keys and I don't see that as something we want to do.
