### ISSUE TITLE
select-pane no longer unzooms

### ISSUE THREAD

**Issue by TomasTomecek** [tmux/tmux#327]
I recently updated tmux to 2.1. Before that, I was able to do `select-pane -D` on a zoomed window and it would unzoom and move to a pane bellow. With 2.1 that is no longer possible, `select-pane -D` does nothing on a zoomed window. Is there a command to unzoom a pane so I can chain it with `select-pane`?

**Comment by nicm** [comment]
Use git master or resizep -Z

**Comment by TomasTomecek** [comment]
Found these two issues, should have search before creating this one: https://github.com/tmux/tmux/issues/314 https://github.com/tmux/tmux/issues/150

Thanks for help!
