### ISSUE TITLE
Is there a way to assign the name for a pane spawned via `split-window`? 

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#3270]
I like batch-opening splits (example use case: want to tail a bunch of logfiles that are being written to in parallel), e.g. 

    for file in *; do echo $file; tmux split -h "tail -f $file"; done

This works great. In particular the greatness of this is that the pane self-closes when the program closes. So using it with `tail` is very elegant, we can just SIGINT our way through to clear out these auto-opened panes. There is one missing piece here which is to be able to have the pane header show something related to the command or an otherwise predetermined name. Yes I can echo something at the beginning but that is not good for long running commands where it will fall off the history scrollback, and besides scrolling just to see that is annoying.

I was hoping that the -n flag could be used, but upon further inspection of manpage it seems like the use of -n in new-window is not the desired "Set pane name to string" but rather to specify a window name which if present just selects it instead of creating the window. And does not apply at all to the split functionality.

I would have expected at least the mechanism I use to make the pane title would do the trick. Here's my format: 

    setw -g pane-border-format ' "#{=/-100/…:pane_title}" [#(ps -p "$(pgrep -P #{pane_pid} | sed -z -e s/\\n/,/g -e s/.$//)" -o args= | sed -E "s/(.{30})(.{2,})(.{20})$/\1…\3/" | sed -z -e s/\\n/\;/g -e s/.$//)] ppid=#{pane_pid} pids=[#(pgrep -P "#{pane_pid}" | tr "\n" " ")]#{pane_current_path} #{?alternate_on,<Alt Mode> ,}'

This works for regular panes, the header looks like:

    ├── "Stevens-MacBook-Pro.local" [tail -f 100.64.0.58_10.42.0.129_log] ppid=92396 pids=[95318 ] /Users/slu/test

but in a scripted pane doing what should be the same tail command, the output is 

    ├── "Stevens-MacBook-Pro.local" [] ppid=91737 pids=[] /Users/slu/test

I know what the reason for this discrepancy is though: The command in the pane USUALLY is a shell, that is why my format looks up the ppid instead of pid, so I'll have to get creative and make this format even more elaborate than it already is. Meanwhile the question is, is this the right way to go about this?

**Comment by nicm** [comment]
I expect that your shell is normally setting the title and when you run `tail` in the pane like this, the shell is run noninteractively so it does not do this.

You can set the title yourself with `select-pane -T`.

**Comment by unphased** [comment]
Yes. Because it makes the most sense to allow the application or shell to control the pane title I tend to avoid overriding the title. But in this case `tail` won't attempt to set the title so it doesn't help, I think the suitable approach here would be to use `select-pane -T` to set the title in the command just prior to calling `tail`.
