### ISSUE TITLE
Tmux process is running, but not attachable

### ISSUE THREAD

**Issue by sina-rostami** [tmux/tmux#3271]
tmux session process is running on my server, but I can not attach to the session.

![image](https://user-images.githubusercontent.com/61062593/180155040-628b158a-b02c-43aa-8a1d-b42f708720bb.png)

tmux version : `tmux 3.2a`
Platform : `Linux x86_64`

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#tmux-says-no-sessions-when-i-try-to-attach-but-i-definitely-had-sessions

**Comment by sina-rostami** [comment]
Thanks!
