### ISSUE TITLE
Status Bar cannot get 24 bit color to work.

### ISSUE THREAD

**Issue by williamhCode** [tmux/tmux#3273]
### The Issue

I am trying to set my status bar to the exact color as my vim status bar, but it seems to be stuck on 256 colors.
My Config:
```
set -g allow-passthrough on
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g status-bg "#a1c281"
set -g status-fg black
```
<img width="681" alt="Screen Shot 2022-07-22 at 2 57 14 PM" src="https://user-images.githubusercontent.com/83525937/180381949-862bf5cf-fa1a-4bde-80bd-ec2d33520967.png">

The color went from #a1c281 to #a7c188.

### Info

Please provide the following information:

* tmux version = 3.3a
* macOS = 12.4
* iterm2 = 3.4.16
* $TERM = xterm-256color (both inside and outside tmux)
* Logs:
[tmux-client-40467.log](https://github.com/tmux/tmux/files/9165453/tmux-client-40467.log)
[tmux-server-40470.log](https://github.com/tmux/tmux/files/9165451/tmux-server-40470.log)
[tmux-out-40470.log](https://github.com/tmux/tmux/files/9165454/tmux-out-40470.log)

**Comment by nicm** [comment]
The colour you have set is the colour tmux is sending:
~~~~
1658473265.936776 /dev/ttys003: \033[48;2;161;194;129m
~~~~
161 = a1, 194 = c2, 129 = 81.

My guess is that iTerm2 or (more likely) macOS is playing silly buggers and changing the colour slightly.

I suggest you use script(1) or look at your vim configs to see exactly what vim is sending and make tmux use the same.

**Comment by williamhCode** [comment]
You are totally right! I went to the palette for onedark (the theme I'm using) and found that the green is #98c379. It matched perfectly. Changing the display option (digital color meter) from native values to sRGB/generic RGB also displays #98c379. It seems like the color profile changes the display color values.
