### ISSUE TITLE
Using OSC4 sequence changes bold color to bright one

### ISSUE THREAD

**Issue by tardypad** [tmux/tmux#3275]
OS: Arch Linux
tmux: 3.3a
terminal emulator: foot (TERM=foot outside, TERM=tmux-256color inside)

Here is an initial screenshot of all the configured colors when using bold and normal display
![screenshot_20220724121726](https://user-images.githubusercontent.com/6368493/180642634-e903e21f-c6c9-42b3-ba42-4109b5618a6c.png)

And after "changing" the colors via the OSC 4 sequence (actually using the same colors already defined as theme), here's the screenshot of the result
![screenshot_20220724121739](https://user-images.githubusercontent.com/6368493/180642637-ddc6410b-86ff-485b-8966-efb9c117a766.png)

So you can see that the colors (30-37)  have been modified for the bold display to use the "bright" (90-97) colors

Here are the attached logs:
[tmux-client-282325.log](https://github.com/tmux/tmux/files/9175573/tmux-client-282325.log)
[tmux-out-282327.log](https://github.com/tmux/tmux/files/9175575/tmux-out-282327.log)
[tmux-server-282327.log](https://github.com/tmux/tmux/files/9175576/tmux-server-282327.log)

Some extra things:
- to confirm that this issue comes from tmux, I've also tested this on foot itself without tmux and the issue is then not present
- I've also tested the background colors (SGR codes 40-47, 100-107) and there's no issue there too
- as is visible from the first screenshot, I do not have the foot `bold-text-in-bright` config enabled

**Comment by nicm** [comment]
Show me a single example `printf` with one colour that I can try inside and outside tmux and see the difference.

**Comment by tardypad** [comment]
For me I see a different behavior between inside and outside of tmux in my foot terminal.
And I just tested on kitty now and I see the same behavior difference.
So I find it weird that you only see a difference between terminals but not between inside/outside tmux.
I've tested using default tmux config but is it possible that there's some other config affecting the result?

Ultimately I want to use those sequences to switch the theme and having such color changes on bold text is quite annoying.
It seems a bug to me overall that applying the current theme via those sequences (or going back and forth between 2 themes) would result in any change.

I'm not sure how those sequences are handled between tmux and the terminal and thus where the issue lies.
I don't mind opening a report in the foot project but then I don't see an issue when using the feature there directly.

**Comment by nicm** [comment]
There is only one palette entry for bright colours so it seems some terminals choose to use it for both ANSI and aixterm bright colours and some only for aixterm. tmux follows xterm and does the former. Can you reproduce this problem with xterm?

**Comment by nicm** [comment]
If you *can* reproduce with xterm, then please give me a version of the script above that will show the problem.

**Comment by nicm** [comment]
This was originally not the case but it was changed to fix https://github.com/tmux/tmux/issues/954.

**Comment by nicm** [comment]
I don't see there is much to do here unless I am misunderstanding the problem. I don't know which way of doing this is better, and in that case it seems sensible to follow xterm. Any theme or program will need to account for both behaviours to work correctly on all terminals.

**Comment by tardypad** [comment]
I've been checking xterm and indeed I also see the same behavior inside and outside tmux.
And to me for xterm, the behavior is correct because it displays bold text using bright colors (and it doesn't seem to be possible to change this config). So it makes sense that the OSC4 sequence would modify the color of the bold text.

The difference is that in my terminal (and many other new ones) there is a setting to use the regular color on bold text (it's actually the default). In that case, the behavior becomes wrong.

I assume there's no way for tmux to retrieve from the terminal what is configured.
So I'm afraid the only way to have a correct behavior would be to introduce a new tmux config for it.
Is that something you would consider?

**Comment by nicm** [comment]
No, there is currently no way for tmux to know whether a terminal is going to treat SGR 1 as bright and bold or just as bold, although we could add a terminfo capability to say so.

I can't think of any reason anyone will care if two different terminals show bold and bright+bold for SGR 1, so I don't think we need to try and force one or the other (realistically we could only force the former). I don't think it will do any harm to have a capability to make OSC 4 work as expected.

You would need to add a new terminfo code (look at, for example, `Rect`/`TTYC_RECT`, I suggest something like `Nobr` for "no bright") and check it in the first block at the start of `tty_check_fg`.

**Comment by tardypad** [comment]
Thanks I'll give a shot at implementing it whenever I have time
