### ISSUE TITLE
improvement idea: set a custom pane-border-line character, have it in a variable

### ISSUE THREAD

**Issue by elig0n** [tmux/tmux#3276]
it would be nice to be able to access the current border line character from a variable so it can be used in panes' border-format as a filler between items, ie. for `simple`
`-- #1 -- (command) ----- (pane title)------------- (pid) --` 

or it would be even better if the pane border-format could be divided into areas like status' status-right, status-left and have the filler automatically adjust to it

Also to be able to set the border line character to any character could be a nice improvement for styling

**Comment by nicm** [comment]
I don't mind if someone adds a format variable for the border characters but I don't really feel like doing it myself.

You can use the `align` style to position the text.
