### ISSUE TITLE
Improvement idea: attaching to a session from within that session should automatically detach

### ISSUE THREAD

**Issue by rikongha** [tmux/tmux#3277]
### Issue description
attaching a session from within itself, causes tmux to get stuck in a loop and unable to force close or run any command, except, there's another access to a terminal to terminate the session or kill the server.
E.g:
`tmux new -s dev`
`tmux attach -t dev`

If a session is being attached from within itself, if possible, I think either it gets ignored or perhaps it should be executed in detached mode `tmux attach -dt dev`

### Required information
<img width="682" alt="Screenshot 2022-07-26 at 21 24 26" src="https://user-images.githubusercontent.com/43537915/181106243-e05a5ce4-1f0f-4347-90d1-3d3b9631eb68.png">

* tmux 3.2a.
* (Mac) Darwin arm.
* screen and xterm-256color

**Comment by nicm** [comment]
tmux warns about this case and I think that is enough.

If you want to change the session instead of attaching, use `switch-client`.
