### ISSUE TITLE
couldn't create directory /private/tmp/tmux-501 (Permission denied)

### ISSUE THREAD

**Issue by nippyin** [tmux/tmux#3278]
### Issue description

Installed tmux and trying to run but getting following error.

couldn't create directory /private/tmp/tmux-501 (Permission denied)

If I run with sudo tmux then it works

### Required information

Please provide the following information:

tmux 3.3a
Darwin i386
xterm-256color
➜  ~ tmux kill-server; tmux -vv new
couldn't create directory /private/tmp/tmux-501 (Permission denied)
couldn't create directory /private/tmp/tmux-501 (Permission denied)

**Comment by krader1961** [comment]
Darwin i386? Not x86_64? Did Apple ever ship a laptop or server that used a 32-bit Intel CPU? Such a system would be ancient and no longer supported. Regardless, have you done the obvious and run `ls -ld /private/tmp/tmux-501`? It seems likely you ran tmux from a shell running with euid == root (e.g., after running "sudo /bin/sh"). Simply remove that directory and you should be able to start tmux as a non-root user.

**Comment by nippyin** [comment]
Yes, I removed and tried but couldn't create directory under path in my original description.

The reason why I tried with root to check and that created the file which anyways I have deleted.

Issue still persists as normal user cannot run tmux.
________________________________

**Comment by krader1961** [comment]
Whatever is going on is specific to your system and is not a tmux bug. I've been using tmux on macOS for over a decade. What does `ls -ld /private/tmp` output? What happens if you run `mkdir /tmp/tmux-501`? I understand that English is not your native language but your comments are very confusing. For now it is probably best to ignore the `tmux` command and debug your problem using standard macOS/UNIX commands.

**Comment by krader1961** [comment]
@nippyin, Ping? Did you resolve this issue? if yes, what was the problem? If no, what happens when you run the commands in my previous comment?

**Comment by nippyin** [comment]
➜  ~ ls -ld /private/tmp
drwxrw-rw- root wheel 256 B Thu Jul 28 20:46:04 2022  /private/tmp

➜  ~ mkdir /tmp/tmux-501
mkdir: /tmp/tmux-501: Permission denied

Looks like the issue is with my /tmp permissions as group does not have write permission. 

➜  ~ ls -ld /tmp
lrwxr-xr-x root wheel 11 B Mon May  9 17:30:48 2022  /tmp ⇒ private/tmp

**Comment by krader1961** [comment]
Your `ls -ld /tmp` is showing the permissions of a symlink which isn't useful. You need to either add a trailing slash to force resolving the symlink or do `ls -ld /private/tmp`. These are the correct permissions for that directory (copied from my system):

```
drwxrwxrwt 10 root wheel 320 Jul 28 18:17 /private/tmp/
```

**Comment by nippyin** [comment]
Thank you very much @krader1961 its fixed, not sure though how come these permissions were changed.

**Comment by krader1961** [comment]
Me either but I had the same problem a couple of years ago. Presumably an OS upgrade screwed up the permissions since, as a UNIX programmer for four decades, I wouldn't have messed with those permissions.

P.S., You should close the issue.
