### ISSUE TITLE
Add `tmux capture-pane -J` option without the extra trailing space

### ISSUE THREAD

**Issue by cnst** [tmux/tmux#3279]
I use the `tmux capture-pane -pJ -S- -E- -t.0` snippet a lot, it's very useful in saving the output of the panes via email by piping it to `mutt`, or for using in shell scripts with `grep`, `sed`, `sort` and `uniq`, to find things of interest in an adjacent pane.  Thank you for such a great tool!

However, I've noticed that the [`-J` option of `capture-pane`](http://man.openbsd.org/tmux.1#capture-pane) adds a lot of extra trailing space that doesn't exist in the original output.  Is there any reason for this?  Is it related to some pseudo-terminal settings?  Is there any workaround?  It seems to happen on some machines, but not on others; right now it didn't happen on `tmux 3.3a` on one Chromebook, but did happen on `tmux 3.3` on another Chromebook, whereas the panes on both machines had the exact same script running (which does NOT print any trailing whitespace).  Sometimes the `wc` word count returns fewer lines and fewer characters once `-J` is added (this is 100% expected, because as the lines are joined, the extra `\n` characters are removed from the output, so both the number of lines, as well as the total character size, are decreased by the same number), other times on other machines, the lines are joined, but a LOT of extra phantom trailing space is added that wasn't supposed to have been there.

Is there any workaround, other than piping through `perl -pe's#[^\S\n]+$##g'`?  Is it too late to ask for `-J` to NOT add extra trailing space, since there's already `-N` for that now, since https://github.com/tmux/tmux/issues/422?  I guess a new option may be needed to preserve backwards compatibility?  Is there any other workaround to get rid of the trailing space that was never supposed to have been there?  For some output with average line length, the `-J` can effectively double the size of the output with so much extra phantom spaces being added.  Any reason why lines aren't joined automatically, without any extra options, and without the trailing whitespace?

**Comment by nicm** [comment]
Best add a new flag meaning join and trim (`-j`?).

**Comment by bfrg** [comment]
@cnst This was already changed in the following commit 2df7bc14fa.

**Comment by cnst** [comment]
Oh, wait, so the extra trailing space for each short line was a legit tmux bug, not a terminal thing?

Looks like this was fixed 2022-03-30 (in 3.3 and 3.3a), but the previous code was introduced 2017-09-10 (with tmux 2.7?), although I'm not quite sure that it's the same bug that I'm experiencing:

* https://cvsweb.allbsd.org/cvsweb.cgi/src/usr.bin/tmux/grid.c?cvsroot=openbsd#rev1.123 @ 2022-03-30
* https://cvsweb.allbsd.org/cvsweb.cgi/src/usr.bin/tmux/grid.c?cvsroot=openbsd#rev1.76 @ 2017-09-10

If the underlying 2x trailing space on each short line bug is fixed, and a random short-line output isn't 2x'ed all the time with the `-J`, then I'm fine without any extra options here, to have the original whitespace preserved!  Guess gotta upgrade the systems with the 2x'ed spaces to from 2.7+ to 3.3 or 3.3a?

**Comment by bfrg** [comment]
Yes, you're right it was changed in https://github.com/tmux/tmux/commit/ded695504faad8f5d6430731f0bcb9beb0e1430a on Mar 30, 2022. Not sure why there are two identical commits.
