### ISSUE TITLE
automatic-rename option stopped working

### ISSUE THREAD

**Issue by joshmedeski** [tmux/tmux#3280]
### Issue description

My windows don't get automatically renamed anymore. It happened recently but I can't figure out why.

```
set-option -wg automatic-rename on
```

<img width="1466" alt="Screen Shot 2022-07-28 at 10 44 21 AM" src="https://user-images.githubusercontent.com/2036594/181581735-ec57d4b8-85ba-4ef3-b60b-facba4718a2c.png">

I've removed all my custom config files and it still can not rename windows automatically. Any idea what's going on?

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.3a`
* Platform (`uname -sp`): `Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`): `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Do you have `allow-rename` set to on? If so, set it to off.

**Comment by joshmedeski** [comment]
I haven't explicitly changed that value, just allowed the default value.

**Comment by joshmedeski** [comment]
I was my `set-title` options not being set properly.
