### ISSUE TITLE
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 1 

### ISSUE THREAD

**Issue by Timemanagerplus** [tmux/tmux#3282]
### Issue description

When i do `source ~/.tmux.conf`, "'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned " was occupy.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 
* tmux 3.3a

* Platform (`uname -sp`).
* Linux x86_64
* 
* $TERM inside and outside of tmux (`echo $TERM`).
* all:  xterm-256color
* 
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by zhangjunpeng9354** [comment]
I faced the same problem while rebuilding my coding env, and finally find a temporal solution by replace "sh" with "bash". No similar problem was observed on my other 5 computers.

**Comment by Timemanagerplus** [comment]
but i am using csh,i change it to csh and it didn't work.

**Comment by krader1961** [comment]
@Timemanagerplus, I understand that English is not your primary language but your question makes no sense. Running `cut -c3- ~/.tmux.conf` simply deletes the first three characters of each line in the tmux config file. Which doesn't make any sense. A google search yielded this earlier issue: https://github.com/gpakosz/.tmux/issues/256. Which also doesn't make any sense. There were some other cryptic results such as https://www.pingzhou.site/?p=204. Where does the `_apply_configuration` script come from? What is its content? What is it intended to do? It seems like this is an example of "[cargo cult programming](https://en.wikipedia.org/wiki/Cargo_cult_programming)".

Also, setting `TERM` to `xterm-256color` inside a tmux session might work, depending on the tmux features you use, but doing so is wrong and likely to cause problems.

**Comment by nicm** [comment]
This is a problem in your config, you will need to work out what is wrong with your `.tmux.conf`.
