### ISSUE TITLE
new-window -c "#{pane_current_path}" doesn't work on Cygwin

### ISSUE THREAD

**Issue by alphaniner** [tmux/tmux#3283]
### Issue description
I'm running tmux on Cygwin 64-bit. OS is Windows 10 Pro.

When I open a new window by running `new-window -c "#{pane_current_path}"` from the tmux command prompt (or with custom keybinds in my .tmux.conf), the working directory in the new window is still `$HOME`.

Cygwin only provides tmux 3.2† but I built and installed tmux 3.3a and the issue persists.

Not sure what can be expected in the logs, but I ran the following outside of tmux:
```
$ tmux -Ltest kill-server
error connecting to /tmp/tmux-197609/test (No such file or directory)
$ tmux -vv -Ltest -f/dev/null new
```
Note: I get a similar error if I simply run `tmux kill-server` even if `/tmp/tmux-197609/default` exists. I don't know what to make of that, just thought I should mention it.

Inside tmux I ran `cd /`, then the `new-window` command, then closed both windows with CTRL-d.

† There is also a "test" package for tmux 3.2 built with a patch applied:
```
diff --git a/server-client.c b/server-client.c
index d3ffd68..7c213e7 100644
--- a/server-client.c
+++ b/server-client.c
@@ -2270,6 +2270,7 @@ server_client_dispatch_identify(struct client *c, struct imsg *imsg)

 #ifdef __CYGWIN__
        c->fd = open(c->ttyname, O_RDWR|O_NOCTTY);
+       c->out_fd = dup(c->fd);
 #endif

        if (c->flags & CLIENT_CONTROL)
```
but I tried that as well to no avail.

### Required information
```
tmux version     3.3a
Platform         CYGWIN_NT-10.0-19043 unknown
$TERM outside    xterm
$TERM inside     tmux-256color
```

## Logs
[tmux-client-2016.log](https://github.com/tmux/tmux/files/9220390/tmux-client-2016.log)
[tmux-out-2018.log](https://github.com/tmux/tmux/files/9220391/tmux-out-2018.log)
[tmux-server-2018.log](https://github.com/tmux/tmux/files/9220392/tmux-server-2018.log)

**Comment by nicm** [comment]
tmux is correctly getting the path as `/` so it seems likely your shell profile or something is changing to `$HOME`.

If you do:
~~~~
tmux set -g remain-on-exit on \; neww -c '#{pane_current_path}' -- /bin/pwd -L
~~~~
Then enter copy mode and scroll up, does it show the right directory?

**Comment by alphaniner** [comment]
I don't know if this is expected or not, but if I run that that outside of tmux and there's no active session I get the error:
```
error connecting to /tmp/tmux-197609/default (No such file or directory)
```
Even if `/tmp/tmux-197609/default` exists.

But to answer your actual question, when run from within tmux it _does_ show the right directory.

**Comment by nicm** [comment]
That means your shell is changing it.

**Comment by alphaniner** [comment]
Yeah, I was looking into that and just figured it out. The default /etc/profile contains:
```
if [ ! -z "${CHERE_INVOKING}" ]; then
  unset CHERE_INVOKING
else
  cd "${HOME}" || echo "WARNING: Failed attempt to cd into ${HOME}!"
fi
```
No idea what `CHERE_INVOKING` is all about, but when I commented out those lines for testing, `neww -c '#{pane_current_path}'` works as expected.

Now I just need to find a proper solution. Thanks!

**Comment by alphaniner** [comment]
Well, that 'solution' actually causes new windows to be opened in the `$PWD` of the shell from which tmux was launched if `-c` is _not_ passed.

But anyway it's still not a tmux issue so I shouldn't have reopened this.
