### ISSUE TITLE
update-environment accepts globs but only updates the first environment variable that's matched

### ISSUE THREAD

**Issue by SeerLite** [tmux/tmux#3284]
#### First issue
`update-environment` accepts globs, however it only updates the very first match instead of all of them (making it useless). Glob matching was implemented in issue #2397.

This is the relevant code from `environ.c`:
```c
/* Copy variables from a destination into a source environment. */
void
environ_update(struct options *oo, struct environ *src, struct environ *dst)
{
	struct environ_entry		*envent;
	struct options_entry		*o;
	struct options_array_item	*a;
	union options_value		*ov;

	o = options_get(oo, "update-environment");
	if (o == NULL)
		return;
	a = options_array_first(o);
	while (a != NULL) {
		ov = options_array_item_value(a);
		RB_FOREACH(envent, environ, src) {
			if (fnmatch(ov->string, envent->name, 0) == 0)
				break;
		}
		if (envent == NULL)
			environ_clear(dst, ov->string);
		else
			environ_set(dst, envent->name, 0, "%s", envent->value);
		a = options_array_next(a);
	}
}
```

The `break` statement breaks on the first matched environment variable. This is inherited from the original code where `update-environment` only matched exact strings, so it made sense to break on the first (and only) match. After the patch however it's incorrect as there can be multiple matches.

#### Steps to reproduce:
Config file:
```tmux
# example.tmux.conf
set-option -ag update-environment 'EXAMPLE_*'
```
Bash commands:
```bash
tmux -L example kill-server
tmux -L example -f example.tmux.conf new-session -d
export EXAMPLE_1=1 EXAMPLE_2=2 EXAMPLE_3=3
tmux -L example attach-session \; new-window
# Inside tmux now:
echo $EXAMPLE_1 $EXAMPLE_2 $EXAMPLE_3
```
Only `1` as output because only `EXAMPLE_1` was updated. 

I'm not sure what the best way to get the wanted behavior is, I don't have experience writing C.

#### Second issue
The fact that update-environment accepts globs is not documented anywhere in the man page.

### Required information

Please provide the following information:

* tmux version (`tmux -V`):
`tmux next-3.4`
(master: 9d9445a48e626731e9384b6b9cda367cd4cef5d3)
* Platform (`uname -sp`):
`Linux unknown`
(Guix System)
* $TERM inside and outside of tmux (`echo $TERM`):
Inside: `screen-256color`
Outside: `alacritty`
* Logs from tmux (`tmux kill-server; tmux -vv new`):
~~Not necessary~~

---

Thank you for writing and maintaining tmux <3

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/9240708/x.diff.txt)
