### ISSUE TITLE
feature request: tmux cmdline in FORMATS

### ISSUE THREAD

**Issue by mosajjal** [tmux/tmux#3285]
* tmux version: tmux next-3.4
* Platform: Linux 
* $TERM inside and outside of tmux: bash 

currently, there's `pid` as a variable name inside FORMATS, but there's no easy way to get the original `tmux` command. For example, if `tmux` has been renamed to `tmux2`, or `tmux` is not in `$PATH`,  the following won't work:

`"bind-key -n M-3 if-shell 'tmux select-window -t 3' '' 'new-window -t 3'"`

I can workaround that in Linux by running this:

`"bind-key -n M-1 if-shell '$(cat /proc/#{pid}/cmdline) select-window -t 3' '' 'new-window -t 3'"`

it'd be good to have a builtin variable to return the command line running `tmux` so it can be reused in shell commands. Ideally, there would be a variable like `#{cmdline}` so I don't have to rely on hacky workarounds.

**Comment by nicm** [comment]
tmux does not know the location of its own binary and there is no portable way for it to find it out.
