### ISSUE TITLE
Regression: DCS passthrough does not work since 3.3a (or earlier)

### ISSUE THREAD

**Issue by JasonXJ** [tmux/tmux#3287]
### Issue description

On a terminal emulator (e.g. alacritty) supporting the OSC52 copy command, running this command inside tmux should put string 'mouse' into the clipboard: `echo -e '\x1bPtmux;\x1b\x1b]52;c;bW91c2U=\x07\x1b\\'`. This works in tmux 3.2a, but not in 3.3a or ToT. It seems that tmux does not process the DCS passthrough sequence `\x1bPtmux;\x1b...\x1b\\`. Normally, it should process it and passthrough the wrapped content (i.e. `\x1b]52;c;bW91c2U=\x07`)

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 3.3a or ToT
* Platform (`uname -sp`): linux debian
* $TERM inside and outside of tmux (`echo $TERM`): in: tmux-256color, out: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`): I am not sure where to find the log.

**Comment by nicm** [comment]
The passthrough escape sequence is now controlled by an option (allow-passthrough).

**Comment by JasonXJ** [comment]
Thanks! Putting `set -g allow-passthrough on` in my tmux config fixes it for me :)
