### ISSUE TITLE
-T UTF-8 has no effect

### ISSUE THREAD

**Issue by xiaq** [tmux/tmux#3288]
### Issue description

According to the manpage:

```
     -u            Write UTF-8 output to the terminal even if the first environment variable
                   of LC_ALL, LC_CTYPE, or LANG that is set does not contain "UTF-8" or
                   "UTF8".  This is equivalent to -T UTF-8.
```

However, they don't seem to be equivalent: `-u` works as intended whereas `-T UTF-8` seems to have no effect.

Reproduction:

*   Run the following in a Unicode-capable terminal:

    ```sh
    env -i PATH=$PATH TERM=xterm tmux -S ./tmux.sock -f /dev/null -u new-session cat
    ```

    And paste some Unicode text (try `文字`). This will echo the Unicode text as expected.

*   Replace the `-u` flag with `-T UTF-8` and paste the same Unicode text, it gets echoed as underscores instead.

### Required information

* tmux version (`tmux -V`): 3.3a
* Platform (`uname -sp`): Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`): xterm (not actually relevant)
* Logs from tmux (`tmux kill-server; tmux -vv new`): https://gist.github.com/xiaq/abc9eed2bd6e5db9ac5a44c62c2880c4 https://gist.github.com/xiaq/3f690f90b1df422424ee3a08ff04f732

**Comment by nicm** [comment]
I think this is an error in the man page. Originally I had added UTF-8 as a feature so you could add it with `-TUTF-8`, but it turned out not to fit well so I removed it. I have removed this text. Thanks!
