### ISSUE TITLE
Line Wrapping Disable Feature

### ISSUE THREAD

**Issue by herryliu** [tmux/tmux#3289]
I think the line wrapping disable feature is extremely useful for me since I logon to different type devices (not only the Linux box, such as router/switch/firewalls) which are much less flexible to deal with line length. So, the option to simply be able to turn off the line wrapping (without being able to scroll to the right) will be very useful. Not sure if that is a difficult task.

The following was the old request in the past. I am pretty sure lots of users like me would love it. I don't want to go back to "screen" just because of that.

https://github.com/tmux/tmux/issues/1784

**Comment by nicm** [comment]
This is already on the todo list. In the meantime, you can still do `printf '\033[?7l'` or use `cut` or one of the other programs that do this.

**Comment by herryliu** [comment]
printf '\033[?7l'  only works when you are in a linux shell. If I am on a router/firewall, I can't execute that.

Where can I find the "todo list"?

**Comment by herryliu** [comment]
In the tmux man page, it mentioned "wrap_flag --> Pane wrap flag". Can I set/clear this flag to achieve wrap/unwrap the lines?

**Comment by nicm** [comment]
No that is a variable to show if the flag is set or clear.
