### ISSUE TITLE
Readline key-bindgins in the search prompt

### ISSUE THREAD

**Issue by netei** [tmux/tmux#329]
When running a command with tmux (`C-b :`) then press "foobar" then press `C-w` , this deletes the last word (which is readline or a readline like implementation).

When searching in a buffer (`C-b [`) , then pressing "foobar", the `C-w` doesn't work (eg nothing happens).

Would you be interested in adding readline bindings in the search prompt ?

**Comment by ThomasAdam** [comment]
Better to use libedit.

**Comment by nicm** [comment]
We can hardly use readline because it is GPL. But libedit won't work either, you need to add the bindings yourself the same way we do for the command prompt.

**Comment by netei** [comment]
> you need to add the bindings yourself the same way we do for the command prompt. 

How would you do that ?

**Comment by nicm** [comment]
Look at the code in status.c status_prompt_key.
