### ISSUE TITLE
Can't compile static tmux 3.3a with ncurses 6.3 and libevent-2.1.12

### ISSUE THREAD

**Issue by klmr** [tmux/tmux#3290]
### Issue description

I'm attempting to build an isolated, static tmux in a Linux environment without suitable libevent/ncurses. The static tmux build fails (whereas a dynamic build succeeds!) with "error: conflicting types for ‘forkpty’" in `compat.h`.

This seems similar (but not identical) to #1729 and #2274 but the resolutions there don't help me, unfortunately.

Here's my build process:

```bash
# build libevent:
cd libevent-2.1.12-stable
./configure --prefix=$HOME/.local/opt/libevent/2.1.12-stable --enable-shared --enable-static
make -j
make install

# build ncurses
mkdir -p  ~/.local/opt/ncurses/6.3/lib/pkgconfig
cd ../ncurses-6.3
./configure --prefix=$HOME/.local/opt/ncurses/6.3 --with-shared --with-termlib --enable-pc-files --with-pkg-config-libdir=$HOME/.local/opt/ncurses/6.3/lib/pkgconfig --enable-static
make -j
make install

# build tmux
cd ../tmux-3.3a
PKG_CONFIG_PATH=~/.local/opt/ncurses/6.3/lib/pkgconfig:~/.local/opt/libevent/2.1.12-stable/lib/pkgconfig ./configure --prefix=$HOME/.local/opt/tmux/3.3a --enable-static
make
```

This yields the following error message:

> ```
> depbase=`echo alerts.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
> gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"3.3a\" -DPACKAGE_STRING=\"tmux\ 3.3a\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"3.3a\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_EVENT2_EVENT_H=1 -DHAVE_NCURSES_H=1 -DHAVE_PR_SET_NAME=1 -DHAVE_SO_PEERCRED=1 -DHAVE_PROC_PID=1 -I.  -> D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/home/rudolpk2/.local/opt/ncurses/6.3/include/ncurses -I/home/rudolpk2/.local/opt/ncurses/6.3/include  -I/home/rudolpk2/.local/opt/libevent/2.1.12-stable/include -DTMUX_VERSION='"3.3a"' -DTMUX_CONF='"/etc/tmux.conf:~/.tmux.conf:$XDG_CONFIG_HOME/tmux/tmux.conf:~/.config/tmux/tmux.conf"' -DTMUX_TERM='"screen"'  -iquote.       -std=gnu99 -O2     -MT alerts.o -MD -MP -MF $depbase.Tpo -c -o alerts.o alerts.c &&\
> mv -f $depbase.Tpo $depbase.Po
> In file included from tmux.h:34,
>                  from alerts.c:23:
> compat.h:379:9: error: conflicting types for ‘forkpty’
>  pid_t   forkpty(int *, char *, struct termios *, struct winsize *);
>          ^~~~~~~
> In file included from compat.h:162,
>                  from tmux.h:34,
>                  from alerts.c:23:
> /usr/include/pty.h:42:12: note: previous declaration of ‘forkpty’ was here
>  extern int forkpty (int *__amaster, char *__name,
>             ^~~~~~~
> make: *** [Makefile:900: alerts.o] Error 1
> ```

In fact, the `configure` step fails to find `forkpty`:

> ```
> checking for library containing fdforkpty... no
> checking for library containing forkpty... no
> ```

I've attached the [`config.log` file](https://github.com/tmux/tmux/files/9267622/config.log).

For completeness, I ran `pkg-config -libs` for `ncurses` and `tinfo` using the same `PKG_CONFIG_PATH` that I used to configure `tmux`, and the results seem ok to me:

```
$ pkg-config -static -libs ncurses
-L/home/rudolpk2/.local/opt/ncurses/6.3/lib -lncurses -ltinfo

$ pkg-config -static -libs tinfo
-L/home/rudolpk2/.local/opt/ncurses/6.3/lib -ltinfo
```

When configuring tmux without `--enable-static`, it finds `forkpty`:

> ```
> checking for library containing fdforkpty... no
> checking for library containing forkpty... -lutil
> ```

... and subsequent compilation succeeds. However, I would like to avoid having to set `LD_LIBRARY_PATH` when running tmux.

### System information

```
$ uname -sp
Linux x86_64

$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterprise
Description:    Red Hat Enterprise Linux release 8.2 (Ootpa)
Release:        8.2
Codename:       Ootpa
```

**Comment by nicm** [comment]
Look in config.log, most likely this means it failed to detect forkpty
because the compiler couldn't build the test program.

**Comment by klmr** [comment]
@nicm Indeed, that's the reason, but I don't understand how that happens, that's why I attached the `config.log`. In particular, I am getting the errors

> ```
> /usr/bin/ld: cannot find -lutil
> /usr/bin/ld: cannot find -lc
> ```

And that makes no sense to me.

**Comment by nicm** [comment]
Do you have a static libc installed?

**Comment by klmr** [comment]
😮 That’s exactly right, `libc.a` is missing. Time to check in why my sysadmins.
