### ISSUE TITLE
Session name introspection from session-{created,renamed,closed} hooks

### ISSUE THREAD

**Issue by acr4** [tmux/tmux#3292]
Is it possible to get the name of the session that was just created/closed from inside the `session-created` and `session-closed` hooks?

Similarly, it is possible to detect the old/from and new/to name of a session inside the `session-renamed` hook?

**Comment by nicm** [comment]
hook_session etc?

**Comment by acr4** [comment]
Ahh, I missed those.  Thank you.  Those variables all return nothing/empty when queried in my current experiment, but let me play with this some more before asking more questions.

**Comment by acr4** [comment]
OK I've got it figured out now.  Here's what I was trying to do:

`set-hook -g session-created "run-shell /my/hook/scripts/session-created"`

Then in `/my/hook/scripts/session-created` I was trying to divine the session name with:

`tmux display -p "#{hook_session_name}"`

But that never returned anything.  Instead what I need to do is pass the variable into the executable script's ARGV when the variable is still within the "hook is being executed" scope with:

`set-hook -g session-created "run-shell \"/my/hook/scripts/session-created #{hook_session_name}\""`
