### ISSUE TITLE
Max & min operators

### ISSUE THREAD

**Issue by delameter** [tmux/tmux#3293]
### Issue description

That's not actually an issue, more like the idea or proposal.

It's really challenging to simulate max/min functionality using current tmux version. For example, when I (or anyone else with similar necessity) need to apply a condition "result must be more or equal to 0", I have to write some monstrosity like this:

```
#{s|-[0-9]+|1|:#{e|-:#{window_width},#{w:#{E:@status_tabs}}}}
```

i.e. compute the value and replace the negative ones with 1 using regular expressions.

Implementing the min and max opeartors would be really helpful and great, the syntax might be like:

```
#{e|^:<val1>,<val2>}
#{e|v:<val1>,<val2>}
```

or

```
#{e|!+:<val1>,<val2>}
#{e|!-:<val1>,<val2>}
```

Implementation of these operators could simplify for example creating dynamic status bars which change set of fields inside depending on current window width (that's my case).

Thanks.

### Required information

* tmux next-3.4

**Comment by nicm** [comment]
This should be very easy to do, look at the existing operators in format.c. I don't like ^ and v; !+ and !- would be OK but I'm not sure if two letter operators will work so maybe something else like H and L for highest and lowest.

**Comment by nicm** [comment]
You can always just use >= to compare with zero...

**Comment by delameter** [comment]
> You can always just use >= to compare with zero...

yeah, but then i will have to count the length twice -- first in condition, seconds in "true"-branch:

```
#{?#{>=:#{<value>},0},<value>,0}
```

which I guess is suboptimal, especially when it's something like window status bar which loops over all windows

**Comment by delameter** [comment]
> This should be very easy to do, look at the existing operators in format.c. I don't like ^ and v; !+ and !- would be OK or maybe something else like H and L for highest and lowest.

Thanks, will look
