### ISSUE TITLE
is there a difference of environment in tmux-popup?

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#3294]
I have $MANPAGER pointing to vim

in tmux , interactive bash, running: man '$PWD/config/ftl/etc/man/ftl.1' works as expected

when runing: tmux popup -h90% -w90% -E "man '$PWD/config/ftl/etc/man/ftl.1'", the man page is displayed in vim but with spellchecking on.

the only difference is the call to tmux popup. Could it be an environment difference? tried to google the problem vim side to no end.

**Comment by pl643** [comment]
I think your issue might be that popup uses the same directory that tmux was started from, not from the directory you are running it.  If you need to use relative pathing, try using the -d popup option.  The following worked for me while inside a neovim:  :!tmux popup -d $(pwd) -E ...
