### ISSUE TITLE
wslvar and wslpath do not work in tmux

### ISSUE THREAD

**Issue by tan-wei-xin-alez** [tmux/tmux#3295]
### Issue description

1. Running `wslvar -S` within tmux yields no output whereas running the same command in bash 5.1.12 on WSL2 yields output e.g.
```
Name                           Value                                                                                   
----                           -----                                                                                   
ALLUSERSPROFILE                C:\ProgramData                                                                          
...                   
windir                         C:\Windows                                                                              
ZES_ENABLE_SYSMAN              1
```

2. Running `wslpath -w "${HOME}"` within tmux returns `wslpath: /home/<username>: Invalid argument` whereas running the same command in bash 5.1.12 on WSL2 returns `\\wsl$\<distro_name>\home\<username>`

### Required information

Please provide the following information:

* tmux 3.3a [newly installed without config]
* Linux x86_64 [Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220)]
* xterm-256color
* [tmux-client-8263.log](https://github.com/tmux/tmux/files/9290260/tmux-client-8263.log)
* [tmux-out-8265.log](https://github.com/tmux/tmux/files/9290261/tmux-out-8265.log)
* [tmux-server-8265.log](https://github.com/tmux/tmux/files/9290262/tmux-server-8265.log)

**Comment by nicm** [comment]
What do the WSL developers say?

**Comment by tan-wei-xin-alez** [comment]
> What do the WSL developers say?

Oh I don't actually know, should I open an issue on their side? I was under the assumption that since it works fine in bash on WSL2 but not in tmux that it's a problem specific to tmux

**Comment by nicm** [comment]
It is probably an issue with the tools but without knowing how they work I can't say for sure, but you are better asking the WSL developers.

**Comment by tan-wei-xin-alez** [comment]
For anyone in the future who's interested, a bug report has been filed at https://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=1591
