### ISSUE TITLE
using mouse to resize pane with `MouseDrag1Pane` doesn't work

### ISSUE THREAD

**Issue by YAMLcase** [tmux/tmux#3296]
Trying to resize the pane when dragging inside doesn't seem to work.  Here's the command I'm using:
```
bind-key -T root MouseDrag1Pane resize-pane -M
```

I want to have this as a supplement to `MouseDrag1Border` for a different feeling, like sliding sheets of paper instead of resizing borders.

**Comment by nicm** [comment]
No, because it uses the border to work out which pane you are resizing and by how much. You could try doing some surgery to `cmd_resize_pane_mouse_update` to see if you could make it work.

**Comment by YAMLcase** [comment]
> You could try doing some surgery to `cmd_resize_pane_mouse_update` to see if you could make it work.

Thanks for the suggestion, probably better than my hacky attempt so far:

I started going down the path of calculating differences in `mouse_x` and `mouse_y` and feeding those into `resize_pane -[UDLR]` but got stuck on how to store the previous coordinates.   This might also be a little too much cpu time used to keep the UX seamless.
