### ISSUE TITLE
[Question] Issue while trying to copy text in copy mode

### ISSUE THREAD

**Issue by GTP95** [tmux/tmux#3299]
### Issue description
Greetings,
I have a tmux window with two panes slitted vertically and I'm trying to copy some text from one of the two panes. According to the docs, I should first enter copy mode with `ctrl-b-[`, then navigate to the text that I want to copy (I'm using the arrows for this) and begin the selection with `spacebar`. But when I hit the spacebar, the cursor jumps baack to the last line of my terminal. What should I do or where should I look to fix this issue?

Thank you for your help,

GTP

### Required information

* tmux version: 3.0a
* Platform: Linux x86_64
* $TERM inside of tmux: screen

**Comment by nicm** [comment]
What docs? With emacs keys it is C-Space.
