### ISSUE TITLE
pane_current_path doesn't agree with pane's PWD

### ISSUE THREAD

**Issue by mfarrugi** [tmux/tmux#33]
With the following settings, new panes appear to open in `pwd -P` instead of `pwd`. This is somewhat unintuitive (and annoying to hack around).

```
# Ubuntu 9.10

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
```

Current pane pwd: `~/dots`
`<split-window>`
New Pane:`/net/host/user/me/dots`

**Comment by nicm** [comment]
Logical cwd is a shell construct and tmux has no access to it

**Comment by mfarrugi** [comment]
Ah I see. 

I'm not proficient enough in C to know/check this myself, but is getenv("PWD") too unstable to use for this? Or would it still refer to the server process in this context?

**Comment by nicm** [comment]
tmux has no access to environment variables from the child processes either.
