### ISSUE TITLE
Columns of text does not show in Tmux

### ISSUE THREAD

**Issue by honeyfairy** [tmux/tmux#330]
I came across this issue while using Empire Powershell in TMUX.
When listing 2 columns of text, only the last column displays.
The same does not happen in a standard Terminal or while using Screen.

Reference Images:
First image: Running Empire in Tmux, shows only last column of text
Second Image: Running Empire in Screen, showing both columns of text. 
![tmux](https://cloud.githubusercontent.com/assets/17691989/13729532/2428df10-e948-11e5-841a-d15b8ca648a4.PNG)
![screen](https://cloud.githubusercontent.com/assets/17691989/13729533/2504db78-e948-11e5-859f-70bb5dec079d.PNG)

**Comment by nicm** [comment]
Are you sure lines are actually missing and your application isn't just choosing to use only one column in tmux?

**Comment by honeyfairy** [comment]
Yes, I am sure, the screenshots will show that only the last column shows, notice where it starts.

I have noticed this issue arises only when using more than one pane.
And it happens randomly in screen too.

**Comment by nicm** [comment]
The screenshots don't show that at all really, it looks to me that the application just decided to use 1 column instead of 2.

Please run the application identically in script(1) inside and outside tmux and send me both transcript files. Completely outside tmux, not in screen.

**Comment by honeyfairy** [comment]
I see that it also just displays the last part of the list, as you can see in the screenshot below:

![tumux 3](https://cloud.githubusercontent.com/assets/17691989/13901530/fc395742-ee37-11e5-9d7c-b9483a0d6b0e.PNG)

**Comment by nicm** [comment]
Screenshots are not useful, show me the files I asked for please.

**Comment by honeyfairy** [comment]
Thanks for the help, please find attached the files requested. (my first time doing a typescript, hope its right!) :)

**Comment by nicm** [comment]
No, this is not right. I need to see what the application is sending to
tmux, so I need two files, one where you run script and the application
inside tmux and one where you run script and the application outside
tmux. Do not run tmux in script.
