### ISSUE TITLE
[Feature]: Fully override foreground 

### ISSUE THREAD

**Issue by tristone13th** [tmux/tmux#3303]
![image](https://user-images.githubusercontent.com/17382962/184810267-54c36533-33e8-4809-9e32-0a87e3744059.png)

My tmux is running inside a floaterm in Neovim, and I use the starship as the prompt. I have set the foreground to #888888 if the pane is inactive by following the code in tmux.conf:
```
set -g window-style 'fg=#888888,bg=#131313'
```
But as you can see, the prompt still has color and doesn't turn to grey, it seems maybe the prompt color is not fully overridden. Can we specify an option to entirely override it and turn the foreground of the entire inactive pane into grey?

**Comment by nicm** [comment]
You can only choose the default foreground and background. If you want to replace other colours the application chose to use, you will need to modify the palette (`whindow-palette` option).

**Comment by tristone13th** [comment]
> You can only choose the default foreground and background. If you want to replace other colours the application chose to use, you will need to modify the palette (`whindow-palette` option).

I didn't find any documentation related to this, could you show me a code example?

**Comment by nicm** [comment]
Sorry the option is actually `pane-colours`...
