### ISSUE TITLE
[ HELP ] Activity Monitor Message Change

### ISSUE THREAD

**Issue by dhaneshsivasamy07** [tmux/tmux#3304]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). ==> `tmux 3.3a`
* Platform (`uname -sp`). ==> `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`). ==> `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

##############################################
# Issue
---

Is there any configurations that I could tweak to make tmux to show visual alter of `Activity on <WindowName>` instead of `Activity on window 0` / `Activity on window 1` ?

**Comment by nicm** [comment]
No, you cannot change the message at the moment. I don't mind changing the default message to include the window name, try this: [x.diff.txt](https://github.com/tmux/tmux/files/9349996/x.diff.txt)
