### ISSUE TITLE
Shift-PageUp broken on rxvt-unicode

### ISSUE THREAD

**Issue by hermanni-xlnx** [tmux/tmux#3305]
### Issue description

After commit 616bde08ac74d4be0ae06087aa3103df54833f86 I can't bind S-PgUp anymore.

I have `bind-key -n S-PgUp copy-mode -eu` and the above commit breaks it. I've tested this using both rxvt-unicode and Konsole.

I'm sure there are some good runes to make this work, but as this breaks existing functionality it should be better documented. For now, I am just using

```diff
diff --git a/tty-keys.c b/tty-keys.c
index bb9ec231..e17b62f3 100644
--- a/tty-keys.c
+++ b/tty-keys.c
@@ -201,6 +201,9 @@ static const struct tty_default_key_raw tty_default_raw_keys
        { "\033[23@", KEYC_F11|KEYC_CTRL|KEYC_SHIFT },
        { "\033[24@", KEYC_F12|KEYC_CTRL|KEYC_SHIFT },
 
+       { "\033[6$", KEYC_NPAGE|KEYC_SHIFT },
+       { "\033[5$", KEYC_PPAGE|KEYC_SHIFT },
+
        /* Focus tracking. */
        { "\033[I", KEYC_FOCUS_IN },
        { "\033[O", KEYC_FOCUS_OUT },
```

### Required information

* tmux version: git commit 9c34aad2 ("tmux next-3.4")
* Platform: Linux x86_64
* $TERM inside tmux: tmux-256color
* $TERM outside tmux: xterm-color

**Comment by hermanni-xlnx** [comment]
[tmux-server-25885.log](https://github.com/tmux/tmux/files/9374492/tmux-server-25885.log)
[tmux-out-25885.log](https://github.com/tmux/tmux/files/9374494/tmux-out-25885.log)
[tmux-client-25883.log](https://github.com/tmux/tmux/files/9374496/tmux-client-25883.log)

**Comment by nicm** [comment]
The reason I deleted these is because they are redundant with the `rxvt-unicode` terminfo entry which correctly has `kNXT=\E[6$` and `kPRV=\E[5$`.

For some reason you are using `TERM=xterm-color` which doesn't have these at all, but even if you used `xterm` or `xterm-256color`, the sequences for xterm would be `kNXT6=\E[6;6~` and `kPRV6=\E[5;6~`.

In short, it seems like you need to set `TERM` to something more suitable for your terminal...

**Comment by nicm** [comment]
Actually, tmux doesn't check `kNXT`/`kPRV` anymore, that seems like an error...

**Comment by nicm** [comment]
Sorry, it does check it, got confused cos it is called kNXT2. So you should be able to change `TERM` to `rxvt-unicode` for rxvt-unicode or `xterm`/`xterm-256color` for Konsole and it should work.

**Comment by hermanni-xlnx** [comment]
Ok, I can confirm setting `TERM=rxvt-unicode` works. I guess using an ancient Ubuntu and selectively building new software is not a wise thing to do...

I'll close this as a stupid user error.
