### ISSUE TITLE
Sending Enter to own pane doesn't work

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#3306]
#!/bin/bash
pane_id=$(tmux display -p "#{pane_id}")
#pane_id="%146" # set to send to other pane

echo "pane_id: $pane_id"

tmux send -t "$pane_id" "ls" Enter
sleep 1 ;
tmux send -t "$pane_id" "ls" Enter
sleep 1 ;
tmux send -t "$pane_id" "ls" Enter

code above works when sending to other pane, sleep is needed but can be quite short.

when sending to own pane, even with long sleep, no ls command is send and display looks like a tab was send, IE: commands starting with ls are listed

* tmux 3.2a
* linux

**Comment by nicm** [comment]
Works for me, seems most likely your shell is clearing the tty input buffer.

**Comment by nkh** [comment]
hmm, any idea of what bash could be doing?

I get this:

> ./tmuxsend
pane_id: %148
ls
ls
ls
> ls
ls                 lsblk              ls_color_default   lscpu              lsipc              lslogins           lsns               lspcmcia           lsx
lsar               lsb_release        ls_color_internal  lshw               lsl                lsmem              lsof               lspgpot
lsattr             ls_color           lscolors           lsinitramfs        lslocks            lsmod              lspci              lsusb
> ls lsls

**Comment by nicm** [comment]
I don't know, it works for me with exactly your script. What if you do `sh myscript;cat` do you see `cat` show what you expect?

**Comment by nkh** [comment]
It doesn't, it even blocks. here's the output:

\> sh ./tmuxsend  ; cat
pane_id: %148
ls
ls
ls
ls
ls
ls

**Comment by nicm** [comment]
That looks fine to me, `cat` will just echo. So it appears tmux is sending the right thing. Maybe you should try a different shell or different shell version?
