### ISSUE TITLE
Support `{}` syntax for `run-shell`

### ISSUE THREAD

**Issue by noscript** [tmux/tmux#3309]
### Issue description

In 3.3 it was changed so that `{}` now only accepts tmux commands. This used to work prior to 3.3 but it is not supported anymore:
```tmux
# ctr-click to set cursor in zsh
# https://www.zsh.org/mla/users/2004/msg01201.html
bind-key -T root C-MouseDown1Pane {
  select-pane -t "{mouse}"
  send-keys -t "{mouse}" C-X # send ctrl-x to trigger mouse-tracking-enable in zsh
  run-shell {
    X=$(( #{mouse_x} + 33 ))
    Y=$(( #{mouse_y} + 33 ))
    BTN=' ' # right click
    chr() {
      awk "BEGIN{printf \"%c\", $1}"
    }
    tmux send-keys "\e[M${BTN}$(chr $X)$(chr $Y)"
  }
}
```

Any shell command fails with `unknown command: <command>`:
```
~/.tmux.conf:15: unknown command: awk
```

`{}` was a great way to improve readability and avoid multiple levels of quote escaping.

### Required information
* tmux 3.3a
* Debian Testing (bookworm) amd64
* $TERM `xterm-256color`

**Comment by cevhyruz** [comment]
Numerical expansion is supported in both `run-shell` and  `send-keys`.

**Comment by noscript** [comment]
This is not about expansions but to be able to run multi-line shell commands without a need to escape quotes and line breaks.

**Comment by nicm** [comment]
`{}` is no longer supported for shell commands because it meant an entirely separate parser that was never quite right. You should be able to just use `'` and indent with spaces:
```
  run-shell '
    X=$(( #{mouse_x} + 33 ))
    Y=$(( #{mouse_y} + 33 ))
    BTN=" " # right click
    chr() {
      awk "BEGIN{printf \"%c\", $1}"
    }
    tmux send-keys "\e[M${BTN}$(chr $X)$(chr $Y)"
  '
```
Or put long shell commands in a separate file.
