### ISSUE TITLE
Command (keybinding) to easily jump between last sessions

### ISSUE THREAD

**Issue by Ganneff** [tmux/tmux#331]
Hi

we have "last-window" command - it would be nice to also have a "last-session" command.

I often have a ton of tmux sessions, getting me to the upper case letters for the selectors of a session whenever i run choose-tree. 40, 50 sessions are easy.

Now, very often i need to switch between two of them regularly.
And here it would be simple to have a shortcut, currently its

choose-tree
*findorremembershortcut (and they change depending on how many sessions with whatever names you open)*
*work again*

Just having a command i can bind to a key to jump back to the last session would be better, and not so disrupting.

I realize I can do parts of that with linking windows into a new session, but often times my work goes over a load of them (I regularly open "multiwindow sessions" using my tm script (https://github.com/Ganneff/tm) that show loads of hosts together), and its not workable to join those windows elsewhere).

(If its possible already, just point me at the docs, but reading the manpage didnt have anything jump at me).

Thx, 
 Joerg

**Comment by nicm** [comment]
I thought switch-client had a flag for this

**Comment by ntnn** [comment]
It has - `-l` for last, `-n` for next, `-p` for previous.

Its even bound by default to `prefix+L`.

**Comment by Ganneff** [comment]
Wohoo.

I really hadnt found that / overlooked it. Possible as I may not have expected it behind switch-client, or it may not have hit my search terms, but switch-client -l is what I need, yes.

(Though its not bound here, only next and previous, according to tmux list-keys)

Thanks!
