### ISSUE TITLE
A Potential NPD Bug

### ISSUE THREAD

**Issue by ash1852** [tmux/tmux#3311]
Hi, I found a potential null pointer dereference bug in the project source code of tmux, and I have shown the execution sequence of the program that may generate the bug on the graph below. The red text illustrates the steps that generate the bug, the red arrows represent the call relationships, and the green text represents some additional information to help understanding when the steps occur, plus the file path can be seen in the blue framed section.

![image](https://user-images.githubusercontent.com/87304478/186302699-79d81f84-aadc-400b-be37-2fd26d93747d.png)

Although the code shown is for version 3.0, this potential bug is still present in the current version
https://github.com/tmux/tmux/blob/038dfb27a822c32c03d028a83f50844f65ab60e5/cmd-capture-pane.c#L87-L93
I look forward to your reply and thank you very much for your patience!

**Comment by krader1961** [comment]
What tool did you use to identify this "NPD"? What is the confidence level it can actually happen? Is this possibly a case of "could happen in theory but never in practice"? Would it be appropriate to simply add a `assert(line);` statement after line 87 to indicate it should never be a NULL pointer at that point? Would that silence whatever tool you used to find this possible "NPD"?

**Comment by ash1852** [comment]
I'm using our internally developed static detection tool, and the situation you describe is possible, i.e. theoretically possible and realistically impossible, but there is no assertion that the input parameter of this function, i.e. wp, will necessarily not cause "EVBUFFER_DATA(pending);" to return null.
In short, whether this bug is possible or not depends on the input of the function "cmd_capture_pane_pending", which may be used with incorrect input if one is not careful when using this function, which increases the requirement of understanding the function when using it, i.e. some prior knowledge is needed when using this function, which is not friendly enough according to my personal understanding.
If you want to add "assert(line)" after "EVBUFFER_DATA(dending);", you can indeed silence the tool. But I think it would not only keep the tool silent but also strengthen the robustness of the code if some code could be written at the beginning of that function to detect the error input that makes the bug happen.

**Comment by krader1961** [comment]
FWIW, I love static (e.g., `oclint` and `go vet`) and dynamic (e.g., `valgrind`) tools that identify programming mistakes. However, static analysis tools need to be conservative, IMHO. It's not clear that your tool is sufficiently conservative given that you acknowledge the scenario being discussed is "realistically impossible" using your own words. I do agree that explicitly handling a theoretical, even if not practical, scenario is preferable to relying on an implicit mechanism like a null pointer dereference causing a process panic.

**Comment by ash1852** [comment]
It is true, as you say, that our tools take a conservative guideline, but it is not clear to me yet whether it is possible to make such an assertion that the input to the function does not create an NPD bug, because this requires a good understanding of the project. if it can be guaranteed in the current version and in a future version, then there is no problem here.

**Comment by nicm** [comment]
How you could total_len be zero in evbuffer_pullup (so it returns NULL) but at the same time EVBUFFER_LENGTH return nonzero?

**Comment by ash1852** [comment]
> How you could total_len be zero in evbuffer_pullup (so it returns NULL) but at the same time EVBUFFER_LENGTH return nonzero?

You are right, there is an error where the figure shows the null pointer dereference however in the call on line 102, NPD may still occur
https://github.com/tmux/tmux/blob/038dfb27a822c32c03d028a83f50844f65ab60e5/cmd-capture-pane.c#L102
https://github.com/tmux/tmux/blob/038dfb27a822c32c03d028a83f50844f65ab60e5/cmd-capture-pane.c#L69

**Comment by nicm** [comment]
memcpy with linelen 0 is fine, no sane implementation will dereference line.

**Comment by ash1852** [comment]
ok,thank you for your effort
