### ISSUE TITLE
A Potential Bug of NPD

### ISSUE THREAD

**Issue by ash1852** [tmux/tmux#3312]
Hi, I found a potential null pointer dereference bug in the project source code of tmux, and I have shown the execution sequence of the program that may generate the bug on the graph below. The red text illustrates the steps that generate the bug

![image](https://user-images.githubusercontent.com/87304478/186306246-39cf5e80-a3ed-4d36-8b9f-cc57d030fdbd.png)

I think I do not need to provide more specific information in this bug to explain why the function bufferevent_new returns null, because some code snippets can already be seen in the current version of the code as follows
https://github.com/tmux/tmux/blob/038dfb27a822c32c03d028a83f50844f65ab60e5/format.c#L523-L526

I look forward to your reply and thank you very much for your patience!

**Comment by nicm** [comment]
Fixed in OpenBSD, will be in GitHub later, thanks.
