### ISSUE TITLE
Unable to access session options while customizing the status-line

### ISSUE THREAD

**Issue by iamFIREcracker** [tmux/tmux#3314]
### Issue description

I have custom bindings to temporarily disable `prefix` and switch to an empty `key-table`; it's all working as expected (i.e. disabling the prefix in one session, leaves all the other sessions unchanged) but when I try to display the value of `prefix` in the status-line (mostly to give me some cue as to which session has the prefix activated and which one has not), `tmux show -v` will **not** return the session-specific value.

Minimal tmux config (~/.tmux.conf.minimal):

```
bind C-z \
         set prefix None \;\
         set key-table off \;\
         refresh-client -S \;\

bind -T off M-z \
         set -u prefix \;\
         set -u key-table \;\
         refresh-client -S

set -g status-left "#S #(tmux show -v prefix) "
```

With the above:

- open up two sessions (`tmux -Ltest -f ~/.tmux.conf.minimal`)
- press `Prefix C-z` in one of them (Session 1)

Expected behavior:

- Session 1: 
  - default mappings are not working anymore (we set `prefix` to `None`)
  - and also `None` should appear in the status-line, after the session name
- Session 2: 
  - default mappings are still working as usual
  - and nowhere in the status-line we should see `None`

Actual behavior:

- Session 1: 
  - default mappings are not working anymore (OK)
  - and also `None` should appear in the status-line (OK)
- Session 2: 
  - default mappings are still working as usual (OK)
  - **but** the status-line  now shows `None` on the right of the current session name (UNEXPECTED)

### Required information

* tmux version (`tmux 3.3a`).
* Platform (`Darwin arm`).
* $TERM inside (`tmux-256color`) and outside (`alacritty`) of tmux.

**Comment by nicm** [comment]
Use #{prefix} instead of #().

**Comment by iamFIREcracker** [comment]
> but when I try to display the value of `prefix` in the status-line (mostly to give me some cue as to which session has the prefix activated and which one has not), `tmux show -v` will **not** return the session-specific value.

FWIW, I got tmux to lunch a custom script of mine while refreshing the status-line so I could inspect what the experiment looked like, and:

- From the statusline: `TMUX=/private/tmp/tmux-501/test,47556,-1`
- From Session 1: `TMUX=/private/tmp/tmux-501/test,47556,0`
- From Session 2: `TMUX=/private/tmp/tmux-501/test,47556,1`

**Comment by iamFIREcracker** [comment]
> Use #{prefix} instead of #().

Ha!  The following seems to populate the status-line as intended:

```
set -g status-left "#S #{?#{==:#{prefix},None},Stopped ,}"
```

i.e. display `Stopped` when `prefix` is `None`.  Great.

Before I close this: why is `tmux show-options -v ...` returning different values, depending on where it's run from? I suspect it has something to do with the different values of the `TMUX` environment variable, but I am not sure why would tmux pass `-1` when refreshing the status-line.

**Comment by nicm** [comment]
Probably yes it is picking a different session or whatnot.
