### ISSUE TITLE
Control key for shift / space bar

### ISSUE THREAD

**Issue by wg21908** [tmux/tmux#3316]
* Latest version: 3.3a
* Platform: CentOS 8

Question: What is the config needed in .tmux.conf to use CNTRL-SPACEBAR instead of the default CNTRL-B?  I have had this setting in place for past tmux versions but cannot getting it working in the most recent current version?

In the past, the following was used to get desired setup:

unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

**Comment by neutaaaaan** [comment]
For what it's worth, I'm using this right now with `tmux 3.3a`, and  I don't remember ever having to tweak it since I started using it with what I believe was `tmux 2.6`.

```
unbind C-b
set -g prefix C-space
```
