### ISSUE TITLE
Weird glitchy bug when typing in tmux

### ISSUE THREAD

**Issue by revolter** [tmux/tmux#3318]
### Issue description

Steps to reproduce:
1. Open tmux
2. Type `ssh aws`
3. Press the <kbd>backspace</kbd> key a few times

What happened:
- Some letters get duplicated, and are not removed when deleting text.

What should have happened:
- It should work as expected.

Screen recording:
<video src="https://user-images.githubusercontent.com/5748627/187512384-4f0b134f-a3fb-48db-9879-c64a043b93fe.mp4"></video>

Related issue:
- https://gitlab.com/gnachman/iterm2/-/issues/10485

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.3a`
* Platform (`uname -sp`): `Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color` and `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): I can't upload them, since they contain sensitive information (yet this template doesn't warn you about it...). I can provide requested information from them myself.

**Comment by revolter** [comment]
I am not 100% sure, but it seems like this started happening without me changing any config files or something. I think that one of the latest tmux releases caused it for me.

**Comment by nicm** [comment]
Does this happen without .tmux.conf? Does it happen in different terminals? If you rebuild whatever version of tmux you were using before does it still happen? Does it only happen sshing to one host or any host?

**Comment by krader1961** [comment]
FWIW, it's been my experience that this type of problem is most often due to the use of Unicode codepoints whose width is greater than one and the terminal and shell (and in this case tmux) don't agree on the width of those codepoints. I would bet the problem goes away if you simplify your prompt to contain only ASCII characters as well as the command you're typing.

**Comment by revolter** [comment]
> Does this happen without .tmux.conf?
Yes.

> Does it happen in different terminals?
Yes, in both iTerm and Terminal.

> If you rebuild whatever version of tmux you were using before does it still happen?
The thing is that I don't know exactly what version worked correctly :( But I'll try a "git bisect"-like search tonight.

> Does it only happen sshing to one host or any host?
If you refer to my "Type `ssh aws`" point, it happens with anything that I type, so that was only an example.

**Comment by revolter** [comment]
> I would bet the problem goes away if you simplify your prompt to contain only ASCII characters as well as the command you're typing.

It reproduces even with `export PS1=''` (empty string).

**Comment by nicm** [comment]
You will need to show the server log, either by trimming out anything you don't want others to see or by sending them privately.

**Comment by revolter** [comment]
I realized that I can get cleaner logs by running it without the `.tmux.conf`.

[tmux-server-38877.log](https://github.com/tmux/tmux/files/9458886/tmux-server-38877.log)

**Comment by nicm** [comment]
Your shell is doing this. Did you read this https://github.com/tmux/tmux/issues/3218#issue-1265998468 about bugs caused by how Homebrew builds tmux?

**Comment by revolter** [comment]
So, if you know that this is a known issue, that many stumbled upon, how come you didn't link to https://github.com/tmux/tmux/issues/3218#issue-1265998468 from the beginning? Don't you want NOT to waste time on the same issue again and again?

Also, I think that you, and other similar maintainers, forget that a lot of users don't know that many technicalities, and are not so experienced as you, so it's absurd to expect regular users to figure out the solution themselves, or even to know how and what to search, in order to stumble upon that issue. For example, I, obviously with no ill will, opened an issue for this problem in the iTerm repo, because I thought that that's the culprit, and wasted George Nachman's time for no reason.

I, myself, didn't know, and still don't know what `ncurses`, `default-terminal`, `TERM`, `tmux-256color`, `infocmp`, `tic`, etc. are and what they do. I only use `tmux` and `tmux a`, and I surely can't be the only one in this situation.

---

Having said these, and somewhat understood the implications of this issue, I think that:
- A separate issue could be created and pinned, specifically for this macOS limitation, containing the 2 solutions, and
- The https://github.com/tmux/tmux/wiki/Installing wiki page could contain the 2 solutions.

---

I will probably offend you and/or others with my comment, and I'm sorry for that, but these past months were a bit frustrating (a bit, because I didn't use `tmux` that much), and I wouldn't want for others to keep stumbling upon this issue over and over again, without finding a simple, clear and explicit solution.

**Comment by nicm** [comment]
I didn't realize it was the same problem until I saw the log so whinging about it isn't terribly helpful.
