### ISSUE TITLE
Command-line pane size not working

### ISSUE THREAD

**Issue by Diltsman** [tmux/tmux#3320]
### Issue description

When splitting windows from the commandline, the specified pane size is not honored by tmux unless the session has previously been attached.  The same behavior is observed if the `-l` parameter is removed and instead is set with the `resize-pane` command.

Steps that do not honor pane size:
1. tmux -vv new-session -d -s MySession
2. tmux -vv split-window -t MySession:0.0 -v -l10
3. tmux -vv attach-session -t MySession
4. C-b :kill-session

Steps that do honor pane size:
1. tmux -vv new-session -d -s MySession
2. tmux -vv attach-session -t MySession
3. C-b :detach-client
4. tmux -vv split-window -t MySession:0.0 -v -l10
5. tmux -vv attach-session -t MySession
6. C-b :kill-session

This was reproduced using git commit 6da520c5a1bc73d93a8b7f8bed7cc3835eb31297, this is master on 2022-09-02.

### Required information

uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 3.2a
st-256color

$TERM in tmux
tmux-256color

[bug.log.tar.gz](https://github.com/tmux/tmux/files/9479885/bug.log.tar.gz)
[no-bug.log.tar.gz](https://github.com/tmux/tmux/files/9479886/no-bug.log.tar.gz)

**Comment by nicm** [comment]
You create a session with the default size of 80x24 and then attach to a presumably bigger terminal so any panes will be resized to fit the new size.

**Comment by Diltsman** [comment]
Passing the terminal size to new-session -x and -y does fix this.
