### ISSUE TITLE
Conditional setting of pane-border-style does not work

### ISSUE THREAD

**Issue by LukasPietzschmann** [tmux/tmux#3321]
### Issue description
I have the following two settings in my tmux.conf:
```
set -g pane-border-style "#{?#{==:#{pane_current_command},fzf},fg=#181818,fg=#504945}"
set -g pane-active-border-style "#{?#{==:#{pane_current_command},fzf},fg=#181818,fg=#504945}"
```
I'm checking if the current pane is running fzf and depending on the result, the color is updated.
`pane-active-border-style` is updated correctly, but `pane-border-style` does not change.

Is there an error with my config, or is this an actual bug?

## Required information

* tmux version 3.3.
* Platform Linux x86_64.
* $TERM inside and outside of tmux : inside xterm-256color, outside xterm-kitty.

**Comment by nicm** [comment]
Are all your panes running `fzf`?

**Comment by nicm** [comment]
If you want to change it if *any* of the panes is running `fzf`, try something like `set -g pane-border-style '#{?#{m:* fzf *,#{P: #{pane_current_command} }},red,blue}'`.

**Comment by LukasPietzschmann** [comment]
> If you want to change it if _any_ of the panes is running `fzf`, try something like `set -g pane-border-style '#{?#{m:* fzf *,#{P: #{pane_current_command} }},red,blue}'`.

That worked. Thanks a lot!

**Comment by LukasPietzschmann** [comment]
Would you mind explaining what `m:` and `P:` does?

**Comment by nicm** [comment]
m is match, P is loop over all panes. There is a page here https://github.com/tmux/tmux/wiki/Formats
