### ISSUE TITLE
signed releases

### ISSUE THREAD

**Issue by moralground** [tmux/tmux#3322]
Hi. Would it be possible to provide pgp-signed release tarballs for new releases? Downstream packagers really appreciate this.

**Comment by nicm** [comment]
What is the benefit of this?

**Comment by hyder365** [comment]
Those who package tmux for various Linux distros could verify the source archive has not been tampered with or corrupted; that it came directly from the developer(s). If Github's downloads were compromised, for example, those who verified the signature wouldn't fall for it.

**Comment by nicm** [comment]
It all sounds a bit theoretical to me, what platform are you packaging tmux for?

I don't think this is something I really have the time or interest in doing.

**Comment by moralground** [comment]
> Those who package tmux for various Linux distros could verify the source archive has not been tampered with or corrupted; that it came directly from the developer(s). If Github's downloads were compromised, for example, those who verified the signature wouldn't fall for it.

That's a good summary. Sorry for the late reply.

As far back as 2001, tech articles like [this one](https://www.linuxjournal.com/article/4828) have said: "Thanks to several high-profile break-ins at public FTP sites on the Internet in which software packages were replaced with compromised (Trojaned) versions, it has become common practice for developers of security software to distribute digital signatures of their software distributions."

A lot of software vendors like Firefox and VLC distribute detached .asc signature files with their software releases. Even other projects where Github is their main repository do so too. (see irssi for example)

**Comment by nicm** [comment]
I don't really have time to work on this but if you can give me a clearly written script to generate a signature file after I create a tarball or (better) a diff to add creating a signature to the `make dist` target, then I will upload it when I upload the tarball to GitHub.

**Comment by moralground** [comment]
It'd just be one line after the tarball is generated by make dist:

    gpg --detach-sign --default-key XXX tmux-version.tar.gz 

(Where XXX is the key ID you [generated](https://wiki.archlinux.org/title/GnuPG#Create_a_key_pair) and [uploaded](https://wiki.archlinux.org/title/GnuPG#Use_a_keyserver))

Then add the resulting "tmux-version.tar.gz.sig" to the Github artifacts when doing a release.
