### ISSUE TITLE
Using Neovim inside tmux causes troubles with displaying emojis. 

### ISSUE THREAD

**Issue by perzzik** [tmux/tmux#3327]
1. First of all my specs. I'm using Windows Terminal with WSL to SSH connect to my server. (My server spec below)
![image](https://user-images.githubusercontent.com/45477829/188838333-e2c598b3-e5bf-4002-817b-ca16b72bc561.png)

2. Inside tmux (launched with tmux -u and without tmux.conf)
![image](https://user-images.githubusercontent.com/45477829/188843087-b8e2f9ae-2d3c-430c-8711-d378f585c199.png)

My issue:
    Inside tmux: 
![image](https://user-images.githubusercontent.com/45477829/188843910-32db5cfb-b131-4568-aaa1-5e6e1f4b2c03.png)
    Outside tmux: 
![image](https://user-images.githubusercontent.com/45477829/188843943-43ed3f31-2991-4684-976b-0be7687fdefd.png)

I have :set colorcolumn=15 on screenshots to clearly show there's width glitch with some emojis. But outside tmux everything is fine.

I tried bunch of things i found on google:
1. from tmux docs --enable-utf8proc not helped me
2. changing my locales to en_IN/en_IN.UTF-8 (according to few answers on askubuntu and etc.)
3. run tmux with -u flag not helped me too
_P.S. Maybe i forgot something in this list but i tried nearly everything i found on google._

**Comment by nicm** [comment]
Logs?

**Comment by perzzik** [comment]
> Logs?

[tmux-client-80931.log](https://github.com/tmux/tmux/files/9507197/tmux-client-80931.log)
[tmux-out-80933.log](https://github.com/tmux/tmux/files/9507198/tmux-out-80933.log)
[tmux-server-80933.log](https://github.com/tmux/tmux/files/9507201/tmux-server-80933.log)

tmux kill-server -> tmux -vv new -> nvim -u NONE (no config, tmux no config too)

**Comment by nicm** [comment]
utf8proc is telling tmux these characters are width 1, but for me at least they appear to be width 2:

![Screenshot 2022-09-07 at 16 00 32](https://user-images.githubusercontent.com/304243/188911686-6b119641-a5ef-4a4d-a1ec-85378acad5a8.png)

You could try a newer utf8proc version.

**Comment by nicm** [comment]
I'm sure you could manage to work out what the latest utf8proc version is yourself.

**Comment by nicm** [comment]
The odd thing is that in your screenshot, it *looks* like the second character is width 1, so 1 should be correct. 
What do you see if you do `printf 'x\360\237\227\202x';echo` inside and outside tmux?

**Comment by perzzik** [comment]
Outside: 
![image](https://user-images.githubusercontent.com/45477829/188914175-869bd361-18f8-4d72-98c1-1719c85d014a.png)

Inside tmux -u:
![image](https://user-images.githubusercontent.com/45477829/188914269-085c2541-75b8-4f11-8835-b8d6917cb206.png)

**Comment by nicm** [comment]
Are you sure vim is configured the same inside and outside tmux? If I send what vim sends to tmux to the terminal here, it looks fine, which means vim probably thinks the character is width 2:

![Screenshot 2022-09-07 at 16 20 03](https://user-images.githubusercontent.com/304243/188916178-b4d70665-0aaa-40fe-8081-9642cbf62a89.png)

It seems most likely this is vim has the wrong width and either it is configured differently outside tmux, or it works outside because the sequences it uses are different.

If you do `TERM=tmux vim` outside tmux, does it still look right?

**Comment by perzzik** [comment]
![image](https://user-images.githubusercontent.com/45477829/188916905-f61b1cd0-297a-44e4-abc4-1e28743665af.png)
Hmm, it looks normal (idk is it normal if i have 2char width one is emoji and second is empty)
But it worked fine outside of tmux in my nvim (configured or not)  you can see this in my first screenshots.

**Comment by nicm** [comment]
Is the first one outside tmux? It clearly thinks the width is two because it has moved the cursor by two positions. As tmux thinks the width is one, it will not display correctly inside tmux.

**Comment by perzzik** [comment]
> Is the first one outside tmux? It clearly thinks the width is two because it has moved the cursor by two positions. As tmux thinks the width is one, it will not display correctly inside tmux.

First one launched just from the shell with TERM=tmux vim 

this one inside of tmux launched with TERM=tmux vim 
![image](https://user-images.githubusercontent.com/45477829/188920356-6181099e-fa6e-41c1-ace6-06c6b3b95356.png)

**Comment by nicm** [comment]
You need to get vim and tmux to agree about the width. vim thinks it is 2 and tmux with utf8proc thinks it is 1. I assume it's the same without utf8proc.

I'd try building tmux with the newest utf8proc and see what it does.

**Comment by perzzik** [comment]
> I tried bunch of things i found on google:
> 
> 1. from tmux docs --enable-utf8proc not helped me

As i texted above i already tried utf8proc. On Ubuntu i have  libutf8proc-dev 2.5.0-1
I'll try it right now
![image](https://user-images.githubusercontent.com/45477829/188923829-a91964a5-0235-453c-ac9d-ba7f0c524f3a.png)

Just did it and nothing is changed. Launched with tmux -u and configured Nvim.
![image](https://user-images.githubusercontent.com/45477829/188924261-cd8bbbdd-c045-443e-8795-97eacc5bb286.png)

**Comment by nicm** [comment]
Right but that's not the latest utf8proc...

**Comment by perzzik** [comment]
I'm sorry for being bit silly but i'm not that good in Linux yet...

**Comment by perzzik** [comment]
> Right but that's not the latest utf8proc...

Well, i found .deb package and installed newer versions.
![image](https://user-images.githubusercontent.com/45477829/188929773-c75f021c-66cd-47b4-b956-bd416fc4cc27.png)

But...
![image](https://user-images.githubusercontent.com/45477829/188929798-f33146cb-0b38-45f4-8e5a-087cd5a15a05.png)

**Comment by nicm** [comment]
Show me tmux logs with that utf8proc version.

**Comment by perzzik** [comment]
Take a look
[tmux-client-110036.log](https://github.com/tmux/tmux/files/9508012/tmux-client-110036.log)
[tmux-out-110038.log](https://github.com/tmux/tmux/files/9508013/tmux-out-110038.log)
[tmux-server-110038.log](https://github.com/tmux/tmux/files/9508014/tmux-server-110038.log)

**Comment by nicm** [comment]
OK its still the same, it still thinks it should be width 1. And you are sure it doesn't work without utf8proc? I wonder where vim is getting the idea is this is width 2...

**Comment by perzzik** [comment]
I did re-built tmux from source with --disable-utf8proc and it was still the same width problems. I thought about this too already.

**Comment by nicm** [comment]
Not much else tmux can do here, it correctly knows that the symbol is width 1. The problem here is really with vim. Maybe you can use a different character?

**Comment by perzzik** [comment]
What do u mean if it works fine outside of tmux? You mean this disagreement can't be solved with fixing tmux?

**Comment by nicm** [comment]
No, tmux and vim disagree about the width of this character so the cursor positioning will be off. tmux correctly knows it is width 1 so it must be vim that is wrong.

**Comment by nicm** [comment]
If you do `printf 'x\360\237\227\202x';echo` inside tmux and then do `C-b : refresh-client`, does the terminal change or does it look the same?

**Comment by perzzik** [comment]
Nothing changes as i can see

**Comment by nicm** [comment]
OK well that confirms tmux and the terminal agree, because if they did not then when tmux redraws it would be wrong. It's only vim doesn't agree.

**Comment by perzzik** [comment]
So we have that term + nvim = fine and term + tmux = fine but term + tmux + nvim = glitches. So u want to say i have to dig forward to nvim to solve this?

**Comment by nicm** [comment]
You need to figure out how to tell vim the correct width for this character.

**Comment by lacygoill** [comment]
I might have been able to help, but for that I would have to make some tests, which is not easy when the relevant [text is provided as images](https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors-when-asking-a-question).

Anyway:

   - [`:help 'emoji'`](https://vimhelp.org/options.txt.html#%27emoji%27)
   - [`:help setcellwidths()`](https://vimhelp.org/builtin.txt.html#setcellwidths%28%29)
