### ISSUE TITLE
how to accept multiple inputs for command-prompt

### ISSUE THREAD

**Issue by TheSafdarAwan** [tmux/tmux#3329]
how to accept input for multiple commands in tmux command-prompt

i want to execute the `bind-key n command-prompt " new-window -n '%1'\;move-window -t '%2'"` but when i give the input only new-window name is accepted how can i give the input to second command to move the window to a certain index.

the thing is i want to automate the process of creating and renaming windows in one go.
I tried to make a hook `set-hook -g after-new-window (command)` but i use the tmux **ressurect** to restore the tmux session across restarts but with this hook it asks for input everytime ressurect creates a new window which is not great.

**Comment by nicm** [comment]
https://man.openbsd.org/OpenBSD-current/man1/tmux.1#command-prompt
 
> If present, -I is a comma-separated list of the initial text for each prompt. If -p is given, prompts is a comma-separated list of prompts which are displayed in order; otherwise a single prompt is displayed, constructed from template if it is present, or ‘:’ if not.
>
> Before the command is executed, the first occurrence of the string ‘%%’ and all occurrences of ‘%1’ are replaced by the response to the first prompt, all ‘%2’ are replaced with the response to the second prompt, and so on for further prompts.

Also you don't need `move-window`, you can give the new index to `new-window -t`.

**Comment by TheSafdarAwan** [comment]
> https://man.openbsd.org/OpenBSD-current/man1/tmux.1#command-prompt
> 
> > If present, -I is a comma-separated list of the initial text for each prompt. If -p is given, prompts is a comma-separated list of prompts which are displayed in order; otherwise a single prompt is displayed, constructed from template if it is present, or ‘:’ if not.
> > Before the command is executed, the first occurrence of the string ‘%%’ and all occurrences of ‘%1’ are replaced by the response to the first prompt, all ‘%2’ are replaced with the response to the second prompt, and so on for further prompts.
> 
> Also you don't need `move-window`, you can give the new index to `new-window -t`.

thank you very much i tried to specify window index using -a and -b and didn't paid attention to traget flag thanks for pointing out.

**Comment by TheSafdarAwan** [comment]
This is the answer `tmux command-prompt -p "Window name:,Window nr:" 'neww -n "%1"; movew -t "%2"'`
