### ISSUE TITLE
Add ability to force read-only on socket owner match

### ISSUE THREAD

**Issue by lkraav** [tmux/tmux#333]
After discovering zolrath/wemux and playing around, I found that as soon as the tmux socket becomes group-write-accessible, full write access cannot be stopped. `wemux` can be easily bypassed by just doing `tmux -S /tmp/tmux-another-user attach`.

I'd be interested in having a configuration option that provides the ability to at least somewhat safely share read-only access to tmux instances. Wondering about how that's possible:

1. For some reason, full `rw-` access is required to attach to a `tmux` socket, even for read-only mode. Why isn't just `r--` enough to provide `attach -r` access? I'm guessing it's because you need input ability to at the very least switch between windows, etc, or the read-only attacher view would be at complete mercy of the owner. Which could also be a valid use case.

2. If socket write access is a hard requirement, perhaps a higher level configuration option could be provided that automatically forces clients `read-only` if the socket owner doesn't match, or something similar?

**Comment by nicm** [comment]
How would tmux know which user is talking to it over the socket?

**Comment by lkraav** [comment]
> How would tmux know which user is talking to it over the socket?

Good question. I was guessing that it's possible to enumerate who has the socket opened and which client receives the data on which handle, but I may be totally off here.

**Comment by nicm** [comment]
Not portably. The only way would be if the client told the server what user it was running at but that has no security benefit at all.

**Comment by nicm** [comment]
There isn't really a way to force read only for certain users that isn't relatively easily bypassed, and read only mode is not a security feature in any case. Fundamentally, you should not give users you don't trust access to your account, through tmux or otherwise.
