### ISSUE TITLE
crash when piping buffer to Vim inside popup

### ISSUE THREAD

**Issue by lacygoill** [tmux/tmux#3330]
### Issue description

To reproduce, run these shell commands:

    $ echo 'bind-key -T root F3 display-popup "tmux show-buffer | vim -Nu NONE -i NONE -U NONE --not-a-term -"' >/tmp/tmux.conf
    $ tmux -Lx -f /tmp/tmux.conf

Then press `F3`.  Tmux crashes.

### Required information

 - `$ tmux -V`: tmux next-3.4, commit 0a0ded32685edafe934b767e6df9d218e227eb95
 - `$ uname -sp`: Linux x86_64
 - terminal: xterm
 - `$TERM` outside tmux: xterm-256color
 - `$TERM` inside tmux: screen
 - logs:

     [tmux-client-1016276.log](https://github.com/tmux/tmux/files/9544271/tmux-client-1016276.log)
     [tmux-out-1016278.log](https://github.com/tmux/tmux/files/9544272/tmux-out-1016278.log)
     [tmux-server-1016278.log](https://github.com/tmux/tmux/files/9544273/tmux-server-1016278.log)

 - [backtrace](https://github.com/tmux/tmux/files/9544269/backtrace.log)
 - [`$ tmux info`](https://github.com/tmux/tmux/files/9544270/info.log)

**Comment by nicm** [comment]
Does this fix it?
[x.diff.txt](https://github.com/tmux/tmux/files/9546472/x.diff.txt)

**Comment by lacygoill** [comment]
It does.  Thank you very much for the quick fix.

**Comment by lacygoill** [comment]
The patch made it to the [OpenBSD repository](http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/tmux/input.c?rev=1.209&content-type=text/x-cvsweb-markup), but not to the [current GitHub repository](https://github.com/tmux/tmux/blob/19344ec890e0c4343e3c20695806d482c631d67c/input.c#L2257).

**Comment by nicm** [comment]
Should be there now, thanks!
