### ISSUE TITLE
Switching sessions behaves in an inconsistent manner

### ISSUE THREAD

**Issue by 3N4N** [tmux/tmux#3331]
### Required information

Please provide the following information:

* tmux version: 3.3a
* Platform: Linux x86_64
* $TERM inside and outside of tmux: inside tmux-256color; outside st-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

### Problem

I have two keybindings to switch between sessions.

```
bind -n M-j switch-client -p
bind -n M-k switch-client -n
```
These are supposed to switch to the previous and the next sessions, and I assumed the serial being followed would be the integer numbers associated with the sessions.

```
(0) + enan:     (attached)
(1) + enan-rl:
(2) + work:
(3) + tmp:
```
But when I switch session with `-p` flag, for example, from session `(3) tmp`, instead of switching to `(2) + work` it switches to `(1) + enan-rl`. The `-n` flag behaves inconsistently as well.

Is there another command to achieve what I want or am I misunderstanding/misusing this `switch-client` command?

**Comment by nicm** [comment]
Next and previous is by name.

**Comment by 3N4N** [comment]
"By name" as in the sessions are sorted in alphabetical order (in the context of `switch-client`)? Any way to get a sort-by-number/id behavior?

**Comment by 3N4N** [comment]
@nicm sorry for pinging you but any idea about what I said above?

**Comment by nicm** [comment]
No, you would have to write a script to do it.

**Comment by 3N4N** [comment]
Do you mean bash script?

And you can close this issue if you want. You already addressed the issue.

**Comment by nicm** [comment]
You would need to write a script to do it.
