### ISSUE TITLE
osc52 works with set-clipboard 'on' but not 'external'

### ISSUE THREAD

**Issue by harshasrisri** [tmux/tmux#3333]
### Issue description
I just setup `nvim` to use osc52 to copy to system clipboard. The content is copied to system clipboard just fine when copying while not using `tmux`. But, from inside `tmux`, copying to system clipboard works only if clipboard is set to `on`, but not `external`.

- Verified set-clipboard setting via `tmux show -s set-clipboard`
- `tmux info | grep Ms` -> `193: Ms: (string) \033]52;%p1%s;%p2%s\a`

### Required information
* tmux version (`tmux -V`) - `tmux next-3.4` (from HEAD)
* Platform (`uname -sp`). `Linux unknown` (Manjaro)
* $TERM inside and outside of tmux (`echo $TERM`). outside: `xterm-256color`. inside: `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-server-48796.log](https://github.com/tmux/tmux/files/9595702/tmux-server-48796.log)
[tmux-client-48794.log](https://github.com/tmux/tmux/files/9595703/tmux-client-48794.log)

**Comment by nicm** [comment]
Yes, that's right...

**Comment by harshasrisri** [comment]
Is this expected behavior? If so, my apologies for raising an issue.
Otherwise, IIUC, `external` copies only to external/system clipboard, but `on` copies to tmux save-buffer as well. In my case, `external` doesn't seem to do anything.

**Comment by nicm** [comment]
No, that is not what they mean, look at set-clipboard in the man page.
