### ISSUE TITLE
Feature Request: Add ability to move the cursor to the top or bottom in copy mode

### ISSUE THREAD

**Issue by r-31415** [tmux/tmux#3334]
### Issue description

This is a feature request to add commands for moving the cursor to the top or bottom in copy mode. The similar `scroll-middle` command has already been implemented (#3307), and it will be very useful to have commands for the other use-cases.

### Required information

* tmux version: tmux 3.3a
* Platform (`uname -sp`): Linux x86_64

**Comment by topcat001** [comment]
@rsmith31415 @nicm I can take a look at this. I'd also like this feature :)

**Comment by rsmith31415** [comment]
It is great to hear that. Thanks!

**Comment by topcat001** [comment]
Hi, please have a look at the attached diff which implements `scroll-top` and `scroll-bottom`. I also fixed a small mistake in the calculation for the `scroll-middle` command. The new commands are not bound to any keys by default.
![git-001 diff](https://user-images.githubusercontent.com/22438522/192124644-3d3b26c7-49f6-4727-94c0-7af4707cc812.png)

**Comment by r-31415** [comment]
Hi @topcat001 , 

If you're referring to the link "git-001 diff", it only references an image with the message "The image ... cannot be displayed because it contains errors". Can you check again if the attachment is working? Thanks!

**Comment by topcat001** [comment]
That's because this interface does not allow diff files. It is just text. Please save it and rename.

**Comment by r-31415** [comment]
Got it. Okay, I tested the three commands and seem to be working pretty well :+1: 

I will let you know if I notice any unusual behavior.

**Comment by nicm** [comment]
@topcat001  Actually, issues and PRs *do* allow diff files, if you add `.txt` at the end. Only the teams chat interface doesn't allow them regardless. The ways of GitHub are mysterious.

**Comment by nicm** [comment]
Applied now, thanks!

**Comment by topcat001** [comment]
> @topcat001 Actually, issues and PRs _do_ allow diff files, if you add `.txt` at the end. Only the teams chat interface doesn't allow them regardless. The ways of GitHub are mysterious.

Right thanks for reminding me. I totally forgot about `.txt` :).
