### ISSUE TITLE
Bug on vim's vertical split within tmux

### ISSUE THREAD

**Issue by wangrongwei** [tmux/tmux#3336]
### Issue description
There is (maybe) a bug about vim's vertical split (vs) within tmux. In a short, if I vs more than three windows in vim, and when switching to the third window with the touch pad, sometimes the cursor will be wrongly positioned to the first window.

And of course, the vim works well without tmux.

### Required information
I not sure if this is a known issue or alternative solution exists？

Thanks.

**Comment by lacygoill** [comment]
- What's the tmux version?
- What's the Vim version?
- What's the terminal?
- What's the value of `TERM` inside/outside tmux?
- What's the OS?
- Where are the logs?

---

Anyway, let's try and guess a solution:

    :set ttymouse=sgr

See [`:help 'ttymouse'`](https://vimhelp.org/options.txt.html#%27ttymouse%27).
