### ISSUE TITLE
Add mouse mode option to enable scrolling but keep the selection behaviour

### ISSUE THREAD

**Issue by serkonda7** [tmux/tmux#3338]
### Issue description
I have seen in the changelog that this may have existed prior to 2.1.

Working with the terminal on a daily base, I'm used to scroll the history via mouse wheel and select text with click + drag.
However tmux doesn't fulfill this expectation neither does it's mouse mode.

Therefore I propose splitting mouse mode into these two options.

### Required information

Please provide the following information:

* tmux 3.1c
* Platform: PiOS lite 64bit (2022-09)
* xterm-256color
* [tmux-client-1672.log](https://github.com/tmux/tmux/files/9616375/tmux-client-1672.log)
* [tmux-server-1674.log](https://github.com/tmux/tmux/files/9616378/tmux-server-1674.log)

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#i-want-to-use-the-mouse-to-select-panes-but-the-terminal-to-copy-how
