### ISSUE TITLE
Right click on OSX Terminal.app does not show popup menu

### ISSUE THREAD

**Issue by yokas** [tmux/tmux#334]
OSX 10.11.3, Terminal.app2.6.1, tmux 2.1

1. start tmux with empty .tmux.conf
=> Right click popup menu
=> Can select text using mouse and copy/paste(press mouse, hold and drag, release mouse, command-c)
=> cannot scroll

2. start tmux with this .tmux.conf
` set-option -g mouse on`
=>  Right click does not popup menu
=> Mouse pointer become a plus `+`
=> Cannot select text(press mouse, hold and drag, release mouse => selected text become unselected)
=> cannot scroll

3. start tmux with this .tmux.conf
`
 set-option -g mouse on
 bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"  
 bind -n WheelDownPane select-pane -t= \; send-keys -M  
`
=> same as 2 expect can scroll

**Comment by nicm** [comment]
When you turn on the mouse, tmux needs to capture all mouse buttons. Most terminals provide a way to bypass it, trying pressing Ctrl or Alt.

**Comment by yokas** [comment]
@nicm what do you mean bypass?
It didn't work.

What I want is simple, just as tmux 2.0 or 1.9 maybe?

1. can scroll
2. right click on Terminal.app popups menu
3. I can copy/paste from/to Terminal

How can I configure it? Or its not supported in 2.1? 

Maybe I should downgrade to 2.0/1.9...

**Comment by nicm** [comment]
When you turn mouse on, tmux needs to take over all of the mouse clicks. You need to find out if your terminal provides a way to open the menu instead of sending the click to tmux, read the iTerm documentation to find out. Or turn off mouse in tmux.

**Comment by yokas** [comment]
hmm...I was wondering why tmux2/1.9 can do this..

yeah, I should probably turn off mouse. if fact, I can get anything I want(click/copy/paste), except scrolling. when I scroll while mouse off, it behaves like key up/down.

Is there any way to just enable scrolling?

**Comment by atomi** [comment]
I have the same complaint. My use case was right clicking on links and selecting open url. This allowed me to open urls with only one hand. Now I have to press shift or ctrl+click to open urls which is an annoyance.

Shouldn't unbinding right click work here? Because it doesn't.

```
unbind MouseDown3Pane
unbind MouseUp3Pane
```

**Comment by nicm** [comment]
When you turn mouse on, tmux needs to take over all of the mouse clicks. Turn the mouse off or bypass it by using whatever key your terminal provides to do so.

**Comment by nicm** [comment]
(There is no way for tmux to reverse a mouse click, once it has been passed to tmux, it cannot go back to the terminal, even if tmux does not want it.)

**Comment by atomi** [comment]
>When you turn mouse on, tmux needs to take over all of the mouse clicks.

Okay thanks for clarifying this :+1:

**Comment by atomi** [comment]
I've disabled mouse. :(
