### ISSUE TITLE
why "Inside tmux TERM must be screen, tmux or similar"?

### ISSUE THREAD

**Issue by LqkUWp** [tmux/tmux#3340]
### Issue description

Why does FAQ of tmux says that "Inside tmux TERM must be screen, tmux or similar"? Is there any potential compatibility problem? Is it possible to customize tmux to be compatible with xterm type TERM, like xterm-256color?

**Comment by nicm** [comment]
TERM tells applications how the terminal behaves and what escape sequences to send to it to make it do what they want. If it is wrong then applications may behave incorrectly. By and large xterm and tmux are close enough that you mostly get away with it though.

**Comment by LqkUWp** [comment]
I encounter some problems with shortcuts containing `CTRL` and `SHIFT` in vim and htop when setting `TERM=screen-256color` or `TERM=tmux-256color` inside tmux. But all probelms disappear once I set `TERM=xterm-256color`. So I want to stick with xterm-256color and avoid potential compatibility problems between tmux and xterm-256color. Maybe I'll report those problems in detail someday.

**Comment by nicm** [comment]
You'd be better reporting the key issues to vim and htop.
