### ISSUE TITLE
Feature request: Synchronized scrolling

### ISSUE THREAD

**Issue by kaddkaka** [tmux/tmux#3342]
It would be nice to scroll two panes simulatenously (like `scrollbind` in vim). It seems to have been possible before but the behavior has changed: https://stackoverflow.com/questions/63169079/tmux-how-to-scroll-two-pane-like-vim-scrollbind

**Comment by nicm** [comment]
I've added this to the todo list but I don't see it happening anytime soon.

**Comment by kaddkaka** [comment]
Personal todo list or something in the repo?

**Comment by nicm** [comment]
It is on the wiki on the contributing page.
