### ISSUE TITLE
Feature request: switch to next or previous session after current session is closed

### ISSUE THREAD

**Issue by imcaizheng** [tmux/tmux#3343]
According to man page, by setting `detach-on-destroy` to `off` the client is switched to the most recently active of the remaining sessions after current session is closed.

I think the most recently active session is not always desired. It could be more predictable if the client is switched to previous session or next session just like how `switch-client -p` or `switch-client -n` does.

I suggest add a new option like `detach-on-destroy-behavior [most-recently-active | previous | next]` to par with the `detach-on-destroy` option.

`most-recently-active` refers to the most recently active of the remaining sessions. `previous`/`next` refers to the previous/next session in alphabetic order.

**Comment by nicm** [comment]
I would be OK with that but instead of a new option change detach-on-destroy to be a choice option where the possible values are off/on/previous/next.

**Comment by imcaizheng** [comment]
You're right. It's more reasonable to reuse the `detach-on-destroy` option.

**Comment by nicm** [comment]
I have added this to the todo list.
