### ISSUE TITLE
Request: using logo based on tmux logo

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#3348]
### Issue description
Hi, I have an application (file manager) that is based on tmux and I have the following logo which is tmux's logo plus the name of the application on it. Is it OK that I use it?

![ftl](https://user-images.githubusercontent.com/45409/195288446-558ad05f-4252-42e8-80f2-c61af3e52fc2.png)

**Comment by nicm** [comment]
Yes, but you will need to include the license as mentioned here: https://github.com/tmux/tmux/blob/master/logo/LICENSE

**Comment by nkh** [comment]
My license in the man page, would it be sufficient that I add a link to your license in it?



...

# LICENSE

*ftl* is under Artistic licence 2.0 or GNU General Public License 3, at your option.

*ftl* logo is base on tmux's logo; tmux license is at https://github.com/tmux/tmux/blob/master/logo/LICENSE

# SEE ALSO
...

**Comment by nicm** [comment]
Yes that seems fine to me. Or if you have a LICENSE file put something similar in there (but in that case I would copy the text rather than linking to it).
