### ISSUE TITLE
feature : get a pane_size or pane_activity variable

### ISSUE THREAD

**Issue by 0xswitch** [tmux/tmux#3349]
### Issue description
There are current variable client_activity, session_activity or windows_activity which are holding the amount of bytes outputed but there is no pane_activity.
So It's seem impossible to get the number of line written to stdout/err by a command. It would be very useful for automatically saving the whole output of the last command like :

- saving pane_activity value
- command with some output 
- new pane_activity value - old pane_activity value

This feature would be life saving. Thanks

**Comment by nicm** [comment]
I think you are under a misapprehenstion. None of these hold bytes, they all hold the time since last output. We could add a timestamp for the last pane activity but it would not help you get the number of lines written by a command.

You can see the number of lines in the history with `history_size`, but it will only help you if you clear the history before your command.

**Comment by nicm** [comment]
We could add a count of all lines written to a pane, but what is the use case? What use is it to know how many lines an application has written?

**Comment by 0xswitch** [comment]
I saw my timestamp mistake right after opening the issue sorry. It's a very specific use I agree, the goal is to programmatically save the output of a command right after it execution without previous commandline output redirection.

**Comment by nicm** [comment]
Why don't you put something distinctive in your shell prompt and then search back for it? Or use `pipe-pane` before and after running the command?

**Comment by nicm** [comment]
It would be relatively easy to track how many lines have been scrolled out of the history, so you could know the number of lines added, but you will only be able to recover the lines if they have not been scrolled away.

**Comment by nicm** [comment]
Try this please: [tmux-hremoved.diff.txt](https://github.com/tmux/tmux/files/9888489/tmux-hremoved.diff.txt)

You can then calculate the number of lines emitted by a command, for example:
~~~~
O=$(tmux display -p "#{e/+:#{history_size},#{history_removed}}")
seq 1000
tmux display -p "#{e/-:#{e/+:#{history_size},#{history_removed}},$O}"
