### ISSUE TITLE
Can't delete from command line in tmux

### ISSUE THREAD

**Issue by nicholasrucci** [tmux/tmux#335]
I am running OSX and I am using iTerm2.

When I go into a tmux session my delete key does not work. I also try to use `Ctrl+H` and `Ctrl+?`, which those are not doing anything for me either.

In iTerm preferences->keys, I have delete sent to `^H`. In preferences->profiles->keys, I also have the box checked, Delete key send `^H`.

Vim is able to delete in tmux but from the command line I can not.

**Comment by nicm** [comment]
tmux always sends ^? for backspace. It works out what key to expect from termios. Make sure stty verase matches what your terminal is configured to send for backspace. I suggest using ^? not ^H.

**Comment by nicholasrucci** [comment]
Awesome. That did the trick. 
Thank you.

**Comment by vnikk** [comment]
Hi, I have exactly the same issue on macos, but the aforementioned method doesn't help.
I'm trying that on terminal and iterm2, have set up both to send ^? for backspace, but still tmux doesn't erase stuff. It's not even that it doesn't erase, but the line is not updated, e.g.:
I type "asdf" (which would give "command not found"), then I press Backspace 4 times, Enter, and just new line appears. I've set `stty erase ^?`.
Any hints please?
