### ISSUE TITLE
[Feature request] Official AppImage - once again

### ISSUE THREAD

**Issue by mliszcz** [tmux/tmux#3351]
Hi @nicm, all,

I'm opening a new issue since the existing ones were locked by the bot:
https://github.com/tmux/tmux/issues/2460
https://github.com/tmux/tmux/pull/2465
https://github.com/tmux/tmux/issues/3000

I'm aware that we have:
* https://github.com/antontkv/tmux-appimage (from @antontkv)
* https://github.com/nelsonenzo/tmux-appimage (from @nelsonenzo)

The main problem is that these are not build automatically and require additional work every time a new version of tmux is released. For example the one from @antontkv is still at 3.2a. And the one from @nelsonenzo is 3.3a but it was built on a machine with GLIBC_2.26, thus I can not use it on RHEL 7.8.

Ideally we should be able to just download the official AppImage from the CI build artifacts and from the files attached to the release on Github.

This can be automated and many projects are doing so. The first step would be to have a CI job that would produce the AppImage. I can contribute that and send a PR if you are willing to accept it.

Thanks!

**Comment by nicm** [comment]
I don't see any need for me to maintain this. If you aren't happy with the way others are doing so, why don't you set up your own repo and keep it up to date? Or ask one of the others if you can take over?

**Comment by mliszcz** [comment]
Okay, I understand your decision. Anyway, thanks for your input.

**Comment by antontkv** [comment]
> For example the one from @antontkv is still at 3.2a

Hi. There is actually 3.3a version in releases page. https://github.com/antontkv/tmux-appimage/releases/tag/3.3a

**Comment by mliszcz** [comment]
> > For example the one from @antontkv is still at 3.2a
> 
> Hi. There is actually 3.3a version in releases page. https://github.com/antontkv/tmux-appimage/releases/tag/3.3a

Sorry! I should write the other way around:

For example the one from ~@antontkv~ @nelsonenzo is still at 3.2a. And the one from ~@nelsonenzo~ @antontkv is 3.3a but it was built on a machine with GLIBC_2.26, thus I can not use it on RHEL 7.8.
