### ISSUE TITLE
tmux sends focus gained event when application starts

### ISSUE THREAD

**Issue by gpanders** [tmux/tmux#3354]
### Issue description

Starting an application that explicitly enables focus reporting sends a "focus gained" event to that application, even if the focused pane has never changed (that is, I started the application in the currently focused pane and never changed panes).

Specifically, this happens in Neovim which sends the CSI sequence to enable focus reporting `CSI ? 1004h` at startup. I have the following in my `init.vim`:

```vim
autocmd FocusLost * setlocal nocursorline
autocmd FocusGained * setlocal cursorline
```

When nvim starts when running in tmux, the `FocusGained` autocommand is fired. The result is that the intro text immediately disappears (because it runs the `setlocal` command).

Here are links to recordings of starting nvim [inside](https://asciinema.org/a/mLPtROnlvxqXqjet1ymuC8cRJ) and [outside](https://asciinema.org/a/zAnGDI0zpMywrVDQPi96fpTB8) of tmux if you want to see what I mean visually.

This is caused by these lines in `input.c` in the `input_csi_dispatch_sm_private` function: https://github.com/tmux/tmux/blob/934f357149dba903f091237e7ea7c7ba78471614/input.c#L1807-L1810

If I comment out these lines the issue goes away.

I would expect that a "focus gained" signal is only sent when the application obtains focus after being unfocused, not when it first starts in a focused pane.

### Required information

Please provide the following information:

* tmux version: 3.3a (can also reproduce on master)
* Platform: Darwin arm
* $TERM inside and outside of tmux: `tmux-256color` in tmux, `xterm-256color` (iTerm2) outside
* Logs from tmux (`tmux kill-server; tmux -vv new`):

  - [tmux-client-66594.log](https://github.com/tmux/tmux/files/9802825/tmux-client-66594.log)
  - [tmux-server-66596.log](https://github.com/tmux/tmux/files/9802826/tmux-server-66596.log)
  - [tmux-out-66596.log](https://github.com/tmux/tmux/files/9802829/tmux-out-66596.log)

**Comment by nicm** [comment]
Hmm I don't know where this came from but it appears xterm doesn't do this so I have changed it. Thanks!
