### ISSUE TITLE
lost server problem

### ISSUE THREAD

**Issue by beantowel** [tmux/tmux#3355]
### Issue description

Running tmux reports "lost server"

### Required information

Please provide the following information:
```shell
uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.3
linux
```

* Logs from tmux (`tmux kill-server; tmux -vv new`)：
[tmux-server-197.log](https://github.com/tmux/tmux/files/9806199/tmux-server-197.log)
the last line in the log is: `1666063292.431528 fatal: tcgetattr failed: Bad file descriptor`

**Comment by beantowel** [comment]
i've tried https://github.com/tmux/tmux/issues/2529, but it didn't work

**Comment by nicm** [comment]
tmux 2.3 has not been supported for five years. Please try a tmux 3.3a or building from master.

If it is the same with one of them, please do `strace -tttfostrace.out tmux new` and then show me the `strace.out` file.
