### ISSUE TITLE
Possible to `send-keys` to tmux itself rather than the application?

### ISSUE THREAD

**Issue by Hexstream** [tmux/tmux#3361]
* tmux version (`tmux -V`): `tmux 3.1c`
* Platform (`uname -sp`): `Linux unknown` (Debian 11)
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color` inside, `xterm-256color` outside.
* Logs from tmux (`tmux kill-server; tmux -vv new`): Irrelevant in this instance, I think...

Hello,

(I am in the process of switching to tmux after more than a decade of GNU screen...)

I want to implement this command for convenience, it would allow me to use TAB to have a look at the available commands under `C-a x`.

```
# C-a x TAB (list custom keys)
bind -T hexstream TAB menu -x P -y P \
'C-a x c (collapse)' c 'send-keys C-a x c' \
'C-a x d (detach client)' d 'send-keys C-a x d' \
'C-a x k (kill current window and switch to last one)' k 'send-keys C-a x k' \
'C-a x x (enter copy mode)' x 'send-keys C-a x x' \
'C-a x q (quit)' q 'send-keys C-a x q'
```

This almost works, except that `send-keys` sends the keys to the application rather than to tmux itself.
Duplicating the actual commands instead of simulating keypresses would be a maintenance burden.

Surely there must be a way to send key(stroke)s directly to tmux as if they had been typed?
For reference, GNU screen can do this with the `process` command.
(I like to call them "keyboard macros", per emacs.)

Perhaps there should be an option to `send-keys` to send keys to tmux rather than the application? (Maybe `-r` for "raw"?)
Or maybe a new kind of "target" that would target the server itself rather than a pane?

**Comment by krader1961** [comment]
> This almost works, except that send-keys sends the keys to the application rather than to tmux itself.

In what way does "this almost work" other than the trivial sense that a menu is displayed? 

> Duplicating the actual commands instead of simulating keypresses would be a maintenance burden.

I don't grok that assertion. Why is it a maintenance burden to replace a `send-keys` command with the actual tmux command? Especially since keys can be rebound. For example, I use `set-option -g prefix C-space` so the C-a in your `send-keys` wouldn't work with my config whereas using the actual tmux commands would work.

**Comment by Hexstream** [comment]
Sorry if I was unclear...

> In what way does "this almost work" other than the trivial sense that a menu is displayed?

This "almost works" in the sense that it does everything as I want it to, except for the fact that selecting a menu item sends the corresponding keys to the application (bash) instead of to tmux itself.

For instance, if I select the last menu item with `q`, then _bash_ receives `C-a x q`, which puts the cursor to the beginning of the line and inputs `xq` there. I want _tmux_ to receive this instead, so that my `C-a x q` binding kills the server.

> I don't grok that assertion. Why is it a maintenance burden to replace a `send-keys` command with the actual tmux command?

Because then, I need to duplicate the full command both in the original key binding and in my `TAB` menu thing ("binding completion"?), which means I will always need to update both places when I update the binding. This is especially a burden for more complex commands, especially if the quoting differs between the original command and the version in my TAB completion menu.

> Especially since keys can be rebound. For example, I use `set-option -g prefix C-space` so the C-a in your `send-keys` wouldn't work with my config whereas using the actual tmux commands would work.

This is irrelevant for my use-case. My `send-keys` invocations only need to work in my configuration, not yours.

----------

Now, of course, even better for my _immediate_ use-case would be if tmux had a nice built-in feature for TAB completion of bindings, but I suspect implementing a way to `send-keys` to tmux itself would open much more exciting possibilities at a much lower engineering cost.

**Comment by nicm** [comment]
I don't see much use for this TBH but I don't mind having it if you (or anyone) wants to open a PR.

It should be relatively simple to add a flag (`-C`?) to `send-keys` to look the key up in the client's key table, it already does this in `cmd_send_keys_inject_key` to run commands for modes. I'd probably add a `-T` flag as well to specify a key table explicitly.

**Comment by Hexstream** [comment]
Great! I don't work in C, though, so I'll let someone else have the fun. ;)

**Comment by Hexstream** [comment]
Unfortunately this doesn't quite do what I want, but I think we're close...

Load only this file with `tmux -f menu.conf`:

```
bind m menu -T 'Test menu' -x P -y P \
     'Direct' d { display 'Success!' } \
     'Indirect a' a { send -Tprefix m d } \
     'Indirect b' b { send -T -- C-b m d }
```

`Direct` works, and as far as I understand, `Indirect a` and `Indirect b` should have an equivalent effect, but it doesn't work.

Also, I think `send-keys` should support an `-n` option like `bind-key` does,
because I would much rather write `send -n C-b m d`.

**Comment by nicm** [comment]
No, you cannot send C-b to send the prefix you need to use -Tprefix.

**Comment by Hexstream** [comment]
I can live with that limitation, although it feels to me like having a way to programmatically add input events directly to tmux's input queue exactly as if they had been typed by the user seems much simpler conceptually and implementationally, and seems much more likely to do the right thing and work as expected in all scenarios. This is what GNU screen does and I haven't found any limitations with that approach.

**Comment by nicm** [comment]
Yes, that might be better. I didn't do that because it is not as useful for scripting, but I don't think this feature is terribly useful for scripting in the first place. Try this instead please: [x.diff.txt](https://github.com/tmux/tmux/files/10167564/x.diff.txt)

**Comment by nicm** [comment]
This has a minor bug fix: [y.diff.txt](https://github.com/tmux/tmux/files/10167592/y.diff.txt)

**Comment by Hexstream** [comment]
Thank you for working on this, this is a very important feature for me.

Unfortunately, I can't seem to get this `y.diff.txt` to work. I'm not even sure if I'm trying the right syntax or anything.
From reading the patch, it seems that the flag is now `-K` instead of `-T`, but I'm pretty lost.

Could you provide a version of  [my `menu.conf` above](https://github.com/tmux/tmux/issues/3361#issuecomment-1312565803) that works on your machine?
I'd like to make sure that I'm at least trying something that is _supposed_ to work...

**Comment by nicm** [comment]
Yes you should just be able to do -K, for example:
~~~~
tmux new
tmux send -K C-b c

**Comment by Hexstream** [comment]
Great! I really like this new syntax much more than the previous `-Tprefix`!

Unfortunately, this doesn't work:

```
bind m menu -T 'Test menu' -x P -y P \
     'Direct' d { display 'Success!' } \
     'Indirect' i { send -K C-b m d }
```

`Direct` works, but not `Indirect`.

Could you please make sure this works on your machine with `tmux -f menu.conf`?

**Comment by nicm** [comment]
Hmm I wonder if it is sending the keys to the menu, I'll have a look.

**Comment by nicm** [comment]
This won't work, because you are trying to send keys to a menu. `send-keys` will queue all three keys but menu keys are not processed off the queue, they are processed immediately (or menus would not work when the queue is blocked). You will need to do this a different way.

**Comment by nicm** [comment]
I have applied this now, it will be in GitHub later today when it syncs. Thanks!

**Comment by Hexstream** [comment]
Thank you.

I actually came up with a Plan B (workaround) ever since you initially said you "don't see much use for this TBH", but I haven't yet gotten around to trying it out. This does not even involve touching the code, although it might involve various minor limitations and might not be very suitable for general use.

I did not understand your explanation for why this feature cannot work with menus, this is an extremely impactful limitation for me because I have 95 instances of this in my would-be tmux configuration. I feel this must be an artificial limitation in the codebase, and I hope this will be fixed natively one day. In any case, my Plan B will hopefully work around that limitation regardless, at least for my use-case.

I will create a new issue if my Plan B is successful, and this might inform a way of working around the limitations regarding menus natively in the codebase.

**Comment by nicm** [comment]
I suggest instead of having menus trigger other menus, you put all your commands in a key table and have the menus trigger them instead.

**Comment by Hexstream** [comment]
Thank you for the great suggestion!

Indeed this `menu.conf` works:

```
bind d { display 'Success!' }

bind m menu -T 'Test menu' -x P -y P \
     'Direct' d { send -K C-b d }
```

I think I should be able to achieve what I want to do now, with some pain...

----------

For the record, my Plan B would have been something like starting a new tmux server ("loopback") to connect as a client to the primary tmux server. Using normal `send-keys` from the loopback server would then send keys to "tmux itself" exactly like I wanted `send-keys -K` to do, and this would work with menus also. (I wonder how easy or hard this would be to implement inside tmux itself...)

**Comment by Hexstream** [comment]
Ok, here is the next show-stopper bug.
I think this is the last one to fix before I can finally complete my advanced tmux configuration.

This seems to be an issue with nested `switch-client` while processing `send -K`.
I really hope this is not the same issue as with menus, and if it is, I really, _really_, _**really**_ hope you can fix this...

Please try this `menu.conf` with `tmux -f menu.conf`:

```
bind -n C-M-a switch-client -T command

bind -T command a { display 'Success!' }

bind -T command b switch-client -T command_b
bind -T command_b c { display 'Success!' }

bind m menu -T 'Test menu' -x P -y P \
     'Test a' a { send -K C-M-a a } \
     'Test b' b { send -K C-M-a b c }
```

`Test a` (C-b m a) works, but `Test b` (C-b m b) does not.

Note the way `Test b` fails: It sends a `c` to the application, and then manually pressing `c` displays "Success!".
So if the `c` was also sent to tmux itself instead of the application, then this would work as expected.

**Comment by nicm** [comment]
Hah:
~~~~
1673303232.653203 session 0 pasting (flag 1)
1673303232.653223 writing key 0x63 (c) to %0
1673303232.653241 input_key: c
~~~~
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/10377409/x.diff.txt)

**Comment by Hexstream** [comment]
**AMAZING!!**

This works almost perfectly, but I found a minor issue.

Please try this `menu.conf` with `tmux -f menu.conf`:

```
bind -n C-M-a switch-client -T command

bind -T command C-M-a { display 'Success!' }
bind -T command b { display 'Success!' }
bind -T command C-b { display 'Success!' }

bind m menu -T 'Test menu' -x P -y P \
     'Test a' a { send -K C-M-a C-M-a } \
     'Test b' b { send -K C-M-a b } \
     'Test c' c { send -K C-M-a C-b }
```

`Test a` and `Test b` work, but `Test c` does not.

I think the best thing to do would be to remove any special handling of the prefix key in the codebase, and just implement it as `switch-client -T prefix`. Support for a "second prefix" could also be removed, since you can just use `switch-client -T prefix` or, even easier, use `send -K` to send whatever your main prefix is.

**Comment by nicm** [comment]
I'll take a look but no we are not going to break every existing config in the world. Hah.

**Comment by Hexstream** [comment]
Your call, but I've noticed that sometimes there are backwards-incompatible changes in tmux, and sometimes those are the best way to reduce complexity for maintainers and users.

**Comment by nicm** [comment]
Yes when it would only affect some users, but removing prefix would be too many.

**Comment by Hexstream** [comment]
Ah, right, sorry, I should have tried manual key presses and the obvious workaround...

----------

**_SO!!_** I finally finished my transition from GNU screen to tmux!! _**Thank you for implementing `send-keys -K`!!**_
(It would be great if it worked with menus one day, although I don't think I'll rewrite my menu system again.)

Here is [the announcement](https://status-quo.hexstream.expert/#18_january_2023), [the documentation stub](https://status-quo.hexstream.expert/tools/tmux/) and, most importantly, [my rather advanced config](https://github.com/Hexstream/status-quo.hexstream.expert/tree/master/assets/tools/tmux/config).
**Let me know what you think!**

I want to make further improvements, but this is a good baseline.

**Comment by Hexstream** [comment]
Ok, here is another bug.

I am using the latest commit `c4a6f403bb9d7c24c291f01dee9572bb4b784096` (17 january 2023) with no patches applied.

Please try this `menu.conf` with `tmux -f menu.conf`:

```
bind -n C-M-a switch-client -T command

bind m menu -T 'Test' -x P -y P \
'Test a (1 2 3)' a {
      send -K C-M-a a
} \
'Test b (4 5 6)' b {
      send -K C-M-a b
} \
'Test c (7 8 9)' c {
      send -K C-M-a c
} \
'Test d ((1 2 3) (4 5 6))' d {
      send -K C-M-a d
} \
'Test e ((1 2 3) (4 5 6) (7 8 9))' e {
      send -K C-M-a e
} \
'Test f (((1 2 3) (4 5 6)) (7 8 9))' f {
      send -K C-M-a f
}

bind -T command a {
     neww -n '1'
     neww -n '2'
     neww -n '3'
}

bind -T command b {
     neww -n '4'
     neww -n '5'
     neww -n '6'
}

bind -T command c {
     neww -n '7'
     neww -n '8'
     neww -n '9'
}

bind -T command d {
     send -K C-M-a a
     send -K C-M-a b
}

bind -T command e {
     send -K C-M-a a
     send -K C-M-a b
     send -K C-M-a c
}

bind -T command f {
     send -K C-M-a d
     send -K C-M-a c
}
```

All tests work as expected, except the last one.

`Test f` (C-b m f) yields windows
`7 8 9 1 2 3 4 5 6` rather than
`1 2 3 4 5 6 7 8 9`.

**Comment by Hexstream** [comment]
So it's been 2 weeks, I'm assuming this is being worked on?

(Perhaps this issue should be reopened?)

**Comment by Hexstream** [comment]
I created [a dedicated issue](https://github.com/tmux/tmux/issues/3476) for this latest bug.
