### ISSUE TITLE
Feature Feasibility Question: would it be possible to zoom to an intermediate node in the tree?

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#3362]
Let's say I have a pane layout like 

```
+--------+---------+---+
|   a    |         |   |
+--------+    c    | d |
|   b    |         |   |
+--------+---------+---+
```

I might want to be able to zoom in *partially* so that I can have a full screen dedicated to just `a` and `b` panes, or just `c` and `d`.  I often want something like this because I like to have many panes, but sometimes many of these panes are semi-abandoned but I don't want to exactly destroy them just yet, so I'd like to hide them. Or sometimes I want to do some side-by-side work but i'm already in a window set up with like 8 panes in it and don't want to disrupt the layout but still want to maximize real estate for TWO panes. Right now it's only possible to do this on one pane. 

I do have some reasonable bindings that make it practical to do the following steps to achieve this: I would break one of these panes out into a new window and then i would "yank" over to the second one into that new window, e.g. `move-pane -t :+`. This is great but it's a highly non-reversible operation. When I want to restore the original layout I can do so but might need to spend a minute reorganizing the entire layout in the window because moving these back into their original window will screw up the layout and leave it in a completely different shape. 

I think that depending on how the internal tree representation is implemented, being able to hide just `d` and show all 3 of `a,b,c` would be cool too. I don't know what the limitations might be. i would hope that once you slide corners into places where they line up rectangularly we could do tree "flips" as necessary. 

    
         0
        / \
       /   \
      1     2 
     / \   / \
    a   b c   d
    
    
           0
          / \
         /   \
        1     2 
       / \    |
      3   4   d
     / \   \
    a   b   c

What I mean by this is that if the internal representation of the panes is the first example, then there's no easy way to show a zoomed view of panes a, b, and c, however if we rotate the tree into the second form, you can see that node 1 contains these panes.

My question is how feasible would such a feature be?

**Comment by nicm** [comment]
This has come up before and the answer is that it would be possible but fairly complicated. I can't find the issue where it was discussed however.
