### ISSUE TITLE
[Bug] Buffer overrun can happen in cmd_find

### ISSUE THREAD

**Issue by yiyuaner** [tmux/tmux#3364]
In the file `cmd.c`, the function `cmd_find` has the following [code](https://github.com/tmux/tmux/blob/5ce34add77fa3517a01e63b915c5f4e3241af470/cmd.c#L482):
```
ambiguous:
	*s = '\0';
	for (loop = cmd_table; *loop != NULL; loop++) {
		entry = *loop;
		if (strncmp(entry->name, name, strlen(name)) != 0)
			continue;
		if (strlcat(s, entry->name, sizeof s) >= sizeof s)
			break;
		if (strlcat(s, ", ", sizeof s) >= sizeof s)
			break;
	}
	s[strlen(s) - 2] = '\0';
```

If the supplied argument `name` does not equal any `entry->name` in the `cmd_table`, then `strlen(s) = 0` and the statement `s[strlen(s) - 2] = '\0'` becomes a buffer under-write.

**Comment by nicm** [comment]
How does it get to the `ambiguous` label without `strncmp(entry->name, name, strlen(name)) != 0` being true for at least one entry?

**Comment by yiyuaner** [comment]
> How does it get to the `ambiguous` label without `strncmp(entry->name, name, strlen(name)) != 0` being false for at least one entry?

Hi, this is a report generated by a static analysis tool. If it never happens, we can ignore it or adding an explicit assertion. Thanks for your response.
