### ISSUE TITLE
Nerd font UTF-8 character `FBD1` is rendered as zero-width

### ISSUE THREAD

**Issue by lewis6991** [tmux/tmux#3365]
### Issue description

`echo '.\ufbd1.'` prints a zero-width character inside tmux

Outside tmux:

![Screenshot 2022-10-26 at 12 38 31](https://user-images.githubusercontent.com/7904185/198019779-e4af1c47-0e9c-4e86-baa3-e6f7f8236514.png)

Inside tmux:
![Screenshot 2022-10-26 at 12 38 05](https://user-images.githubusercontent.com/7904185/198019837-3bb37d3a-f998-449e-b52c-378ea4de15d4.png)

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `3.3a`
* Platform (`uname -sp`): `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`): outside `xterm-256color`, inside `xterm-256color`. I also tried `xterm-kitty`, `tmux`, `tmux-256color` with all the same result.
* Logs from tmux (`tmux kill-server; tmux -vv new`). *I ran `-vvv` hope this is ok.

[tmux-client-5182.log](https://github.com/tmux/tmux/files/9869144/tmux-client-5182.log)
[tmux-out-5187.log](https://github.com/tmux/tmux/files/9869145/tmux-out-5187.log)
[tmux-server-5187.log](https://github.com/tmux/tmux/files/9869146/tmux-server-5187.log)

**Comment by nicm** [comment]
U+FBD1 should be \357\257\221 but this character does not appear in these log files.

**Comment by nicm** [comment]
No, it is not in this log either - there is no sign of you running `echo`, are you sure you ran it inside tmux?

**Comment by lewis6991** [comment]
I can see it on line 180 in tmux-out-40113.log. It is just obscured by a bunch of color codes.

**Comment by lewis6991** [comment]
[tmux-out-44666.log](https://github.com/tmux/tmux/files/9869846/tmux-out-44666.log)

This is after running `zsh -d -f -i` which contains `"cem-dev" 14:23 26-Oct-22^[(B^[[m^[[?12h^[[?25h^[[9;10H^[P=2s^[\e^Hecho '.\ufbd1.'^[P=1s^[\`

**Comment by nicm** [comment]
The out log is irrelevent, show the server log please.

**Comment by nicm** [comment]
Never mind. Are you pasting the character into tmux? It looks like it is being eaten by your terminal and tmux is not receiving it:
~~~~
1666789685.128067 /dev/pts/17: keys are 32 (\033[>1;4000;26c\033P>|kitty(0.26.4)\033\\)
1666789685.128093 /dev/pts/17: keys are 19 (\033P>|kitty(0.26.4)\033\\)
1666789686.783907 /dev/pts/17: keys are 1 (e)
1666789686.989579 /dev/pts/17: keys are 1 (c)
1666789687.065913 /dev/pts/17: keys are 1 (h)
1666789687.150394 /dev/pts/17: keys are 1 (o)
1666789687.519793 /dev/pts/17: keys are 1 (\020)
1666789687.976384 /dev/pts/17: keys are 1 (\020)
1666789688.686631 /dev/pts/17: keys are 1 (\r)
1666789690.672016 /dev/pts/17: keys are 1 (e)
1666789690.859680 /dev/pts/17: keys are 1 (x)
1666789690.945333 /dev/pts/17: keys are 1 (i)
1666789691.091363 /dev/pts/17: keys are 1 (t)
1666789691.221311 /dev/pts/17: keys are 1 (\r)

**Comment by lewis6991** [comment]
No I'm literally entering `echo '.\ufbd1.'`. Outside the tmux it prints the char correctly, inside it doesn't.

**Comment by nicm** [comment]
tmux is not receiving your typing correctly, try putting the echo in a shell script and running that.

**Comment by lewis6991** [comment]
Ok, one detail I've omitted is that tmux is running under ssh, however the terminal is able to display the character (outside tmux) on the remote machine.

I just tried without ssh (local tmux), and it works.

**Comment by lewis6991** [comment]
> tmux is not receiving your typing correctly, try putting the echo in a shell script and running that.

Same problem with a script. I have a feeling kitty is intercepting the sequence and not passing it on.

**Comment by nicm** [comment]
Kitty can't interfere with something sent from a shell script and tmux. Please show me your shell script and the server log from running it inside tmux.

**Comment by nicm** [comment]
Instead of echo, try this please:
~~~~
printf "aaa\357\257\221bbb\n"

**Comment by lewis6991** [comment]
Script is just `printf "aaa\357\257\221bbb\n"` with `source t.sh`

[tmux-server-55346.log](https://github.com/tmux/tmux/files/9870196/tmux-server-55346.log)

**Comment by nicm** [comment]
OK found it. Your platform `wcwidth` function cannot give tmux a width for this character:
~~~~
tmux-server-55346.log:1666792789.103887 UTF-8 \357\257\221, wcwidth() -1
~~~~
So tmux is ignoring it.

You can try building tmux with utf8proc and see if it has a width.

**Comment by lewis6991** [comment]
Useful log. Already on it!

**Comment by lewis6991** [comment]
Ok, so my tmux installation is from homebrew (for Linux) which isn't built with utf8proc. I've built from source by editing the recipe and the issue is now resolved.

Many thanks for your quick and receptive help with this!
