### ISSUE TITLE
C-S-Tab handling with extended keys

### ISSUE THREAD

**Issue by aaronjensen** [tmux/tmux#3366]
### Issue description

Tmux does not appear to detect `M-[ 1 ; 5 Z` as C-S-tab, which is what iterm2 sends (and I believe is what the spec specifies for C-S-tab w/ CSI). C-tab works fine. I'd be happy to add support, but I don't know where the CSI handling is in the code.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 3.3a (also tested with master)
* Platform (`uname -sp`): Darmin arm
* $TERM inside and outside of tmux (`echo $TERM`).: outside: xterm-256color-italic, inside: tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).: I did this, but I'm not sure where logs go

**Comment by nicm** [comment]
You can try adding it to `tty_default_xterm_keys`.

**Comment by nicm** [comment]
Why does it not work as ASCII 9 instead of adding KEYC_TAB?

**Comment by aaronjensen** [comment]
I swear I tried that, but it does work:

```diff
diff --git a/tty-keys.c b/tty-keys.c
index bb9ec231..8ece2733 100644
--- a/tty-keys.c
+++ b/tty-keys.c
@@ -188,6 +188,8 @@ static const struct tty_default_key_raw tty_default_raw_keys[] = {
 	{ "\033[23^", KEYC_F11|KEYC_CTRL },
 	{ "\033[24^", KEYC_F12|KEYC_CTRL },
 
+	{ "\033[1;5Z", '\011'|KEYC_CTRL|KEYC_SHIFT },
+
 	{ "\033[11@", KEYC_F1|KEYC_CTRL|KEYC_SHIFT },
 	{ "\033[12@", KEYC_F2|KEYC_CTRL|KEYC_SHIFT },
 	{ "\033[13@", KEYC_F3|KEYC_CTRL|KEYC_SHIFT },
```

I'll submit a PR and see if I can get proper `C-i` handling working as well. Thank you.

**Comment by nicm** [comment]
No, this is not right, this needs to go into `tty_default_xterm_keys`.

**Comment by nicm** [comment]
Also 5 is Ctrl not Shift+Ctrl.

**Comment by aaronjensen** [comment]
> No, this is not right, this needs to go into tty_default_xterm_keys.

I'll try that, but it doesn't have the same modifier optionality. It's a specific CSI for a specific key combination.

> Also 5 is Ctrl not Shift+Ctrl.

I know it is, but that's not what the fixterms spec has. See https://www.leonerd.org.uk/hacks/fixterms/

**Comment by aaronjensen** [comment]
It doesn't seem to work for me in `tty_default_xterm_keys`, as it does not have a modifier placeholder.

```diff
diff --git a/tty-keys.c b/tty-keys.c
index bb9ec231..1f77df74 100644
--- a/tty-keys.c
+++ b/tty-keys.c
@@ -246,6 +252,7 @@ static const struct tty_default_key_xterm tty_default_xterm_keys[] = {
 	{ "\033[6;_~", KEYC_NPAGE },
 	{ "\033[2;_~", KEYC_IC },
 	{ "\033[3;_~", KEYC_DC },
+	{ "\033[1;5Z", '\011'|KEYC_CTRL|KEYC_SHIFT },
 };
 static const key_code tty_default_xterm_modifiers[] = {
 	0,
```

**Comment by nicm** [comment]
Ugh how stupid can it be...

**Comment by nicm** [comment]
OK I think you were right then - you should just list all the keys explicitly in `tty_default_raw_keys`.

**Comment by nicm** [comment]
Do not put `u` keys in there, they should be handled in `tty_keys_extended_key`.

**Comment by aaronjensen** [comment]
Ok, I'll see what I can do there.

**Comment by aaronjensen** [comment]
`C-S-Tab` is also an extended key, yes? It just doesn't end with `u`. Should that go in `tty_keys_extended_key` as well?

I'm afraid I don't know the how/where to add a new flag/member in the table entries. 

What is the relationship between input keys and tty keys?

**Comment by aaronjensen** [comment]
That's helpful, thank you.

If I understand correctly, then `C-S-Tab` should send backtab if extended keys is disabled and the extended key sequence when it is enabled, does that sound right? Can I do that explicitly in `input_key` within `	if (~s->mode & MODE_KEXTENDED) {` ?

**Comment by nicm** [comment]
I can't get xterm to work right now so I can't check but if you see what it sends for `C-Tab`/`C-S-Tab` by default then that's what tmux should do.

**Comment by nicm** [comment]
OK xterm seems to just ignore the `Ctrl`. So in `input_key`:

- If `KEXTENDED` is set then send the extended sequence;

- Otherwise ignore the `Ctrl` and send `Tab`/`BTab`.

You can probably do the second one just by changing around line 451 to skip the `justkey <= 0x7f` block if `KEXTENDED` is set and the key is `Tab`, then handle the first one with all the cases in the extended bit around line 524.

**Comment by aaronjensen** [comment]
Related, I'm looking into why C-S-a is seen as C-a and I came across efb5e58c381a5faf7751d916a60f256ede19c0e8

I can't tell yet from the code change if it's doing what I think it's doing, but the commit message says "Restore previous behaviour so that C-X remains the same as C-x."

Was there a reason we don't want to support C-S-x and C-x as separate? Per fixterms, if we see `CSI 65;5 u` it should be `C-S-a`, but tmux sees it as and sends it as `C-a`.

**Comment by aaronjensen** [comment]
> OK xterm seems to just ignore the Ctrl. 

iterm, and tmux currently afaict, ignore the entire keypress. i.e. C-tab ends up not being sent at all. Is this more desirable than editorializing the keypress down to just tab?

**Comment by nicm** [comment]
IIRC modifyOtherKeys=1 does not do this and that is all we support. Check what xterm does.

**Comment by aaronjensen** [comment]
I'm having a hard time getting modifyOtherKeys=1 to work on macos, but from https://invisible-island.net/xterm/modified-keys.html it seems like I'd expect it to handle the full fixterms spec, which includes C-S-a

**Comment by nicm** [comment]
I don't know about that, best check what it does or look at the code. There is an escape sequence to turn it on if you can't get the X resource to work.

But in any case we want to emulate xterm's modifyOtherKeys=1. Doing 2 would be nice but it will mean changing some things around because there are keys that tmux cannot currently represent or will not handle correctly.

**Comment by aaronjensen** [comment]
Oh, I didn't realize there were 1 and 2.

**Comment by aaronjensen** [comment]
What do you think about something like this?

```diff
diff --git a/input-keys.c b/input-keys.c
index ebf61333..bce3d830 100644
--- a/input-keys.c
+++ b/input-keys.c
@@ -306,6 +306,19 @@ static struct input_key_entry input_key_defaults[] = {
 	},
 	{ .key = KEYC_DC|KEYC_BUILD_MODIFIERS,
 	  .data = "\033[3;_~"
+	},
+
+	{ .key = '\011'|KEYC_CTRL,
+	  .data = "\011"
+	},
+	{ .key = '\011'|KEYC_CTRL|KEYC_EXTENDED,
+	  .data = "\033[9;5u"
+	},
+	{ .key = '\011'|KEYC_CTRL|KEYC_SHIFT,
+	  .data = "\011"
+	},
+	{ .key = '\011'|KEYC_CTRL|KEYC_SHIFT|KEYC_EXTENDED,
+	  .data = "\033[1;5Z"
 	}
 };
 static const key_code input_key_modifiers[] = {
@@ -468,6 +481,8 @@ input_key(struct screen *s, struct bufferevent *bev, key_code key)
 		key &= ~KEYC_KEYPAD;
 	if (~s->mode & MODE_KCURSOR)
 		key &= ~KEYC_CURSOR;
+	if (~s->mode & MODE_KEXTENDED)
+		key &= ~KEYC_EXTENDED;
 	ike = input_key_get(key);
 	if (ike == NULL && (key & KEYC_META) && (~key & KEYC_IMPLIED_META))
 		ike = input_key_get(key & ~KEYC_META);
@@ -475,6 +490,8 @@ input_key(struct screen *s, struct bufferevent *bev, key_code key)
 		ike = input_key_get(key & ~KEYC_CURSOR);
 	if (ike == NULL && (key & KEYC_KEYPAD))
 		ike = input_key_get(key & ~KEYC_KEYPAD);
+	if (ike == NULL && (key & KEYC_EXTENDED))
+		ike = input_key_get(key & ~KEYC_EXTENDED);
 	if (ike != NULL) {
 		log_debug("found key 0x%llx: \"%s\"", key, ike->data);
 		if ((key & KEYC_META) && (~key & KEYC_IMPLIED_META))
diff --git a/tmux.h b/tmux.h
index f0f17eaa..e88eac0f 100644
--- a/tmux.h
+++ b/tmux.h
@@ -138,6 +138,7 @@ struct winlink;
 #define KEYC_IMPLIED_META    0x08000000000000ULL
 #define KEYC_BUILD_MODIFIERS 0x10000000000000ULL
 #define KEYC_VI              0x20000000000000ULL
+#define KEYC_EXTENDED        0x40000000000000ULL
 
 /* Masks for key bits. */
 #define KEYC_MASK_MODIFIERS  0x00f00000000000ULL
diff --git a/tty-keys.c b/tty-keys.c
index bb9ec231..ac7c0ed3 100644
--- a/tty-keys.c
+++ b/tty-keys.c
@@ -208,6 +208,10 @@ static const struct tty_default_key_raw tty_default_raw_keys[] = {
 	/* Paste keys. */
 	{ "\033[200~", KEYC_PASTE_START },
 	{ "\033[201~", KEYC_PASTE_END },
+
+	/* fixterms C-S-tab. */
+	{ "\033[1;5Z", '\011'|KEYC_CTRL|KEYC_SHIFT|KEYC_EXTENDED },
+
 };
 
 /* Default xterm keys. */
@@ -974,7 +978,7 @@ tty_keys_extended_key(struct tty *tty, const char *buf, size_t len,
 		log_debug("%s: extended key %.*s is %llx (%s)", c->name,
 		    (int)*size, buf, nkey, key_string_lookup_key(nkey, 1));
 	}
-	*key = nkey;
+	*key = nkey|KEYC_EXTENDED;
 	return (0);
 }
 ```

**Comment by aaronjensen** [comment]
Btw, I was mistaken about C-S-a, it is working as I expected. I was just using a checker that didn't have extended keys enabled. With `extended-keys always` it works fine.

**Comment by nicm** [comment]
Looks good but please add all the other Tab modifiers as well.

**Comment by aaronjensen** [comment]
They're unnecessary because of the generic extended key support. Do you want me to add them anyway for clarity?

**Comment by nicm** [comment]
Oh right if they work already that's fine.

**Comment by nicm** [comment]
I'm going to close this and we can continue in the PR. Thanks!
