### ISSUE TITLE
[Feature Request] set one command to multiple hook names in a single 'set-hook' statement

### ISSUE THREAD

**Issue by cevhyruz** [tmux/tmux#3367]
Currently, there is no way to set one command to multiple hook-names in a single `set-hook` statement.

Sometimes you want a togglable event which can only be possible by setting multiple hook statements with redundant commands
For example, If I want to rename a session every time they are created/destroyed I will have to do this:
```tmux
set-hook -g session-created {
  run-shell "/bin/rename_session.sh"
  set-option -F status-style "#{E:_status_style}"
}

set-hook -g session-closed  {
  run-shell "/bin/rename_session.sh"
  set-option -F status-style "#{E:_status_style}"
}

```
There is no problem with this approach however if your hooks start to grow large maintaining pairs of redundant commands is a bit trivial. 

Maybe setting them like this?
```tmux
set-hook -g session-created session-closed {...} 
```

**Comment by nicm** [comment]
You can set the second one to `set-hook -R session-created`?

**Comment by cevhyruz** [comment]
@nicm. You mean like this?
```tmux
set-hook -g session-created {
  run-shell "/bin/rename_session.sh"
  set-option -F status-style "#{E:_status_style}"
}

set-hook -g session-closed  {
  set-hook -R session-created
}
```

**Comment by cevhyruz** [comment]
Yes
