### ISSUE TITLE
Help debug C-S-Tab behavior on 1 system

### ISSUE THREAD

**Issue by uqs** [tmux/tmux#3369]
### Issue description

Ok, sorry, but this will get a bit longer and is rather strange. It's not a dupe of issue #3366, it has existed ever since I switched from using C-A n/p for switching windows to using C-Tab and C-S-Tab, as I have these as macros on a keyboard layer and those work in Chrome and Firefox as well.

Now, I would switch back to using C-Pgup and C-Pgdn for those, but XTerm wants to use those key sequences and I gave up fighting.

Ok, what's the issue. I have numerous systems, some FreeBSD some Linux and am using the same .tmux.conf on all of them. I'm also using different clients, either XTerm on FreeBSD or XTerm on Linux, and often Mosh is in the mix as well.

The problem boils down to tmux on FreeBSD system A seemingly ignoring the "shift" part and it will move to the "next" window no matter whether I send C-Tab or C-S-Tab. This does not happen for FreeBSD system B or C, and they all use the same config, environment and package.

I tested using plain SSH and using ^V that the keycodes are being send just fine. I compared config, binary and termcap database with md5(1) and there are no differences. So then I resorted to using ktrace and caught tmux redhanded!

Working system C:
```
  6486 tmux     CALL  readv(0x13,0x82065a3e0,0x1)
  6486 tmux     GIO   fd 19 read 9 bytes
       0x0000 1b5b 3237 3b36 3b39 7e                                       |.[27;6;9~|
 
  6486 tmux     RET   readv 9
  6486 tmux     CALL  getuid
  6486 tmux     RET   getuid 1000/0x3e8
  6486 tmux     CALL  poll(0x825806200,0x11,0x393)
  6486 tmux     RET   poll 1
  6486 tmux     CALL  writev(0x13,0x820659c00,0x1)
  6486 tmux     GIO   fd 19 wrote 196 bytes
       0x0000 1b5b 3f32 356c 1b5b 3330 6d1b 5b34 336d 1b5b 3630 3b31 484e  |.[?25l.[30m.[43m.[60;1HN|
       0x0018 6f20 7072 6576 696f 7573 2077 696e 646f 7720 2020 2020 2020  |o previous window       |
       0x0030 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020  |                        |
       0x0048 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020  |                        |
       0x0060 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020  |                        |
       0x0078 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020  |                        |
       0x0090 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020  |                        |
       0x00a8 2020 2020 2020 2020 2020 2020 2020 2020 2020 201b 5b6d 1b5b  |                   .[m.[|
       0x00c0 313b 3348                                                    |1;3H|
```

It receives the right sequence with shift `[27;6;9~` instead of the non-shifted `[27;5;9~`. Note the "No previous window" output.

But here's what it receives on the cursed system A:
```
  2772 tmux     CALL  readv(0x14,0x8204ed950,0x1)
  2772 tmux     GIO   fd 20 read 9 bytes
       0x0000 1b5b 3237 3b36 3b39 7e                                                 |.[27;6;9~|
 
  2772 tmux     RET   readv 9
  2772 tmux     CALL  poll(0x8275ce200,0x12,0x2f)
  2772 tmux     RET   poll 1
  2772 tmux     CALL  writev(0x14,0x8204ed170,0x1)
  2772 tmux     GIO   fd 20 wrote 192 bytes
       0x0000 1b5b 3f32 356c 1b5b 3330 6d1b 5b34 336d 1b5b 3630 3b31 484e 6f20 6e65  |.[?25l.[30m.[43m.[60;1HNo ne|
       0x001c 7874 2077 696e 646f 7720 2020 2020 2020 2020 2020 2020 2020 2020 2020  |xt window                   |
       0x0038 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020  |                            |
       0x0054 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020  |                            |
       0x0070 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020  |                            |
       0x008c 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020  |                            |
       0x00a8 2020 2020 2020 2020 2020 2020 2020 201b 5b6d 1b5b 343b 3348            |               .[m.[4;3H|
```
It reads the same correct sequence but interprets it as "next window", same as it does for `[27;5;9~`

What the heck causes that in 1 out of half a dozen servers, across all clients that I can connect to it?

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.3a (but has been an issue for a year now, maybe longer)
* Platform (`uname -sp`). FreeBSD amd64
* $TERM inside and outside of tmux (`echo $TERM`). xterm-256color vs tmux-256color  (on all systems and combinations)
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Show server log from a working and not working system please.
