### ISSUE TITLE
in mouse mode, after selecting text in a scrolled window, it scrolls to end

### ISSUE THREAD

**Issue by timotheecour** [tmux/tmux#337]
i have mouse mode on and tmux 2.1
^b page up (scrolls up)
hover over some text (text selection is yellow)
upon releasing left mouse button, tmux scrolls all the way down (ie exits copy mode)

**Comment by nicm** [comment]
This is how it is meant to work, you can change it in Git master by altering the binding for MouseDragEnd1Pane to add -x.

**Comment by timotheecour** [comment]
is there a tmux.conf option for that? if not can we have such an option? it's often not the desired behavior

**Comment by nicm** [comment]
No option, but if you read my previous reply you may get further.

**Comment by timotheecour** [comment]
I did, and thanks for the suggested solution; but your answer seems to suggest it would be an undesired pull request. However this seems like a very common annoyance:

look at all the +1 under:
https://github.com/tmux/tmux/issues/140: Option to disable "release mouse click to copy selection & exit copy-mode" behavior

(other related issues as well, eg https://github.com/tmux/tmux/issues/147)

**Comment by nicm** [comment]
I like the existing behaviour, but there is now a way to change it. We don't need two ways.

**Comment by timotheecour** [comment]
what should i add in my tmux.conf after rebuilding git master?

is this correct?

```
bind-key MouseDragEnd1Pane copy-selection -x
```

**Comment by nicm** [comment]
bind -temacs-copy MouseDragEnd1Pane copy-selection -x

Or vi-copy if you use vi mode.

**Comment by timotheecour** [comment]
thanks!!

**Comment by timotheecour** [comment]
actually the proposed fix is not great and I now see why you don't want it to be the default.
what i would like (as many others, see +1's under #140):

when scrolling, upon releasing a text selection, it stays in scrolled mode (and hence copy mode)

when not scrolling, upon releasing a text selection, it goes back to normal mode (ie the current default).

in other words, selecting text doesn't change the state (the fact that selecting text enters copy mode is an implementation detail: it should exit copy mode after selection only if we weren't in copy mode before mouse selection)

this is IMO follows the principle of least surprise, and is exactly what the others wanted too.

**Comment by chikamichi** [comment]
I agree it's slightly surprising selecting text in normal mode switches over to copy-mode, instead of simply filling the copy buffer with the selection and staying in normal mode. The extra `q` or `Enter` keypress to exit from the unexpected copy-mode breaks the workflow.

But it's already quite an improvement, not being bounced back while in highlighting during copy-mode!
