### ISSUE TITLE
Relative pane index is affected by interaction with other sessions

### ISSUE THREAD

**Issue by krobelus** [tmux/tmux#3370]
### Issue description

In the first terminal launch session `$0`:

	tmux -Ltest kill-server
	tmux -Ltest -f/dev/null new-session \; split-window

In another terminal launch session `$1`:

	tmux -Ltest new-session \; split-window

In the first terminal, type `C-b o` to switch to the other pane.
In a third terminal, run this command 

	tmux -Ltest display-message -p -t '$1:@1.+1' '#{pane_id}'

The output is `%1` which is a pane in the session `$0`.
I expect it to be `%2`, which is the inactive pane in the session `$1`.
I expect that `-t $1:@1.+1` means the target pane is inside the window `$1:@1`.

### Required information

	$ uname -sp && tmux -V && echo $TERM
	Linux unknown
	tmux next-3.4 (latest master, 9dd1f442c5a7f1d8d480476f11bc62cceab2019a)
	foot

**Comment by nicm** [comment]
Show server log please.

**Comment by krobelus** [comment]
https://gist.github.com/krobelus/33663d5069e34d927232650b4b54eff1

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/9900338/x.diff.txt)

**Comment by krobelus** [comment]
Yes that works, thanks!
I tried to write a scripted test but it only seems to reproduce interactively.
The change looks correct, it establishes `assert(!fs->wp || fs->w == fs->wp->window);`.
`fs->current` is just the fallback; we only use it if a target spec is incomplete.

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
