### ISSUE TITLE
`tmux display-message -p '#{l:#}'` prints nothing

### ISSUE THREAD

**Issue by aaronjensen** [tmux/tmux#3371]
```sh
tmux display-message -p '#{l:#}'
```

As I understand it, it should print `#`, but it prints nothing. Doubling the `##` prints two of them. I don't know of a way to print just a `#`. This seems like a bug, so reporting just in case. 

Just found another case:

```sh
tmux display-message -p '#{l:%}'
```

Am I doing something wrong w/ the literal marker?

**Comment by nicm** [comment]
`tmux display-message -p '##'`

**Comment by aaronjensen** [comment]
Right, but in my instance I am dynamically printing single key presses, and ideally I can do that without having to write escape code. Is there a reason literal doesn’t work for this?

**Comment by nicm** [comment]
I don't know why it doesn't print `#`s, needs debugging...

**Comment by nicm** [comment]
Try this please: 
[x.diff.txt](https://github.com/tmux/tmux/files/9921167/x.diff.txt)

**Comment by nicm** [comment]
Applied this now, thanks!
