### ISSUE TITLE
Crash while deleting the last paste buffer using <prefix>+`-` when the list of all paste buffers is shown

### ISSUE THREAD

**Issue by blurgyy** [tmux/tmux#3373]
### Issue description

Steps to reproduce:

1. In a tmux session with default config, enter copy mode with `<C-b>`+`[`
2. Navigate the cursor and select some text with `v` and copy the selected text with `Enter`
3. Enter list view of all paste buffers with `<C-b>`+`=`, the copied text should show in the list
4. Delete the most recent paste buffer with `<C-b>`+`-`
5. Crash

It can be reproduced with an empty config file on both tmux 3.3a and the latest git build (dbfbd8a195707a8550d59f9576fbbafe1045556c), tested on NixOS and Arch.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  `tmux 3.3a` and `tmux next-3.4`
* Platform (`uname -sp`).
  `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`).
  `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-353151.log](https://github.com/tmux/tmux/files/9921896/tmux-client-353151.log)
[tmux-out-353153.log](https://github.com/tmux/tmux/files/9921897/tmux-out-353153.log)
[tmux-server-353153.log](https://github.com/tmux/tmux/files/9921898/tmux-server-353153.log)

**Comment by nicm** [comment]
This should be fixed in OpenBSD now and will be in GitHub later on, please let me know if you still see any problems. Thanks!
