### ISSUE TITLE
Support purging of paste buffer history 

### ISSUE THREAD

**Issue by ajakk** [tmux/tmux#3374]
Every once in a while I need to copy some kind of secret. These should, for obvious reasons, be completely ephemeral as far as clipboards are concerned as I generally don't want them in memory (let alone easily accessible memory) at all after being pasted.

Could there be a way to limit the paste buffer history to one entry? Or maybe a way to trigger a clearing of the history after pasting via a new hook?

**Comment by nicm** [comment]
Just delete it afterwards?

**Comment by ajakk** [comment]
I am fallible and I'll forget. It would be best if there were a way to do this without an extra interaction from me every time.

**Comment by nicm** [comment]
How should tmux know when to keep and when to delete if you don't want to do anything different to tell it?

**Comment by ajakk** [comment]
> Could there be a way to limit the paste buffer history to one entry? Or maybe a way to trigger a clearing of the history after pasting via a new hook?

I'm requesting a configurable limit to the count of paste history entries, or maybe even a new hook that runs after pasting.

**Comment by nicm** [comment]
Use the existing buffer-limit option or change your paste key binding to add -d.

**Comment by ajakk** [comment]
Thanks! That's about what I was looking for. Sorry for the noise.
