### ISSUE TITLE
kill-session kills more than the session passed as argument

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#3375]
### Issue description
I create two sessions with names
- ftl2685263__1667424914892592235
- ftl2685263

kill-session -t  ftl2685263 kills both sessions. Making the common prefix the suffix fix the problem

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 3.2a
* Platform (`uname -sp`). linux_86_64

**Comment by nicm** [comment]
`kill-session` only kills one session at a time. The rules for `-t` are described in the `COMMANDS` section of the man page.
