### ISSUE TITLE
Can't copy inside tmux popup.

### ISSUE THREAD

**Issue by LintaoAmons** [tmux/tmux#3377]
### Issue description
Can't copy inside tmux popup.

Can copy when in normal panes. But can't in popup windows.

![tmux](https://user-images.githubusercontent.com/95092244/200098367-686a9a8a-c5e2-4570-9ae6-d53c03a544d6.gif)

### Required information

Please provide the following information:

* tmux version: `tmux 3.2a`
* Platform (`Darwin i386`).
* $TERM inside and outside of tmux 
  * inside: screen-256color
  - outside: xterm-256color

**Comment by LintaoAmons** [comment]
I use wezTerm, and I have also tried this in Iterm2, same result~

**Comment by nicm** [comment]
Yes, you can't currently enter copy mode in a popup.

**Comment by bfrg** [comment]
What I currently do is open a new `scratch` session in the popup. This allows me to go into `copy-mode`. Copy/paste works fine then. For example:

```tmux
# Quickly open a scratch pad in a popup window with Alt-Shift-T
bind-key -n -N 'Open a scratch session in a popup window' M-T {
    display-popup -E -w 60% 'tmux attach-session -t scratch 2>/dev/null || tmux new-session -s scratch -c "#{pane_current_path}"'
}
```

It appears from your gif that you're doing something similar. What exactly are you doing in the gif?

**Comment by LintaoAmons** [comment]
```
bind-key -n M-3 run-shell -b "\
    if test 1 -eq #{==:#{session_name},popup} ; then \
        tmux detach-client; \
    else \
        tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h75% -E \"tmux attach -t popup || tmux new -s popup\"; \
    fi\
"
```

I was just showing that when I toggle the popup window (and actually there's also the `popup` session attached just like your `scratch` session) and I think I have already go into the  `copy-mode`, but even though I selected the strings in `copy-mode` but can't copy the selection successfully .

**Comment by bfrg** [comment]
Copy/paste works fine with my snippet above.

Note that you don't need to do the if-check using the shell in your snippet. You can use the `if-shell` command with the `-F` option. This also looks cleaner, though, you might need a recent tmux version for this:

```tmux
bind-key -n -N 'Toggle popup window'  M-3 if-shell -F '#{==:#{session_name},popup}' {
    detach-client
} {
    display-popup -d "#{pane_current_path}" -xC -yC -w 80% -h 75% -E 'tmux attach-session -t popup || tmux new-session -s popup'
}
```

I just tried it and copy/pasting works fine.

**Comment by LintaoAmons** [comment]
Ahhhhhhhhh, I don't know why I can't........

My ideal working flow with one important piece missing!

I tried your snippet but still didn't work for me. Thus I guess it's not the snippet cause this issue?

This is my current `.tmux.conf`: https://gist.github.com/LintaoAmons/b79d866e298c8d7e6744a021a73f21f7

Do you mind take a look?~

**Comment by bfrg** [comment]
Have you tried it again after restarting tmux? And I'm not sure if it has something to do with your key bindings that you defined in `copy-mode`. The ones that use `reattach-to-user-namespace pbcopy`. I don't use OS X, so I can't test it.
