### ISSUE TITLE
running `tmux new-session` from bashrc does not always activate `session-created` hook

### ISSUE THREAD

**Issue by yaronkh** [tmux/tmux#3378]
### Issue description
I configured this hook in my .tmux.conf file:
```
set-hook -g session-created[0] "display-message 'facca'"
```
I execute new tmux session for every new interactive bash session that is executed outside tmux:
```
if [[ -z "$TMUX" ]]; then
    tmux new-session
fi
```

the first time that I run an interactive bash session tmux is executed and the hooked is called.
the second time the hook is not called.

it looks likes a race condition, since if the bash sleep 100 ms before executing the new session, the hook is called:
```
if [[ -z "$TMUX" ]]; then
    sleep 0.1
    tmux new-session
fi

**Comment by nicm** [comment]
Are you sure it is not being run at all and not just that display-message happens before you are attached? Try changing the command to something like `run "date >>/tmp/new_session"` and see if it actually adds to the file.

**Comment by nicm** [comment]
Or try putting the delay in the hook, maybe something like `run -Cd1 "display-message"`.

**Comment by yaronkh** [comment]
actually, I tried that, and that did not help.
