### ISSUE TITLE
[performance] When default-shell is fish, new command run from a fish subshell, not directly from tmux

### ISSUE THREAD

**Issue by sulivanShu** [tmux/tmux#3379]
- tmux 3.3a
- Linux
- st-256color/tmux-256color

Hi,

When default-shell is fish, new command runs from a fish subshell, not directly from tmux.
```
$ tmux -f <(echo set-option -g default-shell /usr/bin/fish) new
$ tmux new-window htop
(...)
─ tmux -f /dev/fd/63/ new
  └─ fish
  └─ fish -c htop
     └─ htop
(...)
```
The problem does not appear when enter the `tmux new-window` command without any other arguments.

When default-shell is bash, new command run directly from tmux.
```
$ tmux -f <(echo set-option -g default-shell /bin/bash) new
$ tmux new-window htop
(...)
─ tmux -f /dev/fd/63/ new
  └─ htop
  └─ bash
(...)
```
When default-shell is fish, creating a new subshell with each new no-shell tmux window consumes resources seemingly unnecessarily.

[tmux-out-2462636.log](https://github.com/tmux/tmux/files/9954536/tmux-out-2462636.log)
[tmux-server-2462636.log](https://github.com/tmux/tmux/files/9954537/tmux-server-2462636.log)
[tmux-client-2462634.log](https://github.com/tmux/tmux/files/9954539/tmux-client-2462634.log)

**Comment by nicm** [comment]
This is something you need to ask the fish developers about.

**Comment by sulivanShu** [comment]
According to https://github.com/fish-shell/fish-shell/issues/9333#issuecomment-1306097153

> tmux runs $SHELL -c htop in both cases, where $SHELL is tmux' default-shell option.
> What you are seeing is that POSIX shells implicitly prepend exec to the last command but fish doesn't, see also https://github.com/fish-shell/fish-shell/issues/6902
> 
> One workaround is to set only default-command to fish and leave default-shell as /bin/sh

```
$ tmux -f <(echo set-option -g default-shell /bin/sh \; set -g default-command /usr/bin/fish) new \; new-window htop
```
It works.

However, it doesn't work with a wrapper like byobu, which runs tmux heterodoxly. On byobu, there is a bug that prevents using `default-shell`.

A partial workaround is to add `set -g default-command 'exec $SHELL'` to your `profile.tmux`.

However, this is a byobu issue, not tmux.

A bug was previously opened on Byobu's bug tracker, if anyone wants to track it.

https://bugs.launchpad.net/byobu/+bug/1995865
