### ISSUE TITLE
Status bar adds a new line every minute when inside a tmux session

### ISSUE THREAD

**Issue by sandeepchittilla** [tmux/tmux#3381]
### Issue description

There is a new status bar line added almost every minute. While the screenshot is of a split pane, it happens even when the pane is NOT split. Screenshot  : 

![image](https://user-images.githubusercontent.com/62606281/200798671-60180989-0985-4249-afab-2af53c43b44b.png)

Steps to reproduce :  
1. Run `tmux`
2. Leave it running and observe

There is a similar older issue which has been marked as closed but with no conclusion : #3168 

### Required information

Please provide the following information:

* tmux version (`tmux -V`) : **tmux next-3.4** built from the latest code on Git

* Platform (`uname -sp`) : **Linux x86_64**
* $TERM inside and outside of tmux (`echo $TERM`) : Outside : **cygwin** Inside : **tmux-256color**
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Logs?

**Comment by sandeepchittilla** [comment]
@nicm is it the tmux-server-xxxx.log file? I may have some sensitive information corporate information in that. Is there a way around? Any particular lines i can grep for you?

**Comment by nicm** [comment]
Yes server log, you can email it to me privately if you like.

**Comment by nicm** [comment]
Most likely this is caused because you have a character in your status line where the terminal and tmux disagree about the width. Try to reproduce without any .tmux.conf (`tmux kill-server;  tmux -f/dev/null new`).

If it still happens with no config, perhaps the terminal does not support automargins and either TERM is incorrectly saying it does, or tmux is not applying the workaround correctly.

**Comment by sandeepchittilla** [comment]
It happens with no config as well, just tried it. Is there a gitter channel for tmux so i can IM you there? Else, I'll have to check with the IT if i can email you the logs

**Comment by nicm** [comment]
You will need to email them.

First try doing `set -as terminal-overrides '*:am@'` in `.tmux.conf` and completely restart tmux (`tmux kill-server`) and see if it helps
