### ISSUE TITLE
Hyperlinks aren't shown in scrollback

### ISSUE THREAD

**Issue by orausch** [tmux/tmux#3383]
### Issue description
This is an issue with the newly added support for escape code hyperlinks: #3240

Hyperlinks show up normally, but disappear when entering scrollback (and/or copy-mode).

### Required information

Please provide the following information:

* tmux version (`tmux -V`): latest master
* platform (`uname -sp`): Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`): outside: `xterm-256color`, inside: `screen-256color`
* config: none/empty config

**Comment by nicm** [comment]
Yes, at minimum the hyperlinks needs to be copied to the cloned screen in `window_copy_clone_screen`, maybe some other bits also.

**Comment by topcat001** [comment]
I don't understand the thumbs-down. Some additional work needed, but it is not impossible.

**Comment by unphased** [comment]
It's impossible to grab hyperlinks in copy-mode. This is going to limit my hyperlink based log-to-code navigation facilities I'm hoping to build. Having hyperlinks to websites or local files in terminal output in general (`ls` already can do this) is really powerful too.

**Comment by nicm** [comment]
I think this is fixed now?

**Comment by unphased** [comment]
Very happy about this getting in, thank you!
