### ISSUE TITLE
sudo user promting for root password

### ISSUE THREAD

**Issue by eng3** [tmux/tmux#3384]
### Issue description

On my system, all users are required to use tmux (via /etc/bashrc "[ -n "$PS1" -a -z "$TMUX" ] && exec tmux") to enforce an automatic session lock.

If a user is using sudo for a long command (ie. sudo bash) and the session locks, it will prompt for the non-privileged user password AND the root password. sudo users typically do not have the root password and thus cannot unlock their session.

Prompting for just the non-root password should be sufficient for a sudo session. If a user used su, I could see a need to prompt for the root password.

Is there anyway to configure tmux so it does not prompt for a root password for a sudo session.
If not, can this be added?

### Required information

Please provide the following information:

* tmux version (`tmux -V`). **2.7**
* Platform (`uname -sp`). **Linux x86_64**
* $TERM inside and outside of tmux (`echo $TERM`). **screen**
* Logs from tmux (`tmux kill-server; tmux -vv new`). **N/A**

**Comment by eng3** [comment]
Actually, now that I look more closely, perhaps this is not a tmux issue.  I have "lock command vlock"

**Comment by nicm** [comment]
tmux just runs the command, it doesn't know what it asks for.
