### ISSUE TITLE
~/.tmux.conf generate "unknown command: activity action" on stderr

### ISSUE THREAD

**Issue by Cbhihe** [tmux/tmux#3386]
### Required information
* tmux version (`tmux -V`): tmux 3.3a
* Platform (`uname -sp`): Linux unknown
* Platform (`uname -r`): 6.0.7-arch1-1
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`)

### Issue description
Not sure this is an issue or just me not grokking how `tmux` should be properly spoken to.
I launch `tmux` from a `gnome-terminal` instance with the following command:

`tmux -T 256,UTF-8  new-session \; split-window -h \; split-window -v \; select-pane -t 0 \; send-keys ' ' C-m \; `

If I don't tack on the last portion of that command: `send-keys ' ' C-m \; ` then pane #0 does not get to display a prompt until I hit Enter on my keyboard. That makes the following message displayed in pane #0
`~/.dotfiles/tmux.conf:<line_nbr>: unknown command: <command>`
disappear and be replaced by the shell prompt.

the <line_nbr> and <command> above stand for whatever line in .tmux.conf does not start with `set -g `.

I share my `~/.tmux.conf` file (~/.tmux.conf -> ~/.dotfiles/tmux.conf) [here](http://paste.c-net.org/BeggingPutting).
I do not believe that is related to any upgrade (my last upgrade was in mid-June 2022). 
I have a hunch that this may be a symptom of something bigger in terms of faulty config.

**Comment by nicm** [comment]
Well yes, `activity-action` is not a command, it is an option...

**Comment by Cbhihe** [comment]
Bad phrasing on my part... Does that mean I should precede much of `~/.tmux.conf`'s lines with `set -g` ?

**Comment by nicm** [comment]
I am completely confused what problem you are having.
