### ISSUE TITLE
Server keeps tty open

### ISSUE THREAD

**Issue by chrysn** [tmux/tmux#3387]
### Issue description

Starting tmux on a TTY keeps that TTY's file descriptor open. Consequently, when the terminal is cleared using SAK (Alt+Print+K, which kills everything on the respective TTY so that the user can be sure to get a genuine login prompt and not enter their credentials into a malicious program the last user left running), the tmux server (and thus everything under it) gets killed unceremoniously. Given that this is pretty much a "hang up" style situation, I'd expect the server to survive that, so that when the user returns, they can continue their work.

```shell
$ cat /proc/4684/comm
tmux: server
$ ls -al /proc/4684/fd
total 0
dr-x------ 2 guest guest  0 Nov 11 14:57 .
dr-xr-xr-x 9 guest guest  0 Nov 11 14:57 ..
lrwx------ 1 guest guest 64 Nov 11 14:57 0 -> /dev/null
lrwx------ 1 guest guest 64 Nov 11 14:57 1 -> /dev/null
lrwx------ 1 guest guest 64 Nov 11 14:57 2 -> /dev/null
lr-x------ 1 guest guest 64 Nov 11 14:57 3 -> 'pipe:[27446]'
l-wx------ 1 guest guest 64 Nov 11 14:57 4 -> 'pipe:[27446]'
lrwx------ 1 guest guest 64 Nov 11 14:57 5 -> /dev/tty1
lrwx------ 1 guest guest 64 Nov 11 14:57 6 -> 'socket:[27447]'
lrwx------ 1 guest guest 64 Nov 11 14:57 7 -> 'socket:[32770]'
lrwx------ 1 guest guest 64 Nov 11 14:57 8 -> /dev/ptmx
```

Then dmesg shows:

```
[  791.769500] sysrq: SAK
[  791.769623] tty tty1: SAK: killed process 4682 (tmux: client): by session
[  791.769637] tty tty1: SAK: killed process 4423 (bash): by session
[  791.769646] tty tty1: SAK: killed process 4089 (login): by session
[  791.769912] tty tty1: SAK: killed process 2869 (startpar): by fd#1
[...] and a few unrelated processes
[  791.771823] tty tty1: SAK: killed process 4089 (login): by controlling tty
[  791.771848] tty tty1: SAK: killed process 4423 (bash): by controlling tty
[  791.771865] tty tty1: SAK: killed process 4682 (tmux: client): by controlling tty
[  791.771872] tty tty1: SAK: killed process 4684 (tmux: server): by fd#5
```

Note that this is not *entirely* reproducible; it appears to work better after a fresh reboot. I have no good idea why that'd be the case, but if I had to guess it might be because the server iterates over processes and picks either the client or the server first, and maybe if the client's killing is processed by the server before the kernel iterates back on it, then the server drops the file descriptor fast enough.

### [edit: added] Context

I found this trying to drill down why I lost my tmux session during an X server crash; not sure it's related to that, but if this were resolved it's one possible cause shaved off the list of possible culprits.

### Ideas at resolution

I don't see why the server would need that around any more, so it should abandon all these connections early, as part of the daemon fork.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux next-3.4` (built from e06c09889c8f56164ddc920d534357357769cf13 in an adjusted Debian package -- but nothing in the diff since then looked suspicious)

<details><summary>probably not important but better to be complete</summary>

* Platform (`uname -sp`): `Linux unknown` (it's a Debian sid amd64)
* $TERM inside and outside of tmux (`echo $TERM`): `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): ``

[tmux-client-4423.log](https://github.com/tmux/tmux/files/9990990/tmux-client-4423.log)
[tmux-out-4425.log](https://github.com/tmux/tmux/files/9990991/tmux-out-4425.log)
[tmux-server-4425.log](https://github.com/tmux/tmux/files/9990992/tmux-server-4425.log)

</details>

**Comment by nicm** [comment]
The tmux server always has the tty fd of all attached clients, that's how it works. Does this still happen if you detach the client first?

**Comment by chrysn** [comment]
As expected after your comment, detaching does protect the server from
the kernel's killing spree.

That's unfortunate over all -- it'd mean that a SAK on any terminal
connected to a TMUX server will automatically tear down the whole
server, and that'd only be worked around by SSH'ing into localhost
(which feels a bit silly).

Is it a fundamental requirement for the server to have them open, an
implementation coincidence or a matter of performance?

**Comment by nicm** [comment]
It is a requirement to have it open for how tmux is implemented.
