### ISSUE TITLE
this simbol: ????????? instead of line to separate panel

### ISSUE THREAD

**Issue by cachafa** [tmux/tmux#3388]
### this simbol: ????????? instead of: I to separate panel

this issues is in tty, in the CWM its fine.

in the command "locale", i have only "C" in all option.

### Required information

Please provide the following information:

* tmux version (`tmux -V`)
tmux OpenBSD-7.2
* Platform (`uname -sp`).
OpenBSD amd64
* $TERM inside and outside of tmux (`echo $TERM`).
in tty outside: vt220, in tty inside:screen; in CWM outside: xterm, in CWM inside:screen
* Logs from tmux (`tmux kill-server; tmux -vv new`).

i am new in IT.

**Comment by krader1961** [comment]
Tmux requires a UTF-8 locale such as "en_US.UTF-8". I would expect "locale -a" to list several such locales you can choose. Since you're currently using the legacy "C" locale,  "en_US.UTF-8" is the appropriate locale to use.

**Comment by krader1961** [comment]
Also, note that you can start tmux with the "-u" option to force it to ignore your locale env vars and assume a UTF-8 locale. You'll need to kill any existing tmux server before running "tmux -u" to see the effect.

**Comment by cachafa** [comment]
Thank you. I will look on the internet(blog) how to do it

**Comment by cachafa** [comment]
Thank you. I will look on the internet how to do it
