### ISSUE TITLE
Can't source files from home directory using ~

### ISSUE THREAD

**Issue by dragon788** [tmux/tmux#339]
Just a note, you CAN use $HOME, but it is somewhat confusing that you can run commands from '~/bin' in 'run' or 'run-shell' commands, but not in the sourcing files.

Tmux version 2.0 (from pi-rho PPA).

**Comment by nicm** [comment]
Works for me.

**Comment by dragon788** [comment]
I wonder if it makes a difference that my tmux config file is being
symlinked from a subfolder inside my home directory, but the file it was
sourcing was not through a symlink.
