### ISSUE TITLE
> tmux always sends ^? for backspace. It works out what key to expect from termios. Make sure stty verase matches what your terminal is configured to send for backspace. I suggest using ^? not ^H.

### ISSUE THREAD

**Issue by poige** [tmux/tmux#3390]
>        tmux always sends ^? for backspace. It works out what key to expect from termios. Make sure stty verase matches what your terminal is configured to send for backspace. I suggest using ^? not ^H.

_Originally posted by @nicm in https://github.com/tmux/tmux/issues/335#issuecomment-197732935_

that's basically why I consider locking out conversation a poorly-thought idea.

So, what I actually wanted to clarify is the difference between OP's "delete" and nicm's "backspace" reply. Delete and backspace are different things as we know. Also delete doesn't work for me in iTerm2 either, have to press ctrl-d as the workaround.

**Comment by poige** [comment]
```
% bindkey | grep char
"^B" backward-char
"^D" delete-char-or-list
"^F" forward-char
"^H" backward-delete-char
"^T" transpose-chars
"^X^F" vi-find-next-char
"^[OC" forward-char
"^[OD" backward-char
"^[[3~" delete-char
"^[[C" forward-char
"^[[D" backward-char
"^?" backward-delete-char```

so, Zsh will send `^[[3~` for Ctrl-D to work and it does work indeed. What's the proper way to have it fixed for using with Tmux?

**Comment by nicm** [comment]
tmux always send `^?` for backspace and `\033[3~` for delete. You will need to ask zsh questions to the zsh developers.
