### ISSUE TITLE
hook_session variable wrong in sesison-closed hook

### ISSUE THREAD

**Issue by Segaja** [tmux/tmux#3391]
### Issue description

I'm trying to build a `session-closed` hook which needs the ID of the session that was closed. According to the man page ( https://man.archlinux.org/man/tmux.1#hook_session ) this is suppose to be contained in the `#{hook_session}` variable. However when I do a simple hook like

```
set-hook -g session-closed "run 'echo \"#{hook_session}\" >> ${HOME}/tmux_debug'"
```

All I get in the `tmux_debug` file is:
```
sh
```

I was expecting the output to be (as the code says: https://github.com/tmux/tmux/blob/master/notify.c#L204 ):
```
$0
```
as this is the ID of my current tmux session.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). => 3.3a
* Platform (`uname -sp`). => Linux unknown  (it is archlinux)
* $TERM inside and outside of tmux (`echo $TERM`). => outsidealacritty ; inside: tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`). => i don't see any verbose output when i execute that

**Comment by Segaja** [comment]
It feels like the issue is that the resulting string from the ID with the `$` prefix is being interpreted by the shell, resulting in `$0` being `sh`. any other following $X is then an empty string.

**Comment by foxxx0** [comment]
That assumption seems correct, when you validate via:
```
set-hook -g session-closed "run \"echo '#{hook_session}' >> /home/segaja/tmux_debug\""
```

I'm questioning the usefulness of the `$` prefix in that variable to be used with hooks, especially when any kind of shell interaction is happening. This requires some quoting and escaping gymnastics and when specifying the numerical ID to other tmux commands, the `$` prefix is not used/allowed either.

**Comment by Segaja** [comment]
Just for reference: 

In my use case I need the session ID without the leading `$`, so I have to exercise some very strange magic to remove the leading `$` sign:

```
set-hook -g session-closed "run \"echo '#{s/\\\\$//:hook_session}' >> /home/segaja/tmux_debug\""
```
