### ISSUE TITLE
Wrong Horizontal and Vertical splits in the context menu

### ISSUE THREAD

**Issue by Solarunit** [tmux/tmux#3393]
### Issue description

I think that Horizontal and Vertical options are wrong in the tmux context menu, like Vertical split does horizontal split and vice versa:

Screenshot:

![](https://i.imgur.com/yEil3qJ.png)

* tmux version: tmux 3.2a
* Platform: Solus
* $TERM inside and outside of tmux: bash: xterm-256color

**Comment by nicm** [comment]
They are definitely correct:
~~~~
        " 'Horizontal Split' 'h' {split-window -h}" \
        " 'Vertical Split' 'v' {split-window -v}" \

**Comment by Solarunit** [comment]
@nicm so, when clicking on **Horizontal Split** you would expect this kind of split?

Screenshot:

![](https://i.imgur.com/j3stMLq.png)

But this is a Vertical Split, you can to it by `<PrefixKey> + %`

**Comment by nicm** [comment]
That is a horizontal split, you can see the panes are laid out horizontally (next to each other).

**Comment by Solarunit** [comment]
Well, I guess the problem with terminology here..
I would personally call this a Vertical Split.

Found this in the wiki page:

>![](https://i.imgur.com/a24Ue6y.png)

___

But looks like I am not alone who is confused, here is screenshot from a 1st tmux-cheat-sheet I googled:

![](https://i.imgur.com/RCiIGEV.png)

They call `<PrefixKey> + %` a Vertical Split :shrug:

**Comment by nicm** [comment]
OK well you can rebind the keys if you want them to be different.

**Comment by nicm** [comment]
Perhaps you should ask vim why their split is the wrong way round?

**Comment by Solarunit** [comment]
:smile: 

Well I let it go :snowflake::snowflake::snowflake: 

___

Anyway, I like that context menu, it makes splits very fast!

**Comment by Hexstream** [comment]
I think both conceptualizations make sense logically. You just have to be consistent within each system.

It's a bit like scrolling direction. In most systems, scrolling "down" means that the _viewport_ goes _down_ while the text technically does not move, with the effect that the _text_ seems to move _up_. But I seem to remember that in emacs, at least traditionally, scrolling "down" means that the viewport does not move but the _text_ goes _down_, which is the other way around. Scrolling "down" in one system is scrolling "up" in the other.

Perhaps the ambiguity could be resolved with an alternative terminology...

**Comment by Solarunit** [comment]
Now I'm curious what's situation with i3wm and others tiling window managers :thinking:
