### ISSUE TITLE
Need #{pane_current_path} to be logical path, for tmux-resurrect

### ISSUE THREAD

**Issue by rltyty** [tmux/tmux#3394]
Hi Tmux team,

Consider I have a logical path `~/tmp/3` which is a symbolic link to a physical path `~/tmp/2/2.1/2.1.1/2.1.1.1` and I have a tmux pane in which the `pwd` is the logical one.

Although `:display-message "#{pane_current_path}"` shows  the physical path, when I split to create another pane, the `pwd` in the new pane is still the logical one, which is good because no one wants to see the tediously long path in every shell prompt. This means the logical pane path can be retrieved or saved to somewhere during new pane creation.

However, when I use tmux-plugins/tmux-resurrect to save and restore a tmux session, all the paths in the restored panes become the physical ones, which is very annoying, because the plugin save code use `#{pane_current_path}`.

[save.sh](https://github.com/tmux-plugins/tmux-resurrect/blob/a2ddfb96b94bb64a7a2e3f5fa2a7c57dce8ad579/scripts/save.sh#L44):
 
`format+=":#{pane_current_path}"`

My question/requirement:

1. Could tmux set logical path (`pwd` in the pane) to #{pane_current_path}?
2. Or is there any other way I can retrieve the logical path to feed tmux-resurrect? Then it can save the logical ones for the panes to be restored later, just like the pane split behavior mentioned above.

Thanks.

**Comment by nicm** [comment]
tmux cannot retrieve logical path for `pane_current_path`. If you use `pane_current_path` for new panes it will be physical too. Logical path will be there only if tmux already knows it and if the shell pays attention to `PWD`.
