### ISSUE TITLE
tmux show picture is blur

### ISSUE THREAD

**Issue by newyorkthink** [tmux/tmux#3395]
### Issue description

I use command timg,viu,chara  show picture in kitty tmux.

when i just use kitty ,timg,viu,chara show pictures is normal
![image](https://user-images.githubusercontent.com/87791643/203957914-036dd8ce-1875-4dca-adfa-2ee9117d8f07.png)

when i run kitty and run tmux.
viu command ,or chara ,timg show pictures is blur
![image](https://user-images.githubusercontent.com/87791643/203958144-9e647347-6359-4154-8f12-80018e81fb38.png)

I set the config screen 256 :
![image](https://user-images.githubusercontent.com/87791643/203958246-fb59211a-048f-4876-80d1-c7b17b14af98.png)

it not work

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
![image](https://user-images.githubusercontent.com/87791643/203958471-1703be7e-f997-4441-acea-07a9245598cc.png)

* Platform (`uname -sp`).
![image](https://user-images.githubusercontent.com/87791643/203958573-481b8741-1dfb-4df6-8257-9473dbe5b75b.png)

* $TERM inside and outside of tmux (`echo $TERM`).
![image](https://user-images.githubusercontent.com/87791643/203958667-89a92262-35dd-4124-81d5-233a6bf6b1cf.png)

* Logs from tmux (`tmux kill-server; tmux -vv new`).
![image](https://user-images.githubusercontent.com/87791643/203958800-24b2148a-5599-44bc-8214-17fbf881e1e1.png)

![image](https://user-images.githubusercontent.com/87791643/203958969-ad693c98-2c83-482a-8d9c-d3bf26b0bbd7.png)

**Comment by newyorkthink** [comment]
this is timg issus
https://github.com/hzeller/timg/issues/95

**Comment by newyorkthink** [comment]
this is chara issus
https://github.com/hpjansson/chafa/issues/116

**Comment by newyorkthink** [comment]
this is viu issus
https://github.com/atanunq/viu/issues/104

**Comment by newyorkthink** [comment]
chara blur too
![image](https://user-images.githubusercontent.com/87791643/203960635-cc8dc0bb-8e63-4c34-8654-ce0493286267.png)

**Comment by nicm** [comment]
tmux does not support images, sorry.
