### ISSUE TITLE
User A using `tmux -S /tmp/pair` results in user B getting "access not allowed" from `tmux -S /tmp/pair attach`

### ISSUE THREAD

**Issue by chriselrod** [tmux/tmux#3396]
Probably related: https://github.com/tmux/tmux/issues/3220

I tried following the suggestions from: https://unix.stackexchange.com/questions/2523/what-are-other-ways-to-share-a-tmux-session-between-two-users

But this did not work either.

I once was able to work collaboratively via one user starting tmux with `tmux -S /tmp/pair` and `chmod`-ing it, and then another running `tmux -S /tmp/pair attach`.
However, this no longer works, resulting in "access not allowed".
How can two people attach to the same session?

**Comment by chriselrod** [comment]
FWIW, I can confirm that this is a change in 3.3a (or 3.3), as using 3.2 downloaded from https://github.com/nelsonenzo/tmux-appimage/releases, this works.

**Comment by nicm** [comment]
Look at  the `server-access` command.

**Comment by YingboMa** [comment]
Could the error message suggest looking into `server-access` as well?
