### ISSUE TITLE
How to handle Ctrl-Enter in modern tmux, called via mintty

### ISSUE THREAD

**Issue by egor7** [tmux/tmux#3398]
### Issue description

For a long time I used tmux 1.8 in centos via git-bash from windows. And it was capable to handle <kbd>Ctrl-Enter</kbd> key sequence brilliantly (one could easily reproduce this by building tmux 1.8 from source):

    [tmux-1.8]$ showkey -a
    Press any keys - Ctrl-D will terminate this program
    ^[[13;5u         27 0033 0x1b
             91 0133 0x5b
             49 0061 0x31
             51 0063 0x33
             59 0073 0x3b
             53 0065 0x35
            117 0165 0x75

But if I switch to the newer version, say even to 1.9 or to the latest one, I start getting something more standard instead:

    [tmux-1.9]$ showkey -a
    Press any keys - Ctrl-D will terminate this program
    ^M       13 0015 0x0d

How to return the previous behaviour back? - how to ask mintty (I believe git-bash use MSYS2's mintty as a virtual term) to send any sequence I can catch and rebing in linux later on? Because of `^[[13;5u` is something you could easily rebing, but `^M` is the same as <kbd>Alt-Enter</kbd>

### Required information

* tmux version (`tmux -V`).
tmux 1.8 vs tmux 3.2a
 
* Platform (`uname -sp`).
Linux x86_64, connected from git-bash (I suspect it is a mintty virtual terminal)

* $TERM inside and outside of tmux (`echo $TERM`).
Outside: `xterm-256color`
Inside 1.8: `screen-256color`
Inside 3.2a: `screen-256color`

* Logs from tmux (`tmux kill-server; tmux -vv new`).
1.8 logs
[tmux-server-341193.log](https://github.com/tmux/tmux/files/10104076/tmux-server-341193.log)
[tmux-client-341191.log](https://github.com/tmux/tmux/files/10104077/tmux-client-341191.log)
3.2a logs 
[tmux-server-341147.log](https://github.com/tmux/tmux/files/10104064/tmux-server-341147.log)
[tmux-out-341147.log](https://github.com/tmux/tmux/files/10104065/tmux-out-341147.log)
[tmux-client-341145.log](https://github.com/tmux/tmux/files/10104066/tmux-client-341145.log)

Tmux was executed by running: `./tmux -vv -Ltest -f/dev/null new`

**Comment by nicm** [comment]
Did you try with `extended-keys` set to `always`?
