### ISSUE TITLE
Questions: How to send text to tmux clipboard?

### ISSUE THREAD

**Issue by mrwensim** [tmux/tmux#3399]
### Issue description

Hi,

I'm trying to copy current working directory path on a remote server to my system clipboard.

I've followed this [clipboard guide](https://github.com/tmux/tmux/wiki/Clipboard) and manage to copy text from tmux on remote server to my system clipboard with the OSC 52 way.

For further customization, I want to add a shortcut key to copy current working directory path on a remote server to my system clipboard too.

I can get the path with `tmux display -p -F "#{pane_current_path}"`, but how can I send this text to the tmux clipboard?

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.3a
* Platform (`uname -sp`).
Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`).
inside tmux: screen-256color-italic
outside tmux: alacritty

**Comment by nicm** [comment]
set-buffer or load-buffer

**Comment by mrwensim** [comment]
Thanks for your answer.
I tried `set-buffer` along with the `-w` option, it works.
