### ISSUE TITLE
Selection on double-click gets un-selected when some other program changes something in another terminal  (in xfce4-terminal)

### ISSUE THREAD

**Issue by yurivict** [tmux/tmux#3400]
### Issue description

Double-clicking on text only selects it until some untrelated change in the screen in xfce4-terminal.
This problem doesn't happen in tmux run in KDE Konsole.

### Required information

Please provide the following information:

    tmux 3.3a
    Platform: FreeBSD amd64
    $TERM inside and outside of tmux: tmux-256color and xterm-256color

**Comment by nicm** [comment]
Doesn't seem like a tmux problem.
