### ISSUE TITLE
OSC 52 within tmux within urxvt

### ISSUE THREAD

**Issue by jayache80** [tmux/tmux#3402]
### Issue description

This is probably a quirk with urxvt, but I'm posing a question here because I think this is the community that might be able to help :)

I use tmux in many environments and terminals and I often use OSC 52 to get text to my system clipboard, which tmux usually handles well by (from what I understand) "forwarding" the OSC 52 sequence to the host terminal (which then sends the text to system clipboard). I often use a `yank` script that basically consists of this (simplified):

    #!/usr/bin/env bash

    # yank text from stdin and print it to stdout with OSC 52 escape sequence

    buf=$(cat "${@}")
    esc="\033]52;c;$(printf %s "${buf}" | base64 | tr -d '\r\n')\a"
    printf "${esc}"

Sending text to the above `yank` script from tmux within a terminal works as expected with Alacritty and Kitty. However, it doesn't seem to make it all the way through to urxvt. The way to get urxvt to handle OSC 52 at all is via an extension script. Something like [this][1]:

```
#! perl

=head1 NAME
52-osc - Implement OSC 32 ; Interact with X11 clipboard
=head1 SYNOPSIS
   urxvt -pe 52-osc
=head1 DESCRIPTION
This extension implements OSC 52 for interacting with system clipboard
Copied from GitHub user parantapa, who also reports most code came from:
http://ailin.tucana.uberspace.de/static/nei/*/Code/urxvt/
=cut

use MIME::Base64;
use Encode;

sub on_osc_seq {
    my ($term, $op, $args) = @_;
    return () unless $op eq 52;

    my ($clip, $data) = split ';', $args, 2;
    if ($data eq '?') {
        my $data_free = $term->selection();
        Encode::_utf8_off($data_free); # XXX
        $term->tt_write("\e]52;$clip;".encode_base64($data_free, '')."\a");
    }
    else {
        my $data_decoded = decode_base64($data);
        Encode::_utf8_on($data_decoded); # XXX
        $term->selection($data_decoded, $clip =~ /c/);
        $term->selection_grab(urxvt::CurrentTime, $clip =~ /c/);
    }

    ()
}
```

In trying to debug this, I've found that while running `tmux` within urxvt the above `on_osc_seq` routine never gets called when OSC 52 sequences occur. However, if I am not in a tmux session, the above `52-osc` script works fine. It's almost as if the OSC 52 sequence doesn't get forwarded from tmux to urxvt in a way that urxvt "understands".

I also have `set-clipboard on` in my tmux.conf which works as expected for most terminals but not urxvt.

Is there a possible configuration issue that would cause my problem?

### Required information

Please provide the following information:

* tmux version: 3.3a
* Platform: Linux unknown
* $TERM inside tmux:  screen-256color
* $TERM outside tmux: rxvt-unicode-256color
* Logs from tmux: attached are logs of a tmux session where I run `echo hello | yank` using the above described configuration (urxvt with the `52-osc` perl script and the above `yank` script)
[tmux-client-191522.log](https://github.com/tmux/tmux/files/10147584/tmux-client-191522.log)
[tmux-out-191524.log](https://github.com/tmux/tmux/files/10147585/tmux-out-191524.log)
[tmux-server-191524.log](https://github.com/tmux/tmux/files/10147586/tmux-server-191524.log)

<details>
<summary>.Xresources</summary>

```
URxvt.iso14755: false
URxvt.iso14755_52: false
URxvt.perl-ext-common: default,resize-font,52-osc
URxvt.resize-font.step: 1
URxvt.scrollBar: false
URxvt.font: xft:DejaVu Sans Mono:size=11

URxvt.scrollTtyOutput: false
URxvt.scrollWithBuffer: true
URxvt.scrollTtyKeypress: true
URxvt.saveLines: 900000

URxvt.transparent:   true
URxvt.shading:       20
```
</details>

<details>
<summary>.tmux.conf</summary>

```
# Remap prefix from C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Use current working directory when opening new windows
bind c new-window -c "#{pane_current_path}"

# Reload config file
bind r source-file ~/.tmux.conf

# Switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Switch panes using prefix,[h,j,k,l]
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes using prefix,M-[h,j,k,l]
bind -r M-h resize-pane -L 5
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5
bind -r M-l resize-pane -R 5

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Don't rename windows automatically
set-option -g allow-rename off

# Renumber windows in sequential order
set-option -g renumber-windows on

# Set scrollback buffer
set-option -g history-limit 10000

# Kill pane without prompting y/n
bind-key x kill-pane

# Eliminate delay after pressing escape
set -s escape-time 0

# Set vi style motions
set-window-option -g mode-keys vi

# Remove preview during prefix,w
bind-key w choose-tree -ZwN

# Copy/paste
set-option -s set-clipboard on
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Move windows left or right
bind-key < swap-window -t -
bind-key > swap-window -t +

# Drag to move windows
bind-key -n MouseDrag1Status swap-window -d -t=

# Potentially needed to make vim look ok in a tmux pane
set -g default-terminal "screen-256color"

# Colours
set-window-option -g status-style bg=default,fg=colour242
set-window-option -g window-status-current-style bg=default,fg=colour252
set -g pane-active-border-style fg=colour246
set -g pane-border-style fg=colour240
```
</detail>

[1]: https://unix.stackexchange.com/questions/629398/does-urxvt-support-the-osc52-escape-sequence

**Comment by jayache80** [comment]
Ok, I believe I'm closer. Per [this][1] I learned that `Ms` was `[missing]` in my tmux session. So I've added this to my .tmux.conf:

    set -as terminal-features ',rxvt-unicode-256color:clipboard'

By monitoring the output from `xsel -op` (primary selection), `xsel -os` (secondary selection), and `xsel -ob` (clipboard), I noticed that running the `yank` script with tmux 3.3a (and copying with tmux's copy mode) was now sending text to somewhere, but to the *primary selection* as opposed to the clipboard. This was progress, but going to the primary selection instead of the clipboard was unexpected. Outside of a tmux session the `yank` script sends text to clipboard only (and not the primary selection).

In debugging the above `52-osc` perl script, I learned that when I run `echo test | yank` outside of a tmux session, `$args` had this value:

    c;dGVzdA==

If I run `echo test | yank` inside of a tmux session, `$args` had this value:

    ;dGVzdA==

Notice that the `c` is missing when done from `tmux`.

I just built master and saw this [has already been addressed][2]. Apparently, in 3.3a, the `c` used to be purposely chopped off of "manual" OSC 52 sequences being passed through but is now preserved. The above `yank` script now works as expected with master branch, however, tmux's *copy mode* doesn't--it missing the `c`, so whenever I copy text using tmux copy mode it goes to the primary selection instead of the clipboard.

How do I get tmux copy mode to send the same kind of OSC 52 sequence (with the `c`) such that it goes the clipboard?

[1]: https://github.com/tmux/tmux/wiki/Clipboard
[2]: https://github.com/tmux/tmux/issues/3192

**Comment by nicm** [comment]
An empty first argument tells the terminal to use its default, you will need to configure your terminal to control what that default is, or modify `Ms` with `terminal-overrides` to force the first argument.

**Comment by jayache80** [comment]
Thank you very much for your assistance!

> you will need to configure your terminal to control what that default is

Since OSC 52 capability is provided by the above `52-osc` extension script, I believe that the implementation there *is* the configuration. So the following patch to that script accomplishes the goal of always sending to the clipboard (even if the argument for which clipboard to send it to is blank, as tmux purposefully does):

```
--- ~/.urxvt/ext/52-osc	2022-12-04 14:40:50.512478192 -0800
+++ ~/.urxvt/ext/52-osc-force-clipboard	2022-12-04 15:16:42.275475617 -0800
@@ -26,8 +26,8 @@
     else {
         my $data_decoded = decode_base64($data);
         Encode::_utf8_on($data_decoded); # XXX
-        $term->selection($data_decoded, $clip =~ /c/);
-        $term->selection_grab(urxvt::CurrentTime, $clip =~ /c/);
+        $term->selection($data_decoded, 1);
+        $term->selection_grab(urxvt::CurrentTime, 1);
     }
     
     close(FH);
```

That can be fleshed out more to actually check if it's blank, and perform a user-configurable option if it is blank (like send to clipboard, or wherever the user would like the "default" to be). I believe this to be the more valid approach.

> or modify Ms with terminal-overrides to force the first argument

Per [this][1], instead of customizing that `52-osc` perl script above, I can instead add this to my .tmux.conf to coerce to `c`:

    set-option -ag terminal-overrides ",rxvt-unicode-256color:Ms=\\E]52;c;%p2%s\\7"

Case closed!

[1]: https://gist.github.com/yudai/95b20e3da66df1b066531997f982b57b
