### ISSUE TITLE
C-c issue with read()

### ISSUE THREAD

**Issue by sandaihu** [tmux/tmux#3403]
Hi,

I'd like to ask some insights about the following `tmux` behaviour.

For example I start `tmux` with the following command:
`tmux new-session 'ls -lh; read -p Enter:; ls; bash';`

In this case if I press `C-c` at the `read`, then the session exits with `[exited]`.

I tried to run the command with an embracing `bash`, but still sending the SIGINT to the `read` exits from the session again.
`tmux new-session 'bash -c "ls -lh; read -p Enter:; ls; bash"';`
Also tried the `set -g remain-on-exit on`, but that just freezes the pane, unbinding `C-c` neither made a difference.

If I first start `tmux` > break the `read` > then properly the internal, client shell session is returned; which I'd expect above as well.

The version I'm running is `3.1c`.

Thanks.

**Comment by nicm** [comment]
When you C-c a shell that is started with a command, it does not return to the shell prompt but instead exits.

**Comment by sandaihu** [comment]
Understood, thanks for the info.
