### ISSUE TITLE
Issue with changing cursor shape via escape sequence

### ISSUE THREAD

**Issue by damnskippy** [tmux/tmux#3404]
Tmux compiled from latest sources on master (1536b7e2).
Currently debugging an issue with changing cursor shape - just checking here to see if this is something to do with my environment, or if others see this too.

Doing `echo -ne "\033Ptmux;\033\033\e[4 q\007\033\\"` inside tmux, and there is no change to the cursor shape.
Doing this outside tmux works fine `echo -ne "\e[4 q"`
Interestingly enough, doing `tmux set -g cursor-style underline` changes the cursor shape correctly.
But the escape sequences don't work -- first noticed it in vim when going to insert mode didn't change the cursor shape, and mistakenly thought it was a vim issue for a good while until I did the echo.

Tried going back to older releases and found tmux 3.2a (https://github.com/tmux/tmux/commit/3b929f332aafa7f1080eacc31feb11ffbb1d1841) to be the last release where this worked (escape sequences change cursor shape), but the next release 3.3 (https://github.com/tmux/tmux/commit/87fe00e8b44901240fc22d7120c1b31e4331f6f5) has the issue.
Started doing a git bisect but ran into build issues halfway into it, but I'm probably not doing this correctly.

Can someone please try the echo above in latest tmux and see if it works for them?

Thanks.

**Comment by krader1961** [comment]
FWIW, using the tmux passthrough sequence to change the cursor is no longer necessary. See https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it. 

Also, works for me. I tested the echo in your comment from inside a tmux session and it changed the cursor from a blinking block to an underline. You should probably kill the tmux server and restart it with `tmux -vvv` to get a server log.

**Comment by damnskippy** [comment]
Thank you for trying this out and the link to the FAQ, I wasn't aware that this was deprecated.
This works for me now.
Much appreciated.
