### ISSUE TITLE
Question: Can I define some sort of "variable" in a complex format definition?

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#3405]
I'm building a highly informative pane title definition. I'm working on the beginning section of it, which has led me to wondering if I can further optimize it. Behold: 

    setw -g pane-border-format ' "#{=/-100/…:pane_title}" #[fg=#7f9f7f]#{s|#{@home}|~|:pane_current_path} #[fg=#6f6f6f]#(pgrep -P #{pane_pid}) #[fg=#7f7fff]#(ps -p "$(pgrep -P "#{pane_pid}" | tr "\n" " " | sed s/.$//)" -o args= | sed -E "s/(.{30})(.{2,})(.{20})$/\1…\3/" | sed -z -e s/\\n/\;/g -e s/.$//)#[fg=#6f6f6f] #{?alternate_on,<Alt Mode>,}

Let me summarize what this does. 

    setw -g pane-border-format ' "#{=/-100/…:pane_title}" 

First segment shows the pane title. This can be set by programs, manually, etc.

    #[fg=#7f9f7f]#{s|#{@home}|~|:pane_current_path} 

Shows the CWD in a light green color. At some point I had to do quite a bit of digging to find out this way of nicely shortening paths within `$HOME` to start with `~`.

    #[fg=#6f6f6f]#(pgrep -P #{pane_pid}) 

Sets fg color to a dim grey. Oh, by the way, 

### The first question pops up here: How can I reset the color to the default fg color for the title?
I couldn't work out what it was so resorted to a subtly dimmer color to explicitly set for the rest of the line. Not ideal but far from actually problematic since I never switch color themes for my setup.

This then shows the pid of the program of interest running in the pane. The actual `#{pane_pid}` is usually a shell, and generally is not useful to know that shell process's pid. Granted, it's not *always* a shell if, say, some specific command is being spawned via script into a pane that'll disappear once it completes, but that is a rare edge case. I'll adjust this to handle that case cleanly in the far future.

    #[fg=#7f7fff]#(ps -p "$(pgrep -P "#{pane_pid}" | tr "\n" " " | sed s/.$//)" -o args= | sed -E "s/(.{30})(.{2,})(.{20})$/\1…\3/" | sed -z -e s/\\n/\;/g -e s/.$//)

This grabs via `ps -p <pid> -o args=` the command of interest being executed as child of the shell as mentioned above. All the sed pipelines after that are for string massaging. Now this brings me to the question.  

I would like to omit either the first pane title section, or this section, if it turns out to be the case that these two "fields" end up comparing equal, in the interest of brevity. I know I can do this by replicating the same code in both sections and doing something like `#{==,pane_title,#(ps -p "$(pgrep...)" -o args= | sed ...)}`. But now I'm running this rather insane bunch of shell code TWICE just to render the pane header. And I can only assume all this runs once for each pane each time tmux renders the panes, which has got to be on a fairly regular basis. 

## Main Question: Is there some sane way I can save the output from some pane variable expansion or expansion shell output to reference again later in the same format string definition?
I don't feel good about hitting the filesystem to do this.

    #[fg=#6f6f6f] #{?alternate_on,<Alt Mode> ,}

For completeness: Last segment just shows whether alt mode is active or not. Not relevant to the question.

------
P.S. I thought of another potential approach which starts to become appealing as the complexity of the format string assembly expands. This would provide a clean way to resolve issues of layout (of which one may argue is what my question is really about):

Maybe what I really want to do is call out to an external process to build the format string and give it to tmux plainly. It would appear that nothing special at all is needed and I could just shove it into a `#()`. I could send in any args I need, e.g. `#{pane_pid}`, `#{pane_title}`, `#{pane_current_path}` as arguments to it. I'd worry about how `#()` spawns a shell to handle it instead of directly forking my program in question but that would be absurd premature optimization. Actually I might have just rubber duckied myself into a clean solution here. As long as nothing weird is going to happen with handling ANSI color codes this should just work like a charm. I'll do some tests.

**Comment by unphased** [comment]
I did some tests following up on the idea I had in my postscript, and although at first I found that tmux gobbles up the color escape sequences, I did realize that simply emitting `#[fg=red]` worked, so... it looks like I might be home free with this.

**Comment by dangh** [comment]
I'm just shooting in the dark here but maybe you can do something like replacing pane_title twice with one? something like

```
#{s|#{E:pane_title}#{E:pane_title}|#{E:pane_title}|:<your format string here>}
```
