### ISSUE TITLE
Issue with #(): newlines inproperly overflow into following arguments even if argument is quoted.

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#3406]
setw -g pane-border-format '#(tmux-pane-border-format-generator "#{pane_title}" "#{s|#{@home}|~|:pane_current_path}" #{pane_pid} #{pane_current_command} #{pane_index} #{window_index} #{session_name} 2> ~/.tmux-pane-border-format-generator.errlog)'

Inside tmux-pane-border-format-generator script: 

    echo "Called with args: 1=$1 2=$2 3=$3 4=$4 5=$5 6=$6 7=$7" >> ~/.tmux-pane-border-format-generator.log

Outputs

    Called with args: 1=echo abc 2=def 3=ghi 4=~/.vim 5=2033884 6=zsh 7=2

When a command containing a newline is run in a pane:

    echo "abc
    def
    ghi"

You can see that the path value which should be $2 has been shifted down to $4 due to the presence of two newlines inside the `#{pane_title}` string. 

I was hoping to work around this by doing some kind of substitution on pane_title instead of just `#{pane_title}` but I cannot find a way to do that (substitute a literal newline in the pane_title...). 

I think this is a bug.

I have tried to change the config to 

    setw -g pane-border-format '#(tmux-pane-border-format-generator $"#{pane_title}" "#{s|#{@home}|~|:pane_current_path}" #{pane_pid} #{pane_current_command} #{pane_index} #{window_index} #{session_name} 2> ~/.tmux-pane-border-format-generator.errlog)'

However this just prepends a `$` to the title everywhere, which hints at me that the `#()` is perhaps not implemented as a shell call.

I kept testing, and 

    setw -g pane-border-format "#(tmux-pane-border-format-generator '#{pane_title}' '#{s|#{@home}|~|:pane_current_path}' #{pane_pid} #{pane_current_command} #{pane_index} #{window_index} #{session_name} 2> ~/.tmux-pane-border-format-generator.errlog)"

(Using double quotes to define the format) does seem to sidestep the problem. This helps a good deal but I kinda wish the newlines would be represented somehow now. They seem to just be dropped.

**Comment by nicm** [comment]
Am I meant to use ESP to see the logs? :-)

**Comment by unphased** [comment]
Good call! I'll grab some logs in a bit
