### ISSUE TITLE
Feature Proposal: Allow send-keys to read keys to send from a file

### ISSUE THREAD

**Issue by nmeum** [tmux/tmux#3407]
I am occasionally (ab)using tmux's `capture-pane` and `send-keys` commands for unit testing of interactive shell programs (e.g. REPLs with readline support). For this purpose, it would be useful if it would be possible to have `send-keys` read keys that should be sent to a pane from a file. Otherwise, one has to deal with shell word-splitting etc. and that is very annoying. A useful format might be having each line, in the file read by `send-keys`, terminated by an `Enter` unless it is escaped with a backslash. So for example, an input file of the form:

```
foo bar
C-d \
baz
```

Would cause the following `send-keys` invocation: `tmux send-keys <…> "foo bar" Enter C-d baz Enter`.

Is there an upstream interest in this feature? If so I could look into creating a patch for it, if not just close this issue.

**Comment by nicm** [comment]
I don't think this is worth the complexity when this should be easy to script. If sh won't do it nicely, use python or perl or one of the million other scripting languages.
