### ISSUE TITLE
double width emoji overlap following characters in prompt when at the bottom of pane in kitty

### ISSUE THREAD

**Issue by longspell** [tmux/tmux#3409]
### Issue description

When tmux is running inside [kitty](https://github.com/kovidgoyal/kitty), double width emoji in PS1 appear fine until the prompt reaches the bottom of the window, at which point they overlap the following characters unless I redraw the pane with `C-b + r` (or `C-a + r` using my remapped keys) or enter/exit copy-mode.

Believing it was an issue with the kitty terminal, I opened an [issue](https://github.com/kovidgoyal/kitty/issues/5745) there, however the kitty developer explained the issue is with the width of the character set by tmux.

The attached screenshot shows the cloud emoji overlapping a `(` character when the prompt reaches the bottom of the pane.

![kitty](https://user-images.githubusercontent.com/60353706/206561640-debf43f7-969e-41b3-b24c-66761392e8ca.gif)

### Required information

Please provide the following information:

* 3.3a
* Darwin i386
* inside: screen-256color, outside: xterm-kitty
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-73700.log](https://github.com/tmux/tmux/files/10189280/tmux-client-73700.log)
[tmux-out-73702.log](https://github.com/tmux/tmux/files/10189281/tmux-out-73702.log)
[tmux-server-73702.log](https://github.com/tmux/tmux/files/10189282/tmux-server-73702.log)

tmux-config:
```
unbind C-b
set-option -g prefix C-a
bind-key -T prefix a last-window
```

**Comment by nicm** [comment]
This is U+FE0F VARIATION SELECTOR-16. iTerm2 has an option to always make characters with this width 2. We should probably do the same, although I think I'd just do it by default and see if anyone complains.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/10189555/x.diff.txt)

**Comment by longspell** [comment]
This fixes the behaviour, thanks!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
