### ISSUE TITLE
TMUX not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by jan-schaeffer** [tmux/tmux#3411]
TMUX still seems to have some issues on 22.04 (Linux x86_64): When I detach a session a enter `tmux -ls` it returns `no server running on /tmp/tmux-1000/default`. Tried this on clean install of both the server and desktop variant. Apt right now has tmux 3.2a but I also tried with 3.3 from the repo. 

$Term inside TMUX is `screen`, outside is `xterm-256color`. Accessing machines via ssh. 

Futhermore, tmux does not read anything from .tmux.conf. Logs are enclosed.
[tmux-client-26876.log](https://github.com/tmux/tmux/files/10216227/tmux-client-26876.log)
[tmux-out-26878.log](https://github.com/tmux/tmux/files/10216228/tmux-out-26878.log)
[tmux-server-26878.log](https://github.com/tmux/tmux/files/10216229/tmux-server-26878.log)

**Comment by nicm** [comment]
From this log, it looks like your shell exited normally, so tmux will exit because there are no longer any panes.

**Comment by jan-schaeffer** [comment]
Somehow works now...
