### ISSUE TITLE
tmux.conf: unknown command: marked

### ISSUE THREAD

**Issue by maxchaos** [tmux/tmux#3413]
### Issue description

As the title says, upon launching a new tmux session, I get an error about an unknown command inside my tmux.config, specifically `{marked}` (see attached minimal configuration file). This command has been there since forever so I believe that the issue appeared after upgrading from v3.2a to v3.3a. The documentation also indicates that this command should still be valid.

Anyway, after loading finishes, tmux opens up a new pane but it is in a messed up state due to the incomplete configuration. For the record, replacing `{marked}` by its equivalent `~` seems to work for the moment. 

[tmux-bug-report.tar.gz](https://github.com/tmux/tmux/files/10235116/tmux-bug-report.tar.gz)

### Required information

* tmux version (`tmux -V`) : tmux 3.3a
* Platform (`uname -sp`) : Linux unknown (Void Linux)
* $TERM inside and outside of tmux (`echo $TERM`) : xterm-kitty (outside), screen-256color (inside)
* Logs from tmux (`tmux kill-server; tmux -vv new`) : See attached files

**Comment by nicm** [comment]
You need to quote strings with {}s now.

**Comment by maxchaos** [comment]
Got it. Thanks for the quick response.
