### ISSUE TITLE
Tabs sent as `\t`

### ISSUE THREAD

**Issue by gnachman** [tmux/tmux#3414]
`tmux list-windows -F "[tab]"` (where there's an actual tab character where I wrote `[tab]`) responds with `\\t` rather than an actual tab.

It is more clearly illustrated with an example:

```
% ./tmux list-windows -F"#{session_name}    #{window_id}"
0\t@0
```

I haven't investigated deeply but it looks like it was caused by commit 7e497c7f2303b29b0f44fe360a78c44ca86b87f9 in this line:

```
utf8_stravisx(&msg, data, size, VIS_OCTAL|VIS_CSTYLE|VIS_TAB);
```

This is a problem for iTerm2 users because it uses raw tabs in tmux integration mode because they won't appear in the various fields it cares about, making the output easy to parse. This breaks tmux integration mode when users upgrade to a newer tmux.

Could the fix to #3401 be narrowed to affect only `capture-pane`?

* tmux version: commit 70ff8cfe1e06987501a55a32df31d1f69acd2f99
* Platform Darwin arm
* $TERM Outside, xterm-256color. Inside, screen-256color
* Logs from tmux: [logs.zip](https://github.com/tmux/tmux/files/10240037/logs.zip)

**Comment by nicm** [comment]
I think we could probably remove `VIS_TAB`.

**Comment by gnachman** [comment]
I did this locally and it fixed the problem.

**Comment by nicm** [comment]
I've changed this now, thanks!
