### ISSUE TITLE
Avoid "No Space Left on Pane" after split-window?

### ISSUE THREAD

**Issue by DocMAX** [tmux/tmux#3416]
When i do a split-window the windows do not balance the free space, so i run quickly out of space.
I can even out after running tmux select-layout tiled after each split.

Is this how it is supposed to be? Can split-window get a flag to balance all windows automatically on creation?
Thanks

**Comment by nicm** [comment]
Use `selectl -E`?

**Comment by DocMAX** [comment]
I forgot to tell you my use case: I created a service running a job in parallel, no interaction myself (only attach if want i want to check and see). So it's fully automated.
