### ISSUE TITLE
Question about pane_current_path

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#3417]
Hi, 

I was wondering if there is a way to truncate the `pane_current_path`

What I mean is:

if I am in home directory to show 
`/Users/xxxx`

if I open new window and I navigate to 

`/Users/xxxx/foo/bar/foobar to show `/bar/foobar`

I hope this makes sense. 

Thanks

lp.

**Comment by nicm** [comment]
See https://github.com/tmux/tmux/wiki/Formats, if you can't do what you want with a format modifier you will need to write a shell script that does it.

**Comment by lanox** [comment]
Thank @nicm  for quick reply, yes I saw that and I was trying to cook something up but couldn't get it to work, hence me asking on here, but I will keep trying.

**Comment by nicm** [comment]
You can have it trim to a length with eg `#{=-15:pane_current_path}` or you could remove a prefix with `#{s|/Users/||:pane_current_path}` but if you want to trim to a length that depends on the number of components you will probably need a shell script.

**Comment by lpuljic24** [comment]
> You can have it trim to a length with eg `#{=-15:pane_current_path}` or you could remove a prefix with `#{s|/Users/||:pane_current_path}` but if you want to trim to a length that depends on the number of components you will probably need a shell script.

Thank you, yes I have tried all the suggestions above you mentioned, however scenario with this 
`#{=-15:pane_current_path}` is where I have  /Users/xxxx/foo/bar/foobar I end up with `oo/bar/foobar`

and the second scenario well we are just trimming `Users` from the path. 

but thanks, I will keep looking.

**Comment by lanox** [comment]
You can have it trim to a length with eg #{=-15:pane_current_path} or you could remove a prefix with #{s|/Users/||:pane_current_path} but if you want to trim to a length that depends on the number of components you will probably need a shell script.

Thank you, yes I have tried all the suggestions above you mentioned, however scenario with this
#{=-15:pane_current_path} is where I have /Users/xxxx/foo/bar/foobar I end up with oo/bar/foobar

and the second scenario well we are just trimming Users from the path.

but thanks, I will keep looking.

**Comment by lanox** [comment]
> You can have it trim to a length with eg `#{=-15:pane_current_path}` or you could remove a prefix with `#{s|/Users/||:pane_current_path}` but if you want to trim to a length that depends on the number of components you will probably need a shell script.

You can have it trim to a length with eg #{=-15:pane_current_path} or you could remove a prefix with #{s|/Users/||:pane_current_path} but if you want to trim to a length that depends on the number of components you will probably need a shell script.

Thank you, yes I have tried all the suggestions above you mentioned, however scenario with this
#{=-15:pane_current_path} is where I have /Users/xxxx/foo/bar/foobar I end up with oo/bar/foobar

and the second scenario well we are just trimming Users from the path.

but thanks, I will keep looking.

**Comment by lanox** [comment]
I have come up something like this, `#(echo $PWD | rev | cut -d'/' -f-2 | rev)` but unfortunately tmux won't update it  on dir change.

**Comment by lanox** [comment]
`#(echo "#{pane_current_path}" | rev | cut -d'/' -f-2 | rev)'` this seems to work the only thing is, refresh on change dir is slow.

**Comment by lanox** [comment]
ah I give up, not sure how to fix this it changes the path  to new window as soon as the new window is created, so I end up with the same path across all the windows...

basically if I have one windows session it works fine, as soon as I create new windows  both windows revert back to home path.

**Comment by dangh** [comment]
@lanox if you want to cut it down to the last 2 components:

```
set-option -wg  @pane_current_path ""
set-option -wga @pane_current_path "#{s"
set-option -wga @pane_current_path   "|.*(/[^/]+/[^/]+)$"
set-option -wga @pane_current_path   "|\\1"
set-option -wga @pane_current_path   "|:pane_current_path"
set-option -wga @pane_current_path "}"

set-option -wg window-status-format "#{E:@pane_current_path}"
set-option -wg window-status-current-format "#{E:@pane_current_path}"
```

`@pane_current_path` is a user option. I break it down to multiple lines for clarity.

**Comment by lanox** [comment]
> @lanox if you want to cut it down to the last 2 components:
> 
> ```
> set-option -wg  @pane_current_path ""
> set-option -wga @pane_current_path "#{s"
> set-option -wga @pane_current_path   "|.*(/[^/]+/[^/]+)$"
> set-option -wga @pane_current_path   "|\\1"
> set-option -wga @pane_current_path   "|:pane_current_path"
> set-option -wga @pane_current_path "}"
> 
> set-option -wg window-status-format "#{E:@pane_current_path}"
> set-option -wg window-status-current-format "#{E:@pane_current_path}"
> ```
> 
> `@pane_current_path` is a user option. I break it down to multiple lines for clarity.

Thanks @dangh  I will give it a try appreciate your reply.
