### ISSUE TITLE
Add support for OSC1337

### ISSUE THREAD

**Issue by nabaco** [tmux/tmux#3419]
### Issue description

I'd like to see support for OSC1337. My specific usecase is for reporting the working directory of the shell to the terminal, using this method `PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'` as described in https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting

Tested and several different platforms. Reading past issues in here, it seems that it is not supported by TMUX and is a new feature request.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 3.2a
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color. Actual terminal used is Tabby, but relevant also for iTerm2
* Logs from tmux (`tmux kill-server; tmux -vv new`): [tmux-client-153839.log](https://github.com/tmux/tmux/files/10321863/tmux-client-153839.log)

**Comment by nicm** [comment]
This seems redundant with OSC 7.

**Comment by nabaco** [comment]
Correct, OSC 7 works for me too. Can you direct me how to enable/use OSC 7 in tmux?

**Comment by nabaco** [comment]
I have tried to use `set-option -g allow-passthrough yes` in `~/.tmux.conf` and then:
```
printf '\033Ptmux;\033\033]7;'$PWD'\a\033\\'
```
but that didn't help

**Comment by nicm** [comment]
`set -as terminal-features '*:osc7'``

And don't use the passthrough sequence.

You need tmux 3.3.

**Comment by nabaco** [comment]
That doesn't seem to work.
I used tmux3.3a (commit https://github.com/tmux/tmux/commit/0b355ae8114511e1ff6359272b164f1cdf718e80)
and put the above line in my tmux.conf and it doesn't seem to work.

**Comment by nicm** [comment]
Show logs please.

**Comment by nabaco** [comment]
[tmux-client-247136.log](https://github.com/tmux/tmux/files/10324603/tmux-client-247136.log)
[tmux-out-247145.log](https://github.com/tmux/tmux/files/10324604/tmux-out-247145.log)
[tmux-server-247145.log](https://github.com/tmux/tmux/files/10324605/tmux-server-247145.log)

**Comment by nicm** [comment]
You need `set-titles` set to `on` as well.

**Comment by nabaco** [comment]
OK, as it seems, the issue was on my side. I was hasty with the experiments, and as it seems, Tabby doesn't support OSC 7. I'll open an issue on them.
But I was able to use OSC 1337 with TMUX passthrough.  I have this in my ~/.bashrc right now, for anyone interested:
```sh
    if [ -z "$TMUX" ]; then
        PS1=${PS1}'\[\e]1337;CurrentDir=${PWD}\a\]'
    else
        PS1=${PS1}'\[\ePtmux;\e\e]1337;CurrentDir=${PWD}\a\e\\\]'
    fi
```

This works with TMUX's default configuration. I've tested it with an empty ~/.tmux.conf and it worked fine.

**Comment by nicm** [comment]
It will work but it will not be accurate when you change the active pane until your shell sends the escape sequence again. You could change `Swd` with `terminal-overrides` to make tmux send 1337 instead of 7 to the outside terminal (you will still need to use 7 inside tmux).

**Comment by nabaco** [comment]
That sounds good to me, can you show me an example how the final configuration would look?
Does it mean that I don't need to send OSC 7 manually from my shell, as TMUX will do it for me?

**Comment by nicm** [comment]
You will still need to send OSC 7 from the shell inside tmux but tmux should update it when you change pane, you will need something like (not tested, look at terminfo(5) for the syntax):

~~~~
set -as terminal-overrides '*:Swd=\E[1337;CurrentDir=%p1%s'

**Comment by nabaco** [comment]
That's my final config, that works with TMUX 3.3:
``` 
set -as terminal-overrides '*:Swd=\E]1337;CurrentDir='
set -as terminal-features '*:osc7'
set -g set-titles on
```
and in ~/.bashrc:
```sh
    if [ -z "$TMUX" ]; then
        export PS1=${PS1}'\[\e]1337;CurrentDir=${PWD}\a\]'
    else
        if [ $(echo "$(echo $TERM_PROGRAM_VERSION | sed 's/\([0-9]\.[0-9]\)[a-z]/\1/') < 3.3" | bc) -eq 0 ]; then
            export PS1=${PS1}'\[\e]7;${PWD}\a\]'
        else
            export PS1=${PS1}'\[\ePtmux;\e\e]1337;CurrentDir=${PWD}\a\e\\\]'
        fi
    fi
```

Thank you very much for the support.
