### ISSUE TITLE
Previous command always shows commands that were run Before tmux opened

### ISSUE THREAD

**Issue by honeyfairy** [tmux/tmux#342]
Cannot see previous commands and cannot scroll up to read a text file

Reference Image: 

![tmux1](https://cloud.githubusercontent.com/assets/17691989/13901405/b9e2a91a-ee33-11e5-905b-91b89cd5883a.PNG)

**Comment by nicm** [comment]
There is an FAQ entry about the terminal scrollback but YMMV.
