### ISSUE TITLE
Backslash inconsistency in option between `3.3a` and `next-3.4`

### ISSUE THREAD

**Issue by MunifTanjim** [tmux/tmux#3420]
### Issue description

```sh
❯ tmux -V
tmux 3.3a
~
❯ tmux set-option -g @test_backslash "a\\,b"
~
❯ tmux show-option -gv @test_backslash
a\,b
❯ tmux set-option -g @test_backslash 'a\\,b'
~
❯ tmux show-option -gv @test_backslash
a\\,b
```

```sh
❯ tmux -V
tmux next-3.4
~
❯ tmux set-option -g @test_backslash "a\\,b"
~
❯ tmux show-option -gv @test_backslash
a\\,b
~
❯ tmux set-option -g @test_backslash 'a\\,b'
~
❯ tmux show-option -gv @test_backslash
a\\\\,b
```

---

What this change intentional?

---

### Required information

Please provide the following information:

* ~tmux version (`tmux -V`).~
* Platform (`uname -sp`): Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`): tmux-256color
* ~Logs from tmux (`tmux kill-server; tmux -vv new`).~

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/10330686/x.diff.txt)

**Comment by MunifTanjim** [comment]
Sorry for the delay. After the patch, the output for `next-3.4` is the same as `3.3a`.
