### ISSUE TITLE
Killing pane created with "tmux split-window -I" crashes tmux server.

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#3422]
### Issue description

tmux will crash if a pane created using `tmux split-window -I` is killed before the `tmux split -I` process is terminated.

To reproduce
1) start new tmux session
2) run a command generating voluminous output into `tmux split-window -I`
   I tested with `find / | tmux split-window -I`
3) The pane containing the output being generated is the active pane.
4) Press PREFIX x (or whatever maps to `kill-pane`)
5) The output pane disappears
6) tmux crashes during redraw

Ideally, the local `tmux split-window -I` command should recognise the output pane is gone, and break the pipe.

### Required information

Please provide the following information:

* tmux version: tmux next-3.4 (built from latest master commit 70ff8cfe)
* Platform (`uname -sp`). Ubuntu 20.04 (x86_64)
* $TERM inside and outside of tmux (`echo $TERM`).  tmux-256color / xterm=256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).  Logs can be provided if you can't easily reproduce the issue.  The logs don't inclu

I rebuilt with GCC debug (-g -O0), and re-tested;  After it crashed and generated a core file, it was analysed with GDB

GDB output.
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./tmux'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000558a0035493e in cmdq_continue (item=0x0) at cmd-queue.c:447
447             item->flags &= ~CMDQ_WAITING;
gdb> p item
$1 = (struct cmdq_item *) 0x0
gdb> where
#0  0x0000558a0035493e in cmdq_continue (item=0x0) at cmd-queue.c:447
#1  0x0000558a00401e50 in window_pane_input_callback (c=0x558a010bfff0, path=0x558a01036a50 "-", error=0, closed=0, buffer=0x558a0107de20, data=0x558a01036a30) at window.c:1551
#2  0x0000558a0036e0e9 in file_fire_read (cf=0x558a0107dda0) at file.c:169
#3  0x0000558a0036ff8c in file_read_data (files=0x558a010c0aa8, imsg=0x7ffe7a4774a0) at file.c:802
#4  0x0000558a003c02e6 in server_client_dispatch (imsg=0x7ffe7a4774a0, arg=0x558a010bfff0) at server-client.c:2768
#5  0x0000558a003aa1b7 in proc_event_cb (fd=9, events=2, arg=0x558a010cae20) at proc.c:102
#6  0x00007f979862de5e in ?? () from /lib/x86_64-linux-gnu/libevent_core-2.1.so.7
#7  0x00007f979862e6ff in event_base_loop () from /lib/x86_64-linux-gnu/libevent_core-2.1.so.7
#8  0x0000558a003aa664 in proc_loop (tp=0x558a010251e0, loopcb=0x558a003c303f <server_loop>) at proc.c:221
#9  0x0000558a003c3024 in server_start (client=0x558a01024300, flags=402718720, base=0x558a01024010, lockfd=5, lockfile=0x558a010251b0 "") at server.c:252
#10 0x0000558a0033f1cb in client_connect (base=0x558a01024010, path=0x558a01023ad0 "/tmp/tmux-0/default", flags=402718720) at client.c:164
#11 0x0000558a0033f5a4 in client_main (base=0x558a01024010, argc=0, argv=0x7ffe7a477b10, flags=402718720, feat=0) at client.c:293
#12 0x0000558a003d1c8b in main (argc=0, argv=0x7ffe7a477b10) at tmux.c:519
gdb>
```

**Comment by nicm** [comment]
This should be fixed now, please try again after GitHub has synced the change over (probably later today).

**Comment by systemmonkey42** [comment]
This has fixed my use case, however the return code from tmux is zero whether the command completed, or was terminated by the pane being killed.

Is it possible for the return code to reflect the early termination?

Thanks

**Comment by nicm** [comment]
Try this please: 
[x.diff.txt](https://github.com/tmux/tmux/files/10369489/x.diff.txt)

**Comment by systemmonkey42** [comment]
That worked perfectly.  I now see exite code == 1 if the command terminated due to the pane being killed.

Thanks

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
