### ISSUE TITLE
Is select-layout broken?

### ISSUE THREAD

**Issue by cfoust** [tmux/tmux#3426]
### Issue description

I cannot get `select-layout` to work. The example from the documentation implies I can copy the layout description and use it in `select-layout`:
```
$ tmux list-windows
0: ksh [159x48]
  layout: bb62,159x48,0,0{79x48,0,0,79x48,80,0}
$ tmux select-layout bb62,159x48,0,0{79x48,0,0,79x48,80,0}
```
Yet when I attempt this (even in a fresh tmux server with no configuraton) I get this result:
<img width="1017" alt="Снимок экрана 2023-01-07 в 7 47 32 AM" src="https://user-images.githubusercontent.com/4588553/211151450-0e030e42-8dff-44c3-94e5-81854fbd5e44.png">

This occurs both on 2.5 and 3.3a. Am I missing something?

### Required information

Please provide the following information:

* `tmux 3.3a` and `tmux 2.5`
* Tested on multiple (`Linux x86_64` and `Darwin arm`)
* $TERM inside and outside of tmux (`echo $TERM`): `xterm-256color`

**Comment by nicm** [comment]
You will need to put it in quotes now.

**Comment by cfoust** [comment]
That worked! This might be worth adding something to the man page about. To my eye it was not obvious why the layout string (which does not appear to have spaces) did not work.

**Comment by nicm** [comment]
I changed the example.Thanks.
