### ISSUE TITLE
UTF-8 characters no longer work in status line

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#3427]
### Issue description

My status line includes unicode symbols which represent various states (disabled panes, session with multiple clients attached etc)

I found that these no longer work with the latest build.

After a little git bisect magic I found the following;

The following commit caused some unicode characters to disappear from the status bar entirely..  
```
commit ef676e1202a4d5c423d5bba2f8ecba1f768d8364
    Remove fallback for wcwidth failure, GitHub issue 3003.
```

The following commit caused the unicode characters to start being rendered as escaped octal (eg `\357\254\211`)
```
commit 6249a4b8666d02e384d48df8516cc9261aa3b3ad
    Merge branch 'obsd-master' - Thomas Adam
```

After some testing with arbirary status lines from the command line and tmux.conf, it appears that the use of `\uXXXX` is longer works correctly for certain code points.

In my specific example, the codepoint is `\ufb09` which renders correctly with `Hack NF` installed from the nerdfonts repository.

If I replace it with '\u00bb' (General code point) or '\uf8e3' (Hack NF extension) it renders correctly.   However using '\fb09' causes the code point to be replaced with the string `\357\254\211`

Also, I just realized, the commands
```
echo $'\u00bb'
echo $'\uf8e3'
echo $'\ufb09'
```
will display three symbols on putty (without tmux)
but will only display the first two symbols when using the latest TMUX
(Using a build before #6249a4b8666d02e384d48df8516cc9261aa3b3ad will result in displaying all three symbols)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).  (range of versions from GIT master)
* Platform (`uname -sp`).  Ubuntu 20.04
* $TERM inside and outside of tmux (`echo $TERM`).  xterm-256color / tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).  Can be made available on request.

**Comment by nicm** [comment]
We'll have to do what was originally suggested in issue 3003.

**Comment by nicm** [comment]
Try this please: 
[y.diff.txt](https://github.com/tmux/tmux/files/10369589/y.diff.txt)

**Comment by systemmonkey42** [comment]
That worked perfectly, thanks!

**Comment by nicm** [comment]
Applied, thanks!
