### ISSUE TITLE
Reissue: slow startup under MSYS2/Cygwin

### ISSUE THREAD

**Issue by iamloci** [tmux/tmux#3428]
### Introduction

On Windows, when using systems such as MSYS2 and Cygwin, tmux takes a relatively long time to start; on the order of seconds.

This is basically a rereport of [this issue](https://github.com/tmux/tmux/issues/1121), but it's been bugging me for the past few days, so I decided to look into a bit more. 

### Additional Information

From what I can tell, the delay occurs in the tmux client code, when it attempts to connect to a socket file which already exists, but does not have any associated sessions. That is, there's no problem when a session already exists, or when tmux is creating an entirely new socket file.

The delay stems from how Windows handles failed TCP handshake processes within Winsock's connect() function. On most Unix-like system, connect() returns almost immediately when the initial socket connection fails, but Windows goes through a series of timeouts and automatic retries. The issue occurs with the tmux builds of both MSYS2 and Cygwin, since their sys/socket.h layer is just a relatively thin layer over Winsock.

Many of the variables surrounding the TCP connection process used to be configurable, but Microsoft, in their infinite wisdom, has been steadily removing the user's ability to modify them, especially on desktop targets.

The only way I have found to mitigate the tmux startup issue is by lowering the maximum SYN retransmissions, as in the following command, which sets the relevant SYN property to 2.

In admin Powershell: `Set-NetTCPSetting -SettingName "InternetCustom" -MaxSynRetransmissions 2`

Heuristically, I've found that each retransmission takes about a half a second, and Windows 10 enforces a minimum value of 2 for this property. And since tmux always tries to connect twice in this situation, even with the manual mitigation, the best case is that tmux will take around 2 seconds to start. (`0.5 second per SYN retransmission * 2 retransmissions * 2 tmux connection attempts`)

Since this is a Windows API thing, you can see the results with other programs as well, such as `telnet`.

### Reproduction and Comparison

Results obtained with `time tmux -v -c 'exit'` using tmux 3.3.a-1 from MSYS2. `$TERM` was `xterm-256color` outside of tmux, and `tmux-256color` inside. Compare the results between the below contexts. The first four are for comparison, with the last two demonstrating the actual issue.

Creating a new socket file (MaxSynRetransmissions=2)

```
# OUTPUT
real    0m0.207s
user    0m0.015s
sys     0m0.046s

# CLIENT LOG EXCERPT
1673178810.026877 client started (1986): version 3.3a, socket /tmp/tmux-197609/default, protocol 8
1673178810.027019 on MINGW64_NT-10.0-19045 3.3.6-341.x86_64 2022-12-09 18:33 UTC
1673178810.027048 using libevent 2.1.12-stable (poll); ncurses 6.3
1673178810.027090 flags are 0x18010000
1673178810.027115 socket is /tmp/tmux-197609/default
1673178810.028506 trying connect
1673178810.028696 connect failed: No such file or directory
1673178810.028759 lock file is /tmp/tmux-197609/default.lock
1673178810.029466 flock succeeded
1673178810.029497 got lock (6)
1673178810.029565 trying connect
1673178810.029926 connect failed: No such file or directory
1673178810.039016 add peer 0x800073760: 7 (0x0)
```

Creating a new socket file (MaxSynRetransmissions=4)

```
# OUTPUT
real    0m0.206s
user    0m0.015s
sys     0m0.031s

# CLIENT LOG EXCERPT
1673179284.674962 client started (2086): version 3.3a, socket /tmp/tmux-197609/default, protocol 8
1673179284.675103 on MINGW64_NT-10.0-19045 3.3.6-341.x86_64 2022-12-09 18:33 UTC
1673179284.675130 using libevent 2.1.12-stable (poll); ncurses 6.3
1673179284.675171 flags are 0x18010000
1673179284.675193 socket is /tmp/tmux-197609/default
1673179284.676607 trying connect
1673179284.676807 connect failed: No such file or directory
1673179284.676871 lock file is /tmp/tmux-197609/default.lock
1673179284.677582 flock succeeded
1673179284.677634 got lock (6)
1673179284.677728 trying connect
1673179284.680046 connect failed: No such file or directory
1673179284.688293 add peer 0x800073760: 7 (0x0)
```

Creating a session when one already exists (MaxSynRetransmissions=2)

```
# OUTPUT
real    0m0.059s
user    0m0.000s
sys     0m0.046s

# CLIENT LOG EXCERPT
1673179158.513030 client started (2046): version 3.3a, socket /tmp/tmux-197609/default, protocol 8
1673179158.513174 on MINGW64_NT-10.0-19045 3.3.6-341.x86_64 2022-12-09 18:33 UTC
1673179158.513205 using libevent 2.1.12-stable (poll); ncurses 6.3
1673179158.513246 flags are 0x18010000
1673179158.513267 socket is /tmp/tmux-197609/default
1673179158.514844 trying connect
1673179158.515701 add peer 0x80007b770: 6 (0x0)
```

Creating a session when one already exists (MaxSynRetransmissions=4)

```
# OUTPUT
real    0m0.055s
user    0m0.046s
sys     0m0.015s

# CLIENT LOG EXCERPT
1673179429.924271 client started (2141): version 3.3a, socket /tmp/tmux-197609/default, protocol 8
1673179429.924419 on MINGW64_NT-10.0-19045 3.3.6-341.x86_64 2022-12-09 18:33 UTC
1673179429.924447 using libevent 2.1.12-stable (poll); ncurses 6.3
1673179429.924487 flags are 0x18010000
1673179429.924508 socket is /tmp/tmux-197609/default
1673179429.925898 trying connect
1673179429.926810 add peer 0x80007b770: 6 (0x0)
```

The last two tests are instances of where the issue actually presents itself. For these, note the jumps in the log timestamps, following the 'trying connect' lines.

Creating a session when one doesn't already exist, and when the socket file already exists (MaxSynRetransmissions=2)

```
# OUTPUT
real    0m2.220s
user    0m0.030s
sys     0m0.015s

# CLIENT LOG EXCERPT
1673178868.644218 client started (1996): version 3.3a, socket /tmp/tmux-197609/default, protocol 8
1673178868.644352 on MINGW64_NT-10.0-19045 3.3.6-341.x86_64 2022-12-09 18:33 UTC
1673178868.644380 using libevent 2.1.12-stable (poll); ncurses 6.3
1673178868.644423 flags are 0x18010000
1673178868.644444 socket is /tmp/tmux-197609/default
1673178868.646088 trying connect
1673178869.654134 connect failed: Connection refused
1673178869.654269 lock file is /tmp/tmux-197609/default.lock
1673178869.655200 flock succeeded
1673178869.655275 got lock (6)
1673178869.655403 trying connect
1673178870.657534 connect failed: Connection refused
1673178870.669820 add peer 0x80007b770: 7 (0x0)
```

Creating a session when one doesn't already exist, and when the socket file already exists (MaxSynRetransmissions=4)

```
# OUTPUT
real    0m4.260s
user    0m0.000s
sys     0m0.015s

# CLIENT LOG EXCERPT
1673179355.124926 client started (2095): version 3.3a, socket /tmp/tmux-197609/default, protocol 8
1673179355.125068 on MINGW64_NT-10.0-19045 3.3.6-341.x86_64 2022-12-09 18:33 UTC
1673179355.125101 using libevent 2.1.12-stable (poll); ncurses 6.3
1673179355.125142 flags are 0x18010000
1673179355.125162 socket is /tmp/tmux-197609/default
1673179355.126608 trying connect
1673179357.149248 connect failed: Connection refused
1673179357.149427 lock file is /tmp/tmux-197609/default.lock
1673179357.150992 flock succeeded
1673179357.151106 got lock (6)
1673179357.151291 trying connect
1673179359.173503 connect failed: Connection refused
1673179359.188498 add peer 0x80007b770: 7 (0x0)
```

###

Unfortunately, at this point, I don't really have any ideas for any workarounds or fixes, but perhaps this information can be of use to someone else who is able to figure something out. Thanks!

**Comment by sskras** [comment]
Reminds the #1121 circa 2017.

**Comment by nicm** [comment]
This seems like one for the Cygwin or Windows developers, there is not much tmux can do here.

You could run tmux with a script to remove the socket if no server, perhaps something like:
~~~~
pgrep -q tmux || rm /tmp/tmux-$(id -u)/default
tmux new
