### ISSUE TITLE
Strange output on tmux attach

### ISSUE THREAD

**Issue by jturner** [tmux/tmux#3429]
### Issue description

When running `tmux attach` the following commands are being sent to tmux. I'm guessing it has to do with commit https://github.com/tmux/tmux/commit/a41a92744188ec5c8a8d4ddc100ec15b52d04603. This is using Terminal on macOS 13.1.

```
10;rgb:f54f/f54f/f54f
11;rgb:0000/0000/0000
```

If I have a shell open on attach I can see them being printed, otherwise they are sent to the running process like mutt.

.tmux.conf
```
unbind C-b
bind C-a send-prefix
bind -n C-k send-keys -R \; clear-history

set -g prefix C-a
set -g set-titles off
set -g status-fg black
set -g status-bg white
set -g status-right ' '
set -g default-command "exec /bin/ksh -l"

new -d -n mutt
neww -d -n porters
neww -d -n hackers
```

### Required information

Please provide the following information:

* tmux openbsd-7.2 (latest snap 1/8)
* OpenBSD amd64
* xterm-color

**Comment by nicm** [comment]
Show tmux logs please.

**Comment by nicm** [comment]
Actually, never mind. I tried this with Terminal.app this morning and it appears it terminates OSC 10 and 11 with BEL which for some reason I did not expect. This should be fixed in tty-keys.c r1.164, please test. Thanks!

**Comment by jturner** [comment]
That fixed it. Thank you!
