### ISSUE TITLE
Fix for 3401 broke tmux-picker.

### ISSUE THREAD

**Issue by jmeurin** [tmux/tmux#3430]
[The fix for issue 3401](https://github.com/tmux/tmux/commit/70ff8cfe1e06987501a55a32df31d1f69acd2f99) seems to break https://github.com/RTBHOUSE/tmux-picker, as it now shows the escape codes instead of highlighting:

cmd-kill-session.o     cmd-show-prompt-history.c  \033[30m\033[48;5;202m\033[1ms\033[m\017\033[30m\033[43m\033[1mdoc2\033[m\017man.awk       tty.o

It works at https://github.com/tmux/tmux/commit/1536b7e206e51488c37379df22b8c58ef3febc28 and fails at https://github.com/tmux/tmux/commit/70ff8cfe1e06987501a55a32df31d1f69acd2f99.

tmux version: top of tree (9b1ea8b1)
Platform: Linux
$TERM: xterm-256color in shell, tmux-256color in tmux

**Comment by jmeurin** [comment]
Yes it does, thanks!

**Comment by systemmonkey42** [comment]
Will this patch be part of GIT?

I've personally fixed tmux-picker by removing the line where it re-imports the environment using
```
eval "$(tmux show-env -g -s | grep ^PICKER)"
```
The environment is ALREADY SET, so this (a) is redundant, and (b) replaces the correct environment with the sanitized version.

**Comment by nicm** [comment]
Sorry I forgot about this, I have changed this now - I don't see any real need to escape nonprintable characters.
