### ISSUE TITLE
[MacOS] iTerm2 Hexcode 0x1 to jump to the start of a line corresponds to prefix

### ISSUE THREAD

**Issue by owittek** [tmux/tmux#3434]
### Issue description

I'm using tmux with iTerm2 and on MacOS it's natural to be able to jump to the start or end of a line by holding command and pressing the left or right arrow key. To emulate this behavior inside of iTerm2 you have to set keymappings that send hex codes (see https://stackoverflow.com/a/29403520).

The hex code to jump to the start of the line happens to be 0x1 and it corresponds to the hex code being sent to send the tmux prefix. This leads to command + left arrow to first call the prefix and pressing the left arrow a second time actually jumps to the beginning of the line. I found this out by googling and reading the [this article](https://thurlow.io/macos/2018/04/13/how-to-forward-command-shortcuts-to-iterm-as-ctrl-shortcuts.html) describes sending the hex code 0x1 to send the tmux prefix.

### Required information

Please provide the following information:

* tmux version: tmux 3.3a
* Platform: Darwin arm
* $TERM: screen256-color (inside) and xterm256-color (outside)
* Logs from tmux: not relevant for this issue

**Comment by nicm** [comment]
I don't know what this is telling me?

**Comment by owittek** [comment]
> I don't know what this is telling me?

I'm assuming that this isn't the desired behavior as the hex code of the prefix should not correspond to the hex code of a default macOS action. Not sure if there's a workaround, if it's an issue of tmux or a wrong handling by iTerm2 but as I assume the first I decided to open an issue here.

**Comment by nicm** [comment]
ASCII 1 is the character code for `C-a`, if you send that to tmux it will treat it as `C-a`.

**Comment by owittek** [comment]
> ASCII 1 is the character code for `C-a`, if you send that to tmux it will treat it as `C-a`.

Oh I see, makes sense and indeed I have the prefix set to C-a. But I'm not sure how to deal with that properly as it's only an issue when I'm using tmux.

**Comment by nicm** [comment]
Either change your prefix in tmux or change the start-of-line binding in your shell and other programs and configure iterm2 to send that key instead of C-a.

**Comment by nicm** [comment]
Most shells let you go to start or end of line with C-Left/C-Right, so why don't you make iTerm2 send those instead?

**Comment by owittek** [comment]
Thanks for all your help @nicm, I went back to the stackoverflow post I linked at the top and found people having the same issue as me. The most satisfying solution was replacing the hex code sequences with the Escape sequences OH and OF as described in a comment below this answer: https://stackoverflow.com/a/10485061

<img width="439" alt="Screenshot 2023-01-12 at 22 15 42" src="https://user-images.githubusercontent.com/57495944/212182712-a7b34e48-bde0-4f91-bb93-0dd1d2c506fe.png">

Closing this issue but I hope this information helps someone else.

**Comment by nicm** [comment]
\033[OH is Home and \033[OF is End.
