### ISSUE TITLE
Passthrough escape sequence

### ISSUE THREAD

**Issue by XXiaoA** [tmux/tmux#3435]
### Issue description
I tried to passthrough escape sequence following the https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it. But it doesn't work. 

https://user-images.githubusercontent.com/62557596/212245290-8a7a83f5-5023-4d2f-bbbd-d1ece513c84e.mp4

<br>

The code I ran: `printf "\033Ptmux;\033\033]1337;SetUserVar=Nvim_Colorscheme=R3J1dmJveCBEYXJr\007\033\\"` and ` printf "\033]1337;SetUserVar=Nvim_Colorscheme=R3J1dmJveCBEYXJr\007"`
And check :https://github.com/wez/wezterm/issues/2945

### Required information

Please provide the following information:

* tmux version (`tmux -V`).  `tmux 3.3a`
* Platform (`uname -sp`). `Linux unknown` (Arch)
* $TERM inside and outside of tmux (`echo $TERM`). outside: `xterm-256color` inside: `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
You need to enable it with `allow-passthrough`.

**Comment by XXiaoA** [comment]
OK, thank you!
