### ISSUE TITLE
3.3a on macOS - wrong key mapping

### ISSUE THREAD

**Issue by PrometheusPi** [tmux/tmux#3436]
### Issue description

Using tmux 3.3a on macOS Ventura 13.1, build with Mac Ports 2.8.0 on M1 Pro Hardware, I get a strange key mapping. 
For example: 
 - the backspace key does not work but instead adds spaces
 - the Up key does not iteratively go through the previous entered commands, but prints them (partially) to the prompt. This results in a weird string mix up of previous commands. 

In the underlying `zsh` shell, everything works as expected. 
 
Using tmux 3.2a on an Intel CPU with the same operating system behaves normally. The Intel Mac shows `screen` for `$TERM` while the M1 Pro shows  `xterm-256color`. 

### Required information

* tmux version 3.3a
* platform Mac OS 13.1
* $TERM inside `tmux-256color` and outside `xterm-256color`
* no logs from tmux

**Comment by nicm** [comment]
You have probably built tmux against a version of ncurses which has `tmux-256color` but not added `tmux-256color` to the system ncurses, so builtin macOS programs don't know about it.

Look at the top of this issue: https://github.com/tmux/tmux/issues/3218
