### ISSUE TITLE
pane-colours gets washed when pane is swapped and brought back

### ISSUE THREAD

**Issue by poetaman** [tmux/tmux#3437]
### Issue description
Consider we have a window for which we set some pane-colours. When the pane is swapped and brought back to the same window, it doesn't inherit the window's pane-colours anymore. Here are steps to reproduce:

1. In a terminal window-1 launch a tmux client ``$ tmux -f /dev/null -vv new``.
2. From another window-2 run ``$ zsh test-panecolours`` (check the file contents below).
3. See the activity in the tmux client attached to terminal window-2 (it will last for 24 seconds). The pane which had inherited window colors, does not anymore.

Contents of file ``test-panecolours``
```
# Set color of window 0 of session 0
# We never set pane colors (-p) for this pane
# (which is in 0:0.0 slot at the moment)
# Only window color is changed, which it will correctly inherit here
# to lose it again
tmux set-option -w -t 0:0.0 pane-colours\[1\] "#888888"
sleep 4
# This will correctly show inherited window color #888888
tmux send-keys -t 0:0.0 'echo "This RED should print \e[31mGRAY\e[0m (#888888), and remain \e[31mGRAY\e[0m "' C-m
sleep 4

# Create session 1 and put green color #00ff00 in it's color 1 (red)
tmux new-session -d
tmux set-option -p -t 1:0.0 pane-colours\[1\] "#00ff00"

# Now swap panes 0 of sessions 1 and 0
tmux swap-pane -d -s 0:0.0 -t 1:0.0
# Show the color of pane, it will correctly show the #00ff00
tmux send-keys -t 0:0.0 'echo "This RED should be \e[31mGREEN\e[0m (#00ff00)"' C-m
sleep 4

# Lets put blue #0000ff in it's color 1 (red)
tmux set-option -p -t 0:0.0 pane-colours\[1\] "#0000ff"
# It will correctly turn the color 1 to blue #0000ff for this pane
tmux send-keys -t 0:0.0  'echo "Prior RED, and this should be \e[31mBLUE\e[0m (#0000ff) now"' C-m
sleep 4
# Lets swap the panes again, and see what happened to color 1 there
tmux swap-pane -d -s 0:0.0 -t 1:0.0
# It no longer inherits window color gray for color 1
sleep 4
tmux send-keys -t 0:0.0  'echo "Why is this and prior RED, not \e[31mGRAY\e[0m (#888888) again?"' C-m
sleep 4

tmux kill-server
```

### Required information

Please provide the following information:

* tmux version: tmux next-3.4
* Platform: Darwin arm
* $TERM: xterm-256color outside, tmux-256color inside
* Logs from tmux (`tmux kill-server; tmux -vv new`):
[tmux-client-84873.log](https://github.com/tmux/tmux/files/10419490/tmux-client-84873.log)
[tmux-out-84875.log](https://github.com/tmux/tmux/files/10419491/tmux-out-84875.log)
[tmux-server-84875.log](https://github.com/tmux/tmux/files/10419492/tmux-server-84875.log)

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/10425356/x.diff.txt)

**Comment by poetaman** [comment]
@nicm Thanks, it is fixed now.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
