### ISSUE TITLE
Strange character pasted when clicking status-right

### ISSUE THREAD

**Issue by wsxarcher** [tmux/tmux#344]
When I click with the mouse on the status-right, for example the clock, or sometimes in a precise point of another pane, it paste "#<ffffffff>" and ""?#?" on the current selected pane.

https://asciinema.org/a/eud88mdij6t9coed2pfewsoq6

**Comment by ThomasAdam** [comment]
Turn off `set-clipboard`

**Comment by ThomasAdam** [comment]
Turn off 'set-clipboard'

**Comment by wsxarcher** [comment]
Thank you!

```
set-option -g set-clipboard off
```
