### ISSUE TITLE
[v3.3a] `tmux display -p "#I"` returned wrong window index

### ISSUE THREAD

**Issue by clarkwang** [tmux/tmux#3441]
### Issue description

For example, with `tmux new sh -c 'tmux display -p "#I"; sleep 60' \; new-window sh -c 'tmux display -p "#I"; sleep 60'`, both windows output `1`.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

   v3.3a

* Platform (`uname -sp`).

   macOS (x86)

* $TERM inside and outside of tmux (`echo $TERM`).

   - inside: screen-256color
   - outside: xterm-256color

**Comment by nicm** [comment]
This is behaving as intended, it uses the current window.

**Comment by clarkwang** [comment]
Is there a way for each window's shell to get the window index?

**Comment by nicm** [comment]
You can use `-t$TMUX_PANE` if you are inside tmux.
