### ISSUE TITLE
Need a way to disable automatic selection of first menu item

### ISSUE THREAD

**Issue by Hexstream** [tmux/tmux#3442]
* tmux version (`tmux -V`): `tmux next-3.4` (built from latest commit `c4a6f403bb9d7c24c291f01dee9572bb4b784096` with no patches applied)
* Platform (`uname -sp`): `Linux unknown` (Debian 11)
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color` inside, `xterm-256color` outside.
* Logs from tmux (`tmux kill-server; tmux -vv new`): Please use provided `menu.conf`.

Hello,

I am using [a rather extensive menu system](https://github.com/Hexstream/status-quo.hexstream.expert/tree/master/assets/tools/tmux/config/open).

To select menu items, I _always_ use hotkeys, and _never_ use the arrow keys.
Furthermore, the first menu item is _almost never_ more likely to be what I want to use over the other menu items.
Also, I like to highlight hotkey mnemonics in my menu items, and highlighting the first menu item obscures that.

The [change](https://github.com/tmux/tmux/blob/master/CHANGES) introduced by `tmux 3.2` is thus entirely undesirable for my use-case:

> Start menu with top item selected if no mouse and use mode-style for the selected item.

I actually tried enabling the mouse with `set -g mouse`, but this does not actually disable the behavior.
Furthermore, I don't actually want to enable explicit mouse support anyway, because:

1. I have no intention of ever using the mouse with tmux anyway, except select/middle-click-paste, which already works without explicit mouse support;
2. Explicitly enabling the mouse actually makes some unwanted behavior changes.
Try selecting text with and without `set -g mouse` and you should see differences.

I also _do not_ want to change the `mode-style`.

Please try this `menu.conf` with `tmux -f menu.conf`:

```
set -s @mnemonic-style 'bold'

bind m menu -T 'Test menu' -x P -y P \
     '#[#{@mnemonic-style}]E#[default]nable mouse ' e { set -g mouse } \
     '#[#{@mnemonic-style}]D#[default]isable mouse' d { set -g mouse 0 }
```

So, I think **it would be really great if there was a simple option for disabling automatic selection of the first menu item**.
Maybe something like `set -g autoselect-first-menu-item 0`?
Or maybe even the other way around, don't autoselect by default, and then `set -g autoselect-first-menu-item` to enable.

And perhaps this should completely ignore mouse support, as it already accidentally does.

**Comment by nicm** [comment]
It means menus opened by the mouse rather than keyboard.

I think the most generally useful thing would be a flag to `display-menu` to give the default-selected item, where you could do `-` or something to have none selected.

**Comment by Hexstream** [comment]
Great idea, I love that approach!

I think "no selection" would be the best default, since there is no particular reason to assume that the first item is a better default selection than any other menu item, but I don't mind passing an extra option to each menu to disable that.

**Comment by nicm** [comment]
No, the default is staying as it is.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/10464926/x.diff.txt)

**Comment by Hexstream** [comment]
Works perfectly!! Thank you!!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
