### ISSUE TITLE
Setulc: difference between terminal-overrides vs. modifying terminfo database

### ISSUE THREAD

**Issue by ddickstein** [tmux/tmux#3444]
### Version information
* tmux 3.1c
* Linux x86_64
* `$TERM` inside tmux: `tmux-256color`
* `$TERM` outside tmux: `xterm-256color`

### Issue description
I modified the terminfo entry for `tmux-256color` to include `Setulc`:
```
$ infocmp -x | grep Setulc
        Setulc=\E[58\:\:2\:\:%p1%{65536}%/%d\:\:%p1%{256}%/%{255}%&%d\:\:%p1%{255}%&%d%;m,
```
This does not produce colored underlines. However, if I instead add it to `terminal-overrides` in my `~/.tmux.conf` as follows:
```
set-option -ga terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m,'
```
Then colored underlines work properly. Is this expected? I'd have thought that `terminal-overrides` would be taken in conjunction with the terminfo and that providing capabilities in either place would be fine from tmux's perspective.

**Comment by nicm** [comment]
Why are you doubling the :s in terminfo?

**Comment by ddickstein** [comment]
Good catch, that was a mistake. It doesn't appear to fix the issue though - here's my updated output from infocmp:

```
$ infocmp -x | grep Setulc
        Setulc=\E[58\:2\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&%d\:%p1%{255}%&%d%;m,
```

**Comment by nicm** [comment]
If you test it with eg tput Setulc 12345|cat -v, what doea it show?

**Comment by ddickstein** [comment]
`^[[58:2:0:48:57m`

**Comment by nicm** [comment]
That is fine. You need to change the entry for the TERM outside tmux though, `tmux-256color` is only used by programs inside tmux not by tmux itself.

**Comment by ddickstein** [comment]
Oh I see - so `terminal-overrides` is meant to communicate additional lines to append to the terminfo of the terminal that tmux is interpreting it to be in, not to the `tmux-256color` definition? That does seem to work btw, so I'm closing this issue. Thank you!

**Comment by unphased** [comment]
Hi sorry to barge in here but can you point me to what referenced you used to learn that underlines can be colored and all that stuff? I'm the author of this SO question https://stackoverflow.com/questions/58774897/how-can-i-find-documentation-knowledge-mentorship-ancient-tomes-for-terminal-def

It appears like theres' been a lot of nice new advancements. I can already see by emitting raw ansi codes that strikethrough, curled underlines, and also colorized underlines all have been implemented in my term of choice (Alacritty), but none of the termcap/terminfo/infocmp related documentation would have any hints related to what the names of capabilities might be for me to use to plumb through both tmux and nvim (in the process of ditching vim now so at least I don't have to also make vim work)...

Do you have any tips? I am pretty convinced at this point that starting to just reverse engineer by reading source code will do me more good than googling around.

**Comment by nicm** [comment]
tmux's extensions are here: https://man.openbsd.org/OpenBSD-current/man1/tmux.1#TERMINFO_EXTENSIONS

Some of them have made it into some upstream terminfo(5) entries: https://github.com/ThomasDickey/ncurses-snapshots/blob/master/misc/terminfo.src#L5517

Everything xterm supports (which is a lot) is documented here: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html

Other terminals have their own documentation for their extensions, for example: https://iterm2.com/documentation-escape-codes.html

I have no knowledge of how vim is configured, you'll need to ask the vim developers or look at the vim manual for that...

**Comment by Hexstream** [comment]
_**This is gold in bars!!** Thank you!!_
