### ISSUE TITLE
Minor issue in man page regarding semicolon parsing examples

### ISSUE THREAD

**Issue by clarkwang** [tmux/tmux#3445]
### Issue description

In man page it says:

~~~
However, a trailing semicolon is also interpreted as a command separator, 
for example in these sh(1) commands:

    $ tmux neww\\; splitw

Or:

    $ tmux 'neww;' splitw
~~~

Here `tmux neww\\; splitw` should be `tmux neww\; splitw`?

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

   3.3a

**Comment by nicm** [comment]
Fixed, thanks.
