### ISSUE TITLE
Killing tmux pane kills system.

### ISSUE THREAD

**Issue by ivandimitrov8080** [tmux/tmux#3446]
### Issue description

Closing a tmux pane (by typing exit into it or by pressing C-b-x)  causes most running programs to crash.
Programs that crash: brave-browser, st, pavucontrol, sxhkd...
Programs that don't crash: dwm

I can close a terminal running tmux, but closing tmux is a no-no.

This happens on artix linux both with the pacman version of tmux as well as the git version compiled from source (not using AUR, but manually cloning and compiling as per the instructions).

Not sure how to get logs, and which logs to get.

### Required information
* tmux next-3.4
* Linux localhost 6.1.6-artix1-1 #1 SMP PREEMPT_DYNAMIC Thu, 19 Jan 2023 21:37:40 +0000 x86_64 GNU/Linux
* st-256color, tmux-256color
* Killing the server kills my computer.

**Comment by nicm** [comment]
Unless these programs are running inside tmux this is unlikely to be a problem with tmux.

**Comment by ivandimitrov8080** [comment]
@nicm The programs are started with GNU parallel.

Here's how most of them start in my `.xinitrc`:

```
autostart_dir=$(xdg-user-dir AUTOSTART)
parallel -j0 ::: ${autostart_dir}/* &
echo $! > "${autostart_dir}/autostart.pid"

xrdb -merge "$HOME/.Xresources"
exec dwm
```

I have a bunch of bash scripts in my autostart directory and when I `startx`, which runs `.xinitrc` they all run.

Here's the contents of my autostart dir:

```
❯ ls .config/autostart
autostart.pid  bingwp  brave  dunst  dwmblocks  jack  picom  pulseaudio  st  sxhkd  xkbmap  xrandr
```

So I do have a terminal that starts when I log in, so I thought it's related, but it's not.

When I start a new terminal and open tmux from there, killing a pane inside tmux started from the new terminal kills all other programs as well.

It is definitely tmux-related by what I can see.

**Comment by nicm** [comment]
tmux cannot kill programs that are not running inside tmux.

**Comment by systemmonkey42** [comment]
At a guess, you have a bash logout script which kills tasks you started in the autostart folder...

**Comment by ivandimitrov8080** [comment]
@systemmonkey42 

That was it.

When I killed the tmux pane, it executed the `.zlogout` script that kills all autostart programs.

I thought it would execute only when I'm actually logging out, you know?

Thanks for the help.

**Comment by ivandimitrov8080** [comment]
A workaround:

By default tmux starts a login shell, which causes it to execute `.zlogout` on exit. To change that behaviour you have to edit either `~/.tmux.conf` or `~/.config/tmux/tmux.conf` by adding in the following line:

```
set -g default-command "${SHELL}"
```

Source: [Arch Wiki](https://wiki.archlinux.org/title/tmux#Start_a_non-login_shell)
