### ISSUE TITLE
beginning and end of line keys not working

### ISSUE THREAD

**Issue by alxsimon** [tmux/tmux#3448]
### Issue description

Hi, sorry if the answer is straightforward but I have been banging my head on this for hours.

Outside tmux either ctrl + A or Home work to go to beginning of line (idem for end of line).
I am using alacritty and zsh on Fedora 37.

Inside tmux, using ctrl + A sends ^A and Home does a weird uppercase thing and enters some kind of mode I can only exit with ctrl + C.

Outside tmux Home sends ^[[H
Inside tmux Home sends ^[[1~

my [tmux.conf](https://github.com/tmux/tmux/files/10494120/tmux.txt)

Any pointer to where the issue might be would be greatly appreciated.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 3.3a
* Platform (`uname -sp`). Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). 'xterm-256colors' / 'tmux-256colors' 
* Logs from tmux:
[tmux-client-367678.log](https://github.com/tmux/tmux/files/10494143/tmux-client-367678.log)
[tmux-out-367680.log](https://github.com/tmux/tmux/files/10494145/tmux-out-367680.log)
[tmux-server-367680.log](https://github.com/tmux/tmux/files/10494146/tmux-server-367680.log)

**Comment by nicm** [comment]
Run `cat` inside tmux and check what you see when you press the keys. `Home` should send `^[[1~`.

It sounds like your shell is not configured correctly if it does not recognise it.

**Comment by alxsimon** [comment]
yes Home correctly sends `^[[1~` inside tmux

**Comment by alxsimon** [comment]
ok I see, I managed to map the keycodes in my zshrc for home and end.

Howether I still have the issue of ctrl+A printing a `^A` instead of going to the beginning of line.
Do I also have to remap those? This should work by default no?

**Comment by nicm** [comment]
tmux is sending ^A so it is doing its job... are you sure you haven't got zsh configured for vi keys or something instead of emacs?

**Comment by alxsimon** [comment]
Not that I know of no. The weird thing is that zsh is behaving correctly outside of tmux. Outside of tmux `^A` behaves correctly as beginning-of-line.

**Comment by alxsimon** [comment]
ok found the issue I think for anyone having the same problem.
Even if emacs mode is the default in zsh, vi mode can be triggered automatically if `$EDITOR` or `$VISUAL` contain vi (https://serverfault.com/questions/844215/remote-zsh-and-moving-to-beginning-of-line-gives-a-print). (which in my case is nvim).
So I have to explicitly put `bindkey -e` in my .zshrc .

**Comment by krader1961** [comment]
@alxsimon, that would seem to be only half the story since you claim it works outside of tmux but not inside a tmux session. So somehow you've configured the environment to have a different`EDITOR` or `VISUAL` env var inside a tmux session than outside of tmux.

**Comment by alxsimon** [comment]
It seems so but I can't find any reason for that, those two variables are set to `nvim` in both cases through my `.profile` file, which is then sourced in my `.zshrc`.  ¯\(°_o)/¯

**Comment by alxsimon** [comment]
Anyway, thanks a lot for the quick answers! Feel free to close the issue as this seems to be more an issue with zsh than with tmux.
