### ISSUE TITLE
Control mode signalling

### ISSUE THREAD

**Issue by flowchartsman** [tmux/tmux#3449]
### Issue description

I'm writing a (Go) persistent plugin framework for Tmux using control mode with the following workflow:

1. command in tmux.conf runs `run -b <framework binary> spawn`
2. binary checks for session `__framework`
3. if not found, calls `tmux new -d -E -c $TMPDIR -s __framework -n __framework <framework binary> control`
4. new binary instance is now in its own session and spawns control-mode listeners for every existing session along with every new session (cleaning then up as necessary). It sends events from each session back to the central `__framework` session by using a shared channel. This allows a tiered approach where each session gets a listener that can dispatch tasks back to the central listener.

The idea being that the framework binary remains resident and can gather state and external information and explicitly create popups containing tools or menus in response to user requests.It works great, actually, except that there doesn't seem to be a way for the control mode client to receive any kind of meaningful message from the user client that it can use to determine what to display and where.

What I would like to be able to do is have a keybinding in the user sessions that signals the persistent control worker somehow so that it knows they want a popup for searching history versus, say a popup menu to configure some value. But I can't figure out any way for any client to reliably send a message or cause a control mode event that is meaningful. Is there any way whatsoever to do this? If not, could we get one? I feel like control mode has a lot of possibility for nifty stuff like this.

Popups also require referencing the client directly, and getting the origin client/session/window/pane is actually quite difficult, though I believe I can work around that. I just need an event that can somehow tell the controller what functionality to invoke.

But perhaps I'm missing something?

### Required information

Please provide the following information:

* tmux version (`tmux -V`). **3.3a**
* Platform (`uname -sp`).  **Darwin-Arm**
* $TERM inside and outside of tmux (`echo $TERM`)- outside: **xterm-256color**  inside: **screen-256color**

**Comment by nicm** [comment]
You could try using a format subscription. So have your key bindings modify a user option and then the control client subscribe to for example `#{@myvar}`.

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/Control-Mode#format-subscriptions

**Comment by nicm** [comment]
You may find format subscriptions are too slow or that you need a global one (which we don't have but could possibly add). The other option without changing tmux would be to use an out-of-band mechanism to signal, so have your program also listen on a named pipe, Unix domain socket or poll a file.

**Comment by flowchartsman** [comment]
I messed with format subscriptions and couldn’t make them work, however I didn’t see this option, so that’s good, I’ll give it a shot.Why would they be too slow?

As far as out-of-band communications, my goal was to avoid process churn or having a dedicated “sender binary”, but I’m already running X tmuxes to get session info,  so might as well try it that way.

**Comment by nicm** [comment]
Format subscriptions are only updated once a second so they may feel unresponsive when a key is pressed.

**Comment by flowchartsman** [comment]
Given that they only update once every second, I think even a global format subscription would probably be too slow for my use. I do feel as if there's probably some use to some kind of immediate signaling mechanism, so I'll punt to you as to what to do with it. Rather than implement entirely new functionality, however, I did notice that `display-message` does nothing when targeted to a control mode client, perhaps it could generate something like

```
%message %client-id %session-id %window-id %pane-id message
```
Where they are filled by the message origin context.

Instead? Aside from the matter of getting the right client, that would solve my use-case quite neatly and allow for a lot of similar flexibility besides.

In any case, I have a path forward regardless, so feel free to close this if the lift is too heavy for the benefit.

**Comment by nicm** [comment]
Good idea, try this please: [tmux-message.diff.txt](https://github.com/tmux/tmux/files/10567821/tmux-message.diff.txt)

**Comment by nicm** [comment]
`display-message` takes a format so you can send the window pane etc yourself. I suggest giving your message a unique prefix though.

**Comment by flowchartsman** [comment]
Yes, this seems to work well!

### Normal Session:
```
$ tmux display-message -c /dev/ttys003 -F "!PREFIX!||#{session_id}||#{client_name}||#{window_id}||#{pane_id}"
```

### Control mode session:
```
%message !PREFIX!||$0||/dev/ttys000||@0||%0
```
I'd call it good here, only I can't figure out how to programmatically get the name of the client to send the message to. The way I have this set up now, the control mode client is the only control-mode client of a known session name, but I cannot find a way to select on this.

Ideally I'd be able to do
`display-message -c  #(list-clients -F "#{client_name}" -t <known_session_name> -f <filter to select on control mode>) "<formatted message>`

but there are a couple problems:

1. `#()` is for shell commands, and I can't figure out a way to interpolate tmux commands from the manpage (if there is one). This isn't a huge problem, since I can always call tmux from the shell, but it would be nice not to have to.
2. list-clients doesn't support `-f`, so I can't select on `client_control_mode`

Hopefully there is a way to do this without needing to reach into every session and add a variable that contains the control mode client name. I might have also missed something.

**Comment by nicm** [comment]
I have applied this to OpenBSD now, will be in GitHub later. Thanks!

Have the client put itself in a user option, either globally or per session when it sees `%session-created`?

Or add `-f` to `list-clients`...

**Comment by flowchartsman** [comment]
> Or add -f to list-clients...

I mentioned this above, but, unless I'm reading this wrong, that's not an option to `list-clients`:

```
const struct cmd_entry cmd_list_clients_entry = {
	.name = "list-clients",
	.alias = "lsc",

	.args = { "F:t:", 0, 0, NULL },
	.usage = "[-F format] " CMD_TARGET_SESSION_USAGE,

	.target = { 't', CMD_FIND_SESSION, 0 },

	.flags = CMD_READONLY|CMD_AFTERHOOK,
	.exec = cmd_list_clients_exec
};
```

**Comment by flowchartsman** [comment]
Unless you meant "add" as in "make a PR that adds `-f` functionality to `list-clients`.  Which, I mean, I suppose I could...

**Comment by nicm** [comment]
Yes I meant make a PR.

**Comment by nicm** [comment]
756591b4ca28089879ef785bde3a6fb30e9f5943 added it to the others.

**Comment by flowchartsman** [comment]
PR issued.

```
$ ./tmux -Ltest list-clients
/dev/ttys009: 0 [80x25 xterm-256color] (attached,focused,UTF-8)
/dev/ttys011: 0 [80x xterm-256color] (attached,focused,control-mode,UTF-8)

$ ./tmux -Ltest list-clients -f '#{client_control_mode}'
/dev/ttys011: 0 [80x xterm-256color] (attached,focused,control-mode,UTF-8)
```

**Comment by flowchartsman** [comment]
Just to wrap up, I _do_ need to shell out to `tmux` make that command? Or is there a way to interpolate the results of `list-clients` directly into a binding without shelling out?

**Comment by nicm** [comment]
You'll need to use the shell. If there was an each-client format modifier like `P`/`W` for panes and windows you could maybe do it internally but there isn't one.

**Comment by flowchartsman** [comment]
Yah, I had a go at adding one, right until I got down to `cmd_find_state`, at which point I was forced to re-think my life. I guess we can call this issue done now, unless you want to keep it open for other reasons.

**Comment by nicm** [comment]
Try this to add `L` similar to `P` and `W`: [format-client.diff.txt](https://github.com/tmux/tmux/files/10661591/format-client.diff.txt)

You can use this with `run-shell` to set the target to the client you want, for example something like:
~~~~
run -C 'some-tmux-command -t #{L:some-expression-to-match-one-client}'
~~~~

**Comment by flowchartsman** [comment]
confimed working, with the rather impressive
`tmux run -C "display-message -c '#{L:#{?#{&&:#{client_control_mode},#{==:#{client_session},sessionname}},#{client_name},}}' PREFIX||message"`

**Comment by nicm** [comment]
Good stuff, applied to OpenBSD now, will be in GitHub later on. Thanks!
