### ISSUE TITLE
Excessive clone/vfork during status-line updates

### ISSUE THREAD

**Issue by pragma-** [tmux/tmux#3452]
In a comment on another issue, @nicm said:

              You could run your `#()` as long running processes, either separate from tmux and setting a user option or leave them as child processes but make them continually add new lines rather that exiting. That would avoid `fork` entirely.

_Originally posted by @nicm in https://github.com/tmux/tmux/issues/3352#issuecomment-1280342882_
            
I have been struggling with this. I want to eliminate forking completely from my status-line.

I used to have `#(cat /proc/loadavg)` in my `status-right`. I've since replaced this with a script that opens `/proc/loadavg` once and then repeatedly prints its contents to stdout along with a 5 second sleep on every iteration. This has eliminated one clone/vfork. However, the status-line itself continues to clone/vfork on every `status-interval` (which I've set to 5).

I've tried emptying the status-line by setting `status-right` and `status-left` both to empty strings. There are no `#()` anywhere. Yet tmux still does one clone/vfork sequence on every `status-interval` update. Only by setting `status` to `off` does the forking stop.

I have 10+ tmux sessions running on my system. Tmux is increasing my PIDs by 10+ every `status-interval` even without any `#()` commands in the status-line. This is causing my PIDs to reach the 4 millions and wrap around within days. I'd much, much prefer not to have this many forks happening every few seconds.

How can I entirely stop tmux from forking on status-line updates, even without any `#()` in the status-line? I just want my PIDs to be sane again, and to not have 20+ syscalls (SYS_clone and SYS_vfork) happening every `status-interval`.

tmux 3.2a
Linux x86_64

**Comment by nicm** [comment]
tmux does not fork unless you ask it to so you still have a #() or similar somewhere. Use strace to see what the child process is doing.

**Comment by pragma-** [comment]
I have set `status-right` and `status-left` both to "". There is nothing in them. Tmux still clone/vforks on every `status-interval`. When I set `status` to `off` then the clone/vfork stops.

The only place I have `#()` in my .tmux.conf is `set -g set-titles-string "(#S) #(whoami) #I:#W"`.  But this does not appear to be relevant since the clone/vforking stops when I set `status` to `off`. Does the `status` also stop the titles string from updating as well?

**Comment by nicm** [comment]
Well, you've reached the limits of my ESP powers so until you are willing to post logs or strace, there is not much more I can tell you.

**Comment by pragma-** [comment]
Can you provide me with a `strace` command that will give you what you are looking for, please? It spews a lot of output and I do not know which section or filters or what output you want. `strace` doesn't output anything interesting unless I add `-f` to follow forks. Do you want me to just collect `strace -f tmux -o strace.log` and send you that `strace.log` file after leaving tmux open for a couple of `status-interval` updates?

**Comment by nicm** [comment]
Yes, you need -f something like:
~~~~
tmux kill-server
strace -vtttfostrace.out tmux new
~~~~
Then wait a bit for it to fork a few times then exit, try not to do anything much else while waiting or it will clutter the file.

You can attach strace to a running tmux server instead if you prefer, that will avoid all the noise at startup.

I may not be able to look at it until tomorrow but if you look for clone and exec you may be able to see what it is running.

Or tmux's own logs may tell you, look for job_run and other job related logging.

**Comment by pragma-** [comment]
Thank you. I will investigate the strace. I was previously using auditd to track the fork syscalls to tmux. I did not know what was causing my PIDs to climb so high so fast. I initially thought that replacing the `#(cat /proc/loadavg)` with a script that stays open would resolve this, but ... 

I will look through the strace and tmux logs to see if I can figure something out. If I cannot, I'll post the strace logs here later. Either way, I will return to this issue to post an update.

**Comment by pragma-** [comment]
It is the only remaining `#()` I had in my .tmux.conf, as mentioned in my previous comment, `set -g set-titles-string "(#S) #(whoami) #I:#W"` that is causing the fork. I did not realize this was updated at the same interval as `status-interval`. As per the tmux manpage:

```
    status-interval interval
             Update the status line every interval seconds.  By default, updates will occur every 15 seconds.  A setting of zero disables redrawing at interval.
```
I had thought this was specifically for the status line. I was led astray because the forks were happening at the exact same interval as the `status-interval` setting so I focused my `#()` attention on `status-left` and `status-right`.

I have removed the `#(whoami)` from `set-titles-string`. The long-running `#(loadavg)` script is working well without forking. I'll go ahead and close this issue as invalid. Sorry for wasting your time.

```
$ strace -p 4076668 --trace=fork,clone,vfork,/exec -ttfvsudo strace -p 4076668 --trace=fork,clone,vfork,/exec -ttfv
03:07:37.594089 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4109815, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
03:07:41.060100 clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLDstrace: Process 4109819 attached
, child_tidptr=0x7f3b67461a10) = 4109819
[pid 4109819] 03:07:41.064806 execve("/bin/sh", ["sh", "-c", "whoami"]) = 0
[pid 4109819] 03:07:41.069509 vfork(strace: Process 4109820 attached
 <unfinished ...>
[pid 4109820] 03:07:41.069715 execve("/usr/bin/whoami" <unfinished ...>
[pid 4109819] 03:07:41.070730 <... vfork resumed>) = 4109820
[pid 4109820] 03:07:41.070770 <... execve resumed>) = 0
[pid 4109820] 03:07:41.080059 +++ exited with 0 +++
[pid 4109819] 03:07:41.080193 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4109820, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
[pid 4109819] 03:07:41.080601 +++ exited with 0 +++```
