### ISSUE TITLE
Removing effect of Ctrl-F5 and Ctrl-F6 in tmux

### ISSUE THREAD

**Issue by TryerGit** [tmux/tmux#3453]
* tmux version (`tmux -V`). tmux 3.0a
* Platform (`uname -sp`). Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). screen-256color

Hello,

I have a different meaning/command for <kbd>CTRL-F5</kbd> and <kbd>CTRL-F6</kbd> in my .vimrc.

When I open vim within tmux, these two keybindings seem to be intercepted by tmux leading to capitalizing the word under the cursor. 

Please see gif:

![tmuxvim](https://user-images.githubusercontent.com/70434658/215002217-e485ea61-e383-4adb-9787-0df05e96fc46.gif)

How is it possible to have tmux not intercept these keystrokes and pass them untouched to the underlying vim instance so that the command specified in the .vimrc is executed?

My .tmux.conf is:

```
set-option -g base-index 1
set-option -g renumber-windows on
setw -g pane-base-index 1
bind r source-file ~/.tmux.conf \; display "Reloaded!"
set -g default-terminal "screen-256color"
setw -g pane-border-style fg=green,bg=black
setw -g pane-active-border-style fg=white,bg=yellow
set -g status-justify centre
setw -g mode-keys vi
bind-key % split-window -h -c '#{pane_current_path}'
bind-key \" split-window -v -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'
```

I have tried having the following additional lines in my .tmux.conf:

```
unbind -n C-F5
unbind -n C-F6
```

but they don't seem to make any change.

Thank you.

**Comment by nicm** [comment]
This is a problem with vim, it is not interpreting what tmux sends for these keys correctly, or your key mappings are incorrect.

**Comment by TryerGit** [comment]
Inside a pure vim session started from a WSL terminal <kbd>CTRL-F5</kbd> emits `^[[15;5~` and <kbd>CTRL-F6</kbd> emits `^[[17;5~`

Inside a vim session started from a tmux session started from a WSL teminal, I obtain the very same emissions.

**Comment by nicm** [comment]
There you go then, tmux is sending the same thing, vim is misinterpreting it.

**Comment by nicm** [comment]
Try setting TERM to tmux-256color inside tmux and see if vim works it out.

Also make sure TERM outside tmux is correct for the outside terminal.

**Comment by TryerGit** [comment]
> Try setting TERM to tmux-256color inside tmux and see if vim works it out.
> 
> Also make sure TERM outside tmux is correct for the outside terminal.

In my .tmux.conf at root, I had:

`set -g default-terminal "tmux-256color"`

in place of 

`set -g default-terminal "screen-256color"`

Then, in `.bashrc` I had:

`[ -z "$TMUX" ] && export TERM=tmux-256color`

in place of 

`[ -z "$TMUX" ] && export TERM=xterm-256color`

With this setting, starting vim within Tmux renders the screen unusable with display of random characters all over the screen.

Let me try to create a MWE and open an issue with vim folks and link to this issue.

**Comment by nicm** [comment]
So you were setting TERM outside tmux to tmux-256color? One of those -z should be -n.

**Comment by TryerGit** [comment]
> So you were setting TERM outside tmux to tmux-256color? One of those -z should be -n.

Thank you so much! This exactly fixed the issue with <kbd>CTRL-F5</kbd> working just fine as in my .vimrc. If it is not too much to ask -- could you briefly explain the difference between -z and -n? I possibly picked it up from stackoverflow and got my tmux configuration to work nicely with Vim for LaTeX but recently I seem to have encountered this trouble. Glad to have it resolved nonetheless. Any online resource / document about the difference between -n and -z would be useful too!

**Comment by nicm** [comment]
Do "man test" and it will explain the operators or https://www.man7.org/linux/man-pages/man1/test.1.html.
