### ISSUE TITLE
Text area in characters height and wdith swapped

### ISSUE THREAD

**Issue by kiwichris** [tmux/tmux#3457]
### Terminal query CSI 1 8 t Height and Width Swapped

The set up is:

1.  MacBook running Terminal
2. SSH to FreeBSD
3. Tmux session running on FreeBSD
4. Connection in tmux pane using `telnet` to `ser2net`
5. `ser2net`connected to embedded hardware running RTEMS via USB UART connections
6. Add debug code to print as hex the results of RTEMS sending the `CSI 1 8 t` request 

The MacBook has Terminal sessions to each tmux version in tabs in the same Terminal window so the size is the same. Both machines report the same size using the `stty` command:
```
$ stty -a
speed 9600 baud; 99 rows; 586 columns;
  ...
```

[CTL seqs](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Device-Control-functions) defines the command as:

>   Ps = 1 8  ⇒  Report the size of the text area in characters.
>          Result is CSI  8 ;  height ;  width t

Changing the `TERM` environment variable did not change the results.

I have reviewed CHANGES and nothing indicated this is a valid issue and has been fixed.

## FreeBSD 11 with Tmux 2.7
```
$ telnet cs-ser-2 30006
Trying 10.10.5.11...
Connected to cs-ser-2
Escape character is '^]'.
rtems [/etc] # cd /etc

1b 5b 38 3b 39 39 3b 35 38 36 74
rtems [/etc] #
```

The height is `39 39` and the width is `35 38 36`

## FreeBSD 13 with Tmux 3.2a
```
$ telnet cs-ser-2 30006
Trying 10.10.5.11...
Connected to cs-ser-2
Escape character is '^]'.
rtems [/etc] # cd /etc        

1b 5b 38 3b 35 38 36 3b 39 39 74 
rtems [/etc] # 
```
The height is now `35 38 36` and width is `39 39` which looks like it is swapped.

**Comment by nicm** [comment]
https://github.com/tmux/tmux/commit/68dc9af9ac1a8ea332c82fd510b01c46602fa03a

**Comment by kiwichris** [comment]
Thanks for quick response. Good to know it is fixed.
