### ISSUE TITLE
[3.3a] display-menu's `-y <position>` does not work

### ISSUE THREAD

**Issue by clarkwang** [tmux/tmux#3458]
### Issue description

For example I have this in tmux conf:

~~~
bind  M  menu -x 10 -y 10 -T " Press q to quit " \
            'Status on/off'  '' {
                set status
            } "---------------------" '' {
                run true
            } 'list-keys -T prefix'  '' {
                list-keys -T prefix
            }
~~~

When the menu pops up the x position is correct but y position wrong:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/157076/215939257-5a2a714a-c0d2-45d9-ae8f-6f88e7938d28.png">

I'd expect the y position is relative to the top line of the window.

### Required information

* tmux version (`tmux -V`). tmux 3.3a
* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`). screen-256color, xterm-256color

**Comment by krader1961** [comment]
I've never used the tmux `display-menu` command so I had to look at the documentation. It seems to me, given your example, that the `-x` option is relative to the left side of both the pane and menu. While the `-y` option is relative to the top of the pane and the bottom of the menu. Regardless of whether that analysis is correct it is clear the behavior is not adequately specified and appears to be inconsistent vis-a-vis the two axis. The documentation also says the position is relative to "the terminal" for several special values but does not state explicitly that integer offsets are relative to "the terminal". So, it seems to me, there is probably a bug in the handling of the `-x` value and, more importantly, the documentation for the `display-menu` options `-x` and `-y` need clarification.

**Comment by clarkwang** [comment]
[code]: https://github.com/tmux/tmux/blob/f5af3cfb211c12897b15e3b5a3b29c4bbb0493a8/cmd-display-menu.c#L112

According to the [code], `-x, -y` is the menu's "bottom-left position". This is not quite convenient to calculate when more items are added to the menu. I think it's better to define `-x, -y` as the menu's **top-left** position.

**Comment by clarkwang** [comment]
Based on the previous analysis, figured out how to make it work:

~~~
bind  M  menu -x 10 -y '#{e|+:10,#{popup_height}}' \                                        -T " Press q to quit " \                                                        'Status on/off'  '' {                                                               set status
            } "---------------------" '' {
                run true
            } 'list-keys -T prefix'  '' {
                list-keys -T prefix
            }
~~~

<img width="731" alt="image" src="https://user-images.githubusercontent.com/157076/215949300-7aa2ee76-f103-491f-b6c8-4409b37d6b7a.png">

**Comment by clarkwang** [comment]
To keep backward compatibility I'd suggest a new option be added so `-x, -y` would be handled as the menu's top-left position.

**Comment by krader1961** [comment]
> According to the [code](https://github.com/tmux/tmux/blob/f5af3cfb211c12897b15e3b5a3b29c4bbb0493a8/cmd-display-menu.c#L112), -x, -y is the menu's "bottom-left position".

That is certainly consistent with the behavior your observed but, obviously, doesn't negate my point that the documentation does not adequately explain the behavior. 😄 I suspect we would both accept the current behavior if it was documented; especially since you and I (and probably most users) expected the coordinates to be relative to the "top-left" rather than "bottom-left" position for the menu.
