### ISSUE TITLE
Problem distinguishing between sessions named '1' and '10'

### ISSUE THREAD

**Issue by fawind** [tmux/tmux#346]
I have a session named '10' (and no session named '1'). The command `tmux has-session -t 1` returns true. In addition to this `tmux switch-client -t 1` switches to session 10.

This only happens if session '1' does not exist. Trying the same thing with an existing session '1' and a missing session '10' works fine.

I am using tmux 2.1.

**Comment by nicm** [comment]
You can use = for exact match.

**Comment by ThomasAdam** [comment]
Correct.  This is intended default behaviour.  For your purposes, see:

`tmux -t=10`
