### ISSUE TITLE
Broken background in Neovim

### ISSUE THREAD

**Issue by SoporteCoctell** [tmux/tmux#3461]
### Issue description

Hi. Some weeks ago I started using alacritty, and today I started learning tmux. I've discovered that when I want to open Neovim, it appears to be lacking the background color (with Tmux), but when I open it outside Tmux, it works perfectly fine. [Images of the problem](https://imgur.com/a/Z4liByi) . If I do the same in Kitty or Konsole, opening Neovim with tmux, it shows the background how it's meant to be (so the problem is with Alacritty specifically). [I opened an issue in Alacritty's Repo](https://github.com/alacritty/alacritty/issues/6668) but they closed it as they suggest that was a TERM variable problem: I've tried screen-256color, tmux-256color, alacritty and nothing change: the background color of Neovim is the only things that gets affected within tmux.

Thank you very much and greetings

### Required information

Please provide the following information:

* tmux version: tmux next-3.4 and tmux 3.3a.
* Platform: Linux unknown (Manjaro)
* $TERM inside of tmux: screen-256color
* $TERM outside of tmux: alacritty

**Comment by nicm** [comment]
Show tmux logs from running vim inside tmux in alacritty please.

**Comment by SoporteCoctell** [comment]
Oh am sorry. I forgot that one. Here are the links:
[Server](https://drive.google.com/file/d/1QJNaxVDK-9mP6YnFvxO3p4WpmD1BFzm3/view?usp=sharing)
[Client](https://drive.google.com/file/d/1TkEt5hTizXF5grf40gqLUc-gC8ZgbK8Y/view?usp=sharing)
[Output](https://drive.google.com/file/d/1_gNOxWfw3x2I3xLxX3Pb5oLW0j2ZzGdz/view?usp=sharing)

**Comment by nicm** [comment]
vim is using RGB colour but TERM=alacritty does not advertise that and tmux cannot autodetect alacritty, try:
~~~~
set -as terminal-features 'alacritty:rgb'

**Comment by SoporteCoctell** [comment]
Thank you so much!!!! That work perfectly!  I'll close the issue.
