### ISSUE TITLE
Could we add a paste or "paste from clipboard" to MouseDown3Pane?

### ISSUE THREAD

**Issue by Ergus** [tmux/tmux#3462]
Hi:

This is not an issue, but a feature request... could we consider to add a Paste (Yank) entry in the right click menus for those who like/need it?

**Comment by nicm** [comment]
OK why not... need to add to `DEFAULT_PANE_MENU` in `key-bindings.c`, may want to display the first bit of `buffer_sample`.

**Comment by Ergus** [comment]
I just tried to emulate a paste from the clipboard in this way:

```config
bind -N "Paste from clipboard" C-y \
     run-shell -b 'tmux set-buffer "$(xclip -o -sel c)"'\;\
     paste-buffer -p
```

But I got an error when trying to paste some text due to an issue with the set-buffer. I refined to this:

```shell
> tmux set-buffer '-o -sel c'
command set-buffer: unknown flag -o
```
Somehow I don't find a way to pass a text starting with - because tmux attempt to interpret it.

Is this intended?

**Comment by nicm** [comment]
Try this for paste please: [menu-paste.diff.txt](https://github.com/tmux/tmux/files/10613869/menu-paste.diff.txt)

**Comment by Ergus** [comment]
Hi:

I will try that. However this doesn't solve the clipboard part of the issue. So, I don't know what's better in your opinion?
 1. Add an option like `paster-buffer -c` or `paste-buffer --clipboard` to use the system's clipboard
 2. Make paste-buffer respect the `set-clipboard` value.
 3. Add an extra value for `set-clipboard` that uses system clipboard not only when copying, but also when pasting.
 4. Add an option symmetric to `copy-command` like `paste-command`.

**Comment by nicm** [comment]
Using the system clipboard with tmux is covered here: https://github.com/tmux/tmux/wiki/Clipboard

**Comment by Ergus** [comment]
> Using the system clipboard with tmux is covered here: https://github.com/tmux/tmux/wiki/Clipboard

Yes I saw that but there is a use case that does not work for me (or maybe there is an issue in my config?) because the paste from the clipboard does not work when coping outside (ex. in firefox) and paste in tmux with prefix-]. Is already some option for this?

**Comment by nicm** [comment]
tmux has no way to know when the system clipboard changes externally, you can only make it check with `refresh-client -l`.
