### ISSUE TITLE
 is it possible to use "control-l" to clear screen in tmux (alacritty)

### ISSUE THREAD

**Issue by jaden-falls** [tmux/tmux#3463]
So, I tried to use tmux for the first time in my life, when I was going to clear my screen with `control-l`, but it didn't work.

* tmux version (`tmux 3.3a`).
* Platform (`Darwin i38`).
* $TERM inside and outside of tmux (`screen-256color`).

**Comment by nicm** [comment]
`C-l` to clear is a feature of your shell, not tmux.

**Comment by willhbr** [comment]
You can create a keybinding in tmux that will do this:

```
bind-key -n C-l send-keys -R
```

**Comment by aorith** [comment]
I've been running this for a while without issues:

```
bind -N 'Clear both screen and tmux history buffer' -n 'C-l' {
    send-keys 'C-l'
    run 'sleep 0.1'
    if-shell '[[ ! $(tmux display-message -p "#W") =~ vim ]]' clear-history
}
```
