### ISSUE TITLE
Support ANSI coloring and styling

### ISSUE THREAD

**Issue by tigerinus** [tmux/tmux#3466]
Filed feature request to each of starship and oh-my-posh:

https://github.com/starship/starship/issues/4835
https://github.com/JanDeDobbeleer/oh-my-posh/issues/475

The common problem is that neither of them support TMUX coloring and styling. For both to integrate with TMUX statusline, they would have to build a converter from ANSI to TMUX format.

Thus, instead of re-inventing wheels, maybe it's a better idea for TMUX to natively support ANSI coloring/styling (or at least a converter command). This would immediately enable many projects like starship and oh-my-posh to be able to integrate with TMUX.

**Comment by nicm** [comment]
It is not reinventing the wheel, ANSI sequences are not capable of fully expressing what tmux styles need to, not to mention being harder to use.

But I don't mind accepting ANSI sequences for colours as well, although I don't intend to do it soon. I've added it to the todo list.
