### ISSUE TITLE
Option not to overwrite TERM_PROGRAM

### ISSUE THREAD

**Issue by heavywatal** [tmux/tmux#3468]
`TERM_PROGRAM` environment variable is a convenient way to check in which application the shell is running, e.g., `Apple_Terminal`, `iTerm.app`, `vscode`, etc. But it is overwritten by `tmux`, and there seems no easy way to trace it back. It would be helpful to have an option not to overwrite `TERM_PROGRAM`. Checking tmux does not become very hard by that because there are other variables such as `TMUX`.

By adding `set-option -ga update-environment TERM_PROGRAM` to `.tmux.conf`, the value shown in `tmux show-environment` is updated according to the application, but `echo $TERM_PROGRAM` remains `tmux`.

```
% uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 3.3a
screen-256color
```

**Comment by nicm** [comment]
Absolutely not. Inside tmux the terminal is tmux.

**Comment by heavywatal** [comment]
Thank you for the quick reply. OK, then what do you recommend to users who want to check which application is running the tmux? I can change the proposal to "Forwarding the original value of `TERM_PROGRAM` to a new environment variable".

**Comment by nicm** [comment]
Why do you need to know what terminal tmux is running in?

You can get external `TERM` by looking at the `client_termname` or if the terminal responds to XDA you can get the response from `client_termtype`, or you could get `TERMINAL_PROGRAM` from the session environment with `showenv`.

**Comment by heavywatal** [comment]
I use R and Python on tmux in different environments: Apple Terminal, iTerm, VSCode (integrated terminal), and remote servers. There are some configuration commands that I want to execute only in local VSCode for its extensions.

`TERM` and `client_termname` are irrelevant here. VSCode and Apple Terminal do not show `client_termtype`. The way to go seems to be using `update-environment TERM_PROGRAM` and `show-environment TERM_PROGRAM`. Thank you for the kind support.
