### ISSUE TITLE
UTF-8 zero-width space character 200B is rendered as a blob, not zero-width

### ISSUE THREAD

**Issue by idallen** [tmux/tmux#3469]
### Issue description

Last June's cloned version "next-3.4" displays a zero-width space (\u200b) as zero width on my Ubuntu Linux.
This February's cloned version "next-3.4" does not.

    $ /usr/bin/printf '.\u200b.\n'
    ..
    $ SHELL=/bin/sh tmux -vv -Ltest -f/dev/null new
    $ /usr/bin/printf '.\u200b.\n'
    . .

Reproduced with gnome-terminal (`xterm-256color`), xterm (`xterm`), and urxvt (`rxvt-unicode-256color`). 
 
It worked fine (displayed zero-width) last June.

### Required information

Please provide the following information:

    $ uname -sp && tmux -V && echo $TERM
    Linux x86_64
    tmux next-3.4
    tmux-256color

This "next-3.4" clone is newer than the previous "next-3.4" I cloned last June. 
The one from last June works fine.  The newest clone (from February 7) does not.

    $ lsb_release -a
    Distributor ID:     Ubuntu
    Description:        Ubuntu 20.04.5 LTS
    Release:    20.04
    Codename:   focal

[tmux-out-577937.log](https://github.com/tmux/tmux/files/10702489/tmux-out-577937.log)
[tmux-server-577937.log](https://github.com/tmux/tmux/files/10702490/tmux-server-577937.log)
[tmux-client-577935.log](https://github.com/tmux/tmux/files/10702491/tmux-client-577935.log)

**Comment by nicm** [comment]
Try this please: [tmux-width.diff.txt](https://github.com/tmux/tmux/files/10705329/tmux-width.diff.txt)

**Comment by idallen** [comment]
> Try this please: [tmux-width.diff.txt](https://github.com/tmux/tmux/files/10705329/tmux-width.diff.txt)
Yes, that fixes the null character width problem.  Closed.

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
