### ISSUE TITLE
starting tmux or doing tmux attach generates input buffer garbage only under urxvt

### ISSUE THREAD

**Issue by idallen** [tmux/tmux#3470]
### Issue description

When starting `tmux` or doing a `tmux attach` under `urxvt`, a line of garbage appears in the input buffer:

    $ TERM=xterm SHELL=/bin/sh tmux -vv -Ltest -f/dev/null new
    $ ^[]10;rgb:0000/0000/0000^[^[]11;rgb:ff00/ff00/dd00^[

The garbage does not appear when starting `tmux` or doing the attach from inside of `gnome-terminal` or `xterm`.
The same `urxvt` garbage appears when I set TERM to any of `xterm`, `rxvt-unicode-256color`, or `xterm`.
I can get rid of the input buffer garbage using either backspaces or line-erase (CTRL-U).

### Required information

This is the February 7 tmux version `next-3.4` patched with the recent zero-width patch.
(The zero-width patch did not cause this; it was happening before the patch.)
This "next-3.4" clone is newer than the previous "next-3.4" I cloned last June.
The one from last June works fine. The newer clone (from February 7) does not.

    $ uname -sp && tmux -V && echo $TERM
    Linux x86_64
    tmux next-3.4
    tmux-256color
    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 20.04.5 LTS
    Release:        20.04
    Codename:       focal

[tmux-out-1089532.log](https://github.com/tmux/tmux/files/10707681/tmux-out-1089532.log)
[tmux-server-1089532.log](https://github.com/tmux/tmux/files/10707683/tmux-server-1089532.log)
[tmux-client-1089530.log](https://github.com/tmux/tmux/files/10707684/tmux-client-1089530.log)

**Comment by nicm** [comment]
This is a bug in urxvt.

**Comment by nicm** [comment]
You can make this change to urxvt:

https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/ports/x11/rxvt-unicode/patches/patch-src_command_C?rev=1.6&content-type=text/plain

**Comment by idallen** [comment]
> This is a bug in urxvt.

Indeed it is.  How did you know where to find the fix?
Are you watching the bug lists of all the world's terminal emulators? :-)

Building `urxvt` from source required not only the source here https://github.com/exg/rxvt-unicode
but also libraries http://dist.schmorp.de/libev/ and http://dist.schmorp.de/libptytty/ 
Then the patch can be applied and a new version compiled and installed.  It works!

Closed.

**Comment by nicm** [comment]
Someone else already reported it to me :-).
