### ISSUE TITLE
Tmux eating some German keyboard inputs. 

### ISSUE THREAD

**Issue by apozharski** [tmux/tmux#3472]
### Issue description
When entering commands Tmux eats some keys when using a German keyboard. In particular `+`, `-`, `/`, and `*`. 

This makes it impossible to enter for example `set -g mouse on`

No tmux config required and this occurs on the latest github commit.

### Required information

Please provide the following information:
```
uname -sp: Linux x86_64
tmux -V: tmux next-3.4
echo $TERM: xterm-256color
echo $TERM (inside tmux): screen
```
logs attached
[tmux_logs.tar.gz](https://github.com/tmux/tmux/files/10712971/tmux_logs.tar.gz)

**Comment by nicm** [comment]
I only see one unusual key in this log: `\033Om` which is Keypad-Minus.

I can only see you typing it at the command prompt, which does not have any interest in keypad keys. What happens if you type it into a pane? Please show the a server log of doing that.
