### ISSUE TITLE
Add -t flag to source-file

### ISSUE THREAD

**Issue by willhbr** [tmux/tmux#3473]
Currently the `source-file` command does not have any way to specify the context that the file is evaluated in. As far as I can tell, the commands in the file are evaluated as though the command was run in the most recently active client - even if the command is run outside of tmux.

If `source-file` had a `-t` argument, it would be possible to do things like load a config to customise a particular session/window/pane, or simplify scripts that have to run a series of tmux commands each with a target specified.

An example of how I would use this is something like [this](https://github.com/willhbr/dotfiles/blob/main/bin/show-tmux-popup.sh#L8-L10) where I want to put a certain tmux session into a particular "mode" (change the key-table, prefix, and appearance) but have to run each command separately. Instead it could just be:

```
tmux source-file -t "$my_session" setup_popup_mode.conf
```

The only prior discussion I could find was [a passing mention in tmux-users](https://groups.google.com/g/tmux-users/c/qjwtLL2tVc4/m/tRB0dQaYCAAJ).

(Since this is a feature request rather than a bug report, I've omitted version/OS info)

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/12504042/x.diff.txt)

**Comment by willhbr** [comment]
I'm a bit confused, that's patching the contents of a function called `server_client_check_pane_resize`, I'm not sure how that relates to the target of `source_file`.

**Comment by nicm** [comment]
Whoops, sorry wrong file: 
[y.diff.txt](https://github.com/tmux/tmux/files/12548049/y.diff.txt)

**Comment by willhbr** [comment]
Aha! This seems to work, I've given it test:

I created a file `test.conf` with the contents `new-window`. With two sessions (`$0` and `$1`) open, I ran `tmux source-file -t '$1' test.conf` in `$0`, and a new window opened in `$1`.

And I've been able to do the same use-case from my original comment.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
