### ISSUE TITLE
Give cue when output was added to pane while in copy mode

### ISSUE THREAD

**Issue by da-x** [tmux/tmux#3475]
[[ perhaps this was already implemented and I've misread tmux man page, please bear with me ]]

Sometimes I accidentally leave panes in copy mode. Output lines are added to these panes and I don't notice it because they don't scroll to the bottom (I like it this way - not interested in 'surprise scroll down').

I'd like to add visual indication in the pane status when this happened, so I can leave copy mode and look at the new output. Like to change the color of the pane status bar or something like that.

I'd like to implement this myself, with your assistance. Perhaps you can provide:
1. what do you think about this feature in general.
2. design: how would you like this feature to be configured by users.
3. implementation: pointers in the code as to where and what to change in high level. 

Thanks

**Comment by da-x** [comment]
Nice idea by AI suggesting something that probably doesn't work - set the individual pane status style based on a hook. It's a nice start though.

![image](https://user-images.githubusercontent.com/321273/219276319-1e71c448-f2de-4e48-aa9e-322f98dd5678.png)

**Comment by da-x** [comment]
On the way to this, I was able to condition `page-border-format` based on `pane_in_mode`.

```
set -g pane-border-format '#{?pane_in_mode,#[fg=#222200 bg=#dddd00 bold],#[fg=#00ffff bg=#003333 bold]}#T'
```

Now I wish I could `&&` this condition with an boolean expression that tells whether there is new pane output that we have not scrolled to see yet.

**Comment by nicm** [comment]
You could add a format variable to `window_copy_formats` with the total lines in the copy mode version of the screen and a similar one to compare to for outside to `format.c` (I thought I had done this but maybe it was never applied and now I can't find it).

**Comment by da-x** [comment]
@nicm Thanks, this got me thinking -

1) Do we need to trigger redraw, otherwise what would redraw the status line when there's new pane output
2) If relying on number of lines in history of copy mode vs. what is in the window pane, the latter gets rotated when history reaching maximum, so the comparison will not be fully reliable.

Maybe we need to reply on something that grows monotonically when pane data is added. I am thinking, perhaps `window_pane->written`  can be copied into a new field `written_saved` in `struct window_copy_mode_data` when copy mode starts, and only when `window_pane->written` is modified it can be compared against `written_saved` and trigger a single redraw (though, the bad thing is that the redraw may be redundant if the user has not configured usage of this feature).

**Comment by nicm** [comment]
Yes you could save the number of lines written when entering copy mode and then compare with the saved value.

You'll probably need a low `status-interval`.

**Comment by da-x** [comment]
I got a working implementation as 
https://github.com/tmux/tmux/pull/3498
