### ISSUE TITLE
Weird `tmux command-prompt` behaviour

### ISSUE THREAD

**Issue by mpiiroinen** [tmux/tmux#3477]
`tmux command-prompt -t <client> 'attach -t .'` starts a new client in the shell the command is run from, instead of reattaching in the `<client>`.

I have used a similar command succesfully on 3.0a to in order to change the current working directory of the tmux session. However, on other Arch Linux machine,  running `3.3a` or `next-3.4` it is broken because of this weird behaviour.

```
Linux unknown
tmux next-3.4
xterm-256color
```

I do not think the `$SHELL` inside of tmux matters because this happens regardless of what is running inside the session.

Maybe this is intended behaviour, but I could at least not recognize such thing in the changelog.

**Comment by mpiiroinen** [comment]
Seems like this changed between 3.2a and 3.3. (tested compiling from the source tarballs).

**Comment by nicm** [comment]
Yeah it looks like previously the command was always run in the context of the target client and now it uses the calling client (that did the `command-prompt`). Probably something like this did not used to work as expected:
~~~~
tmux command-prompt -txxx  'run "echo %1"'\; run "echo after"
~~~
I think it is better as it is now TBH. We probably need a better way to change a client's working directory (a flag to `switch-client` or `refresh-client` would be best).

**Comment by mpiiroinen** [comment]
Indeed your example works weird in `3.2a`. The latter `run` prints in the calling client's shell.

What I am mainly looking for is an easy way to open new splits in the working directory of the current shell. Either a way to change the tmux working directory, or a possibility to configure a key binding that would take the directory from the current pane. I cannot come up with either in `3.3a`.

Thanks to the change `split-window`, called remotely, now seems to take the working directory from the calling client. So maybe there is some workaround there, though not yet sure how I would go about binding a shell command within a pane to a key.

**Comment by nicm** [comment]
This is not clear to me, you talk about taking the WD from the current shell, but your example is being run from the shell, so you can juse use `$PWD`, no?

**Comment by nicm** [comment]
You can get the *current process* working directory outside the pane with `pane_current_path`; if you actually want the *shell's* working directory you will need to have the shell either send OSC 7 so it goes into `pane_path`, or have it issue a tmux command to store the shell in a user option.

**Comment by mpiiroinen** [comment]
Thanks. I think `pane_current_path` is something I can work with.. E.g. `bind-key <key> attach -t . -c "#{pane_current_path}"`. Did not think of that before.

Previously I was doing something along the lines `tmux command-prompt  "attach -t . -c $PWD"`  to change the WD from a pane. That does not work in `3.3a` as it tries to attach nested tmux instead. Using `pane_current_path` is probably a better way to achieve I wanted..

**Comment by nicm** [comment]
But if you want a new pane, why not `split-window -c`/`new-window -c`?

**Comment by mpiiroinen** [comment]
Yes there seems to be a lot of options after all. Switching the tmux workdir, instead of always splitting using `-c "#{pane_current_path}"`, works better for my workflow.
