### ISSUE TITLE
command-prompt does not work with more than 1 prompt

### ISSUE THREAD

**Issue by k-y** [tmux/tmux#3478]
### Issue description

`bind-key * { command-prompt -p 'Lines: ,Filename: ' 'capture-pane -pS -%1 > ~/tmp/logs/%2.log' }` fails with `Command command-prompt: too many arguments (need at most 1)`

Adding `-I` makes no difference.  Fails with the same error.

Working around the issue by creating 2 separate command-prompts:
```
bind-key F8 { command-prompt 'capture-pane -S -%1' }
bind-key F9 { command-prompt 'save-buffer %1' }
```

### Required information

* version (tmux 3.3a).
* Platform (Linux x86_64).
* screen-256color inside and outside of tmux (xterm-256color).

**Comment by nicm** [comment]
> capture-pane -pS -%1 > ~/tmp/logs/%2.log' 

`>` is not something you can put in tmux commands.

**Comment by k-y** [comment]
Without using `>`, the same error occurs on the following:
`bind-key * { command-prompt -p 'Lines: ,Filename: ' 'capture-pane -pS -%1 \; save-buffer ~/tmp/logs/%2.log' }`

**Comment by nicm** [comment]
`-%1` what is this meant to do? Also I think you shouldn't need the `\` before the `;`.

**Comment by k-y** [comment]
Yup; I saw some examples of other users escaping the `;` so I tried it both ways.

`-%1` is meant to allow me to substitute the value when prompted for the number of lines that I want to capture from the scrollback history -- e.g., `capture-pane -S -1000`

I typoed the previous command, should be:
`bind-key * { command-prompt -p 'Lines: ,Filename: ' 'capture-pane -S -%1 ; save-buffer ~/tmp/logs/%2.log ; delete-buffer ' }`

**Comment by nicm** [comment]
This command works for me, is it still broken for you with master?

**Comment by k-y** [comment]
I just built next-3.4 from master and the same command fails:
`bind-key * { command-prompt -p 'Lines: ,Filename: ' 'capture-pane -S -%1 ; save-buffer ~/tmp/logs/%2.log ; delete-buffer ' }` with `Command command-prompt: too many arguments (need at most 1)`

**Comment by nicm** [comment]
That is exactly what I have in .tmux.conf and it works.

**Comment by k-y** [comment]
I'd been testing this using an active tmux session and then trying to assign the command while in command-line mode.

If I add the `bind-key ...` to my .tmux.conf then source the file, the bound key does work as expected.  Worked in both 3.3a and next-3.4.

Does tmux handle configuration of `command-prompt` differently when reading in .tmux.conf vs being configured via command-line mode?

**Comment by nicm** [comment]
`command-prompt` is replacing the initial `%1` with your command and then since the command contains `%2` it is ending up replacing that with the command as well. I don't think there should actually be a `%2` here, try this please: 
[x.diff.txt](https://github.com/tmux/tmux/files/10839728/x.diff.txt)
