### ISSUE TITLE
Tmux automatically rename windows

### ISSUE THREAD

**Issue by haruops** [tmux/tmux#3479]
Hi, all. Tmux automatically rename windows. How to fix it?

OS: MacOS
Tmux -V: 3.3a

https://user-images.githubusercontent.com/44260786/221341658-c423523b-a2c3-488f-84ef-916d67f521b3.mp4

**Comment by haruops** [comment]
`set-option -g automatic-rename off` - it didn't help me

**Comment by nicm** [comment]
Your shell must be doing it, try `set -g allow-rename off`.

**Comment by haruops** [comment]
`set -g allow-rename off`  / `set-option -g allow-rename off`  - unfortunately, that didn’t help either

Setting the following variable in .zshrc `DISABLE_AUTO_TITLE=true` didn't solve the problem.

**Comment by nicm** [comment]
Show tmux server log please.

**Comment by haruops** [comment]
> Show tmux server log please.

Please clarify, how can I get the server log?

**Comment by nicm** [comment]
https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md#how-do-i-get-logs-from-tmux

**Comment by haruops** [comment]
> Show tmux server log please.

[tmux-logs.tar.gz](https://github.com/tmux/tmux/files/10999142/tmux-logs.tar.gz)

**Comment by nicm** [comment]
There are no windows being renamed in this log other than when it is initially set to `zsh`.

**Comment by haruops** [comment]
> There are no windows being renamed in this log other than when it is initially set to `zsh`.

[tmux-logs-v2.tar.gz](https://github.com/tmux/tmux/files/11001390/tmux-logs-v2.tar.gz)

**Comment by gbrsts** [comment]
So, if I put: "set-window-option -g window-status-format #{#W}" on tmux.conf, it will show the name of windows I rename?
