### ISSUE TITLE
Zero-width space breaks selection

### ISSUE THREAD

**Issue by juliekoubova** [tmux/tmux#3482]
### Issue description

A zero-width space (U+200b) in the output causes tmux to duplicate surrounding characters when selecting nearby text using mouse. It is much worse when done in a pane that doesn't start at the left side of the terminal.

https://user-images.githubusercontent.com/142506/221361416-58ed1af1-9add-4a13-becd-b0dd91e93d1d.mp4

### Required information

* Linux 5.15.90.1-microsoft-standard-WSL2
* tmux 3.3a (reproes both in the Alpine package and in local build of current master)
* tmux-256color
* zsh 5.9 (x86_64-alpine-linux-musl) (also reproes with Windows version of PowerShell 7.3.2)
* Windows Terminal 1.16.10262.0

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by juliekoubova** [comment]
> Does this still happen with master?

Yes, I tried it yesterday.

**Comment by nicm** [comment]
Show logs please.

**Comment by juliekoubova** [comment]
[tmux-server-18743.log](https://github.com/tmux/tmux/files/10843974/tmux-server-18743.log)
[tmux-client-18740.log](https://github.com/tmux/tmux/files/10843975/tmux-client-18740.log)

**Comment by nicm** [comment]
This is from 3.3a, please show log from master.

**Comment by juliekoubova** [comment]
[tmux-client-22396.log](https://github.com/tmux/tmux/files/10853527/tmux-client-22396.log)
[tmux-server-22399.log](https://github.com/tmux/tmux/files/10853529/tmux-server-22399.log)

**Comment by nicm** [comment]
The problem here is that `wcwidth` tells us the character is zero width but terminals actually display it as a normal space of width 1 which means tmux cannot correctly calculate the cursor position. We can perhaps just replace it with an actual space, at least for a quick fix. Try this please: [zws.diff.txt](https://github.com/tmux/tmux/files/10910330/zws.diff.txt)
