### ISSUE TITLE
Inconsistent `$XDG_VTNR` in tmux?

### ISSUE THREAD

**Issue by rrueger** [tmux/tmux#3483]
### Issue description

Usually, `$XDG_VTNR` tells me which `tty` I am on. However, in `tmux`, `$XDG_VTNR` tells me on which `tty` tmux was first started.

For example

    # In tty1
    echo $XDG_VTNR
    1
    # good. Now enter tmux
    tmux
    echo $XDG_VTNR
    1
    # So far, so good
    # Now switch to tty2, whilst leaving tmux open in tty1
    echo $XDG_VTNR
    2
    # good. Now enter tmux (still on tty2)
    tmux
    echo $XDG_VTNR
    1
    # What??

I don't know if this is a bug, or expected behaviour, but I couldn't find anything online.

Information
* tmux version. `tmux 3.3a`
* Platform. `Linux unknown` (ArchLinux)
* $TERM. Inside tmux: `tmux-256color`. Outside tmux: `foot`

**Comment by nicm** [comment]
There is no way for tmux to update this, even if it wanted to, after the shell has been started.

**Comment by rrueger** [comment]
Thanks for the fast response!

Is the new `tmux` call "attaching" to the already running session in `tty1`? Or why does tmux think it is in `VTNR` 1 when actually it is in 2?

As I understand it, tmux starts a new session each `tmux` call?

**Comment by nicm** [comment]
See this section of the manual page: https://man.openbsd.org/OpenBSD-current/man1/tmux.1#GLOBAL_AND_SESSION_ENVIRONMENT

**Comment by rrueger** [comment]
Thank you. Unfortunately, I do not understand how to prevent tmux from passing XDG_VTNR from the global environment to the session environment (I am not even sure if this is the right terminology and "direction" of passing).

I do not understand what the "global environment" is in comparison to the "session environment". In this terminology, what is the environment of the shell that starts tmux?

As I understand it, the initial tmux call populates the global environment with the environment of the shell from which tmux is started.

> When the server is started, tmux copies the environment into the [global environment](https://man.openbsd.org/OpenBSD-current/man1/tmux.1#global)

When a new tmux session is started, it inherits values from the global environment, unless the environment of the shell already defines that value

> If a variable exists in both, the value from the session environment is used

Here, I am assuming that "session environment" == "environment of the session that started tmux".

However, the opposite seems to be the case here? (The value `XDG_VTNR=1` from the global environment is overriding `XDG_VTNR=2` from the shell that started tmux)

Thanks in advance for explaining!

**Comment by nicm** [comment]
Everything goes into the global environment when tmux is started. When a session is created, its environment (the session environment) gets whatever is in the global environment and then everything in `update-environment` is copied from the shell which created the session (if there is one). So unless you put XDG_VTNR in update-environment it will not be updated after the server has started. All this only applies to newly created panes (child processes of tmux); there is no way for tmux to modify the environment in existing child processes.

**Comment by rrueger** [comment]
Perfect! I added

    set-option -g update-environment XDG_VTNR

to my `~/.tmux.conf` and now `$XDG_VTNR` is as I would expect.

Thank you for your quick replies and patience!
