### ISSUE TITLE
OSC 52 clear selection

### ISSUE THREAD

**Issue by aymanbagabas** [tmux/tmux#3485]
### Issue description

Per [the OSC 52 specs](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands:~:text=If%20the%20second%20parameter%20is%20neither%20a%20base64%20string%20nor%20%3F%20%2C%0A%20%20%20%20%20%20%20%20%20%20then%20the%20selection%20is%20cleared.), the clipboard selection gets cleared if the second parameter is neither a base64 string nor a "?" character. I tried this in a my remote linux server running tmux 3.2a and locally running tmux 3.3a on macOS.

### Required information

* tmux version (`tmux -V`): tmux 3.3a
* Platform (`uname -sp`): Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`): tmux-256color & xterm-256color

**Comment by nicm** [comment]
I don't think programs should be able to delete paste buffers with an escape sequence.

**Comment by aymanbagabas** [comment]
It's the same argument as changing the paste buffer with an escape sequence. If a program can change the paste buffer with an escape sequence, I don't see how _clearing_ the paste buffer is any different.

**Comment by nicm** [comment]
It can create paste buffers but it cannot delete existing ones.

**Comment by aymanbagabas** [comment]
We could create a new empty buffer to make tmux fully compliant with OSC 52.

**Comment by nicm** [comment]
I don't know what the point of that would be. What are you using this for?

**Comment by aymanbagabas** [comment]
True there isn't much value here. I was working on implementing OSC 52 in a project and noticed that tmux doesn't clear the system clipboard when it should.

**Comment by nicm** [comment]
I don't think there is much need to support this, I can't see why anyone would wants a empty paste buffer or for existing to be deleted. Thanks anyway.
