### ISSUE TITLE
Horizontal Mouse Wheel

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#3486]
I had noticed, on a `tmux-next-3.3` build I had been running, that horizontal mouse wheel (both left and right) would get translated to a MouseWheelDown event by tmux, though it wasn't a consistent behavior since horizontal scroll still worked properly inside vim there. 

This was causing some issues mainly with inadvertent horizontal scroll inputs from a macbook trackpad interacting with copy-mode. 

Since I've built from master today (showing `tmux-next-3.4`) the horizontal scroll behavior is now perfect:
- No more MouseWheelDown happening on horizontal scrolling anymore. Spurious side scroll inputs are ignored again in copy-mode.
- vim continues to handle both vertical and horizontal scroll perfectly

The only remaining question relating to horizontal mouse wheel, then, is will/**does tmux support defining it in binds yet**? I did not see entries referring to this in the manpage.

**Comment by nicm** [comment]
You can try them as mouse buttons 6 and 7, if that doesn't work show a tmux log from you pressing them.
