### ISSUE TITLE
Cannot use C-Space as prefix

### ISSUE THREAD

**Issue by PeuTit** [tmux/tmux#3487]
### Issue description

I've been using Tmux on Mac OS for a year now and love the productivity boost it gave me. But then my prefix stopped working recently.

I've set up a minimal config to test this:
```bash
unbind C-b
set -g prefix C-Space
bind Space send-prefix
```

This problem happen on both Terminal.app and WezTerm.app.

### Required information

* tmux version (`tmux -V`).
tmux 3.3a (Installed via HomeBrew.
* Platform (`uname -sp`).
Darwin i386
Mac OS 13.2.1
Macbook Pro 15,1 (Intel)
* $TERM inside and outside of tmux (`echo $TERM`).
Outside: `xterm-256color` (both terminals)
Inside: `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-27949.log](https://github.com/tmux/tmux/files/10888010/tmux-client-27949.log)
[tmux-out-27951.log](https://github.com/tmux/tmux/files/10888011/tmux-out-27951.log)
[tmux-server-27951.log](https://github.com/tmux/tmux/files/10888012/tmux-server-27951.log)

**Comment by krader1961** [comment]
Works for me, and I use Tmux on macOS. The Ctrl-Space key combination should send a nul character. If you type `od -tx1`, press Ctrl-Space, Enter, then Ctrl-D you should see output llke this:

```
> od -tx1
^@
0000000    00  0a
0000002
```

Also, you `bind` statement should be `bind C-Space send-prefix`, not `bind Space send-prefix`.

**Comment by PeuTit** [comment]
Did the steps you provided and ended up with a different result:
```bash
➜  ~ od -tx1

0000000    0a                                                            
0000001
```

**Comment by PeuTit** [comment]
Issue solved!
Based on the previous result, I figured that Ctrl-Space must be assigned to a system wild keyboard shortcut. 
My guess was right, going into Settings > Keyboard > Keyboard Shortcuts... > Input Source, the shortcut for toggling between input sources was mapped to Ctrl-Space (^Space). Disabling it and running the same command yields the correct result:
```bash
➜  ~ od -tx1
^@
0000000    00  0a                                                        
0000002
```
Now my tmux configuration behave normally. Thanks a lot for your help!
