### ISSUE TITLE
allow-passthrough all sends the sequence to other sessions

### ISSUE THREAD

**Issue by sergei-grechanik** [tmux/tmux#3489]
Hi, I discovered the following bug in the `allow-passthrough all` feature: it's sending the passthrough sequence to all clients, even those running different sessions. I've attached a patch that should fix the issue. It basically checks the session, but I'm not sure I'm getting the session from the window correctly.
[tmux-fix-allow-passthrough-all-check-session.patch.txt](https://github.com/tmux/tmux/files/10893593/tmux-fix-allow-passthrough-all-check-session.patch.txt)

**Comment by nicm** [comment]
Thanks, but this is not right:
~~~~
                if (wp->window->winlinks.tqh_first->session == c->session)
~~~~
You should not reach inside TAILQ, use the macros.

In any case there is no guarantee the first `winlink` in the list will be in this client's session. You'd need to check them all.

But you can probably just use `session_has(c->session, wp->window)` which will ask the question the other way round, but give the same result (true if the window is in the client's session).

**Comment by sergei-grechanik** [comment]
Oh, I see, thanks for the correction. Here is the fixed patch: [tmux-fix-allow-passthrough-all-check-session-2.patch.txt](https://github.com/tmux/tmux/files/10916942/tmux-fix-allow-passthrough-all-check-session-2.patch.txt)
