### ISSUE TITLE
tmux 2.1 locally.-

### ISSUE THREAD

**Issue by jimsrc** [tmux/tmux#349]
Hi!,

I'm trying to use tmux 2.1 locally (in my user space).
So I have a script (see below) that installs it locally in $HOME/local/.
When I execute it to create a new session, everything goes perfect. 

After I close or detach from my session, I can not enter again with tmux list-sessions.
Neither I can open another session.
When I go check I have:
srw-rw---- 1 jim jim     0 mar 25 12:26 /home/jim/local/bin/tmux_2.1
Before creating my session I had:
-rwxrwxr-x 1 jim jim  3.1M mar 25 10:32 /home/jim/local/bin/tmux_2.1

Why did permissions changed automagically? and why it suddenly has 0 bytes?

Thanks very much in advance!,
Jimmy.

++++++++++++++++++++++++++++++++++++++++++
set -e
TMUX_VERSION=2.1
mkdir -p $HOME/tmux_tmp
cd $HOME/tmux_tmp
wget -O tmux-${TMUX_VERSION}.tar.gz https://github.com/tmux/tmux/releases/download/2.1/tmux-${TMUX_VERSION}.tar.gz
tar xvzf tmux-${TMUX_VERSION}.tar.gz
cd tmux-${TMUX_VERSION}

./configure CFLAGS="-I$HOME/local/include -I$HOME/local/include/ncurses" LDFLAGS="-L$HOME/local/lib -L$HOME/local/include/ncurses -L$HOME/local/include"

CPPFLAGS="-I$HOME/local/include -I$HOME/local/include/ncurses" LDFLAGS="-static -L$HOME/local/include -L$HOME/local/include/ncurses -L$HOME/local/lib" make

cp tmux $HOME/local/bin/tmux_${TMUX_VERSION}
#EOF 
++++++++++++++++++++++++++++++++++++++++++

**Comment by nicm** [comment]
Are you are running tmux with -S pointing to the binary so it overwrites it
with the socket?

**Comment by jimsrc** [comment]
Hi!, nope.
I'm running this way:
> $TMUX -2 # I use -2 so that recognizes my .vimrc config
where:
export TMUX=~/local/bin/tmux_2.0 # this is in my .zshrc

**Comment by nicm** [comment]
tmux gets the socket path from $TMUX so use a different variable name.

**Comment by jimsrc** [comment]
PERFECT!
It works! Thank you very much :D
