### ISSUE TITLE
tmux doesn't work inside chroot

### ISSUE THREAD

**Issue by XXXBold** [tmux/tmux#3490]
### Issue description

I'm facing an issue where I can't use tmux inside a chroot. It crashes/closes immediately when I attempt to start a new session.
It does work so far in the normal environment (On the same user).
For testing purposes, I'm using mount-bind for the following locations inside chroot (chroot at /var/chroottest) to their original location on /:
- /var/chroottest/bin
- /var/chroottest/etc
- /var/chroottest/lib64
- /var/chroottest/run
- /var/chroottest/tmp
- /var/chroottest/dev
- /var/chroottest/lib
- /var/chroottest/proc
- /var/chroottest/sys
- /var/chroottest/usr

Homedir of usrtest1 is set to /var/chroottest/home/usrtest1 (Currently not using a .tmux.conf)

### Required information
System: Linux Mint XFCE 21.1

Logs from WORKING command (run in "real" environment, rund command: "sudo -u usrtest1 tmux kill server" first and then "sudo -u usrtest1 strace tmux -vv new" and exited via "exit" command)
tmux version (latest git): tmux next-3.4
Platform (uname -sp): Linux x86_64 
$TERM outside tmux (sudo -u usrtest1 echo $TERM): xterm-256color
$TERM inside tmux: tmux-256color
Logfiles:
[tmux-realenv-client.log](https://github.com/tmux/tmux/files/10940759/tmux-realenv-client.log)
[tmux-realenv-out.log](https://github.com/tmux/tmux/files/10940760/tmux-realenv-out.log)
[tmux-realenv-server.log](https://github.com/tmux/tmux/files/10940762/tmux-realenv-server.log)
[tmux-realenv-strace.log](https://github.com/tmux/tmux/files/10940763/tmux-realenv-strace.log)

Logs from chroot (Startcommand for chroot: "sudo chroot --userspec=usrtest1:usrtest1 /var/chroottest /bin/bash"):
Runcommand for tmux: first "tmux kill server" and then "strace tmux -vv new"
tmux version (latest git): tmux next-3.4
Platform (uname -sp): Linux x86_64 
$TERM outside tmux (echo $TERM): xterm-256color
$TERM inside tmux: N/A, doesn't start/closes immediately
Logfiles:
[tmux-chroot-client.log](https://github.com/tmux/tmux/files/10940767/tmux-chroot-client.log)
[tmux-chroot-out.log](https://github.com/tmux/tmux/files/10940768/tmux-chroot-out.log)
[tmux-chroot-server.log](https://github.com/tmux/tmux/files/10940769/tmux-chroot-server.log)
[tmux-chroot-strace.log](https://github.com/tmux/tmux/files/10940770/tmux-chroot-strace.log)

**Comment by nicm** [comment]
> 1678441463.406221 cmdq_error: create window failed: fork failed: No such device

I expect your pty subsystem doesn't work. Did you mount devpts?

**Comment by XXXBold** [comment]
> > 1678441463.406221 cmdq_error: create window failed: fork failed: No such device
> 
> I expect your pty subsystem doesn't work. Did you mount devpts?

Hm, I've  just mounted the whole /dev, isn't that enough?
