### ISSUE TITLE
Popup window memory usage

### ISSUE THREAD

**Issue by ndsizeif** [tmux/tmux#3492]
Tmux popup windows can cause large amounts of memory to be used.

Steps to reproduce:

In a new tmux session, run `tree $HOME` several times and note the tmux server memory
usage. Kill the session.

Open a new tmux session. Then open a popup menu with `tmux display-popup`. In the popup
window, run `tree $HOME` several times while monitoring memory usage. Close the popup.

Alternatively, open a new tmux session and hold carriage return for 30 seconds. Then
perform the same action inside a popup window.

Result:

Running a command that produces significant text output in a regular window may increase
memory usage slightly, but subsequent commands don't impact memory.

Running that same command in a popup window will continue to consume system memory. After
the popup is closed, the memory is still reported as being used by the tmux server
indefinitely (the above session with one window still uses 300MB after 8 hours). This
occurs with or without a `.tmux.conf` file.

If someone else can't reproduce, I will provide the log

>tmux 3.3a
Linux unknown 
tmux-256color / alacritty

**Comment by nicm** [comment]
glibc is very bad at returning memory to the OS. tmux will call `malloc_trim` once an hour, does the memory go down if you wait for an hour?

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/10977477/x.diff.txt)

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
