### ISSUE TITLE
Cannot switch-client to panes which ID starts with 2

### ISSUE THREAD

**Issue by markkrj** [tmux/tmux#3493]
### Required information
Trying to switch to a pane which ID starts with 2, the rest of the ID is duplicated, so:
%21 becomes %211
%212 becomes %21212
![tmux](https://user-images.githubusercontent.com/13537652/225010376-85ab5c98-9427-4a7e-9578-6db160a81a6e.gif)

Please provide the following information:

* tmux version (`tmux -V`).
3.3a
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
original: xterm
tmux: tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-111.log](https://github.com/tmux/tmux/files/10968872/tmux-client-111.log)
[tmux-out-113.log](https://github.com/tmux/tmux/files/10968873/tmux-out-113.log)
[tmux-server-113.log](https://github.com/tmux/tmux/files/10968874/tmux-server-113.log)

**Comment by nicm** [comment]
Does this fix it? 
[x.diff.txt](https://github.com/tmux/tmux/files/10969601/x.diff.txt)

**Comment by markkrj** [comment]
@nicm yes, that works

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
