### ISSUE TITLE
can tmux read shell variable in shell script conveniently?

### ISSUE THREAD

**Issue by czg-sci-42ver** [tmux/tmux#3495]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.0a
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
```bash
out:
$ echo $TERM
xterm-256color
in:
$ echo $TERM
screen
```
* Logs from tmux (`tmux kill-server; tmux -vv new`).
```bash
$ tmux kill-server; tmux -vv new
server exited unexpectedly
$ tmux kill-server; tmux -vv new
no server running on /tmp/tmux-1000/default
[exited]
```

- I want to directly run `gdb-tmux ...` in terminal which then open tmux and run all I expect without running `tmux` before run `gdb-tmux ...`
here is my bash func:
```bash
gdb-tmux() {
    pkill tmux 
    tmux -vv new -d -s DEV -n debug && tmux new-window -d -a -n main -t DEV:debug
    
    local id_1="$(tmux display-message -t DEV:debug -p '#P')"
    local id_2="$(tmux split-pane -d -t DEV:debug.$id_1 -hPF "#P" -p 45)"
    local tty_new="$(tmux display-message -t DEV:debug.$id_2 -p '#{pane_tty}')"
    local id_3="$(tmux split-pane -d -t DEV:debug.$id_2 -vPF "#P" -p 85)"
    local tty_new_2="$(tmux display-message -t DEV:debug.$id_3 -p '#{pane_tty}')"

    tmux select-pane -e -t DEV:debug.$id_1
    Args="$@"
    
    tmux split-pane -d -t DEV:debug.$id_1 -vPF "#P" -p 35
    tmux send-keys -t DEV:debug.$id_1 'echo $Args' C-m
    tmux send-keys -t DEV:debug.$id_1 'echo $Args | xargs -I "{}" gdb -ex "dashboard source" -ex "dashboard variables" -ex "dashboard variables -output $tty_new" -ex "dashboard source -output $tty_new_2" -ex "start" "{}"' C-m
    # gdb -ex "dashboard source" -ex "dashboard variables" -ex "dashboard variables -output $tty_new" -ex "dashboard source -output $tty_new_2" -ex "start" "$@"
    tmux a -t DEV:debug.$id_1
}
```
it is a little complex to read cmd args by `echo $Args | xargs -I "{}" ...`, then more complex to read $tty_new,etc
if 
```bash
gdb -ex "dashboard source" -ex "dashboard variables" -ex "dashboard variables -output $tty_new" -ex "dashboard source -output $tty_new_2" -ex "start" "$@"
```
then would be stuck 

I hope someone can help me.

**Comment by nicm** [comment]
Put them in tmux environment or user options with `tmux setenv` or `tmux set` then you can use `-F` and expand them with formats such as `#{MYVAR}` or `#{@myopt}`.

**Comment by nicm** [comment]
Maybe `eval "$(tmux display -p 'gdb #{@myargs}')"`?

**Comment by czg-sci-42ver** [comment]
Thanks very much
Do you means like `tmux send-keys -t $sid:$wid.$id_1 "eval '$(tmux display -p -t $sid:$dwid.$id_1 "gdb #{ARGS}")'" C-m`, this works
but if put quote argument to gdb
may still need **escape "** like `"eval \""` and `"\"`
```bash
tmux send-keys -t $sid:$wid.$id_1 "eval \"" "$(tmux display -p -t $sid:$dwid.$id_1 "gdb #{ARGS} -ex 'dashboard source' -ex 'dashboard variables' -ex 'dashboard variables -output #{t1}' -ex 'dashboard source -output #{t2}' -ex 'start'")" "\"" C-m
```
with `set -v -x -T` I found the above command run
```bash
eval "gdb ./nan -ex 'dashboard source' -ex 'dashboard variables' -ex 'dashboard variables -output /dev/pts/3' -ex 'dashboard source -output /dev/pts/4' -ex 'start'"
```

So the **escape "** can't be avoided if with too many quotes needed.

**Comment by nicm** [comment]
You might be better running a script rather than using `send-keys`.
