### ISSUE TITLE
Problem building tmux with utempter

### ISSUE THREAD

**Issue by xapple** [tmux/tmux#350]
Tmux seems like a really useful little utility, but often it is not available on servers that are using certains distributions, one example because that's the one I'm fighting with: `SUSE Linux Enterprise Server 11 SP3`

This would not be a problem, if it was not exceptionally hard to build. Normally such as small script would do the job:

    mkdir -p ~/programs/tmux
    mkdir -p ~/test
    cd ~/test
    wget -O tmux-2.1.tar.gz https://github.com/tmux/tmux/releases/download/2.1/tmux-2.1.tar.gz
    tar xf tmux-2.1.tar.gz
    cd tmux-2.1
    ./configure --prefix=$HOME/programs/tmux
    make
    make install

But that fails at the configure step, complaining about the absence of libevent. So, such a depencendy should be easily solved with the following script:

    mkdir -p ~/programs/libevent
    cd ~/test
    wget -O libevent.tar.gz https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz
    tar xf libevent.tar.gz
    cd libevent-*/
    ./configure --prefix=$HOME/programs/libevent
    make
    make install

But then returning to tmux at the make step (and after adding `./configure CFLAGS="-I$HOME/programs/libevent/include" LDFLAGS="-L$HOME/programs/libevent/lib"`) it fails with the following error:

    server-fn.o: In function `server_destroy_pane':
    server-fn.c:(.text+0xabc): undefined reference to `utempter_remove_record'
    window.o: In function `window_pane_spawn':
    window.c:(.text+0x3c00): undefined reference to `utempter_add_record'
    window.o: In function `window_pane_destroy':
    window.c:(.text+0x3dd0): undefined reference to `utempter_remove_record'
    collect2: ld returned 1 exit status
    make: *** [tmux] Error 1

And I seem unable to locate a project page for `utempter`. How is one supposed to install tmux ? Why don't you distribute precompiled binaries for x86_64 ?

**Comment by nicm** [comment]
Probably the utempter on your system is too old, you can try this diff 
[tmux-no-utempter.diff.txt](https://github.com/tmux/tmux/files/190598/tmux-no-utempter.diff.txt) then configure --without-utempter

**Comment by xapple** [comment]
You know, I really don't understand this Linux habit of asking **users** to compile programs. It always ends in tears. I solved it, with a service that distributes these precompiled binaries that everyone wants. You should seriously consider distributing them too, because it was a bit hard to find. In the end this is the installation:

    mkdir -p ~/programs
    cd ~/programs
    git clone git@github.com:minos-org/minos-static.git
    export PATH="$PATH:$HOME/programs/minos-static"
    
    mkdir -p ~/test
    cd ~/test
    static-get tmux
    tar xf tmux-1.9a.tar.xz
    mv bin/tmux ~/bin/tmux

**Comment by nicm** [comment]
Actually, this is probably a better solution, check for utempter_add_record which only appears in the new API (unlike utempter.h which is in both): [tmux-utempter-lib.diff.txt](https://github.com/tmux/tmux/files/190603/tmux-utempter-lib.diff.txt)

**Comment by xapple** [comment]
I tried your patch, just because. Now the make step stops earlier:

    $ make
    WARNING: 'aclocal-1.15' is missing on your system.
             You should only need it if you modified 'acinclude.m4' or
             'configure.ac' or m4 files included by 'configure.ac'.
             The 'aclocal' program is part of the GNU Automake package:
             <http://www.gnu.org/software/automake>
             It also requires GNU Autoconf, GNU m4 and Perl in order to run:
             <http://www.gnu.org/software/autoconf>
             <http://www.gnu.org/software/m4/>
             <http://www.perl.org/>
    make: *** [aclocal.m4] Error 127

I tell you it always ends in tears, go the precompiled way !

**Comment by nicm** [comment]
You need to install autoconf and automake and run "sh autogen.sh && ./configure".

A precompiled binary would not help you here because it would be linked against the latest version of utempter, so it would not run on your system. If you want a binary, you will need to talk to the packagers for your platform.

**Comment by xapple** [comment]
Of course I'm thinking of a statically linked precompiled binary.

The packagers are useless. Wherever it's `apt-get` or `yum` they never thought a `--user` option would be useful and you can only run those programs if you own the machine and are `sudo` on it. I'm just a user amongst hundreds with a size and CPU quota. If you want to know it's the login-node of this computer: http://top500.org/system/177826

**Comment by nicm** [comment]
Even if I had the time, interest or resources to distribute binaries for
even a few platforms, static linking would defeat the purpose of, well,
dynamic linking. And I would be duplicating the work of packagers, useless
or otherwise.

If you don't like package management on one system, you can always use
another.

tmux is not hard to build anyway, you are just unlucky enough to have a
very old version of an optional dependency, which it does not detect
properly.

**Comment by xapple** [comment]
It would defeat dynamic linking, yes, it would also defeat the problem of not having tmux working.

You say a "few platforms", you just need to target one: `x86_64` that's really what most people use.

I can't use another package management system, I don't have any access except to my home directory through SSH.

I don't think I'm that unlucky in my situation, look at all the comments on this gist for instance https://gist.github.com/ryin/3106801

Anyways, I suppose we are not going to resolve a decade of developer and system administrator centric software distribution and suddenly make it user centric in this github issue.

I thank you for your help !

**Comment by nicm** [comment]
I have applied this fix, so tmux should ignore utempter if a version with the old API is not installed.

**Comment by xapple** [comment]
OK well that's nice !

In the end, this service that is more in touch with today's users and distributes precompiled library did the job: https://github.com/minos-org/minos-static

You use it just like this:

    sh <(wget -qO- http://s.minos.io/s) -x tmux-2.0

**Comment by nicm** [comment]
Yes, there is someone (or multiple) who build binaries already for most platforms.

**Comment by xapple** [comment]
I have a feeling that you mean linux distro when you say "platform" ? The only platform that is target is `x86_64` here. This binary will work with any linux.

**Comment by nicm** [comment]
I mean a combination of operating system, distribution, version and
processor. I don't have the resources to build binaries for even a
subset, and if I built only the popular ones - well, I would be
providing something that most people don't need, and duplicating what is
already available for those that do (as you have found).

I support building tmux from source; packagers support binary packages
(whether it be Yum, MacPorts, pkgsrc, OpenCSW, or something else).

I don't think you are going to see a change in this model anytime
soon. In any case, if you try Git now or wait for (probably) 2.2 it
should build on your system.

**Comment by xapple** [comment]
It's all working good now for me, so it's just a discussion about distribution methods from here on. But that can be interesting.

I don't think the combination of operating system, distribution, version and processor matter so much. There is really only one thing you need to target to satisfy 95% of your user. That's: Linux, latest version and x86_64. (All the OS X users have homebrew that also has precompiled binaries). It costs you almost nothing to just host that file in the release section of github and make your users happy. It was hard to find that alternate provider of binaries. And you should want your users to use your product easily.

**Comment by nicm** [comment]
I don't agree and I am not going to distribute binaries.

**Comment by xapple** [comment]
OK, that's your choice.

It's funny because that's actually the only advantage that `screen` still has over `tmux` today: the widespread availability. From my point of view, you should be aiming to bridge that gap and not force users to build thing. 

Anyways, happily as I have found out there are these new services that can fill this need.
