### ISSUE TITLE
Is it possible to reorder tmux panes by dragging them using mouse?

### ISSUE THREAD

**Issue by j-rahman** [tmux/tmux#3503]
### Issue description
This is similar to issue #656 but, instead of windows in the status bar, I would like to drag the borders of panes in order to rearrange them within a single window.

Is that possible? If yes, could you please show me how? If not, might I suggest this as a feature request? Thank you.

### Required information

* tmux version: `tmux 3.1c`.
* Platform: `Linux x86_64 RHEL 8.7 (Ootpa)`.
* $TERM inside and outside of tmux: `screen-256color` and `xterm-256color`.

**Comment by nicm** [comment]
Not at the moment, I tried to do this before and it didn't work...

**Comment by nicm** [comment]
Added to todo list.
