### ISSUE TITLE
Tmux won't auto-rename the windows for current app

### ISSUE THREAD

**Issue by umermasood** [tmux/tmux#3504]
### Issue description

Just switched from bash to zsh and every tmux window I launch has the name set to "zsh".

Basically the auto rename of windows is not working, It used to work in bash. for example, when I used to launch vim in a new window, tmux would auto rename the current window to "nvim".

What might be causing this behavior? Any kind of help would be appreciated. Thanks.

### Required information

* Version 3.2a
* Linux x86_64
* xterm-256color

[tmux-client-18263.log](https://github.com/tmux/tmux/files/11059176/tmux-client-18263.log)
[tmux-out-18265.log](https://github.com/tmux/tmux/files/11059177/tmux-out-18265.log)
[tmux-server-18265.log](https://github.com/tmux/tmux/files/11059162/tmux-server-18265.log)

**Comment by nicm** [comment]
Show server log please.

**Comment by umermasood** [comment]
Uploaded server logs

**Comment by nicm** [comment]
Don't see anything wrong here, zsh must be starting processes differently which means tmux cannot work out what the current process is.

**Comment by umermasood** [comment]
Just found out it's not a tmux related issue. Tmux works fine. This behavior was caused by installing a plugin.
