### ISSUE TITLE
Feature request: copy-* commands raw/html mode

### ISSUE THREAD

**Issue by FractalBoy** [tmux/tmux#3505]
### Feature request

Currently all of the copy-* commands copy just the text that is highlighted, stripping any attributes. I am requesting a feature of a new argument to those commands that allows you to pass a format to the command. The ideas I have right now are:

* plain or text (functions like today)
* raw (prints ANSI control sequences)
* html (formats as HTML, using either a stylesheet or inline styles)
* rtf (formats as RTF)

The RTF one is probably unnecessary but I thought I'd include it. At the very least I would like the "raw" format.

This would allow easy copy/paste of data including any colors or other attributes.

I took a look at window-copy.c, but it seems like I would need to create some sort of virtual tty to write the grid cells to, and then somehow copy off of that in order to implement "raw" format.

For HTML, it could open a tag (such as &lt;span&gt;) every time a grid cell has a different attribute than the previous one, and apply a different style. However, this probably requires some sort of stack to ensure we correctly open and close tags, and may also be complicated.

Thoughts?

**Comment by nicm** [comment]
Not keen on HTML or RTF.

You can use `grid_stringify_cells` to generate ANSI in the same way as `capture-pane` does. It'd probably be best to add new commands (`copy-pipe-annotated`? `formatted`? not sure) since flags to copy mode commands don't work that well.

**Comment by FractalBoy** [comment]
Oh, cool, I thought everything had to go through `tty_attributes`.

`copy-pipe-raw`?

**Comment by FractalBoy** [comment]
Did you mean `window_copy_stringify`? I can't find `grid_stringify_cells`.

**Comment by nicm** [comment]
No, you are just going from grid -> string. `window_copy_copy_line` does not currently use `grid_string_cells` but I don't see why it couldn't use it (maybe with some changes).

`-raw` suffix would be fine.

**Comment by nicm** [comment]
Sorry it is `grid_string_cells`.

**Comment by FractalBoy** [comment]
Thanks. I'll take a stab at this then.
