### ISSUE TITLE
After tmux v3.2, enter vim than resize terminal and than exit vim that lead screen messed up

### ISSUE THREAD

**Issue by fengyichui** [tmux/tmux#3510]
Hi,

After tmux v3.2 (include v3.2), the follow step will lead screen messed up:
1. Enter vim (may `vim Makefile`)
2. Resize terminal (may maximize the terminal window)
3. Exit vim

![2023-03-27_143442](https://user-images.githubusercontent.com/17896291/227860732-ee4ac0b3-1849-4662-b13a-742337252c19.png)

But v3.1c is good.
I also test the lastest master version and I remove the `~/.tmux.conf`, `~/.vim/` and `~/.vimrc` files, the issue exists.

> Linux x86_64
> tmux 3.2
> tmux-256color
> mintty
> WSL1

**Comment by nicm** [comment]
tmux logs?

**Comment by fengyichui** [comment]
The logs: [tmux-log.zip](https://github.com/tmux/tmux/files/11076483/tmux-log.zip)

**Comment by fengyichui** [comment]
What can I do to help with this?

**Comment by nicm** [comment]
I don't see vim turning on the alternate screen, does this still happen if you run with the default vim config (-uNONE)?

Does this happen if you try without WSL (eg putty to a Linux host)? WSL appears to be full of terminal bugs.

**Comment by fengyichui** [comment]
This still happen with the `vim -u NONE Makefile`.
I remove the ~/.tmux.conf, ~/.vim/ and ~/.vimrc files, the issue exists.

I use putty to login my Ubuntu22.04 server (not WSL), this still happen.

**Comment by nicm** [comment]
Does this fix it?
~~~~
nicholas@macbook-pro:~/tmux$ git diff
diff --git a/screen.c b/screen.c
index 12ca4d17..a9b7d40e 100644
--- a/screen.c
+++ b/screen.c
@@ -625,7 +625,7 @@ screen_alternate_off(struct screen *s, struct grid_cell *gc, int cursor)
         * before copying back.
         */
        if (s->saved_grid != NULL)
-               screen_resize(s, s->saved_grid->sx, s->saved_grid->sy, 1);
+               screen_resize(s, s->saved_grid->sx, s->saved_grid->sy, 0);

        /*
         * Restore the cursor position and cell. This happens even if not

**Comment by fengyichui** [comment]
This fix it. I've tested and it works well!
