### ISSUE TITLE
xterm-256color sgr0 (exit_attribute_mode) results in trailing ^O in less -R output

### ISSUE THREAD

**Issue by ericvw** [tmux/tmux#3511]
### Issue description

I use the `fish` shell, and when running [ `fish_delta`](https://fishshell.com/docs/current/cmds/fish_delta.html) in `tmux`, I received output with trailing `^O`(i.e., Ctrl-O):

```
Changed^O: /Users/eric/.config/fish/conf.d/editor.fish
--- /dev/null   2023-03-28 15:03:33.000000000 -0400^O
+++ /Users/eric/.config/fish/conf.d/editor.fish 2022-04-26 16:04:09.000000000 -0400^O
@@ -0,0 +1,5 @@
+if status is-login^O
+    # Set default editor.^O
+    set -gx EDITOR nvim^O
+    set -gx VISUAL $EDITOR^O
+end^O
```

It turns out that [`fish_delta` uses `less -R`](https://github.com/fish-shell/fish-shell/blob/bc04abe3eca950c231fec322c8339e3a82437e12/share/functions/fish_delta.fish#L77) to capture and page its output and uses [`set_color normal`](https://fishshell.com/docs/current/cmds/set_color.html) to reset colors where `^0` is being displayed. In digging into `fish`'s codebase it is eventually obtaining the value `sgr0` from the set `TERM`.

`man less` indicates `-R` *only* recognizes ANSI "color" escape sequences of the form `ESC [ ... m`.

When checking what `sgr0` for `tmux-256color`, I discovered:
``` console
$ infocmp tmux-256color | grep -E -o 'sgr0.*?,'
sgr0=\E[m\017,
```
Thus, explaining the trailing `^O` characters being observed.

With all that being said, I'm not sure if this is a bug with `tmux` because `less -R` is behaving as described.

However, I wanted to start with `tmux` to see if Ctrl-O ("Switch to Standard Character Set" according to https://www.invisible-island.net/xterm/ctlseqs/ctlseqs.html) is necessary or if `\E[0;10m` (from https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters) could be used instead?

If `\E[m\017` is correct and desired, I will direct my efforts towards the `fish` shell to see what adjustments can be made.

### Required information

* tmux version (`tmux -V`).

```console
$ tmux -V
tmux 3.3a
```

* Platform (`uname -sp`).

```console
$ uname -sp
Darwin arm
```

* $TERM inside and outside of tmux (`echo $TERM`).

```console
$ echo $TERM
xterm-256color
$ tmux
$ echo $TERM
tmux-256color
```

**Comment by nicm** [comment]
SGR 0 does not affect character set so it is not equivalent. There is an alternative - to switch G0 rather than changing to G1. This is what xterm does (its smacs is \E(0 and rmacs and sgr0 use \E(B instead of ^N and ^O). This would also work for tmux.

But changing terminfo for this will be more trouble than it's worth, and even were it changed it would take years to propagate. If you wanted to try you need to talk to the terminfo maintainer (Thomas Dickey) but I don't think there is a compelling case for changing this.

Your best bet is to either change the tmux terminfo entry yourself locally, or you could see if less could be persuaded that -R should also strip C0 characters.

**Comment by nicm** [comment]
Oh maybe SGR 10 is meant to do something with character set, who knows? In any case tmux does not support it and I don't think anything else does either.

**Comment by ericvw** [comment]
@nicm, thank you for the response, and it's helped me learn more about all of this!

> Your best bet is to either change the tmux terminfo entry yourself locally, or you could see if less could be persuaded that -R should also strip at least these C0 characters.

I'll use `sgr0=\E(B\E[m`, `smacs=\E(0`, and `rmacs=\E(B` locally. 

I'll explore further with the `less` maintainer and potentially the terminfo maintainer (Thomas Dickey) after I internalize all of this.

**Comment by ericvw** [comment]
Thanks, @ThomasDickey, for your response — I almost sent you an email and stopped when I noticed your comment.

I'll direct my energy and focus to `less` to see how this can be addressed.

**Comment by ThomasDickey** [comment]
yes... my code for stripping the alternate-character stuff might miss some detail, but MacOS definitely has this feature.

**Comment by ericvw** [comment]
@ThomasDickey in this case, `fish` is emitting the control sequences, whereas `less -R` is reading the output from `fish` to interpret and render the colors, if I understand correctly. I'm still firming up my understanding of all these moving parts, so I apologize if I misunderstand something.

I'll see if `less` is willing to strip out those characters when `-R` is used, as @nicm mentioned in https://github.com/tmux/tmux/issues/3511#issuecomment-1487506299.

@ThomasDickey, is it possible, and worth it, to update the `tmux` and `tmux-256color` terminfo entries with `sgr0=\E(B\E[m`, `smacs=\E(0`, and `rmacs=\E(B`?

**Comment by ThomasDickey** [comment]
If `less -R` only recognizes **`\E[`** (CSI), then it shouldn't do any better with the **`\E(`**  and **`\E)`**(SCS) flavors.

tmux's sgr0 is the same as screen's (tmux could use either, of course).

That **`\E[0;10m`** is likely to run into problems with some version of tmux, and is likely also to have some portability problem.

(Agreeing with nicm that changing stuff like this isn't quick - for MacOS in particular don't expect change "soon").

**Comment by ericvw** [comment]
I appreciate the responses and have learned much in this discussion.

For anyone who stumbles across this, changing `sgr0=\E(B\E[m`, `smacs=\E(0`, and `rmacs=\E(B` in `tmux` or `tmux-256color` terminfo sources and recompiling with `tic` is a viable workaround.

I created https://github.com/gwsw/less/issues/357 to see if `less` is willing to enhance how `-R` handles `^O`.
