### ISSUE TITLE
In Alacritty, some of their hotkeys stop working

### ISSUE THREAD

**Issue by 097115** [tmux/tmux#3516]
## Description:

When running tmux in Alacritty, some of their default hotkeys stop working:

  - the default `alacritty.yml` has `<Control-Shift-u>` mapped to toggle their "Hints" mode: after starting `tmux`, it stops working;
  - same with `<Shift-PgUp / PgDn / Home / End>`: by default, they navigate the scrollback, and yet under `tmux` they return the following sequences: `^[[5;2~ / ^[[6;2~ / ^[[1;2H / ^[[1;2F` but do not scroll.

## Info:

platform: Linux x86_64
terminal: alacritty 0.11.0
multiplexer: tmux next-3.4
`$TERM`: tmux-256color

## Logs:

via `alacritty --config-file /dev/null --print-events` and  `tmux -L test -f /dev/null -vv`:

  - when `<S-C-u>` was pressed:
    - alacritty: http://ix.io/4stA
    - tmux: according to the timestamps, nothing was present in the logs when the hotkey was pressed
  - when `<S-PgUp / PgDn / Home / End>` were pressed:
    - alacritty: http://ix.io/4syf
    - tmux: http://ix.io/4sye

## Additionally:

The same issue @ Alacritty's tracker (discarded and closed): https://github.com/alacritty/alacritty/issues/6832

**Comment by nicm** [comment]
tmux has no control over alacritty hotkeys. Probably scrollback is disabled because tmux enters the alternate screen, this is standard for all terminal emulators. Terminal scrollback is useless in tmux anyway, you should use copy mode.

**Comment by nicm** [comment]
If tmux does not receive the keys, alacritty must be handling them. Why the mode doesn't work I can't really help you, perhaps it looks for stuff in the incoming data (ie before display rather than after) and tmux breaks it up into multiple pieces so it can't find it? That seems to be what @chrisduerr is suggesting anyway. tmux is definitely not bound by how the data comes in, it will split up, remove or draw out of order if that seems most effective, there is a lot of that sort of thing in order to support multiple panes and to try and have them perform well on slow terminals.

**Comment by 097115** [comment]
@nicm 

Thanks again for the reply -- and I must admit, I missed some bits about this "Hints" mode from the start: in Alacritty + tmux, it **does** work for the usual URLs. But instead it fails for filenames, which Alacritty recognizes thanks to, e.g., `ls`'s `--hyperlink=always` option (and similar software).

Thus, it's a wrongly worded issue, it's not that some hotkeys stop working but instead something happens with the certain propgrams' output, and I'm really sorry for the misuderstanding and the lack of meticulousness on my side.

So, when you say:

> perhaps it looks for stuff in the incoming data (ie before display rather than after) and tmux breaks it up into multiple pieces so it can't find it?

I understand it like this: when a user does, for instance, `ls -a --hyperlink=always`, tmux tweaks something in the output in such a way that Alacritty doesn't see URIs on the screen and therefore doesn't start its "Hints" mode.

And then this sounds like a problem on tmux's side, no? But probably it's too hard to catch?
