### ISSUE TITLE
command-prompt '-i' option is broken

### ISSUE THREAD

**Issue by Koston-0xDEADBEEF** [tmux/tmux#3517]
the `command-prompt` option `-i` has multiple issues. It works for incremental searching in copy mode, but beyond that, it barely works at all. Issues encountered:

- `-I "text"` option doesn't work at all, prompt is always empty.
- '%%' always expands with a `=` prefix, eg. typing "hello" actually expands into `=hello`.
- `%%` expansion has some race condition, eg. `display-value -v "#(echo '%%' | tr -d '=')"` works sporadically; erasing one character and re-typing it will work, but next is again random if it works or not.

* tmux version 3.3a
* Platform macOS 13.2.1
* $TERM outside: xterm-256color, inside: tmux-256color (terminfo compiled for tmux)

What I was trying to achieve is renaming current pane title, which is visible to the user, so changing it is immediately obvious:

```
set -g pane-border-format "#{pane_title}"
set pane-border-status top
bind , command-prompt -i -I "#{pane_title}" { select-pane -T '%%' }
```

FWIW, it *can* be made to work, with this mother of workarounds:

```
bind , command-prompt -I "#T" -p "Pane #{pane_index} title:" -i { setenv -h -F pname '%%' ; select-pane -T '#{s/^=//:pname}' }
```

Fixing this isn't terribly important, but it should be addressed somehow; eg. restricting `-i` use to copy mode.

**Comment by nicm** [comment]
It will always prefix =, + or - to tell you whether it was an update, forward or reverse search.

Using `#()` will probably not work reliably, so you are better to use the builtin substitute.

I don't see any real justification for restricting this flag since, as you say, it can be used.

**Comment by Koston-0xDEADBEEF** [comment]
You are not going to address

* The `-I` option not working at all
* `#()` being very unreliable

?
