### ISSUE TITLE
Server socket listen queue overflow on FreeBSD

### ISSUE THREAD

**Issue by iblis17** [tmux/tmux#352]
Hi!
I got this message on my FreeBSD 10.1 box.
```
Mar 29 03:19:56 imfsa kernel: sonewconn: pcb 0xfffff8001c94d960: Listen queue overflow: 25 already in queue awaiting acceptance (8 occurrences)
```
and 
```
% netstat -anA | grep fffff8001c94d960                                                                                                     
fffff8001c94d960 stream      0      0 fffff8006c70c1d8        0        0        0 /tmp/tmux-1001-inner
```

Also, i got the number of backlog on tmux server:16
ref: https://github.com/tmux/tmux/blob/master/server.c#L126

It seems that `16` is too small for my daily use.
I am willing to make a PR for the configurable backlog.
What is the best way to configure it? *env var* just flashed into my mind.

**Comment by nicm** [comment]
Just bump it to 64 or 128, there is no need for it to be configurable.

Index: server.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/server.c,v
retrieving revision 1.157
diff -u -p -r1.157 server.c
--- server.c	19 Jan 2016 15:59:12 -0000	1.157
+++ server.c	29 Mar 2016 07:20:27 -0000
@@ -124,7 +124,7 @@ server_create_socket(void)
 		return (-1);
 	umask(mask);
 
-	if (listen(fd, 16) == -1)
+	if (listen(fd, 128) == -1)
 		return (-1);
 	setblocking(fd, 0);

**Comment by iblis17** [comment]
Hi @nicm !
Thanks for your reply.
Will this patch be merged in the future?

**Comment by nicm** [comment]
It is done now, thanks.
