### ISSUE TITLE
PWD with dot-dot components (non-corformant with POSIX)

### ISSUE THREAD

**Issue by cirho** [tmux/tmux#3520]
### Issue description
When spawning a new pane with a non-absolute custom current working directory (by using `-c` flag), `tmux` simply concatenates addition. 
https://github.com/tmux/tmux/blob/b9524f5b72d16bd634fc47ad1a4a9d3240bd4370/spawn.c#L228-L236
Without any kind of further checks the path is passed to `chdir` and set as `$PWD`.
https://github.com/tmux/tmux/blob/b9524f5b72d16bd634fc47ad1a4a9d3240bd4370/spawn.c#L402-L409
Although `chdir` verifies existence of a directory, it does not care whether the path contains dot-dot component or not. So `tmux` may end up setting e.g. `/home/user/.config/../` as `$PWD`. 

Citing [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/):
> This variable shall represent an absolute pathname of the current working directory. It shall not contain any components that are dot or dot-dot. The value is set by the [cd](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cd.html) utility, and by the [sh](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html) utility during initialization.
https://pubs.opengroup.org/onlinepubs/9699919799/

So we now know that the current behavior is not `POSIX`-conformant.  

## Consequences of the current behavior
Aside from an ugly prompt in some shells (`bash`, `fish`), I haven't found any bugs, but surely they exist somewhere.

## Expected behavior
`tmux` should resolve the path into an absolute one without any dot-dot and dot components, but preserving symlinks.
## Reproduction
```bash
# tmux.conf
set -g default-shell /bin/bash
```
```bash
cd ~/
mkdir foo
tmux -Ltesting -f tmux.conf  new-session -c 'foo/../' 
# Inside tmux
echo $PWD
```

### Required information
* tmux version `3.3a` and  `master`
* Platform `Linux 6.1.22 x86_64 glibc 2.36`.
* $TERM `tmux-256color`, `alacritty`

**Comment by nicm** [comment]
tmux is not specified by POSIX so it doesn't have to set PWD any particular way. It is up to POSIX utilities like `sh` to ensure that `PWD` conforms.

Passing the path through `realpath` would resolve symlinks and defeat the purpose of setting `PWD` in the purpose. We could add custom code to remove `..` and `.`, it seems a bit unnecessary to me but if you want to do it I will accept it.
