### ISSUE TITLE
$PATH is inconsisent inside tmux

### ISSUE THREAD

**Issue by sokinpui** [tmux/tmux#3522]
Inside tmux:
```
 ~ $ uname -sp && tmux -V && echo $TERM
Darwin arm
tmux 3.3a
xterm-256color
 ~ $
```

Outside tmux:
```
 ~ $ uname -sp && tmux -V && echo $TERM
Darwin arm
tmux 3.3a
xterm-256color
 ~ $
```

Platform:
```
MacOS : 12.6
Alacritty : 0.11.0
```

The $PATH env variable is not the same outside and inside tmux, leading to vim use the system default version instead of homebrew version, which lack the support of `python3`, so some plugins out of work e.g. `Ultisnips`. Also, the color display in tmux seems to not 256 color. 
Inside tmux:
```
 ~ $ echo -e ${PATH//:/\\n}
/Users/mac/.local/bin
/usr/local/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/VMware Fusion Tech Preview.app/Contents/Public
/Library/TeX/texbin
/Library/Apple/usr/bin
/Users/mac/.local/bin
/opt/anaconda3/bin
/opt/anaconda3/condabin
/opt/homebrew/bin
/opt/homebrew/sbin
```

Outside tmux:
```
 ~ $ echo -e ${PATH//:/\\n}
/Users/mac/.local/bin
/usr/local/bin
/opt/anaconda3/bin
/opt/anaconda3/condabin
/opt/homebrew/bin
/opt/homebrew/sbin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/VMware Fusion Tech Preview.app/Contents/Public
/Library/TeX/texbin
/Library/Apple/usr/bin
```

I have no idea why the order of vim version is not the same?
insdie tmux:
```
 ~ $ type -a vim
vim is /usr/bin/vim
vim is /opt/homebrew/bin/vim
```

outside tmux:
```
~ $ type -a vim
vim is /opt/homebrew/bin/vim
vim is /usr/bin/vim
```

The color in tmux and in alacritty is not the same:
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/104958540/230719756-626fcc4b-3697-4f1c-b7ca-2526932743ef.png">

**Comment by nicm** [comment]
This is probably to do with how your shell startup files are executed and what they do. Perhaps they just append to the existing PATH or move new entries to the end?

Panes created from inside tmux (that is, not by running `tmux neww` or similar from a shell) tmux will start with `PATH` from the shell tmux was started with.
