### ISSUE TITLE
Hyperlinks are reset with `\e[0m`

### ISSUE THREAD

**Issue by ltrzesniewski** [tmux/tmux#3525]
### Issue description

OSC-8 hyperlinks get reset with `\e[0m` inside tmux, but the reset color code doesn't reset them outside of tmux.

Repro:

```sh
tmux -T hyperlinks
printf '\e]8;;https://github.com\e\\Hello,\e[0m world!\e]8;;\e\\\n'
```

Outside of tmux:

![image](https://user-images.githubusercontent.com/7913492/231580251-d83f2350-4bfe-4375-9169-34756147feef.png)

Inside tmux:

![image](https://user-images.githubusercontent.com/7913492/231580428-7d16ae19-da9f-49df-9c2c-c30857455fd8.png)

My understanding of the [hyperlink spec](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) is that the hyperlink status should only be changed though an OSC-8 code:

> Following this, all subsequent cells that are painted are hyperlinks to this target. A hyperlink is closed with the same escape sequence, omitting the parameters and the URI but keeping the separators

I tested this with Windows Terminal, but @097115 reported that this also occurs with kitty and alacritty.

### Required information

* tmux version (`tmux -V`): `tmux next-3.4` (tested with current master b9524f5b72d16bd634fc47ad1a4a9d3240bd4370)
* Platform (`uname -sp`): `Linux x86_64` (this is WSL)
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color`/`xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): [logs.zip](https://github.com/tmux/tmux/files/11216033/logs.zip)

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/11859079/x.diff.txt)

**Comment by ltrzesniewski** [comment]
Yes, it does. Thanks! 🙂

![image](https://github.com/tmux/tmux/assets/7913492/fcfcf41c-52f7-4ee9-9ba4-8c9672039ddf)

(the hyperlinks in this screenshot contain a few reset codes)

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
