### ISSUE TITLE
Is it possible to select words with delimiters on double click? 

### ISSUE THREAD

**Issue by k0va1** [tmux/tmux#3528]
For example in alacritty without tmux I can double click on branch name like this `feature/new_awesome_feature` and full branch name will be selected
[Screencast 2023-04-14 16:10:15.webm](https://user-images.githubusercontent.com/3451694/232068622-10a5e49e-9c85-4cc6-8d0a-e8718742645b.webm)

But in tmux only first or second part
[Screencast 2023-04-14 16:10:47.webm](https://user-images.githubusercontent.com/3451694/232068702-8ee9c357-1155-47b4-9352-3e8c467c8c08.webm)

**Comment by joshbode** [comment]
I believe you're looking for the `word-separators` option.

This is what I set mine to:
```
set -g word-separators " |{}()[]<>`='\"!@#$%^&*:;,?"
```
which supports the select-behaviour I think you're looking for.
(note: it doesn't include `/`, and the `\` is escaping the `"`)

**Comment by k0va1** [comment]
@joshbode thank very much! That's exactly what I wanted, just changed `word-separators` to Alacrity's and it works like a charm

**Comment by joshbode** [comment]
Great! Glad I could help :)
