### ISSUE TITLE
Make main pane static when resizing window with main-horizontal/vertical layout

### ISSUE THREAD

**Issue by mkoskar** [tmux/tmux#3530]
Consider `main-horizontal` and `main-vertical` layouts and configured `main-pane-height` and `main-pane-width` with an absolute value.

When terminal window is resized it would make much more sense to try and keep `main` pane static and instead add/remove height/width from "secondary" pane exclusively. 

Since `main-pane-height` and `main-pane-width` can also be configured with a percentage, next step would be probably take those into account upon resizing too.

Current behavior is mainly annoying not because one would resize terminals often, but when session is created "detached" and then attached, carefully fixed layout is broken. Executing `select-layout` will reset it.

```
$ tmux -f /dev/null -L test new \; set main-pane-width 30 \; splitw -h \; selectl main-vertical
```
[screencast-2023-04-15.1681564929.webm](https://user-images.githubusercontent.com/4387891/232226613-ebd9e621-c631-41a6-bb6b-8379baee2a95.webm)

**Comment by nicm** [comment]
It would be nice to have fixed layouts/layout hints, this has been on the wishlist forever. But it does not work at the moment.
