### ISSUE TITLE
Question: make Ctrl-. and Ctrl-, recognized by Emacs

### ISSUE THREAD

**Issue by illia-danko** [tmux/tmux#3532]
Hello. I'm trying to make a work around to bind non standard key sequences, namely making Ctrl-. and Ctrl-, to be recognized by emacs. I achieved the desire result on alacritty by:

```yaml
key_bindings:
  - {key: Period, mods: Control, chars: "\e[46;5u"} # Ctrl-. on Emacs
  - {key: Comma, mods: Control, chars: "\e[44;5u"} # Ctrl-, on Emacs
```
and it works as expected on plain emacs, however when I started tmux (without any custom configuration) it doesn't work. Is a way to make Ctrl-. and Ctrl-, work under the tmux session as well? Thank you

**Comment by nicm** [comment]
Try setting `extended-keys` to `on` or `always`. If that doesn't work you will need to set them up using `user-keys`.

**Comment by illia-danko** [comment]
Thank you, that helped. `set -g extended-keys always` works for me (however `set -g extended-keys on` doesn't).
