### ISSUE TITLE
User defined key bindings function with SHIFT required

### ISSUE THREAD

**Issue by yixiaoxian** [tmux/tmux#3534]
Hello, my tmux version is 3.3a, installed via Homebrew.
Here are my .conf contents for pane switching:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/7151193/232736715-391b0ba2-935a-4885-87cf-aa362071cc45.png">
However, I have to type C-S-h,j,k,l (or C-H,J,K,L? It is said that it is case-insensitive) for the triggering.
Could someone help to handle it? Thanks.

**Comment by nicm** [comment]
Do you have caps lock on?
