### ISSUE TITLE
Tmux 2.1 and 256 colors issue.

### ISSUE THREAD

**Issue by Magicloud** [tmux/tmux#354]
Hi, I am on Ubuntu Trusty. The tmux from official repository is 1.8. I just compiled 2.1 from Github source (tag 2.1).
When running tmux-2.1 in gnome-terminal, I found that the 256 colors which worked well in 1.8 is somehow messed up.
The major noticeable problem is that the background. It should be some kind of dark blue, but now is grey green. What should I do?

**Comment by nicm** [comment]
What is TERM set to inside and outside tmux?

**Comment by Magicloud** [comment]
It is "screen-256color" inside. And I started `tmux -2` directly from gnome-terminal. It worked before.

**Comment by Magicloud** [comment]
Also noticed that, if I killed all tmux processes, then started it, from shell, or gnome-terminal, it would hang.

**Comment by nicm** [comment]
What is TERM outside tmux?

**Comment by Magicloud** [comment]
If I started tmux from shell, the env would be screen-256color.

**Comment by nicm** [comment]
That is wrong unless you are running tmux inside tmux or screen.

**Comment by Magicloud** [comment]
I have tried to unset the env, no luck.

**Comment by nicm** [comment]
Show me a screenshot of what is wrong.

**Comment by Magicloud** [comment]
Sorry took your time. Seems like something incompatible in my tmux configuration. I cleared them except sourcing solarized colors, and it looked fine. Let me see which command exactly caused this.
Thanks.
