### ISSUE TITLE
paste in vim error

### ISSUE THREAD

**Issue by walkerxk** [tmux/tmux#3540]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.
i copy status-right and paste in vim, then i got Tatus-right, when i do this outside tmux, it's ok.
Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). :tmux next-3.4
* Platform (`uname -sp`). :CYGWIN_NT-10.0-19045 unknown
* $TERM inside and outside of tmux (`echo $TERM`).: inside tmux-256color outside: xterm
* Logs from tmux (`tmux kill-server; tmux -vv new`).
* 
[tmux-client-34421.log](https://github.com/tmux/tmux/files/11303304/tmux-client-34421.log)
[tmux-out-34423.log](https://github.com/tmux/tmux/files/11303305/tmux-out-34423.log)
[tmux-server-34423.log](https://github.com/tmux/tmux/files/11303306/tmux-server-34423.log)

**Comment by nicm** [comment]
No clue what this is about.

**Comment by walkerxk** [comment]
1. i killed all tmux processs
2. i run tmux -vv
3. vi .tmux.conf and press i into insert mode 
4. i copy "status-right" from the file
5. i paste into vi
6. i got Tatus-right in vi
seems like tmux send wrong strings to vim
and i make a screenshot too:
![time](https://user-images.githubusercontent.com/3411710/235076459-ce7b8580-54d0-45c8-a077-7eb955d97d4c.gif)

**Comment by nicm** [comment]
But you aren't in insert mode when you paste?

**Comment by walkerxk** [comment]
sorry, i didn't record full window, i record again, and this is the log of this time.
[tmux-client-33793.log](https://github.com/tmux/tmux/files/11351799/tmux-client-33793.log)
[tmux-out-33813.log](https://github.com/tmux/tmux/files/11351800/tmux-out-33813.log)
[tmux-server-33813.log](https://github.com/tmux/tmux/files/11351801/tmux-server-33813.log)
![time](https://user-images.githubusercontent.com/3411710/235102463-20d7a0ba-a4f0-425a-a0b2-57ad061dfbdf.gif)

**Comment by nicm** [comment]
tmux is writing correctly to vim, this is a problem with vim. Probably it is not correctly recognising the paste bracket sequences.
~~~~
1682671687.031342 writing key 0x10e003 (PasteStart) to %0
1682671687.031374 input_key: \033[200~
1682671687.053233 writing key 0x73 (s) to %0
1682671687.053250 input_key: s
1682671687.053391 writing key 0x74 (t) to %0
1682671687.053406 input_key: t
1682671687.053545 writing key 0x61 (a) to %0
1682671687.053561 input_key: a
1682671687.053698 writing key 0x74 (t) to %0
1682671687.053713 input_key: t
1682671687.053850 writing key 0x75 (u) to %0
1682671687.053866 input_key: u
1682671687.054002 writing key 0x73 (s) to %0
1682671687.054016 input_key: s
1682671687.054149 writing key 0x2d (-) to %0
1682671687.054165 input_key: -
1682671687.054298 writing key 0x72 (r) to %0
1682671687.054313 input_key: r
1682671687.054444 writing key 0x69 (i) to %0
1682671687.054457 input_key: i
1682671687.054574 writing key 0x67 (g) to %0
1682671687.054583 input_key: g
1682671687.054653 writing key 0x68 (h) to %0
1682671687.054662 input_key: h
1682671687.054730 writing key 0x74 (t) to %0
1682671687.054738 input_key: t
1682671687.071962 writing key 0x10e004 (PasteEnd) to %0
1682671687.071979 input_key: \033[201~
~~~~
