### ISSUE TITLE
New scroll commands are not bindable

### ISSUE THREAD

**Issue by mohkale** [tmux/tmux#3541]
### Issue description

Hi, I noticed tmux added commands for scroll-top, scroll-middle and scroll-bottom in the manual but I can't bind to them or inspect them. I was trying to set this up like so:

```text
bind -T copy-mode-vi z switch-client -Tcopy-mode-scroll
bind -T copy-mode-scroll t scroll-top
bind -T copy-mode-scroll z scroll-middle
bind -T copy-mode-scroll b scroll-bottom
```

But this errors with:

```text
unknown command: scroll-top
unknown command: scroll-middle
unknown command: scroll-bottom
```

Is there something missing in the command definition? I'd be surprised if the manual lists the commands but my build of tmux doesn't have them.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux next-3.4
* Platform (`uname -sp`). Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`). tmux-24bit
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
You need `send -X`, https://github.com/tmux/tmux/wiki/Getting-Started#copy-mode-key-bindings or look at the existing bindings.

**Comment by mohkale** [comment]
Ah, thank you. I always get confused by how copy-mode commands aren't actual commands. This works perfectly.

```elisp
tmux bind -T copy-mode-vi z switch-client -Tcopy-mode-scroll
tmux bind -T copy-mode-scroll t send-keys -X scroll-top
tmux bind -T copy-mode-scroll z send-keys -X scroll-middle
tmux bind -T copy-mode-scroll b send-keys -X scroll-bottom
```
