### ISSUE TITLE
Updating window title from path in 3.0

### ISSUE THREAD

**Issue by elliottslaughter** [tmux/tmux#3546]
### Issue description

I'm upgrading from version 1.8 to 3.0a, and despite reading through the change log and related issues like #2586 and #1688, I cannot figure out how to replicate the old title-updating behavior that I had before.

Old behavior: the window title contained the path, truncated to 32 characters. Note: it updated instantly as well.

New behavior: the window title contains the program name (e.g., `bash`) and updates with a delay of a few seconds.

As best I can tell, here's the relevant part of the old configuration I used to do this:

```
set-option -g set-titles on
set-window-option -g window-status-format '#[fg=white,bold]#F#I#[default]$ #32W '
set-window-option -g window-status-current-format '#[fg=white,bold]#F#I#[default]$ #32W '
```

(Note: I've updated the styles to get that part working (well, minus the truncation to 32 characters), but it seems to not affect the window title.)

And then in my `~/.bashrc` (which I source from `~/.bash_profile`):

```bash
# Update title automatically with current directory within tmux.
if [ -n "$PS1" ]; then
    case "$TERM" in
    screen-256color)
        PS1='\[\033k\w\033\\\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ ';;
    *)
        PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ ';;
    esac
fi
```

To be honest, I'm not an expert on bash `PS1` so I'm not entirely sure how this worked in the old version, but I assume it's sending an escape sequence to tmux to tell it that the window has changed, and somehow tmux is no longer responding to that. I tried reading through the tmux change logs for several versions and haven't been able to find anything relevant.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 3.0a
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): `screen-256color` inside and `xterm-256color` outside.
* Logs from tmux (`tmux kill-server; tmux -vv new`): not sure this is relevant but happy to get this if it would help.

Thanks!

**Comment by nicm** [comment]
You need to turn `allow-rename` on.

**Comment by elliottslaughter** [comment]
Thanks, that's it!

What about the `#32W` syntax for truncating the window name to 32 characters? What's the modern replacement for that?

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/Formats#trimming-and-padding

You want `window_name`.

**Comment by elliottslaughter** [comment]
Thanks again!
