### ISSUE TITLE
tmux crashes when selecting text

### ISSUE THREAD

**Issue by fjbaldon** [tmux/tmux#3549]
### Required information

Please provide the following information:

* tmux 3.3a.
* Linux x86_64.
* $TERM inside: screen-256color and outside of tmux: xterm-256color.
* Logs from tmux: tell me where to get the log

**Comment by fjbaldon** [comment]
why was this closed :/

**Comment by nicm** [comment]
No logs, no description.

But it is probably the same as https://github.com/tmux/tmux/issues/3539 anyway.
