### ISSUE TITLE
blank screen after session attach when mobile carier tello (t-mobile)

### ISSUE THREAD

**Issue by yaitskov** [tmux/tmux#3551]
I have a VM in AWS and access it via SSH. tmux version 3.2a.
When I am connected to the Internet via WiFi router there is no issue with attaching to existing tmux session. 
I travel a lot across the US and used many WiFi routers.

Though I have to use mobile hot spot when I am out side and tmux draws blank screen with cursor position restored and don't respond to keyboard. After a minute SSH is closed as non responsive.

Once I get back to home wifi the issue is not reproducible.
This is very strange, because SSH encrypts traffic and connection goes over VPN so how carrier make the difference?

**Comment by nicm** [comment]
Do you have problems with other terminal applications or with high throughput for example copying a file with scp or rsync?

**Comment by yaitskov** [comment]
new tmux session works more stable, but might freeze. I run emacs, htop.
TCP connection parameters must be tuned somehow.

**Comment by nicm** [comment]
This is something to do with your VPN and not a tmux issue.
