### ISSUE TITLE
Memory leak in format_find

### ISSUE THREAD

**Issue by Hripsimee** [tmux/tmux#3553]
The format_find function in the tmux/format.c source file appears to contain a memory leak. Specifically, memory is allocated using xstrdup in line 3524 or 3536:

found = xstrdup(fe->value); // line 3524
or 
found = xstrdup(envent->value);

However, If free(found) in line 3548 is not executed, and one of the subsequent lines (either line 3553 or 3562) is executed, then the memory allocated to found in line 3553 or 3562 will not be freed, resulting in a memory leak.

**Comment by nicm** [comment]
This is a bit vague, what is the path following the `found` label where this is not freed? It's a bit convoluted but it looks OK to me...
