### ISSUE TITLE
memory leak in file_vprint, file_error, file_print_buffer

### ISSUE THREAD

**Issue by Hripsimee** [tmux/tmux#3554]
The file_vprintf function in the tmux/file.c source file appears to contain a memory leak. Specifically, memory is allocated using file_create_with_client in line 207 and xstrdup in line 208:

cf = file_create_with_client(c, 1, NULL, NULL); // line 207
cf->path = xstrdup("-"); // line 208

However, if file_create_with_client in line 207 fails to insert cf to the red-black tree from c->files (due to c->flags == CLIENT_ATTACHED), the memory allocated to cf in line 207 or 208 will not be freed, resulting in a memory leak.

Similar cases are also in file_error, file_print_buffer functions.

**Comment by nicm** [comment]
How can `c->flags & CLIENT_ATTACHED` be false in `file_can_print` but true in `file_create_with_client`?
