### ISSUE TITLE
Permission problem on tmux with ngrok and launchdarkly

### ISSUE THREAD

**Issue by jjairojr** [tmux/tmux#3555]
Im having some troubles with tmux, i'm trying to start my app server and are logging this only on tmux
```
[0] warn: [LaunchDarkly] Received I/O error (read ECONNABORTED) for streaming request - will retry
[1] warn: [LaunchDarkly] Received I/O error (read ECONNABORTED) for streaming request - will retry
````

in ngrok too
```
 reconnecting (Get "https://dns.google.com/resolve?name=tunnel.ngrok.com&type=A": read tcp [2804:14c:bbaf:4fea:548f:363e:eaae:c60c]:61014->[2001
```
Please provide the following information:

Darwin arm
tmux 3.3a
screen-256color

**Comment by nicm** [comment]
No logs, no description of how to recreate, almost certainly not a tmux issue in any case.

**Comment by jjairojr** [comment]
> No logs, no description of how to recreate, almost certainly not a tmux issue in any case.

it is a issue from tmux, why work on normal terminal ?
