### ISSUE TITLE
Clipboard syncing needs to be simpler

### ISSUE THREAD

**Issue by davidsonpoole** [tmux/tmux#3556]
### Issue description

I was unable to sync my system clipboard with tmux clipboard, and narrowed it down to the issue that the OSC52 sequence wasn't being passed through. I worked on this for hours today trying to get it to work and finally found a really obscure fix [here](https://gist.github.com/yudai/95b20e3da66df1b066531997f982b57b) to forwards the "Ms" to the terminal:
set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7"

I just feel like this should be much easier to locate or included in the build somehow.

### Required information

* tmux next-3.4
* Linux x86_64
* xterm-256color
* Logs:
[tmux-client-18898.log](https://github.com/tmux/tmux/files/11390003/tmux-client-18898.log)
[tmux-client-26605.log](https://github.com/tmux/tmux/files/11390004/tmux-client-26605.log)
[tmux-out-26607.log](https://github.com/tmux/tmux/files/11390005/tmux-out-26607.log)
[tmux-server-26607.log](https://github.com/tmux/tmux/files/11390006/tmux-server-26607.log)

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/Clipboard
