### ISSUE TITLE
tmux crash

### ISSUE THREAD

**Issue by sfmqrb** [tmux/tmux#3559]
### Issue description

Hello,

I am experiencing a problem with `tmux`. After pressing `Ctrl-b` and `:`, I pressed `Esc` multiple times and `tmux` crashed. I am running `tmux` on Ubuntu.

### Steps to reproduce

1. Start `tmux` by running `tmux`.
2. Press `Ctrl-b` and then `:`.
3. Press `Esc` multiple times.

### Required information

* `tmux` version (`tmux -V`): `tmux 3.2a`
* Platform (`uname -sp`): `Linux x86_64`
* `$TERM` inside and outside of `tmux` (`echo $TERM`): inside = `screen` outside = `xterm-256color`

Thanks.

**Comment by nicm** [comment]
Does this still happen if you build tmux from master?

**Comment by sfmqrb** [comment]
Yes it still happens.

**Comment by nicm** [comment]
Show logs please.

**Comment by sfmqrb** [comment]
I'm not sure if the Tmux server log may contain any sensitive information, like some unrelated environment variables or file system details. Is there any sensitive information that could be stored in this log? 
The log is about 1 MB in size.
Is it OK if I send the log file to you via email instead of posting it on GitHub publicly?

**Comment by nicm** [comment]
Yes email is OK.

**Comment by sfmqrb** [comment]
> Yes email is OK.

Which email should I send it to?
