### ISSUE TITLE
Tmux 2.1 on OS X 10.8.5 - monitor-activity sporadically not working.

### ISSUE THREAD

**Issue by ghshephard** [tmux/tmux#356]
I've set:
  setw -g monitor-activity on
  setw monitor-activity on

And then set up a simple loop:
  while : ; do date; sleep 5; done

But monitor-activity does not seem to be catching the event reliably.  It either 100% fails, or 100% works.

What's strange, is that *occasionally* this does work - once after something as simple as opening a new window (prefix + c) - but what's odd is that *EVERY* window immediately shows activity when this happens (initially)- and everything then happens exactly as expected (Status line updates, # appears beside the window name) - and once it starts working, it seems to 100% reliably work after that, everywhere.    This behavior of every window showing activity  makes sense - as it looks like there has been some activity in all of the windows for the last 20 minutes or so, so it is reasonable that an activity indicator would appear on them.

But, if I shut down the tmux server, and restart in an attempt to replicate, I'm unable to get it to work again - though, after some fiddling, and the creation of a new window (with prefix+c) I can get monitor-activity to start working.

I'm ready to start debugging, looking at logging code as needed.

It looks like 

-   void alerts_queue
-   int alerts_check_activity
-   void alerts_run_hook
-   int alerts_enabled

Are good places to start to see what's happening.  Any suggestions as to how to debug this other than "Compile the code, add hooks to the various functions, and log the results?"

**Comment by ghshephard** [comment]
I think I have a reproducible case for this issue now.

- tmux # start tmux
- prefix+c # create a new window
- prefix+: setw -g monitor-activity on # Enable monitor activity
- while : ; do sleep 15; date; done # set up a loop to generate activity
- prefix+n # switch to new window.  Wait 30+ seconds - nothing happens.
- prefix+c # create a new window - monitor activity starts working.

**Comment by nicm** [comment]
This works fine for me, is it still the same in Git?

**Comment by ghshephard** [comment]
I downloaded version 2.1 from Git, and did  ./configure && make && ./tmux - I was able to replicate the issue.  Note, if you place setw -g monitor-activity on in the .tmux.conf file, you don't see this issue on OS X 10.8.5.

**Comment by nicm** [comment]
git master is not 2.1

**Comment by ghshephard** [comment]
Tried the exact same (100% reproducible) issue with:

- git clone https://github.com/tmux/tmux.git
- cd tmux/ && sh autogen.sh && ./configure && make && ./tmux

And monitor-activity works fine without creating a new window.  Thanks!
