### ISSUE TITLE
Fix pane across windows

### ISSUE THREAD

**Issue by elexunix** [tmux/tmux#3563]
Hello!
It would be great if it was possible to "fix" a pane across different tmux windows, so that it persisted when you switch windows
Currently, one has to create in new pane in every window where it is needed
For example, you might want to see htop/nvidia-smi in the corner of your terminal
Or, as in my case, I ssh into different machines on different windows (so as to have more space than if I ssh'ed into several machines from small panes), but sometimes I need to do something on the host machine (from which I ssh), and for that I have to create a new pane every time I need to enter a command or create many panes, one in every window, for that purpose

```
$ tmux -V
tmux 3.2a
$ uname -sp
Linux x86_64
$ echo $TERM
screen
```

**Comment by nicm** [comment]
This has been on the todo list for a long time and there is a discussion here https://github.com/tmux/tmux/issues/2449.
