### ISSUE TITLE
Issue #3560

### ISSUE THREAD

**Issue by adrianatrevinoe** [tmux/tmux#3564]
Hello! I had an issue but i thought i did not get a response but it is now closed! The issue was #3560 ,how could i build3.3a or master?

 from the response " Does this still happen if you build 3.3a or master?"

**Comment by adrianatrevinoe** [comment]
Also, the issue temporarily resolves if i use the command tmux -vv -Ltest -f/dev/null new and reload the config.

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/Installing

**Comment by adrianatrevinoe** [comment]
```
git clone https://github.com/tmux/tmux.git
cd tmux
sh autogen.sh
./configure && make
```
i did this earlier but i had no success in fixing it :(

**Comment by nicm** [comment]
After you do that, kill your tmux and run `./tmux` instead and see if it still crashes.

**Comment by adrianatrevinoe** [comment]
it crashed again, i dont really know what is happening i will add my logs again :(
[tmux-client-275136.log](https://github.com/tmux/tmux/files/11481014/tmux-client-275136.log)
[tmux-client-275602.log](https://github.com/tmux/tmux/files/11481015/tmux-client-275602.log)
[tmux-out-275604.log](https://github.com/tmux/tmux/files/11481016/tmux-out-275604.log)
[tmux-server-275604.log](https://github.com/tmux/tmux/files/11481017/tmux-server-275604.log)

**Comment by nicm** [comment]
This log is still from 3.0a you need to either install the 3.3a you built or run it from the build directory.

**Comment by adrianatrevinoe** [comment]
thankyou very much for the help, i really appreciate it. And I'm sorry, after i have done this 
```
git clone https://github.com/tmux/tmux.git
cd tmux
sh autogen.sh
./configure && make
``` 
how could i actually install the version 3.3a, is there any script with the instructions? I can't find it, thankyou and sorry for the bother!

**Comment by nicm** [comment]
Run `make install`.

You may want to remove the existing tmux package so you can't run it anymore.

**Comment by elandorr** [comment]
N.B. Uninstalling something you `make install`-ed is usually a pain. Sometimes code comes with `make uninstall`, but for that you have to keep the build folder around. You can also symlink the binary to your PATH.

**Comment by nicm** [comment]
It's two files.

**Comment by elandorr** [comment]
In this case, but she might be tempted to run around `make install`-ing something else, too. Can get messy real fast.
