### ISSUE TITLE
Neovim + Tmux weird rendering issue

### ISSUE THREAD

**Issue by muzammil-iftikhar** [tmux/tmux#3566]
### Issue description

Neovim running inside Tmux. Whenever I write something inside neovim and lsp kicks in and shows the autocompletion popup, that popup leaves the weird traces behind when it closes.
Continuing with the code, a lot of lsp autocompletion popups leave a lot of traces on screen.

![image](https://github.com/tmux/tmux/assets/33807314/31062226-0871-4fb4-9269-329515873268)

#### When does the issue occur?

It only happens when neovim is running inside tmux. It doesn't happen when neovim is running outside of tmux.

#### What have I tried so far?

Different terminals:
1. Windows terminal 1.16.10262.0
2. Wezterm 20230408-112425-69ae8472

Different neovim configurations:
1. Astronvim
2. NvChad

Upgrading:
1. Tmux from 3.0a to 3.3a
2. Neovim from stable 0.9 to 0.10

Other than that I tried running tmux without any conf file and the issue persisted.

### Required information

Please provide the following information:

* My setup
`ubuntu 20.04 inside wsl 2`
* tmux version (`tmux -V`).
`tmux 3.3a`
* Platform (`uname -sp`).
`Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`).
`Outside: xterm-256color`
`Inside: tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux.zip](https://github.com/tmux/tmux/files/11474881/tmux.zip)

**Comment by nicm** [comment]
Does this only happen on WSL? It seems like their various terminal emulation are a bit buggy. Do you see it if you run the terminal on a real *nix box?

**Comment by muzammil-iftikhar** [comment]
Sorry..  but i don't have the linux box readily available on my machine. I can set one using virtualbox if you want. What do you say ?

**Comment by nicm** [comment]
Maybe try using putty to ssh into the Windows box and see if it still happens?

**Comment by muzammil-iftikhar** [comment]
I gave it a try with mobaXterm by connecting with my wsl distribution and yes the issue didn't happen.
What does that mean ?

**Comment by nicm** [comment]
Possibly it is a bug in the Windows console layer or the terminal emulators you were using before. Can you show me the server log for doing the same as you did in the last log but in mobaxterm?

**Comment by muzammil-iftikhar** [comment]
[tmux.zip](https://github.com/tmux/tmux/files/11485799/tmux.zip)

**Comment by muzammil-iftikhar** [comment]
yes, I can confirm the overflowing of nerd font icons with my setup as well.

**Comment by PookieBuns** [comment]
I also have this issue

**Comment by muzammil-iftikhar** [comment]
After trying so many things past days. I finally moved to installing kitty in wsl using this guide:
[kitty on wsl2](https://github.com/danielbisar/settings/blob/main/guides/kitty-on-windows-with-wsl2.md)
and editing the shortcut with this option to disable hardware-accelerated rendering (as normal was not working for me)
 `LIBGL_ALWAYS_SOFTWARE=1 kitty`

**Comment by lostl1ght** [comment]
@muzammil-iftikhar @nicm Wez has [updated](https://github.com/wez/wezterm/issues/3704#issuecomment-1567529453) ConPTY in  the latest WezTerm nightly (wezterm 20230530-062729) and looks like the issue is gone.
