### ISSUE TITLE
tmux leaves behind an empty ".lock"-file when trying to open a directory as socket

### ISSUE THREAD

**Issue by mb706** [tmux/tmux#3569]
Running `tmux -S <directory>/` errors out (as it should) but creates an empty `.lock` file in that directory:

```sh
ls /tmp/.lock
#> ls: cannot access '/tmp/.lock': No such file or directory
tmux -S /tmp/
#> error connecting to /tmp/ (Is a directory)
ls /tmp/.lock
#> /tmp/.lock
```
tmux created the `/tmp/.lock` file here. The `/` at the end of the directory name is necessary to reproduce this. I believe it happens in [this line](https://github.com/tmux/tmux/blob/149d9cc851dbf184b5b2041a5ec4be426b2f2914/client.c#L137).

Running tmux like this is obviously an error by the user, but tmux should probably still not leave any residues in this case.

### Further Information
* **uname -sp**: Linux x86_64
* **tmux -V**: tmux 3.3a
* **echo $TERM**: screen-256color

**Comment by nicm** [comment]
Can't reproduce, presumably on your platform `connect` is initially succeeding despite trying to connect to a directory.

Show me the client log from reproducing with `-vv` please.

**Comment by mb706** [comment]
`tmux -vvS /tmp/` creates the following tmux-client.log:
```
1684441692.516656 client started (242036): version 3.3a, socket /tmp/, protocol 8
1684441692.516794 on Linux 6.2.7-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar 17 16:16:00 UTC 2023
1684441692.516846 using libevent 2.1.12-stable (poll); ncurses 6.3
1684441692.517403 flags are 0x10010000
1684441692.517459 socket is /tmp/
1684441692.517556 trying connect
1684441692.517651 connect failed: Connection refused
1684441692.517730 lock file is /tmp/.lock
1684441692.517867 flock succeeded
1684441692.517909 got lock (6)
1684441692.517990 trying connect
1684441692.518074 connect failed: Connection refused
```

`connect` fails with `ECONNREFUSED` in both tries, but after the first try the `/tmp/.lock` file is created which then remains after the program exits.

This happens reliably on various different Linux systems that I try it on. Maybe you have a setup that forbids the creation of dot-files in /tmp or something? You can try a different directory from `/tmp/`: `mkdir ~/test && tmux -S ~/test/` should work as well. The `/` at the end of the file name is important, so `tmux -S /tmp` does not leave a residual file, only `tmux -S /tmp/` does.

**Comment by nicm** [comment]
I didn't try it on Linux. `ECONNREFUSED` is allowed, because that is what you get if the socket exists but the server has exited, but presumably the later `unlink` is then failing.

Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/11514641/x.diff.txt)
