### ISSUE TITLE
RFE: Serial support

### ISSUE THREAD

**Issue by owendelong** [tmux/tmux#3570]
### Issue description

Please add serial functionality similar to screen (e.g. screen /dev/ttyUSB0 115200)

### Required information

Please provide the following information:

* tmux version (`tmux -V`). -- Any version
* Platform (`uname -sp`). -- All platforms
* $TERM inside and outside of tmux (`echo $TERM`). -- Not relevant to this request
* Logs from tmux (`tmux kill-server; tmux -vv new`). -- Not Applicable to this request

I realize this issue was previously raised and summarily dismissed on religious grounds.

Respectfully, however, I disagree and would like to make the case for considering it.

tmux for better or worse is, effectively the de facto replacement for screen.
While dedicated serial programs like cu, kermit,  and minicom have their place, there is a lightweight elegance to having the functionality integrated into screen (and similarly I would hope tmux).

Unlike the other programs, screen provides a very iightweight and simple mechanism for quickly attaching to serial consoles and accomplishing a variety of tasks. Equivalent functionality in tmux should be similarly easy to work with.

While I realize there are those who argue that this functionality is orthogonal to the purpose of tmux and even go so far as to claim it should never have been put into screen, the fact remains that it is an extremely popular use of screen among network engineers and having it in tmux would be useful to a significant user population.

**Comment by nicm** [comment]
Not going to happen.

**Comment by owendelong** [comment]
Probably will result in a fork eventually then.

Owen
