### ISSUE TITLE
TMUX CTRL + B NOT WORKING

### ISSUE THREAD

**Issue by itsnotms** [tmux/tmux#3571]
Suddenly ctrl + b + :  is not working anymore did work before but now nothing is working not a single shortcut nothing. Cant split panes either. Neither horizontical nor vertical.

**Comment by nicm** [comment]
Logs?

**Comment by krader1961** [comment]
What is in your *~/.tmux.conf*? When you opened this issue did you not see these directions:

```
Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).
```

**Comment by itsnotms** [comment]
> 

Hey Krader all i have in my config is the following: 

set -g mouse on

Havent changed anything and it was working before

**Comment by itsnotms** [comment]
> Logs?

Hey Nicm i tried getting them but getting above reply

**Comment by krader1961** [comment]
> Havent changed anything and it was working before.

Well, clearly something has changed. 

> When trying to get logs -> sessions should be nested with care, unset $TMUX to force

You need to terminate the current tmux server first. Running `tmux kill-server` should do that. If it doesn't try the `pkill` command.
