### ISSUE TITLE
how to change default dir?

### ISSUE THREAD

**Issue by qq1243196045** [tmux/tmux#3574]
version of my tmux is :
Name        : tmux
Version     : 1.8
Release     : 4.el7
Architecture: x86_64
Install Date: Wed 24 May 2023 09:10:37 AM CST
Group       : Applications/System
Size        : 571847
License     : ISC and BSD
Signature   : RSA/SHA256, Fri 04 Jul 2014 01:34:17 PM CST, Key ID 24c6a8a7f4a80eb5
Source RPM  : tmux-1.8-4.el7.src.rpm
Build Date  : Tue 10 Jun 2014 10:40:36 AM CST
Build Host  : worker1.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Vendor      : CentOS
URL         : http://sourceforge.net/projects/tmux
Summary     : A terminal multiplexer
Description :
tmux is a "terminal multiplexer."  It enables a number of terminals (or
windows) to be accessed and controlled from a single terminal.  tmux is
intended to be a simple, modern, BSD-licensed alternative to programs such
as GNU Screen.

and when I use like [this issue](https://github.com/tmux/tmux/issues/1646)
` mkdir ~/tmp/foo`
`export TMUX_TMPDIR=~/tmp/foo`
`tmux new -d`
`tmux display -pF '#{socket_path}'`
it return none
nothing happend
how can I changed default dir?

**Comment by nicm** [comment]
Sorry, tmux 1.8 has not been supported for almost 10 years.
