### ISSUE TITLE
tmux next-3.4 and rxvt-unicode: ff/ffff000/0000

### ISSUE THREAD

**Issue by m0gj** [tmux/tmux#3575]
```
Platform: Linux
Version: tmux next-3.4
$TERM: rxvt-unicode-256color
```

After upgrading tmux to version next-3.4, the string `ff/ffff000/0000` is inserted into first window of every new tmux session, and in the current window when reconnecting to an existing session.

This happens when using the rxvt-unicode terminal emulator, but only after tmux is upgraded to next-3.4. The issue does not happen if connecting to an older tmux version with the same rxvt-unicode setup.

If opening the st terminal emulator from inside another emulator, then creating a new tmux session or reconnecting to an existing, following is logged to the parent shell:

```
erresc: unknown csi ESC[>c
erresc: unknown csi ESC[>q
erresc: unknown private set/reset mode 7727
```

Alpine Linux developers have suggested that following issue could be related:

https://github.com/tmux/tmux/issues/3531

**Logs:**

[tmux-client-3198.log](https://github.com/tmux/tmux/files/11568955/tmux-client-3198.log)
[tmux-out-3201.log](https://github.com/tmux/tmux/files/11568956/tmux-out-3201.log)
[tmux-server-3201.log](https://github.com/tmux/tmux/files/11568957/tmux-server-3201.log)

**Comment by nicm** [comment]
This is a urxvt bug, see https://github.com/tmux/tmux/issues/3470.
