### ISSUE TITLE
Need help: Json format distorted after pasted to remote vim file using tmux 

### ISSUE THREAD

**Issue by mikeyang01** [tmux/tmux#3576]
### Issue description
Copy from mac to remote ubuntu vps using tmux

json format distorted
original format:
```
{
   "tools":[
      "python",
      "python",
      "python",
      "python",
      "python",
      "python"
   ]
}
```
pasted on vim editor on vps using tmux
Image link: https://share.cleanshot.com/Qdw6mw5C
![](https://media.cleanshot.cloud/media/64477/UMPROzWevukI1qjvxVSbcaFHgGVbTCiAOyh7LDC8.jpeg?Expires=1685384196&Signature=dECA2nakwDiY3~rqncCIDd2Rxk8cSixUQBVbor9Qgd7IC9dNc5f2t7HNZPRZHT938dZ~SuEOfHKrVlc0QLexn31RnCalM4u0o7SiYqQCF8zuTP5DL8k2nuwk5PYijapoOvA32wLPZtXc~v6Dfu4QRcvR8vimfVBG-u5N0KylzxEU~tKUdjHmmMsMPPLlT08V9vWfH1ewwgxTv3qFlU1WgA6WOVHQeRv3CiTljwzH1NmZoDWahoHq76d6x~VYi-DBuI1mu-j~fUekX-0DD0BiO3ACeeco5c7jcmfKuxB-0LRwKflmWOy3QponSjuPAgys3yAAhDOu0XqCTpmeaaCYTw__&Key-Pair-Id=K269JMAT9ZF4GZ)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.3a

* Platform (`uname -sp`).
Ubuntu Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).
Macbook air Terminal Version 2.13 (447)

* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by krader1961** [comment]
FWIW, I can't make any sense of your problem description. Nor how someone might reproduce the problem. Your screenshot doesn't show any form of "crash". Your screenshot appears to show you pasting a JSON blob into a Vim editor session. I have no difficulty doing that. The stair-stepping you observed is typical. Pressing Ctrl-a before leaving insert mode should undo the extra indentation.

P.S., The instructions for opening an issue tell you to report the value of the `TERM` env var inside and outside of the tmux session. You simply reported the actual terminal emulator you are using. The point of asking for the two values of `TERM` is to ensure you are using a `screen` or `tmux` TERM inside tmux and something else (e.g., `xterm-256color`) outside of tmux.

P.P.S., The instructions also ask that you provide a tmux server log which you did not do.

**Comment by mikeyang01** [comment]
Thanks a lot
Checked on other VPS provoider, issue not reproduced, maybe related to VPS environment

**Comment by krader1961** [comment]
> Checked on other VPS provoider, issue not reproduced, maybe related to VPS environment

It is still unclear what you meant by "crash", and which you subsequently changed to "distorted" after my previous comment. It would have been helpful if you showed us what happened "on other VPS provider." That would allow what is known as a differential analysis.


If the original problem was that the entire JSON blob was not received by the Vim editor running inside a Tmux session there are several possible explanations. For example, you might be using [Mosh SSH](https://mosh.org/) to connect to your VPS. It has been known to drop data (at least in the distant past when I first learned about it).

I have no doubt you observed unexpected behavior, but you provided far too little useful information to either understand what problem you observed, let alone make any hypothesis as to the cause of the unexpected behavior.

Also, I see you modified your problem statement to show us the JSON blob you were trying to paste. You should have tried alternative JSON blobs. Such as one that was much shorter; e.g., by retaining only one `"python"` element of the `tools` list.
