### ISSUE TITLE
Can Translation of tmux manpage be added to tmux wiki?

### ISSUE THREAD

**Issue by Freed-Wu** [tmux/tmux#3578]
I create a [Chinese translation of tmux man pages](https://github.com/Freed-Wu/tmux-zh) by [po4a](https://github.com/mquinson/po4a) and [cmake](https://github.com/Kitware/CMake). Can it be added to [tmux wiki](https://github.com/tmux/tmux/wiki) to let more people who need a translation to know it? Thanks!

**Comment by nicm** [comment]
Thanks. Are you going to keep it up to date as tmux man page is changed?

**Comment by Freed-Wu** [comment]
I project to realize a CI/CD to detect the updated version of tmux and translate the changed po by machine translation and then create a pull request about translated changed po and let human merge it. With the help of CI/CD, I think it can provide a translation which almostly always latest.

**Comment by Freed-Wu** [comment]
I notice many open source project use [weblate](https://hosted.weblate.org/) and po4a to provide internationalization and localization. How about for tmux? I think it is a better solution. @nicm

**Comment by nicm** [comment]
Thanks. I don't know, I'm not going to do any translation myself or set up any processes. My only concern is that anything added is kept mostly up to date. Whether you want to open a PR every month or so or send me an email or use some automated tool, I don't mind.

**Comment by nicm** [comment]
What do you want me to do here? Do you just want me to link to your GitHub project or a generated page with the manual from the tmux wiki?

Or it looks like at least on Linux, translated man pages are installed as for example man/zh_CN/man1/tmux.1. If you open a PR with the file as say tmux.1.zh_CN I can install it there when tmux is installed. But this will mean you will need to open new PRs to keep it up to date?

Which do you prefer?
