### ISSUE TITLE
Plotext output in terminal

### ISSUE THREAD

**Issue by mdoksa76** [tmux/tmux#3583]
There is difference in image quality output in terminal with plotext in tmux session and without use of tmux.

With tmux:
![plotext-tmux](https://github.com/tmux/tmux/assets/122205220/38cd39f6-21cb-4c39-9a11-ec6b22a3644f)

Without tmux:
![plotext-wo-tmux](https://github.com/tmux/tmux/assets/122205220/5cad6163-2fa4-4728-853b-560413c02490)

Any advice?

**Comment by krader1961** [comment]
You didn't provide any of the information requested in the new issue template. Such as the value of the `TERM` env var inside and outside of the tmux session. Nor did you explain the format of the "image". I'm guessing your image is a file containing [ANSI X3.64 SGR](https://en.wikipedia.org/wiki/ANSI_escape_code) 24-bit "true color" sequences. And the terminal definitions you are using don't support true color sequences. See the [Tmux FAQ](https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour)

**Comment by mdoksa76** [comment]
Sorry for not following new issue template.

uname -sp && tmux -V && echo $TERM
Linux armv7l
tmux 2.6
xterm

Same output in outside of tmux and in tmux.

In tmux there is no true color mode. Here are screenshots for non-tmux session and tmux session:
![no-tmux](https://github.com/tmux/tmux/assets/122205220/819acb7d-4f33-44a4-8c03-a0b534c24d78)

![tmux](https://github.com/tmux/tmux/assets/122205220/1016e473-df53-4ba3-8261-299a9488ab45)

At the moment I did not check jpg picture details.

**Comment by nicm** [comment]
tmux 2.6 has not been supported for five years.

I can't remember if it supports RGB colour but if it does you can turn it on as described in the FAQ.

**Comment by mdoksa76** [comment]
It becomes better with "tmux -2":
![plotext-tmux-2](https://github.com/tmux/tmux/assets/122205220/27779763-11be-47aa-8775-2c2cfa5a1a26)

**Comment by mdoksa76** [comment]
When back to xterm in -tmux.conf, tmux -2 outputs all same as non-tmux session.
