### ISSUE TITLE
Good catch @jettero. My remark was based on `automatic-rename` and `automatic-rename-format` which affect the window title (ie no equivalent option for pane title).

### ISSUE THREAD

**Issue by woodgear** [tmux/tmux#3584]
Good catch @jettero. My remark was based on `automatic-rename` and `automatic-rename-format` which affect the window title (ie no equivalent option for pane title).

As for the pane title, docs say:
```
When a pane is first created, its title is the hostname. A pane's title can be set via the OSC title setting sequence, for example:
$ printf '\033]2;My Title\033\\'
```
which could correlate with @yorkbai's observation.

_Originally posted by @nkgm in https://github.com/tmux/tmux/issues/680#issuecomment-389508237_

**Comment by woodgear** [comment]
ssh to a other machine did change the current panel title. and the origin title set via `seleect panel -T` are losed...
tmux version 3.0a
os: linux
term: xterm-256color

**Comment by woodgear** [comment]
and even wrose. if you ssh to some host,and use `seleect panel -T` to change the pane title. it changes.
but after hit antoher enther key,it change backs to the host's name.

**Comment by woodgear** [comment]
why just close？

**Comment by nicm** [comment]
No question or bug report, no tmux version, no logs.

**Comment by woodgear** [comment]
sorry for the missing.i will create another issue.

**Comment by woodgear** [comment]
i confirmed this issue is not logger reproduce in latested source code buid... so just ignore me.sorry for my intrusion.
