### ISSUE TITLE
Feature: user configurable padding on a per-pane basis

### ISSUE THREAD

**Issue by Pocco81** [tmux/tmux#3585]
Hello!

### Problem
I wanted to have some sort of border padding around my terminal that I could toggle on and off while using programs like NeoVim, where more screen space is desirable. On my terminal (ST) I'm able to sort of accomplish this by using XRDB to dynamically adjust the terminal's `borderpx` through my `xresources` file, however this doesn't account for Tmux's panes. Moreover, not every terminal has the possibility of being "reconfigured' on-the-fly, so this option should be discarded. 

### Possible solution and implementation

As first suggested by #3097, it could be done by:

> add(ing) a flag to `resize-pane` command that does an internal resize by padding it without affecting the window layout (size and position of panes).

This could, obviously, be used on-the-fly, and thus, people like me could make wrappers or aliases to adjust padding dynamically.

Although I think the issue I linked above is asking for something a bit different, we are both keen on adding padding to panes.

### About it being not "highly demanded"

[this](https://github.com/tmux/tmux/issues/3097#issuecomment-1057331359) comment on the issue I linked above mentioned that it wasn't a highly requested feature:

> As you are the first person to suggest it so far it seems unlikely it is something in high demand.

So here are a couple places I've found people asking for the same thing/something similar:

* https://www.reddit.com/r/tmux/comments/nmgvi0/pane_padding/
* https://www.reddit.com/r/tmux/comments/6s2yw9/is_it_possible_to_increase_margins_of_panes_push/
* https://github.com/tmux/tmux/issues/3097
* https://www.reddit.com/r/tmux/comments/jjocy2/how_to_add_gaps_between_tmux_panes/
* https://superuser.com/questions/692988/is-there-a-way-to-set-margins-paddings-in-tmux

Although this is not a "critical" feature, I think it'd be nice to have it.

Thanks for the great work on Tmux, I seriously could not be productive without it!

**Comment by nicm** [comment]
I'm not convinced of the usefulness of this and I am not sure it will be that easy. I don't intend to work on it but if you want to have a go feel free to ask questions.

To start with I would probably try to get `tty_draw_pane` to redraw with your padding and `resize.c` to take it into account. For panes that are fully visible it may be enough just to reduce the width and height and draw some spaces instead, panes that are partly invisible may be much more difficult...

Once that works it may be enough just to force all panes down the slow path through tty_draw_pane in all the draw functions (for example the first if in `tty_cmd_insertcharacter`).
