### ISSUE TITLE
Mouse scrolling doesn't work in tmux the way it works outside of tmux (in Linux Terminal):

### ISSUE THREAD

**Issue by lgmgeo** [tmux/tmux#3587]
Mouse scrolling doesn't work in tmux the way it works outside of tmux (in Linux Terminal):
tmux sends mouse scroll events as when I pressed Up/Down keys. 
But I would like it to scroll through the shell output history.  
Moreover, I also want to keep copy/paste functions as the ones in the shell (when I select with the mouse, I would like to keep the selected text highlighted).
Is there a way to make tmux work like this?

I already add `set -g mouse on` to ~/.tmux.conf, and start new tmux session. 
It's quite good: I can scroll through the shell output history  while **holding Shift key + scrolling with the mouse**. But when copying text with the mouse, it doesn't stay highlighted when I release the mouse click ;o(

Do you have an optimal solution?
Thank you for any help you can provide me.

* tmux version: tmux 3.2a
* Platform: Linux x86_64
* $TERM inside of tmux: screen-256color
* $TERM outside of tmux: screen

**Comment by ThomasLudwig** [comment]
`set -g mouse on` affects the copy/paste behaviour

to only affect the scrolling, add the following to ~/.tmux.conf :
`set -g terminal-overrides 'xterm*:smcup@:rmcup@'`
