### ISSUE TITLE
Underline style colour support

### ISSUE THREAD

**Issue by lpuljic** [tmux/tmux#3589]
Hi, 

I was wondering if there is a possibility to support colour style for `undersline` in status-format ?

Thanks

**Comment by nicm** [comment]
No this is not supported at the moment, but it wouldn't be too hard to add.

**Comment by lpuljic** [comment]
Thanks @nicm, I am not sure if I know where to start, is it something that I just need to wait till you have time? 

Thanks for all the hard work in tmux.

**Comment by nicm** [comment]
Try this please against master: [tmux-us.diff.txt](https://github.com/tmux/tmux/files/11859065/tmux-us.diff.txt)

~~~~
set -g status-left '#[underscore us=red]hello'
~~~~

**Comment by lpuljic** [comment]
Amazing, works like a charm, thank you

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by lpuljic** [comment]
Thanks @nicm appreciate it.
