### ISSUE TITLE
Spacing *nightmare* in tmux

### ISSUE THREAD

**Issue by GH-Syn** [tmux/tmux#3599]
### Discussed in https://github.com/orgs/tmux/discussions/3598

<div type='discussions-op-text'>

<sup>Originally posted by **GH-Syn** June 24, 2023</sup>
#### Preface
 > I'm not really sure where to put this, as it's not a problem with my terminal as it applies to every terminal that I've tried (kitty, alacritty, st, xterm, terminator), and i genuinely have no idea what the solution is. 

## Lé problem
Every single word has a monolithic amount of spacing after it, making text a nightmare to read.

## Screenshot
![image](https://github.com/tmux/tmux/assets/101031214/556986c2-0893-44cb-8ebf-96e61196e946)

## System / Info
**tmux**: tmux 3.3a
system:
<img width="350px" src="https://github.com/tmux/tmux/assets/101031214/dcafa2f1-141d-4562-aaa4-aab4502824e3"></img>
</div>

**Comment by krader1961** [comment]
It appears you opened two issues for the same problem. You should close this as a duplicate of #3598.

**Comment by GH-Syn** [comment]
Closed as a duplicate of #3598.
