### ISSUE TITLE
Feature request: allow bind key to take effect before Ctrl key is released

### ISSUE THREAD

**Issue by kerframil** [tmux/tmux#36]
I am trying to switch from screen to tmux and discovered that I have a habit of doing this:-

1) Press C-a
2) Release the 'a' key
3) Press another key, according to whatever I need to do
4) Release the Ctrl key

In screen, this is tolerated. In tmux, however, a prefix of C-a does not function unless both keys are released prior to step 3.

I find this characteristic of screen comfortable and it's nigh on impossible for me to alter this habit. Is there any chance of introducing an option for tmux to allow for this sloppy use case?

**Comment by ThomasAdam** [comment]
You just need to bind C-$key in your .tmux.conf

Thomas Adam

**Comment by kerframil** [comment]
Interesting. I would have expected that to suppress the normal handling of the key combination. I'd still rather not have to rebind keys that are already meaningful following the prefix key but, given that I only use several on a regular basis,  that's good enough. Thanks.
