### ISSUE TITLE
Tmux copy/paste doesn't work on OSX

### ISSUE THREAD

**Issue by ns-cweber** [tmux/tmux#360]
I'm using tmux 2.0 on OSX 10.10.5. When I enter copy mode `ctrl+b [`, select text via `ctrl+<space>`, and then try to paste it via `ctrl+]`, different text is pasted (presumably I accidentally copied something some time in the past). I tried changing the meta key to alt in my iTerm profile, but that didn't affect it. Other users on the internet suggested using `esc` as my meta key, which similarly doesn't work (it just kicks me out of copy-mode as soon as the esc key is pressed).

**Comment by nicm** [comment]
Did you copy it with M-w?
