### ISSUE TITLE
Broken Rendering of Characters Composed of Multiple Code Points in kitty

### ISSUE THREAD

**Issue by elcurious** [tmux/tmux#3600]
## Description

Characters composed of multiple Unicode code points (e.g., `👍🏻` which is composed of `U+1F44D` and `U+1F3FB`) do not render properly when running tmux inside kitty.

## Steps to Reproduce

1. Run kitty without any configuration from a different terminal: `kitty --config NONE`.
2. Run `printf "Test\t\t|\n'👍' Test\t|\n'👍🏻' Test\t|\n" > test.txt`.
3. Run `cat test.txt`.
4. Observe that the `|` characters are aligned properly.
5. Run tmux without any configuration inside kitty: `tmux -vv -f /dev/null new`.
6. Run `cat test.txt`.
7. Observe that the `|` characters are misaligned.

This example is not drastic, but this bug causes problems when typing commands with multi-code-point characters in the shell or editing files with multi-code-point characters in vim/neovim: (https://github.com/kovidgoyal/kitty/issues/6355#issue-1750974942).

## Screenshots

kitty without tmux:

![image](https://github.com/tmux/tmux/assets/136172567/7c909371-99b1-4360-842a-be14ac8734f4)

kitty + tmux:

![image](https://github.com/tmux/tmux/assets/136172567/c2275547-03e1-48a7-ac0f-7a37a8d2f73f)

Gnome Terminal:

![image](https://github.com/tmux/tmux/assets/136172567/5297af93-89eb-42ec-9fd0-3fbc4adc2b2e)

Gnome Terminal + tmux:

![image](https://github.com/tmux/tmux/assets/136172567/b28e24a3-c3ef-4410-a19b-caadda108301)

## Environment Details

* tmux version (`tmux -V`): `tmux 3.3a`

* `$TERM` inside tmux (`echo $TERM`): `tmux-256color`

* `$TERM` outside tmux (`echo $TERM`): `xterm-kitty`

* kitty version (`kitty --version`):  `kitty 0.28.1 created by Kovid Goyal`

* Platform (`uname -sp`): `Linux unknown` (Arch Linux)

## Logs

Logs of starting tmux in kitty using `tmux -vv -f /dev/null new` and running `cat test.txt` followed by `exit`:

[tmux-client-14609.log](https://github.com/tmux/tmux/files/11855584/tmux-client-14609.log)
[tmux-out-14611.log](https://github.com/tmux/tmux/files/11855585/tmux-out-14611.log)
[tmux-server-14611.log](https://github.com/tmux/tmux/files/11855586/tmux-server-14611.log)

## Potential Culprit

kitty combines a character with multiple code points per the Unicode standard. That is, it combines `U+1F44D` and `U+1F3FB` and displays 👍🏻 instead of 👍 followed by 🏻. It seems like tmux expects that those two code points will be displayed separately. The mismatch between the character width that tmux expects and the width that kitty actually uses causes this issue.

## Additional Context

The relevant bug on the kitty side: https://github.com/kovidgoyal/kitty/issues/6355.

**Comment by nicm** [comment]
Thanks, your analysis looks correct. tmux, like GNOME terminal, does not currently support this feature. Until it does, I suggest you either avoid the characters, or configure Kitty not to do this.

If you (or anyone else) want to look at adding this, the implementation would not be very difficult - it is just a form of combining characters which is already supported (look at how ZWJ is handled in `screen_write_cell`). The trickiest thing would be working out which codepoints it applies to, since we don't want to carry around a load of Unicode data. Possibly utf8proc can provide this, I would be OK if - initially at least - this is only supported with utf8proc. We would also need an extension terminfo(5) capability and corresponding tmux "terminal feature" to tell tmux whether the outside terminal supports it.

**Comment by nicm** [comment]
Possibily we could assume `UTF8PROC_CATEGORY_SK` has width 0, although of course this will break GNOME terminal. You could try this anyway: [x.diff.txt](https://github.com/tmux/tmux/files/11857660/x.diff.txt)

I don't think there is a similar way to get this information from libc...
~~~~
diff --git a/compat/utf8proc.c b/compat/utf8proc.c
index dd4ab27f..2d21e273 100644
--- a/compat/utf8proc.c
+++ b/compat/utf8proc.c
@@ -33,6 +33,13 @@ utf8proc_wcwidth(wchar_t wc)
                 */
                return (1);
        }
+    if (cat == UTF8PROC_CATEGORY_SK) {
+        /*
+         * Modifier symbols are only useful when combined, so treat as zero
+         * width.
+         */
+        return (0);
+    }
        return (utf8proc_charwidth(wc));
 }

**Comment by nicm** [comment]
You can also try this (against master): [tmux-codepoint-widths.diff.txt](https://github.com/tmux/tmux/files/11857833/tmux-codepoint-widths.diff.txt)

It adds an option `codepoint-widths` allowing you to override the widths of codepoints, so you can do:
~~~~
set -as codepoint-widths "U+1F3FB=0,U+1F3FC=0,U+1F3FD=0,U+1F3FE=0,U+1F3FF=0"
~~~~

I thought of including these in the option by default, but it appears there are other major terminals that do not support this yet so perhaps that is premature...

For these specific characters it may be better to just hardcode a list and add a terminfo(5) capability, but maybe that is overkill.

**Comment by elcurious** [comment]
Thanks a lot for the quick response, Nicholas!

I tested the diff, and it does indeed resolve the issue in my first comment (https://github.com/tmux/tmux/issues/3600#issue-1772496615). However, there still seems to be an issue with Unicode characters that are composed of multiple code points (e.g., 🇪🇸 which is composed of `U+1F1EA` and `U+1F1F8`).

If we run `printf "Test\t\t|\n'👍' Test\t|\n'🇪🇸' Test\t|\n" > test.txt` followed by `cat test.txt`, the file content gets displayed properly inside and outside tmux:

kitty (without tmux):

![image](https://github.com/tmux/tmux/assets/136172567/62425bbc-f81c-424c-981b-96608cd935dd)

kitty + tmux:

![image](https://github.com/tmux/tmux/assets/136172567/0f99838e-da50-4ff9-a15f-5a15884ee4d7)

However, if we open `test.txt` in neovim using `nvim -u NONE -c 'set colorcolumn=20' test.txt`, there's still an issue with the character width:

kitty (without tmux):

![image](https://github.com/tmux/tmux/assets/136172567/f9a505cd-111d-41a2-8c6d-2cedecc206da)

kitty + tmux:

![image](https://github.com/tmux/tmux/assets/136172567/9ab61ea3-5740-4451-af12-d6a037234ae8)

In this case, I don't think we can unconditionally set the widths of `U+1F1EA` and `U+1F1F8` to static values using `codepoint-widths`, right?

**Comment by nicm** [comment]
All programs must agree on the widths: terminal, tmux and vim. If they don't agree, things will look funny. If you configure these characters to be width 2 in tmux, you will need to configure vim in the same way, or tmux will move the cursor more or fewer positions than it expects.

**Comment by elcurious** [comment]
Yes, I understand that, but for certain code points, I don't think the widths can be **statically** specified in `codepoint-widths`.  For example, the Armenian flag emoji (🇦🇲) is composed of `U+1F1E6` (🇦) + `U+1F1F2` (🇲), and the Moroccan flag emoji (🇲🇦) is composed of the same code points but in the reverse order:  `U+1F1F2` (🇲) + `U+1F1E6` (🇦) (try removing the space between 🇦 🇲 and 🇲 🇦, and the flags should be rendered).

In the case of the Armenian flag,  we want 🇦 to have a width of 1 but 🇲 to have a width of zero. In the case of the Moroccan flag, we want 🇲 to have a width of 1, but 🇦 to have a width of 0. When the code points are separated (e.g., by a space between them), we want each of them to have a width of 1. Therefore, I don't think we should **statically** define the width of the _code points_ in `codepoint-widths`. Instead, I think tmux should be reasoning about the width of an entire _character ([grapheme](https://stackoverflow.com/a/27331885))_ rather than the width of a _code point._

What do you think?

**Comment by elcurious** [comment]
Perhaps we could use [`utf8proc_grapheme_break_stateful`](https://github.com/JuliaStrings/utf8proc/blob/1cb28a66ca79a0845e99433fd1056257456cef8b/utf8proc.h#L589-L607) to automatically determine the real width of a grapheme? That way, we don't need to manually/statically specify the width of individual code points.

**Comment by nicm** [comment]
Yes we would need the ability to specify codepoint sequences rather than individual codepoints, and tmux would need to be able to understand "this codepoint might be followed by X or Z" in the same way as it does for keys.

I don't really like depending on utf8proc because that means it won't work without it.

**Comment by nicm** [comment]
Can you please try this: [tmux-unicode.diff.txt](https://github.com/tmux/tmux/files/11955732/tmux-unicode.diff.txt)

This adds a `unicode-widths` option instead; you can't use `U+` now, you either need to enter the characters as-is or use `\u`/`\U`:
~~~~
set -as unicode-widths '🇦🇲=2'
set -as unicode-widths '🇲🇦=2'
set -as unicode-widths '👍🏻=2'
~~~~

It works for me but this is very much a work in progress:

- It is not very efficient as it caches the option values as a list. This should be a tree but I had changed it to a list to do it a different way and I don't have time to change it back. The cache should also store the final combined character so it can be used immediately, instead of building it in `input_utf8_finish`.

- This requires that each codepoint that makes up the `unicode-widths` list be valid and have a valid width. So for exotic/recent characters you are likely to need to build with utfproc because `wcwidth` will most likely have a width for them. This limits the usefulness of this for defining widths for PUA characters, so it would be good to allow missing widths here.

- I suspect we are missing some calls to `input_utf8_finish`.

- If we are processing strings of UTF-8 in `input.c` instead of individual characters, we should do the same to merge zero width characters, ZWJ and so on, and remove the code in `screen-write.c` (this would probably be simplier in any case).

- I think we could probably try to automatically work out the width if the user *is* using utf8proc, and only require them to be defined by the user for `wcwidth` (this could probably be done later however).

**Comment by elcurious** [comment]
Thanks for continuing  to work on this, Nicholas!

I applied the patch in https://github.com/tmux/tmux/issues/3600#issuecomment-1621302475 on top of https://github.com/tmux/tmux/commit/237ee6f2311b351b8a3bb3b46e17622f6e3b6bb9.

This works as expected when `cat`ing `test.txt` with the following content: `printf "Test\t\t|\n'👍' Test\t|\n'👍🏻' Test\t|\n'🇪🇸' Test\t|\n" > test.txt`, but unfortunately, this doesn't resolve the issue in neovim. Here is a video of the issue:

[tmux-unicode-bug.webm](https://github.com/tmux/tmux/assets/136172567/7db81019-28bd-4e18-be5f-055e096ea396)

**Comment by nicm** [comment]
Show the tmux server log please. If it works with `cat` - that is, following text is correctly aligned both when initially printed and when redrawing (`C-b r` or change window or session and back), then this is probably a mismatch in how vim and tmux see the widths.

**Comment by elcurious** [comment]
Using `refresh-client` didn't seem to change the incorrect rendering

I recorded a new session:

[tmux-unicode-bug.webm.webm](https://github.com/tmux/tmux/assets/136172567/3a63fa4b-fc28-4e35-9307-67553211e16b)

Here are the logs associated with the recording above:

[tmux-client-30064.log](https://github.com/tmux/tmux/files/12062806/tmux-client-30064.log)
[tmux-out-30066.log](https://github.com/tmux/tmux/files/12062807/tmux-out-30066.log)
[tmux-server-30066.log](https://github.com/tmux/tmux/files/12062808/tmux-server-30066.log)

**Comment by nicm** [comment]
I meant if it is correct without vim and still correct after `refresh-client` without vim.

**Comment by elcurious** [comment]
Yes, outside of neovim, the text is properly aligned when running `cat test.txt` followed by `refresh-client` (`refresh-client` doesn't actually change the rendering in that case).

**Comment by nicm** [comment]
Sorry for the delay here. I am not sure nvim is sending the same characters as actually in the file. Can you open the text file in nvim in `script` (inside tmux) and show me the typescript file?

**Comment by nicm** [comment]
There are actually only a couple of hundred of these characters, so we could just list them and work out whether to combine based on the list.

Please try this instead of the last diff (only lightly tested, eg I didn't try ZWJ): [tmux-unicode-new.diff.txt](https://github.com/tmux/tmux/files/12301200/tmux-unicode-new.diff.txt)


You should not need to do any configuration for this (there is no option anymore).

**Comment by nicm** [comment]
ZWJ still seems to work, for example `printf '|\360\237\244\267\342\200\215\342\231\202\357\270\217|'`.

But please test and see if it works for your symbols.

**Comment by elcurious** [comment]
Thanks for looking into this again! I applied the diff on top of 237ee6f2, but it still didn't work. Here's a video of the issue:

[tmux-unicode-bug.webm](https://github.com/tmux/tmux/assets/25834760/76b962f7-59ab-46a4-b7d2-19f05a421629)

Noteworthy in the video is how `cat`ing `test.txt` is different inside and outside of tmux:

outside tmux:
![](https://github.com/tmux/tmux/assets/25834760/d73376ab-df25-4297-a253-7ba4bb0e2d16)

inside tmux:
![](https://github.com/tmux/tmux/assets/25834760/cc388f3a-a8ab-4e41-99b0-988104961277)

Similarly, opening `test.txt` in neovim displays the text normally outside tmux, but the output is mangled inside tmux:

outside tmux:

![](https://github.com/tmux/tmux/assets/25834760/e963d7cb-23a1-4b26-8358-61f061c50da0)

inside tmux:
![](https://github.com/tmux/tmux/assets/25834760/a8b39c7f-f2f5-4067-b2b7-9a414ba3beab)

Are you able to replicate this at your end? Here's some information that might help with replicating:

- `test.txt` is created using `printf "Test\t\t|\n'👍' Test\t|\n'👍🏻' Test\t|\n'🇪🇸' Test\t|\n" > test.txt`
- Kitty version: 0.29.2
- tmux version: 237ee6f2 + the diff from https://github.com/tmux/tmux/issues/3600#issuecomment-1671080219
- neovim version: 0.9.1

**Comment by nicm** [comment]
It works for me. Are you sure you applied the diff and were running the right tmux binary? If so please show tmux logs from running `tmux -Ltest -f/dev/null -vv new`, `cat test.txt` then `exit` only.

Please show me the `typescript` file from running `script` then opening the file in `vim` inside and outside tmux (separate files).

**Comment by elcurious** [comment]
> Are you sure you applied the diff and were running the right tmux binary?

My bad! I accidentally applied an older diff. Sorry for the confusion.

I applied the new diff (https://github.com/tmux/tmux/issues/3600#issuecomment-1671080219) on top of e3a8b843. 

There still seems to be an issue. Here's the result of `cat`ing `test.txt` inside and outside tmux:

outside tmux:

![](https://github.com/tmux/tmux/assets/136172567/22d22f8f-acf4-456a-af2d-b9e7a8cb763c)

inside tmux:

![](https://github.com/tmux/tmux/assets/136172567/c58e1d2e-f76d-48c9-a5ba-915e04ef713a)

Here are the logs from running `tmux -L test -f /dev/null -vv new /bin/bash --norc --noprofile`, `cat test.txt` followed by `exit`:

[tmux-client-15010.log](https://github.com/tmux/tmux/files/12389143/tmux-client-15010.log)
[tmux-out-15012.log](https://github.com/tmux/tmux/files/12389144/tmux-out-15012.log)
[tmux-server-15012.log](https://github.com/tmux/tmux/files/12389145/tmux-server-15012.log)

The issue with displaying the characters in neovim also persists:

outside tmux: 

![](https://github.com/tmux/tmux/assets/136172567/d89824d9-7df3-4753-865b-0308c442f5a1)

`script` output:  [nvim_outside_tmux.script.txt](https://github.com/tmux/tmux/files/12393245/nvim_outside_tmux.script.txt)

inside tmux:

![](https://github.com/tmux/tmux/assets/136172567/0f5a5edd-2a8b-446a-8c98-06d2018e9c64)

`script` output: [nvim_inside_tmux.script.txt](https://github.com/tmux/tmux/files/12393246/nvim_inside_tmux.script.txt)

During the testing, I was using `/bin/bash --norc --noprofile` when starting shells (e.g., started kitty using `kitty --config NONE /bin/bash --norc --noprofile`) to avoid any (unlikely) interference from the shell configs. The bash version I'm using is `5.1.16`.

**Comment by nicm** [comment]
This log is not from the right build either, can you please check you are running the right binary? The server log should contain the text `UTF8_WRITE_`.

nvim moves the cursor around inside the characters but I will look at that later.

**Comment by elcurious** [comment]
You are absolutely correct! I forgot that my `alias` for the locally-built tmux would not get used when running the shell with `--norc` (duh!). So third time is the charm?

For `cat test.txt`, the problem only seems to be with the flag now.

outside tmux:

![](https://github.com/tmux/tmux/assets/136172567/7312dc52-531a-45b4-a130-ca5e03bb1d11)

inside tmux:

![](https://github.com/tmux/tmux/assets/136172567/c454bdfd-9ca8-4e4a-a05e-d12266a5aae3)

Here are the logs from running `~/tmux/tmux -L test -f /dev/null -vv new /bin/bash --norc --noprofile`, `cat test.txt` followed by `exit`:

[tmux-client-2283.log](https://github.com/tmux/tmux/files/12401191/tmux-client-2283.log)
[tmux-out-2285.log](https://github.com/tmux/tmux/files/12401192/tmux-out-2285.log)
[tmux-server-2285.log](https://github.com/tmux/tmux/files/12401193/tmux-server-2285.log)

With tmux + neovim, there is a problem with the flag and the color of the colored thumbs-up emoji.

outside tmux:

![](https://github.com/tmux/tmux/assets/136172567/795dc5d0-c4fc-4c00-bfa0-eaf95f1ade73)

`script` output: [outside_tmux.script.txt](https://github.com/tmux/tmux/files/12401610/outside_tmux.script.txt)

inside tmux:

![](https://github.com/tmux/tmux/assets/136172567/1fe15b93-73c1-45d8-87b7-9bc125f68cea)

`script` output: [inside_tmux.script.txt](https://github.com/tmux/tmux/files/12401613/inside_tmux.script.txt)

When inside tmux, the problem with the colored thumbs-up emoji in neovim is resolved after highlighting the line in neovim:

![](https://github.com/tmux/tmux/assets/136172567/e502b36b-d748-4f7a-bc92-5af6a3e7b03d)

`script` output: [inside_tmux_highlight.script.txt](https://github.com/tmux/tmux/files/12401620/inside_tmux_highlight.script.txt)

**Comment by nicm** [comment]
OK test.txt works for me but if I do this it is wrong:
~~~~
printf '|\360\237\207\252\360\237\207\270|'
~~~~

The reason is that the kernel and utf8proc both think this character is width 1.
~~~~
1692644272.325423 input_top_bit_set 4 '\360\237\207\252' (width 1)
1692644272.326210 input_top_bit_set 4 '\360\237\207\270' (width 1)
~~~~
However, it appears your terminal and mine both think that the character is width 2.

I don't know if any terminals will make this width 1, so we could probably just force them to width 2. Try this please: [tmux-unicode-combine.diff.txt](https://github.com/tmux/tmux/files/12406546/tmux-unicode-combine.diff.txt)

I think I know what is wrong with vim but I am not going to work on that right now until this is working.

**Comment by nicm** [comment]
I made this fix as well and now trying your script file from vim does not misbehave (I have applied this change also). Can you let me know if you still see problems either by applying it as well as the last diff, or wait until GitHub syncs?
~~~~
--- screen-write.c      1 Sep 2023 14:29:11 -0000       1.219
+++ screen-write.c      1 Sep 2023 16:01:24 -0000
@@ -1792,6 +1792,8 @@ screen_write_collect_add(struct screen_w
        u_int                            sx = screen_size_x(s);
        int                              collect;

+       ctx->flags &= ~SCREEN_WRITE_COMBINE;
+
        /*
         * Don't need to check that the attributes and whatnot are still the
         * same - input_parse will end the collection when anything that isn't

**Comment by nicm** [comment]
Am I meant to guess which characters? Where are the logs?

**Comment by nicm** [comment]
Does this fix it?
~~~~
--- a/utf8-combined.c
+++ b/utf8-combined.c
@@ -1114,10 +1114,8 @@ utf8_try_combined(const struct utf8_data *ud, const struct utf8_data *last,
         * later; also force the width to two.
         */
        if (last == NULL) {
-               if (utf8_find_combined_first(ud) != NULL) {
-                       *width = 2;
+               if (utf8_find_combined_first(ud) != NULL)
                        return (UTF8_WRITE_MAYBE_COMBINE);
-               }
                return (UTF8_WRITE_NOW);
        }

**Comment by nicm** [comment]
Never mind, it is a different bug, please try this or wait for it to reach GitHub:
~~~~
--- utf8-combined.c	1 Sep 2023 14:29:11 -0000	1.1
+++ utf8-combined.c	1 Sep 2023 18:43:08 -0000
@@ -962,7 +962,7 @@ utf8_combined_first_cmp(struct utf8_comb
 		return (-1);
 	if (ud1->size > ud2->size)
 		return (1);
-	return (memcmp(ud1->data, ud2->data, sizeof *ud1->data));
+	return (memcmp(ud1->data, ud2->data, ud1->size));
 }
 RB_HEAD(utf8_combined_tree, utf8_combined_first);
 RB_GENERATE_STATIC(utf8_combined_tree, utf8_combined_first, entry,
@@ -979,7 +979,7 @@ utf8_combined_second_cmp(const void *vp1
 		return (-1);
 	if (ud1->size > ud2->size)
 		return (1);
-	return (memcmp(ud1->data, ud2->data, sizeof *ud1->data));
+	return (memcmp(ud1->data, ud2->data, ud1->size));
 }

 static int

**Comment by nicm** [comment]
I'm going to close this to get it out of the way but please let me know if you still see issues with vim and I will reopen. Thanks!

**Comment by elcurious** [comment]
Sorry for my (very) late reply, and thanks a lot for all your work on this, Nicholas!

I tested the latest changes at `master` (f68d35c5), and there still seems to be some issues outside and inside neovim. 

For outside neovim, here is exactly how to reproduce:

1. Open kitty using `kitty --config NONE /bin/bash --norc --noprofile`.
2. Run `printf "Test\t\t|\n'👍' Test\t|\n'👍🏻' Test\t|\n'🇪🇸' Test\t|\n" > test.txt`.
3. Run `cat test.txt`.
4. Observe that the vertical bars are aligned properly:
![image](https://github.com/tmux/tmux/assets/136172567/f55c889d-78ad-43c3-9afe-3e6e00263aee)
5. Run `~/tmux/tmux -L test -f /dev/null -vv new /bin/bash --norc --noprofile`.
6. Run `cat test.txt`.
7. Observe that the vertical bars are not aligned:
![image](https://github.com/tmux/tmux/assets/136172567/b2af1600-14e9-4316-9eda-931036e19ff5)

Here are the tmux logs for this session:
[tmux-client-17039.log](https://github.com/tmux/tmux/files/12565413/tmux-client-17039.log)
[tmux-out-17041.log](https://github.com/tmux/tmux/files/12565414/tmux-out-17041.log)
[tmux-server-17041.log](https://github.com/tmux/tmux/files/12565415/tmux-server-17041.log)

For inside neovim:

1. Open kitty using `kitty --config NONE /bin/bash --norc --noprofile`.
2. Run `printf "Test\t\t|\n'👍' Test\t|\n'👍🏻' Test\t|\n'🇪🇸' Test\t|\n" > test.txt`.
3. Run `nvim -u NONE -c 'set colorcolumn=20' test.txt`.
4. Observe that the color column is aligned properly:
![image](https://github.com/tmux/tmux/assets/136172567/f2eaa17e-f437-4111-afb7-9be80729e82a)
5. Run `~/tmux/tmux -L test -f /dev/null -vv new /bin/bash --norc --noprofile`.
6. Run `nvim -u NONE -c 'set colorcolumn=20' test.txt`.
7. Observe that the color column's misalignment:
![image](https://github.com/tmux/tmux/assets/136172567/8fe740c3-552e-40d6-a76b-22fdd6e8847f)

Here are the tmux logs for this session:
[tmux-client-34960.log](https://github.com/tmux/tmux/files/12565430/tmux-client-34960.log)
[tmux-out-34962.log](https://github.com/tmux/tmux/files/12565431/tmux-out-34962.log)
[tmux-server-34962.log](https://github.com/tmux/tmux/files/12565432/tmux-server-34962.log)

Here are the `script` files for running neovim inside and outside tmux (recorded using `script -c 'nvim -u NONE -c "set colorcolumn=20" test.txt' <filename>`):

[inside_tmux.script.txt](https://github.com/tmux/tmux/files/12565447/inside_tmux.script.txt)
[outside_tmux.script.txt](https://github.com/tmux/tmux/files/12565448/outside_tmux.script.txt)

Software Versions:
- kitty: 0.29.2
- Bash: 5.1.16(1)-release
- Linux kernel: 6.4.12

**Comment by elcurious** [comment]
It's worth noting that the issue is not just about cosmetics. For example, when editing `text.txt` in neovim in tmux, typing `Gfe` in normal mode should position the cursor on top of the "e" in "Test" on the fourth line, but it positions it over the "t" instead:

![image](https://github.com/tmux/tmux/assets/136172567/343de240-109d-47ef-9457-58a937e643d4).

The cursor is positioned correctly when editing `test.txt` in neovim outside of tmux:

![image](https://github.com/tmux/tmux/assets/136172567/ae3ce1de-765e-4afc-871d-94350e908dcc)

**Comment by nicm** [comment]
Ah, it looks OK for me because iTerm2 has DECSLRM so the way tmux does cursor positioning is different and this hides the problem.

It was working but I broke it by accident, please try this:[x.diff.txt](https://github.com/tmux/tmux/files/12594920/x.diff.txt)

**Comment by elcurious** [comment]
Thanks for the quick fix! I tried  8191c58 which contains the diff above. It fixes the misalignment of the vertical bars when `cat`ing `test.txt` inside tmux. However, the neovim [issue](https://github.com/tmux/tmux/issues/3600#issuecomment-1712471623) still persists.

Do you need me to capture some logs at 8191c58?

**Comment by nicm** [comment]
No, I'll have a look at vim at some point.

**Comment by nicm** [comment]
Is this better? I was trying to get away from reaching into the existing data to check if we need to combine because that is going to be slow, but I think that is what we will have to do: [width.diff.txt](https://github.com/tmux/tmux/files/12617638/width.diff.txt)

**Comment by nicm** [comment]
Don't bother with that one, it doesn;t work with actual zero width characters, will send a new one later.

**Comment by nicm** [comment]
Try this please: [width2.diff.txt](https://github.com/tmux/tmux/files/12618658/width2.diff.txt)

I'm not wild about calling `mbtowc` to look up the character in the table but maybe it will be alright...

**Comment by elcurious** [comment]
Thanks for quickly looking into this, Nicholas! I applied the latest diff to 9f9156c0 and cannot reproduce the issue anymore 🎉

**Comment by nicm** [comment]
OK I have applied this now, please let me know if you see any further problems.
