### ISSUE TITLE
[FR] Add `-c start-directory` option to `run-shell` command

### ISSUE THREAD

**Issue by pataquets** [tmux/tmux#3608]
### Issue description
As done for `new-window` command, for instance.
Being able to customize where commands are run has lots of scenarios where it is useful.

### Required information
``` console
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 3.3a
tmux-256color
```

**Comment by caiuswang** [comment]
Do you mean starting directory?  If it is, you can  run new-window with '-c' to specify it.

**Comment by nicm** [comment]
I'm closing this because we do not need an issue and a PR, please see my comments on the PR, thanks.
