### ISSUE TITLE
Underline colors not working

### ISSUE THREAD

**Issue by ciza99** [tmux/tmux#3609]
* tmux version (`tmux -V`).
tmux 3.2a

* Platform (`uname -sp`).
Linux x86_64 (Ubuntu 22.04.2)

* $TERM inside and outside of tmux (`echo $TERM`).
inside tmux: `screen`
outside tmux: `xterm-256color`

## Issue

Underline colors work normally outside of tmux. However whenever I enter tmux, the underline colors are the same as the text.
I have tried searching for this but seems like its hard to find a solution. I use the Gnome Terminal Version 3.44.0.

Inside `.tmux.conf` I do set the overides to use 256-color like so:
`set-option -ga terminal-overrides ",xterm-256color:Tc"`

**Comment by nicm** [comment]
tmux cannot automatically detect Gnome Terminal so you will have to tell it these are supported, try:
~~~~
set -as terminal-features 'xterm*:usstyle'

**Comment by ciza99** [comment]
> tmux cannot automatically detect Gnome Terminal so you will have to tell it these are supported, try:
> 
> ```
> set -as terminal-features 'xterm*:usstyle'
> ```

That worked! I have seen the `usstyle` option somewhere in the man page of `tmux` but I tried to set it with terminal-overrides and probably did it wrong. Thank you :+1: :+1:

**Comment by nicm** [comment]
It is possible to do the same with `terminal-overrides` but `terminal-features` was added so you could enable these features easily without having to muck about figuring what escape sequences to set.
