### ISSUE TITLE
format_skip() can read beyond the end of its input

### ISSUE THREAD

**Issue by rtmrtmrtmrtm** [tmux/tmux#3610]
format_skip() in tmux-3.3a's format.c will read off the end of the
input string if it ends with a #. The strchr() here:

        for (; *s != '\0'; s++) {
                ...;
                if (*s == '#' && strchr(",#{}:", s[1]) != NULL) {
                        s++;
                        continue;

returns non-NULL if s[1] is '\0', since strchr() is specified to find
a '\0' if asked. Then the s++ skips the terminating '\0', and
(depending on what follows) format_skip() likely returns an "end"
value that's beyond the end of the input string.

One consequence is that this code in format_trim_left():

                       if (*cp == '#') {
                                end = format_skip(cp + 2, "]");
                                if (end == NULL)
                                        break;
                                memcpy(out, cp, end + 1 - cp);

can write beyond the end of the allocated heap block for out if the
input ends with #.

I've attached a file which exercises this if displayed in tmux with
cat. This example doesn't usually result in a core dump for me, so I have to
add an assertion (or step through in gdb) to see the problem.

[tmux2a.txt](https://github.com/tmux/tmux/files/11930772/tmux2a.txt)

**Comment by nicm** [comment]
It does look like a problem and your analysis seems correct, but I cannot see the problem with your test file (which I assume you have generated with some tool). I did this:
~~~~
@@ -3659,9 +3660,11 @@ format_strip(const char *s)
 const char *
 format_skip(const char *s, const char *end)
 {
-       int     brackets = 0;
+       int             brackets = 0;
+       const char*     ep = s + strlen(s);

        for (; *s != '\0'; s++) {
+               assert(s <= ep);
                if (*s == '#' && s[1] == '{')
                        brackets++;
                if (*s == '#' && strchr(",#{}:", s[1]) != NULL) {
~~~~
And it does not trigger.

In any case, does this fix the problem:
~~~~
--- format.c    19 May 2023 07:46:34 -0000      1.313
+++ format.c    3 Jul 2023 09:32:33 -0000
@@ -3664,7 +3664,9 @@ format_skip(const char *s, const char *e
        for (; *s != '\0'; s++) {
                if (*s == '#' && s[1] == '{')
                        brackets++;
-               if (*s == '#' && strchr(",#{}:", s[1]) != NULL) {
+               if (*s == '#' &&
+                   s[1] != '\0' &&
+                   strchr(",#{}:", s[1]) != NULL) {
                        s++;
                        continue;
                }

**Comment by rtmrtmrtmrtm** [comment]
Yes, the change you have in mind does fix the problem for me.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
