### ISSUE TITLE
tmux-3.3a's format_trim_left() doesn't allocate enough space in some cases

### ISSUE THREAD

**Issue by rtmrtmrtmrtm** [tmux/tmux#3611]
format_trim_left() in format-draw.c assumes the output will be
no larger than the input:

        out = copy = xcalloc(1, strlen(expanded) + 1);

This is an example of an input whose output is longer than the
input:

  ###w}K

For this input, format_leading_hashes() consumes the three #'s (i.e.
returns end = cp+3), but also returns leading_width = 2, causing
the following

  out += 2 * leading_width

to generate four bytes of output, not three.

I've attached a file which, if you display it in tmux with cat,
tickles this problem, though you'll likely have to add something like

  assert(out - copy <= strlen(expanded))

at the end of format_trim_left() to see it.

[tmux8a.txt](https://github.com/tmux/tmux/files/11931067/tmux8a.txt)

**Comment by nicm** [comment]
Thanks. This looks right and the test file does work, OpenBSD malloc's `C` option blows it up on `free` for writing over the canary.

This seems like a trivial fix:
~~~~
--- format-draw.c       22 Feb 2022 11:07:25 -0000      1.26
+++ format-draw.c       3 Jul 2023 09:42:01 -0000
@@ -1083,7 +1083,7 @@ format_trim_left(const char *expanded, u
        struct utf8_data         ud;
        enum utf8_state          more;

-       out = copy = xcalloc(1, strlen(expanded) + 1);
+       out = copy = xcalloc(1, 2 * strlen(expanded) + 1);
        while (*cp != '\0') {
                if (width >= limit)
                        break;
@@ -1150,7 +1150,7 @@ format_trim_right(const char *expanded,
                return (xstrdup(expanded));
        skip = total_width - limit;

-       out = copy = xcalloc(1, strlen(expanded) + 1);
+       out = copy = xcalloc(1, 2 * strlen(expanded) + 1);
        while (*cp != '\0') {
                if (*cp == '#') {
                        end = format_leading_hashes(cp, &n, &leading_width);

**Comment by nicm** [comment]
I applied this now.
