### ISSUE TITLE
cmd_find_target: error

### ISSUE THREAD

**Issue by EdmundsEcho** [tmux/tmux#3616]
* tmux version (`tmux -V`): 3.3a
* Platform (`uname -sp`): Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`): screen-256color, xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`): 

I'm reporting a log that opens then closes a tmux session.   There are no plugins, nor am I running `tpm`.  When I do, I just get a lot more of the error.

<details>
<summary>Several `cmd_find_target: error` entries</summary>
```log
1688757422.551042 yylex_token: unbind
1688757422.551046 yylex_token: C-b
1688757422.551049 yylex_token: set
1688757422.551052 yylex_token: -g
1688757422.551054 yylex_token: prefix
1688757422.551057 yylex_token: C-s
1688757422.551061 yylex_token: bind
1688757422.551064 yylex_token: -r
1688757422.551066 yylex_token: C-s
1688757422.551069 yylex_token: send-prefix
1688757422.551075 cmd_parse_build_commands 0:0: unbind
1688757422.551078 cmd_parse_build_commands 0:1: C-b
1688757422.551080 cmd_parse_build_commands 1:0: set
1688757422.551082 cmd_parse_build_commands 1:1: -g
1688757422.551085 cmd_parse_build_commands 1:2: prefix
1688757422.551087 cmd_parse_build_commands 1:3: C-s
1688757422.551089 cmd_parse_build_commands 2:0: bind
1688757422.551091 cmd_parse_build_commands 2:1: -r
1688757422.551094 cmd_parse_build_commands 2:2: C-s
1688757422.551096 cmd_parse_build_commands 2:3: send-prefix
1688757422.551103 args_parse: flags end at 1 of 2
1688757422.551105 args_parse: 1 = C-b (type 1)
1688757422.551110 args_parse: -g
1688757422.551113 args_parse: flags end at 2 of 4
1688757422.551115 args_parse: 2 = prefix (type 1)
1688757422.551118 args_parse: 3 = C-s (type 1)
1688757422.551121 args_parse: -r
1688757422.551124 args_parse: flags end at 2 of 4
1688757422.551126 args_parse: 2 = C-s (type 1)
1688757422.551128 args_parse: 3 = send-prefix (type 1)
1688757422.551138 cmd_parse_build_commands: unbind-key C-b ;; set-option -g prefix C-s ;; bind-key -r C-s send-prefix
1688757422.551148 cmdq_get_command: [unbind-key/0x10de0c780] group 2575
1688757422.551151 cmdq_get_command: [set-option/0x10de0c870] group 2578
1688757422.551154 cmdq_get_command: [bind-key/0x10de0cbc0] group 2581
1688757422.551157 cmdq_append <global>: [unbind-key/0x10de0c780]
1688757422.551159 cmdq_append <global>: [set-option/0x10de0c870]
1688757422.551161 cmdq_append <global>: [bind-key/0x10de0cbc0]
1688757422.551164 cmdq_append <global>: [cfg_done/0x10de0cac0]
1688757422.551166 peer 0x110008000 message 200
1688757422.551170 cmd_unpack_argv: argv[0]=new
1688757422.551173 cmd_parse_build_commands 0:0: new
1688757422.551176 args_parse: flags end at 1 of 1
1688757422.551179 cmd_parse_build_commands: new-session
1688757422.551182 cmdq_get_command: [new-session/0x10de0cec0] group 2585
1688757422.551185 cmdq_append </dev/ttys001>: [new-session/0x10de0cec0]
1688757422.551188 cmdq_append </dev/ttys001>: [server_client_command_done/0x10de0d030]
1688757422.551191 cmdq_next <global>: enter
1688757422.551194 cmdq_next <global>: [unbind-key/0x10de0c780] (0), flags 0
1688757422.551201 cmdq_fire_command <global>: (2575) unbind-key C-b
1688757422.551203 cmd_find_best_session: 0 sessions to try
1688757422.551205 cmd_find_current_client: no target, return 0x0
1688757422.551208 cmd_find_best_session: 0 sessions to try
1688757422.551210 cmd_find_current_client: no target, return 0x0
1688757422.551212 cmd_find_best_session: 0 sessions to try
1688757422.551214 cmd_find_best_session: 0 sessions to try
1688757422.551218 key_bindings_remove: 0x2 C-b
1688757422.551220 cmd_find_best_session: 0 sessions to try
1688757422.551223 cmdq_next <global>: [set-option/0x10de0c870] (0), flags 0
1688757422.551227 cmdq_fire_command <global>: (2578) set-option -g prefix C-s
1688757422.551230 cmd_find_best_session: 0 sessions to try
1688757422.551232 cmd_find_current_client: no target, return 0x0
1688757422.551234 cmd_find_best_session: 0 sessions to try
1688757422.551236 cmd_find_current_client: no target, return 0x0
1688757422.551238 cmd_find_best_session: 0 sessions to try
1688757422.551242 cmd_find_target: target none, type pane, item 0x10de0c870, flags QUIET,CANFAIL
1688757422.551244 cmd_find_best_session: 0 sessions to try
1688757422.551246 cmd_find_target: error                   <<<<< HERE
1688757422.551250 format_defaults: c=none
1688757422.551252 format_defaults: s=none
1688757422.551254 format_defaults: wl=none
1688757422.551256 format_defaults: wp=none
1688757422.551260 format_expand1: expanding format: prefix
1688757422.551263 format_expand1: result is: prefix
1688757422.551276 options_push_changes: prefix
1688757422.551280 cmd_find_best_session: 0 sessions to try
1688757422.551283 cmdq_next <global>: [bind-key/0x10de0cbc0] (0), flags 0
1688757422.551287 cmdq_fire_command <global>: (2581) bind-key -r C-s send-prefix
1688757422.551290 cmd_find_best_session: 0 sessions to try
1688757422.551292 cmd_find_current_client: no target, return 0x0
1688757422.551294 cmd_find_best_session: 0 sessions to try
1688757422.551296 cmd_find_current_client: no target, return 0x0
1688757422.551298 cmd_find_best_session: 0 sessions to try
1688757422.551301 cmd_find_best_session: 0 sessions to try
1688757422.551304 yylex_token: send-prefix
1688757422.551307 cmd_parse_build_commands 0:0: send-prefix
1688757422.551310 args_parse: flags end at 1 of 1
1688757422.551313 cmd_parse_build_commands: send-prefix
1688757422.551317 key_bindings_add: 0x13 C-s = send-prefix
1688757422.551319 cmd_find_best_session: 0 sessions to try
1688757422.551324 cmdq_next <global>: [cfg_done/0x10de0cac0] (1), flags 0
1688757422.551327 cmdq_next <global>: exit (empty)
1688757422.551329 cmdq_next </dev/ttys001>: enter
1688757422.551332 cmdq_next </dev/ttys001>: [cfg_client_done/0x10de0be90] (1), flags 0
1688757422.551335 unref client 0x11e80c600 (4 references)
1688757422.551337 cmdq_next </dev/ttys001>: [new-session/0x10de0cec0] (0), flags 0
1688757422.551341 message: /dev/ttys001 command: new-session
1688757422.551343 cmdq_fire_command </dev/ttys001>: (2585) new-session
1688757422.551346 cmd_find_best_session: 0 sessions to try
1688757422.551348 cmd_find_current_client: no target, return 0x0
1688757422.551350 cmd_find_best_session: 0 sessions to try
1688757422.551353 cmd_find_target: target none, type session, item 0x10de0cec0, flags QUIET,CANFAIL
1688757422.551356 cmd_find_best_session: 0 sessions to try
1688757422.551358 cmd_find_target: error                   <<<<<< HERE
1688757422.551364 adding term xterm-256color
```
</details>

Does anyone have ideas for how to troubleshoot this!

**Comment by krader1961** [comment]
> Does anyone have ideas for how to troubleshoot this!

Troubleshoot what? The `cmd_find_target: error` log entry can appear for a large number of reasons. See the source code for the function in source file *cmd-find.c*. In your case the preceding two log entries explain why:

```
1688757422.551353 cmd_find_target: target none, type session, item 0x10de0cec0, flags QUIET,CANFAIL
1688757422.551356 cmd_find_best_session: 0 sessions to try 
```

In other words, there are no sessions so `cmd_find_target` cannot succeed. It would help if you told us the sequence of operations you performed, what you expected, and what you observed.

**Comment by EdmundsEcho** [comment]
Thank you for your response.  The sequence starts from an open terminal, after having killed the tmux server:

```
> tmux -vv new
# in the tmux session
> exit
```

When I have the battery plugin activated, I quickly generate a bunch of these errors.

What does `cmd_find_target` need to successfully find a target session(s) for `cmd_find_best_session`?

**Comment by krader1961** [comment]
> When I have the battery plugin activated, I quickly generate a bunch of these errors.

You wrote in your original problem statement: "There are no plugins". Which is it?

> What does cmd_find_target need to successfully find a target session(s) for cmd_find_best_session?

It doesn't, but in that case it reports an error and returns -1 to indicate it could not find the best session. Which makes sense since there are no sessions after you exit the only session that (briefly) existed. I still don't understand what the problem is. Is the problem that the tmux server is consuming a lot of CPU cycles when you use the battery plugin when there are no tmux sessions?

**Comment by EdmundsEcho** [comment]
I'm taking advantage of my recently "cleaning-up" for lack of a better word, my setup.  That said, I have a lag when I fire-up new panes; I'm trying to see if there is something I can do about it.  It sounds like the server firing off errors is ok as long as things work?  In my troubleshooting I was trying to get to a state with no errors.  That may not be possible during the initialization phase?

**Comment by krader1961** [comment]
> That may not be possible during the start-up and shutting down phases?

Correct, there are many actions the Tmux server may attempt to perform that may fail and those failures are harmless. They are logged solely to help in diagnosing real problems; i.e., when a failure to find the best session **unexpectedly** occurs.

Rather than focusing on figuring out the meaning of each line in the Tmux server log it would be more productive to take a step back and clearly describe the problem and how someone else might reproduce it. I suggest starting by ensuring no Tmux server is running then starting it with no config (`tmux -f /dev/null`) and see if your problem still occurs. If it does then the problem probably has nothing to do with Tmux. If it doesn't then it's due to your specific Tmux configuration and we can work on identifying which aspect of your config is causing the problem.

**Comment by EdmundsEcho** [comment]
Per the recommendation, I logged the activity without using my configuration file.  

This establishes a baseline.  The error messages recorded during this baseline are seemingly "innocuous"; tmux "works".  

If the baseline does not help speed-up the initialization, it will help me in the future (e.g., need to debug following an update; including from external dependencies that impact tmux).  I'll have a better idea of what error messages are essentially "par for the course" when operating "normally".

The logs were generated as follows:

```fish
> tmux -f /dev/null -vv new
# in the tmux session
> echo $TERM
screen-256color
> exit
```

## client log: Connection refused
The baseline client activity for tmux includes "trying to connect" and failing once or twice before "working".

This was relevant at one point when MacOS changed it's access privilege policies.  If memory servers, that included the introduction of `/private/` in the root.  To avoid having to depend on the root directory, I set-up `$HOME/tmp/tmux`.  

Notwithstanding, it clearly works as I'm able to connect to active sessions.  However,  I'm not sure what causes the initial failure; perhaps this is inherent in first establishing a connection.

<details>
<summary>Client log with refused connections</summary>

```log
1689001582.667404 client started (59795): version 3.3a, socket /Users/edmund/tmp/tmux/tmux-501/default, protocol 8
1689001582.667491 on Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
1689001582.667921 using libevent 2.1.12-stable (select); utf8proc 2.8.0; ncurses 6.4
1689001582.667965 flags are 0x18010000
1689001582.667982 socket is /Users/edmund/tmp/tmux/tmux-501/default
1689001582.668067 trying connect
1689001582.668114 connect failed: Connection refused
1689001582.668136 lock file is /Users/edmund/tmp/tmux/tmux-501/default.lock
1689001582.668406 flock succeeded
1689001582.668422 got lock (18)
1689001582.668434 trying connect
1689001582.668452 connect failed: Connection refused
1689001582.669071 add peer 0x130008000: 19 (0x0)
1689001582.674212 sending message 100 to peer 0x130008000 (4 bytes)
1689001582.674248 sending message 111 to peer 0x130008000 (8 bytes)
```
</details>

## server log: new-session error

This error occurred once in the baseline.  However, this error happens repeatedly over time the more I interact with tmux.  When I load the battery plugin, it happens every second.  

<details>
<summary>Baseline will include a `cmd_find_target:error`</summary>

```log
1689001582.723279 message: /dev/ttys009 command: new-session
1689001582.723283 cmdq_fire_command </dev/ttys009>: (2576) new-session
1689001582.723286 cmd_find_best_session: 0 sessions to try
1689001582.723288 cmd_find_current_client: no target, return 0x0
1689001582.723291 cmd_find_best_session: 0 sessions to try
1689001582.723294 cmd_find_target: target none, type session, item 0x14f61ae90, flags QUIET,CANFAIL
1689001582.723296 cmd_find_best_session: 0 sessions to try
1689001582.723298 cmd_find_target: error
```

</details>


## server log: new-session error

This error happened once during the baseline.  I have not seen this error occur more than that when I run a "fully-configured" instance of tmux.

<details>
<summary>What seems like a "one-off" error finding window @0</summary>

```log
1689001603.033242 @0 name timer already queued (494205 left)
1689001603.033255 %0 error
1689001603.033283 cmd_find_best_session_with_window: window is @0
```
</details>
