### ISSUE TITLE
 Failure send-keys command inside tmux binding key

### ISSUE THREAD

**Issue by abdulbadii** [tmux/tmux#3617]
### Issue description
 Why this never succeed doing `send-keys` inside tmux binding key with purpose of executing Bash' commands,
instead it always behaves echoing the command

`
bind -n C-v split-window -h  \; send-keys 'ls -Apv' C-m
`
to mean execute `ls -Apv` every time a pane is created by user pressing control v

and likewise for other Bash' commands in place of `ls -Apv` 

### Required information
* tmux version (`tmux -V`)   3.3a
* Platform (`uname -sp`). Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`).  tmux-256color   xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
```
1688824013.676689 client started (6875): version 3.3a, socket /tmp/tmux-1000/default, protocol 8
1688824013.676761 on Linux 6.3.6-artix1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Jun 2023 19:57:22 +0000
1688824013.676775 using libevent 2.1.12-stable (poll); ncurses 6.4
1688824013.676818 flags are 0x10010000
1688824013.676830 socket is /tmp/tmux-1000/default
1688824013.676856 trying connect
1688824013.677046 add peer 0x55c3d8c58820: 6 ((nil))
1688824013.678021 sending message 100 to peer 0x55c3d8c58820 (4 bytes)
1688824013.678040 sending message 111 to peer 0x55c3d8c58820 (8 bytes)
1688824013.678053 sending message 101 to peer 0x55c3d8c58820 (14 bytes)
...
...
1688824013.681829 sending message 105 to peer 0x55c3d8c58820 (16 bytes)
1688824013.681843 sending message 106 to peer 0x55c3d8c58820 (0 bytes)
1688824013.682002 cmd_pack_argv: argv[0]=new
1688824013.682017 sending message 200 to peer 0x55c3d8c58820 (8 bytes)
1688824013.682031 client loop enter
1688824013.690452 peer 0x55c3d8c58820 message 303
1688824013.690479 open write file 2 -
1688824013.690504 sending message 305 to peer 0x55c3d8c58820 (8 bytes)
1688824013.690530 write check file 2
1688824013.691007 peer 0x55c3d8c58820 message 304
1688824013.691021 write 58 to file 2
1688824013.691036 peer 0x55c3d8c58820 message 203
1688824013.691049 file 2 58 bytes left
1688824013.691091 write check file 2
1688824013.691103 client loop exit

```

**Comment by krader1961** [comment]
I don't understand. Your key binding works for me; that is, it does exactly what I would expect. It splits the current window, which starts a new shell in the new window, then sends the string `ls -Apv` followed by Enter just as if I had typed it. The shell echoes the command line then executes it.

**Comment by abdulbadii** [comment]
So even me, don't understand either on steroid
Soo painful confusing..

the xfce terminal launcher's CLI might help lead to clear idea:
`
xfce4-terminal --geometry=105x50+791+0 --execute bash -c 'lsblk -f;ls -Apv;exec bash'
`

**Comment by krader1961** [comment]
The command in your last comment is not the same thing as using `send-keys` to send a command to an interactive shell. What you seem to be saying is you want to run a command and only display its output. Try `bind -n C-v split-window -dh 'ls -Apv; read'`. The `read` command will keep the new window from closing until you press Enter in that window. You can also set the `remain-on-exit` option to `on` and omit `read`.

**Comment by abdulbadii** [comment]
"The command in your last comment is not the same thing as..."

**the xfce terminal launcher's CLI ...:**

it is just the line inside the launcher icon on desktop in `~/Desktop` from which the user starts all tmux affairs
Not yet try the help given above though... just about to do it now

**Comment by krader1961** [comment]
My comment had nothing to do with your xfce launcher. It was in reference to the command you told xfce to run:

```
tmux new 'lsblk -f; ls -Apv; exec bash'
```

That command is not the same thing as using the Tmux `send-keys` command to run `ls -Apv`. I recognize that English is not your native language but you really need to take a little more time to try and understand what I am saying.
