### ISSUE TITLE
Configurable passthrough of escape sequences without additional DCS passthrough

### ISSUE THREAD

**Issue by prashantv** [tmux/tmux#3618]
Using the DCS passthrough support (e.g., `printf "\033Ptmux;<...>\033\\"`) requires calling scripts to know they're running under tmux, making it harder to take advantage of these escape sequences more broadly.

For example, I want to use iTerm's prompt marking support (OSC 133), and this is supported natively in powerlevel10k (`POWERLEVEL9K_TERM_SHELL_INTEGRATION`), but this doesn't work within tmux since the escape sequence needs to be escaped.

If tmux passed through this escape sequence without any wrapping, these integrations could be used as-is. Users could configure tmux to specify a list of escape sequences to passthrough, e.g., in this case I'd specify `133;` as a prefix to passthrough.

**Comment by nicm** [comment]
No, tmux cannot be sure what external terminals will do with unknown escape sequences and in any case this will break as soon as tmux adds support for the sequence itself. The passthrough sequence is going to remain required, sorry.

**Comment by prashantv** [comment]
The conditional prefix would allow users to configure what is passed through based on the terminal they're using. Given that passthrough is already passing through escape sequences that may not work, would a user-configured passthrough be any different?

While tmux support for escape codes is ideal, there's a lot of proprietary escape codes being added to terminals which may never make sense to support in tmux, and I don't think think the tmux-specific passthrough is something other programs will explicitly use to support these use-cases.
