### ISSUE TITLE
Pasting into tmux rearranges pasted content, after extended uptime

### ISSUE THREAD

**Issue by askedrelic** [tmux/tmux#362]
Hi, I hope you have some ideas: I've noticed after leaving a tmux session open for a long time (10 days apparently), when pasting, it scrambles the pasted content. Restarting the tmux server fixes it, so it's not that bad. It's happened several times to me over the last few months, but I finally have time to record all the details.

Here is a quick example of what happens when trying to paste the alphabet. It appears like for short pasted content, it's only visually altered?
```
$ abcdefghijklmoprstuvwxz nqy
-bash: abcdefghijklmoprstuvwxz: command not found
```

Here is a longer example from 2 different terminals, both connected to the same tmux session/server. I tried to narrow down that it wasn't just iTerm doing this behavior.

iTerm paste behavior
http://files.asktherelic.com/20160407-1628-tt4ez.mp4

OSX Terminal paste behavior
http://files.asktherelic.com/20160407-1629-b3uod.mp4

Here is all my relevant info, but since I'm about to restart tmux, it might take awhile to get to this state again, if you need more info.
```
System is OSX, 10.11.4
Terminal 2.6.1
iTerm 2.9.20160313 (nightly)

$ tmux -V
tmux 2.1

# current tmux.conf
https://github.com/askedrelic/dotfiles/blob/master/system/tmux.conf.symlink

$ uptime
 16:31pm  up 10 days  1:05,  3 users,  load average: 2.53, 2.73, 2.38

 $ tmux server-info
started Tue Mar 29 10:27:40 2016
socket path /private/var/folders/1c/4b08bpwj51j_f5pxj6sxxbgh5hjc11/T/tmux-185118753/default
debug level 0
protocol version 8

Terminal 0: xterm-256color [references=1, flags=0x1]:
   0: AX: (flag) true
   1: acsc: (string) ``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~
   2: bce: (flag) true
   3: bel: (string) \007
   4: blink: (string) \033[5m
   5: bold: (string) \033[1m
   6: civis: (string) \033[?25l
   7: clear: (string) \033[H\033[2J
   8: cnorm: (string) \033[?12l\033[?25h
   9: colors: (number) 256
  10: Cr: (string) \033]112\007
  11: Cs: (string) \033]12;%p1%s\007
  12: csr: (string) \033[%i%p1%d;%p2%dr
  13: cub: (string) \033[%p1%dD
  14: cub1: (string) \010
  15: cud: (string) \033[%p1%dB
  16: cud1: (string) \012
  17: cuf: (string) \033[%p1%dC
  18: cuf1: (string) \033[C
  19: cup: (string) \033[%i%p1%d;%p2%dH
  20: cuu: (string) \033[%p1%dA
  21: cuu1: (string) \033[A
  22: cvvis: (string) \033[?12;25h
  23: dch: (string) \033[%p1%dP
  24: dch1: (string) \033[P
  25: dim: [missing]
  26: dl: (string) \033[%p1%dM
  27: dl1: (string) \033[M
  28: E3: [missing]
  29: ech: (string) \033[%p1%dX
  30: el: (string) \033[K
  31: el1: (string) \033[1K
  32: enacs: [missing]
  33: fsl: (string) \007
  34: home: (string) \033[H
  35: hpa: (string) \033[%i%p1%dG
  36: ich: (string) \033[%p1%d@
  37: ich1: [missing]
  38: il: (string) \033[%p1%dL
  39: il1: (string) \033[L
  40: invis: (string) \033[8m
  41: is1: [missing]
  42: is2: (string) \033[!p\033[?3;4l\033[4l\033>
  43: is3: [missing]
  44: kcbt: (string) \033[Z
  45: kcub1: (string) \033OD
  46: kcud1: (string) \033OB
  47: kcuf1: (string) \033OC
  48: kcuu1: (string) \033OA
  49: kDC: (string) \033[3;2~
  50: kDC3: (string) \033[3;3~
  51: kDC4: (string) \033[3;4~
  52: kDC5: (string) \033[3;5~
  53: kDC6: (string) \033[3;6~
  54: kDC7: (string) \033[3;7~
  55: kdch1: (string) \033[3~
  56: kDN: (string) \033[1;2B
  57: kDN3: (string) \033[1;3B
  58: kDN4: (string) \033[1;4B
  59: kDN5: (string) \033[1;5B
  60: kDN6: (string) \033[1;6B
  61: kDN7: (string) \033[1;7B
  62: kend: (string) \033OF
  63: kEND: (string) \033[1;2F
  64: kEND3: (string) \033[1;3F
  65: kEND4: (string) \033[1;4F
  66: kEND5: (string) \033[1;5F
  67: kEND6: (string) \033[1;6F
  68: kEND7: (string) \033[1;7F
  69: kf1: (string) \033OP
  70: kf10: (string) \033[21~
  71: kf11: (string) \033[23~
  72: kf12: (string) \033[24~
  73: kf13: (string) \033[1;2P
  74: kf14: (string) \033[1;2Q
  75: kf15: (string) \033[1;2R
  76: kf16: (string) \033[1;2S
  77: kf17: (string) \033[15;2~
  78: kf18: (string) \033[17;2~
  79: kf19: (string) \033[18;2~
  80: kf2: (string) \033OQ
  81: kf20: (string) \033[19;2~
  82: kf21: (string) \033[20;2~
  83: kf22: (string) \033[21;2~
  84: kf23: (string) \033[23;2~
  85: kf24: (string) \033[24;2~
  86: kf25: (string) \033[1;5P
  87: kf26: (string) \033[1;5Q
  88: kf27: (string) \033[1;5R
  89: kf28: (string) \033[1;5S
  90: kf29: (string) \033[15;5~
  91: kf3: (string) \033OR
  92: kf30: (string) \033[17;5~
  93: kf31: (string) \033[18;5~
  94: kf32: (string) \033[19;5~
  95: kf33: (string) \033[20;5~
  96: kf34: (string) \033[21;5~
  97: kf35: (string) \033[23;5~
  98: kf36: (string) \033[24;5~
  99: kf37: (string) \033[1;6P
 100: kf38: (string) \033[1;6Q
 101: kf39: (string) \033[1;6R
 102: kf4: (string) \033OS
 103: kf40: (string) \033[1;6S
 104: kf41: (string) \033[15;6~
 105: kf42: (string) \033[17;6~
 106: kf43: (string) \033[18;6~
 107: kf44: (string) \033[19;6~
 108: kf45: (string) \033[20;6~
 109: kf46: (string) \033[21;6~
 110: kf47: (string) \033[23;6~
 111: kf48: (string) \033[24;6~
 112: kf49: (string) \033[1;3P
 113: kf5: (string) \033[15~
 114: kf50: (string) \033[1;3Q
 115: kf51: (string) \033[1;3R
 116: kf52: (string) \033[1;3S
 117: kf53: (string) \033[15;3~
 118: kf54: (string) \033[17;3~
 119: kf55: (string) \033[18;3~
 120: kf56: (string) \033[19;3~
 121: kf57: (string) \033[20;3~
 122: kf58: (string) \033[21;3~
 123: kf59: (string) \033[23;3~
 124: kf6: (string) \033[17~
 125: kf60: (string) \033[24;3~
 126: kf61: (string) \033[1;4P
 127: kf62: (string) \033[1;4Q
 128: kf63: (string) \033[1;4R
 129: kf7: (string) \033[18~
 130: kf8: (string) \033[19~
 131: kf9: (string) \033[20~
 132: kHOM: (string) \033[1;2H
 133: kHOM3: (string) \033[1;3H
 134: kHOM4: (string) \033[1;4H
 135: kHOM5: (string) \033[1;5H
 136: kHOM6: (string) \033[1;6H
 137: kHOM7: (string) \033[1;7H
 138: khome: (string) \033OH
 139: kIC: (string) \033[2;2~
 140: kIC3: (string) \033[2;3~
 141: kIC4: (string) \033[2;4~
 142: kIC5: (string) \033[2;5~
 143: kIC6: (string) \033[2;6~
 144: kIC7: (string) \033[2;7~
 145: kich1: (string) \033[2~
 146: kLFT: (string) \033[1;2D
 147: kLFT3: (string) \033[1;3D
 148: kLFT4: (string) \033[1;4D
 149: kLFT5: (string) \033[1;5D
 150: kLFT6: (string) \033[1;6D
 151: kLFT7: (string) \033[1;7D
 152: kmous: (string) \033[M
 153: knp: (string) \033[6~
 154: kNXT: (string) \033[6;2~
 155: kNXT3: (string) \033[6;3~
 156: kNXT4: (string) \033[6;4~
 157: kNXT5: (string) \033[6;5~
 158: kNXT6: (string) \033[6;6~
 159: kNXT7: (string) \033[6;7~
 160: kpp: (string) \033[5~
 161: kPRV: (string) \033[5;2~
 162: kPRV3: (string) \033[5;3~
 163: kPRV4: (string) \033[5;4~
 164: kPRV5: (string) \033[5;5~
 165: kPRV6: (string) \033[5;6~
 166: kPRV7: (string) \033[5;7~
 167: kRIT: (string) \033[1;2C
 168: kRIT3: (string) \033[1;3C
 169: kRIT4: (string) \033[1;4C
 170: kRIT5: (string) \033[1;5C
 171: kRIT6: (string) \033[1;6C
 172: kRIT7: (string) \033[1;7C
 173: kUP: (string) \033[1;2A
 174: kUP3: (string) \033[1;3A
 175: kUP4: (string) \033[1;4A
 176: kUP5: (string) \033[1;5A
 177: kUP6: (string) \033[1;6A
 178: kUP7: (string) \033[1;7A
 179: Ms: (string) \033]52;%p1%s;%p2%s\007
 180: op: (string) \033[39;49m
 181: rev: (string) \033[7m
 182: ri: (string) \033M
 183: rmacs: (string) \033(B
 184: rmcup: (string) \033[?1049l
 185: rmkx: (string) \033[?1l\033>
 186: Se: (string) \033[2 q
 187: setab: (string) \033[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m
 188: setaf: (string) \033[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m
 189: sgr0: (string) \033(B\033[m
 190: sitm: [missing]
 191: smacs: (string) \033(0
 192: smcup: (string) \033[?1049h
 193: smkx: (string) \033[?1h\033=
 194: smso: (string) \033[7m
 195: smul: (string) \033[4m
 196: Ss: (string) \033[%p1%d q
 197: tsl: (string) \033]0;
 198: vpa: (string) \033[%i%p1%dd
 199: xenl: (flag) true
 200: XT: (flag) true

Job 0: whoami [fd=44, pid=11752, status=0]
Job 1: tmux send-keys 'Enter'; /Users/mbehrens/.tmux/plugins/tmux-copycat/scripts/copycat_mode_quit.sh; true [fd=13, pid=11747, status=0]
```

**Comment by nicm** [comment]
Do you mean tmux pasting (C-b ]) or terminal pasting? What is in your .tmux.conf?

**Comment by askedrelic** [comment]
This is using Terminal paste. The behavior is the same on Terminal paste using iTerm and OSX Terminal.

Tmux conf is here available here; I am running 5 plugins (I know that can always be a source of weirdness) but I don't think any of them actively affect paste behavior.
https://github.com/askedrelic/dotfiles/blob/master/system/tmux.conf.symlink

**Comment by nicm** [comment]
And if you detach tmux, close the terminal, open a new terminal and reattach tmux, the problem remains?

Also if you paste the same content outside tmux it is fine?

**Comment by askedrelic** [comment]
Yes, here is a video showing that behavior, with iTerm 2 and copy on select: https://files.asktherelic.com/20160413-2100-3n9yd.mp4

Seems like I hit it again today after about 5 days uptime.

**Comment by nicm** [comment]
Yes to which question?

**Comment by askedrelic** [comment]
Yes, to both questions. 

That video should show
- typing the alphabet in correct order, in iTerm, in a tmux session
- copy and paste using native iTerm, with the paste in the incorrect order, mainly the n/q letters at the end
- tmux detach
- while outside out tmux, in normal iTerm session, the same content is pasted unaltered
- tmux reattach, to the previous session
- pasting the same content, results in the incorrect order again

**Comment by nicm** [comment]
And if you then detach this tmux in iTerm2 and attach the same tmux in Terminal.app or xterm, you have the same problem?

**Comment by askedrelic** [comment]
If I remember correctly from my original test session, I think switching Terminal apps and detaching/reattaching did not fix the problem; I would still get pasting problems from both terminals.

I will specifically try this next time I can reproduce (which might be 5ish days from now)

**Comment by narayandesai** [comment]
I think that I'm experiencing a related (or perhaps the same) problem. I'm on OSX, with ITerm2. After extended uptime, terminal (cmd-v) pastes start getting garbled in a consistent way. In my case, the paste is prepended with the string "00~" and "01~" is appended. 

Detach/attach of the session doesn't help, only a full shutdown of the session fixes the problem. Detaching from ITerm2 and reattaching from Terminal.app exhibits the same problem. 

It looks like the problem is with the session itself. if I create a new session and connect to it from ITerm while the first session is failing, pastes work fine there.

**Comment by nicm** [comment]
It doesn't sound like the same thing at all. \e[200~ and \e[201~ are the start and end of bracketed paste mode. Sounds like something inside tmux is leaving it on when it exits. Try running printf "\033[?2004l" in all your windows.

**Comment by nicm** [comment]
Is this still a problem?

**Comment by narayandesai** [comment]
I haven't seen my paste problem in the last few days, but i haven't been at the command line as much the last week. I'll try running that printf the next time it happens. What should I expect to see?

**Comment by nicm** [comment]
You should expect the problem to go away.

**Comment by askedrelic** [comment]
I have gotten in this incorrect pasting state again and tried running printf "\033[?2004l" in all windows, but there was no effect and pasting would still swap letters.

**Comment by nicm** [comment]
It won't make any difference for you if you are not seeing 00~ appear when you paste, that is a different problem. But with your problem: if you detach your tmux in iTerm2 and attach the same tmux in Terminal.app or xterm, does the problem still remain when you paste into them?

**Comment by narayandesai** [comment]
To follow up, when seeing the 00~ problem, printf "\033[?2004l" does the trick. cut and paste works properly after that, though i need to run it in each window for cut and paste to be fully fixed.

**Comment by wilywampa** [comment]
The culprit is almost definitely tmux-copycat. It binds n, q, and y in the root table (i.e. intercepts them without needing prefix)  and I noticed sometimes it doesn't clear those bindings. As a result, pressing those keys takes longer than other keys because they run a shell script resulting in what you described. I haven't had time to figure out why the bindings aren't being cleared yet.

**Comment by askedrelic** [comment]
Hmm I was hoping it wasn't a plugin, good find @wilywampa 
I will file a ticket with that project. I guess I will close this issue, since this doesn't appear to be a tmux core problem.

**Comment by phodge** [comment]
You can also get this sort of behaviour by binding the `M-[` key sequence:

    # this will stop you pasting into your tmux session with
    bind-key -n M-[ command-prompt -p "New Session,New Window" "new-session -n '%2' -s '%1'"

*Pro Tip*: don't do this.
