### ISSUE TITLE
Is prohibiting epoll is still necessary?

### ISSUE THREAD

**Issue by azat** [tmux/tmux#3622]
I don't see any polling of `/dev/null` in the code, does this still actual?

https://github.com/tmux/tmux/blob/1a11c972aed11c1996d732f15ad16f02c668b5a0/osdep-linux.c#L96-L97

**Comment by nicm** [comment]
Yes it is, stdin, stdout or stderr of the client could be /dev/null.

**Comment by nicm** [comment]
For example you  can probably try something like these:
~~~~
tmux lsk >/dev/null
tmux setb x \; saveb /dev/null
~~~~

**Comment by azat** [comment]
But does poll required for this? The same way you can redirect to a regular file which is not pollable (in any polling mechanism)

**Comment by nicm** [comment]
Unless they have fixed it, you cannot use epoll on a /dev/null file descriptor in Linux. tmux needs to do this if the user wants to write to /dev/null because it uses libevent for there file descriptors.

**Comment by azat** [comment]
It does not work with /dev/null you are right, and by some reason I thought that poll does not work for regular files, but it does. Closing.

**Comment by nicm** [comment]
> some reason I thought that poll does not work for regular files

You may be thinking of macOS where kqueue (and so also poll since they are the same) only works on sockets (unless they have fixed it).
