### ISSUE TITLE
tmux -D (serverless mode) seems broken?

### ISSUE THREAD

**Issue by azat** [tmux/tmux#3624]
### Issue description

Right now if you will run `tmux -D` is simply hangs

### Required information

Please provide the following information:

* tmux version (`tmux -V`) - `tmux 3.3a` and 1a11c972
* Platform (`uname -sp`) - `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`). - `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
It does not hang, the server is running. What do you expect it to do?

**Comment by nicm** [comment]
`-D` means the server doesn't run as a daemon, not that it doesn't run at all :-).

**Comment by azat** [comment]
So usually tmux has two processes: client and server.

What I was expecting from this flag is that tmux can operate with server and client in one process.
Since it is useful for debugging.

But I guess I was wrong, and this is just spawns server only, and if you need client, then you should spawn it by yourself.

**Comment by nicm** [comment]
Correct, but it is still useful for debugging because you do not need to attach gdb to the server process separately, you can run the server in it directly.
