### ISSUE TITLE
tmux exited

### ISSUE THREAD

**Issue by PREM1980** [tmux/tmux#3625]
### Issue description

I have installed tmux on top of docker.io/library/ubuntu:20.04 using dockerfile.

RUN apt-get -qq update && apt-get upgrade -qy &&  tmux

It works fine when I run the docker container as root - docker run -it tmux-image sh(whoami-root)

But, when I run the same container in k8s(we have a restriction to run the container using a specific user id(1999)). I tmux gets exited.

$ tmux    
[exited]
$ ^[[?1;2c

I believe this is more an issue with running the image using different user id. Should I install tmux in a different way? I checked the permission of tmux bin and it looks good.

$ cd /usr/bin
$ ls -al tmux
-rwxr-xr-x. 1 root root 692192 Jan 31 13:55 tmux

### Required information

Please provide the following information:

* tmux version (`tmux -V`). - tmux 3.0a
* Platform (`uname -sp`). - Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`) -TERM
* Logs from tmux (`tmux kill-server; tmux -vv new`). - no server running on /tmp/tmux-1000650000/default

**Comment by nicm** [comment]
Show tmux logs please.
