### ISSUE TITLE
Underline is black when underline color is unspecified

### ISSUE THREAD

**Issue by serban** [tmux/tmux#3627]
## Environment

| Terminal | Version     | $TERM Outside  | $TERM Inside  |
|----------|-------------|----------------|---------------|
| iTerm2   | 3.5.0beta10 | xterm-256color | tmux-256color |
| Kitty    | 0.29.0      | xterm-kitty    | tmux-256color |

| Software | Version                     |
|----------|-----------------------------|
| macOS    | Ventura 13.4.1              |
| Debian   | testing                     |
| fish     | 3.6.1                       |
| vim      | 9.0.1650                    |
| tmux     | 80d4f4af from June 26, 2023 |

Reproducible on both macOS Ventura and Debian testing.

## Problem

Commit ff8882a24f44594c871ad849f885bcd895836e73 from June 26 broke underline colors for me in both iTerm2 and Kitty (in the pane / pseudo terminal area, not the status line). Before, underlined text without a specified underline color would have the same foreground color as the text. After, the underline appears black. This is true for Fish, for Vim, and also for the simple examples below.

## Reproduce

Run the following to observe the behavior. The expected result is that the underline has the same foreground color as the text. The observed behavior is that the underline is black:

```fish
printf '\033[4mLorem Ipsum\033[0m\n'
```

The problem is more pronounced when there is a foreground color set. Here the expected result is that both the text and the underline are red. The observed behavior is that the text is red and the underline is black:

```fish
printf '\033[31m\033[4mLorem Ipsum\033[0m\n'
```

There is no problem when both the foreground and underline colors are set. The expected and observed behavior is that the text is red and the underline is also red:

```fish
printf '\033[31m\033[4m\033[58;5;1mLorem Ipsum\033[0m\n'
```

## Observed Behavior

I compared the behavior between ffe2410639b1f9d5ba40a2df9f4f8df976b1617d just before the underline change and 80d4f4afc69fcd0699bfec49b55fc846e97dcc97 just after.

### Outside tmux

<img width="713" alt="iTerm2" src="https://github.com/tmux/tmux/assets/382656/92728d8f-f482-45b9-8a38-420e60f39d7f">

### Inside tmux · Before (ffe24106)

<img width="713" alt="iTerm2-ffe24106" src="https://github.com/tmux/tmux/assets/382656/e1ee0dbb-b4e0-4bf9-9bb2-a026390a21f6">

### Inside tmux · After (80d4f4af)

<img width="713" alt="iTerm2-80d4f4af" src="https://github.com/tmux/tmux/assets/382656/2bcd2551-7836-4903-a22f-cebe4385f23f">

## Related

I did see https://github.com/tmux/tmux/issues/3609 ⟨Underline colors not working⟩, but since I didn't have trouble with underline colors before, I figured I wouldn't mess with `terminal-features` just yet.

I can generate tmux logs if you really need them. Thanks!

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/12011684/x.diff.txt)

**Comment by nicm** [comment]
Did you restart tmux entirely?

Please show tmux server log.

**Comment by serban** [comment]
Yup, I did restart tmux completely. Logs below.


* [tmux-server-13049.log](https://github.com/tmux/tmux/files/12021805/tmux-server-13049.log)
* [tmux-client-13047.log](https://github.com/tmux/tmux/files/12021807/tmux-client-13047.log)
* [tmux-out-13049.log](https://github.com/tmux/tmux/files/12021808/tmux-out-13049.log)

Steps executed:

```fish
tmux -vv -f /dev/null new-session -s patch
```

```fish
printf '\033[4mLorem Ipsum\033[0m\n'
```

```fish
printf '\033[31m\033[4mLorem Ipsum\033[0m\n'
```

**Comment by nicm** [comment]
I confused things by using 0 to mean default underline when I wrote it rather than 8 like the other colours, please try this: [y.diff.txt](https://github.com/tmux/tmux/files/12027931/y.diff.txt)

**Comment by serban** [comment]
No worries. 🙂

Patch `y.diff.txt` gets us in the right direction, but it rewrites the ANSI colors as RGB values. Examining `tmux-out.log`:

```fish
printf '\033[31m\033[4m\033[58;5;1mLorem Ipsum\033[0m\n'
```

produces:

```
\033[31m\033[58:2:128:0:0m\033[4mLorem Ipsum
```

The text and the underline end up being different shades of red since my terminal's ANSI color palette is different from the default. From https://github.com/tmux/tmux/issues/1492#issuecomment-427815410, I see that for underline styles we have to encode the color as an 8-bit value or a 24-bit value. Can we map from ANSI to an 8-bit value between 0 and 15 instead?

## Expected Output

<img width="1662" alt="iTerm2-underline-colors" src="https://github.com/tmux/tmux/assets/382656/d3334086-f0e2-46dc-ade1-655c8150f4db">

## Observed Output

<img width="1662" alt="tmux-underline-colors-rgb" src="https://github.com/tmux/tmux/assets/382656/18f35847-cf52-40d6-91f4-b8f9be108e54">

↑ Note the color changes.

**Comment by nicm** [comment]
I've applied this now since it fixes the original problem.

Unfortunately `setal` (and `Setulc` which is the same) does not support setting colours from the 256 colour palette, only RGB colours, so tmux does not either. We would need to modify it or add an additional capability for that, which we could do, I might look at it at some point.

**Comment by nicm** [comment]
Non-RGB colours should work now, it should be in GitHub later today. You'll need to make sure tmux adds the `usstyle` feature for your terminal, check `tmux display -p '#{client_termfeatures}'` inside tmux. If it is not present, try `set -as terminal-features '*:usstyle'`. Please let me know of any problems.
