### ISSUE TITLE
#{mouse_word} is blank from status bar click

### ISSUE THREAD

**Issue by faustind** [tmux/tmux#3628]
### Issue description

This is almost a feature request:

I would like to access  #{mouse_word} from clicks in the status bar.

I have the following use case: I show the list of sessions in the status bar and I would like to attach to a different session by clicking on it.

I saw #2913 and could confirm that #{mouse_x} and #{mouse_y} are set, but #{mouse_word} remains blank. Here is a minimal tmux.conf

```tmux
# start with mouse mode enabled
set -g mouse on

set -g status-keys vi
set -g mode-keys vi

# add second line to status line
set -g status 2 
# format of second line: list of active sessions
set -g status-format[1] '#[align=centre]#{S:#{session_name} }'

# click on a session in the list to switch to it 
bind -Troot MouseUp1StatusDefault if -F '#{mouse_word}' {
    run-shell "tmux attach-session -t #{mouse_word}"
} { display -F 'mouse word: #{mouse_word} x: #{mouse_x} y: #{mouse_y}'}
```

My specific use case may be unpopular but I believe the 
ability to reference the #{mouse_word} from the status bar could enable more customizations.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  `tmux 3.3a`
   I also tried with c8494df

* Platform (`uname -sp`).
  `Linux x86_64`

* $TERM inside and outside of tmux (`echo $TERM`).
  Inside: `tmux-256color`
  Outside: `xterm-256color`

* Logs from tmux (`tmux kill-server; tmux -vv new`).
  [tmux-client-264627.log](https://github.com/tmux/tmux/files/12029491/tmux-client-264627.log)
  [tmux-out-264629.log](https://github.com/tmux/tmux/files/12029492/tmux-out-264629.log)
  [tmux-server-264629.log](https://github.com/tmux/tmux/files/12029494/tmux-server-264629.log)

**Comment by nicm** [comment]
I'm closing this since we do not need an issue and a PR.
