### ISSUE TITLE
Extended keys stop working after reset(1)

### ISSUE THREAD

**Issue by yut23** [tmux/tmux#3629]
### Issue description

With `extended-keys` set to `always`, tmux stops forwarding extended key sequences to a pane after *reset(1)* is run in that pane. It still works normally in all other panes.

Minimal tmux.conf:
```
set -s extended-keys always
```

Steps to reproduce in *xterm(1)* with `modifyOtherKeys` enabled:
1. Run *cat(1)* then press `C-Tab`, `^[[9;5u` will be printed.
2. Run *reset(1)*.
3. Run *cat(1)* then press `C-Tab`, a tab character will be printed instead of `^[[9;5u`.

### Required information

* tmux version (`tmux -V`): git master ([828efc7](https://github.com/tmux/tmux/commit/828efc7bcf721049c85f108a9cebe798079cbd06))
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color` inside, `xterm-256color` outside
<details><summary>Relevant section of the server log</summary>
<p>
<pre>
1689268074.138399 input_parse_buffer: %0 ground, 17 bytes: \033c\033[?1000l\033[?25h\r
1689268074.138411 input_esc_dispatch: 'c', 
1689268074.138423 screen_write_collect_flush: flushed 0 items (screen_write_scrollregion)
1689268074.138451 /dev/pts/3: \033[1;23r
1689268074.138495 tty_clear_area: /dev/pts/3, 80,23 at 0,0
1689268074.138506 /dev/pts/3: \033[23S
1689268074.138522 screen_write_collect_flush: flushed 0 items (screen_write_fullredraw)
1689268074.138535 input_csi_dispatch: 'l' "?" "1000"
1689268074.138545 parameter 0: number 1000
1689268074.138557 screen_write_mode_clear: MOUSE_STANDARD,MOUSE_BUTTON,MOUSE_ALL
1689268074.138568 input_csi_dispatch: 'h' "?" "25"
1689268074.138576 parameter 0: number 25
1689268074.138585 screen_write_mode_set: CURSOR
1689268074.138594 input_c0_dispatch: '\r'
1689268074.138604 screen_write_collect_flush: flushed 0 items (screen_write_stop)
1689268074.138616 cmdq_next <global>: empty
1689268074.138626 cmdq_next </dev/pts/3>: empty
1689268074.138635 /dev/pts/3: redraw deferred (12 left)
1689268074.138643 redraw timer started
1689268074.138652 /dev/pts/3: pane %0 needs redraw
1689268074.138662 server_client_reset_state: client /dev/pts/3 mode CURSOR,WRAP
1689268074.138672 /dev/pts/3: \033[1;1H
1689268074.138687 /dev/pts/3: \033[1;24r
1689268074.138702 server_client_reset_state: cursor to 0,0
1689268074.138711 /dev/pts/3: \033[1;1H
1689268074.138727 /dev/pts/3: \033[?12l\033[?25h
1689268074.138742 /dev/pts/3: \033[6 q
1689268074.138757 /dev/pts/3: current mode CURSOR,WRAP,CURSOR_BLINKING,KEXTENDED
1689268074.138766 /dev/pts/3: setting mode CURSOR,WRAP
</pre>
</p>
</details>

**Comment by nicm** [comment]
Does this fix it?
~~~~
Index: screen-write.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/screen-write.c,v
retrieving revision 1.214
diff -u -p -r1.214 screen-write.c
--- screen-write.c      27 Mar 2023 08:31:32 -0000      1.214
+++ screen-write.c      13 Jul 2023 19:52:58 -0000
@@ -326,7 +326,9 @@ screen_write_reset(struct screen_write_c
        screen_reset_tabs(s);
        screen_write_scrollregion(ctx, 0, screen_size_y(s) - 1);

-       s->mode = MODE_CURSOR | MODE_WRAP;
+       s->mode = MODE_CURSOR|MODE_WRAP;
+       if (options_get_number(global_options, "extended-keys") == 2)
+               s->mode |= MODE_KEXTENDED;

        screen_write_clearscreen(ctx, 8);
        screen_write_set_cursor(ctx, 0, 0);

**Comment by yut23** [comment]
Yes, I'd already tracked it down to that locally. Thanks for the fast response!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
