### ISSUE TITLE
The relationship between `new-session`'s `-s session-name` and `attach-session`'s `-t target-session` is insufficiently documented

### ISSUE THREAD

**Issue by VPanteleev-S7** [tmux/tmux#3632]
Hi and thank you again for tmux. I ran into some confusion setting something up; I hope some clarification in the documentation will help avoid it in the future.

1. It is not clear that `session-name` in `new-session`'s documentation refers to the same thing as `target-session` in `attach-session` (and others). One must infer that the identifier accepted by `-t` is the session name; however, the word "name" doesn't even appear anywhere in `attach-session`'s description in the man page.

2. The syntax accepted by the two switches seems to be different. It seems that `.` is a special character conferring additional meaning, however, this is only true for `attach-session`. When `new-session` is used with `-s` with a string containing `.`, it appears to work without issue. However, trying to use the same string with `attach-session` got me "can't find window" / "can't find pane" errors (exact wording may be slightly different).

Hope this helps.

**Comment by nicm** [comment]
There is a large section which describes targets in the man page (under `COMMANDS`), which includes this text:
~~~~
     target-session is tried as, in order:

           1.   A session ID prefixed with a $.

           2.   An exact name of a session (as listed by the list-sessions
                command).

           3.   The start of a session name, for example ‘mysess’ would match
                a session named ‘mysession’.

           4.   An fnmatch(3) pattern which is matched against the session
                name.

**Comment by VPanteleev-S7** [comment]
Okay, but it would be nice if there was a way to discover that section without requiring that the user read the entire man page top-to-bottom.
