### ISSUE TITLE
Get output of command from window started by shortcut, that itself creates panes.

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#3633]
* tmux version (`tmux -V`) : tmux 3.2a
* Platform (`uname -sp`) : Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color

I install a binding that runs a command and inserts it's output in the application I'm in. The code below works fine and I get the text in my terminal or vim.

binding:
tmux bind -n C-g bind -n C-h popup -w 80% -h 80% -E -d $PWD "./tmux-insert"

tmux-insert:
buffer=`fd --color always | fzf -m --ansi --cycle` #command 
[[ "$buffer" ]] && { tmux set-buffer "$buffer" ; tmux paste-buffer ; }

If the command itself creates panes things awry, and I have to kill everything.

I tried use run-shell with no success.

I try to run the command in a new-window, it gives better result, the application run normally but I get no results back,  I guess that they are pasted in the window that closes after the application exits.

binding:
tmux bind -n C-g bind -n C-f new-window "cd $PWD ; ./tmux-wait-ftl"

tmux-wait:
buffer=`ftll` # a command that creates panes
[[ "$buffer" ]] && { tmux set-buffer "$buffer" ; tmux paste-buffer ; }

Is there a way to achieve the result I want?

Also, is there a better way to bind a double key command?

**Comment by nicm** [comment]
There is an example of binding sequences of keys here https://man.openbsd.org/OpenBSD-current/man1/tmux.1#switch-client.

The other thing you are trying to do is completely unclear so I have no idea what result you want.

**Comment by nkh** [comment]
I want to:

-register some bindings
- when the binding is used
    - a program is started
         - the program uses tmux to create panes
    - when the program ends it outputs data on stdout
    - I want to capture that output
- I want to insert the captured output in the window where I was when I used the binding

The first example I gave works but not when the called program creates panes

**Comment by nicm** [comment]
Have the application pipe to `tmux loadb -` then paste the buffer?

**Comment by nkh** [comment]
I've come a bit further.

binding:
```
tmux bind -n C-q new-window -c "$PWD" "./tmux_ftll" \\\; wait-for ftll_out \\\; paste-buffer
```

./tmux_Ftll:
```
#!/bin/bash
buffer="$(application_that_opens_panes)" 

tmux set-buffer "$buffer" 
tmux wait-for -S ftll_out
```

The problem I have is that **application_that_opens_panes** blocks waiting for *ftll_out*, when I want it to generate that signal when done so the pane where I used the shortcut would paste the buffer. I could check that by sending the signal in another window.

**Comment by nkh** [comment]
Hi, finally got it to run as I want, i made a diagram of the solution

```
                                     .--------------.
.---------------.                    |  temporary   |
|    current    |   .------------.   |    window    |   .-----------.
|    window     |   |  binding   |   |--------------|   |    ftl    |
|---------------|   |------------|   | run ftl -------->|-----.-----.
| *use binding* |-->| save id    |-->| get text<--------| P   | P   |
|               |   | run script |   |              |   |     |     |
| ^             |   '------------'   | get id       |   '-----'-----'
'-|-------------'                    | set buffet   |
  |                                  '------|-------'
  |                                         v
  |                                    .--------.
  '------------------------------------| buffer |
                                       '--------'
```


```
# tmux bind -Ttable_ctl_g C-g run "tmux display -p '#{pane_id}'>/tmp/tmux_ftll_destination_pane" \\; new-window -c "$PWD" "./tmux_ftll"
```

```bash
P=$(mktemp -u) 
tmux new-window -n tmux_ftll "ftl 3>$P ; tmux wait -S ftll_$$" 
tmux wait ftll_$$

buffer="$(<$P quote_lines | remove_nl ' ')"
rm $P

destination_pane="$(</tmp/tmux_ftll_destination_pane)"
[[ "$buffer" ]] && { tmux set-buffer -t $destination_pane "$buffer" ; tmux paste-buffer -t $destination_pane ; }

```

ftl, to simplify, is an application that has two panes and returns some text

I needed an in-between window becaus eI can't just us run-shell, which may not provide a pty as it's non interactive; nor could I use popup, to make thing happen I had to save the start-window id in the the binding so the script could use it.

the idea  came to me while looking at https://github.com/junegunn/fzf-git.sh
