### ISSUE TITLE
Automatic-rename-format not working as expected

### ISSUE THREAD

**Issue by hqkhan** [tmux/tmux#3635]
### Issue description

Hello. I'm having difficulties dealing with running a shell script using `automatic-rename-format` for my pane name updates. 

This is a bit of an inquiry about an issue that I'm having with a plugin called [tmux-nerd-font-window-name](https://github.com/joshmedeski/tmux-nerd-font-window-name). It replaces the pane's name with a nerd font icon associated with the running command. 

Here's the meat basically:

```
get_icon() {
	case $NAME in
	tmux)
		echo ""
		;;
	htop | top)
		echo ""
		;;
```

It's a shell script that matches cases and outputs an icon. 

Here's the tmux bit:

```
tmux set-option -g automatic-rename-format "#($CURRENT_DIR/bin/tmux-nerd-font-window-name #{pane_current_command})"
```

The problem I'm running into is that the name of the window only updates based on keypress instead of auto updating by itself based on status-interval. I have status-interval set like so:

```
set -g status-interval 1      # update status every 1 seconds
```

Normally, the name will update automatically based on w/e command is being ran but this fails. Here's a video of the issue:

https://github.com/tmux/tmux/assets/22674069/fc5406c9-7c8b-44ab-81c0-59c6f953c521

When I ran sleep, it updated at the end of the `sleep` command and the name of the command doesn't change until I press a key. 

I took some time and read [man tmux](https://man7.org/linux/man-pages/man1/tmux.1.html). Specifically the [FORMATS](https://man7.org/linux/man-pages/man1/tmux.1.html#FORMATS) section. Here's the important bit I'd like to confirm:

> In addition, the last line of a shell command's output may be
     inserted using ‘#()’.  For example, ‘#(uptime)’ will insert the
     system's uptime.  When constructing formats, tmux does not wait for
     ‘#()’ commands to finish; instead, the previous result from running
     the same command is used, or a placeholder if the command has not
     been run before.  If the command hasn't exited, the most recent
     line of output will be used, but the status line will not be
     updated more than once a second.  Commands are executed using
     /bin/sh and with the tmux global environment set (see the GLOBAL
     AND SESSION ENVIRONMENT section).

To me, it looks like there's some timing issue going on where tmux runs the script but doesn't wait for the result? 

So, instead of using a bash script, I moved to emulating the same thing that the bash script is doing but using tmux's grammar instead. This led to a prototype:

```
set-option -g automatic-rename-format "#{?#{==:#{pane_current_command},nvim},,\#{?#{==:#{pane_current_command},bash}\,\,#{pane_current_command}}}"
```

The above works great. As in, the names of the window changes based on the current command and updates accordingly. So, does this mean that I have to turn the bash script into a giant nested set of if statements to get what I want? Is there a better way?

What I've said was also described in [my own issue from the plugin's repo](https://github.com/joshmedeski/tmux-nerd-font-window-name/issues/9)

### Required information

* tmux version (`tmux -V`):  `tmux.orig 3.3a`
* Platform (`uname -sp`): `Linux x86_64`
* $TERM inside: `screen-256color`
* $TERM outside: `xterm-256color`

**Comment by nicm** [comment]
Automatic rename does not happen when the status line is updated, it is triggered if the active pane content has changed and at most every half a second. `#()` completing will not trigger an update so it will wait for the next time the active pane changes.

**Comment by hqkhan** [comment]
Oh, I see. I understand the behavior now. That's why the last ran command stays to be the name of the pane until key-press since there's no change since last ran command. 

So, by using tmux's grammar for creating a format, I'm still updating the name every half a second at most BUT it is no longer bounded by `#()` and will trigger an update instead of waiting for a change?

**Comment by nicm** [comment]
The status line will trigger a follow on update when `#()` completes but `automatic-rename` will not so anything that does not evaluate immediately has to wait for the next update.

**Comment by nicm** [comment]
No if you don't use #() then the format will be entirely evaluated before the name is set.

**Comment by hqkhan** [comment]
Got it. I'm following now. Thank you for the information. Since original question has been answered. I am closing the issue.
