### ISSUE TITLE
reproducible tmux freeze on openbsd-current amd64

### ISSUE THREAD

**Issue by bsdmp** [tmux/tmux#3637]
tmux openbsd-7.3 (current kernel #1294 from Jul 18)
OpenBSD amd64
xterm-256color inside and outside tmux

```
$ cat ~/.tmux.conf
set -g renumber-windows on
```

steps to repeat:
$ tmux
C-b c
C-b c
C-d
C-d
C-b c
C-b c
C-d
<tmux freezes and slowly starts eating 100% cpu>

**Comment by nicm** [comment]
This may be fixed by session.c r1.94.
