### ISSUE TITLE
Question: dynamic variables?

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#3640]
I have this scenario: 

I've got two binds F8 and F9 which cycle through next pane and previous pane and if the pane is already zoomed, it will preserve zooming. So, if already zoomed its going to change the pane and zoom it again, turning panes into "windows", very handy for small screen use or using tmux on a server from a tmux pane itself. 

```
bind -n F9 if -F '#{==:#{pane_current_command},ssh}' {send-keys F9} {if -F '#{window_zoomed_flag}' {selectp -t:.+; resizep -Z} {selectp -t:.+}}

bind -n F8 if -F '#{==:#{pane_current_command},ssh}' {send-keys F8} {if -F '#{window_zoomed_flag}' {selectp -t:.-; resizep -Z} {selectp -t:.-}}
```

As you can see i am letting this pass through the key if the command is `ssh`. This favors the second use case (controlling tmux over ssh). However I am finding a use case where sometimes I have multiple machines open and I dumped out the same config file on both and I'm trying to do a quick and dirty visual diff between them and the full screen f8/f9 pane swap would be perfect for this. However, this goes against my ssh checking logic there.  (Yes I recognize I can simply break the other pane out into a new window and do the same job there... just humor me for a sec)

So my thought is it would be sweet if we could have global tmux dynamic variables that we can set from bindings or commands so that I can for example toggle the behavior. During this session i would like to use an alternative binding which does not carve out ssh commands. 

Failing this ability I suppose the next best thing (which is nearly as good) is to just keep a auxiliary tmux config files around to remap the keys in question. that would be a fine way to maintain separate "modes".

**Comment by nicm** [comment]
I'm not sure what you are asking for.

There is nothing stopping you changing key bindings from other bindings.

Or using a global user option and checking it in your key binding to decide what to do.

Or you could use different keys.

**Comment by unphased** [comment]
Thanks. user option seems to answer my original question really, but in the course of asking the question what happened was I figured out that my need is also met by changing the bindings!

I know we can perform logic in binds off of options, I already rely on this, so since user options sound like options that I get to set arbitrarily then that is exactly what I asked for. Thanks
