### ISSUE TITLE
Moving cursor to a specific (X, Y) coordinate

### ISSUE THREAD

**Issue by hqkhan** [tmux/tmux#3642]
### Issue description

Hello. I wanted to ask if there is a way to move the cursor to a specific X Y location? I looked at the [man tmux](https://man7.org/linux/man-pages/man1/tmux.1.html) for tmux but could not find something like this to move the cursor to a location. My goal is to move the cursor to `copy_cursor_y` specifically and do something else after. I realize that I can do something like:

```
send -X -N 5 cursor-up
```

I'd have to do the math to figure out how much to jump by. I was wondering if there's an easy thing that takes in coordinates. 

### Required information

* tmux version (`tmux -V`):  `tmux.orig 3.3a`
* Platform (`uname -sp`): `Linux x86_64`
* $TERM inside: `screen-256color`
* $TERM outside: `xterm-256color`

**Comment by hqkhan** [comment]
I tried a few more things. 

```
  send -X -N "#{e|-:#{copy_cursor_y},#{mouse_y}}" cursor-up
  display-message "#{e|-:#{copy_cursor_y},#{mouse_y}}"
```

The display works but the cursor does not move. It cannot take the `#` syntax after `-N`.

Also tried:

```
  set -pq @FOO #{e|-:#{copy_cursor_y},#{mouse_y}}
  display-message "#{@FOO}"
```

This doesn't work either. `@FOO` is empty.

**Comment by krader1961** [comment]
Have you tried `tput cup $x $y`?

**Comment by hqkhan** [comment]
I hadn't tried `tput cup`. I just gave it a shot and it's not working as I thought. It does move the cursor but causes the screen to be messed up and subsequent commands start overlapping with what's already on terminal.

**Comment by hqkhan** [comment]
I was thinking that since tmux already has the cursor info AND it can also do arithmetic based on these variables, it would be simple to use them in commands such as `cursor-up` but that doesn't seem to be the case.

**Comment by nicm** [comment]
Wrap your `send -X` in `run -C` to expand formats.

Or use quotes and `-F` with `set`.

**Comment by hqkhan** [comment]
Thank you @nicm, that worked in that I'm able to get the right value now. 

There's something that I don't understand about the behavior. I've attached a video of what I'm seeing. 

https://github.com/tmux/tmux/assets/22674069/3a861317-3289-49b3-9b55-53bd76bde5c6

I have a bind that moves the cursor down. I don't have any other binds using `Mouse`. The rest are defaults. When I press `M-MouseDown1Pane`, it'll apply the `cursor-down` from `mouse_y` as opposed to `copy_cursor_y` it seems. 

I'm trying to get the cursor at the Y position of mouse. 

I added `cursor-up` to get to mouse position but it seemed to only apply the last `cursor` command instead. It seems that `MouseDown1Pane` moves the cursor behind the scenes? I'm not sure why doing double cursor command didn't work...

**Comment by hqkhan** [comment]
By issuing `MouseDown1`, it changes the `copy_cursor` position to mouse position. Is there a way to disable this? I want to control the cursor position myself but the positions keep messing with what I want to accomplish.

Here's another video of what I'm seeing.

https://github.com/tmux/tmux/assets/22674069/ee95d0f3-eeea-4347-9ccc-b5766b3448fb

Bind: `M-MouseDown1Pane`. For some reason, when I issue `search-again`, the cursor moves back normally. But when a cursor command or `begin-selection` is added into the mix, the selection will start from `mouse` position. 

This seems to me that there's some inconsistency with `copy_cursor` position vs `cursor` position. I haven't looked into the code to confirm this mainly because I'm not entirely sure where to look.

**Comment by topcat001** [comment]
If the mouse was active at the time when a copy-mode command is issued, then the copy-mode cursor is moved to the mouse position. You can see this here: https://github.com/tmux/tmux/blob/fda393773485c7c9236e4cf0c18668ab809d2574/window-copy.c#L3006
In many cases this behaviour is convenient. I don't think it can be disabled by the user. In particular, the cursor is being reset at the start of each `cursor-up` command in your binding.

**Comment by hqkhan** [comment]
Thank you for that. Hmm, so I guess it's not possible to do what I want without modifying that line and risk breaking other features?

**Comment by topcat001** [comment]
Maybe you're looking for a copy-mode no-op to set the cursor's initial position? How about this?
```
bind -n M-MouseDown1Pane { send -X rectangle-toggle; send -X rectangle-toggle; }
```
Then issue subsequent cursor commands separately, say using a keyboard shortcut. Then the cursor won't reset.

**Comment by hqkhan** [comment]
I see! That makes sense. That'll work for sure. I already had a keybind that does what I want. I was hoping to invoke it at the end of this `M-MouseDown1Pane`. For example, I have a bind for `C-F`. I was hoping to do `send-keys -X C-F` at the end of the function above but it doesn't invoke the bind associated with tmux. I guess its a way to avoid recursive behavior...

**Comment by hqkhan** [comment]
Ok, I more or less got what I wanted to do with your no-op recommendation. Works great! Thank you very much @topcat001
