### ISSUE TITLE
Custom pane-border-indicators

### ISSUE THREAD

**Issue by amanvm** [tmux/tmux#3643]
### Issue description

Hi, the utf arrow characters used by tmux for pane-border-indicators are double width and they overlap with the first character of the pane to its right/left. It would be nice to be able to set them to custom glyphs.

<img width="173" alt="Screenshot 2023-07-21 at 3 38 11 PM" src="https://github.com/tmux/tmux/assets/25681815/6cbc06c8-edc0-4f70-b6b2-3306f1d12923">

### Required information

Please provide the following information:

* tmux version (next-3.4).
* Platform (n/a).
* $TERM inside and outside of tmux (n/a).
* Logs from tmux (n/a).

**Comment by ThomasDickey** [comment]
platform isn't "n/a" because those are classified as "ambiguous width" (on some platforms, those are single-width, while on others they're double-width).

**Comment by amanvm** [comment]
@ThomasDickey I see, here it is ``$uname -sp`` gives ``Darwin arm``. Some additional information: 1) TERM: ``xterm-256color`` outside tmux, ``tmux-256color`` inside tmux. 2) terminal emulator is iTerm2 on macOS Ventura 13.4.1.

**Comment by ThomasDickey** [comment]
iTerm2 might be doing this based either on locale or font.  On my machine, I see U+2192 printing as a single column (using either iTerm2 3.4/3.5)

**Comment by nicm** [comment]
They are single width for me with iTerm2.

You could try `set -as terminal-overrides ",*:U8=0"` to make tmux use ACS line drawing instead of UTF-8 characters, but I'm not sure arrows are well supported...
