### ISSUE TITLE
pane-border-indicators at every intersection of active pane's length/width

### ISSUE THREAD

**Issue by amanvm** [tmux/tmux#3644]
### Issue description

I like pane-border-indicators over border coloring, thanks for the feature. One way it can be more useful is if it shown at every intersection of active pane's length and width.

In the image below, pane1 -- the full height pane to the left -- is active. But the arrow is only shown at the top, where pane1 intersects with pane2. It would be nice if it is also shown at the intersection of pane1 and other panes. Particularly in the absence of color, it is hard to use as a visual cue otherwise. 

The proposal is to add an indicator at every intersection of active pane with it's neighbors.

<img width="951" alt="Screenshot 2023-07-21 at 3 44 56 PM" src="https://github.com/tmux/tmux/assets/25681815/5bf1c9db-36cc-49a9-9c84-e0dd3a273d5e">

### Required information

Please provide the following information:

* tmux version (next-3.4).
* Platform (n/a).
* $TERM inside and outside of tmux (n/a).
* Logs from tmux (n/a).

**Comment by nicm** [comment]
I think we have enough options for this TBH, but if you want to add it and make a PR then that's OK. Feel free to ask questions here if you need to.
