### ISSUE TITLE
External clipboard stopped working after updating my machine

### ISSUE THREAD

**Issue by blueray453** [tmux/tmux#3646]
### Issue description

I have checked https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

My clipboard stopped working after updating my machine. I did not change anything in the config file for about 2/3 months. It was working.

### Required information

Please provide the following information:

![command_output](https://github.com/tmux/tmux/assets/855297/1a746def-fbfe-4503-aa43-89adba8c494e)

I am using debian sid / unstable.

Here are the log files:

[tmux-client-6984.log](https://github.com/tmux/tmux/files/12175594/tmux-client-6984.log)
[tmux-out-6987.log](https://github.com/tmux/tmux/files/12175595/tmux-out-6987.log)
[tmux-server-6987.log](https://github.com/tmux/tmux/files/12175596/tmux-server-6987.log)

Here is my minimum config.

```
# Fix Color Issues
set-option -g default-terminal "tmux-256color"
set-option -ag terminal-overrides ",alacritty:Tc"

# Clipboard
set-option -as terminal-features ',alacritty:clipboard'

set-option -s set-clipboard external

# Mouse mode
set-option -g mouse on

# `Ctrl+c` to Copy
bind-key -T copy-mode C-c send-keys -X copy-pipe-and-cancel
```
![tmux-info](https://github.com/tmux/tmux/assets/855297/dd4046df-a968-412b-84c9-7e7cf5a23697)

**Comment by krader1961** [comment]
Do not use screen grabs for purely textual information. Copy/paste the text.

**Comment by blueray453** [comment]
I have vision impairment. I can not copy from clipboard so made screenshot.

**Comment by blueray453** [comment]
Teserract output, might be a little different
....
$ uname -sp && tmux -V && echo $TERM
Linux unknown

tmux 3.3a

tmux-256color

$ tmux info|grep Ms:
192: Ms: (string) \033]52;%pl%s ;%p2%s\a
```

**Comment by Artanicus** [comment]
After a lot of hair pulling, I did land on at least a work around to this new behaviour in 3.3a.

In addition to `set -g set-clipboard on` I now also need to specify `set -g allow-passthrough on`.

What lead me to try it is this comment: https://github.com/tmux/tmux/issues/3218#issuecomment-1153404631 .. So it would seem that change made all OSCs explicitly opt-in, even if another option such as `set-clipboard` should perhaps imply it's wanted.

**Comment by nicm** [comment]
You do not need `allow-passthrough` for `set-clipboard` to work.

This log shows `xsel -i` being run which is not included in your example config.

It also shows this:
~~~~
1690392089.853812 could not expand Ms
~~~~
Probably you have an ncurses version which is after the strict `tparm` checks were added but before the addition of `tiparm_s`. Please upgrade to at least ncurses-6.4-20230424.

**Comment by Artanicus** [comment]
In my (very similar) case it definitely fixes the issue though at least as a workaround. libncurses6 is sitting at 6.4.20221231, so that may indeed be the actual thing to fix, which I'm not in a position to fix.

```shell
%> uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 3.3a
xterm-kitty
%> tmux info|grep Ms:                
 192: Ms: (string) \033]52;%p1%s;%p2%s\a
%> apt show libncurses6
Package: libncurses6
Version: 6.4-4
[*snip*]
%> ncurses6-config --version
6.4.20221231
```

If there's a specific thing in the logs you'd want to see I'm happy to share that portion, the full logs are so full of PII I'm not comfortable sharing them as-is.

**Comment by nicm** [comment]
`set-clipboard` does not depend on `allow-passthrough` so it is not the reason it works, either you are setting the clipboard separately from `set-clipboard` or have made some other change as well. Does it continue to work even if you turn `set-clipboard` off but leave `allow-passthrough` on?

**Comment by Artanicus** [comment]
Indeed the following config still works after a kill-server:
```
set -g allow-passthrough on
set -g set-clipboard off
```
But the reverse does not:
```
set -g allow-passthrough off
set -g set-clipboard on 
```


OSC-52 works outside tmux (kitty `0.26.4` + ssh to the debian unstable host), and I seem to tick off all the other requirements in https://github.com/tmux/tmux/wiki/Clipboard such as `Ms:`.

**Comment by nicm** [comment]
Right, the script is using passthrough which is why it works with `allow-passthrough`.

Probably `set-clipboard` isn't working either because the script never actually uses it or for the same reason as @blueray453 (ncurses).

**Comment by dabeibao** [comment]
Mine doesn't work either. It is also tmux 3.3a. After setting `allow-passthrough` to on, it works.

My script is:
```sh
stuff="$(base64 -w0)"
esc="\x1b]52;c;${stuff}\x07"
if [ -n "$TMUX" ] ; then
    exec echo -en "\x1bPtmux;\x1b$esc\x1b\\"
else
    exec echo -en "$esc"
fi
```

**Comment by vashirov** [comment]
On Debian I downgraded ncurses from 6.4+20230625-2 to 6.4-4 and it solved the issue for me.

```
# apt install {libncursesw6,libtinfo6,ncurses-bin,ncurses-base}=6.4-4
```

```
# dpkg-query -W | grep -E 'tmux|ncurses|tinfo'
libncursesw6:amd64	6.4-4
libtinfo6:amd64	6.4-4
ncurses-base	6.4-4
ncurses-bin	6.4-4
tmux	3.3a-4
```

**Comment by blueray453** [comment]
@vashirov 

> On Debian I downgraded ncurses from 6.4+20230625-2 to 6.4-4 and it solved the issue for me.

If i run `apt install {libncursesw6,libtinfo6,ncurses-bin,ncurses-base}=6.4-4` then is it enough to downgrade or shall i do something else? I mean if i `sudo apt upgrade` then will it not upgrade the whole system?

**Comment by vashirov** [comment]
I have `bookworm` and `sid` repos enabled, so I was able to downgrade to ncurses packages from `bookworm`.
To prevent the upgrade of these packages next time you run `sudo apt upgrade`, you can mark them on hold:
```
$ sudo apt-mark hold libncursesw6 libtinfo6 ncurses-bin ncurses-base tmux
libncursesw6 set on hold.
libtinfo6 set on hold.
ncurses-bin set on hold.
ncurses-base set on hold.
tmux set on hold.
```

HTH

**Comment by blueray453** [comment]
If I may add, 
```
set-option -s set-clipboard off
set -s copy-command 'xclip -in -selection clipboard'
```
eliminate one issue which i had when i was using 
```
set-option -as terminal-features ',alacritty:clipboard'
set-option -s set-clipboard external
```
The issue was, suppose I gave a long running command. Then i came back, i will see that the tmux session has "[exited]".

This issue came back when I fixed the version of ncurses and set:
```
set-option -as terminal-features ',alacritty:clipboard'
set-option -s set-clipboard external
```
I did not report it earlier because i was not sure whether it was an alacritty issue or tmux issue.
 
So I am again using:
```
set-option -s set-clipboard off
set -s copy-command 'xclip -in -selection clipboard'
```

**Comment by nicm** [comment]
I'm going to close this because the solution is to use a newer or older ncurses version.

There were a series of changes to ncurses to fix potential problems when expanding capabilities (using the `tparm` function). Versions of those changes before 6.4-20230424 will cause tmux builds before 39d41d0810d4e8ae6ce8d27776dfbb96722d9319 to crash with `set-clipboard` on; builds after 39d41d0810d4e8ae6ce8d27776dfbb96722d9319 will not crash but they will not be able to send `Ms` so `set-clipboard` will fail.

ncurses 6.4-20230424 added a function `tparm_s` that tmux can use for `Ms` which solves these problems; any tmux build after `39d41d0810d4e8ae6ce8d27776dfbb96722d9319` will use this if it is available.

It seems like Debian have either upgraded to an ncurses before 6.4-20230424, or backported the changed from before that version.

The solution is to step back to an older ncurses, build an ncurses from 6.4-20230424 or later, or to use a different method of setting the clipboard (see https://github.com/tmux/tmux/wiki/Clipboard).
