### ISSUE TITLE
How to avoid the white line at the bottom?

### ISSUE THREAD

**Issue by maplewizard** [tmux/tmux#365]
I use tmux and has a white line at the bottom. How to set the status bar at the most bottom?The figure are as follow:
![image](https://cloud.githubusercontent.com/assets/1419566/14416367/e0e97e26-ffdb-11e5-85e8-fd406853a4b0.png)

**Comment by nicm** [comment]
This is not to do with tmux but the fact that your font does not fit exactly into the width and height of your  terminal. Try a different font or a different font size.
