### ISSUE TITLE
pane-colours gets unapplied for when bold is active

### ISSUE THREAD

**Issue by amanvm** [tmux/tmux#3651]
### Issue description

pane-colours is supposed to change a terminal's underlying palette. When bold attribute is active, tmux picks older color. Here are steps to reproduce:

```
tmux set -g -t :. pane-colours\[0\]  "#55ff55"
printf "\e[30m\e[45mHelloWorld\e[0m"
printf "\e[1m\e[30m\e[45mHelloWorld\e[0m"
```

Luckily it does not happen with italic or underline. Here's the screenshot showing the problem:

<img width="614" alt="Screenshot 2023-07-30 at 2 05 43 AM" src="https://github.com/tmux/tmux/assets/25681815/c5b1ebc6-3e63-4366-994f-0fd73d6d4ccd">

### Required information

* tmux version (``tmux next-3.4``).
* Platform (``Darwin arm``).
* $TERM inside and outside of tmux (``tmux-256color`` inside, ``xterm-256color`` outside).
* Logs from tmux (``n/a``).

**Comment by amanvm** [comment]
@nicm On my machine it is \e[1m, which is what I use in the example. Not sure if I am misunderstanding something, or if you missed looking at \e[1m and looked at the reset sequence \e[0m at the end of my sample sequences.

**Comment by nicm** [comment]
SGR 1 selects the bright colour, bright colours are 8-15 in the palette, not 0-7. You need to change `pane-colours[8]` for bright black instead of 0.

**Comment by amanvm** [comment]
@nicm This setting disabled ``set -ag terminal-overrides ',*:Nobr'`` brightening of bold font, that's what I needed. Found it from: https://github.com/tmux/tmux/issues/3275.
