### ISSUE TITLE
Ability to change popup color within the popup

### ISSUE THREAD

**Issue by mgpinf** [tmux/tmux#3655]
### Issue description
* It would be nice if there was an ability to change `tmux` popup color from within the popup (especially while running a script that calls it)
* Went through the manual, where it is mentioned that `Panes are not updated while a popup is present.`.
* I think it would be a good idea to edit at least popup options from within the popup window (if not the pane options)
* Asking this because while calling `fzf` within `tmux` popup window, if the `tmux` popup has border beforehand, and the `fzf` window also has borders, it would look cluttered. So, if there is an option to change popup options in a popup window, then the popup border is initially deactivated, and after calling the `fzf` function, the popup border would be activated, (once `fzf` function call ends), thereby obtaining a more homogeneous appearance
* Current tmux popup window in which a script calling `fzf` runs: (as seen, there are 2 borders, one for `fzf`, other one for `tmux`)
  
<img width="1385" alt="image" src="https://github.com/tmux/tmux/assets/56510798/8b98ceaf-952c-496e-a0aa-410735ff3ddc">

* It's a feature request

Steps to reproduce:
* `tmux display-popup 'script'`
* `script` contains command to change tmux popup border color
* Initially the popup window has a border of a certain color
* Unable to change it once the popup window starts

### Required information

* tmux version (`tmux -V`).
`tmux 3.3a`
* Platform (`uname -sp`).
`Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`).
  * Inside `xterm-256color`
  * Outside `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
I have added this to the todo list but I don't think it would be trivial and it doesn't seem to have wide use cases, so I wouldn't hold your breath...

Can't you ask fzf not to show a border instead?
