### ISSUE TITLE
OSC 8 Hyperlinks redux

### ISSUE THREAD

**Issue by HaleTom** [tmux/tmux#3656]
I'm opening this to revisit OSC 8 support which I believe was first raised in "Feature request: Hyperlinks" #911 in 2017.

It seemed that "support osc-8 hyperlinks" #3240 got very close to a resolution, and stalled on including `curses.h`.  It was close because of inactivity.

I re-open this since general support of this feature continues to grow:

- [GCC 10](https://gcc.gnu.org/gcc-10/changes.html#:~:text=As%20of%20GCC%2010%2C%20that%20option%20text%20is%20now%20a%20clickable%20hyperlink%20for%20the%20documentation%20of%20that%20option) since May 7, 2020
- [groff](https://www.gnu.org/software/groff/): Since [1.23.0](https://git.savannah.gnu.org/cgit/groff.git/tag/?h=1.23.0) (2023-07-05), for links in roff documents, including man pages.
- [ls --hyperlink[=always/auto/never]](https://www.gnu.org/software/coreutils/manual/html_node/ls-invocation.html#ls-invocation): since [coreutils v8.28](https://github.com/coreutils/coreutils/blob/v8.28/NEWS#L88-L89) (2017-09-02).
- [Emacs](https://www.gnu.org/software/emacs/): Since [28.1](https://www.gnu.org/software/emacs/news/NEWS.28.1) (2022-04-04)

The above list is courtesy of [Alhadis/OSC8-Adoption](https://github.com/Alhadis/OSC8-Adoption#apps).

@tizee Did I correctly glean that #3240 was very close to completion?

**Comment by nicm** [comment]
See cdacc12ce305ad2f3e65e2a01328a988e3200b51.
