### ISSUE TITLE
new-window doesn't respect the session directory set using new-session -c flag

### ISSUE THREAD

**Issue by darkseid-is** [tmux/tmux#3657]
### Issue description
Tmux new-window doesn't respect the session directory set using new-session when detached.

```
tmux -L temp new-session -d -c /tmp
tmux -L temp new-window
```
the above command creates window with current directory as working directory.

`tmux -L temp new-window -c /tmp ` works as intended

### Required information

Please provide the following information:

* tmux version (`tmux next-3.4`).
* Platform (`Linux unknown
`).
* $TERM inside and outside of tmux (`xterm-256color`).

**Comment by nicm** [comment]
Correct, when you create a new window from the shell, tmux will use the shell's working directory. This is so you can do stuff like:
~~~~
echo foo >bar
tmux neww "emacs bar"
~~~~
The session working directory is used when `new-window` is used from somewhere without a shell, such as the command prompt.

If you want a different directory you will need to use `-c`.
