### ISSUE TITLE
Sometimes tmux crashes while kill a session

### ISSUE THREAD

**Issue by invisible1988** [tmux/tmux#3658]
### Issue description

Hey Guys,

I work with a lot tmux sessions. Sometimes when I'm killing a session, the whole tmux server crashes. I tried to reproduce it right now, but didn't have luck.

Someone else experienced this behavior?

### Required information

Please provide the following information:

* tmux version: tmux 3.3a
* Platform: Darwin arm, Mac OS, M2
* $TERM: screen-256color
* Logs: Couldn't reproduce it

**Comment by nicm** [comment]
Does this still happen if you build tmux from master? Does tmux leave a core?

There was a crash you could trigger by editing at the tmux command prompt (C-b :) in 3.3a, were you doing that?

If it still happens with master and there is no core, you will need to figure out how to reproduce...
