### ISSUE TITLE
Is there a way to revert to old pane-navigation bahaviour?

### ISSUE THREAD

**Issue by N46AN** [tmux/tmux#366]
In changelog CHANGES FROM 1.9a to 2.0 6 March 2015:
```
Pane navigation has changed:
......
(because clearly if we go right from the top-left in a tiled set of four 
we want to end up in top-right, even if we were last using the bottom-right).
```
In my use case, the bottom-right pane is always displaying syslog.
So If I want to go right from the bottom-left, I always want to end up in top right, not bottom-right.

Is it possible to revert to old pane-navigation bahaviour?

Thanks!

**Comment by nicm** [comment]
No we are not going to change this again, but you can bind a key to to do select-pane -t'{bottom-right}'.

**Comment by nicm** [comment]
Er, or {top-right}.

**Comment by N46AN** [comment]
@nicm I managed to find the corresponding commit [https://github.com/tmux/tmux/commit/540f0b3e45acae9b0c5fa12f7e9170c6c78d177f](url)
 and reverted to the old behaviour.
