### ISSUE TITLE
Crash when removing last item from paste buffer

### ISSUE THREAD

**Issue by brsakai-csco** [tmux/tmux#3662]
### Issue description

tmux server crashes when I remove all elements from the paste buffer while it's open.

I didn't see a similar open issue but I'm not overly familiar with tmux terminology so I may have missed it

Steps to reproduce:
1. On git commit `b013e0`
2. `./tmux -Ltest kill-server`
3. `./tmux -Ltest -f/dev/null new`
4. `C-b [` (enter copy mode)
5. `C-space` (start copying)
6. Left arrow a few times
7. `C-w` (finish copying, so there should be 1 element in paste buffer)
8. `C-b =` (open paste buffer)
9. `C-b -` (remove element from paste buffer)
10. Wait a bit (less than 30 seconds)
11. tmux prints `[server exited unexpectedly]` (and strace shows that the server dies with a SIGSEGV)

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux next-3.4` (first seen in `tmux 3.2a`)
* Platform (`uname -sp`): `Linux x86_64` (Ubuntu 22.04.3)
* $TERM inside and outside of tmux (`echo $TERM`): `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): Attached below (I used `./tmux -f /dev/null -vv new` as opposed to what's shown here)
    * [tmux-server-13087.log](https://github.com/tmux/tmux/files/12317104/tmux-server-13087.log)
    * [tmux-client-13085.log](https://github.com/tmux/tmux/files/12317105/tmux-client-13085.log)
    * [tmux-out-13087.log](https://github.com/tmux/tmux/files/12317106/tmux-out-13087.log)

**Comment by brsakai-csco** [comment]
Thanks @nicm for the quick response!

With this change, there is no crash at step 10, but the element is not removed visually from the list, and the paste buffer doesn't close. Looks like maybe the list empties but the display doesn't refresh. Hitting Enter closes the paste buffer and I'm then unable to reopen it with `C-b =` (since it's empty, adding new items to the buffer lets me open it again)

This behavior differs from when there are two elements in the paste buffer, and deleting one instantly refreshes the display to show only one member

My expected behavior when deleting the last item in the buffer would be to either
1. Display an empty list
2. Close the paste buffer when there are no elements in it (this is probably better, since the buffer can't be opened while there are no entries in it)

So this prevents the crash, which is good enough to resolve this issue. But it still leaves a visual bug which may or may not matter.

**Comment by nicm** [comment]
I noticed that but I don't think it matters. If you really care that it exit when empty the delete them with `d` instead.

**Comment by brsakai-csco** [comment]
Yeah, that makes sense. Since the patch above solves the crash, that's enough for me. And looks like that `d` command doesn't trigger the crash even in the original version, so that's a helpful workaround

**Comment by nicm** [comment]
Great, I have applied this fix. Thanks!
