### ISSUE TITLE
gibberish being inserted on entering session

### ISSUE THREAD

**Issue by elandorr** [tmux/tmux#3663]
tmux next-3.4 from today
debian stable
naked rxvt-unicode-256color
in tmux xterm-256color
makes sense since set -g default-terminal "xterm-256color"
nothing is shown verbose other than 'exited'

On attach or new, this is inserted:

10;rgb:de00/c100/6500]11;rgb:2500/1200/0000

Which causes random strangeness to happen, depending on where you left off.

Tried the latest tmux git to see if it's fixed to no avail.

Nothing changed, except regular Debian updates.

I have absolutely no time to debug this, zero, but I wanted to quickly post it anyway since there are 0 search hits.

**Comment by nicm** [comment]
This is a bug in rxvt-unicode, see https://github.com/tmux/tmux/issues/3470.

**Comment by nicm** [comment]
It was reported to them but I don't know if they have fixed it or not.
