### ISSUE TITLE
tmux auto completion is broken or nonexistent

### ISSUE THREAD

**Issue by Cody-Learner** [tmux/tmux#3667]
Installed the official Arch tmux package: https://archlinux.org/packages/extra/x86_64/tmux/

$ uname -a
Linux Arch2023p3-2 6.4.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 16 Aug 2023 22:44:10 +0000 x86_64 GNU/Linux

$ pacman -Q tmux
tmux 3.3_a-7

Auto completion is nonexistent in bash. ie: typing tmux, [space], [tab] in the console or vt should provide completions, and none are available. 

Had to install an additional non official, AUR package for auto completion: https://aur.archlinux.org/packages/tmux-bash-completion-git

$ aurch -Bi tmux-bash-completion-git

This should be part of/included with the tmux package. https://github.com/imomaliev/tmux-bash-completion

**Comment by nicm** [comment]
This is one for the developers of your shell or your packages.
