### ISSUE TITLE
sixel doesn't seem to work on macOS

### ISSUE THREAD

**Issue by amanvm** [tmux/tmux#3668]
### Issue description

This comment https://github.com/tmux/tmux/issues/3652#issuecomment-1679458641, and this commit https://github.com/tmux/tmux/commit/dfbc6b1888c110cf0ade66f20188c57757ee1298 motivated me to try sixel (tmux configured with ``--enable-sixel``). It doesn't seem to work fully on aarch64 macOS. What I see is that cat doesn't work. [lsix](https://github.com/hackerb9/lsix) does produce a tiny few cursor wide result, but never bigger than that. cat works outside in iTerm2 and other terminals (produces full size image in terminal).

Inside tmux in iTerm2 or WezTerm:
<img width="396" alt="Screenshot 2023-08-22 at 10 56 20 PM" src="https://github.com/tmux/tmux/assets/25681815/d6bf8936-4919-4162-a5b5-0b495d656b35">

Outside tmux in iTerm or WezTerm:
<img width="545" alt="Screenshot 2023-08-22 at 11 05 08 PM" src="https://github.com/tmux/tmux/assets/25681815/b973476b-3a53-4591-93c8-2a28aed23866">

### Required information

Please provide the following information:

* tmux version (``tmux next-3.4``).
* Platform (``Darwin arm``).
* $TERM inside and outside of tmux (``xterm-256color`` outside, ``tmux-256color`` inside).
* Logs from tmux (`tmux kill-server; tmux -vv new`): [tmux-logs.zip](https://github.com/tmux/tmux/files/12415855/tmux-logs.zip)

**Comment by nicm** [comment]
What does `tmux display -p '#{client_cell_width} #{client_cell_height}'` show inside tmux?

**Comment by nicm** [comment]
Your file is too big, it is 2.1 MB but the limit is 1 MB. Convert it to be smaller.

**Comment by nicm** [comment]
I think 1 MB is a reasonable limit TBH but maybe we could bump it up.

The image will disppear if the pane is resized horizontally.

**Comment by nicm** [comment]
That's because SIXEL is slow.

Entering and exiting the alternate screen will also remove the image, although if the terminal size has not changed on exit it probably shouldn't <-- @topcat001.

**Comment by nicm** [comment]
tmux cannot scroll a SIXEL, so it needs to redraw it when you scroll which is slow. Terminals can just move them so they don't have the same problem.

This is one of the reasons SIXEL is not a very good image protocol...

**Comment by nicm** [comment]
No, I don't want an option or mouse clicking. If you use big images then it will be slow. Is gnuplot really generating 3 MB images? You can always remove the image yourself by resizing, although a command to do it manually would be OK.

**Comment by nicm** [comment]
This image is 2100x1180 which is too big, the maximum is 2016x2016.

**Comment by topcat001** [comment]
@amanvm Thank you for testing.
 
> Entering and exiting the alternate screen will also remove the image, although if the terminal size has not changed on exit it probably shouldn't <-- @topcat001.

Yes I think this is reasonable.

**Comment by nicm** [comment]
I can't think of or see a technical reason for the 2016x2016 limit so we could probably increase it quite a bit.

**Comment by topcat001** [comment]
Probably 4k resolution is sufficient?

**Comment by Jorengarenar** [comment]
Hmm, I'm on Linux, I've compiled with `--enable-sixel`, but even [monkey-2.sixel.txt](https://github.com/tmux/tmux/files/12416918/monkey-2.sixel.txt) doesn't work for me

**Comment by Jorengarenar** [comment]
@amanvm Yes indeed, even few emulators, XTerm in particular. Without tmux images are displayed.

**Comment by topcat001** [comment]
Thank you for the fix. I missed those commits in my local copy and was puzzled about this :) BTW, `tools/image.sixel` in the repo can be used to test.
