### ISSUE TITLE
pane_current_command is far too long for a window name

### ISSUE THREAD

**Issue by sam-s** [tmux/tmux#3669]
### Issue description

I did not change `automatic-rename` (`on`) and `automatic-rename-format`  `#{?pane_in_mode,[tmux],#{pane_current_command}}#{?pane_dead,[dead...`

The window names in the status in the bottom middle are good except that sometimes there are far far far too long.
E.g.:
```
2UA8471RN8/main][0:bash* 1:C:\\Users\\ssteingold\\venv\\a3\\Scripts\\python.e>][2023-08-23 16:29]
```

I wonder if it might be possible to keep just the `python` part of the name and drop the full path.

### Required information

* tmux version (`tmux -V`).
`tmux 3.3a`

* Platform (`uname -sp`).
`MINGW64_NT-10.0-19044 unknown`

* $TERM inside and outside of tmux (`echo $TERM`).
`xterm-256color` under tmux, `xterm` outside.

**Comment by nicm** [comment]
If you change it to `#{b:pane_current_command}`, does it help?

**Comment by sam-s** [comment]
Yes, thank you,  much better: it is now `pythonw.exe`.
It would have been even better if `.exe` were gone too!

**Comment by nicm** [comment]
You can get rid of the exe with s, something like `#{s/\.exe$//:#{b:pane_current_path}}`.
