### ISSUE TITLE
`new-window -S -n <window-name>` does not expand window-name for comparing window names

### ISSUE THREAD

**Issue by schnedo** [tmux/tmux#3670]
### Issue description

Title pretty much describes the problem.

Steps to reproduce:

* Start new test server:
```
tmux -Ltest kill-server
tmux -Ltest -vv -f/dev/null new
```
* Run new-window in command mode `<C-B>:`. New window opens with name 'foo@0' as expected.
```
new-window -S -n "foo#{window_id}"
```
* Go back to window 0 `<C-B>0` and rerun new-window command. Another new window opens with name 'foo@0'. This should not happen as -S flag should open previously created window.

* Rename current window to unexpanded name:
```
rename-window "foo##{window_id}"
```
* Go back to window 0 `<C-B>0` and rerun new-window command. Renamed window with unexpanded name opens instead of window named 'foo@0'.

### Required information

* tmux version `tmux next-3.4`
* Platform `Linux x86_64`
* $TERM inside `screen-256color` and outside of tmux `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-out-88899.log](https://github.com/tmux/tmux/files/12438549/tmux-out-88899.log)
[tmux-server-88899.log](https://github.com/tmux/tmux/files/12438550/tmux-server-88899.log)
[tmux-client-88897.log](https://github.com/tmux/tmux/files/12438548/tmux-client-88897.log)

**Comment by nicm** [comment]
This should be fixed now in OpenBSD, will be in GitHub later on. Thanks!
