### ISSUE TITLE
(Feature request) Allow setting "default-command" per session

### ISSUE THREAD

**Issue by Hubro** [tmux/tmux#3671]
I use tmux heavily at work, one session per project. I've recently started using Nix to manage project dependencies, and I use `nix-shell --command zsh` to start development shells that have all my dependencies installed.

It would be nice if I didn't have to run this for each new pane or window, but I obviously can't update my global `default-command` since not all my projects use Nix.

Unfortunately running `tmux new-session "nix-shell --command zsh"` only works for the initial window created, any window opened after this use the system default shell.

Setting the `SHELL` environment variable in the session scope has no effect, but in any case it looks like tmux ignores `SHELL` if it contains any spaces.

It would be perfect if `default-command` could be set per session. If that's technically challenging (which I'm guessing it is), maybe introduce a new session-scoped option called `session-default-command` or something like that. It could be set on launch like:

```
$ tmux new-session -C "nix-shell --command zsh"
```

This would be great for Nix users, but also for Python developers (`tmux new-session -C "poetry shell"`) and probably others.

---

As a workaround, I can set the global `default-command` to a script the defaults to launching my shell, but instead runs `nix-shell --command zsh` if a `shell.nix` file is detected.

This isn't perfect, since I don't always want to do this (for example when perusing repos I'm not working on). I'd rather be explicit when I start my session.

I could achieve this by setting an environment variable for the session that instructs the default script what to do.

In any case, I probably won't be doing this since I like to synchronize my tmux config to all my servers and I don't want to add a dependency on an external script.

**Comment by nicm** [comment]
But `default-command` is already a session option??
