### ISSUE TITLE
Keyboard interrupt a running search

### ISSUE THREAD

**Issue by YodaEmbedding** [tmux/tmux#3675]
### Issue description

1. Output a ton of data in the terminal window.
2. Now, run a regex search, e.g. `^hel*o`
3. It may take quite some time. Tmux freezes until the search completes.

Possible proposed fixes:

1. Ability to cancel the search via e.g. Ctrl-C, or (less discoverable, but more robust) Prefix+Ctrl-C, or something like that.
2. Perform search on a different non-UI thread. Lock user input on only the current pane, but not the window/session/client.

### Required information

Please provide the following information:

* tmux version: tmux 3.3a
* Platform: Arch Linux
* $TERM inside: tmux-256color; outside of tmux: alacritty.
* Logs from tmux: N/A.

**Comment by nicm** [comment]
I cannot make a search take long enough to even hit the timeout now, so I don't know that this is necessary. What are you searching for and in how much history?

**Comment by YodaEmbedding** [comment]
Looks like it's a problem only if searching for contains certain regex characters (e.g. `^`).

Searching backwards for the regex `^hello` is problematic. In contrast, a non-regex `hello` searches nearly instantly.

Here's a reproducible example:

```
echo "set  -g history-limit 20000" > example.conf
tmux -f example.conf
python -c 's = "0123456789" * 100000; print(s); print("hello world"); print(s)'

<C-b>[?^hello<CR>
```

If that doesn't freeze for long enough (depends on your CPU), increase the magnitude by 10x or 100x. Note that sufficiently large numbers may be prone to crashes.

---

Forgot to mention earlier: I have also noticed that tmux is prone to crashing if the amount of text to search is very large (or is it because the text contains "binary output data"? not sure), and I try to do some actions while that search is running (C-c, switch panes, etc).

**Comment by nicm** [comment]
Yes, we do far too much work when you have very log lines. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/12509193/x.diff.txt)

We should probably make this part of searching have the timeout as well (timeout is currently only applied to marking search results).

**Comment by YodaEmbedding** [comment]
`WINDOW_COPY_SEARCH_MAX_LINE` seems to make everything much more tolerable, including my usual use-case of accidentally printing a ton of long lines and then running a regex.

It's a bit strange that a regex on a long line takes many hours to run, though. For comparison, python runs a similar regex search in 0.005s:

```python
import re
import timeit

s = "0123456789" * 1000000 + "hello" + "0123456789" * 1000000
print(timeit.timeit(lambda: re.search(r"hel*o", s), number=1000) / 1000)

# 0.005 seconds/search
```

**Comment by nicm** [comment]
The major improvement comes from not searching wrapped lines multiple times (once for each screen line) rather than the length limit.

But yes it could probably do with being profiled since we are no doubt doing more work than we need to in other places.

For the moment I have applied this change to OpenBSD, it should be in GitHub later. Thanks!
