### ISSUE TITLE
prefix C-up/down/left/right keyboard short no longer working Apple M1 Pro 2021

### ISSUE THREAD

**Issue by azizj1** [tmux/tmux#3677]
### Issue description

The following shortcuts are no longer working in tmux 3.2a

```
bind-key -r -T prefix C-Up             resize-pane -U 14
bind-key -r -T prefix C-Down           resize-pane -D 10
bind-key -r -T prefix C-Left           resize-pane -L 15
bind-key -r -T prefix C-Right          resize-pane -R 15
```

I want the panes to resize if I do ctl+b, let go of 'b', and then repeatedly press up/down/left/right to change the pane size.

* OS: macOS 13.5
* iTerm2 version Build 3.4.20

### Required information

Please provide the following information:

* tmux version: 3.2a
* Platform: Darwin arm
* $TERM inside: xterm-256color
* $TERM outside: xterm-256color
* Logs from tmux: none

**Comment by krader1961** [comment]
What happens if you run `cat -evt` and press C-Up outside of Tmux? Since Ctrl-Up is intercepted by the window manager on my macOS system Tmux never sees it. This also happens for Ctrl-Down. But not Ctrl-Left or Ctrl-Right. It isn't obvious your issue has anything to do with Tmux and is instead a consequence of the behavior of macOS.

**Comment by krader1961** [comment]
Also, @azizj1, the value of the `TERM` env var should never be `xterm-256color` inside a Tmux session. That will work most of the time but can cause problems even if your external terminal reports to be `xterm-256color`. It should be a `screen` or `tmux` variant inside a Tmux session.

**Comment by azizj1** [comment]
> What happens if you run cat -evt and press C-Up outside of Tmux? 

<img width="226" alt="image" src="https://github.com/tmux/tmux/assets/11378821/3066815d-00b2-4fd4-b371-3c6e0acb035b">

It adds characters to the screen as expected. For all four Ctrl up/down/left/right. My older Mac (where these bindings work) does the same thing. I've tried both Mac's native terminal and iTerm2. Both behave similarly.

> P.S., You should always provide a Tmux server log for this type of issue.

How do I get the server logs?

**Comment by JuliusDegesys** [comment]
I just updated to Ventura 13.5.1, and am seeing this same issue with both WezTerm and the native Terminal. @azizj1 can you run the `cat -evt` command inside of tmux as well? Also, can you check if you use Alt/Option + Shift + Arrow Key, does it do what the previous ctrl up/down/left/right keys did?

Outside of tmux:
```
printf '\033[>4;1m'
cat -evt

# Up/Down/Right/Left
^[[A^[[B^[[C^[[D
# Shift + Up/Down/Right/Left
^[[1;2A^[[1;2B^[[1;2C^[[1;2D
# Alt + Up/Down/Right/Left
^[[1;3A^[[1;3B^[[1;3C^[[1;3D
# Alt + Shift + Up/Down/Right/Left
^[[1;4A^[[1;4B^[[1;4C^[[1;4D
# Ctrl + Up/Down/Right/Left
^[[1;5A^[[1;5B^[[1;5C^[[1;5D
```

Inside of tmux:
```
# No Mods
^[[A^[[B^[[C^[[D
# Shift
^[[1;3A^[[1;3B^[[1;2C^[[1;2D
# Alt
^[[1;4A^[[1;4B^[[1;4C^[[1;4D
# Alt + Shift
^[[1;5A^[[1;5B^[[1;5C^[[1;5D
# Ctrl 
^[[1;6A^[[1;6B^[[1;6C^[[1;6D
```

So, it looks like the modifier masks are getting mixed up.

**Comment by JuliusDegesys** [comment]
And here's my tmux server log (I hope this is the same issue and I'm not hijacking this thread):
[tmux-server-9211.log](https://github.com/tmux/tmux/files/12539434/tmux-server-9211.log)

**Comment by nicm** [comment]
There are no key presses in this log, what's the point in a log that doesn't show the problem?

**Comment by nicm** [comment]
Show me the output of `infocmp -x` outside tmux as well please.

**Comment by JuliusDegesys** [comment]
And in case it's easier to just see a single key being pressed, here's the tmux server log for just Ctrl+Left (you'll notice tmux sends C+S+Left):
```
1694014355.333978 writing key 0x60000010e1aa (C-S-Left) to %0
1694014355.334066 found key 0x60000010e1aa: "\033[1;6D"
1694014355.334075 input_key: \033[1;6D
```

[tmux-server-10947.log](https://github.com/tmux/tmux/files/12539714/tmux-server-10947.log)

**Comment by nicm** [comment]
> kUP=\E[1;7C, kUP3=\E[1;2A, kUP4=\E[1;3A,
> kUP5=\E[1;4A, kUP6=\E[1;5A, kUP7=\E[1;6A, ka2=\E[1;7A,

This is wrong. If your terminal is generating `\033[1;5A` for C-Up, then `kUP5` should be `\033[1;5A` not `\033[1;4A`. They all look wrong.

Have you installed a custom terminfo entry?

You can do one of the following:

- Update the xterm-256color entry using tic from a working installation or ncurses sources.

- Install a newer ncurses and link tmux against it instead of the system ncurses.

- Remove all these entries from tmux with `terminal-overrides` so it uses the builtin defaults, something like:
    ~~~~
    set -as terminal-overrides 'xterm*:kUP@:kUP2@:kUP3@:kUP4@:kUP5@:kUP6@:kUP7@'
    ~~~~
    And the same for kLFT, kRIT, kDN and so on.

**Comment by JuliusDegesys** [comment]
Ahh. So nice! The `terminal-overrides` fixes things. Thank you!

To the best of my knowledge, I have not installed a custom terminfo entry (I actually have no idea how one would do that). I will research your other suggestions as well to figure out how get the terminfo back into alignment.

**Comment by JuliusDegesys** [comment]
For future reference (and for those running into the same issue), you can also follow the steps below to get the terminfo setup for `tmux-256color` (@nicm 's first suggestion): https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95

**Comment by nicm** [comment]
I upgraded my macOS and I see the same.

I'm not sure what version of ncurses it had before but now it says 5.7.20081102. I checked that upstream version and its xterm-256color looks correct. In fact, there is only one `kUP7` in any entry and it is right:
~~~~
$ fgrep '[1;7A' misc/terminfo.src
        kUP4=\E[1;4A, kUP5=\E[1;5A, kUP6=\E[1;6A, kUP7=\E[1;7A,
~~~~
So it appears Apple have contrived to make a mess of this somehow.

Anyway, you can use one of the solutions above, or complain to Apple.

**Comment by nicm** [comment]
If you install iTerm2 it now appears to ship with its own terminfo entries and set `TERMINFO_DIRS`:
~~~~
$ echo $TERMINFO_DIRS
/Applications/iTerm.app/Contents/Resources/terminfo:/usr/share/terminfo
~~~~
Although those are built with a newer ncurses and don't work with the system ncurses, so I'm not sure what their intention is...

**Comment by ThomasDickey** [comment]
Perhaps someone at Apple messed up.   The naming for the extended (modified) keys shows what the modifier code is.   I see a recent (August 2) date on my macOS' terminfo entry, and get the same result for the infocmp output.  But it differs from the content that I created (whether due to Apple or the very-old version of the tools which they use I don't know).  Here's what infocmp says about the difference compared with the current version (there are of course differences in features other than the modified keys):
````
comparing xterm-256color to xterm-256color.
        eslok: T, F.
        hs: T, F.
        XF: T, F.
        XT: T, F.
        pairs: 65536, 32767.
        dim: '\E[2m', -.
        dsl: '\E[0$~', -.
        fsl: '\E[0$}', -.
        ka1: '\EOw', -.
        ka3: '\EOy', -.
        kb2: '\EOu', '\EOE'.
        kbeg: '\EOE', -.
        kbs: '^?', '^H'.
        kc1: '\EOq', -.
        kc3: '\EOs', -.
        kmous: '\E[<', '\E[M'.
        mgc: '\E[?69l', -.
        nel: '\EE', -.
        oc: '\E]104\007', -.
        rep: '%p1%c\E[%p2%{1}%-%db', -.
        ritm: '\E[23m', -.
        rmcup: '\E[?1049l\E[23;0;0t', '\E[?1049l'.
        rs1: '\Ec\E]104\007', '\Ec'.
        sgr: '%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m', '%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m'.
        sitm: '\E[3m', -.
        smcup: '\E[?1049h\E[22;0;0t', '\E[?1049h'.
        smglp: '\E[?69h\E[%i%p1%ds', -.
        smglr: '\E[?69h\E[%i%p1%d;%p2%ds', -.
        smgrp: '\E[?69h\E[%i;%p1%ds', -.
        tsl: '\E[2$~\E[1$}\E[%i%p1%d`', -.
        u8: '\E[?%[;0123456789]c', '\E[?1;2c'.
        BD: '\E[?2004l', -.
        BE: '\E[?2004h', -.
        Cr: '\E]112\007', -.
        Cs: '\E]12;%p1%s\007', -.
        E3: '\E[3J', -.
        Ms: '\E]52;%p1%s;%p2%s\007', -.
        PE: '\E[201~', -.
        PS: '\E[200~', -.
        RV: '\E[>c', -.
        Se: '\E[2 q', -.
        Ss: '\E[%p1%d q', -.
        XM: '\E[?1006;1004;1000%?%p1%{1}%=%th%el%;', -.
        XR: '\E[>0q', -.
        kDC3: '\E[3;3~', -.
        kDC4: '\E[3;4~', '\E[3;3~'.
        kDC5: '\E[3;5~', '\E[3;4~'.
        kDC6: '\E[3;6~', '\E[3;5~'.
        kDC7: '\E[3;7~', '\E[3;6~'.
        kDN: '\E[1;2B', '\E[3;7~'.
        kDN3: '\E[1;3B', '\E[1;2B'.
        kDN4: '\E[1;4B', '\E[1;3B'.
        kDN5: '\E[1;5B', '\E[1;4B'.
        kDN6: '\E[1;6B', '\E[1;5B'.
        kDN7: '\E[1;7B', '\E[1;6B'.
        kEND3: '\E[1;3F', '\E[1;7B'.
        kEND4: '\E[1;4F', '\E[1;3F'.
        kEND5: '\E[1;5F', '\E[1;4F'.
        kEND6: '\E[1;6F', '\E[1;5F'.
        kEND7: '\E[1;7F', '\E[1;6F'.
        kHOM3: '\E[1;3H', '\E[1;7F'.
        kHOM4: '\E[1;4H', '\E[1;3H'.
        kHOM5: '\E[1;5H', '\E[1;4H'.
        kHOM6: '\E[1;6H', '\E[1;5H'.
        kHOM7: '\E[1;7H', '\E[1;6H'.
        kIC3: '\E[2;3~', '\E[1;7H'.
        kIC4: '\E[2;4~', '\E[2;3~'.
        kIC5: '\E[2;5~', '\E[2;4~'.
        kIC6: '\E[2;6~', '\E[2;5~'.
        kIC7: '\E[2;7~', '\E[2;6~'.
        kLFT3: '\E[1;3D', '\E[2;7~'.
        kLFT4: '\E[1;4D', '\E[1;3D'.
        kLFT5: '\E[1;5D', '\E[1;4D'.
        kLFT6: '\E[1;6D', '\E[1;5D'.
        kLFT7: '\E[1;7D', '\E[1;6D'.
        kNXT3: '\E[6;3~', '\E[1;7D'.
        kNXT4: '\E[6;4~', '\E[6;3~'.
        kNXT5: '\E[6;5~', '\E[6;4~'.
        kNXT6: '\E[6;6~', '\E[6;5~'.
        kNXT7: '\E[6;7~', '\E[6;6~'.
        kPRV3: '\E[5;3~', '\E[6;7~'.
        kPRV4: '\E[5;4~', '\E[5;3~'.
        kPRV5: '\E[5;5~', '\E[5;4~'.
        kPRV6: '\E[5;6~', '\E[5;5~'.
        kPRV7: '\E[5;7~', '\E[5;6~'.
        kRIT3: '\E[1;3C', '\E[5;7~'.
        kRIT4: '\E[1;4C', '\E[1;3C'.
        kRIT5: '\E[1;5C', '\E[1;4C'.
        kRIT6: '\E[1;6C', '\E[1;5C'.
        kRIT7: '\E[1;7C', '\E[1;6C'.
        kUP: '\E[1;2A', '\E[1;7C'.
        kUP3: '\E[1;3A', '\E[1;2A'.
        kUP4: '\E[1;4A', '\E[1;3A'.
        kUP5: '\E[1;5A', '\E[1;4A'.
        kUP6: '\E[1;6A', '\E[1;5A'.
        kUP7: '\E[1;7A', '\E[1;6A'.
        ka2: '\EOx', '\E[1;7A'.
        kb1: '\EOt', -.
        kb3: '\EOv', -.
        kc2: '\EOr', -.
        kp5: '\EOE', -.
        kpADD: '\EOk', -.
        kpCMA: '\EOl', -.
        kpDIV: '\EOo', -.
        kpDOT: '\EOn', -.
        kpMUL: '\EOj', -.
        kpSUB: '\EOm', -.
        kpZRO: '\EOp', -.
        kxIN: '\E[I', -.
        kxOUT: '\E[O', -.
        rmxx: '\E[29m', -.
        rv: '\E\\[41;[1-6][0-9][0-9];0c', -.
        smxx: '\E[9m', -.
        xm: '\E[<%i%p3%d;%p1%d;%p2%d;%?%p4%tM%em%;', -.
        xr: '\EP>\\|XTerm\\([1-9][0-9]+\\)\E\\\\', -.
````

**Comment by ThomasDickey** [comment]
I've noticed that Apple has updated the terminfo tree a few times, though the applications and libraries are old.   Updating the terminfo is something that (I assume) they did (like OpenBSD) to get some newer terminal descriptions.

**Comment by ThomasDickey** [comment]
Their [Git repo](https://github.com/apple-oss-distributions/ncurses/tree/ncurses-61.140.2) has been updated recently -- for `tiparm` -- but nothing obvious about the terminal database.

**Comment by nicm** [comment]
>        kHOM7: '\E[1;7H', '\E[1;6H'.
>        kIC3: '\E[2;3~', '\E[1;7H'.
>        kIC4: '\E[2;4~', '\E[2;3~'.

It looks like they've lost kDC3 and shifted the rest down. Maybe a misbehaving script...

Perhaps they'll fix it in a later release.

**Comment by ThomasDickey** [comment]
Welll... I had fixed problems in tic/infocmp related to forward-referencing in [ncurses 6.2](https://invisible-island.net/ncurses/announce-6.2.html#h3-bug-fixes).  Perhaps this is something related (old code, new data, bugs).
