### ISSUE TITLE
base-index is ignored if started via tmux attach and new-session

### ISSUE THREAD

**Issue by peterhoeg** [tmux/tmux#368]
```set -g base-index 1``` works as normal to change the index of the first window, but is ignored if tmux autocreates a session as part of ```tmux attach```.

Create ```/etc/tmux.conf``` as follows:
```
new-session
set -g base-index 1
```
Without tmux running, run ```tmux``` and the first window has index 1.
Without tmux running, run ```tmux attach``` and the window has index 0.
If the window with index 0 is now closed, tmux will use 1 as the base index.

Observed on tmux 2.1

**Comment by nicm** [comment]
By the time you set base-index, the session has already been created...

**Comment by peterhoeg** [comment]
Thanks for the quick response. Is there any way to work around this or ideally align the functionality between starting normally and tmux attach spawning a new session?

**Comment by nicm** [comment]
Set base-index before you create new sessions.

**Comment by peterhoeg** [comment]
Cool, that does the trick, thanks! Oddly enough, the other configuration in tmux.conf DO take effect despite being defined after ```new-session```.

**Comment by nicm** [comment]
That is because base-index is only used when you create a new window or
when they are renumbered. If it isn't set when a window is created, the
window is created at index 0.
