### ISSUE TITLE
Feature Request: Allow for triggering terminal bell when commands need user input

### ISSUE THREAD

**Issue by jdholtz** [tmux/tmux#3681]
### Issue description
In a Tmux session, it would be helpful for a terminal bell to ring when a command being run requires user input. An example of this would be running `pacman -Syu` on Arch Linux, triggering a full system update. Sometimes, this takes a while and it would be nice to be alerted when user action is needed. Obviously this feature could be added in every specific command that takes user input, but I believe it would be more helpful for users to have a general solution.

### Required information

Please provide the following information:

* tmux version (`tmux 3.3a`).
* Platform (`Linux unknown`).
* $TERM inside and outside of tmux (`xterm-256color both inside and outside`).
* Logs from tmux (`N/A`).

**Comment by nicm** [comment]
How would tmux know this? Apart from no output which is already covered by `monitor-silence`.

**Comment by jdholtz** [comment]
> How would tmux know this? Apart from no output which is already covered by `monitor-silence`.

I'm not very familiar with tmux yet, so I am not sure if tmux even has the ability to know when commands need user input. However, I didn't know tmux had a `monitor-silence`, so I will use that. Thanks!
