### ISSUE TITLE
tty-keys put in the shell prompt when launching tmux

### ISSUE THREAD

**Issue by bivoje** [tmux/tmux#3683]
### Issue description

When I start tmux (executing `tmux` from shell) I sometimes get unexpected characters injected into my shell prompt. Not only shown on the screen, they are put in the readline buffer so that I have to delete them before entering my commands. 

my ordinary prompt
![Screenshot 2023-09-06 204736](https://github.com/tmux/tmux/assets/16592366/6af6c303-16eb-414b-86b2-f499fccea336)

tty-keys injected in tmux
![Screenshot 2023-09-06 204712](https://github.com/tmux/tmux/assets/16592366/30c2f8e1-2163-4ba7-b332-1b78eaf527e0)

The injected string contains an identical substring from [WSL issue #5931](https://github.com/microsoft/WSL/issues/5931) but the problem does not go away after applying the suggested solution. (Changing the value of `set -sg escape-time` from 0 to 500 doesn't work)
Since the problem occurs only occasionally, I decided to dig for the solution by myself.

### what I found

From the prefix pattern (`\033[`) I suspect they are tty-keys that tmux should have handled behind the scenes.
Actually, injected strings are sent from my terminal emulator (WezTerm) as the response to the previous CGI request from the program (probably tmux itself)
In the tmux server log file, at the timestamp `1694003698.249734`, we can see that the tty-key sequence is not handled correctly while correctly handling the similar sequence at `1694003698.249724`. (It should have reported `partial key` instead of treating the sequence header `\033` as an independent key)

```
*1694003698.249724 /dev/pts/1: complete key \033[>0;10;1c 0xfe000000000 # GOOD
1694003698.249726 /dev/pts/1: keys are 6 (\033[?1;0)
1694003698.249729 /dev/pts/1: next key is 6 (\033[?1;0) (expired=0)
1694003698.249732 /dev/pts/1: next key is 5 ([?1;0) (expired=0)
*1694003698.249734 /dev/pts/1: complete key \033[ 0x10000000005b # WRONG!
1694003698.249738 cmdq_append </dev/pts/1>: [server_client_key_callback/0x5616d0e14f90]
1694003698.249741 /dev/pts/1: keys are 4 (?1;0)
1694003698.249743 /dev/pts/1: next key is 4 (?1;0) (expired=0)
1694003698.249746 /dev/pts/1: complete key ? 0x3f
```

This happens in the function `tty_keys_next` of file `tty-keys.c`. This function parses tty sequences (possibly partial) by trying parser functions for each pattern. Two tty sequences in the problem (`\033[[>0;10;1c` and `\033[P>|Wez...fa2`) have been successfully parsed by functions `tty_keys_device_attributes` and `tty_keys_device_attributes2` respectively. But with the current implementation they return `-1` indicating failure rather than `0` complete or `1` partial on the occasions. (checked by adding debugging messages) The reason is that they both return early when they have parsed any sequence successfully at least once (`TTY_HAVEDA` or `TTY_HAVEDA2` set in `tty->flags`). So, for some reason, by terminal happened to send the sequence multiple times and tmux rejected them by stopping parsing them.

I don't know why should they be ignored after the first arrival. But IMHO, they should be able to parse the sequences no matter what and may reject applying utilizing the info. The following change would allow it. By moving the early return statement below the parsing routine, the parser function will recognize and parse the tty key even after its first successful, yet returning before the actual application of the retrieved info.
```
@@ -1274,8 +1287,6 @@ tty_keys_device_attributes(struct tty *tty, const char *buf, size_t len,
        char             tmp[128], *endptr, p[32] = { 0 }, *cp, *next;

        *size = 0;
-       if (tty->flags & TTY_HAVEDA)
-               return (-1);

        /* First three bytes are always \033[?. */
        if (buf[0] != '\033')
@@ -1314,6 +1325,11 @@ tty_keys_device_attributes(struct tty *tty, const char *buf, size_t len,
                        break;
        }

+       if (tty->flags & TTY_HAVEDA) {
+                log_debug("%s: received primary DA %.*s", c->name, (int)*size, buf);
+               return (0);
+        }
+
        /* Add terminal features. */
        switch (p[0]) {
        case 62: /* VT220 */
```

If I compile with this change, the aforementioned problem vanishes and everything works fine. I've been using this fixed version for a week and no crashes/bugs on this change have been found. Is this change OK to do? Is there a reason behind rejecting repeated certain types of tty sequences? If OK, I'd like to make a pull request for this. :)

The solution suggested in [WSL issue #5931](https://github.com/microsoft/WSL/issues/5931) changes the time duration to wait for the next sequence when the sequence is partial. If it is set to 0 it will definitely reject sequences that are cut by packet border (if remote). Even though it's not set to 0, the early return statement still raises the problem when the sequence is sent more than once. I experience this with both Windows terminal and WezTerm, so would not be a problem for WezTerm itself.

I did this with the latest commit on the master branch. (e26356607e38cbb4676a7c91815ae2d5734443c3)

### Required information

* tmux version: tmux next-3.4
* platform: Linux x86_64
* $TERM inside: screen-256color
* $TERM outside: screen-256color
* related log from tmux is included above

**Comment by nicm** [comment]
Or maybe it is not sending it twice but instead taking more than five seconds to send it, but without any logs I can only guess...

**Comment by bivoje** [comment]
Thanks for the reply! Didn't think about tmux forwarding the sequences to the application. I'll check why is it sent multiple times. By the way, the log snippet included is a continuous part of a single log file; so I believe the sequence do be sent more than once.
