### ISSUE TITLE
Using tmux's "send-keys" Command, to Automate an Interactive Program

### ISSUE THREAD

**Issue by spaceman5** [tmux/tmux#3686]
Hi

Thank you very much for creating tmux.

I have a small idea that came up after using the **send-keys** command.

The send-keys command can send keys to any Window/Pane,
and if there's an Interactive program there that is running, it can automate it.

Now generally, in Linux, programs have a rich set for Command Line parameters that can help us automate the program,
but there may be a situation where we need to do something and maybe the program does not offer a command line option for that.

So the  send-keys command can be used to control the program, when it's running.

Now there's only one thing that is needed:
Can tmux somehow also **read characters** from the screen (at a specified location)?

For example:
- **read-char**, for reading a single char, at location (Y,X)
and
- **read-string**, for reading a string, at location (Y1,X1)-(Y2,X2)

Is that possible?

Thank you very much

**Comment by krader1961** [comment]
See the `capture-pane` command.

**Comment by spaceman5** [comment]
This is terrific,
exactly what I was looking for.

Thank you so much.
