### ISSUE TITLE
INPUT_CSI_REP does not works with non ASCII chars

### ISSUE THREAD

**Issue by ceccopierangiolieugenio** [tmux/tmux#3687]
### Issue description
tmux v:3.2a

The **REP** escape code:
```
    # CSI Ps b  Repeat the preceding graphic character Ps times (REP).
```
Does not works if the character used is not ASCII

**Expected result**:
 - Terminator:
![image](https://github.com/tmux/tmux/assets/8876552/57bc2cf0-6b22-4842-bc31-7d853b8eb92c)
 - Xterm:
![image](https://github.com/tmux/tmux/assets/8876552/67705dbf-4ebb-431d-8f5a-ebffe93ef227)

**Actual result**:
- ![image](https://github.com/tmux/tmux/assets/8876552/e85d3c59-192f-4dc0-b7fb-bda664b60dfc)
 - Using an ascii char:
![image](https://github.com/tmux/tmux/assets/8876552/8848287d-ec7a-48e7-afda-0f3ee7bac188)

### Required information

```
 $ uname -sp && ./tmux -V && echo $TERM
Linux x86_64
tmux 3.3a
xterm-256color
```

**Comment by nicm** [comment]
This fixes it, although I'm not entirely convinced it is worth it: [x.diff.txt](https://github.com/user-attachments/files/16487068/x.diff.txt)

**Comment by ceccopierangiolieugenio** [comment]
Thanks @nicm 
Do you know if this fix will be included in the official release?

I am asking because I am using it to speedup the rendering process of:
https://github.com/ceccopierangiolieugenio/pyTermTk
But it is currently disabled because it cause glitches on tmux.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
