### ISSUE TITLE
clipboard integration (OSC-52) appears suddenly broken in tmux 3.3a, fixed on master

### ISSUE THREAD

**Issue by aktau** [tmux/tmux#3691]
NOTE: This issue is somehow fixed on master, but I can't figure out which commit fixed it. Bisecting doesn't work properly due to the (odd?) merge commits. I'm likely holding `git-bisect` wrong, can anyone guide me? Ideally I'd have some help bisecting this to find the fix/culrpit and ask Debian to cherry-pick it. If not, a workaround for 3.3a would also be appreciated. As detailed below, it would probably work if I could force the TTY to use for OSC-52 operations to `$SSH_TTY`.

### Issue description

I used to have `set -g mouse on` and `set -g set-clipboard on`, and successfully used this to send whatever I selected to my local clipboard. I use a Chromebook, and the "Terminal" app to connect to a remote host over SSH (its builtin, AFAIK OpenSSH with NaCL), the terminal emulator is hterm. Since 1-2 weeks (was on holiday), this no longer works. When I'm outside of tmux, a command like:

```
$ printf "\033]52;c;Y29weXBhc3RhIQ==\a\n"
```

Works, successfully setting the clipboard. But inside of tmux, neither the command works (somewhat expected, as AFAIK tmux intercepts this sort of control codes), nor does any attempt at making tmux send data to my terminal emulator via OSC-52 term-codes. So I started to investigate.

> NOTE: I suspect nothing changed at tmux side. I run Debian testing and the last package upgrade was  more than a month ago, when it was definitely still working [1]. Perhaps it's an ncurses thing, as it fits the date range:
> 
> ```
> $ ( cd /var/log ; zcat dpkg.log.*.gz ; cat dpkg.log.1 dpkg.log ) | grep ncurses-term | grep upgrade
> 2023-04-13 10:40:42 upgrade ncurses-term:all 6.3+20221224-2 6.4-1
> 2023-09-07 00:47:44 upgrade ncurses-term:all 6.4-4 6.4+20230625-1
> ```
>
> Very mildly suspect changes (according to me) from https://invisible-island.net/ncurses/NEWS.html.
>
> - add/use bracketed+paste to help identify terminals supporting this xterm feature (prompted by discussion with Bram Moolenaar) -TD
> - change RV to XR/xr, to avoid conflict with pre-existing usage in vim, to use RV/rv to denote DA2 and its response (discussion with Bram Moolenaar) -TD
> - add XF flag to xterm+focus so that termcap applications can be aware of terminals which may support focus in/out -TD
> - use xterm+focus in xterm-p370 and tmux -TD
> - add mode 1004 to xterm+sm+1006 from xterm 380  -TD

Tmux does recognize the terminal as OSC-52 capable

```
$ tmux display -p '#{client_termfeatures}'
bpaste,ccolour,clipboard,cstyle,focus,RGB,title
```

But I **can** get it to work from inside tmux, by printing to a different TTY. The clue which got me somewhere was hidden in this article: https://medium.com/free-code-camp/tmux-in-practice-integration-with-system-clipboard-bcd72c62ff7b.

```
$ printf "\033]52;c;Y29weXBhc3RhIQ==\a\n"
(works)
[TMUX] $ printf "\033]52;c;Y29weXBhc3RhIQ==\a\n"
(doesn't work)
[TMUX] $ printf "\033]52;c;Y29weXBhc3RhIQ==\a\n" > $SSH_TTY
(works)
$ echo $SSH_TTY
/dev/pts/5
$ tmux list-panes -F "#{pane_active} #{pane_tty} #{client_tty}"
1 /dev/pts/0 
0 /dev/pts/1 
```

Side note: I'm not sure why `#{client_tty}` is empty here. At any rate: could I somehow force tmux to set OSC-52 commands to a /dev/ptsX of my choosing?

### Required information

* tmux version (`tmux -V`).
tmux 3.3a

* Platform (`uname -sp`).
Linux

* $TERM inside and outside of tmux (`echo $TERM`).

  - Outside: xterm-256color (it's actually hterm, I've tried hterm-256color as the outer term with the same result)
  - Inside: tmux-direct (I've tried tmux-256color with the same effect)

* Logs from tmux (`tmux kill-server; tmux -vv new`).

[1]: 

```
{ zcat dpkg.log.*.gz ; cat dpkg.log.1 dpkg.log } | grep tmux | grep 2023
2023-07-10 23:18:49 upgrade tmux:amd64 3.3a-3 3.3a-4
2023-07-10 23:18:49 status half-configured tmux:amd64 3.3a-3
```

**Comment by aktau** [comment]
I tried manually bisecting, as I thought I could get the better of these build failures, runtime crashes (nul deref?) and missing-files-on-non-merge commits. But I was wrong. Feel free to close this issue, I think I'll give up and live at HEAD for a while.

**Comment by nicm** [comment]
This is probably https://github.com/tmux/tmux/issues/3531 and your ncurses does not have tiparm_s but the tmux has been patched not to crash.

**Comment by aktau** [comment]
That issue explains the crashes that I observed while bisecting, but it doesn't really explain why it "doesn't work" (without crashing) on my Debian tmux 3.3a.
