### ISSUE TITLE
Suggestion: Revisiting mouse wheel scrolling behavior

### ISSUE THREAD

**Issue by zalza** [tmux/tmux#3692]
### Issue description

First of all, I'm sorry for revisiting this recurring subject which bothers @nicm.
I want to modify some default key bindings to make the mouse wheel on tmux panes behave like some terminal emulators such as
gnome-terminal, mintty, terminator, etc.

| Current behavior  | Alternate screen on                                            | Alternate screen off                          |
|-------------------|----------------------------------------------------------------|-----------------------------------------------|
| Mouse support on  | send mouse event (vim with “set mouse=a” / htop / less –mouse) | send mouse event (are there any useful apps?) |
| Mouse support off | no op                                                          | no op                                         |

| Suggested behavior | Alternate screen on                                                                       | Alternate screen off |
|--------------------|-------------------------------------------------------------------------------------------|----------------------|
| Mouse support on   | send mouse event (vim with “set mouse=a” / htop / less –mouse)                            | no op                |
| Mouse support off  | send up/down arrow keys (vim with “set mouse=” / man / less): is it harmful for any apps? | no op                |

With this change, `vim`, `less` and `man` in tmux panes are scrollable out of the box regardless of mouse support.
Although @nicm didn't seem to like this idea (https://github.com/tmux/tmux/issues/1333#issuecomment-386371456),
this change would help tmux newcomers like me not wandering around web for searching how to configure their `~/.tmux.conf` to make the scroll behavior similar to their terminal emulator's behavior.

Here is my `~/.tmux.conf`:
```
set -g mouse on
#set -s set-clipboard on  # if your terminal supports OSC 52 clipboard feature
set -s copy-command 'xsel && xsel -o | xsel -b'  # else use X11 clipboard

# Main suggestion
bind-key -n WheelUpPane {
  #select-pane  # this should be consistent with the minor suggestion below
  if-shell -F '#{alternate_on}' {
    if-shell -F '#{mouse_any_flag}' {
      send-keys -M  # vim with "set mouse=a" / htop / less with mouse support e.g. "LESS='--mouse --wheel-lines 5' less"
    } {
      send-keys -N5 Up  # vim with "set mouse=" / man / less without mouse support
    }
  } {
    copy-mode -e
    send-keys -N5 -X scroll-up
  }
}
bind-key -n WheelDownPane {
  #select-pane
  if-shell -F '#{alternate_on}' {
    if-shell -F '#{mouse_any_flag}' {
      send-keys -M
    } {
      send-keys -N5 Down
    }
  }
}

# Minor suggestion
# By removing 'select-pane' command from the default implementation, scrolling wheel on a pane does not make the pane active anymore.
# This behavior is in line with common windowing systems, where an inactive window is scrollable without getting focused.
bind-key -Tcopy-mode WheelUpPane {
  #select-pane
  send-keys -N5 -X scroll-up
}
bind-key -Tcopy-mode WheelDownPane {
  #select-pane
  send-keys -N5 -X scroll-down
}
bind-key -Tcopy-mode-vi WheelUpPane {
  #select-pane
  send-keys -N5 -X scroll-up
}
bind-key -Tcopy-mode-vi WheelDownPane {
  #select-pane
  send-keys -N5 -X scroll-down
}
```

This implementation is a simplified version from the reference below.
It seems to work well without checking `pane_in_mode` variable, which is used in other implementations.

Even if this suggestion is not accepted as default implementation,
people who want this scrolling behavior can use the key bindings above in their `~/.tmux.conf`.

### Required information
* tmux version (`tmux -V`) : `next-3.4` (the lateset commit f68d35c52962c095e81db0de28219529fd6f355e)
* Platform (`uname -sp`) : `Linux x86-64` (Ubuntu 22.04.3)
* $TERM inside and outside of tmux (`echo $TERM`): Outside = `xterm-256color` / Inside = `tmux-256color`
* `vim`: 8.2.3995-1ubuntu2.11
* `less`: 590-1ubuntu0.22.04.1 
* `htop`: 3.0.5-7build2

### Reference
- https://www.reddit.com/r/tmux/comments/tqmyzm/snippet_better_scrolling
- https://github.com/tmux/tmux/issues/1610
- https://github.com/tmux/tmux/issues/1333
- https://github.com/tmux/tmux/issues/1320

**Comment by nicm** [comment]
I don't like this feature so I don't want it to be enabled by default.
