### ISSUE TITLE
Feature request , pane names for select-pane -T 'newName

### ISSUE THREAD

**Issue by freddieventura** [tmux/tmux#3693]
Hi,

This is not an issue rather a feature request (which I dont know if it exactly goes here)

So as per newer versions of tmux, we have got the ability to change the height of the status bar , making it span more than 1 line height, such as

`set-option -g status 2`

1st feature request) , the ability to distribute the whole status bar on these new-lines , seems that adding 3 lines height , the remaining lines from the 2nd one are just for padding.
So a comprehensive way to code an customize the status bar with these new lines. (so for instance if we have a big session with loads of windows opened , maybe the window names wont fit on the status bar, making it span 2 lines height even 3 would be awesome)

2nd feature request) as when setting status bar height 2 , looks like the second line shows an abstract of the current panes that exists within a window. They are show in the following format 
0 [199x55] 1 [49x55] etc...

Seeming that there is no `rename-pane` option such as `rename-window` , the trick to get pane names is to
`select-pane -T 'newName'`
And this pane Name can be shown when using the following 
```
set -g pane-border-status top
set -g pane-border-format " [ ###P #T  ] "
```

(when using that pane-border parameter)

So it would be nice to embed that to the second line of the status bar.

Or make a plugging that can do this.

Thank you

**Comment by nicm** [comment]
Change your `status-format[1]` to include `#{pane_title}`?

**Comment by freddieventura** [comment]
Your answer is in the right direction.

Ok I can get  the current pane index and name on the status bar by doing
```
set-option -g status 2
set-option -g status-format[1] "###P #T"
```

But how do I get a list of all them available for that window?

```
set-option -g status-format[1] "#{pane[0]} ###P #T #{pane[1]} ###P #T "
```

I know this doesnt work , but you get my idea?

**Comment by nicm** [comment]
Look at what the default does...

**Comment by freddieventura** [comment]
Yeah I was thinking.
Where can I look at thatone? Is it in the codebase? Any commands to check it?

**Comment by freddieventura** [comment]
Capito :D
```
:show -g status-format[1]
status-format[1] "#[align=centre]#{P:#{?pane_active,#[reverse],}#{pane_index}[#{pane_width}x#{pane_height}]#[default] }"
```

**Comment by freddieventura** [comment]
set-option -g status-format[1] "#[align=centre]#{P:#{?pane_active,#[reverse],}#{pane_index}[#{pane_title}]#[default] }"

Is a good way to get the functionality I was looking for
