### ISSUE TITLE
Documented "next/previous-prompt" default bindings don't exist  

### ISSUE THREAD

**Issue by zach-is-my-name** [tmux/tmux#3696]
tmux next-3.4
commit: 9f9156c0303ad9c50fd44e0561ef0f5bb21a418b
Linux x86_64

I'm trying to get "next/previous-prompt" to work because I think it is a stellar feature for any interactive workflow.  This issue contains several sub-issues related to this feature:

1.) Documented "next/previous-prompt" default bindings are not actually set.  From man page:
    

```
 next-prompt (vi: C-n) (emacs: C-n)
             Move to the next prompt.

previous-prompt (vi: C-p) (emacs: C-p)
             Move to the previous prompt.
```
Steps to reproduce:
1.)Start tmux `[~/Github/tmux]$ ./tmux -f /dev/null`
2.) ctrl-b :
3.) :list-keys
4.) search down: /next-prompt -> no results

Issue 2.) (Included because it's brief):
"next/previous-prompt" seem to be documented twice.  From the man pages again you have the commands as I listed them before:

```
next-prompt (vi: C-n) (emacs: C-n)
             Move to the next prompt.

previous-prompt (vi: C-p) (emacs: C-p)
             Move to the previous prompt.
```
             
But also above that they're defined separately:

```
```next-prompt [-o]
             Move to the next prompt.

previous-prompt [-o]
             Move to the previous prompt.
```
```

  Note: the -o flags for these commands are documented directly below the former pair.

**Comment by nicm** [comment]
Yes, the ones with the keys were added by mistake at some point. I have removed them. Thanks!
