### ISSUE TITLE
Allow switching tabs by clicking on tab names

### ISSUE THREAD

**Issue by rushiagr** [tmux/tmux#37]
More of a feature request. It would be great if I'm using mouse, and can click on the tab name (e.g. on "2:bash") it opens up that tab if a different tab is opened right now.

**Comment by ntnn** [comment]
`set -g mouse-select-window on`

**Comment by ThomasAdam** [comment]
In tmux 2.0:

set -g mouse on

Which implies clicking the status line.  Or use:

set -g mouse-select-window on

**Comment by rushiagr** [comment]
Oops. Sorry. Thanks :)
