### ISSUE TITLE
opening vscodium exits tmux session

### ISSUE THREAD

**Issue by blueray453** [tmux/tmux#3701]
If I open vscodium, it just kill the tmux session. Here is a screenshot.

![Peek 2023-09-19 23-39](https://github.com/tmux/tmux/assets/855297/f6f83ea5-5571-4dac-b7e1-5bb2e9669140)

I have reproduced it 7/8 times already.

```
$ tmux -V && uname -sp && echo $TERM
tmux 3.3a
Linux unknown
tmux-256color
```

Logs from tmux:

[tmux-client-19214.log](https://github.com/tmux/tmux/files/12665007/tmux-client-19214.log)
[tmux-out-19216.log](https://github.com/tmux/tmux/files/12665009/tmux-out-19216.log)
[tmux-server-19216.log](https://github.com/tmux/tmux/files/12665010/tmux-server-19216.log)

**Comment by nicm** [comment]
tmux does not crash in this log, it exits normally.

**Comment by blueray453** [comment]
I did not give the command to exit. I just opened vscodium. So why does it exit without me telling it to exit?

**Comment by blueray453** [comment]
I want to add something. It might or might not be relevant. 

zsh is my default terminal and it has a function like:

```
function tmux-as-default-terminal() {

  if [ -z ${TMUX} ]
  then
    if tmux list-sessions &>/dev/null ; then
        for i in $(tmux list-sessions -F "#{session_attached} #{session_name}"); do
            if [[ $(echo "$i" | cut -d' ' -f1) -eq 0 ]]; then
                tmux kill-session -t $(echo "$i" | cut -d ' ' -f 2)
            fi
        done
    # tmux
    fi
    tmux
  fi


}

tmux-as-default-terminal "$@"
```
It make sure there is always a tmux session. Is it causing the issue?

**Comment by nicm** [comment]
Something ran the command "kill-session -t 0".

**Comment by blueray453** [comment]
So, is it possible that when i run vscodium, it somehow start a zsh session, which call this function, which in turn kill other tmux sessions?

**Comment by nicm** [comment]
Seems likely but I can only tell you what tmux does, not other programs that I don't use.

**Comment by blueray453** [comment]
Please let me report back to you tomorrow.

**Comment by blueray453** [comment]
Yes the .zshrc was the issue. I have put `notify-send`, there, and when i open vscodium, a notification is set. The solution was to put the following at the top of the .zshrc.

```
if [[ ! -o interactive ]]; then
    return
fi
```
I mean, if the shell is not interactive, then do not run rest of the code.

The following also works:

```
function tmux-as-default-terminal() {
  if [[ -o interactive ]]
  then
    if [ -z ${TMUX} ]
    then
      tmux
    fi
  fi
}

tmux-as-default-terminal "$@"
```

**Comment by krader1961** [comment]
FYI, something about your analysis doesn't make sense. The *~/.zshrc* script is normally only run for interactive shells. Which is why people are surprised when they put statements, such as modifying `PATH`, in that script and those statements are not run for non-interactive shells.

**Comment by blueray453** [comment]
I have used `sudo chsh --shell $(which zsh) $USER`, so zsh is my default shell.

In vscode I have settings like:

```
    "terminal.integrated.profiles.linux": {
        "bash": null,
        "zsh": {
            "path": "/usr/bin/zsh"
        },
        "fish": {
            "path": "/usr/bin/fish"
        },
        "tmux": null,
        "pwsh": null
    },

    "terminal.integrated.defaultProfile.linux": "zsh",
```

something somewhere is triggering the interactive shell. It is not just vscode, some other app (i do not remember now) also used to create this problem. It is interesting to see GUI applications calling interactive shell in the background.

Probably this is why `if status is-interactive` is used in fish shell. I thought it was useless code. Now I see this practice save a lot of headache. I was actually having this problem for a long time now. Earlier i could not reproduce, but this time i was able to reproduce many times so reported.

**Comment by krader1961** [comment]
> Probably this is why if status is-interactive is used in fish shell.

@blueray453 That's because Fish always sources *config.fish* -- for both interactive and non-interactive  Fish shell. Zsh shouldn't be sourcing *.zshrc* if the shell isn't interactive and `[[ -o interactive ]]` should always be true when executed inside *.zshrc*. So I still think you have not identified the real problem and your "fix" isn't doing what you think it is doing.

**Comment by blueray453** [comment]
I could not recreate the bug after using the solution i have mentioned. 

I have sort of large dotfiles with many settings.  I also use some zsh plugins whose codes i am not aware of. 

As I have said, I have put notify-send, in the .zshrc and when i open vscodium, a notification is sent, that means vscodium is calling the .zshrc. it is not quite impossible because vscodium has an interactive shell within it.

Please let me use the machine for a few days. If the issue reappears, I will report back.

**Comment by krader1961** [comment]
@blueray453 Note that programs like Vscodium can run external programs, like Zsh, by attaching their stdin/stdout/stderr file descriptors to pseudo TTYs. Which tricks the shell into thinking they are interactive with a human. That does not change my earlier comments that your "fix" cannot possibly work because, by definition, `[[ -o interactive ]]` is always true for an interactive shell. Which means any Zsh shell that sources *~/.zshrc* will always report true for that test. So you have not correctly identified the cause of your problem and your "fix" does not actually fix the problem.
