### ISSUE TITLE
How to map the Mac command key？

### ISSUE THREAD

**Issue by xhsky** [tmux/tmux#3704]
How to represent mac's command key in tmux?

**Comment by krader1961** [comment]
The Mac command key (in the past it was called the apple key) is known as the hyper (or sometimes meta) key on non-Macs. It is handled by the OS and not visible to Tmux and thus does not have a Tmux representation. See https://github.com/tmux/tmux/wiki/Modifier-Keys.

**Comment by ryan-WORK** [comment]
There are a bunch of good videos that will take you through a setup: https://www.youtube.com/watch?v=DzNmUNvnB04&t=555s

```
# Set the control character to Ctrl+Spacebar (instead of Ctrl+B)
set -g prefix C-space
unbind-key C-b
bind-key C-space send-prefix
```
