### ISSUE TITLE
Opening one display-menu from another one

### ISSUE THREAD

**Issue by raszuk** [tmux/tmux#3706]
I have struggled for over 6h to make this to work with no success. 

I have three menus. From HELP menu I would like to be able to open Menu_1 and Menu_2 respectively. 

No matter what I try the other menus are not opening while in the same time when I escape the HELP menu I can open them without any issues with Ctrl-a and Ctrl-y respectively. 

Is this a known issue or I am doing something wrong here ? 

My HELP menu: 
bind-key -n C-h display-menu -x R -y W -T HELP \
    "    Menu 1  ==> Ctrl-a"          a "send-keys -t 0 C-a" \    
    "    Menu 2  ==> Ctrl-y"          a "send-keys -t 0 C-y" 

I am using tmux 3.3a - There seems to be no -K option there to try it out. 

Many thx in advance !!!

**Comment by raszuk** [comment]
Ok I have compiled 3.4 and -K does exactly what is needed here. But 3.4 is not available in any distribution. 

Is there any workaround ? 

Key question turns out to be: What are you going to promote 3.4 to stable and make it available to be included in distros ?

**Comment by nicm** [comment]
3.4 will probably be quite soon when I have time.
