### ISSUE TITLE
How to use an environment variable named with braces, in a format string?

### ISSUE THREAD

**Issue by pallaswept** [tmux/tmux#3711]
### Issue description

I need to use the environment variable ${0} in a format string. The braces (curly brackets) are tripping me up. I've been unable to find an escape character (I saw a suggestion of using '#' but that did not work). Lil' help, please, anyone?

### Required information

uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 3.3a
tmux-256color

I want to rename my windows automatically, depending on the current activity in the pane. This is presently working very well:

If I am in a bash prompt, then the window is renamed to the working directory (with my home directory substituted to '~', and the length limited to 20 characters so that long paths don't result in excessively long window names

If I am in a command, it shows the working directory (with the same substitution, but this time truncated to 7 characters to make room for the command name), followed by the command name.

This part works great. There's one problem - if the command is run with sudo, then the only command I see in the title is "sudo".

So, I want to conditionally replace the command name, where if it is sudo, then I use the environment variable ${0}, which shows the command being used, ie if I use 'sudo bash' and then echo ${0} then it echoes 'bash'. So I'd like this to be my window title.

All of this works fine, here's a working example, minus the {0} environment variable, and instead using the USER environment variable as a placeholder to show that it does in fact work as intended:

` set-option -g automatic-rename-format '#{?#{==:#{pane_current_command},bash},#{=/-20/…:#{s/#(echo $HOME)/~/:pane_current_path}},#{=/-7/…:#{s/#(echo $HOME)/~/:pane_current_path}}> #{?#{==:#{pane_current_command},sudo},#{USER},#{pane_current_command}}}'`
 
So what I really need would be the same thing with USER replaced with {0}, ie:

` set-option -g automatic-rename-format '#{?#{==:#{pane_current_command},bash},#{=/-20/…:#{s/#(echo $HOME)/~/:pane_current_path}},#{=/-7/…:#{s/#(echo $HOME)/~/:pane_current_path}}> #{?#{==:#{pane_current_command},sudo},#{{0}},#{pane_current_command}}}'`

But because of the braces characters in the variable name, it doesn't work. I tried using unicode characters (doesn't work, just prints the characters rather than expanding the environment variable), I tried setting a tmux internal variable (doesn't work, it sets it once at the time I set the tmux variable and doesn't change its value when the environment variable does) I tried calling echo as a command (doesn't work, fails to expand the variable for unknown reasons):
```

tmux display -pv '#(echo ${0})'
# expanding format: #(echo ${0})
# found #(): echo ${0}
#  expanding format: echo ${0}
#  result is: echo ${0}
# #() result:
# result is:

echo ${0}
-bash
```

Is there any way around this? Sorry if this has been covered but I looked around for days and I've come up blank. Any help would be appreciated. Surely there's some escape character for the braces in a format string? I tried double braces and hashes and all kinds of things, to no avail. That should solve the problem, but I can't find any documentation of such a thing (except the aforementioned hash character, which was in a very old post and may have worked once but now does not)

**Comment by nicm** [comment]
How is tmux going to know what $0 is inside your running shell?

**Comment by krader1961** [comment]
> then I use the environment variable ${0}

That is not an environment variable. It is a regular variable private to the shell. However, that doesn't really matter because if you do `export MY_VAR=value` inside a shell Tmux still can't access the value of `$MY_VAR`. That env var also lives only in the address space of the shell process. When Tmux runs shell commands it creates a new shell process which won't inherit `MY_VAR` because that new shell will have the Tmux server as its parent process, not the shell where you exported `MY_VAR`.

**Comment by pallaswept** [comment]
> How is tmux going to know what $0 is inside your running shell?

The same way `echo` does?
```
echo ${0}
-bash
```

But I guess from what you're saying, is that the child process won't have access to tmux running in its parent, so even if it can expand this variable, it won't be able to export it to tmux?

Anyway, how does one escape curly braces, in a format string?

**Comment by krader1961** [comment]
```
> bash -c 'echo ${0}'
/bin/bash
> cp /opt/homebrew/bin/bash mybash
> ./mybash -c 'echo ${0}'
./mybash
```

> But I guess from what you're saying, is that the child process won't have access to tmux running in its parent, so even if it can expand this variable, it won't be able to export it to tmux?

No. Tmux has no trouble capturing the stdout produced by the shell it spawns in response to evaluating `#()`. The whole point of the `#()` format. The problem is that Tmux spawns a new shell to execute the shell statements between the parenthesis. That shell will have the Tmux server process as its parent. Not the shell (or whatever program) is running inside one of your Tmux windows. And therefore it won't have access to the env vars of the process in that window; even assuming it is a shell and not some other program like Vim. And, as already pointed out the `$0` variable is not an environment variable and would not be exported to the new shell even if things work the way you think they do.

**Comment by pallaswept** [comment]
Thanks for your advice, but I found a way to get it working.

PMA FTW

> ```
> > bash -c 'echo ${0}'
> /bin/bash
> > cp /opt/homebrew/bin/bash mybash
> > ./mybash -c 'echo ${0}'
> ./mybash
> ```
> 

Exactly.

> > But I guess from what you're saying, is that the child process won't have access to tmux running in its parent, so even if it can expand this variable, it won't be able to export it to tmux?
> 
> No

> That shell will have the Tmux server process as its parent. Not the shell (or whatever program) is running inside one of your Tmux windows. And therefore it won't have access to the env vars of the process in that window

So by "no" you mean "yes"?

Anyways I got it working and I'm not sensing a strong attitude toward "how to get this working or at least answer the dude's question about how to escape braces" so much as "how to explain that it can't be done" so I'll just leave this here.

**Comment by krader1961** [comment]
> Anyways I got it working

Care to share your solution? Because your original approach cannot work and it's not obvious how to do what you wanted. Also, escaping the braces would not solve your problem because inside `$()` braces are not special. For example, try this:

```
set-option -g status-right "#[bg=brightcyan] #W #[default] #(echo ${TERM})"
```

**Comment by krader1961** [comment]
Argh! I see my previous comment is incorrect regarding brace expansion inside `#()`. It turns out that Tmux was expanding `{TERM}`. The solution is what you would expect: simply preface the opening brace with a backslash. Try this:

```
set-option -g status-right "#[bg=brightcyan] #W #[default] #(X=z; echo .$\{X}.)"
```

If the backslash is removed the `{X}` expands to the empty string. Regardless, escaping the brace doesn't solve your problem. Try this:

```
set-option -g status-right "#[bg=brightcyan] #W #[default] #(echo .$\{0}.)"
```

You should see "sh" as the rightmost string of your status line.

**Comment by krader1961** [comment]
> Anyways I got it working and I'm not sensing a strong attitude toward "how to get this working or at least answer the dude's question about how to escape braces" so much as "how to explain that it can't be done" so I'll just leave this here.

@pallaswept, Please tell us how you "got it working". I love learning something new. Especially if it invalidates something I used to believe since I always want to increase my knowledge and abandon incorrect beliefs. I think that is true for most people.

**Comment by pallaswept** [comment]
Sorry but after the attitude I copped for just asking I'm not really keen to continue conversation. You had no interest in making it work until you knew I could, you only wanted to shit on me. Sorry but I'm not playing that game.
