### ISSUE TITLE
Question about repeat-time

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#3712]
Under most Operating systems, the keyboard has two confiurable settings for key repeat;, Initial delay, and repeat speed.

I find the `repeat-time` setting has to be higher than the default to overcome the "initial delay", but once you have
it repeats fine.

The downside of having the repeat time set so high, is once you finish resizing a pane for example, you must wait for a second
before pressing the cursor keys for example.  I would often try to press <kbd>Up</kbd> to recall the last bash command, and inadvertently end up triggering the previous-pane binding.

I would like to request the ability to configure initial and repeat delays separately.

The initial delay would apply only after the initial key press, all subsequent presses would be the shorter delay.

A quick read of the code shows you might be able use `c->flags & CLIENT_REPEAT` to identify the initial repeat vs subsequent
repeats. 

eg,
```
set repeat-time 500
set repeat-time-inital 1000
```

I tried implementing a trivial example, but there was an issue where changing which key was being held (like from <kbd>Ctrl-Up</kbd> to <kbd>Ctrl-Down</kbd> wouldn't work unless the initial delay was applied again.  This required remembering the key-code of the last key to detect changes.  I managed this by adding a `keycode last_key` to the client struct, but I'm sure theres a much cleaner way.

Having a shorter repeat-time (300) and a longer repeat-time-initial (900), I've found usablility improved significantly.

I can create a PR for my initial attempt if that would be of value.

Regards

**Comment by nicm** [comment]
I completely missed this issue for some reason, sorry... yes if you have something please open a PR. I think `initial-repeat-time` would be more readable than `repeat-time-initial`.

**Comment by systemmonkey42** [comment]
As suggested, I've create pull request #4164 with the new option name.

I've used this on all my installations of tmux for about a year now, and while I have no problems with it, there is one other problem related to key-repeat handling I havent been able to solve...

Press <kbd>PREFIX</kbd>, press <kbd>UP</kbd>, then press <kbd>UP</kbd> again.  Unless you've waited a while, its going to trigger the repeat-time and move up another pane.
The only "correct" soluition for this is to have the terminal report key-release events.  No exactly a widely supported feature.. (only possible on the console on linux and only by taking over the keyboard)
