### ISSUE TITLE
Tmux Server Exiting Unexpectedly

### ISSUE THREAD

**Issue by SahithiKasim** [tmux/tmux#3713]
The system information is as follows:

Operating System: Linux x86_64
Tmux Version: 3.0a
Terminal Emulation: xterm-256color

After running tmux -vv new, I received the message "server exited unexpectedly."

Expected Behavior:
The Tmux server should start and create a new session without exiting unexpectedly.

Actual Behavior:
The Tmux server exits unexpectedly, and I cannot create a new session.

Logs:
I have attached the log files generated during the execution of these commands, as mentioned in the CONTRIBUTING.md.
[tmux-client-706137.log](https://github.com/tmux/tmux/files/12840139/tmux-client-706137.log)
[tmux-out-706035.log](https://github.com/tmux/tmux/files/12840140/tmux-out-706035.log)
[tmux-server-706035.log](https://github.com/tmux/tmux/files/12840141/tmux-server-706035.log)

**Comment by nicm** [comment]
tmux 3.0a has not been supported for three years. Does this still happen with tmux built from master?

**Comment by SahithiKasim** [comment]
"I'm unsure about it; unfortunately, I couldn't manage to update it. I attempted a reinstallation, but I ended up with the same version."

**Comment by nicm** [comment]
Did you look at https://github.com/tmux/tmux/wiki/Installing#from-version-control?

After you run `make` but before `make install` you should be able to run the new tmux from the source directory with `./tmux`.

Also make sure you have uninstalled any tmux packages before you install so there are no old versions.
