### ISSUE TITLE
Some unicode symbols appear/reappear in editor when moving cursor around in neovim inside tmux

### ISSUE THREAD

**Issue by sdondley** [tmux/tmux#3715]
### Issue description

Unicode symbols created by combining code points can appear/reappear when editing a file containing such symbols while moving the cursor in the file. See animation below:

![Oct-08-2023 16-38-07](https://github.com/tmux/tmux/assets/2506364/31d30eb8-3305-4940-a881-db13952009bf)

Simpler emojis with one codepoint do not have this problem. 

On the same machine, I do not experience this problem when not using tmux.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

tmux next-3.4

* Platform (`uname -sp`).

ID=alpine
VERSION_ID=3.18.2
PRETTY_NAME="Alpine Linux v3.18"

* $TERM inside and outside of tmux (`echo $TERM`).

tmux-256color (inside)
xterm (outside)

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[client.log](https://github.com/tmux/tmux/files/12841754/client.log)
[out.log](https://github.com/tmux/tmux/files/12841755/out.log)
[server.log](https://github.com/tmux/tmux/files/12841756/server.log)

**Comment by nicm** [comment]
It looks like your tmux build is not up to date...

**Comment by sdondley** [comment]
I'm using alpine latest so not sure why. What is "next-3.4"? I'm confused by that. It's not even a tag in the github repo.

But it's funny you just chimed in. I found your comment here: https://github.com/tmux/tmux/issues/632#issuecomment-258790044

I did another Docker build and built tmux from source with utf8proc and fired it up in a container and it works. So, apparently, the version that ships with alpine is not configured for utf8.

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/FAQ#how-often-is-tmux-released-what-is-the-version-number-scheme

**Comment by sdondley** [comment]
OK, thanks.

And I just did another docker build without utf8proc to confirm that was the issue. It appears to be. I created a file with some combined codepoint characters and they were invisible upon reopening the file and I could not get them to show up at all.
