### ISSUE TITLE
pane-border-format updates after some interval when underlying value changes

### ISSUE THREAD

**Issue by Hritik14** [tmux/tmux#3716]
### Issue description

I've the following in my tmux rc file: 
```
set -g pane-border-format "#{pane_index} #{pane_current_command} #{pane_current_path}"
```
but whenever I change my dir with `cd`, the pane_current_path takes a while (5 to 15s) to update.
This is also valid when I change the current command, I tried with a file named ``duration.sh``:
```
for i in {1..100}; do
    echo $i
    sleep 1
done
```
The pane border updated after 11s.

This looks similar to https://github.com/tmux/tmux/issues/1852 as `tmux refresh -S` instantly updates the border.
Eg: 
```
mkdir test && cd test && tmux refresh -S
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.3a
* Platform (`uname -sp`): Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`): Inside: screen-256color, Outside: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`): I can't kill the server rn, pls let me know if this is necessary

**Comment by nicm** [comment]
What's `status-interval` set to?

**Comment by Hritik14** [comment]
@nicm it is set to 1.
You can see in the video, the pane border does not change the directory unless I do a `tmux refresh -S`

https://github.com/tmux/tmux/assets/7457065/5ab36940-9fad-46ef-8b60-2c95141e5140

**Comment by nicm** [comment]
It is fine for me. Does this still happen with master? If so, please show logs.

**Comment by Hritik14** [comment]
It's fixed after I restarted tmux (kill server) and my terminal. thanks!
