### ISSUE TITLE
tmux crashes when closing current session with a single window with multiple panes

### ISSUE THREAD

**Issue by lorentzforces** [tmux/tmux#3717]
### Issue description

Closing a session containing a window with multiple panes crashes tmux (with some specific conditions).

Steps to reproduce:

1. Open a new session in tmux
1. Create a second session
1. In one session, split the window. Do not switch to another session.
1. While in that session, use the `<prefix> w` command to view the window list, and use `x` to close the session.
1. Observe that the entire tmux server crashes, and all other sessions are lost. Tmux's last visual state persists in the terminal.

This specifically seems only to happen under the following conditions:
- a session is closed
- that session has exactly one window in it, which is split into panes
- that session is the currently viewed session

This behavior is NOT seen if the _window_ is killed instead of the _session._

An additional, weird symptom is that when tmux dies in this way, the terminal session the user is returned to has some issues:
- the cursor is invisible
- user input is invisible
- output is mangled in a weird way

Screenshot of `ls` output after tmux dies like this:
![broken-terminal-output-after-tmux](https://github.com/tmux/tmux/assets/25649139/5084afd0-fec9-4528-a08c-0dbde1546f2f)

`bash` version (in case it's relevant): `GNU bash, version 5.2.15(1)-release (x86_64-redhat-linux-gnu)`

### Required information

* tmux version: `tmux 3.3a`
* Platform: `Linux x86_64`
* $TERM
  * inside tmux: `tmux-256color`
  * outside tmux: `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

Attached are logs from a minimal reproduction (no config, server started with `tmux -vv -Ltest -f/dev/null`):
[tmux-client-49107.log](https://github.com/tmux/tmux/files/12843212/tmux-client-49107.log)
[tmux-out-49109.log](https://github.com/tmux/tmux/files/12843213/tmux-out-49109.log)
[tmux-server-49109.log](https://github.com/tmux/tmux/files/12843214/tmux-server-49109.log)

**Note:** tested on MacOS and can reproduce the same issue there.

**Comment by lorentzforces** [comment]
**Note:** I have not yet reproduced with a latest-commit version of tmux. I will attempt to do so tomorrow, and will close this issue if the problem appears resolved in that version.

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by lorentzforces** [comment]
Just confirmed: occurs on latest master as well.

**Comment by nicm** [comment]
Thanks, this fixes it for me:
~~~~
--- window.c    10 Jul 2023 09:24:53 -0000      1.286
+++ window.c    23 Oct 2023 08:11:11 -0000
@@ -340,6 +340,7 @@ window_destroy(struct window *w)
 {
        log_debug("window @%u destroyed (%d references)", w->id, w->references);

+       window_unzoom(w);
        RB_REMOVE(windows, &windows, w);

        if (w->layout_root != NULL)
~~~~
I have applied this to OpenBSD and it will be in GitHub later. Please let me know if you continue to see problems with this change.
