### ISSUE TITLE
`choose-*`er's key bindings

### ISSUE THREAD

**Issue by dkuettel** [tmux/tmux#3718]
I saw https://github.com/tmux/tmux/issues/1846 and https://github.com/tmux/tmux/pull/1848 .

From what I understand, the key bindings for `choose-*` are unified and not customizable. The original reason above did not convince `tmux` to make or allow a change. Can we revisit this considering people that dont have a qwerty layout? On, eg, colemak, the defaults are off. It seems to me the terminal folks are often into optimizing their tools.

What's your take on this? An alternative is to have people use a third-party tool to replace the `choose-*`ers?

### Required information

Please provide the following information:

* tmux version (`tmux -V`) `next-3.4`
* Platform (`uname -sp`) `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`) `tmux-256color` and `alacritty`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
I don't have any plans to change the key bindings. You can change the shortcut keys using `-K`.
