### ISSUE TITLE
Hook `window-layout-changed` not documented in man page?

### ISSUE THREAD

**Issue by clarkwang** [tmux/tmux#3719]
[q]: https://unix.stackexchange.com/q/533709/29039

### Issue description

Found a stackexchange question [Show tmux pane-status only when there is more than one pane in window][q] and it's using hook `window-layout-changed`. I tried and it really worked but I did not find this hook in `man tmux`. 

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

  3.3a

**Comment by nicm** [comment]
The reason this was missed is it is also a control mode notification (`%layout-change`). I think maybe it was renamed and used to be covered by the "all control mode notifications are also hooks"... I've added it separately as well, thanks!
