### ISSUE TITLE
We need a feature to take the place of ‘monitor-content’

### ISSUE THREAD

**Issue by mamin506** [tmux/tmux#372]
‘monitor-content’ is a useful feature in my daily job. I can use it to check if my progress output some specified messages and alert me. monitor-activity + monitor-silence is not enough.

I saw your TODO. You are planning to improve "monitor-*" option. But, I want to know if you are considering bring the 'monitor-content' back? Thanks for  your great job. :)

**Comment by ThomasAdam** [comment]
Something will happen at some point.  I know it's in the TODO.

**Comment by wernight** [comment]
Why close this issue then? I'd be useful for people tracking this feature.

**Comment by ThomasAdam** [comment]
Because no one's working on it right now, and having this issue open isn't helping.  That's now how we work on new features, either.

**Comment by wernight** [comment]
Ok, then just for reference there is this Stackoverflow answer that'll probably need updating if someone works on it. https://stackoverflow.com/questions/23755063/alert-in-tmux-when-a-process-completes/34153396
