### ISSUE TITLE
Carriage returns in tmux.conf cause errors

### ISSUE THREAD

**Issue by rex-ludorum** [tmux/tmux#3720]
### Issue description

I recently duplicated my Ubuntu tmux setup to Windows 10 on msys2, and I found that the carriage returns git added to my ~/.config/tmux/tmux.conf were causing errors. For reference, here is my tmux.conf:
```
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
set -g mouse on
set -g repeat-time 300
# 256 color support
set -g default-terminal "screen-256color"
```

This is fixed by dos2unix or removing the CRs, but it would be nice to have tmux properly recognize them so that my files can be consistently formatted on Windows.

### Required information
* tmux version (`tmux -V`).
3.3a
* Platform (`uname -sp`).
MINGW64_NT-10.0-22621 unknown
* $TERM inside and outside of tmux (`echo $TERM`).
outside: xterm-256color, inside: screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-1840.log](https://github.com/tmux/tmux/files/12888906/tmux-client-1840.log)
[tmux-out-1842.log](https://github.com/tmux/tmux/files/12888907/tmux-out-1842.log)
[tmux-server-1842.log](https://github.com/tmux/tmux/files/12888908/tmux-server-1842.log)

**Comment by nicm** [comment]
Does this work? [x.diff.txt](https://github.com/tmux/tmux/files/12905190/x.diff.txt)

**Comment by rex-ludorum** [comment]
I made the changes in Ubuntu since I had trouble on Windows, but the issues weren't fixed. I attached my logs.
[tmux-out-20497.log](https://github.com/tmux/tmux/files/12913881/tmux-out-20497.log)
[tmux-client-20495.log](https://github.com/tmux/tmux/files/12913882/tmux-client-20495.log)
[tmux-server-20497.log](https://github.com/tmux/tmux/files/12913883/tmux-server-20497.log)

**Comment by nicm** [comment]
Try this please:

[y.diff.txt](https://github.com/tmux/tmux/files/12914294/y.diff.txt)

**Comment by rex-ludorum** [comment]
That did the trick. Thanks!

**Comment by nicm** [comment]
I've applied this now (to OpenBSD, will be in GitHub later) and will see how it goes. Thanks!
