### ISSUE TITLE
C-S-/ (C-?) recognized outside of tmux but not inside tmux

### ISSUE THREAD

**Issue by cpoile** [tmux/tmux#3721]
### Issue description

I'm using iTerm2 with CSI u mode. Using `printf '\033[>4;1m'` and `cat`:
- Only using iTerm2: pressing `C-/` sends `^[[47;5u`, `C-S-/` sends `^[[63;5u`.
- Inside tmux: pressing `C-/` sends `^[[47;5u`, `C-S-/` acts like backspace was pressed (deletes the u from the previous code). 
- Looking at the logs it looks like tmux sees the correct key code and sends it, but I'm not certain.

- I've tried setting tmux's term to screen-256color, tmux-256color, xterm-256color, all with the same results. 
- I've tried with no `.tmux.conf` and with the one I've attached below (with passthrough, extended keys, etc.).
- I've tried with a bare bash shell, no bashrc, same result as above.

Thanks for any help!

Edit: just tried on a fresh compile from master, and it has the same problem. I wouldn't be surprised if it's something in my setup, please let me know if you can think of anything else to test.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

tmux 3.3a

* Platform (`uname -sp`).

Darwin arm

* $TERM inside and outside of tmux (`echo $TERM`).

- outside tmux (in iTerm2): xterm-256color
- inside tmux: tmux-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).

This is from me starting the server, typing `hello!\r` and: `C-/ C-/ C-S-/ C-S-/` then detaching and killing the server.

[tmux-client-20792.log](https://github.com/tmux/tmux/files/12907643/tmux-client-20792.log)
[tmux-out-20794.log](https://github.com/tmux/tmux/files/12907644/tmux-out-20794.log)
[tmux-server-20794.log](https://github.com/tmux/tmux/files/12907645/tmux-server-20794.log)
[tmux.conf.zip](https://github.com/tmux/tmux/files/12907658/tmux.conf.zip)

**Comment by nicm** [comment]
Does this fix it? I can't get iTerm2 to generate CSI u with `\033[4;1m` anymore...

[x.diff.txt](https://github.com/tmux/tmux/files/13067527/x.diff.txt)

**Comment by MohamedOsman1998** [comment]
I have the same exact issue, it used to work on version 3.0 but broke on updating to 3.2 and also 3.3a. I am using wezterm to pass the keys.
