### ISSUE TITLE
Problem recreate pane

### ISSUE THREAD

**Issue by lars44** [tmux/tmux#3724]
Version tmux 3.3a
Platform: Debian 12
screen-256color

### Issue description
I get an error when I want to recreate all panes incl. the ssh scripts that log in to different places.
Command C-a C-r loads all panes but without scripts.
Command C-a R shows:
#### /root/.tmux/resurrect/last:1: unknown command: pane

The last part in .tmux.conf looks like this:

resurrect_dir="/root/.tmux/resurrect"
set -g @resurrect-dir $resurrect_dir
set -g @plugin '/root/.tmux/plugins/tmux-resurrect'
set -g @plugin '/root/.tmux/plugins/tmux-continuum'
set -g @plugin '/root/.tmux/plugins/tmux-sensible'

bind-key R source-file /root/.tmux/resurrect/last
run-shell '/root/.tmux/plugins/tpm/tpm'

What do I need to change or add to get the correct function?
Thanks for all the help.

**Comment by nicm** [comment]
Sorry, you will need to ask whoever wrote the scripts that you are using.

**Comment by lars44** [comment]
I'm sorry. Not so good in English.
What I am referring to is not a real script.
I'm only referring to a command like "ssh -p2222 server2"
and also "ssh -p2222 server3" to connect to these servers in separate windows.

**Comment by nicm** [comment]
Try asking here: https://github.com/tmux-plugins/tmux-resurrect
