### ISSUE TITLE
Environment variables set in `if-shell` have unexpected behaviour

### ISSUE THREAD

**Issue by casr** [tmux/tmux#3725]
### Issue description

Environment variables set in `.tmux.conf` are set to the last assignment regardless of the outcome of the `if-shell` block. I've tested this with and without `%hidden` but still get similar results. In the example below, 'blue' is always set, regardless of if the wall clock is between 0-30 seconds.

```
if-shell '[ $(date +%S) -gt 30 ]' {
	%hidden status_bg=red
} {
	%hidden status_bg=blue
}

set-option -g status-style bg=$status_bg
```

### Required information

Please provide the following information:

* tmux version: `tmux 3.3a`.
* Platform: `Darwin arm`.
* $TERM: inside `tmux-256color`, outside `xterm-256color`.

**Comment by nicm** [comment]
Correct, `%` commands are evaluated when the configuration file is parsed and `if-shell` whn it is executed. Your file is equivalent to:

%hidden status_bg=red
%hidden status_bg=blue
if-shell '[ $(date +%S) -gt 30 ]' {} {}
set-option -g status-style bg=$status_bg

You need to use either `%if`/`%hidden` or `if-shell`/`setenv`.

**Comment by casr** [comment]
Thanks for explaining that. I've had a try with both options but struggling to make it work for me.

This one will always set it to blue:
```
%if "#{>:#(date +%S),30}"
%hidden status_bg=red
%else
%hidden status_bg=blue
%endif

set-option -g status-style bg=$status_bg
```

I am unable to access to the environment variable for this one:
```
if-shell '[ $(date +%S) -gt 30 ]' {
	setenv -hg status_bg red
} {
	setenv -hg status_bg blue
}
set-option -g status-style bg=$status_bg
```

**Comment by nicm** [comment]
In the first, you can't use #() with %if. But IIRC you may be able to just use %S directly.

And in the second, $status_bg is also evaluated when the file is parsed. You will need to do #{status_bg} (may need -F).

**Comment by casr** [comment]
> you may be able to just use %S directly

Perhaps! I was using the `date` command was a placeholder for a local command I want to use.

Otherwise... `-F` did the trick! Here's the working version:
```
if-shell "[ $(date +%S) -gt 30 ]" {
	set-environment -hg status_bg red
} {
	set-environment -hg status_bg blue
}

set-option -Fg status-style "bg=#{status_bg}"
```

For others that might come across this, it's important to wrap the `bg=` part within the quotes too.

Thanks for the help!
