### ISSUE TITLE
Sixel not displaying specific image.

### ISSUE THREAD

**Issue by niksingh710** [tmux/tmux#3726]
### Issue description

![image](https://github.com/tmux/tmux/assets/60490474/285063d6-b31d-46f6-938c-f12d35efe59c)

tmux unable to display this image others work fine.
tried with commands:

`chafa -f sixels img.png`
`convert img.png sixel:-`
`img2sixel img.png`

### Required information

Please provide the following information:

* tmux version (tmux next-3.4).
* Platform (Arch).
* $TERM inside and outside of tmux (tmux-256color).

**Comment by nicm** [comment]
No logs.

**Comment by niksingh710** [comment]
> No logs.

https://gist.github.com/niksingh710/7b8553bdcf3939a80fa5c0886f5257b0

**Comment by niksingh710** [comment]
> The image is too big, the maximum is 1 MB.

Is there any option in tmux config by which i can increase this size?

**Comment by shiny-comic** [comment]
@niksingh710 It is not an option, but you can raise the limit by changing INPUT_BUF_LIMIT in input.c then compile.
[Reference](https://github.com/tmux/tmux/issues/3668#issuecomment-1689540241).
