### ISSUE TITLE
Advertise sixel support via XTSMGRAPHICS and maybe DA1

### ISSUE THREAD

**Issue by rockorager** [tmux/tmux#3727]
### Issue description
tmux recently gained sixel support (dfbc6b1888c110cf0ade66f20188c57757ee1298). tmux should advertise support for sixels to applications via a response to XTSMGRAPHICS (documented [here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html), and consider a change to the DA1 response.

An application will query the terminal with a request for the sixel graphics geometry:

```
\x1B[?2;1;0S
```

tmux should respond with the pixel size of the addressable screen

```
\x1B[?2;0;1920;1080S
```

Also, ideally this would be advertised in the DA1 response, but tmux responds with `\x1B[?1;2c`, which is a form that does not technically allow for parameters. Perhaps tmux can advertise itself as a VT125 (not sure what features it's missing to do so?) and could instead respond with `\x1B[?12;4;22c` (VT125 with sixel and RGB support)?

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux next-3.4

* Platform (`uname -sp`).
Linux unknown (arch, btw)

* $TERM inside and outside of tmux (`echo $TERM`).
Inside: tmux-256color
Outside: foot

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[server exited]

**Comment by nicm** [comment]
tmux already adds this to DA1. If you want any more XTGRAPHICS please open a PR.

**Comment by rockorager** [comment]
Ah I see it now, my build didn't actually have sixels in it. Running `configure --enable-sixel` if you've previously run `configure` doesn't result in a build with sixel support. Thanks!

I tried to confirm with `notcurses-info` as well, and it's hanging. I suspect it's an issue in the notcurses DA1 parser. I'll open an issue over there.

**Comment by rockorager** [comment]
> tmux already adds this to DA1. If you want any more XTGRAPHICS please open a PR.

What do you think about altering the DA1 response depending on the underlying terminals' support for sixels? I can submit a PR for this if you are ok with doing this.

The upside is that modern libraries are checking for support, and falling back to more primitive images (see notcurses) when sixel support isn't detected. Without a dynamic response based on the underlying terminal, any fallback breaks since the application thinks it can display sixels.

Let me know!

**Comment by nicm** [comment]
That can't work because you could start with a terminal that supports it and then later attach to a terminal that does not.

**Comment by rockorager** [comment]
The implementation I have is working if you detach and then later attach with a different terminal. However, if both terminals simultaneously are connected then you get two DA1 responses (one with sixel support, one without).

**Comment by rockorager** [comment]
I guess the correct way would be make sure _all_ connected clients support sixel, otherwise none do.

How about that?

**Comment by nicm** [comment]
But how do applications know they are meant to send the request again to get a new response?

You can't send two responses, that'll just confuse everything.

**Comment by nicm** [comment]
The problem is that applications may only check for SIXEL on startup so tmux needs to do something sensible if they send a SIXEL even if the terminal it is now attached to does not support them.

**Comment by rockorager** [comment]
Yeah, I hadn't considered the case where the application that requested DA1 is the one still running, nothing you can do there.
