### ISSUE TITLE
Printing certain glyphs reliably triggers a crash

### ISSUE THREAD

**Issue by Seirdy** [tmux/tmux#3729]
### Issue description

Printing certain characters crashes the tmux server. To reproduce, run the following command in a Tmux session:

```sh
curl -sS https://seirdy.one/pb/crash-tmux.txt
```

The issue does not appear on tmux 3.3a, but does appear on the latest git build and in Fedora 39; rpm reports the release as `5.20230918gitb202a2f.fc39`.

Logs a re attached:

[tmux-client-3074535.log](https://github.com/tmux/tmux/files/13206997/tmux-client-3074535.log)
[tmux-out-3074537.log](https://github.com/tmux/tmux/files/13206998/tmux-out-3074537.log)
[tmux-server-3074537.log](https://github.com/tmux/tmux/files/13206999/tmux-server-3074537.log)

### Required information

- tmux version: 3.4-next
- Platform: Linux unknown (Fedora 39). [Another user reproduced it in Arch](https://fedi.ioangogo.dev/objects/7a28ca48-a928-4a94-8641-e37b76ccf095) from Git.
- TERM: tmux-256color, in both foot and alacritty.

**Comment by Seirdy** [comment]
Attaching the plaintext file containing the offending glyphs; a simple `cat` should trigger a crash.

[crash-tmux.txt](https://github.com/tmux/tmux/files/13207061/crash-tmux.txt)

**Comment by nicm** [comment]
This character is too long and the check for that appears to have gone missing. I have fixed this in OpenBSD and it will be in GitHub later. Thanks!

Here is the change:
~~~~
--- screen-write.c      23 Oct 2023 08:12:00 -0000      1.223
+++ screen-write.c      30 Oct 2023 16:04:52 -0000
@@ -2025,6 +2025,10 @@ screen_write_combine(struct screen_write
                        return (0);
        }

+       /* Check if this combined character would be too long. */
+       if (last.data.size + ud->size > sizeof last.data.data)
+               return (0);
+
        /* Combining; flush any pending output. */
        screen_write_collect_flush(ctx, 0, __func__);

**Comment by Seirdy** [comment]
Thank you so much. It was giving me a lot of trouble because it was part of someone's Fediverse display name, causing crashes whenever I browsed from the CLI and TUI.
