### ISSUE TITLE
tmux doesnt respect config setw -g mode-keys vi on darwin

### ISSUE THREAD

**Issue by henningphan** [tmux/tmux#3739]
### Issue description
When starting tmux with a ~/.tmux.conf containing `setw -g mode-keys vi`, followed by typing the command `tmux show-options -g mode-keys` I expect it to say `vi` but it says `emacs` instead

What is weird is that if running a command prompt and calling `setw -g mode-keys vi` it will then be vi-mode afterwards.
Or if calling `tmux -f ~/.tmux.conf` instead of only `tmux` will also work.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `tmux 3.3a`
* Platform (`uname -sp`). `Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`). Inside: `screen`, outside: `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-8127.log](https://github.com/tmux/tmux/files/13256285/tmux-client-8127.log)
[tmux-out-8129.log](https://github.com/tmux/tmux/files/13256286/tmux-out-8129.log)
[tmux-server-8129.log](https://github.com/tmux/tmux/files/13256287/tmux-server-8129.log)

**Comment by nicm** [comment]
Your config file changes it to `vi` and then back to `emacs`:
~~~~
$ grep cmdq_fire_command.*mode-keys tmux-server-8129.log
1699091593.014155 cmdq_fire_command <global>: (2596) set-window-option -g mode-keys vi
1699091593.127362 cmdq_fire_command <global>: (2699) set-option -g mode-keys emacs
1699091595.164592 cmdq_fire_command </dev/ttys003>: (4929) show-options -g mode-keys

**Comment by nicm** [comment]
~~~~
$ egrep '( loading |cmdq_fire_command.*mode-keys)' tmux-server-8129.log
1699091592.978927 loading /nix/store/kgmmib2yp43p18qy9ayrjsljp1nxy8sg-hm_tmux.conf
1699091592.980286 loading /nix/store/37wdc7aakkaxmcsjscbijb8fq1aqjckw-hm_tmuxtmux.conf
1699091592.980941 loading /Users/phan/.tmux.d/tmux.defaults.globals
1699091592.985703 loading /Users/phan/.tmux.d/tmux.defaults.sessions
1699091592.987310 loading /Users/phan/.tmux.d/tmux.defaults.bindings
1699091593.014155 cmdq_fire_command <global>: (2596) set-window-option -g mode-keys vi
1699091593.021489 loading /Users/phan/.tmux.d/tmux.profile
1699091593.022276 loading /Users/phan/.tmux.d/tmux.plugins
1699091593.022486 loading /Users/phan/.tmux.d/tmux.copy
1699091593.127362 cmdq_fire_command <global>: (2699) set-option -g mode-keys emacs

**Comment by henningphan** [comment]
thanks that helped a lot, im just going to provide more context.
There is only `mode-keys vi` in my tmux.conf but I still ended up with emacs, its because Im using nix-darwin to manage my tmux config, and they have a separate config file where mode-keys defaults to `emacs`.

https://mipmip.github.io/home-manager-option-search/?query=tmux+emacs

The solution is to install tmux as a normal package when using nix-darwin instead of letting darwin manage the tmux configuration.
