### ISSUE TITLE
[Question] Configure word boundary markers in copy mode?

### ISSUE THREAD

**Issue by phillip-koebbe-fidelity** [tmux/tmux#374]
I'm using Vim key bindings via

```
set -g status-keys vi
setw -g mode-keys vi
```

When I'm in copy mode and moving around or selecting some text, the cursor passes markers that are boundaries in other apps, like Vim. For example, given the text

```
ITERM_SESSION_ID=w0t0p1:EE33EC0E-D14C-4FA7-9B3D-04264D11C48F
```

when I enter copy mode and navigate to the beginning of the line, each press of 'w' moves the cursor as follows

```
# Start
ITERM_SESSION_ID=w0t0p1:EE33EC0E-D14C-4FA7-9B3D-04264D11C48F
^

# Press w
ITERM_SESSION_ID=w0t0p1:EE33EC0E-D14C-4FA7-9B3D-04264D11C48F
      ^

# Press w
ITERM_SESSION_ID=w0t0p1:EE33EC0E-D14C-4FA7-9B3D-04264D11C48F
              ^

# Press w
ITERM_SESSION_ID=w0t0p1:EE33EC0E-D14C-4FA7-9B3D-04264D11C48F
                                 ^
```

I would expect the `=` to be a boundary marker, but it gets passed over. In Vim, it works as I expect it to. I'd like to tweak the markers in tmux, but I can't find anything that discusses it.

**Comment by nicm** [comment]
There is the word-separators option.

**Comment by phillip-koebbe-fidelity** [comment]
@nicm (facepalm) I totally missed that. Thanks a bunch.
