### ISSUE TITLE
[server exited unexpectedly] when mouse double clicking on tmux pane after upgraded to Ubuntu Mantic

### ISSUE THREAD

**Issue by tigerinus** [tmux/tmux#3742]
### Issue description

Have been using tmux 3.3a for a while. Zero problem on Debian and Ubuntu in the past.

Recently upgraded to Ubuntu Mantic (23.10)

Inside tmux, any double clicking on the pane by mouse will immediately cause [server exited unexpectedly] error

![image](https://github.com/tmux/tmux/assets/7172560/165e5265-9422-43ed-bc20-36765d02b266)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

```
tmux 3.3a
```

* Platform (`uname -sp`).

```
Linux x86_64
```

* $TERM inside and outside of tmux (`echo $TERM`).

```
tmux-256color (inside)
xterm-256color (outside)
```

* tmux.conf 

```
run-shell "powerline-daemon -q"
source "~/.local/pipx/venvs/powerline-status/lib/python3.11/site-packages/powerline/bindings/tmux/powerline.conf"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# settings
set -g default-terminal "tmux-256color"
set -g escape-time 10
set -g focus-events on
set -g mouse on
set -g terminal-overrides ",*256col*:Tc"

set -s copy-command 'wl-copy -n'   # <- removing this line does not help

set-window-option -g xterm-keys on

# bindings
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind ` set-window-option synchronize-panes

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
```

* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-14694.log](https://github.com/tmux/tmux/files/13259435/tmux-client-14694.log)
[tmux-out-14696.log](https://github.com/tmux/tmux/files/13259436/tmux-out-14696.log)
[tmux-server-14696.log](https://github.com/tmux/tmux/files/13259437/tmux-server-14696.log)

**Comment by nicm** [comment]
Probably your nurses is too new or tmux is too old, try building tmux from master or downgrading ncurses.
