### ISSUE TITLE
Reponening issue #3741 "Tmux SEGV crash "

### ISSUE THREAD

**Issue by creatldd1** [tmux/tmux#3746]
### Issue description

When I run `tmux new `, the server crashes with SEGV signal. After the crash the console is in a mess and need to be closed.
Apparently it's related to my Tmux config because when running `tmux -f /dev/null`, there is no crash.
Yet if I run `tmux source-file ~/.tmux.conf` to load my settings, it works fine.

The logs and my conf :
[tmux-client-3552.log](https://github.com/tmux/tmux/files/13259060/tmux-client-3552.log)
[tmux-out-3554.log](https://github.com/tmux/tmux/files/13259061/tmux-out-3554.log)
[tmux-server-3554.log](https://github.com/tmux/tmux/files/13259062/tmux-server-3554.log)
[.tmux.conf.txt](https://github.com/tmux/tmux/files/13259068/default.tmux.conf.txt)

I compiled a tmux 3.3a debug version and got the following call stack from last crash  :
```
debian@debian12:~/Documents/github/tmux/logs$ coredumpctl info 
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
           PID: 3554 (tmux: server)
           UID: 1000 (debian)
           GID: 1000 (debian)
        Signal: 11 (SEGV)
     Timestamp: Sun 2023-11-05 09:35:52 CET (36s ago)
  Command Line: tmux -vvv new
    Executable: /usr/local/bin/tmux
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-org.kde.konsole-2541.scope
          Unit: user@1000.service
     User Unit: app-gnome-org.kde.konsole-2541.scope
         Slice: user-1000.slice
     Owner UID: 1000 (debian)
       Boot ID: 4dc0d5ed55464068a1c69f9c95e90984
    Machine ID: 0c416d1db4a04738a6efea31f430ae08
      Hostname: debian12
       Storage: /var/lib/systemd/coredump/core.tmux:\x20server.1000.4dc0d5ed55464068a1c69f9c95e90984.3554.1699173352000000.zst (present)
  Size on Disk: 164.1K
       Message: Process 3554 (tmux: server) of user 1000 dumped core.
                
                Stack trace of thread 3554:
                #0  0x000055cd34c79964 status_message_clear (tmux + 0x7f964)
                #1  0x000055cd34c79a48 status_message_set (tmux + 0x7fa48)
                #2  0x000055cd34c21db4 cmd_if_shell_callback (tmux + 0x27db4)
                #3  0x000055cd34c5085e job_check_died (tmux + 0x5685e)
                #4  0x000055cd34c733fa server_child_exited (tmux + 0x793fa)
                #5  0x00007f4b387bfc12 n/a (libevent_core-2.1.so.7 + 0x1cc12)
                #6  0x00007f4b387c042f event_base_loop (libevent_core-2.1.so.7 + 0x1d42f)
                #7  0x000055cd34c6150f proc_loop (tmux + 0x6750f)
                #8  0x000055cd34c730d0 server_start (tmux + 0x790d0)
                #9  0x000055cd34c1b124 client_connect (tmux + 0x21124)
                #10 0x000055cd34c1624c main (tmux + 0x1c24c)
                #11 0x00007f4b384f91ca n/a (libc.so.6 + 0x271ca)
                #12 0x00007f4b384f9285 __libc_start_main (libc.so.6 + 0x27285)
                #13 0x000055cd34c16601 _start (tmux + 0x1c601)
                ELF object binary architecture: AMD x86-64
debian@deb
```

### Required information

* tmux version (`tmux -V`). 
     tmux 3.3a and  "tmux next-3.4"
* Platform (`uname -sp`). b 
  Debian GNU/Linux 12 (bookworm)"
* $TERM inside and outside of tmux (`echo $TERM`). 
   xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

# * Addtionnal information *

The problem still persists, even on the master branch, after all.
Check previous issue : [3741](https://github.com/tmux/tmux/issues/3741)

This problem is linked to this section of my config file : 
```
if-shell -b 'echo $XDG_SESSION_TYPE | grep -q x11' {
    bind-key -T copy-mode-vi y                  send-keys -X copy-pipe            'xclip -in -selection clipboard' #\; send-keys -X copy-selection
    bind-key -T copy-mode-vi Y                  send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard' #\; send-keys -X copy-selection
    bind-key -T copy-mode-vi W                  send-keys -X "0v\$h"
    bind-key -T copy-mode-vi MouseDragEnd1Pane  send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard > /dev/null'
    bind-key C-p run 'xclip -out -selection clipboard | tmux load-buffer - ; tmux paste-buffer'
    bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"
} "/usr/bin/logger -t TMUX 'if-shell failure'"
```
More precisely it's the "else" section that triggers the SEGV : `"/usr/bin/logger -t TMUX 'if-shell failure'"`.
I tried another output like `echo test` but with the same result.

2 workarounds : 
- comment the else sections
- run tmux with no config file, and load the config-file afterwards : 

```bash
tmux -vvv new -f /dev/null ;

# in another terminal
tmux source-file ~/.tmux.conf

```

**Comment by nicm** [comment]
This should be fixed in OpenBSD now and will be fixed in GitHub later when it syncs. Here is the diff if you want to apply it manually: [x.diff.txt](https://github.com/tmux/tmux/files/13351371/x.diff.txt)

Note your command won't work because "/usr/bin/logger -t TMUX 'if-shell failure'" is not a tmux command (did you want `run-shell`?), check `C-b ~` to see the messages.

**Comment by creatldd1** [comment]
You're right, the "else" part was incorrect (and nonsensical after second thoughts...). I copy-pasted it without testing thoroughly. Still discovering tmux conf language. 
Thanks for the diff and the tips
