### ISSUE TITLE
Starting a session inside a popup crashes tmux

### ISSUE THREAD

**Issue by callms** [tmux/tmux#3748]
### Issue description

I have a setup where I use popup a lot to have a “scratch shell” floating above my regular windows and panes, with a keybinding to easily show/hide the floating popup.

Today I updated `tmux` and noticed my setup stopped working. In the latest versions of `tmux` in `master`, including `v3.3a` but older commits as well, running the following crashes the tmux server:

```bash
$ tmux
$ # now from inside tmux:
$ tmux popup -w 200 -h 50 -E "tmux new -s popup"
```

Here is the output in my terminal:

<img width="2168" alt="Screenshot 2023-11-17 at 14 09 49" src="https://github.com/tmux/tmux/assets/66381046/f64d8bf6-5014-4630-bc8a-3843e4deb9a2">

After running a bisect in the code, I was able to pinpoint the faulting commit to be 9f9156c0303ad9c50fd44e0561ef0f5bb21a418b. 

Commit known to be working on the `master` branch: c57a0926 — [diff](https://github.com/tmux/tmux/compare/c57a0926...9f9156c0303ad9c50fd44e0561ef0f5bb21a418b)

### Required information

Please provide the following information:

* tmux version (`tmux -V`). ```tmux next-3.4```
* Platform (`uname -sp`). ```Linux x86_64```
* $TERM inside and outside of tmux (`echo $TERM`). ```xterm-256color```
* Logs from tmux (`tmux kill-server; tmux -vv new`).
```
[server exited]
```

**Comment by nicm** [comment]
Seems like this might be #3747.

**Comment by nicm** [comment]
Does this still happen with latest master?
