### ISSUE TITLE
lock via "lock-after-time" and I find that it require keyboard operation to reset timer.

### ISSUE THREAD

**Issue by jamespanda** [tmux/tmux#375]
Not ony lock but also vlock can lock the console by setting lock-after-time.
But I find it won't lock again if I just unlock the console without other operation of keyboard.

**Comment by ThomasAdam** [comment]
Hmm.   Try this:

```
diff --git a/session.c b/session.c
index 12a593f..c986b0c 100644
--- a/session.c
+++ b/session.c
@@ -275,12 +275,10 @@ session_update_activity(struct session *s, struct timeval *from)
        else
                evtimer_set(&s->lock_timer, session_lock_timer, s);

-       if (~s->flags & SESSION_UNATTACHED) {
-               timerclear(&tv);
-               tv.tv_sec = options_get_number(s->options, "lock-after-time");
-               if (tv.tv_sec != 0)
-                       evtimer_add(&s->lock_timer, &tv);
-       }
+       timerclear(&tv);
+       tv.tv_sec = options_get_number(s->options, "lock-after-time");
+       if (tv.tv_sec != 0)
+               evtimer_add(&s->lock_timer, &tv);
 }

 /* Find the next usable session. */
```

**Comment by jamespanda** [comment]
thanks a lot
the patch works
but i use the version 2.1_1 of tmux
so i change it to

diff --git a/session.c b/session.c
index 12a593f..c986b0c 100644
--- a/session.c
+++ b/session.c
@@ -275,12 +275,10 @@ session_update_activity(struct session *s, struct timeval *from)
        else
                evtimer_set(&s->lock_timer, session_lock_timer, s);

-       if (~s->flags & SESSION_UNATTACHED) {
-               timerclear(&tv);
-               tv.tv_sec = options_get_number(&s->options, "lock-after-time");
-               if (tv.tv_sec != 0)
-                       evtimer_add(&s->lock_timer, &tv);
-       }
+       timerclear(&tv);
+       tv.tv_sec = options_get_number(s->options, "lock-after-time");
+       if (tv.tv_sec != 0)
+               evtimer_add(&s->lock_timer, &tv);
 }

 /* Find the next usable session. */

**Comment by nicm** [comment]
Updating the timer for unattached sessions is wrong. Probably when it unlocks it needs to do something (reset the timer, or call recalculate_sizes(), or something else).

**Comment by nicm** [comment]
This is probably the issue:

~~~~
? tmux
Index: server-client.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/server-client.c,v
retrieving revision 1.183
diff -u -p -r1.183 server-client.c
--- server-client.c	18 Mar 2016 07:28:27 -0000	1.183
+++ server-client.c	27 Apr 2016 12:16:38 -0000
@@ -1090,12 +1090,13 @@ server_client_dispatch(struct imsg *imsg
 
 		if (gettimeofday(&c->activity_time, NULL) != 0)
 			fatal("gettimeofday failed");
-		if (s != NULL)
-			session_update_activity(s, &c->activity_time);
 
 		tty_start_tty(&c->tty);
 		server_redraw_client(c);
 		recalculate_sizes();
+
+		if (s != NULL)
+			session_update_activity(s, &c->activity_time);
 		break;
 	case MSG_SHELL:
 		if (datalen != 0)

**Comment by jamespanda** [comment]
@nicm 
thanks a lot.    the patch also works although i don't know the different between the two patches

**Comment by nicm** [comment]
Applied, thanks.
