### ISSUE TITLE
Adding a script.sh in set default-command causes a crush.

### ISSUE THREAD

**Issue by oluevaera** [tmux/tmux#3751]
Describe the problem and the steps to reproduce. Add a minimal tmux config if necessary.

Adding `set -g default-command "exec /path/to/shell/script.sh"` to the tmux.conf makes the server instantly crush on call.

Steps to reproduce:
- Make sure tmux is not active `tmux kill-server`
- Create an empty script.sh and chmod +x.
- Add `set -g default-command "exec /path/to/shell/script.sh"` to your tmux.conf file.
- run `tmux`
- Tmux server should init but then break in an instant.

Observations:
I've been looking into it for a few days, I found that if I add the shell after the script, the server will stay open.

Working command: `set -g default-command "exec /path/to/shell/script.sh"; /bin/zsh`

But this causes all the changes that I do in my script.sh to be overwritten. (I make a wrapper function for conda{} in it and after the /bin/zsh my shell is using the normal conda function instead of my wrapper.

I also tried to move the `/bin/zsh` into the default-shell option of tmux.conf, like this:
`set -g default-shell "/bin/zsh"`
`set -g default-command "exec /path/to/shell/script.sh"` 

But it also crushes instantly.

And finally I've also tried 'exec', 'source', and just the path with and without the `default-shell`, but they all crush the server.
`set -g default-command "exec /path/to/shell/script.sh"` 
`set -g default-command "source /path/to/shell/script.sh"`
`set -g default-command "/path/to/shell/script.sh"`

I also have an Ubuntu 20.04 machine and I am able to reproduce with tmux 3.3a and /bin/bash.

### Required information

Please provide the following information:

* tmux version: `tmux 3.3a`
* Platform (`uname -sp`). `Darwin arm` mac OS
* $TERM inside and outside of tmux (`echo $TERM`). Inside: `screen-256color` Outside: `xterm-256color` Using Alacritty.
*Logs attached below. 
[tmux-client-97929.log](https://github.com/tmux/tmux/files/13466914/tmux-client-97929.log)
[tmux-out-97931.log](https://github.com/tmux/tmux/files/13466915/tmux-out-97931.log)
[tmux-server-97931.log](https://github.com/tmux/tmux/files/13466916/tmux-server-97931.log)

**Comment by nicm** [comment]
Does this still happen if you build tmux from master?

**Comment by oluevaera** [comment]
Yes, that's the case on the Ubuntu machine when built from master.

**Comment by nicm** [comment]
You have asked tmux to run a script that immediately exits in every pane, which means every pane will immediately close. What are you expecting tmux to do here?

Try putting something in your script to stop it exiting like `sleep 1000` or `exec $SHELL`.
