### ISSUE TITLE
Silently run command via "send-keys" for scripting

### ISSUE THREAD

**Issue by LucEast** [tmux/tmux#3752]
### Issue description
Hi, I want to create a bash script which adds the current active kubectl context and namespace similar to [kube-tmux](https://github.com/jonmosco/kube-tmux). 
The difference is, that I want to get the `kubectl config current-context` variable from the active pane. 
When I try to run `current-context=tmux send-keys -t "$tmux_pane_id" "kubectl config current-context" Enter` to save the context to a variable I will always get the input and the output in my current pane every second because I configured my `.tmux.conf` with the following: `set -g status-interval 1` . 
```
user@host:~$ kubectl config current-context
some-context
user@host:~$ kubectl config current-context
some-context
user@host:~$ kubectl config current-context
some-context
...
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 
tmux 3.1c
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
screen-256color 
xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
tmux cannot reach into other processes to get environment variables, you will need to make the shell inside tmux save it somewhere (maybe a user option named with `$TMUX_PANE`).
