### ISSUE TITLE
Feature suggestion: populate the scrollback buffer sixel placeholders with derasterized versions

### ISSUE THREAD

**Issue by csdvrx** [tmux/tmux#3753]
### Issue description

On tmux built today 2023-11-28 from master (bdf8e614af34ba1eaa8243d3a818c8546cb21812) with `sh autogen.sh  && ./configure --enable-sixel --enable-systemd`, sixels are correctly displayed. That's wonderful!

However, when using tmux integrated scrollback, empty (blank) placeholders of the sixels are shown: this creates a confusing user experience for the scrollback, where images can vanish and then reappear when going back to the bottom of the scrollback.

### Suggested fix

[Use derasterize to convert the sixels](https://github.com/csdvrx/derasterize) into an appropriate ANSI+Unicode text equivalent [as done in sixel-tmux](https://github.com/csdvrx/sixel-tmux/): it's illustrated at the "Let's scroll back" step of the first example, after using gnuplot.

![actual first example](https://raw.githubusercontent.com/csdvrx/sixel-tmux/main/examples/sixel-tmux_mintty.gif)

Drawback: an ANSI+Unicode text equivalent stored inside the placeholders of the scrollback history would not be "pixel perfect", so it might be offered as a ./configure flag like --sixel-scrollback-derasterize.

### Discussion of the alternatives

Keeping all the sixels image in memory or in a file may be a worse solution, especially for long-running sessions. Still, it could be another configure option like --sixel-scrollback-keep for uses who don't care about keeping a low memory usage, or simply prefer a pixel-perfect solutions.

Even if imperfect, a simple textual representation using little storage would be sufficient to provide a reminder of what the images looked like in the context they were displayed, and where they were: when scrolling back in the  example above, the derasterized version are sufficient to remember the snake and vimperator happened before the gnuplot.

### Advantages of the proposed approach

The derasterize could also offer compatibility with terminals that don't support sixel yet: instead of showing empty/blank placeholders, tmux could be used as 'magic goggles allowing to see sixels': not perfectly, but at least enough to experience some of the dense information they can carry.

This is something very helpful when doing gnuplot over ssh to quickly diagnose issues on remote systems and fix them live: in this case, the remove system would only need to have tmux with this feature enabled, and could be ssh'ed with any terminal while still allowing the exact same gnuplot command to show the information.

### Choice of defaults

I am extremely surprised and happy to see mainline tmux now support sixels, and that it will be in the next 3.4 main version. It's a wonderful step forward!

Yet it would be even better if 3.4 could support this "downgraded sixel experience" mode when sixels are not available or during the scrollback.

Therefore, I would even suggest to have "--sixel-scrollback-derasterize" as a default option: if for any reason the linux distributions packaging tmux do no use "--enable-sixel" by default, tmux would then at least show something were sixels should be, instead of blank placeholders.

### Suggested implementation

The code to implement the suggested feature works in sixel-tmux. Please take a look at it, change it however you want it, and feel free to copy anything from the derasterize scrollback feature of sixel-tmux into mainline tmux, with or without attribution to me. I don't care, I only care about sixels and the users.

If you prefer to implement directly from derasterize, its license is as free/open/compatible as can be. basicidea.c is even in the public domain.

Still, should the licenses terms cause any issues, please let me know and I'll be happy to change them to anything you want (and I'd ask @jart if it includes her code).

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux next-3.4
* Platform (`uname -sp`): Linux unknown (kernel 6.2.2, with arch freshly updated)
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`) (available upon request, but not needed)

**Comment by nicm** [comment]
I don't know why you should be surprised since I wrote the original SIXEL support and the branch had been sitting there for years, it just needed someone to pick it up and get it into shape.

I don't object to this idea although I would not take this code as it is, I think it needs some tidying - at minimum to remove unnecessary code and to fit the tmux code style. And it would need a good fallback for non-UTF-8 terminals. I don't intend to work on this but as always I am happy to answer questions and review PRs.

I do think SIXEL is still not well tested so I would prefer to see general improvements and testing (for example fixing the issues around SIXEL images disappearing with the alternate screen and resize). No doubt there are other problems and improvements as well. I think we need at least one release for that. I intend to do a release after I am back home, probably in the new year.

I'm going to close this issue but I will add an entry on the TODO list so it is not forgotten.

**Comment by csdvrx** [comment]
> I don't know why you should be surprised since I wrote the original SIXEL support and the branch had been sitting there for years, it just needed someone to pick it up and get it into shape.

I'm surprised, because many people seem to have an irrational dislike of sixels, to the point of derailing the inclusion of sixel support in many projects, and IIRC you said you would never support sixels.

I can't read your mind, but based on these priors, I can't assume either that you only have good intentions.

This is why your public commitment to sixel support in tmux was both surprising to me, and very heartwarming: it meant I was wrong and you had good intentions for sixels after all.

> And it would need a good fallback for non-UTF-8 terminals. I don't intend to work on this but as always I am happy to answer questions and review PRs.

You don't have to work on this, it's already there: if you check the derasterize code , you will see it simply chunks the input, and [selects characters from a set of possible and acceptable characters called glyphs defined around line 195](https://github.com/csdvrx/derasterize/blob/dc98c8b782664904eb48116c0c90c206dbb7b048/derasterize.c#L195)

If you have a theoretical terminal that only supports the letters A, B and C, the set of glyphs could just be these 3 characters (or even 2): the result will be poorer, as the best fit (as defined by minimizing the difference from the image chunk and this glyph) will only be selected from this limited set, but the code will work the same.

Another way to see how it works, if you have an image that boils down to a single chunk that looks like a 8, the letter B would be the best fit from the set of glyphs={A,B,C}. If you don't have B, A would be better than C.

This means the fallback for non-UTF8 terminals is just to define a set of glyphs that doesn't include unicode chars: it could be the full ASCII range, as it's better for quality to have a large set, but the tradeoff is speed, so you want to have a set that's "small and diverse" to match geometric shapes of the chunked image. This means the non-UTF8 glyphs should be a small subset of the full ASCII range.

For example, say underscore _ minus - equal = pipe | slash / antislash \ star * and pound \# to cover few basic shapes. But it could also be just the "traditional characters" used in ASCII art

> I don't object to this idea although I would not take this code as it is, I think it needs some tidying - at minimum to remove unnecessary code and to fit the tmux code style.

I can suggest a set of glyphs if you want, or even prepare the \#defines for the full ASCII range of glyphs using a 4x8 bitmap font (so you can chose from them which ones you want) but I don't understand your "tmux style" or what you see as unnecessary code, so it's unlikely you will be satisfied by what I give you.

I've tried to explain the details, but I don't want to waste more time on something I deem unlikely to happen, so I won't do this as a PR:  I believe you doing the tidying of the existing sixel-tmux (just as you want, for your ideas of minimalism and code style) is better than me trying to read your mind.

> I'm going to close this issue but I will add an entry on the TODO list so it is not forgotten.

I've explained you why having no textual fallback is bad, and given you all the options, including removing all attributions to me if for whatever reason you don't want me associated with tmux, as ultimately, only you can decide what kind of sixel supports lands in tmux.

Since apparently neither you nor me want to do this feature, I think it would be better to let the issue open: this way, a potential contributor will have all the context and details. Sixels are seeing a resurgence, and your release of a tmux with sixel support out-of-the-box will attract more attention to sixel, and will increase the chance of finding a potential contributor.

I'll leave things as is with just this suggestion "let the ticket open".

It's Chrismas time, so be happy and have fun.
