### ISSUE TITLE
Unable to passthrough DCS sequence

### ISSUE THREAD

**Issue by gpanders** [tmux/tmux#3755]
### Issue description

The DCS passthrough (`\ePtmux;...\e\\`) does not allow passing through other DCS sequences, because the ST terminator from the "inner" DCS is consumed by tmux as the terminator of the outer passthrough sequence.

The use case is using XTGETTCAP in an application to query the outer/host terminal for terminal capabilities. For instance, to query for the `Ms` capability we use the DCS sequence `\eP+q4D73\e\\`. Wrapping this in the passthrough DCS gives you `\ePtmux;\e\eP+q4D73\e\\\e\\`. However, tmux sees the first `\e\\` as the terminator for the passthrough sequence, so what ends up being forwarded to the terminal is `\eP+q4D73`, without the terminator.

Not all terminals require the terminator, but some do and will refuse to parse the DCS if the terminator is missing.

Steps to reproduce:

```
tmux -v
printf '\x1bPtmux;\e\eP+q4D73\e\\\e\\'
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`): Tested both on 3.3a and on `bdf8e614af34ba1eaa8243d3a818c8546cb21812`
* Platform (`uname -sp`): Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`): inside tmux is `tmux-256color`. This issue manifests in any terminal which requires an ST terminator for DCS sequences (kitty is the only one that I know of, `xterm-kitty` is $TERM)

* Logs from tmux (`tmux kill-server; tmux -vv new`): 

```
input_parse_buffer: %0 ground, 146 bytes: \033Ptmux;\033\033P+q4D73\033\\                                                   \r\342\217\216 \r\033[K
input_enter_dcs
input_dcs_dispatch: "tmux;\033P+q4D73"
/dev/ttys008: \033P+q4D73
```

**Comment by nicm** [comment]
You are missing a `\e`...

**Comment by gpanders** [comment]
> You are missing a `\e`...

Thanks for the quick response. I was able to get it working. I did try this before opening the issue, but it hung my shell. But checking in the logs shows that tmux is forwarding the sequence correctly, so I'll hunt down what's going on there next.

**Comment by przepompownia** [comment]
Thanks from me too!
