### ISSUE TITLE
[Solved] A script to create tmux sessions and run by systemd. 

### ISSUE THREAD

**Issue by bs0c** [tmux/tmux#3757]
Hi guys. I want to write a script to run several sessions in tmux and run the script by systemd.
When I run it in terminal or awesome wm by rc.lua it works, but not by systemd. I have no errors and new session.

Unit systemd:
```
[Unit]
Description=Tmux
Documentation=man:tmux(1)

[Service]
Type=oneshot
ExecStart=/home/bs0c/develop/scripts/create-tmux-session.sh -v %i
ExecStop=/usr/bin/tmux kill-session -t %i

[Install]
WantedBy=default.target
```

[create-tmux-session.sh](https://pastebin.com/ztfkyTpn)

[log from systemd](https://pastebin.com/hCfC6Amw)

* tmux 3.3a
* Linux Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz
* xterm-256color

What am I doing wrong?

**Comment by zsugabubus** [comment]
man systemd.service:

> […] without RemainAfterExit= the service will never enter "active" unit state, but directly transition from "activating" to "deactivating" or "dead" since no process is configured that shall run continuously […]

In practice it means session started by systemd is immediately killed after creation.

```
[Unit]
Description=Tmux Session %i
Documentation=man:tmux(1)

[Service]
Type=oneshot
ExecStart=/usr/bin/tmux new-session -s %i -d
ExecStop=/usr/bin/tmux kill-session -t %i
RemainAfterExit=yes

[Install]
WantedBy=default.target
```
