### ISSUE TITLE
cannot scroll with mouse, even in mouse mode (on MacOS)

### ISSUE THREAD

**Issue by amills-vibeirl** [tmux/tmux#3758]
### Issue description

My tmux config is like so:

```
set -g status on
set -g mouse on
```

but when I click on a pane and try to scroll with my mouse (the trackpad on Macos), I just get the A^ characters:

<img width="679" alt="Screen Shot 2023-11-30 at 12 26 01 PM" src="https://github.com/tmux/tmux/assets/150489986/0a0e45b6-3053-4c98-89b4-32258cd39bbc">

### Required information

Please provide the following information:

* tmux version (`tmux -V`).  tmux 3.3a
* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`). screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).  (this didn't work for me)

**Comment by nicm** [comment]
Please show tmux logs.
