### ISSUE TITLE
“server exited unexpectedly” when copy inside a pane using mouse

### ISSUE THREAD

**Issue by Sejen27** [tmux/tmux#3761]
Environment
[OS] : Ubuntu 23.10
[Terminal] : GNOME Terminal 3.49.92, GNOME 45
[tmux] : v3.3a (build from source)

The mouse option is on. 
I drag with the left button inside a pane and select text, after releasing the mouse, tmux goes wrong. 
![截图 2023-12-04 23-48-46](https://github.com/tmux/tmux/assets/16253972/95b78222-e884-4443-b21a-1515d1c762b0)
Then the terminal does not show any characters I have typed, but after I press 'Enter' key, the terminal run the command I have typed
![image](https://github.com/tmux/tmux/assets/16253972/f23e85ef-31fe-4b72-9927-987582dcc513)

**Comment by nicm** [comment]
Does this still happen if you build tmux from master?

**Comment by Sejen27** [comment]
This problem does not happen on the master
