### ISSUE TITLE
[Question] How does one copy raw control characters from copy mode?

### ISSUE THREAD

**Issue by surajRathi** [tmux/tmux#3763]
### Issue description

I am trying to copy tmux selections as html (to preserve colors when pasting to Google Docs or similar programs). The first step to implementing this feature would be to copy the raw control characters from the screen.

This functionality is seen in `capture-pane -e`:
> If -e is given, the output includes escape sequences for text and background attributes.

I could not find any such option for copy-mode or save-buffer, which leads me to believe that the functionality does not exist.

1. Is there such functionality in copy-mode/save-buffer?
2. Is there a technique where i can hijack copy mode, get the start and end positions of the selection, and then run my own commands (capture-pane) to extract the data I need? I was unable to find this in the documentation, could you point me to the correct page?

### Required information

Please provide the following information:

* tmux version `tmux 3.0a`.
* Platform `Linux x86_64`.
* $TERM inside of tmux `screen-256color`.
* Logs from tmux: n/a.

**Comment by nicm** [comment]
Correct, you need to use capture-pane.

**Comment by nicm** [comment]
I think so, look at the available format variables, selection_present, selection_start_x, etc.
