### ISSUE TITLE
Tmux exits on start when run  without  specifying any command.

### ISSUE THREAD

**Issue by cronyakatsuki** [tmux/tmux#3768]
### Issue description

Recently tmux has started to exit immediatly when starting. I can do `tmux new -- /bin/zsh` and then it start normally but when I just type tmux it just exits immediatly after showing the tmux window, or any other command I provide tmux will start and work correctly.

I have tried  commention out my whole tmux and zsh configs but that didn't fix the issue.

### Required information

Please provide the following information:

* tmux version: 3.3a.
* Platform Linux AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx.
* Distro:  gentoo
* $TERM inside and outside of tmux (`echo $TERM`):  alacritty,  tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`): [tmux-client](https://upfast.cronyakatsuki.xyz/files/tmux-client-18258.log), [tmux-out](https://upfast.cronyakatsuki.xyz/files/tmux-out-18260.log), [tmux-server](https://upfast.cronyakatsuki.xyz/files/tmux-server-18260.log)

Edit: [tmux  config](https://code.cronyakatsuki.xyz/crony/gentoo-dots/src/branch/main/.config/tmux/tmux.conf), [zsh config](https://code.cronyakatsuki.xyz/crony/gentoo-dots/src/branch/main/.config/zsh/.zshrc)

**Comment by cronyakatsuki** [comment]
After checking other issues I have seen that using set -g default-shell /bin/bash or /bin/sh doesn't result in tmux exiting on start.

Is there an issue with my zsh config then?

**Comment by krader1961** [comment]
Look in the strace output for writes to fd 1 and 2. Here are a few of the relevant lines:

```
9538  write(2, "(EE)", 4)               = 4
9538  write(2, "Server terminated with error (1)"..., 52) = 52
9537  write(2, "xinit: ", 7)            = 7
9537  write(2, "giving up", 9)          = 9
9537  write(2, "\n", 1)                 = 1
9537  write(2, "xinit: ", 7)            = 7
9537  write(2, "unable to connect to X server", 29) = 29
9537  write(2, ": Connection refused\n", 21) = 21
9537  write(2, "xinit: ", 7)            = 7
9537  write(2, "server error", 12)      = 12
9537  write(2, "\n", 1)                 = 1
9537  exit_group(1)                     = ?
```

Why are you trying to start the X server from your Zsh startup scripts?

**Comment by cronyakatsuki** [comment]
> Look in the strace output for writes to fd 1 and 2. Here are a few of the relevant lines:
> 
> ```
> 9538  write(2, "(EE)", 4)               = 4
> 9538  write(2, "Server terminated with error (1)"..., 52) = 52
> 9537  write(2, "xinit: ", 7)            = 7
> 9537  write(2, "giving up", 9)          = 9
> 9537  write(2, "\n", 1)                 = 1
> 9537  write(2, "xinit: ", 7)            = 7
> 9537  write(2, "unable to connect to X server", 29) = 29
> 9537  write(2, ": Connection refused\n", 21) = 21
> 9537  write(2, "xinit: ", 7)            = 7
> 9537  write(2, "server error", 12)      = 12
> 9537  write(2, "\n", 1)                 = 1
> 9537  exit_group(1)                     = ?
> ```
> 
> Why are you trying to start the X server from your Zsh startup scripts?

 I'mnot starting a X server from my zsh startup scripts. The only line even remotelly connected to that is this line in .zprofile
```bash
[[ $(fgconsole 2>/dev/null) == 1 ]] && exec startx $HOME/.config/X11/xinitrc &> /dev/null
```
and even then this only starts a X server when I login in the tty1.

**Comment by cronyakatsuki** [comment]
Seems like that line for some reason has gotten broken recently, replacing it with this line fixes the issue.

```bash
if [[ -z $DISPLAY ]] && (( $EUID != 0 )) {
    [[ ${TTY/tty} != $TTY ]] && (( ${TTY:8:1} == 1 )) &&
        exec startx $HOME/.config/X11/xinitrc 1> ~/.local/share/logs/xsession-errors 2>&1
}
```
