### ISSUE TITLE
Unable to output colored underline in tmux

### ISSUE THREAD

**Issue by ssxwcz** [tmux/tmux#3769]
### Issue description
After launching tmux, execute the following command. Normally, the underline should be displayed in red, but in reality, there is no color showing.
```bash
printf "\x1b[58:2::255:0:0m\x1b[4:1msingle\x1b[4:2mdouble\x1b[4:3mcurly\x1b[4:4mdotted\x1b[4:5mdashed\x1b[0m\n"
```

### My config
```conf
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*256col*:Tc"
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'
set -as terminal-features ",gnome*:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m' 
set -as terminal-features '*:usstyle'

```

#### Outside tmux
![image](https://github.com/tmux/tmux/assets/43665491/31c86d3d-867e-4a53-91db-8118f3516848)

#### In tmux
![image](https://github.com/tmux/tmux/assets/43665491/85f83c17-780a-4283-80e3-de696ec7103f)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
```txt
tmux 3.3a
```
* Platform (`uname -sp`).
```txt
ArchWSL Linux ssxw-work 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux
```
* $TERM inside and outside of tmux (`echo $TERM`).
```txt
tmux-256color
```
* terminal
```txt
wezterm
```
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-19019.log](https://github.com/tmux/tmux/files/13683752/tmux-client-19019.log)
[tmux-out-19021.log](https://github.com/tmux/tmux/files/13683753/tmux-out-19021.log)
[tmux-server-19021.log](https://github.com/tmux/tmux/files/13683754/tmux-server-19021.log)

**Comment by nicm** [comment]
It is fine for me. Does it work if you build tmux from master?

**Comment by nicm** [comment]
Show server log from master please.

**Comment by ssxwcz** [comment]
Are you referring to tmux logs?
[tmux-client-24718.log](https://github.com/tmux/tmux/files/13691092/tmux-client-24718.log)
[tmux-out-24720.log](https://github.com/tmux/tmux/files/13691093/tmux-out-24720.log)
[tmux-server-24720.log](https://github.com/tmux/tmux/files/13691094/tmux-server-24720.log)

**Comment by nicm** [comment]
This seems like a problem with your config file:
````
1702692933.701038 unknown terminal feature: usstyle\n
````
Please show me your .tmux.conf.

Have you got a stray literal `\n` at the end of the file?

If not, it seems like you are missing a newline at the end of the file, so perhaps try adding one?

**Comment by ssxwcz** [comment]
> This seems like a problem with your config file:
> 
> ```
> 1702692933.701038 unknown terminal feature: usstyle\n
> ```
> 
> Please show me your .tmux.conf.
> 
> Have you got a stray literal `\n` at the end of the file?
> 
> If not, it seems like you are missing a newline at the end of the file, so perhaps try adding one?

I'm sorry, the error in the log was caused by the lack of a quotation mark on the last line of my configuration file. However, even after fixing this issue, the colored underline still cannot be displayed in tmux.

![image](https://github.com/tmux/tmux/assets/43665491/71df25e3-3624-4670-a940-b20cfa67ef87)

[tmux-client-2856587.log](https://github.com/tmux/tmux/files/13691871/tmux-client-2856587.log)
[tmux-out-2856589.log](https://github.com/tmux/tmux/files/13691869/tmux-out-2856589.log)
[tmux-server-2856589.log](https://github.com/tmux/tmux/files/13691870/tmux-server-2856589.log)

**Comment by nicm** [comment]
tmux appears to be working correctly, this is what it is sending to the terminal:
~~~~
1702715169.111856 /dev/pts/0: \033[58:2:255:0:0m
1702715169.111859 /dev/pts/0: \033[4m
1702715169.111860 /dev/pts/0: single
1702715169.111862 /dev/pts/0: \033(B\033[m
1702715169.111864 /dev/pts/0: \033[58:2:255:0:0m
1702715169.111866 /dev/pts/0: \033[4:2m
~~~~
So it seems like your terminal is ignoring this sequence.

**Comment by davidsierradz** [comment]
Add `config.term = 'wezterm'` to your wezterm config ([term - Wez's Terminal Emulator](https://wezfurlong.org/wezterm/config/lua/config/term.html)):

With `$TERM` `xterm-256color`:
![image](https://github.com/tmux/tmux/assets/9190258/ddc9b945-0829-4d88-99e6-414a6a6f1ed0)
With `$TERM` `wezterm`:
![image](https://github.com/tmux/tmux/assets/9190258/e4a83f96-efa2-475b-a1c7-22f4fba8e33e)
Both inside TMUX

**Comment by ssxwcz** [comment]
> tmux appears to be working correctly, this is what it is sending to the terminal:
> 
> ```
> 1702715169.111856 /dev/pts/0: \033[58:2:255:0:0m
> 1702715169.111859 /dev/pts/0: \033[4m
> 1702715169.111860 /dev/pts/0: single
> 1702715169.111862 /dev/pts/0: \033(B\033[m
> 1702715169.111864 /dev/pts/0: \033[58:2:255:0:0m
> 1702715169.111866 /dev/pts/0: \033[4:2m
> ```
> 
> So it seems like your terminal is ignoring this sequence.



> tmux appears to be working correctly, this is what it is sending to the terminal:
> 
> ```
> 1702715169.111856 /dev/pts/0: \033[58:2:255:0:0m
> 1702715169.111859 /dev/pts/0: \033[4m
> 1702715169.111860 /dev/pts/0: single
> 1702715169.111862 /dev/pts/0: \033(B\033[m
> 1702715169.111864 /dev/pts/0: \033[58:2:255:0:0m
> 1702715169.111866 /dev/pts/0: \033[4:2m
> ```
> 
> So it seems like your terminal is ignoring this sequence.

Thank you, and you are correct.

The color sequence output in tmux logs is ```\033[58:2:255:0:0m```, and this escape sequence does not work on Windows wezterm. It needs to be changed to ```\033[58:2::255:0:0m``` to take effect. This seems to be an issue with conpty https://github.com/microsoft/terminal/pull/15795 , as it does not support ```\e[58:2:<r>:<g>:<b>m```.

**Comment by ssxwcz** [comment]
> Add `config.term = 'wezterm'` to your wezterm config ([term - Wez's Terminal Emulator](https://wezfurlong.org/wezterm/config/lua/config/term.html)):
> 
> With `$TERM` `xterm-256color`: ![image](https://private-user-images.githubusercontent.com/9190258/291746582-ddc9b945-0829-4d88-99e6-414a6a6f1ed0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MDc1MDIsIm5iZiI6MTcwMzQwNzIwMiwicGF0aCI6Ii85MTkwMjU4LzI5MTc0NjU4Mi1kZGM5Yjk0NS0wODI5LTRkODgtOTllNi00MTRhNmE2ZjFlZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjRUMDg0MDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWFiNWNkM2NmNTA1MmIzYTE1YmVlNzVjODU3ZDRmNjg1Yjc2MjVkZjk1ZWUwNTExMjViNWRkZDBiNjYyNTJhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PHdZJQ45tWfXkYmyfgrX4whqT0UCD2dt2de3Y8elT3c) With `$TERM` `wezterm`: ![image](https://private-user-images.githubusercontent.com/9190258/291746662-e4a83f96-efa2-475b-a1c7-22f4fba8e33e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MDc1MDIsIm5iZiI6MTcwMzQwNzIwMiwicGF0aCI6Ii85MTkwMjU4LzI5MTc0NjY2Mi1lNGE4M2Y5Ni1lZmEyLTQ3NWItYTFjNy0yMmY0ZmJhOGUzM2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjRUMDg0MDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGViZDk1MTRlZWM3ZTk1NzQ0MTI0NjkxNDY3MjM5MWJhNmQ5OGRhOGVjYTMxY2E4MWJmMmY4OTNmNDQ1YzU3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OvxoMiANEDDLomX4aEIFgJJ4ysG7j_ilVcs_nMIJp2k) Both inside TMUX

Thank you for your response, but this issue seems to be related to conpty in Windows Terminal, not wezterm.

**Comment by nicm** [comment]
You should be able to change `Setulc` in .tmux.conf for this, but may need to remove the `usstyle` feature or it will overwrite it.

**Comment by ssxwcz** [comment]
> You should be able to change `Setulc` in .tmux.conf for this, but may need to remove the `usstyle` feature or it will overwrite it.

Thank you, with the modification of `setulc` to `set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'`, the colored underline now displays correctly in tmux on Windows Wezterm.
