### ISSUE TITLE
[Feature Request] allow setting window-status styles beyond the previously selected window and add MRU window switching index

### ISSUE THREAD

**Issue by theblop** [tmux/tmux#3770]
tmux allows styling the status bar for the current and previously selected windows (via `window-status-current-style` and `window-status-last-style`). 
It's very useful to know which window will be selected when using the `last-window` command (`prefix-l` by default I think)

I often need to switch between 3 (or more) tmux windows during related work in multiple windows (I use multiple panes already but it's not enough). It would be nice to have a way to set status bar window styles based on the "MRU" (Most Recently Used) index of the previously selected windows, and also have key bindings to switch to "last window - N"

If that's too complex to implement, it would already be a nice improvement if this new feature was only limited to 3 windows (current, last and last-1) instead of a more generic unlimited window history: for example just adding something like `last-1-window` and `window-status-last-1-style` to complement `last-window` and `window-status-last-style` (the names aren't great I know).

**Comment by nicm** [comment]
The position for a window is available in `window_stack_index`, so you can get the last - 1 window by doing:
~~~~
tmux display -p '#{W:#{?#{==:#{window_stack_index},2},#{window_id},}}'
~~~~

Then it should be possible to set the style by adding something like this in the right place in `status-format[0]`:

~~~~
#{?#{==:#{W:#{?#{==:#{window_stack_index},2},#{window_id},}},#{window_id}},#{@my-last-last-window-style},}
~~~~

It should also be fairly easy to write a script to move through the previous windows (although obviously changing the window will change the stack).

**Comment by theblop** [comment]
thanks for your detailed answer! Expending on it, I ended up doing this tmux configuration (trying to minimize copy/paste and make it a bit more readable...):

```
%hidden _TMUX_LAST_LAST_WINDOW_ID="#{W:#{?#{==:#{window_stack_index},2},#{window_id},}}"

# bind ctrl-L to switch to 2nd last window:
bind ^L run 'tmux select-window -t $(tmux display -p "'$_TMUX_LAST_LAST_WINDOW_ID'")'

# set style and format of window status:
set -wgq @last-last-window-style 'fg=yellow'

set -wg window-status-format "\
#{?#{==:$_TMUX_LAST_LAST_WINDOW_ID,#{window_id}},#[#{@last-last-window-style}],}\
#I #W\
#{?#{>:#{window_panes},1},(#{window_panes}),}\
#{?window_marked_flag,#[fg=red#,bold]*,}\
#{?pane_synchronized,#[fg=red#,bold]S,}\
#{?monitor-activity,#[fg=yellow]A,}\
#{?monitor-silence,#[fg=yellow]z,}\
#{?window_zoomed_flag,#[fg=red]Z,}\
"
```

**Comment by nicm** [comment]
> bind ^L run 'tmux select-window -t $(tmux display -p "'$_TMUX_LAST_LAST_WINDOW_ID'")'

You should be able to do:
~~~~
run -C { selectw -t "$_TMUX_LAST_LAST_WINDOW_ID" }
~~~~
Can't remember if will expand the $, if not maybe:
~~~~
run -C { selectw -t "#{_TMUX_LAST_LAST_WINDOW_ID}" }
~~~~

**Comment by theblop** [comment]
Hmm that doesn't seem to work:
> ```
> run -C { selectw -t "$_TMUX_LAST_LAST_WINDOW_ID" }
> ```

gives me the error: `Can't find session: #{W`

and:
> ```
> run -C { selectw -t "#{_TMUX_LAST_LAST_WINDOW_ID}" }
> ```

gives me: `Can't find window: #{_TMUX_LAST_LAST_WINDOW_ID}`

**Comment by nicm** [comment]
Sorry, `run -C` doesn't expand with {}, try:
~~~~
%hidden L="#{W:#{?#{==:#{window_stack_index},2},#{window_id},}}"
bind ^L run -C "selectw -t \"$L\""
