### ISSUE TITLE
How do I fix it?

### ISSUE THREAD

**Issue by Kana-fi** [tmux/tmux#3773]
How do I fix the error in neovim? I tried a few solutions, but no luck. echo $TERM print alacritty-direct
![Screenshot 2023-12-18 at 10 35 34 PM](https://github.com/tmux/tmux/assets/106124331/72ff5ec9-8adc-45cd-addb-5a6d81eebf4b)
![Screenshot 2023-12-18 at 10 32 14 PM](https://github.com/tmux/tmux/assets/106124331/ffe67ced-4f43-479e-986a-48d14d985049)
![Screenshot 2023-12-18 at 10 30 47 PM](https://github.com/tmux/tmux/assets/106124331/7d805b47-5681-4725-ade0-ae9fc21702e4)

**Comment by haolian9** [comment]
probably a typo? `.tmix.conf` -> `.tmux.conf`

**Comment by Kana-fi** [comment]
> probably a typo? `.tmix.conf` -> `.tmux.conf`

Lol, I didn't see that, thanks.

**Comment by Kana-fi** [comment]
Btw, sorry for the wrong repo.
