### ISSUE TITLE
Scrolling on man page doesn't work despite adding mouse support.

### ISSUE THREAD

**Issue by robelene112** [tmux/tmux#3775]
I have this problem where i can't scroll on a man page with the mouse. When i open a man page, ctrl+f and ctrl+b does work. Then, when i scroll upward my terminal history appears (see screenshot). From this point my keys also don't work. Then, when i scroll down the first part of the man page buffer reappears. Now my keys work again.

I desperately want mouse scrolling to work on man pages too and i'm at my wits' end.

$TERM: tmux-256color
tmux -V: tmux 3.3a
uname -sp: Linux unknown
uname -r: 6.6.6-100.fc38.x86_64
distribution: fedora
window manager: dwm
terminal emulator: alacritty
shell: zsh

.tmux.conf:
```
set -g prefix C-x
unbind C-b
set-option -sg escape-time 10
set-option -g focus-events on
set-option -g history-limit 5000
set -g mouse on
```

Some things to note:
- I have tried several different terminal emulators: alacritty, st, gnome-terminal.
- I tried removing my configuration file.
- Scrolling works on all above mentioned emulators when not using tmux.
- When i use the commands ```tmux -Ltest kill-server``` and 
```tmux -vv -Ltest -f/dev/null new``` everything works perfectly fine (of course it does 🙄)

Here are my logs:
[tmux-client-345560.log](https://github.com/tmux/tmux/files/13728948/tmux-client-345560.log)
[tmux-out-345562.log](https://github.com/tmux/tmux/files/13728949/tmux-out-345562.log)
[tmux-server-345562.log](https://github.com/tmux/tmux/files/13728950/tmux-server-345562.log)

 ![brightnessctl](https://github.com/tmux/tmux/assets/82229562/b44c9265-7131-4fb9-86e6-ad625d9e4047)

**Comment by robelene112** [comment]
> Your man pager is not turning on mouse mode, are you sure it supports the mouse?
> 
> Maybe you want this: https://github.com/tmux/tmux/wiki/Recipes#send-up-and-down-keys-for-the-mouse-wheel

Hey nicm,
I forgot to mention in my original post that i tried two different pagers: "Less" and "More". I tried adding ```bind -n WheelUpPane if -Ft= "#{mouse_any_flag}" "send -M" "send Up"``` and ```bind -n WheelDownPane if -Ft= "#{mouse_any_flag}" "send -M" "send Down"``` to my config file as per your comment, but it doesn't seem to work unfortunately. I made sure to restart tmux after editing my config file.

**Comment by nicm** [comment]
Show logs please with these bindings in place.

**Comment by robelene112** [comment]
It seems to work now thanks! Not sure what i did wrong last month but it works now.

**Comment by robelene112** [comment]
Only issue i have now is that i can't scroll through my terminal history

**Comment by nicm** [comment]
Maybe https://github.com/tmux/tmux/wiki/FAQ#i-want-to-use-the-mouse-to-select-panes-but-the-terminal-to-copy-how

**Comment by nicm** [comment]
Hmm if you mean inside tmux, you will need to set some criteria for when tmux should scroll and when it should send Up or Down. I've seen people only send Up or Down when the command is more or less, something like this, although my mouse wheel doesn't work so I can't test it:
~~~~
bind-key -n WheelUpPane if -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" {
    send -M
} {
    if -F '#{m/r:^(less|more),#{pane_current_command}' {
        send Up
    } {
        copy-mode -e
    }
}
~~~~

**Comment by robelene112** [comment]
Hey Nic, 

Your last code snippet fixed scrolling through history again but now scrolling through man pages doesn't work anymore. To clarify, yes this was all done inside a tmux session. Another clarification: with 'terminal history' i mean the terminal output history and not the command history.

Below I have logs of each case: 
- no configuration file,
- configuration file with  ```bind -n WheelUpPane if -Ft= "#{mouse_any_flag}" "send -M" "send Up"``` and ```bind -n WheelDownPane if -Ft= "#{mouse_any_flag}" "send -M" "send Down"```
- configuration file with your last code snippet.

I've tried my best to make the logs as consistent as possible by going through the same steps every time:
- run the appropriate commands to start a tmux session with logging enabled depending on if i'm using a configuration file or not
- open the man page for getc
- scroll down using ctrl+f
- scroll up with mouse
- scroll down with mouse
- scroll back up with ctrl+u
- exit man page with 'q'
- run ls -Alsh to generate a lot of terminal history
- scroll through terminal history
- exit tmux session

(Note that i had to copy the contents of .tmux.conf to tmux.txt because the file picker wasn't able to find .tmux.conf.)

### 1. No config file
Config file: none.
Logs: 
[tmux-out-123383.log](https://github.com/tmux/tmux/files/14084985/tmux-out-123383.log)
[tmux-server-123383.log](https://github.com/tmux/tmux/files/14084986/tmux-server-123383.log)
[tmux-client-123381.log](https://github.com/tmux/tmux/files/14084987/tmux-client-123381.log)
Results: was able to scroll through man page, was not able to scroll through terminal history.

### 2. Config file with first code snippet
Config file: 
[tmux.txt](https://github.com/tmux/tmux/files/14085074/tmux.txt)
Logs:
[tmux-out-179905.log](https://github.com/tmux/tmux/files/14085247/tmux-out-179905.log)
[tmux-server-179905.log](https://github.com/tmux/tmux/files/14085249/tmux-server-179905.log)
[tmux-client-179903.log](https://github.com/tmux/tmux/files/14085251/tmux-client-179903.log)
Results: was able to scroll through man page, was not able to scroll through terminal history. 

### 3. Config file with last code snippet
Config file: 
[tmux.txt](https://github.com/tmux/tmux/files/14084898/tmux.txt)
Logs:
[tmux-out-142956.log](https://github.com/tmux/tmux/files/14085053/tmux-out-142956.log)
[tmux-server-142956.log](https://github.com/tmux/tmux/files/14085054/tmux-server-142956.log)
[tmux-client-142954.log](https://github.com/tmux/tmux/files/14085056/tmux-client-142954.log)
Results: was not able to scroll through man page, was able to scroll through terminal history.

Appreciate the help.

**Comment by robelene112** [comment]
Hey Nic, sorry for the late response.
```tmux lsp -aF '#{pane_current_command}'``` outputs:

tmux
node
zsh

**Comment by zalza** [comment]
@robelene112, this is exactly the same issue as #3705.
The `~/.tmux.conf` from #3692 should resolve your issue.

I think that making #3692 default can reduce this recurring confusion, although this is not perfect fit for @nicm's taste (https://github.com/tmux/tmux/issues/1333#issuecomment-386371456, https://github.com/tmux/tmux/issues/3692#issuecomment-1717060967).

So as a compromise, #3705 might be more adequate default if #3692 is written in some wiki FAQ page to help users to customize their scrolling behavior as #3692.

Nevertheless, I think it's worth making #3692 default because so many tmux newbies experience this issue and just want tmux pane to behave just like the same as the scrolling behavior of some popular terminal emulators.

Or another alternative might be adding a toggle option to switch between #3705 (turn off translation of scroll to Up/Down) and #3692 (turn on translation of scroll to Up/Down)?

## Suggestions for this recurring issue
- #3705
- #3692

## Other references
- https://www.reddit.com/r/tmux/comments/tqmyzm/snippet_better_scrolling
- https://github.com/tmux/tmux/issues/1610
- https://github.com/tmux/tmux/issues/1333
- https://github.com/tmux/tmux/issues/1320

**Comment by robelene112** [comment]
@zalza Terribly sorry for the late response. Thank you, this helped immensely. It works like I expected now.
