### ISSUE TITLE
Run confirm-before with run-shell command

### ISSUE THREAD

**Issue by dindon-sournois** [tmux/tmux#3778]
### Issue description

Is it possible to run confirm-before combined with run-shell ? Did I use it incorrectly, or is it a planned/not planned feature ?

```bash
$ tmux bind-key c confirm-before run-shell "ls"
command confirm-before: too many arguments (need at most 1)
```

### Required information

```bash
$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 3.3a
tmux-256color
```

**Comment by nicm** [comment]
{} or ""?

**Comment by dindon-sournois** [comment]
Quoting with "" worked, thanks :O
