### ISSUE TITLE
display-menu gets closed prematurely even with -O option when launched from a shell spawned by mouse event

### ISSUE THREAD

**Issue by damnskippy** [tmux/tmux#3779]
Not sure if this is a usage error on my part, but I'm seeing the following issue and was wondering if there's a way to handle this.
With the following binding, the menu is displayed upon mouse click, and menu is persistent until user action is taken - this works as expected:

`$ tmux bind-key -n M-MouseDown1Pane display-menu -O option o "display-message 'foo'"`

But putting this same command into a shell script as below:
```
$ cat /var/tmp/test.sh
#!/bin/sh
tmux display-menu -O option o "display-message 'foo'"
```
and then binding the script to the mouse event as below causes the menu to be displayed only briefly and then closed soon as the mouse button is released.
`$ tmux bind-key -n M-MouseDown1Pane run-shell "/var/tmp/test.sh"`

Idea is to dynamically render the menu contents based on mouse_word, mouse_hyperlink, etc. and this is done in the script bound to the mouse event.

This is observed using the latest sources from github as of today, running on ubuntu.

Thanks.

**Comment by nicm** [comment]
Running it from `run-shell` seems to make tmux forget it was run from a mouse key.

Try applying this then add `-M` to `display-message` to tell it to allow the mouse even though it doesn't think it was opened from a mouse key: [x.diff.txt](https://github.com/tmux/tmux/files/14516273/x.diff.txt)

**Comment by damnskippy** [comment]
Patch works great, thanks very much for taking care of this, much appreciated.

**Comment by damnskippy** [comment]
Would be great if this can be merged into the main branch whenever you get the chance for it.
Thanks.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
