### ISSUE TITLE
switching panes with arrow keys

### ISSUE THREAD

**Issue by AquaL1te** [tmux/tmux#378]
Running tmux-2.1-3.fc23.x86_64, I noticed a regression when upgrading from tmux 1.9 to 2.1 when I use the following prefixes below. When I do ctrl + b and then arrow key right and then start typing ls it goes to the last used window. This is of course the same as ctrl +b and then l. In the past this prefix was locked only for the arrow keys when the first arrow key was pressed. Now it keeps the time-out for all prefixes rather than just the pane switching with the arrow keys. Which leads to confusing situations when typing too fast, especially when hitting the d key after switching a pane with the arrow keys, which will terminate your tmux and you have to reattach it again.

ctrl + b and then ? output
bind-key -r -T prefix Up               select-pane -U
bind-key -r -T prefix Down             select-pane -D
bind-key -r -T prefix Left             select-pane -L
bind-key -r -T prefix Right            select-pane -R

Custom settings
* Delay time for sending commands
set-window-option -g escape-time 1000

* Delay time for repeating commands
set-window-option -g repeat-time 600

**Comment by AquaL1te** [comment]
Why did you close this bug? Is it already fixed upstream?

**Comment by symonds** [comment]
It seems this issue was fixed in 2.2, however I'm running on OS X and can only get 2.1 at the moment.
