### ISSUE TITLE
Not able to unbind or overwrite custom key-bindings

### ISSUE THREAD

**Issue by dusanbrankov** [tmux/tmux#3781]
### Issue description

I noticed that when changing a custom key binding, the old ones persist, and for whatever reason, explicitly unbinding them has no effect.

For example, I had this key binding:

```
bind -n M-j previous-window
bind -n M-k next-window
```

And I changed it to:

```
bind -n M-Left previous-window
bind -n M-Right next-window
```

Now the old key bindings are still active and I can't use them for other tasks. `unbind M-j` doesn't seem to do anything.

I found an [older question on StackExchange](https://unix.stackexchange.com/questions/57641/reload-of-tmux-config-not-unbinding-keys-bind-key-is-cumulative) and tried to solve it based on the given answers:

- I unbound all keys with `unbind-key -a`
- I re-added all default key-bindigs with `tmux -f /dev/null -L temp start-server \; list-keys >> ~/.config/tmux/tmux.reset.conf` 
- I added `source-file ~/.config/tmux/tmux.reset.conf` at the very beginning of my `tmux.conf`

Although I didn't get any errors after restarting tmux, none of my custom key bindings work anymore, and worse, the terminal doesn't respond when I press my prefix key `s`. Also, I can't roll back the changes.

But even if it did work, it's complete nonsense. When I change a key bind, I expect the old one to be overwritten.

Is there a way to solve this problem or am I misunderstanding something?

P.S. My `tmux.conf` is relatively short, you can find it [here](https://github.com/dusanbrankov/dotfiles/blob/main/dots/.config/tmux/tmux.conf).

### Required information

* tmux next-3.4
* Linux x86_64
* $TERM inside/outside of tmux: xterm-256color

#### Logs from tmux

- [tmux-server-72039.log](https://github.com/tmux/tmux/files/13753609/tmux-server-72039.log)
- [tmux-client-72037.log](https://github.com/tmux/tmux/files/13753610/tmux-client-72037.log)
- [tmux-client-29997.log](https://github.com/tmux/tmux/files/13753611/tmux-client-29997.log)
- [tmux-out-5288.log](https://github.com/tmux/tmux/files/13753612/tmux-out-5288.log)
- [tmux-server-5288.log](https://github.com/tmux/tmux/files/13753613/tmux-server-5288.log)
- [tmux-client-5281.log](https://github.com/tmux/tmux/files/13753614/tmux-client-5281.log)

---

Please let me know if more information is needed.

Thanks in advance.

**Comment by dusanbrankov** [comment]
Update: I forgot to add the `-n` flag to unbind the old key bindings, sorry. I would still like to know what's going on and how to automatically disable old key bindings that are no longer present in `tmux.conf`.

**Comment by nicm** [comment]
`unbind -n M-j`?

**Comment by dusanbrankov** [comment]
@nicm Yes, but is that the way it should be? Do I always have to unbind before replacing the old ones?

**Comment by nicm** [comment]
No, if you do `bind -n M-j xyz` and then `bind -n M-j def` then `def` will replace `xyz`.

**Comment by dusanbrankov** [comment]
Ok, got it. Thanks for the quick help.
