### ISSUE TITLE
FR: Option for `tmux selectw -t 'string*'` to cycle matching windows

### ISSUE THREAD

**Issue by pataquets** [tmux/tmux#3782]
### Feature description
I use `tmux selectw -t` to jump directly to my editor window (Emacs in daemon mode). It works if there is only one window. As soon as I run Emacs on another window, it stops working. Having an option to cycle on matching windows would be super useful.

### Required information

* tmux version (`tmux -V`). 3.2a
* Platform (`uname -sp`). Ubuntu Jammy
* $TERM inside and outside of tmux (`echo $TERM`). n/a
* Logs from tmux (`tmux kill-server; tmux -vv new`). n/a

**Comment by nicm** [comment]
This has been on the todo list for a long time and so far nobody has done it.

You could do something like`findw -N 'emacs'`. You will need to write a little script if you want it to only list the windows if there is more than one.

It'd be nicer to do `findw -rN `^emacs$'` but there was a bug that means that won't work so if you want to do that you will need to wait for a few days then build from master.

**Comment by pataquets** [comment]
Thanks for the advice, @nicm. I've tried `findw`, with no luck. Also, as far as I understand, it's quite unreliable, anyway.

Since you mentioned "it's on the TODO", I've looked for it to find the feature list item, but found nothing about the FR (assuming [this](https://github.com/tmux/tmux/wiki/Contributing) is the TODO). I would like to ask the FR to be kept visible (initially, I was thinking into request the issue to be left open), but I'm unsure on how to request it. Should I send a PR to the TODO file to add the FR to the list? Can this issue be reopened? My point is to make the issue visible, in case it can attract other potentially interested parties' contributions.

As far as I have read the code, it must be something around [this call](https://github.com/tmux/tmux/blob/605bf21ff225c68d21577a94d423e9ec16158cdb/cmd-select-window.c#L137). So far, despite my limited knowledge of the code, looks like it _might be_ a "low hanging fruit"/"good first issue" type for new contributors to pick up.

**Comment by nicm** [comment]
Hmm it definitely was there, maybe I removed it on the grounds it wasn't going to be done and is relatively easy to script.

It's not easy to do because it has to work for all commands, just supporting one command is not much use.

`find-window` is completely reliable, I use it all the time.
