### ISSUE TITLE
Remapping ctrl-m in tmux makes terminal unusable.

### ISSUE THREAD

**Issue by benibilme** [tmux/tmux#3786]
* tmux version: 3.3a
* Platform: Linux 5.10.202-1-MANJARO  
* $TERM : alacritty 

Hello
I am using non latin1 keyboard and instead of `h,j,k,l` keys, I need to use `t,k,m,l` keys.  

When I map `Ctrl-m` to in place of `Ctrl-k` as select pane up, my terminal becomes unusable since I can no longer use `enter` and execute a command.  

Pressing `enter` mimics the navigation command `Ctrl-m`, switching between splits, selecting upper pane, instead of executing the command written on terminal line. `Ctrl-m` does the same. Following is the setting that I am using. I realized that in tmux and in bash `Ctrl-m` is synonym for `enter`.  I searched for keymap in tmux could not find spefic setting for `Ctrl-m` or `enter` which I can remap something else.  After exiting tmux, terminal behaves normally meaning `Ctrl-m` acting as `enter`. 

Any help is much appreciated.     

````
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator

# decide whether we're in a Vim process
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-t' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-m' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'

if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -n 'C-Space' if-shell "$is_vim" 'send-keys C-Space' 'select-pane -t:.+'

bind-key -T copy-mode-vi 'C-t' select-pane -L
bind-key -T copy-mode-vi 'C-k' select-pane -D
bind-key -T copy-mode-vi 'C-m' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
bind-key -T copy-mode-vi 'C-Space' select-pane -t:.+

````

Note:  _I initially posted this in discussion, but later I decided to make it issue, but I could not delete that from discussion, since I could not see delete option._

**Comment by krader1961** [comment]
The Enter (or Return) key sends Ctrl-m. So remapping Ctrl-m means you are also remapping the behavior of your Enter (or Return) key. What you are attempting is impossible. To make this work you would have to modify your terminal or keyboard so that what it sends when you press Ctrl-m is some other sequence. You cannot, in any practical and usable sense, change how the OS and every application treats Enter/Return/Ctrl-m. At best you may be able to configure your terminal so that when you press Ctrl-m it sends something else.

**Comment by benibilme** [comment]
Thank you for the input.  I am a complete nob in this matter, so please bare with me.  

I would like to clearly understand this. Is it not possible to break the synonym between `Crtl-m/enter/return` in tmux?  I mean that I use `Ctrl-m` for my purpose but keep using `enter` as it is supposed to be. 

Is it terminal or bash problem? I am asking this because I have been using in vim/nvim these mappings for years without problem in all sorts of  terminals such as alacrittyl  for years, which means application can understand it, even though it is being in a terminal environment. Again I may be being silly, so please be patient with me. 

I have found possibly the only real discussion at [How to turn off alternative Enter with Ctrl+M in Linux](https://stackoverflow.com/questions/40444408/is-ctrlm-the-same-as-enter?rq=3) 

>  think your question is backwards. It is not C-m that is bound to Enter, it is Enter that is bound to C-m. And C-m is the same as RET.
> If you run C-h k C-m, you will see something like "RET runs the command ...". C-m sends RET because it is a control code, see http://en.wikipedia.org/wiki/Control_character.
> The Enter key is bound to C-m; if you run C-h k Enter, you will see something like "RET (translated from <return>) runs the command ...". See, Enter is being interpreted by emacs as <return> and then that key is getting translated to C-m.
> What you want to do is first remove the translation from <return> to RET by binding it directly to what it's currently indirectly bound, e.g. (global-set-key (kbd "<return>") 'newline). Then you're free to bind C-m to whatever you want without affecting Enter.
> This assumes you're using the graphical emacs. If you're running it in a terminal, this won't work, because Enter will send C-m, not <return>. You can check that using the window-system variable though.

I happen to interested in using vim/nvim in tmux environment.   Thank you again.

**Comment by krader1961** [comment]
The only way vim could behave the way you describe is if it enables extended keys so that it can distinguish Ctrl-m, the keypress, from a literal Ctrl-m sent by Enter/Return. No shell I'm familiar with enables extended keys. The SO question you linked to is unrelated to your question.

**Comment by benibilme** [comment]
I have enabled extended keys and mapped every combination in a file based on [fixing terminals](https://www.leonerd.org.uk/hacks/fixterms/) similar to as follows and enabled `set -s extended-keys on. It seems not working, or I possibly have error in my configuration. 

Anyhow thank you for the input, it was really helpful.  It was I will be asking this to the developers of alacritty, maybe they provide more insight in terms of terminal capability. I am closing this issue, and for know I will survive by using additional key such as ctrl-b, (t,k,m,l). 

If I have more information, I will try to update this issue for future reference for anybody who may interested in. 

````
key_bindings:
  - { key: H, mods: Control|Shift, chars: "\x1b[72;6u" }
  - { key: J, mods: Control|Shift, chars: "\x1b[74;6u" }
  - { key: K, mods: Control|Shift, chars: "\x1b[75;6u" }
  - { key: L, mods: Control|Shift, chars: "\x1b[76;6u" }

  - { key: I, mods: Control, chars: "\x1b[105;5u" }

  - { key: Period, mods: Control, chars: "\x1b[46;5u" }
  - { key: Comma, mods: Control, chars: "\x1b[44;5u" }
  - { key: Semicolon, mods: Control, chars: "\x1b[59;5u" }

  - { key: Return, mods: Shift, chars: "\x1b[13;2u" }
````
