### ISSUE TITLE
Different behaviors of zoom across OS

### ISSUE THREAD

**Issue by dragonxlwang** [tmux/tmux#379]
I am using zoom to "maximize" a pane in a window.

In Linux, where tmux is compiled from source (version 2.1), when a pane is zoomed/maximized, switching pane ``select-pane -D/U/L/R`` will not switch to the hidden panes; however, in Mac with homebrew tmux with a maximized pane, I can still jump to hidden panes in the same window (which would make the current pane unzoomed) by using ``select-pane''. Is it normal to have different zoom across OS?

I would rather the jumping being available across all OS as that's really convenient (save a keystroke of prefix-Z first)

![untitled](https://cloud.githubusercontent.com/assets/15812510/14754132/fec28124-089e-11e6-875f-3394eac15c97.gif)

In above, the first clip is from a mac, and the second is from a linux (ssh-ed from a mac)

**Comment by ThomasAdam** [comment]
So this should be fixed in tmux 2.2

-- Thomas Adam
