### ISSUE TITLE
Add new option: `window-status-last-format`

### ISSUE THREAD

**Issue by tristan957** [tmux/tmux#3792]
My current `window-status-current-format` is:

```tmux
set -g window-status-current-format '#[bg=#BEE2B5] #[bg=#9BD28C] #[bg=#89ca78] #I:#W#F #[bg=#9BD28C] #[bg=#BEE2B5] '
```

I would like an opportunity to do this with the last window as well.

**Comment by nicm** [comment]
I don't think we need any new options as this can be done with conditionals in the existing options.

**Comment by tristan957** [comment]
@nicm, being a non-expert at tmux's config syntax, could you post a little snippet of how I could do that?

If I can just achieve what I want like that, then we can just close the issue.

**Comment by nicm** [comment]
You can put something like `#{?window_last_flag,last,not last}` into `window-status-format`.

**Comment by tristan957** [comment]
@nicm thanks. I'll let you make the decision on whether or not to close this. I will work with the example you have given!
