### ISSUE TITLE
OSC52 set clipboard doesn't work when the window is not active

### ISSUE THREAD

**Issue by anhpt379** [tmux/tmux#3793]
### Issue description

I'm using OSC52 to copy text to clipboard. It works normally when the window is active, but doesn't work when the window is in the background. Here's how to reproduce it:

I do have `set-clipboard on`:
```bash
$ tmux show -s set-clipboard
set-clipboard on
```

It works perfectly when the window where we use OSC52 is active:
```bash
$ printf "\033]52;c;$(echo "test1" | base64)\a"
```

But it doesn't work when the window is not active:

```bash
$ sleep 2; printf "\033]52;c;$(echo "test2" | base64)\a"  # press Enter, then switch to another window, and wait for 2 seconds, the clipboard setting in the background window where we run this command doesn't work.
```

### Required information

My environment:

```
$ uname -sp && tmux -V && echo $TERM
Linux aarch64
tmux 3.3a
tmux
```

`$TERM` outside of tmux is `xterm-kitty`.

**Comment by damnskippy** [comment]
Might be worth trying `set-buffer -w "test1"` if it's an option for you, although I have no clue why the escape sequence doesn't take in this case.

**Comment by anhpt379** [comment]
Using `set-buffer -w` fixes the issue partially. I'm using a tmux locally, and a nested tmux on remote servers. The `set-buffer -w` works for background window on my local tmux, but doesn't work when the background window has a nested remote tmux session (it does set clipboard for the remote tmux, but doesn't propagate to the local tmux clipboard).

**Comment by nicm** [comment]
It's generally not a great idea to let windows you can't see set the clipboard by default. It would need a similar `all` option added to `set-clipboard` as was added to `allow-passthrough`.
