### ISSUE TITLE
`extended-keys` do not work in Contour terminal

### ISSUE THREAD

**Issue by AlexKurisu** [tmux/tmux#3796]
### Issue description

`extended-keys` feature doesn't work at all under Contour terminal.
Config:
```
set -s extended-keys on
set -as terminal-features 'contour:extkeys'
```
`$TERM`: `contour`

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux next-3.4 (built from commit e809c2e)
* Platform (`uname -sp`): Linux unknown (Arch Linux)
* `$TERM` inside tmux - `tmux-256color`. Outside tmux - `contour`.
* Logs from tmux:
[tmux-client-860121.log](https://github.com/tmux/tmux/files/13846674/tmux-client-860121.log)
[tmux-out-860123.log](https://github.com/tmux/tmux/files/13846675/tmux-out-860123.log)
[tmux-server-860123.log](https://github.com/tmux/tmux/files/13846676/tmux-server-860123.log)

**Comment by AlexKurisu** [comment]
Link to terminal emulator web site: https://contour-terminal.org
It probably supports only `CSI u` key encoding and not `modifyOtherKeys`

**Comment by AlexKurisu** [comment]
Also, i used the `printf '\e[>1u'; cat -v'` command to test for `CSI u` input, but `printf '\033[>4;1m'; cat -v` didn't work either. Logs:
[tmux-server-861103.log](https://github.com/tmux/tmux/files/13846759/tmux-server-861103.log)
[tmux-out-861103.log](https://github.com/tmux/tmux/files/13846760/tmux-out-861103.log)
[tmux-client-861099.log](https://github.com/tmux/tmux/files/13846762/tmux-client-861099.log)

**Comment by nicm** [comment]
I don't see any extended keys (CSI u) being sent in this log. Which keys did you press?

**Comment by AlexKurisu** [comment]
> I don't see any extended keys (CSI u) being sent in this log. Which keys did you press?

I don't remember already, so I took new logs (tested with `printf '\e[>1u'; cat -v`, which works outside of tmux). Pressed keys are Ctrl-1 to Ctrl-9 and then Ctrl-C
[tmux-client-132585.log](https://github.com/tmux/tmux/files/14271062/tmux-client-132585.log)
[tmux-out-132587.log](https://github.com/tmux/tmux/files/14271063/tmux-out-132587.log)
[tmux-server-132587.log](https://github.com/tmux/tmux/files/14271065/tmux-server-132587.log)

**Comment by AlexKurisu** [comment]
Reproducible with tmux built from commit 608d113486835515e7a89b1511704440c68ae817 btw

**Comment by AlexKurisu** [comment]
Tested this in WezTerm (it supports modifyOtherKeys) and looks like tmux is also (incorrectly) emits CSI u keycodes when application requests xterm's modifyOtherKeys

**Comment by nicm** [comment]
xterm can emit either sequence but tmux always sends CSI u because this is what almost all terminals now support (if they support either).

**Comment by nicm** [comment]
From the log it seems your terminal is not sending extended sequences to tmux, for example here tmux is simply receiving `7`:
~~~~
1707850955.995069 /dev/pts/3: keys are 1 (7)
~~~~

**Comment by AlexKurisu** [comment]
Maybe tmux implements only XTerm's CSI u and not kitty's CSI u? That would explain everything

**Comment by AlexKurisu** [comment]
Most terminals that have CSI u implement kitty's one (https://sw.kovidgoyal.net/kitty/keyboard-protocol)

**Comment by nicm** [comment]
They should be the same although kitty may be doing something silly. But I thought you were talking about contour terminal? If it isn't sending anything different for `1` and `C-1` there is little tmux can do whether it supports the keys or not.

**Comment by AlexKurisu** [comment]
> They should be the same

They are enabled with different keycodes. Kitty's one is enabled with `ESC[>1u`

**Comment by nicm** [comment]
CSI u is nothing to do with kitty, it was invented by leonerd who IIRC also wrote the xterm support, it is described here https://www.leonerd.org.uk/hacks/fixterms/.

**Comment by nicm** [comment]
OK well tmux will only do anything with the original one.

**Comment by AlexKurisu** [comment]
> CSI u is nothing to do with kitty, it was invented by leonerd who IIRC also wrote the xterm support, it is described here [leonerd.org.uk/hacks/fixterms](https://www.leonerd.org.uk/hacks/fixterms/).

The thing is that no terminal other that xterm implements that. All other terminals use Kitty's modified and extended version of this protocol.

**Comment by nicm** [comment]
Apart from iTerm2 you mean?

**Comment by AlexKurisu** [comment]
Well, yes

**Comment by nicm** [comment]
OK well in any case if your terminal does not support extended keys as xterm does then tmux may either not be able to turn them on or not be able to understand them. But I should have thought C-1 would be the same so you might get away with just making tmux send whatever enable sequence you need.

**Comment by AlexKurisu** [comment]
No extended-keys for terminals without modifyOtherKeys i guess

**Comment by nicm** [comment]
I don't mind supporting if you're going to do the work, but I'd be a bit reluctant to drop or break support for the "original" protocol without some evidence that kitty's is becoming widespread, as far as I remember many of the major terminals either have no support (VTE, Terminal.app?) or xterm-style support (xterm, iTerm2, mintty?).

You can maybe use the `user-keys` option if you only need a subset of keys to work.
