### ISSUE TITLE
[Feature Request] Disabling line-wrap while preserving clipped contents

### ISSUE THREAD

**Issue by no-more-secrets** [tmux/tmux#3797]
Previous issue that is now locked: "[Feature Request] Disabling line-wrap" #1784

I'd like to reconsider that issue as I think it would be a compelling feature.  The idea is to give tmux native support for a mode where it truncates lines (instead of wrapping them) but preserves the full content of the lines so that they become visible when maximizing/enlarging the pane.  This mode could be set per-pane.

This is really needed on small screens that are split vertically; in such configurations, terminal output tends to be difficult to read, and neither manual clipping nor wrapping meets the need.

**Comment by nicm** [comment]
This is already on the todo list and so far nobody has done it.

You can turn off wrapping by sending DECAWM (`printf '\033[?7l'`).
