### ISSUE TITLE
tmux on msys2 not displaying some icons in nvim and breaking layout

### ISSUE THREAD

**Issue by markjfisher** [tmux/tmux#3800]
### Issue description

I'm trying to get tmux/nvim working in a MSYS2 environment in windows.

Everything is very close to working, except some nerd-font characters are not showing, and the layout breaks when using nvim through tmux, but it's fine when I use nvim in the normal shell without tmux.

Working image 1 (not using tmux)
![image](https://github.com/tmux/tmux/assets/1616940/e73745c9-ea1a-431c-9da7-b4d9e40f935a)

Broken Image 1 (using tmux)
![image](https://github.com/tmux/tmux/assets/1616940/7da2ad45-f579-406e-8da3-0cf334419b11)

You can see that on *.inc and *.txt lines, the icon is missing, this leads to screen misalignment

After selecting a file and opening it, the file tree gets broken
<img width="759" alt="image" src="https://github.com/tmux/tmux/assets/1616940/4aafd827-1887-4753-9fd8-15bb5fa4336f">

Without tmux, it's showing fine
<img width="797" alt="image" src="https://github.com/tmux/tmux/assets/1616940/a68048da-f384-4a9c-8aa9-10643bf0b3a8">

I've tried 2 different nerd fonts, and different terminals (all are on Windows; but all mintty based, as windows terminal doesn't support tmux).

I've tried starting with/without utf8 flag (-u)
I've add exports to LC_ALL, LANG, LC_TYPE, and LANGUAGE to en_US.UTF-8 and en_GB.UTF-8 (both are listed as supported with "locale -a").

My script for starting a tmux session is this:
```shell
tmux -u \
  new-session -s $1 \
  -e LANG=en_GB.UTF-8 \
  -e LC_ALL=en_GB.UTF-8 \
  -e LC_TYPE=en_GB.UTF-8 \
  -e LANGUAGE=en_GB.UTF-8 \
  -d
```

Within the tmux session I see:

```shell
$ tmux show-environment
-DISPLAY
-KRB5CCNAME
LANG=en_GB.UTF-8
LANGUAGE=en_GB.UTF-8
LC_ALL=en_GB.UTF-8
LC_TYPE=en_GB.UTF-8
MSYSTEM=CLANG64
SSH_AGENT_PID=61402
-SSH_ASKPASS
SSH_AUTH_SOCK=/tmp/ssh-jakfCCqi6ITZ/agent.61401
-SSH_CONNECTION
-WINDOWID
-XAUTHORITY
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`)
tmux 3.3a

* Platform (`uname -sp`).
MINGW64_NT-10.0-22621 unknown

* $TERM inside and outside of tmux (`echo $TERM`).
Outside:
xterm-256color

Inside:
tmux-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-logs.zip](https://github.com/tmux/tmux/files/13853872/tmux-logs.zip)

**Comment by nicm** [comment]
Most likely this is to do with disagreements about the widths of the characters between tmux, the terminal and vim. Did you try building tmux with utf8proc?

**Comment by markjfisher** [comment]
sorry I switched to just not using tmux in msys2 for now. I haven't tried building from scratch for msys2, if I get a chance I'll take a look at this.
