### ISSUE TITLE
Feature request: don't resize hidden panes on select-pane -Z

### ISSUE THREAD

**Issue by sergei-grechanik** [tmux/tmux#3802]
`select-pane -Z` allows switching panes without zooming out. However, when you switch away from a zoomed-in pane, it will be resized to its original unzoomed state while hidden (and then it will be resized back to the zoomed state when returning to it). This causes issues with apps like vim that cannot restore the original state precisely after resizing back and forth (although vim tries to do its best).

The easiest way to reproduce is to run something like
```
while true; do stty size; sleep 0.5; done
```
in one pane, then create another pane, then zoom in to the original pane, then switch between them with something like `select-pane -t .+1 -Z`. The size reported when the pan is hidden will always be different from the size when it is active.

**Comment by nicm** [comment]
Am I meant to guess the tmux version?

**Comment by sergei-grechanik** [comment]
At the time of creating the ticket I checked the master branch. Now I've just checked the master branch again, the behavior is the same, so `tmux next-3.5`, more specifically b54e1fc4f73b34f3f9c671289fef8cbbc7771d9c
