### ISSUE TITLE
Sixel graphics in foot

### ISSUE THREAD

**Issue by nkoehring** [tmux/tmux#3804]
### Issue description

When running tmux inside [foot](https://codeberg.org/dnkl/foot), I get weird behaviour with Sixel graphics. As a test, I run
`convert /some/image -geometry 800x480 sixel:-`, which works fine inside foot directly. Inside tmux, when I run the same command on an empty terminal, the image flickers in for a split-second and then disappears. Running it again (without clearing the terminal) shows the image just as expected. It also works, when I run the command with some content above, but if it is not enough content, the image disappears fully or partially. See screenshot:

![image](https://github.com/tmux/tmux/assets/246402/4e4f9bdc-7cf9-429f-bed8-5ed01dc863e0)

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux next-3.4` (compiled from [current master](https://github.com/tmux/tmux/commit/e809c2ec359b0fd6151cf33929244b7a7d637119)) 
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`):
[tmux-server-190075.log](https://github.com/tmux/tmux/files/13871208/tmux-server-190075.log)
[tmux-out-190075.log](https://github.com/tmux/tmux/files/13871209/tmux-out-190075.log)
[tmux-client-190073.log](https://github.com/tmux/tmux/files/13871210/tmux-client-190073.log)

**Comment by nicm** [comment]
Where is the SIXEL file?

I don't see any SIXEL output in this log.
