### ISSUE TITLE
Include resurrect capabilities in base tmux

### ISSUE THREAD

**Issue by effinsky** [tmux/tmux#3805]
### Issue description

Resurrection capabilities missing in out-of-the-box tmux experience. At this point, though limited by my own workflow perspective, I cannot imagine using tmux without https://github.com/tmux-plugins/tmux-resurrect. When I found out resurrect existed, it opened up ways to setup tmux flows for myself in ways that would not have been feasible before. Not sure what percentage of users actually utilize resurrect, but to those that do not, the cost of having it included in base tmux would be virtually none. To me and others who prefer a minimalist approach and would rather not have to do with any plugins to have full basic functionality -- including resurrect -- it would be a win if we could have this included in tmux out of the box.

For reference, while for me zellij does not compare, still they have included resurrect capabilities that way: https://zellij.dev/documentation/session-resurrection

**Comment by krader1961** [comment]
I'm a strong thumbs down on this proposal. The tmux-resurrect project promises far more than it can deliver. The fact it even has a `set -g @resurrect-processes ':all:'` tells me the project owner is all but hoping you will use their plugin to kill your system. Not to mention it has an open pull request that is 9 years old and 27 of the 31 open pull requests are older than 6 months! Consider that one of the reasons I use tmux is to manage connections via SSH to the VMs (virtual machines) I use to verify behavior of the programs I work on. Tmux-resurrect can't restore those SSH connections let alone the programs running on those VMs. Nor would I want it to do so.

Also, consider issues like https://github.com/tmux-plugins/tmux-resurrect/issues/484 which ask if tmux-resurrect can save and restore env vars. JFC! Of course not. The idea that tmux-resurrect can do anything more than reliably restore the Tmux sessions/windows/panes (not including the state of the programs in those windows) is nonsense.

> Not sure what percentage of users actually utilize resurrect, but to those that do not, the cost of having it included in base tmux would be virtually none.

Wrong. Even if the feature is not enabled by default the cost is more bugs being introduced into the Tmux project and code bloat.

I will stop upgrading tmux on my systems if this functionality is ever merged and would consider forking the project myself or using a fork created by someone else.

**Comment by krader1961** [comment]
I'll also point out that I do want a specific Tmux environment when I start it after rebooting my system. But I don't use tmux-resurrect to create that environment. I use an Elvish (a modern alternative to crufty POSIX shells) shell script that uses commands such as `tmux new-window` and `tmux send-keys` to create my desired Tmux environment. Which doesn't require me to manually "save" my Tmux configuration and doesn't attempt to restore the state of the processes running in those Tmux sessions (which is impossible except in very trivial ways). My Elvish program correctly handles establishing things like SSH connections to my VMs (something tmux-resurrect can't do). Again, this functionality doesn't belong in Tmux. Tmux should only provide mechanisms to make creating a particular Tmux environment possible. Which it does via existing commands such as `tmux  new-window`.

**Comment by krader1961** [comment]
This has also been requested in the past. See, for example, https://github.com/tmux/tmux/issues/3100. That is the only one that is obviously analogous to this issue that I could find. But there are many more that reference the `tmux-resurrect` plugin. Such as https://github.com/tmux/tmux/issues/231. I am pretty confident that @nicm will never merge the `tmux-resurrect` project, @effinsky. If he does merge it I will conclude @nicm has suffered brain damage. :-)

**Comment by effinsky** [comment]
I am not suggesting merging the plugin into the base tmux code. I am suggesting finally adding some sensible resurrect capability into tmux. that is all. in light of this, I believe the arguments above dismissing this proposal are not to the point. you have your workflow, great. but I would like tmux to be able to keep and restore its own state. to manage itself.

**Comment by krader1961** [comment]
@effinsky, You need to be more precise about the state you expect to be saved/restored and what triggers those operations. For example, should the state be saved automatically whenever the state changes? Saved periodically such as every ten minutes? Saved only when the user manually initiates saving the state? Should a saved state be automatically restored when starting tmux with no options? Manually restored? What happens to the current state when restoring the saved state? Are all existing windows, panes, etc. destroyed?

**Comment by krader1961** [comment]
Also, keep in mind the Tmux state includes more than just the sessions, windows and panes. You can alter the Tmux configuration (e.g., formats and bindings) while it is running via its command prompt reached via prefix-`:`. Should those changes to the running configuration be saved and restored?
