### ISSUE TITLE
UTF-8 broke Alt+UTF-8 char shorcuts

### ISSUE THREAD

**Issue by sardemff7** [tmux/tmux#381]
I use a keyboard layout (bépo) with UTF-8 characters (namely `«` and `»`) on the number line. I use `Alt+<number>` shortcuts in WeeChat to switch buffers, and with the tmux 2.2 update, it broke for these two keys. WeeChat (or zsh for that matter) only prints `«`, `Alt` being simply ignored.

**Comment by nicm** [comment]
Run "tmux -Ltest -f/dev/null -vvvvv new" then press the problem key once then exit and send me the tmux-server*.log file please.

**Comment by sardemff7** [comment]
[Here is the log](https://gist.github.com/aff6f3838bbfd0d31eb69ca24eaf3afe). I run tmux, pressed `Alt-«`, then `Return` then `Ctrl-D`.

**Comment by nicm** [comment]
It looks like your terminal does not distinguish between « and M-«:

1461583953.726437 keys are 2 (\302\253)
1461583953.726519 UTF-8 key \302\253 0xab
1461583953.726531 complete key \302\253 0xab

\302\253 is U+00AB alone, it would need to be proceeded by a \033 in order to be M-«.

This probably worked before by accident because we did not support Unicode keys, so it may have been mangled into two separate keys. What does the log look like if you do the same with 2.1?

You could try doing something like this in .tmux.conf (where M-2 is whatever key it is you expect):

bind -n « send M-2

**Comment by nicm** [comment]
This makes sense because I presume on your keyboard it is something like 2 gives "2" and M-2 gives "«" (not M-2 which is ^[2).

For whatever reason 2.1 was probably sending an actual M-2 (that is, ^[2) which is what weechat is probably expecting. So I expect you will need to:

- Configure tmux to translate « into M-2 (with the bind command I gave above).
- Configure weechat to change window on « rather than M-2.
- Do something else (configure your keyboard or terminal to send M-2 instead of «?).

**Comment by sardemff7** [comment]
[Log for 2.1](https://gist.github.com/128e668ac3d1a5c7bfea7a9f70d67742)

On my keyboard ([bépo](//download.tuxfamily.org/dvorak/wiki/images/Carte-bepo-complete.png)), the key `2` sends "«", `Shift-2` sends "2", and `Alt-2` has no specific keysym associated with.
Without tmux, zsh is showing "«" with the key alone, and a "`<ffffffff>`" for `Alt-2`, so my terminal seems to send different values for those two.

Binding "«" works, but it is not the correct behaviour, since I cannot type "«" any more.

**Comment by nicm** [comment]
So if you are pressing Alt-2 in these logs, tmux (neither 2.1 or 2.2) is not seeing it as different from «. Possibly the difference to zsh is because tmux turns on keypad mode. Anyway, you need your terminal to be sending ^[2 (that is, \033 then 2) instead of « for Alt-2.

**Comment by sardemff7** [comment]
Rechecked with 2.1, [here is the log](https://gist.github.com/70db466897574676864073726aa42356). I can see that `\033` you want, and it prints as “expected” the weird `<ffffff>` char, which I can see in the tmux log too.
So 2.1 is working as expected (probably conflicted in the previous log because I run everything under tmux, so I rechecked with a bare terminal).
In this log, and the first one, I can confirm I pressed `Alt-2`, then `Return`, then `Ctrl-D`.

**Comment by nicm** [comment]
Yes, you need to test them in the same way.

Your terminal is sending something different for 2.1 and 2.2. This is M-«:

1461588325.980461 keys are 3 (\033\302\253)

Which probably means we are sending something different on initialization of the terminal.

Can you show me the output of "tmux info" from /inside/ tmux for both 2.1 and 2.2 (mark which is which)?

**Comment by nicm** [comment]
(You can do "tmux info >file", but do it from inside tmux.)

**Comment by sardemff7** [comment]
[Here is the 2.1 → 2.2 diff](https://gist.github.com/02cdcd8e4256d60bdee622f04796b65a)

**Comment by nicm** [comment]
I do not see any changes from 2.1 to 2.2 to what we send to the terminal that could cause it to send any different keys.

Can you send me the two tmux-out*.log files for 2.1 and 2.2?

**Comment by sardemff7** [comment]
[tmux-out.log 2.1 as Base64](https://gist.github.com/9ff88e7268b332106922c064064df5b9)
[tmux-out.log 2.2 as Base64](https://gist.github.com/f6fda5dd05fdf9a832a786a18a0ef240)

**Comment by nicm** [comment]
Are you sure that you are running both of these in the terminal directly? Your original logs show you were running tmux 2.2 inside tmux, and there are differences in the output which should not be there if TERM is the same in both. The logs are useless if we are not comparing like with like.

Can you please do this again and send me matching tmux-server*.log and tmux-out*.log files for both 2.1 and 2.2, run in the same terminal? If possible add them to the issue directly (you will need to rename them to add .txt) rather than gist which requires more faffing around.

**Comment by sardemff7** [comment]
New clean files attached (sorry for the other files, I didn’t see we could attach files directly until the tmux-out.log, and then I only tried to send an archive, didn’t test the `.txt` trick).

Same key sequence, same terminal, no nesting, just tweaked the command line to use `-Ltest2.1` and `-Ltest2.2`.
[tmux-client-2.1.txt](https://github.com/tmux/tmux/files/234784/tmux-client-2.1.txt)
[tmux-out-2.1.txt](https://github.com/tmux/tmux/files/234785/tmux-out-2.1.txt)
[tmux-server-2.1.txt](https://github.com/tmux/tmux/files/234786/tmux-server-2.1.txt)
[tmux-client-2.2.txt](https://github.com/tmux/tmux/files/234787/tmux-client-2.2.txt)
[tmux-out-2.2.txt](https://github.com/tmux/tmux/files/234788/tmux-out-2.2.txt)
[tmux-server-2.2.txt](https://github.com/tmux/tmux/files/234789/tmux-server-2.2.txt)

**Comment by nicm** [comment]
Okay this is completely different, now 2.2 is seeing the \033 as well, so it is not the terminal sending something different.

**Comment by nicm** [comment]
Please apply this: [tty-keys.c.diff.txt](https://github.com/tmux/tmux/files/234929/tty-keys.c.diff.txt)

And a) let me know if it works and b) send me a server log as before.

It may apply to 2.2 or you may need to check out master.

**Comment by nicm** [comment]
Also let me know if it breaks any other keys :_).

**Comment by sardemff7** [comment]
It works! And I cannot spot any breakage easily. If you want I can patch my system tmux and see in the next days if anything breaks.
[tmux-client-2.2-patched.txt](https://github.com/tmux/tmux/files/234982/tmux-client-2.2-patched.txt)
[tmux-info-2.2-patched.txt](https://github.com/tmux/tmux/files/234983/tmux-info-2.2-patched.txt)
[tmux-out-2.2-patched.txt](https://github.com/tmux/tmux/files/234984/tmux-out-2.2-patched.txt)
[tmux-server-2.2-patched.txt](https://github.com/tmux/tmux/files/235001/tmux-server-2.2-patched.txt)

**Comment by nicm** [comment]
Yes try this instead though please it fixes a minor problem with xterm-keys 
[tty-keys.c.diff.2.txt](https://github.com/tmux/tmux/files/235006/tty-keys.c.diff.2.txt)

**Comment by nicm** [comment]
Actually hold on, from your log it looks like it isn't passing through the \033.

**Comment by nicm** [comment]
Oh never mind, it just doesn't show the M- for Unicode keys.

**Comment by sardemff7** [comment]
With the second patch, works too.
[tmux-client-2.2-patched2.txt](https://github.com/tmux/tmux/files/235010/tmux-client-2.2-patched2.txt)
[tmux-info-2.2-patched2.txt](https://github.com/tmux/tmux/files/235011/tmux-info-2.2-patched2.txt)
[tmux-out-2.2-patched2.txt](https://github.com/tmux/tmux/files/235012/tmux-out-2.2-patched2.txt)
[tmux-server-2.2-patched2.txt](https://github.com/tmux/tmux/files/235013/tmux-server-2.2-patched2.txt)

**Comment by nicm** [comment]
Ok cool, well I will need to test it for a while.

**Comment by sardemff7** [comment]
It seems to break (one of) my prefix(es), `M-i`.

**Comment by nicm** [comment]
How are you configuring the prefix?

**Comment by sardemff7** [comment]
```
set -g prefix M-l
bind-key M-l send-keys M-l
```

**Comment by nicm** [comment]
Yes, I see, try this instead: 
[tty-keys.c.diff.3.txt](https://github.com/tmux/tmux/files/236071/tty-keys.c.diff.3.txt)

**Comment by sardemff7** [comment]
It works, do you want logs too?

**Comment by nicm** [comment]
No it is ok thanks, just let me know if you see anything else wrong.

**Comment by nicm** [comment]
I have applied this to master now. Thanks.

**Comment by tek** [comment]
this seems to have broken the escape key, pressing it once floods the terminal with control characters until another key is pressed.
