### ISSUE TITLE
`C-9` is being consumed or otherwise not passed on to neovim, in terminal

### ISSUE THREAD

**Issue by mmynsted** [tmux/tmux#3815]
## Details

* Darwin arm
* term 
   * outside `xterm-256color`
   * inside `tmux-256color` 

---

## Issue description:

The `C-9` (Control 9) key combination is being consumed or otherwise not  passed on to neovim in terminal (any terminal) when in a tmux session. Outside of tmux the key combination is sent. There is no known key binding for `C-9` defined for tmux that I can find.

The problem exists both with a config and without a config. (Following instructions from https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md)

[tmux-server-32586.log](https://github.com/tmux/tmux/files/13968131/tmux-server-32586.log)
[tmux-client-32584.log](https://github.com/tmux/tmux/files/13968132/tmux-client-32584.log)
[tmux-out-32586.log](https://github.com/tmux/tmux/files/13968133/tmux-out-32586.log)

Outside of tmux the key combination is passed as expected.
Inside of tmux, regardless of the terminal emulator, and regardless of the use of a config file, the key combination is not passed through. 

I do not see any explanation or issues (open or closed) for this.

**Comment by krader1961** [comment]
Ctrl-9 only sends a literal 9 unless extended key modifiers are enabled. Which means, among other things, putting `extended-keys on` in your *.tmux.conf*.

**Comment by murtaza64** [comment]
What prints out if you run `cat` in tmux then press C-S-n?

**Comment by murtaza64** [comment]
There's a workaround, which is to map C-9 or C-S-n to a macro (e.g. `:mycommand<CR>` at your outer terminal emulator level (e.g. alacritty) though that'll make your shortcut only work when working in your configured terminal.
