### ISSUE TITLE
tmux popup window can not copy text in neovim

### ISSUE THREAD

**Issue by yifan0414** [tmux/tmux#3817]
### Issue description

When I copy text in neovim in tmux popup windows, the text correctly copy to tmux buffer. But not in my system clipboard. (This situation only in popup window).

https://github.com/tmux/tmux/assets/45898625/68364f92-af96-4384-a55d-e0d0811ead97

**Basic thing is when i use `tmux load-buffer -w -` in **popup window**, it only copy to tmux buffer, not to my system clipboard(mac or windows). **but it work normally in basic window**.**

I don't know which thing is wrong, `tmux-yank`, `neovim`, `tmux`

1. The neovim clipboard config
```
  vim.g.clipboard = {
    name = "TmuxClipboard",
    copy = {
      ["+"] = "tmux load-buffer -w -",
      ["*"] = "tmux load-buffer -w -",
    },
    paste = {
      ["+"] = "tmux save-buffer -",
      ["*"] = "tmux save-buffer -",
    },
    cache_enabled = 0,
  }
vim.opt.clipboard = "unnamedplus" -- allows neovim to access the system clipboard
```

2. The `.tmux.conf`

```
set -g set-clipboard on
bind-key -T copy-mode-vi DoubleClick1Pane select-pane\; send-keys -X select-word
bind-key -T copy-mode-vi TripleClick1Pane select-pane\; send-keys -X select-line
unbind-key -T copy-mode-vi MouseDragEnd1Pane
bind-key -T copy-mode-vi MouseDown1Pane select-pane\; send-keys -X clear-selection

set -g @yank_with_mouse off
set -g @yank_action 'copy-pipe' # or 'copy-pipe-and-cancel' for the default
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
run '~/.tmux/plugins/tpm/tpm'
```

### Required information

Please provide the following information:

* tmux version: the latest commit 
* Platform: Mac and wsl2
* $TERM inside and outside of tmux : xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

#3377

**Comment by krader1961** [comment]
> I don't know which thing is wrong

You should be able to determine "which thing is wrong" using basic debugging steps. Also, the huge number of commands in your Tmux config that include `2> /dev/null` is problematic. That tells me you are cargo cult programming (google the phrase). Discarding stderr output in that fashion is always a red flag.

**Comment by krader1961** [comment]
Also, why do you have statements like this in your *tmux.rc*:

```
run -b 'tmux bind -t vi-copy v begin-selection 2> /dev/null || true'
```

I don't see the point of that statement. Why don't you simply execute the binding without shelling out to a `tmux` command that throws away error messages? The use of the `-b` option to run the command in the background is especially confusing given the command being run.  I think you have no idea what you are doing.

**Comment by SnakeHit** [comment]
> > I don't know which thing is wrong
> 
> You should be able to determine "which thing is wrong" using basic debugging steps. Also, the huge number of commands in your Tmux config that include `2> /dev/null` is problematic. That tells me you are cargo cult programming (google the phrase). Discarding stderr output in that fashion is always a red flag.

thanks for reply, I'm sorry for my shallow knowledge. I am learning this gradually. In my opinion, the key of this problem is the pipe between tmux buffer and system clipboard which tmux-yank need to resolve.

**Comment by krader1961** [comment]
@SnakeHit, I am curious where you got the idea to include statements like the following in your *tmux.conf*:

```
run -b 'tmux bind -t vi-copy v begin-selection 2> /dev/null || true'
```

That statement makes no sense. There is no need to execute an external Tmux command to modify the key bindings of the current Tmux process in that fashion. That indirection makes no sense..

**Comment by SnakeHit** [comment]
I just want the tmux copy mode like vim copy mode, and copy this code for convenience from somewhere.  I know a little about tmux config at beginning. but I think this is not crucial about this problem. even I comment it,   problem also appear.

> @SnakeHit, I am curious where you got the idea to include statements like the following in your _tmux.conf_:
> 
> ```
> run -b 'tmux bind -t vi-copy v begin-selection 2> /dev/null || true'
> ```
> 
> That statement makes no sense. There is no need to execute an external Tmux command to modify the key bindings of the current Tmux process in that fashion. That indirection makes no sense..

**Comment by krader1961** [comment]
> I just want the tmux copy mode like vim copy mode, and copy this code for convenience from somewhere. I know a little about tmux config at beginning. but I think this is not crucial about this problem. even I comment it, problem also appear.

I understand that English is not your native language. Nonetheless, you did not tell us where you got the idea that a command such as this makes sense:

```
run -b 'tmux bind -t vi-copy v begin-selection 2> /dev/null || true'
```

Wherever you copied that code from has no idea what they are doingl

**Comment by SnakeHit** [comment]
Because I press `v`, I can selection text in tmux copy-mode when I add this code.

**Comment by SnakeHit** [comment]
> > I just want the tmux copy mode like vim copy mode, and copy this code for convenience from somewhere. I know a little about tmux config at beginning. but I think this is not crucial about this problem. even I comment it, problem also appear.
> 
> I understand that English is not your native language. Nonetheless, you did not tell us where you got the idea that a command such as this makes sense:
> 
> ```
> run -b 'tmux bind -t vi-copy v begin-selection 2> /dev/null || true'
> ```
> 
> Wherever you copied that code from has no idea what they are doingl

Because I press v, I can selection text in tmux copy-mode when I add this code.

**Comment by SnakeHit** [comment]
```
bind-key -Tcopy-mode-vi 'v' send -X begin-selection

bind-key -Tcopy-mode-vi 'H' send -X start-of-line

bind-key -Tcopy-mode-vi 'L' send -X end-of-line
```
Does this is the proper config

**Comment by SnakeHit** [comment]
I take back what I said earlier. The issue lies with the `tmux set-buffer -w` and `tmux load-buffer -w` in the popup window. while tmux-yank use `tmux send -X copy-pipe-and-cancel "cat | clip.exe" or "pbcopy"`. It works normally in the popup windows.

**Comment by SnakeHit** [comment]
After my test, OSC 52 does not work on popup either.

**Comment by nicm** [comment]
Not entirely certain this works in popups, although I don't see any reason it wouldn't on a quick look.

**Comment by yifan0414** [comment]
I current use below command to adress this problem in popup..
```
vim.api.nvim_set_keymap("v", "<leader>y", [["+y :call system('clip.exe', @+)<cr>]], { noremap = true, silent = true })
```

**Comment by nicm** [comment]
Ah, no OSC 52 does not work inside popups.

**Comment by yifan0414** [comment]
> Ah, no OSC 52 does not work inside popups.

oh, my fault, use `C-a + :` open command line , then input `display-popup` work normal.
I use below popup reuse code work unnormal
```
# set M-p open/close popup window
bind-key -n -N 'Toggle popup window' M-q if-shell -F '#{==:#{session_name},popup}' {
    detach-client
} {
    display-popup -d "#{pane_current_path}" -xC -yC -w 90% -h 95% -E 'tmux attach-session -t popup || tmux new-session -s popup'
}
```
