### ISSUE TITLE
tmux crashing when adding to copy buffer

### ISSUE THREAD

**Issue by Abbotta4** [tmux/tmux#3818]
### Issue description

tmux crashes when trying to put something into the copy buffer with zsh on Cygwin. The crash did not happen with bash.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.2`
* Platform (`uname -sp`): `CYGWIN_NT-10.0-22621 unknown`
* $TERM inside and outside of tmux (`echo $TERM`): outside: `xterm`, inside: `screen`
* Logs from tmux (`tmux kill-server; tmux -vv new`): 
[tmux-client-2229.log](https://github.com/tmux/tmux/files/14009162/tmux-client-2229.log)
[tmux-out-2231.log](https://github.com/tmux/tmux/files/14009163/tmux-out-2231.log)
[tmux-server-2231.log](https://github.com/tmux/tmux/files/14009166/tmux-server-2231.log)

**Comment by krader1961** [comment]
Saying it happens with Zsh but not Bash is not helpful. A Tmux server log is helpful but less so when the Tmux server dies due to something like a SIGSEGV event. You also don't tell us how you "put something into the copy buffer". We shouldn't have to guess what you did to trigger the failure.

You should enable core dumps (typically by running `ulimit -c unlimited`) then starting a new Tmux server and triggering the failure. That should result in a core dump file that can be examined using a tool like `gdb` to show the function backtrace via its `bt` command.

**Comment by Abbotta4** [comment]
> You also don't tell us how you "put something into the copy buffer".

tmux crashes any time I put something into the copy buffer. I enter copy mode with prefix+'[' (with `-f/dev/null`, it's `C-b [`) and I either kill a line with `C-k` or kill a selection with `C-SPC`, select text, `C-w`. While trying either method, tmux crashes.
> You should enable core dumps (typically by running `ulimit -c unlimited`) then starting a new Tmux server and triggering the failure. That should result in a core dump file that can be examined using a tool like `gdb` to show the function backtrace via its `bt` command.

[tmux.exe.stackdump.gz](https://github.com/tmux/tmux/files/14022445/tmux.exe.stackdump.gz)
I built tmux 3.2 myself by checking out the 3.2 tag, and following the [build instructions in the wiki](https://github.com/tmux/tmux/wiki/Installing#from-version-control). I configured with `--enable-debug` to enable debug symbols and then allowed coredumps with `ulimit -c unlimited`. I ran `tmux -f/dev/null -Ltest new`, echoed "test" and then tried to copy it in copy mode with `C-k`. tmux crashed and the above .stackdump file was generated. I also tried to generate a bt by running tmux with gdb to see if I could generate a core dump from that, but when it crashed, it printed `Program terminated with signal SIGHUP, Hangup.` and `(gdb) generate-core-file` informed me there was no process to dump. Please let me know what else I should do to provide a proper backtrace or if there is any more info I can provide.

**Comment by nicm** [comment]
Does this still happen if you build tmux from master?

**Comment by Abbotta4** [comment]
> Does this still happen if you build tmux from master?

I just built master ea7136fb and I can successfully use the copy buffer 👍
I will just use this build until Cygwin updates their repositories. Thank you.
