### ISSUE TITLE
Please describe the issue with new ncurses

### ISSUE THREAD

**Issue by avih** [tmux/tmux#3819]
Issue #3699 describes a crash with new ncurses (and slightly older tmux), and the patch required for backporting (slightly) older tmux to address this crash.

I would have posted that question there, but that issue is locked for further comments.

would you please describe what got broken between tmux and new ncurses, and what's the gist of the fix?

Looking at the commits, it seems that some non-portable function[s] was used, which needs a local/compat implementation of it?

The linked patch is fairly big, and I wasn't able to figure that out from the commit messages. It _seems_ to me like the linked patch might not be minimal.

Thanks in advance.

**Comment by nicm** [comment]
What linked patch?

**Comment by avih** [comment]
In this comment: https://github.com/tmux/tmux/issues/3699#issuecomment-1723158807

**Comment by nicm** [comment]
That's not a patch that's just the top of master when that person built. This bf636d9575806134ca7efd917ee0d54e9330ae86 is the one that will stop it exiting (but stuff like `Ms` will no longer work).

**Comment by avih** [comment]
> This [bf636d9](https://github.com/tmux/tmux/commit/bf636d9575806134ca7efd917ee0d54e9330ae86) is the one that will stop it exiting

Thanks. So can you please describe what got broken between tmux and new ncurses?

**Comment by nicm** [comment]
ncurses added much more strict validation (for some CVE IIRC, possibly nonsense but I don't know), which means some functions returned NULL when previously they did not with some of the custom capabilities tmux uses. They can't work without giving ncurses some extra information (which there are new APIs to do).

**Comment by avih** [comment]
Much appreciated.
