### ISSUE TITLE
attach processes to tmux session from scripts or systemd service

### ISSUE THREAD

**Issue by thkoch2001** [tmux/tmux#3824]
I have qemu VMs that get started as systemd services. I'd like to attach their stdio to a tmux window. So I tried this in the service file:

    ExecStart=tmux new-session -A -d -s microvm -n "%i" "exec qemu [...]"

This worked fine when the tmux session "microvm" did not exist. Once it exists, the service fails with:

    open terminal failed: not a terminal

The reason seems to be, that `new-session` does not honor the `-d` flag when the session exists. One can see this by running the following two times in a row, assuming there is no session named "test":

    tmux new -A -s test -d

The first time, the command returns. The second time, the existing tmux session is attached to the current terminal, the `-d` flag is not honored.

So I'm searching for a way to attach a process to a tmux session from a non tty environment, create the session if necessary and preferably have no race conditions.

I also tried command mode but did not find a solution.

I'm not sure whether this issue is a feature request or a bug. From the documentation it seems to me, that the `-d` flag is not really defined for the case that the session already exists. I'd argue it should work the same way all times.

**Comment by nicm** [comment]
Do you mean `-D`?

**Comment by thkoch2001** [comment]
Thank you @nicm for replying, but no, I do not mean -D. I just tested `tmux new -A -s test -d -D` and `tmux new -A -s test -D` and both commands cause the terminal to get attached.

This is also how I understand the manpage. Giving `-D` to `new-session` only has an effect if `-A` is given **and** the session already exists. Then it should mean: "any **other** clients attached to the session are detached" (manpage, attach-session).

**Comment by thkoch2001** [comment]
This [SO question](https://unix.stackexchange.com/questions/515935/tmux-how-to-specify-session-in-new-window) gave me the hint that I could specify the target session for the `new-window` command with `-t $SESSION:`.

Now my systemd service looks like this:

```
ExecStartPre=-tmux new -s microvm -d
ExecStart=tmux new-window -t microvm: -n "%i" qemu [...]
```

This will cause an ugly line in the logs saying "duplicate session: microvm" in case the session already exists but otherwise it does what I want (in a not so elegant way).

Note the minus before tmux in the ExecStartPre line to avoid the service to fail in case the session already exists.

I could also have used `has-session`, e.g.:

    tmux has-session -t test || tmux new-session -s test -d

But has-session prints "can't find session: test" in case the session does not exists.

Please feel free to close this issue if you don't want to take it as a feature request for a more elegant solution.

**Comment by nicm** [comment]
There is no point in combining `-A` and `-d`. `-A` is asking to attach the session if it already exists, so it doesn't make sense to also ask not to attach with `-d`.

You can't use `new-session` to create a window in an existing session, that's what `new-window` is for.

You are probably best with something like `tmux new -dnfoo mycommand || tmux neww -tfoo: mycommand`.

**Comment by thkoch2001** [comment]
If you want to turn this in a feature request, I believe the most elegant way would be an additional option to new-window: "Create target session if it does not exist yet" - I just don't know which letter to use for such an option.
