### ISSUE TITLE
can't bind both MouseDown2Pane and S-MouseDown2Pane

### ISSUE THREAD

**Issue by Aeyk** [tmux/tmux#3825]
### Issue description
I can't bind both MouseDown2Pane and S-MouseDown2Pane, only MouseDown2Pane takes. 

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux -V
tmux 3.2a
* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
outside: xterm-256color
inside: tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
* .tmux.conf
```
set -g mouse on
bind-key -n S-MouseDown2Pane run "tmux set-buffer -b clipboard \"$(xsel -bo)\"; tmux paste-buffer -b clipboard; tmux delete-buffer -b clipboard"
bind-key -n MouseDown2Pane run "tmux set-buffer -b primary_selection \"$(xsel -po)\"; tmux paste-buffer -b primary_selection; tmux delete-buffer -b primary_selection"
```
* `xsel -bo && xsel -po` are not the same
* `tmux kill-server; tmux -vv new -f ~/.tmux-copy-mouse` logs

[tmux-client-3150623.log](https://github.com/tmux/tmux/files/14084248/tmux-client-3150623.log)
[tmux-out-3150625.log](https://github.com/tmux/tmux/files/14084249/tmux-out-3150625.log)
[tmux-server-3150625.log](https://github.com/tmux/tmux/files/14084251/tmux-server-3150625.log)

**Comment by nicm** [comment]
Show (attach) server log please.

**Comment by Aeyk** [comment]
Sorry to be a bother, this still appears to an issue for me as of commit 608d113486835515e7a89b1511704440c68ae817.

tmux -V
tmux next-3.5

[tmux-client-273231.log](https://github.com/tmux/tmux/files/14280074/tmux-client-273231.log)
[tmux-out-272802.log](https://github.com/tmux/tmux/files/14280075/tmux-out-272802.log)
[tmux-server-272802.log](https://github.com/tmux/tmux/files/14280076/tmux-server-272802.log)

**Comment by nicm** [comment]
Looks like your terminal does not send anything different for Shift:
~~~~
$ grep mouse.input tmux-server-272802.log
1707917698.452078 /dev/pts/0: mouse input (SGR): \033[<1;77;16M
1707917698.539718 /dev/pts/0: mouse input (SGR): \033[<1;77;16m
1707917700.556257 /dev/pts/0: mouse input (SGR): \033[<1;77;16M
1707917700.644084 /dev/pts/0: mouse input (SGR): \033[<1;77;16m
~~~~
Shift should have 5 in the first field rather than 1.

**Comment by Aeyk** [comment]
Oh, thank you. I'll will try with another terminal emulator .
