### ISSUE TITLE
PATH environment variable is modified

### ISSUE THREAD

**Issue by r10r** [tmux/tmux#3828]
### Issue description

The PATH environment variable is modified in versions > **tmux 3.2a**.
Other environment variables are not affected.

I noticed this after upgrading from **tmux 3.2a** to **tmux-3.3a_git20230428-r0** on alpine linux.

Tested with **tmux-3.3a_git20230428-r0** (alpine packages) and with build
from source ea7136fb838a2831d38e11ca94094cea61a01e3a

```bash
devpod-dev-0:~#  export PATH=/mynewbin:/usr/sbin:/usr/bin:/sbin:/bin
devpod-dev-0:~#  tmux new-session -A -s main
devpod-dev-0:~# env | grep ^PATH
PATH=/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
devpod-dev-0:~# tmux showenv -g | grep ^PATH
PATH=/mynewbin:/usr/sbin:/usr/bin:/sbin:/bin
```

As a workaround the flags `-e -c /bin/bash` must be appended to keep the **PATH** env.

```bash
devpod-dev-0:~# export PATH=/mynewbin:/usr/sbin:/usr/bin:/sbin:/bin
devpod-dev-0:~# tmux new-session -A -s main -e -c /bin/bash
devpod-dev-0:~# env | grep ^PATH
PATH=/mynewbin:/usr/sbin:/usr/bin:/sbin:/bin
devpod-dev-0:~# tmux showenv -g | grep ^PATH
PATH=/mynewbin:/usr/sbin:/usr/bin:/sbin:/bin
```

Seems to be the related to #3613

**Comment by nicm** [comment]
I don't know what you're showing me here because it's unclear whether you already have a session called `main` or not. And there are no logs.

Most likely your shell is changing PATH for login shells.

**Comment by r10r** [comment]
@nicm Indeed */etc/profile* has changed after upgrading packages in alpine. (*/etc/profile* is owned by the package  **alpine-baselayout-data**). 
Looking at */proc/$pid/environ* of the shell started by tmux also shows that tmux does not change the environment. 

Sorry for the fuss and thanks for pointing me in the right direction.
