### ISSUE TITLE
Mouse event "x" coordinates max out at ~220 columns

### ISSUE THREAD

**Issue by djvs** [tmux/tmux#3834]
### Issue description

See: https://github.com/ncmpcpp/ncmpcpp/issues/532

Clicking on song seek/progress bar in ncmpcpp on ultrawide monitor only lets me seek to a max of about 50% of the song (~220 columns).  Starting ncmpcpp without tmux, this works fine, however tmux seems to transmit the events down the line incorrectly, including with $TERM spoofed.  

Happens with my normal .tmux.conf as well as a blank one (`-f /tmp/notarealfile`).

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

tmux 3.3a

* Platform (`uname -sp`).

"Linux unknown"  (Linux 6.7.3, x86_64)

* $TERM inside and outside of tmux (`echo $TERM`).

Inside, `tmux-256color`, outside, `xterm-kitty`

* Logs from tmux (`tmux kill-server; tmux -vv new`).

Not sure this is relevant

**Comment by ThomasDickey** [comment]
The problem comes from kitty, rather than tmux.
kitty is using the older xterm mouse protocol.

**Comment by djvs** [comment]
What terminal would work?  Same problem with urxvt, xterm, alacritty...

**Comment by nicm** [comment]
Logs?

**Comment by djvs** [comment]
Figured that was enough - 
[tmux-server-26273.log](https://github.com/tmux/tmux/files/14241692/tmux-server-26273.log)

**Comment by djvs** [comment]
It does seem to write the codes in excess of ~220:

```
1707758716.267516 /dev/pts/0: mouse input (SGR): \033[<0;350;95M
1707758716.267575 /dev/pts/0 mouse 00 at 349,94 (last 349,94) (0)
1707758716.267598 mouse window @0 at 0,0 (491x95)
1707758716.267606 mouse 349,94 on pane %0
1707758716.267615 mouse key is MouseDown1Pane
1707758716.267623 cmd_find_from_mouse: s=$0 0
1707758716.267630 cmd_find_from_mouse: wl=0 1 w=@0 d ncmpcpp
1707758716.267638 cmd_find_from_mouse: wp=%0
1707758716.267645 cmd_find_from_mouse: idx=none
1707758716.267949 cmd_mouse_at: x=349, y=94
1707758716.267956 writing mouse \033[M \377~ to %0
1707758716.267964 input_key_mouse: \033[M \377~
```

So something is getting lost in translation I guess?

**Comment by nicm** [comment]
ncmpcpp is not turning on either of the extended mouse modes supported by tmux (SGR or UTF-8), so the maximum position will be 222. You will need to ask the ncmpcpp developers to add support for SGR mouse mode (UTF-8 is definitely not recommended anymore).

**Comment by djvs** [comment]
Thanks!
