### ISSUE TITLE
Cumbersome nested string comparison format, to set colours, one working other is not.

### ISSUE THREAD

**Issue by freddieventura** [tmux/tmux#3835]
I just want to achieve the following functionality (compatible for 256 colours terminal):
For Window number 7 or 11 : Get a green-ish colour
For Window number 8 or 12 : Get a blue-ish colour
For Window number 9 or 13 : Get a red-ish colour
For Window number 10 or 14 : Get a grey colour

For rest of the findows , either get purple-ish colour

If the window is activated, this colour will be lighter

For the rest of the windows, colour will be yellow.

So I do the following works for activated windows
```
set -g window-status-current-format "#{?#{||:#{==:#I,7},#{==:#I,11}},#[bg=colour157][#I:#W#F],\
#{?#{||:#{==:#I,8},#{==:#I,12}},#[bg=colour63][#I:#W#F],\
#{?#{||:#{==:#I,9},#{==:#I,13}},#[bg=colour131][#I:#W#F],\
#{?#{||:#{==:#I,10},#{==:#I,14}},#[bg=colour145][#I:#W#F],\
#[bg=colour11][#I:#W#F]}}}}"
```

But this doesnt work for non-activated windows
`bad colour: #{?#{||:#{==:#I,7},#{==:#I,11}},colour149,#{?#{||:#{==:#I,8},#{==:#I,12}},colour60,#{?#{||:#{==:#I,9},#{==:#I,13}},colour124,#{?#{||:#{==:#I,10},#{==:#I,14}},colour246,colour183}}}}` 
```
set -g status-bg "#{?#{||:#{==:#I,7},#{==:#I,11}},colour149,\
#{?#{||:#{==:#I,8},#{==:#I,12}},colour60,\
#{?#{||:#{==:#I,9},#{==:#I,13}},colour124,\
#{?#{||:#{==:#I,10},#{==:#I,14}},colour246,\
colour183}}}}"
```

What may be wrong with previous directive?

**Comment by nicm** [comment]
status-bg needs a colour, you want maybe window-status-format or maybe status-style?
