### ISSUE TITLE
Unintended pane synchronization across terminals, even with identical terminals

### ISSUE THREAD

**Issue by KevinGIRAULT** [tmux/tmux#3837]
I am encountering an issue with tmux 3.3a where two distinct terminals, whether from the same or different emulators, are in "mirror" mode when sharing the same tmux session. Actions performed in one terminal are replicated identically in the other terminal, including navigating wee-slack channels and switching tmux windows.

1. Open two terminals, whether from the same emulator or different emulators.
2. Launch tmux in each terminal.
3. Join the same tmux session in both terminals.
4. Perform actions in one terminal. Example : as navigating wee-slack channels or switching tmux windows.
5. Observe the duplication of actions in the other terminal.

- tmux version: 3.3a
- Terminal emulators tested: xfce4-terminal, gnome-terminal, st, kitty
- XFCE et LXQT/i3wm
- tested pane synchronization disabled with the command `Ctrl-b :setw synchronize-panes off` and I verified .tmux.conf

* echo $TERM :
- gnome-terminal : without tmux = xterm-256color ; with tmux = screen-256color
- xfce4-terminal : without tmux = xterm-256color ; with tmux = screen-256color
- st : without tmux = st-256color ; with tmux = screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-268898.log](https://github.com/tmux/tmux/files/14278881/tmux-client-268898.log)
[tmux-client-270257.log](https://github.com/tmux/tmux/files/14278884/tmux-client-270257.log)
[tmux-out-270259.log](https://github.com/tmux/tmux/files/14278886/tmux-out-270259.log)

 Same with test such as `tmux -Ltest kill-server` then `tmux -vv -Ltest -f/dev/null new`

 
the tmux-server log is 300MB (!!!), impossible to attach

If additional information is needed, feel free to ask.

**Comment by nicm** [comment]
You're looking at the same session, this is how tmux works...

**Comment by KevinGIRAULT** [comment]
It's strange. The same session but not the same window.

If you're saying that's normal (after a few months of use, I hadn't noticed), then it makes tmux much less efficient for the workflow.

One session for side projects, one session for professional projects, etc.
And within the session for professional projects, multiple windows with different tools. And each having panes.

:(

**Comment by bioe007** [comment]
For the behavior you want just start different tmux sessions for each 'project'. Look here and read about starting named sessions and reattaching to them: 
https://www.man7.org/linux/man-pages/man1/tmux.1.html#CLIENTS_AND_SESSIONS
