### ISSUE TITLE
3.4 on rxvt-unicode leaks OSC10/11 response

### ISSUE THREAD

**Issue by mkoskar** [tmux/tmux#3838]
When attaching session inside `rxvt-unicode (urxvt) v9.31 - released: 2023-01-02` following unexpected text is echoed:

` ^[]10;rgb:ae00/ae00/ae00^[^[]11;rgba:0000/0000/0000/e666^[`

To reproduce run: `tmux -vv -f /dev/null -L test new cat`

![screenshot-2024-02-14 1707932557](https://github.com/tmux/tmux/assets/4387891/364a1491-4e91-4110-a83d-4a2e10b6d553)

Issue doesn't occur when downgrading to `tmux 3.3a`. 

* tmux version (`tmux -V`).
`tmux 3.4`

* Platform (`uname -sp`).
`Linux unknown`

* $TERM inside and outside of tmux (`echo $TERM`).
`tmux-256color` and `rxvt-unicode-256color`

* Logs from tmux (`tmux kill-server; tmux -vv new`). 

[tmux-client-78828.log](https://github.com/tmux/tmux/files/14284421/tmux-client-78828.log)
[tmux-out-78830.log](https://github.com/tmux/tmux/files/14284423/tmux-out-78830.log)
[tmux-server-78830.log](https://github.com/tmux/tmux/files/14284424/tmux-server-78830.log)

**Comment by nicm** [comment]
This is a urxvt bug, see previous issues on the subject.

**Comment by mkoskar** [comment]
Ah my bad, I haven't searched closed issues thinking 3.4 is fresh and somehow haven't even thought `urxvt` might be an issue. Actually in the meantime compared it to `xterm` and saw its response has malformed `ST` at the end.

For reference these are the previous issues regarding this: #3470 and #3575
