### ISSUE TITLE
Crash when outputting a Sixel in a one row pane

### ISSUE THREAD

**Issue by ybc37** [tmux/tmux#3839]
I'm really happy to have Sixel support in tmux :heart:

I experienced a crash when outputting Sixel graphics and resizing panes. Though, I don't have logs for the first time it happened, but I found a way to reproduce a crash:

1. Resize a pane to only 1 row
2. Output some Sixel -> crash

Minimal script to reproduce:

```sh
#!/usr/bin/env sh

tmux -f /dev/null -vv new-session -d
tmux split-window -l1
tmux send 'echo -e "\x1bPq#1@\x1b\\"' ENTER;
tmux attach
```

I'm not comfortable to attach the complete server log (including my environment), so it only contains (hopefully useful) parts.

[tmux-server-parts.log](https://github.com/tmux/tmux/files/14288450/tmux-server-parts.log)
[tmux-client-106615.log](https://github.com/tmux/tmux/files/14288451/tmux-client-106615.log)

Let me know if more information is needed.

Environment:

```sh
$ uname -spr && tmux -V && echo $TERM
Linux 6.7.4-arch1-1 unknown # processor is Intel x86_64
tmux 3.4
tmux-256color
```

I tested and reproduced the crash with foot and Konsole, so I guess the terminal doesn't matter.

**Comment by topcat001** [comment]
Thanks for the report! Looks like you have hit an edge case. I'll take a look.

**Comment by topcat001** [comment]
I think this image is technically invalid, as the colour registers have not been defined before use. My quick fix is:
<details>
  <summary>diff</summary>

  ```diff
 diff --git a/image-sixel.c b/image-sixel.c
index 3396a22a..7b91300d 100644
--- a/image-sixel.c
+++ b/image-sixel.c
@@ -489,6 +489,9 @@ sixel_print(struct sixel_image *si, struct sixel_image *map, size_t *size)
 		colours = si->colours;
 		ncolours = si->ncolours;
 	}
+
+	if (ncolours == 0)
+		return NULL;
 	contains = xcalloc(1, ncolours);
 
 	len = 8192;
  ```
</details>
This would bail out when this happens. Can you please try this? I'm thinking about how to properly handle such cases.

**Comment by krader1961** [comment]
My question is what happens if the color registers have been defined but the image simply can't be rendered in a one row pane? If that is handled then your fix is probably sufficient. The old Internet standards wisdom says "be conservative in what you send, be liberal in what you accept". This is known as the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle).

**Comment by topcat001** [comment]
There are actually two issues exposed by the OP's example. The first issue is using colours without defining them. The second issue is when the image render area becomes zero size. I have updated the diff to handle these two cases, please test.

**Comment by ybc37** [comment]
Sorry for using an invalid Sixel. Just looked for a minimal example for reproduction. Actually it's reproducible with any Sixel, e.g. `curl https://raw.githubusercontent.com/saitoha/libsixel/master/images/snake.six`, `lsix`, `convert logo: sixel:`,...

I try to find the time to test your patch later today.

**Comment by ybc37** [comment]
I tested the patch and can confirm that tmux doesn't crash anymore (tested with the invalid and with valid images). Thanks!

**Comment by krader1961** [comment]
@topcat001 I happened to compile tmux without SIXEL support and noticed this warning:

```
input.c:1842:50: warning: unused parameter 'ictx' [-Wunused-parameter]
input_csi_dispatch_sm_graphics(struct input_ctx *ictx)
```

That is the only warning. It is because the body of the `input_csi_dispatch_sm_graphics` function is empty if SIXEL support isn't enabled. While this isn't technically a bug it would be preferable to suppress the warning since any warnings indicate a potential bug. Probably the easiest solution is to replace the `#endif` with this:

```
#else
    #include <assert.h>
    assert(ictx);
#endif
```

**Comment by topcat001** [comment]
Thank you! Noted.

**Comment by topcat001** [comment]
Hi, sorry for the delay. I was waiting for any further feedback. I will post the patch shortly. Regarding bigger, I set it like that as a test. I found that if after resizing the image is no longer visible in the pane, then we can `fatalx` crash in `tty_clamp_area` as `tty_is_visible` will just check bigger and return true. I am looking for a better way to force the visibility check in this situation. Visibility is always true when just drawing a new image (or scrolling it) so we don't encounter this normally.

**Comment by topcat001** [comment]
@nicm I have thought about your comment a bit more and have decided to back out setting bigger like I did. The situation with pane resize is the following:
- If the width is changed, then we `screen_reflow` and delete all images. No problem there.
- If the height is changed, then it is much easier to keep the visible (portions) of the existing images. However, in this case the offsets have to be recomputed and the images trimmed if necessary. This is currently not done properly which leads to mathematical inconsistencies in the functions which calculate dimensions and intersections (e.g., `tty_clamp-area`, `tty_is_visible`, etc.).
So, for now I am going to delete the images on any resize, which should avoid inconsistencies in the computations (and fix the crashes). I am going to follow this up with another PR (soon hopefully) which handles vertical resize better.
Updated diff attached. Please test this again, thank you!
<details>
  <summary>diff</summary>

  ```diff
diff --git a/image-sixel.c b/image-sixel.c
index 3396a22a..7b91300d 100644
--- a/image-sixel.c
+++ b/image-sixel.c
@@ -489,6 +489,9 @@ sixel_print(struct sixel_image *si, struct sixel_image *map, size_t *size)
 		colours = si->colours;
 		ncolours = si->ncolours;
 	}
+
+	if (ncolours == 0)
+		return NULL;
 	contains = xcalloc(1, ncolours);
 
 	len = 8192;
diff --git a/input.c b/input.c
index eb421b28..6ebd9a26 100644
--- a/input.c
+++ b/input.c
@@ -25,6 +25,7 @@
 #include <stdlib.h>
 #include <string.h>
 #include <time.h>
+#include <assert.h>
 
 #include "tmux.h"
 
@@ -1854,6 +1855,8 @@ input_csi_dispatch_sm_graphics(struct input_ctx *ictx)
 		input_reply(ictx, "\033[?%d;0;%uS", n, SIXEL_COLOUR_REGISTERS);
 	else
 		input_reply(ictx, "\033[?%d;3;%dS", n, o);
+#else
+	assert(ictx);
 #endif
 }
 
diff --git a/screen-write.c b/screen-write.c
index 6892d041..a732f093 100644
--- a/screen-write.c
+++ b/screen-write.c
@@ -2283,6 +2283,10 @@ screen_write_sixelimage(struct screen_write_ctx *ctx, struct sixel_image *si,
 		new = sixel_scale(si, 0, 0, 0, y - sy, sx, sy, 1);
 		sixel_free(si);
 		si = new;
+
+		/* Bail out if the image cannot be scaled. */
+		if (si == NULL)
+			return;
 		sixel_size_in_cells(si, &x, &y);
 	}
 
diff --git a/screen.c b/screen.c
index f73a8505..0eaf4698 100644
--- a/screen.c
+++ b/screen.c
@@ -308,12 +308,12 @@ screen_resize_cursor(struct screen *s, u_int sx, u_int sy, int reflow,
 	if (sy != screen_size_y(s))
 		screen_resize_y(s, sy, eat_empty, &cy);
 
-	if (reflow) {
 #ifdef ENABLE_SIXEL
-		image_free_all(s);
+	image_free_all(s);
 #endif
+
+	if (reflow)
 		screen_reflow(s, sx, &cx, &cy, cursor);
-	}
 
 	if (cy >= s->grid->hsize) {
 		s->cx = cx;

  ```
</details>

**Comment by nicm** [comment]
This is fine but do not add asserts please instead put __unused before the ictx parameter (inside an ifdef SIXEL if you like although it's just a hint so it's OK to always have it). An assert is not a great solution here because they can be compiled away with NDEBUG. 

Also your indentation looks wrong in screen-write.c?

**Comment by topcat001** [comment]
Thanks! I have replaced the assert with `__unused` which is more idiomatic. I think the indentation is a diff macro artefact. I have instead attached a diff file.
![sixel-fixes diff](https://github.com/tmux/tmux/assets/22438522/e4bbc90d-24bd-486d-8c54-09ecb3c5febe)

**Comment by rfrancoise** [comment]
Maybe a PR would be easier to manage.

**Comment by 7c6f434c** [comment]
My testing with definitely invalid SIXEL images (accidentally trying `img2sixel -P` in `tmux` instead of `screen` made the server force-exit for me; testcase minimised to `echo -ne '\e\\\ePqC\e\\'`) shows that the patch provided fixes tat case too, thanks.

**Comment by topcat001** [comment]
@nicm this seems stable for now. I also tested some more cases with resizes and garbage data.

**Comment by Heather7283** [comment]
Can confirm that this patch also fixes crashes when trying to display specific images, like this one:
![crash.png](https://github.com/tmux/tmux/assets/142042427/77af29d8-76fe-41e2-bd2a-648af58af21d)
you can test with `chafa -f sixels crash.png` inside tmux, it crashes even in full-size pane. Not sure if I should create a separate issue for this since it also happens in not-one-row panes

**Comment by nicm** [comment]
I have applied this patch now, thanks @topcat001.
