### ISSUE TITLE
Something weird happens to Vim colorshemes (vim issue?)

### ISSUE THREAD

**Issue by LDVSOFT** [tmux/tmux#384]
I tried launching Vim in tmux 2.1, and saw a diffrence in displayed colorshemes when invoked in `gnome-terminal` with or without tmux. Tmux on the left:
![2016-04-25 18-08-38](https://cloud.githubusercontent.com/assets/5804255/14828743/4dc11af8-0bf9-11e6-8c02-9a2b4729c779.png)
Inside `tmux`, `$TERM` is set to `tmux-256color` from `ncurses-term` Ubuntu Xenial package. `gnome-terminal` has `$TERM` set to `xterm-256color`. I don't know is that `vim` or `tmux` issue, but when I tried to compare 256 color palette manually, they are the same (at least, not **so** different):
![2016-04-25 18-18-53](https://cloud.githubusercontent.com/assets/5804255/14828826/b7ee7f4c-0bf9-11e6-9e5b-9f7f1a8dbe70.png)
I will be happy to know how to resolve this issue or know is that a `vim` error.

**Comment by nicm** [comment]
I don't know what is happening here but if the 256 colour script shows the same thing it is hard to see how it is tmux's fault. Are you sure vim isn't checking TERM (for example looking for screen*) instead of using the colors attribute?

**Comment by LDVSOFT** [comment]
So, tmux never changes passed colors attributes? One of my ideas was that vim sends RGB control sequences, and uses some internal palettes to turn them to one of 256.

**Comment by nicm** [comment]
Yes but you said it was using 256 colour palette and if it is doing so then tmux should not change it. If it is using RGB colour then you will need to enable that in tmux.

**Comment by LDVSOFT** [comment]
Okay, then will lookup `vim` settings.

Tmux can RGB, by the way?

**Comment by nicm** [comment]
Yes you need to add Tc in terminal-overrides.
