### ISSUE TITLE
delay after pressing esc key

### ISSUE THREAD

**Issue by gmankab** [tmux/tmux#3843]
### Issue description

i use fish shell with vi mode and neovim

everytime i press esc to enter normal mode, tmux freezes for a second, and after then goes to normal mode

### Required information

* tmux version (`tmux -V`).
`tmux next-3.4`
* Platform (`uname -sp`).
`linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`).
`tmux-256color`
`xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-698372.log](https://github.com/tmux/tmux/files/14305762/tmux-client-698372.log)
[tmux-out-698375.log](https://github.com/tmux/tmux/files/14305764/tmux-out-698375.log)
[tmux-server-698375.log](https://github.com/tmux/tmux/files/14305765/tmux-server-698375.log)

os is fedora silverblue
terminal emulator is black box

**Comment by krader1961** [comment]
From the man page:

```
     escape-time time
             Set the time in milliseconds for which tmux waits after an escape is input to
             determine if it is part of a function or meta key sequences.  The default is 500
             milliseconds.
```

I have this in my *.tmux.conf*:

```
# Default is too slow which is annoying during heavy-use of the copy buffer.
# This might need to be tweaked. This page for emacs evil mode,
# https://www.emacswiki.org/emacs/Evil recommends zero.
set-option -s escape-time 10
```

**Comment by krader1961** [comment]
This situation is due to decisions made over four decades ago by various groups such as the VT-100 and Vi designers. Unless you are connecting to a system over a high latency connection that is likely to fragment the characters you type into multiple packets the legacy `escape-time` value is way too high; that is, by two orders of magnitude.

**Comment by krader1961** [comment]
I'll also point out my value of 10 milliseconds was chosen over a decade ago. It is almost certainly longer than it needs to be. I'm going to experiment with one and zero millisecond. I expect even zero will be reliable given that I don't connect to Tmux sessions over high latency connections. If you do connect to systems hosting Tmux sessions far away from your computer you are likely to need to set the `escape-time` to at least a few milliseconds.

**Comment by gmankab** [comment]
thank you, i set it to 0
