### ISSUE TITLE
Change the default value for `escape-time` to a much lower value

### ISSUE THREAD

**Issue by krader1961** [tmux/tmux#3844]
See issue #3843 for background. The default of 500ms for `escape-time` was arguably too long two decades ago and is definitely too long today. While zero is almost certainly okay for anyone connecting to a Tmux server over a LAN that is probably not appropriate as a default. Even if you are connecting to a Tmux server on the opposite side of the Earth a value of 250ms should be long enough. And for any likely use case (e.g., connecting from a client system on the west coast of the USA to a Tmux server on the east coast) 20ms should be adequate. I recommend changing the default from 500ms to 20ms. Anyone needing to support a high latency connection from a Tmux client more than 3km away can explicitly set a higher value.

**Comment by krader1961** [comment]
While 20ms is almost certainly far longer than it needs to be for most users it is also short enough to be unnoticeable. I think it strikes a better balance than the current default of 500ms. There is no obviously correct default value and there are good arguments for an even smaller default than 20ms. However, I feel a default near 20ms strikes a reasonable trade-off.

**Comment by krader1961** [comment]
This has been asked many times. For example, #2719. And there is a [FAQ](https://github.com/tmux/tmux/wiki/FAQ#what-is-the-escape-time-option-is-zero-a-good-value) for this issue. Nonetheless, I think it is time to significantly reduce the default `escape-time`. It is preferable to support the 99% of users who don't need an `escape-time` longer than a few milliseconds and require the 1% who do need a longer time to explicitly configure a longer time.

**Comment by systemmonkey42** [comment]
I have escape-time set to 10ms, and according to git-log, have had it set that way since around 2018.  Anything longer messes with shell and vim meta keys, and causes vim `timeout` and `ttimeout` settings to behave unpredictably.

**Comment by nicm** [comment]
I think 10 is probably sensible enough nowadays.

**Comment by gmankab** [comment]
yes it would be nice

**Comment by nicm** [comment]
Changed now in OpenBSD, will be in GitHub later, thanks!
