### ISSUE TITLE
Weird characters on tmux startup: ^[]10;rgb:e5e5/e5e5/e5e5^[^[]11;rgb:0000/0000/0000^[

### ISSUE THREAD

**Issue by module0x90** [tmux/tmux#3845]
### Issue description

When starting tmux with no server running, even with "tmux -f /dev/null -L test" it always prints

^[]10;rgb:e5e5/e5e5/e5e5^[^[]11;rgb:0000/0000/0000^[

### Required information

Please provide the following information:

* tmux version 3.4
* Platform Linux unknown - Arch Linux
* $TERM inside: tmux-256color, outside: rxvt-unicode

I am using urxvt/urxvtd, this even happens in xterm. Interestingly "sakura" isn't affected by this.

I found  https://www.reddit.com/r/vim/comments/cnyrva/first_line_occasionally_has_weird_characters_and/, where TaDaaAhah (https://www.reddit.com/user/TaDaaAhah) wrote:
> 
> "For the weird text it looks like ansii query for terminal colors ."
> 

And the "weird characters" there with vim look similar. Could this have to do with:

Query the client terminal for foreground and background colours and if OSC 10
or 11 is received but no colour has been set inside tmux, return the colour
from the first attached client.

How can I switch this (new) behaviour off? When I downgrade to tmux-3.3_a-7 this doesn't happen.

**Comment by nicm** [comment]
This is a bug in rxvt, best bet is to use a different terminal.
