### ISSUE TITLE
Script running with a few errors

### ISSUE THREAD

**Issue by jonnovaretti** [tmux/tmux#3846]
### Issue description

I implemented this script to create a session with three windows with three panels.

There are some issues that I don't know how to solve them

- The first window is not being renamed to `admin`
- The first panel in the first window in not opening the `nvim`
- every last panel don't go to the right directory, they stay in the root

```shell

#!/bin/bash

tmux new-session -d -s coding

# admin window
tmux new-window -t coding:1 -n 'admin' 'nvim'
tmux split-window -h -p 33 -t coding:1
tmux split-window -v -p 50 -t coding:1

tmux send-keys -t coding:1.0 'cd ~/Projects/git/admin' C-m
tmux send-keys -t coding:1.1 'cd ~/Projects/git/admin' C-m
tmux send-keys -t coding:1.2 'cd ~/Projects/git/admin' C-m

# web window
tmux new-window -t coding:2 -n 'web' 'nvim'
tmux split-window -h -p 33 -t coding:2
tmux split-window -v -p 50 -t coding:2

tmux send-keys -t coding:2.0 'cd ~/Projects/git/web' C-m
tmux send-keys -t coding:2.1 'cd ~/Projects/git/web' C-m
tmux send-keys -t coding:2.2 'cd ~/Projects/git/web' C-m

# api window
tmux new-window -t coding:3 -n 'api' 'nvim'
tmux split-window -h -p 33 -t coding:3
tmux split-window -v -p 50 -t coding:3

tmux send-keys -t coding:3.0 'cd ~/Projects/git/api' C-m
tmux send-keys -t coding:3.1 'cd ~/Projects/git/api' C-m
tmux send-keys -t coding:3.2 'cd ~/Projects/git/api' C-m

tmux attach-session -t coding

```

### Required information

Please provide the following information:

* tmux version (`3.3a`).
* Platform (`Darwin arm`).
* $TERM inside and outside of tmux (`xterm-256color`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
`new-session` creates a window so that's probably why your first one is not what you expect.
