### ISSUE TITLE
Background color incorrect when using U+FEOF

### ISSUE THREAD

**Issue by vincentbernat** [tmux/tmux#3848]
### Issue description

Since tmux 3.4, the background is not extended below a character using U+FEOF:

```
printf "\e[44m\u2744\ufe0f \u2744   \n"
```

![image](https://github.com/tmux/tmux/assets/631446/c5cb6ee7-b6f1-45d9-a261-28aa7a7fa3cf)

I suppose this is related to https://github.com/tmux/tmux/commit/8bd17bff49888d11f9cb19955e778bdcbc4eeea6. Previously, the width was incorrect, now it is correct, but no background.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 3.4
* Platform (`uname -sp`): Linux
* $TERM inside and outside of tmux (`echo $TERM`): screen-256color/xterm-256color

**Comment by nicm** [comment]
Logs?
