### ISSUE TITLE
ESC sends unwanted signal to STDIN

### ISSUE THREAD

**Issue by agrajag9** [tmux/tmux#385]
I recently upgraded tmux from v1.8 to v2.3 and began experiencing a behavior that I can only describe as a bug. When I press ESC it seems to send a string of 5 seemingly-random bytes until I kill the terminal. I was able to capture some of this using vim:

```
00000000  f9 be 84 b2 a8 f9 be 84  b2 a8 f9 be 84 b2 a8 f9  |................|
00000010  be 84 b2 a8 f9 be 84 b2  a8 f9 be 84 b2 a8 f9 be  |................|
```

This also occurs in bash, but I haven't been able to capture exactly what's being inserted - I only know that it puts my shell into a difficult-to-recover state.

This appears to be documented as well here: https://github.com/neovim/neovim/issues/2093 This thread implies that there are some workarounds related to changing the `escape-time` setting. I normally have mine set to 0, but changing it to 20 was a sufficient workaround - this did not actually fix the problem however, just made it recoverable.

**Comment by nicm** [comment]
Wait for a few hours and then git pull.

**Comment by agrajag9** [comment]
@nicm Whatever you did fixed the problem. Thank you.

Is there an explanation for the fix?

**Comment by nicm** [comment]
It was a bug introduced in the last few days when changing the way keys
are processed so that Meta works with Unicode keys.
