### ISSUE TITLE
garbage printed: `10;rgb:ffff/ffff/ffff]11;rgb:0000/0000/0000`

### ISSUE THREAD

**Issue by kmille** [tmux/tmux#3852]
### Issue description

I'm using `rxvt-unicode` on Arch  Linux. If I start tmux, then I get the following garbage printed out to the console:
> ^[]10;rgb:ffff/ffff/ffff^[^[]11;rgb:0000/0000/0000^[%                                                                                                                                                                                          
kmille@linbox:/etc 10;rgb:ffff/ffff/ffff]11;rgb:0000/0000/0000

It happens for for 1-2 weeks... Same if I remove my tmux.conf

### Required information

Please provide the following information:

* tmux version: 3.4
* Arch Linux with current Kernel
* In both casees `tmux-256color`
* Logs from tmux: nothing?

**Comment by krader1961** [comment]
This is a FAQ: https://github.com/tmux/tmux/issues?q=is%3Aissue+rxvt+rgb+

Switch to a different terminal.

**Comment by Tblue** [comment]
Good news, this will apparently be [fixed in the next rxvt-unicode release](http://cvs.schmorp.de/rxvt-unicode/Changes?revision=1.1304&view=markup#l69).

**Comment by kmille** [comment]
Thanks @Tblue. This builds and installs `urxvt-unicode` with the required patch:
```bash
cd /tmp
git clone https://gitlab.archlinux.org/archlinux/packaging/packages/rxvt-unicode.git
cd rxvt-unicode
makepkg -s --nobuild --skipint
curl -o /tmp/fix.diff https://github.com/exg/rxvt-unicode/commit/417b540d6dba67d440e3617bc2cf6d7cea1ed968.diff
cd src/rxvt-unicode-9.31/
patch --dry-run -p1  < /tmp/fix.diff
patch -p1  < /tmp/fix.diff
cd ../../
makepkg -i --noextract
cd
rm -rf /tmp/fix.diff cd /tmp/rxvt-unicode
```
