### ISSUE TITLE
Formatting should support a modifier to make a value a valid string to a POSIX shell

### ISSUE THREAD

**Issue by krader1961** [tmux/tmux#3854]
See https://github.com/orgs/tmux/discussions/3853

The crux of the matter is that constructs such as `#(...)` need a mechanism to escape Tmux values (e.g., `#{pane_title}`) so they can be correctly interpreted as a string by a POSIX shell even if the value contains characters such as single or double quotes. I propose a `s:` format prefix to perform the appropriate shell escaping; e.g., `#{s:pane_title}`.

**Comment by nicm** [comment]
You mean like `q`?

**Comment by krader1961** [comment]
> You mean like q?

LOL! Yes. But in my defense, and the person who started the discussion, that prefix is hard to discover. The "or with a 'h' suffix" in the relevant sentence of the documentation is also weird and hard to interpret in the context of a `q:` prefix. This is something that would benefit from a rewrite of the documentation. If nothing else, the `b:` and `d:` prefixes should not be in the same paragraph as the `q:` prefix. Which should have its own paragraph that better explains its purpose.

@unphased

**Comment by krader1961** [comment]
I'll also point out this hard to understand text in the man page:

```
The ‘b:’ and ‘d:’ prefixes are basename(3) and dirname(3) of the variable respectively.  ‘q:’ will escape sh(1) special characters...
```

Note that it doesn't say 

> The `q:` prefix will escape shell strings...

That is one reason discovering this mechanism is hard. The paragraph containing all of these prefixes should be rewritten so each prefix is a separate paragraph. The the behavior of the `q:` prefix needs more documentation.

**Comment by nicm** [comment]
That's fine if you want to open a PR.

**Comment by krader1961** [comment]
> That's fine if you want to open a PR.

LOL! I won't open a PR since I don't use Tmux in a manner similar to the person that prompted this issue. That is, I don't personally use any Tmux constructs that invoke an external shell with values that might be special to an external shell. But I am perplexed why you are hostile to improving the Tmux documentation.

**Comment by nicm** [comment]
Saying I would accept a PR is hostile? I don't deny it could be improved but it is not a priority for me to do this and you seem to have a clear idea what it should look like.
