### ISSUE TITLE
`OSC 133` flags are lost on `CSI 0 J`

### ISSUE THREAD

**Issue by ikalnytskyi** [tmux/tmux#3856]
### Issue description

Tmux 3.4 has introduced support for OSC 133 (see 43b841f188c994966e00e59c96581b876652bef1) that allows marking shell prompt, and jump in history between them.

Those marks may be **lost** when `tmux` receives [CSI 0 J](https://vt100.net/docs/vt510-rm/ED.html) escape code (see `INPUT_CSI_ED`). `CSI 0 J` means erase from the cursor through the end of the display.

What happens is that `CSI 0 J` indirectly invokes `grid_clear`, which has an [optimization](https://github.com/tmux/tmux/blob/608d113486835515e7a89b1511704440c68ae817/grid.c#L616-L619) that _empties_ an entire line if cursor at index `0` and we need to clear an entire line. This emptying part resets `grid_line.flags` and those shell prompt marks we used to have are lost. 

### How to reproduce?

One can simply execute the following command:

```shell
echo -e "\e]133;A\a\e[J"
```

and use the following tmux command to jump to previous prompt in the copy mode:

```tmux
send-keys -X previous-prompt
``` 

Please note, if you just add a single character in front of `CSI 0 J` escape code, jumping between prompts will work. E.g:

```shell
echo -e ".\e]133;A\a\e[J"
```

### Required information

Please provide the following information:

* Tmux: 3.4
* OS: Arch Linux
* Outside: `TERM=foot-direct`
* Inside: `TERM=tmux-256color`

### P.S.

I know this sounds weird, who on Earth will use `CSI 0 J` at the beginning of the line?! I use Fish shell and [Starship][https://starship.rs/] prompt. Fish shell inserts `\e]133;A\a` at the beginning of the prompt, and [starship prints](https://github.com/starship/starship/blob/eeadf432e6688bcf79e8e2a953ea3bdc6de16b1b/src/print.rs#L81-L83) `\e[J` as the very first escape code for Fish shell only.

This means Tmux' OSC 133 support is broken for Fish + Starship users.

I don't know Tmux details enough to implement a safe fix. The only thing that pops into my mind is to extend the condition for the optimization mentioned in the issue description by checking that there are no _prompt_ flags on the line before opting into emptying the line.

**Comment by nicm** [comment]
I don't get it, if you clear the line there is no prompt on it, right? It's empty. If we didn't do this you would be left with stray prompt markers.

**Comment by ikalnytskyi** [comment]
The OSC 133 prompt marker (`\e]133;A\a`) comes _before_ the erase display code (`\e[J`). And this erase display code is not for erasing the entire line, but for erasing the line from current cursor position till the end of the screen.

It's just so happened that Tmux seeing that the current cursor position is `0` decides to empty the entire line instead of iterating over cells to the end of the screen. And unfortunately, emptying the entire line and emptying every cell in the line is not the same in Tmux (the former resets line flags while the latter does not).

**Comment by nicm** [comment]
ED0 is intended to erase the current line if you send it at the start of the line.

Say you have a prompt on line 1 and you send \033[H\033[J, you think tmux should remove the prompt flag on every line except the first?

What does iTerm2 do in both these cases? We should probably follow it here.

**Comment by ikalnytskyi** [comment]
> Say you have a prompt on line 1 and you send \033[H\033[J, you think tmux should remove the prompt flag on every line except the first?

I'm not sure I'm following you, so sorry if I got you wrong. What I basically mean is that if `\033[J` comes after `\033]133;A\033\\`, then the flag on the current line should not be cleared since `\033[J` means from current position till the end of the screen. And even though the current position is at index 0, it's not beginning of the line since `\033]133;A\033\\` preceding it.

I see the problem now, that assuming we're using CSI H to move the cursor, whenever we print ED0, there's no way to tell whether we before the prompt marker or after to make a decision whether it should be set or unset. Does it mean that the marker should also be stored in grid cell?

> What does iTerm2 do in both these cases? We should probably follow it here.

I don't know, I don't use macOS. I can probably check it in a day or two.

On Foot (the terminal I use), `033[J` doesn't clear the prompt marker and I'm able jump between my prompts.

**Comment by nicm** [comment]
Yes, when we do ED0 there is no way to know if the application really wants to clear the line including the prompt marker or whether it wants to leave it. Whichever we do there will be a scenario where it is wrong, either the prompt marker will be left on a line without a prompt, or it will be missing from a line with a prompt.

It is not sensible for this application to send the prompt marker and then immediately clear the line.

**Comment by ikalnytskyi** [comment]
> Whichever we do there will be a scenario where it is wrong, either the prompt marker will be left on a line without a prompt, or it will be missing from a line with a prompt.

Yeah, I believe there are many more edge case scenarios. I think the best we can do here is to follow footsteps of other terminals which implement OSC 133. Let me investigate how Foot and iTerm behave here. It may take some time, but I'll get back there as soon as I collect information on their behaviour.

> It is not sensible for this application to send the prompt marker and then immediately clear the line.

In my case the issue lies in the combination of Tmux, Starship and Fish. The Fish shell inserts the prompt marker via its [`fish_prompt` event hook](https://fishshell.com/docs/current/language.html#event-handlers), which is invoked before the Starship prompt. The Starship prompt then sends ED0 knowing nothing about the prompt marks inserted by my Fish hook.

I tried to use Starship without ED0 for couple of days, and it seems to work fine. Most likely ED0 has been used to workaround some bugs that are no longer present in Fish. I plan to upstream this change, I'll see what Starship devs think about it.
