### ISSUE TITLE
i3wm fullscreen toggle tmux panes resize

### ISSUE THREAD

**Issue by qrockz** [tmux/tmux#3859]
![simplescreenrecorder-2024-02-24_05 09 42](https://github.com/tmux/tmux/assets/56853194/ae5a2aa2-6ea7-467a-ab82-e5773ab0e2bf)

Hi,

whenever I toggle my terminal (gnome terminal, wezterm) to fullscreen (i3 wm) the panes change their height unexpected. 

```
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera

uname -sp
Linux x86_64

tmux -V
tmux 3.2a

i3 --version
i3 version 4.22-35-g2a4576be
```
[tmux-client-215444.log](https://github.com/tmux/tmux/files/14393258/tmux-client-215444.log)
[tmux-server-215446.log](https://github.com/tmux/tmux/files/14393259/tmux-server-215446.log)

**Comment by nicm** [comment]
If you resize the termin
