### ISSUE TITLE
Really strange. On Ubuntu (VM): if-shell command seems to not work with [[ ]]

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#386]
It's doing this on Ubuntu here with 2.1 from `apt` and 2.2 built from source. Happens with and without my tmux config. Happens with `bash` and `zsh`.

```
$ tmux if "[[ 'vim' == 'vim' ]]" "display -p yes" "display -p no"
no
```

This is expected (and seen on OS X): 

```
$ tmux if "[[ 'vim' == 'vim' ]]" "display -p yes" "display -p no"
yes
```

The reason it says vim here is that I'm normally comparing `#{pane_current_command}` to a regex using the shell (to implement a contextual keybinding switched by tmux).

The strange thing is that most of my other tmux configuration (which includes use of `if`) seems to work fine.

**Comment by nicm** [comment]
if-shell will use /bin/sh, IIRC [[ ]] is an extension

**Comment by unphased** [comment]
So what explains this behavior: 

```
$ tmux if "[ 'vim' == 'vim' ]" "display -p yes" "display -p no"
no
```

**Comment by nicm** [comment]
== is also an extension.

**Comment by unphased** [comment]
Sure, but still:

```
$ tmux if "[[ ! 'vim' = 'vim' ]]" "display -p yes" "display -p no"
no
$ tmux if "[[ 'vim' = 'vim' ]]" "display -p yes" "display -p no"
no
```

**Comment by nicm** [comment]
Yes because [[ ]] is an extension and whatever shell you are using does not
support it when installed as /bin/sh

**Comment by nicm** [comment]
You probably need to either do something like:

tmux if 'bash -c "[[ x == x ]]"' ...

Or stick to POSIX sh:

tmux if '[ x = x ]' ...

**Comment by nicm** [comment]
OS X /bin/sh is probably ksh which is not as ridiculously strict as bash.

**Comment by krader1961** [comment]
> OS X /bin/sh is probably ksh which is not as ridiculously strict as bash.

Correct on both points. Also, I'm impressed by the patience you exhibit in dealing with these types of issues.

**Comment by unphased** [comment]
I'll try `[ = ]` tomorrow

**Comment by nicm** [comment]
Perhaps the other Linuxes use ash for /bin/sh instead of bash.

**Comment by unphased** [comment]
Writing back to confirm, looks like Ubuntu /bin/sh is dash. It's strict enough that only `[ = ]` and such work. I have to use a case to replace the regex I have in there right now.

**Comment by unphased** [comment]
For posterity: I now compile a C++ program that I use with `if-shell`. Seems to be pretty good for performance. The case/esac statement under dash is not expressive enough. Difficult to debug as well.
