### ISSUE TITLE
tmux set -g status-right "#{?window_active,#(echo '123,456'),0}" displays nothing

### ISSUE THREAD

**Issue by gpakosz** [tmux/tmux#3867]
### Issue description

It seems that parsing of `#()` within conditionals has a bug when the command has commas.

The following displays an empty status right segment instead of printing `123,456`:
```
$ tmux set -g status-right "#{?window_active,#(echo '123,456'),0}"
```

```
1709372991.848764 format_replace: format 'status-right' found: #{?window_active,#(echo '123,456'),0}
1709372991.848771 format_expand1: expanding format: #{?window_active,#(echo '123,456'),0}
1709372991.848779 format_expand1: found #{}: ?window_active,#(echo '123,456'),0
1709372991.848786 format_replace: condition is: window_active
1709372991.848796 format_replace: condition 'window_active' found: 1
1709372991.848804 format_replace: condition 'window_active' is true
1709372991.848811 format_expand1: expanding format: #(echo '123
1709372991.848818 format_expand1: result is: 
1709372991.848825 format_replace: replaced '?window_active,#(echo '123,456'),0' with ''
1709372991.848833 format_expand1: result is: 
```

I couldn't find a way to escape the comma.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 
  * `3.3a`
* Platform (`uname -sp`):
  * `Darwin i386` and `Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`):
  * Outside: `xterm-256color`
  * Inside: `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`)
  * [tmux-client-19975.log](https://github.com/tmux/tmux/files/14468764/tmux-client-19975.log)
  * [tmux-out-19977.log](https://github.com/tmux/tmux/files/14468765/tmux-out-19977.log)
  * [tmux-server-19977.log](https://github.com/tmux/tmux/files/14468766/tmux-server-19977.log)

**Comment by nicm** [comment]
I think you can escape it as `#,`?

**Comment by gpakosz** [comment]
Indeed it works. Thanks
