### ISSUE TITLE
#{selection_present} format variable is 1 when the selection is zero-length

### ISSUE THREAD

**Issue by mgrant0** [tmux/tmux#3868]
### Issue description

If there's a MouseDrag1Pane followed immediatly by a MouseDragEnd1Pane, there is a zero-length selection and the format variable selection_present is set to 1.

`#{selection_present}` format variable should not be set if the selection is zero-length

See discussion: https://github.com/orgs/tmux/discussions/3831

### Required information

Please provide the following information:

* tmux version 3.4
* Platform all
* $TERM inside tmux-256color outside of tmux putty-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
https://github.com/tmux/tmux/pull/3869
