### ISSUE TITLE
Support for scrolloff

### ISSUE THREAD

**Issue by chaosteil** [tmux/tmux#3871]
### Issue description

I was wondering if it seems reasonable to implement a scrolling behavior configuration similar to vim's scrolloff setting:
```
						*'scrolloff'* *'so'*
'scrolloff' 'so'	number	(default 0)
			global or local to window |global-local|
	Minimal number of screen lines to keep above and below the cursor.
	This will make some context visible around where you are working.  If
	you set it to a very large value (999) the cursor line will always be
	in the middle of the window (except at the start or end of the file or
	when long lines wrap).
	After using the local value, go back the global value with one of
	these two:  
		setlocal scrolloff<
		setlocal scrolloff=-1
 	For scrolling horizontally see 'sidescrolloff'.
```

I find to be incredibly useful to see more context when scrolling content, so
having a similar feature would be some of the few things that would tie my terminal
experience together.

Would something as such be in the scope of tmux itself? If necessary I would be willing
to contribute to the PR myself with guidance.

**Comment by nicm** [comment]
OK but I don't know if I would make it a configurable number of lines, a way to just keep the cursor on the centre line may be simpler and easier to use.

You want to be looking at `window-copy.c`.
