### ISSUE TITLE
How to use a star glob in switch-client?

### ISSUE THREAD

**Issue by lobre** [tmux/tmux#3875]
### Issue description

Sorry in advance if the answer is trivial but I could not answer it by reading the manual.

I do have a session named "aports". From within tmux, I would like to switch my current client (using `switch-client -t <target-session>`) to this session, but using a `fnmatch` pattern, which is: `*ports`.

If I read the manual for `target-session`, there is:

```
target-session is tried as, in order:
       1.   A session ID prefixed with a $.

       2.   An exact name of a session (as listed by the list-sessions command).

       3.   The start of a session name, for example ‘mysess’ would match a session named ‘mysession’.

       4.   An fnmatch(3) pattern which is matched against the session name.
```

The last one is a `fnmatch`. Now if I lookup the manpage using `man 3 fnmatch`, I do have:

```
The fnmatch() function checks whether the string argument matches the pattern argument, which is a shell wildcard pattern (see glob(7)).
```

And continuing my journey, I check `man 7 glob`:

```
   Wildcard matching
       A string is a wildcard pattern if it contains one of the characters '?', '*' or '['.  Globbing is the operation that expands a wildcard pattern into the list of pathnames matching the pattern.  Matching is defined by:

       A '?' (not between brackets) matches any single character.

       A '*' (not between brackets) matches any string, including the empty string.
```

Having read all of that, I don't understand why entering `*ports` does not match my `aports` session. Instead, it says: "Can’t find session: *ports."

However, if I use `?ports`, it works.

Do you have an idea why? Am I missing something, or is it a bug?

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.4
* Platform (`uname -sp`): Linux x86_64

**Comment by nicm** [comment]
It works for me:
~~~~
$ tmux -Ltest kill-server
$ tmux -Ltest new -s xfoo
...inside tmux...
$ tmux lsw -t'*foo'
0: bash* (1 panes) [80x24] [layout b25d,80x24,0,0,0] @0 (active)
$ tmux switchc -t'*foo'
$
~~~~

**Comment by lobre** [comment]
I tried your example and you are right, it actually works.

By digging, I realised I had multiple sessions matching my pattern, hence the error.

However, the message is not very clear. I don’t know if it is a "catch-all" error, but it says: "can't find session: *ports" while in reality, the pattern matches multiple sessions, so tmux cannot know which one to select.

Does it make sense to you if I try to improve this message?

**Comment by nicm** [comment]
Possibly, although tmux can't really know if you are looking for a session called "*ports" or "*ports123" which will match before for example "xports".

**Comment by lobre** [comment]
Do you mean something like a session literally named "*ports123" (with the star in the session name)?

I did not know this was possible. If that is the case, I think it is effectively tricky to understand what the user is trying to do.

**Comment by nicm** [comment]
Yes that's right if you have a session named exactly the pattern then it will match first. It is number 2 in the list you showed from the man page. So we can't really say exactly what the user meant.

This kind of -t is really meant for interactive use where it doesn't really matter if you get the wrong session, you'll just change it again. For scripting you should use `=` to force an exact match or work out the session ID some other way and use it.
