### ISSUE TITLE
icon in status line not displayed correctly

### ISSUE THREAD

**Issue by qrockz** [tmux/tmux#3878]
![weather2](https://github.com/tmux/tmux/assets/56853194/203384eb-2bd5-4059-9bc5-43ed4314889a)
Problem: a black block appears in status line.

```
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera

uname -sp
Linux x86_64

tmux -V
tmux 3.2a

i3 --version
i3 version 4.22-35-g2a4576be
```
It happens in wezterm and gnome-terminal.
I'm using nerd font and noto emoji is also installed.  It happens on this specific ☁️ icon **combined** with text. Other icons seem to work.

Also noteworthy to mention is when I type  `set-option -gq status-right "☁️aaaa"` in tmux and I want to move the cursor to the beginning of the line then the cursor stops after the first char 's' and before 'e'. Outside of tmux the cursor would be right behinde the prompt.

Has this something to do with encoding and how to fix it?

running `tmux -u `doesn't help

```
locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=lv_LV.UTF-8
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=lv_LV.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=lv_LV.UTF-8
LC_NAME=lv_LV.UTF-8
LC_ADDRESS=lv_LV.UTF-8
LC_TELEPHONE=lv_LV.UTF-8
LC_MEASUREMENT=lv_LV.UTF-8
LC_IDENTIFICATION=lv_LV.UTF-8
LC_ALL=
```

**Comment by nicm** [comment]
Same as #3865.
