### ISSUE TITLE
sixel image bleed

### ISSUE THREAD

**Issue by joseluis** [tmux/tmux#3879]
This simple sixel image [map8_libsixel.six.zip](https://github.com/tmux/tmux/files/14551022/map8_libsixel.six.zip) created with libsixel from this png ![map8](https://github.com/tmux/tmux/assets/5832068/58b12c14-5f07-479e-93bd-9788c3f0b054) seemingly displays incorrectly in tmux, bleeding the first color onto the next line, in all terminals tested (alacritty graphics branch, wezterm and xterm -ti vt480.

This is all using: `tmux next-3.5` on `Linux x86_64`, invoked with `-f /dev/null -vv new`. $TERM in tmux is `tmux-256color`.

![alacritty](https://github.com/tmux/tmux/assets/5832068/d5e9a5ac-92e4-43c9-b714-2d974f492018) alacritty
![alacritty-tmux](https://github.com/tmux/tmux/assets/5832068/e72c3366-41ad-4929-9d09-deb85f775ec8) alacritty + tmux

![wezterm](https://github.com/tmux/tmux/assets/5832068/f6bdca66-5ead-421c-8856-657165a7dcfc) wezterm
![wezterm-tmux](https://github.com/tmux/tmux/assets/5832068/05b4db8e-f020-4d38-8453-83a88a6f8d56) wezterm + tmux

![xterm_vt340](https://github.com/tmux/tmux/assets/5832068/b1799693-5640-4fc9-a761-e32cef5f5fb1) xterm
![xterm_vt340-tmux](https://github.com/tmux/tmux/assets/5832068/ab16dfb7-a883-4d4a-81f2-0831ad4bfb77) xterm + tmux

[tmux-logs.zip](https://github.com/tmux/tmux/files/14551082/tmux-logs.zip)

**Comment by nicm** [comment]
This seems to be fixed in master by #4149, let me know if you still see problems. Thanks!
