### ISSUE TITLE
Is it possible to create a new pane/window when I'm already root?

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#388]
When I login into my Linux box using regular user, and in a terminal like Konsole, **sudo ssh** into a Linux server in local network, and I want to create a new pane/window, and it always creates new one under regular user account, and I have to type my password again when **sudo ssh xxx**, it is very annoying when I have to ssh into multiple servers at the same time. (tmux is not installed in Linux server machine).

So, is it possible to create a new pane/window when I'm already root in the current pane/window without prompting for password?

**Comment by ntnn** [comment]
You shouldn't need superuser privileges to ssh into another machine.

You can try setting `default-command` as a session option.

E.g. you want a session on a remote host called `bray`, so you create
a new tmux sessions `remote-bray`, run `tmux set -s default-command 'ssh
bray'` and now all new panes automatically open a shell on `bray`.

**Comment by c02y** [comment]
If I directly **ssh xxx**, it says 

    Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

after typing the correct password repeatedly. (I don' do ssh a lot, so unnecessary to config ssh, sudo ssh is OK)

Here is more info, I want to create a new pane/window so I can ssh into another server machine (different IP addresses) using the regular binding which creating a new pane/window, but it will check if I'm already the root user, if so, then new pane/window under root user so I don't have to type sudo and password for root.

**Comment by nicm** [comment]
tmux doesn't really know you have changed users in a window so it can't do it for you in new windows, not to mention that needing it so you can run ssh as root instead of your own user (!) because you don't know how to configure it is not a compelling use case.
