### ISSUE TITLE
Tmux output numbers separated by semicolon at startup

### ISSUE THREAD

**Issue by PunkPhysicist** [tmux/tmux#3880]
When tmux is first started, a series of numbers and slashes is auto inserted (see images below). This is the problem listed [here](https://github.com/tmux-plugins/tpm/issues/272) on the github page for the tmux plugin manager. However, the problem persists even if I move/delete both the `tmux.conf` and `~/.tmux/` folder with my tpm plugins.

Images of a fresh tmux session both with (top) and without (bottom) any configs/plugins: 
![with](https://github.com/tmux/tmux/assets/10066902/5ef2b8b6-9c15-4071-81ce-d2b311c08c1c)
![without](https://github.com/tmux/tmux/assets/10066902/6d259e57-7c02-45a1-9362-3e6dc0ddc576)

Edit: Seems to be an issue with tmux in urxvt, as I don't seem to have this problem if I use other terminals.

**Comment by agent-69** [comment]
the same problem, tmux+ urxvt

**Comment by nicm** [comment]
This is a urxvt bug as discussed in several other issues.

**Comment by magoerlich** [comment]
@nicm it's not, it happens in Windows Terminal as well. And thanks for closing this issue without referencing ANY of these mentioned issues...very replicable

**Comment by nicm** [comment]
I should run around looking for issues for someone who can't even include the tmux version let alone the logs in their issue?

**Comment by magoerlich** [comment]
Ahh the welcoming world of Open Source.

You shouldn't reference these issue for me, but to save yourself further questions about it, stupid moron
😘

**Comment by magoerlich** [comment]
Ah yeah, the welcoming world of Open Source. 🤦‍♀️
Who said that? Could you quote?
Otherwise properly documenting the closing reasons for an issue is in YOUR interest, not anyone elses.
