### ISSUE TITLE
Interactive buffer list doesn't work with only named buffers

### ISSUE THREAD

**Issue by sjoegren** [tmux/tmux#3883]
### Issue description

When buffer list contains only named buffers, keys in choose-tree menu doesn't work, i.e. no buffers can be selected from menu.

Steps to reproduce:

1. `tmux -f /dev/null new`
2. `tmux set-buffer -b foo 'buffer content'`
3. Open buffer menu with `PREFIX =`
4. Press up/down/j/k/enter and the menu just closes directly
5. Now, add an unnamed buffer either from copy mode or `tmux set-buffer 'other data'`
6. See that there are now one named and one unnamed buffer:
    ```
    $ tmux lsb
    buffer0: 10 bytes: "other data"
    foo: 14 bytes: "buffer content"
    ```
7. Open buffer menu with `PREFIX =`
8. Now navigation and buffer selection works as expected.

This worked on 3.3a but not from 3.4.
It's probably introduced in 020c403dff56269d93625970ed41761520afc853, as I tried reverting it on master and built it and the issue disappeared.

### Required information

Please provide the following information:

* tmux next-3.5 (git master)
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`). outside: `xterm-256color`, inside: `tmux-256color`

**Comment by kugel-** [comment]
Hello. I have the same problem. The buffer list simply closes immediately when I use the arrow keys. 

Also choosing the buffer by it's index number does not work.

**Comment by kugel-** [comment]
Hm, now it works fine again. Same tmux version though. So it's not always reproducible.

**Comment by nicm** [comment]
This seems like the same as https://github.com/tmux/tmux/issues/4061, there is a fix in that issue.
