### ISSUE TITLE
Keycode `CTRL-'` do not work inside tmux session

### ISSUE THREAD

**Issue by ucomru** [tmux/tmux#3884]
### Issue description

Good day!
I'm using `tmux 3.4` with `iterm2 Build 3.4.23` on `Mac OS 14.4 (23E214), M1`.
There are 2 different key code are available: `'` and `ctrl+'`. It's work well.
But, when I'm using it inside `tmux`, they are going to the single key code **`'`** (`ctrl+'` -> `'`).
According to `:list-keys`, there are no tmux  bindings with `C-'`.

### Required information

* tmux version -- `tmux 3.4`
* Platform -- `Darwin arm`
* $TERM inside and outside of tmux -- `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Does it work with extended keys on? See https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys.

**Comment by ucomru** [comment]
> Does it work with extended keys on? See https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys.

Many thank to answer!!!
All is working good now.
I'm looked so more information, but all information is available at github/tmux/wiki...

**Comment by ucomru** [comment]
If anybody find this question in the future:

**The short instruction**:

1) **iTerm**:
`Profiles -> Keys -> General`: _**`Report modifiers using CSI`**_ -- set check box **`ON`**
**!!** iTerm will asked you to **remap** terminal key mappings -- _**do it**_.

2) Add to **`~/.tmux.conf`**:
```bash
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
```

3) Detach `tmux` and run command: **`tmux kill-server`**
4) Restart `iTerm2` and enjoy...
