### ISSUE TITLE
garbage in prompt in 3.4

### ISSUE THREAD

**Issue by FeodorPetrov** [tmux/tmux#3885]
I get garbage after prompt:
10;rgb:bebe/bebe/bebe]11;rgb:0000/0000/0000
after updating from 3.3a to 3.4.
CRUX GNU/Linux.
TERM=linux
Running from rxvt-unicode.

**Comment by LordPax** [comment]
Hi, i have similar garbage prompt
```
/ff00/ff00^[^[]11;rgb:0800/0800/0800^[
```
I also run tmux from rxvt-unicode

**Comment by LordPax** [comment]
there is an issue about that https://github.com/tmux/tmux/issues/3470
