### ISSUE TITLE
Is it possible to change the color of the tmux status bar in command mode or "highlight" mode?

### ISSUE THREAD

**Issue by hq6** [tmux/tmux#3887]
### Issue description

When I type `Prefix-:` inside tmux to start typing a command, tmux changes the color of the status bar to dark yellow. 
A similar effect happens if I push `Prefix-,` to change the name of a window.

While fine on a normal monitor, I've recently started using an E-Ink monitor, and the highlight color makes the status bar completely unreadable when I'm trying to type into it.

**Is it possible to control the color that the status bar changes into?**

I've searched through the manual as well as the web, and haven't found a way to configure this setting.

I'm currently looking through the source but I have not found yet found where the color is emitted.
If the answer is that there is a no configuration for this, a pointer to the source line that sets this color would be greatly appreciated, so I can rebuild tmux with this highlight color changed.

### Required information

Please provide the following information:

* Tmux version: I have tested this behavior `tmux next-3.5` as well as `tmux 3.0a`.
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): Outside tmux is `xterm-256color`. Inside tmux is `screen`.
* Logs from tmux (`tmux kill-server; tmux -vv new`). Attached.
[tmux-out-291328.log](https://github.com/tmux/tmux/files/14622842/tmux-out-291328.log)
[tmux-server-291328.log](https://github.com/tmux/tmux/files/14622843/tmux-server-291328.log)
[tmux-client-291326.log](https://github.com/tmux/tmux/files/14622844/tmux-client-291326.log)

**Comment by nicm** [comment]
`message-style`

**Comment by hq6** [comment]
Thanks, that fixed it!
It might be worth updating the man page to mention that this is also the "highlight" style or the style used when typing a command.

**Comment by hq6** [comment]
Closing this since the question has been addressed.
