### ISSUE TITLE
docs claim that attach works as switch from inside tmux; this is incorrect

### ISSUE THREAD

**Issue by amaramth** [tmux/tmux#3889]
### Issue description

docs say "If [attach-session is] used from inside, switch the current client." but instead it returns the opaque error message `sessions should be nested with care, unset $TMUX to force`. This was mentioned in [a previous issue](https://github.com/tmux/tmux/issues/3124), but the maintainer of tmux pretended that they didn't hear it.

### Required information

* tmux 3.4

**Comment by nicm** [comment]
You need to use it from the command prompt not from the shell, from the shell use `switch-client`.

**Comment by amaramth** [comment]
I see. Then, the bug in the docs is that it uses terms "inside tmux" and "outside tmux" to refer to `C-b :` and the `tmux` command, but does not explain this, so people think that the docs' phrase "inside tmux" refers to the `tmux` command when run inside tmux as well as `C-b :`
