### ISSUE TITLE
can not find pane: next 

### ISSUE THREAD

**Issue by muezabdalla** [tmux/tmux#3896]
i added these line to navigate the pane in tmux
bind-key -n M-j selectp -t next
bind-key -n M-k selectp -t previous

and now when i press alt-j it says "can not find pane: next " and when press alt-k it says "can not find pane: previous".
I just want to make a short cut to go to next pane and another one to go to the previous pane
### Required information

Please provide the following information:

* tmux version (`tmux 3.4`).
* Platform (`Linux unknown`)(but i am on void linux).
* $TERM inside and outside of tmux (`xterm-256color`).

**Comment by nicm** [comment]
`-t '{next}'`, see https://man.openbsd.org/tmux#Token~2

**Comment by muezabdalla** [comment]
thanks that worked
in the linux tmux man page they only have this example 'select-window -t:+2' maybe I should try BSD
