### ISSUE TITLE
MouseDragEnd1Pane doesn't get triggered when dragging mouse out of the window

### ISSUE THREAD

**Issue by anhpt379** [tmux/tmux#3904]
### Issue description

I'm on macOS Sonoma 14.3.1. The `MouseDragEnd1Pane` event doesn't get triggered when we drag the mouse out of the current window. It is annoying because I have a config that copy the selection to clipboard on `MouseDragEnd1Pane`, and sometimes it doesn't work because I accidentally release the mouse at the edge of the screen.

It happens even when the window is in full-screen mode. It can be reproduce by pressing the left mouse button in the middle of a text line in the window, hold and drag the mouse to the left edge of the screen, and release the left mouse button there. 

Here's the minimal tmux config:

```
set-option -g mouse on
set-option -g mode-keys vi
bind-key -T copy-mode-vi MouseDragEnd1Pane display-message "Drag ended"
```

### Required information

* tmux version (`tmux -V`): `tmux 3.4`
* Platform (`uname -sp`): `Darwin arm`
* $TERM inside tmux (`echo $TERM`): `screen-256color`
* $TERM outside tmux (`echo $TERM`): `xterm-kitty`

**Comment by nicm** [comment]
No logs.

**Comment by anhpt379** [comment]
@nicm Here are the logs:

[tmux-out-38527.log](https://github.com/tmux/tmux/files/14693849/tmux-out-38527.log)
[tmux-server-38527.log](https://github.com/tmux/tmux/files/14693850/tmux-server-38527.log)
[tmux-client-38525.log](https://github.com/tmux/tmux/files/14693851/tmux-client-38525.log)

**Comment by nicm** [comment]
tmux is not getting any event from the terminal telling it the drag has finished, so it has no way to know it should end.

This is an issue with your terminal (although it may not be able to tell the mouse has been released outside its window either).

**Comment by anhpt379** [comment]
oh, thanks. I've just tried with macOS default terminal app, and WezTerm and the issue didn't happen. This issue only happens with [Kitty](https://github.com/kovidgoyal/kitty). I'll report the issue there.
