### ISSUE TITLE
tmux interfering with keybinds starting with control

### ISSUE THREAD

**Issue by beamandala** [tmux/tmux#3907]
### Issue description
I am using neovim inside of tmux. One of the keymaps I have is 'Control + \`'. This keymap works outside of tmux but when run within tmux, it runs my neovim keymap for '\`'. It looks like tmux is interfering somewhere in between and messing with any keybind starting with Control. 

Another example: the 'Control + l' keybind is supposed to clear the terminal screen and this works outside of tmux but again doesn't work inside tmux.

I have attempted to fix this issue by adding 'unbind C-`' to my tmux conf file but it didn't do anything.

This issue is occuring in both iterm and alacritty.

### Required information
* tmux version: 3.4
* Platform: Darwin arm
* $TERM: alacritty, screen-256color
* Logs from tmux: N/A

**Comment by danielwikander** [comment]
I'm having this issue with ctrl+i in neovim too, works fine outside of tmux (with some alactritty conf settings), but inside a tmux session it goes back to acting like tab.

**Comment by danielwikander** [comment]
This happens immediately for me.
I've also tried setting my tmux prefix to c-space but never got that to work, so it's possible that this is related.

**Comment by krader1961** [comment]
You need to enable extended keys: https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys

**Comment by danielwikander** [comment]
Alright, so my setup might be a bit unconventional:
I'm running alacritty on Windows and using WSL2.
Inside WSL2 (ubuntu), if I hit Ctrl-i `xxd -ps` prints the following:
`^[[105;5u`
If i hit tab, it prints:
`09`
If i start tmux, and run `xxd -ps` and hit Ctrl-i, it prints:
`09` for both tab and Ctrl+i.

So it only happens when I start tmux.

I have extended keys enabled in my tmux conf:
```
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
```

My alacritty config contains this bit to help differentiate Ctrl+i from tab:
```
[[keyboard.bindings]]
key = "I"
mods = "Control"
chars = "\u001b[105;5u"
```
And it works fine outside tmux.

Have I missed something in my setup?

**Comment by nicm** [comment]
Are you sure TERM outside tmux is xterm and not alacritty?

**Comment by danielwikander** [comment]
Yeah, if I run:
```
echo $TERM
```
outside of tmux, I get: 
```
xterm-256color
```

**Comment by danielwikander** [comment]
Found this issue, probably a duplicate?
https://github.com/tmux/tmux/issues/2705

**Comment by nicm** [comment]
Oh yeah we don't do `C-i`.

**Comment by danielwikander** [comment]
> Oh yeah we don't do `C-i`.

Alright, is it because of a technological limitation or is it an agreed upon design decision?

**Comment by nicm** [comment]
tmux does not currently have a way to represent them as different keys internally so we only chose to support `modifyOtherKeys` set to `1` which keeps `C-i` and `Tab` the same. If you want to work on this, see last half of this comment https://github.com/tmux/tmux/pull/3872#issuecomment-1985374120.

**Comment by nicm** [comment]
This comment also has some thoughts on the way forward: https://github.com/tmux/tmux/issues/2705#issuecomment-841133549

**Comment by ThomasGHenry** [comment]
The 3.4 update seems to have invalided this stanza of my config (such as it was... sprawling copy/paste curation 1000 years old).

```
set -gu prefix2
unbind C-a
unbind C-b
unbind C-space
set -g prefix C-space
bind c-space send-prefix
```

c-space is totally ignored on WezTerm and Terminal.app (though oddly still works via ssh from Termux)

Commenting it out restores C-b.

Having installed tmux via brew on macos, is building from source the only way to step back down to 3.3 or before?

Thanks!

**Comment by ucomru** [comment]
> ### Issue description
> I am using neovim inside of tmux. One of the keymaps I have is 'Control + `'. This keymap works outside of tmux but when run within tmux, it runs my neovim keymap for '`'. It looks like tmux is interfering somewhere in between and messing with any keybind starting with Control.
> 
> Another example: the 'Control + l' keybind is supposed to clear the terminal screen and this works outside of tmux but again doesn't work inside tmux.
> 
> I have attempted to fix this issue by adding 'unbind C-`' to my tmux conf file but it didn't do anything.
> 
> This issue is occuring in both iterm and alacritty.
> 
> ### Required information
> * tmux version: 3.4
> * Platform: Darwin arm
> * $TERM: alacritty, screen-256color
> * Logs from tmux: N/A

https://github.com/tmux/tmux/issues/3884#issuecomment-2012459381

It's helped to me with `CTRL` + _non regular keys_:

---

**The short instruction**:

1) **iTerm**:
- `Profiles -> Keys -> General`: _`Report modifiers using CSI`_ -- set check box **`ON`**
- `Profiles -> Keys -> Key Mappings`: _`Presets`_ -- set **`xterm Defaults`**

2) Add to **`~/.tmux.conf`**:
```bash
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
```

3) Detach `tmux` and run command: **`tmux kill-server`**
4) Restart `iTerm2` and enjoy...
