### ISSUE TITLE
split-window's -l gets ignored when issued as a command in the shell

### ISSUE THREAD

**Issue by rieje** [tmux/tmux#3909]
### Issue description
split-window's -l gets ignored when issued as a command in the shell. As an example, bash:

    tmux new-session -d -s "nnn" \; \
      new-window -t nnn \; \
      split-window -h -t nnn \; \
      split-window -fv -t nnn -l 8
 
    tmux a -t nnn

The last split window is split without sizing it up 8 lines. If I omit the last line from this command instead do it manually running it as a tmux command within tmux: `:split-window -fv -t nnn -l 8`, it splits and sizes it to 8 lines as expected.

### Required information

* tmux version: 3.4
* Platform: Linux unknown
* `$TERM=alacritty` (outside) and `$TERM=tmux-256color` inside of tmux

**Comment by nicm** [comment]
Does it work if you specify the terminal size with -x/-y to new-session instead of letting tmux start it at 80x24 and resize when on attach?

**Comment by rieje** [comment]
Yes it works!

**Comment by nicm** [comment]
Good stuff.
