### ISSUE TITLE
tmux -CC : first window theme different from the subsequent ones

### ISSUE THREAD

**Issue by aphecetche** [tmux/tmux#391]
Hi,

Working on MBP under El Capitan (10.11.4), with iTerm2 Build 2.9.20160426
 and tmux 2.1.

I'm trying to use tmux -CC but get the following strange behaviour (see attached screenshot) : 

1 - when doing tmux -CC new-session, the window (tab really, but I've then exploded those into windows for the screeshot) that appears is white (while my theme is a dark one). Note that this one is numbered 3 in the screenshot (no idea why ?)

2 - the next windows (or tabs) (numbered 1 and 4) appear to have the correct theme but littered with a bunch of "tmux;tmux;..." (29 to be precise). 

Concerning the point 2 I guess this is related to the theming script I use (https://github.com/chriskempson/base16-shell/blob/master/base16-solarized.dark.sh) which indeeds sends "strange" things in the tmux case. But what I don't get is why the first window is different. 

Thanks,

<img width="1440" alt="capture d ecran 2016-04-29 a 16 38 32" src="https://cloud.githubusercontent.com/assets/1566009/14919422/0cbfabd2-0e29-11e6-901b-3f75e0df7363.png">

**Comment by nicm** [comment]
tmux has nothing to do with the colours of iTerm2 windows.

**Comment by aphecetche** [comment]
My bad, intended to post this to iTerm2 project, obviously. Sorry about that.
