### ISSUE TITLE
Customize `copy-mode` status format

### ISSUE THREAD

**Issue by musjj** [tmux/tmux#3910]
### Issue description

When you enter `copy-mode`, you will see a status on the top-right corner of the pane. It'd be nice if we can customize the format of this message, just like `remain-on-exit-format`, `window-status-format`, etc.

### Required information

Please provide the following information:

* tmux version: 3.4.
* Platform: Linux unknown.
* $TERM inside and outside of tmux: `tmux-256color` inside, `xterm-kitty` outside.
* Logs from tmux: N/A.

**Comment by nicm** [comment]
This will be available now in master (`copy-mode-position-format`) as soon as GitHub syncs, probably later today.
