### ISSUE TITLE
unable to copy text into system clipboard

### ISSUE THREAD

**Issue by GooVincent** [tmux/tmux#3911]
### Issue description

I use the mouse to select a string, like "text", it's working when paste with C-a and press P. but failed to paste into the other applicaion, like broswer and text editor etc by ctrl+v. ctrl + v is my system shortcuts for paste.

Please anyone could help me on this?

### Required information

Please provide the following information:

* tmux version: 3.2a
* Platform (`uname -sp`): Linux x86_64, Ubuntu 22.04.1 LTS
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-out-1030961.log](https://github.com/tmux/tmux/files/14783438/tmux-out-1030961.log)
[tmux-client-1030959.log](https://github.com/tmux/tmux/files/14783441/tmux-client-1030959.log)
tmux-server.log is too large(1.5M), always failed to upload.

### config file .tmux.conf
```
# remap prefix from 'C-b' to 'C-a'
set -sg escape-time 1
set -g base-index 1
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

setw -g mouse on

#set -g default-terminal "screen-256color"
set -as terminal-features ',rxvt-unicode-256color:clipboard'
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind c new-window -c "#{pane_current_path}"

#split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind-key l last-window

#set-window-option -g mode-keys vi
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer

#set -s set-clipboard external
set -s copy-command 'xsel -i'
bind -Tcopy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel 'xsel -i'
```

**Comment by nicm** [comment]
https://github.com/tmux/tmux/wiki/Clipboard

**Comment by GooVincent** [comment]
> https://github.com/tmux/tmux/wiki/Clipboard

I have read the guide already, but not clear why the tmux failed to copy  to system clipboard.

**Comment by nicm** [comment]
How would it be clear to me either without the server log?

**Comment by nicm** [comment]
Try gzip or zip the server log to upload.

**Comment by GooVincent** [comment]
sorry for that, here is [tmux-server-1030961.log.gz](https://github.com/tmux/tmux/files/14802596/tmux-server-1030961.log.gz)

**Comment by nicm** [comment]
You are running tmux over ssh, yes? Do you have ssh X11 forwarding set up? I do not see DISPLAY set in the environment, so xsel will not know how to talk to the X server on your local computer.

**Comment by GooVincent** [comment]
Yes, with ssh. This time I set up the X11 forwarding, and in the host I executed following cmd
```
root@user:~# echo $DISPLAY
localhost:10.0
```

tmux still failed to copy to system clipboard. Following is the server log.
[tmux-server-321608.log.gz](https://github.com/tmux/tmux/files/14809416/tmux-server-321608.log.gz)

**Comment by nicm** [comment]
Does `echo xyz|xsel` work if you run it after ssh but outside tmux? What if you run it in a tmux pane?

**Comment by nicm** [comment]
Does it copy outside tmux when you pipe something to xsel (after ssh)?

**Comment by GooVincent** [comment]
No, I pipe 'xyz' in tmux, then try to paste in the other app, the content is different thing.

**Comment by GooVincent** [comment]
No, it doesn't.

**Comment by krader1961** [comment]
Copying text selections over SSH requires enabling forwarding the X11 protocol. See the `ForwardX11` option and the `-X` flag.

**Comment by GooVincent** [comment]
> Copying text selections over SSH requires enabling forwarding the X11 protocol. See the `ForwardX11` option and the `-X` flag.
I have enabled ForwardX11 already. Anyway to see that why tmux copy text failed?

**Comment by nicm** [comment]
You know that `echo xyz|xsel -i` doesn't work outside tmux so it seems like this is an ssh forwarding problem not a tmux problem. Are you sure you don't want `-b` for `xsel`? Do other X programs work or give an error? What does `ssh -vvv` say?

**Comment by GooVincent** [comment]
Following my new testing for what **ssh -vvv** says.
```
root@hs:~# echo xyz|xsel -i
debug3: receive packet: type 90
debug1: client_input_channel_open: ctype x11 rchan 4 win 65536 max 16384
debug1: client_request_x11: request from 127.0.0.1 50686
debug2: fd 8 setting O_NONBLOCK
debug3: fd 8 is O_NONBLOCK
debug1: channel 2: new [x11]
debug1: confirm x11
debug3: send packet: type 91
root@hs:~# 
root@hs:~# 
root@hs:~# echo xyz|xsel -b
debug3: receive packet: type 90
debug1: client_input_channel_open: ctype x11 rchan 5 win 65536 max 16384
debug1: client_request_x11: request from 127.0.0.1 48344
debug2: fd 9 setting O_NONBLOCK
debug3: fd 9 is O_NONBLOCK
debug1: channel 3: new [x11]
debug1: confirm x11
debug3: send packet: type 91
root@hs:~# debug3: receive packet: type 96
debug2: channel 1: rcvd eof
debug2: channel 1: output open -> drain
debug2: channel 1: obuf empty
debug2: chan_shutdown_write: channel 1: (i0 o1 sock 7 wfd 7 efd -1 [closed])
debug2: channel 1: output drain -> closed
debug1: channel 1: FORCE input drain
debug2: channel 1: ibuf empty
debug2: channel 1: send eof
debug3: send packet: type 96
debug2: channel 1: input drain -> closed
debug2: channel 1: send close
debug3: send packet: type 97
debug3: channel 1: will not send data after close
debug3: channel 1: will not send data after close
debug3: channel 1: will not send data after close
debug3: channel 1: will not send data after close
debug3: channel 1: will not send data after close
debug3: channel 1: will not send data after close
debug3: channel 1: will not send data after close
debug3: receive packet: type 97
debug2: channel 1: rcvd close
debug3: channel 1: will not send data after close
debug2: channel 1: is dead
debug2: channel 1: garbage collecting
debug1: channel 1: free: x11, nchannels 4
debug3: channel 1: status: The following connections are open:
  #0 client-session (t4 r0 i0/0 o0/0 e[write]/0 fd 4/5/6 sock -1 cc -1 io 0x01/0x00)
  #1 x11 (t4 r3 i3/0 o3/0 e[closed]/0 fd 7/7/-1 sock 7 cc -1 io 0x00/0x00)
  #2 x11 (t4 r4 i0/0 o0/0 e[closed]/0 fd 8/8/-1 sock 8 cc -1 io 0x01/0x00)
  #3 x11 (t4 r5 i0/0 o0/0 e[closed]/0 fd 9/9/-1 sock 9 cc -1 io 0x01/0x00)

debug3: receive packet: type 96
debug2: channel 2: rcvd eof
debug2: channel 2: output open -> drain
debug2: channel 2: obuf empty
debug2: chan_shutdown_write: channel 2: (i0 o1 sock 8 wfd 8 efd -1 [closed])
debug2: channel 2: output drain -> closed
debug1: channel 2: FORCE input drain
debug2: channel 2: ibuf empty
debug2: channel 2: send eof
debug3: send packet: type 96
debug2: channel 2: input drain -> closed
debug2: channel 2: send close
debug3: send packet: type 97
debug3: channel 2: will not send data after close
debug3: receive packet: type 97
debug2: channel 2: rcvd close
debug3: channel 2: will not send data after close
debug2: channel 2: is dead
debug2: channel 2: garbage collecting
debug1: channel 2: free: x11, nchannels 3
debug3: channel 2: status: The following connections are open:
  #0 client-session (t4 r0 i0/0 o0/0 e[write]/0 fd 4/5/6 sock -1 cc -1 io 0x01/0x00)
  #2 x11 (t4 r4 i3/0 o3/0 e[closed]/0 fd 8/8/-1 sock 8 cc -1 io 0x00/0x00)
  #3 x11 (t4 r5 i0/0 o0/0 e[closed]/0 fd 9/9/-1 sock 9 cc -1 io 0x01/0x00)
```

Then I add -b in the .tmux.conf which finnally is 'set -s copy-command 'xsel -i -b'. Now it works. Thanks a million.
