### ISSUE TITLE
Inconsistency with allow-passthrough Option in tmux 3.3a

### ISSUE THREAD

**Issue by huangyingw** [tmux/tmux#3912]
### Issue description

I encountered some confusion when attempting to use the `allow-passthrough` option in `tmux`. In one environment (hostname `server`, running `tmux 3.3a`), executing `tmux set -g allow-passthrough on` results in an `invalid option: allow-passthrough` error. However, in another environment (hostname `mini`, also running `tmux 3.3a`), the same command appears to be accepted without any error message. I would like to understand why there is this discrepancy and how the `allow-passthrough` option is intended to be used.

#### Steps to reproduce

1. Open a terminal.
2. Start `tmux` ensuring the version is 3.3a.
3. Execute the command `tmux set -g allow-passthrough on`.
   - On the `server` machine, this displays the error `invalid option: allow-passthrough`.
   - On the `mini` machine, the command seems to be accepted without any error message.

#### Expected behavior

I expect clarification on the use and status of the `allow-passthrough` option in `tmux`, including whether it is a valid option and why there might be different feedback in different environments.

### Required information

* tmux version: `tmux 3.3a`.
* Platform: Linux x86_64 (same result on both machines).
* $TERM inside and outside of tmux: `xterm-256color` (same result on both machines, both inside and outside of `tmux`).

**Comment by nicm** [comment]
I bet one of them is an older version, what does `tmux display -p '#{version}'` show?

**Comment by huangyingw** [comment]
these are the commands I used to build
```
sh autogen.sh
./configure
make
sudo make install
```

**Comment by huangyingw** [comment]
ok, I solved this issue by myself, for I have 2 tmux installed, rm the old one, now, I got the latest version building from source code running correctly.
