### ISSUE TITLE
Need help with escaping %  properly in 'tmux command-prompt'

### ISSUE THREAD

**Issue by SivanagBalla** [tmux/tmux#3913]
### Issue description

I have requirements to record entire pane output as follows
 - Should be able to trigger record in any pane and that pane output will be saved to a file
 - Before staring recording, it should ask me the file name to which the pane output will be saved
 - Current timestamp should be prepended to everyline that gets printed in the pane. I should be asked for timestmap format also

I'm able to fulfull all above with below command which is put in a script. 
```
tmux  command-prompt -p 'Record filename:','Options:'  -I '~/tp/def_rec','"[%%%%H:%%%%M:%%%%S]"' \
     'pipe-pane "ts %2 > %1_ts"'
```
(Yes, I had to put four '%' to make it work, because it promtps for timestamp where two '%' are consumed and when invoking command tmux consume one more '%')

When i call the script, it asks the filename like below
![image](https://github.com/tmux/tmux/assets/19350704/a3515781-5007-497d-84c4-b83d563f8261)

Next it asks me the timestamp format like below. 
![image](https://github.com/tmux/tmux/assets/19350704/a1bb3db5-c937-435e-8964-b26952bc93f5)

Finally it will start saving the output to file like below (note the timestamp corresponds to the time the line appered in pane not some fixed timestamp)

```
[20:45:09] Detected device id0:0xae02, id1:0x5230
[20:45:09] Chip found!!! Initializing PHY....
[20:45:09] core->pm_core.type = 0
[20:45:15] Core Ver:0
```
The command invoked by tmux is as below
` sh -c ts [%H:%M:%S] > ~/tp/def_rec_ts`

All of this was working perfectly fine until tmux 3.2a.

I upgraded to tmux 3.3a and timestamp got messed up. When i call the script, same prompts appear but the command invoked by tmux is different.

`sh -c ts [[%H:%M:%S]H:%M:%S] > ~/tp/def_rec_ts`

Output in file:
```
[[12:26:24]H:26:24] siballa@bgl-ads-3366:~ $ echo "test line"; sleep 5; echo "test line2 afer 5secs"
[[12:26:24]H:26:24] test line
[[12:26:29]H:26:29] test line2 afer 5secs
```

I tried below modification - although not 

Replaced '%2' with '%%' for ts command

```
tmux  command-prompt -p 'Record filename:','Options:'  -I '~/tp/def_rec','"[%%%%H:%%%%M:%%%%S]"' \
     'pipe-pane "ts %% > %1_ts"'
```

--> this resulted in first argument: ~/tp/def_rec being prepended to each line in output file

Replaced four '%' with two '%'
```
tmux  command-prompt -p 'Record filename:','Options:'  -I '~/tp/def_rec','"[%%H:%%M:%%S]"' \
     'pipe-pane "ts %2 > %1_ts"'
```

--> this resulted in fixed time stamp (time when recording started) being prepended to each line in output file. Command invoked by 
 tmux is `sh -c ts [12:38:31] > ~/tp/def_rec_ts`

How do i fix this.??

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
```
siballa@bgl-ads-3366:~/tp $ tmux -V
tmux 3.3a
siballa@bgl-ads-3366:~/tp $ uname -sp
Linux x86_64
```
* $TERM inside and outside of tmux (`echo $TERM`).
```
siballa@bgl-ads-3366:~/tp $ echo $TERM
xterm-256color
```

* Logs from tmux (`tmux kill-server; tmux -vv new`).

Can't kill server, I have a lot of sessions and windows that are open

**Comment by SivanagBalla** [comment]
Don't know why no one responded this. May be its too length to read.

Anyway, I got it fixed, I replaced `'"[%%%%H:%%%%M:%%%%S]"'` with '`"[\%%\%%H:\%%\%%M:\%%\%%S]"'` and then it started working.

**Comment by krader1961** [comment]
> Don't know why no one responded this. May be its too length to read.

I'm glad you solved your problem. I suspect the reason no one responded is because the sort of string interpolation problem you were dealing with is inherently hard and unusual. Very few people are going to expend the effort to figure out a solution for a problem of this nature. Notice how hard it is to interpret the string in your solution. When I saw your question the first thing that occurred to me is Tmux is the wrong tool for your problem. You should be using something like a custom version of the `script` command.
