### ISSUE TITLE
[Request feature] visible mark at top right coner to easy switch pane?

### ISSUE THREAD

**Issue by tmpm697** [tmux/tmux#3914]
I find it hard to switch pane with tmux, tried some methods like use `key-table` or just `select-pane` + number to quick switch some panes in a window.

tmux has `display-panes` and select a number to switch pane, but i still find it not elegant and intuitive enough.

what i want is a combined keys to trigger mode same like `display-panes` but showing `marks` at top right conner of each pane window with a `random` character instead of number.

like this plugin from neovim to quick navigate text: https://github.com/ggandor/leap.nvim

i.g: we have three panes in current focused window -> press alt+p --> showing 3 random marks: h, u, l at top right conner of 3 panes -> user press either h or u or l to select that correct pane

@nicm

**Comment by nicm** [comment]
How is a random character any better than pressing "0" or "1" or "2"? Seems a lot worse.

**Comment by tmpm697** [comment]
> How is a random character any better than pressing "0" or "1" or "2"? Seems a lot worse.

it's not that `worse` as if you intend those random chars around `g, h, j, k, l, n, m, y, u, i, o` that just there for user to press on,

reaching and distinguish where is 3, where is 4, look if i can mistakenly press 3 instead of 4 is another level of `worse`

**Comment by tmpm697** [comment]
> You can mistakenly press `3` instead of `4` but not `j` instead of `h`?
> 
> I don't see any difference between pressing `M-p q` to go to pane 0 and `C-b q 0` to go to pane 0.

you're doing the edge case, <10 panes let make it chars near right hand in keyboard. it's not the same. but this request is probably QOS request :)

**Comment by tmpm697** [comment]
This is what i'm doing rn for quick and easy to navigate pane, it's hacky:
```
  26   │ bind -n M-j select-pane -t 1
  27   │ bind -n M-k select-pane -t 2
  28   │ bind -n M-l select-pane -t 3
  29   │ bind -n M-J select-pane -t 4
  30   │ bind -n M-K select-pane -t 5
  ```

**Comment by nicm** [comment]
I don't think showing in the right corner is any different from showing in the middle of the pane.

I think you just want it to be what you're used to. There is no practical difference between a number key shown in the middle of the pane and a letter key shown the top right of the pane.

**Comment by tmpm697** [comment]
> I don't think showing in the right corner is any different from showing in the middle of the pane.
> 
> I think you just want it to be what you're used to. There is no practical difference between a number key shown in the middle of the pane and a letter key shown the top right of the pane.

can be different view in UX/UI, my suggestion will be an improvement in user's experience but idk the cost of code complexity, anyway even that feature implemented, it still can't beat my current fixed mappings, once i get used to it.

**Comment by nicm** [comment]
But you are not telling me why it would be an improvement, so I am not convinced it would be. How it showing a number in the middle of each pane and then the user presses that number any less intuitive or slower to use than showing a letter in a corner of each pane and the user presses that letter? The number of key strokes is exactly the same.

You can also navigate panes using the arrow keys or by clicking with the mouse or by binding your own custom keys.

**Comment by tmpm697** [comment]
> But you are not telling me why it would be an improvement, so I am not convinced it would be. How it showing a number in the middle of each pane and then the user presses that number any less intuitive or slower to use than showing a letter in a corner of each pane and the user presses that letter? The number of key strokes is exactly the same.
> 
> You can also navigate panes using the arrow keys or by clicking with the mouse or by binding your own custom keys.

The idea is the same why https://github.com/ggandor/leap.nvim exist, you `see` that pane, you `select` that pane, that easy.

algorithm that if pane in current window < 10 for example, then random chars near user's right hand like `j, k, l ...` that will boost up fast navigate between pane.

I have always look up my eyes on numbers to select it correctly, meanwhile I know exactly where `j, k, l..` because my right hand already touching one of those keys.

**Comment by nicm** [comment]
This link seems to be to do with searching in vim not with switching panes.

I'm not convinced this is any better. The number keys are always in the same place on the keyboard just as much as the j,k,l keys are and it just seems like personal preference.

But I don't really mind adding additional aliases so pane 0 is always `h` as well as `0`, if you want to look at that you can look at `cmd-display-panes.c`.

**Comment by tmpm697** [comment]
> This is what i'm doing rn for quick and easy to navigate pane, it's bad due to hardcoded the pane index:
> 
> ```
> bind -n M-j select-pane -t 1
> bind -n M-k select-pane -t 2
> bind -n M-l select-pane -t 3
> bind -n M-J select-pane -t 4
> bind -n M-K select-pane -t 5
> bind -n M-L select-pane -t 6
> ```
> 
> that's why i prefer to `M-p` then `h or j, or k, or ....` showing in right conner of the pane --> much easier.
> 
> the `showing in right conner` is another thing to quick identify pane to navigate. (like a small circle or square with chars or just chars at right conner with able to set the color of it)

I gave this example but it's bad as I always have to re-map and *count* in my memory that `j` is 1st pane, `k` is pane 2nd...

You look at the pane, seeing that character and then press the key to select is better, instead try to recall "ah, this seem like pane 3 (1, 2, 3 orderly, seem correct) and it should be key `l` for it to switch to` --> purely bad.

I don't think it's personal preference, I suggesting this from my struggle when work with tmux, it's nice but can be better.

**Comment by nicm** [comment]
> You just dummy look at the pane, seeing that character 

This makes no sense to me, looking for small `j` in the corner seems no better than looking for a giant `1` in the middle.
