### ISSUE TITLE
Gaps around tmux bar when resizing the terminal

### ISSUE THREAD

**Issue by Solarunit** [tmux/tmux#3918]
### Issue description

Not sure if it's a tmux issue it alacritty ussue, or both.
When resizing a terminal window, tmux bar can't position itself properly and you will see gaps below it (and on the sides)

Screenshot:

![tmux](https://github.com/tmux/tmux/assets/20891064/e5b83285-b6f8-491a-a26f-a7402a3bf496)

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.4
* Platform (`uname -sp`). Linux
* $TERM inside and outside of tmux (`echo $TERM`). bash: tmux-256color | alacritty

Update: same issue in kitty, but in GNOME Terminal 3.48.0 there is no such problem.

**Comment by successgo** [comment]
It's the terminal side issue. Because the space does not fit for a line.

**Comment by Solarunit** [comment]
>It's the terminal side issue. Because the space does not fit for a line.

GNOME Terminal 3.48.0 doesn't have this problem. On your screenshot the terminal window has a rounded corners, so I guess that's expected. I tried Alacritty and kitty, and both have the same issue, the gap is less than a line and it could be just few pixels. And not rounded corners here.

**Comment by Solarunit** [comment]
Ok, I found the problem. In Alacritty you can set `resize_increments = true` (Default is false)
This will solve tmux issue.

```toml
[window]
resize_increments = true
```
>resize_increments = Prefer resizing window by discrete steps equal to cell dimensions.

But maybe tmux bar could adapt when resize_increments is false too?
