### ISSUE TITLE
detach-on-destroy option does not find most recently used session

### ISSUE THREAD

**Issue by vimpostor** [tmux/tmux#3922]
It is kinda surprising to me that this bug went unnoticed for almost 15 years, but the `detach-on-destroy` option does not actually do what the man page says it does, because a comparison is flipped by accident.

The man page describes the following:
```
if detached sessions exist, the client is switched to the most recently active.
```

That behaviour would be sensible, but the following check does the exact opposite thing and finds the least recently used session instead (i.e. the oldest session):
```c
return (timercmp(&s_loop->activity_time, &s_out->activity_time, <));
```

The `<` should be a `>`.
Attached, here is a patch that fixes the issue:

[0001-Fix-inverted-timercmp-for-detach-on-destroy.patch.txt](https://github.com/tmux/tmux/files/14858598/0001-Fix-inverted-timercmp-for-detach-on-destroy.patch.txt)

Additionally, here is a visualization of the problem: https://asciinema.org/a/lAn98PyX9QPq1IvXdOeaELiAS
On the left side is unpatched tmux with broken behaviour, on the right side the fixed version with my patch.

In the screencast I open multiple sessions and then close them again. The left side shows the problem of tmux not automatically selecting the most recently active session, rather it always selects the oldest session. For further visualization the bottom status line shows the currently active session highlighted as a yellow dot.

FYI the dotted session visualization was accomplished with the following status format:
```
set -g status-left "#[align=absolute-centre]#{?#{e|>:#{server_sessions},1},#{S:#{?#{==:#{session_name},#{client_session}},#[fg=colour3]\u00B7#[fg=default],\u00B7}} ,}"
```

**Comment by nicm** [comment]
Yes, good spot... clearly either nobody has used it or they've never really cared which session they end up in. Fixed in OpenBSD now, will be in GitHub later. Thanks!
