### ISSUE TITLE
Regression of `run-shell` command (with workaround)

### ISSUE THREAD

**Issue by pyhedgehog** [tmux/tmux#3924]
### Issue description

In previous versions (in 3.2), `tmux run ...` (i.e. `run-shell` from one-command client without `-t` option) sends output of command to client stdout. But in 3.4 (and 3.3a which manifests itself as `next-3.4`) it creates view mode in active pane (even if there are no attached client at all).

Maybe I've missed item in CHANGES? I think that good idea is to mention this in desription of `run-shell` command, or return old behaviour if this change was unintentional. Also option `-p` will be good for similarity with `capture-pane` and `display-message`.

### Workaround

If you've used in your script, i.e. `tmux run 'id -Gn'`, you can replace it with `tmux run 'tmux set -g @id "$(id -Gn)"' \; display -p '#{@id}'`.

### Required information

* tmux version: 3.4
* Platform: Linux x86_64
* $TERM=xterm-256color, default-terminal=screen
* Logs from tmux - N/A.

**Comment by nicm** [comment]
Yes... I think this was an accident. Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/14929208/x.diff.txt)
