### ISSUE TITLE
[Feature Request] Provide option 'window-status-activity-format'

### ISSUE THREAD

**Issue by QuocAnhVu** [tmux/tmux#3927]
### Proposal

The tabs of a tmux status bar have three states:

- normal - unselected windows
- current - selected windows
- activity - windows with some sort of running process

There are three corresponding "style" options to adjust the color of these tabs:

- `window-status-style`
- `window-status-current-style`
- `window status-activity-style`

For users that want to style with glyphs, there are two "format" options: 

- `window-status-format`
- `window-status-current-format`

`window-status-activity-format` is conspicuously missing. Let's add it.

### Problem

If `window-status-format` is set, you cannot customize styling of an activity state. `window-status-format` being set will cause any value of `window-status-style` to be ignored. If `windows-status-style` is not set, then the default behavior of an activity state is to swap fg and bg colors. 

![Screenshot from 2024-04-06 14-24-19](https://github.com/tmux/tmux/assets/5098329/82584867-1e79-4374-a37a-a82f15693cf6)
_The second tab is in an activity state, which is causing an undesired aesthetic._

![Screenshot from 2024-04-06 14-31-29](https://github.com/tmux/tmux/assets/5098329/420a5eaa-53da-4446-b4dd-46c87bbb64fc)
_An okay workaround is to set `window-status-activity-style` to an empty string, which disables the behavior, but hides activity._

A `window-status-activity-format` option will allow users to customize tabs in an activity state. As a bonus, users will be able to signal an activity state with glyphs, instead of just colors/blinking.

**Comment by nicm** [comment]
You should be able to do this with conditionals in `window-status-style` or `window-status-format` so I don't think there is a need for a separate option.

**Comment by QuocAnhVu** [comment]
Could you provide an example or show me where that behavior is documented so I can read about it?

**Comment by QuocAnhVu** [comment]
I figured it out. Documentation found at `man tmux`.

An example config that puts the tab with activity in bold is this:

```sh
set -g window-status-current-format "#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#W #F #[fg=cyan,bg=black,nobold,noitalics,nounderscore]"
%hidden NORMAL_FORMAT="#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#I #[fg=white,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#W #F #[fg=brightblack,bg=black,nobold,noitalics,nounderscore]"
%hidden ACTIVITY_FORMAT="#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack,bold]#I #[fg=white,bg=brightblack,bold,noitalics,nounderscore] #[fg=white,bg=brightblack,bold]#W #F #[fg=brightblack,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-format "#{?window_activity_flag,#{E:ACTIVITY_FORMAT},#{E:NORMAL_FORMAT}}"
```

This gets me something like this:

![Screenshot from 2024-04-07 05-50-08](https://github.com/tmux/tmux/assets/5098329/b7c48b7e-59f1-4fa4-bf92-d50942d3948e)
_The second tab (with activity) now has bold text._

### PS: A small gripe.

I tried to make the bold consistent across current and normal tabs, but it seems that `window_activity_flag` is set to 0 on the current tab.

```sh
%hidden NORMAL_CURRENT_FORMAT="#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#W #F #[fg=cyan,bg=black,nobold,noitalics,nounderscore]"
%hidden ACTIVITY_CURRENT_FORMAT="#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan,bold]#I #[fg=black,bg=cyan,bold,noitalics,nounderscore] #[fg=black,bg=cyan,bold]#W #F #[fg=cyan,bg=black,nobold,noitalics,nounderscore]"
set - window-status-current-format="#{?window_activity_flag,#{E:ACTIVITY_CURRENT_FORMAT},#{E:NORMAL_CURRENT_FORMAT}}"
```

![Screenshot from 2024-04-07 05-57-42](https://github.com/tmux/tmux/assets/5098329/38acfec0-d443-4ab1-9e62-92b53c3514ef)
_Current window with activity should have bolded text according to my config._

**Comment by nicm** [comment]
Activity, bell etc don't apply to the current window on the grounds that there is no point notifying you about the window you are looking at.

**Comment by nicm** [comment]
I don't agree.

**Comment by QuocAnhVu** [comment]
Personally, I think consistency is important in UX but I also believe every project gets to define its own set of values. I imagine changing `window_activity_flag` to `1` on current windows may be a breaking change for many users' configs and I trust that your judgement that this functionality is not worth pursuing for tmux.

I'm closing this as we've gone far away from the original proposal. Conditionals are excellent and they solve 80% of the problem.
