### ISSUE TITLE
default-terminal 'tmux-direct' showing bright-named colors as black

### ISSUE THREAD

**Issue by jwfang** [tmux/tmux#3929]
* tmux version (`tmux -V`).
`tmux next-3.5`
* Platform (`uname -sp`).
`Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`).
inside `tmux-direct`
outside `alacritty` and `wezterm`
* configuration file
```
cat ./tmux.conf
set -g default-terminal "tmux-direct"
```

```
tput setaf 1; echo hello; tput sgr0
hello # in RED
tput setaf 1; echo hello; tput sgr0
hello # in BLACK, should be BRIGHT RED
```

This cause some applications, such as viewing man-pages using `most` and `htop`, showing `black`, which is hard to spot in a dark theme.

**Comment by nicm** [comment]
What do you expect me to do with this? No logs and example commands that don't show anything.

**Comment by jwfang** [comment]
> What do you expect me to do with this? No logs and example commands that don't show anything.

The `tput` command are run in `shell`, and comments after `#` are expected result. 

I don't know what logs are required, maybe i can post some screeshots if github allow it.

**Comment by nicm** [comment]
These screenshots don't show the commands you gave.

But it doesn't matter - this behaviour is expected: the `-direct` variants do not support aixterm bright colour variants (SGR 91 etc). AFAIK there is no way to emit the aixterm colours using `-direct` terminfo entries. You can try `xterm-direct` outside tmux and you'll see the same.

This is perhaps a bit of a pity but it is what it is and applications need to handle it themselves, so you probably need to talk to the most and htop developers.

**Comment by jwfang** [comment]
**outside `tmux`**, `xterm-direct` works fine, it seems ignore BRIGHT color, but `alacritty-direct` that has the same showing black problem.
The only relevant difference i can find it's the seperator for 24-bit color escape: `:` ignore BRIGHT colors but `;` showing black.

i am not quite understand the "no aixterm bright color for -direct" thing. Why can't we just translate color below 16 to the old  ways of setting color, like `setaf` does in the `-256color` `terminfo`? We lose another 8 `black` but more compatible with old applicaton.

```
❯ infocmp xterm-256color | rg setaf
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
```

**Comment by nicm** [comment]
> outside tmux, xterm-direct works fine

If it works then you are not testing the same thing. All `-direct` generate the same sequence for 9:
~~~~
$ tput -Txterm-direct setaf 9|cat -v; echo
^[[38:2::0:0:9m
$ tput -Ttmux-direct setaf 9|cat -v; echo
^[[38:2::0:0:9m
$ tput -Talacritty-direct setaf 9|cat -v; echo
^[[38;2;0;0;9m
~~~~

> i am not quite understand the "no aixterm bright color for -direct" thing. Why can't we just translate color below 16 to the old ways of setting color

You will need to talk with @ThomasDickey about the reason for this, but whatever they are, I suspect the ship has now long sailed.

**Comment by jwfang** [comment]
> > outside tmux, xterm-direct works fine
> 
> If it works then you are not testing the same thing. All `-direct` generate this for 9 (RGB 000009 which is black):
> 
> ```
> $ tput -Txterm-direct setaf 9|cat -v; echo
> ^[[38:2::0:0:9m
> $ tput -Ttmux-direct setaf 9|cat -v; echo
> ^[[38:2::0:0:9m
> $ tput -Talacritty-direct setaf 9|cat -v; echo
> ^[[38;2;0;0;9m
> ```

By works fine i mean not showing black: `xterm-direct` seems just ignore the BRIGHT color, showing normal color instead.

`tput` show idential color but different escape seperator: `:` vs `;`. Not showing the same result for `TERM=XXX htop` command: `:` ignoring color but `;` showing black. Maybe `ncurses` implementation related.

> 
> > i am not quite understand the "no aixterm bright color for -direct" thing. Why can't we just translate color below 16 to the old ways of setting color
> 
> You will need to talk with @ThomasDickey about the reason for this, but whatever they are, I suspect the ship has now long sailed.

Thank you for your explanation. I am curious about the reason, since there are no translation of 8-15 color in `-direct` terminfo either. I guess they're related.

**Comment by nicm** [comment]
The `;` and `:` should not change anything so I guess you are either seeing a bug in your terminal or there is a workaround for this case in the terminal or application.

**Comment by jwfang** [comment]
Thanks. I am now wondering what's the point of `-direct` terminfo.

If i choose `-256color`, most application will show properly, more _advanced_ applications will test _TRUECOLOR_ support themself (maybe directly write color escape sequence i guess);

On the other hand, when choose `-direct`, many existing applications will not showing properly, but what we get in return?

Maybe for everyday use, `-256color` is the way to go ?

**Comment by jwfang** [comment]
I end up compile my own `terminfo` which does translation for the BRIGHT named color, let's see how it goes.
