### ISSUE TITLE
missing or unsuitable terminal :xterm-256color

### ISSUE THREAD

**Issue by rmGFW** [tmux/tmux#3931]
i install tmux from source code compile use branch master follow the [installing wiki](https://github.com/tmux/tmux/wiki/Installing#from-source-tarball)

but the binary execute failed with `missing or unsuitable terminal :xterm-256color` 

```txt
 find / -name "*xterm-256color*"
/usr/lib/terminfo/x/xterm-256color
/usr/lib/terminfo/s/screen.xterm-256color
```
xterm-256color is in my machine , and pre-build tmux installed from apt works well

**Comment by rmGFW** [comment]
> Did you build your own ncurses as well instead of using the system one?

yes , i build ncurses-6.4 , not use system one, 

```shell
wget https://invisible-mirror.net/archives/ncurses/ncurses-6.4.tar.gz \
        && tar -zxf ncurses-*.tar.gz \
        && cd ncurses-*/ \
        && ./configure\
            --enable-bsdpad \
            --enable-ext-colors \
            --enable-ext-mouse \
            --enable-opaque-curses \
            --enable-pc-files \
            --enable-termcap \
            --enable-widec \
            --mandir="/usr/share/man" \
            --prefix="/usr" \
            --with-cxx-shared \
            --with-pkg-config-libdir="/usr/lib/pkgconfig" \
            --with-shared \
            --with-terminfo-dirs=/etc/terminfo:/usr/share/terminfo:/lib/terminfo \
            --with-termlib \
            --with-termpath=/etc/termcap:/usr/share/misc/termcap \
            --with-versioned-syms \
            --with-xterm-kbs=del \
            --without-ada \
            --without-debug \
        && make && make install
```

by the way ,  i build on machine A , and run the binary on the other

**Comment by nicm** [comment]
Did you build a static tmux then? What version is the system ncurses on the machine you are running on?

**Comment by rmGFW** [comment]
> Did you build a static tmux then? What version is the system ncurses on the machine you are running on?

```shell
git clone https://github.com/tmux/tmux.git \
      && cd tmux \
      && git checkout 3.3a \
      && sh autogen.sh \
      && ./configure --prefix=/usr --enable-static && make -j$(nproc) \
      && strip tmux
```
right , i was built a static 

the version of ncurses of the machine that running on 

machine1 
```txt
ii  libncurses5:amd64  6.3-2ubuntu0.1 amd64        shared libraries for terminal handling (legacy version)
ii  libncurses6:amd64  6.3-2ubuntu0.1 amd64        shared libraries for terminal handling
ii  libncursesw5:amd64 6.3-2ubuntu0.1 amd64        shared libraries for terminal handling (wide character legacy version)
ii  libncursesw6:amd64 6.3-2ubuntu0.1 amd64        shared libraries for terminal handling (wide character support)
ii  ncurses-base       6.3-2ubuntu0.1 all          basic terminal type definitions
ii  ncurses-bin        6.3-2ubuntu0.1 amd64        terminal-related programs and man pages
ii  ncurses-term       6.3-2ubuntu0.1 all          additional terminal type definitions
```
machine2
```txt
ii  libncurses5:amd64  6.0+20160213-1ubuntu1 amd64        shared libraries for terminal handling
ii  libncursesw5:amd64 6.0+20160213-1ubuntu1 amd64        shared libraries for terminal handling (wide character support)
ii  ncurses-base       6.0+20160213-1ubuntu1 all          basic terminal type definitions
ii  ncurses-bin        6.0+20160213-1ubuntu1 amd64        terminal-related programs and man pages
ii  ncurses-term       6.0+20160213-1ubuntu1 all          additional terminal type definitions
```

so , should i downgrade the ncurses in the build environment?

**Comment by nicm** [comment]
They are all 6 so should work I think. But don't you need `/usr/lib/terminfo` here:
~~~~
            --with-terminfo-dirs=/etc/terminfo:/usr/share/terminfo:/lib/terminfo \
~~~~

**Comment by rmGFW** [comment]
> They are all 6 so should work I think. But don't you need `/usr/lib/terminfo` here:
> 
> ```
>             --with-terminfo-dirs=/etc/terminfo:/usr/share/terminfo:/lib/terminfo \
> ```

i tried, but still not working in these machine ,  and i found in the other machine C ,  my static build tmux will failed with another error 
```txt

tmux
server exited unexpectedly
                          #
```

**Comment by nicm** [comment]
OK I can't really help you with this you will need to debug it yourself.

Best bet would be to build against the version of ncurses available on the other computers, but you'll need to make sure it is configured with the same terminfo dirs.

**Comment by rmGFW** [comment]
> OK I can't really help you with this you will need to debug it yourself.
> 
> Best bet would be to build against the version of ncurses available on the other computers, but you'll need to make sure it is configured with the same terminfo dirs.

still feel greatly appreciative of you help, let me try downgrade ncurses first
