### ISSUE TITLE
SHELL environment variable on popup windows does not respect default-shell

### ISSUE THREAD

**Issue by s417-lama** [tmux/tmux#3935]
### Issue description

If I have the following configuration,
```
set-option -g default-shell /opt/homebrew/bin/fish
```

then we get the following outcome in tmux panes:
```console
> echo $SHELL
/opt/homebrew/bin/fish
```

Here, the SHELL env val points to `fish`, even if we do not set `fish` as the system's login shell (by `chsh`).

However, in popup windows, the SHELL environmental variable does not point to `fish`, which is specified in the `default-shell` option in `.tmux.conf`.

For example, if we execute:
```sh
tmux popup
```

then a new popup window is shown with the `fish` shell launched on it.

We expect the SHELL variable points to `fish` as well, but actually it was not.

Executing the following command inside the popup window (running the `fish` shell) resulted in:
```console
> echo $SHELL
/opt/homebrew/bin/bash
```

I'm wondering if it is an expected behavior or not.

In fact, this is problematic in using the `fzf-tmux` command with the [fzf.fish](https://github.com/PatrickF1/fzf.fish) plugin for fish.
fzf.fish defines some fish functions and passes them through fzf command arguments (e.g., `--preview`), but if `$SHELL` is not fish on popup windows, fzf on popup windows tries to execute the commands on `$SHELL`. Of course, this causes an error because fish functions are not visible from other shells.

I would appreciate if `$SHELL` is set to the shell configured with `default-shell` even on popup windows if nothing prevents this.

### Required information

* tmux version (`tmux -V`). tmux 3.4
* Platform (`uname -sp`). Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`). tmux-256color (inside), alacritty (outside)

**Comment by nicm** [comment]
Try this please: [tmux-job-shell.diff.txt](https://github.com/tmux/tmux/files/15319037/tmux-job-shell.diff.txt)

**Comment by s417-lama** [comment]
Thank you for your work so much!
I applied it to the current codebase and confirmed that it worked perfectly.
Do you have a plan to merge this patch into the mainstream?

**Comment by nicm** [comment]
It is merged to OpenBSD now, will be in GitHub later. Thanks!
