### ISSUE TITLE
A memory leak defect exists on line 174 of the file /tmux/arguments.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [tmux/tmux#3937]
Dear developers of the tmux project,

Hello! I have discovered a memory leak defect in the latest version of tmux. The defect is located on line 174 of the file /tmux/arguments.c. The specific path to the defect is as follows:

1.In the file /tmux/arguments.c, a pointer variable named 'new' is defined at line 151. This variable allocates a block of dynamic memory using the function xcalloc at line 154. When the if statement at line 171 evaluates to true, the program returns at line 174. During this process, the dynamic memory area pointed to by the 'new' pointer is neither used nor freed, thus resulting in a memory leak, as illustrated in the following diagram:
https://github.com/LuMingYinDetect/tmux_defects/blob/main/tmux_1.png

**Comment by nicm** [comment]
Fixed by #3941, thanks!
