### ISSUE TITLE
There is a memory leak defect on line 80 of the file /tmux/cmd-confirm-before.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [tmux/tmux#3939]
Dear developers of the tmux project,

Hello! I have discovered a memory leak defect in the latest version of tmux. The defect is located on line 80 of the file /tmux/cmd-confirm-before.c. The specific path to the defect is as follows:

1.In the file /tmux/cmd-confirm-before.c, a pointer variable named 'cdata' is defined at line 70, and at line 77, the xcalloc function is used to allocate a block of dynamic memory for this pointer. When the if statement at line 79 evaluates to true (indicating the failure of the assignment to cdata->cmdlist at line 78, but since the code uses a member of the pointer cdata, it implies that the dynamic memory allocation for cdata was successful), the program returns at line 80. During this process, the dynamic memory area pointed to by 'cdata' is not freed, leading to a memory leak, as illustrated in the following diagram:
https://github.com/LuMingYinDetect/tmux_defects/blob/main/tmux_3.png

**Comment by nicm** [comment]
Fixed by #3941, thanks!
