### ISSUE TITLE
how can i keep pane id persistent

### ISSUE THREAD

**Issue by rmGFW** [tmux/tmux#3942]
i found after split pane, it may change other pane's id 

for example 

# only have 1 pane
tmux splitw -t 1 ...
# there two pane exist
tmux splitw -t 1 ...
# the pane with id 2 have changed  to id 3

this make write some bash script more complicated ,  if the id is persistent  and ordered by create time , it will more easy

---
* tmux version (`tmux -V`). : tmux 3.4
* Platform (`uname -sp`). : Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`). screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
You are confusing pane index which does change with pane ID which doesn't. Pane ID will always be prefixed by %, for example %0 %1.
