### ISSUE TITLE
Searching a large string selectively broken in 3.4

### ISSUE THREAD

**Issue by vtk9** [tmux/tmux#3944]
[large_example.json](https://github.com/tmux/tmux/files/15001804/large_example.json)
### Issue description

When a large single line string is outputed to the terminal, searching via `Prefix+[` and then `/` to search for the string `blue` does not work. The word is not found/highlighted. It seems to work for 1 or 2 or sometimes 3 character strings. 

To reproduce, print out the attached example file `cat large_example.json`. Then try to search for the word blue

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.4. Issue is not present in 3.3a
* Platform (`uname -sp`).
  - Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`).
  - Inside: `screen-256color`
  - Outside: `xterm-256color`
  - reproduced on default macos terminal with default configuration
* Logs from tmux (`tmux kill-server; tmux -vv new`).
  - N/A

**Comment by yan12125** [comment]
Same issue as https://github.com/tmux/tmux/issues/3864 ?

**Comment by cyanpencil** [comment]
No, it's not the same. I can reproduce even for the first part (non-wrapped lines)

**Comment by cyanpencil** [comment]
@yan12125 I am dumb. I re-read the issue #3864 and it is exactly the same. 
I can only search on the last part of the string (the last visual line, non-wrapped)

**Comment by kmarkley86** [comment]
I stumbled onto this, too.  Here's a very simple way to reproduce it.

1. Start tmux
2. C-b :list-keys
3. C-b :send-keys -X search-forward Double

If the terminal is narrow enough that the line with DoubleClick1Pane wraps, then search-forward will fail to match it.

**Comment by timotheecour** [comment]
I was going to file an issue and then found that this issue is the same as I was having; a few more info:
* search backward is also broken
* it also affects ubuntu
* it's indeed a regression from 3.3a to 3.4
* the issue disappears as soon as there is no line wrap (eg by resizing terminal width) and re-appears when we have line wrap
I have a test case to reproduce in case it's needed but looks like others have already reported such test cases

**Comment by vtk9** [comment]
@nicm Can we re-open given that the fix for this was reverted? https://github.com/tmux/tmux/pull/3975#issuecomment-2109691584

**Comment by MeanderingProgrammer** [comment]
Hey @vtk9, while the change I made was reverted so was the original change that caused the problem in searching wrapped lines in the first place. 

This has the benefit of the default having the fixed search behavior, rather than what I had written which was opt in.

No need to re-open this.

**Comment by vtk9** [comment]
@MeanderingProgrammer Got it. Thank you for the update!
