### ISSUE TITLE
macos tmux super slow to start

### ISSUE THREAD

**Issue by fawaf** [tmux/tmux#3947]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

from inside tmux:
```shell
% uname -sp && tmux -V && echo $TERM
Darwin arm
tmux 3.4
screen-256color
```

from outside tmux:
```shell
% uname -sp && tmux -V && echo $TERM
Darwin arm
tmux 3.4
xterm-256color
```

tmux started to start incredibly slowly after updating to macos 14.4 iirc. i have started it with and without any tmux config as well as with and without any zsh configs. they all start super slow. without tmux (or screen), the terminal starts fine.

logs attached below.
[tmux-client-43758.log](https://github.com/tmux/tmux/files/15016420/tmux-client-43758.log)
[tmux-out-43760.log](https://github.com/tmux/tmux/files/15016421/tmux-out-43760.log)
[tmux-server-43760.log](https://github.com/tmux/tmux/files/15016422/tmux-server-43760.log)

**Comment by awalker4** [comment]
I'm seeing something similar on macos 14.2.1. Disabled all config, and a new shell is taking 5-10 seconds to load. What's interesting is that as it's loading, all other terminal windows are blocked as well.
[tmux-client-6958.log](https://github.com/tmux/tmux/files/15026466/tmux-client-6958.log)
[tmux-out-6960.log](https://github.com/tmux/tmux/files/15026467/tmux-out-6960.log)
[tmux-server-6960.log](https://github.com/tmux/tmux/files/15026468/tmux-server-6960.log)

**Comment by fawaf** [comment]
> What's interesting is that as it's loading, all other terminal windows are blocked as well.

+1 as well to the blocking of all other terminals

**Comment by lwickline** [comment]
+1 3.4 is taking upwards of a minute to open and/or open a window. It blocks on new windows opening. only happens in tmux.. also tested on screen and zellij to make sure it wasn't zsh.

**Comment by lwickline** [comment]
compiled 3.3a and the issue was there. 
set the default shell in tmux to bash and no issue
removed my .zshrc and restarted tmux still took 20 seconds to open 
thee is something with tmux and zsh going on 
zsh 5.9 (x86_64-apple-darwin21.3.0)

**Comment by lwickline** [comment]
more testing. https://www.reddit.com/r/zsh/comments/1bqtb7m/zsh_login_shell_slow_20s_but_not_when_invoked/ led me to think it may be a path issue.
cleaned up 10 years of bad paths and killed all the tmux processes and the issue cleared up for me.

**Comment by veryhappythings** [comment]
I had the same issue and the problem turned out to be that I had mentions of `/home` in my path from my linux days. This is a symlink to a directory that macOS treats as a network share, and for some reason that seems to cause issues particularly when running path_helper (referenced in /etc/zprofile) and `brew shellenv`, which zsh runs as it spins up. Crucially this only happens if this is the $PATH of the shell that initially runs tmux, which is why your first login shells work fine, but then tmux ends up slow.

**Comment by fawaf** [comment]
yep, seems like it was a path issue that made it SUPER slow. kind of crazy how it did that.
