### ISSUE TITLE
There is a memory leak defect on line 179 of /tmux/arguments.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [tmux/tmux#3949]
Dear developers of the tmux project,

Hello! I have discovered a memory leak defect in the latest version of tmux. The defect is located on line 179 of the file /tmux/arguments.c. The specific path to the defect is as follows:

1.In /tmux/arguments.c, on line 151, a pointer variable named 'new' is defined. This variable allocates a new dynamic memory area through the function xcalloc on line 154. When the 'if' statement on line 170 returns true and the 'if' statement on line 171 returns false, the program will return on line 179. During this process, the dynamic memory area pointed to by 'new' is not freed like it is on line 175, thus causing a memory leak defect, as illustrated in the following diagram:
https://github.com/LuMingYinDetect/tmux_defects/blob/main/tmux_5.png

**Comment by nicm** [comment]
Should be fixed in OpenBSD now, will be in GitHub later. Thanks!
