### ISSUE TITLE
Can't compile tmux 2.2

### ISSUE THREAD

**Issue by xapple** [tmux/tmux#395]
I tired to get the newest version, and executed the following script for installation:

    #!/bin/bash
    # Exit on error #
    set -e

    # Variable version #
    TMUX_VERSION=2.2

    # Create our directories #
    mkdir -p ~/test
    mkdir -p ~/programs/tmux
    mkdir -p ~/programs/libevent

    # It depends on libevent #
    cd ~/test
    wget https://github.com/downloads/libevent/libevent/libevent-2.0.19-stable.tar.gz
    tar xvzf libevent-2.0.19-stable.tar.gz
    cd libevent-*/
    ./configure --prefix=$HOME/programs/libevent --disable-shared
    make
    make install

    # Tmux #
    cd ~/test
    wget -O tmux-${TMUX_VERSION}.tar.gz https://github.com/tmux/tmux/releases/download/${TMUX_VERSION}/tmux-${TMUX_VERSION}.tar.gz
    tar xvzf tmux-${TMUX_VERSION}.tar.gz
    cd tmux-${TMUX_VERSION}

    # Build #
    ./configure --prefix=$HOME/programs/tmux CFLAGS="-I$HOME/programs/libevent/include" LDFLAGS="-static -L$HOME/programs/libevent/lib"
    CPPFLAGS="-I$HOME/programs/libevent/include" LDFLAGS="-static -L$HOME/programs/libevent/include" make

But this resulted in the following error message:

    In file included from /usr/include/string.h:637:0,
                     from arguments.c:22:
    compat.h:203:8: error: expected identifier or ‘(’ before ‘__extension__’
     char  *strsep(char **, const char *);
            ^
    compat.h:203:8: error: expected identifier or ‘(’ before ‘)’ token
     char  *strsep(char **, const char *);
            ^
    make: *** [arguments.o] Error 1

If anyone sees this issue and could point me in the direction of a precompiled static binary that I could just use, that would be very nice.

**Comment by nicm** [comment]
This is wrong. You need to configure tmux with --enable-static to do a static build.

**Comment by xapple** [comment]
Well I added the `--enable-static` parameter to the `./configure` command, but the error is still the same ? I forgot to specify, the error is generated at the final `make` step.

**Comment by nicm** [comment]
Tell me the platform and show me the full configure and build output and the config.log then please.

**Comment by xapple** [comment]
OK ! Here is all the information I have:

    xapple@uni_cluster ~ $ cat /etc/issue
    Red Hat Enterprise Linux Server release 6.7 (Santiago)
    Kernel \r on an \m

    xapple@uni_cluster ~ $ uname -a
    Linux taito-login4.csc.fi 2.6.32-573.12.1.el6.x86_64 #1 SMP Mon Nov 23 12:55:32 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

I put the output of the script in a gist:
https://gist.github.com/xapple/c5de42137853c8319081da2adebd0384

And the `config.log` is here:
https://gist.github.com/xapple/bc714127d035faab48184707264dc297

**Comment by nicm** [comment]
So I think the problem is that you are missing ncurses libraries for static linking.

configure is detecting ncurses.h but then the test programs for strsep() and other functions are failing because of missing libncurses and libtinfo (RHEL6.7 will definitely have strsep):

configure:5950: checking for strsep
configure:5950: gcc -o conftest -I/homeappl/home/lsinclai/homes/taito/programs/libevent/include    -static -L/homeappl/home/lsinclai/homes/taito/programs/libevent/lib -static conftest.c -lncurses -ltinfo   -levent -lrt  -lresolv >&5
/appl/opt/binutils/2.25/bin/ld: cannot find -lncurses
/appl/opt/binutils/2.25/bin/ld: cannot find -ltinfo

This makes tmux try to use a compatibility strsep() implementation which gets tangled up with the system strsep() (probably a macro) and makes the build fail.

It seems inconceivable that you would not have ncurses-libs installed because lots of stuff depends on it, so probably it does not include static libraries. And checking on a CentOS 6.5 installation, it does in indeed look at ncurses-libs does not include any .a files.

If a ncurses-static or ncurses-devel-static package exists on RHEL (I don't seem to have it on CentOS) you might try installing it (or asking the admin to install it). Otherwise you will need to do a dynamic build, or build your own static ncurses, or build a static tmux on a different box that has the correct libraries and copy it over.

**Comment by xapple** [comment]
OK, well that definitely makes things a bit more clear as to what is happening. Could never have guessed it had to do with `ncurses`.

Yeah I tried to make the static tmux on a other box and copy it over. I used Ubuntu 14.04 but I just ended up with this when I executed it on the university cluster:

    xapple@uni_cluster test $ ./tmux -V
    ./tmux: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./tmux)
    ./tmux: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./tmux)
    ./tmux: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./tmux)

So I did it all again and made a virtual machine with Ubuntu 10.10 because that's the one that had the right version of libc6... but it wasn't supported anymore and none of the `apt-get` would work...

Compilation is something that interests system admins and developers. I think you should just distribute static binaries for users that want to use tmux. It's such a waste of time for everyone to do this.

But ok, here is a new script that includes the installation of ncurses:

    #!/bin/bash
    # Exit on error #
    set -e

    # Clean up #
    rm -rf ~/programs/libevent
    rm -rf ~/programs/ncurses
    rm -rf ~/programs/tmux

    # Variable version #
    TMUX_VERSION=2.2

    # Create our directories #
    mkdir -p ~/test
    mkdir -p ~/programs/libevent
    mkdir -p ~/programs/ncurses
    mkdir -p ~/programs/tmux

    ############
    # libevent #
    ############
    cd ~/test
    wget https://github.com/downloads/libevent/libevent/libevent-2.0.19-stable.tar.gz
    tar xvzf libevent-2.0.19-stable.tar.gz
    cd libevent-*/
    ./configure --prefix=$HOME/programs/libevent --disable-shared
    make
    make install

    ############
    # ncurses  #
    ############
    cd ~/test
    wget ftp://ftp.gnu.org/gnu/ncurses/ncurses-5.9.tar.gz
    tar xvzf ncurses-5.9.tar.gz
    cd ncurses-5.9
    ./configure --prefix=$HOME/programs/ncurses LDFLAGS="-static"
    make
    make install

    ############
    # tmux     #
    ############
    cd ~/test
    wget -O tmux-${TMUX_VERSION}.tar.gz https://github.com/tmux/tmux/releases/download/${TMUX_VERSION}/tmux-${TMUX_VERSION}.tar.gz
    tar xvzf tmux-${TMUX_VERSION}.tar.gz
    cd tmux-${TMUX_VERSION}

    # Build #
    ./configure --prefix=$HOME/programs/tmux --enable-static CFLAGS="-I$HOME/programs/libevent/include -I$HOME/programs/ncurses/include" LDFLAGS="-static -L$HOME/programs/libevent/lib -L$HOME/programs/ncurses/lib"
    CPPFLAGS="-I$HOME/programs/libevent/include -I$HOME/programs/ncurses/include" LDFLAGS="-static -L$HOME/programs/libevent/lib -L$HOME/programs/ncurses/lib" make

Still gives the same error... What am I doing wrong ?

**Comment by nicm** [comment]
Is there a libncurses.a in your ncurses directory?

I am not going to make static builds of tmux.

**Comment by nicm** [comment]
ncurses lib directory that is.

**Comment by xapple** [comment]
Yes this the content:

    xapple@uni_cluster ~ $ ls ~/programs/ncurses/lib/
    ada    libform_g.a  libmenu_g.a   libncurses++.a  libpanel.a    terminfo
    libform.a  libmenu.a    libncurses.a  libncurses_g.a  libpanel_g.a

But I see something else: seems like it should be `$HOME/programs/ncurses/include/ncurses` for the include. For some reason, it creates a sub-directory. So this time I include everything possible everywhere:

    ./configure --prefix=$HOME/programs/tmux --enable-static CFLAGS="-I$HOME/programs/libevent/include -I$HOME/programs/ncurses/include/ncurses" LDFLAGS="-static -L$HOME/programs/libevent/lib -L$HOME/programs/libevent/include -L$HOME/programs/ncurses/lib -L$HOME/programs/ncurses/include/ncurses"
     CPPFLAGS="-I$HOME/programs/libevent/include -I$HOME/programs/ncurses/include/ncurses" LDFLAGS="-static -L$HOME/programs/libevent/lib -L$HOME/programs/libevent/include -L$HOME/programs/ncurses/lib -L$HOME/programs/ncurses/include/ncurses" make


Still the same error.

**Comment by nicm** [comment]
Show me config.log.

**Comment by xapple** [comment]
https://gist.github.com/xapple/e9ccd8438c5b57692dee9838e3a99dea

**Comment by nicm** [comment]
It is still looking for libtinfo probably it is getting it from
pkg-config, try setting PKG_CONFIG to nothing:

PKG_CONFIG= ./configure

**Comment by xapple** [comment]
Still not apparently:

https://gist.github.com/xapple/5c27acd9d2e60e177dd91dee11e5c9b9

**Comment by nicm** [comment]
What does the script look like now? It is still trying
pkg-config. PKG_CONFIG= works for me, maybe try PKG_CONFIG=/bin/false
instead.

**Comment by xapple** [comment]
Ahh I see ! Perfect ! Thanks a lot ! I was able to download it !
Just a strange thing that didn't happen with the other version:

    xapple@login4 ~ $ export LANGUAGE="en_US.UTF-8"
    xapple@login4 ~ $ export LANG="en_US.UTF-8"
    xapple@login4 ~ $ export LC_ALL="en_US.UTF-8"
    xapple@login4 ~ $ export LC_CTYPE="en_US.UTF-8"
    xapple@login4 ~ $ export CTYPE="en_US.UTF-8"
    xapple@login4 ~ $ tmux -V
    tmux: need UTF-8 locale (LC_CTYPE) but have ASCII
    tmux 2.2

But I should probably open a ticket at the developer's repository for that I suppose.

**Comment by xapple** [comment]
Sorry I posted to the wrong thread ^^

**Comment by xapple** [comment]
OK I put `bin/false` like this:

     PKG_CONFIG=/bin/false ./configure --prefix=$HOME/programs/tmux --enable-static CFLAGS="-I$HOME/programs/libevent/include -I$HOME/programs/ncurses/include/ncurses" LDFLAGS="-static -L$HOME/programs/libevent/lib -L$HOME/programs/libevent/include -L$HOME/programs/ncurses/lib -L$HOME/programs/ncurses/include/ncurses"
    CPPFLAGS="-I$HOME/programs/libevent/include -I$HOME/programs/ncurses/include/ncurses" LDFLAGS="-static -L$HOME/programs/libevent/lib -L$HOME/programs/libevent/include -L$HOME/programs/ncurses/lib -L$HOME/programs/ncurses/include/ncurses" make

The log: https://gist.github.com/xapple/2614416ab867a922189a223a8f51c812

**Comment by nicm** [comment]
Weird; try putting it with the other environment variables at the end of
configure instead of before configure.

**Comment by xapple** [comment]
./configure --prefix=$HOME/programs/tmux --enable-static CFLAGS="-I$HOME/programs/libevent/include -I$HOME/programs/ncurses/include/ncurses" LDFLAGS="-static -L$HOME/programs/libevent/lib -L$HOME/programs/libevent/include -L$HOME/programs/ncurses/lib -L$HOME/programs/ncurses/include/ncurses" PKG_CONFIG=/bin/false
    CPPFLAGS="-I$HOME/programs/libevent/include -I$HOME/programs/ncurses/include/ncurses" LDFLAGS="-static -L$HOME/programs/libevent/lib -L$HOME/programs/libevent/include -L$HOME/programs/ncurses/lib -L$HOME/programs/ncurses/include/ncurses" make

Still not : /
https://gist.github.com/xapple/06c7916b47ed6a87171d837b75633363

**Comment by nicm** [comment]
Oh because we override it for --enable-static.

Your best bet is to open configure and find the line that says:

        PKG_CONFIG="pkg-config --static"

And comment it out:

        #PKG_CONFIG="pkg-config --static"

**Comment by xapple** [comment]
Hah !
It worked !
Seems like I have a working tmux 2.2 binary  🎉🎉🎉

But yeah, my usual word of caution about "if the standard user of your product has to start modifying the configure file, you might want to reconsider the distribution method".

Thanks for the help !

**Comment by nicm** [comment]
Well, the PKG_CONFIG thing was an error in the configure.ac file for
static builds. But you are not the standard user.

**Comment by xapple** [comment]
Ah so I helped you find a bug on your side. That's cool. Might be useful for others then !

I don't represent the standard user ? My case is pretty simple, there is this university cluster I am supposed to work on, and I don't like using screen so much. RedHat is also pretty standard for such linux boxes. So I want to get the latest version of tmux on it. How do I do it ?

**Comment by nicm** [comment]
On Thu, May 05, 2016 at 07:27:52AM -0700, Lucas Sinclair wrote:
>    Ah so I helped you find a bug on your side. That's cool. Might be useful
>    for others then !
> 
>    I don't represent the standard user ? My case is pretty simple, there is
>    this university cluster I am supposed to work on, and I don't like using
>    screen so much. RedHat is also pretty standard for such linux boxes. So I
>    want to get the latest version of tmux on it. How do I do it ?

Simple perhaps but it is not typical. Most users do not build tmux
manually at all (they use packages) and most who do, have root, or do
not do a static build, or can fix any problems, or some combination of
the above.

I don't particularly mind helping you to build tmux, but you are not the
typical user and the problems you are having are not the common ones.

**Comment by xapple** [comment]
OK well I guess you certainly have a better view of what the users of tmux are then me !

But I know that there are thousands such clusters around the world, and not only in universities, designed for remote work, and each of them have hundreds of users. And **no one** is root. It would appear to me lots of people would want tmux without having super user privileges.

**Comment by nicm** [comment]
Honestly yes you would think so but I don't seem to get many issues like
this, or at least not so many that I have noticed it particularly. So
either there are not so many people doing this or they are getting help
somewhere else.

**Comment by dbabits** [comment]
@nicm, I'm facing the same issue. I need to statically link tmux because the machine where I'm going to run it does not have the same version of glibc as the machine where I'm building it.
I went through the thread, but am still not clear what I should edit.
The script is this: https://github.com/dbabits/tmux_local_install/blob/master/tmux_local_install.sh

Appreciate your help.

**Comment by NickeZ** [comment]
I'm having a similar issue trying to compile statically on a machine where I'm not root. Tried everything above, even modifying `configure`

Here is the output of `make`:

```
$ make
depbase=`echo compat/asprintf.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        gcc -std=gnu99 -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"2.6\" -DPACKAGE_STRING=\"tmux\ 2.6\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"2.6\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_NCURSES_H=1 -DHAVE_PR_SET_NAME=1 -DHAVE_PROC_PID=1 -I.  -DTMUX_CONF="\"/etc/tmux.conf\""  -iquote.      -I/afs/psi.ch/user/c/claesson_n/.local/include/ncurses  -I/afs/psi.ch/user/c/claesson_n/.local/include  -std=gnu99 -O2    -MT compat/asprintf.o -MD -MP -MF $depbase.Tpo -c -o compat/asprintf.o compat/asprintf.c &&\
        mv -f $depbase.Tpo $depbase.Po
In file included from compat/asprintf.c:23:
./compat.h:236: error: expected identifier or ‘(’ before ‘__extension__’
./compat.h:236: error: expected identifier or ‘(’ before ‘)’ token
./compat.h:261: error: expected identifier or ‘(’ before ‘__extension__’
compat/asprintf.c: In function ‘vasprintf’:
compat/asprintf.c:49: warning: implicit declaration of function ‘xmalloc’
compat/asprintf.c:49: warning: assignment makes pointer from integer without a cast
compat/asprintf.c:51: warning: implicit declaration of function ‘free’
compat/asprintf.c:51: warning: incompatible implicit declaration of built-in function ‘free’
make: *** [compat/asprintf.o] Error 1
```

Here is my `configure` command:

```
./configure LIBEVENT_CFLAGS=-I$HOME/.local/include LIBEVENT_LIBS=-L$HOME/.local/lib LIBNCURSES_CFLAGS=-I$HOME/.local/include/ncurses LIBNCURSES_LIBS=-L$HOME/.local/lib --enable-static --prefix=$HOME/.local
```

Versions I've downloaded are:
* libevent-2.1.8-stable.tar.gz
* ncurses-6.0-20180121.tgz
* tmux-2.6.tar.gz

**Comment by thinki** [comment]
> Oh because we override it for --enable-static.
> 
> Your best bet is to open configure and find the line that says:
> 
> ```
>     PKG_CONFIG="pkg-config --static"
> ```
> And comment it out:
> 
> ```
>     #PKG_CONFIG="pkg-config --static"
> ```
> On Thu, May 05, 2016 at 07:10:47AM -0700, Lucas Sinclair wrote:
> 
> > ./configure --prefix=$HOME/programs/tmux --enable-static CFLAGS="-I$HOME/programs/libevent/include -I$HOME/programs/ncurses/include/ncurses" LDFLAGS="-static -L$HOME/programs/libevent/lib -L$HOME/programs/libevent/include -L$HOME/programs/ncurses/lib -L$HOME/programs/ncurses/include/ncurses" PKG_CONFIG=/bin/false
> > CPPFLAGS="-I$HOME/programs/libevent/include -I$HOME/programs/ncurses/include/ncurses" LDFLAGS="-static -L$HOME/programs/libevent/lib -L$HOME/programs/libevent/include -L$HOME/programs/ncurses/lib -L$HOME/programs/ncurses/include/ncurses" make
> > Still not : /
> > [1]https://gist.github.com/xapple/06c7916b47ed6a87171d837b75633363
> > --
> > You are receiving this because you commented.
> > Reply to this email directly or [2]view it on GitHub
> > Reverse link: [3]unknown
> > References
> > Visible links
> > 
> > 1. https://gist.github.com/xapple/06c7916b47ed6a87171d837b75633363
> > 2. [#395 (comment)](https://github.com/tmux/tmux/issues/395#issuecomment-217164628)
> > 3. [#395 (comment)](https://github.com/tmux/tmux/issues/395#issuecomment-217164628)

I meet the same problems on centos. This also solve my problems. Thanks!
