### ISSUE TITLE
There is a memory leak defect on line 95 of /tmux/cmd-confirm-before.c file.

### ISSUE THREAD

**Issue by LuMingYinDetect** [tmux/tmux#3950]
Dear developers of the tmux project,

Hello! I have discovered a memory leak defect in the latest version of tmux. The defect is located on line 95 of the file /tmux/cmd-confirm-before.c. The specific path to the defect is as follows:

1.In /tmux/cmd-confirm-before.c, on line 70, a pointer variable named 'cdata' is defined. This variable allocates a new dynamic memory area through the function xcalloc on line 77. When the program takes the 'else' branch on line 93, it will return on line 95. During this process, the dynamic memory area pointed to by 'cdata' is neither freed like it is on line 80 nor used like it is on line 109, thus causing a memory leak defect, as illustrated in the following diagram:
https://github.com/LuMingYinDetect/tmux_defects/blob/main/tmux_6.png

**Comment by nicm** [comment]
Fixed in OpenBSD now, will be in GitHub later. Thanks!
