### ISSUE TITLE
There is a memory leak defect on line 1020 of /tmux/status.c file.

### ISSUE THREAD

**Issue by LuMingYinDetect** [tmux/tmux#3951]
Dear developers of the tmux project,

Hello! I have discovered a memory leak defect in the latest version of tmux. The defect is located on line 1020 of the file /tmux/status.c. The specific path to the defect is as follows:

1.In /tmux/status.c, on line 986, pointer variables named 'ud' and 'udp' are defined. The program allocates a new dynamic memory area for pointer 'ud' using the function xreallocarray on line 997 (although it's a realloc function, passing NULL as the original pointer effectively acts like an alloc function). Then, on line 998, the pointer 'ud' is assigned to pointer 'udp'. When the 'if' statement on line 1019 evaluates to true (meaning 'udp - ud == 0'), the program returns on line 1020. During this process, the dynamic memory area pointed to by 'ud' is neither used nor freed, thus causing a memory leak defect, as illustrated in the following diagram:
https://github.com/LuMingYinDetect/tmux_defects/blob/main/tmux_7.png

**Comment by nicm** [comment]
Fixed in OpenBSD now, will be in GitHub later. Thanks!
