### ISSUE TITLE
There is a memory leak defect on line 1842 of /tmux/status.c file.

### ISSUE THREAD

**Issue by LuMingYinDetect** [tmux/tmux#3952]
Dear developers of the tmux project,

Hello! I have discovered a memory leak defect in the latest version of tmux. The defect is located on line 1842 of the file /tmux/status.c. The specific path to the defect is as follows:

1.In /tmux/status.c, on line 1793, a pointer variable named 'spm' is defined. This variable allocates a new dynamic memory area using the function xmalloc on line 1802. When the 'if' statement on line 1840 evaluates to true, the program returns on line 1841. During this process, the dynamic memory area pointed to by 'spm' is neither freed nor used like it is on line 1874, thus causing a memory leak defect, as illustrated in the following diagram:
https://github.com/LuMingYinDetect/tmux_defects/blob/main/tmux_8.png

**Comment by nicm** [comment]
Fixed in OpenBSD now, will be in GitHub later. Thanks!
