### ISSUE TITLE
Unable to create new-window with multiple options

### ISSUE THREAD

**Issue by manangulati9** [tmux/tmux#3954]
Hi, I'm new to tmux so kindly bear with me.

I'm trying to setup my dev environment and for that I need to programmatically create a new window.  
This is the command I'm using. I don't know what I'm doing wrong - 

`tmux new-window -ad -c "~/path-to-project" -n "Server" "npm run dev"`

Shell - bash

I'm assuming there's some issues with parsing of this command by the shell. I RTFM but it doesn't provide examples so it's a bit confusing. Would appreciate the help.

**Comment by nicm** [comment]
What happens? Is the window immediately closing?

If you replace your npm command with "sleep 1000" does it work? If so then npm is probably exiting so tmux closes the window. Try making it "npm run dev; sleep 1000" so you can see any error.

**Comment by manangulati9** [comment]
> What happens? Is the window immediately closing?
> 
> If you replace your npm command with "sleep 1000" does it work? If so then npm is probably exiting so tmux closes the window. Try making it "npm run dev; sleep 1000" so you can see any error.

I don't get any output. Nothing happens and no errors are thrown by command.

**Comment by manangulati9** [comment]
Nevermind, I got it working by removing the quotes around the path.

`tmux new-window -ad -c ~/path-to-project -n "Server" "npm run dev;sleep 1000"`

This command works. Weird that it wouldn't parse the path in quotes. Any reason why?

**Comment by kenlau46** [comment]
The shell does not expand `~` when it is quoted.

You can try `$ ls ~` vs `$ ls "~"`, the quoted version will prompt file not found error, indicating `~` is not expanded to you home directory path.

**Comment by manangulati9** [comment]
Thanks for your help @kenlau46 and @nicm ! Appreciate it.
