### ISSUE TITLE
[Bug] TMUX crashes on Alpine Linux / musl when running `showkey`

### ISSUE THREAD

**Issue by rsmirnov90** [tmux/tmux#3955]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

**Brand new minimal Alpine Linux install (musl, OpenRC, Intel x64 (gen 10)), and fresh tmux install (no config files anywhere -- not for user and not on system). 

Tried rebooting: clean boot, log in as root, execute `tmux`, execute `showkey`, TMUX fully crashes with "[server exited unexpectedly]". 

Did a quick log of `showkey > logfile`, and showkey picked up the Enter key being released right before the crash.

Keyboard is sometimes left in an inconsistent state after the crash, and showkey is still running in the background (have to wait the 10 seconds before I hit ctrl+c and reset the terminal).

Not sure where else to look.**

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

**tmux next-3.4**

* Platform (`uname -sp`).

**Linux unknown**

* $TERM inside and outside of tmux (`echo $TERM`).

**linux**

* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
No logs.
