### ISSUE TITLE
Command to force update-environment?

### ISSUE THREAD

**Issue by rhelmot** [tmux/tmux#3957]
### Issue description

I am trying to script tmux to run update-environment on client-focus-in instead of just on client-attach. I can't seem to find any way to force an update-environment. If there's a command I'm missing or an easier way to achieve my desires, I would love to hear it :)

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `tmux 3.3a`
* Platform (`uname -sp`). `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`). `tmux-256color` and `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`). `don't particularly think this is relevant`

**Comment by nicm** [comment]
What is the need for this? How are you managing to change the environment in the client process without detaching it?

Or are you changing `update-environment`? If so, why not just set them directly with `tmux set-environment`?

**Comment by nicm** [comment]
You want the enviroment to go back to what it was before the new client attached?

**Comment by rhelmot** [comment]
Yes. Detaching the original client and reattaching it works but I'd like to not have to do that.

**Comment by nicm** [comment]
What if you do `C-b : attach` does it update?

**Comment by rhelmot** [comment]
Yes, that works perfectly, even from a script! The docs seem to mention offhandedly that this is a side effect, but I didn't see it. Thank you!
