### ISSUE TITLE
Some Images Files are not displayed when converted to Sixels

### ISSUE THREAD

**Issue by stephenprater** [tmux/tmux#3959]
### Issue description

Some images are not displayed as SIXELs

Certain images (I have not found a pattern) do not display as Sixels in tmux.  They do displays via the same command in the underlying terminal (ITerm2) 

<img width="1000" alt="Screenshot 2024-04-26 at 12 09 09 PM" src="https://github.com/tmux/tmux/assets/149870/d7cdaa50-5780-410d-9a64-cf1b82d079cb">

(The left here is in tmux, while the right is in a regular ITerm2 split pane.)

Here is the difference in `identify -verbose` for both images.

https://gist.github.com/stephenprater/e106a99970a11455f5991e653412d2f0

Weirdly - converting the `bamboo_bridge.png` image to JPG still does not seem to make it display.

### Required information

Please provide the following information:

* tmux version (`tmux next-3.5`).
* Platform (`Darwin arm`).
* $TERM inside and outside of tmux (`xterm-256color (in both instances)`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-45850.log](https://github.com/tmux/tmux/files/15135662/tmux-client-45850.log)
[tmux-out-45852.log](https://github.com/tmux/tmux/files/15135663/tmux-out-45852.log)

The server log is _2.6G_?  It won't let me upload that.

**Comment by nicm** [comment]
Are we meant to transfer the problem images from your computer telepathically? :-)

Try compressing the server log.

**Comment by stephenprater** [comment]
Oh duh.  🤦 Welp - I'm a dumbass.  This is from a different run - but same images, same setup.

[tmux-server-62079.log.tgz](https://github.com/tmux/tmux/files/15169568/tmux-server-62079.log.tgz)
[tmux-client-62077.log](https://github.com/tmux/tmux/files/15169569/tmux-client-62077.log)
[tmux-out-62079.log](https://github.com/tmux/tmux/files/15169570/tmux-out-62079.log)

**Comment by nicm** [comment]
Attach the image files too please.

**Comment by stephenprater** [comment]
[suicidal_despair.sixel.tgz](https://github.com/tmux/tmux/files/15170999/suicidal_despair.sixel.tgz)
[bamboo.sixel.tgz](https://github.com/tmux/tmux/files/15171000/bamboo.sixel.tgz)

**Comment by jayjwa** [comment]
There's probably a size limit. "bamboo" is a large file. Xterm does this as well. Foot, and evidently your ITerm2 allow large files.
` convert -resize 50% bamboo.sixel bamboo-sm.sixel`

...and _that_  image will display (foot/tmux, TERM=sixel-tmux, Slackware x86_64).

**Comment by stephenprater** [comment]
Hmm - it's got to be the size of the uncompressed sixel.  Seems like I can display an image up to 1M.

[bamboo_sm.sixel.tgz](https://github.com/tmux/tmux/files/15227082/bamboo_sm.sixel.tgz)

**Comment by nicm** [comment]
Yes, the input buffer size is 1 MB so that is the largest image you will be able to use.

**Comment by nicm** [comment]
Yes, from the logs the files are too big:
~~~~
1714503067.280432 input_dcs_dispatch: 1048575 bytes (discard)
~~~~
Unfortunately there is not really any way for us to signal this, that I can think of at least.
