### ISSUE TITLE
copy paste does not work on tmux 3.4 with ncurses 6.5

### ISSUE THREAD

**Issue by cattyhouse** [tmux/tmux#3960]
### Issue description

ncurses 6.5 makes copy and paste with mouse/trackpad NOT working under tmux 3.4, tried iTerm2 with copy to pasteboard with selection and alacritty with save_to_clipboard = true.

there are 2 solution that fix this issue

1. keep tmux 3.4 stable, but downgrade to ncurses 6.4, **problem gone**.
2. install `tmux git` version with ncurses 6.5, **problem gone**.

regarding the 2nd solution, my issue is: **there must be some commit since 3.4 release that fixed that issue, and homebrew devs would like to backport the commit to 3.4**, see [discussion here](https://github.com/Homebrew/homebrew-core/pull/170245) 

### Required information

Please provide the following information:

* tmux version (`tmux -V`). : 3.4
* Platform (`uname -sp`). : Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`). : inside:tmux-256color outside: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`). todo

**Comment by nicm** [comment]
tmux will not find tparm_s if you build it against nurses 6.4 release because it did not exist until 6.4-20230424, so it will use tparm and extension capabilities will not work.

**Comment by nicm** [comment]
I can't tell you what they should do but it seems like common sense to rebuild programs using a new library version.
