### ISSUE TITLE
allow-passthrough no longer working

### ISSUE THREAD

**Issue by hardwarily** [tmux/tmux#3964]
### Issue description

On Fedora, 3.3a-1 was the last version of tmux where allow-passthrough on was working with vim's t_RB setting to request the terminal bg color.

Set up a bare environment:
```
podman run -it --rm fedora:37
dnf install vim tmux
echo 'let &t_RB="\ePtmux;\e\e]11;?\007\e\\"' > ~/.vimrc
echo 'set -g allow-passthrough on' > ~/.tmux.conf
tmux
```

And then run the following inside of vim:
```
echo v:termrbgresp
```

Returns the correct RBG sequence, but moving to fedora:38 (the first broken version is building from commit b202a2f) causes the sequence to stop working, and v:termrbgresp is empty. I have confirmed this also happens building from tmux master.

### Required information

Please provide the following information:

* tmux version (tmux 3.3a).
* Platform (Linux x86_64).
* $TERM inside and outside of tmux (tmux-256color).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by mellery451** [comment]
could this have broken osc52 codes too?..because clipboard updating via mosh + tmux has broken for me...

**Comment by hardwarily** [comment]
@nicm my issue isn't resolved, I've tested it with the default tmux and vim configs and it's still happening in the latest commit of 3.4.

**Comment by nicm** [comment]
You're asking the terminal to send an OSC 11 response, but tmux will process this itself, so it will never be delivered to the pane. You need to have vim send it to tmux (so don't use the passthrough sequence).

**Comment by hardwarily** [comment]
@nicm if I send '\e]11;?\007\e\' instead of '\ePtmux;\e\e]11;?\007\e\\' it does get a response, but when I change the background colors of the terminal, the response stays the same. When I exit tmux, the regular shell correctly returns the updated colors. Does tmux cache the OSC response? Opening a pane also doesn't seem to change the response.

**Comment by hardwarily** [comment]
Yes, if I send printf '\ePtmux;\e\e]11;?\007\e\\' I don't get a response, but it does make printf '\e]11;?\007\e\' start returning the updated response.

**Comment by nicm** [comment]
OK well the best thing is probably to do that for the moment. The best thing would probably be if tmux could send the request to the terminal with the client which background colour it decides to use when it receives one in a pane, but its complicated because it would have to wait before sending its own response.
