### ISSUE TITLE
Tmux copy mode fails under WSL

### ISSUE THREAD

**Issue by mikeymckay** [tmux/tmux#3965]
### Issue description

When I enter copy mode, I press space to start copying but instead nothing is copied and the cursor jumps to the bottom of the screen as if I had pressed the page down key. No text is highlighted or copied. When I enable vi copy mode, it also fails to highlight text using the v command to start copying. In this case nothing on the screen changes after pressing v.

This is using the default tmux configuration on WSL (version 2) using the builtin terminal (also happens when I use terminator in wsl). I have tried various tmux configurations, I have tried changing the keyboard language. I always get the same result.  

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
3.2a

* Platform (`uname -sp`).
Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).
xterm-256color (same for both)

* Logs from tmux
 ([tmux-server-381322.log](https://github.com/tmux/tmux/files/15185806/tmux-server-381322.log)`).

**Comment by nicm** [comment]
Seems like you have got `mode-keys` set to `vi`.

**Comment by mikeymckay** [comment]
As mentioned in the description:
I can't select text using either the standard mode: pressing space to start selection jumps to the bottom of the screen without selecting anything
or using the VI mode: pressing v/V does nothing
I've tried with various configurations, and it works fine for me on Linux.

I expect that Windows/WSL is capturing some keyboard commands and not passing them to tmux. Can you suggest any debugging approaches?
