### ISSUE TITLE
/configure: line 7035: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by svanschalkwyk** [tmux/tmux#3971]
When running ./configure: 

./configure: line 7035: syntax error near unexpected token `newline'
./configure: line 7035: `PKG_CHECK_MODULES('

* tmux version 3.3
* Platform Ubuntu 22.04 under WSL2
* $TERM inside and outside of tmux (`echo $TERM`). xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`). - none as it isn';t building
*

**Comment by clarkwang** [comment]
I'm on Debian and this fixes the issue for me:

```
$ apt install pkg-config    # it will also install "pkgconf".
$ ./autogen.sh
$ ./configure ...
```

**Comment by svanschalkwyk** [comment]
> I'm on Debian and this fixes the issue for me:
> 
> ```
> $ apt install pkg-config    # it will also install "pkgconf".
> $ ./autogen.sh
> $ ./configure ...
> ```

Thanks. Trying this weekend.
