### ISSUE TITLE
Red status bar in nested session in "example_tmux.conf"

### ISSUE THREAD

**Issue by lifecrisis** [tmux/tmux#3974]
Greetings:

In the current `example_tmux.conf` file, we have the snippet just here...

```tmux
# If running inside tmux ($TMUX is set), then change the status line to red
%if #{TMUX}
set -g status-bg red
%endif
```

See this [permalink to the relevant code](https://github.com/tmux/tmux/blob/3823fa2c577d440649a84af660e4d3b0c095d248/example_tmux.conf#L11C1-L14C7).

It seems to me that this is not helpful since `tmux` prompts us to `unset TMUX` in order to force nesting. Deleting the variable means it's not there to be detected in the initialization file, thus our status bar will not turn red.

Apologies in advance if this issue turns out to be nothing. I am still new to tweaking `tmux`, and I was puzzled by this short section in the example configuration file.

Thanks,
lifecrisis

**Comment by nicm** [comment]
That's only if you attach a session inside a session from the same server. Using a different server is fine.

**Comment by lifecrisis** [comment]
> That's only if you attach a session inside a session from the same server. Using a different server is fine.

Ah, I see. This makes sense. I will close this issue directly.

Thanks!

**Comment by lifecrisis** [comment]
Closing...
