### ISSUE TITLE
Wrong keycodes for F11 and F12 when using rxvt-unicode

### ISSUE THREAD

**Issue by janvkn** [tmux/tmux#3977]
### Issue description

When using rxvt-unicode as the terminal, pressing F11 and F12 inside a tmux session generates the keycodes for Shift+F1 and Shift+F2 respectively. This interferes with a number of terminal programs which can't receive the F11 and F12 key being pressed. In a plain xterm the keycodes are produced correctly. Outside of tmux, the keycodes are also produced correctly, which leads me to believe it is an issue with tmux.

To reproduce:

1. Use rxvt-unicode with `TERM=rxvt-unicode-256color` and start a new tmux session.
2. Type ctrl+v followed by F11. Expected keycode = `^[[23~`. Actual keycode produced = `^[[1;2P`. 
3. Type ctrl+v followed by F12.  Expected keycode = `^[[24~`. Actual keycode produced = `^[[1;2Q`. 

As a workaround, putting the following line in `.tmux.conf` resolves the issue
````
set -g terminal-overrides "rxvt-*:kf11=\033[23~:kf12=\033[24~"
````

When running tmux info, it shows kf11 and kf12 as missing:
````
  /usr/local/bin/tmux info |grep -E 'kf11|kf12'
    83: kf11: [missing]
    84: kf12: [missing]
````

The issue seems to have been introduced when going from 3.3a to 3.4. Pressing F11 and F12 works as expected in 3.3a, but in 3.4 as well as in the version on the current master branch the wrong keycodes are produced.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux next-3.5`
* Platform (`uname -sp`): `Linux unknown ` 
* $TERM inside tmux: `screen-256color`
* $TERM outside tmux: `rxvt-unicode-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`). 
[tmux-client-15140.log](https://github.com/tmux/tmux/files/15300781/tmux-client-15140.log)
[tmux-out-15142.log](https://github.com/tmux/tmux/files/15300782/tmux-out-15142.log)
[tmux-server-15142.log](https://github.com/tmux/tmux/files/15300783/tmux-server-15142.log)

**Comment by nicm** [comment]
I just tried rxvt-unicode and when I press S-F1 I get `^[[23~`. F11 generates the same, so it appears it has no unique sequence.

If you want tmux to follow terminfo, meaning you will get F11 instead of S-F1, then you should be able to remove `ignorefkeys` from the `terminal-features` option.

**Comment by janvkn** [comment]
Indeed it seems that rxvt doesn't distinguish between S-F1/S-F2 and F11/F12. It's probably an old hack or workaround for supporting old keyboards where the function keys only went to F10 (for example, the old IBM Model F).

Thanks for the pointer to the `terminal-features` option. If I run the command `tmux show-option terminal-features` on a default installation, I get:
````
terminal-features[0] xterm*:clipboard:ccolour:cstyle:focus:title
terminal-features[1] screen*:title
terminal-features[2] rxvt*:ignorefkeys
````

So it seems that `ignorefkeys` gets set automatically for rxvt* terminals. On 3.3a this option does not get set automatically, which explains the changed behavior on 3.4. Now I have a few questions about that:

First, and I'm sorry if this is a basic question but I couldn't figure it out from the manual, how would I *remove* that option from `terminal-features`? I could only find a way to append options to `terminal-features`, but not to remove any.

Secondly, can I ask why `rxvt*:ignorefkeys` is set by default? It appears to have been added to `options-table.c` in 616bde0. 

As I understand it we can have either S-F1/S-F2 working or F11/F12 working because they send the same codes. To me it makes more sense that the default behavior would be to follow what terminfo specifies, and don't add the `ignorefkeys` override by default. This way rxvt-unicode behaves the same way inside or outside of tmux, which is what I expect most users would want.

So might I suggest not to set `ignorefkeys` by default for rxvt-* terminals?

**Comment by janvkn** [comment]
Yep that works, and solves my immediate problem.

Any thoughts on my suggestion about not setting `ignorefkeys` by default for rxvt* ?

**Comment by nicm** [comment]
I don't think we're going to change the default, presumably whoever first pointed this out preferred it that way, I don't think it makes much difference either way. I also can't remember if there are other issues in the rxvt terminfo entries we are working around...

**Comment by janvkn** [comment]
If I can make some counterpoints:

1. As seen above, it's easier and more straightforward to add/append an option to `terminal-features` than to remove one that's already set. It seems cleaner to me that people who prefer this feature, add it to their `.tmux.conf`.
2. There's the principle of least surprise. One would expect that the function keys in rxvt-unicode behave the same way and send the same keycodes inside tmux as outside of tmux. Having a hard coded override for the behavior of the function keys is more surprising than not having it.

I can't speak to the other workarounds for rxvt's terminfo that you may be doing, but removing `ignorefkeys` should only affect the function keys behavior right?

**Comment by nicm** [comment]
(1) You are the only person to have asked about this in the two years since it was added. We are not changing the default based on one issue when both options will be wrong for someone.
 
(2) You are suggesting we send the same sequences for F11 but different for S-F1 rather than vice versa, I don't see there is any difference, one of them is going to be wrong. Besides, the idea is for tmux to send the same sequences regardless of terminal, not the same as rxvt.

If we did change, I don't think we should remove the `ignorefkeys` default but instead change what tmux expects for the keys in `tty-keys.c`. But I think it is premature to change anything now.

**Comment by janvkn** [comment]
(1) Actually 3.4, the first stable release to include `ignorefkeys` by default for rxvt, was only released in February of this year. People generally don't use the latest git version of tmux, so it's more like I'm the first person to ask about it in 3 months. Also, most non-rolling release distros are still on 3.3a or lower. I only stumbled upon this by accident when investigating why an Arch Linux system had recently started to behave differently than a Debian Bookworm system in this respect.

The venn diagram of people who use a rolling release *and* people who use tmux regularly *and* people who use rxvt-unicode as their main terminal *and* people who have a terminal application that relies on F11 and F12 *and* are motivated enough to report an issue with an upstream developer is probably only me :o)

That said...

(2) No, I think you are mistaken here. If you remove the `ignorefkeys` option, rxvt sends exactly the same F-key sequences inside tmux as it would outside of tmux. So if you remove `ignorefkeys` nothing is wrong/changed in terms of expected rxvt behavior.

I think you are overlooking that rxvt normally doesn't pass through shift+F-key combo sequences. It always remaps a shift+F-key combo to F(x+10). So shift+F1 becomes F11, shift+F2 becomes F12, and so on up to F20. It differs from xterm and derivatives in this respect. As far as I can tell, this is some kind of compatibility feature, presumably so that keyboards with less function keys can still send the same sequences as physical terminals with more function keys. For reference, check the kf sequences in [rxvt-unicode.terminfo](https://github.com/exg/rxvt-unicode/blob/main/doc/etc/rxvt-unicode.terminfo)

Ironically, I found out about this through a 9 year old [post](https://tmux-users.narkive.com/URxZFrcs/rxvt-unicode-s-strange-handling-of-function-keys-with-modifiers) on the tmux-users mailing list.

You may disagree with this design decision by the rxvt developers, and I agree that it is a bit weird, but it is not up to tmux to second guess this and implement a "fix" overriding the behavior, especially so when that fix has the side effect of F11 and F12 not functioning anymore in the default configuration.

So this is why I think `ignorefkeys` should be reverted to being optional again: it changes rxvt's default behavior and is only suitable for people who have a need to send an explicit shift+F-key combo (again, something you normally can't do in rxvt anyway) and who can afford the trade off of losing normal usage of function keys beyond F10.
