### ISSUE TITLE
Sixel not working in nested tmux

### ISSUE THREAD

**Issue by DroidCoil** [tmux/tmux#3978]
Linux unknown (EndeavourOS, Latest Kernel)
tmux 3.4
st-256color (Have tested also with both tmux-256color and screen-256color)

When using sixel inside a nested tmux session it does not render correctly. This mainly becomes an issue when I use tmux to ssh to my server then create a tmux session on the server. I have confirmed this is a nesting issue by trying it on the local machine inside a nested tmux session and I see the same results. 

Example image:
![image](https://github.com/tmux/tmux/assets/168860683/80014037-2fdf-4eb0-82e8-b2966936be21)

**Comment by nicm** [comment]
Are you sure both tmux are built with SIXEL? Are you sure they are detecting SIXEL correctly (check `tmux display -p '#{client_termfeatures}'` includes `sixel`)?
