### ISSUE TITLE
tmux 2.2 with iTerm2 causes spinning wheels

### ISSUE THREAD

**Issue by xapple** [tmux/tmux#398]
I don't know if this interests you, it's probably more an issue of iTerm2.app and is reported also at https://gitlab.com/gnachman/iterm2/issues/4582

But it's also something that didn't happen in tmux 2.1 and has been introduced in tmux 2.2.

All my tmux session tabs are constantly displayed with a "processing animation" (=rendered with a spinner) even though nothing is happening in those terminals, and they are idle. Is tmux refreshing the display all the time even though no output is being generated ?

![tmux](https://cloud.githubusercontent.com/assets/649288/15048028/e018382e-12e7-11e6-8cf4-148889344570.png)

**Comment by xapple** [comment]
This used to happen for instance if your tmux status bar displayed the current time with seconds, but would not happen if no clock was included.

**Comment by nicm** [comment]
tmux is not responsible for this icon.
