### ISSUE TITLE
Starting TMUX in MOSH sessions is showing "server version is too old for client" messages for "tmux ls"

### ISSUE THREAD

**Issue by sumikum7** [tmux/tmux#3981]
### Issue description
I am getting "server version is too old for client" for tmux commands such as `tmux ls` where I have already checked that there are no old sessions from previous tmux which is still running as I have rebooted my server and if I do `tmux choose-session` then I can see session only from my new tmux which I installed.

Please note 
 - If I do **SSH** to the server and start tmux sessions inside that, then I don't see this issue. Whenever I do **MOSH** to the server and start tmux sessions inside that then I do see this issue.
   - I do MOSH in ITERM like this >>> 
     - `mosh --server="/usr/local/bin/mosh-server" VM_SERVER_TO_CONNECT -- sh -c "tmux ls | grep -vq attached && tmux a || tmux new"`
   - SSH from MAC terminal >>> 
     - `ssh VM_SERVER_TO_CONNECT`

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.4
* Platform (`uname -sp`) : Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`) : xterm-color (both inside and outside tmux)
* Logs from tmux (`tmux kill-server; tmux -vv new`). NA(not sure how to collect, pls tell me more on this if required)

Issue screenshots:
 - Mosh session : 
   - ![image](https://github.com/tmux/tmux/assets/8676370/bbe999a9-6c80-4d64-9a61-ea68256df8d3)
 - SSH session : 
   - ![image](https://github.com/tmux/tmux/assets/8676370/53ab84a0-6f49-45fa-8ffb-6763bb8e3d94)

**Comment by sumikum7** [comment]
Ok, on further investigation I seem to Root cause it to one thing. This is maybe because of different version of tmux being selected when this command is run : 
 - `mosh --server="/usr/local/bin/mosh-server" VM_SERVER_TO_CONNECT -- sh -c "tmux ls | grep -vq attached && tmux a || tmux new"`
 - To be precise, this command: `"tmux ls | grep -vq attached && tmux a || tmux new"`
   - My bashrc has the correct path to the tmux I want to select. I have verified this with `which tmux` when the shell is loaded. 
   - How can we make sure it reads bashrc(to know which tmux to select) and then run this command? 
     - I tried giving the exact path of tmux, which helps but would appreciate it if this follows the paths I set in ~/.bashrc
      - I'm not sure, how in ssh it is read and then tmux opens the session but in the case of mosh it is not read!

**Comment by nicm** [comment]
I can't help you with mosh, but you need to make sure you are running the
same tmux version.
