### ISSUE TITLE
Issues with control-F2 and other control based chords on byobu

### ISSUE THREAD

**Issue by scvsoft-cruzfernandez** [tmux/tmux#3985]
### Issue description

After creating a small config file, I've reproduced that on Mac OS X Sonoma (M3), with iTerm2 3.4.23 (mostly normal stuff on that) I can't assign `Control`-`F2` chord key to split horizontally. Also to note, I've already taken out `Control`-`F2` from the Mac OS shortcuts (this test can be reproduced with `Control`-`F3` to ease reproduction). A very similar thing has been reported on stackoverflow, just for reference https://superuser.com/questions/744508/mac-os-x-byobu-vertical-split-using-iterm-tmux-zsh 

`tmux.conf` file:
```
bind-key -n S-F2 display-panes \; split-window -v -c "#{pane_current_path}"
bind-key -n C-F2 display-panes \; split-window -h -c "#{pane_current_path}"
```

`Shift`-`F2` splits panes, but `Control`-`F2` doesn't split the pane.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `3.4`
* Platform (`uname -sp`). `Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`). `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv -f /tmp/tmux.conf`).
[tmux-client-56055.log](https://github.com/tmux/tmux/files/15381218/tmux-client-56055.log)
[tmux-server-56057.log](https://github.com/tmux/tmux/files/15381219/tmux-server-56057.log)
[tmux-out-56057.log](https://github.com/tmux/tmux/files/15381249/tmux-out-56057.log)

**Comment by nicm** [comment]
Why do you have `TERM` set to `linux` if you are running in iTerm2 on macOS? This will not help anything.

I don't see any evidence of you pressing `C-F2` (`\033[1;5Q`) in this log, only `S-F2` (`\033[1;2Q`) so it appears likely it is not making it to tmux. What do you see if you run `cat` *outside tmux* and press `C-F2`?

**Comment by scvsoft-cruzfernandez** [comment]
Thanks for looking at my logs!!
This is what I see if I `cat` outside of tmux (I see same thing inside of tmux, if it matters to you):
<img width="467" alt="image" src="https://github.com/tmux/tmux/assets/155481921/9cd97fa5-1f5c-439e-9379-4e825af85e72">

**Comment by nicm** [comment]
How have you configured your iTerm2? It should send ^[[1;5Q for C-F2. What do you see if you press C-F1 or C-F3?

**Comment by scvsoft-cruzfernandez** [comment]
C-F1:
<img width="398" alt="image" src="https://github.com/tmux/tmux/assets/155481921/1006c635-3a5b-4442-8f1a-bd47ebed1e19">

C-F3:
<img width="409" alt="image" src="https://github.com/tmux/tmux/assets/155481921/cf0b3889-5f6a-4b19-8ca2-29a96703d833">

**Comment by nicm** [comment]
You need to fix your iTerm2 configuration to send the keys it normally sends because tmux will not recognise them until you do. `F1` should be `^[OP` and `C-F1` should be `^[[1;5P`.

**Comment by nicm** [comment]
Have you selected "Terminal.app Compatibility" in your profile (Keys tab)? If so, choose "xterm Defaults" instead:
<img width="1117" alt="Screenshot 2024-05-24 at 14 33 47" src="https://github.com/tmux/tmux/assets/304243/f835d0f7-9906-4394-94c3-cefe8cf6dbec">

**Comment by scvsoft-cruzfernandez** [comment]
That fixed it! Thanks for that!
