### ISSUE TITLE
The "tmux detach" command is ignored when executed in a shell script.

### ISSUE THREAD

**Issue by max4018** [tmux/tmux#3988]
**Environment**: Ubuntu18, Xilinx ZYNQ

**tmux Version**: The tmux version on Ubuntu18 is the latest, and Xilinx ZYNQ uses tmux 2.1. Both encounter the following issue.

**Problem Description:**

- My goal is to automatically change the session status of the previous SSH terminal to "detach" every time I log in via SSH, then "attach" the session in the current terminal. This aims to reduce system resource usage.
- In my shell script, the process is: first modify the "main" session status of other terminals to "detach", then in the current terminal attach the "main" session using tmux attach -t main. The final result is that the attach session connects successfully, but the detach command does not take effect.
- As you can see in Figure 1, the left side is my ~/.bashrc script, and the right side shows multiple new terminals. They all successfully execute the tmux attach command but ignore the tmux detach command.
- This issue only appears in the shell script. If I manually execute tmux send -t main "tmux detach -a" C-m ; tmux send -t main "tmux detach" C-m ; tmux attach -t main, it works perfectly and meets my needs.

**Reproduction Method:**
- Add my complete script below to /etc/profile or ~/.bashrc, then create a new SSH or terminal connection, or you can also create a new shell file and add the script. Both can reproduce the issue.

```shell
# 判断 main_session 会话是否存在
tmuxls=$(tmux ls | grep main_session | grep -v grep)
if [ -n "$tmuxls" ]; then
	tmux send -t main_session "#main_session, already running" C-m
	tmux attach -t main_session
	tmux send -t main_session "tmux detach -a" C-m
	tmux send -t main_session "tmux detach" C-m
	tmux attach -t main_session
else
	echo "#main_session, no running"
	# 启动新的tmux会话，但不立即连接
	tmux new -d -s main_session
	tmux send -t main_session "echo TMUX1 = \$TMUX " C-m
	
	# 鼠标滚轮支持
	tmux send -t main_session "tmux set -g mouse on" C-m
	tmux send -t main_session "tmux set -g history-limit 10000" C-m
fi
```

**Comment by max4018** [comment]
![微信图片_20240524180507](https://github.com/tmux/tmux/assets/51016928/f1817892-afe3-46fb-9f88-1fd81a049d01)

**Comment by nicm** [comment]
Are you sure you are detaching the right session? Does `detach -a` detach it?
