### ISSUE TITLE
Question:  Should display-popup ignore keybindings?

### ISSUE THREAD

**Issue by Jimmyscene** [tmux/tmux#3990]
### Issue description

Hi,

I can provide a more detailed breakdown if this isn't intended, but before doing so I wanted to understand whether or not this is intended.

When opening up a popup with `:display-popup`, a floating pane is opened in the center of the screen. Once this is open, all keybindings seem to be ignored, e.g. `prefix+:` no longer takes you back to the status bar, etc. It seems that the only way to give control back to the client which opened the popup is to close the popup.

Is this expected? 

### Required information

Please provide the following information:

* tmux version: built from master
* Tested on both linux and macos

**Comment by nicm** [comment]
Yes this is correct.
