### ISSUE TITLE
`pane-focus-out/in` events not fired when popup opened/closed

### ISSUE THREAD

**Issue by loichyan** [tmux/tmux#3991]
### Issue description

Reproduce step:

```sh
# tmux -Ltest -f/dev/null
tmux set -g focus-events on
tmux set-hook -g pane-focus-in 'display -F "IN #(date)"'
tmux set-hook -g pane-focus-out 'display -F "OUT #(date)"'
tmux popup -E
```

The focus events on the current pane are not fired when a popup is opened or closed. I found a potentially related issue (#2903) where the discussion noted that:

> Popups are not panes and do not fire focus hooks.

However, shouldn't the focus events be fired on the current pane from which a popup is opened and to which it returns after closing?

### Required information

* tmux version: 3.4 (installed from nixpkgs)
* Platform: Linux unknown (Fedora Silverblue 40)
* $TERM inside tmux: xterm-kitty
* $TERM outside tmux: tmux-256color

I also reproduced on the latest commit (tmux/tmux@c07e856d244d07ab2b65e72328fb9fe20747794b).

**Comment by nicm** [comment]
Yes... does this fix it? [focus.diff.txt](https://github.com/user-attachments/files/17265407/focus.diff.txt)

**Comment by loichyan** [comment]
> Yes... does this fix it? [focus.diff.txt](https://github.com/user-attachments/files/17265407/focus.diff.txt)

Yes! Great thanks!

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
