### ISSUE TITLE
After starting TMUX , terminal commands start executing very slow and each command in the tmux shell takes forever to run even pwd

### ISSUE THREAD

**Issue by neerajbadlani** [tmux/tmux#3993]
[](url)### Issue description

I have tried different versions of tmux from 3.2a to 3.4 , tried starting with no configs . Nothing seems to be helping

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[HEAD:bin] ./tmux -V
tmux 3.2a

[HEAD:bin] uname -sp
Darwin arm

[HEAD:bin] echo $TERM ( Outside ) 
xterm-256color

[tmux-server-78817.log](https://github.com/tmux/tmux/files/15497540/tmux-server-78817.log)
[tmux-out-78817.log](https://github.com/tmux/tmux/files/15497541/tmux-out-78817.log)
[tmux-client-78815.log](https://github.com/tmux/tmux/files/15497542/tmux-client-78815.log)

[HEAD:bin] echo $TERM ( Inside ) 
xterm-256color

Once tmux starts , all the bash commands in other non tmux terminals also slow down a lotttt .

**Comment by nicm** [comment]
Have you got some tmux command in your prompt?

**Comment by neerajbadlani** [comment]
i dont think so ,

**Comment by neerajbadlani** [comment]
how can i check ?

**Comment by nicm** [comment]
Well, I would start without your tmux config first (`tmux kill-server; tmux -f/dev/null new`) and if it still happens maybe try moving or disabling your shell profiles to see if that helps, or make a new user with the default profiles and see if it is the same.

**Comment by neerajbadlani** [comment]
i removed bash-preexec from my system , and that helps a lot . After that i see a different behaviour now 

New Behaviour : 
For shells outside tmux , bash startup to prompt is very fast 
For shells started inside tmux , bash startup to prompt is very slow ( ~10-15 secs ) , but once it reaches prompt , then it works fine similar to shells outside tmux 
Any idea on what to look for ?

**Comment by neerajbadlani** [comment]
tmux popup-window shells startup to prompt is also very fast .. except for new panes and windows

**Comment by neerajbadlani** [comment]
Think found the issue 
When tmux starts , it uses system bash as default , and I think thats slow for some reason . 
Tmux pop up uses the shell i have configured . Any idea why the startup windows and panes dont use the configured shell ? 

<img width="1798" alt="image" src="https://github.com/user-attachments/assets/5a835a6f-e437-4703-a350-86512e85aba1">

**Comment by nicm** [comment]
What is in the default-shell and default-command options after you start tmux?

**Comment by neerajbadlani** [comment]
set-option -g default-shell /opt/homebrew/bin/bash #  Set Default Shell , since MacOS uses different default shell
there is not default-command option

**Comment by nicm** [comment]
Is that what is actually in `default-shell` when you do `tmux show -g default-shell`? What does `echo $SHELL` show in a new pane?

**Comment by neerajbadlani** [comment]
[master:.configfiles] tmux show -g default-shell
default-shell /opt/homebrew/bin/bash
[master:.configfiles] echo $SHELL
/opt/homebrew/bin/bash
[master:.configfiles] echo $0
-bash

**Comment by nicm** [comment]
That looks fine. tmux windows should use that shell unless you have also set `default-command`.
