### ISSUE TITLE
list-panes -F pane_current_path not working as expected with multiple sessions

### ISSUE THREAD

**Issue by tesinclair** [tmux/tmux#3996]
**System 1 from master**:
* tmux version: next-3.5 (master)
* Platform: Linux Rpi (should be ARM but uname -p is unknown)
      - Release Debian 12
* TERM: tmux-256color

![image](https://github.com/tmux/tmux/assets/66572748/c97ad2bc-38bd-4cc1-93ab-849c5a531785)

**
[tmux-logs.zip](https://github.com/user-attachments/files/15526888/tmux-logs.zip)
Summary:**
There seems to be an issue with list-panes specifically with the `-F "#{pane_current_path}"` flag, not working as expected. When creating two (only tried with 2, may work with more) sessions one after another. Then trying to print the first ones pane current path. This will actually print the second ones path (the second one also prints the second one). As seen in the above image.

**Steps to reproduce:**
* Enter tmux session 1
* Navigate to a directory of your choice
* Detach
* Enter tmux session 2
* Navigate to a different directory than session 1
* Detach
* Run `tmux list-panes -t 0 -F "#{pane_current_path}"`

If reproduced successfully, you should see the second session's current path, not the first session's.

**Also works on:**
* tmux version: 3.4
* Platform: Linux (x86-64) 
    - Release: Ubuntu 24.04
* TERM: tmux-256color

**Comment by nicm** [comment]
Why do you expect `-t 0` to choose window 0 in the first session rather than the second?

**Comment by tesinclair** [comment]
@nicm because when you start a new session without declaring the name it defaults to 0, and increments.

**Comment by nicm** [comment]
You aren't asking for session 0, you're asking for window 0. If you want session 0 you need to do `0:`.

**Comment by tesinclair** [comment]
Ohhh, i'm stupid. So, obviously leaving the second sessions -t 0 just goes to the first window in the last session.
Sorry.

**Comment by nicm** [comment]
If you just want to point to a single pane you are much better to use `display-message -p` and the pane ID.
