### ISSUE TITLE
Ability to force tmux to adapt to new terminal size

### ISSUE THREAD

**Issue by ant5** [tmux/tmux#4003]
### Issue description

I'm using terminal connected to a serial port in Virtual Machine. Inside VM I'm using ``tmux``.
Unfortunately, there is no way (as I been told) to notify ``tty`` when terminal window is resized: no way to do TIOCSWINSZ in response to terminal window resize consequently no SIGWINCH emiited.

As a workaround there is a ``resizewin`` program which manually "measure" terminal size and update tty info:
https://github.com/freebsd/freebsd-src/blob/a16cb8709de7ddc6dd6ab71918af9fc5fd96f377/usr.bin/resizewin/resizewin.c

When I'm in pure shell I can run ``resizewin`` after resizing terminal window then all seems well.
When I'm in ``tmux`` ``resizewin`` will fail measure real terminal size because it inside ``tmux`` window.

Is there a way to force tmux do the same that ``resizewin`` do?

### Required information

VM is a QEMU 9.0 on Windows 10 running FreeBSD 14.1 guest. Terminal is a WindowsTerminal Preview.

Please provide the following information:

* tmux 3.3a
* FreeBSD amd64
* $TERM inside tmux: tmux-256color
* $TERM outside of tmux: xterm-256color

**Comment by ant5** [comment]
There is some beauty in running VM as easy as any other shell command.
Techniqally it has no need to setup and no infrastructure dependency. I think this is interesting case.

**Comment by ant5** [comment]
Yes.  I can detach ``tmux`` then run ``resizewin`` then  ``tmux attach``. 

I just wander may be there is a some code doing this things already in ``tmux`` that can be bringed out as a some command. Then I can bind hot-key to the command and get life little bit easier.

**Comment by nicm** [comment]
No there is no builtin way to do this and I don't think it is worth it for what is a pretty rate use case. Most people would use serial consoles for very short periods and would not resize them often.
