### ISSUE TITLE
Carriage Returns not working correctly when pane is split vertically

### ISSUE THREAD

**Issue by MillerMedia** [tmux/tmux#4004]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
`tmux 3.4`

* Platform (`uname -sp`).
`Linux unknown` (I am using Kali)

* $TERM inside and outside of tmux (`echo $TERM`).
inside tmux - `screen-256color`
outside tmux - `xterm-256color`

* Logs from tmux (`tmux kill-server; tmux -vv new`).
These commands did not work for me?

My issue persists when using command line applications that uses carriage returns to print progress (i.e. rewriting over the same line to show an updated progress). This works fine on a singular tmux window and when I split the pane horizontally (`Ctrl-B "`). When I split the window vertically (`Ctrl-B %`), each iteration of the output is printed on a new line instead of overwriting the current line (normal carriage return functionality). This happens whether I split panes vertically in the midst of a process or start a new process in a vertically split pane.

I have tested this with $TERM values of both screen-256color and tmux-256color.

Please see GIF below demonstrating the bug.
![tmux-bug](https://github.com/tmux/tmux/assets/7741082/eaa2f0f5-90c7-46a0-b5fd-5a7e0e7db622)

**Comment by nicm** [comment]
CR moves to column 1 on the current line, it does not move between lines. Your text wraps over two lines and the cursor is on the second line when the CR is sent.

**Comment by MillerMedia** [comment]
> CR moves to column 1 on the current line, it does not move between lines. Your text wraps over two lines and the cursor is on the second line when the CR is sent.

Oh yes, that totally makes sense. In that case, I'm not sure if there is a simple fix for this but it does create a pretty significant UX issue when trying to use panes to run multiple fuzzing tools.

**Comment by nicm** [comment]
It is a bug in your application, it should adapt its output to the terminal width so this does not happen.

**Comment by MillerMedia** [comment]
> It is a bug in your application, it should adapt its output to the terminal width so this does not happen.

To clarify, that's not my application, just an application I use for pentesting that's relatively common. It happens with all of the other common tools I use that display progress output in this fashion (gobuster, verbose output on hydra, etc)

**Comment by nicm** [comment]
There is an escape sequence called DECAWM which turns off wrapping, you could try that, I think it's `printf "\033[?7l"`.
