### ISSUE TITLE
osc52 not working on V3.4 and Next 3.5？

### ISSUE THREAD

**Issue by MichaelC001** [tmux/tmux#4007]
### Issue description

**Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md**
YES

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

**Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.**

I can use https://github.com/ojroques/nvim-osc52 this plugin to copy neovim text in tmux over ssh ,and paste to local , but it not work on tmux 3.4 and tmux next-3.5, with the same plugin , it works in zellij. please help me , this function is very important to me ,thank you

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
 TMUX next-3.5
* Platform (`uname -sp`).
Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`).
inside tmux： screen-256color
outside tmux：xterm-256color
* Logs from tmux 
[tmux-server-84693.log](https://github.com/user-attachments/files/15887572/tmux-server-84693.log)
[tmux-out-84693.log](https://github.com/user-attachments/files/15887574/tmux-out-84693.log)
[tmux-client-84691.log](https://github.com/user-attachments/files/15887576/tmux-client-84691.log)

**Comment by nicm** [comment]
Logs?

**Comment by MichaelC001** [comment]
> Logs?

how to get logs?
when I run tmux kill-server or tmux -vv new , nothing  is shown.

**Comment by damnskippy** [comment]
FYI, client & server logs in separate files stored under current dir.

https://github.com/tmux/tmux/blob/c07e856d244d07ab2b65e72328fb9fe20747794b/README#L70

**Comment by MichaelC001** [comment]
> Logs?

I added logs in the post.

**Comment by damnskippy** [comment]
@MichaelC001 if you haven't already, maybe go through this page and make sure all your config settings are correctly set up?

https://github.com/tmux/tmux/wiki/Clipboard

**Comment by MichaelC001** [comment]
> I do not see any evidence in this log of you copying text.

I regenerate log like this: 
tmux kill-server
tmux
go to file, yy to copy test "test fzfe"
tmux kill-server
tmux -vv

get the log file [tmux-out-38124.log](https://github.com/user-attachments/files/15913540/tmux-out-38124.log)

with the plugin  https://github.com/ojroques/nvim-osc52, I could copy the remote text in neovim over tmux and ssh, and paste it to the local machine, I could do this with Zellij, but I can't do this over tmux 3.4 even copy text from neovim to local machine without ssh. please help me. thank you.

**Comment by nicm** [comment]
Show the server log please

**Comment by MichaelC001** [comment]
> Show the server log please

thank you for replying. I fix the bug with comment the line:
```
set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7" 
```
