### ISSUE TITLE
Cannot unbind Ctrl-h

### ISSUE THREAD

**Issue by hfytr** [tmux/tmux#4008]
I'm having trouble unbinding C-h in tmux, (i use it as a vim shortcut). I'm trying like this: `unbind-key C-h`. However the shortcut doesn't work in tmux  + nvim, while it does outside tmux. Running `tmux unbind-key C-h` doesn't work either

tmux 3.4
nixos
kitty 0.34.1

**Comment by hfytr** [comment]
so you're saying that tmux recieves BSpace instead?

**Comment by nicm** [comment]
C-h and Backspace send the same character on most terminals, but you should receive it. If you don't probably your terminal is sending something funny or vim is expecting something different from what tmux is sending.

**Comment by hfytr** [comment]
Hmm, I use kitty, and I'm pretty sure it sends c-h (otherwise it also wouldn't work outside tmux).
