### ISSUE TITLE
How to configure different mouse actions on status lines

### ISSUE THREAD

**Issue by afh** [tmux/tmux#4011]
### Issue description

Looking at the manpage and sources it seems not possible to configure mouse actions for each status line individually.

Let me give an example based on tmux with a default config:

* Create a multi-line status bar: `set status 2`
* Enable the mouse: `set mouse on`
* Configure a mouse action for the status bar: e.g. `bind-key -T root MouseDown1StatusDefault display-message "Ping"`

Now clicking anywhere on either of the status lines (the first and the second) that isn't part of the tmux status window list or left or right status the message "Ping" is displayed.

I'd like to be able to configure a different action when the second status line is clicked, e.g.:

`bind-key -T root MouseDown1Status2Default display-message "Pong"`

so that clicking on the first line shows "Ping" and clicking on the second line shows "Pong".

I guess my proposal is to expand the location suffix, so that can include the index of the status line for multi-line status, e.g. `Status2Default`. 

@nicm is this a (new?) functionality that you and others would see value in?
If yes, what is your estimated effort/complexity on adding this?
And would you be willing to give some pointers for guidance how and where this would need to be added to tmux. Depending on the estimated effort/complexity I'd be willing to give it a try.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.4`.
* Platform (`uname -sp`): `Darwin arm`.
* $TERM inside and outside of tmux (`echo $TERM`): `alacritty`.
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
You can get which status line was clicked on  in the `mouse_status_line` format variable.

Or alternatively you should be able to define user ranges which will fire `MouseDownXStatus` instead and then you can get the argument with `mouse_status_range`.

**Comment by afh** [comment]
Thanks for the quick and **very** helpful response, @nicm! 🥳
Using  `if -F '#{==:#{mouse_status_line},1}'` I can (almost completely (see below)) do what I'd like to do.

One nit that I don't understand so far is that mouse actions configured with the location suffixes `StatusLeft` and `StatusRight` only seem work on the first status line. I assume that is intentional as that line is the only one that handles the `status-right` and `status-left` settings…

In case I wanted to differentiate whether "items" on the second or third status line on the left or right (aligned using `#[align=left|right]`) were clicked, would or should I be able to use `#{mouse_status_range}`? First rudimentary tests indicate that this might currently not be possible…

**Comment by afh** [comment]
Ah just saw the first message you posted. Let me read up on user ranges…

**Comment by afh** [comment]
I'm beginning to understand. As always tmux impresses with its functionality! At first my mind was trying to set `status-right[1]` but that didn't work, yet setting `status-format[1] = '#[range=right]` did work and triggered the location suffix `StatusRight`. 🎉 

A few tests seem to indicate that if using the `-a` (append) option on `set-option -a status-format[1]`, it is not possible to add a format with `#[range=left]` **after** previously the format was set with `#[range=right]`. Ergo the format should be created from left to right, is that correct?

Does `#[norange]` exist or even make sense to end a range in a given format?

And now I'm torn whether I should use custom user ranges or the standard `left` and `right`? 😅

**Comment by nicm** [comment]
You can look at what styles are left after `status-format[0]` is evalulated:
~~~~
$ tmux display -p '#{E:status-format[0]}'
#[align=left range=left default]#[push-default][0] #[pop-default]#[norange default]#[list=on align=left]#[list=left-marker]<#[list=right-marker]>#[list=on]#[range=window|0 default]#[push-default]0:irssi-#[pop-default]#[norange default] #[range=window|1 default]#[push-default]1:mutt #[pop-default]#[norange default] #[range=window|2 default]#[push-default]2:emacsclient #[pop-default]#[norange default] #[range=window|3 default]#[push-default]3:emacsclient #[pop-default]#[norange default] #[range=window|4 default]#[push-default]4:emacsclient #[pop-default]#[norange default] #[range=window|5 default]#[push-default]5:ksh #[pop-default]#[norange default] #[range=window|6 default]#[push-default]6:ksh #[pop-default]#[norange default] #[range=window|7 default]#[push-default]7:emacsclient #[pop-default]#[norange default] #[range=window|8 list=focus underscore]#[push-default]8:ksh*#[pop-default]#[norange list=on default]#[nolist align=right range=right default]#[push-default]14:34#[pop-default]#[norange default]

**Comment by afh** [comment]
Answering my own question: `#[norange]` exists and seems to be necessary for the mouse events to trigger…

**Comment by afh** [comment]
TIL: `push`- and `pop-default` 🙂 I was looking how to dump the current config and formats to learn from it, but only found `tmux show -g`; `display -p` comes in very handy!

Thanks for sharing your knowledge, @nicm, and helping out, very much appreciated! 🙏

**Comment by afh** [comment]
I'm going to close this as tmux already allows me to do what I want to do, I was just looking in a ~~wrong~~different direction  when looking for a solution.
