### ISSUE TITLE
`previous-prompt -o` does not work on the same line

### ISSUE THREAD

**Issue by Susensio** [tmux/tmux#4012]
### Issue description
Jump to the beginning of the current command output does not work as expected. When inside a command output, it should go to the the beginning of the same output, but it goes 1 prompt too far.

### Steps to reproduce

```
tmux kill-server; tmux -vv -L test -f /dev/null new bash
```
```
PS1='\[\e]133;A\e\\\]$ ' # prompt start
PS0='\[\e]133;C\e\\\]'   # command output start
```
```
echo 1111
```
```
echo 2222
```
```
Ctrl+B [                          # enter copy-mode
k                                 # jump to the end of line with the 2222 output
Ctr+B :send -X previous-prompt -o # this should jump to the start of the line with the 2 output, but goes up to 1111
```

`previous-prompt` (without `-o`) works fine

https://asciinema.org/a/j4wyrcsKscalH51bebDnRU5Bq

### Required information

tmux next-3.5
Linux unknown
tmux-256color

<details>

1718959094.153891 client started (3766098): version next-3.5, socket /tmp/tmux-1000/test, protocol 8
1718959094.154124 on Linux 6.7.12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.7.12-1 (2024-04-24)
1718959094.154198 using libevent 2.1.12-stable poll
1718959094.154246 using ncurses 6.4 20240113
1718959094.154435 flags are 0x18010000
1718959094.154500 socket is /tmp/tmux-1000/test
1718959094.154600 trying connect
1718959094.155189 add peer 0x5588cdcb3940: 6 ((nil))
1718959094.157644 sending message 100 to peer 0x5588cdcb3940 (4 bytes)
1718959094.157757 sending message 111 to peer 0x5588cdcb3940 (8 bytes)
1718959094.157815 sending message 101 to peer 0x5588cdcb3940 (15 bytes)
1718959094.157863 sending message 109 to peer 0x5588cdcb3940 (4 bytes)
1718959094.157910 sending message 102 to peer 0x5588cdcb3940 (11 bytes)
1718959094.157957 sending message 108 to peer 0x5588cdcb3940 (15 bytes)
1718959094.158003 sending message 112 to peer 0x5588cdcb3940 (58 bytes)
1718959094.158051 sending message 112 to peer 0x5588cdcb3940 (5 bytes)
1718959094.158098 sending message 112 to peer 0x5588cdcb3940 (5 bytes)
1718959094.158144 sending message 112 to peer 0x5588cdcb3940 (6 bytes)
1718959094.158190 sending message 112 to peer 0x5588cdcb3940 (6 bytes)
1718959094.158237 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.158280 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.158321 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.158365 sending message 112 to peer 0x5588cdcb3940 (14 bytes)
1718959094.158410 sending message 112 to peer 0x5588cdcb3940 (19 bytes)
1718959094.158455 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.158502 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.158549 sending message 112 to peer 0x5588cdcb3940 (15 bytes)
1718959094.158594 sending message 112 to peer 0x5588cdcb3940 (21 bytes)
1718959094.158640 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.158688 sending message 112 to peer 0x5588cdcb3940 (7 bytes)
1718959094.158795 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.158875 sending message 112 to peer 0x5588cdcb3940 (7 bytes)
1718959094.158923 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.158971 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.159017 sending message 112 to peer 0x5588cdcb3940 (21 bytes)
1718959094.159066 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.159112 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.159160 sending message 112 to peer 0x5588cdcb3940 (16 bytes)
1718959094.159206 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.159253 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.159300 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.159347 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.159393 sending message 112 to peer 0x5588cdcb3940 (8 bytes)
1718959094.159439 sending message 112 to peer 0x5588cdcb3940 (8 bytes)
1718959094.159486 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.159534 sending message 112 to peer 0x5588cdcb3940 (7 bytes)
1718959094.159581 sending message 112 to peer 0x5588cdcb3940 (7 bytes)
1718959094.159628 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.159675 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.159723 sending message 112 to peer 0x5588cdcb3940 (15 bytes)
1718959094.159769 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.159816 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.159864 sending message 112 to peer 0x5588cdcb3940 (8 bytes)
1718959094.159910 sending message 112 to peer 0x5588cdcb3940 (14 bytes)
1718959094.159956 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.160003 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.160051 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.160097 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.160143 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.160255 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.160307 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.160356 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.160402 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.160450 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.160497 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.160544 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.160590 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.160634 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.160680 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.160727 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.160774 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.160820 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.160866 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.160915 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.160961 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.161009 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161056 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161103 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161150 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161197 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161244 sending message 112 to peer 0x5588cdcb3940 (8 bytes)
1718959094.161290 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.161338 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.161386 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.161434 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.161480 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.161528 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.161575 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.161620 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161668 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161715 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161762 sending message 112 to peer 0x5588cdcb3940 (8 bytes)
1718959094.161810 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161857 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161905 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161948 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.161995 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162042 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.162088 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.162136 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.162183 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.162230 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162276 sending message 112 to peer 0x5588cdcb3940 (8 bytes)
1718959094.162323 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162371 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162418 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162465 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162513 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162561 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162621 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162647 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.162673 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.162699 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.162763 sending message 112 to peer 0x5588cdcb3940 (8 bytes)
1718959094.162800 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.162842 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162904 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162932 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162958 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.162984 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163011 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163036 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163062 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163087 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163112 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.163138 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163165 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163191 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163217 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163242 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163269 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163294 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163320 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163347 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163374 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163400 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.163427 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163453 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163479 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163503 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163529 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.163555 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.163581 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.163607 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163632 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163656 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163682 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163707 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163733 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.163758 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.163783 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.163808 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163832 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163857 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163882 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163907 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163931 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.163956 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.163981 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.164006 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164031 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164056 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164080 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164106 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164130 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.164155 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.164179 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.164203 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164228 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164252 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164276 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164304 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164330 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.164390 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.164420 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164447 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164473 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164499 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164525 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164551 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.164577 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.164602 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164628 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164654 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164681 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164706 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.164732 sending message 112 to peer 0x5588cdcb3940 (11 bytes)
1718959094.164759 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.164788 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.164815 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.164842 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.164868 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.164896 sending message 112 to peer 0x5588cdcb3940 (21 bytes)
1718959094.164923 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.164951 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.164978 sending message 112 to peer 0x5588cdcb3940 (6 bytes)
1718959094.165005 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.165032 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.165059 sending message 112 to peer 0x5588cdcb3940 (24 bytes)
1718959094.165085 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.165112 sending message 112 to peer 0x5588cdcb3940 (9 bytes)
1718959094.165140 sending message 112 to peer 0x5588cdcb3940 (70 bytes)
1718959094.165168 sending message 112 to peer 0x5588cdcb3940 (69 bytes)
1718959094.165195 sending message 112 to peer 0x5588cdcb3940 (12 bytes)
1718959094.165222 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.165249 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.165276 sending message 112 to peer 0x5588cdcb3940 (24 bytes)
1718959094.165302 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.165328 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.165355 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.165383 sending message 112 to peer 0x5588cdcb3940 (10 bytes)
1718959094.165411 sending message 112 to peer 0x5588cdcb3940 (13 bytes)
1718959094.165438 sending message 112 to peer 0x5588cdcb3940 (15 bytes)
1718959094.165466 sending message 112 to peer 0x5588cdcb3940 (5 bytes)
1718959094.165505 sending message 104 to peer 0x5588cdcb3940 (0 bytes)
1718959094.165539 sending message 110 to peer 0x5588cdcb3940 (0 bytes)
1718959094.165571 sending message 107 to peer 0x5588cdcb3940 (4 bytes)
1718959094.165597 sending message 105 to peer 0x5588cdcb3940 (19 bytes)
1718959094.165624 sending message 105 to peer 0x5588cdcb3940 (41 bytes)
1718959094.165652 sending message 105 to peer 0x5588cdcb3940 (20 bytes)
1718959094.165679 sending message 105 to peer 0x5588cdcb3940 (25 bytes)
1718959094.165705 sending message 105 to peer 0x5588cdcb3940 (68 bytes)
1718959094.165731 sending message 105 to peer 0x5588cdcb3940 (46 bytes)
1718959094.165758 sending message 105 to peer 0x5588cdcb3940 (22 bytes)
1718959094.165785 sending message 105 to peer 0x5588cdcb3940 (14 bytes)
1718959094.165812 sending message 105 to peer 0x5588cdcb3940 (28 bytes)
1718959094.165839 sending message 105 to peer 0x5588cdcb3940 (80 bytes)
1718959094.165865 sending message 105 to peer 0x5588cdcb3940 (24 bytes)
1718959094.165893 sending message 105 to peer 0x5588cdcb3940 (43 bytes)
1718959094.165920 sending message 105 to peer 0x5588cdcb3940 (20 bytes)
1718959094.165973 sending message 105 to peer 0x5588cdcb3940 (16 bytes)
1718959094.166006 sending message 105 to peer 0x5588cdcb3940 (23 bytes)
1718959094.166036 sending message 105 to peer 0x5588cdcb3940 (17 bytes)
1718959094.166064 sending message 105 to peer 0x5588cdcb3940 (35 bytes)
1718959094.166092 sending message 105 to peer 0x5588cdcb3940 (49 bytes)
1718959094.166121 sending message 105 to peer 0x5588cdcb3940 (44 bytes)
1718959094.166150 sending message 105 to peer 0x5588cdcb3940 (79 bytes)
1718959094.166178 sending message 105 to peer 0x5588cdcb3940 (26 bytes)
1718959094.166205 sending message 105 to peer 0x5588cdcb3940 (62 bytes)
1718959094.166233 sending message 105 to peer 0x5588cdcb3940 (26 bytes)
1718959094.166261 sending message 105 to peer 0x5588cdcb3940 (190 bytes)
1718959094.166288 sending message 105 to peer 0x5588cdcb3940 (23 bytes)
1718959094.166315 sending message 105 to peer 0x5588cdcb3940 (56 bytes)
1718959094.166343 sending message 105 to peer 0x5588cdcb3940 (25 bytes)
1718959094.166370 sending message 105 to peer 0x5588cdcb3940 (20 bytes)
1718959094.166399 sending message 105 to peer 0x5588cdcb3940 (37 bytes)
1718959094.166427 sending message 105 to peer 0x5588cdcb3940 (44 bytes)
1718959094.166455 sending message 105 to peer 0x5588cdcb3940 (69 bytes)
1718959094.166484 sending message 105 to peer 0x5588cdcb3940 (16 bytes)
1718959094.166512 sending message 105 to peer 0x5588cdcb3940 (76 bytes)
1718959094.166539 sending message 105 to peer 0x5588cdcb3940 (62 bytes)
1718959094.166568 sending message 105 to peer 0x5588cdcb3940 (19 bytes)
1718959094.166597 sending message 105 to peer 0x5588cdcb3940 (18 bytes)
1718959094.166625 sending message 105 to peer 0x5588cdcb3940 (590 bytes)
1718959094.166652 sending message 105 to peer 0x5588cdcb3940 (38 bytes)
1718959094.166680 sending message 105 to peer 0x5588cdcb3940 (17 bytes)
1718959094.166707 sending message 105 to peer 0x5588cdcb3940 (38 bytes)
1718959094.166765 sending message 105 to peer 0x5588cdcb3940 (27 bytes)
1718959094.166794 sending message 105 to peer 0x5588cdcb3940 (44 bytes)
1718959094.166838 sending message 105 to peer 0x5588cdcb3940 (21 bytes)
1718959094.166866 sending message 105 to peer 0x5588cdcb3940 (56 bytes)
1718959094.166894 sending message 105 to peer 0x5588cdcb3940 (8 bytes)
1718959094.166927 sending message 105 to peer 0x5588cdcb3940 (56 bytes)
1718959094.166955 sending message 105 to peer 0x5588cdcb3940 (48 bytes)
1718959094.166983 sending message 105 to peer 0x5588cdcb3940 (24 bytes)
1718959094.167010 sending message 105 to peer 0x5588cdcb3940 (18 bytes)
1718959094.167036 sending message 105 to peer 0x5588cdcb3940 (20 bytes)
1718959094.167063 sending message 105 to peer 0x5588cdcb3940 (70 bytes)
1718959094.167089 sending message 105 to peer 0x5588cdcb3940 (38 bytes)
1718959094.167115 sending message 105 to peer 0x5588cdcb3940 (11 bytes)
1718959094.167142 sending message 105 to peer 0x5588cdcb3940 (58 bytes)
1718959094.167169 sending message 105 to peer 0x5588cdcb3940 (44 bytes)
1718959094.167196 sending message 105 to peer 0x5588cdcb3940 (50 bytes)
1718959094.167222 sending message 105 to peer 0x5588cdcb3940 (44 bytes)
1718959094.167248 sending message 105 to peer 0x5588cdcb3940 (14 bytes)
1718959094.167275 sending message 105 to peer 0x5588cdcb3940 (21 bytes)
1718959094.167302 sending message 105 to peer 0x5588cdcb3940 (49 bytes)
1718959094.167329 sending message 105 to peer 0x5588cdcb3940 (23 bytes)
1718959094.167355 sending message 105 to peer 0x5588cdcb3940 (42 bytes)
1718959094.167384 sending message 105 to peer 0x5588cdcb3940 (36 bytes)
1718959094.167411 sending message 105 to peer 0x5588cdcb3940 (20 bytes)
1718959094.167439 sending message 105 to peer 0x5588cdcb3940 (25 bytes)
1718959094.167466 sending message 105 to peer 0x5588cdcb3940 (31 bytes)
1718959094.167492 sending message 105 to peer 0x5588cdcb3940 (50 bytes)
1718959094.167520 sending message 105 to peer 0x5588cdcb3940 (49 bytes)
1718959094.167547 sending message 105 to peer 0x5588cdcb3940 (54 bytes)
1718959094.167575 sending message 105 to peer 0x5588cdcb3940 (17 bytes)
1718959094.167632 sending message 105 to peer 0x5588cdcb3940 (30 bytes)
1718959094.167654 sending message 105 to peer 0x5588cdcb3940 (39 bytes)
1718959094.167673 sending message 105 to peer 0x5588cdcb3940 (51 bytes)
1718959094.167691 sending message 105 to peer 0x5588cdcb3940 (26 bytes)
1718959094.167709 sending message 105 to peer 0x5588cdcb3940 (52 bytes)
1718959094.167728 sending message 105 to peer 0x5588cdcb3940 (79 bytes)
1718959094.167746 sending message 105 to peer 0x5588cdcb3940 (42 bytes)
1718959094.167764 sending message 105 to peer 0x5588cdcb3940 (29 bytes)
1718959094.167783 sending message 105 to peer 0x5588cdcb3940 (54 bytes)
1718959094.167801 sending message 105 to peer 0x5588cdcb3940 (28 bytes)
1718959094.167819 sending message 105 to peer 0x5588cdcb3940 (52 bytes)
1718959094.167838 sending message 105 to peer 0x5588cdcb3940 (59 bytes)
1718959094.167856 sending message 105 to peer 0x5588cdcb3940 (53 bytes)
1718959094.167874 sending message 105 to peer 0x5588cdcb3940 (20 bytes)
1718959094.167893 sending message 105 to peer 0x5588cdcb3940 (613 bytes)
1718959094.167914 sending message 105 to peer 0x5588cdcb3940 (17 bytes)
1718959094.167933 sending message 105 to peer 0x5588cdcb3940 (23 bytes)
1718959094.167951 sending message 105 to peer 0x5588cdcb3940 (23 bytes)
1718959094.167970 sending message 105 to peer 0x5588cdcb3940 (193 bytes)
1718959094.167989 sending message 105 to peer 0x5588cdcb3940 (42 bytes)
1718959094.168007 sending message 105 to peer 0x5588cdcb3940 (39 bytes)
1718959094.168025 sending message 105 to peer 0x5588cdcb3940 (27 bytes)
1718959094.168043 sending message 105 to peer 0x5588cdcb3940 (29 bytes)
1718959094.168061 sending message 105 to peer 0x5588cdcb3940 (47 bytes)
1718959094.168080 sending message 105 to peer 0x5588cdcb3940 (58 bytes)
1718959094.168099 sending message 105 to peer 0x5588cdcb3940 (116 bytes)
1718959094.168117 sending message 105 to peer 0x5588cdcb3940 (18 bytes)
1718959094.168135 sending message 105 to peer 0x5588cdcb3940 (55 bytes)
1718959094.168164 sending message 105 to peer 0x5588cdcb3940 (26 bytes)
1718959094.168185 sending message 105 to peer 0x5588cdcb3940 (46 bytes)
1718959094.168203 sending message 105 to peer 0x5588cdcb3940 (105 bytes)
1718959094.168221 sending message 105 to peer 0x5588cdcb3940 (17 bytes)
1718959094.168239 sending message 105 to peer 0x5588cdcb3940 (11 bytes)
1718959094.168257 sending message 105 to peer 0x5588cdcb3940 (47 bytes)
1718959094.168275 sending message 105 to peer 0x5588cdcb3940 (26 bytes)
1718959094.168294 sending message 105 to peer 0x5588cdcb3940 (1524 bytes)
1718959094.168363 sending message 105 to peer 0x5588cdcb3940 (28 bytes)
1718959094.168388 sending message 105 to peer 0x5588cdcb3940 (148 bytes)
1718959094.168407 sending message 105 to peer 0x5588cdcb3940 (181 bytes)
1718959094.168426 sending message 105 to peer 0x5588cdcb3940 (24 bytes)
1718959094.168445 sending message 105 to peer 0x5588cdcb3940 (45 bytes)
1718959094.168464 sending message 105 to peer 0x5588cdcb3940 (11 bytes)
1718959094.168484 sending message 105 to peer 0x5588cdcb3940 (37 bytes)
1718959094.168504 sending message 105 to peer 0x5588cdcb3940 (51 bytes)
1718959094.168522 sending message 106 to peer 0x5588cdcb3940 (0 bytes)
1718959094.168699 cmd_pack_argv: argv[0]=new
1718959094.168729 cmd_pack_argv: argv[1]=bash
1718959094.168749 sending message 200 to peer 0x5588cdcb3940 (13 bytes)
1718959094.168769 client loop enter
1718959094.172756 peer 0x5588cdcb3940 message 207
1718959094.172801 sending message 208 to peer 0x5588cdcb3940 (0 bytes)
1718959132.178453 peer 0x5588cdcb3940 message 201
1718959132.178622 sending message 205 to peer 0x5588cdcb3940 (0 bytes)
1718959132.180622 peer 0x5588cdcb3940 message 204
1718959132.180791 client loop exit

</details>

could be related to https://github.com/tmux/tmux/issues/3734

**Comment by vimpostor** [comment]
Yeah, the whole grid system works [based on lines](https://github.com/tmux/tmux/blob/7ad29b98311b4961d203dc360e6a21f35dac9f97/window-copy.c#L5423) and not on exact positions, so with the current implementation it is impossible to distinguish prompt and cursor location if they are on the same line.

And to be honest, for me the current behaviour also makes more sense. If I am already on the beginning of the output (regardless of if I am on the end or the beginning of the line), then `previous-prompt -o` should go to the previous prompt's output and not stay on the current line once more.

**Comment by nicm** [comment]
I think it is fine as it is. If you are on the same line it is already at the prompt.

**Comment by nicm** [comment]
Your prompt is always pretty much the same though, right? So you can skip over it? For example if it ends in `$` you could do `start-of-line` and then `jump-forward '$'` and it will take you to the end of the prompt.

**Comment by Susensio** [comment]
Thanks for the hint! I can skip the prompt by one line:
```
bind -T copy-mode-vi p {
  send-keys -X previous prompt;
  send-keys -X cursor-down;
  send-keys -X begin-selection;
  send-keys -X next prompt;
}
```

**Comment by vimpostor** [comment]
> Thanks for the hint! I can skip the prompt by one line

Depending on how long your prompt is, it might be more reliable to go to the previous prompt, then to the next prompt output instead of assuming one cursor-down is enough to get from the prompt to the output.
