### ISSUE TITLE
regression: tmux cannot find occurrences of text in scrollback buffer if they are in a wrapped line

### ISSUE THREAD

**Issue by komar007** [tmux/tmux#4017]
### Issue description

The issue is related to tmux-3.4, it is a regression with respect to 3.3a.

When there is just one occurrence of some text in the scollback buffer and it happens to be in a wrapped line (the occurrence is not necessarily broken into two lines - it may be at the very start of the line), `search-forward` does not find this occurrence in the scrollback buffer (and a popup indicating no results is shown in copy-mode).

When another occurrence is added to the scrollback buffer (but this time in a short, non-wrapped line), the next search correctly highlights both occurrences and correctly indicates that there are "2 results", but consecutive <kbd>n</kbd> or <kbd>N</kbd> only highlight the second occurrence as the current one. When there are more occurrences, <kbd>n</kbd> and <kbd>N</kbd> only cycle through the occurrences in the non-wrapped lines, omitting the one in the wrapped line, even though it remains highlighted and included in the number of results.

### Steps to reproduce

1. Prepare a terminal that has fewer than 400 columns,
2. run the following script:
   ```sh
   (sleep 1 && ./tmux -Lx send-keys "aaaaa $(printf '.%.0s' {1..400})" && ./tmux -Lx copy-mode && ./tmux -Lx send-keys -X search-forward aaaaa &) && ./tmux -vv -Lx -f /dev/null
   ```
3. observe the yellow popup in the top-right hand corner - it reads "[0/0]"; it should read "(1 results) [0/0]", or at least that's the case on 3.3a.

### Required information

* tmux version: 3.4
* Platform: Linux x86_64
* $TERM inside tmux: tmux-256color
* $TERM outside of tmux: alacritty (it doesn't seem to be dependent on the terminal, I've tested both alacritty and urxvt so far)
* Logs from tmux:
[tmux-server-22443.log](https://github.com/user-attachments/files/15959566/tmux-server-22443.log)
[tmux-client-22441.log](https://github.com/user-attachments/files/15959570/tmux-client-22441.log)

**Comment by komar007** [comment]
A quick bisect between 3.3a and master with the script provided above shows the culprit: https://github.com/tmux/tmux/commit/43e5e80343185e69a1b864fc48095ede0b898180.
The commit reverts cleanly on master and it resolves the issue.

**Comment by nicm** [comment]
This is already fixed in master.

**Comment by timotheecour** [comment]
@nicm when can we expect `brew install tmux` to have this fix ?
refs https://github.com/Homebrew/homebrew-core/pull/170396#issuecomment-2084864383
