### ISSUE TITLE
User options cannot be used in conditionals

### ISSUE THREAD

**Issue by lostl1ght** [tmux/tmux#4018]
### Issue description

User options cannot be used in conditionals because they cannot be expanded there.

With the config below tmux displays 2 messages: 
```
tmux.conf:3: 1
tmux.conf:8: else
```
However, I expect it to display messages:
```
tmux.conf:3: 1
tmux.conf:8: if
```
#### Minimal config

```tmux
set -g @theme 'theme'

display-message "#{==:#{@theme},"theme"}" # this correctly evaluates to 1

%if "#{==:#{@theme},"theme"}" # this produces an error in logs
display-message 'if' # this message __should__ be displayed
%else
display-message 'else' # this message __is__ displayed
%endif
```

### Required information

Please provide the following information:

* tmux version is `3.4`.
* Platform is `Linux unknown`.
* $TERM inside and outside of tmux are `tmux-256color` and `wezterm` respectively.
* Logs from tmux (`tmux -Ltest -ftmux.conf -vv`): [logs.tar.gz](https://github.com/user-attachments/files/15971157/logs.tar.gz)
  Relevant line is probably 16863 in server logs.

### Workaround

I was able to work around the issue by using (both hidden & explicit) environment variables.

```tmux
%hidden theme="theme"

%if "#{==:#{theme},"theme"}" 
# the rest of the config
```

**Comment by nicm** [comment]
`%if` happens when the config is parsed and `set` when commands are executed so it is expected that `@theme` is not set for `%if`.

**Comment by lostl1ght** [comment]
If you could, please, explain how are environment variables different in this case? Are they set when the config is parsed?

And is the only way to have this kind of conditional is to use environment variables?

**Comment by nicm** [comment]
Yes. Environment variables set with `X=y` are set when parsing, if set with `set-environment` they are set when the commands are executed.
