### ISSUE TITLE
`tmux-attach -c .` doesn't have the expected behaviour

### ISSUE THREAD

**Issue by dev-ardi** [tmux/tmux#4019]
I would expect `tmux-attach -c .` to change the default dir to my current shell dir but instead it changes it to the first dir that tmux was opened with.
```bash
cd /path/1
tmux # default is /path/1
:attach-session -c /path/2 # default is /path/2
cd /path/3
:attach-session . # default is /path/1
```

**Comment by nicm** [comment]
Correct, that is how it works.

**Comment by dev-ardi** [comment]
Why? And how to use the cwd?

**Comment by nicm** [comment]
Server does not know `.` means the client WD so it uses its own, best bet is to use `$PWD` instead.

**Comment by dev-ardi** [comment]
Is this behaviour something that any user could want?
Could it be possible to override the `.` with `$PWD` and if the user wanted to preserve old behaviour use something like `tmux-attach -c -`?
