### ISSUE TITLE
Alt-arrow key bindings to switch panes not working

### ISSUE THREAD

**Issue by Naylenv** [tmux/tmux#4021]
Hello,

I have the following configuration in my ~/.tmux.conf:
My machine is macos, targert machine is debain.
```bash
# Use Alt-arrow keys to switch panes
bind -n M-S-Left select-pane -L
bind -n M-S-Right select-pane -R
bind -n M-S-Up select-pane -U
bind -n M-S-Down select-pane -D
```
This setup worked perfectly in tmux version 3.1. However, after upgrading to version 3.3a, these key bindings no longer work. Instead, I receive outputs like `0D0A` in the terminal.

Could you please advise on how to resolve this issue?

Thank you!

**Comment by nicm** [comment]
Logs?
