### ISSUE TITLE
TMUX sessions are lost after shutdown

### ISSUE THREAD

**Issue by joaomendoncaa** [tmux/tmux#4022]
### Issue

![image](https://github.com/tmux/tmux/assets/57664150/7ccf694f-8368-49d6-8730-54c0d7f4b57b)

**Recently a WSL instance I use a lot started to not be able to recover tmux sessions after a shutdown.** 

Using WSL + Ubuntu (spec listed bellow) a tmux install through `apt` and creating a new session, doing any kind of activity, shutting down the WSL instance and booting back up will show this message: `error connecting to /tmp/tmux-1000/default (No such file or directory)`.

I've searched around for some [identical issues](https://github.com/tmux/tmux/issues/2377) with no success. It seems to me there's some kind of `/tmp` files flushing after a shutdown that doesn't correctly persist the necessary data for tmux to function normally after botting back up.

### Steps to reproduce (given that you're on a Ubuntu WSL instance)

1. `tmux`
2. do anything at all like opening panels starting processes etc
3. open powershell to shutdown wsl with `wsl --shutdown`
4. open wsl again and try to attach to your last session with `tmux a`

PS: Alternative to step 3. you can `exit` and re-boot on.

---

### Specs

* tmux version - `3.2a`
* Platform - `Linux x86_64` (WSL2 Ubuntu instance)
* $TERM inside - `screen-256color`
* $TERM outside - `xterm-256color`
* WSL: 2.2.4.0
* kernel: 5.15.153.1-2
* WSLg: 1.0.61
* MSRDC: 1.2.5326
* Direct3D: 1.611.1-81528511
* DXCore: 10.0.26091.1-240325-1447.ge-release
* Windows: 10.0.22631.3737

--- 

Appreciate any help/insights in advance.

**Comment by hauphanlvc** [comment]
In my opinion, /tmp will be deleted after WSL rebooted, so the old Tmux sessions also  deleted, I suggest that you could try to use [tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect). Have a nice day

**Comment by joaomendoncaa** [comment]
> In my opinion, /tmp will be deleted after WSL rebooted, so the old Tmux sessions also deleted, I suggest that you could try to use [tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect). Have a nice day

Installed it, it worked. I was under the impression that tmux itself was suposed to persist across sessions. 🤔 Is that not the case? Is this the expected behaviour from tmux (losing all sessions upon reboot)?
