### ISSUE TITLE
Question: how to always show pane numbers

### ISSUE THREAD

**Issue by Giessen** [tmux/tmux#4025]
### Required information

Please provide the following information:

* tmux version: V3.4
* Platform: WSL2 / Linux x86_64
* $TERM inside and outside of tmux: xterm-256color | tmux-256color

1) Is there any way to allow showing pane numbers forever, surviving any key pressing, etc.? 
2) Is there an option to show pane number on top right corner, in position of pane size?
Thanks in advance.

**Comment by nicm** [comment]
You can turn on the pane status line (`pane-border-status`) and show the pane index and size in it.

**Comment by Giessen** [comment]
Thank you very much! It works like charm!
