### ISSUE TITLE
no server running on /tmp/tmux-1000/default

### ISSUE THREAD

**Issue by opu-hossain** [tmux/tmux#4026]
### System Information:
- **tmux version**: 3.4
- **OS**: Arch Linux (installed via AUR using yay)
- **Terminal Emulator**: Kitty
- **TERM environment variable outside tmux**: xterm-kitty
- **TERM environment variable inside tmux**: tmux-256color
- **Kernel version**: Output of `uname -sp`: Linux unknown

### Steps to Reproduce:
1. Install tmux using AUR via `yay -S tmux`.
2. Start a new tmux session using `tmux new -s test`.
3. Perform some work inside the tmux session.
4. Detach from the session using `Ctrl+b d`.
5. Attempt to list the tmux sessions using `tmux ls`.

### Expected Behavior:
A list of active tmux sessions should be displayed.

### Actual Behavior:
Error message: `no server running on /tmp/tmux-1000/default`.

### Additional Information:
Below are the terminal commands and their outputs leading up to the issue:

```sh
❯ tmux ls
no server running on /tmp/tmux-1000/default

❯ tmux -vv new -s test
[exited]

❯ tmux -V
tmux 3.4

❯ uname -sp
Linux unknown

❯ echo $TERM
xterm-kitty

❯ tmux
[exited]

❯ nano ~/.tmux.conf
# (No changes made or default configuration)

❯ ls -l /tmp/tmux-$(id -u)/default
srw-rw---- - salman  2 Jul 14:44 /tmp/tmux-1000/default

❯ ps -ef | grep -i tmux
salman     50689   23623  0 14:55 pts/0    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox -i tmux
```
[tmux-client-32368.log](https://github.com/user-attachments/files/16065426/tmux-client-32368.log)
[tmux-out-32370.log](https://github.com/user-attachments/files/16065457/tmux-out-32370.log)
[tmux-server-32370.log](https://github.com/user-attachments/files/16065460/tmux-server-32370.log)

**Comment by nicm** [comment]
Your tmux server is exiting as normal because all of the panes have exited. Looks like someone is pressing `C-d` to exit the last shell.

**Comment by opu-hossain** [comment]
> Your tmux server is exiting as normal because all of the panes have exited. Looks like someone is pressing `C-d` to exit the last shell.

i tried to `C-d`( detach) tmux after opening a session

**Comment by nicm** [comment]
You are pressing `C-b C-d` but your prefix is `C-a`... so the `C-d` will exit the shell.

**Comment by opu-hossain** [comment]
> OK so it did attach?

i don't know,
First I created a new session after installing Tmux,
then for testing purposes, I updated my aur, and using `C-d` I detached from tmux

and then tried to list all the sessions, but there were none.

**Comment by nicm** [comment]
Your prefix is `C-a` so when you press `C-b C-d` tmux is not detaching and instead the `C-d` is making the shell exit.

**Comment by opu-hossain** [comment]
> Your prefix is `C-a` so when you press `C-b C-d` tmux is not detaching and instead the `C-d` is making the shell exit.

oh, so what do I do now? I'll re-install tmux using Pacman and without any external config I perform the same steps, if I face any problem I'll reply to you in a bit.

**Comment by nicm** [comment]
Make sure you delete the config files that are setting the prefix to C-a.

**Comment by opu-hossain** [comment]
> Make sure you delete the config files that are setting the prefix to C-a.

i have deleted the config file and then re-installed tmux.

then same happened. 
`❯ tmux -vv new -s test
[exited]
❯ tmux ls
no server running on /tmp/tmux-1000/default`

here are the logs:
[tmux-client-41838.log](https://github.com/user-attachments/files/16066038/tmux-client-41838.log)
[tmux-out-41840.log](https://github.com/user-attachments/files/16066040/tmux-out-41840.log)
[tmux-server-41840.log](https://github.com/user-attachments/files/16066042/tmux-server-41840.log)

To detach the session I pressed `ctrl+b with d (for detaching)`. now what might be the issue?

**Comment by nicm** [comment]
I don't know what you are doing with the keyboard but you are not managing to press `C-b d`. Are you sure you are releasing `Ctrl` before you press `d`? In the end you are pressing `C-d` which is making the shell exit.

Try `set -o ignoreof` in the shell and it will not exit on `C-d`.

**Comment by opu-hossain** [comment]
> I don't know what you are doing with the keyboard but you are not managing to press `C-b d`. Are you sure you are releasing `Ctrl` before you press `d`? In the end you are pressing `C-d` which is making the shell exit.
> 
> Try `set -o ignoreeof` in the shell and it will not exit on `C-d`.

Thanks to you, 
now I understand that, I was pressing `ctrl + b and d ` at the same time, I didn't know that I have to release `ctrl + b` before pressing `d`,

now the session stays there and working fine, I can view my test session using `tmux ls`

I appreciate your help
