### ISSUE TITLE
Tmux not working with oh my zsh on macOS

### ISSUE THREAD

**Issue by remsforian** [tmux/tmux#4028]
### Issue description

I am attempting to work on macOS with tmux. I use ohmyzsh for theming and general zsh improvements. It works great most of the time, but I have issues with tmux. When I try to run tmux I get this error:
```
dyld[4197]: Symbol not found: _tiparm_s
  Referenced from: <27D24360-1494-37DC-A874-D054ED06898D> /usr/local/Cellar/tmux/3.4_1/bin/tmux
  Expected in:     <F59A9373-1C86-3CE4-85C0-570FC7075647> /Users/masters1/anaconda3/envs/pacmann/lib/libncursesw.6.dylib
[1]    4197 abort      tmux
```
I do have a workaround where I go into bash to create and attach to my tmux sessions, and inside I can run zsh. This is a new issue, and I was able to use tmux through zsh fine before. 

Thank you for any help

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* `tmux 3.4`
* Platform (`uname -sp`).
* `Darwin i386`
* $TERM inside and outside of tmux (`echo $TERM`).
* outside: xterm-256color
* inside: tmux-256color

**Comment by nicm** [comment]
Seems like your installed ncurses is older than the version tmux was built against. One for your package maintainers?
