### ISSUE TITLE
Bells no longer shown in window flags if monitor-activity is on (2.2 regression)

### ISSUE THREAD

**Issue by orebokech** [tmux/tmux#403]
Hi,

I've tried to reach you on IRC but was unsuccessful, maybe I will have better luck here.

There's a regression in 2.2 caused by commit 98967c5ec97fe: if monitor-activity is on and the window receives a bell, its flags in the status line only show the activity marker, not the bell. In previous versions, you'd get both (i.e. '#!', not just '#'). This is originally Debian bug #823527: https://bugs.debian.org/823527

The bug reporter suggested this patch, which seems ok to me:
https://bugs.debian.org/cgi-bin/bugreport.cgi?filename=bug823527.patch;bug=823527;att=1;msg=40

Thanks,

**Comment by nicm** [comment]
Applied with one minor tweak, thanks!
