### ISSUE TITLE
Featur request: Output rate limiter

### ISSUE THREAD

**Issue by paddor** [tmux/tmux#4031]
(This is by no means anything important or urgent)

In situations like `git add -p`, where the output it sometimes larger, sometimes smaller, it can be hard to visually find the previous prompt to know how large the diff hunk is. I'd like the ouptut to slow down a bit so my eyes can see where the prompt moved to. This should not apply to scrolling.

I've looked into tools like `pv`, but it didn't work:

```gitconfig
[interactive]
    ; diffFilter = delta --color-only
    diffFilter = stdbuf -i0 -o0 -e0 pv -qlL10
```

Since terminals can't know what's command output and what's scrolling, I guess Tmux is the right place for a feature request.

A new feature where the output within a pane can be slowed down, line-wise, would be nice.

**Comment by nicm** [comment]
I think some sort of slow redraw mode would be complex for a feature like this where there are already perfectly adequate ways to solve the problem - for example, you could use `less` and search for the prompt; use the prompt escape sequences for tmux and the `next-prompt` and `previous-prompt` commands in copy mode (or just search for the prompt); or pipe the output to a file and open it in an editor.
