### ISSUE TITLE
Use popups as toast notifcations?

### ISSUE THREAD

**Issue by Garulf** [tmux/tmux#4032]
I have been improving my workflow using tmux's awesome `display-popup` and `display-menu` command. Would it be possible to have an option for a popup menu to not steal focus? This would allow for some cool use cases like toast notifications.

I included some examples below:

![image](https://github.com/tmux/tmux/assets/535299/03f0d353-58ae-4cb7-a180-355d7ca5c119)

![image](https://github.com/tmux/tmux/assets/535299/9caa0019-4978-4c69-9e83-81ce0a6f0ec2)

**Comment by nicm** [comment]
I think it would be possible for popups not to steal key presses from the panes now that they do not block redrawing, but I don't know how difficult it would be. Look at the overlay section in `server_client_handle_key`, I would start by disabling that and see if it works, if it does then you would need to add a flag to say "this is noninteractive overlay".
