### ISSUE TITLE
Add support for `DECRQSS`

### ISSUE THREAD

**Issue by sol** [tmux/tmux#4034]
https://vt100.net/docs/vt510-rm/DECRQSS.html

Personally, I'm only really interested in querying `SGR`

```
printf '\eP$qm\e\\'
```

to probe for truecolor support as per https://github.com/termstandard/colors?tab=readme-ov-file#querying-the-terminal.

This has been requested before in https://github.com/tmux/tmux/issues/2101. The issue was closed as "completed", however:

- `#2101` doesn't show any cross referenced commit that  addressed it.
- [CHANGES](https://github.com/tmux/tmux/blob/master/CHANGES) doesn't seem to mention it.
- It still doesn't seem to work with tmux 3.4.

---

* tmux version: 3.4
* Platform: Linux x64
* $TERM: xterm-256color / tmux-256color

**Comment by nicm** [comment]
Implementing query for SGR wouldn't be terribly difficult because it is entirely internal to tmux. If you want to have a go look at `input_dcs_dispatch` in `input.c`, for existing replies look for `input_reply`.
