### ISSUE TITLE
When started via systemd socket activation, unexport the various `LISTEN_*` variables

### ISSUE THREAD

**Issue by cipriancraciun** [tmux/tmux#4035]
When using `tmux` via `systemd` socket activation, `tmux` should unexport all socket activation related environment variables from the started clients.  (At the moment these seem to be `LISTEN_FDS`, `LISTEN_PID` and `LISTEN_FDNAMES`.)

The issue is that some applications (especially ones that themselves interact with `systemd`, like `podman` in my case) misinterpret these variables and start to act strangely...

I'm using `tmux` `3.3a`, although by looking at the latest code in master, the issue remains present.

Apparently the `systemd` documentation acknowledges this issue, and provides the required functionality, as per the manpage for `sd_listen_fds`:
> `int sd_listen_fds(int unset_environment);`
> [...]
> If the `unset_environment` parameter is non-zero, `sd_listen_fds()` will unset the `$LISTEN_FDS`, `$LISTEN_PID` and `$LISTEN_FDNAMES` environment variables before returning (regardless of whether the function call itself succeeded or not). Further calls to `sd_listen_fds()` will then return zero, but the variables are no longer inherited by child processes.

Thus I believe the following minor patch should solve the issue (I have not tested this):
~~~~patch
int
systemd_create_socket(int flags, char **cause)
{
[...]
	socklen_t		addrlen = sizeof sa;

-	fds = sd_listen_fds(0);
+	fds = sd_listen_fds(1);
	if (fds > 1) { /* too many file descriptors */
[...]
~~~~

Until then, as a workaround one can configure the following in their `tmux.conf` to achieve a similar outcome:
~~~~
set-environment -g -u -- LISTEN_FDNAMES
set-environment -g -u -- LISTEN_FDS
set-environment -g -u -- LISTEN_PID
~~~~

**Comment by nicm** [comment]
OK I can't test this either so I guess it can wait until someone has this problem who can test it.

**Comment by cipriancraciun** [comment]
> OK I can't test this either so I guess it can wait until someone has this problem who can test it.

If you want, I can apply the patch and test it myself.  Would that help?

**Comment by cipriancraciun** [comment]
Just calling `sd_listen_fds(1)` doesn't seem to work, because I believe `tmux` copies the environment much earlier than invoking this function.

For example by hacking the `environ_for_session` to just remove the environment variables (if it was indeed activated via `systemd`) seems to work (I'm using 3.3a as base for this patch):

~~~~patch
diff --git a/compat.h b/compat.h
index 6eb97619..931e7e1d 100644
--- a/compat.h
+++ b/compat.h
@@ -424,6 +424,7 @@ void        *recallocarray(void *, size_t, size_t, size_t);
 #ifdef HAVE_SYSTEMD
 /* systemd.c */
 int         systemd_create_socket(int, char **);
+extern int  systemd_is_activated;
 #endif
 
 #ifdef HAVE_UTF8PROC
diff --git a/compat/systemd.c b/compat/systemd.c
index 7317e43a..f52f084f 100644
--- a/compat/systemd.c
+++ b/compat/systemd.c
@@ -23,6 +23,8 @@
 
 #include "tmux.h"
 
+int systemd_is_activated = 0;
+
 int
 systemd_create_socket(int flags, char **cause)
 {
@@ -31,7 +33,7 @@ systemd_create_socket(int flags, char **cause)
    struct sockaddr_un  sa;
    int         addrlen = sizeof sa;
 
-   fds = sd_listen_fds(0);
+   fds = sd_listen_fds(1);
    if (fds > 1) { /* too many file descriptors */
        errno = E2BIG;
        goto fail;
@@ -46,6 +48,7 @@ systemd_create_socket(int flags, char **cause)
        if (getsockname(fd, (struct sockaddr *)&sa, &addrlen) == -1)
            goto fail;
        socket_path = xstrdup(sa.sun_path);
+       systemd_is_activated = 1;
        return (fd);
    }
 
diff --git a/environ.c b/environ.c
index 74d672e0..1f3bcb37 100644
--- a/environ.c
+++ b/environ.c
@@ -261,6 +261,14 @@ environ_for_session(struct session *s, int no_TERM)
        environ_set(env, "TERM_PROGRAM_VERSION", 0, "%s", getversion());
    }
 
+#ifdef HAVE_SYSTEMD
+   if (systemd_is_activated) {
+       environ_clear(env, "LISTEN_PID");
+       environ_clear(env, "LISTEN_FDS");
+       environ_clear(env, "LISTEN_FDNAMES");
+   }
+#endif
+
    if (s != NULL)
        idx = s->id;
    else
~~~~

**Comment by nicm** [comment]
OK, I think just removing them always if built with systems would be bothering with `systemd_is_activated`.

**Comment by cipriancraciun** [comment]
Always removing the `LISTEN_FD*` environment variables is an option, and I don't see any (obvious) issue.

**Comment by nicm** [comment]
Changed now, thanks!
