### ISSUE TITLE
Tmux session with vim freezes randomly

### ISSUE THREAD

**Issue by vonflynee** [tmux/tmux#404]
I'm experiencing some random freezes when I'm connected to my Archlinux dedicated server, especially when I'm experiencing internet timeouts on my laptop. It's running latest tmux and vim and I'm connected via PuTTY/KiTTY on Windows 10. Ctrl+S,Ctrl+Q nor stty -ixon are not unfreezing the session. Tmux responds to all the commands, e.g. Ctr+B ". After some time tmux unfreezes. It happens few times a day.
How can I fix this?

Thanks in advance,
Mike VonFlynee

**Comment by nicm** [comment]
Try detaching all other clients with C-b D.

**Comment by vonflynee** [comment]
I've tried it many times but it doesn't fixed this issue.

**Comment by nicm** [comment]
Does this still happen with tmux from Git master?

**Comment by vonflynee** [comment]
Switched to Git Master version. I haven't got any freezes so far. I'll reopen this issue when I catch any.
