### ISSUE TITLE
Tmux >=3.3a default colors mess fish shell 3.7 command suggestion - black on black

### ISSUE THREAD

**Issue by silviumc** [tmux/tmux#4044]
### Issue description

The default colors in tmux >=3.3a make the fish shell 3.7 command suggestion invisible with Linux terminal colors. That is black on black, when it's supposed to be dark gray on black. I'll attach screenshots from tmux 3.4 that show the problem and tmux 3.1c that are ok.

Command suggestion in fish shell is an essential feature. I'd say functionality is severely degraded without it.

It's important to mention that suggestion colors work as expected in fish 3.7 without tmux.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.3a or tmux 3.4

* Platform (`uname -sp`)
Linux x86_64 (SUSE Linux Enterprise Server 15 SP6 + updates)

* $TERM inside and outside of tmux (`echo $TERM`).
screen

* Logs from tmux (`tmux kill-server; tmux -vv new`).
Will attach
[tmux_logs.zip](https://github.com/user-attachments/files/16246887/tmux_logs.zip)

![2024-07-16 tmux31c_fish_suggestion](https://github.com/user-attachments/assets/83d39be5-9e8e-4578-adf9-fe653f8d1244)Tmux 3.1c
![2024-07-16 tmux31c](https://github.com/user-attachments/assets/f81671b7-653f-4fe1-9b34-fcc7717934f7)Tmux 3.1c
![2024-07-16 tmux34](https://github.com/user-attachments/assets/872d21c7-a964-4a93-8dc0-82fc0611f753)Tmux 3.4
![2024-07-16 tmux34_fish_suggestion_black_on_black](https://github.com/user-attachments/assets/214059f3-11b3-40cf-a2bb-381885c644ef)Tmux 3.4

**Comment by nicm** [comment]
Does this still happen if you build tmux from Git master?

**Comment by silviumc** [comment]
> Does this still happen if you build tmux from Git master?

Yes, just built it to test this. Same behavior.

**Comment by nicm** [comment]
What happens if you set `TERM` to `xterm-256color` outside tmux or start tmux with `tmux -2`?

**Comment by silviumc** [comment]
> What happens if you set `TERM` to `xterm-256color` outside tmux or start tmux with `tmux -2`?
It's visible, everything is ok with TERM=xterm-256color
![2024-08-05 tmux34TERM=xterm-256color](https://github.com/user-attachments/assets/2302a5f4-4792-4b5c-b8cf-96f282292423)

**Comment by nicm** [comment]
That would be the problem then.

**Comment by silviumc** [comment]
Adding this to /etc/tmux.conf fixes the problem system-wide

`set-option -T 256`

**Comment by nicm** [comment]
Yes that will work if you don't mind breaking colours on any non-256-colour terminal.

**Comment by silviumc** [comment]
What would be the best solution from the perspective of a Linux distribution, so that it works as expected by default? Because I have opened a bug report with the distro before coming here.

**Comment by nicm** [comment]
Whatever terminal you are using needs to set the right TERM by default. It is the terminal's responsibility to set TERM to an entry that correctly describes its capabilities.

**Comment by silviumc** [comment]
Ok, I get it. Maybe it's my particular setup, because I'm forced to use Windows to connect to Linux servers and it goes through putty, then it launches bash, then fish, then tmux. Who knows where it breaks. I have a working solution, I'll leave it at that.

Thank you

**Comment by nicm** [comment]
You can probably configure putty to set xterm-256color (it probably sets xterm by default) and then just make sure you don't change it in your shell profiles.

**Comment by silviumc** [comment]
The value of TERM is configurable in PuTTY, I'm putting it up a screenshot so that it's useful for anyone landing here from a search. It fixes the fish autosuggestion color in Tmux.
![image](https://github.com/user-attachments/assets/ecbc03a6-bf7a-4fbc-944b-272dbb9b390c) PuTTY Connection/Data/Terminal-type string
