### ISSUE TITLE
tmux keeps duplicating users on ssh server

### ISSUE THREAD

**Issue by F0RCAD31T0R** [tmux/tmux#4045]
I’m running arch Linux on my server and every time I rejoin the server a new user gets created. When typing uptime command it adds 1 user to the count, meanwhile the users command actually shows the correct users, it’s been very frustrating since I want to really fix this for viewing who’s truly logged in

**Comment by nicm** [comment]
Hard to know what you are looking at but at a guess try building tmux without utempter.

**Comment by F0RCAD31T0R** [comment]
I guess it was just problem of my miner (xmrig) it kept launching and
making users and it also made my server crash, gladly fixed this by just
making the miner a systemd service, and running the logs in a tmux just
seems to work fine now. But the miner I had it running with sudo and I
hadn’t built it, just downloaded it with my package manager.
