### ISSUE TITLE
[Question] Copy Mode Auto Scroll Down Stops When Cursor Hits Status Bar

### ISSUE THREAD

**Issue by denppa** [tmux/tmux#4047]
### Issue description

When I try to copy text, and need to scroll downwards in copy mode, the auto scrolling stops once the cursor hits the menu bar. It is a rather precise operation to keep the mouse right between the auto scroll threshold and status bar.

Is this the intended behavior? For example, iTerm2 continues to scroll even if the mouse exceeds the pane / window border. If it is intended, is there a config line to just keep it scrolling down even if the mouse hits the status bar or goes out of bounds?

Thank you.

### Required information

Please provide the following information:

* tmux version: "tmux3.4".
* Platform: "Darwin arm"
* $TERM inside: "tmux-256color"
* $TERM outside: "xterm-256color"

**Comment by nicm** [comment]
Try this please: 
[x.diff.txt](https://github.com/user-attachments/files/16486998/x.diff.txt)
