### ISSUE TITLE
Way to automate update content of tmux clipboard buffer

### ISSUE THREAD

**Issue by jrmd54** [tmux/tmux#4048]
Hello,

I work on multiple Linux servers that each run without using an X server.
To have a shared clipboard buffer that I can 'copy to' / 'paste from' by using bash/vim function calls, I use an OSC52 wrapper.

It allows me to e.g. do:
local> `echo foo | osc_copy`
remote> `bar=$(osc_paste)`

It works well except when my ssh sessions are ran from a local tmux instance.

The following points illustrate my problem:
1 - local>  I launch tmux from my terminal, then ssh on a remote server.
2 - remote (inside the tmux pane)>  I use OSC52 to copy the string 'foo' (which is successfully stored in my local clipboard)
3 - local> From e.g Firefox I Ctrl+C the string 'bar'
4 - remote (inside the tmux pane)> I use OSC52 to paste the clipboard content: 'foo' is copied instead of 'bar'

By searching on the net the source of the issue, I came across this [blog post](https://kalnytskyi.com/posts/on-tmux-osc52-support/) saying that the problem comes from the internal buffer used by tmux, which is not automatically updated during the above step 3 and needs the following to be manually typed on the tmux panel:
`C-b : refresh-client -l`

Having to manually type that command each time I want to sync my clipboard with tmux's buffer is really cumbersome and I would like to automatize that.

From what I have found by reading the documentation I thought of 2 possible solutions, but I failed to make them work properly:

**Solution 1**:
Cf this  [thread](https://serverfault.com/questions/734180/send-tmux-command-from-remote-inside-ssh-session-to-local-instance), I should be able to run:
1 - local> Start tmux with command
    `tmux -L foo`
2 - remote> Connect to the remote server by using the command
    `ssh -R/tmp/tmux-$UID/default:/tmp/tmux-${REMOTE_UID}/default remote`
3 - remote> Update local tmux buffer by using command
    `tmux -L default send-key C-b : refresh-client -l Enter`
The command in above step 3 could be automatically called before accessing clipboard with OSC52 on remote... but I must be doing something wrong as it does not work.

**Solution 2**:
Use tmux hooks; e.g. by adding the line
`set-hook -g pane-set-clipboard 'refresh-client -l'`
in my local .tmux.conf file; each time I copy something using OSC52 in tmux, the buffers of all my running tmux sessions are updated.
The problem is that the above hook event is not triggered if I copy something with Ctrl-C from outside of tmux, e.g. Firefox.
I tried all tmux hook events, but I could not find one that for example is triggered each time a key is typed in a tmux session (which would have solved the problem).

I admit that I am a little stuck, is what I want to do even possible?

My configuration is the following:
- term: alacritty vers. _0.13.2_, with config:
```
    terminal.osc52 = "copypaste"
    env.TERM = "xterm-256color"
```
- tmux 3.3a, with config:
```
    set -g default-terminal "xterm-256color"
    set -g set-clipboard on
    set-window-option -g allow-passthrough on
```
The command uname -sp && tmux -V && echo $TERM outputs:
    Linux x86_64
    tmux 3.3a
    xterm-256color

Thank you very much for your insights.

**Comment by nicm** [comment]
There is nothing that tells tmux when a copy has taken place outside tmux so there is no way for it to update automatically.

**Comment by jrmd54** [comment]
Hum i am trying a different approach...
The idea is to listen to changes of clipboard content in my host by using [clipnotify](https://github.com/cdown/clipnotify).

The problem i now have is to make refresh-client -l works when called from outside of the active session.
Running any of the following commands from another terminal on the host doesn't do anything:
`tmux refresh-client -l   # trying simple command`
`tmux refresh-client -t <client>  # trying command with every value given with tmux list-clients command`
`tmux refresh-client  -l <session>:<window>.<pane>  # trying command with every combination  `
`tmux refresh-client -t <client> -l <session>:<window>.<pane> `

Do you have any idea of what these commands are missing to achieve the same result as running `C-b: refresh-client -l` from within the running tmux session?

**Comment by cenk1cenk2** [comment]
I do use the tmux clipboard mechanism on the remote machine and everything is propagating through `osc52` correctly, I was looking for a similar hook if we had some hook like `before-save-buffer` to call this `run-shell tmux refresh-client -l` to refresh the clipboard that would be very nice. But since by design `tmux refresh-client -l` returns the result of the `osc52` to the terminal, that also needs to be able to go silent (maybe with a flag) if that can even work.

**Comment by jrmd54** [comment]
Hello,

Since i could not get `refresh-client -l` to work when called from the outside, i tried to update tmux's source code to add a new hook that trigger events before a paste.

i.e.  my conf file now has
`set-hook -g pane-beforepaste-clipboard 'refresh-client -l' `
and options-table.c has the added line
`+ OPTIONS_TABLE_PANE_HOOK("pane-beforepaste-clipboard", "")`

At first i tried to fire the hook directly in the function
static void input_osc_52(struct input_ctx *ictx, const char *p)  // input.c
by adding the line
```
	 if (strcmp(end, "?") == 0) {
     +         notify_pane("pane-beforepaste-clipboard", wp);
               if ((pb = paste_get_top(NULL)) != NULL)
```
but since the callback is added to the cmdq, the clipboard buffer is updated _after_ the paste, which is not great.

What did work was to instead put the notify_pane() call at the beginning of the function
static void input_parse(struct input_ctx *ictx, u_char *buf, size_t len)  // input.c
i.e.
```
input_parse(struct input_ctx *ictx, u_char *buf, size_t len)
    {
+           notify_pane("pane-beforepaste-clipboard", ictx->wp);
	    struct screen_write_ctx		*sctx = &ictx->ctx;
```

What is unclean is that the hook is now fired too often to be called 'beforepaste' (maybe 'pane-input'?).
Is having a generic 'input' hook compatible with tmux's design, or is there a more specific place where this hook can be put?

(Albeit not very clean, I also tried to directly fire the event without adding it to the cmdq, without success)

**Comment by nicm** [comment]
We are not going to add a hook before any input from any pane.

**Comment by jrmd54** [comment]
yes i talked too quickly, this is ugly..

**Comment by nicm** [comment]
You could bind another key to paste with a small delay, something like:
````
bind C-p { refresh-client -l; run -d0.5; paste-buffer; delete-buffer }

**Comment by dante0624** [comment]
Hey @nicm, thanks for this suggestion. I personally was trying to achieve the same effect as @jrmd54, where `refresh-client -l` is invoked automatically for me whenever I want to paste. I specifically wanted this to make OSC52 work nicely with tmux and neovim. I finally managed to get this to work by modifying your command slightly to be:

```
bind-key -T root C-p { refresh-client -l; run -d0.2; send-keys C-p}
```

I use C-p for pasting in neovim, and setting up my tmux config with this line just works. Commenting this for visibility, and in case anyone has a suggestion for improving on this
