### ISSUE TITLE
tmux overrides bindings set by the terminal emulator

### ISSUE THREAD

**Issue by 097115** [tmux/tmux#4050]
### Issue description

I use Kitty terminal (just in case, it's also reproducible in xterm), and have the following binding set in Kitty's config:

    map shift+enter        send_text all \x1b[31~

So that when I run `cat` in the terminal session, pressing `<S-CR>` indeed returns `^[[31~`.

Now, locally, on Ubuntu 22.04.04, it works as intended both inside and outside tmux. However, when I ssh to a remote AlmaLinux 8.10, outside tmux it still works OK (pressing `<S-CR>` sends `^[[31~` to the terminal) but **inside** tmux it starts to send `^[[18;2~`. 

Of course, both machines share exactly the same configuration files both for the shell and for tmux (happens without the config, too).

And, yes, I understand that this is probably not exactly tmux's *problem* but may be you could help me with some hint? Why doesn't it happen on one machine, and yet happens on another? Some terminfo related differences? Or what else could be the problem?

### Required information

* tmux version (`tmux -V`): tmux next-3.5 (latest master)
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`):
  - outside: xterm-256color
  - inside: tmux-256-color

**Comment by nicm** [comment]
`^[[31~` is `S-F7`. tmux uses xterm sequences for modified function keys so this is `^[[18;2~`.

If you want it to send something different you can bind `S-F7` to `send-keys`, or pick another sequence for `S-Enter` that is not already in use for another key.

**Comment by 097115** [comment]
> `^[[31~` is `S-F7`. tmux uses xterm sequences for modified function keys so this is `^[[18;2~`

@nicm, Thanks, expected something like this.

Why does it work locally, though? It really shouldn't, right?

**Comment by nicm** [comment]
Are you sure it's the same tmux version?

**Comment by 097115** [comment]
@nicm, right now both machines run the current latest master (have just updated the local installation, killed all the running instances and relaunched, it does return `^[[31~` inside and outside tmux).

Also, on a side note, locally it works for quite some time already. I'd say, at least back to tmux next-3.4, maybe earlier...

**Comment by nicm** [comment]
Is TERM the same outside tmux? Maybe it changed S-F7.

**Comment by 097115** [comment]
`$TERM` is the same, too, `xterm-256color` outside, `tmux-256color` inside. No custom terminfo files, same (git synced) configs for bash, tmux :)

**Comment by nicm** [comment]
Show tmux server logs from pressing the key with both working and not working.

**Comment by 097115** [comment]
@nicm, Sorry for the delay...

  - [Working](https://0x0.st/s/i9H-reNGmFmuI2tO4IiSdw/Xpj4.log)
  - [Non-working](https://0x0.st/s/iyDHGUpBtr7EAusgrlZzyg/Xpjy.log)

**Comment by nicm** [comment]
Configs are not the same at all? The working one has `user-keys` set and the not working does not:
~~~~
... set-option -s user-keys[1] \\033[31~ ;; bind-key -n User1 send-keys Escape [31~ ...

**Comment by 097115** [comment]
@nicm,

Oh, shit, sorry! Please, pardon me for wasting your time :(

Thanks! And sorry again :(

**Comment by nicm** [comment]
No worries.
