### ISSUE TITLE
Change suggestion, update format of option array without subscript to produce all values

### ISSUE THREAD

**Issue by johnfb** [tmux/tmux#4051]
### Description

Currently, formating an array option such as:
```
$ tmux display -p '#{update-environment}'
```
will display nothing.

I suggest that this behavior be changed to display all the values of the array when a subscript is absent for an option array.
It would be additionally convenient if the output was suitable for passing back to `set-option` to produce the same result.

### Additional details

In an attempt to play around with the viability of this idea, I made the following edit as a possible solution (updated from [commment](https://github.com/tmux/tmux/issues/4051#issuecomment-2243076698)) [show-array.diff.txt](https://github.com/user-attachments/files/16335803/show-array.diff.txt):
```diff
diff --git a/options.c b/options.c
index fef5637e..31a45ba4 100644
--- a/options.c
+++ b/options.c
@@ -578,10 +578,29 @@ char *
 options_to_string(struct options_entry *o, int idx, int numeric)
 {
 	struct options_array_item	*a;
+	char				*result = NULL;
+	char				*last = NULL;
+	char				*next;
 
 	if (OPTIONS_IS_ARRAY(o)) {
-		if (idx == -1)
-			return (xstrdup(""));
+		if (idx == -1) {
+			RB_FOREACH(a, options_array, &o->value.array) {
+				next = options_value_to_string(o, &a->value, numeric);
+				if (last == NULL) {
+					result = next;
+				} else {
+					xasprintf(&result, "%s %s", last, next);
+					free(last);
+					last = NULL;
+					free(next);
+					next = NULL;
+				}
+				last = result;
+			}
+			if (result == NULL)
+				return (xstrdup(""));
+			return result;
+                }
 		a = options_array_item(o, idx);
 		if (a == NULL)
 			return (xstrdup(""));
```
when compiled, I performed the following test running as `tmux -L testing -f/dev/null`:
```
$ ./build/local/tmux/tmux show-option -g update-environment
update-environment[0] DISPLAY
update-environment[1] KRB5CCNAME
update-environment[2] SSH_ASKPASS
update-environment[3] SSH_AUTH_SOCK
update-environment[4] SSH_AGENT_PID
update-environment[5] SSH_CONNECTION
update-environment[6] WINDOWID
update-environment[7] XAUTHORITY
$ ./build/local/tmux/tmux display -vp '#{update-environment}'
# expanding format: #{update-environment}
# found #{}: update-environment
# format 'update-environment' found: DISPLAY KRB5CCNAME SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY
# replaced 'update-environment' with 'DISPLAY KRB5CCNAME SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY'
# result is: DISPLAY KRB5CCNAME SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY
DISPLAY KRB5CCNAME SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY
$ for val in $(./build/local/tmux/tmux display -p '#{update-environment}'); do echo "${val}"; done
DISPLAY
KRB5CCNAME
SSH_ASKPASS
SSH_AUTH_SOCK
SSH_AGENT_PID
SSH_CONNECTION
WINDOWID
XAUTHORITY
$ ./build/local/tmux/tmux set-option -g update-environment "$(./build/local/tmux/tmux display -p '#{update-environment}') DBUS_SESSION_BUS_ADDRESS"
$ ./build/local/tmux/tmux show-option -g update-environment
update-environment[0] DISPLAY
update-environment[1] KRB5CCNAME
update-environment[2] SSH_ASKPASS
update-environment[3] SSH_AUTH_SOCK
update-environment[4] SSH_AGENT_PID
update-environment[5] SSH_CONNECTION
update-environment[6] WINDOWID
update-environment[7] XAUTHORITY
update-environment[8] DBUS_SESSION_BUS_ADDRESS
```

### Thoughts

- Why might this be a bad idea?
- Any changes to the diff to be conformant to project styles and guidelines?
- Is there a different better approach? In a shell script `tmux show-option -v` is sufficient, but this does not provide the functionality for formats.

**Comment by nicm** [comment]
I think this is a good idea and it looks fine. Can you remove the {}s around single-line blocks, so this:
~~~~
+                       if (result == NULL) {
+                               return (xstrdup(""));
+                       } else {
+                               return result;
+                       }
~~~~
Becomes:
~~~~
if (result == NULL)
    return (xstrdup(""));
return result;
~~~~
Also there is no need to initialize or assign `next` to `NULL` since it is replaced every time in the loop.

**Comment by johnfb** [comment]
I have edited the diff in the description above to remove the unnecessary {} around single-line blocks, else clause, and initialization.

Should I make a merge request or something? I don't mind someone else committing it, whatever is easiest.

**Comment by johnfb** [comment]
Attachment made [show-array.diff.txt](https://github.com/user-attachments/files/16335803/show-array.diff.txt)

Thank you, let me know if there are any issues.

**Comment by nicm** [comment]
This looks OK, thanks - if you want to be credited in the commit message please give me your real name or email address otherwise I will just mention the issue number.

**Comment by johnfb** [comment]
Just mentioning the issue is fine with me.
