### ISSUE TITLE
Right-Shift + Mouse Won't Mark Text For Clipboard

### ISSUE THREAD

**Issue by rracb** [tmux/tmux#4052]
Only line in /usr/local/etc/tmux.conf
'set -g mouse on'

Hold down Left-Shift and can use mouse to mark text to clipboard for pasting on external app. Holding Right-Shift doesn't do the same. I'm a left-handed mouse person so Right-Shift would be more normal. (Specifically using Bitvise ssh client on Windows 11 machine to access FreeBSD v13.3p4 server. Writing clipboard text to Notepad++. Same behavior with PuTTY)

Shown below is latest version available to me via FreeBSD packages.

	tmux 3.3a
	FreeBSD amd64
	tmux-256color
	xterm-256color

[tmux-client-3010.log](https://github.com/user-attachments/files/16339491/tmux-client-3010.log)
[tmux-out-3012.log](https://github.com/user-attachments/files/16339492/tmux-out-3012.log)
[tmux-server-3012.log](https://github.com/user-attachments/files/16339493/tmux-server-3012.log)

Thank you.

**Comment by nicm** [comment]
The mouse sequences do not distinguish left and right shift to tmux so this is something you would need to configure at the terminal.
