### ISSUE TITLE
tmux pane-focus-in hook does not work under ssh

### ISSUE THREAD

**Issue by pinkfrog9** [tmux/tmux#4053]
### Required information

Please provide the following information:

* tmux version (`tmux -V`):  tmux3.3a
* Platform (`uname -sp`). Debian

## How to reproduce:
- I open iterm2 (mac) and ssh to a remote debian machine.  
- I run tmux on the debian machine.
- I run the following code:
```
tmux set-hook -g pane-focus-in 'display-message "Pane focused"'
```
- I switch focus between different tmux panes and also between different mac apps too.

## Expected behavior:
the above "Pane focused" message is shown.

## Real behavior:
**No message was displayed.**

Note that if I omit the ssh-to-the-remote-machine step and run tmux locally on my mac, hooks was correctly triggered.

I also tried sshing to the remote machine, but didn't launch tmux, instead I directly run emacs there. Emacs is able to catch the focus event too.

**Comment by nicm** [comment]
No logs.
