### ISSUE TITLE
cannot unbind Enter

### ISSUE THREAD

**Issue by tessus** [tmux/tmux#4056]
### Issue description

It is impossible to unbind `Enter` in the prefix table. 

Whenever I press `prefix Enter`, the action for `prefix C-m` is triggered (toggle mouse support). When I list the keys, only Enter shows up and `C-m` is not even in the list:

```
$ tmux lsk |grep -E "Enter|C-m"
bind-key    -T copy-mode-vi Enter                  send-keys -X copy-pipe-and-cancel
bind-key    -T prefix       Enter                  set-option mouse \; display-message "mouse -> #{?mouse,on,off}"
```

tmux config:
```
unbind C-b
set -g prefix C-a
unbind-key Enter
unbind-key C-m
bind-key -N 'Toggle mouse helper' C-m set-option mouse \; display-message 'mouse -> #{?mouse,on,off}'
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.4
* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`). inside: tmux-256color , outside: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-server-90473.log](https://github.com/user-attachments/files/16399030/tmux-server-90473.log)
[tmux-client-90471.log](https://github.com/user-attachments/files/16399031/tmux-client-90471.log)
[tmux-out-90473.log](https://github.com/user-attachments/files/16399032/tmux-out-90473.log)

**Comment by nicm** [comment]
Enter and C-m are the same key, see here: https://github.com/tmux/tmux/wiki/Modifier-Keys#limitations-of-ctrl-keys

**Comment by tessus** [comment]
Thanks
