### ISSUE TITLE
Tmux showing no session even tho session is still running

### ISSUE THREAD

**Issue by HakaishinShwet** [tmux/tmux#4057]
```
ps aux | grep tmux

u224   1985  0.0  0.0  16792  2248 pts/19   S+   09:35   0:00 grep --color=auto tmux
u224   4892  0.3  0.0  40056  8772 ?        Ss   02:13   1:21 tmux
u224  10207  0.0  0.0  42048  7908 ?        Ss   Jul22   0:50 tmux new-session -s my_session
u224  19681  0.0  0.0  39140  6480 ?        Ss   Jul20   0:01 tmux new-session -s my_session
```
```
tmux attach -t my_session

no sessions

```

```
tmux -S /tmp/tmux-$(id -u)/default ls

no server running on /tmp/tmux-227009/default
```
```
ls -l /tmp/tmux-$(id -u)/
total 0
srw-rw---- 1 u224942 u224942 0 Jul 27 09:36 default
```

I did left my session running in tmux and it is running i know because i can access one project which i made publicly accessible inside it but when i try to attach to it or use tmux ls no session shown plus i used gpt to get more idea and used some commands for getting more info about this and sharing above. I dont know if its bug or not but if it is then i request you to look into this matter.

Thankyou very much for this awesome project

**Comment by nicm** [comment]
Send SIGUSR1 to tmux to make it recreate the socket https://github.com/tmux/tmux/wiki/FAQ#tmux-says-no-sessions-when-i-try-to-attach-but-i-definitely-had-sessions

**Comment by HakaishinShwet** [comment]
@nicm thank you very much this resolved my issue :-)). Maybe in future if tmux can autocheck if file deleted from /tmp and recreate socket connection then it would great
