### ISSUE TITLE
 Highlighted text not visible in tmux during msfconsole search

### ISSUE THREAD

**Issue by darkvpier** [tmux/tmux#4060]
## Issue description

I'm experiencing an issue where highlighted text during search in msfconsole is not visible when using tmux. It is not limited to Metasploit Framework (msfconsole) but for various tools like the linpeas script.

## Required information

Please provide the following information:

* tmux 3.4
* `uname -av`: `Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux`
* `echo $TERM`: `tmux-256color`
* Default tmux Config
* qterminal `1.4.0`
* Metasploit Framework Version: `6.4.18-dev`

## To reproduce the issue:
```
sudo msfconsole
search smbv3
```
### Expected:
The search results with highlighted matches should be displayed within the tmux pane.
![image](https://github.com/user-attachments/assets/db7d6424-7d51-498d-a4fe-01aebc95374d)

### Error in tmux:
The search results are displayed, but the highlighted text for matches is not visible.
![image](https://github.com/user-attachments/assets/144bb2ff-e65e-41df-af88-835feffe5b43)

**Comment by nicm** [comment]
Logs?
