### ISSUE TITLE
broken behavior with named paste buffers

### ISSUE THREAD

**Issue by habys** [tmux/tmux#4061]
### Issue description

If _all_ of the paste buffers are named, several functions do not function correctly.
  1) pasting
  2) `choose-buffer`
  3) `delete-buffer`

`list-buffer` appears to work correctly.

To reproduce:

* create a new tmux session.
* create any number of named buffers eg:

```
tmux loadb -b test <(echo hi)
tmux loadb -b test2 <(echo hi2)
```

Now the listed behaviors above will not function.
If you open the `choose-buffer` menu, any key press closes the menu without action.
Paste does not paste.
`delete-buffer` says: no buffer

I've tested this without a .tmux.conf.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

I have observed this behavior since

[020c403dff56269d93625970ed41761520afc853] When picking a buffer because one isn't specified by the user, ignore named buffers. GitHub issue 3212 from David le Blanc.

to the latest commit at this time of writing this (109d2bda1a7b06948e35b7e08c159e71ebc988fb Mon Jul 22 18:01:09 2024 +0100)

* Platform (`uname -sp`).

Linux amd64 / OpenBSD amd64

* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

foot / tmux-256color
alacritty / tmux-256color
xterm / tmux-256color

**Comment by habys** [comment]
[tmux-out-856034.log](https://github.com/user-attachments/files/16415358/tmux-out-856034.log)
[tmux-server-856034.log](https://github.com/user-attachments/files/16415359/tmux-server-856034.log)
[tmux-client-856032.log](https://github.com/user-attachments/files/16415360/tmux-client-856032.log)

**Comment by nicm** [comment]
This will fix buffer mode:
~~~~
diff --git a/window-buffer.c b/window-buffer.c
index e2c36ed4..0b4b364c 100644
--- a/window-buffer.c
+++ b/window-buffer.c
@@ -508,7 +508,7 @@ window_buffer_key(struct window_mode_entry *wme, struct client *c,
        struct window_buffer_itemdata   *item;
        int                              finished;

-       if (paste_get_top(NULL) == NULL) {
+       if (paste_is_empty()) {
                finished = 1;
                goto out;
        }
@@ -541,7 +541,7 @@ window_buffer_key(struct window_mode_entry *wme, struct client *c,
        }

 out:
-       if (finished || paste_get_top(NULL) == NULL)
+       if (finished || paste_is_empty())
                window_pane_reset_mode(wp);
        else {
                mode_tree_draw(mtd);
~~~~
I think the intent was that manually created buffers should never be chosen automatically by commands - the user needs to explicitly as for them. But I'm not sure that is ideal for `paste-buffer` and friends...
