### ISSUE TITLE
Cursor shape of terminal is reverted back to block after exiting tmux session

### ISSUE THREAD

**Issue by huongng** [tmux/tmux#4062]
* tmux version: tmux 3.4
* Platform: Darwim arm
* $TERM (outside): xterm-256color, (inside) tmux-256color

I'm using iTerm2 with tmux on OSX. I have configured my iTerm2 cursor shape to be an underline, and when I get to a tmux session, it'll be an underline. However, when I enter and exit vim then use the tmux command prompt to either detach or exit the tmux session, my cursor shape will be reverted back to a block shape.

In terminal:
<img width="310" alt="Screenshot 2024-08-01 at 11 34 16 AM" src="https://github.com/user-attachments/assets/4004642e-afad-4dec-93c9-b691541ebf9a">

Enter tmux:
<img width="231" alt="Screenshot 2024-08-01 at 11 34 33 AM" src="https://github.com/user-attachments/assets/f37abe06-7511-42e9-8467-c724d848ea51">

Enter neovim:
<img width="318" alt="Screenshot 2024-08-01 at 11 38 40 AM" src="https://github.com/user-attachments/assets/9cd55013-2966-4e70-9f81-4e2e3029f0f3">

Exit tmux:
<img width="246" alt="Screenshot 2024-08-01 at 11 34 46 AM" src="https://github.com/user-attachments/assets/2ac936b5-4535-4d4c-958e-6f6a9c829542">

In terminal:
<img width="205" alt="Screenshot 2024-08-01 at 11 35 48 AM" src="https://github.com/user-attachments/assets/acc48afe-bc5a-48cd-b2df-e3a53b3c54c9">

Here's my neovim config:
```
vim.cmd([[
  au VimEnter,VimResume * set guicursor=i-c-ci-ve:hor25,n-v-sm:block25,r-cr:hor20,o:hor50
    \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
    \,sm:block25-blinkwait175-blinkoff150-blinkon175

  au VimLeave * set guicursor=a:hor25-blinkon1
 ]])
```

**Comment by nicm** [comment]
tmux emits `Se` which defaults `\033[2 q` on exit to restore the cursor shape. You can change this with the `terminal-overrides` option:
~~~~
set -as terminal-overrides '*:Se=\e[1 q'

**Comment by kaiguang** [comment]
> tmux emits `Se` which defaults `\033[2 q` on exit to restore the cursor shape. You can change this with the `terminal-overrides` option:
> 
> ```
> set -as terminal-overrides '*:Se=\e[1 q'
> ```

Thank you so much @nicm , was spending hours yesterday trying to fix my cursor style.
