### ISSUE TITLE
Can `list-keys` generate a valid config with notes?

### ISSUE THREAD

**Issue by milesfrain** [tmux/tmux#4063]
## Issue:

`list-keys` cannot generate a valid config while also preserving keybinding notes. The two options are:
- `list-keys` prints a valid config with notes stripped out.
- `list-keys -N` prints notes only, which is not a valid config.

I tested this on both `3.2a` and the latest commit at `109d2bda1a`.

Here are some examples which springboard off of the [wiki](https://github.com/tmux/tmux/wiki/Getting-Started#key-bindings) (printing just the `prefix` key-table).

#### Existing valid config with notes omitted:
```
$ tmux lsk -Tprefix
bind-key    -T prefix C-b     send-prefix
bind-key    -T prefix C-o     rotate-window
...
```

#### Existing invalid config with notes included:
```
$ tmux lsk -Tprefix -N
C-b     Send the prefix key
C-o     Rotate through the panes
...
```

## Proposal

Proposing `list-keys` be modified to preserve notes. That would change the first snippet to:
```
$ tmux lsk -Tprefix
bind-key -N 'Send the prefix key'       -T prefix C-b     send-prefix
bind-key -N 'Rotate through the panes'  -T prefix C-o     rotate-window
...
```

This output is more verbose, but it seems like that was the original plan https://github.com/tmux/tmux/issues/2000#issuecomment-561259577:
> One problem is that list-keys should be valid if copied into a config file and it will become very cluttered if it has a long help string as one of the arguments, although I suppose there is no avoiding that.

Some other implementation options:
- Require a new flag to output a valid config with notes, for example `-A`. That would avoid breaking any existing workflows which rely on the default notes-omitted behavior.
- Move notes column farther to the right (e.g. after the key-table column) for cleaner alignment.

I'd be happy to implement this change.

**Comment by milesfrain** [comment]
Sharing additional context on how I ran into this issue.

A popular strategy for enabling live modification of configs without restarting tmux is to source the output of `list-keys` after clearing all bindings. Here's one example from a stackoverflow thread:
```sh
# Unbind ALL keybindings whilst REBINDING defaults
run-shell '\
    export f=$(mktemp) \
    && tmux -f /dev/null -L temp start-server \; list-keys > $f \
    && tmux unbind -a \; source-file $f'
```
https://unix.stackexchange.com/questions/57641/reload-of-tmux-config-not-unbinding-keys-bind-key-is-cumulative

One gotcha with this strategy is that `PREFIX ?` becomes a no-op because it is bound to `list-keys -N`, which only displays bindings with notes. Since notes are stripped out, `PREFIX ?` and `list-keys -N` display nothing.

One workaround is to simply change the default `?` binding from `list-keys -N` to `list-keys` (as it was pre-`3.1`) and ignore the new notes feature entirely. But this notes feature is nice, and so I'd like to keep the notes and enjoy the newer more human-readable help text.

On a related note, I'd like to promote the proposal in #729 which requests a built-in way to restore stock bindings. I'd comment or upvote there, but the issue is locked. I believe there are a fair number of users who would appreciate that feature, as it would likely be more robust than existing workarounds. I'd also be up for doing the implementation work if it's something that would be well-received.

**Comment by nicm** [comment]
I am OK with flags to `list-keys` to include `-N` in the command output and to `unbind-key` to reset to the default key bindings if you want to open a PR.

**Comment by milesfrain** [comment]
It looks like there's been a regression where `list-keys` no longer outputs a fully valid config on `master`. All lines were valid on `3.2a`, and there are now 6 failing lines on `master`. Perhaps it's an escaping issue. I think we should fix this before adding the notes column. I'll look into it after adding the `unbind-keys -R` reset feature. LMK if you see an obvious fix for these lines.

These are the broken lines on `master`:
```
bind-key    -T copy-mode    C-r command-prompt -i -I "#{pane_search_string}" -T search -p "(search up)" { send-keys -X search-backward-incremental "%%" }
bind-key    -T copy-mode    C-s command-prompt -i -I "#{pane_search_string}" -T search -p "(search down)" { send-keys -X search-forward-incremental "%%" }
bind-key    -T copy-mode-vi /   command-prompt -T search -p "(search down)" { send-keys -X search-forward "%%" }
bind-key    -T copy-mode-vi ?   command-prompt -T search -p "(search up)" { send-keys -X search-backward "%%" }
bind-key    -T prefix       \'  command-prompt -T window-target -p index { select-window -t ":%%" }
bind-key    -T prefix       .   command-prompt -T target { move-window -t "%%" }
```

Here are the corresponding working lines on `3.2a`:
```
bind-key -T copy-mode    C-r command-prompt -i -I "#{pane_search_string}" -p "(search up)" "send -X search-backward-incremental \"%%%\""
bind-key -T copy-mode    C-s command-prompt -i -I "#{pane_search_string}" -p "(search down)" "send -X search-forward-incremental \"%%%\""
bind-key -T copy-mode-vi /   command-prompt -p "(search down)" "send -X search-forward \"%%%\""
bind-key -T copy-mode-vi ?   command-prompt -p "(search up)" "send -X search-backward \"%%%\""
bind-key -T prefix       \'  command-prompt -W -p index "select-window -t ':%%'"
bind-key -T prefix       .   command-prompt -T "move-window -t '%%'"
```

**Comment by nicm** [comment]
I do not see that, the entire output of `lsk` works for me, including those lines.
