### ISSUE TITLE
Blockcursor on the Linux console

### ISSUE THREAD

**Issue by rkta** [tmux/tmux#4064]
Note: I tried posting this to the ML, but my mail was rejected, probably because I'm not subscribed - but I don't find any instructions on how to subscribe. That's why I post it here.

I have trouble keeping my block cursor when using tmux on the Linux
console.

My TERM is 'linux' before starting tmux. When I start tmux with 'tmux'
or with 'tmux -L foo -f /dev/null' the cursor is reset to an underscore
and using "echo -e '\033[?8c'" does show no effect anymore.

Currently I set TERM to 'tmux' before starting tmux to work around it.
This is on Debian Stable with tmux next-3.5 build from 109d2bda
(2024-07-22).

Can I do anything to let tmux keeping my blockcursor?

**Comment by nicm** [comment]
Does this change the cursor outside tmux:
~~~~
printf '\033[2 q'
~~~~

**Comment by rkta** [comment]
On Sun, Aug 04, 2024 at 01:18:34AM -0700, Nicholas Marriott wrote:
> Does this change the cursor outside tmux:
> ~~~~
> printf '\033[2 q'
> ~~~~

No.

**Comment by nicm** [comment]
Something in the `linux` terminfo entry must be causing it to reset. What sequence do you use to set the cursor? Look at `infocmp linux` for anything that changes it back.

**Comment by rkta** [comment]
On Sun, Aug 04, 2024 at 01:41:59AM -0700, Nicholas Marriott wrote:
> Something in the `linux` terminfo entry must be causing it to reset.
> What sequence do you use to set the cursor?

'\033[?6c'

> Look at `infocmp linux` for anything that changes it back.

I did have a look, but I'm not sure what I'm looking for. I tried
echoing some sequences that end with a 'c', but other than
cnorm=\E[?25h\E[?0c nothing did change my cursor back. And AFAIU cnorm
is the sequences meant to reset the cursor.

Any pointers for I should be looking?

Here is the output of infocmp linux:
#	Reconstructed via infocmp from file: /lib/terminfo/l/linux
linux|Linux console,
	am, bce, ccc, eo, mir, msgr, xenl, xon,
	colors#8, it#8, ncv#18, pairs#64,
	acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, civis=\E[?25l\E[?1c,
	clear=\E[H\E[J, cnorm=\E[?25h\E[?0c, cr=\r,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?25h\E[?8c, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
	dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
	el1=\E[1K, enacs=\E)0, flash=\E[?5h$<200/>\E[?5l,
	home=\E[H, hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
	ich1=\E[@, il=\E[%p1%dL, il1=\E[L, ind=\n,
	initc=\E]P%p1%x%p2%{255}%*%{1000}%/%02x%p3%{255}%*%{1000}%/%02x%p4%{255}%*%{1000}%/%02x,
	kb2=\E[G, kbs=^?, kcbt=\E^I, kcub1=\E[D, kcud1=\E[B,
	kcuf1=\E[C, kcuu1=\E[A, kdch1=\E[3~, kend=\E[4~, kf1=\E[[A,
	kf10=\E[21~, kf11=\E[23~, kf12=\E[24~, kf13=\E[25~,
	kf14=\E[26~, kf15=\E[28~, kf16=\E[29~, kf17=\E[31~,
	kf18=\E[32~, kf19=\E[33~, kf2=\E[[B, kf20=\E[34~,
	kf3=\E[[C, kf4=\E[[D, kf5=\E[[E, kf6=\E[17~, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\E[1~, kich1=\E[2~,
	kmous=\E[M, knp=\E[6~, kpp=\E[5~, kspd=^Z, nel=\r\n, oc=\E]R,
	op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM, rmacs=^O,
	rmam=\E[?7l, rmir=\E[4l, rmpch=\E[10m, rmso=\E[27m,
	rmul=\E[24m, rs1=\Ec\E]R, sc=\E7, setab=\E[4%p1%dm,
	setaf=\E[3%p1%dm,
	sgr=\E[0;10%?%p1%t;7%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;%?%p6%t;1%;m%?%p9%t\016%e\017%;,
	sgr0=\E[m\017, smacs=^N, smam=\E[?7h, smir=\E[4h,
	smpch=\E[11m, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
	u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?6c, u9=\E[c,
	vpa=\E[%i%p1%dd,

**Comment by nicm** [comment]
Start tmux with -vv (with -L is ok) then exit it and show me the server log please. It's possible resetting the cursor is a side effect of some other sequence so it might be hard to find. You can experiment by changing the cursor and then sending the sequences with tput eg `tput cnorm` (all outside tmux).

**Comment by nicm** [comment]
`civis` will reset it but if you changed `cnorm` with terminal-overrides it should set it back...

**Comment by rkta** [comment]
Here is the server log.  I will try to play around a bit, not so much familiar with this stuff, might take some time before I got something useful.

[tmux-server-18595.log.gz](https://github.com/user-attachments/files/16509394/tmux-server-18595.log.gz)

**Comment by nicm** [comment]
I don't see your `terminal-overrides` in this log, are you sure the config file is being loaded?

**Comment by rkta** [comment]
On Tue, Aug 06, 2024 at 04:33:50AM -0700, Nicholas Marriott wrote:
> I don't see your `terminal-overrides` in this log, are you sure the
> config file is being loaded?

Uh, sorry, this is without '-f /dev/null', I got some weird behaviour
with terminal-overrides in the config. Should have mentioned this. Let
me double check with terminal-overrides and report back.

**Comment by rkta** [comment]
Here is the log with terminal-overrides set. 

/tmp/tmux.conf has only one line:
```
set -as terminal-overrides 'linux:cnorm=\e[?25h\e[?6c:cvvis=\e[?25h\e[?6c'
```

When I run `./tmux -L foo -f /tmp/tmux.conf -vv` I get some weird behavior where `\e[?25h\e[?6c` is printed on the scree and I don't see a cursor. If I remove the cnorm part from the overrides it works. I don't spot the error...

[tmux-server-3044.log.gz](https://github.com/user-attachments/files/16518203/tmux-server-3044.log.gz)

**Comment by nicm** [comment]
Sorry try " instead of ' in the argument to `terminal-overrides`.

**Comment by rkta** [comment]
On Tue, Aug 06, 2024 at 09:55:00PM -0700, Nicholas Marriott wrote:
> Sorry try " instead of ' in the argument to `terminal-overrides`.

That does the trick! Now I've got a block cursor. Sorry for stating that
it does not work in a previous message. I must have messed something up
while testing, probably a server instance was already running...

Do you still want the logs? And thank you very much for your help!

**Comment by nicm** [comment]
No worries, if it works that's it I don't need to see the logs.
