### ISSUE TITLE
capture-pane does not respect utf-8 encoding setting?

### ISSUE THREAD

**Issue by avose** [tmux/tmux#4065]
### Issue description

Horizontal and vertical lines (e.g., from `bmon` network monitoring tool) look fine in my terminal and in an interactive tmux session. However, when running a detached tmux session and using `capture-pane`, I only ever see the ACS characters (i.e., `q` instead of `-` and `x` instead of `|`).

```
# Start new session with utf-8 and launch bmon.
tmux -u new-session -d -s test
tmux send-keys -t test bmon ENTER

# Try capturing plain text to terminal and see 'x' and 'q'.
tmux -u capture-pane -p -t test

# Try capturing text with escape sequences to terminal and see 'x' and 'q'.
tmux -u capture-pane -e -p -t test

# Try capturing with "-C" and see 'x' and 'q'.
tmux -u capture-pane -C -e -p -t test

# Now it works fine when attaching.
tmux attach -t test
```

### Required information

* tmux version: `tmux 3.4`
* Platform: `Linux x86_64`
* $TERM inside: `tmux-256color`
* $TERM outside: `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): ??

**Comment by avose** [comment]
Think I managed to generate logs (attached).
[tmux-server-560985.log](https://github.com/user-attachments/files/16510709/tmux-server-560985.log)
[tmux-out-560985.log](https://github.com/user-attachments/files/16510710/tmux-out-560985.log)
[tmux-client-560983.log](https://github.com/user-attachments/files/16510711/tmux-client-560983.log)

**Comment by nicm** [comment]
Are you sure `bmon` is sending UTF-8 and not ACS? `capture-pane` should reflect what it sends.

**Comment by avose** [comment]
> `capture-pane` should reflect what it sends.

I agree, after reading some of the capture and grid code ([cmd-capture-pane.c](https://github.com/tmux/tmux/blob/master/cmd-capture-pane.c) and [grid.c](https://github.com/tmux/tmux/blob/master/grid.c)), it looks like the output from capture-pane should be what's in the grid..

> Are you sure bmon is sending UTF-8 and not ACS?

Maybe? I just now looked at `bmon | tee test.log` which shows up as expected in an interactive terminal. Then opening `test.log` in emacs does not show the `q` and `x` characters. I suppose this implies that `bmon` is not outputting ACS?

An example string (as shown in emacs) from `test.log` where `bmon` should be writing output which includes line characters looks like:
```
^[[8d    qdisc none (noqueue) ^[[6b^[[0m^[[37m^[[40mx^[[0m^[[37m^[[40m      0 ^[[8b0      ^[[0m^[[37m^[[40mx^[[0m^[[37m^[[40m      0 ^[[8b0^[[K
^[[9d^[[0m^[[37m^[[40mq^[[30bvq^[[22bvq^[[48bq^[[39;49m^[[m^[[10;30H^[[0m^[[37m^[[40m^[[0m^[[37m^[[40m^[[1K (RX Bytes/second)^[[K
```

**Comment by nicm** [comment]
Certainly looks like it is using ACS to me:
![Screenshot 2024-08-06 at 16 01 24](https://github.com/user-attachments/assets/4ee878a0-f829-46fe-8b4e-823ed7497e0e)

**Comment by avose** [comment]
Thanks much for that!

So, my attempt at understanding this is: `bmon` is putting out ACS characters (presumably with a mode change early on, or else my interactive terminal wouldn't be able to render these correctly), and then tmux does not output the mode change with `capture-pane`, since the grid at the time of capture doesn't contain the escape sequence for enabling ACS mode?

**Comment by nicm** [comment]
tmux should include the escape sequence to turn on ACS with `-e`.

**Comment by avose** [comment]
Hmm. I don't know what I'm missing here then..

Since the following commands do not render the ACS line characters correctly:
```
tmux -u new-session -d -s test
tmux send-keys -t test bmon ENTER
tmux -u capture-pane -e -p -t test
```
while these commands do render the ACS line characters correctly:
```
# Terminal 1
bmon > bmon.out
# Terminal 2
tail -n 100000 -f bmon.out
```
it seems the issue is not with my terminal or what `bmon` is outputting, but something to do with the capture from tmux?

> tmux should include the escape sequence to turn on ACS with `-e`.

Does anyone happen to know the escape sequence needed to enable ACS? I haven't been able to find it from googling yet; I was thinking I'd check for that escape sequence in the output to see if that helps me figure out what's going on here.

**Comment by nicm** [comment]
IIRC it will be SI and SO, so \016 and \017.

**Comment by avose** [comment]
Tmux does output the SI/SO escape codes (checked with Emacs in hex editor mode) exactly where I would expect to see them, so I can interpret the output from tmux fine now. Thanks much for that.

I'm still confused about the output from `bmon`, as it doesn't have SI/SO in it at all. Suppose it doesn't really matter at this point, though. Thanks again for all the help.
