### ISSUE TITLE
Question: Possible in tmux conf file to emulate pressing the prefix key with another key situationally

### ISSUE THREAD

**Issue by TommiKabelitz** [tmux/tmux#4067]
Hello

Would like to configure tmux so that I can use an alternative key as the prefix key when I am in emacs. Ie. Use C-x as the prefix key outside of emacs, then when in emacs, use the key set as the prefix i.e. C-v

It would look something like this

.tmux.conf
````
set-option -g prefix C-v # For use in emacs (but still available globally)
bind -n C-x if -F '#{==:#{window_name},emacs}' 'send-keys C-x' 'enter-prefix-mode'
# Where enter-prefix-mode does not exist
````

Firstly, is something like this already possible. If not, could it be added? Essentially the capacity to enter the state as if the prefix key has just been pressed, but without actually pressing it.

Cheers

**Comment by nicm** [comment]
You want `switch-client -T` but you will need to set `prefix` to `None` as well.

**Comment by jixiuf** [comment]
https://github.com/jixiuf/vmacs/blob/71825f4f23d707fdc51f3f4f87a8ec1612a19885/linux/etc/xremap.yaml#L153
I use xremap on linux to send C-cC-c in emacs
 but just send C-c in tmux
