### ISSUE TITLE
Add .tmux configuration directory

### ISSUE THREAD

**Issue by pvltlnv** [tmux/tmux#407]
Please add .tmux directory to look for configuration file. The order would be:
1) /etc.tmux.conf
2) ~/.tmux.conf
3) ~/.tmux/tmux.conf

**Comment by nicm** [comment]
Why?

**Comment by krader1961** [comment]
Not only, why, but if such a change is warranted why not follow the XDG standard and use *~/.config/tmux/tmux.conf*?

**Comment by paveltsialnou** [comment]
It would be very useful. ~/.tmux directory can contain not only one configuration file, but also several additional files to source from .tmux.conf and/or plugins directory, etc.
Of course, you can create own .tmux direcotory (in any place) and use ~/.tmux.conf, but possibility store it in one place is just more holistic approach, IMHO.

**Comment by nicm** [comment]
I don't think this is a good idea. There is no consensus on what a directory should be called, and you can already do this by creating a .tmux.conf with source '.tmux.d/file1', source '.tmux.d/file2' and so on.

A more useful feature would be to make source-file (and perhaps also -f) able to load multiple files given by a glob(3) pattern.
