### ISSUE TITLE
bug: `git fetch` inside tmux, error "Recv failure: Software caused connection abort"

### ISSUE THREAD

**Issue by erlangparasu** [tmux/tmux#4070]
### Issue description

trying to execute `git fetch` inside tmux

i got error, output:
```
Recv failure: Software caused connection abort
```

**NOTE** `git fetch` works outside the `tmux`

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

```
tmux 3.4
```

* Platform (`uname -sp`).

```
Darwin arm
```

* $TERM inside and outside of tmux (`echo $TERM`).

```
screen-256color
```

```
xterm-kitty
```

* Logs from tmux (`tmux kill-server; tmux -vv new`).

```

```

**Comment by nicm** [comment]
What did the Git developers say about this?

**Comment by erlangparasu** [comment]
here is error message screenshot:

<img width="1350" alt="Screenshot 2024-08-21 at 13 54 22" src="https://github.com/user-attachments/assets/e2b8cf3a-7175-479b-8de4-feb8e65e360c">

**Comment by erlangparasu** [comment]
outside of tmux, it works just fine: screenshot:

<img width="1572" alt="Screenshot 2024-08-21 at 13 57 17" src="https://github.com/user-attachments/assets/f1a0cc3a-f362-481a-95e7-b739c9071f5c">

**Comment by erlangparasu** [comment]
tmux, git: screenshot:

<img width="1180" alt="Screenshot 2024-08-21 at 14 00 03" src="https://github.com/user-attachments/assets/500c72dc-938e-492d-b8d0-902bdc4691d7">

**Comment by nicm** [comment]
This is clearly something in your environment. Are you sure you are running the same `git` binary inside and outside? What differences are there in `env`? I don't know what `git` is looking for here so you will need to figure it out.

**Comment by erlangparasu** [comment]
Outside tmux:

<img width="648" alt="Screenshot 2024-08-21 at 14 41 14" src="https://github.com/user-attachments/assets/2c6fbfff-31eb-4dd8-a319-1d91099fe6dd">

<br>
<br>

Inside tmux:

<img width="836" alt="Screenshot 2024-08-21 at 14 41 50" src="https://github.com/user-attachments/assets/8e9744aa-aad7-4978-b5c6-c8936de6e131">
