### ISSUE TITLE
Can't make iTerm2's "CSI u" option work with tmux

### ISSUE THREAD

**Issue by svtkhn** [tmux/tmux#4072]
### Issue description

I have been trying to configure my setup to differentiate between `<c-h>` vs `<c-s-h>` or `<tab>` vs `<c-i>` and other similar shortcuts, and I thought that enabling [CSI u](https://iterm2.com/documentation-csiu.html) would solve the issue. It seems to work outside of `tmux` just fine, but when i start `tmux`, it's like the CSI u gets disabled (it stays disabled for the same terminal session even if i detach from `tmux`, but it gets enabled again if i open a new terminal window). 

Here `<c-h>` is printed as `^[[72;5u` outside of `tmux`, but inside `tmux` it still prints `^H`:
![Screenshot 2024-08-11 at 18 22 51](https://github.com/user-attachments/assets/759911a1-c134-40b9-abe6-428ecb6c80da)

I have tried various combinations of the following commands in `.tmux.conf`, but no luck:
```
run-shell 'printf "\033[>4;1m"'
set -s extended-keys on
# set -s extended-keys always
set -g xterm-keys on
set -g default-terminal "xterm-256color"
set -as terminal-features 'xterm*:extkeys'
```

I am probably missing something obvious, but i have gone through every relevant google result i could find and i don't understand why it's still not working with the config above.
I'd really appreciate any pointers from those who managed to make "CSI u" play nicely with `tmux` on their MacOS. Thank you!

### Required information

* tmux version (`tmux -V`): 
`tmux 3.4`
* Platform (`uname -sp`): 
`Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`): 

   inside: `tmux-256color` or `xterm-256color` 
   (depending on `set -g default-terminal "xterm-256color"`)

   outside: `xterm-256color` 
* Logs from tmux (`tmux kill-server; tmux -vv new`):
[tmux-client-41903.log](https://github.com/user-attachments/files/16576710/tmux-client-41903.log)
[tmux-out-41905.log](https://github.com/user-attachments/files/16576711/tmux-out-41905.log)
[tmux-server-41905.log](https://github.com/user-attachments/files/16576712/tmux-server-41905.log)

**Comment by nicm** [comment]
`C-h` is not mapped by `modifyOtherKeys` which is all tmux supports at the moment, you will need to wait for CSI u support which will be the second part of https://github.com/tmux/tmux/pull/4038.
