### ISSUE TITLE
tmux refresh-client -l returns immediately

### ISSUE THREAD

**Issue by juru1234** [tmux/tmux#4074]
The` tmux refresh-client -l ` command returns immediately and therefore I need to use a `sleep` in my neovim config when pasting with OSC52:
```

if vim.env.TMUX ~= nil then
  local copy = {'tmux', 'load-buffer', '-w', '-'}
  local paste = {'bash', '-c', 'tmux refresh-client -l && sleep 0.05 && tmux save-buffer -'}
  vim.g.clipboard = {
    name = 'tmux',
    copy = {
      ['+'] = copy,
      ['*'] = copy,
    },
    paste = {
      ['+'] = paste,
      ['*'] = paste,
    },
    cache_enabled = 0,
  }
end
```

Would it be an idea to make a version of this command that returns when tmux successfully copied the clipboard content from the terminal?

**Comment by nicm** [comment]
OK if you want to open a PR I will take a look.
