### ISSUE TITLE
hyperlink does not work

### ISSUE THREAD

**Issue by GreatBahram** [tmux/tmux#4078]
### Issue description
Hello there,

I have an issue, hyperlinks do not work in tmux, while I am using tmux 3.4 Hyperlinks using a simple `ls` command work
[tmux-out-1682050.log](https://github.com/user-attachments/files/16626808/tmux-out-1682050.log)
[tmux-client-1682048.log](https://github.com/user-attachments/files/16626810/tmux-client-1682048.log)
[tmux-server-1682050.log](https://github.com/user-attachments/files/16626811/tmux-server-1682050.log)
 fine outside of tmux, but inside not.

I even tried it with no configuration using `tmux -f /dev/null` to make sure my configuration is not causing this.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.4
* Platform (`uname -sp`): `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Try `set -as terminal-features 'xterm*:hyperlinks'`.

**Comment by GreatBahram** [comment]
Awesome this fixed it :sunflower:
