### ISSUE TITLE
OSC52 not working on V3.4 with specific Ms (which dont have `%p1%s`)

### ISSUE THREAD

**Issue by popjdh** [tmux/tmux#4081]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  * `tmux 3.4`
* Platform (`uname -sp`).
  * `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`).
  * Both `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
  * [tmux-out-22472.log](https://github.com/user-attachments/files/16639260/tmux-out-22472.log)
  * [tmux-server-22472.log](https://github.com/user-attachments/files/16639261/tmux-server-22472.log)
  * [tmux-client-22470.log](https://github.com/user-attachments/files/16639262/tmux-client-22470.log)

These are the only contents in my configuration file:
```conf
set-option -s set-clipboard on
set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7"
```

I found `1723825207.031737 could not expand Ms` in `tmux-server-22472.log`.
Then I try `set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p1%s%p2%s\\7"`, It is ok. 

**But I am not sure about the specific function of `%p1%s`, it seems that writing it this way does not affect the content of the clipboard.**

**Comment by popjdh** [comment]
I am using konsole with a simple osc52 [patch](https://aur.archlinux.org/cgit/aur.git/tree/osc52.patch?h=konsole-osc52). This only accepts OSC 52 sequences with the c; option.

**Comment by nicm** [comment]
`Ms` takes two string parameters so it will not work if you only give it one, you will need to use a capability value that uses both parameters.

**Comment by popjdh** [comment]
> `Ms` takes two string parameters so it will not work if you only use one, you will need to use a capability value that uses both parameters.

As tmux does not pass the single option 'c' by default, in previous versions it was allowed for Ms to specify the 'c' option instead of `%p1%s`.

**Can we continue to be compatible with previous behavior or provide a way to specify `%p1%s` content for this need?**

**Comment by nicm** [comment]
No, new ncurses versions requires us to tell it how many arguments we are giving so it can validate the capability.

Does it work if you do `%p1%.0s` so it uses the string but does not print it?

**Comment by popjdh** [comment]
After your reply, I searched for Ms related content again:

1. The role of Ms and the function of each parameter can be referred to [here](https://invisible-island.net/xterm/terminfo-contents.html#tic-xterm_pcfkeys).
2. This `%p1%s` structure can be referred to [Parameterized Strings Section](https://www.man7.org/linux/man-pages/man5/terminfo.5.html) .

> Does it work if you do `%p1%.0s` so it uses the string but does not print it?

The `%p1` parameter is empty in my environment. So it seems diffcult to directly test the specified accuracy. By the way, I tested `%p1%2s` and it got `  ` (two spaces). 

I have switched to using `set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c%p1%.0s;%p2%s\\7"`, and it works. Therefore, this plan should be effective.
