### ISSUE TITLE
`range=pane|X` not passing `X` to `=` or `{mouse}`

### ISSUE THREAD

**Issue by theutz** [tmux/tmux#4087]
The `range=pane|X` format does not pass the pane ID as an argument to the `Mouse*Status` event like the `range=window|X` does.

### Minimal config:

```tmux
set -g mouse on
set -g status 2
set -g status-format[1] "#{P:#[range=pane|#{pane_id}]#P:#{pane_current_command} #[norange]}"
bind -n MouseDown1Status if -F '#{==:#{mouse_status_range},pane}' {
  select-pane -t =
}
```

*I also tested this with `select-pane -t '{mouse}'` and it was equally unsuccessful.*

### Start the server

`tmux -vv -Ltest -ftest.conf new\; splitp`

### Actions to take

- Click on the status item `0:0.0`.

## Expected Behavior

The active pane should change to `0:0.0`

**or**

If the intended behavior of this feature is to pass `pane %1` to the `#{mouse_status_range}` variable, then it's not doing that either. So there's no way to retrieve the pane_id.

## Output from `uname -sp && tmux -V && echo $TERM`:

```
Darwin arm
tmux 3.4
xterm-256color
```

## Logs
- [tmux-client-53689.log](https://github.com/user-attachments/files/16711016/tmux-client-53689.log)
- [tmux-out-53691.log](https://github.com/user-attachments/files/16711017/tmux-out-53691.log)
- [tmux-server-53691.log](https://github.com/user-attachments/files/16711018/tmux-server-53691.log)

**Comment by nicm** [comment]
This seems to fix it:
~~~~
--- server-client.c     26 Aug 2024 07:30:46 -0000      1.406
+++ server-client.c     27 Aug 2024 07:24:54 -0000
@@ -783,8 +783,7 @@ have_event:
                        log_debug("mouse on pane %%%u border", wp->id);
                m->wp = wp->id;
                m->w = wp->window->id;
-       } else
-               m->wp = -1;
+       }

        /* Stop dragging if needed. */
        if (type != DRAG && type != WHEEL && c->tty.mouse_drag_flag != 0) {

**Comment by nicm** [comment]
Applied to OpenBSD, will be in GitHub when it syncs up.
