### ISSUE TITLE
"focus-events" option broken since commit 692bae9e

### ISSUE THREAD

**Issue by Sharpeee** [tmux/tmux#4090]
### Issue description
Since commit 692bae9e when the "focus-events" option is set "on", control characters are inserted in the terminal when the window is gaining (Ctrl-2 / ^@) and losing (Ctrl-A / ^A) focus.

It is easily reproducible like this:

In one terminal window run
```
tmux -f /dev/null
tmux set-option -g focus-events on
```

In another terminal window run
```
tmux
cat
```

Now observe in the second terminal window that ^A and ^@ is inserted whenever the window loses/gains focus.

### Required information
* tmux version (`tmux -V`).
    `tmux next-3.5`. Commit 692bae9e.
* Platform (`uname -sp`).
    `Linux unknown`. Arch Linux.
* $TERM inside and outside of tmux (`echo $TERM`).
    `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
    [tmux-client-244629.log](https://github.com/user-attachments/files/16728982/tmux-client-244629.log)
    [tmux-out-244631.log](https://github.com/user-attachments/files/16728983/tmux-out-244631.log)
    [tmux-server-244631.log](https://github.com/user-attachments/files/16728984/tmux-server-244631.log)

**Comment by nicm** [comment]
I think this should be fixed as soon as GitHub syncs up, probably within the next few hours. Thanks!
