### ISSUE TITLE
feat: Can we get a `search_count` for use in formats?

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#4091]
I'd like to be able to move the top-right copy mode indicator text into the pane status. That is, I'd like to turn off the thing in the top right[^ie] that says `(35 results) [0/106]`, and instead put that same info in the `pane-border-format`. I can synthesize the `[0/106]` bit by using `#{scroll_position}` and and `#{history_size}` formats, but I can't see a way to get the result count. Any chance we could expose the `searchcount` info that is [used internally here](https://github.com/tmux/tmux/blob/34807388b064ed922293f128324b7d5d96f0c84d/window-copy.c#L4257) (or something like it) so that formats can make use of it?

[^ie]: By setting up bindings to pass the `-H` switch when performing the `copy-mode` command.

**Comment by nicm** [comment]
I've added `search_count` and `search_count_partial`, will be in GitHub when it syncs hopefully in the next day or so. Thanks!

**Comment by wincent** [comment]
Thanks a bunch @nicm! 🙇
