### ISSUE TITLE
[Feature Request] Options for `capture-pane` to use tmux's OSC 133 integration.

### ISSUE THREAD

**Issue by eth-p** [tmux/tmux#4092]
### Issue description

Version 3.4 added support for shell integration sequences (OSC 133), using it to set the `GRID_LINE_START_PROMPT` and `GRID_LINE_START_OUTPUT` flags.

It would be **extremely** useful if `capture-pane` was able to use these flags as references to the start and end of a capture. A couple example uses cases are:

 - Viewing a command in isolation, making it easier to search through.
 - Piping the output of a slow, previously-executed command through another tool (e.g. `kubectl get -oyaml pod` capture into `yq`)
 - Creating a help script that reads the error message of the previous command, similar to [thefuck](https://github.com/nvbn/thefuck).

As for what that would look like, possibly reusing `-S` and `-E`? They currently take relative numbers or `-`, but they could be extended to use the `!<history_index>` syntax that bash uses:

```
hostname$ uname -s
Darwin

hostname$ echo hello world
hello world

hostname$ tmux capture-pane -S '!2' -E '!3' | sed s/^/'> /'
> hello world

hostname$ tmux capture-pane -S '!1' -E '!3' | sed s/^/'> /'
> Darwin
> hello world
```

A `-c` flag can be added to specify if lines with `GRID_LINE_START_PROMPT` should also be included.

I'm proficient enough with C that I could make a pull request if this is something that you would consider adding. It may require a couple revisions if I do, since I would be a first-time contributor and not be familiar with the tmux design standards and style preferences.

### Required information

Please provide the following information:

* tmux version: `tmux 3.4` (`tmux -V`).
* Platform: `Darwin arm` (`uname -sp`).
* Term inside: `xterm256-color`
* Term outside:`xterm256-color` (Alacritty)
* Logs from tmux: N/A

**Comment by nicm** [comment]
I am OK with this if you want to make a PR.
