### ISSUE TITLE
After su the window title never changes

### ISSUE THREAD

**Issue by 12425** [tmux/tmux#41]
In tmux window with default settings, if I change directories, the window title will change.
However after I switch user, the title will never change.
This issue only appears in zsh in tmux. In bash in tmux, the window title is correct.

There is another similar issue for the status line.
If I set the status-left as
`set -g status-left '#(echo $USER)@#H '`
Then I see `admin@dev`
But whatever user I switch to, it always shows `admin@dev`.

**Comment by nicm** [comment]
tmux does not set the directory in the window title, zsh does, so it is clearly doing in it in a way that doesn't work with su.

$USER in status-left will always be the user tmux is running as, it has no way to know you have run su in a child process.
