### ISSUE TITLE
`window-status-bell-style` not working

### ISSUE THREAD

**Issue by joshdick** [tmux/tmux#410]
I'm running tmux 2.2. With the following lines in my `~/.tmux.conf`, `window-status-bell-style` has no effect unless I comment out `window-status-format` and `window-status-current-format`:

```
setw -g window-status-format "#[fg=colour8,bg=colour15] #I #[fg=colour15,bg=colour8] #W "
setw -g window-status-current-format "#[fg=colour8,bg=colour7] #I #[fg=colour7,bg=colour8] #W "
setw -g window-status-bell-style fg=colour1,bg=colour8
```

I've also tried setting `window-status-bell-bg` and `window-status-bell-fg` and these similarly had no effect unless the aforementioned format settings were commented out.

Is this expected behavior?

**Comment by nicm** [comment]
Yes, window-status-bell-style only sets the default style for windows with a bell. You are overriding the default with #[]. You can either not use #[] and set the styles with the properties, or use formats, for example #{?window_bell_flag,#[fg=colour1],#[fg=colour8]}

**Comment by joshdick** [comment]
Exactly the information I needed; thanks very much!
