### ISSUE TITLE
3.4 segfault in format.c:format_add_modifier

### ISSUE THREAD

**Issue by nairb774** [tmux/tmux#4100]
### Issue description

I was using tmux and it randomly crashed leaving me with a core dump.

<details>
<summary>GDB Backtrace</summary>

```
(gdb) bt
#0  0x00007200d1a58a5f in arena_for_chunk (ptr=0x7200d1a5596a <_int_free_merge_chunk+154>) at /usr/src/debug/glibc/glibc/malloc/arena.c:153
#1  arena_for_chunk (ptr=0x7200d1a5596a <_int_free_merge_chunk+154>) at /usr/src/debug/glibc/glibc/malloc/arena.c:151
#2  __GI___libc_realloc (oldmem=0x55c08c0675a0, bytes=bytes@entry=48) at malloc.c:3509
#3  0x00007200d1a5a1c5 in __GI___libc_reallocarray (optr=<optimized out>, nmemb=nmemb@entry=2, elem_size=elem_size@entry=24) at reallocarray.c:32
#4  0x000055c086262ba1 in xreallocarray (ptr=<optimized out>, nmemb=2, size=24) at /usr/src/debug/tmux/tmux/xmalloc.c:67
#5  0x000055c0861fdda6 in format_add_modifier (list=list@entry=0x7fffa4dfb280, count=count@entry=0x7fffa4dfb210, c=c@entry=0x7fffa4dfb240 "=", n=n@entry=1, argv=argv@entry=0x55c08cec83b0, argc=1) at /usr/src/debug/tmux/tmux/format.c:3803
#6  0x000055c086200dfe in format_build_modifiers (es=0x7fffa4dfd570, s=<synthetic pointer>, count=0x7fffa4dfb210) at /usr/src/debug/tmux/tmux/format.c:3925
#7  format_replace (es=es@entry=0x7fffa4dfd570, 
    key=key@entry=0x55c0875c7de0 "T;=/#{status-left-length}:status-left}#[pop-default]#[norange default]#[list=on align=#{status-justify}]#[list=left-marker]<#[list=right-marker]>#[list=on]#{W:#[range=window|#{window_index} #{E:window"..., keylen=keylen@entry=37, 
    buf=buf@entry=0x7fffa4dfb3d8, len=len@entry=0x7fffa4dfb3c8, off=off@entry=0x7fffa4dfb3d0) at /usr/src/debug/tmux/tmux/format.c:4381
#8  0x000055c086203b04 in format_expand1 (es=0x7fffa4dfd570, 
    fmt=0x55c0875c7de0 "T;=/#{status-left-length}:status-left}#[pop-default]#[norange default]#[list=on align=#{status-justify}]#[list=left-marker]<#[list=right-marker]>#[list=on]#{W:#[range=window|#{window_index} #{E:window"...)
    at /usr/src/debug/tmux/tmux/format.c:4893
#9  0x000055c086229c5c in format_expand_time (ft=0x55c0879d0480, fmt=<optimized out>) at /usr/src/debug/tmux/tmux/format.c:4974
#10 status_redraw (c=0x55c08764f3f0) at /usr/src/debug/tmux/tmux/status.c:439
#11 screen_redraw_update (c=0x55c08764f3f0, flags=403013777) at /usr/src/debug/tmux/tmux/screen-redraw.c:514
#12 screen_redraw_screen (c=0x55c08764f3f0) at /usr/src/debug/tmux/tmux/screen-redraw.c:575
#13 0x000055c08623b767 in server_client_check_redraw (c=0x55c08764f3f0) at /usr/src/debug/tmux/tmux/server-client.c:2662
#14 server_client_loop () at /usr/src/debug/tmux/tmux/server-client.c:2121
#15 server_loop () at /usr/src/debug/tmux/tmux/server.c:277
#16 0x000055c086237365 in proc_loop (tp=0x55c0875d3c80, loopcb=<optimized out>) at /usr/src/debug/tmux/tmux/proc.c:218
#17 server_start (client=<optimized out>, flags=402718720, base=<optimized out>, lockfd=5, lockfile=0x55c0875d2df0 "") at /usr/src/debug/tmux/tmux/server.c:252
#18 0x000055c0861c7971 in client_connect (base=0x55c0875d2580, path=0x55c0875d22d0 "/tmp/tmux-1000/default", flags=402718720) at /usr/src/debug/tmux/tmux/client.c:164
#19 client_main (base=0x55c0875d2580, argc=4, argv=<optimized out>, flags=<optimized out>, feat=1) at /usr/src/debug/tmux/tmux/client.c:290
#20 main (argc=4, argv=<optimized out>) at /usr/src/debug/tmux/tmux/tmux.c:519
```

</details>

At this point, it isn't clear to me if there is a bug somewhere in this code, or if there is some other lurking memory corruption floating about. I don't expect to be able to reproduce this easily, or at all, but I thought it might be worth surfacing in the event the bug ends up being obvious.

I'm not a gdb expert, so if there is useful information that I could extract from the core dump, I'm happy to do so. The core dump looks to have some amount of sensitive information in it, so I'm a little hesitant to share it.

Lastly, I am using tmux via byobu. It is on my todo list to simplify away from byobu. If this over-complicates the debugging from prior experience, feel free to close.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
`tmux 3.4`
Installed from https://archlinux.org/packages/extra/x86_64/tmux/ @ 3.4-10
* Platform (`uname -sp`).
`Linux brian 6.6.47-1-lts #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 05:13:57 +0000 x86_64 GNU/Linux`
* $TERM inside and outside of tmux (`echo $TERM`).
Inside: `screen-256color`
Outside: `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-485884.log](https://github.com/user-attachments/files/16808360/tmux-client-485884.log)
[tmux-out-485941.log](https://github.com/user-attachments/files/16808361/tmux-out-485941.log)
[tmux-server-485941.log](https://github.com/user-attachments/files/16808362/tmux-server-485941.log)

**Comment by nicm** [comment]
Realistically unless you can reproduce this we will not find it. If you are going to reproduce, please try with master. It may also be worth running tmux with valgrind, but unless you can reproduce it will probably not show anything useful either.
