### ISSUE TITLE
Unexpected Highlighting in Neovim within Tmux

### ISSUE THREAD

**Issue by BugReportOnWeb** [tmux/tmux#4102]
### Issue description

Special keywords and commented words are being highlighted unexpectedly when opening Neovim within a tmux window.

<img width="618" alt="Screenshot 2024-09-01 at 7 32 17 PM" src="https://github.com/user-attachments/assets/0fa4807f-80f8-419d-88e8-e3c65d07d798">

<img width="524" alt="Screenshot 2024-09-01 at 7 49 10 PM" src="https://github.com/user-attachments/assets/98c7d39a-5968-462f-95c7-98d9b6965113">

### Required information

* tmux version - tmux 3.4
* $TERM inside and outside of tmux - tmux-256color (inside), linux (outside)
* Platform - Darwin arm (Sonoma 14.6.1)
* Terminal - iTerm2 (Build 3.5.4)
* Neovim version - NVIM v0.9.5
* Log files:
    - [tmux-client-75318.log](https://github.com/user-attachments/files/16829309/tmux-client-75318.log)
    - [tmux-out-75320.log](https://github.com/user-attachments/files/16829310/tmux-out-75320.log)
    - [tmux-server-75320.log](https://github.com/user-attachments/files/16829313/tmux-server-75320.log)

**Comment by nicm** [comment]
But `TERM=linux` is for the Linux console not iTerm2?

**Comment by BugReportOnWeb** [comment]
That's what I don't understand either. I'm using iTerm2, but the output of `$TERM` is `linux` for some reason. It must be something from the new build, as it wasn't the case before, as far as I remember.

**Comment by nicm** [comment]
Check your iTerm2 config (look for "Report terminal type") and shell profiles.

**Comment by BugReportOnWeb** [comment]
Great! I changed it to `xterm-256color` and everything is fixed now. Thanks!
