### ISSUE TITLE
Take over the maintenance of tmux snap

### ISSUE THREAD

**Issue by boukendesho** [tmux/tmux#4103]
As the title, i want to take over the maintenance of tmux snap, would you willing to support me?

The [tmux snap](https://snapcraft.io/tmux) is too outdated. The current maintainer could not be contacted.

I know you have no interest beyond tar ball, I'll create a new  repo under my account to maintain snap stuff.

I really don't want to see a very outdated version of such a useful tool!

**Comment by boukendesho** [comment]
It's a little complicate.

First i will post a new issue like [this](https://github.com/rclone/rclone/issues/7221), to prove me that I'm officially recognized.

Then i will show the new post to Canonical and let them transfer the tmux snap ownership to me.

Last after ownership is transferd to me, then i can  release a update.

**Comment by nicm** [comment]
OK let me know.
