### ISSUE TITLE
Bug fix release?

### ISSUE THREAD

**Issue by robsmith11** [tmux/tmux#4107]
After a few minutes of being very confused why I couldn't search scrollback after upgrading to 3.4, I had to roll back my whole system.  Being able to search text is a major feature of tmux, so I'm surprised to see that a bug fix wasn't released months after the issue [1] was fixed.  Surely many people must be affected by this.

[1] https://github.com/tmux/tmux/issues/3944

**Comment by nicm** [comment]
There will be a new release in due course.

**Comment by yang** [comment]
Seconding this. The scrollback search in particular makes tmux unusable.

**Comment by robsmith11** [comment]
Since the tmux maintainer doesn't seem to feel a need to release timely bug fixes, I'd recommend the alternative that I've started using:

https://github.com/zellij-org/zellij
