### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by wanchanglin** [tmux/tmux#4109]
### Issue description
I have installed by `sudo apt install tmux`.  Launch it and there are error massage like this: 
```
: No such file or directory
: No such file or directory
: command not found
: command not found
```
I cannot figure out what wrong with this. I have also installed `tmux` from source but the same issue remaining.  

### Required information

Please provide the following information:

* tmux version: `3.4`
* Platform: `Linux x86_64`
* $TERM inside: `tmux-256color`  and outside of tmux: `xterm-256color`
* Logs from tmux
   * tmux kill-server: `no server running on /tmp/tmux-1000/default`
   * tmux -vv new:
    ```
   : No such file or directory
   : No such file or directory
   : command not found
   : command not found
   ```

**Comment by wanchanglin** [comment]
Install `tmux` 3.2a from source and there is the same issue. Currently I use Ubuntu 24.04. I suspect Linux version since there ware no any problems for Ubuntu 22.04 and beyond.

**Comment by nicm** [comment]
Almost certainly this is something wrong in your shell profiles.

**Comment by wanchanglin** [comment]
Dear @nicm, many thanks for your reply.
Using your suggestion, I find out I have accidentally copied a `.bash_profile` produced by Windows' Git into my $HOME:
```bash
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
```
Delete this file and everything works perfectly.  

Many thanks again.
