### ISSUE TITLE
When printing character by character, sometimes tmux overwrites the line instead of going to the next line

### ISSUE THREAD

**Issue by maxjacobson** [tmux/tmux#411]
![tmux-wrapping](https://cloud.githubusercontent.com/assets/1421211/15305957/9d65197e-1b94-11e6-8da4-52ca877d86f8.gif)

this issue seems to only occur when the prompt is already at the very bottom of the terminal.

switching to a different tmux tab and then switching back fixes the output

issue occurs in zsh and bash

here's [app.rb](https://gist.github.com/maxjacobson/fe40c331b4046e348376bf565ca6eee3) from the GIF in case you want to try with this, but any program which prints dots will do, for example when using a unit test runner that prints dots.

**Comment by nicm** [comment]
tmux version?

**Comment by maxjacobson** [comment]
2.2 -- got it via `brew install tmux --HEAD`

It might be the same issue as the one discussed here: http://comments.gmane.org/gmane.comp.terminal-emulators.tmux.user/651

I can come to a similar conclusion that it works correctly in iTerm 2, and maybe I should be using that instead of the default mac Terminal...

**Comment by nicm** [comment]
If it works in one terminal but not another most likely your TERM is wrong
in the one where it doesn't work or it is a bug in the terminal. I'd guess
the latter since Terminal.app is known for being a bit poo.

**Comment by maxjacobson** [comment]
haha

![screenshot 2016-05-17 09 56 34](https://cloud.githubusercontent.com/assets/1421211/15324749/aa543f80-1c15-11e6-860a-c3912a566323.png)

**Comment by maxjacobson** [comment]
whoops, prematurely submitted this -- but the question is, do you think I should be changing the value in that dropdown menu? I've never really opened it before so maybe this is the default

**Comment by maxjacobson** [comment]
Wow, yep, switching to `dtterm` makes it work. Neat! Thanks

**Comment by nicm** [comment]
It sounds like it has a bug in some terminal feature advertised by the TERM
you were using that doesn't appear in dtterm.

**Comment by maxjacobson** [comment]
Cool, thanks for helping me understand that 😄
