### ISSUE TITLE
[Search] Infinite loop in `window_copy_search_marks` caused by `width == 0`

### ISSUE THREAD

**Issue by v01dXYZ** [tmux/tmux#4110]
* Context: Search in the history could sometimes cause server to turn unresponsive and eat 100% CPU. 
* Version: it occurs both with `3.4` and commit 651891c3

The code that is susceptible to cause the issue is in `window-copy.c window_copy_search_marks(...)`. FYI, `gdb` shows `width` is equal to `0` and even with multiple loop iterations, it neither exits the loop nor sets `width` to non-zero:

https://github.com/tmux/tmux/blob/c36ffcbe563bdb37a294bdab93f8d1d120484150/window-copy.c#L3971-L3999

**Comment by nicm** [comment]
This isn't much use. How do you reproduce?

**Comment by v01dXYZ** [comment]
I am able to reproduce the bug when the first character of a backward search is `C-o` (ASCII hex: `0x0f`, https://en.wikipedia.org/wiki/Shift_Out_and_Shift_In_characters).

More explicitly:

* Launch independent server: `tmux -L backward-search-bug-0 -vvv`
* Type `prefix [` for `copy-mode`
* Type `C-r` for incremental reverse search
* Type as search input `C-o`. The server becomes unresponsive.

FYI, I am not able to reproduce the bug with `tmux 3.3a`.

I've got to confess I've read the code to reproduce it as I was unable to reproduce it on my own. It took me some time to realise the code in `window-copy.c` is actually correct (`b - gd->sx*gd>sy > 0` is true if `window_copy_search_mark_at(...)` returns `true`).

The culprit seems to be in `status_prompt_key(...)` just after the `append_key:` label. With the search input being `C-o`, `searchstr` is `{0x0f, 0x00}`. The function `screen_write_strlen(searchstr)` (from `screen-write.c`) will ignore Control characters and returns a length of `0`.

`3.3a` has the following:

https://github.com/tmux/tmux/blob/0b355ae8114511e1ff6359272b164f1cdf718e80/status.c#L1454-L1463

`HEAD` has the following:

https://github.com/tmux/tmux/blob/c36ffcbe563bdb37a294bdab93f8d1d120484150/status.c#L1482-L1489

The commit introducing the change: 48eba4c.

**Comment by v01dXYZ** [comment]
I can write the commit if you want (I guess putting back the case for `key <= 0x1f`). I would need some directions for the integration test though.

**Comment by nicm** [comment]
I cannot reproduce this. Are you sure your tree is up to date? `C-o` is not 0xf now, it is `KEYC_CTRL|'o'` and this will be caught by the `else` on line 1486.

**Comment by nicm** [comment]
Make sure your tree is after c7e61a01e53905b09ee423c93f29e13267d86f99 and see if this still happens.

**Comment by v01dXYZ** [comment]
Indeed my repo was not up to date... The problem is not present with upstream. I apologise for the waste of time.

The commit you pointed translates the control key into 64-bit values that won't be considered as a valid character to append. It's maybe possible to recreate the bug with a non-UTF8 byte sequence. This edge case could happen with terminals that don't normalise a copy paste but I was not able to reproduce it with alactritty.

Thanks for your answers.
