### ISSUE TITLE
Tmux prefix key is deactivated on mouse move when Emacs's xterm-mouse-mode is enabled

### ISSUE THREAD

**Issue by whhone** [tmux/tmux#4111]
### Issue description

**Issue**: When using Emacs's `xterm-mouse-mode`, the Tmux prefix key is canceled on mouse move. It is annoying because it is too easy to touch the touchpad on a laptop and deactivate the prefix key before the next key press.

**Minimum `.tmux.config`**
```
set -g mouse on
# to visualize whether the prefix key is activated
set -g status-left '#{?client_prefix,#[bg=colour01] ON  #[bg=default], OFF }'
```

**Repro Steps**:
1. Create a new tmux session: `tmux new`
2. In tmux, run `emacs -q` (Emacs without config)
3. In Emacs, type "M-x xterm-mouse-mode" to enable mouse support in Emacs
4. Press the tmux prefix (C-b)
5. Move the mouse

**Expected behavior**: The prefix key is still activated.

**Actual behavior**: The prefix key is deactivated as soon as the mouse is moved.

[video](https://github.com/user-attachments/assets/720248d8-a6a5-4109-a39e-308b1ba88c8a)

The video shows that the prefix key remains activated on the mouse move in normal cases, but not in Emacs with `xterm-mouse-mode`.

**Analysis**: When enabling `xterm-mouse-mode`, it prints `\e[?1000h\e[?1003h\e[?1005h\e[?1006h`.

```
Control sequence to enable xterm mouse tracking.
Enables basic mouse tracking, mouse motion events and finally
extended tracking on terminals that support it.  The following
escape sequences are understood by modern xterms:

"\e[?1000h" "Basic mouse mode": Enables reports for mouse
            clicks.  There is a limit to the maximum row/column
            position (<= 223), which can be reported in this
            basic mode.

"\e[?1003h" "Mouse motion mode": Enables reports for mouse
            motion events.

"\e[?1005h" "UTF-8 coordinate extension": Enables an extension
            to the basic mouse mode, which uses UTF-8
            characters to overcome the 223 row/column limit.  This
            extension may conflict with non UTF-8 applications or
            non UTF-8 locales.

"\e[?1006h" "SGR coordinate extension": Enables a newer
            alternative extension to the basic mouse mode, which
            overcomes the 223 row/column limit without the
            drawbacks of the UTF-8 coordinate extension.
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `3.4`
* Platform (`uname -sp`): `unknown` (Arch Linux)
* $TERM inside and outside of tmux (`echo $TERM`): Inside: `tmux-256color` Outside: `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
  * [tmux-client-2429010.log](https://github.com/user-attachments/files/16913660/tmux-client-2429010.log)
  * [tmux-server-2429012.log](https://github.com/user-attachments/files/16913661/tmux-server-2429012.log)
  * [tmux-out-2429012.log](https://github.com/user-attachments/files/16913663/tmux-out-2429012.log)

**Comment by nicm** [comment]
Does this change it? 
[x.diff.txt](https://github.com/user-attachments/files/16944423/x.diff.txt)

**Comment by whhone** [comment]
Built and tested. The above change works brilliantly!  Thanks @nicm!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
