### ISSUE TITLE
Ctrl-{num_key} binds not working.

### ISSUE THREAD

**Issue by The-Briel-Deal** [tmux/tmux#4113]
### Issue description
Hey Tmux maintainers and contributers! Thanks for spending your time on such a great piece of software.

So I have used control with a number key (e.g. `<C-1>`, `<C-2>` ... `<C-9>`) in nvim for the longest time to quickly switch between marked buffers. And every time I try to integrate tmux into my workflow it bothers me so much that I can't get this to work. So the last few days I've been trying to figure out what is causing this.

My understanding is that this is due to the same reason ctrl-i and tab are identical inside tmux. Which is because without protocol extensions, some key sequences are ambiguous.

I saw that there is a WIP PR [here](https://github.com/tmux/tmux/pull/4038) for the Kitty Keyboard Protocol (I'm using alacritty which supports this). But building from source still gave me the same results.

Currently if you run cat, then press ctrl-1 in tmux, it will result in "1" being output, if you press ctrl-2 it will result in "^@" being output. I've enabled extkeys, set extended-keys-format to csi-u, and set extended-keys to always.

```
set -ga terminal-features ',*alacritty*:extkeys'
set -g extended-keys-format csi-u
set -g extended-keys always
```

But no amount of tweaking these things has resulted in things working. I've also tried various terminals (kitty, alacritty, foot, xterm, ...) and for all of them, the keys work when running nvim on its own. But the <C-{num}> don't work when tmux is running.

I'm happy to fix this myself and submit a PR. I was just hoping for some pointers to where in the tmux source this issue might be.

Describe the problem and the steps to reproduce.
```
# Start nvim Without Tmux
nvim
:nmap <C-2> echo "I pressed control 2!!!!"
# Press control+2 and it will echo the message

# Start tmux then nvim
tmux
nvim
nmap <C-2> echo "I pressed control 2!!!!"
# Press control+2 and it will not echo the message.

```

### Required information

Please provide the following information:
```
gf@arch:~/C/tmux=>tmux -V
tmux next-3.5

gf@arch:~/C/tmux=>uname -sp
Linux unknown (latest arch linux)

gf@arch:~/C/tmux=>uname --all
Linux arch 6.10.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 29 Aug 2024 16:48:57 +0000 x86_64 GNU/Linux

# Term outside of tmux (I've tested this on xterm and foot as well)
gf@arch:~/C/tmux=>echo $TERM
alacritty
# Term inside of tmux
gf@arch:~/C/tmux=>echo $TERM
tmux-256color
```

[tmux-out-546351.log](https://github.com/user-attachments/files/16919416/tmux-out-546351.log)
[tmux-server-546351.log](https://github.com/user-attachments/files/16919417/tmux-server-546351.log)
[tmux-client-546349.log](https://github.com/user-attachments/files/16919418/tmux-client-546349.log)

**Comment by nicm** [comment]
If you do `printf "\033[>4;1m"; cat` in xterm and press `C-1` what do you see? And what if you do the same in tmux?

**Comment by The-Briel-Deal** [comment]
Plain xterm I get `^[[27;5;49"`. In xterm+tmux I get `^[[49;5u`.

In alacritty it just prints `1` in and out of tmux.

One interesting thing here is that in xterm, while C-1 gives me that unique response (Guessing its CSI-U or modifyOtherKeys?) C-2 just prints `^@` both in and out of tmux?

**Comment by The-Briel-Deal** [comment]
One other note I forgot in my original post.

C-1 in xterm+tmux works, but C-2 does not. In plain xterm, all C-{num} keys work. I wonder what the difference is?

(Also in alacritty+tmux, none of the C-{num} keys work)

I've been very confused throughout this by the lengthy combination of extended key protocols. And some are only partially implemented from my understanding?

**Comment by nicm** [comment]
Seems like tmux is working correctly in xterm then, you have configured CSI u so you are getting the CSI u sequence instead of the one you see outside tmux.

I don't know why vim isn't working. Are you sure it doesn't only add the key maps in xterm? Maybe there is a way to turn this on in vim for tmux as well?

Not sure why C-2 is not mapped but if it's the same inside and outside tmux I guess it is right.

If alacritty just sends 1 then there is no way for tmux to know it is different, are you sure alacritty supports the xterm style extended keys?

**Comment by crzcrz** [comment]
Do not set `extended-keys` to `always`, it's only there to avoid breaking existing configs. All it does today is prevent applications from requesting extended key mode 2. Set it to `on`.

I just gave vim a quick test, and all `C-<num>` keys can be bound, save for `C-2`, which seems to be a bug in vim.

You can always add `pane_key_mode` variable to your status bar to see what mode the application has requested. You want to see `Ext 2` there.

**Comment by crzcrz** [comment]
I tried neovim as well, and it does not appear to enable the extended key mode at all when running in tmux, leaving the terminal in VT10x compatibility mode.

According to its documentation, it first probes for KKP, and only enables xterm extended mode if the former fails. It's possible that this probing somehow misfires.

Can you try the following in neovim prompt `call chansend(v:stderr, "\x1b[>4;2m")` and see if `C-<num>` keybindings start working.

**Comment by crzcrz** [comment]
I started digging into it, and it seems you just need to update neovim.

In v0.10.1 extended keys work as expected in tmux.
In v0.4.3 extended keys work in tmux only if manually requested from the terminal (as in my previous comment).

So, apparently, it was fixed somewhere in between those two versions.

**Comment by nicm** [comment]
We should perhaps change so that `extended-keys always` allows applications to switch into mode 2 but switching off goes into mode 1.

**Comment by The-Briel-Deal** [comment]
Thanks for the advice! I'll test a bit later today once I'm done with work and then I'll report back.

**Comment by The-Briel-Deal** [comment]
> Do not set `extended-keys` to `always`, it's only there to avoid breaking existing configs. All it does today is prevent applications from requesting extended key mode 2. Set it to `on`.
> 
> I just gave vim a quick test, and all `C-<num>` keys can be bound, save for `C-2`. The behaviour is the same inside tmux or in plain terminal, so it seems to be a bug in vim.
> 
> You can always add `pane_key_mode` variable to your status bar to see what mode the application has requested. You want to see `Ext 2` there.
> 
> We will have a Wiki page, explaining all this a bit better, it's being worked on.

Well, C-2 works outside of vim. (That may be only because nvim and alacritty support the Kitty Keyboard Protocol). I don't think its a bug with vim since it certainly works in Wezterm, Alacritty, Kitty, and with all of these in latest version of Zellij. Thanks for testing though! Hopefully I can try some of these other things in a bit.

**Comment by crzcrz** [comment]
> We should perhaps change so that `extended-keys always` allows applications to switch into mode 2 but if they turn off it goes into mode 1.

I like this idea. I will see if I have time to implement it this weekend.

**Comment by crzcrz** [comment]
@nicm can you take a look at the patch please?

[0001-Saner-behaviour-of-extended-keys-always.patch](https://github.com/user-attachments/files/17002472/0001-Saner-behaviour-of-extended-keys-always.patch)

**Comment by crzcrz** [comment]
@nicm Can you take a look at the patch please?

[0001-Saner-behaviour-of-extended-keys-always.patch](https://github.com/user-attachments/files/17002481/0001-Saner-behaviour-of-extended-keys-always.patch)

**Comment by nicm** [comment]
This looks good, I have applied this with a couple of minor changes (I introduced a temporary for the `extended-keys` option value which avoids looking it up twice and also allows some long lines to be shortened, and moved the check for n == 4 earlier). Let me know if you see any problems - it'll be in GitHub when it syncs up. Thanks!

**Comment by nicm** [comment]
Is the original issue here still a problem or was it confirmed as a vi problem?
