### ISSUE TITLE
Validation For Snap Maintenance

### ISSUE THREAD

**Issue by boukendesho** [tmux/tmux#4114]
Hello team, as we've discussed before on #4103 

can i please get an upstream nod or approval for maintaining snap packages, i wish to publish snap packages under the name **tmux** , and to get the **tmux** name, the snapcraft community is asking for upstream approval or acknowledgement officially, please comment or reply back by acknowledging that snap packages by me has received approval for unofficial way of distributing tmux in snap store, your coordination and favour will be sincerely appreciated.

Here [my snap repo](https://github.com/boukendesho/tmux-snap)

**Comment by nicm** [comment]
OK this is fine with me.
