### ISSUE TITLE
set-option -F does not capture output of commands

### ISSUE THREAD

**Issue by vdbe** [tmux/tmux#4115]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

```
$ ./tmux -V
tmux next-3.5
$ git rev-parse HEAD
c36ffcbe563bdb37a294bdab93f8d1d120484150
$ uname -sp
Linux unknown
$ echo TERM
tmux-256color
```

#### Bug
1. start and enter a new tmux server (`tmux -L testing kill-server; tmux -L testing -f /dev/null -vv`)
2. run `tmux set -gF @example  "#(echo example)"`
3. show `@example`
  ```bash
  $ tmux show-option -g @example
  @example ''
  ```

I would expect the option `@example` to contain the value `example` (+/- a newline).
The command between `#()` is being executed but the output is not captured
```bash
$ rm -f hello-world
$ tmux set -gF @example  "#(touch hello-world)"
$ file hello-world
hello-world: empty
```

The problem seems to be that the `format_job_complete` callback from https://github.com/tmux/tmux/blob/9ae69c3795ab5ef6b4d760f6398cd9281151f632/format.c#L396-L398 is not called when using `set-option` with -F resulting in `fj->out` being `NULL`.

When a `#()` is in the status bar (`set -g status-left '#(echo example)'
`) this is called from [here](https://github.com/tmux/tmux/blob/c36ffcbe563bdb37a294bdab93f8d1d120484150/job.c#L326) in `job_error_callback` (after a job error?).
```
1725808642.412788 format_replace: format 'status-left' found: #(echo example)
1725808642.412791 format_expand1: expanding format: #(echo example)
1725808642.412795 format_expand1: found #(): echo example
1725808642.412800 format_expand1: expanding format: echo example
1725808642.412806 format_expand1: result is: echo example
1725808642.413034 job_run: cmd=echo example, cwd=/home/user/projects/tmux, shell=/run/current-system/sw/bin/fish
1725808642.413397 run job 0x5bbc20: echo example, pid 222472
1725808642.413405 format_expand1: #() result: 
1725808642.413409 format_expand1: result is: 
...
1725808642.502370 job error 0x5bbc20: echo example, pid 222472
1725808642.502377 cmdq_next <global>: empty
1725808642.502381 cmdq_next </dev/pts/8>: empty
1725808642.502385 server_client_reset_state: client /dev/pts/8 mode CURSOR,WRAP
1725808642.502388 server_client_reset_state: cursor to 0,0
1725808642.502393 server_client_check_pane_buffer: pane %0 is on
1725808642.502396 @0 active pane not changed
1725808642.502406 server_signal: Child exited
1725808642.502417 job died 0x5bbc20: echo example, pid 222472
1725808642.502422 format_job_complete: 0x523990 echo example: 
1725808642.502425 free job 0x5bbc20: echo example
````

but with `tmux set -gF @example  "#(echo example)"` the job seems to be just freed from `format_job_tidy` without callback after lost client.
```
1725808887.148374 format_expand1: expanding format: #(echo example)
1725808887.148386 format_expand1: found #(): echo example
1725808887.148398 format_expand1: expanding format: echo example
1725808887.148409 format_expand1: result is: echo example
1725808887.149003 job_run: cmd=echo example, cwd=/home/user/projects/tmux, shell=/run/current-system/sw/bin/fish
1725808887.149243 job_run: cmd=echo example, cwd=/home/user/projects/tmux, shell=/run/current-system/sw/bin/fish
1725808887.149877 run job 0x165f750: echo example, pid 223181
1725808887.149896 format_expand1: #() result: 
1725808887.149908 format_expand1: result is: 
...
1725808887.163573 job write 0x165f750: echo example, pid 223181, output left 0
1725808887.163598 cmdq_next <global>: empty
1725808887.163605 cmdq_next </dev/pts/8>: empty
1725808887.163610 cmdq_next </dev/pts/4>: empty
1725808887.163617 server_client_reset_state: client /dev/pts/8 mode CURSOR,WRAP
1725808887.163622 server_client_reset_state: cursor to 0,3
1725808887.163628 server_client_check_pane_buffer: pane %0 is on
1725808887.163634 @0 active pane changed
1725808887.163639 @0 name timer already queued (460587 left)
1725808887.166307 lost client 0x1747560
1725808887.166351 format_job_tidy: echo example
1725808887.166358 free job 0x165f750: echo example
1725808887.166398 remove peer 0x1757740
1725808887.166427 unref client 0x1747560 (1 references)
```
[tmux-out-226175.log](https://github.com/user-attachments/files/16922754/tmux-out-226175.log)
[tmux-server-226175.log](https://github.com/user-attachments/files/16922755/tmux-server-226175.log)
[tmux-client-226173.log](https://github.com/user-attachments/files/16922756/tmux-client-226173.log)

**Comment by nicm** [comment]
You can't use `#()` except in the status line.
