### ISSUE TITLE
[Feature proposal] Options to customise cursor behaviour in different modes

### ISSUE THREAD

**Issue by lexurco** [tmux/tmux#4117]
Hello!

At the moment cursor styling in tmux is not very consistent. I can set the `cursor-style` option, but it reverts to block in copy-mode regardless of what I set, in the command prompt the cursor is actually hidden, and is instead emulated with reverse-video, and in other modes it behaves in yet more mysterious ways that I'll have to investigate at some point.

I am not entirely sure how to approach the issue, or if there would be any interest in fixing it at all. I did, however, go ahead, and implement an option to switch between emulated and "hardware" cursor for the command prompt on my own branch for a start. The branch: https://github.com/lexurco/tmux/tree/emulate-cursor-option

Any comments would be appreciated. Thanks!

### Required information

tmux version: `tmux next-3.5`
Platform: `OpenBSD amd64`
`$TERM`: `tmux-256color`
Logs: N/A

**Comment by lexurco** [comment]
Great! The diff does work for the copy mode. I'll return once I implement the remaining changes.

**Comment by lexurco** [comment]
I am not exactly sure when I'll be able to continue working on that. So far I've added the `prompt-cursor-{colour,style}` options. Seems to work fine. So I'll see about the modes when I have some time next.

**Comment by nicm** [comment]
I have applied my change (to OpenBSD, should be in GitHub later), if you make any further changes please open a PR. Thanks!
