### ISSUE TITLE
Horizontal split get's messed up (with alacrittty, kitty, zsh) with status-position = top

### ISSUE THREAD

**Issue by jonasdiemer** [tmux/tmux#4118]
### Issue description

Steps to reproduce:

1. Open Alacritty (or kitty)
2. Launch tmux with one-line config: `set -g status-position top`
3. Create a horizontal split (`ctrl+b "`)
4. Display some text in upper split (e.g. `cat lorem.txt`)
5. `cat` some text in lower split (needs to be enough text so it scrolls) 

As result, the split gets "messed up", i.e. the area above the split shows the split line again and text is moved. This happens with alacrity and kitty, but not with iTerm2.

Before step 5:
<img width="979" alt="image" src="https://github.com/user-attachments/assets/4cbee4d8-71e0-4a69-b9fa-493a4bc50508">

After step 5: 
<img width="979" alt="image" src="https://github.com/user-attachments/assets/cbd29471-bdd7-4522-a328-da1bf449acc5">

### Required information

* tmux version (`tmux ↓`). 3.4
* Platform (`uname -sp`). Darwin arm
[tmux-server-40282.log](https://github.com/user-attachments/files/16942217/tmux-server-40282.log)

* $TERM inside and outside of tmux (`echo $TERM`). tmux-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-server-40282.log](https://github.com/user-attachments/files/16942220/tmux-server-40282.log)
[tmux-client-40280.log](https://github.com/user-attachments/files/16942218/tmux-client-40280.log)

**Comment by nicm** [comment]
Why do you have `TERM` set to `tmux-256color` outside tmux? Set it to `xterm-256color` or maybe `alacritty`.

Does this still happen with tmux built from master?

**Comment by jonasdiemer** [comment]
Good catch on the TERM - currently not sure where it's set (it's not in my .profile or .zshrc/.bashrc, maybe related to z4h)...

Re master - just compiled tmux from GitHub HEAD. Manually set `TERM` to `xterm-256color` before launching it (not sure that makes any difference). Same result (with alacritty).
