### ISSUE TITLE
Build error: `cc1: error: unrecognized command line option "-Wno-unused-result"`

### ISSUE THREAD

**Issue by barracuda156** [tmux/tmux#4119]
Master branch added `-Wno-unused-result` flag without checking if it is supported by a compiler. This has broken the build with gcc-4.2:

```
depbase=`echo cmd-attach-session.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	ccache /usr/bin/gcc-4.2 -std=gnu99 -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"next-3.5\ \(20240712-5039be6\)\" -DPACKAGE_STRING=\"tmux\ next-3.5\ \(20240712-5039be6\)\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"next-3.5\ \(20240712-5039be6\)\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DHAVE_WCHAR_H=1 -DSTDC_HEADERS=1 -D_ALL_SOURCE=1 -D_DARWIN_C_SOURCE=1 -D_GNU_SOURCE=1 -D_HPUX_ALT_XOPEN_SOCKET_API=1 -D_NETBSD_SOURCE=1 -D_OPENBSD_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D__STDC_WANT_IEC_60559_ATTRIBS_EXT__=1 -D__STDC_WANT_IEC_60559_BFP_EXT__=1 -D__STDC_WANT_IEC_60559_DFP_EXT__=1 -D__STDC_WANT_IEC_60559_EXT__=1 -D__STDC_WANT_IEC_60559_FUNCS_EXT__=1 -D__STDC_WANT_IEC_60559_TYPES_EXT__=1 -D__STDC_WANT_LIB_EXT2__=1 -D__STDC_WANT_MATH_SPEC_FUNCS__=1 -D_TANDEM_SOURCE=1 -D__EXTENSIONS__=1 -DHAVE_BITSTRING_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIBPROC_H=1 -DHAVE_PATHS_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_UTIL_H=1 -DHAVE_SYS_SIGNAME=1 -DHAVE_LIBM=1 -DHAVE_FLOCK=1 -DHAVE_PROC_PIDINFO=1 -DHAVE_SYSCONF=1 -DHAVE_ASPRINTF=1 -DHAVE_CFMAKERAW=1 -DHAVE_FGETLN=1 -DHAVE_GETDTABLESIZE=1 -DHAVE_GETPEEREID=1 -DHAVE_GETPROGNAME=1 -DHAVE_SETENV=1 -DHAVE_STRCASESTR=1 -DHAVE_STRLCAT=1 -DHAVE_STRLCPY=1 -DHAVE_STRSEP=1 -DHAVE_EVENT2_EVENT_H=1 -DHAVE_NCURSES_H=1 -DHAVE_TIPARM=1 -DHAVE_TIPARM_S=1 -DHAVE_UTF8PROC=1 -DHAVE_B64_NTOP=1 -DHAVE_DAEMON=1 -DHAVE_FORKPTY=1 -DHAVE___PROGNAME=1 -DBROKEN___DEAD=1 -DBROKEN_CMSG_FIRSTHDR=1 -I.  -DUTF8PROC_EXPORTS -D_DARWIN_C_SOURCE -DNCURSES_WIDECHAR -DTMUX_VERSION='"next-3.5 (20240712-5039be6)"' -DTMUX_CONF='"/opt/local/etc/tmux.conf:~/.tmux.conf:$XDG_CONFIG_HOME/tmux/tmux.conf:~/.config/tmux/tmux.conf"' -DTMUX_LOCK_CMD='"lock -np"' -DTMUX_TERM='"screen-256color"' -DDEBUG -iquote.      -I/opt/local/include -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes -Wno-unused-result -Wno-format-y2k -Wno-deprecated-declarations -Wno-cast-align  -pipe -Os -arch ppc -MT cmd-attach-session.o -MD -MP -MF $depbase.Tpo -c -o cmd-attach-session.o cmd-attach-session.c &&\
	mv -f $depbase.Tpo $depbase.Po
cc1: error: unrecognized command line option "-Wno-unused-result"
make: *** [arguments.o] Error 1
make: *** Waiting for unfinished jobs....
cc1: error: unrecognized command line option "-Wno-unused-result"
make: *** [alerts.o] Error 1
cc1: error: unrecognized command line option "-Wno-unused-result"
make: *** [cfg.o] Error 1
cc1: error: unrecognized command line option "-Wno-unused-result"
make: *** [cmd-attach-session.o] Error 1
cc1: error: unrecognized command line option "-Wno-unused-result"
make: *** [attributes.o] Error 1
cc1: error: unrecognized command line option "-Wno-unused-result"
make: *** [client.o] Error 1
```

`tmux` 3.4 builds fine with the same compiler. Could this be fixed?

**Comment by nicm** [comment]
GCC 4.2 has not been supported since 2008. If you use 4.4 or later it will work.

**Comment by barracuda156** [comment]
Well, it builds fine with gcc-4.2, if you just drop this one warning flag. Is it worth breaking it for this?

I have gcc-14 on the machine, but I do not see a point to force everyone to install a new gcc. Old macOS has gcc-4.2 with Xcode, and anything later requires to build it. On some G4 machine is may take many hours. On a G3 possibly days.

**Comment by nicm** [comment]
I don't really see all that much point in carrying around a workaround for a 15 year old compiler when the tiny number of people this affects can use a newer compiler, an older tmux or just take the warning away themselves. But TBH I don't care too much so if you make a PR to check for the warning I will add it.

**Comment by kenlau46** [comment]
`-Wno-unused-result` is related to `enable_debug` and default is set `yes` (in `configure.ac`) in master build.

The debug flag can be disabled with `$ ./configure --enable-debug=no`, but I found the setting was not respected if build from `master`. Checking the git history and looks like it is related to `733185d0a93b608f5c2f5396e48643b1f97b2c23`.

Shouldn't the user choice being respected instead of always enable? If user choice should be respected, I could help to fix it.

**Comment by nicm** [comment]
Builds from master default to debug builds, only release builds are not debug builds. I don't mind if it can be turned off but the default should be enabled for master.

**Comment by barracuda156** [comment]
If it will be possible to turn that off from a user side, this perfectly solves the issue. Default behavior needs not be changed, of course.

**Comment by kenlau46** [comment]
Hi, sorry for the delay. I attached the fix as a patch file. If you prefer a pull request I could create one later today. The default value of `--enable-debug` is preserved (i.e. `yes` if no specified in non-release build) 

[tmux_4119_0001.patch](https://github.com/user-attachments/files/17005717/tmux_4119_0001.patch)

**Comment by nicm** [comment]
Nice one, applied now, thanks!
