### ISSUE TITLE
Replace `.tmux.conf` with `.config/tmux/tmux.conf`  in the wiki

### ISSUE THREAD

**Issue by Managor** [tmux/tmux#4120]
### Issue description

It would be better if the wiki listed file locations that don't litter the home folder with dotfiles

**Comment by nicm** [comment]
No, .tmux.conf is the default location.

**Comment by Managor** [comment]
The issue is that it litters the home folder. Documenting better that .config location exists helps reduce that.

**Comment by kenlau46** [comment]
It breaks existing user if changing the config file path, which is a big NO.

Imagine your tmux config does not apply after system upgrading, the first thing you will do is not checking the man page or debugging with strace, but opening ticket in GitHub, which will be littered by many users with the same issue.

The purpose of dot file is to hide the file from daily usage, like `ls`
