### ISSUE TITLE
Feature: Finer control over set-clipboard / copy-selection behaviour

### ISSUE THREAD

**Issue by hetmankp** [tmux/tmux#4123]
### Issue description

Current tmux behaviour means the set-clipboard option determines both the OSC 52 security level, and whether copying text into the tmux buffer also automatically sends it to the terminal emulator via OSC 52. This is a problem if one would like to use different shortcuts to copy into the tmux buffer and into the system clipboard by using OSC 52, without these two behaviours overlapping with each other.

### Solutions

Two possible solutions to tackle this issue:

1. Provide a different configuration options to manage OSC 52 security vs the option used to determine if copied data should be automatically sent via OSC 52. Unfortunately right now, setting `set-clipboard` to `off`, also means that `copy-pipe` is not able to send OSC 52 messages to the terminal emulator. The most backwards compatible solution would probably be to create a new config option, for example called `send-to-clipboard` and have it `on` by default. This setting would determine if tmux should send copied data to the clipboard regardless of security level. This would ensure existing configurations continue working as they currently do.
2. Provide an alternative to `copy-selection` and `copy-selection-and-cancel` etc (e.g. `copy-selection-no-send` ?). These new commands would copy a selection to the tmux buffer but not send it onto the clipboard.

### Required information

* tmux version (`tmux -V`): `tmux next-3.5`
* Platform (`uname -sp`): `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color`, `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): N/A

**Comment by nicm** [comment]
I'd say add a flag to `copy-selection` and friends (like `-o` for `next-prompt`) which skips setting the clipboard.

**Comment by hetmankp** [comment]
Yes I like that better than option no. 2. Is this something you'd like to see a pull request for?

**Comment by nicm** [comment]
It would certainly help :-).

**Comment by hetmankp** [comment]
Great, I'll try to take a look at this soon.
