### ISSUE TITLE
[Feature request] Preview in choose-tree take up available space

### ISSUE THREAD

**Issue by avesst** [tmux/tmux#4124]
Hi,

Searched around for this but couldn't find anything. I would like the ability to have the preview pane in the `choose-tree` (I think it's called - session switcher, `prefix+s`) view span the full available space below the list of session.

I realized this might be handy when I had the log of a long running Ansible job in another session and quickly wanted to glance over on it.

Not sure what else to add, I think that's all?

**Comment by nicm** [comment]
TBH I think the size is fine, its only meant to give you an idea of what is in the pane. Even if we changed it it'd still be too big or too small for some circumstance.

**Comment by nicm** [comment]
Keys to make it scroll up or down might be more flexible if you do want to use it for this IMO and probably not that hard to implement, although if there are multiple panes shown I guess it would need to scroll them all. I'm not convinced it is something that would get a lot of use though...

**Comment by maetthew** [comment]
> TBH I think the size is fine, its only meant to give you an idea of what is in the pane. Even if we changed it it'd still be too big or too small for some circumstance.

Sorry, didn't mean a change in default behaviour, rather a config option.

I understand that it's meant to only give an idea, my idea is to give it another potential use.

**Comment by nicm** [comment]
I had a look at this and actually it is pretty easy and works better than I expected, please try this (press `v`): [tmux-preview.diff.txt](https://github.com/user-attachments/files/17201270/tmux-preview.diff.txt)

**Comment by avesst** [comment]
@nicm Works great, thanks :) Is it possible to configure so `MODE_TREE_PREVIEW_BIG` is the default behaviour?

![image](https://github.com/user-attachments/assets/bc04773b-2fc9-4384-9ac3-fcf24cc0d789)

**Comment by nicm** [comment]
If you try this instead then `-NN` will start in "big" mode: [tmux-preview2.diff.txt](https://github.com/user-attachments/files/17202488/tmux-preview2.diff.txt)

**Comment by avesst** [comment]
@ncim Perfect! Thank you very much :)

**Comment by nicm** [comment]
Great - applied to OpenBSD now, will be in GitHub later. Thanks!
