### ISSUE TITLE
[BUG] Can’t paste from another program

### ISSUE THREAD

**Issue by 0xJWLabs** [tmux/tmux#4125]
### Issue description

Does anyone know how to fix this?

So currently my tmux can copy and paste within tmux, when I copy from tmux I can paste it on other program, but when I copy from other program, I can’t paste it on tmux unless i set mouse = off.

- Version: tmux 3.4
$TERM = wezterm <- outside
$TERM = tmux-256color <- inside tmux
Platform: Windows + WSL2

**Comment by nicm** [comment]
There is no way for tmux to know you have copied from another program unless you ask it to read the clipboard with `refresh-client -l`.
