### ISSUE TITLE
Feature request: add support to querying the cursor color (OSC12)

### ISSUE THREAD

**Issue by aymanbagabas** [tmux/tmux#4127]
### Issue description

It would be nice to add support for querying the cursor color. As of Tmux 3.4, users can query the fg/bg colors using OSC10/OSC11, but not OSC12. The [Xterm control sequences specs](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands) also uses `OSC 12 ?` to query the cursor color.

Here's a picture from Ghostty with the cursor color changed

<img width="358" alt="image" src="https://github.com/user-attachments/assets/9e1eaee7-0d4a-4e5c-bbc1-44936127ef60">

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `tmux 3.4`
* Platform (`uname -sp`). `Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`). `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`). `N\A`

**Comment by nicm** [comment]
OSC 12 already works if you change the cursor colour in tmux.

**Comment by aymanbagabas** [comment]
> OSC 12 already works if you change the cursor colour in tmux.

Ah, I see. I updated the title and description accordingly 🙂

**Comment by nicm** [comment]
What is the use case for this? Do applications use it and what for?

**Comment by aymanbagabas** [comment]
For example, Neovim supports setting the cursor color advertised by the `Cs` terminfo capability. I would like to use different colors for different Vim modes. For example, green during normal mode, blue in insert mode, etc. Right now, you could use Tmux passthrough DCS sequence to change the color _globally_, and would be neat to make this work on a pane to pane basis.

See this comment https://github.com/neovim/neovim/blob/ff7832ad3fce55671ac4032716164ada0350b0ec/src/nvim/tui/tui.c#L2348

**Comment by nicm** [comment]
I'll add this to the todo list but I'm not sure I would expect it soon.

**Comment by nicm** [comment]
If anyone wants to add it, it is a matter of duplicating how OSC 10 and 11 work - look at `tty_send_requests` and `tty_keys_colours`.
