### ISSUE TITLE
tmux 3.4 doesn't build on macOS 15 with Xcode 16

### ISSUE THREAD

**Issue by eschaton** [tmux/tmux#4129]
I tried to build tmux-3.4 on macOS 15 with Xcode 16. The build system chose to use `"compat/queue.h"` correctly, however using the same `_SYS_QUEUE_H_` include guard as used in `<sys/queue.h>` means that `"combat/queue.h"` content isn't actually being used.

It looks like this was addressed in mainline in 775789fbd5c4f3aa93061480cd64e61daf7fb689 which seems like low-hanging fruit if there's a 3.4.1 maintenance release.

**Comment by nicm** [comment]
3.5 will probably be after the next OpenBSD release and will include it.
