### ISSUE TITLE
Can the behavior of the mouse be the same as Zellij

### ISSUE THREAD

**Issue by x93008** [tmux/tmux#4132]
### Issue description

Can the behavior of the mouse be the same as Zellij? I hope to make the mouse scroll to see the history log, click and drag to copy, release the mouse to complete the copy, and not exit the history log interface

**Comment by bfrg** [comment]
Can you specify what Zellij' behavior is? Regarding scrolling the scrollback buffer, this should work out of the box. You need to enable mouse in tmux though:
```
set-option -g mouse on
```

If you want to stay in copy mode after clicking with the mouse, try these here (notice, the first one requires `xclip`):
```tmux
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe 'xclip -i -selection primary'
bind-key -T copy-mode-vi DoubleClick1Pane { select-pane ; send-keys -X select-word ; run-shell -d 0.3 ; send-keys -X copy-pipe }
bind-key -T copy-mode-vi TripleClick1Pane { select-pane ; send-keys -X select-line ; run-shell -d 0.3 ; send-keys -X copy-pipe }
```
