### ISSUE TITLE
"lost server" when invoking tmux 2.3 from zsh line editor widget

### ISSUE THREAD

**Issue by wilywampa** [tmux/tmux#414]
I'm running tmux 2.3 in OS X 10.5.5 and iTerm2 2.9.20160510.

I used to be able to run a tmux command in zsh's line editor but it broke at some point. I bisected down and found the cause is somewhere between https://github.com/tmux/tmux/commit/0a2ef2b (latest working commit) and https://github.com/tmux/tmux/commit/260de2cb5e384a0cf193b5f9f996fa8fb2c5aaf8 (first bad commit) but I couldn't compile the commits between those and the diff is 1000 lines log.

Here's a minimal example to reproduce (run and press CTRL+T):

    split() { tmux split-window }; zle -N split; bindkey '^T' split

I compared the client log files generated from running `tmux split-window` in a normal shell versus in the ZLE function and found two differences. First, messsage 102, which is `MSG_IDENTIFY_TTYNAME`, is 13 bytes for the regular shell and 1 byte for the ZLE command. Second, the regular shell gets a message 203 (`MSG_EXIT`) before "client loop exit" and the ZLE version does not.

Could not having a valid tty name cause this? Any other suggestions for trying to debug?

**Comment by nicm** [comment]
Where are the tmux logs? Is there a core file?

**Comment by wilywampa** [comment]
I should clarify - the tmux server isn't completely crashing; it just prints "server lost" in the current pane. I can continue to use the session without any other problems (so no core file). Here are -vvvv logs: https://gist.github.com/wilywampa/12d45470eb235121c27ab8f19cc6c068

The first client log is `split-window` in a regular shell (which works) and the second is in ZLE.

Thanks!

**Comment by wilywampa** [comment]
I think there's something to my thought about the tty name. If I change the command to:

    split() { tmux -vvvv split-window < /dev/null }; zle -N split; bindkey '^T' split

it works just fine!

**Comment by nicm** [comment]
No, ttyname does not have to be set, and if you had shown the log for working commmand with </dev/null as well we would probably see it has an empty MSG_TTYNAME as well.

Can you try a git pull to make sure you have 7411f21c5f9dbc64d98538ad3df8d4b25e1988ba and see if that fixes it?

**Comment by nicm** [comment]
Are you sure this server log actually matches these two client (working and nonworking) logs? There are two clients in the server log, but neither of them look like the second, nonworking client.

**Comment by wilywampa** [comment]
Looks like that commit solved the problem. Thanks again!

I thought the nonworking client joins the server here: https://gist.github.com/wilywampa/12d45470eb235121c27ab8f19cc6c068#file-tmux-server-18196-log-L3764

I could be wrong. I can generate new logs if you think that would be valuable.

**Comment by nicm** [comment]
Ah yes you are right, sorry. But if it is now fixed then don't worry about it.
