### ISSUE TITLE
BUG | New in version 3.5 | Custom key maps not working using Ctrl.

### ISSUE THREAD

**Issue by airvzxf** [tmux/tmux#4140]
### Duplicate or similar issue
* https://github.com/tmux/tmux/issues/4113

#### Summary
Creating a keyboard shortcut in the “.tmux.conf” customization file does not work if the key pressed starts with Control (Ctrl).

#### Long description
I have been using the shortcut mentioned below for years to open new windows. The problem is that today, after the update from version 3.4 to 3.5, this shortcut no longer works.

```config
# Create new window with Ctrl+T
bind -n C-T new-window -c "#{pane_current_path}"
```

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

> CHANGES FROM 3.4 TO 3.5
> * Revamp extended keys support to more closely match xterm and support mode 2
  as well as mode 1. This is a substantial change to key handling which changes
  tmux to always request mode 2 from parent terminal, changes to an unambiguous
  internal representation of keys, and adds an option (extended-keys-format) to
  control the format similar to the xterm(1) formatOtherKeys resource.
> * Mouse move keys are not useful as key bindings because we do not turn them on
  unless the application requests them. Ignore them so they do not cause the
  prefix to be canceled
Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

#### Exploring 1
Create a new keyboard shortcut, changing the Tmux command, to rule out that the issue was the command, and it doesn't work either. The shortcut Alt+Shift+T works as expected because if I only press Alt+T it is not working. I test the Ctrl+T, Ctrl+Alt+T, and Ctrl+Shift+T, but it didn't work to zoom the pane. Furthermore, I inverted the commands in both shortcuts, and only corks the Alt+Shift+T.

```config
# Create new window with Ctrl+T
#bind -n C-T new-window -c "#{pane_current_path}"
bind -n C-T resize-pane -Z
bind -n M-T next-window
```

#### Exploring 2

The issue is not the key Ctrl because it works as a key bind. If I press Ctrl+b ➟ c, Tmux creates a new window. Maybe it is part of the problem because I saw the changes in the source code and saw some changes related to the key bin and Ctrl conditions.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  * tmux 3.5
* Platform (`uname -sp`).
  * Linux unknown
  * `uname -a` | Linux laptop-archlinux 6.10.10-arch1-1 # 1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux
* $TERM inside and outside of tmux (`echo $TERM`).
  * tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
  * I deleted the logs and follow the above commands. I create manually a new window, then use the Alt+T to go to next windows. Furthermore, I try the Ctrl+T, Ctrl+Alt+T, and Ctrl+Shift+T to do a zoom in the pane but it didn't work.
  * [tmux-client-20614.log](https://github.com/user-attachments/files/17174767/tmux-client-20614.log)
  * [tmux-out-20616.log](https://github.com/user-attachments/files/17174768/tmux-out-20616.log)
  * [tmux-server-20616.log](https://github.com/user-attachments/files/17174769/tmux-server-20616.log)

**Comment by nicm** [comment]
Previously `C-T` and `C-t` were the same, now they are not. Change your bindings to `C-t`.

**Comment by airvzxf** [comment]
Shame on me 😓; I didn't see the documentation or research in depth. It works.
