### ISSUE TITLE
changing prefix key doesn't work in 3.5 anymore

### ISSUE THREAD

**Issue by mbunkus** [tmux/tmux#4141]
### Issue description

I've been using the following snippet for ages in order to change my prefix key to C-Z:

```
set -g prefix C-Z
```

This stopped working after upgrading to 3.5. Downgrading back to 3.4 & it immediately starts working again.

In 3.5 hitting C-Z simply passes C-Z through to the application, just as if the prefix had not been changed at all. However, C-B doesn't work as the prefix anymore either as soon as the line above is active. Meaning with the line active, no key is acting as prefix anymore.

I have verified that solely using this line causes the effect by using a newly created user account in a newly created home directory. The only tmux config option I've activated was the one listed above.

How to reproduce:

1. Create a blank new user account, e.g. with `sudo useradd -m clean-new-user`
2. Become the user with `sudo -i -u clean-new-user`
3. Create settings file with `echo set -g prefix C-Z > prefix.conf`
4. Start tmux 3.5 with the settings file with `tmux -f prefix.conf`
5. Try using C-Z as the prefix key & observe that it simply doesn't work
6. Exit out of tmux
7. Downgrade to 3.4
8. Start tmux 3.4 as in step 4 & observe that it works again

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.5` (Arch package `3.5-1`; last one I had working & which I confirmed via downgrading was Arch's `3.4-10`)
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`): outside `putty-256color`, inside `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): client & server logs are [here](https://gist.github.com/mbunkus/5b5b5b12181fdbd66cba5dc3395c073f)

**Comment by nicm** [comment]
`C-z`

**Comment by mbunkus** [comment]
That works, thanks. And it works with 3.4, too, which is kind of important for me as I share config files between various hosts.

I honestly don't remember why I had upper-case Z in there for such a long time.
