### ISSUE TITLE
tmux 3.5 doen't run run-shell commands with /bin/sh anymore

### ISSUE THREAD

**Issue by gpakosz** [tmux/tmux#4143]
### Issue description

The documentation still says

> Execute shell-command using /bin/sh or (with -C) a tmux command in the background without creating a window.

However tmux 3.5 doesn't run `run-shell` commands with `/bin/sh` anymore.
Which is breaking my Oh my tmux! configuration.

I compiled both tmux `3.4 `and `3.5` which I respectively named `tmux-3.4` and `tmux-3.5`.

Then I used the following troubleshoot steps with tmux `3.4`:

```
$ ./tmux-3.4 -f /dev/null -vvv
# now I'm inside a tmux pane
$ ./tmux-3.4 run-shell 'echo $fish_pid'
```
Which prints nothing

However, with tmux `3.5`:
```
$ ./tmux-3.5 -f /dev/null -vvv
# now I'm inside a tmux pane
$ ./tmux-3.5 run-shell 'echo $fish_pid'
```
Which prints a PID.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `3.5`.
* Platform (`uname -sp`): `Darwin i386`.
* $TERM inside and outside of tmux (`echo $TERM`): `xterm-256color`.
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-3.4-client-33952.log](https://github.com/user-attachments/files/17180846/tmux-3.4-client-33952.log)
[tmux-3.4-out-33954.log](https://github.com/user-attachments/files/17180847/tmux-3.4-out-33954.log)
[tmux-3.4-server-33954.log](https://github.com/user-attachments/files/17180848/tmux-3.4-server-33954.log)

[tmux-3.5-client-34047.log](https://github.com/user-attachments/files/17180849/tmux-3.5-client-34047.log)
[tmux-3.5-out-34049.log](https://github.com/user-attachments/files/17180850/tmux-3.5-out-34049.log)
[tmux-3.5-server-34049.log](https://github.com/user-attachments/files/17180851/tmux-3.5-server-34049.log)

**Comment by gpakosz** [comment]
I bisect it to
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
d39dcea30ad2814a70a1f65e43468a78df4df8e5
fc84097379d8d53481303d021a981c724082e94d
We cannot bisect more!
```

On macOS, there are commits I can't build so I skipped them

**Comment by nicm** [comment]
You can change `default-shell` to `/bin/sh` to use it, but ultimately the program's authors will need to fix it to remove this assumption.

**Comment by gpakosz** [comment]
This is such a set back 😢

I'm going to try to workaround this new behaviour by explictly using `sh -c`.
Welcome to shell escape hell 🔥

**Comment by nicm** [comment]
l know but not using default-shell was an omission in tmux and scripts should really not assume what shell they should be run with.

I guess we could add a flag to run-shell etc to set shell for that command.

**Comment by gpakosz** [comment]
> and scripts should really not assume what shell they will be run with

The manual says `/bin/sh`. That's not really an assumption 🤔

**Comment by nicm** [comment]
Yeah you're right actually, we should probably stick with `/bin/sh` for `run-shell` and only change it for popups.

**Comment by nicm** [comment]
Does this work? [x.diff.txt](https://github.com/user-attachments/files/17181283/x.diff.txt)

**Comment by gpakosz** [comment]
It works for me as far as I can tell

**Comment by nicm** [comment]
Great, I have applied this to OpenBSD now, it will be in GitHub when it syncs up.

**Comment by gpakosz** [comment]
Will there be a point release?

**Comment by nicm** [comment]
Probably might as well but let's see if anything else comes up by the end of the week.

**Comment by nicm** [comment]
I made a tmux-3.5a branch you can use for the moment.

**Comment by nicm** [comment]
This will be in 3.5a sometime this week.
