### ISSUE TITLE
`client_prefix` isn't reset after `prefix-timeout` elapses

### ISSUE THREAD

**Issue by mkoskar** [tmux/tmux#4145]
When set `prefix-timeout` period elapses, `client_prefix` format variable doesn't seem to reset.

* it will get reset only after e.g., a key is pressed
* setting `status-interval` doesn't help

To reproduce:

1) start tmux
```
$ tmux -L test -f /dev/null new \; \
    set prefix-timeout 1000 \; \
    set status-left '#{?client_prefix,^, } '
```

2) hit prefix key (`^B`)
3) observe `^` character appear in the left-bottom corner
4) it is expected `^` disappears in 1s (wait for 1s or longer)
5) press any key, `^` disappears

----

* `tmux -V` = `tmux 3.5`
* `uname -sp` = `Linux unknown`
* `$TERM` = `xterm-256color` / `tmux-256color`

**Comment by nicm** [comment]
This is expected, the timeout is not a timer, tmux does not wake up in order to check it, it is only checked when a key is pressed.

**Comment by nicm** [comment]
OK I don't have any plans to change this, although I don't think it would be a very big change to make it use a timer like `repeat-time` (so check if the timer has expired rather than comparing with the activity time) if you wanted to have a go and open a PR.
