### ISSUE TITLE
Requesting modifyOtherKeys level 1 mode in tmux 3.5 produces level 2 sequences

### ISSUE THREAD

**Issue by craigbarnes** [tmux/tmux#4146]
Running the following command in tmux 3.5:

```sh
tmux split-window sh -c 'printf "\033[>4;1m"; cat -v'
```

...now produces `^[[27;2;65~` when <kbd>Shift</kbd>+<kbd>a</kbd> is pressed, despite xterm (and foot, etc.) only producing `A` for the same mode/input.

tmux appears to be producing `modifyOtherKeys` level 2 sequences when only level 1 has been requested. This is making tmux's input handling almost unusable in [dte](https://github.com/craigbarnes/dte), because it doesn't request or expect level 2 sequences. I think the input rework in 3.5 is causing several other issues too, although I haven't figured out exactly what they are yet (more to come).

Other info:

* `tmux -V`: tmux 3.5 (git commit 25b1cc1e8e5b78fab718fa797f2cf2ccc310079e also tested)
* `uname -sm`: Linux x86_64
* `$TERM` inside tmux: `tmux-256color`
* `$TERM` outside tmux: `foot`

**Comment by nicm** [comment]
Does this fix it? If not, please include logs.
~~~~
Index: input-keys.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/input-keys.c,v
diff -u -p -r1.99 input-keys.c
--- input-keys.c	1 Oct 2024 06:15:47 -0000	1.99
+++ input-keys.c	1 Oct 2024 06:44:29 -0000
@@ -556,6 +556,11 @@ input_key_mode1(struct bufferevent *bev,
 	     (onlykey >= '2' && onlykey <= '8') ||
 	     (onlykey >= '@' && onlykey <= '~')))
 		return (input_key_vt10x(bev, key));
+
+
+	/* Shift keys becomes unshifted. */
+	if ((key & KEYC_SHIFT) && onlykey >= 'A' && onlykey <= 'Z')
+		return (input_key_vt10x(bev, key & ~KEYC_SHIFT));

 	/*
 	 * A regular key + Meta. In the absence of a standard to back this, we

**Comment by nicm** [comment]
@crzcrz can you look at this as well please if you have a moment.

iTerm2 appears to always send `A` for `S-a`, but xterm does seem to send `^[[27;2;65~` in mode 2 so perhaps iTerm2 is incorrect.

**Comment by crzcrz** [comment]
@nicm the problem was already clear to me from the 3.5 thread. When the parent terminal sends `S-<Capital Letter>` instead of just `<Capital Letter>`, we don’t correctly convert it for mode 1 output. At the first glance your patch is correct, I will take a more detailed look later in the evening today.

**Comment by nicm** [comment]
OK good stuff, thanks.

**Comment by crzcrz** [comment]
@nicm I gave this some thought and I believe the condition should be extended to all keys, not just letters.

What do you think of this?

[0001-Avoid-Shift-modifier-when-not-expected-in-mode-1.patch](https://github.com/user-attachments/files/17212840/0001-Avoid-Shift-modifier-when-not-expected-in-mode-1.patch)

**Comment by nicm** [comment]
Yes, I think that is right, there are keys like `S-{` as well.

**Comment by nicm** [comment]
I have applied this to OpenBSD now, it'll be it GitHub later. I'll put it in 3.5a as well when I get round to that. Thanks!

**Comment by vbauerster** [comment]
There are still some issues with build from 38c38f1c64ef72d3e00d30c7409ddb1c435a0eeb:

- <kbd>shift</kbd>+<kbd>tab</kbd> is reported as `tab` in mode 1.
- default capital letter bindings, for example `C` and `E` do not work.
- in command prompt pressing `shift+letter` is ignored.

In following test I pressed <kbd>shift</kbd>+<kbd>c</kbd> in the command prompt:
```
❯ tmux command-prompt -k -p key 'list-keys -Tprefix -1 "%%"'
unknown key: S-C
```

**Comment by crzcrz** [comment]
Our fix wasn’t entirely correct. I believe we need to lose the Shift when receiving a key, not when sending it out.

This will remap `Shift-A` to just `A` in mode 2, but that is probably OK, as many terminals do not send Shift as the only modifier for character keys anyway.

Until we have fixed this properly, a workaround would be to configure tmux to only request mode 1, by overriding the `Eneks` terminal feature.

**Comment by crzcrz** [comment]
We really rushed yesterday with the fix. The new fix addresses the issue at the source and unifies handling of shifted keys, regardless of what the outside terminal sends in.

I tested this by configuring iTerm to send `\033[27;2;65~` for `Shift-a` and `\033[27;2;67~` for `Shift-c`, and confirmed correct behaviour. `S-Tab` works, default bindings work, and capital letters can be entered in the command prompt.

@vbauerster would it be too much to ask you to confirm that the patch works as expected?

[0001-Fix-handling-of-shifted-keys.patch](https://github.com/user-attachments/files/17234809/0001-Fix-handling-of-shifted-keys.patch)

**Comment by vbauerster** [comment]
Quick test in foot terminal revealed no problems with the patch applied. I'll report here if I find something wrong.
Thank you!

**Comment by nicm** [comment]
I've applied this one instead now, you can try `tmux-3.5a` branch. Thanks!
