### ISSUE TITLE
Bindings for C-i and C-m don't work in 3.5

### ISSUE THREAD

**Issue by odormond** [tmux/tmux#4147]
### Issue description

Bindings for C-i and C-m don't work in 3.5.

With this simple config:
```
set -g prefix C-o
set -g status on
bind C-i previous-window
bind C-o last-window
bind C-p next-window
bind C-m last-window
```

Press `C-o c` 2 times to have a total of three window. Then press `C-o C-o` to have the middle one active.
Now, pressing `C-o C-i` does nothing instead of making the first window active.
Pressing `C-o C-p` correctly makes the third one active (as the second one was still active).
Pressing `C-o C-m` does nothing instead of making the second active again.

The sequence above (plus three `C-d` to exit all the shells) is recorded in the attached logs below.

### Required information

* tmux version: next-3.6 (commit 826ba515)
* Platform: Linux x86_64
* $TERM inside tmux: tmux-256color
* $TERM outside of tmux: xterm-256color (gnome-terminal)
* Logs from tmux (and tmux.conf used): 
[tmux-conf-and-logs.zip](https://github.com/user-attachments/files/17226945/tmux-conf-and-logs.zip)

### Additional information

Apparently this is similar to the issue addressed by commit 31b6c9356c2afb7d8677dbf1b36220320fa78cc6 about binding of C-h. At least applying the following patch fixes it:
```patch
diff --git a/input-keys.c b/input-keys.c
index 80a477f9..553c4d59 100644
--- a/input-keys.c
+++ b/input-keys.c
@@ -610,9 +610,7 @@ input_key(struct screen *s, struct bufferevent *bev, key_code key)
 	 * key and no modifiers.
 	 */
 	if (!(key & ~KEYC_MASK_KEY)) {
-		if (key == C0_HT ||
-		    key == C0_CR ||
-		    key == C0_ESC ||
+		if (key == C0_ESC ||
 		    (key >= 0x20 && key <= 0x7f)) {
 			ud.data[0] = key;
 			input_key_write(__func__, bev, &ud.data[0], 1);
diff --git a/tty-keys.c b/tty-keys.c
index 9a0f3ea6..13ee73d5 100644
--- a/tty-keys.c
+++ b/tty-keys.c
@@ -892,8 +892,6 @@ first_key:
 	 */
 	onlykey = key & KEYC_MASK_KEY;
 	if (onlykey < 0x20 &&
-	    onlykey != C0_HT &&
-	    onlykey != C0_CR &&
 	    onlykey != C0_ESC) {
 		onlykey |= 0x40;
 		if (onlykey >= 'A' && onlykey <= 'Z')
```
You can find the patch and the logs for the same sequence of key presses with the patch applied in this archive: 
[fixed-tmux-logs-and-patch.zip](https://github.com/user-attachments/files/17227097/fixed-tmux-logs-and-patch.zip)

**Comment by nicm** [comment]
This change would mean that `C-i` and `Tab` and `C-m` and `Enter` are always the same and cannot be different even when the terminal supports it. I don't mind doing this, but it needs to be only when `extended-keys` is `off`, so you will need to add a check for this to your change.

I think the `C-h`/`BSpace` change is actually also incorrect for the same reason so we probably also want to add `C0_BS` back too.

Alternatively, you can change your bindings to use `Tab` and `Enter` which is what the terminal is sending for `C-i` and `C-m`, or (if your terminal supports it) set `extended-keys on` so tmux receives `C-i` and `C-m`.

**Comment by jakubbortlik** [comment]
It may be related to this issue that pressing `CTRL-;` (control+semicolon) does not work in version 3.5 as it used to in e.f., [v 3.4-9](https://archive.archlinux.org/packages/t/tmux/tmux-3.4-9-x86_64.pkg.tar.zst). In 3.4-9 I was able to map `<ctrl-;>` in neovim to a certain action, however, in Tmux 3.5, `ctrl-;` emits just a plain `;`.
I've tried compiling `next-3.6` with the above patch and in that version, `ctrl-;` works again.

**Comment by odormond** [comment]
First of all, my patch break the command line, i.e, with my test config, doing `C-o :` and then typing some tmux command, you cannot use tab to complete nor enter to validate the input. :-/

I will have a look at the extended keys. So far the setting doesn't seem to do anything with gnome-terminal on ubuntu 22.04 so I will need to find more time to see what's going on.

Using `Tab` and `Enter` in place of `C-i` and `C-m` does indeed fix my binding at least. :-)

**Comment by nicm** [comment]
You could use xterm, I don't think gnome-terminal supports it.

**Comment by crzcrz** [comment]
> It may be related to this issue that pressing `CTRL-;` (control+semicolon) does not work in version 3.5 as it used to in e.f., [v 3.4-9](https://archive.archlinux.org/packages/t/tmux/tmux-3.4-9-x86_64.pkg.tar.zst). In 3.4-9 I was able to map `<ctrl-;>` in neovim to a certain action, however, in Tmux 3.5, `ctrl-;` emits just a plain `;`.
> 
> I'm using Manjaro Linux with the Sway window manager (v 1.9).

I can confirm that you can bind `C-;` in neovim without issues, inside or outside tmux. I myself use this keybinding daily to invoke embark in Emacs, so I would have noticed if it broke.

To debug this further we'd need to know what your terminal sends when you press this key.

Can you do the following and show us the output when pressing `C-;` please?

```
$ showkey -a
```

And then

```
$ printf "\033[>4;2m"
$ showkey -a
```

**Comment by jakubbortlik** [comment]
> Can you do the following and show us the output when pressing `C-;` please?
> ```
> $ showkey -a
> ```
> 
> And then
> 
> ```
> $ printf "\033[>4;2m"
> $ showkey -a
> ```

Thank you for taking the time to look at this!

I forgot to mention that I'm using the [foot](https://codeberg.org/dnkl/foot) terminal.

This is what happens when I type the commands and press `ctrl-;` in just `bash`:
```
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^[[27;5;59~ 	27 0033 0x1b
 	91 0133 0x5b
 	50 0062 0x32
 	55 0067 0x37
 	59 0073 0x3b
 	53 0065 0x35
 	59 0073 0x3b
 	53 0065 0x35
 	57 0071 0x39
 	126 0176 0x7e
^D 	 4 0004 0x04
$ printf "\033[>4;2m"
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^[[27;5;59~ 	27 0033 0x1b
 	91 0133 0x5b
 	50 0062 0x32
 	55 0067 0x37
 	59 0073 0x3b
 	53 0065 0x35
 	59 0073 0x3b
 	53 0065 0x35
 	57 0071 0x39
 	126 0176 0x7e
```
Interestingly, after typing `printf "\033[>4;2m"` I'm not able to terminate the program with `Ctrl-D` anymore.

When I follow the same steps in Tmux 3.4-9, I get the following (notice, that before running `printf ...`, `Ctrl-;` does not seem to have any output at all, but my `<c-;>` mapping in Nvim works):
```
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^D        4 0004 0x04
$ printf "\033[>4;2m"
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^[[59;5u         27 0033 0x1b
         91 0133 0x5b
         53 0065 0x35
         57 0071 0x39
         59 0073 0x3b
         53 0065 0x35
        117 0165 0x75
^D        4 0004 0x04
```

And now with Tmux 3.5 (compiled from source), I'm getting the following (the behaviour is the same before and after running `printf "\033[>4;2m"`):
```
$ showkey -a

Press any keys - Ctrl-D will terminate this program

;        59 0073 0x3b
^D        4 0004 0x04
$ printf "\033[>4;2m"
$ showkey -a

Press any keys - Ctrl-D will terminate this program

;        59 0073 0x3b
^D        4 0004 0x04
```

**Comment by crzcrz** [comment]
@jakubbortlik the fact that after switching on mode 2 you can still use `C-D` to exit `showkey -a` suggests that the extended key support is disabled in tmux. Do you have `extended-keys` set to `on` in your `tmux.conf`?

**Comment by jakubbortlik** [comment]
> @jakubbortlik the fact that after switching on mode 2 you can still use `C-D` to exit `showkey -a` suggests that the extended key support is disabled in tmux. Do you have `extended-keys` set to `on` in your `tmux.conf`?

Setting `extended-keys` to `on` actually fixes my issue for Tmux 3.5. @crzcrz thank you for pointing me in the right direction!

Now I see that extended keys are mentioned in the `CHANGES FROM 3.4 TO 3.5`, but I didn't even know about various "modes", so I wouldn't probably know how to solve it myself just from reading about the change.

**Comment by natebragg** [comment]
I am seeing the same issue with CTRL+space (CTRL+@).  It worked fine on 3.4, I upgraded to 3.5, and now it doesn't work.

**Comment by jakubbortlik** [comment]
> I am seeing the same issue with CTRL+space (CTRL+@). It worked fine on 3.4, I upgraded to 3.5, and now it doesn't work.

Does adding `set-option -g extended-keys on` to your `tmux.conf` solve the issue?

**Comment by natebragg** [comment]
No, the same issue persists.

**Comment by randomcoder67** [comment]
Having a similar issue since the upgrade to 3.5, C-Tab works fine, but C-S-Tab doesn't work anymore. Using `showkey -a`, Ctrl+Shift+Tab seems to send `^[[Z`, which seems to be the same as just Shift+Tab.

**Comment by natebragg** [comment]
@nicm @craigbarnes I'm not familiar with the code in question, but the commit confused me.  How does this fix the issue in this ticket?  Do we need to do something specific in our tmux configuration files to re-enable these CTRL codes?  Or will it just work now?

**Comment by nicm** [comment]
Using `Tab`/`Enter` instead of `C-i`/`C-m` fixed the problem.

**Comment by craigbarnes** [comment]
> @craigbarnes I'm not familiar with the code in question, but the commit confused me. How does this fix the issue in this ticket?

If you mean the dte commit above - it doesn't. That was a commit in a different project to work around a different tmux 3.5 [bug](https://github.com/tmux/tmux/issues/4146). I just happened to include a link to this issue and the GitHub UI (perhaps annoyingly in this case) cross-referenced it.

**Comment by natebragg** [comment]
@nicm so should I open a new ticket with the Ctrl+space issue?

**Comment by nicm** [comment]
If binding `C-Space` does not work then yes.

**Comment by nicm** [comment]
It'd be nice if with `extended-keys` off tmux mapped bindings for `C-i` to `Tab` (and similar keys) automatically, although since they are resolved when the key bindings happen, if someone later turned `extended-keys` on they would be wrong. A little too late now anyway...

**Comment by randomcoder67** [comment]
> Having a similar issue since the upgrade to 3.5, C-Tab works fine, but C-S-Tab doesn't work anymore. Using `showkey -a`, Ctrl+Shift+Tab seems to send `^[[Z`, which seems to be the same as just Shift+Tab.

Update: Using `C-BTab` instead of `C-S-Tab` works perfectly, thanks to @crzcrz (mentioned in other thread)

**Comment by nicm** [comment]
Yeah it would have to either when tmux converts the string to a key or when it looks up the key binding, neither would be ideal. I would probably do the first.

I don't think it is that much of a problem for some of the keys like `C-@` where almost everyone will actually be pressing `C-Space`, so it makes sense to call it what it is, but it is confusing that keys people actually press like `C-i`. I imagine many people have until now gone through life blissfully unaware that `C-i` and `Tab` are the same...

**Comment by nicm** [comment]
Maybe something like this [keys.diff.txt](https://github.com/user-attachments/files/17266526/keys.diff.txt). But it seems like the potential for adding confusion to confusion is very high...

**Comment by flipsi** [comment]
I had the similar problem that my binding (CTRL+Alt+i) stopped working:
```
bind-key -T root C-M-i new-window -c $HOME
```
But no luck with the mentioned setting:
```
set-option -g extended-keys on
```

So [I worked around the issue](https://github.com/flipsi/dotfiles/commit/2f32e84836f838dff28a7663d4348dfc5f172a96) by mapping a special character (`î`,  ASCII 0xEE) _that I otherwise don't use_ to the same function:
```
bind-key -T root î new-window -c $HOME
```
and sending this character in my terminal emulator with the original CTRL+Alt+i binding. In Alacritty this looks like this:
```
[[keyboard.bindings]]
key = "i"
mods = "Control|Alt"
chars = "î"
```

Note that [you can only use 8 bit character encodings, no fancy UTF-8 characters](https://superuser.com/questions/930771/bind-tmux-prefix-to-an-unicode-character).

I hope this is helpul for other users that are in a similar love-hate-relationship with tmux like me. I mean it is generally awesome terminal multiplexer, but how breaking changes are handled without proper migration guides is somewhat annoying.
