### ISSUE TITLE
Ctrl-Left, Ctrl-Right don't work

### ISSUE THREAD

**Issue by safinaskar** [tmux/tmux#415]
When I press Ctrl-Left (or Ctrl-Right) in bash, cursor moves left by word. But when I press this in bash in tmux, this is processed like a normal Left.

I use normal PC (not Mac) laptop keyboard. Debian GNU/Linux Jessie. My terminal emulator is Konsole 2.14.2. Bash 4.3.30(1). tmux 1.9

**Comment by nicm** [comment]
What is TERM outside tmux?

**Comment by nicm** [comment]
You will probably need to turn on xterm-keys to make tmux send C-Left and C-Right, or configure bash to recognize what tmux sends for C-Left and C-Right, or both.

**Comment by safinaskar** [comment]
TERM is xterm outside tmux. I turned on xterm-keys and now everything works. But this should work out-of-the-box
