### ISSUE TITLE
Feature request: kill sessions in choose-tree without confirmation

### ISSUE THREAD

**Issue by linkarzu** [tmux/tmux#4152]
### Issue description

- I opened discussion 4139 a few days ago ["choose-tree kill selected item without confirmation"](https://github.com/orgs/tmux/discussions/4139)
- I was given a wonderful solution to change the key used to kill panes whe inside choose-tree, I switched that from the default `x` to `d` with this provided tmux.conf command `bind -n d if -F '#{==:#{pane_mode},tree-mode}' 'send x' 'send d'`
- However, I would also like to be able to kill sessions without the confirmation message shown below

![linkarzu com 2024-10-02 at 17 03 28](https://github.com/user-attachments/assets/de94fadd-a241-4957-93fc-0d3b3e07a658)

- I'm not suggesting that this confirmation message is disabled entirely, but it would be really nice if you can add a line to your tmux conf file that disables it, something like `set -g choose-tree-kill-confirmation off` and have it set to `on` as the default to not affect all the existing tmux users that are used to this safety mechanism
- The reason I'm asking this to be made optional, is because I'm used to closing buffers in neovim using a similar navigation approach, in which my buffers are sorted the same way that in tmux, so when I press `d` it just closes the buffer without confirmation
- It makes the cleanup of unused tmux sessions way faster
- One other important detail I'd like to add, is that when a session is closed, the cursor is moved at the very top of the list of sessions, it would be wonderful if the cursor remained in the same place where it was after deleting the session
  - This is the way that I sort my sessions in choose-tree in case it helps
```bash
# When pressing prefix+s to list sessions, I want them sorted by time
# That way my latest used sessions show at the top of the list
# -s starts with sessions collapsed (doesn't show windows)
# -Z zooms the pane (don't uderstand what this does)
# -O specifies the initial sort field: one of ‘index’, ‘name’, or ‘time’ (activity).
# https://unix.stackexchange.com/questions/608268/how-can-i-force-tmux-to-sort-my-sessions-alphabetically
bind s choose-tree -Zs -O time
```

- Here's a link to my [tmux.conf](https://github.com/linkarzu/dotfiles-latest/blob/415946372638f40a3b4827778f76b0d85020962f/tmux/tmux.conf.sh) file as well in case it helps

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
```bash
❯ tmux -V
tmux 3.5
```

* Platform (`uname -sp`).
```bash
linkarzu.@.mini~/github/LazyVim on  main via 🌙 v5.4.7
[24/10/02] kubernetes ()
❯ uname -sp
Darwin arm
```

* $TERM inside and outside of tmux (`echo $TERM`).
```bash
❯ echo $TERM
wezterm
```

* Logs from tmux (`tmux kill-server; tmux -vv new`)

**Comment by nicm** [comment]
I don't mind having a `-y` flag to `choose-tree` and friends to disable the prompts, if you want to open a PR. Although personally I would just get used to tagging all the sessions with t` then using `X` then you only need to press `y` once.

**Comment by nicm** [comment]
I had a look at this, please try this: [x.diff.txt](https://github.com/user-attachments/files/17254835/x.diff.txt)

**Comment by linkarzu** [comment]
Really appreciate it, I'll be testing this shortly!

**Comment by linkarzu** [comment]
So just to make sure I'm right, the way this works, is that my choose-tree bind should change by adding the '-y' flag correct?
```bash
# Before
bind s choose-tree -Zs -O time

# Now
bind s choose-tree -Zs -O time -y
```
I tried this, and it works wonderfully, it closes the sessions without asking for confirmation.
I know its probably too much asking, but when you close a session, the "cursor" moves to the top of the file instead of staying in that same place as seen on the video below


https://github.com/user-attachments/assets/c96da3a0-eda8-479c-b4f1-961d68501517

In the video I also showed how this works in neovim in case it helps to compare

I know this might be asking too much, but would make session management perfect in tmux.

I tried the "tag" feature that you mentioned, and works beautifully, I tag a session, the cursor stays in the same place, then I just move to another session to tag it, I changed it so that I can tag with "d", and close all of them with "D", tried this without the confirmation and it's wonderful!!!

But even compared to tagging, which works great, I prefer this other method of just deleting something with "x" or "d", and it would be awesome if the cursor could stay in the same position, the same way it happens with tagging. Maybe there's a setting already that I'm not aware of?

**Comment by nicm** [comment]
I have applied this to OpenBSD now, it will be in GitLab later.

I'm thought it used to try and keep the position when you deleted but now it always seems to reset to the top row, I'll take a look at some point.

**Comment by linkarzu** [comment]
Really appreciate the time and work put into this

**Comment by nicm** [comment]
Try this:
~~~~
Index: mode-tree.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/mode-tree.c,v
diff -u -p -r1.70 mode-tree.c
--- mode-tree.c 1 Oct 2024 10:10:29 -0000       1.70
+++ mode-tree.c 4 Oct 2024 22:24:30 -0000
@@ -356,8 +356,13 @@ mode_tree_set_current(struct mode_tree_d
                        mtd->offset = 0;
                return (1);
        }
-       mtd->current = 0;
-       mtd->offset = 0;
+       if (mtd->current >= mtd->line_size) {
+               mtd->current = mtd->line_size - 1;
+               if (mtd->current > mtd->height - 1)
+                       mtd->offset = mtd->current - mtd->height + 1;
+               else
+                       mtd->offset = 0;
+       }
        return (0);
 }

**Comment by linkarzu** [comment]
I'll give that a try in a little while and report back, thank you!

**Comment by linkarzu** [comment]
That did it for me!!!
I'm now closing sessions with `d`, without a confirmation message, and cursor staying in the same place!!!

https://github.com/user-attachments/assets/0aca6f30-96e9-4a50-b820-7040b8bd28f2

I'll keep the changes locally for now, as it's working beautifully, but since I install through brew, I'll monitor the [homebrew repo](https://github.com/Homebrew/homebrew-core/blob/master/Formula/t/tmux.rb) for changes (in case you decide to merge them 😍) so that I can go back to my brew install.

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
