### ISSUE TITLE
Forced release of key press before next key combination

### ISSUE THREAD

**Issue by sallmann** [tmux/tmux#4155]
### Issue description

In tmux 3.4 - before switching to Manjaro/Arch Linux unstable branch - I was used to press CTRL-A and afterwards CTRL-SPACE to navigate through my active tmux tabs. After upgrading this works somehow different.
Pressing those two combinations work, but I need to release the pressed "A" key in order to get the navigation to start.
Before upgrading I could held CTRL and "A" key and whilst doing it pressing additionally SPACE. This was way faster and more convinent for me as a workflow.
Actually I needed to downgrade tmux to 3.4 to work with it as I was used to the last couple of years.

Perhaps I am missing something and hope someone can clarify wether this is a bug or a "new" feature.

### /etc/tmux.conf
```
# $Id: screen-keys.conf,v 1.6 2010/02/02 21:34:16 nicm Exp $
#
# By Nicholas Marriott. Public domain.
#
# This configuration file binds many of the common GNU screen key bindings to
# appropriate tmux key bindings. Note that for some key bindings there is no
# tmux analogue and also that this set omits binding some commands available in
# tmux but not in screen.
#
# Note this is only a selection of key bindings and they are in addition to the
# normal tmux key bindings. This is intended as an example not as to be used
# as-is.

# Set the prefix to ^A.
unbind C-b
set -g prefix ^A
bind a send-prefix

# Bind appropriate commands similar to screen.
# lockscreen ^X x 
unbind ^X
bind ^X lock-server
unbind x
bind x lock-server

# screen ^C c 
unbind ^C
bind ^C new-window
#bind c
bind c new-window

# detach ^D d
unbind ^D
bind ^D detach

# displays * 
unbind *
bind * list-clients

# next ^@ ^N sp n 
unbind ^@
bind ^@ next-window
unbind ^N
bind ^N next-window
unbind " "
bind " " next-window
unbind n
bind n next-window

# title A
unbind A
bind A command-prompt "rename-window %%"

# other ^A
unbind ^A
bind ^A last-window

# prev ^H ^P p ^? 
unbind ^H
bind ^H previous-window
unbind ^P
bind ^P previous-window
unbind p
bind p previous-window
unbind BSpace
bind BSpace previous-window

# windows ^W w 
unbind ^W
bind ^W list-windows
unbind w
bind w list-windows

# kill K k 
unbind K
bind K confirm-before "kill-window"
unbind k
bind k confirm-before "kill-window"

# redisplay ^L l 
unbind ^L
bind ^L refresh-client
unbind l
bind l refresh-client

# split -v |
unbind |
bind | split-window

# :kB: focus up
unbind Tab
#bind Tab down-pane
unbind BTab
#bind BTab up-pane

# " windowlist -b
unbind '"'
bind '"' choose-window

set -g status-bg black
set -g status-fg white
set -g status-left "#[fg=green]#H"
#set-window-option -g window-status-current-bg red
setw -g automatic-rename on

set -g set-titles on
set -g set-titles-string "root: #T"

set -g default-terminal screen-256color
```

### Required information

* Version: working as expected on tmux 3.4, not working on "tmux-git-10299_3.5.r21.g2df15ad0-1" and tmux-3.5-1
* Platform: Manjaro (Arch Linux unstable) / KDE6/Wayland
* $TERM: rxvt-unicode-256color

**Comment by nicm** [comment]
No logs.

**Comment by sallmann** [comment]
Additionally the missing logs. I'm sorry for that.

[tmux-client-31771.log](https://github.com/user-attachments/files/17243189/tmux-client-31771.log)
[tmux-client-31780.log](https://github.com/user-attachments/files/17243190/tmux-client-31780.log)
[tmux-server-31782.log](https://github.com/user-attachments/files/17243191/tmux-server-31782.log)

**Comment by nicm** [comment]
I don't see you pressing `C-a C-Space` in this log?

**Comment by sallmann** [comment]
TMUX 3.4 Logs
[tmux-client-79623.log](https://github.com/user-attachments/files/17243539/tmux-client-79623.log)
[tmux-out-79625.log](https://github.com/user-attachments/files/17243540/tmux-out-79625.log)
[tmux-server-79625.log](https://github.com/user-attachments/files/17243541/tmux-server-79625.log)

TMUX 3.5 Logs
[tmux-client-77650.log](https://github.com/user-attachments/files/17243546/tmux-client-77650.log)
[tmux-out-77652.log](https://github.com/user-attachments/files/17243547/tmux-out-77652.log)
[tmux-server-77652.log](https://github.com/user-attachments/files/17243548/tmux-server-77652.log)

**Comment by nicm** [comment]
I don't see any differences here. Is the 3.5 log from it working or not working?

Can you reproduce it in 3.5 once or twice with it not working and show me the log from that?

**Comment by nicm** [comment]
Your key binding is not `C-Space` it is `C-@`, you need to change the config file to use `C-Space` now:
~~~~
unbind C-Space
bind C-Space next-window

**Comment by sallmann** [comment]
> Your key binding is not `C-Space` it is `C-@`, you need to change the config file to use `C-Space` now:
> 
> ```
> unbind C-Space
> bind C-Space next-window
> ```

Thank you very much nicm.
This little change in configuration indeed fixed my issue.
