### ISSUE TITLE
Alt+Backspace emits unusual/invalid sequence

### ISSUE THREAD

**Issue by craigbarnes** [tmux/tmux#4156]
Recent commits seem to have resolved #4146, but <kbd>Alt</kbd>+<kbd>Backspace</kbd> is still producing an unusual sequence of bytes, which don't match other terminals I've seen and don't appear to be a valid escape sequence (per ECMA-48).

Example `showkey -a` output for tmux (built from commit 2df15ad08c9e4cf286cdb38cb645fc9066c3098d):

```
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^[􎆔      27 0033 0x1b
        244 0364 0xf4
        142 0216 0x8e
        134 0206 0x86
        148 0224 0x94
```

… vs. xterm (for comparison):

```
$ printf "\033[>4;2m"
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^[[27;3;8~       27 0033 0x1b
         91 0133 0x5b
         50 0062 0x32
         55 0067 0x37
         59 0073 0x3b
         51 0063 0x33
         59 0073 0x3b
         56 0070 0x38
        126 0176 0x7e

```

… and foot:

```
$ printf "\033[>4;2m"
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^[[27;3;127~ 	27 0033 0x1b
 	91 0133 0x5b
 	50 0062 0x32
 	55 0067 0x37
 	59 0073 0x3b
 	51 0063 0x33
 	59 0073 0x3b
 	49 0061 0x31
 	50 0062 0x32
 	55 0067 0x37
 	126 0176 0x7e
```

The reason foot differs from xterm in this case is mentioned [here](https://codeberg.org/dnkl/foot/pulls/791#issuecomment-279784).

Other info:

* tmux version: commit 2df15ad08c9e4cf286cdb38cb645fc9066c3098d
* `uname -sm`: Linux x86_64
* `$TERM` inside tmux: `tmux-256color`
* `$TERM` outside tmux: `foot`

**Comment by craigbarnes** [comment]
FWIW, <kbd>Alt</kbd>+<kbd>Backspace</kbd> is a key combo I use often in both [dte](https://github.com/craigbarnes/dte) and bash. When running under tmux, dte filters out the invalid bytes and it simply results in the expected key binding not being triggered, whereas in bash it results in a corrupted readline buffer and some very strange behavior (which I can elaborate on further if needed).

**Comment by nicm** [comment]
Try this please:
~~~~
diff --git a/tty-keys.c b/tty-keys.c
index 8c77d031..8d703fc0 100644
--- a/tty-keys.c
+++ b/tty-keys.c
@@ -1069,7 +1069,7 @@ tty_keys_extended_key(struct tty *tty, const char *buf, size_t len,
                nkey = number;

        /* Convert UTF-32 codepoint into internal representation. */
-       if (nkey & ~0x7f) {
+       if (nkey != KEYC_BSPACE && nkey & ~0x7f) {
                if (utf8_fromwc(nkey, &ud) == UTF8_DONE &&
                    utf8_from_data(&ud, &uc) == UTF8_DONE)
                        nkey = uc;

**Comment by craigbarnes** [comment]
Just tested that patch applied on top of 7a78cdf78c00370d4ff1eb2c7cb5678412de9002 and it seems to work as expected (in `modifyOtherKeys` modes 0, 1 and 2). Thanks for the quick fix!

**Comment by nicm** [comment]
Applied now, thanks.
