### ISSUE TITLE
Feature Request: Kitty Keyboard Protocol (KKP)

### ISSUE THREAD

**Issue by pierreay** [tmux/tmux#4158]
Hello! This is actually not an issue but a question about a feature.

*State*

Currently, some escape codes interpretation are ambiguous and do not work well for complex modifier sequences (_e.g._: C-RET).
I encountered this issue when using Emacs in terminal.
I discovered that the Kitty solved the problem, defining the [Kitty Keyboard Protocol (KKP)](https://sw.kovidgoyal.net/kitty/keyboard-protocol/), which is nowadays supported by major modern terminals (Kitty, Alacritty, WezTerm) or text editors (Vim, Neovim, Emacs).

**The problem**: using tmux between one of these terminal and text editor will break the correct escape code interpretation.

*Question(s)*

- Is implementing this protocol planned? If not, why?
- How hard it could be to implement it?

Thanks! ;)

**Comment by craigbarnes** [comment]
> (e.g.: C-RET)

Possibly related: #4157.

> Is implementing this protocol planned

This is mentioned in https://github.com/tmux/tmux/pull/4038#issuecomment-2288411060 (although note that the statement there about iTerm2's `CSI u` protocol and Kitty's protocol being the same thing [isn't accurate](https://gitlab.com/gnachman/iterm2/-/issues/10017)).

**Comment by pierreay** [comment]
> Possibly related: #4157.

Thanks for the pointer. Unfortunately, it does not solve my issue... :(
I tried with `TERM=xterm` and `TERM=tmux-256color`, and to give some examples, when pressing `C-RET,` only `RET` is recognized ; when pressing `C-;`, only `;` is recognized by Emacs.

> This is mentioned in PR [#4038 (comment)](https://github.com/tmux/tmux/pull/4038#issuecomment-2288411060)

Interesting! Would love to see this finished and merged. Thanks for the work!
