### ISSUE TITLE
How to get the working directory from pane_current_path variable after updating to v3.5

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#4159]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `V3.5`
* Platform (`uname -sp`). `Archlinux`
* $TERM inside and outside of tmux (`echo $TERM`). `screen-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux.log.zip](https://github.com/user-attachments/files/17250974/tmux.log.zip)

I just upgraded tmux from `tmux 3.4-10` to `tmux-3.5-1` (Archlinux package format), and I notice some of my config doesn't work anymore

```
set -g window-status-format '#I:[#W]#(pwd="#{pane_current_path}"; echo ${pwd####*/})#F'
```
Screenshot of old and new:
https://imgur.com/UODXBhS

The directory is gone, the directory part is from `#(pwd="#{pane_current_path}"; echo ${pwd####*/})` part, it works normally for quite a few years, now it is not working at all.

So how can get the working directory from the PWD for the `window-status-format` in V3.5?

**Comment by nicm** [comment]
Does this work if you build from `tmux-3.5a` branch?

**Comment by c02y** [comment]
I followed the README to compile the `tmux-3.5a` branch
```
sh autogen.sh
./configure && make
```
I got error from the `make` command
```
job.c: In function ‘job_run’:
job.c:96:22: error: ‘JOB_DEFAULTSHELL’ undeclared (first use in this function)
   96 |         if (~flags & JOB_DEFAULTSHELL)
      |                      ^~~~~~~~~~~~~~~~
job.c:96:22: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:1005: job.o] Error 1
```

**Comment by nicm** [comment]
Try again now please.

**Comment by c02y** [comment]
> So I added #define JOB_DEFAULTSHELL 0x8 in tmux.h of branch tmux-3.5a, compile and run it, this version works fine:
[imgur.com/uigzwzF](https://imgur.com/uigzwzF)

Not sure if you saw this line.

I tried both the latest commit of `master` and `tmux-3.5a`, they are both working fine.

**Comment by nicm** [comment]
OK good stuff, thanks, I will make 3.5a at some point next week I expect.
