### ISSUE TITLE
Sixel graphics no longer work after upgrading to 3.5

### ISSUE THREAD

**Issue by prurigro** [tmux/tmux#4161]
### Issue description

With 3.4 sixel graphics rendered correct, now with 3.5 nothing is output.

### Required information

Please provide the following information:

* tmux 3.5
* Archlinux
* $TERM inside tmux: tmux-256color
* $TERM outside tmux: alacritty (patched with sixel support)
* Logs below:

[tmux-client-61201.log](https://github.com/user-attachments/files/17264253/tmux-client-61201.log)
[tmux-out-61203.log](https://github.com/user-attachments/files/17264255/tmux-out-61203.log)
[tmux-server-61203.log](https://github.com/user-attachments/files/17264256/tmux-server-61203.log)

Let me know if you need anything more!

**Comment by nicm** [comment]
The only SIXEL in this log is too big and is ignored.

**Comment by prurigro** [comment]
Ahh you're right, other smaller images are working... I'm fairly certain this one did work previously on that note as it's been my test image for confirming sixel support. It also works outside tmux. That said, I could see how this might be a wontfix if it's to keep from using too many resources or something (in which case feel free to close).

**Comment by nicm** [comment]
I don't know because the limit has been 1 MB since the start unless it was lowered and I've forgotten (don't think since 3.4 though).

I don't mind really mind bumping the limit but what is the use case apart from testing SIXEL - are you really routinely looking at 1 MB SIXEL images?

**Comment by prurigro** [comment]
The source image is actually only 500kb, I guess the size increases when converted to sixel format due to the larger resolution (3644x2470)? Both chafa and timg get skipped in tmux. It's not only a test image on that note, it just happens to be an image I've had at the root of my home folder for a bit that sort of turned into a test image because it was conveniently located.

**Comment by sonjiku** [comment]
> The source image is actually only 500kb, I guess the size increases when converted to sixel format

That is true, you can do a simple redirect of stdout to a file to get a good estime of the size of the sixel image.

> I don't know because the limit has been 1 MB since the start

If you, @prurigro, are still looking for a solution to view your large sixel images in tmux, you could use this patch which is what I'm currently using:
```diff
diff --git a/input.c b/input.c
index 86af45cf..45d27d5f 100644
--- a/input.c
+++ b/input.c
@@ -93,7 +93,7 @@ struct input_ctx {
 	size_t			param_len;
 
 #define INPUT_BUF_START 32
-#define INPUT_BUF_LIMIT 1048576
+#define INPUT_BUF_LIMIT 10485760
 	u_char		       *input_buf;
 	size_t			input_len;
 	size_t			input_space;
```
