### ISSUE TITLE
3.5a uses /bin/bash instead of the default user shell /bin/zsh

### ISSUE THREAD

**Issue by ChrisGVE** [tmux/tmux#4166]
### Issue description

When opening tmux or any pane, tmux runs bash as default shell instead of the user default zsh.
I've set the global option:

`set -g default-shell /bin/zsh`

without success, any new pane is still opened with bash instead of zsh.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 3.5a
* Platform (`uname -sp`).  Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`).  inside: tmux-256color outside xterm-kitty
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by donus3** [comment]
+1 Same here 

tmux version (tmux -V). 3.5a
Platform (uname -sp). Darwin arm
$TERM inside and outside of tmux (echo $TERM). inside: alacritty outside alacritty

**Comment by donus3** [comment]
It might relates to this commit https://github.com/tmux/tmux/commit/a1b7a3bcb32066a36367fbcd4ebbfedbd6ad8ec1 🤔

**Comment by nicm** [comment]
Logs?

**Comment by donus3** [comment]
It turns out that it comes from the [tmux-sensible](https://github.com/tmux-plugins/tmux-sensible/tree/master) ( this script https://github.com/tmux-plugins/tmux-sensible/blob/master/sensible.tmux#L102)

**Comment by nicm** [comment]
`reattach-to-user-namespace` should not be be required now (since tmux 2.6).

**Comment by ChrisGVE** [comment]
Thanks, adding @donus3 config line works for me too, of course this does not solve the root cause of the problem

**Comment by fmoda3** [comment]
I have this same problem on 3.5a.  I also use sensible, but removing it doesn't solve the problem.  I also don't use `reattach-to-user-namespace`.  Is there a different solution to this problem?  3.4 works fine.

**Comment by fmoda3** [comment]
@nicm Can we reopen this, since the underlying issue still exists?

tmux version (tmux -V).
`3.5a`

Platform (uname -sp).
`Darwin i386`

$TERM inside and outside of tmux (echo $TERM).
inside: `screen-256color`
outside: `xterm-256color`

Logs from tmux (tmux kill-server; tmux -vv new).
[tmux-client-25696.log](https://github.com/user-attachments/files/17317409/tmux-client-25696.log)
[tmux-server-25698.log](https://github.com/user-attachments/files/17317411/tmux-server-25698.log)
[tmux-out-25698.log](https://github.com/user-attachments/files/17317412/tmux-out-25698.log)

**Comment by nicm** [comment]
From your log:
~~~~
1728500147.396577 cmd_parse_build_commands: set-option -g default-command "/nix/store/yqrp6fy74vg6rf0va7sdbpm28vb5k6w3-reattach-to-user-namespace-2.9/bin/reattach-to-user-namespace -l /bin/sh"
~~~~

**Comment by nicm** [comment]
`$SHELL` in the environment that the client that issued this command sends to tmux is `/bin/sh`. tmux logs the command before it does any expansion so it seems likely it is getting it with `$SHELL` already replaced by `/bin/sh`:
~~~~
1728500147.396485 peer 0x7f7c50048000 message 200
1728500147.396491 cmd_unpack_argv: argv[0]=set-option
1728500147.396504 cmd_unpack_argv: argv[1]=-g
1728500147.396508 cmd_unpack_argv: argv[2]=default-command
1728500147.396513 cmd_unpack_argv: argv[3]=/nix/store/yqrp6fy74vg6rf0va7sdbpm28vb5k6w3-reattach-to-user-namespace-2.9/bin/reattach-to-user-namespace -l /bin/sh
~~~~
Are you sure you didn't upgrade anything else at the same time as tmux that might have changed this?

Are you sure it works if you go back to 3.4 and make no other changes? What do the logs for 3.4 look like?

Do your scripts do anything different depending on tmux version?

**Comment by nicm** [comment]
This is what your script is running for `default-command` and they behave the same for me with 3.4 and 3.5a:
~~~~
$ tmux show -gv default-command

$ tmux set -g default-command "$SHELL"
$ tmux show -g default-command
default-command /bin/bash
$
~~~~
With `'`s it does work how was perhaps intended:
~~~~
$ tmux set -g default-command '$SHELL'
$ tmux show -g default-command
default-command "\$SHELL"
~~~~

**Comment by fmoda3** [comment]
So, that seems to come from sensible:
```
if is_osx && command_exists "reattach-to-user-namespace" && option_value_not_changed "default-command" ""; then
	tmux set-option -g default-command "reattach-to-user-namespace -l $SHELL"
fi
```
which hasn't changed in a long time.

outside tmux, `echo $SHELL` returns `/bin/zsh`
inside tmux, `echo $SHELL` returns `/bin/zsh` but `echo $0` is `-sh`

When i downgrade back to tmux 3.4, the issue goes away.
Logs when on 3.4:
[tmux-client-28984.log](https://github.com/user-attachments/files/17317990/tmux-client-28984.log)
[tmux-server-28986.log](https://github.com/user-attachments/files/17317993/tmux-server-28986.log)
[tmux-out-28986.log](https://github.com/user-attachments/files/17317994/tmux-out-28986.log)

It also seems to work on tmux 3.5.
Logs when on 3.5:
[tmux-client-29989.log](https://github.com/user-attachments/files/17318025/tmux-client-29989.log)
[tmux-server-29991.log](https://github.com/user-attachments/files/17318028/tmux-server-29991.log)
[tmux-out-29991.log](https://github.com/user-attachments/files/17318026/tmux-out-29991.log)

Going back to 3.5a, and it's broken again.
New logs on 3.5a:
[tmux-client-30720.log](https://github.com/user-attachments/files/17318038/tmux-client-30720.log)
[tmux-server-30722.log](https://github.com/user-attachments/files/17318040/tmux-server-30722.log)
[tmux-out-30722.log](https://github.com/user-attachments/files/17318039/tmux-out-30722.log)

I then took 3.5a, and removed the sensible plugin (I didn't remove it correctly last time i tried), and this _does_ fix the issue:
Logs on 3.5a with sensible plugin removed:
[tmux-client-33256.log](https://github.com/user-attachments/files/17318164/tmux-client-33256.log)
[tmux-server-33258.log](https://github.com/user-attachments/files/17318166/tmux-server-33258.log)
[tmux-out-33258.log](https://github.com/user-attachments/files/17318165/tmux-out-33258.log)

Seems to me, something in 3.5a clashes with Sensible, where it worked fine before.

**Comment by nicm** [comment]
If you do this does it work:
~~~~
--- a/job.c
+++ b/job.c
@@ -167,7 +167,6 @@ job_run(const char *cmd, int argc, char **argv, struct environ *e,
                closefrom(STDERR_FILENO + 1);

                if (cmd != NULL) {
-                       setenv("SHELL", shell, 1);
                        execl(shell, argv0, "-c", cmd, (char *)NULL);
                        fatal("execl failed");
                } else {

**Comment by fmoda3** [comment]
I applied that change to a fork here: https://github.com/fmoda3/tmux/commit/64345b47f5d370212204f8a770bf731ccc84681c

and that did seem to fix it.

Here are the logs from that run:
[tmux-client-39135.log](https://github.com/user-attachments/files/17318441/tmux-client-39135.log)
[tmux-server-39137.log](https://github.com/user-attachments/files/17318443/tmux-server-39137.log)
[tmux-out-39137.log](https://github.com/user-attachments/files/17318442/tmux-out-39137.log)

**Comment by nicm** [comment]
OK, so the problem is that it is running the script with `run-shell`:
~~~~
1728504250.297736 job_run: cmd=/nix/store/3y8h2b12jkm7gwx63zyya7x8aq9p4fah-tmuxplugin-sensible-unstable-2017-09-05/share/tmux-plugins/sensible/sensible.tmux, cwd=/Users/fmoda3/.nix-configs, shell=/bin/sh
~~~~
`run-shell` has always used `/bin/sh` but it did not also set `SHELL` to `/bin/sh`. This was an oversight that was fixed in 3.5

No script should be expecting `SHELL` to be different from the shell it was executed with so I think it needs to be fixed - you will need to contact the author.

It could use `'`s to let tmux do the expansion, or use `tmux showenv -g SHELL` instead. Or just get rid of the whole bit - `reattach-to-user-namespace` has not been needed on macOS since tmux 2.6.

**Comment by nicm** [comment]
@bruno- is still active and seems to be the maintainer of `tmux-sensible` so maybe he can fix?

**Comment by fmoda3** [comment]
Got it, ok.  At your suggestion, I have added
```
set -g default-command '$SHELL'
```
in my config after sensible, and that fixes it for the time being.

**Comment by jaseemabid** [comment]
If we are changing the behaviour (intentionally or unintentionally), should we add this to changelog? I think a lot of people will hit this issue when they eventually upgrade to v3.5.

**Comment by nicm** [comment]
I added a note to the release issue.
