### ISSUE TITLE
Ctrl modified numpad keys emit Hangul letters

### ISSUE THREAD

**Issue by craigbarnes** [tmux/tmux#4168]
If I hold <kbd>Ctrl</kbd> and press numpad keys 1234567890 in sequence (with NumLock on), I get the following output in my bash prompt:

```
ﾱﾲﾳﾴﾵﾶﾷﾸﾹﾰ
```

Pressing <kbd>Ctrl</kbd>+<kbd>1</kbd> (numpad <kbd>1</kbd>; NumLock on) in `showkey -a` produces:

```
ﾱ       239 0357 0xef
        190 0276 0xbe
        177 0261 0xb1
```

...which looks like the UTF-8 encoding of U+FFB1.

Other numpad keys are similarly affected when <kbd>Ctrl</kbd> is held; with or without NumLock enabled in the case of <kbd>/</kbd>, <kbd>*</kbd>, <kbd>-</kbd>, <kbd>+</kbd> and <kbd>Enter</kbd>.

Possibly related/similar: #4156

Other info:

* tmux version: commit 933d6b90edc4c673d22903381d367fa0cdd02655 (current git `master`)
* `uname -sm`: Linux x86_64
* `$TERM` inside tmux: `tmux-256color`
* `$TERM` outside tmux: `foot`

**Comment by nicm** [comment]
Show logs please.
