### ISSUE TITLE
Status bar center background transparency

### ISSUE THREAD

**Issue by hykilpikonna** [tmux/tmux#4169]
How can I set a background color for the center while keeping the background color for left and right transparent?

If I don't set `status-style`, I cannot set the center to white:

![image](https://github.com/user-attachments/assets/2262c23d-7c55-46f6-88f0-d1fdb2f93db3)

If I set `status-style 'bg=#ffffff'`, then the left and right status bars also become white:

![image](https://github.com/user-attachments/assets/eb34a14a-b3da-4dbd-a5d6-6be68220f7ac)

I also tried manually adding ANSI escape codes with either the ESC character or escape sequences, they do not seem to work:

![image](https://github.com/user-attachments/assets/a54b6b0f-2c75-4169-8623-d91c0df2d313)
![image](https://github.com/user-attachments/assets/d05db923-ac77-4f86-969c-4d731bbeaa20)

**Comment by nicm** [comment]
You will need to change `status-format[0]`.

**Comment by hykilpikonna** [comment]
> You will need to change `status-format[0]`.

Setting `status-format[0]` seem to result in the same behavior as setting status-left...

![image](https://github.com/user-attachments/assets/c06973cc-ea85-4509-93b1-a94dd7c8eda6)

![image](https://github.com/user-attachments/assets/ed4d9b5a-c745-4c6c-ab0f-1fa817a7448a)

**Comment by nicm** [comment]
Where have you got this idea you can use escape sequences in tmux options?

**Comment by hykilpikonna** [comment]
> Where have you got this idea you can use escape sequences in tmux options?

ANSI escape are standard in all xterm* terminals, which means that they should work unless tmux is explicitly removing them (which it seems to be doing).

**Comment by nicm** [comment]
Of course it removes them.

Show me what you are putting in the option, I can't guess what it is from screenshots.

**Comment by hykilpikonna** [comment]
> Of course it removes them.
> 
> Show me what you are putting in the option, I can't guess what it is from screenshots.

Previously using status-left and status-right: 

```tmux.conf
set -g status-left-length 0
set -g status-left '#[fg=#32738c,bg=#333333]#[bg=#459dbf]#[fg=#459dbf,bg=#58c8f2]#[fg=#333333]   #(date +"%a %m-%d") #[fg=#58c8f2,bg=#eda4b2]#[fg=#333333]   #(date +"%I:%M %p") #[fg=#eda4b2,bg=#ffffff]'

# Centered window status
set -g status-justify centre
set -g status-interval 1
set -g window-status-style 'fg=#333333,bg=default'
set -g window-status-current-style 'fg=#333333,bg=default'
set -g window-status-separator '  '

set -g status-right-length 0
set -g status-right '#[fg=#ffffff,bg=#eda4b2]#[fg=#333333] #(python3 -m hyfetch --print-font-logo)  #(hostname) #[fg=#eda4b2,bg=#58c8f2]#[fg=#333333]   Be happy! #[fg=#58c8f2,bg=#459dbf]#[fg=#459dbf,bg=#32738c]#[fg=#32738c,bg=#333333]'
```

I'm not sure about how I would use `status-format[0]` to achieve the same result. If I set status-format[0] to the following, the tabs would no longer be visible:

```tmux.conf
set -g status-format[0] '#[fg=#32738c,bg=#333333]#[bg=#459dbf]#[fg=#459dbf,bg=#58c8f2]#[fg=#333333]   #(date +"%a %m-%d") #[fg=#58c8f2,bg=#eda4b2]#[fg=#333333]   #(date +"%I:%M %p") #[fg=#eda4b2,bg=#ffffff]#[bg=#ffffff]  tabs?  #[align=right]#[fg=#ffffff,bg=#eda4b2]#[fg=#333333] #(python3 -m hyfetch --print-font-logo)  #(hostname) #[fg=#eda4b2,bg=#58c8f2]#[fg=#333333]   Be happy! #[fg=#58c8f2,bg=#459dbf]#[fg=#459dbf,bg=#32738c]#[fg=#32738c,bg=#333333]'
```

**Comment by nicm** [comment]
You can't do this with the individual options alone because there is no way to specify more than one background colour for the empty parts of the status line, but with `status-format` you can control every part of the status line.

I would copy the default `status-format[0]` and modify it to use a different background colour for the left and right. Whether you want to keep using the other options as well or just insert their values inline is up to you.

BTW it is probably unnecessary to use `#()` for `date` since tmux will expand `strftime` formats in the status line itself.

**Comment by nicm** [comment]
Actually maybe I'm on crack here, did you try just putting `bg=terminal` in `status-left`?

**Comment by hykilpikonna** [comment]
> Actually maybe I'm on crack here, did you try just putting `bg=terminal` in `status-left`?

That worked perfectly, thank you so much!

**Comment by nicm** [comment]
Great, sorry I forgot about `terminal` earlier...
