### ISSUE TITLE
Broken panes selection on "master" branch

### ISSUE THREAD

**Issue by SchweinDeBurg** [tmux/tmux#4173]
After commit [Add prompt-cursor-colour and prompt-cursor-style to set the style of the](https://github.com/tmux/tmux/commit/735082b7c245bb282cbc84c6fd6030bef1ce21a9) pressing `Ctrl+B`, `Q` just crashes tmux server instead of showing panes numbers and sizes. Commit [Add initial-repeat-time option to allow the first repeat time to be](https://github.com/tmux/tmux/commit/a3dea81b496be2dd1665947a66844aa1c85434b0) works pretty well.

**Comment by nicm** [comment]
This should be fixed when GitHub updates in a few hours. Thanks!
