### ISSUE TITLE
Support for displaying logical paths in tmux

### ISSUE THREAD

**Issue by huangyxi** [tmux/tmux#4174]
Currently, tmux displays the physical working path in the `#{pane_current_path}` variable, as seen with the command `tmux display-message -p -F "#{pane_current_path}"`. However, in scenarios where the physical path is long and rarely used — for example, in Linux, where a disk is mounted automatically at `/mnt/07f512b2-6e62-4b57-8a9b-bb0962898784` and symbolically linked to a shorter, more readable path manually (e.g. `~/data`) — it would be beneficial to display the logical path instead. Note that while the disk's mount point can be changed, this is managed by the system administrator.

I would like to propose the ability to display the logical path in tmux. Here are two possible approaches:

1. Re-implement the `osdep_get_cwd` function to display the logical path instead of the physical path.
2. Introduce a new variable (e.g., `#{pane_current_logical_path}` or another name to be discussed) to display the logical path.

I am willing to implement either method if the community agrees, but my development experience is limited to Linux.

**Comment by nicm** [comment]
How is it going to get the logical path?

**Comment by huangyxi** [comment]
Hi, I implemented a demo to get the logical path of the given shell at https://github.com/huangyxi/shell-cwd

**Comment by huangyxi** [comment]
Actually, there is an easier way to get the logical current working directory: by parsing the title printed by the shell, if it is set correctly.

**Comment by huangyxi** [comment]
Thank you for your clarification.
