### ISSUE TITLE
macOS paste with CMD+V stopped working in v3.5a

### ISSUE THREAD

**Issue by rensftw** [tmux/tmux#4175]
### Issue description
When I enable `extended-keys` on macOS the regular clipboard pasting with `CMD-V` stops working for multiline text - specifically, it starts adding this character escape code in place of newlines `^[[27;5;106~`.
This is happening in both Alacritty and Terminal.app.

For example if I copy this:
```txt
line1
line2
```
and then paste inside tmux, I get this:
```txt
line1^[[27;5;106~line2
```

https://github.com/user-attachments/assets/4e783e94-f72e-4cd7-b22b-14eb932c9c8f

### Minimal tmux config
```tmux
set -g extended-keys on
set -g default-terminal "tmux-256color"
```

### Required information
* tmux version (`tmux -V`): `tmux 3.5a`
* Platform (`uname -sp`): `Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`)
  * inside tmux: `tmux-256color`
  * outside tmux: `xterm-256color`
* Terminals: 
  * `alacritty 0.13.2 (bb8ea18)`
  * `Terminal.app Version 2.14 (454.1)`
* Logs: https://gist.github.com/rensftw/ea006a541516aca26eb61a8fc0584a8a

**Comment by nicm** [comment]
Does this still happen if you build tmux from master?

**Comment by rensftw** [comment]
@nicm Good news, in the latest commit on master `4f5d6d97` this issue is not reproducible:

https://github.com/user-attachments/assets/c73deab3-c94b-48b0-9e9e-847feabf84cb

**Comment by ipatch** [comment]
can confirm i ran into this issue after a recent upgrade pasting text into my neovim sessions inside of tmux. did not see the escape sequences outside of tmux. i get the above mentioned escape sequences inside of tmux running neovim with the tmux v3.5a release on arch linux. tested with both alacritty and kitty, and get the same results.

building tmux from source now using homebrew `brew install tmux -v -s --HEAD` to see if this issue will go away.

will update my comment if it does.
