### ISSUE TITLE
Feature Request: Add a way to determine if Sixel is enabled during the build (`--enable-sixel`)

### ISSUE THREAD

**Issue by sxyazi** [tmux/tmux#4177]
### Issue description

Hi, I'm the maintainer of [Yazi](https://github.com/sxyazi/yazi) - a terminal file manager that offers image preview support.

I'm excited to see that tmux now supports Sixel, which means Yazi and tmux users can run Yazi within tmux and use Sixel for image previews.

I've built a `yazi --debug` command that provides full information about the user's terminal and multiplexer, but currently, there doesn't seem to be a way to check if tmux supports Sixel *outside*, other than the user [manually running a DA1 query](https://github.com/tmux/tmux/issues/4104) *inside* tmux.

It would be great to have a separate command, like `tmux show-flag enable-sixel`, that outputs specified tmux's build flags, and when passed `--enable-sixel`, it would indicate if Sixel support was enabled. This would make diagnosing issues like https://github.com/sxyazi/yazi/issues/1750 much easier.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux 3.5a
* Platform (`uname -sp`). Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`). inside:tmux-256color, outside:xterm-kitty
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
But that is the same as all terminals? Can't your application send DA1?

**Comment by sxyazi** [comment]
Thanks for the response!

DA1 requires the user to have Yazi running in tmux, but this proposal's method avoids that. It's like static information, similar to a version (`tmux -V`) as the command `yazi --debug` provides not just tmux detection but other info too (there's an example https://github.com/sxyazi/yazi/issues/1750), making it usable outside of tmux while still accurately getting them.

Also querying tmux for DA1 isn't very meaningful for my application because it only reports whether tmux supports Sixel, not whether the actual user terminal does. Even if the user terminal doesn't support Sixel, tmux will report support if it was built with `--enable-sixel`. More often I pass DA1 through to the real user terminal.

**Comment by nicm** [comment]
This doesn't really make any sense to me, what is the need for your application to know if tmux supports SIXEL when it is not running in tmux? If it is running in tmux, it can send DA1 which has the benefit of working on any other terminal that it might be running in as well.

You can't accurately tell if the terminal tmux is running in supports SIXEL because there might be several of which some do and some don't. You could use `tmux display -p '#{client_termfeatures}'` to see if the current "best" client terminal supports it...

**Comment by sxyazi** [comment]
> what is the need for your application to know if tmux supports SIXEL when it is not running in tmux?

No, as I mentioned, my application doesn't need to know if tmux supports Sixel; it only needs to know if the actual user terminal does. That's why I don't send DA1 to tmux — my application **itself** doesn't require that information.

However, `yazi --debug` is a standalone diagnostic tool that is independent of the application. It's meant to help users quickly troubleshoot issues, and I want it to include tmux build information. 

If tmux hasn't been built with `--enable-sixel` and the user wants to use it, they need to know that information and recompile tmux with the flag. I believe this info is useful regardless of whether the user is running Yazi in tmux, and it should be consistent. DA1, on the other hand, is only available when the user runs Yazi in tmux.

**Comment by nicm** [comment]
You can try this [x.diff.txt](https://github.com/user-attachments/files/17325940/x.diff.txt) which will add a `sixel_support` variable, then you can do something like:
~~~~
tmux -Ltest -f/dev/null start \; display -p '#{sixel_support}'
~~~~

**Comment by sxyazi** [comment]
I tested and it works great for me. Thank you so much!

**Comment by sxyazi** [comment]
For those who need to call it in Rust or other languages, you need to pass `start` and `display` as separate arguments:

```rust
let output = std::process::Command::new("tmux")
	.args(["-Ltest", "-f/dev/null", "start", ";", "display", "-p", "#{sixel_support}"])
	.output()?;
```

Just leaving here in case it's helpful

**Comment by nicm** [comment]
This is applied now, thanks!
