### ISSUE TITLE
Executing  tmux display -p "%0" under cygwin causes tmux to consume all available memory before being killed

### ISSUE THREAD

**Issue by dutchgecko** [tmux/tmux#418]
This issue has cropped up on my cygwin installation when trying to use powerline (bug report initally filed there: powerline/powerline#1590)

When the command `tmux display -p "%0"` is executed, and a tmux server is running, the tmux server quickly proceeds to consume all available memory before being killed by the operating system. The display command reports: `lost server`

`tmux -V` reports version 2.2, the cygwin package manager reports version 2.2-1.

**Comment by nicm** [comment]
I don't use Cygwin and this doesn't happen for me on other platforms, so
you are going to need to do some debugging. What is tmux doing while the
memory is growing? Can you attach gdb to it and get a backtrace?

**Comment by dutchgecko** [comment]
It seems that gdb can't give me a backtrace because the process is being killed externally. I'm not sure if this is a limitation of the cygwin system.

I do have an strace though, starting from when the window is focused to when the display command is executed: http://slexy.org/view/s2eAHDGZBO

**Comment by nicm** [comment]
This doesn't show much useful. It is probably something that is only
used on Windows, can you show me the output of running tmux's configure
script?

**Comment by dutchgecko** [comment]
Output of `configure`: http://slexy.org/view/s22t6HN8aq

It's worth noting that `configure` includes the flag `-D_XOPEN_SOURCE=600`, which causes `make` to fail due to typedefs which are unavailable with this flag. Removing the flag allows the build to complete.

For sanity's sake I tested my own build of 2.2 and it shows the same issue as the cygwin package.

**Comment by nicm** [comment]
Hmm I thought it might be compat asprintf but it is using the system asprintf.

What does the tmux -vvvv log look like?

**Comment by dutchgecko** [comment]
Output of `tmux-server.log`: http://slexy.org/view/s21jenG74Q

The last line speaks volumes ;)

**Comment by nicm** [comment]
Does this still happen if you run "tmux -Ltest -f/dev/null new"?

**Comment by nicm** [comment]
Never mind, I know what this is.

**Comment by nicm** [comment]
This is because Cygwin's strftime implementation returns 0 for unknown formats. The behaviour on unknown formats is undefined, but returning 0 is not useful. Still, there isn't really much reason for us to have an expanding buffer here. Please try this: [x.txt](https://github.com/tmux/tmux/files/278203/x.txt)

**Comment by dutchgecko** [comment]
Yes, this patch fixes the issue. Thanks! I look forward to the next version.

**Comment by nicm** [comment]
Great, thanks.
