### ISSUE TITLE
REP of line-drawing characters behavior change since commit de6bce0

### ISSUE THREAD

**Issue by rfrancoise** [tmux/tmux#4182]
Commit `de6bce0` causes an issue with repeating line-drawing characters, as seen in `iftop`. The commit reverts cleanly and gets back the behavior seen in 3.4 and earlier releases after revert. I'm attaching client/server logs for both situations.

With current `HEAD`:
<img width="521" alt="Screenshot 2024-10-09 at 10 32 14 PM" src="https://github.com/user-attachments/assets/f8c2df29-d85e-4473-8abd-e39cda1ab6cb">
[tmux-client-NOK.log](https://github.com/user-attachments/files/17349571/tmux-client-NOK.log)
[tmux-out-NOK.log](https://github.com/user-attachments/files/17349572/tmux-out-NOK.log)
[tmux-server-NOK.log](https://github.com/user-attachments/files/17349573/tmux-server-NOK.log)

With commit `de6bce0` reverted:
<img width="515" alt="Screenshot 2024-10-09 at 10 31 24 PM" src="https://github.com/user-attachments/assets/88750cf7-2c71-4274-9d55-e72e5cda25f0">
[tmux-client-OK.log](https://github.com/user-attachments/files/17349575/tmux-client-OK.log)
[tmux-out-OK.log](https://github.com/user-attachments/files/17349576/tmux-out-OK.log)
[tmux-server-OK.log](https://github.com/user-attachments/files/17349577/tmux-server-OK.log)

As you will see from the log `iftop` is started with `TERM=xterm` inside tmux, otherwise it defaults to regular ASCII characters to draw the boxes.

* tmux version (`tmux -V`): `next-3.6`
* Platform (`uname -sp`): `Linux`
* $TERM inside and outside of tmux (`echo $TERM`): `screen-256color`

**Comment by nicm** [comment]
This fixes it for me: [x.diff.txt](https://github.com/user-attachments/files/17362215/x.diff.txt)

**Comment by rfrancoise** [comment]
Works for me too. Thanks!

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
