### ISSUE TITLE
OSC 133 prompt start marker sometimes ignored if immediately followed by clr_eol

### ISSUE THREAD

**Issue by krobelus** [tmux/tmux#4183]
fish-shell received a [bug report] about an apparent regression.
We'll probably apply a workaround but it sounds like it could be a bug in tmux.

Current repro steps are as follows (I can try to reduce further later):

```shell
$ git clone https://github.com/fish-shell/fish-shell
$ cd fish-shell
$ git checkout 69380c6c92e1e35db6593fc4696897ac4eea63f4
$ make
$ home=$(mktemp -d)
echo >$home/.tmux.conf '
    bind-key -T copy-mode-vi [ send-keys -X previous-prompt
    bind-key -T copy-mode-vi M-[ send-keys -X previous-prompt -o
    bind-key -T copy-mode-vi ] send-keys -X next-prompt
    bind-key -T copy-mode-vi M-] send-keys -X next-prompt -o
'
(
    sleep .5
    tmux -S $home/tmux-socket send-keys \
        '
            function fish_prompt
                printf "first_prompt_line\\nsecond_prompt_line> "
            end
            function signal-handler --on-signal USR1
                commandline -f repaint
            end
            function refresh-prompt --on-event fish_prompt
                kill -USR1 $fish_pid &
            end
        ' \
        Enter \
        'echo 1' Enter \
        'echo 2' Enter \
        'echo 3' Enter
) &
HOME=$home EDITOR=vim tmux -S $home/tmux-socket new-session build/fish
```

now inside tmux press `C-b [ [ [`.
Observe that this skips several prompts.
It should visit each prompt individually.

Evidently, this is triggered because when fish writes the OSC 133 prompt start sequence (`133;A`)
sequence, it prints `clr_eol` (`\x1b[K`) immediately afterwards.
We know this because if I apply this workaround to fish to first
print `clr_eol` and then print the OSC 133 marker, it works.

```diff
diff --git a/src/screen.rs b/src/screen.rs
index ff4f923c3..636aab45c 100644
--- a/src/screen.rs
+++ b/src/screen.rs
@@ -821,15 +821,20 @@ impl Screen {
         // Output the left prompt if it has changed.
         if left_prompt != zelf.actual_left_prompt {
             zelf.r#move(0, 0);
-            zelf.write_bytes(b"\x1b]133;A;special_key=1\x07");
             let mut start = 0;
-            for line_break in left_prompt_layout.line_breaks {
+            for (i, &line_break) in left_prompt_layout.line_breaks.iter().enumerate() {
                 zelf.outp
                     .borrow_mut()
                     .tputs_if_some(&term.and_then(|term| term.clr_eol.as_ref()));
+                if i == 0 {
+                    zelf.write_bytes(b"\x1b]133;A;special_key=1\x07");
+                }
                 zelf.write_str(&left_prompt[start..=line_break]);
                 start = line_break + 1;
             }
+            if left_prompt_layout.line_breaks.is_empty() {
+                zelf.write_bytes(b"\x1b]133;A;special_key=1\x07");
+            }
             zelf.write_str(&left_prompt[start..]);
             zelf.actual_left_prompt = left_prompt.to_owned();
             zelf.actual.cursor.x = left_prompt_width;
```

The fact that the repro involves fish repainting its prompt triggered by a signal handler suggests that it could be a race condition.
Other terminals that support OSC 133 like foot and kitty do not seem to reproduce the issue.

* tmux version reproduces with all of 3.4, 3.5, 3.5a and today's master (cb00e869ea34ed28bdd8f700d425fd250b209a9e)
* Platform `Linux unknown` or `macOS`
* $TERM inside and outside of tmux (`foot` / `tmux-256color`).

[bug report]: https://github.com/fish-shell/fish-shell/issues/10776

[tmux-server-1288192.log](https://github.com/user-attachments/files/17350685/tmux-server-1288192.log)
[tmux-out-1288192.log](https://github.com/user-attachments/files/17350687/tmux-out-1288192.log)
[tmux-client-1288189.log](https://github.com/user-attachments/files/17350688/tmux-client-1288189.log)

**Comment by nicm** [comment]
I can't look at the logs right now but if it does EL0 from column 1 it is erasing the line and that will include all the flags associated with the line, including the prompt. This seems like common sense to me and I'm surprised other terminals leave it in place. Do they keep it if you send say DL or ED3?

**Comment by krobelus** [comment]
If I send `dl` to `foot`, the prompt markers are left intact as well. Not sure how to send ED3 though I don't expect that will give us new information.

I agree that fish should not rely on the markers being left around.
So tmux behavior seems fine.
