### ISSUE TITLE
Meta key not working in OpenBSD console

### ISSUE THREAD

**Issue by iszczesniak** [tmux/tmux#4189]
I'm using OpenBSD 7.5 amd64 with a standard PC keyboard.  Under the console (switched to with Ctrl+Alt+F1, not in X), outside of tmux, the Meta key is recognized as I can tell with the `cat -t` command, where I entered M-x (and got ø) and pressed Enter, to which `cat` responded with M-x:

~ $ cat -t
ø
M-x

Inside tmux, the `cat` command shows no output.  However, it seems that tmux is receiving the key, because in the status bar I can see a change exactly when I press M-x from `0:ksh*` to `0:cat*`.

### Required information

* tmux version (`tmux -V`): tmux openbsd-7.5

* Platform (`uname -sp`): OpenBSD amd64

* $TERM inside and outside of tmux (`echo $TERM`): inside: screen, outside: vt220

* Logs from tmux (`tmux kill-server; tmux -vv new`): attached

To create the log files, in my session I:

* entered `cat -t`, pressed Enter,

* pressed M-x, pressed Enter,

* pressed C-d twice to exit cat and tmux.

[tmux-client-39888.log](https://github.com/user-attachments/files/17395280/tmux-client-39888.log)
[tmux-out-10677.log](https://github.com/user-attachments/files/17395281/tmux-out-10677.log)
[tmux-server-10677.log](https://github.com/user-attachments/files/17395282/tmux-server-10677.log)

**Comment by nicm** [comment]
Did this previously work? This is a top-bit-set key but not value UTF-8.

**Comment by iszczesniak** [comment]
Not in the past few months that I tried to use it.

**Comment by iszczesniak** [comment]
> What does `wsconsctl -a` show?

wsconsctl: Use explicit arg to view keyboard.map.
wsconsctl: Use explicit arg to view keyboard1.map.
wsconsctl: Use explicit arg to view keyboard2.map.
keyboard.type=pc-xt
keyboard.bell.pitch=400
keyboard.bell.period=100
keyboard.bell.volume=50
keyboard.bell.pitch.default=400
keyboard.bell.period.default=100
keyboard.bell.volume.default=50
keyboard.repeat.del1=400
keyboard.repeat.deln=100
keyboard.repeat.del1.default=400
keyboard.repeat.deln.default=100
keyboard.ledstate=0
keyboard.encoding=pl
keyboard1.type=usb
keyboard1.bell.pitch=400
keyboard1.bell.period=100
keyboard1.bell.volume=50
keyboard1.bell.pitch.default=400
keyboard1.bell.period.default=100
keyboard1.bell.volume.default=50
keyboard1.repeat.del1=400
keyboard1.repeat.deln=100
keyboard1.repeat.del1.default=400
keyboard1.repeat.deln.default=100
keyboard1.ledstate=0
keyboard1.encoding=pl
keyboard2.type=usb
keyboard2.bell.pitch=400
keyboard2.bell.period=100
keyboard2.bell.volume=50
keyboard2.bell.pitch.default=400
keyboard2.bell.period.default=100
keyboard2.bell.volume.default=50
keyboard2.repeat.del1=400
keyboard2.repeat.deln=100
keyboard2.repeat.del1.default=400
keyboard2.repeat.deln.default=100
keyboard2.ledstate=0
keyboard2.encoding=us.noencoding
mouse.type=usb
mouse.rawmode=1
mouse.scale=0,0,0,0,0,0,0
mouse.reverse_scrolling=0
display.type=inteldrm
display.width=1920
display.height=1080
display.depth=32
display.fontwidth=16
display.fontheight=32
display.emulations=vt100
display.screentypes=std
display.focus=0
display.screen_on=250
display.screen_off=0
display.vblank=off
display.kbdact=on
display.msact=on
display.outact=on

**Comment by nicm** [comment]
What are you trying to have happen? Do you want `M-x` to be sent as `ø` or do you want it to be `^[x` so that tmux and programs will recognise it?

**Comment by nicm** [comment]
OK try changing `keyboard.encoding` to `pl.metaesc`? Maybe same for the others.

When you run `cat` and press `M-x` outside tmux you want to be seeing `^[x`.

**Comment by iszczesniak** [comment]
> OK try changing `keyboard.encoding` to `pl.metaesc`? Maybe same for the others.
> 
> When you run `cat` and press `M-x` outside tmux you want to be seeing `^[x`.

I tried (I also recall trying this months ago):
`~ $ wsconsctl keyboard.encoding=pl.metaesc`
`keyboard.encoding -> pl.metaesc`

Sadly, when running `cat`, I don't see `^[x`, just `ø`.

Wait! You wrote "maybe same for the others". Did you mean keyboard1 and keyboard2? I don't know what they are, but changing keyboard1 requires root, while changing keyboard2 takes no effect.

So I tried for `keyboard1`:

`~ $ doas wsconsctl keyboard1.encoding=pl.metaesc`
`keyboard1.encoding -> pl.metaesc`

And indeed now I can see `^[x`, and Emacs in tmux receives M-x in the console. Thank you!

To make the changes persistent, in `/etc/wsconsctl.conf` I added:

`keyboard1.encoding=pl.metaesc`

So I don't think it's an issue with tmux as there is a way to configure OpenBSD. The problem is the weird `keyboard1`.

I will write to the OpenBSD mailing list to inquire about `keyboard1`, and I'll report back here later.

**Comment by nicm** [comment]
Do you have multiple keyboards? It says `keyboard1.type` is `USB` and `keyboard.type` is `pc-xt`.

If not, maybe your computer has both PS1 and USB ports internally but the actual keyboard is wired up with USB. `dmesg` might tell you what the hardware looks like.

**Comment by iszczesniak** [comment]
I found a better way of configuring my keyboard.  Instead of configuring keyboard1 in `/etc/wsconsctl.conf`, I put `pl.metaesc` in `/etc/kbdtype`.

I mentioned that I would do some more research on keyboard1 and keyboard2, and that I would report back.  I took a look at the output of `dmesg` and noticed three lines that seem to be about keyboards.  The drivers are `wskbd`, `ukbd` and `ucc`.  I took a look at the map of keyboard2, and it had only a few keys (`doas wsconsctl keyboard2.map`). Concluding something concrete (like keyboard1 is always the USB keyboard) would require more work, so I'll just leave it here, as my problem is solved.

Thank you again!

**Comment by iszczesniak** [comment]
I forgot to mention that my computer does not have the PS/2 keyboard port.  Maybe it still has a chip that supports PS/2 that I'm not aware of, and so the keyboard is recognized.  Or maybe OpenBSD always represents a PS/2 keyboard as `keyboard` regardless of whether it's present or not.
