### ISSUE TITLE
Slow output from Neovim messages/shell commands with multiple panes

### ISSUE THREAD

**Issue by tweekmonster** [tmux/tmux#419]
When Neovim produces output either through `:messages` or running a command such as `:!ls -al ~`, the output is displayed very slowly when there are other panes visible.  Here's a video of it happening: https://youtu.be/91cvQr7Ealo

In the video, I'm running: `!ls -al ~` in Neovim.  Once while there are two panes visible, and again with the Neovim pane zoomed.  When the pane is zoomed, the output is instant.  As a side note, this problem doesn't seem to occur (or isn't as noticeable) with mainstream Vim or running `ls -al ~` at the shell.

I ran `git bisect` but hit a dead end because `autogen.sh` wasn't present in the remaining commits:

```
The first bad commit could be any of:
c5443da2d3bd5ef2464cc59941e55890aaff3fb0
0d84fdd95303a6ed4dcd761425e35f3731b86725
5f2bfd980737d2f13b744e288532e5d2daf97a0f
ba9f32b464effc09b7ceaef21b1804c49ece17db
We cannot bisect more!
```

The commit earliest commit that I was able to compile with this problem: https://github.com/tmux/tmux/commit/ba9f32b464effc09b7ceaef21b1804c49ece17db

The last commit where the problem wasn't as bad: https://github.com/tmux/tmux/commit/e7de2fe552a7b4392f208533b72e7fcbe41c0537

@zchee found that increasing `READ_SIZE` to `1024` seems to resolve it, and increasing it to `2048` makes the output almost instant.  But, neither of us are familiar enough with tmux's source to know what the side effect would be.

**Comment by nicm** [comment]
Does this happen with tmux from Git master?

**Comment by zchee** [comment]
@nicm Hi, 
and, yes. also occur HEAD branch.

FYI, @tweekmonster said 
> As a side note, this problem doesn't seem to occur (or isn't as noticeable) with mainstream Vim or running ls -al ~ at the shell.

but, I tested.
If change the `READ_SIZE` value to `1024`or etc, it will improve performance even in the case of shell (e.g. `ls -la` on exists many files directory)
This problem is only vertical split. horizontal, or zooming(hide one pane), does not occur.

I hope this will help.

**Comment by tweekmonster** [comment]
@nicm Yes.  Before I did the bisect, I tried the tagged versions.  2.2 and 2.1 seem to be alright.

I guess `READ_SIZE` deals with buffering and it's how tmux deals with getting input when a pane is really busy with output?  It seems increasing it causes all panes to be unresponsive when a pane is printing quickly.

**Comment by zchee** [comment]
@nicm and, If you want to screencast, debug mode messages, debug log or gdb result, I can post them.

**Comment by nicm** [comment]
Yes the more you increase READ_SIZE the more output tmux will process from each pane before looking for input from the terminal outside.

**Comment by tweekmonster** [comment]
@nicm Would it be possible do this in the similar way HTTP servers deal with rate limiting?  Allow an initial burst, then taper down to a more reasonable rate after a short duration of continuous output?  I think newlines would have to be counted, though.

**Comment by ThomasAdam** [comment]
On 26 May 2016 4:43 p.m., "Tommy Allen" <notifications@github.com> wrote:
>
> @nicm Would it be possible do this in the similar way HTTP servers deal
with rate limiting? Allow an initial burst, then taper down to a more
reasonable rate after a short duration of continuous output? I think
newlines would have to be counted, though.

That's more or less how it used to be.

**Comment by nicm** [comment]
Yes, it was sort of like that. I didn't remove the C0 stuff because I objected to the idea of counting them, but because it never worked very well and I don't want something that the user has to tune - it needs to just work, no options.

**Comment by nicm** [comment]
Here's something that might work, putting the rate limiting at the client side instead of the pane, redrawing if it backs up too far let's us drop a lot of output: [x.txt](https://github.com/tmux/tmux/files/292322/x.txt)

**Comment by tweekmonster** [comment]
Please forgive me if I'm repeating things you've already considered or already know.  I haven't had a ton of free time to figure out if this would fit with how tmux operates (or if what I'm suggesting was already done in the past).

I was thinking of the rate limiting being about how many lines are in a pane.  The initial burst interval would be based on some hard coded value, like say `0.5s` since the last output.

1. Display, at most, 1 or 2 full panes worth of text.
2. If more than `0.5s` elapsed, reset the rate limit and process input.
3. If there's more output before rate is reset, divide the maximum line count and process input.  Keep dividing until a minimum is reached.  The minimum number of lines could be 1/8th of the pane height, or 5 lines.
4. After a fixed amount of time has passed with continuous output (say `5s`), manually reset the rate limiting and start over, but at half the pane height instead of the initial full pane height.

For the diagrams below, a box is a tmux pane, `#` is text output, and `.` is an input processing break.  A screen line is a visual line of text whether wrapped or not.

```
        Burst                     <500ms                  <500ms cont.    
+--------------------+    +--------------------+    +--------------------+
|####################|    |####################|    |####################|
|####################|    |####################|    |....................|
|####################|    |####################|    |####################|
|####################| -> |....................| -> |....................| ->
|####################|    |####################|    |####################|
|####################|    |####################|    |....................|
|####################|    |####################|    |####################|
+--------------------+    +--------------------+    +--------------------+

   (2000ms elapsed)             <500ms cont.              <500ms cont.    
+--------------------+    +--------------------+    +--------------------+
|####################|    |####################|    |####################|
|####################|    |....................|    |....................|
|####################|    |####################|    |####################|
|....................| -> |....................| -> |....................|
|####################|    |####################|    |####################|
|####################|    |....................|    |....................|
|####################|    |####################|    |####################|
+--------------------+    +--------------------+    +--------------------+
```

> Here's something that might work

@nicm Thanks!  I'll try it out in a little bit.

**Comment by tweekmonster** [comment]
@nicm I tried out the patch and it's certainly better in regard to this issue.  But, now scrolling in Vim is really choppy.  Scrolling in a pane is a slightly choppy, but not as bad as with Vim.

With fast output in a pane, it seems like it can be interrupted.  Sometimes I get it the first try, but I have to mash `ctrl-c` a couple times before it takes.  Other panes aren't responsive while one is printing a lot, though.

I'm using this to spam a pane:

```python
#!/usr/bin/python3
for i in range(200000):
    print('%06d test' % i)
```

**Comment by nicm** [comment]
I bumped READ_SIZE to 4096.
