### ISSUE TITLE
Tmux won't send ctrl + number to the terminal

### ISSUE THREAD

**Issue by printfdebugging** [tmux/tmux#4193]
### Issue description

I use tmux with neovim, and recently I found that the unbind C-1.. settings are not working. so I downloaded the source and built it first on the master then on master~50. it doesn't send the keys C-1 to C-9 to the terminal on the master, but it does on the master~50, so the bug has been introduced somewhere in between.

### Required information

tmux next-3.6
void-linux 
st-256color

please note that it's a tmux issue and not a terminal issue, as I have patched my terminal to not capture the control keys.

**Comment by printfdebugging** [comment]
There I meant 50 commits back from the latest master.

**Comment by nicm** [comment]
logs?

**Comment by printfdebugging** [comment]
[tmux-client-12236.log](https://github.com/user-attachments/files/17412799/tmux-client-12236.log)
[tmux-out-12238.log](https://github.com/user-attachments/files/17412800/tmux-out-12238.log)
[tmux-server-12238.log](https://github.com/user-attachments/files/17412801/tmux-server-12238.log)

Haha, I thought I could get away without those :)

**Comment by raaymax** [comment]
I have exactly the same issue only when using tmux `C-[0-9]` are not working.
tmux: 3.5a
NeoVim: v0.10.1
Alacritty: 0.14.0-dev
MacOS: 15.0.1

**Comment by nicm** [comment]
I do not see you pressing `C-1` or similar in this log.

**Comment by printfdebugging** [comment]
Here are the log files with control characters 
[tmux-client-3899.log](https://github.com/user-attachments/files/17416437/tmux-client-3899.log)
[tmux-out-3901.log](https://github.com/user-attachments/files/17416438/tmux-out-3901.log)
[tmux-server-3901.log](https://github.com/user-attachments/files/17416439/tmux-server-3901.log)

**Comment by nicm** [comment]
You have not turned `extended-keys` to `on`.

**Comment by printfdebugging** [comment]
Yes, you are right! placing `set -g extended-keys on` in the config makes it work as expected. Thanks!

**Comment by raaymax** [comment]
I have such entry in my config but it still doesn't work
```
❯ cat ~/.config/tmux/tmux.conf
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
```
[tmux-client-79385.log](https://github.com/user-attachments/files/17435188/tmux-client-79385.log)
[tmux-out-79387.log](https://github.com/user-attachments/files/17435189/tmux-out-79387.log)
[tmux-server-79387.log](https://github.com/user-attachments/files/17435190/tmux-server-79387.log)

**Comment by printfdebugging** [comment]
@raaymax I also have these in my tmux config
```
unbind C-1
unbind C-2
unbind C-3
unbind C-4
unbind C-5
unbind C-6
unbind C-7
unbind C-8
unbind C-9
unbind C-0
```
