### ISSUE TITLE
Support kitty keyboard protocol

### ISSUE THREAD

**Issue by Arnaudv6** [tmux/tmux#4196]
Hi there and thanks for your work on this project.

IFAICT #3335 is not fixed: I hit the bug on tmux-3.5a-r0 on alpine linux.
Work probably started (?) on #3335, (thanks @nicm for your instructions to @hovsater) but I can see no trace of any MR/commit.
This feature is key to tmux being a transparent proxy. Tmux limits some client applications that use this modern protocol, and situation will worsen as more modern applications see daylight.
I read you did not `intend to work on it`, but if you don't rule it _out of scope_, #3335 should be re-opened until a proper fix is merged. 

#3335, #2705

**Comment by nicm** [comment]
tmux is not a transparent proxy...

**Comment by nicm** [comment]
Support for this may come in time but you are not going to boss anyone into working on it.

**Comment by jixiuf** [comment]
My fork of tmux at https://github.com/jixiuf/tmux supports KKP (Disambiguate escape codes) with the following settings:

```
set -s kitty-keys always
set -as terminal-features '*:kitkeys'
```

It works well, but maybe there’s still a lot of work to be done before it can be merged. If you're interested, you can build upon what I've done.

**Comment by nicm** [comment]
Yes, a PR would go a lot further than unsolicited advice on how to manage issues. You will want to look at https://github.com/tmux/tmux/pull/4038 as well.

**Comment by Arnaudv6** [comment]
Again, thanks for your work and support, to me and @crzcrz, @jixiuf  and @hovsater...
#4038 is good news, as is https://github.com/jixiuf/tmux.
I still insist on my advice: visibility and collaboration would benefit from those bugs and this MR not being _closed but not merged yet wanted_.

**Comment by nicm** [comment]
I am not leaving PRs or issues open to rot forever when nobody is working - or even replying - to them. This is not likely to change. If someone wants to take it up *and has code or questions* they can easily open their own PR.
