### ISSUE TITLE
How do I remove the timestamp in the top right when in copy mode?

### ISSUE THREAD

**Issue by bpsib** [tmux/tmux#4197]
### Issue description
I get a timestamp when entering copy mode or scrolling back after updating to version 3.4. I find this really annoying and gets in the way. I don't see any need for a timestamp in this case. How do I remove this?

### Required information
* tmux version: 3.4
* Platform: Linux x86_64

![image](https://github.com/user-attachments/assets/46ed3643-02b6-4d91-8b24-3f90162652cc)

**Comment by nicm** [comment]
You will need to build from master and then you can configure this.

**Comment by bpsib** [comment]
I am livid that a timestamp now gets forced down our throats when scrolling and really wanted to disable this without having to build. Whoever decided this timestamp trash when scrolling deserves to be thrown in the dump. It's plain stupid. It needs to be optional rather than forced down our throats.
