### ISSUE TITLE
How to tweak styling in "Choose a session from a list" view (`C-b s`)

### ISSUE THREAD

**Issue by ccjmne** [tmux/tmux#4199]
### Issue description

Hey,
Thank you for this awesome project!

I cannot seem to figure out how to tweak the styling of these elements in the "Choose a session from a list" view:

![image](https://github.com/user-attachments/assets/36a0947f-f45a-4780-b58a-bd43b8ee626a)

I did scour the Web a little, browse the `man` page, this repository's closed issues, and ask ChatGPT; to no avail. Is it at all possible?

### Required information

```shell
> { tmux -V; uname -sp; echo $TERM }
tmux 3.5a
Linux unknown
tmux-256color
```

**Comment by nicm** [comment]
`display-panes-colour` and `display-panes-active-colour` are the only bits you can change here.

**Comment by ccjmne** [comment]
Thank you!
