### ISSUE TITLE
session_name number increases as you kill and start new sessions if another session is already running

### ISSUE THREAD

**Issue by Brottweiler** [tmux/tmux#420]
I create one new session, and detach it. . `tmux ls` shows this:

```
0: 1 windows (created Mon May 23 16:10:24 2016) [154x40]
```

I create a new session, it will automatically be called `1`. If I kill it, and then start a new one, I would expect the new one to be called `1` aswell, but it is called `2`.

As I start creating and killing new sessions, the `session_name`, or `#S` that I have in the status line or window title, will start to increase, like this.

```
0: 1 windows (created Mon May 23 16:10:24 2016) [154x40]
6: 1 windows (created Mon May 23 16:12:28 2016) [154x40]
```

If I kill the `0` window, so that I have no running sessions, then the `session_name` number will reset and it will start increase from `0` again.

Is this intentional, a bug, or can I work around this somehow?

**Comment by ThomasAdam** [comment]
It's intentional.  The session_id is global and ever-incrementing.
