### ISSUE TITLE
tmux: server exited unexpectedly

### ISSUE THREAD

**Issue by griffin-rickle** [tmux/tmux#4200]
### Issue description
Every time I attempt to run tmux, I am show the message `server exited unexpectedly`. In the resulting terminal I cannot see anything I type (even though it seems to still accept keystrokes; I can run commands). I have to close my terminal window and open another one to have a usable terminal. This issue happens whether I use Alacritty or the OOTB Terminal App that comes with Fedora 40.

### Required Information
I am using Fedora 40; `uname -sp` produces `Linux unknown`, so I provided `uname -sm` instead.

```
# uname -sm
Linux x86_64
```

```
# tmux -V
tmux next-3.6
```

```
# echo $TERM
screen-256color
```

### Log Files
I have provided a tar.gz file which contains a screenshot of what my terminal looks like, the 3 log files created by running `tmux -vv -Ltest -f/dev/null` as well as an strace output file produced by running `strace -o git/tmux/tmux-issue-attachments/tmux-strace.txt tmux -f/dev/null` here: 
[tmux-issue-attachments.tar.gz](https://github.com/user-attachments/files/17446960/tmux-issue-attachments.tar.gz)

Please let me know if there is anything else I can provide. Thank you in advance!

**Comment by nicm** [comment]
Can you repeat the strace but with `-ttt -fostrace.out` so it shows server and client process separately?

**Comment by griffin-rickle** [comment]
Sure thing! I have attached that here:
[tmux-strace-client_server.txt](https://github.com/user-attachments/files/17461043/tmux-strace-client_server.txt)


I will also add that this is tmux which I have compiled from source. I had previously been running tmux with the version supplied by `sudo dnf install tmux`. Sometime around when I upgraded to Fedora 40 I started having issues with tmux; the only feedback I received was `"tmux" : cannot locate symbol "tiparm_s"`. That's why I decided to build from source to see if that helped anything.

**Comment by nicm** [comment]
This is the same thing:
~~~~
8241  1729514949.749172 writev(2, [{iov_base="tmux", iov_len=4}, {iov_base=": ", iov_len=2}, {iov_base="symbol lookup error", iov_len=19}, {iov_base=": ", iov_len=2}, {iov_base="tmux", iov_len=4}, {iov_base=": ", iov_len=2}, {iov_base="undefined symbol: tiparm_s", iov_len=26}, {iov_base="", iov_len=0}, {iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 10) = 60
~~~~
Seems likely you have built tmux against an ncurses library that contains `tiparm_s` but are trying to run it against older libraries.

**Comment by pperalta** [comment]
Hello! I'm experiencing the same behavior on Photon OS with a `yum` installed tmux.

```
$ uname -a
Linux photon-machine 6.1.10-10.ph5-esx #1-photon SMP Mon Apr 24 22:51:08 UTC 2023 x86_64 GNU/Linux
$ tmux -V
tmux 3.5
$ echo $TERM
xterm-256color
```
I've attached my trace file: [tmux-strace.txt](https://github.com/user-attachments/files/17478305/tmux-strace.txt)

**Comment by griffin-rickle** [comment]
@pperalta I believe this is an issue with the specific way our machines have been configured. There must be some mismatch in the libraries provided by our package providers. I have already made a post on the Fedora Forums [here](https://forums.fedoraforum.org/showthread.php?333429-ncurses-issues-after-upgrade-to-Fedora-40), but it has not yet received any feedback; I'm actually pretty sure it won't receive any attention and we're going to be on our own.

**Comment by griffin-rickle** [comment]
Wow, I actually just found some more information randomly. I can't execute any terminal command which requires ncurses as my user. But I can execute the same commands just fine as root. Do you see the same behavior @pperalta?

**Comment by griffin-rickle** [comment]
Additionally, I am able to run tmux as my user if I compile version 3.3a from source and execute that binary. Sorry for the rapid influx of comments, I don't have a ton of time to put towards this and want folks to have all the info I have.

**Comment by pperalta** [comment]
> Wow, I actually just found some more information randomly. I can't execute any terminal command which requires ncurses as my user. But I can execute the same commands just fine as root. Do you see the same behavior @pperalta?

I tried tmux as root and I see the same behavior:
```
pperalta@photon-machine [ ~ ]$ sudo tmux
[sudo] password for pperalta
server exited unexpectedly
...
pperalta@photon-machine [ ~ ]$ su - root
Password:
root@photon-machine [ ~ ]# tmux
server exited unexpectedly
```

**Comment by nicm** [comment]
Compare `which tmux` and `ldd $(which tmux)` as root and as user.

**Comment by griffin-rickle** [comment]
@nicm thank you so much! I know you said that tmux must be running with a version of libncurses which was different than what it was compiled with. I was not sure how that could be the case, but I looked at my path and I didn't see anything too weird. Before your last comment, the linking process was sort of a black box; I wasn't sure how to examine which objects were being used at runtime. I also was not sure how to voice my ignorance. Your last comment was the golden ticket, though!

Here is the output of my user's `ldd /usr/bin/tmux`:
```
	linux-vdso.so.1 (0x00007fe94e423000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007fe94e394000)
	libncursesw.so.6 => /lib64/libncursesw.so.6 (0x00007fe94e355000)
	libtinfo.so.6 => /home/griff/.local/lib/mojo/libtinfo.so.6 (0x00007fe94e322000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe94e23e000)
	libhwloc.so.15 => /lib64/libhwloc.so.15 (0x00007fe94e1da000)
	libnl-3.so.200 => /lib64/libnl-3.so.200 (0x00007fe94e1b5000)
	libnl-genl-3.so.200 => /lib64/libnl-genl-3.so.200 (0x00007fe94e1ad000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe94dfbc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe94e425000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007fe94df84000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe94df56000)
```

Notice the path of `libinfo.so.6`! I had installed the SDK for modular's new programming language mojo some time ago and it had somehow become a source for shared objects. I removed all of mojo from my computer and I am happy to report that this is closed. 

@pperalta I would suggest executing the commands which @nicm provided and examining the output. I am not sure whether to close this issue or not due to your issue still being open.
