### ISSUE TITLE
[Feature Request] Allow infinite `repeat-time` and a command to exit prefix or any mode

### ISSUE THREAD

**Issue by budimanjojo** [tmux/tmux#4202]
Currently, the highest value of `repeat-time` is `32767`. It would be nice to be able to set it to `infinite` (maybe by setting it to `-1` or "infinite" string?).

And to exit the prefix mode, have a command like `root-mode` to return to `root` mode/key table?

The use case for me is I want to have a higher `repeat-time`, but I don't want to wait for too long when I'm done with what I'm doing. For example, I want to resize the pane without pressing prefix key again, so I use `bind -r` and have the repeat time set for say `10000ms`, but after I'm done resizing I don't want to wait for 10 seconds to be able to do something else. So naturally I want to go back to `root` mode by pressing something, let's say `Escape` key.

**Comment by nicm** [comment]
You can switch table as you like with `switch-client -T` and if you bind it to a non-repeating key it will turn off the repeat flag.

**Comment by budimanjojo** [comment]
Thank you! Yeah `switch-client -T` works as I want it to be with repeat flag (doesn't work without -r flag). But is the infinite `repeat-time` a reasonable feature to ask for? 32secs is long enough for me too so I'm fine with just this `switch-client -T` as a workaround.

**Comment by budimanjojo** [comment]
Yeah I'm fine with this being 32 seconds as max value too. Feel free to close this as I've got my answer. Thank you!

**Comment by budimanjojo** [comment]
Sorry, but I just found out that the maximum time for `repeat-time` is set to `10000` in the master branch by this commit: https://github.com/tmux/tmux/commit/a3dea81b496be2dd1665947a66844aa1c85434b0 so it will be too short now.

**Comment by nicm** [comment]
Yeah we can bump that up to like 200000 instead easily enough.

**Comment by budimanjojo** [comment]
That would be awesome :D

**Comment by nicm** [comment]
Should be changed now.
