### ISSUE TITLE
copy to clipboard stopped working in 3.5a

### ISSUE THREAD

**Issue by fredrik-jansson-se** [tmux/tmux#4204]
### Issue description
Clipboard stopped working in 3.5a (worked in 3.5 with the same tmux.conf).
I can NOT reproduce this on the master branch. 

I couldn't find any previous issues on this, hence the report, since it's fixed on master you may want to close it right away.

### Required information
Open a vertically split pane, mark text with mouse.
Expected: text to clipboard

This is over ssh from a Mac (iTerm2) to a Linux host.

Please provide the following information:
* tmux version (`tmux -V`).
`tmux 3.5a`
* Platform (`uname -sp`).
`Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`).
Inside: `screen-256color`
Outside: `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-server-717420.log](https://github.com/user-attachments/files/17459812/tmux-server-717420.log)

**Comment by nicm** [comment]
You must have built them against different ncurses versions and the 3.5a one is too old.

**Comment by fredrik-jansson-se** [comment]
I don't think so, I build them in the same source tree, just checking out master or a specific tag.

**Comment by nicm** [comment]
OK well if it works in master then it must be fixed.

**Comment by fredrik-jansson-se** [comment]
Yup :)
