### ISSUE TITLE
# New configuration format TOML

DISCUSSION 

### ISSUE THREAD

**Issue by VikasPoddar** [tmux/tmux#4207]
Hello people, 
I want to know if it's possible to add a new configuration format TOML: tmux.toml other than plain-text: tmux.conf as an optional configuration format.
I know, I am fully aware of the condition, why do you try to fix something which does not exist. But, I am thinking about uniformity across various tools in configuration format. 

I am happy to discuss, what are possible problems, edge cases, what can be done? What good and bad? 
Share your opinions

**Comment by nicm** [comment]
There won't be a new config format built into tmux, but you could easily
write something that translates your preferred format into tmux's.
