### ISSUE TITLE
Sixel graphics not working in Windows Terminal Preview

### ISSUE THREAD

**Issue by kyllingstad** [tmux/tmux#4208]
### Issue description

Sixel support has been added to Windows Terminal Preview version 1.22. Rendering a sixel image outside tmux works just fine, but inside it I only see a plain-text placeholder. Here is an example after I've SSH-ed into a Linux host from my Windows machine, *before* I start tmux:

![image](https://github.com/user-attachments/assets/9061ade6-e51b-479d-8ae2-580347f7c6f1)

After entering tmux (with no custom config), this is what I see instead:
```
$ echo $TERM
tmux-256color
$ cat snake.six
SIXEL IMAGE (38x15)+++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
```
I am using tmux 3.5a from Debian testing, which appears to have been compiled with sixel support:
```
$ tmux display -p '#{client_termfeatures}'
bpaste,ccolour,clipboard,cstyle,focus,margins,rectfill,sixel,title
```

### Required information

* tmux version (`tmux -V`): `tmux 3.5a`
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`): Inside: `tmux-256color`. Outside: `xterm-256color`.
* Logs from tmux (`tmux kill-server; tmux -vv new`): Attached: [tmux-server.log](https://github.com/user-attachments/files/17505144/tmux-server.log)

**Comment by nicm** [comment]
Attach full tmux server log please.

**Comment by nicm** [comment]
I suspect your terminal does not correctly support TIOCGWINSZ, there was a workaround for this added to master, I believe it was for some Windows terminal or other. Does this work with if you build tmux from master?

**Comment by yabb85** [comment]
I have the same issue on windows terminal with tmux builded from master with git clone https://github.com/tmux/tmux.git .


On windows terminal
```
❯ echo $TERM
tmux-256color
```
![image](https://github.com/user-attachments/assets/196ab3d6-188e-4ef4-91bf-a2012e6cef8f)

On tmux 3.4 from ubuntu 24.04:
Ouput:
```
❯ tmux -V
tmux 3.4
❯ echo $TERM
tmux-256color
❯ cat snake.six
SIXEL IMAGE (38x15)+++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
```

client feature:
```
❯ tmux display -p '#{client_termfeatures}'
bpaste,ccolour,clipboard,cstyle,focus,title
```

From tmux compiled with --enable-sixel option
```
❯ ./dev/tmux/tmux -V
tmux next-3.6
❯ echo $TERM
tmux-256color
❯ cat snake.six
SIXEL IMAGE (38x15)+++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++
```

client feature:
```
❯ ./dev/tmux/tmux display -p '#{client_termfeatures}'
bpaste,ccolour,clipboard,cstyle,focus,title
```

**Comment by kyllingstad** [comment]
> I suspect your terminal does not correctly support TIOCGWINSZ

Seems you are right: microsoft/terminal#8581
