### ISSUE TITLE
`#{client_key_table}` doesn't respond to `copy-mode` activation

### ISSUE THREAD

**Issue by budimanjojo** [tmux/tmux#4211]
### Issue description

Not sure if this is an intended behavior, but `#{client_key_table}` recognize `copy-mode` as `root`.
To reproduce:
1. Run `tmux set -g status-right "#{client_key_table}"`
2. Run `tmux copy-mode`
3. Notice that the right status shows `root` instead of `copy-mode`.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.5a`
* Platform (`uname -sp`): `Linux x86_64`

**Comment by nicm** [comment]
Changing mode doesn't change the default key table, it just overrides it. I don't think this is a problem, if you want to see the difference you can do something like `#{?pane_in_mode,#{pane_mode},#{client_key_table}}` instead.

**Comment by budimanjojo** [comment]
Thank you! Didn't know I can check it with `#{pane_mode}`
