### ISSUE TITLE
Sixel images dissapear when resizing either the panes or the window

### ISSUE THREAD

**Issue by joseluis** [tmux/tmux#4213]
### Issue description

Rendered sixel images dissapear when geometry changes, either by resizing panes or the terminal window.
But they do not dissapear when resizing the terminal window outside of tmux. Tested with wezterm and alacritty (graphics branch).

Tested with latest master build and an empty config:
`tmux -L testing-tmux -f /dev/null new-session`

### Required information
tmux next-3.6
Linux x86_64
xterm-256color|tmux-256color
alacritty|tmux-256color

**Comment by nicm** [comment]
tmux does not currently support preserving SIXEL images across resize.

**Comment by joseluis** [comment]
Thank you for the confirmation. I hope some day it'll be supported 👍🏻
