### ISSUE TITLE
Clipboard wiki page should mention allow-passthrough option

### ISSUE THREAD

**Issue by graham33** [tmux/tmux#4214]
### Clipboard wiki page should mention allow-passthrough option

I recently spent some time trying to get `set-clipboard` to work, to eventually discover that I needed to set the `allow-passthrough` option as well. It would be nice if https://github.com/tmux/tmux/wiki/Clipboard mentioned this.

I don't believe I can edit the wiki myself, but let me know if that's not the case, I'm happy to.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `tmux 3.5a`
* Platform (`uname -sp`). `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`). `tmux-256color`, `xterm-kitty`
* Logs from tmux (`tmux kill-server; tmux -vv new`). n/a

**Comment by nicm** [comment]
allow-passthrough is not required for set-clipboard.

**Comment by graham33** [comment]
> allow-passthrough is not required for set-clipboard.

Interesting, it seems to be required in my case. Note that what doesn't work without it is OSC52 from applications run within tmux (i.e. `set-clipboard on`, not `external`), copying from tmux itself to the system clipboard via OSC52 works fine without it. It made sense to me that this might be blocked based on the description of `allow-passthrough`.

**Comment by nicm** [comment]
Probably whatever applications you are using are using the bypass sequence rather than just setting the clipboard normally.

**Comment by graham33** [comment]
> Probably whatever applications you are using are using the bypass sequence rather than just setting the clipboard normally.

It's just Emacs using [clipetty](https://github.com/spudlyo/clipetty), which is hopefully not doing anything too unusual. I also noticed that https://github.com/theimpostor/osc has [an explicit check for allow-passthrough](https://github.com/theimpostor/osc/blob/main/main.go#L169), which implies I'm not the only one to encounter this.

Anyway, happy to close this if you think it's not a general issue, just thought it would be worth flagging.

**Comment by crzcrz** [comment]
Emacs' built-in `xterm.el` fully supports OSC52 clipboard access, there's no need in extra packages, they only cause issues.
