### ISSUE TITLE
tmux source-file can enter an infinite loop

### ISSUE THREAD

**Issue by gpakosz** [tmux/tmux#4215]
### Issue description

It's possible to make make the `source-file `command enter an infinite loop with the following `.conf` files:

```
source -F '#{current_file}'
```

or

```
source -F '#{d:current_file}/*.conf'
```

Maybe tmux could inspect `config_files` before including another file again? As a safety net.

### Required information

* tmux version (`tmux -V`): `tmux 3.5a`
* Platform (`uname -sp`): `Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color` and `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): I don't think it's needed

**Comment by nicm** [comment]
There are two ways to fix it, either keep a list of all the previous files and do not allow one to be included again, or just have a hard limit on the amount of nesting (say 20 or 100 or something). The former will prevent a file conditionally including itself or a file that includes itself so the latter is probably better.

**Comment by gpakosz** [comment]
Having a configuration that includes the same file multiple times, and relies on variables having specific values, and using `%if` statements is somewhat convoluted but possible 🙃

Having a hard limit sounds reasonable. And in that case `source-file` should return an error.

**Comment by FadiAfani** [comment]
> There are two ways to fix it, either keep a list of all the previous files and do not allow one to be included again, or just have a hard limit on the amount of nesting (say 20 or 100 or something). The former will prevent a file conditionally including itself or a file that includes itself so the latter is probably better.

can nesting be counted by the number of references to a given file or a client ? by looking at the source code it seems to me a new client_file instance is created with each source-file call for a given client, am I getting this wrong ?

**Comment by nicm** [comment]
I don't really know where it would go because it will need to be somewhere that subsequent `source-file` commands can access. I guess it would need to go into the `cmdq_item`.

**Comment by nicm** [comment]
This should be fixed now, thanks.

**Comment by gpakosz** [comment]
Thank you @FadiAfani and @nicm 🙏
