### ISSUE TITLE
Shortcut is different from manual discription  in WSL2-Ubuntu at 3.2a  version

### ISSUE THREAD

**Issue by 1078249029** [tmux/tmux#4219]
### Issue description

When I use C-b M-3  to reset window to  Set the main-horizontal layout, the window was reset Set the main-vertical layout which shortcut of C-b M-4.It's different from manual.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* tmux 3.2a  
* Platform (`uname -sp`).
* Linux DESKTOP-EPJK785 5.15.153.1-microsoft-standard-WSL2 # 1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* $TERM inside and outside of tmux (`echo $TERM`).
* screen(inside)
* xterm-256color(outside)
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by 1078249029** [comment]
> Seems fine to me:
> 
> ```
> $ tmux lsk -Tprefix M-3
> bind-key -T prefix M-3 select-layout main-horizontal
> ```
Sorry,you could don't get me.I mean the discription of manual is *different* from result caused by shortcut key.For me,it wiill transform  Set the main-vertical layout.

**Comment by nicm** [comment]
The manual says `M-3` is `main-horizontal` and that is what `M-3` does.
