### ISSUE TITLE
Add capture-pane option to only preserve trailing spaces

### ISSUE THREAD

**Issue by MarkLodato** [tmux/tmux#422]
Would it be possible to add an option to `capture-pane` that *only* preserves trailing spaces but does not join?  `-J` does both, but I do not want the lines to be joined.

Background:  I am trying to document tmux's behavior for each of [vt100-parser](https://github.com/MarkLodato/vt100-parser)'s test cases.  My setup is to run each `.in` file through the following:

    tmux new-session -d -x 80 -y 24 "./rawcat <file>; tmux wait-for -S done" \; wait-for done \; capture-pane -S - -p

This almost works but it removes trailing spaces from the ends of the lines.  Adding the `-J` option to `capture-pane` preserves spaces but then joins the lines.

Alternatively, if you can think of a solution where I can use existing commands to do what I want, that would be cool too!

**Comment by nicm** [comment]
I don't object to such an option, it would not be a big change.

**Comment by nicm** [comment]
I will put this in the TODO file.
