### ISSUE TITLE
Need help debugging sporadic hang

### ISSUE THREAD

**Issue by tom-neara** [tmux/tmux#4226]
### Issue description

For a long time now I get into a situation where all TMUX sessions on my machine stop working, all `tmux` commands hang indefinitely, and the only fix is to `rm /tmp/tmux-$UID/default` which means I lose ll my session history. I don't think it's possible to provide steps to repro, and I'm happy to debug this myself, but I don't know where to start. Is there any advice as to what logging/asserts/etc I should add to help diagnose this issue the next time it happens?

I'm using `tmux -CC` with iTerm2's tmux integration.

### Required information

Please provide the following information:

* tmux version: tmux next-3.5
* Platform: Linux x86_64
* $TERM inside and outside of tmux: tmux-256color/xterm-256color
* Logs from tmux N/A

**Comment by nicm** [comment]
When it hangs see what `pstack` says on the server process or attach with `gdb -attach $(which tmux) PID` and look at the backtrace with `bt`.
