### ISSUE TITLE
3.5/3.5a breaks <S-CR> in neovim

### ISSUE THREAD

**Issue by zcysxy** [tmux/tmux#4228]
### Issue description

I have a keymap `<S-CR>` (Shift + Enter) in neovim to accept completion candidate. This keymap works fine with tmux 3.4, but breaks in 3.5/3.5a.

Temporary workaround: revert to 3.4

### Required information

Please provide the following information:

* tmux version: 3.5a.
* Platform: Darwin arm.
* $TERM inside tmux: tmux-256color.
* $TERM inside tmux: xterm-256color

**Comment by zcysxy** [comment]
Minimal config: no config for tmux, init.lua for neovim:

```lua
vim.api.nvim_set_keymap("i", "<S-CR>", "hello", { silent = true, noremap = true })
```

Reproduce:

```shell
tmux
nvim -u init.lua
```

The keymap works outside of tmux but breaks in tmux 3.5a.

**Comment by nicm** [comment]
No logs.
