### ISSUE TITLE
clear-history

### ISSUE THREAD

**Issue by rafaelpirolla** [tmux/tmux#4232]
~~~~
If you shell supports C-l it is probably easier, something like:

bind C send C-l \; clear-history
~~~~

_Originally posted by @nicm in https://github.com/tmux/tmux/issues/1730#issuecomment-490947890_

### Replicate
Make the tmux.conf:
cat ~/.tmux.conf
bind C send 'C-l' \; clear-history

Start tmux, create some text until you create some history. Use the bind.
Enter copy mode. Expected not to see anything above the last line, actually history still there.

Any way to fix this to get the expected result? (GNU screen have this feature on prefix + upper case C - it works while doing a tail -f in a big log; meaning you don't need to execute anything in the shell)

**Comment by trailblazing** [comment]
Have you ever tried writing like this? 
```
bind C send 'C-l' \; clear-history

```
Or enclose the right hand side in quotation marks (backslashes no longer needed)?

**Comment by rafaelpirolla** [comment]
I've tried these:
```
bind C-t send 'C-l' \; clear-history
bind C-n send 'C-l' \; 'clear-history'
bind C-l "send 'C-l' ; clear-history"
bind C-c "clear-history ; send 'C-l'"
bind C-g "send 'C-l' \; clear-history"
bind C-s {
  send 'C-l'
  clear-history
}
```

**Comment by nicm** [comment]
Try adding a delay after the `send C-l` (`run -d0.5` or similar) or doing `send -R` first so the visible content is sure to be in the history before you clear it.

**Comment by rafaelpirolla** [comment]
Aha, thanks. That did it:
```
bind C-k {
  send -R 'C-l'
  run -d0.5
  clear-history
}
```
