### ISSUE TITLE
Nested %if %else %endif seems failed?

### ISSUE THREAD

**Issue by trailblazing** [tmux/tmux#4234]
I am currently typing on my phone, trying to write the minimum settings. Please forgive me if there are omissions in the description, I will add them later. If the question is valid, please let me know if there is anything that needs to be supplemented.
>cat t.conf
```
L1=1
L2=1
test=
%if #{L1}
  %if #{L2}
    test=1
  %else
    test=2
  %endif 
  test=5
%else
  %if #{L2}
    test=3
  %else
    test=4
  %endif 
  test=6
%endif 
display -p "test=#{test}"

```

>tmux source t.conf

Expected output:
>test=1

Actual output:
>test=3

>tmux -V
>tmux 3.4/3.5a

Is this a design or a bug? 
Thank you :)

**Comment by gpakosz** [comment]
What's the explanation please?

**Comment by gpakosz** [comment]
Discussed here: https://groups.google.com/g/tmux-users/c/fsg-dp2WkHc
