### ISSUE TITLE
Feature Request: Keybindings scoped like options (`-g`, `-s`, `-w`, `-p`)

### ISSUE THREAD

**Issue by theutz** [tmux/tmux#4235]
It would be great if I could define one-off keybindings for simple tasks that are specific to an open window. My main use-case is to trigger a build in a different tmux pane in the same window without having to switch to the second window.

```
|------------------------|-------------|
|                        |             |
| `EDITOR`               | `make`      |
|                        |             |
|------------------------|-------------|
```

I can spawn the second pane from the first with `tmux splitw -h make`, and if `remain-on-exit` is set, the results will linger.

But I'd like to be able to press `<C-b>g` and have it respawn that second pane to run the script again. Currently, there's no way for me to write these kind of one-off, per-window bindings without using hooks.

If I could type `<C-b> :bind -w g "respawnp -t.2"` to bind `<C-b>g`, I think that'd be pretty neat.

**Comment by nicm** [comment]
You can make `g` something like:
~~~~
bind -n g { if -F '#{@respawn_on_key}' 'respawnp' 'send g' }
~~~~
And then do that when you want to change the key binding:
~~~~
set -p @respawn_on_key 1
~~~~
Or `-w` for the whole window rather than a single pane.

**Comment by theutz** [comment]
Ah! I hadn't even considered using custom options for this use-case. I'm sure you're right that I can achieve what I'm looking for with some combination of those tools. Thanks!
