### ISSUE TITLE
Session is killed for some reason

### ISSUE THREAD

**Issue by heya5** [tmux/tmux#4238]
### Issue description
In one of my machines, I found that tmux sessions without any running processes disappear after a while (maybe 5 minutes). I also haven't made any additional configurations after installing tmux, and I don't have a `~/.tmux.conf` file.

### Required information

Please provide the following information:

* tmux version: tmux 3.2a
* Platform: Linux x86_64
* $TERM inside and outside of tmux: outside is xterm-256color, inside is 
* Logs from tmux:  
[tmux-server-1945210.log](https://github.com/user-attachments/files/17749440/tmux-server-1945210.log)
[tmux-client-1945208.log](https://github.com/user-attachments/files/17749441/tmux-client-1945208.log)

**Comment by nicm** [comment]
Try unsetting `TMOUT`:
~~~~
1731591787.085580 client 0x5561134208b0 IDENTIFY_ENVIRON TMOUT=300
...
1731591805.710551 input_parse_buffer: %0 ground, 52 bytes: \033[?2004l\r\atimed out waiting for input: auto-logout\r\n
~~~~

**Comment by heya5** [comment]
Thanks! You are right. I unset `TMOUT` in my `~/.bashrc` and it worked!
