### ISSUE TITLE
Choose pane and zoom in one go

### ISSUE THREAD

**Issue by quite** [tmux/tmux#424]
I wanted a key for choosing a pane display-panes style, and then activating and zooming in on it in one go. Tentative, as provided by jo_sch on #tmux:

  bind-key C-x display-panes \; resize-pane -Z

But no, that doesn't work. resize-pane doesn't wait for display-panes to be done. I feel running tmux from the outside with some sleep or so to be a bit hackish. It would be cool if display-panes could be used somehow like the command-prompt for the purpose of selecting a pane and doing something with it..

**Comment by nicm** [comment]
Yes, it would be good if display-panes worked like command-prompt.

**Comment by ThomasAdam** [comment]
I'm looking at this. Patch will be sent soon.

**Comment by nicm** [comment]
Try this please: [x.txt](https://github.com/tmux/tmux/files/316613/x.txt)

This makes display-panes work like command-prompt, in that you can specify a command sequence to execute with the selected pane:

tmux display-panes 'selectp -t%%; resizep -Z'

But it doesn't block the client command queue, so "display-panes\; resizep -Z" will still not work. I don't see any particular need to make it block (command-prompt and choose-* and the rest don't).

**Comment by quite** [comment]
Neat! Works as expected. And yes, that these functions behave similarly feels most important.

**Comment by nicm** [comment]
Applied, thanks.
