### ISSUE TITLE
Default shell is `sh`, regardless of `set-option -g default-shell`

### ISSUE THREAD

**Issue by rohansatapathy** [tmux/tmux#4240]
### Issue description

I use `fish` as my default shell (configured in iTerm2 settings and `chsh -s`) and until recently, tmux respected the default setting I had in place. At the moment, when I launch tmux from `fish`, the default shell in the initial pane is  `sh` instead of `fish`, which is really confusing. There are a couple things I think might have caused this to happen:

1. Recently, I installed [`tmux-resurrect`](https://github.com/tmux-plugins/tmux-resurrect) and [`tmux-continuum`](https://github.com/tmux-plugins/tmux-continuum), then uninstalled them after some experimenting. I didn't change the default configuration at all, just tried using session persistence once.
2. I upgraded my operating system to macOS Sequoia recently, which might have changed the shell configuration?

The one thing I tried was adding the following line to my `tmux.conf`:
```
set-option -g default-shell /opt/homebrew/bin/fish
```
When I added this line and killed and restarted the server, I was still launched into `sh`. 

Any guidance here would be much appreciated, thank you!

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux 3.5a`
* Platform (`uname -sp`): `Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`): Outside of tmux: `xterm-256color`, inside of tmux: `tmux-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`): Attached below.
[tmux-client-38794.log](https://github.com/user-attachments/files/17758223/tmux-client-38794.log)
[tmux-out-38796.log](https://github.com/user-attachments/files/17758224/tmux-out-38796.log)
[tmux-server-38796.log](https://github.com/user-attachments/files/17758225/tmux-server-38796.log)

`tmux.conf`:
```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tinted-theming/base16-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

# Set prefix
unbind C-b
set -g prefix M-Space
bind M-Space send-prefix

# Set colorscheme
# set -g default-terminal "screen-256color"
# set-option -sa terminal-overrides ",xterm*:Tc"
set -g @colors-base16 'ia-dark'

# Set status bar on top
set -g status-position top

# Enable mouse
set -g mouse on

# Enable yanking from tmux window
set -g set-clipboard on

# Start window and pane numbering at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Rebind split pane keys and open panes in current directory
bind '_' split-window -v -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"
bind 'c' new-window      -c "#{pane_current_path}"

# Use Prefix-R to reload tmux configuration
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded."

# Status bar configuration
set -g status-left-length 20

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator

# decide whether we're in a vim process
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'

if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

set-option -g default-shell /opt/homebrew/bin/fish

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Keep at bottom? I think?
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by rohansatapathy** [comment]
I found the solution in #4162 -- I needed to add the following lines to the bottom of my config:
```
set -gu default-command
set -g default-shell "$SHELL"
```

**Comment by skowalak** [comment]
@rohansatapathy @MarkusLohmayer Are you both using the Nix package manager? I am experiencing the same problem, but I do not think the source is here at tmux but rather at nixpkgs.

**Comment by rohansatapathy** [comment]
I’m using Homebrew, not Nix.
