### ISSUE TITLE
add a way to search only the visible contents of the pane

### ISSUE THREAD

**Issue by jyn514** [tmux/tmux#4244]
### Issue description

Some programs use the alternate screen to display a TUI. Often, I want to search for text only within the TUI, not within my command history. There is currently no way to do this that I know of, other than hackery with `capture-pane`, because `tmux send-keys -X search-forward` unconditionally searches the whole pane history, not just the visible pane.

### Steps to reproduce:

1. spawn a new pane
2. `echo foo`
3. scroll down far enough that the output goes off the screen. i am not entirely sure why this step is necessary.
4. `echo foo | less`
5. enter copy mode (`C-b [` by default)
6. search for `foo`. either the first or second hit will show the main screen, not the alternate screen (depending whether you searched forward or backward).

![image](https://github.com/user-attachments/assets/6850293f-f0b6-41c4-8679-5624bc8bc719)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

```
; uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux next-3.6
tmux-256color
```

TERM outside tmux is `xterm-kitty`.

Github for some reason is not letting me upload files. i've put them in a paste here: https://gist.github.com/jyn514/f96794af52377b4dcaa20424cb69df76

**Comment by nicm** [comment]
I guess you mean `search-backward`, not `search-forward`.

It seems like you could do this trivially by creating a binding that does `top-line` and then `search-forward`. You could turn off `wrap-search` if you don't like it wrapping at the bottom.

**Comment by jyn514** [comment]
> It seems like you could do this trivially by creating a binding that does `top-line` and then `search-forward`. You could turn off `wrap-search` if you don't like it wrapping at the bottom.

this is a cool idea, it got me close. but it doesn't do what i want: i want wrapping at the bottom to go to the top of the *visible* pane, not the top of the pane history. with your idea, if i hit N to search up, it still goes off the screen instead of wrapping.
