### ISSUE TITLE
Tmux session breaking neovim keybindings

### ISSUE THREAD

**Issue by whoop-t** [tmux/tmux#4249]
### Issue description
Certain keybindings do not make it to neovim

I use nvim keybindings with `ctrl` like `ctrl + ,`  `ctrl +m`  `ctrl + .`  `ctrl + /`
these work correctly outside of a tmux session.

Within a tmux session, these bindings dont work. It seems tmux interprets some key differently while in a tmux session.

**Is there a work around to have tmux recognize these key correctly**, Id rather not rebind my nvim config based on tmux

### Replicate
Install tmux
Install neovim
Create a basic init.lua with `ctrl + ,` bound to something
Open tmux session
Open nvim and try keybinding, observe not working

Also test without tmux and see keybinding work

### Required information

Linux/MacOS
tmux next-3.6 / tmux 3.5a
tmux-256color
NVIM v 0.10.1
kitty/iterm2
zsh/bash

**Comment by vamuscari** [comment]
Hello!

What terminal are you using? Do any of your keybindings from tmux conflict with your terminal?

I am using a MBP M3 
kitty 0.37.0
tmux 3.5a 
nvim 10.2

I am personally not experiencing this issue so it might be something with your configs.

**Comment by whoop-t** [comment]
@vamuscari 

I'm on kitty and tested with config and no config, but I've also tested with iterm2 and popos default terminal. Doesn't seem to have to do with any config, it's just tmux not interpreting certain Ctrl combinations.

**Comment by whoop-t** [comment]
Video of neovim tmux session in neovim not recognizing `ctrl + , . / ;`
The first part is in a tmux session try to use `ctrl + ,' etc
The second is not tmux doing the same

If you enter insert mode then type `ctrl + v`, you instruct vim to enter the literal terminal code you press next.
You can see in the tmux session it doesn't register `ctrl` when hitting `ctrl + ,` etc
Without the session you can see it is inserted just fine

https://github.com/user-attachments/assets/67fbeada-0510-4c9d-9938-537cd06953e0

**Comment by vamuscari** [comment]
@whoop-t I dropped my configs and it is ignoring the ctrl key for those. The may be related to the the [3.5a ctrl update.  ](https://github.com/tmux/tmux/issues/4162#issue-2567682883)
Ill try to see what is different for my configs so you can at least have a work around.  

Here is my logging for a nvim and tmux with no additional configurations. 
Running `nvim -V10nvim-startup` in and out of tmux with configs. 
[nvim-startup.log](https://github.com/user-attachments/files/17815066/nvim-startup.log)
[nvim-tmux-startup.log](https://github.com/user-attachments/files/17815070/nvim-tmux-startup.log)
[tmux-keys.log](https://github.com/user-attachments/files/17815117/tmux-keys.log)

Diff isn't show anything obvious here but I could be missing something.

**Comment by whoop-t** [comment]
@vamuscari 
Thanks for testing, I've also verified this issue with others I know who use tmux and they are able to replicate it.

Also noting I did test with tmux 3.2a and same issue.

**Comment by TRPB** [comment]
How can I debug this?

I have a bare-bones config, keybinds work if I just run `nvim` but running it inside tmux breaks them.

`cat` then typing `Ctrl+/` gives the same result both inside and outside tmux and even inside a terminal inside nvim.

both zellij and screen have the same issue though so I'm not actually convinced it's tmux specific, it may be a nvim problem. But I have no idea why nvim would see anything differently inside/outside a multiplexer

**Comment by TRPB** [comment]
The same thing happens in `screen` and `zellij` though regardless of terminal emulator or shell in use. The only common factor is nvim

**Comment by whoop-t** [comment]
@nicm
Logs
[tmux-client-63650.log](https://github.com/user-attachments/files/17834772/tmux-client-63650.log)
[tmux-out-63652.log](https://github.com/user-attachments/files/17834773/tmux-out-63652.log)
[tmux-server-63652.log](https://github.com/user-attachments/files/17834774/tmux-server-63652.log)

Also tested in vim(not neovim) and same issue with ctrl + ,(and others) not working

**Comment by nicm** [comment]
You do not have extended keys turned on. Assuming your terminal supports them, try adding these to .tmux.conf and restarting tmux entirely:
~~~~
set -s extended-keys on
set -as terminal-features 'xterm-kitty:extkeys'
~~~~
If this doesn't work please show updated server log with these in place.

**Comment by TRPB** [comment]
I've added a bug report to neovim. `emacs -nw` recieves the same key presses just fine within tmux, further pointing towards a neovim issue

**Comment by whoop-t** [comment]
@nicm 

@TRPB Is correct, same issue with it on

here are logs though:
[tmux-client-89493.log](https://github.com/user-attachments/files/17836306/tmux-client-89493.log)
[tmux-out-89496.log](https://github.com/user-attachments/files/17836307/tmux-out-89496.log)
[tmux-server-89496.log](https://github.com/user-attachments/files/17836309/tmux-server-89496.log)

**Comment by whoop-t** [comment]
@nicm Same for iterm2
[tmux-client-2209.log](https://github.com/user-attachments/files/17836781/tmux-client-2209.log)
[tmux-out-2211.log](https://github.com/user-attachments/files/17836782/tmux-out-2211.log)
[tmux-server-2211.log](https://github.com/user-attachments/files/17836783/tmux-server-2211.log)

**Comment by whoop-t** [comment]
@nicm See reply on nvim issue report, might relate
https://github.com/neovim/neovim/issues/31282#issuecomment-2489733089

Yes I am pressing `C-.`
I see just `.`
<img width="523" alt="Screenshot 2024-11-20 at 4 10 28 PM" src="https://github.com/user-attachments/assets/5a46673f-2135-4b40-baaf-58b3ab8bd89e">

**Comment by nicm** [comment]
If you are only seeing `.` for `C-.`  outside tmux then there is no way for tmux to distinguish them and the problem lies with your keyboard, OS, or terminal configuration.

**Comment by whoop-t** [comment]
It seems more of an issue that tmux doesnt support the keyboard protocol used in terminals like kitty, iterm2, wezterm etc

I've tested on macos and ubuntu, multiple keyboards and default configs for more of these.

**Comment by nicm** [comment]
That is incorrect, iTerm2 and tmux both support the same extended keyboard protocol.

Kitty has its own protocol which tmux does not support, I don't know if it also supports the standard protocol.

**Comment by whoop-t** [comment]
So there are no plans to support the kitty keyboard protocol?

I will look into if kitty supports the standard protocol

**Comment by nicm** [comment]
Several people have talked about it but nobody has done the work yet, it may come in time.

It should work for you in iTerm2, are you sure your iTerm2 version is up to date? Did you try changing the option mentioned in point 1 at https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys?

After you do `printf "\033[4;2m` outside tmux, if you go to the right click menu there is a submenu with a bunch of terminal options on it (keys, mouse etc) - what is ticked on that menu?

**Comment by whoop-t** [comment]
@nicm Sorry I dont normally drive iterm2, I updated and followed the steps in the tmux link you sent and now it does work
<img width="809" alt="Screenshot 2024-11-20 at 4 44 49 PM" src="https://github.com/user-attachments/assets/ca15e683-d5f1-4d35-875d-403238bee0df">

This also makes them work in neovim.

So this seems more like tmux doesnt handle the kitty key protocol, but also kitty doesnt seem to have a way to not use the kitty protocol, atleast I have found it as of yet.

**Comment by nicm** [comment]
OK well that is expected, if you want the full range of extended keys in tmux you will need to use a terminal which supports the same protocol.

If it's only a couple of keys you may be able to work around it by configuring tmux to forward what the terminal sends using the `user-keys` option and `send-keys` and suitable configuration at the application.

**Comment by whoop-t** [comment]
So as a work around I just rebind them directly in my `kitty.conf` and in neovim binding.

kitty.conf
```
# Make kitty send different keys when ctrl + KEY is pressed
map ctrl+m send_key alt+j
map ctrl+, send_key alt+k
map ctrl+. send_key alt+l
map ctrl+/ send_key alt+;
```

Then just map the keybinding in neovim that I want for  `ctrl + ,` (or whatever) to `alt + k`

**Comment by TRPB** [comment]
thanks for the explanation and workaround!

I'm seeing the same ctrl-/ problem in both alacritty and wezterm though so it's not kitty specific
