### ISSUE TITLE
Tmux split by windows key binding are reversed

### ISSUE THREAD

**Issue by cruz94** [tmux/tmux#4251]
### Issue description

Key binding for window splits are reversed as shown below 

![image](https://github.com/user-attachments/assets/5f3d3411-cc1b-4dd0-9be7-cd45a6879b7d)

### Required information
* tmux version (`tmux 3.5a`).
* Platform (`Darwin arm`).
* $TERM inside and outside of tmux (`tmux-256color`).

**Comment by nicm** [comment]
No they are correct.

**Comment by cruz94** [comment]
@nicm  - really??
C-b " - Split window vertically
result
![image](https://github.com/user-attachments/assets/6e8a162e-c2d6-4bdc-a496-13b3aad41c98)

C-b % - split window horizontally
result
![image](https://github.com/user-attachments/assets/1dd5fd75-d644-4707-9290-06dc5a702b21)
