### ISSUE TITLE
adding window_linked to window-status-format shows unexpected behavior

### ISSUE THREAD

**Issue by dalbertom** [tmux/tmux#4258]
### Issue description

I noticed that `#{window_flags}` does not include a marker for `#{window_linked}` so I added it to my config:
```
set -g window-status-format "#I:#W#F#{?window_linked,L,}"
set -g window-status-current-format "#I:#W#F#{?window_linked,L,}"
```

However, the `L` marker sometimes shows for windows that are not linked, and it disappears shortly after, especially when creating a new window or switching between windows.

I tried checking for window_linked on the window while the marker was showing and it shoed zero, but it's possible I didn't run it quickly enough.

### Required information

Please provide the following information:

* tmux version: 3.5
* Platform: Darwin arm
* $TERM inside tmux: screen-256color, outside tmux: xterm-256color
* Logs from tmux (`tmux -L test -vv new`).
  * [tmux-client-16112.log](https://github.com/user-attachments/files/17838576/tmux-client-16112.log)
  * [tmux-out-16114.log](https://github.com/user-attachments/files/17838577/tmux-out-16114.log)
  * [tmux-server-16114.log](https://github.com/user-attachments/files/17838578/tmux-server-16114.log)

**Comment by nicm** [comment]
Yes... the linked flag abuses the window's reference count so it will be set when the window is being held for any purpose, in this case it is probably because there is a pending notification. We probably need to do it a different way... does this fix it? [x.diff.txt](https://github.com/user-attachments/files/17842672/x.diff.txt)

**Comment by dalbertom** [comment]
Hi, thank you for sending the patch along. I wasn't able to build tmux@master on macOS - I likely don't have the right dependencies. I'll try on Linux over the weekend.

**Comment by dalbertom** [comment]
I was able to build from source on Linux but I cannot reproduce the issue there on master (3.5-114-gceaf9b74) or tag 3.5

**Comment by dalbertom** [comment]
I was finally able to build it on macOS and reproduce the issue on master (3.5-114-gceaf9b74) - after applying the patch you shared I no longer see the issue. Thank you!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
