### ISSUE TITLE
Missing documentation for escape sequence for command output start / -o option for next-prompt/previous-prompt

### ISSUE THREAD

**Issue by von** [tmux/tmux#4259]
This issue is purely about missing documentation and not a bug in the code.

With the `-o` option,` next-prompt` and `previous-prompt` are meant to jump to the start of the command output instead of the prompt.  However, while the 3.5a tmux man page provides the escape sequence to use to enable tmux to find the prompt (`\033]133;A\033\\`), it is missing documentation for the escape sequence to enable tmux to find the start of the command output. The appropriate escape sequence for the start of command output is: `\033]133;C\033\\\`.

It seems appropriate to include this information in the tmux man page in the same paragraph where the other escape sequence is given.

I figured this out from [a clue in another issue](https://github.com/tmux/tmux/issues/3734). It is not easy to figure out from [the source code](https://github.com/tmux/tmux/blob/bb94a5437dadda91d272f18f8157baac1330a8c5/input.c#L2929).

**Comment by nicm** [comment]
Do you want to suggest some text and where it should go?

**Comment by von** [comment]
Thank you for the suggestion. My understanding of troff isn't good enough to suggest a direct edit, but here is a proposed text addition to [tmux.1](https://github.com/tmux/tmux/blob/master/tmux.1#L2344), with the suggested sentence addition in bold at the end of the paragraph.

The ‘next-prompt’ and ‘previous-prompt’ move between shell prompts, but require
the shell to emit an escape sequence (\033]133;A\033\\) to tell tmux where the
prompts are located; if the shell does not do this, these commands will do
nothing.  The -o flag jumps to the beginning of the command output instead of
the shell prompt. **Finding the beginning of command output requires the shell to
emit a different escape sequence (\033]133;C\033\\\) to tell tmux where the output
begins; if the shell does not do this, these commands will do nothing..**

**Comment by nicm** [comment]
Looks good - applied to OpenBSD now with some minor tweaks, will be in GitHub later. Thanks!

**Comment by von** [comment]
Thank you
