### ISSUE TITLE
tmux 2.2+ in control mode (-C/-CC) breaks non-latin input

### ISSUE THREAD

**Issue by sideshowbarker** [tmux/tmux#426]
Steps to reproduce with 2.2 (or current master):

1.  `tmux new-session -s foo` to create a session.
2.  At the bash shell prompt or whatever, type a non-latin character, such as `º` (right-option+0 on OS X) and notice that it gets input and displayed correctly. Or use a Japanese IME to type `日本語` and notice that it gets input and displayed correctly.
3. In a different window, run `tmux -CC attach-session -d -t foo` to attach to the same session you created. Notice that the`º` and `日本語` you typed in in step 2 display correctly in the tmux window.
4. At the bash shell prompt or whatever, again try to type a non-latin character such as `º` and notice it gets input and displayed incorrectly as `Âº`. Or use a Japanese IME to try to type `日本語` and notice it gets input and displayed incorrectly as something like `æ¥æ¬èª`. (And if you hit return to see what the shell things those characters are, you get `-bash: $'æ\302\227¥æ\302\234¬èª\302\236'`.
5. In a new window, do `tmux attach-session -d -t foo` (with no `-CC`) to attach to the same session.
6. At the bash shell prompt or whatever, again type a non-latin character, such as `º` (right-option+0) but notice notice that unlike in the `-CC` window you created earlier, it gets input and displayed correctly. Or use a Japanese IME to type `日本語` and notice it also gets input and displayed correctly.

So `-CC` with tmux 2.2+ seems to cause it to misinterpret the character encoding of non-latin input text.

And try the same steps above with tmux 2.1 instead and you’ll see that unlike with tmux 2.2, in step 4, everything works as expected—that is, you get `º` instead of `Âº`, and `日本語` instead of `æ¥æ¬èª`.

**Comment by nicm** [comment]
Platform?

Does this help?

~~~~
diff --git a/client.c b/client.c
index 3203412..dc14918 100644
--- a/client.c
+++ b/client.c
@@ -316,6 +316,9 @@ client_main(struct event_base *base, int argc, char **argv, int flags,
 			fatal("tcgetattr failed");
 		cfmakeraw(&tio);
 		tio.c_iflag = ICRNL|IXANY;
+#ifdef IUTF8
+		tio.c_iflag |= IUTF8;
+#endif
 		tio.c_oflag = OPOST|ONLCR;
 #ifdef NOKERNINFO
 		tio.c_lflag = NOKERNINFO;

**Comment by sideshowbarker** [comment]
> Platform?

Linux x86_64 and OS X x86_64. I see the same behavior as described above when building from latest master. I also see the same when running from the Debian tmux 2.2-2 binary package。

> Does this help?
> [`ifdef IUTF8 tio.c_iflag |= IUTF8` patch to client.c]

No, I see the same behavior still even after applying that patch and rebuilding.

**Comment by nicm** [comment]
I can't reproduce this, whatever I type into a tmux session appears correctly whether or not I have it also attached to a -CC client.

Please kill tmux entirely, then use a build from Git master and start the initial session with:

tmux -f/dev/null -vvvv new

Then reproduce, but only with one character, such as º. Then kill tmux and send me the tmux-server-*.log.

**Comment by sideshowbarker** [comment]
> Please kill tmux entirely, then use a build from Git master and start the initial session with:
> 
> tmux -f/dev/null -vvvv new
> 
> Then reproduce, but only with one character, such as º. Then kill tmux and send me the tmux-server-*.log.

OK, did that and posted the log to:

 https://gist.github.com/sideshowbarker/8284404#file-tmux-server-62581-log

**Comment by sideshowbarker** [comment]
By the way, I’ve been trying `git bisect` but when I get to 531869bd92f0daff3cc3c3cc0ab273846f411dc8 `make` fails to run (because of the `.include <bsd.prog.mk>` the Makefile in the repo, and there’s no `autogen.sh` in that revision to re-create the build files from…)

**Comment by ThomasAdam** [comment]
On 26 May 2016 at 15:21, Michael[tm] Smith <notifications@github.com> wrote:

> By the way, I’ve been trying git bisect but when I get to 531869b
> <https://github.com/tmux/tmux/commit/531869bd92f0daff3cc3c3cc0ab273846f411dc8>
> make fails to run (because of the .include <bsd.prog.mk> the Makefile in
> the repo, and there’s no autogen.sh in that revision to re-create the
> build files from…)
>

This won't help you because of the merges that happen from OpenBSD.

-- Thomas Adam

**Comment by nicm** [comment]
You are doing this from the -CC client:

send-keys -t %0 0xc2 0xba

This is two keys. You need to give send-keys a single key as Unicode. For º, 0xba is enough:

send-keys -t %0 0xba

For something like 日, you would do:

send-keys -t %0 0x65e5

**Comment by nicm** [comment]
This was a side effect of making tmux understand UTF-8 keys. There is a bug, however: keys higher than FFFF cannot be entered.

**Comment by sideshowbarker** [comment]
> You are doing this from the -CC client:
> 
> send-keys -t %0 0xc2 0xba

OK, I guess in those terms the client I am testing this in is iTerm2 on OS X, and it sounds like you’re saying iTerm2 needs to change what it has been sending up to now in `send-keys`? (I mean, what it does that was working with tmux 2.1 at least.)

**Comment by nicm** [comment]
Ok you didn't mention iterm2 and I assumed that because you said it failed on Linux you were doing something else. Yes you need to get iterm2 to send Unicode characters instead of UTF-8 and it won't be able to send anything >0xffff until tmux 2.3 anyway.
