### ISSUE TITLE
Border Pane Style Colours not correct

### ISSUE THREAD

**Issue by lpuljic** [tmux/tmux#4261]
### Issue description

Hi, 
When setting colour for 
```
set-option -g pane-border-style "fg=#090909, bg=default"
set-option -g pane-active-border-style "fg=#090909, bg=default"
```
Color is returned as white on the pane lines  which should be more closer to black

<img width="1246" alt="Screenshot 2024-11-21 at 3 42 41 pm" src="https://github.com/user-attachments/assets/e2b63f31-3441-458a-9799-0f7e9f76ef22">

### Required information
Please provide the following information:

* tmux version (`tmux 3.5a`).
* Platform (`Darwin arm`).
* $TERM inside and outside of tmux (`screen-256color`).

**Comment by nicm** [comment]
Are you sure your terminal actually supports RGB colour? tmux is sending `\033[38;2;9;9;9m` which is correct:
![Screenshot 2024-11-21 at 08 21 17](https://github.com/user-attachments/assets/6286b51b-5d91-484d-bcd2-c65e1071bad5)
What does this show outside tmux `printf 'abc\033[38;2;9;9;9mdef\033[0mghi\n'`?

If you remove the `set -a terminal-features` line from your config and restart tmux, does it work (tmux will map the RGB colour to black)?

**Comment by nicm** [comment]
Actually, removing `RGB` won't work because your terminfo entry includes `setrgbf` and `setrgbb` which tmux will use (this is why the SGR sequence it sends has `;` instead of `:`). You will need to remove the `terminal-features` *and* add:
~~~~
set -as terminal-overrides 'xterm-ghostty:setrgbf@:setrgbb@`

**Comment by nicm** [comment]
Seems like a bug in your terminal to me, report it to them or try a different terminal.

**Comment by nicm** [comment]
Seems likely you made more changes to your config than just adding those two lines, or there is some strange dependency, because they will not affect the status line.

But this seems like a terminal problem, either your terminal does not support RGB colours or has a bug in its implementation.

**Comment by nicm** [comment]
You should always have `screen-256color` or (better) `tmux-256color` inside tmux, and the right `TERM` for your terminal outside tmux.
