### ISSUE TITLE
Allow styling for `choose-session`, `choose-buffer` etc.

### ISSUE THREAD

**Issue by voronind-com** [tmux/tmux#4264]
### Issue description

![image](https://github.com/user-attachments/assets/a11a3b82-1b6f-4ff6-a1e7-f766e38ada26)

Currently there's only one way to customize this part - via `mode_style` which also affects visual selection style. This makes it impossible to have one style for the visual selection and another for the choosers.

### Required information

Please provide the following information:

* tmux 3.5a

**Comment by nicm** [comment]
Yes, that is correct at the moment.

**Comment by nicm** [comment]
Oh was this meant to be a feature request...

I don't have any plans to do it but it would not be difficult. There is already `copy-mode-match-style` etc so you could add `copy-mode-selection-style`.

**Comment by nicm** [comment]
I have added this to the todo list and maybe someone will pick it up.

**Comment by voronind-com** [comment]
> I have added this to the todo list and maybe someone will pick it up.

Thanks.

**Comment by voronind-com** [comment]
@nicm Sorry, but where can I find said todo list? Just to track the issue. Thanks!

**Comment by kenlau46** [comment]
@voronind-com , see https://github.com/tmux/tmux/wiki/Contributing#small-things
Look at the bottom of the "small change" section, or search "4264"

**Comment by nicm** [comment]
I've fixed it now, thanks.

**Comment by nicm** [comment]
I added the additional styles for copy mode, please try this: [styles.diff.txt](https://github.com/user-attachments/files/17918144/styles.diff.txt)

**Comment by voronind-com** [comment]
> I added the additional styles for copy mode, please try this: [styles.diff.txt](https://github.com/user-attachments/files/17918144/styles.diff.txt)

I'll try it today and reply, many thanks!

**Comment by voronind-com** [comment]
@nicm Yay, it works great! Thank you very much for your amazing work. We love tmux.

https://github.com/user-attachments/assets/08042178-d415-4e47-880c-78a3d3f49f74

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
