### ISSUE TITLE
STILL OPEN : Tmux split window shortcuts

### ISSUE THREAD

**Issue by cruz94** [tmux/tmux#4265]
> No they are correct.

@nicm  - really??
C-b " - Split window vertically
result
![image](https://github.com/user-attachments/assets/6e8a162e-c2d6-4bdc-a496-13b3aad41c98)

C-b % - split window horizontally
result
![image](https://github.com/user-attachments/assets/1dd5fd75-d644-4707-9290-06dc5a702b21)

_Originally posted by @cruz94 in https://github.com/tmux/tmux/issues/4251#issuecomment-2487625938_

**Comment by nicm** [comment]
The panes are clearly laid out vertically (one above the other) in the first and horizontally in the second (one next to the other). This is correct. Please stop asking about this.
