### ISSUE TITLE
Dragging panes with mouse to reorder and change split mode

### ISSUE THREAD

**Issue by Radivarig** [tmux/tmux#4271]
There's a ticket https://github.com/tmux/tmux/issues/3503 which was closed as completed and locked but contains no further info. Was this implemented?

Otherwise it would be great to move the panes around by dragging the pane status and to convert split mode based on which edge of the target is closest to the mouse (up/down vertical, left/right horizontal).

**Comment by nicm** [comment]
No this has not been done so far.

**Comment by Radivarig** [comment]
@nicm I'm a bit confused why you'd close the original and this ticket and specifically as completed.
The original ticket says you've added it on TODO so keeping one ticket opened would be beneficial for tracking the progress.

**Comment by nicm** [comment]
I prefer not to keep issues open unless they are being worked on.
