### ISSUE TITLE
macOS paste with CMD+V stopped working in v3.5a

### ISSUE THREAD

**Issue by hovsater** [tmux/tmux#4273]
### Issue description

The issue is described in detail in https://github.com/tmux/tmux/issues/4175, but it was locked so I could not reuse it. While building from master makes this better, it's still not solved. Some of the pastes still emit the escape sequences and end up on a single line. In fact, it's more inconsistent now than before, as before all pastes would inline and emit escape sequences and now some work, some inline without escape sequences and some emit escape sequences.

Here's an example of be pasting the following contents three times in a row.

```
abc
def
123
456
```

The output:

```
abc
def
123
456
abcdef123456abc
def
123
456
^[[201~
```

As you can see, the first paste is correct. The second paste is inlined without escape sequences and the last paste in mult-line but with escape sequences being emitted.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `tmux next-3.6`
* Platform (`uname -sp`). `Darwin arm`
* $TERM inside and outside of tmux (`echo $TERM`). `tmux-256color` and `xterm-ghostty`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Show server log please with master.

**Comment by hovsater** [comment]
Here's the logs from a session doing repeated pastes inside `cat`.

[tmux-client-82961.log](https://github.com/user-attachments/files/17919946/tmux-client-82961.log)
[tmux-out-82963.log](https://github.com/user-attachments/files/17919947/tmux-out-82963.log)
[tmux-server-82963.log](https://github.com/user-attachments/files/17919948/tmux-server-82963.log)

**Comment by hovsater** [comment]
> Does this fix it? [paste.diff.txt](https://github.com/user-attachments/files/17932769/paste.diff.txt)

Hey, sorry for the late response. I've been out sick. I just tried your patch and it does indeed fix the problem. 🎉

**Comment by nicm** [comment]
Good stuff, applied to OpenBSD now, will be in GitHub later. Thanks!
