### ISSUE TITLE
Tmux locks while moving

### ISSUE THREAD

**Issue by loeffel-io** [tmux/tmux#4279]
### Issue description

tmux locks while moving in neovim for longer then 3 minutes

```
set -g lock-after-time 180
set -g lock-command "tmux detach"
```

### Required information

Please provide the following information:

tmux 3.5a
Darwin arm
alacritty

**Comment by exosyphon** [comment]
I am also having this issue in Neovim on MacOS 15.1.1 on Apple Silicon in Kitty

**Comment by nicm** [comment]
No logs.

**Comment by loeffel-io** [comment]
could belong to https://github.com/camgraff/telescope-tmux.nvim/issues/14
will keep you updated

**Comment by loeffel-io** [comment]
confirmation: the plugin was my issue
sorry for any inconveniences
