### ISSUE TITLE
Cursor changes sometimes to arrow cursor ↖ and does not return to text cursor Ꮖ

### ISSUE THREAD

**Issue by dilyanpalauzov** [tmux/tmux#4280]
When I work with tmux 3.5a I sometimes select text with the mouse and press Copy to put in the clipboard of the operating system.  The selected text is just highlighted by the terminal and the copy operation is also done by the terminal.  For this to work a text mouse cursor  Ꮖ is needed, which is the default mouse cursor.

Sometimes in some windows the cursor changes to arrow  ↖ and then I cannot select anymore text with the mouse.  If I change the tmux-window I can select text.  When I return to the window, which had switched to arrow mouse cursor ↖, I cannot select text, instead some random characters are printed, which look like CSI ecsape codes.  My terminal-features are
```
terminal-features[0] xterm*:clipboard:ccolour:cstyle:focus:title
terminal-features[1] screen*:title
terminal-features[2] rxvt*:ignorefkeys
```
* Why does tmux sometimes change the mouse cursor in some windows to arrow ↖, and how can I change it back to text cursor Ꮖ?

Of course, I first tried to find answers in the manual, but I could not.

**Comment by nicm** [comment]
tmux does not control the mouse cursor, this would be a terminal issue.

**Comment by dilyanpalauzov** [comment]
Yes, but when I change the window with `Ctlr+B n` then the cursor changes, when I return to the previous tmux window, the mouse cursor returns to the previous state.  Gnome Terminal does not know about tmux windows, so GNOME Terminal cannot intentionally change the mouse cursor, when tmux changes windows.

**Comment by nicm** [comment]
I can't help you with when and how the terminal decides to change the mouse pointer because tmux doesn't control it. GNOME Terminal must be deciding based on something tmux sends when it draws the window, but that is not something tmux asks it to do, you will need to ask the GNOME Terminal developers.
