### ISSUE TITLE
Keybinging issues in emacs

### ISSUE THREAD

**Issue by Ergus** [tmux/tmux#4285]
### Issue description

Since the last version I have been facing issues with emacs.

If I don't enable `extended-keys` then the `C-M-p` combination works normally, but `C--` (negative prefix) sends `C-_` (undo).
When I change some parameters (default-term, extended-key-formats, extended-keys) then `C-M-p` doesn't work. Emacs prints `2~` even when I do `C-h k` for emacs to show me what it received, I get this 2~ and not the help window. On the other hand the `C--` works correctly.

This behavior changes depending of the combination of the following parameters. I have tried all permutations

```config
set -g xterm-keys on
set -g extended-keys on  # send extended keys when application requests
#set -g extended-keys-format csi-u
#set -g extended-keys-format xterm
set -g default-terminal "tmux-256color"
#set -g default-terminal "screen-256color"
#set -g default-terminal "xterm-256color"
```

However, in general no combination allows to use `C--` and `C-M-p` at the same time.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.5a

* Platform (`uname -sp`).
Linux unknown (it is actually Arch linux up to date)

* $TERM inside and outside of tmux (`echo $TERM`).
inside: `tmux-256color` (I have tried screen and xterm as well
outside: foot

However on xterm+tmux I get the same problem.

* Logs from tmux (`tmux kill-server; tmux -vv new`).
```
set -g xterm-keys on
set -g extended-keys on  # send extended keys when application requests
set -g extended-keys-format xterm
set -g default-terminal "xterm-256color"
```

`C--` sends `C-_` 

[tmux-client-29387.log](https://github.com/user-attachments/files/17994032/tmux-client-29387.log)
[tmux-out-29389.log](https://github.com/user-attachments/files/17994033/tmux-out-29389.log)
[tmux-server-29389.log](https://github.com/user-attachments/files/17994034/tmux-server-29389.log)

```

set -g xterm-keys on
set -g extended-keys on  # send extended keys when application requests
set -g extended-keys-format xterm
set -g default-terminal "tmux-256color"
```
`C-M-p` sends `2~`

[tmux-client-31570.log](https://github.com/user-attachments/files/17994134/tmux-client-31570.log)
[tmux-out-31572.log](https://github.com/user-attachments/files/17994136/tmux-out-31572.log)
[tmux-server-31572.log](https://github.com/user-attachments/files/17994137/tmux-server-31572.log)

**Comment by nicm** [comment]
No logs.

**Comment by Ergus** [comment]
> No logs.

SOrry forgot yo upload them, check now please, but reopen this

**Comment by nicm** [comment]
Without `extended-keys`, `C--` and `C-_` are the same so without `extended-keys on` you will not be able to use both.

I don't see emacs requesting extended keys in your log, so tmux will send `C-_` for `C--`.

You will need to configure emacs to do this (mine does it by default so perhaps your emacs is too old).

**Comment by Ergus** [comment]
> Without `extended-keys`, `C--` and `C-_` are the same so without `extended-keys on` you will not be able to use both.
> 
> I don't see emacs requesting extended keys in your log, so tmux will send `C-_` for `C--`.
> 
> You will need to configure emacs to do this (mine does it by default so perhaps your emacs is too old).

Hi Nicolas:

My emacs is actually a build master, so it can't be newer.

However, see that in the second logs the `C--` works as expected, But the broken one is `C-M-p`. So emacs may be requesting the extended keys somehow.

**Comment by nicm** [comment]
You are changing too many things at a time.

In the first log, you have TERM set incorrectly to `xterm-256color` rather than `tmux-256color`, so emacs is not turning on extended keys, although I don't know why.

In the second log, you aren't setting `terminal-features`, so tmux will not turn on extended keys because it is not aware that the terminal supports them.

Please test with a .tmux.conf containing nothing but this and then show me the server log. Make sure you press all three problem keys.
~~~~
set -s extended-keys on
set -s default-terminal "tmux-256color"
set -as terminal-features 'foot:extkeys'
~~~~

**Comment by Ergus** [comment]
> set -s extended-keys on
> set -s default-terminal "tmux-256color"
> set -as terminal-features 'foot:extkeys'

Hi Nicolas:

The `set -as terminal-features 'foot:extkeys'` I found around, but I was not aware that it was enabled in the first case. 

With the config you sent, the `C--` works, but the `C-M-p` not, attached log:

[tmux-server-71873.log](https://github.com/user-attachments/files/17996436/tmux-server-71873.log)

**Comment by nicm** [comment]
For `C-M-p` tmux is sending what it receives:
~~~~
1733244961.962929 /dev/pts/3: read 11 bytes (already 0)
1733244961.962983 /dev/pts/3: keys are 11 (\033[27;7;112~)
1733244961.963007 /dev/pts/3: extended key \033[27;7;112~ is 8300000000070 (C-M-p[I])
1733244961.963013 /dev/pts/3: complete key \033[27;7;112~ 0x8300000000070
...
1733244961.963101 writing key 0x8300000000070 (C-M-p[I]) to %0
1733244961.963109 input_key_mode1: key in 8300000000070
1733244961.963115 input_key_extended: \033[27;7;112~
~~~~
emacs only asks for mode 1, so perhaps it expects `^[^P`... 

Does this fix it?
~~~~
--- a/input-keys.c
+++ b/input-keys.c
@@ -543,7 +543,7 @@ input_key_mode1(struct bufferevent *bev, key_code key)
        log_debug("%s: key in %llx", __func__, key);

        /* A regular or shifted key + Meta. */
-       if ((key & (KEYC_CTRL | KEYC_META)) == KEYC_META)
+       if (((key & KEYC_MASK_MODIFIERS) & (KEYC_CTRL|KEYC_META)) == KEYC_META)
                return (input_key_vt10x(bev, key));

        /*

**Comment by Ergus** [comment]
> For `C-M-p` tmux is sending what it receives:
> 
> ```
> 1733244961.962929 /dev/pts/3: read 11 bytes (already 0)
> 1733244961.962983 /dev/pts/3: keys are 11 (\033[27;7;112~)
> 1733244961.963007 /dev/pts/3: extended key \033[27;7;112~ is 8300000000070 (C-M-p[I])
> 1733244961.963013 /dev/pts/3: complete key \033[27;7;112~ 0x8300000000070
> ...
> 1733244961.963101 writing key 0x8300000000070 (C-M-p[I]) to %0
> 1733244961.963109 input_key_mode1: key in 8300000000070
> 1733244961.963115 input_key_extended: \033[27;7;112~
> ```
> 
> emacs only asks for mode 1, so perhaps it expects `^[^P`...
> 

Hi Nicolas:

I am not an expert on this, but if you think this is an emacs issue (or something that can be improved) I can comment in the emacs mailing list. 

I already asked about something similar to this in emacs-devel mailing list two months ago:

https://lists.gnu.org/archive/html/emacs-devel/2024-10/msg00172.html

But not a real solution for this came out. Do you think that emacs may ask for a mode different than 1?


> Does this fix it?
> 
> ```
> --- a/input-keys.c
> +++ b/input-keys.c
> @@ -543,7 +543,7 @@ input_key_mode1(struct bufferevent *bev, key_code key)
>         log_debug("%s: key in %llx", __func__, key);
> 
>         /* A regular or shifted key + Meta. */
> -       if ((key & (KEYC_CTRL | KEYC_META)) == KEYC_META)
> +       if (((key & KEYC_MASK_MODIFIERS) & (KEYC_CTRL|KEYC_META)) == KEYC_META)
>                 return (input_key_vt10x(bev, key));
> 
>         /*
> ```

Yes, this seems to fix the problem at least for the bindings I tested (`C-M-p`, `C-M-n` and `C--`).

**Comment by Ergus** [comment]
My apologies, apparently the change is not even needed, I updated and built the git master branch again  and it seems to be working correctly any way (without the change). IIRC I build master the last week, so is there some change since then that could fix this?

Very thanks for your help,
Ergus

**Comment by nicm** [comment]
OK so long as you are sure, because as far as I remember there have been no changes in the last few weeks would have fixed this.
