### ISSUE TITLE
 Allow automatic light/dark mode detection from applications running within tmux (CSI 2031)

### ISSUE THREAD

**Issue by jonathanslenders** [tmux/tmux#4286]
Several terminal emulators now allow for automatic switching between light and dark themes, and allow applications running within the terminal to subscribe to theme changes. Automatic switching off all applications together is important to prevent situations where bright white and black windows end up side by side on a screen.

It would be great if tmux would understand CSI 2031, so that it could proxy these requests from applications to the outer terminal.

A few other terminal emulators and applications have implemented a simple protocol for dark/light mode detection and update notifications. For documentation, see: https://github.com/contour-terminal/contour/blob/f3c3334aa5c861348c5bbe8ffe572c872eef2e08/docs/vt-extensions/color-palette-update-notifications.md

Terminal emulators that are implementing CSI 2031 are:
- Ghostty
- Contour

Applications that take advantage of CSI 2031 are:
- Neovim: https://github.com/neovim/neovim/pull/31350
- (probably others.)

The request here is to make sure that applications running in tmux can query the current theme (light/dark), but can also use CSI 2031 to subscribe to theme updates.

One edge case that would complicate things for tmux is a situation where a single window is attached in two different terminals, one with a light theme and one with a dark theme. In that case tmux would have to choose what to present to the applications.

**Comment by nicm** [comment]
Same as https://github.com/tmux/tmux/issues/4269.

**Comment by nicm** [comment]
This feature is a very good idea but I don't have time to work on it and I don't think it is pressing while realistically only one terminal and one application supports it. If someone writes it I will review it...

**Comment by jonathanslenders** [comment]
Of course! Thank you.
