### ISSUE TITLE
Alt+Backspace broken

### ISSUE THREAD

**Issue by SchweinDeBurg** [tmux/tmux#4290]
After commit 6d792e41236dbcbd90f21fe8b2f25eabbc66e77f pressing `Alt+Backspace` deletes only one character and not the word. It is very painfully for me. :-)

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/user-attachments/files/18019808/x.diff.txt)

**Comment by SchweinDeBurg** [comment]
@nicm Thank You very much, this patch got rid of my pain.

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
