### ISSUE TITLE
VirtualBox, ZSH, tmux copy mode issue

### ISSUE THREAD

**Issue by user11-11** [tmux/tmux#4291]
### Discussed in https://github.com/orgs/tmux/discussions/4282

<div type='discussions-op-text'>

<sup>Originally posted by **user11-11** November 29, 2024</sup>
I'm running Windows 11 with VirtualBox 7.0.14. In a VirtualBox VM I'm running Debian with ZSH, using tmux with this option set in tmux.conf:

set-window-option -g mode-keys vi

When I enter copy/edit mode, I need to press Ctrl+Spacebar to start highlighting text instead of just Spacebar. After I highlight the text, I cannot press Enter or any other keystroke to copy the highlighted text to the buffer.

I've tried multiple options:

1) mouse copy to buffer
2) tmux plugin manager with tmux-yank
3) highlighting the text then running "tmux showb | xclip -i -selection clipboard"
4) capture-pane
5) setting capture keys in tmux.conf (binding y as the copy to buffer key)

I'm not sure what is needed to get this to work.</div>

**Comment by nicm** [comment]
No logs.

**Comment by user11-11** [comment]
Sorry about that. Attached are logs from a session today where I tried to copy and paste. If you need any more info please let me know.

[tmux-troubleshooting.tar.gz](https://github.com/user-attachments/files/18267799/tmux-troubleshooting.tar.gz)

**Comment by nicm** [comment]
Show full server log please from starting tmux, there is not enough here to show if the option is actually being set.

**Comment by user11-11** [comment]
I appreciate your patience. Attached are a new set of logs.
[tmux-troubleshooting.tar.gz](https://github.com/user-attachments/files/18390030/tmux-troubleshooting.tar.gz)

**Comment by nicm** [comment]
It looks like your config is missing a `"` after `%%` because the `set-window-option -g mode-keys` is being treated as part of an argument to `command-prompt`:
~~~~
1736696778.763758 cmd_parse_build_commands: set-option -g prefix C-a ;; bind-key C-a send-prefix ;; unbind-key C-b ;; set-option -g history-limit 50000 ;; set-option -g allow-rename off ;; bind-key j command-prompt -p "join pane from:" "join-pane  -s  '%%'" ;; bind-key s command-prompt -p "send pane to:     join-pane" -t "%%\\n\\n\\nset-window-option -g mode-keys vi\\n\\n\\n\\n\\n\\n\\n\\n\\nset -g mouse on\\n"
~~~~

**Comment by user11-11** [comment]
Thanks. I added the additional double quote. Attached is another set of logs.

After fixing the tmux.conf settings, I tried to copy the contents to the buffer but pressing enter doesn't copy the selected text.

I enter a tmux session, enter vi search mode, press ctrl+spacebar to start highlighting, and then after that I am not able to copy the selection or paste it. I'm not sure if this is because I'm running linux through virtualbox.
[tmux-troubleshooting (1).tar.gz](https://github.com/user-attachments/files/18390494/tmux-troubleshooting.1.tar.gz)

**Comment by nicm** [comment]
This log looks the same to me, `mode-keys` is still not being set because it is seen as part of a previous string.

**Comment by user11-11** [comment]
I was mistakenly running tmux as root. Instead I ran "sudo -E tmux new -s mytmux" as a non-root user, using the original bind-key lines:

bind-key j command-prompt -p "join pane from:"  "join-pane  -s  '%%'"
bind-key s command-prompt -p "send pane to:"     "join-pane  -t  '%%'"

# Search Mode VI (default is emac)
set-window-option -g mode-keys vi

I am able to use just spacebar now to copy text into the buffer.

I've attached another set of logs. I don't see the same invalid references as the original logs. Does anything look wrong now?
[tmux-server-4872.log](https://github.com/user-attachments/files/18391211/tmux-server-4872.log)

**Comment by nicm** [comment]
Looks OK to me now.
