### ISSUE TITLE
Resizing broken after update: su - user -c tmux new

### ISSUE THREAD

**Issue by Jipok** [tmux/tmux#4292]
After upgrading to 3.5, tmux stopped resizing automatically along with the terminal. I don't know what version of tmux was before, I haven't updated the system for about six months.

If I first log in as a user and then `tmux new`, everything is fine. I analyzed the environment variables and it seems there is nothing that could affect it. In any case, `TERM` is the same.

https://github.com/user-attachments/assets/8fccc9d7-0c50-4cf2-8a75-106bb3f2cc9c

I don't have any tmux config.

**Comment by nicm** [comment]
No logs.

**Comment by Jipok** [comment]
When using `su - pdf -c 'tmux -v new'` only the client log appears in the user folder. I couldn't find the server log.
https://gist.github.com/Jipok/1785535c41037300a5d545a425f222d5

**Comment by nicm** [comment]
You probably didn't kill tmux entirely first.

**Comment by Jipok** [comment]
Client: https://gist.github.com/Jipok/1cb1383fd1ab93323a99b42421723bac
Server: https://gist.github.com/Jipok/ff403b53e56b76c8468d52b31fb9b8b7

I just did:
1) `su - pdf -c 'tmux -v new'`
2) Resized terminal, which broke the tmux status line
3) Exited via ctrl-d

**Comment by nicm** [comment]
Seems like the tmux client is not being sent SIGWINCH. I expect this is to do with ownership of the pty. Does it work if you su first and then run tmux?

**Comment by Jipok** [comment]
Yes, this order works:
1) `su - pdf`
2) `tmux new`

But the old command also worked before the update.

**Comment by nicm** [comment]
Are you sure you only updated tmux and nothing else? No kernel or su update? What if you try some older tmux versions? Does it go back to working?

**Comment by Jipok** [comment]
I'm not messing around, this is a really important feature for me. I use the following "alias":
https://github.com/Jipok/Cute-bash/blob/9daad41698b492979edbe4fe3593a344625959ea/.bashrc#L64C1-L101C2

I got used to it very much. And now it doesn't work correctly. And I can't execute commands sequentially from the script.

**Comment by Jipok** [comment]
> Are you sure you only updated tmux and nothing else? No kernel or su update?

Of course I completely updated the system. And I don't know what versions were there before. I don't quite understand how the kernel version can affect tmux.

**Comment by nicm** [comment]
I don't know why you are taking this attitude because trying some older tmux versions to narrow down when it was broken is a perfectly reasonable suggestion.

Of course the kernel version can affect tmux, it affects everything, what else do you think tells tmux when the terminal resizes...

**Comment by Jipok** [comment]
Oh. It's really not tmux. I tried older versions up to 3.3a and it still didn't work. I tried a clean system on a vps, the problem persisted.
And then I tried changing the terminal to wezterm and everything started working for me. I don't understand why Alacritty 0.14.0 doesn't work if I use exactly `su - user -c 'tmux new'`.

**Comment by nicm** [comment]
OK a guess would be it is something to do with how alacritty sets up the pty, which means SIGWINCH is not being delivered to tmux. You'll need to ask the alacritty developers.
