### ISSUE TITLE
set -g pane-border-status "off" doesn't work

### ISSUE THREAD

**Issue by MrNavaStar** [tmux/tmux#4294]
### Issue description

```
# Does Not Work
set -g pane-border-status "off"
# Does Work
set -g pane-border-status "bottom"
```
Setting pane-border-status to off should hide pane borders, correct? If I am misunderstanding this feature please let me know.

### Required information

Please provide the following information:

* tmux version (tmux 3.5a).
* Platform (Linux unknown).
* $TERM inside and outside of tmux (outside: xterm-256color, inside: tmux-256color).

**Comment by clarkwang** [comment]
It turns off "pane status", not "pane border".

**Comment by MrNavaStar** [comment]
Ah I see, my bad
