### ISSUE TITLE
Code block works in if-shell but run-shell

### ISSUE THREAD

**Issue by keelung-yang** [tmux/tmux#4296]
Hi,
Why code block is supported by `if-shell` but `run-shell` ?

If I use following `run-shell` block instead of "", I cannot use mouse to select pane. 
So TMUX_VERSION isn't set but no error reported.

```shell
# The mouse works
run-shell "tmux setenv -g TMUX_VERSION $(tmux -V | cut -c 6- | sed -E 's/[a-z]+//g')"

# The mouse doesn't work
# run-shell {
#     tmux setenv -g TMUX_VERSION $(tmux -V | cut -c 6- | sed -E 's/[a-z]+//g')
# }

# In version 2.1 "mouse" replaced the previous 4 mouse options
if-shell -b '[ "$(echo "$TMUX_VERSION >= 2.1" | bc)" = 1 ]' {
    set -g mouse on
}
```
TMux 3.4 on Ubunt 24.10 x64
I also checked change log but found nothing useful info.

**Comment by nicm** [comment]
You can't put shell commands inside {}, only tmux commands.

**Comment by keelung-yang** [comment]
> You can't put shell commands inside {}, only tmux commands.

It's my mistake.
But I got `tmux.conf:6: command set-environment: too many arguments (need at most 2)` after removing `tmux` in code block.

Seems `setenv` cannot parse the `$()`  even in a run-shell block. If yes, then if-shell cannot too, I guess.

tmux.conf
```
# The mouse works
# run-shell "tmux setenv -g TMUX_VERSION $(tmux -V | cut -c 6- | sed 's/[^0-9.]//g')"

# The mouse doesn't work
run-shell {
    setenv -g TMUX_VERSION $(tmux -V | cut -c 6- | sed 's/[^0-9.]//g')
}
```

**Comment by nicm** [comment]
$() is shell syntax not tmux.

**Comment by nicm** [comment]
So where are you ""s around $()?

**Comment by nicm** [comment]
You can't put shell syntax in {}s and run-shell does not accept a tmux command without -C, only a shell command. You need to use "s around shell commands:
~~~~
run-shell "tmux setenv -g TMUX_VERSION $(tmux -V | cut -c 6- | sed 's/[^0-9.]//g')"
~~~~

**Comment by keelung-yang** [comment]
OK. Thanks! Now closing this bug.
