### ISSUE TITLE
bind-key ^@ with extended keys

### ISSUE THREAD

**Issue by enometh** [tmux/tmux#4297]
Version information: tmux next-3.6 (ae8f220) on Linux amdd64
Example Config:
```
set-window-option -g remain-on-exit on
bind-key  ^@ respawn-pane
```
After commit ceda0a68ae0 the above configuration 
does not work: ^@ (C-b C-@) is not
handled by tmux and  (in this case does not re-spawn a dead pane)

show-options -s:
```
extended-keys off   
extended-keys-format xterm  
```
but trying other values for these options makes no difference

is C-b C-@ expected to be usable as a valid keybinding?

**Comment by nicm** [comment]
Show server log please.

**Comment by enometh** [comment]
(I was hesitant because the log file is huge and includes environment information, I'm trying to attach a zipped file of the client and server logs and the history file of commands executed)

**Comment by nicm** [comment]
It should not be huge if you only have the config above, just gzip the server log.

**Comment by enometh** [comment]
[debug-tmux-extended-2024-12-18.zip](https://github.com/user-attachments/files/18184919/debug-tmux-extended-2024-12-18.zip)
This is with tmux commit off ae8f2208c
The same sequence of steps:
C-d (exit the shell)
C-b C-@ (respawn the pane)
worked on my previous checkout off tmux 963e824f5.

**Comment by nicm** [comment]
What if you change the binding to `C-Space`?

**Comment by enometh** [comment]
Yes, C-Space (i.e. bind-key "^ ") works, and it worked before the "extended keys" patches, so operationally there isn't' a problem.
Is the change in behaviour,  i.e. no longer being able to bind "^@" ,
explained correctly by the introduced patches? (Thanks)

**Comment by nicm** [comment]
Yes this is expected.

**Comment by enometh** [comment]
Any pointers on where the "extended keys" behaviour is documented so I can understand what actually changed and why my old key binding was impacted?

**Comment by enometh** [comment]
Can you please delete  server.log  uploaded on this issue?   It is not relevant
to the diagnosis or the fix of the issue, and I don't want that information (which I negelected to scrub)
in the public domain. There was no need for it to have been requested by you or to have been supplied by me.

**Comment by nicm** [comment]
Deleted now.
