### ISSUE TITLE
There is a memory leak defect at line 1048 in the file /tmux/mode-tree.c.

### ISSUE THREAD

**Issue by LuMingYinDetect** [tmux/tmux#4298]
A pointer variable named mtm is defined at line 1015 in the file /tmux/mode-tree.c. This variable is allocated a new dynamic memory area through the xmalloc function at line 1036. When the if statement at line 1046 returns true, only the dynamic memory area pointed to by another pointer variable menu is freed at line 1048, while the dynamic memory area pointed to by mtm is not freed, resulting in a memory leak defect, as shown in the diagram below:
https://github.com/LuMingYinDetect/tmux_defects/blob/main/tmux_9.png

**Comment by nicm** [comment]
Should be fixed once GitHub syncs up, thanks!
