### ISSUE TITLE
send-keys -R causes garbage unicode output

### ISSUE THREAD

**Issue by alexdavid** [tmux/tmux#43]
Clean install of tmux 2.0 with no config causes strange output after running `tmux send-keys -R`

```shell
~ > ls
Applications   Documents      Library        Pictures
Desktop        Downloads      Movies         Public
Development    Dropbox        Music          VirtualBox VMs
~ > tmux send-keys -R
· > ┌⎽   # <--- this was ls
A⎻⎻┌☃c▒├☃⎺┼⎽   D⎺c┤└e┼├⎽      L☃b⎼▒⎼≤        P☃c├┤⎼e⎽
De⎽┐├⎺⎻        D⎺┬┼┌⎺▒d⎽      M⎺┴☃e⎽         P┤b┌☃c
De┴e┌⎺⎻└e┼├    D⎼⎺⎻b⎺│        M┤⎽☃c          V☃⎼├┤▒┌B⎺│ VM⎽
```

**Comment by nicm** [comment]
That's not Unicode, looks like it is ending up with ACS turned on. What do you have in your prompt? Are you running "tmux send-keys -R" inside or outside tmux?

**Comment by alexdavid** [comment]
I'm running `tmux send-keys -R` inside tmux

**Comment by nicm** [comment]
What's in your prompt?

**Comment by alexdavid** [comment]
Thanks for your time so far!

What do you mean by my prompt?

**Comment by alexdavid** [comment]
This seems to only happen with fish shell, but any prompt causes it

**Comment by nicm** [comment]
Can you run script inside tmux, then do the send-keys -R, then exit script and send me the typescript file?

**Comment by alexdavid** [comment]
Here you go: https://gist.github.com/47d08bfb60aee175978e.git

There is a lot of output because of fish shell's auto-complete. Unfortunately I can't reproduce in any other shell

**Comment by nicm** [comment]
Did you build tmux yourself? Are you sure it is unmodified?

send-keys -R should clear the screen, does it do that?

This works fine for me if I install fish.

**Comment by alexdavid** [comment]
I didn't build tmux myself. I'll try that next. I installed it from homebrew which uses this to build https://github.com/Homebrew/homebrew/blob/master/Library/Formula/tmux.rb

`send-keys -R` does clear the screen, but output is messed up for the remainder of the session

**Comment by nicm** [comment]
Actually I think I have spotted the problem, can you try this please: http://pastebin.ca/raw/3060027

**Comment by alexdavid** [comment]
That patch fixes the issue. Thanks!

**Comment by nicm** [comment]
Applied, thanks
