### ISSUE TITLE
Solutions for scrollback buffer blocking the application

### ISSUE THREAD

**Issue by raedah** [tmux/tmux#431]
When in a windows scrollback buffer, the application becomes blocked. I found other people online having the same experience.

http://unix.stackexchange.com/questions/242449/how-can-i-prevent-tmux-from-blocking-when-i-scroll-up
http://unix.stackexchange.com/questions/82850/how-can-i-scroll-screen-or-tmux-buffer-without-pausing-the-application

What solutions are available to not have the application blocked? This is especially a problem for server daemons. If its not possible to not block the application, the next best option would be to have an option to autoexit the scrollback buffer after x seconds of inactivity.

**Comment by nicm** [comment]
Yes this is unfortunate. Scrolling on any output would be annoying, and
updating on output would be both annoying for the user and complicated to
implement. A timer would be relatively easy, perhaps a combination of both
- exit copy mode on output, after an idle timer expires.

**Comment by nicm** [comment]
The reason this happens is that copy mode turns off the event processing of the pane so it can copy from it if necessary. This also makes it impossible for us to tell whether there is any output waiting, so the only option is a pure timer.

Please try this which will exit a mode after 180 seconds if there is no user input, I made it apply to all modes even though only copy mode is a problem: [x.txt](https://github.com/tmux/tmux/files/291232/x.txt)

**Comment by raedah** [comment]
thank you. i am not able to patch and compile at the moment, but if I am able to do that later I will. Much appreciated.

**Comment by raedah** [comment]
One question I am having is why is it that not all applications are blocked?  Rsync for example, seems to continue in the background with no issue.

**Comment by nicm** [comment]
Applied with the addition of ioctl(FIONREAD) to only exit if there is actual pending output.

**Comment by nicm** [comment]
rsync probably uses nonblocking I/O to the terminal and ignores EAGAIN.

**Comment by schlichtanders** [comment]
is there a solution to this problem which can be applied to an already installed TMux version? Like a tmuxconf setting?

I just hit this problem, realising that the reason for my program blocking for 14 hours was tmux and not my program...
worse of all it seemed to have entered copy-mode by itself (the pause in the logs started when I was already enjoying the evening with friends)

**Comment by warrenfalk** [comment]
We've had this happen when not even in copy mode.  It might be what @schlichtanders was experiencing.

It occurs when an ssh user will have his network interrupted or his computer panic or blue-screen without properly detaching from tmux.  This results in tmux showing his client still attached even though he is definitely no longer connected.  Eventually some buffer must fill up and the process hangs.  From another attached client, the defunct client (which isn't really there) can be detached resulting in immediate unblocking of the process.

Hope that helps someone.

**Comment by Chealer** [comment]
This was apparently solved by [commit bee3e3e28d04a237b1013b1dd3d36cddcd326891](https://github.com/tmux/tmux/commit/bee3e3e28d04a237b1013b1dd3d36cddcd326891), for tmux 2.3 (2019-09-26).

**Comment by Chealer** [comment]
For those still using buggy tmux versions, be aware that **detaching blocking sessions does not suffice to avoid the issue**. If a session is detached, copy mode must be left before.
