### ISSUE TITLE
Enable Hyperlinks without a command-line param

### ISSUE THREAD

**Issue by bjackman** [tmux/tmux#4310]
Basically, [this SO question](https://stackoverflow.com/questions/79013973/enable-hyperlinks-in-tmux-config-file).

I _think_ it's currently only possible to enable hyperlinks by setting a command-line flag. I might be wrong about this, in which case this issue can just be considered a request for documentation.

(Not including extra details since IIUC this is totally orthogonal to platform details/version etc, please let me know if I'm wrong about that too).

**Comment by nicm** [comment]
Put it in `terminal-features` in .tmux.conf

**Comment by bjackman** [comment]
Ah OK if that is expected to work then I will drop extra details:

```
❯❯ uname -sp && tmux -V && echo $TERM

Linux x86_64
tmux 3.4
xterm-256color

~/src/limmat (master↑5|✚1)  
❯❯ cat ~/.tmux.conf
set -g mouse on
set-window-option -g xterm-keys on
set-option -g history-limit 50000

bind-key h select-pane -L
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D

set -g default-terminal "xterm-256color"

set -as terminal-features ",gnome*:hyperlinks"

❯❯ TERM=screen-256color tmux attach # No hyperlinks
```

it works great if I use `tmux -T hyperlinks attach` instead. I am using `gnome-terminal`. 

I strongly suspect that I have the `terminal-features` command wrong in my config but it's not clear exactly how.

**Comment by nicm** [comment]
Show logs please.

**Comment by nicm** [comment]
Actually:
~~~~
TERM=screen-256color tmux attach
~~~~
How is that going to match `gnome`?

**Comment by nicm** [comment]
You have to restart tmux entirely if you change .tmux.conf.

**Comment by bjackman** [comment]
OK thanks, I think I just didn't even realise there was still a server running in my case. I'll update the SO question
