### ISSUE TITLE
Show full timestamp on scrollback

### ISSUE THREAD

**Issue by 0xShkk** [tmux/tmux#4311]
I would love to have the full timestamp shown (including the actual time) when scrolling back past the present day. Currently, when scrolling over the current day, only the date is displayed but not the time.

**Comment by nicm** [comment]
You can do this in master, there is an option to control the format of what is shown.

**Comment by 0xShkk** [comment]
Based on this reddit thread, the format is hardcoded?

[https://www.reddit.com/r/tmux/comments/1cb2lfl/tmux_scrollback_buffer_timestamp_how_to_always/](https://www.reddit.com/r/tmux/comments/1cb2lfl/tmux_scrollback_buffer_timestamp_how_to_always/)

**Comment by nicm** [comment]
OK well you can believe them or believe me, it's up to you.

**Comment by 0xShkk** [comment]
:D

Did not mean to offend you. Where exactly can I change the format than without building tmux myself?

**Comment by nicm** [comment]
You will need to build tmux yourself from master, then you can use the `copy-mode-position-format` option https://man.openbsd.org/OpenBSD-current/man1/tmux.1#copy-mode-position-format.

**Comment by 0xShkk** [comment]
So you are saying that this option is available at current master but this version is not yet pushed to package repositories.

Did I get you right?

**Comment by nicm** [comment]
Yes that's right.
