### ISSUE TITLE
Command prompt appears in first status bar instead of the second

### ISSUE THREAD

**Issue by cyanghxst** [tmux/tmux#4315]
## Description

I've set a blank line between the prompt and tmux status bar using a multi-line status bar and the snippet from #1886. While the blank line appears as expected, when I open the command prompt using `prefix + :`,  the command input appears in the blank line instead of temporarily replacing the second status line.

## Actual Behavior

The command prompt appears in the blank line, as shown in this [screenshot](https://imgur.com/a/chgwYuJ)

## Expected Behavior

When the command prompt is opened, I'd like it to appear below the blank line, as shown in this [screenshot](https://imgur.com/a/l67M92b)

## My tmux status line configuration

```
# Statusbar color
set-option -g status-style "bg=default"
set-option -g status-style "fg=#414868"

# Message text
set-option -g message-style "bg=default"
set-option -g message-style "fg=white"

# Position and indicators
set-option -g status-left ""
set-option -g status-right ""
setw -g window-status-format "#{pane_current_command}"
setw -g window-status-current-format "#{pane_current_command}"
set-window-option -g window-status-current-style "fg=#c0caf5"

# Add blank line between status bar and prompt
if -F '#{!=:#{status},2}' {
    set -Fg 'status-format[1]' '#{status-format[0]}'
    set -g 'status-format[0]' ''
    set -g status 2
}
```

## Environment

- **Version**: tmux 3.5a
- **Platform**: macOS Sequoia  15.1.1 arm64
- **$TERM**: tmux-256color (inside), xterm-kitty (outside)

**Comment by nicm** [comment]
This is currently not supported and has been on the todo list for a while (https://github.com/tmux/tmux/issues/3114).
