### ISSUE TITLE
join-pane -t {previous} doesn't work

### ISSUE THREAD

**Issue by bergman** [tmux/tmux#433]
Start a new session, create a second window, run from the second window: `join-pane -t {previous}` results in
> Can't join a pane to its own window

On the other hand, running `join-pane -t {last}` works as expected.

How can I make the first command work, to join a pane to the left of the active window?

**Comment by nicm** [comment]
{previous} is not the window to the left, you want -t:-1

**Comment by bergman** [comment]
Ah, didn't realise the difference between window and pane in that command and how the colon works. Thanks so much!

This seems to work as well: `join-pane -t:{previous}`

Closing!
