### ISSUE TITLE
Per-pane title bar

### ISSUE THREAD

**Issue by kevmitch** [tmux/tmux#436]
It seems that tmux doesn't currently support displaying a title within each pane. It has only a single bottom bar that displays the currently active title. As I prefer to keep my prompt extermely minimal, this makes it difficult to tell at a glance where each pane is at.

It looks like there are some [old patches](https://github.com/jonathanslenders/tmux) for this that mostly seem to behave "correctly" (i.e., they use the dividing line between panes so that no additional screen space is used except for the top-most pane). Unfortunatley, it seems the patches have been abandoned in favour of [pytmux](https://github.com/jonathanslenders/pymux).

I would rather not use pytmux because a) a terminal reemulator in python seems kind of insane, and b) it seems to have even more keyboard / modifier issues than tmux (probably related to point a).

Anyway I was thinking of cleaning up those patches so that they could apply to the current tmux. Would this kind of thing be accepted as a pull request?

**Comment by nicm** [comment]
I thought I had done this already.

**Comment by kevmitch** [comment]
Ah, indeed `pane-border-status` seems to do what I want. In fact it has better defaults than the above patch becuase it actually shows the same title an xterm would.

Sorry I missed this. Probably because it wasn't documented. So maybe I'll submit a pull request documenting it?

**Comment by kevmitch** [comment]
or never, mind it is documented, I was just reading an old man page form v2.2
