### ISSUE TITLE
Rendering of unselected cells broken on master

### ISSUE THREAD

**Issue by osandov** [tmux/tmux#437]
To reproduce, enter copy mode, move the cursor a few characters to the right, then back to the left. The unselected characters are still rendered as if they were selected.

I narrowed this down to commit 36ab4c7c49d8. The problem is that the cell in the grid view is the same whether it is selected or not, so this comparison is true after a cell has been unselected:

    skip = (memcmp(&now_gc, gc, sizeof now_gc) == 0);

**Comment by nicm** [comment]
I think that is just a guess, because if you look a few lines further,
skip is not used if the cell is selected.

In any case, I can't reproduce this.

**Comment by osandov** [comment]
Right, but the problem is when the cell _was_ selected and is no longer selected. I'll try to do a screencap or something.

**Comment by osandov** [comment]
Here is the behavior on tmux 2.2:
![tmux 2.2](https://cloud.githubusercontent.com/assets/3682206/15794162/bb50b364-299d-11e6-8a67-56bb0ca881eb.gif)
And here is the behavior on the master branch:
![master](https://cloud.githubusercontent.com/assets/3682206/15794174/d8136d66-299d-11e6-9a5e-e7debff37cc0.gif)

**Comment by nicm** [comment]
I still can't reproduce this, but I can see how it might happen. Please try this: 
[x.txt](https://github.com/tmux/tmux/files/298718/x.txt)

**Comment by osandov** [comment]
Weird, it's 100% reproducible for me. Your patch fixes it for me, though. Thanks!

**Comment by nicm** [comment]
Applied now, thanks.
