### ISSUE TITLE
Include systemd service to tackle changes in systemd; KillUserProcesses=yes

### ISSUE THREAD

**Issue by moviuro** [tmux/tmux#438]
Hi,

After hearing of systemd v230 killing user processes after logout (tmux, among others), I thought upstream tmux would be interested in a systemd service file that could be used for users so that they can have their tmux session started at boot and not killed upon logout. (see the [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825394))

The file of interest is here: https://github.com/moviuro/etc-systemd/blob/master/system/tmux.service . See also the [archlinux wiki page](https://wiki.archlinux.org/index.php/Tmux#Autostart_with_systemd)

If such a file can be included in upstream (thirdparty? extra?), I think it can help lots of people on systemd-powered systems. 

Cheers

**Comment by ThomasAdam** [comment]
I really don't think we should be providing this.  This is outside of tmux's remit, and is better supported through Linux packagers.

**Comment by gdamjan** [comment]
why is a single declarative unit file a problem to include?
delegating to linux packagers will mean that every distro will have a different service file.
In the end it'll just increase the support burden even for tmux people.

**Comment by ThomasAdam** [comment]
Because the only we do in tmux is to support *that* in terms of the code which runs atop of the platforms we support.  The running of tmux on those systems (outside of any code changes needed) is down to the distributions.

**Comment by nicm** [comment]
We are not carrying around tons of little files that tmux itself doesn't use, we only just got rid of some of the other ones. It is so easy nowadays for people to host things themselves there is no reason for us to have it. For this, I suggest writing an FAQ entry with an explanation and a link to the file.
