### ISSUE TITLE
Attributes in window-status-separator are not evaluated

### ISSUE THREAD

**Issue by vilhalmer** [tmux/tmux#439]
The title pretty much covers it. I was hoping to make my separators the same color as the one I manually attach to status-left and -right, but instead I get the literal attribute text.

I'm running tmux 2.2 from Homebrew on OS X.

**Comment by nicm** [comment]
Try this please 
[x.txt](https://github.com/tmux/tmux/files/299532/x.txt)

**Comment by vilhalmer** [comment]
Appears to be working perfectly! Thanks.

**Comment by nicm** [comment]
Applied, thanks.
