### ISSUE TITLE
Using colors in window names

### ISSUE THREAD

**Issue by martinvonwittich** [tmux/tmux#442]
The man page explains how to rename a window:

```shell
printf '\033kWINDOW_NAME\033\\'
```

![Screenshot](http://i.imgur.com/WpKfu15.png)

I've also figured out that I can also use colors here:

```shell
printf '\033k#[fg=red]hello world\033\\'
```

![Screenshot](http://i.imgur.com/O40Pmz5.png)

What I can't figure out is how to disable the colors again, for example when I want the "hello" to appear red, but the "world" in the default text color. I tried `default`:

```shell
printf '\033k#[fg=red]hello#[fg=default] world\033\\'
```

But `default` seems to mean "the fg color from `status-style`", which in my case is black. That works well when the window is not the current window, because my `window-status-format` uses fg=black too:

![Screenshot](http://i.imgur.com/OnFZmfv.png)

But it doesn't look very good when the window is the current window, because my `window-status-current-format` uses fg=white:

![Screenshot](http://i.imgur.com/emqLa48.png)

What I'm looking for would be a special color name that reverts to the color specified by either `window-status-format` (if the window is not the current window) or the color specified by `window-status-current-format` (if the window is the current window). Or alternatively a way to specify that a color only affects a certain part of the string, something like `#[/fg]`, e.g.:

```shell
printf '\033k#[fg=red]hello#[/fg] world\033\\'
```

**Comment by nicm** [comment]
This works as intended for me:

$ tmux set -g status-style fg=red
$ tmux set -g window-status-style fg=blue
$ tmux set -g window-status-current-style fg=green
$ tmux renamew '#[fg=white]white#[fg=default]default'

**Comment by martinvonwittich** [comment]
Oohh.. I was missing `window-status-style` and `window-status-current-style` in my config; instead I had just put the colors in `window-status-format` and `window-status-current-format`. Thanks for the tip!
