### ISSUE TITLE
Unable to start nohup command

### ISSUE THREAD

**Issue by tnguyen14** [tmux/tmux#443]
When I have command like so
`nohup "$command" "$@" <&- >$HOME/command.log 2>&1 &`

 I can start it normally in iTerm2, but if I run it in a tmux session, I get this error:

`nohup: can't detach from console: Inappropriate ioctl for device`

I am seeing this issue on both tmux versions 2.1 and 2.2, OS X Yosemite and El Capitan.

**Comment by nicm** [comment]
There was an issue about this before but I can't find it. This is a bug either in OS X or in OS X nohup.

**Comment by tnguyen14** [comment]
@nicm Thank you for the response. If it is a bug, is there a way we could reproduce it so that it could be filed elsewhere?

**Comment by krader1961** [comment]
Does the problem occur if you replace the `<&-` with `</dev/null`?

You should never close stdin, stdout, or stderr. That's because the next `open()` call will use the lowest closed fd. So if you've closed stdin (which is what you did) the next `open()` call will be assigned fd 0 (stdin) which can cause problems when $command tries to use stdin.

**Comment by tnguyen14** [comment]
@krader1961 changing it to `</dev/null` didn't fix the issue for me. I am still getting the same error.

**Comment by krader1961** [comment]
> changing it to </dev/null didn't fix the issue for me.

Okay, that was a long shot. Nonetheless, you should get into the habit of doing that rather than `<&-` to avoid other problems.

I can't reproduce your problem. Probably because I'm using the [reattach-to-user-namespace](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard) program to launch my shell inside tmux. I do so via these entries in my *.tmux.conf*:

```
# The reattach-to-user-namespace is necessary to be able to contact ssh-agent
# via the SSH_AUTH_SOCK env var. This is also necessary to make pasteboard
# (clipboard) interaction work for programs run within the tmux server.
set-option -g default-command "exec reattach-to-user-namespace -l /usr/local/bin/fish"
```

**Comment by nicm** [comment]
You can reproduce it by running nohup inside tmux...

**Comment by krader1961** [comment]
> You can reproduce it by running nohup inside tmux...

Works fine for me but only if I launch the shell inside tmux via `reattach-to-user-namespace` as shown in my *.tmux.conf* snippet above. If I don't do that then, yes, I see the problem reported by the O.P.

**Comment by tnguyen14** [comment]
@nicm what is the reason to close this issue? We have validated that this is a reproducible problem. I understand that it might not be due to tmux itself, but tmux is still the environment the bug is occurring in. I feel like it should be kept open until we can figure out at least the root cause?

**Comment by krader1961** [comment]
@tnguyen14 The root cause is a well known quirk of OS X (MacOS). The solution is the one I posted above. The only thing for the tmux project to do is perhaps document this in its FAQ. In fact, it's already mentioned with respect to the pbcopy/pbpaste commands, it just needs to also mention nohup:

```
On OS X, reattach-to-usernamespace lets pbcopy/pbpaste work:

        https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
```

**Comment by nicm** [comment]
There is nothing else I need with this issue so it can be closed. If you find out anything relating to tmux you can continue to comment and I will get the updates by email.

**Comment by tnguyen14** [comment]
@krader1961 Thanks, but from that repo, I see this line
> Note: Under Yosemite (and later) pasteboard access seems to work fine without the program from this repository.

So it didn't seem like it was necessary for pbcopy/pbpase. I wonder if it might be too heavy-handed of a solution for nohup?
