### ISSUE TITLE
make `tmux attach` idempotent?

### ISSUE THREAD

**Issue by Profpatsch** [tmux/tmux#447]
I’m often not sure whether there is already a tmux session running, so I type `tmux attach`. Way to often it aborts with `no current session` and I have to retype `tmux`.

Are there any good reasons for not making that start up a session and attach to it? Especially considering that `tmux attach` doesn’t abort when there is more than one session, but attaches to the last opened one (I think).

**Comment by ntnn** [comment]
From the man page under attach-session:

    If no server is started, attach-session will attempt to start it;
    this will fail unless sessions are created in the configuration
    file.

**Comment by ntnn** [comment]
From the man page under attach-session:

    If no server is started, attach-session will attempt to start it;
    this will fail unless sessions are created in the configuration
    file.

**Comment by ntnn** [comment]
From the man page under attach-session:

    If no server is started, attach-session will attempt to start it;
    this will fail unless sessions are created in the configuration
    file.

**Comment by ntnn** [comment]
From the man page under attach-session:

    If no server is started, attach-session will attempt to start it;
    this will fail unless sessions are created in the configuration
    file.

**Comment by ntnn** [comment]
From the man page under attach-session:

    If no server is started, attach-session will attempt to start it;
    this will fail unless sessions are created in the configuration
    file.

**Comment by ntnn** [comment]
From the man page under attach-session:

    If no server is started, attach-session will attempt to start it;
    this will fail unless sessions are created in the configuration
    file.

**Comment by ntnn** [comment]
From the man page under attach-session:

    If no server is started, attach-session will attempt to start it;
    this will fail unless sessions are created in the configuration
    file.

**Comment by ntnn** [comment]
From the man page under attach-session:

    If no server is started, attach-session will attempt to start it;
    this will fail unless sessions are created in the configuration
    file.

**Comment by ntnn** [comment]
From the man page under attach-session:

    If no server is started, attach-session will attempt to start it;
    this will fail unless sessions are created in the configuration
    file.

**Comment by ntnn** [comment]
From the man page under attach-session:

    If no server is started, attach-session will attempt to start it;
    this will fail unless sessions are created in the configuration
    file.

**Comment by ntnn** [comment]
From the man page under attach-session:

    If no server is started, attach-session will attempt to start it;
    this will fail unless sessions are created in the configuration
    file.

**Comment by Profpatsch** [comment]
That was not the question, but thank you anyway.

I will have to patch it out myself, then.
