### ISSUE TITLE
Text corruption in gnome-terminal when highlighting with mouse

### ISSUE THREAD

**Issue by jnschaeffer** [tmux/tmux#459]
Highlighting certain portions of text causes garbled output to appear in gnome-terminal when the mouse is enabled.

Confirmed on a fresh install of Ubuntu 16.04 with Unity and a fresh Ubuntu 16.04 virtual machine with tmux 2.1 and 2.2.

Steps to reproduce:

1. Start tmux with the default configuration.
2. Run `:set-option -g mouse on` to enable the mouse in tmux.
3. Holding the mouse button, highlight all text in the terminal, including the first character of the prompt.
4. Release the mouse button.

The result should be garbage characters appearing on the screen, obscuring the original highlighted text. Attempting to highlight the characters will cause them to disappear and be replaced by the original prompt. When using split panes highlighting certain portions of text (particularly long strings) will also cause garbage characters to appear across panes.

This does not happen in xterm when using tmux, nor does it happen when highlighting text in gnome-terminal outside of tmux.

**Comment by nicm** [comment]
You are using TERM=xterm in a terminal that does not support xterm
features, in this case the clipboard escape sequences. Either turn
set-clipboard off in tmux, remove Ms and friends using terminal-overrides,
or use TERM=gnome.

**Comment by jnschaeffer** [comment]
Using TERM=gnome works, though it looks like tmux is actually setting TERM to screen, not xterm. Either way, that solves the problem. Thanks!

**Comment by nicm** [comment]
No you must use TERM=screen inside tmux and gnome outside

**Comment by jnschaeffer** [comment]
Right, what I did per your suggestion was to run `TERM=gnome tmux`, not to set TERM=gnome inside tmux. I had thought you meant TERM was being set to xterm inside screen. It looks like gnome-terminal's default is to use TERM=xterm-256color, which I'm assuming would explain the issue.
