### ISSUE TITLE
Right status bar disappear with long text

### ISSUE THREAD

**Issue by alex88** [tmux/tmux#46]
Hi there, I'm using powerline with tmux, I've already discussed with powerline owner about this issue at https://github.com/powerline/powerline/issues/1410 but the problem seems with the length of the text being displayed in tmux.

If you look at https://github.com/powerline/powerline/issues/1410#issuecomment-120666387 screenshots the issue seems to be the length of the status being set.
Also, `tmux show-options -g` seems to truncate its value, is that correct? Seems that after 165 bytes of content the tab disappear

I've tried to manually increase `status-right-length` but without any luck.

**Comment by nicm** [comment]
Are you asking about tmux show -g or about status-right in the actual status line?

What tmux version? What platform?

**Comment by alex88** [comment]
If you look at `tmux show-options -g` after I've set a long value, the `status-right` value is truncated, I've seen with `| sed 's/#\[[^]]*\]//g' | wc -c` that after 165 the right status disappear.

Anyway, tmux 2.0 on OSX 10.11

**Comment by nicm** [comment]
But it doesn't actually affect the status line?

**Comment by alex88** [comment]
Well the right part of the status line is not shown

**Comment by nicm** [comment]
If your status-right is longer than will fit on the screen, it will not be shown. Use status-right-length to limit it.

**Comment by alex88** [comment]
If the length is longer, shouldn't it shrink by removing components, or that's a powerline issue?

**Comment by nicm** [comment]
It removes windows until it can't fit any and then the status line is made blank.

**Comment by alex88** [comment]
Well if you look at the screenshots you see there is a lot of room on the left of the right status and with a single char Unicode it's hidden but with multiple single chars (so longer in size but smaller in bytes) it's shown

**Comment by nicm** [comment]
What screenshots?

**Comment by alex88** [comment]
The ones I'm talking about in the first comment https://github.com/powerline/powerline/issues/1410#issuecomment-120666387

**Comment by nicm** [comment]
This is not very clear.

So there is a point where if you set status-right to a string of width N
it will be shown in the status line and to N + 1 it is blank?

I suggest you generate lengths of strings with something like:

    python -c 'print "".join([str(x % 10) for x in range(0,200)])'

Until you find what point it works and what point it doesn't.

Also please let me know what width your terminal is.

Or are you suggesting it doesn't work with some particular UTF-8
characters? In which case please give me an exact status-right to
reproduce without any #[] or #() or #{} in it.

**Comment by fofoni** [comment]
I believe I'm having the same issue, and note that I don't have any fancy utf-8 characters. If I set the status to ` = 1.88% | "rio.smt.ufrj.br" 19:44 Nov-`, it displays correctly. However, when I set it to ` = 1.88% | "rio.smt.ufrj.br" 19:44 Nov-28`, the last `8` is not displayed. 

The problem persists when I set the status to the explicit strings I mentioned above, instead of the pattern `#{prefix_highlight} #{cpu_icon}#{cpu_percentage} | #h | %H:%M %h-%d ` that I was using when I noticed the problem.
