### ISSUE TITLE
"lost server" when entering vim mode

### ISSUE THREAD

**Issue by kouno** [tmux/tmux#460]
Configured a new machine and I'm getting `lost server` whenever I press ESC or `i` in tmux.

Here's the output I got when using `tmux -vvvv` when pressing ESC:
[tmux-client-50126.log.txt](https://github.com/tmux/tmux/files/327364/tmux-client-50126.log.txt)
[tmux-out-50128.log.txt](https://github.com/tmux/tmux/files/327365/tmux-out-50128.log.txt)
[tmux-server-50128.log.txt](https://github.com/tmux/tmux/files/327366/tmux-server-50128.log.txt)

tmux version is 2.2. Let me know if I can give you more information.

Also thanks for writing great software ❤️ !

**Comment by nicm** [comment]
This looks like you ran tmux in tmux -vvv and sent the logs of the outside tmux, you need to send the logs of the tmux that actually died.

**Comment by kouno** [comment]
tmux didn't die AFAICT.

```
[11:00:57] vincent.bonmalais:~ $ ps -ef | grep tmux
1204795080 57940     1   0 11:00AM ??         0:00.04 tmux
1204795080 57938 38293   0 11:00AM ttys000    0:00.00 tmux
1204795080 58258 58110   0 11:01AM ttys001    0:00.00 grep --colour=auto tmux
[11:01:00] vincent.bonmalais:~ $ lost server
lost server
[11:01:04] vincent.bonmalais:~ $ ps -ef | grep tmux                                                                                                                                                                                                                   <<<
1204795080 57940     1   0 11:00AM ??         0:00.07 tmux
1204795080 57938 38293   0 11:00AM ttys000    0:00.00 tmux
1204795080 58301 58110   0 11:01AM ttys001    0:00.00 grep --colour=auto tmux
```

The line where you see "lost server" is the one where I pressed ESC.

**Comment by nicm** [comment]
But that is coming from inside tmux. Does this still happen if you run:

tmux -Ltest -vvvv new

Then press Escape.


On Wed, Jun 22, 2016 at 03:03:07AM -0700, Vincent Bonmalais wrote:
>    tmux didn't die AFAICT.
> 
>  [11:00:57] vincent.bonmalais:~ $ ps -ef | grep tmux
>  1204795080 57940     1   0 11:00AM ??         0:00.04 tmux
>  1204795080 57938 38293   0 11:00AM ttys000    0:00.00 tmux
>  1204795080 58258 58110   0 11:01AM ttys001    0:00.00 grep --colour=auto tmux
>  [11:01:00] vincent.bonmalais:~ $ lost server
>  lost server
>  [11:01:04] vincent.bonmalais:~ $ ps -ef | grep tmux                                                                                                                                                                                                                   <<<
>  1204795080 57940     1   0 11:00AM ??         0:00.07 tmux
>  1204795080 57938 38293   0 11:00AM ttys000    0:00.00 tmux
>  1204795080 58301 58110   0 11:01AM ttys001    0:00.00 grep --colour=auto tmux
> 
>    The line where you see "lost server" is the one where I pressed ESC.
> 
>    --
>    You are receiving this because you commented.
>    Reply to this email directly, [1]view it on GitHub, or [2]mute the thread.
> 
>    Reverse link: [3]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/tmux/tmux/issues/460#issuecomment-227699206
>    2. https://github.com/notifications/unsubscribe/AASkc_5hCYsj3ArPS4K2LnYDfSpO_1vwks5qOQhbgaJpZM4I7kK0
>    3. https://github.com/tmux/tmux/issues/460#issuecomment-227699206

**Comment by kouno** [comment]
Yes, Indeed.

**Comment by nicm** [comment]
Show me those logs please...

**Comment by kouno** [comment]
Here you go:

[tmux-client-62273.log.txt](https://github.com/tmux/tmux/files/327532/tmux-client-62273.log.txt)
[tmux-out-62275.log.txt](https://github.com/tmux/tmux/files/327533/tmux-out-62275.log.txt)
[tmux-server-62275.log.txt](https://github.com/tmux/tmux/files/327534/tmux-server-62275.log.txt)

Again thanks for the help :)

**Comment by nicm** [comment]
Oh sorry I meant this:

tmux -Ltest -f/dev/null -vvvv new

Please try this instead.

**Comment by kouno** [comment]
Third time the charm? :)

[tmux-client-63778.log.txt](https://github.com/tmux/tmux/files/327620/tmux-client-63778.log.txt)
[tmux-out-63780.log.txt](https://github.com/tmux/tmux/files/327622/tmux-out-63780.log.txt)
[tmux-server-63780.log.txt](https://github.com/tmux/tmux/files/327621/tmux-server-63780.log.txt)

**Comment by nicm** [comment]
I think you have bound Escape to do something in your shell, because tmux is not triggering this.

**Comment by kouno** [comment]
Ok I found it.

I'm using `vi-mode` plugin in `oh-my-zsh`. Which created the issue. Removing it solved the issue.

Content of my vi-mode.zsh file: https://github.com/robbyrussell/oh-my-zsh/blob/87e782f/plugins/vi-mode/vi-mode.plugin.zsh

I don't think this file has changed on oh-my-zsh master branch either.
