### ISSUE TITLE
[Question] Sharing tmux socket between host and guest virtual machine

### ISSUE THREAD

**Issue by Morantron** [tmux/tmux#462]
Hi!

When working with containers or virtual machines, sometimes is common to end up in nested session scenario. This is far from ideal, because you need to bind some keyboard shortcut to send the prefix to the nested session, or use two different prefixes ( one for host, and one for guest VM ).

My question is, would it be possible to use the same tmux server by establishing a socket path ( `-S` option )? This would be two complete different instances of tmux in two separate different OSes ( that happen to share an specific folder )

I've tried already but I only get a `lost server` response, and the socket path is renamed to `/path/to/socket.lock`.

Thanks!

**Comment by ThomasAdam** [comment]
No, it's not currently possible.

**Comment by nicm** [comment]
No it is not possible.
