### ISSUE TITLE
Some unicode characters not displaying correctly (v2.2)

### ISSUE THREAD

**Issue by xamfoo** [tmux/tmux#463]
Thanks for looking at this 😄 

To reproduce:

- `rm ~/.tmux.conf`
- `tmux -u`
- `echo 💩`

Result:
- a blank line is echoed

Expected result:
- `💩` is echoed

Note:
- tmux v2.0 does not seem to have this issue when using these repro steps
- tmux v2.2 is installed in Ubuntu 14.04 by building from source
- Result is the same with other emoji characters as well

System:

```
> tmux -V
tmux 2.2

> lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

> locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by nicm** [comment]
Please try tmux from Git master and if that still doesn't work show me the tmux-server*.log file generated from running tmux (from Git) like this:

tmux -Ltest -f/dev/null -vvvv new

Then printing one nonworking character and exiting tmux.

**Comment by xamfoo** [comment]
```
> echo Iñtërnâtiônàlizætiøn☃💩
Iñtërnâtiônàlizætiøn☃💩
```
Seems fixed in master. Thanks! 😄

**Comment by cafeblue** [comment]
this happened again in tmux 2.4, 2.5 and the latest master (July 28).

 $ echo "\UF8FF"                                                                                [19:05:28]

 $ tmux -V                                                                                           [19:05:51]
tmux master
 $ rm -rf .tmux.conf                                                                            [19:05:54]
 $ tmux -Ltest -f/dev/null -vvvv new

 $ echo "\UF8FF"                                                                                [19:17:25]

 $ exit
[tmux-server-54721.log.txt](https://github.com/tmux/tmux/files/1189081/tmux-server-54721.log.txt)
