### ISSUE TITLE
send-keys displays "preview" of sent keys when used while detached or not-running

### ISSUE THREAD

**Issue by simbalion** [tmux/tmux#467]
When using 'tmux send-keys' from outside of a tmux session, this happens:
https://tailpuff.net/wp-content/uploads/2016/06/Capture.jpg

When using 'tmux send-keys' from inside a tmux session, there is no 'preview' of the commands sent.

Can this be patched? I would like to write a script to configure several windows and execute various commands (such as tail -f /var/log/blah), and only require a single input of the user's sudo password. I have made the script, but because of this weird behavior it displays the password in plain text in the scrollback buffer of the window.

**Comment by nicm** [comment]
You need to make sure you turn off echo (that the stty has finished) before
you send the other keys, if you send them all at once of course they will
be echoed.

**Comment by simbalion** [comment]
If you look at the image I linked you can see that I tried that. That works for the text sent to the prompt. The issue I wrote about is something different, the text appears at the very top of the buffer before everything else.

**Comment by nicm** [comment]
tmux just sends the keys to the window, it is up to the tty and the shell what gets echoed.

**Comment by nicm** [comment]
You are not turning off echo before you send the keys, you need to wait until the stty has actually taken effect before you send the keys. Try 'stty echo; sleep 2'.

**Comment by nicm** [comment]
I mean:

tmux send 'stty -echo'
sleep 2
tmux send 'whatever'

**Comment by nicm** [comment]
You will still see the 'stty -echo', echoed of course.
