### ISSUE TITLE
select-pane -LDUR command - disable auto-cycling behavior

### ISSUE THREAD

**Issue by fogine** [tmux/tmux#47]
Hello,

is it possible to disable the behavior which cause selecting a pane on opposite side of a tmux window if there is no more pane left in a direction `select-pane` command was originally triggered at?

if not, is there a way how to determine if any other panes exist in specific direction eg.: `select-pane -L`?

if a tmux window doesn't have any `(v)splited` window and a `select-pane` command is triggered, an error message is threw - this is expected behavior.

Thank you

**Comment by nicm** [comment]
You can probably work it out by looking at pane_left/right/top/bottom/width/height formats.

**Comment by fogine** [comment]
Thank you for response @nicm
I found the format variables. But I couldn't really find out what proper output should be from that formats...

if I do not have window splitted, it still give me a non-zero number for eg. for `pane_left/right`.
What a output of those formats represent?

**Comment by nicm** [comment]
They are the position on screen.

**Comment by gilgameshskytrooper** [comment]
Just add this to your `~/.tmux.conf`.

```
set-option -g default-shell /bin/bash
unbind Up     
unbind Down   
unbind Right   
unbind Left  
bind Up run-shell "if [ $(tmux display-message -p '#{pane_at_top}') -ne 1 ]; then tmux select-pane -U; fi"
bind Down run-shell "if [ $(tmux display-message -p '#{pane_at_bottom}') -ne 1 ] ; then tmux select-pane -D; fi"
bind Right run-shell "if [ $(tmux display-message -p '#{pane_at_right}') -ne 1 ]; then tmux select-pane -R; fi"
bind Left run-shell "if [ $(tmux display-message -p '#{pane_at_left}') -ne 1 ]; then tmux select-pane -L; fi"
```

If you want to launch a custom-shell, do it through `set-option -g default-command fish` (or zsh or csh or whatever). As an alternative, you can code out the logic above in the language of your choice. However, (as was in my case) using certain shells doesn't give you the convenience of one-liner if commands (or it might just be I don't know enough about certain shells, or maybe multiple lines do work in `run-shell`.

**Comment by gilgameshskytrooper** [comment]
I'm not a pro at tmux, I just found a partial work around I guess. Can you please what you are trying to accomplish? I'm not sure sure what you mean by shell name and current command?

**Comment by sandric** [comment]
@gilgameshskytrooper if you define a hook on `after-select-pane` with `rename-window "#{pane_current_command}"` - your shell name will be showed and not currently running program in pane you want to switch (lets say htop is running, but all you see is `fish`). That is because you wrap it in run-shell.

**Comment by gilgameshskytrooper** [comment]
I'm sorry for being exeedingly dull, but here is an example of me using the above settings (with a few failures 😜) [Had to install htop because its not really a program I really use]. But as you see, even with htop running, I had no issues navigating panes as usual (although I forgot to add the part of me showing how cycling is disabled so you're just going to have to take my word for it.)

But please watch and let me know what you think.

[https://youtu.be/QDvLQnorZMs](https://youtu.be/QDvLQnorZMs)

**Comment by sandric** [comment]
@gilgameshskytrooper hmm, interesting. Do you have `after-select-pane` hook set up with `rename-window` invoked, or you use default tmux renaming on interval?

**Comment by gilgameshskytrooper** [comment]
Here is everything in my `~/.tmux.conf`

```
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g default-terminal "tmux-256color"
set -g default-terminal "screen-256color"
set -ga terminal-overrides "screen-256color:Tc"
set -g mouse on
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'

set -g history-limit 20000

set-window-option -g mode-keys vi
# bind -Tcopy-mode-vi M-y send -X copy-pipe "lemonade copy" \; display-message "copied to system clipboard"
# bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "lemonade copy"

set-option -g default-command fish
set-option -g default-shell /bin/bash
unbind Up     
unbind Down   
unbind Right   
unbind Left  
bind Up run-shell "if [ $(tmux display-message -p '#{pane_at_top}') -ne 1 ]; then tmux select-pane -U; fi"
bind Down run-shell "if [ $(tmux display-message -p '#{pane_at_bottom}') -ne 1 ] ; then tmux select-pane -D; fi"
bind Right run-shell "if [ $(tmux display-message -p '#{pane_at_right}') -ne 1 ]; then tmux select-pane -R; fi"
bind Left run-shell "if [ $(tmux display-message -p '#{pane_at_left}') -ne 1 ]; then tmux select-pane -L; fi"
set-option -sg escape-time 10

run '~/.tmux/plugins/tpm/tpm'
```
