### ISSUE TITLE
Integration issues with direnv

### ISSUE THREAD

**Issue by zimbatm** [tmux/tmux#470]
Hi, author of direnv here.

We're having an issue integrating with tmux, I think because tmux does some unorthodox things with the environment variables which direnv very much depends on. Do you mind taking a look at what we've collected so far? https://github.com/direnv/direnv/issues/106

**Comment by nicm** [comment]
tmux always starts login shells (by default).

**Comment by nicm** [comment]
We could start with an empty environment except for what is in
update-environment I suppose but I'm not sure it wouldn't cause more
problems than it solves.

**Comment by zimbatm** [comment]
Yeah I think you're right, the same issue we found would probably also happen by just running `bash -l`, independently of tmux.

Thanks for listening :)
