### ISSUE TITLE
command-prompt use 2 %% args

### ISSUE THREAD

**Issue by lluxury** [tmux/tmux#472]
bind P command-prompt -p  "new-window  'exec ssh tomcat@%%'"  is works,
bind P command-prompt -p  "new-window  'exec ssh %%@%%'"  is error, what should I do?

man said that
Before the command is executed, the first occurrence of the string ‘%%’ and all occurrences of ‘%1’ are replaced by the response to the first prompt, the second ‘%%’ and all ‘%2’ are replaced with the response to the second prompt, and so on for further prompts. Up to nine prompt responses may be replaced (‘%1’ to ‘%9’).

I  wannr manual input; "tomcat  IP"  and tmux can ssh  %%@%%

**Comment by nicm** [comment]
Yes this is wrong, only the first %% is replaced, %2 is for the second
replacement.

You need to do:

bind P command-prompt -puser,host "neww 'exec ssh %1@%2'"
