### ISSUE TITLE
Configure script syntax error

### ISSUE THREAD

**Issue by hahmed1** [tmux/tmux#474]
I'm trying to run the ./configure script and I'm getting: 

./configure: line 4725: syntax error near unexpected token 'newline'  

Already ran autogen successfully, not sure what else to do.  

The last line on config.log is configure: exit 2

**Comment by nicm** [comment]
Where is config.log?

**Comment by hahmed1** [comment]
I think it gets generated by the ./configure script

**Comment by nicm** [comment]
Right but how am I meant to see it if you don't add it to the issue?

**Comment by hahmed1** [comment]
Right sorry.  

[config.txt](https://github.com/tmux/tmux/files/355457/config.txt)

**Comment by nicm** [comment]
Show me the configure script as well please. Did you generate it or use the one from the tarball?

**Comment by hahmed1** [comment]
It was generated from the autogen script on the latest commit.  

[configure.txt](https://github.com/tmux/tmux/files/364962/configure.txt)

**Comment by nicm** [comment]
You generated it yourself, but you don't have pkgconfig installed. You need to install pkgconfig.

**Comment by hahmed1** [comment]
Thank you!
