### ISSUE TITLE
Environment handling appears incorrect

### ISSUE THREAD

**Issue by justin8** [tmux/tmux#476]
We recently upgraded from v1.9 to v2.x and noticed some behavioural changes in how environment variables were being handled. It no longer behaves like the documentation explains. Would be best to return to what the documentation says, but worst case updating the documentation is required

It appears that some variables, notably PATH is inherited from the first created session, as well as variables in update-env.

According to http://man.openbsd.org/OpenBSD-current/man1/tmux.1#ENVIRONMENT
(If I read it correctly), when running 
```sh
tmux -C -L 1 kill-server
env -i PATH=p1 X=x1 Y=y1 tmux -C -L 1 new -s  a1 "/bin/bash -c '/usr/bin/env'; /bin/bash"
```
to create the first session PATH, X and Y are all taken from the caller

after that when creating the second session, only variables in update-env should be taken from environment
```sh
env -i PATH=p2 X=x2 Y=y2 tmux -C -L 1 new -s  a2 "/bin/bash -c '/usr/bin/env';"  
```

but instead of that PATH is updated too.

running 
```sh
tmux -C -L 1 set-option -g update-env X
tmux -C -L 1 show-option -g update-env
```

and then the second command gets X and PATH updated
with tmux 1.9, path handling was correct.

**Comment by nicm** [comment]
PATH is an exception, it always behaves as if it was in
update-environment. This is because if I do:

tmux neww -- mycommand

I want it to use the PATH I currently have set rather than the PATH from
the session environment.

**Comment by justin8** [comment]
Well, I would like the opposite.

Which is what happened in 1.9, but not 2.x.

Either way, if this change was intentional, then the documentation should be updated as it currently does not explain that PATH is handled as a special case, and in my situation caused a lot of issues as it was unexpected.

**Comment by nicm** [comment]
Yes it probably should.
