### ISSUE TITLE
reflow doesn't work with mksh

### ISSUE THREAD

**Issue by seanlaguna** [tmux/tmux#477]
Hello, I'm running Debian testing/unstable and using `mksh` for my shell. I am using tmux 2.2.

When I resize a window, the prompt is corrupted. The window need not have fewer columns than the prompt for this to happen.

I have tested this with empty tmux and mkshrc configs... it happens even when the prompt is a single character wide. Only the current prompt becomes corrupted, all past lines are fine.

Let me know if there's something else needed to confirm this.

I'm not claiming this is a bug with tmux, but there are no strange reflow behaviors with mksh in general, this doesn't happen with pdksh or other korn shells, and I'm kind of confused about where the source of the problem might be. Any leads would be helpful.

**Comment by nicm** [comment]
What is TERM inside and outside tmux? What is in your prompt?

**Comment by seanlaguna** [comment]
TERM inside tmux: `tmux-256color`
TERM outside tmux: `xterm-256color (or st-256color when using st)`

My prompt is a bit complex (uses the git prompt). But I've tested this with a prompt that's a single character, just `$`.

``` mksh
_PS1 ()
{
    local PRE= NAME="$1" LENGTH="$2";
    [[ "$NAME" != "${NAME#$HOME/}" || -z "${NAME#$HOME}" ]] &&
        PRE+='~' NAME="${NAME#$HOME}" LENGTH=$((LENGTH-1));
    ((${#NAME}>$LENGTH)) && NAME="/...${NAME:$((${#NAME}-LENGTH+4))}";
    echo "$PRE$NAME"
}
. ~/.git-prompt.mksh
export GIT_PS1_SHOWDIRTYSTATE=1
PS1='\
${debian_chroot:+($debian_chroot)}\
${USER:=$(id -un)}@${HOSTNAME:=$(hostname)}:\
$(_PS1 "$PWD" 32)\
$(__git_ps1 " (%s)")\
$(if (( USER_ID )); then print \$; else print \#; fi)\
 '
```

(As you can see the PS1 is not as nice for korn shells as for bash et. al)

Actually I've done some more testing and there seems to be an mksh idiosyncracy here. The only terminal that handles cutting the prompt reasonably correctly is `st` (`gnome-terminal` and `xfce4-terminal` are introducing some odd behavior on resized windows without tmux, though I'm not sure they make any guarantees about reflow regardless.

**Comment by seanlaguna** [comment]
You should be able to confirm this by installing mksh and typing it into your default shell prompt, then starting up tmux and resizing the window down at least half its original size. It would be nice to know if this is reproducible.

**Comment by nicm** [comment]
Looks like mksh doesn't use a newline when printing the prompt, instead
it uses spaces to clear the line and backspaces to go back to the end of
the prompt, so tmux doesn't see the line as wrapped.

**Comment by seanlaguna** [comment]
Holy cow! That's a bizarre behavior, but thanks for the detective work!

Any quick fix you can see given that difference?

**Comment by nicm** [comment]
Original OpenBSD ksh does not do this nor does ksh93, so I expect it is a
mksh invention.

**Comment by seanlaguna** [comment]
pdksh also doesn't do it. It is a mksh invention and lord knows why they chose this.

When I first found mksh I loved it, but slowly small issues have been cropping up and I'm thinking to switch off it again :(

**Comment by seanlaguna** [comment]
Hey, the mksh developer has addressed this. The reason for implementing it differently was to keep compatibility with some other tty, and to avoid requiring the curses library, but he decided to write a fix anyway, which can already be found committed to the public CVS repository. I have to give him a lot of credit for discussing this issue, having a good reason for implementing it the way he had, and creating a fix so quickly it was really great work on his part.

He did suggest, and I agree, that adding a setting for whether to use reflow would be good. It's a thing most people want, but it does step on the toes of the underlying shell, which ultimately is the only thing that knows what gets entered into the terminal.
