### ISSUE TITLE
Issue using meta-[non-latin-character] in tmux

### ISSUE THREAD

**Issue by etu** [tmux/tmux#479]
Hello!

I'm on Archlinux here, since updating to 2.2 I have issues using `meta-[non-latin-character]` in tmux, this wasn't a problem in 2.1.

(Using some emacs speech below, `M-` as in Meta or Alt)

If I in tmux 2.1 press `M-å` for example when my shell is active, it will enter the letter `å` therefore programs such as weechat can capture it and it works as a keybinding in there.

But since tmux 2.2, and I press `M-å`, it will enter `¥` instead which obviously breaks my keybindings. 

Sure I could probably keybind `M-¥` instead and enter it with `M-å` but it seems like wrong solution.

**Comment by nicm** [comment]
Is tmux from Git master the same?

**Comment by etu** [comment]
Good point, just built it and it seems like it works as expected there. Then I guess I just have to wait for the next release before I upgrade it :)
