### ISSUE TITLE
tmux exits with no error message when started with "large" environment variables

### ISSUE THREAD

**Issue by jnalley** [tmux/tmux#48]
Steps to reproduce:

1) Set a large environment variable e.g.

```bash
export FOO=$(tr -d '\t\n ' < /usr/share/dict/words | dd bs=1k count=64)
```

2) Start tmux

```bash
tmux
```

--
If started with '-v' tmux writes 'fatal: server_client_msg_identify: bad MSG_IDENTIFY_ENVIRON string' to  tmux-server-nnn.log.

Tested with tmux version 1.9 on Linux and 2.0 on OSX.

**Comment by nicm** [comment]
Try this please http://pastebin.com/raw.php?i=yzPFjAxM

**Comment by jnalley** [comment]
The patch fixes the issue.

Thanks!

**Comment by nicm** [comment]
Applied, thanks
