### ISSUE TITLE
Support iTerm3 Shell Integration escapes

### ISSUE THREAD

**Issue by docwhat** [tmux/tmux#482]
iTerm2 version 3 (iTerm3?) now has (Shell Integration)[https://www.iterm2.com/documentation-shell-integration.html) which is pretty cool.

I think the bulk of the problem is that their custom escape codes are being eaten by tmux.

According to their list of [proprietary escape codes](https://www.iterm2.com/documentation-escape-codes.html) what is missing is basically these two sequences:

* `^[]133;<something>^G` -- Used for meta binary codes.
* `^[]1337;<something>^G` -- Used for string commands, like `SetUserVar=foo=bar`.

Is it possible for tmux to pass these through?

**Comment by nicm** [comment]
We already have a general purpose escape sequence to pass through:

	\033Ptmux;<whatever>\033\\

You need to double up any \033.

**Comment by docwhat** [comment]
Sure, I [figured that out](https://github.com/docwhat/dotfiles/blob/master/zsh/startup/iterm.zsh#L6) but I have to detect TMUX to make those escape codes work.

I can't, to the best of my knowledge, detect TMUX over an ssh connection to a remote system.

There are some hacks, like mapping a tmux key to ssh and set some environment variables.

**Comment by nicm** [comment]
You can check TERM, it will be screen* or tmux* inside tmux.

**Comment by docwhat** [comment]
`screen` and its friends isn't that helpful (it could be screen. people still use that, right?).  Is there a `tmux` terminfo definition or something?

**Comment by nicm** [comment]
Yes there is but you need a recent ncurses.
