### ISSUE TITLE
border-status not taken in account for size of panes

### ISSUE THREAD

**Issue by YPetremann** [tmux/tmux#484]
When border-status are set to top or bottom, a line is added depending to the position but is not reserved like status bar, so top pane if set to top or bottom pane if set to bottom can have a height of one character instead of two.

The minimum height should be set to 1 or 2 to all pane and should take border-status parameter in account.

Demonstration : https://asciinema.org/a/6r1bosqk3e2ovtjuwl81rfjz4

**Comment by nicm** [comment]
Try this please: 
[layout.diff.txt](https://github.com/tmux/tmux/files/370963/layout.diff.txt)

**Comment by YPetremann** [comment]
This seems to solve the problem, thanks.

**Comment by nicm** [comment]
Applied, thanks.
