### ISSUE TITLE
'tmux;' passthrough: large sequences

### ISSUE THREAD

**Issue by cesarkawakami** [tmux/tmux#487]
I'm currently working on a small script between tmux and iTerm2 for myself for clipboard integration.

I've worked out that it'd in theory be possible to combine tmux's `tmux;` passthrough and iTerm2's `1337;CopyToClipboard=` escape sequence<sup>(1)</sup> to do a direct copy from the remote terminal to the local clipboard. I even have a script that somewhat works: https://gist.github.com/cesarkawakami/81a567af45a16522cb7ee20642feed41

The script emits something like this [newlines added for clarity]:

    \033Ptmux;\033
    \033\033]1337;CopyToClipboard=\007
    <whatever>
    \033\033]1337;EndCopy\007
    \033\\

The problem I'm having is that the passthrough sequence has an upper bound on the number of characters that are passed through. If I'm emitting

    \033Ptmux;\033<whatever>\033\\

and `<whatever>` is larger than (apparently) 211 characters, the command simply doesn't go through.

I've thought about chunking the input, doing something like:

    \033Ptmux;\033
    \033\033]1337;CopyToClipboard=\007
    first_chunk
    \033\\
    \033Ptmux;\033
    second_chunk
    \033\033]1337;EndCopy\007
    \033\\

But as soon as I emit the first `\033\\`, tmux emits some escape codes itself, adding spurious characters (from what I can see, they're always `\033[1;1H`) to the local clipboard.

Is there a way to either (1) avoid emitting these control characters temporariliy or (2) somehow work around the passthrough length limitation?

(1): https://www.iterm2.com/documentation-escape-codes.html

**Comment by nicm** [comment]
Am I supposed to guess the tmux version?

Well, I will... and my guess is tmux 1.9, because we increased the
buffer size in 2.0.

**Comment by cesarkawakami** [comment]
Oh wow, sorry about that. I've just realized I'm using a pretty old version, 1.8.5.

I didn't even think this could be something that'd get better with more modern versions, limiting buffer sizes to the smallest possible value seems like the natural thing to do in general.

Thanks for taking the time to comment that! I'll update my tmux version and rerun my tests.

**Comment by wookayin** [comment]
What is the length of passthrough buffer size? How can we escape a very long stream, if it's larger than the buffer size?
