### ISSUE TITLE
Shell used by new-window is not always user's default in OS X

### ISSUE THREAD

**Issue by echristopherson** [tmux/tmux#489]
I finally upgraded to tmux 2.2 from whatever I was using before (it might have even been 2.0), and now I find that when I invoke `tmux new-window` from non-terminal OS X apps (such as AppleScript), I get the following at the top of the window, and subsequently tab completion causes lots of error messages to be shot out (although using meta-/ for completion works without error):

    bash: declare: -A: invalid option
    declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
    bash: complete: -D: invalid option
    complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]

I've managed to deduce that this comes from part of the bash-completion stuff I have installed via Homebrew, which is compatible only with bash 4. The /bin/bash in OS X 10.11 is still 3.x; the bash 4 I use is /usr/local/bin/bash and is also provided by Homebrew. I believe tmux is, for some reason I don't know, using bash 3 as the shell when `tmux new-window` is run from programs not running in a terminal -- whenever I run it from within tmux or iTerm or Terminal, the window opens up with bash 4 and no error messages. (The same is true of my tmux key bindings related to new-window.) 

I just confirmed that /usr/local/bin/bash is my user's default shell.

The minimal test case I have for the broken behavior is to create an AppleScript with the text

    do shell script "/usr/local/bin/tmux new-window"

and run it. Interestingly, running the following in the shell doesn't trigger the bug:

    osascript -e 'do shell script "/usr/local/bin/tmux new-window"'

**Comment by nicm** [comment]
default-shell will be set from SHELL first, you probably need to set it manually.

**Comment by echristopherson** [comment]
OK, so when I'm already running my desired shell it just inherits that $SHELL value.

Is the current behavior intended, or should it look at the user's default shell in /etc/passwd or the OS-specific equivalent? I'm confused as to why the tmux server, which is running in a given environment (e.g. having a $SHELL variable inherited from the shell it was run in), would decide to replace part of that environment with the environment that's running the tmux command-line tool.

These are relevant lines:
https://github.com/tmux/tmux/blob/5658b628b9bf1c1e0bd5856736332ce8b9c51517/session.c#L341
https://github.com/tmux/tmux/blob/5e9412608ecae6fde3b68577397dbc07e6f2b4ac/tmux.c#L299

**Comment by nicm** [comment]
new-window will always use default-shell if not given a command.

**Comment by nicm** [comment]
Are you sure default-shell is set to the right shell after you start the tmux server?

**Comment by echristopherson** [comment]
Yes. It's set to /usr/local/bin/bash, as I intended.

**Comment by nicm** [comment]
And after you run the new-window where the problem is, what is in $SHELL and $BASH_VERSION?

**Comment by echristopherson** [comment]
I even just tried

    do shell script "/usr/local/bin/tmux show-options -g default-shell"

in an AppleScript to see how it behaves outside of any terminal; still shows /usr/local/bin/bash.

**Comment by echristopherson** [comment]
That's strange. The actual bash command in $SHELL is /usr/local/bin/bash, but the version is shown as 3.x:

    $ echo $SHELL
    /usr/local/bin/bash
    $ echo $BASH_VERSION
    3.2.57(1)-release

But it's obviously actually /bin/bash that's running.

**Comment by nicm** [comment]
tmux will always use default-shell. If you kill tmux entirely and restart with -vvv the log will show you what shell it is using (look for "spawn").

**Comment by echristopherson** [comment]
1469657865.785625 spawn: /usr/local/bin/bash -- bash --login
    1469657865.785635 spawn: argv[0] = bash --login

**Comment by nicm** [comment]
You are asking tmux to run bash --login, did you put it in default-command?
If it is run from somewhere without /usr/local/bin in PATH, then it will
use /bin. There is no need in any case, tmux runs login shells by default.

**Comment by echristopherson** [comment]
Oh... I had in .tmux.conf:

    set-option -g default-command "bash --login"

I'm not sure why I set that, but it had been in there for a long time. So I guess I was running twice as many bash processes as I needed all this time.

Tmux works as expected now.
