### ISSUE TITLE
from an kmscon session tmux prints ^@uu on startup

### ISSUE THREAD

**Issue by x539** [tmux/tmux#49]
Wenn starting tmux from an kmscon session tmux prints `^@u` before the first bash-prompt and `u` directly after.

I am using kmscon 8-8.fc22 (Fedora)
and
tmux 1.9a-5.fc22 / tmux 2.1 (git: dcc2843)

How to reproduce:
- Start _kmscon_
 `sudo kmscon --vt=/dev/tty3 --no-switchvt`

- Switch to TTY3

- Start _tmux_
 `$ tmux`

-
Output:
`^@u[myname@hostname] ~$ u`

**Comment by nicm** [comment]
What is TERM set to inside and outside tmux? What is in your prompt?

**Comment by x539** [comment]
TERM is `xterm-256color` outside and `screen-256color` inside
But it makes no difference if I set TERM to `linux` before starting tmux.

As prompt I use `powerline` but same Issue with `git-prompt` or plain `PS1='\$'`

The chars are only printed before/after the very first Prompt after starting tmux and not if I start tmux within tmux.

**Comment by nicm** [comment]
If you do C-b r after starting tmux do the characters disappear?

**Comment by x539** [comment]
No. Also if I `tmux attach` to that session, from a working Terminal, they are there.

If I `tmux attach` to a open Session from `kmscon` I only get an extra `u` after the Prompt (in all attached clients).

**Comment by nicm** [comment]
Please do this to reproduce the problem:

tmux -Ltest -vvvv new

Then "exit" and send me the tmux-*.log files that will be in the directory where you ran tmux.

**Comment by x539** [comment]
Here it is.

On 14.07.2015 15:13, Nicholas Marriott wrote:
> Please do this to reproduce the problem:
> 
> tmux -Ltest -vvvv new
> 
> Then "exit" and send me the tmux-*.log files that will be in the directory where you ran tmux.

-- 
Andreas Freimuth

**Comment by nicm** [comment]
Weird... tmux sees ^@ and u keys. My bet is the terminal is responding weirdly to something we send.

Do you still see this if you start tmux with TERM=vt100?

**Comment by x539** [comment]
No, with TERM=vt100 there is no Problem.

I'm not sure where the ^ and @ come from. But the Terminal response for `echo -e "\e[c"` is `60;1;6;9;15cu`. 

So it is a bug in `kmscon` ?

**Comment by nicm** [comment]
Yes it is, the response should end at the c. Probably there is a zero byte between the c and the u (zero is ^@).

**Comment by x539** [comment]
Thanks for the Quick help. Bug is Identified, patched and reported [Upstream](https://bugs.freedesktop.org/show_bug.cgi?id=91335).
