### ISSUE TITLE
24 bit color support for pane / window styling

### ISSUE THREAD

**Issue by sn0opy** [tmux/tmux#490]
Any chance to get a support to style windows, panes and other elements? Right now, Tmux only supports  256 colors and Hex codes become the closest color of the 256 color palette.

Related question on SO: http://stackoverflow.com/q/38495301/237312

**Comment by townba** [comment]
Have you tried building from the latest source? It should already work.

**Comment by townba** [comment]
To be specific, the changes from my branch that went in on July 14 fixed this, so builds using source from then on should allow you to style tmux using 24-bit color.

**Comment by jschaf** [comment]
Nice, works for me.
