### ISSUE TITLE
Mac OS ⌘K breaks UI

### ISSUE THREAD

**Issue by isaacmast** [tmux/tmux#491]
When using the standard terminal application on Mac OS X (v10.11.6 to be specific), the ⌘K command to clear the terminal scrolling buffer breaks the tmux UI. If multiple panes are open in the current window, the green pane separators disappears along with the terminal prompts of some of the other panes. The green banner at the bottom also disappears, but does return after several seconds. Creating a new pane while in the broken state seems to "fix" the UI, but the ⌘K command doesn't seem to have done anything because the scrolling buffer is still there. The whole experience is rather jarring. I've attached some before and after pictures for reference. 
![screen shot 2016-07-27 at 11 36 31 am](https://cloud.githubusercontent.com/assets/8737981/17182125/78663d62-53f0-11e6-97f6-a09cf139a665.png)
![screen shot 2016-07-27 at 11 37 45 am](https://cloud.githubusercontent.com/assets/8737981/17182129/7bdfb8c4-53f0-11e6-94fb-77cf7496ff2e.png)

**Comment by nicm** [comment]
You cannot ask the terminal to mess around with the terminal state behind tmux's back and expect tmux to work properly.

**Comment by krader1961** [comment]
Substitute any other app such as vim or emacs. Now press [cmd-K]. What happens? You should see that they too do not redraw the content of the screen. As @nicm said you can't change the state of the terminal behind the back of the application (and tmux is just an application) and expect it to magically notice what you just did.
