### ISSUE TITLE
unbind C-b,set caps-lock or option A

### ISSUE THREAD

**Issue by FantasRu** [tmux/tmux#493]
Hi.
Thanks for creating such a awesome terminal tools.
I am wondering if i can use caps-lock-a or option-a for prefix.
````
unbind C-b
set -g prefix ??-a
````
But i don't know what is the names of these keys in .tmux.conf

**Comment by nicm** [comment]
No you can't, at least not easily.

**Comment by FantasRu** [comment]
thx

**Comment by townba** [comment]
If you want to use the option key on a Mac as part of the prefix, you can try `set -g prefix M-a`. That would allow ⌥A to function as the prefix as long as your terminal emulator sends `Escape` for the option key. (If you use iTerm2 3.x, you can set this at Preferences→Profiles→Keys under "[Left|Right] option (⌥) key acts as:" – it's the "+Esc" option.) If you go this route, then pressing **Escape** then **A** will also work as the prefix.

**Comment by FantasRu** [comment]
It doesn't work when i've done this `set -g prefix M-a`.When i type in `option-a`,it returns me a `å`.

 ►_◄
