### ISSUE TITLE
unable to use `open` command anymore?

### ISSUE THREAD

**Issue by yifanchen** [tmux/tmux#494]
in Shell, run `open -a 'google chrome' index.html` takes me to Chrome and open that `index.html` file. 
but in Tmux, run `open -a 'google chrome' index.html` doesn't work, instead it opens new Chrome window without opening `index.html` in background.

**Comment by townba** [comment]
I take it you're on a Mac, right? I just tried it on my Mac and it worked as expected. Can you try starting tmux without your `.tmux.conf` (you can use `tmux -f /dev/null`) and see if it works differently?

**Comment by yifanchen** [comment]
Yes, I am on macOS El Cap. I've always had it working till some week last week I assume. I just tried run `tmux -f /dev/null` didn't work either.

**Comment by yifanchen** [comment]
Just restarted my machine, everything works as expected now. Thanks.
