### ISSUE TITLE
if-shell always get false result?

### ISSUE THREAD

**Issue by Treri** [tmux/tmux#495]
Because tmux 2.2 had removed some options only available before 2.2, but my server's tmux is old. So I want to have version detect in my tmux.conf to set some options only on old version.

But I found `if-shell` will always get false result?

my screenshot
![image](https://cloud.githubusercontent.com/assets/2631733/17287401/05e150b8-5802-11e6-99d8-35c4aff71387.png)

my tmux version is 2.2, and I use zsh as my default shell.

could anyone help me correctly detect tmux version in tmux.conf?

**Comment by Treri** [comment]
I get the anwser.

1. `-lt -lt -gt -ge` are only used for integer
2. string compare more than or equal, I have to use `[[ $a == 'string' ]] || [[ $a > 'string' ]]`

So this issue closed.

**Comment by douglasdd** [comment]
Also NOTE:  only POSIX shell syntax is officially supported for `if-shell`, so bash/zsh extensions (like `[[`) *might* work (or might not) -- depending on whether your `/bin/sh` is a symlink to `/bin/bash` (will work), or a symlink to `/bin/dash` (won't work), or something else entirely.
