### ISSUE TITLE
tmux pane does not respond

### ISSUE THREAD

**Issue by fabioperez** [tmux/tmux#496]
Sometimes (it seems random), my tmux panes do not respond to any command after it finishes running a command.

For example, after I run `ls`, the tmux does not respond to any key despite printing everything that I type. `Ctrl+C` does nothing.

[![enter image description here][1]][1]

I use zsh as my default shell. I'm not sure if this is a bug with zsh or tmux. Anyone knows a solution for this?

My setup:

    tmux 1.8
    zsh 5.0.2 (x86_64-pc-linux-gnu) (with Prezto)
    

  [1]: http://i.stack.imgur.com/CXXkv.png

**Comment by fabioperez** [comment]
@nicm https://github.com/fabioperez/dotfiles/blob/master/.tmux.conf

**Comment by nicm** [comment]
Does pressing C-q fix it?

**Comment by fabioperez** [comment]
@nicm No.

**Comment by nicm** [comment]
Ok please upgrade to tmux 2.2 and see if you can reproduce.

**Comment by fabioperez** [comment]
@nicm Yes, I got the same behaviour on 2.2.

**Comment by nicm** [comment]
Do this on 2.2:

tmux -Ltest -f/dev/null -vvvvv new

Then reproduce, then exit tmux (tmux kill-server) then send me the tmux-server-*.log file from the current directory.

**Comment by fabioperez** [comment]
I'm not able to reproduce with this command. Maybe it's something with the config.

**Comment by nicm** [comment]
Must be.
