### ISSUE TITLE
Add an option to turn off color inversion for the marked pane

### ISSUE THREAD

**Issue by raxod502** [tmux/tmux#497]
It appears that in _tmux_, when I mark a pane using `prefix-m`, the borders of that pane are displayed with inverted colors. By this I mean the foreground color is used for the background and the background color is used for the foreground.

I asked [a question on Stack Exchange](http://unix.stackexchange.com/questions/301890/turn-off-color-inversion-for-marked-pane-in-tmux) regarding whether or not it is possible to turn off this feature, and [the answer](http://unix.stackexchange.com/a/301901/176805), based on looking at the _tmux_ source code, was that this is impossible.

I am OK with the inverted colors, but with some color schemes (such as the foreground of pane borders being green and the background being transparent) the result can look quite odd, especially when different parts of a pane's borders are different colors. For instance:

<img width="370" alt="20160807155142" src="https://cloud.githubusercontent.com/assets/6559064/17465536/e283a3c8-5cb6-11e6-943c-873b86626836.png">

In some cases (and this might be a separate bug), I can even get the following by deleting panes after I have already marked one:

<img width="271" alt="20160807155519" src="https://cloud.githubusercontent.com/assets/6559064/17465555/7c82893a-5cb7-11e6-9f46-039fb22f24b3.png">

It seems reasonable to me, in any case, to at least have a configurable option, on by default, for whether or not to perform this inversion.

**Comment by ThomasAdam** [comment]
No thanks.  Given marked panes are meant to be transitory---that is, whilst performing a given command; an option for this seems overkill when the effect of the pane's border is for a short length of time only.
