### ISSUE TITLE
Keeps getting "lost server" in tmux 2.1 and 2.2. Installed using Homebrew

### ISSUE THREAD

**Issue by rezmuh** [tmux/tmux#498]
Hi,

A week ago, after my laptop was restarted (forcefully), I kept getting "lost server" whenever I"m in tmux. I could still proceed with everything else I wanted to work on but every time I typed anything, I would get "lost server" all the time. I was running tmux 2.1 at the time.

Then i upgraded my tmux to 2.2 using Homebrew. I kept getting the same thing. I even tried to remove my .tmux.conf to make sure it wasn't caused by plugins yet still getting that "lost server" messages.

When i ran tmux ls, here's what I get:
![No server running](https://dl.dropboxusercontent.com/s/yo50atfv0zntdil/Screenshot%202016-08-09%2015.27.55.png)

Inside tmux:
![inside tmux](https://dl.dropboxusercontent.com/s/ypm6pqqq6w58ljy/Screenshot%202016-08-09%2015.30.19.png)

Here's tmux-client-*.log when I run tmux -vvv:

1470731469.293530 client started (80899): socket /private/tmp/tmux-502/default, protocol 8
1470731469.293567 on Darwin 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64; libevent 2.0.22-stable (kqueue)
1470731469.293622 socket is /private/tmp/tmux-502/default
1470731469.293637 trying connect
1470731469.293661 connect failed: Connection refused
1470731469.293729 lock file is /private/tmp/tmux-502/default.lock
1470731469.293808 flock succeeded
1470731469.293817 got lock (5)
1470731469.293825 trying connect
1470731469.293836 connect failed: Connection refused
1470731469.294223 add peer 0x7fd3b401e600: 6 (0x0)
1470731469.295990 sending message 100 to peer 0x7fd3b401e600 (4 bytes)
1470731469.296016 sending message 101 to peer 0x7fd3b401e600 (15 bytes)
1470731469.296025 sending message 102 to peer 0x7fd3b401e600 (13 bytes)
1470731469.296032 sending message 108 to peer 0x7fd3b401e600 (14 bytes)
1470731469.296047 sending message 104 to peer 0x7fd3b401e600 (0 bytes)
1470731469.296055 sending message 107 to peer 0x7fd3b401e600 (4 bytes)
1470731469.296062 sending message 105 to peer 0x7fd3b401e600 (60 bytes)
1470731469.296069 sending message 105 to peer 0x7fd3b401e600 (66 bytes)
1470731469.296076 sending message 105 to peer 0x7fd3b401e600 (76 bytes)
1470731469.296083 sending message 105 to peer 0x7fd3b401e600 (15 bytes)
1470731469.296089 sending message 105 to peer 0x7fd3b401e600 (22 bytes)
1470731469.296096 sending message 105 to peer 0x7fd3b401e600 (14 bytes)
1470731469.296103 sending message 105 to peer 0x7fd3b401e600 (18 bytes)
1470731469.296110 sending message 105 to peer 0x7fd3b401e600 (25 bytes)
1470731469.296117 sending message 105 to peer 0x7fd3b401e600 (24 bytes)
1470731469.296123 sending message 105 to peer 0x7fd3b401e600 (15 bytes)
1470731469.296130 sending message 105 to peer 0x7fd3b401e600 (27 bytes)
1470731469.296137 sending message 105 to peer 0x7fd3b401e600 (23 bytes)
1470731469.296144 sending message 105 to peer 0x7fd3b401e600 (89 bytes)
1470731469.296151 sending message 105 to peer 0x7fd3b401e600 (22 bytes)
1470731469.296157 sending message 105 to peer 0x7fd3b401e600 (20 bytes)
1470731469.296164 sending message 105 to peer 0x7fd3b401e600 (19 bytes)
1470731469.296171 sending message 105 to peer 0x7fd3b401e600 (57 bytes)
1470731469.296178 sending message 105 to peer 0x7fd3b401e600 (12 bytes)
1470731469.296185 sending message 105 to peer 0x7fd3b401e600 (19 bytes)
1470731469.296191 sending message 105 to peer 0x7fd3b401e600 (15 bytes)
1470731469.296198 sending message 105 to peer 0x7fd3b401e600 (61 bytes)
1470731469.296205 sending message 105 to peer 0x7fd3b401e600 (38 bytes)
1470731469.296212 sending message 105 to peer 0x7fd3b401e600 (8 bytes)
1470731469.296218 sending message 105 to peer 0x7fd3b401e600 (21 bytes)
1470731469.296225 sending message 105 to peer 0x7fd3b401e600 (13 bytes)
1470731469.296232 sending message 105 to peer 0x7fd3b401e600 (26 bytes)
1470731469.296241 sending message 105 to peer 0x7fd3b401e600 (17 bytes)
1470731469.296249 sending message 105 to peer 0x7fd3b401e600 (11 bytes)
1470731469.296255 sending message 105 to peer 0x7fd3b401e600 (17 bytes)
1470731469.296262 sending message 105 to peer 0x7fd3b401e600 (34 bytes)
1470731469.296269 sending message 105 to peer 0x7fd3b401e600 (25 bytes)
1470731469.296276 sending message 105 to peer 0x7fd3b401e600 (25 bytes)
1470731469.296283 sending message 105 to peer 0x7fd3b401e600 (21 bytes)
1470731469.296290 sending message 105 to peer 0x7fd3b401e600 (21 bytes)
1470731469.296296 sending message 105 to peer 0x7fd3b401e600 (28 bytes)
1470731469.296303 sending message 105 to peer 0x7fd3b401e600 (21 bytes)
1470731469.296310 sending message 105 to peer 0x7fd3b401e600 (25 bytes)
1470731469.296317 sending message 105 to peer 0x7fd3b401e600 (32 bytes)
1470731469.296324 sending message 105 to peer 0x7fd3b401e600 (107 bytes)
1470731469.296331 sending message 105 to peer 0x7fd3b401e600 (17 bytes)
1470731469.296338 sending message 105 to peer 0x7fd3b401e600 (21 bytes)
1470731469.296345 sending message 105 to peer 0x7fd3b401e600 (39 bytes)
1470731469.296363 sending message 105 to peer 0x7fd3b401e600 (44 bytes)
1470731469.296370 sending message 105 to peer 0x7fd3b401e600 (30 bytes)
1470731469.296377 sending message 105 to peer 0x7fd3b401e600 (61 bytes)
1470731469.296384 sending message 105 to peer 0x7fd3b401e600 (54 bytes)
1470731469.296390 sending message 105 to peer 0x7fd3b401e600 (40 bytes)
1470731469.296397 sending message 105 to peer 0x7fd3b401e600 (47 bytes)
1470731469.296404 sending message 105 to peer 0x7fd3b401e600 (24 bytes)
1470731469.296411 sending message 105 to peer 0x7fd3b401e600 (136 bytes)
1470731469.296417 sending message 105 to peer 0x7fd3b401e600 (54 bytes)
1470731469.296424 sending message 105 to peer 0x7fd3b401e600 (22 bytes)
1470731469.296431 sending message 106 to peer 0x7fd3b401e600 (0 bytes)
1470731469.296441 sending message 200 to peer 0x7fd3b401e600 (4 bytes)
1470731469.296448 client loop enter
1470731470.780187 peer 0x7fd3b401e600 message 207
1470731470.780216 sending message 208 to peer 0x7fd3b401e600 (0 bytes)
1470731473.590380 peer 0x7fd3b401e600 message 203
1470731473.590395 sending message 205 to peer 0x7fd3b401e600 (0 bytes)
1470731473.590748 peer 0x7fd3b401e600 message 204
1470731473.590763 client loop exit

Can someone help me out on how to fix this?

Thank you

**Comment by nicm** [comment]
Kill tmux entirely, restart it with -vvv and send me the server log please.

**Comment by rezmuh** [comment]
Hi, here's server log:

https://gist.github.com/rezmuh/69751973d6480add3b7b7f6003f4b93f

Thanks

**Comment by nicm** [comment]
This message is not coming from the running tmux server it is coming
from something inside tmux, are you running an old copy of tmux or
something from your prompt?

**Comment by rezmuh** [comment]
hi @nicm sorry about above link. i stopped tmux before looking at the file.

Here's the server while tmux is still running with -vvv (i also removed my .tmux.conf first to make sure "lost server" issue doesn't come from the plugins I have).

https://gist.github.com/rezmuh/2184d59ad59085c6a57225257fc3a41c

And i'm running tmux 2.2, installed from Homebrew on Mac OS X 10.11.6

**Comment by nicm** [comment]
This is the same, there is something in your shell profile that is
running before every prompt and is causing this.

**Comment by rezmuh** [comment]
Hi, there's this line in my shell profile:

export PS1="$PS1"'$([ -n "$TMUX"  ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'

I used the above line for tmux-powerline to determine pwd. Not sure why it worked before though.

**Comment by nicm** [comment]
Dunno. Run the tmux commands manually and see which causes it?
