### ISSUE TITLE
Unable to set global hook via config file without a session started

### ISSUE THREAD

**Issue by mozzwald** [tmux/tmux#499]
I am trying to use set-hook to play a sound on terminal bell. This is in my tmux.conf:

`set-hook -g alert-bell 'run "aplay /usr/share/sounds/beep.wav"'`

but when starting tmux I get the error:

`tmux.conf:34: no current session`

Running the above set-hook command after a session is started works. I have tried another hook that displays the same error:

`set-hook -g after-new-window 'run "notify-send new-window"'`

My workaround at the moment is to check for $TMUX in my shell profile and then run set-hook. Is it possible to have set-hook work before a session has been started?

**Comment by nicm** [comment]
Isn't this fixed in Git master?

**Comment by mozzwald** [comment]
Sorry, I was building v2.2. Tested with master and it does work as expected.

Additionally, I'm cross compiling for arm with musl (openwrt) and needed to add 
```
#ifndef ACCESSPERMS
#define ACCESSPERMS (S_IRWXU|S_IRWXG|S_IRWXO)
#endif
```
to server.c for it to build.
