### ISSUE TITLE
In Emacs copy-mode, how to move the cursor to the beginning and end of screen?

### ISSUE THREAD

**Issue by hajimezhao** [tmux/tmux#50]
Hi everybody,
In tmux copy-mode (Emacs), I am able to use Alt-R to move the cursor to the middle of screen. Is it possible to move the cursor to the beginning and end of screen? (similar to M-r in Emacs defined by function move-to-window-line-top-bottom in window.el)

Thank you very much!
Bests,
Khon

**Comment by ntnn** [comment]
`man tmux | less +/copy-mode`

**Comment by hajimezhao** [comment]
Thank you very much! It works for me.
I did check in the tmux help, but forget to check in the manual.

Have a nice day,
Khon

On Wed, Jul 15, 2015 at 2:53 PM, Nelo-Thara Wallus <notifications@github.com
