### ISSUE TITLE
tty-term.c:410:37: error: ‘OK’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by herrbischoff** [tmux/tmux#502]
While trying to build v2.2 or Git master on Debian 8.5 as per instructions, I get the following error:

```
[...]
mv -f $depbase.Tpo $depbase.Po
tty-term.c: In function ‘tty_term_find’:
tty-term.c:410:37: error: ‘OK’ undeclared (first use in this function)
  if (setupterm(name, fd, &error) != OK) {
                                     ^
tty-term.c:410:37: note: each undeclared identifier is reported only once for each function it appears in
Makefile:862: recipe for target 'tty-term.o' failed
make: *** [tty-term.o] Error 1
```

**Comment by herrbischoff** [comment]
I found out that after running `apt-get install libncurses-dev`, it builds as expected. The configure script does not complain about missing ncurses dependencies though. Maybe this should be fixed.

**Comment by herrbischoff** [comment]
It'd be nice to get any kind of feedback on this instead of just closing the issue.

**Comment by nicm** [comment]
Feedback on what? You said you got it working?

**Comment by herrbischoff** [comment]
Feedback on:

> The configure script does not complain about missing ncurses dependencies though. Maybe this should be fixed.

**Comment by nicm** [comment]
configure and make output, config.log?

**Comment by welkinspring** [comment]
I also found this issue on Ubuntu 12.04 server, but it's ok on my VMWare Kali system, how to resolve it at last?
