### ISSUE TITLE
"tic: Can't open -" when trying to enable italics according to FAQ

### ISSUE THREAD

**Issue by prashcr** [tmux/tmux#504]
I was trying to enable italics according to: https://github.com/tmux/tmux/blob/2.2/FAQ#L355-L378

```
cat <<EOF|tic -x -
	tmux|tmux terminal multiplexer,
		ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
		use=xterm+tmux, use=screen,

	tmux-256color|tmux with 256 colors,
		use=xterm+256setaf, use=tmux,
	EOF
```

I get `tic: Can't open -` when I try to run this. What could I be doing wrong?

I'm on OS X 10.11.6, using tmux 2.2 installed via Homebrew.

**Comment by krader1961** [comment]
That just means your `tic` command doesn't recognize `-` to mean read from stdin (i.e., the pipe). Try running it without the `-` argument. If that doesn't work simply put the here-document in a temporary file and use that file name in place of the `-` argument.

P.S., When reporting these types of problems you should always tell us what operating system and version you're using.

**Comment by prashcr** [comment]
Sorry! Added details to original post.

I tried without `-` and it said a filename was required.

I then saved the below into a file called `tmux.terminfo` and ran `tic -x tmux.terminfo`, but it gives me a segfault instead.

```
[1]    32091 segmentation fault  tic -x tmux.terminfo
```

```
tmux|tmux terminal multiplexer,
    ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
    use=xterm+tmux, use=screen,

tmux-256color|tmux with 256 colors,
    use=xterm+256setaf, use=tmux,
```

**Comment by krader1961** [comment]
What OS are you using? Failures like "segmentation faults" in OS provided utilities are not something tmux is responsible for. That specific failure means `tic` accessed an invalid (probably zero or "NULL") memory address. The tmux community might be able to help but you should really be talking to the users and maintainers of whatever OS you are using.

**Comment by prashcr** [comment]
I added my OS to the first post, which is OS X 10.11.6.

Thank you for your help so far, and I understand this isn't the place for my issue. I was just surprised and hoping I'd done something wrong in following the instructions since I've seen the same instructions all over the internet and nobody seems to have had the same problem.

Where would you recommend me to look for help? I've posted this on apple.stackexchange as well though I haven't gotten any replies yet.

**Comment by nicm** [comment]
I'd guess one of the parent entries it is trying to include with Tc doesn't
exist. Your best bet is to do "infocmp -x tmux" on a platform with a modern
terminfo then install the result with tic -x on yours.

**Comment by RatanRSur** [comment]
Hi, @prashcr did you ever end up solving this? I'm having this issue currently

**Comment by prashcr** [comment]
@RatanRSur
Nope :S
I ended up just doing TERM=xterm-256color inside tmux which seems to work fine

**Comment by RatanRSur** [comment]
found this after I commented here which helped me:

**Comment by IanEdington** [comment]
Try this: https://apple.stackexchange.com/a/295584/160579
