### ISSUE TITLE
tmux 2.2 crashes on too many output of a pane

### ISSUE THREAD

**Issue by ChaosEternal** [tmux/tmux#506]
to reproduce:

type these command in a terminal(eg xterm, putty)
tmux
tmux splitw -d -h 'true' \; set-option remain-on-exit yes
tmux respawn-pane -t 1 "echo -e {1..10000}\\\n"

repeat last command multiple times and tmux will crash for sure

tested on version 2.2 and 2.1

PS:
if the last command changed to following, tmux can survive for thousands of rounds and survives until i stop the test.
tmux respawn-pane -t 1 "echo -e {1..10000}\\\n;sleep 0.5"

**Comment by ThomasAdam** [comment]
Can you try tmux from git?  I can't reproduce it there.

-- Thomas Adam

**Comment by ChaosEternal** [comment]
well, i tested with current git build
it does not crash
but the output of dead pane is not correct. 
see attachment

![screenshot-tmux](https://cloud.githubusercontent.com/assets/1491611/17699929/38b6d9cc-63f6-11e6-94ab-520a3cf02ccd.png)

**Comment by nicm** [comment]
Probably the process exited before tmux had processed all the output, in which case it is discarded. Try adding a sleep at the end of your process to let tmux catch up.

**Comment by ChaosEternal** [comment]
@nicm  thanks, but I've already documented that in my first message.

**Comment by nicm** [comment]
If the process exits before tmux finishes processing its output, we discard the remaining output. I don't think this is a problem.

**Comment by ChaosEternal** [comment]
@nicm I DONT think so, since the pane is flagged "remain-on-exit" that means the output is useful and desired be read.

**Comment by nicm** [comment]
No, remain-on-exit means the pane is not closed, it doesn't guarantee anything about the output.

Still, I think we can change this fairly easily. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/437170/x.diff.txt)

**Comment by ChaosEternal** [comment]
Are you saying this will be fixed in future commits? will the patch you'v mentioned be merged ?

**Comment by nicm** [comment]
Did you test it?

**Comment by ChaosEternal** [comment]
not fixed.

**Comment by nicm** [comment]
Hmm, it fixes it for me. Please run the following:

tmux -Ltest -vvvv -f/dev/null new

Then reproduce the problem, exit tmux and send me the tmux-server*.log file from the current directory.

**Comment by nicm** [comment]
Do this with a tmux built from Git master and with the patch applied please.

**Comment by ChaosEternal** [comment]
what do you expect me to do?
all issues are closed but problem remains unsolved and you are forbidding me opening new issue.
I am upset.

Why this issue gets closed before solved,  
and when a closed issue happens again, it should be reopened.
and Github GRANTS YOU THE ABILITY TO REOPEN IT, WHY DONT YOU REOPEN IT?

Please, reopen this issue.


And, I did the test with git HEAD with patch applied, FAILED
