### ISSUE TITLE
Tmux window freeze

### ISSUE THREAD

**Issue by BarbareBzhdev** [tmux/tmux#507]
Hi, 
Sometimes, the content of my tmux windows freezes. I can change pane, the time plugin correctly updates, but when I type any word in vim, shell or something else, nothing happens. If I change pane, the content of the window is refreshed, but still frozen. I can't reliably reproduce it, as it starts to happen every few hours.

![gifi](http://i.imgur.com/bQzEONZ.gif)

**Comment by nicm** [comment]
tmux version, platform, .tmux.conf?

**Comment by mbarbari** [comment]
Sorry, completely forgot about it!

tmux 2.3
Archlinux Linux ns352949 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64 GNU/Linux

```
#https://github.com/seebi/tmux-colors-solarized/blob/master/tmuxcolors-256.conf
set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow
set-option -g status-attr default

# set window split
bind-key v split-window -h
bind-key b split-window

# default window title colors
set-window-option -g window-status-fg colour244 #base0
set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg colour166 #orange
set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour240 #base01

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange
# clock
set-window-option -g clock-mode-colour green #green


set -g status-interval 1
set -g status-justify centre # center align window list
set -g status-left-length 20
set -g status-right-length 140
set -g status-left '#[fg=green]#H #[fg=black]• #[fg=green,bright]#(uname -r | cut -c 1-6)#[default]'
set -g status-right '#[fg=green,bg=default,bright]#(tmux-mem-cpu-load) #[fg=red,dim,bg=default]#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") #[fg=white,bg=default]%a%l:%M:%S %p#[default] #[fg=blue]%Y-%m-%d'

# C-b is not acceptable -- Vim uses it
set-option -g prefix C-a
bind-key C-a last-window

# Start numbering at 1
set -g base-index 1

# Allows for faster key repetition
set -s escape-time 0

# Rather than constraining window size to the maximum size of any client
# connected to the *session*, constrain window size to the maximum size of any
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Allows us to use C-a a <command> to send commands to a TMUX session inside
# another TMUX session
bind-key a send-prefix

# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

# Vi copypaste mode
set-window-option -g mode-keys vi
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection

# hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# set to main-horizontal, 60% height for main pane
bind m set-window-option main-pane-height 60\; select-layout main-horizontal

bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# auto window rename
set-window-option -g automatic-rename

# color
#set -g default-terminal "screen-256color"

# https://github.com/edkolev/dots/blob/master/tmux.conf
# Updates for tmux 1.9's current pane splitting paths.

# from powerline
run-shell "tmux set-environment -g TMUX_VERSION_MAJOR $(tmux -V | cut -d' ' -f2 | cut -d'.' -f1 | sed 's/[^0-9]*//g')"
run-shell "tmux set-environment -g TMUX_VERSION_MINOR $(tmux -V | cut -d' ' -f2 | cut -d'.' -f2 | sed 's/[^0-9]*//g')"

# status bar
if-shell '\( #{$TMUX_VERSION_MAJOR} -eq 2 -a #{$TMUX_VERSION_MINOR} -lt 2\) -o #{$TMUX_VERSION_MAJOR} -le 1' 'set-option -g status-utf8 on'

# rm mouse mode fail
if-shell '\( #{$TMUX_VERSION_MAJOR} -eq 2 -a #{$TMUX_VERSION_MINOR} -ge 1\) -o #{$TMUX_VERSION_MAJOR} -gt 2' 'set -g mouse off'
if-shell '\( #{$TMUX_VERSION_MAJOR} -eq 2 -a #{$TMUX_VERSION_MINOR} -lt 1\) -o #{$TMUX_VERSION_MAJOR} -le 1' 'set -g mode-mouse off'

# fix pane_current_path on new window and splits
if-shell "#{$TMUX_VERSION_MAJOR} -gt 1 -o \( #{$TMUX_VERSION_MAJOR} -eq 1 -a #{$TMUX_VERSION_MINOR} -ge 8 \)" 'unbind c; bind c new-window -c "#{pane_current_path}"'
if-shell "#{$TMUX_VERSION_MAJOR} -gt 1 -o \( #{$TMUX_VERSION_MAJOR} -eq 1 -a #{$TMUX_VERSION_MINOR} -ge 8 \)" "unbind '\"'; bind '\"' split-window -v -c '#{pane_current_path}'"
if-shell "#{$TMUX_VERSION_MAJOR} -gt 1 -o \( #{$TMUX_VERSION_MAJOR} -eq 1 -a #{$TMUX_VERSION_MINOR} -ge 8 \)" 'unbind v; bind v split-window -h -c "#{pane_current_path}"'
if-shell "#{$TMUX_VERSION_MAJOR} -gt 1 -o \( #{$TMUX_VERSION_MAJOR} -eq 1 -a #{$TMUX_VERSION_MINOR} -ge 8 \)" 'unbind %; bind % split-window -h -c "#{pane_current_path}"'
```

**Comment by nicm** [comment]
Hmm. Are you using xclip?

**Comment by mbarbari** [comment]
Nop :)

**Comment by nicm** [comment]
Are you sure you are running the latest Git build?

**Comment by ChaosEternal** [comment]
try press ctrl-q ?

**Comment by mbarbari** [comment]
the build's commit is af389364739224e5fefa1e523b110fdcae1c7961 the merge of 19 jully.

**Comment by nicm** [comment]
Ok please kill tmux entirely and run tmux with -vvvv, then reproduce then
kill tmux and send me the tmux-server*.log file from the current directory.

**Comment by mbarbari** [comment]
oki thanks :)

**Comment by Bastian-Kuhn** [comment]
Same here, but with tmux 2.1. Luckily happens rarely, but i can not reproduce it. 
Its on Ubuntu 16.04, I can create new Tabs, switch between split screens, but cannot type anything into the shells or to e.g. vim.  I started now tmux again with -vvv and hope the error happens again in the next time.

**Comment by nicm** [comment]
2.1 is too old

**Comment by Bastian-Kuhn** [comment]
It's the version shipped with Ubuntu 16.04. too bad...

**Comment by BarbareBzhdev** [comment]
in fact, since I launch tmux with -vvv I don't have freeze anymore. But if i delete -vvv option, it's begins again...

**Comment by BarbareBzhdev** [comment]
Ah yes, if i use tmux with Socket option, i don't have any problem.

**Comment by typeless** [comment]
I was just encountering the issue (again) and finding the issue ticket here.
Eventually, the solution I discovered is as follows:

1. [prefix] + d to detach tmux
2. ```kill -CONT `pidof tmux` ```

3. ```tmux attach```

Hope this helps

**Comment by a-kazakov** [comment]
I'm also having this issue very often. detaching `[prefix] + d` and reattaching with `-d` option (`tmux a -d`) usually helps me.

**Comment by agherzan** [comment]
I have the same problem with byobu.

**Comment by haridsv** [comment]
This actually happened to me today when I pasted into Vim using `^B]`. Vim appeared to be stuck in insert mode. Though I thought it was an issue with tmux, as the rest of the tmux tabs were responding and even the Vim tab was responding (e.g., for help and scrolling), I realized it was Vim that is stuck. I was able to recover Vim by the following sequence:
- Send `SIGSTOP` to Vim
- Use `fg` to get back into Vim
- Press `^C`
- Press `:redraw!`

**Comment by ClonedOne** [comment]
I am experiencing the same exact issue. 
Ubuntu 16.04, Tmux 2.1.
All the fixes proposed above did not work.

**Comment by dmitry-kabanov** [comment]
I've just got this thing also with Ubuntu 16.04 and Tmux 2.1.

**Comment by interbiznw** [comment]
getting it frequently on ubuntu 16.04 also

**Comment by pemmaraju5** [comment]
I am running into the same issue on CentOS 7.4 + Tmux v.2.1. Detaching my session and reattaching with -d seems to work in my case at least. 

`tmux attach -d`

**Comment by SethArchambault** [comment]
The issue for me was solved by this solution:
https://superuser.com/questions/553330/vim-freezes-inside-tmux

> You might have hit Ctrl+S, which turns off flow control in terminals and stops the terminal from accepting input. It is reenabled by pressing Ctrl+Q.

**Comment by alphaCTzo7G** [comment]
Having the same issue a few times. I can switch between panes, create new panes, but I cant type in vim or in the shell. If I create a new session it works..

Also its intermittent as others have pointed out. It usually happens when I start up my laptops

**Comment by alphaCTzo7G** [comment]
@pemmaraju5 , what does the `-d` option do?

**Comment by alphaCTzo7G** [comment]
it seems that using `Ctrl-S` solved the problem for me. If it happens, again I will try it again and repost here for others

**Comment by mkschreder** [comment]
You should first try to close your terminal window and then run "tmux attach" when my window froze this was the solution. There was nothing wrong with tmux, just the terminal froze.

**Comment by Fonata** [comment]
@alphaCTzo7G from the man page:
> If **-d** is specified, any other clients attached to the session are detached.

I am also running tmux 2.1 and will update my Ubuntu in hope of getting a newer tmux.

**Comment by TDHTTTT** [comment]
> try press ctrl-q ?

wow but why it works?

**Comment by ChaosEternal** [comment]
magic

**Comment by m3at** [comment]
@TDHTTTT if you're still curious about this, it's because of something called [flow control](https://en.wikipedia.org/wiki/Software_flow_control). Simply put XON/XOFF toggle data transmission, with the particular key mapping (ctrl-s/ctrl-q) originating from a machine from 1963 (!) ([link](https://en.wikipedia.org/wiki/Teletype_Model_33#Historical_impact)). Bonus: [some history](http://rachelbythebay.com/w/2015/06/20/blocking/)

**Comment by yushuinanrong** [comment]
Press ctrl-q indeed solve the problem for me. Pure magic!

**Comment by yushuinanrong** [comment]
> try press ctrl-q ?

Pure magic!
