### ISSUE TITLE
[feature] support duplicate the current panel 

### ISSUE THREAD

**Issue by jiahut** [tmux/tmux#508]
I use the tmux everyday,  often fork current panel then do something temporary and back , so I  found that duplicate the currrent panel will be very useful. can support this feature in future ?  
thinks

**Comment by ThomasAdam** [comment]
What feature?  If you use `-c '#{pane_current_path}'` then you already get this for free...

**Comment by jiahut** [comment]
@ThomasAdam  thinks.
duplicate session, for example , I am  in  ssh@aws,  or had defined some variable in current shell ,I would fork current shell session ,not only current pane path.

**Comment by nicm** [comment]
You can already duplicate a window with link-window.
