### ISSUE TITLE
Some charcater are altered when used in tmux

### ISSUE THREAD

**Issue by eephyne** [tmux/tmux#509]
I don't really know how to explain corretly this.

I use a french layout for my keyboard, so I have some keys not in ascii like é è ç à.
I use them without issue in tmux but I recently try to use a binding (Alt-é) in emacs and discover that in tmux Alt-é give me ©, in urxvt without tmux , it give me ^[é which is what I want.
Its the same for all the others keys (except the ascii one of course).
I tested with screen and there is no issue, with tmux on multiple terminal, still the same issue.
I asked different people and they seem to have this issue too.

**Comment by nicm** [comment]
tmux version? Platform? Logs from running with -vvvv?

**Comment by eephyne** [comment]
tmux 2.2 , linux (arch 64) 
-vvvv flag give me this

> 1471519121.462352 client started (19914): socket /tmp/tmux-1000/default, protocol 8
> 1471519121.462405 on Linux 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016; libevent 2.0.22-stable (epoll)
> 1471519121.462461 socket is /tmp/tmux-1000/default
> 1471519121.462482 trying connect
> 1471519121.462574 add peer 0xf0b9a0: 7 ((nil))
> 1471519121.462690 sending message 100 to peer 0xf0b9a0 (4 bytes)
> 1471519121.462720 sending message 101 to peer 0xf0b9a0 (15 bytes)
> 1471519121.462738 sending message 102 to peer 0xf0b9a0 (11 bytes)
> 1471519121.462753 sending message 108 to peer 0xf0b9a0 (14 bytes)
> 1471519121.462771 sending message 104 to peer 0xf0b9a0 (0 bytes)
> 1471519121.462787 sending message 107 to peer 0xf0b9a0 (4 bytes)
> 1471519121.462801 sending message 105 to peer 0xf0b9a0 (11 bytes)
> 1471519121.462816 sending message 105 to peer 0xf0b9a0 (57 bytes)
> 1471519121.462832 sending message 105 to peer 0xf0b9a0 (18 bytes)
> 1471519121.462847 sending message 105 to peer 0xf0b9a0 (15 bytes)
> 1471519121.462862 sending message 105 to peer 0xf0b9a0 (54 bytes)
> 1471519121.462876 sending message 105 to peer 0xf0b9a0 (45 bytes)
> 1471519121.462890 sending message 105 to peer 0xf0b9a0 (31 bytes)
> 1471519121.462905 sending message 105 to peer 0xf0b9a0 (13 bytes)
> 1471519121.462918 sending message 105 to peer 0xf0b9a0 (37 bytes)
> 1471519121.462933 sending message 105 to peer 0xf0b9a0 (58 bytes)
> 1471519121.462947 sending message 105 to peer 0xf0b9a0 (25 bytes)
> 1471519121.462969 sending message 105 to peer 0xf0b9a0 (60 bytes)
> 1471519121.462982 sending message 105 to peer 0xf0b9a0 (17 bytes)
> 1471519121.462995 sending message 105 to peer 0xf0b9a0 (41 bytes)
> 1471519121.463007 sending message 105 to peer 0xf0b9a0 (52 bytes)
> 1471519121.463020 sending message 105 to peer 0xf0b9a0 (284 bytes)
> 1471519121.463039 sending message 105 to peer 0xf0b9a0 (29 bytes)
> 1471519121.463053 sending message 105 to peer 0xf0b9a0 (22 bytes)
> 1471519121.463066 sending message 105 to peer 0xf0b9a0 (13 bytes)
> 1471519121.463078 sending message 105 to peer 0xf0b9a0 (52 bytes)
> 1471519121.463090 sending message 105 to peer 0xf0b9a0 (18 bytes)
> 1471519121.463104 sending message 105 to peer 0xf0b9a0 (21 bytes)
> 1471519121.463118 sending message 105 to peer 0xf0b9a0 (18 bytes)
> 1471519121.463131 sending message 105 to peer 0xf0b9a0 (51 bytes)
> 1471519121.463143 sending message 105 to peer 0xf0b9a0 (20 bytes)
> 1471519121.463156 sending message 105 to peer 0xf0b9a0 (23 bytes)
> 1471519121.463169 sending message 105 to peer 0xf0b9a0 (16 bytes)
> 1471519121.463182 sending message 105 to peer 0xf0b9a0 (52 bytes)
> 1471519121.463195 sending message 105 to peer 0xf0b9a0 (20 bytes)
> 1471519121.463209 sending message 105 to peer 0xf0b9a0 (16 bytes)
> 1471519121.463223 sending message 105 to peer 0xf0b9a0 (17 bytes)
> 1471519121.463237 sending message 105 to peer 0xf0b9a0 (15 bytes)
> 1471519121.463250 sending message 105 to peer 0xf0b9a0 (19 bytes)
> 1471519121.463263 sending message 105 to peer 0xf0b9a0 (8 bytes)
> 1471519121.463277 sending message 105 to peer 0xf0b9a0 (61 bytes)
> 1471519121.463290 sending message 105 to peer 0xf0b9a0 (16 bytes)
> 1471519121.463302 sending message 105 to peer 0xf0b9a0 (26 bytes)
> 1471519121.463315 sending message 105 to peer 0xf0b9a0 (54 bytes)
> 1471519121.463327 sending message 105 to peer 0xf0b9a0 (50 bytes)
> 1471519121.463350 sending message 105 to peer 0xf0b9a0 (13 bytes)
> 1471519121.463364 sending message 105 to peer 0xf0b9a0 (31 bytes)
> 1471519121.463377 sending message 105 to peer 0xf0b9a0 (11 bytes)
> 1471519121.463391 sending message 105 to peer 0xf0b9a0 (56 bytes)
> 1471519121.463404 sending message 105 to peer 0xf0b9a0 (26 bytes)
> 1471519121.463416 sending message 105 to peer 0xf0b9a0 (19 bytes)
> 1471519121.463429 sending message 105 to peer 0xf0b9a0 (41 bytes)
> 1471519121.463441 sending message 105 to peer 0xf0b9a0 (45 bytes)
> 1471519121.463454 sending message 105 to peer 0xf0b9a0 (44 bytes)
> 1471519121.463469 sending message 105 to peer 0xf0b9a0 (23 bytes)
> 1471519121.463484 sending message 105 to peer 0xf0b9a0 (36 bytes)
> 1471519121.463498 sending message 105 to peer 0xf0b9a0 (80 bytes)
> 1471519121.463512 sending message 105 to peer 0xf0b9a0 (41 bytes)
> 1471519121.463539 sending message 105 to peer 0xf0b9a0 (64 bytes)
> 1471519121.463552 sending message 105 to peer 0xf0b9a0 (36 bytes)
> 1471519121.463564 sending message 105 to peer 0xf0b9a0 (24 bytes)
> 1471519121.463576 sending message 105 to peer 0xf0b9a0 (33 bytes)
> 1471519121.463589 sending message 105 to peer 0xf0b9a0 (18 bytes)
> 1471519121.463602 sending message 105 to peer 0xf0b9a0 (15 bytes)
> 1471519121.463615 sending message 105 to peer 0xf0b9a0 (14 bytes)
> 1471519121.463628 sending message 105 to peer 0xf0b9a0 (20 bytes)
> 1471519121.463640 sending message 105 to peer 0xf0b9a0 (50 bytes)
> 1471519121.463653 sending message 105 to peer 0xf0b9a0 (11 bytes)
> 1471519121.463666 sending message 105 to peer 0xf0b9a0 (11 bytes)
> 1471519121.463680 sending message 105 to peer 0xf0b9a0 (1416 bytes)
> 1471519121.463713 sending message 105 to peer 0xf0b9a0 (25 bytes)
> 1471519121.463729 sending message 105 to peer 0xf0b9a0 (25 bytes)
> 1471519121.463743 sending message 105 to peer 0xf0b9a0 (21 bytes)
> 1471519121.463756 sending message 105 to peer 0xf0b9a0 (21 bytes)
> 1471519121.463769 sending message 105 to peer 0xf0b9a0 (28 bytes)
> 1471519121.463783 sending message 105 to peer 0xf0b9a0 (21 bytes)
> 1471519121.463797 sending message 105 to peer 0xf0b9a0 (25 bytes)
> 1471519121.463810 sending message 105 to peer 0xf0b9a0 (32 bytes)
> 1471519121.463824 sending message 105 to peer 0xf0b9a0 (16 bytes)
> 1471519121.463837 sending message 106 to peer 0xf0b9a0 (0 bytes)
> 1471519121.463852 sending message 200 to peer 0xf0b9a0 (4 bytes)
> 1471519121.463866 client loop enter
> 1471519121.468276 peer 0xf0b9a0 message 207
> 1471519121.468306 sending message 208 to peer 0xf0b9a0 (0 bytes)


just after starting but nothing after

**Comment by nicm** [comment]
Does it work if you build tmux from Git master?

**Comment by eephyne** [comment]
I will test

**Comment by eephyne** [comment]
still the same behavior with git build

**Comment by nicm** [comment]
Ok please do this:

tmux -vvvv -Ltest -f/dev/null new

Then press one key that does not work, then exit tmux and send me the
tmux-server*.log file.

**Comment by eephyne** [comment]
http://pastebin.com/CBtQT3cC

**Comment by nicm** [comment]
Are you sure this is tmux built from Git master?

**Comment by eephyne** [comment]
ah no, I did it with mine version, I did'nt get you wanted it from the git one 

When I do it with git version I don't get a server log only a client one

**Comment by nicm** [comment]
You Will get a log if you kill tmux entirely first then run what I said.

**Comment by eephyne** [comment]
ok done http://pastebin.com/Fi3iY5Sv
But it worked, the last time I did'nt killed the other tmux running (sorry). so with git version it seem to work

**Comment by eephyne** [comment]
Since git version is working, you want to close this or still want to debug it?

**Comment by nicm** [comment]
Ok great

**Comment by nicm** [comment]
Close it please
