### ISSUE TITLE
Tmux pane spilling

### ISSUE THREAD

**Issue by pe-vsn** [tmux/tmux#51]
This crashes tmux. Also, if you have two panes open, this will cause the data in the pane running this to spill over into the other pane.

```
wget -O - http://distfiles.gentoo.org/releases/arm/autobuilds/20150607/stage3-armv7a_hardfp-20150607.tar.bz2
```

**Comment by ThomasAdam** [comment]
Well, that's hardly surprising about the spurious output, given what you've asked it to do.  Likewise, I'm sure you could achieve the same result by catting /dev/urandom as well.

I'm more interested in the crash you're reporting.  Is it an actual segfault?  If so, can you get a backtrace?

**Comment by pe-vsn** [comment]
Sorry, should have been more descriptive. Tmux doesn't crash, but it does not recover from that command (or `cat /dev/urandom`). I'm sure you can recreate the /dev/urandom case easy enough. I think the best I could do to describe the issue is a screenshot? I really can't describe it.

**Comment by nicm** [comment]
Does just that pane not recover? What did you try? Did you try: set -u automatic-rename; send-keys -R?

Or does the entire tmux server hang?

**Comment by pe-vsn** [comment]
The most noticeable issues is the green bar at the bottom. After the cat is done, it acts "randomly": sometimes creating two lines of green bars sometimes more. When the terminal cursor is at the bottom of the screen it gets mixed up in the green bars creeping up.

**Comment by nicm** [comment]
You can't just send random crap the terminal and expect it not to be messed up. Some of it is likely to make tmux do things you don't want and - more importantly - stuff that tmux has to pass through may make the terminal outside do things that tmux doesn't want and can't predict (particularly, some terminals accept top bit set escape sequences). If unsetting automatic-rename and send-keys -R doesn't fix it then you will probably have to do them and also reattach from a new terminal.

If tmux crashes that is actually a bug however.
