### ISSUE TITLE
Using environment variables in run-shell

### ISSUE THREAD

**Issue by agross** [tmux/tmux#511]
Hi,

I just started looking at tmux and tpm. I'd like to download tpm (and plugins) to a custom directory and I was trying this:

```
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.cache/tmux'
if "test ! -d $TMUX_PLUGIN_MANAGER_PATH/tpm" "run-shell "git clone --depth 1 https://github.com/tmux-plugins/tpm $TMUX_PLUGIN_MANAGER_PATH/tpm""
run-shell "TMUX_PLUGIN_MANAGER_PATH/tpm"
```

Note the use of `$TMUX_PLUGIN_MANAGER_PATH`in run-shell. I also tried different quotes, as I guess normal shell quoting rules apply.

That doesn't seem to work, tpm is never downloaded. Only when I manually `source tmux.conf` the download starts.

My guess is that `set-environment` isn't setting the environment of the initial tmux process, but for the shell. Only after the shell has started and `source` is run by me, the environment variable is available.

Any ideas how to work around me repeating myself like I need to right now:

```
# Install tpm unless it is.
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.cache/tmux'

# Using $TMUX_PLUGIN_MANAGER_PATH here does not seem to work.
if "test ! -d ~/.cache/tmux/tpm" "run-shell 'git clone --depth 1 https://github.com/tmux-plugins/tpm ~/.cache/tmux/tpm'"

# Initialize tmux plugin manager (keep this line at the very bottom of tmux.conf).
run-shell '~/.cache/tmux/tpm/tpm'
```

Thanks!

Alex

**Comment by ntnn** [comment]
`setenv` modifies the session-global table of environment variables
passed to shells started by tmux. My guess is that tmux' only passes
these down to children after parsing the initial config file.

A feasible workaround would be to keep the environment variable in your
shells' profile.

**Comment by agross** [comment]
Many thanks for the clarification! I now went with the default directories.
