### ISSUE TITLE
tmux server with no sessions automatically closes itself

### ISSUE THREAD

**Issue by BrainDamage** [tmux/tmux#512]
tmux server with no sessions seems to automatically close itself, i'm not sure if this is intentional or a bug, if it's the first, could an option to provide permanence even with no sessions?
~❯ tmux start-server \; set-option -g exit-unattached off 
~❯ tmux ls 
no server running on /tmp/tmux-1000/default

**Comment by ThomasAdam** [comment]
That's correct.  There's no sessions created, and the command exited.
