### ISSUE TITLE
Potential race condition in join-pane

### ISSUE THREAD

**Issue by ericpruitt** [tmux/tmux#514]
I have a script I use to replicate some of GNU screen's behavior in tmux. One of the functions in the script will select a hidden pane then use join-pane to bring it into view. I've noticed that when I sometimes run this script, the join-pane executes successfully but I get taken to a different window afterward. Here's the traceback from the script's execution when this happened (the name of the function is "join_hidden_pane"):

    + join_hidden_pane -h
    + args=("$@")
    + read pane_id window_flags
    ++ tmux list-panes -s -F '#{pane_id} #{window_flags}'
    + [[ - =~ -$ ]]
    + tmux join-pane -h -s %12
    + return

The tmux binding to run the script is `bind | run-shell "metamux join-hidden-pane -h"`.

Here's an ASCII diagram of what should happen:

    +-----+
    |     |
    |  A  |
    |     |
    +-----+

    *Prefix key, then "|"*

    +-----+
    |  |  |
    |A | B|
    |  |  |
    +-----+

Here is an ASCII diagram of what actually happens:

    +-----+
    |     |
    |  A  |
    |     |
    +-----+

    *Prefix key, then "|"*

    +-----+
    |     |
    |  C  |
    |     |
    +-----+

The reason I think this might be a race condition in tmux is because maybe ~95% of the time, the join-pane works as expected, but I haven't noticed any pattern with the 5% of cases where it does happen. Can you please provide me with some insight and let me know if I'm doing something with tmux incorrectly? I am running tmux compiled from the current Git HEAD of the master branch, 88eb30222150798a33ddc786b785e63f2d0280a3.

**Comment by nicm** [comment]
IIRC join-pane doesn't change current window so are you sure you are not
doing something else at the same time that is causing the window to change?

**Comment by ericpruitt** [comment]
On Mon, Aug 22, 2016 at 06:33:00PM -0700, Nicholas Marriott wrote:
> IIRC join-pane doesn't change current window so are you sure you are not
> doing something else at the same time that is causing the window to change?

I don't have any custom other mappings for the keys immediately
surrounding "|" (I'm using a standard American QWERTY layout), and just
glancing through the default bindings and my configuration file, nothing
stands out to me. I'll poke around some more and see if I can replicate
the problem with the "-v" flag.

Eric

**Comment by ericpruitt** [comment]
I just figured out how to replicate the issue: I have to hit Ctrl+Tab then execute then run the script that executes join_hidden_pane. This is my Ctrl+Tab binding:

    bind-key -n C-Tab if-shell 'test "$(tmux list-panes -F x)" != "x"' \
                               'select-pane -t :.+' 'next-window'

This will cause Ctrl+Tab to go to a new window if there's only one pane in the current window. If there are multiple panes, it makes Ctrl+Tab cycle through them; here are some diagrams I made that explains it:


![](https://www.codevat.com/assets/about-me/tmux-single-pane-mode.png)
![](https://www.codevat.com/assets/about-me/tmux-split-view-mode.png)

I don't understand how that interferes with the next "join-pane" command.

**Comment by ericpruitt** [comment]
The problem seems to be related to "job error" issues because that's what I see in the server logs whenever this happens:

    1471920676.536071 cmdq 0xe692f0: run-shell "metamux join-hidden-pane -h"
    1471920676.536086 preparing state for run-shell "metamux join-hidden-pane -h" (client 0xe79e80)
    1471920676.536230 preparing state for run-shell "metamux join-hidden-pane -h" (client 0xe79e80)
    1471920676.536448 format 'metamux join-hidden-pane -h' -> 'metamux join-hidden-pane -h'
    1471920676.536991 run job 0xe6b5c0: metamux join-hidden-pane -h, pid 12749
    1471920676.538077 job write 0xe6b5c0: metamux join-hidden-pane -h, pid 12749, output left 0
    1471920676.569406 job error 0xe6b5c0: metamux join-hidden-pane -h, pid 12749
    1471920676.569480 job died 0xe6b5c0: metamux join-hidden-pane -h, pid 12749
    1471920676.569493 free job 0xe6b5c0: metamux join-hidden-pane -h

I don't understand what the error is, though; the script is returning with an exit status of 0 as far as I can see.

**Comment by nicm** [comment]
Show me the full log from the problem please; if it is a long log file then tell me where to find it.

**Comment by nicm** [comment]
Where to find the problem in the log file I mean, line number.

**Comment by ericpruitt** [comment]
Sorry for not posting the full log, but I saw there was a lot of data in there, and I was concerned some of it might be sensitive information. After doing some more experimenting, I don't think the job error is related. The problem seems to be related to "renumber-windows" set to "yes;" here's the minimal tmux configuration needed to reproduce the problem:

    set -g renumber-windows yes
    set -g prefix C-f
    set -g default-terminal "tmux-256color"
    set-option -gw xterm-keys on
    set -g default-command "$SHELL"
    bind-key t new-window
    bind | run-shell "metamux join-hidden-pane -h"
    bind q run-shell "metamux pane-buster -r"
    bind-key -n C-Tab next-window

First I ran ` tmux new-window; tmux new-window; tmux new-window; tmux new-window; tmux new-window; tmux new-window` then I hit Ctrl+Tab a few times and then I hit Ctrl+F then `|`. I have attached the logs with some environment variables redacted. Please let me know if there's any other information you need.

[tmux-client-30924.txt](https://github.com/tmux/tmux/files/435983/tmux-client-30924.txt)
[tmux-server-30928.txt](https://github.com/tmux/tmux/files/435984/tmux-server-30928.txt)

**Comment by nicm** [comment]
Does this fix it? [x.diff.txt](https://github.com/tmux/tmux/files/436494/x.diff.txt)

**Comment by ericpruitt** [comment]
No, I still have the same problem with that patch applied. I'm not sure if this will helps but I am currently using this as a work around:

        tmux set renumber-windows no
        tmux join-pane -s "$src" "$@"     # <--- Previously, this was the only line in the function.
        tmux move-window -r
        tmux set renumber-windows yes

**Comment by nicm** [comment]
Are you sure you restarted tmux entirely after rebuilding with the diff?

**Comment by ericpruitt** [comment]
Yes, I am sure. I repeated the process again just now to make sure:

    tmux-src$ git log -1
    tmux-src$ git log -1 | cat
    commit 88eb30222150798a33ddc786b785e63f2d0280a3
    Merge: baf1550 43f292b
    Author: Thomas Adam <thomas@xteddy.org>
    Date:   Mon Aug 22 22:01:13 2016 +0100
    
        Merge branch 'obsd-master'
    tmux-src$ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    nothing to commit, working directory clean
    tmux-src$ wget -qO- https://github.com/tmux/tmux/files/436494/x.diff.txt | patch
    patching file session.c
    tmux-src$ make
    depbase=`echo cmd-string.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"2.3\" -DPACKAGE_STRING=\"tmux\ 2.3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"2.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_CURSES_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NCURSES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_TERM_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_PRCTL=1 -DHAVE_SYSCONF=1 -DHAVE_CFMAKERAW=1 -DHAVE_B64_NTOP=1 -DHAVE_FORKPTY=1 -DHAVE_DAEMON=1 -DHAVE_SETENV=1 -DHAVE_ASPRINTF=1 -DHAVE_STRCASESTR=1 -DHAVE_STRSEP=1 -DHAVE_CFMAKERAW=1 -DHAVE_OPENAT=1 -DHAVE_DECL_OPTARG=1 -DHAVE_DECL_OPTIND=1 -DHAVE_DECL_OPTRESET=0 -DHAVE_BSD_TYPES=1 -DHAVE___PROGNAME=1 -DHAVE_PROGRAM_INVOCATION_SHORT_NAME=1 -DHAVE_PR_SET_NAME=1 -DHAVE_PROC_PID=1  -I.   -I/usr/include/ncursesw  -I/home/ericpruitt/projects/static-tmux/tmux-src/../libevent/build/include -DTMUX_CONF="\"/etc/tmux.conf\"" -DDEBUG -iquote.    -I/home/ericpruitt/projects/static-tmux/tmux-src/../libevent/build/include -D_GNU_SOURCE -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes    -MT cmd-string.o -MD -MP -MF $depbase.Tpo -c -o cmd-string.o cmd-string.c &&\
    mv -f $depbase.Tpo $depbase.Po
    depbase=`echo session.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"2.3\" -DPACKAGE_STRING=\"tmux\ 2.3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"2.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_CURSES_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NCURSES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_TERM_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_PRCTL=1 -DHAVE_SYSCONF=1 -DHAVE_CFMAKERAW=1 -DHAVE_B64_NTOP=1 -DHAVE_FORKPTY=1 -DHAVE_DAEMON=1 -DHAVE_SETENV=1 -DHAVE_ASPRINTF=1 -DHAVE_STRCASESTR=1 -DHAVE_STRSEP=1 -DHAVE_CFMAKERAW=1 -DHAVE_OPENAT=1 -DHAVE_DECL_OPTARG=1 -DHAVE_DECL_OPTIND=1 -DHAVE_DECL_OPTRESET=0 -DHAVE_BSD_TYPES=1 -DHAVE___PROGNAME=1 -DHAVE_PROGRAM_INVOCATION_SHORT_NAME=1 -DHAVE_PR_SET_NAME=1 -DHAVE_PROC_PID=1  -I.   -I/usr/include/ncursesw  -I/home/ericpruitt/projects/static-tmux/tmux-src/../libevent/build/include -DTMUX_CONF="\"/etc/tmux.conf\"" -DDEBUG -iquote.    -I/home/ericpruitt/projects/static-tmux/tmux-src/../libevent/build/include -D_GNU_SOURCE -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes    -MT session.o -MD -MP -MF $depbase.Tpo -c -o session.o session.c &&\
    mv -f $depbase.Tpo $depbase.Po
    depbase=`echo tmux.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"2.3\" -DPACKAGE_STRING=\"tmux\ 2.3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"2.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_CURSES_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_NCURSES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_TERM_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_PRCTL=1 -DHAVE_SYSCONF=1 -DHAVE_CFMAKERAW=1 -DHAVE_B64_NTOP=1 -DHAVE_FORKPTY=1 -DHAVE_DAEMON=1 -DHAVE_SETENV=1 -DHAVE_ASPRINTF=1 -DHAVE_STRCASESTR=1 -DHAVE_STRSEP=1 -DHAVE_CFMAKERAW=1 -DHAVE_OPENAT=1 -DHAVE_DECL_OPTARG=1 -DHAVE_DECL_OPTIND=1 -DHAVE_DECL_OPTRESET=0 -DHAVE_BSD_TYPES=1 -DHAVE___PROGNAME=1 -DHAVE_PROGRAM_INVOCATION_SHORT_NAME=1 -DHAVE_PR_SET_NAME=1 -DHAVE_PROC_PID=1  -I.   -I/usr/include/ncursesw  -I/home/ericpruitt/projects/static-tmux/tmux-src/../libevent/build/include -DTMUX_CONF="\"/etc/tmux.conf\"" -DDEBUG -iquote.    -I/home/ericpruitt/projects/static-tmux/tmux-src/../libevent/build/include -D_GNU_SOURCE -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes    -MT tmux.o -MD -MP -MF $depbase.Tpo -c -o tmux.o tmux.c &&\
    mv -f $depbase.Tpo $depbase.Po
    gcc  -I/home/ericpruitt/projects/static-tmux/tmux-src/../libevent/build/include -D_GNU_SOURCE -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes     -L/home/ericpruitt/projects/static-tmux/tmux-src/../libevent/build/lib                  -L/home/ericpruitt/projects/static-tmux/tmux-src/../libevent/build/include -static   -o tmux alerts.o arguments.o attributes.o cfg.o client.o cmd-attach-session.o cmd-bind-key.o cmd-break-pane.o cmd-capture-pane.o cmd-choose-buffer.o cmd-choose-client.o cmd-choose-tree.o cmd-clear-history.o cmd-command-prompt.o cmd-confirm-before.o cmd-copy-mode.o cmd-detach-client.o cmd-display-message.o cmd-display-panes.o cmd-find.o cmd-find-window.o cmd-if-shell.o cmd-join-pane.o cmd-kill-pane.o cmd-kill-server.o cmd-kill-session.o cmd-kill-window.o cmd-list-buffers.o cmd-list-clients.o cmd-list-keys.o cmd-list-panes.o cmd-list-sessions.o cmd-list-windows.o cmd-list.o cmd-load-buffer.o cmd-lock-server.o cmd-move-window.o cmd-new-session.o cmd-new-window.o cmd-paste-buffer.o cmd-pipe-pane.o cmd-queue.o cmd-refresh-client.o cmd-rename-session.o cmd-rename-window.o cmd-resize-pane.o cmd-respawn-pane.o cmd-respawn-window.o cmd-rotate-window.o cmd-run-shell.o cmd-save-buffer.o cmd-select-layout.o cmd-select-pane.o cmd-select-window.o cmd-send-keys.o cmd-set-buffer.o cmd-set-environment.o cmd-set-hook.o cmd-set-option.o cmd-show-environment.o cmd-show-messages.o cmd-show-options.o cmd-source-file.o cmd-split-window.o cmd-string.o cmd-swap-pane.o cmd-swap-window.o cmd-switch-client.o cmd-unbind-key.o cmd-wait-for.o cmd.o colour.o control.o control-notify.o environ.o format.o grid-view.o grid.o hooks.o input-keys.o input.o job.o key-bindings.o
    key-string.o layout-custom.o layout-set.o layout.o log.o mode-key.o names.o notify.o options-table.o options.o paste.o proc.o resize.o screen-redraw.o screen-write.o screen.o server-client.o server-fn.o server.o session.o signal.o status.o
    style.o tmux.o tty-acs.o tty-keys.o tty-term.o tty.o utf8.o window-choose.o window-clock.o window-copy.o window.o xmalloc.o xterm-keys.o osdep-linux.o  compat/imsg.o compat/imsg-buffer.o compat/closefrom.o  compat/getprogname.o compat/setproctitle.o  compat/strlcat.o compat/strlcpy.o  compat/fgetln.o compat/fparseln.o compat/getopt.o   compat/vis.o compat/unvis.o compat/strtonum.o    compat/reallocarray.o  -lutil -lncurses -ltinfo  -L/home/ericpruitt/projects/static-tmux/tmux-src/../libevent/build/lib -levent  -lresolv
    cmd-string.o: In function `cmd_string_expand_tilde':
    /home/ericpruitt/projects/static-tmux/tmux-src/cmd-string.c:346: warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    /home/ericpruitt/projects/static-tmux/tmux-src/cmd-string.c:332: warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    tmux-src$ mv tmux ~/bin
    tmux-src$ pkill -f tmux

**Comment by nicm** [comment]
Weird, because it fixes the problem for me.

Please give me a tar with the actual simplified scripts and tmux.conf that you are using.

**Comment by ericpruitt** [comment]
I think the issue does become harder reproduce (i.e. it takes longer). Here are the requested files:

[tmux-conf.txt](https://github.com/tmux/tmux/files/439436/tmux-conf.txt)
[metamux.sh.txt](https://github.com/tmux/tmux/files/439435/metamux.sh.txt)

To reproduce the issue, I first run `tmux new-window; tmux new-window; tmux new-window; tmux new-window; tmux new-window; tmux new-window`. This is the general process:

1. Press Ctrl+Tab
2. Ctrl+F then "|"
3. If there is no split, press Ctrl+Shift+Tab to go backward and confirm the bug happened.
4. If there is a split, press Ctrl+F, then "q" to undo it.
5. `GOTO 1`

**Comment by nicm** [comment]
I can't reproduce this with your instructions, can you write a simple script which will reproduce the problem that I can run in a loop?

My diff definitely fixed an issue very like what you are seeing but I can't reproduce it either now...

**Comment by nicm** [comment]
Never mind, looks like I didn't fix the problem completely:

tmux -Ltest -f/dev/null new\; neww\; splitw\; neww -d\; set -g renumber-windows on\; joinp -s:0\; attach

Should preserve the current window, but it does not. So apparently my diff is not enough...

**Comment by nicm** [comment]
OK the problem is that without -d join-pane wants to select the same window, so it saves the index. But with renumber-windows this index might have changed after the join. We can't just search by window instead of index, because there could be multiple links to the same window. So instead, do the select before we kill the empty window so the indexes should be the same. Please try this instead of the previous diff: [x.diff.txt](https://github.com/tmux/tmux/files/439896/x.diff.txt)

**Comment by ericpruitt** [comment]
I was not able to reproduce the problem with that patch; thanks.

**Comment by nicm** [comment]
Applied thanks.
