### ISSUE TITLE
Proposal: session-status-format option and #{session_status}

### ISSUE THREAD

**Issue by ericpruitt** [tmux/tmux#517]
As far as I can tell, there isn't a format option that can be used to get information related to tmux that applies for the whole session. I previously had my own marking command before tmux 1.9 was released where you could mark a pane then upon marking another pane, the panes would be immediately swapped. I am now implementing this in the following manner:

    # Binding to mark and swap panes; if no pane is marked, the shortcut will mark
    # the active pane, but if a pane is already marked, active pane will be swapped
    # with the marked pane.
    bind-key m if-shell 'test -z "$PANE_IS_MARKED"' \
                        "select-pane -m; set-env PANE_IS_MARKED 1" \
                        "swap-pane; select-pane -M; set-env -u PANE_IS_MARKED"

I think it would be nice if the flags of all windows could be accessed using a tmux format string like `#{session_status}` which would effectively be a alternate status line that isn't displayed anywhere. With a feature like that, I could replace the above code with the following:

    bind-key m if-shell 'session_status="#{session_status}"; test -n "${session_status/%%*M*%}" \
                        "select-pane -m" \
                        "swap-pane; select-pane -M"

Since I would be getting the session-status directly from tmux, I would no longer have to rely on environment variables to track state which has the potential of being out of sync with reality. Would you be open to a patch implementing this?

**Comment by nicm** [comment]
Since you are writing a shell script anyway, you can just build it
yourself with lsw -F.

**Comment by ericpruitt** [comment]
That's what I originally had, but it would be nice to avoid an additional fork-exec, and I don't feel like adding these variables would require a lot of changes to tmux since it would literally use the exact same variables and format options as the status line.
