### ISSUE TITLE
Tmux Freezing

### ISSUE THREAD

**Issue by jfelchner** [tmux/tmux#52]
Hey all, I've never had a noticeable issue with tmux before, but today I've had this happen twice.  Not sure what's going on.  The entire tmux process locks up, it pegs the CPU at 100% and won't respond to anything.

![image](https://cloud.githubusercontent.com/assets/285582/8738466/40f9121a-2bf5-11e5-8705-f87e2dd393c3.png)
![image](https://cloud.githubusercontent.com/assets/285582/8738495/a3566642-2bf5-11e5-8b58-fafcce1b6c26.png)
![image](https://cloud.githubusercontent.com/assets/285582/8738468/4f85014a-2bf5-11e5-86f6-0b7aab6b3f39.png)

Here's a gist of the sample that I took while this was happening: https://gist.github.com/jfelchner/c81317e6fcebbbf85eae

Let me know if you need any more information.

**Comment by nicm** [comment]
Am I supposed to guess the tmux version?

This may be the same as issue 14. Can you see if you can reproduce with tmux from git?

**Comment by jfelchner** [comment]
@nicm "Am I supposed to guess the tmux version?" Really? Obviously I forgot to supply it. It would have taken you just as much effort to ask nicely. It's your prerogative to use whatever tone you want on your project, but dang man. :-/

I'm on version 2.0.  I can try compiling it from `master` tomorrow.  Thanks for pointing me to #14 as well.

**Comment by jfelchner** [comment]
@nicm this hasn't happened again since my post. Didn't update or anything. No idea. I don't want to leave this issue open though so I'll close it until if/when it happens again. 

Thanks! 😄👍🏻
