### ISSUE TITLE
Tmux has incorrect when large outputs occurs.

### ISSUE THREAD

**Issue by ChaosEternal** [tmux/tmux#520]
This is REOPEN of #506 #518 

as demand of #506 
I attached the log. this log is generated by the newest code pulled from git and with patch applied.
[tmux-log.zip](https://github.com/tmux/tmux/files/441022/tmux-log.zip)

I don't know why I need to answer a closed Issue, but closing an issue before solving it itself is a weird thing.

**Comment by nicm** [comment]
I you want me to look at this you are not doing yourself any favours, I do not need three issues for one problem, and I do not want to hop between different issues. I decide when issues are closed and when they are opened, not you. Please continue to discuss this on the original issue or not at all.
