### ISSUE TITLE
`tmux ...` commands entered at prompt can confuse two grouped sessions under certain conditions

### ISSUE THREAD

**Issue by qiemem** [tmux/tmux#521]
To reproduce:

1. `tmux new-session -s s1`
2. In `s1`: `tmux new-window`
3. In another terminal: `tmux new-session -s s2 -t s1`.
4. In `s2`: `tmux display-message '#S'` -> will erroneously display `s1`.
5. In `s2`: `tmux split-window` -> will split the window displayed in `s1`, not the one displayed in `s2`.

This only happens when you enter the commands at the terminal command prompt, not when you enter them through tmux's command prompt.

Screenshot:

![screen shot 2016-08-28 at 10 27 02 am](https://cloud.githubusercontent.com/assets/28215/18034725/24c62e5a-6d0a-11e6-90be-f4615868e709.png)

Found in OS X 10.11.6, in iTerm 2 and built-in Terminal, running zsh 5.0.8.

**Comment by nicm** [comment]
This is probably because tmux will prefer the session from TMUX if there
are multiple sessions and the session from TMUX exists. Either specify
the session unambiguously, or unset TMUX.

**Comment by qiemem** [comment]
Great, thanks! Unsetting `TMUX` fixes the issue.

It does seem like this behavior could cause confusion and undesirable behavior, so you might consider changing it. Regardless, prefixing `TMUX=''` to tmux commands is an easy enough workaround, so I'm closing this.

**Comment by qiemem** [comment]
For anyone who stumbles on this, simply blanking out the `TMUX` variable (predictably) messes up when using a custom socket name. This should work in general:

```
TMUX=$(echo $TMUX | cut -d , -f 1,2)
```
