### ISSUE TITLE
Splitting into web view

### ISSUE THREAD

**Issue by Widdershin** [tmux/tmux#525]
Hiya! I'm a huge fan of tmux, and I do almost all of my development work inside of it.

There's one thing that I would really love to be able to do that I can't. I want to be able to open a split pane into a webview with tmux.

I recognize that this is something that would require support from the terminal emulator. With that in mind, here's what I'm thinking.

What if we had a tmux specific terminal emulator, written with web technologies (electron). Ideally there would be a builtin `browse` command that would open a web view in the current pane. Some might be quick to point out the existence of HyperTerm, but as far as I know you can't open web panes inside of tmux, so it's not quite what I want.

As far as I understand, tmux uses a server client architecture. It seems like the server would not need to be changed, but this is effectively a combo terminal emulator + client reimplementation.

Now, I'm happy to have a go at this myself. But I'm unsure where the best place to start is. Is there documentation of the tmux client protocol? Is it feasible to attempt to re-implement the client with web technologies?

(Please feel free to close this issue. I appreciate any advice or insight anyone has)

**Comment by nicm** [comment]
Hi
Control mode is meant for stuff like this.

**Comment by Widdershin** [comment]
Thanks for that advice @nicm, control mode is great for what I'm doing. I managed to get pretty far in the last day or so:

![img](https://github.com/Widdershin/hypertmux/raw/master/example.gif?raw=true)

I do have a question though, and I haven't been able to find the answer in the man page or online. Currently my session size is stuck at 80x24. When I use a normal terminal emulator, resizing the window causes the session in tmux to resize.

How can I advise tmux through control mode of my desired session size? Or am I going about this the wrong way?

**Comment by nicm** [comment]
Use refresh-client -C to set the size of the control client.

**Comment by Widdershin** [comment]
That's perfect, thanks for the quick response.

**Comment by nicm** [comment]
I am closing this but feel free to ask any further questions on the same issue.

**Comment by Widdershin** [comment]
Hiya! I've been getting along but have run into a few barriers.

I want users to be able to use their key bindings as they would in tmux.

I see two possible options, but I'm a bit stuck on both:

1) Send input through to tmux, ideally send-keys would allow passing prefix and bound keys. So far, this does not appear to work, but I could be missing something.
2) Parse the output of `list-keys`, handle input in my web client and send commands to tmux.

I'm stuck on the second approach because I can't figure out how to determine the user's prefix key in control mode. I myself use `C-Space`. Since it's set with `set -g prefix <val>`, I tried `tmux show-window-options -g prefix` but I couldn't see anything.

I would very much appreciate your advice. What's the best way to handle bound keys in control mode?

**Comment by nicm** [comment]
show prefix/show -g prefix should show it.

**Comment by Widdershin** [comment]
That method of showing the prefix works perfectly, thank you.

I've run into another block. How can I keep track of which pane is active?

I would expect that the output of a command like `select-pane -L` would contain which pane is now active. However, that command produces no information inside of the `begin` and `end` lines.

I have considered that I could send a command like `tmux display-message -p '#{pane_id}'`, but how would I know when to send it? Is there any way to be notified?

**Comment by nicm** [comment]
You don't get notifications when the active pane changes, you'd need to
add that to tmux if you really need it.

The %output lines contain the pane number and you will get all output
for panes in the current window, so your active pane doesn't need to
be the same as tmux.

**Comment by nicm** [comment]
You aren't told when the current window changes either...

**Comment by Widdershin** [comment]
So I've managed to implement a control mode notification for when the active pane changes:

https://github.com/Widdershin/tmux/commit/3119b5ba6cb0c6c8853bb6bf4ceed95a3f38319f

I will have a go at doing the same for when the window changes, and I'll make a pull request with all that.

I have to say, it was really easy to read and understand the code that I touched. This is my first time working with C, but it was really clear how I might make this change. Kudos to you and the other contributors for such a readable and clear codebase.

**Comment by nicm** [comment]
OK this is not quite correct.

You will see in notify_add that we increase the reference count of the
window, session, or client when we store it in the notify entry.

This is because notifications can be deferred while commands are run,
which may include commands that destroy the window, session, or client.

The same applies to panes.

Unfortunately panes don't have a reference count at the moment.

I think you will probably need to add one.

In other places we get around this by storing the pane id instead then
checking that the pane still exists with window_pane_find_by_id before
we need to use it, but I think that won't work here because the
notification that needs the pane could be a notification from a command
that has removed the pane...

**Comment by ChristopherJones72521** [comment]
Hi Widdershin, 

Are you able to include installation / usage instructions in your Readme? I love this project but sadly don't yet understand how to implement it.

**Comment by nicm** [comment]
Show me what you have so far for the pane reference count.

Any other problems with control mode let me know and I'll take a look if
I've got time.

**Comment by Widdershin** [comment]
@nicm thank you for the changes to control mode in 2.5 to allow tracking active panes and windows. I had intended to get back to working on this but was overwhelmed with other things. I'll try and get hypertmux using it now 😄
