### ISSUE TITLE
status-right is broken in master

### ISSUE THREAD

**Issue by supermarin** [tmux/tmux#528]
It works properly in 2.2, but it's gone when installing from --HEAD.

To give precise info - it doesn't show up at all, and doesn't throw any error on setting it to something.

**Comment by ThomasAdam** [comment]
Do you get status-right with:

`pkill tmux ; tmux -Lx -f/dev/null`

Works for me, and this has nothing to do with MacOS, AFAICT.  So it's probably something in your config.

**Comment by supermarin** [comment]
My config didn't change, and it got fixed by reinstalling `tmux 2.2`.
I'll double confirm later, but pretty sure it's caused by a tmux source change
