### ISSUE TITLE
Odd clipboard issues with pyobjc on Sierra

### ISSUE THREAD

**Issue by myyc** [tmux/tmux#531]
It's a bit awkward to report this here but maybe some of you has a clue. This bit of Python code:

```python
from AppKit import NSPasteboard
print(NSPasteboard.generalPasteboard())
```

should output a reference to the `pasteboard` object. On OSX 10.12, from within a `tmux` (2.2) session, this doesn't happen (prints `None`). It works fine on 10.11. Did Sierra (10.12) change anything fundamental that `tmux` interacts with, or is it necessarily a `pyobjc` bug?

**Edit**: everything is the same: tmux version, Python version and location, libraries, etc.

**Comment by nicm** [comment]
I don't know what this means. What is this code trying to do? What
should happen and what does happen? What are Sierra and El Capitan
(apart from the obvious)? Duh?

**Comment by myyc** [comment]
It's a bit of `pyobjc` code that should get a reference to OSX's global clipboard (and do whatever you want with it). I have no idea why any Python script launched via `tmux` messes with it with the most recent OSX version.

**Comment by nicm** [comment]
Possibly missing something in the environment but Apple are always
changing stuff, you could ask them.

**Comment by myyc** [comment]
Do you have their phone number? ;)

It's not major anyway, feel free to park it / close it.
