### ISSUE TITLE
Allow appending values to user options

### ISSUE THREAD

**Issue by zeorin** [tmux/tmux#533]
The tmux man page says that tmux supports user options, which may be set to any string:

> tmux also supports user options which are prefixed with a ‘@’.  User options may have any name, so long as they are prefixed with ‘@’, and be set to any string.

And further in the man page it is explained how one can append a value to a string option:

> With -a, and if the option expects a string or a style, value is appended to the existing setting.

This does not work for user options, even though they're strings. I think it could be quite handy for user options to be appendable. One potential use case I know of is the Tmux Plugin Manager: https://github.com/tmux-plugins/tpm/issues/85.

Currently, they're using a regex to parse the `.tmux.conf` file instead of querying the value of the user option, because they'd like to define more than one plugin, but can only use one option name for it. Querying the value of `@plugin` (e.g. `$(tmux start-server\; show-option -gqv "@plugin")`) will just output the last value set to `@plugin`. Even if one includes the `-a` flag to `set-option`.

This is a problem, because any regex will necessarily not be aware of the whole `.tmux.conf` script. I.e. if [`@plugin` is set conditionally](https://github.com/zeorin/dotfiles/blob/5507b9d/.tmux.conf#L73-L77) the regex doesn't recognize the `@plugin` assignment.

Allowing user options to be appendable using `set-option -a @someuseroption` allows for poor man's arrays (in that a script could explode it using some delimeter):
```
set-option -ga @someuseroption ',foo'
set-option -ga @someuseroption ',bar'
set-option -ga @someuseroption ',qux'
```
Should ideally result in:
```
$ echo "$(tmux start-server\; show-option -gqv "@someuseroption")"
,foo,bar,qux
```
User option values could then be constructed in many ways, including as the result of `if-shell` statements, allowing for scripts to do cool things, and not having to (admirably) try their best with regex workarounds.

**Comment by nicm** [comment]
Try this please.

diff --git a/cmd-set-option.c b/cmd-set-option.c
index 356668e..491353a 100644
--- a/cmd-set-option.c
+++ b/cmd-set-option.c
@@ -227,10 +227,11 @@ enum cmd_retval
 cmd_set_option_user(struct cmd *self, struct cmd_q *cmdq, const char *optstr,
     const char *valstr)
 {
-	struct args	*args = self->args;
-	struct session	*s = cmdq->state.tflag.s;
-	struct winlink	*wl = cmdq->state.tflag.wl;
-	struct options	*oo;
+	struct args		*args = self->args;
+	struct session		*s = cmdq->state.tflag.s;
+	struct winlink		*wl = cmdq->state.tflag.wl;
+	struct options		*oo;
+	struct options_entry	*o;
 
 	if (args_has(args, 's'))
 		oo = global_options;
@@ -262,18 +263,22 @@ cmd_set_option_user(struct cmd *self, struct cmd_q *cmdq, const char *optstr,
 		}
 		options_remove(oo, optstr);
 	} else {
-		if (valstr == NULL) {
-			cmdq_error(cmdq, "empty value");
-			return (CMD_RETURN_ERROR);
-		}
-		if (args_has(args, 'o') && options_find1(oo, optstr) != NULL) {
+		o = options_find1(oo, optstr);
+		if (args_has(args, 'o') && o != NULL) {
 			if (!args_has(args, 'q')) {
 				cmdq_error(cmdq, "already set: %s", optstr);
 				return (CMD_RETURN_ERROR);
 			}
 			return (CMD_RETURN_NORMAL);
 		}
-		options_set_string(oo, optstr, "%s", valstr);
+		if (valstr == NULL) {
+			cmdq_error(cmdq, "empty value");
+			return (CMD_RETURN_ERROR);
+		}
+		if (o != NULL && args_has(args, 'a'))
+			options_set_string(oo, optstr, "%s%s", o->str, valstr);
+		else
+			options_set_string(oo, optstr, "%s", valstr);
 	}
 	return (CMD_RETURN_NORMAL);
 }
diff --git a/options.c b/options.c
index df79ac4..cd3bd8e 100644
--- a/options.c
+++ b/options.c
@@ -128,19 +128,23 @@ options_set_string(struct options *oo, const char *name, const char *fmt, ...)
 {
 	struct options_entry	*o;
 	va_list			 ap;
+	char			*s;
 
+	s = NULL;
 	if ((o = options_find1(oo, name)) == NULL) {
 		o = xmalloc(sizeof *o);
 		o->name = xstrdup(name);
 		RB_INSERT(options_tree, &oo->tree, o);
 		memcpy(&o->style, &grid_default_cell, sizeof o->style);
 	} else if (o->type == OPTIONS_STRING)
-		free(o->str);
+		s = o->str;
 
 	va_start(ap, fmt);
 	o->type = OPTIONS_STRING;
 	xvasprintf(&o->str, fmt, ap);
 	va_end(ap);
+
+	free(s);
 	return (o);
 }

**Comment by nicm** [comment]
[x.diff.txt](https://github.com/tmux/tmux/files/475755/x.diff.txt)

**Comment by zeorin** [comment]
@nicm that works, thanks! Would you be able to get this merged into mainline tmux?

For reference (after applying this patch):

`~/.tmux.conf`:
```
# Testing user options appendability
set -ga @plugins ',tmux-plugins/tpm'
set -ga @plugins ',tmux-plugins/tmux-sensible'
set -ga @plugins ',NHDaly/tmux-scroll-copy-mode'
```
```
$ killall tmux
```
In a new tmux session:
```
$ echo "$(tmux start-server\; show-option -gqv "@plugins")"
,tmux-plugins/tpm,tmux-plugins/tmux-sensible,NHDaly/tmux-scroll-copy-mode
```

**Comment by nicm** [comment]
Applied thanks.
