### ISSUE TITLE
Double-width characters sometimes show as blank

### ISSUE THREAD

**Issue by sphaugh** [tmux/tmux#535]
```
# only skipped commits left to test
# possible first bad commit: [d4eeeb5498822d4330f19534f5b25b70589aec1f] Merge branch 'obsd-master'
# possible first bad commit: [0f73af876f1222000a9eea76c70ae9a51ecb95e1] Don't update cells in each block of data read from a pane immediately, instead track them as change (dirty) and update them once at the end, saves much time if repeatedly writing the same cell. Also fix comparison of cells being equal in a few places (memcmp is not enough).
# possible first bad commit: [1fd6ca2260bc738f1e467e7e32d03cc225327ebf] Instead of representing colours in several different forms with various cell flags, convert to use an int with flags marking 256 or RGB colours in the top byte (except in cells, which we don't want to make any bigger). From Brad Town.
```

bad:
![2016-09-17-002236_848x480_scrot](https://cloud.githubusercontent.com/assets/8660255/18606178/47c8ff3c-7c6d-11e6-9342-af691b6e359a.png)

good:
![2016-09-17-002245_848x480_scrot](https://cloud.githubusercontent.com/assets/8660255/18606179/47cd5122-7c6d-11e6-8f9e-3b0af0f6c03a.png)

**Comment by hchbaw** [comment]
I've encountered a similar problem, too.

Here is a perl script to reproduce:
https://gist.githubusercontent.com/hchbaw/07d31d48d9688cff17f94610e63bebaf/raw/69cbe4462266f8f1c307d7f782619e76ee73255a/pl.pl
It is small enough, so I've pasted blow:
```perl
#!/usr/bin/env perl

{
  local $|=1;

  print " あaいb";
  sleep 1.0;
  print "\r";
  print "あaいb_";
  print "\n";
}

{
  # do above block's prints in one go
  print " あaいb\rあaいb_\n";
}
```

This script shoud finally print below:
```
あaいb_
あaいb_
```
But on tmux, it print as follows: (double-width characters are show as blanks)
```
  a  b_
  a  b_
```

I'm not 100% sure that my problem is exact same as @sphaugh's though.

**Comment by hchbaw** [comment]
I made a below patch which backs out the hunk (https://github.com/tmux/tmux/commit/36ab4c7c49d8ffbde113048acb8a6a05ceb00fdc#diff-6aac0f3b802ca7449235400ab53b7771L1091) in this commit (36ab4c7c49d8ffbde113048acb8a6a05ceb00fdc) to fix this problem:

```diff
diff --git a/screen-write.c b/screen-write.c
index 94ce359..5585342 100644
--- a/screen-write.c
+++ b/screen-write.c
@@ -1270,15 +1270,13 @@ screen_write_overwrite(struct screen_write_ctx *ctx, struct grid_cell *gc,
 	 * Overwrite any padding cells that belong to a UTF-8 character
 	 * we'll be overwriting with the current character.
 	 */
-	if (gc->data.width != 1 || gc->flags & GRID_FLAG_PADDING) {
-		xx = s->cx + width - 1;
-		while (++xx < screen_size_x(s)) {
-			grid_view_get_cell(gd, xx, s->cy, &tmp_gc);
-			if (~tmp_gc.flags & GRID_FLAG_PADDING)
-				break;
-			grid_view_set_cell(gd, xx, s->cy, &grid_default_cell);
-			done = 1;
-		}
+	xx = s->cx + width - 1;
+	while (++xx < screen_size_x(s)) {
+		grid_view_get_cell(gd, xx, s->cy, &tmp_gc);
+		if (~tmp_gc.flags & GRID_FLAG_PADDING)
+			break;
+		grid_view_set_cell(gd, xx, s->cy, &grid_default_cell);
+		done = 1;
 	}
 
 	return (done);
```
(Above patch is same as https://gist.githubusercontent.com/hchbaw/07d31d48d9688cff17f94610e63bebaf/raw/844074506b42113ca3513d57cde23c8fe1d5d9f6/patch.patch)


Btw on the commit d4eeeb5498822d4330f19534f5b25b70589aec1f which @sphaugh has shown, I did `git reset --hard d4eeeb549~1` and looked into a bit. At a glance, it prints correct characters as long as entering the copy-mode. If tmux enters the copy-mode, double-widths characters are shown as blanks, ugh.

**Comment by nicm** [comment]
This script works fine for me. Are you using OS X?

**Comment by hchbaw** [comment]
I'm very sorry, I reported without any informations.

No, I'm using Linux (Debian) here. I've checked the tip of github's master (27591570c4a6d1142e0403e209106326a45b859e) on xterm.

Here is a figure (27591570c4a6d1142e0403e209106326a45b859e):
![blank](https://gist.githubusercontent.com/hchbaw/07d31d48d9688cff17f94610e63bebaf/raw/2227fc483748e407032f73fb389698927de711c1/2016-09-28-204136_484x355_scrot.png)

On the other hand tmux-2.2, it works fine:
![ok](https://gist.githubusercontent.com/hchbaw/07d31d48d9688cff17f94610e63bebaf/raw/2227fc483748e407032f73fb389698927de711c1/2016-09-28-204306_484x355_scrot.png)

**Comment by nicm** [comment]
Please kill tmux then run tmux -vvvv new then reproduce and send me the
server log file from the current directory.

**Comment by hchbaw** [comment]
I've created server's log file here:
https://gist.githubusercontent.com/hchbaw/07d31d48d9688cff17f94610e63bebaf/raw/364a08f73dbe93cd1bc7577a475c8fd3440adada/tmux-server-13344.log

(I've tried to type almost same stuff as above images.)

**Comment by nicm** [comment]
can you give me the corresponding tmux-out-13344.log file as well please?

**Comment by nicm** [comment]
Never mind, just managed to reproduce it.

**Comment by nicm** [comment]
When we are clear padding we need to get rid of padding for any characters that are overlapping with the new character - at the moment we only do it if the existing character overlaps with the first cell of the new one. So if we have cells xy and we are writing ab, we currently only clear if x is replacing a or b, not if y is replacing a. The easiest way to do this is just to do the overwrite check for all characters with width > 1 - it isn't the most efficient but they are the vast minority, the important thing is not to do the loop for width == 1 characters.

Anyway, try this please: [x.diff.txt](https://github.com/tmux/tmux/files/498300/x.diff.txt)

**Comment by hchbaw** [comment]
I confirmed. It works fine.

Thank you very much!

**Comment by sphaugh** [comment]
It fixes the issue for me as well.
