### ISSUE TITLE
Set prefix to S-F7, tmux recognize Shift F7 as prefix, but not F19

### ISSUE THREAD

**Issue by leira** [tmux/tmux#536]
On my mac, I mapped Caps Lock to F19, and used it as a dedicated tmux prefix key with setting
```
set-option -g prefix S-F7
```

I recently setup an arch linux box,  I mapped Caps Lock to F19 using xmodmap, and want to using tmux in termite with the same setting. But when I press F19 key in tmux, it simply print '[33~', rather than take it as prefix. Shift F7 works, though.

Is there any extra settings needed to make it work in termite?

**Comment by nicm** [comment]
Are they the same tmux version?

**Comment by leira** [comment]
I used 2.1 and 2.3 on Mac, both worked. On Arch Linux I'm using 2.2.

**Comment by nicm** [comment]
And is TERM the same?

**Comment by leira** [comment]
$TERM is 'screen-256color' on Mac, and 'tmux-256color' on Linux.

**Comment by nicm** [comment]
tmux doesn't have separate F19 and S-F17 keys, they are the same. Please run tmux like this:

tmux -Ltest -f/dev/null -vvvv new

Then press both of the keys that don't work, then exit tmux and send me the tmux-server-*.log file from the current directory.

**Comment by leira** [comment]
Sorry, busy week, didn't have the chance to collect the information...

On Mac, $TERM is xterm-256color outside of tmux, and screen-256color inside tmux.

On LInux, $TERM is xterm-termite outside of tmux, and tmux-256color inside tmux. I'm using termite BTW.

I ran sed -n l on Mac, F19 and Shift-F7 print the same output ^[[18;2~.

```fish
mac ~> sed -n l
^[[18;2~
\033[18;2~$
^[[18;2~
\033[18;2~$
^C⏎ 
```

While on Linux inside termite without tmux, F19 and Shift-F7 print differently. F19 prints out ^[[33~. Shift-F7 prints out ^[[18;2~.

```fish
~> sed -n l
^[[33~
\033[33~$
^[[18;2~
\033[18;2~$
^C⏎
```

On Linux inside tmux with termite, S-F7 is set to prefix, double tap S-F7 to send S-F7. Both F19 and S-F7 print out ^[[33~, but only S-F7 works as prefix key... Set prefix to other keys, test again, give the same result.

```tmux
set-option -g prefix S-F7
bind-key S-F7 send-prefix
```

```fish
~> sed -n l
^[[33~
\033[33~$
^[[33~
\033[33~$
^C⏎
```


Then I ran `tmux -Ltest -f/dev/null -vvvv new` as you suggested, it turned out, there were difference between F19 and S-F7 after all, (\033[33~) vs (\033[18;2~). I don't know what need to be changed to support F19 as prefix key. log file is attached.

```
1537:1475559908.261830 keys are 1 (F)
1575:1475559908.813876 keys are 1 (1)
1596:1475559909.013925 keys are 1 (9)
1625:1475559911.398201 keys are 1 (\r)
1747:1475559913.229957 keys are 5 (\033[33~)
1754:1475559913.230084 keys are 3 (33~)
1760:1475559913.230141 keys are 2 (3~)
1766:1475559913.230193 keys are 1 (~)
1808:1475559914.670186 keys are 1 (\r)
2155:1475559919.150092 keys are 1 (S)
2214:1475559919.398158 keys are 1 (h)
2252:1475559919.550123 keys are 1 (i)
2275:1475559919.686038 keys are 1 (f)
2304:1475559919.957938 keys are 1 (t)
2331:1475559921.053849 keys are 1 (-)
2354:1475559921.357905 keys are 1 (F)
2381:1475559921.733840 keys are 1 (7)
2408:1475559923.021867 keys are 1 (\r)
2516:1475559924.857525 keys are 7 (\033[18;2~)
2519:1475559924.857542 keys in list: 0x900000000034
2560:1475559925.865649 keys are 1 (\r)
2682:1475559930.457804 keys are 1 (\004)
```

[tmux-server-10070.log.txt](https://github.com/tmux/tmux/files/507780/tmux-server-10070.log.txt)

**Comment by nicm** [comment]
Since 2056a9ef9e91996c294b5db0a3d01ed415e95e56 in 2014, tmux only
supports S-F7, it doesn't support F19 (on most terminals they are the
same).

It will expect whatever is in TERM outside tmux as S-F7, for xterm that
is:

$ TERM=xterm-256color tput kf19|cat -v
^[[18;2~

xterm-termite must be a local extension, it is not in the ncurses
terminfo I have here, but whatever it contains for kf19 is what tmux
will expect for S-F7.

**Comment by leira** [comment]
I've filed issues with termite (https://github.com/thestinger/termite/issues/414) and vte (https://bugzilla.gnome.org/show_bug.cgi?id=773444). They were both considered as non-issue.

I do agree with @egmontkob that "the current escape sequences allow an app to differentiate all of F7, F9, F19, Shift+F7, Shift+F9, Shift+F19 and so on from each other. In your proposed one F19 would generate the same as Shift+F7. As such, I believe the current behavior is the better one"

For change https://github.com/tmux/tmux/commit/2056a9ef9e91996c294b5db0a3d01ed415e95e56, I tried to search an issue reported here which was fixed by this change, but couldn't find one. So what's the rationale behind this change? What kind of issue was this change trying to solve?

I understand this change might want to give applications inside tmux the convenience to not differentiate F19 and Shift-F7. If that's the case, shouldn't tmux acting like an adaptor, adapting both F19 (^[[33~) and Shift-F7 (^[[18;2~) into Shift-F7 (^[[18;2~) for applications, rather than pretend such difference never exist?

Thanks~

**Comment by egmontkob** [comment]
@leira It would be great if you could please ask Thomas why xterm sends 33 whereas terminfo contains 18;2. You should probably reach him via the mailing list at https://lists.gnu.org/mailman/listinfo/bug-ncurses so that we can all publicly see it :)
