### ISSUE TITLE
finer control of resize-pane

### ISSUE THREAD

**Issue by benkinooby** [tmux/tmux#537]
Hi,

## Issue
when resizing panes I can not control on what side of the selected pane the resize will happen.

### Example
A window is split into 3 panes (left, center, right). Set "right" to width 80. Now try to set "center" to width 90 and "left" to whatever horizontal space is available. Resizing "center" adds/removes space from "right" (messing up the width just set for "right") instead of "left".

## proposed solution
Allow negative values for resize-pane -LRUD:
resize-pane -L +3 (increase width of selected pane by 3 units on the left)
resize-pane -L -3 (decrease width of selected pane by 3 units on the left)
-RUD accordingly.

A similar scheme may be adopted for resize-pane -xy:
resize-pane -x +80 (set width of selected pane to 80, keeping the left side of the pane fixed)
resize-pane -x -80 (set width of selected pane to 80, keeping the right side of the pane fixed)

What do you think about this proposal?

**Comment by nicm** [comment]
Sounds fine.

**Comment by benkinooby** [comment]
I had a quick glance at the code and noticed that your pane-logic works hierarchically (i.e. parent/child panes). Would I need to introduce something that would give tmux a concept of "to the left / to the right" or can you think of a way to express this with the currently available structures?


> Sounds fine.
>

**Comment by ThomasAdam** [comment]
@benkinooby -- that depends on the layout; see layout.c
