### ISSUE TITLE
Mouse wheel no longer works with TERM=tmux-256color

### ISSUE THREAD

**Issue by hobarrera** [tmux/tmux#538]
I just configured tmux to use italics by switching `TERM` from `screen-256color` to `tmux=256color`:

    set -g default-terminal tmux-256color

With this change alone, the mouse stopped working as expected. Noticeably, I used my wheel to scroll inside vim:

    set mouse -a

With this change, scrolling no longer works. Moving the mouse wheel does nothing.  
Also, clicking inside vim formerly allowed me to select text using vim's text selection capabilities. It now selects text à la tmux.

My `tmux.conf` includes `set -g mouse on`, since I frequently use mouse events for other things _outside_ vim.

Is this an expected change, and have I skipped configuring something else, or is this a bug of some sort?

---

In case it matter, my `tmux.conf` is [here](https://gitlab.com/hobarrera/dotfiles/blob/aacfb09f06c59bcf361b2fa7db2f4e4708673c88/home/.config/tmux/tmux.conf), and `vimrc` is [here](https://gitlab.com/hobarrera/dotfiles-vim/blob/master/home/.vim/vimrc)

**Comment by nicm** [comment]
vim must be looking at TERM to determine how it accepts mouse input,
because tmux does not change anything except italics when you set
default-terminal.

**Comment by hobarrera** [comment]
Thanks for the fast reply.

I'm not entirely sure what this means though (or rather, how I'd go around to having a behaviour similar as to what I did with `set -g default-terminal scree-256color`).

Do I need to reconfigure something on the tmux side, or the vim side?

**Comment by nicm** [comment]
vim

**Comment by hobarrera** [comment]
Sorry to be such a nuisance, but, what exactly should I be looking for here?

When I click-drag on vim (or , I get tmux's text selection (rather than vim's). Is vim even getting the mouse event?

**Comment by nicm** [comment]
No, it is probably not asking for the mouse to be sent.

I do not know how much clearer I can be: tmux does not change anything
except italics when you set default-terminal, so vim must be looking at
TERM and changing its behaviour.

**Comment by nicm** [comment]
Does running

   TERM=screen-256color vim

work?

**Comment by hobarrera** [comment]
Yes, `TERM=screen-256color vim` makes scrolling work fine.

**Comment by nicm** [comment]
Right then. Look at your vim config.

**Comment by hobarrera** [comment]
Thanks again!

I dug up on vim's help guided by what you mentioned, and found that vim tries to recognize the mouse based on `$TERM`.

`set ttymouse=xterm` (on vim) fixes the issue. Since vim has a few hardcoded term which it recognizes to do this automatically (including screen), I'll report this there, so maybe it can behave properly with tmux out-of-the-box as well.

Again, thanks for your patience, and for tmux!
