### ISSUE TITLE
list-panes doesn't work if target is in another session

### ISSUE THREAD

**Issue by thomasjachmann** [tmux/tmux#54]
I tried to do something in all panes of all windows of all sessions in tmux:

```bash
for session in `tmux list-sessions -F '#{session_id}'`; do
  for window in `tmux list-windows -t $session -F '#{window_id}'`; do
    for pane in `tmux list-panes -t $window -F '#{pane_id}'`; do
      echo $session $window $pane
    done
  done
done
```

```list-sessions``` and ```list-windows``` works but ```list-panes``` doesn't. Let's say I have the following setup:

* session $0
  * window @0
    * pane %0
* session $1
  * window @1
    * pane %1
  * window @2
    * pane %2
    * pane %3

When I execute the script above in pane %0, the result depends on whether window @1 or @2 is active in session $1.

window @1 is active in session $1:
$0 @0 %0
$1 @1 %1
$1 @2 %1

window @2 is active in session $1:
$0 @0 %0
$1 @1 %2
$1 @1 %3
$1 @2 %2
$1 @2 %3

So: ```list-panes``` always lists the panes of the currently active window when you try to make it list the panes of a window in another session. If the script above is executed in pane %1, everything works fine, but just since session $0 only has one window.

I would expect (in both cases):
$0 @0 %0
$1 @1 %1
$1 @2 %2
$1 @2 %3

Versions used:
tmux 2.0 (via Homebrew)
Mac OS X 10.9.5 (13F1077)

**Comment by thomasjachmann** [comment]
Argh, just tried it with the current master and it works as expected. Sorry, should have tried that before posting an issue.

**Comment by nicm** [comment]
lsp -t is a window unless you also give -s, so you want lsp -st $window.

But you can do this instead:

tmux lsp -aF'#{session_id} #{window_id} #{pane_id}'|while read s w p; do something; done

**Comment by nicm** [comment]
Oh yes it should work with the new target parsing code too even without -s. Maybe we could make -s a noop.

**Comment by thomasjachmann** [comment]
Also specifying -s didn't work, that listed all panes of the current session for all windows.

Specifying -a even works in 2.0 and avoids nested loops, thanks!

BTW, I'm impressed by your fast response!
