### ISSUE TITLE
Unknown option set-option -g status-utf8 on

### ISSUE THREAD

**Issue by z1003031335** [tmux/tmux#540]
There is a error of unknown option: status-utf8 when executing  tmux source-file ~/.tmux.conf

**Comment by kaatish** [comment]
Does [this](https://github.com/edkolev/tmuxline.vim/pull/57) help?

I think that this option has become obsolete in newer versions on tmux. If you have any .tmux.conf files that contain this option, try to search for this line and remove it. The newer versions of tmux should stop complaining about it. It is possible that older versions of tmux might have an issue without the option though.
