### ISSUE TITLE
Need help on text UI

### ISSUE THREAD

**Issue by echoma** [tmux/tmux#542]
This is not an issue or bug report about tmux. I opened this issue for help.
I am planing to make a text ui tool, but I am new to ncurses.
I am curious about how tmux embed other shell command in its UI. Would any one tell me which source file of tmux should I read to learn about the implementation. Or, would any one tell me the inside mechanism about this tech?

Thanks a lot.

**Comment by nicm** [comment]
tmux doesn't make much use of ncurses, you would be better to look at some
other tools.

**Comment by echoma** [comment]
@nicm So, do you know anything about embeding a shell command?
