### ISSUE TITLE
Problems copying text on Mac OS Sierra

### ISSUE THREAD

**Issue by rtfpessoa** [tmux/tmux#543]
Mac OS Sierra, using latest tmux 2.2 with latest reattach-to-user-namespace 2.5.

**Copy stopped working**

If I do `ls | pbcopy` pbcopy is working but when I use `y`, `Enter` or mouse selection I can never copy the text.
I also enabled both options on iterm 2 to have integration.

I have this settings:

```
# set Zsh as your default Tmux shell
set-option -g default-shell /usr/local/bin/zsh

# Patch for OS X pbpaste and pbcopy under tmux.
set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"

# Setup 'v' to begin selection as in Vim
bind-key -t vi-copy r rectangle-toggle
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy y copy-pipe "pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -t vi-copy Enter
bind-key -t vi-copy Enter copy-pipe "pbcopy"

# Mouse copy
bind-key -t vi-copy MouseDragEnd1Pane copy-pipe "pbcopy"
```

Any ideas?

**Comment by mbbill** [comment]
same here

**Comment by leojrfs** [comment]
+1

**Comment by carlmjohnson** [comment]
I had this problem before I upgraded to Sierra.

One weird thing I noticed was an error message that flashed by about MouseDragEnd1Pane not being a recognized command. I will try to reproduce it.

**Comment by carlmjohnson** [comment]
`/.tmux.conf:47: unknown key: MouseDragEnd1Pane`

**Comment by carlmjohnson** [comment]
It looks like I had `bind-key -t emacs-copy -T root MouseUp1Pane copy-pipe "pbcopy"` but I needed to have `bind-key -t emacs-copy -T root MouseUp1Pane copy-pipe "reattach-to-user-namespace pbcopy"`.

**Comment by rtfpessoa** [comment]
@carlmjohnson that actually works but does not seem the correct way. Or is it?

Aren't we always reattaching to the namespace when copying?

**Comment by carlmjohnson** [comment]
Well, here's a further wrinkle: I use two users on my Mac. On the main user, copying selected text works, but on my secondary user it does not. Maybe something is wrong with reattach?

**Comment by leojrfs** [comment]
`reattach-to-user-namespace` [isnt necessary sometime since el capitan](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/42).

I only used pbcopy ever since, and it worked flawlessly.

**Comment by carlmjohnson** [comment]
I don't think that is correct. I turned off reattach-to-user-namespace and pbpaste stopped working.

**Comment by leojrfs** [comment]
it worked until Sierra... thats the topic here.

If you have a El Capitan computer you can check that pbcopy/paste **without** the reattach-to-user-namespace **works**.

**Comment by keith** [comment]
Another related issue aside from copy is that even with El Cap, you couldn't access anything that uses tccdb for permissions access without reattach-to-user-namespace. But now even with it in Sierra you can no longer access contacts/reminders which I believe is related to the regression seen here. More info about this other stuff here: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/43

**Comment by maletor** [comment]
I have a similar issue where copying from vim inside tmux no longer works. Outside tmux it works fine.

**Comment by cilindrox** [comment]
Same here, piping to `pbcopy` broke after upgrading to Sierra. 

Tmux v2.2 via Homebrew, using the `EVENT_NOKQUEUE=1` setting as [described here](https://github.com/tmux/tmux/issues/475#issuecomment-231527159).

**Comment by joshuamcginnis** [comment]
I was experiencing the same issues, but finally got it fixed. Here's what I did:

* `brew install reattach-to-user-namespace`

Ensure the following `.tmux.conf` is set:
```
set -g default-shell $SHELL 
set -g default-command "reattach-to-user-namespace -l ${SHELL}"
```

In `.vimrc` or `~/.config/nvim/init.vim` (I use Neovim):
```
set clipboard=unnamed
```

Now all is well and I can copy/paste between system <-> vim sessions using vim keybindings and/or system ctrl+c / ctrl+p.

**Comment by maletor** [comment]
It's a regression on macOS. https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/53

This is just so sad for Apple.

**Comment by marciopuga** [comment]
@joshuamcginnis's solution fixed the problem for me! Thanks a lot dude!

**Comment by ryancheung** [comment]
Remember to restart tmux server `tmux kill-server` after `.tmux.conf` updated.

**Comment by olalonde** [comment]
@joshuamcginnis thanks for the fix! worked here too. Seemed to work without the `set clipboard=unnamed` part with vim 8.0.

**Comment by sammilechman** [comment]
```
brew update
brew upgrade vim
brew upgrade tmux
```
This fixed the issue for me.

**Comment by krzkrzkrz** [comment]
But now every new pane that is opened is named `reattach-to-user-namespace`. Is this expected?

**Comment by aleksandrs-ledovskis** [comment]
@krzkrzkrz 

Yes, check below.

[Here](https://github.com/tmux/tmux/blob/5f9ba2f223bcdc4770e56248d5f20e488ee11456/cmd-new-window.c#L75-L78) `argv` is set from `default-command` value. Later on it's [used](https://github.com/tmux/tmux/blob/b9dc855016cf79c8bb8469c272dbc6bca24deadc/names.c#L113) in `char *
default_window_name(struct window *w)`

As far as I can tell there's no option to stop this action & keep using "reattach-to-user-namespace" bar patching and recompiling tmux from source.

**Comment by krzkrzkrz** [comment]
@aleksandrs-ledovskis In the meantime, I'm using `set-window-option -g automatic-rename on` which will automatically rename the name of the pane. Its not the best solution, but an interim, until a proper fix is in place

**Comment by aleksandrs-ledovskis** [comment]
@krzkrzkrz 

Digging around I've found [this](https://github.com/tmux/tmux/issues/611#issuecomment-256816921) workaround

All you need to do is change default command to look like this `"tmux rename-window fish; reattach-to-user-namespace -l $SHELL"` and it will work.

**Comment by keith** [comment]
@krzkrzkrz I created a separate binary that handles whether or not you have reattach-to-user-namespace installed, also with a shorter name just to make the pane names less obnoxious https://github.com/keith/dotfiles/blob/master/bin/tdc

**Comment by aignas** [comment]
Solution by @joshuamcginnis worked for me as well except with one tweak which I found on http://superuser.com/a/413233/118233.

I needed to install `reattach-to-user-namespace` with an option to wrap `pbcopy` and `pbpaste` like so:
```
brew install reattach-to-user-namespace --wrap-pbcopy-and-pbpaste
```

**Comment by nbibler** [comment]
@aignas's solution above worked for me, although there is now a warning thrown during installation:

```
Warning: reattach-to-user-namespace: --wrap-pbcopy-and-pbpaste was deprecated; using --with-wrap-pbcopy-and-pbpaste instead!
```

I have no idea when Homebrew updated to add that warning. But seemingly sometime within the past two weeks. 😄

**Comment by anderson-dan-w** [comment]
Unfortunately @joshuamcginnis solution didn't work for me - I still just get an alarm bell if I try to use ctrl-c inside tmux (whether or not inside vim).

**Comment by zacacollier** [comment]
@anderson-dan-w not sure if this helps: in iTerm 2 - before upgrading to Sierra - I had to disable "Applications in terminal may access clipboard" in order to make clipboard integration work (having followed [this guide](https://evertpot.com/osx-tmux-vim-copy-paste-clipboard/)).

Then, Sierra upgrade borked my tmux / vim clipboard integration, and with the solution posted by  @joshuamcginnis I got it working again. Checked my iTerm preferences and confirmed that I still have that option disabled.

**Comment by xuxiangyang** [comment]
any idea about emacs copy?  I used this config

```
```

**Comment by resoliwan** [comment]
someone who use byobu must attach @joshuamcginnis solution at ~/.byobu/.tmux.conf

**Comment by dvcrn** [comment]
I am still having issues with this. vim clipboard integration works stellar but tmux doesn't. 

Here's how it used to work but not anymore:
```
set-option -g default-shell $SHELL
set-option -g default-command "reattach-to-user-namespace -l $(echo $SHELL)"

# copy-mode
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-pipe "pbcopy"
```

**Comment by brandur** [comment]
@dvcrn I had the same problem. It started working for me after I changed the last two lines of what you have above to this (i.e. invoke `reattach-to-user-namespace` from within the copy action):

```
unbind -t vi-copy Enter
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
```

I originally got my configuration from [this blog post](https://robots.thoughtbot.com/tmux-copy-paste-on-os-x-a-better-future), and the good news is that they seem to have updated it since, so it's probably just a few people with outdated configurations like us who will get stuck on the Sierra upgrade.

**Comment by dvcrn** [comment]
@brandur this worked for me! thanks a lot!

**Comment by SpoBo** [comment]
Here's how to get it working on Sierra for vi bindings with tmux 2.4. Notice the new syntax.

```
setw -g mode-keys vi
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
```

Now it works whenever I 'yank' or drag with the mouse.

**Comment by GhostValk** [comment]
@SpoBo 

bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

I've been wondering for centuries how to copy automatically just by selecting the text (like irc-style) and that line did the trick! Own you a beer bro =D

**Comment by toobulkeh** [comment]
👍 for @SpoBo. The important parts I might've forgotten was upgrading tmux, killing the server, and editing .tmux.conf properly. 🍻

**Comment by 001ben** [comment]
Spent hours trying to figure this out on a recently upgraded sierra, my issue was i was for some reason defining `set-option -g default-shell $SHELL` below where i was calling:
```
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
```
Putting `set-option -g default-shell $SHELL` at the top of my .tmux.conf fixed broken tmux + vim/neovim copy to clipboard functionality

**Comment by aanari** [comment]
Thank you so much @SpoBo - that finally worked for me!

**Comment by johnelliott** [comment]
> Here's how to get it working on Sierra for vi bindings with tmux 2.4. Notice the new syntax.
> ...

still works in macOS Mojave 10.14.2, tmux 2.8 via homebrew 🎉
