### ISSUE TITLE
How to keep the path at the top line of the screen?

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#544]
I personally have two lines as the prompt, one line contains the path, time and git info, another line of prompt contains the real command prompt such as ">>" where I type my commands, the whole prompt is like this:

    user@localhost: /usr/share          [17:48] (master|...)
    >> ls

Can I set the first line fixed at the top line of the window (the info will change of course), like another status bar but at the top of the window, so I can just use "<<" as the prompt and I don't have to see the path line moving all the time?

**Comment by ThomasAdam** [comment]
No.

**Comment by c02y** [comment]
If anyone want this feature, you can use:

    set -g pane-border-status top

it will show info of path in the top line of every pane.

The complete info shown in that line is:
    
    set-option -g pane-border-format "#{?pane_active,#[reverse],}#{pane_index}#[default] ""\"#{pane_title}\""

This line is the default configuration, you don't need to add it into .tmux.conf, but if anyone wants to customize the info shown in that line, just config `pane-border-format` variable.
