### ISSUE TITLE
Background colour slightly off

### ISSUE THREAD

**Issue by hobarrera** [tmux/tmux#545]
If I run `set -g status-bg "#282828"`, the status bar's bg is actually set to `#262626`. I confirmed this by capturing a screenshot of that, and colour-picking the status bar's colour. I noticed this mostly because my actual terminal bg is `#282828`.

I'm running urxvt, inside i3wm. No transparency or fancy stuff involved here.

**Comment by nicm** [comment]
tmux version...?

Did you enable RGB colour?

**Comment by hobarrera** [comment]
tmux 2.2.  

```
$ tmux show -sg terminal-overrides
terminal-overrides "xterm*:XT:Ms=\E]52;%p1%s;%p2%s\007:Cs=\E]12;%p1%s\007:Cr=\E]112\007:Ss=\E[%p1%d q:Se=\E[2 q,screen*:XT,rxvt-unicode-256color:Tc"
$ echo $TERM
tmux-256color
$ tmux info | grep Tc
 197: Tc: (flag) true
```

My tmux.conf includes:

```
set -g default-terminal tmux-256color
set -ag terminal-overrides ",rxvt-unicode-256color:Tc"
```

**Comment by nicm** [comment]
IIRC tmux didn't support RGB colour itself in 2.2, only for applications
running inside.

**Comment by hobarrera** [comment]
Are there any plans for tmux to support this in future? Otherwise, it's not possible for tmux to adapt to the colour themes used by inside apps.
