### ISSUE TITLE
Unable to start tmux - Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by amandogra** [tmux/tmux#547]
I have just install tmux on MacBook using the following command:
```
▶ brew install tmux
```
but when I run it, I get the following:
```
▶ tmux
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Expected in: flat namespace

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Expected in: flat namespace

[1]    36630 trace trap  tmux
```

I tried installing libevent but got the following:
```
▶ brew install libevent
Warning: libevent-2.0.22 already installed
```
Now I can see that my system has `libevent-2.0.22` installed, whereas tmux is looking for some Symbol `_clock_gettime` in libevent-2.0.5, but I don't know how to point it to the correct libevent

In short, how to run `tmux`?

**Comment by ThomasAdam** [comment]
Looks as though there's something missing on your system.  Not tmux-related.

**Comment by amandogra** [comment]
It got solved by OS upgrade. 
For someone who comes to this...
I was on Mac OSX El Capitan, but I upgraded to macOS Sierra.
Then, I executed the following command
```
brew unlink libevent && brew link libevent
```
This fixed my issue.

**Comment by marialivia16** [comment]
@amandogra I have the same issue you described, but your fix didn't help unfortunately.

**Comment by amandogra** [comment]
@marialivia16 try reinstalling libevent and delinking it. The culprit here is Xcode. Are you using the latest Xcode?

**Comment by wenlyin** [comment]
Xcode Version: 8.0 (8A218a)
OS Version :OS X EI Capitan

 I have the same issue

**Comment by noisyboiler** [comment]
Same issue here.
Xcode Version 8.1 (8B62)
OS Version :OS X EI Capitan 10.11.6

**Comment by unicodefreak** [comment]
This helped in my case:

1. Updated brew
2. Removed preexisting libevent and tmux, and their respective bottles
3. Installed tmux via `brew install --build-from-source tmux`

**Comment by noisyboiler** [comment]
@unicodefreak 
many thanks

**Comment by davidhooey** [comment]
@unicodefreak worked for me too. Thanks!

**Comment by irvatoDev** [comment]
**install tmux **

```sh
 brew install --build-from-source tmux
```

```sh
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Expected in: flat namespace

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Expected in: flat namespace

[1]    19608 trace trap  tmux

```

not work

**Comment by lpathak** [comment]
@unicodefreak it worked for me

**Comment by jzck** [comment]
`brew uninstall libevent tmux && brew install --build-from-source tmux`
