### ISSUE TITLE
Pasting text got reordered

### ISSUE THREAD

**Issue by kcwu** [tmux/tmux#548]
The detail:
 1. tmux entered a bad state.
I don't know how to reliable to reproduce this state yet. I have build tmux with debug symbol and will try to debug it next time.
 2. when paste text into tmux and the second character is "n", the "n" will be reordered to end of text. For example, if I copy/paste "android", the pasted text become "adroidn". Any text with 'n' in 2nd apply.

my tmux is running on ubuntu 14.04. tmux is local build using master of June 2016.

I have some testing and believe the problem exists in tmux server. Experiment I have tried:
Doesn't work:
 a. switching window/session/pane doesn't help
 b. detach/attach doesn't help
 c. switch client (rxvt-unicode on linux or iterm2 on mac over ssh) doesn't help 
 d. detech, attach with master of today, doesn't help.
 e. the application inside tmux doesn't matter. (shell, vim, etc.)
And
 f. with the same configuration, starting another tmux server (env TMUX_TMPDIR=/tmp/foo tmux) helps.
 g. the reorder only happen in "application region". It still works well in tmux command-prompt line (prefix-: )

When tmux entered this bad state, it persist. The only solution is abandon this tmux server and create another.

I have encountered this issue two or three times in recent months.

**Comment by nicm** [comment]
Show me your .tmux.conf.

**Comment by kcwu** [comment]
Is it possible to ask tmux list my custom settings?

I used some tmux plugins and it's probably not trivial what setting applied.

**Comment by nicm** [comment]
Can you reproduce without the plugins? Is this the same as issue 362?

**Comment by kcwu** [comment]
Oh, yes! I did use tmux-copycat plugin

```
tmux unbind-key -n n 
```
solved this problem.

So it is indeed a problem of
https://github.com/tmux-plugins/tmux-copycat/issues/99

**Comment by kcwu** [comment]
Thanks!
