### ISSUE TITLE
TMux has wrong size on DEC VT420

### ISSUE THREAD

**Issue by wictory** [tmux/tmux#549]
Hi,

I have a DEC VT420 serial terminal which i run on 132 col x 48 rows. TMux sets itself to 80 cols and 24 rows, which is rather small and I can't find a way to change this default. It seems that the DEC VT420 is not capable of reporting the termsize (at least in any commonly used fashion).

Ncurses accept the COLUMNS and LINES env. variables for setting the terminal size as well as it respects the terminfo. I know this because I made a custom terminfo for 132x48, with which ncurses programs work. Neither of these methods work with tmux.

I also grepped the code for 80 and 24, to change any hardcoded defaults that are in place but it didn't work for me, and I think it would be better with some feedback from people who actually knows how things works :)

**Comment by nicm** [comment]
Did you try using stty rows/columns before starting tmux?

**Comment by wictory** [comment]
I did not, I will try that. Thank you for your quick answer!

**Comment by wictory** [comment]
It does not seem to do the trick. :(

**Comment by wictory** [comment]
When I got the cols/rows properly set with stty it worked. Seems they get reset when I log in.
Thanks for the help!
