### ISSUE TITLE
Implement "palette switching" to allow applications to render properly

### ISSUE THREAD

**Issue by lenormf** [tmux/tmux#552]
Hi,

After some complaints on the [Kakoune issue tracker](https://github.com/mawww/kakoune/issues/762) about colors not being rendered faithfully in a `tmux` session, we came to the conclusion that it would be very convenient if `tmux` implemented OSC 4 commands.

This issue also impacts other software (such as `vim`), basically all the ones that use `ncurses` have to use this "palette switching" trick because `ncurses` does not support true color escapes.

Thanks for your consideration.

**Comment by nicm** [comment]
I think I would accept such a change but I don't plan to do it myself.
