### ISSUE TITLE
Make separate history for command-prompt (:) and rename-window (,)

### ISSUE THREAD

**Issue by fcpg** [tmux/tmux#553]
On the `prefix+: ` command prompt, one can fetch previous commands by hitting `<up>` or `<C-p>`. Unfortunately, the history list also contains input from 'rename-window' commands (`prefix+,`).

Would it be possible to have two distinct history lists, one for commands and one for names/labels?

**Comment by nicm** [comment]
It is not currently possible and TBH I am not convinced it is worth the
complexity even if someone wrote the code.

**Comment by fcpg** [comment]
What about having some readline/linenoise integration on the prompt, then?

**Comment by nicm** [comment]
libedit would be the only acceptable option if you want to look at it.

**Comment by fcpg** [comment]
[This one](http://thrysoee.dk/editline/) ? I'll try and give it a shot.

**Comment by nicm** [comment]
Yes the NetBSD libedit.
