### ISSUE TITLE
Crash with long command

### ISSUE THREAD

**Issue by densefog** [tmux/tmux#555]
Wondering if any progress or solutions have been found for errors like:

`fatal: xsnprintf: overflow`

I found a previous issue that mentioned this would be fixed soon here: #217. My tmux is crashing several times a day trying to kick off a command (rspec) in tmux from vim.

**Comment by nicm** [comment]
Is there some kind of competition to see who can give the least amount of information in a bug report? tmux version? Platform? Length of the command line you are seeing issues with? Logs?

**Comment by densefog** [comment]
Sorry about the lack of detail. Here's some more information:

I've uploaded the content of my client and server log files into a Gist here. This was a partial of the server file but I can provide the full file if you want more. (The server log starts around line 100.)

https://gist.github.com/densefog/2205ab3626a15d916204127e74b08d57

My workflow is to run NeoVim 0.1.5 (originally on Vim 7.4.2210 with same issue) under Tmux 2.3. My Vim is running the `janko-m/vim-test` plugin which integrates into several other plugins to talk with tmux including (vimux, Vim Tmux Runner, Tslime). All of these plugins have failed at some point in time so my guess is the size of the command being sent by vim-test. It looks like the following command is being sent:

```clear; cd '/Users/troys/Desktop/CI/projectxx/projectxx-one'; echo -e './bin/rspec spec/features/user_submits_an_awesomev_special_spec.rb'; ./bin/rspec spec/features/user_submits_an_awesomev_special_spec.rb```

Unfortunately this happens randomly. It definitely happens several times over the course of a day. Sometimes on the 3rd test run and sometimes on the 300th. I've tried the following to try to resolve this:

1. I started out on Tmux 2.2 from Homebrew on:
- OS X El Capitan (10.11.6)
- iTerm 2 (version 3.0.9)
- Running ZSH Shell with oh-my-zsh installed (with lots of plugins)

2. I tried un-installing and re-installing tmux and libevent through Homebrew.
3. I then downloaded the latest tmux from Github and compiled / installed it so it now reports version 2.3. 
4. I now start tmux with -vvvv to get expanded log information (can I do something to get a larger crash report?)
5. I recently saw a discussion on the problem being the zsh `vi-mode` plugin so I uninstalled that but no luck. 

Let me know what other information I can provide. I can easily make changes and run them throughout the day and it will crash at some point. Any compiler flags I could try to build tmux with to get more information? 

Thanks!

**Comment by nicm** [comment]
I can't reproduce this even if I do something like:

    tmux send "`perl -e 'print "x" x 8192'`"

Can you make this change:

--- a/xmalloc.c
+++ b/xmalloc.c
@@ -131,7 +131,7 @@ xvsnprintf(char *str, size_t len, const char *fmt, va_list ap)
 	i = vsnprintf(str, len, fmt, ap);
 
 	if (i < 0 || i >= (int)len)
-		fatalx("xsnprintf: overflow");
+		abort ();
 
 	return i;
 }

Then reproduce and see if tmux generates a core file, then load that
core file into gdb and show me a backtrace ("gdb /path/to/tmux corefile"
then "bt", please use a tmux built from Git master).

**Comment by densefog** [comment]
I'm a bit out of my water here. I rebuilt tmux with the code changes you mentioned, installed gdb from homebrew, had a couple crashes but no core-dumps so ran a command to enable saving core dumps. I now have a core dump but when I try to process it I'm getting a message that `no core file handler recognizes format`. This appears possibly related to this OSX issue:

http://stackoverflow.com/questions/27680712/homebrew-gdb-cant-open-core-file-on-yosemite-10-10

Is it possible to open core dumps from another machine if I get the file to you? It's 672mb so pretty big. Also, I do see some expanded debugging being output as a Diagnostic report that has some backtrace in it here:

https://gist.github.com/densefog/5f6649e0da30e66de6883b8ce1a04e19

**Comment by nicm** [comment]
the backtrace in that log is enough, please try this:

diff --git a/window-copy.c b/window-copy.c
index 320cc3d..cc31c72 100644
--- a/window-copy.c
+++ b/window-copy.c
@@ -1288,7 +1288,8 @@ window_copy_write_line(struct window_pane *wp, struct screen_write_ctx *ctx,
 			xoff = size = xsnprintf(hdr, limit,
 			    "Repeat: %d", data->numprefix);
 		} else {
-			xoff = size = xsnprintf(hdr, limit,
+			/* We don't care about truncation. */
+			xoff = size = snprintf(hdr, limit,
 			    "%s: %s", data->inputprompt, data->inputstr);
 		}
 		screen_write_cursormove(ctx, 0, last);

**Comment by densefog** [comment]
Just wanted to report back that the above fix has been working perfectly for the past week! Thanks for the help!

**Comment by nicm** [comment]
Applied, thanks.
