### ISSUE TITLE
Broken UI with 2-bytes unicode characters (e.g. 🗲🔋)

### ISSUE THREAD

**Issue by edouard-lopez** [tmux/tmux#556]
Here is my status-bar config which use [tmux-plugins/tmux-battery](https://github.com/tmux-plugins/tmux-battery) plugin:

    set -g status-right '#[fg=blue]⬇#{download_speed} #[fg=green]⬆#{upload_speed} #[default] | #{battery_icon}#[fg=black]#{battery_percentage} | #[fg=blue]%a %d %b#[default] ⌚ #[fg=yellow]%H#[default]:#[fg=yellow]%M #[default]'

If I set the icons as follow:

```
set -g @batt_charged_icon "✔"
#set -g @batt_charging_icon "🗲"
set -g @batt_discharging_icon '🔋'
set -g @batt_attached_icon '🔌'
```

The UI broke loose when I unplug my laptop and switch to discharging and the tmux status bar appear twice each time it refresh.

![selection_005](https://cloud.githubusercontent.com/assets/1212392/18348455/b28ea464-75cb-11e6-8700-2e44aec8ea68.png)

If I replace charging icon `🗲` (`U+1F5F2 LIGHTNING MOOD`, UTF-16: `0xD83D 0xDDF2`) by `⚡`  (`U+26A1 HIGH VOLTAGE SIGN`, UTF-16: `0x26A1`) there is no more problem while charging.

### Env

**tmux**
```
$ tmux -V
tmux 2.1
```
**OS**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 18 Sarah
Release:        18
Codename:       sarah
```

**terminal**
```
yakuake --version
Qt: 4.8.7
KDE Development Platform: 4.14.16
Yakuake: 2.9.9
```

### Source

My config can be find at:
* [.tmux.conf](https://github.com/edouard-lopez/dotfiles/blob/fb9137c2ec060ed8c7f13fdf25d8c837ad9d78c6/.tmux.conf) ;
* [.tmux/status-bar.tmux](https://github.com/edouard-lopez/dotfiles/blob/fb9137c2ec060ed8c7f13fdf25d8c837ad9d78c6/.tmux/status-bar.tmux)

### Notes

I'm using Noto Sans as main font but the 2-bytes unicode character are rendered by [Symbola Font](http://users.teilar.gr/~g1951d/).

**related:** tmux-plugins/tmux-battery#31

### Question

Is this a known issue ? How do I fix it?

**Comment by nicm** [comment]
tmux version? Platform?

**Comment by edouard-lopez** [comment]
@nicm I update the question a few minutes after posting.

**Comment by nicm** [comment]
Please run this:

tmux -Ltest -f/dev/null -vvvv new

Print one of the nonworking characters, then exit tmux and send me the tmux-server-*.log file from the current directory.

**Comment by nicm** [comment]
Oh wait, actually, don't do that. Try tmux from Git master first and see if the problem has been fixed already.

**Comment by martinbeentjes** [comment]
As the release notes of 2.3 describe, that version should fix a lot of unicode character issues on macOS. Check if the latest version does fix some of the problems! :)

**Comment by edouard-lopez** [comment]
Same result with 23254f5 (`tmux -V` → `2.4`).

**Comment by nerzhul** [comment]
i have the same problem using powerline like integration (https://github.com/nerzhul/magicline).
The problem appears on terminator & gnome-terminal but not in uxterm which cannot display utf8 in my configuration

**Comment by nicm** [comment]
Please run this:

tmux -Ltest -f/dev/null -vvvv new

Print one of the nonworking characters, then exit tmux and send me the tmux-server-*.log file from the current directory.

**Comment by nerzhul** [comment]
characters are working but status bar create a new line on each tick. 
Here is the char: ⌚

Characters are perfectly working

**Comment by nicm** [comment]
...

**Comment by edouard-lopez** [comment]
@nerzhul `⌚` is `U+231A WATCH` is working for me and it's a one byte (UTF-16: `0x231A`) so not the same issue.

@nicm either [L1936](https://gist.github.com/edouard-lopez/f0b6b06bb167f84f2d99e345ea9fe911#file-tmux-server-1096-log-L1936) or [L2411](https://gist.github.com/edouard-lopez/f0b6b06bb167f84f2d99e345ea9fe911#file-tmux-server-1096-log-L2411)

**Comment by nicm** [comment]
Your platform is reporting both these characters as width 1 but I suspect they should be width 2.

**Comment by nicm** [comment]
Linux appears to be the same here, so this is probably a glibc bug. You can try reporting it to them, or perhaps build tmux with utf8proc.

**Comment by nerzhul** [comment]
The duplicate status line is also present on FreeBSD

**Comment by edouard-lopez** [comment]
did someone confirm the glibc origin?

**Comment by nerzhul** [comment]
i noticed this is a problem with the client running the terminal. At work with archlinux it works properly, at home with archlinux testing i have the problem.
On my Debians i have various tmux versions (Debian 6 to 8), on FreeBSD and OpenBSD i have various versions of tmux too. I connect to those systems using gnome-terminal and SSH. I also have the problem with terminator & SSH but not with UXTerm (which doesn't support UTF8)
