### ISSUE TITLE
Tmux prints list of declared variables on startup or when splitting

### ISSUE THREAD

**Issue by AlexYaruki** [tmux/tmux#558]
When I start tmux or split screen, always list of defined variables are printed on console

`declare -x ANDROID_NDK="/opt/android-ndk"
declare -x CLUTTER_IM_MODULE="xim"
declare -x COMPIZ_CONFIG_PROFILE="ubuntu"
declare -x CUDA_HOME="/usr/local/cuda-7.5"
declare -x DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-gHNw807iPC"
declare -x DEFAULTS_PATH="/usr/share/gconf/ubuntu.default.path"
declare -x DESKTOP_SESSION="ubuntu"
declare -x DISPLAY=":0"
declare -x EVENT_NOEPOLL="1"
declare -x GDMSESSION="ubuntu"
declare -x GDM_LANG="en_US"
declare -x GNOME_DESKTOP_SESSION_ID="this-is-deprecated"
declare -x GNOME_KEYRING_CONTROL=""
declare -x GNOME_KEYRING_PID=""
declare -x GOPATH="/home/zayl/go"
declare -x GOROOT="/usr/local/go"
declare -x GPG_AGENT_INFO="/home/zayl/.gnupg/S.gpg-agent:0:1"
declare -x GTK2_MODULES="overlay-scrollbar"
declare -x GTK_IM_MODULE="ibus"
declare -x GTK_MODULES="gail:atk-bridge:unity-gtk-module"
declare -x HOME="/home/zayl"
declare -x IM_CONFIG_PHASE="1"
declare -x INSTANCE="Unity"
declare -x JAVA_HOME="/opt/jdk"
declare -x JOB="gnome-session"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US"
declare -x LC_ADDRESS="pl_PL.UTF-8"
declare -x LC_IDENTIFICATION="pl_PL.UTF-8"
declare -x LC_MEASUREMENT="pl_PL.UTF-8"
declare -x LC_MONETARY="pl_PL.UTF-8"
declare -x LC_NAME="pl_PL.UTF-8"
declare -x LC_NUMERIC="pl_PL.UTF-8"
declare -x LC_PAPER="pl_PL.UTF-8"
declare -x LC_TELEPHONE="pl_PL.UTF-8"
declare -x LC_TIME="pl_PL.UTF-8"
declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
declare -x LESSOPEN="| /usr/bin/lesspipe %s"
declare -x LOGNAME="zayl"
declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x M2_HOME="/opt/mvn"
declare -x MANDATORY_PATH="/usr/share/gconf/ubuntu.mandatory.path"
declare -x OLDPWD
declare -x PATH="/home/zayl/bin:/home/zayl/.local/bin:/opt/jdk/bin:/opt/mvn/bin:/usr/local/go/bin:/opt/android-ndk:/opt/swift/usr/bin:/usr/local/cuda-7.5/bin:/home/zayl/Scripts/seed:/opt/scala/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin"
declare -x PWD="/home/zayl/Downloads"
declare -x QT4_IM_MODULE="xim"
declare -x QT_ACCESSIBILITY="1"
declare -x QT_IM_MODULE="ibus"
declare -x QT_LINUX_ACCESSIBILITY_ALWAYS_ON="1"
declare -x QT_QPA_PLATFORMTHEME="appmenu-qt5"
declare -x SCALA_HOME="/opt/scala"
declare -x SEED_HOME="/home/zayl/Scripts/seed"
declare -x SESSIONTYPE="gnome-session"
declare -x SHELL="/bin/bash"
declare -x SHLVL="2"
declare -x SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"
declare -x SWIFT_HOME="/opt/swift"
declare -x TERM="screen"
declare -x TMUX="/tmp/tmux-1000/default,10492,1"
declare -x TMUX_PANE="%4"
declare -x UPSTART_EVENTS="started starting"
declare -x UPSTART_INSTANCE=""
declare -x UPSTART_JOB="unity-settings-daemon"
declare -x UPSTART_SESSION="unix:abstract=/com/ubuntu/upstart-session/1000/2583"
declare -x USER="zayl"
declare -x VTE_VERSION="4205"
declare -x WINDOWID="69212836"
declare -x XAUTHORITY="/home/zayl/.Xauthority"
declare -x XDG_CONFIG_DIRS="/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg"
declare -x XDG_CURRENT_DESKTOP="Unity"
declare -x XDG_DATA_DIRS="/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
declare -x XDG_GREETER_DATA_DIR="/var/lib/lightdm-data/zayl"
declare -x XDG_RUNTIME_DIR="/run/user/1000"
declare -x XDG_SEAT="seat0"
declare -x XDG_SEAT_PATH="/org/freedesktop/DisplayManager/Seat0"
declare -x XDG_SESSION_DESKTOP="ubuntu"
declare -x XDG_SESSION_ID="c2"
declare -x XDG_SESSION_PATH="/org/freedesktop/DisplayManager/Session0"
declare -x XDG_SESSION_TYPE="x11"
declare -x XDG_VTNR="7"
declare -x XMODIFIERS="@im=ibus"
`

**Comment by nicm** [comment]
Your shell startup scripts are doing this, probably you have something that ends up evaluating to a plain "declare -x" with no more arguments.

**Comment by AlexYaruki** [comment]
Log that I copied there is not formatted as presented in terminal, each "declare" is in one line. Also, I did not add any of them manually. It may be result of package upgrade.

Which startup scripts ? I am using Ubuntu.

**Comment by nicm** [comment]
I don't know it depends on your shell, if you are using bash try .bash* .profile /etc/bash*.

**Comment by AlexYaruki** [comment]
My stupid mistake. I have script "/etc/profile.d/vars.sh" that declares various variables. One export was incorrectly split in two lines. Sorry for bothering you and thanks for insanely quick replay :)
