### ISSUE TITLE
Tmux 2.3 sets opening directory to '/'

### ISSUE THREAD

**Issue by andyl** [tmux/tmux#559]
I just upgraded from 2.1 to 2.3

In 2.3, when I start tmux, it always sets the opening directory to `/`.

I use the `new_window -c "#{pane_current_path}"` and  `split_window -c "#{pane_current_path}"` commands - those work fine.

My problem is just when tmux starts.  Is there an environment variable or setting that I can use to force the opening directory to `$PWD`??

**Comment by zbits** [comment]
I'm seeing the same thing, compiled for FreeBSD 10.3-release.

**Comment by andyl** [comment]
@zbits thanks for that tip - I also had older (2.1) tmux sessions active.  Looks like killing the old session resolves the problem.
