### ISSUE TITLE
tmux-2.3 status-right not displayed

### ISSUE THREAD

**Issue by Ypnose** [tmux/tmux#560]
Hi there,
Using the following [tmux.conf](https://github.com/Ypnose/dotfiles/blob/master/tmux.conf) with <code>2.3</code> "disables" <code>status-right</code> text (it is not displayed). It was working fine with <code>2.2</code>.
The trick is to use one of the following change:
 - delete <code>status-style</code> option
 - replace <code>default</code> by another color, like <code>red</code>
 - expand <code>status-style</code> option to <code>'bg=default,fg=black'</code>.

I was wondering if this behavior is legit or if it was a regression. What is your opinion?

**Comment by ThomasAdam** [comment]
WFM.

**Comment by Ypnose** [comment]
My "problem" (using the link tmux.conf) occured with tmux-2.3 compiled with glibc 2.24 + ncurses 6.0. It also occurs when tmux-2.3 is statically compiled with musl-1.15 and [netbsd-curses](https://github.com/sabotage-linux/netbsd-curses)-0.1.1.

**Comment by nicm** [comment]
Show me a screenshot please.

**Comment by Ypnose** [comment]
Hi nicm, here the screenshots:
**tmux-2.2:**
![tmux-2.2](https://framapic.org/sfcrPTf4kLAC/4iv9m58ADrb5.png)

**tmux-2.3:**
![tmux-2.3](https://framapic.org/NGSeonC28hDu/4Ty3cWdZnEuw.png)

**Comment by nicm** [comment]
This does appear to be a bug, I can't see where at the moment.

If you give status-style a non-default fg, it works:

set -g status-style fg=white,bg=default

**Comment by nicm** [comment]
This is due to a malfunctioning optimization in screen_write_copy, we should be able to just remove this now. I don't know why this worked before, I guess we were lucky and were drawing it again. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/512413/x.diff.txt)

**Comment by nicm** [comment]
I have applied this, so you can wait for an hour or so then do git pull and see if the problem goes away.

**Comment by Ypnose** [comment]
Thanks to you nicm! You are pretty good. I will try the fix this evening and I report back.

**Comment by Ypnose** [comment]
Good evening nicm, the patch is fine. I thank you for the quick fix. tmux(1) just rocks.

**Comment by nicm** [comment]
Applied, thanks.

**Comment by nicm** [comment]
Er sorry it was already applied, just closed ;_).

**Comment by supermarin** [comment]
@nicm please reopen the issue, as this is still not fixed in HEAD.

OSX 10.11.6
I warned about this before 2.3 release [here](https://github.com/tmux/tmux/issues/528)

![screen shot 2016-10-13 at 4 03 43 pm](https://cloud.githubusercontent.com/assets/627285/19370136/a41e638e-915e-11e6-9601-96ffd2822302.png)

It all *works* in tmux 2.2. After playing with colors, i can confirm that `default` fg color setting breaks the status.

**Comment by nicm** [comment]
Please open a new issue and this time include config, platform, etc.

**Comment by nicm** [comment]
Or just give us your config here, we don't particularly need a new issue.

**Comment by supermarin** [comment]
@nicm here's the minimal required config to reproduce behavior:

```
set-option -g status-bg default
set-option -g status-fg default
set -g status-right "WAT"
```

**Comment by nicm** [comment]
2.3? The fix is not in 2.3. I can't reproduce this on master with this config.

**Comment by Ypnose** [comment]
@supermarin: The issue is already fixed on HEAD. I also applied @nicm patch on top of 2.3 release and using it for a week, without any issues. And BTW, if you build tmux from HEAD, you will now see 2.4 with ```tmux -V``` (bb7cc8e8fd9d797b9b00ab8254e51f25).

**Comment by supermarin** [comment]
@Ypnose thanks for the info, let me try to install from HEAD and will report back

**Comment by supermarin** [comment]
fixed, thanks!
