### ISSUE TITLE
rename-window breaks pane-border-status

### ISSUE THREAD

**Issue by sphaugh** [tmux/tmux#564]
I added the following to my `~/.tmux.conf`:

```
# Show pane status on the border
set-option -g pane-border-status top
set-option -g pane-border-format " #P: #{pane_current_command} "
```

When I rename a window, it seems the pane status stops updating. This might be an intermittent issue? Minimal example:

![pane](https://cloud.githubusercontent.com/assets/8660255/19046535/74c0616c-8963-11e6-86b0-4cc18b20affd.png)

**Comment by nicm** [comment]
When you rename a window, automatic-rename is turned off, I guess you
were getting the status line updated as a side-effect of
automatic-rename. You probably want to adjust your status-interval
instead.
