### ISSUE TITLE
[>=2.2] Separate bell and activity

### ISSUE THREAD

**Issue by schreq** [tmux/tmux#565]
It's not possible anymore to use `window-status-bell-style` and `monitor-activity on` together and have a distinguishable window-status. Now you can only have one of the two, because setting `monitor-activity on` will make bells count as activity instead of a bell. `window-status-bell-style` is only used when monitor activity is off.

Having an audible bell for bells while using monitor-activity is also not possible anymore because bell-on-alert has to be on, which will also ring the bell on activity. This is quite a step backwards from the old behaviour.

**Comment by ThomasAdam** [comment]
It's a lot easier this way.

**Comment by nicm** [comment]
Of course I can only guess what you are doing, but for me it seems to work exactly as intended in the code and the opposite of how you describe (bell-style will override activity-style).

**Comment by nicm** [comment]
I don't see any reason for it to be one or the other, you could try this:

~~~~
--- status.c    12 Sep 2016 15:40:58 -0000      1.150
+++ status.c    5 Oct 2016 15:53:20 -0000
@@ -535,7 +535,7 @@ status_print(struct client *c, struct wi

        if (wl->flags & WINLINK_BELL)
                style_apply_update(gc, oo, "window-status-bell-style");
-       else if (wl->flags & (WINLINK_ACTIVITY|WINLINK_SILENCE))
+       if (wl->flags & (WINLINK_ACTIVITY|WINLINK_SILENCE))
                style_apply_update(gc, oo, "window-status-activity-style");

        text = status_replace(c, wl, fmt, t);

**Comment by schreq** [comment]
Consider the following use case: I have a tmux session for irc where all my irc channels are their own shell script in a seperate tmux window. If my nick gets mentioned my script to monitor a channel will print a \a and the window status number turned red. On normal activity the window status number would turn green.

The new behaviour also makes it impossible to _only_ get a terminal bell when the bell has actually been rung while having monitor-activity.

**Comment by nicm** [comment]
Bell works fine with monitor-activity on, and until you explain what you are actually doing and show your configs we will not be able to help you any further.

**Comment by schreq** [comment]
Stripped down config. Doing `sleep 1;printf "\a"` in a window and then switching to another one will just turn the windows status green. I get no bell either.

```
set -g monitor-activity on

set -g window-status-format '#I'
set -g window-status-current-format '#I'

set -g window-status-style fg=colour240,bg=default

set -g window-status-current-style fg=black,bg=white

set -g window-status-bell-style fg=red,bright,bg=default

set -g window-status-activity-style fg=green,bright,bg=default
```

**Comment by nicm** [comment]
You can only have one fg colour of course. By default bell will win, with
my diff activity will win. The diff only allows you to apply different
attributes for bell and activity, you can't have two fg colours.

**Comment by nicm** [comment]
What tmux version are you using? Your subject line is vague.

I can't reproduce this at all with Git master, so please try that. You will still only be able to set one foreground colour, however.

**Comment by schreq** [comment]
Sorry, I should've stated that I was using 2.2.

I just compiled the latest master and the old behaviour is back <3
