### ISSUE TITLE
Is it possible to query tmux for the id of the pane which is running the command, instead of the active one?

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#567]
I have a script that I want to use to implement a manual method of visually notifying that a long-running script has finished. 

The usage would be like this: 

     make && tmuxalert

`tmuxalert` is a shell script that has some `tmux` commands inside of it which does the following:

1. change the background of the pane to red via tmux: `tmux select-pane -P 'bg=colour124'`
2. prompt for key, and print "Hit any key to dismiss"
3. change back the background color of the pane via tmux

Heres the problem... when we send a command to tmux, it defaults to using the focused pane. this is true usually, but in this particular situation it's precisely the point that I don't want the focused pane, I want the pane the command is running in. 

I've looked in the manpage but it seems like everything that I can use is just implicitly relating to the pane that is in focus. I'm wondering if there's a way to have a CLI `tmux` call retrieve the pane that that terminal is running in without doing crazy tricks.

The "solution" that i just thought up is this: Finding the pty of the term, listing tmux sessions, find it, grab the pane identifier from that list. But I am not sure that it's possible to find this information (the pty) either, I can't find it yet. For example: 

    tmux list-panes -F "#D #{client_tty}"

only yields the values of `#D`, I can't grab the tty's. Upon further testing, it's clear that `client_tty` is exactly what it says on the tin, not the emulated pty that I need.

**Comment by nicm** [comment]
I thought there was a way to do this internally, but if there is I can't remember what it is. You can try this, although not sure about the format name: [x.diff.txt](https://github.com/tmux/tmux/files/518166/x.diff.txt)

(For lsp, you want pane_tty not client_tty, so something like T=$(tty);tmux lsp -F'#{pane_tty} #{pane_id}'|grep ^$T)

**Comment by unphased** [comment]
Awesome, `#{pane_tty}` is the ticket, and this is definitely sufficient for my purposes. Thanks.
