### ISSUE TITLE
synchronize-panes modifier for pane-active-border-style

### ISSUE THREAD

**Issue by Alives** [tmux/tmux#568]
I'd like to be able to change pane-active-border-style if synchronize-panes is enabled so that I know that the current window is synched.

**Comment by nicm** [comment]
You can turn on pane status lines and then put an indicator in there, but there is no scope for modifying styles based on options and I don't see that it is generally particularly useful.

**Comment by Alives** [comment]
So I started using this to set the pane border colors per window so I could determine if sync-panes is enabled or not:

```
bind-key y set-window-option synchronize-panes on \;\
  set-window-option pane-active-border-style fg=red \;\
  set-window-option pane-border-style fg=yellow \;\
  display-message "Sync panes ON"

bind-key Y set-window-option synchronize-panes off \;\
  set-window-option pane-active-border-style fg=green \;\
  set-window-option pane-border-style default \;\
  display-message "Sync panes OFF"
```

There's an issue though.  If I sync panes on window 1 and see the border change to red, then change to another window where sync panes is not set, the border is still red.  This should be a window option, but it seems to be bleeding into the global session for some reason.

Am I doing something wrong here?

**Comment by nicm** [comment]
I can't reproduce this, these key bindings work as expected for me.
