### ISSUE TITLE
pane-border-status not updating from status-interval timer

### ISSUE THREAD

**Issue by orebokech** [tmux/tmux#570]
It seems that in the default configuration, if you enable pane-border-status the text in pane borders gets refreshed by a side effect; if you set status-right to the empty string then they don't get updated when they change, not even from the status-interval timer.

To reproduce, use the following minimal config file:

    set -g pane-border-status top
    set -g status-right ""
    set -g status-interval 1

If you change the window title from inside the pane, the title displayed in the pane border doesn't change after 1 second, it only changes if the windows gets redrawn for some other reason.

I suggest the attached patch, which sets the CLIENT_BORDERS flag when processing CLIENT_STATUS and pane-border-status is enabled to ensure that borders get redrawn along with the status line: [xx.txt](https://github.com/tmux/tmux/files/517944/xx.txt)

**Comment by nicm** [comment]
How about this instead?

Index: status.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/status.c,v
retrieving revision 1.150
diff -u -p -r1.150 status.c
--- status.c	12 Sep 2016 15:40:58 -0000	1.150
+++ status.c	9 Oct 2016 08:11:48 -0000
@@ -158,6 +158,8 @@ status_timer_callback(__unused int fd, _
 
 	if (c->message_string == NULL && c->prompt_string == NULL)
 		c->flags |= CLIENT_STATUS;
+	if (options_get_number(s->curw->window->options, "pane-border-status"))
+		c->flags |= CLIENT_BORDERS;
 
 	timerclear(&tv);
 	tv.tv_sec = options_get_number(s->options, "status-interval");

**Comment by orebokech** [comment]
I tried this first, but then it only updates from the timer.

With my patch it also updates from the window title escape sequence handler (see input_exit_apc()) which is a much more pleasant experience as the title updates immediately, not after 1 (or more) seconds.

**Comment by nicm** [comment]
Hmm I had another look and we already tie together borders and status in
screen-redraw.c (although this is wrong), so your change is probably
OK. But we should fix screen-redraw.c too:

Index: screen-redraw.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/screen-redraw.c,v
retrieving revision 1.37
diff -u -p -r1.37 screen-redraw.c
--- screen-redraw.c	15 Jul 2016 00:42:56 -0000	1.37
+++ screen-redraw.c	9 Oct 2016 08:54:34 -0000
@@ -361,7 +361,7 @@ screen_redraw_screen(struct client *c, i
 	if (pane_status != CELL_STATUS_OFF && (draw_borders || draw_status)) {
 		TAILQ_FOREACH(wp, &w->panes, entry) {
 			if (screen_redraw_make_pane_status(c, w, wp))
-				draw_borders = draw_status = 1;
+				draw_borders = 1;
 		}
 	}
 
@@ -372,7 +372,7 @@ screen_redraw_screen(struct client *c, i
 		screen_redraw_draw_panes(c, top);
 	if (draw_status)
 		screen_redraw_draw_status(c, top);
-	if (pane_status != CELL_STATUS_OFF && (draw_borders || draw_status))
+	if (pane_status != CELL_STATUS_OFF && draw_borders)
 		screen_redraw_draw_pane_status(c, pane_status);
 	tty_reset(tty);
 }
Index: server-client.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/server-client.c,v
retrieving revision 1.188
diff -u -p -r1.188 server-client.c
--- server-client.c	28 Sep 2016 08:30:44 -0000	1.188
+++ server-client.c	9 Oct 2016 08:54:35 -0000
@@ -949,6 +949,7 @@ void
 server_client_check_redraw(struct client *c)
 {
 	struct session		*s = c->session;
+	struct window		*w = s->curw->window;
 	struct tty		*tty = &c->tty;
 	struct window_pane	*wp;
 	int		 	 flags, masked, redraw;
@@ -968,6 +969,10 @@ server_client_check_redraw(struct client
 			redraw = status_redraw(c);
 		if (!redraw)
 			c->flags &= ~CLIENT_STATUS;
+
+		/* Force border redraw if pane status lines are on. */
+		if (options_get_number(w->options, "pane-border-status"))
+			c->flags |= CLIENT_BORDERS;
 	}
 
 	flags = tty->flags & (TTY_FREEZE|TTY_NOCURSOR);

**Comment by nicm** [comment]
Actually no, this is still wrong.

The problem is we have no way to differentiate "draw the borders" and "draw the borders if the status line is on"

**Comment by nicm** [comment]
I think this is better - move the check code into a function screen_redraw_update and:

a) on entry STATUS means check both status line and pane status lines for changes;
b) if status line hasn't changed then STATUS goes off, if pane status line has changed then BORDERS goes on;
c) screen_redraw_screen does less funny business with the flags.

Please take a look: [x.diff.txt](https://github.com/tmux/tmux/files/518196/x.diff.txt)

**Comment by orebokech** [comment]
Yes, much better, thanks!

(Note: 'wp' is now unused in screen_redraw_screen())

**Comment by nicm** [comment]
Great applied thanks.
