### ISSUE TITLE
tmux 2.2 can not display Chinese character 

### ISSUE THREAD

**Issue by springmoonlight** [tmux/tmux#571]
Tmux 1.8 can display Chinese character, but when I update tmux 2.2, the status bar can not display.

**Comment by krader1961** [comment]
Insufficient data. What character? That is, what is the unicode code point? What is your tmux configuration? What do you mean by "status bar can not display"? Can you provide a screenshot of 
the 1.8 behavior and the 2.2 behavior?

The current released version of tmux is 2.3 which includes some changes related to unicode chars. Does the problem still occur with that version or can you build and test using the "git head" code?

**Comment by springmoonlight** [comment]
Thank you so much!

tmux 1.8
![0084983dbaf94187c93a5c04c1aceed5](https://cloud.githubusercontent.com/assets/1595077/19217767/ddffa50a-8e15-11e6-8e7c-0a3bfc7a61b5.png)
tmux 2.3
![e50a640d1b5ad9aec6ea496b4719f588](https://cloud.githubusercontent.com/assets/1595077/19217768/de20cc8a-8e15-11e6-8ce6-068173fc5de5.png)

my configure file is 
> \#### COLOUR (Solarized dark)
> 
> \# default statusbar colors
> set-option -g status-bg black #base02
> set-option -g status-fg yellow #yellow
> set-option -g status-attr default
> 
> \# default window title colors
> set-window-option -g window-status-fg brightblue #base0
> set-window-option -g window-status-bg default
> set-window-option -g window-status-attr dim
> 
> \# active window title colors
> set-window-option -g window-status-current-fg brightred #orange
> set-window-option -g window-status-current-bg default
> set-window-option -g window-status-current-attr bright
> 
> \# pane border
> set-option -g pane-border-fg black #base02
> set-option -g pane-active-border-fg brightgreen #base01
> 
> \# message text
> set-option -g message-bg black #base02
> set-option -g message-fg brightred #orange
> 
> \# pane number display
> set-option -g display-panes-active-colour blue #blue
> set-option -g display-panes-colour brightred #orange
> 
> \# clock
> set-window-option -g clock-mode-colour green #green
> 
> set -g default-command zsh
> set -g base-index 1
> \#set -g status-utf8 on

**Comment by nicm** [comment]
Does it work in tmux from Git master?

**Comment by springmoonlight** [comment]
Thanks, and I tried,  and It does not work. I can not input Chinese character as the session name as well.

**Comment by nicm** [comment]
Please run this:

tmux -vvvLtest -f/dev/null new

Then print one nonworking character, exit tmux and send me the
tmux-server*.log file from the current directory.

**Comment by springmoonlight** [comment]
Thanks a lot.  

My actions follow as below. 
1. ./**tmux** -vvvLtest -f/dev/null new
2. rename the current window (**ctrl + B**, then **comma**)
3. ues default Chinese input method of macOS 10.12 to input "ni", the pinyin of 你，then enter
4. exit

[log.ZIP](https://github.com/tmux/tmux/files/518383/log.ZIP)

**Comment by nicm** [comment]
This is expected, we do not support UTF-8 keys at the command
prompt. Please show me the logs from when the status line is not
displaying the character

**Comment by springmoonlight** [comment]
>  Please show me the logs from when the status line is not
displaying the character

1. the version of tmux that I encounter this problem: **tmux 2.2**
2. the logs of my tmux (the attachment is complete log) : 
```
1476064321.061501 next key is 1 (,) (expired=0)
1476064321.061511 complete key , 0x2c
1476064321.061521 session 0 activity 1476064321.061517 (last 1476064320.790821)
1476064321.061530 session 0 not pasting
1476064321.061540 continuing cmdq 0x7f836f701c20: flags 0, client 0x7f8370800000
1476064321.061554 cmdq 0x7f836f701c20: command-prompt -I #W "rename-window '%%'"
1476064321.061565 preparing state for command-prompt -I #W "rename-window '%%'" (client 0x7f8370800000)
1476064321.061572 cmd_find_current_client: using cmdq 0x7f836f701c20 client 0x7f8370800000
1476064321.061578 cmd_find_client: no target, return 0x7f8370800000
1476064321.061583 preparing -t state: target none
1476064321.061588 preparing -s state: target none
1476064321.061598 preparing state for command-prompt -I #W "rename-window '%%'" (client 0x7f8370800000)
1476064321.061604 cmd_find_current_client: using cmdq 0x7f836f701c20 client 0x7f8370800000
1476064321.061610 cmd_find_client: no target, return 0x7f8370800000
1476064321.061615 preparing -t state: target none
1476064321.061620 preparing -s state: target none
1476064321.061849 format '(rename-window) ' -> '(rename-window) '
1476064321.061939 format '#W' -> 'zsh'
1476064321.062018 screen_write_start: size 238x1, no pane
1476064321.062076 screen_write_stop: 0 of 238 written (dirty 238, skipped 0)
1476064321.062112 @0 active pane not changed
1476064321.062138 @0 active pane not changed
1476064322.567750 keys are 3 (\344\275\240)
1476064322.567777 next key is 3 (\344\275\240) (expired=0)
1476064322.567785 UTF-8 key \344\275\240 0x4f60
1476064322.567789 complete key \344\275\240 0x4f60
1476064322.567795 session 0 activity 1476064322.567792 (last 1476064321.061517)
1476064322.567809 @0 active pane not changed
1476064322.803397 keys are 1 (\r)
1476064322.803414 next key is 1 (\r) (expired=0)
1476064322.803419 complete key \r 0xd
1476064322.803427 session 0 activity 1476064322.803423 (last 1476064322.567792)
1476064322.803444 continuing cmdq 0x7f836f701c20: flags 0, client 0x7f8370800000
1476064322.803450 cmdq 0x7f836f701c20: rename-window zsh
1476064322.803455 preparing state for rename-window zsh (client 0x7f8370800000)
1476064322.803459 cmd_find_current_client: using cmdq 0x7f836f701c20 client 0x7f8370800000
1476064322.803462 cmd_find_client: no target, return 0x7f8370800000
1476064322.803465 preparing -t state: target none
1476064322.803469 cmd_prepare_state_flag: flag t 7 0
1476064322.803473 cmd_find_current_session: have client 0x7f8370800000 (with session)
1476064322.803476 cmd_find_target: target none, type 1
1476064322.803480 cmd_find_target: cmdq 0x7f836f701c20, flags 0
1476064322.803483 cmd_find_target: s=$0
1476064322.803486 cmd_find_target: wl=0 1 w=@0 zsh
1476064322.803489 cmd_find_target: wp=%0
1476064322.803492 cmd_find_target: idx=0
1476064322.803496 preparing -s state: target none
1476064322.803500 preparing state for rename-window zsh (client 0x7f8370800000)

```
[tmux-server-log.ZIP](https://github.com/tmux/tmux/files/518714/tmux-server-log.ZIP)

**Comment by nicm** [comment]
Hi

But this is still at the "(rename-window)" prompt. We don't allow UTF-8
characters at the prompt at the moment.

**Comment by springmoonlight** [comment]
I got it! Thanks a lot! 

By the way, will tmux allow UTF-8 characters at the prompt again?

**Comment by nicm** [comment]
I had forgotten it didn't, I think we should change it but it's not easy.

**Comment by springmoonlight** [comment]
Tmux is so exciting, and thanks for all tmux developers again!

**Comment by nicm** [comment]
Hi

Can you please checkout tmux from Git master and apply this diff: 
[tmux-status-utf-8.diff.txt](https://github.com/tmux/tmux/files/519541/tmux-status-utf-8.diff.txt)

Then rebuild tmux and see if the status line now works.

That is, something like:

git clone https://github.com/tmux/tmux.git
cd tmux
git apply /path/to/tmux-status-utf-8.diff.txt
sh autogen.sh
./configure
make
./tmux new

(You may need to install libevent and libncurses development packages first.)

You may want to install this tmux and use it for a while and let me know if you see any bugs.

**Comment by springmoonlight** [comment]
Wow! It works! And I will use this version. Thanks!

**Comment by nicm** [comment]
I have applied this now, it will be in GitHub soon and then in the next tmux release.

**Comment by nicm** [comment]
Thanks!
