### ISSUE TITLE
pane-border-status is wrong for zoomed panes

### ISSUE THREAD

**Issue by sphaugh** [tmux/tmux#576]
![dblstatus](https://cloud.githubusercontent.com/assets/8660255/19287156/34787680-8fc6-11e6-8a3e-f999f90534c3.png)

**Comment by nicm** [comment]
Try this please: 
[x.diff.txt](https://github.com/tmux/tmux/files/524035/x.diff.txt)

**Comment by sphaugh** [comment]
Looks good!

**Comment by nicm** [comment]
Applied now.

**Comment by nicm** [comment]
Thanks.

**Comment by kokapui** [comment]
I pull the latest (showing the fixes in screen-redraw.c) and observed the issue in RedHat 6.5 Santiago.
