### ISSUE TITLE
Focus events lag when creating or closing a split

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#577]
I've got Vim set up to respond to `FocusGained` and `FocusLost` events. I've noticed that when creating a new split (ie. with `Prefix-%` or `Prefix-"`)  causes Vim to lose focus, there is a variable, multi-second lag before it gets the `FocusLost` event. Likewise when closing a split causes Vim to regain focus, there is again a multi-second, variable lag before it gets `FocusGained`.

I am not sure whether this is a bug in tmux, Vim, iTerm, or my configuration, but I wanted to start by ruling out tmux as a cause because the behavior is tied to split creation and deletion. Other triggers for focus events are instantaneous (for example clicking between splits with the mouse, or clicking between iTerm windows, or using the keyboard to move between splits (ie. bindings mapped to `select-pane -L` and so on).

This gif shows the problem:

![lag](https://cloud.githubusercontent.com/assets/7074/19290812/591481d2-8fc6-11e6-9fff-e651ce2700dc.gif)

In the top window I have a Vim session (v8.0 patches 1-5) in iTerm2 (v3.0.10, with no custom tmux integration enabled) on macOS 10.11.6, and I'm using tmux 2.3 (installed via Homebrew, and according to the install receipt, using libevent 2.0.22). I have Vim set up to log `Focus*` events:

```
autocmd FocusLost * call system('echo "' . localtime() . ' FocusLost" >> /tmp/thelog && sync')
autocmd FocusGained * call system('echo "' . localtime() . ' FocusGained" >> /tmp/thelog && sync')
```

In the bottom window you can see me tailing the log file with `tail -f`, and you can see how the events arrive with significant lag in response to me creating or closing new splits, but happen instantly whenever I click or use the keyboard to jump between splits. In this video the lag is about 1 second, but I have seen delays as long as 10 seconds or more.

Is there any additional information I could collect to narrow down my list of suspects? As I said above, at the moment I am not sure if the culprit is tmux, Vim, iTerm or my own config, or perhaps something else that I am not thinking of.

**Comment by nicm** [comment]
I can't reproduce this. If I do this in one pane:

printf '\033[?1004h'; cat

Then whenever that pane becomes focused, I see the key entered immediately, regardless of whether it is due to selecting the pane or because it becomes selected or unselected by closing another pane.

Unless you can reproduce this without vim as well, it sounds like vim is just taking its time. Are you sure it isn't first dealing with being resized?

**Comment by wincent** [comment]
Thanks @nicm. That definitely narrows things down. I'll close this, but I'll post back for posterity if I get to the bottom of it and find out what it is (in Vim most likely) that explains the delay.
