### ISSUE TITLE
Incorrect draw of bottom right corner in mc after 2.3

### ISSUE THREAD

**Issue by dreviejo** [tmux/tmux#578]
After 2.3 upgrade, there is a minor incorrect draw in midnight commander window, configurated without the bottom button bar, affecting the end of last two lines, as you can see in this gif animation:
![mc-tmux2 2-3](https://cloud.githubusercontent.com/assets/13448813/19305538/a82dd52e-9071-11e6-8a6e-f13ebf2e9ca2.gif)
Maybe it's a problem with mc (I can't see this in any other program), but it works right with tmux previous versions, or without tmux in xterm, rxvt, linux console...

**Comment by nicm** [comment]
What is TERM inside and outside tmux?

**Comment by nicm** [comment]
Also if you do C-b r after it has gone wrong, does it redraw properly?

**Comment by dreviejo** [comment]
Sorry... I see this with TERM=tmux in the linux console, and TERM=tmux-256color within rxvt-unicode-256color. And tested with the last git tmux.
If I do C-l, this fix the penultimate line, not the last.
If I do C-b r, this clear the last char of the last line (line an space).
In both cases, resizing the window return to the incorrect redraw.

**Comment by nicm** [comment]
I can't reproduce this with mc 4.8.15:

- What mc version are you using?
- Is it built against slang? (check mc --version)
- Can you please give me your mc config?

**Comment by nicm** [comment]
Never mind, I missed that I had to turn the keybar off, I see it now.

**Comment by nicm** [comment]
We are flushing dirty cells to the terminal in the wrong place for insert mode, it needs to happen before we make room for the inserted cell in the screen. Please try this: [screen-write.c.diff.txt](https://github.com/tmux/tmux/files/524391/screen-write.c.diff.txt)

**Comment by dreviejo** [comment]
Better. With your patch, the initial redraw of mc is correct... with one pane. But if you do C-b r, you got the wrong redraw again (with the empty last char in the last line). If you do C-l or resize the terminal, the redraw is correct again.
But if you split the window (verticat or horizontal), then you got the wrong redraw (or some variant) on all the panes. And doing C-l or resizing doesn't help.
![mc-tmux-10121545](https://cloud.githubusercontent.com/assets/13448813/19312512/f92b1bfa-9092-11e6-8e6a-8b37d87f073d.jpg)

**Comment by nicm** [comment]
This one is an older bug, we should be using grid_view_insert_cells not grid_move_cells: 
[screen-write.c.diff.2.txt](https://github.com/tmux/tmux/files/524911/screen-write.c.diff.2.txt)

**Comment by dreviejo** [comment]
Ok. This time I think you did it; I'm unable to reproduce the problem. Thank you...

**Comment by nicm** [comment]
Applied now, should be in GitHub now. Thanks
