### ISSUE TITLE
automatic-rename stops working after pane is moved between sessions

### ISSUE THREAD

**Issue by sc0ty** [tmux/tmux#579]
When there are two tmux sessions running in separate terminals, after pane is moved between sessions (using mark-pane, then join-pane) title for that pane is no longer updated.
I have `setw -g automatic-rename on`.
This concerns tmux version 2.3.

**Comment by ThomasAdam** [comment]
Really?  Works for me.  What shell are you using?

**Comment by sc0ty** [comment]
I am running zsh under xterm.
To be clear, this problem concerns window name displayed in status line (#W), not the title set with escape code '\033]2;My Title\033\\'

**Comment by nicm** [comment]
After you move the window, does "tmux showw" in it show anything?

**Comment by sc0ty** [comment]
It turns out that automatic-rename wasn't turned on, now it is working. Sorry for your trouble and thanks for your time.
