### ISSUE TITLE
Vertical panes don't respond to clear commands

### ISSUE THREAD

**Issue by jgminder** [tmux/tmux#580]
When using the default macOS Terminal.app I set up a tmux session with 2 vertically split panes and when issuing a clear command the current pane would not clear the text. I also tried tmux clear-history command. If the panes are horizontally laid out the clear command works. iTerm2 works great so it could just be Terminal.app.

OSX Sierra
Terminal.app
tmux 2.3 (installed via homebrew).

**Comment by nicm** [comment]
TERM inside and outside tmux?

**Comment by jgminder** [comment]
Outside tmux: ansi
Inside tmux: screen-256color

**Comment by nicm** [comment]
Does it work with TERM=xterm outside tmux?

**Comment by jgminder** [comment]
Yes, clear works correctly outside of tmux when I set TERM=xterm.

**Comment by nicm** [comment]
No, inside tmux, with TERM=xterm outside tmux instead of TERM=ansi.

**Comment by jgminder** [comment]
Yes it works now inside tmux when I set TERM=xterm outside! Thanks for the quick responses!

**Comment by nicm** [comment]
It is probably still a tmux bug, ansi is a primitive terminal entry, we
are probably not emulating something properly. I'll take a look at some
point.

**Comment by nicm** [comment]
This is not actually a bug I think.

"ansi" is a TERM without the xenl flag, which means that it does not wrap lines the same as normal terminals, so tmux changes the way it works out the cursor position.

Since your terminal isn't really a !xenl terminal, it actually wraps differently, so tmux's idea of cursor position and the terminal's get out of sync. "ansi" is just the wrong TERM for your terminal.

**Comment by nicm** [comment]
We could do something like this [xenl.diff.txt](https://github.com/tmux/tmux/files/528761/xenl.diff.txt) which would hopefully make it work on both types of terminal, but I don't have any !xenl terminals around to test (IIRC the last common one was the NetBSD console).

**Comment by nicm** [comment]
I've applied this now, but you should continue to use TERM=xterm or TERM=nsterm in OS X Terminal.app, ansi is almost never the right choice.
