### ISSUE TITLE
Tmux randomly jumps back to end of buffer when scrolling

### ISSUE THREAD

**Issue by tymm** [tmux/tmux#582]
When I run tmux inside of rxvt-unicode, I get this unwanted jumping behavior when scrolling the history buffer.
When I scroll the buffer and stop at some position (which is not the end), tmux jumps back to the end of the buffer after some amount of time (I measured it twice: 26 seconds and 45 seconds).
I don't get this behavior when scrolling a buffer in a rxvt-unicode terminal without tmux.

I run Debian testing with tmux 2.3-1 and rxvt-unicode 9.22-1. My window manager is i3 4.12-2.
I start tmux and rxvt-unicode with `urxvt -e tmux -2`.
The following is my .tmux.conf.
```
unbind C-b
set -g prefix C-a
setw -g mode-keys vi
bind j select-pane -L
bind k select-pane -R
set -g default-terminal "screen-256color"
bind c new-window -c '#{pane_current_path}'
```

**Comment by nicm** [comment]
Do you mean tmux history in copy mode or the internal rxvt scrollback?

**Comment by tymm** [comment]
I guess I am using the internal rxvt scrollback since I am just using the touchpad for scrolling.

**Comment by nicm** [comment]
tmux has no real control over when rxvt chooses to scroll back to the
bottom, possibly it is doing it when tmux is redrawing the status line,
you could try setting status-interval to 0.

**Comment by tymm** [comment]
Tmux was redrawing every minute since I have the time in the status line.
Setting the status-interval to 0 helped to solve the issue.
Thank you!
