### ISSUE TITLE
Unknown key table error for vi-copy

### ISSUE THREAD

**Issue by micahjsmith** [tmux/tmux#585]
I just upgraded to tmux 2.4 using `brew install --HEAD tmux`. One of my commands is now failing.

```
$ tmux bind-key -t vi-copy v begin-selection
unknown key table: vi-copy
```
But in the man pages, I see
```
With -t, the key bindings in mode-table are listed; this may be one of: vi-edit, emacs-edit, vi-choice, 
emacs-choice, vi-copy or emacs-copy.
```

So is vi-copy a mode-table or not?

**Comment by nicm** [comment]
Yes, it should have been removed from there too, I'll remove it now, thanks.
