### ISSUE TITLE
[Proposal] Add support for mouse buttons 8 and 9 (left,right buttons)

### ISSUE THREAD

**Issue by Naereen** [tmux/tmux#588]
Hi,

First, :clap: and thanks for tmux, it's awesome and I love it (as everybody does).

Second, I asked [here on StackOverflow](https://stackoverflow.com/q/39976825/) if it would be possible to map a tmux command (let say `next-window`) with a mouse right button.
These basic mouse button are supported e.g. in Firefox (next, prev in history), and for instance can be used [in Sublime Text 3](http://perso.crans.org/besson/publis/ST3/Default%20%28Linux%29.sublime-mousemap).

Someone [replied to me](https://stackoverflow.com/q/39976825/#comment67253816_39976825), saying that this is not yet implemented in tmux.

So here is a small proposal: **could you (try to) add support for extra mouse buttons to tmux** ?
The more common ones are left and right additional button, usually denoted button8 and button9.

Thanks in advance!

**Comment by nicm** [comment]
If you do this in the terminal:

printf '\033[?1006h\033[?1000h';cat

then press the buttons, what do you see?

**Comment by Naereen** [comment]
Hi.

One try of this black-magic command, when I pressed on and off the main then the left button, then the right button, gave:
```
^[[M N0^[[M#N0^[[M N1^[[M#N1^[[M N1^[[M#N1
```
I guess `^[[M N0` corresponds to clicking the button 1 (main click), `^[[M#N0` to releasing it.

And I guess there an issue as the left and right buttons (8 and 9) are detected with the same response code (`^[[M N1` old, `^[[M#N1` release).

It seems to be really random, at least for the "identifier" part (`N0`, `N1` part).

**Comment by nicm** [comment]
OK so your terminal doesn't support SGR mouse mode (that is the 1006
bit), and isn't generating a unique escape sequences for buttons 8 and
9. (Outside SGR mouse mode, the protocol only allows for three buttons.)

I'm not certain, but if you can find a terminal that supports SGR mouse
mode (try rxvt-unicode perhaps), you might see a difference

However, we are not going to add 9 buttons to tmux anyway, that is a
ridiculous number of mouse buttons. If SGR mouse mode supports them, I'd
be open to adding buttons 3 and 4.

So you need to see if you can find a terminal that generates something
unique for your buttons, and persuade it that you are pressing buttons 3
and 4 (probably you can just change the mapping in X).

**Comment by Naereen** [comment]
I tried with `rxvt-unicode`, and indeed my buttons 8 and 9 are not detected. And the "identifier" part is still random for left and right clicks.

I understand that adding support for extra buttons is kinda opposed to tmux philosophy ("do less with your mouse, more with your keyboard")...

But would it be too complicated?
I [don't see much code](https://github.com/tmux/tmux/search?utf8=%E2%9C%93&q=MouseDown1&type=Code) using `MouseDown1` (for instance), so adding the same lines with `MouseDown8` (and Up8 and Down9 and Down10) would work ?

**Comment by nicm** [comment]
On Sun, Oct 16, 2016 at 11:41:28AM -0700, Lilian Besson wrote:
>    I tried with rxvt-unicode, and indeed my buttons 8 and 9 are not detected.
>    And the "identifier" part is still random for left and right clicks.
> 
>    I understand that adding support for extra buttons is kinda opposed to
>    tmux philosophy ("do less with your mouse, more with your keyboard")...
> 
>    But would it be too complicated?
>    I [1]don't see much code using MouseDown1 (for instance), so adding the
>    same lines with MouseDown8 (and Up8 and Down9 and Down10) would work ?

There is no point if terminals can't tell us about them.

**Comment by Naereen** [comment]
OK that's what I was afraid of...
Anyway, thanks for your replies!

So I used another approach, rebinding my keys with a [.xbindkeysrc](https://wiki.archlinux.org/index.php/Xbindkeys) file, but that's not on the tmux part.
