### ISSUE TITLE
Feature Request: Swap panes # and #

### ISSUE THREAD

**Issue by pcgeek86** [tmux/tmux#589]
# Scenario

* tmux offers an option to "Briefly display pane indexes"
* tmux offers an option to "swap current pane with [previous|next] pane." 

# Feature Request

It would be nice if we could combine the above features, into a new tmux command to "swap-panes ## and ##" where the user is prompted for "pane 1" and "pane 2" to swap. This command wouldn't replace the existing features, but rather join them together into a separate, new command.

From a user perspective, the key sequence would look something like: 

* `Ctrl + b`
* `<NewKeyBinding>`
* `2`
* `5`

This example would swap panes 2 and 5, regardless of which one is currently selected, or which one is considered "previous" or "next," relative to the currently selected pane.

Does this seem like a reasonable user enhancement? The thought process is that: "I want to swap *those* two panes. I don't care which one I'm currently on, or which ones are "next" and "previous." I just want to swap "those" two over there."

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by ThomasAdam** [comment]
You can do this with marked-panes or use a prompt.

**Comment by nicm** [comment]
You could maybe use command-prompt or script something with display-panes.

**Comment by pcgeek86** [comment]
@nicm @ThomasAdam Looking through documentation.

- Searches for `marked-panes` returns nothing.
- Not quite sure what is meant by command prompt -- maybe `CTRL + B, :`?

**Comment by nicm** [comment]
I'm not sure what to tell you because both the command prompt and marked
panes are described in the man page.

**Comment by nicm** [comment]
You could also do it with display-panes, if your tmux is sufficiently new. Unfortunately display-panes doesn't fire anything for "no pane chosen", so it is a bit fiddly. Something like this seems to work (note you need to use "run -b" to run it from a key binding):

~~~~
#!/bin/sh

trap 'tmux set -u display-panes-time' 0 1 15
O=$(tmux set display-panes-time 100000000)

tmux set -qu @first
tmux display-panes 'set @first %%'
for i in 0 1 2 3 4 5 6 7 8 9; do
        P1=$(tmux show -qv @first)
        [ -n "$P1" ] && break
        sleep 0.1
done
[ -z "$P1" ] && exit

tmux set -qu @second
tmux display-panes 'set @second %%'
for i in 0 1 2 3 4 5 6 7 8 9; do
        P2=$(tmux show -qv @second)
        [ -n "$P2" ] && break
        sleep 0.2
done
[ -z "$P2" ] && exit

tmux swapp -s$P1 -t$P2

**Comment by nicm** [comment]
It would be nice for this kind of thing if display-panes a) could take a command to fire on "no pane chosen", then could use wait-for instead of a loop b) had a flag to bypass display-panes-time. But TBH not sure this is required often enough for them to be worth it...

**Comment by pcgeek86** [comment]
Yeah, `display-panes` is the command I was thinking of, that shows the pane numbers. I do see it in the documentation. I don't think I'm advanced enough with tmux to make this work myself. I'm just an average user of it, but figured I'd file the feedback request, to see if it was of interest.

**Comment by nicm** [comment]
I think we already have enough ways to do this, the easiest is to mark one pane (C-b m) and then run swapp from the other (bind swapp to a key if you like).

When the new choose mode is done may be able to do it interactively there too...
