### ISSUE TITLE
Messy code in status bar

### ISSUE THREAD

**Issue by Retorz** [tmux/tmux#590]
At first, please allow my appreciation for your consistent great work on this project.

I searched around, it seems very rare to see messy display like this:
<img width="573" alt="screen shot 2016-10-17 at 00 05 09" src="https://cloud.githubusercontent.com/assets/10254172/19418777/99254b68-93fd-11e6-9a5e-1d2b787494d3.png">

I really need your help on this. What will cause it in your expertise?

**Terminal info**:
- Terminal: iTerm2

- Fonts: Ubuntu Mono

- Terminal Type: xterm-256color

**env**:

- LC_ALL: en_US.UTF-8

- LANG: en_US.UTF-8

**Comment by Retorz** [comment]
One more word: no `.tmux.conf` yet.

**Comment by nicm** [comment]
Are you asking about the question marks?

You must have a tmux.conf because this is not the default, do you have /etc/tmux.conf?

**Comment by Retorz** [comment]
@nicm Yeah, the `question marks` on the status bar.
The strange thing is I removed the `.tmux.conf` before screenshot and no `/etc/tmux.conf` found.
Anywhere else will `tmux` search for default setting?

**Comment by nicm** [comment]
Make sure you kill tmux entirely after removing .tmux.conf (pkill tmux).

**Comment by Retorz** [comment]
That's it!
Seems tmux need a restart to reload config, which I ignored. 
Will close this issue. Thanks for you kindly help ;-)
