### ISSUE TITLE
Provide a mechanis for double key binding

### ISSUE THREAD

**Issue by nkh** [tmux/tmux#591]
It's messy to try to make a command run with prefix + letter +letter, specially as  switch-client may be used in the command.

I spend a few hours that were quite frustrating, even with the very helpful nicm on #tmux.

bind key1 key2 command

bind key1 key2 -T table, where the command is define in table:key2, and  the sessions current table is not changed

Rational: we're running out of single keys
Rational: simple things should be simple

**Comment by nicm** [comment]
This is not a simple thing and most people don't want to do it, so long as it is possible this is fine.

**Comment by nkh** [comment]
if possible take an infinite time to find out, then it is not possible. Even with your help for two consecutive days, it did not work.  Even  counting my silly mistakes, it still took many tries to not get where one wants.

A simpler mechanism will make people use it more.

**Comment by nicm** [comment]
We are not adding a second way to do this. It is really not that hard either, I'm not sure what you are doing wrong. This works fine for me:

bind -Tprefix Tab switch -Ttab
bind -Ttab Tab new\; switch -Tprefix

Then C-b Tab Tab c will make a new session with a new window.

**Comment by nkh** [comment]
I am running a script that creates a new session and switches to it.

the script is meant to implement multiple commands, some creating sessions and windows, other manipulating them.

the idea is to have a common prefix + key for all of them:

prefix + tab + tab
prefix + tab + l
prefix + tab + r
...

None of the combinations I have tried and none of those you provided worked; including the one above which I have as:

bind -Tprefix Tab switch -Ttab
bind -Ttab Tab run-shell "/home/nadim/nadim/bin/tmuxake switch" \; switch -Tprefix

As I wrote in the first entry, the shell script create and manipulates sessions and  windows. using the binding above, I find myself forced to type "prefix + tab + tab" twice  in one window and only once in the other. 

I also have 
bind BSpace run-shell "/home/nadim/nadim/bin/tmuxake close"

which according to the documention would be in the prefix table but I don't need to press prefix, a simple BSpace runs the command. Which is either a bug or something messed up in my script, which doesn't work with tables at all.

I am happy to provide the script.

**Comment by nkh** [comment]
I will install the latest commit and run the same  test just to be sure..

**Comment by nicm** [comment]
This 

bind -Tprefix Tab switch -Ttab
bind -Ttab Tab run 'P=$(tmux new -dP);tmux switchc -t$P'\; switch -Tprefix

Also works fine for me.

Please reduce your script to an absolute minimum example that doesn't work and I will take a look.

**Comment by nkh** [comment]
tested with the latest commit, with the same configuration, there is a difference

I switch a window from a session to another through the script

in both windows, "prefix + tab + tab" must be pressed twice for the script to be run, Bspace which is bound in the prefix table  still does not need a prefix!

**Comment by nicm** [comment]
You have messed up your key bindings somehow. What does tmux lsk show?

**Comment by nkh** [comment]
tmux lsk output
http://nopaste.linux-dev.org/?1120082

I also noticed that if, after the prefix+tab+tab, any key is entered then the behavior is the expected one. as if that after prefix+tab+tab, one just typed a prefix and tmux is expecting input. that would explain why BSpace does not need a prefix

**Comment by nicm** [comment]
> prefix+tab+tab, one just typed a prefix and tmux is expecting input

This is exactly what it is doing. What did you think the switchc -Tprefix after the run-shell was doing?

**Comment by nicm** [comment]
These key bindings are fine, I suggest you start with the examples I have given, make sure they work and then extend them until it doesn't work.

**Comment by nicm** [comment]
switch-client -T tells the client what key table to look for the next key in, if you do this:

tmux run "script"\; switchc -Tprefix

Then after the script finishes, it will look up the next key press in the prefix table.

If you press a key BEFORE the script finishes, it will be looked up in the root key table.

**Comment by nkh** [comment]
after  prefix-tab-tab, tmux is as I had typed prefix. That is why two inputs are needed or that BSpace works without prefix.

it doesn't matter how long I wait before the next input. The script executes and I see the results of it, I can wait 30 s and still get the same behavior

As I have stated above, after prefix+tab+tab, tmux is acting as if I had type prefix. This is proven by the fact that I can type tab+tab without prefix, or Bspace without prefix.

I can type prefix-tab-tab, this executes the script; tab-tab (no prefix), executes the script again; 10 seconds later, tab-tab (still without prefix first), executes the scripts; a BSpace (still without prefix) would execute the other command.

**Comment by nicm** [comment]
I don't think you are reading what I reply.

**Comment by nicm** [comment]
With your current key bindings, Prefix-Tab-Tab will leave you in the prefix table, so the next key will also go to the prefix table. Remove the switchc -Tprefix if you don't want that.

**Comment by nkh** [comment]
What part of me reporting this bug: After prefix-tab-tab, tmux is acting as if prefix was type althoug it was no, is not serious enough, not described well enough, for you to not take my input seriously?

**Comment by sstallion** [comment]
@nicm I like this solution a lot, however I'm running into a problem. What I'd like to do is only match certain characters in a new table, otherwise I'd prefer to send the key sequence to the window.

For example:

    bind-key -Tmove j <some-action>
    bind-key -Tmove k <some-action>
    bind-key -n C-w switch-client -Tmove

How could I ensure that any key sequence that doesn't match C-w j or C-w k is sent to the window?

**Comment by nicm** [comment]
The only way to do it is to bind all the other keys to send-keys, but
what does it matter? Don't press C-w if you want it to go through?

**Comment by sstallion** [comment]
I'm stuck between a rock and a hard place. My current workflow binds C-j and C-k to other keys in the window (vim in this case), but I'd like to have unified movement between panes and vim windows. Ideally this means that I could only target certain keys to have an action in tmux, otherwise the sequence would be passed through. I could map every possible vim combination, but it would be really useful to have a default key binding for a table that I could wire to the send-keys command.

**Comment by sstallion** [comment]
With @nkh 's help on IRC I was able to come up with a solution that I really like: https://github.com/sstallion/dotfiles/blob/master/files/tmux/vi-keys.tmux#L44

Essentially this combines the approach documented in vim-tmux-navigator with using a client key-table for non-vim panes mentioned above. Thanks!
