### ISSUE TITLE
[tmux 2.3] pipe-pane doesn't work correctly after upgrade

### ISSUE THREAD

**Issue by toiffel** [tmux/tmux#594]
Hi,

I'm trying to log all output of the current pane into a file using pipe-pane command. Here is an example of simple bash session inside tmux pane:

```
$ tmux pipe-pane -o "cat >~/tmux.log"
$ printf '\e[1;34mhello\e[0m\n'
$ exit
```

tmux 2.2 correctly saves the entire session to file. Here is the contents of `~/tmux.log`:

```
[artur@hell ~]$ printf '\e[1;34mhello\e[0m\n'
[1;34mhello[0m
[artur@hell ~]$ exit
logout
```

But tmux 2.3 produces garbled log:

```
[artur@hell ~]$ intf '\e[1hello\1;34mhello[0m
[artur@hell ~]$ 
gout
```

Please notice how some arbitrary characters are missed from the output. This seems to happen more frequently after escape sequences but I haven't figured out any repeatable pattern so far. The same happens when I use pipe-pane directly from tmux command line.

**OS:** Arch Linux
**Terminal:** urxvt
**TERM inside tmux:** screen-256color

Thanks in advance!

**Comment by nicm** [comment]
I must have been on crack when I did this, try changing this back in window_pane_read_callback:

~~~~
--- window.c    16 Oct 2016 22:06:40 -0000      1.172
+++ window.c    18 Oct 2016 07:36:06 -0000
@@ -970,7 +970,7 @@ window_pane_read_callback(__unused struc

        input_parse(wp);

-       wp->pipe_off = size;
+       wp->pipe_off = EVBUFFER_LENGTH(evb);
 }

**Comment by toiffel** [comment]
This did the trick for me! Thank you for quick reply!

I'll play with tmux more today but compiling a large project with lots of output works well with pipe-pane. Guess we can close it for now.

**Comment by brotherjimthomas** [comment]
Oh, that's fantastic! Thank you - I was despairing about every getting logging (pipe-pane) to work in tmux and this solved my dilemma nicely.
