### ISSUE TITLE
Vim is blank when splitting pane or creating/switching window

### ISSUE THREAD

**Issue by cHoco** [tmux/tmux#595]
I've been having this issue since I think tmux 2.1 but it has gotten worse as time went on. I'm not sure if it's caused by tmux or by vim but I first wanted to ask here. 
Basically when I have `lazyredraw` set in my vimrc I experience redraw bugs with tmux. The most common is when I'm using vim, split the pane and the vim pane turns completely blank; switching back to it redraws it correctly. This also happens when creating/moving between windows, with vim panes inside of them.
I don't know what steps to provide to reproduce the issue because just having lazyredraw isn't enough, but a complex vimrc ***with*** that options shows the above problem.

**Comment by nicm** [comment]
If you ask tmux to redraw with C-b r (refresh-client) by default, does it
redraw correctly?

What if you make vim redraw (C-l or similar if it supports it, or resize
the terminal)?

**Comment by cHoco** [comment]
I said vim but I was using neovim, sorry for that. But with vim the issue is even stranger and doesn't even require lazy-redraw to be set.
In vim when I perform a new split or switch windows the background changes color to a light blue (?!?) 

> If you ask tmux to redraw with C-b r (refresh-client) by default, does it
redraw correctly?

With both vim and neovim (even though they have different graphical glitches) this doesn't solve it

> What if you make vim redraw (C-l or similar if it supports it, or resize
the terminal)?

The issue disappears for both vim and neovim, but I don't have a way to perform a redraw when leaving a pane. (There's a FocusLost event in vim but using it to trigger a redraw still exposes the issue)
The strange thing is that this happens only after the initial split, then I can freely siwtch between panes and it doesn't have any issue

**Comment by nicm** [comment]
Are you using some crappy extension that assumes tmux is BCE even though
TERM says it isn't? Try tmux from Git master, BCE is supported there.

**Comment by cHoco** [comment]
> Are you using some crappy extension that assumes tmux is BCE even though
TERM says it isn't? 

I don't think so
> Try tmux from Git master, BCE is supported there.

I'm already using it from Git, latest commit.

**Comment by nicm** [comment]
OK do this:

tmux -f/dev/null -Ltest new

Then run vim, reproduce in as few steps as possible, then take a
screenshot, exit tmux and send me both the screenshot and the tmux-*.log
files from the current directory.

**Comment by nicm** [comment]
Use Git master please.

**Comment by cHoco** [comment]
I can't reproduce it when launching tmux with the command above.
In my tmux.conf I use
```
set -g default-terminal "xterm-256color"
```

**Comment by nicm** [comment]
That is because that is wrong.

**Comment by cHoco** [comment]
Ops I meant `set -g default-terminal "tmux-256color"`

**Comment by nicm** [comment]
What if you create a .conf with just this line, and use that:

echo 'set -g default-terminal "tmux-256color"' >/tmp/foo
tmux -Ltest kill-server
tmux -Ltest -f/tmp/foo new

**Comment by cHoco** [comment]
I can't with the one above, but I can reproduce the issue with this 
`echo 'set -g default-terminal "tmux-256color"\n set -g focus-events on' >/tmp/foo`
to produce the logs I launched tmux with `-vvv`
Here's a screenshot:
![screen shot 2016-10-18 at 14 11 40](https://cloud.githubusercontent.com/assets/85527/19477128/0cf65f6a-953d-11e6-9871-2b92fb859284.png)
and the logs:
- tmux-client.log http://pastebin.com/YFqmz8KL
- tmux-server.log https://gist.github.com/cHoco/213300570b8a54f0a508e1b68b5f52ba

**Comment by nicm** [comment]
So vim should be in the left hand pane in this screenshot?

**Comment by cHoco** [comment]
Yes, exactly

**Comment by nicm** [comment]
I think this is a vim bug.

The split window is executed at 1476792697.287132 and 1476792697.304117
is the next data received from pane %0 (vim).

But it is all blanks:

1476792697.304172 input_parse: %0 ground, 1024 bytes: \033[?25l\033[1;1H\033(B\033[m\033[37m\033[40m                                                       \033[2;1H                             \033[3;1H                                                       \033[4;1H                                                       \033[5;1H                               \033[6;1H\033[7;1H                                                       \033[8;1H                                 \033[9;1H  \033[10;1H                                                       \033[11;1H                                     \033[12;1H       \033[13;1H                                                       \033[14;1H                                          \033[15;1H            \033[16;1H                                                       \033[17;1H

And so on, clearing all the lines in the pane (last at 1476792697.304835).

It doesn't redraw any content until 7 seconds later at 1476792704.943527
when it again clears the entire pane, but this time draws some content
as well (starting at 1476792704.944422).

So for whatever reason, vim is not correctly redrawing after the
split-window has resized the pane.

I suggest you try to track down what element in your vim config is
causing this and then report it to them.

**Comment by cHoco** [comment]
Thank you so much for taking a look, I found an issue on the neovim repository that is tracking it.

Could you also take a look at these logs? The above one is the issue in neovim, this one is in vim and seems to be related to the truecolor feature since I can't reproduce it if I don't enable it in tmux and vim.

Screenshot:
![screen shot 2016-10-18 at 15 36 11](https://cloud.githubusercontent.com/assets/85527/19479930/3b0b0b42-9549-11e6-9371-1956acdbea32.png)

Logs: 
https://gist.github.com/cHoco/ca01826171be703069a6ba58e599261c

tmux.conf
```
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g focus-events on
```

To reproduce the screenshot I open a file, create a new window, switch back to vim one and it's like this.

**Comment by nicm** [comment]
Does C-b r fix it?

If you do this:

 printf '\033[48;2;45;45;45m\033[H\033[2J'

Outside tmux, does is correctly clear the screen to grey?

**Comment by nicm** [comment]
Never mind think I have reproduced it, you need a terminal outside tmux that doesn't have BCE.

**Comment by nicm** [comment]
We aren't setting the bg colours properly on cleared cells when it is a 256 or RGB colour, here is the fix: [x.diff.txt](https://github.com/tmux/tmux/files/536579/x.diff.txt)

**Comment by nicm** [comment]
I have applied this so if you wait for a bit it should be in Git.

**Comment by cHoco** [comment]
The patch does indeed fix the issue :)  I'm closing this since the other one is a layout problem in neovim itself. Thank you so much again for your work!
