### ISSUE TITLE
freebsd build: "libevent not found"

### ISSUE THREAD

**Issue by jungle-boogie** [tmux/tmux#596]
Hi All,

I build tmux from source almost daily, but now I'm not able to because of a config issue around event.h:

```
checking for library containing flock... none required
checking for dirfd... yes
checking for flock... yes
checking for prctl... no
checking for sysconf... yes
checking for cfmakeraw... yes
checking for library containing clock_gettime... none required
checking for LIBEVENT... yes
checking event.h usability... no
checking event.h presence... no
checking for event.h... no
configure: error: "libevent not found" 
```

libevent2 is already installed on the system. I'll checkout something earlier than yesterday to see if I'm able to build from source.

**Comment by jungle-boogie** [comment]
works:
733185d0a93b608f5c2f5396e48643b1f97b2c23

doesn't work:
7ba845297fd60c784ecff248b27db109750211bf

Looks like changes in 7ba845297fd60c784ecff248b27db109750211bf break the build.

**Comment by ThomasAdam** [comment]
On Tue, Oct 18, 2016 at 08:53:34AM -0700, jungle-boogie wrote:
> works:
> 733185d0a93b608f5c2f5396e48643b1f97b2c23
> 
> doesn't work:
> 7ba845297fd60c784ecff248b27db109750211bf
> 
> Looks like changes in 7ba845297fd60c784ecff248b27db109750211bf break the build.

They work just fine for me on FreeBSD 11-p1.  Can you tell us more about your
system?

-- Thomas Adam

**Comment by jungle-boogie** [comment]
HI @ThomasAdam,

FreeBSD 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1

```
 % cc -v
FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
Target: i386-unknown-freebsd11.0
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by jungle-boogie** [comment]
Also failing on dragonflyBSD with this commit:
http://gitweb.dragonflybsd.org/dragonfly.git/commit/c00575de8491dc402abf52c8c7e1cca1ef79e257

```
> cc -v
Using built-in specs.
COLLECT_GCC=/usr/libexec/gcc50/cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc50/lto-wrapper
Target: x86_64-pc-dragonflybsd
Configured with: DragonFly/x86_64 system compiler (c c++ objc LTO)
Thread model: posix
gcc version 5.4.1 [DragonFly] Release/2016-08-27
```

**Comment by jungle-boogie** [comment]
also failing on a freebsd 11-stable  with revision r307391 from tmux's master:

```
checking for library containing clock_gettime... none required
checking for LIBEVENT... yes
checking event.h usability... no
checking event.h presence... no
checking for event.h... no
configure: error: "libevent not found"
```

```
% cc -v
FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
Target: i386-unknown-freebsd11.0
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by nicm** [comment]
Show config.log please.

**Comment by jungle-boogie** [comment]
hi @nicm,

Please see attached file.

[config.txt](https://github.com/tmux/tmux/files/536788/config.txt)

**Comment by nicm** [comment]
Yeah the test for event.h needs to use LIBEVENT_CFLAGS if it has been set,
I'll look at it when I get home in a few hours.

**Comment by nicm** [comment]
Can you try changing this please:

~~~~
--- a/configure.ac
+++ b/configure.ac
@@ -145,7 +145,8 @@ PKG_CHECK_MODULES(
 AC_CHECK_HEADER(
        event.h,
        ,
-       found_libevent=no
+       found_libevent=no,
+       $LIBEVENT_CFLAGS
 )
 if test "x$found_libevent" = xno; then
        AC_MSG_ERROR("libevent not found")

**Comment by jungle-boogie** [comment]
Hi @nicm,

Sorry for the late response.

That didn't seem to change it. I deleted tmux, cloned, patched configure.ac, sh autogen.sh ./configure

**Comment by ThomasAdam** [comment]
Do you have `-I/usr/local/include` in `CFLAGS`?  I bet you don't...

**Comment by nicm** [comment]
He shouldn't need to add it, pkg-config will tell us in LIBEVENT_CFLAGS. But that isn't being used by AC_CHECK_HEADER. I'm going to revert the AM_* change,

**Comment by nicm** [comment]
Please try git pull and see if it is working again.

**Comment by jungle-boogie** [comment]
git master worked and built tmux correctly on both dragonfly and the freebsd stable.

@ThomasAdam,

You never had the problem on your system?

**Comment by nicm** [comment]
OK thanks

**Comment by nicm** [comment]
I have changed the configure.ac again, please let me know if it is broken again now.

**Comment by jungle-boogie** [comment]
hi @nicm,

Yes, this builds without problems.
