### ISSUE TITLE
interaction between zoomed pane and pane-border-status

### ISSUE THREAD

**Issue by quite** [tmux/tmux#598]
Turning on `pane-border-status` (top/bottom) while in `resize-pane -Z` mode results in the border-format texts of other (non-zoomed) panes appearing on screen in ugly places -- not precisely where they would appear when un-zoomed, but they should not appear at all anyway right. (Yeah I bound a key to toggle border-status, since I'm not sure yet whether I like it or not.)

This is obviously tmux 2.3, from jessie-backports. Also verified on Arch Linux. I'm afraid I don't have time to try with a cleaner tmux.conf etc now.

**Comment by nicm** [comment]
This is already fixed.
