### ISSUE TITLE
unknown command: copy-pipe

### ISSUE THREAD

**Issue by joma74** [tmux/tmux#599]
Tmux built on Ubuntu 14.04 from source at of commit b951f0621caf154fbb73c99965b52b3bd4f9813c. The command 'copy-pipe' is not recognized in my environment. Gives
```
joma@kopernikus-u:~$ tmux list-commands
unknown command: copy-pipe
attach-session (attach) [-dEr] [-c working-directory] [-t target-session]
bind-key (bind) [-cnr] [-t mode-table] [-T key-table] key command [arguments]
break-pane (breakp) [-dP] [-F format] [-s src-pane] [-t dst-window]
capture-pane (capturep) [-aCeJpPq] [-b buffer-name] [-E end-line] [-S start-line][-t target-pane]
choose-buffer [-t target-window] [-F format] [template]
choose-client [-t target-window] [-F format] [template]
choose-session [-t target-window] [-F format] [template]
choose-tree [-suw] [-b session-template] [-c window template] [-S format] [-W format] [-t target-window]
choose-window [-t target-window][-F format] [template]
clear-history (clearhist) [-t target-pane]
clock-mode [-t target-pane]
command-prompt [-1N] [-I inputs] [-p prompts] [-t target-client] [template]
confirm-before (confirm) [-p prompt] [-t target-client] command
copy-mode [-Mu] [-t target-pane]
delete-buffer (deleteb) [-b buffer-name] 
```

While literally referenced in window-copy.c - did not grep it anywhere else in sources, esp. no "cmd-copy-pipe.c". Is it still supported?

**Comment by nicm** [comment]
It was never a command, probably you are seeing an error because the way you bind mode keys has changed.

**Comment by nicm** [comment]
See 76d6d3641f271be1756e41494960d96714e7ee58.

**Comment by joma74** [comment]
:+1: Thanks @nicm for the reference. Works a treat 

``` bash
bind -Tcopy-mode-vi M-y send -X copy-pipe "xclip -i -sel p -f | xclip -i -sel c" \; display-message "copied to system clipboard"
````

**Comment by serussell** [comment]
Oh, yeah... that's a **huge** improvement over `bind -t vi-copy y copy-pipe "xclip -sel clip -i"`.  Glad to see the disruptive configuration changes are for a good cause.

**Comment by nbwoodward** [comment]
In Ubuntu 18.04 and tmux 2.6 I was getting some unicode junk at the end of the line when I used the above suggestion but I don't get the same behavior with `copy-pipe-and-cancel`:
```
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -sel clip -i"
```
