### ISSUE TITLE
New pane does not keep relative path

### ISSUE THREAD

**Issue by HeathNaylor** [tmux/tmux#60]
If I `cd ~/myfolder` and then open a new tmux pane split below the current one my directory goes back to my `~/` home folder. I would expect this to all be relative to my current path.

**Comment by nicm** [comment]
You probably want splitw -c '#{pane_current_path}'

**Comment by HeathNaylor** [comment]
Yes, this should be the default in my opinion. It used to operate like this.

**Comment by HeathNaylor** [comment]
For now I have fixed this by adding the following bindings to my `~/.tmux.conf` file.

```
bind '"' splitw -c '#{pane_current_path}'
bind '%' splitw -h -c '#{pane_current_path}'
```

**Comment by nicm** [comment]
It is not going to be the default, it can have unexpected results and is not supported on all platforms.

**Comment by HeathNaylor** [comment]
Fair enough, doesn't work on Windows. Might look into why, I feel like this is pretty important.
