### ISSUE TITLE
On Mac OS X, Tmux Causes Problems Communicating With Launchctl

### ISSUE THREAD

**Issue by paulcavallaro** [tmux/tmux#600]
It seem that when running tmux, it has problems communicating and working with launchctl, reporting simply: "Operation not permitted"

I am regrettably short on details, but this is from experiencing and following along with the reported bug here in Watchman: https://github.com/facebook/watchman/issues/69

The underlying problem seems to have been tmux, as when not inside a tmux session, the launchctl commands from watchman worked just fine.

Diagnostic info follows:

OS Version:
El Capitan 10.11.4

```
➜  ptcc git:(master) tmux -V
tmux 1.9a
➜  ptcc git:(master)
```

**Comment by krader1961** [comment]
You need to use [reattach-to-user-namespace](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard) by adding something like the following (from my *~/.tmux.conf*):

```
# The reattach-to-user-namespace is necessary to be able to contact ssh-agent
# via the SSH_AUTH_SOCK env var. This is also necessary to make pasteboard
# (clipboard) interaction work for programs run within the tmux server.
set-option -g default-command "exec reattach-to-user-namespace -l /usr/local/bin/fish"
```

If you're using Homebrew run `brew install reattach-to-user-namespace`.
