### ISSUE TITLE
Getting "configure: error: C compiler cannot create executables" on OSX

### ISSUE THREAD

**Issue by symbolix** [tmux/tmux#601]
Hi,

I have previously built `tmux` from scratch on OSX (many times), however, with the latest `git clone`, I am getting the following error on OSX:

```
checking whether the C compiler works... no
configure: error: in `/Users/me/.tmp/tmux/build':
configure: error: C compiler cannot create executables
```

The first stage:

```
$ git clone https://github.com/tmux/tmux.git
$ cd tmux
$ sh autogen.sh
$ ./configure && make
```

... is all good. I have all the bits and pieces in place: `auto-tools, pkg-config etc.`. `libtools` and `ncurses` all good as well.

This error is really strange and I remember getting it on my Linux machine at work. I solved the problem by configuring an environment that points to `GCC 4.8.2`. Then, everything worked. I have the latest `master` built from source on Linux.

However, not sure how to fix this under OSX.

`gcc --version` is returning the following:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin  
```

Below is the section from the log, that I believe, is pointing to the issue:

```
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
configure:3309: $? = 0
configure:3298: gcc -v >&5
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
configure:3309: $? = 0
configure:3298: gcc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3309: $? = 1
configure:3298: gcc -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:3309: $? = 1
configure:3329: checking whether the C compiler works
configure:3351: gcc -arch x86_64 -I/Users/me/apps/Darwin64/libevent-2.0.22-clang-503.0.40/include -I/Users/me/apps/Darwin64/ncurses-6.0-clang-800.0.38/include  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -arch x86_64 -I/Users/me/apps/Darwin64/libevent-2.0.22-clang-503.0.40/include -I/Users/me/apps/Darwin64/ncurses-6.0-clang-800.0.38/include  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -arch x86_64 -L/Users/me/apps/Darwin64/libevent-2.0.22-clang-503.0.40/lib -L/Users/me/apps/Darwin64/ncurses-6.0-clang-800.0.38/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib conftest.c  >&5
ld: file not found: /usr/lib/system/libsystem_symptoms.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3355: $? = 1
configure:3393: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "tmux"
| #define PACKAGE_TARNAME "tmux"
| #define PACKAGE_VERSION "2.4"
| #define PACKAGE_STRING "tmux 2.4"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "tmux"
| #define VERSION "2.4"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3398: error: in `/Users/me/.tmp/tmux/build':
configure:3400: error: C compiler cannot create executables
See `config.log' for more details
```

I know this must be something silly, cause I have fixed it under Linux. I must be definitely missing something on OSX.

Thanks.

**Comment by ThomasAdam** [comment]
Looks like an XCode problem; nothing to do with tmux.

**Comment by symbolix** [comment]
This is not entirely correct. I do not use Xcode on Linux, right? And I had the same issue on Linux. Clearly something has changed, not that I cannot go in there and dig around and find out what the problem is. This is exactly what I did and I fixed the issue on my Linux machine.

The issue is that this is not clearly documented. As a user, I would expect this to build with the least possible effort. Cause, that was the case with `tmux` 2.2. Never had problems. And I am building `tmux` from source since 1.9.

Could you please clarify what the problem is (at least for the other users that may face the same issue)? If this is a minimum `GCC version` situation or something to do with the `C Flags` please make sure that it is explained clearly.

**Comment by nicm** [comment]
Give me the full config.log please.

**Comment by nicm** [comment]
Actually it's OK, looks like a problem on your system:

ld: file not found: /usr/lib/system/libsystem_symptoms.dylib for architecture x86_64

**Comment by nicm** [comment]
A quick Google seems to indicate this is an XCode 8 bug.

**Comment by symbolix** [comment]
Strange, I will check the log on my Linux machine. The one I have generated before fixing the issue. I am kind of sure it is a `GCC version` and `GCC include folder` problem, as switching to GCC 4.8.2 has fixed the issues (from 4.2). So apple might have messed up things on that side. I will try this with a custom GCC and see how it goes.

**Comment by nicm** [comment]
Apple have left out a library in Xcode, it does not use GCC. You have a completely different problem on Linux but it will similarly be something in the environment.

**Comment by symbolix** [comment]
I will try to get a newer version of GCC and see how it goes. Or switch to a newer 'clang'.

**Comment by symbolix** [comment]
Having said that, the confusing bit is, if system clang / Xcode is so broken, how on earth I managed to build all the `tmux` pre-requests from scratch: `autoconf`, `automake`, `pkg-config`, `libevent` and `ncurses` all from source and without any issues. That bit is confusing.

**Comment by symbolix** [comment]
Also, I can confirm that `tmux-1.9a` builds just fine from tar-ball.

```
export CPPFLAGS="-arch x86_64 -I/Users/me/apps/Darwin64/libevent-2.0.22-clang-503.0.40/include -I/Users/me/apps/Darwin64/ncurses-5.9-clang-503.0.40/include"

export CFLAGS="-arch x86_64 -I/Users/me/apps/Darwin64/libevent-2.0.22-clang-503.0.40/include -I/Users/me/apps/Darwin64/ncurses-5.9-clang-503.0.40/include"

export LDFLAGS="-L/Users/me/apps/Darwin64/libevent-2.0.22-clang-503.0.40/lib \
-L/Users/me/apps/Darwin64/ncurses-6.0-clang-800.0.38/lib"

../configure --prefix=/Users/me/apps/Darwin64/tmux-1.9a-clang-800.0.38
```

No issues. Maybe the `autoge.sh` stage is the problem?

**Comment by symbolix** [comment]
Also, I can confirm that `tmux-2.3` builds fine from the tar-ball.

```
# First, download and extract the tar bundle
tar xvf tmux-2.3
  
# Go inside the folder and create a build folder
cd tmux-2.3
mkdir build
cd build
  
# We are compiling tmux against the dependencies we have compiled in the previous stage
export CPPFLAGS="-arch x86_64 -I/Users/me/apps/Darwin64/libevent-2.0.22-clang-800.0.38/include -I/Users/me/apps/Darwin64/ncurses-6.0-clang-800.0.38/include"
 
export CFLAGS="-arch x86_64 -I/Users/me/apps/Darwin64/libevent-2.0.22-clang-800.0.38/include -I/Users/me/apps/Darwin64/ncurses-6.0-clang-800.0.38/include"
 
export LDFLAGS="-arch x86_64 -L/Users/me/apps/Darwin64/libevent-2.0.22-clang-800.0.38/lib -L/Users/me/apps/Darwin64/ncurses-6.0-clang-800.0.38/lib"
 
# Run the configure script from inside the "./build" folder
../configure --prefix=/Users/me/apps/Darwin64/tmux-2.3-clang-800.0.38
 
# Finally
make
make install
```

**Comment by symbolix** [comment]
Ok. I have found the solution and finally managed to build tmux 2.4 from `git clone` source with `autogen.sh`. I have to accept it was quite tricky and it is because OSX has it's own ways etc. I would like to share my solution as a new issue, in case other OSX people run into similar difficulties. Thanks for your time.

**Comment by nicm** [comment]
Please do not open any more issues for this, if you want to put your
solution on this issue that is fine.

**Comment by perks** [comment]
Wait @symbolix u bailed so hard
