### ISSUE TITLE
Activity in window 1, only 1 window

### ISSUE THREAD

**Issue by supermarin** [tmux/tmux#603]
Activity indicator shouldn't be shown for the current window.
Also, it seems like cursor disappears on each input character and drawing seems slower.
Tmux HEAD (5f9ba2f223bcdc4770e56248d5f20e488ee11456), OSX 10.11.6

![tmux](https://cloud.githubusercontent.com/assets/627285/19669458/43104da0-9a14-11e6-99c1-b752c8e7babe.gif)

**Comment by nicm** [comment]
Should be fixed.
