### ISSUE TITLE
Esc if no key follows prefix key after a period of time

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#604]
When I press a prefix key to execute functions like creating/closing window/pane, scrolling the page, etc., sometimes I forgot that I have pressed the prefix key after a period and didn't press any other keys, if I don't want to execute any tmux commands any more I have to type Esc to escape the tmux-prefix status.

How can tmux escape prefix status after a period of time like 2 seonds if no key follows prefix key?

**Comment by nicm** [comment]
I don't think this is something worth doing.

**Comment by c02y** [comment]
@nicm It happens me from time to time.

**Comment by nicm** [comment]
It doesn't sound like something important enough or common enough we need to add a feature to avoid.

**Comment by c02y** [comment]
OK, please close this issue.
