### ISSUE TITLE
feature request / discussion: a text-mode window manager and an UI framework

### ISSUE THREAD

**Issue by stronny** [tmux/tmux#605]
Please hear me out. My particular tmux use-case is that of a "window manager" not unlike i3, but without X altogether. tmux is remarkable and unchallenged in this role, but I frequently run into walls for some additional features I would like to implement on top. Some are built-in commands inconsitencies (I can create a full-width pane, but no way to join pane full-width), some are lack of extensibility, for example: tmux has code to draw a menu (select-window), but no way to supply user-data to that menu.

I do not ask to overbloat tmux with additional features, I ask to make it more extensible without patching the source. For example. is it possible to decouple tmux messages from its current visualizations? What if I want to hook into the part that draws a message in status line and instead for example use libnotify for that?

If I would ever like tmux to do anything completely new, I'm thinking floating panes. Just like in i3: normally you have windows side-by-side, but sometimes you want a modal window right in the middle. Is this possible at all?

**Comment by nicm** [comment]
I have no idea what you are suggesting here.

**Comment by stronny** [comment]
Let me try to illustrate my point. Is it possible to register a `before-display-message` hook that will a) fire on tmux own messages; and b) prevent the message from being displayed?

`split-window` takes `-f`, while `join-pane` does not. This is a practical issue for me as right now I have to do `split-window` and `swap-pane` which feels like a hack.

Is it possible to export the code that draws a `choose-window` menu into a new tmux command `draw-menu` that will take strings and return the one selected?

**Comment by nicm** [comment]
So what you are asking for is -f for join-pane?

Before hooks have been removed already.

We are not having a general purpose menu. command, there are already
solutions out there like dialog.

**Comment by stronny** [comment]
I do ask for `join-pane -f`, but my overall point is much more generic. As I don't really know what tmux architecture is I can't point to any precise points, so I am suggesting this in broad strokes. Is it possible to make tmux more extensible? I am implementing some interactive code and I have a feeling that tmux already has many parts of an UI framework, and with little effort it could become a tremendous platform for interactive applications.

As to your Dialog reference: for example, there is a command to display messages, though it could be certainly done in other ways, right? And I certainly do not suggest that tmux should implement lots of new features for that, just expose those parts that it already has for its own interactive needs is all.

**Comment by nicm** [comment]
It is possible to make tmux more extensible, and we do try to do so, broadly by making it possible to use tmux from shell scripts. At the moment I'm afraid your suggestions are just too vague. I think you should spend some time looking at how tmux works and then you can probably describe what you are suggesting in a more concrete way.

**Comment by stronny** [comment]
This is of course a reasonable answer, alas I doubt I will be able to do that. Maybe other people would though.
