### ISSUE TITLE
Differenciation between C-b C (uppercase) and C-b c (lowercase)

### ISSUE THREAD

**Issue by pfigue** [tmux/tmux#606]
Hi,

I am used to programs where **C-b C** and **C-b c** would be equivalent. In my tmux right now it is not equivalent.

Is this behaviour intended? Is it a mistake in my tmux configuration? Is it a bug?

Thanks!

**Comment by ThomasAdam** [comment]
On Wed, Oct 26, 2016 at 05:44:30AM -0700, pfigue wrote:
> Hi,
> 
> I am used to programs where **C-b C** and **C-b c** would be equivalent. In my tmux right now it is not equivalent.
> 
> Is this behaviour intended? Is it a mistake in my tmux configuration? Is it a bug?

Intended.

-- Thomas Adam

**Comment by nicm** [comment]
It is intentional.
