### ISSUE TITLE
With `monitor-activity` on, bell is sent on each keystroke after the first bell

### ISSUE THREAD

**Issue by tweekmonster** [tmux/tmux#607]
Just compiled from master.  Disabling `monitor-activity` causes the problem to go away.  GIF of tmux giving me the business:

![](https://cloud.githubusercontent.com/assets/111942/19728319/f1a8dd26-9b60-11e6-87ba-8a1d756f5f0a.gif)

**Comment by nicm** [comment]
Do you have 99946aaaafcd0fb38dd73f750739bb58f6822ed2?

**Comment by tweekmonster** [comment]
I compiled today from b6f00a3945e1e34ca4314c3e1c4b3a08f5b5c982

**Comment by nicm** [comment]
I can't reproduce this, please show me a minimal config and directions on how to reproduce.

**Comment by tweekmonster** [comment]
I just recompiled on 178894b and am able to reproduce with only this in `~/.tmux.conf`:

```
setw -g monitor-activity on
```

I'm also able to reproduce this without `~/.tmux.conf` and using `^b:setw -g monitor-activity` to turn it on/off.  The bell spam happens regardless of when the first bell occurred when changing the setting at runtime.  If I use `set -g visual-bell on` I get the message in the status line on each keystroke, which I guess means it's not the terminal misinterpreting things.


## Logs

- [client](http://sprunge.us/SPRO)
- [server](http://sprunge.us/KTcD)

This was what I ran during the session:

```shell
$ tmux -v new \; setw -g monitor-activity on
$ printf '\x07'
$ hello^C^D
```

## My setup

I'm on OS X and ssh into a Linux server to use tmux.  (FWIW, I'm able to reproduce this with the latest build on OS X)

- Server (where tmux is running):
  - OS: `Ubuntu 16.04.1 LTS`
  - Shell: `zsh 5.2`
- Client:
  - OS: `OS X 10.11.6`
  - Shell: `zsh 5.0.8`
  - Terminal: `iTerm2 3.0.20160713-nightly` and `Terminal.app`

## Runtime settings (Linux)

```shell
$ tmux new \; setw -g monitor-activity on

$ cat ~/.tmux.conf
cat: /home/tallen/.tmux.conf: No such file or directory

$ tmux show -gs
buffer-limit 20
default-terminal "screen"
escape-time 500
exit-unattached off
focus-events off
history-file ""
message-limit 100
quiet off
set-clipboard on
terminal-overrides "xterm*:XT:Ms=\E]52;%p1%s;%p2%s\007:Cs=\E]12;%p1%s\007:Cr=\E]112\007:Ss=\E[%p1%d q:Se=\E[2 q,screen*:XT"

$ tmux show -gw
aggressive-resize off
allow-rename on
alternate-screen on
automatic-rename on
automatic-rename-format "#{?pane_in_mode,[tmux],#{pane_current_command}}#{?pane_dead,[dead],}"
clock-mode-colour blue
clock-mode-style 24
force-height 0
force-width 0
main-pane-height 24
main-pane-width 80
mode-keys vi
mode-style fg=black,bg=yellow
monitor-activity on
monitor-silence 0
other-pane-height 0
other-pane-width 0
pane-active-border-style fg=green
pane-base-index 0
pane-border-format "#{?pane_active,#[reverse],}#{pane_index}#[default] "#{pane_title}""
pane-border-status off
pane-border-style default
remain-on-exit off
synchronize-panes off
window-active-style default
window-style default
window-status-activity-style reverse
window-status-bell-style reverse
window-status-current-format "#I:#W#{?window_flags,#{window_flags}, }"
window-status-current-style default
window-status-format "#I:#W#{?window_flags,#{window_flags}, }"
window-status-last-style default
window-status-separator " "
window-status-style default
wrap-search on
xterm-keys off

$ infocmp
#       Reconstructed via infocmp from file: /lib/terminfo/s/screen
screen|VT 100/ANSI X3.64 virtual terminal,
        am, km, mir, msgr, xenl,
        colors#8, cols#80, it#8, lines#24, ncv@, pairs#64,
        acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=^M,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
        cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, ed=\E[J, el=\E[K, el1=\E[1K,
        enacs=\E(B\E)0, flash=\Eg, home=\E[H, ht=^I, hts=\EH,
        ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L, ind=^J, is2=\E)0,
        kbs=\177, kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC,
        kcuu1=\EOA, kdch1=\E[3~, kend=\E[4~, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf2=\EOQ, kf3=\EOR, kf4=\EOS,
        kf5=\E[15~, kf6=\E[17~, kf7=\E[18~, kf8=\E[19~, kf9=\E[20~,
        khome=\E[1~, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM, rmacs=^O,
        rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[23m,
        rmul=\E[24m, rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
        setab=\E[4%p1%dm, setaf=\E[3%p1%dm,
        sgr=\E[0%?%p6%t;1%;%?%p1%t;3%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;m%?%p9%t\016%e\017%;,
        sgr0=\E[m\017, smacs=^N, smcup=\E[?1049h, smir=\E[4h,
        smkx=\E[?1h\E=, smso=\E[3m, smul=\E[4m, tbc=\E[3g,
```

**Comment by nicm** [comment]
I think you either didn't restart your tmux properly after upgrading, or
you are missing something here, because tmux will not send bells unless
bell-on-alert is also on.

**Comment by tweekmonster** [comment]
What do you mean by restart?  I did restart tmux, as well as the machine, multiple times in the past couple of days for unrelated reasons.  Is there some sort of state information that's reloaded?  I can confirm that the server isn't running before reproduction:

```shell
$ tmux ls
no server running on /tmp/tmux-1000/default
```

I don't know what I could be missing if I'm using default options :/

Here's a Dockerfile that allows me to reproduce this in a bare environment:

```Dockerfile
FROM ubuntu

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

RUN locale-gen en_US en_US.UTF-8 \
      && apt-get update -y \
      && apt-get install -y build-essential git autoconf libevent-dev pkg-config libncurses-dev \
      && git clone https://github.com/tmux/tmux \
      && cd tmux \
      && ./autogen.sh && ./configure && make && make install

ENTRYPOINT ["tmux", "new"]
```

Within the container:

```
$ tmux setw -g monitor-activity on
$ printf '\x07'
$ # type anything
```

**Comment by nicm** [comment]
Please add -vvvv, reproduce and show me the server log file.

**Comment by tweekmonster** [comment]
tmux-server: http://sprunge.us/JXLe
tmux-out: http://sprunge.us/PRdD

**Comment by nicm** [comment]
Oh I'm wrong, the default bell-action is any... I must have changed it
here.

We need to clear the window flags after we have finished using them (and
set the corresponding winlink flags). Please try this:

diff --git a/alerts.c b/alerts.c
index 2dbdc40..43108ed 100644
--- a/alerts.c
+++ b/alerts.c
@@ -62,6 +62,8 @@ alerts_callback(__unused int fd, __unused short events, __unused void *arg)
 
 		w->alerts_queued = 0;
 		TAILQ_REMOVE(&alerts_list, w, alerts_entry);
+
+		w->flags &= ~WINDOW_ALERTFLAGS;
 		window_remove_ref(w);
 	}
 	alerts_fired = 0;

**Comment by tweekmonster** [comment]
That seems to have worked and I'm not crazy after all!  Is there a reason you weren't able to reproduce this?

**Comment by nicm** [comment]
No, I can't reproduce it at all but I don't know why. Applied the fix anyway.
