### ISSUE TITLE
Getting the error while running the selenium test with FF on macSierra

### ISSUE THREAD

**Issue by srinivaspullabhotla** [tmux/tmux#608]
Error is as below, any helpful hints please.
`1477511848111	geckodriver	INFO	Listening on 127.0.0.1:20665
Oct 26, 2016 12:57:29 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1477511849505	mozprofile::profile	INFO	Using profile path /var/folders/dk/xyw6v2zd1bd5sp8pd_4f8fpw0000gn/T/rust_mozprofile.XVzDPbJpHADa
1477511849507	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin
1477511849553	geckodriver::marionette	INFO	Connecting to Marionette on localhost:50185
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
1477511853075	Marionette	INFO	Listening on port 50185
1477511855791	Marionette	INFO	startBrowser f2b8b358-1795-514b-b9bb-2a96d663635c
Oct 26, 2016 12:57:36 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`

And the code is :
`public class sampleTest1 {
	public static void main (String[] args) {
		System.setProperty("webdriver.gecko.driver", "//Library/Java/geckodriver");
		WebDriver driver=new FirefoxDriver();
		String baseUrl = "http://www.seleniumhq.org";
		String et = "Selenium - Web Browser Automation";
		driver.get(baseUrl);
		String rt = driver.getTitle();
		if (rt.contentEquals(et)) {
			System.out.println("Title is matched");
		}
			else {
				System.out.println("Title is not matched");
			}
		}
		
	}`

**Comment by krader1961** [comment]
What does this have to do with tmux? If you're trying to say that this failure only occurs if you run the test from within a tmux session then make sure you're using `reattach-to-user-namespace`.

**Comment by srinivaspullabhotla** [comment]
Sorry about that. The forking was a mistake - its a generic question.

Thank you,
Srinivas
408.431.2129
