### ISSUE TITLE
Unresponsive when displaying a lot of output in vertical splits

### ISSUE THREAD

**Issue by cwatk** [tmux/tmux#609]
I think this is a 2.3 regression. 2.2 seemed fine. tmux gets really unresponsive when a lot of output is being displayed in vertical splits. I'm on ubuntu 14.04 using gnome terminal. To repro, open a vertical split and run 'yes' in one of them. Switching panes is slow. Sending ctrl-c is slow.

**Comment by nicm** [comment]
Please try tmux from Git.

**Comment by cwatk** [comment]
Just tried the tip of master. It's just as bad as 2.3 or worse.

I built 2.2 and it was a lot better. I was able to switch panes and send ctrl-c within ~0.5-1s. Whereas with 2.3 it takes 5-10s. It's easier to detach.

**Comment by nicm** [comment]
Yeah it might work or might not, the rate limiting had to change from 2.2 because it caused other problems. It's not really an easy problem to solve, I will no doubt revisit it again at some point.

**Comment by cwatk** [comment]
Fair enough. Thanks for your work. Until then I guess I'll try to avoid vertical splits.

**Comment by nicm** [comment]
In master you can try fiddling with READ_FAST_SIZE/READ_SLOW_SIZE and READ_CHANGE_HITS in tmux.h.

Try making SLOW smaller, but the problem is to avoid making one-off redraws slow (like starting or scrolling in emacs or something else full screen).

**Comment by nfischer** [comment]
@nicm is there any way to configure this behavior without recompiling, or any recommended workarounds? Vertical splits are my main reason for using tmux, but killing a long-running command in a vertical split makes the whole window hang, which is pretty painful. Thanks!

**Comment by randomekek** [comment]
It is still possible to kill the binary during a hang:

1. Ctrl+B d -- disconnect from tmux
1. kill/pkill -- kill noisy thing
1. Alternative: `tmux break-pane -t :` to move the thing into a separate pane
1. tmux attach-session -d

**Comment by rgfibe** [comment]
This can be pretty painful for very large outputs because your whole terminal locks while tmux is scrolling ("Ctrl+B d" is unresponsive) , and that can take several minutes.

My workaround is to open another terminal and detach that tmux session with "tmux detach-client -s <session_name>".  Once it's detached, scrolling finishes immediately and you can re-attach.
