### ISSUE TITLE
Copy-line adds trailing newline in 2.0

### ISSUE THREAD

**Issue by rwstauner** [tmux/tmux#61]
It appears that `copy-line` (and `copy-end-of-line`) changed slightly in 2.0.

With `mode-keys` set to `vi`...
In 1.9a (and, i believe, in all previous versions since the functionality was added in 1.5) the trailing newline was not included; in 2.0 it is.
`list-buffers` shows the difference:

```
0: 19 bytes: "@raptor:~/tmux-2.0$"
```

```
buffer0000: 20 bytes: "@raptor:~/tmux-2.0$\012"
```

Was this an intended change?  I didn't see any reference to it in the changelog.

For someone who used those features a lot, this is a big change.
Is it possible configure the old functionality?
Alternatively, if there was a way to bind a key to multiple commands in copy-mode I could compose the functionality myself, but I haven't been able to find a way to do that.

**Comment by rwstauner** [comment]
FWIW, the `end-of-line` command is visually the same in both, however what gets copied differs:
Htting `$` takes me (one character) past the last character on the line.
Hitting `h` then moves the cursor so that it is on the last character.

In 1.9a, neither position copies the newline.
In 2.0, being after the last character (`$`) copies the newline, and being on the last character (`h`) does not.

**Comment by rwstauner** [comment]
Looks like 00ac1af43fe6fe51cc199a9d983499ef7fd78cf5 is what changed the functionality.

**Comment by rwstauner** [comment]
So, I don't know why that commit was made, but at least for the time being i can switch to emacs mode and just rebind all the keys to get that functionality back.

**Comment by nicm** [comment]
Looks to me like this is how vim at least works.

**Comment by rwstauner** [comment]
If I load vim with no profile,
`D` deletes to the end of the line without the newline.
`Y` will yank the entire line including the newline.
I could probably live with it if tmux was consistent with that behavior,
but including the newline with `D` seems quite unhelpful.

I can see how this might come down to a preference,
but for pasting into a shell I would think more often than not that a person wouldn't want the trailing newline.  It seems much easier to add a missing newline than to remove an extraneous one.

Is there any possibility of making this configurable?
Or binding a mode key to more than one command?

While switching to emacs modes and rebinding all the keys to vi-style works, there might be other undocumented mode differences that i may not be prepared for.
For now I've bound my "paste" key to a `new-window` command that saves the buffer, chomps the newline, loads the buffer and then pastes.  It seems fast enough despite the obvious overhead, so I'll try this for a while.

**Comment by huozhe** [comment]
@rwstauner This also causes some headache to me. Do you mind to share your config lines to ```bound my "paste" key to a new-window command that saves the buffer, chomps the newline, loads the buffer and then pastes```?

**Comment by rwstauner** [comment]
Sure: https://github.com/rwstauner/run_control/blob/master/tmux/chomp-buffer.conf

**Comment by huozhe** [comment]
Thanks! Will try it out later today.

**Comment by rlister** [comment]
For reference, this works pretty nicely to handle this issue in a DWIM way:
https://github.com/knakayama/tmux-newline-detector

**Comment by axelson** [comment]
Is there a work-around for this if pasting in a non-tmux application?
