### ISSUE TITLE
Tmux 2.4 text selection in copy mode does not

### ISSUE THREAD

**Issue by smkniazi** [tmux/tmux#610]
in tmux 2.4 text selection does not work for me. Same config works on tmux 2.2

# vi mode 
setw -g mode-keys vi
set -g status-keys vi
set-window-option -g mode-keys vi
bind-key -t vi-copy 'v' begin-selection
#bind-key -t vi-copy 'y' copy-selection
bind -t vi-copy y copy-pipe 'xclip -in -selection clipboard'
bind -n M-[ copy-mode
bind -n M-] paste-buffer

I am using Fedora 24. Bash version 4.4.0 and I am using vi key binding for bash.

**Comment by tweekmonster** [comment]
The key tables have changed: https://github.com/tmux/tmux/commit/76d6d3641f271be1756e41494960d96714e7ee58

Change your bindings from

```
bind-key -t vi-copy 'v' begin-selection
```

 to

```
bind-key -T copy-mode-vi 'v' send -X begin-selection
```

**Comment by smkniazi** [comment]
Thanks it works :)

**Comment by lmayorga1980** [comment]
@smkniazi can you share your tmux config?

**Comment by chusiang** [comment]
Thanks for @tweekmonster, it's working, now.

Hi @lmayorga1980, maybe you can reference my fix.

> https://github.com/chusiang/tuxENV/commit/5c0570825640bb830f551ff01d300f2a3cfc994d

**Comment by lmayorga1980** [comment]
@chusiang ,

I am using this one for now https://gist.github.com/lmayorga1980/16dd5b49000f59fc51610e973d67d62f but want to check your fix as well.

👍
