### ISSUE TITLE
option '-n' in new-window command does not work at the end of command

### ISSUE THREAD

**Issue by linsong** [tmux/tmux#611]
running following command: 
```$ tmux -f empty_file.conf new-session -n shell \; new-window -n make```
expect the tmux session containing two windows: '0:shell' and '1:make', but the result is: '0:shell' and '1:shell' ;

```$ tmux -f empty_file.conf new-session -n shell \; new-window -n make \; new-window -n make```
will create a tmux session with 3 windows: '0:shell', '1:make' and '2:shell' . seems only the last '-n' option in new-window command does not work. 

I use an empty configuration file here to get rid of effect of my local .tmux.conf file. 

environment: 
```$ tmux -V ```
tmux 2.3 

macOS Sierra(10.12)

Pls let me know if you need more information.

tmux is awesome, thanks for the great work! :)

**Comment by nicm** [comment]
I can't reproduce this, it works fine for me. Please add -vvvv and show
me the tmux-server-*.log file.

**Comment by linsong** [comment]
sorry, I just find there is one configuration 
```set -g default-command "tmux rename-window shell; reattach-to-user-namespace -l /bin/bash"``` 
in my .tmux.conf file. In my above tests, tmux server still use .tmux.conf, although tmux client use 'empty_file.conf' as specified in the command line. 

I remove the configuration, shutdown tmux server and try again, it works well. Sorry for the false report, thanks for your time.
