### ISSUE TITLE
right statusbar broken again

### ISSUE THREAD

**Issue by supermarin** [tmux/tmux#614]
It worked for a while, just installed tmux from --HEAD again and it's broken.
It comes back if you `set status-bg black`, but doesn't work if default is `set status-bg default`

**Comment by nicm** [comment]
Can't reproduce, not that I have much hope with so little information.

**Comment by supermarin** [comment]
All the info is here: https://github.com/tmux/tmux/issues/560

**Comment by nicm** [comment]
Works for me. Logs?

**Comment by supermarin** [comment]
Crap, I haven't `killall tmux` beforehand and it seems like config was initialized with tmux 2.3.
I'm sorry for the noise, my bad this time! 🍺
