### ISSUE TITLE
Client failed to connect to the D-BUS daemon

### ISSUE THREAD

**Issue by Atcold** [tmux/tmux#616]
I'm not sure what is causing this.
I'm on a new account on a Ubuntu box, and when I run a script which drives some graphics from *tmux* I get:

```bash
(process:7616): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Failed to connect to socket /tmp/dbus-o8DqCJUmuu: Connection refused

(qlua:7616): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Failed to connect to socket /tmp/dbus-o8DqCJUmuu: Connection refused

(qlua:7616): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(qlua:7616): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(qlua:7616): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(qlua:7616): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(qlua:7616): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(qlua:7616): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```
If I `export $(dbus-launch)`, then everything works just fine.
Another user, on the same machine, does not see this quirk.
Any idea of what is going on?

**Comment by nicm** [comment]
Did you start tmux before the DBus environment stuff had been set up?

**Comment by Atcold** [comment]
I'm not sure about *who* sets up the DBus environment.
If I open a new *Terminal* and run the script, it connects just fine.
If I open a new *tmux* within the new *Terminal*, then it shows the same critical errors.

**Comment by nicm** [comment]
Are you sure you killed tmux entirely before opening a new one?

**Comment by Atcold** [comment]
No, I did not kill *tmux* before opening a new one. I had a sessions going.
Anyhow, a (forced) reboot of the system (which I wanted to avoid) fixed the problem.
Sorry for the noise. Nevertheless, I'm not sure I understood what was going on with the DBus thingy.

**Comment by nicm** [comment]
DBus has some environment variables, probably you started tmux before
DBus was started so those were not in the environment - if tmux didn't
know about them then it couldn't pass them to new panes.

**Comment by Atcold** [comment]
And, even issuing a new instance of *tmux* does not suffice because...?

**Comment by Aspect9** [comment]
i got "failed to connect to bus daemon" on Parrot Os...what to do, what to do...

**Comment by Atcold** [comment]
@Aspect9, try rebooting your system :stuck_out_tongue_winking_eye:
