### ISSUE TITLE
Load selection to buffer only after the selection is released

### ISSUE THREAD

**Issue by snehesht** [tmux/tmux#617]
I was playing with the copy-paste in tmux using the following config and found out that Tmux copies current text selection to buffer only after the selection is released. Is this intentional ?

```
bind -n C-y run "tmux save-buffer - | xsel -ib"
bind -n C-v run "xsel -ob | tmux load-buffer - ; tmux paste-buffer"
```
edit: changed run-shell to run

[![asciicast](https://asciinema.org/a/4p0nhx27cg5rs6ils99ajv6rr.png)](https://asciinema.org/a/4p0nhx27cg5rs6ils99ajv6rr)

**Comment by nicm** [comment]
tmux copies to a buffer when a key bound to copy-selection is invoked.

**Comment by snehesht** [comment]
I thought the same but that's not what's happening here. I didn't press any keys, unless mouse selection invokes a func to copy selection to buffer, I think tmux might store the selection to buffer after the selection is cleared, is that the case ?

**Comment by nicm** [comment]
MouseDragEnd1 key is normally bound to copy-selection.
