### ISSUE TITLE
Wrong pane focus with mouse click in vertical panes

### ISSUE THREAD

**Issue by raedah** [tmux/tmux#619]
Using the mouse to select the last pane while using vertical panes (columns) will not allow you to select the last (far right) pane. Focus instead goes to the first pane. Work around is cycling through panes using the keyboard to get there.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.

**Comment by arza-zara** [comment]
This is terminal-specific. Many terminals send mouse coordinates over ~224 incorrectly. xterm works.

**Comment by raedah** [comment]
I am using urxvt.

**Comment by nicm** [comment]
OK, I can't reproduce, even with a very wide terminal. Please show me the server log.

**Comment by raedah** [comment]
server log https://bpaste.net/show/c9a80fbd92be

this issue does seem to happen at coordinates after ~224 width, such as when the pane begins at over 224. Trying to use the mouse to drag and resize the pane size when it is already over 224 also fails.

**Comment by nicm** [comment]
Looks like your terminal doesn't support SGR mouse mode, so you will be
limited to 224 columns. Which is odd, because I have rxvt-unicode 9.21
here and it seems to work well above that. Still, probably you should
ask the rxvt-unicode folks.

**Comment by raedah** [comment]
For anyone looking here in the future, the fix for me was to switch from rxvt-unicode to rxvt-unicode-patched in the Arch AUR which includes sgr-mouse-mode.patch
