### ISSUE TITLE
#{pane_title} not updating with TERM=screen*

### ISSUE THREAD

**Issue by baco** [tmux/tmux#62]
if ``TERM`` environment variable is different from ``xterm``* or ``rxvt``* the variable ``pane_title`` does not get updated. Default ``TERM`` value inside tmux is ``screen`` or ``screen-256color``.

``#{pane_title}`` should be updated at least whith ``TERM=screen`` or ``TERM=screen-256color`` (not necessarily with any other values, but at least the values tmux works well with).

**Comment by nicm** [comment]
No, I think instead we should add the XT flag or tsl/fsl to the new tmux terminfo entry.

**Comment by nicm** [comment]
Hmm. Actually this should work, because we add XT to screen* in terminal-overrides. Did you remove that bit from terminal-overrides?

**Comment by nicm** [comment]
I've emailed terminfo upstream to ask if tsl/fsl can be added to TERM=tmux.
