### ISSUE TITLE
Underline attribute for consecutive words ignores spaces.

### ISSUE THREAD

**Issue by cHoco** [tmux/tmux#620]
**Platform:** OS X
**Version:** tmux git
**$TERM:**
- outside: `xterm-256color`
- inside: `tmux-256color`

Not sure if this is an issue with tmux or my terminal (I can't reproduce it in other terminals), but it renders correctly outside tmux.
When there are words with underline attribute, separated by space, the underline ignores the spaces.
Command used for testing `echo -e "\e[4mwords\e[0m \e[4msaparated\e[0m \e[4mby\e[0m \e[4mspaces\e[0m\n"`

Here's a screenshoot of how it looks inside tmux:
![screen shot 2016-10-30 at 19 27 59](https://cloud.githubusercontent.com/assets/85527/19838865/14b9b522-9ed8-11e6-8ab5-b6149c6130e8.png)

I can reproduce by launching tmux without a conf file.
Here are the logs: https://gist.github.com/cHoco/ec6ca16c05478f1f505ad908d1576422

Strangely if I enter copy-mode and cause the text to redraw (by selecting, scrolling it), or resize terminal it gets rendered correctly
EDIT: Forgot to mention the terminal emulator is iTerm2, latest nightly

**Comment by nicm** [comment]
Hmm. I can't reproduce this. My guess would be it is a terminal problem - tmux will not output anything different in different terminals if TERM outside is the same.

If you add another few -v when logging, you will get a tmux-out*.log file, can you show me it too? It will show what tmux is actually sending to the terminal.

**Comment by cHoco** [comment]
Thank you for taking the time to look at this, here there are all 3 logs files https://gist.github.com/cHoco/8a2703e2d07678f0940204ba2b99591f

**Comment by nicm** [comment]
I think the terminal is getting confused because tmux does not output the spaces as space, instead it is just moving the cursor right. Please try this outside tmux and see if it prints correctly:

printf '\033[4mwords\033[Csaparated\033[Cby\033[Cspaces\033[0m'

**Comment by cHoco** [comment]
You're right, it also doesn't work outside tmux with your test command.

**Comment by nicm** [comment]
You will need to report this as an issue to iterm2.

**Comment by cHoco** [comment]
Again, thank you so much for your help!
