### ISSUE TITLE
Weird stacked bottom bar on gnome terminal 3.20.2 and tmux 2.3-3 (debian testing)

### ISSUE THREAD

**Issue by niltonvasques** [tmux/tmux#621]
![image](https://cloud.githubusercontent.com/assets/2291529/19856863/1c959702-9f5a-11e6-95e2-45d00761d29b.png)

**Comment by niltonvasques** [comment]
After uninstall powerline this weird bug is gone. So I will close this issue here.

**Comment by flyinva** [comment]
Same problem with Debian Sid 

- powerline 2.5
- tmux 2.3
- terminator

**Comment by niltonvasques** [comment]
@flyinva Let me know if you found some solution to this. I've also reported this bug in debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842716
