### ISSUE TITLE
Tmux true color support.

### ISSUE THREAD

**Issue by yifanchen** [tmux/tmux#622]
I am on Neovim, trying to get this Atom color scheme(https://github.com/rakr/vim-one) working. It works completely fine after `let $NVIM_TUI_ENABLE_TRUE_COLOR=1` in `.vimrc`. However, it doesn't work right in Vim within Tmux. 
I figured that it might be some true color setting needed in my `.tmux.config`. So, I tried the following cmds that I saw on another thread #34, didn't seem working. Any ideas? 

```
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
```

```
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",screen-256color:Tc"
```

Correct color scheme in Vim by itself:
![image](https://cloud.githubusercontent.com/assets/2340896/19869569/7abe860a-9f72-11e6-887f-4416a75b07f6.png)

Wrong color scheme in Vim within Tmux:

![image](https://cloud.githubusercontent.com/assets/2340896/19869578/86b021d0-9f72-11e6-95ae-d89f31c83e0f.png)

I am on 10.12.1 Sierra
Tmux 2.3
iTerm 2.9
Neovim 0.1.4

**Comment by nicm** [comment]
tmux 2.1 is too old.

**Comment by snehesht** [comment]
what's the name of the color scheme ?

**Comment by yifanchen** [comment]
@nicm Just upgraded to 2.3, didn't seem working either.

**Comment by yifanchen** [comment]
@snehesht https://github.com/rakr/vim-one

**Comment by bubuzzz** [comment]
@yifanchen i used exactly your vim color and tmux does not seem to work. This is my tmux conf 

```
# List of plugins
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

bind Up select-pane -U
bind k select-pane -U
bind Down select-pane -D
bind j select-pane -D
bind Left select-pane -L
bind h select-pane -L
bind Right select-pane -R
bind l select-pane -R

# remap prefix from 'C-b' to 'C-x
unbind C-b
set -g prefix C-x
bind C-x send-prefix

# split panes using | and -
bind \ split-window -h
bind - split-window -v
unbind '"'
unbind %

#
# Set up tmux copy/paste
# Copy-paste integration, need to install reattach-to-user-namespace first (brew install reattach-to-user-namespace)
set-option -g default-shell /bin/zsh
set-option -g default-command "reattach-to-user-namespace -l zsh"
# set tmux to 256 colors
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -t vi-copy Enter
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"

# Bind ']' to use pbpaste
bind ] run "reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"

# fix the delay esc of vim
set -sg escape-time 0
```

Can you show me how did you config it please ?

**Comment by yifanchen** [comment]
@bubuzzz Have you tried to update your TMUX to the latest version? I wrote a blog post of how to set it up correctly. Maybe you can find it helpful. http://www.cyfyifanchen.com/neovim-true-color/

**Comment by bubuzzz** [comment]
@yifanchen thank for your reply. Sorry, i forget to mention the version. 

➜  tmux -V
tmux 2.3

on iterm 3.0.13

**Comment by yifanchen** [comment]
@bubuzzz Does that color work in Vim but in Tmux? Do you mind uploading the screenshot of the color-scheme when only running in Vim and the screenshot of the color-scheme when Vim is running inside Tmux?

**Comment by bubuzzz** [comment]
@yifanchen morning mate, this is the screenshot 
<img width="1322" alt="screen shot 2017-02-10 at 8 44 48 am" src="https://cloud.githubusercontent.com/assets/571736/22804467/4f353362-ef6d-11e6-97a8-9c99e71fbab3.png">

You can see that the left side is the tmux + vim and the right side is vim only. If running the true color testing in https://gist.github.com/XVilka/8346728, i will get the left side has the 256 color whereas the right side is true color 

<img width="1280" alt="screen shot 2017-02-10 at 8 47 53 am" src="https://cloud.githubusercontent.com/assets/571736/22804566/bcd5d822-ef6d-11e6-98b7-72a954d6554f.png">

I pasted my tmux config here again so it is easy to see https://gist.github.com/bubuzzz/4a6e975d23ce51be4fed76573af9696c  

Also, this is my $TERM 

➜  ~ echo $TERM
screen-256color

**Comment by bubuzzz** [comment]
oh, no problem. i think i didn't read the vim-one theme documentation correctly. I have to set the $TERM=xterm-color and apply the override in the tmux.conf like the doc and it started to work. Thank @yifanchen 👍

**Comment by yifanchen** [comment]
@bubuzzz Good luck, let me know if you can't get it working. I had to set the background color of iTerm manually to match the background color of the Vim-One theme.

**Comment by lifepillar** [comment]
I have updated tmux to v2.5 and the issue is gone.
