### ISSUE TITLE
Compatibility with Nvim-R

### ISSUE THREAD

**Issue by LiNk-NY** [tmux/tmux#624]
@nicm @tcunha @jalvesaq

Hi all,  
I was wondering if this version of Tmux is compatible with the newer Nvim-R plugin. 
I find Tmux-Vim-R to be a superb combo. 
I'm currently running Vim 8, Tmux 2.4, and NvimR (jalvesaq/Nvim-R) installed via Pathogen on Linux of course :penguin:. 

Thanks!

**Comment by nicm** [comment]
I don't know what this is or what compatibility with it would mean.

**Comment by krader1961** [comment]
The O.P. is referring to this [package](https://github.com/jalvesaq/Nvim-R) which provides a way to interact with a [R](https://www.r-project.org/) console from within Vim. I have no idea why he thinks tmux would in any way affect that configuration. For that matter he seems to imply he's already using that configuration under tmux so I would expect him to know if it was working or not.

**Comment by LiNk-NY** [comment]
The current configuration isn't working. 

This seems to be more of an issue for @jalvesaq since tmux seems to have little to do with the way new panels are created in tmux. 

I'll post it in the appropriate repository. Thanks.

**Comment by LiNk-NY** [comment]
Just to follow up: 
The issue pertained to a vim configuration in the `.vimrc`. 
For those looking to open Tmux panes with Nvim-R, enter `let g:R_tmux_split = 1` in your `.vimrc`.
