### ISSUE TITLE
Artifacts/ghosting issue

### ISSUE THREAD

**Issue by kyhy** [tmux/tmux#625]
Running:
zsh 5.2 (true color enabled)
tmux 2.3
OSX 10.21.1

Artifacts/ghosting seems to happen when a lot of repaint happens. I have found rendering issue in fzf and neovim so far. I don't have a reliable way of replicating the issue atm.

Here is an example:
![tmux](https://cloud.githubusercontent.com/assets/4664197/19945791/e58c8ab2-a0fe-11e6-9ebf-ff70aed1f898.gif)

I'm not entirely sure if tmux is the root cause of these issues... Any pointers would be appreciated.. thanks!

**Comment by nicm** [comment]
What is $TERM inside and outside tmux?

**Comment by kyhy** [comment]
both inside and outside: `xterm-256color`

**Comment by nicm** [comment]
TERM inside tmux must be screen* or tmux*.

**Comment by kyhy** [comment]
do I update $TERM in .tmux.conf?

**Comment by kyhy** [comment]
that did the trick! thank you @nicm 

For true color support in zsh with tmux, I did the following:
in .zshrc I added:
```[[ $TMUX = "" ]] && export TERM="xterm-256color"```
and in .tmux.conf:
```set -g default-terminal "screen-256color"```

hope that helps others. :D

**Comment by nicm** [comment]
terminal-overrides applies to the TERM outside tmux, so you probably want this:

set-option -ga terminal-overrides ",xterm-256color:Tc"

**Comment by kyhy** [comment]
thank you so much
