### ISSUE TITLE
Pane titles don't update quickly when using \w with long directory name

### ISSUE THREAD

**Issue by j8s0n** [tmux/tmux#626]
I have the following PS1 variable:
PS1="\[\033]0;\w\007\]$ "
This shows my current working directory in the titlebar of my terminals, and tmux panes.

I've got the following ~/.tmux.conf:
set-window-option -g window-status-current-fg blue
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

#set inactive/active window styles
set -g window-style 'fg=colour247,bg=colour235'
set -g window-active-style 'fg=colour250,bg=black'

set -g pane-border-status top
# set the pane border colors
set -g pane-border-fg colour250
set -g pane-border-bg colour236
set -g pane-active-border-fg colour17
set -g pane-active-border-bg colour250

When I get deeper in subdirectories than this:
"~/a/a/a/a/a/a/a/a/a/a"
or
"~/xxxxxxxxxxxxxxxxxxx"
it no longer updates the current path immediately.

I tried with different lengths of directory names, and it always cuts off just past 20 total characters. 
It always ends at a full component name, never truncating like the window level status bar does.
After an interval, it will update with the full pwd value (it's been anywhere from 10s to 56s, is there a redraw running on a one-minute timer?). It will also update as soon as I switch to a different pane (forced redraw?).
If the directory names are shorter than this, it will update instantly as I change in and out of directories.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.
