### ISSUE TITLE
Please make it sane to dump a buffer to disk

### ISSUE THREAD

**Issue by kaihendry** [tmux/tmux#629]
I am struggling to enter copy mode. :sob: 

http://unix.stackexchange.com/a/26552/27433 doesn't work for me on tmux 2.3 & it's so many key presses!

Also I noticed ...
https://github.com/tmux/tmux/commit/76d6d3641f271be1756e41494960d96714e7ee58

Furthermore when I do get copy mode working after I've sobered up, if I am using for example a narrow terminal, the flow of the output can be messed up.

Can we please please have a **simple** way to get terminal output out from tmux for logs and such use cases.

**Comment by nicm** [comment]
capture-pane

**Comment by nicm** [comment]
tmux capturep -pJ -E- -S- >x
