### ISSUE TITLE
/etc/tmux.conf

### ISSUE THREAD

**Issue by E1HC** [tmux/tmux#63]
Hi guys 
i update to tmux 2.0 and i have an issue with emacs/freebsd with the cursor
i load a tmux session without ~/.tmux.conf and the cursor in emacs it is back.

but my point is other :
i look for the /etc/tmux.conf and i can't find it in my system
why isn't a tmux.conf in the github ? 

i have examples in /usr/share/tmux/ 
but isn't a real tmux.conf 

tmux's man page says that : 
FILES
~/.tmux.conf       Default tmux configuration file.
 /etc/tmux.conf     System-wide configuration file.

it is any place for the file tmux.conf  after install in the OS ??

thanks for your time

**Comment by nicm** [comment]
There are no default config files, you have to create your own.

**Comment by E1HC** [comment]
ok nicm
how you manage the config lines if they change it ?
you need to search in other tmux web page or github fork project?

why tmux team don't have a tmux.conf just like other app 
for example spectrwm create /etc/spectrwn.conf

i mean soon or later you will change the default config
but i don't understand why they update all the code but not a real default tmux.conf

**Comment by nicm** [comment]
Some programs ship with a default config and some do not. tmux does not and will not, its defaults are builtin.

**Comment by E1HC** [comment]
nicm thanks for the answer
it is a BSD licence - that is why i ask about the defualt config like any BSD project
i saw /usr/share/tmux/  examples [some examples are from 2009]
and http://www.openbsd.org/faq/faq7.html#tmux
