### ISSUE TITLE
usable pane area got affected by vim lines

### ISSUE THREAD

**Issue by darluc** [tmux/tmux#630]
when vim not use the entire pane size and after I quit vim, the bottom of pane cannot be used. Unless I resize the terminal window.

![](http://ww4.sinaimg.cn/large/7327fe71gw1f9fxv7skjfj20ob0mimzi.jpg)

![](http://ww3.sinaimg.cn/large/7327fe71gw1f9fxurwuukj20ma0mdwgk.jpg)

**Comment by nicm** [comment]
This issue does not include enough information. Please read the
[CONTRIBUTING](https://github.com/tmux/tmux/blob/master/CONTRIBUTING)
file.

**Comment by darluc** [comment]
**tmux version:** tmux 2.3

**platform:** macOS Sierra Version 10.12.1

**steps to reproduce:** 
1. ssh to a centos server;
2. run 'vim';
3. quit vim;

**tmux config:**
set -g default-terminal "screen-256color"
set-option -g default-command "reattach-to-user-namespace -l ${SHELL}"
setw -g mode-keys vi
setw -g aggressive-resize on
unbind C-b
set-option -g prefix C-y

**my terminal:** iTerm2 3.0.9
**$TERM inside:** screen-256color
**$TERM outside:** xterm

**logs from tmux:**
[logs.zip](https://github.com/tmux/tmux/files/572360/logs.zip)

**Comment by nicm** [comment]
It appears as if vim is sending \033[1;24r to set a scroll region when
it starts, but it does not clear the scroll region when it exits.

Are you sure $TERM is still screen-256color after you ssh?

**Comment by darluc** [comment]
Yes. After ssh $TERM is still screen-256color

# zvz @ zvz in ~ [12:43:31]
$ padev 21

Last login: Sat Nov  5 02:32:32 from 10.59.91.3

# www @ dev-old001 in ~ [12:43:35]
$ echo $TERM
screen-256color

# www @ dev-old001 in ~ [12:43:40]
$

**Comment by nicm** [comment]
I guess either there is something wrong with the screen-256color entry
on that system, or this is a bug in vim.

**Comment by darluc** [comment]
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Apr  5 2012 10:17:30)         
Included patches: 1-411

**Comment by nicm** [comment]
I do not think this is a tmux problem, did you try asking the vim people?

**Comment by darluc** [comment]
Finally I find out the reason.
Because I use a python script to ssh the remote host and lose the $LINES variable.
