### ISSUE TITLE
Unicode character in status bar confuses tmux

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#632]
On macOS 10.11.6 running tmux built from recent master branch (around commit 13f1a922e180bc834), I am seeing an issue with a `~/.tmux.conf` containing only:

```
set -g status-left '#[fg=yellow]#S ⧉ '
```

Note the use of the Unicode char, ⧉, in there. This is `U+29C9` (`e2 a7 89` in UTF-8); the file is UTF-8 encoded (confirmed with `file ~/.tmux.conf`, and by hitting `g8` in Vim with the cursor over that character).

Specifically, even though the window is `n` columns wide, tmux is only drawing the status bar up to `n - 1` columns. Note that Vim is using the full `n` columns, because you can see the rightmost "%" character in the Vim statusline appears to the right of the rightmost character in the tmux statusline:

<img width="710" alt="tmux__tmux_" src="https://cloud.githubusercontent.com/assets/7074/20035964/532da9c0-a3b6-11e6-97b1-82dcefdd4c8e.png">

* `$TERM` inside tmux is `screen`.
* `$TERM` outside tmux is `xterm-256color`.
* Terminal is iTerm2 (3.0.12), but the same thing happens in the Apple Terminal.app.
* tmux client/server logs: [tmux-logs.zip](https://github.com/tmux/tmux/files/573697/tmux-logs.zip) (did some minor pruning to remove sensitive environment variables).

Getting rid of the Unicode char makes the problem go away. I don't think this happened before, so I suspect a regression although I haven't run a bisect yet.

**Comment by nicm** [comment]
These logs do not include this character at all so they are no use, please give me logs from printing the character.

**Comment by nicm** [comment]
That is, do printf "\342\247\211"

**Comment by wincent** [comment]
Here are some fresh logs: [logs.zip](https://github.com/tmux/tmux/files/574509/logs.zip)

Same `~/.tmux.conf` as before; opened a new session, did `printf "\342\247\211"`, then exited.

**Comment by nicm** [comment]
This looks fine, if you do:

printf 'a\342\227\217b'

inside and outside tmux, what does the terminal show in each case?

**Comment by nicm** [comment]
Wait forget that, I was looking at the wrong character.

**Comment by nicm** [comment]
Yes, tmux is being told that \342\247\211 is width 2 but it appears your terminal is expecting it to be width 1. If you are not building tmux with utf8proc, try that. If the same problem remains, then either the terminal or utf8proc is wrong about the width of the character (or they are using different Unicode specifications).

**Comment by wincent** [comment]
This was built using Homebrew (`brew install tmux --HEAD`), which under the covers configures with `--enable-utf8proc`.

> if the same problem remains, then either the terminal or utf8proc is wrong about the width of the character (or they are using different Unicode specifications).

Any idea how I can rule out one of your likely suspects?

**Comment by wincent** [comment]
So I decided to go ahead an bisect, first some manual steps:

* `HEAD` of `master`: buggy with `--enable-utf8proc`, works without it
* 2.3: buggy with `--enable-utf8proc`, works without it
* 6c94774b70f72 (first rev to add `--enable-utf8proc`: buggy with `--enable-utf8proc`, buggy without it
* 2.2: works

I was a little surprised that 6c94774b70f72 would be buggy without `--enable-utf8proc`, given that all the other revs I tested were fine without it. So I went ahead and did a full `git-bisect` from 2.2 to 6c94774b70f72 to see where it broke, and funnily enough, it bisects to 6c94774b70f72:

```
# bad: [6c94774b70f72952c4c512e4aa59a207ca1c34f2] Add support for using utf8proc with --enable-utf8proc, useful for platforms (like OS X) where the system implementation is crap. From Joshua Rubin.
# good: [9a4b45dc0fdefead3fe9d471e144da78163860d0] Add CHANGES notes for 2.2 release
git bisect start '6c94774b' '2.2'
# good: [95e304d1113410e1deb5245bfe8d55a1cd44a059] Merge branch 'obsd-master'
git bisect good 95e304d1113410e1deb5245bfe8d55a1cd44a059
# good: [697b912f2697f8729a3c337052fe9ee55b0089af] Merge branch 'master' of github.com:tmux/tmux
git bisect good 697b912f2697f8729a3c337052fe9ee55b0089af
# good: [d4eeeb5498822d4330f19534f5b25b70589aec1f] Merge branch 'obsd-master'
git bisect good d4eeeb5498822d4330f19534f5b25b70589aec1f
# skip: [537964b92dcd2b4a30fdf37a370f9a204fff561c] Kill empty window after moving pane and updating current window, so that index is still valid before renumber-windows happens. Fixes issue reported by Eric Pruitt.
git bisect skip 537964b92dcd2b4a30fdf37a370f9a204fff561c
# good: [1bc467fe52248410321cd4880b9688e514c406d7] Merge branch 'obsd-master'
git bisect good 1bc467fe52248410321cd4880b9688e514c406d7
# good: [ae297cb487590d0bb8e42e21e28926a1f957ad0b] Merge branch 'obsd-master'
git bisect good ae297cb487590d0bb8e42e21e28926a1f957ad0b
# first bad commit: [6c94774b70f72952c4c512e4aa59a207ca1c34f2] Add support for using utf8proc with --enable-utf8proc, useful for platforms (like OS X) where the system implementation is crap. From Joshua Rubin.
```

So I am a little puzzled about it, but I have a workaround, which is to run `HEAD` of `master` *without* `--enable-utf8proc`.

One other interesting thing to note: this issue seems to co-manifest with a bunch of other display issues. See this screenshot:

![vim___glh-mbp___tmux___zsh__tmux_](https://cloud.githubusercontent.com/assets/7074/20072229/65b7aa9c-a4dc-11e6-92fd-767e33285904.png)

When the status line is acting up, Vim redraw is also acting up. Note the truncated "%" signs at the right of the Vim status lines, and also note how the quickfix listing has a line redrawing crazily off to the left. At all the revs during bisection, I was able to repro these redraw issues in Vim whenever the tmux status line issue was occurring, so I think they are actually manifestations of the same underlying problem.

**Comment by nicm** [comment]
If tmux (via utf8proc or libc) and the terminal disagree about the width of Unicode characters, you will see display problems.

**Comment by wincent** [comment]
Sadly looks like utf8proc causes more problems than it fixes. Going to close this as a dupe of #631.
