### ISSUE TITLE
Is it possible to change the pane backgroundcolor when in copy mode?

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#634]
This is something that happens a lot: an errant mouse wheel event or keystrokes sends a pane into copy-mode, but we don't notice it because we're not focusing on the top-right corner of the pane. 

It'd be great if theres a way to style the pane background whenever copy-mode is enabled. We already have `window-active-style` which works so great for using bg color to identify the focused pane.

**Comment by nicm** [comment]
No it is not possible and I do not really see a compelling reason to add it.

**Comment by unphased** [comment]
The compelling reason is to visually indicate the mode-change. 

Modal interfaces are extremely powerful (I am also a vim user) but visual indicators tuned to the user's preferred level of attention aids usability dramatically.

**Comment by atsepkov** [comment]
+1 on this, I've gotten trolled by being in copy mode without realizing it on multiple occasions. I should also mention that my tmux control sequence is a backtick rather than ctrl+a, so perhaps this is not as common of a case for someone whose combo isn't as easy to accidentally trigger in vim.

**Comment by unphased** [comment]
well, you have to hit something additional to the tmux escape prefix to enter copy mode (default is `[`), but in most configs a single mouse wheel up event caught by the terminal emulator will cause a pane to enter copy-mode, and we want to visually highlight this in a way that is configurably more prominent than just a few characters on the top right corner in yellow.

**Comment by nicm** [comment]
You can probably do it with the pane-mode-changed hook now.

**Comment by unphased** [comment]
I got as far as this: 

    set-hook -g pane-mode-changed "display-message '#{?pane_in_mode,copy,normal}'"

that works a treat.

    set-hook -g pane-mode-changed "select-pane -P '#{?pane_in_mode,bg=blue,}'"

this is more what I want but gives me 

![image](https://user-images.githubusercontent.com/1542910/59328704-11633c80-8cbb-11e9-9b82-f1cae254cb29.png)

I just need some kind of "eval" style functionality here...

**Comment by nicm** [comment]
Use if -F for the condition and two selectp commands as the true and false
arguments.

**Comment by unphased** [comment]
I knew there was a way but have gotten rusty on the specifics. Thank you. Will confirm if it works shortly.

**Comment by unphased** [comment]
I've got this: 

    set-hook -g pane-mode-changed 'if -F "#{pane_in_mode}" "selectp -P bg=blue" "selectp -P \"\""'

However the problem is that if I use the mouse to scroll a different pane, the active pane's bg gets manipulated. So close!

**Comment by unphased** [comment]
Maybe if there was some way to query the `%pane-mode-changed` value from in that hook.

**Comment by nicm** [comment]
Hmm that isn't right, the target for the hook should be the mouse pane if
it is present, probably an omission, I'll take a look when I get home.

**Comment by nicm** [comment]
You could try adding -t= to the select-pane commands but it might change
the active pane.

**Comment by unphased** [comment]
it just says "No mouse target" if I add the `-t=`.

**Comment by unphased** [comment]
BTW I'm on commit `53914e50 - (HEAD, tag: 3.0)`

**Comment by nicm** [comment]
This should fix it. Although you could also change the WheelUpPane binding to select the pane (if you scroll the wheel a second time copy mode will select it anyway).
~~~~
--- cmd-if-shell.c      25 May 2019 07:15:53 -0000      1.62
+++ cmd-if-shell.c      12 Jun 2019 07:37:24 -0000
@@ -67,6 +67,7 @@ cmd_if_shell_exec(struct cmd *self, stru
        struct cmd_if_shell_data        *cdata;
        char                            *shellcmd, *cmd;
        struct cmdq_item                *new_item;
+       struct cmd_find_state           *fs = &item->target;
        struct client                   *c = cmd_find_client(item, NULL, 1);
        struct session                  *s = item->target.s;
        struct winlink                  *wl = item->target.wl;
@@ -103,7 +104,7 @@ cmd_if_shell_exec(struct cmd *self, stru
                        free(pr->error);
                        return (CMD_RETURN_ERROR);
                case CMD_PARSE_SUCCESS:
-                       new_item = cmdq_get_command(pr->cmdlist, NULL, m, 0);
+                       new_item = cmdq_get_command(pr->cmdlist, fs, m, 0);
                        cmdq_insert_after(item, new_item);
                        cmd_list_free(pr->cmdlist);
                        break;

**Comment by nicm** [comment]
This is the key binding I am trying:
~~~~
set-hook -g pane-mode-changed { if -F "#{pane_in_mode}" "selectp -P bg=blue" "selectp -P default" }

**Comment by unphased** [comment]
Thanks for the nice example of v3.0 conf syntax. My configuration is in dire need of rewriting with braces. 

Yes. I use the `nhdaly/tmux-better-mouse-mode` tmux plugin manager plugin, with the `set -g @scroll-without-changing-pane "on"` option set. It's quite nice as you can keep keyboard focus in an editor in one pane while using your mouse to accomplish scrolling in any other pane you want. So in light of that innate ability within tmux, I think it would be best for the correct target pane of this hook to be the pane that actually entered the mode, rather than just relying on changing the active pane.

Do you reckon this code change safe for inclusion into the code?

**Comment by nicm** [comment]
Yes, does it work?

**Comment by unphased** [comment]
I have only done a cursory test (though with many windows and panes) and it works admirably.
