### ISSUE TITLE
[lost server] when running run-shell -b "asdf"

### ISSUE THREAD

**Issue by sergei-dyshel** [tmux/tmux#635]
Reproduced by running `tmux -f /dev/null` and then entering command `:run-shell -b "asdf"`.
Bisect shows that the bug was introduced with merge c67b702

**Comment by sergei-dyshel** [comment]
Instead of `asdf` you can use any other invalid command, of course

**Comment by nicm** [comment]
Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/578105/x.diff.txt)

**Comment by sergei-dyshel** [comment]
Thanks, it works!

**Comment by nicm** [comment]
Applied thanks.

**Comment by sergei-dyshel** [comment]
@nicm, I think there is still a problem with your fix. I'm observing that by reproducing the issue and also I can see the reason in the code (though do not know how to fix it properly).

In `cmd_run_shell_exec()` there are lines:
```c
	if (!args_has(args, 'b'))
		cdata->item = item;
```
so basically `cdata->item == NULL` for `run -b` commands. After fix `cmd_run_shell_print()`  includes:
```c
	if (cdata->item != NULL && wp == NULL) {
		cmdq_print(cdata->item, "%s", msg);
		return;
	}

	if (window_pane_set_mode(wp, &window_copy_mode) == 0)
		window_copy_init_for_output(wp);
```
so the `if` is not taken and then server crashes in `window_pane_set_mode` (since `wp == NULL`).

**Comment by nicm** [comment]
Oops I changed it several times and I guess I got it wrong the last time,
I'll fix it when I get home.

**Comment by sergei-dyshel** [comment]
I tried removing `if (!args_has(args, 'b'))` line (so that `cdata->item` is always initialized) and it seems to do the trick.

**Comment by nicm** [comment]
Looks like I applied the wrong fix entirely, just fixed it now, hopefully. Should be in Git soon.
