### ISSUE TITLE
tmux ignores printing escape

### ISSUE THREAD

**Issue by dasJ** [tmux/tmux#636]
I want to use the print escape codes for vt100 like this:
```
echo "\033[5ithis is a test\033[4i"
```
Just running this works, my terminal emulator prints "this is a test".
When I execute this in tmux, nothing happens.

I run tmux like this:

```
TERM=screen-256color tmux -2
```

Relevant parts from my tmux.conf:
```
set -ga terminal-overrides ',st*:Tc'
set -g default-terminal "screen-256color"
```

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.

**Comment by nicm** [comment]
Actually, I misread this, I don't even need to know the version to tell you that these aren't supported.

**Comment by dasJ** [comment]
I'm sorry, these are the missing infromation:

- OS: Arch Linux
- Version: tmux 2.3
- Terminal Emulator: Kitty on Windows

I hope that's all you need

**Comment by nicm** [comment]
We don't support printing and it is not really practical to do so (which client do we choose to print to?). And I don't think there is much demand for it really anyway.

**Comment by dasJ** [comment]
@nicm I want to clearify my use case.
I use kitty (a putty replacement) on windows. Copying to the clipboard with tmux is rather annoying because kitty doesn't know about the splits and copies them all. So I basically want something like xclip where I can pipe command output to.
I found [this site](http://aplawrence.com/Unixart/transparent_printing.html) where they explain how to use xterm's escapes for that:
```
echo "\033[5ithis is a test\033[4i"
```
The printer this will be sent to is selected in the kitty configuration. Kitty, unlike putty, is able to use the windows clipboard as a printing target, which would be exactly what I need. I would just pipe my command to a small shell function which prints it to the windows clipboard.

This functionality works great when just executed, but I'm almost always in tmux which somehow prevents this from working. I tried with `TERM=xterm echo ...` but it doesn't work either.

Is the actual use case clear and worth a look in your opinion?

Thank you

**Comment by nicm** [comment]
For this you should be able to use the tmux bypass escape sequence (you
need to double up any escapes):

printf '\033Ptmux;\033\033[5iwhatever text\033\033[4i\033\\'

(But I would recommend looking for a terminal that supports xterm's
clipboard escape sequence instead which tmux already handles.)
