### ISSUE TITLE
Ambiguous console cursor position

### ISSUE THREAD

**Issue by everedifice** [tmux/tmux#637]
Today i updated tmux 2.4 by homebrew.

There is additional whitespace between info and cursor

![_2016-11-09_ _5_41_30](https://cloud.githubusercontent.com/assets/1061205/20132014/44a89d56-a6a4-11e6-8a8f-98a51a7645d4.png)

Is there any way to clear this whitespace?

**Comment by wincent** [comment]
Possibly related to #631/#632?

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING (https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.
