### ISSUE TITLE
issues displaying 'ⓔ'

### ISSUE THREAD

**Issue by Galbar** [tmux/tmux#639]
Yesterday I installed tmux from HEAD using `brew` in mac osx sierra. If I run `tmux -V` it says _tmux 2.4_

I have been using it for a while (not the version from HEAD) and I use something like the following in my prompt to know if I have a python virtual environment active:
```$(if [[ "$VIRTUAL_ENV" != "" ]]; then echo "ⓔ"; fi)```

In the HEAD version I installed yesterday it the character 'ⓔ' displays as a whitespace when in vim and when displayed in the prompt it puts the cursor in the beginning of the line.

This works perfectly if not in tmux and it used to work fine in the previous installation of tmux (sorry I don't know what version was it... the one by default from brew(?))

terminal: iterm2
$TERM: screen-256color
[tmux-server-32475.log](https://github.com/tmux/tmux/files/585473/tmux-server-32475.txt)

**Comment by Galbar** [comment]
After looking into it a bit longer, it seems that '✔' has something to do with it too

**Comment by nicm** [comment]
This character is \342\222\272 which does not appear in this log. Please show a log from printing this character (printf  "\342\222\272").

However, this is almost certainly another case of the terminal and locale implementation disagreeing about the Unicode version or about the width of these characters. If you are not using utf8proc, try using it, otherwise is this a problem with either the terminal, the font, or utf8proc.

**Comment by Galbar** [comment]
The reason I'm reporting this issue is because with tmux 2.3 in the same pc, terminal, config, etc. It works fine.
I don't know about utf8proc.

**Comment by nicm** [comment]
Right but we changed so that tmux believes what it is told by utf8proc for
symbols instead of overriding it.

**Comment by Galbar** [comment]
I edited my previous comment because I sent it by mistake incomplete. I added more info, could you check it? 😄 (I don't know how editing a comment works over email)

**Comment by nicm** [comment]
Please get logs by killing tmux then running tmux -vvvv new, printing the problem characters, then exiting tmux. There will be a tmux-server-*.log file in the current directory.

**Comment by Galbar** [comment]
There you go! installed from HEAD: `brew install --HEAD tmux --with-utf8proc`
[tmux-server-78384.txt](https://github.com/tmux/tmux/files/592040/tmux-server-78384.txt)

**Comment by nicm** [comment]
utf8proc is telling tmux this \342\222\272 is width 2 but it appears your terminal thinks it is width 1.
