### ISSUE TITLE
Why hex color is different?

### ISSUE THREAD

**Issue by zchee** [tmux/tmux#64]
Hi @ThomasAdam.

I build tmux HEAD.

Next, I tried `printf "\x1b[48;2;71;85;91mCOLOR\x1b[0m\n"`, but result bg color is hex `#4e4e4e`.
In fact, `71;85;91` is hex `#49555b`

Why hex color is different?
Do you have any idea?

===

Environments
- OS X Yosemite and El Capitan
- iTerm2 and OS X Terminal
- xscope(Hex color check)

**Comment by nicm** [comment]
The closest colour to 47555b is colour 238 which is 4e4e4e.

**Comment by zchee** [comment]
@nicm Thanks reply.
So, tmux doesn't support 24bit true color?

I think you already know, but,
[choppsv1 are posted tmux true color support diff](https://gist.github.com/choppsv1/dd00858d4f7f356ce2cf).
I want to know why don't merge that diff?
If there is information(or issue) about it, I want you to tell me.

**Comment by saitoha** [comment]
@zchee This specification(konsole-style 3byte color mode) proposed in various places by various people seems to be broken. It also has a clear problem from the point of view of backward compatibility. It gives more serious impacts to the terminal world than probably you can imagine. If we want to propose new or extended terminal control sequence, we should learn the proper and practical way for it.

**Comment by zchee** [comment]
@saitoha Thanks reply.
and, I understand problem.

Since detailed want to talk a little more to hear, please take the contact with twitter.
