### ISSUE TITLE
Pipe-pane not working properly

### ISSUE THREAD

**Issue by korosuke114** [tmux/tmux#641]
Dear Admin,

I'm facing pipe-pane output issue.

Environment : tmux2.3
MacOS Yosemite 10.10.5

<pipe-pane command>

bind-key H pipe-pane "cat >>$HOME/tmuxLog/`date +%Y%m%d-%H%M`-#S.#I.#P.log"
bind-key h pipe-pane

When I get tmux working log by pipe-pane. all of pipe-pane output could not print properly
Here is my output sample.

in Terminal window shown as follow.

< terminal output >
MacBook-Pro:Library hoge$ ls -al
total 24
drwx------@  57 hoge  staff  1938 12 14  2015 .
drwxr-xr-x+  52 hoge  staff  1768 11 12 02:42 ..
-rw-r--r--@   1 hoge  staff  8196 11 22  2015 .DS_Store
-rw-r--r--    1 hoge  staff     0 11 14  2014 .localized
drwx------    5 hoge  staff   170 11 14  2014 Accounts
drwxr-xr-x    4 hoge  staff   136 12 31  2014 Address Book Plug-Ins
drwxr-xr-x    4 hoge  staff   136  6 14 21:05 Application Scripts
drwx------+  43 hoge  staff  1462  9  1 20:12 Application Support
drwx------+   2 hoge  staff    68 11 14  2014 Assistants
drwx------+   5 hoge  staff   170 11 14  2014 Audio
drwx------    2 hoge  staff    68 12  1  2015 Autosave Information
drwx------+  93 hoge  staff  3162 11 12 15:48 Caches
drwxr-xr-x   11 hoge  staff   374  6 14  2015 Calendars
drwx------+   2 hoge  staff    68 11 14  2014 ColorPickers
drwx------+   2 hoge  staff    68 11 14  2014 Colors
drwx------+   3 hoge  staff   102 11 14  2014 Compositions
drwx------   68 hoge  staff  2312  8 14 21:23 Containers
drwxr-xr-x    7 hoge  staff   238 11 12 15:36 Cookies
drwxr-xr-x    4 hoge  staff   136 10 23  2015 Developer
drwxr-xr-x    4 hoge  staff   136 11 14  2014 Dictionaries
drwx------+   3 hoge  staff   102 11 14  2014 Favorites
drwx------+   8 hoge  staff   272 11 14  2014 FontCollections
drwx------+   2 hoge  staff    68 11 14  2014 Fonts
drwx--x--x    3 hoge  staff   102 10 21  2015 GameKit
drwxr-xr-x    4 hoge  staff   136 12 13  2014 Google
drwx------    9 hoge  staff   306  7 23 11:56 Group Containers
drwx------    5 hoge  staff   170 11 14  2014 IdentityServices
drwx------+   3 hoge  staff   102 11 14  2014 Input Methods
drwx------+   3 hoge  staff   102 12 14  2015 Internet Plug-Ins
drwxr-xr-x    3 hoge  staff   102 11 20  2014 Java
drwx------+   2 hoge  staff    68 11 14  2014 Keyboard Layouts
drwxr-xr-x   13 hoge  staff   442 11 12 15:34 Keychains
drwxr-xr-x   12 hoge  staff   408  8 16 23:00 LanguageModeling
drwxr-xr-x    4 hoge  staff   136  7 12 20:04 LaunchAgents
drwx------+  33 hoge  staff  1122 11 11 22:23 Logs
drwx------    3 hoge  staff   102 11 14  2014 Mail
drwx------    7 hoge  staff   238  6 13  2015 Messages
drwx------    3 hoge  staff   102 11 18  2014 Mozilla
drwx------+   2 hoge  staff    68 11 14  2014 PreferencePanes
drwx------+ 223 hoge  staff  7582 11 12 15:49 Preferences
drwx------+   3 hoge  staff   102  8  7 18:44 Printers
drwxr-xr-x    5 hoge  staff   170 11 14  2014 PubSub
drwxr-xr-x    4 hoge  staff   136 12 14  2015 Receipts
drwxr-xr-x   29 hoge  staff   986 11 12 15:38 Safari
drwx------   29 hoge  staff   986 11 12 15:34 Saved Application State
drwx------+   2 hoge  staff    68 11 14  2014 Screen Savers
drwx------+   2 hoge  staff    68 11 14  2014 Services
drwx------+   2 hoge  staff    68 11 14  2014 Sounds
drwx------+   5 hoge  staff   170  8 22 21:10 Spelling
drwxr-xr-x    9 hoge  staff   306 11 12 15:41 SyncedPreferences
drwxr-xr-x    4 hoge  staff   136  9 23  2015 TextWrangler
drwx------    5 hoge  staff   170 11 18  2014 Thunderbird
drwx------+   2 hoge  staff    68 11 14  2014 Voices
drwx------    6 hoge  staff   204 11 10  2015 WebKit
drwxr-xr-x    3 hoge  staff   102 11 12 15:18 com.apple.nsurlsessiond
drwx------+   4 hoge  staff   136 11 14  2014 iMovie
drwxr-xr-x    5 hoge  staff   170 11  8  2015 iTunes
MacBook-Pro:Library hoge$
[0] 0:*:[bash]:MacBook-Pro.local                                                  LoAvg  2016/11/12 15:53

<< Pipe-pane output >>

But pipe-pane output followings. pipe-pane could not output completely and missing output line a lots.

tal 24
@  57 hoge  staff  1938 12 14  2015 .
drwxr-xr-x+  52 hoge  staff  1768 11 12 02:42 ..
014 .localized
drwx------    5 hoge  staff   170 11 14  2014 Accounts
drwxr-xr-x    4 hoge  staff   136 12 31  2014 Address Book Plug-Ins
drwxr-xr-x    4 hoge  staff   136  6 14 21:05 Application Scripts
drwx------+  43 hoge  staff  1462  9  1 20:12 Application Support
drwx------+   2 hoge  staff    68 11 14  2014 Assistants
drwx------+   5 hoge  staff   170 11 14  2014 Audio
drwx------    2 hoge  staff    68 12  1  2015 Autosave Information
drwx------+  93 hoge  staff  3162 11 12 15:48 Caches
drwxr-xr-x   11 hoge  staff   374  6 14  2015 Calendars
drwx------+   2 hoge  staff    68 11 14  2014 ColorPickers
drwx------+   2 hoge  staff    68 11 14  2014 Colors
drwx------+   3 hoge  staff   102 11 14  2014 Compositions
drwx------   68 hoge  staff  2312  8 14 21:23 Containers
drwxr-xr-x    7 hoge  staff   238 11 12 15:36 Cookies
drwxr-xr-x    4 hoge  staff   136 10 23  2015 Developer

I would like to know can I fix this issue by some workaround.

**Comment by nicm** [comment]
There is a bug in 2.3, please try Git master.

**Comment by korosuke114** [comment]
Thanks nicm,

I tried to use tmux 2.2. it version works fine.
This is first post, what exactly version is master? 2.2?

Thanks

**Comment by nicm** [comment]
Master is checkout from latest git.
