### ISSUE TITLE
Tmux easy session startup

### ISSUE THREAD

**Issue by pickfire** [tmux/tmux#643]
Hi, I have recently started using tmux again since I have found it really nice to use it over ssh and for checking the page history.

I would like to create some startup files in `~/.tmux/` in which `~/.tmux/arch` would be my laptop and `~/.tmux/alarm` would be the pi but I can't source it using:
```
source-file ~/.tmux/#h
```
Or is there any alternative to this method?

**Comment by ThomasAdam** [comment]
`source-file` doesn't expand formats.  Use `if-shell` to do this instead.

**Comment by pickfire** [comment]
@ThomasAdam Ah, thanks a lot for the answer.
