### ISSUE TITLE
true color support happens something wrong

### ISSUE THREAD

**Issue by springmoonlight** [tmux/tmux#644]
As the picture shows, I found tmux (2.3) can not display true colors right.

<img width="974" alt="qq20161113-0 2x" src="https://cloud.githubusercontent.com/assets/1595077/20243768/73bbfecc-a9a0-11e6-9f2e-838ded111d0a.png">

I did search the solution among the closed issues, but failed to find one.

Is there anyone encounter this problem?

Thanks.

**Comment by krader1961** [comment]
What is $TERM outside and inside tmux? What terminal emulator, including its version, are you using?

**Comment by springmoonlight** [comment]
Thanks. 

iTerm2 3.0.10
outside tmux $TERM=xterm-256color
inside tmux $TERM=screen

By the way, I tried to set TERM as screen-256color, and it does not work.

**Comment by krader1961** [comment]
Your screen shots imply you're also using zsh. Is that correct? I haven't used zsh in quite a while. I use fish now and it, for example, bases whether or not it will automatically enable true color support on several factors including the TERM value. You may need to do something extra to get zsh to use true colors with TERM=screen. Also, for true color support inside tmux I'm pretty sure you need to add a terminal override to your *~/.tmux.conf*: `set-option -ga terminal-overrides ",xterm-256color:Tc"`.

**Comment by springmoonlight** [comment]
Thanks. I think the problem is not at zsh. Because outside tmux, zsh display true color right.

**Comment by krader1961** [comment]
Does adding the terminal override to your tmux.conf I mentioned fix the problem for you?

**Comment by springmoonlight** [comment]
Yes, but still wrong.

**Comment by nicm** [comment]
Show your config.

**Comment by springmoonlight** [comment]
Thanks!

![image](https://cloud.githubusercontent.com/assets/1595077/20333468/ad97c820-abed-11e6-8cad-194fc284f962.png)


[tmux.conf.txt](https://github.com/tmux/tmux/files/593686/tmux.conf.txt)

**Comment by nicm** [comment]
Did you restart tmux entirely after adding the terminal-overrides line?
Try "tmux kill-server" then run it again.

**Comment by springmoonlight** [comment]
Yes, I restart my computer.

**Comment by nicm** [comment]
Show me the script you are testing with.

**Comment by nicm** [comment]
Also show me output of:

tmux show -s terminal-overrides

Inside tmux.

**Comment by tracyone** [comment]
same problem
zsh user

**Comment by tracyone** [comment]
solved it.

remove this line  in .zshrc

```bash
export TERM=xterm-256color
````

**Comment by springmoonlight** [comment]
terminal-overrides "xterm*:XT:Ms=\E]52;%p1%s;%p2%s\007:Cs=\E]12;%p1%s\007:Cr=\E]112\007:Ss=\E[%p1%d q:Se=\E[2 q,screen*:XT,*:Tc"

**Comment by springmoonlight** [comment]
`terminal-overrides "xterm*:XT:Ms=\E]52;%p1%s;%p2%s\007:Cs=\E]12;%p1%s\007:Cr=\E]112\007:Ss=\E[%p1%d q:Se=\E[2 q,screen*:XT,*:Tc"`

**Comment by nicm** [comment]
OK so please do this:

pkill tmux
tmux -vvvv new
exit

Then show me the tmux-server-*.log file from the current directory.

**Comment by springmoonlight** [comment]
Thanks again!

[tmux-server-1528.log.txt](https://github.com/tmux/tmux/files/599471/tmux-server-1528.log.txt)

**Comment by springmoonlight** [comment]
Thanks again.

[tmux-server-2438.log.txt](https://github.com/tmux/tmux/files/599487/tmux-server-2438.log.txt)

**Comment by nicm** [comment]
Your script is using :s not ;s to separate the escape sequences, this is
not (and will not be) supported by tmux.

So the script needs to send:

 \033[48;2;0;172;255m

Not:

 \033[48:2:0:172:255m

**Comment by springmoonlight** [comment]
I change :s to ;s, and it works. You are so cool, and thanks a lot!
