### ISSUE TITLE
tmux crashes when doing prefix-o in a zoomed pane

### ISSUE THREAD

**Issue by sphaugh** [tmux/tmux#645]
- platform: Linux
- steps to reproduce: split a window, zoom one of the panes, try prefix-o, tmux crashes
- repro'd w/o config
- terminal: st, TERM=st-256color and TERM=screen-256color

[tmux-server-1781.log.txt](https://github.com/tmux/tmux/files/589805/tmux-server-1781.log.txt)

I think it used to be that tmux would unzoom the window and select the next pane.

**Comment by nicm** [comment]
You need this, just applied now, will be in GitHub soon:
~~~~
@@ -48,6 +48,8 @@ cmd_rotate_window_exec(struct cmd *self,
        struct window_pane      *wp, *wp2;
        struct layout_cell      *lc;
        u_int                    sx, sy, xoff, yoff;
+
+       server_unzoom_window(w);

        if (args_has(self->args, 'D')) {
                wp = TAILQ_LAST(&w->panes, window_panes);

**Comment by nicm** [comment]
Thanks

**Comment by sphaugh** [comment]
nic, I think cmd_select_pane_exec needs this as well. tmux is still crashing when I do prefix-o which is `select-pane -t :.+` for me.

**Comment by nicm** [comment]
This is a different problem, the pane can be found be :.+ but because it is zoomed it is no longer considered visible so it fails the valid target check. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/591601/x.diff.txt)

**Comment by nicm** [comment]
I thought o was rotate-window but it is C-o :-).

**Comment by sphaugh** [comment]
Nice, looks good!
