### ISSUE TITLE
Tmux detecting emoji as single-width

### ISSUE THREAD

**Issue by wyqydsyq** [tmux/tmux#647]
I'm using tmux `2.3` under fish-shell `2.4.0`, I'm using some unicode characters in my fish prompt (emojis for "Home" and "Computer" to represent "~" and "/" respectively) and tmux appears to incorrectly detect these emojis as single-width. When a new prompt appears the cursor is in the correct position, but as soon as tmux recalculates (either automatically or on input) the cursor is moved -1 position. I was under the impression both tmux and fish use `glibc`'s `wcwidth()` so thought they would be compatible out of the box.

My `$TERM` is `xterm-256color`, the fonts are all correctly installed and the fish prompt works flawlessly with these emoji characters when it's not being ran inside of tmux.

I've searched around and saw a few similar issues but they seem either a bit different or are already closed.

Is there some way I could force tmux to treat these characters as 2-width via config as a temporary work-around?

**Comment by nicm** [comment]
This is probably a bug in glibc.

**Comment by nicm** [comment]
Show logs please from printing one problem character.

**Comment by wyqydsyq** [comment]
Looking into it further it seems this issue actually is happening without tmux now (whenever I use an emoji in my terminal), and I'm getting this behaviour with both gnome-terminal and QTerminal so it seems this is actually a bug in `libvte` which both are using as I can't reproduce this issue using the `st` emulator.

I've [opened an issue](https://bugzilla.gnome.org/show_bug.cgi?id=774510) on vte's Bugzilla for this, might wanna close this issue here 👍
