### ISSUE TITLE
tmux is not preserving the distinction between soft and hard newlines

### ISSUE THREAD

**Issue by timotheecour** [tmux/tmux#65]
In https://gitlab.com/gnachman/iterm2/issues/3590 I reported a bug in iterm2 in which, under tmux, in some cases, multiline mouse-select of wrapped text includes newlines.
I've attached in that bug a reproducible test case. According to George Nachman (iterm2 dev), this is due to tmux not preserving the distinction between soft and hard newlines (see his answer here: https://gitlab.com/gnachman/iterm2/issues/3590#note_1368481)

Is that something that could be fixed?

**Comment by nicm** [comment]
What tmux version? Are you using copy mode?

**Comment by timotheecour** [comment]
i'm using tmux 2.0, on OSX
the exact steps are listed in https://gitlab.com/gnachman/iterm2/issues/3590#note_1313341
here's a snippet:

1) start log

2) tmux

3) control b + percent

to split pane horizontally

4) cat ~/.history|grep Lorem|grep -v grep|tail -n 1 to print what should be a SINGLE line of text (because of tail -n 1)

now selecting with mouse the printed text and pasting into an editor reveals:

echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum"

(ie HARD line breaks after: do eiusmod pariatur. Excepteur est laborum" )

5) stop log


NOTE: step 1 and 5 are mostly relevant for iterm2

**Comment by timotheecour** [comment]
also, I have this in my tmux.conf:

set-option -g default-command "reattach-to-user-namespace -l zsh"

**Comment by nicm** [comment]
You need to copy from tmux with copy mode, you can't depend on copying with the mouse outside tmux because tmux may do whatever it wants to draw the screen efficiently, it's the same as any other full screen program.

**Comment by timotheecour** [comment]
Copying with tmux' copy mode doesn't interact well with iterm2 (and is more complicated). Where should i look in tmux source code to allow using soft line breaks instead of hard line breaks for wrapped text?

Even if it prevents 'draw the screen efficiently' which I probably don't care about compared to this usability bug.
