### ISSUE TITLE
Set HISTFILE=$(tmux display-message -p  "#{window_name}") unreliable/inconsistent

### ISSUE THREAD

**Issue by bedge** [tmux/tmux#653]
I want to have a different, yet consistent, history file for each window I create.

Once the shell window is open and usable, I can use

```
HISTFILE=$(tmux display-message -p  "#{window_name}")
```
so the obvious thing seems to be to put this in my ~/.zshenv:
```
if [ "${TMUX}" ] ; then
        HISTFILE=$(tmux display-message -p  "#{window_name}")
fi
```
However, the value returned for this when I start a new tmux session (from tmuxinator), that creates a number of windows, seems to cycle between the `next` window in the session, and the one after that.

I added this to see what it cycled through as the shell was initializing and it does in fact change to the value of several different windows
```
if [ "${TMUX}" ] ; then
    set -x
    while true; do
        HISTFILE=$(tmux display-message -p  "#{window_name}")
        echo sleep
        sleep 1
    done
    set +x
fi
```
output (trimmed):
```
+/Users/bedge/.zshenv:16> HISTFILE=+/Users/bedge/.zshenv:16> tmux display-message -p '#{window_name}'
+/Users/bedge/.zshenv:16> HISTFILE=editor
+/Users/bedge/.zshenv:16> HISTFILE=+/Users/bedge/.zshenv:16> tmux display-message -p +/Users/bedge/.zshenv:16> HISTFILE=ml_sh
```

This is for the window named `ml_sh`, the `editor` window in next in sequence.

For the editor window, the sequence is reversed.

So, I'm not sure how one should reliable set HISTFILE

**Comment by nicm** [comment]
Try -t$TMUX_PANE

**Comment by bedge** [comment]
Thanks! that was it:
```
HISTFILE=~/.zsh/history/$(tmux display-message -p -t${TMUX_PANE} "#{window_name}")
```
works beautifully.
