### ISSUE TITLE
Support aliases with new-window, split-window etc?

### ISSUE THREAD

**Issue by sphaugh** [tmux/tmux#655]

**Comment by nicm** [comment]
.......

**Comment by sphaugh** [comment]
:) ?

**Comment by ThomasAdam** [comment]
We already have aliases for those commands.  If you want something additional, use the shell to provide it.

**Comment by sphaugh** [comment]
Okay, sorry I wasn't being clear. I'm asking if new-window, etc can check if their argument is an alias and translate properly before running it (or not running it).

**Comment by nicm** [comment]
What alias? A shell alias?

**Comment by sphaugh** [comment]
Yes... mostly just for convenience.

**Comment by nicm** [comment]
There is no sensible way for tmux to know what the shell aliases are.

**Comment by sphaugh** [comment]
Fair enough :)
