### ISSUE TITLE
renumber/reorder windows by dragging using mouse

### ISSUE THREAD

**Issue by dmd** [tmux/tmux#656]
It would be nice if, in mouse mode, one could drag window titles to reorder/renumber them (like tabs in a browser).

**Comment by dmd** [comment]
It would be nice to leave a comment like 'won't do this' or something instead of just closing with no explanation at all.

**Comment by KamarajuKusumanchi** [comment]
I am curious why this bug is closed? This will be a nice features to have!

**Comment by sudobash1** [comment]
For those who find this issue in a Google search, you need to add a `-d` flag to `swap-window` now (as of version 3.0 I believe). This prevents the window you are swapping from being selected. If you don't do this, you will get tons of stuttering behavior when dragging windows.

```
bind-key -n MouseDrag1Status swap-window -d -t=
```

(Thanks to @nicm for pointing this out)
