### ISSUE TITLE
new-session vs. new-window

### ISSUE THREAD

**Issue by nerd-of-paridise** [tmux/tmux#657]
Version:  git master branch

I'm trying to create multiple windows running an executable, with all windows in the same session.

The following works, but isn't perfect.
$ tmux new-session -d -s test 'shell-cmd'
$ tmux new-window -d -t test 'shell-cmd'
$ tmux new-window -d -t test 'shell-cmd'
(etc.)

However, if 'shell-cmd' from the first invocation of tmux exists before the second invocation, the remaining invocations fail.

I thought that the '-A' argument to  new-session would do what I want, but the -A doesn't run the 'shell-cmd', but acts as if attach-session had been called.

What I really need is a flag for new-window that will create a session if the one specified by the '-t target-window' does not exist.

Something like:
$ tmux new-window -Sd -s test 'shell-cmd'
$ tmux new-window -Sd -t test 'shell-cmd'
$ tmux new-window -Sd -t test 'shell-cmd'

Would this be difficult to implement?

**Comment by nicm** [comment]
You could use remain-on-exit.

**Comment by nerd-of-paridise** [comment]
Using 'remain-on-exit' will leave a window with a dead process in it.

My tmux use-case is simply to "background" long-running processes that have a console interface.
I find that if I start each processes using 'new-session', things work.
While it would be preferable to have them all in a single session, one process per session also works.
To switch between processes, I use 'choose-tree' rather than 'choose-window' to switch between sessions.

Providing **implicit** session creation in new-window would allow the windows to be grouped in the same session.

I don't have the bandwidth to look at it at this time, but I may submit a pull-request if I get an opportunity in the future.

**Comment by nicm** [comment]
I will put this on the TODO list, but I would prefer a solution that did not involve adding an additional flag to neww.
