### ISSUE TITLE
Binding key in three key combination (C-w-l) blocks using it in two key combination (C-l).

### ISSUE THREAD

**Issue by purpleP** [tmux/tmux#663]
tmux version is 2.3. I use it in macos and ubuntu 16.10.

You don't need a config, to reproduce it.
`:bind-key -n C-w-l select-pane -R` and then `:list-keys` and you would see `C-l` bounded to `select-pane -R`.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING (https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.

**Comment by purpleP** [comment]
@nicm After a couple of minutes looking at tmux code I can see where the problem is. Somehow tmux thinks that I would only use zero or more modifiers and exactly one normal key in the binding.

**Comment by nicm** [comment]
Actually this is not even a valid key, we should probably complain about it.

**Comment by nicm** [comment]
Changed to error on invalid modifiers, thanks.

**Comment by nicm** [comment]
If you want to bind C-w l or C-w C-l you need to bind the second key in an additional key table and bind the first to switchc -T.

**Comment by purpleP** [comment]
@nicm 
```
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -Troot C-w switch-client -Twindows
bind-key -Twindows h "$is_vim" "send-keys C-w-h" "select-pane -L"
bind-key -Twindows j "$is_vim" "send-keys C-w-j" "select-pane -D"
bind-key -Twindows k "$is_vim" "send-keys C-w-k" "select-pane -U"
bind-key -Twindows l "$is_vim" "send-keys C-w-l" "select-pane -R"
bind-key -Twindows p "$is_vim" "send-keys C-w-p" "select-pane -l"
bind-key -Twindows v "$is_vim" "send-keys C-w-v" "split-window -h"
bind-key -Twindows s "$is_vim" "send-keys C-w-s" "split-window -v"
```
This gives me 

` unknown command: ps -o state= -o comm= -t '#{pane_tty}'     | grep -iqE '^[^TXZ ]+ +(\S+\/)?g?(view|n?vim?x?)(diff)?$'
`
With or without space after `-T` flag
