### ISSUE TITLE
Unable to use Unicode in window names

### ISSUE THREAD

**Issue by alerque** [tmux/tmux#664]
I'm using Tmux 2.2 and am often working or projects that are not in English. I've noticed that I cannot name windows (using the `Prefix + ,` binding) with names that include letters outside an ASCII character set. Is there really a good reason for this restriction? Sometimes they end up with other characters there such as when vim passes on the name of a file it has open and that gets set as the window name. In that case it works fine, why wouldn't I be allowed to set a name like this manually from the tmux prompt?

**Comment by nicm** [comment]
Is this a problem in Git master?

**Comment by alerque** [comment]
I just updated first to 2.3 (no change to this issue) then to the latest git version. The current git head does in fact accept some Unicode characters. The only thing I see now is that it doesn't accept spaces any more (it used to). Is that intentional? Shouldn't the prompt do something other that ignore rename requests with spaces?

**Comment by nicm** [comment]
Works for me.

**Comment by nicm** [comment]
What exactly are you typing?

**Comment by alerque** [comment]
The title I was going for the other day was `aykırı ateş`. Either the first or the second works (no problem with the Unicode in the git HEAD version), but it won't accept both together and hitting enter at the prompt causes no change (or error) to the session.

**Comment by nicm** [comment]
And "tmux ls" from the shell shows the session with the old name?

**Comment by alerque** [comment]
Correct, it shows the old name without any change (it does not even reflect the first word of the new name).

**Comment by alerque** [comment]
It seems there is some kind of usage error being flashed after I hit enter, but it goes by so fast it's just a blink and I haven't been able to read it.

**Comment by nicm** [comment]
What if you do the rename from the shell instead?

**Comment by alerque** [comment]
I can rename it from the shell just fine: `tmux rename-session "aykırı ateş"`. Note that the quoting is eaten by the shell anyway so it gets passed to tmux as just a string. I also tried quoting it at both the rename prompt and as port of running `:rename-session "…"` from inside tmux. Neither of those work.

**Comment by nicm** [comment]
OK, please run tmux with -vvvv and send me the server log showing you
trying to rename from the tmux command prompt (not the shell).

**Comment by nicm** [comment]
This is working absolutely fine for me, from the command prompt it ends up running the same command as if I had typed it from the shell:

1480014137.877029 cmdq_next <0x173f9a154000>: command[rename-session] (0), flags 0
1480014137.877061 preparing state for rename-session "ayk\304\261r\304\261 ate\305\237" (client 0x173f9a154000)
...
