### ISSUE TITLE
Scrolling back doesn't account for unicode width

### ISSUE THREAD

**Issue by vincentbernat** [tmux/tmux#665]
Hey!

When using wide unicode characters (like 💻), tmux seems to have some difficulties when scrolling back. To reproduce, use this:

```sh
for i in $(seq 1 $LINES); do echo ; done
for i in $(seq 1 $LINES); do echo "💻  36dd9179-c2e3-4d76-bfe6-6cfe7f713dac"; done
```

Then scroll back one screen. Here is the output I get:

```raw
                                       c
                                       c
                                       c
                                       c
                                       c
                                       c
                                       c
                                       c
                                       c
                                       c
💻  36dd9179-c2e3-4d76-bfe6-6cfe7f713dac
💻  36dd9179-c2e3-4d76-bfe6-6cfe7f713dac
💻  36dd9179-c2e3-4d76-bfe6-6cfe7f713dac
```

However, tmux internal state is correct as if I try to copy paste, I don't get the spurious "c" chars. Therefore, I suppose the bug is in the part the optimize the part of the screen to be rerendered.

I am using tmux 2.3-4 (from Debian unstable).

**Comment by nicm** [comment]
Is this still a problem in Git master?

**Comment by vincentbernat** [comment]
Yes, I have the same problem with master.

**Comment by nicm** [comment]
Please show logs from running the example you give, scrolling up, then exiting tmux. With master please.

**Comment by vincentbernat** [comment]
Here are the logs.
[tmux-logs.zip](https://github.com/tmux/tmux/files/610767/tmux-logs.zip)

**Comment by nicm** [comment]
Your platform is telling tmux that this character (\360\237\222\273) is width 1, not width 2. Or perhaps your terminal or font thinks it is width 2 when it should be width 1.

You could try building tmux with utf8proc.

**Comment by vincentbernat** [comment]
With `--enable-utf8proc`, it works. Is that something that should be enabled for everybody? Or should I find why it thinks the width is 1 while it should be 2?

**Comment by nicm** [comment]
Probably your terminal is Unicode 9 but the system wcwidth() in libc is
an older Unicode version, eventually libc will catch up.

**Comment by vincentbernat** [comment]
It seems that my libc (glibc 2.24) is up-to-date:

```c
#define _XOPEN_SOURCE
#include <locale.h>
#include <stdio.h>
#include <wchar.h>

#define D(x) printf("%06X %d\n",(x),wcwidth(x))

int
main(void)
{
	setlocale(LC_ALL, "");

	D('a');
	D(0x1F4BB);
	return (0);
}
```

It gives me "2" for the wide char.

**Comment by nicm** [comment]
That is not what it is telling tmux, what do you have in LC_CTYPE and LC_ALL?

**Comment by vincentbernat** [comment]
Both are empty. I have LANG set to `fr_FR.utf8`.

**Comment by nicm** [comment]
Is it different if you change LANG to en_US.UTF-8?

**Comment by nicm** [comment]
What if you try this:

~~~~
#define _XOPEN_SOURCE
#include <locale.h>
#include <stdio.h>
#include <stdlib.h>
#include <wchar.h>

int
main(void)
{
    wchar_t w;
    char *s = "\360\237\222\273";

    setlocale(LC_ALL, "en_US.UTF-8");

    printf("%d\n", mbtowc(&w, s, (sizeof s) - 1));
    printf("%06x %d\n", (int)w, wcwidth(w));
    return (0);
}
~~~~

I get:

$ ./x
4
01f4bb 1

**Comment by vincentbernat** [comment]
I get:
```
4
01f4bb 2
```

But I am now confused. I have disabled utf8proc (with `--disable-utf8proc`) to test with alternative locales and it now works perfectly. I have:

```
1480003197.707302 input_utf8_close 4 '\360\237\222\273' (width 2)
```

I have removed `libutf8proc2` and `libutf8proc-dev` packages, done a `git clean -fxd`, recompiled everything and it still works fine. Nothing else has changed on my system, so I am a bit clueless on what may have happened. LANG and LC_* are unchanged.

Well, good news?

**Comment by nicm** [comment]
Are you sure you didn't have tmux built against an older libc?

**Comment by vincentbernat** [comment]
I have always checked that the running binary was the one I have just built (I run it with `./tmux -S ~/tmp/test.tmux`, so it's easy to spot in `ps` that you get those two processes on each try). I am using a dedicated socket. But, yeah, it's likely that I messed up something along the path.
