### ISSUE TITLE
something changed in tmux 2.3 with F61-F63 keys

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#667]
I have special key bindings and use tmux config to bind them. 

`set -g terminal-overrides "*:kf22=\\033[34~,*:kf34=\\033[44~,*:kf46=\\033[54~,*:kf58=\\033\\033[21~,*:kf61=\\033\\033[34~,*:kf62=\\033\\033[44~,*:kf63=\\033\\033[54~"`

The "f61" key is supposed to map to M-S-F1 as explained in the change notes for tmux 2.0.

`bind -n M-S-F1 previous-window`

This bind spits `<ESC>[21;4~` into the console rather than triggering `previous-window`.  It worked in tmux 2.1 and 2.2 I think, but not 2.3.

**Comment by nicm** [comment]
Logs? \033[23;4~ is M-S-F10 but there is no way to define it in terminfo.

**Comment by unphased** [comment]
Do you know what \033[21;4~ is?

Basically, I have my terminal emulators which put out the stream `\033\033[34~` and I want this sequence to become bindable in tmux. I can't quite tell what's happening because I don't know what combo the resultant code tmux sends is supposed to correspond to. 

What does seem to happen is the terminal-overrides seems to not like my binds which start with two escape characters.

**Comment by nicm** [comment]
I meant 21 not 23.

**Comment by unphased** [comment]
I have no idea what black magic is causing tmux to convert the sequence `\033\033[34~` to `\033[21;4` no matter whether I bind it to kf61 or not with terminal-overrides. But if I use `\033\033[33~` instead, the bind works (bindable with `M-S-F1`).

**Comment by nicm** [comment]
Please look at the CONTRIBUTING file and show some logs.

**Comment by nicm** [comment]
Just pressing one nonworking key then exiting will be enough.

**Comment by unphased** [comment]
thanks, I'll try that.

**Comment by unphased** [comment]
I've found some info in the log. I ran it and pressed the `\033\033[44~` key. In the config I used for tmux, I've bound M-S-F2 to last-window. The log appears to report that C-M-F10 got sent to the term. So I'm not sure why it's doing that. 

[tmux-server-61288.log.txt](https://github.com/tmux/tmux/files/609725/tmux-server-61288.log.txt)

I used the setup file `util/.tmux.test.conf`:

```
set -g terminal-overrides "*:kf22=\\033[34~,*:kf34=\\033[44~,*:kf46=\\033[54~,*:kf58=\\033\\033[21~,*:kf61=\\033[21;4~,*:kf62=\\033\\033[44~,*:kf63=\\033\\033[54~"
bind -n M-S-F1 previous-window
bind M-S-F1 previous-window
bind -n M-S-F2 last-window
bind M-S-F2 last-window
``` 

`tmux -vvvv -Ltest -futil/.tmux.test.conf new`

**Comment by unphased** [comment]
Here's another thing I see. 

In the same set of bindings there I have `kf22=\\033[34~`

If I remove this, my `\\033\\033[34~` bind starts working!

MaybeI can remove the kf61,62,63 binds and just use the `M-` handles in the tmux key binds...

**Comment by nicm** [comment]
You have a binding for \033[44~ to C-F10 which means that \033\033[44~
is C-M-F10, if you also bind that to a different key then tmux has no
way to distinguish the two. As it happens tmux looks up the key without
\033 first, so you will get C-M-F10 (\033[21;7~ if xterm-keys is on).

It is asking for trouble for a terminal to generate a key with two
\033 that does mean Meta + another key.

**Comment by nicm** [comment]
A leading \033 always means Meta (so for example M-a is \033a).
