### ISSUE TITLE
tmux input freezing/not responding (but cursor stop blinking showing recognition)

### ISSUE THREAD

**Issue by mordof-work** [tmux/tmux#668]
I'm on Linux Mint 18, using zsh (with the oh-my-zsh bundle), and tmux 2.3 (compiled after downloading from the website since mint repos are at 2.1). regular gnome terminal.

Every so often the input will start to lock up. I just had a scenario where i was typing, and then it started only putting some of the letters i was typing into my prompt. Then it froze for about 20 seconds, resuming after for normal input. Finished my command, hit enter, and what got submitted was a previous command with my command slapped on the end of it. Then it froze altogether and i gave up and killed the window.

Is there anything I can provide to help sort this out, or any workaround known that I can try?

**Comment by nicm** [comment]
Is this still a problem with Git master?

**Comment by mordof-work** [comment]
I'll grab that and see if the problem persists. I don't know how to recreate it at the moment, it just comes about sporadically, so unfortunately I doubt i'll be able to give feedback quickly on that.

**Comment by nicm** [comment]
OK please comment again if you can reproduce with master.

**Comment by mordof-work** [comment]
Same scenario happening on master unfortunately.
