### ISSUE TITLE
next and prev don't work in copy-mode 

### ISSUE THREAD

**Issue by octoploid** [tmux/tmux#669]
Once copy-mode is entered next and prev don't work anymore.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.

**Comment by octoploid** [comment]
I have the following in my ~/.tmux.conf:
```
bind-key -n C-right next                                                                                                                                                           bind-key -n C-left prev
```
These key don't work in copy-mode anymore. They work fine with version 2.3.

**Comment by krader1961** [comment]
Have you enabled xterm-keys? That is, is `set-window-option -g xterm-keys on` in your *~/.tmux.conf*? Presumably your terminal is still configured to generate xterm style key sequences as well but if not then that will also cause the symptom you're seeing. Having the [control] modifier usable on keys like [left-arrow] and [right-arrow] is a non-standard extension and isn't enabled by default in tmux.

**Comment by octoploid** [comment]
No, I don't have `xterm-keys on` in my ~/.tmux.conf.
As I wrote my setup works fine with version 2.3., so this issue is a regression.
My terminal is konsole.

**Comment by octoploid** [comment]
Unfortunately, I cannot git bisect the issue, because I land in an unbuildable tree after a few steps.

**Comment by nicm** [comment]
This is probably because panes in copy mode will use the copy-mode table not the root table, you can bind your keys in that table as well.

**Comment by octoploid** [comment]
Thanks @nicm.
The following works fine:
```
bind-key -n C-right next                                                                                                                                                           
bind-key -n C-left prev                                                                                                                                                            
bind-key -Tcopy-mode-vi C-right next                                                                                                                                               
bind-key -Tcopy-mode-vi C-left prev
```
