### ISSUE TITLE
fatal: xreallocarray: zero size

### ISSUE THREAD

**Issue by CaptSpify** [tmux/tmux#67]
Just upgraded to tmux 2. I use this to open a new window, and prompt for a title:

    bind-key -n "M-o" command-prompt -I "" "new-window -n '%%'"
tmux doesn't like having -I be empty, and gives me this error: 

    cmdq 0x7ff95aa25960: command-prompt -I  "new-window -n '%%'" (client 15)
    fatal: xreallocarray: zero size

If I put a space for input, it works:
    bind-key -n "M-o" command-prompt -I " " "new-window -n '%%'"

Not sure if there's a newer preferred way of opening a new window. My current fix works, and a real fix is definitely a low-priority for me, but wanted to document it as it could be causing issues for other people.

**Comment by nicm** [comment]
Pretty sure this is fixed in git.

**Comment by CaptSpify** [comment]
@nicm Oops, your are correct. I was using the package version. Thanks!
