### ISSUE TITLE
How to change the base index for various choice modes

### ISSUE THREAD

**Issue by thornycrackers** [tmux/tmux#670]
Hello :)

I recently came across the ability to change the base index as well as the base pane index. The only thing left is when you execute command such as choose-session or choose-window they are still zero indexed which would be nice if those could also be changed to index starting from 1. Is there some mechanism that already supports this or is it a feature request?

**Comment by ThomasAdam** [comment]
This isn't possible at the moment.

**Comment by thornycrackers** [comment]
Would you mind elaborating?
