### ISSUE TITLE
`-N` option for send-keys for non-copymode commands

### ISSUE THREAD

**Issue by choco** [tmux/tmux#671]
I'm not sure if it is supposed to work or it is restricted to copy mode commands, but it would be nice if it was possible to use the `-N` option of `send-key` for everything.
Basically I'd like to be able to do:
```
send -N 3 Up
```
but right now this returns `not in mode` message

**Comment by mlgh** [comment]
Don't we want to get rid of `modeprefix` and just issue the command `N` times in `cmd-send-keys.c`?
This will break `select-line`, (perhaps this is fixable somehow), other than that I don't immediately see any problems with such approach. This will make send-keys more uniform.

**Comment by nicm** [comment]
I don't mind if -N changes to work without -X, but I suggest just adding a loop rather than removing modeprefix.
