### ISSUE TITLE
Unable to scroll using a touch screen, despite of working good in simple ssh in my terminal 

### ISSUE THREAD

**Issue by Dvbnhbq** [tmux/tmux#673]
This makes me sad, cause I used to scroll logs with the swipe gesture in my git-bash terminal on Windows 10, using a nice tablet device. Now I'd like to start using tmux, but this is a problem, this is not very handy for me to use the mousewheel or keyboard :( Nor it works with the pen, neither on touch... 
Tried to config the MouseDrag bindings, but this doesn't seem to work.
Any way to solve this problem??

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.

**Comment by lool** [comment]
Does this also happen when you add:
set-window-option -g mode-mouse on
to your ~/.tmux.conf?
