### ISSUE TITLE
Tmux died with a general protection fault

### ISSUE THREAD

**Issue by hughsaunders** [tmux/tmux#676]
```
Nov 29 06:44:40 cb kernel: [12063621.191047] traps: tmux[30262] general protection ip:7fad937e11c0 sp:7ffcb6f55bd8 error:0 in libc-2.19.so (deleted)[7fad93749000+1bb000]
```

There doesn't seem to be a core dump so I can't provide any useful info :(

tmux version: 1.8 / 506adf376478c28a8ac50768cedc067fdd089483 (I think)
kernel: Linux cb 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linu
distro: Ubuntu 14.04/trusty

**Comment by ThomasAdam** [comment]
Well, what were you doing at the time? There's nothing here to go on. Try tmux from git. 1.8 is old.

**Comment by hughsaunders** [comment]
I was disconnected. I only found out when I tried to reconnect and tmux said "no sessions" so I went hunting in syslog for clues, and that was all I found. Probably had 20 tmux windows each with a couple of panes, irc, vims and shells. 

I realise there isn't enough to go but thought that GPF is an unusual way to die.
