### ISSUE TITLE
a way to turn on mousewheel scrolling without capturing clicks?

### ISSUE THREAD

**Issue by oconnor663** [tmux/tmux#68]
Being able to mousewheel scroll in the terminal without first hitting the tmux prefix (or needing to scroll the cursor from the bottom to the top of the screen before the screen starts to move) is wonderful, so I like to turn `mouse-mode` on. But I prefer to have my terminal's normal text highlighting behavior, rather than the tmux-specific text selection mode, or the trouble that any mouse-up event takes me out of scroll mode. Is there a way to get the mousewheel behavior without the left-click behavior?

**Comment by nicm** [comment]
Use tmux from git and configure the mouse keys the way you want.

**Comment by oconnor663** [comment]
Awesome, just found bf635e7741f7b881f67ec7e4a5caa02f7ff3d786. Thanks!

**Comment by oconnor663** [comment]
@nicm, having played with it for a little while, I have a few questions about the new settings:

1. I'm able to unbind the left click and drag events, so that they no longer take me out of copy mode, which is great:

    ```
bind -n MouseDown1Pane send-keys -M
bind -n MouseDrag1Pane send-keys -M
```
    But is there a way to Really Unbind them, so that gnome-terminal's click-and-drag text highlighting comes back? It seems like tmux is still consuming the event whenever `mouse` is turned on. (Programs like vim do receive these unbound events, so vim's cursor movement and visual selection do work with the mouse. It's only the terminal's text highlighting that's disabled.)

2. Is there a way to bind the mouse wheel now so that it works the way it did in old `mode-mouse`? That is, I'd like it to *both* turn on copy mode *and* scroll inside of copy mode. (And if possible, to exit copy mode when I scroll back to the bottom of the buffer.) Here's the best I've been able to do so far:

    ```
bind -n WheelUpPane copy-mode \; send-keys C-y
bind -n WheelDownPane copy-mode \; send-keys C-e
```
    That feels a little hacky, but it gets the first two bits working. It doesn't exit copy mode at the bottom though. I wasn't able to bind the `scroll-up` etc. commands directly, since tmux gave me `unknown command: scroll-up`. (Maybe those should be defined in regular mode, such that they automatically enter copy mode? And maybe then `scroll-down` could accept a flag that enables the exit-at-bottom behavior?)

3. I noticed that if I tried to make a separate mode-specific binding like `bind -t vi-copy WheelUpPane scroll-up`, it got around the unknown command error, but it seemed like it would get totally shadowed by the `-n` bindings above and ultimately have no effect. Is that intended? It doesn't seem currently possible to make a non-prefix binding in regular mode and also a binding in copy mode with the same key.

Apologies for the wall of text. I'm very excited to see mouse mode getting reworked!

**Comment by oconnor663** [comment]
Followup: I'm finding it works a little better for me right now to disable mouse mode and do

    set -ga terminal-overrides ',xterm*:smcup@:rmcup@'

as [recommended in the Arch Wiki](https://wiki.archlinux.org/index.php/Tmux#Scrolling_issues). That lets scrolling work fine most of the time -- since I usually have a single pane on screen -- and it preserves the normal terminal highlighting behavior.

**Comment by nicm** [comment]
On Thu, Jul 30, 2015 at 09:57:32AM -0700, oconnor663 wrote:
>    [1]@nicm, having played with it for a little while, I have a few questions
>    about the new settings:
> 
>     1. I'm able to unbind the left click and drag events, so that they no
>        longer take me out of copy mode, which is great:
> 
>  bind -n MouseDown1Pane send-keys -M
>  bind -n MouseDrag1Pane send-keys -M
> 
>        But is there a way to Really Unbind them, so that gnome-terminal's
>        click-and-drag text highlighting comes back? It seems like tmux is
>        still consuming the event whenever mouse is turned on. (Programs like
>        vim do receive these unbound events, so vim's cursor movement and
>        visual selection do work with the mouse. It's only the terminal's text
>        highlighting that's disabled.)
>

If you turn mouse on then tmux takes over the mouse. Most terminals let
you bypass this by holding down Shift.

>     2. Is there a way to bind the mouse wheel now so that it works the way it
>        did in old mode-mouse? That is, I'd like it to both turn on copy mode
>        and scroll inside of copy mode. (And if possible, to exit copy mode
>        when I scroll back to the bottom of the buffer.) Here's the best I've
>        been able to do so far:
> 
>  bind -n WheelUpPane copy-mode \; send-keys C-y
>  bind -n WheelDownPane copy-mode \; send-keys C-e
> 
>        That feels a little hacky, but it gets the first two bits working. It
>        doesn't exit copy mode at the bottom though. I wasn't able to bind the
>        scroll-up etc. commands directly, since tmux gave me unknown command:
>        scroll-up. (Maybe those should be defined in regular mode, such that
>        they automatically enter copy mode? And maybe then scroll-down could
>        accept a flag that enables the exit-at-bottom behavior?)
> 
>     3. I noticed that if I tried to make a separate mode-specific binding
>        like bind -t vi-copy WheelUpPane scroll-up, it got around the unknown
>        command error, but it seemed like it would get totally shadowed by the
>        -n bindings above and ultimately have no effect. Is that intended? It
>        doesn't seem currently possible to make a non-prefix binding in
>        regular mode and also a binding in copy mode with the same key.

Yes, you need to pass through the keys with send-keys -M. Look at the
default binding for MouseDrag1Pane.
