### ISSUE TITLE
set pane title

### ISSUE THREAD

**Issue by lonAlpha** [tmux/tmux#680]
I see pane-border-status is added in tmux 2.3.  Is there an easy way to set pane title? 

Now I write a script to set and update pane title. It is 

cat /usr/local/setpane
#!/usr/bin/env csh 
printf '\033]2;%s\033\\' $1
tmux set-option -g pane-border-format '#{pane_index} "#{pane_title}"'

**Comment by nicm** [comment]
There is no way to set the pane title from outside the pane itself, and I don't particularly think we should add that - the title belongs to the application, not to tmux.

**Comment by lonAlpha** [comment]
rename-pane should be as useful as rename-window.

By using pane I can compare the results side by side.

When I need to compare the output of one program with different input, I open a pane for each input. It may takes one day or two to get the output. When the result is ready, I have forgotten which input is given to which pane, and will  have to check the log. If I can set title of pane when launch the job, I do not need this check later.

**Comment by jtmkrueger** [comment]
I just have
```
set -g pane-border-format "#P: #{pane_current_command}"
```
in my `.tmux.conf` and it seems to keep up with whatever I is happening in the pane.

**Comment by lieut-data** [comment]
I regularly give my windows custom names to group my panes, and now *love* the new feature to render a custom pane title. I'd love to see a built-in `rename-pane` vs. just the escape codes.

**Comment by lonAlpha** [comment]
@jtmkrueger Thanks for your tips.  I often run same command with different parameters, then command name is not enough

**Comment by nicm** [comment]
Please try this [x.diff.txt](https://github.com/tmux/tmux/files/689910/x.diff.txt) to add selectp -T to set pane title. I was thinking of adding a separate pane label distinct from the title, but it actually seems redundant.

**Comment by nkgm** [comment]
@nicm is there a particular reason why you'd rather not include this in master?

**Comment by nicm** [comment]
Nobody tested it

**Comment by nkgm** [comment]
Just did a fresh build of master with the patch applied and it's working great so far. Any specific guidelines?

**Comment by nicm** [comment]
No that's grand, so long as it works for someone apart from me and
solves the problem... I'll take another look at it later

**Comment by nkgm** [comment]
With some sugar on top:
```tmux
# toggle pane title visibility
bind T run 'zsh -c "arr=( off top ) && tmux setw pane-border-status \${arr[\$(( \${arr[(I)#{pane-border-status}]} % 2 + 1 ))]}"'
# rename pane
bind t command-prompt -p "(rename-pane)" -I "#T" "select-pane -T '%%'"
```

**Comment by nicm** [comment]
applied now, thanks!

**Comment by hakunin** [comment]
Hey, I updated my tmux to 2.6 but it does not recognize `rename-pane` yet. Is this planned for future release or am I doing something incorrectly?

**Comment by bgwines** [comment]
@nkgm, these titles display perfectly (yay!) but get overwritten when I run any command in that pane, reverting to showing the default pane title. Is there a way to get it to stick? Thanks so much!

**Comment by nkgm** [comment]
@bgwines could you try running with minimal config see if the problem still happens?
@hakunin there's no actual command named `rename-pane`. It's just the `-T` switch added to the existing `select-pane` command.

**Comment by yorkbai** [comment]
@nkgm  great setting!  I've another problem after config it.   iterm2 + zsh + tmux in local host , when ssh to remote server in one pane , the pane title info rightly, after logout from remote host , the pane title can't chang to local and no more change even I  enter another path . 

![tmux](https://user-images.githubusercontent.com/7995150/39192520-f52902aa-479e-11e8-8042-1f471abb0594.png)

**Comment by nkgm** [comment]
@yorkbai I don't think pane titles are meant to be auto-refreshed in the same way window titles are.
/cc @nicm

**Comment by jettero** [comment]
@nkgm that's not what the docs say...

> tmux distinguishes between names and titles.  Windows and sessions have names, which may be used to specify them in targets and are displayed in the status line and various lists: the name is the tmux identifier for a window or session.  Only panes have titles.  A pane's title is typically set by the program running inside the pane using an escape sequence (like it would set the xterm(1) window title in X(7)).  Windows themselves do not have titles - a window's title is the title of its active pane.

It doesn't seem to me the `\033kTITLE HERE\033\\` strings update the #T like the docs seem to say they should... it updates #W and #T remains the hostname no matter what.

I think I'll post this as an issue...

**Comment by nkgm** [comment]
Good catch @jettero. My remark was based on `automatic-rename` and `automatic-rename-format` which affect the window title (ie no equivalent option for pane title).

As for the pane title, docs say:
```
When a pane is first created, its title is the hostname. A pane's title can be set via the OSC title setting sequence, for example:
$ printf '\033]2;My Title\033\\'
```
which could correlate with @yorkbai's observation.

**Comment by seanspotatobusiness** [comment]
Hey, am I doing it wrong? These comments suggest the solution is select-pain with -T switch but that doesn't work.

```
pi@raspberrypi:~ $ tmux select-pane -t 1 -T test    
tmux: unknown option -- T                           
usage: select-pane [-DdegLlMmRU] [-P style] [-t target-pane]
pi@raspberrypi:~ $ 
```

**Comment by seanspotatobusiness** [comment]
I have the latest version of tmux installed but `tmux select-pane -t 1 -T test` doesn't work as expected from the comments here.

```
pi@raspberrypi:~ $ tmux select-pane -t 1 -T test    
tmux: unknown option -- T                           
usage: select-pane [-DdegLlMmRU] [-P style] [-t target-pane]
pi@raspberrypi:~ $ tmux -V
tmux master
```

**Comment by jettero** [comment]
I forgot about having posted in this thread. The problem I was having with window/pane title/names and the escape codes is that there's a separate code for pane names. IMO, the docs aren't very clear about this, though technically all the details are in the docs if you know what to look for.

https://github.com/tmux/tmux/issues/1342#issuecomment-388274552

**Comment by ethagnawl** [comment]
> @nkgm, these titles display perfectly (yay!) but get overwritten when I run any command in that pane, reverting to showing the default pane title. Is there a way to get it to stick? Thanks so much!

Did you ever figure this out? I'm seeing the same behavior.

> @nkgm, these titles display perfectly (yay!) but get overwritten when I run any command in that pane, reverting to showing the default pane title. Is there a way to get it to stick? Thanks so much!

Were you ever able to figure out a reliable workaround? I understand that this value is subject to change by the shell or an application, but sometimes I'd really prefer it didn't.
