### ISSUE TITLE
Long, single-line file output issue

### ISSUE THREAD

**Issue by whereswaldon** [tmux/tmux#681]
## Platform

First observed on tmux 2.3 on macOS 10.12.1 using Terminal.app with bash 3.2.57(1)-release.
Reproduced on master.

## Problem

When your prompt is at the bottom of your screen and you `cat` a file that is long but has no newlines in it, you will only see a chunk of the end of the file displayed before your prompt returns. If you run another command or press the `Enter` key again, the rest of the file's content will pop into view in the previous `cat file`'s output as though it was there the whole time. This **only** occurs if the prompt is at the bottom of the screen.

Maybe this is a problem with `cat`? Sorry if I'm barking up the wrong tree.

Here's the contents of a file that I know works to reproduce, assuming that your terminal is only 80 chars wide:
```
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
```
I have also observed other ways of fixing the output include scrolling up and down again, taking a screenshot of the terminal window, and forcing a tmux redraw `Control-b r`.

## Config

No config needed to reproduce.

## TERM

Using Terminal.app
Outside tmux: `xterm-256color`
Inside tmux: `screen`

## Server Log

[tmux-server-87182.log.txt](https://github.com/tmux/tmux/files/627300/tmux-server-87182.log.txt)

## Screenshots

Within tmux after running `cat`:
<img width="818" alt="screen shot 2016-12-02 at 8 44 27 am" src="https://cloud.githubusercontent.com/assets/3922125/20836033/8f8eefae-b86b-11e6-86a7-bf713d15af72.png">
Within tmux after hitting `Enter` again:
<img width="818" alt="screen shot 2016-12-02 at 8 46 47 am" src="https://cloud.githubusercontent.com/assets/3922125/20836115/e0c6d3aa-b86b-11e6-9059-b54d1cca034a.png">
Expected behavior (outside of tmux):
<img width="818" alt="screen shot 2016-12-02 at 8 47 31 am" src="https://cloud.githubusercontent.com/assets/3922125/20836133/fa01805e-b86b-11e6-88ae-a7c97898f2a3.png">

# Notes

@reSoley is also having this issue, though his system is the same as the [Platform](#Platform) section above.

**Comment by whereswaldon** [comment]
After playing with it for a while, @reSoley and I noticed that it only happens when the current tmux pane is not part of a vertically split. Not sure why.

**Comment by nicm** [comment]
Does this still happen on master as of 5ea143f521726a47fd5092dcc3abf9101af32751?

**Comment by whereswaldon** [comment]
Yes, but it's a little different now. When you first run `cat`, you get:
<img width="762" alt="screen shot 2016-12-07 at 3 49 22 pm" src="https://cloud.githubusercontent.com/assets/3922125/20986004/d8ef01de-bc94-11e6-8331-b8cea32f1d14.png">
And after pressing Enter (or triggering some other redraw):
<img width="762" alt="screen shot 2016-12-07 at 3 50 38 pm" src="https://cloud.githubusercontent.com/assets/3922125/20986024/ebeda0f6-bc94-11e6-9c2e-451274ed9ac9.png">

**Comment by nicm** [comment]
I can't reproduce this.

Does it still happen if you do for example:

perl -e 'print "x"x200';cat

So it sits in cat rather than going back to the shell prompt?

Does it still happen if you set your prompt to a plain $?

**Comment by whereswaldon** [comment]
Using that command with a plain $ shell prompt:
<img width="762" alt="screen shot 2016-12-08 at 7 22 26 am" src="https://cloud.githubusercontent.com/assets/3922125/21009912/26cb2cb6-bd17-11e6-8824-4d20529236df.png">
After switching windows (which I guess makes something redraw):
<img width="762" alt="screen shot 2016-12-08 at 7 23 28 am" src="https://cloud.githubusercontent.com/assets/3922125/21009927/3c7986a2-bd17-11e6-922e-e1acf3bc8df2.png">
Please note that it **only** happens when the prompt is at the bottom of your screen already. Also, it doesn't happen if there's a vertical split present.
Is there any diagnostic info that I can get/make that would be helpful for replicating this?

**Comment by nicm** [comment]
If you use TERM=nsterm instead of xterm outside tmux, does that help?

**Comment by nicm** [comment]
Could you also see if you can reproduce in xterm (best) or iterm2 (if you can't do xterm)?

**Comment by nicm** [comment]
(or TERM=nsterm-256color is fine too)

**Comment by whereswaldon** [comment]
Yes, it does. Setting TERM=nsterm outside of tmux fixes it. Do you still want me to try xterm and iterm2?

**Comment by nicm** [comment]
No that is OK, I suggest you use nsterm (which is the correct TERM for
Terminal.app) instead of xterm, there must be something in the xterm
entry that Terminal.app doesn't like - and bugs in Terminal.app are not
unheard of.

**Comment by whereswaldon** [comment]
Ah. Sorry about that. I'm not sure why it's set to xterm now... I don't set that manually anywhere. I think it's defaulting to xterm-256color. Anyway, thank you. I actually had no idea that nsterm existed as a TERM setting.

**Comment by nicm** [comment]
Yes it probably defaults to xterm, lots of terminals do, but then don't fully support everything xterm does :-).

**Comment by whereswaldon** [comment]
I have a couple of followup questions:
- nsterm-256color doesn't seem to be in my terminal database. Does that definitely exist, or was that a guess?
- what's the proper way to override TERM in Terminal.app/bash? If I set it in .bashrc or .bash_profile, it clobbers whatever tmux sets when I launch tmux.

**Comment by nicm** [comment]
nsterm-256color exists for me but my terminfo database may be newer. It actually looks like you don't need it though:

$ TERM=nsterm tput colors
256

(You can also check from inside tmux by doing tmux showmsgs -T|grep color.)

If it doesn't have 256 colours on your system, you can either run tmux with -2, or use something like "set -ag terminal-overrides ",nsterm*:colors=256"" in tmux.conf).

If you can configure Terminal.app to set nsterm itself, that is the best option, then you don't need to set it in the profiles at all. Otherwise you can do something like:

[ -z "$TMUX" ] && export TERM=nsterm
