### ISSUE TITLE
Word or line mouse selection reverts to character selection when dragging

### ISSUE THREAD

**Issue by lqueryvg** [tmux/tmux#682]
**TMUX VERSION**: git master (>2.3, https://github.com/tmux/tmux/commit/6749a30a6e1a6467b8ce688cc5c1c245224ef013 = latest github version, as of 3rd December 2016)

**PLATFORM**:             CentOS Linux release 7.2.1511 (Core)

**MINIMAL TMUX CONFIG**: set -g mouse on

**TERM OUTSIDE TMUX**: xterm-256color
**TERM INSIDE TMUX**: screen-256color

Steps to reproduce problem:

1. Start tmux in terminal session
2. `echo "The Quick Brown Fox Jumps"`
3. Enter copy mode with `Prefix '['`
4. Double click mouse button 1 over the `o` in `Brown`.
Note: The word `Brown` should now be highlighted by tmux (good)
5. While still holding down mouse button 1, drag the selection to the right over `o` in `Fox`.
Note: Instead of `Brown Fox` being highlighted (good), you will see only `own Fo` highlighted (bad)

The same applies to line selection mode after triple-clicking when selecting lines.

E.g. if you have the text:

```
The Quick Brown Fox Jumps
Over The Lazy Dog
```

and you triple-click over the `o` in `Brown`, the whole first line is selected (good).
But if you drag the selection down to the `y` in `Lazy` you will see only
`own Fox Jumps`...`y Dog` selected, i.e. the right half of the first line and the left half of the second line  (bad).

**Comment by mlgh** [comment]
@nicm, since this feature seems to be needed to others, would it be ok if I change #672 to include `lineflag` and `wordflag` functionality (by analogy to `rectflag`) that would be triggered by `select-word` and `select-line`?

**Comment by nicm** [comment]
I haven't had time to look but I don't think we need wordflag, it sounds like the problem is just that the selection start should be moved to the B?

**Comment by nicm** [comment]
Something like this: [x.diff.txt](https://github.com/tmux/tmux/files/637340/x.diff.txt)

**Comment by mlgh** [comment]
@nicm, I can't see how this problem can be solved without introducing wordflag.
The behavior wanted here can be seen in any text editor/web browser: double click a word and now you select only on word boundaries. triple click - and you select on line boundaries.

**Comment by nicm** [comment]
OK, if you want to do it go for it.

**Comment by dannydulai** [comment]
it's be really cool if these flags also worked for mouse dragging selection

**Comment by nicm** [comment]
I've put this in the TODO file.
