### ISSUE TITLE
Pluralization mistake in `tmux ls` output

### ISSUE THREAD

**Issue by koorgoo** [tmux/tmux#683]
Hello, I started learning tmux and noticed a pluralization mistake.

```bash
$ tmux ls
basic: 1 windows (created Sun Dec  4 21:57:52 2016) [80x23]
```

Expected  to see `1 window` instead of `1 windows` in output.
The devil is in the details. Even so little ;)

Environment:
macOS 10.12.1
tmux 2.3

**Comment by nicm** [comment]
We don't bother with this or we would be doing it everywhere, the meaning
is clear.
