### ISSUE TITLE
Backoff mechanism in xterm

### ISSUE THREAD

**Issue by cunha** [tmux/tmux#684]
Hi, it seems `tmux`'s backoff mechanism is not interacting effectively with my `xterm`s. Has anyone had a similar problem?

Here are the tests I made:

* Open `xterm`, run `yes`, press `^C`: `yes` exists instantly.
* Open `rxvt`, run `yes`, press `^C`: `yes` exists instantly.
* Open `xterm`, run `tmux`, run `yes` inside `tmux`, press `^C`: scrolls for several seconds before stopping.
* Open `rxvt`, run `tmux`, run `yes` inside `tmux`, press `^C`: `yes` exists instantly.

Here is some information:

* [.tmux.conf][1]
* [.Xresources][2]

 [1]: https://github.com/cunha/dottmux/blob/master/.tmux.conf
 [2]: https://github.com/cunha/dotxfiles/blob/master/.Xresources

```
[xps:~]% cat /etc/issue
Debian GNU/Linux stretch/sid \n \l
[xps:~]% uxterm -v
XTerm(327)
[xps:~]% tmux -V
tmux 2.3
```

**Comment by nicm** [comment]
I suspect this is just that xterm is slower than rxvt so there is more opportunity for tmux to buffer and it takes longer to drain. Are you using the same terminal size and the same font with both?

**Comment by nicm** [comment]
Try using a bitmap font in xterm, TrueType fonts are slow. xterm is naturally a bit slower than rxvt, but those won't help at all.

**Comment by cunha** [comment]
The test results hold regardless of terminal size or font aliasing. It holds when rxvt has a significantly larger window and anti-aliasing on, or when xterm has a 80x25 window with a bitmap font.

**Comment by cunha** [comment]
I agree that the problem seems to be with `xterm` or how `tmux` interacts with it though. Maybe someone has had similar experience and has a solution. Will edit the opening post ot make this clearer.

**Comment by lucanLepus** [comment]
I have been experiencing this issue for a while and was wondering what caused it.
I now can confirm that something about xterm is causing the issue.
Can't offer a solution unfortunately, but i hope someone else can.
