### ISSUE TITLE
Bell indicator on linked window not displayed in all sessions

### ISSUE THREAD

**Issue by jlebon** [tmux/tmux#685]
Steps to reproduce:

Create this setup exactly (including currently active windows and currently attached session):

```
(0) - 0: 2 windows
(1)   ├─> 0: linked-
(2)   └─> 1: bash*
(3) - 1: 2 windows (attached)
(4)   ├─> 0: linked-
(5)   └─> 1: bash*
```

The two windows named "linked" are the same window, just linked.

- Go to (4) and run `sleep 5 && printf "\007"`.
- Go to (5) before the sleep expires.

Expected behaviour:

- I receive a bell indicator on window 0.

Actual behaviour:

- No bell indicator turned on, though looking in the choose-tree output, I do see that window 0 of the first session did have its bell indicator turned on. So it seems like the notification is sent only to the first session, not the others.

This seems like a regression. I'm on 2.2, though I can test master if needed. `bell-action` is set to the default (`any`).

**Comment by ThomasAdam** [comment]
This should be fixed on master. Try it.

**Comment by jlebon** [comment]
Yes, it does work now. However, there seems to be a delay of about 5s between hearing the bell (which is immediate), and the bell indicator going off on the window index.

**Comment by ThomasAdam** [comment]
Status update. Not a problem.
