### ISSUE TITLE
Swith-client does not work with repeat flag

### ISSUE THREAD

**Issue by yevhen-m** [tmux/tmux#687]
Why was this [issue]( https://github.com/tmux/tmux/issues/488) closed?

```
bind-key -r ( switch-client -p 
bind-key -r ) switch-client -n
```
These bindings do not work in tmux 2.2 and 2.3. Can somebody look into this?

**Comment by nicm** [comment]
Did you test the fix?

**Comment by yevhen-m** [comment]
@nicm should I apply this patch and compile tmux from source?

**Comment by nicm** [comment]
Yes (if it still applies) and see if it fixes the problem. Make sure you
stop tmux entirely before starting the new build.

**Comment by yevhen-m** [comment]
@nicm Ok, I've tried to remove that line and it does not fix anything ((.

**Comment by nicm** [comment]
Ok I will look tomorrow

**Comment by yevhen-m** [comment]
@nicm thanks.

**Comment by nicm** [comment]
This change fixes it for me, are you sure you restarted tmux entirely?
What key binding are you using?

**Comment by yevhen-m** [comment]
@nicm thanks, your change fixes the issue. Sorry that it took me so long to test it properly. Could you merge it?

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will appear in GitHub soon. Thanks!
