### ISSUE TITLE
After swapping windows both the source and target windows are constantly marked with "new activity"

### ISSUE THREAD

**Issue by er0** [tmux/tmux#690]
Create two windows, run 'swap-window -t +1'

Switch to window 1, then back to window 0
Now the two windows have new activity until they are swapped back to their original order.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.

**Comment by er0** [comment]
Version: built from git dda701d95fd539d7af8f76a8fe9d9cf71691b79a
Platform: Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
tmux.conf:
  setw -g monitor-activity on
  set -g visual-activity on
terminal: simple terminal (st) http://st.suckless.org/
TERM: screen

**Comment by er0** [comment]
[tmux-server-39065.log.txt](https://github.com/tmux/tmux/files/649628/tmux-server-39065.log.txt)

**Comment by nicm** [comment]
OK we need to update the list of winlinks that is now attached to each window when we swap them, please try this: [x.diff.txt](https://github.com/tmux/tmux/files/650202/x.diff.txt)

**Comment by er0** [comment]
After applying the patch, this is working perfectly.

**Comment by nicm** [comment]
Applied thanks!
