### ISSUE TITLE
hook for copy?

### ISSUE THREAD

**Issue by dannydulai** [tmux/tmux#691]
There is a ton of hacks related to keybindings for copy doing an action on copy, but ideally this could just be a hook whenever any copy worked.

Right now, it's impossible to capture that for mouse based selection (I think!)

I'm using tmux 2.3 on OSX.

**Comment by nicm** [comment]
A hook is not a bad idea, but in master you could change the key binding
for MouseDragEnd1Pane in copy-mode to add whatever extra commands you
want.

**Comment by dannydulai** [comment]
but copy-mode only seems to support a small subset of commands, no? for example:

`bind-key -t vi-copy MouseDragEnd1Pane display-panes` does not work -- it gives invalid command: display-panes

**Comment by nicm** [comment]
You need to use Git master.

**Comment by dannydulai** [comment]
Sweet, got what I needed to work, but it'd still be nice to do a hook.
