### ISSUE TITLE
is default-terminal a server or a session option?

### ISSUE THREAD

**Issue by logol** [tmux/tmux#692]
Hey, as stated in the [CHANGES FROM 2.0 to 2.1 18 October 2015](https://github.com/tmux/tmux/blob/master/CHANGES) 

> 'default-terminal' is now a session option

But if I add `set-option -g default-terminal tmux-256color` to tmux.conf and in tmux run
`:show-options -g`

default-terminal is not listed there, it's still shown in server options (`:show-options -s`)

Therefor I'm a little bit confused if this option should be set with -g or with -s flag.

**Comment by nicm** [comment]
I think it should read now a server option

**Comment by logol** [comment]
Okay,
I think this was changed again but not listed in the Changelog, because default-terminal is mentioned as a server option in the man pages.

**Comment by nicm** [comment]
I am pretty sure it is just an error In the changelog, it used to be a
session option
