### ISSUE TITLE
Wishlist: New command break-all-panes

### ISSUE THREAD

**Issue by Ganneff** [tmux/tmux#693]
Hi

assume you got a session with loads of panes in one window and now want to have each pane end up its own window. You can manually "break-pane" on each of them, of course, but a convenience command for this would be nice to have.

Thanks,
 Joerg

**Comment by ThomasAdam** [comment]
On Mon, Dec 19, 2016 at 06:16:10AM -0800, Joerg Jaspert wrote:
> Hi
> 
> assume you got a session with loads of panes in one window and now want to
> have each pane end up its own window. You can manually "break-pane" on each
> of them, of course, but a convenience command for this would be nice to
> have.

Should be able to do the following.  Not tested:

```
for i in $(tmux lsp -t2:0 -F '#{pane_id}'); do tmux breakp -s"$i"; done
```

-- Thomas

**Comment by Ganneff** [comment]
That does seem to work, yes, though an tmux internal command would be the nicer way IMO. But until then I will use something similar to the above, thanks for that.

**Comment by nicm** [comment]
I don't think this is a common enough need that builtin is better than a script.
