### ISSUE TITLE
Window Style Colours?

### ISSUE THREAD

**Issue by bhajneet** [tmux/tmux#698]
I see there are fg and bg values for window-style and window-active-style. Is this also possible for terminal colors 0-15? I'm using different background colors based on active pane and I would like to change the text color scheme of active/inactive panes accordingly.

**Comment by nicm** [comment]
No you can set default bg and fg but you cannot change the other colours.

**Comment by bhajneet** [comment]
Is it even possible? I would feature request it then. But otherwise, let's close this issue. Would have been fancy to have multiple colour schemes in panes or windows.

**Comment by nicm** [comment]
It is theoretically possible (tmux could just use colour X instead of colour Y) but we are not going to do it, it is complicated and I don't see a lot of uses.
