### ISSUE TITLE
Vim color scheme changes in tmux

### ISSUE THREAD

**Issue by gapplef** [tmux/tmux#699]
I'm using tmux 2.2 + Gnome Terminal + vim 7.4 on Ubuntu Gnome 16.10 x64
the screenshot of vim used in and outside tmux show below:
![screenshot from 2016-12-23 17-02-44](https://cloud.githubusercontent.com/assets/5604665/21453332/d764de04-c948-11e6-8df7-dad9408cfdc7.png)
![screenshot from 2016-12-23 17-03-29](https://cloud.githubusercontent.com/assets/5604665/21453331/d7642658-c948-11e6-8518-89565df64b7c.png)

tmux and vim are all used with the default config
$TERM outside tmux is 'xterm-256color', inside tmux is 'screen'.
I've tried the common said `set -g default-terminal "screen-256color"` in .tmux.conf , `tmux -2`, or `set t_Co=256` in .vimrc.
All these method take no effect in my case.

**Comment by nicm** [comment]
What if you do "export TERM=screen-256color" in the shell right before you run vim?

**Comment by gapplef** [comment]
Yes, that caused the problem!
After `export TERM=screen-256color`, color scheme of vim is same with that used inside tmux.
Then, how can I fix this problem?

**Comment by nicm** [comment]
Show me output of "tmux info" please.

**Comment by nicm** [comment]
From inside tmux.

**Comment by gapplef** [comment]
~$ `tmux info`
>  Terminal 0: xterm-256color [references=1, flags=0x1]:
   0: AX: (flag) true
   1: acsc: (string) ``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~
   2: bce: (flag) true
   3: bel: (string) \007
   4: blink: (string) \033[5m
   5: bold: (string) \033[1m
   6: civis: (string) \033[?25l
   7: clear: (string) \033[H\033[2J
   8: cnorm: (string) \033[?12l\033[?25h
   9: colors: (number) 256
  10: Cr: (string) \033]112\007
  11: Cs: (string) \033]12;%p1%s\007
  12: csr: (string) \033[%i%p1%d;%p2%dr
  13: cub: (string) \033[%p1%dD
  14: cub1: (string) \010
  15: cud: (string) \033[%p1%dB
  16: cud1: (string) \012
  17: cuf: (string) \033[%p1%dC
  18: cuf1: (string) \033[C
  19: cup: (string) \033[%i%p1%d;%p2%dH
  20: cuu: (string) \033[%p1%dA
  21: cuu1: (string) \033[A
  22: cvvis: (string) \033[?12;25h
  23: dch: (string) \033[%p1%dP
  24: dch1: (string) \033[P
  25: dim: (string) \033[2m
  26: dl: (string) \033[%p1%dM
  27: dl1: (string) \033[M
  28: E3: (string) \033[3J
  29: ech: (string) \033[%p1%dX
  30: el: (string) \033[K
  31: el1: (string) \033[1K
  32: enacs: [missing]
  33: fsl: (string) \007
  34: home: (string) \033[H
  35: hpa: (string) \033[%i%p1%dG
  36: ich: (string) \033[%p1%d@
  37: ich1: [missing]
  38: il: (string) \033[%p1%dL
  39: il1: (string) \033[L
  40: invis: (string) \033[8m
  41: is1: [missing]
  42: is2: (string) \033[!p\033[?3;4l\033[4l\033>
  43: is3: [missing]
  44: kcbt: (string) \033[Z
  45: kcub1: (string) \033OD
  46: kcud1: (string) \033OB
  47: kcuf1: (string) \033OC
  48: kcuu1: (string) \033OA
  49: kDC: (string) \033[3;2~
  50: kDC3: (string) \033[3;3~
  51: kDC4: (string) \033[3;4~
  52: kDC5: (string) \033[3;5~
  53: kDC6: (string) \033[3;6~
  54: kDC7: (string) \033[3;7~
  55: kdch1: (string) \033[3~
  56: kDN: (string) \033[1;2B
  57: kDN3: (string) \033[1;3B
  58: kDN4: (string) \033[1;4B
  59: kDN5: (string) \033[1;5B
  60: kDN6: (string) \033[1;6B
  61: kDN7: (string) \033[1;7B
  62: kend: (string) \033OF
  63: kEND: (string) \033[1;2F
  64: kEND3: (string) \033[1;3F
  65: kEND4: (string) \033[1;4F
  66: kEND5: (string) \033[1;5F
  67: kEND6: (string) \033[1;6F
  68: kEND7: (string) \033[1;7F
  69: kf1: (string) \033OP
  70: kf10: (string) \033[21~
  71: kf11: (string) \033[23~
  72: kf12: (string) \033[24~
  73: kf13: (string) \033[1;2P
  74: kf14: (string) \033[1;2Q
  75: kf15: (string) \033[1;2R
  76: kf16: (string) \033[1;2S
  77: kf17: (string) \033[15;2~
  78: kf18: (string) \033[17;2~
  79: kf19: (string) \033[18;2~
  80: kf2: (string) \033OQ
  81: kf20: (string) \033[19;2~
  82: kf21: (string) \033[20;2~
  83: kf22: (string) \033[21;2~
  84: kf23: (string) \033[23;2~
  85: kf24: (string) \033[24;2~
  86: kf25: (string) \033[1;5P
  87: kf26: (string) \033[1;5Q
  88: kf27: (string) \033[1;5R
  89: kf28: (string) \033[1;5S
  90: kf29: (string) \033[15;5~
  91: kf3: (string) \033OR
  92: kf30: (string) \033[17;5~
  93: kf31: (string) \033[18;5~
  94: kf32: (string) \033[19;5~
  95: kf33: (string) \033[20;5~
  96: kf34: (string) \033[21;5~
  97: kf35: (string) \033[23;5~
  98: kf36: (string) \033[24;5~
  99: kf37: (string) \033[1;6P
 100: kf38: (string) \033[1;6Q
 101: kf39: (string) \033[1;6R
 102: kf4: (string) \033OS
 103: kf40: (string) \033[1;6S
 104: kf41: (string) \033[15;6~
 105: kf42: (string) \033[17;6~
 106: kf43: (string) \033[18;6~
 107: kf44: (string) \033[19;6~
 108: kf45: (string) \033[20;6~
 109: kf46: (string) \033[21;6~
 110: kf47: (string) \033[23;6~
 111: kf48: (string) \033[24;6~
 112: kf49: (string) \033[1;3P
 113: kf5: (string) \033[15~
 114: kf50: (string) \033[1;3Q
 115: kf51: (string) \033[1;3R
 116: kf52: (string) \033[1;3S
 117: kf53: (string) \033[15;3~
 118: kf54: (string) \033[17;3~
 119: kf55: (string) \033[18;3~
 120: kf56: (string) \033[19;3~
 121: kf57: (string) \033[20;3~
 122: kf58: (string) \033[21;3~
 123: kf59: (string) \033[23;3~
 124: kf6: (string) \033[17~
 125: kf60: (string) \033[24;3~
 126: kf61: (string) \033[1;4P
 127: kf62: (string) \033[1;4Q
 128: kf63: (string) \033[1;4R
 129: kf7: (string) \033[18~
 130: kf8: (string) \033[19~
 131: kf9: (string) \033[20~
 132: kHOM: (string) \033[1;2H
 133: kHOM3: (string) \033[1;3H
 134: kHOM4: (string) \033[1;4H
 135: kHOM5: (string) \033[1;5H
 136: kHOM6: (string) \033[1;6H
 137: kHOM7: (string) \033[1;7H
 138: khome: (string) \033OH
 139: kIC: (string) \033[2;2~
 140: kIC3: (string) \033[2;3~
 141: kIC4: (string) \033[2;4~
 142: kIC5: (string) \033[2;5~
 143: kIC6: (string) \033[2;6~
 144: kIC7: (string) \033[2;7~
 145: kich1: (string) \033[2~
 146: kLFT: (string) \033[1;2D
 147: kLFT3: (string) \033[1;3D
 148: kLFT4: (string) \033[1;4D
 149: kLFT5: (string) \033[1;5D
 150: kLFT6: (string) \033[1;6D
 151: kLFT7: (string) \033[1;7D
 152: kmous: (string) \033[M
 153: knp: (string) \033[6~
 154: kNXT: (string) \033[6;2~
 155: kNXT3: (string) \033[6;3~
 156: kNXT4: (string) \033[6;4~
 157: kNXT5: (string) \033[6;5~
 158: kNXT6: (string) \033[6;6~
 159: kNXT7: (string) \033[6;7~
 160: kpp: (string) \033[5~
 161: kPRV: (string) \033[5;2~
 162: kPRV3: (string) \033[5;3~
 163: kPRV4: (string) \033[5;4~
 164: kPRV5: (string) \033[5;5~
 165: kPRV6: (string) \033[5;6~
 166: kPRV7: (string) \033[5;7~
 167: kRIT: (string) \033[1;2C
 168: kRIT3: (string) \033[1;3C
 169: kRIT4: (string) \033[1;4C
 170: kRIT5: (string) \033[1;5C
 171: kRIT6: (string) \033[1;6C
 172: kRIT7: (string) \033[1;7C
 173: kUP: (string) \033[1;2A
 174: kUP3: (string) \033[1;3A
 175: kUP4: (string) \033[1;4A
 176: kUP5: (string) \033[1;5A
 177: kUP6: (string) \033[1;6A
 178: kUP7: (string) \033[1;7A
 179: Ms: (string) \033]52;%p1%s;%p2%s\007
 180: op: (string) \033[39;49m
 181: rev: (string) \033[7m
 182: ri: (string) \033M
 183: rmacs: (string) \033(B
 184: rmcup: (string) \033[?1049l
 185: rmkx: (string) \033[?1l\033>
 186: Se: (string) \033[2 q
 187: setab: (string) \033[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m
 188: setaf: (string) \033[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m
 189: sgr0: (string) \033(B\033[m
 190: sitm: (string) \033[3m
 191: smacs: (string) \033(0
 192: smcup: (string) \033[?1049h
 193: smkx: (string) \033[?1h\033=
 194: smso: (string) \033[7m
 195: smul: (string) \033[4m
 196: Ss: (string) \033[%p1%d q
 197: Tc: [missing]
 198: tsl: (string) \033]0;
 199: vpa: (string) \033[%i%p1%dd
 200: xenl: (flag) true
 201: XT: (flag) true

**Comment by nicm** [comment]
This seems like a problem with vim, you are correctly telling tmux that
it is a 256 colour terminal outside (by setting xterm-256color outside)
and vim that it is a 256 colour terminal inside (by setting
screen-256color inside).

My guess is that vim is doing something when TERM is xterm* that it
doesn't when TERM is screen*.

**Comment by gapplef** [comment]
I saw an option `set background=dark` in the default config of vim(/etc/vim/vimrc).
The option is disabled by default. I tried put this in my .vimrc, and it seems this fixed the problem(on some degree).
This time, the color scheme of vim is correct inside the tmux, but the font become bold (don't know why).
![screenshot from 2016-12-28 19-13-25](https://cloud.githubusercontent.com/assets/5604665/21520741/cdb56602-cd31-11e6-8888-9a165b03c682.png)

It seems that vim know my background is dark when used outside tmux, but it didn't get the information when used inside tmux.
So, It's because tmux didn't give the correct information or just vim's problem?

**Comment by nicm** [comment]
Possibly vim expects tmux to be BCE when it isn't, try building tmux from Git master.

**Comment by gapplef** [comment]
I build the tmux from Github (Version 2.4), the problem still didn't solve.

Put the following config in .vimrc seems fixed the problem in my case.
`set background=dark`
`set t_Co=256`
Both the color scheme and font are normal(still don't know why).

**Comment by pingsoli** [comment]
@gapplef I have tried it, but some colors still changed, and in vim visual mode no highlight. So I sought an  answer from [here](https://stackoverflow.com/questions/21553289/vim-tmux-visual-mode-not-highlighting). but it did not work. does there have some conflicts with tmux, airline plugin and vim. Have you solved it at last ? I'll apperciate your reply.

**Comment by pingsoli** [comment]
@gapplef I set tmux `set -g default-terminal "screen-256color"` and .vimrc 
```
set background=dark
set t_Co=256
```
at last, forcing tmux use 256 color, so there is no conflicts.
`tmux -2`

I'm really sorry to bother  you.

**Comment by mongoose64** [comment]
@pingsoli  you may need this:
https://vi.stackexchange.com/questions/10708/no-syntax-highlighting-in-tmux

short-answer: **do not** `set termguicolors` in vim

**Comment by jurelik** [comment]
Please note that changes to .tmux.conf won't be applied until you kill all tmux sessions. This is what finally made `set -g default-terminal "screen-256color"` work for me. To kill all tmux sessions type `killall tmux` into your terminal. You can also check if any sessions are active by typing in `tmux list-sessions`.

Hope this helps.

**Comment by betoharres** [comment]
I've tried everything... I think I'm just going give up on this and get used to this

**Comment by roycyt** [comment]
@betoharres 
Please try if this works for you ;)
```
set -g default-terminal "screen.xterm-256color
```

**Comment by aasutossh** [comment]
@roycyt I am getting `/home/aa/.tmux.conf:245: invalid or unknown command: set -g default-terminal "screen.xterm-256color` when initializing tmux.

**Comment by jurelik** [comment]
@aasutossh There's a quote missing from roycyt's answer. This should get rid of that error:
`set -g default-terminal "screen.xterm-256color"`

**Comment by aasutossh** [comment]
That's it. The error is fixed.
My bad.
Thanks @jurelik
