### ISSUE TITLE
the reload of conf don't support to comment config code when I don't exit all session.

### ISSUE THREAD

**Issue by rupertqin** [tmux/tmux#700]
## Enviranment

**tmux: stable 2.3 (bottled), HEAD**
**MacOS X**

## Problem: the strategy to  reload a conf is not good

for example, I had this in conf: 
```conf
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix
```

then I commented the three lines and `tmux source-file ~/.tmux.conf`, the prefix-bind-key didn't change.
Unless I set:  
```conf
unbind-key C-a
set-option -g prefix C-b
bind-key C-b send-prefix
```
and `tmux source-file ~/.tmux.conf`,  then the prefix-bind-key was set to C-b again. Or I exited all tmux session, then start a new tmux session, the config work right as expect.

It's not convenient, the reload of conf should support to comment config code.

**Comment by nicm** [comment]
The config file is just a set of commands, if you want to undo stuff you need to explicitly do so.
