### ISSUE TITLE
Heavy RAM usage when running on OSX

### ISSUE THREAD

**Issue by nka1024** [tmux/tmux#702]
I've been running 6 terminal tabs with separate tmux sessions in dual-pane mode. Using vim, mc and tig (ncurses-based git client) intensively. After couple of days tmux mem usage went up to 6,67 Gb and i couldn't find a way to clean it up except SIGKILL. It wouldn't bother me if it wasn't affecting scrolling speed but it was too slow for comfort. 

tmux 2.3, using config file from here https://github.com/tony/tmux-config

**Comment by nicm** [comment]
Can you reproduce with tmux from Git master?

**Comment by nka1024** [comment]
I had issues with compiling it, gonna try again and let you know.
