### ISSUE TITLE
Some odd formatting for the status bar when using iTerm2.  Attached screenshot

### ISSUE THREAD

**Issue by SpencerCDixon** [tmux/tmux#703]
<img width="813" alt="screen shot 2016-12-29 at 9 26 07 am" src="https://cloud.githubusercontent.com/assets/7471018/21545872/ed17d332-cda8-11e6-935d-c1e7f9b00e8c.png">

Has anyone seen something like this before/have thoughts on how to fix?

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING (https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.
