### ISSUE TITLE
While scrolled, cannot enter session selector

### ISSUE THREAD

**Issue by andrewbenton** [tmux/tmux#71]
Perhaps this was done on purpose.  What I am seeing is that as soon as I enter the scroll mode, whether by mouse or by keyborad, I can no longer switch to the session selector (<prefix>+s) unless I exit the scroll mode.  This usually means that I have to switch to a different window within the same session before I can switch sessions.  I can produce this instance as follows:

1. Enter scroll mode (mouse or keyboard)
2. Enter <prefix>+s and nothing happens
3. Exit scroll mode
4. Enter <prefix>+s and interactive session switcher shows up

**Comment by nicm** [comment]
Yes a pane can only be in one mode at a time. Exit copy mode before trying to enter choose mode;

**Comment by andrewbenton** [comment]
Is there a way that tmux can be extended so that multiple modes can be stacked? Having to open a separate window to enter choose mode si inconvenient.
