### ISSUE TITLE
Allow variable expansion in: new-window -n "#{expand_this}"

### ISSUE THREAD

**Issue by ramn** [tmux/tmux#711]
I'd like to be able to set the name of the newly created window - and use tmux variables in the string. However, tmux doesn't expand variables in the name arg (-n) where as it does in the path arg (-c). It seems reasonable that tmux should expand variables in -n as well.

$ tmux -V
tmux 2.3
running on macOS

**Comment by nicm** [comment]
Try this please: 
[xx.diff.txt](https://github.com/tmux/tmux/files/689958/xx.diff.txt)
