### ISSUE TITLE
when no sessions, "tmux -CC at" prints some errors.

### ISSUE THREAD

**Issue by springmoonlight** [tmux/tmux#713]
master branch, latest version.

When no sessions, "tmux -CC at" prints some errors as follows.

<img width="482" alt="0311ea5d05957a2584e17a87ed22ac8d" src="https://cloud.githubusercontent.com/assets/1595077/21833435/12c0d13a-d7ed-11e6-8767-eb8305751ee6.png">

**Comment by nicm** [comment]
This is a problem with iterm which is sending commands to the terminal even after tmux has exited.

**Comment by springmoonlight** [comment]
I get it. Thanks a lot!
