### ISSUE TITLE
Mac "say" not working in tmux session

### ISSUE THREAD

**Issue by geoherna** [tmux/tmux#716]
Not entirely sure if this is an issue with tmux or this requires special config, but when I run `say -v "Alex" "Hello, World!"` from Terminal or iTerm outside of Tmux, it works just fine. But when I try and run it from within a Tmux session, it simply hangs and does nothing.

Anyone else ever encounter this? Looks around and couldn't find any previous issues, etc.

Thanks.

**Comment by krader1961** [comment]
Works for me. Make sure you the `reattach-to-user-namespace` program installed and add lines like the following to your *~/.tmux.conf* (obviously changing the shell to whatever you prefer):

```
# The reattach-to-user-namespace is necessary to be able to contact ssh-agent
# via the SSH_AUTH_SOCK env var. This is also necessary to make pasteboard
# (clipboard) interaction work for programs run within the tmux server.
set-option -g default-command "exec reattach-to-user-namespace -l /usr/local/bin/fish"
```

**Comment by nicm** [comment]
This is an Apple problem not a tmux problem. I am closing this but continue to reply here if you wish.

**Comment by ylluminarious** [comment]
+1 for @krader1961's solution
