### ISSUE TITLE
[feature] link-pane (link-window for panes.)

### ISSUE THREAD

**Issue by genki** [tmux/tmux#719]
There is `like-window` but no `link-pane` yet.

Suppose there're 3 panes A, B, C and window 0, 1.
While the window 0 shows pane A and B, I want the window 1 to show pane A and C.
I often face to such situation, so it is very useful if it would be able to share the pane among several windows by `link-pane`.

**Comment by nicm** [comment]
Yes... I know... this has been in the TODO file since forever.
