### ISSUE TITLE
After autogen.sh ./configure && make fail to compile.

### ISSUE THREAD

**Issue by peterrobie** [tmux/tmux#72]
After autogen.sh ./configure && make fail to compile.

Ubuntu 15.04
GCC v.4.9.2
Automake 1.14.1
Autoconf   2.64

checking for flock... yes
checking for setproctitle... no
checking for sysconf... yes
checking for cfmakeraw... yes
checking for library containing clock_gettime... none required
./configure: line 4662: syntax error near unexpected token `newline'
./configure: line 4662: `PKG_CHECK_MODULES('

**Comment by ThomasAdam** [comment]
Does:

    autoreconf -i --force && ./configure

help?

**Comment by peterrobie** [comment]
It does not. That results in the following error...

autoreconf -i --force && ./configure

configure.ac:100: error: possibly undefined macro: AC_SEARCH_LIBS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by nicm** [comment]
You need pkgconfig installed as well if you are going to regenerate configure
