### ISSUE TITLE
tmux manual: refresh-client misses option -C

### ISSUE THREAD

**Issue by braph** [tmux/tmux#720]
Hi,

I've been searching a long while for the right way how to use the tmux control mode without resizing the attached session to 80x24 and finally found the solution in iTerm2's source code: `refresh-client -C $width,$height`.

Unfortunately the `-C` option is neither documented in the tmux manual, nor will it be suggested as an option in the shell autocompletion.

Regards, Benjamin

**Comment by nicm** [comment]
Yes I think this should be documented under refresh-client and also mentioned in the CONTROL MODE section.

**Comment by nicm** [comment]
Changed.
