### ISSUE TITLE
tmux kill-pane -a is not consequent

### ISSUE THREAD

**Issue by 0phoff** [tmux/tmux#722]
**Tmux version:** 2.3
**Minimal Config:** none

**Platform:** Linux Arch
**Terminal:** gnome-terminal

**$TERM outside tmux:** xterm-256color
**$TERM inside tmux:** screen without config, screen-256 with usual config

**Problem:**
the _kill-pane -a_ command is not behaving consequent imo!
When there are multiple panes in the window and you run _tmux killp -a_ it destroys all the panes except for the one that ran the command. This is as I expect.
However, when you run the command and there is only one pane in the window, it will destroy that pane (& window), which is not what I expect. When there is only one pane, it should not destroy anything imo...

I am creating a little script that can create a few different layouts I often use... Before creating the new layout I want to kill all the panes except the one that ran the command, so that I am sure there is only one pane.
I 'fixed' this issue by calling _tmux splitw -d_ before _tmux killp -a_, but it feels hacky imo...

**Comment by nicm** [comment]
Yes, this is an error. It should be fixed now, and will be in GitHub soon. Thanks for the report.
