### ISSUE TITLE
true colors stopped working after updating package on ubuntu 16.04

### ISSUE THREAD

**Issue by ErickChacon** [tmux/tmux#723]
- Platform: Ubuntu Xenial 16.04
- After installing tmux from github repository, true colors does not work. Next image, true colors outside tmux (upper) and inside tmux (lower). 
![true-colors](https://cloud.githubusercontent.com/assets/7862458/21964334/d4da30c0-db41-11e6-8f47-2d6b13ebc650.png)
- This is a small tmux configuration `.tmux.config` that reproduces my problem:
```
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
```
- I am working on the default gnome-terminal 3.18.3 of ubuntu.
term outside tmux: `xterm-256color`
term inside tmux: `screen-256color`

- Logs from tmux 
`tmux -Ltest kill-server`: "no server running on /tmp/tmux-1000/test"

```
tmux -vvvv -Ltest -f/dev/null new
tmux -Ltest kill-server

```
 this is the result file: 
[tmux-server-14065 .txt](https://github.com/tmux/tmux/files/706727/tmux-server-14065.txt)

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.

**Comment by nicm** [comment]
... what tmux versions?

**Comment by ErickChacon** [comment]
tmux 2.4

**Comment by nicm** [comment]
Are you sure you have commit a3cf99501782fc036d415369eb5a5d805eb9bdcc?

**Comment by ErickChacon** [comment]
Thank @nicm , I have updated the installation and it is working now. That commit made the difference.
