### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by jealie** [tmux/tmux#726]
Hey guys,

I just found a compilation error when installing tmux using the script at: https://github.com/jealie/install_tmux, apparently it is a mistake during the rework of set-option/show-options. It is solved with the pull request #725

**Comment by nbari** [comment]
Probably related, just updated mac os to 10.12.2 and once I open tmux it crashes full terminal.

While trying to update by using the HEAD version via brew:

    brew install --HEAD tmux

I get this error:

```
cmd-show-options.c:108:53: error: use of undeclared identifier 'VIS_DQ'
                stravis(&escaped, value, VIS_OCTAL|VIS_TAB|VIS_NL|VIS_DQ);
                                                                  ^
    
```
