### ISSUE TITLE
Cursor contrast

### ISSUE THREAD

**Issue by rumpelsepp** [tmux/tmux#73]
Hi,
I have an annoying problem with my cursor. Outside tmux it looks like this:
![screenshot from 2015-08-06 11-14-42](https://cloud.githubusercontent.com/assets/1961699/9108158/78b643a2-3c2c-11e5-92df-af72b0d011de.png)

Inside tmux it looks like this:

![screenshot from 2015-08-06 11-15-31](https://cloud.githubusercontent.com/assets/1961699/9108163/80a473ea-3c2c-11e5-9a68-bac2e31936b7.png)

That's super annoying... Any ideas?

**Comment by nicm** [comment]
... What terminal? What platform? What tmux version?

**Comment by rumpelsepp** [comment]
sure:
```
$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

$ pacman -Q tmux
tmux 2.0-1
```

Happens in guake and termite.

**Comment by nicm** [comment]
Does cursor change like this if you do "tput cnorm" outside tmux?

**Comment by rumpelsepp** [comment]
Sry, I complete forgot about this, since I have changed my cursor to "underline". That command did not change anything, but I think I have spotted the problem somewhere in my colorscheme scripts. I'll dig further and I'll ping you if I still think it's a tmux problem.
