### ISSUE TITLE
truecolor in status line

### ISSUE THREAD

**Issue by odedlaz** [tmux/tmux#731]
Hello!
I noticed that setting true color hex values for the status line doesn't work.
for instance, [atom](https://github.com/atom/atom)'s black background: [#282c34](http://www.colorhexa.com/282c34) shows up as: [#303030](http://www.colorhexa.com/303030).

I have true colors enabled and working in multiplexed terminals, just not the status line.

P.S: I used [gpick](https://github.com/thezbyg/Gpick) to extract the colors.

![pic](https://cloud.githubusercontent.com/assets/2660175/22155151/216fc6f4-df37-11e6-965c-53b4f9bcac99.png)

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.

**Comment by odedlaz** [comment]
It looks like this has already been addressed: https://github.com/tmux/tmux/issues/490
