### ISSUE TITLE
pane_current_command: show command with parameters

### ISSUE THREAD

**Issue by id777** [tmux/tmux#733]
I use this settings:
```
set -g pane-border-status bottom
set -g pane-border-format "#P: #{pane_current_command}"
```
Question: It is possible **to show** in pane-border-status not only command name, but **full command with parameters** (if they were given)?

I often run same command with different parameters, so then command name is not enough.
Example: I use [scrapy framework](https://doc.scrapy.org/en/0.10.3/topics/commands.html#crawl), and very often run several crawlers in the same time (command: $ scrapy crawl example.com).
It would be very convenient to see in pane-border-status not only command (scrapy), but full command with arguments (scrapy crawl example.com, scrapy crawl example_2.com, scrapy crawl example_3.com, etc.)

**Comment by nicm** [comment]
It is not possible and would not be trivial to implement. However, depending on your platform you could probably script this by using pane_pid or pane_tty with ps or /proc.

**Comment by id777** [comment]
Hello @nicm !

I found a solution: `ps -f --no-headers --ppid $(tmux display-message -p '#{pane_pid}') | awk '{ print substr($0, index($0,$8)) }'`

It's works well in the bottom bar:
`set -g status-left "#(ps -f --no-headers --ppid $(tmux display-message -p #{pane_pid}) | awk '{ print substr($0, index($0,$8)) }') | "`
When i switch to the next pane, then command changed as expected.
Here is screenshot: https://hsto.org/files/e2b/f78/b5b/e2bf78b5be67447a9563d0b91f923b34.png

But i can't set the same thing in the pane border. 
`set -g pane-border-format " #(ps -f --no-headers --ppid $(tmux display-message -p #{pane_pid}) | awk '{ print substr($0, index($0,$8)) }') "`
Here is screenshot: https://hsto.org/files/a83/bd0/b0b/a83bd0b0bd9b47d693ebc38688368103.png
Process in first pane showings in other panes too. 

I would be very grateful if you tell me how to solve this problem.

**Comment by nicm** [comment]
Something like this should work:

set -g pane-border-format '#(ps -f --no-headers --pid #{pane_pid} -o args)'

But if you are using master you will probably need the format force change I made for someone else, otherwise it will not update often enough, let me see if I can find it.

**Comment by nicm** [comment]
Er I meant ppid not pid.

**Comment by nicm** [comment]
Actually I think you may be right, there is a bug here.

**Comment by nicm** [comment]
OK the problem is that they are both running the same command, so tmux assumes they have the same result and it can use the cached result for both.

**Comment by nicm** [comment]
OK please try this diff: [tmux-format-tag.diff.txt](https://github.com/tmux/tmux/files/729467/tmux-format-tag.diff.txt)

This adds a tag for the format, so jobs (that is, #()) for different windows or panes are considered to be different (tmux won't use the result for job foo for pane 0 for same job foo for pane 1).

I am using this:

set -g pane-border-format '#(ps --no-headers -t #{pane_tty} -o args -O-c)'

**Comment by id777** [comment]
Hello @nicm 
I'm sorry for delay. 
I applied your diff and set command (set -g pane-border-format '#(ps --no-headers -t #{pane_tty} -o args -O-c)'), and it's works very well! Just perfectly. 
Here is a screenshot: https://hsto.org/files/7dc/660/a3d/7dc660a3dd0d4f03bc120b0b522e75ed.png

Do you planning merge this diff?
Again, thank you very much!

**Comment by id777** [comment]
Here is just a small thing: when i creating new pane or window, approx on 0.5-1 second appears "not ready" message, screenshot: https://hsto.org/files/d95/bef/465/d95bef465af74b37bd6f7f6506067f33.png
But i think it is a normal behavior.

**Comment by nicm** [comment]
Applied now, thanks! Yes the not ready message is normal, tmux is telling you the command has not finished running yet, it will display the output as soon as the command finishes.

**Comment by ptbrowne** [comment]
On macOS, the `ps` command has different arguments, I had to do : 

```
tmux set -g pane-border-format '#(ps -t #{pane_tty} -o args= | head -n 1
```
