### ISSUE TITLE
trash symbols on other pane after copying

### ISSUE THREAD

**Issue by andrey-starodubtsev** [tmux/tmux#735]
- tmux version: master d2eab39
- platform: Ubuntu 16.04.1 LTS
- TERM outside tmux: xterm-256color
- TERM inside tmux: screen

how to reproduce:
- launch tmux (I use vi-mode)
- fill screen with some text (for example, `man man`)
- `<C-B>%` (split vertically)
- `<C-B>;` (select original pane)
- `<C-B>[` (enter in selection mode)
- `Space` (select lines)
- select several lines
- `Enter` (copy selected lines to buffer)

There's trash symbols on other pane after copying:

![tmux-1](https://cloud.githubusercontent.com/assets/7666511/22197933/37f0a922-e165-11e6-8017-1e3180d306cf.png)

They disappear after selecting other tab, resizing terminal etc.

**Comment by nicm** [comment]
You are using TERM=xterm-256color but your terminal does not support the
xterm clipboard escape sequences, either use a different TERM outside
tmux, or turn the set-clipboard option off.

**Comment by andrey-starodubtsev** [comment]
Indeed, according https://askubuntu.com/questions/621522/use-tmux-set-clipboard-in-gnome-terminal-xterms-disallowedwindowops gnome-terminal doesn't implement this feature.
Using `set-option -gs set-clipboard off` fixes the issue, thank you.
