### ISSUE TITLE
server doesn't start

### ISSUE THREAD

**Issue by hgfischer** [tmux/tmux#736]
Hi,

I'm using tmux 2.1 from official Ubuntu 16.04 repository and the server doesn't seem to work. I have no special configurations for tmux.

```
 $ tmux start-server
 $ tmux new-session -d testing
 $ tmux list-sessions
no server running on /tmp/tmux-1000/default
```

Is this a known problem?

**Comment by nicm** [comment]
You are not using tmux correctly, unless you are trying to run a command called "testing".

**Comment by mtgred** [comment]
I have the same error message.

What is the correct way to use it?

On Mac OS:
```
$ brew install tmux
$ tmux
```
It works. A green bar appears at the bottom. `tmux ls` show the session.

On Arch Linux:
```
$ pacman -S tmux
$ tmux
$ tmux ls
no server running on /tmp/tmux-1000/default
```

Nothing happens after `tmux`. No green bar no error.

**Comment by pavlix** [comment]
Same in my case, should be reopened.

**Comment by GaloisZhou** [comment]
I have the same error message. 
I try to copy the `example-tmux.conf` to `~/.tmux.conf`. And then run `tmux`, it's working.
Here is my .tmux.conf:
```
#
# Example .tmux.conf
#
# By Nicholas Marriott. Public domain.
#

# Some tweaks to the status line
set -g status-bg green
set -g status-right "%H:%M"
set -g window-status-current-attr "underscore"

# No bells at all
set -g bell-action none

# Lock after 15 minutes
set -g lock-after-time 1800

# Keep windows around after they exit
set -g remain-on-exit on

# Turn on xterm-keys so that additional function keys get escape sequences
set -g xterm-keys on

# Change the prefix key to C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Turn the mouse on, but without copy mode dragging
set -g mouse on
unbind -n MouseDrag1Pane
unbind -temacs-copy MouseDrag1Pane

# Some extra key bindings to select higher numbered windows
bind F1 selectw -t:10
bind F2 selectw -t:11
bind F3 selectw -t:12
bind F4 selectw -t:13
bind F5 selectw -t:14
bind F6 selectw -t:15
bind F7 selectw -t:16
bind F8 selectw -t:17
bind F9 selectw -t:18
bind F10 selectw -t:19
bind F11 selectw -t:20
bind F12 selectw -t:21

# Keys to toggle monitoring activity in a window, and synchronize-panes
bind m set monitor-activity
bind y set synchronize-panes\; display 'synchronize-panes #{?synchronize-panes,on,off}'

# Keys to hide and show a window name from the status line
bind '-' set window-status-format '#I'\; set window-status-current-format '#I'
bind '+' set window-status-format '#I:#W#F'\; set window-status-current-format '#I:#W#F'

# Create a single default session
new -d -s0 -nirssi 'exec irssi'
set -t0:0 monitor-activity on
set  -t0:0 aggressive-resize on
neww -d -ntodo 'exec emacs ~/TODO'
setw -t0:1 aggressive-resize on
neww -d -nmutt 'exec mutt'
setw -t0:2 aggressive-resize on
neww -d
neww -d
neww -d
```

**Comment by nealmcb** [comment]
I'm having this problem when trying to run tmux inside a docker container, which I'm accessing via 

`docker exec -it containername bash`

The underlying problem is revealed by

```
$ tty
not a tty
```

If tmux could notice this and give a useful error message, that would be helpful.

See e.g. https://github.com/moby/moby/issues/8755

**Comment by mtm0riah** [comment]
I had the same issue before, and I realized that borrowed tmux config prevented to restart the server. 

You would need to clear all in your .tmux.config as a first step.

Then simply type
```
tmux
```

This should restore your server and start a new session.

**Comment by RedGreatApe** [comment]
I had a similar issue, it was caused by my tmux config. in my case it was caused by trying to set a session option

    set-option -s escape-time 0    
    set-option -s repeat-time 200

there was no session when the server tried to start and this caused it to fail

**Comment by krader1961** [comment]
@hktalent Please don't comment on a closed issue. You also did not state what your problem was or provide any server logs. Please open a new issue and include the logs from `tmux -vv`. For that matter, you might find it sufficient to look at those logs.

**Comment by jackkinsella** [comment]
For the original issue opener and the 15 people who are also facing difficulties, the likely issue is that you're calling `tmux` in the wrong way. Instead of 

`$ tmux new-session -d testing`

do this

`$ tmux new-session -t testing -d`
