### ISSUE TITLE
Funny behaviour: constantly adding new lines itself

### ISSUE THREAD

**Issue by binarykitchen** [tmux/tmux#738]
Suddenly I see this very funny behaviour: command line over a tmux session constantly adds new lines every 2 second or so. Itself, without my interference. See screenshot.

![selection_002](https://cloud.githubusercontent.com/assets/177641/22168890/f83b0886-dfd4-11e6-81fb-630af0b956f5.png)

Why is this happening and what config could cause this? Or is this because of a recent version bump? I cannot say exactly and would be great if you can give me some clues where to start investigating this?

Using latest zprezto, zsh and tmux here.

**Comment by beoldhin** [comment]
I noticed this is about Unicode 9.0 two cell wide characters. More here: https://github.com/powerline/powerline/issues/1652

**Comment by binarykitchen** [comment]
thanks for the link - among all that stuff, ssh, tmux, powerline, python, zsh, really difficult to find out who to blame.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://github.com/tmux/tmux/blob/master/CONTRIBUTING) file.

**Comment by MrMino** [comment]
I had the same issue after updating to the newest gnome desktop version in Ubuntu 16.10 and doing `apt dist-upgrade`.

Had to reinstall Ubuntu from scratch. Fun times.

Also, this doesn't affect ssh sessions at all.

**Comment by binarykitchen** [comment]
yeah, i just uninstalled powerline and then problem is gone
