### ISSUE TITLE
Add formats to set-option

### ISSUE THREAD

**Issue by odedlaz** [tmux/tmux#739]
Currently `set-option` doesn't support formatting (-F flag).
I find this feature quite useful.

Any plans on adding that?

**Comment by nicm** [comment]
Useful for what?

**Comment by odedlaz** [comment]
If you want to set variables that reference other variables, formatting can come in handy.

for instance, I created a plugin that makes tmux use atom's one dark colors.

To do so elegantly I needed to set all the colors in their own variables, then set each option and reference those variables.

Because set-option doesn't allow formatting, I wrote the whole thing as a bash script:

https://github.com/odedlaz/tmux-onedark-theme

**Comment by nicm** [comment]
I'm not sure about this. We can't do it by default for options, because it would mess up the way people already set options. So we'd need an extra flag -F to do it.

TBH I don't see it would help that much over just doing it in a shell script.

**Comment by nicm** [comment]
This might be useful for option names which would allow per-pane user options by doing @foo_#{pane_id}.

**Comment by nicm** [comment]
Try this please: [tmux-option-format.diff.txt](https://github.com/tmux/tmux/files/827934/tmux-option-format.diff.txt)
