### ISSUE TITLE
Unable to set activity-status-style with complex status bar

### ISSUE THREAD

**Issue by mhartington** [tmux/tmux#74]
Given the follow window status in tmux

```shell
set-window-option -qg window-status-format "#[fg=colour237 bg=colour237]|#[fg=white bg=colour237] #I | #W #[fg=colour237 bg=colour237]|"
```

It seems that I am unable to change the activity styles at all.

```shell
setw -g window-status-activity-style fg=white,bold,bg=colour160
```
Having two windows and having one run 

```
while true; do echo "activity"; sleep 2; done;
```

There is never any change in the activity status for that pane.

If I remove the complex settings and use the default, the activity-styles work fine.

The additional configurations of colors and symbols seem to be messing with the activity settings. Is it possible to maintain the styles that I have for the windows but still have the activity styles work?

OSX
iTerm 2
Tmux 2.0
Let me know if you need anymore information.

**Comment by nicm** [comment]
The text should change to bold, are you sure you turned monitor-activity
on? If so, then probably your terminal doesn't support bold, or doesn't
support bold with colours from the 256 colour palette.

In any case, #[] happens right at the end so it will replace the colours
set by activity-style. So if you have:

set -g window-status-format 'aa#[bg=colour237]bb#[bg=default]cc'
set -g window-status-style 'bg=red'
set -g window-status-activity-style 'bg=blue'
set -g monitor-activity on

Then "aa" and "cc" will change from red to blue on activity but not "bb".

You can either arrange your config to take this into account, or do
this:

set -g window-status-format 'aa#{?window_activity_flag,#[bg=blue],#[bg=colour237]}bb#[bg=default]cc'

**Comment by mhartington** [comment]
Ahh nice, didn't know about the `window_activity_flag`. Thanks, was able to get everything working.
