### ISSUE TITLE
Options set as if -a is given

### ISSUE THREAD

**Issue by Darkshadow2** [tmux/tmux#742]
tmux from git master
macOS 10.12.2

When you set an option that takes a list, such as `terminal-overrides` or `update-environment`, it acts like you've used `-a` even if you haven't.  Items already in the list are kept, and if you try to set it to something else, it is just added.

i.e. `tmux set -g update-environment SSH_TTY` will just append that to the list rather than resetting the list to just SSH_TTY.

**Comment by nicm** [comment]
Good spot - fixed in OpenBSD now, will be in GitHub soon, thanks.
