### ISSUE TITLE
Whats happening with named groups?

### ISSUE THREAD

**Issue by 99-lives** [tmux/tmux#745]
In issue #449 There was some discussion surrounding named groups, with @nicm saying that "it would be nice if groups had names instead of indexes". There was some confusion in the thread about other things the issue submitter wanted, but named groups are a simple idea, and it seemed to me that our awesome maintainers were quite keen on the idea.

Is adding named groups planned? Was it forgotten about? Or the idea abandoned?

I make heavy use of groups in my workflow, and simply being able to name them would be a great quality of life addition for tmux; Along with simple controls for groups, such as killing and creating sessions in them, and being able to display the group name in the status line, would also be brilliant.

I think the old issue I linked to was closed because there were various other things that the submitter wanted, and confusion as to how they should be implemented. But as I said, named groups is a simple idea, and how it should be implemented should be up to the maintainers. I hope I can start some discussion on this topic again.

**Comment by nicm** [comment]
IIRC I wrote some code but nobody tested it.

**Comment by 99-lives** [comment]
I'd be happy to test it. This is a feature I very much want, so I'll do anything I can to help. I'm not knowledgeable enough to contribute code though...

**Comment by nicm** [comment]
I don't have time to fix up the diff so that t applies again but I will try to do it at some point.

**Comment by nicm** [comment]
Try  this please:  [sg.diff.txt](https://github.com/tmux/tmux/files/745779/sg.diff.txt)

If you use new -t foo and there is no session called foo it will create a new group called foo and put the new session in it, if there is a session foo it will add it to the same session group as foo (creating a new group if necessary).

**Comment by 99-lives** [comment]
This is working great so far, on my Arch Linux machine. If I find any bugs I'll make sure to report them.

I think a few extra features are required to really flesh out this functionality, like a `kill-group` command, and being able to display the group name in the status line, as I said above. But that can all come later.

**Comment by nicm** [comment]
You can use the session_group format to display it wherever you like.

If you want to be helpful you could write some documentation for these
changes in tmux.1.

**Comment by 99-lives** [comment]
Ah, thanks for that. I still haven't read through the whole manual.

Here's an updated doc, just adding some info to the new session, --target-session section. 
[sg_docs.diff.txt](https://github.com/tmux/tmux/files/763186/sg_docs.diff.txt):
> ... Groups are named, and the group will have the same name as the target-session.  If the given target-session does not exist, it will create a new group with the name of target-session and add the new session to that group.

Hope that's up to scratch for you.

**Comment by nicm** [comment]
Good start, thanks. Applied to OpenBSD now, will be in GitHub later.
