### ISSUE TITLE
Mac overworked in nested tmux session

### ISSUE THREAD

**Issue by ddickstein** [tmux/tmux#748]
I tried creating a nested tmux session, where locally I run tmux on my laptop (Mid 2015 Retina Macbook Pro running OS X Sierra) and within that session I ssh into a remote machine's tmux session.  Functionally it works fine, but it causes the fans to kick up hard.  Running tmux on my laptop on its own or connecting to the remote tmux session in a non-nested way causes no problems.  It's not apparent to me why nesting should cause such a spike in work, so I wanted to flag that here.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.
