### ISSUE TITLE
Not working bindings in copy mode

### ISSUE THREAD

**Issue by id777** [tmux/tmux#749]
I have bindings:
```
# Alt + arrows to switch panes
bind-key -n M-Left select-pane -L
bind-key -n M-Right select-pane -R
bind-key -n M-Up select-pane -U
bind-key -n M-Down select-pane -D

# Shift + arrows to switch windows
bind-key -n S-Left previous-window
bind-key -n S-Right next-window

# Shift + Alt + up arrow to Maximaze/Minimaze
bind -n M-S-Up resize-pane -Z
```

But this bindings not working when focus located in pane with enabled copy mode. Is there way to make it work? 
I can duplicate my above bindings in copy mode too (bind-key -Tcopy-mode-vi ...). But maybe there is more simplest way.

**Comment by nicm** [comment]
You will need to duplicate the bindings at the moment.
