### ISSUE TITLE
Backslash at end of commented line will comment next line

### ISSUE THREAD

**Issue by blueyed** [tmux/tmux#75]
With the following snippet in a config, "foo" won't be displayed:

    # some comment \
    display "foo"

The Vim syntax file (`examples/tmux.vim`) does not display the second line as a comment.

The man page says:

>      Multiple commands may be specified together as part of a command sequence.
     Each command should be separated by spaces and a semicolon; commands are
     executed sequentially from left to right and lines ending with a backslash
     continue on to the next line, except when escaped by another backslash.  A
     literal semicolon may be included by escaping it with a backslash (for exam‐
     ple, when specifying a command sequence to bind-key).

The man page does not mention comments at all (a separate issue?!).

**Comment by nicm** [comment]
Apparently lines are joined before comments are removed.

**Comment by nicm** [comment]
Applied thanks
