### ISSUE TITLE
Allow kill-window to accept multiple targets via multiple -t or allow -t to accept a list of windows

### ISSUE THREAD

**Issue by derekschrock** [tmux/tmux#750]
tmux 2.3 FreeBSD 11.0-RELEASE

When trying to kill multiple windows with -t ... or ... -a -t .... there are cases where I don't want to kill all but one (-a -t target) or I want to kill a set of windows.

Could kill-window -t accept multiple targets via a comma separated list or multiple -t?

ex:  
```
       tmux kill-window -t 1 -t 2        # Kill windows 1 and 2
       tmux kill-window -t 1,2

       tmux kill-window -a -t 1 -t 2     # Kill all windows but 1 and 2
       tmux kill-window -a -t 1,2
```

Right now tmux uses the last -t passed

**Comment by nicm** [comment]
This has been in the TODO file forever but it is not enough to just do killw, you will need to make a general solution that works for the other commands too and it is not trivial. For now you will have to loop over the command in sh.
