### ISSUE TITLE
displaying the state of 'synchronize-panes' always reports 'on'

### ISSUE THREAD

**Issue by er0** [tmux/tmux#751]
toggling the synchronize-panes, works great, but when panes are not synchronized the display query reports 'on' for either state.

Version: built from git 68d9107
Platform: Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
tmux.conf:
bind y set synchronize-panes\; display 'synchronize-panes #{?synchronize-panes,on,off}'
terminal: simple terminal (st) http://st.suckless.org/
TERM: screen

**Comment by er0** [comment]
[tmux-server-30722.log.txt](https://github.com/tmux/tmux/files/739821/tmux-server-30722.log.txt)

**Comment by nicm** [comment]
Yes this is an error introduced recently, I accidentally made the #{foo} form of flag options return "on" or "off" (which are both true) instead of "0" or "1". I've fixed this in OpenBSD now, it should be in GitHub in an hour or so. Thanks!
