### ISSUE TITLE
invalid or unknown command: `bind-key -t vi-copy ....`

### ISSUE THREAD

**Issue by kevinushey** [tmux/tmux#754]
It looks like my attempts to bind keys in my `.tmux.conf` with `vi-copy` are now failing:

```
/Users/kevin/.tmux.conf:25: invalid or unknown command: bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"
/Users/kevin/.tmux.conf:26: invalid or unknown command: bind-key -t vi-copy v begin-selection
/Users/kevin/.tmux.conf:30: invalid or unknown command: bind-key -t vi-copy Y copy-end-of-line
/Users/kevin/.tmux.conf:31: invalid or unknown command: bind-key -t vi-copy V rectangle-toggle
/Users/kevin/.tmux.conf:32: invalid or unknown command: bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
/Users/kevin/.tmux.conf.2:3: invalid or unknown command: bind-key -t vi-copy PPage page-up
/Users/kevin/.tmux.conf.2:4: invalid or unknown command: bind-key -t vi-copy NPage page-down
```

Is this expected with current `tmux`?

```
$ tmux -V
tmux master
```

Thanks!

**Comment by kevinushey** [comment]
Reading the updating man pages, it looks like this is intentional, and we must now write e.g.

    bind-key -t vi-copy ...      # before
    bind-key -T copy-mode-vi ... # after

Are there any plans to support the old way of declaring copy-mode keybindings?

**Comment by nicm** [comment]
No this is how it is now.

**Comment by kevinushey** [comment]
Got it; thanks.

**Comment by timotheecour** [comment]
@nicm 
can this new syntax be backported to previous version of tmux? so that tmux.conf will work in either

**Comment by alaska** [comment]
# Conversion how-to
For anyone who finds this for posterity, the full changes should be as follows:

## Steps
1. replace ```-t``` with ```-T```
2. replace ```vi-<name>``` with ```<name>-mode-vi```
3. prefix the command with ```send-keys -X```

## Example
From my own tmux.conf:

### Old Way
```
bind-key -t vi-edit Up history-up
bind-key -t vi-edit Down history-down
unbind-key -t vi-copy Space     ;   bind-key -t vi-copy v begin-selection
unbind-key -t vi-copy Enter     ;   bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"
unbind-key -t vi-copy C-v       ;   bind-key -t vi-copy C-v rectangle-toggle
unbind-key -t vi-copy [         ;   bind-key -t vi-copy [ begin-selection
unbind-key -t vi-copy ]         ;   bind-key -t vi-copy ] copy-selection
```

### New Way
```
bind-key -T edit-mode-vi Up send-keys -X history-up
bind-key -T edit-mode-vi Down send-keys -X history-down
unbind-key -T copy-mode-vi Space     ;   bind-key -T copy-mode-vi v send-keys -X begin-selection
unbind-key -T copy-mode-vi Enter     ;   bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
unbind-key -T copy-mode-vi C-v       ;   bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
unbind-key -T copy-mode-vi [         ;   bind-key -T copy-mode-vi [ send-keys -X begin-selection
unbind-key -T copy-mode-vi ]         ;   bind-key -T copy-mode-vi ] send-keys -X copy-selection
```

**Comment by exhuma** [comment]
Hmm... I've got my config files synced via a git project. But not all machines have the same version of tmux installed. So I now have to decide where I want my bindings to work if I don't want to maintain two versions of my tmux.conf 😞

**Comment by labianchin** [comment]
@exhuma [this is what I am doing](https://github.com/labianchin/dotfiles/commit/cd0b079d92d788cec322a61e4c0765524212118a) on `tmux.conf` to be compatible with older tmux versions:

```
# based on https://stackoverflow.com/a/40902312/1046584
run-shell "tmux setenv -g TMUX_VERSION $(tmux -V | cut -c 6-)"

# In version 2.1 "mouse" replaced the previous 4 mouse options
if-shell -b '[ "$(echo "$TMUX_VERSION >= 2.1" | bc)" = 1 ]' \
  "set -g mouse on"

# UTF8 is autodetected in 2.2 onwards, but errors if explicitly set
if-shell -b '[ "$(echo "$TMUX_VERSION < 2.2" | bc)" = 1 ]' \
  "set -g utf8 on; set -g status-utf8 on; set -g mouse-utf8 on"

# New keybindings for vi-mode
# https://github.com/tmux/tmux/issues/754
if-shell -b '[ "$(echo "$TMUX_VERSION >= 2.4" | bc)" = 1 ]' \
   'bind -T copy-mode-vi v send-keys -X begin-selection ; \
   bind -T copy-mode-vi C-v send-keys -X rectangle-toggle ; \
   bind -T copy-mode-vi y send-keys -X copy-selection ; \
   bind -T copy-mode-vi H send-keys -X start-of-line ; \
   bind -T copy-mode-vi L send-keys -X end-of-line ; \
   bind -T choice-mode-vi h send-keys -X tree-collapse ; \
   bind -T choice-mode-vi l send-keys -X tree-expand ; \
   bind -T choice-mode-vi H send-keys -X tree-collapse-all ; \
   bind -T choice-mode-vi L send-keys -X tree-expand-all ; \
   bind -T copy-mode-emacs MouseDragEnd1Pane send-keys -X copy-pipe "pbcopy"; \
   bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "pbcopy"; ' \
   'bind -t vi-copy v begin-selection; \
   bind -t vi-copy C-v rectangle-toggle; \
   bind -t vi-copy y copy-selection; \
   bind -t vi-choice h tree-collapse; \
   bind -t vi-choice l tree-expand; \
   bind -t vi-choice H tree-collapse-all; \
   bind -t vi-choice L tree-expand-all; \
   bind -t emacs-copy MouseDragEnd1Pane copy-pipe "pbcopy"; \
   bind -t vi-copy MouseDragEnd1Pane copy-pipe "pbcopy"; '
```

**Comment by kevinushey** [comment]
I put together a simple tool for generating `.tmux.conf` configuration files tailored towards a particular platform from a single 'source of truth'. The repository lives here:

https://github.com/kevinushey/tmux-config

The general idea is that you can embed `sh` directives in your `.tmux.conf` file, e.g.

```
# @if [ "${TMUX_VERSION}" \< "2.0" ]
set -gq mode-mouse on
set -gq mouse-resize-pane on
set -gq mouse-select-pane on
set -gq mouse-select-window on
# @else
set -gq mouse on
# @fi
```

and `tmux-config` will do the work of generating and sourcing a tmux configuration file based in that source of truth.

Although this doesn't do anything you couldn't already do with clever use of `if-shell`, I think this is a cleaner solution to the problem. Hopefully someone else finds it useful!

**Comment by pedroarthur** [comment]
@labianchin since I have no `bc`, I changed your code to use `awk`:

    
    if-shell -b 'awk "$0 >= 2.4 { exit(0) }" <<< $TMUX_VERSION'  \
        # code flows the same now on
    

Thanks for the idea!

**Comment by samgranieri** [comment]
This helped me out a ton. Thanks!!

**Comment by anowlcalledjosh** [comment]
Note that if you're using a pre-release version of tmux, you can declare `$TMUX_VERSION` like this instead to avoid your comparison failing when you try to numerically compare `2.4` with `2.6-rc3`:

```sh
run-shell "tmux setenv -g TMUX_VERSION $(tmux -V | cut -c 6- | cut -d- -f1)"
```

**Comment by ksze** [comment]
What's the deal with `send-key -X`? I don't see `-X` in the manpage of tmux 2.6.

**Comment by wookayin** [comment]
Just for a future reference: the version detection trick based on `bc` does not work with recent tmux's version strings such as `2.9a` or `3.0a`. I ended up doing like:

```bash
if-shell -b '[ "$(echo -e "$TMUX_VERSION\n"2.4 | sort -V | head -n1)" == "2.4" ]' \
   'bind -T copy-mode-vi "v" send-keys -X begin-selection; \
    bind -T copy-mode-vi "y" send-keys -X copy-pipe-and-cancel "pbcopy"; \
   '
```
