### ISSUE TITLE
Feature request: tmux control mode: notify about called commands

### ISSUE THREAD

**Issue by braph** [tmux/tmux#755]
Hello,

the tmux control mode currently provides notifications such as `%output, %sessions-changed, %window-add`, etc.

I think it would be nice if the control mode also notifies about commands that have been run (by other clients).

I added this functionality by changing the cmdq_fire_command() in cmd-queue.c [link](https://github.com/braph/tmux/commit/a28e596de26658407f0d871e2bfc5f7c8d752582
).
Sample output on control mode client:

```
#                 timestamp  num command 
%command-executed 1485978232 365 select-window -t 4
```

Background information:

I am writing a script that keeps a history of the last selected windows. Later, I want to go forward/backword in that history.
The script talks to tmux using the control mode. It needs to know when the user switched his active window (called select-window).

My current solution for getting this event looks like this:
   - Register hook for select-window
     ` set-hook after-select-window 'run -b "echo call-hook select-window > script_fifo"'`
   - Hook writes the command name to fifo file
   - Script listens on fifo for "call-hook ..." commands

In my case, adding a notification about called commands would save me a FIFO file and the after-select-window hook would not be abused.

Maybe this is also useful for other people working with the control mode.

Regards,

Benjamin

**Comment by nicm** [comment]
Sure, but it can be simpler, please try this: [x.diff.txt](https://github.com/tmux/tmux/files/746177/x.diff.txt)

I don't see why you need the time and number in the output?

**Comment by braph** [comment]
Great, that looks more clean.

I don't need the timestamp or command number. But I thought they could be useful.

Another question:

How about extending `display-message` (or adding a new command) for writing to all control mode clients?

`bind 1 display-message -C "custom output for tmux control client"`

This way we could create custom hooks.

`bind 1 display-message -C "%call select-window-fuzzy -t 1`
`bind 2 display-message -C "%call select-window-fuzzy -t 2`

The goal is to `bind` a key to an alternative version of `select-window`, called `select-window-fuzzy`.
That command is provided by the script around `tmux -C`. It parses `%call select-window-fuzzy -t ...` and runs the modified `select-window`.

**Comment by nicm** [comment]
I don't really understand what you are trying to do here.

If you want a control mode notification when the current window changes,
just add it, like the existing client-session-changed. But I would
suggest adding the same for the active pane too.

If you want to replace a builtin command, I think the best thing to do
would be to change the command-aliases[] stuff in master to do this. At
the moment it will only look for an alias if no command is found, but it
could easily be changed to look for an alias first.

tmux already keeps a history of the previously selected windows, it is in
s->lastw. You could easily make it accessible in some way.

**Comment by braph** [comment]
Nice, I didn't know about the command-aliases[] yet.

> If you want a control mode notification when the current window changes,
> just add it, like the existing client-session-changed. But I would
> suggest adding the same for the active pane too.

Like [this](https://github.com/braph/tmux/commit/479471bcde1622e82232d099b09b54f340388ffb
)?

Sample output
```
# session id, window id
%window-selected $0 @1
# session id, window id, pane id
%pane-selected $0 @1 @1
```

> tmux already keeps a history of the previously selected windows, it is in
> s->lastw. You could easily make it accessible in some way.

I thought on extending the `list-windows` command to make the last window queue
available.

https://github.com/braph/tmux/commit/daad9c82ed638cbe768051d1be5e010a7674dd76

```
$ tmux list-window -l # list windows in queue order
2: zsh- (1 panes) [80x23] [layout ae5f,80x23,0,0,2] @2
3: zsh (1 panes) [80x23] [layout ae60,80x23,0,0,3] @3
1: zsh (1 panes) [80x23] [layout ae5e,80x23,0,0,1] @1
0: zsh (1 panes) [80x23] [layout ae5d,80x23,0,0,0] @0

$ tmux list-windows -l -a # list sessions and their windows in queue order
0:2: zsh- (1 panes) [80x23]
0:3: zsh (1 panes) [80x23]
0:1: zsh (1 panes) [80x23]
0:0: zsh (1 panes) [80x23]
1:3: zsh- (1 panes) [80x22]
1:1: zsh (1 panes) [80x22]
1:2: zsh (1 panes) [80x22]

$ tmux list-windows -a 
0:0: zsh (1 panes) [80x23]
0:1: zsh (1 panes) [80x23]
0:2: zsh- (1 panes) [80x23]
0:3: zsh (1 panes) [80x23]
0:4: zsh* (1 panes) [80x23]
1:0: zsh* (1 panes) [80x22]
1:1: zsh (1 panes) [80x22]
1:2: zsh (1 panes) [80x22]
1:3: zsh- (1 panes) [80x22]
```

> If you want to replace a builtin command, I think the best thing to do
> would be to change the command-aliases[] stuff in master to do this.

Yeah, but the replacement for the builtin lives inside a script.

> I don't really understand what you are trying to do here.

What I am trying to achieve with writing directly to the control mode instances is the following:

I got a tmux "plugin" script that attaches to the user's session in control mode.
That script provides the `select-window-fuzzy` command (which is basically just a `select-window` that selects the next nearest window if the target window was not found).
That `select-window-fuzzy` command should be callable inside tmux.

Currently I'm doing that using a FIFO as described in my first post:
`bind 1 run -b "echo select-window-fuzzy -t 1 >> script_fifo`
The plugin script reads the FIFO and executes the `select-window-fuzzy` function if it parses it.

But that could be simplified:
`bind 1 display-message -C "%call_plugin_command select-window-fuzzy -t 1"`
This way the FIFO could be dropped. Instead the script only relies on the output of the control mode.

Why not just `run` the plugin script using `bind`?
I could also do a `bind 1 run -b 'select_window_fuzzy.rb -t 1` but that would not be as fast as just
talking to a persistent process. Using a new process each time will also make it hard to save its state among invocations.

**Comment by nicm** [comment]
Yes like that except I would call them window-pane-changed and
session-window-changed, also you need to add them to tmux.1.

**Comment by nicm** [comment]
I am closing this but please continue to comment if you settle what you need.
