### ISSUE TITLE
Feature request: Read/Activity marker

### ISSUE THREAD

**Issue by schreq** [tmux/tmux#758]
Would be nice to have an option for drawing a line when switching windows like some irc clients do. That way one can easily tell what's new since the window was last viewed.  A command to automatically scroll to the marker could be quite useful as well.

**Comment by unphased** [comment]
I don't know what you're describing, only have used IRC a few times.

**Comment by nicm** [comment]
I would like a generic way of adding marks in the history, and this could be part of it. Also iTerm2 has some escape sequences to set marks, we could add them too. Added to TODO file.

**Comment by unphased** [comment]
Oh! I understand now, that would be a SWEET feature.
