### ISSUE TITLE
Pane split line does not show correctly

### ISSUE THREAD

**Issue by kaienkira** [tmux/tmux#759]
ENV: 
```
original tmux v2.1 on Ubuntu 16.04 server
use secureCRT v6.2.3 from Windows 7 to connect the ubuntu server
secureCRT use xterm + ansi color, utf-8
bash use LANG=en_US.UTF-8
no .tmux.conf, every config is default
```
Steps:
```
tmux new -s dev
ctrl + b + %
```
Problem:
![pane-split-line](https://cloud.githubusercontent.com/assets/1057578/22624327/9a3d7daa-ebb3-11e6-8797-0d4d92975247.PNG)

[tmux-server-2427.txt](https://github.com/tmux/tmux/files/752797/tmux-server-2427.txt)
[tmux-out-2427.txt](https://github.com/tmux/tmux/files/752798/tmux-out-2427.txt)

Any suggestion?

**Comment by nicm** [comment]
Looks to me like your terminal doesn't support UTF-8 line drawing
characters. I suggest you use a UTF-8 terminal, or unset
LANG/LC_ALL/LC_CTYPE before starting tmux.
