### ISSUE TITLE
Allow getting environment variables via FORMATS

### ISSUE THREAD

**Issue by blueyed** [tmux/tmux#76]
Given the new `if -F` feature with tmux 2.0, it would be very useful to have a way to get an environment variable.

This could be used for vim-tmux-navigator to detect if Vim in running in tmux (see https://github.com/christoomey/vim-tmux-navigator/pull/37 for a PR in this regard).

It currently sets an environment variable from Vim and then uses `if` in a binding to check it:
 
    tmux show-env tmux_navigator_bypass_#{pane_id} >/dev/null 2>&1

Something like the following would be nice:

    if_vim='if -F "#{env:tmux_navigator_bypass_#{pane_id}}"
    bind -n C-h "$if_vim" "send-keys C-h" "select-pane -L"
    bind -n C-j "$if_vim" "send-keys C-j" "select-pane -D"
    bind -n C-k "$if_vim" "send-keys C-k" "select-pane -U"
    bind -n C-l "$if_vim" "send-keys C-l" "select-pane -R"
    bind -n C-\ "$if_vim" "send-keys C-\\" "select-pane -l"

**Comment by nicm** [comment]
Just {FOO} would be easy enough, look at how options were added to formats.

**Comment by nicm** [comment]
Done now.
