### ISSUE TITLE
ability to set xterm title escape sequence globally by tmux

### ISSUE THREAD

**Issue by unphased** [tmux/tmux#764]
I'm looking for a way to communicate various information about tmux window layout state up through SSH. The use case is to run SSH -> Tmux inside of a Tmux pane. This is a workflow that enables the possibility of effective orchestration of multiple machines with Tmux. 

The main idea is that of a unified keybinding system that lets you navigate panes in the outer and inner tmuxes. So you could imagine a maximized tmux window, and inside of it are 3 panes, each SSH'd into a different server, and Tmux is run inside them. 

We can trivially make two sets of 4 directional key binds, one set to move around between the machines and one that "tunnels" through (where the outer tmux performs a keybind translation). 

I'm looking to do better than this and it can be done using an `if-shell` based contextual switch program. I used to use a bash script, which turned into an inline dash-compatible `case` shell statement, and now it is a native C++ program. At any rate, this program is used to decide whether to just switch the pane or to pass along a key. But for this situation something extra is needed: the state of the inner tmux, specifically, whether the pane of the inner tmux is at a corresponding edge or not, and this would determine whether we want to switch panes on the inside or on the outside. 

Whew, ok now that the explanation has been specified, I have already done the work to see that this (very specific) information as specified above can be produced. `tmux list-panes -F "#{pane_bottom} #{pane_left} ..."` etc and logic done on top of that easily reveals whether the focused pane is at an edge or not, and which edge it is. 

What remains is for the inner tmux to communicate this state back to the outer tmux, this has always been a stumbling block, but what's great is that tmux will automatically handle the xterm title escape sequence as the pane title. This works great! So all I need is for the inner tmux to emit the escape sequences `\033]0;` `\007` sequences. I see no option in the manpage for this, but the feature should be trivial to implement as a new tmux command which simply echoes it out inside those escapes.

**Comment by nicm** [comment]
If you change set-titles-string it will use that for the title, but you
could also send your own escape sequences instead using the DCS
passthrough escape sequence. So long as they don't modify the terminal
tmux won't care.

**Comment by unphased** [comment]
Wow yes that's right, it is in the manpage. Couldn't find it! 

Brilliant

**Comment by unphased** [comment]
I'm testing this and am not sure how to trigger Tmux to issue the sequence. At any rate, I'm unable to make the outer tmux receive a new title. I'll test it with a single regular tmux inside a regular terminal window, though, as that's the "original" use case anyway.

**Comment by unphased** [comment]
This is where this should be happening: 

https://github.com/tmux/tmux/blob/master/server-client.c#L1241

Still perusing a bit to identify what my particular problem is. I'll try to add some debug code in here and troubleshoot it myself, and if that fails probably all I would need for what I want is my own simpler version of this `server_client_set_title` function.

**Comment by nicm** [comment]
I don't know what you are asking here. tmux setting the title definitely
works. Do you have the set-titles option on?

**Comment by unphased** [comment]
Yeah I was playing around with it and could not find a way to get it to set the title. I'll be able to debug it by getting my hands dirty though

**Comment by unphased** [comment]
I was digging around in the iterm settings and saw the checkbox "Terminal may report window title", this was not checked. I'll look into whether this functionality works once I check this.
