### ISSUE TITLE
reattach-to-user-namespace for copy paste to status line

### ISSUE THREAD

**Issue by timotheecour** [tmux/tmux#766]
when pasting `FOO` to status line after `^b ,` to rename a window, the window title becomes:
`200FOO201~` instead of `FOO`

using iterm2 sshing to ubuntu from mac
```
tmux 2.3
screen
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

same issue when using tmux on mac, where my ~/.tmux.conf has:

`set -g default-command "reattach-to-user-namespace -l ${SHELL}"`
which avoids the exact same issue but for pasting into window, not window status bar

workaround: use `tmux rename-window FOO` instead of `^b ,`

**Comment by nicm** [comment]
The application inside tmux must have requested bracketed paste mode and
so tmux has turned it on outside.

Does this fix it:

Index: server-client.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/server-client.c,v
retrieving revision 1.210
diff -u -p -r1.210 server-client.c
--- server-client.c	3 Feb 2017 11:57:27 -0000	1.210
+++ server-client.c	8 Feb 2017 11:50:14 -0000
@@ -1110,6 +1110,10 @@ server_client_reset_state(struct client 
 			mode |= MODE_MOUSE_BUTTON;
 	}
 
+	/* Clear bracketed paste mode if at the prompt. */
+	if (c->prompt_string != NULL)
+		mode &= ~MODE_BRACKETPASTE;
+
 	/* Set the terminal mode and reset attributes. */
 	tty_update_mode(&c->tty, mode, s);
 	tty_reset(&c->tty);
