### ISSUE TITLE
Feature request: session-base-index

### ISSUE THREAD

**Issue by adamyonk** [tmux/tmux#769]
I would love to be able to set something like a `session-base-index` so that I could change the index of the sessions in `choose-tree` similar to how you can change the index for windows with `base-index`:

![pasted image at 2017_02_09 14_11](https://cloud.githubusercontent.com/assets/33258/22801318/fc94e986-eed1-11e6-8630-0f6a6cf39696.png)

_Edited:_ s/pane-base-index/base-index/, more description

**Comment by nicm** [comment]
I don't see much point. Session 0 is never reused, if you don't want a
session 0 then create it and kill it in .tmux.conf.

**Comment by adamyonk** [comment]
I meant so that you could use the [1] key to get to the first session in the `choose tree` list.

**Comment by adamyonk** [comment]
If I kill a session, the session that was `(1)` in that list becomes `(0)`.

**Comment by nicm** [comment]
base-index doesn't change that either.

**Comment by adamyonk** [comment]
When I set pane-base-index I get to the first pane in the session with prefix+1/2/3 instead of prefix+0/1/2.

**Comment by adamyonk** [comment]
Sorry, I meant base-index and windows, not pane-base-index and panes.

**Comment by nicm** [comment]
These are a key, not an index but I don't think it would do any harm for the number keys to start at base-index (if it is <= 9) for everything (sessions, windows, buffers,etc). But it will have to be in the new choose modes, I'm not going to change the existing code - @ThomasAdam?

**Comment by ThomasAdam** [comment]
I'm fine with this for the new choose-mode we're working on, certainly not for how choose-tree currently works.  I'm assuming this won't be configurable?  That is, we'll apply any base-index setting if it exists?

**Comment by nicm** [comment]
Right, base-index will be the option for all - it will mean "I like my
numbers to start here" - windows, keys, whatever.

**Comment by ThomasAdam** [comment]
Cool -- I'll add it to the top of the file in my TODO block.  Marking this as closed.

**Comment by adamyonk** [comment]
Thanks, sorry for my confusing language.

**Comment by cj** [comment]
@ThomasAdam did this get added in?  I can't see it in TODO or CHANGES.  I would love to set my session default index to 1 instead of 0, like windows.

**Comment by ThomasAdam** [comment]
No, it didn't. Sessions are counted globally. I can't see why this needs to
change.

**Comment by chauncey-garrett** [comment]
I too would appreciate having the ability to start counting from 1 instead of 0. Like many others, I have both `base-index` and `pane-base-index` set to `1` instead of the default `0` so that all keys start on the left side of my keyboard. When transitioning from switching windows/panes to switching sessions, the numbering inconsistency is disruptive.

**Comment by chauncey-garrett** [comment]
I too would appreciate having the ability to start counting from 1 instead of 0. Like many others, I have both `base-index` and `pane-base-index` set to `1` instead of the default `0` so that all keys start on the left side of my keyboard. When switching sessions, the numbering inconsistency is disruptive.

It certainly seems like it's not an uncommonly wished for feature: https://unix.stackexchange.com/questions/313577/how-to-make-tmux-sessions-count-from-1-instead-of-0

**Comment by ThomasAdam** [comment]
That doesn't mean a thing. Given the way sessions are governed, and the
fact that most users name their sessions, this means nothing.

**Comment by adamyonk** [comment]
Again, in `choose-tree -s` you don't jump by name, but by index (0, 1, 2). 
<img width="277" alt="messages image 711525232" src="https://user-images.githubusercontent.com/33258/31688686-bf50bf96-b352-11e7-9413-48eb8b2148a2.png">

**Comment by chauncey-garrett** [comment]
Same here. I have `choose-session` bound to `Space`:

![2017-10-17 at 16 08](https://user-images.githubusercontent.com/302358/31689714-ee8adb54-b355-11e7-88ba-106e09ad81f8.png)

So `prefix + Space` gets me here:

![2017-10-17 at 16 09](https://user-images.githubusercontent.com/302358/31689701-e0912b52-b355-11e7-8de2-d2b23b468c6b.png)

and then pressing `1` would take me to the named `prezto` session.

**Comment by j-pb** [comment]
This would be a really nice thing to have, I find myself in the need to kill sessions a lot in pair programming, and it's a mental mismatch between 1 based window indexing and this.
It's not a deal breaker, but it would be a really nice to have.

**Comment by last5bits** [comment]
@ThomasAdam Do you find this feature of session-base-index hard to implement? If implemented, is it likely to be accepted to the repo? Thanks!

**Comment by ThomasAdam** [comment]
No, and no.

**Comment by adamyonk** [comment]
@ThomasAdam maybe if you could explain how we got from

> Cool -- I'll add it to the top of the file in my TODO block.

to

> WONTFIX

?

**Comment by ThomasAdam** [comment]
Different thing, entirely.

**Comment by ThomasAdam** [comment]
No misunderstanding. It's just not a helpful feature.

**Comment by adamyonk** [comment]
I think everyone is wondering why you can set `base-index` and `pane-base-index` but     not this index. Those other "features" seem helpful.

**Comment by nicm** [comment]
We are not going to change the default session naming.

I think if we are going to have a way to change the quick key bindings in
choose mode to start at 1 then we should just roll all this stuff into one
base-index option.

**Comment by last5bits** [comment]
The number of thumbs down on your message suggest the opposite. This feature would certainly be useful for me, and I'm not alone.

**Comment by last5bits** [comment]
![image](https://user-images.githubusercontent.com/290707/39067033-3fef99b8-44a5-11e8-88c7-766e7b16f995.png)

**Comment by rl1k** [comment]
every forum and on stack we can see a lot of people asking for this feature like bas-index for windows starting at 1 but this isn't helpful fr the dev... never saw a guy so...

**Comment by ierdnah** [comment]
+1 for this feature

**Comment by krader1961** [comment]
@ierdnah It seems like you did not read the issue. The cost of this backward incompatible change cannot be justified.

**Comment by anowlcalledjosh** [comment]
@krader1961 which change are you referring to? changing the _default_ session-base-index may be backwards-incompatible, but adding a new config option to allow the session-base-index to be changed (much like the existing base-index and pane-base-index options) doesn't seem like it would break anything.

**Comment by nicm** [comment]
Sessions do not have indexes or numbers, they have names. If you don't like
session 0 then create and kill it in your config so tmux creates the next
one at 1, or use new -s to set names you do like.

**Comment by ierdnah** [comment]
I understand that sessions have names but when you press "ctrl+b s" first is an index number and then is the session name. So sessions do have indexes.
You could let the user decide about the backward incompatibility by adding a config option and warning that it is backward incompatible.
