### ISSUE TITLE
Tmux overlap next character when modifying the bash input history

### ISSUE THREAD

**Issue by dreamingo** [tmux/tmux#771]
Hi, When I search input history in bash, for example,  I got:
```bash
vim test.c
```
when I move the cursor(I use vim mode in bash) to the beginning of the command line and try to modify `vim test.c` to `ls test.c`, but in tmux, after I delete `vim` and type `ls`, I found that the characters will overlap the existed command, which result in `lsst.c`; However, when I press enter, the whole command is `ls test.c`

The phenomenon described above just occasionally appear. Once I open a new pane, everything goes right but it will broken for a while..

The term configuration in my `.tmux.conf` is:
```bash
set -g default-terminal "screen-256color"   
```

my term configuration in my `~/.bashrc` is:
```bash
 TERM=xterm-256color;export TERM
```

Can anyone help me, Thanks!

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.
