### ISSUE TITLE
"send-keys -X" in a bind-key no longer working

### ISSUE THREAD

**Issue by rfrancoise** [tmux/tmux#774]
Originally reported here: https://bugs.debian.org/850146

I can reproduce this with current master.

> In my ~/.tmux.conf I've got these settings (among others):
>
>     bind-key M-,     copy-mode \; send-keys -X 0 Left Left ^ Space E Enter \; paste-buffer
>     bind-key M-.     copy-mode \; send-keys -X 0 Left Left Space B Enter \; paste-buffer
>     bind-key M-Enter copy-mode \; send-keys -X 0 Left Left Space ^ Enter \; paste-buffer
>
> These select the first word, the last word, or the whole line in the line 
> above the cursor.
>
> For example, when doing a "du -sk X" command I was able to copy the number 
> out via these keypresses.
>
>
> Now this doesn't work any more.
> "tmux" goes into copy-mode; I can see the [0/X] position in the top-right 
> corner, but the "send-keys -X" doesn't seem to be active, and the keys just 
> vanish.
> After pressing Enter (a few times) or Ctrl-C (once) to get out of 
> copy-mode, the buffer contents are pasted, though; so it's just the 
> "send-keys" that's not working.

**Comment by nicm** [comment]
This never worked, -X has only ever accepted a command not a key.

**Comment by rfrancoise** [comment]
Hmm, then I guess the original reporter was confused...

But now that I try it the way it's supposed to work, this doesn't do anything either when run from the key while it does work when using send-keys from the outside:

    bind-key M-Enter copy-mode \; send-keys -X cursor-up copy-line \; paste-buffer

**Comment by nicm** [comment]
-X only accepts one command at a time, so you will need two send -X
commands.

**Comment by rfrancoise** [comment]
Duh, thanks, and sorry for wasting your time.
