### ISSUE TITLE
Want to disable mouse, getting error on options.

### ISSUE THREAD

**Issue by yatesj9** [tmux/tmux#780]
Not able to disable the Mouse getting error

.tmux.conf:83: unknown option: mode-mouse                                                                                                                                                
.tmux.conf:84: unknown option: mouse-select-pane
.tmux.conf:85: unknown option: mouse-resize-pane
.tmux.conf:86: unknown option: mouse-select-window

.tmux config has this

setw -g mode-mouse off
set  -g mouse-select-pane off
set  -g mouse-resize-pane off
set  -g mouse-select-window off

**Comment by sphaugh** [comment]
All of the mouse options were put into just mouse.

`set -g mouse off`

The default is off btw.
