### ISSUE TITLE
Proposal: Set default format string for choose-window, etc?

### ISSUE THREAD

**Issue by sphaugh** [tmux/tmux#781]
Maybe I'm just blind and didn't read the man pages thoroughly. Is there a way to set the default format string? It doesn't seem very elegant to manually configure each command that uses choose-window.

**Comment by nicm** [comment]
No, and the formats will be going away anyway in time (2.5 or 2.6 maybe?) so I wouldn't get too used to them.

**Comment by RobertoFranceschini** [comment]
any change on this? I am on 2.4 and woud like to change the wait "choose-windows" shows the list. How to do that?
