### ISSUE TITLE
line reflow messed up

### ISSUE THREAD

**Issue by timotheecour** [tmux/tmux#783]
```
lsb_release -a  && tmux -V && echo $TERM

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
tmux 2.3
screen
```

not sure what triggers it but i sometimes end up with line reflow messed up in some panes and the only way to recover is to kill the offending pane:

![image](https://cloud.githubusercontent.com/assets/2194784/23053249/de74636c-f48c-11e6-8dc0-e60e9cdd34c9.png)

**Comment by nicm** [comment]
Can you reproduce this in master?
