### ISSUE TITLE
Possible to silence the "<'cmd' not ready>" message?

### ISSUE THREAD

**Issue by unhammer** [tmux/tmux#784]
According to the man page, when tmux is waiting for a `#(cmd)` command to finish, if it has not yet run for the first time, a placeholder shall be used (what placeholder?), while if it has run before, the previous output is used. However, [tmux 2.2](http://packages.ubuntu.com/yakkety/tmux) instead shows `<'cmd' not ready>` – e.g. try doing `tmux setw -g window-status-current-format '#(sleep 1; date +%s )' `.

Is it possible to get tmux to do use an empty placeholder (even if the command changed)? Or at least to silence the "not ready" message? It's messing up my status line with duplicate lines:

![tmux-status-mess](https://cloud.githubusercontent.com/assets/56868/23061318/a52be830-f501-11e6-91ff-da24cc08775d.png)

**Comment by nicm** [comment]
The placeholder is "'cmd' not ready".

"sleep 1; date +%s" is a poor idea because when tmux expands %s it will be a different command every time (date +1234, date +1235 and so on), so there will never be any previous output and you will always see the placeholder during the sleep.

The behaviour has changed slightly in master so it looks up the previous output before expanding tmux formats (but it is still after expanding strftime() formats).

**Comment by unhammer** [comment]
The sleep example was just to have something reproducible ;-) What I'm using is `#(tmux-status-name `tmux display-message -p "#W #{pane_pid}"` (where tmux-status-name actually just prints back the `#W` in this case), so it changes only on new commands. 

-----

I notice now that the double status line issue is due to my using a wrapper around ssh `printf '\033k💻 %s\033\\' "$1"; command ssh "$@"` which used to work fine in http://packages.ubuntu.com/xenial/tmux 2.1 but does not in http://packages.ubuntu.com/yakkety/tmux 2.2 nor in 2.3 on Arch Linux – `printf '\033k💻 %s\033\\' foo` always messes up my status lines. Is this worth opening a new issue for?

**Comment by nicm** [comment]
You should try tmux from master.

**Comment by nicm** [comment]
#W and #{pane_pid} suffer from the same problem as %s in 2.3, in master they do not.

Open a new issue for UTF-8 problems only if you can reproduce with master and using utf8proc doesn't fix it, and make sure to include logs.

**Comment by unhammer** [comment]
`./configure --enable-utf8proc` solves the issue in master (otherwise it's still reproducible when no utf8proc, with a simple `printf '\033k💻NAME\033\\'` and empty .tmux.conf/.bashrc), so I won't open a new issue.

If there's no way to change the placeholder I guess this can be closed too.
