### ISSUE TITLE
Binding raw escape sequences

### ISSUE THREAD

**Issue by agilmor** [tmux/tmux#786]
Hi,

First of all, thanks a lot for such a nice tool!
It really changed my life!!

This is a feature-request.

Some time ago I had some problems with key-combos that I love to use like <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Arrows</kbd>, plus accessing to remote Linux servers from MobaXterm, etc. Yes, a really bad combination... I known.
Anyway, I made it work with some specific combination of, `TERM`, `xterm-keys`, `default-terminal`, etc... and it worked nice for a while!

But now I need to work in another and newer windows+mobaxterm combination, and I just can't make it work after hours of reading an regoogleing...

I'm pretty sure that the problem is not on tmux at all!
But I was wondering if could be possible to add this kind of bindings in `tmux.conf`:
```
bind -n ^[[1;2C prev
bind -n ^[[1;2D next
```

Again, I'm sure that tmux is handeling escape sequence fine, and this comment put it clear: https://github.com/tmux/tmux/issues/120#issuecomment-143375064

My point is just that at the end of the day, if I'm able to see with <kbd>Ctrl</kbd>+<kbd>v</kbd> what escape sequence is my ugly combination of terminal emulators is sending to tmux, then I could custimze my bindings quite easly with raw escape sequences bindings like the examples above.
I already do some of this in Vim with `map`, and it just work great.

Do you think that this feature could be added?

Thanks!

Disclamer: this is not related to colorschemes issues...

**Comment by nicm** [comment]
^[[1;2C is an xterm style cursor key (C-Left) and tmux should understand
it without any changes. If you turn on xterm-keys, it will generate it
as well.

You can add custom key bindings by using terminal-overrides to assign
them to a key that you don't used, like:

set -ag terminal-overrides ',*:kf60=\033[1;2D'

Then bind M-F12 in tmux (F60 is M-F12, F59 M-F11, etc) to whatever you
want it to do.

**Comment by agilmor** [comment]
Hi!

I don't know way, but in my case C-Left/Right is `^[[1;5D` and `^[[1;5C`...
Anyway, your idea looks really promising to me!
I've tryied the `terminal-overrides` plus the extra binding for M-F11 and M-F12, but it didn't worked...?
The binding are working fine, the overrides is not.
The `xterm-keys` has been always `on`, and I'm using `screen-256color` as default term.

I've been testing with the `terminal-overrides` and it seems that doesn't work with other simpler sequences...?
How can I test if terminal-overrides is really working in my setup?

Now I'm using the tmux 2.3 version of Mobaxterm 9.4.

**Comment by nicm** [comment]
Sorry, 5D is C-Left, 2D is S-Left. In any case, tmux will recognise them
already and you do not need to do anything else. It will only SEND them
to the application inside if you turn xterm-keys on.

Or you can change what it sends by binding them to send-keys.

If you want to bind some other sequence, show me exactly what you are
adding to terminal-overrides and what you are binding the key to in
tmux.

**Comment by agilmor** [comment]
Hi,

My normal bindings that just work on Linux are:
```
# navigation
bind -n M-Up      select-pane -U
bind -n M-Down    select-pane -D
bind -n M-Left    select-pane -L
bind -n M-Right   select-pane -R
bind -n M-S-Left  prev
bind -n M-S-Right next
```

The first four are working fine, but last two are not working/detected on Mobaxterm.
If I use Ctrl-V to see the escape secuence outside and inside tmux, they are in both cases:
```
# M-Left:    ^[[1;3D]]
# M-Right:   ^[[1;3C]]
# M-Up:      ^[[1;3A]]
# M-Down:    ^[[1;3B]]
# M-S-Left:  ^[[1;2D]]
# M-S-Right: ^[[1;2C]]
```

So, I just want this:
```
bind -n M-S-Left  prev
bind -n M-S-Right next
```
But some reason are not working...
So, I was wondering how to force them working by something like:
```
bind -n ^[[1;2D]]  prev
bind -n ^[[1;2C]] next
```

Thanks a lot for your support!

**Comment by nicm** [comment]
2D is not M-S-Left (that would be 4D), I am guessing the terminal
incorrectly sends 2D for both M-S-Left and S-Left.

Does it work if you try binding S-Left as well as M-S-Left?

**Comment by agilmor** [comment]
You are right!
```
# S-Left: ^[[1;2D
# S-Right: ^[[1;2C
```

If I change my bindings to S-Left/Right, then when I press S-Left/Right, or M-S-Left/Right, it works.
So, it seems that Mobaxterm is not sending M-S-Arrows properly, but just S-Arrows.
And then, nothing can be done from the tmux side... right?

Ok, I will report it to Mobaxterm!

Thanks a lot!

**Comment by nicm** [comment]
Note that since these are keys which tmux is already aware of, you do
not need to use a key like F60, you can just change the sequence for
M-S-Left. The modified cursor keys are in terminfo as kUPX, kDNX, kLFTX
and kRITX where X is one of:

2 Shift
3 Alt
4 Shift + Alt
5 Ctrl
6 Shift + Ctrl
7 Alt + Ctrl
8 Shift + Alt + Ctrl
 
So you can change them with terminal-overrides. Something like this
should fix MobaXTerm, but because it matches all TERMs (the "*") it will
almost certainly break the other terminals you use:

set -ag terminal-overrides ',*:kLFT2@:kLFT4=\e[1;2D:kRIT2@:kRIT4=\e[1;2C'

So you would need to make sure that you use a unique TERM in MobaXTerm
and then set a terminal-override just for that.

If I was you I would bind S-Left and S-Right instead, that should work.

**Comment by nicm** [comment]
It would be a good idea to report it to MobaXTerm authors, if they are going to follow this scheme it would be wise to match xterm and xterm uses 4 for Meta+Shift and 2 for just Shift. Particularly if they recommend TERM=xterm (do they?) because that is what it contains:

$ TERM=xterm tput kLFT4|cat -v
^[[1;4D

**Comment by agilmor** [comment]
> If I was you I would bind S-Left and S-Right instead, that should work.

I know...
But I use S-Arrows a lot inside apps in tmux (e.g. Vim).
In deed, I use M-* for **all** tmux bindings, and **only** for tmux bindings (it's my mnemotechnic rule).

> set -ag terminal-overrides ',*:kLFT2@:kLFT4=\e[1;2D:kRIT2@:kRIT4=\e[1;2C'

If I'm not worng, if Mobaxterm is sending the same sequence from M-S-Arrows than S-Arrows, tmux (or any app in that teminal emulator) won't be able to distingiush between them, right?
I need to distinguish them, so I need to report to Mobaxterm and try another alternave in the meanwhile like using the Prefix+S-Arrows, that is also ok with my mnemothechnic rules and ok for non-mobaxterm sessions! ;-)

Thanks a lot!

**Comment by agilmor** [comment]
By the way!
I've tried the `set -ag terminal-overrides ',*:kLFT2@:kLFT4=\e[1;2D:kRIT2@:kRIT4=\e[1;2C'``and it didn't work with my usual bindings... should it?

**Comment by nicm** [comment]
Yes because it sends the same for both, there is no way for any application to distinguish.

terminal-overrides should work (did you detach and reattach?) but I wouldn't but too much effort into it because it won't let you use both keys anyway, it will just replace S-Left with M-S-Left.

**Comment by agilmor** [comment]
> terminal-overrides should work (did you detach and reattach?)

In fact, just be sure, I'm doing always kill-session and starting tmux from scratch.

> it will just replace S-Left with M-S-Left.

It didn't work...
It looks like mobaxterm is not allowing the terminal-overrides?
Can I test terminal-overrides with a simpler case to see if it is working?

> but I wouldn't but too much effort into it because it won't let you use both keys anyway,

Agree!
Thanks!

**Comment by nicm** [comment]
You can run tmux -vvvvv and show me the server log if you want with the terminal-overrides set.

**Comment by agilmor** [comment]
I've just added 4 -vvvv, with five I have 40MB of log! ;-)
[tmux-server-4404.txt](https://github.com/tmux/tmux/files/785887/tmux-server-4404.txt)

I also tried with another combination of overrides... trying to be intuitive swapping 4s and 2s...
[tmux-server-4500.txt](https://github.com/tmux/tmux/files/785885/tmux-server-4500.txt)

Thanks!

**Comment by nicm** [comment]
Are you doing \\e instead of \e?

**Comment by nicm** [comment]
Actually, probably my fault - try using " instead of ' so it expands \e.

Or use \E instead of \e, I think that will work.

**Comment by agilmor** [comment]
> try using " instead of ' so it expands \e.

It worked!
Thanks a lot!

**Comment by ecx86** [comment]
For anyone wondering, this is now possible in master using `user-keys`.
