### ISSUE TITLE
invalid option: set-remain-on-exit

### ISSUE THREAD

**Issue by OliverLeitner** [tmux/tmux#787]
im getting this when im trying to start my usual tmux scripts.

it doesnt work anymore...

heres a conf example for trying:

tmuxtest.conf
--------------------
set -g set-remain-on-exit on
--------------------

called by:
tmux -vvv -f tmuxtest.conf
----------------

read the changelog, it says nothing about that.

**Comment by nicm** [comment]
This option was removed, you can do the same by setting remain-on-exit in the session-created hook.

**Comment by kaibosh** [comment]
As I understand from above, as of tmux 2.4 is there no longer any way to set this option via tmux conf files. Correct?

Alternatively, would this work to set the remain-on-exit option for the specified tmux session?

`tmux -t SESSION-NAME set-hook set-remain-on-exit on`

**Comment by nicm** [comment]
No, you can set the hook from your config file to behave the same as
set-remain-on-exit:

set-hook -g session-created 'set remain-on-exit on'

If you just want remain-on-exit for one session, just set it for that
session with set-option as normal. For all sessions, set it globally.

**Comment by kaibosh** [comment]
Ak ok, then for clarity; within the tmux.conf file for <= v2.3 we use this:

`set -g set-remain-on-exit on`

From v2.4 onwards it changes to:

`set-hook -g session-created 'set remain-on-exit on'`

to maintain the same behavior as before.

**Comment by nicm** [comment]
Actually no, sorry, if you have:

set -g set-remain-on-exit on

Then you can just replace it with:

set -g remain-on-exit on

Because you set set-remain-on-exit globally it is the same as setting remain-on-exit globally.

If you genuinely want set-remain-on-exit for an individual session, you will need to set a session hook for that session to set remain-on-exit on window-linked:

set-hook -tmysession window-linked 'set remain-on-exit on'

**Comment by kaibosh** [comment]
OK got it, that's enough for me to start testing :)

Thanks for the explanation.

**Comment by GregHilston** [comment]
@nicm and @kaibosh, just wanted to thank you for taking the time to document how to do this. This was the top hit for me on google and saved me a lot of time <3
