### ISSUE TITLE
paste one line long string command to bottom of tmux  show truncated

### ISSUE THREAD

**Issue by weareno1** [tmux/tmux#789]
Darwin i386
tmux 2.1
screen
with default .tmux.conf && .zshrc && .bashrc

![image](https://cloud.githubusercontent.com/assets/18136108/23119192/2b0f691c-f792-11e6-8005-cd9f172dfd50.png)

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.
