### ISSUE TITLE
The index in the windows list from choose-window

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#79]
After executing the tmux command `choose-window`, the windows list will be shown and I can type a number/letter or use arrow keys to choose the right window, but there are two numbers for each window.

I already set the `base-inedx` (and `pane-base-index`) to 1 in my .tmux.conf file, so the second number in  the list is the right number for the right window, starting from 1 normally, but the first is an index number starting from 0, 0~9a~z, no matter what the order of the windows (the second numbers). 

I thought setting `base-inedex` to 1 will also set this number start from 1.
Is there a way that I can set the first the number start from 1 like setting the `base-index` to 1?

**Comment by ThomasAdam** [comment]
No. We toyed with this before, but it's not going to happen.

**Comment by nicm** [comment]
The first number is a key not an index.

**Comment by c02y** [comment]
How to make the key start from 1 then?

**Comment by nicm** [comment]
You can't

**Comment by c02y** [comment]
It's very confusing that the key is 0,1,2,3, but the index of the windows in the the list is 1,2,3,4, sometimes I typed the wrong number and switched into the wrong window.

**Comment by ThomasAdam** [comment]
It doesn't map correctly, what about displaying sessions as well?  That
throws the count out as well.

-- Thomas Adam

**Comment by c02y** [comment]
I personally only use one session almost all the time. I only care windows here, since positions of 0 and 1 in keyboard are two far away, and I already set `base-index` to 1, I think it is better the key value for windows in the list also starts from 1, and the 0123 to 1234 issue I mentioned earlier is the real problem for me.
