### ISSUE TITLE
C-e 'scroll-down' and C-y 'scroll-up' move cursor in buffer, unlike vi(m)

### ISSUE THREAD

**Issue by echristopherson** [tmux/tmux#791]
Using 55e76ed, on OS X 10.11.6, in default config, in iTerm 2 3.0.14.

The behavior of C-e ('scroll-down') and C-y ('scroll-up') vi-mode bindings in copy mode don't act like they do in vi or Vim. In those editors, those keystrokes cause the position of the cursor to stay the same relative to the buffer, even though it usually moves relative to the screen or window. In tmux, the cursor stays on the same line (and same column if it's not at the end of the line) relative to the pane, but relative to the buffer the position changes.

```
$ uname -sp && tmux -V
Darwin i386
tmux master
```
Outside tmux:
```
$ echo $TERM
xterm-256color
```

Inside tmux:
```
$ echo $TERM
screen-256color
```

**Comment by nicm** [comment]
I don't really know what you mean, and the behaviour seems to approximately match emacs, which is what is intended, so I think it is fine.

**Comment by echristopherson** [comment]
The correct vi behavior is for the cursor to stay at the same line in the buffer when C-e and C-y are invoked. In tmux, the cursor moves onto different lines when those are used. I would like to be able to position the cursor near where I want to select and copy, then scroll up or down so I can see more context, and then either make the copy or move my cursor to the actual thing I want to copy -- without being disoriented by the displacement of the cursor relative to the line in the buffer where it started out. With the behavior as it is now, every time I scroll the buffer like this, I have to manually move the cursor back to where I had it.

I acknowledge I don't know of an equivalent in Emacs.
