### ISSUE TITLE
Feature to allow configuration of copy-mode search wrapping

### ISSUE THREAD

**Issue by echristopherson** [tmux/tmux#792]
Using 55e76ed, on OS X 10.11.6, in default config, in iTerm 2 3.0.14.

Currently, the copy-mode search operations (forward and backward, incremental and not) wrap around the top and bottom of the buffer. It would be nice to have an option to make them stop at the edges of the buffer.

```
$ uname -sp && tmux -V
Darwin i386
tmux master
```
Outside tmux:
```
$ echo $TERM
xterm-256color
```

Inside tmux:
```
$ echo $TERM
screen-256color
```

**Comment by nicm** [comment]
Such an option already exists.

**Comment by nicm** [comment]
wrap-search

**Comment by echristopherson** [comment]
Thanks. :+1:
