### ISSUE TITLE
Can not start tmux on the cygwin with 'lost server'

### ISSUE THREAD

**Issue by aiplay** [tmux/tmux#794]
My cygwin is 64bit, how could I trace where is wrong?

**Comment by nicm** [comment]
tmux -vvvv logging, or try strace?

**Comment by aiplay** [comment]
1. tmux -vvvv         --------------  also show 'lost server'
2. tmux -vvvv logging ---------------- unknown command: logging

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by aiplay** [comment]
I found a file named 'tmux-client-5572.log', and here is the log : 

1487815146.018784 client started (5572): socket /tmp/tmux-1076726/default, protocol 8
1487815146.018784 on CYGWIN_NT-6.1 2.7.0(0.306/5/3) 2017-02-12 13:18; libevent 2.0.22-stable (poll)
1487815146.018784 socket is /tmp/tmux-1076726/default
1487815146.018784 trying connect
1487815146.018784 connect failed: No such file or directory
1487815146.018784 lock file is /tmp/tmux-1076726/default.lock
1487815146.018784 flock succeeded
1487815146.018784 got lock (6)
1487815146.018784 trying connect
1487815146.018784 connect failed: No such file or directory
1487815146.050185 add peer 0x600057590: 7 (0x0)
1487815146.050185 sending message 100 to peer 0x600057590 (4 bytes)
1487815146.050185 sending message 101 to peer 0x600057590 (15 bytes)
1487815146.050185 sending message 102 to peer 0x600057590 (10 bytes)

**Comment by nicm** [comment]
You are not giving me enough information, please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

For example, what is the tmux version? What is in the tmux server log?

**Comment by aiplay** [comment]
Here is my environment version : 
CYGWIN_NT-6.1 unknown
tmux 2.3
xterm-256color
windows7

And when I run these commands below
    **_tmux -Ltest kill-server
    tmux -vvvv -Ltest -f/dev/null new_**
There is not any  tmux-server-\*.log file generated, only tmux-client-\*.log file.

**Comment by nicm** [comment]
What does:

strace -fostrace.out tmux new

Show in strace.out?

**Comment by aiplay** [comment]
$ strace -fostrace.out tmux new
strace.exe: error creating process tmux, (error 50)

**Comment by ResolverJay** [comment]
@aiplay I had a similar (the same?) issue. The issue was caused by `/tmp/tmux-12162` created by tmux without proper permissions, so I'm not able to access it when tmux starts (with a non-admin user).

I just resolved it by creating `tmux-12162` folder (change to whatever name for your version) under `cygwin/tmp`. This way you'll get proper permissions to the folder/directory. Try it and let me know if it works for you.

@nicm this sounds like a bug for creating tmux folder/directory under tmp without proper permissions when tmux is executed at the first time.

**Comment by nicm** [comment]
tmux creates the directory with the correct permissions on every other platform and the code is no different for Cygwin.

**Comment by ResolverJay** [comment]
Ya, just found that it looks like a cygwin issue - any folder created in cygwin by a non-admin user has some permission issue in Windows. Creating the folder in Windows beforehand can work around it, but it is really annoying to do it every time.

**Comment by aiplay** [comment]
@ResolverJay @nicm 
After I created a directory which named tmux-1076726 has been existed in the cygwin64/tmp,
And run 'tmux' , terminal prompt me "can't create socket: Permission denied"

**Comment by ResolverJay** [comment]
@aiplay did you mount `/tmp` with `noacl` by any chance? I had the same issue when I did that. When I set it back to `acl`, it worked again (with the tmux folder created in Windows).

If you don't want to mount `/tmp` with `acl`, try this command (I'm not sure why it works, but it works, at least for me)
```
tmux -S /tmp/tmux-12162/default
```

**Comment by aiplay** [comment]
@ResolverJay Sorry， I did'nt mount /tmp with noacl, and tmux -S /tmp/my-tmux-version/default wasn't worked for me.

**Comment by huffstler** [comment]
I'd like to thank @ResolverJay for [this](https://github.com/tmux/tmux/issues/794#issuecomment-305236569) comment which helped me out. 

I'm using tmux from cygwin on windows. This 'lost server' issue happened to me after I killed the tmux server manually. To fix it, I deleted the directory located at /tmp/tmux-{version}, restarted cygwin and then ran tmux. Started up without a problem.
