### ISSUE TITLE
reliable pane_current_path using tmux env var

### ISSUE THREAD

**Issue by timotheecour** [tmux/tmux#799]
I'd like to have a more reliable `bind % split-window -h -c "#{pane_current_path}"` which is unreliable when a command changes PWD (cf https://github.com/tmux/tmux/issues/33)

* The following works but could it be made simpler?
(adapted from http://unix.stackexchange.com/a/104278/211423)
* what's a good way to avoid code duplication when this pattern is used in `bind-key % ` `bind-key "\""` etc?

~/.zshrc:
```
# executed before the prompt is shown(http://zsh.sourceforge.net/Doc/Release/Functions.html)
precmd() {
  if [ -n "$TMUX" ]; then
    tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD"
  fi
}
```

~/.tmux.conf:
```
# instead of: bind % split-window -h -c "#{pane_current_path}"
bind-key % run-shell 'tmux split-window -h "cd \"$(tmux show-environment $(echo "TMUXPWD_#D" | tr -d %) | sed -e "s/^.*=//")\"; exec $SHELL"'
```

Related:
* https://github.com/tmux/tmux/issues/313 use logical path for new pane #313
* https://github.com/tmux/tmux/issues/286 Can we have pre-expanded # in #(my-shell-command "#{pane_thing}") ? #286
* https://github.com/tmux/tmux/issues/188 split pane switch to pane_current_path #188
* https://github.com/tmux/tmux/issues/33 pane_current_path doesn't agree with pane's PWD #33

**Comment by nicm** [comment]
I don't really know what you're asking here. If it works, it works. There are no macros or similar in .tmux.conf so if you want to avoid copying the same command around, you'll need to set up the key bindings from a shell script.

**Comment by hanxi** [comment]
Thanks @timotheecour 
It works for symbolic link.

~/.tmux.conf:
```tmux
bind c run-shell 'tmux new-window "cd \"$(tmux show-environment $(echo "TMUXPWD_#D" | tr -d %) | sed -e "s/^.*=//")\"; exec $SHELL"'
bind '"' run-shell 'tmux split-window -v "cd \"$(tmux show-environment $(echo "TMUXPWD_#D" | tr -d %) | sed -e "s/^.*=//")\"; exec $SHELL"'
bind '%' run-shell 'tmux split-window -h "cd \"$(tmux show-environment $(echo "TMUXPWD_#D" | tr -d %) | sed -e "s/^.*=//")\"; exec $SHELL"'
```
~/.bashrc:
```bash
# set pwd for tmux
function my_cd() {
    \cd $1
    $([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")
}
alias cd=my_cd
```
