### ISSUE TITLE
Problem with numbers in window titles

### ISSUE THREAD

**Issue by notfoss** [tmux/tmux#8]
If a window title begins with a number and no window with that number exists, if we use prefix-number, we are taken to the window with that number in the title.

Example:

Say 3 windows exist:

0:win1
1:win2
2:7zero

Now, if I press prefix-7, I am taken to window 2 instead of getting the standard "Window not found" message.

**Comment by nicm** [comment]
That's how it works, if there is no exact match a prefix matches wins. An exact-match-only flag has been on the list for a while, maybe it's time...

**Comment by nicm** [comment]
Try this please: http://git.io/vIvNF

Note that this will not fix the case if window 2 was called exactly "7" but TBH I don't think that's a big issue (or your original problem). If you had a real window 7 it would always win anyway. There are other cases with prefix matches that are more of a problem though, so this is probably worth having.

**Comment by notfoss** [comment]
@ nicm

Thanks, the patch works as intended. Funny enough, I never encountered this behaviour even after years of tmux use :P

**Comment by nicm** [comment]
I have applied this but tweaked it slightly so that it also applies to the fnmatch check (so "=foo*" will match exactly "foo*" only, not "foo", not "foobar", not "foo*bar") and other special charters ("=+1" is "+1" not the next window index).

Thanks!
