### ISSUE TITLE
Feature request: Find as you type + numbers only for choose-tree (-u)

### ISSUE THREAD

**Issue by jotrk** [tmux/tmux#80]
I'm using tmux extensively to separate projects, topics, etc.
Currently my tmux server instance has 15 sessions, with a several windows for each.
When I call `choose-tree -u` the list exceeds `Z` (capital z) and gives the windows numbers again (`55`, `56`, etc.). However, when I hit `5` tmux will show me the window labeled with `5`, instead of waiting for another number or for me to confirm my choice (e.g. by hitting `Enter`).

Hence, I'd wish for two features (at least for the `choose-tree -u` mode):

```
1) Sequentially number all sessions and windows when expanded
   - Allow typing any number and either switch to that session/pane
       IF the number is completely matched
       OR the user confirms, e.g. hits `Enter`
   - As a bonus, it would be nice to expand the tree to panes as well.

2) Allow find as you type
   - Typing an arbitrary string should narrow the tree down to any
     session or window which is a {pre,suf,in}fix match
   - The new list is numbered again, with adapted numbers
```

Bot features are heavily inspired of [vimperator](http://www.vimperator.org/)'s way for selecting links.
Personally, I find this very user friendly. It'd be nice if tmux offered
a similar experience.

**Comment by ThomasAdam** [comment]
So I implemented something like this a while ago, and it got removed because it was inflexible past 26 items or so.

Your suggestion is OK, although we're not going to do this.  There are plans to make choose-* modes more streamline, and this just doesn't fit in with those ideas.

**Comment by jotrk** [comment]
Hm, I can't agree on the inflexibility, because it works very well with vimperator on pages with hundreds of links.

What do you mean by streamline?

Would it be conceivable to have a feature like this with a new command, like `choose-find`?

**Comment by ThomasAdam** [comment]
We definitely don't need a choose-find, no.

**Comment by jotrk** [comment]
So there's basically no way to get this feature, even if I would implement it?

**Comment by nicm** [comment]
If you implement it I will look at it and it will most likely go in if it ends up in the right shape. Modes are likely to change radically but there is a low probability it will be particularly soon.

-------- Original message --------

**Comment by nicm** [comment]
Oh id say keep the 0-9a-z,  I like that. But narrowing the tree as you type is a nice idea, I think probably you'll need to start it with a key binding (C-s maybe?) so it doesn't interfere with the current press-a-key-to-go
