### ISSUE TITLE
incorrect display of utf8 text.

### ISSUE THREAD

**Issue by MadMaverick9** [tmux/tmux#803]
I have attached the test file and screen shots to show what happens. I do hope github does not mess with it.
```
bash $ file /tmp/test.txt 
/tmp/test.txt: UTF-8 Unicode text
```
![tmux-01](https://cloud.githubusercontent.com/assets/14071022/23575938/b21db6bc-00c9-11e7-8600-75d064a7f712.png)
![tmux-02](https://cloud.githubusercontent.com/assets/14071022/23575940/bca1f8fa-00c9-11e7-9460-d95a186ec223.png)
[test.txt](https://github.com/tmux/tmux/files/818397/test.txt)

**Comment by MadMaverick9** [comment]
```
bash $ wget -q -O - "https://github.com/tmux/tmux/files/818397/test.txt" | diff - /tmp/test.txt 
bash $ 
```

**Comment by MadMaverick9** [comment]
```
bash $ git archive --format tar f5c5847788c45dd700ccf5f18cf46ceb6d7042b3 | ( cd /tmp/tmux-testing/ ; tar xf - )
```
It works correct with this commit.

**Comment by nicm** [comment]
Logs? Platform? Terminal?

Does it work if you build with utf8proc?



On 4 Mar 2017 4:15 am, "MadMaverick9" <notifications@github.com> wrote:

bash $ git archive --format tar
f5c5847788c45dd700ccf5f18cf46ceb6d7042b3 | ( cd /tmp/tmux-testing/ ;
tar xf - )

It works correct with this commit.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/803#issuecomment-284125888>, or mute
the thread

**Comment by krader1961** [comment]
Are you saying it doesn't work with the subsequent commit, 43e8f60bc6e962fe6e9b432ac650d0d7a7f0c86c? If it does it would help a lot if you actually bisect to the commit which causes the problem.

**Comment by MadMaverick9** [comment]
I narrowed it down to commit https://github.com/tmux/tmux/commit/3fd34e70e531314558a182b85411c21cba4eb0d1.

https://github.com/tmux/tmux/commit/50f25a8f0539caa217b34ba12f4bd4e73043165a - works.
https://github.com/tmux/tmux/commit/446177a8326d6d29591c1e42ec44d0f92e39c466 - does not work.

```
checking utf8proc.h usability... no
checking utf8proc.h presence... no
checking for utf8proc.h... no
configure: error: "utf8proc not found"
```
```
bash $ uname -sp
Linux Intel(R) Pentium(R) Dual  CPU  E2160  @ 1.80GHz
```
No tmux configuration. rxvt-unicode:
```
bash $ echo $TERM 
rxvt-unicode-256color
```
Inside tmux as usual:
```
bash $ echo $TERM 
screen
```
Now I will build git master again and produce log files and see if anything's in there.

**Comment by MadMaverick9** [comment]
Is this what you're looking for:
```
bash $ grep -i combine tmux-server-10843.log 
1488604328.648196 screen_write_combine: \340\271\207 onto \340\270\236 at 26,3
1488604328.648358 screen_write_combine: \340\270\261 onto \340\270\240 at 27,3
1488604328.648500 screen_write_combine: \340\270\265 onto \340\270\224 at 28,3
1488604328.649105 screen_write_combine: \340\271\207 onto \340\270\236 at 26,4
1488604328.649248 screen_write_combine: \340\270\261 onto \340\270\240 at 27,4
1488604328.649400 screen_write_combine: \340\270\265 onto \340\270\224 at 28,4
bash $ 
```
[tmux-server-10843.txt](https://github.com/tmux/tmux/files/818427/tmux-server-10843.txt)

**Comment by nicm** [comment]
Your libc appears to be giving tmux the same widths as mine, so I suspect either your font, terminal or Unicode itself is at fault.

The zero width characters appear to be:

U+0E31 U+0E35 U+0E47

These all look likely to be combining marks to me, but whether or not that is accurate I don't know.

You should try utf8proc in case these have changed in Unicode 9.

**Comment by nicm** [comment]
These do not appear to actually be combining characters, so I guess that the width 0 from libc is actually wrong for these characters.

**Comment by nicm** [comment]
Hmm actually maybe tmux is doing the wrong thing, I'll look again when I get home on Monday.

**Comment by MadMaverick9** [comment]
These are diacritics that are not displayed correctly.
And this test file displays correctly in plain rxvt-unicode.
It's only inside tmux that the diacritics are not displayed correctly.

Ok - Thank you. Have a good weekend.

**Comment by MadMaverick9** [comment]
The file [./tools/UTF-8-demo.txt](https://github.com/tmux/tmux/blob/master/tools/UTF-8-demo.txt) does not display correctly also (`grep -B 1 -A 18 Thai ./tools/UTF-8-demo.txt`). So you don't even need my test file.

> Thai (UCS Level 2):
> ...
> (The above is a two-column text. If combining characters are handled correctly, the lines of the second column should be aligned with the | character above.)

They don't align.

And - Slackware does not come with utf8proc, so I just manually built it & copied the two files "`/usr/include/utf8proc.h`" and "`/usr/lib/libutf8proc.a`" and built tmux with "`--enable-utf8proc`".
But it did not make a difference.

**Comment by DmitryHetman** [comment]
In my opinion UTF-8 shold be disabled by default. I can't open tmux, it requires utf-8 locale.

**Comment by nicm** [comment]
I've found the problem: when tmux combines the zero width character onto the existing character it needs to redraw the result (this is a change from previous versions where it would redraw the whole line). It was moving the cursor back to redraw the new character in the old position, but was not restoring it ready for the next character. Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/819837/x.diff.txt)

**Comment by MadMaverick9** [comment]
That worked. Thanks for your quick reply and fix.

Please close this issue at your discretion.

![tmux-03](https://cloud.githubusercontent.com/assets/14071022/23597661/4da6f44c-0267-11e7-9fe7-da39e8070520.png)

**Comment by nicm** [comment]
Applied to OpenBSD, will be GitHub shortly. Thanks!
