### ISSUE TITLE
say command is not working in tmux

### ISSUE THREAD

**Issue by blakejia** [tmux/tmux#804]
my platform : osx 10.12.3

When I input in the tmux say hello when nothing happened.
but this command can excute outside of tmux.

**Comment by krader1961** [comment]
You need to use [reattach-to-user-namespace](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard). I do this for the top-level shell I run within each tmux window so I don't have to use it for each command (e.g., `ssh`, and `pbcopy`) that needs it:

```
# The reattach-to-user-namespace is necessary to be able to contact ssh-agent
# via the SSH_AUTH_SOCK env var. This is also necessary to make pasteboard
# (clipboard) interaction work for programs run within the tmux server.
set-option -g default-command "exec reattach-to-user-namespace -l /usr/local/bin/fish"
```

This is asked so frequently we should probably add it to the FAQ. I'll try to find a few minutes later today to do so.

**Comment by krader1961** [comment]
So I see this is already documented in the FAQ but doesn't explicitly mention `say` or `ssh`. I'll do a trivial PR to clarify that those commands also need the `reattach-to-user-namespace` workaround.

It would be nice if there was a simple way to issue a one time warning when the user ran `tmux` on macOS and their *~/.tmux.conf* doesn't have `reattach-to-user-namespace` in the default command but I don't see any way to do so.

**Comment by blakejia** [comment]
thk！
