### ISSUE TITLE
Minor annoyance with copy mode and multibyte characters

### ISSUE THREAD

**Issue by rr-** [tmux/tmux#805]
<dl>
<dt>tmux version</dt><dd>master and 2.3</dd>
<dt>OS</dt><dd>Linux Arch</dd>
<dt>Terminal</dt><dd>urxvt 9.22</dd>
<dt>Configuration file</dt><dd>not needed</dd>
<dt><code>$TERM</code></dt><dd><code>rxvt-unicode-256color</code> outside, <code>screen</code> inside</dd>
</dl>

When I'm in copy mode and I `begin-selection` and try to move over characters such as 漢字, it takes two key presses to move over each character - rather than moving over characters, it moves over bytes.

Same thing happens with `--enable-utf8proc`.

**Comment by nicm** [comment]
Yes... try this please: [tmux-wide-cursor.diff.txt](https://github.com/tmux/tmux/files/828109/tmux-wide-cursor.diff.txt)

**Comment by rr-** [comment]
Works like a charm :)

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub soon. Thanks!
