### ISSUE TITLE
reverse search in bash eats last symbols

### ISSUE THREAD

**Issue by andrey-starodubtsev** [tmux/tmux#806]
tmux: 48a3dba
OS: Ubuntu 16.04.2 LTS
terminal: gnome-terminal
TERM outside tmux: xterm-256color
TERM inside tmux: tmux-256color
$BASH_VERSION: 4.3.46(1)-release

When I try to do reverse search using `Ctrl+R` in bash, last symbols of current match are deleted while symbols of pattern are entered. The problem was introduced to master in 4b112c1.

![tmux-reverse-search-in-bash](https://cloud.githubusercontent.com/assets/7666511/23586350/484b074a-01a4-11e7-9980-c13b1b2f09f3.gif)

**Comment by nicm** [comment]
Show me the server log from reproducing with latest master please.

**Comment by andrey-starodubtsev** [comment]
[tmux-server-5903.log.gz](https://github.com/tmux/tmux/files/825317/tmux-server-5903.log.gz)

Found another way to reproduce it:

- create vertical split
- enter `echo abc` and `Enter` in right pane
- select previous command using `Up` or `Ctrl+P`
- jump to begin of the line with `Home` or `Ctrl+A`
- start enter symbols
- end of the command vanishes character by character

**Comment by andrey-starodubtsev** [comment]
just pulled latest changes, it's been fixed in 5d3296c
