### ISSUE TITLE
Cannot bind Ctrl+Enter

### ISSUE THREAD

**Issue by Bergfried** [tmux/tmux#81]
I have this line in my `~/.tmux.conf`:

    bind -n C-Enter new-window

However, it does not seem to work, neither in guake nor in urxvt nor in tty. Neither `-n` nor the `xterm-keys` seem to have an influence. Config lines like

    bind -n C-PageDown next-window

do work, however.

Using tmux 2.0.

**Comment by nicm** [comment]
Most terminals don't distinguish between Enter and C-Enter.

**Comment by Bergfried** [comment]
I see. Thank you very much for the explanation. Pointing this out in the man page (for Enter or any other problematic key or key combination you are aware of) might also help other users as well.

**Comment by nicm** [comment]
I don't think we should try to document the quirks of different terminals in the man page, it is the tmux manual and should stay focused on tmux. But an FAQ entry would be fine if you'd like to write one - it could also mention the fact that, for example, the pairs of C-Space/C-@ and Enter/C-m are the same.
