### ISSUE TITLE
Multiple clients of same session mirror actions

### ISSUE THREAD

**Issue by mwgant** [tmux/tmux#814]
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.2
xterm-256color

I have a question about connecting to the same session from two or more clients.

I'm a new user of tmux and have been using screen for many years. When I use screen, I often have multiple clients attached to the same session and each one operates independently. That is, if I'm in window 1 of client A, I can be in window 2 or any other window from client B. 

This is not the case with tmux. In tmux, when I select window 1 in client A, client B will also switch to window 1. 

I know nothing about the architecture of tmux vs. screen but was wondering if it's possible to change this behavior to be like screen. 

If you need more details I am happy to provide them.

Thank you for your time.

-Mike

**Comment by nicm** [comment]
You need to use session groups.

**Comment by mwgant** [comment]
Thanks, I somehow missed that in all my searches.

I still have questions about groups but will do some more reading first

-mike
