### ISSUE TITLE
Cursor ends up at wrong position in bash prompt when it wraps

### ISSUE THREAD

**Issue by dmalyuta** [tmux/tmux#817]
- Platform: Ubuntu 14.04
- Problem: after resizing a pane, the cursor in tmux ends up in the wrong position when the pane is resized. Before resize:
![one](http://i.imgur.com/f6yQBEV.png)
After resize (decrease width), cursor is way outside the prompt now:
![image](https://cloud.githubusercontent.com/assets/12475811/23715709/5ed78cfa-03e2-11e7-82b2-a9b364179f9b.png)
After resize (increase width), cursor is inside the prompt now:
![image](https://cloud.githubusercontent.com/assets/12475811/23715731/74d87974-03e2-11e7-97f8-3a9878cb1abb.png)

- tmux config:
```
# look good
set-option -g default-terminal "screen-256color"

# remap prefix to Ctrl+x (Emacs style)
set -g prefix C-x
# bind 'C-x C-x' to type 'C-x'
bind C-x send-prefix
unbind C-b

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Ctrl-arrow
bind -n C-Left select-pane -L
bind -n C-Right select-pane -R
bind -n C-Up select-pane -U
bind -n C-Down select-pane -D

# Resize pane splits quicker
bind-key -n M-Up resize-pane -U 1
bind-key -n M-Down resize-pane -D 1
bind-key -n M-Left resize-pane -L 1
bind-key -n M-Right resize-pane -R 1

# don't rename windows automatically
set-option -g allow-rename off

# window resizing
set-window-option -g aggressive-resize

# navigate using Emacs keys
setw -g mode-keys emacs

# Enable mouse support (works in iTerm)
set-option -g -q mouse on
set-option -g set-clipboard off
# make mousewheel work when not in copy mode
bind-key -T root WheelUpPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
bind-key -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"
bind-key -t vi-copy WheelUpPane halfpage-up
bind-key -t vi-copy WheelDownPane halfpage-down

# Allows for faster key repetition
set -s escape-time 0

# Highlight active window in tab-bar at bottom in red
set-window-option -g window-status-current-bg red

# move current window left and right in the tab list, respectively.
bind '<' swap-window -t -1
bind '>' swap-window -t +1
```
- Terminal: terminator 0.98 (also happens in regular Ubuntu GNOME terminal 3.6.2), $TERM=screen-256color inside tmux and $TERM=xterm outside tmux

```
~ $ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.3
xterm
```

This error occurs also with `tmux -vvvv -Ltest -f/dev/null new`, tmux-server-*.log attached (renamed to .txt for github to upload it):
[tmux-server-8046.txt](https://github.com/tmux/tmux/files/828467/tmux-server-8046.txt)

**Comment by nicm** [comment]
Does this still happen with tmux built from Git master?

**Comment by dmalyuta** [comment]
Yes it does

**Comment by nicm** [comment]
I don't think this is a bug, the cursor has to stay on screen when you resize, tmux does a best effort to move it but only the shell actually knows where it wants it. If it cares, it is up to it to fix it when it is told about the resize. It is easy to get the cursor position in the wrong place when resizing xterm without tmux as well.

**Comment by dmalyuta** [comment]
A friend has the same issue with bash, but not with zsh - does zsh do cursor positioning?

**Comment by nicm** [comment]
For me, when I resize bash, the cursor is in the wrong place until I press a key, then bash seems to redraw the line and fix the cursor position.

zsh may redraws on SIGWINCH while bash waits for a key press, but that's just a guess.

**Comment by dmalyuta** [comment]
Well, is there a way to tell tmux to redraw the prompt/the pane/the window on resize? I'm seeing that the problem only occurs for wrapped prompts (when the pane width is too small/prompt is too long).

**Comment by nicm** [comment]
tmux always redraws the entire window on resize but it will redraw it after resizing what was already there. If the prompt needs to change for the new size it is up to bash to take care of that.

**Comment by dmalyuta** [comment]
Do you know of a way to implement this in bash? Or of pointers on how to do it?

**Comment by nicm** [comment]
No I don't know anything about bash.
