### ISSUE TITLE
interrupt(ctrl-c) not available while cat a large file

### ISSUE THREAD

**Issue by zhuaoyuan** [tmux/tmux#818]
ubuntu 14.04. tmux 2.3 from http://tmux.github.io/
My terminal cannot accept ctrl-c or ctrl-b during cat a large file.
the same as https://github.com/tmux/tmux/issues/468

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by zhuaoyuan** [comment]
Thanks, it works now.
