### ISSUE TITLE
"mode-mouse copy-mode" breaks non-copy-mode mouse actions

### ISSUE THREAD

**Issue by Bergfried** [tmux/tmux#82]
The man page says:

> If set to copy-mode, the mouse behaves as set to on, but cannot be used to enter copy mode.

While tmux certainly behaves as described, it feels like a bug to me because it breaks the normal mouse actions I am used to while not in copy mode, especially scrolling in man pages, vim, and selecting text for copying to Primary (X clipboard)). I think it would be more useful if `mode-mouse copy-mode` behaves like `mode-mouse off` when not in copy mode, and like `mode-mouse on` if in copy mode. This issue is probably related to #68. (Note that the "holding down Shift" workaround described there only works for selecting text, not for scrolling.)

Using tmux 2.0.

**Comment by nicm** [comment]
mode-mouse has been removed from 2.1 and you can bind the mouse to behave how you like so this is no longer relevant.

**Comment by iseth** [comment]
So there is no workaround?

**Comment by iseth** [comment]
Is there anyway to scroll up with the mouse in tmux without going into copy mode?
