### ISSUE TITLE
macOS 10.12.4 Beta (16E183b) Breaks GPG Keychain Signing in Tmux

### ISSUE THREAD

**Issue by martynchamberlin** [tmux/tmux#820]
OS: macOS 10.12.4 Beta (16E183b)

```
$ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.3
screen
```

I use pinentry-mac to provide the GPG passphrase for my signed commits. It was working fine on Beta 4 macOS 10.12.4 but it's not on Beta 5. Also it works fine _outside_ tmux. Just not in tmux. Right now, if I want to sign commits in Tmux, I have to remove this line from `~/.gnupg/gpg.conf`: 

```
no-tty
```

And then I have to manually provide the passphrase for every commit. 

Not sure if this is on tmux's end specifically or on pinentry-mac or if it's something that Apple will fix in a new beta build. Just reporting it here since it works fine in regular Terminal but not in Tmux. 

Thanks!

**Comment by krader1961** [comment]
Are you using [reattach-to-user-namespace](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard)? If not does using that command to launch the shell within tmux fix the issue?

**Comment by martynchamberlin** [comment]
It does. We're golden. That fixed it!

**Comment by holms** [comment]
I have same problem with Debian! GPG passphrase fails under tmux and I can't commit with a git.
