### ISSUE TITLE
tmux: unknown option -- 3

### ISSUE THREAD

**Issue by MrNsfocus** [tmux/tmux#821]
[root@OR2 ~]# tmux 
tmux: unknown option -- 3
usage: tmux [-2CluvV] [-c shell-command] [-f file] [-L socket-name]
            [-S socket-path] [command [flags]]
[root@OR2 ~]# cat .tmux.conf 
[root@OR2 ~]# 
[root@OR2 ~]#

**Comment by nicm** [comment]
You have an alias or something.
