### ISSUE TITLE
tmux split freezes on high text output while fullscreen works

### ISSUE THREAD

**Issue by Chris-Bee** [tmux/tmux#822]
Hello,
I'm encountering an issue where the whole tmux session freezes when there is high test output from a program in a split (see image). This issue does not happen when no splits are used. Also, sometimes reattaching to the session recovers the tmux session. Also, after stopping the program, tmux keeps the last line printed, "reset" the terminal or reloading zsh does not solve this. I would need to close the pane and open a new one

![image](https://cloud.githubusercontent.com/assets/12284463/23812534/c7be4f66-058f-11e7-8928-0a8a4d45b267.png)

Thanks in advance,
Chris

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by Chris-Bee** [comment]
Sorry for that:

System Info:
Linux x86_64
tmux 2.3
xterm
Tmux config:
set -g default-terminal "screen-256color"
set-option -g default-shell /bin/zsh
 source "/.powerline/powerline/bindings/tmux/powerline.conf"

```
1   set -g default-terminal "screen-256color"
  1 #set -g default-terminal "gnome-256color"
  2 
  3 set-option -g default-shell /bin/zsh
  4 # reload config
  5 bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."
  6 
  7 # remap prefix from 'C-b' to 'C-a'
  8 unbind C-b
  9 set-option -g prefix C-a
 10 bind-key C-a send-prefix
 11 
 12 set-option -g repeat-time 450 #500 is the default value
 13 
 14 # split panes using | and -
 15 bind | split-window -h -c "#{pane_current_path}"
 16 bind - split-window -v -c "#{pane_current_path}"
 17 bind c new-window -c "#{pane_current_path}"
 18 
 19 unbind '"'
 20 unbind %
 21 
 22 is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
 23 bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
 24 bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
 25 bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
 26 bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
 27 bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
 28 
 29 set-option -g allow-rename off
 30 # Toggle mouse
 31 bind m set -g mouse on \; display 'Mouse: ON'
 32 
 33 bind M set -g mouse off \; display-message 'Mouse: OFF'
 34 
 35 #run-shell "~/.powerline/scripts/powerline-daemon -q"
 36 source "~/.powerline/powerline/bindings/tmux/powerline.conf"

```

**Comment by nicm** [comment]
Does this still happen with a tmux built from Git master?

When you say freeze, what do you mean? Does it recover when the output
ends, or never? Does just that pane freeze, or tmux entirely (can you
still create new windows with C-a c)?

**Comment by Chris-Bee** [comment]
Yes it also happens with tmux build from master. Both scenarios happen, sometimes it never comes back and the pane keeps printing the output in this case, tmux freezes entirely and I can not create and switch panes. Sometimes detaching and attaching helps recovering.

It also happens that I can stop the program that produces the high output, then it only prints a few more lines and I have the control over tmux back.

**Comment by nicm** [comment]
If tmux recovers when the high output stops, or when you close the terminal and reattach to tmux, this is probably not a bug but just a reflection of the fact that there are interacting buffers (tmux, ssh if it is involved, and the terminal), which is an extremely difficult problem to solve without affecting normal output as well. Try without ssh if you are using it, and try using a faster terminal and see if it helps (xterm in particular is slow). However, at some point there will be too much output and you can't expect everything to necessarily keep up - you may have to wait until buffers drain.

If tmux never recovers when the high output stops or when you kill the terminal and reattach tmux from somewhere else, then it is a problem, please figure out the smallest file you can reproduce with, then please get some logs from tmux. Make sure you are not using ssh, and are running tmux from Git master.

**Comment by nicm** [comment]
If tmux appears to freeze but attaching it from another terminal is fine, what happens if you kill the tmux client process in the original terminal (but not the server process)? Does the terminal allow you to type normally or does it remain frozen?

**Comment by dmalyuta** [comment]
I get the same issue. My concern is not with freezing, but with how the output is printed (see OP's image) when the pane is resized. Originally, the output is a single line being updated over and over with the time. Let's say the number of characters in this line is X and initially the pane width is >X. Now, if I resize the pane to a width <X while the output is still getting printed, I get OP's behavior of that now the line gets printed over and over again in a giant spaghetti string, rather than being the single "updated" line that it is meant to be... any way to fix this?

>  try using a faster terminal and see if it helps (xterm in particular is slow)

What terminal do you suggest?

**Comment by nicm** [comment]
Does the same happen outside tmux?

**Comment by dmalyuta** [comment]
Actually yes, but here's the difference:

* Outside tmux, when I make the window again >X:

![image](https://cloud.githubusercontent.com/assets/12475811/23835511/d01d67cc-0725-11e7-9fe7-c31e4415430d.png)

* Inside tmux, when I make the pane width again >X:

![image](https://cloud.githubusercontent.com/assets/12475811/23835521/0195f74c-0726-11e7-8c8b-8af5dbb81f99.png)

Tmux creates a spaghetti string while terminator (TERM=xterm-256color) doesn't. Ideally this would not happen at all and only one line would always be printed and updated (how?) but anyhow for me the spaghetti string is more visually disturbing.

**Comment by nicm** [comment]
OK you need to make your own issue with some logs rather than hijacking this one.

**Comment by Chris-Bee** [comment]
@nicm thank you for your fast answer. SSH was not involved in this case. I will set up a small file to reproduce the error and test the points you mentioned. Is there a particular recommendation on which term works best with tmux?

**Comment by nicm** [comment]
They should all work, but if you are having performance problems I would
give rxvt-unicode a go and see if it improves - I am not necessarily
recommending you use it permanently (it has its own problems) but it
would point to the fact that the terminal performance is a factor.
