### ISSUE TITLE
Complains about missing powerline.conf

### ISSUE THREAD

**Issue by binarykitchen** [tmux/tmux#825]
Each time I SSH into my server, I am seeing this one error

![selection_001](https://cloud.githubusercontent.com/assets/177641/23831052/ee932266-077d-11e7-8371-a8df4a06ea06.png)

And then I am just seeing this plain theme where powerline and sorin theme are missing
![selection_003](https://cloud.githubusercontent.com/assets/177641/23831059/0fbe0ae6-077e-11e7-8258-69e18f51366a.png)

Any clues what this could be?

**Comment by nicm** [comment]
grep for powerline.conf in your tmux and shell profiles?
