### ISSUE TITLE
bind-key o kill-pane -a   not refreshing pane after other panes get killed

### ISSUE THREAD

**Issue by pmnoxx** [tmux/tmux#826]
I'm using latest tmux from master. 
Here is my .tmux.conf
``
bind-key o kill-pane -a  
``
First I do the following to get two vertical panes:
``
:split-window -h
``
At this point I have to panes open. After I press ctrl-b o. It kills one of the panes, but the ui doesn't redraw.

However, pressing ctrl-d works properly. It kills current pane and forces the second one to redraw.

Also, pressing ctrl-b and typing ":kill-pane -a" cases all other panes to get killed, and the current pane to redraw.

**Comment by nicm** [comment]
try this please

Index: cmd-kill-pane.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-kill-pane.c,v
retrieving revision 1.23
diff -u -p -r1.23 cmd-kill-pane.c
--- cmd-kill-pane.c	14 Jan 2017 18:53:08 -0000	1.23
+++ cmd-kill-pane.c	16 Mar 2017 08:44:22 -0000
@@ -56,6 +56,7 @@ cmd_kill_pane_exec(struct cmd *self, str
 			layout_close_pane(loopwp);
 			window_remove_pane(wl->window, loopwp);
 		}
+		server_redraw_window(wl->window);
 		return (CMD_RETURN_NORMAL);
 	}

**Comment by pmnoxx** [comment]
I tested this hotfix.  Now the refresh works properly. Thanks!

**Comment by nicm** [comment]
Applied now, thanks!
