### ISSUE TITLE
Add multi-key mapping

### ISSUE THREAD

**Issue by pmnoxx** [tmux/tmux#827]
Hi, currently tmux doesn't support multiple key binding. It would be extremely useful to have support for it. 
   
I wanted to bind keys for useful commands, like in vim, that i use really often. For example I would add those mappings:
``
bind-key gp command-prompt "cd $GIT_HOME; git pull"
``
``
bind-key gd command-prompt "cd $GIT_HOME; git diff"
``
``
bind-key gs command-prompt "cd $GIT_HOME; git status"
``
``
bind-key gc command-prompt "cd $GIT_HOME; git commit -e"
``
``
bind-key hp command-prompt "cd $HG_HOME; hg pull -u"
``
``
bind-key hd command-prompt "cd $HG_HOME; hg diff"
``
``
bind-key hs command-prompt "cd $HG_HOME; hg status"
``
``
bind-key hc command-prompt "cd $HG_HOME; hg commit -e"
``
``
bind-key ww new-window
``
``
bind-key ws new-window -h
``
``
bind-key wc kill-pane
``
``
bind-key wo kill-pane -a
``
``
...
`` and a few others.
I saw a few posts from a few different, asking about multi-key support. For example http://unix.stackexchange.com/questions/324527/tmux-multi-key-key-binding-like-in-screen-possible http://stackoverflow.com/questions/25294283/bindings-with-key-sequences etc.

**Comment by nicm** [comment]
It does support it, you need to use multiple key tables and
switch-client -T..

**Comment by pmnoxx** [comment]
Thanks, that works perfectly.

**Comment by MoJoeDev911** [comment]
> It does support it, you need to use multiple key tables and switch-client -T..

How to do that? Thanks
