### ISSUE TITLE
Multiline statusline

### ISSUE THREAD

**Issue by jbarbero** [tmux/tmux#828]
Just adding my support to requesting a multiline statusline feature. This is the feature that keeps me from switching from GNU screen. In screen, I use hardstatus to display information about my system, time and date, etc, and caption to display just the list of windows. Without this distinction, my tmux statusline is too crowded. I would love to switch, instead of maintaining my own set of patches (labels, vertical splits, utf 8) against screen, which the maintainers are resistant against including.

Would love to take a stab at it and submit a PR at some point, but for now I'm just sticking with screen and I wanted to voice my support for this feature. Thank you for listening!

**Comment by nicm** [comment]
OK.

**Comment by nicm** [comment]
This was the last diff but nobody seemed particularly interested in taking it forward: [tmux-two-status.diff.txt](https://github.com/tmux/tmux/files/849180/tmux-two-status.diff.txt)
