### ISSUE TITLE
Prefix+mouse action should enter copy mode on "mode-mouse copy-mode"

### ISSUE THREAD

**Issue by Bergfried** [tmux/tmux#83]
If `mode-mouse copy-mode` is set, it would be nice if, after entering the prefix (Ctrl+b by default), using the mouse (e.g. scrolling or attempting to select text *within* a pane) makes tmux enter copy mode automatically.

**Comment by nicm** [comment]
mode-mouse has gone in git/2.1.

**Comment by Bergfried** [comment]
I see. I played around a bit with the recent master but I couldn't configure my `.tmux.conf` to make it work as intended. The closest config I could get looks like this:

    bind WheelUpPane copy-mode -t {mouse}

However, for this to work, `set mouse on` must have been set beforehand, but that is exactly what I am trying to avoid. It would be nice to see something like

    set mouse "mode=copy || key-table=prefix"

or

    set -T prefix mouse on
    set -T root mouse off
    set --mode copy mouse on
    set --mode default mouse off

meaning that mouse mode is enabled if and only if *the currently active pane* is in copy mode *or* the currently active key table is the `prefix` key table. (The latter is especially important as it allows to enter or leave mouse mode automatically, depending on the current key table. Without such an option, the `bind` example above would work only if the `mouse` option is already set to `on`.)

I tried to use `switch-client` to emulate the described behavior but I did not manage to do so either:

    bind -Ttable2 Enter set mouse off ; switch-client -Troot ; new-window
    bind -Troot C-b set mouse on ; switch-client -Ttable2

With this, pressing `Ctrl+b` enables mouse support and the prefix key (`C-b` in this example) does not work anymore at all. Also, pressing `Ctrl+b Enter` does not create a new window and does not turn `mouse off`.

**Comment by nicm** [comment]
This is not going to happen, tmux needs to take over the mouse to make any of the mouse key bindings work. I think it is overcomplicated to make it try and figure out whether you only have mouse key bindings in copy mode or globally. Most terminals let you bypass application mouse mode by holding Shift.

**Comment by nicm** [comment]
Your key bindings probably need to use \; but I expect that even if you get the key bindings right, you will find that tmux will not be able to turn on mouse mode quickly enough between C-b and the mouse event for it to work reliably.
