### ISSUE TITLE
resize-pane won't resize to very small values with "tmux -f somefile.conf"

### ISSUE THREAD

**Issue by CleanCut** [tmux/tmux#833]
Tmux 2.3
macOS Sierra 10.12.3
Terminal.app and iTerm2 3.0.15

```shell
# From inside tmux
$ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.3
screen-256color
```
Problem:

Usingly only a custom conf file like this that doesn't reference any other config:

```tmux
new-session -s DB -n monitoring -d
split-window -h -t DB
resize-pane -t 0 -x 10
```

I cannot get my left pane to resize to 10 columns using the custom conf file.  It *is* smaller than 50%, but it's still about 54 of my 183 columns.

Resizing to 10 columns works fine interactively, or with `PREFIX : resize-pane -t 0 -x 10`

I would guess that this has something to do with the config running before tmux has obtained the terminal size.  What can I do to get the panes sized correctly via configuration?

[logs.zip](https://github.com/tmux/tmux/files/858976/logs.zip)

<img width="837" alt="screen shot 2017-03-21 at 10 49 49 am" src="https://cloud.githubusercontent.com/assets/5838512/24159219/3234c98c-0e24-11e7-9d4a-50fbcfdb92c1.png">

**Comment by nicm** [comment]
Create the session with -x and -y.

**Comment by CleanCut** [comment]
@nicm Is there a wy that I can specify that -x and -y be the full width of my terminal from inside the config file?

From outside the config file I can use the environment variables COLUMNS and LINES.

**Comment by nicm** [comment]
If you export LINES and COLUMNS you can use them in .tmux.conf.

**Comment by CleanCut** [comment]
Great!  I didn't realize you could do that.  Thank you!
