### ISSUE TITLE
Add counter of founded results in search mode

### ISSUE THREAD

**Issue by id777** [tmux/tmux#835]
It will be handy to have counter of search found results. And position of matched result too.
For example how it shows in sublime text ([see screenshot](https://hsto.org/files/b9c/fe5/733/b9cfe57336ff40f5b5ad66e0726432c9.png))

**Comment by nicm** [comment]
Try this, which shows the number of results: [x.diff.txt](https://github.com/tmux/tmux/files/864089/x.diff.txt)

It might be possible to show the current result by checking the cursor position, will have a look later.

**Comment by nicm** [comment]
Try this instead please: [y.diff.txt](https://github.com/tmux/tmux/files/864675/y.diff.txt)

**Comment by id777** [comment]
@nicm 
Thanks a lot again, It works perfectly! [Screenshot](https://hsto.org/files/53d/fe0/faf/53dfe0faf00e4b94b413e8c7485c63b2.png)

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
