### ISSUE TITLE
Resizing panes with "right prompt" in fish

### ISSUE THREAD

**Issue by NickeZ** [tmux/tmux#837]
# Description
I have a "right prompt" in fish and it renders incorrectly when the pane is resized. This doesn't happen if I use fish outside of tmux.

Here is a screenshot after resizing the window a couple of times:

![fish-in-tmux-screenshot](https://cloud.githubusercontent.com/assets/492753/24294914/c75e7d84-1098-11e7-94fc-4ddd11f0ac32.png)

Here are logs from running without config, launching fish, splitting in two panes, enable mouse support, resize pane a couple of times and then exiting:
[tmux-logs.zip](https://github.com/tmux/tmux/files/867868/tmux-logs.zip)

# System info
**tmux -V**: tmux master 2d84ee900131214ee463d89abc051586b3a63afb
**uname -vrpi**: 4.8.0-41-generic #44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017 x86_64 x86_64
**lsb_release -d**: Description:    Ubuntu 16.04.2 LTS
**$TERM (outside)**: xterm-256color
**$TERM (inside)**: screen-256color

```fish
#fish git prompt
set __fish_git_prompt_showdirtystate 'yes'
set __fish_git_prompt_showstashstate 'yes'
set __fish_git_prompt_showupstream 'yes'
set __fish_git_prompt_showcolorhints 'yes'
set __fish_git_prompt_color_branch 'yellow'
function fish_prompt  -d "Write out the prompt"
  set last_status $status
  printf '%s%s%s @ %s%s%s : %s%s%s%s\n' (set_color red) (whoami) (set_color blue) (set_color magenta) (hostname|cut -d . -f 1) (set_color blue) (set_color $fish_color_cwd) (prompt_pwd) (set_color normal) (__fish_git_prompt)
  set_color normal
  printf '$ '
end

function fish_right_prompt -d "Write out the right prompt"
  date "+[%H:%M] %m/%d/%y"
end
```

**Comment by nicm** [comment]
tmux doesn't know anything about the prompt, when you resize it will make a best effort to do something sensible with what is currently on screen but there is no way it could know where to move that bit over to the right when you resize. It is up to the shell to redraw the prompt correctly when it is told about a resize and it seems like it is not doing so correctly.

**Comment by NickeZ** [comment]
Could or should tmux be doing something differently then, because it renders correctly in terminal emulators without tmux. Or does tmux have less information and therefore cannot redraw the line as expected?

**Comment by NickeZ** [comment]
This is what the prompt looks like in a terminal emulator after resizing multiple times:

![fish-in-terminal](https://cloud.githubusercontent.com/assets/492753/24295819/c9f03d18-109c-11e7-8216-d6e40442394c.png)

**Comment by nicm** [comment]
Could be that tmux does something different, but its hard to say what. There aren't really any rules about what the terminal should do with existing content on resize.

What terminal are you using?

**Comment by NickeZ** [comment]
I'm using [alacritty](https://github.com/jwilm/alacritty)

**Comment by nicm** [comment]
Do you see the same thing in gnome-terminal as in tmux?

**Comment by NickeZ** [comment]
Hmm, so you mean that fish could redraw the prompt when the size changes?

This is what gnome-terminal looks like for reference, a bit broken but not as bad as tmux.

![fish-in-gnome-terminal](https://cloud.githubusercontent.com/assets/492753/24297086/c15c60aa-10a1-11e7-8216-7f2991124147.png)

**Comment by nicm** [comment]
gnome-terminal and tmux both reflow text when you resize; xterm doesn't, I am guessing your terminal doesn't either.

**Comment by NickeZ** [comment]
yeah I also think alacritty doesn't reflow the text.

I think the difference in behavior between tmux and gnome-terminal is that I get a lot of new prompts in tmux

**Comment by NickeZ** [comment]
If I tail /var/log/dmesg and then resize the window a couple of times it looks like 

![fish-in-tmux-after-tail](https://cloud.githubusercontent.com/assets/492753/24297434/0dfab37a-10a3-11e7-91e6-d7b870dfbefe.png)

**Comment by nicm** [comment]
tmux can't know what to do with the text on the right, reflow is designed to work with normal text output not text drawn with cursor positioning. If your shell draws text like this but without entering cursor positioning mode (which turns off reflow and history) and without updating it when the terminal is redrawn, then tmux (and other terminals) are likely to get it wrong when they are resized.

Does it work as expected if you turn off the right-hand-side text?

**Comment by NickeZ** [comment]
I'm also starting to think that this is an issue with fish and not with tmux. It looks like bash reflows correctly but fish fails both in tmux and in gnome-terminal

**Comment by NickeZ** [comment]
Found an existing bug report. Closing this..

https://github.com/fish-shell/fish-shell/issues/2320
