### ISSUE TITLE
Defined behavior of #{pane_id} format in list-windows -F

### ISSUE THREAD

**Issue by tony** [tmux/tmux#839]
If someone does `$ tmux list-windows -F "#{pane_id}"`  I can get a result of a pane_id back.

> tmux list-windows -F "#{pane_id}
> %4

Is this defined behavior in tmux? What is the `pane_id` currently? the active pane?

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by nicm** [comment]
It is the active pane (and I think it actually always has been).

**Comment by tony** [comment]
Yes, it seemed like active pane.

Is it going to stay that way for the foreseeable future? The behavior is not defined in the documentation, is it? If someone is scripting tmux, this is a quicker way of getting the active pane.

**Comment by nicm** [comment]
Well, what else would it to show instead? I don't think there is any realistic chance of it changing, if we need a pane and we only have a window, we always use the active pane.

**Comment by tony** [comment]
I'm fine with `pane_id` in `list-windows` being the active pane, if the behavior stays as it.

The other plausible option would have been showing nothing; pane_id wouldn't exist on `list-windows`, since windows are a collection of panes, it's not expected a window would have a `pane_id`. The `pane_id` format should be reserved for `list-panes`. Something more explicit like `window_pane_active` / `window_active_pane` may be a better place for storing the active pane ID of a tmux window.
