### ISSUE TITLE
Get current command doesn't work as expected when piping to fzf

### ISSUE THREAD

**Issue by ddickstein** [tmux/tmux#840]
If I run [fzf](https://github.com/junegunn/fzf) directly and then run `display-message '#{pane_current_command}'` I get "fzf" as expected, but if I pipe to it, e.g. `ls mydir | fzf` and then while fzf is open I try to display pane_current_command I just get "bash".  Is there a reliable way to find out if fzf is running in this context?

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.
