### ISSUE TITLE
missing -c options for respawn-pane

### ISSUE THREAD

**Issue by pmnoxx** [tmux/tmux#844]
new-session / new-window / split-window have -c options which allows to select starting-directory.
Is there any way to select starting directory for respawn-pane function?

I'm trying to bind a shortcut, which restart current pane with old's bash pwd.
`
bind-key -T prefix x respawn-pane -c "#{pane_current_path}"
bind-key -T prefix n respawn-pane -c "#{pane_current_path}" "nvim; $SHELL"
`

Edit:
I figured out a workaround.
```
bind-key -T prefix n run-shell 'CC="#{pane_current_path}"; tmux respawn-pane -k "cd $CC; DISPLAY=remoteport nvim -c CtrlP; $SHELL"'
bind-key -T prefix x run-shell 'CC="#{pane_current_path}"; tmux respawn-pane -k "cd $CC; $SHELL"'
```

**Comment by nicm** [comment]
I would accept a change to add -c to respawn-pane/respawn-window like the existing commands.
