### ISSUE TITLE
Multiline strings not being presented to terminal as single string

### ISSUE THREAD

**Issue by andrewla** [tmux/tmux#847]
Using tmux at the tip of master (commit 05c97d7fe9ede1b9d185ed21242eb8470350affc).

Related, I think, to a recent commit, https://github.com/tmux/tmux/commit/3c3c08b6d9704b00a12e14772b95f7a40c20b10e, that fixes an issue with wrapped strings being available for selection by the controlling terminal.

```
~$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux master
screen-256color
```

After pulling in that patch, when you have a wrapped string, double-clicking in the controlling window will select the entire wrapped string with no newlines embedded.  When you switch to a new window, `C-a n`, and switch back, then double-clicking on the same string (to select the "word") will end at the end of the line, and will include a newline if selected manually.

Another interesting thing is that if the window is resized to be long enough that the string does not wrap, then it will be rendered, correctly, as a single line (for both display and selection purposes), but when the window is resized to the smaller size, then the line break appears again.

**Comment by nicm** [comment]
Yes this is a problem in tty_draw_line (so it only appears when the pane is redrawn, not when it is initially drawn).

**Comment by nicm** [comment]
Try this please: 
[x.diff.txt](https://github.com/tmux/tmux/files/890145/x.diff.txt)

**Comment by andrewla** [comment]
The provided diff did not fix it.  I've attached the output of a session for an 80-pixel wide window (using `script`), with three outputs -- one outside tmux, one inside tmux, and one after switching to a new pane in tmux and switching back.

Note that even in the non-redraw case, for strings longer than two lines, tmux inserts a break, and appears to elide the line break between two consecutive 80-character output strings with newline attached.

foo.py is just:

```
#!/usr/bin/python

print "two lines"
print "a" * 150
print ""
print "three lines"
print "a" * 190
print "Two consecutive one-lines"
print "a" * 80
print "a" * 80
```

And here's the transcript:
[transcript.txt](https://github.com/tmux/tmux/files/945413/transcript.txt)

I'm digging around to see if I can offer a fix for this, but I figure this information might be useful if someone else wants to have a go at it.

**Comment by nicm** [comment]
What terminal are you using?

**Comment by andrewla** [comment]
st, from suckless.
```
~$ echo $TERM
st-256color
```

I'll try it in xterm just to see if anything jumps out differently.

**Comment by nicm** [comment]
Please make sure your terminal is less than 200 columns wide then apply this patch [a.diff.txt](https://github.com/tmux/tmux/files/945464/a.diff.txt) and do exactly this:

tmux -f/dev/null -Ltest -vvvv new
perl -e 'print "x"x200'
C-b r

Then verify you can reproduce the problem by double clicking on the xxxxx... string (do not create a new window, just C-b r). Then exit tmux and send me the tmux-server*.log file from the current directory.

**Comment by andrewla** [comment]
Behavior in xterm is pretty much identical; some differences in escape sequences, but the same breaks to the relevant lines.

**Comment by andrewla** [comment]
Before the C-b r, the problem occurs (that is, double-clicking on the first line only selects the first two lines, not the third one).  After C-b r, double-clicking selects the entire block.

Here are the logs:
[patched.tar.gz](https://github.com/tmux/tmux/files/945478/patched.tar.gz)

**Comment by andrewla** [comment]
Some more experimentation shows that after refresh, this behaves quite nicely, fixing all the issues that I reported above -- the two consecutive lines being incorrectly joined, and the two-line limitation.

But another test with five lines of output -- `perl -e 'print "x"x400'` shows the problem again -- three lines get selected, but the other two do not.

**Comment by nicm** [comment]
So the diff fixes your original problem, but you are seeing a new problem?

Please try this (includes the previous): [b.diff.txt](https://github.com/tmux/tmux/files/945506/b.diff.txt)

**Comment by andrewla** [comment]
This appears to fix the problems for refresh, but only when there is no downward scrolling.

Without scrolling after a refresh all things work with this patch.  I used the test case below to check wrapping behavior:

[testcase.txt](https://github.com/tmux/tmux/files/947416/testcase.txt)

Before refresh there's only one broken case; and that's that consecutive full-length lines are selected as a single block (no CRs or cursor movement commands are injected).  After refresh, though, things are fixed.  It's just in the initial output.

But if I hit enter a couple of times to scroll, then everything pretty much breaks after a refresh.  Logs attached (here my terminal is 80x24):
[patched-c.tar.gz](https://github.com/tmux/tmux/files/947440/patched-c.tar.gz)

**Comment by nicm** [comment]
OK I see, try this please: [xyz.diff.txt](https://github.com/tmux/tmux/files/948840/xyz.diff.txt)

**Comment by nicm** [comment]
I have applied this now.

**Comment by bdrewery** [comment]
It was in d520dae6ac9acf980d48fbc8307ac83a5cee2938
