### ISSUE TITLE
[request] tmx script build in

### ISSUE THREAD

**Issue by ranomier** [tmux/tmux#848]
EDIT: tmux 2.3 (archlinux 64bit)

Hi,

I'm using this script for Years:
https://wiki.archlinux.org/index.php/Tmux#Clients_simultaneously_interacting_with_various_windows_of_a_session
From my understanding what it does:
- If there is no session with given name it will create one
- If there is a session with given name it will create one and will syncronize all windows.

It would be  a w e s o m e  to have that build into tmux. Maybe as a switch and/or config option.

What do you guys think?

**Comment by nicm** [comment]
Like tmux new -tname?

**Comment by ranomier** [comment]
What does -tname?
Im running tmux version 2.3 and i don't find it in the man page.

**Comment by nicm** [comment]
It makes a session group.

**Comment by MadMaverick9** [comment]
```
new-session ... [-t group-name]
```
