### ISSUE TITLE
Is it possible to replace the "/home/user/" part with "~" in pane_current_path in the status-bar

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#85]

**Comment by nicm** [comment]
Use #() and sed.

**Comment by c02y** [comment]
Currently my status-right configuration is:

    set -g status-right "\"#{=50:pane_current_path}\" %H:%M %u %m/%d"

but I don't know how to make it working using `sed`, any suggestion?

**Comment by c02y** [comment]
There is another clean solution from https://github.com/tmux/tmux/issues/1570#issuecomment-449599556
~~~
set -g status-right "#{s|$HOME|~|:pane_current_path} %H:%M %u %m/%d"
~~~
Hoping it would be helpful for others.

BTW: it doesn't work for the "50" in the string.
