### ISSUE TITLE
Frequently [lost server] crashes with tmux 2.3

### ISSUE THREAD

**Issue by bogner** [tmux/tmux#852]
Using tmux 2.3 from homebrew on macOS, I'm frequently seeing tmux spit out [lost server] and crash. For a while I thought it had to do with sigkill-ing client sessions, but it happened on copy-pasting a command from the history buffer today and I was able to reproduce with -vvvv. The error at the end seems to be "xsnprintf: overflow". Let me know if there's anything else you need.

[tmux-server-90341.log.txt](https://github.com/tmux/tmux/files/894592/tmux-server-90341.log.txt)

**Comment by nicm** [comment]
Does this still happen with a build from Git master?

**Comment by bogner** [comment]
Didn't reproduce with the copy-paste from before. Let me try it for a day or two and get back to you.
