### ISSUE TITLE
Can't build tmux

### ISSUE THREAD

**Issue by xapple** [tmux/tmux#853]
Hi !

I'm using the following script to build tmux and all its dependencies:

https://gist.github.com/xapple/cb4d94dd59b2a7b7f1219e5131d7e36e

It all works until the last command on line 56 which outputs this error:

        gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"2.2\"     -DPACKAGE_STRING=\"tmux\ 2.2\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\"     -DVERSION=\"2.2\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1     -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1     -DHAVE_UNISTD_H=1 -DHAVE_CURSES_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1     -DHAVE_NCURSES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1     -DHAVE_TERM_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_SYSCONF=1 -DHAVE_CFMAKERAW=1 -DHAVE_CFMAKERAW=1     -DHAVE_BSD_TYPES=1 -DHAVE_PROC_PID=1  -I.   -DTMUX_CONF="\"/etc/tmux.conf\""  -iquote.    -I/home/    sinclail/programs/libevent/include -I/home/sinclail/programs/ncurses/include/ncurses -D_GNU_SOURCE     -std=gnu99 -O2    -MT arguments.o -MD -MP -MF $depbase.Tpo -c -o arguments.o arguments.c &&\
        mv -f $depbase.Tpo $depbase.Po
    In file included from tmux.h:38,
                     from arguments.c:25:
    compat.h:203: error: expected identifier or ‘(’ before ‘__extension__’
    compat.h:203: error: expected identifier or ‘(’ before ‘)’ token
    make: *** [arguments.o] Error 1

How could I fix this?

**Comment by nicm** [comment]
What happens when you configure and build it yourself without the script?

**Comment by xapple** [comment]
If I do this:

    wget -O tmux-2.2.tar.gz https://github.com/tmux/tmux/releases/download/2.2/tmux-2.2.tar.gz
    tar xvzf tmux-2.2.tar.gz
    cd tmux-2.2
    ./configure

I get this:

    checking for flock... yes
    checking for setproctitle... no
    checking for sysconf... yes
    checking for cfmakeraw... yes
    checking for library containing clock_gettime... -lrt
    checking for LIBEVENT... no
    checking for library containing event_init... no
    configure: error: "libevent not found"

**Comment by Jesin** [comment]
You are attempting to install tmux 2.2 but the latest stable version is tmux 2.3, so any bug report you submit based on that may be outdated.

Also, based on the message `configure: error: "libevent not found"`, it sounds like you need to install libevent. You can find it at http://libevent.org/ or it may be in your distribution's package manager.

**Comment by xapple** [comment]
I only tried the direct compilation version because nicm asked about it. My first post described an error when installing with all of tmux dependencies, including of course libevent. The package manager of the linux distribution is, as always, of no use at all since it does not include an option to work without sudo privileges.

**Comment by nicm** [comment]
Try 2.3 please and show me config.log and full build output if you still see the error.

**Comment by godnani2006** [comment]
Before you need to  install this commands :+1: 
apt-get install autogen automake libevent-dev libncurses5-dev

**Comment by xapple** [comment]
To execute that command you need to have sudo privileges. I am not a system administrator, I am a user of the computer.

**Comment by Chen-kaiyuan** [comment]
That's right,try "yum install libevent-devel ncurses-devel" and running again tmux.
I have the same problem on centos 6.5 and tmux1.8.

**Comment by godnani2006** [comment]
Hi xapple,

Yes, Please use sudo privileges.

**Comment by xapple** [comment]
When you need high performance computing for real world use cases, in most cases, unless you have huge resources at disposal, what you get is a login to a shared compute node -- provided by a company or a university. The fact that you suggest I use sudo privileges just after having told you that I am a user of the machine, and not an administrator makes me think you have never worked in such environments, nor do you take time to adequately read my responses.

**Comment by Jesin** [comment]
It should be possible to use tmux even on shared computers where you do not have root privileges. In fact, that is one of the environments where tmux is _most_ helpful, since those systems are usually logged into remotely and tmux allows you to keep a session open and re-attach to it later.

@godnani2006 Most sysadmins do not (and should not!) hand out root privileges to everyone.

**Comment by codefool** [comment]
Okay, so you want to build tmux without having to actually install the dependent libraries. This can be done, but with great difficulty. You would have to first identify the packages and all their dependents, download them, unpack their distributions and fixup environment vars to point to them during the build.

Or, you could just ask an admin to install the packages for you. Since they are standard distributions, they should have no issue doing that. You can then run the build process from your workspace. Or, you could ask an admin to just install tmux for you. I think if you work with your admin you can find a solution that works.

HTH - glh

**Comment by xapple** [comment]
The "ask the admin" route has a thousand complexities that are more intricate that any installation of dependency libraries. If you have ever depended on some IT unit with more or less knowledgeable staff, with more or less time to spare, with more or less political ramification, etc, then you know what I am talking about.

In fact, the answer from them often is "just install what you want in your home, what we provide is such and such distro and that's it". Which is a reasonable answer I would say. What is unreasonable in my eyes is the lack of simple tmux binaries to use, and the install nightmare that ensues.

**Comment by xapple** [comment]
I think we have gone full circle as that gist that you posted looks awfully like the one I linked to in my first message when I opened this issue a year ago.

**Comment by nicm** [comment]
I am not going to maintain static builds. If you want to maintain a
repository on GitHub or elsewhere with static binaries for your platform
then feel free.

tmux only has two dependencies so it is not hard to build without root, and
there are a number of scripts out there that will do so including building
ncurses and libevent.

**Comment by jdhao** [comment]
Tmux has two dependency. libevent and ncurses. On my system, ncurses
has been installed. So I need to install libevent.

```
wget https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz
tar zxvf libevent-2.1.8-stable.tar.gz
cd libevent-2.1.8-stable
mkdir -p ~/tools/libevent
./configure --prefix="$HOME/tools/libevent"
make -j && make install
```

Libevent will be install to `$HOME/tools/libevent`.

Then download Tmux release tarball and build it

```
wget https://github.com/tmux/tmux/releases/download/2.8/tmux-2.8-rc.tar.gz
tar zxvf tmux-2.8-rc.tar.gz
cd tmux-2.8-rc
mkdir -p ~/tools/tmux
./configure --prefix="$HOME/tools/tmux" \
    CFLAGS="-I$HOME/tools/libevent/include" \
    LDFLAGS="-L$HOME/tools/libevent/lib" \
make -j && make install
```

Tmux will be installed to `$HOME/tools/tmux`.

Then add tmux executable to your PATH.

```
export PATH="$HOME/tools/tmux/bin:$PATH"
```
