### ISSUE TITLE
cc1: warning: unrecognized command line option "-Wno-unused-result"

### ISSUE THREAD

**Issue by jwz-ecust** [tmux/tmux#856]
something wrong with my installation

control.c: In function ‘control_write’:
control.c:39: warning: passing argument 2 of ‘evbuffer_add’ discards qualifiers from pointer target type
/home/users/jwzhang/script/source-code/vagrant/libevent/include/event.h:280: note: expected ‘void *’ but argument is of type ‘const char *’
control.c: In function ‘control_write_buffer’:
control.c:48: warning: passing argument 2 of ‘evbuffer_add’ discards qualifiers from pointer target type
/home/users/jwzhang/script/source-code/vagrant/libevent/include/event.h:280: note: expected ‘void *’ but argument is of type ‘const char *’
control.c: In function ‘control_callback’:
control.c:80: warning: implicit declaration of function ‘evbuffer_readln’
control.c:80: error: ‘EVBUFFER_EOL_LF’ undeclared (first use in this function)
control.c:80: error: (Each undeclared identifier is reported only once
control.c:80: error: for each function it appears in.)
At top level:
cc1: warning: unrecognized command line option "-Wno-unused-result"

**Comment by nicm** [comment]
Your libevent is too old.

**Comment by jwz-ecust** [comment]
@nicm  Thank you! after I posted the issue,  I also found that libevent is too old.
