### ISSUE TITLE
is it possible to list all panes?

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#86]
Say, I got two windows, Window 1 contains 2 pane (1, 2), Window 2 contains 3 panes(1,2,3), and I'm in pane 1 in Window 1, and I want to jump directly into the pane 2 in Window 2, `PREFIX w` which is `choose-window` will list all the windows in the session so I can jump into the right window, but it will not list the panes, `PREFIX q` which is `display-panes` will let me choose the right pane but it will not across windows.

So I wonder if there is any command that let me choose panes across windows.
The best solution is `choose-window` or a new command will not only list all the windows but also list all the panes inside each window like `tree` in a directory.

**Comment by ThomasAdam** [comment]
There's no way to choose panes as there are with choose-tree, for instance.

**Comment by c02y** [comment]
@ThomasAdam I can use `tmux list-panes -s` to list all the panes in the current session, but how can I use this list so I can choose one like `tmux choose-window`?

**Comment by nicm** [comment]
Heh. It is not as easy as that.

**Comment by c02y** [comment]
This problems is solved by commit aad4e4d , use `choose-tree` (just bind it to a key) to show all panes in all sessions/widows/tabs, it even show a preview box when you scroll line into one pane from the list, very nice.
