### ISSUE TITLE
vim broken on trunk

### ISSUE THREAD

**Issue by octoploid** [tmux/tmux#862]
Consider the file:
```
 % cat xxx
This is a simple test
This is a simple test
This is a simple test
This is a simple test
This is a simple test
```
When I edit the file with vim and insert say the word "very" before "simple" on line three
and then press ESC and then the left cursor key I get the following:
```
This is a simple test
This is a simple test
This is a very
```
The rest of the file gets truncated.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by octoploid** [comment]
Sorry I don't have time to debug this any further.
So take it as an FYI.
