### ISSUE TITLE
tmux >= 2.2 key mappings broken on Solaris

### ISSUE THREAD

**Issue by ericvw** [tmux/tmux#864]
On SunOS sparc (`uname -sp`), for tmux >= 2.2, the key mappings are broken.  For example, attempting to `Ctrl-d`, results in the status bar reporting "No mouse target"; up arrow outputs `8` and down arrow outputs `9`.

After running `git bisect` between 2.1 and 2.2, 5f483499 is the merge commit that introduces this issue.  When building using the Solaris `cc` compiler, for 64bit, there are warnings which are emitted in `tmux.h` for the enumeration of key codes of the form:

    "./tmux.h", line 136: warning: enumerator value overflows INT_MAX (2147483647)

What appears to be the issue is that Solaris does not support values greater than of type `int` for enumerations.  I have found via the [Solaris 64-bit Developer Guide](https://docs.oracle.com/cd/E18752_01/html/816-5138/convert-1.html) that this also appears to be the case.

Unfortunately, I am unable to upload any logs due to work policies, but I hope the provided information is adequate enough.

It seems like the path forward would be to remove the enumeration in favor of global constants; however, specifying & incrementing the values would be tedious.  There may be other solutions to address this elegantly.

I'm happy to contribute a patch/PR once it is made known how this would like to be addressed.

**Comment by nicm** [comment]
This warning was fixed about four months ago:

commit 353439aceeed6ab311a74fc38f15276f72c654a4
Author: nicm <nicm>
Date:   Fri Nov 4 14:47:38 2016 +0000

    enum values need to fit in 32 bits; we only use enum for numbering and
    Unicode characters fit in 24 bits, so we can leave key_code as 64 bits
    and change KEYC_BASE down to 0x10000000.

**Comment by ericvw** [comment]
Oh wow - thanks.

I had trouble compiling `master` on Solaris due to an anonymous struct within a union - I'll track that down before raising a separate issue.  Otherwise I would have verified this before filing.  Thanks for the quick response.

**Comment by nicm** [comment]
That'd be struct grid_cell_entry and struct options_entry probably. Anonymous unions weren't standardized until C11 but they are an extremely useful extension so if you can persuade Sun CC to accept them it would be useful.

**Comment by ericvw** [comment]
It looks like the latest Sun CC has support for anonymous unions & structs using `-features=extensions`.  https://docs.oracle.com/cd/E18659_01/html/821-1383/bkael.html

For anyone who comes across this and is using an older CC version, just name the struct and perform a search & replace for the struct member access in `options.c`.
