### ISSUE TITLE
Cursor's pane doesn't update from control mode.

### ISSUE THREAD

**Issue by snoe** [tmux/tmux#867]
Using iterm2 3.0.15, os x sierra 10.12.4, tmux 2.3, outside TERM=xterm-256color, inside TERM=screen (or screen-256color doesn't matter).

When I switch panes in iTerm2 using tmux integration control mode the cursor in terminal attached sessions stays in the last panel opened by iterm2. A client attached to the same session who's not in control mode can move cursor and other clients will see the change but the control mode client can never move the cursor to another pane. Typing and other interactions by the control mode client appear in the correct panes.

Repro:
tmux -vvvv -Ltest -f/dev/null -CC new
tmux -vvvv -Ltest -f/dev/null attach
create two panes in CC terminal switch between them. attached client cursor will stay in second pane.

**Comment by nicm** [comment]
Can't reproduce. In one terminal:

tmux -Ltest -f/dev/null -C new
splitw

In other:

tmux -Ltest -f/dev/null attach

Back to -C tmux:

selectp -U
selectp -t:.0

Cursor moves fine.

**Comment by snoe** [comment]
ok I was using the mouse in iterm to select the pane. 
So does this seem like an iterm bug and they need to send `selectp` when panes are selected?

**Comment by nicm** [comment]
Yes if iTerm2 is handling the mouse itself rather than passing it to tmux then it will need to select the pane itself.
