### ISSUE TITLE
warning still present while compiling with gcc7

### ISSUE THREAD

**Issue by rosset** [tmux/tmux#868]
Eg,
               "arch" : "x86_64",
               "code" : "TypePun",
               "context" : {
                  "excerpt" : [
                     "compat/imsg-buffer.c: In function &#39;msgbuf_write&#39;:",
                     "compat/imsg-buffer.c:261:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]"
                  ],
                  "lineno" : 546,
                  "path" : "x86_64/build.log",
                  "sub" : "(in %build)"
               },
               "diag" : "gcc warnings"

Link with all build logs/warnings: https://kojipkgs.fedoraproject.org//packages/tmux/2.4/2.fc27/data/logs/x86_64/build.log

**Comment by nicm** [comment]
The warning is fine, you can ignore it.
