### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [tmux/tmux#87]
I would like to point out that identifiers like "[`__progname`](https://github.com/tmux/tmux/blob/18a64ad52d5b33e229783574a637268eb098b1f0/tmux.c#L56)" and "[`_VIS_H_`](https://github.com/tmux/tmux/blob/f7598b8a267eeab926ed0a934f36595077aab605/compat/vis.h#L35)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by nicm** [comment]
No thanks

-------- Original message --------

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by nicm** [comment]
What do you think would happen if we changed __progname in tmux... do you know what it is for?

And vis.h is a thirdparty header, I'm not making it harder to sync to solve a theoretical problem.
