### ISSUE TITLE
Typo in FORMATS section of man page

### ISSUE THREAD

**Issue by juniorism** [tmux/tmux#870]
The tmux.1 man page in commit c376c5a817973f176894c7ee11bb5675affb3be4 of the master branch states:

     Simple comparisons may be expressed by prefixing two comma‐separated
     alternatives by ‘==’ or ‘!=’ and a colon.  For example
     ‘#{==,#{host},myhost}’ will be replaced by ‘1’ if running on ‘myhost’,
     otherwise by ‘0.’

The example should use a colon in place of the first comma:

```
diff --git a/tmux.1 b/tmux.1
index 86281194..c842e069 100644
--- a/tmux.1
+++ b/tmux.1
@@ -3439,7 +3439,7 @@ or
 .Ql !=
 and a colon.
 For example
-.Ql #{==,#{host},myhost}
+.Ql #{==:#{host},myhost}
 will be replaced by
 .Ql 1
 if running on
```

**Comment by nicm** [comment]
Applied thanks.
