### ISSUE TITLE
Disappear some words when I types more than two Chinese words in '', just 2.4, not 2.3.

### ISSUE THREAD

**Issue by getong** [tmux/tmux#873]
![tmux_2 4_disappear_words](https://cloud.githubusercontent.com/assets/3949379/25302372/440bb562-276f-11e7-8b46-10f1a67d72de.png)

I compile tmux 2.4 myself.  Today I type more than two Chinese words in the tmux version 2.4. It disappears some words in the terminal. See the pic above.

I also test it in 2.3 version, it works fine and not found this bug.

**Comment by nicm** [comment]
Logs please.

**Comment by getong** [comment]
@nicm It does not crash, and works fine. Even the words disappears in the terminal, the words still works as I get it back from the other softwares. And I don't know how to get the log.

**Comment by nicm** [comment]
Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by getong** [comment]
[tmux-server-3788.log.txt](https://github.com/tmux/tmux/files/948823/tmux-server-3788.log.txt)

**Comment by nicm** [comment]
I think this is the fix, we need to treat UTF-8 characters like normal characters. Please try to make this change:

~~~~
Index: input.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/input.c,v
retrieving revision 1.118
diff -u -p -r1.118 input.c
--- input.c	22 Mar 2017 07:16:54 -0000	1.118
+++ input.c	22 Apr 2017 07:59:41 -0000
@@ -2011,7 +2011,7 @@ input_utf8_close(struct input_ctx *ictx)
 	    (int)ud->size, ud->data, ud->width);
 
 	utf8_copy(&ictx->cell.cell.data, ud);
-	screen_write_cell(&ictx->ctx, &ictx->cell.cell);
+	screen_write_collect_add(&ictx->ctx, &ictx->cell.cell);
 
 	return (0);
 }

**Comment by getong** [comment]
@nicm I replace the patch, it works fine. Thanks.
