### ISSUE TITLE
set-{server,session}-option aliases

### ISSUE THREAD

**Issue by jedahan** [tmux/tmux#877]
On tmux 2.4/zsh 5.3.1/iTerm2 3.0.15/macOS 10.12.4 *~/.tmux.conf*:

    set-server-option -g escape-time 0

gives 'invalid or unknown command'. Similarly for `set-session-option` as an alias for `set-option`.

It would be really nice for beginner/human-readable configs to support `set-session-option` and `set-server-option`, similar to `set-window-option` but for `set-option -s` and `set-option`.

**Comment by jedahan** [comment]
I tried using the following but it still gives `invalid or unknown command`:

```tmux
set -sg command-alias[2] set-server-option='set-option -s'
set-server-option -g escape-time 0
```

**Comment by nicm** [comment]
Works for me.

**Comment by jedahan** [comment]
Which works for you? The commands themselves, or the aliases?
What system are you on @ncim ?
Mind sharing your config?

**Comment by jedahan** [comment]
It's worth noting - this works when i manually type in the commands after tmux has loaded, but does not work when inside the tmux.conf file

**Comment by nicm** [comment]
command-alias can be set from the config file but you can't use the aliases in the config file itself because the entire config file is parsed before any commands are executed, so the new command-alias will not be present when the line attempted to use it is parsed.

**Comment by jedahan** [comment]
How do you feel about #878 @ncim ? I wouldn't mind adding it to the documentation as well.

**Comment by nicm** [comment]
I don't think this is necessary TBH and if we add aliases and people start to use them we are stuck with them.

**Comment by nicm** [comment]
Ideally setw would become an alias and be removed from the manual. It doesn't matter which you use anyway unless you are setting a user option (it does for show-option though). Ideally there would only be one set of options anyway and it'd inherit window->session->server but I haven't looked at doing that yet.
