### ISSUE TITLE
Binding WIndows key

### ISSUE THREAD

**Issue by binamkayastha** [tmux/tmux#879]
I read online that it's impossible to bind the Windows key in tmux. I was wondering why this was such a difficult issue, and why the only workaround is to bind the windows key to something ridiculous, and use that. 

I must be missing something, because I don't understand how difficult it would be to add this feature to tmux. I'm would think all you'd have to do is add a new define statement in the tmux.h file like it was done for shift:

`#define KEYC_SHIFT 0x800000000000ULL // Also it would help if you could tell me how you guys got this keycode value that might help me as well`

And then change the modifiers function in key-string.c

Unnecessary but required info:
tmux 2.3
ArchLinux
$TERM outside tmux: xterm
$TERM inside tmux: screen

uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.3
xterm

**Comment by nicm** [comment]
Terminals only support three modifiers (ctrl, meta and shift), and only a limited subset of keys for each. You will need to change your terminal to send the Windows key before trying to change tmux to use it.

**Comment by dkrikun** [comment]
How about using the windows key not as a modifier? Is it possible?
Now I have it mapped to f12 using a keymap (via kbd package), and then f12 bound to prefix in tmux.
Would it be possible to just set the window key as  prefix in tmux?

**Comment by krader1961** [comment]
@dkrikun Please don't ask new questions on issues that have been closed a long time. But I'll provide some hints that might help you understand why what you want to do won't work. First, eliminate tmux from the equation. In your preferred MS Windows terminal (ConEmu or whatever) run a command that will show the characters it receives. For example, `od -tx1`. Then press a key like `a`, [enter], then [ctrl-D] and observe what is displayed. Repeat the experience and press the [windows] key, [enter], then [ctrl-D]. Do you see any characters corresponding to the [windows] key?

**Comment by dkrikun** [comment]
Is it strictly necessary to be able to bind it on all supported platforms?
I am asking because even if it was possible to, I had no slightest
intention to use the key on windows, but on linux, because it is rather
useless in tty anyway.
