### ISSUE TITLE
Dragging does not work in tmux 2.4 with mouse on

### ISSUE THREAD

**Issue by ejpcmac** [tmux/tmux#880]
## Environment

* **Version:** 2.4 from `brew`, and tested with `master@9d041d8`
* **Platform:** OS X Yosemite 10.10.5
* **Minimal config:** `set -g mouse on`
* **Terminal outside tmux:** `xterm-256color`
* **Terminal inside tmux:** `screen-256color`

## Problem description

In tmux 2.3 I was able to resize panes or select text with the mouse. In tmux 2.4 with `mouse on`, I am able to scroll and select the pane, but not do anything related to dragging: it is not possible to resize the panes or select text with the mouse.

**Comment by nicm** [comment]
It works for me. What terminal are you using? Show some tmux logs?

**Comment by ejpcmac** [comment]
I’m using the default OSX Terminal. You will find log files on [this gist](https://gist.github.com/ejpcmac/27ee06234c1f157b56419567f20f2660). My test setup is as follows:

* `tmux` compiled from master
* `/etc/tmux.conf` containing only `set -g mouse on`

I runned:

```
./tmux -vvvv -Ltest -f/dev/null new
```

Then in tmux I just tried to select the prompt, it did nothing.

**Comment by nicm** [comment]
-f/dev/null won't load your config, did you run "set -g mouse on" after
starting tmux?



On 24 Apr 2017 7:24 pm, "Jean-Philippe Cugnet" <notifications@github.com>
wrote:

I’m using the default OSX Terminal. You will find log files on this gist
<https://gist.github.com/ejpcmac/27ee06234c1f157b56419567f20f2660>. My test
setup is as follows:

   - tmux compiled from master
   - /etc/tmux.conf containing only set -g mouse on

I runned:

./tmux -vvvv -Ltest -f/dev/null new

Then in tmux I just tried to select the prompt, it did nothing.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/880#issuecomment-296780687>, or mute
the thread

**Comment by ejpcmac** [comment]
Oops no, I did not. But strangely the scroll works without this config. [Here is a new gist](https://gist.github.com/ejpcmac/1a70c2bc38072be39d5bfa8e2019ee5e) with this new procedure:

I runned:

```
./tmux -vvvv -Ltest -f/dev/null new
```

Then in tmux I did `C-b`+`:`, `set -g mouse on`, `<Enter>`. I then scrolled up and down, it worked. I tried to select the prompt, it did nothing.

**Comment by nicm** [comment]
What do you mean select the prompt?

**Comment by ejpcmac** [comment]
I mean click over `[JPC@MacBook-JP]:~ % ` and drag to select it. In previous versions it shows a yellow hilight over the text and tmux is in selection mode.

**Comment by nicm** [comment]
OK please give me a log of doing that without using the scroll wheel first. So just do this:

tmux -vvvvLtest -f/dev/null new
tmux set -g mouse on

Then drag over the prompt once, then exit tmux immediately and send me the log.

**Comment by ejpcmac** [comment]
Here is the new log: https://gist.github.com/ejpcmac/3723a2eb017f433d2c0a25a4d17742bd

**Comment by nicm** [comment]
This seems like a bug in Terminal.app. tmux is seeing the mouse down event OK but when you drag it is getting buttons == 3 which means "release". 00 is button 1 pressed, 23 is drag+release, 03 is all buttons release:
~~~~
1493071707.703368 mouse 00 at 0,1 (last 0,0) (0)
1493071707.762280 mouse 23 at 0,1 (last 0,1) (0)
1493071707.780529 mouse 23 at 1,1 (last 0,1) (1)
...
1493071708.556734 mouse 23 at 24,1 (last 24,1) (0)
1493071708.571819 mouse 23 at 24,1 (last 24,1) (0)
1493071708.590075 mouse 23 at 25,1 (last 24,1) (0)
1493071708.765386 mouse 03 at 25,1 (last 25,1) (0)
~~~~
Compare with xterm which (with SGR mouse disabled) shows mouse button 1 pressed through the entire drag (20 is drag+button 1):
~~~~
1493073097.947016 mouse 00 at 0,0 (last 0,0) (0)
1493073098.115018 mouse 20 at 1,0 (last 0,0) (0)
1493073098.138912 mouse 20 at 2,0 (last 1,0) (1)
...
1493073098.514826 mouse 20 at 25,0 (last 24,0) (1)
1493073098.546856 mouse 20 at 26,0 (last 25,0) (1)
1493073098.610880 mouse 20 at 27,0 (last 26,0) (1)
1493073099.059166 mouse 03 at 27,0 (last 27,0) (1)
~~~~

**Comment by alwinmarkcf** [comment]
Have the same issue with gnome terminal and vim.
Without tmux I'm able to resize splits. With tmux not. I can use any mouse feature in vim except dragging stuff.

Guess it is a bug in tmux somehow
