### ISSUE TITLE
tmux 2.4 - key bindings in root table does work in copy mode

### ISSUE THREAD

**Issue by ShikChen** [tmux/tmux#881]
```
❯ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.4
screen-256color
```

I have `bind -n M-j previous-window` in my conf and it works in copy mode in tmux 2.3, but not 2.4.
The current workaround is to add `bind -T copy-mode-vi M-j previous-window` as well.
Is this a bug or an incompatible change?

**Comment by nicm** [comment]
It doesn't work in 2.4 but it has been changed to work in master.
