### ISSUE TITLE
tmux >=2.4 — ‘if-shell’ changed behaviour

### ISSUE THREAD

**Issue by floand** [tmux/tmux#882]
## Environment
**Version:** Release 2.4 and Commit 9d041d8e6c1f24828da727077bc13b49c1f58654
**Platform:** Gentoo Linux
**Minimal config:** `if-shell '[[ "$(tput colors)" -ge 256 ]]' 'set-option -g default-terminal tmux-256color' 'set-option -g default-terminal tmux'`
**$TERM outside tmux:** `rxvt-unicode-256color` (urxvt) and `xterm-256color` (xfce4-terminal)
**$TERM inside tmux:** `tmux` (due to failing test)
## Behaviour description

Until new release _tmux-2.4_, I used two working conditions in my configuration. The one mentioned above (minimal config) and a second to create a certain session conditionally:
```
if-shell 'tmux has-session -t local' '' \
    'new-session -s local -n bash -d -x 240 -y 69 ; \
        split-window -h -p 50 ; \
        split-window -v -l 46 ; select-pane -t 1 ; \
[...] \
    select-window -t bash'
```
Now with >=_tmux-2.4_, both tests evaluates always to _false_ even with a different syntax for the former:
```
if-shell '[ "$(tput colors)" -ge 256 ]' 'set-option -g default-terminal tmux-256color' 'set-option -g default-terminal tmux'
if-shell 'test "$(tput colors)" -ge 256' 'set-option -g default-terminal tmux-256color' 'set-option -g default-terminal tmux'
```
But on the other hand, what always work as expected is:
```
if-shell 'true' 'display-message "true, as expected"' 'display-message "false"'
if-shell 'false' 'display-message "true"' 'display-message "false, as expected"'
```
Am I missing something? Is there any alternative solution and/or a workaround for this behaviour? Independently from that, thanks for your work!

FWIW: Building 9d041d8e6c1f24828da727077bc13b49c1f58654 triggers two warnings here:
- **format.c:998:2:** `warning:` format not a string literal, format string not checked [-Wformat-nonliteral]
- **compat/imsg-buffer.c:261:3:** `warning:` dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

**Comment by nicm** [comment]
Please show me logs from running "tmux -vvvv -Ltest" with your minimal config. Use test or [ ] not [[ ]].

**Comment by nicm** [comment]
Actually it's OK, I know what this is. TERM is now set for if-shell and run-shell, so tput colors will show the capability for _tmux's_ TERM, which at that point is "screen".

**Comment by nicm** [comment]
You if-shell with the has-session seems to work OK for me, if I do "tmux new" I end up with two sessions - "local" and "0". Then if I do source-file, it doesn't create a second "local" session.

**Comment by nicm** [comment]
You can try this change to fix the former, it is probably sensible not to set TERM while loading the config the first time:

~~~~
diff --git a/environ.c b/environ.c
index 868324e..b9b4746 100644
--- a/environ.c
+++ b/environ.c
@@ -233,8 +233,10 @@ environ_for_session(struct session *s)
 	if (s != NULL)
 		environ_copy(s->environ, env);
 
-	value = options_get_string(global_options, "default-terminal");
-	environ_set(env, "TERM", "%s", value);
+	if (cfg_finished) {
+		value = options_get_string(global_options, "default-terminal");
+		environ_set(env, "TERM", "%s", value);
+	}
 
 	if (s != NULL)
 		idx = s->id;

**Comment by nicm** [comment]
Actually, wait, that is wrong, because we do want to set it for new windows and sessions

**Comment by nicm** [comment]
You can try this instead: [t.diff.txt](https://github.com/tmux/tmux/files/954137/t.diff.txt)

But it's a bit more involved and I'm not sure it's worth it. You are getting the benefit of the fact that tmux derives the initial environment from the shell where it is started, but I'd really like that to stop. Maybe we should provide a way to explicitly get the client environment. Or I suppose we could preserve TERM from the client like PATH for this case.

**Comment by nicm** [comment]
It is probably impractical to start with an empty environment at this point TBH so I guess this will be OK.

I don't know why your other command is failing, I'll take a look when you have some logs.

**Comment by blueyed** [comment]
I've noticed that `$TERM` in `if-shell` changed the behavior.
I am using the following in my config:
```tmux
if-shell '[ "$TERM" = "linux" ]' 'set -g default-terminal "tmux"' 'set -g default-terminal "tmux-256color"'
```

Using the following displays `2:rxvt-unicode-256color`:
```tmux
if-shell '[ "$TERM" = "linux" ]' 'display -p 1:$TERM' 'display -p 2:$TERM'
```

With the first, short patch (https://github.com/tmux/tmux/issues/882#issuecomment-296935700) I get `TERM=rxvt-unicode-256color` in the first window, and then `tmux-256color` with a new pane (?!).
With the second one (`t.diff.txt`) I get `TERM=screen` in the first window/pane, and `tmux-256color` in new ones.

Therefore the 2nd patch would need to be adjusted to also affect the first pane already?!
That might be more an issue with `set -g default-terminal` though.

**Comment by nicm** [comment]
Ah yeah I remember now, this is why the config file needed to go on the client command queue not on the global one, so that it is complete before the config file is finished. If you revert 311dad8c28c8c1a842beb3dbb1757064b9d83b2e it would work, but I don't want to do that because it breaks something else.

However, a simpler fix might be to just not process any client queues until the config is done:

~~~~
diff --git a/server.c b/server.c
index bdbe922..74813b5 100644
--- a/server.c
+++ b/server.c
@@ -201,9 +201,11 @@ server_loop(void)
 
 	do {
 		items = cmdq_next(NULL);
-		TAILQ_FOREACH(c, &clients, entry) {
-			if (c->flags & CLIENT_IDENTIFIED)
-				items += cmdq_next(c);
+		if (cfg_finished) {
+			TAILQ_FOREACH(c, &clients, entry) {
+				if (c->flags & CLIENT_IDENTIFIED)
+					items += cmdq_next(c);
+			}
 		}
 	} while (items != 0);

**Comment by blueyed** [comment]
That makes it hang with something like the following:
```tmux
if-shell 'tmux show -g -w | grep -q c0-change-trigger' \
    "set -g c0-change-trigger 0" ""
```
(this is constructed and can be simplified, but I had that in my config)

It might also affect TPM in general (https://github.com/tmux-plugins/tpm/issues/110).

**Comment by nicm** [comment]
Yes of course it does, it needs clients to be working too... blah. I'll
have another look in a bit.

**Comment by nicm** [comment]
Here is a better idea, block that client, but only that one: [x.diff.txt](https://github.com/tmux/tmux/files/955175/x.diff.txt)

**Comment by floand** [comment]
With your [x.diff.txt](https://github.com/tmux/tmux/files/955175/x.diff.txt) patch applied it works again for me. And also constructs like:
```
if-shell '[[ -z ${DISPLAY} ]]' \
    'set-option -g default-terminal linux' \
    'if-shell "[[ $(tput colors) -ge 256 ]]" \
        "set-option -g default-terminal tmux-256color" "set-option -g default-terminal tmux"'
```

Thanks for investigating and solving this so fast.

**Comment by nicm** [comment]
I have applied this now, thanks!
