### ISSUE TITLE
Clearing screen with status-position top

### ISSUE THREAD

**Issue by casr** [tmux/tmux#887]
On macOS 10.12.4, with `status-position` set to `top` I noticed that when I have two panes and I clear the top pane with `C-l` the bottom pane disappears.

To quickly test with a minimal tmux configuration:

```sh
tmux -f <(echo 'set-option -g status-position top')
```

then `C-b "` `C-b ⬆️` `C-l`. `C-b ⬇️` and the missing pane will reappear.

Hopefully this video can illustrate it nicely: https://gfycat.com/WillingNiceBluefish

```sh
$ uname -smp && tmux -V && echo $TERM
Darwin x86_64 i386
tmux 2.4
screen
```

Logs: https://gist.github.com/casr/e363faef3b9e334472f7de96d30b92c2

**Comment by casr** [comment]
I think my zsh configuration is triggering this; I couldn't reproduce with an empty zsh configuration.

**Comment by nicm** [comment]
This should be fixed in master.
