### ISSUE TITLE
Feature request: allow percentage for "tmux set-window-option main-pane-height"

### ISSUE THREAD

**Issue by trevordmiller** [tmux/tmux#888]
Currently I'm using
`tmux set-window-option main-pane-height 30`
along with
`tmux select-layout main-horizontal`
to create this:

![image](https://cloud.githubusercontent.com/assets/5497885/25462116/1fd84abe-2aaa-11e7-8e50-1c96ac1a3ce1.png)

This works well for my main monitor but not as well on smaller screens; it would be great if I could use a percentage so that the non-main panes take up 1/3 or 33% height of the entire terminal or something.

Thank you for the great work. tmux is amazing.

**Comment by nicm** [comment]
You could write a script and run that instead of selectl, something like:
~~~~
tmux selectl main-horizontal
Y=$(expr $(tmux display -p '#{window_height}') / 3)
tmux resizep -t:.0 -y $Y

**Comment by trevordmiller** [comment]
Ok thanks

**Comment by trevordmiller** [comment]
Worked great! Thank you. Here is the diff for anyone else that may need it:
https://github.com/trevordmiller/settings/commit/83799626451d76655f4ac0a4c97eb9dd2c52ea9d

**Comment by tony** [comment]
I made a script for handling this at https://github.com/tony/tmux-config/blob/5b348ee/scripts/resize-adaptable.sh. I also wrote a blog post about it at https://devel.tech/tips/n/tMuXrSz9/resize-tmux-main-panes-by-percentage/ and linked this issue up.
