### ISSUE TITLE
tmux randomly stops passing scrollback buffer history to the terminal

### ISSUE THREAD

**Issue by BrainDamage** [tmux/tmux#89]
tmux version 2.0
tmux seems to have erratic behavior when a lot of text is being dumped very fast, the mid of the scrollback buffer there'll be random interruptions chopping off multiple lines of history, but the start and end of the text will be preserved
tmux's own builtin scrollback works fine
i can reproduce this over multiple terminal emulators using different engines ( terminator, urxvt, konsole ), multiple commands, local and remote ( ssh ) shell instances ( even using android connectbot as ssh client ), and multiple shells ( bash and zsh )

the following screenshots were created using zsh and the command "man gpg | cat" to dump text in the scroll buffer, for the sake of brevity I didn't include a sample for each test i tried

terminator ( vte-based, requires disabling the output to alternate screen in order to have history saved ):
[no tmux](https://imgur.com/a/j6Tzm#0) vs [tmux](https://imgur.com/a/j6Tzm#1) 

urxvt:
[no tmux](https://imgur.com/a/j6Tzm#2) vs [tmux](https://imgur.com/a/j6Tzm#3) 

It's also interesting that the interruption point differs between different terminal emulators, yet is somehow close, however, I suspect it's due to the different performance of the various terminals since the data rate seems to be impacting a lot the effect ( manually throttling to a sufficiently slow value can reduce or even make the problem disappear ), perhaps this is an indication of a threading race condition/concurrency issue? ( sorry, not familiar with the code base)

**Comment by nicm** [comment]
If you write a lot of lines quickly tmux will not write them all to the terminal if it doesn't need to. This is an optimization. Use tmux copy mode if you want the entire pane history.

**Comment by BrainDamage** [comment]
Is it possible to disable such optimization? I understand it'll come at a performance loss, however buffer scrollback integrity is a  necessity on some of the terminals I use tmux with; in particular, ssh clients on touchscreen devices where sending keystrokes is always a pain ( which makes tmux's own scrollback buffer pretty hard to operate ), yet terminal's buffer history access is easily available trough gestures

**Comment by nicm** [comment]
No it isn't

**Comment by nicm** [comment]
Well you could disable it by changing the code, there is a function something like pane_is_big or region_is_large in tty.c. Make it always return 0. But tmux has NO control over what the terminal puts in its scrollback so it will not necessarily be complete after this.
