### ISSUE TITLE
./configure fails while building tmux on syntax error

### ISSUE THREAD

**Issue by ygeo** [tmux/tmux#890]
uname -a
Linux tendenta 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

git clone git@github.com:tmux/tmux.git
cd tmux

git tag | sort -nr | head -n 1
2.4

sh autogen.sh

./configure 
: 
.... 
checking for setproctitle... no
checking for strcasestr... yes
checking for strlcat... no
checking for strlcpy... no
checking for strndup... yes
checking for strsep... yes
checking for strtonum... no
checking for working strnlen... yes
checking for library containing clock_gettime... none required
./configure: line 5156: syntax error near unexpected token `newline'
./configure: line 5156: `PKG_CHECK_MODULES('

**Comment by nicm** [comment]
You need to install pkg-config.

**Comment by sivareddyforu** [comment]
The issue still persists even after installing pkg-config. Has anyone got a solution?

**Comment by sivareddyforu** [comment]
Sorry it worked for me now.

Install
sudo apt-get install pkg-config

Once installed, run below once again
sh autogen.sh

Then
./configure && make

**Comment by andradei** [comment]
@Mario253 Had the same issue.

Run `sudo apt install libevent-dev` then try again.
