### ISSUE TITLE
garbled pane content with e.g. color or certificate pictograms

### ISSUE THREAD

**Issue by mbunkus** [tmux/tmux#893]
Please see the following two screenshots. This is how tmux master looks after a simple `cat bad.txt` (which contains the output of `certtool -i bunkus.org-ca.pem`):

![screenshot_20170428_135436](https://cloud.githubusercontent.com/assets/414282/25527762/82cc94ec-2c1a-11e7-8936-d975d391e377.png)

Contrast with how it should and does look with tmux 2.3:

![screenshot_20170428_135511](https://cloud.githubusercontent.com/assets/414282/25527765/884770a4-2c1a-11e7-9b9e-622d2c0e8c21.png)

This affects other types of output, too, e.g. it happens when I use SaltStack to view documentation: `salt-call sys.doc file`.

How to reproduce:

  * download [this test file](https://www.bunkus.org/misc/tmux-causes-bad-output.txt)
  * start tmux
  * run `cat tmux-causes-bad-output.txt`, maybe multiple times as the output isn't consistent over multiple iterations, and observe the broken behavior

Information:

  * Arch Linux 64-bit, happens with Arch's own 2.4 package but also with a self-compiled tmux at revision e4b4125310b27ef8e33f7652eb5f96fe7e362515. Does not happen with Arch's 2.3 package, neither with a self-compiled 2.3
  * can be reproduced without any configuration (I've tested with `-f/dev/null` and no other tmux running)
  * I'm running konsole → ssh → tmux with `TERM=xterm-256color` outside of tmux at the moment, but I've also observed this behavior yesterday at home where I run Windows → putty → tmux with `TERM=putty-256color` outside of tmux.
  * [Log files from tmux (after having killed the server, of course)](https://gist.github.com/mbunkus/1525f135159e7ccf6e72337e42a7232a)

I've tried to bisect the problem but ended up somewhere where I cannot compile on Linux. Here's the bisect log until that point:

```
# bad: [e4b4125310b27ef8e33f7652eb5f96fe7e362515] source-file too.
# good: [52869ed182482c26163799a7215139f4d81b6fca] Release tmux 2.3
git bisect start 'master' '2.3'
# good: [3e495b4001889596ac6b148cffd1735343a1333e] compat/* should not include tmux.h.
git bisect good 3e495b4001889596ac6b148cffd1735343a1333e
# bad: [12c6c723a9dad969bc9865f7ecd76f3ea7251524] Merge branch 'obsd-master'
git bisect bad 12c6c723a9dad969bc9865f7ecd76f3ea7251524
# bad: [cb50a51127f02ea8cfe41152d35bcc27dffc83cf] Merge branch 'obsd-master'
git bisect bad cb50a51127f02ea8cfe41152d35bcc27dffc83cf
# good: [7417e391d5ab127adb6c598776547119f516bb7b] Merge branch 'obsd-master'
git bisect good 7417e391d5ab127adb6c598776547119f516bb7b
# good: [a9a0039be4fafb1d6772a1c844a95eb744d922a0] Merge branch 'obsd-master'
git bisect good a9a0039be4fafb1d6772a1c844a95eb744d922a0
# skip: [2f854969ff8dfea7b03b6534318a64f51e9c65e7] Do not adjust region lower by pane offset when scrolling up, it is already an absolute position.
git bisect skip 2f854969ff8dfea7b03b6534318a64f51e9c65e7
# skip: [1811dc5271f5c47f71ddf259adf038d271d0c555] Another helper function to write to terminal and log.
git bisect skip 1811dc5271f5c47f71ddf259adf038d271d0c555
# skip: [1811dc5271f5c47f71ddf259adf038d271d0c555] Another helper function to write to terminal and log.
git bisect skip 1811dc5271f5c47f71ddf259adf038d271d0c555
# good: [e09625e38b361b8ce0b8fa88851f447144f1a718] Merge branch 'obsd-master'
git bisect good e09625e38b361b8ce0b8fa88851f447144f1a718
# bad: [130b77edc737fcd113964fd77123285d78dfe3f9] Merge branch 'obsd-master'
git bisect bad 130b77edc737fcd113964fd77123285d78dfe3f9
# skip: [13a0b6bb3fe05454cace81f5ec7624f6fd9021a5] Collect sequences of printable ASCII characters and process them together instead of handling them one by one. This is significantly faster. Sequences are terminated when we reach the end of the line, fill the internal buffer, or a different character is seen by the input parser (an escape sequence, or UTF-8).
git bisect skip 13a0b6bb3fe05454cace81f5ec7624f6fd9021a5
# skip: [d4b006b9faf001de41560db2e8fb890c654598e2] Fix clear start of line.
git bisect skip d4b006b9faf001de41560db2e8fb890c654598e2
# skip: [e100d465daefd20da0bb5eea87c4b4896badff16] Add support for scroll up escape sequence (CSI S) and use it when possible instead of sending individual line feeds.
git bisect skip e100d465daefd20da0bb5eea87c4b4896badff16
# skip: [7475165cd87d443da34da11298e638d3d17f43e9] Some other tidying bits.
git bisect skip 7475165cd87d443da34da11298e638d3d17f43e9
# skip: [05802a6fe309e3b4559286ca5ce3c51f7367d661] window_copy_pagedown shouldn't reset the mode anymore, instead let the caller do it so it can free the marks. Problem reported by attila at stalphonsos dot com.
git bisect skip 05802a6fe309e3b4559286ca5ce3c51f7367d661
# skip: [ac1f294bb930a0c05f96197b6a53b883ebc483f2] Add a helper to store a cell, and some tidying.
git bisect skip ac1f294bb930a0c05f96197b6a53b883ebc483f2
# only skipped commits left to test
# possible first bad commit: [130b77edc737fcd113964fd77123285d78dfe3f9] Merge branch 'obsd-master'
# possible first bad commit: [05802a6fe309e3b4559286ca5ce3c51f7367d661] window_copy_pagedown shouldn't reset the mode anymore, instead let the caller do it so it can free the marks. Problem reported by attila at stalphonsos dot com.
# possible first bad commit: [e100d465daefd20da0bb5eea87c4b4896badff16] Add support for scroll up escape sequence (CSI S) and use it when possible instead of sending individual line feeds.
# possible first bad commit: [13a0b6bb3fe05454cace81f5ec7624f6fd9021a5] Collect sequences of printable ASCII characters and process them together instead of handling them one by one. This is significantly faster. Sequences are terminated when we reach the end of the line, fill the internal buffer, or a different character is seen by the input parser (an escape sequence, or UTF-8).
# possible first bad commit: [d4b006b9faf001de41560db2e8fb890c654598e2] Fix clear start of line.
# possible first bad commit: [7475165cd87d443da34da11298e638d3d17f43e9] Some other tidying bits.
# possible first bad commit: [ac1f294bb930a0c05f96197b6a53b883ebc483f2] Add a helper to store a cell, and some tidying.
```

**Comment by nicm** [comment]
Good bug report, thanks!

This doesn't happen in xterm or gnome-terminal, but I can reproduce in konsole. It seems to be a bug in konsole's implementation of the CSI S escape sequence (SU, scroll up).

It looks like if the number of lines to scroll is more than the size of the scroll region, konsole will incorrectly ignore the sequence rather than scrolling as much as it can.

Compare this in xterm versus konsole:
~~~~
printf '\033#8\033[10;15r\033[10S'
~~~~
But this works fine:
~~~~
printf '\033#8\033[10;15r\033[5S'

**Comment by nicm** [comment]
You can do this in .tmux.conf to work around this problem:

set -as terminal-overrides ',*:indn@'

Or we can work around it in tmux itself with something like this [a.diff.txt](https://github.com/tmux/tmux/files/964437/a.diff.txt).

But you should probably report this to the Konsole developers.

**Comment by mbunkus** [comment]
Thanks for looking into this so quickly. I highly appreciate it.

It's not just konsole, it's putty, too.

I can confirm that both of your workarounds work with konsole. I'll test with putty later tonight.

**Comment by mbunkus** [comment]
Both methods work fine with putty, too, though now I'm having difficulties reproducing the original problem with putty. Therefore I'm actually doubting my earlier statement that putty's faulty, too.

I'm going to file a bug report for konsole as I do believe in fixing bugs at the source instead of using workarounds elsewhere. That being said, I'd appreciate your patch being committed, mostly because I don't consider it being that much of a workaround. According to the comment in the code tmux is now limiting the number of lines to scroll to the number of visible lines (or something like that), and that sounds to me like the correct thing to do in the first place. I guess there's no formal specification about how terminal emulators must work regarding scroll commands; they're all just trying to do what the user probably expects.

But that's arguing finer points of semantics; so I wouldn't be disappointed if you refused to fix something that may not actually be tmux's fault.

Again, thanks for such a timely investigation, the workaround, the fixes.

**Comment by nicm** [comment]
The spec is what DEC terminals did (and what xterm does), Konsole is wrong
here

**Comment by mbunkus** [comment]
I stand corrected.

I've just filed a report [for konsole](https://bugs.kde.org/show_bug.cgi?id=379318).

**Comment by nicm** [comment]
I think I will apply the patch to tmux, even if Konsole fix it there will
still be old versions around and it isn't a big change.

**Comment by nicm** [comment]
Applied now, thanks!

**Comment by nicm** [comment]
I reverted this change because it is not right. Konsole ignores scrolling exactly the height of the region as well, and we need to be able to do that/

**Comment by mbunkus** [comment]
Just today a [patch](https://bugs.kde.org/show_bug.cgi?id=379318#c1) was posted for konsole that works well for me with tmux 2.4 and without any workaround. So here's to hoping it'll be fixed on konsole's end soon.
