### ISSUE TITLE
Tmux 2.4-1 right prompt gets scrambled

### ISSUE THREAD

**Issue by leandro19** [tmux/tmux#894]
Please read https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING

Hi,

I am running Arch linux and since upgrading to tmux version 2.4-1 from 2.3-1 my right powerline prompt seems to be getting scrambled whenever I open tmux. The problem goes away whenever I reload .tmux.conf or enter copy mode, but when I issue the next command it shows up again. I've attached some screenshots for better understanding. I'm using oh-my-zsh with powerlevel9k theme. I use gnome-terminal, and my $TERM outputs "xterm-256color" both in and out of tmux. When I open the terminal without tmux, this issue is not apparent.

Here is my output of "uname -sp && tmux -V && echo $TERM", for reassurance:
[settings.txt](https://github.com/tmux/tmux/files/964823/settings.txt)

Here is my .tmux.config file (I tried uncommenting setting the terminal to 256 colors but it changed nothing):
[tmux.txt](https://github.com/tmux/tmux/files/964831/tmux.txt)

When I first open tmux:
![screenshot from 2017-04-28 11-31-20](https://cloud.githubusercontent.com/assets/22228427/25537039/f1da099c-2c0a-11e7-8c39-efb0509dad9a.png)

When I enter copy mode or reload my config file the problem goes away:
![screenshot from 2017-04-28 12-04-27](https://cloud.githubusercontent.com/assets/22228427/25537058/02c45cbc-2c0b-11e7-8080-5e21bd875b51.png)

**Comment by nicm** [comment]
TERM of xterm-256color is wrong inside tmux.

**Comment by leandro19** [comment]
I changed my .zshrc file to be xterm-256colors when not running tmux, and screen-256colors when running tmux, but the right prompt problem persists.

**Comment by nicm** [comment]
Does this still happen with master? There was a bug with UTF-8 characters.

**Comment by leandro19** [comment]
I initially had tmux installed from the arch package manager, but I suppose it still had the UTF-8 character bug. I now installed it from here and the bug is fixed. Thank you :)
