### ISSUE TITLE
Feature detection with `%if`

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#896]
Just taking 2.4 for a spin and trying out the new conditional config feature. Very happy to see this feature added and it is a great start.

I think one big use case here is feature detection; that is, using a single `.tmux.conf` on multiple machines and having it work gracefully on all of them regardless of what tmux versions they're using.

At the moment, it is easy to gate on a specific version:

```
%if #{==:#{version},2.5}
# Do a thing that only 2.5 supports.
%endif
```
(Obviously, doesn't help you if you are on a version older than 2.4, but eventually we'll move past this phase.)

However, we don't appear to have an `%else` construct, so we can't even do simple things like:

```
%if #{==:#{version},2.5}
# Do a thing that only 2.5 supports.
%else
# Do a fallback thing.
%endif
```

Instead, we have to workaround like so:

```
# Do a default thing.

%if #{==:#{version},2.5}
# Do a thing that only 2.5 supports, overriding the default.
%endif
```

In the absence of a version-aware `>` or `<` or `>=` or `<=` format (ie. `#{>:a,b}` etc), if we want to detect something like "2.5 or 2.6", we have to resort to nested ternaries like:

```
%if #{?#{==:#{version},2.6},1,#{==:#{version},2.5}}'
# ...
%endif
```

And it will get nastier with each new release that has to be added to the range.

What we really want, perhaps, is a sort of feature detection. This won't allow us to detect breaking syntax changes (like the recent reworking of key tables), but it would allow us to check for newly added features. Would work like this:

```
%if #{has:search-forward-incremental}
# Set up incremental search binding.
%endif
```

Anyway, just wanted to put this out there as a bit of food for thought. Thanks for reading.

**Comment by nicm** [comment]
We're not going to have feature detection.

You can do else using !=.

I'd be OK with having %else and other comparison operators (< and >).

**Comment by nicm** [comment]
I've added %else and <> to the TODO file, thanks.
