### ISSUE TITLE
Everything Turns into Gibberish

### ISSUE THREAD

**Issue by xanderdunn** [tmux/tmux#90]
Periodically, while using neovim in tmux, I see all text displayed in tmux turn into garbage: 
<img width="1440" alt="screen shot 2015-08-22 at 12 06 26" src="https://cloud.githubusercontent.com/assets/1313618/9425460/3af47e20-48c6-11e5-8bc5-1f25682bff7b.png">

This output looks similar to what's seen in #43.  

It happens in both the Mac's built-in Terminal app, as well as iTerm.  It always seems to happen when I'm in neovim.  I haven't tried using vim as I don't have it configured at all to use as my editor.  Once it's happened, the problem persists even after quitting neovim: 
<img width="1440" alt="screen shot 2015-08-22 at 12 11 53" src="https://cloud.githubusercontent.com/assets/1313618/9425478/ff68a6e6-48c6-11e5-8eb3-e79bc753defb.png">
The only way around it is to completely kill the tmux server and then restart it.  

Mac OS 10.10.4.  tmux 2.0 installed via Homebrew.

neovim :ver: 
```
NVIM 0.0.0-alpha+201508201245 (compiled Aug 20 2015 16:33:58)
Commit: f253c8d9b4ab0b31ce0d9a6a1b60428785d93d50
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovi
m20150820-50685-4mm35x/build/config -I/tmp/neovim20150820-50685-4mm35x/src -I/tmp/neovim20150820-50685-4mm35x/deps-build/usr/include -I/tmp/neovim20150820-50685-4mm35x/deps-build/usr/include -I/tmp/neovim
20150820-50685-4mm35x/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20150820-50685-4mm35x/deps-build/usr/include -I/tmp/neovim20150820-50685-4mm35x/deps-build/usr/include -I/tmp/neovim20150820-50685-4mm3
5x/deps-build/usr/include -I/tmp/neovim20150820-50685-4mm35x/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim20150820-50685-4mm35x/build/src/nvim/auto -I/tmp/neovim2015
0820-50685-4mm35x/build/include
Compiled by admin@Xander-Dunns-MacBook-Pro.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

I've seen this occurring for a number of months now.  It's not very new.

**Comment by ThomasAdam** [comment]
So try to find out what escape sequences, etc., neovim might be sending.

**Comment by xanderdunn** [comment]
@ThomasAdam Thanks.  How might I go about this?  I'm not familiar with sending escape sequences.

**Comment by nicm** [comment]
Try tmux from git please, I think this may have been fixed.

**Comment by xanderdunn** [comment]
@nicm Although, thanks.  I've got tmux installed and running from HEAD on master branch.  Let's see if it reproduces now.

**Comment by xanderdunn** [comment]
I've been working in tmux built from HEAD all day and this hasn't happened. :+1: Thanks!  

On an unrelated note, in this more recent version of tmux I'm told that these options can't be found on startup: mode-mouse, mouse-select-pane, mouse-resize-pane, and mouse-select-window.  Have they changed?

Indeed, my mouse doesn't work.
