### ISSUE TITLE
tmux new session won't start on my Ubuntu server 16.04.2

### ISSUE THREAD

**Issue by Benqzq** [tmux/tmux#900]
I have a freshly installed Ubuntu server 16.04.2 and tmux 2.1. When tmux **isn't running** (i.e when I'm in a regular session) I ran the following tmux heredocument which I use to download, install, use, and delete certain programs in a timeout in the background:

```
(
cat > /dev/shm/my_script.sh && 
chmod +x /dev/shm/my_script.sh && 
tmux new-session -d '/dev/shm/my_script.sh; rm /dev/shm/my_script.sh'
) <<-'EOF'
	# apt-get install utility
        sleep 5h
        # apt-get purge utility
EOF
```

In this new system, the heredocument fails to work - I run it and it seems to have been runned successfully but nothing changes in the system - No tmux session will start and no utility will be installed.

I would thank you dearly for your opinion on this.

**Comment by nicm** [comment]
Is the new install the same tmux version?

**Comment by Benqzq** [comment]
Yes, both environments (two different remote machines) are with tmux 2.1.

**Comment by nicm** [comment]
I guess something must be running tmux at startup, you should probably try
to figure out what that is.

**Comment by Benqzq** [comment]
I made sure tmux won't start in reboot, and indeed it doesn't start wit the system. I am in a regular session and `tmux ls` brings:

> no server running on /tmp/tmux-0/default

Yet, when I run the heredocument above on the new server, nothing happens. It's just doesn't work though the code is valid.

**Comment by nicm** [comment]
what if you do:

tmux new-session -d '/dev/shm/my_script.sh; rm /dev/shm/my_script.sh; sleep 1000'

**Comment by Benqzq** [comment]
In this case a session does created.

**Comment by nicm** [comment]
Right... and if you attach, do you see an error message from your script?

**Comment by Benqzq** [comment]
Indeed, that's all I see when I attach:

> bash: /dev/shm/my_script.sh: No such file or directory
> rm: cannot remove '/dev/shm/my_script.sh': No such file or directory

**Comment by nicm** [comment]
Apparently your script doesn't work then or it is running before /dev/shm
is mounted.

**Comment by Benqzq** [comment]
I can swear the script is fine as I checked each command separately. What you say about executing it before /dev/shm is mounted, is interesting. Allow me to have your take on this for the last time, please, as I'm new to Linux: Is a situation when /dev/shm isn't mounted on bootstrap seems plausible to you? As far as I know this is not natural, and it might be part of a bigger problem.

**Comment by nicm** [comment]
So what happens if you don't use /dev/shm and write the script in /tmp or /root?

**Comment by nicm** [comment]
This does seem like something you could do more sensibly with

**Comment by nicm** [comment]
This does seem like something you could do more sensibly with at rather than tmux TBH.

**Comment by Benqzq** [comment]
Sadly, nothing happens when I change all relevant `/dev/shm/` to `/tmp/` or `/root/`. I had trouble doing this with `at`. For 6 months tmux worked for me the best and should work now. I will further check what is going on (and will be glad to update here). Thanks!

**Comment by Benqzq** [comment]
It's not executed in /tmp or /root. I prefer not to use `at`... 

I now notice the exact problem is this:

The script can be executed when I do `cd /dev/shm` but when I'm out of this mounted device, it won't be executed. 

This behavior is new - I didn't experience it before. Can you please try explain it? It could help me much...

**Comment by nicm** [comment]
I don't know. Perhaps you should pick a way to do this that is easier for you to trouble shoot.

**Comment by Benqzq** [comment]
This the easiest way I know and the only one I wish to use. Sorry for not updating (planned to do so later today), but I've found why I didn't work and I also made a slight change to the script, [for those who want to expand](https://unix.stackexchange.com/questions/362354/tmux-script-works-only-inside-dev-shm).
