### ISSUE TITLE
rotate-window unzooms pane

### ISSUE THREAD

**Issue by caedn** [tmux/tmux#901]
__behaviour__
Using `rotate-window` while zoomed into a pane unzooms and then rotates.

__expected behaviour__
Rotate the panes without unzooming, which is how it used to work.

```
Darwin i386
tmux master (latest head)
screen-256color
```

**Comment by nicm** [comment]
This is intentional and matches many other commands. You can zoom again by doing

rotatew; resizep -Z

**Comment by iasj** [comment]
It didn't work for me. In tmux 2.3 I used to to like the following:
```
>>>cat .tmux.conf | grep rotate
bind   -rn   M-r        rotate-window     -D
```

and then I did
```
bind   -rn   M-r        rotate-window     -D; resizep -Z
```
and yet it doesn't do full screen again.

**Comment by CallumHoward** [comment]
maybe you need to escape the `;`, so
```bind   -rn   M-r        rotate-window     -D\; resizep -Z```

**Comment by CallumHoward** [comment]
My workflow relies on the old behaviour, I would like a way to restore this behaviour. The following does not work, it zooms the pane without rotating.
```bind 'C-o' rotate-window\; resize-pane -Z```
however even if this did work, it doesn't restore the previous behaviour of rotating and zooming if and only if the current pane is zoomed. Please consider reopening this issue.

**Comment by nicm** [comment]
It should work, I'll check when I get home in a few days. It is not
changing back.

You can make the resize or rotate conditional with if-shell.

**Comment by iasj** [comment]
Yes, it doesn't work like expected. The command:
`bind -rn M-r rotate-window -D\; resizep -Z`

zoom into the selected pane if it is not zoom, and it doesn't rotate at all. If it is zoomed, still doesn't rotate. I'll downgrade to 2.3 and wait, once my workflow also relies on that. Thanks for reopening.

**Comment by nicm** [comment]
Please try this diff: [x.diff.txt](https://github.com/tmux/tmux/files/981927/x.diff.txt)

Should fix doing something like this:
~~~~
$ tmux bind o rotatew \\\; resizep -Z

**Comment by nicm** [comment]
Applied this.

**Comment by CallumHoward** [comment]
For anyone who finds this issue from Google: `bind 'C-o' rotate-window\; resize-pane -Z` now works nicely for me.

**Comment by dalbertom** [comment]
I set mine to the following so it only zooms if the window was previously zoomed.

```
bind 'C-o' if-shell 'test #{window_zoomed_flag} -eq 1' 'rotate-window; resize-pane -Z' 'rotate-window'
```

**Comment by iasj** [comment]
@dalbertom, you saved my life pal, tnks!
