### ISSUE TITLE
Key binding for instant copy-mode search stopped working after upgrade to 2.4

### ISSUE THREAD

**Issue by imomaliev** [tmux/tmux#902]
tmux: 2.4
os: Linux Mint 17.2 Rafaela

My binding for instant copy-mode search stopped working(worked on 2.3)
```
bind / copy-mode \; send-keys ?
```

I tried 
```
bind / copy-mode \; send-keys -X ?
bind / copy-mode \; send-keys -X search-backward
bind / send -X search-backwards
bind / copy-mode \; command-prompt -p'search up' "send -X search-backward-incremental '%%'"
```

Is it even possible to have such binding in current version of tmux?

**Comment by nicm** [comment]
search-backward not search-backwards

**Comment by imomaliev** [comment]
@nicm yes, you are correct that was a typo

**Comment by nicm** [comment]
You need -T

**Comment by imomaliev** [comment]
@nicm but if I add -T it would become binding for copy-mode. I want to create binding that will start search after I press `prefix+/`.

**Comment by nicm** [comment]
Oh right, doh. I have this binding which is probably what you want (tmux
lsk will show you the existing bindings so you can base it off that):

bind-key C-r copy-mode\; command-prompt -ip "search up" "send -X search-backward-incremental '%%%'"

**Comment by nicm** [comment]
great
