### ISSUE TITLE
[fixed in master?] tmux 2.4 introduces extra newlines when copying long text

### ISSUE THREAD

**Issue by oconnor663** [tmux/tmux#903]
[I got all the way through writing this up before I checked master, and it turns out it doesn't repro. So maybe it's fixed!? Filing anyway just to make sure the fix was deliberate :) ]

- Arch Linux
- gnome-terminal (TERM = xterm-256color)
- bash, vanilla config
- tmux 2.4, no config (TERM = screen) (does not repro on 2.3 [edit: or on master e354b0e40fe1be1e1f8977d424e02e6487039a56])

Here's a screenshot of what I _was_ able to do on 2.3. I could echo a big blob of text, copy the output back from the terminal (shift-leftclick-drag to highlight, ctrl-shift-c to copy), paste in into another echo command (ctrl-shift-v), and get the same result:

![image](https://cloud.githubusercontent.com/assets/860932/25621984/03012a20-2f21-11e7-9afb-4d696a0a49b4.png)

Now with 2.4, the copy step receives text with extra newlines in it:

![image](https://cloud.githubusercontent.com/assets/860932/25622019/261db956-2f21-11e7-88b9-f6d7917a726c.png)

Here the effect of the newlines is that bash thinks I've entered multiple commands, but you can also see them by resizing the terminal, or by pasting the text you copy into any text editor. (So it's definitely something that happens on the copy step, not on the paste step.)

Note that the result isn't a newline for every visible line in the terminal. It's actually a newline for every _two_ visible lines. So in this example the word "nunc" is not split, even though it's at the end of the first line, but the word "accumsan" at the end of the second line does get split. This every-other-line pattern holds for longer inputs too.

**Comment by oconnor663** [comment]
Looks like the fix was d520dae6ac9acf980d48fbc8307ac83a5cee2938

**Comment by nicm** [comment]
Please let me know if you can reproduce in master.
