### ISSUE TITLE
tmux reuses SHELL environment variable from the first session in subsequent new sessions

### ISSUE THREAD

**Issue by steveeJ** [tmux/tmux#904]
```
$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 1.9
xterm-256color
```

This can be easily reproduced:
```
$ SHELL=$(which bash) tmux new -s bash
$ echo $SHELL
/bin/bash
CTRL+B+D
[detached (from session bash)]
$ SHELL=$(which sh) tmux new -s sh
$ echo $SHELL
/bin/bash
```

It would be nice if each session could use a different shell.

**Comment by nicm** [comment]
default-shell is a session option so you can have a different shell for each session if you want. We are not going to take SHELL from the environment for new sessions.

**Comment by steveeJ** [comment]
> default-shell is a session option so you can have a different shell for each session if you want.

Is it possible to set this option in the same command as new-session?

**Comment by nicm** [comment]
If you are starting a new sessions just do something like (untested)

tmux new exec $SHELL\; set default-shell $SHELL

**Comment by steveeJ** [comment]
> tmux new exec $SHELL; set default-shell $SHELL

If I omit the `exec` this works too, thanks!
