### ISSUE TITLE
Copy mode: cannot move cursor with C-b C-b

### ISSUE THREAD

**Issue by pharada** [tmux/tmux#905]
- macOS 10.12.4
- Apple Terminal
- `master` - e354b0e4
- `TERM=xterm-256color` outside, `TERM=screen` inside
- `./autogen.sh && ./configure --prefix=$HOME/lib/opt/tmux && make && make install`
- `$HOME/lib/opt/tmux/bin/tmux -L foo -f /dev/null new`

```
$ uname -a
Darwin sierrabox.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
```

**Expected:** In 2.3, assuming prefix is `C-b`, typing `C-b C-b` in copy mode moves the cursor left by one character.

**Actual:** Post-2.4, typing `C-b C-b` in copy mode does nothing. Unclear whether it is `send-prefix` or `send-keys` which is at fault. The default key bindings should allow this to work:

```
$ $HOME/lib/opt/tmux/bin/tmux list-keys | grep C-b
bind-key    -T copy-mode    C-b               send-keys -X cursor-left
bind-key    -T copy-mode-vi C-b               send-keys -X page-up
bind-key    -T prefix       C-b               send-prefix
```

If prefix is set to anything else (e.g. `C-a`), `C-b` moves the cursor normally in copy mode.

**Comment by nicm** [comment]
Yes this doesn't work anymore, prefix always wins.

**Comment by nicm** [comment]
We need send-keys/send-prefix to be aware of the mode key table.

**Comment by nabin-info** [comment]
It totally works for me ...

bind-key    -T prefix C-b     send-prefix

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/986446/x.diff.txt)

**Comment by Niwilai** [comment]
@nicm seems like the same issue. I've retested and `Ctrl+f` is working fine for scrolling a fullpage down so I will amend the title for my issue. Can you elaborate on why `Ctrl+b` prefix now takes preference over scrolling up in copy-mode?

**Comment by nicm** [comment]
send-keys doesn't work anymore because sending a key to copy mode is not enough, it needs to fire the key binding in the copy-mode table. Please try above patch.

**Comment by pharada** [comment]
Applied against f3221941, but `KEYC_XTERM` is not defined:

```
depbase=`echo cmd-send-keys.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"master\" -DPACKAGE_STRING=\"tmux\ master\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"master\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_BITSTRING_H=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_PATHS_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_UTIL_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_SYSCONF=1 -DHAVE_ASPRINTF=1 -DHAVE_CFMAKERAW=1 -DHAVE_FGETLN=1 -DHAVE_FPARSELN=1 -DHAVE_GETPROGNAME=1 -DHAVE_SETENV=1 -DHAVE_STRCASESTR=1 -DHAVE_STRLCAT=1 -DHAVE_STRLCPY=1 -DHAVE_STRNDUP=1 -DHAVE_STRSEP=1 -DHAVE_NCURSES_H=1 -DHAVE_B64_NTOP=1 -DHAVE_DAEMON=1 -DHAVE_DECL_OPTARG=1 -DHAVE_DECL_OPTIND=1 -DHAVE_DECL_OPTRESET=1 -DHAVE_GETOPT=1 -DHAVE_FORKPTY=1 -DHAVE___PROGNAME=1 -DBROKEN_CMSG_FIRSTHDR=1 -I.  -DTMUX_CONF="\"/etc/tmux.conf\"" -DDEBUG -iquote.      -I/usr/local/Cellar/libevent/2.1.8/include  -std=gnu99 -O2 -g -Wno-long-long -Wall -W -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wundef -Wbad-function-cast -Winline -Wcast-align -Wdeclaration-after-statement -Wno-pointer-sign -Wno-attributes -Wno-unused-result   -MT cmd-send-keys.o -MD -MP -MF $depbase.Tpo -c -o cmd-send-keys.o cmd-send-keys.c &&\
	mv -f $depbase.Tpo $depbase.Po
cmd-send-keys.c:72:24: error: use of undeclared identifier 'KEYC_XTERM'
        bd_find.key = (key & ~KEYC_XTERM);
                              ^
1 error generated.
make: *** [cmd-send-keys.o] Error 1
```

It is not defined anywhere in-tree nor can I find any similar definitions, so I assume something didn't make it into the patch.

**Comment by nicm** [comment]
Try again now please.

**Comment by pharada** [comment]
Works great, thanks! (applied on 4bcb64f8)

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub soon.
