### ISSUE TITLE
Create and swap pane in single keybind does not change active pane in 2.4

### ISSUE THREAD

**Issue by acehko** [tmux/tmux#908]
Arch Linux
Tmux 2.4

I have a config that allows me to create a new pane in the desired direction:
```tmux
bind h split-window -h -c '#{pane_current_path}' \; swap-pane -U
bind j split-window    -c '#{pane_current_path}'
bind k split-window    -c '#{pane_current_path}' \; swap-pane -U
bind l split-window -h -c '#{pane_current_path}'
```
When I press prefix-h, tmux creates a new pane on the right side, and then swaps them making it appear as if it was opened on the left. That also makes the left pane the active one.
After upgrading the pane on the left does not become active, instead the cursor stays in the right pane.

There is a workaround that works as intended:
```tmux
bind h run-shell "tmux split-window -h -c '#{pane_current_path}'; tmux swap-pane -U"
bind k run-shell "tmux split-window    -c '#{pane_current_path}'; tmux swap-pane -U"
```

**Comment by TheLocehiliosan** [comment]
@acehko Have you tried using the `-b` option for `split-window`? I think it was introduced in 2.0.
> The -b option causes the new pane to be created to the left of or above target-pane.

**Comment by nicm** [comment]
Does this work again in master?

**Comment by acehko** [comment]
@nicm I tried on master and it doesn't work. But I use the `-b` option now as @TheLocehiliosan suggested which works.
