### ISSUE TITLE
Can't make an app fullscreen, when run from tmux session, on Mac OS 10.10.5

### ISSUE THREAD

**Issue by ssreekanth** [tmux/tmux#91]
I see the following error message appearing on the tmux bash shell..

```
2015-08-23 04:15:30.150 MacVim[5700:3688585] Message error: Connection invalid
2015-08-23 04:15:30.160 MacVim[5700:3688585] ___createFullScreenMessageConnection_block_invoke: Fullscreen message error: Connection invalid
```

**Environment -**
* Mac OS 10.10.5
* tmux 2.0

**Steps to reproduce -**
* open tmux session
* run **mvim** (link to macvim application) from the shell in tmux. or any other Mac application.
* Now, try maximizing macvim app to go fullscreen.

I can not tell how it behaves on previous versions of Mac OS, as I do not have access to them.

When I run **mvim** from outside the tmux session, directly from the terminal window shell, it works fine as expected.

**Comment by nicm** [comment]
Probably something it needs in the environment that tmux doesn't update or goes out of date when you reattach. I suggest you ask the macvim people.

**Comment by ssreekanth** [comment]
I see the issue with other apps too, not just macvim..

Actually, I noticed the issue when I'm developing/testing my app on Mac OS. Then, just to make sure that it is not an issue with only my application, I tried other Mac apps (one of them is macvim) and noticed the same issue with them.

So, it is clearly an issue with tmux, unless I misunderstood something here..

**Comment by nicm** [comment]
You can try to figure out what these applications need that tmux is not providing on OS X.

-------- Original message --------

**Comment by cHoco** [comment]
The problem is described in detail here: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
Basically some services provided by OS X are only available to certain namespaces. Wrapping your shell  using reattach-to-user-namespace will fix the issue.
In your tmux.conf

```
set-option -g default-command "reattach-to-user-namespace -l zsh"
```

**Comment by ssreekanth** [comment]
Thanks @cHoco!! That solves my issue.
