### ISSUE TITLE
replacement for "bind-key -t vi-copy 'y' copy-selection" ?

### ISSUE THREAD

**Issue by bedge** [tmux/tmux#910]
What's the 'new' keybinding replacement for the following?
```
bind-key -t vi-copy 'y' copy-selection
```

Specifically, I have:
```
set-window-option -g mode-keys vi
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection
```

I'm not a tmux whiz, but it is embedded in my workflow and this is a blocking issue.

thanks in advance.

**Comment by bedge** [comment]
I've tried some of the new default bindings, ie:
```
bind-key    -T copy-mode-vi C-j               send-keys -X copy-selection-and-cancel
```
It does clear the selection highlight, but doesn't impact my clipboard at all.

I'm using:
```
reattach-to-user-namespace version 2.5
```
ie:
```
set -g default-command "reattach-to-user-namespace -l ${SHELL}"
```

**Comment by bedge** [comment]
This kinda works:
```
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe 'reattach-to-user-namespace pbcopy'
```

Except that it requires 'y' AND '<cr>' to copy.

**Comment by nicm** [comment]
Replacement for:
bind-key -t vi-copy 'y' copy-selection
Is:
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection

**Comment by bedge** [comment]
Perfect.
Thanks from all the tmux/vi-keymap users that only read the docs when stuff breaks and even then need help.

Just a thought - a migration doc may not be a bad thing when changes of this magnitude are released. I know the README had some info, but it was emacs specific and there's a lot more that's different now besides just the keymap stuff.

**Comment by rawaludin** [comment]
@bedge Is
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection

Will put yanked text to osx clipboard too?

Mine don't. 

I used this to put yanked text to osx clipboard too:
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe 'reattach-to-user-namespace pbcopy'

But the selection won't clear after I press `y`.

Any idea?

**Comment by delphinus** [comment]
You may use `copy-pipe-and-cancel` instead of `copy-pipe`.

But, if you only want to yank by tmux, you do not need `reattach-to-user-namespace`.

(And you should check on `Application in terminal may access clipboard` setting in iTerm2)

```
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
```

**Comment by bedge** [comment]
@rawaludin yeah, it's not working consistently. It worked right when I 1st tried it, but it's not now.

@delphinus I use my clipboard to transfer between apps, so I believe the `reattach-to-user-namespace` is needed.

**Comment by nicm** [comment]
I don't know what you are asking now, you're not providing enough
information.

**Comment by nabin-info** [comment]
FYI, the builtin `bind-key` commands are defined in `key-bindings.c`

**Comment by bedge** [comment]
Here's the final working config (that clears selection mode with 'y'):
```
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
```
Didn't pick up on the subtle hints 1st time around.

**Comment by asarbu** [comment]
I tried changing some bindings, but it doesn't seem to do anything.
```
bind-key -T copy-mode C-x send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi C-x send-keys -X copy-selection-and-cancel
```

When I select a text and hit `C-x`, nothing happens, but when I try `C-w` (default key binding) the text is copied and I can paste it using `C-b, ]`.

Can somebody help me figure this out ?

**Comment by rjhilgefort** [comment]
@bedge I'm not seeing what `copy-pipe-and-cancel` adds- my selection is cleared with just `copy-pipe`. What's the difference?

**Comment by bedge** [comment]
@rjhilgefort IIRC this was right after I upgraded to tmux 2.x
At the time, just using copy-pipe wasn't clearing selection. From your comment I expect this may have changed.

**Comment by sursh** [comment]
Yay thank you! And here's the command for begin-selection that's now working for me: 

`bind-key -T copy-mode-vi 'v' send-keys -X begin-selection`
