### ISSUE TITLE
Reduce border size (width)

### ISSUE THREAD

**Issue by istarukhin** [tmux/tmux#914]
I'm using

```
set -g window-style 'bg=default'
set -g window-active-style 'bg=#262626'
```
to highlight active pane and just same foreground for active/inactive borders
```
set -g pane-border-fg '#4d5057'
set -g pane-active-border-fg '#4d5057'
```
and I got this result
![result](https://i.stack.imgur.com/3FIyZ.png)
so, as you can see there is a big sized border, which has terminal default background and it looks awful, so im trying to find way to reduce border size in tmux to 1px or something like this.

Actually it looks like a padding but it's not, if we'll try to set border bg to red, for example, we'll get this result
![result](https://i.stack.imgur.com/wsCYk.png)

Output of
`uname -sp && tmux -V && echo $TERM`
command is 
```
Darwin i386
tmux 2.4
screen-256color
```
So, the question is: how to reduce border size to 1px or make border bg transparent (not default, which equals terminal bg), can't find any config setting for this.

Thank you.

**Comment by nicm** [comment]
Terminals do not work in pixels, they work in character cells. What you see
are the two possibilities for borders.

**Comment by istarukhin** [comment]
Got it, thanks, what about transparent bg, same impossible?

**Comment by nicm** [comment]
Default bg will be transparent if your terminal bg is transparent
