### ISSUE TITLE
Can not scroll page up in VI copy-mode with Ctrl+b

### ISSUE THREAD

**Issue by Niwilai** [tmux/tmux#917]
Hi there,
```
Darwin i386
tmux 2.4
screen-256color

setw -g mode-keys vi
```

I've updated my Tmux recently to v2.4 and I cannot jump page up and/or down with Ctrl+b and Ctrl+f in vi-copy-mode. Actually when I press either of them in copy-mode Tmux seems to be frozen.

Any known issue, is this not supported anymore?
Thanks

**Comment by nicm** [comment]
Is this the same as https://github.com/tmux/tmux/issues/905?
