### ISSUE TITLE
Request - please allow to merge two panes back together from same window

### ISSUE THREAD

**Issue by mdeguzis** [tmux/tmux#918]
- your platform: Linux
- a brief description of the problem with steps to reproduce; split a window into 4 panes, try to merge panel with the one next to it. Essentially "undo" a split.
- your terminal, and $TERM inside and outside of tmux; putty, xterm (outside), screen (inside)

I wish to merge 3 and 4 after 3 was split vertically or otherwise.
________
| 1  |  2 |
| 3  |  4 |

**Comment by nicm** [comment]
kill-pane?

**Comment by mdeguzis** [comment]
That just exists the pane. When you have different splits, you cannot merge offset panes. If the splits align, it'd be nice to be able to marge

On resize horizontal

|   1   |   2   |
|  3  |    4    |

If the vertical div aligns..

|   1   |   2   |
|   3   |   4   |

Allow merge 3 and 4 for:

|   1   |   2   |
|        3       |

**Comment by nicm** [comment]
What's the difference between killing a pane, which will merge the empty space with another, and what you are describing?

**Comment by mdeguzis** [comment]
If you start with a horizontal line, then split vertical on the top half, yes that works. However, this scenario does not work.

```
|   1   |   2   |

divide pane two to create 3

|   1   |   2   |
|   1   |   3   |

divide 1 to get 4

|   1   |   2   |
|   4   |   3   |

Try to merge 4 and 3 to this:

|   1   |   2   |
|        3       |
```

That last part cannot be done (at least that I can tell). Which means, if you didn't rearrange first, or pre-plan with a horizontal divide first instead of vertical, you can't make it work. I work around this by PREFIX+SPACE to jumble things, then PREFIX+ [ or ] to swap the panes around.

**Comment by nicm** [comment]
OK, added to TODO file, thanks.
