### ISSUE TITLE
FreeBSD pane_current_path

### ISSUE THREAD

**Issue by mipko** [tmux/tmux#919]
Hello,

There seems to be an issue with FreeBSD and pane_current_path command. On FreeBSD it returns **NULL**. I was tracing the problem and it fails in a call to 
`kinfo_getfile(pgrp, &nrecords)`
The call to **osdep_getcwd** tries **_sysctl_** first, and than reverts to the **osdep_get_cwd_fallback** which uses **kinfo_getfile**.

Is there any work around regarding this issue? 

best regards
Mirko

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by mipko** [comment]
Hello,

Many thanks for your prompt response. Here are the needed details:

***issue description**: On FreeBSD 11 x86 64bit, pane_current_path returns empty string instead of current pane path. Issue is not related to the tmux configuration. Even empty config returns such behavior. The reason for this is the fail of sysctl and kinfo_getfile call in osdep_getcwd and osdep_getcwd_fallback respectively.

* **tmux version** - 2.4

* **output of uname -a** 

`FreeBSD f12 11.0-RELEASE-p9 FreeBSD 11.0-RELEASE-p9 #0: Tue Apr 11 08:48:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64`

***tmux.config** - it is reproducable with any config, here is example of minimal config
```
set -g mouse on

run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux

set -g @resurrect-strategy-vim 'session'
set -g @resurrect-save-command-strategy 'ps'
set -g @resurrect-capture-pane-contents 'on'
```
* **TERM** in tmux and outside tmux = xterm-256color

***steps to reproduce it**
- it is enough to execute display-message -F \"#{pane_current_path}\" -t0 and you won't get current path on FreeBSD 11. Due to this issue tmux-resurrection is not working and auto rename of windows is not working. Other tmux functionality is OK.

***screenshots** - nothing meaningful to display related to this issue.

***logs**, currently unavailable.

I will try to debug it as well as soon as I get home.

Best regards,
Mirko

**Comment by nicm** [comment]
Why isn't KERN_PROC_CWD being used? Is it returning ENOENT? Was it added after FreeBSD 11?

**Comment by mipko** [comment]
I just finished debugging, it actually calls KERN_PROC_CWD and gets an EPERM error (1). It never tries fallback method.

I have made a debug purpose code that returns error tag, PID and error code.
There is screenshot attached. The same behavior is experienced with example conf provided with source code.

```
#ifdef KERN_PROC_CWD
char *
osdep_get_cwd(int fd)

...
...
if ((name[3] = tcgetpgrp(fd)) == -1)
    return ("FBSD_E0");

if (sysctl(name, 4, &info, &len, NULL, 0) == -1) {
    if (errno == ENOENT) {
        fallback = 1;
        return (osdep_get_cwd_fallback(fd));
    }
    char *errstr = (char*)malloc(255);
    memset(errstr, 0, 255);
    sprintf(errstr, "FBSD_E1 PID: %d errorcode %d", name[3], errno); 
    return (errstr); //code ends up here with EPERM (1) errorcode
}
...
...
```
* screenshots

PID of external tmux process I presume got EPERM 

![t4](https://cloud.githubusercontent.com/assets/11368206/25921016/294b4fda-35d4-11e7-8e6b-1ec78d5ee4da.png)

![t5](https://cloud.githubusercontent.com/assets/11368206/25921031/32944c0e-35d4-11e7-8756-12186c66346c.png)

**Comment by nicm** [comment]
So did FreeBSD change it that KERN_PROC_CWD is only allowed as root?

What if you use the fallback for EPERM as well as ENOENT?

**Comment by mipko** [comment]
same thing. I have forced fallback method and got EPERM as well
```

if ((info = kinfo_getfile(pgrp, &nrecords)) == NULL) {
        char *errorstr = (char*)malloc(255);
        memset(errorstr, 0, 255);
        sprintf(errorstr, "FBSD_fallback checkP_2, PID: %d errorcode %d", pgrp, errno);
        return (errorstr);
    }
```
PID : 84379 belongs to -zsh(zsh)

![t6](https://cloud.githubusercontent.com/assets/11368206/25923086/287ec84a-35dc-11e7-8278-331ca7349852.png)

**Comment by nicm** [comment]
Well if this is not allowed on FreeBSD then we can't do it.

On 10 May 2017 10:56 pm, "mipko" <notifications@github.com> wrote:

same thing. I have forced fallback method and got EPERM as well


if ((info = kinfo_getfile(pgrp, &nrecords)) == NULL) {
        char *errorstr = (char*)malloc(255);
        memset(errorstr, 0, 255);
        sprintf(errorstr, "FBSD_fallback checkP_2, PID: %d errorcode
%d", pgrp, errno);
        return (errorstr);
    }

PID : 84379 belongs to -zsh(zsh)

[image: t6]
<https://cloud.githubusercontent.com/assets/11368206/25923086/287ec84a-35dc-11e7-8278-331ca7349852.png>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/919#issuecomment-300624556>, or mute
the thread

**Comment by mipko** [comment]
I totally agree. I will let you know, if I come up with something. Thanks for helping me with this one.
cheers,
Mirko

**Comment by nicm** [comment]
It would be helpful to find out if this was an intentional change and why
it was made, and what the recommend way to enable it is.

**Comment by mipko** [comment]
It works OK as root.
