### ISSUE TITLE
bug with printf and unicode

### ISSUE THREAD

**Issue by kovetskiy** [tmux/tmux#920]
1. start xterm session with bash (empty bash config)
```
xterm -e bash
```
2. Enter command:
```
 printf '%s\r%s\n' 'w' 'ц'
```
you will see (unicode letter):
```
ц
```
3. Start fresh tmux session:
```
    tmux -Ltest kill-server
    tmux -vvvv -Ltest -f/dev/null new /bin/bash
```
4. Enter command:
```
printf '%s\r%s\n' 'w' 'ц'
```
expected to see (unicode letter):
```
ц
```
actual result:
```
w
```

tmux -V
```
tmux 2.4
```
(and reproduced with tmux master)

uname -na:
```
Linux laptop 4.10.11-1-ARCH #1 SMP PREEMPT Tue Apr 18 08:39:42 CEST 2017 x86_64 GNU/Linux
```
uname -sp:
```
Linux unknown
```

tmux server log https://gist.github.com/kovetskiy/ebd64540fd49bcde1417f54c5210267f

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by seletskiy** [comment]
@nicm: Everything OK with master.

**Comment by kovetskiy** [comment]
@nicm: nope, ok with master
