### ISSUE TITLE
output for lines with utf8 chars sometimes gets truncated

### ISSUE THREAD

**Issue by parcs** [tmux/tmux#921]
**Version**: master @ 1cdc4568
**Platform**: linux
$TERM inside tmux is screen-256color
$TERM outside is xterm-256color

**Description**: When I run the following command and I scroll down using 'd', some of the lines read "Franç" instead of "François".

`for i in $(seq 1 100); do echo "François\n"; done | less`

**Comment by nicm** [comment]
Works for me. What terminal are you using? Get some tmux logs?

**Comment by parcs** [comment]
I'm using gnome terminal and connecting remotely via mosh to another computer.  Now that you mentioned it, I just tried using ssh instead and the problem goes away.  So it looks like it may be a bug in mosh, sorry for the noise.
