### ISSUE TITLE
tmux 2.4 disables paste in vim

### ISSUE THREAD

**Issue by timothysm** [tmux/tmux#923]
I recently updated tmux to 2.4. I am able to "yank" while in editing a file in vim, but I am unable to paste. When I try to I get the following tmux message:  "E353: Nothing to register * " 

Running MacOS Sierra 10.12.4 in Terminal

**Comment by nicm** [comment]
That's not a tmux message

**Comment by timothysm** [comment]
Sorry! My .tmux.conf got rewritten and wasn't calling reattach-to-user-namespace, this fixed the problem.

Cheers
