### ISSUE TITLE
Add styling for search highlight/current position/line indicator in copy mode

### ISSUE THREAD

**Issue by jfelchner** [tmux/tmux#929]
Now that we have the ability to highlight our searches (this is amazing! ❤), would it be possible to add the ability to style:

* the search highlight
* the highlight where the cursor currently is

Bonus:

* the upper right display showing the result count/line position

Thank you!

**Comment by jfelchner** [comment]
Specifically the fact that it's yellow makes it very difficult to see the current cursor position.

**Comment by nicm** [comment]
I don't want a bunch of different options for this and I don't really see a need for them. There is only ever one significant use of mode-style on screen at a time. You can't have a selection and search highlights at the same time, and the line indicator doesn't take up much room and is in a fixed position so it is hardly confusing.

If your cursor colour and mode-style mean it is difficult to see, perhaps you should change one or the other - but you can already do that?

**Comment by jfelchner** [comment]
@nicm what I'm specifically needing is a way to visually see which search term is the one I'm actively on. 

Secondarily maybe I'm missing an option that's already there. Is there a way to change the yellow search color to something else? I searched all through the man page but couldn't find anything.

**Comment by nicm** [comment]
mode-style is the colour.

**Comment by jfelchner** [comment]
@nicm perfect! Let me try that! I'll close this for now.
