### ISSUE TITLE
A window_flags to show a window contains multiple panes?

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#93]
If multiple windows in one session, and one of the windows contains multiple panes and you have one of the panes zoomed, there will be a letter `"Z"` which is a `window_flags` (I can see other `window_flags` from `man tmux`) appended to the `window_name` indicating that one of the panes in that window is zoomed, but it seems there is no flag existed to indicate that one window contains multiple panes instead of one.

Is there other solution that I can see that if the window contain multiple panes? If the answer is no, is there any plan for creating this `window_flags`?

**Comment by ThomasAdam** [comment]
This is what #{window_panes} is for.

**Comment by c02y** [comment]
`#{window_panes}` will show the number even if there is only one pane, but I want the number appended to the `window_name` if the `window_panes` is more than 1.

**Comment by nicm** [comment]
Try:

#([ #{window_panes} -gt 1 ] && echo #{window_panes})

**Comment by c02y** [comment]
>Try:
>
>#([ #{window_panes} -gt 1 ] && echo #{window_panes})

It doesn't work, for example, this is what I want:

    1: less-<3> 2:man* 3:vim

the Window 1 contains 3 panes and it is the last visited window (symbol -), Window 2 is the current visited window (symbol *), the current one does not have to contains the panes number even if it contains panes more than 1, Window 3 contains only one pane so it doesn't contains extra `window_panes`.

This is my configuration in my `.tmux.conf`

    setw -g window-status-format "#I:#W#F#([ #{window_panes} -gt 1 ] && echo <#{window_panes}>)"

This is not working as expected, `#([ #{window_panes} -gt 1 ] && echo #{window_panes})` doesn't change anything.

**Comment by nicm** [comment]
Works for me, did you try exactly what I suggested? Adding <> will mess it up of course (what do they do in the shell?).

**Comment by c02y** [comment]
@nicm 
yes

    setw -g window-status-format "#I:#W#F#([ #{window_panes} -gt 1  ] && echo #{window_panes})"

this is not working either.

**Comment by nicm** [comment]
Exactly this works for me, you probably need to use tmux from git.

**Comment by c02y** [comment]
Thanks, it works for the latest version from git which is version 2.1 but not work for version 2.0.
