### ISSUE TITLE
Alt key combinations don't work when hardware flow control is enabled on serial tty

### ISSUE THREAD

**Issue by iavael** [tmux/tmux#930]
OS: Fedora Linux x86_64
Tmux: tmux 2.3
Term: vt220

Problem: when hardware flow control (RTS/CTS) is enabled on ttyS0, tmux attached to it stops handling Alt key combinations.
Expected behaviour: tmux always handles Alt-combinations irrelevant to state of flow control on serial tty.

Difference in keycodes with and without hardware flow control (pressed 2 combinations each time: Alt-PgUp, Alt-PgDown)
```
$ stty crtscts -F /dev/ttyS0
$ showkey -a
^[       27 0033 0x1b
[        91 0133 0x5b
5        53 0065 0x35
;        59 0073 0x3b
3        51 0063 0x33
~       126 0176 0x7e
^[       27 0033 0x1b
[        91 0133 0x5b
6;       54 0066 0x36
         59 0073 0x3b
3        51 0063 0x33
~       126 0176 0x7e
^D        4 0004 0x04
$ stty -crtscts -F /dev/ttyS0
$ showkey -a
^[[5;3~          27 0033 0x1b
         91 0133 0x5b
         53 0065 0x35
         59 0073 0x3b
         51 0063 0x33
        126 0176 0x7e
^[[6;3~          27 0033 0x1b
         91 0133 0x5b
         54 0066 0x36
         59 0073 0x3b
         51 0063 0x33
        126 0176 0x7e
^D        4 0004 0x04
$
```

Tmux server log: [tmux-server.txt](https://github.com/tmux/tmux/files/999938/tmux-server.txt)

**Comment by krader1961** [comment]
Your server log shows that you are setting `escape-time` to zero. Doing anything that changes the timing of the received characters, specifically if it adds any delay, will cause problems. And enabling flow-control is likely to alter the timing of the received characters. I'm willing to bet that if you change your `set-option -gs escape-time 0` to a non-zero value the problem will disappear. The value is in milliseconds. Try 10.

**Comment by iavael** [comment]
@krader1961 
Hmm, thanks it helped.
I think this issue can be considered as solved, but I have a question (unrelated to tmux but maybe you can answer it).

Actually I made showkey demonstration just before posting this issue and I'm still puzzled, because it looks like uart controller returns input per byte with hw flow control enabled and I thought that it should buffer them in FIFO (rx trigger level is 8) anyway. Is this something that should be (or unrelated to FIFO maybe?) or this is really weird behaviour specific to my uart controller?

**Comment by krader1961** [comment]
I don't know. A decade ago I knew the Linux kernel extremely well and there were only a couple of people my equal at analyzing a Linux kernel crash dump. But I haven't looked at Linux kernel source or attempted to debug kernel level issues in the past ten years so am no longer qualified to answer that question. The issue may be with the driver for your specific UART controller. Or it may be in the common code shared by such drivers. The bottom line is that setting `escape-delay` to zero is only safe when the tmux client and server are on the same machine. With a value of zero you could potentially see the same problem over a SSH connection.

**Comment by krader1961** [comment]
Also, shameless plug, you might want to install the `fish` shell and use its `fish_key_reader` program for debugging this type of problem since it will show you the inter-char delay with a resolution of microseconds. A feature that really needs to be added to the `showkey` command.

**Comment by iavael** [comment]
@krader1961
Ok, i'll try to dig deeper. Anyway thanks for you answer and especially for pointing to fish_key_reader. Just wanted to know if it looks like a bug to someone else.

**Comment by krader1961** [comment]
> Just wanted to know if it looks like a bug to someone else.

If it is a bug I am confident the bug is in the Linux kernel you are running rather than tmux. More likely is that what you're seeing is the expected behavior. The fkr program should make it clear how much delay is being introduced when hardware flow-control is enabled. If you do use the fkr program to collect timing data I'd love to see you add a comment to this issue with that data. Mostly because the fish project where I contribute sometimes gets similar questions. Which is why I added inter-char timing data to the fkr program output.

**Comment by iavael** [comment]
@krader1961 
Hmm... no big difference here

```
$ stty crtscts -F /dev/ttyS0
$ fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.130 ms)  hex:   5B  char: [
(  0.077 ms)  hex:   36  char: 6
(  0.075 ms)  hex:   3B  char: ;
(  0.074 ms)  hex:   33  char: 3
(  0.076 ms)  hex:   7E  char: ~
bind \e\[6\;3~ 'do something'
$ stty -crtscts -F /dev/ttyS0
$ fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.209 ms)  hex:   5B  char: [
(  0.123 ms)  hex:   36  char: 6
(  0.111 ms)  hex:   3B  char: ;
(  0.108 ms)  hex:   33  char: 3
(  0.109 ms)  hex:   7E  char: ~
bind \e\[6\;3~ 'do something'
$
```

Also i've decreased in tmux escape-time to 1 and it still works.

**Comment by iavael** [comment]
Executed again couple times - no difference at all
```
$ stty crtscts -F /dev/ttyS0; fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.128 ms)  hex:   5B  char: [
(  0.095 ms)  hex:   36  char: 6
(  0.094 ms)  hex:   3B  char: ;
(  0.092 ms)  hex:   33  char: 3
(  0.093 ms)  hex:   7E  char: ~
bind \e\[6\;3~ 'do something'
$ stty crtscts -F /dev/ttyS0; fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.138 ms)  hex:   5B  char: [
(  0.084 ms)  hex:   36  char: 6
(  0.081 ms)  hex:   3B  char: ;
(  0.081 ms)  hex:   33  char: 3
(  0.081 ms)  hex:   7E  char: ~
bind \e\[6\;3~ 'do something'
$ stty -crtscts -F /dev/ttyS0; fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.149 ms)  hex:   5B  char: [
(  0.138 ms)  hex:   36  char: 6
(  0.095 ms)  hex:   3B  char: ;
(  0.099 ms)  hex:   33  char: 3
(  0.093 ms)  hex:   7E  char: ~
bind \e\[6\;3~ 'do something'
$ stty -crtscts -F /dev/ttyS0; fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.124 ms)  hex:   5B  char: [
(  0.130 ms)  hex:   36  char: 6
(  0.089 ms)  hex:   3B  char: ;
(  0.087 ms)  hex:   33  char: 3
(  0.088 ms)  hex:   7E  char: ~
bind \e\[6\;3~ 'do something'
$
```

**Comment by krader1961** [comment]
Your test results suggests that tmux treats an `escape-time` value of zero specially. Specifically, that a single read will return more than one character if there is more than one character available and that enabling hardware flow control on your system breaks that assumption. However, without digging deeper into the implementation of both programs, and the Linux kernel, any conjecture at this point is just a guess.

Regardless of the above the reality is that an `escape-time` of zero is going to cause problems. It appears there are too many highly ranked Google search results for "tmux escape-time" recommending people set it to zero. Such as this one for [Emacs Evil mode](https://www.emacswiki.org/emacs/Evil) which simultaneously recommends zero and five.

This is basically a red hot mess because the original author of the Vi editor chose to use the escape character to switch from "insert" to "normal" (i.e., command) mode.

**Comment by iavael** [comment]
Looking at the source of showkey I see, that it always reads input by 1 byte and prints it formatted after tab. Which means that ascii representation before tab is printed by echo of terminal itself. Looks like with hardware flow control terminal echo becomes synchronous.
Also FINOREAD ioctl with hw flowctl enabled always returns 1 (that causes problems in tmux when escape-time = 0).
