### ISSUE TITLE
aborted zsh completion not fully cleared

### ISSUE THREAD

**Issue by octoploid** [tmux/tmux#931]
[log.tar.zip](https://github.com/tmux/tmux/files/1000201/log.tar.zip)
Start tmux -> dmesg -> type man m[tab]

![2017-05-15-075812_538x726_scrot](https://cloud.githubusercontent.com/assets/327746/26044464/cd50e018-3944-11e7-9653-acfc9e5a2dcc.png)

type [backspace] to abort:
![2017-05-15-075821_538x726_scrot](https://cloud.githubusercontent.com/assets/327746/26044477/d9395fea-3944-11e7-9d36-4a61006cfff5.png)

**Comment by nicm** [comment]
Are you sure you have 7a4c66b7f5710e92f4af2bdfdb3b88bd64306320?

Does this show the same problem (compare inside and outside tmux):
~~~~
clear;dmesg;printf '\033[3;1H\033[J\033[10;1H'

**Comment by octoploid** [comment]
I have 7a4c66b and no, your command line doesn't show any problems.

**Comment by nicm** [comment]
Does this also happen in xterm? Make sure TERM is the same outside tmux in both terminals.

**Comment by nicm** [comment]
Never mind, this is the same bug in Konsole. I thought you couldn't scroll _more_ than the scroll region, but it looks like you can't scroll the whole scroll region either. Compare this in xterm:

~~~~
clear;seq 100;printf '\033[3;20r\033[18S\033[r';sleep 10
~~~~

And:

~~~~
clear;seq 100;printf '\033[3;20r\033[17S\033[r';sleep 10
~~~~

With a scroll region of 3-20 we need to scroll 18 lines to remove the whole thing. 17 is not enough.

So 7a4c66b7f5710e92f4af2bdfdb3b88bd64306320 is wrong, and I am going to revert it.

tmux needs a working indn if it is specified in terminfo. What did the Konsole guys say to your bug report?

You should be able to work around this for now by doing:

~~~~
set -as terminal-overrides ',*:indn@'
~~~~

**Comment by octoploid** [comment]
Yes, it also happens in xterm.

**Comment by octoploid** [comment]
Commit cb5fcb3d doesn't fix this issue for xterm.

**Comment by nicm** [comment]
Show me logs from using xterm with latest master please (only need the server log).

**Comment by octoploid** [comment]
Sorry, false alarm (had an unnoticed tmux instance running in the background).
Xterm is fine now.

**Comment by nicm** [comment]
OK cool. I don't think there is a practical way to detect this bug, I think it will need to be fixed in Konsole.

**Comment by octoploid** [comment]
I would be good if you could open a Konsole bug yourself, because I don't understand the issue sufficiently:
https://bugs.kde.org/enter_bug.cgi?product=konsole

**Comment by octoploid** [comment]
Ah, found the konsole bug: https://bugs.kde.org/show_bug.cgi?id=379318

**Comment by nicm** [comment]
Yes I think this bug report is fine. If you can figure out how to build Konsole you could try this, which copies the check in Screen::scrollDown() to Screen::scrollUp():
~~~~
diff --git a/src/Screen.cpp b/src/Screen.cpp
index d456d67..02c1e4c 100644
--- a/src/Screen.cpp
+++ b/src/Screen.cpp
@@ -868,7 +868,9 @@ QRect Screen::lastScrolledRegion() const

 void Screen::scrollUp(int from, int n)
 {
-  if (n <= 0 || from + n > bmargin) return;
+  if (n <= 0) return;
+  if (from > bmargin) return;
+  if (from + n > bmargin) n = bmargin - from;

   _scrolledLines -= n;
   _lastScrolledRegion = QRect(0,tmargin,columns-1,(bmargin-tmargin));

**Comment by nicm** [comment]
Actually that was a very old tree, try this:

~~~~
diff --git a/src/Screen.cpp b/src/Screen.cpp
index 90671829..fd8e5c3c 100644
--- a/src/Screen.cpp
+++ b/src/Screen.cpp
@@ -752,7 +752,12 @@ QRect Screen::lastScrolledRegion() const

 void Screen::scrollUp(int from, int n)
 {
-    if (n <= 0 || from + n > _bottomMargin) return;
+    if (n <= 0)
+        return;
+    if (from > _bottomMargin)
+        return;
+    if (from + n > _bottomMargin)
+        n = _bottomMargin - from;

     _scrolledLines -= n;
     _lastScrolledRegion = QRect(0, _topMargin, _columns - 1, (_bottomMargin - _topMargin));

**Comment by octoploid** [comment]
Thanks. I have created: https://git.reviewboard.kde.org/r/130133/diff/1#index_header

(there was an off by one error in your patch, which caused exactly the same issue
that I've described above)


`
diff --git a/src/Screen.cpp b/src/Screen.cpp
index 90671829bf9b..45b8da0ab0e9 100644
--- a/src/Screen.cpp
+++ b/src/Screen.cpp
@@ -752,7 +752,12 @@ QRect Screen::lastScrolledRegion() const
 
 void Screen::scrollUp(int from, int n)
 {
-    if (n <= 0 || from + n > _bottomMargin) return;
+    if (n <= 0)
+        return;
+    if (from > _bottomMargin)
+        return;
+    if (from + n > _bottomMargin)
+        n = _bottomMargin + 1 - from;
 
     _scrolledLines -= n;
     _lastScrolledRegion = QRect(0, _topMargin, _columns - 1, (_bottomMargin - _topMargin));
`

**Comment by octoploid** [comment]
Not a tmux bug. Lets close this issue.
