### ISSUE TITLE
My terminal doesn't redraw the screen 

### ISSUE THREAD

**Issue by c02y** [tmux/tmux#933]
- version: tmux master commit 3df4e78492 and another commit from master since I pulled once.
- platform: CentOS6.5 32-bit Qt: 4.6.2 KDE: 4.3.4 (KDE 4.3.4) kde4-config: 1.0
- $TERM: xterm-256color or empty ~/.tmux.conf
- same result with empty ~/.tmux.conf

This problem happens in both in bash or fish-shell, so it is not the problem of shell.

This problem happens in Konsole_v2.3.3/Yakuake_v2.9.8 with new version built from tmux master, but not in gnome-terminal_v2.31.3 with any version of tmux.

This problem happens when using tmux binary built from tmux master, **but** 2.5-rc branch or earlier versions are OK, so it's the problem of new code of tmux.

![recorded](https://cloud.githubusercontent.com/assets/2135996/26136055/362c216c-3aec-11e7-926e-b0274c940767.gif)

[tmux-server-26331.log.txt](https://github.com/tmux/tmux/files/1006374/tmux-server-26331.log.txt)

**Comment by octoploid** [comment]
Yes, this is a known konsole bug. See https://github.com/tmux/tmux/issues/931 for a workaround or a konsole patch.

**Comment by c02y** [comment]
Thanks, `set -as terminal-overrides ',*:indn@'` fix it.

**Comment by forfrt** [comment]
Get fixed. Thanks

**Comment by ggsalas** [comment]
Any update on this? I have the same problem on macos and neovim. Thanks!
