### ISSUE TITLE
pane-border-format usage

### ISSUE THREAD

**Issue by liquid1982** [tmux/tmux#934]
Not sure if this an issue – maybe more a feature request, but it looks like it's not possible to set individual panel names using `pane-border-format` – see the attached screencast. Is there a way to set pane names individually? It would be really useful. I work with multiple Rails app in the same window and It's kinda difficult to tell which one is which. I tried exporting env variables etc, but no luck.

https://asciinema.org/a/40l7wl8i2tyr9zs7t1c15djdh

**Comment by nicm** [comment]
Panes don't have names. You can set the pane title using the escape sequences, or write a script that works out the name from some other attribute of the pane (pane_current_command, pane_tty, pane_pid).

**Comment by liquid1982** [comment]
@nicm thanks for your note. I found something that I could use: `pane_current_path`. I was thinking to something like:

```bash
function pane_title() {
  local pane_dir=$1
  local pane_cmd=$2

  echo "Dir: $pane_dir - Command: $pane_cmd"
}
```

and

```
tmux set pane-border-format " `pane_title \"#{pane_current_path}\" \"#{pane_current_command}\""` "
```

**Comment by nicm** [comment]
Great
