### ISSUE TITLE
Disable tmux mouse copy-mode jumps to bottom on tmux < 2.1?

### ISSUE THREAD

**Issue by mdeguzis** [tmux/tmux#935]
When I select text it gets automatically copied to the tmux-buffer and the window jumps to the end. So if i scroll up and klick on sth it jumps to the end... When I switch between panes a copy comand is triggered and the output goes to the end. I really dislike this behaviour and I'd rather have to press a button to copy or click q to finish copy mode or sth.

Is it possible to disable auto-copy // auto jump to the end on mouse button release?

See: http://stackoverflow.com/questions/32374907/tmux-mouse-copy-mode-jumps-to-bottom

**Comment by nicm** [comment]
You can use 2.4 or master and bind copy-selection instead of copy-selection-and-cancel.

**Comment by mdeguzis** [comment]
This unfortunately is not an option on RHEL 7.3 (tmux 1.8, non-EPEL).

**Comment by nicm** [comment]
Don't remember how to do it in older versions. There was a flag or something (copy-selection -x)?

**Comment by tessus** [comment]
@mdeguzis I've created a tmux 2.4 package for CentOS 7.3, which also works on RHEL 7.3.
If you are interested, let me know.
I will also create a 2.5 package as soon as tmux 2.5 is released.

**Comment by mdeguzis** [comment]
I know how to build RPMs. Unfortunately, being in a large company, We must adhere to RHEL 7.3 via Satellite channels. I may be persuade folks if such a version is available via EPEL.

**Comment by nicm** [comment]
You will need to upgrade to a version where this is supported.
