### ISSUE TITLE
start-server exits immediately and doesn't run anything.

### ISSUE THREAD

**Issue by hobarrera** [tmux/tmux#936]
`start-server` doesn't do anything, just exits immediately.

```
$ tmux -V
tmux 2.4
$ echo $TERM
xterm-termite
$ tmux start-server
$ echo $?
0
$ ps aux | grep tmux
$
```

* ArchLinux on amd64
* Reproducible without a config file
* [Output of running `tmux -vvvv -Ltest -f/dev/null new`](https://gist.github.com/hobarrera/b78999f202c1d819543f0b0444ec4d62)

**Comment by krader1961** [comment]
This appears to be a dup of issue #869.
