### ISSUE TITLE
Feature request: new option `renumber-sessions` in addition to `renumber-windows`

### ISSUE THREAD

**Issue by maximbaz** [tmux/tmux#937]
```
❯  uname -sr && tmux -V && echo $TERM

Linux 4.10.13-1-ARCH
tmux master
tmux-256color
```

----------

Just like we have `renumber-windows` option, I'd like to see another option `renumber-sessions` for sessions.

I saw someone made an [analysis](https://unix.stackexchange.com/a/177986) on stackexchange of the same feature request, but that is the only mention of such request that I found.

-------------

#### Steps to reproduce:

- Add `set-option -g renumber-sessions on` to `.tmux.conf`
- Open terminal 1 and execute `tmux new` (session `0` created).
- Open terminal 2 and execute `tmux new` (session `1` created).
- Open terminal 3 and execute `tmux new` (session `2` created).
- Type `exit` in terminal 2 (session `1` terminated).

#### Expected:
- Session `2` in terminal 3 is renamed to `1`.

#### Actual:
- Session `2` in terminal 3 remains named `2`.

#### More steps:
- Open terminal 4 and execute `tmux new`

#### Expected:
- Session `2` is created.

#### Actual:
- Session `3` is created.

------------

### My personal use-case for this feature request.

I start a new tmux session in every terminal window (I have `tmux new` in my `.zshrc`). 

I discovered, that starting tmux server takes time, so it takes visibly longer to open the first terminal window (read: to create the first tmux session, which in turn creates tmux server). Because I open and close terminal windows many times during the day, I am quite affected by this slowness. 

In order to work around such slowdown, I created a simple systemd service that creates the first "invisible" session on login that is always alive. I then open and close many terminals, but this first session is never destroyed, and thus tmux server doesn't restart all the time.

Terminal startup is fast, I'm quite happy with this setup, however the session numbers are growing very quickly, I easily reach hundred on the counter during one day. With large session numbers it becomes a bit cumbersome to work with them, for example to move a window between sessions. If there was a `renumber-sessions` option, my counter would probably never go above 10.

Currently the workaround is to restart the tmux server, but I'd really love to see the `renumber-sessions` option.

**Comment by nicm** [comment]
Sessions are not numbered in the same way windows are, the default name
is a number but it is just a placeholder. If you want them renumbered in
order, write a script to rename them the way you want.

**Comment by maximbaz** [comment]
I see. If I have a script, is there a way to execute it automatically when a tmux session was closed? I'd like it to run without my explicit command, but also ideally not in some infinite loop in background.

**Comment by nicm** [comment]
You could run it from session-closed hook.

**Comment by maximbaz** [comment]
Nice, that works for me, thanks!

**Comment by maximbaz** [comment]
It was actually very easy to script this knowing that there are `session-created/closed` hooks. 
So thanks again 🙂

In case anyone else finds this thread, feel free to take the script from [my dotfiles](https://github.com/maximbaz/dotfiles/commit/925a5b88a8263805a5a24c6198dad23bfa62f44d).
