### ISSUE TITLE
Shortcut for next-window/previos-window in copy-mode.

### ISSUE THREAD

**Issue by h0t0sh0** [tmux/tmux#939]
In copy-mode doesn't work shortcuts Shift-Right/Shift-Left for next-window/previous-window.
At the same time prefix-n and prefix-p are working fine.
In tmux 2.3 Shift-Right/Shift-Left for next-window/previous-window worked fine too.

Shortcuts working fine If I change commands for shortcut like:
bind-key -T copy-mode-vi S-Right send -X cursor-right
bind-key -T copy-mode-vi S-Left send -X cursor-left

> uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.4
screen

test.conf
bind -n S-Right next-window
bind -n S-Left previous-window
bind-key -T copy-mode-vi S-Right send -X next-window
bind-key -T copy-mode-vi S-Left send -X previous-window

Steps to reproduce:
tmux -f test.conf
C-b c   # Create new window
S-Left  # Forking fine
S-Right # Working fine
C-b [   # Switch to copy-mode
S-Left  # Doesn't work
S-Right # Doesn't work

**Comment by nicm** [comment]
Do they work in master?

**Comment by h0t0sh0** [comment]
Sorry, forgot to check.
Shortcuts are working perfect in master, waiting for the release of version 2.5 :)
