### ISSUE TITLE
tmux uses a lot of CPU on macOS

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#941]
Currently running master from a few days ago (d1497527c6b4771c9d4bc0e9f9956f38322545d2) but this problem has been manifesting for at least a month, I think.

I notice that tmux will, at times, chew threw 100% of CPU even when idle. I'm on macOS (10.12.4), so there's no `strace`,  unfortunately, but I do get [this output](https://gist.github.com/wincent/1a72b3fcca749abe21b3ca08c338b34a) from the `sample` tool. Is there a way I can activate useful debug logging on an already-running session to gather more info? (I can't really set up logging from the beginning because this issue can take many hours to manifest, and I'd probably create an unusably large quantity of log output).

I'm seeing this bug right now, with 4 sessions, 2 of them attached. If I detach both of them and run `tmux ls`, it still shows one of them as attached, and CPU usage continues to be pegged up at 100%. If I reattach to the session in question and hit `prefix-D`, I can see two entries instead of the expected one: I can then kill one of the sessions (I chose the one whose dimensions did not match the current dimensions), and the CPU usage immediately goes down. When I detach from the remaining active session and re-run `tmux ls`, I no longer see the spurious "attached" session.

So, there is a workaround of sorts (and it doesn't require me to kill all sessions, which is nice). Is there any more info that I could gather and share here to get to the bottom of this?

**Comment by nicm** [comment]
Does this happen with an empty config?

**Comment by wincent** [comment]
Hard to say, as I don't think I can use tmux for hours of possibly days with an empty config. :-(

**Comment by andreypopp** [comment]
Also have this problem (on two macOS machines), after some time tmux starts to use 100% CPU. This is my [tmux.conf](https://gist.github.com/10a0e8e07f8edeb0bdc680e1c328a8e4)

**Comment by nicm** [comment]
Try ktrace?

**Comment by nicm** [comment]
Please comment again when you have some more information.

**Comment by wincent** [comment]
@nicm: [This](https://gist.github.com/wincent/eceb73b0439d9e72aa87e1de9a2cc839) is the output of running `dtruss` (an `strace`-like `dtrace` script that ships on macOS) for just under 5 seconds when tmux is exhibiting this behavior. As you can see, it made over 8k syscalls in that time.

To give some idea of how many that is relative to the other processes on the system, this is a list of the top processes over 5 seconds, as reported by `syscallbyproc.d` (another `dtrace` script that ships with macOS):

```
  notifyd                                                         541
  WindowServer                                                    555
  configd                                                         573
  netstat                                                         614
  Python                                                          743
  splunkd                                                         867
  git                                                            1136
  iTerm2                                                         1146
  dbfseventsd                                                    1419
  Activity Monitor                                               1619
  java                                                           1836
  Google Chrome                                                  2130
  Google Chrome He                                               3050
  sysmond                                                        8972
  tmux                                                         630018
```

For reference, the `tmux` processes running at this time (as reported by `ps auxww` are:

```
glh              63856 100.0  0.2  2513936  25608   ??  Rs   Tue09AM  72:17.62 tmux new-session -d -s email -c /Users/glh/Downloads -n mutt
glh              69210   0.0  0.0  2448748   1892   ??  S    11:23AM   0:00.01 tmux attach -t masochist:vim.left
glh              13723   0.0  0.0  2438508   1892   ??  S     7:41AM   0:00.01 tmux attach -t dot:vim.left
glh              32203   0.0  0.0  2450796   1888 s009  S+    4:52PM   0:00.01 tmux new -A -s relay
glh              64179   0.0  0.0  2440556    636 s005  S+   Tue09AM   0:00.01 tmux new -A -s fbs
glh              63885   0.0  0.0  2449772    468 s000  S+   Tue09AM   0:00.01 tmux attach -t email:mutt
glh               5595   0.0  0.0  2445676   2648 s007  S+    4:38PM   0:00.00 tmux new -A -s code
```

The top one — PID 63856 — is the one doing all the syscalls. I believe it corresponds to the first tmux session that I spawned, and It consists of two windows:

- One containing an idle `mutt` process.
- Another containing three panes with long-running processes in them that produce a little output (basically email filtering and syncing scripts). By "little output", I mean that over a course or hours they can produce a few thousand lines (I'm currently running with a `history-limit` of 4096).

(Note that PID 63885 is also attached to that "email" session. When I do `prefix-D` to get a list of all sessions, however, I only see one session attached, not two.)

So, as I was writing up this comment I exited out of some of those sessions and the CPU dropped back to idle again, and `ps auxww` now shows this:

```
glh              64179   0.0  0.0  2440556    628 s005  S+   Tue09AM   0:00.01 tmux new -A -s fbs
glh              63856   0.0  0.1  2513936  24768   ??  Ss   Tue09AM  79:59.12 tmux new-session -d -s email -c /Users/glh/Downloads -n mutt
```

So that ghost "email" session is still there even though it's no longer churning the CPU — [here's another `dtruss` for it](https://gist.github.com/wincent/7c9e187d69d3ba336fd5f437ee87066f), showing that it is doing almost nothing over 5 seconds — and `tmux ls` knows nothing about it:

```
fbs: 1 windows (created Tue May 30 09:30:53 2017) [238x117] (attached)
```

Please let me know if this sheds any light on things, and if there's anything else I could do to collect more info the next time this happens, as it surely will.

**Comment by nicm** [comment]
PID 63856 is most likely the server process, so it could be any session that is causing the problem, not the first one you created when you started the server.

What are you doing when this happens?
What is in your .tmux.conf?
Does it stop  if you detach clients (rather than killing sessions, just detach the clients)?
What about attaching ktrace to the process? It will show the system calls

**Comment by nicm** [comment]
You can try this which will toggle logging when you send SIGUSR2 to tmux: [log.diff.txt](https://github.com/tmux/tmux/files/1043769/log.diff.txt)

**Comment by wincent** [comment]
> What are you doing when this happens?

I haven't identified a pattern yet. Just typical usage: editing things in Vim, running commands at the shell, typically moving between various project-based sessions. I generally notice some arbitrary amount of days or hours after starting tmux for the first time. If I can spot a pattern I'll let you know.

> What is in your .tmux.conf?

[This](https://github.com/wincent/wincent/blob/b56f4cad2c5c073fd5db95a21b22b53d9574f0c7/roles/dotfiles/files/.tmux.conf).

> Does it stop if you detach clients (rather than killing sessions, just detach the clients)?

Not necessarily. In my first comment, I said "If I reattach to the session in question and hit `prefix-D`, I can see two entries instead of the expected one: I can then kill one of the sessions (I chose the one whose dimensions did not match the current dimensions), and the CPU usage immediately goes down." This last time, however, simply detaching fixed it.

> What about attaching ktrace to the process? It will show the system calls

No `ktrace` here, but see the `dtruss` output that I linked to in my previous comment (https://gist.github.com/wincent/eceb73b0439d9e72aa87e1de9a2cc839).

> You can try this which will toggle logging when you send SIGUSR2 to tmux

Thanks. I'll apply that and use it next time I catch this in the act.

**Comment by nicm** [comment]
That dtrace is useless because it is just statistics, I need to see what tmux is actually doing during the time.

**Comment by nicm** [comment]
What's in ~/.tmux-local.conf? Nothing?

**Comment by wincent** [comment]
> That dtrace is useless because it is just statistics, I need to see what tmux is actually doing during the time.

Are we looking at the same gist? It has over 8,000 lines of syscalls in it; here are the first few lines:

```
dtrace: system integrity protection is on, some features will not be available
SYSCALL(args) 		 = return
ioctl(0x1F, 0x4004667F, 0x7FFF536F23B0)		 = -1 Err#25
readv(0x1F, 0x7FFF536F23B0, 0x1)		 = -1 Err#5
ioctl(0x25, 0x4004667F, 0x7FFF536F23B0)		 = -1 Err#25
readv(0x25, 0x7FFF536F23B0, 0x1)		 = -1 Err#5
select(0x30, 0x7FDD73F02570, 0x7FDD73F00BF0, 0x0, 0x7FFF536F2528)		 = 2 0
```

> What's in ~/.tmux-local.conf? Nothing?

Correct.

**Comment by nicm** [comment]
Oh wait sorry I didn't see your link to the dtruss output, Ill ltake a look

**Comment by nicm** [comment]
Does this help?

~~~~~
? tmux
Index: tty.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/tty.c,v
retrieving revision 1.287
diff -u -p -r1.287 tty.c
--- tty.c	31 May 2017 10:29:15 -0000	1.287
+++ tty.c	1 Jun 2017 06:07:59 -0000
@@ -159,8 +159,10 @@ tty_read_callback(__unused int fd, __unu
 	int		 nread;
 
 	nread = evbuffer_read(tty->in, tty->fd, -1);
-	if (nread == -1)
+	if (nread == -1) {
+		event_del(&tty->event_in);
 		return;
+	}
 	log_debug("%s: read %d bytes (already %zu)", c->name, nread, size);
 
 	while (tty_keys_next(tty))

**Comment by wincent** [comment]
> Does this help?

Thanks. I've applied the patch. Will report back after I've been running with it for a while.

**Comment by nicm** [comment]
Is this fixed?

**Comment by wincent** [comment]
@nicm: I haven't seen the CPU usage problem since applying the patch despite hours of daily use, so there is a good chance that this is fixed.

**Comment by nicm** [comment]
OK I have applied it let me know if the problem continues.
