### ISSUE TITLE
default window_name

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#945]
Hi,

I was wondering is there any way to set a window_name to blank ?

e,g. When I start tmux status bar shows up 1:zsh, I understand if I remove #W from my .tmux.conf I will have what I want. However I do use rename window_name especially when I shh to remote hosts and with out #W I can't do that.

Basically my goal is to have a status bar showing only 1 and be able to rename window_name when I need to .

Thanks
LX

**Comment by nicm** [comment]
If you do this:

set -g automatic-rename-format "#{}"

Then tmux will set all the names to blank, unless you rename them manually (which will turn automatic-rename off for just that window).

If you want them to go back to blank you can then do this in the window:

set -u automatic-rename

**Comment by lanox** [comment]
@ncim thanks so much it was exactly what I was looking for.
