### ISSUE TITLE
tmux copy doesn't work well with vertically split `tig`

### ISSUE THREAD

**Issue by timotheecour** [tmux/tmux#946]
```
uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.3
screen
```

tig creates a vertical split but within a tmux pane, is there a way for tmux to detect this? 
What would be a workaround for vertical-split tig?

https://www.dropbox.com/s/ztxnt057r5q1kow/Screenshot%202017-05-24%2013.14.55.png?dl=0

**Comment by nicm** [comment]
There is no way for tmux to detect this.
