### ISSUE TITLE
process in vertically split pane takes a while to kill via ^C

### ISSUE THREAD

**Issue by timotheecour** [tmux/tmux#953]
```
uname -sp && tmux -V && echo $TERM

Linux unknown
tmux 2.3
screen
```

under tmux run:
`while true; do echo hello; done`
then afer a few seconds press ^C : the process stops almost immediately  (<0.5 s).
But do the same under a vertically split pane: the process takes a while to stop; sometimes 6 seconds

**Comment by timotheecour** [comment]
[EDITED post above]

**Comment by nicm** [comment]
Does this happen in master?
