### ISSUE TITLE
bright text does not change colour after palette has been set

### ISSUE THREAD

**Issue by bertnp** [tmux/tmux#954]
Problem description
==============
Many terminal emulators have the option to print bold/bright text with bold font, or a different colour, or both. In tmux, after the colour palette has been set using OSC4 codes, bold/bright text is no longer printed in a different colour. The screenshots below show a minimal working example.

This issue is particularly problematic when programs use bold/bright text on a background of the same colour (for example, if text is outputted using \033[1;30;40mtext\033\[0m.) In this case, the text is invisible. An example of this happening in practice is text turning invisible with htop using the default theme.

Without tmux
=========
![tmux-off](https://cloud.githubusercontent.com/assets/13802707/26744246/15125e6e-47b3-11e7-9078-6f0fcd87ed79.GIF)

With tmux
=======
![tmux-on](https://cloud.githubusercontent.com/assets/13802707/26744258/1d0246ac-47b3-11e7-8a3c-82f65d9f1995.GIF)

Desired solution
===========
It would be nice to be able to configure how bold/bright text is handled when the colour palette is set. The options should include: none, bold font, bright colour, bold font + bright colour.

Additional details
============
- platform: Arch linux
- tmux config: default
- terminals tested: ROXTerm, rxvt-unicode, mintty
- TERM inside of tmux: tmux-256color
- TERM outside of tmux: xterm-256color
- tmux version: latest version from github as of posting (commit 73b9328)

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1049142/x.diff.txt)

**Comment by bertnp** [comment]
Thanks!

This appears to fix the issue when only fg options are specified. However, tmux still behaves differently than my terminal emulator when a fg and bg are specified. Here's an example:

Without tmux:
![mintty](https://cloud.githubusercontent.com/assets/13802707/26748587/fcf382a8-47cc-11e7-85f2-db354d7ba5f9.GIF)

With tmux:
![tmux](https://cloud.githubusercontent.com/assets/13802707/26748589/01b427f2-47cd-11e7-850a-ad2fdeefea35.GIF)

So far I've only tested this with mintty.

**Comment by nicm** [comment]
Oh yeah the bright attribute doesn't apply to the bg, try this instead [y.diff.txt](https://github.com/tmux/tmux/files/1049214/y.diff.txt)

**Comment by bertnp** [comment]
This looks good. I'll continue using the patched version and report back if I notice any problems.

Thanks again!

**Comment by nicm** [comment]
Applied to OpenBSD, will be in GitHub soon. Thanks!
