### ISSUE TITLE
Possible to specify min length of mouse-selected text to copy?

### ISSUE THREAD

**Issue by xiumingzhang** [tmux/tmux#958]
Hi,

I often use my mouse to select some text and copy it from one pane (source pane) to another (destination pane). I'm using tmux via iTerm2, with mouse reporting enabled, on macOS. As you may already know, copying happens automatically the moment when I release my mouse drag.

Then when I move to the destination pane by mouse clicking, oftentimes some accidental mouse drag happens, and it usually spans only a few characters. As a result, the clipboard contents get flushed by these mis-selected characters. 

Is there a way to tell tmux to only copy things of length > N to the clipboard?

Thanks in advance!

---

Output of `uname -sp && tmux -V && echo $TERM`:

```
Linux x86_64
tmux 1.8
screen-256color
```

Relevant part of my `.tmux.conf`:

```
set -g mode-mouse on
set -g mouse-select-pane on
set -g mouse-resize-pane on
set -g mouse-select-window on 
```

**Comment by nicm** [comment]
Not using 1.8 no.
