### ISSUE TITLE
can't split panes

### ISSUE THREAD

**Issue by reymonr** [tmux/tmux#959]
Hi, i'm trying to split panes on tmux, but it failed. I got a message:

Can't find window 5.

I'm trying to find the solution by googling the message, but found nothing to help.

Thank you.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by chmercesmoreira** [comment]
I'm having exactly the same problem, before it was working normally when I type:
ctrl+b + % = vertical split
ctrl+b + " = horizontal split

Now I'm getting:
ctrl+b + % = Can't find window 5 (it tries to switch window by number)
ctrl+b + " = index prompt (it asks for the window index)

I don't know why the behaviour of these two shortcuts had change, I did nothing.
How do I turn back to the correct behaviour?

**Comment by lloydjatkinson** [comment]
Every site out there fails to mention the need for shift + %. Thank you @ghost for figuring it out!
