### ISSUE TITLE
[bug?] different behaviuor for new[-session] command

### ISSUE THREAD

**Issue by ZuBB** [tmux/tmux#96]
preconditions: no tmux sessions and server are not running

run next command
```
tmux new -As test
```
in newly created session `tmux ls` gives one session
```
vv@e5520 ~/.config/tmux $ tmux ls
test: 1 windows (created Sat Aug 29 21:21:01 2015) [123x21] (attached)
vv@e5520 ~/.config/tmux $ 
```
kill all tmux stuff

now run tmux with conf file that holds only one line (same as above) - `tmux new -As test`. now `tmux ls` gives two active sessions
```
vv@e5520 ~/.config/tmux $ tmux ls
1: 1 windows (created Sat Aug 29 21:23:10 2015) [123x21] (attached)
test: 1 windows (created Sat Aug 29 21:23:10 2015) [80x23]
vv@e5520 ~/.config/tmux $ 
``` 

Is this a bug? I suppose to see only one session created in both cases. tested in 1.8 and 2.0 versions

**Comment by ZuBB** [comment]
smth similar is described here https://github.com/sorin-ionescu/prezto/issues/849

**Comment by nicm** [comment]
It is not a bug, in the first case you are running new-session once (on the command line), in the second you are running it twice (in the config file and on the command line).

**Comment by ZuBB** [comment]
oops. sorry I forget to mention that for 2nd case I use next command
```
tmux -f my_custom_config
```

**Comment by ZuBB** [comment]
Ok, but how I can disable creation of new session from command line?

**Comment by nicm** [comment]
Use tmux attach or tmux start instead of tmux new from command line.

**Comment by ZuBB** [comment]
Did I understand correctly that in 2nd case 'new' command is still present/invoked even if I do not type it?

**Comment by nicm** [comment]
Yes

**Comment by ZuBB** [comment]
is it possible to use in tmux config smth like next?
```
if-shell "tmux has -t vim" "TMP_NAME=`display -p '#S'` ; attach-session -t 'vim' ; kill-session -t $TMP_NAME" "rename 'vim'"
```

**Comment by nicm** [comment]
What are you trying to achieve?
