### ISSUE TITLE
Can't use join-pane with choose-tree

### ISSUE THREAD

**Issue by wilywampa** [tmux/tmux#960]
I am running git master tmux (i.e. 2.5+) on OS X in iTerm2 but the configuration doesn't really matter for this issue. If I have a binding:

    bind 'j' choose-window "join-pane -s '%%'"

to execute `join-pane` on a pane in another window, I get the error `"Can't join a pane to its own window"`. I think it's because the a preview of the selected pane is displayed in the current window, not taking into account the fact that the preview window will immediately disappear after making a selection.

**Comment by nicm** [comment]
Does this fix it?

~~~~
Index: window-tree.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/window-tree.c,v
retrieving revision 1.1
diff -u -p -r1.1 window-tree.c
--- window-tree.c	30 May 2017 21:44:59 -0000	1.1
+++ window-tree.c	6 Jun 2017 06:56:12 -0000
@@ -699,7 +699,7 @@ window_tree_key(struct window_pane *wp, 
 		name = window_tree_get_target(item, &fs);
 		window_pane_reset_mode(wp);
 		if (name != NULL)
-			mode_tree_run_command(c, &fs, command, name);
+			mode_tree_run_command(c, NULL, command, name);
 		free(name);
 		free(command);
 		return;

**Comment by wilywampa** [comment]
Indeed it does. Thanks for the quick response!

**Comment by nicm** [comment]
Applied, thanks!
