### ISSUE TITLE
Choose view of attached sessions no longer shows dimensions

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#964]
The rewrite of the "choose view" looks amazing (thanks for that!) but I've found it less useful for one of my use cases.

Fairly often, I want to detach other clients that have smaller dimensions and are causing the usable area to shrink as in this screenshot:

![ls___glh-mbp___tmux___zsh__tmux_](https://user-images.githubusercontent.com/7074/26906113-ed8abddc-4b9f-11e7-8f46-75198716d5ad.png)

Before the choose view rewrite, I'd hit `<prefix>-D` and kill the session with the smaller dimensions. Now that the dimensions are no longer shown in the textual list, I can't tell which one to kill.

```
(0) /dev/ttys003: session email (Wed Jun  7 16:46:23 2017)
```
Compare that with the output of `tmux list-clients`, which is very similar, but includes dimensions:

```
/dev/ttys003: email [238x118 xterm-256color] (utf8)
```

There may be a workaround in the form of setting some kind of default format in `~/.tmux.conf` (ie. using `session_height` and `session_width`), but I haven't been able to find it based on my reading of the man-page.

**Comment by wincent** [comment]
Should note that for the use-case I've described above `tmux detach-client -a` seems to work pretty well (disconnects all clients of the current session except for the current client in which the command is issued; leaves the other sessions' clients alone).

**Comment by nicm** [comment]
Yes, changed it now to add the size. Thanks

**Comment by wincent** [comment]
Thank you!
