### ISSUE TITLE
tmux doesn't search scrollback across line breaks

### ISSUE THREAD

**Issue by dcaixinha** [tmux/tmux#966]
When I search my tmux scrollback by typing `prefix` + `/`, instances of search target that are interrupted by line breaks (because the tmux pane or terminal window is too narrow or search target is very long, or it's just bad luck) are not found. If I resize the pane so that an instance of search target is not interrupted by a line break, then tmux finds it.

Is there a way to perform a search with tmux that finds stuff in wrapped lines? This is really important for me as I used the find to confirm (or deny) the presence of certain things in my output. I've asked some of my colleagues and they were able to reproduce this with other OSs and tmux versions (namely OSX and tmux 2.1).

tmux 2.3, Terminator 1.91,  Arch Linux latest build

**Comment by nicm** [comment]
There is no point in opening an issue to ask exactly the same thing as an issue you already found.

**Comment by nicm** [comment]
Anyway, there has been no change in the way this works.

**Comment by dcaixinha** [comment]
I'm sorry. Since the issue was closed (and I didn't `@` anyone) I was afraid nobody saw it. Thanks for your response. Is this in the roadmap?

**Comment by nicm** [comment]
Not really, it doesn't bother me and it is probably not trivial to do, AFAIK nobody has looked at it.

**Comment by dcaixinha** [comment]
This is probably a long shot, since my C is a **bit** rusty, but can you give me some pointers on which files should I look at to implement this? This is kind of a big deal to me because having false negatives when searching for something in my terminal can be a bit misleading. Thanks 😉

**Comment by nicm** [comment]
It's almost all in window-copy.c but the problem is that it copies the
current screen into a new one and I don't think it includes the line wrap
flag, so that'll need to change. Then it will need to unwrap them for
searching.

**Comment by NasaGeek** [comment]
@dcaixinha Have you considered using something like tee to route your stdout to a file (while still being able to see it in the terminal) and then searching the file? Probably easier than patching tmux if that fits your workflow.

**Comment by nicm** [comment]
This is in the TODO file already and I'm clearly not going to get to it soon so there is no need for an issue to stay open.

**Comment by offero** [comment]
Not being able to search wrapped text is a horrible usability issue for me
