### ISSUE TITLE
tmux putty-256color arrow keys not working

### ISSUE THREAD

**Issue by jacob-keller** [tmux/tmux#967]
Linux x86_64
tmux 2.2
putty-256color

In order to get proper 256colors working from PuTTY, I have configured to use putty-256color terminal. Unfortunately, when I run tmux, the left/right arrow keys don't work in bash (inside tmux) unless I "set keypad on" in my .inputrc.

It works fine outside of Tmux. This leads me to believe it's a bug in Tmux, as the bash shell and other readlines work fine outside of tmux, but somehow get messed up once we enter tmux. Maybe I set the internal terminal wrong? If I instead use putty-noapp, then 256color mode does not work.

See https://bugzilla.redhat.com/show_bug.cgi?id=1369182 for more information, as well as this thread on the upstream ncurses mailing list.

https://lists.gnu.org/archive/html/bug-ncurses/2016-01/msg00010.html

Inside tmux default config:

Linux x86_64
tmux 2.2
screen

**Comment by jacob-keller** [comment]
[tmux-server-5302.txt](https://github.com/tmux/tmux/files/1064650/tmux-server-5302.txt)

**Comment by jacob-keller** [comment]
I suspect this might be because screen and screen-256color do not support the application keys, while putty-256color does. I am re-trying with tmux-256color inside the tmux.

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by jacob-keller** [comment]
Yes. 

Using xterm-256color from putty isn't a solution either, because this breaks other things from putty side and colors don't work right.

I suspect the problem is mishandling of application key. It may be a bug in the screen-256color or tmux-256color terminfo?

**Comment by jacob-keller** [comment]
Wait. I re-tried this again on master, as I realized my first try did not run the actual master version. It appears to work. I'm going to try to verify with a git-bisect.

**Comment by jacob-keller** [comment]
It appears like this was fixed in 78ca1b026568 ("Always send smkx to the terminal outside, the keys we get from terminfo are the keys when it is on.", 2017-03-08) which was fixed in 2.4.

Thanks!

**Comment by nicm** [comment]
Good stuff

**Comment by jacob-keller** [comment]
I couldn't finish the bisect because it fails to build between the versions for some reason, but I highly suspect the fix above, and it does work on master

**Comment by eloj** [comment]
I ran into this after upgrading from Debian 8 ("jessie") to Debian 9 ("stretch"), where in tmux the left/right arrow keys would print "2D"/"2C" in bash, but seemingly work in other applications like vim and irssi.

Gave up and added an `.inputrc` with `set enable-keypad on` which seems to "solve it", but I'm sure it'll come back and bite me.

**Comment by jacob-keller** [comment]
You should check the version of tmux and make sure it's up to date, it's
possible Debian stable hasn't updated to a fixed version. Without the fix
you will run into problems, most notably every ssh session inside tmux has
to be configured on the remote end to fix input rc and that fix only works
for application using readline

**Comment by eloj** [comment]
Yeah, it's not even [been updated in 2017](http://metadata.ftp-master.debian.org/changelogs/main/t/tmux/tmux_2.3-4_changelog), so the patch is not there.

I guess it could be packported, however, I solved it by simply installing the tmux package from [buster](https://packages.debian.org/buster/tmux) instead, which provides tmux 2.5

It does not require any updated dependencies so it's really easy to just install it over the stretch version.

**Comment by jacob-keller** [comment]
It's not hard to backport that's what I did for Fedora but yeah that works
too

**Comment by m4agenbitter** [comment]
Im encountering the same issue:
```
[root@client02 /root]# tmux -V
tmux 2.6
[root@client02 /root]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[root@client02 /root]# echo $TERM
putty-256color
[root@client02 /root]# cat
^[[D

^[OD

^C
[root@client02 /root]# tmux
[root@client02 /root]# echo $TERM
screen
[root@client02 /root]# cat
^[[D

^[[D

^C
```

Pressing left arrow and left ctrl + arrow both yield the same sequence, but only inside tmux.

screen works just fine though:
```
[root@client02 /root]# screen
[root@client02 /root]# echo $TERM
screen
[root@client02 /root]# cat
^[[D

^[OD
D
^C
```

**Comment by jacob-keller** [comment]
This should be properly fixed by the latest tmux with a proper tmux-256color terminal info. You should encourage debian to update its package, or accept a backport patch. It was pretty easy to backport the patch to tmux 2.3 which is what I did a while back for Fedora (who have since updated their package to 2.5)

**Comment by chros73** [comment]
> This should be properly fixed by the latest tmux with a proper tmux-256color terminal info.

That's correct, I just tried out with 2.6 and tmux-256color on Ubuntu 14.04 using KiTTY 0.70.x with putty-256color:

inside and outside of tmux:
```
^[[D
^[[1;5D
```

> You should encourage debian to update its package

@devs: btw, I'm working on a simple but powerful build script (that should work on any distro), I'll let you know when it's finished.

**Comment by eloj** [comment]
For Debian Stretch users, tmux 2.6 is available via the [stretch-backports](https://packages.debian.org/stretch-backports/tmux) repository.

**Comment by m4agenbitter** [comment]
Thanks for the quick feedback.
Im actually using Windows (so Putty runs on Windows while connection to a VM running tmux).
Im also using the latest release from here https://github.com/tmux/tmux/releases/tag/2.6.

It strangely works with kitty (never heard about kitty before) but not with putty:

**putty:**
```
[root@client02 /root]# echo $TERM
putty-256color
[root@client02 /root]# cat
^[[D

^[OD

^C
[root@client02 /root]# cat .tmux.conf
set -g default-terminal "tmux-256color"
[root@client02 /root]# tmux
[root@client02 /root]# echo $TERM
tmux-256color
[root@client02 /root]# cat
^[[D

^[[D

^C
[root@client02 /root]#
```

**kitty:**
```
[root@client02 /root]# echo $TERM
putty-256color
[root@client02 /root]# cat
^[[D

^[[1;5D

^C
[root@client02 /root]# tmux
[root@client02 /root]# echo $TERM
tmux-256color
[root@client02 /root]# cat
^[[D

^[[1;5D

^C
```

Maybe putty is broken? I don't know whats wrong :(

**Comment by chros73** [comment]
> It strangely works with kitty (never heard about kitty before) but not with putty

You're right, I can confirm your latest finding with putty 0.70 x64 (KiTTY works fine).

**Comment by sulydeni** [comment]
same here
