### ISSUE TITLE
Yank puts stray characters on tmux session

### ISSUE THREAD

**Issue by anmoljagetia** [tmux/tmux#97]
I am facing this problem on Ubuntu 15.04 with tmux 1.9. To reproduce, follow the following steps :

1. Press ` Prefix + [ ` to get into the selection mode.
2. press `ctrl + space` to start highlighting.
3.  Yank to the clipboard. (I use `y` key here, but I tried without the yank plugin, the bug still exists).
4.  press `ctrl + shift + v` or `Prefix + ]` to paste the copied content on the screen.
5. Repeat step `1`, `2,` `3`.

I am attaching a screenshot to give a better idea of what I mean.
![random](https://cloud.githubusercontent.com/assets/6505326/9564903/b8780c2e-4ea5-11e5-97d4-5366c77bcd34.png)

**Comment by nicm** [comment]
Use the right TERM for your terminal or turn off set-clipboard.

**Comment by anmoljagetia** [comment]
can you help me with the right TERM variable for `Ubuntu 15.04` running `gnome-terminal`. I've tried using a lot of things like `xterm`, `screen-256color`, `gnome-256color`.
![tmux_broken](https://cloud.githubusercontent.com/assets/6505326/9736488/147772c4-565f-11e5-8042-f7aaa290e792.png)

my tmux dotfiles can be found [here](https://github.com/anmoljagetia/dotfiles/blob/master/tmux/tmux.conf).

**Comment by nicm** [comment]
gnome outside tmux, screen inside tmux.

Or xterm outside tmux and turn off set-clipboard.

**Comment by anmoljagetia** [comment]
I have set them like that. When I run `echo $TERM` it outputs `xterm` and I have this line in my tmux.conf which sets the clipboard off (`set-option -s set-clipboard off`), but it still doesn't seem to solve the problem.

**Comment by nicm** [comment]
You have to have TERM=xterm outside tmux and TERM=screen inside tmux.

Turning set-clipboard off should fix the problem. What does "tmux show -s set-clipboard" show inside tmux?

**Comment by anmoljagetia** [comment]
running the command you gave inside tmux gives me `set-clipboard off` output. `echo $TERM` when tmux is not running gives `xterm` as output, and running inside tmux gives `screen`. I have the following lines in my .tmux.conf to set them : 
``` 
set -g default-terminal "screen"
set-option -s set-clipboard off
```

**Comment by nicm** [comment]
And you are still seeing exactly the same problem with the base64 characters overwriting the screen when you copy in copy mode?

**Comment by anmoljagetia** [comment]
okay thanks a lot! the base64 characters are completely gone now :)
However this new statusbar problem has come up, should I open a new issue for that?

**Comment by nicm** [comment]
So if you have a config containing exactly this and nothing else:

set -g default-terminal "screen"
set -s set-clipboard off

Then run:

tmux -Ltest new

Then "echo $TERM" shows "screen" and the problem occurs? What exactly is happening?

**Comment by anmoljagetia** [comment]
running this command opens a new tmux session inside the old one, with another bar at the bottom. The `echo $TERM` works well, as it should with `xterm` outside and screen inside.

**Comment by nicm** [comment]
No run it outside tmux and make sure you see the problem with exactly those 2 lines in your config and nothing else

-------- Original message --------

**Comment by anmoljagetia** [comment]
It works properly with just the two lines. I think some of the config is causing this problem?

**Comment by nicm** [comment]
Must be, does your status-left/status-right contain any UTF-8? Do you have utf8 and status-utf8 options turned on in tmux?

**Comment by anmoljagetia** [comment]
Yes, the UTF-8 are on, and the status works fine now. I think it is a broken script that I was running. I have removed my right status bar completely, and I can now work in the session, so it is all good now, thanks to you :)

**Comment by anmoljagetia** [comment]
And you were 100% correct, I had an heart icon in my right status bar, and as soon as I removed it, all things look well now :)

I can use other icons, but is there a way I can enable UTF-8 support for the status bar?

**Comment by nicm** [comment]
Yes make sure status-utf8 is on

**Comment by anmoljagetia** [comment]
The problem is definitely the UTF-8 character (a heart) that I am using to display my battery percentage. Unfortunately, I can't fix it, even after adding `set-option -g status-utf8 on` to my `.tmux.conf` file.

**Comment by nicm** [comment]
What Unicode code point is it?

**Comment by nicm** [comment]
Is it this http://www.fileformat.info/info/unicode/char/2764/index.htm?

This works fine for me:

$ cat .tmux.conf
set -g status-left '❤'
set -g status-right '❤'

Is it still a problem if you use tmux from git? What if you use uxterm or urxvt? Or a different font?

**Comment by anmoljagetia** [comment]
I tried using the powerline fonts (the ones that have modded characters inside), but even then the same problem persists. I have since then, resolved to using 'X' instead of hearts, but that is not the same thing, in my opinion. 
also, If I swap out 'x' for a ❤ it works while my machine has not rebooted, but once I reboot, it breaks again. I have a few special characters, like the git branch sign in my shell as well, but they usually work without causing a lot of problem. It works well in uxterm, I guess it is a problem with gnome-terminal then? (I am also having other stability issues with gnome-terminal as well).

**Comment by nicm** [comment]
Yes if it works in urxvt but not gnome-terminal with the same font then it is gnome-terminal problem.

**Comment by anmoljagetia** [comment]
I think that should be the case too. I will try using it in uxterm and try fixing the gnome-terminal setup. I'll post back here with whatever I observe. Thanks for your help :)
