### ISSUE TITLE
Wrapped character incorrectly written to display line above

### ISSUE THREAD

**Issue by nuao** [tmux/tmux#970]
I'm experiencing a strange wrapping error where a multi-byte character is written to the display line above.

I have an attached below utf-8 encoded file which has one line. Its content is the concatenation of 'a' + 79 spaces + 'ß'. I change the terminal window's width to 80 characters so that wrapping should force the 'ß' to appear on the next display line, directly under the 'a'.

Repeatedly calling cat, the output is at first displayed normally, and the prompt moves down the pane:

```
$ cat a_above_ss.txt
a
ß
$ cat a_above_ss.txt
a
ß

```
Now the prompt is on the final line at the bottom of the pane. But something odd happens:

```
$ cat a_above_ss.txt
ß

```
The 'ß' character is positioned on the line above, overwriting the character 'a'.

The problem seems to arise only when the prompt is on the bottom line, and resizing the window causes the output to redraw correctly.

If I replace 'ß' with a single-byte char such as 'z', there is no problem, but another multi-byte char such as '£' causes the same problem, replacing the 'a' above.

I'm using urxvt but also tried different terminals, and different fonts too. The problem occurs in all cases but only when using tmux. Reproduced using tmux from master without a configuration started as
```
$ tmux -vv -Ltest -f/dev/null new

$ uname -sp && tmux -V && echo $TERM

Linux unknown
tmux 2.5
screen-256color
```
Thanks for any help and for tmux in general.

[a_above_ss.txt](https://github.com/tmux/tmux/files/1066807/a_above_ss.txt)

**Comment by octoploid** [comment]
Also happens when running htop and scrolling down. At some point tmux stops scrolling the whole htop window and only overrides the last line.

**Comment by nicm** [comment]
Try this please:

~~~~
Index: screen-write.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/screen-write.c,v
retrieving revision 1.127
diff -u -p -r1.127 screen-write.c
--- screen-write.c	4 Jun 2017 08:02:20 -0000	1.127
+++ screen-write.c	12 Jun 2017 07:23:06 -0000
@@ -1339,8 +1339,10 @@ screen_write_cell(struct screen_write_ct
 
 	/* Check this will fit on the current line and wrap if not. */
 	if ((s->mode & MODE_WRAP) && s->cx > sx - width) {
+		log_debug("%s: wrapped at %u,%u", __func__, s->cx, s->cy);
 		screen_write_linefeed(ctx, 1, 8);
 		s->cx = 0;
+		screen_write_collect_flush(ctx, 1);
 	}
 
 	/* Sanity check cursor position. */

**Comment by octoploid** [comment]
The patch doesn't help:

[capture_smaller.mkv.zip](https://github.com/tmux/tmux/files/1067368/capture_smaller.mkv.zip)

**Comment by nicm** [comment]
Please don't hijack this issue with a different problem.

**Comment by nuao** [comment]
No problem at all now. The extra call to `screen_write_collect_flush` seems to fix it.

(and I'm aware your "hijack" comment is for someone else whose own comment is now deleted)

Thank you for your help.

**Comment by nuao** [comment]
No problem at all now. The extra call to `screen_write_collect_flush` seems to fix it.

(and I'm aware your "hijack" comment above is for someone else whose comment is now deleted)

Thank you for your help.

**Comment by nicm** [comment]
Good stuff, applied to OpenBSD now, will be in GitHub soon. Let me know if you see any further problems.
