### ISSUE TITLE
has-session behavior in tmux 2.5

### ISSUE THREAD

**Issue by adamstrickland** [tmux/tmux#971]
We're getting reports in <https://github.com/tmuxinator/tmuxinator> that tmuxinator is having compatibility issues with tmux 2.5.  I have traced it to an apparent change in behavior in the `has-session` command.  In <2.5, `has-session` returns a 1 if the targeted session does not exist.  It would appear that this is no longer the case? Was this expected?  If so, should we expect that in 2.5+ we should be prepared to accommodate?

**Comment by ThomasAdam** [comment]
What exactly are the reports?  This hasn't changed:

```
[~]{5581}[0] % tmux has -twork
[~]{5582}[0] % tmux has -twork2
can't find session work2
[1][~]{5583}[0] % echo $?
1
[~]{5584}[0] % 
```

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1069554/x.diff.txt)

**Comment by adamstrickland** [comment]
Applied patch; looks like a winner.  👍

**Comment by nicm** [comment]
Great, applied, thanks.

**Comment by adamstrickland** [comment]
@nicm One question: will this be applied to 2.5 (i.e. 2.5.1 or whatever), or just to master, meaning (presumably) to 2.6 and later? Just looking to provide guidance for `tmuxinator` users.

**Comment by nicm** [comment]
master then 2.6 and above.
