### ISSUE TITLE
after upgrading to tmux 2.5, selecting text in scrolled window scrolls to end

### ISSUE THREAD

**Issue by timotheecour** [tmux/tmux#973]
```
Linux unknown
tmux 2.5
screen
```

The fix for https://github.com/tmux/tmux/issues/337 doesn't seem to work after upgrading to tmux 2.5 from 2.3.

what command should i put in .tmux.conf to allow selecting text (so that it becomes in the clipboard) but not scrolling to the end ?

I tried:
```
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel -x "xclip -selection clipboard -i"

```

settings that worked in 2.3:
```
setw -g mode-keys vi
if-shell "uname | grep -q Darwin" "set -g default-command \"reattach-to-user-namespace -l ${SHELL}\"" " "
set -g mouse on
bind -t vi-copy MouseDragEnd1Pane copy-selection -x
```

**Comment by timotheecour** [comment]
this seems to work, not sure why we should skip `-x` now:

```
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection
```

**Comment by NgoHuy** [comment]
I try it but I cannot selection text or copy it, Can @timotheecour share me your configuration ?

**Comment by NgoHuy** [comment]
I used `bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "xclip -selection clipboard -i"` and it works fine

**Comment by fazlearefin** [comment]
`bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"` works fine for me.
