### ISSUE TITLE
F13 (S-F1) as prefix(2) broken in v2.5

### ISSUE THREAD

**Issue by pdf** [tmux/tmux#974]
Working in v2.4, but pressing key bound to F13 outputs various unexpected characters and does not trigger prefix on v2.5, with the following minimal tmux.conf:

```
set -g prefix2 S-F1
```

Item|Value
------|------
Platform | Linux (Arch)
Terminal Emulator | Konsole
$TERM (outside) | xterm-256color
$TERM (inside) | screen-256color
tmux -V | tmux 2.5

log output: https://gist.github.com/pdf/78acdadc87924c607db0a17c6fce2903

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1070502/x.diff.txt)

**Comment by pdf** [comment]
@nicm functionality is restored after applying this diff.

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later.
