### ISSUE TITLE
Tmux status line usage has regressed

### ISSUE THREAD

**Issue by purplefishies** [tmux/tmux#975]
Using the latest released tmux ( 2.5 ) or master if I try typing the following 

C-b :   
clear-history --help

I just see 
~~~
Invalid or unknown command: clear-history --help                                                                                               
~~~

whereas with tmux 2.2 I would see  
~~~
Usage: clear-history [-t target-pane]                                                                                                          
~~~

**Comment by purplefishies** [comment]
So the correction is that this difference no usage being displayed occurred between 2.3 and 2.4 versions of tmux

**Comment by nicm** [comment]
Should be fixed in OpenBSD now, will be in GitHub later. Thanks!
