### ISSUE TITLE
tmux high cpu usage on osx after update 2.3 > 2.5

### ISSUE THREAD

**Issue by ebenezar-mccoy** [tmux/tmux#976]
~ % uname -a
Darwin mbp.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
~ % tmux -V
tmux 2.5

tmux with default configuration

When i close terminal window with running tmux inside load jumps to 100% on tmux process, reattaching to sessions doesn't solve the problem.

When i deattach before quiting winow there is no issue.

This bug happend to me after upgrading from 2.3 to 2.5 thre brew upgrade tmux.

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by trdcaz** [comment]
Same as @ebenezar-mccoy said.

```bash
$ uname -a
Darwin Air.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

$ brew info tmux
tmux: stable 2.5 (bottled), HEAD

$ brew info libevent
libevent: stable 2.1.8 (bottled)
```

**Comment by trdcaz** [comment]
Append two log files:

client:
[tmux-client-14714.txt](https://github.com/tmux/tmux/files/1077467/tmux-client-14714.txt)

server:
[tmux-server-14716.txt](https://github.com/tmux/tmux/files/1077468/tmux-server-14716.txt)

**Comment by nicm** [comment]
These log files are from 2.5, not from master.

**Comment by Crazor** [comment]
I had the exact same issue as @trdcaz after I upgraded to tmux 2.5
FYI I can confirm that the issue doesn't occur with 07a1369.

**Comment by ebenezar-mccoy** [comment]
I can confirm, that installing this by brew install tmux --HEAD solved this issue.

thanks.
