### ISSUE TITLE
Give ability to display different terminals in the same pane (not at the same time)

### ISSUE THREAD

**Issue by purpleP** [tmux/tmux#979]
First of all - thanks for implementing incremental-search. Great feature.

I'd like to ask to implement a new feature based on the workflow I would like to achieve. So I will describe the problem I would like to be solved first and then the solution I see.

Suppose I'm writing some code that deals with database (suppose I use python, but any language with interpreter would suffice). To the job I need three terminals. One with vim, one with ipython (interpreter) and one with command line database client. Right now I achieve that with splitting window horizontally and then splitting window below vertically.

This, however creates problem if the initial terminal window wasn't that big (suppose I half of the screen was terminal and other half is web browser of just display isn't big enough).
So what I do instead in this situation is killing interpreter and opening command line database client in that pane. Or opening database client in another tmux window. Which isn't always what I want. And if you imagine that I also need to connect to some server at the same time, to see logs or something you can see that this workflow isn't optimal.

What would be more optimal is splitting terminal window in half. And then selecting the application you need at the moment. When you need interpreter - select running interperter to be displayed in the second pane. When you need database client - select database client etc.

So what I mean is tmux to be more like emacs or vim. Where window (pane in you terminology) is just a window that gives ability to see buffer (terminal in you terminology) and tabs (windows in your terminology) represent specific arrangements of windows. So you can see different buffers from the same window. Which translates to displaying different terminals in the same pane.

From the user perspective it wouldn't require to learn anything new for users that would use old style. All previous bindings etc can work. This just make the concept of pane more general so to speak.

**Comment by nicm** [comment]
You don't need to sell this idea, someone just needs to do it, but it is far from trivial.

**Comment by purpleP** [comment]
@nicm Why close the issue if you think that it's valid feature request?

**Comment by nicm** [comment]
We do not leave issues open unless something is happening. Nobody is going
to forget about this.

**Comment by nicm** [comment]
You can probably do much of what you want with swap-pane/join-pane BTW. You
just can't have the same pane in two places at once.

**Comment by purpleP** [comment]
@ncim Oh, okay. Thanks for suggestion, I'll try that.
