### ISSUE TITLE
Vim pop-up blinks in its first-window

### ISSUE THREAD

**Issue by demon386** [tmux/tmux#98]
##  Setup:
iTerm2  Build 2.99.20150626
tmux installed with `brew install tmux --HEAD`
Vim: latest Macvim's terminal version

## Phenomenon:
See screen record:
https://dl.dropboxusercontent.com/u/12474941/tmux_vim_popup_blinks.mp4

Vim's auto-completion pop-up window blinks in first window. This doesn't happen if I use Vim inside normal iTerm2 terminal, nor with Iterm2's intergartion with tmux (i.e. tmux -CC).

It only happens when I use tmux program inside iTerm2's normal terminal. The weird thing is that only in the first window of Vim it blinks.

I also experience blinks when using tmux inside OS X's Terminal program, but doesn't have this "first window only" property.

**Comment by nicm** [comment]
Does it happen without a .tmux.conf or .vimrc?

**Comment by demon386** [comment]
Just tried an empty .tmux.conf and a minimal .vimrc (With YouCompleteMe plugin because auto-completion pop-up was trigged by it.). It still blinks.

**Comment by nicm** [comment]
Does this happen in xterm?

**Comment by demon386** [comment]
I use Mac OS X.

**Comment by demon386** [comment]
This might be a problem of Vim:

https://groups.google.com/d/msg/vim_dev/KE7b3tXNmDU/DUMtFcgEBAAJ

I experience the same thing in OS X Terminal program without tmux.

But as stated, that doesn't happen in iTerm2 (without tmux).
