### ISSUE TITLE
Tmux with "zsh" will make zsh process never quit?

### ISSUE THREAD

**Issue by zxdposter** [tmux/tmux#980]
I use tmux in zsh, process "zsh" have been growing, 

![wx20170620-182140](https://user-images.githubusercontent.com/13846260/27328631-54e1682e-55e5-11e7-83c2-0cf8b508efb1.png)

I not so sure it will have same problem in bash, or cause by tmux or zsh itself.

So I try ask in here.

**Comment by nicm** [comment]
This issue does not include enough information. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by zxdposter** [comment]
@nicm 
Run this, with oh-my-zsh, will make orphan process.
`tmux -q -L swap-pane-test -f /dev/null new-session -d \; new-window \; new-window \; swap-pane -t :1 \; kill-session;`

**Comment by nicm** [comment]
tmux version?

**Comment by zxdposter** [comment]
@nicm version 2.5

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by zxdposter** [comment]
I install by brew, cannot know the which branch I user.
If use this, this situation will not happen， Pay attention to **set default-shell /bin/sh**.
`tmux -q -L swap-pane-test -f /dev/null new-session -d \; set default-shell /bin/sh \; new-window /bin/sh \; new-window /bin/sh \; swap-pane -t :1 \; kill-session;`
