### ISSUE TITLE
tmux newer than 2.3 doesn't display some lines of text

### ISSUE THREAD

**Issue by MirLach** [tmux/tmux#984]
After upgrading from tmux 2.3 to 2.4 or 2.5 I get randomly broken output of commands like "cat somefile.txt". Some lines are not displayed at all or are just blank lines. Tmux always worked for me for years, but I cannot use 2.4 nor 2.5. I tried tmux session without `tmux.conf` but no difference.

For example file `/var/log/pkg_upgrade.2017-06-26_15-36-32.txt` contains this on start (it is much longer than that)
```
root@pkgbuilder ~/ # /root/bin/pkg_upgrade.sh

pkgbuilder - 2017-06-26 standardni pkg upgrade z vlastniho poudriere

uname: FreeBSD 10.3-RELEASE-p18 amd64 GENERIC
pkg_abi: FreeBSD:10:amd64
pkg_version: 1.10.1
pkg_repos: codelab
codelab_repo_url: http://pkg.protected.tld/packages/10_3_amd64-default-global/
```
But `cat /var/log/pkg_upgrade.2017-06-26_15-36-32.txt` inside tmux sessions shows just

```
pkg_repos: codelab
codelab_repo_url: http://pkg.protected.tld/packages/10_3_amd64-default-global/
```
First 7 lines are missing.

If I put just these 10 lines in a file and run cat again, everything is displayed fine.

I am not alone with this problem on FreeBSD, it is discussed here: https://lists.freebsd.org/pipermail/freebsd-ports/2017-May/108611.html

OS: FreeBSD 10.3-RELEASE-p18 amd64 GENERIC

tmux version: 2.5
terminal outside: xterm
terminal inside: screen

Log of tmux sessions is attached, also file which exhibits this problem

[tmux-server-72032.log.txt](https://github.com/tmux/tmux/files/1102397/tmux-server-72032.log.txt)
[pkg_upgrade.2017-06-26_15-36-32.txt](https://github.com/tmux/tmux/files/1102398/pkg_upgrade.2017-06-26_15-36-32.txt)

**Comment by nicm** [comment]
What terminal are you using?

**Comment by MirLach** [comment]
I am connecting with Putty 0.67 from KDE 4.14 on FreeBSD 10.3 desktop (PC-BSD)

**Comment by nicm** [comment]
Show me a screenshot of the problem please.

**Comment by MirLach** [comment]
Here are some examples:
1) broken in tmux
![2017-06-26_broken_in_tmux](https://user-images.githubusercontent.com/10672697/27546036-d45934f0-5a91-11e7-9b80-9cf47ae583fd.png)

2) fine without tmux
![2017-06-26_fine_no_tmux](https://user-images.githubusercontent.com/10672697/27546038-d702d012-5a91-11e7-8bf5-d939363faaee.png)

The problem is not always at the beginning of the output. If text is long enough there are often many parts of text missing.

**Comment by nicm** [comment]
Are you scrolled up? You can't rely on the terminal scrollback to be complete when running in full terminal applications like tmux. Use tmux copy mode instead.

**Comment by MirLach** [comment]
Yes, I scrolled up. It is much faster to use mouse scroll wheel than anything else. And when I need to copy & paste a few hundreds of lines of text I have no other choice, just use scroll up & copy & paste. (copy mode doesn't allow me to do that, with copy mode I must copy & paste small parts of screen)

This exact usage worked without any issues for years in previous versions and even in "screen". So there must be something broken (incompatible change) in 2.4 / 2.5.

**Comment by nicm** [comment]
The way tmux redraws changed quite a lot after 2.3 and tmux will omit lines it does not need to draw.

**Comment by MirLach** [comment]
I still don't understand ... how tmux determines which lines can be omitted and how this is useful?

Does it mean that if I need this workflow I cannot use tmux anymore?

**Comment by nicm** [comment]
tmux only cares about what is displayed on the visible terminal, it has no control over the scrollback and it explicitly asks the terminal to turn it off by entering cursor positioning mode. You can't rely on what is in the scrollback when using tmux, because it may not be complete. It is much faster for tmux to drop lines that it doesn't need to display rather than sending them to the terminal.

If you want a terminal history with tmux you will need to use copy mode. You can configure it to work with the mouse.

**Comment by MirLach** [comment]
I tried ti find out how to configure tmux with mouse support, I found this settins but it doesn't work for me. (no errors, mouse is ignored)
```
set -g mouse on

bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "cat >/tmp/foo"
bind-key -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel "cat >/tmp/foo"
bind -n WheelUpPane copy-mode
```

I really don't like when something I used for years is now broken without any change on my side. I think I will stay on 2.3 for some time and eventually try `screen` again. Which is sad to me...

**Comment by mike402** [comment]
And why would you expect everyone to know of your "optimizations" from the start. Why would anyone need  this on a local machine -- introducing quirks instead of being a convenient transparent layer everyone is used to? Why not just make this optional for those who explicitly want it to happen, e.g. over SSH over a slow/overpriced mobile connection?

**Comment by scfarley** [comment]
I notice an unusual behavior when cat'ing pkg_upgrade.2017-06-26_15-36-32.txt (attached in issue submission) inside a tmux session on both FreeBSD and Linux.  Note that both sessions are inside a FreeBSD xterm in case that matters.  I execute xterm without a scrollbar and with zero save lines; everything is done via tmux's copy mode.

In FreeBSD, I see the following at the top of the screen:
```
to dyn
To load a module at runtime, include the new `load_module'
directive in the main context, specifying the path to the shared
object file for the module, enclosed in quotation marks.  When you
```

In Linux, I see the following at the top of the screen:
```
==================================
To load a module at runtime, include the new `load_module'
directive in the main context, specifying the path to the shared
object file for the module, enclosed in quotation marks.  When you
```

In both cases, the first line is wrong.  cat'ing the file in an xterm does not have the issue.  Entering copy mode fixes the display.  Exiting copy mode keeps the fixed display.  As long as the correct line to be displayed is short or empty, I see the issue.  If the correct line is larger than the incorrect line, it will be displayed correctly.

Currently, it is only that file for me where the discrepancy is apparent.

**Comment by user501254** [comment]
@nicm 
Would it be a possibly to include a setting specific to restore the behaviour prior to the changes?
I, like @MirLach strongly feel that some things are lot easier with the mouse wheel. For me it's copying text from the terminal to the clipboard directly.

**Comment by eguendelman** [comment]
I am also getting missing lines in tmux when connecting through ssh (but never when on a local machine).  And it doesn't just affect history buffer, I'm referring to lines that most certainly should be displayed.  Was this issue resolved or just closed?  Thanks

**Comment by MirLach** [comment]
It was just closed. I am using version 2.3 on all our machines.

**Comment by xoneill007** [comment]
Same here, had to go back to 2.3.  This option apparently no longer has a bearing on scrollback behavior (set -ga terminal-overrides ',xterm*:smcup@:rmcup@').
