### ISSUE TITLE
visual-silence logic is backward

### ISSUE THREAD

**Issue by townba** [tmux/tmux#985]
(Found on master with `.tmux.conf` setting `set -g visual-silence off`.) Looks like commit 899e629bf0bc6053112cec5b65a63f1dd2330001 accidentally inverted the meaning of the `visual-silence` setting in [`alerts.c`](https://github.com/tmux/tmux/blob/6995497e5b66e090f25e85fbb207f033f7790199/alerts.c).

[Before](https://github.com/tmux/tmux/blob/bc27451e156c0a4af73d016ea04827710ea70d5b/alerts.c#L269-L275):
```c
	if (options_get_number(s->options, "visual-silence")) {
		TAILQ_FOREACH(c, &clients, entry) {
			if (c->session != s)
				continue;
			status_message_set(c, "Silence in window %d", wl->idx);
		}
	}
```
[After](https://github.com/tmux/tmux/blob/6995497e5b66e090f25e85fbb207f033f7790199/alerts.c#L289-L290):
```c
		if (!options_get_number(s->options, "visual-silence"))
			alerts_set_message(s, "Silence in window %d", wl->idx);
```

**Comment by nicm** [comment]
Changed, thanks!
