### ISSUE TITLE
strange cursor with screen-256color in bash on ubuntu on windows terminal

### ISSUE THREAD

**Issue by candywater** [tmux/tmux#986]
> Linux x86_64
> tmux 2.5( the same problem in tmux 2.1 which is the default version in ubuntu 16.04)
> $TERM=screen-256color
> Description: Ubuntu 16.04.2 LTS

> here is the [tmux-server-*.log](https://gist.github.com/candywater/db860b2e69fdd3e8e4832920aff2245b)
> my [.zshrc file](https://gist.github.com/candywater/158b57212d6f8a055fbaa69f5d75af0e)
> my [.vimrc file](https://gist.github.com/candywater/5948198abfa5621f7aa141cd1bfc62b0)

---
after adding $TERM=screen-256color in .zshrc, the cursor in tmux become  "・" but not "_",
(but cursor in default terminal on win10 works well)
but if I do not change  $TERM, tmux works well.

---
for example, in the tmux, when I use vim,
cursor becomes a strange mark "・", and transforms char where cursor has stayed into "・" .
like the image below

![line_p2017628_161429](https://user-images.githubusercontent.com/12393438/27624747-01ddf5f0-5c1d-11e7-9694-b9a24be44e09.jpg)

but without tmux, vim works well 
---
the same problem in command line, 
what cursor is
![line_p2017628_161432](https://user-images.githubusercontent.com/12393438/27624938-c1f63a96-5c1d-11e7-9c4c-aca0fbb4307b.jpg)

and what it should be 

![line_p2017628_161434](https://user-images.githubusercontent.com/12393438/27624942-c7de63c0-5c1d-11e7-9ec2-c9cba9111dcd.jpg)
---

**Comment by nicm** [comment]
This seems like a bug in your terminal, tmux doesn't control how the cursor is drawn. Are you sure your terminal supports 256 colours?

**Comment by candywater** [comment]
I used [this one](https://gist.github.com/hSATAC/1095100) to make sure that 
my terminal can output all 256 colors, 
so I think my terminal supports 256 colors.
maybe this is not problem of tmux , but the bug of my terminal.
I'll try different way to avoid this problem.
thanks a lot.

**Comment by nicm** [comment]
I don't think tmux can be causing this, it will not be sending anything unusual and the logs look fine. I think it is your terminal.
