### ISSUE TITLE
Feature request: next-word-vi and next-word-end-vi commands for copy-mode-vi

### ISSUE THREAD

**Issue by Grazfather** [tmux/tmux#987]
tmux 2.4 on any platform

This has been broken as far as I can remember.

I use vi mode for text selection, but its w (`copy-mode-vi w` -> `send-keys -X next-word`) doesn't use the vim definition of a word.

In vim, if I am on the 's' in 'some_func()', hitting `w` will move to '('. In tmux, it'll move to 'f'. The next press of `w` will go past the end of the word to the end of ().

This is because the vi bindings still leverage the normal tmux commands, which use emacs semantics

Adding vim-style word-moving semantics command (e.g. `next-word-vi`) would be a great addition.

**Comment by nicm** [comment]
You can change word-separators option.

**Comment by Grazfather** [comment]
Indeed you can (I didn't know, now at least I can remove "_").

That still doesn't seem to work correctly. If I set it, for instance, to _only_ "-", it still won't navigate `this-test-case` properly: It moves to the "t", _not_ to the "-" as it should.

**Comment by nicm** [comment]
Yes it works like emacs. I am not opposed to adding further differences when in vi mode but I'm not planning to do it myself, someone familiar with vi will need to do it.

**Comment by Grazfather** [comment]
Fair enough. Not sure if the `next-word` should add a check for if it's in vi mode (It already does this check for something else) or if new commands should be added to provide the vi semantics, and have them bound by default in `copy-mode-vi`. I already have an idea about how it should be done, but haven't otherwise looked at the code before.

I renamed and edited the issue, hoping we can keep it as a feature request, and hoping someone can hop on it, otherwise I will take a look when I have the time.

**Comment by nicm** [comment]
It should have a check for MODEKEY_VI like the existing check in window_copy_cursor_next_word_end().

**Comment by nicm** [comment]
Please open a PR or send an email if you have a change.

**Comment by janderland** [comment]
For people searching for a solution to this "problem", from @Grazfather own [dotfiles](https://github.com/Grazfather/dotfiles/blob/master/tmux.conf)...

```
# Set the word separators to get closer to vim's
set-option -g word-separators " -()@.,[]{}:="
```
