### ISSUE TITLE
Introduce pane_pipe format variable

### ISSUE THREAD

**Issue by mkoskar** [tmux/tmux#990]
It would be nice to be able to see that ``pipe-pane`` is in progress for active pane.

I suggest new format variable:
```
pane_pipe (0 = pipe-pane is not-active / 1 = pipe-pane is active)
```

**Comment by nicm** [comment]
Added now to OpenBSD, will be in GitHub later.

**Comment by mkoskar** [comment]
Cool, Thanks!
