### ISSUE TITLE
pipe-pane output gets truncated when pane closes too fast

### ISSUE THREAD

**Issue by shym** [tmux/tmux#991]
I use a lot @tpope’s [vim-dispatch](/tpope/vim-dispatch) with tmux (I’m running tmux 2.5, debian gnu/linux package from unstable, version 2.5-2, usually in a rxvt-unicode-256color terminal).
This setup creates new panes just to run a command (so that the pane closes as soon as the command finishes) but it still logs its output to a file for later investigation when needed. So it relies on `pipe-pane` to log it, but the log gets randomly truncated.

To illustrate the problem, I checked launching in a new pane running a shell:

```
$ tmux pipe-pane "sleep 1s; wc -l > /tmp/log"; seq 10000; logout
```

and I get some random (and < 10000, obviously) number in log.

I expected obviously all the output to be piped to the command. Of course, in such cases that means that tmux has to wait for the command to finish reading.
(I think it would make more sense to keep the pane open while this happens than closing it as soon as the command ends.)

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1117148/x.diff.txt)

**Comment by shym** [comment]
Brilliant! It works for me!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later.  Thanks
