### ISSUE TITLE
visual block select + opposite corner doesn't work properly

### ISSUE THREAD

**Issue by dylnmc** [tmux/tmux#992]
steps to recreate bug:

1
--

set vi status-keys in ~/.tmux.conf

    set-option -g status-keys vi

2
--

go into visual block mode, move left/right (on a specific corner -- other corner works fine).

1. <kbd>prefix</kbd>`+`<kbd>[</kbd> ==> go into `copy-mode`

2. <kbd>shift</kbd>`+`<kbd>m</kbd> ==> go to middle of screen

3. <kbd>shift</kbd>`+`<kbd>v</kbd> ==> go into `copy-mode`/`select-line`

4. <kbd>k</kbd><kbd>k</kbd><kbd>k</kbd> ==> select three lines up, as well

5. <kbd>control</kbd>`+`<kbd>v</kbd> ==> go into `copy-mode`/`rectangle-toggle`

6. <kbd>h</kbd><kbd>h</kbd><kbd>h</kbd> **--OR**-- <kbd>l</kbd><kbd>l</kbd><kbd>l</kbd> ==> move left --OR-- right, resp.

If you move down in step **4** with <kbd>j</kbd><kbd>j</kbd><kbd>j</kbd> instead, then press <kbd>o</kbd> after step **5** to reproduce this.

---

It seems like there is a specific corner that does not update the rectangle visual mode.

3
--

screenshot:

![screenshot-wrong](https://ptpb.pw/Ubmu.png)

what it should look like (if you press <kbd>o</kbd><kbd>o</kbd>, it updates the boundary properly)

![screenshot-right](https://ptpb.pw/iEYi.png)

**Comment by amosbird** [comment]
same as visual line mode selection

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1259939/x.diff.txt)

**Comment by amosbird** [comment]
it works fine here. Both line mode and rectangle mode.

**Comment by nicm** [comment]
Applied now, thanks.
