### ISSUE TITLE
[Feature] Add buffer-modified hook

### ISSUE THREAD

**Issue by dasJ** [tmux/tmux#997]
When I modify a buffer, I want to run a hook (to copy it into my X11 clipboard).

Running tmux 2.5 on Arch Linux.

**Comment by nicm** [comment]
Yes... we could add one, but how are you modifying the buffers that the existing mechanisms are no good?

**Comment by dasJ** [comment]
I'm sorry. My termcap lacked `Ms`, so tmux never tried to use the clipbaord escape. My goal was to implement this via piping to xclip. However, fixing the termcap also fixed the problem
